### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by ozza** [laurent22/joplin#1]
hello,

i got an error after i executed

`sudo npm install -g joplin`

```
npm ERR! code 128
npm ERR! Command failed: /bin/git clone --depth=1 -q -b master https://github.com/laurent22/node-emoji.git /root/.npm/_cacache/tmp/git-clone-7a2d2726
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-7a2d2726': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-02T08_38_04_712Z-debug.log
```

so i managed to install with `--unsafe-perm` command. now i'm having 

`Error: Cannot find module '/usr/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node'`

error. i tried to remove node_modules directory under joplin and reinstall by `npm install`. still getting the same error. there is no binding directory under the lib folder by the way. 

do you have any idea?

(i'm running it on Fedora 25 (Korora))

**Comment by laurent22** [comment]
Hello,

Does it work if you install without sudo? Generally it's recommended to avoid using sudo when installing packages, even globally ([see here](https://docs.npmjs.com/getting-started/installing-npm-packages-globally) ).

There could be some issue with the permission of the npm install directory, please [see here](https://docs.npmjs.com/getting-started/fixing-npm-permissions) on how to fix them. Personally, I always go for Option 2 and set the install directory under `$HOME`. That way I don't need sudo and I know that the permissions are always correct.

Please give that a try and let me know if you're still having any issue.

**Comment by ozza** [comment]
hello,

it was a permission problem as you mentioned. i fixed it with the guide you sent and it's working now.

thanks!

**Comment by Happyfeet01** [comment]
Hello,

I have the same error. I try to install it with sudo but I get this error:
/root/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v57-linux-x64

I have no sqlite3 directory in node_modules, but why?

That's my system:
Ubuntu 16.04.3 LTS
Nodejs 8.9.3
