### ISSUE TITLE
Add support for markdown task lists 

### ISSUE THREAD

**Issue by jeanm** [laurent22/joplin#10]
Would be great to have support for the "task list items" extension of GitHub Flavoured Markdown:

```
- [x] foo
  - [ ] bar
  - [x] baz
- [ ] bim
```

<https://github.github.com/gfm/#task-list-items-extension->

**Comment by laurent22** [comment]
You can already do this, if you create checkboxes it will be converted in the renderer:

![capture](https://user-images.githubusercontent.com/1285584/33692518-8c868086-dae5-11e7-9103-d3a59ca69678.PNG)

You can also click a checkbox to switch it on and off.

**Comment by jeanm** [comment]
@laurent22 you're right, I hadn't realised that with a dash they work. However they don't work when the list marker is an asterisk or a plus:
```markdown
* test
* [ ] test

+ [ ] test
+ [x] test
+ test
```
