### ISSUE TITLE
voci record/dictation

### ISSUE THREAD

**Issue by smokinjo** [laurent22/joplin#100]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [X ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ X] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

It would be interesting to be able to use the voice dictation service of Google to speak/record the tasks we want.

**Comment by laurent22** [comment]
That might be out-of-scope as built-in dictation support should not be necessary since these services should work with any text field.
