### ISSUE TITLE
Desktop: Performance: Viewer rerenders 2-3 times when switching notes

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#10008]
### Operating system

Linux

### Joplin version

2.14.16

### Desktop version info

Joplin 2.14.16 (dev, linux)

Client ID: 44da07c87ebf4662aa0e0f97f77f7f38
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: c2c2b61a5 (pr/fix-performance-close-viewer-issue-2)

Backup: 1.4.0

### Current behaviour

1. Apply the following diff
```diff
diff --git a/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v5/CodeMirror.tsx b/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v5/CodeMirror.tsx
index 5e9647758..218e04040 100644
--- a/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v5/CodeMirror.tsx
+++ b/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v5/CodeMirror.tsx
@@ -620,6 +620,8 @@ function CodeMirror(props: NoteBodyEditorProps, ref: ForwardedRef<NoteBodyEditor
 				bodyToRender = `<i>${_('This note has no content. Click on "%s" to toggle the editor and edit the note.', _('Layout'))}</i>`;
 			}
 
+			console.log('rerender');
+
 			const result = await props.markupToHtml(props.contentMarkupLanguage, bodyToRender, markupRenderOptions({
 				resourceInfos: props.resourceInfos,
 				contentMaxWidth: props.contentMaxWidth,
diff --git a/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/CodeMirror.tsx b/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/CodeMirror.tsx
index 2a99f1595..30b6ce8f7 100644
--- a/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/CodeMirror.tsx
+++ b/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/CodeMirror.tsx
@@ -228,6 +228,8 @@ const CodeMirror = (props: NoteBodyEditorProps, ref: ForwardedRef<NoteBodyEditor
 				bodyToRender = `<i>${_('This note has no content. Click on "%s" to toggle the editor and edit the note.', _('Layout'))}</i>`;
 			}
 
+			console.log('rerender (v6)');
+
 			const result = await props.markupToHtml(props.contentMarkupLanguage, bodyToRender, markupRenderOptions({
 				resourceInfos: props.resourceInfos,
 				contentMaxWidth: props.contentMaxWidth,

```
2. Open the developer tools > Console, then filter by `rerender`
3. Open the legacy markdown editor
4. Switch notes
5. Switch notes again
6. Repeat steps 3-5 for the beta markdown editor

Currently, `rerender` is logged 2-3 times for each switch between notes.

### Expected behaviour

`rerender` should only be logged once when switching notes.

**Comment by Sanket-0510** [comment]
This is how it is rendering

[Screencast from 2024-02-27 17-30-30.webm](https://github.com/laurent22/joplin/assets/104385297/3b721934-8211-462f-95d2-654764a52895)
 
from the comment - https://github.com/laurent22/joplin/blob/afedc5335494e5f86b4a3291904b4f7b9364982f/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v5/CodeMirror.tsx#L636C1-L642C2
 it is clear that it will render for atleast 2 times. But right now it is rendering thrice and the only variable causing an extra rendering on the initial mount is `resourcesInfo`  removing that from the array does the job, but I am not sure how much resourcesInfo string has effect on our function. memotising resourcesInfo can be  an option I tried but that did not work. But as of now eliminating `props.resourcesInfo` from - https://github.com/laurent22/joplin/blob/afedc5335494e5f86b4a3291904b4f7b9364982f/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v5/CodeMirror.tsx#L650    
does the job 

[Screencast from 2024-02-27 17-24-06.webm](https://github.com/laurent22/joplin/assets/104385297/547a2490-5fce-434c-9823-cc5c7b04bba4)

**Comment by personalizedrefrigerator** [comment]
> from the comment - https://github.com/laurent22/joplin/blob/afedc5335494e5f86b4a3291904b4f7b9364982f/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v5/CodeMirror.tsx#L636C1-L642C2

I missed that! I'm closing this until I check whether this really is a performance issue (e.g. multiple renders are started before the first one can finish and cache its result).

Thank you for looking into this!
