### ISSUE TITLE
Desktop: Beta editor: Toggle comment command does nothing

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#10007]
### Operating system

Linux

### Joplin version

2.14.16

### Desktop version info

Joplin 2.14.16 (dev, linux)

Client ID: 44da07c87ebf4662aa0e0f97f77f7f38
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: c2c2b61a5 (pr/fix-performance-close-viewer-issue-2)

Backup: 1.4.0

### Current behaviour

1. Enable the editor beta
2. Switch to the markdown editor
3. Select text
4. Go to `Edit > Toggle comment`
5. Compare to behavior in the legacy editor

### Expected behaviour

The text should be commented or uncommented.

**Comment by criticic** [comment]
can reproduce, and also note duplicate line, delete line, sort selected lines also does not work.


I have fixed the toggle comment bug, should I also fix the other ones, and open a PR?

**Comment by PackElend** [comment]
> should I also fix the other ones, and open a PR?

if you haven't done yet, yes, would be appreciated

**Comment by criticic** [comment]
I have now implemented all 4 in the same PR, rest of the options in the Edit Menu were working as far as I checked, if there is any other command that is not working, kindly let me know.
