### ISSUE TITLE
Clicking H2 menu item in rich text editor causes all of the text to display as headers

### ISSUE THREAD

**Issue by rloski-public** [laurent22/joplin#10019]
### Operating system

Windows

### Joplin version

2.13.15 (prod Win32)

### Desktop version info

Joplin 2.13.15 (prod, win32)

Client ID: 525b0700fc9c489a935cde87015c2339
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 7d2c1c0

Agenda: 3.7.1
Combine notes: 1.2.1
Email Plugin: 1.0.0
Embed Search: 2.0.0
Favorites: 1.3.2
Hotfolder: 1.1.0
Inline TODO: 1.7.0
Quick Move: 1.1.0
Templates: 2.4.0

### Current behaviour

1. I am editing file like the attached.  
[BaseMarkdown.txt](https://github.com/laurent22/joplin/files/14435623/BaseMarkdown.txt)
2. The Markdown and Richtext look like this:  
![BeforeClickH2](https://github.com/laurent22/joplin/assets/100482635/ad32872b-182e-4473-80dd-29fe5a9b2d24)
3. I return to just the Richtext editor and click H2 on the Paragraph to Change.  The cursor is somewhere in the paragraph.
4. Sometimes (today about every other time) the Richtext editor displays bolding on all lines like the image:  
![AfterClickH2](https://github.com/laurent22/joplin/assets/100482635/2b0accad-f9f7-4c15-831b-40aeb8781817)
5. I checked Markdown, and both Markdown and Richtext look the way that they should:  
![AfterClickH2WMarkdown](https://github.com/laurent22/joplin/assets/100482635/4b78f6c3-f17e-47bd-bbce-fe99b0b53ec7)
6. I close Markdown and the Richtext looks correct.

### Expected behaviour

I expect only the line I applied H2 to to change

**Comment by tarunsinghofficial** [comment]
I would Like to work on this issue. Please assign it to me. Thanks and happy coding!

**Comment by PackElend** [comment]
Feel free and may read the instructions, live blog again 😉
