### ISSUE TITLE
Toggle External Editing STOP button overlaps the BOLD button in Rich Text Editor

### ISSUE THREAD

**Issue by tarunsinghofficial** [laurent22/joplin#10025]
### Operating system

Windows

### Joplin version

2.13.15

### Desktop version info

**Joplin 2.13.15 (prod, win32)

Client ID: 34c17e21a1b64929a62e6d4ae8e26691
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 7d2c1c0**

### Current behaviour

1. When I click the **Toggle external editing**, the STOP button overlaps the Bold button.
![image](https://github.com/laurent22/joplin/assets/62840625/cc1a48a6-8bc0-4ed1-b2c4-c98353ad484b)

### Expected behaviour

There should be no overlapping between the buttons, and proper spacing should be provided.

**Comment by tarunsinghofficial** [comment]
I would love to work on the issue, so please assign the issue to me. Thanks

**Comment by personalizedrefrigerator** [comment]
> I would love to work on the issue, so please assign the issue to me. Thanks

Feel free to work on this without being assigned. (We generally don't assign issues to non-core-team members).

For reference, this is roughly where the button is added to the UI in the code:

https://github.com/laurent22/joplin/blob/bd5b3feabeeed301c313df437423ce1760c21d99/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx#L1266-L1280

**Comment by tarunsinghofficial** [comment]
Sure. Thanks for letting me know.

**Comment by tarunsinghofficial** [comment]
> Sure. Thanks for letting me know.

Can you please let me know, where are the styles of these toolbar, and where is the toolbar buttons?

Also, how can I see the changes like is there any way to reload the application to see the changes?
