### ISSUE TITLE
Email-to-note: Some image attachments not downloading

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#10027]
### Operating system

iOS

### Joplin version

2.13.10

### Current behaviour

Currently, image attachments may fail to download under some circumstances.

See https://discourse.joplinapp.org/t/feature-request-for-joplin-cloud-mail-with-attachment/36295/10

**Comment by IvoA1975** [comment]
Thnx for adding this issue, if anybody has questions on the specific situation , feel free to ask. I am currently experiencing the problem.

**Comment by criticic** [comment]
Is there a way to reproduce this issue consistently?

**Comment by IvoA1975** [comment]
For me it havens every time. Probably because I use Outlook?
It happens on both iOS and Linux . On iOS, I use an iPhone 14 and an iPad Pro with M1 chip.  All sync with Joplin Cloud.

**Comment by IvoA1975** [comment]
Hi,

Thanks all for your effort, this issue has been successfully resolved.

Kind regards, Ivo
