### ISSUE TITLE
Scrambled Screen on Ubuntu with AMD 7600 graphic card

### ISSUE THREAD

**Issue by anttonis** [laurent22/joplin#10028]
### Operating system

Linux

### Joplin version

2.13.15

### Desktop version info

Using Ubuntu 22.04. After opening I get this. My guess is browser is set as hardware acceleration. I have seen this before and after turning it off (added a graphic card in first) it was fine with CPU graphic AMD 7600.
![image](https://github.com/laurent22/joplin/assets/8221886/6db3291b-e067-4840-9080-51dfd2a643f7)

### Current behaviour

1. Run the app and that is it

**Comment by personalizedrefrigerator** [comment]
[This comment (though related to NVIDIA graphics)](https://github.com/laurent22/joplin/issues/9735#issuecomment-1962440067) suggests that this issue may be related to XWayland apps. Something to try might be [starting Joplin in Wayland mode](https://github.com/laurent22/joplin/issues/9735#issuecomment-1900782003).
