### ISSUE TITLE
Editor font size and font family settings are not applied to RTE

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10036]
### Operating system

Windows

### Joplin version

2.14

### Expected behaviour

- Change the editor font size or font family in the settings

=> Change is applied to Markdown editor but not to RTE (I think there may be a good reason for this, but if so we should document it)

**Comment by criticic** [comment]
The RTE Editor uses the style values obtained from the renderer/noteStyle.ts ie the same one used in the md preview.
And that also does not use the editor font size (though it makes sense here).
