### ISSUE TITLE
FR: Journal Note

### ISSUE THREAD

**Issue by gerroon** [laurent22/joplin#1003]
Hi

We have regular note, todo note atm. It would be very nice if there is one more note that is journal note which names the note based on the date (and the time) automatically. Optionaly these notes could be created under a specially designed Notebook.

This is different than sorting based on dates or such. I am specifically talking about naming the notes based on current date.

thanks

**Comment by takacsot** [comment]
You could use you computer to do it almost automatically. In all op system there are tools for inserting current date automatically:

- windows: ahk (if only free is interested)
- linux: autokey
- macos: built in, or aText or anything similar.

What I am doing:

1. create note
2. press the shortcut -> current date and time "magically" appearing as the title.

**Comment by gerroon** [comment]
f@@@@@k you @stable bot
