### ISSUE TITLE
Corrupted syncInfoCache would crash the app on startup

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10030]
### Operating system

Windows

### Joplin version

2.14

### Current behaviour

I don't understand how it could happen but if the syncInfoCache setting value is corrupted, the app crashes on startup.

![image](https://github.com/laurent22/joplin/assets/1285584/ff6d7f8b-0c97-493a-a013-43b32eb563ea)

ref: https://discourse.joplinapp.org/t/fatal-error-unterminated-string-in-json-at-position-4423/36354/2

**Comment by pedr** [comment]
- At least not crash, take a look what can be done (probably can't delete and get another from server)
