### ISSUE TITLE
Android: Can not to use editer

### ISSUE THREAD

**Issue by Byvm815** [laurent22/joplin#10034]
### Operating system

Android 9, qualcomm855

### Joplin version

2.14.x

### info

![S40302-12165988](https://github.com/laurent22/joplin/assets/99241417/f01b6e6a-b218-4133-a0f0-c95d193ee7c3)
When I want to edit my note, the editer is losed
![S40302-12170565](https://github.com/laurent22/joplin/assets/99241417/d2922828-2253-4913-8242-2e8743ec1ea4)

Bugs have been around since 2.14.x

**Comment by personalizedrefrigerator** [comment]
Hi,

We'll likely need a bit more information to help with this:
- Logs: To get these, go to "Configuration", then "Tools", "Log". Probably only note editor logs are relevant here, so click the search button and filter by "Note".
- Joplin version: There are several Joplin 2.14.x versions. To determine which one, go to "Configuration", then click "More information". 

Note that going to the app store on your device and updating an "Android System WebView" app may fix the issue.

Thank you for reporting this!

**Comment by Byvm815** [comment]
1. installed System WebView, it is not usefull
2. 2.14.x is all of 2.14 version(Yes, I tested all 2.14 version from F-droid). 
3. version 2.13.x is no problem(tested for all 2.13 version)

**Comment by Byvm815** [comment]
[mobile-log(1).log](https://github.com/laurent22/joplin/files/14471538/mobile-log.1.log)

**Comment by Byvm815** [comment]
I tested 2.14.8 version on another mobile phone(Android 7), BUG can be reproduced

**Comment by personalizedrefrigerator** [comment]
Thank you for the additional information!

I haven't been able to reproduce this on Android 7 (Joplin from the Play Store) or 13 (Joplin 2.14.8 from FDroid).

Does the "draw picture" option work? (It also uses a `WebView`).

Until this is fixed, a temporary option could be to use the legacy plain text editor. To do this, go to Configuration > Note > Use the plain text editor. Not all editor features will be available.

> [!NOTE]
>
> For context, the note viewer, editor, and "draw picture" screens all use `WebView`s. In the past, the note editor (based on CodeMirror) has used features that aren't available in older `WebView` versions.
>

**Comment by Byvm815** [comment]
***Use the plain text editor***, think you for telling me about this option. Now, I can edit my note with mobile phone😊

**Comment by Byvm815** [comment]
I do not find any option about ***draw picture***, Could you elaborate on that?

**Comment by Byvm815** [comment]
1. android 7 can not find any version about webview
2. android 9 webview version is 70.0
3. I tested 2.14.8 in android 14, editer is works. And android 11 webview version is 117.0

**Comment by Byvm815** [comment]
If the newer version(joplin) does not need to be compatible with the older webview version, issue can be close, I can ***Use the plain text editor***

**Comment by personalizedrefrigerator** [comment]
> android 9 webview version is 70.0

Thank you for that information! I think this corresponds to [Chrome version 70](https://developer.chrome.com/blog/new-in-chrome-70/).  

Note that updating "Chrome" may also fix the issue (but only if it's already installed).

> I do not find any option about draw picture, Could you elaborate on that?

After opening a note, it should be the option just below "Attach..." in the note menu (top right corner of the screen).

**Comment by Byvm815** [comment]
1. draw picture works in the same condition as editor (2.14.8)
2. updating "Chrome" can not fix the issue

**Comment by Byvm815** [comment]
I tested 2.14.9 on Android 9, bug has been fixed. but I do not find any commit about #10034.

**Comment by personalizedrefrigerator** [comment]
> I tested 2.14.9 on Android9, bug has been fixed. but I do not find any commit about https://github.com/laurent22/joplin/issues/10034.

It's possible [this commit](https://github.com/laurent22/joplin/commit/ea6b704754439c78e69bab8cda153aefbe956105) fixed the issue. According to [the changelog](https://joplinapp.org/help/about/changelog/android/#android-v2149-pre-release---2024-02-26t195611z), the earliest Android version it was in was [android-v2.14.9](https://github.com/laurent22/joplin/releases/tag/android-v2.14.9). (I had incorrectly assumed it was in 2.14.8).

Thank you again for reporting this! (And for the information about "draw picture" not working in older Android versions.)
