### ISSUE TITLE
iOS: Autocorrect inserts 2 line breaks.

### ISSUE THREAD

**Issue by itzTheMeow** [laurent22/joplin#10043]
### Operating system

iOS

### Joplin version

12.14.6

### Current behaviour

When typing in the note editor and the last word on the line is spelled incorrectly (autocorrect) pressing return inserts 2 line breaks and does not autocorrect the word
Screen recording explains it better

https://github.com/laurent22/joplin/assets/50887230/c87bb682-e719-48d6-84de-7bd9ac9922da

### Expected behaviour

Instead of inserting 2 new lines it should autocorrect the word and insert 1 new line

**Comment by itzTheMeow** [comment]
Not sure if this is a CodeMirror problem.

**Comment by personalizedrefrigerator** [comment]
What version of iOS are you using?

**Edit**: I can reproduce this on iOS 17.3.1. I suspect it's a CodeMirror issue -- [I'm posting a link to a CodeMirror demo](https://codemirror.net/try/?c=aW1wb3J0IHtiYXNpY1NldHVwLCBFZGl0b3JWaWV3fSBmcm9tICJjb2RlbWlycm9yIgppbXBvcnQge21hcmtkb3dufSBmcm9tICJAY29kZW1pcnJvci9sYW5nLW1hcmtkb3duIgppbXBvcnQge2xhbmd1YWdlc30gZnJvbSAiQGNvZGVtaXJyb3IvbGFuZ3VhZ2UtZGF0YSIKCi8vIFRoZSBNYXJrZG93biBwYXJzZXIgd2lsbCBkeW5hbWljYWxseSBsb2FkIHBhcnNlcnMKLy8gZm9yIGNvZGUgYmxvY2tzLCB1c2luZyBAY29kZW1pcnJvci9sYW5ndWFnZS1kYXRhIHRvCi8vIGxvb2sgdXAgdGhlIGFwcHJvcHJpYXRlIGR5bmFtaWMgaW1wb3J0LgpsZXQgdmlldyA9IG5ldyBFZGl0b3JWaWV3KHsKICBkb2M6ICItIFsgXSBUZXNzdCIsCiAgZXh0ZW5zaW9uczogWwogICAgYmFzaWNTZXR1cCwKICAgIG1hcmtkb3duKHtjb2RlTGFuZ3VhZ2VzOiBsYW5ndWFnZXN9KSwKICAgIEVkaXRvclZpZXcuY29udGVudEF0dHJpYnV0ZXMub2YoewogICAgICAgIGF1dG9jYXBpdGFsaXplOiAnc2VudGVuY2UnLAogICAgICAgIGF1dG9jb3JyZWN0OiAndHJ1ZScsCiAgICAgICAgc3BlbGxjaGVjazogJ3RydWUnLAogICAgfSksCiAgXSwKICBwYXJlbnQ6IGRvY3VtZW50LmJvZHkKfSkK) that may help verify this.

**Comment by itzTheMeow** [comment]
yep, iOS 17.3.1 on an iPhone 12

**Comment by itzTheMeow** [comment]
Yes also seems to be same behavior on the demo page. I'll create a code mirror issue. Should this one stay open?

**Comment by itzTheMeow** [comment]
https://github.com/codemirror/dev/issues/1349

**Comment by personalizedrefrigerator** [comment]
>  Should this one stay open?

Yes, please keep this issue open.

**Comment by itzTheMeow** [comment]
Looks like it's fixed, just waiting for the author to tag a version.
