### ISSUE TITLE
UI displays abnormally in some themes

### ISSUE THREAD

**Issue by oiabtt** [laurent22/joplin#10044]
### Operating system

macOS

### Joplin version

2.14.17

### Desktop version info

Joplin 2.14.17 (prod, darwin)

Client ID: *
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: 094175c

Backup: 1.4.0

### Current behaviour

Table menu displays abnormally. The options such as cell, row, column, etc., are not clear to see.

![3cfef825262340b1820a6803795b17d7](https://github.com/laurent22/joplin/assets/45990280/bf52faa0-ef06-4403-8037-34f031c680ca)

**Comment by personalizedrefrigerator** [comment]
I can reproduce this on Ubuntu 23.10.
