### ISSUE TITLE
Windows 10: Notebook list not showing up

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#10041]
### Operating system

Windows

### Joplin version

2.14.17

### Desktop version info

Joplin 2.14.17 (prod, win32)

ID client : eb2360f4f46448e6a1a4a49ff41397ec
Version de Synchro : 3
Version du profil : 46
Trousseau supporté : Oui

Révision : 094175c

Backup: 1.4.0

### Current behaviour

1. Standard installation of Joplin on Windows 10
2. Default "Welcome" notebook not showing up
3. Creating a new notbook is doing nothing

Note : When syncing with WebDav (other clients of Joplin on Linux and Android already in use connected), the online content seems to be uploaded on the Windows Laptop successfully but not showing up, and locally created notebooks (invisible on Windows) are uploaded to my drive. I think it is really a display issue making Joplin unusable for me on Windows.

![image](https://github.com/laurent22/joplin/assets/89936433/e31cc488-4010-4a2e-80db-cb782a95ff3d)

![image](https://github.com/laurent22/joplin/assets/89936433/81fd1710-24c3-4832-84a4-47073cca1cd0)
(Screenshot of sucessfully synced client, but nothing showing up)

### Expected behaviour

Sucessfully display notebooks

**Comment by personalizedrefrigerator** [comment]
Here are some things to try:
- Clicking on "CARNETS" in the sidebar.
- Searching for a word known to be present in the welcome notes -- do notes still show up in the search results?

**Comment by ghost** [comment]
No, but I managed to make it work, I think it was a mix of misconfiguration and old config files of removed Joplin app still breaking the app when trying to make a clean install...

For the record : Connected to a Nextcloud Drive with the Nextcloud config

If you had the same bug than me, instead of uninstalling / reinstalling (which doesn't work, the old parameters will still be there), just go in "Tools > Options > Synchronisation > Show Advanced Settings > Delete local data and re-download from sync target".

This made the trick for me. Have a nice day :)

![image](https://github.com/laurent22/joplin/assets/89936433/6e1cdd9e-0c49-47ff-89e6-46496ea88a63)
