### ISSUE TITLE
Default backup plugin shows an error message if there's nothing to backup

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10046]
- Start the app with a brand new profile (run with --no-welcome to prevent the creation of the welcome notes)

=> An error is displayed from the Backup plugin:

<img width="352" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/4f331965-b3b0-4b3e-8e93-d5c3a804ce64">

Since the backup happens in the background, this error (which is not really an error) should not be displayed. It could however be displayed when the user manually creates a backup.

**Comment by NamanKothari5** [comment]
@PackElend  a possible fix to this issue could be adding some flag for a **New User** or by identifying the context of the backup i.e. whether it is **manual** or **automatic**. It will be really helpful if you could point me to the relevant section in the code.

**Comment by PackElend** [comment]
I'm not familiar with the code base but you can ask around in the forum or Discord

**Comment by JackGruber** [comment]
Fixed in commit https://github.com/JackGruber/joplin-plugin-backup/commit/13ee4897d16bc5df99709888d5a456b22e505b83

**Comment by laurent22** [comment]
Thanks @JackGruber!
