### ISSUE TITLE
One or more master keys need a password message 

### ISSUE THREAD

**Issue by slicingmelon** [laurent22/joplin#10057]
### Operating system

Windows

### Joplin version

2.4.17 

### Desktop version info

Joplin 2.4.17 (windows)

### Current behaviour

For the past few months I am still seeing this message
`One or more master keys need a password` `Set the password`

![image](https://github.com/laurent22/joplin/assets/57750222/77889a08-4bf2-40d3-a1a0-bae76d77eb38)

When I click Set the password, I get to the Encryption Settings, and it looks like this

![image](https://github.com/laurent22/joplin/assets/57750222/1225f47a-79cc-496c-8f20-f6b4e12be3d3)

![image](https://github.com/laurent22/joplin/assets/57750222/1309c462-8af9-4758-b539-25937bcb0b37)

Regarding Missing Keys, the key with the ID shown in the screenshot above is not present in the full list of encryption keys. 

I am running a self-deployment of Joplin server for collaboration purposes, but I've never logged in on more than one device. 

### Expected behaviour

I expect that message to disappear, or to help me out to resolve this problem.

**Comment by personalizedrefrigerator** [comment]
Are there any keys in the list of disabled keys? (See the "Show disabled keys" link below the decryption keys table)
