### ISSUE TITLE
Android Sync Message Will not Clear

### ISSUE THREAD

**Issue by sepetersen** [laurent22/joplin#10052]
### Operating system

Android

### Joplin version

2.14.9

### Current behaviour

1. Synchronized with local file system
2. Received banner message at top of all screens:  Some items cannot be synchronized.
3. More info from banner lists two notes and their too-large attachments
4. Removed notes
5. Attachments are not in .resource
6. Re-synchronized
7. Message persists

### Expected behaviour

Expected no sync errors/banner after removing the offending notes

### Logs

[syncReport-1709607436057.txt](https://github.com/laurent22/joplin/files/14489826/syncReport-1709607436057.txt)

Screenshot with banner and notes information:
![Screenshot_20240304_212812_Joplin](https://github.com/laurent22/joplin/assets/52665036/0978fc2b-0165-4585-8fa6-701badf67db4)

**Comment by luisriverag** [comment]
Same here. 2.14.9. Deleted notes remotely, confirmed sync in another computer + iPhone. Issue persists on Android. Clicking on refresh/retry doesn't seem to trigger anything.



![Screenshot from 2024-03-05 16-54-17](https://github.com/laurent22/joplin/assets/2425973/bdd9c74b-eb80-4dd7-9caa-24a7a6595bc2)

**Comment by sneira** [comment]
I'm getting the same error message with 2.14.9. Problem is, I can't find the file or the resource anywhere in Joplin. I have tried searching the name and the ID in both the Android and the desktop apps with no results. I keep backups of the last 14 days created by the Backup plugin, and it's not in them either. I do recognize the file, though - it's an ebook I read (and probably tried to send to my phone via Joplin) two years ago. I've attached today's log for the Android app.

![600d757019874d099fed57bc7a9ab11b](https://github.com/laurent22/joplin/assets/4180520/a2ccccd5-f7f3-4563-ad10-bfe078ab0913)

[mobile-log.log](https://github.com/laurent22/joplin/files/14513053/mobile-log.log)

**Comment by luisriverag** [comment]
I'm now experiencing the issue on iPhone, same 3 notes that I deleted over a week ago

**Comment by luisriverag** [comment]
I've changed sync history to 1day on all devices including Mac and Ubuntu, 48h later error persists on Android and iPhone

**Comment by luisriverag** [comment]
I've uninstalled + re-synced iPhone app and banner seems gone. Uninstalling Android app now, will let you know how it goes

**Comment by luisriverag** [comment]
Apologies for the delay following up. Android message gone, workaround confirmed. If you encounter the bug after deleting resources and dont want to wait for a fix you can uninstall, reinstall and resync

**Comment by laurent22** [comment]
Fixed in 03c3feef1680e6e9bd3ebd1a8f60bbee3447a739
