### ISSUE TITLE
OCR does not start for German users

### ISSUE THREAD

**Issue by wginolas** [laurent22/joplin#10058]
### Operating system

Linux

### Joplin version

2.14.27

### Desktop version info

```
Joplin 2.14.17 (prod, linux)

Client-ID: 35d72068ef8a4731a01eb95cceeb5fd6
Sync-Version: 3
Profil-Version: 46
Unterstützter Schlüsselbund: Nein

Revision: 094175c

ABC Sheet Music Plugin: 1.0.4
Automatic Backlinks to note: 3.0.3
Backup: 1.4.0
Hotfolder: 1.1.1
LanguageTool integration: 0.1.0
Quick Links: 1.3.0
```

### Current behaviour

1. Use German translation of Joplin
2. Enable OCR
3. See this message in the dev tools
![grafik](https://github.com/laurent22/joplin/assets/1014026/e1d98948-96de-40de-800c-f9806deda9e8)

4. Set language to English
5. Restart Joplin
6. OCR now works \o/

**Comment by laurent22** [comment]
Well German language somehow didn't make it to our ISO-639 list, I'm going to add this.

**Comment by Rolograaf** [comment]
> Well German language somehow didn't make it to our ISO-639 list, I'm going to add this.

Could you add Dutch as well please? Was wondering why it did not work for me

> Uncaught (in promise) Error: Cannot convert to ISO-639 code: nl

**Comment by laurent22** [comment]
I can't believe so many languages are missing. As I remember I copied that list from somewhere else. I'll look and try to see what's missing, thank you for the report
