### ISSUE TITLE
A non-synchronised item cannot be found

### ISSUE THREAD

**Issue by robe070** [laurent22/joplin#10068]
### Operating system

Windows

### Joplin version

2.14.17

### Desktop version info

Joplin 2.14.17 (prod, win32)

Client ID: 426797a29eb04d969676e6832c96ee4c
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: 094175c

Automatic Backlinks to note: 3.0.3
Backup: 1.4.0
Favorites: 1.3.2
Hotfolder: 1.1.1
Note overview: 1.7.1
Note Tabs: 1.4.0
Outline: 1.5.13
Quick Links: 1.2.4

### Current behaviour

This is the error message:
D3 3 the key of play.wav (cffe65dca8e319cc6394d9811b53ced3) could not be uploaded: network timeout at: https://api.joplincloud.com/api/items/root:/.resource/cffe65dca8e319cc6394d9811b53ced3:/content

I've uploaded 13,000 notes and 31,000 resources. I have just this one file that won't sync.

I can't locate the note by searching for "D3 3 the key of" or "play.wav".

I can't find it in Note attachments. It only lists 10,000 attachments. If its in title ascending order, then all the titles are (untitled). If I reverse the sort order then it doesn't get down to "D3".

### Expected behaviour

A search for ID would be really useful on the Note Attachments page. Also search for Title.

Is there a way to locate this file on disk and delete it so that it doesn't corrupt anything?

**Comment by personalizedrefrigerator** [comment]
> Is there a way to locate this file on disk and delete it so that it doesn't corrupt anything?

It should be possible to do this through Joplin's development tools (make sure you have a backup of your data first!).

To do this,
1. Open the development tools (Help > Toggle development tools). 
2. Open the "Console" tab.
3. To see information about a resource, run `await Resource.load("some-resource-id-here")`
4. To delete a resource, run `await Resource.delete("some-resource-id-here")` (**be careful with this**)

Additionally, from the GUI, if you don't need note history, setting "Keep note history for (days)" to `1` and restarting Joplin (then waiting about 30 seconds) should remove resources that have been unlinked from Joplin notes for at least a day. If `play.wav` isn't linked to by a note, this should delete it.

**Comment by robe070** [comment]
Thanks. I've got rid of the sync warning message with the above instructions.

I still think the Note Attachments page needs some enhancement.
