### ISSUE TITLE
Wrong scroll position when the window gets de-maximized 

### ISSUE THREAD

**Issue by Tommy-01** [laurent22/joplin#1006]
### Operating system

- Windows
- Linux

### Application

- Desktop

To reproduce:
The window is maximized.
The note is much longer than the window height.
Cursor position is at the end of the note.
De- maximize the window.

Now the visible part of the note is somewhere above the last line. The last line, where the curor is, isn't visible anymore. You have to scroll down again oder hit enter.

**Comment by laurent22** [comment]
I think that was fixed in a recent release.
