### ISSUE TITLE
Question at the start - Linux App

### ISSUE THREAD

**Issue by Tommy-01** [laurent22/joplin#1007]
### Operating system

- Linux
### Application

- Desktop

Everytime i start the Linux app, (and hit "no") it asks me if i want to install it.
It's enough if i get asked once. Maybe there schould be an option to reset this decision.

By the way, the text of the window, doesn't use the with of the window. It's a little hard to read.
![1](https://user-images.githubusercontent.com/34900296/48967021-0674e300-efdb-11e8-8110-ba78f33fd11b.png)

**Comment by Shamp0o** [comment]
I'm pretty sure this prompt is caused by your Linux distribution and not by Joplin. I'm getting a similar one from AppImageLauncher which comes with Manjaro.

**Comment by laurent22** [comment]
That's part of the installer process and will probably not be changed (unless someone want to look into it and submit a pull request).
