### ISSUE TITLE
Moving a note down with alt + down works until it hits the bottom of the screen then focuses the current note

### ISSUE THREAD

**Issue by nickhobbs94** [laurent22/joplin#10078]
### Operating system

macOS

### Joplin version

2.14.17 (prod, darwin)

### Desktop version info

Joplin 2.14.17 (prod, darwin)

Client ID: 106e8412861b4727ba9cbb979ad9064d
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: 094175c

Backup: 1.4.0

### Current behaviour

1. I'm trying to reorder a list of todos with alt + down
2. Once I pass the end of the screen Joplin will lose focus and either
3. Stop reordering the note, or
4. Start moving the first line of the note down inside the note contents

Here's a screen recording:

https://github.com/laurent22/joplin/assets/11778560/dbda80bf-df89-4093-9a3c-3c7a6bdfe277

### Expected behaviour

I'd expect the note to continue down the list until it reaches the bottom. Note that moving upwards always seems to work fine.

**Comment by 7adidaz** [comment]
I don't have a Mac to reproduce and I can't reproduce it on my Ubuntu machine, but I suspect that at some point the focus switches to the `codemirror` editor, and the keybindings related to `codemirror` fire.
