### ISSUE TITLE
CLI Application: Can't delete notes from trash with `rmnote`

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#10090]
### Operating system

Linux

### Joplin version

3.0.0

### Current behaviour

1. Launch the CLI application
2. Delete a note with `:rmnote $n` ($n = current note)
3. Navigate to the trash folder
4. Delete the note from the trash folder with `:rmnote`
5. Observe that the note is no longer visible.
6. Navigate away from, then back to the trash folder.

Currently, the note is visible again in the trash folder.

### Expected behaviour

Calling `:rmnote` on a note in the trash folder should delete that note from the trash.

**Comment by laurent22** [comment]
That makes sense. Also I guess the `rmnote` command should be reviewed to take into account the trash folder.

I think this should be done:

- When deleting to trash (by default), don't display a confirmation message
- When deleting from the trash, display the confirmation message and indeed permanently delete the note
- Add a `--permanent` flag to optionally skip the trash folder. And a confirmation message should be displayed (unless `--force` is used)

**Comment by radhesh1** [comment]
Hi @personalizedrefrigerator i think we need to skip the note from going into `deleted_items`

**Comment by keys-i** [comment]
How to navigate to the Trash folder you are referring to in terminal?
I tried building from the latest repository but `toTrash` in `Note.ts` implementation seems to doing something different
> it seems to be saving everything to a sqlitedb and toTrash just updates the deleted time in the db.

**Comment by personalizedrefrigerator** [comment]
I've just opened https://github.com/laurent22/joplin/pull/10107. While working on it, however, I noticed that there doesn't seem to be a `restore` command (or similar) to move an item back to its original (before-deletion) location. I plan to open an issue for this later today. **Edit**: It exists. See below.

> How to navigate to the Trash folder you are referring to in terminal?

The trash folder should be visible in the left sidebar (I'm running with `yarn start` from `packages/app-cli`):
![screenshot: Trash folder visible in the left sidebar](https://github.com/laurent22/joplin/assets/46334387/12ce74b6-94fc-44da-b242-bc95e7b56c04)

> it seems to be saving everything to a sqlitedb and toTrash just updates the deleted time in the db.

The `toTrash` option sets `deleted_time` to a non-zero value, which causes the item to be visually shown in the trash folder. If `deleted_time` is `0`, an item is not deleted, otherwise, if it's a positive number, it's considered deleted (but not permanently). At present, only notebooks and notes can be in the trash.

**Comment by laurent22** [comment]
> I've just opened #10107. While working on it, however, I noticed that there doesn't seem to be a `restore` command (or similar) to move an item back to its original (before-deletion) location. I plan to open an issue for this later today.

There is in command-restore.ts, is that what you mean?

**Comment by personalizedrefrigerator** [comment]
> There is in command-restore.ts, is that what you mean?

Yes! I missed that (or assumed it was related to note history?).

**Comment by laurent22** [comment]
> Yes! I missed that (or assumed it was related to note history?).

I didn't think of that and indeed it could be confusing. I made a change to clarify that it's to restore items from the trash (currently the note history is not really supported for the CLI)
