### ISSUE TITLE
capture camera: camera gets no (auto)focus

### ISSUE THREAD

**Issue by moonstruxx** [laurent22/joplin#1009]
### Operating system

- Android

### Application

- Mobile
When i capture a photo the camera does not get focused. I'm also not able to touch trigger the focus action by taping on screen. I think we should give an initial auto-focus trigger. Beeing able to focus select objects / region would even be better :) But that is probably an enhancement

**Comment by Shamp0o** [comment]
My autofocus does work, but I cannot tap to focus either.

**Comment by laurent22** [comment]
Does it happen every time or only when trying to take certain photos? What's make of the phone?
