### ISSUE TITLE
Mobile: Can't empty trash

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#10092]
### Operating system

Android

### Joplin version

3.0.0

### Current behaviour

To reproduce,
1. Move a folder to the trash
2. Long-press on the trash folder
3. Long-press on the new subfolder of the trash folder

Currently,
1. The trash folder has no long-press menu
2. The subfolder of trash does not have a "permanently delete" option.

### Expected behaviour

As on desktop, it should be possible to
1. Delete folders from the trash notebook, or
2. Clear all items in the trash notebook (including folders).

**Comment by Sidd-R** [comment]
Hello, I wish to work on this issue. I am trying for gsoc this year and the guidelines state that one cannot submit another pull request before the previous one is merged and my previous pull request is yet to be merged. So, can I start working on this or should I wait for the previous pr to get merged?

**Comment by PackElend** [comment]
Dépending on the quality of the open PR.
If it has a lot of comments and you start the same way again, your next PR could be closed immediately

**Comment by Sidd-R** [comment]
> Dépending on the quality of the open PR. If it has a lot of comments and you start the same way again, your next PR could be closed immediately

Okay, got it. I'll keep that in mind. If there are any issues with the quality of the pr then can you please point it out so that I can improve on it next pr onwards.

**Comment by Sidd-R** [comment]
HI! I have completed the Implementation of this feature. I have added all the above mentioned features, apart from these I have also added an option to delete individual notes permanently and to restore all folders/notes from trash on long press. Requesting feedback for the same. If all is okay, then I'll create a pr.

https://github.com/laurent22/joplin/assets/97161173/bc5a3cd2-1265-459c-9195-0225f84e4da5

**Comment by personalizedrefrigerator** [comment]
> I have added all the above mentioned features, apart from these I have also added an option to delete individual notes permanently and to restore all folders/notes from trash on long press. Requesting feedback for the same. If all is okay, then I'll create a pr.

That looks good to me! @laurent22 do you have any comments on the proposed design?

**Comment by laurent22** [comment]
Yes I'm fine with it but there are multiple features in this video and there should be only one per PR. So @Sidd-R feel free to create a pull request but only for the "empty trash" feature (no "restore all", etc.)

**Comment by Sidd-R** [comment]
> only for the "empty trash" feature

okay got it. Also, should I wait for separate issues for the other features in the video to be created? or should I create multiple pull requests each addressing one feature on this issue only?

**Comment by laurent22** [comment]
Yes please create a separate issue for each feature so that we can evaluate if we actually want to add it or not
