### ISSUE TITLE
sync not working

### ISSUE THREAD

**Issue by exanta** [laurent22/joplin#101]
### Operating system

- [ x] Windows
- [ ] macOS
- [ ] Linux
- [ x] Android
- [ ] iOS

### Application

- [x ] Desktop
- [ x] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---
version 0.10.39

**Comment by laurent22** [comment]
Please could you provide more information? Do you have any error or warning? What specifically doesn't sync (all the notes or only some of them)?

Also if you could try to enable debug mode and provide any error or warning you are seeing: https://github.com/laurent22/joplin/blob/master/README_debugging.md
