### ISSUE TITLE
Markdown export / import Schedules to allow sync between organizers

### ISSUE THREAD

**Issue by moonstruxx** [laurent22/joplin#1010]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

Org-mode is able to export and import schedules and and task planing states . 
Org mode Feature description:
Toggle export of planning information (org-export-with-planning). “Planning information” comes from lines located right after the headline and contain any combination of these cookies: SCHEDULED:, DEADLINE:, or CLOSED:. 
This would allow meaningful sync of Tasks between arbitrary other organizer systems :)
Example Markdown (exported from org-mode)
****************************
# Table of Contents

1.  [Rose Rechung bezahlen](#org081763d):ATTACH:

<a id="org081763d"></a>

# TODO Rose Rechung bezahlen     :ATTACH:

<p><span class="timestamp-wrapper"><span class="timestamp-kwd">SCHEDULED:</span> <span class="timestamp">&lt;2018-12-04 Tue&gt;</span></span></p>

<span class="timestamp-wrapper"><span class="timestamp">[2018-11-25 Sun 10:06]</span></span>
<file:///home/bjoern/test/capture/Rose%20Rechung.md>

**************************
input org:
* TODO Rose Rechung bezahlen :ATTACH:
  SCHEDULED: <2018-12-04 Tue>
  :PROPERTIES:
  :Attachments: 3bbf9aeddfc441dfb57b47c560dda441.jpg
  :ID:       3cf80975-2bdc-465d-9735-0b8212aa137d
  :END:
  :LOGBOOK:
  CLOCK: [2018-11-25 Sun 10:06]--[2018-11-25 Sun 10:08] =>  0:02
  :END:
[2018-11-25 Sun 10:06]
[[file:~/test/capture/Rose%20Rechung.md::!%5BIMG_20181125_093806.jpg%5D(:/3bbf9aeddfc441dfb57b47c560dda441)]]

With this enhancement org-mode user (and pobably other ) could sync schedules.
If you like this feature i would try to contribute

**Comment by laurent22** [comment]
I'm afraid this would be out of scope for this project as it is a bit too specialised.
