### ISSUE TITLE
Restoring a note does not retain its history

### ISSUE THREAD

**Issue by jtagcat** [laurent22/joplin#10101]
### Operating system

Linux

### Joplin version

2.12.8

### Current behaviour

1. Revision history
2. Restore a note
3. Restored note does not have history

### Expected behaviour

Both original and restored notes retain history, manual 'rollback' is possible.

**Comment by laurent22** [comment]
This is working as expected because when you restore a revision you actually create a new note. If you want to preserve the history, you can copy the content of that new note to the old one, and delete the new note.
