### ISSUE TITLE
When updating and clicking the "X" to close Joplin, Joplin doesn't get fully closed

### ISSUE THREAD

**Issue by TheNightRider12** [laurent22/joplin#10114]
### Operating system

Windows

### Joplin version

2.14.19

### Desktop version info

Joplin 2.14.19 (prod, win32)

Client ID: 935b18de5283411a9b2f46659f00e432
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: 971c4e5

Backup: 1.4.0

### Current behaviour

1. Download an update
2. Have joplin running
3. Start the update executable
4. Will get a popup about Joplin currently running
5. Click the "X" in joplin to close it
6. Click "Retry" in the update dialog
7. Will get the same error message about joplin being running
8. Have to open task manager and end Joplin's task before I can continue updating. 

### Expected behaviour

Either "Retry" should kill the joplin task or clicking the "X" in Joplin should close the app as well as kill the task that is being ran. That way updating with the app being opened, or previously closed via the "X" button is a seamless process.

**Comment by JackGruber** [comment]
When the `Show tray icon` option is enabled, then Joplin is only minimized to the Systray and not closed.
When the option is activated you ned to close Joplin via File > Quit

The option could be found under `Tools > Options > General > Application`

**Comment by TheNightRider12** [comment]
Ah. I see. Thank you! Appreciate your help.
