### ISSUE TITLE
TypeError when running "process orphaned items" on Joplin server

### ISSUE THREAD

**Issue by rainforest1155** [laurent22/joplin#10118]
### Operating system

Linux

### Joplin version

Joplin server 2.14.2 via Docker on Pine64 with Debian Bullseye

### Current behaviour

running "process orphaned items" via the Web UI, the server log shows a TypeError:
`Cannot use 'in' operator to search for 'name' in undefined`

### Expected behaviour

there should be no error

### Logs
```
app-1        | 07:50:18 0|app  | 2024-03-14 07:50:17: [error] TaskService: On #10 (Process orphaned items) TypeError: Cannot use 'in' operator to search for 'name' in undefined
app-1        | 07:50:18 0|app  |     at UserItemModel.<anonymous> (/home/joplin/packages/server/src/models/UserItemModel.ts:126:17)
app-1        | 07:50:18 0|app  |     at Generator.next (<anonymous>)
app-1        | 07:50:18 0|app  |     at /home/joplin/packages/server/dist/models/UserItemModel.js:8:71
app-1        | 07:50:18 0|app  |     at new Promise (<anonymous>)
app-1        | 07:50:18 0|app  |     at __awaiter (/home/joplin/packages/server/dist/models/UserItemModel.js:4:12)
app-1        | 07:50:18 0|app  |     at /home/joplin/packages/server/src/models/UserItemModel.ts:124:41
app-1        | 07:50:18 0|app  |     at UserItemModel.<anonymous> (/home/joplin/packages/server/src/models/BaseModel.ts:221:19)
app-1        | 07:50:18 0|app  |     at Generator.next (<anonymous>)
app-1        | 07:50:18 0|app  |     at fulfilled (/home/joplin/packages/server/dist/models/BaseModel.js:5:58)
app-1        | 07:50:18 0|app  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by khuongduy354** [comment]
Sorry, where is the "process orphaned items"? I cant find it on Web UI, i want to reproduce this bug.

**Comment by roman-r-m** [comment]
> Sorry, where is the "process orphaned items"? I cant find it on Web UI, i want to reproduce this bug. 

Try searching for this string in the repo

**Comment by rainforest1155** [comment]
@khuongduy354 Sorry for the late reply, especially since there already seems to be a potential fix. For reference, here's how to manually run that task from the server web UI:
![image](https://github.com/laurent22/joplin/assets/4227209/694447fb-5b50-49bd-b3e2-c490fc46351d)

Thanks @Akash12233 for working on a fix! I'll check it out as soon as it is released.
