### ISSUE TITLE
attachments missing on Android; message says "some items cannot be synchronized"

### ISSUE THREAD

**Issue by fredcy** [laurent22/joplin#10119]
### Operating system

Android

### Joplin version

2.14.9

## Summary:
Joplin on Android now seems to be missing all attachments, and there is a banner saying "Some items cannot be synchronized". Attempts to "retry" and "retry all" seem to do nothing.

## Scenario
1. Search in the app for an item with a PDF attachment. 
2. Open the note.
3. Click on the attachment link in the note.
4. Choose the app to open the PDF (I have not set a default).
5. The PDF does not display. Instead I get an error popup saying "Cannot display PDF (e6e6...)".

## More info
This does not happen on all attachments. A few recently created attachments work OK.

I use Joplin Cloud for sync. This was all working fine until I first noticed the problem a week or so ago.

Joplin with the same account is working fine (near as I can tell) on MacOS desktop, and in iOS (iPad).

I'm using a Pixel 7 with Android version 14, last security update on Feb 5, 2024.

The orange banner with "Some items cannot be synchonized" leads to a page with a heading "Items that cannot be synchronized". There is a "Retry All" button, and a "Retry" button next to each item. The items seems to name an attachment file and each have a message saying "... could not be uploaded: Trying to upload resource, but only metadata is present". Clicking the Retry button for an item removes it from the list. But the item is back when I revisit the list later. Clicking "Retry All" doesn't appear to do anything.

Sometimes clicking the orange banner leads to a different page with summary counts of attachments and sync status.

![Screenshot_20240314-104021](https://github.com/laurent22/joplin/assets/15950/890dae05-e34d-4e7c-a4f2-e479efbe06f1)

### Expected behaviour

I expected the app to manage attachments correctly and to open them when I click on them.

### Logs

[mobile-log.log](https://github.com/laurent22/joplin/files/14604845/mobile-log.log)

**Comment by personalizedrefrigerator** [comment]
> There is a "Retry All" button, and a "Retry" button next to each item. The items seems to name an attachment file and each have a message saying "... could not be uploaded: Trying to upload resource, but only metadata is present".

 Joplin can download resource metadata separately from resources themselves (particularly if "Attachment download behavior" is set to "Manual" or "Auto"). In the past, users have experienced similar warnings when switching sync targets without first downloading all attachments. In the last week or two, have you switched sync targets?

A possible workaround is to create a new profile (Configuration > Tools > Profiles) and sync that profile to Joplin Cloud. This, however, involves doing a full sync with Joplin Cloud, which can be slow.

**Comment by fredcy** [comment]
I have been using Joplin Cloud as the sync target ever since I started using Joplin months ago; I have not changed it.

**Comment by fredcy** [comment]
I thought this problem was pervasive in my PDFs but it seems to really affect just one that I've found so far. So I recreated the item from scratch by downloading the PDF from the desktop app (where it works ok) and loading it into a new item.

So the issue wasn't fixed, but I have a workaround.  Might as well close it.
