### ISSUE TITLE
add more intent filters

### ISSUE THREAD

**Issue by moonstruxx** [laurent22/joplin#1011]
I'm for example not able to share a picture from gallery to Joplin
Current solution is to save the picture with remarkable name and finally i use "joplin attach file" to add the picture to a note. Direct sharing would be a great enhancement
here are some filter for you reference:
Pick a file
(org.openintents.action.PICK_FILE)
Print Image
(org.androidprinting.intent.action.PRINT)
Process text
(android.intent.action.PROCESS_TEXT)
Record Sound
(android.provider.MediaStore.RECORD_SOUND)
Scan
(la.droid.qr.scan)
Take a picture
(android.media.action.IMAGE_CAPTURE)
### Operating system

- Android

### Application

- Mobile

**Comment by RPDiep** [comment]
I would love this, too

**Comment by aritrakoley** [comment]
I switch between the desktop and the android app quite frequently and this feature is almost a necessity for me. I would love to see this implemented.
