### ISSUE TITLE
ENEX does not import correct when title of note matches the name of the attachment

### ISSUE THREAD

**Issue by emlowe** [laurent22/joplin#10125]
### Operating system

macOS

### Joplin version

2.14.19

### Desktop version info

Joplin for Desktop

Copyright © 2016-2024 Laurent Cozic
Joplin 2.14.19 (prod, darwin)

Client ID: 03e7649e749d430799dc0f4427f6cb68
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: 971c4e5

Backup: 1.4.0
macOS theme: 1.3.18
Rich Markdown: 0.13.4

### Current behaviour

The attached ENEX file does not import correctly

The PDF will be missing from the note. This happens when the Title of the note has the exact name of the attachment. It's unclear if secondary requirements are needed (like only one attachment) - however, this is at least the minimum needed

Changing the title to anything else and the import works correctly

[test-pdf-evernote.pdf.enex.zip](https://github.com/laurent22/joplin/files/14608816/test-pdf-evernote.pdf.enex.zip)

### Expected behaviour

PDF to import and be visible in the note

**Comment by khuongduy354** [comment]
Hi, can you elaborate the reproduce steps? Is it import ENEX as markdown? In my case, after import, it chose the name already so I cant change it to make pdf appear ?

**Comment by emlowe** [comment]
Import as markdown 

The PDF file itself is missing from the import on-disk - the Note references some UUID file name that doesn't exist.
You cannot make the PDF appear since it wasn't imported correctly

If you edit the ENEX XML file directly however, and change the title, then it will import correctly

**Comment by emlowe** [comment]
![Screenshot 2024-03-15 at 9 44 14 AM](https://github.com/laurent22/joplin/assets/30607889/0fcd25c7-2805-42bd-b7e0-f0d19b281276)

Normally one would expect to find `35fab64c7dba45e1a477262e36a2f1c4.pdf` in the `/Users/elowe/.config/joplin-desktop/resources/` directory

However, it's missing and not there.

**Comment by emlowe** [comment]
I'll note that the expected MD5 of the file listed in the markdown `35fab64c7dba45e1a477262e36a2f1c4` is NOT the MD5 of the actual attachment.

In fact, when I calculate the expected MD5 of the filename from the ENEX file it is `cd892fa62f1bc4115cb2eceda654143c` and that file IS in fact in the correct place

So, the file is there.

**Comment by khuongduy354** [comment]
I've found the bug cause: [import-enex.ts](https://github.com/laurent22/joplin/blob/dev/packages/lib/import-enex.ts)
![image](https://github.com/laurent22/joplin/assets/42113313/829ca384-67fe-40b5-a664-301b2084be4b)

in the existingResource part, when enex is imported, a note with that file name is also imported and is available in database, when we load a pdf with that same name, it found the note and thought it's a duplicated, so it skips the pdf creation.

**Comment by khuongduy354** [comment]
The bug is in [restore-note-link](https://github.com/laurent22/joplin/blob/dev/packages/lib/import-enex.ts#L297), it use link title to change Evernote's note-link to Joplin's note-link. The problem is the link title in your example is a resource-link (not note-link), and it has same name as note-link. so it mistakes and fix the link. The resource creation stills work fine.

![image](https://github.com/laurent22/joplin/assets/42113313/87eee837-5b63-486d-a2c9-cab29a690687)

Proof: comment out restoreNoteLinks function, and run, it works. 
My solution: To distinguish a note-link and resource link, title alone is not enough, we need the resources' ids of the imported ENEX, I'll make a PR in the morning.

**Comment by khuongduy354** [comment]
#10149, how can I address this PR, without typing it in a comment like this ? Still don't know how to do it :laughing: .
![image](https://github.com/laurent22/joplin/assets/42113313/283d5633-aa6d-42db-9dc0-a16e4af51af5)
