### ISSUE TITLE
Attachments to notes doesn't sync after editing

### ISSUE THREAD

**Issue by AlterMax** [laurent22/joplin#10129]
### Operating system

Windows

### Joplin version

2.14.19

### Desktop version info

Joplin 2.14.19

### Current behaviour

1. Create a new note on the first device
2. Insert the Excel file (111.xlsx for example) as an attachment in this note
3. Performing synchronization, encryption enabled
4. The note and attachment file syncs normally and appears on the second device
5. Editing, saving and closing the attachment file (111.xlsx) on the first device
6. Performing synchronization, encryption enabled
7. Checking the file, on the first device there is a new version after editing
8. Checking the file, on the second device there is an old version before editing

### Expected behaviour

I expect that after editing the attachment file will also be synced to the second and the rest of my devices

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

From the description, this looks similar to [this issue in the mobile app](https://github.com/laurent22/joplin/issues/9175) -- fixing this bug might look similar to the commit that fixed that issue.

**Comment by G0maa** [comment]
Hello, I've reproduced this using `Joplin server` (Linux & Windows) without encryption.

It seems the problem only happens if the file on the target machine is being watched by Joplin, I will take a deeper look at the code and report back my findings if any.
