### ISSUE TITLE
Joplin is opened behind the top taskbar after closed in half or quarter screen mode

### ISSUE THREAD

**Issue by PixelOfDeath** [laurent22/joplin#10131]
### Operating system

Windows

### Joplin version

Joplin 2.14.19

### Desktop version info

Joplin 2.14.19 (prod, win32)

Client-ID: dc26cb5a512841edbe25b50849c20cae
Sync-Version: 3
Profil-Version: 46
Unterstützter Schlüsselbund: Ja

Revision: 971c4e5

Backup: 1.4.0

### Current behaviour

When dragging the Joplin windows to the left or right to resize the windows to half screen size, or into a corner to resize it to quarter size, and then closing Joplin, it will open behind the taskbar if the taskbar is on top.

I have to then resize the taskbar or Joplin to make the Joplin Windows move below it.

Edition	Windows 10 Pro
Version	22H2
Betriebssystembuild	19045.4046
Windows Feature Experience Pack 1000.19053.1000.0

![joplin under top taskbar](https://github.com/laurent22/joplin/assets/3923342/c8f1bfee-8cdb-423c-a066-45ccf345bfc0)

**Comment by G0maa** [comment]
I'll try to reproduce this shortly, but my initial assumption is that it's a bug in the `electron-window-state` dependency.  (I might be wrong though)

Electron natively doesn't store window state, and there has been a [long back-and-forth discussion](https://github.com/electron/electron/issues/526#issuecomment-905323663) about implementing it or not.

Edit: another electron based app (Zulip) also has a window-state related [issue](https://github.com/zulip/zulip-desktop/issues/1330), Zulip uses the same dependency as far as I know to control window state.

For now, you can try using `Shift + Windows key + Arrow Up`, to at least be able to see the top bar and re-size the window,

**Comment by G0maa** [comment]
Yep, both electron apps have the same issue (and other weird window-state related bugs).

https://github.com/laurent22/joplin/assets/12874707/d82ea679-64b1-416e-b1a3-a83cdb4115a8
