### ISSUE TITLE
Rich text editor: Default font no longer matches the note viewer or markdown editor

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#10141]
### Operating system

Linux

### Joplin version

3.0.0

### Desktop version info

Joplin 3.0.0 (dev, linux)

Client ID: 44da07c87ebf4662aa0e0f97f77f7f38
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: a40c3b792

Backup: 1.4.0
Freehand Drawing: 2.8.0

### Current behaviour

1. Ensure that the "Editor font family" input is empty in settings
2. Open the rich text editor
3. Type text
4. Compare to the note viewer font
5. Compare to the markdown editor font

#### Screenshots

**Rich text editor**:
![screenshot: Content uses a serif font, including code blocks](https://github.com/laurent22/joplin/assets/46334387/850cfc06-c955-4fa8-a625-56ce535b09bb)

**Note viewer and markdown editor**:
![screenshot: Content uses a sans-serif font for main text, monospace for code blocks](https://github.com/laurent22/joplin/assets/46334387/4c1c578a-8d60-4c9c-89d2-9a0359df4d1a)

### Expected behaviour

As before, the rich text editor's default font should match the note viewer's default font.

**Comment by laurent22** [comment]
> As before, the rich text editor's default font should match the note viewer's default font.

That's a good point - but should it? When I merged this change I indeed considered that it means the viewer and RTE will have different fonts, but maybe that's correct? The font editor should apply to the Markdown and Rich Text editor but the viewer is not an editor, so I guess it could stay as it was?

I'm not 100% sure though about all this actually, it was just my thoughts when I merged this pull request.

**Comment by personalizedrefrigerator** [comment]
> The font editor should apply to the Markdown and Rich Text editor but the viewer is not an editor, so I guess it could stay as it was?

Note that the default Rich Text editor font is now also different from the default markdown editor font (the markdown editor defaults to sans-serif, the Rich Text editor defaults to serif).

**Edit**: I've updated the issue title and description to reflect this.

**Comment by personalizedrefrigerator** [comment]
It also seems to change the font in math and code regions:

![screenshot: Math and code regions also use serif](https://github.com/laurent22/joplin/assets/46334387/1b37bbbe-7834-4efb-9dd7-c08edcc204d7)

**Edit**: I've created a separate issue for this: https://github.com/laurent22/joplin/issues/10142

**Comment by laurent22** [comment]
Thanks, although I'd be tempted to revert this change as it feels like it hasn't been well though out, and so that we can deal with it some other time.

**Comment by ab-elhaddad** [comment]
Hi, I really apologize for these bugs 🙏🏼, but I am willing to fix them. I have already opened a PR fixing this issue and will go for the other issue.
