### ISSUE TITLE
Select and convert multiple lines to list items

### ISSUE THREAD

**Issue by ivywong** [laurent22/joplin#1014]
### Operating system

- Linux

### Application

- Desktop

When I select multiple lines/paragraphs in the editor and click the "Numbered List" or "Bulleted List" button, only the first paragraph or line is turned into a list item, and the others remain unchanged. The expected behavior (to me) is to convert each paragraph into its own list item.

Also, when I select and format this way, a new line is inserted before the selection, but the selection itself remains unchanged, so some of the highlighted text "drops out" of the selection, which is a little odd.

**Comment by nolanmoore** [comment]
I agree with the expected behavior, I am used to this auto formatting functionality from a number of other programs and apps.

**Comment by mic704b** [comment]
Please assign.

BTW what is the purpose of inserting the new line at the start?

Should it not just convert to list item(s) in place, and only insert a new line if the selection starts in the middle of a line?
