### ISSUE TITLE
Back button handler on mobile doesn't go back to previous note

### ISSUE THREAD

**Issue by djsudduth** [laurent22/joplin#10148]
### Operating system

iOS

### Joplin version

12.14.6

### Current behaviour

There is a bug in the mobile versions of Joplin where tapping on a link in a document, correctly opens the linked document, but tapping on the back button doesn't go back to the original document... it goes to the folder where that original document is located in. This makes linked notes practically unusable on mobile devices. This was verified that this bug affects both the iOS and Android versions. The back button in the Linux, Windows, and MacOS versions all work correctly.

### Expected behaviour

The back button should behave the same as on desktop - go back to the original note that contained the link.

**Comment by nebiyuelias1** [comment]
I'm sorry but I'm new here and hoping to get involved in GSOC 2024, can you please provide a reproducing steps?

**Comment by djsudduth** [comment]
@nebiyuelias1 - to verify the steps, I tested on both Windows and iOS:
On Windows - Joplin version 2.14.19: 
- Create a note within a notebook that has some notes within it already
- Create another second note in the same notebook
- Add a link of the first note within the second note
- Click on the link to go back to the first note
- Press the back button at the top of the note editor
- The second note appears in the editor successfully

Follow the same steps on iOS - Joplin version 12.14.6
- When you press the back button, the second note does not appear, only the notebook list appears (so you don't know what note you were supposed to go back to)

**Comment by nebiyuelias1** [comment]
@djsudduth - I can confirm this after trying it on Android.
