### ISSUE TITLE
Spell checker should ignore code blocks

### ISSUE THREAD

**Issue by AriaMoradi** [laurent22/joplin#10159]
### Operating system

Linux

### Joplin version

1.14.20

### Desktop version info

Joplin 2.14.20 (prod, linux)

Client ID: bbd6d29626e14324ae8419d6e5ee8c8c
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: cfd98e3

Backup: 1.4.0

### Current behaviour

Text inside code blocks goes through the spell checker which is annoying when the text doesn't contain normal words.

Here's an example
![image](https://github.com/laurent22/joplin/assets/8719233/d6b7ec26-f6b1-4197-a787-0742f672363a)

### Expected behaviour

Ignore code blocks.

**Comment by personalizedrefrigerator** [comment]
This should be fixed in the beta markdown editor. It can be enabled in the "General" tab of settings.

**Comment by AriaMoradi** [comment]
Beta editor doesn't have this issue.
