### ISSUE TITLE
Help>Apropos: version info not updated on new releases

### ISSUE THREAD

**Issue by Wenzel** [laurent22/joplin#1018]
### Operating system
- Linux

### Application
- Desktop

Hi, i'm running the latest release `wenzel wenzel  77M 28 nov.  18:09 Joplin-1.0.117-x86_64.AppImage` here, and the version info in the app says otherwise:

![screenshot_20181128_181442](https://user-images.githubusercontent.com/964610/49169311-cd6da300-f339-11e8-9ed1-8274bf0d63d4.png)

Can you confirm ?

**Comment by laurent22** [comment]
As far as I can see the version info is correct in latest version, so it might just be you're looking at the wrong version. Could you try to download it and run it again?

**Comment by CalebJohn** [comment]
Just for reference, I'm also use the AppImage (on Ubuntu 18.04) but my version number is correct.
![image](https://user-images.githubusercontent.com/2179547/49172560-a9d93700-f2fe-11e8-9163-05ba5a3e534c.png)

**Comment by Wenzel** [comment]
@CalebJohn thanks for your comment.
Can you please confirm the SHA1?

I downloaded the image again and got the same SHA1 and version issue.

I don't how these AppImage works, is it possible that the old got copied into .local/something and is being used by default ?

~~~
$ find . -iname '*joplin*'
./softs/Joplin-1.0.117-x86_64.AppImage
./Downloads/Joplin-1.0.117-x86_64.AppImage
./.local/share/icons/hicolor/16x16/apps/appimagekit-joplin.png
./.local/share/icons/hicolor/72x72/apps/appimagekit-joplin.png
./.local/share/applications/appimagekit-joplin.desktop
./.config/Joplin
./.config/joplin-desktop


~~~

**Comment by Wenzel** [comment]
Found it, but I need explanations.

I removed `~/.config/Joplin` and `~/.config/joplin-desktop`, and it have the right version now.

**Comment by laurent22** [comment]
How did you install the app?

**Comment by Wenzel** [comment]
I just downloaded the app and ran the `AppImage`
