### ISSUE TITLE
(c) will be placed with © when note is saved.( when switch to other notes)

### ISSUE THREAD

**Issue by lxdfly** [laurent22/joplin#10198]
### Operating system

Windows

### Joplin version

2.14.20

### Desktop version info

Joplin 2.14.20 (prod, win32)

客户端 ID: 3a28dacd47de4540b5ad985293885fcc
同步版本：3
配置文件版本：46
支持的密钥链：是

修订：cfd98e3

### Current behaviour

if there is (c) in note, it will be placed with  ©  when the note is saved, printed or export to PDF file.

### Expected behaviour

show (c) as （c） ，not to  be shown as  ©

### Logs

<img width="195" alt="C-after" src="https://github.com/laurent22/joplin/assets/22286259/b6aceed3-df02-47b5-9f9e-4e1fd22281e9">
<img width="212" alt="c-before" src="https://github.com/laurent22/joplin/assets/22286259/8d50fa62-236c-4e12-9878-847ae3ca83de">

**Comment by lxdfly** [comment]
<img width="554" alt="c" src="https://github.com/laurent22/joplin/assets/22286259/66fc632f-275f-4169-9cb2-cfa011eb210b">

**Comment by arre-ankit** [comment]
I don't think there is a issue in that

![image](https://github.com/laurent22/joplin/assets/98694380/61aadaf7-af90-4190-876c-8bd893bb64c0)

You might using older version

I think you should reinstall it from https://joplinapp.org/download/

If the issue still remains please inform.

**Comment by laurent22** [comment]
This is because of a Markdown plugin that you need to disable
