### ISSUE TITLE
Unable to click any hyperlinks

### ISSUE THREAD

**Issue by AlexNduta** [laurent22/joplin#10199]
### Operating system

Linux

### Joplin version

2.13.15(prod, linux)

### Desktop version info

Joplin 2.13.15 (prod, linux)

Client ID: b004e148f5cb4b5599fec4870acef301
Sync Version: 3
Profile Version: 44
Keychain Supported: No

### Current behaviour

I have two types of links on my notebooks:
1. URLs I just copy-pasted randomly from a web page
2. URL that I used the `insert/Edit` feature in Joplin

unfortunately, none of the links open up by default. I have to copy the link manually from the notebook and paste it in a browser. 
NB: I am running on Debian 12 Bookworm. I highly doubt its a base OS issue.
![image](https://github.com/laurent22/joplin/assets/86476101/bcec24f3-c753-45c7-b6c0-753b1b86cc7e)

This is a video of me demonstrating the issue. unless I copy and paste the link manually, I cannot open the link.
[Screencast from 2024-03-25 08-24-28.webm](https://github.com/laurent22/joplin/assets/86476101/c612d8ca-f2a0-4d58-a5e2-b3a2b696e6ca)

### Expected behaviour

I am sure this feature was intended to work through a redirect.
I expected that, clicking the link would redirect me to my default webpage.

**Comment by laurent22** [comment]
Does it work in 2.14? I think this has been fixed

**Comment by AlexNduta** [comment]
Just updated and still no changes. Update details below: 

Joplin 2.14.20 (prod, linux)

Client ID: b004e148f5cb4b5599fec4870acef301
Sync Version: 3
Profile Version: 46
Keychain Supported: No

**Comment by DarkFalc0n** [comment]
Hey @AlexNduta, I just looked at your screen recording and I think the issue lies in the fact that you are using the Rich text editor. Clicking directly only works in markdown mode (in the right preview panel).
If you want to open links instantly in Rich Text mode instead, you can hold the CTRL (or equivalent) button while clicking.

**Comment by DarkFalc0n** [comment]
Also, there are certain [limitations](https://joplinapp.org/help/apps/rich_text_editor/) to using the Rich Text Editor. If you decide to switch to Markdown editor, you can directly click the links in the right preview column

**Comment by personalizedrefrigerator** [comment]
> If you want to open links instantly in Rich Text mode instead, you can hold the CTRL (or equivalent) button while clicking.

If it does work with <kbd>ctrl</kbd>, updating the tooltip text for links could be helpful. For example, Libreoffice Writer shows the following when hovering over a link:
![screenshot: Libreoffice writer suggests ctrl-clicking on a link](https://github.com/laurent22/joplin/assets/46334387/e7df137d-5493-46e2-9810-66aedc39650e)
Joplin, however, just shows the link:
![screenshot: Joplin: Hovering over a link shows a tooltip with just the content of the link](https://github.com/laurent22/joplin/assets/46334387/24191386-e7f7-4ab5-b0a3-2ca3d28fee4d)

**Comment by AlexNduta** [comment]
Thanks @DarkFalc0n, It worked. I could have never figured that out. I think what @personalizedrefrigerator is suggesting sounds practical because its part of self-documentation.

**Comment by DarkFalc0n** [comment]
I think the tooltip handling is done together for all types of editors (md and richtext). However, I think altering only the richtext editor hyperlink tooltips would be the way to go.

**Comment by DarkFalc0n** [comment]
I found another [solution here](https://www.tiny.cloud/docs/plugins/opensource/link/#link_context_toolbar) that will be less intrusive. 
Looks like this: 
![image](https://github.com/laurent22/joplin/assets/59203815/132fc934-9455-404d-9f1a-235bed33d244)


It has an icon at the end to visit the link from the editor

**Comment by 243JohnM** [comment]
I have a similar problem with Joplin 2.14.20 on Windows. I posted this: https://discourse.joplinapp.org/t/web-links-in-joplin-windows-dont-work/37170

Someone told me about Ctrl + click on the link. That works, however, focus doesn't change to the web browser. Works fine on Android though!

**Comment by laurent22** [comment]
> If it does work with ctrl, updating the tooltip text for links could be helpful. For example, Libreoffice Writer shows the following when hovering over a link:
> ![screenshot: Libreoffice writer suggests ctrl-clicking on a link](https://private-user-images.githubusercontent.com/46334387/316558580-e7df137d-5493-46e2-9810-66aedc39650e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMDA2MzYsIm5iZiI6MTcxMzIwMDMzNiwicGF0aCI6Ii80NjMzNDM4Ny8zMTY1NTg1ODAtZTdkZjEzN2QtNTQ5My00NmUyLTk4MTAtNjZhZWRjMzk2NTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDE2NTg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmZmRlZDQ3NjU1MWQ1NzA5YTllMjJmYmVmMjdlNGUxMGY2ODRkMTc5YTVhZGU4YWRlOGY3ZTU5YmFhMWU4YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wZcS9Qb17RuPdOMxcoqjRcl9rFoYAHzp5QvQBFCHScM)

For this issue we'd like to implement this then, if possible. If not possible maybe we can look at making the link clickable by default instead?
