### ISSUE TITLE
Note list cannot be resized in "Detailed" mode

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10192]

**Comment by G0maa** [comment]
Any way of reproducing this? Mine resizes normally, or am I missing something?
![joplin-resize-notelist-works](https://github.com/laurent22/joplin/assets/12874707/587a7b83-59dd-40e9-ac31-968f706a0c48)

**Comment by laurent22** [comment]
For me it doesn't resize past a certain width. Try to resize it to very large for example and I think it should somehow prevent you from doing this even though it shouldn't

**Comment by khalidkhankakar** [comment]
Can you explain it?

**Comment by laurent22** [comment]
I cannot replicate this anymore
