### ISSUE TITLE
Deleting a note from the trash make it disappear, even though it's still there

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10190]
- Open the trash
- Select a note
- Delete it
- Leave the trash folder
- Come back

=> the note is back

Instead the delete button should permanently delete the note. A confirmation dialog should be displayed.

**Comment by anmoljhamb** [comment]
Hey! I just checked it out, and it seems to work. I tested it on a Debian machine. Was it fixed?

**Comment by laurent22** [comment]
It is no longer possible to do the above so we can indeed close the issue.
