### ISSUE TITLE
Image files do not attach / display 

### ISSUE THREAD

**Issue by dexp2008** [laurent22/joplin#102]
### Operating system

- [ ] Windows
- [ ] macOS
- [x ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x ] Desktop
- [ ] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---
Attempt to attach image files via "attach files" menu selection.
Repeated with several image file formats viz., jpg, png etc.
No file is attached or displayed etc.
Attachment proceeds per expectation with various document formats viz., pdf, doc, odt etc.

Thank you for your review and consideration!
David

**Comment by laurent22** [comment]
Hello, please could you enable the debugging mode and try again? As described there: https://github.com/laurent22/joplin/blob/master/README_debugging.md

If you could post any warning or error that you get that would be helpful.

**Comment by dexp2008** [comment]
Laurent22,
Thank you for your expedient reply and request!
I created the requisite 'flags.txt' file in the ~/.config/Joplin directory viz., with the listed line
"--open-dev-tools --log-level debug". No development tools "Console" tab appears?
I also placed the specified options on separate lines viz.,
--open-dev-tools <cr>
--log-level debug
However, no "Console" tab appears?
I shall await your additional debug suggestions.
Appreciatively,
David

**Comment by laurent22** [comment]
Actually it should be `~/.config/joplin` lowercase. Was there a file "database.sqlite" in the folder where you've added flags.txt? Also the flags should be on one line only.

**Comment by dexp2008** [comment]
Laurent,
Thank you for your review and assessment!
I discovered both a "Joplin" and "joplin-desktop" directory in ~/.config.
Saved the "flags.txt" file to the "joplin-desktop" directory (w/database.sqlite file).
Invoked the Joplin application and voila! debug mode per expectation.
No console errors were observed when the "attach file" option was activated.
However, observed errors in the log.txt file viz.,
_2017-12-18 10:48:57: "Error: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_JoplinNRLIX7/app/resources/app/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)
Error: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_JoplinNRLIX7/app/resources/app/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)_
Application installed via "Joplin-0.10.39-x86_64.AppImage". Linux Mint 18.3 Sylvia system
Attached is the log.txt file for your inspection.
[log.txt](https://github.com/laurent22/joplin/files/1569858/log.txt)
Thank you for your expedient support!
Appreciatively,
David

**Comment by laurent22** [comment]
Thanks for the report, it seems it's a problem with sharp (the module used to resize the image) that doesn't get packaged properly into the app. I'd need to do some test in a VM to try to fix this. Which OS and version are you using?

**Comment by dexp2008** [comment]
Laurent,
You are welcome regarding the report! Thank you for your debug support :)
I have attached a image displaying the OS system information per your request.
OS: Linux Mint 18.3 Cinnamon 64 bit
Cinnamon Version: 3.6.6
Linux Kernel: 4.10.0-42-generic

![system info](https://user-images.githubusercontent.com/34593868/34196407-dc1e8a68-e516-11e7-8e71-9ee1c73c7d7a.png)

Appreciatively,
David

**Comment by tpaukku** [comment]
Hi Laurent,
I can also confirm this bug with Ubuntu 16.04 (64bit) and Ubuntu Mate 16.04 (64bit). I also tested that when you just remove .jpg from file name (picture.jpg -> picture for example), file attaching works fine. = obviously picture isn't shown, but file is attached, versus with .jpg it's not even attached.
Have you found any solution or is there any way to get this working before the actual solutions appears?
And thank you for an excellent application, I can translate it also to finnish when I have little time.

**Comment by twslade** [comment]
@laurent22 I'm experiencing the same issue above. Tailing the `log.txt` shows the following error which is the same as above. 
```sh
2018-02-04 10:42:30: "Error: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_Joplin8NpQxm/app/resources/app/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)
Error: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_Joplin8NpQxm/app/resources/app/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/.mount_Joplin8NpQxm/app/resources/app/node_modules/sharp/lib/constructor.js:9:15)
    at Object.<anonymous> (/tmp/.mount_Joplin8NpQxm/app/resources/app/node_modules/sharp/lib/constructor.js:234:3)"
```
Showing shared dependencies via `ldd` reveals the missing dependency as well.
```sh
$> ldd  /tmp/.mount_Joplin8NpQxm/app/resources/app/node_modules/sharp/vendor/lib/libpng16.so
/tmp/.mount_Joplin8NpQxm/app/resources/app/node_modules/sharp/vendor/lib/libpng16.so: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_Joplin8NpQxm/app/resources/app/node_modules/sharp/vendor/lib/libpng16.so)
	linux-vdso.so.1 =>  (0x00007fffe08ff000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ff81bf63000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff81bc5a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff81b890000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff81c3b6000)

``` 

This looks related and *deep*.
https://github.com/lovell/sharp/issues/892 

Looks like a conflict between electron and sharp... I don't know if you'll be able to do anything here to resolve this at the moment.

I've setup a simple instance of sharp at the same version for the current release and was not able to reproduce the problem. I'm going to setup a project using electron + sharp to see if I can reproduce it there.

**Comment by laurent22** [comment]
@twslade, in the latest version, I've reverted to 0.17.3. Does it work any better?

**Comment by twslade** [comment]
@laurent22 Yup, that fixed it for me. I noticed your change in 29e9ccf21618d7a90ae1445f814002e14a26d137 
@tpaukku @dexp2008  please give this a test with [v0.10.60](https://github.com/laurent22/joplin/releases/tag/v0.10.60)

**Comment by tpaukku** [comment]
@twslade I tested with v0.10.60 (Ubuntu Mate 16.04) and attaching images works great (tested with .jpg and .png)! :) Thanks for your efforts to everyone! I started with translation but I'm not very experienced with command line so it's going to take me a while to learn how to install all dependencies for Poedit and compile it, but it's useful to learn it so coming up... :)

**Comment by laurent22** [comment]
Thanks all for the feedback. Let's leave Sharp at 0.17.3 for now and review later when new versions of Electron are released.
