### ISSUE TITLE
Commandline export of Joplin-desktop data with Joplin terminal app does not work

### ISSUE THREAD

**Issue by mrkafk** [laurent22/joplin#1020]
### Operating system

- Linux (amd64, Debian 9.5, KDE Plasma)

### Application

- Terminal

Export command finishes with no error, but the created export directory does not contain notes, only a single directory "resources" for raw format:

```
user@host /tmp % joplin export --log-level debug --profile ~/.config/joplin-desktop --format raw /tmp/dd
user@host /tmp % cd dd
user@host /tmp/dd % find . -type f
user@host /tmp/dd % ls
resources
```

Same for md format:

```
joplin export --log-level debug --profile ~/.config/joplin-desktop --format md /tmp/ff
% ls ff
_resources
```

For jex format:

```
% joplin export --log-level debug --profile ~/.config/joplin-desktop --format jex /tmp/ee
There is no data to export.
```

I do have the relevant folder:
```
% ls ~/.config/joplin-desktop 
database.sqlite  log-clipper.txt  log-database.txt  log.txt  resources  tmp
```

No warning on nonexistent profile directory either:

```
joplin export --log-level debug --profile ~/.config/NODIRHERE --format raw /tmp/dd
```

Terminal app version:
```
% npm list -g --depth=0 | grep joplin
├── joplin@1.0.118
```

**Comment by foxmask** [comment]
Try to provide the profile parm as the first argument and logfile path later

**Comment by mrkafk** [comment]
It's --profile arg that is not respected.

**Comment by laurent22** [comment]
Command should go last:

    joplin --log-level debug --profile ~/.config/NODIRHERE export --format raw /tmp/dd
