### ISSUE TITLE
Mobile: Describe the plugin settings page

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#10207]
### Operating system

Android

### Joplin version

3.0.0

### Current behaviour

At present, the mobile plugins settings page has no description of what plugins are, who creates/publishes them, etc.
<img src="https://github.com/laurent22/joplin/assets/46334387/83689708-0d97-4eaf-ace3-b985492525f7" width="400" alt="screenshot: Plugin settings page. Has: List of installed plugins with delete buttons, install from file, and search (and advanced settings)"/>

### Expected behaviour

The plugin settings screen *might* have the following:
- [x] A description of who publishes plugin plugins and how to tell.
   - Resolved -- see: https://github.com/laurent22/joplin/pull/10348
- [x] What "recommended" plugins are.
   - Resolved -- see: https://github.com/laurent22/joplin/pull/10348
- [x] What to do if a plugin doesn't work on mobile. (Maybe mark plugins as a beta feature?)
   - Resolved -- most plugins marked as incompatible.
- If using a GitHub mirror, what this means.
   - Currently, a warning is shown at the top of the screen (similar to desktop). However, it isn't clear from the warning what a "mirror" is or why it's being used.
- A link for more information.

**Comment by DarkFalc0n** [comment]
Tracking completion of this issue: (can add more with ideas from community)
- [ ] Description of plugin publishers and how to tell
- [x] Description of recommended plugins
- [x] Mark plugins that dont work on mobile / Mark plugins as beta
- [ ] Describe github mirror, if using
- [ ] Add link for more info on plugins

**Comment by personalizedrefrigerator** [comment]
Re-opening, as this is only partially resolved.

**Comment by personalizedrefrigerator** [comment]
Closing as resolved.
