### ISSUE TITLE
Desktop: Unable to close application when in fullscreen

### ISSUE THREAD

**Issue by tankh99** [laurent22/joplin#10214]
### Operating system

macOS

### Joplin version

2.14.20

### Desktop version info

2.14.20 (macOS, Ventura 13.4.1, M2 Pro)

### Current behaviour

1. If Joplin is in full-screen, pressing on Close will not close the window
2. If it is not in full-screen, pressing on Close will close the window

### Expected behaviour

Pressing on close should close the application regardless of full screen or not

Note: This is my first issue here, so please do correct me if I'm mistaken

**Comment by DarkFalc0n** [comment]
Can you make it a bit clearer? By 'close' do you mean the red button on the Mac menubar?

**Comment by tankh99** [comment]
> Can you make it a bit clearer? By 'close' do you mean the red button on the Mac menubar?

Sorry I just saw this! Yes, I meant the red button at the top left of the Mac menubar. Below is a screen recording of what I mean

https://github.com/laurent22/joplin/assets/56617918/c5978ed5-9296-4364-bb50-5887d891c2b0

**Comment by DarkFalc0n** [comment]
I think this maybe a Mac specific issue, I use a Linux desktop with Mac-like menubar buttons and it works fine for me.

**Comment by tankh99** [comment]
> I think this maybe a Mac specific issue, I use a Linux desktop with Mac-like menubar buttons and it works fine for me.

Yup, I believe you are right. What would then be the next steps to resolve this issue?
