### ISSUE TITLE
[Android] No github APK updates since DEC 1, 23

### ISSUE THREAD

**Issue by KruyKaze** [laurent22/joplin#10211]
### Operating system

Android

### Joplin version

v2.13.10

### Current behaviour

Self explanatory. Please update the repo: `https://github.com/laurent22/joplin-android/releases`

**Comment by personalizedrefrigerator** [comment]
The more recent APK updates seem to be under "Tags": https://github.com/laurent22/joplin-android/tags (see, for example, 3.0.1: https://github.com/laurent22/joplin-android/releases/tag/android-v3.0.1)

All, however, are associated with the same commit on the Android repo (which is from 2020), so all have the same commit date.

**Comment by laurent22** [comment]
Thanks for the reminder, I've set 2.14.9 as latest official release
