### ISSUE TITLE
Create bulleted list hotkey not working in rich text editor

### ISSUE THREAD

**Issue by thovin** [laurent22/joplin#10218]
### Operating system

Windows

### Joplin version

2.14.20

### Desktop version info

Joplin 2.14.20 (prod, win32)

Client ID: 494e601b2d17406e91fd5acd28ef5fed
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: cfd98e3

Backup: 1.4.0

### Current behaviour

Hotkey to create a bulleted list does not work in rich text editor. Works fine in markdown editor. Tried changing the hotkey to a bunch of other things to ensure no overrides from other programs. All other hotkeys working correctly as far as I can tell.

**Comment by DarkFalc0n** [comment]
I could reproduce the bug consistently, in my Arch Linux System. This has something to do with TinyMCE, though I have not investigated it fully.

**Comment by thovin** [comment]
Issue is still active, pending review/repair of tinyMCE implementation for the feature

**Comment by thovin** [comment]
Issue is still active, pending review/repair of tinyMCE implementation for the feature
