### ISSUE TITLE
[feature] Display creation date?

### ISSUE THREAD

**Issue by ebousse** [laurent22/joplin#1021]
At the moment only the last modification date is shown when editing a note. It would be great to also have the option to display the creation date, in order to more easily avoid losing track of dates eg. when fixing typos in old notes.

**Comment by laurent22** [comment]
Creation date is displayed too if you click on the Information icon on the desktop app. Is that what you're looking for?

**Comment by ebousse** [comment]
Indeed sorry I should have been more precise! My suggestion was to have the possibility to have it displayed without the need to press a button, eg. next to the modification date in the editor view directly.

In fact I would even be in favor of finding a way to show creation and/or modification date in the notes list directly, but this it yet another topic :)

**Comment by foxmask** [comment]
@ebousse something [like that](https://discourse.joplin.cozic.net/t/joplin-web-a-webapp-for-our-joplin-editor/555/11) ?

**Comment by ebousse** [comment]
> @ebousse something [like that](https://discourse.joplin.cozic.net/t/joplin-web-a-webapp-for-our-joplin-editor/555/11) ?

Indeed!
