### ISSUE TITLE
Focus on title field after creating new note or todo

### ISSUE THREAD

**Issue by PaulS-26** [laurent22/joplin#10237]
### Operating system

Android

### Joplin version

2.14.9

### Current behaviour

1. Create new note or todo by pressing the "+" button or using the home screen app shortcut
2. New note opens, no focus is set
3. Cursor must be placed manually in the title field before title text can be entered

### Expected behaviour

Cursor is placed directly on the title field so that keyboard input can start immediately (same behavior as in desktop app).

**Comment by kushalShukla-web** [comment]
Hey @PaulS-26  wanted to work on this issue

**Comment by PaulS-26** [comment]
Hi @laurent22

I have just tested this with version 3.0.8 (on Android 14), unfortunately the focus is not automatically set to the title field and still has to be set manually. Thanks for taking a look...

**Comment by ZornHadNoChoice** [comment]
@PaulS-26 You're right. This is still an issue in v3.2.7.
