### ISSUE TITLE
Issue in Menu Nav Bar

### ISSUE THREAD

**Issue by MrCodYrohit** [laurent22/joplin#10233]
### Operating system

Windows

### Joplin version

3.0.2

### Current behaviour

The functionality of undo and redo options in the window menu bar becomes ineffective when adding a new line.
The code for issue is:
`{
	role: 'undo',
	label: _('Undo'),
},
{
	role: 'redo',
	label: _('Redo'),
},`

### Expected behaviour

After fixing this isse, The undo and redo options are expected to remain functional properly.

**Comment by Aitchessbee** [comment]
It's happening on Linux (PopOS) as well
