### ISSUE TITLE
Menu bar undo and redo options doesn't work when new line is inserted.

### ISSUE THREAD

**Issue by ab-elhaddad** [laurent22/joplin#10231]
### Operating system

Windows

### Joplin version

3.0.2

### Desktop version info

Joplin 3.0.2 (dev, win32)

Client ID: 8a192868cad6461aa4b81f41e9b0f5d9
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: 06aa64016 (dev)

Backup: 1.4.1
BibTeX: 0.5.0
Delete notes without confirmation: 1.0.0
Rich Markdown: 0.13.4

### Current behaviour

The undo and redo options in the window menu bar don't work when a new line is inserted although the `ctrl+z` and `ctrl+shift+z` work. the undo and redo only work on the first line of the note.

This is a video producing the issue.

https://github.com/laurent22/joplin/assets/113056556/52869c16-1737-431d-9fce-09a226f048de

I think it's a bug from the electron framework, as we use the built-in undo and redo actions in electron.

**Code Snippet from [Menu.tsx](https://github.com/laurent22/joplin/blob/3062f833671884b9b4707457a2ce7f9d8cfda2a3/packages/app-desktop/gui/MenuBar.tsx#L700)**
``` javascript
// Using the generic "undo"/"redo" roles mean the menu
// item will work in every text fields, whether it's the
// editor or a regular text field.
{
	role: 'undo',
	label: _('Undo'),
},
{
	role: 'redo',
	label: _('Redo'),
},
```

So, we may disable them or implement our undo and redo functionalities and override them. 

#9584 Related issue.

### Expected behaviour

undo and redo options should work on all lines like the `ctrl+z` and `ctrl+shift+z`

**Comment by DarkFalc0n** [comment]
I couldn't recreate this in my Arch Linux system, the undo and redo buttons are working for me.
Im using an older version, 2.14.20

**Comment by ab-elhaddad** [comment]
It doesn't work either in version 2.14.20. But I am using Windows in both versions, so it may be a Windows-related bug.

https://github.com/laurent22/joplin/assets/113056556/3765eacc-0187-40b4-980f-96697d0871ea

**Comment by khalidkhankakar** [comment]
`{
    role: 'undo',
    label: _('Undo'),
    // Assign the handleUndo function to the click event of the menu item
    click: handleUndo
},
`
`
{
    role: 'redo',
    label: _('Redo'),
    // Assign the handleRedo function to the click event of the menu item
    click: handleRedo
}`

I think it wil work when we pass function to this like handleUndo and handleRedo
