### ISSUE TITLE
Cannot create a new note or to-do after Joplin shutdown with All Notes or a tag selected in the sidebar

### ISSUE THREAD

**Issue by dpoulton-github** [laurent22/joplin#10230]
### Operating system

Linux

### Joplin version

2.14.20 & 3.0.2

### Desktop version info

**Joplin 2.14.20 (prod, linux)**
Client ID: 78fda5cfc2b24f6d98003028e039cf15
Sync Version: 3
Profile Version: 46
Keychain Supported: No
Revision: cfd98e3
Backup: 1.4.0

**Joplin 3.0.2 (prod, linux)**
Client ID: 78fda5cfc2b24f6d98003028e039cf15
Sync Version: 3
Profile Version: 46
Keychain Supported: No
Revision: a59ad20
Backup: 1.4.0

### Current behaviour

Vanilla install, no non-default plugins, customisations or changes to default settings. No sync.

If Joplin 2.14.20 is shut down with "All Notes" or a tag selected in the sidebar, upon restart Joplin opens with the same sidebar item selected. However a new note or todo cannot be created. The buttons above the note list and in the file menu options are "greyed out" and the keyboard shortcuts do not work. New notes and todos can only be created again (the options become live) after first selecting a notebook. After this a new note or todo can be created with "All notes" or a tag selected in the sidebar.

For Joplin 3.0.2 the same occurs for tags but this time not for All notes. However if you shut down Joplin with Trash selected (trash does not display the new note / todo buttons), when you start Joplin again if you click on any tags they too do not display new note / todo buttons at all until a notebook has first been selected.

For both versions if Joplin is shut down with a _notebook_ selected there are no issues when Joplin is restarted.

### Expected behaviour

Ideally the ability to create notes / todos would be consistent and the same as before the application was shut down.

**Comment by personalizedrefrigerator** [comment]
I can reproduce this on Ubuntu 23.10 with Joplin 2.14.20.

**Comment by laurent22** [comment]
Could it be related to this PR? https://github.com/laurent22/joplin/pull/10021

**Comment by HahaBill** [comment]
I can reproduce this in macOS Sonoma 14.3.1 for Joplin 2.14.20 and Joplin Dev 3.0.2. I tried to revert my changes in PR #10021 and test it, but they seem unrelated since the problem persists.

I have other observations here. When I click the Trash folder and then click All Notes or tags, I do not see 'create a new note,' 'search bar,' 'sort selection,' or 'to-do buttons.' 

But when I click notebook and then All Notes or tags, I see the 'create new note', 'search bar', 'sort selection', and 'to-do buttons' again. You do not need to shut down Joplin to produce this bug. If someone else hasn't done it, I will create an issue of this.

**Comment by HahaBill** [comment]
Joplin 3.0.2 (dev, darwin)

Client ID: 004ab82932304ae7a03ad62a3757f7b3
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: cbe0f956c (dev)

Backup: 1.4.1

Hi guys, I've just run the app and then shutdown and I do not encounter this issue anymore when I updated my forked repo. @dpoulton-github Can you also test this and verify?

Also clicking Trash folder first and then All notes folder does not make the creating note 'create a new note,' 'search bar,' 'sort selection,' or 'to-do buttons.' disappear anymore. It seems like new commits fixed the issue!

**Comment by HahaBill** [comment]
> I can reproduce this in macOS Sonoma 14.3.1 for Joplin 2.14.20 and Joplin Dev 3.0.2. I tried to revert my changes in PR #10021 and test it, but they seem unrelated since the problem persists.
> 
> I have other observations here. When I click the Trash folder and then click All Notes or tags, I do not see 'create a new note,' 'search bar,' 'sort selection,' or 'to-do buttons.'
> 
> But when I click notebook and then All Notes or tags, I see the 'create new note', 'search bar', 'sort selection', and 'to-do buttons' again. You do not need to shut down Joplin to produce this bug. If someone else hasn't done it, I will create an issue of this.

Joplin 3.0.2 (dev, darwin)

Client ID: 004ab82932304ae7a03ad62a3757f7b3
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: cbe0f956c (dev)

Backup: 1.4.1

I updated my forked repo.

Clicking Trash folder first and then All notes folder does not make the creating note 'create a new note,' 'search bar,' 'sort selection,' or 'to-do buttons.' disappear anymore. It seems like new commits fixed the issue!

**Comment by personalizedrefrigerator** [comment]
I can reproduce this when running from commit 15770e92988c7bd02fed60066da160cad3de331b.
