### ISSUE TITLE
Mobile: Add a way to ignore sync issues related to a specific attachment

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#10245]
### Operating system

Android

### Joplin version

3.0.2

### Current behaviour

Currently, it doesn't seem to be possible to fix certain types of attachment-related sync issues without reinstalling Joplin Mobile. Sometimes, these issues only affect 1-2 attachments and can be safely ignored. At present, however, there doesn't seem to be a way to dismiss the "some items could not be synchronized" banner.

One possible solution would be to add an ignore button to the list of synchronization errors (perhaps just below the "retry" button). If all sync errors are ignored or resolved, the "some items could not be synchronized" banner should no longer be shown.

See also [this post on the Joplin forum](https://discourse.joplinapp.org/t/repaeted-sync-problem/37008/2).

### Expected behaviour

It should be possible to hide the "some items could not be synchronized" banner.

**Comment by luisriverag** [comment]
Yes please
