### ISSUE TITLE
Sort notes utility is visible even without any notes in a notebook.

### ISSUE THREAD

**Issue by DarkFalc0n** [laurent22/joplin#10249]
### Operating system

Linux

### Joplin version

2.14.20 (prod, linux)

### Desktop version info

Joplin 2.14.20 (prod, linux)

Client ID: c517f8cc3313466e904d92464e900f5e
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: cfd98e3

Backup: 1.4.0
Better Code Blocks: 1.1.0
BibTeX: 0.5.0

### Current behaviour

1. Create an empty notebook, the note sort type switching button is visible even without any notes.
2. Start typing some text in the search bar of the notes section inside the notebook, the sort button disappears.
3. Close the search utility using the close button, the sort button reappears.
4. Delete all notebooks, the sort button still stays.
5. Repeat step 2
6. This time the sort button does not return even after closing the search bar.

### Expected behaviour

The sort button should only be visible when there are any notes to display.

**Comment by SySagar** [comment]
I would like to work on this
