### ISSUE TITLE
Fixed `selectedFolderId` value when going from the trash folder to "All notes"

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10259]
Fixing this should address various strange behaviours related to the trash folder and "all notes".

> I have tried using props.selectedFolderId, it is failing in some cases. When there are no notebooks and the app opens to the "all notes" screen, the initial selectedFolderId is null. Then if we go to trash folder, it is set to the trash folder id. Now, if we go back to "all notes" screen, the value of the selectedFolderId still remains the same as the trash folder id and the "There are no notes here." message is shown. This doesn't occur when using the parentId from the notesSource as it updates to the ALL_NOTES_FILTER_ID when we go back to "all notes" screen.

Ref: https://github.com/laurent22/joplin/pull/10201/files#r1546220109

**Comment by Sidd-R** [comment]
This same issue happens on desktop as well. I suggest we set the `selectedFolderId` to null when in "all notes" screen. We can dispatch this change when the` notesSource` updates and the `notesParentType` is equal to `SmartFilter`.

**Comment by laurent22** [comment]
With all the recent changes regarding the trash folder and selected folder it's hard to tell what remains to be done here. Instead let's focus on fixing specific bugs and that's when we're going to improve how selectedFolderId is handled (if necessary).
