### ISSUE TITLE
Input fields all over the application are disabled after showing message dialog

### ISSUE THREAD

**Issue by ab-elhaddad** [laurent22/joplin#10251]
### Operating system

Windows

### Joplin version

2.14.20, 3.0.2

### Current behaviour

1. Open application settings
2. Write anything in any input field without saving it
3. Switch to the encryption screen
4. A dialog with warning is shown (take any action doesn't matter)
5. **All input fields in the application are disabled**
6. Switch to another window and come back again to joplin
7. All input fields work normally

https://github.com/laurent22/joplin/assets/113056556/9de376cb-cdc2-4d68-bf5a-39ac7d9164f3

https://github.com/laurent22/joplin/assets/113056556/10b8b29c-0854-4e7d-bd1b-bc8d0f6acbd0

### Expected behaviour

Input fields should work all the time and not be affected by a warning dialog

**Comment by laurent22** [comment]
I cannot replicate this on macOS

**Comment by ab-elhaddad** [comment]
I couldn't replicate it on Ubuntu either. But I replicated it on several Windows machines. I am not sure why does it appears only on Windows.

**Comment by Aitchessbee** [comment]
I can replicate it when I run Joplin code on my pc locally... Cannot replicate it in the downloaded Joplin desktop app.

Operating system - PopOS (linux)
