### ISSUE TITLE
old.reddit pages are not saved correctly as HTML by the Web Clipper

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10274]
Ref: https://discourse.joplinapp.org/t/support-for-singlefile/37407

- Clip this page: https://old.reddit.com/r/literature/comments/17a9o2v/whats_your_favourite_japanese_contemporary_or/

=> Open the RTE: All comments are missing

=> Open the Markdown viewer: formatting is better but all comments are missing too

They are actually in the HTML but for some reason are hidden by default, so maybe the CSS or something else needs to be tweaked.

**Comment by DarkFalc0n** [comment]
I copy pasted the html output from Joplin to a seperate HTML file and it seems to be working fine in Chromium based browsers. It may as well be a limitation of the markdown viewer.

**Comment by Aitchessbee** [comment]
I also noticed that switching to rich text editor and, making some text change, then switching back to markdown editor caused the comments to disappear from the HTML code.

**Comment by DarkFalc0n** [comment]
This is related to `<form>` tag, that doesn't render in markdown. All comments are wrapped in `<form>` tags and hence invisible. I tried to work on this but the dev web clipper extension throws an error like this:
```
"error":"Internal Server Error: Cannot create property 'httpCode' on string 'Image at /home/darkfalcon/.config/joplin-desktop/tmp/pixel_dde73b08250645e98d0f25e3b7f40a27.png failed to load.'
```
However, a straightforward fix would be to replace all `<form>` with something else that renders properly in markdown.

**Comment by silversheaf** [comment]
Hi -- was just wondering why this was marked completed? The problem still seems to be happening (I have the latest version)... @laurent22
