### ISSUE TITLE
Strikethrough button missing as part of toolbar

### ISSUE THREAD

**Issue by mcmxcdev** [laurent22/joplin#10278]
### Operating system

Linux

### Joplin version

3.0.2

### Desktop version info

Joplin 3.0.2 (prod, linux)

Client ID: f964f06935f348e1b58784c8abc9e8de
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: a59ad20

Backup: 1.4.0

### Current behaviour

I am able to use `~~` to mark text as strikethrough, but I am missing a shortcut button for it next to `B` and `I` in the toolbar:

![Screenshot from 2024-04-06 16-34-54](https://github.com/laurent22/joplin/assets/16797721/bcf3bc97-195c-4034-a4d9-3afffd542a4c)

### Expected behaviour

Add a strikethrough shortcut to the toolbar

This is how the button looks like in e.g. LibreOffice Writer: 
![image](https://github.com/laurent22/joplin/assets/16797721/bd3207a7-ad67-444d-9cf1-fdd8ba8d5961)

**Comment by Aitchessbee** [comment]
Is this feature missing for a reason or should I try to create a PR to add strikethrough button?

**Comment by dpoulton-github** [comment]
The [Menu items, Shortcuts, Toolbar icons plugin](https://joplin.github.io/website-plugin-discovery/plugin/cx.evermeet.tessus.menu-shortcut-toolbar/) adds highlight (mark), strikethrough, underline, superscript, and subscript to the toolbar.

![ksnip_20240430-142117](https://github.com/laurent22/joplin/assets/60117449/c9ef23c0-83af-4f2a-becd-1f849b53ef6b)

**Comment by mcmxcdev** [comment]
If there is a bold and italic button without using any plugins, I would consider strikethrough also one of the "basic" actions without needing a plugin.

That plugin hasn't been updated in a couple years so I am a bit hesistant.

**Comment by dpoulton-github** [comment]
I have been using it without any problem since it was written and I am now on Joplin 2.14.20.

> That plugin hasn't been updated in a couple years so I am a bit hesistant.

I guess that it has not been updated because there's not really anything to update or make better.

**Comment by mcmxcdev** [comment]
Not stale
