### ISSUE TITLE
Location of found notes not displayed

### ISSUE THREAD

**Issue by synk-a-dynka** [laurent22/joplin#1028]
### Operating system
- Linux

### Application
- Desktop

When searching I get a list of matching notes in the note list but there is no way of knowing which notebook the notes belong to. It's not indicated or displayed anywhere.

(In the Android app the parent notebook is displayed in the top bar when opening a searched and found note.)

**Comment by laurent22** [comment]
It's displayed in the toolbar, on the left side.

**Comment by synk-a-dynka** [comment]
I beg to differ. It is not displayed. 

The list of notebooks is displayed, but not a notation of which notebook the current searched and found note belongs to. If I browse my way to the note via the notebooks the parent notebook is marked. Searching and clicking a found note give no such indication.

If it is supposed to this is a bug report rather than a feature request.

**Comment by glowinthedark** [comment]
@laurent22: why has this issue been closed? It is still reproducible. 

Search for a string in the desktop version of Joplin — you only get a list of matching notes without any way to figure out which notebooks they belong to. 

Which toolbar you are talking about? There is no indication of the parent notebook. 

Also right-clicking the note doesn't show any menu entry (e.g. Note Info etc) which would display anything useful about the note hierarchy.
