### ISSUE TITLE
Note list: Slower to update in version 2.14 and 3.0 than 2.13

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#10284]
### Operating system

Linux

### Joplin version

3.0.2

### Desktop version info

Joplin 3.0.2 (dev, linux)

Client ID: 5cd73fa94f1c4847a76b5ee095980929
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: b3f441402

Backup: 1.4.1

### Current behaviour

See https://discourse.joplinapp.org/t/performance-issue/37207/19

In Joplin 2.14+, the note list takes several seconds to update its sorting, while in Joplin 2.13, it was very fast.

https://github.com/laurent22/joplin/assets/46334387/344b50c8-834d-4810-84d3-f5f881d07b81

### Expected behaviour

The note list sorting should update quickly in Joplin 2.14 and Joplin 3.0, as it did in Joplin 2.13.

**Comment by personalizedrefrigerator** [comment]
Likely related to/a duplicate of https://github.com/laurent22/joplin/issues/10203

**Comment by HahaBill** [comment]
First of all, great bug report! I will have a look and tell you what I've discovered.

**Comment by HahaBill** [comment]
Alright, I got an update: The problem seems to be in the `NOTE_SORT`, where there is a timeout of 2 seconds in `sortNoteListTimeout`. I changed it to 0 seconds, and it was immediately fast and solved the issue! However, in the comments, the purpose of this delay was stated.  

```typescript
if (sortNoteList) {
		if (sortNoteListTimeout) shim.clearTimeout(sortNoteListTimeout);
		sortNoteListTimeout = null;

		// We sort the note lists with two seconds debounce because doing can be
		// very slow and would have to be done every time a note is added.
		if (Date.now() - newState.noteListLastSortTime > 10000) {
			dispatch({ type: 'NOTE_SORT' });
		} else {
			sortNoteListTimeout = shim.setTimeout(() => {
				sortNoteListTimeout = null;
				dispatch({ type: 'NOTE_SORT' });
			}, 2000);
		}
	}
```

**Comment by HahaBill** [comment]
> Alright, I got an update: The problem seems to be in the `NOTE_SORT`, where there is a timeout of 2 seconds in `sortNoteListTimeout`. I changed it to 0 seconds, and it was immediately fast and solved the issue! However, in the comments, the purpose of this delay was stated.
> 
> ```ts
> if (sortNoteList) {
> 		if (sortNoteListTimeout) shim.clearTimeout(sortNoteListTimeout);
> 		sortNoteListTimeout = null;
> 
> 		// We sort the note lists with two seconds debounce because doing can be
> 		// very slow and would have to be done every time a note is added.
> 		if (Date.now() - newState.noteListLastSortTime > 10000) {
> 			dispatch({ type: 'NOTE_SORT' });
> 		} else {
> 			sortNoteListTimeout = shim.setTimeout(() => {
> 				sortNoteListTimeout = null;
> 				dispatch({ type: 'NOTE_SORT' });
> 			}, 2000);
> 		}
> 	}
> ```

Oh and one more thing. `NOTE_SORT` is used for both notes and to-dos, that also explains the #10203
