### ISSUE TITLE
Default note list: Alphabetic sorting icon is also used for due date and completion date sorting

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#10283]
### Operating system

Linux

### Joplin version

3.0.2

### Desktop version info

Joplin 3.0.2 (dev, linux)

Client ID: 5cd73fa94f1c4847a76b5ee095980929
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: b3f441402

Backup: 1.4.1

### Current behaviour

1. Open the welcome notebook
2. ~~Select the Alphabetic -- Ascending sort order~~ Cycle through the available sort orders, select the first one with the alphabetic sorting icon.
3. Compare between Joplin 2.14.20 and Joplin 3.0.2.
4. Repeat steps 2-3 for the other two sorting methods that use the same icon.

![screenshot: Compares Joplin 2.14.20 to Joplin 3.0.2 -- Joplin 3.0.2's note list shows alphabetic ascending sort selected (the same sort type as Joplin 2.14.20), but items are clearly not sorted alphabetic (ascending)](https://github.com/laurent22/joplin/assets/46334387/b8998420-5ab9-4924-b199-6e177d33e4d2)

**Edit**: A similar issue can be reproduced by:
1. Set the sort order to alphabetic
2. Create a new notebook
3. Create notes "1. A test", "2. B", "3. C", "4. D", "5. E"
5. Click "reverse sort order"
   - For me, nothing happens.
6. Set the content of "3. C" to `a`
   - For me, after about 1 second, the note moves to the end of the note list.

### Expected behaviour

When alphabetic sort is enabled, note list items should be sorted based on their titles.

**Comment by DarkFalc0n** [comment]
I couldn't recreate this in my Linux desktop, both versions sort in a similar manner.

**Comment by cagnusmarlsen** [comment]
Both versions sort the same for me too (same as the first example here)

**Comment by personalizedrefrigerator** [comment]
I'm able to reproduce this issue in a new profile. Here's a screen recording:


https://github.com/laurent22/joplin/assets/46334387/e804455c-6cef-482c-bd75-8d3847aa84e2

Above, I do the following:
1. Set the sort order to alphabetic
2. Create a new notebook
3. Create notes "1. A test", "2. B", "3. C", "4. D", "5. E"
4. Click "reverse sort order"

Observe that in step 4, the sort order doesn't change. Additionally, if I then edit "3. C", it moves to the end of the list, despite alphabetic sorting still being enabled (26s into the video below):

https://github.com/laurent22/joplin/assets/46334387/32279578-4cd6-4549-ae99-1eb9450ba4e3




<details><summary>Joplin client information</summary>

OS: Ubuntu 23.10

```
Joplin 3.0.2 (prod, linux)

Client ID: 00e8c808f0654f86b6ebdbc1fd8971e4
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: b3f441402

Backup: 1.4.1
RevealJS Integration: 0.7.0
```
</details>

**Comment by cagnusmarlsen** [comment]
I created a new profile and followed the steps you mentioned, but the sort toggle functionality still works correctly for me.

Ascending Order -
![sortorder1](https://github.com/laurent22/joplin/assets/91818868/8fd86de8-4e3f-40e5-9a95-cef4009eb20a)

Descending Order -
![sortorder2](https://github.com/laurent22/joplin/assets/91818868/40949316-56f2-4118-9cd5-e5c81a390bbe)

This is in Joplin 3.0.2 (dev, linux)

**Comment by personalizedrefrigerator** [comment]
I'm building from 2ae08ff46ed3db89ef1756863be7eae7cf4c9379 ("Mobile: Support importing from JEX files") and can also reproduce this on a different computer (MacOS). @cagnusmarlsen What commit are you building from?


**Edit**: It looks like it's trying to sort by due date:
![screenshot: Tooltip for "A" sort by says "due date"](https://github.com/laurent22/joplin/assets/46334387/3256e966-1003-477c-9e82-8d21c59390d3)

**Edit 2**: I think that this issue is being caused by [this commit](https://github.com/laurent22/joplin/commit/ce451c5850bac8e9818315bc1012dfab5e5182db#diff-168ba5d940478a01525a4306dd2640e1675202dba1951c02d48d2ef1e26d4d62R946).

**Comment by DarkFalc0n** [comment]
so it is only an icon mismatch issue ?

**Comment by personalizedrefrigerator** [comment]
> so it is only an icon mismatch issue ?

Based on the title of [this commit](https://github.com/laurent22/joplin/commit/ce451c5850bac8e9818315bc1012dfab5e5182db#diff-168ba5d940478a01525a4306dd2640e1675202dba1951c02d48d2ef1e26d4d62R946), I think that this change was only intended to affect the detailed note list and not the default.

In the detailed note list (which needs to be enabled in view > note list style), right-clicking on the titlebar allows showing "due" and "completed" columns, which can then be used to sort by due date or completed time.

**Comment by cagnusmarlsen** [comment]
I tried building from [2ae08ff](https://github.com/laurent22/joplin/commit/2ae08ff46ed3db89ef1756863be7eae7cf4c9379), it still works fine for me with correct sorting and no icon mismatch. I also tried this on a different computer (Windows 11) with the same result.

**Comment by laurent22** [comment]
I broke this, and I think I even removed the test that was telling me I broke it: https://github.com/laurent22/joplin/commit/28b8818c4de4b8fb7947edfeec5377345525c07e
