### ISSUE TITLE
Cracked phone screen locked me out of all my Joplin notes

### ISSUE THREAD

**Issue by kalexmills** [laurent22/joplin#10299]
### Operating system

Android

### Joplin version

2.14.9

### Current behaviour

I have biometrics enabled on my Joplin app. After cracking my phone screen the biometric identification on my Pixel Pro 6 no longer works properly. I can't even retrain the fingerprints. There does not appear to be any way to access the app at all in this case -- by design, I imagine. 

### Expected behaviour

Have a backup code in place to allow access in case of hardware failure.

**Comment by laurent22** [comment]
If you disable biometric on the device, then restart your phone, then Joplin should no longer ask you for your fingerprint

**Comment by kalexmills** [comment]
I have tried disabling fingerprints and restarting, but Joplin is still asking me for my fingerprint.

**Comment by laurent22** [comment]
That's strange, normally it's supposed to follow the phone setting. What if you enable it again, then delete all your fingerprints, disable it again, and restart your phone?
