### ISSUE TITLE
iOS editor not scrolling when keyboard is displaying

### ISSUE THREAD

**Issue by RCJacH** [laurent22/joplin#103]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---

Here's a screenshot
![Content below iOS keyboard is blocked](https://user-images.githubusercontent.com/12930244/34068690-bd1e493a-e27a-11e7-8db6-02aa9be76858.png)

As you can see, when the iOS keyboard is displaying, the content beneath the keyboard is blocked, and since the whole document is less than a page long, it is not possible to scroll to the bottom of the document to edit the lines that are blocked, unless a lot of empty lines are preserved in advance.

Is it possible to add a variable in iOS version (maybe android as well) so that when the keyboard is showing during input mode, the vertical size of the editor is reduced by the size of the keyboard?

**Comment by alexdevero** [comment]
I have the same issue:
![img_0896](https://user-images.githubusercontent.com/4237724/34610885-5e14679a-f223-11e7-9f70-0a9b1d6b4fd4.PNG)

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS (11.2.1)

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

**Comment by alexdevero** [comment]
@laurent22 This issue should be closed as solved.
