### ISSUE TITLE
[Feature Request] iOS mobile app Markdown keyboard or toolbar

### ISSUE THREAD

**Issue by casasfernando** [laurent22/joplin#1030]
### Operating system

- iOS

### Application

- Mobile

It would be great to have a Markdown toolbar or keyboard in the iOS app to be able to use Markdown styling without having to type Markdown sintax directly in the note. Something similar to this Markdown keyboard app would help: https://itunes.apple.com/us/app/markdown-keyboard/id945466386?mt=8

**Comment by protree** [comment]
Yes definitly!

What I do to make typing in iOS easier: I use Apple‘s built in text replacemant feature, e.g. „mb“ -> „- [ ]“ (MardownBullet)

**Comment by trymeouteh** [comment]
I totally agree. I would like this for Android also. This is a major thing that is missing on the mobile devices. By adding the toolbar it would allow Joplin to have a user-friendly way for making checkboxes and even making text bold.

Evernote has a toolbar in their mobile apps and by looking at how that is layed out would be a good toolbar for mobile devices, by having the toolbar appear above the OS keyboard.

**Comment by JOJ0** [comment]
Hi, I really love the idea of Joplin but for me one major usability issue is the lack of a toolbar in the markdown editor on ios. 

A slim toolbar could be shown as one line, containing only some (ideally configurable) items. The rest of the items could be hidden in a drop down, or even better, available by side-scrolling the toolbar. If you had a wysiwig editor (which I realised a lot of people voted for already) you’d definitely need a toolbar and would face the same space problems.

Another suggestion regarding small mobile screens: The top (blue) toolbar. IMHO takes a lot of unused space. It coul be slimmer. Also I dont think it’s necessary that the title of the currently edited note is always shown while editing. It would be enough if it’s shown wenn scrolling to the top of the note.

all the best and thanks a lot for all the work! I love that I can just host this on my own machines. The desktop editor is great and I am already checking out the commandline editor! Love it :-)
And yes I think somebody feature requested this already and I will vote for it: Markdown syntax highlighting in the mobile app would also be great. Just like in joplin cli.

Sorry I know this is more than one feature request and I should research if some of it has already been requested. Will do!

Jojo

**Comment by trymeouteh** [comment]
A suggestion I will have is to have one row but be able to have the row scrollable on the X axis. That will nake the toolbar small but pact with everything you need.

Just have to scroll left or right in the toolbar to find the bold button or checkbox button.

Another option besides scrolling is to have pages, have a arrow key and when you tap it to will scroll to the next row of options

**Comment by scottwallacesh** [comment]
Another way might be to manually enter a checkbox (e.g. `- [ ] `) the first time but then automatically add it on the next line after a hard enter.

**Comment by FuturePilot** [comment]
This issue has not been fixed.

**Comment by FuturePilot** [comment]
Still not been fixed

**Comment by JOJ0** [comment]
Hi @FuturePilot there is also a currently active discussion about this topic in the joplin forum: https://discourse.joplinapp.org/t/wysiwyg-editor-in-joplin/2253/23

**Comment by FuturePilot** [comment]
Not fixed

**Comment by JOJ0** [comment]
Hi @FuturePilot 

> Not fixed

well, that's not entirely true ;-) actually there is a very great beta feature out that gives you a markdown toolbar for a couple of things: https://github.com/laurent22/joplin/pull/2224

discourse topic: https://discourse.joplinapp.org/t/feature-request-list-continuation-on-mobile/1742/18

check it out!
all the best
Jojo

**Comment by FuturePilot** [comment]
Awesome! I was not aware of that work being done in #2224. That's exactly what I'm looking for! Hope to see that soon!

**Comment by JOJ0** [comment]
> Awesome! I was not aware of that work being done in #2224. That's exactly what I'm looking for! Hope to see that soon!

you can see that now already! Configuration - Note - Opt-in to the editor beta - enable

**Comment by FuturePilot** [comment]
> > Awesome! I was not aware of that work being done in #2224. That's exactly what I'm looking for! Hope to see that soon!
> 
> you can see that now already! Configuration - Note - Opt-in to the editor beta - enable

Awesome! This is great!

**Comment by SimonBrazell** [comment]
> you can see that now already! Configuration - Note - Opt-in to the editor beta - enable

@JOJ0 or @FuturePilot I know this was some time ago but I'm just new to Joplin and having a toolbar available on Android is a must for me, writing lists and checklists in markdown is too cumbersome, how do I enable this feature? 

I have installed Joplin v2.1.4 on my Android and I can't see any option in the Configuration > Notes section for this, is it no longer available or is there a beta build I need to get from somewhere to get the toolbar?

**Comment by JOJ0** [comment]
> > Awesome! I was not aware of that work being done in #2224. That's exactly what I'm looking for! Hope to see that soon!
> 
> 
> 
> you can see that now already! Configuration - Note - Opt-in to the editor beta - enable

that doesnt work anymore right? couldnt find it either

**Comment by JOJ0** [comment]
hi @SimonBrazell again, have a look at latest posts in https://github.com/laurent22/joplin/pull/2224#issuecomment-829369791

unfort. it's a react native shortcoming still :-(

**Comment by SimonBrazell** [comment]
Thanks @JOJ0 

Yeah damn, I can't really use the app without it, see I'm fine with Markdown but my partner isn't and we wanted to use it to share notes and checklists, having to type `- [ ] ...` each time you want to insert a checkbox is pretty painful. 

Do you know if there is a corresponding issue on the react native repo I could follow?

**Comment by semyl** [comment]
I came looking for this also for Android. I *can* type in `- [ ]` but it is a huge pain because it involves so many extra clicks on the mobile keyboard to get to the different symbols pages. 

Sometimes I copy and paste the `- [ ]` instead, but it is still more tedious than I like. So I end up just putting the text in a regular line, and then if I notice it on desktop I'll fix it then. Not ideal though.
