### ISSUE TITLE
After text input using ibus IME, immediately inputting a punctuation removes the text entered

### ISSUE THREAD

**Issue by UlyssesZh** [laurent22/joplin#10309]
### Operating system

Linux

### Joplin version

2.14.17

### Desktop version info

Joplin 2.14.17 (prod, linux)

Client ID: d58809e2a4fc48cb99c3cc5a8c18bfdd
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: 094175c

### Current behaviour

I am using the IME [ibus-rime](https://rime.im/download/#ibus-rime) on NixOS. First, input some text using the IME, and then immediately input a punctuation. The text that was just input will be deleted. If I wait for a while before inputting the punctuation, it is fine. I have only seen similar things in Joplin, not in any other desktop apps.

https://github.com/laurent22/joplin/assets/26196187/29a24da7-31c5-482f-915a-da33b6637c38

Reproduceable with no plugins enabled.

**Comment by personalizedrefrigerator** [comment]
Is this with the beta editor enabled? (See Settings > General > Opt-in to the editor beta).

Thank you for reporting this!

**Comment by UlyssesZh** [comment]
Beta editor does not have this bug as I just tried.

**Comment by laurent22** [comment]
That's good to know. We had some issues with IME and hopefully CM6 will have fixed some of these

**Comment by UlyssesZh** [comment]
Since beta editor is good, I think it can be closed.
