### ISSUE TITLE
Build fails because of git commit invocations

### ISSUE THREAD

**Issue by totikom** [laurent22/joplin#10306]
### Operating system

Linux

### Joplin version

2.14.20

### Current behaviour

When building `joplin`, inside `packages/default-plugins/buildDefaultPlugins.ts` a new `git` repo is created. The script tries to commit some changes, but fails, because on my machine `git` is configured to sign every commit.

### Expected behaviour

Before `git commit`, this code should disable commit signing (i.e. enforce default settings).

### Logs

➤ YN0000: [@joplin/app-desktop]: fatal: failed to write commit object
➤ YN0000: [@joplin/app-desktop]:     at makeError (/home/eugene/.cache/paru/clone/joplin/src/joplin-2.14.20/packages/utils/node_modules/execa/lib/error.js:60:11)
➤ YN0000: [@joplin/app-desktop]:     at handlePromise (/home/eugene/.cache/paru/clone/joplin/src/joplin-2.14.20/packages/utils/node_modules/execa/index.js:118:26)
➤ YN0000: [@joplin/app-desktop]:     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
➤ YN0000: [@joplin/app-desktop]:   shortMessage: 'Command failed with exit code 128: git commit -m Initial commit',
➤ YN0000: [@joplin/app-desktop]:   command: 'git commit -m Initial commit',
➤ YN0000: [@joplin/app-desktop]:   escapedCommand: 'git commit -m "Initial commit"',
➤ YN0000: [@joplin/app-desktop]:   exitCode: 128,
➤ YN0000: [@joplin/app-desktop]:   signal: undefined,
➤ YN0000: [@joplin/app-desktop]:   signalDescription: undefined,
➤ YN0000: [@joplin/app-desktop]:   stdout: '',
➤ YN0000: [@joplin/app-desktop]:   stderr: 'error: gpg failed to sign the data:\n' +
➤ YN0000: [@joplin/app-desktop]:     '[GNUPG:] KEY_CONSIDERED #my key id# 0\n' +
➤ YN0000: [@joplin/app-desktop]:     '[GNUPG:] BEGIN_SIGNING H8\n' +
➤ YN0000: [@joplin/app-desktop]:     '[GNUPG:] PINENTRY_LAUNCHED 986588 curses 1.3.0 /dev/pts/3 xterm-256color-italic :0 20620/1000/5 1000/1000 0\n' +
➤ YN0000: [@joplin/app-desktop]:     'gpg: signing failed: Timeout\n' +
➤ YN0000: [@joplin/app-desktop]:     '[GNUPG:] FAILURE sign \n' +
➤ YN0000: [@joplin/app-desktop]:     'gpg: signing failed: Timeout\n' +
➤ YN0000: [@joplin/app-desktop]:     '\n' +
➤ YN0000: [@joplin/app-desktop]:     'fatal: failed to write commit object',
➤ YN0000: [@joplin/app-desktop]:   failed: true,
➤ YN0000: [@joplin/app-desktop]:   timedOut: false,
➤ YN0000: [@joplin/app-desktop]:   isCanceled: false,
➤ YN0000: [@joplin/app-desktop]:   killed: false
➤ YN0000: [@joplin/app-desktop]: }

**Comment by laurent22** [comment]
I'm pretty sure we don't commit anything when building, that would cause so many problems. What command did you use?

**Comment by personalizedrefrigerator** [comment]
> I'm pretty sure we don't commit anything when building, that would cause so many problems. 

The commit was being done in the temporary git repository we use for building default plugins. The commit step seems to only be necessary when updating a default plugin patch file. I've disabled it — except when updating plugin patches — in #10308.

**Comment by totikom** [comment]
> > I'm pretty sure we don't commit anything when building, that would cause so many problems.
> 
> The commit was being done in the temporary git repository we use for building default plugins. The commit step seems to only be necessary when updating a default plugin patch file. I've disabled it — except when updating plugin patches — in #10308.

Yep, that's a much better solution, thank you.
