### ISSUE TITLE
Plugins update script stopped working?

### ISSUE THREAD

**Issue by alondmnt** [laurent22/joplin#10316]
### Operating system

macOS

### Joplin version

3.0.2

### Current behaviour

Pushed a plugin release yesterday: https://www.npmjs.com/package/joplin-plugin-tag-navigator
It hasn't updated in Joplin after 10 hours, which is unusual.
Also, the plugin repo hasn't updated in a few days.

**Comment by alondmnt** [comment]
I see it was updated a few hours ago.

**Comment by laurent22** [comment]
Yes sorry we had some issues with it, but it should be working again now

**Comment by alondmnt** [comment]
Seems to have happened again.
