### ISSUE TITLE
Note display / selection changes during text input

### ISSUE THREAD

**Issue by norbert-wiener** [laurent22/joplin#10318]
### Operating system

macOS

### Joplin version

3.0.2

### Desktop version info

Joplin 3.0.2 (prod, darwin)
Client ID: 48e4646500f94412ba1c3994d1126dee
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes
Revision: a59ad20
Backup: 1.4.0

### Current behaviour

Select a note. Start typing text into it. Joplin jumps to another note, and the list of notes no longer displays that note title. This repeats, i.e. after switching to a different note, typing into that one causes it to vanish and switch to another note. If I again select the All notes category, the All Notes category, the original note title reappears, and I can repeat this ad infinitum. Obviously this makes is impossible to enter any content in this client version / platform. I don't see this behavior on Windows or IOS.

### Expected behaviour

When I select a note and start typing I expect input focus to remain on that note, and for the list of notebook titles to continue displaying the title of the note being edited, subject to whatever sorting options are in effect.

**Comment by personalizedrefrigerator** [comment]
This may be fixed by https://github.com/laurent22/joplin/pull/10222.

**Comment by Dricc123** [comment]
I'm experiencing this with version 3.0.3 on Windows 10

**Comment by Dricc123** [comment]
duplicate of #10236

**Comment by norbert-wiener** [comment]
Confirmed this behavior still occurs with 3.0.3 on both macOS and Windows. Not sure when #10222 might make its way into a build, or if that is a user-configurable setting for All Notes.

**Comment by Dricc123** [comment]
> Confirmed this behavior still occurs with 3.0.3 on both macOS and Windows. Not sure when #10222 might make its way into a build, or if that is a user-configurable setting for All Notes.

it got fixed

**Comment by Dricc123** [comment]
I believe this issue can be closed
