### ISSUE TITLE
iOS: "Share to Joplin" is missing

### ISSUE THREAD

**Issue by robert-franklin** [laurent22/joplin#10311]
### Operating system

iOS

### Joplin version

12.14.6

### Current behaviour

1. Go to Safari and click the button to share a page.
2. Observe that there is no "Share to Joplin" option.
3. Try with both photos and notes.
4. Observe that there is no "Share to Joplin" option in either one.

### Expected behaviour

A "Share to Joplin" option should have been available.

**Comment by personalizedrefrigerator** [comment]
It's working for me on iOS 17.4.1. 
- Is Joplin visible under the "More" menu at the end of the share list?
- When sharing from Safari, does clicking "Options" in the share sheet (just below the title of the page), then clicking "Automatic" show Joplin in the list of share suggestions?
