### ISSUE TITLE
Add recording vocal memo

### ISSUE THREAD

**Issue by webafrancois** [laurent22/joplin#1032]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile

When we're using the app on smartphone, we can take a photo and add it to a note.
It would be great to add a vocal memo directly from the app. 
Of course, we can record it and add the file after but it's more complex for simple users.

Thanks a lot for this great software !

**Comment by Stele77** [comment]
I would add that it now only is more complex for simple users (meaning beginners?) but also for every user.
With the most used note taking apps like evernote the user would ony tap on an icon once for a recording, which then is automatically saved.
Right now for this to do in Joplin is impossible in a timely manner (e.g. as a spontenious quick voice note, when recording important parts of a speech) and manually inserting the file is so time consuming that it will not be practical for anything more than casual use.
I would also add that this is another of those features where Joplin needs parity to the market leaders like Evernote for most of their users to be able to switch to a FOSS alternative like Jolin. And those users switching IMHO drive the adoption of Joplin the most.

**Comment by Araly** [comment]
I'd love to have that. For now I'm writing my notes on Joplin, but I'm recording audio notes on the microphone app of my phone. When I do audio notes it's that I can't write a normal note, so attaching it to a joplin note would break the purpose for me. I'd love to have a button, like a widget or something that you can click, automatically starts recording and saves the note to some default notebook.

#468 also talks about this feature

**Comment by foxmask** [comment]
is that not a dup of #468 ?

**Comment by Araly** [comment]
I think so, and yesterday I had seen yet another duplicate with other words, but I can't find it. I prefered to reply on this one as the last comments were more recent, but maybe It'd be smarter to bring back conversation to the other issue ? I don't know really what's prefered

**Comment by foxmask** [comment]
we prefer KISS (keep it simple & smart;)

**Comment by Araly** [comment]
alright, but that doesn't tell me how you're going to keep it simple. Should we then move discussion to the old issue ? Is there some other way you want to do that ?

**Comment by foxmask** [comment]
ok :) so let's continue on the other one. #468
