### ISSUE TITLE
安装joplin全部插件报错，无法正常使用。

### ISSUE THREAD

**Issue by ShangTianYa** [laurent22/joplin#10320]
### Operating system

Linux

### Joplin version

Flatpak2.14.20Linux

### Desktop version info

Flatpak2.14.20Linux-Debian12GnomeStable-Kernel6.1.0-20-amd64

### Current behaviour

[noteoverview.log](https://github.com/laurent22/joplin/files/15004412/noteoverview.log)
1、使用flatpak进行安装joplin后发现无法使用搜索公里进行直接安装，只能选择下载插件后进行一个一个点击进行使用。
2、后因为本人太懒惰嫌弃太麻烦，进行git joplin所有源代码，将源代码plugins目录下全部插件进行随机重命名到Joplin插件目录“/home/shangtianorg/.config/joplin-desktop/plugins” 
![image](https://github.com/laurent22/joplin/assets/69330243/f63c1ee3-4cf9-4ba1-850c-294d506179fe)
![image](https://github.com/laurent22/joplin/assets/69330243/d56b8384-72fc-4b32-878d-342cea36d676)
共共计202插件。然后打开joplin直接无法正常使用
![image](https://github.com/laurent22/joplin/assets/69330243/84afd0bf-613e-46dd-9240-61fbdf3197c8)
抱歉我查询后没有日志信息，只有一个插件的日志信息
![image](https://github.com/laurent22/joplin/assets/69330243/a495ae83-35ea-456c-b0d5-443b299e7311)

### Expected behaviour

我希望你们能默认配置一些优秀的插件，避免大众进行麻烦的安装和配置，因为删除自己不想要的插件简单，但是安装插件很麻烦。能做到开箱即用最好。

### Logs

cat ~/noteoverview.log 
[2024-04-17 09:20:21.181] [info]  check all overviews
[2024-04-17 09:20:34.776] [info]  all overviews checked
[2024-04-17 09:29:19.372] [info]  check all overviews
[2024-04-17 09:29:20.279] [info]  all overviews checked
[2024-04-17 09:34:20.287] [info]  check all overviews
[2024-04-17 09:34:20.312] [info]  all overviews checked

**Comment by lambdakilo** [comment]
Could you rewrite this all in English?

**Comment by ifurther** [comment]
What is the "搜索公里" ?
