### ISSUE TITLE
Vim Mode Command Execution

### ISSUE THREAD

**Issue by mmh0000** [laurent22/joplin#10335]
### Operating system

Linux

### Joplin version

2.14.20

### Desktop version info

Joplin 2.14.20 (prod, linux)

Client ID: f180ffae00cc4eba93bf53f9181e7fdf
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: cfd98e3

Backup: 1.4.0
Freehand Drawing: 1.12.1

### Current behaviour

In the markdown editor, using vim mode's command execution operator results in the error message: 
`Not an editor command ":'<,'>!sort`

### Expected behaviour

Excepted Joplin to pass the selected text to the STDIN of the called application, then replace the selected text with the STDOUT of the called application.

**Comment by nakulbh** [comment]
hey @mmh0000 can you help me reproduce the bug

**Comment by mmh0000** [comment]
Certainly!  This is using the latest appimage version for Linux (2.14.20).


```
# A Simple VIM Mode Bug

1. Add a few lines:

cat
dog
moose
bear
fish
pig
cow

2. Press ESC to enter command mode

3. Use Visual Line Mode, shift+v, to select the lines from cat to cow.

4. Press : to enter command mode

5. Enter `!sort` (or any other external command)
```

![10335-demo](https://github.com/laurent22/joplin/assets/39450959/4bc84aa6-0818-4243-ac63-8c6bf0ec3ead)

**Comment by mmh0000** [comment]
Still broken
