### ISSUE TITLE
Incorrect line breaks when line ends with multiple spaces

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#1033]
https://discourse.joplin.cozic.net/t/md-line-break-with-2-spaces/1175

```
Line 1  
Line 2
```

And check https://markdown-it.github.io/

**Comment by subi54** [comment]
That's a feature isn't it? Moreover, people who have been using the app for a while, with numerous/long notes, will have to go back and edit everything.

**Comment by tessus** [comment]
Does this mean you change the behaviour that

```
Line1
Line2
```

renders as `Line1Line2`? This would mess up a lot of my notes.

**Comment by laurent22** [comment]
Please have a look at the forum link for more info - https://discourse.joplin.cozic.net/t/md-line-break-with-2-spaces/1175/3

**Comment by tessus** [comment]
I've read the forum entries, but you only said that the two spaces and newline are ignored and are considered a bug.
However, according to specification the current behaviour of `Line1\nLine2` to be rendered on two lines is also a bug. Therefore I asked the question above.

**Comment by subi54** [comment]
Exactly what @tessus commented.

Adding `two spaces also means a line break` so that people coming from other markdown editors feels at home is one thing but removing the current behaviour of the app is detrimental to current users and users coming from say Evernote or somesuch.

**Comment by matsest** [comment]
Isn't is possible to adhere to both that two+ spaces + newline renders line break as well as newline renders line break? 

That way new users coming from other .md-editors will feel at home and existing notes for users will not render differently (unless they explicitly filled their notes with two spaces+line break to render .. well, nothing -- which is unlikely)

**Comment by laurent22** [comment]
> Isn't is possible to adhere to both that two+ spaces + newline renders line break as well as newline renders line break?

Yes actually "anything + newline", should always render as "anything + newline". The current behaviour of not adding a newline when there are two spaces is a bug.
