### ISSUE TITLE
Noticeable lag when typing

### ISSUE THREAD

**Issue by Nicco94** [laurent22/joplin#10346]
### Operating system

Linux

### Joplin version

2.14.20

### Desktop version info

Joplin 2.14.20 (prod, linux)

ID del Client: 5c6e54dba54b47b29629d800a19fbda6
Sinc. versione: 3
Profilo versione: 46
Portachiavi supportato: No

Revisione: cfd98e3

Backup: 1.4.0

### Current behaviour

After some typing with no lag, there is a very annoying lag on each key press/mouse click, which makes the software almost unusable.
I tried disabling the spell check - as some users suggested some time ago - but noticed no change in the behavior.

### Expected behaviour

I expect no noticeable lag when typing or moving the cursor.

**Comment by laurent22** [comment]
How many tags do you have? Because there's a performance issue related to tags

**Comment by personalizedrefrigerator** [comment]
Decreasing the frequency of automatic backups could also help. To do this, go to to settings > backup and increase the "backup interval in hours" to a large number. Backups that happen in the background can slow down the app, particularly when there's a large number of notes.

**Comment by Nicco94** [comment]
> How many tags do you have? Because there's a performance issue related to tags

I have the problem also with no tags

**Comment by laurent22** [comment]
> > How many tags do you have? Because there's a performance issue related to tags
> 
> I have the problem also with no tags

Could you check if it's due to the Backup plugin doing the backup? You could click on Tools => Create Backup, and see if it causes the app to slow down

**Comment by Nicco94** [comment]
> > > How many tags do you have? Because there's a performance issue related to tags
> > 
> > 
> > I have the problem also with no tags
> 
> Could you check if it's due to the Backup plugin doing the backup? You could click on Tools => Create Backup, and see if it causes the app to slow down

Also with backup disabled. One thing that seems to trigger the problem is jumping around and editing quickly parts of the note that are far apart.

**Comment by personalizedrefrigerator** [comment]
> > > > How many tags do you have? Because there's a performance issue related to tags
> > > 
> > > 
> > > I have the problem also with no tags
> > 
> > 
> > Could you check if it's due to the Backup plugin doing the backup? You could click on Tools => Create Backup, and see if it causes the app to slow down
> 
> Also with backup disabled. One thing that seems to trigger the problem is jumping around and editing quickly parts of the note that are far apart.

Is this with the rich text editor or the markdown editor? Is the beta markdown editor enabled (settings > general > opt-in to the beta markdown editor)?

<details><summary>How to determine if the rich text or markdown editor is enabled.</summary>

If in the markdown editor, the "toggle editors" button should look like this: <img alt="screenshot: Toggle editors, markdown (left) side is a darker grey" src="https://github.com/laurent22/joplin/assets/46334387/f8de7e66-fc7f-4ac4-9338-adaea53a57e4" width="100"/>. If in the rich text editor, it should look like this: <img alt="screenshot: Toggle editors, markdown side is a lighter grey" src="https://github.com/laurent22/joplin/assets/46334387/74ff02be-ca7e-47f6-931f-a24c33247b69" width="100"/>.

</details>

**Comment by Nicco94** [comment]
> > > > > How many tags do you have? Because there's a performance issue related to tags
> > > > 
> > > > 
> > > > I have the problem also with no tags
> > > 
> > > 
> > > Could you check if it's due to the Backup plugin doing the backup? You could click on Tools => Create Backup, and see if it causes the app to slow down
> > 
> > 
> > Also with backup disabled. One thing that seems to trigger the problem is jumping around and editing quickly parts of the note that are far apart.
> 
> Is this with the rich text editor or the markdown editor? Is the beta markdown editor enabled (settings > general > opt-in to the beta markdown editor)?
> How to determine if the rich text or markdown editor is enabled.

I noticed it with both markdown (preview on and off) and rich text editor. The beta markdown is not enabled.
One way I found to reproduce the issue (most of the time) is to quickly delete the last 2/3 characters of several lines (I was deleting trailing spaces in a list)
