### ISSUE TITLE
`Network request failed` when trying to sync

### ISSUE THREAD

**Issue by K4LCIFER** [laurent22/joplin#10340]
### Operating system

Android

### Joplin version

3.0.1 also 2.14.9

### Current behaviour

Syncing fails with an error saying `Network request failed`
```
1. Set up a sync with WebDAV, or Nextcloud
2. Enter in credentials, and WebDAV URL
3. Tap  "Check synchronization settings"
4. Observe that it fails and that the error `Network request failed` is displayed.
```

---

Just some extra context: I'm running Nextcloud as the AIO docker container behind a Caddy reverse proxy. This issue seems to have only started after switching to Nextcloud AIO with Caddy from the Snap. 

I also know that Nextcloud, and WebDAV sync is working fine because the exact same URL and credentials work in the Flatpak version of Joplin (v.2.14.20).

### Expected behaviour

I would expect sync to work. It worked in the past.

### Logs

[Fdroid Logs](https://github.com/laurent22/joplin/files/15050658/mobile-log.log)
[Google Play Logs](https://github.com/laurent22/joplin/files/15050677/mobile-log-2.log)

**Comment by laurent22** [comment]
Make sure the reverse proxy pass the complete data to and from Nextcloud, in particular headers. I know that a missing content-type header for example would cause this error (error reporting in the framework we use, React Native, is extremely vague). Also could probably happen with custom TLS certificates

**Comment by ViktorF** [comment]
I had the same problem.
I recently migrated my Nextcloud to a new host and reinstalled it from scratch.
I had misconfigured my SSL in nginx. It didn't provide the full certificate chain, which then triggered the "network request failed" error in joplin.
Fixing this allowed me to synchronise with nextcloud.

**Comment by K4LCIFER** [comment]
I am no longer using Joplin, so I can no longer test this issue.
