### ISSUE TITLE
Recorded location is vague

### ISSUE THREAD

**Issue by metafarion** [laurent22/joplin#10347]
### Operating system

Android

### Joplin version

3.0.2

### Current behaviour

The geo-location data on notes created on my phone doesn't seem to be very precise.  It has correctly identified my city, but nothing else.  I'm running a Pixel 6 with Android 14

### Expected behaviour

When granted Precise Location permissions, shouldn't the GPS be used to derive my exact location?  It seems to only be using my IP.

**Comment by laurent22** [comment]
When you create a new note, is there any information regarding geo-location in the log? I believe it should indeed only use the phone GPS for this and should be precise, but maybe there's an error. You can find the log info as described here: https://joplinapp.org/debugging

**Comment by metafarion** [comment]
Hmmm, this is peculiar.  I'm not sure what has changed since my prior tests, but now my location is being reported as somewhere in France.  Looking at the App Permissions for Joplin in the android settings, I can reconfirm that it has location permissions, though curiously it says last accessed over an hour ago.  So my current tests do not even seem to be trying to use the GPS, but are still attaching some kind of default location.
I dug through the logs a bit, and I can see the lines for "fetching geolocation" "Got lat/long" "Updating lat/long of note" for each note, but no errors in their vicinity.

**Comment by laurent22** [comment]
Where in France exactly? and are you not in France? Also where did you get this app version from?

**Comment by metafarion** [comment]
Oh sorry, no I'm in the US.  But the location 48.73219094, -3.45966339 is now being assigned to every note I create on my phone.  This version of Joplin is from FDroid

**Comment by laurent22** [comment]
> Oh sorry, no I'm in the US. But the location 48.73219094, -3.45966339 is now being assigned to every note I create on my phone. This version of Joplin is from FDroid

That's the location used in a dev environment which means your app somehow is in dev mode. Unless we made a mistake somewhere it seems it's F-Droid that's publishing a dev version of the app so you might want to let them know. We don't manage this particular distribution.

**Comment by metafarion** [comment]
Alright, so after some discussion with the F-Droid people, it turns out the geolocation problem is a consequence of them not wanting any FOSS software or dependencies in their repository at all.  Specifically in this case, it's an objection to the use of Google location services: https://gitlab.com/fdroid/fdroiddata/-/issues/3248#note_1876008277

So this might be a show-stopper for the F-Droid version of Joplin, but I thought you should be aware if you aren't already, and perhaps there is a FOSS geolocation method that could be used instead, though I understand that's probably a good deal more work.

**Comment by laurent22** [comment]
Thanks for looking into this, that's good to know. I guess they patched this part of the code then and probably the easiest way was to make it follow the dev code path.

I guess we could make it fallback to use an IP-based geolocation like on desktop but that would require some extra work which I'm not sure is worth it. If someone is willing to create a PR for it though I'd be ok with it

**Comment by licaon-kter** [comment]
> Specifically in this case, it's an objection to the use of Google location services:

not quite true actually :), it's not a matter of services but of libs used to access whose services, and those libs are themselves or depend on other libs that are non-FOSS.
