### ISSUE TITLE
Typing messed up in latest Android version 3.0.2

### ISSUE THREAD

**Issue by foodfan** [laurent22/joplin#10352]
### Operating system

Android

### Joplin version

3.0.2

### Current behaviour

1. Open new note
2. Start swipe typing using GBoard 
3. Last letter of each word gets cut off, making it impossible to type accurately
4. Same happens with other keyboards and normal tap typing.

This was not a problem with the last version. (I'm on Android 14 pixel 7) Please fix. Thanks

### Expected behaviour

Finish typing word, cursor moves on to the next word, instead of cutting off the last letter of the previous word.

**Comment by personalizedrefrigerator** [comment]
I haven't been able to reproduce this locally, but could it be related to [this upstream CodeMirror issue](https://github.com/codemirror/dev/issues/1358)?

(Thank you for reporting this!)

**Comment by foodfan** [comment]
> I haven't been able to reproduce this locally, but could it be related to [this upstream CodeMirror issue](https://github.com/codemirror/dev/issues/1358)?
> 
> (Thank you for reporting this!)

It might be, but here is a video of the problem. Looks like it places the cursor in the wrong place, creating multiple misspellings, making typing impossible.

https://github.com/laurent22/joplin/assets/43094559/b001f5b4-6177-4b36-b2f5-fe1a8e81deec
