### ISSUE TITLE
The flatpak build has a GitHub username instead of a Name

### ISSUE THREAD

**Issue by LaurentBonnaud** [laurent22/joplin#10363]
### Operating system

Linux

### Joplin version

2.14.20

### Desktop version info

Joplin 2.14.20 (prod, linux)

Client ID: d7803e220f0c4b76bcf457d62aed30e6
Sync Version: 3
Profile Version: 46
Keychain Supported: No

### Current behaviour

Your GitHub username (laurent22) is used as an application Name:
```
$ flatpak list
Name                             Application ID                          Version         Branch       Origin       Installation
[...]
laurent22                        net.cozic.joplin_desktop                2.14.20         stable       flathub      system
```

### Expected behaviour

"Joplin" instead of "laurent22"

**Comment by laurent22** [comment]
We don't manage the flatpak release so that should be reported on their repository
