### ISSUE TITLE
Ctrl + Shift + S inconsistency

### ISSUE THREAD

**Issue by lambdakilo** [laurent22/joplin#10369]
### Operating system

Windows

### Joplin version

2.14.20

### Desktop version info

Joplin 2.14.20 (prod, win32)

Client ID: 44a105c3e48447908ea3dee79c3453f9
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: cfd98e3

Backup: 1.4.0

### Current behaviour

1. Ctrl + Shift + S to focus sidebar
2. Press Down 3 times
3. On the third Down the focus goes down one note in the notes list

### Expected behaviour

The Sidebar focus should stay on sidebar unless otherwise commanded. This same issue works if the Notebook hits the top, losing the focus to the note list instead.

### Logs

No relevant logs since this might be a bug not an error.

**Comment by laurent22** [comment]
I think the loss of focus to the note list is fixed in v3

**Comment by lambdakilo** [comment]
You're right. Tried to replicate the bug on 3.0.3 portable.exe and it has been fixed. Thanks and sorry for not trying out the pre-release first! ❤️
