### ISSUE TITLE
Add more option when long pressing the icon on mobile

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10374]
Currently we have only "New note", and "New to-do"

We should add shortcuts for:

- New photo
- New attachment
- New drawing
- New voice typing note

Each of these would create a new note, and automatically start the camera, or a drawing, etc.

**Comment by personalizedrefrigerator** [comment]
I'm adding the `mobile` label — the "new note" and "new to-do" options seem to be present on iOS as well.

**Comment by mptpro** [comment]
It would be great to also have Android home screen shortcuts for "voice note" and "document scan".

thanks
