### ISSUE TITLE
Plugin settings stored with `SettingStorageType.File` occasionally lost when restarting Joplin

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#10381]
### Operating system

Linux

### Joplin version

2.14.20

### Desktop version info

Joplin 2.14.20 (prod, linux)

Client ID: 24b2a961cccf40fe8448cdc0930b6fce
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: cfd98e3a4

Backup: 1.4.0
CodeMirror 6 settings: 1.0.0
CodeMirror 6 snippets: 0.0.5
Custom CodeMirror .vimrc: 1.0.6
Freehand Drawing: 2.9.1
RevealJS Integration: 0.13.0
Work tracker: 0.0.1

### Current behaviour

Occasionally, after restarting Joplin, all settings for certain plugins (which are stored with [`SettingStorage.File`](https://joplinapp.org/api/references/plugin_api/enums/settingstorage.html#file)) are lost.

Downstream issues:
- https://github.com/personalizedrefrigerator/joplin-plugin-extra-editor-settings/issues/1
- https://github.com/personalizedrefrigerator/joplin-plugin-codemirror-6-snippets/issues/2

### Expected behaviour

Settings should not be lost when restarting Joplin.

**Comment by laurent22** [comment]
I don't know if this is related but I have this error related to plugins and settings when the application starts:

<img width="834" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/f6aa5b7b-3009-4f1d-93e8-abb7ba6955ea">

I assume it's some kind of race condition, maybe the same plugin call setSetting multiple times and some of the calls are dropped. For the db, it causes this error and maybe when saving to file it's overwriting the file with old data.

**Comment by personalizedrefrigerator** [comment]
The issue seems to be that `Setting.saveAll` can be called before plugin file settings are loaded. This call to `.saveAll` overwrites `settings.json` with only the currently-loaded settings. As such, when plugin settings are later registered and loaded, `settings.json` no longer contains the plugin's settings.
