### ISSUE TITLE
Plugins: Default values not applied for `SettingStorageType.File` settings 

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#10382]
### Operating system

Linux

### Joplin version

2.14.20, 3.0.3

### Desktop version info

Joplin 2.14.20 (prod, linux)

Client ID: 24b2a961cccf40fe8448cdc0930b6fce
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: cfd98e3a4

Backup: 1.4.0
CodeMirror 6 settings: 1.0.0
CodeMirror 6 snippets: 0.0.5
Custom CodeMirror .vimrc: 1.0.6
Freehand Drawing: 2.9.1
RevealJS Integration: 0.13.0
Work tracker: 0.0.1

### Current behaviour

1. Install the [CodeMirror 6 settings](https://joplinapp.org/plugins/plugin/io.github.personalizedrefrigerator.codemirror6-settings/) plugin
2. Restart Joplin
3. Open settings for the CodeMirror 6 settings plugin
4. Observe that "show line numbers" is unchecked, even though [the default value for that setting is `true`](https://github.com/personalizedrefrigerator/joplin-plugin-extra-editor-settings/blob/efe23cedb1731199a46e1de0c98e875f1bea207a/src/settings.ts#L23).

### Expected behaviour

Default values of file-storage settings should be respected.

**Comment by jahoyne** [comment]
This is the status here after your recent changes, hope it's helpful.

> Fixed: Fix default values for plugin settings stored in `settings.json` not applied ([#10383](https://github.com/laurent22/joplin/pull/10383)) ([#10382](https://github.com/laurent22/joplin/issues/10382) by [@personalizedrefrigerator](https://github.com/personalizedrefrigerator))

**Joplin 3.0.7** (prod, **linux**)

Client ID: 615c7880d02145c5a89371d6264bdcb9
Sync Version: 3
Profile Version: 47
Keychain Supported: No
Revision: 8330833

<details>
<summary><b>Installed plugins</b></summary>

Admonition markdown extension: 1.1.0
Backup: 1.4.1
CodeMirror 6 settings: 1.0.0
CodeMirror 6 snippets: 0.0.8
Conflict Resolution: 1.2.3
Copy Code Blocks: 1.1.0
Copy Universal Web Link: 0.1.0
Create and go to #tags and @notebooks: 1.3.7
Draw.io: 2.2.0
Embed Search: 2.0.0
Enhancement: 1.2.1
History Panel: 1.0.2
Home Note: 2.0.0
Hotfolder: 1.1.1
Inline tags: 1.3.0
Insert Date: 1.0.1
Joplin debug tool: 0.0.4
joplin-note-email: 1.0.5
joplin-plugin-TimelineRender: 1.0.2
Kminder Mindmap Joplin Plugin: 0.8.6
Markdown Prettier: 0.1.0
Markdown Table: Colorize: 1.2.0
Markdown Table: Sortable: 1.2.2
Menu items, Shortcuts, Toolbar icons: 1.1.0
Note Statistics: 1.0.4
Note Tabs: 1.4.0
Outline: 1.5.13
Persistent Editor Layout: 2.2.0
PlantUML2: 1.11.0
Quick Links: 1.3.2
Quick Move: 1.1.0
Rich Markdown: 0.15.0
Space Indenter: 0.2.5
Spoilers: 1.0.6
Tagging: 1.0.3
Templates: 2.4.0
turnToChart: 1.9.3
VS-Code Style Note Search: 0.0.1
</details>


**CodeMirror 6 settings v1.0.0**

The default values are not being lost, however they are always applied on restart, regardless of changes made by the user. I'm not sure if the fixes were meant to fix this? Reporting FWIW

At startup these are the settings (presumed to be the defaults):

- [x] Show line numbers
- [ ] Enable code folding
- [ ] Enable autocomplete
- [ ] Highlight the gutter for the active line
  *Requires show line numbers enabled*
- [x] Highlight active line
- [ ] Highlight spaces
- [ ] Highlight trailing spaces

After the user makes the changes below in *Options > Extra editor Settings*, Code Folding becomes available and works as expected, and trailing spaces are highlighted. However on Joplin restart, the settings return to the defaults as above.

- [ ] Show line numbers
- [x] Enable code folding
- [x] Enable autocomplete
- [ ] Highlight the gutter for the active line
  *Requires show line numbers enabled*
- [ ] Highlight active line
- [ ] Highlight spaces
- [x] Highlight trailing spaces

**CodeMirror 6 snippets v0.0.8**

1. In the plug-in Options the user adds the note ID for the Snippets Note and applies the change
2. Snippets become available and work as expected
3. On restart the Snippets Note ID is lost, and the options field is again blank
