### ISSUE TITLE
Android text editor: Cursor jump at note end

### ISSUE THREAD

**Issue by Captain-Barge** [laurent22/joplin#10389]
### Operating system

Android

### Joplin version

3.0.2

### Desktop version info

Joplin 3.0.2 from F-Droid

Device: Pixel 3 XL
OS: Android 14 LineageOS 21-20240312-NIGHTLY-crosshatch

### Current behaviour

Within a note's text editor if the cursor is at the very last position of the note then the first character of each word causes the cursor to move backward one position. This effect leads to sentences like this:
"heT uickq rownb oxf umpedj vero het azyl ogd"

I discovered a workaround is to add new line characters to the end of a note, so when I type new text my cursor is not at the end of the note & the effect doesn't happen.

The effect doesn't happen in other programs on this device (only Joplin).

### Expected behaviour

When typing at the end of a note the cursor should remain at the end (& not jump backwards) as new characters are added.

**Comment by sjorskoot** [comment]
I have the same issue, also version 3.0.2 from F-droid. It occurs when a space is inserted and the cursor is at the end of the line. If you type without correcting, you get "The uick brown fox jumps over the lazy dogq". (The q after the first space remains at the end)

I'm on Android 13 on a Fairphone 5.

**Comment by personalizedrefrigerator** [comment]
See https://github.com/laurent22/joplin/issues/10352 — this should be fixed in [version 3.0.3](https://discourse.joplinapp.org/t/android-pre-release-v3-0-is-now-available-updated-27-04-2024/36993/3).

**Comment by personalizedrefrigerator** [comment]
> **Joplin version**
>
> 3.0.2

Version 3.0.3 [should be available on F-Droid](https://f-droid.org/packages/net.cozic.joplin/). If you're using this version, is the issue still present?

**Comment by sjorskoot** [comment]
Solved it for me!
