### ISSUE TITLE
Cant update

### ISSUE THREAD

**Issue by unrealistic-reality** [laurent22/joplin#10391]
### Operating system

Linux

### Joplin version

1.29.2

### Desktop version info

Latest

### Current behaviour

```bash
pi@raspberrypi:~ $ docker pull florider89/joplin-server:latest
latest: Pulling from florider89/joplin-server
no matching manifest for linux/arm/v8 in the manifest list entries
```

### Logs

no matching manifest for linux/arm/v8 in the manifest list entries

**Comment by JackGruber** [comment]
The `florider89/joplin-server` image is no maintained by Joplin!
https://hub.docker.com/r/florider89/joplin-server
https://github.com/flosoft/docker-joplin-server

**Comment by unrealistic-reality** [comment]
@JackGruber Does this repo supports RPI?

**Comment by JackGruber** [comment]
I don't know, I haven't looked at the repro config. The two links are only included as a reference to the one in the error message.
