### ISSUE TITLE
Mismatched translations

### ISSUE THREAD

**Issue by vulpivia** [laurent22/joplin#10399]
### Operating system

Linux

### Joplin version

dev branch

### Current behaviour

The translation for the string `"Keep notes in the trash for"` doesn't match the original English version in most languages. It seems that the translation of the string before that was copied over in each `.po` file. I discovered that issue while creating pull request #10398.

### Expected behaviour

Translations should reflect the intended meaning in all supported languages.

**Comment by laurent22** [comment]
In which language in particular? That's a new string so there aren't that many translations

**Comment by vulpivia** [comment]
In every language besides:

- Danish
- Esperanto (not yet translated)
- Farsi
- French
- Galician (not yet translated)
- Indonesian
- Korean
- Turkish
- Chinese (S)

Although I just noticed that it's marked as fuzzy, so this issue I've created might be unnecessary.

**Comment by laurent22** [comment]
Yes strings are marked as initially marked as fuzzy when they're added to the po file, but on application side we simply ignore all those fuzzy strings and display the English version instead. But all these will be translated eventually (for example I've just translated the French one)
