### ISSUE TITLE
IOS Application does not open

### ISSUE THREAD

**Issue by parduspanteri** [laurent22/joplin#10412]
### Operating system

iOS

### Joplin version

12.14.7

### Desktop version info

ipad ios version 12.5.7

### Current behaviour

https://github.com/laurent22/joplin/assets/105588014/0b1506f7-85b6-4966-9a0d-3dbf645b1851

**Comment by laurent22** [comment]
Would you be able to share a low level crash log as described here? https://joplinapp.org/help/apps/debugging/#creating-a-low-level-bug-report-on-ios

**Comment by parduspanteri** [comment]
I sent an e-mail to s**@joplinapp.org

**Comment by laurent22** [comment]
Thanks for the report!

12.14.8 is out now, please give it a try and let me know if it's any better

**Comment by parduspanteri** [comment]
Now it's working well. Thanks...

**Comment by laurent22** [comment]
Fixed in 966fe38ae3a30d70db6a330cdf29a53e3ad9fff1
