### ISSUE TITLE
Minor translation error

### ISSUE THREAD

**Issue by Dyrke** [laurent22/joplin#10440]
### Operating system

Windows

### Joplin version

Joplin 2.14.20

### Desktop version info

Joplin 2.14.20

### Current behaviour

In Danish translation da_DK.po at line 1206/1207 
It is wrongly translated from "Create new profile..." to "Opret ny note...", and it should have been "Opret ny profil..."

**Comment by sunny-thakurwar** [comment]
Hi @Dyrke, i had worked on this but not able to link this to issue the pr id translation bug fix #10445 can you please assign issue and check Once.
