### ISSUE TITLE
When writing in rtl and pressing the right/left arrow keys the cursor moves in the wrong direction

### ISSUE THREAD

**Issue by michronin** [laurent22/joplin#10461]
### Operating system

Windows

### Joplin version

2.14.20 i think. ive downloaded it yesterday

### Desktop version info

Joplin 2.14.22 (prod, win32)

Client ID: 3722251244854c72bce77af50c3ed5de
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: e579eb9

Backup: 1.4.0
Templates: 2.4.0

### Current behaviour

1. When i write in hebrew, and press the left arrow key, the cursor moves to the right.
2. When I write in hebrew, and press the right arrow key, the cursor moves to the left

### Expected behaviour

1. When i write in hebrew, and press the left arrow key, the cursor needs moves to the left.
2. When I write in hebrew, and press the right arrow key, the cursor needs to move to the right.

**Comment by personalizedrefrigerator** [comment]
Which editor is this happening with (markdown legacy, markdown beta, or rich text)? 

<details><summary>Determining which editor is in use</summary>

<figure>
<img src="https://github.com/laurent22/joplin/assets/46334387/837f4c7f-e7a0-4029-969d-4dc83c7789cf"/>
<figcaption>In the markdown editor, the "toggle editors" button highlights the "markdown" icon.</figcaption>
</figure>

---

<figure>
<img src="https://github.com/laurent22/joplin/assets/46334387/6a5277b6-a10f-40b8-82c3-ac3afadbe79b"/>
<figcaption>In the Rich Text editor, the "toggle editors" button highlights the "edit" icon.</figcaption>
</figure>

---

<figure>
<img src="https://github.com/laurent22/joplin/assets/46334387/b323ee88-3fac-45ea-9146-badaa03747a3"/>
<figcaption>In settings, "opt-in to the editor beta" can be used to toggle the beta editor.</figcaption>
</figure>

</details>

Thank you for reporting this!

**Comment by michronin** [comment]
Im using the markdown editor with the beta off
