### ISSUE TITLE
Cannot render Katex content: KaTeX parse error

### ISSUE THREAD

**Issue by arithforu** [laurent22/joplin#1046]
### Operating system

- Linux
- iOS

### Application

- Desktop
- Mobile

When you write the below text in the body of the notes:

CocVbqjY$pASHnGrgpfzZ@vXPXId#75F&jAMYXSm52nr$

It gives below error:

CocVbqjYCannot render Katex content: KaTeX parse error: Expected 'EOF', got '#' at position 20: …nGrgpfzZ@vXPXId#̲75F&jAMYXSm52nr

Please note:

This issue is different than https://github.com/laurent22/joplin/issues/783

The text in the question here is NOT code.  It's a text string only.

**Comment by laurent22** [comment]
The "$" either need to be escaped with `\$` or the string put inside backticks.
