### ISSUE TITLE
Can't upgrade through Chocolatey

### ISSUE THREAD

**Issue by troogyt** [laurent22/joplin#10460]
### Operating system

Windows

### Joplin version

2.14.20

### Desktop version info

Joplin 2.13.15 (prod, win32)

Client ID: <omitted>
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 7d2c1c0

ABC Sheet Music Plugin: 1.0.4
Admonition markdown extension: 1.1.0
Advanced Tagging Rules: 1.2.0
Agenda: 3.7.1
Better Code Blocks: 1.1.0
Bible Quote: 2.1.0
Bidirectional Links: 0.1.2
bytefield-svg: 1.1.0

### Current behaviour

Upgrade fails.

Joplin pesters me about upgrading, so I tried. It failed.
Installed: 2.13.15
Target: 2.14.20
Method: Chocolatey (GUI and CLI both fail, even when running as Administrator)

GUI upgrade attempt:
![image](https://github.com/laurent22/joplin/assets/41710820/bc63fe20-7700-477a-8362-80a09a5a26bb)
![image](https://github.com/laurent22/joplin/assets/41710820/06acdb3d-5fc6-46df-a556-b74d100c3399)

CLI upgrade attempt:
![image](https://github.com/laurent22/joplin/assets/41710820/8f912f70-d131-4f37-8011-d46bbe788374)

but result after launching GUI:
![image](https://github.com/laurent22/joplin/assets/41710820/422bb38d-883d-4488-a0d6-09f4df0ab834)

### Expected behaviour

Upgrade successfully.

### Logs

No crashing. Still runs fine and I can create notes. It just won't upgrade.

**Comment by laurent22** [comment]
See here for the Chocolatey package contact links: https://community.chocolatey.org/packages/joplin
