### ISSUE TITLE
Request: Show metadata on Desktop and Terminal

### ISSUE THREAD

**Issue by cori** [laurent22/joplin#105]
### Operating system

- [ ] Windows
- [ x ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [ x ] Desktop
- [ ] Mobile
- [ x ] Terminal

It would be nice to be able to see the metadata when on desktop and terminal.
---

**Comment by laurent22** [comment]
On terminal, type "tm"

**Comment by cori** [comment]
I see, thanks; is that documented somewhere that I missed?

Nothing on desktop, I gather? 

Also this is a new and different paradigm for commands in the terminal app (aside from the vim-like command tray). Are there other commands like this?

**Comment by laurent22** [comment]
Yes I think it should be documented when you type `:` followed by `help shortcuts`. Also try `help` for more information.

Currently this feature is only on mobile and terminal but it should be added at some point to the desktop one.

**Comment by cori** [comment]
Got it, thanks!
