### ISSUE TITLE
global search: changing a note from the result switches to a random note

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#10507]
### Operating system

Windows

### Joplin version

3.0.8 (dev, darwin)

### Desktop version info

Joplin 3.0.8 (dev, darwin)

Client ID: e354a932e6e143c782264aad4112b674
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 50d08cd17 (dev)

Automatic Backlinks to note: 3.0.3
Backup: 1.4.1
Convert Text To New Note: 1.5.1
Get Notebook ID: 1.0.1
Insert Date: 1.0.1
Markdown table calculations: 1.0.5
Math Mode: 0.5.3
Menu items, Shortcuts, Toolbar icons: 1.1.0
Note list and sidebar toggle buttons: 1.0.3
Note overview: 1.6.0
Quick Links: 1.2.4
Table Formatter Plugin: 1.2.1
Templates: 2.3.0

### Current behaviour

1. enter a text in the global search box
2. click on a note that shows up in the note list
3. try to edit this note (click in the note and press a few keys)
4. Joplin switches to a random note and the note list changes as well

https://github.com/laurent22/joplin/assets/223439/e70d1981-c43c-4f81-9df2-98a52f74caa9

### Expected behaviour

I should be able to edit the note and the note list should not change.

### Logs

[log.txt](https://github.com/laurent22/joplin/files/15462318/log.txt)

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this (and for the video)! This is a regression from v2.14 and definitely something that we want to fix before version 3.0 becomes stable.

Possible duplicate: https://github.com/laurent22/joplin/issues/10236.

**Comment by tessus** [comment]
Yep, it seems to be a duplicate. 

I'll add my log and the video to the other issue and close this one.

**Comment by tessus** [comment]
Closing in favor of #10236
