### ISSUE TITLE
Can't drag and drop images from browser and render properly

### ISSUE THREAD

**Issue by djsudduth** [laurent22/joplin#10519]
### Operating system

Windows

### Joplin version

2.14.22

### Desktop version info

Joplin 2.14.22 (prod, win32)
Client ID: 19f20674be77445bbd5535190049d93c
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes
Revision: e579eb9

### Current behaviour

1. Open either Chrome or Firefox 
2. Find any webpage that contains images
3. Drag and drop image from browser to Joplin note
4. Image does not appear. From Chrome nothing happens. From Firefox just a link appears such as vxw9l5vo.bmp which will open the default Windows image viewer with the image.

### Expected behaviour

The drag and drop behavior should be the same as right-click, copy and paste the image from the browser (right-click, copy-paste works fine).

### Logs

14:22:26: resourceHandling: Attaching C:\Users\<myid>\AppData\Local\Temp\pu53j0lx.bmp
C:\Users\<myid>\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:221 14:22:27: resourceHandling: File was attached.
C:\Users\<myid>\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\utils\useMessageHandler.js:27 Got ipc-message: noteRenderComplete null

**Comment by siddhantJH** [comment]
I've just started exploring open-source projects. Can you please guide me on how to get started and resolve the issue?

**Comment by djsudduth** [comment]
@siddhantJH all the instructions on setting up your dev environment and contributing are documented in the README near the bottom of the page. Get yourself familiar with setting up javascript/typescript projects along with using npm.

**Comment by sysescool** [comment]
There is a question.
one format (url image): 
`[more about Evernote import](https://joplinapp.org/help/#importing-from-evernote)`
another format (attachment image): 
`![image-20210411153337965.png](:/bcc1e7272a894e83bff542729af5df7b)`

If you download it, then drag into joplin note, it'll be the second format.

I prefer to the second format, because sometimes webpage go down.

**Comment by laurent22** [comment]
I didn't see the version number - I believe this is fixed as of 3.0. Please give that version a try and if it still happens, post here
