### ISSUE TITLE
Korean translation error

### ISSUE THREAD

**Issue by doyun0202** [laurent22/joplin#10529]
### Operating system

Windows

### Joplin version

2.14.22

### Desktop version info

Joplin 2.14.22 (prod, win32)

클라이언트 ID: ded66487635f4b7c932e20caaae4ce3e
동기화 버전: 3
프로파일 버전: 46
키체인 지원: 예

개정판: e579eb9

Backup: 1.4.0
Draw.io: 2.2.0
Email Note: 1.2.2
Freehand Drawing: 2.7.1
Markdown table calculations: 1.0.5
Markdown Table: Sortable: 1.1.0
Metis: 0.1.5
Rich Markdown: 0.13.3
Slash Commands: Datetime & More: 1.3.1

### Current behaviour

ko : 한국어 기반의 joplin 프로그램에서 "파일" 버튼을 클릭하고 3번쨰와 4번째의 항목이 번역이 잘못되었음
"새 노트북" 과 "하위 노트북" 이라고 번역해야되지만 번역이 정상적이지 않고 둘다 새 노트북으로 번역되어있음

en : When I clicked the "File" button in the Korean-based joplin program, the 3rd and 4th items were mistranslated.
It should be translated as new notebook and sub-notebook, but the translation is not normal and both are translated as new notebook.

en gui
![image](https://github.com/laurent22/joplin/assets/80564665/870ba27e-faf4-45e5-a1a3-d44c8451d0d9)

ko gui
![image](https://github.com/laurent22/joplin/assets/80564665/479f12cc-d3f4-47c5-bc1c-4af0ff900f8a)

### Expected behaviour

한국어 기반의 gui의 메뉴에서 노트북 추가에 대한 ui의 번역오류를 수정해주세요

Please correct the translation error in the UI for adding a laptop in the menu of the Korean-based GUI.

**Comment by tushar-coin** [comment]
hey moderators i dug into the issue and have found the part of code which is causing it 
Please assign this bug to me

**Comment by tushar-coin** [comment]
have already raised a pr against the issue https://github.com/laurent22/joplin/pull/10539

**Comment by roman-r-m** [comment]
> hey moderators i dug into the issue and have found the part of code which is causing it 
> Please assign this bug to me 

We do not assign issues but feel free to work on it

**Comment by tushar-coin** [comment]
hey @roman-r-m thanks for the quick response 
currently working on it then

**Comment by tessus** [comment]
fixed in df8c7fd31
