### ISSUE TITLE
Search errors

### ISSUE THREAD

**Issue by dseter** [laurent22/joplin#1052]
### Operating system

- macOS, 10.13.6

### Application

- Desktop, 1.0.119

1. The program searches for Russian words only if the register is the same. For example, if I search for a word that begins with a capital letter, and in the text this word is written with a small letter, then it will not be found.
2. The program searches only for a complete word match, it does not show a partial.
3. Pressing the Esc key does not clear the search bar and does not remove the focus from it.

**Comment by dseter** [comment]
I am using global search in the top toolbar (F6).

**Comment by laurent22** [comment]
Thanks, would you mind posting an example note in Russian and an example query for what you mentioned here?

> for a word that begins with a capital letter, and in the text this word is written with a small letter, then it will not be found.

I'm not sure I can even fix this since I don't know Russian but can give it a try.

**Comment by dseter** [comment]
This text, for example: "Агентство Рейтер со ссылкой на источник сообщило, что все сотрудники Госдепа США будут эвакуированы из Сирии в течение суток. Все вооруженные силы США покинут арабскую республику, когда закончатся финальные стадии операции против ИГ".

Bug № 1. If you search for "рейтер" (with a small letter), you will not find anything. And if you search for "Рейтер", you will find it.
Bug № 2. If you search for the "Госдеп" (incomplete version of the word), you will not find anything. And if you look for the "Госдепа", then the word will be found.

**Comment by ComputingFroggy** [comment]
search is a bit fleaky.
I was searching for "icon" and it would not find "icons". Then just before writing I tried again, and this time the search for "icon" found "icons" ! ?

**Comment by laurent22** [comment]
Search for Russian text should be improved in latest release, but let me know if you notice something not right.
