### ISSUE TITLE
Update notification steal window focus.

### ISSUE THREAD

**Issue by zvodd** [laurent22/joplin#10523]
### Operating system

Windows

### Joplin version

2.14.20

### Desktop version info

Joplin 2.14.20 (prod, win32)

Client ID: d9eb68c96c7f42f7a7f973b0b56d9072
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: cfd98e3

Backup: 1.4.0

### Current behaviour

When Joplin finds an update, it will steal focus from whatever the user is currently doing.
This is a truly obnoxious software behaviour, on par with infamous Windows 10 un-telegraphed update restarts. 
...and so my description is hyperbolic and impolite.

What happens:

- Joplin is open in the background.
- User doing something else entirely.
- Joplin checks for an update, finds one and...
- **Interrupts the user immediately, throwing up a large window in the middle of the screen.**
- User click cancel on Joplin update window.
- An hour or two later, same thing.

I cannot fathom how this anti-feature has survived multiple versions. Has nobody else complained?

### Expected behaviour

Maybe use a toast notification.
Only show the Update notification, when the Joplin window has focus?
Just some kind of sane practise, that follows industry standards.

**Comment by laurent22** [comment]
Closed as duplicate

**Comment by zvodd** [comment]
`checkForUpdates` is only used once, here:

https://github.com/laurent22/joplin/blob/32e16f6e518b08cee932419357baab509e7f77d2/packages/app-desktop/app.ts#L539

and the `inBackground` function parameter is always set to true

https://github.com/laurent22/joplin/blob/32e16f6e518b08cee932419357baab509e7f77d2/packages/app-desktop/checkForUpdates.ts#L68

That argument should be removed and the local variable `checkInBackground_ ` should be set by querying the parent window argument - should be something like:
```
checkInBackground_ = parentWindow?.isFocused()
```
