### ISSUE TITLE
Joplin MD exporter - data loss due to note titles

### ISSUE THREAD

**Issue by ferrouswheel** [laurent22/joplin#10525]
### Operating system

Windows

### Joplin version

2.13.8

### Desktop version info

Joplin 2.13.8 (prod, win32)

Client ID: 2d7ee8695f5946a29c1ac1e822d1e571
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 604dcbc

Favorites: 1.3.0

### Current behaviour

When exporting to MD:

If you export to the same location twice, it will rename everything with a `-1` suffix. It should probably warn the user instead or abort and require a clean location.

If you export two notes with the same title but different capitalisation, one will overwrite the other. I imagine this is due to windows file system limitations. However, given the above behaviour of explicitly adding a `-1` suffix, you'd expect the same instead of silently overwriting the note.

### Expected behaviour

Provide user feedback if the export location has existing files.

Don't overwrite notes and loose data.

**Comment by personalizedrefrigerator** [comment]
I can reproduce this in Joplin 2.14.22 and 3.0.8 (Windows 11) with Export all > "MD - Markdown" and a notebook structure similar to the following:
```
📂 Notebook
⏐ 📄 a
⏐ 📄 A

📂 Welcome!
⏐ ... welcome notes ...
```
Within the exported copy of `Notebook`, `A.md` is present, but not `a.md`. 

---

In Joplin's exporter, this line seems to be responsible for avoiding name collisions:

https://github.com/laurent22/joplin/blob/97ddb67f683cc4ed3ad832c2f97ce0e8a3057528/packages/lib/services/interop/InteropService_Exporter_Md.ts#L104

Above, `Object.values(context.notePaths)` are being passed [as `reservedNames`](https://github.com/laurent22/joplin/blob/97ddb67f683cc4ed3ad832c2f97ce0e8a3057528/packages/lib/fs-driver-base.ts#L149). Although `findUniqueFilename` [uses the case-insensitive[^1] `.exists`](https://github.com/laurent22/joplin/blob/97ddb67f683cc4ed3ad832c2f97ce0e8a3057528/packages/lib/fs-driver-base.ts#L161) to check the filesystem for an item with each name, it compares the given path with items in `reservedNames` **in a case-sensitive way**.

[^1]: On Windows. This was checked by running the following after an export from Joplin's development tools:
    ```javascript
    // where A.md exists in ...\Notebook\
    > await shim.fsDriver().findUniqueFilename("C:\\Users\\User\\Downloads\\md-6-4-2024-3-01\\Notebook\\a.md")
    'C:\\Users\\User\\Downloads\\md-6-4-2024-3-01\\Notebook\\a (1).md'
    ```
    A similar check was also done for a.md existing and A.md given to findUniqueFilename.
