### ISSUE TITLE
ENEX import loses titles of some notes

### ISSUE THREAD

**Issue by soshial** [laurent22/joplin#10530]
### Operating system

macOS

### Joplin version

Joplin 2.14.22 (prod, darwin)

### Desktop version info

Joplin 2.14.22 (prod, darwin)

Client ID: 15215adc7be148d0a74d13fcb09dd4ba
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: e579eb9

Backup: 1.4.0

### Current behaviour

This is how the "Hardware" notebook looks like in Joplin after import:
<img width="1050" alt="Screenshot 2024-06-02 at 17 19 46" src="https://github.com/laurent22/joplin/assets/100644/675cc141-3e2a-4c4f-a488-86215ebeda5b">

This is how it looked in Evernote:
<img width="400" alt="Screenshot 2024-06-02 at 17 19 46" src="https://github.com/laurent22/joplin/assets/100644/8a943546-d9e4-4be0-83f6-d418c319a001" />

### Logs
[.enex file](https://mega.nz/file/f9R1nSgL#qWYeASIlrxDyKQ1IXucAHCGp6k8esO2BGGLakG0UUN8) (contains a single notebook named "hardware")

**Comment by laurent22** [comment]
It's Evernote export that loses the note titles. If you check the enex file content you'll see that they are actually named "Untitled notes"

**Comment by soshial** [comment]
Those bastards 😆
You may close the ticket then. Thank you, Laurent
