### ISSUE TITLE
Find in note does not jump to the text in editor

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#1053]
### Operating system

- Windows
- macOS
- Linux

### Application

- Desktop

---

When using `cmd+F` to search within a note, the layout is changed to show the editor and rendering pane. The search text is only highlighted in the rendering pane and not selected in the editor.

Maybe I don't understand the logic behind the algorithm, but usually when I search something I want to change the text or start editing at that point.

If this is not a bug and working as intended, we can close this issue right away.

**Comment by matsest** [comment]
I think the highlighting itself is only possible in the rendered view. But I also agree that it is somewhat confusing that the rendered pane pops up when initiating a search. Some thoughts:

* It would be useful if the marker in the editor view would follow the 
highlight in the rendered view.

* Pressing ESC when searching should take you bake to editor view with selection at search result

**Comment by dseter** [comment]
I also think that the found word should be marked in the editor window, because it is the main window when working with the program.

**Comment by tessus** [comment]
We still haven't established, whether this is a bug or not.

@laurent22 what's your take one this? shall we just close it or classify it as a bug?

**Comment by laurent22** [comment]
It's not a bug as it only searches in the viewer for now. It could be a FR

**Comment by tessus** [comment]
I'm not sure, if I want to create a feature request for it. I thought it was a bug. There are so many FR open and I think there are others which are more important. Although it would certainly help the note taking workflow if one hadn't have to scroll to the correct position manually after finding the text where one wanted to append additional text.

**Comment by laurent22** [comment]
Yes I don' t know if I'd even accept a PR for it, except if they find a nice trick to do it in a simple way (which I doubt is possible).

The problem is that Ace Editor is dated so it doesn't make sense to add many features to it. Rather than spend time on this, it would make more sense to spend time to switch it to a more modern editor.

Ideally we should use Code Mirror 6, if it's ever released, as we can then also use it in the mobile app too (it's one of the rare code editor that will support mobile).

**Comment by tessus** [comment]
Ok, let's close this for now. Let's see what the future holds.
