### ISSUE TITLE
Table column size can't be changed in RTE

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10560]
### Operating system

macOS

### Joplin version

3.0.6

### Current behaviour

- Create a table in the RTE
- Switch to the Markdown Editor
- Switch back to RTE

=> Column size cannot be adjusted anymore

This applies to tables that are saved as Markdown and those that are saved as HTML (for example tables that contain bullet points)

**Comment by laurent22** [comment]
@pedr, that may be related to what you're working on - maybe we add an exception if the table has been resized. In that case, we save it to HTML and that might solve this issue

**Comment by pedr** [comment]
Do you mean the change is not saved when you change from one editor to another? Because it seems like you can change the column size, it is just not saved, right?

https://github.com/user-attachments/assets/4dc9ab38-d9c2-4517-a9a4-7670b44ab8c3

**Comment by laurent22** [comment]
I just tried again and still doesn't work for me. Maybe try these exact steps:

- Switch to RTE
- Create a new note
- Create a table 2x2
- Write "a" in the top left corner
- Switch to Markdown
- Switch to RTE

Are you able to resize columns in this case?

Using Dark theme, last dev version, macOS

<img width="424" alt="image" src="https://github.com/user-attachments/assets/04add0b3-39f6-4743-b8af-5866dfa50674">

**Comment by pedr** [comment]
Yes, I can reproduce it now, thanks for the step-by-step.

**Comment by futuremotiondev** [comment]
@pedr @laurent22 

So this is working for me in the RTE, but...

_Why_ is the option to resize columns and rows even available if it doesn't persist after a change to the Markdown editor and back to RTE? 

It would be great to be able to control column width and have the values stick once adjusted, but this doesn't seem to currently be possible. I wouldn't even mind if the table markup gets converted to HTML in this use-case to make it work.

TBH, I've been dreaming about this functionality. It would be very helpful in documents where a lot of tables are being used to ensure visual consistency.
