### ISSUE TITLE
F-droid build doesn't have "take picture" feature

### ISSUE THREAD

**Issue by Th3-A6add0n** [laurent22/joplin#10573]
### Operating system

Android

### Joplin version

3.0.3

### Current behaviour

When I clicked on "take picture" it doesn't work & neither does it ask for camera permissions.
[Screenrecording](https://imgur.com/a/iwoXBWq)

### Expected behaviour

When clicked on "take pictures" it should open up the camera to take pictures.

**Comment by JackGruber** [comment]
Yes as mentioned in the description page, the F-Droid app doesn't have the camera feature.
https://github.com/laurent22/joplin/pull/5735

**Comment by Th3-A6add0n** [comment]
> Yes as mentioned in the description page, the F-Droid app doesn't have the camera feature. #5735

How does getting a camera access depend on play services or firebase?

**Comment by personalizedrefrigerator** [comment]
> How does getting a camera access depend on play services or firebase?

Among other libraries, `react-native-camera` ([on a list of libraries we may want to replace](https://discourse.joplinapp.org/t/weekly-update-2/38525/13)) depends on Google Play Services for barcode scanning and face detection (I think we use neither of these aspects of `react-native-camera`):
```
  implementation "com.google.android.gms:play-services-mlkit-text-recognition:16.3.0"
  generalImplementation "com.google.android.gms:play-services-mlkit-barcode-scanning:16.2.0"
  generalImplementation "com.google.android.gms:play-services-mlkit-face-detection:16.2.0"
  mlkitImplementation "com.google.mlkit:barcode-scanning:16.2.0"
  mlkitImplementation "com.google.mlkit:face-detection:16.1.2"
```
