### ISSUE TITLE
title disappeared - android 1.0.181

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#1057]
### Operating system

- Android

### Application

- Mobile

With android 1.0.181, the title disappeared from the view of the note + there is a new blank line instead. And there is a "liseraie" (a thin blank line) that appears between jolpin app and the status bar

**Comment by foxmask** [comment]
![screenshot_20181221-071359](https://user-images.githubusercontent.com/208212/50329369-4acea280-04f7-11e9-94f4-a3e297902cee.png)

**Comment by laurent22** [comment]
@foxmask, please could you give this version a try to see if it fixes the issue?

https://github.com/laurent22/joplin-android/releases/download/android-v1.0.224/joplin-v1.0.224.apk

The hack to fix this strange bug is ugly but seems to work, at least on my phone. If you could confirm that would be great.

**Comment by foxmask** [comment]
Works fine thanks

**Comment by foxmask** [comment]
yes
sometimes I just open a note and title is not there
sometimes I just open a note and title is there and once a edit and save it ; the title is not displayed at all

**Comment by laurent22** [comment]
Ok I could indeed replicate this. This version should have a fix for these issues:

https://github.com/laurent22/joplin-android/releases/download/android-v1.0.232/joplin-v1.0.232.apk

Unfortunately it means that for now there will be a small glitch on the title field when a note is opened or reloaded. Let's see if that hack can be removed later on when new versions of React Native are released.

**Comment by foxmask** [comment]
Looks fine now. Thanks
