### ISSUE TITLE
Update plugin config screen

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10592]
For consistency with the desktop app and I feel for improved UX, we should tweak the plugin config screen like so:

- Remove the "Installed plugins" section
    - By default, show all the installed plugins
    - Add a header "Installed plugins"
    - If there's no installed plugin, display a message instead
- Remove the "Installed new plugins" section, and move the Search bar to the top of the screen
    - Add a "Clear" button to the Search bar
    - When searching, hide the "Installed plugins" section
- Give a border to the "Installed" and "Update available" badges, and remove the background color (because they look like buttons at the moment)

**Comment by laurent22** [comment]
@personalizedrefrigerator, hopefully those are not too big changes since we're close to 3.0, if they are please let me know

**Comment by personalizedrefrigerator** [comment]
Here are some screenshots of a draft implementation:
![screenshot: Search bar reads "search for plugins", is now above installed list](https://github.com/laurent22/joplin/assets/46334387/a2a1fc2d-b3b1-4676-a5a8-7292f46fd1c4)

**Comment by laurent22** [comment]
Thanks, that looks good! Only thing is that I would put a transparent background on the Recommended badge, and yellow (or orange?) border and text. Like it is on desktop, so maybe using the "warning" color? Otherwise it's a bit distracting and looks like a button, especially since the recommended plugins are on top of the list anyway.

**Comment by personalizedrefrigerator** [comment]
> Otherwise it's a bit distracting and looks like a button, especially since the recommended plugins are on top of the list anyway.

That can be changed. (Note that it is a button — pressing it shows a description of what a recommended plugin is.)

**Comment by personalizedrefrigerator** [comment]
I'm attaching screenshots of two design options, both using `colorWarn`:

![screenshot: Option 1: Recommended badge is now orange. Option 2: Recommended badge is gone and now, on the right of each card is a crown if recommended.](https://github.com/laurent22/joplin/assets/46334387/1c127cc0-dca9-4a68-900f-b26a8e34cfb8)

With option 2, I worry that it won't be clear to users that the crown means "recommended". Note that it's still possible to tap on the crown to view a description of what it means to be a recommended plugin. However, it might not be clear to users that they can do this.

**Comment by laurent22** [comment]
I saw this comment after having merged the pull request. Both options look fine to me. Clicking the Recommended badge is something that the user might do once and then never again once they know what it means so usability is not too important for this
