### ISSUE TITLE
Put plugin settings under a separate section

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10594]
### Operating system

Android

### Joplin version

3.0.0

### Current behaviour

The plugin settings currently are appended at the end of the Config screen. We should:

1. Remove the small "plugin" icon on the right 🧩
2. Put the plugin settings under a separate section, as is done on desktop:

<img width="187" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/305988ee-cff9-4f7b-a375-ff465e8cc944">

**Comment by personalizedrefrigerator** [comment]
I'm including screenshots of a work-in-progress implementation:

![screenshot: Plugin icons are no longer visible, plugins are below a "Plugins" header](https://github.com/laurent22/joplin/assets/46334387/ac3feeb5-d2fb-4b20-84aa-8eda1c06c8db)
![screenshot: Tab in dark mode](https://github.com/laurent22/joplin/assets/46334387/215a2154-d7d6-4b72-b07a-5296d895880a)
