### ISSUE TITLE
The Search button in the header should be removed from the Plugin Screen

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10596]
### Operating system

Android

### Joplin version

3.0.0

### Current behaviour

This button should either be removed or be used to search plugins. Currently it searches settings which is probably not obvious and not needed in this context.

**Comment by Om-Midya** [comment]
Hi there! I want to work on this issue, I am new to OS-contributions, would probably ask for a lot of help. Can You please elaborate more on this issue, i have the repository set-up in my local machine
