### ISSUE TITLE
FR: Add Ctrl-Shift-F as an alternate global search

### ISSUE THREAD

**Issue by gerroon** [laurent22/joplin#1060]
Hi

It would be nice if the search shortcut semantics makes little more sense, instead of following what another app might be doing for the same functionality. That is why I recommend to at least offer Ctrl-Shift-F as an alternate for global search. Personally I am not getting the logic of assinging F6 to global search.  

This F6 is an extra issue for people with FN keys, makes it extra hard to access it and it is distracting to be honest.

thanks

**Comment by dseter** [comment]
I also think that the global search through F6 is inconvenient (on a Mac you have to press Fn) and it is unusual. It seems to me that the search for all notes is used more often than the search in the current note. Maybe it is better to change the global search to Ctrl+F (Cmd+F on Mac), and search on the current note on F6 (or Ctrl-Shift-F as gerroon suggests)?

**Comment by matsest** [comment]
I think it's good to avoid Fn-buttons overall in such an application. AFAIK, F6 has no history of being a universal search button? (like F11 has for full screen) Also agree that search in all notes are used more often than search in current note. Something like this would be a good solution IMO:

* Ctrl+F: search in all notes
* Ctrl+Shift+F: search in current note

**Comment by laurent22** [comment]
f6 because it's what Thunderbird is using, but I'm ok with ctrl shift s too.

**Comment by gerroon** [comment]
Sure but Thunderbird is not as widespread nowadays. I suspected that it was implemented after some application. In any case thanks for considering an alternative shortcut.

**Comment by tessus** [comment]
available in Desktop version 1.0.127

commit 860e8a8f5adeae73da9246291247b7d24753f205
