### ISSUE TITLE
Display html notes using white theme 

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10609]
### Operating system

Android

### Joplin version

3.0.0

### Current behaviour

- web clip a note in order to create an html note
- open the note in the mobile app, while the dark theme is active

=> The note might be unreadable (black text in black background)

Instead the white theme should be enabled while viewing an html note, like on desktop

**Comment by X1Vi** [comment]
can u give this bug to me

**Comment by laurent22** [comment]
we don't assign bugs

**Comment by X1Vi** [comment]
> Owner Author

then I just start working on it ?

**Comment by X1Vi** [comment]
also can u give more information with screenshots possibly ?

**Comment by X1Vi** [comment]
@laurent22 for some reason web clipper doesnt work in my machine I have confirmed that service is running 
`C:\Users\needJobCoder>netstat -ano | findstr :27583                                                                      
 TCP    127.0.0.1:27583        0.0.0.0:0              LISTENING       22444 `
