### ISSUE TITLE
Implement workaround for WebDAV encoding issue on certain servers

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10608]
### Operating system

Windows

### Joplin version

3.0.0

### Current behaviour

Error:

> Last error: Error: href /remote.php/dav/files/name@gmail.com/Joplin/locks/ not in baseUrl https://nc.nl.tab.digital/remote.php/dav/files/name%40gmail.com/Joplin nor relativeBaseUrl /remote.php/dav/files/name%40gmail.com/Joplin

The current WebDAV driver needs to extract the relative path from the URL however due to the URL being encoded differently in different contexts, it sometimes fails to do so.

We should improve this check by first doing a regular comparison (as we do know) and, if that fails, do another comparison while URL-decoding the URL.

**Comment by pedr** [comment]
Use https://thegood.cloud/ to test it
