### ISSUE TITLE
"Joplin wont run without GooglePlay Services"

### ISSUE THREAD

**Issue by gerroon** [laurent22/joplin#1062]
I am using the Fdroid version , 1.0.181 on Lineage OS 14.1 I cant tell if it came from Fdroid's own or Izzydroid repos (I have both repos), it is not clear to me. 

This message never showed up before. I do not have Google stuff on my device,  This kind of message happens with some apps I download from Apkmirror. It is surprising to me that Joplin implemented Gplay stuff.

**Comment by foxmask** [comment]
Hi, Complaining is ok, not vulgarity against anything anyone
Thanks for your understanding

**Comment by laurent22** [comment]
Can't fix at the moment because Gplay is needed for notifications

**Comment by gerroon** [comment]
Notifcations of what? This app never required Gplay stuff before and that is the main reason I use your app. This is sad that Google Play Services is now part of this app. 

I guess time to move on, it seems like the desicion is made already

**Comment by laurent22** [comment]
The implication of using Firebase weren't completely clear so it's possible I'll revert back to the previous notification implementation, while keeping the improvement I made for Firebase. Notification are only the local ones (no tracking) for alarms.

**Comment by gerroon** [comment]
@laurent22 
Thanks for reconsidering the fix, I appreciate it as an ardent  user and a promoter. I realize sometimes the devs need to make some hard desicions.

**Comment by eMBee** [comment]
how are the notifications used? are they essential to the application? (to display important messages)
or is it possible to use joplin without notifications?

if the latter is the case, maybe it is possible to change the message to: "google play services are needed for notifications. if you don't need notifications you may ignore this message. other functions will continue to work fine."

then those who don't like google play services can move on without worry.

**Comment by gerroon** [comment]
Yes but that is a drag atm, everytime I start the app or share something to the app it shows that annoying white box, I do not mind if Joplin shows it only one time ever.

**Comment by laurent22** [comment]
Please give a try to vv1.0.225 and let me know if it works.

**Comment by gerroon** [comment]
This is not an issue in v1.0.225, it seems that it is fixed
