### ISSUE TITLE
server: user never really deletes after scheduling for deletion

### ISSUE THREAD

**Issue by chrislawso** [laurent22/joplin#10639]
### Operating system

Windows

### Joplin version

server v2.14.2 . 
Running your plain docker compose yaml with postgresql.

### Desktop version info

server v2.14.2 

### Current behaviour

server does not delete user

previously reported by others:
https://github.com/laurent22/joplin/issues/8757#issuecomment-2179968254
https://discourse.joplinapp.org/t/joplin-server-user-deletion-task-not-executing/28871

### Expected behaviour

server to delete user

### Logs

06:55:45 0|app  | 2024-06-20 06:55:45: App: Starting services...
06:55:45 0|app  | 2024-06-20 06:55:45: TaskService: Scheduling #1 (Delete expired tokens): 0 */6 * * *
06:55:45 0|app  | 2024-06-20 06:55:45: TaskService: Scheduling #2 (Update total sizes): 0 * * * *
06:55:45 0|app  | 2024-06-20 06:55:45: TaskService: Scheduling #3 (Process oversized accounts): 30 */2 * * *
06:55:45 0|app  | 2024-06-20 06:55:45: TaskService: Scheduling #6 (Delete expired sessions): 0 */6 * * *
06:55:45 0|app  | 2024-06-20 06:55:45: TaskService: Scheduling #7 (Compress old changes): 0 0 */2 * *
06:55:45 0|app  | 2024-06-20 06:55:45: TaskService: Scheduling #8 (Process user deletions): 10 * * * *
06:55:45 0|app  | 2024-06-20 06:55:45: TaskService: Scheduling #10 (Process orphaned items): 15 * * * *
06:55:45 0|app  | 2024-06-20 06:55:45: TaskService: Scheduling #11 (Process shared items): PT10S
06:55:45 0|app  | 2024-06-20 06:55:45: TaskService: Scheduling #12 (Process emails): * * * * *
06:55:55 0|app  | 2024-06-20 06:55:55: TaskService: Running #11 (Process shared items) (scheduled)...
06:55:56 0|app  | 2024-06-20 06:55:56: TaskService: Completed #11 (Process shared items) in 151ms
06:56:00 0|app  | 2024-06-20 06:56:00: TaskService: Running #12 (Process emails) (scheduled)...
06:56:00 0|app  | 2024-06-20 06:56:00: EmailService: Starting maintenance...
06:56:02 0|app  | 2024-06-20 06:56:02: EmailService: Transporter is operational - service will be enabled
06:56:02 0|app  | 2024-06-20 06:56:02: EmailService: Maintenance completed in 1757ms
06:56:02 0|app  | 2024-06-20 06:56:02: TaskService: Completed #12 (Process emails) in 1807ms
06:56:05 0|app  | 2024-06-20 06:56:05: TaskService: Running #11 (Process shared items) (scheduled)...
06:56:05 0|app  | 2024-06-20 06:56:05: TaskService: Completed #11 (Process shared items) in 46ms
06:56:15 0|app  | 2024-06-20 06:56:15: TaskService: Running #11 (Process shared items) (scheduled)...
06:56:15 0|app  | 2024-06-20 06:56:15: TaskService: Completed #11 (Process shared items) in 55ms
06:56:25 0|app  | 2024-06-20 06:56:25: TaskService: Running #11 (Process shared items) (scheduled)...
06:56:25 0|app  | 2024-06-20 06:56:25: TaskService: Completed #11 (Process shared items) in 57ms
06:56:35 0|app  | 2024-06-20 06:56:35: App: GET /users/me (200) (28ms)
06:56:35 0|app  | 2024-06-20 06:56:35: TaskService: Running #11 (Process shared items) (scheduled)...
06:56:35 0|app  | 2024-06-20 06:56:35: App: GET /images/server_logo.png (200) (3ms)
06:56:36 0|app  | 2024-06-20 06:56:36: TaskService: Completed #11 (Process shared items) in 176ms
06:56:45 0|app  | 2024-06-20 06:56:45: App: GET /admin/user_deletions (200) (54ms)
06:56:45 0|app  | 2024-06-20 06:56:45: App: GET /images/server_logo.png (200) (1ms)
06:56:45 0|app  | 2024-06-20 06:56:45: TaskService: Running #11 (Process shared items) (scheduled)...
06:56:45 0|app  | 2024-06-20 06:56:45: TaskService: Completed #11 (Process shared items) in 87ms
06:56:47 0|app  | 2024-06-20 06:56:47: App: GET /api/items/root:/info.json:/content (200) (64ms)
06:56:47 0|app  | 2024-06-20 06:56:47: App: POST /api/locks (200) (23ms)
06:56:47 0|app  | 2024-06-20 06:56:47: App: PUT /api/batch_items (200) (80ms)
06:56:47 0|app  | 2024-06-20 06:56:47: App: GET /api/items/root:/:/delta (200) (7ms)
06:56:48 0|app  | 2024-06-20 06:56:48: App: DELETE /api/locks/1_1_f909fdd5599d4d14bcc6a1e775900f92 (200) (13ms)
06:56:48 0|app  | 2024-06-20 06:56:48: App: GET /api/share_users (200) (2ms)
06:56:48 0|app  | 2024-06-20 06:56:48: App: GET /api/shares (200) (4ms)
06:56:55 0|app  | 2024-06-20 06:56:55: TaskService: Running #11 (Process shared items) (scheduled)...
06:56:55 0|app  | 2024-06-20 06:56:55: TaskService: Completed #11 (Process shared items) in 60ms
06:57:00 0|app  | 2024-06-20 06:57:00: TaskService: Running #12 (Process emails) (scheduled)...
06:57:00 0|app  | 2024-06-20 06:57:00: EmailService: Starting maintenance...
06:57:00 0|app  | 2024-06-20 06:57:00: EmailService: Maintenance completed in 1ms
06:57:00 0|app  | 2024-06-20 06:57:00: TaskService: Completed #12 (Process emails) in 43ms
06:57:05 0|app  | 2024-06-20 06:57:05: TaskService: Running #11 (Process shared items) (scheduled)...
06:57:05 0|app  | 2024-06-20 06:57:05: TaskService: Completed #11 (Process shared items) in 42ms
06:57:15 0|app  | 2024-06-20 06:57:15: TaskService: Running #11 (Process shared items) (scheduled)...
06:57:15 0|app  | 2024-06-20 06:57:15: TaskService: Completed #11 (Process shared items) in 43ms
06:57:25 0|app  | 2024-06-20 06:57:25: TaskService: Running #11 (Process shared items) (scheduled)...
06:57:25 0|app  | 2024-06-20 06:57:25: TaskService: Completed #11 (Process shared items) in 42ms
06:57:35 0|app  | 2024-06-20 06:57:35: TaskService: Running #11 (Process shared items) (scheduled)...
06:57:35 0|app  | 2024-06-20 06:57:35: TaskService: Completed #11 (Process shared items) in 62ms
06:57:45 0|app  | 2024-06-20 06:57:45: TaskService: Running #11 (Process shared items) (scheduled)...
06:57:45 0|app  | 2024-06-20 06:57:45: TaskService: Completed #11 (Process shared items) in 44ms
06:57:56 0|app  | 2024-06-20 06:57:56: TaskService: Running #11 (Process shared items) (scheduled)...
06:57:56 0|app  | 2024-06-20 06:57:56: TaskService: Completed #11 (Process shared items) in 134ms
06:58:01 0|app  | 2024-06-20 06:58:01: TaskService: Running #12 (Process emails) (scheduled)...
06:58:01 0|app  | 2024-06-20 06:58:01: EmailService: Starting maintenance...
06:58:01 0|app  | 2024-06-20 06:58:01: EmailService: Maintenance completed in 3ms
06:58:01 0|app  | 2024-06-20 06:58:01: TaskService: Completed #12 (Process emails) in 267ms
06:58:05 0|app  | 2024-06-20 06:58:05: TaskService: Running #11 (Process shared items) (scheduled)...
06:58:05 0|app  | 2024-06-20 06:58:05: TaskService: Completed #11 (Process shared items) in 43ms
06:58:15 0|app  | 2024-06-20 06:58:15: TaskService: Running #11 (Process shared items) (scheduled)...
06:58:15 0|app  | 2024-06-20 06:58:15: TaskService: Completed #11 (Process shared items) in 51ms
06:58:25 0|app  | 2024-06-20 06:58:25: TaskService: Running #11 (Process shared items) (scheduled)...
06:58:25 0|app  | 2024-06-20 06:58:25: TaskService: Completed #11 (Process shared items) in 44ms
06:58:35 0|app  | 2024-06-20 06:58:35: TaskService: Running #11 (Process shared items) (scheduled)...
06:58:35 0|app  | 2024-06-20 06:58:35: TaskService: Completed #11 (Process shared items) in 51ms
06:58:45 0|app  | 2024-06-20 06:58:45: TaskService: Running #11 (Process shared items) (scheduled)...
06:58:45 0|app  | 2024-06-20 06:58:45: TaskService: Completed #11 (Process shared items) in 42ms
06:58:55 0|app  | 2024-06-20 06:58:55: TaskService: Running #11 (Process shared items) (scheduled)...
06:58:55 0|app  | 2024-06-20 06:58:55: TaskService: Completed #11 (Process shared items) in 60ms
06:59:00 0|app  | 2024-06-20 06:59:00: TaskService: Running #12 (Process emails) (scheduled)...
06:59:00 0|app  | 2024-06-20 06:59:00: EmailService: Starting maintenance...

I am running Joplin Server v2.14.2 and am experiencing exact same issue as others have posted in past, ie
https://discourse.joplinapp.org/t/joplin-server-user-deletion-task-not-executing/28871
https://github.com/laurent22/joplin/issues/8757#issuecomment-2179968254

 The web UI indicates that the user is scheduled to be deleted and I also try to manually start selected task for running '8 Process user deletions '. The columns for Last Run and Last Completion show recent dates and times which make it appear that the process did run. 

However I do not believe the process successfully deleted the user because I can continue to login to that user account and that user continues to appear in user list in admin dashboard..

What steps can I take to delete a user?

Thank you

**Comment by laurent22** [comment]
The user deletion task is meant to slowly delete user data over time while minimising the risk of accidental data loss, it's not meant for instantly removing a user. It's mostly meant for Joplin Cloud really, I don't think it's very useful outside of it. Once you schedule a user for deletion you can see in the "User deletion" tab when the deletion is going to happen.

**Comment by chrislawso** [comment]
Hi, the user I need to delete has little or nearly no user data. This user was a test account created momentarily only to test email smtp password reset. This test user never connected or synced any joplin client data or any notebooks or notes. 

The "User deletion" tab shows user has been scheduled for deletion on 16 Jun 24 22:40:48 (UTC). 
That date and time was several days ago. If the deletion was supposed to occur in past and you suggest the deletion task is to slowly delete user data over time I continue to believe there is a problem given the information provided. 

Is there any steps I can perform to troubleshoot this issue further?

Thank you

**Comment by laurent22** [comment]
Could you share a screenshot of the User Deletion page? It works for me so not sure what the issue is

**Comment by chrislawso** [comment]
Hi,
Here is screenshot of the User Deletion page

https://pasteimg.com/image/h8RHO
