### ISSUE TITLE
Cursor and view move to random position on layout change (not always)

### ISSUE THREAD

**Issue by curiousbarbarian** [laurent22/joplin#10638]
### Operating system

Linux

### Joplin version

2.14.22

### Desktop version info

Joplin 2.14.22 (prod, linux)

Client ID: da427f77c5644293808709854992929e
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: e579eb9

Backup: 1.4.0
Kanban: 1.1.0

### Current behaviour

1. Open a long note (multiple screens).
2. Go to the end.
3. Switch to editor layout.
4. Start typing.
5. Switch to viewer layout.
6. See that cursor and view go somewhere top. Sometimes even multiple screens top.

### Expected behaviour

Cursor and view should stay where there were at the moment of switching layout.

Sorry for emotions, but it's super-duper annoying behavior.

**Comment by X1Vi** [comment]
I have noticed that issue if I am able to solve it I ll be back
