### ISSUE TITLE
WebDAV sync to mailbox.org (Open-Xchange)

### ISSUE THREAD

**Issue by heluca** [laurent22/joplin#1064]
### Operating system
- Windows
- Android

### Application
- Desktop
- Mobile

Joplin desktop creates the files in the WebDAV folder, but keeps reporting: "Error: MKCOL .sync/: Unknown error 2 (412): 

Android app reports the same error.

What does the error mean?

This WebDav service and account work fine with another app using WebDav (keepass)
Using URL:
https://office.mailbox.org/servlet/webdav.infostore/Userstore/FirstName%20LastName/Joplin/
Mailbox.org uses https://www.open-xchange.com/
Free demo accounts are available.

**Comment by weipah** [comment]
I think that might be a general Bug introduced somehow, because I see the same errors with Webdav sync with Nextcloud.

**Comment by laurent22** [comment]
I don't know how to setup an open-xchange account with WebDAV. If you can send me a username/password for testing I can look at it. Also, is the sync not working? Or is it just a warning message?

**Comment by weipah** [comment]
For me the webdav sync is wroking again. I have not tried with open-xchange, but with Nextcloud. The error disappeared by itself. I did not make any configuration changes, only kept all versions joplin up-to-date.
