### ISSUE TITLE
Joplin does not update notes when using an external editor

### ISSUE THREAD

**Issue by jr1234567** [laurent22/joplin#10647]
### Operating system

Linux

### Joplin version

3.0.10

### Desktop version info

Joplin 3.0.10 (prod, linux)
Client ID: 1e18f520ee284e08b45db5b014b0aaed
Sync Version: 3
Profile Version: 47
Keychain Supported: No
Revision: 45f8e27
Backup: 1.4.1
Insert Date: 1.0.1

### Current behaviour

Joplin does not take into account external editing 
It used to work in the past, 

### Expected behaviour

Joplin should update notes when editing in external editor.

**Comment by laurent22** [comment]
With which editor? It works for me on macOS

**Comment by jr1234567** [comment]
This is on Linux using neovim ("kitty nvim")
It did work in the past but it may be related to neovim as I've just tested using gedit and xed and it works with these 2 editors.

**Comment by personalizedrefrigerator** [comment]
> This is on Linux using neovim ("kitty nvim")
> It did work in the past but it may be related to neovim as I've just tested using gedit and xed and it works with these 2 editors.

I've also experienced this on Linux with Vim 9.1 and am currently working around it with a custom save command:
```vim
" ... .vimrc ...

" Needed by Joplin when running as an external editor.
" If necessary, replace with an autocmd (https://stackoverflow.com/a/74757597)
nnoremap ,w :w<CR>:!touch %<CR>
```

**Comment by jr1234567** [comment]
It works fine ! thank you !

Le ven. 21 juin 2024 à 16:12, Henry Heino ***@***.***> a
écrit :

**Comment by personalizedrefrigerator** [comment]
I'm closing this for now — the issue is also being tracked by https://github.com/laurent22/joplin/issues/10672.
