### ISSUE TITLE
Inline Code does not support Superscript and Subscript

### ISSUE THREAD

**Issue by nikhilkomakula** [laurent22/joplin#10657]
### Operating system

macOS

### Joplin version

2.14.22

### Desktop version info

Joplin 2.14.22 (prod, darwin)

Client ID: 05204d562d2e4ff69f62b1782fe0b3ab
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: e579eb9

Backup: 1.4.0

### Current behaviour

1. In a Note (call it Note1), create some superscript text like x2 (x-square) and mark it with inline code. It shows up just fine here.
2. Now switch to another Note (call it Note2) under the same or different Notebook.
3. Switch back to Note1 again, and now you see the text as "x< s u p >2</ s u p >" (added spaces in between "sup" just for rendering).

### Expected behaviour

Text marked with inline code should work as-is even if it contains superscript or subscript in the rich text editor.

**Comment by Daeraxa** [comment]
Took me a second to understand this as you hadn't escaped the `<sup>` in point 3. so it was rendered.

As the app is Markdown based I'm not actually sure there is a valid way to get superscript (or other formatting) within code blocks like that in which case maybe a non-conversion needs to be added and it stays as html.

**Comment by nikhilkomakula** [comment]
> Took me a second to understand this as you hadn't escaped the `<sup>` in point 3. so it was rendered.
> 
> As the app is Markdown based I'm not actually sure there is a valid way to get superscript (or other formatting) within code blocks like that in which case maybe a non-conversion needs to be added and it stays as html.

Thanks @Daeraxa. I updated the defect description. Thanks.
