### ISSUE TITLE
[Feature Request] Import From Omni-Notes

### ISSUE THREAD

**Issue by zero77** [laurent22/joplin#1065]
### Operating system

Android

### Application

Android

Can you please add support for importing from Omni-Notes.
Thanks

https://github.com/federicoiosue/Omni-Notes

**Comment by foxmask** [comment]
can you show us a piece of an exported note ?

**Comment by zero77** [comment]
@foxmask 
The backup is in a .json format and this is an example of a backup file.

> {"passwordChecked":false,"archived":false,"attachmentsList":[],"checklist":false,"content":"Test","creation":1545912427903,"lastModification":1545912427903,"locked":false,"reminderFired":false,"title":"Test","trashed":false}

**Comment by zero77** [comment]
@foxmask 
> "content":"Test" & "title":"Test"

I think the content and title parts are the most important.

**Comment by laurent22** [comment]
Omninotes won't be supported but you have two options :
- Convert the Json file to an Enex one, and import that Enex file
- Read the json from a programming language and import using the Clipper API
Both options unfortunately need some knowledge of programming.

**Comment by dapgo** [comment]
Omni-notes also store info in a SQLlite db file, so maybe the easiest is to select/update from a database to the other.

The other option is to generate the ENEX format  through SQL queries to the Omni-notes db.

[Omni-notes to Joplin request](https://github.com/dapgo/PIM_Data_Interoperability/issues/5)
