### ISSUE TITLE
Disable setting the resource mime type via API props

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10654]
### Operating system

Windows

### Joplin version

3.0.

### Current behaviour

Currently it's possible to set a resource mime type via the `props` property of the API when calling `PUT /resources`

We should disallow this because setting the mime type doesn't rename the local file so it won't work when opening the file.

Ref: https://discourse.joplinapp.org/t/how-does-joplin-determine-the-mime-type-of-a-resource/38726/5?u=laurent

**Comment by roman-r-m** [comment]
It's used on mobile though, at least on Android

**Comment by laurent22** [comment]
You mean a plugin is using this API on mobile?

**Comment by roman-r-m** [comment]
> You mean a plugin is using this API on mobile?

No, sorry I wasn't clear. I was referring to this:

> We should disallow this because setting the mime type doesn't rename the local file so it won't work when opening the file.

On android mime type determines how a file will be opened, I believe.

**Comment by roman-r-m** [comment]
See

https://github.com/laurent22/joplin/blob/dev/packages%2Fapp-mobile%2Fcomponents%2FNoteBodyViewer%2Fhooks%2FuseOnResourceLongPress.ts#L33

**Comment by pedr** [comment]
> See
> 
> https://github.com/laurent22/joplin/blob/dev/packages%2Fapp-mobile%2Fcomponents%2FNoteBodyViewer%2Fhooks%2FuseOnResourceLongPress.ts#L33

Roman, I'm not sure what you mean by this. The propose change is to disable the API that is used by the desktop app. When you create a resource, we will still be setting the `mime` property (see `createResourceFromPath` on `shim-init-node`)

**Comment by roman-r-m** [comment]
I was only saying that mime does determine how a file is opened on android, even if it doesn't on desktop

**Comment by laurent22** [comment]
Closing for now as I'm not sure we should make this change if it's going to limit what plugins can do. I think it's difficult assess the impact of the change
