### ISSUE TITLE
Generate deletion log

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10664]
Now that we are logging deletion actions, we should add an item, under the Help menu to generate a deletion log.

It would parse the existing log, and extract only deletion-related items. Then it would output a file with just those items.

Needs to work on both mobile and desktop.

**Comment by personalizedrefrigerator** [comment]
At least on mobile, this should be possible by opening the log screen with a `DeleteAction` filter:
![screenshot: Log screen: Filtering on "DeleteAction"](https://github.com/laurent22/joplin/assets/46334387/0487dba3-092e-43c9-af4a-a0ce1f521969)

We currently do something similar for plugin errors:
https://github.com/laurent22/joplin/blob/dfdc2fda27a0ae844b1dfac5dc9bca4696346589/packages/app-mobile/components/screens/ConfigScreen/plugins/utils/usePluginCallbacks.ts#L62

**Comment by Spoorthy1423** [comment]
Hey!! @laurent22 i would love to work on this issue , please assign me

**Comment by roman-r-m** [comment]
> Hey!! @laurent22 i would love to work on this issue , please assign me

We do not assign issues
