### ISSUE TITLE
Log in with a different user to Joplin Cloud doesn't update account information

### ISSUE THREAD

**Issue by pedr** [laurent22/joplin#10665]
### Operating system

Windows

### Joplin version

3.0.10

### Desktop version info

Joplin 3.0.10 (dev, linux)

Client ID: 8db24c567e5e4a54b9a9ae7d12757fd9
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 1ea3c91a3 (improve-joplin-cloud-connection-ux)

Backup: 1.4.1

### Current behaviour

1. On desktop, connect to Joplin Cloud with one account
2. Go to Joplin Cloud Login scren again
3. Now logout of your original account on Joplin Cloud website and enter another account
4. Authorize the new account to connect to the client
5. The account information doesn't update on Joplin Cloud settings screen ~and the synchronisation can't happen~

### Expected behaviour

1. On desktop, connect to Joplin Cloud with one account
2. Go to Joplin Cloud Login screen again
3. Now logout of your original account on Joplin Cloud website and enter another account
4. Authorize the new account to connect to the client
5. The account information should be updated on Joplin Cloud settings screen to the new one ~and allow synchronisation to happen~

**Comment by pedr** [comment]
I'm not even sure if this is a bug, anymore, since I tested on 2.14 and saw that this behaviour is similar.

I guess if you change the account on Joplin Cloud client the correct behaviour would be to change the account information in the settings screen for Joplin Cloud, even if won't be able to synchronise. I will try to address that.

**Comment by laurent22** [comment]
Yes I don't think we need to support this for now since we generally don't support swapping accounts for any sync target.

But is it actually possible to logout on the desktop app, and then login again?

**Comment by pedr** [comment]
> Yes I don't think we need to support this for now since we generally don't support swapping accounts for any sync target.
> 
> But is it actually possible to logout on the desktop app, and then login again?

Not in the desktop app, but the user can log out from the browser and log in on another account, go to Joplin Cloud Login screen and authorize that app in another account

**Comment by pedr** [comment]
Closing since it was already necessary to change the Profile to be able to connect to another Joplin Cloud account before the changes to login process
