### ISSUE TITLE
Upgrading from last version 2.x Joplin to latest 3.x facing folder expanding slowness issue.

### ISSUE THREAD

**Issue by toomding** [laurent22/joplin#10674]
### Operating system

Windows

### Joplin version

3.0.12

### Desktop version info

Joplin 3.0.12 (prod, win32)

Client ID: dbbb0ba7b0014de28c9c5f6cd297ea00
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: a64d6e3

Backup: 1.4.1

### Current behaviour

Since today received Joplin 3.x version upgrading reminder. I upgrade my 2 pc and 1 mac Joplin to the latest version.

All machines face slowness in expanding folders. I get a huge Joplin collections contain 23K notes and combined into multiple folders and layered and stacked folder and sub-folders.

So i used expand folder a lot. just after i upgrade to the latest it became very slow.

it can take 15s and even longer and it will then trigger the no response warning and let me decide if ignore or quite it.
![image](https://github.com/laurent22/joplin/assets/52145538/652f68da-b015-459e-83a2-79677ed43071)

If i choose to ignore and wait a longer it will eventually ok but take many times.

After restarted to safe mode, it is still slow, and it happened on 2 pc and 1 mac just after i upgrade to 3.0.12 version.

Nothing changed and just the version upgrading.

I used the backend server 2.14.2 and it is doing good.

The note is rendered well and perfect still. it just the slowness when expand folders.

My 2 pc and 1 mac is super-fast and no workload in background and i didn't see the cpu jump if i expand the folder.

### Expected behaviour

Expected it will be quick like <2s but now it takes 20s to be expanded and unable to do collections and order.

**Comment by toomding** [comment]
Hi Expert,

I reproduced the issue and expand a folder it takes > 20s.
![image](https://github.com/laurent22/joplin/assets/52145538/e2bed3e1-4543-47f7-ab3c-7bbb3c2a9d49)

and grab the Performance logs.

[Trace-20240703T094346.json](https://github.com/user-attachments/files/16075971/Trace-20240703T094346.json)

**Comment by toomding** [comment]
Thank you so much personalizeddrefrigerator, much appreciated for your swift work and quick insight on what the issue cause is going on. Please accept my deep thanks to you. 🤗

Wondering when this fix will hit the next release or what would be the next release number version of Joplin?

**Comment by personalizedrefrigerator** [comment]
> Wondering when this fix will hit the next release or what would be the next release number version of Joplin?

The fix has been merged into the [release-3.0](https://github.com/laurent22/joplin/commits/release-3.0/) branch. Hopefully it will be available in a few days!

**Comment by personalizedrefrigerator** [comment]
A user has [confirmed on the forum](https://discourse.joplinapp.org/t/whats-new-in-joplin-3-0/38867/19?u=personalizedrefriger) that this issue also seems to affect mobile.

**Comment by personalizedrefrigerator** [comment]
The fix should be available in [v3.0.13](https://github.com/laurent22/joplin/releases/tag/v3.0.13).
