### ISSUE TITLE
Mobile: cannot open previously opened note if navigating with links

### ISSUE THREAD

**Issue by ImperialSquid** [laurent22/joplin#10677]
### Operating system

Android

### Joplin version

3.0.7

### Desktop version info

N/A

### Current behaviour

1. Create two notes A and B
2. Have a link to A in B and vice versa
3. Open note A
4. Navigate to note B with link
5. Navigate back to A with link
6. Attempt to navigate to B again, link does nothing

### Expected behaviour

Links should take you to where you expect to go

### Logs

Had a look, didn't see any errors weirdly

**Comment by ImperialSquid** [comment]
Further weirdness:

- Navigating A -> B -> A not only prevents going back to B, it makes all links to other notes unresponsive (links that take you out of Joplin are unaffected)
- After A -> B -> A the dropdown at the top where you can change which notebook a note is in gets initially greyed out and is also unresponsive
- After A -> B -> A, pressing any note link un greys out the notebook dropdown and it can be used again (link still doesn't work after first press)
- After un greying out the notebook dropdown by attempting to follow a link, other links become useable again _except_ the one used to un grey out

(I'm aware there's a bunch of different behaviours being described here that might be one or more bugs, let me know if you need more details/want these as separate issues/etc)

**Comment by personalizedrefrigerator** [comment]
On iOS (from TestFlight) and [mobile deployed to web](https://personalizedrefrigerator.github.io/joplin/web-client/), this seems to work. I'm attaching version information (Configuration > More information > Copy version info) for comparison:
<details><summary>iOS</summary>

```
Joplin 13.0.3 (prod, ios)

Client ID: bd7dceef9c634159837b31252daa8fc9
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Quick Links: 1.3.2

iOS version: 17.5.1
FTS enabled: 1
Hermes enabled: 1
```


</details>

<details><summary>web</summary>

```
Joplin 3.0.0 (dev, web)

Client ID: 909bee992f0a4fcc80b1299b3e3d99f7
Sync Version: 3
Profile Version: 47
Keychain Supported: No

User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
FTS enabled: 1
Hermes enabled: 0
```

</details>

Note that the iOS and web patch versions are different from the Android version, even if built from the same commit.

**Comment by ImperialSquid** [comment]
Huh, so do you think it's an android exclusive issue?

Here's my version info if that's helpful:


<details><summary>Version info</summary>

Joplin 3.0.7 (prod, android)

Client ID: d94348b4ba434bb589db1fb87e33a45a
Sync Version: 3
Profile Version: 47
Keychain Supported: No

AlertsPerfect: 1.0.1
CodeMirror 6 settings: 1.0.0
History Panel: 1.0.2
Inline Tag Navigator: 0.8.0
Link Graph UI: 1.5.0
Note Tabs: 1.4.0
Quick Links: 1.3.2

Android API level: 34
WebView version: 126.0.6478.134
WebView package: com.google.android.webview
FTS enabled: 1
Hermes enabled: 1

</details>

**Comment by personalizedrefrigerator** [comment]
~~Does it also happen with plugin support disabled? (Configuration > Plugins > Advanced settings > Enable plugin support).~~ Ignore -- see below.

**Comment by personalizedrefrigerator** [comment]
> Huh, so do you think it's an android exclusive issue?

If note A and note B are in different notebooks, I can reproduce this on web and iOS.

**Comment by ImperialSquid** [comment]
Yep, can also confirm they have to be in separate notebooks and that plugins enabled/disabled doesn't affect anything for me too
