### ISSUE TITLE
Deleting Notebooks on click of delete Keyboard Key

### ISSUE THREAD

**Issue by harsh-791** [laurent22/joplin#10675]
### Operating system

Linux

### Joplin version

3.0.12

### Desktop version info

Joplin 3.0.12 (dev, linux)

Client ID: d6d921f8d92745daa99f74e8c5cddb1b
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 6215de608 (dev)

Backup: 1.4.1

### Current behaviour

If i have selected a particular noteboook, then i doesn't get  deleted on click of delete keyboard button

Steps to Reproduce:

  Open joplin.
  Select a notebook you wish to delete.
  Press the delete keyboard key.

Actual Result:

The notebook is not deleted. Users must double-click the notebook and then select the "Delete Notebook" option from the context menu to delete it.
![Screenshot from 2024-06-28 20-20-23](https://github.com/laurent22/joplin/assets/144247829/3e4b2527-4e95-45d8-8275-737719174547)

### Expected behaviour

Desired Functionality:

Please add support for using the delete keyboard key to delete selected notebooks. This enhancement will improve user efficiency and align with common user expectations for deleting files or items in many applications.

**Comment by shubhiscoding** [comment]
@laurent22 please assign this to me

**Comment by harsh-791** [comment]
@laurent22  i wish to resolve the issue

**Comment by Daeraxa** [comment]
1) This is a feature request rather than a bug and therefore needs to be discussed on the forum (unless you are indicating this is a regression in which case which version showed the correct behaviour last?).
2) We do not assign issues
