### ISSUE TITLE
Bug Shift+Del wants to delete the note

### ISSUE THREAD

**Issue by GigaTech** [laurent22/joplin#10685]
### Operating system

Windows

### Joplin version

3.0.12

### Desktop version info

Joplin 3.0.12 (prod, win32)

Client ID: 26c636c2b06d4d0395935193ad2eec1b
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: a64d6e3

Backup: 1.4.1
Email Note: 1.2.2

### Current behaviour

I upgraded from 2.14.22 to 3.0.12, now Shift+Del  tries to delete the note

### Expected behaviour

Shift+Del  should be 'cut', the same function as Ctrl+X which still works
Shift+Ins (same function as Ctrl+V) still works
Essential for left handed users

**Comment by personalizedrefrigerator** [comment]
A workaround might be to re-assign "permanently delete" from <kbd>shift</kbd>-<kbd>delete</kbd> to something else in Settings > "Keyboard Shortcuts", then restart Joplin.

![screenshot: Permanently delete note is assigned to shift+delete in the keyboard shortcut tab in settings.](https://github.com/laurent22/joplin/assets/46334387/9b4806c7-0bde-48b7-b717-7115534275c9)

**Notes**:
- [Microsoft standard keyboard shortcut list includes <kbd>shift</kbd>-<kbd>delete</kbd>](https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec):
    - "Shift + Delete  -  Delete the selected item without moving it to the Recycle Bin first."
    - Presumably, this description is for File Explorer, and not for text editors. Perhaps this command/keyboard shortcut should only be enabled when the note list is selected?

**Comment by laurent22** [comment]
> Perhaps this command/keyboard shortcut should only be enabled when the note list is selected?

Yes I guess it should only be enabled then. I see that there's no when clause like "noteListFocused" so maybe we could add one and make this a condition for "permanently delete note"

**Comment by GigaTech** [comment]
"only be enabled when the note list is selected" - perfect, when text is selected preform the equivalent of Ctrl+X and if note/To Do item or Notebook/folder is selected then perm delete. this is how windows and other apps work

Thanks
