### ISSUE TITLE
the icons in  editor's toolbar are almost the same

### ISSUE THREAD

**Issue by mathews** [laurent22/joplin#10688]
### Operating system

Linux

### Joplin version

3.0.12

### Desktop version info

Joplin 3.0.12 (prod, linux)

客户端 ID: 480cf8f7c5504b2a9c255a64677f87c7
同步版本：3
配置文件版本：47
支持的密钥链：否

修订：a64d6e3

Backup: 1.4.1
Better Code Blocks: 1.1.0
Combine notes: 1.2.2
Hotfolder: 1.2.0
macOS theme: 1.5.7
Math Mode: 0.6.2
Note overview: 1.7.1
Quick Links: 1.3.2
Rich Markdown: 0.15.0
Table Formatter Plugin: 1.2.1
Tagging: 1.0.3

### Current behaviour

![Uploading 2024-07-06_10-02.png…]()

**Comment by sanjanaynvsdl** [comment]
I would like to work on this issue could you please assign this to me @laurent22

**Comment by roman-r-m** [comment]
> I would like to work on this issue could you please assign this to me @laurent22 

We don't assign issues

**Comment by BHAV0207** [comment]
hey @mathews   the current behaviuor link is redirecting to the same page again please update the link .
