### ISSUE TITLE
Emojis are rendered incorrectly

### ISSUE THREAD

**Issue by gerelef** [laurent22/joplin#10683]
### Operating system

Linux

### Joplin version

3.0.12

### Desktop version info

Joplin 3.0.12 (prod, linux)

Client ID: 5c4be7c8a7b84edeb53eeda9f0196f22
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: a64d6e3

### Current behaviour

1. Open the app
2. Add/create/edit any new/existing folder and add an emoji via the 'select emoji' modal
3. Emoji is not rendered correctly

### Expected behaviour

Emojis should be rendered correctly

### Logs

Logs not needed, this is a visual regression, see below;

On the right, Joplin is open, with the notebook names being partially visible, and on their left is the broken rendering of emojis.
On the left, I googled '💁👌🎍😍' as to provide an example that the current (system) fontface is not the issue, to my knowledge, since they are rendered correctly using the system fontface (GNOME default).
Left highlighted emojis is the expected, right folder emojis is the regression.
![Pasted image](https://github.com/laurent22/joplin/assets/44060598/cd038e51-bc39-4c1e-b8f5-0f7297a9353e)

Relevant System specs:
# System Details Report
---

## Report details
- **Date generated:**                              2024-07-04 22:03:29

## Hardware Information:
- **Hardware Model:**                              Micro-Star International Co., Ltd. MS-7C37
- **Memory:**                                      16.0 GiB
- **Processor:**                                   AMD Ryzen™ 5 3600 × 12
- **Graphics:**                                    NVIDIA GeForce RTX™ 2070 SUPER
- **Disk Capacity:**                               3.5 TB

## Software Information:
- **Firmware Version:**                            A.80
- **OS Name:**                                     Fedora Linux 40 (Forty)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.9.7-200.fc40.x86_64

**Comment by gerelef** [comment]
I'd like to add that this issue happens on the editor as well:
![image](https://github.com/laurent22/joplin/assets/44060598/ac019d68-2a1a-41e1-8aa0-ec49836ab11f)

**Comment by personalizedrefrigerator** [comment]
Possibly related: https://github.com/laurent22/joplin/issues/9505

**Comment by gerelef** [comment]
If any steps can be done to help with debugging this, I'm available.
This looks like an issue where Joplin expects some sort of glyphs installed; that are obviously not.
I'm running the official joplin app installed via the `.sh` script. 
Any updates in terms of steps to be done to help w/ debugging this would be wonderful, this is terribly inconvenient :(
Issue persists on 3.0.14

**Comment by gerelef** [comment]
Issue was solved on my fedora (40) system by installing the `input-methods` group via dnf.

Example command for anyone else who stumbles upon this:

`sudo dnf group install -y input-methods`

Likely the `Noto Emoji` font was missing, and was installed via this group. Note that `rpmfusion` was enabled for my personal system.
