### ISSUE TITLE
How can I use the same folder in Windows and in Ubuntu without synchronization?

### ISSUE THREAD

**Issue by mseliger** [laurent22/joplin#1069]
At home I use Ubuntu as operating system, at work Windows 10. My data are stored on an USB drive. At the moment I use a sync directory to sync between the Windows Desktop Application and the Linux Appimage.

Windows Folder <--> Sync File Folder Joplin on external USB <--> Ubuntu Folder

Can I use the same folder both for Windows and Linux without syncing (perhaps with a profile?)

**Comment by foxmask** [comment]
Can you reserved the issue for bug and questionss on the forum https://discourse.joplin.cozic.net ?
Thanks;)
Otherwise the answer is yes.
