### ISSUE TITLE
Global search does not work reliable

### ISSUE THREAD

**Issue by scoroi** [laurent22/joplin#1072]
### Operating system
MacOS 10.14.2

### Application
Desktop 1.0.119 (prod, darwin)

After upgrade to the latest Joplin the global search does not work reliable, I have to modify the note to get it to be indexed (does not work all the time even after edit).
I cannot find a patter for which query exactly it does not work, it works sporadically.

**Comment by laurent22** [comment]
I'll need more info, an example of note or something. I know that it does not work well with Russian text at the moment.

**Comment by scoroi** [comment]
Please find bellow additional details.

**[Environment]**
MacOS 10.14.2
Desktop 1.0.119 (prod, darwin)

**[Setup config]**
1. Have hierarchical notebooks
2. "When creating a new note: focus body"

**[Steps]**
1. Select a notebook from root
2. Create a note with body: "exact match". Let the app set the title to same value
3. Select global search and copy paste "exact match"

**[Result]**
No results

**[Expected]**
Note is found and text selected both in title and body 

**[Side notes]**
1. After restart the copy paste into the field fiends the note
2. When performing manual typing following behavior is manifested:
a. "exact" search term finds the note
b. "exact m" does not find the note

**Comment by laurent22** [comment]
Search engine has been reworked in latest release so this bug is probably fix. Please give it a try and, if still not working, please open another issue
