### ISSUE TITLE
Flatpak sync broken by android

### ISSUE THREAD

**Issue by morphiak** [laurent22/joplin#10736]
### Operating system

Linux

### Joplin version

Joplin 2.14.22 Flatpak / Andoid 3.x

### Desktop version info

Joplin 2.14.22 Flatpak
Andoid 3.x

### Current behaviour

In order to sychronize plz update to 3.x on linux flatpak, android happy.

### Expected behaviour

This is expected, schema changes happen, it's just there should at least be a warning on the android side that this is breaking, frankly I would have kept desktop functionality (i.e. saving/syncing) first, the android is mostly a mirror in my use case. Would've been fine with a timely flatpak update (on Fedora Atomic (ublue-kinoite), so while I can use say the AUR distrobox version, I worry about switching causing issues)

Nevermind, v3 just dropped on flatpak, and best I can tell everything integrated well, kudos. I will however submit this anyway just to say flatpak should not be a second class citizen, leaving people unsaved for a week is a bad user experience.

That said, Joplin is great, well done ppl.

Go ahead and tag Solved...

**Comment by Perkolator** [comment]
> I will however submit this anyway just to say flatpak should not be a second class citizen, leaving people unsaved for a week is a bad user experience.

Flatpak Joplin is offered by a 3rd party, Joplin takes no responsibility of it.

> Go ahead and tag Solved...

You can close this issue too.

**Comment by personalizedrefrigerator** [comment]
For future reference, I'm linking to a few related issues/posts:
- https://github.com/flathub/net.cozic.joplin_desktop/issues/202
- https://discourse.joplinapp.org/t/joplin-on-flatpak-still-at-v2-cant-update-to-v3/39033
