### ISSUE TITLE
Dotted red underlines appear after using a code block in a `<details>` section

### ISSUE THREAD

**Issue by mamekoro** [laurent22/joplin#10732]
### Operating system

Linux

### Joplin version

3.0.13

### Desktop version info

Joplin 3.0.13 (prod, linux)

Client ID: f6a71a31d84140789a40c814095e1a8b
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 599cf5b

Backup: 1.4.1

### Current behaviour

When I tried to add a collapsible section to a note using the `<details>` tag, strange dotted red underlines appeared.

To reproduce, open a new note, then enter the following document to the editor pane.
I reproduced this with Joplin 3.0.13 AppImage on a clean-installed Ubuntu 22.04 virtual machine.

````markdown
`Cow<'a, str>`

<details>
<summary>Example</summary>

```rust
use std::borrow::Cow;
fn func<'a>(s: Cow<'a, str>, s2: &str) {}
```

</details>

`Cow<'a, str>`
````

As you can see in the screenshot below, dotted red underlines are drawn in the editor pane on the left. (The viewer pane on the right has no problem.)

![screenshot2](https://github.com/laurent22/joplin/assets/86554319/f7de5f33-62ed-40d1-b0c0-589cbe52978f)

I believe there might be a bug occurring when a `<details>` section contains a code block with a dotted red underline. This bug seems to cause dotted red underlines to appear on subsequent text, even when they shouldn't be there.

***

Note that the first and last lines of the example shown above are the same `Cow<'a, str>`, but there is a difference in whether a red dotted underline appears or not.

Besides, the former is correctly drawn in a monospace font as code, while the latter is drawn as normal text despite being surrounded by backticks.

The underlines will disappear if you remove the `<details>` and `</details>` tags or the code block.

This means the string `Cow<'a, str>` itself is not the cause of the problem, but a bug caused by using `<details>` tags and code blocks together.

### Expected behaviour

The document shown above should be drawn without dotted red underlines.

**Comment by personalizedrefrigerator** [comment]
This should be fixed in the beta markdown editor (Settings > General > Opt-in to the editor beta).

**Comment by mamekoro** [comment]
Confirmed. Thanks!
