### ISSUE TITLE
OCR is not working, Context menu shows no entry

### ISSUE THREAD

**Issue by TobyEU** [laurent22/joplin#10746]
### Operating system

Linux

### Joplin version

3.0.13 (prod, linux)

### Desktop version info

Joplin 3.0.13 (prod, linux)

Client-ID: 2931d45f8e164a75959fc7290f6eab2f
Sync-Version: 3
Profil-Version: 47
Unterstützter Schlüsselbund: Nein

Revision: 599cf5b

Backup: 1.4.1
Delete unlinked resources: 1.0.0
Freehand Drawing: 2.11.0
Markdown table calculations: 1.0.5
Markdown Table: Sortable: 1.2.2
Paste Special: 1.1.2

### Current behaviour

1. GUI language is German
2. Adding a attachment e. g. png (screenshot with readable text, not handwritten) to a note
4. Waiting a short time
5. Try to view OCR text via new context menu entry on attachment (https://github.com/laurent22/joplin/commit/8bdec4c2b4045365d18178167aa5142644ed8236)
6. Context menu shows: Open, Save as, Show file in directory, copy path, copy image (but due to language setting in German). 
7. Try to search for text on screenshot

Annotation:
Notes will be synchronized to WebDav. Other client is Android device. Joplin is in use still 2.x.
I'd had the feeling that the OCR wasn't working in the past, but now I can really check via the context menu, that something is wrong (now entry in context menu). Does anybody have an idea what is wrong? 

### Expected behaviour

1. File should be processed via OCR
2. Text should be searchable
3. OCR-Text should be visible via new context menu or message, that there is no text. Entry like: 
![grafik](https://github.com/user-attachments/assets/dd401900-3e90-48d4-af97-2f479dd44c79)

### Logs

21:52:27: OcrService: Starting background service...
node:internal/process/task_queues:95 21:52:27: OcrService: Found 0 resources to process...
/tmp/.mount_JoplincMeLTN/resources/app.asar/node_modules/@joplin/utils/dist/Logger.js:270 21:52:27: OcrService: 0 resources have been processed.
node:internal/process/task_queues:95 21:57:27: OcrService: Found 0 resources to process...
/tmp/.mount_JoplincMeLTN/resources/app.asar/node_modules/@joplin/utils/dist/Logger.js:270 21:57:27: OcrService: 0 resources have been processed.
/tmp/.mount_JoplincMeLTN/resources/app.asar/node_modules/@joplin/utils/dist/Logger.js:270 22:02:27: OcrService: Found 0 resources to process...
/tmp/.mount_JoplincMeLTN/resources/app.asar/node_modules/@joplin/utils/dist/Logger.js:270 22:02:27: OcrService: 0 resources have been processed.
node:internal/process/task_queues:95 22:07:08: OcrService: Found 1 resources to process...
node:internal/process/task_queues:95 22:07:27: OcrService: Found 1 resources to process...
node:internal/process/task_queues:95 22:12:27: OcrService: Found 1 resources to process...

/tmp/.mount_JoplincM…lib/TaskQueue.js:48 Uncaught (in promise) Error: Cannot push task when queue is stopping
    at TaskQueue.push (/tmp/.mount_JoplincM…/TaskQueue.js:48:19)
    at TaskQueue.<anonymous> (/tmp/.mount_JoplincM…/TaskQueue.js:60:18)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_JoplincM…b/TaskQueue.js:5:58)
node:internal/process/task_queues:95 22:17:27: OcrService: Found 1 resources to process...
/tmp/.mount_JoplincM…lib/TaskQueue.js:48 Uncaught (in promise) Error: Cannot push task when queue is stopping
    at TaskQueue.push (/tmp/.mount_JoplincM…/TaskQueue.js:48:19)
    at TaskQueue.<anonymous> (/tmp/.mount_JoplincM…/TaskQueue.js:60:18)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_JoplincM…b/TaskQueue.js:5:58)
node:internal/process/task_queues:95 22:22:27: OcrService: Found 1 resources to process...
/tmp/.mount_JoplincM…lib/TaskQueue.js:48 Uncaught (in promise) Error: Cannot push task when queue is stopping
    at TaskQueue.push (/tmp/.mount_JoplincM…/TaskQueue.js:48:19)
    at TaskQueue.<anonymous> (/tmp/.mount_JoplincM…/TaskQueue.js:60:18)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_JoplincM…b/TaskQueue.js:5:58)

**Comment by laurent22** [comment]
Could you restart the app and share the log again? I think the messages you have happen when you disable then quickly enable OCR again

**Comment by TobyEU** [comment]
@laurent22 thanks for investigating.
I've just played around with ticking OCR on and off and also restart the application.
Good story: OCR is generally working now :).

In which view the context menu with "View OCR text" should appear (after right-clicking the image)? I'm always using the split view and neither in the editor nor in the view panel it's working. The context menu in the rich text editor is also not showing the context menu entry.

How should the search regarding OCR text and identifying the attachments should work? Searching in the note (ctrl+F) is not working, but the "general" search is working.
In the note:
![grafik](https://github.com/user-attachments/assets/c217fbc8-25de-4521-bac6-223c67643ab0)
General:
![grafik](https://github.com/user-attachments/assets/3b81aaa2-0ba1-433d-98a4-ab4fd024fc08)

OCR:
`14:47:05: OcrService: Found 1 resources to process...
/tmp/.mount_JoplinFVXfNG/resources/app.asar/node_modules/@joplin/utils/dist/Logger.js:270 14:47:05: OcrService: Processing resource 1 / 1: 972fccbf454a4cba95a32d67aa7791bd (type image/png)...
/tmp/.mount_JoplinFVXfNG/resources/app.asar/node_modules/@joplin/utils/dist/Logger.js:270 14:47:05: OcrDriverTesseract: Created worker: 1`

Context menu:
Got ipc-message: contextMenu {type: 'image', resourceId: 'cd1bf330153b4f2ca140040b68e4b8c2'}

**Comment by laurent22** [comment]
It's used in general search only. And right-clicking the image should show the menu item

**Comment by TobyEU** [comment]
The menu entry item isn't appearing (and also no message box). Based on general search I know, that there was OCR text identified.
Also switching app language from German to English doesn't help. Log isn't helpful I guess.
Any hints want I can do to track down the issue?

Btw: Could the search be extended to note search or are there any reasons not doing that?

Log:
Got ipc-message: contextMenu {type: 'image', resourceId: '3d13478b8624473ba66b8be68e524dd6'}

**Comment by JackGruber** [comment]
Possible you try it on a image? 

For a an Resource Link like over the PDF preview or on a image link the `View OCR text` is working, but not directly on the PDF/Images

Clicked on the Link:
![image](https://github.com/user-attachments/assets/29b69b46-7cd9-46bc-9366-304d8ef65f99)

Clicked on the Image:
![image](https://github.com/user-attachments/assets/9eb5c509-3a98-4b07-8121-2365e349eca5)

**Comment by TobyEU** [comment]
> Possible you try it on a image?
> 
> For a an Resource Link like over the PDF preview or on a image link the `View OCR text` is working, but not directly on the PDF/Images
> 
> Clicked on the Link: ![image](https://private-user-images.githubusercontent.com/24863925/349560753-29b69b46-7cd9-46bc-9366-304d8ef65f99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzODUxNzgsIm5iZiI6MTcyMTM4NDg3OCwicGF0aCI6Ii8yNDg2MzkyNS8zNDk1NjA3NTMtMjliNjliNDYtN2NkOS00NmJjLTkzNjYtMzA0ZDhlZjY1Zjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDEwMjc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MGVkYzRkMjg0YmU4MTZjNTllNDY5NzAxNDFhODA0ZTIyZTIzMTFmOTkzMTA0YzUwZmRlNzRiOGE4NjYxNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Ms7to4gCJ71a-HbyKjERTprKF0Dj2Z3UYi3RsUNXPQ)
> 
> Clicked on the Image: ![image](https://private-user-images.githubusercontent.com/24863925/349560898-9eb5c509-3a98-4b07-8121-2365e349eca5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzODUxNzgsIm5iZiI6MTcyMTM4NDg3OCwicGF0aCI6Ii8yNDg2MzkyNS8zNDk1NjA4OTgtOWViNWM1MDktM2E5OC00YjA3LTgxMjEtMjM2NWUzNDllY2E1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDEwMjc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmYmVhOGMwYzQxOGIyOTdkYTBhNDNjZTlmNTAxMDRmN2Q4ZDgwMWEzMWYwMTk0YTM0NjgyNzM5YzUwMzViOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UnPOMqW89m8SF7-EB-HiJU6NJZwETauurz2Z5ZYbAwc)

Woah, that is the trick. Now it's feeling a little bit embarrassing for creating the ticket. But honestly I've never used the link feature, I'm always pasting the images, pdfs, directly in the note.
Is there any reason to limit the "view ocr data" to the link? Could it be also applicable when right-clicking directly on the image?

**Comment by JackGruber** [comment]
I think this could be classified as a bug, because you can't get the text of OCR images that are displayed and not included as link only.
