### ISSUE TITLE
joplin seem can't choise parent node when create notebook

### ISSUE THREAD

**Issue by kexirong** [laurent22/joplin#1077]
hope joplin can choise parent node when create notebook.
just like  in the picture.
![2018-12-26 17-31-24](https://user-images.githubusercontent.com/31177595/50441567-44e12300-0936-11e9-9c48-b3d552de0121.png)

**Comment by foxmask** [comment]
OS ? Plateforme ?

**Comment by kexirong** [comment]
> OS？Plateforme？

Joplin-1.0.117-x86_64.AppImage
