### ISSUE TITLE
Any Dokcer update?

### ISSUE THREAD

**Issue by wx2020** [laurent22/joplin#10774]
### Operating system

Linux

### Joplin version

N/A

### Desktop version info

N/A

### Current behaviour

I see the docker hub joplin/server was not updated for 6 months. Can you tell me when the update will be released?

**Comment by Terrance** [comment]
A 3.0 image was published last month.

Is there a way to get notified of these?  An RSS feed would be ideal though Docker Hub doesn't seem to provide one, there are no GitHub releases for the server (they are tagged, though the tags feed is a bit noisy and not easily filtered down), and I can't see any Discourse posts for them either?
