### ISSUE TITLE
Markdown rendering issue: Text above '-' line incorrectly formatted as header

### ISSUE THREAD

**Issue by smritidoneria** [laurent22/joplin#10770]
### Operating system

MacOS
### Joplin version

3.0.13

### Desktop version info

Joplin 3.0.13 (prod, darwin)

Client ID: f430ddb1156d45d994b50887776f73a7
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 599cf5b

Backup: 1.4.1

### Current behaviour

When a line of text is immediately followed by a line containing only a dash ('-'), the Markdown renderer incorrectly formats the text as a header. This is due to the Markdown parser interpreting the dash as a setext header underline. This behavior is inconsistent with standard Markdown syntax, where a line of dashes should only create a header if it is directly underneath a line of text, with no empty line in between.

https://github.com/user-attachments/assets/1d742c3d-8267-45f0-b6af-70d3e74cb9cb

### Expected behaviour

line containing only a dash ('-') should not affect the formatting of the preceding line of text

**Comment by personalizedrefrigerator** [comment]
I can reproduce this in the [upstream markdown-it test page](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22A%5Cn-%5Cn-%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D).

**Note**:

GitHub renders
```
a
-
-
```

as 

a
-
-
