### ISSUE TITLE
bug? on Math input

### ISSUE THREAD

**Issue by idealkindom** [laurent22/joplin#10790]
### Operating system

Windows

### Joplin version

3.0.13

### Desktop version info

Joplin 3.0.13

### Current behaviour

When I input Math like $\overrigharrow{v}$ the Joplin always fails toi render it, of which the reason is that Joplin  wierdly add one more \ at the begining of math input.

**Comment by personalizedrefrigerator** [comment]
Possibly related: https://github.com/laurent22/joplin/issues/9593
