### ISSUE TITLE
Manually downloading attachments is ineffective

### ISSUE THREAD

**Issue by lighcen** [laurent22/joplin#10792]
### Operating system

iOS

### Joplin version

13.0.7

### Current behaviour

Configuration - Synchronization - Attachment download behavior - Manual

Clicked picture icon can't download image.

but Attachment download Auto is OK.

**Comment by personalizedrefrigerator** [comment]
Interestingly, I can reproduce this in the release version of the app (13.0.7 on iOS 17.5.1), but not a development build built from the `ios-13.0.7` tag (iOS 17.4 simulator)...

Thank you for reporting this!

**Comment by personalizedrefrigerator** [comment]
I'm removing the "v3.1" label &mdash; this issue doesn't seem to be present in the 3.1.x branch (and thus only in 3.0.x).

**Edit**: See https://github.com/laurent22/joplin/pull/10748, [regression test](https://github.com/laurent22/joplin/blob/d1ac3d415ea7665271accd581807e1e5ae56feef/packages/app-mobile/components/NoteBodyViewer/NoteBodyViewer.test.tsx#L122)
