### ISSUE TITLE
Feature Request: Multiple note directories

### ISSUE THREAD

**Issue by ted-gould** [laurent22/joplin#108]
If Joplin was to support multiple sources of notes, then those sources could be shared using the underlying file sync's sharing support. So for instance I could have `/foo/joplin/notes` that was the default directory and `/foo/joplin/shared_with_family` that has another set of notes. Then I could use Dropbox/Nextcloud/etc. to share the second directory with my family to their Joplin directory.

I think this would add a powerful feature to Joplin using mostly the sharing ability of the networked filesystems.

**Comment by laurent22** [comment]
Unfortunately that wouldn't be possible without changing the architecture of the application.

**Comment by eandersons** [comment]
It would be really useful if Joplin supported multiple synchronisation sources therefore it could be used for multiple purposes (for example work (OneDrive) and private (Nextcloud) notes/to-dos on a phone). I understand that this feature would require big changes in the application, therefore this comment is more like +1 to the original feature request.
