### ISSUE TITLE
Unable to Paste Images in Joplin

### ISSUE THREAD

**Issue by raysnizzard** [laurent22/joplin#10803]
### Operating system

macOS

### Joplin version

3.0.14

### Desktop version info

Joplin 3.0.14 (prod, darwin)

Client ID: c7fae65fbf0b44a4b018a5dc980d7683
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 05cf51e

Backup: 1.4.1
Rich Markdown: 0.15.0

### Current behaviour

1. Copy an image from any source (e.g., web browser, image viewer).
2. Try to paste the image into a Joplin note using the paste command (Ctrl+V or Command+V)
3. Nothing happens; the image does not appear in the note, and there are no error messages.

![9TCVYLab](https://github.com/user-attachments/assets/acf3e308-74a2-46d5-bba6-37252feab0c1)

### Expected behaviour

The copied image should be pasted into the note, either as an embedded image or as a linked file.

**Comment by zhouxinghong** [comment]
The same error exists in Windows 10...

**Comment by laurent22** [comment]
Works for me on the Rich Text and Markdown editor. Please provide a specific example

**Comment by raysnizzard** [comment]
> Works for me on the Rich Text and Markdown editor. Please provide a specific example

Thank you for looking into this issue.

I have identified the cause of the problem. The issue was related to how CleanShot X handles screenshots. By default, CleanShot X stores the screenshot as a file in the clipboard, which Joplin cannot paste directly. After adjusting CleanShot’s settings to store screenshots as images in the clipboard, I am now able to paste images into Joplin without any issues.

**Comment by salihselimsekerci** [comment]
Proposed Solution:

The issue with exporting encrypted items can be resolved by ensuring that items are decrypted before they are exported. Here’s a sample fix:  

```
async function exportItem(item) {
    if (item.isEncrypted) {
        const decryptedItem = await decryptItem(item);
        return saveItem(decryptedItem);
    } else {
        return saveItem(item);
    }
}

async function decryptItem(item) {
    // Implement the decryption logic here
}
```

This change ensures that all items, regardless of encryption status, are correctly exported by decrypting them first. Please review and let me know if this approach works for you.
