### ISSUE TITLE
couldn't sync with WebDAV on my iPhone

### ISSUE THREAD

**Issue by zhangzscn** [laurent22/joplin#10805]
### Operating system

iOS

### Joplin version

13.0.7

### Expected behaviour

The setup is the same as Joplin on my computer, which synced with Joplin on my computer, but I couldn't sync with WebDAV on my iPhone. However, if URL2 is used on a LAN, it can be synchronized.

WebDAV URL：http://1.tcp.vip.cpolar.top:11730/homes/zzs/Joplin
WebDAV URL2：http://192.168.4.101:5005/homes/zzs/Joplin

**Comment by personalizedrefrigerator** [comment]
Be aware that `http` sync doesn't work with most domains on iOS. See https://github.com/laurent22/joplin/issues/10420#issuecomment-2103632934 for details.
