### ISSUE TITLE
SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by spe123** [laurent22/joplin#10802]
### Operating system

Windows

### Joplin version

3.0.13

### Desktop version info

Joplin 3.0.13 (prod, win32)

客户端 ID: 8783bafdf2074a40b898c3838ffd7331
同步版本：3
配置文件版本：47
支持的密钥链：是

修订：599cf5b

ABC Sheet Music Plugin: 1.0.2
Backup: 1.4.1
CodeMirror Options: 1.1.0
Copy Code Blocks: 1.0.0
EncDecModeV2: 2.0.1
Folding in Code Mirror Editor: 2.0.1
Freehand Drawing: 1.6.1
History Panel: 1.0.2
Hotfolder: 1.0.1
Joplin Evernote Links Replacer: 1.0.0
Kity Minder: 1.0.12
Make All Links: 1.0.3
Note Link System: 0.8.0
Note Tabs: 1.4.0
OCR: 0.3.2
Outline: 1.5.8
Pages Publisher: 1.7.1
Quick HTML tags: 0.1.1
Quick Links: 1.2.4
Resource Search Plugin: 0.1.2
Rich Markdown: 0.13.2
Search & Replace: 2.2.0
Spoilers: 1.0.6
Templates: 2.3.0

### Current behaviour

1、Notebook list is displayed incorrectly, the software is stuck, notes can't be edited, it often turns into a white window, only the menu bar is displayed, nothing else is displayed
2、displaError: Error: SQLITE_BUSY: database is locked: UPDATE `notes` SET `parent_id`=?, `title`=?, `body`=?, `created_time`=?, `updated_time`=?, `is_conflict`=?, `latitude`=?, `longitude`=?, `altitude`=?, `author`=?, `source_url`=?, `is_todo`=?, `todo_due`=?, `todo_completed`=?, `source`=?, `source_application`=?, `application_data`=?, `order`=?, `user_created_time`=?, `user_updated_time`=?, `encryption_cipher_text`=?, `encryption_applied`=yed error：

**Comment by laurent22** [comment]
Is it any better in safe mode? (in Help => Safe mode)

**Comment by spe123** [comment]
> Is it any better in safe mode? (in Help => Safe mode)在安全模式下会更好吗？（在帮助 => 安全模式下）

Thanks for the tip, I turned off some plugins and the problem seems to be solved, it does seem to be caused by a plugin, I'll try to find out what plugin is causing the problem later!
