### ISSUE TITLE
Shift-Del is "cut text" but in Joplin it deletes the note

### ISSUE THREAD

**Issue by sid3windr** [laurent22/joplin#10811]
### Operating system

Windows

### Joplin version

3.0.12

### Current behaviour

1. Select text to cut
2. Press Shift-Del (shortcut working since the MS-DOS days, I know Ctrl-X exists as well)
3. Get popup asking me to confirm deletion of the note

### Expected behaviour

1. Select text to cut
2. Press Shift-Del
3. Selected text is cut to the clipboard

**Comment by personalizedrefrigerator** [comment]
See https://github.com/laurent22/joplin/issues/10685. This should be fixed in [version 3.0.14](https://github.com/laurent22/joplin/releases/tag/v3.0.14).

**Comment by sid3windr** [comment]
Thank you! I tried to search but clearly failed. Downloading 3.0.14 now.
