### ISSUE TITLE
Turkish android joplin sync issue

### ISSUE THREAD

**Issue by aliilkertopcu** [laurent22/joplin#10836]
### Operating system

Android

### Joplin version

3.0.8

### Current behaviour

I am trying to sync the notes in a freshly built Joplin Server via android Joplin app. The error below shoots:

_Error: RNFetchBlob request
error: Unexpected char 0x131 at 4 in header name: **x-apı-mın-versıonnull**_

![image](https://github.com/user-attachments/assets/b4826080-ca68-4bec-887f-acbe66c11bbc)

I changed local language into EN but when I changed back into TR the error continueing to pop up. There are no setting for using just this app in english (S22 doesn't show Joplin in app specific language selection list, it doesn't support that). Users shouldn't be obligated to use their whole phone in another language to use an app in a specific language I think. So the palliative treatment is not working imho.

It seems as a localization error to me, the parameter causing the error shows as turkish character 'ı' (lower I): `x-apı-mın-versıonnull` instead: `x-api-min-versionnull`

The previous issue I found about is: 
https://github.com/laurent22/joplin/issues/10681

Also a turkish lowercase I (ı) is there:
![image](https://github.com/user-attachments/assets/a587f466-23ac-4e23-bdaf-0f079280a470)

**Comment by personalizedrefrigerator** [comment]
For reference, this issue should be fixed by https://github.com/laurent22/joplin/commit/8ff13e5fc48c176a3b3926549b3f03e5808b8023. However, this commit has yet to be included in a release.

**Comment by personalizedrefrigerator** [comment]
A fix should be in the [v3.1.2](https://discourse.joplinapp.org/t/android-pre-release-v3-1-is-now-available-updated-10-08-2024/39551/2) pre-release! (Be aware that there are a few new issues (e.g. [this one](https://github.com/laurent22/joplin/commit/39bd7d3aef2745185ebd6b104a9f2a08341a298a)) in the pre-release).
