### ISSUE TITLE
[Feature Request] Faster way to create multiple To-Dos

### ISSUE THREAD

**Issue by jv-barsuk** [laurent22/joplin#1083]
### Operating system

- Android
- iOS

### Application

- Mobile

Up to now it is not very handy to create a new To-Do on the mobile app. You need to 
- tab on the plus icon
- select New To-Do
- enter the title
- save it
- go back 
- and start again for the next item. 

It would be very handy if it would work like this:
- tab on the plus icon
- select New To-Do
- enter the title
- tab the return button
- the next blank To-Do opens
- enter the next title
- ...

**Comment by foxmask** [comment]
sliding the toolbar could help (I noticed that in GoogleKeep) https://github.com/laurent22/joplin/issues/1397#issuecomment-503554630
