### ISSUE TITLE
Investigate what requests Tesseract.js is making

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10835]
### Operating system

Windows

### Joplin version

3.0.0

### Current behaviour

By default Tesseract.js downloads the language model as needed. However, this behaviour is (or should be) disabled since we package the language model with the app.

However it seems Tesseract is still making some requests. We should investigate what are these requests and how to disable them.

**Comment by personalizedrefrigerator** [comment]
When I first enable OCR, Tesseract.js downloads the `.traindata` files for the current language from JsDelivr. This is done by the following upstream logic:

https://github.com/naptha/tesseract.js/blob/e8919a70888383b59a46b463be079c30d5860b20/src/worker-script/index.js#L141

After the first download, [these files should be read from a localStorage cache](https://github.com/naptha/tesseract.js/blob/e8919a70888383b59a46b463be079c30d5860b20/src/worker-script/index.js#L111).

[Tesseract.js's local installation documentation](https://github.com/naptha/tesseract.js/blob/master/docs/local-installation.md) states that this behavior can be overridden by customizing the `langPath`. Currently, we do not supply this path. Supplying this path would also mean bundling the `.traindata` files for OCR languages with Joplin (the GZipped English training data seems to be about 2 MiB). We don't seem to do this.

For reference, [this is the Joplin code that creates the Tesseract.js worker](https://github.com/laurent22/joplin/blob/500c31565de8c080fd7fb0a54d028c5a5e68635a/packages/lib/services/ocr/drivers/OcrDriverTesseract.ts#L61). Observe that it can specify `workerPath` and `corePath`, but not `langPath`.

**Comment by laurent22** [comment]
That's great, thanks for looking into this. Ok so we're bundling the worker and core files, but not the lang file although I thought we did. But indeed doing so could be a problem if we need to bundle all files for all languages. Let's see how we can possibly improve this - maybe there should be an option to download the OCR files from a specific (potentially self-hosted) URL, like we do for voice typing.
