### ISSUE TITLE
v3.0.14 pre-release doesnt update from linux installer and update script Ubuntu 24.04

### ISSUE THREAD

**Issue by IkaSumi33** [laurent22/joplin#10858]
### Operating system

Linux

### Joplin version

3.0.14

### Desktop version info

Joplin 3.0.14 (prod, linux)

Client ID: f02259b47a604fb58a45d04962747a80
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 05cf51e

Backup: 1.4.1
Combine notes: 1.2.2

### Current behaviour

When i run Linux installer and update script from CMD line  joplin v 3.0.14 doesn't update to latest pre-release v3.1.1 using
wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash -s – --prerelease
CMD line output  - You already have the latest version 3.0.14 installed.

Linux Installer & update script  v 3.0.14 - Doesn't update v3.0.14 to the latest pre-release v 3.1.2 either  ( 16Aug24)

### Expected behaviour

Update to the current new pre-release version to 3.1.1 or v 3.1.2 pre-release

**Comment by marph91** [comment]
I can't reproduce this. `wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash -s -- --prerelease` works for me.

Can you check that the hyphens in the command were not merged to a dash? I. e.

```bash
# wrong
bash -s – --prerelease

# correct
bash -s -- --prerelease
```

**Comment by IkaSumi33** [comment]
Hi marph91

Yes Having checked, It seems one of my CMD lists that I cut & paste from had the #wrong version (the one I used)

I have successfully upgraded using the #correct version from 3.0.15 to 3.1.3 pre-release while writing this response.
So all good
Thanks for pointing that out - this can be closed
