### ISSUE TITLE
Desktop: Error logged to console on startup

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#10865]
### Operating system

Linux

### Joplin version

3.1.1

### Desktop version info

Joplin 3.1.1 (dev, linux)

Client ID: 8e53753252dc4e05952f2d39c0462568
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: c4ebb64fb

Backup: 1.4.2

### Current behaviour

I'm getting an error in the console on startup.

In the terminal from which I ran `yarn start`:
```
Error occurred in handler for '__ELECTRON_LOG__': Error: No handler registered for '__ELECTRON_LOG__'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78277)
    at WebContents.emit (node:events:514:28)
    at WebContents.emit (node:domain:488:12)
```

In Joplin's development tools:
```
main-html.js:54 Error: electron-log isn't initialized in the main process. Please call log.initialize() before. Error invoking remote method '__ELECTRON_LOG__': Error: No handler registered for '__ELECTRON_LOG__'
    at /home/self/Documents/joplin/packages/app-desktop/node_modules/electron-log/src/renderer/electron-log-preload.js:36:33
```

`electron-log` seems to be used by `AutoUpdaterService.ts`.

### Expected behaviour

No error should be logged to the console.

**Comment by laurent22** [comment]
@AliceHincu , that's probably related to your recent change, seems like you need to initialize the package before using it
