### ISSUE TITLE
iOS: Shortcut Menu disappears when clicking ellipsis 

### ISSUE THREAD

**Issue by bsavant** [laurent22/joplin#10860]
### Operating system

iOS

### Joplin version

13.1.3

### Current behaviour

- Create a new note. 
- While trying to edit the body of the note, use ellipsis to open the menu for list options

https://github.com/user-attachments/assets/29f4dd6f-22eb-4fe1-ac99-a3aaf88849c6

### Expected behaviour

Ellipsis menu should display with shortcut options.

**Comment by Tommy-01** [comment]
Same here on Android with Version 3.1.1. 
Hope the new Version is coming quick. This version seems to have several bugs.
