### ISSUE TITLE
Markdown immediately following HTML isn't rendered correctly

### ISSUE THREAD

**Issue by urbite** [laurent22/joplin#10879]
### Operating system

Windows

### Joplin version

Joplin 2.14.23

### Desktop version info

Joplin 2.14.23 (prod, win32)

Client ID: cc3d6d3080164b5cbb264b01fa4efaef
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: 7b6a19a

Backup: 1.4.0

### Current behaviour

When HTML is immediately followed by markdown, the markdown is not rendered correctly. More specifically, the markdown is rendered as unformatted text.  _'Immediately followed by'_ means on the next line, e.g. there is no blank line between the HTML and markdown code.

In this specific case, an HTML table is immediately followed by a heading tag. Here's a screen cap from Joplin, with subject area highlighted. It's interesting to note that the markdown is rendered correctly in the markdown editor but not in the final output!?

![image](https://github.com/user-attachments/assets/0728bd7e-2e4b-4fe6-9b03-7e97614c82be)

Simply adding a blank line between the end of the HTML and the markdown fixes the issue.

![image](https://github.com/user-attachments/assets/dfe023a9-8dbc-48ba-9ada-eb975924b41b)

### Expected behaviour

The expectation is that Joplin would correctly render the markdown following html code, even without a blank line separating the two. As a simple test I pasted the *complete* HTML table and markdown as posted above into the Typora app and it rendered correctly.

### Typora source
![image](https://github.com/user-attachments/assets/875f8ef2-2e1f-4812-a524-841afd5f49ea)

### Typora rendered
![image](https://github.com/user-attachments/assets/c32bc909-bd07-4de0-aaf2-c57d97a8bcb4)

This can be reproduced by the following simple code block, with a blank html table
```
<table>
</table>
### Final repair
In all likelihood, the freezer light with the mondo LED will last long after 
```

**Comment by personalizedrefrigerator** [comment]
The upstream [`markdown-it`](https://github.com/markdown-it/markdown-it) editor [shows the same behavior](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Ctable%3E%5Cn%20%20%3Cthead%3E%5Cn%20%20%20%20%3Cth%3ETable%20Header%3C%2Fth%3E%5Cn%20%20%3C%2Fthead%3E%5Cn%20%20%3Ctbody%3E%5Cn%20%20%20%20%3Ctr%3E%3Ctd%3ERow%3C%2Ftd%3E%3C%2Ftr%3E%5Cn%20%20%3C%2Ftbody%3E%5Cn%3C%2Ftable%3E%5Cn%23%20Test%5Cn%5Cn%23%20Test%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D).

**Comment by urbite** [comment]
I'm not familiar with markdown-it. Is this a component in Joplin?

It is interesting that the same behavior is observed. Is there something in the markdown spec about what can or can't follow html?

Regarding the lack of a blank line between the end of the html table the markdown, this occurs in two places in one of my pages. I had a look at that page in OneNote and in both cases there is no line between the table and the heading.

Not stated previously in this issue, but I used [OneNote Md Exporter](https://github.com/alxnbl/onenote-md-exporter) to covert my OneNote notebook. Apparently the converter is correctly passing on the line spacing (or lack thereof) in the notebook.

**Comment by personalizedrefrigerator** [comment]
> I'm not familiar with markdown-it. Is this a component in Joplin?

`markdown-it` is a JavaScript library for rendering Markdown to HTML. Joplin renders Markdown with an extended version of the `markdown-it` library. 

This [issue on `markdown-it`'s GitHub repository may be relevant](https://github.com/markdown-it/markdown-it/issues/478).

**Edit**: This seems to be the [relevant part of the CommonMark spec](https://spec.commonmark.org/0.31.2/#html-blocks):
> [...]
> 6. **Start condition:** line begins with the string < or </ followed by one of the strings (case-insensitive) address, article, aside, base, basefont, blockquote, body, caption, center, col, colgroup, dd, details, dialog, dir, div, dl, dt, fieldset, figcaption, figure, footer, form, frame, frameset, h1, h2, h3, h4, h5, h6, head, header, hr, html, iframe, legend, li, link, main, menu, menuitem, nav, noframes, ol, optgroup, option, p, param, search, section, summary, table, tbody, td, tfoot, th, thead, title, tr, track, ul, followed by a space, a tab, the end of the line, the string >, or the string />.
> **End condition:** line is followed by a [blank line](https://spec.commonmark.org/0.31.2/#blank-line).
>
> [...]
>
> HTML blocks continue until they are closed by their appropriate [end condition](https://spec.commonmark.org/0.31.2/#end-condition), or the last line of the document or other [container block](https://spec.commonmark.org/0.31.2/#container-blocks). This means any HTML within an HTML block that might otherwise be recognised as a start condition will be ignored by the parser and passed through as-is, without changing the parser’s state.
>
> &mdash; https://spec.commonmark.org/0.31.2/#html-blocks
