### ISSUE TITLE
Joplin for Android crashes when opening configuration screen or pressing synchronize button

### ISSUE THREAD

**Issue by mrjo118** [laurent22/joplin#10870]
### Operating system

Android

### Joplin version

3.0.8

### Desktop version info

Asus Zenfone 3 running Android 6.0.1. I'm aware this is a very old OS version, but I can no longer get any updates on the phone as Asus has de-supported it and removed all download links to their firmware for it, even though the model theoretically supports up to Android 8

### Current behaviour

Opening the configuration screen via the button on the side panel, or pressing synchronize button, results in the app crashing with the error popup "Unfortunately, Joplin has stopped"

### Expected behaviour

The app should not crash but the buttons should do the intended behaviour

**Comment by personalizedrefrigerator** [comment]
This (unreleased) commit may be related: https://github.com/laurent22/joplin/commit/60e347a78290643960c3af55af444f528c0cf988

**Comment by mrjo118** [comment]
@personalizedrefrigerator You may be right. I have tried an older apk I have (v2.13.10) and I don't get the crash. Do you have a development apk for a newer release which includes that fix, so I can verify that?

**Comment by personalizedrefrigerator** [comment]
The commit hasn't been included in a pre-release yet (but it should be soon!).

For reference, [Android pre-releases can be found here](https://discourse.joplinapp.org/t/android-pre-release-v3-1-is-now-available-updated-10-08-2024/39551/2).

**Comment by mrjo118** [comment]
I can confirm that this is fixed in prerelease 3.1.3
