### ISSUE TITLE
Regression of reordering selected lines between 3.0.8 and 3.1.1

### ISSUE THREAD

**Issue by mcmxcdev** [laurent22/joplin#10895]
### Operating system

Linux

### Joplin version

3.1.1

### Desktop version info

Joplin 3.1.1 (prod, linux)

Client ID: b4a9f9fb862543058da6a46087ada545
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: a97c04c

Backup: 1.4.2

### Current behaviour

In this video I am showcasing:
- hitting Alt+Up/Down reorders one line at a time (expected behavior)
- selecting multiple lines and hitting Alt+Up/Down only moves "F" instead of "D", "E" and "F" (regressed behavior)

https://github.com/user-attachments/assets/6e9c1265-de2e-42c9-8b0a-4f09a56cb480

### Expected behaviour

All highlighted lines should be reshuffled up or down respectively when pressing Alt+Up/Down.

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!


**Note**: In the 3.1.x pre-release, the previously-in-beta Markdown editor was made the default. The legacy Markdown editor can be enabled under Settings > general > advanced.

**Comment by mcmxcdev** [comment]
Oh very interesting! I was able to go back to the legacy markdown editor and it now works again as expected ;)

Nice to have a workaround and hoping for this to get fixed eventually.
