### ISSUE TITLE
Export to md via joplin cli creates numbered extra subdirectories

### ISSUE THREAD

**Issue by peter-sc** [laurent22/joplin#1090]
### Operating system

- Windows

### Application

- Desktop
- Terminal

The note in notebook is saved as:

Notebook \ folder \ note1
Notebook \ folder \ note2

If I export all notes to md format via Desktop app , then the correct folder structure with names is created:

Notebook \ folder \ note1
Notebook \ folder \ note2

If I export via cli command (Windows WSL)
```
PROFILE="/mnt/c/Users/username/.config/joplin-desktop"
BACKUP_DIR="/mnt/c/Users/username/Joplin-notes-md-format"
JOPLIN_BIN="/usr/bin/joplin"
$JOPLIN_BIN --profile "$PROFILE" --log-level debug export --format md "$BACKUP_DIR"
```

Then for the first time, notes are exported correctly

Notebook \ folder \ note1
Notebook \ folder \ note2

After deleting all the files and folders in BACKUP_DIR and doing subsequent export, following structure is created

Notebook \ folder \ **(1)** \ note1
Notebook \ folder \ **(2)** \ note2

So all the notes inside of folder are stored in another directory, each note having it's own and names (number).

My goal is to export all notes via cron script in md format, add to git, so changes in each note can be easily seen.

**Comment by foxmask** [comment]
> After deleting all the files and folders in BACKUP_DIR 
did you sync stuff before this 
> and doing subsequent export, following structure is created
?

**Comment by peter-sc** [comment]
OK I found the problem. My backup script had following commands:

```
cd "$BACKUP_DIR"
rm -rf Notebook
rm -rf _resources
$JOPLIN_BIN --profile "$PROFILE" --log-level debug export --format md "$BACKUP_DIR"
```

If the export command is executed, while we are in the same directory as the export is saved to, the (1) directories are created.

If I changed the script as following, then it works correctly and no duplicated directories are created. Maybe this isn't a bug, but a feature?

```
cd "$BACKUP_DIR"
rm -rf Notebook
rm -rf _resources
cd ..
$JOPLIN_BIN --profile "$PROFILE" --log-level debug export --format md "$BACKUP_DIR"
```

**Comment by laurent22** [comment]
Yes it's a feature. I do the same as your cron script but I delete the content before exporting the data, that way it's exactly the data as it is in Joplin (including notes that have been deleted). Also in your case it's probably better to use the "raw" format when exporting, that way you also have tags and other metadata.
