### ISSUE TITLE
TypeError: t.clone is not a function in latest version

### ISSUE THREAD

**Issue by steven-twerdochlib** [laurent22/joplin#10908]
### Operating system

Windows

### Joplin version

1.11.12

### Current behaviour

I've upgraded my version from version 1.11.10 to 1.11.12 but now I'm getting the error: "TypeError: t.clone is not a function" when running my unit-tests, I don't think this minor upgrade had any breaking changes so I'm suprised this is happening.

This is the line being test: `dayjs(variableName1).format('YYYY-MM-DD')` where I set variableName1 in unit test like this: `wrapper.setData({ variableName1: dateUtils.newDateUTC(String('2015' + '-' + '11' + '-' + '10'), 'YYYY-MM-DD') } );`
The below function is in dateUtils btw:
```
export function newDateUTC(value: string, format: string): Dayjs | null {
  if (value) {
    return dayjs.utc(value, format);
  } else {
    return null;
  }
}
```

### Expected behaviour

My unit tests should all pass like in version 1.11.10.

**Comment by laurent22** [comment]
I don't understand what you mean. Version 1.11.12 is very old obviously, and why would you run unit tests on it?

**Comment by steven-twerdochlib** [comment]
Sorry I just realised that I was sent to the wrong github xD sorry
