### ISSUE TITLE
"Jolplin/info.json" is locked on v3 (OK on v2)

### ISSUE THREAD

**Issue by mammique** [laurent22/joplin#10917]
### Operating system

Android

### Joplin version

3.1.2 and 3.0.9

### Desktop version info

Since I updated to v3.1.2 I get the following error:

![image](https://github.com/user-attachments/assets/da9f1f72-e356-4273-b577-5147076d8694)

When I downgrade to v2.14.9 everything works fine:
![image](https://github.com/user-attachments/assets/7186a6e5-3f2a-4af3-af02-41121dd3f16e)

I tried with v3.0.9 but same bug.

I'm using nextcloud docker on server side (raspberry).

**Comment by iTrooz** [comment]
This issue also affects me. What's weird is that it only occurs on mobile (Android, 3.0.8) but not on desktop (AppImage,  3.0.13)

**Comment by iTrooz** [comment]
I managed to fix the issue by deleting the content of the table `oc_file_locks` in my Nextcloud (28.0.4)

Sources:
https://discourse.joplinapp.org/t/nextcloud-sync-issue-on-desktop-but-not-mobile/21355/2
https://help.nextcloud.com/t/file-is-locked-how-to-unlock/1883
