### ISSUE TITLE
Pressing "show more actions" (3 dots) just hides the whole bottom menu

### ISSUE THREAD

**Issue by trololot** [laurent22/joplin#10916]
### Operating system

Android

### Joplin version

Joplin Mobile 3.1.2 (prod, android) - from F-Droid

### Current behaviour

When editing a note, there's a horizontal menu bar at the bottom with these options: "Bold", "Italic", "Code", "Show more options", "Task list", "Link", "Find and replace". The 4th item in this menu - "Show more options" (3 dots) used to open more menu options, like the button for inserting the current date and time, for example. But it broke in the latest (or one of the latest) updates - pressing those 3 dots in the latest version(s) just hides the whole menu instead of showing more options.

### Expected behaviour

Pressing "Show more options" used to do just that - it showed more options. Now it just hides the whole bottom menu bar.

**Comment by personalizedrefrigerator** [comment]
See https://github.com/laurent22/joplin/pull/10871, https://github.com/laurent22/joplin/issues/10860 &mdash; a [fix](https://github.com/laurent22/joplin/commit/39bd7d3aef2745185ebd6b104a9f2a08341a298a) has been merged, but has not yet been included in a mobile release. Note that F-Droid distributes pre-release versions of Joplin.

**Edit**: Reformatted.

**Comment by trololot** [comment]
Thanks for the quick reply! I looked through other open issues here before posting this one and couldn't find this bug mentioned elsewhere, missed those two posts somehow, sorry. Great to hear it's going to get fixed!
