### ISSUE TITLE
[FR] Add folder Nextcloud

### ISSUE THREAD

**Issue by oasisck** [laurent22/joplin#1092]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

Hi,
My personnal folder in Nextcloud is a mess due to .md files.
A directory would be nice
Thanks 👍

**Comment by BioFacLay** [comment]
You can create your own folder and add it to the path. But I agree, there could at least be a warning.

**Comment by oasisck** [comment]
Whoops happy RTFM to myself :-)
Thanks 👍
