### ISSUE TITLE
Locked out of Android app due to broken fingerprint scanner

### ISSUE THREAD

**Issue by mrcjkb** [laurent22/joplin#10926]
### Operating system

Android

### Joplin version

3.0.8

### Current behaviour

1. Enable biometric unlock
2. Break fingerprint scanner on device (optional)
3. Remove all fingerprints from device
4. Try to open Joplin 
5. Error message: Could not verify identity. Biometric unlock is not set up on the device.

### Expected behaviour

The app falls back to asking for a PIN

**Comment by laurent22** [comment]
I thought the app was setup to not ask for fingerprints if it's disabled on the device but apparently not.

**Comment by Devilon68** [comment]
Type: Multimedia message
Subject:
Priority:Unknown
From: 019-717 7588
To: 014-233 2890
Sent:08/24/24 3:01 pm
Received:08/24/24 3:01 pm
