### ISSUE TITLE
Desktop: Cmd+Left and Cmd+Right no longer do Back/Forward in Markdown Editor

### ISSUE THREAD

**Issue by bsavant** [laurent22/joplin#10921]
### Operating system

macOS

### Joplin version

3.1.3

### Desktop version info

Joplin 3.1.3 (prod, darwin)

Client ID: 1dfa99475d17480db74956dc092b7dfc
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 263a7ef

Backup: 1.4.2
Draw.io: 2.2.0
Embed Search: 2.0.0
Freehand Drawing: 2.11.0
Inline tags: 1.3.0
Insert Date: 1.0.1
Note Tabs: 1.4.0
Quick Links: 1.4.1
Rich Markdown: 0.15.0
Templates: 2.4.0

### Current behaviour

1. Create a few different notes
2. Navigate through the notes to build navigation history
2. Use Cmd+Left to go to the Previous note

### Expected behaviour

Cmd+Left should move to the previous note, instead it moves to the beginning of the current line.

**Comment by bsavant** [comment]
Cmd+Left and Cmd+Right are added as custom shortcuts.  I've tried with other keys too and this still doesn't seem to be working.  Also see [10578](https://github.com/laurent22/joplin/issues/10578)

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

> I've tried with other keys too and this still doesn't seem to be working.

On Linux (Fedora 40 with Joplin 3.1.3), I'm able to assign <kbd>alt</kbd>-<kbd>left</kbd> to "Back" in settings and (after restarting Joplin), <kbd>alt</kbd>-<kbd>left</kbd> moves to the previously selected note. Perhaps this is specific to MacOS?

**Edit**: Does it work with non-<kbd>Cmd</kbd> modifier keys? (E.g. <kbd>Control</kbd>?) **Edit 2**: Yes, but only for non-arrow-key shortcuts.
