### ISSUE TITLE
Shortcut to switch between notes

### ISSUE THREAD

**Issue by gyaaniguy** [laurent22/joplin#1093]
- Windows
- Desktop

Is there any such feature ? 
Also I can't seem to find any shortcuts, beyond the ones on the menu items..

**Comment by matsest** [comment]
AFAIK there is no shortcut for direct switching between notes when editing a note. 

However, if you have focused the note list you could use Tab or Shift+Tab to change focus to other notes and then press Enter to focus it.

A simple arrow-up/down implementation could be useful :)

**Comment by hb20007** [comment]
In Cherry Tree, if you press `Ctrl` + `Tab`, focus shifts from editing a notebook to the note list. This would be great.
