### ISSUE TITLE
NPM package joplin import raw doesn't search for resources in `.resource`

### ISSUE THREAD

**Issue by martinkozle** [laurent22/joplin#10936]
### Operating system

Linux

### Joplin version

3.0.1

### Desktop version info

Joplin CLI Client

Copyright © 2016-2024 Laurent Cozic
joplin 3.0.1 (prod, linux)

Client ID: fa3b86d7d3b243d8b4ebf494fe03161f
Sync Version: 3
Profile Version: 47
Keychain Supported: No

### Current behaviour

Running `joplin import --format raw ...` tries to find resources under `resources` with a file extension, while my other clients are saving them under `.resource` without a file extension.

I am not sure if the NPM package is still supported?

### Expected behaviour

The npm package's import command to find the resources under `.resource`.

### Logs

Full path redacted.

Importing notes...
Could not find resource file: .../resources/0ca26349245244cd883a62a07e2b06f3.png
...

**Comment by laurent22** [comment]
It's not supposed to support this. It can only import what's been exported as "raw". I think you're trying to import a sync target

**Comment by martinkozle** [comment]
Aha, I thought that sync targets were supposed to be in raw form, I guess I have misunderstood this. Is there a way to import from format with the NPM CLI?

**Comment by laurent22** [comment]
No, but you can sync with it and then export the notes

**Comment by martinkozle** [comment]
Alright, thanks for the help.
