### ISSUE TITLE
Right Alt Key

### ISSUE THREAD

**Issue by GigaTech** [laurent22/joplin#10934]
### Operating system

Windows

### Joplin version

3.0.13

### Desktop version info

Joplin 3.0.13 (prod, win32)

Client ID: 26c636c2b06d4d0395935193ad2eec1b
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 599cf5b

Backup: 1.4.1
Email Note: 1.2.2

### Current behaviour

Alt+Up and Alt+Down works great to move line up or down, but the right Alt key does nothing, I cannot even create a new mapping in Options >> Keyboard Shortcuts, as the Right alt key is not recognised when pressed.

The right Alt key is closer to the arrow keys and allows for a one-handed function/action

### Expected behaviour

Alt should 'mean' both left and right Alt keys or if not then pick one and allow us to remap to the other

Thanks

**Comment by tomasz1986** [comment]
> I cannot even create a new mapping in Options >> Keyboard Shortcuts, as the Right alt key is not recognised when pressed.

This depends on your language and keyboard layout. For example, when using English (US), you can map shortcuts with the right Alt key. However, this isn't the case when using Polish, where the right Alt key is the modifier for some Polish letters. The same is likely true for other languages, which use the right Alt key in a similar manner.

What is your keyboard language and layout?

**Comment by GigaTech** [comment]
Keyboard layout, English (UK)

**Comment by tomasz1986** [comment]
Yeah, the right Alt key on the UK layout is not actually the same right Alt key as on the US layout. Its other name is AltGr (see [https://en.wikipedia.org/wiki/AltGr_key](https://en.wikipedia.org/wiki/AltGr_key)). It seems that Joplin doesn't allow to use AltGr in shortcuts.

**Comment by GigaTech** [comment]
ok great, can this be changed?

**Comment by GigaTech** [comment]
Hi, is there any plan to add this functionality?

Allow the use of AltGr key in shortcuts

**Comment by StephenArg** [comment]
Option-up and option-down don't work for me on the Mac desktop app. I actually tried remapping "swap up" to other hot keys but it still doesn't work. Is this a bug?
