### ISSUE TITLE
Three or more dashes (---) render the lines above it as bold instead of displaying a line

### ISSUE THREAD

**Issue by ratchek** [laurent22/joplin#10930]
### Operating system

Linux

### Joplin version

2.11.11

### Desktop version info

Joplin 2.11.11 (prod, linux)

Client ID: 637787a2b9a942ec806963b8ee8bf3ab
Sync Version: 3
Profile Version: 43
Keychain Supported: No

Revision: 6886f6f

Note Tabs: 1.4.0

### Current behaviour

When inserting three or more dashes in a new line, it doesn't create a line, but instead bolds previous lines according to these rules:
- In the markdown editor:
	- bolds the line immediately before the three dashes
- In the markdown preview window:
	- bolds all the lines before the three dashes but stops after it encounters an empty line.

### Notes:
- This doesn't happen when using stars * instead of dashes
- This *might* be some intended interaction regarding formatting tables with markdown, but I couldn't find any mention of it in the documents, so I'm assuming that is not the case.
- I tested this still happens on a fresh profile, but did not test on a fresh install

![Screenshot from 2024-08-25 21-24-43](https://github.com/user-attachments/assets/aeec9630-3ae2-4717-9f0b-543e79a939b3)

### Expected behaviour

Should render a line and not bold the lines above it.

**Comment by MatsG23** [comment]
Not a bug but a correct implementation of the Markdown spec. To render a divider, you have to write three hypens surrounded by empty lines, like this:
```
Lorem ipsum

---

Lorem ipsum
```

The new lines are important - if you write two or more hypens under a text, you style the text as a h2 heading. See [here](https://www.markdownguide.org/basic-syntax/#alternate-syntax). Alternatively you can write `- - -`, this will work out without new lines.

**Comment by ratchek** [comment]
Ah, I see. My bad. 
Neither of those will work because I was hoping to be adding frontmatter to my notes, but thank you for the recommendations!
