### ISSUE TITLE
[FR] Move to Notebook in right-click menu (Desktop)

### ISSUE THREAD

**Issue by matsest** [laurent22/joplin#1094]
### Operating system

- Windows
- macOS
- Linux

### Application

- Desktop

### Description

Even though dragging a note to a notebook works as a charm for moving notes between notebooks, I would like to suggest implementing the "Move to Notebook" [feature from mobile](https://github.com/laurent22/joplin/blob/master/ReactNativeClient/lib/components/screen-header.js) into the right-click menu in the Desktop version.

It would be consistent with the current entries in the right-click menu to have an entry for "Move to Notebook" with a submenu with entries of the different notebooks.

I'm not experienced in js but from what I can see this could be implemented in [itemContextMenu](https://github.com/laurent22/joplin/blob/master/ElectronClient/app/gui/NoteList.jsx) by listing the notebooks and using moveToFolder from [Note.js](https://github.com/laurent22/joplin/blob/master/ReactNativeClient/lib/models/Note.js). Or something like that.. What do you think? :)

**Comment by matsest** [comment]
Should still be open - would be very useful!

**Comment by matsest** [comment]
.

**Comment by chrischoy** [comment]
I second this. It would be very useful to have this feature. Especially for the mobile environment.
