### ISSUE TITLE
Feature request: Allow modifying attachments

### ISSUE THREAD

**Issue by fmrtn** [laurent22/joplin#1095]
### Operating system

- Windows
- macOS (not tested)
- Linux

### Application

- Desktop

Scenario:

I create a note (or todo) on "A" computer and I attached an spreadsheet with some content, after sync I can see the note and the attached file in computer "A" and "B"

Behavior:

If I edit the file (clicking in the link on the note) in any computer (A or B) the attached file did not sync anymore, the contents is modified locally only.

Tested with latest version (1.0.119) on Windows and Linux, with WebDAV sync and File System sync (relying on Seafile client for do the sync work).

**Comment by zgec** [comment]
Is this planned to be fixed?

This would be a really great feature if it worked. Allowing to attach lets say a .ods file, edit it from time to time and it would sync up with the rest of the notes...

**Comment by Nebucatnetzer** [comment]
I just noticed the same behaviour today.
It's a really counter intuitive behaviour.

This issue is mentioned in a few issues already, most of the time with a comment that there already exists an issue for this.
Since it wasn't linked I had to search it and I reckon it's this one here: https://github.com/laurent22/joplin/issues/279

**Comment by Dasymi** [comment]
It would be great if this was fixed. I used this feature a lot in Evernote, with spreadsheets and Word documents saved in Evernote and then editable on any device.

**Comment by IpeTek** [comment]
Nebucatnetzer: 
> It's a really counter intuitive behaviour.

This counter intuitiveness used to be the norm in OneNote up until this week. 

I am pro fixing/changing this in Joplin, too.

**Comment by swdrumm** [comment]
Will fixing this issue also correct the general file system sync problem mentioned in the forum here?

https://discourse.joplinapp.org/t/attachments-sync/1191/18

**Comment by Nebucatnetzer** [comment]
I don't think this one should be closed.

**Comment by s1291** [comment]
@swdrumm 

Did you find any solution (without using syncthing)? I don't know why on earth joplin stores the attachements in `~/.config` folder instead of the sync folder itself.

**Comment by swdrumm** [comment]
Sort of...Attachments appear to work properly if I sync using WebDAV on my personal owncloud instance.  I need to do some php and owncloud upgrades though before I put it into production.  I never did get attachments to work properly with file system sync though.  ¯\_ (ツ)_/¯

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Nebucatnetzer** [comment]
It isn't working fully yet. At least on Android I get a permission error when I try to edit an attached file.


2 Dec 2019 03:11:27 Scott Drumm <notifications@github.com>:

> Sort of...Attachments appear to work properly if I sync using WebDAV on my personal owncloud instance. I need to do some php and owncloud upgrades though before I put it into production. I never did get attachments to work properly with file system sync though. ¯\_ (ツ)_/¯
> 
> Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.
> 
> ‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by laurent22** [comment]
Closed in favour of #279 279
