### ISSUE TITLE
Tag Android pre-releases as such

### ISSUE THREAD

**Issue by licaon-kter** [laurent22/joplin#10968]
### Operating system

Android

### Joplin version

-

### Current behaviour

current Github "pre-release" labels are not part of the source code hence F-Droid autoupdate will build and publish all versions

**Comment by licaon-kter** [comment]
ref: https://gitlab.com/fdroid/fdroiddata/-/issues/3353

**Comment by laurent22** [comment]
That's not how we do things and anyway I don't think I'd want the prerelease status to be part of the source code.

But F-droid can get that information by fetching the releases on the Joplin Android repository: https://github.com/laurent22/joplin-android/tags

**Comment by licaon-kter** [comment]
F-Droid uses the source code repo.

The other repo has, besides being dated 2020 for some reason, tags that point to commits that don't exist in the actual source code.

This workflow is confusing for humans, let alone scripts.

**Comment by laurent22** [comment]
I'm just saying how it's setup, now they can do whatever they want with this information. We are not going to restructure everything when there are already ways to get the required information
