### ISSUE TITLE
Joplin only shares Notes as texts 

### ISSUE THREAD

**Issue by bush911** [laurent22/joplin#10984]
### Operating system

Android

### Joplin version

3.0.8

### Current behaviour

1. Open a specific note.
2. Press 3-dot on top right.
3. Choose share 
4.  A window with title "sharing text" appears.
5. Now can be shared to other text editor, of course losing images in note.
6. No print option. Just copied Texts 

### Expected behaviour

Just like the Joplin for windows, I would like to share/ export a specific note to **PDF or HTML etc, not text-only format.**

**Comment by jm33-m0** [comment]
This is obviously not a bug, it's a feature request. People are abusing the bug report template here.

**Comment by bush911** [comment]
I'm sorry for any confusion. I'm not very familiar with coding and technical details, so I may have misunderstood the process. I hope my issue didn't cause any inconvenience to the developers.
> This is obviously not a bug, it's a feature request. People are abusing the bug report template here.
