### ISSUE TITLE
Please give the ability to share from another Android app into Joplin. 

### ISSUE THREAD

**Issue by dklawren** [laurent22/joplin#110]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [X] Android
- [ ] iOS

### Application

- [ ] Desktop
- [X] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*
Enhancement

*If there is an error, please copy and paste the full error message*
None

Please give the ability to share from another app into Joplin. 

Example: Sharing a web URL from inside a browser app by clicking the share icon and having Joplin included in the list of possible apps to send the URL to. Or selecting some text and having that text included in the new note.

Thanks
dklawren

**Comment by martinpengellyphillips** [comment]
https://github.com/alinz/react-native-share-extension might be useful.

**Comment by laurent22** [comment]
Maybe can be done using this: https://facebook.github.io/react-native/docs/linking.html

**Comment by Nebucatnetzer** [comment]
This seams to me more like a bug than a feature request.
Without this the app looses it's main purpose for me (quickly adding a note) and it's quite general behaviour for a todo/notes app.

**Comment by laurent22** [comment]
For info, current (non-working) branch: https://github.com/laurent22/joplin/tree/share

**Comment by CalebJohn** [comment]
What's the status on this fix? I'd like to try taking over this fix if you are not working on it and don't mind. I don't have an ios device so I would only really be implementing/testing for android devices.

**Comment by tessus** [comment]
@CalebJohn why don't you take a crack at it? @laurent22 hasn't commited anything to this branch since May 10th.

**Comment by jovandeginste** [comment]
@CalebJohn @laurent22 thanks for this!

**Comment by nr458h** [comment]
Thanks!

**Comment by elatre** [comment]
May I tell you a bug? I open an existing note (or a new note and write some text in it). Without closing the note I open the browser (Chrome in my case) and share some website with joplin. Oh dear!, the text of the initially note were replaced with the url and got lost. I am on Android 8.0.0

**Comment by CalebJohn** [comment]
Did you save the note before switching to chrome?

**Comment by CalebJohn** [comment]
Just to clarify, after you share the note from chrome, the title is the title from the old note, and the text is the shared url? And if you save again it will overwrite the old note?

**Comment by elatre** [comment]
Yes to both.
