### ISSUE TITLE
400 MB idle memory usage

### ISSUE THREAD

**Issue by lambdakilo** [laurent22/joplin#11013]
### Operating system

Windows

### Joplin version

3.0.15

### Desktop version info

Joplin 3.0.15 (prod, win32)

Client ID: 44a105c3e48447908ea3dee79c3453f9
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 598677b

Backup: 1.4.1

### Current behaviour

1. Close active Joplin window
2. Open up Task Manager
3. Joplin shows up using a bit over 440 MB of RAM usage

### Expected behaviour

Joplin should not be using half a gig of memory while not active and only running in background. I think.

### Logs

[log.txt](https://github.com/user-attachments/files/16934078/log.txt)
debugging enabled. start application. close application. uploaded logs.

**Comment by laurent22** [comment]
Is that a lot these days? I look at my processes and I see many of them that take more memory than Joplin - the Dropbox client (which I almost never use) takes 500 MB, VSCode takes nearly 2 GB, Thunderbird, 1GB, several Chrome tabs around 500 MB each, etc.

And I don't think memory usage means much these days. This is the memory space reserved by the app but how it will be allocated will depend on your own usage. I assume rarely used apps are swapped to disk, etc.

**Comment by lambdakilo** [comment]
Ah thanks for the reply! This might be normal behavior then especially for an Electron app.
