### ISSUE TITLE
Problem with the three lines that contain side options.

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#11028]
### Operating system

Android

### Joplin version

3.0.8

### Current behaviour

When I click on the three lines in the top corner of the app, the sidebar appears wrong and overlapping, and I tried changing the language and it did not solve the problem.

### Expected behaviour

When you press the three lines in the upper corner of the app, the sidebar is supposed to appear covering part of the screen, but the text appears incorrectly and follows the dragging motion when the menu appears to the right. And it does not appear at the beginning of the menu on the left.

### Logs

[mobile-log.log](https://github.com/user-attachments/files/16967497/mobile-log.log)

**Comment by laurent22** [comment]
Could you post a screenshot or video of what you mean?

**Comment by ghost** [comment]
Sure,![Screenshot_٢٠٢٤٠٩١٤_١٠٥٢٢٥_Joplin.jpg](https://github.com/user-attachments/assets/4dfb7b32-9d96-4765-8b62-7141dbeef623)

![Screenshot_٢٠٢٤٠٩١٤_١٠٥٢٣١_Joplin.jpg](https://github.com/user-attachments/assets/59e51a02-9fe0-473f-81ca-a764e1796079)

**Comment by laurent22** [comment]
Thanks for the screenshot. Unfortunately we don't yet support right to left languages (at least not properly).

**Comment by ghost** [comment]
It also happens when the language is english![Screenshot_٢٠٢٤٠٩١٤_١٧٥٨٠١_Joplin.jpg](https://github.com/user-attachments/assets/43d36294-d7f8-41af-8ab3-7dabc391034e)
