### ISSUE TITLE
Change tab order in note

### ISSUE THREAD

**Issue by jnslmk** [laurent22/joplin#1103]
### Operating system

- Windows
- macOS
- Linux

### Application
- Desktop

When creating a new Joplin focuses the note title. 
After entering the title of the new note, I would like to move to the note content field with the tab key. 
Before moving to the note content Joplin selects the different note edit buttons.

![test](https://user-images.githubusercontent.com/23459370/50742021-e8b7b200-1205-11e9-9f53-2a713c388453.gif)

My proposal is to change the tab order to *Note title* -> *Note content* -> *Buttons*.

Alternatively I think it would be possible to remove the buttons from being focusable by pressing tab altogether. 
Currently it is not possible to switch back to them using tab when editing and I doubt many users try to access the buttons using the tab key.

**Comment by foxmask** [comment]
If I remember well, it has already been suggested.

**Comment by jnslmk** [comment]
I did not find it when I searched for it. Can you link the issue? I'll close this one then

**Comment by foxmask** [comment]
I didn't find it . 😎

**Comment by tessus** [comment]
Has been fixed a while ago.
