### ISSUE TITLE
BUG: Checkbox UL (list) markdown parsing is broken. If a normal UL is below or above a Checkbox UL, BOTH are rendered erronously as a Checkbox UL. 

### ISSUE THREAD

**Issue by futuremotiondev** [laurent22/joplin#11059]
### Operating system

Windows

### Joplin version

3.1.8 (prod, win32)

### Desktop version info

Joplin 3.1.8 (prod, win32)

Client ID: 1bb78c52da5b4fe090823a3b13953af6
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 55faab2

Backup: 1.4.2
Csv Import: 1.0.1
Favorites: 1.3.2
Headings 4 to 6: 1.0.1
Insert Date: 1.0.1
Paste Special: 1.1.2
Table Formatter Plugin: 1.2.1

### Current behaviour

1. Create the following markup:

```markdown
## Lorem ipsum dolor sit amet

- Lorem ipsum dolor sit amet, consectetur adipiscing elit.
- Ut fringilla neque efficitur imperdiet luctus.
- Donec id magna ac nisi iaculis gravida sit amet non orci.
- Praesent semper massa vel elit dapibus mollis.
- Proin sit amet massa mollis, convallis ipsum et, vulputate metus.

- [ ] Lorem ipsum dolor sit amet, consectetur adipiscing elit.
- [ ] Ut fringilla neque efficitur imperdiet luctus.
- [ ] Donec id magna ac nisi iaculis gravida sit amet non orci.
- [ ] Praesent semper massa vel elit dapibus mollis.
- [ ] Proin sit amet massa mollis, convallis ipsum et, vulputate metus.
```

2. Switch to RTE mode.
3. Observe that both lists are rendered as checkbox lists:

![Joplin_LqBiyZdAy9](https://github.com/user-attachments/assets/13af0841-c244-4805-88bf-d709799f0dc1)

Also if inspected with devtools, you can see that Joplin is treating them both as a single checkbox list:

![Joplin_DZFnLuRDWf](https://github.com/user-attachments/assets/e1d296fd-d4ba-4ebf-b5f5-987d83b6bbd1)

### Expected behaviour

I expected Joplin to render the normal UL section with discs, and the checkbox UL section with check-boxes.

I have attached a zipped jex file that demonstrates the bug:

[Broken List Rendering.zip](https://github.com/user-attachments/files/17009523/Broken.List.Rendering.zip)

This is a fairly big rendering and parsing error, hopefully you can reproduce and fix. If you need any help with reproducing the bug I am here and will do my best.

**Comment by futuremotiondev** [comment]
Also, a followup. If you insert an `HR` between the lists like so:

```markdown
## Lorem ipsum dolor sit amet

- [ ] Lorem ipsum dolor sit amet, consectetur adipiscing elit.
- [ ] Ut fringilla neque efficitur imperdiet luctus.
- [ ] Donec id magna ac nisi iaculis gravida sit amet non orci.
- [ ] Praesent semper massa vel elit dapibus mollis.
- [ ] Proin sit amet massa mollis, convallis ipsum et, vulputate metus.

---

- Lorem ipsum dolor sit amet, consectetur adipiscing elit.
- Ut fringilla neque efficitur imperdiet luctus.
- Donec id magna ac nisi iaculis gravida sit amet non orci.
- Praesent semper massa vel elit dapibus mollis.
- Proin sit amet massa mollis, convallis ipsum et, vulputate metus.
```

It renders correctly:

![Joplin_azMZrcLs2Z](https://github.com/user-attachments/assets/873bd8cd-1a0a-47dc-a19e-6a536feae777)

**Comment by tomasz1986** [comment]
This is a known limitation of Joplin (see https://github.com/laurent22/joplin/issues/6423#issuecomment-1100917535).

**Comment by futuremotiondev** [comment]
Looks like nirzaf just submitted a PR fixing this... awesome! Hopefully it gets merged.
