### ISSUE TITLE
Fedora 40 installer fails distro moved to wget2 without `--show-progress` 

### ISSUE THREAD

**Issue by FloatingBoater** [laurent22/joplin#11054]
### Operating system

Linux

### Joplin version

3.0.15

### Desktop version info

Fedora 40
Linux 
```
wget2 --version
GNU Wget2 2.1.0 - multithreaded metalink/file/website downloader
```

### Current behaviour

1. The standard shell pipe to get the latest release (not the older packaged RPM) pulls a shell script:
  `wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash`
2. This fails with the error `Unknown option 'show-progress` presumably as Fedora 40 moved to `wget2`
3. Pulling the install script locally and editing it to remove `--show-progess` gives a workaround.

Details of the `wget2` change are here:
  https://fedoraproject.org/wiki/Changes/Wget2asWget

The `wget2` release notes suggest `--show-progress` has been renamed to `--force-progress`
  https://gitlab.com/gnuwget/wget2/-/wikis/Home#different-behavior-of-wget2

```
$ wget --show-progress
Unknown option 'show-progress'
$ wget2 --show-progress
Unknown option 'show-progress'
$ wget2 --force-progress
Nothing to do - goodbye
```

Fedora 40 is clearly bleeding-edge, but my guess is other *nix distros will start to see this issue as they also move across from `wget` to `wget2`.
The Fedora release note statement `The change should be mostly transparent to users.` is clearly a tad optimistic! :-)

### Expected behaviour

* Pull the latest  install script
* Upgrade Joplin

### Logs

`Joplin_install_and_update.sh` fails with the error `Unknown option 'show-progress'.

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

Be aware that `https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh` is a very old version of the install script (2-4 years out of date). See https://joplinapp.org/help/install/ for the up-to-date command (changes `master` → `dev`).

Based on a [code search](https://github.com/search?q=repo%3Alaurent22%2Fjoplin+%2Fmaster%5C%2FJoplin_install_and_update%2F&type=code), the out-of-date command does not seem to be present in the Joplin repo. As such, I'm closing this for now.

If the documentation still needs to be updated, please let me know and I can re-open the issue.
