### ISSUE TITLE
Desktop: Pressing ctrl-a in a notebook with 14500 notes freezes Joplin

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#11065]
### Operating system

Linux

### Joplin version

3.1.12

### Desktop version info

Joplin 3.1.12 (dev, linux)

Client ID: 5c73f3b671b445378a8caf85ee1d2935
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 9c80dcb3f (pr/desktop/faster-go-to-anything)

Backup: 1.4.2
Extra Markdown viewer settings: 0.3.0
Freehand Drawing: 2.11.0
Rich Markdown: 0.15.0

### Current behaviour

1. Create a notebook with 14000 notes.
    - Tested with 14519 notes.
2. Click on a note in the note list.
3. Press <kbd>ctrl</kbd>-<kbd>a</kbd>.
4. Try to interact with Joplin.

Currently, after 20-30s, the multi-note selection menu becomes visible. However, clicking on "Move to notebook" seems to do nothing for at least 30s (Joplin remains frozen).

### Expected behaviour

It should be possible to select a large number of notes on desktop.

**Comment by laurent22** [comment]
That's interesting. Selection should normally be virtual since we only create the note list elements that are currently visible.

**Comment by personalizedrefrigerator** [comment]
The issue seems to be `stateToWhenClauseContext` (as called by `makeContextMenu`):

![image: profiler screenshot](https://github.com/user-attachments/assets/f3fc41c6-d658-44c3-a6da-ca64de439952)

In particular, it seems to be this line:

https://github.com/laurent22/joplin/blob/e80bede7b7f1342f21c76def8976f756c6baf9a6/packages/lib/services/commands/stateToWhenClauseContext.ts#L57

The profiler lists it as consuming roughly 28s.
![image: Profiler screenshot](https://github.com/user-attachments/assets/f658d401-267b-4153-851b-812e83fd2b11)
