### ISSUE TITLE
Improving Markdown Directory Import

### ISSUE THREAD

**Issue by markbmullins** [laurent22/joplin#1108]
### Operating system

- Windows
- macOS
- Android

### Application

- Desktop
- Mobile

Handle relative links, for example:

README.md  
First.md    
[First Chapter}(./First.md}

**Comment by foxmask** [comment]
can you give us some details ?

**Comment by markbmullins** [comment]
Yep, I would like relative links to work just like web links. So if I have a notebook A and files B and C, in file B I could say

[Go see file C here!](./A/C)
