### ISSUE TITLE
Synchronisation on Android is supposed to happen every 5 minutes but does not

### ISSUE THREAD

**Issue by dejafait** [laurent22/joplin#11081]
### Operating system

Android

### Joplin version

3.0.8

### Current behaviour

Simplest steps to reproduce: use a new profile with the Welcome notebook. Sync it to any target (e.g. Dropbox). After the initial sync completes, leave the app open as shown in screenshot. 

Current behavior: the app never syncs again unless the user interacts to manually trigger it. Screenshot proves it (last sync happened at 11:51 but it's now 12:00).
![Screenshot_20240919-120017](https://github.com/user-attachments/assets/c31872a3-5be9-4f3a-8cdd-4a514b17b874)

### Expected behaviour

It should sync every 5 minutes even without user interaction as long as the app stays open as shown in the screenshot.

### Why it matters

Users have to keep "babysitting" (got that term from another user) the sync on all their android devices. It's been my case for one year. Really wish android sync would be more seamless thus here I am reporting the issue narrowed down to its simplest form.

**Comment by laurent22** [comment]
It is designed this way - if you interact with the app and more than 5 minutes have passed it will sync. But it's true that if you just leave it open without touching it, it won't happen. I guess we're making the assumption that the user actually interacts with the app when it's opened, which in most cases is a correct assumption on mobile.

**Comment by dejafait** [comment]
I keep Joplin open on several android devices and keep switching between them. Everytime I switch to a different device, I have to worry about syncing recent changes and waste 5-10sec (Joplin Cloud, E2EE, 10k notes), waiting for the triggered sync to complete. It happens maybe 50+ times a day (I use Joplin a lot, it is a central tool in my life). I'm sorry to insist.

Waiting a few seconds 50+ times a day is a bummer, when this sync could just proactively happen every 5 minutes, like the Interface claims it is, but is not.

As a side note, I will soon migrate from Joplin Cloud to my own Joplin Server Docker. I already tested it with my 10k notes, syncs 2-3x faster, because LAN and no more E2EE needed I guess. 

This will alleviate the present issue but even there imho it would still make sense to offer an option to sync even when the user does not interact.

Afair Evernote still syncs (every N minutes) when there is no interaction. Also Todoist (instantly). Also Google Docs (instantly). This is the first time I encounter this unexpected degraded syncing pattern.

If the user has an app, any app with some sync, open on two devices, once the user makes a change on device A, the change should eventually propagate to device B without any user interaction. It may take a few minutes but it eventually happens. Imho.

**Comment by dejafait** [comment]
> we're making the assumption that the user actually interacts with the app when it's opened, which in most cases is a correct assumption on mobile.

Then why not have the same logic on desktop and mobile ? Current behavior on desktop is automatic syncing every 5 minutes even without user interaction. Why punish mobile users vs desktop users? I don't understand.

**Comment by laurent22** [comment]
> Then why not have the same logic on desktop and mobile ? Current behavior on desktop is automatic syncing every 5 minutes even without user interaction. Why punish mobile users vs desktop users? I don't understand.

Originally this is because long running timers with the framework we're using are not reliable, so we have this technique that is based on user interactions and that assumption that if the app is open it's to be used.

I don't really understand your use case though - you mean that your phone is on all the time with the app opened, but you don't use your phone? Also normally when you open the app, it should sync too, it shouldn't wait 5 minutes.

**Comment by dejafait** [comment]
I mostly use Joplin on several (2-4) eink android tablets permanently open on my desk. I multitask between them. Let's say I completed some tasks and joplin changes on device A an hour ago. I switch to device B which already had Joplin open (usually 1-3 of my tablets have Joplin open). I always have to worry about syncing first, even if changes happened one hour ago. This is why I have developed the habit of not trusting Joplin sync and having to babysit it. I don't have this issue with any other app (Evernote, Todoist, gmail, Google doc, any app with user data sync).

Yes when I open the app it syncs. When I edit a note it syncs. When I interact it syncs.

**Comment by laurent22** [comment]
That makes sense. This workaround with interaction-based timers was implemented years ago and maybe today the framework timers are more reliable so it would be good to revisit

**Comment by dejafait** [comment]
Fyi this is still an issue as of 3.1.4.

Both my tablet and my smartphone run 3.1.4. I edited a note on my tablet at home one hour ago. I am now in the subway with only my smartphone. Bad surprise, my latest changes made at home are only partially synced. I am now editing the note on my smartphone knowing there will be an annoying conflict to manually solve when I come back home.

**Comment by dhwalker** [comment]
I hope a revisiting will include background sync'ing even when the Android app is not "open." I have a couple of use cases: 1) I take a photo of a receipt as an attachment in Joplin note. After taking the photo, I open another app. When I use my laptop next, I'd like the receipt image to be there, even if I haven't reopened Joplin on my phone. 2) I create a note on my laptop with materials for an upcoming meeting (perhaps including sizable attachments), then I go to the meeting with my phone. I would really like the note and its attachments to be on my phone when I arrive at the meeting.

**Comment by laurent22** [comment]
> I hope a revisiting will include background sync'ing even when the Android app is not "open."

For the record background sync is not a simple problem to solve. The comment reminds me of this xkcd:

![image](https://github.com/user-attachments/assets/0ba1086c-4cb6-4cb1-a41e-f869e42896a4)

**Comment by dejafait** [comment]
@laurent22 I just realized background sync now works on mobile, using 3.2.7. I had not realized till today. Even if I'm late to the party I want to say a very big thank you, this a major improvement for quality of life.

**Comment by mrjo118** [comment]
> [@laurent22](https://github.com/laurent22) I just realized background sync now works on mobile, using 3.2.7. I had not realized till today. Even if I'm late to the party I want to say a very big thank you, this a major improvement for quality of life.

When you say 'background sync', do you just mean automatic sync after x amount of time, or do you also mean that if I switch to another app or put the phone on sleep, then it will continue to sync?

**Comment by mrjo118** [comment]
I did some tests on 3.2.7 using an old phone. The background sync does indeed work to a point.

If you switch to another app, the synchronization will continue, but only for the current batch. When downloading changes, it will download objects in batches of 50. So if you switch app, it will complete the current batch in the background, but will be unable to start the next batch until Joplin is restored to the foreground.
If you put the phone to sleep, regardless of whether Joplin is in the foreground or background, the synchronization will halt.

So you couldn't complete an initial sync of your profile while doing other things on your phone or with the screen off, but for the most part, as long as you're connected to the internet, unless you make a change which changes a lot of sync objects in a very small space of time, changes will be synced in real time even if you switch between apps, providing you don't put the phone to sleep within a few seconds of making changes. So this is indeed a significant quality of life improvement. Kudos to you @laurent22 :)

EDIT: Ah ok, looks like that behaviour was already like that before this change. The issue the current behaviour presents when switching apps is that if the sync did not yet auto trigger before switching, then the sync will not start until switching back to Joplin. Nonetheless getting the sync on interval working on mobile is a win

**Comment by dejafait** [comment]
It works perfectly for my use case, which is that when I leave my Joplin app open on several devices, I am now confident they will all eventually sync both to and from sync target and all get in sync within 5-10 minutes. I hope this answers your question @mrjo118
