### ISSUE TITLE
Cannot move note and plugins broken after using note links

### ISSUE THREAD

**Issue by dejafait** [laurent22/joplin#11108]
### Operating system

Android

### Joplin version

3.0.8

### Current behaviour

Steps to reproduce.

Create note A in notebook NA, B in NB and C in NC.
Create a link from A to B and from B to C.
Open NA, click A to open, click link to B, click link to C.
The menu at the top of the screen is now blocked (the drop-down to move to a different notebook) thus I cannot move note C to a different notebook. Also, simultaneously and likely relatedly, plugins seem temporarily broken e.g. backlinks don't show up.
Everything goes back to normal as soon as I leave note C.

### Expected behaviour

Top menu and plugins should work the same no matter on which note I am.

### Notes

The bug doesn't happen if B and C are in the same notebook.

### Why it matters

It punishes users who use note links a lot and/or wikify their notes.

**Comment by personalizedrefrigerator** [comment]
This might be fixed (possibly by https://github.com/laurent22/joplin/pull/10750) &mdash; I haven't been able to reproduce this in a web build of the mobile app, built from a recent commit (b97a14c).
