### ISSUE TITLE
Changes made via the `editor.setText` command are not saved

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#11105]
### Operating system

Windows

### Joplin version

3.1

### Current behaviour

- Using a plugin, call the `setText` command and set the body of the current note, using `await joplin.commands.execute('editor.setText', 'something');`
- The change appears in the note
- Open the configuration screen
- Go back to the note

=> The changes have not been saved.

**Comment by personalizedrefrigerator** [comment]
It looks like `editor.setText` calls `setFormNote`:

https://github.com/laurent22/joplin/blob/85c2eb43ddad918878d7f3838ed2da6aac049d49/packages/app-desktop/gui/NoteEditor/utils/useWindowCommandHandler.ts#L56-L59

Based on `onFieldChange`, it might also be necessary to [set hasChanged to `true`](https://github.com/laurent22/joplin/blob/85c2eb43ddad918878d7f3838ed2da6aac049d49/packages/app-desktop/gui/NoteEditor/NoteEditor.tsx#L210) and call `scheduleSaveNote`:

https://github.com/laurent22/joplin/blob/85c2eb43ddad918878d7f3838ed2da6aac049d49/packages/app-desktop/gui/NoteEditor/NoteEditor.tsx#L207-L211

**Comment by laurent22** [comment]
I was wondering why ChatGPT was telling me to call both `joplin.data.put` and `editor.setText` but it looks like it was the right advice. Maybe it's common knowledge that `editor.setText` is somewhat broken and that's been picked up by ChatGPT

* * *

<img width="715" alt="image" src="https://github.com/user-attachments/assets/c597e217-0e02-4ffb-933a-526f0e3e0355">
