### ISSUE TITLE
Note becomes Untitled till notebook is left and reopened 

### ISSUE THREAD

**Issue by dejafait** [laurent22/joplin#11109]
### Operating system

Android

### Joplin version

3.0.8

### Current behaviour

Steps to reproduce.

Create note A in notebook NA and B in NB.
Create a link from A to B.
Open NA, open A, click to B, move B to NA using top menu, click back button.
You are now back in NA and you should see A and B.
Instead you see A and Untitled.
Everything goes back to normal after you leave and reopen NA.

### Expected behaviour

You should always see the correct note titles.

**Comment by dejafait** [comment]
I saw you added the desktop label so I assume bug affects desktop as well.
However please note that this bug report is initially about mobile. Maybe add mobile label as well?

**Comment by personalizedrefrigerator** [comment]
I can reproduce this with a recent web build of the mobile app (v3.1.x, built from b97a14c).

**Comment by dejafait** [comment]
Fyi this bug still happens with 3.1.4.

**Comment by personalizedrefrigerator** [comment]
I can no longer reproduce this in a web build of the mobile app (v3.2.x, built from 2399e56).

**Comment by personalizedrefrigerator** [comment]
I'm closing this as complete! If you can still reproduce the issue, please let me know and I can re-open this.
