### ISSUE TITLE
Plugin template: Scripts bundled with `extraScripts` cause "ReferenceError: exports is not defined" in some situations

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#11106]
### Operating system

Linux

### Joplin version

3.1.15

### Desktop version info

Joplin 3.1.15 (prod, linux)

Client ID: c13c7d68206342d0be14de538812a561
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: e5771a3

Backup: 1.4.2
Extra Markdown viewer settings: 0.4.0

### Current behaviour

To reproduce:

1. Add a plugin that either:
    - Creates a dialog/panel script built with `extraScripts`.
    - Adds a Markdown viewer asset built with `extraScripts`.
2. If the plugin includes a WebView script, open the WebView. If it adds a Markdown viewer asset, open the Markdown viewer.
3. Check Joplin's development tools.

### Expected behaviour

No error should be logged to the console.

## Past attempts at fixing this

https://github.com/laurent22/joplin/commit/c197a83de8ad6081872e8f42484a6acbc62febd5:
- Defines `exports`
- [Reverted here](https://github.com/personalizedrefrigerator/joplin/commit/8d74d527c24f544cf9eb7be214656031bbf2bd1a) &mdash; it broke the Function Plot plugin, which uses a library that behaves differently when `exports` is defined.

**Setting `target: 'web'` and changing [libraryTarget](https://github.com/laurent22/joplin/blob/85c2eb43ddad918878d7f3838ed2da6aac049d49/packages/generator-joplin/generators/app/templates/webpack.config.js#L298C4-L298C17) to `var` or `global` in [webpack.config.js](https://github.com/laurent22/joplin/blob/85c2eb43ddad918878d7f3838ed2da6aac049d49/packages/generator-joplin/generators/app/templates/webpack.config.js#L250)**:
- Just setting `target: 'web'` is insufficient.
- This breaks renderer/editor content scripts, which define an `exports` variable and expect it to be modified.

### Logs

```
viewer.js:720 Uncaught ReferenceError: exports is not defined
    at viewer.js:720:11
    at viewer.js:722:12
```

**Comment by laurent22** [comment]
> Just setting target: 'web' is insufficient.

Would that fix at least certain plugins (without breaking new plugins)? I've set that up for a plugin and it did help getting rid of the error without any negative effect as far as I can see
