### ISSUE TITLE
Create the iOS 18 Dark icon

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#11119]
Ref: https://discourse.joplinapp.org/t/ios-18-enhancement-request-dark-icon/40330

Based on the provided Apple documentation, I guess it would be a black/dark grey icon with a blue "J" letter. Need to check if React Native supports this too.

**Comment by itzTheMeow** [comment]
Id like to do this, is there a generator script for the icons or should I just make them myself? I can't seem to find one.

**Comment by laurent22** [comment]
Yes the icons are generated from this script: https://github.com/laurent22/joplin/blob/dev/packages/tools/generate-images.ts
