### ISSUE TITLE
[Feature Request] Tag by dropdown list

### ISSUE THREAD

**Issue by christianlupus** [laurent22/joplin#1111]
### Operating system

- Windows
- macOS
- Linux
- Android (?)
- iOS (?)

### Application

- Desktop
- Mobile (?)

At the moment the tags in the desktop app are typed as a comma separated string. This is ok, if you only manage a handful of tags. On the other hand, if it gets more and more, it would be nice, if the app could help you: I would like to have a dropdown menu that allows to quickly add/remove single tags to a note.

There are some similar tags:

- #471 would allow to insert tag names faster rendering this request partly obsolete
- #359 is simplified by this request I think as the batch operation can be done much more easy (from the view of the GUI programming) than handling all the strings individually in the current variant.

**Comment by christianlupus** [comment]
The PR #1206 was merged but reverted afterwards. So closing this issue here was ok at the time (PR was merged) but now no longer is fixed.

**Comment by christianlupus** [comment]
@laurent22 I cannot reopen the issue (missing right probably). Can you do this please. I hoped it would get reopened as soon as I add a comment to it.

**Comment by kaumpail** [comment]
Same here. This future would be really nice for the Desktop client
