### ISSUE TITLE
Notes that start with emoji in title cannot be exported as Markdown

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#11110]
> Sure, create a note and call it 💾 example. Then right-click on the note, select "Export" > "MD - Markdown," and choose a folder to export to. The target folder will be empty. Although two folders, "_resources" and "ALL," will be created, they won't contain any "md" files. Now, do the same process but remove the emoji from the note's title; the export will be done correctly, and the note will be exported as expected.

Ref: https://discourse.joplinapp.org/t/emoji-in-note-titles-prevent-export-without-warning/40286/3

**Comment by personalizedrefrigerator** [comment]
This works on Fedora Linux (Joplin 3.1.15). I'm re-tagging this with `windows`.

**Comment by kirtish16** [comment]
I don't see this issue with new version 3.1.20 on Windows. 
I was able to save with any emoji on export it as Markdown.

**Comment by viazure** [comment]
> I don't see this issue with new version 3.1.20 on Windows. I was able to save with any emoji on export it as Markdown.

It did, I guess it should be fixed in the new version.

**Comment by thejaz** [comment]
yes, it's resolved! thanks!
