### ISSUE TITLE
Note becomes Untitled after being moved from a search

### ISSUE THREAD

**Issue by dejafait** [laurent22/joplin#11123]
### Operating system

Android

### Joplin version

3.0.8

### Current behaviour

Create note A in notebook NA and note B in notebook NB.
Open NA, start a search matching B, open B, move it to NA, go back two times.
You should now be back in NA and see A and B. Instead you see A and Untitled.

### Expected behaviour

You should always see the correct title of any note.

**Comment by personalizedrefrigerator** [comment]
This seems to be fixed &mdash; I can no longer reproduce the issue in the web app (built from 2399e56). I've also tested on iOS with Joplin 13.2.2.

**Comment by personalizedrefrigerator** [comment]
I'm closing this as complete! If you can still reproduce the issue, please let me know and I can re-open this.
