### ISSUE TITLE
Sync doesn't work with target directory on different partition

### ISSUE THREAD

**Issue by jfacemyer** [laurent22/joplin#11120]
### Operating system

Linux

### Joplin version

3.0.15

### Desktop version info

Joplin 3.0.15 (prod, linux)

Client ID: f7637bf5bafb4423843a69910d0e61ef
Sync Version: 3
Profile Version: 47
Keychain Supported: No

### Current behaviour

1. Set Joplin to sync to directory on different partition than home (same drive, same FS type, mounted with user read/write permissions)
2. Sync.
3. Joplin says sync happens, but no files are synced. It acts as if it works every time, stating the correct number of files synced, etc. No files are synced.
4. Set sync target to different directory on same partition; same effect.
5. Set sync target to a directory in the home drive; sync works.

### Expected behaviour

Sync should work on any target directory that the user has permissions to read/write.

Incidentally, when importing and exporting, I can import from the exact same target directories I'm having problems syncing to.

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

How was Joplin installed (e.g. official installation script, Snap, Flatpak)?

**Comment by jfacemyer** [comment]
Flatpack - installed thorugh Manjaro's pamac.

Had the same issue when I was using Ubuntu and the Flathub repo.

**Comment by personalizedrefrigerator** [comment]
The Flatpak's README seems to [have a section related to this issue](https://github.com/flathub/net.cozic.joplin_desktop?tab=readme-ov-file#file-system-sync-on-removable-media).

(Be aware that the Flatpak distribution is unofficial (community-maintained).)

**Comment by jfacemyer** [comment]
Ah! thank you.

**Comment by jfacemyer** [comment]
Yes, I switched to a different package and it works as expected. Thanks!
