### ISSUE TITLE
Text Rendering Issue in Note Editor: Overlapping and Unreadable Content

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#11132]
### Operating system

Windows

### Joplin version

3.1.17 (prod, win32)

### Desktop version info

In the Joplin note editor, there appears to be a text rendering bug causing overlapping and unreadable content. The screenshot shows the title "GENERAL HEALT" with text underneath that is overlapping and illegible. This issue seems to affect the readability and usability of the note editor interface.

## Steps to reproduce:
- Open Joplin
- Create or edit a note
- Observe the text rendering in the editor

### Current behaviour

![image](https://github.com/user-attachments/assets/2fe5d564-dc62-4267-93cb-b84fc881eb1b)

- Text is overlapping and unreadable, making it difficult to view or edit note content.
Additional information:
- The issue appears to affect both the note title and body text
- The editor toolbar is visible and seems unaffected by this rendering problem
- This bug report highlights the visual glitch while providing context for the Joplin developers to investigate and address the issue.

### Expected behaviour

- Text should be clearly rendered without overlap, allowing for easy reading and editing.

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

It's working for me with Joplin 3.1.17 on a Windows 11 virtual machine (no GPU):
![screenshot of Joplin](https://github.com/user-attachments/assets/6ab3af40-b776-4c11-b53b-990bb4b5e3ca)


For comparison, I'm posting Joplin's version information:

<details><summary>Version info</summary>

```
Joplin 3.1.17 (prod, win32)

Client ID: 2867e4ffc08c462ba70fc0cc546443c2
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 3ea403d

Backup: 1.4.2
```

</details>

Follow-up questions:
- Is this on Windows 10 or Windows 11?
- Does this happen with Joplin versions before 3.1.17? (E.g. 3.0.15? 3.1.15?)
- Does this also apply to the toolbar ("File", "Edit", ...)?
  - If not, does enabling safe mode help? (Help > Toggle safe mode).

**Comment by mrjo118** [comment]
The screenshot is very blurry, so I can't quite make out what exactly is overlapping. Also it would help to provide what the title and body is supposed to say, or a comparison screenshot of a working version, if you do have a working version to compare to.

**Comment by ghost** [comment]
Hi @mrjo118, the issue is exacly the blurry screenshot, here is another after restarting the app:

![image](https://github.com/user-attachments/assets/ead5b315-92a7-4d49-89e1-a269c78d436d)

As you can see, it seems something when I pass the mouse over the text over some region.

And after rolling mouse over the window for sometime it turn this:
![image](https://github.com/user-attachments/assets/b00ea99e-c545-46e5-bfbd-ffe710f492e3)


The env is:
- OS Name: Microsoft Windows 11 Pro
- OS Version: 10.0.22635 N/A Build 22635
- System Type: x64-based PC
- BIOS Version: American Megatrends Inc. 1208, 21/07/2020

![image](https://github.com/user-attachments/assets/31bad90a-9100-458f-aad9-0b07e582a19a)

**Comment by telecomunicacoes** [comment]
To anyone interested: disable "Antialiasing - FXAA" on NVIDIA and restart to fix this.

**Comment by ghost** [comment]
To anyone with this issue, disable `Antialiasing - FXAA` and restart to fix this.
