### ISSUE TITLE
Beta editor deletes numbers when editing lists

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#11135]
### Operating system

Windows

### Joplin version

3.0

### Current behaviour

- Create a note with this content:

```
10.100.128.200 Example 1
128.13.145.129 Example 2
```

- Select the whole text
- Click on the "Bulleted list" button

=> The first digit of the IP addresses is removed and a "dash" is added

### Expected behaviour

It should not remove the first digits

This has caused me to corrupt a large number of IPs and it's not obvious to notice it's doing this.

**Comment by dejafait** [comment]
Thanks for reporting this issue, I experienced it too.
