### ISSUE TITLE
When I go from note A to note B I briefly see an unrelated screen (note list)

### ISSUE THREAD

**Issue by dejafait** [laurent22/joplin#11155]
### Operating system

Android

### Joplin version

3.0.8

### Current behaviour

Steps to reproduce: create note A with a link to note B. Open A, click link to B.

Why it matters: if you use note links a lot e.g. wikifying your Joplin notes, you see that unrelated screen 100+ times a day.

### Expected behaviour

I should see only A then B and nothing else.

**Comment by personalizedrefrigerator** [comment]
This should be fixed by https://github.com/laurent22/joplin/pull/10750, which is currently in pre-release.

**Comment by laurent22** [comment]
Yes i cannot replicate on pre releases so it seems to be fixed
