### ISSUE TITLE
Tags starting with upper case special characters are not imported properly

### ISSUE THREAD

**Issue by marph91** [laurent22/joplin#11179]
### Operating system

Linux

### Joplin version

3.1.17

### Current behaviour

Unzip and import the following folder with the "MD + Front Matter (Directory)" import. It contains two empty notes with tag `Ökonomie`.

[example_tag_umlaut.zip](https://github.com/user-attachments/files/17265549/example_tag_umlaut.zip)

Result: The tag `ökonomie` is created and assigned to the first note. The second note gets imported, but without tag. Instead, there is an error message and the import stops:

![grafik](https://github.com/user-attachments/assets/ed3c7942-7fbb-4ab1-bb09-b548044f93d0)

References:

- https://github.com/marph91/jimmy/issues/6#issuecomment-2184981456
  - `Điện` doesn't work
  - `điện` works
  - `Dien` works
- https://discourse.joplinapp.org/t/jimmy-a-joplin-import-tool/38503/13
  - `Ökonomie` doesn't work
  - `ökonomie` works
  - `Oekonomie` works

### Expected behaviour

Import both notes including tags.

**Comment by JackGruber** [comment]
Possible the same problem with the SQLite function `LOWER` as in https://github.com/laurent22/joplin/issues/5102

**Comment by richardsprague** [comment]
when I import the enclosed file with a single tag, joplin explodes the tag into multiple tags of one letter each. Oddly, it imports correctly when the imported note contains more than one tag.  
[Notes 241019 Saturday.md](https://github.com/user-attachments/files/17445796/Notes.241019.Saturday.md)

**Comment by marph91** [comment]
> when I import the enclosed file with a single tag, joplin explodes the tag into multiple tags of one letter each. Oddly, it imports correctly when the imported note contains more than one tag.

The `tags` field [expects a list](https://joplinapp.org/help/dev/spec/interop_with_frontmatter/#supported-metadata-fields). I guess if you specify a single tag only, it's handled as a list of characters (each a separate tag). Imo. this is expected behavior and not related to the original issue.

NB: I didn't try, but

```
tags: [notes]
```

or

```
tags:
  - notes
```

should work in your case.

**Comment by pedr** [comment]
It seems like this is limitation of sqlite, we can't have a "case insensitive" search for all Unicode characters without adding a extension to SQLite.

I found that this extension could be used:
https://github.com/nalgeon/sqlean/blob/main/docs/text.md

In the image text_lower is the function added by the extension.
![image](https://github.com/user-attachments/assets/82e73fda-9a8e-4623-a007-82b85abe6a78)
