### ISSUE TITLE
[Feature Request] Autosaving for the terminal application

### ISSUE THREAD

**Issue by leveled** [laurent22/joplin#1118]
### Operating system

- Windows
- macOS
- Linux

### Application

- Terminal

I'm not sure if this is specific to certain editors, or it is feasible to implement such a feature, but I would find it highly useful if Joplin had an autosave feature on notes edited via the terminal. There has been a few times where I have had long running notes in the terminal editor lost because although I had been 'saving' them via vim, they were not technically saved in Joplin's DB, and so logging out or losing power has resulted in me losing those notes. I should probably be less careless, but it would be nice if there was a feature which protected against careless people like me.

**Comment by laurent22** [comment]
I guess we should use the same script as in the desktop app, since it watches the file and save in the background. I'll check if it can be integrated.
