### ISSUE TITLE
Missing stable docker tags in docker hub

### ISSUE THREAD

**Issue by ahayzen** [laurent22/joplin#11180]
### Operating system

Linux

### Joplin version

3

### Current behaviour

On docker hub currently there is 
| Tag | Digest |
|---|---|
| latest | 52af57880c0e |
| 3.0.1-beta | 52af57880c0e |
| 3.0-beta | 52af57880c0e | 
| 3-beta | 52af57880c0e |
|beta | 52af57880c0e |
|2.14.2-beta | b87564ef34e9 |
| 2.14-beta | b87564ef34e9 |
| 2-beta | b87564ef34e9 |

### Expected behaviour

Why is `latest` pointing to the beta tag ?
Where is the `3.0.15` tag for the latest stable release in https://github.com/laurent22/joplin/releases ?
The latest stable tag I can find is `2.5.1` ?

https://hub.docker.com/r/joplin/server states that there should be stable tags and latest should also track this but this doesn't seem to be the case, am I missing something obvious?

**Comment by andypiper** [comment]
This is very confusing. My container manager shows an available update, even after I updated to the latest version on Docker hub (taking me from 2.14.2 to 3.0.1).

**Comment by kiteloopdesign** [comment]
Some info from the forum on this:
https://discourse.joplinapp.org/t/simple-instructions-for-joplin-server-upgrade/18343/20

**Comment by kiteloopdesign** [comment]
> Where is the 3.0.15 tag for the latest stable release in https://github.com/laurent22/joplin/releases ?

I think those are not server releases. For server releases I found this:

https://joplinapp.org/help/about/changelog/server

**Comment by ahayzen** [comment]
Then I guess the question becomes where is the 3.0.1 tag? There is a beta version, but https://joplinapp.org/help/about/changelog/server suggests there should be a 3.0.1 stable tag?

Or maybe all of server is considered "beta"? 🤔
