### ISSUE TITLE
AppImage icon is broken in basic setup

### ISSUE THREAD

**Issue by zach-delong** [laurent22/joplin#11214]
### Operating system

Linux

### Joplin version

3.0.15

### Desktop version info

Joplin 3.0.15 (prod, linux)

Client ID: 64c113d6fca244a28e7ddd65fb041570
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 598677b

Backup: 1.4.1

Extra information about my system to help debugging: 
![Screenshot from 2024-10-15 15-08-40](https://github.com/user-attachments/assets/f6cf4e91-521b-49ae-8bb2-841e966f2b78)

### Current behaviour

- I "installed" the Joplin AppImage linked [here](https://joplinapp.org/help/install/) 
![Screenshot from 2024-10-15 15-03-25](https://github.com/user-attachments/assets/60ca1e77-f579-4992-a771-e7b0fcfc919c)
- I allows AppImageLauncher to "integrate" the app and set up the icon for it. 
- In my dock, I see an error icon 
![Screenshot from 2024-10-15 15-04-51](https://github.com/user-attachments/assets/37ceff0b-ed0d-42d6-ba60-ddfd40eb19b2)
- If I navigate to the AppImage in `/home/me/Applications` the AppImage doesn't have an icon 
![Screenshot from 2024-10-15 15-05-53](https://github.com/user-attachments/assets/bda60011-86e5-4d99-9e6f-2140df356a56)
- If I alt+enter to see properties I do see an icon correctly, so it's definitely in there somewhere 
![Screenshot from 2024-10-15 15-06-38](https://github.com/user-attachments/assets/b7833c85-de28-427a-9069-6b1d85cd2407)

### Expected behaviour

I expect the icons to appear everywhere and not just in the AppImage's properties.

### Logs

I don't think there are any logs relating to this, though I'll follow any instructions to grab anything.

**Comment by zach-delong** [comment]
Update: I reinstalled using the suggested script and I still have the same broken icon on my dock. :thinking:

**Comment by isshin1** [comment]
problem is that its app_id has '/' character in its name, appid is whats used to pick icon for a window, and it is causing issues

**Comment by zach-delong** [comment]
I did some more debugging and noticed that my desktop (also running Fedora 40) doesn't have this issue, so I kept digging in. I have the icon at `~/.local/share/icons/hicolor/512x512/apps/joplin.png` and in my desktop icon file I have

```
[Desktop Entry]
Encoding=UTF-8
Name=Joplin
Comment=Joplin for Desktop
Exec=env APPIMAGELAUNCHER_DISABLE=TRUE "/home/zachery/.joplin/Joplin.AppImage"  %u
Icon=joplin
StartupWMClass=Joplin
Type=Application
Categories=Office;
MimeType=x-scheme-handler/joplin;
X-GNOME-SingleWindow=true // should be removed eventually as it was upstream to be an XDG specification
SingleMainWindow=true
```

So the icon and the image appear to exist in the right places, but I'm not sure why they aren't connecting yet. 

> problem is that its app_id has '/' character in its name, appid is whats used to pick icon for a window, and it is causing issues

I would expect this is probably why the appimage itself doesn't have the right icon, but the "installer script" that I fell back to when the appimage didn't behave as expected _seems_ to my untrained eye to account for this by setting up its own .desktop file that manually specifies.

**Comment by isshin1** [comment]
gnome uses startup-wm class to find icon i think, hence its correct in fedora, but other wms, specially wlroots, they use app_id only, hence the issue in them

**Comment by zach-delong** [comment]
> hence its correct in fedora

Both of my computers are Fedora, but  one of them (my laptop) is showing the broken icon, which is strange.  I was just using my laptop as normal and installed something (wine) and the icon magically fixed itself. I am not sure why the icon would just fix itself during install but not during reboot, but apparently something got shaken loose...

**Comment by zach-delong** [comment]
I have tried to reproduce this again and haven't been able to. I think the issue is either resolved by a recent patch or it's harder to reproduce than I realized. Either way, good to go for now.
