### ISSUE TITLE
ERROR: Cannot read properties of undefined (reading 'body')

### ISSUE THREAD

**Issue by DevLenn** [laurent22/joplin#11225]
### Operating system

Windows

### Joplin version

3.0.15

### Desktop version info

Joplin 3.0.15 (prod, win32)

Client-ID: 5bb2083e853b4ec49842c890bb1c467b
Sync-Version: 3
Profil-Version: 47
Unterstützter Schlüsselbund: Ja

Revision: 598677b

Backup: 1.4.1

### Current behaviour

Error:
![image](https://github.com/user-attachments/assets/22f4374f-4b28-40e2-ab3d-cbc9149b00fc)

What i was trying to do:
![image](https://github.com/user-attachments/assets/09fcbe57-43d3-4280-b386-58ae0af1ab73)

### Expected behaviour

export full backup as RAW joplin export directory
--> error message not clear about the note the issue is due to

**Comment by laurent22** [comment]
Any additional errors in the console?

**Comment by DevLenn** [comment]
@laurent22 nope. neither in the console, nor in the logs

**Comment by laurent22** [comment]
Any chance you could share a minimal example that replicates the issue?

**Comment by mrjo118** [comment]
Not entirely sure from the screenshots but I think the window theme suggests it's Windows 11? I wonder if it could be related to the 24H2 update which has caused issues such as https://github.com/laurent22/joplin/issues/11199

Also I'm not sure why the text and colours look really weird on the screenshots. Is that some sort of accessibility setting on Windows or is it a bug that everything looks like that?

On a side note, I think it could be helpful for the issue template in GitHub to have a field to enter the version of the operating system you are using, especially for mobile

**Comment by DevLenn** [comment]
> Any chance you could share a minimal example that replicates the issue?

@laurent22 not really. started taking notes about a year back and now i can't export them... The only "how to reproduce" szenario i can give you is:
1. export
2. export everything
3. RAW - Joplin export directory

I only need to know which note the problem is due to, so i can fix it, is there any way to find out? i really don't want to look note by note if theres a corrupted "thing" in the body. The error occurred from one day to another...





> Not entirely sure from the screenshots but I think the window theme suggests it's Windows 11? I wonder if it could be related to the 24H2 update which has caused issues such as #11199
> 
> Also I'm not sure why the text and colours look really weird on the screenshots. Is that some sort of accessibility setting on Windows or is it a bug that everything looks like that?
> 
> On a side note, I think it could be helpful for the issue template in GitHub to have a field to enter the version of the operating system you are using, especially for mobile

@mrjo118 Nope windows 10, latest version. Error doesn't seem to be realted to any kind of windows update. At least it wasn't like the error occurred the day after an updaten.

**Comment by mrjo118** [comment]
On the note list you can select a note and then hold the shift key and click another note to select a range of notes. You can then click the export button to export only the selected notes.

You can try selecting a large group of notes and keep selecting different groups until you hit the error on export. Then narrow down the selection within that group until you can narrow it down to a single note

**Comment by DevLenn** [comment]
@mrjo118 yup, thank you.
i'll try later and will update what's wrong with the note the error is due to . 

_Update (21/10/24 12:40pm):_ please leave this issue open, i'll come back to this issue as soon as i've testet. could take a while. will give my best to do it in under one week.

**Comment by DevLenn** [comment]
randomly started working. idk why.
oh and btw, the sync to webdav is great
