### ISSUE TITLE
Killing the root parent pid of Joplin desktop could somehow cause the gnome desktop environment to crash

### ISSUE THREAD

**Issue by photonxp** [laurent22/joplin#1122]
### Operating system

- Linux (Ubuntu 16)

### Application

- Desktop

### Report Type
- Bug

#### Steps to reproduce:
Basically killing the parent pid of Joplin.AppImage would make it happen.

$ ps -el| grep oplin

> 0 S  1000 **21946** **21197**  0  80   0 - 341346 poll_s ?       00:00:00 **joplin**
> 1 S  1000 **21951** **21197**  1  80   0 -  5414 fuse_d ?        00:00:01 **Joplin.AppImage**
> 0 S  1000 21967 21946  0  80   0 - 80016 poll_s ?        00:00:00 joplin
> 0 S  1000 21995 21946  0  80   0 - 103873 poll_s ?       00:00:00 joplin
> 1 S  1000 22003 21967  4  80   0 - 295023 futex_ ?       00:00:02 joplin
> 1 S  1000 22032 21967  0  80   0 - 242702 futex_ ?       00:00:00 joplin

Find the parent pid of Joplin.AppImage: 21197
$ kill **21197**

The desktop environment would crash and then return to the login screen.

However, kill the pid of 21946 and 21951, instead of **21197**, would not crash the gnome desktop.

#### Log
- Joplin log:

no relevant log was found for the crash in the ~/.config/joplin-desktop/log.txt as in debug mode.

- Syslog:

> Jan 12 10:22:33 pp gnome-session[21555]: (nautilus:21733): GVFS-RemoteVolumeMonitor-WARNING **: Owner of volume monitor org.gtk.vfs.MTPVolumeMonitor disconnected from the bus; removing drives/volumes/mounts
> Jan 12 10:22:33 pp gnome-session[21555]: (unity-fallback-mount-helper:21741): GVFS-RemoteVolumeMonitor-WARNING **: Owner of volume monitor org.gtk.vfs.MTPVolumeMonitor disconnected from the bus; removing drives/volumes/mounts
> Jan 12 10:22:33 pp gnome-session[21555]: (deja-dup-monitor:22361): GVFS-RemoteVolumeMonitor-WARNING **: Owner of volume monitor org.gtk.vfs.MTPVolumeMonitor disconnected from the bus; removing drives/volumes/mounts
> Jan 12 10:22:33 pp gnome-session[21555]: (nautilus:21733): GVFS-RemoteVolumeMonitor-WARNING **: Owner of volume monitor org.gtk.vfs.AfcVolumeMonitor disconnected from the bus; removing drives/volumes/mounts
> Jan 12 10:22:33 pp gnome-session[21555]: (unity-fallback-mount-helper:21741): GVFS-RemoteVolumeMonitor-WARNING **: Owner of volume monitor org.gtk.vfs.AfcVolumeMonitor disconnected from the bus; removing drives/volumes/mounts
> Jan 12 10:22:33 pp gnome-session[21555]: (deja-dup-monitor:22361): GVFS-RemoteVolumeMonitor-WARNING **: Owner of volume monitor org.gtk.vfs.AfcVolumeMonitor disconnected from the bus; removing drives/volumes/mounts
> Jan 12 10:22:33 pp gnome-session[21555]: gnome-session-binary[21555]: WARNING: Lost name on bus: org.gnome.SessionManager
> Jan 12 10:22:33 pp gnome-session-binary[21555]: WARNING: Lost name on bus: org.gnome.SessionManager
> Jan 12 10:22:33 pp gnome-session[21555]: gnome-session-binary[21555]: CRITICAL: We failed, but the fail whale is dead. Sorry....
> Jan 12 10:22:33 pp gnome-session-binary[21555]: CRITICAL: We failed, but the fail whale is dead. Sorry....

One possible cause of the problem seems to be somehow related to the mount points of Joplin, though other factors may play the real culprits, e.g. bugs in the gnome desktop.

**Comment by laurent22** [comment]
Joplin doesn't do anything special with its process so it could be a bug in Electron, electron-builder or the Gnome desktop.
