### ISSUE TITLE
Improve file deletion prompt

### ISSUE THREAD

**Issue by oguzhanogreden** [laurent22/joplin#1123]
Hi,

Consider a user right clicking on a notebook (or a note) when another is selected, then click Delete. There is a nice little prompt which warns the user that this is a delete action. I think there are several easy improvements possible here:

1. It's not clear which notebook is being deleted. It would be nicer to write the name and type of the object that's being deleted.
2. It's not clear if deletion of notebooks/notes is an undoable action. It seems not, but I've been using Joplin for far too few days to be sure of this.
2. At least on Windows, the 'active' button is OK. So if I hit enter or space accidentally, it will perform the remove action. This is a vastly higher price to pay for a mistake. I would not want to hate my cat for stepping onto my keyboard at a particularly unlucky time :)

I suppose these would be fairly easy to change, with a considerable improvement in user experience.

Great job overall, thanks for Joplin!
Oguzhan

### Operating system
- Windows
- macOS
- Linux

### Application
- Desktop

**Comment by i-need-to-tell-you-something** [comment]
I found it really unintuitive on Linux that when I press Delete and follow it with Enter, then it cancels. I feel the UX convention in general is that Delete+Enter deletes things (also there is now no way to delete things with keyboard only - which would be much faster than by mouse or touch). Also the likelihood of notes or notebooks being selected AND delete being pressed AND enter being pressed sounds just super unlikely.
