### ISSUE TITLE
Joplin Running Synchronization to S3 Bucket Too Often

### ISSUE THREAD

**Issue by Eric599** [laurent22/joplin#11238]
### Operating system

macOS

### Joplin version

3.0.15

### Desktop version info

Joplin 3.0.15 (prod, darwin)

### Current behaviour

I have hooked up my personal S3 bucket to sync my Joplin notes. I started noticing my cloud bill increasing dramatically and eventually found out that it was coming from my S3 Joplin bucket. I have changed the sync settings to only happen once every 24 hours but I noticed that it is still syncing every time I make a change to a note/document. I have disabled the sync shortcut (cmd+s) so I know I am not accidentally syncing numerous times. But still notice an excessive amount of read/writes to my S3 Bucket. Below I have provided evidence of Joplin syncing multiple times even though I have it set to 24 hour intervals, you can see that it has synced 3 times within a 10 minute interval. This is leading to 100s of unnecessary requests to my S3 bucket every week. Thank you, for your time!

EDIT: As a work around, I have tried disabling the synchronization completely with the intent to manually sync by clicking the "synchronization" button but I am still noticing that Joplin syncs automatically every time I make a change to a document. 

<img width="360" alt="image" src="https://github.com/user-attachments/assets/ae0dd789-7b7f-48a2-a0e1-27fac87d0196">

<img width="286" alt="image" src="https://github.com/user-attachments/assets/51c71df9-383c-4f9f-9332-af3b0b66b20c">

<img width="290" alt="image" src="https://github.com/user-attachments/assets/e0cbd799-91a5-41d3-85e6-807bc55c7eb3">

<img width="243" alt="image" src="https://github.com/user-attachments/assets/294d16eb-fbad-463f-b021-4d3d8b3c8bca">

### Expected behaviour

I expect Joplin to only sync to my S3 bucket once every 24 hours, as specified in the settings

**Comment by executed** [comment]
Eric, I'm just curious. What storage plan do you use? How big is your bucket? And what's the average monthly cost?

**Comment by JackGruber** [comment]
If a sync target is active, Joplin synchronized the Note which is edited to reduce conflicts. This behavior cannot be deactivated either, unless the Synctarget is set to None, the Syncronisation intervall has no influence on this behavior. Has been explained in the forum and here on git by Laurent.

**Comment by executed** [comment]
@JackGruber sounds like this bug can be closed then and a new one about algorithm change or something can be opened.
CC: @Eric599

**Comment by Eric599** [comment]
@executed I am currently using the free tier AWS S3 Bucket pricing but received an email that I am about to exceed the free tier usage which is what made me realize that Joplin was excessively reading and writing to my bucket. Since I was using the free tier I am unsure what the monthly costs would have been but as mentioned above, I have been manually deactivating sync and re enabling it once a day to sync.  If more information is needed feel free to let me know, I can dig up the read write metrics provided by AWS. Thanks guys!

**Comment by executed** [comment]
@Eric599 ok thanks. See comment from Jack - I think this one might be closed
