### ISSUE TITLE
Release Checksum - improper method employed

### ISSUE THREAD

**Issue by scottfurry** [laurent22/joplin#11249]
### Operating system

macOS

### Joplin version

gt or eql 3.1.15

### Current behaviour

Current Stable Releases uses a Windows blockfile to verify MacOS disk-image dmg.

### Expected behaviour

Platform independent sha512sum file expected.

**Comment by laurent22** [comment]
Answered here: https://github.com/laurent22/joplin/pull/11252

**Comment by scottfurry** [comment]
From pull request:
> Reason for the Change:
> The current build process relies on platform-specific mechanisms to verify the integrity of macOS .dmg files. This change provides a platform-independent solution by using a sha512sum checksum, improving security and ease of use for all users.

I believe the rational is valid and prudent. The .dmg can be manipulated. I have to disagree with the decision.

**Comment by laurent22** [comment]
> The .dmg can be manipulated

Yes it can - but then it won't be allowed to run. So I'm not seeing any problem here. Also, again, we already publish a hash in latest-mac.yml. It's unclear why this is not enough
