### ISSUE TITLE
Spell checker cannot be disabled in RTE

### ISSUE THREAD

**Issue by tconsta** [laurent22/joplin#11261]
### Operating system

macOS

### Joplin version

3.1.20

### Desktop version info

Joplin 3.1.20 (prod, darwin)

Client ID: bbbeabf1223040a0b4246893ba912bc7
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 8199362

Backup: 1.4.2

### Current behaviour

1. Create a note in RTE
2. Enable spell check
3. Misspell a word
4. Disable spell check
5. Move cursor and wait a sec to see if it changed
6. The error is still underlined

<img width="716" alt="image" src="https://github.com/user-attachments/assets/0641920e-dad8-4830-a45b-bcd64833446e">

### Expected behaviour

I'd like to be able to disable spell checking at all.

No plugins installed, default styles, stable release works the same.

Is there any workarounds like just CSS tweak? 

But I think it can annoy and alienate newcomers, so maybe fixing it properly has some value.

**Comment by Amaanhussain11** [comment]
Thank you for reporting this bug, I would like to work in it. I am actually new to this project, can you please give me an overview to set this up in my local machine, I would be very thankful.

**Comment by dhakarRaghu** [comment]
@tconsta 
Do you have any insights on whether this could be the source of the bug, or if there's another area where settings may not be applying correctly?
Thanks for your help!

**Comment by dhakarRaghu** [comment]
@tconsta @laurent22  I have created a PR regarding this issue  #11388 . please review it.
