### ISSUE TITLE
Export jex error

### ISSUE THREAD

**Issue by marklove5102** [laurent22/joplin#11278]
### Operating system

Windows

### Joplin version

3.1.20

### Logs

Joplin 3.1.20 (prod, win32)

客户端 ID: 8eb04e988992493da3f9cf376aab31b3
同步版本：3
配置文件版本：47
支持的密钥链：是

修订：8199362

Backup: 1.4.2

![导出](https://github.com/user-attachments/assets/62faa827-dc0d-4af2-9f07-abb87ddb89e1)
![捕获](https://github.com/user-attachments/assets/cb35b3aa-1152-49f0-9492-599a8e19782a)

**Comment by marklove5102** [comment]
![image](https://github.com/user-attachments/assets/0463cf14-3ee9-4dec-829d-9bb5d4629879)
````
备份为 jex 时出错: Error: EPERM: operation not permitted, unlink 'C:\Users\freem\.config\joplin-desktop\tmp\820b317ffbe9476bc3d290a91b6e399e\resources\80b3a972cb264f77b5978af63694f8e5.htm'. Path: C:/Users/freem/.config/joplin-desktop/tmp/820b317ffbe9476bc3d290a91b6e399e
````

**Comment by mrjo118** [comment]
I think I've seen this error before (might have been on sync, rather than on export) and it was related to a file / folder being locked. Do you still get the issue after restarting your PC?

**Comment by marklove5102** [comment]
Windows Defender caused this issue. Closing Defender cannot reproduce it
Open and export again to reproduce the problem
@mrjo118
