### ISSUE TITLE
Indentation in markdown editor

### ISSUE THREAD

**Issue by SamuelUlep** [laurent22/joplin#11279]
### Operating system

Windows

### Joplin version

3.1.20

### Desktop version info

Joplin 3.1.20 (prod, win32)

Client ID: ----
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 8199362

Backup: 1.4.2

### Current behaviour

1. Updated joplin to latest version
2. See attached image, new markdown editor has indentation
![image](https://github.com/user-attachments/assets/88c75f48-8318-4980-bee9-3b28a6567527)

### Expected behaviour

1. Expecting there to be no indentation on the markdown editor like in the older version of joplin
2. Old joplin after enabling legacy markdown without indentation in markdown editor
![image](https://github.com/user-attachments/assets/0627d6fc-ccad-4f9b-8e77-aff9fc9a5612)

Is this expected? If so can I remove the indent without enabling legacy markdown editor?

**Comment by personalizedrefrigerator** [comment]
I'm linking to the [relevant forum post](https://discourse.joplinapp.org/t/editor-maximum-width-issue/41551/2). It includes:
> - The 15px left-right margin is on the `.cm-content` element.
>    - This comes from the use of `theme.marginLeft` in [`theme.ts`](https://github.com/laurent22/joplin/blob/db966f919ea51f5f32fa454a10c7a64957a4e9de/packages/editor/CodeMirror/theme.ts#L97).
> - Each `.cm-line` has an additional `2px` left-edge padding.
>     - This also seems to be present in the [upstream CodeMirror example editor](https://codemirror.net/).
>     - It should be possible to override in [`theme.ts`](https://github.com/laurent22/joplin/blob/db966f919ea51f5f32fa454a10c7a64957a4e9de/packages/editor/CodeMirror/theme.ts).
>
> <details><summary>Workarounds</summary>
>
> 1. Re-enable the legacy editor
> 2. Add the following [custom CSS](https://discourse.joplinapp.org/t/introduction-to-customising-joplin-userchrome-css-userstyle-css/21370):
>   ```css
>    .CodeMirror .cm-line {
>           padding-left: 0;
>    }
>  
>    .CodeMirror .cm-content {
>           margin-left: 0;
>           margin-right: 0;
>    }   
>    ```
>
> </details>

**Edit/Clarification**: Items 1 and 2 under "workarounds" are separate workarounds (and not steps of a procedure).

**Comment by SamuelUlep** [comment]
I mean is there a way to fix the issue without enabling the legacy markdown editor?

**Comment by personalizedrefrigerator** [comment]
> I mean is there a way to fix the issue without enabling the legacy markdown editor?

I've [opened a pull request](https://github.com/laurent22/joplin/pull/11290) that should remove the extra margins. Until it's released, item 2 under "workarounds" should allow removing the margins without disabling the new edtior:
> 2. Add the following [custom CSS](https://discourse.joplinapp.org/t/introduction-to-customising-joplin-userchrome-css-userstyle-css/21370):
>   ```css
>    .CodeMirror .cm-line {
>           padding-left: 0;
>    }
>  
>    .CodeMirror .cm-content {
>           margin-left: 0;
>           margin-right: 0;
>    }   
>    ```

**Comment by SamuelUlep** [comment]
I see thanks, I'll wait for the update then.

**Comment by personalizedrefrigerator** [comment]
I'm re-opening this until the [pull request](https://github.com/laurent22/joplin/pull/11290) is merged.
