### ISSUE TITLE
How to switch markdown editor in 3.1

### ISSUE THREAD

**Issue by yuxh** [laurent22/joplin#11277]
### Operating system

Windows

### Joplin version

3.1.20

### Desktop version info

Joplin 3.1.20 (prod, win32)

Client ID: 380bb1f6b79c426ea9634b5e85d77933
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 8199362

Backup: 1.4.2
Highlight Matching: 0.1.0
macOS theme: 1.5.8
Note Tabs: 1.4.0
Outline: 1.5.13

### Current behaviour

I find this warning after update to 3.1.20 "The following plugins may not support the current markdown editor: Outline" . It suggests me to switch to legacy editor 

### Expected behaviour

Actually it affects the Highlight Matching plugin if I don't switch to legacy editor . I don't see any options to toggle the markdown editor

**Comment by JackGruber** [comment]
Go to `Tools > Options > General`, open the `Advanced Settings` and set the Checkbox for `Use the legacy Markdown editor`. After that restart Joplin.

**Comment by yuxh** [comment]
> Go to `Tools > Options > General`, open the `Advanced Settings` and set the Checkbox for `Use the legacy Markdown editor`. After that restart Joplin.

thanks, I found it . I think the compatible plugin warning is not correct about which plugin will have a problem in new editor
