### ISSUE TITLE
Joplin doesn't update postgresql password

### ISSUE THREAD

**Issue by s1s1fo** [laurent22/joplin#11293]
### Operating system

Linux

### Joplin version

Joplin Server .3.0.1

### Current behaviour

1. Set database authentication via docker-compose.
2. Start containers. Connection is successful between server and database.
3. Change database password in postgresql container.
4. Update docker-compose setting new password in joplin container (using secrets or env)
5. Test connection: Failure

Joplin seems to store the authentication data somewhere and doesn't update it from compose file.

### Expected behaviour

Joplin should update the authentication data if it is changed in the docker configuration parameters or provide mechanism for updating it.

**Comment by asmit990** [comment]
first restart the container , then clear the Cached confi then you can  use this command like  " environment:
  DB_PASSWORD_FILE: /run/secrets/db_password
" most prolly it will work
