### ISSUE TITLE
markdown monospace/code font rendering in iOS app

### ISSUE THREAD

**Issue by jeschwar** [laurent22/joplin#1130]
### Operating system

- iOS

### Application

- Mobile

How can I do markdown rendering of monospace/code font in the iOS app?  I am accustomed to using the back-quote/back-tick key for inline code sections when writing markdown documents on a desktop; the problem is this key does not appear on my iPhone keyboard.

**Comment by tessus** [comment]
Tap and hold the key for the single quote.

**Comment by jeschwar** [comment]
Thank-you!
