### ISSUE TITLE
New item button hidden when using 3-button navigation mode

### ISSUE THREAD

**Issue by nbaxley** [laurent22/joplin#11315]
### Operating system

Android

### Joplin version

3.1.7 (prod, android)

### Current behaviour

1. When using 3-Button navigation mode in Android (v14 and v15)
2. The red "new item" button at the bottom of the screen is hidden by the 3-button navigation bar and can not be clicked without precise clicking

### Expected behaviour

1. When using 3-Button navigation mode in Android
2. The New item button should be moved up so it's above the navigation bar.

**Comment by personalizedrefrigerator** [comment]
I'm linking to an issue that might be related: https://github.com/laurent22/joplin/issues/11276
