### ISSUE TITLE
List autocompletion not working if current list item ends with HTML code

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#11318]
Create a list like so in the new Markdown editor:

```
- [ ] One
- [ ] Two <span style="color: #2b0d3e;">Test/span>
```

Position the cursor at the end of the second list item and press Enter

=> Instead of starting a new list item with `- [ ] `, it starts an empty line

Note: This doesn't happen with the legacy text editor.

**Comment by personalizedrefrigerator** [comment]
I can reproduce this in [a Markdown editor on the CodeMirror try it page](https://codemirror.net/try/?c=aW1wb3J0IHtiYXNpY1NldHVwLCBFZGl0b3JWaWV3fSBmcm9tICJjb2RlbWlycm9yIgppbXBvcnQge21hcmtkb3dufSBmcm9tICJAY29kZW1pcnJvci9sYW5nLW1hcmtkb3duIgppbXBvcnQge2xhbmd1YWdlc30gZnJvbSAiQGNvZGVtaXJyb3IvbGFuZ3VhZ2UtZGF0YSIKCmxldCB2aWV3ID0gbmV3IEVkaXRvclZpZXcoewogIGRvYzogJy0gWyBdIE9uZVxuLSBbIF0gVHdvIDxzcGFuIHN0eWxlPSJjb2xvcjogIzJiMGQzZTsiPlRlc3Q8L3NwYW4+JywKICBleHRlbnNpb25zOiBbCiAgICBiYXNpY1NldHVwLAogICAgbWFya2Rvd24oe2NvZGVMYW5ndWFnZXM6IGxhbmd1YWdlc30pCiAgXSwKICBwYXJlbnQ6IGRvY3VtZW50LmJvZHkKfSkK).

**Comment by personalizedrefrigerator** [comment]
Upstream bug report: https://github.com/codemirror/dev/issues/1462

**Comment by laurent22** [comment]
Thanks for submitting the report! And it looks like it's already fixed
