### ISSUE TITLE
Add Support for Mermaid 11.4.0

### ISSUE THREAD

**Issue by bsavant** [laurent22/joplin#11327]
### Operating system

macOS

### Joplin version

3.1.20

### Desktop version info

Joplin 3.1.20 (prod, darwin)

Client ID: 1dfa99475d17480db74956dc092b7dfc
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 8199362

Backup: 1.4.2
Combine notes: 1.2.2
Draw.io: 2.2.0
Embed Search: 2.0.0
Freehand Drawing: 2.11.0
Inline tags: 1.3.0
Insert Date: 1.0.1
Note Tabs: 1.4.0
Quick Links: 1.4.1
Rich Markdown: 0.15.0
Templates: 2.4.0
Time Slip: 0.2.0

### Current behaviour

Joplin is using Mermaid 10.9.1.  

### Expected behaviour

Newer Mermaid releases have added a number of new diagram types.

**Comment by LEVIII007** [comment]
@personalizedrefrigerator @bsavant  I have created a PR #11367 regarding this issue. Please take a look at it. 
please tell me if there is any change I need to make to it.
