### ISSUE TITLE
Back navigation often stuck in a loop

### ISSUE THREAD

**Issue by Terrance** [laurent22/joplin#11324]
### Operating system

Android

### Joplin version

3.1.7

### Desktop version info

Joplin Mobile 3.1.7 (prod, android)

Client ID: d8e98c66054049f0b59e6d8c0db590b2
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 41b251d67 (release-3.1)

Joplin Calendar: 1.2.0
Outline: 1.5.13

Android API level: 33
WebView version: 130.0.6723.86
WebView package: com.google.android.webview
FTS enabled: 1
Hermes enabled: 1

### Current behaviour

1. Share content into Joplin
    * note editor for new note with shared content
2. Navigate back
    * note viewer for newly created note
3. Navigate back again
    * note list for the current notebook
4. Navigate back again
   * note list for _All notes_
5. Navigate back again
    * note viewer for newly created note
6. Repeat of steps 3 to 5
7. Spam multiple back navigation gestures
    * app eventually exits

### Expected behaviour

Previously, navigating back from the current notebook would leave the app.

Navigation appears to work ok when the app is freshly launched from a launcher rather than a share.

This started in the Android 3.1.6 release, and persists in 3.1.7, happening about 50% of the time (with #10850 happening the rest of the time -- I've yet to have any shares work without fault in 3.1.7).

### Logs

📎 [syncReport-1730920450865.txt](https://github.com/user-attachments/files/17651959/syncReport-1730920450865-snip.txt)

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

I can reproduce the issue on an Android 15 emulator.

From my (limited) debugging, it seems related to [this `NAV_GO` action](https://github.com/laurent22/joplin/blob/5a44f62fb6988a5b3380cc86274fd20947952c73/packages/app-mobile/components/screens/Note.tsx#L252) and [this commit from September](https://github.com/laurent22/joplin/commit/a01f51913159913e11e4ad3b3b493b128c25d979).

So far, replacing [this NAV_GO](https://github.com/laurent22/joplin/blob/5a44f62fb6988a5b3380cc86274fd20947952c73/packages/app-mobile/components/screens/Note.tsx#L252) with a `NAV_BACK` seems to fix the issue. However, this may cause other regressions.
