### ISSUE TITLE
Update & fix changelogs

### ISSUE THREAD

**Issue by Perkolator** [laurent22/joplin#11321]
### Operating system

Windows

### Joplin version

3.1.22

### Current behaviour

The changelogs need updating and fixing, files & website.

For example (I didn't check other changelogs):

1) The [desktop changelog](https://github.com/laurent22/joplin/blob/dev/readme/about/changelog/desktop.md) is missing the latest 3.1.22 update.

2) The [Android changelog](https://github.com/laurent22/joplin/blob/dev/readme/about/changelog/android.md) seems to be updated to the latest version (3.1.7), but the [website changelog](https://joplinapp.org/help/about/changelog/android/) is not updated, it still shows version 3.1.5 as the latest.

3) The same Android changelog, since the `android-v2.6.9 - 2021-12-20` release almost 3 years ago, EVERY new version after that is marked as `(Pre-release)`.

I also propose that the changelogs should be made more easier to read. For example the newest stable could list ALL changes since the last stable. "Just read the changelogs back to the previous stable" you say? Well, it's not that easy. Let's say that I read all changes (all pre-releases) between 3.1.20 and the previous stable version 3.0.15, I would still miss some changes because the 3.0.15 was a small update that had only 2 quick fixes from the 3.1.x "branch" pre-release versions, and the real last stable was version 3.0.14.

**Comment by Vineet1101** [comment]
Is this issue still there , I would like to fix this bug if its not fixed
