### ISSUE TITLE
Text cursor is not visible when at the start of a line in normal Markdown editor mode

### ISSUE THREAD

**Issue by isaacsu** [laurent22/joplin#11320]
### Operating system

Windows

### Joplin version

 3.1.22

### Desktop version info

Joplin 3.1.22 (prod, win32)

Client ID: 2a633219cc4e4fd0b5a87cefd7562bdb
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: da10297

### Current behaviour

1. Click "New note" to create a new note
2. Ensure the editor is in Markdown mode and Rich Text editor is disabled
3. Click on editor to focus on text editor
4. Observe that text cursor (i.e. "|") is not visible
5. Press space once. Observe that text cursor is visible.
6. Press backspace once. Observe that text cursor is not visible.
7. Type the word "bun". Observe that text cursor is to the right of "n" (e.g. "bun|")
8. Press left arrow key three times
9. Observe that text cursor is not visible.

Thank you so much for creating Joplin!

### Expected behaviour

In step (4), text cursor should be visible
In step (6), text cursor should be visible
In step (9), text cursor should be visible

**Comment by mariosgit** [comment]
Same here. Very irritating.

```
Joplin 3.1.22 (prod, win32)
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes
Revision: da10297
```

**Comment by Sidd-013** [comment]
I can recreate this behavior in prod version but not in my up to date repo locally. Why could it be this way?

**Comment by isaacsu** [comment]
If it's any help at all, I only see this happening on Windows. 

It works as expected on MacOS:

```
Joplin 3.1.22 (prod, darwin)
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes
Revision: da10297
```

**Comment by krc** [comment]
Same as two above 
Joplin 3.1.22 (prod, win32) on Windows 10 (22H2, Build 19045.5073)

**Comment by rafaelespinoza** [comment]
Unlike @isaacsu [mentioned here](https://github.com/laurent22/joplin/issues/11320#issuecomment-2461098753) I have noticed this issue on MacOS.
Same observations and steps to reproduce mentioned in the original comment.

```
Joplin 3.1.22 (prod, darwin)

Client ID: xxxxxx
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: da10297

Backup: 1.4.2
```

Also, thank you laurent22 and co. for creating this incredible app!

**Comment by starlight173** [comment]
Same, but I still encountered it even not only in the mark down style mode but also in simple text. The cursor just disappeared at the begining of the new line

```
Joplin 3.1.22 (prod, win32)

Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: da10297

Backup: 1.4.2
Code Section: 1.0.6
```

**Comment by isaacsu** [comment]
FYI, downgrading to `Joplin 3.1.20 (prod, win32)` seems to have made the cursor visible at the start of the line again, so it's probably something that was introduced in `3.1.22`.

**Comment by isaacsu** [comment]
Huh, looks to be related to: https://github.com/laurent22/joplin/issues/11313

In which case, a fix should be coming soon with https://github.com/laurent22/joplin/pull/11316 in `3.1.23`.

**Comment by GAnestoNCS** [comment]
A temporary fix I used while waiting for the official release is adding the following code to my userchrome.css file to resolve the issue:
```
.cm-line {
    padding-left: 1px !important;
}
```

**Comment by aganet** [comment]
As a temporary fix while awaiting the official fix release, I added the following css override to my userchrome.css file, and cursor is visible again:
```css
.cm-line {
    padding-left: 1px !important;
}
```

**Comment by rafaelespinoza** [comment]
v3.1.23 was released a few hours ago. It has fixed my issue on MacOS Desktop. Thank you!

**Comment by krc** [comment]
Fixed for me on Windows with 3.1.23! Thanks!

**Comment by CoderAllan** [comment]
Yes, v3.1.23 fixed the issue. Thanks!!

**Comment by isaacsu** [comment]
Fixed for me too 🎉
