### ISSUE TITLE
Drag and drop preview caret invisible in dark mode

### ISSUE THREAD

**Issue by annoyedhumanoid** [laurent22/joplin#11336]
### Operating system

macOS

### Joplin version

3.1.23

### Desktop version info

Joplin 3.1.23 (prod, darwin)

Client ID: 11cb0a2d420047cd9119a44d443e827c
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: b3ea127

Backup: 1.4.2
Note Statistics: 1.0.4

### Current behaviour

Version 3.1.22 fixed issue #11274 "Dragging and dropping text no longer shows preview caret", so that there is a drag-and-drop preview caret now, but it's black even in dark mode, which makes it nearly invisible:

https://github.com/user-attachments/assets/ef349bff-4f53-4555-94fc-647541ebdafd

It can be seen in the highlighted text, but nowhere outside of it.

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

**Development information**: [theme.ts](https://github.com/laurent22/joplin/blob/0b6082d679a41ffa55fa015057a651714d2292c0/packages/editor/CodeMirror/theme.ts#L104) will likely need to be updated to style the drop cursor in addition to the standard cursor.

**Comment by RgiriH** [comment]
Is the colour of the text need to be white in dark mode?

**Comment by VANSH3104** [comment]
@annoyedhumanoid can i work on this

**Comment by LEVIII007** [comment]
@annoyedhumanoid @personalizedrefrigerator  I have made a pull request regarding this issue. I have added the drop cursor color config to the dark theme in theme.ts file. Please review it. Thank you
