### ISSUE TITLE
First line of “unformatted text” has less indent

### ISSUE THREAD

**Issue by tomatojam42** [laurent22/joplin#11333]
### Operating system

Linux

### Joplin version

Joplin 3.0.15 (prod, linux)

### Desktop version info

Joplin 3.0.15 (prod, linux)

Client ID: 2f52a55e2382439982ec533c0077f388
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Note overview: 1.7.1
Note Tabs: 1.4.0
Search & Replace: 2.2.0
Space Indenter: 0.2.5
Table Formatter Plugin: 1.2.1
Templates: 2.4.0

### Current behaviour

If I indent text with 4 spaces or with tab for creating "Unformatted text" as described in the guide ([Markdown Guide | Joplin](https://joplinapp.org/help/apps/markdown/)), then:

- IN EDITOR first line of every unformatted paragraph would be with small indentation and rest lines would be with huge indentation.
- Even if I count spaces one by one, at first line they will have smaller size, but number is same.
- IN VIEWER all lines aligned straight by left.

![image](https://github.com/user-attachments/assets/496e537c-c015-479d-8a9f-b3189a922391)

### Expected behaviour

IN EDITOR all lines should be aligned straight by left.

(Although in the Android app all are rendered right)

**Comment by tomatojam42** [comment]
Of course I tried to disable all extensions.

**Comment by personalizedrefrigerator** [comment]
In Joplin v3.0.15, enabling the beta editor should help.  To do this, go to settings > advanced > opt-in to the editor beta.
