### ISSUE TITLE
bug in global search algorithm

### ISSUE THREAD

**Issue by marcorighi** [laurent22/joplin#1133]
### Operating system

- Linux

### Application

- Desktop

I have a note that has the following line:

```
...
something written
...
***
**TL WPA4220**
wlanext
***tplsoggiorno***
**AFF0**

Range Extender MAC Address:
0C-80-02-44-AF-F1
...
something written
...
```

in general search I found nothing using only one of the following search string 
1. "sogg"
2. "sogg*"
3. "*sogg*"

I found the correct note with the string "tpl*"

I think that the bug was not present when Joplin had only global search.

please ask me if you need more information

**Comment by favadi** [comment]
I'm also using Joplin on Linux and the problem is global search refuses to find anything unless the search term matches exactly whole world.
