### ISSUE TITLE
[Feature Request] In-note todo due dates and global agenda

### ISSUE THREAD

**Issue by pettni** [laurent22/joplin#1134]
I like the philosophy expressed in this [Org-mode talk](https://www.youtube.com/watch?v=oJTwQvgfgMM), namely that it is natural to mix notes with todo items since todo's often come up while writing down notes. In Joplin I tend to use in-note todos more often than todos that are notes themselves, but when the in-note todos are spread across notes and notebooks they become hard to keep track of.

I therefore think these would be great features:
 - Syntax for adding a "duedate" field to in-note todos similar to Org-mode. This project has implemented this functionality using a syntax that is fairly readable in plain text: https://github.com/benjaminoakes/markdo
 - A global agenda that grabs in-note todos from all notes and lists them sorted by due date with a link to the note where the todo was found. This could maybe be implemented by piggy-backing on global search

It is possible to do something like this with a command-line pipe:
```zsh
grep -h '@due' Dropbox/Apps/Joplin/* | grep '\[\s\]' | sed 's/\-\s\[\s\]\s//g;s/@due.\(.*\))\s/\1: /g' | sort
```
I'm currently using this with ````alias agenda="..."``` but it would of course be even better to have the functionality inside of Joplin with typesetting and links to the notes etc.

Nice-to-haves but likely more work/more intrusive to implement:
 - Possibility to interact with a todo from the agenda (i.e. mark it as done, kick the date further into the future, etc)
 - Nice rendering of the due date property

Would something like this be aligned with the goals of the project?

**Comment by jkassel** [comment]
The one missing feature from Joplin that would make it 100% perfect!
