### ISSUE TITLE
Feature request: Porter tokenizer in fulltext search

### ISSUE THREAD

**Issue by jbriales** [laurent22/joplin#1135]
Really happy for the introduction of fulltext search in Joplin as requested in https://github.com/laurent22/joplin/issues/959. I think this really improves the user experience.

I still find however a detail missing:
I think the created FTS table is currently using the default "simple" tokenizer. Am I right?
If so, would it be possible to set "porter" by default? I.e. defining
`CREATE VIRTUAL TABLE notes_fts USING fts4(content="notes", notindexed="id", id, title, body, tokenize=porter)` instead.
The "porter" tokenizer uses the Porter Stemming algorithm and provides a much more intelligent search in my opinion and experience :)
Quick read: https://www.sqlite.org/fts3.html#tokenizer

**Comment by tessus** [comment]
I like this idea, but I'm afraid it's only a viable solution for English. Please correct me, if I'm wrong, but the Porter Stemming algorithm only applies to English. What happens for other languages?
I think it might be more interesting to get rid of diacritics. However, this also only helps for latin based languages.

**Comment by laurent22** [comment]
I'm not familiar with but will check. The tokenizer would have to be available on Android and iOS which often it's not.

**Comment by jbriales** [comment]
@tessus you're right on that. I know there are other variations of Porter for other languages, such as the ICU tokenizer. But Porter's is probably the best working one (actually that's one of the reasons why I write all my notes in English! :D). I'm not sure how does the Porter algorithm behave when applied over non-English text. Most likely it will be similar to the "simple" tokenizer as no English suffices will be found.

@laurent22 it's probably the first/second most common tokenizer (together with the "simple" one), so hopefully might be available in mobile platforms as well.

I didn't say it in the original request but actually I think it shouldn't be difficult to make this an option in settings (it's an `tokenize=` option when creating the SQLite table so I guess if you change the option you just need to delete the table and create it again with the different tokenizer, then index all notes from scratch). I'd make a pull request for it but sadly I'm not familiar with JavaScript so reading the code is easier than modifying it :)

**Comment by jbriales** [comment]
@laurent22 did you get to check about availability on Android and iOS?

**Comment by laurent22** [comment]
I forgot about this, and I guess search works well enough that changing it doesn't make much sense.

If you're familiar with this tokenizer, do you know what would we gain from it? For example, what query currently returns poor results, and would return good ones with this tokenizer? We'd also need to clarify how it supports non-English queries, and whether it's available on iOS and Android (and whether it's available on all Android devices or just some of them).

I think it's no an easy change and benefits are not clear.

**Comment by jbriales** [comment]
Haven't had the time to look thoroughly onto this yet.
I'm currently using my own virtual table in the SQLite database to enable the Porter tokenizer.
The main benefit I noticed so far is Porter uses the root of words so it's much more flexible to find notes based on keywords than the usual simpler tokenizer.
