### ISSUE TITLE
Incomplete Sync with Android through Nextcloud

### ISSUE THREAD

**Issue by fethomm** [laurent22/joplin#1136]
### Operating system

- Linux
- Android

### Application

- Mobile

Hi, 

found Joplin a couple of days ago and liked it's options from the start. Ran into a problem with Android though. Notebooks in the desktop app on linux synchronise only in parts with my phone through Android. 
From 5 Notebooks only 2 get synced. 

Version of Joplin on desktop is:     Joplin 1.0.120 (prod, linux)
Version of Joplin on  Android is:     Joplin 1.0.234
Android Version is                           Android 8.1.0 

Two things I should mention: I created the folder /Joplin on Nextcloud. Second is I tested encryption in Joplin, it worked and I disabled it because I don't need it right now. Is there a way to debug what is to blame here?

**Comment by foxmask** [comment]
did you disable e2ee on each device, one after the other (and not both in same times ) ?
