### ISSUE TITLE
Mobile: Blank UI from switching between notes in different notebooks and unloading app

### ISSUE THREAD

**Issue by ImperialSquid** [laurent22/joplin#11384]
### Operating system

Android

### Joplin version

3.1.8

### Desktop version info

Joplin Mobile 3.1.8 (prod, android)

Client ID: d94348b4ba434bb589db1fb87e33a45a
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 41b251d67 (release-3.1)

AlertsPerfect: 1.0.1
Extra Markdown editor settings: 1.4.1
History Panel: 1.0.2
Kanban: 1.1.0
Link Graph UI: 1.5.0
Math Mode: 0.7.1
Note Tabs: 1.4.0
Quick Links: 1.3.2

Android API level: 34
WebView version: 130.0.6723.107
WebView package: com.google.android.webview
FTS enabled: 1
Hermes enabled: 1

### Current behaviour

1. Create two notebooks
2. Create a note in each notebook
3. Create a markdown link from one note to the other
4. Open the first note
5. Follow the link to the other
6. Close the app (eg by pressing the home or switch app buttons on the bottom UI)
7. Reopen the app (may need to wait a few seconds)
8. See that UI is mostly blank

### Expected behaviour

UI shouldn't break by unloading the app

**Comment by ImperialSquid** [comment]
Here's a screenshot of the UI after following the steps above:

![Screenshot_20241112_162616_Joplin](https://github.com/user-attachments/assets/830426b0-a5bf-42b0-9ea0-a859329f4cc2)

**Comment by ImperialSquid** [comment]
Possibly related to the fix for #10677? Since that one was also about buggy behaviour when switching notes in different notebooks...

**Comment by ImperialSquid** [comment]
Interestingly, navigating A -> B -> A then unloading doesn't seem to result in a blank UI, so the issue seems to be with the current note being in a different notebook than the first one

**Comment by jmooo** [comment]
I posted about this on the community forums and posted 2 videos of the bug happening there, if that helps at all
* https://discourse.joplinapp.org/t/search-result-navigation-across-notebooks-causes-note-to-display-blank-on-ios/41879

**Comment by personalizedrefrigerator** [comment]
> I posted about this on the community forums and posted 2 videos of the bug happening there, if that helps at all
> 
>     * https://discourse.joplinapp.org/t/search-result-navigation-across-notebooks-causes-note-to-display-blank-on-ios/41879

Thank you for the additional information!

Be aware that a [fix](https://github.com/laurent22/joplin/pull/11396) for this issue has been merged. However, at the time of this writing, it has not been included in a release.
