### ISSUE TITLE
Duplicating a note containing a bulleted list with an image destroys the list formatting

### ISSUE THREAD

**Issue by L1ghtmann** [laurent22/joplin#11382]
### Operating system

Windows

### Joplin version

3.1.24

### Desktop version info

Joplin 3.1.24 (prod, win32)

Client ID: 13d5227f980241778ad5562f8f944732
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: d581264

macOS theme: 1.5.7

### Current behaviour

Create a note with a list:
<img width="305" alt="{CCB4FC40-8DD0-4EB6-8AC6-63A789DE3D84}" src="https://github.com/user-attachments/assets/ae4bc1e4-429b-4390-987b-a42f27a10d61">
Duplicate the note
Observe change to formatting to BOTH the original note and the duplicate:
<img width="701" alt="{D42CD7E9-61DF-4E44-B8CE-03EF57EA573D}" src="https://github.com/user-attachments/assets/22267e9d-d9cb-486c-b820-d49e07ceaa19">

Note that this does NOT occur if the list does not contain an image

### Expected behaviour

The formatting to be retained

**Comment by personalizedrefrigerator** [comment]
I can reproduce this in Joplin 3.2.1 &mdash; it seems that if a list item contains only a user-resized (HTML) image, following list items are merged onto the same line when rendering.

In particular if I,
1. Create a note containing a bulleted list in the Rich Text Editor.
2. Add an image as the first list item.
3. Resize the image by dragging one of the resize handles.
4. Add new sub-list-items below the first item.
5. Switch to the Markdown viewer.
6. Switch back to the Rich Text Editor,

I can reproduce this issue.

**Comment by VANSH3104** [comment]
@personalizedrefrigerator I'm new here and wanted to ask if you could point me to where I can find the code for the rich text editor. I'd really appreciate your help! i want to work on this issue

**Comment by VANSH3104** [comment]
@personalizedrefrigerator I also generate this bug it only happens with bulletlist not with numbered list and squared list I also check the pasted list statement too it is same in all case I am working on this issue

**Comment by L1ghtmann** [comment]
Really appreciate your guys' speedy assistance with this! 

I'm unsure if it's also related to resource handling, but I encountered https://github.com/laurent22/joplin/issues/11373 recently. Just figured I'd mention in the event they were similar underlying problems. Thanks again!

**Comment by VANSH3104** [comment]
@L1ghtmann  yes i also think that it is related

**Comment by VANSH3104** [comment]
"Hi @laurent22, I have some doubts related to this issue. I messaged you on Discord. Could you please check?"

**Comment by personalizedrefrigerator** [comment]
It seems that if a list has markup similar to the following,
```markdown
- <img src=":/fa188ce561be4f7f9e7541a1fe4b1341"/>
    - Test
```
then `markdown-it` renders the list as
![screenshot: First list item included on same line as image](https://github.com/user-attachments/assets/29b5ca0e-4f57-4c4c-80c5-2918301b21d0)

Note that GitHub renders the list in a similar way.

To prevent the next line from becoming a continuation of the first, it seems necessary to add a closing tag or other content after the `<img ... />`. For example,
```markdown
- <img src=":/fa188ce561be4f7f9e7541a1fe4b1341"></img>
    - Test
```

**Comment by L1ghtmann** [comment]
Really appreciate you looking into this! I've been meaning to learn TS so I could take a crack myself, but been really busy lately
