### ISSUE TITLE
blurred text (again)

### ISSUE THREAD

**Issue by ulu** [laurent22/joplin#11418]
### Operating system

Windows

### Joplin version

Joplin 3.1.24 (prod, win32)

### Desktop version info

Joplin 3.1.24 (prod, win32)

Client-ID: c44bf0562075478eb365dbce1d5f2ff5
Sync-Version: 3
Profil-Version: 47
Unterstützter Schlüsselbund: Ja

Revision: d581264

Automatic Backlinks to note: 3.0.3
Backup: 1.4.2
Conflict Resolution: 1.2.3
Extra Markdown editor settings: 1.5.0
Link Graph UI: 1.5.0
Quick Links: 1.3.2

### Current behaviour

1. open Joplin
2. resize Window to less than full screen (this will produce the error faster but is not necessary)
3. use mouse coursor with mouse track feature "on" to go into window and out of the window
4. the text sometimes blurs where the mouse has moved over - even DevTools Console gets blurred
5. Text becomes clear on context switch to another window, [Win] or mouse click into another window

There are a number of tickets regarding bluring issues with electron apps. But I do not know if this is a specific Joplin behaviour. One mentioned workaround is to disable FSAA on nVidia. Bur this does not change the behaviour.

My system is an old laptop:
CPU: Intel(R) Core(TM) i7-7700HQ
RAM: 32,0 GB
Gfx 1 (on): GeForce GTX 1060
Gfx 2 (off): intel HD Graphics 630
Monitor: LG Ultrafine with 3840x2160 @60Hz, 8-Bit RGB, standard dynamic range
Windows 10 Pro x64 - 22H2

The blurring can be seen in the window but not on the window label:
<img width="589" alt="Joplin_blur_02" src="https://github.com/user-attachments/assets/8921f1f7-3937-4321-9ad6-5ceebd775bca">

### Expected behaviour

no blurring effect at all

### Logs

only messages, that plugins cannot be loaded in safe mode

**Comment by sutharjay1** [comment]
Can I work on this?

**Comment by imaniketmondal** [comment]
Ensure both your NVIDIA and Intel graphics drivers are up to date. 
Disable Display Scaling
Force Hardware Acceleration or Disable It
Hardware acceleration can sometimes cause such issues.
Check Monitor Refresh Rate Settings.
then too if not working then u may try the previous version.
