### ISSUE TITLE
Broken checkbox styles

### ISSUE THREAD

**Issue by luewolf** [laurent22/joplin#11425]
### Operating system

Android

### Joplin version

3.2.1

### Current behaviour

This issue was introduced recently, probably in 3.2.1 or 3.2.

Checkbox lists with text that spans multiple lines no longer have the checkbox aligned at the top, making it difficult to see where one task ends and the next begins.

![checkbox_align](https://github.com/user-attachments/assets/225a0c77-563b-444c-9ff5-30c9351c4f29)

Also, text highlights (`==foo==`) are no longer inline elements within checkbox list items, which causes weird spacing issues.

![checkbox_highlight](https://github.com/user-attachments/assets/7e7abe9c-3dc5-4bfb-bda3-0492156322b1)

For reference, the words in the second line should be delimited by spaces:

```md
- [ ] So said Midas: ==Mark my words==, I'll have all the gold.
- [ ] foo ==bar== baz
```

The issue was observed with the "Aritim dark" theme. I do not know if it affects other themes as well.

### Expected behaviour

The checkboxes in checkbox lists should be top-aligned when the text spans multiple lines, as it used to be, as the current center-alignment severely impacts readability (and is inconsistent with other kinds of lists to boot!)

Text highlights within checkbox list items should be inline elements like they are everywhere else (including the other kinds of lists).

**Comment by personalizedrefrigerator** [comment]
I'm also experiencing this on the desktop app:
![screenshot: checklist items have inline-block content in their bodies](https://github.com/user-attachments/assets/50b56330-3776-4b8a-b441-febee1255a9a)

@laurent22 could this be related to https://github.com/laurent22/joplin/commit/49e86d116fb400add0e7dac13aeb7deb99ee7231?

**Comment by laurent22** [comment]
Oh, right, yes that would be this change. My goal was to ensure that the checkbox is aligned with the line in front of it, but looks like it broke other things

**Comment by laurent22** [comment]
I can't replicate it though - could you post the Markdown you're using please?

**Comment by laurent22** [comment]
Also please try with [v3.2.3](https://github.com/laurent22/joplin/releases/tag/v3.2.3) since it has a fix for the checkbox vertical alignment

**Comment by personalizedrefrigerator** [comment]
I'm using Joplin desktop v3.2.3 on Fedora Linux. I'm able to reproduce the issue with the following Markdown.
```markdown
- [ ] This `is` a
    test
- [ ] This `is` another<br/>test.
```
For me, it renders as
![screenshot: Codeblock spans multiple lines](https://github.com/user-attachments/assets/3b4f0054-784a-4e3f-abeb-0a4bf0b4281b)
in the Markdown viewer.
