### ISSUE TITLE
Markdown Language addition

### ISSUE THREAD

**Issue by sumi1239** [laurent22/joplin#11422]
### Operating system

Windows

### Joplin version

3.1.24

### Current behaviour

The Joplin export menu currently supports exporting notes in formats such as PDF and HTML. However, it does not provide an option to export notes directly to Markdown (.md) format. 

### Expected behaviour

The export menu should include an option to export notes as Markdown (.md) files. This would allow users to integrate their notes with other Markdown-supported tools and platforms.

**Comment by personalizedrefrigerator** [comment]
At least for me, Joplin (v3.2.1, Linux) includes `Export all` > `MD - Markdown`:
![screenshot: Export all > MD - Markdown shown in file menu](https://github.com/user-attachments/assets/48887c92-7be6-498b-84dc-291949b6dc3d)

For me, the right-click > export menu also includes "MD - Markdown".

I'm testing on v3.2.1 and v3.1.22 (both on Linux).

One possibility is that a plugin is causing an issue with Joplin's export menu. Enabling safe mode disables all plugins. Is the "export all > MD - Markdown" option visible if Joplin is restarted in safe mode (Help > Toggle safe mode)?

**Comment by sumi1239** [comment]
I will give that a try, Thank you very much!

**Comment by awesome-pro** [comment]
Also in macbook, I am getting the option to export into Markdown format, 
can you update to latest version (if not)

<img width="449" alt="Screenshot 2024-11-21 at 3 01 24 AM" src="https://github.com/user-attachments/assets/a9b6271d-6220-4ea4-9cce-bb7730357c7b">
