### ISSUE TITLE
Drag to Notebooks

### ISSUE THREAD

**Issue by TosKam** [laurent22/joplin#1142]
### Operating system
- Windows

### Application
- Desktop

After making a new note to a notebook and drag it to Notebooks (red arrow in the photo), it seems that I could move it, but I can not find it anywhere. When I search it, I can find it. Where does the note go?
According to @tessus , this might be a bug.
Thank you in advance.

![asset 1](https://user-images.githubusercontent.com/46772716/51507736-a1503900-1e35-11e9-86f3-3b10a46fdbad.png)

**Comment by laurent22** [comment]
It's indeed a bug so it will need to be disabled. To get them back, I think you can search for them, then drag them again to a valid folder.

**Comment by TosKam** [comment]
Thank you very much. Search and drag the notes worked fine with me.
