### ISSUE TITLE
Multiple window support: Zoom in/out only affects the main window

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#11444]
### Operating system

Linux

### Joplin version

3.2.3

### Desktop version info

Joplin 3.2.3 (prod, linux)

Client ID: 3b7b5a86ebe4424fbacc04b288e4e6e5
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 1993d30

Backup: 1.4.2
Freehand Drawing: 2.12.0
Import local CSS: 0.0.8

### Current behaviour

1. Press <kbd>ctrl</kbd>-<kbd>-</kbd> in a secondary window
2. Observe that only the main window's zoom level changes.

### Expected behaviour

<kbd>ctrl</kbd>-<kbd>-</kbd> and <kbd>ctrl</kbd>-<kbd>+</kbd> should affect the zoom level in the current window. **Edit**: Or (perhaps better) it should affect the zoom level in all windows.

**Comment by laurent22** [comment]
> ctrl-- and ctrl-+ should affect the zoom level in the current window.

Or it should affect all the windows?

**Comment by manmeetnagii** [comment]
@personalizedrefrigerator can you provide the screen recording or steps to reproduce this

**Comment by LEVIII007** [comment]
@personalizedrefrigerator  Do I need to make changes to the electronAppWrapper.ts and openNoteInNewWindow.ts files to solve this issue? We need to send the zoom level to all secondary windows whenever it gets updated in the main window. will it work?
