### ISSUE TITLE
Katex $ does not render single character

### ISSUE THREAD

**Issue by dejohnua** [laurent22/joplin#1145]
As shown in the following picture, $ expression with single character is not rendered properly, but longer expressions are.
![snipaste_2019-01-24_16-00-08](https://user-images.githubusercontent.com/42671254/51663311-64c93c80-1ff1-11e9-8c5e-d408deba1d7e.jpg)
The problem exists in the lastest version on Windows, but not on Android. Didn't test other platforms.

**Comment by CalebJohn** [comment]
I think this has actually been fixed in development and the next release should reflect that. We might have to wait and see.

**Comment by twchen** [comment]
> 
> 
> I think this has actually been fixed in development and the next release should reflect that. We might have to wait and see.

Yes, just confirm that the problem is fixed in v1.0.125

**Comment by dejohnua** [comment]
> I think this has actually been fixed in development and the next release should reflect that. We might have to wait and see.

Yes, just confirm that the problem is fixed in v1.0.125.
