### ISSUE TITLE
Joplin crashes on startup with read-only-related error

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#11457]
### Operating system

Windows

### Joplin version

3.1.24 and 3.1.23

### Current behaviour

From the forum:
> ```
> An error occurred: Fatal error:
>
> Cannot change or delete a read-only item: e3ce90472d9f4e8b95acff6a437d0cac
>    at checkIfItemCanBeChanged
> (C:\Users\Pa\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\....:15)
>    at checkIfItemsCanBeChanged
> (C:\Users\Pa\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\....:45)
>    at async Note.batchDelete
> (C:\Users\Pa\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\....:17)
>    at async permanentlyDeleteOldItems
> (C:\Users\Pa\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\....:5)
>    at async setupAutoDeletion
> ...
> ```

This happens when Joplin attempts to remove old read-only items from the trash on startup.

In particular, the error is happening here:

https://github.com/laurent22/joplin/blob/24542ca4048baba7a2eb4cef32fe2d5e0139e9bc/packages/lib/services/trash/permanentlyDeleteOldItems.ts#L23

`permanentlyDeleteOldItems` calls `Note.batchDelete`, which calls `BaseItem.batchDelete`, which calls `checkIfItemsCanBeChanged`:

https://github.com/laurent22/joplin/blob/24542ca4048baba7a2eb4cef32fe2d5e0139e9bc/packages/lib/models/BaseItem.ts#L311

This then throws a `JoplinError` because one of the items is read-only:

https://github.com/laurent22/joplin/blob/24542ca4048baba7a2eb4cef32fe2d5e0139e9bc/packages/lib/models/utils/readOnly.ts#L45

### Expected behaviour

Joplin should not try crash on startup.

**Comment by personalizedrefrigerator** [comment]
**Update**: This may not affect mobile &mdash; `setupAutoDeletion` is currently [only called in `BaseApplication`](https://github.com/laurent22/joplin/blob/24542ca4048baba7a2eb4cef32fe2d5e0139e9bc/packages/lib/BaseApplication.ts#L883), which is not used on mobile.

**Comment by CoffeeHT** [comment]
@personalizedrefrigerator 
> closed this as [completed](https://github.com/laurent22/joplin/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in [9c4142f](https://github.com/laurent22/joplin/commit/9c4142fcd23c655215c2dacb241a68ccd5618cfd)

Hmmm...
Maybe I should take the brave step of trying a prerelease for the first time. So far, I've only used the ‘normal’ versions that were automatically offered to me – currently still Joplin 3.1.24 (prod, win32)
From your point of view, is there anything wrong with me installing V3.2.6 from https://github.com/laurent22/joplin/releases/download/v3.2.6/Joplin-Setup-3.2.6.exe?
 That is the Windows version, isn't it?

**Comment by CoffeeHT** [comment]
I have installed this version.
The profile started was that of a basic user who only has read-only rights to my shares. 
He got the error message:


>Remote-Elemente aktualisiert: 1.
Abgeschlossen: 2025-01-04 18:58 (1s)
Letzte Fehlermeldung: **Sync target lock error: syncLockGone. Original error was: user does not have write access to this share**
Anhänge abrufen: 3/5437


Joplin 3.2.6 (prod, win32)

Client-ID: xxx
Sync-Version: 3
Profil-Version: 47
Unterstützter Schlüsselbund: Ja

Revision: 40914be

Backup: 1.4.2
Conflict Resolution: 1.2.3
Diff view: 0.1.0
Freehand Drawing: 2.13.0
Joplin debug tool: 0.2.0
