### ISSUE TITLE
MD export doesn't have source URL

### ISSUE THREAD

**Issue by fastlorenzo** [laurent22/joplin#1146]
### Operating system

- Windows (Joplin 1.0.120 prod,win32)

### Application

- Desktop

When exporting a note in MD, the source URL information is lost (for clipped content). This should be added somewhere (ex: a comment in the MD exported file or a link at the bottom).

**Comment by laurent22** [comment]
To export metadata, you can use the RAW format. MD only exports title and body.

**Comment by fastlorenzo** [comment]
Well, it might be interesting to have this new feature then. Not sure how complex it would be to implement?
If you could point me in the right direction I could maybe make a PR

Lorenzo Bernardi

**Comment by laurent22** [comment]
Hmm, well MD export just exports Markdown, that's the goal of the feature. If we add metadata like the source URL, there's no reason we shouldn't add all the remaining metadata, and in that case it becomes like a RAW file, so that's why I'm pointing to this export option.
