### ISSUE TITLE
Can't get terminal to install via command line

### ISSUE THREAD

**Issue by larissa-k** [laurent22/joplin#1147]
### Operating system

- Windows

### Application

- Terminal

---

I'm trying to get Joplin syncing with Nextcloud; based on the documentation it looks like I need to install Joplin's terminal app next. However, every time I try I get the following error:
`'NPM_CONFIG_PREFIX' is not recognized as an internal or external command,
operable program or batch file.`

I also tried the npm command but got an error; I don't have git installed.

node version is 10.15; npm version is 6.4.1.

**Comment by tessus** [comment]
I'm not following. Why are you not using the Windows application? Why do you want to install the terminal app?

Also, npm install does not require git. Unless you are using a node version which is not the one that was used to build the app, which means part of the libs might have to be recompiled and for that you need a build env that has access to git and a c compiler. Although most libs should download a tarball and not use git. Anyway, I'm not a Windows person, maybe someone with Windows experience can help you out here.
