### ISSUE TITLE
Desktop: Bold or italic text in checklists have weird formatting in markdown viewer

### ISSUE THREAD

**Issue by mrjo118** [laurent22/joplin#11478]
### Operating system

Windows

### Joplin version

3.2.3

### Desktop version info

Joplin 3.2.3 (prod, win32)

Client ID: 6cfb4e5a34d04a73aeea629e561b4dd6
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 1993d30

Backup: 1.4.2

### Current behaviour

When bold or italic text is included in a checklist item, the formatting looks weird in the markdown viewer
![bug1](https://github.com/user-attachments/assets/f6bedaf4-6b07-4933-82de-7624cf14dfaa)

This is not the case in the rich text editor
![bug2](https://github.com/user-attachments/assets/a383f902-5f6d-4a6e-a18f-0a5cebab46ae)

### Expected behaviour

The formatting of the markdown view should look the same as on the rich text editor for the checklist item

**Comment by personalizedrefrigerator** [comment]
This should be fixed by https://github.com/laurent22/joplin/commit/9373c334b3b1b9481710d2e9189639c664472077 (not currently included in a release).

See https://github.com/laurent22/joplin/issues/11425.
