### ISSUE TITLE
cannot copy text from vim to joplin

### ISSUE THREAD

**Issue by chinmayrozekar** [laurent22/joplin#11487]
### Operating system

Linux

### Joplin version

Joplin 3.1.24 (prod, linux)

### Desktop version info

Joplin 3.1.24 (prod, linux)

Client ID: e892a318eb924d3b8a7941f047ef741a
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: d581264

Backup: 1.4.2
Favorites: 1.3.2
Inline tags: 1.3.0
Quick Links: 1.3.2

### Current behaviour

1. Open a .txt file in vim 
2. Go to Visual mode to copy the first 2 lines and yank them, with yy
3. now if you try to paste it in Joplin the paste doesnt work. I tried Ctrl V, Ctrl + Shift + V as well, no luck.

### Expected behaviour

Paste the text in Joplin

**Comment by personalizedrefrigerator** [comment]
Does paste from Vim work in other apps (e.g. Firefox & Chrome)? If not, be aware that clipboard access [may not work with some distributions/builds of Vim out of the box](https://stackoverflow.com/a/11489440).

**Comment by chinmayrozekar** [comment]
Ok Community, this is what worked for me, so I have documented this for future users:

![image](https://github.com/user-attachments/assets/c8d0179b-9518-45c5-9fe2-b93df3cb0e97)

**Comment by personalizedrefrigerator** [comment]
I'm closing this as "not a Joplin bug".

**Comment by chinmayrozekar** [comment]
Ok. Can you add this somewhere in the official documentation?
It took me a while to figure this out.
Thanks
Chinmay
