### ISSUE TITLE
The whole window renders incorrectly after exiting while maximized

### ISSUE THREAD

**Issue by jh05013** [laurent22/joplin#11481]
### Operating system

Linux

### Joplin version

3.1.24

### Desktop version info

Joplin 3.1.24 (prod, linux)

Client ID: a57757ba6afa47e689e4ab7eab8d8171
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: d581264

Backup: 1.4.2
Emoji: 1.0.4

### Current behaviour

Whenever I exit Joplin while the window is maximized, and then turn it on again, the whole window renders incorrectly. Furthermore, the window does not appear on the task bar, and all other windows including the start menu gets hidden behind the Joplin window.

![image](https://github.com/user-attachments/assets/609a9877-bdcf-477c-b476-97c33ed9c2de)

The 2 only ways I've found to exit it again are:
1. click the top left corner (where "File" would normally be in) and click "Quit". This method doesn't work sometimes because the menu instantly closes.
2. ctrl+Q.

OS: Linux Mint 21.3 Virginia (MATE Desktop Environment)

The same issue was reported in #9657, which was closed due to inactivity.

### Expected behaviour

The window should render correctly.

**Comment by jh05013** [comment]
Closing since it's going to be closed as "stale" anyway, and I moved on to a different software.

**Comment by alecov** [comment]
What a joke of support, honestly. This bug has been here for almost two years at least, and nobody gave a single passing glance over it.
