### ISSUE TITLE
Pressing decision while entering a title in multibyte removes focus from the title. Can this be improved?

### ISSUE THREAD

**Issue by sasaki-kouhei** [laurent22/joplin#11485]
### Operating system

macOS

### Joplin version

Joplin 3.1.24 (prod, darwin)

### Desktop version info

Joplin for Desktop

Copyright © 2016-2024 Laurent Cozic
Joplin 3.1.24 (prod, darwin)

クライアントID: 74a7f9253411489c93054e68733fa522
同期バージョン: 3
プロファイルバージョン: 47
キーチェーンのサポート: Yes

リビジョン: d581264

Backup: 1.4.2
Kanban: 1.0.7
Kminder Mindmap: 0.8.6
Markmap: 1.6.0
OCR: 0.3.2

### Current behaviour

1. Pressing decision while entering a title in multibyte removes focus from the title.

### Expected behaviour

Expect that pressing Enter while typing a title will not cause it to lose focus.

**Comment by personalizedrefrigerator** [comment]
I can reproduce this with the "Japanese - Romaji" input method on MacOS Sequoia.
