### ISSUE TITLE
Native app for SailfishOS

### ISSUE THREAD

**Issue by tobru** [laurent22/joplin#115]
It would be great to see a native application of Joplin for [SailfishOS](https://sailfishos.org/)

**Comment by laurent22** [comment]
Do you have access to a SailfishOS device? If so could you try if one these APKs are working on it? https://github.com/laurent22/joplin/issues/15#issuecomment-348815711

If one of them do, I could setup something to automate releasing APK files on GitHub.

**Comment by tobru** [comment]
Yes, I have. Will test the APK and let you know...

The idea of this issue is to find a way to have a native application, not an Android one. But I could imagine that this is not easy as native Sailfish apps are coded in C++.

**Comment by laurent22** [comment]
Right, most likely that won't be possible since the app would have to be re-developed from scratch. The advantage of using Javascript is that the same code can be shared between the CLI, Electron and React Native apps.

**Comment by tobru** [comment]
I gave `app-x86-release.apk` a try on my Sony Xperia X with Sailfish X but the app doesn't start. Maybe because this device has a 64-Bit architecture?

**Comment by laurent22** [comment]
I've accidentally put twice the same APK in the linked post. Could you try with the ARM one? Since it's a much more common Android architecture, it's possible that Sailfish is compatible with this one:

https://github.com/laurent22/joplin/releases/download/v0.10.35/app-armeabi-v7a-release.apk

**Comment by tobru** [comment]
Yes, this one works. Feel free to close this issue as most probably there won't be a native SailfishOS app of Joplin in the near future as I understand.
