### ISSUE TITLE
Discussion: Suggestion for new Pull Request Template

### ISSUE THREAD

**Issue by matsest** [laurent22/joplin#1150]
Hi, since this is GitHub-related I figured this would be the place to create a post rather than in the forum.

I have a suggestion for a more standardized Pull Request Template which more easily conveys what the nature of the PR is and how it affects the code, as well as makes sure PRs are correctly crafted with respect to the contributing guidelines by using a checklist at the end. 

If it's discussed I'm more than happy to create a PR for it, but it can be left here for discussion as of now as the maintainers probably has some good sense of what is needed and not. Something that should be added? Something unnecessary / too verbose? Should something be restructured?

As I know you are looking into creating tests for various parts of the code, this might change in a bit, but here it is anyways.

* [My suggested template](https://github.com/matsest/joplin/blob/new-pr-template/docs/PULL_REQUEST_TEMPLATE.md)
  * also in raw [here](https://raw.githubusercontent.com/matsest/joplin/new-pr-template/docs/PULL_REQUEST_TEMPLATE.md) for inspecting the comments

**Comment by laurent22** [comment]
Thanks for the suggestion and this kind of PR template could indeed be useful. I guess for things like translation, all this is not needed, but for adding new features it is. The main issue now is that it's difficult for me to review large PR and to understand what impact they will have, whether they'll introduce bugs, how difficult they will be to maintained, etc. Not sure if a PR template could help with this but worth looking into it.
