### ISSUE TITLE
Failed to start after install via brew

### ISSUE THREAD

**Issue by earthday** [laurent22/joplin#1153]
### Operating system

- macOS

### Application

- Terminal

![image](https://user-images.githubusercontent.com/90078/51783000-d3330980-216d-11e9-82ff-6d8b42c875d0.png)

**Comment by tessus** [comment]
Please have a look at this https://github.com/laurent22/joplin/issues/886#issuecomment-431733664

It seems that if the app is build with one version of node it doesn't run on another version of node. This is an upstream issue and there's a bug open with node-sqlite3 https://github.com/mapbox/node-sqlite3/issues/1064

Duplicate of #886
