### ISSUE TITLE
[Feature request] Auto-save upon any change on Android

### ISSUE THREAD

**Issue by Vioner** [laurent22/joplin#1156]
I've been testing Joplin and almost decided to migrate, but then I realized that it doesn't auto-save on Android. 

Would you please add an option to enable auto-save upon change?  
Of course, this feature is most useful when the app keeps track of changes.

**Comment by foxmask** [comment]
did you upgrade and noticed that the behavior is still the same ? 
I did not noticed that at all .

**Comment by themightychris** [comment]
If you start a new note and write a bunch without hitting the save button, and get distracted in another app long enough for Android to background Joplin, your input evaporates. I learned to avoid it after getting bitten a couple times, maybe this is what's being described?

**Comment by laurent22** [comment]
It's done now
