### ISSUE TITLE
Joplin shows blank view of notes when in admin mode

### ISSUE THREAD

**Issue by ANDRmark** [laurent22/joplin#11561]
### Operating system

Windows

### Joplin version

3.1.24

### Desktop version info

Joplin 3.1.24 (prod, win32)

Client ID: a4c380753fc14aa9a92d28b1f844f9d3
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: d581264

### Current behaviour

1. Download a fresh JoplinPortable.exe
On page https://joplinapp.org/help/install/ click on link [Portable version](https://objects.joplinusercontent.com/v3.1.24/JoplinPortable.exe?source=JoplinWebsite&type=New)
2. Launch the  JoplinPortable.exe as Administrator
3. Observe the default Welcome notebook with an empty view pane 

![image](https://github.com/user-attachments/assets/abc2f6c4-f7d3-496e-864b-846c1ee0e8db)

### Expected behavior

The view panel should display the content of the Welcome notebook

UPD
Workaround: run `JoplinPortable.exe --no-sandbox`

**Comment by ANDRmark** [comment]
When run `JoplinPortable.exe --open-dev-tools --debug --log-level debug` then nothing happens.
When added the file flags.txt to the JoplinProfile directory then it seems it does not have effect.

**Comment by laurent22** [comment]
Anything in the console? joplinapp.org/debugging

**Comment by TejasriPacharu** [comment]
![Screenshot (1102)](https://github.com/user-attachments/assets/d5993617-133c-4137-bbd1-d7f39d47f6fa)
Just now downloaded fresh JoplinPortable.exe, for me the notes is displayed twice, ........can you guys share what should actually be seen in the blank part of the screenshot posted by @ANDRmark ???

**Comment by ANDRmark** [comment]
> Just now downloaded fresh JoplinPortable.exe, for me the notes is displayed twice,

This is the expected and desired behavior. The left part is the editor and the right part is the preview panel.

**Comment by ANDRmark** [comment]
Narrowed down the problem.
I was using TotalCommander with admin privileges. I was implicitly launching the JoplinPortable.exe as Administrator.
**This problem does not reproduce when run with lowered privileges.**
It can be closed.

Details
I had a similar problem with VS Code. It was resolved by specifying flags to disable "sandboxing".
https://code.visualstudio.com/docs/setup/windows#_unable-to-run-as-admin-when-applocker-is-enabled
I know that Joplin is similar to VS Code in terms of rendering content.
This problem relates to some "security sandboxing" features.
Found workaround:  run in console like this: `JoplinPortable.exe --no-sandbox`
