### ISSUE TITLE
Feature Request: Import Tomboy Notes

### ISSUE THREAD

**Issue by osprinzl** [laurent22/joplin#116]
### Operating system

- [ ] Windows
- [ ] macOS
- [ X ] Linux
- [ ] Android
- [ ] iOS

### Application

- [ X ] Desktop
- [ ] Mobile
- [ X ] Terminal

It would be nice if I can import my Tomboy notes into Joplin. Would this be possible?
--

**Comment by laurent22** [comment]
A simple way to get the notes into Joplin would be to export them to Evernote (using the method described [there](https://askubuntu.com/questions/243691/how-can-i-export-my-tomboy-notes-into-evernote/608551) for example, but maybe there are other ways). Then you can import them into Joplin as Enex files.
