### ISSUE TITLE
Back button out of reach

### ISSUE THREAD

**Issue by sciurius** [laurent22/joplin#1162]
When browsing the "General options" screen, the top bar scrolls out of reach, so you must scroll back to the beginning top be able to go back.
(When browsing the "Synchronisation status" screen, the top bar with the "<Back" button stays in place.)

### Operating system
- Linux

### Application

- Desktop

**Comment by laurent22** [comment]
Already fixed in next release (actually the back button will be removed and ok/cancel/apply will be sticky at the bottom)
