### ISSUE TITLE
Android application crash when today is selected for alarm.

### ISSUE THREAD

**Issue by qhvuipgp** [laurent22/joplin#1164]
### Operating system

- Android

### Application

- Mobile

On a task, set alarm, if you clic directly on the current day, application crash.
No problem with other days, or if you select another day before selecting today.
Problem with version 1.0.234.

Thanks for this application.

**Comment by foxmask** [comment]
I don't meet that behaviour. Which android version is it ?

**Comment by qhvuipgp** [comment]
Yes, it's an important detail. It's Android 5.0 on a Samsung Note 3, all is a little old.
