### ISSUE TITLE
[Feature Request] Footnote Support

### ISSUE THREAD

**Issue by dometto** [laurent22/joplin#1166]
Are there any plans to include support for markdown [footnote rendering](https://www.markdownguide.org/extended-syntax/#footnotes)?

**Comment by innocuo** [comment]
I'm closing this issue, it looks like @CalebJohn added this feature a couple of months ago. See PR #1347 for reference.

Footnotes is one of many [markdown plugins enabled by default](https://joplinapp.org/#plugins).
