### ISSUE TITLE
Export to HTML

### ISSUE THREAD

**Issue by sciurius** [laurent22/joplin#1167]
Please add a way to export notes to HTML, similar to PDF export.

### Operating system

- Linux

### Application

- Desktop

**Comment by foxmask** [comment]
Fyi ;)

https://discourse.joplin.cozic.net/t/feature-request-pandoc-markdown-with-preview-and-export/1471/3

**Comment by matsest** [comment]
Should still be open - not yet implemented.

**Comment by deciacco** [comment]
This would be very useful for sharing notes on one's own website. I would think it's fairly easy to implement... take what's in the preview layout and save it out to file... with images, in a resource folder of course...

**Comment by tatoosh** [comment]
Export should be done in HTML5 with empedded Images and mermaid Filter.
Typora has already HTML Export and also VSCode Extension markdown-pdf could help developing that Feature.How to help here?

**Comment by karlredman** [comment]
Hi, I'm new to Joplin and just converted 10 years of notes I've managed in a complicated setup involving  Vimwki (markdown format files), a build system, a personal git repository, and Hugo (for web deployment). I'm an avid Vim user for all my editing.

With that said, relative to the topic, one of the most useful plugins for vim markdown editing is the [iamcco/markdown-preview.nvim: markdown preview plugin for (neo)vim](https://github.com/iamcco/markdown-preview.nvim) plugin. 

This plugin provides github flavored markdown, plant-uml, mermaid, Katex and other rendering in a web page that is updated in real-time.

My thinking is that Joplin might be able to tap the concept of this plugin to use as a real-time rendering and export engine.

The only real hitch I foresee is getting the miniserver to deliver note attachments correctly (i.e. images, etc.)

I hope to contribute in the future but for now I thought I'd run this idea by the group.

**Comment by laurent22** [comment]
Implemented in coming version
