### ISSUE TITLE
Desktop (dev): Marker renders spaces in writing mode

### ISSUE THREAD

**Issue by matsest** [laurent22/joplin#1170]
### Operating system

- Linux

### Application

- Desktop

### Description

I built joplin from latest sources (242926d3818f541b3d8c477120fdb3f5dd66a887) and there is some weird going on with the marker:

![joplin](https://user-images.githubusercontent.com/10927304/52051655-16b1bd00-254c-11e9-886e-1f33de7bba62.gif)

Happens in both split view and plain writing view.

No relevant info in the debug console or logs.txt..

**Comment by laurent22** [comment]
The editor is using a regular font but it needs to use a monospace font. Did you change this setting or did it pick a wrong default?

**Comment by matsest** [comment]
You are right... This is from my .config/joplindev so my settings are not updated - I tried using different fonts for a while back. As this is already warned about in the settings, I'll close the issue. It works as intended with a monospace font.
