### ISSUE TITLE
Fix API 500 error

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#1171]
https://discourse.joplin.cozic.net/t/api-error-500/1480

**Comment by foxmask** [comment]
I met other uses cases when `delete` returns an error 500 with the same error message : 

`DELETE /tags/:id/notes/:note_id ` : we can't delete tag for a given note 
`DELETE /folders/:id `: when deleting a folder, error 500 is returned, even if the folder has been dropped 

```
curl -X DELETE  http://127.0.0.1:41184/folders/143ec0716e594ae18ee5e75cb56bcb91?token=xxx
First argument must be a string or Buffer
```

**Comment by laurent22** [comment]
It was happening when the response had no content, but it indeed still was working as expected. It will be fixed in the next release.
