### ISSUE TITLE
Exporting on android and attribution on exported files

### ISSUE THREAD

**Issue by Daniil77177** [laurent22/joplin#1172]
### Operating system

- Android

### Application

- Mobile

## Export on android
How can I export file on android into pdf or html?
When I'll export this and post into some social networks, attribution is required (in comments or in file)?

**Comment by laurent22** [comment]
Attribution is not necessary, but currently you can only export from the desktop app.

**Comment by matsest** [comment]
@Daniil77177  AFAIK export (and import) is not supported on mobile.

If you absolutely need to convert a note to pdf or html on mobile I would recommend using the [Dillinger web site](https://dillinger.io/). 
First, In Joplin, find your note and use Android's built-in share menu to copy to clipboard. Open Dillinger web site and paste the contents. You can export it from the menu there.

**Comment by archont00** [comment]
@matsest: Android does not have a feature "share to clipboard", the user can only select some text area and/or image and copy to clipboard.

I tried Dillinger, but that page did not really worked in Firefox (mobile view) - I could paste the md text and then the web page became non-responsive.

However, even if it worked, I assume there is no way how to get also images rendered.

**Comment by matsest** [comment]
@archont00 I have the option in my ahare menu from Joplin and other apps. Might be different in various versions of Android though. Also, Dillinger works here. But I agree that this is a non-optimal method, including lack of image support. Would be nice to have a default export option in the mobile app.
