### ISSUE TITLE
Needs HTTPS (& deserves own domain, maybe)

### ISSUE THREAD

**Issue by rugk** [laurent22/joplin#118]
So add HTTPS, and, maybe, you could use an own domain or so, instead of thus subdomain.

Why you should always use HTTPS (no matter whether the site is static etc.):
* IT security specialist: https://scotthelme.co.uk/still-think-you-dont-need-https/
* Google: https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

**Comment by laurent22** [comment]
Hello, https cannot currently be enabled due to this issue: https://github.com/isaacs/github/issues/156
