### ISSUE TITLE
Lost notes after sync

### ISSUE THREAD

**Issue by onomori** [laurent22/joplin#1180]
### Operating system

- Windows

### Application

- Desktop

---

So first time trying out Joplin and I might have made some wrong moves here and there.

Imported my Evernote notes and reorganized it in Joplin for quite a bit. Once I was contented, I enabled encryption and then I wanted to try syncing it with dropbox. I followed the instructions in the wiki and for most of the part it worked. At some point it got stuck though and I assume it must have been because of some heavy images (GIFs). Being stupid and impatient, I tried to cancel the sync and then forced it to close when it took time to cancel.

My next attempts to sync it didn't work and was just stuck at "importing 1 item" or something along those lines. I enabled the console but it wasn't throwing any errors to it.

I then decided I'll try the other syncing options for now so I tried the File System as a sync target. I "synced" it into some folder in my drive and it went okay. At some point though I noticed my notes slowly being deleted until none was left.

I tried resyncing it but nothing happened. I then cleared my local data as suggested in #656 and then resynced it with that folder and it started syncing. It completed but no notes/notebooks showed up in the sidebar. Checking the sync status, it says:

Note: 0/0
Folder: 0/0
Resource: 772/772
Tag: 0/0
NoteTag: 0/0
MasterKey: 1/1
Total: 773/773

After that I added the encryption key I used previously but still nothing changed.

Are my notes gone?

**Comment by laurent22** [comment]
Probably you want to start over from a clean state if you saw it delete stuff. Choose in advance how you want to sync and let it finish, even letting it run overnight if needed.

**Comment by onomori** [comment]
So is it safe to assume it's gone? They're not terribly important data but it would be nice to get them back and I've already cleared out the source unfortunately. Are the encrypted files in the `.resources` folder be of any use to me or are they unrelated to the notes altogether?

**Comment by laurent22** [comment]
What's left should be in your local profile directory, in the "resources" directory. To find the path of that profile directory, open the app and go to the Options screen - the path will be displayed on top.
