### ISSUE TITLE
Synchronization of a subset of notebooks

### ISSUE THREAD

**Issue by jbriales** [laurent22/joplin#1183]
I have the following use case:
I have several notebooks, one of them containing only sensitive stuff related to the company I work for.
That sensitive stuff can only live within a corporate Dropbox account for the company, which I can access only from the company computers (desktop, laptop, phone, etc.)

Because of the above, I currently keep ALL notes and notebooks in that same corporate Dropbox account, BUT because of this I cannot access my personal (non-company) notes anymore due to external accessibility restrictions for that corporate Drobpox account.

I would like to synchronize my personal notes so that I can access, modify and sync them back from both my personal and corporate devices.

Any proposals/ideas on how to achieve this, given current Joplin capabilities?
Would it be possible to implement an optional synchronization service to use for a particular notebook only?
I understand the above may be hard to implement in the current design, so I also welcome any working hacks to achieve the requirements explained above :)

**Comment by laurent22** [comment]
Currently that would be the only way unfortunately. Otherwise it would be about adding support for multiple services from the same app (there's a feature request for this already).
