### ISSUE TITLE
Android App, & Sync

### ISSUE THREAD

**Issue by vixwd** [laurent22/joplin#1184]
### Operating system

- Android

### Application

- Mobile

I have been able to sync. and set-up the application with my computer, and not the mobile phone. 

>  Error, Please check the URL, username, password, etc. are correct and that sync target is accessible. The reported error was: 
> Network request failed

I have made the file in Nextcloud, and set it up with the PC and Nextcloud. They sync correctly, and I am using the same information for all the apps. The android app is the only version that is not working. Thanks

**Comment by NJannasch** [comment]
Hi

Can you please add information regarding your configuration inside the android app?
Have you choosen as target Nextcloud and verify that your WebDAV-URL is correct?

**Comment by tessus** [comment]
Please re-open, if you have a bit more information that we can use to narrow down the problem.

**Comment by vixwd** [comment]
Ooff... I wish I had gotten the Notification long ago. >.< 

I am using Android Latest, Moto X4 latest Software. No Root, No ROM. Using Nextcloud Latest, with Vultr LAMP setup Latest, and software for Joplin on Windows/Nextcloud/Android all latest. 

I can resubmit this is it is warranted.

**Comment by tessus** [comment]
@vixwd I'm using Nextcloud myself with Joplin on macOS, Android, and iOS. No problems so far.
If sync on Android doesn't work, it's usually one of 2 reasons: wrong password, wrong WebDAV URL.
What does the log say? You must get some sort of error message.

**Comment by tessus** [comment]
IMO this looks like a user error. Maybe you want to head over to the [forum](https://discourse.joplinapp.org/).
Since I haven't heard back since my last reply, please make sure that the password  and the WebDAV URL is correct. Also, if you use 2fa on nextclouf, you must use an app token - not a password.

**Comment by vixwd** [comment]
How do I find the log to check the error? 
I need to turn on notifications for this site, so I am not getting a message ~20 days after a reply. 
I do not use 2FA, but since this point my server ended up melting down after an update and I have to scrap it for a backup. So I will have to revisit this issue at a later date. 

[Closed]

**Comment by tessus** [comment]
> How do I find the log to check the error?

https://joplinapp.org/debugging/
