### ISSUE TITLE
text has been filled color in no reason

### ISSUE THREAD

**Issue by donaldtone** [laurent22/joplin#1186]
### Operating system

- Windows

### Application

- Desktop

when the "book" is input, it has been filled in color automatic.
![yellow](https://user-images.githubusercontent.com/23021576/52319462-c5fcf280-2997-11e9-997e-471fcb4f7056.jpg)

**Comment by laurent22** [comment]
Did you search for "book" previously? Maybe it didn't clear the search properly?
