### ISSUE TITLE
Cannot copy from rendered Markdown pane

### ISSUE THREAD

**Issue by dddjjjbbb** [laurent22/joplin#1189]
### Operating system

- macOS

### Application

- Desktop

I'm unable to copy text from the rendered view, this seems to be only permitted when doing so from the markdown pane on the left.

![joplin_markdown_and_rendered_panes](https://user-images.githubusercontent.com/10849506/52361645-98b35180-2a36-11e9-80ad-5f6d68a3dc81.png)

**Comment by laurent22** [comment]
What if you select the text, right-click and select "Copy". Does it work?

**Comment by dddjjjbbb** [comment]
Hi, I should have been more clear, my mistake. If you employ: ```cmd + c```the string is not copied to the clipboard. If you right-click it is.

**Comment by laurent22** [comment]
I can't replicate it for some reason. Cmd+C works fine for me. Can you try again and see if the bug is still happening? Maybe it's some bug that happens only under certain conditions?

**Comment by tessus** [comment]
Nope, I have the same problem. `Cmd+C` does not work in the preview pane. 
(Joplin 1.0.125 / macOS)

**Comment by laurent22** [comment]
Weird, I've just tried again and it works for me. You are on v125, right?

**Comment by tessus** [comment]
I have to say that I've noticed this behaviour for quite some time. I can't even remember if it ever worked. I just copied from the edit pane and never opened a bug report. (I thought there are more pressing matters at hand and there are 2 workarounds available, so I pretty much ignored it.)

**Comment by tessus** [comment]
Weird, all of a sudden it works for me as well.

Ok, now I'm slightly confused. I restarted Joplin and it still works. Ok, I will keep an eye out and try to reproduce the issue.

**Comment by laurent22** [comment]
I wonder if it's specific to a particular note. If so, if it's happening consistently for any of you on a particular note, please could you post the markdown here?

**Comment by brad-safetonet** [comment]
I've seen this issue, but I'm finding it to be inconsistant. It wasn't copying the selection for me, but then I tried clicking some different notes on the side-bar, and then it started working. I'll see if I can find some procedure to replicate the issue.

**Comment by dddjjjbbb** [comment]
Actually, this issue seems to be intermittent for me too. I'll also see if I can recreate consistently. Will post markdown thereafter.

**Comment by brad-safetonet** [comment]
I got Joplin into this strange state again for a while. I tried copying and pasting with CMD-C about 20 times, and it never successfully copied the text that I had selected (I pasted into a text editor each time and didn't get the selected text). After a while, I tried selecting a bit of text and choosing **Edit -> Copy** and that didn't work either. Going back and forth between these two methods of copying continued to fail several times. However, I did eventually try something that might provide a clue. I selected a bit of text, right-clicked and chose the **Copy** item from the context menu. That worked normally! After I did that once, everything seemed to start working again. As soon as I copied with the context menu just once, then CMD-C started to work as expected again. Hope this helps.

**Comment by dddjjjbbb** [comment]
I can confirm this behaviour on my side too. On startup I'm unable to copy using CMD-C, only after right clicking via the context menu and copying is copying made available via the keyboard.

**Comment by innocuo** [comment]
I can't reproduce this issue on MacOS 10.13.6, Joplin v1.0.160. Can anybody confirm?

I see that Electron was updated from v4.0.5 to v4.1.4 in April, and there were significant changes in the markdown renderer in March, maybe that fixed this issue?

If you can reproduce the bug, try using the Top Menu Edit>Copy to see if that works (in theory that's the same as using the keyboard shortcut). 

Note that the menu and keyboard shortcut let Electron handle the copying, while the context menu explicitly adds the text to the keyboard. This kinda indicates it's an Electron issue. [They've already had a similar issue in the past](https://github.com/electron/electron/issues/16338). And it seems [they still have MenuItem issues in v5](https://github.com/electron/electron/issues/18745).

**Comment by tessus** [comment]
It currently works for me, but the issues were intermittent and not easy to reproduce.
I will keep an eye out. I got used to copying from the edit pane, but I will remind myself using the preview pane.

**Comment by PRASHANT1104** [comment]
closely related to this so posting here, pressing cmd-f does not take me to search and rather gives an error in console . I am not sure , whether this is intended ? Is it a bug ?

**Comment by tessus** [comment]
@PRASHANT1104 you have to be more specific. What is the error message?

**Comment by PRASHANT1104** [comment]
@tessus .Uncaught Error: HACK: Overriding Ace Editor shortcut: Ctrl+F

**Comment by tessus** [comment]
No bug. `HACK: Overriding Ace Editor shortcut: Ctrl+F`

The Ace editor has it's own shortcuts. To make them available to the app, there's this hack.

**Comment by PRASHANT1104** [comment]
@tessus .I seem to be missing something here . I looked into the code and saw this error is ought to throw when F,t,p,q,l,,g,k are pressed with Cmd and Ctrl . I also looked into the Ace keyboard shortcut , cmd-f is mapped to find . So , why are these keys marked as cancelled keys in the code ? Isnt cmd-f supposed to search/find ?

**Comment by tessus** [comment]
Yes, i's mapped to the find in Ace Editor. We use `Cmd+F` or `Ctrl+F` to make a local search, which is not done in the editor, but in the preview pane. Thus it has to be overriden.
The problem is that the Ace Editor does not allow to re-map or unmap keys, therefore the hack. I think there's an explanation in the code.

**Comment by att14** [comment]
What about the other keys mentioned in #2601?

**Comment by laurent22** [comment]
Can someone still replicate this bug or should we close the issue? Many things have changed since so it's possible the bug is gone.

**Comment by anihm136** [comment]
I'm able to copy from the viewer pane using `Ctrl-C`on Linux Desktop `1.0.195`. I think it should be resolved.
