### ISSUE TITLE
[Feature Request] - free flow organizationing notes/notebooks

### ISSUE THREAD

**Issue by smokinjo** [laurent22/joplin#1191]
Joplin automatically organizes notebooks in alphabetical order.   It also separates notes and notebooks when organizing so that the can not be mixed up.

Can the automatic notes and notebooks organization be dropped and allow the user to organize the notes and notebooks in any order they want?

My notes and ideas are not in alphabetical order.  So, being forced to do it this way does not allow the user to organize the notes and notebooks according to their style or manner of arranging them.

Thanks

Joseph

**Comment by laurent22** [comment]
There's a feature request for this. Although not ideal, the current workaround is to start the notes with a number (10, 20, 30, so that you can also insert notes) and sort them by name.
