### ISSUE TITLE
REQUEST: Windows - Remember which note was selected when switching between notebooks

### ISSUE THREAD

**Issue by strantheman** [laurent22/joplin#1192]
- Windows
- Desktop

Its just that simple, I think the app was designed to mirror functionality in other apps where users would swap between notebooks often. When I do this it always picks the first note at the top, but I'd expect it to have opened the last note I had open on that computer.

**Comment by laurent22** [comment]
Already done, and will be available in next release.

**Comment by strantheman** [comment]
Nice! Yep seems to be working.
