### ISSUE TITLE
Code snippets clipboard

### ISSUE THREAD

**Issue by noklam** [laurent22/joplin#1193]
It would be much handy if there is a copy to clipboard button for code snippets. It saves a lot of copy and paste efforts.
![image](https://user-images.githubusercontent.com/18221871/52427140-570bcf00-2b3a-11e9-91cf-1948580a2e78.png)

### Operating system
- Windows
- macOS
- Linux

### Application

- Desktop

**Comment by claudiospizzi** [comment]
I've a lot of code snippets in my Joplin notes too, so would love to see this copy button. Maybe only show the button while the mouse is over the source code box, too still have a clean view?
