### ISSUE TITLE
Check why desktop app is so slow to do initial rendering of note

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#1196]
![](https://i.imgur.com/0Dy8Thd.gif)

**Comment by TobiasDev** [comment]
Is that part of the markdown render update? It looks good. I'm excited about this update!

**Comment by laurent22** [comment]
Yes that's the new Markdown rendering. But while doing some clean up on the way notes are loaded, I've noticed that it's surprisingly slow to switch from one to another so this is what this bug is about.
