### ISSUE TITLE
Lost Notes - corrupted database row

### ISSUE THREAD

**Issue by derekwsgray** [laurent22/joplin#1197]
### Operating system

- Linux (Mint 19)
- Android

### Application

- Desktop
- Mobile

### Incident

Unfortunately, I create a new development log note at the beginning of each month, so losing my two most recent notes cost me all of Jan and Feb so far. 

I sync with Dropbox

I have no explanation for what happened, I just started my machine yesterday and instead of my full list of notes, the most recent 2 notes were replaced with a blank note (title blank on Desktop, and on Android the title showed "undefined".
After exhausting all other avenues to recover, I looked in the .config/joplin-desktop sqlite database, and indeed the last row of notes had a blank title and content.

Dropbox - showed the same state - there were no .md files there for Jan/Feb files and no "deleted" files showed up when selecting toggling the view in the Dropbox webpage.

No relevant errors in log.txt or log-database.txt.  Though curiously the log indicates that as of January there were 13 notes - no indication of a 14th note created or saved at the beginning of February.

Unfortunately I can no longer trust this to my important daily log and meeting notes :(

**Comment by laurent22** [comment]
Hmm, no idea what happened to be honest. If it's a corrupted database, it could be a hard drive failure, which no software can protect against. I don't 100% trust Joplin either, nor any software really, I just make regular backups. In case of db error or network errors, the sync process is designed to retry later and normally it cannot commit any invalid data to the db, nor to the sync target.

I assume you don't have a backup of this data? If not, can't you recover the file using Dropbox (as mentioned there https://www.dropbox.com/help/security/recover-deleted-files-folders ). You can find the file you need by searching for the note ID, so the file would be something like "abcd1234......md".

**Comment by subi54** [comment]
@laurent, I'm curious how often do you backup? Once a week? Can this be made into a feature? Regular backups on both the service one of using and local drives (desktop only) at regular intervals of time?

**Comment by derekwsgray** [comment]
@laurent22 Yeah, could have been a bad write during a shutdown. This machine _is_ getting long in the tooth. As mentioned above in this bug report, I already tried to find deleted files in Dropbox and none existed. I am suspecting the last two were perhaps never actually sync'd with Dropbox for some reason?

As it happens, no lie, I was literally upgrading my other/desktop machine that makes cloud backups over the same two days - this happened at exactly the unluckiest time possible. ;) (And I don't have timeshift running on my home directory on this laptop because it doesn't support backing up _just_ hidden files when home directories are encrypted...)

Just wanted to report this in case someone could make something more out of it. It did seem pretty strange there were no log errors, as well the notes count in the log seemed wrong, and there were no deleted files in Dropbox (which should be keeping 30 days worth even on free account.) So still a bit of head-scratching. I can't rule out that it stopped synch'ing 5 weeks ago.

**Comment by laurent22** [comment]
> @laurent, I'm curious how often do you backup? Once a week? Can this be made into a feature? Regular backups on both the service one of using and local drives (desktop only) at regular intervals of time?

You can simply do a regular backup and include the Joplin profile as part of that backup. For more advanced backup, there are some examples of cron on the forum, with git versioning and so on. Making it part of the app would be a bit overkill I think.

> Just wanted to report this in case someone could make something more out of it. It did seem pretty strange there were no log errors, as well the notes count in the log seemed wrong, and there were no deleted files in Dropbox (which should be keeping 30 days worth even on free account.) So still a bit of head-scratching. I can't rule out that it stopped synch'ing 5 weeks ago.

Yes this is quite strange, I don't quite understand how it could do this and not give any error.
