### ISSUE TITLE
Suggestions for the new styling

### ISSUE THREAD

**Issue by TobiasDev** [laurent22/joplin#1201]
Hello! 
I've gotten your latest pre-release and I'm liking this direction a lot. It is easier to read the formatted note, 
esp. the tables! If it's okay I also have some suggestions. These are just personal thoughts for the design, so if it doesn't follow your idea for Joplin just ignore them. :)

**Markdown formated text**
I can change the text size of the markdown side, but I can't change the font size on the formatted side. I would love to have this ability because I just feel like the current size is too big. I'm not sure if it has size 13 or 14 currently?

**Headlines**
If possible, could you add a bit more variation to h2, h3 and preferably also h4 (I wrote very long journals and it's not rare that I'm using h4 in these)

**Todo's**
For the Todo's I feel like it is a bit much that they have a dot in-front of them. It would be enough with the check-box, so could we remove the dotted list in-front of the todos?

**Tables**
Adding an effect when you hover over a row. This would make it a lot easier in large tables to be able to follow a selected one.
 
**Code**
Make this stick out a bit more. Maybe have a dark background for the code rather than a very light, and adding numbers. So you have the 1. 2. 3. stuff on the side. 

Thanks for an amazing tool! I look forward to the future of this tool! 
// Tobias

**Comment by subi54** [comment]
I concur with @TobiasDev.

* Even with userstyle.css, font size doesn't go below 12 afaik.
* The other Headings could use a bit of your new styling jazz too @laurent22.
* I don't mind Todo's bullets but they are a bit big for me with the new styling, maybe they are relative to the font size.
* Tables with hover color would be better rather than having default color. Or could someone tell me how to get back the plain table back? I don't mind the header color though.

**Comment by laurent22** [comment]
Most of these can be done with userstyle.css or using the zoom config option. For the font size, I think `body { font-size: 10px; }` should change the size of all the text.

For the bullets before the checkboxes, it's strangely difficult if not impossible to do this with plain CSS (and I don't want to use JS for this), so that's why it isn't done. If someone has some idea of CSS that could be used, I'll take it.

I've added row highlighting, which is indeed useful.

**Comment by TobiasDev** [comment]
> 
> 
> Most of these can be done with userstyle.css or using the zoom config option. For the font size, I think `body { font-size: 10px; }` should change the size of all the text.
> 
> For the bullets before the checkboxes, it's strangely difficult if not impossible to do this with plain CSS (and I don't want to use JS for this), so that's why it isn't done. If someone has some idea of CSS that could be used, I'll take it.
> 
> I've added row highlighting, which is indeed useful.

Thanks! Where is the userstyle.css? Or do I need to build it myself to change that one? 

and I know you can remove the dots in-front. I have done it... but it was a while ago (with CSS), let me check and I'll come back with a pull request if I can remember it. :) 

Which CSS file is it I need to work in to test that?

**Comment by subi54** [comment]
@laurent22 I tried `body { font-size: 10px; }`. The default style is overriding font size. I can't go below 12px. Nothing changes. And yes, I restarted the app.

**Comment by TobiasDev** [comment]
@laurent22 I can't seem to find what the checkbox get's for value. It is part of the ul, but I can't find what I need to type to change the base of that one. Eg. ul.checkbox doesnt work. Do you happen to know what it is called? I tried debugging, but I can't seem to debug details in the markdown render but only the full "page". 

Because it must be called something in the list as far as I know.

**Comment by laurent22** [comment]
The HTML is something like this:

```
<ul>
	<li>
		<p class="checkbox">[ ] My todo<p>
	</li>
</ul>
```

The question is: with CSS, how to remove the bullet for LIs that contain an element with a "checkbox" class, but leave it for those that don't?

**Comment by TobiasDev** [comment]
Hmm. Right. I thought it would be <ul class=checkbox> or something like that. Because if that was the case it would just be possible to do `ul.checkbox{ list-style-type: none }` 

Would it be possible to add a class to the UL for the checkboxes? So they have their own class rather than using the default styling?

**Comment by TobiasDev** [comment]
I should probably try and learn how this works, and where lists, bold, etc. are created. Then I could look into this more myself. But like I said, first time ever in react, sooooo will take a bit longer. :D

**Comment by laurent22** [comment]
> Would it be possible to add a class to the UL for the checkboxes?

I'd like that too ;) Unfortunately it's a bit tricky. At the moment, the UL is built the parser doesn't know the list contains a checkbox or not. That's why it's surprisingly complicated to style this right.

**Comment by laurent22** [comment]
> I should probably try and learn how this works, and where lists, bold, etc. are created. Then I could look into this more myself. But like I said, first time ever in react, sooooo will take a bit longer. :D

Most of the code is in MdToHtml.js and it's pure Javascript, no React.

**Comment by TobiasDev** [comment]
> > I should probably try and learn how this works, and where lists, bold, etc. are created. Then I could look into this more myself. But like I said, first time ever in react, sooooo will take a bit longer. :D
> 
> Most of the code is in MdToHtml.js and it's pure Javascript, no React.

Oh, cool. I'll have a look and see what I can find. :)

> > Would it be possible to add a class to the UL for the checkboxes?
> 
> I'd like that too ;) Unfortunately it's a bit tricky. At the moment the UL is built the parser doesn't know the list contains a checkbox or not. That's why it's surprisingly complicated to style this right.

Ah, hmm, that explains that part.

**Comment by CalebJohn** [comment]
@subi54 you should be able to clear the the row colouring using

```
td {
    background-color: white;
}
```
