### ISSUE TITLE
disable crashlytics on android by updating the AndroidManifest.xml

### ISSUE THREAD

**Issue by joergister** [laurent22/joplin#1202]
### Operating system

- Android

### Application

- Mobile

As https://reports.exodus-privacy.eu.org/en/reports/56011/ shows, the crashlytics tracker is enabled by default. I don't think this was on purpose (if I'm wrong about that, please correct me and just close this issue), but is due to the fact, that you use an sdk that enables it by default.

Crashlytics can be disabled by adding 
`<meta-data android:name="firebase_analytics_collection_deactivated" android:value="true" />`
to the 

> AndroidManifest.xml

I can open a pull request which contains just this one change if you'd like

**Comment by laurent22** [comment]
Normally Firebase will be completely removed from the next release. I really dislike these "somethinglytics" so I hope it's gone now but will need to be checked in the next version.

**Comment by joergister** [comment]
oh sounds great. 
will check when the next version is available. 
If its not removed then I will notify you.

**Comment by alexara** [comment]
You can definitely completely remove the Firebase Analytics libraries as follow: https://github.com/nextcloud/talk-android/commit/24626ba2dda4f1f6e617aa2ae2ebbcf9ce5b7e6c :)
