### ISSUE TITLE
DOT graph support

### ISSUE THREAD

**Issue by raddessi** [laurent22/joplin#1208]
Hi, first off I want to say thank you. I love Joplin so far, I'm switching over from Zim since after using that for the last 8 or so years I wanted something more up to date and found Joplin as the tool best suited for my needs. So thank you for the work! It's great :)

Have you thought about adding DOT graph (or any other type of relationship graphing) capability to joplin? I don't see any open/closed issues about this yet.

**Comment by laurent22** [comment]
There's an issue for another graphing lib but I forgot the name. Not sure about DOT - is there a Markdown plugin for it?

**Comment by raddessi** [comment]
Unfortunately I don't think so, most implementations I've seen (only a few) just grab the dot code and send it through graphviz to generate the image themselves. I'm not too familiar with markdown plugins themselves but on a quick search I didn't see anything. If I find something I'll post here

**Comment by raddessi** [comment]
There is the [remark-graphviz](https://github.com/temando/remark-graphviz) project but that hasn't been updated in a while and I don't think that is what you mean by plugin correct?

**Comment by tessus** [comment]
@raddessi Joplin uses markdown-it

**Comment by raddessi** [comment]
I don't think this would be an easy task, I can't find anything that would be a drop-in for it :/

**Comment by tessus** [comment]
@raddessi I will try to add back mermaid support, which is similar to dot graph. As mentioned [earlier](https://github.com/laurent22/joplin/issues/163#issuecomment-489394102) this is not as straightforward.

**Comment by charlesdaniels** [comment]
I too would like this feature. I ran across [Dagre](https://github.com/dagrejs) which might be of interest? It supports DOT notation and is all client side. Their [demo](https://dagrejs.github.io/project/dagre-d3/latest/demo/interactive-demo.html) would appear to be fairly compelling. Sadly it does not have a markdown-it plugin. I'm not sure how difficult that would be to implement.
