### ISSUE TITLE
Android app: slowing down on edit

### ISSUE THREAD

**Issue by dayfuaim** [laurent22/joplin#1209]
### Operating system
- Android

### Application
- Mobile on tablet

App slows down when in edit mode proportional to size of note: the bigger – the slower.

Device: Acer A3-A40, Android 6.0
**Joplin 1.0.236**

**Comment by Araly** [comment]
I'll add on that, using
- android
- mobile application (phone)
- Moto G4 (athene)
- Joplin 1.0.252
- Android 7.1.2 (Lineage OS 14.1-20181031-NIGHTLY-athene)

The app starts fluid and gets slow during edition of notes. There is a noticeable delay between a key press and the letter appearing. Closing the app and coming back to the note fixed the issue for maybe a minute before the incremental slow down becomes noticeable again.

On short notes it doesn't seem to happen (or I don't notice it), but it gets noticeable once the note starts having some good amount of text in it. Let me know if you want me to test some things

**Comment by nr458h** [comment]
#metoo on lineage os 16 on an oneplus 5t with Joplin 1.0.281

**Comment by dayfuaim** [comment]
Yeah.
It's STILL THERE 1.0.281. :(

**Comment by m-p-3** [comment]
My phone becomes slower and slower when I use this app, and the only way to fix it is to reboot..

**Comment by nr458h** [comment]
I still face this problem - so please go away Mr Stale

**Comment by dayfuaim** [comment]
Problem is still here.
Good morning, Mr. Stale.

Joplin 1.0.308 @ Samsung Tab S5e

**Comment by henrebotha** [comment]
New user, experiencing the same. TA-1033 running Android 9. I have a note whose word count is maybe in the low thousands, and editing it is so painful as to be completely impractical.

**Comment by davidpoza** [comment]
I'm also suffering this problem. My device is a xiaomi a1, android 9. I hope React Native fixes it soon.

**Comment by seth100** [comment]
Same to me. Android Lineageos 16. Joplin v1.0.316

**Comment by seth100** [comment]
Same to me. Android Lineageos 16. Joplin v1.0.316

**Comment by seth100** [comment]
Same to me. Android Lineageos 16. Joplin v1.0.316

**Comment by erichiller** [comment]
Same here, Samsung S8

**Comment by dpoza** [comment]
For me it's been fixed.
Joplin 1.0.329
Android 9 april update
xiaomi a1

**Comment by virtadpt** [comment]
I've still been kind of gunshy about it lately.  I'll give it a try in a bit and see what happens.

**Comment by henrebotha** [comment]
It's _kind of_ fixed. I'm using a Samsung S10 to edit a note that is about 4.4k words long, and there is a noticeable latency when typing. It's usable, but I worry that a lower-spec device editing a longer note might become quite unusable.
