### ISSUE TITLE
Losing Changes when sync occurs while active editing of notes. 

### ISSUE THREAD

**Issue by tggrissom** [laurent22/joplin#121]
### Operating system

- [ ] Windows
- [ ] macOS
- [ x ] Linux
- [ ] Android
- [ ] iOS

### Application

- [ x ] Desktop
- [ ] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---
I have noticed this several times while editing a document, Part of my changes are lost. It seems to happen after a sync to cloud. 

I also noticed that 'Conflict' version of the document appear. I am not editing this document on the other instances I have installed so there should not be any conflict.

I will close the app on my mac an iphone to see if this stops the issue.  But this should not happen.

**Comment by braynebuddy** [comment]
I'm finding the same thing happens on the Windows desktop version as well as the Linux desktop. (v0.10.39). It's harder to tell, but I think Android is doing something similar.

**Comment by alexdevero** [comment]
I have the problem, with "Conflict" version of the document, even though I am working only on one device at the time. Could there be an option *disable sync after every edit or change*? I already set the "Synchronization interval" option to "Disabled". That didn't help.

### Operating system

- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

**Comment by laurent22** [comment]
Yes this is big annoyance on the desktop app - I'm planning to remove the auto-saving feature and make it a manual save as that should work much better (like on the mobile and terminal apps).

**Comment by laurent22** [comment]
Ok I think I've finally fixed this annoying race condition in 78ce10ddf08ed400f4f4537c41d602a34f074701. It will be part of the next release.

**Comment by laurent22** [comment]
Closing this as the next version should fix it.
