### ISSUE TITLE
korean support issue.

### ISSUE THREAD

**Issue by cybertramp** [laurent22/joplin#1210]
### Operating system

- [x] Windows 
- macOS
- Linux
- Android
- iOS

### Application

- [x] Desktop
- Mobile
- Terminal

Hi!
I found a korean input bug.
Strange special characters are displayed like this when I type.
Could it be an UTF-8 encoding problem?
Please check this bug.

![Alt text](https://i.ibb.co/VqnL532/tt.gif)

Thank you for providing a good program.

**Comment by thereblight** [comment]
I'm having the exact same issue with Joplin 1.0.127 on Windows 10 and Kubuntu 18.04 with Plasma 5 DE. (FYI, Debian Buster with Xfce doesn't have this issue.) And this happens on the editor area only. On the search box or the note title box, Korean input works without any glitch.

As I understand it, The note edit area in Joplin is embeded Ace editor. So I tested it on the Ace editor demo site(https://ace.c9.io/build/kitchen-sink.html), and Korean input works as it should. So maybe this issue ocurrs in the course of implementing the editor to Joplin.

I assume that CJK issues like this is quite low in priority and I understand that, and this doesn't make the app totally unusable, but to a Korean user like me this is quite an annoying show stopper. I hope that it's dealt with someday.

**Comment by Icy-Breath** [comment]
I have the same issue on Windows 10 while it works fine on Linux Mint 19 (Cinnamon desktop).

**Comment by Icy-Breath** [comment]
Problem still exists.
