### ISSUE TITLE
Joplin 1.0.127.AppImage - Electron App fatal error

### ISSUE THREAD

**Issue by mhdry** [laurent22/joplin#1215]
### Operating system

- Linux (Ubuntu 18.04, 64 bit)

### Application

- Desktop

The AppImage for `Joplin 1.0.127.AppImage` was built following the instructions in `BUILD.md`. The application will ask whether the launcher in `~/.local/share/applications` should be installed. After that, it crashes with the following message:

````
Electron App fatal error:
TypeError: this.electronApp_.makeSingleInstance is not a function
    at Promise (/tmp/.mount_JoplinwLPEq6/resources/app/ElectronAppWrapper.js:195:45)
    at new Promise (<anonymous>)
    at ElectronAppWrapper.ensureSingleInstance (/tmp/.mount_JoplinwLPEq6/resources/app/ElectronAppWrapper.js:194:10)
    at ElectronAppWrapper.start (/tmp/.mount_JoplinwLPEq6/resources/app/ElectronAppWrapper.js:214:37)
````

**Comment by CalebJohn** [comment]
It looks like that function has been [removed in electron 4](https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#appmakesingleinstance) You can probably get the build to work by using an older version of electron. 
That said, I think @laurent22 just started updating to use the newer version of electron, so this should be fixed soon.

**Comment by laurent22** [comment]
Yes I've upgraded from Electron v1 to v4 yesterday so there might be things that are broken on master at the moment. Overall otherwise it seems to work reasonably well. Please keep reporting these kind of issues and we get them sorted for the next release.
