### ISSUE TITLE
So many tags

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [laurent22/joplin#1221]
After updating joplin portable on my windows pc there are so many tags and I'm not able to delete them through the ios application,
Please remove them in the next update.

**Comment by CalebJohn** [comment]
Sorry, just to clarify, you'd like someone else to delete the tags for you? 
In the windows application you can right click on a tag and select delete to remove it. It should take < 1 min for all the added tags.
Hopefully this resolves the issue for you!

**Comment by NginUS** [comment]
I have the same problem on the Android app. Seems there's no way to remove them. They've resulted in the 'Synchronize' button moving to a new place, which caught me off guard the first time.

**Comment by NginUS** [comment]
I followed your instructions & deleted all the tags from in the Windows app. Then when I synchronized the Linux app, they all disappeared.
However, only maybe 2/3 of the tags were removed in the mobile app. Seems there are more there that don't get sync'd to either of the desktop apps to be able to delete them.
Screenshot of what remains:
![android](https://user-images.githubusercontent.com/8769067/52905098-247d6880-3203-11e9-90f6-aea242bf3db0.png)

**Comment by CalebJohn** [comment]
Have you removed the welcome notebook on Android? I don't think you'll be able to remove the tags until you either delete that notebook, or remove the tags from individual notes.

Additionally it looks like your android app isn't syncing correctly with the desktop app, can you confirm that notes created on the mobile app are correctly syncing to desktop?

**Comment by NginUS** [comment]
I was able to delete the Welcome notebook with no issue. However I had already deleted it on the Linux app more than a whole day prior, & it was there to be deleted on Android this afternoon. I know I sync'd Android manually before deleting it- don't know why the sync didn't remove it.
My other notebook appears to be sync'ing properly to the other 2 desktop variants.
Maybe those tags that remain on mobile have something to do with the associated notebook being deleted prior to deleting any tags?
Not sure how I would be able to test that since I no longer have a freshly updated Android app to tinker with...

**Comment by CalebJohn** [comment]
I had a similar issue that the welcome notebook was created on all the devices that use Joplin so I had to delete 3 times. This resulted in me having duplicate tags, which I was able to delete from the desktop application.

Here it seems like those created tags on mobile didn't correctly sync to your desktop application (where they can be easily deleted). Maybe you could try re-syncing all your devices?

**Comment by NginUS** [comment]
At the time when I saw there were leftovers on mobile, I did try sync'ing on all 3 in various orders of who was first, etc.
It's been a couple hours now & although they're all set to 5 minutes I just tried again, to no avail.

**Comment by CalebJohn** [comment]
I'm sorry, I don't know what's going on, maybe @laurent22 has some ideas? It really sounds like there's a syncing bug.

**Comment by laurent22** [comment]
On android and desktop, unused tags should no longer be displayed. If they are please give your os, version number and an example of tag having this problem. On iOS it will be fixed in next release.

**Comment by NginUS** [comment]
Android Version: 7.0 Nougat
Joplin Version: 1.0.237
Relevant Screenshot:
![android](https://user-images.githubusercontent.com/8769067/52907691-74c0ee80-3234-11e9-9849-5c1e61d7d9ed.png)

-----

Linux Version: Mint 18.3 (Ubuntu 16.04 LTS)
Joplin Version: 1.0.127
Relevant Screenshot:
![linux](https://user-images.githubusercontent.com/8769067/52907692-81454700-3234-11e9-8934-cc6d8bf2bcdf.png)

-----

Windows Version: 10 Home 
Joplin Version: 1.0.127
Relevant Screenshot:
![windows](https://user-images.githubusercontent.com/8769067/52907693-8a361880-3234-11e9-8e55-141ca4c7c77d.png)

**Comment by kellerjustin** [comment]
Same issue here - cannot delete Welcome notebook tags on Android -- they show up twice despite deleting the notebook, and they sync to Linux (Ubuntu 16.04) client 1.0.127.
Android version 9
![screenshot_20190218-092105](https://user-images.githubusercontent.com/31552409/52961895-9370d380-3361-11e9-8e80-9b5ca8570bbe.png)

**Comment by yngwi** [comment]
I have that problem to, Sony Xperia XZ1, Android 9. Installed yesterday, notes are synced with desktop via nextcloud, welcome notebook is deleted. Tags are only showing on Android.
![screenshot](https://i.imgur.com/doyCQMe.png)

**Comment by foot-gloves** [comment]
I see this same issue. Syncing with Nextcloud.
Installed the first client on Ubuntu 18.10 Joplin client 1.0.127
Shortly after installed on Android 8.0.0 LG V30 Joplin client 1.0.237

I deleted the Welcome book on my Linux machine and all the tags disappeared. They remained on the Android device even after syncing both devices.

I then deleted the Welcome book on my Android device but all tags still remain on the V30.

So right now my tags are not in sync anymore. The Linux session has no tags while my Android client has all tags with duplicates.

**Comment by NginUS** [comment]
In my case, the errant tags were only displayed on Android. This morning it updated to 1.0.239 & they disappeared. Now all appears to be well.

**Comment by foot-gloves** [comment]
> In my case, the errant tags were only displayed on Android. This morning it updated to 1.0.239 & they disappeared. Now all appears to be well.

This is what I initially thought but I just tried installing it on iOS and the duplicate tabs returned to my linux client. They also are seen on the iOS and Android device. I even deleted the Welcome notebook on the new iOS device before setting up syncing and the tags still returned.

**Comment by laurent22** [comment]
> They also are seen on the iOS

This is expected as it hasn't been updated yet.

> and Android device.

Which version of Joplin? Latest should have a fix.

**Comment by foot-gloves** [comment]
> > They also are seen on the iOS
> 
> This is expected as it hasn't been updated yet.
> 
> > and Android device.
> 
> Which version of Joplin? Latest should have a fix.

Hello, from my post above:
> Installed the first client on Ubuntu 18.10 Joplin client 1.0.127
> Shortly after installed on Android 8.0.0 LG V30 Joplin client 1.0.237

I grabbed the APK from the website this morning on 2019-02-25.

**Comment by foxmask** [comment]
after the update to 1.0.241, now I have that behavior of duplcation tags entries :/

**Comment by Dasymi** [comment]
Yes, I have the issue of tags appearing in Android Joplin that I can't get rid of. 1.0.241, Galaxy S9+, Android version 9.

**Comment by Dasymi** [comment]
Today, presumably after several syncs, when I opened the app on Android the additional tags had disappeared.
