### ISSUE TITLE
Upgrade to 1.0.127 seems to be missing an image

### ISSUE THREAD

**Issue by mgrandi** [laurent22/joplin#1224]
### Operating system

- macOS

### Application
- Desktop

After upgrading to the latest version (1.0.127), it appears a new notebook was added, called "Welcome", in it, the first note, `1. Welcome to Joplin! 🗒️` , seems to have an image link that is broken because the file is not there

![screenshot_1148](https://user-images.githubusercontent.com/802786/52888543-4ad6d180-3139-11e9-922c-7ce58b0d16a8.png)

As you can see, it is even complaining about syncing, because it is trying to sync a file that is referenced but is not there:

```
Items that cannot be synchronised

AllClients.png (5c05172554194f95b60971f6d577cc1a): File not found: /Users/markgrandi/.config/joplin-desktop/resources/5c05172554194f95b60971f6d577cc1a.png
 
These items will remain on the device but will not be uploaded to the sync target. In order to find these items, either search for the title or the ID (which is displayed in brackets above).

```

it appears that this item was added to the sqlite3 database: 

```
[2019-02-15 15:53:52] markgrandi@Gypaetus:~$ sqlite3 /Users/markgrandi/.config/joplin-desktop/database.sqlite
SQLite version 3.24.0 2018-06-04 14:10:15
Enter ".help" for usage hints.
sqlite> .headers on
sqlite> SELECT * FROM resources WHERE id = '5c05172554194f95b60971f6d577cc1a';
id|title|mime|filename|created_time|updated_time|user_created_time|user_updated_time|file_extension|encryption_cipher_text|encryption_applied|encryption_blob_encrypted
5c05172554194f95b60971f6d577cc1a|AllClients.png|image/png||1550270276543|1550270276543|1550270276543|1550270276543|png||0|0
```

and the note was added to the database obviously had the link in the text:

```
![](:/5c05172554194f95b60971f6d577cc1a)
```

so it seems that the file was not added to the `~/.config//oplin-desktop/resources/5c05172554194f95b60971f6d577cc1a.png` folder? maybe reupload the release with that fixed?

**Comment by laurent22** [comment]
How about the other images, do they show up?

**Comment by mgrandi** [comment]
yeah, the other images show up, its just that one that is missing.

**Comment by mgrandi** [comment]
however, when i used the mobile app, it seemed to have put the image in the right spot and now it shows up on mobile, but not on the desktop version

i think that the mobile app tried to add the Welcome! notebook again and now the phone and desktop databases are out of sync, i noticed it added duplicates of tags and stuff (i see bug tickets for this already)

**Comment by laurent22** [comment]
I cannot replicate so closing it for now.
