### ISSUE TITLE
Give Welcome tags a unique ID

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#1237]
To avoid duplicates coming from multiple clients.

**Comment by tessus** [comment]
I've noticed that the welcome tags use American spelling: `synchronizing` and `organizing`.

In favor of consistency they should also use the British spelling as is used in the rest of Joplin.

Funny side note, the code is using American spelling, but the UI is using British spelling.

**Comment by laurent22** [comment]
Right, it should indeed use British spelling. Well the default locale is en_GB so that's why it's all British English but we could have an en_US one if we wanted. Currently Welcome notes are not localisable.

Code is definitely American English for consistency - I'll have a headache if I need to start writing things `style={{color: colour}}` :)

**Comment by taikedz** [comment]
Closed? Merged? I was about to ask about this in a new Issue as it still affects current installed clients (e.g. desktop version `1.0.14 prod,linux`)

I've got around 2-3 different "Welcome" resource duplicates that seem to come back with no rhyme or reason (I do delete them every time and sync back.....)
