### ISSUE TITLE
Clipper sometimes doesn't respond on PDF pages

### ISSUE THREAD

**Issue by dekaufman** [laurent22/joplin#1238]
### Operating system

- macOS

### Application

- Desktop

When I click the Joplin Web Clipper in Firefox while viewing a file like http://www.africau.edu/images/default/sample.pdf, it pops up a little balloon tip saying "Loading...", but nothing else ever happens.  No note is created in Joplin, and the balloon goes away when I click anything else, change windows, or any other action.

This appears to be the case for all PDF files I've tried to do any kind of clip of.  I realize that Joplin has limited support for viewing and indexing PDF contents, but unless something's broken, I might have guessed that the clipper would at least create a Note with useful metadata (web address, date captured, etc.) into which I could paste a copy of the downloaded PDF manually.

I enabled debugging but didn't see anything happen in the Console after I clicked the Clipper.  There's nothing in log.txt related to this event either.

**Comment by dekaufman** [comment]
Oh, screenshot:  
<img width="281" alt="image" src="https://user-images.githubusercontent.com/9930919/52971253-6382f980-337c-11e9-9935-08afcdacb4fe.png">

**Comment by laurent22** [comment]
This issue unfortunately cannot be fixed due to a limitation of Firefox, which doesn't allow extensions to access PDF tabs.
