### ISSUE TITLE
horizontal scrollbar too thick

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#1239]
### Operating system

- Windows
- macOS
- Linux
- Android ?
- iOS ?

### Application

- Desktop
- Mobile ?

---

As you can see in the screenshot below, the horizontal scrollbar is too thick. It's probably twice as thick as the vertical one:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/223439/52971680-57039e80-3386-11e9-968b-28f312959470.png">

**Comment by CalebJohn** [comment]
That was my bad I forgot to add a height property to the scrollbars, it was fixed in #1229 along with a bug that was only evident in dark mode. It should be available on the next release.

**Comment by tessus** [comment]
Thanks for the info and the fix.
