### ISSUE TITLE
Ipad resize

### ISSUE THREAD

**Issue by victor-moreno** [laurent22/joplin#124]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS  11.2.1

### Application

- [ ] Desktop
- [x] Mobile. Ipad
- [ ] Terminal

—-

Hi, I am new to this app. On iPad I don’t get a full screen. It seems it is recognized as a small iPhone. Nothing like the photo shown in your web
---

**Comment by laurent22** [comment]
Duplicate #186
