### ISSUE TITLE
Resize All 4 Columns: Feature Request

### ISSUE THREAD

**Issue by washere** [laurent22/joplin#1241]
### Operating system

- Windows

### Application

- Desktop

This is an enhancement request.

Ability to:

**RESIZE the WIDTH of ALL 4 COLUMNS:**

1) SideBar

2) Outline of Notes

3) Editor

4) Preview

Because it would make the app look and function professionally like many outliner productivity apps.

And also because then, many would recommend Joplin by word of mouth and it would go viral in a big way.

Also please do not close this enhancement feature request thread until ALL 4 Columns are resizable.

Thanks for the great Joplin.

**Comment by CalebJohn** [comment]
Currently (unreleased) there is the ability to resize the notebook/tag column and the note list column. You also want to be able to resize the editor, or is it enough to be able to toggle the layout? Also note, have you looked through issue #16?

Maybe this is a good issue to hijack. @laurent22 I'm able to resize the columns after your recent commit, but I only to the minimum and maximum values, trying to set anywhere in between snaps to the minimum width value.

**Comment by washere** [comment]
I had looked at #16 and several others before posting, hence the careful wording in title and post. And also why I requested it not be closed.

I opened this issue after the recent dark theme's newer extra features.

I have a long experience (and postgrad qualifications) in UI/UX. IMHO with the recent version of the improved dark theme, there is only one more feature to make Joplin have a top class UI to compete with any Outliner Tree based app. That is the ability to RESIZE ALL COLUMNS.

Not toggle, or other  issues or features.

I suggest 2 Phases:

**Phase 1:**
Initially the resize can be for the two left columns (Notes and Outline). This will greatly increase the UI benefits. Specially on laptops which is where many people will use Joplin on Windows.

**Phase 2:**
Later the the two content columns (Editor & Preview Panes) should be able to resize too. This should be variable and done by the mouse pointer. Not predetermined options as in CSS templates. Resizing either by their left border.

Until all 4 are Resizable via the mouse Pointer, please do not close this enhancement feature request.

I believe once we have the resizable, even if initially for the 2 left columns (Notes & Outlines), you will love it because it adds so much more to Joplin usability for everyone.

Thanks.

**Comment by washere** [comment]
Now the two left columns can be resized individually.

With the new dark theme and this resizing, Joplin has a really professional UI for a modern markdown editor with preview and sync-scroll of preview too.

Plus online sync with dropbox. It is awesome.

The resize of the two or one of the left 2 columns, leaves the rest of space to divide equally between editor and preview.

This is good enough now. I am closing this.

Thanks again.
