### ISSUE TITLE
Bulleted list - total freeze

### ISSUE THREAD

**Issue by marix88** [laurent22/joplin#1243]
### Operating system

- Windows

### Application

- Desktop

I have a list of items which all start with: "-". I wanted to add 2 items inside one of the items in the list, so I pressed _tab_, then _Bulleted List_ from the editor's ribbon, then deleted "-" and I am now stuck in this note. I can't go to other notes or to other layout or do anything else except for closing the program. When I open it, it takes me to the same note and I am back having the same problems with the program. The text in my note keeps moving like a 3D gif shade: the text underneath that comes over the current one seems to be the text I wrote at the beginning of the note(I am at the end of a longer note). The Bulleted List won't deactivate and shows up as text when I hover over items in the Bar(New note, New to-do etc.)

**Comment by laurent22** [comment]
Hard to tell what the problem is. Any chance you could post a video of it?

**Comment by marix88** [comment]
I found a fix around it: I stopped the app from Processes using CTR+ALT+Delete and it worked! I also realized exactly what I did and was able to reproduce it easily: click on Bulleted List, select all (I did it by mistake the first time by clicking multiple times on the place. I also used CTR+A when I reproduced it), then click on Bulleted List again.

**Comment by neuralgraffiti** [comment]
@laurent22 I can reproduce this (JoplinPortable.exe 1.0.127 on Windows 10), although it appears to only happen in some notes and not others.  One other data point -- if I kill the process, then re-open the same note, and click the button, the loop will start again.  Making an edit to the note before doing so will prevent the loop, but if I undo the changes and click again, the loop will restart.   

Iv'e attached the console and Joplin logs and a screen capture of the rendered window scrolling quickly up and down a few lines.  Happy to try other things to reproduce if it's helpful. 

[console.log](https://github.com/laurent22/joplin/files/2897187/console.log)
[joplin.log.txt](https://github.com/laurent22/joplin/files/2897188/joplin.log.txt)

![bulleted-list-loop](https://user-images.githubusercontent.com/6074556/53290863-26917b00-375f-11e9-948a-43a83bdb433b.gif)

I also had the console break on exceptions and pulled this exception:

>` "Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at invariant ([AppData\Local\Temp\]nsqA855.tmp\app\resources\app.asar\node_modules\fbjs\lib\invariant.js:42:15)
    at scheduleWork$1 ([AppData\Local\Temp\]nsqA855.tmp\app\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:16099:11)
    at Object.enqueueSetState ([AppData\Local\Temp\]nsqA855.tmp\app\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11185:5)
    at Connect.Component.setState ([AppData\Local\Temp\]nsqA855.tmp\app\resources\app.asar\node_modules\react\cjs\react.development.js:273:16)
    at Connect.onStateChange ([AppData\Local\Temp\]nsqA855.tmp\app\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:222:16)
    at Object.notify ([AppData\Local\Temp\]nsqA855.tmp\app\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs ([AppData\Local\Temp\]nsqA855.tmp\app\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:69:20)
    at Connect.onStateChange ([AppData\Local\Temp\]nsqA855.tmp\app\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:219:16)
    at Object.notify ([AppData\Local\Temp\]nsqA855.tmp\app\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs ([AppData\Local\Temp\]nsqA855.tmp\app\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:69:20)"`

**Comment by laurent22** [comment]
@neuralgraffiti, could you post the note that's causing the issue?

**Comment by neuralgraffiti** [comment]
> @neuralgraffiti, could you post the note that's causing the issue?

@laurent22 Happy to.  [Text is in this gist](https://gist.github.com/neuralgraffiti/17b44e1d1c4b0d01fe3304db4f954b11); it's pretty vanilla.  I've also done an export in case it's helpful.  Process was: 
1. Go to the note, export (non-crashy.jex).  
2. Confirm the UI freeze/jitter does not happen when I click the bullet toolbar button.
3. Ctrl-Z to undo the toolbar press.  For some reason this selects all of the text in the editing pane and then jumps to the bottom and does not undo the edit.  (Another Control-Z will undo, but keep all text selected.)  Export the note again (crashy.jex).  
4. Confirm that the crash happens when I click the button again.
I've also got a yet-later version in the attached zip that seems to be even more fragile.
[exports.zip](https://github.com/laurent22/joplin/files/2899242/exports.zip)

A couple other things that may be helpful:
- Making edit in the text box inconsistently prevents the crash.  (I thought it always did but am not so sure now).
- Selecting all via Ctrl-A appears to leave the editor in the crash-prone state

**Comment by laurent22** [comment]
@neuralgraffiti, thanks for the note and info but I can't seem to be able to replicate it. I've took your note and pasted it in Joplin. From there, could you describe what steps lead to the bug or crash? Where should the cursor be positioned, what actions should be done, etc.

**Comment by neuralgraffiti** [comment]
@laurent22 

Here's another try.  It is a little inconsistent, but I can usually get it into the crashing state by doing the following (attaching a screen capture of what I did here):
1. Create (or edit) a note.  
1. Make sure it has enough text that the edit box has to scroll 
1. (Then I scrolled up to the top)
1. Added a bullet and edited it
1. Did a Ctrl-Z to undo the edits (this is where the full select and jump to the bottom happens)
    - I am wondering if this is where the problem is, because it seems odd that an undo would select all the text and move to the bottom of the text field.
1. Jump to the top of the screen with Ctrl-Home
1. Click the bullet toolbar button
1. Crash/loop.

![reproduction](https://user-images.githubusercontent.com/6074556/53624991-c82d2800-3bb6-11e9-95d3-bc342054e371.gif)

If there's some way I can get you a more robust trace or debug log, I'm happy to try it.
