### ISSUE TITLE
Improve tag deletion prompt

### ISSUE THREAD

**Issue by sciurius** [laurent22/joplin#1245]
In the attached screenshot, which tag is being removed?

(Hint: it is not the tag that is selected.)

It would be nice if the tag name was shown in the dialog.

### Operating system

- Linux

### Application

- Desktop

![scrot20190220171311](https://user-images.githubusercontent.com/1118804/53106815-b51db680-352b-11e9-9fd1-13d4a36d25b3.png)

**Comment by tessus** [comment]
This would be a useful enhancement. Maybe I can create a PR for that... (I have to check the code. I'm not good with js.)
