### ISSUE TITLE
Adding the possibility to make text larger for easier reading!

### ISSUE THREAD

**Issue by madlogic54** [laurent22/joplin#125]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---

**Comment by laurent22** [comment]
Implemented in recent version
