### ISSUE TITLE
Sync Error with OwnCloud on desktop - PROPFIND : Unknown error 2 (403)

### ISSUE THREAD

**Issue by StreamEnviro** [laurent22/joplin#1256]
### Operating system

- Windows

### Application

- Desktop

My Android phone running Joplin synchonises to my OwnCloud instance perfectly fine, but the Windows app will not, even though using the same settings.

I have tried http and https, ‘dav’ and ‘webdav’, using a / after the destination folder or not, using a different web connection, everything I can think of. Debug report shows no conflicts.

File location is - https://www.website.co/vault/remote.php/dav/files/username/Notes. I have copied the .md files there manually.

Error is:

PROPFIND : Unknown error 2 (403): <!DOCTYPE html> <html class=“ng-csp” data-placeholder-focus=“false” lang=“en” > <head data-requesttoken=“OgoHdjUIODkvVx5JAnUlESIzFSt5Nw9dMWJyaFwjHHY=:cf12BGVjG3zqnAsASqVX/bFrE7Y+dhZ4m7ZGavEBcVQ=”> <meta charset=“utf-8”> <title> ownCloud </title> <meta http-equiv=“X-UA-Compatible” content=“IE=edge”> <meta name=“referrer” content=“never”> <meta name=“viewport” content=“width=device-width, minimum-scale=1.0, maximum-scale=1.0”> <meta name=“apple-itunes-app” content=“app-id=543672169”> <meta name=“theme-color” content="#1d2d44"> <link rel=“icon” href="/vault/core/img/favicon.ico"> <link rel=“apple-touch-icon-precomposed” href="/vault/core/img/favicon-touch.png"> <link rel=“mask-icon” sizes=“any” href="/vault/core/img/favicon-mask.svg" color="#1d2d44"> <link rel=“stylesheet” href="/vault/core/vendor/select2/select2.css?v=43597fd8c41e25ad5ec3a4db1e5a4c33"> <link rel=“stylesheet” href="/vault/core/css/styles.css?v=43597fd8c41e25ad5ec3a4db1e5a4c33"> <link rel=“stylesheet” h (Code 403)

Please help.

**Comment by tessus** [comment]
>File location is - https://www.website.co/vault/remote.php/dav/files/username/Notes. I have copied the .md files there manually.

What is your setting in options for the WebDAV URL? It believe your path is incorrect:

try: `https://www.website.co/vault/remote.php/webdav/Notes`

**Comment by StreamEnviro** [comment]
Hello, I have tried the suggested URL and get the following error... (very similar)

PROPFIND : Unknown error 2 (403): <!DOCTYPE html> <html class="ng-csp" data-placeholder-focus="false" lang="en" > <head data-requesttoken="FBg+QAoQUAZIDCVcUA1XczVLTkJLJhE6AygmKgYQWWc=:dTz1Ru7D0xt+5FgCa28pxTbQKXisBe+1u0eEz8eqUWc="> <meta charset="utf-8"> <title> ownCloud	</title> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="referrer" content="never"> <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0"> <meta name="apple-itunes-app" content="app-id=543672169"> <meta name="theme-color" content="#1d2d44"> <link rel="icon" href="/vault/core/img/favicon.ico"> <link rel="apple-touch-icon-precomposed" href="/vault/core/img/favicon-touch.png"> <link rel="mask-icon" sizes="any" href="/vault/core/img/favicon-mask.svg" color="#1d2d44"> <link rel="stylesheet" href="/vault/core/vendor/select2/select2.css?v=43597fd8c41e25ad5ec3a4db1e5a4c33"> <link rel="stylesheet" href="/vault/core/css/styles.css?v=43597fd8c41e25ad5ec3a4db1e5a4c33"> <link rel="stylesheet" h (Code 403)

**Comment by StreamEnviro** [comment]
Sorry the error is not showing properly I presume due to Markdown.

The error is 

`PROPFIND : Unknown error 2 (403): <!DOCTYPE html> <html class="ng-csp" data-placeholder-focus="false" lang="en" > <head data-requesttoken="FBg+QAoQUAZIDCVcUA1XczVLTkJLJhE6AygmKgYQWWc=:dTz1Ru7D0xt+5FgCa28pxTbQKXisBe+1u0eEz8eqUWc="> <meta charset="utf-8"> <title> ownCloud	</title> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="referrer" content="never"> <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0"> <meta name="apple-itunes-app" content="app-id=543672169"> <meta name="theme-color" content="#1d2d44"> <link rel="icon" href="/vault/core/img/favicon.ico"> <link rel="apple-touch-icon-precomposed" href="/vault/core/img/favicon-touch.png"> <link rel="mask-icon" sizes="any" href="/vault/core/img/favicon-mask.svg" color="#1d2d44"> <link rel="stylesheet" href="/vault/core/vendor/select2/select2.css?v=43597fd8c41e25ad5ec3a4db1e5a4c33"> <link rel="stylesheet" href="/vault/core/css/styles.css?v=43597fd8c41e25ad5ec3a4db1e5a4c33"> <link rel="stylesheet" h (Code 403)`

**Comment by laurent22** [comment]
Error 403 means "Forbidden" so maybe some error with your username or password, or that WedDAV folder is not accessible.

**Comment by tessus** [comment]
What happens, if you enter your webdav URL in a browser?

**Comment by StreamEnviro** [comment]
If I log into the same link on a browser, it asks for the username and password and then shows me the following:

> 
Sabre\DAV\Exception\NotFound File with name files/d7tq2u/Notes could not be located
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
<s:message>
File with name files/d7tq2u/Notes could not be located
</s:message>
<s:message>...</s:message>
</d:error>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">...</d:error>

**Comment by StreamEnviro** [comment]
And if I change the link to /dav/ instead of /webdav/, then I get:

> This  is the WebDAV interface. It can only be accessed by WebDAV clients such as the ownCloud desktop sync client.

**Comment by tessus** [comment]
I think the error message `File with name files/d7tq2u/Notes could not be located` couldn't be more clear.

I'm truly sorry, but I don't know what else I can tell you. 

In owncloud/nextcloud there's a WebDAV url displayed in the settings. (File application bottom, left corner in Settings.) If this URL is not working (don't forget to add the folder where your Joplin notes are supposed to be located), it's a problem with your owncloud/nextcloud installation.

**Comment by iljapanic** [comment]
I'm getting the same error but with Nextcloud.

When I enter the WebDAV url in a browser I get:
>This is the WebDAV interface. It can only be accessed by WebDAV clients such as the ownCloud desktop sync client.

so I presume the WebDAV interface is working fine.

When I check the synchronisation configuration in settings pane I get:
>Success! Synchronisation configuration appears to be correct.

I'm testing this on Ubuntu 18.04.2 LTS x86_64 (Xubuntu)

**Comment by tessus** [comment]
@iljapanic do you have synchronization errors in Joplin?

Or are you talking about this message: `This is the WebDAV interface. It can only be accessed by WebDAV clients such as the ownCloud desktop sync client.` ?
If so, this is not an error. I asked @StreamEnviro to use the browser to narrow down the issue.

I'm puzzled by your comment. If the sync test in settings is ok, then everything is fine.

**Comment by iljapanic** [comment]
@tessus Sync test works fine, but when I press 'Synchronise' in the main app then I get a following error:

```
Completed: 12/03/2019 01:08
Last error: Error: MKCOL .sync/: Unknown error 2 (403): <html>
 <head><title>403 Forbidden</title></head>
 <body bgcolor="white">
 <center><h1>403 Forbidden</h1></center>
 <hr><center>nginx</center>
 </body>
 </html>
```

**Comment by tessus** [comment]
So the sync test works, but the actual sync doesn't. This is very strange. @laurent22 any idea how to debug this any further?

**Comment by laurent22** [comment]
You mentioned Nextcloud but this is an nginx error. Maybe try to disable nginx webdav module.

**Comment by StreamEnviro** [comment]
Sorry I am not clear which issue is being addressed? @laurent22 ?

I do not have a Sync test that works fine, it gives the error I have given above. I have an OwnCloud instance, not NextCloud.

It looks like the issue that @iljapanic has is different, and should be on a different thread.
