### ISSUE TITLE
Is there a way to not automatically save anything i input on the note?

### ISSUE THREAD

**Issue by JunkyardCat** [laurent22/joplin#1259]
Earlier this day i had overwritten something i made previously and didnt noticed it until later. since there was no prompt bto overwrite the already create note i had lost some important stuff. if this isnt implemented yet can we have it as a feature request

**Comment by JunkyardCat** [comment]
anyone looking into this?

**Comment by JunkyardCat** [comment]
can i ask if this will be implemented?

**Comment by laurent22** [comment]
Version control is coming in next version and will allow restoring previous or deleted notes.
