### ISSUE TITLE
Can't resize sidebar on v1.0.132 but only shrink to specific size

### ISSUE THREAD

**Issue by bugcaptor** [laurent22/joplin#1265]
### Operating system
- Windows

### Application
- Desktop

![sidebar resize bug](https://user-images.githubusercontent.com/919071/53454056-54313980-3a69-11e9-8741-9bab06b60399.gif)

Upgraded to v1.0.132.
Sidebars are only shrinking to specific width.
Can't resize.
Have to downgrade to previous version.

**Comment by laurent22** [comment]
I can indeed replicate this on Windows, but on macOS it seems to work fine.

**Comment by edenpc** [comment]
Same here on Windows.

**Comment by laurent22** [comment]
Fix will be in tomorrow's release.

**Comment by jovandeginste** [comment]
@laurent22 thanks for the fix! (tested and works here)

**Comment by M-O-Z-G** [comment]
@laurent22, the bug is gone in 1.0.134, thanks. But now dragging action doesn't work with graphic tablet (only in mouse mode). Testing with Wacom CTH-460 on Windows 7 x64 SP3.
