### ISSUE TITLE
Sync button is unresponsive for OneDrive Business

### ISSUE THREAD

**Issue by rosareven** [laurent22/joplin#1266]
### Operating system

Windows 10, Android 9

### Application

Desktop & Mobile

Details:
I signed into OneDrive Business account in Joplin. The app folder never got created and the sync button is unresponsive (click it and nothing happens, beside for the initial login). Same with the android app.

**Comment by edr0id** [comment]
Confirmed the same exactly in Windows 10 using fresh Joplin 1.0.145.

**Comment by Project0** [comment]
still not working...

**Comment by laurent22** [comment]
OneDrive Business is not supported.

**Comment by Project0** [comment]
might be worth to mention it in the readme ;-)

**Comment by laurent22** [comment]
It should show an error message saying that OneDrive Business is not supported. If not, more information is needed.

**Comment by Project0** [comment]
I definitively did not received any error (1.0.169 on linux)
