### ISSUE TITLE
Check update popup

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#1267]
### Operating system

- Windows
- macOS

### Application

- Desktop

It could be fine if the message was rendered in html instead of raw markdown 
in the attached snapshot, the  `**not**` should be bold and all the quoted #XXXX could lead to the issue.
![check for updates](https://user-images.githubusercontent.com/208212/53476893-c3ac2680-3a73-11e9-97d2-8634049bbcaa.png)

**Comment by dayfuaim** [comment]
Yes, confirm.
![2019-02-27 12 07 59](https://user-images.githubusercontent.com/1274699/53478651-65d60980-3a88-11e9-8fb2-c19fa9f23b0d.png)

**Comment by foxmask** [comment]
i'll check for the next update

**Comment by foxmask** [comment]
I tried to start older versions, to check, but that does not work :)

**Comment by foxmask** [comment]
i close that because I dont see problem with the actual release(note) now but It may be reopened if I see `**words**` instead of **word**
