### ISSUE TITLE
Error exporting to PDF

### ISSUE THREAD

**Issue by BurtonChia** [laurent22/joplin#1268]
[test.pdf](https://github.com/laurent22/joplin/files/2909589/test.pdf)
### Operating system
- Linux
- Windows
- macOS

### Application
- Desktop

### Version
1.0.132 (app image)

### Issue
This version has an issue exporting to PDF. A blank PDF will be created with the word "undefined" in it. I've attached an example of the PDF output. I didn't face this issue with the older 1.0.127 version.

**Comment by sachilles** [comment]
Hi there,

I'm using Joplin (version 1.0.132) under Mac OS X (10.14.3) and faced the same issue.

**Comment by tydel** [comment]
I am encountering this error as well using the latest 1.0.134 on Windows 10.

**Comment by tessus** [comment]
This happens on all desktop OS.

**Comment by laurent22** [comment]
They broke regular printing and printing to PDF in Electron 4. While we wait for them to fix it I've implemented a workaround. For reference: https://github.com/electron/electron/issues/16171 https://github.com/electron/electron/issues/16219  https://github.com/electron/electron/issues/16534
