### ISSUE TITLE
Welcome items on every update: please don't!

### ISSUE THREAD

**Issue by brenthuisman** [laurent22/joplin#1269]
### Operating system

Win, Lin, Android

### Application

- Desktop
- Mobile

The welcome items now (re)appear on every update of every client. Since I use about 4 or 5 clients, thats quite a lot of work to remove it every time. I think the welcome page shouldn't reappear for update, only fresh installs or empty repo's.

**Comment by CalebJohn** [comment]
How are you updating? I use Joplin on Linux and Android and this didn't happen with me. Maybe this is a windows only issue?

**Comment by brenthuisman** [comment]
On Android its autoupdated through the Play store, on Linux I update the Appimage myself. Both cause it. I do not use Windows. If you dont have it, might there be a trigger? 

-----Oorspronkelijk bericht-----
Van: "Caleb John" <notifications@github.com>
Verzonden: ‎28-‎2-‎2019 04:53
Aan: "laurent22/joplin" <joplin@noreply.github.com>
CC: "Brent Huisman" <mail@brenthuisman.net>; "Author" <author@noreply.github.com>
Onderwerp: Re: [laurent22/joplin] Welcome items on every update: please don't!(#1269)

How are you updating? I use Joplin on Linux and Android and this didn't happen with me. Maybe this is a windows only issue?

**Comment by CalebJohn** [comment]
Are you doing anything to your .config/joplin-desktop folder when updating? Maybe something is getting broken there?

**Comment by brenthuisman** [comment]
I haven't touched anything in the filesystem, only configured Joplin through its interface. I've been using Joplin for about half a year now, and this started a few weeks, maybe a month ago.

**Comment by laurent22** [comment]
@brenthuisman, on one of your devices could you open database.sqlite, then look at the "settings" table. What is the value of "welcome.wasBuilt"?

**Comment by brenthuisman** [comment]
That value is set to `1`.

**Comment by virtadpt** [comment]
@brenthuisman @CalebJohn It happened to me on Android, Linux AppImage, and OSX.

**Comment by laurent22** [comment]
With 5 clients, you'll get 5 Welcome notebooks - is it possible that some of them weren't synced to some devices and you're seeing them now? Could you try to delete all the Welcome items then try to install the app again (even the same version over the it)?

There's nothing special happening on update. If there was something creating Welcome items it would be every time you start Joplin, but it doesn't seem to be what's happening.

**Comment by brenthuisman** [comment]
I made it a habit to sync upon starting Joplin, so i doubt it due to unpropagated changes (I'd expect more things to fail updating then). The only 'rule' that seems to predict the reappearance is an update.

What constitutes a reinstall? Trashing .config/joplin* ?

-----Oorspronkelijk bericht-----
Van: "Laurent Cozic" <notifications@github.com>
Verzonden: ‎28-‎2-‎2019 18:47
Aan: "laurent22/joplin" <joplin@noreply.github.com>
CC: "Brent Huisman" <mail@brenthuisman.net>; "Mention" <mention@noreply.github.com>
Onderwerp: Re: [laurent22/joplin] Welcome items on every update: please don't!(#1269)

With 5 clients, you'll get 5 Welcome notebooks - is it possible that some of them weren't synced to some devices and you're seeing them now? Could you try to delete all the Welcome items then try to install the app again (even the same version over the it)?
There's nothing special happening on update. If there was something creating Welcome items it would be every time you start Joplin, but it doesn't seem to be what's happening.

**Comment by bugcaptor** [comment]
I just got updated on my iphone then I got a welcome document again(I have deleted welcome document and tags on any device). Of course, the iphone was well synchronized before update.

**Comment by bugcaptor** [comment]
Same symptom on my ipad after update. App update cause welcome document creation?

**Comment by CalebJohn** [comment]
What version were you on before the update? Is it possible that this issue is because this is your first update in ~1 month?

**Comment by bugcaptor** [comment]
I can't remember previous version number or when. But I'm trying to update apps everyday, so not so old one. I can see previous update was about 3 weeks ago in appstore history.

**Comment by ironjohn** [comment]
I think I'm seeing the same thing.  I just deleted 4 x all of the welcome tags and have 3 x Welcome! folders.

I'm not familiar with React/Java specifically, but perhaps some version of the sqlite "CREATE TABLE IF NOT EXISTS notebooks" and "tags" could help.  

If I knew React/Java I'd try it myself before making the suggestion, but I'm not qualified to contribute to your project directly.

**Comment by CalebJohn** [comment]
@ironjohn currently the behaviour you're describing is already present in Joplin. That's why this bug is so strange, and why we really need the help of the people experiencing it.

@bugcaptor the iOS application wasn't updated as quickly as the android one. It's possible that this bug won't happen again, I think it's best to wait for the next update to see if it happens again and if you can please update here (even if it doesn't create a new notebook) that would be great!

@brenthuisman typically you should never have to trash .config/joplin unless you're trying to nuke things for some reason.
That said the reason @laurent22 is trying to get you to ensure everything is synced before updating is because this bug seems to only affect a few people and from the Joplin side it doesn't look like there are any bugs, so the most likely explanation is that some client accidentally synced the welcome notebook and the other ones pulled it down. If this isn't the case, my apologies, I'll keep trying to help you figure this out, but since no one willing to help resolve this bug is actually experiencing it I hope you can understand that this is a difficult process.

**Comment by brenthuisman** [comment]
Caleb, Im not sure why you repeat what was already addressed. Ensuring sync I already do, it isn't a one time event (nor a one person event as became clear) and Im here to help troubleshoot. I asked if trashing .config/joplin* would help, but i havnt had a reply to that. In case there are other steps that I could take, please let me know.

-----Oorspronkelijk bericht-----
Van: "Caleb John" <notifications@github.com>
Verzonden: ‎2-‎3-‎2019 20:45
Aan: "laurent22/joplin" <joplin@noreply.github.com>
CC: "Brent Huisman" <mail@brenthuisman.net>; "Mention" <mention@noreply.github.com>
Onderwerp: Re: [laurent22/joplin] Welcome items on every update: please don't!(#1269)

@ironjohn currently the behaviour you're describing is already present in Joplin. That's why this bug is so strange, and why we really need the help of the people experiencing it.
@bugcaptor the iOS application wasn't updated as quickly as the android one. It's possible that this bug won't happen again, I think it's best to wait for the next update to see if it happens again and if you can please update here (even if it doesn't create a new notebook) that would be great!
@brenthuisman typically you should never have to trash .config/joplin unless you're trying to nuke things for some reason.
That said the reason @laurent22 is trying to get you to ensure everything is synced before updating is because this bug seems to only affect a few people and from the Joplin side it doesn't look like there are any bugs, so the most likely explanation is that some client accidentally synced the welcome notebook and the other ones pulled it down. If this isn't the case, my apologies, I'll keep trying to help you figure this out, but since no one willing to help resolve this bug is actually experiencing it I hope you can understand that this is a difficult process.

**Comment by CalebJohn** [comment]
@brenthuisman As far as I can tell it has not been addressed, what we need to determine is if this was a one time issue or if it is reproducible (unfortunately other users having the same issue doesn't count because we need to figure out what causes the bug, because the existence of this issue already proves that it happened). As far as next steps, if you could update you client again ("update" to the same version if you have to) and report back if the welcome note is created that would be very informative for us. Thanks.

If you remove .config/joplin then you will definitely get a welcome notebook!

edit: I just re-read your issue text, and I believe I may have misunderstood the issue. 
1. By "every update" do you mean that the welcome notebook was created by each client that was updated meaning n notebooks total for n clients.
2. Or did you update your n clients and get n welcome notebooks (which were then deleted) and when you updated again, n more notebooks were created? For a total of 2*n notebooks (n notebooks for each update).
This is important because these are 2 very different cases. If you are unsure, updating now and checking for a welcome notebook will help us understand the issue.

**Comment by brenthuisman** [comment]
Case 2. All my clients are updated right now, but over the past weeks a Joplin update was guaranteed to produce and then propagate the welcome document, per client.

-----Oorspronkelijk bericht-----
Van: "Caleb John" <notifications@github.com>
Verzonden: ‎3-‎3-‎2019 02:51
Aan: "laurent22/joplin" <joplin@noreply.github.com>
CC: "Brent Huisman" <mail@brenthuisman.net>; "Mention" <mention@noreply.github.com>
Onderwerp: Re: [laurent22/joplin] Welcome items on every update: please don't!(#1269)

@brenthuisman As far as I can tell it has not been addressed, what we need to determine is if this was a one time issue or if it is reproducible (unfortunately other users having the same issue doesn't count because we need to figure out what causes the bug, because the existence of this issue already proves that it happened). As far as next steps, if you could update you client again ("update" to the same version if you have to) and report back if the welcome note is created that would be very informative for us. Thanks.
If you remove .config/joplin then you will definitely get a welcome notebook!
edit: I just re-read your issue text, and I believe I may have misunderstood the issue.
By "every update" do you mean that the welcome notebook was created by each client that was updated meaning n notebooks total for n clients. 
Or did you update your n clients and get n welcome notebooks (which were then deleted) and when you updated again, n more notebooks were created? For a total of 2*n notebooks (n notebooks for each update).
This is important because these are 2 very different cases. If you are unsure, updating now and checking for a welcome notebook will help us understand the issue.

**Comment by CalebJohn** [comment]
The update that added the welcome notebook was only a few weeks ago, but I trust that this isn't the case. Since this is case 2, can you do as suggested above and trigger another update, I would like to confirm.

**Comment by brenthuisman** [comment]
To which instructions above are you exactly referring? How can I trigger an update? At least the appimages are all manual updates. I could try a downgrade perhaps? (As currently I'm on the latest release)

**Comment by CalebJohn** [comment]
Yes a downgrade would be best, but go to a version before the welcome book (v1. 0.125 and earlier). Then please upgrade to the most recent version from there.

**Comment by brenthuisman** [comment]
I just performed the following steps:

1. Delete ~/.config/joplin*
2. Downloaded and ran Joplin-1.0.120-x86_64.appimage
3. Redownload all my notes from my webdav server. I made sure no trace of any welcome page was present, and I synced once more.
4. Reran Joplin-1.0.134-x86_64.AppImage
5. I was greeted with a brand spanking new `Welcome! (Desktop)` page with associated labels, added to the database downloaded in step 3.

Meanwhile, no other devices have synced.

**Comment by brenthuisman** [comment]
Another observation that is perhaps related: on desktop deleted labels do not seem to propagate (reliably) to my Android clients. I do not see a way to delete labels on the mobile client.

**Comment by CalebJohn** [comment]
I'm sorry @brenthuisman I thought it was clear that you should **not** delete .config/joplin, doing so guarantees that you'll get a welcome on update. Can you try the same experiment but without removing the .config folder?

In general when trying to debug, you should only modify one thing at a time. For example in this case you never deleted the .config/joplin folder before, so just from this test we don't know what caused the notebook to appear, the removal of all configuration files or the update (that said, in this case we know that deleting .config/joplin is **guaranteed** to duplicate the welcome notebook). So in all we have unfortunately not learned anything from this test, but if you follow the same procedure without deleting the configuration that will be helpful.

Additionally for yourself it might be interesting to delete the .config/joplin folder and observe that the welcome not will be created the next time you launch Joplin. But this is not necessary and will only help show you what the configuration files do.

**Comment by brenthuisman** [comment]
When I do not remove the config, Joplin simply warns me that it cannot read a configuration created by a newer version.

But, as I thought I wrote clearly, the welcome page and tags were recreated. So your last paragraph is *not* correct. Try it yourself.

Caleb John <notifications@github.com> schreef op March 4, 2019 7:00:07 PM UTC:

**Comment by CalebJohn** [comment]
@brenthuisman I'm sorry that I'm not being more clear. **If you delete .config/joplin you are guaranteed to have the welcome notebook recreated**.

> When I do not remove the config, Joplin simply warns me that it cannot read a configuration created by a newer version.

I forgot about that issue, you're correct I was giving you bad instructions. If you go to the [joplin releases page](https://github.com/laurent22/joplin/releases) there are a few pre-release versions which I believe are fairly stable, please upgrade to one of them without deleting .config/joplin and let me know if you get the welcome notebook. In this case by "upgrade" I mean to download the .AppImage, rename it Joplin.AppImage and replace the currently existing Joplin.AppImage from your ~/.joplin folder (or wherever you run it from).

**Comment by brenthuisman** [comment]
Note that when I downgraded, the welcome page came after the upgrade. That also sounds like it shouldn't be happening (after all, after an upgrade I had been using Joplin already).

I just upgraded to 138, and no welcome page.

**Comment by CalebJohn** [comment]
It seems more likely to me that any update that takes the version from a pre-welcome notebook version to anything past that will trigger the creation. But any update beyond that shouldn't. 

To fix this perhaps there could be a flag or something that is set when the database is first created, this way there would be no way that notebooks are created on update.

**Comment by brenthuisman** [comment]
I have not seen this behavior in recent months, so I'll mark it closed.
