### ISSUE TITLE
[Linux, Desktop, 1.0.132] Dragging to expand notes or notebooks pane instantly snaps it back to minimum size

### ISSUE THREAD

**Issue by cable729** [laurent22/joplin#1272]
### Operating system
- Linux

### Application
- Desktop (1.0.132 prod)

### Steps to Reproduce
1. Put mouse on divider between note list/note content or notebooks/note list
2. Click and drag, then go to the right to make the pane wider

### Expected
Pane will expand as expected

### Actual
Pane snaps back almost immediately to an extremely small size. This actually makes the application almost unusable. It's pretty bad.

**Comment by laurent22** [comment]
Did you try v134?

**Comment by cable729** [comment]
OK, I just tried and it's fixed in that version. There are some other issues related to resizing, but I'll open up another bug for that.
