### ISSUE TITLE
[Feature Request] Open notes in new window

### ISSUE THREAD

**Issue by cable729** [laurent22/joplin#1274]
### Operating system
- Windows
- macOS
- Linux

### Application
- Desktop

### Feature Request
Allow notes to be opened in a new window, similar to EverNote. This is helpful when I am editing two notes at the same time. For instance, when I'm writing a draft in one note and pulling up a bunch of different reference notes at the same time, I'd like to keep the draft open in a separate window.

**Comment by CalebJohn** [comment]
This is already possible but you need to specify an external editor first. [Typography](typora.io) is a really good editor I think you'll find it nicer than editing all notes in Joplin directly.

**Comment by cable729** [comment]
An external editor is an alright solution, but it's not very tightly integrated. Having the toolbar at the top of the editor with tags and notebook selector is useful enough to me to want multi-window support.
