### ISSUE TITLE
[Feature Request] Detailed note view layout

### ISSUE THREAD

**Issue by cable729** [laurent22/joplin#1275]
### Operating system
- Windows
- macOS
- Linux

### Application
- Desktop

### Feature Request
See the example below. Basically, it would be nice to display the list of notes like below, so that they can be sorted by tag and so that tags are easily visible.

![EverNote layout](https://cdn-images-1.medium.com/max/1600/1*yOJI9C6b7kRbMOSXtSTYRA.png)

**Comment by Dasymi** [comment]
This is something I miss from Evernote.
