### ISSUE TITLE
No more single click to tray to open Joplin?

### ISSUE THREAD

**Issue by gerroon** [laurent22/joplin#1277]
Hi

I am using Joplin 135 on Debian x64. 

I am wondering why single clicking to tray icon to open Joplin was removed? Now one has to do click and choose "Open Joplin" which might not be a big  deal to many of you but this is such a big issue with elderly users of these apps. This kind of usability is really hard for elderly people,people with certain muscle diseases that affects motor control or people with sight issues. 

Riot broke this feature too some time ago, now  I need to VNC to my parent's computer so I can open the main Riot window, because it is so hard for her to find that icon and do that pull down thing. This new Joplin anti feature is the exact same problem :(

I really hope that the devs reconsider this decision and bring single click to bring Joplin window to front back.

thanks

**Comment by tessus** [comment]
Nothing has changed in the Joplin code for the tray icon. However, Joplin now uses Electron 4.x. It's more than likely that this is an upstream issue.

**Comment by gerroon** [comment]
Sure but cant that be reconfigured?

**Comment by tessus** [comment]
Sorry, I cannot answer that. 

e.g. If upstream removed that feature w/o making it  possible to reactivate this behavior with some sort of an option, then no. Otherwise, yes.

As far as I have seen so far, there are several things that have been removed in Electron 4.x.

**Comment by gerroon** [comment]
@tessus

Thanks. That is really unfortunate and overlooking such an accessibility hardship for elders and people with certain disabilities is just sad.  I am actually having hard time with why they did this :(

**Comment by tessus** [comment]
@gerroon I hear you. I have no idea why they did that. Maybe they didn't know that they removed a functionality that was previously there. Maybe the behavior was just a side effect. e.g. on macOS I always had to click on the menu item and then on the menu item `Open Joplin`. Maybe this behavior is specific to Linux, or the desktop env you are using. The only people who can answer these questions are the Electron devs.

**Comment by sciurius** [comment]
No, opening a system tray app with a single click is standard behaviour on all modern Linux desktops, not a side effect.
Some investigation learns that I now have a couple malbehaving apps in the tray -- all electron based. All other Linux applications behave normally.
The electron devs better reconsider this breakage. Fast.

**Comment by laurent22** [comment]
@sciurius, maybe file a bug over there? For information the relevant code, that used to work, is there: https://github.com/laurent22/joplin/blob/fca4fa666d829a65b34623726273a73b77ff8a71/ElectronClient/app/ElectronAppWrapper.js#L180

**Comment by sciurius** [comment]
I don't feel eligible to file bugs with electron. I'm a Joplin user, I don't know electron, I even didn't know it existed before it allegedly started breaking Joplin behaviour.

**Comment by gerroon** [comment]
@laurent22 

I think that it would be more legit if a prominent dev like you actually files it, obviously if you have time for it. The upstream issues are a bit abstract for users like us.

**Comment by tessus** [comment]
> opening a system tray app with a single click is standard behaviour

I was talking about the menu item (the little icon, which is in the top menu bar on macOS). On Linux that would be in the bottom, right corner where the date and time is located (where you also see the icons for the speaker, wifi, ...). For me that's called the tray.

The dock (macOS) / launcher (Linux), and the app switcher (`meta+tab`) are probably what people in this thread meant.

**Comment by sciurius** [comment]
This is the tray I'm talking about (notification applet in the mate panel):
![scrot20190305205512](https://user-images.githubusercontent.com/1118804/53833577-c54c8180-3f80-11e9-9bd6-9b79e656a864.png)

**Comment by tessus** [comment]
Ok, so now I'm confused. ;-) I'm saying that on macOS the menu item (which is the same as the tray icon on Linux) never opened Joplin, but a menu. But when I click on the Joplin icon in the macOS Dock, Joplin opens.

So the menu item and the tray icon apparently behave differently on macOS and Linux.
