### ISSUE TITLE
[Feature Request] Insert date and time in android

### ISSUE THREAD

**Issue by PunnyBoi** [laurent22/joplin#1278]
Hi,
### Operating system

- Android

### Application

- Mobile

### Feature Request
It seems that the android app doesn't have the 'Insert Date and Time' option. I think this will be important for people who use Joplin as a diary.

**Comment by starstuff** [comment]
I'm looking for this feature because I want to use Android for daily diary.

**Comment by ronaldscott** [comment]
iOS too please...
