### ISSUE TITLE
code block not rendered correctly

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#1279]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile

---

The following text:

<img width="179" alt="image" src="https://user-images.githubusercontent.com/223439/53542776-06124980-3aee-11e9-8bc6-7ec47dee6f40.png">

is rendered as:

<img width="183" alt="image" src="https://user-images.githubusercontent.com/223439/53542802-1de9cd80-3aee-11e9-9741-4f7b75829f88.png">

but it should be rendered like this:

```
- [ ] Item 1
- [ ] Item 2
    - [ ] Subitem 2.1

**bold** _italic_
```

**Comment by laurent22** [comment]
hmm, yes I marked the part that deals with checkboxes with "HORRIBLE_HACK" in the code since it's quite messy and it looks like you found a flaw in this hack :-)

I think the solution would be to use an existing markdown-it plugin for checkboxes, if any, and use this to properly parse them. Maybe that will allow solving the problem of having bullets before the checkboxes too.

**Comment by tessus** [comment]
> I think the solution would be to use an existing markdown-it plugin for checkboxes, if any, and use this to properly parse them. Maybe that will allow solving the problem of having bullets before the checkboxes too.

Yep, this could work. Unfortunately I won't be of any help in this regard. I apparently do not understand how parsing and rendering work, otherwise I would hae been able to get the toc plugin working....

**Comment by laurent22** [comment]
Fixed in latest release.

**Comment by tessus** [comment]
Thanks for the info. I'm currently still using 1.0.127 and 1.0.138, but I will get git master and test the dev version locally. I've also noticed a few other issues that might still be there. I will open issues on github accordingly.
Btw, electron 4.0.7 fixed one of the issues you referenced in one of the tickets.

**Comment by tessus** [comment]
Yep, I've tested with current master. The checkboxes are shown as text in a code block.
I also like the fact that the new rendering does not show the bullets.

However, I've noticed that the checkboxes are much smaller now. Is this on purpose?

<img width="146" alt="image" src="https://user-images.githubusercontent.com/223439/54485618-4abe1480-4852-11e9-81f8-cddfd59f0cc2.png">
