### ISSUE TITLE
Can not scale editor page by gesture on Mac

### ISSUE THREAD

**Issue by tornadoyi** [laurent22/joplin#1280]
hi:
    I can not scale editor page by gesture on Mac.
    my Joplin version:  
           Copyright © 2016-2019 Laurent Cozic
           Joplin 1.0.135 (prod, darwin)

### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

**Comment by tessus** [comment]
I don't understand. This was never supported in the first place.

**Comment by tornadoyi** [comment]
> I don't understand. This was never supported in the first place.

That is impossible,  In the previous version, I can zoom into editor page by touchpad for checking small font.

**Comment by tessus** [comment]
Just because it worked does not mean it was intended to work or supported. But maybe I'm wrong. Maybe @laurent22 implemented gesture support just for macOS.

**Comment by tornadoyi** [comment]
> Just because it worked does not mean it was intended to work or supported. But maybe I'm wrong. Maybe @laurent22 implemented gesture support just for macOS.

This functionality is very important. As you know, I can not work for Joplin because of small font size.

**Comment by tornadoyi** [comment]
> > Just because it worked does not mean it was intended to work or supported. But maybe I'm wrong. Maybe @laurent22 implemented gesture support just for macOS.
> 
> This functionality is very important. As you know, I can not work for Joplin because of small font size.

Would you like to add back this functionality at next version ? I looking forward your next version. LOL

**Comment by CalebJohn** [comment]
You can change the editor font size in the config screen. I think maybe if this was supported before it's wasn't on the Joplin side, and maybe this is a big with Ace Editor. When was the last time you updated before it stopped working?

**Comment by tornadoyi** [comment]
> You can change the editor font size in the config screen. I think maybe if this was supported before it's wasn't on the Joplin side, and maybe this is a big with Ace Editor. When was the last time you updated before it stopped working?

I forgot， but I first use Joplin at February 1st.

**Comment by tessus** [comment]
@CalebJohn I think the switch to Electron 4 remove the gesture. I'm not sure, if that behavior was ever intentionally supported though.
