### ISSUE TITLE
Unreadable "Mermaid" preview using the "Dark" theme.

### ISSUE THREAD

**Issue by zohozer** [laurent22/joplin#1281]
I am using the latest Joplin 1.0.135 into a Windows10 PC, using the "Dark" theme and unfortunately the preview of the "Mermaid" charts are not readable.

Using this code:

```mermaid
graph TD;
A-->B;
A-->C;
B-->D;
C-->D;
```
I get this image, where I can't see the arrows. They need to be white on black background but seems that they are black on black background

![joplin_mermaid_preview1](https://user-images.githubusercontent.com/5983791/53547927-37a80680-3b28-11e9-9a73-eca7584088b3.png)

Another example:

![joplin_mermaid_preview2](https://user-images.githubusercontent.com/5983791/53547931-3a0a6080-3b28-11e9-99ac-f323799d97a1.png)

The code used is as follows:

```mermaid
sequenceDiagram
participant Alice
participant Bob
Alice->John: Hello John, how are you?
loop Healthcheck
    John->John: Fight against hypochondria
end
Note right of John: Rational thoughts <br/>prevail...
John-->Alice: Great!
John->Bob: How about you?
Bob-->John: Jolly good!
```

```mermaid
gantt
dateFormat  YYYY-MM-DD
title Adding GANTT diagram functionality to mermaid
section A section
Completed task            :done,    des1, 2014-01-06,2014-01-08
Active task               :active,  des2, 2014-01-09, 3d
Future task               :         des3, after des2, 5d
Future task2               :         des4, after des3, 5d
section Critical tasks
Completed task in the critical line :crit, done, 2014-01-06,24h
Implement parser and jison          :crit, done, after des1, 2d
Create tests for parser             :crit, active, 3d
Future task in critical line        :crit, 5d
Create tests for renderer           :2d
Add to mermaid                      :1d
```

**Comment by laurent22** [comment]
Please check again in next version.
