### ISSUE TITLE
Ran It at Win10 1803 ,just opened a window titled "Joplin",I see nothing in the window at all

### ISSUE THREAD

**Issue by 772b** [laurent22/joplin#1282]
### Operating system

- Windows 10 1803 x86

### Application

- Desktop

emmm....my English is not very good,sry.

I downloaded JoplinPortable.exe(v1.0.135) from releases, saved it in "F:\Program Files\Joplin\" and ran it, but it just opened a window titled "Joplin",I see nothing in the window at all.

![01](https://user-images.githubusercontent.com/47287126/53549643-ad839080-3b6f-11e9-8e89-433751b106ef.jpg)

![02](https://user-images.githubusercontent.com/47287126/53549649-b3797180-3b6f-11e9-9c37-902707fa282f.png)

![03](https://user-images.githubusercontent.com/47287126/53549658-b7a58f00-3b6f-11e9-9264-6bd59aabfac9.png)

How can I do?

**Comment by 772b** [comment]
I using Joplin on my Win7 SP1 x64 at home , and my Android phone too,but I am working on win10 1803 x86 now, can't use it , this made me sad

**Comment by laurent22** [comment]
Can you try to put the portable executable outside of Program Files directory? On your desktop for instance? Program Files has special permissions and the executable probably is not able to write the profile data.

**Comment by 772b** [comment]
> Can you try to put the portable executable outside of Program Files directory? On your desktop for instance? Program Files has special permissions and the executable probably is not able to write the profile data.

tks for reply , I put it on desktop and run again...but no working , still show me this

![04](https://user-images.githubusercontent.com/47287126/53556756-774e0d00-3b7f-11e9-9b24-8a507adc973f.png)

I don't think it's permissions has error , because I run it as administrators , and also like this

**Comment by laurent22** [comment]
Any chance you could enable debug mode and run the app again? https://joplin.cozic.net/debugging/ In particular it would be useful to see the content of the console as I assume there's an error message in there.

**Comment by 772b** [comment]
emmm....I‘m after work now, can't use my Win10 computer , I'll try that tomorrow,thank you very much

**Comment by 772b** [comment]
oh, btw, I think if I can copy the folder "/JoplinProfile" from my Win7 to Win10, saved it next to JoplinPortable.exe , will it working with that ? 
I'll try tomorrow

**Comment by Snawe** [comment]
I had the same problem on my phone today in the morning. I restated the app like 4 times and it always looked white... then after a minute it worked again.. I thought that it was maybe syncing something.

**Comment by 772b** [comment]
> I had the same problem on my phone today in the morning. I restated the app like 4 times and it always looked white... then after a minute it worked again.. I thought that it was maybe syncing something.

tks
I thought about your situation before, but I tried, and it did't work. 
I had waited half hour....noly white

**Comment by 772b** [comment]
> oh, btw, I think if I can copy the folder "/JoplinProfile" from my Win7 to Win10, saved it next to JoplinPortable.exe , will it working with that ?
> I'll try tomorrow

emmmm...did't worked

**Comment by 772b** [comment]
> Any chance you could enable debug mode and run the app again? https://joplin.cozic.net/debugging/ In particular it would be useful to see the content of the console as I assume there's an error message in there.

I ran it like this:

![00](https://user-images.githubusercontent.com/47287126/53615466-f2173680-3c18-11e9-8501-8207d2d69aa3.png)

and wait 10+ minutes bug.... u see T_T

**Comment by laurent22** [comment]
@772b, one important flag was missing from your command unfortunately. Please could you run it again using this command? `JoplinPortable.exe --open-dev-tools --log-level debug` This normally should open the console, which I think must contain some error or warnings.

**Comment by obert99** [comment]
Same problem on Win7. Did several clean (un-)installs (deleting the profile dir) and reinstalled the application. The debug parameters did not produce any output (neither console nor logfiles). Worked great until the upgrade to v 1.0.135.

**Comment by serenitatis** [comment]
> ### Operating system
> * Windows 10 1803 x86
> 
> ### Application
> * Desktop
> 
> emmm....my English is not very good,sry.
> 
> I downloaded JoplinPortable.exe(v1.0.135) from releases, saved it in "F:\Program Files\Joplin" and ran it, but it just opened a window titled "Joplin",I see nothing in the window at all.
> 
> ![01](https://user-images.githubusercontent.com/47287126/53549643-ad839080-3b6f-11e9-8e89-433751b106ef.jpg)
> 
> ![02](https://user-images.githubusercontent.com/47287126/53549649-b3797180-3b6f-11e9-9c37-902707fa282f.png)
> 
> ![03](https://user-images.githubusercontent.com/47287126/53549658-b7a58f00-3b6f-11e9-9264-6bd59aabfac9.png)
> 
> How can I do?

Try to switch Joplin to use Intel video card not discrete one. I have same problem in my laptop with Radeon video card.

**Comment by laurent22** [comment]
It seems to happen mostly with Chinese translation? @obert99, what language are you using in Joplin?

**Comment by obert99** [comment]
@laurent22: I am using the German translation.

**Comment by jpmv27** [comment]
I am upgrading my desktops from 1.0.125/1.0.127 to 1.0.135
On Fedora Linux 28 64-bit, no problem
On Windows 10 Pro 64-bit, no problem
On Windows 7 Home 32-bit, I do see this problem
Language is English everywhere

All I see is an empty window frame. There is no menu, there is no tray icon.

I tried following the debug instructions, but nothing happens. (After reverting
to an earlier version I do see the debug console, so the flags.txt file must
be correct.)

Nothing at all is written to log.txt

**Comment by laurent22** [comment]
So it seems the app is not longer compatible with Windows 32 bit? Could you all confirm if you are using Win 32 or 64 bit?

**Comment by laurent22** [comment]
This release should normally work fine with Windows 32-bit - https://github.com/laurent22/joplin/releases/tag/v1.0.137 Please could you give it a try and confirm?

**Comment by obert99** [comment]
I can confirm that v1.0.137 work fine again. And yes, still using Win7 32-bit. Thanks or the quick fix!

**Comment by laurent22** [comment]
Great, that's good to know. I'm leaving the post open in case someone still has an issue.

**Comment by jpmv27** [comment]
@laurent22 
Also happy to report that 137 resolved the issue for me.
