### ISSUE TITLE
Menu translation is missing

### ISSUE THREAD

**Issue by serenitatis** [laurent22/joplin#1285]
### Operating system

- Windows

### Application

- Desktop

In recent version (1.0.135) top level menu translation is missing. I see only English text. Other text is in Russian as expected.

![Bug](https://i.imgur.com/a29k5xj.jpg)

**Comment by dayfuaim** [comment]
Mac has it too:
![2019-03-01 16 18 13](https://user-images.githubusercontent.com/1274699/53640714-f30e8f00-3c3d-11e9-9109-8245fd14f7cc.png)
Joplin 1.0.135

**Comment by tessus** [comment]
Due to a bug in Electron (see https://github.com/electron/electron/issues/11106), the top level menu items had to prefixed with a `&`. Therefore the translations are missing and have to be adjusted.

**Comment by tessus** [comment]
Duplicate of #1283
