### ISSUE TITLE
Bullet list - Markdown problem

### ISSUE THREAD

**Issue by Snawe** [laurent22/joplin#1286]
### Operating system

- Windows
- Android

### Application

- Desktop
- Mobile

If you write a bullet list with
```
- text
  -
```
the text becomes a header 2.
the second "-" has to be at least 2 whitespaces or one tab stop to reproduce this

![grafik](https://user-images.githubusercontent.com/17966466/53644809-c6f00f80-3c37-11e9-951c-f28dec34504e.png)

**Comment by CalebJohn** [comment]
Funny enough this is a ["feature" of markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers). In your example it definitely seems like the wrong behaviour, but the way other people use markdown this is exactly what would be expected.

**Comment by Snawe** [comment]
oh, ok. than closed :D
