### ISSUE TITLE
File System Sync on iOS

### ISSUE THREAD

**Issue by akvadrako** [laurent22/joplin#1287]
On iOS I can select "File system" synchronisation. But what am I supposed to put for a path?

This is a rather unusual option for an iOS app, so some instructions would be appreciated. Is it supposed to appear in iCloud drive?

### Operating system

- iOS

### Application

- Mobile

**Comment by tessus** [comment]
I believe this is a bug. On iOS there's no userland filesystem as there is on Android. Apps can only use their own dedicated filesystem as part of the app. But maybe I'm wrong.

IMO, the iOS app should not allow you to sync with the file system.

**Comment by rezmarch** [comment]
Hi there. Struggling with the same issue: I'd like to sync both my iOS and MacOS apps using the MegaSync folder. Any ideas on how it would be possible?

**Comment by laurent22** [comment]
This cannot be supported on iOS
