### ISSUE TITLE
find with wildcard at begin of word

### ISSUE THREAD

**Issue by maxmopp** [laurent22/joplin#1288]
### Operating system

- Linux

### Application

- Desktop

Search in all notes
To be found: Donauschiffahrt
\*schiffahrt - no match
Donau\* - match

**Comment by maxmopp** [comment]
?

**Comment by laurent22** [comment]
This is actually working as expected, as described in the doc.

**Comment by maxmopp** [comment]
Thank you. I am sorry, I should have read the docs. Still inconvenient
