### ISSUE TITLE
Tags forced to lower case, even if upper case tag exists

### ISSUE THREAD

**Issue by braynebuddy** [laurent22/joplin#129]
### Operating system

- [x] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

I imported a bunch of Evernote notes. They had tags that were mixed case (e.g., "Acts"). These tags transferred just fine, but I can't add these tags to new notes I create in Joplin. If I add the tag "Acts" to a note, Joplin adds a new tag "acts" to the list of tags and assigns that tag to the note.

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---

**Comment by ryansyah** [comment]
I can confirm this behavior in macOS as well.
