### ISSUE TITLE
Duplicate info when pasting from some applications

### ISSUE THREAD

**Issue by jpmv27** [laurent22/joplin#1291]
### Operating system

Windows 10 Pro 64-bit

### Application

Desktop

### Issue

*Context*

When copying to the clipboard, some applications save the information to the clipboard in multiple formats, with the expectation that the receiving application will choose its preferred format.

For example, when copying to the clipboard MS OneNote saves the information in HTML, text and bitmap (image) format.

*Steps to Reproduce*

Select from OneNote and paste into new (empty) Joplin note.

*Expected Behavior*

Selected information is pasted once, as text (rationale: text is searchable and editable, so is more useful than an image.)

*Actual Behavior*

Selected information is pasted twice, once as text and once as an image.

*Additional Information*

If I paste into Notepad first and copy the text from Notepad into the clipboard to remove the additional formats, then pasting into Joplin only pastes text.

**Comment by laurent22** [comment]
Unfortunately I can't think of a fix for this and it seems to be specific to Microsoft's products. They shouldn't put an image in the clipboard if it's text that's been copied.

**Comment by jpmv27** [comment]
Hmm, maybe I'm missing something, but the fix seems straightforward.
There is a Joplin callback triggered in the capturing phase that checks for an image and, if found, adds it to the note.
Then the brace callback is triggered in the target phase that adds text if the clipboard has content in text/plain format.
Couldn't you check in the Joplin callback for content in text/plain format and skip inserting the image in that case?

**Comment by laurent22** [comment]
Well it's an open source app, so you're free to try your fix if it's straightforward.

**Comment by jpmv27** [comment]
I will, but I am having trouble building on/for Windows
