### ISSUE TITLE
Problem with iOS sync after using Desktop App Mac

### ISSUE THREAD

**Issue by titounet** [laurent22/joplin#1292]
### Operating system

- macOS
- iOS
Problem with iOS sync after using Desktop App Mac
### Application

- Desktop
- Mobile

First I've used iOS app, with Nextcloud sync, everything was ok. 
After that i've installed MacOS Desktop app, with Nextcloud sync, I've imported my Evernote notes, the Sync was OK (files on Nextcloud). But After that, I've errors message in iOS app, impossible to Sync.

After that, I've installed the Dropbox sync on MacOS Desktop app and iOS app. Everything was ok in the Desktop app, but after that, impossible to Sync with iOS app.

After that, I've deleted the Dropbox files, MacOS Desktop app and iOS app. I've installed first the iOS app, did the sync. After that i've Installed MacOS Desktop app, nothing was synced.

It looks like it's impossible to use the MacOS Desktop app and the iOS app in the same time.

**Comment by laurent22** [comment]
Hello, using the macOS and iOS app at the same time should work. Could you try to sync again and post here the error messages you're having?

**Comment by titounet** [comment]
I've delete all applications.
I've just reinstall the Mac Desktop App, and its very strange : the sync Begin, upload *.md files on the Nextcloud Joplin Directiry, but i see nothing : no "Carnets", no "Notes", no "Etiquettes" in the Joplin app ! .

[syncReport-1551634221313.txt](https://github.com/laurent22/joplin/files/2923427/syncReport-1551634221313.txt)

**Comment by titounet** [comment]
I've deleted all apps and files (local and server) and install the apps : everything is OK for the Mac Desktop app. After installing the iOS app, everything is OK for the Mac Desktop app, the Notes from  the Mac Desktop app the notes iOS app are synced with  the Mac Desktop app.

But there's a problem with the iOS app, files are not synced and there's error messages
![img_0088](https://user-images.githubusercontent.com/567711/53699483-0316a200-3de9-11e9-9726-9a3ba3747333.jpg)
![img_0091](https://user-images.githubusercontent.com/567711/53699484-06119280-3de9-11e9-9664-86a4eeedd525.jpg)
![img_0090](https://user-images.githubusercontent.com/567711/53699486-0873ec80-3de9-11e9-8415-9583e7925bee.jpg)
![img_0089](https://user-images.githubusercontent.com/567711/53699490-0ad64680-3de9-11e9-9c51-e22d5ba5fe25.jpg)

**Comment by laurent22** [comment]
It's hard to tell what's happening because some apps might still have some state while the server might have a different one, etc.

The best way would be to start over clean like this:

- Delete all Joplin data on Nextcloud
- Uninstall iOS app
- Delete profile on macOS app (delete folder ~/.config/joplin-desktop)
- Open macOS app
- Import Evernote notes
- Sync desktop
- Open iOS app
- Sync app

I'd expect this would work, but if you get any error message along the way, feel free to post them here.

**Comment by titounet** [comment]
I've exactly did this, in this order.
Mac Desktop app is OK.
But  iOS app doesn't sync

**Comment by titounet** [comment]
I restarted again from the beginning.
Too much errors.
I give up.
Thanks anyway.

**Comment by laurent22** [comment]
HTTP error 503 means "Service unavailable" so is it possible there's some issue with your server?
