### ISSUE TITLE
Import from .html

### ISSUE THREAD

**Issue by PopeRigby** [laurent22/joplin#1296]
Can you make it so we can import notes from .html files? I'm trying to transfer my stuff from Google Keep.

**Comment by lindadick** [comment]
I agree that built-in support for this would be great, however I just came across this utility which worked well for me: https://github.com/vHanda/google-keep-exporter. It converts Keep notes in .html format to Markdown, which can then be imported into Joplin.

**Comment by marcorichetta** [comment]
Also I recently tried [this project](https://gitlab.com/charlescanato/google-keep-to-evernote-converter) and it worked great!.
It converts Keep notes to txt or ENEX files.
