### ISSUE TITLE
not working on W7 after updating 

### ISSUE THREAD

**Issue by metrolan** [laurent22/joplin#1297]
### Operating system

- Windows 7

### Application

- Desktop

After updating last version, Joplin no longer works. It only shows the initial window without menu bar, and finally closes without any message. 
flags.txt created but it gives no changes.

Here is a screen capture.

![captura](https://user-images.githubusercontent.com/13301193/53793781-d40a4880-3f2e-11e9-963a-a2b5c4879ede.JPG)

**Comment by tessus** [comment]
fixed in pre-release https://github.com/laurent22/joplin/releases/tag/v1.0.137

**Comment by metrolan** [comment]
Yes, it works. Thanks.

**Comment by mathiasconradt** [comment]
I'm having similar issue on Mac OS X, where simply no window comes up when starting Joplin. I believe it was also since after I ran an app update recently.

**Comment by mathiasconradt** [comment]
This issue is a duplicate to https://github.com/laurent22/joplin/issues/1250

**Comment by tessus** [comment]
This was a Windows issue, which was fixed.
