### ISSUE TITLE
vi[m] mode

### ISSUE THREAD

**Issue by Henry78** [laurent22/joplin#1298]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop

Please add support for a "vim mode" that supports keybindings and operations as they are used in vi[m]. See https://codemirror.net/demo/vim.html for an very extensive example of vi mode in another JS-based editor.

At first there should be support for navigation (h, j, k, l, 0, $, ^, w, W, #w, b, B, #b, G, gg) and simple text editing like inserting text (a, A, i, O, o), manipulating text (x, dw, d0, d$, dgg, dG, dd, #dd) and copying/inserting text (yy, p, P) as well as undo/redo (u, Ctrl-r) and searching (/string, n, N).

**Comment by ShaneKilkelly** [comment]
Given that the editor is based on Ace, this shouldn't be too hard to do.
I'll look into it over the next week or so.

**Comment by flipjs** [comment]
It would be nice if vim mode could be added to command line version too.

**Comment by Double1996** [comment]
@ShaneKilkelly  Use vim like leanote

**Comment by jorfanakis** [comment]
> Given that the editor is based on Ace, this shouldn't be too hard to do.
> I'll look into it over the next week or so.

Any status update on this? I think this would be a massive improvement.

**Comment by ShaneKilkelly** [comment]
I've got a working feature branch, almost ready to go. I'll open a PR some time in the next few days, hopefully :)

Oh, and it also includes an `emacs` mode, in addition to the default bindings.

**Comment by ShaneKilkelly** [comment]
PR open: https://github.com/laurent22/joplin/pull/2056

**Comment by jorfanakis** [comment]
Thank you for your work on this. I’ve attempted to pull and build but I’m
running into version issues of packages. Seems like the SQLite package
specifically had been deprecated.

I’ve tried building on Linux Mint Tina and macOS Catalina

**Comment by Nebucatnetzer** [comment]
I wanted to try this feature but I can't find the new option for it.
![Screenshot from 2019-11-11 10-33-34](https://user-images.githubusercontent.com/2287221/68576670-ca969000-046e-11ea-8260-a5ee7086c848.png)

**Comment by ShaneKilkelly** [comment]
The option should be in the "General" section. I think the comment at the top of the pull-request is misleading, as the location changed during review.

**Comment by Nebucatnetzer** [comment]
Ah yes found it now, thank you :).

**Comment by de0xy** [comment]
> I've got a working feature branch, almost ready to go. I'll open a PR some time in the next few days, hopefully :)
> 
> Oh, and it also includes an `emacs` mode, in addition to the default bindings.

Thank you so much!!!! I think I've finally found my perfect note taking app now. Cheers.
