### ISSUE TITLE
Add archive folder

### ISSUE THREAD

**Issue by PopeRigby** [laurent22/joplin#1300]
Instead of deleting a note, sometimes you want to keep it, but don't want it to sit around in your active notebook, so there should be an archive folder to put them there.

**Comment by tessus** [comment]
I don't understand. Create an `Archive` folder and move the note there.

**Comment by PopeRigby** [comment]
I have that already. I just think it would be easier to have built in archiving, so we can have things like 'add to archive' in the context menu.

**Comment by tessus** [comment]
Ah, I see.

**Comment by justyns** [comment]
See https://discourse.joplin.cozic.net/t/support-for-archiving-notes/1121 as well.  I had a similar request, but have been using the todo system for this since then.   I still agree that it would be nice to have a specific archive option in the ui though.

**Comment by PopeRigby** [comment]
@tessus How do I re-open these? I think they're still important.

**Comment by laurent22** [comment]
I don't really see this feature happening as it's easy enough to simply move the note to any folder you want.

**Comment by PopeRigby** [comment]
True, but the specific functionality surrounding the archive folder would be the useful part. Specifically, a context menu item for "Add to archive". The archive folder could also categorize the archived note under a notebook named after the one the note was previously contained it. That sounds confusing, but I don't know how to make it sound less confusing.

**Comment by laurent22** [comment]
I see what you mean, it would be convenient. I'm reopening in case someone is interested in creating a pull request for it.

**Comment by tessus** [comment]
@PopeRigby I'm sorry, I never received a notification that you asked me a question. To answer your question: Issues can only be re-opened by the owner of the repo and collaborators.

**Comment by PopeRigby** [comment]
@tessus It's alright. It's been resolved (:

**Comment by wessel145** [comment]
Announcing my support for this request! I don't have any JS experience, but would love to see archiving.

**Comment by Perkolator** [comment]
GSoC 2020 candidate?

**Comment by laurent22** [comment]
Yes, could be. For me what would be interesting with the archive concept is if we can somehow move these notes out of the way when syncing. i.e. they go to a special folder on the sync target and it doesn't need to be synced frequently since this is just old content that doesn't change. Perhaps an archived note should be immutable, and would need to be unarchived in order to change it.

All that would make the app more scalable as it wouldn't matter even if there are millions of files as long as they are out of the way in the archive folder.
