### ISSUE TITLE
Newly-imported folder not syncing

### ISSUE THREAD

**Issue by fonnesbeck** [laurent22/joplin#1301]
### Operating system

- Windows
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

I've imported a folder of markdown files with the Windows app, and they are imported and saved to dropbox, where everything is being synced. However, when I try to sync on any other devices (iOS, android, terminal), these new files do not sync across. 

I get an error saying that it is processing a path that has already been done ... sync_time was not updated? Remote item has and  updated_time in the future?

Unfortunately, I'm not able to interpret these errors. In any case, only one client has the correct state.

**Comment by omniviator** [comment]
Hello there!
Same here, but no error message.
The android app has chosen only the 3 top notebooks to sync and that's it.
The sync between my windows PC and my Linux Mint works fine (17 Notebooks ans some sub-notebooks). I'd love to be to able to use Joplin on my Smartphone! Any help would be greatly appreciated! :-)

Operating system :
    Windows
    Linux
    Android

Application :
    Desktop
    Mobile

**Comment by xuhcc** [comment]
I'm experiencing similar problem on Android (1.0.242) with file system sync. The app seems to be syncing only new objects. Objects which were created on Desktop app before I had configured sync are ignored by Android app.

**Comment by asifbacchus** [comment]
Same issue here as @omniviator and @xuhcc using latest app on Android Oreo.
No errors recorded in the log (just shows 0 for total notes, total folders, total resources).  Using filesystem, permissions are granted.  Markdown files actually exist in the folder, I can open and read them manually.  They are encrypted, however, and the app recognizes that it needs a master key but doesn't not have it.  New items will sync flawlessly.  If I switch to using WebDAV or something, everything syncs properly.  It seems like the app is just ignoring the fact that files are in the folder :-(  I used to use WebDAV but it just got way too slow with 75 notes, so I wanted to try file sync instead hoping it would be faster.

Any help appreciated, or I can provide whatever additional information is requested.  Thanks!

**Comment by asifbacchus** [comment]
Cleared data, uninstalled, SHUTDOWN AND RESTART phone then reinstalled... everything syncs EXCEPT the master key.  Can this be copied/synced manually somehow?  Does that file have a special name I can search for to make sure it's actually being copied?

**Comment by Dasymi** [comment]
I had a similar problem. 3500 notes, took a long time to sync to Android and iOS using Dropbox with encryption. The master key never arrived so I gave up and, as a last resort, went back to WebDAV without encryption on local NAS. Luckily that worked.

**Comment by asifbacchus** [comment]
Not an impressive solution, but I noticed that my main client (computer) was showing encryption was enabled but not listing a key.  Decrypted everything, created a new key and then re-synced everything to my file-share.  Uninstalled and reinstalled the app on the phone and then everything started working.

File-system sync seems pretty finicky to get set up at first if you're starting with a backup.  But, everything is working again and much faster than straight WebDAV.  Nice to have my Joplin back up and running!
