### ISSUE TITLE
Adding another to-do item on mobile takes too many clicks

### ISSUE THREAD

**Issue by PopeRigby** [laurent22/joplin#1302]
You have to:
- click the plus
- click add to-do item
- type your item
- click back once to get to the edit screen
- click back again to get to the main notebook screen

Maybe it could be streamlined by letting you click the line below the checkbox item you just wrote, and write another item.

**Comment by warsix4** [comment]
Also having this issue with the Android client. 

I'm having a lot of trouble understanding how the notebooks/notes/to-do items are working in general. Not sure if a notebook should have a list of to-do items or if a to-do items is supposed to have multiple checkboxes somehow.

**Comment by PopeRigby** [comment]
How can I re-open this @laurent22
