### ISSUE TITLE
markdown's  "```mermaid " does'nt work in Android?

### ISSUE THREAD

**Issue by 772b** [laurent22/joplin#1306]
### Operating system

- Android

### Application

- Mobile

first。。。tks for your help in #1282，also my English is not very good ，sry

Then I wirte a MD file on PC used Joplin，like this：

![01](https://user-images.githubusercontent.com/47287126/53854732-95938d00-4005-11e9-9dc4-cb46f48d6253.png)

But it opened in my Android phone used Joplin like this：

![02](https://user-images.githubusercontent.com/47287126/53854778-bfe54a80-4005-11e9-86d1-342162c25ddd.jpg)

。。。I don't know why, would u help me?

**Comment by 772b** [comment]
BTW
Joplin in PC is v1.0.137, in Android is v1.0.237

**Comment by tessus** [comment]
It says it right there in the release notes:

**New: Experimental support for Mermaid graphs (This is not yet supported on mobile).**

/ref https://github.com/laurent22/joplin/releases/tag/v1.0.135

**Comment by 772b** [comment]
> It says it right there in the release notes:
> 
> **New: Experimental support for Mermaid graphs (This is not yet supported on mobile).**
> 
> /ref https://github.com/laurent22/joplin/releases/tag/v1.0.135

ok, sry, my bad
