### ISSUE TITLE
Cannot sync Notebook with name containing a space

### ISSUE THREAD

**Issue by jpmv27** [laurent22/joplin#1311]
### Operating system

- Windows 10 Pro 64-bit

### Application

- Desktop 1.0.135

### Description

**To reproduce**

- Create a Notebook with a name containing a space, e.g., "Wish Lists"
- Sync

**Expected behavior**

- Sync is successful

**Actual behavior**

- Sync fails

**Comment by laurent22** [comment]
Error message?

**Comment by jpmv27** [comment]
Yes, would like to post it but didn't capture it at the time and now the app is in serious trouble, see next issue.

**Comment by jpmv27** [comment]
My apologies, but it seems I cannot reproduce it any longer :-(
Feel free to close and I can reopen if I encounter it again

**Comment by okoetter** [comment]
The default notebook name `"Welcome to Joplin!"` contains two spaces and syncs just fine.

**Comment by tessus** [comment]
Yea, let's close this issue for now. @jpmv27 please re-open it, if this happens again.
