### ISSUE TITLE
DNS Query Fails (NextCloud WebDAV URL synchronization)

### ISSUE THREAD

**Issue by ermin-sakic** [laurent22/joplin#1313]
### Operating system

- Linux
- Android

### Application

- Desktop
- Mobile

Resolving an A/AAAA DNS query may lead to multiple results, of which currently the netcode only selects the first IP address, that might potentially be old/cached by the router DNS server for whatever reason.

i.e.: My NextCloud server (```server.fritz.box```) is configured with an IP address: ```192.168.178.62```

```nslookup``` on the remote Joplin client returns two IPv4 addresses:

```bash
➜  ~ nslookup server.fritz.box
Server:		192.168.178.1
Address:	192.168.178.1#53

Name:	server.fritz.box
Address: 192.168.178.62
Name:	server.fritz.box
Address: 192.168.178.75
```

Joplin fails on NextCloud synchronisation with issue ```EHOSTUNREACH``` try as it only polls the ```192.168.178.75``` address instead of both above with following error:
```
request to http://server.fritz.box/nextcloud/remote.php/dav/files/admin/Joplin/ failed, reason: connect EHOSTUNREACH 192.168.178.75:80 (Code EHOSTUNREACH)
```

**Comment by tessus** [comment]
IMO, this is a problem with the DNS server on your router. DNS should only return IP addresses which are reachable. If they are not, the DNS server is configured incorrectly.
Please contact your router manufacturer.

**Comment by ermin-sakic** [comment]
Thanks, closing the issue in this case.
