### ISSUE TITLE
[Feature Request] Location based reminders

### ISSUE THREAD

**Issue by PopeRigby** [laurent22/joplin#1314]

**Comment by mollusko** [comment]
+1

**Comment by trymeouteh** [comment]
+1

**Comment by ssakatausa** [comment]
+1

**Comment by laurent22** [comment]
> Location based reminders

meaning?

**Comment by ssakatausa** [comment]
A location based reminder is a reminder given when you reach a prespecified location. I can make a location based reminder on my Nexus 6p in the following way:
  1. Say "Hey Google, I want to set a reminder".
  2. Answer the question, "What's the reminder?"
  3. Say "When I get to .... " answering the question about the desired timing of the reminder.
It would be great if a Joplin note can be brought up based on the location.

**Comment by PopeRigby** [comment]
Bump
