### ISSUE TITLE
Issues when imported from existing folder

### ISSUE THREAD

**Issue by frank777777777** [laurent22/joplin#1317]
### Operating system

- macOS
- Linux

### Application

- Desktop

I am doing a daily backup of the joplin sync repo, in case of anything important being deleted.

When I wipe .config/joplin-desktop/, and set the the synchronization directory to my backup folder. It regenerates duplicated default tags. 
In the folder, there are a lot of duplicated .md files as well. Those .md files that refers to tags and images, even though tags and images were no longer there.
<!--

**Comment by foxmask** [comment]
Why don't you do :
```
cd  .config/joplin-desktop/
rsync -avz pathtobackupfolder .
```
Because it may be possible that hash file are calculated from the path where the files are
