### ISSUE TITLE
[Feature Request] Webclipper - sort tag list

### ISSUE THREAD

**Issue by CollinChaffin** [laurent22/joplin#1319]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

As it relates to all OS' and clients (potentially) I do not have the capability to confirm whether there is any active sorting applied on other clients, but on Windows as it relates to the Webclipper (which is awesome, BTW) the one annoyance coming from someone using it a LOT is that as I add and make good use of tags, the current list loading simply pulls the tags in the order in which they were added over time, which is not very intuitive.  If I added a tag months ago on my ever-growing list, I often wind up having to literally type almost every one (at least partially) because finding them scattered in non-alpha order has become far too time-consuming.

Whether it is a new option that can be enabled/disabled, or simply new behavior that replaces the "load what we have" current method of no sorting, I would ask for consideration of a feature request to in some way allow even just a simple alphabetical sorting for the tag list.

Thanks and keep up the awesome work Joplin has quickly replaced all as my go-to note-everything app!

**Comment by rcrx** [comment]
I'm on Linux and list-loading does not work *at all*. I'm not sure if the issue is specific to my system, but I don't believe it is. This has been the case with multiple distros and DEs.

**Comment by rcrx** [comment]
Note, however, this may be due to using Vivaldi rather than actual Chrome.
