### ISSUE TITLE
[Feature Request] Show sub-notebooks when parent notebook is selected 

### ISSUE THREAD

**Issue by PopeRigby** [laurent22/joplin#1320]
It should show them along with the other notes contained in the parent notebook, along with maybe a notebook icon to differentiate.

**Comment by StoltHD** [comment]
A feature to select if you want to show sub notebooks and sub notes recursive would be nice

**Comment by PopeRigby** [comment]
Oops. How do I get this re-opened?

**Comment by laurent22** [comment]
I don't understand this feature. If you simple-click a notebook, it will just select it. If you double-click it will open it and show the sub-notebooks. I think this is the normal behaviour, unless I'm missing something.

**Comment by PopeRigby** [comment]
Yeah. I don't remeber why I though this was a good idea.
