### ISSUE TITLE
1.0.140 md rendering update broke checkboxes in tables

### ISSUE THREAD

**Issue by eyriewow** [laurent22/joplin#1324]
### Operating system

- Windows

### Application

- Desktop

I used checkboxes inside tables quite a lot. Unfortunately, the latest update (1.4.140) broke this functionality completely. Please consider adding it back.

Screenshot of the issue: 
![](https://i.imgur.com/vLYeztb.png)

**Comment by tiaga** [comment]
Android application is also affected

**Comment by laurent22** [comment]
Unfortunately checkboxes in tables were possible as a result of a bug, which has now been fixed. Neither checkboxes nor lists are supported within Markdown tables (if you try on GitHub, it won't work either) and I'm afraid it won't be possible to support them again.

I can only suggest to move checkbox lists outside of tables.

**Comment by Tekki** [comment]
> (if you try on GitHub, it won't work either) and I'm afraid it won't be possible to support them again.

On Github you can write
```
| first | second |
| -- | -- |
| <ul><li>- [ ] one</li></ul> | <ul><li>- [ ] two</li></ul> |
```

| first | second |
| -- | -- |
| <ul><li>- [ ] one</li></ul> | <ul><li>- [ ] two</li></ul> |

A bit complicated, but if we have a list of tasks with different subcategories it would be very useful.
