### ISSUE TITLE
folders sorting on android

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#1328]
### Operating system

- Android

### Application

- Mobile

### description 

the order of the display of the folders on android is from Z to A and can't be changed. No option is available to change that like on desktop app.

**Comment by laurent22** [comment]
Even in the latest version? I think I've fixed this?

**Comment by subi54** [comment]
This is fixed in the latest update.

**Comment by foxmask** [comment]
yes nice, i didnt see the 1.0.241 ;)
thanks
