### ISSUE TITLE
iOS Syncing local files

### ISSUE THREAD

**Issue by smhearty** [laurent22/joplin#133]
This looks extremely interesting. Although I see in the documentation that synchronization is available through OneDrive or local file, I don't see an option in iOS to select a local file. 

I set up syncing the files to Box.com (yes, I understand that there needs to be some more work done for that to work correctly). The files show up in the Files app, but Joplin is not an option to open them. Is there another way to synchronize to iOS without using OneDrive?

### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [X] iOS

### Application

- [ ] Desktop
- [X] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---

**Comment by tommyguitfiddle** [comment]
It is the same situation on Android.  I use Syncthing for all of my cross-device needs, so saving to the file system would make this app way more useful to me as well.

**Comment by Nepochal** [comment]
Same here. It would be nice to be able to sync the local files via Syncthing on all devices.

**Comment by laurent22** [comment]
I don't believe it's possible to access directory directly in iOS so this feature probably can't be done.
