### ISSUE TITLE
UI: Separate cancel and back in config page

### ISSUE THREAD

**Issue by episk** [laurent22/joplin#1330]
### Operating system
- Windows
### Application
- Desktop

Please do not combine a back arrow with a cancel button. It's bad practice and creates confusion. A cancel action means for most users *abort*, *revert* or *return* **without making changes** – regardless if they have been applied or not. If a user applies new settings, a cancel option should no longer be present. As of now (v.1.0.140) clicking "Apply" in config leaves "Cancel" as only option to return out of the options/config page.

**Comment by laurent22** [comment]
That's a good point - I guess it could simply be renamed "Close" or do you have some other suggestion?

**Comment by episk** [comment]
There are several alternatives solving this, but I think the easiest would be to have a separate back-button that is either
A. active only when changes have been made.
B. Active at all times, but prompting the user when detecting unsaved input. (Performing the back-action without saving is considered a destructive action and a prompt is therefore recommended.)

**Comment by episk** [comment]
Fiddled with this today and made a mockup of how this could be implemented without any major changes in how the settings are structured. Now obviously there's more to this example than just addressing the issue at hand, but hey, it's spare time, so I got to make it fun.

Looking past the styling, I hope it still manages to illustrate what I was thinking. This solution is very close to general UI standards, particularly Windows, and I have tested it with good results on other applications.

But, perhaps as ground for discussion, I'm not completely sure a confirmation prompt is totally viable in this case since there aren't really any critical consequences if the user fails to save or saves by mistake (?). On the other hand, the prompt don't force the user to repeat any process, and will only show up on unconfirmed changes. Generally Windows users less likely to complain on this behavior than Mac users, since they are more accustomed to having the settings apply instantly.

Room for improvement, but I'd say it's a step up from the back/cancel combo.

https://episk.design/joplin-settings.gif
https://episk.design/joplin-still.png

**Comment by laurent22** [comment]
Since this post was made the back was labelled "Cancel" as I think it makes it clear enough, and it means there's no need for the extra confirmation dialog:

<img width="456" alt="image" src="https://user-images.githubusercontent.com/1285584/57316361-873d1c80-70ed-11e9-9339-ed7b7f5f4ceb.png">

**Comment by episk** [comment]
This is no change. This is wrong, as I explained in my previous posts.

**Comment by laurent22** [comment]
For now, the current UI is good enough, though not perfect. I'd accept pull requests that improve this.
