### ISSUE TITLE
Joplin 1.0.140 (prod, darwin) not showing any windows on Mac OS X (10.13.6 (17G5019))

### ISSUE THREAD

**Issue by mathiasconradt** [laurent22/joplin#1332]
### Operating system

Mac OS X High Sierra 10.13.6 (17G5019)

### Application

Desktop

### Issue Description

When starting Joplin, no windows are shown at all anymore (not sure when this happened, but I assume since an update. 
I have two MacBooks running, both with the same Joplin version 1.0.140.
One MacBook runs MacOS Mojave 10.14.3 and there I have no problem.
One MacBook runs MacOS High Sierra 10.13.6 and there I have this problem (though it worked on that one as well previously, and I assume it came with an update or something).

In the Mac logs, I see this:

`AEGetDescData of non-desc type 'reco' not a good idea`

![Screen Shot 2019-03-12 at 2 32 53 PM](https://user-images.githubusercontent.com/295122/54204320-4d2c1180-44d4-11e9-8b45-ce27a3927a8c.png)

Googling for above mentioned error, it seems that it's somehow related to recent OS X versions, where apps in general (not Joplin related) stop working, though I see people report it for High Sierra as well (which I have as well on one MBP and where Joplin runs fine), not only Mojave.

**Comment by tessus** [comment]
I've been trying to find out anything in the Apple developer forums, but the posts there are - like most of the time - useless. People have no clue why this is happening, there doesn't seem to be a solution and Apple, well guess what, doesn't give a damn as always.
I will try to get more info on that error.

**Comment by laurent22** [comment]
It might be due to the recent Electron upgrade. Is there maybe some issue about it on their GitHub tracker?

**Comment by tessus** [comment]
I've checked the electron issue tracker already. There are no open or closed issues mentioning the word `AEGetDescData`.

**Comment by jmarccourtiade** [comment]
I've had the same issue this week. Have uninstalled/reinstalled Joplin a couple of times. I thought it was probably linked to an installation of the Mono library, as it seemed to have occurred afterwards (Mono uninstalled now). Anyway, I've tried again today to install Joplin again and have noticed a little "graphical thing" (or a "white line") on the left side of my screen that I had not seen before. Just pulled on it: it was Joplin's window reduced to the max, as a simple box as big as a line. Problem solved. 

FYI: i'm using a dual screen.

**Comment by mathiasconradt** [comment]
@jmarccourtiade yes figured it was a window size of just a line height and finally found it somewhere on the screen, also got it showing by manually resizing it.
