### ISSUE TITLE
Clipper enhancement: save URL of clipped page

### ISSUE THREAD

**Issue by maxf** [laurent22/joplin#1335]
### Application

Web clipper

### Description

It would be nice to include a link to the saved page. Or even just the title of the page and a link to it.
As a user of Joplin to bookmark pages, I don't always need an actual clip of pages. Just having the option to save the page's URL would be nice.

**Comment by laurent22** [comment]
This PR implemented exactly what you want:  https://github.com/laurent22/joplin/pull/1173 I just need to release the updated clipper with this change.

**Comment by maxf** [comment]
awesome :+1: 
Joplin's fantastic

**Comment by Nebucatnetzer** [comment]
Always great to see that an issue is already solved before I can open it :)
