### ISSUE TITLE
Attachment was not downloaded or decrypted yet

### ISSUE THREAD

**Issue by heidlma** [laurent22/joplin#1336]
### Operating system
- iOS

### Application
- Mobile

Joplin works great for me on Desktop (macOS) but on my iOS application, I found some notes with attached PDFs (pulled them in on desktop using drag and drop). 
When I try to open the PDF on my iPhone, it gives me error "This attachment was not downloaded or not yet decrypted".  This is not for all notes like this, but for some. 

And if I look into the encryption configuration section, it tells me:
Encryption: activated:
Decrypted objects: 453 / 461

No errors are shown in the debug log. 

Thanks for your help.

**Comment by n00b12345** [comment]
I have this issue. Attachments aren't being downloaded.
