### ISSUE TITLE
Order Notebooks by Keyboard (Windows)

### ISSUE THREAD

**Issue by washere** [laurent22/joplin#1338]
### Operating system
- Windows
### Application
- Desktop

In any good Outliner Tree pane, re-ordering the nodes in the Left Outline Tree Pane is a Vital Basic.

Currently reordering nodes in the Notebooks (most Left Pane) by mouse is impossible for certain nodes on Windows version.

I have 3 nodes in Notebooks pane:

Welcome! (default demo file with new Joplin)
DiskFolder (Local Folder of Markdwon files, with subfolders)
Personal Notes

I want the order reversed with Welcome! at bottom and Personal Notes at top.

It does not do this.

It either puts the notebooks inside each other or just does not put certain nodes (notebooks) at top. I tried for half an hour.

Even the functions it does do, takes many tries.
Moving notebook nodes in the left pane is very buggy.

For moving nodes/subnodes orders, All good Tree Outliner nodes have;

1) Keyboard Shortcuts 
2) Menu Operations to move currently focused (highlighted/selected) node/subnode in tree

The operations are:
i) Move Node Up
ii) Move Node Down
iii) Move Node Right (indent right: make node child or subnode of Node immediately above)
iv)  Move Node leftt (indent left: move node one level higher)

Usually these are keyboard combinations of CTRL or ALT or SHIFT with ArrowKeys.

For example:

Click (set focus, highlight/select) on Node (Notebook) in left pane you want to move:

Up/Down are Orders in the Tree:
Move up in Tree: CTRL+ArrowKey Up
Move down in Tree: CTRL+ArrowKey Down

Left/Right are subnode levels within another node:
Move left in Tree: CTRL+ArrowKey Left
Move right in Tree: CTRL+ArrowKey Right

If a node is at root (highest level) it will not Move Left any more
If a node is at lowest level of parent node, it will not Move Right any more, it is at current deepest subnode level

Thanks again for Joplin.

**Comment by bmxmaza** [comment]
It would be nice if the same ordering way would be implemented in linux version.

**Comment by i-need-to-tell-you-something** [comment]
This is a duplicate of #51, but has nice example of shortcut keys that could be used. Maybe this should be closed and the text move to a comment there?
