### ISSUE TITLE
Cannot update synchronization details

### ISSUE THREAD

**Issue by matthewmoppett** [laurent22/joplin#1339]
### Operating system
- Linux
### Application
- Desktop
---------------------------------
I found today (after returning to Joplin after a break) that clicking "Synchronise" had no effect. There was no warning or any other kind of response -- just nothing happened whether I clicked the button in the sidebar or chose the "Synchronise" option from the File menu. Looking at log.txt, I found the following lines:

```
2019-01-14 07:42:01: "Could not run background sync:"
2019-01-14 07:42:01: "Error: The caller does not have permission to perform the action.
Code: accessDenied
```
I guessed that I must have changed my OneDrive password at some stage, so I looked for some way to update my synchronisation authorisation details via the Joplin GUI -- but after a careful search I couldn't find any. In the end I deleted the sqlite database in ~/config/joplin-desktop and tried again, which solved my problem -- Joplin just rebuilt the database and synchronised all my old data after prompting me for my OneDrive login details.

I think it's pretty important that (1) if there's a problem synchronising, the user should be informed about what's happening, and (2) there should be a way to update synchronisation authorisation details via the GUI.

My log file:
[log.txt](https://github.com/laurent22/joplin/files/2964982/log.TXT)

**Comment by foxmask** [comment]
did you use Encryption before and did you disable it since then ?

**Comment by matthewmoppett** [comment]
I can't remember for sure, but my "Tools -> Encryption Options" screen says:

> Status
> Encryption is: Disabled
> 
> Decrypted items: 565 / 565

Which suggests that I did in fact do that.

**Comment by foxmask** [comment]
and in the screen encryption settings, you have no "master key" with a created date in front of one of them ?

**Comment by matthewmoppett** [comment]
Not that I can see, no.
