### ISSUE TITLE
table of contents

### ISSUE THREAD

**Issue by peng19832** [laurent22/joplin#1340]
Hi，how to automatically generate a table of contents？
I tried using [toc], but it didn't work.

### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

**Comment by subi54** [comment]
Because it is not yet supported. markdown-it plugins can be integrated now. Perhaps make a toc plugin case for that, till then good old html ahref id manual toc creation.

**Comment by tessus** [comment]
Duplicate of #478
