### ISSUE TITLE
[Feature Request] - Support bibtex

### ISSUE THREAD

**Issue by theinfinityproject** [laurent22/joplin#1349]
Hi,
first off thanks for ur efforts and this amazing piece of free software! I'd like to request a feature that might prove useful to others as well. I use joplin mainly as my research diary, while it is great at what it offers, it lacks one important feature for me: citation and references. Since most bibliography/reference-management-tools like zotero, mendeley, endnote etc. support the export and auto-syncing of the bibliography as a bibtex file it would enrich joplin a lot, if joplin would be able to read a bibtex file defined by the user and then create a citation or reference automatically. In conjunction with #1166 it would enable proper citation and reference management in joplin.

**Comment by franzperdido** [comment]
Excellent idea, I had already drafted a similar feature request but had no time to finish it.

**Comment by theinfinityproject** [comment]
Reading my request this morning again i realized that some additional information might be useful.They way it would work is like this: A bibliography/reference-management-tool like zotero creates for every reference an entry in a bibtex file with all the information on author, publisher, year, etc and it also creates a citation key. This key looks like this: [auth][year] for example johnson2005. Now if this key gets called in LaTeX with \cite{johnson2005} or in markdown in this case with (@johnson2005) it will create a reference or citation based on a user defined style and also (if needed) add the title to a  bibliography.
