### ISSUE TITLE
weird characters appearing while inputting in Korean(possibly multibyte chars?)

### ISSUE THREAD

**Issue by jeremychoi** [laurent22/joplin#1351]
### Operating system

- Windows

### Application

- Desktop

While editing notes in Korean, something broken stuff appears like the attachment (red colored circle). This only happens in the note content taking area. It's okay in other input forms like search or note title .
Not sure if this issue is only relevant to Korean.

![20190318_124713](https://user-images.githubusercontent.com/25311915/54503827-b43a4200-497c-11e9-9dc7-2dcf351eaeaa.jpg)

**Comment by jeremychoi** [comment]
This seems to be the same issue as https://github.com/laurent22/joplin/issues/113, but it occurs in the Windows application.

**Comment by foxmask** [comment]
on linux i don't see that behavior
![Sans titre](https://user-images.githubusercontent.com/208212/55276128-30734480-52f0-11e9-80d2-87a881dc0ed5.png)

**Comment by Icy-Breath** [comment]
Problem still exists.
