### ISSUE TITLE
Sync error "Processing a path that has already been done"

### ISSUE THREAD

**Issue by jpmv27** [laurent22/joplin#1353]
### Operating system

Windows 7 Home 32-bit

### Application

Desktop 1.0.140

### Description

Observing intermittent sync errors per the below. Error resolves itself on the next sync.

![sync](https://user-images.githubusercontent.com/1688977/54534998-f5722800-4963-11e9-9bf3-125c97bca0b4.png)

This seems to happen if I am typing in a note at the moment that a scheduled sync happens.

**Comment by virtadpt** [comment]
It happens with 1.0.140 on MacOSX and the Linux 64-bit .appimage, too.

**Comment by tessus** [comment]
This is not a new issue. This always has happened in ceratain situations. This is not a bug.

**Comment by jpmv27** [comment]
@tessus 
The message says "error". If it's somehow "normal" or "expected", then the code should check for it and not display an error message.

**Comment by tessus** [comment]
I didn't say that it's _normal_ or _expected_. I said it's not a bug.
It is an error in the sense that the sync algorithm hit an edge case which results in an error. But it's not a bug. If you hit sync or wait for the next scheduled sync, the error is gone.

e.g. take a copy operation from one filesystem to another. The copy fails with an error, if there's not enough space on the target filesystem. This is also not a bug, but a valid error.

**Comment by tessus** [comment]
Please also see [Laurent's comment](https://discourse.joplinapp.org/t/getting-sync-errors/2027/2?u=tessus)
