### ISSUE TITLE
Reset search when notebook is selected

### ISSUE THREAD

**Issue by jpmv27** [laurent22/joplin#1354]
### Operating system

- Windows

### Application

- Desktop 1.0.140

### Description

**To reproduce**

Enter a search phrase. A list of notes matching the search phrase is displayed.
Manually select a notebook.

**Expected behaviour**

The search is reset and the notebook contents are displayed.

**Actual behaviour**

The notebook contents are displayed, but the search is not reset, so it still looks like what is displayed are search results.

**Comment by tessus** [comment]
This is intentional.

Why would you want to do that? It is also possible that you want to edit several notes with that search term. Resetting it would require you to search again, even though you already have all the notes you want.

**Comment by Dasymi** [comment]
I’ve noticed that too and thought it was odd. It would make more sense to me if, when you select the **notebook**, the search remains active and only displays the notes in that notebook that match the search. As it is, you see all the notes in the notebook and the search box erroneously suggests that they match the search.

**Comment by jpmv27** [comment]
@tessus 
If you manually select a **notebook** (not a note), then all the search results are replaced with the notes from that notebook, so you can't edit any more notes from the search.
I agree with you that you wouldn't want to do this when selecting a **note** from the search results.

**Comment by tessus** [comment]
@jpmv27 thx, my bad. I read note instead of notebook.

You are right. In that case the search field should be cleared. @laurent22 can I label this as a bug?

**Comment by innocuo** [comment]
this is related to #1186 
If search is not reset when you click on a notebook after a search, search matches inside notes will remain highlighted.

I'm submitting a PR for this

**Comment by innocuo** [comment]
I'm closing this one, it was fixed by PR #1504
