### ISSUE TITLE
cant load pics

### ISSUE THREAD

**Issue by dasnnj** [laurent22/joplin#1356]
### Operating system

- Android

### Application

- Mobile

in miui10 with android 9, it unable load pic correctly（I mean,  can't load pic, it's blank.）,but it`s normal on Windows

**Comment by foxmask** [comment]
You can't see picture you added with windows from the mobile ?

can you provide the joplin android version ? (you can find it from the menu configuration, at the bottom of that screen 'Joplin 1.0.???')

**Comment by dasnnj** [comment]
> You can't see picture you added with windows from the mobile ?
> 
> can you provide the joplin android version ? (you can find it from the menu configuration, at the bottom of that screen 'Joplin 1.0.???')

joplin version ：1 0.241
i added picture with mobile。but i cant see it in preview.
i can see it with windows10,i think it's no problem with Markdown grammar。please know

**Comment by dasnnj** [comment]
The picture I added came from the Internet,
like `![](https://xxx.xxx.com/xxx.jpg)`
please know

**Comment by NothingCtrl** [comment]
Do you try to force close app the re-open?

**Comment by dasnnj** [comment]
> Do you try to force close app the re-open?

sure, I even opened it a day later, but it didn't seem to work.

**Comment by undecomposed** [comment]
Seeing similar behavior. For me, only force-closing the app works. It works this way in both directions - Android to Windows and vice versa. Syncing through Next Cloud.
