### ISSUE TITLE
All notes deleted after new client added

### ISSUE THREAD

**Issue by stalker314314** [laurent22/joplin#1358]
Repro:
* Have a bunch of notebooks on one machine (Windows both), synced to Nextcloud
* Install Joplin on a new machine (you get Welcome notes there)
* Delete Welcome notes (so, there is 0 notebooks now)
* Go to Tools->General Options and configure Nextcloud sync
* Check it is working, press OK
* Press "Synchronise"
* There was some text saying that something was deleted/modified, but I cannot remember
* Watch in horror as your Nextcloud client is removing all .md files from all your machines as you question you life choices
* Joplin shows 0 notebooks with no (obvious) way to do anything to restore old notebooks

I managed to scavenge bunch of .md files directly in Nextcloud joplin/ directory. Not sure if there is something missing though.

This is either bug in my usage, or bug in app, or just very weird UX. I tried to do what I *assumed* will sync my existing notes on new machine, but I got sync other way around and my joplin seems to be wiped.

**Comment by tessus** [comment]
Yea, in that case you should not lose any data. The only time you _can_ lose data is, if you switch the sync target. But since you didn't have one in the first place, there shouldn't be any deletion of your local notes.

@laurent22 will have to have a look at it...

**Comment by stalker314314** [comment]
My apologies. After looking at original machine, it still have data. I missed subdirectory on new machine and I (accidentaly) synced empty notes. I will optimistically close this issue, unless there are some UX work that you might think. Once again - I am really sorry.
