### ISSUE TITLE
iOS: missing End-To-End Encryption input

### ISSUE THREAD

**Issue by alexdevero** [laurent22/joplin#136]
There is no visible input to set the password for enabling encryption. After clicking on "Enable", "Password cannot be empty" error message is shown. However, after clicking on the empty space between the text and "Enable" the keyboard will actually appear.

### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*
![img_0899](https://user-images.githubusercontent.com/4237724/34637549-56c9ea5a-f2b9-11e7-984a-ac4fa8d2e8ad.PNG)

**Comment by nr458h** [comment]
Same in android

**Comment by laurent22** [comment]
Thanks for the report, that will be fixed in the next release too.

**Comment by alexdevero** [comment]
Thanks a lot @laurent22. I want to help you with translations. Is there some language that is missing and many users use it?

**Comment by laurent22** [comment]
@alexdevero, not that I know of but any contribution, translation or improvement of existing translations is welcome.

**Comment by alexdevero** [comment]
@laurent22 count with me. Translations are only a beginning. I love Joplin and want to help you as much as I can.
