### ISSUE TITLE
Note creation time not saved in 1.0.140

### ISSUE THREAD

**Issue by regul8or** [laurent22/joplin#1361]
Can not change note creation time in version 1.0.140 for Windows.

1. Open note properties
2. Click edit on Created property
3. Choose another date
4. Close date selection form (date is still new)
5. Click Save button. Field content changed to old date
6. Click Apply
7. Open note properties again. Date is still old
8. Restart the application.
9. Checking note properties. Date is still old

I can reproduce this behavior on 2 different computers with every note I try

I reinstalled version 1.0.135 and in this version I can change creation date

Checking console and log as per _debugging_ document shows no relevant entries

### Operating system

- Windows (other OSes not tested)

### Application

- Desktop (other platforms not tested)

**Comment by CalebJohn** [comment]
Hi, lucky for you this bug has already been reported and fixed (see #1329), everything should work correctly in the next release

**Comment by tessus** [comment]
New release [1.0.142](https://github.com/laurent22/joplin/releases/tag/v1.0.142) is available.
