### ISSUE TITLE
Reading sync folder on pCloud (generated from linux)

### ISSUE THREAD

**Issue by ambs** [laurent22/joplin#1364]
### Operating system

- Windows

### Application

- Desktop

I usually work in Linux, with Joplin syncing with pCloud. Works great. Tried to put windows reading it. Problem, it complains when reading the folder (see image).

I tried activating the debug tab, but the console doesn't show any other interesting information.

Thanks for your great app.

**Comment by ambs** [comment]
https://my.pcloud.com/publink/show?code=XZmHGt7ZdVihRiuxbmzWGkIURjrQ6QYDYW3V

**Comment by ambs** [comment]
I am having the same problem with Linux now. What should I delete to clean up every Joplin configuration detail? I tried `.config/Joplin` but it seems it is not enough. Can you give me some hint here?

**Comment by laurent22** [comment]
For support questions, please use the forum.
