### ISSUE TITLE
RDS/Citrix - Disable Update Check / Auto-Update

### ISSUE THREAD

**Issue by BornToBeRoot** [laurent22/joplin#1367]
Hello,

i want to install joplin in a multi user environment (RDS/Citrix XenApp).

Is it possible to disable the update check for all users? 

Greetings

**Comment by foxmask** [comment]
what's the problem with that ? Did you try joplin in that use case ?

**Comment by BornToBeRoot** [comment]
I installed Joplin on Citrix XenApp. There is no issue with it running in a multi user environment.

It would be great if you could disable the update check. (I currently do it, by deploying the setting db to the user profile). In a multi user environment, the user is not able to install it updates...

Maybe a reg-key under HKLM/HKCU or a file in the folder (disableUpdate.settings) would be great.
