### ISSUE TITLE
Text after enabeling E2E with dark-theme not readable

### ISSUE THREAD

**Issue by nr458h** [laurent22/joplin#137]
![screenshot_20180106-082428](https://user-images.githubusercontent.com/34851898/34637667-84b3ecac-f2bb-11e7-87fb-817ce59a5e06.png)
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---

**Comment by laurent22** [comment]
Thanks for the report, that will be fixed in the next release.
