### ISSUE TITLE
Webclipper not working in latest Chrome due to security policy block

### ISSUE THREAD

**Issue by CollinChaffin** [laurent22/joplin#1373]
I'm guessing you may be aware of this I see you released a fix on the Firefox side but if not the clipper is currently totally broken in Chrome due to this:

```
Refused to execute inline script because it violates the following Content Security Policy directive: “script-src ‘self’ ‘unsafe-eval’”. Either the ‘unsafe-inline’ keyword, a hash (‘sha256-18j9+nErtuKtcSwKvHjJxqQJK1kCjNV0fFqZIbKBDDY=’), or a nonce (‘nonce-…’) is required to enable inline execution
```

TIA!

**Comment by tessus** [comment]
Please see: https://discourse.joplin.cozic.net/t/chrome-web-clipper-is-not-working-getting-a-popup-error/1987

Fix will come soon.

**Comment by CollinChaffin** [comment]
You guys rock I've already left five star review in Chrome Web Store!  Looking forward to the fix found it's harder and harder now to live without Joplin especially the clipper!

**Comment by CollinChaffin** [comment]
I can confirm that clipper build 1.0.13 looks good and problem seems to be resolved.  Thanks for the quick fix!
