### ISSUE TITLE
API call for markdown rendering

### ISSUE THREAD

**Issue by tsumare** [laurent22/joplin#1376]
### Operating system

- Windows
- macOS
- Linux

### Application

- Desktop

### Description

Please add an API endpoint to run Joplin's markdown render on a note (either by ID or body text) and return the rendered HTML associated with that note.  This will allow rendering and use in external tools while automatically keeping up with all features of and improvements to the Joplin markdown renderer.

**Comment by tessus** [comment]
@laurent22 this is actually not a bad idea. Is this something that can be done easily?

**Comment by laurent22** [comment]
Hard to do well, and also it's not clear why it's needed?

**Comment by tsumare** [comment]
I use a custom external tool to retrieve notes from the API, render them and post them on my website as a sharing tool.  Making the rendering relatively similar to Joplin has been a decent amount of work, and not being as familiar with javascript, getting a similarly configured rendering engine in another language is not necessarily easy.  This option would allow for me to know that my final product would look the same as what I see in Joplin, as well as keeping up with any features you add or tweak.  I expected that this would be simply a matter of duplicating a few function calls related to the rendering and sending the result to the client rather than a particular pane of the app.  If that's not the case, it may not be worth it?  I can do the work I've described on my end to approximate the main features I use, but I doubt I'm the only one trying to do something similar.  It seemed useful, if it was relatively simple, to expose access to your existing markdown renderer.  It's much easier to walk the DOM and edit links to other resources than it is to generate an entire hopefully similar DOM from a diverse world of varying markdown renderers.

**Comment by laurent22** [comment]
I'll take a look at it but if I remember well it's not as simple as giving access to the renderer because there's quite a bit of JS involved. For example, resources need to be loaded and an external HTML file will not have access to the internal Joplin resources, so these would need to be exported too and linked properly from the file.

**Comment by tsumare** [comment]
@laurent22, I think it's reasonable to expect the user of the API to deal with resource links themselves.  It's not too terribly difficult to walk a DOM, or even to just do a string replace on `<a href=":/` and `<img src=":/`. Whoever is using this API is obviously going to be aware of the various details of how Joplin works, and will need to rearrange linked resources, notes or images to suit whatever they're going to do with it no matter what you provide.  If you are concerned, however, perhaps a base_resource_url would solve this?  It could default to the actual Joplin resource path (for attachments), if you want to provide the most accessible default output, similar to what is done for editing in external editors now.

**Comment by tsumare** [comment]
This would still be useful.
