### ISSUE TITLE
clipper: Simplified Page button should be hidden when page not available in this mode

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#1379]
Firefox 66.0.2, WebClipper 1.0.13

When I try to clip a github issue page, e.g. https://github.com/laurent22/joplin/issues/955 , as 'simplified page', I get the following error (in the preview and the clipped note):

```
The content you are editing has changed. Please try again.

Attach files by dragging & dropping, selecting or pasting them. <img width="16" height="16" src=":/6096569cdb644360ac17f1fc8bcb4e3e"/> Uploading your files…   We don’t support that file type.  with a GIF, JPEG, JPG, PNG, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX or ZIP.   Attaching documents requires write permission to this repository.  with a GIF, JPEG, JPG, PNG, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX or ZIP.   We don’t support that file type.  with a GIF, JPEG, JPG, PNG, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX or ZIP.   Yowza, that’s a big file  with a file smaller than 10MB.   This file is empty.  with a file that’s not empty.   This file is hidden.  with another file.  Something went really wrong, and we can’t process that file.
```

I was able to narrow it down a bit: This only happens when there's only one post. As soon as there's at least one reply, the error is gone.

**Comment by laurent22** [comment]
It seems GitHub is not supported by the Readability lib. A simple check for this in Firefox is to see if the "[Reader View](https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages)" icon is present: if it is, Simplified Page in Joplin will most likely work, if not, there's a chance it will be broken.

I'm not sure how Mozilla is doing to detect if a page can work in Reader View or not. I guess I should apply the same logic to the Simplified Page button and hide it when the page does not work with this mode.

**Comment by tessus** [comment]
Ah, I see. Although I have never understood the `Reader View`. e.g. on my own [ffmpeg web page](https://evermeet.cx/ffmpeg/) the reader view only shows the first pararaph, but not the entire page, which makes no sense.

**Comment by laurent22** [comment]
Yes their lib is far from perfect, although I guess it's tricky business to know what should be included or not in a page.

**Comment by tessus** [comment]
Yea, but even Safari only shows the first paragraph. There's nothing in my html code that would tell the reader to only show the first paragraph. Weird.

**Comment by tessus** [comment]
@laurent22 isn't that fixed already?

**Comment by tessus** [comment]
Oh, sorry, no, it isn't.

**Comment by laurent22** [comment]
Turns out Mozilla also open source their detection logic as a nice [self-contained JS file](https://github.com/mozilla/readability/blob/master/Readability-readerable.js), so I've added that to the clipper. Instead of completely removing the "Clip Simplified Page" button, I'm putting a warning next to it so that the user can decide to give it a try.

**Comment by tessus** [comment]
Cool. I really like the `clip simplified page` option. In many occasions the result looks better than clipping the complete page - at least that's what I have experienced so far.
