### ISSUE TITLE
clipper: some issues on medium.com

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#1380]
Firefox 66.0.2 and WebClipper 1.0.13

When I try to clip a selection from a [medium post](https://medium.com/@eleroy/10-things-you-need-to-know-about-date-and-time-in-python-with-datetime-pytz-dateutil-timedelta-309bfbafb3f7), I get a somewhat strange result.

- `.` in headers are escaped by a `\`
- Code blocks are not recognized
- `#` in text is also escaped by a `\`

jex export of the clipped note: [clipper-medium.jex.txt](https://github.com/laurent22/joplin/files/3027323/clipper-medium.jex.txt)

**Comment by dayfuaim** [comment]
I can confirm this.
It happens not only in FF, but in Chrome-based browsers (Opera, Brave etc.)

**Comment by laurent22** [comment]
Although the result is indeed not great, it's working as expected:

- Code block cannot be detected in this page (they just use custom "pre" tags), therefore the code is added as regular text
- To prevent the # from being interpreted as headers, they are escaped (which is normal)
- To prevent the "1.", "2." etc from being interpreted as bullet points, they are escaped too

**Comment by tessus** [comment]
Thanks for the info.

One question though. Couldn't we transform a `<pre>` tag to a code block? When you think of it, it's the same thing anyway. If not, we could still use `<pre>` tags. Using normal text for a pre block can be a disaster. e.g. imagine html code in the pre block.

**Comment by laurent22** [comment]
<pre> tags are used in all kind of way over the web unfortunately, so we cannot use this alone as an indicator for a code block. Medium should use the tag for codeblock which is <code> but they don't (even what looks like a single block on their site is actually a mess or multiple pre tags) so conversion to Markdown is not possible. We can see, visually, that it's a codeblock but the browser doesn't know it, let alone the Html2Md converter.

So far the only reasonable way to handle this is to add it as regular text.
