### ISSUE TITLE
Feature request: Easy editor

### ISSUE THREAD

**Issue by PopeRigby** [laurent22/joplin#1381]
On Reddit, there's something called a 'Fancy Pants Editor'. It's sort of like combining the preview into the editor. Having an option for something like this would make editing easier, because there would be no need to switch back and forth between the editor and preview.

**Comment by tkilaker** [comment]
@PopeRigby On what platform are we talking about? It would be helpful if you'd attach a screenshot to describe what you are after. In the Windows desktop version, there is a possibility to see edit and preview side-by-side (Ctrl+L).

**Comment by PopeRigby** [comment]
Presumably on all platforms. [Here's](https://peertube.linuxrocks.online/videos/watch/05159776-5a4a-4ef7-b199-5ac3d0809314) a quick video to show what I'm talking about

**Comment by CastedConst** [comment]
The Video won't load for me, but as I understand it you want the formatting-buttons on the top to work on the preview pane as well:

E.g. You select some text in the preview pane and press the "Bold" button and expect the text to become bold. In the current version the Bold-button would be applied to whatever is selected in the editor pane (which can even be be off-screen).

The formatting-buttons are only partially working anyhow on Windows: Selecting an italic text and pressing the italic-button renders the text bold (cause `*text*` plus `*<>*` => `**text**`). The regular WYSIWYG behavior would be to remove the formatting.

That said I think it's a great idea. It would probably reduce the barrier to use Joplin for non-technical users greatly.

**Comment by CastedConst** [comment]
#176

**Comment by PopeRigby** [comment]
Ah. This stale bot is kind of annoying.

**Comment by laurent22** [comment]
As I understand this would be WYSIWYG editor, and there's already a feature request for it.
