### ISSUE TITLE
Go to search keyboard shortcut (global search - not in note)

### ISSUE THREAD

**Issue by husimo** [laurent22/joplin#1382]
### Operating system

- Windows
- macOS
- Linux

### Application

- Desktop

Hello,
I would like to know if there is a shorcut to go to global search.
I know there is **[CTRL+F]** to search in note but I want to activate the global search.
Thank you, that's really an amazing project, keep up the good work :+1:

**Comment by tessus** [comment]
Yes, there is. When you open the 'Edit' menu you'll see the shortcut

<img width="234" alt="image" src="https://user-images.githubusercontent.com/223439/55344823-69d8bb00-547c-11e9-8cab-c692e65d3a12.png">

on macOS: cmd+shift+f
on windows I guess it is: ctrl+shift+f

**Comment by Dasymi** [comment]
F6 on Windows.

**Comment by husimo** [comment]
Thank you.
For information, it's also F6 on GNU/Linux.
