### ISSUE TITLE
Android app update

### ISSUE THREAD

**Issue by subi54** [laurent22/joplin#1385]
Desktop app have had its fun, even markdown-it plugins are here.

We still need a serious Android update though. A lot of user experience is ruined because of the lack of a better Android app.

Not talking about custom CSS or plugins, no. Talking about better editor window scrolling and the likes. Basic stuff. Updated UI would be nice as well but as long as the app is functional, UI can be disregarded.

**Comment by tessus** [comment]
> Talking about better editor window scrolling and the likes. Basic stuff.

The mobile apps use react-native thus a lot of the issues are actually upstream. But I'm sure @laurent22 will accept a PR from an app designer to improve the UI. (Although changes in that regard should first discussed with Laurent.)
