### ISSUE TITLE
Feature request: option to sort search results by date

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#1388]
I believe this is the default for comparable programs like OneNote (or at least they put a weight on descending date). For my use case, this would be more useful than relevance and I'd prefer it to be the default, but I think it should at least be an option. Either through syntax in the search box or a menu option.

**Comment by Valicanto** [comment]
Same here, what I really like about Evernote, is dat you can see a list of your notes with Titles, Date Created, Date Modified, Tags. That way you can sort your notes by column. I would like this view:
![image](https://user-images.githubusercontent.com/32411270/59756812-c1701100-928a-11e9-8863-c573e3511842.png)

**Comment by frogger72** [comment]
If the UI component of this is difficult, maybe as a temporary solution this could be enabled in preferences or through a flag. Sorting results by data is the default behaviour in comparable apps and is much more useful to me for finding notes so I would be happy turning that on permanently

**Comment by frogger72** [comment]
Any thoughts here? If someone can point to where in the code an edit would need to be made, I could take a crack myself.

**Comment by frogger72** [comment]
Still hoping for this feature as it's the only thing that prevents me from fully migrating to Joplin. It looks like a pull request was rejected - why not add this option, so users can at least use it similarly to other notetaking apps?

**Comment by kevinmickey** [comment]
Based on https://github.com/laurent22/joplin/pull/2369#issuecomment-578525402, I think we need some specification agreed upon before a PR can be written and rejected again.  There seems to be community support for this feature, at least as an option.

**Comment by frogger72** [comment]
Still very much interested in this and happy to help if I can

**Comment by frogger72** [comment]
@laurent22 Would be great to get some clarity on plan or feedback on this issue in case we can contribute.

The pitch is that sort by date should be available as an option when searching (I would personally set it to default). Currently it's much harder to find notes in a large notebook compared to other note apps because of this difference. Relevance scores are structurally less meaningful when you have many high frequency short notes each with 1 hit.

**Comment by frogger72** [comment]
This is the most important outstanding feature for me and I think is quite
important to some others too - let's please keep this open.

**Comment by ricog** [comment]
Hopefully https://github.com/laurent22/joplin/pull/3777, which is in the [latest pre-release](https://github.com/laurent22/joplin/releases/tag/v1.3.7) will get close to what you requested. There is also [discussion of  sorting filters](https://github.com/laurent22/joplin/pull/3777#issuecomment-699062257) in the PR comments.

**Comment by altosaar** [comment]
This plugin seems to be the solution while we wait for this: 

https://discourse.joplinapp.org/t/note-overview/13962/41

https://github.com/JackGruber/joplin-plugin-note-overview#open-todos-for-the-next-7-days-and-overdue-todos

**Comment by altosaar** [comment]
Yes the issue still requires attention :) It seems like the only solution so far is to use the solution pointed out in https://github.com/laurent22/joplin/issues/1388#issuecomment-852423632

**Comment by gitterspec** [comment]
Still despearately needed. The solution in #1388 requires a big effort for every search and is not practical for casual use.

**Comment by altosaar** [comment]
Still desperately needed!

**Comment by altosaar** [comment]
Still desperately needed!

**Comment by kevinmickey** [comment]
> But why would you search for "jenkins" only?

People often search for the primary keyword associated with what we are looking for, even if there have been many notes on that topic. For empirical stats on the number of words used in Google searches, see: https://www.statista.com/statistics/269740/number-of-search-terms-in-internet-research-in-the-us/

> Presumably you're looking for a specific note, so why not add keywords relevant to your search?

I have encountered an issue where several specific words associated with the note that I have in mind did not actually appear in the note. Sometimes there are synonyms, sometimes there are acronyms, sometimes there are URLs to websites with that word, sometimes the note is just brief and so managed to not include the more specific term I happened to think of. While improving search relevancy would fix some of these, often the note is just very brief where no search keywords could uniquely identify it.

In other cases, we are keeping regular notes of a recurring meeting called Big Idea meetings. I have taken notes on >100 Big Idea meetings, and my notes may be stream of consciousness and not inclusive of very specific terms.  The meeting may not occur on predictable dates to filter, but I know I want the Big Idea meeting notes from two meetings ago.

> And if you need something time-related, there are several date filters that can help with that.

Perhaps I am looking up an old project, so I know none of the results will be recent, but I want the most recent note related to that old project.  If I worked on the old project from Feb 2017 to June 2017, when I search in 2022, I have no recollection of the last month (June 2017) to add as a date filter.

**Comment by wiicode** [comment]
@kevinmickey put this far more elegantly than I could ever, so thank you.   To simply add to that...  when I search I want to find something. If I knew what I was looking for then I would not be searching.  I am sure that's common for many of us.   In practice that means broad term first and then iterate through possibilities.  While Google is quite good at relevancy, Joplin is not and it's futile to try.  I know what's relevant - give me tools I can use to select it.

**Comment by gitterspec** [comment]
I echo these comments. Many times, I'm on-the-go looking for something I wrote just a few days/weeks ago. I know a keyword will match the note and I prefer to look note by note in reverse chronological order until I find it. This is something that my family and I do all the time and it works fine in Evernote / OneNote. I think this is a very natural and common use case for search... maybe the most common on a mobile device.

**Comment by lehelkeresztes** [comment]
Bump.
I've switched from Evernote this week (finally) and my two biggest hurdles so far was the ordering of search results and the lack of note "cards" in the note list (where it only shows title). 

My use case - i'm used to writing down everything and anything that can be interesting and i "tag" some of these. To give a better idea, i create at least 1 note/day for that day and use that as a container. Let's say i get an idea i want to save for later, i write it down and add an inline tag to it (which is basically just a string of my own choosing, say "@remember"). 

Periodically i go through my notes to check what i've tagged. With the current "relevant" search order this is a huge pain. Sorting search results by date (created or updated) would make most sense for me in this case.

**Comment by lehelkeresztes** [comment]
Still open

**Comment by gitterspec** [comment]
Request to ropen this issue. Still sorely needed.

**Comment by lehelkeresztes** [comment]
Bump, still needed, please reopen.

**Comment by 304535076** [comment]
这是QQ邮箱自动回复邮件，

您的来信已收到。

**Comment by BrunoAHVincent** [comment]
I would love a solution for this also.

**Comment by GreatWhiteShirt** [comment]
The link to:

"Desktop: Add option to select the search result order #7622"

appears to show the ability to sort search results by various means. 

This would be very helpful as the default sorting algorithm is extremely frustrating and not helpful at all when I use it. I can never easily find what I am looking for when I search by keyword. I need to be able to sort by date as I usually recall the rough time frame I made an entry I am trying to locate. 

So are these features being added in a forthcoming update? New features depicted in the link provided recently by JackGruber do not exist in my version of Joplin (Joplin 2.9.17 Mac desktop) unless I am missing something.

Thanks!
