### ISSUE TITLE
New Greek translation.

### ISSUE THREAD

**Issue by N3tFX** [laurent22/joplin#1389]
### Operating system

- Linux

### Application

- Desktop

I have just finished the first draft of Greek translation. First time I do something like this. It needs proofreading and completing any strings I couldn't translate. What are the steps to integrate it?
[el_GR.po.txt](https://github.com/laurent22/joplin/files/3038980/el_GR.po.txt)

**Comment by tessus** [comment]
Thank you for adding a new language!

Well, the proofreading has to be done by people who actually read and speak Greek. ;-)

The strings that are currently not translated will fall back to the default, which is English. Over time, others will add to the translation and/or improve upon yours.

The next steps are also explained in the README:

Once it is done, please either [open a pull request](https://github.com/laurent22/joplin/pulls) or send the file to [this address](https://raw.githubusercontent.com/laurent22/joplin/master/Assets/Adresse.png).

**Comment by tessus** [comment]
@N3tFX what's the status of this?
