### ISSUE TITLE
Bug: crashes on clicking "new notebook " on some android

### ISSUE THREAD

**Issue by Likivik** [laurent22/joplin#139]
Android 7.1.2 LinageOS(ido, 3/01/18)
Xiaomi Redmi 3

On my device, app is rendered unusable. Can't create a note because there are no notebooks. And it crashes on clicking "new notebook" 
If you could point me to where logs are I will try to figure out what the problem is.

**Comment by laurent22** [comment]
Thanks for the report, creating a new notebook from a fresh installation was indeed broken. This will be fixed in the next release
