### ISSUE TITLE
rclick to copy a weblink

### ISSUE THREAD

**Issue by techi99** [laurent22/joplin#1392]
### Operating system
- Windows 10 v1803 b17134.648

### Application
- Desktop v1.0.142, same with v1.0.140

Thank's for the great app so far! I'm using the Windows and Android App with file system sync and encryption.

Right click on a weblink and choosing 'Copy Link-Address' sends '#' to the clipboard instead of the url. Left mouse-click works fine, opening the url in the standard browser. But sometimes I like to use a different browser.
<img width="665" alt="Joplin_rclick_link" src="https://user-images.githubusercontent.com/49309597/55627175-cce48d80-57ad-11e9-8d57-c9b78fb31264.png">

See also enclosed screenshot.

**Comment by Nebucatnetzer** [comment]
I'm experiencing the same problem. Both on Linux and Windows.

**Comment by laurent22** [comment]
Fixed in 9356841cfc3f4c4b26f2edd818f1284f95c70023
