### ISSUE TITLE
no update of version number?

### ISSUE THREAD

**Issue by techi99** [laurent22/joplin#1393]
### Operating system
- Windows 10 v1803 b17134.648

### Application
- Desktop v1.0.142, same with v1.0.140

I started using Joplin with the desktop version 1.0.140 some weeks ago. Today I opened the menu item point 'Help - Check for updates', showing me the attached screenshot. I downloaded the new version 1.0.142 and replaced the new exe with the old one. After running the new version and opening 'Help - Check for updates' again, the same information is shown like before.

The SQL query on the db <select * from "version"> gives the result "18". I think the version number wasn't changed by the program.

What went wrong?
How to fix?

Thanks for help in advance.
![Joplin_version number](https://user-images.githubusercontent.com/49309597/55630416-ed184a80-57b5-11e9-9753-ec65ca19cd84.png)

**Comment by laurent22** [comment]
What version does it show in the About dialog?

**Comment by techi99** [comment]
mmmh, nothing is happening at all with this menu Item. Just made a restart.
After same result. I'm using the German language template.

Laurent Cozic <notifications@github.com> schrieb am Fr., 5. Apr. 2019,
15:21:

**Comment by tessus** [comment]
> The SQL query on the db <select * from "version"> gives the result "18". I think the version number wasn't changed by the program.

The database version does not change every time.

>  I downloaded the new version 1.0.142 and replaced the new exe with the old one.

If you replaced the new with the old one, how do you expect the new one to be new?

**Comment by techi99** [comment]
OK, here is the explanation for the malfunction:
I didn't make a reboot of my PC for longer time. I always closed the app by
clicking the “x” icon at the top right corner of the application window.
Doing so, four processes of the app remain running in the background.
Starting the new program version didn't rerun the background processes of
the old version. Closing the app with strg+Q also stopped the background
processes of the former program version. After the restart everything works
fine now:
Help / Check for updates tells me: "Die aktuelle Version ist auf dem
neuesten Stand." (The running version is up to date.)
Help / About Joplin shows: ... Joplin 1.0.142 (prod, win32). Before this
menu item did nothing at all.

Thanks for putting me on the right track! Please close this incident.

I love Joplin! *****




Am Fr., 5. Apr. 2019 um 22:48 Uhr schrieb Helmut K. C. Tessarek <
notifications@github.com>:
