### ISSUE TITLE
White screen briefly after opening Joplin

### ISSUE THREAD

**Issue by PopeRigby** [laurent22/joplin#1395]
Platform: Android
Version: 1.0.241

Expected: Joplin loads immediately

Reality: Joplin spends around 3-5 seconds on a completely blank white screen, and then loads

Steps to reproduce:
1. Leave Joplin open for a while
2. Open Joplin

**Comment by N3tFX** [comment]
This might be related to the problem I am having (described at bug report #1284). When this white screen and delay happens, it affects Firefox. Some rare times it doesn't happen and in this case Joplin loads normally and Firefox stays unaffected. But when I see the white screen...
