### ISSUE TITLE
[feature request] Add markdown shortcut in mobile app

### ISSUE THREAD

**Issue by frank777777777** [laurent22/joplin#1397]
### Operating system

- Android

### Application

- Mobile

Can you add markdown shortcut in mobile app, like the desktop version?
![screenshot](https://images2.imgbox.com/17/14/fe69PhAF_o.jpg)

Its harder to type `, *, _, - [ ] and etc in mobile app. In my opinion, mobile apps need those functionality more than the desktop version.
It also nice to add auto-complete for lists like the desktop version. For example, It's a PITA in mobile app, to actually create a to-do check list, and has to manually type - [ ] for every single item..

**Comment by foxmask** [comment]
i can imagine it's complicate for `- [ ]` but the others should be accessible from the num pad.
Otherwise, personnaly, when I have to repeat a couple of signs, I copy / paste it ; like for the checkbox.

**Comment by foxmask** [comment]
in fact, we would need to have a toolbar too that could slide to be displayed/hidden

**Comment by foxmask** [comment]
close this one as (almost) dup of #1083

**Comment by xuhcc** [comment]
@foxmask This is not a duplicate. #1083 describes completely different problem.

**Comment by foxmask** [comment]
Both are for shortcuts...
