### ISSUE TITLE
[Feature Request] Option to have a space for tags after the title

### ISSUE THREAD

**Issue by starstuff** [laurent22/joplin#1399]
### Operating system

- Windows
- macOS
- Linux

### Application

- Desktop

Hello,

I would like to request an option in Joplin to have a space for tags.

This is a faster way to add/edit/delete tags because you don't need to click on the tag icon before you can write/remove tags, and you will have an idea what the tags are for that note.  

The request is similar to the Evernote tags

![tags](https://user-images.githubusercontent.com/16585579/55678764-87e96400-5931-11e9-9ae1-9beec7f76b78.jpg)

Thank you!

**Comment by traedamatic** [comment]
Hello,
i like this idea of a space for all tags of the note/to-do at first glance within the details page of the item. 
That makes the tags very useful for visible marking the items.

Best wishes,
Nicolas

**Comment by mic704b** [comment]
+1

The most important is to display the tags. Being able to edit them would be a bonus.

**Comment by anihm136** [comment]
If this hasn't been resolved yet, I'd like to try it. I'm a first time contributor to Joplin. Would this be simple enough for me to start with?

**Comment by mic704b** [comment]
The tags list has already been added to the app, but the tags are not editable.  Implementing the feature should be simple enough, but there is no clear agreed spec on how it should work.

So feel free to have a go, just be prepared for the chance the solution is not accepted.  You could try discussing it first on the forum.
