### ISSUE TITLE
Copy/Paste

### ISSUE THREAD

**Issue by clemlucasynotek** [laurent22/joplin#14]
Using Joplin on Mac OSX, Copy/Paste from external and internal text is not working 😢

**Comment by ingpf** [comment]
I also meet this issue

**Comment by laurent22** [comment]
Oh that's not good, I assumed the default keyboard shortcuts would just work. I will add support for it.

**Comment by MichaelWTA** [comment]
Same, cannot copy/paste via keyboard or the edit menu

**Comment by laurent22** [comment]
The copy/cut/paste issue on macOS should now be fixed as of v0.10.30. Please give it a try and let me know if there's still any issue.
