### ISSUE TITLE
some suggests

### ISSUE THREAD

**Issue by guqinglei123** [laurent22/joplin#1400]
I would like to ask if the Android and iOS versions can provide import functions. Sometimes I will write on the phone and then I can import them after I finish writing.

**Comment by foxmask** [comment]
Import what ?

**Comment by guqinglei123** [comment]
import some file which is markdown format.

**Comment by foxmask** [comment]
Why not just writing directly in Joplin?

**Comment by guqinglei123** [comment]
Joplin  is very good software for manage my notebooks. However，I like markdown editor that  support WYSIWYG function. I'm  accustomed to use typora editor in PC and Bear in IPad. Changing the editor is difficulty for me. so I want to Joplin can support import/export function in Android and IOS platform.
what's more，when I ofter build the note in the Joplin and edit it by typora，i have encount one issue.  when i  paste a image in the note using the typora editor，the image  can display in typora but it don't load in Joplin. I don't kown to config the path of image. if there are some method to solve it，please tell me. thank for you very much.

**Comment by i-need-to-tell-you-something** [comment]
This feature is called [External editor](https://joplinapp.org/#external-text-editor). So what you want is "Support for external text editor in Android/iOS". Maybe you can please change the issue title to that as well to make it more clear.
