### ISSUE TITLE
Line breaks don't nehave according to the markdown "standard"

### ISSUE THREAD

**Issue by Nebucatnetzer** [laurent22/joplin#1406]
### Operating system

I have tested it on these plattforms.

- Linux
- Android
- iOS

### Application

I have tested these applications.

- Desktop
- Mobile

I tried the external editor feature today.
My editor is setup so that it breaks lines after 80 characters.
After I switched back to Joplin I noticed that it interprets all the line breaks like the editor does.
However all the markdown implementations I've used ignore those and only insert a line break with additional markup (two spaces,`\`, `<br/>`). 

https://gist.github.com/shaunlebron/746476e6e7a4d698b373

https://markdown-it.github.io/#md3=%7B%22source%22%3A%22This%20is%20a%20long%20text%20which%20contains%20linebreaks%5Cnhowever%20they%20get%20ignored%20by%20markdown.%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

**Comment by subi54** [comment]
Joplin actually supports both markdown and normal line breaks.

**Comment by Nebucatnetzer** [comment]
Is there an option for it?

**Comment by subi54** [comment]
No, by default they both work.

**Comment by Nebucatnetzer** [comment]
I see, that's exactly what I meant with my issue.
The normal line breaks shouldn't work in a markdown editor.

**Comment by tessus** [comment]
@Nebucatnetzer no, currently Joplin does not support soft line breaks. I am working on a PR to add that option. I was just a bit busy the last few days, but I hope I will be able to do that soon.
Also, no promises that it will be merged, because I don't have a definitive ok from Laurent yet.

**Comment by Nebucatnetzer** [comment]
That's good to know.
It would already be nice if it was an option we could toggle.

**Comment by tessus** [comment]
Yep, the PR adds a check box to use soft breaks in settings. The default behavior won't change, but you will be able to use soft breaks, if you really like that behavior better.

**Comment by tessus** [comment]
added in https://github.com/laurent22/joplin/commit/12ebf44e22d778f6079998e72e0189af59cd094f
