### ISSUE TITLE
Order of items not the same on both machines

### ISSUE THREAD

**Issue by smokinjo** [laurent22/joplin#141]
### Operating system

- [ ] Windows
- [ ] macOS
- [ X] Linux
- [ X] Android
- [ ] iOS

### Application

- [X ] Desktop
- [X ] Mobile
- [ ] Terminal
I was messing around with my Ubuntu and Android version of and  find the the order of the items is not always respected between the two machines.  After ,messing about with it(synching), it eventually decided to be in the same order.

There was also one case with on one machine, there was an item deleted, but it was not synch'd to the other one.

Thanks

Joseph

**Comment by smokinjo** [comment]
I just wanted to check in again to see if there is anyt comment on my issue?

Thanks

joe

**Comment by laurent22** [comment]
By default, items are ordered with uncompleted tasks on top and then newest on top (can be changed in config), so any difference between clients is indeed resolved when syncing.

Is there any case where it still happens after syncing?
