### ISSUE TITLE
unicode not managed in the title on joplin desktop nor terminal

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#1410]
### Operating system

- Linux

### Application

- Desktop
- Terminal

### Description 
![Sans titre](https://user-images.githubusercontent.com/208212/55984916-e0f12900-5c9e-11e9-8e75-08ddfaa515d7.png)

in that picture we can see that the korean flag is not displayed in the desktop version, except in the popup to confirm the deletion

in the terminal version, joplin displays `:kr:` as 'flag'

**Comment by tessus** [comment]
This is totally weird. There is no unicode character for the Korean flag, but if you paste the codepoint `U+1f1f0` and then the codepoint `U+1f1f7` it creates the flag.

Also, how would the terminal version know to translate a unicode character to `:kr:`. This is not possible.

Btw, I tried this on macOS. Strangely it actually shows the Korean flag in the title and the preview area (right pane). 
However, in the editor (left pane), I get this when I paste the flag:

<img width="41" alt="image" src="https://user-images.githubusercontent.com/223439/56010909-75fe1d00-5cb3-11e9-848b-a668e463807f.png">

If you paste a "real" unicode character, like 😈 `U+1F608`, it works everywhere.

As I said... very weird... or maybe I don't understand unicode.

**Comment by foxmask** [comment]
:D

**Comment by foxmask** [comment]
i dont know what can be done here
