### ISSUE TITLE
Notebooks on the start page Android.

### ISSUE THREAD

**Issue by polinom11** [laurent22/joplin#1412]
### Operating system

- Android

### Application

- Mobile

Add to the initial screen of the Android application a list of all the notebooks, please.
![Screenshot_2019-04-12-14-55-02-672_net cozic joplin](https://user-images.githubusercontent.com/48948406/56036795-7095e680-5d36-11e9-94db-2f530baa8753.jpg)

**Comment by Nebucatnetzer** [comment]
Another thought I had was that we could show the recently changed notes.

**Comment by tessus** [comment]
Yea, I think the Welcome screen is totally unnecessary as soon as there's been a single notebook created. In that case the Welcome screen should be replaced by the list of notebooks.

**Comment by tessus** [comment]
Maybe the title should be changed to:

`Welcome screen improvements` (or something similar)

**Comment by keachi** [comment]
I think another idea is an overview over all notebooks with the recent ~10 notes. IMHO this is one thing which most note apps fail, and one thing I love on Google Keep (sorry for the comparison). What I want to see when I open the app is an overview what I have to do over all notebooks.
What I agree here, is that the Welcome screen is useless and should be replaced and this is just an idea what can be done with such a welcome page.
