### ISSUE TITLE
CTRL-P should not be "jump" in sublime it should be Print like other notes apps

### ISSUE THREAD

**Issue by strantheman** [laurent22/joplin#1413]
- Windows
- Desktop

I print from notes apps (my new one is Joplin - for now) a lot. CTRL-P is a standard for printing. I do understand the IDEs and even minimalist IDEs like Sublime have certain keyboard shortcuts which can be very effective when I'm writing software. However, when I'm using a notes app I print more than I jump, and I think "Goto anything" in Sublime is a wonderful function but I don't think it should be tied to CTRL-P in a notes app.

![image](https://user-images.githubusercontent.com/3137756/56053224-6ceb6b00-5d08-11e9-923b-4bbe73a36757.png)

How about CTRL-J for "Jump to anything" or even CTRL-G for "Goto anything" ?

The only reason Sublime used "P" is because "G" is a convention for "Goto line" in IDEs and text editors. In the context of a notes app however choosing "P" just because Sublime uses it makes no sense.

Notes apps are unlikely to need a "G" for Goto line, so why not use the proper letters for your actions?

- G = Goto anything
- P = Print

thanks for listening!

**Comment by laurent22** [comment]
You made some good points. I guess I've used ctrl+p because as a Sublime user that's what I'm used to, and I've also seen the same shortcut in other apps (maybe Atom)?

That being said it's true that dropping the Print shortcut is not ideal especially since other keys can indeed be used instead. Eventually it would be better to have customisable shortcuts but that's for another day.

For now, if no-one has any objection I'll restore the print shortcut, and indeed use ctrl+g for Goto Anything.

**Comment by Dasymi** [comment]
I don’t use ctrl+p but ctrl+g seems more intuitive to me.

**Comment by tessus** [comment]
@laurent22 I just tried to create a PR for fixing this, but it seems that the `.gitignore` file excludes the `ElectronClient/app/plugins/GotoAnything.min.js` file. It's also a bit strange that this min file is no min file at all. I think the source tree has to be fixed there. Btw, there's no `GotoAnything.js` file anywhere either. Please let me know how to proceed. I can still force commit this file, but I think there's something wrong, so I don't want to do that.

**Comment by laurent22** [comment]
There should be a GotoAnything.jsx in there. All the .jsx files have a corresponding .min.js file, which is basically the compiled JSX. It's a .min extension because eventually it could be minified too, but I haven't done that yet.

**Comment by tessus** [comment]
@laurent22 thx a bunch for the info. this makes sense now. I totally forgot that js files are generated from jsx files. my bad.

**Comment by strantheman** [comment]
Thanks everyone. Well met.

**Comment by strantheman** [comment]
Works great! Thanks for your response to this issue. Good work team.
