### ISSUE TITLE
[SOLVED] Unable to sync Joplin on iOS with Nextcloud, Cannot parse XML response (200)

### ISSUE THREAD

**Issue by Trinity-Dan** [laurent22/joplin#1414]
### Operating system

- iOS

### Application

- Mobile

Please forgive me if this has been asked and answered elsewhere, I did search extensively for a solution before posting here. I have a user attempting to sync Joplin on iOS with our private Nextcloud. She is able to successfully sync between her Windows desktop PC and her MacBook using the same account information, but when we attempt to setup synchronization on her iPhone we get the attached error "Cannot parse XML response (200)". Any assistance in resolving this issue would be greatly appreciated. Thank you.
![Joplin Sync Test Failure](https://user-images.githubusercontent.com/49573658/56070156-3844d700-5d3b-11e9-94ab-29394698353f.jpg)

**Comment by laurent22** [comment]
My first guess would be that the WebDAV URL is not correct because the response you are getting is a web page, not a WebDAV XML document. Please check the doc for info on how to specific the exact WebDAV URL (which is different from the URL where Nextcloud is hosted).

**Comment by Trinity-Dan** [comment]
Thank you for the amazingly prompt response! I am familiar with setting up the directory for Joplin, usually we call it Joplin. I was skeptical that this could be the source of the issue but went to test it again anyway and triple check the URL and sure enough, the autocorrect on her phone was changing webdav to WebDAV. When I forced it to use lowercase, we no longer received the error above. Unfortunately now we receive another error, PROPFIND : Unknown error 2 (405): (Code 405), which seems to indicate that there is a problem with her username and password, but she entered them multiple times and even gave me her password to try entering it myself and we still get the error. Any ideas what could be causing that?

**Comment by laurent22** [comment]
Is the url definitely the right one? Because this error would indicate it's making a valid call but on a url that doesn't support it. If Webdav works on your other devices, the only thing I can think of is that the url on this device is not right.

**Comment by Trinity-Dan** [comment]
Thank you for that information. I won't be able to do anymore testing on it until Monday but will follow up then. Thank you for all the work you have done on Joplin and the amazing responsiveness to issues! It is greatly appreciated!

**Comment by Trinity-Dan** [comment]
Sorry for the delayed reply. I did get another chance to check it out on Tuesday and very carefully entered the URL and it just worked. So ultimately all the problems I was having with this user were apparently related to the URL. I don't know how we missed it the second time after we got the webdav capitalization sorted out, but that must have been it. Thanks again for your help!

**Comment by tessus** [comment]
Wrong URL. Closing.
