### ISSUE TITLE
Web Clipper - Notebook Order not Sorted

### ISSUE THREAD

**Issue by mikeo85** [laurent22/joplin#1417]
### Operating system
- Windows
- Linux

### Application
Web Clipper (Firefox, Chrome)

### Issue
Web clipper does not sort notebooks in alphabetical order like the desktop or mobile apps do. It seems to be sorting in roughly the order that notebooks were created.

Screenshot below.

If any other info is needed/helpful, let me know.

Thanks in advance!

![Screenshot from 2019-04-13 08-10-21](https://user-images.githubusercontent.com/33993323/56079574-b4373180-5dc4-11e9-95f8-1e7a0da45e8b.png)

**Comment by tessus** [comment]
I think there are 2 ways to fix this:

- make the API call `GET /folders` return the result already sorted
- sort the folders in clipper code

Not sure, which is the better approach. I'd say the first one, but it's not my call.

**Comment by mikeo85** [comment]
Works great -- thank you!
