### ISSUE TITLE
Synchronized resources don't have file extensions

### ISSUE THREAD

**Issue by PNeigel** [laurent22/joplin#1418]
### Operating system

- Windows

### Application

- Desktop

When I add resources to my notes on PC A, e.g. some `image.png`, a duplicate of that image is added to my local resources:  `(PC A)C:\Users\me\.config\joplin-desktop\resources\234lkkl7856n3.png`. If I now use filesync, it is synced to `\filesync\destination\.resources\234lkkl7856n3` , without a file extension.

When I sync the complete `\filesync\destination` to another PC B, there are two problems:

1. Joplin does not sync any resources from `\filesync\destination\.resources` to `(PC B)C:\Users\me\.config\joplin-desktop\resources`, I have to do it manually. The `.md`-files are synced without a problem and I can see all my notes, just without resources.
2. Even if I copy the resources manually, the images still don't show up in the notes, because they have no file extensions. After adding the extensions they show up normaly, but adding file extensions is not only tedious but also difficult if you have many different filetypes.

**Comment by tessus** [comment]
Both items look like a bug to me.

@laurent22 there have been quite a lot of tickets on gh (resources not synced, images aren't displayed) and quite a few on the forum. Is this a problem you've been working on? I'd like to consolidate all these tickets somehow and then just refer to that particular ticket when people open new issues about this problem.

**Comment by laurent22** [comment]
Don't know about this bug or how to replicate it as of now but feel free to consolidate the issues if you find a common pattern.

**Comment by tessus** [comment]
@laurent22 I've noticed a few tickets similar to this one I think they are all related somehow.

I will make a list and maybe you can have a look and determine, whether my suspisions are warranted.
