### ISSUE TITLE
[Feature Request] Checklist Notes

### ISSUE THREAD

**Issue by trymeouteh** [laurent22/joplin#1419]
It will be similar to ToDo notes but instead of having one checkbox it will have multiple checkbox in a single note. To create a checkbox in the note you just need to press the Enter key to create a new line with a new checkbox. Similar to how Google Keep uses checklists.

This will be handy for making grocery lists and such.

**Comment by tessus** [comment]
Hmmm, this has been available for ages.

You click on this icon in the editor's toolbar: 
<img width="35" alt="image" src="https://user-images.githubusercontent.com/223439/56107537-e061c800-5f14-11e9-899f-50c68c31f3dc.png">

Or you write them manually: 

`- [ ]`

**Comment by trymeouteh** [comment]
> Hmmm, this has been available for ages.
> 
> You click on this icon in the editor's toolbar:
> <img alt="image" width="35" src="https://user-images.githubusercontent.com/223439/56107537-e061c800-5f14-11e9-899f-50c68c31f3dc.png">
> 
> Or you write them manually:
> 
> `- [ ]`

Oh I didn't know that. Is this also possible on mobile (Android, iOS)? If Not, please reopen this issue.

**Comment by tessus** [comment]
Yes, but there's no toolbar on mobile. You will have to write it manually or create an entry in your (keyboard or system) dictionary.

**Comment by trymeouteh** [comment]
A toolbar would be ideal then.
https://github.com/laurent22/joplin/issues/1030

**Comment by tessus** [comment]
Well, this is probably not going to happen. The screens on phones are already small, therefore a toolbar is useless.

You have to be able to click on the different icons in the toolbar, so the toolbar would have to be more than just one row.
Then you have to type, so they ket=yboard takes a large junk of the screen.
In the end you end up with 4 lines where you can edit stuff. That's exaggerated but you get the idea.

**Comment by JOJ0** [comment]
Hi, I just put a comment regarding ideas for improvements with small screen sizes here: https://github.com/laurent22/joplin/issues/1030#issuecomment-485285039

HTH Jojo

**Comment by trymeouteh** [comment]
A suggestion I will have is to have one row but be able to have the row scrollable on the X axis. That will make the toolbar small but pact with everything you need.

Just have to scroll left or right in the toolbar to find the bold button or checkbox button.

Another option besides scrolling is to have pages, have a arrow key and when you tap it to will scroll to the next row of options
