### ISSUE TITLE
Sync doesn't work in Linux anymore

### ISSUE THREAD

**Issue by joaopsys** [laurent22/joplin#142]
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

My Joplin stopped syncing on linux. I tried to set it to debug mode with the flags.txt but nothing happens either. It started behaving weird, not syncing all of my stuff, whereas on mobile and OneDrive everything is still there and being updated.

I also tried deleting my .config/joplin* folders to try and start it from scratch, but now it's just not syncing at all. I set my username and password, and that's it, the sync status doesn't even show up.

**Comment by joaopsys** [comment]
Some additional details: I tested in on my Windows which still had the previous version (.40) and the behaviour was the same as in, it didn't sync all the items (probably because I added/updated some of them with the .41 version in the mobile app?).

However after updating the Joplin version in Windows, everything started working normally. On Linux that didn't work out.

**Comment by laurent22** [comment]
Hi, I've just tried on Ubuntu with the latest version and it's working for me. Could you try to put the following in flags.txt:

    --log-level debug --open-dev-tools

Then start the application and do a sync, then open the file in `~/.config/joplin-desktop/log.txt` and see if there's any error or warning.

**Comment by joaopsys** [comment]
I thought flags was supposed to open some kind of console. It doesn't for me. But still, I did that and caught this error inside log.txt

```
2018-01-07 20:15:57: "Saving updated OneDrive auth."
2018-01-07 20:15:57: "Scheduling sync operation..."
2018-01-07 20:15:57: "Preparing scheduled sync"
2018-01-07 20:15:58: "Could not run background sync:"
2018-01-07 20:15:58: "SyntaxError: Unexpected token o in JSON at position 1
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at timeoutCallback (/tmp/.mount_Joplin67JkLn/app/resources/app/lib/registry.js:83:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)"
```

**Comment by joaopsys** [comment]
I've pasted a huge JSON in one of my notes some days ago. Can that be related in any way?

**Comment by laurent22** [comment]
This is weird, it means the result of the last sync operation was not stored correctly. Could you print the list of settings to see what could be the issue?

This would work:

    sqlite3 -list ~/.config/joplin-desktop/database.sqlite 'SELECT * FROM settings'

The key that's causing a problem would be `sync.3.context` - normally it's JSON but it seems it something else in your case. If you could check and let me know what it is, that would help fix the issue.

**Comment by joaopsys** [comment]
Sure thing:

```
sync.3.context|
locale|en_GB
firstStart|0
activeFolderId|
noteVisiblePanes|["editor","viewer"]
sync.3.auth|{"token_type":"Bearer","scope":"Files.ReadWrite","expires_in":3600,"ext_expires_in":0,"access_token":"Ew....
```

**Comment by laurent22** [comment]
Is it still printing the same error in the log? Because it seems the value of sync.3.context is now empty.

**Comment by joaopsys** [comment]
Yes, same error everytime I click 'Synchronize' (after my credentials have been saved)

```
2018-01-07 20:50:40: "Scheduling sync operation..."
2018-01-07 20:50:40: "Preparing scheduled sync"
2018-01-07 20:50:40: "Could not run background sync:"
2018-01-07 20:50:40: "SyntaxError: Unexpected token o in JSON at position 1
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at timeoutCallback (/tmp/.mount_Joplin67JkLn/app/resources/app/lib/registry.js:83:29)
    at <anonymous>"
2018-01-07 20:50:41: "Scheduling sync operation..."
2018-01-07 20:50:41: "Preparing scheduled sync"
2018-01-07 20:50:41: "Could not run background sync:"
2018-01-07 20:50:41: "SyntaxError: Unexpected token o in JSON at position 1
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at timeoutCallback (/tmp/.mount_Joplin67JkLn/app/resources/app/lib/registry.js:83:29)
    at <anonymous>"
```

**Comment by laurent22** [comment]
It's not clear what's happening because it seems to be loading a context value, but none is set in the database. I assume you use OneDrive for synchronisation? If you check the database with something liek SQLiteStudio, is there some value being displayed for any of the `sync.*.context` variables?

**Comment by joaopsys** [comment]
I dumped the entire database to a file and can only find the sync.3.context from the settings and the value is NULL

**Comment by joaopsys** [comment]
Might as well just give you the dump :)

I removed the line that contained my access token, but here it goes:

https://pastebin.com/bTc2JXKR

**Comment by joaopsys** [comment]
This seems to have gotten fixed with the latest version. You can close it if you wish!

Thank you so much :) I love Joplin

**Comment by laurent22** [comment]
Great, glad it's working. Invalid context values and null settings should be handled and fixed automatically now.
