### ISSUE TITLE
Search Anything does not search by notebook name

### ISSUE THREAD

**Issue by glowinthedark** [laurent22/joplin#1421]
**Search Anything** does not search by notebook name.

Steps to reproduce:

1. Create a new notebook named e.g. `XYZ`.
2. From **Tools** > **Goto Anything** (⌘+ P) search for the notebook name `XYZ`.

EXPECTED:

- notebook `XYZ` is listed in the search results

ACTUAL:
- no results found

**Comment by Dasymi** [comment]
I get the same behavior when the notebook is empty, but if there is at least one note in it the notebook is found.

**Comment by glowinthedark** [comment]
@Dasymi: it is only found _if_ the name of the notebook happens to also be contained somewhere in an actual note, but not otherwise. Just make sure you **do not mention** the notebook title anywhere inside the notes in that notebook, and then it won't be found, no matter how many notes there are in the notebook.

**Comment by Dasymi** [comment]
No, the notebook title isn't in the note. Are you searching for the notebook by prefixing the title with @?

**Comment by laurent22** [comment]
Can't replicate this.

**Comment by glowinthedark** [comment]
@laurent22:  @Dasymi: indeed, i was not prepending `@` to the notebook name, and was assuming that just typing the name as-is i.e. `xyz` will display the notebook. Thanks for clarifying. 

Maybe for better usability maybe it would be better to always display by default the help text `Type a note title to jump to it. Or type # followed by a tag name, or @ followed by a notebook name.` but display it in a dismissable alert similar to

![image](https://user-images.githubusercontent.com/48893368/56201497-4b102200-6041-11e9-9b45-3e425361827b.png)

(taken from https://react-bootstrap.github.io/components/alerts/)
