### ISSUE TITLE
Joplin command line install script fails on lubuntu

### ISSUE THREAD

**Issue by stevenirby** [laurent22/joplin#1422]
### Operating system

- Linux

### Application

- Desktop

I ran the install script on an lubuntu system (18.10) and the script fails to install Joplin. 

This is because the variable `$XDG_DATA_DIRS` doesn't match the regex checks in the script

`$XDG_DATA_DIRS` == `/usr/share/Lubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop`

Also `$XDG_CURRENT_DESKTOP` is: `LXQt`
```
if [ "$XDG_CURRENT_DESKTOP" = "" ]
    then
      desktop=$(echo "$XDG_DATA_DIRS" | sed 's/.*\(xfce\|kde\|gnome\).*/\1/')
    else
      desktop=$XDG_CURRENT_DESKTOP
fi
```
```
 if [[ $desktop =~ .*gnome.*|.*kde.*|.*xfce.*|.*mate.* ]]
```

The end result is a message saying:

```
Create Desktop icon.
NOT DONE
```

At the very least, maybe a better error message could be shown if Joplin won't run in this enviorment.

**Comment by laurent22** [comment]
Maybe that desktop lxqt desktop should just be added to the regex list?

**Comment by stevenirby** [comment]
Yup, just updating the regex seem to do the trick:

```
[[ $desktop =~ .*gnome.*|.*kde.*|.*xfce.*|.*mate.*|.*lxqt.* ]]
```
