### ISSUE TITLE
[Feature Request] Multiple notes; open in new tab

### ISSUE THREAD

**Issue by xvol** [laurent22/joplin#1424]
### Operating system
- Windows
- macOS
- Linux

### Application
- Desktop

I love Joplin and I use it extensively for many different purposes.

The one drawback I have found is, when you are jumping between notes, you must:
1. remember the name of the current note and current position in text.
2. search for secondary note; make changes
3. search previous note, and scroll to previous location.

Things get even more complicated if you want to work on 3+ notes in the same session.

I suggest that a tab-system would work wonders.
An implementation as in most text editors (Atom, Notepad++, etc) would simplify the application for users with many notes.
![joplin_with_tabs](https://user-images.githubusercontent.com/31360195/56213204-f0a5ae80-609e-11e9-854c-afa546b3feda.png)

I think an intuitive mode of operation would be...
- Left clicking a note from the note-pane would update the current tab to the selected note.
    - Shift + click would open in a new tab
- Right clicking a note from the note-pane would include an option to open in a new tab

All tabs would ideally keep track of current position in text and scroll location.
Please let me know your thoughts.

Thanks!

**Comment by msbentley** [comment]
Agreed this would be great - it is a feature I really like about the 3rd party Evernote client NixNote. Often I am working with reference to several notes and want to easily switch between them. See below a snapshot of how it works in NixNote:

![image](https://user-images.githubusercontent.com/1671065/56723680-bcd72280-6749-11e9-9f0b-54a2dd8c9d12.png)

**Comment by xvol** [comment]
> Agreed this would be great - it is a feature I really like about the 3rd party Evernote client NixNote. Often I am working with reference to several notes and want to easily switch between them. See below a snapshot of how it works in NixNote:
> 
> ![image](https://user-images.githubusercontent.com/1671065/56723680-bcd72280-6749-11e9-9f0b-54a2dd8c9d12.png)

@msbentley looks great! This kind of implementation would take Joplin to a new level 
NixNote is very clean wrt tabs; I hope we can implement something very similar

**Comment by nicolad** [comment]
Since Joplin is built on top of Electron, it is totally doable. I found this related package: https://github.com/brrd/electron-tabs
@laurent22 what's your thoughts on this and what implications it might have on overall architecture?

**Comment by xvol** [comment]
bump?

**Comment by Perkolator** [comment]
@laurent22 Did you have time to review this request? This feature would be really great.
