### ISSUE TITLE
Images absolute path not working on external editor

### ISSUE THREAD

**Issue by ianzhuo** [laurent22/joplin#1425]
### Operating system
- Windows
### Application
- Desktop
### External Editor
- Visual Studio Code

In Joplin internal Editor, images normally show like this.
![圖片](https://user-images.githubusercontent.com/1394735/56216860-c51dc680-6094-11e9-821e-d96e1c5a69d0.png)

When a note open in external editor, images link will be convert to absolute path like `D:\path\to\images.png`, but can not work properly.
![圖片](https://user-images.githubusercontent.com/1394735/56217261-82a8b980-6095-11e9-89c2-a310045cc88b.png)

after modified image link to relative path `..\\path\\to\\images.png`, everything worked!!
![圖片](https://user-images.githubusercontent.com/1394735/56217836-783aef80-6096-11e9-8b00-5756c35f42d2.png)

**Comment by laurent22** [comment]
Does it also work if you replace all the `\` of the full path with `\\`?

**Comment by ianzhuo** [comment]
Nope, absolute path seems not working on VScode, only relative path work.
In my test, all \ need to be replaced to \\\.

**Comment by laurent22** [comment]
Still not clear what the issue is. If really it supports relative paths but not absolute ones, it's a bug with VSCode and something you should raise in their issue tracker.

On the other hand if the issue is that it doesn't support single \ but only \\ then it's something we can fix, but I'm not going to install VSCode to confirm.

**Comment by laurent22** [comment]
Do paths like `file://c:/someimage.png` show up in VSCode? I'm thinking about changing the implementation to this kind of path as that would be more standard and perhaps it works in VSCode.

**Comment by ianzhuo** [comment]
Hi laurent22,
I've found that problem as link below

https://github.com/yzhang-gh/vscode-markdown/issues/118#
>We now restrict the markdown preview to only loading resources inside the current workspace for security reasons
Microsoft/vscode#45260 (comment)

It's a restriction from VScode, and it seems that I have to edit md without Image Preview(or choose another editor). lol
Anyway, thanks for your kindly help.

**Comment by ianzhuo** [comment]
Hi,
I've tried Typora and Atom with Joplin v143.
Test result as below, FYI.

orgin external link is:`![](file://C%3A/........`
doesn't work on both editor.
## Atom:
![圖片](https://user-images.githubusercontent.com/1394735/56678758-0eee5880-66f6-11e9-9283-2593078e5877.png)
## Typora:
![圖片](https://user-images.githubusercontent.com/1394735/56679010-9b991680-66f6-11e9-8946-caf8082dc694.png)

after modify as `![](C:/...`
both editor worked.
## Atom:
![圖片](https://user-images.githubusercontent.com/1394735/56678807-2c232700-66f6-11e9-966a-be7b1664b5bb.png)
## Typora:
![圖片](https://user-images.githubusercontent.com/1394735/56678870-49f08c00-66f6-11e9-833d-9841aed71fae.png)

**Comment by laurent22** [comment]
Any chance you could test with relative link in typora and atom? If it does work I guess that's what we should use as that way it will also work on vscode.

**Comment by ianzhuo** [comment]
for test, I make a /resources copy under /tmp and rename as "/resources-underworkspace"

JopolinProfile
    /resources
    /tmp
         /resouces-underworkspace

In vscode, relative link only under workspace.
atom and typora accept absolute link and relative link.
Perhaps you should consider create tmporary md file under /JoplinProfile to make all external editor work with image preview. 
![圖片](https://user-images.githubusercontent.com/1394735/56821373-af708400-6880-11e9-90d1-f3aa138b115f.png)
![圖片](https://user-images.githubusercontent.com/1394735/56821402-c7480800-6880-11e9-8919-e44ed68dc02f.png)
![圖片](https://user-images.githubusercontent.com/1394735/56821507-1beb8300-6881-11e9-9dcc-591047fb07c4.png)

**Comment by laurent22** [comment]
Many thanks for looking into it @ianzhuo. What do you mean by workspace? Does it mean that the temp md file and resource files need to be under the same directory? If not, could you explain what directory structure would work under vscode?

**Comment by ianzhuo** [comment]
Yes it does.
In vsocde, /resources and temp md file must be in the same directory to make markdown preview worked.
