### ISSUE TITLE
Typing the backtick character in editor should enclose selected text

### ISSUE THREAD

**Issue by glowinthedark** [laurent22/joplin#1426]
Typing the backtick character with a selection replaces selection instead of enclosing the selection with backticks.

Current behaviour
-------

Currently selecting a word and typing a single backtick character replaces the selected text with the backtick.

Expected behaviour
--------
Typing a single backtick with a text selection should surround the text with backticks rather than replacing the selection.

i.e. given a text selection of
```
spam
```

typing the backtick character should produce the following result:

```
`spam`
```

 Backticks should work in the same way as other pairing symbols which currently already have the expected behaviour, i.e. single quotes, double quotes, round brackets, square brackets: 
```
' " ( [
```

**Comment by inimitablemind** [comment]
I down vote that. it will create issues with creating code blocks.

Plus its not difficult to back tick twice and left arrow once.

**Comment by tessus** [comment]
Maybe it's a bug in the Ace editor that is used in Joplin. I checked the Ace Editor Test web page and there a backtick encloses selected text properly.

**Comment by glowinthedark** [comment]
@tessus: this is indeed an issue with the ACE editor: typing the backtick encloses the selection _only_ for some document types such as **Javascript** and **Java** but NOT for **Markdown** (also not for HTML, SML, C/C++, Python).

Verified in the ACE full-featured demo editor: https://ace.c9.io/build/kitchen-sink.html

**Comment by tessus** [comment]
@glowinthedark maybe there's away to change this in the config for the editor. if you can find this out (maybe open a ticket with ace) I am more than happy to make the change in Joplin. I'm confident that Laurent understands the merrits of such a change...

**Comment by laurent22** [comment]
This is a bug in their Markdown theme it seems so probably worth reporting on their forum.

**Comment by tessus** [comment]
@laurent22 I've reported this to the ace team and they fixed this in https://github.com/ajaxorg/ace/commit/e2adfefdeea85ba3f38a5a74f18adf596d056ea5

However, it seems the we are using react-ace, which uses brace, so I'm not sure how to fix this. I also asked, if we could do this in userland and the answer was that we could:

_You can add the $quote property to the mode similar to the commit._ 

```
this.$quotes = {'"': '"', "`": "`"};
```

I don't know the Joplin code very well, but you should be able to find the location where to add that property rather quickly. If you point me in the right direction I can play around with it.

**Comment by laurent22** [comment]
I'm not planning to look into this at the moment but you can check in NoteText.jsx to see if you can add the config. If I remember well it's not so simple due to the React wrapper.

**Comment by tessus** [comment]
I don't really understand how the architecture works (react, reducer, IPC, ...). I've been learning how to code a few things in js, but I have no clue how all these components work together. Maybe @CalebJohn and @innocuo can help with this. They have a far better understanding of the internals.

**Comment by CalebJohn** [comment]
I gave this a quick look but I think it'll be more effort than it's worth, the fix really should happen upstream (in brace). It's probably a better use of time to look into alternative editors.

**Comment by tessus** [comment]
@CalebJohn Fair enough. Thanks for looking into it.

**Comment by innocuo** [comment]
I agree this probably should be fixed in the source, but I found a way to add it dynamically. PR #1534.

**Comment by tessus** [comment]
@glowinthedark unfortunately we had to revert the support for this, because it had some side effects.

However, I've added a shortcut, so you can select a text and press ``` Cmd+` ``` (macOS) or  ``` Ctrl+` ``` (Linux, Windows) to enclose it with a backtick.
I've also opened a ticket with the Ace editor and they have fixed this (the original issue and the side-effect) in their code. But it will take a while before these changes will make it to `react-ace` and `brace`, which are the packages we are using as the glue for the Ace editor. So until all upstream packages include the fix, you will have to use the shortcut.
