### ISSUE TITLE
Checkboxes behind bullets do not work

### ISSUE THREAD

**Issue by koiulpoi** [laurent22/joplin#1427]
### Operating system
- Windows
- Android

### Application
- Desktop
- Mobile

The following text doesn't function correctly:

- - [ ] (item)

`- - [ ] (item)`

I would expect this to make it a checkbox behind a bullet, and it does render correctly. However, interaction is not handled correctly.

On Desktop (Windows), clicking the Checkbox doesn't actually check the item off. I would expect it to change to: - - [X], but it does nothing. Moving away and back to the page and the render is un-checked again.

On Android, clicking this checkbox crashes the app.

**Comment by necotec** [comment]
test this:
- [x]
and this:
- [ ]

**Comment by dayfuaim** [comment]
This works in Joplin 1.0.142:
```
- - [ ] item
- - [x] item2
```
![Снимок экрана 2019-04-17 в 00 07 29](https://user-images.githubusercontent.com/1274699/56244122-d40c7500-60a4-11e9-92ee-1d60b4cfcd89.png)

**Comment by koiulpoi** [comment]
> 
> 
> test this:
> " - [x] "
> and this:
> " - [ ] "
> 
> without the " ;)

Yes, that's the code for a regular Checkbox. As I posted, I'm referring to checkboxes behind bullets. Please refer to my original post.

**Comment by laurent22** [comment]
That's not valid syntax so it shouldn't render a checkbox normally. I think the fix will be to disable the rendering.

**Comment by koiulpoi** [comment]
> 
> 
> That's not valid syntax so it shouldn't render a checkbox normally. I think the fix will be to disable the rendering.

If you look at my original, now edited post, you'll see that Github renders it correctly...

**Comment by necotec** [comment]
@koiulpoi i have tested it on my Joplin V1.0.140 (Linux).
It is working fine with your syntax. On Android, it is working fine too. 
![joplin_checkboxes](https://user-images.githubusercontent.com/34749799/56274488-195d9080-60ff-11e9-847c-1b266ed2dcb5.png)

**Comment by koiulpoi** [comment]
> 
> 
> That's not valid syntax so it shouldn't render a checkbox normally. I think the fix will be to disable the rendering.

If you look at my original, now edited post, you'll see that Github renders it correctly...

> 
> 
> @koiulpoi i have tested it on my Joplin V1.0.140 (Linux).
> It is working fine with your syntax. On Android, it is working fine too.
> ![joplin_checkboxes](https://user-images.githubusercontent.com/34749799/56274488-195d9080-60ff-11e9-847c-1b266ed2dcb5.png)

Yes, the syntax renders find for me too. That's not what I spoke about in my original post.

The issue is the interactivity. If, on the render pane on the right, you "check" one of the checkboxes, it should change to `- - [X]` automatically, but it doesn't. This functionality works normally for `- [ ]`, in other words ones behind bullets.

On Android for me, attempting this same interactivity (checking one of the checkboxes) results in a crash.
