### ISSUE TITLE
[Feature request] Todo-complete bar

### ISSUE THREAD

**Issue by TobiasDev** [laurent22/joplin#1429]
I personally keep several notes with tons of Todo's in them for larger tasks. I guess you kind of could call them milestones. :) Eg. Todo, Thursday 18.4, Todo, Friday 19.4, etc. For stuff I need to get done daily. 

It would be really motivating if there was progress bar at the top of the note, under the WYSISWG editor, that has current procent completed of all tasks inside that note. I mean this is not something huge that I feel is a must have, but it would be something that I would love to see and that would motivate me to get all my tasks done as I can see the progress bar fill up as I complete tasks!

**Comment by TobiasDev** [comment]
Something like this: https://imgur.com/8CvnsbZ

**Comment by Stele77** [comment]
I dont know if this helps, but Inkdrop ( [inkdrop.app](url) ) which also is an Electron based markdown note taking app has this implemented like this:
![Inkdrop_EHs6VIOj2f](https://user-images.githubusercontent.com/21282842/59567891-d3c43200-9073-11e9-8a0e-77a229b783d3.png)

It looks just like the progress bar on Github issues, so maybe there is an easy way to use that?
I sadly cant help on the details, i have no idea about coding except BASH ;). But i believe Inkdrop dev just seemed to reuse this implementation from Github, so maybe that is indeed an option?
