### ISSUE TITLE
Plugin GotoAnything. Error with national characters.

### ISSUE THREAD

**Issue by wofs** [laurent22/joplin#1432]
### Operating system

- Windows

### Application

- Desktop 1.0.142

This plugin incorrectly uses the letter "Л".

![2019-04-19_21-04-33](https://user-images.githubusercontent.com/841974/56434723-d78f3e80-62e6-11e9-8949-75a42ddbd75a.png)

Besides, in the note everything is all right.
![2019-04-19_20-45-24](https://user-images.githubusercontent.com/841974/56434659-88490e00-62e6-11e9-928f-5df08595e900.png)

**Comment by laurent22** [comment]
Could you copy and paste the Russian text here so that I can test?

**Comment by wofs** [comment]
Yes, certainly.
"Съешь же еще этих мягких французских булок да выпей чаю."
![2019-04-20_16-52-49](https://user-images.githubusercontent.com/841974/56457502-c7319f00-638c-11e9-8feb-3cde1549f4d0.png)
Thank you for your prompt reply.

**Comment by laurent22** [comment]
Thanks, I've just realised that this has actually been fixed in 72b36522e810451e36ca1886bd40904253e21641 so it should work from the next release.
