### ISSUE TITLE
Joplin crashes when first opened

### ISSUE THREAD

**Issue by PopeRigby** [laurent22/joplin#1436]
### Operating system

- Windows 10

### Application

- Desktop

After opening Joplin for the first time after boot, it will crash. To use it, you have to open it again, then it will be fine.

**Comment by tessus** [comment]
Do you have some crash information that we can look at? Does Windows produce a crash report?

**Comment by lumbo7332** [comment]
Where are the crash logs stored?

**Comment by tessus** [comment]
I'm sorry, I do not know. The only thing I know about Windows is how to spell it.

@laurent22 do you know, if Windows creates a crash log/file/dump?

**Comment by lumbo7332** [comment]
There's an event viewer, but I have no idea how to use it, and all the online guides I've found are useless.

**Comment by tessus** [comment]
I'm gonna ask 2 of my colleagues who are really good with Windows. They should be able to tell me how to get a crash log.
We need to see what actually happened. The crash log (or actually the stack trace within the log) should tell us what function was called when the crash occured.

**Comment by Dasymi** [comment]
If it’s of any relevance, I use Joplin on Windows and so far it’s not behaving that way.

**Comment by lumbo7332** [comment]
@tessus I've found no crash log for Joplin, which is weird. I looked through all the event viewer errors and none of them came from Joplin.

**Comment by tessus** [comment]
@lumbo7332 I talked to several of my colleages and they all told me that the EventViewer should include something like a crash log. I am not a Windows user, I don't have a Windows machine or VM to reproduce the error, therefore I won't be of any help from this point forward.

But to solve this problem, we need some sort of information why it crashed. If we don't have that info, there's nothing we can do.

**Comment by lumbo7332** [comment]
I'll boot into safe mode and try again

**Comment by PopeRigby** [comment]
Sorry for taking so long. I have a crash log [here](https://send.firefox.com/download/add9f28734fd2d04/#lF65SL05_JNIt8fhXuMdlg), @tessus.

**Comment by tessus** [comment]
Unfortunately I cannot read .evtx files. These are binary files for Windows. I do not have a Windows system. Isn't there a way to export this to a text file?
@laurent22 does this file help you narrowing down the issue?

**Comment by PopeRigby** [comment]
Oops. Here you go: https://send.firefox.com/download/89d0860d680f6a43/#ZTswJcXVs1AGf1CfMMlC4A

**Comment by laurent22** [comment]
The log files doesn't seem to contain any crash or events related to Joplin unfortunately.

**Comment by PopeRigby** [comment]
That's what I feared. That's the only log file I got from the event viewer. I did have a folder pop up on my desktop that had a Joplin log, so I could upload that when I get home.

**Comment by PopeRigby** [comment]
[Here's](https://send.firefox.com/download/176a81a89857ecae/#zNtQU12eF5YvWFqeuPAFeA) the metadata file I found, @tessus. It showed up on my desktop in a folder labelled `LocaleMetaData`.

**Comment by PopeRigby** [comment]
I think I might know the problem. I think Joplin is minimizing itself to the tray as soon as it's opened. I can replicate what happens when I boot up by

1. Opening the tray
2. Right clicking Joplin
3. Clicking 'close'
4. Re-opening Joplin

It immediately closes the current window and minimizes to the tray. Is this intended behavior? If it is, that's kind of annoying.

**Comment by tessus** [comment]
check your settings:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/223439/59237393-24491480-8bc8-11e9-911b-beacdceae607.png">

**Comment by tessus** [comment]
Oops, I wasn't done writing...

You would have to uncheck `Start application minimized in the tray icon`. If it is and it still gets minimized at start, it's a bug. :-(

**Comment by PopeRigby** [comment]
That was ticked. I feel dumb.

**Comment by tessus** [comment]
No worries. This happens.
