### ISSUE TITLE
iOS Bug: Last line of text hidden, unable to scroll down to see

### ISSUE THREAD

**Issue by diver-down** [laurent22/joplin#1437]
### Operating system

- iOS  [v. 12.2 (16E227)]  [iPhone XR]

* * *

### Application

- Mobile  [Joplin v.10.0.30, Database v18]

* * *

### Bug Report and Attachments

On Joplin for iOS (latest versions of all, annotated above) on iPhone XR the last row of text and the cursor is hidden when trying to edit text. 

A picture is worth a thousand words, so hopefully the attached screenshot helps a bit!  :)

![IMG_0928](https://user-images.githubusercontent.com/35608185/56476231-e0a51a80-6462-11e9-9011-9d84f2cfb20a.PNG)

* * *

### Current Workaround 

Although awkward at best, I'm able to get around this for now by mashing enter several times, inserting a single character or word, then tapping further up to select the row I was trying to edit. (now, the new "lower" row is hidden instead)

* * *

Hope this report helps! :)

**Comment by diver-down** [comment]
JFC, silly bot, **yes this is still a problem**

**Comment by laurent22** [comment]
Note: best solution would be to include a large white space below editable so that it can be scrolled as needed.

**Comment by bedwardly-down** [comment]
@diver-down I can confirm that this is still a big issue with 13.3 on all iOS keyboards. One fix I implemented despite being a pain when I'm out and about for work and want to take a quick note: carry my bluetooth keyboard around and type with it when I have downtime at work.

**Comment by diver-down** [comment]
> @diver-down I can confirm that this is still a big issue with 13.3 on all iOS keyboards. One fix I implemented despite being a pain when I'm out and about for work and want to take a quick note: carry my bluetooth keyboard around and type with it when I have downtime at work.

Same on my end — still an issue on iPad Pro (10.5”), iPhone (5S, 6S, and XR).

## Two workarounds I’ve found:

1) Use a bluetooth keyboard
2) Insert a single character (./-/etc) and several line-returns above, and then go back to typing. This created the white-space needed. Problem with this: entering a note to edit positions the cursor at the last character (normal and expected, so thanks!) which means I have to reposition my cursor above the generated white-space every time I use this workaround.

Just to clarify: I’m not complaining, just confirming the issue also still exists from my end as well! 
(love Joplin, on Patreon, and use it every day for work and personal life!)

**Comment by bedwardly-down** [comment]
> > @diver-down I can confirm that this is still a big issue with 13.3 on all iOS keyboards. One fix I implemented despite being a pain when I'm out and about for work and want to take a quick note: carry my bluetooth keyboard around and type with it when I have downtime at work.
> 
> Same on my end — still an issue on iPad Pro (10.5”), iPhone (5S, 6S, and XR).
> 
> ## Two workarounds I’ve found:
> 1. Use a bluetooth keyboard
> 2. Insert a single character (./-/etc) and several line-returns above, and then go back to typing. This created the white-space needed. Problem with this: entering a note to edit positions the cursor at the last character (normal and expected, so thanks!) which means I have to reposition my cursor above the generated white-space every time I use this workaround.
> 
> Just to clarify: I’m not complaining, just confirming the issue also still exists from my end as well!
> (love Joplin, on Patreon, and use it every day for work and personal life!)

Glad I'm not the only one with a bluetooth keyboard for their phone. I may have to implement your second method, though. Thanks

**Comment by diver-down** [comment]
Bug persists. I just verified now. Running v. 10.0.46 on iOS, iPhone XR, Database v.28

**Comment by diver-down** [comment]
Was able to grab a quick screencap. This is the furthest down I’m able to scroll (the entire last line of text is hidden)

![A507ED73-D393-466D-831E-1E45A4771849](https://user-images.githubusercontent.com/35608185/78734104-55dc5a80-7915-11ea-9820-ce414f9b4749.png)

**Comment by laurent22** [comment]
It will be in the next release.
