### ISSUE TITLE
Feature Request: Add Alerts to notes

### ISSUE THREAD

**Issue by trymeouteh** [laurent22/joplin#1438]
There is a feature to add notes to ToDos but not Notes. Please add the option for alerts on notes.

**Comment by foxmask** [comment]
note can become a todo with or without reminder ; which is in fact an "alert" isnt it ?

**Comment by trymeouteh** [comment]
Why cant notes have alerts? I do not see why not. Every note I have that I want an alert on has to be a todo.

**Comment by cbennydesuza8** [comment]
I would like this also. I think it is logical for notes to have alarms just like todos.
