### ISSUE TITLE
[Feature Request] Search in note support

### ISSUE THREAD

**Issue by martinpengellyphillips** [laurent22/joplin#144]
### Operating system

- [x] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [x] Desktop
- [x] Mobile
- [ ] Terminal

---

Would be great for long notes to be able to search within the note itself for specific text, much like how you can "Find in page" in a web browser.

**Comment by technoboi** [comment]
For me searching within a note is an absolute 'essential'. I successfully converted about 1300 Tomboy Notes to Joplin. They sync well between a Linux desktop and my Android phone. From that viewpoint I am very happy with the way it works. However, many  of my notes are very long and all are technical. It is proving too time consuming to search manually within these notes and  so, until/if this becomes a feature I'll have to return to Tomboy.

**Comment by laurent22** [comment]
@technoboi, I'm still not set on what would be a good search feature. Any suggestion on what makes the Tomboy search better?

**Comment by technoboi** [comment]
On Tomboy Notes it is possible to make an initial global search. This searches everything in all documents - Headings and message bodies. Then, choose from the list of 'finds' as one does in Joplin. So, up to now Tomboy and Joplin are the same. Once in the chosen note the original global search term is highlighted throughout the document.  There is a search box within the note display. In that box is the global search term but that can now be changed and that new search term will change the highlight as appropriate. Starting at the beginning of the document it is possible to use Ctrl-g to progress through all the instances of the search term.
Where Joplin is superior to Tomboy is that it allows file attachments, the sync appears to work well and the Android application isn't sluggish. About seven years ago I made a video on Tomboy. Beyond 6 minutes it is all out of date but the rest is valid. It doesn't specifically show the 'in note' search but you can see the search box. The video might also give you some other ideas.
https://www.youtube.com/watch?v=xCstHOCVExA

**Comment by laurent22** [comment]
Thanks @technoboi, that makes sense. From that I think the key missing features at the moment are:

- Highlighting search results

- Searching within the current note

A way to change the search query once a note has been opened like you mentioned would also be useful.

**Comment by laurent22** [comment]
**Technical note**: use [Full Text Search SQLite extension](https://sqlite.org/fts3.html), which will provide ranked results and allow using a limited querying language (AND/OR).

```sql
CREATE VIRTUAL TABLE notes_fts USING fts4(content="notes", title, body);

INSERT INTO notes_fts(docid, title, body) SELECT rowid, title, body FROM notes;

SELECT title, offsets(notes_fts) length(offsets(notes_fts)) - length(replace(offsets(notes_fts), ' ', '')) + 1
FROM notes_fts
WHERE notes_fts
MATCH 'test';
```

**Comment by JSoet** [comment]
Just want to check about this, as far as I can tell the second point mentioned about searching within a current note doesn't exist right now, correct? You need to go outside of the note and then search and then the results are highlighted in the note, but there's no way to jump to the next found instance or anything is there?
