### ISSUE TITLE
Input bar problem in Fedora/Linux with 200% screen

### ISSUE THREAD

**Issue by xijiang** [laurent22/joplin#1441]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

**Comment by xijiang** [comment]
When using a 4k screen and 200% display enlargement, the ibus input bar is out of screen often. To input CJK in other programs doesn't have such problem. I think this is maybe because of one of the parameters in Joplin is still using the original resolution. Hence the input bar is twice the distance away from the up-left conner of that of the input position.

**Comment by laurent22** [comment]
Any screenshot?

**Comment by xijiang** [comment]
Confirm on screen of different resolution. https://www.getsky.no/share/jvtcneieep1g . so 4k is irrelevant. Any screen display with 200% or other enlargement ratio will have this problem.
