### ISSUE TITLE
Allow opening the note when selecting reminder from the notification bar

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#1442]
### Operating system

- Android (8.1.0)

### Application

- Mobile

### Description

When a reminder is triggered, a notification is available in the notification status bar.
It  could be helpful if we could open that note when selecting that reminder.
Actually that just open joplin on the welcome page.

**Comment by tessus** [comment]
At least it does something. ;-) (On macOS the show button does nothing.)

I think for this feature to work deep linking or a subset of it would have to be implemented. But I think it would be worth it. Unfortunately I have no idea how to do this with a js and/or react-native application.

**Comment by foxmask** [comment]
>  I have no idea how to do this with a js and/or react-native application.
i imagined that the notification could get a piece of code that will be able to do the correct call(back) to joplin. that seems to not be as simple as i said.

**Comment by foxmask** [comment]
may be one day
