### ISSUE TITLE
Create new note in external editor

### ISSUE THREAD

**Issue by mark6400** [laurent22/joplin#1443]
### Operating system

- macOS

### Application

- Desktop

### Issue

I'd like to create notes in an external editor. I use the following commands: "New note", then "Open in external editor". This does not open the external editor.

But this does work: if I create a new note, then enter a single character in the title field (thereby causing the "Creating new note..." default text disappears), such as a single space, *then* the note opens in the external editor; I can then backspace out the single character and begin to create the new note.

This workaround is manageable, but the underlying behavior seems odd, and it may make sense to streamline this for folks (such as myself) who like to do their typing in their text editor of choice.

**Comment by innocuo** [comment]
The app forces saving an empty note on the following actions:
- adding a tag
- attaching a file
- setting an alarm

So it'd make sense the same behavior applies when you click on "edit on external note"
But it doesn't seem straightforward.

calling saveIfNeeded(true) before trying to open the external editor saves the note, but has 2 issues:

1. The default note title is "Untitled", but users might be expecting a completely empty note to edit?
2. saveIfNeeded(true) tries to update the external note file, to the call the external editor, which saves the note file. Could this cause any issues?

If that is not good enough, the other option would be to save the note to create it, then clear the title and save again, and only then open the external editor. Any better ideas?

**Comment by laurent22** [comment]
> If that is not good enough, the other option would be to save the note to create it, then clear the title and save again, and only then open the external editor. Any better ideas?

I think that should be the way. Maybe we could have an option that disables the auto-title in that case, so that we can open the note directly.
