### ISSUE TITLE
reminder not shown on linux notification status bar

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#1444]
### Operating system

- Windows
- macOS
- [x] Linux (ubuntu 18.04)
- Android
- iOS

### Application

- [x] Desktop v 1.0.142
- Mobile
- Terminal

### Description

when creating notes as reminders, not any reminder are shown at the expected moment.

**Comment by foxmask** [comment]
I will have a loook at https://github.com/laurent22/joplin/issues/476#issuecomment-387842877 because I change of PC and distrib too (ubuntu 18.04 now instead of my lovely debian 9)

**Comment by foxmask** [comment]
installed notfy-osd (i thought it should already be the case by default on ubuntu) then notifications appear

**Comment by gerroon** [comment]
I do no get any notification either on Debian Buster, Fluxbox
