### ISSUE TITLE
"External" indicator icon remains after updating note / closing editor

### ISSUE THREAD

**Issue by NginUS** [laurent22/joplin#1445]
### Operating system

- Linux Mint 18.3 (Ubuntu 16.04)

### Application

- Desktop 1.0.143

After closing the note in the external editor, its content updated correctly in Joplin, but I had to exit & restart the app for the little square 'external' indicator icon to disappear from the note entry on the left.

**Comment by laurent22** [comment]
Work as intended. You can also click on the toolbar button to stop watching the file.
