### ISSUE TITLE
[Feature Request] One way Sync

### ISSUE THREAD

**Issue by CS-GSI** [laurent22/joplin#1447]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

I use File Sync as a automatic backup only and therefore am not interested in syncing two ways. 
A potential risk is accidentally delting/changing the synced files. It would be nice to have a one-way-sync option (Joplin to File System) so changes are not written back to the Joplin Database.

**Comment by laurent22** [comment]
For backup, there's the export feature. That's essentially one way sync already.
