### ISSUE TITLE
Can't synchronize due to 2fa on Nextcloud [Solved]

### ISSUE THREAD

**Issue by JasonMeg** [laurent22/joplin#1453]
### Operating system

- Android

### Application

- Mobile

When I enable 2fa on Nextcloud, I get this message
![joplin](https://user-images.githubusercontent.com/40995110/56732382-d1c1af00-6765-11e9-8093-0485227604fa.jpeg)

When I disable it everything is fine. Is there a workaround for this that I am missing?

**Comment by laurent22** [comment]
I'm not familiar with 2FA on Nextcloud, but don't you need to go to your Nextcloud account, then allow that particular application?

**Comment by JasonMeg** [comment]
No, not really. You just give Joplin the WebDAV, username, and password and it connects. It's not like Dropbox. The problem is that when Joplin tries to connect to NextCloud, the algorithm can only see 2fa instead of being able to access the files directly. And because it can't complete 2fa, I get this error.

**Comment by laurent22** [comment]
As I understand 2FA is quite new in Nextcloud? If so maybe it doesn't work quite well with WebDAV yet, did you try to report this on their forum?

**Comment by JasonMeg** [comment]
No, not yet, but I just found something important, give me a minute and I will report back.

**Comment by JasonMeg** [comment]
Ok, I figure this out. 
![image](https://user-images.githubusercontent.com/40995110/56733649-7bef0600-6769-11e9-88ee-d0c62cfb4529.png)

It turns out you can create a one-time password that bypasses 2fa. Sorry for wasting your time.

**Comment by laurent22** [comment]
No problem, it's always good to understand how it works. I'll add an entry linking to this post on the FAQ.
