### ISSUE TITLE
Installer is marked as FileRepMalware by AVG Antivirus

### ISSUE THREAD

**Issue by cyberdelphos** [laurent22/joplin#1455]
### Operating system
- Windows

### Application
- Desktop

Installer is considered as FileRepMalware by AVG Antivirus. Cannot upgrade.

![image](https://user-images.githubusercontent.com/6488860/56751532-f0b34780-674b-11e9-9959-b013de983e3e.png)

**Comment by laurent22** [comment]
Nothing we can do - it needs to be reported to AVG as false positive.

See VirusTotal results - https://www.virustotal.com/#/url/a98519748cc34c8bdd5b37cd59d1923bdd1ee16043bb7ba4f2eadd516c3cf9d0/detection

**Comment by TJHdev** [comment]
Same with Avast on windows
