### ISSUE TITLE
[Feature request] Plantuml support

### ISSUE THREAD

**Issue by vlaw** [laurent22/joplin#1458]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- ~~Terminal~~

This is quit an amazing software , thanks for all  the efforts. And  I saw a lot  of plugins built-in  already. I'd like to request a feature ([plantuml](http://plantuml.com) support) that might prove useful to others as well. Hope  it could be implemented as a  plugin as  well. Maybe something    like this?

```
    ```puml

    Class Stage
    Class Timeout {
	    +constructor:function(cfg)
	    +timeout:function(ctx)
	    +overdue:function(ctx)
	    +stage: Stage
    }
    Stage <|-- Timeout
    ```
```

Thanks!

**Comment by initjsk** [comment]
I would also really love this feature. It would be great for software documentation.

There is already a plugin for this [Visual Studio Code](https://blog.anoff.io/2018-07-31-diagrams-with-plantuml/).

Also, I found a markdown-it plugin for it: [markdown-it-plantuml](https://github.com/gmunguia/markdown-it-plantuml) so it should be possible to integrate with Joplin, right?

**Comment by evilSwanson** [comment]
Plantuml support would be great :+1:

**Comment by laurent22** [comment]
How does it compare to Mermaid? Someone knows?

**Comment by danil-tolkachev** [comment]
> 
> @laurent22 
> How does it compare to Mermaid? Someone knows?

From [here](https://ruleoftech.com/2018/generating-documentation-as-code-with-mermaid-and-plantuml#comment-400051):

> Plant UML is definitely more mature (older) and solves very wide number of UML issues and different kinds of diagrams. It is not implemented in a “modern way” using javascript, but java. That might be the actuall advantage to some folks. Basically it is java server returning images generated from PlantUML language. It is complex to run localy for individuals or smaller teams. Especialy on Windows machines. Even using VS Code. Using public www based server(s) is of course possible, buit not an option for many teams.

> Mermaid is just a pretty small, wildy popular, JS library, made by one man team with 47 contributors … There is no server required. Images are produced dynamically by JS code behind. There is also a CLI tool.

**Comment by huyz** [comment]
Would just like to suggest creating a markdown keyword that says `plantuml`, not `puml` (why a create a new potentially-confusing keyword?).   Example prior art: https://github.com/mikitex70/plantuml-markdown

**Comment by laurent22** [comment]
Thanks for the info @danil-tolkachev. If a full server is needed to support this, I don't think it will be included.

**Comment by observerss** [comment]
+1 for this feature

plantuml can be easily integrated using plantuml server service like http://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000 , they even open sourced that server and made Dockerfile for that: https://github.com/plantuml/plantuml-server

Boostnote has included plantuml feature in this way, as far as I can guess, because when you typing too fast(change too fast), the plantuml server will return rate limit information.

**Comment by huyz** [comment]
Alternatively, rely on the command line instead of a server.
On macOS, I have the `plantuml` binary  installed using `brew install plantuml`.
So the desktop app could just invoke it from the $PATH.

**Comment by danger89** [comment]
Yup. needed feature!

**Comment by danger89** [comment]
ps. @laurent22 No full server is required, only Graphviz dot, which can be made part of the Joplin desktop app for example.

**Comment by danger89** [comment]
Ps. ps. the official external server would be: https://www.plantuml.com/plantuml

**Comment by danger89** [comment]
Ps. ps ps. It requires only some simple encoding en voila! Please, read:
https://plantuml.com/text-encoding

So, hello world is encoded to:
http://www.plantuml.com/plantuml/png/Aov9B2hXil98pSd9LoZFByf9iUOgBial0000

And the Alice & Bob is encoded to this:
http://www.plantuml.com/plantuml/png/Syp9J4vLqBLJSCfFib9mB2t9ICqhoKnEBCdCprC8IYqiJIqkuGBAAUW2rJY256DHLLoGdrUS2W00

> For example, the following uml text description:
> 
> Alice -> Bob: Authentication Request
> Bob --> Alice: Authentication Response
> 
> is encoded as:
> Syp9J4vLqBLJSCfFib9mB2t9ICqhoKnEBCdCprC8IYqiJIqkuGBAAUW2rJY256DHLLoGdrUS2W00
> 
> To achieve such an encoding, the text diagram is:
>    * Encoded in UTF-8
>    *  Compressed using Deflate algorithm
>    *  Re-encoded in ASCII using a transformation close to base64
>

**Comment by pihentagy** [comment]
> Thanks for the info @danil-tolkachev. If a full server is needed to support this, I don't think it will be included.

An _own_ full server could be used (for privacy reasons).

But there is a public server, as @danger89 explained.

So my suggestion is (as seen in other markdown editors) to make plantuml rendering an opt-in feature, defaulting to use the public renderer, but having an option to specify a custom server.

Both `puml` and `plantuml` are common language markers, so why not support both?
