### ISSUE TITLE
Simplified page does not match Firefox Reader View

### ISSUE THREAD

**Issue by JLKM** [laurent22/joplin#1460]
Joplin has come a real long way offering exactly the features needed to get hold of your doings and readings. And the web-clipper is simply excellent.

I prefer to clip using the simplified page mode, and I use Firefox on Windows. Though, I've noticed, this mode doesn't get all the content, that's visible in Firefox Readers View.

Typically author names, subheadings and publishing dates get "lost in transition".

Any workaround or fix available or planned, so that this really user friendly mode could become more complete?

### Operating system
- Windows

### Application
- Desktop

**Comment by laurent22** [comment]
Joplin makes use of the lib developed by Mozilla for Reader View so normally it should give the same results. Perhaps it's a matter of updating the lib so I'll check.

**Comment by laurent22** [comment]
By the way, could you give the URL of the page that was causing an issue? For all clipper issues, a URL is necessary, otherwise it's not possible to test.

**Comment by JLKM** [comment]
With pleasure. Couldn't right away find a clip with a missing sub-headline compared ti Reader View. Bus here re two examples with missing time/date and author.

Time missing (9. maj 2019 - 22.51). Author mising (Laura Rode Nygaard):
https://www.bt.dk/underholdning/miss-danmark-angrebet-af-organisation-her-er-hendes-egen-version

Time missing (8. maj 2019 - 13:57). Author missing (Tanja Andersen):
https://www.version2.dk/artikel/windows-faar-linux-kerne-microsoft-med-koebet-1088048

**Comment by laurent22** [comment]
I've just updated the Readability lib that's used to get the simplified page and I didn't see any improvement for these two pages unfortunately. It's not something we can fix on our end so what I can suggest is to submit these two URLs to the Readability project and explain what doesn't work: https://github.com/mozilla/readability 

It's not sure they'll look at it, but it's worth a try (they did check when I posted an example of Guardian article that didn't work but it's a major site so it might different).
