### ISSUE TITLE
Duplicate notebook names must not be allowed

### ISSUE THREAD

**Issue by glowinthedark** [laurent22/joplin#1465]
Currently joplin allows creating notebooks with already existing names. This must not be allowed and a warning/error must be shown instead.

### Steps to reproduce

1. Click **New Notebook** and enter a name e.g. `dinsdale`.
1. Click **New Notebook** again and enter and enter the same name —`dinsdale`.

### Actual result
Two notebooks with identical names are created.

### Expected
Duplicated notebook names must not be allowed and a warning message must be shown. This must be consistent across multiple devices.

**Comment by Nebucatnetzer** [comment]
Why shouldn't it be allowed to have notebooks with the same name?
I often create notebooks for projects and then have a sub notebook with the name "Tasks" in each of the project notebooks.

**Comment by laurent22** [comment]
This is a feature - duplicate notebook titles are allowed.

**Comment by glowinthedark** [comment]
@laurent22: this is counter-intuitive: at least there should be a warning that there is already a notebook with the same name

**Comment by laurent22** [comment]
Enforcing this kind of constraint is far from trivial as it will have to be handled at every level of the app, on the three apps, when moving notebooks, renaming them, creating them, etc.

Disallowing duplicate names would also be an issue with sync - for example if two devices create a notebook with the same name, then sync. Both devices end up with a duplicate notebook name. You could say that the sync process should rename the notebooks automatically to something like "my notebook (1)", but then what if both clients also rename automatically to that same name?

And there are probably many other edge cases I haven't thought about. Basically it's not worth adding so much complexity to the app for a only a small improvement to the user experience.

**Comment by glowinthedark** [comment]
If two devices create a notebook with the same name then the most user-friendly approach would be to merge them into one so that there is only one notebook with the same name at a given hierarchy level.

And this would probably be better done not at the note level which at the implementation level shouldn't really have a name, but at the index level — ie a top-level object which will only keep track of links to actual notebooks and notes within the notebooks along with names and some metadata. <sup>(In fact I am planning to create another issue regarding this.)</sup>

**Comment by laurent22** [comment]
If you're interested in improving Joplin then a first step would be to make yourself familiar with the app architecture, sync process and so on. Perhaps try to implement what you're suggesting in a pull request, and you'll see you'll quickly hit some serious road blocks.

**Comment by glowinthedark** [comment]
I've already started looking at the code but js is not my core programming language and react/jsx is even less so, but I take this as an opportunity to learn and discover things. Right now I'm still far from being able to make a meaningful contribution, although I do believe in reusing generic code and patterns and not having to re-inventing the wheel.
