### ISSUE TITLE
Empty note titles lead to sync and UI issues, data loss also possible

### ISSUE THREAD

**Issue by innocuo** [laurent22/joplin#1468]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

I tested on Electron, but this is a bug in the common library, so I think it affects all apps.

### Description

- Create a note with a title and 4 lines. Example:
Title:
```
this is the title
```
Content:
```
this is line 1
this is line 2

this is line 4 (line 3 is empty)
```
- After the app has saved the note, delete the title, Result: 
Title:
```

```
Content:
```
this is line 1
this is line 2

this is line 4 (line 3 is empty)
```
- Synchronize the app (tested with nextcloud)
- On another device, synchronize the app to get this note.
- I believe device 2 will display a note like this:
Title:
```
is is line 1
```
Content:
```

this is line 4 (line 3 is empty)
```
- line 1 and 2 are gone from the content. Line 1 is now the title.
- Synchronizing again does nothing, even though now the note is different in each device. Sync works after you edit the note on either device

**Comment by innocuo** [comment]
The problem is in the serialize and unserialize functions in /lib/models/BaseItem.js
which can be fixed, but should the apps allow empty titles?

**I can submit a PR, but it'll take me a bit (job stuff).**

My notes on a possible solution.

in static async serialize(), you have:
```
if (output.title) temp.push(output.title);
```
output.title is evaluated as false. The .md file will have the body starting in the first line (that's why when syncing, it uses the first line as title).

fix:
```
if ( typeof output.title != "undefined") temp.push(output.title);
```

in static async unserialize(), you have:
```
let title = body.splice(0, 2);
output.title = title[0];
```
this gets rid of the second line in the .md file, which is why part of the original note gets deleted.
Fix: (untested)
```
let lines_to_remove = body[1].length > 0 ? 1 : 2;
let title = body.splice(0, lines_to_remove);
output.title = title[0];
```
This isn't really needed if serialize always works, but it'd minimize risks of data loss for those who don't update all their devices to the latest version.

Instead of an empty box in NoteList, it could retrieve the default title.

in displayTitle(item)
```
return !!item.encryption_applied ? '🔑 ' + _('Encrypted') : (item.title.length>0)? item.title + '' : Note.defaultTitle(item);
```

**Comment by laurent22** [comment]
I didn't check yet, but normally the notes serialize to this format:

```
Note title

this is line 1
this is line 2
```

And if there's no title, it should leave a blank line on top:

```


this is line 1
this is line 2
```

Is that not what's happening?

**Comment by innocuo** [comment]
as far as I checked, no, you end up with 
```
this is line 1
this is line 2
```
without the empty lines. I was testing on macOS, and syncing between another macOS and an android app instances.

**Comment by innocuo** [comment]
I'm closing this. There's a merged PR that solves this.
