### ISSUE TITLE
Support for middle mouse paste on Linux

### ISSUE THREAD

**Issue by cas--** [laurent22/joplin#1470]
I am using Joplin on Ubuntu Linux and I have found that it is missing the usual copy/paste for highlighted text. This is the ability to highlight text and then paste it using either middle mouse button or 'shift + insert' key press. (Note not the ctrl-c and ctrl-v clipboard)

So what I would like to see is to be able to select text anywhere and then be able to paste it with middle mouse button within a Joplin note. Also highlighting text within a note would be available to paste anywhere.

Relevant Electron issue: https://github.com/electron/electron/issues/377

Desktop v1.0.127 on Linux

**Comment by gardar** [comment]
+1 It always frustrates me that Joplin is the only application I use that's not able to copy/paste by selecting and using the middle mouse button.

**Comment by cas--** [comment]
I updated to latest version 1.0.173 and looks to be fixed! :+1:

**Comment by CalebJohn** [comment]
Tested on Ubuntu 20.04 with v1.0.229 and middle clicking still does not paste.

**Comment by CalebJohn** [comment]
Looks like this is only a bug with the AceEditor, so this should be fixed soon.

**Comment by CalebJohn** [comment]
fixed by #3703
