### ISSUE TITLE
Inefficient and faulty synchronization logic

### ISSUE THREAD

**Issue by glowinthedark** [laurent22/joplin#1474]
The way synchronization is currently implemented is inefficient, takes a lot of time and is apparently broken.

### Real life scenario

1. On the desktop version of Joplin setup dropbox sync with encryption and import over one thousand notes from an ENEX file to a single notebook.

1. Configure the same dropbox account and encryption on three mobile devices: two android clients and one ios. It took literally hours until everything was synched on all devices, although most of the data is just short text notes with almost no images and no file attachments. (NOTE: there is no issue with Internet connection speed which is roughly around 100Mbit).

1. Because syncing has now become so slow across devices I deleted the notebook with imported data from ENEX and triggered sync on all the devices. It again takes at least half an hour to sync all the items and delete all the items one by one.

After this operation the actual number of notes is 100+, and I get the following info for the **Sync Status**:

```
Sync status (synced items / total items)
Note: 142/142
Folder: 34/34
Resource: 19/19
Tag: 55/55
NoteTag: 1247/1247
MasterKey: 2/2
Total: 1499/1499
 
Conflicted: 0
To delete: 0
```

I am not sure what `NoteTag=1247` actually represents but it does not look right. Apparently even though over a thousand notes have been deleted there is still some metadata lurking somewhere. When I connected another client to the same dropbox account the number of synched items was also around `1499`  — how could this be if currently I only have less than 200 notes? 

### Suggestions
Maybe it would make more sense to maintain an index file which would contain the top-level structure including the names and titles of notes and notebooks, but not the actual note content? That would allow displaying the updated notes/notebooks in the tree almost instantly even before the actual content of the notes has been downloaded. Clicking such a note would display some kind of loader animation, and would prioritize fetching the content. Also it would be great to be able to have concurrent download threads so that remote files don't have to be fetched/pushed one by one. Not sure though if the dropbox API allows connection pooling, but I guess it should be possible to create multiple concurrent connections e.g. by instantiating multiple remote connection clients.

**Comment by laurent22** [comment]
For discussion about Joplin's feature, please use the forum. Many of these issues have been discussed already but feel free to contribute to the discussion.
