### ISSUE TITLE
Evernote import unusable formatting

### ISSUE THREAD

**Issue by crankedguy** [laurent22/joplin#1476]
### Operating system

- Windows

### Application

- Desktop

I am trying to import my notes from Evernote but this leaves me with complete unusable formatting as shown here. Is there any trick to get that right?

Evernote 
![image](https://user-images.githubusercontent.com/34091479/57020566-ec929880-6c29-11e9-95d6-f885ed003ea8.png)

Joplin 
![image](https://user-images.githubusercontent.com/34091479/57020585-0207c280-6c2a-11e9-94c0-1a3226b1e779.png)

**Comment by laurent22** [comment]
Could you attach your ENEX file?

**Comment by crankedguy** [comment]
Yes, sure


[Evernote.zip](https://github.com/laurent22/joplin/files/3134708/Evernote.zip)

**Comment by laurent22** [comment]
Hmm, unfortunately Evernote's HTML is broken and invalid, which is why it doesn't work. I'll check if there's some hack that can be added to make this use case work.

**Comment by crankedguy** [comment]
This would be nice from you. Will watch this issue here. Thanks.

**Comment by laurent22** [comment]
Fix will be in the next release.
