### ISSUE TITLE
Local (external) links to notes?

### ISSUE THREAD

**Issue by crankedguy** [laurent22/joplin#1477]
- Windows

- Desktop

OneNote has the really great possibility to create local links to notes which can be put into any other app (I use that from ClickUp heavily fro instance)
Will there ever be such functionality for Joplin. So if I click the link Joplin will open and show the note?

Thanks

**Comment by artkpv** [comment]
That would be really nice to have. Now when I import my notes from Evernote links are like this `[Text](evernote:///view/101111/111...)` Clicking this opens Evernote.
