### ISSUE TITLE
https://joplinapp.org/#notifications does not work

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#1478]
the `Tools/build-website.js` script does not do:
```
<h1><a name="notification">Notifications</a></h1>
```
but just
```
<h1>Notifications</h1>
```
so, when I'm in joplin and click on the link "notification" in the Tips note, https://joplinapp.org/#notifications does not work, we stay on the top of the page ...

this is an example but it's the case anywhere where the index.html uses a #paragraph 

I tried to fix that but does not spotted the part of the JS that handle the header generation

**Comment by foxmask** [comment]
that should do the trick 
```
# <a name="notification"></a> Notifications
```
i try to make the build

**Comment by laurent22** [comment]
It just needed a Markdown plugin to add an anchor to each heading. I've been meaning to do that for some times so I've just done it in that commit - 49c998de8338f581feaaca4f6091695688c124d7
