### ISSUE TITLE
[bug] [visual] Editor small visual bug: nested lists and code block

### ISSUE THREAD

**Issue by ventormo** [laurent22/joplin#1482]
**OS:** Xubuntu 18.04
**App:** Desktop v1.0.143

Desc: If I'm not mistaken, the syntax shown in the screenshot is correct, but Joplin recognizes part of the list as just text (white color). At the same time, if you remove the nesting of the list, everything will be displayed correctly.

What I expect: all items in the list should be yellow

What I get: third and next lines  are not perceived as part of the list and are painted white.

![pic](https://user-images.githubusercontent.com/50117913/57068677-1d7ed600-6cdb-11e9-80c6-7079eb9f640d.png)

**Comment by laurent22** [comment]
We can't fix this as it's a bug in the Ace Editor so it should be reported there.
