### ISSUE TITLE
sqlite3 build files seem to be present in macOS build

### ISSUE THREAD

**Issue by mgrandi** [laurent22/joplin#1488]
### Operating system
- macOS

### Application
- Desktop

### version
`Joplin 1.0.145 (prod, darwin)`

The sqlite3 source code , built object files (`build` folder), and dependencies ( `deps` folder) seem to still be present in the final build of joplin , which takes up like 15 MB that doesn't need to be there. Is this a problem with how joplin is built or is this a problem with the sqlite3 node library?

`ncdu` output: 

```
--- /Applications/Joplin.app/Contents/Resources/app/node_modules/sqlite3 
   14.5 MiB [##########] /build
    3.9 MiB [##        ] /lib
    2.7 MiB [#         ] /deps
    1.9 MiB [#         ] /bin
   40.0 KiB [          ] /src
    4.0 KiB [          ]  CONTRIBUTING.md
    4.0 KiB [          ]  LICENSE
    4.0 KiB [          ]  package.json
    4.0 KiB [          ]  sqlite3.js
```

**Comment by laurent22** [comment]
That could be an issue either with electron-builder or with the sqlite3 package, it's hard to tell. Maybe try to post this issue on their forums as I doubt we can do something on our side.

**Comment by tessus** [comment]
Any update on this?

**Comment by tessus** [comment]
@mgrandi have you had the chance to investigate this upstream?

**Comment by mgrandi** [comment]
I missed this conversation , sorry. I have not had a chance to investigate this upstream yet. 

Looking at your [package.lock file,](https://github.com/laurent22/joplin/blob/master/ElectronClient/app/package-lock.json), the sqlite version used is located here: https://registry.npmjs.org/sqlite3/-/sqlite3-4.0.6.tgz

i downloaded it and looked at what it contains, and it looks like its just the source code, and not anything compiled:

```text
$ tree /Users/markgrandi/Temp/sqlite3-4.0.6/package
/Users/markgrandi/Temp/sqlite3-4.0.6/package
├── CHANGELOG.md
├── CONTRIBUTING.md
├── LICENSE
├── README.md
├── binding.gyp
├── cloudformation
├── deps
│   ├── common-sqlite.gypi
│   ├── extract.py
│   ├── sqlite-autoconf-3260000.tar.gz
│   └── sqlite3.gyp
├── lib
│   ├── index.js
│   ├── sqlite3.js
│   └── trace.js
├── package.json
├── sqlite3.js
└── src
    ├── async.h
    ├── database.cc
    ├── database.h
    ├── gcc-preinclude.h
    ├── macros.h
    ├── node_sqlite3.cc
    ├── statement.cc
    ├── statement.h
    └── threading.h

4 directories, 23 files
```

so I am assuming that this is a problem with "electron-builder" as you said, should I report the bug there?

**Comment by tessus** [comment]
> should I report the bug there?

@mgrandi yes, this would be great.

**Comment by mgrandi** [comment]
after doing some investigation, i think the problem is actually with the `node-sqlite3` module, and i reported a bug on their github page:

https://github.com/mapbox/node-sqlite3/issues/1182

**Comment by mgrandi** [comment]
hello, they apparently have a new branch to test, can you see if this fixes the problem @tessus ? https://github.com/mapbox/node-sqlite3/tree/electron-builds-light

**Comment by tessus** [comment]
@mgrandi sure, I'd love to. But how? I'm still not very versed in js and its toolchain. I know how to update packages via package.json and build a project. I don't know how to use a branch for a module, instead of the published one on npm.

**Comment by mgrandi** [comment]
according to google, in package.json you do this:

```
To have npm install a public project that is hosted on Github, and not the NPM registry, add the Github repo to package.json dependencies using the username/repo#branch-name format.
```

https://medium.com/@jonchurch/use-github-branch-as-dependency-in-package-json-5eb609c81f1a

i don't have the NPM / electron whatever build environment set up myself either, but assuming its just as simple as changing the package.json dependency to use that branch, doing a full build and see if the sqlite3 folder in node_modules (for me on mac its `/Applications/Joplin.app/Contents/Resources/app/node_modules/sqlite3` ) has all of the build cruft

**Comment by tessus** [comment]
Great, thanks for the info. I'll have a look.

**Comment by tessus** [comment]
Ok, sorry that it took so long.

I tested this, but it doesn't seem to work.

Please note that I **ALWAYS** have to run `./node_modules/.bin/electron-rebuild` after installing sqlite3 via npm, otherwise I get `Uncaught Error: Cannot find module`.

After I run the `electron-rebuild`, the build directory is created in node_modules/sqlite3. I thought the branch should clean/remove the build dir after, but this doesn't happen.
`npm run dist` which creates the Joplin app, also does not remove the `build` dir.

@laurent22 maybe we have to add a script that deletes the build dir when running `npm run dist`.

**Comment by mgrandi** [comment]
maybe comment on the node-sqlite3 bug ticket i created, i don't know much about node/electron to be of much help =( 

https://github.com/mapbox/node-sqlite3/issues/1182

**Comment by mgrandi** [comment]
I don't have easy access to a mac computer anymore, i tried looking in windows and it seems that the sqlite build files are not there, so it might be a mac only problem?

**Comment by mgrandi** [comment]
the latest version of joplin (1.0.179) seems to still have the sqlite3 build files included

![image](https://user-images.githubusercontent.com/802786/74991377-07c1d500-5403-11ea-9507-b83bb6f6cdfc.png)

**Comment by tessus** [comment]
I'm not sure what we can do here. Sometimes an sqlite3 rebuild happens and then this dir is there. Excluding the dir from the build is an upstream issue. The build files are not copied for any other module, so why is it with sqlite3?
