### ISSUE TITLE
[CONTRIBUTION] Prettier support 

### ISSUE THREAD

**Issue by marcosvega91** [laurent22/joplin#149]
Hi @laurent22,

as we said in other posts, it can be possible to add prettier dependency that with the support of circle ci check if a commit or PL follow the settings inside .prettierrc file (use tabs for example). 
What do you think? Can i add the task inside package.json?

**Comment by laurent22** [comment]
Hi @marcosvega91, this feature would be useful but I'm mostly concerned whether it will make maintenance more difficult (by having one more piece of software to maintain and debug), or making building the app more complex (by adding a dependency). How would it work exactly? Will it be executed after the code has been pushed? Or is it on commit? Do you have an example of open source project that uses this?

**Comment by marcosvega91** [comment]
Hi @laurent22, yes https://github.com/facebook/Docusaurus for example uses this feature. The idea is to add a prettier task that reformat the code based on a config file, and a prettier diff that prints all files that not respect the guide line inside the config file. You can make your CI working with prettier, so when a commit is pushed the CI check if the code is well formatted. The user before commit has to run prettier task

**Comment by laurent22** [comment]
Sorry looks like I missed the last comment - I think the prettier task would indeed be useful and I would take a PR for it.
