### ISSUE TITLE
[Feature Request] Anchor jumping with between note links

### ISSUE THREAD

**Issue by sgtoutlaw** [laurent22/joplin#1490]
I love the ability to link between notes that is now available.  The only thing I want to be added to that is to be able to link to a section of a note from another note.

So when I link to another note I could do.

> [Random Link][1]
> [1]: :/noteid#jumptoheader 

As a result of this I could not only jump to the note, but also go to the _jumptoheader_ section of said note.

Right now doing anything similar keeps joplin from recognizing it.

**Comment by tessus** [comment]
/ref https://discourse.joplinapp.org/t/jumping-to-a-section-of-a-note-you-linked/2267

**Comment by deciacco** [comment]
Yes. this would be a great addition. I'd like to be able to create a "Table of Contents" of sorts for a long note, so I can jump down to a section of it really quickly without having scroll.

**Comment by tessus** [comment]
@deciacco I think you misunderstood this issue, unless you are talking about having the toc in one note and jump to a section of **another** note.

There's already a toc plugin available.

**Comment by deciacco** [comment]
@tessus thank you! I did! I just checked the plugins section of the settings and sure enough there it is.

**Comment by JLKM** [comment]
Referencing specific paragraphs seems to be possible with this rather new markdown rendering library [markdown-it-auto-parnum](https://github.com/dnotes/markdown-it-auto-parnum). This would be an awesome addition to the yet great collection of markdown plugins available by click in Joplin. And referencing those paragraphs might be possible using a syntax like `[Link to specific paragraph in specific note](:/b6e1acb07b48428da83ae4f7e8ab30d8#paragraph-number)`. This would in my opinion be a really useful feature for everyone writing long notes with lots of points, that call for direct anchor links.

**Comment by tessus** [comment]
@JLKM sounds good. Have you tried it? I could imagine that the problem is to make Joplin recognize this new format. But maybe I'm wrong. 
Just adding it as a plugin should be straightforward.

**Comment by JLKM** [comment]
Sorry to say I haven't tested it. Furthermore this feature may also need an addition to the renderer, which creates a hover showing the actual paragraph number for composing the correct anchor link. Or even a pop-up function creating the correct anchor link on your clipboard just like the present create-markdown-link feature... Hope someone has the setup and time to push/test this idea further.
