### ISSUE TITLE
Line break issue in the latest version

### ISSUE THREAD

**Issue by luckydays** [laurent22/joplin#1491]
### Operating system

- Linux

### Application

- Desktop

Hey guys.
Thank you for this ongoing Joplin support and development!

Somehow after updating to the latest version (1.0.145) I see the single line break in markdown editor doesn't reflect correctly in the preview mode and display things in one line.
Please, see the screenshot:

![image](https://user-images.githubusercontent.com/10942891/57195361-d0f10000-6f51-11e9-84ed-0eb0de0b5af9.png)

Could you assist with this one?

**Comment by subi54** [comment]
In the latest version, Tools > General Options > Plugins, there is an option for 'soft breaks'. Maybe it's ticked. Un-tick it and apply. Try restarting the app if nothing changes.

**Comment by luckydays** [comment]
Sure.
Wasn't aware at once that this tickbox is related to the issue.
Thanks for pointing this out @subi54
