### ISSUE TITLE
2 issues with attached resources

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#1492]
### Operating system

- Windows
- macOS
- Linux

### Application

- Desktop

---

I have noticed 2 problems with attached resources, although I think to remember that these things worked in the past.

Steps to reproduce:

attach an image called `test.jpg`
1. double click on the image in the preview pane - nothing happens
2. right click on the image in the preview pane and select `open...` - image opens, but does not show `test.jpg` as the name, but `<hash>.jpg`

Tested with git master on macOS 10.14.4.

**Comment by tessus** [comment]
@laurent22 is this a regression or was this functionality removed intentionally? If the latter, we could close this.

**Comment by laurent22** [comment]
It was always working as you described.

**Comment by tessus** [comment]
In that case I'm afraid we have a regression that crept in at one point.

**Comment by laurent22** [comment]
I don't think so. The filename has always be HASH.jpg and double-click on images has never been implemented as far as I remember.

**Comment by tessus** [comment]
It seems I misunderstood your previous statement then.

But I really think both worked at one point. I even opened an issue about a PDF file having the hash instead of the name. And then it was fixed and it showed the filename.
I will search for these issues and try to find the code changes that fixed them.

**Comment by innocuo** [comment]
you both are having a deja vu 😆 
this is a duplicate of #570, almost the same conversation, too. 
There's issue #618 about opening files with the right name, in a temp folder.

And there's [this post in the forums](https://discourse.joplinapp.org/t/file-attachments-lose-name-on-download/759), but I couldn't find the exact issue you were referring to.

**Comment by tessus** [comment]
Yes, you are right. But I also thought that item 2 had been fixed at one point. I really remember a commit that fixed this, but maybe I'm mixing this up with opening a PDF file (local link, not an attachment)...

So I guess we can close this issue as duplicate in favor of #618. @laurent22 what do you think?
