### ISSUE TITLE
[Feature request] Short note preview under title

### ISSUE THREAD

**Issue by reisub0** [laurent22/joplin#1494]
### Operating system

- Android
- iOS

### Application

- Mobile

Hi!

Thank you for this amazing piece of software. One small feature I'd really love to see on Joplin is the fact that on Evernote, as you scroll through your notebooks, you can see not just the title of your notes but also the first few lines of the note. This helps distinguish between multiple **Untitled Note**s. 
![pixelised](https://user-images.githubusercontent.com/25099244/57239082-89996b00-7048-11e9-80fa-ae25772f6dd8.png)

Similar to how on email, you see not just the subject of the email but also the first few lines or even just words of the email, just for context.

This is much more of an issue on Mobile vs Desktop because it's harder to scroll through individual notes and identify which one you're looking for.

It'd be pretty great if you could implement this feature. I'm also willing to submit a PR for the same if you could just point me towards what exactly I should be doing.

Thanks

**Comment by tessus** [comment]
Just keep in mind that this should be optional. I certainly wouldn't want this by default.

**Comment by chriswayg** [comment]
I also miss this feature on Joplin and would like to have it as a display option on mobile as well as in the desktop app. It is called 'Snippet View' on Evernote and makes it much easier to find notes. A thumbnail of the main image of the note would also be nice. The default 'List View' should still be available.

![image](https://user-images.githubusercontent.com/13681327/65413199-7e8e7e00-de23-11e9-8ae3-b2cf6a613750.png)

**Comment by tessus** [comment]
Maybe we should move discussions to the forum. The dev doesn't look at them on gh until they are accepted. I've changed the feature request template a while back, but I believe this one might have still created on error here on gh.
