### ISSUE TITLE
`L SEP` is displayed at the top during conversion of Japanese IME on Windows

### ISSUE THREAD

**Issue by kakkou** [laurent22/joplin#1497]
### Operating system
- Windows
### Application
- Desktop(1.0.145)

When you try to enter Japanese, `L SEP` is displayed at the beginning of the string.
It disappears when the conversion is finalized, but It is creepy.
![image](https://user-images.githubusercontent.com/696724/57288427-6a581780-70f4-11e9-8b7a-3fd92f3867ad.png)

**Comment by innocuo** [comment]
This is a duplicate of #1210

**Comment by laurent22** [comment]
Closed as duplicate
