### ISSUE TITLE
[Feature Request] Tags on whole markdown lines

### ISSUE THREAD

**Issue by simonsan** [laurent22/joplin#1498]
#### Operating system & applications
all platforms and applications

#### Tags on whole markdown lines
It's somehow connected to #1407, I want to propose the possibility to tag also single markdown lines and not just the whole note in a notepad.

That means if you tag let's say 3 lines you could do it like this, including syntax:

```
@personal::inspiration, @personal::sparetime::activities
{
Lorem Ipsum and so on.
Lorem Ipsum and so on.
Lorem Ipsum and so on.
};
```
Syntax explanation:
`@personal::inspiration` marks the following lines inside brackets as a hierarchical tag. `@personal::inspiration, @personal::sparetime::activities` are two separated "lines" of hierarchical tags. `::` is the known scope operator to go into next hierarchy. This means you would find the three lines of note inside all four tags - personal, inspiration, sparetime, activities. The `{` & `}` or some other bracket style show the beginning and ending of the multi-line tagged note. The `;` could be the definite end of that note (C-style), otherwhise you could add a second one to the same tags as the following:

```
@personal::inspiration, @personal::sparetime::activities
{
Lorem Ipsum and so on.
Lorem Ipsum and so on.
Lorem Ipsum and so on.
}
{
Lorem Ipsum and so on.
Lorem Ipsum and so on.
};
```
Syntax explanation: This would be two separate notes with the tags: personal, inspiration, sparetime, activities.

Related topic:
#375

**Comment by simonsan** [comment]
Would be still a highly appreciated feature honestly. <3

**Comment by laurent22** [comment]
Sorry we won't implement this at this time. We hope to add more tag-related features, but not via advanced markup like this. We prefer if the Markdown in use stay as close as possible to standard Markdown and provide extra functionalities directly in the apps.

**Comment by simonsan** [comment]
@laurent22 Thanks for the answer, what is your opinion on the related issue then?

https://github.com/laurent22/joplin/issues/375

**Comment by laurent22** [comment]
I think it should be implemented if possible. I've just added it as a project for GSoC.
