### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by goodevilgenius** [laurent22/joplin#1505]
### Operating system

- Linux
- Android

### Application

- Desktop
- Mobile
- Terminal

#### Issue

I recently got an update in F-Droid to Android version 1.0.245. However, on my desktop, joplin-desktop is on 1.0.145. Additionally, joplin-cli is at 1.0.125

I modified a note in Joplin for Android early this morning, and not, I can no longer sync either joplin-desktop or joplin-cli. When I try in joplin-cli, I get the error:

> Completed: 08/05/2019 07:00 Last error: Error: On file 2374e8eef5b8440a868d5a5a226b8689.md: Unknown type: 13

In joplin-desktop, I get a similar error, with an additional message saying "please upgrade Joplin to the latest version".

However, under https://github.com/laurent22/joplin/releases, the release marked "Latest release" (and the only one downloadable releases) is the version I'm on.

---

The file referenced in the error appears to be a diff, and references the note that I changed this morning. It seems a new feature (one that I personally don't need, since I keep my notes in a `git` repo) was introduced in the Android version, that hasn't yet made it to the desktop or terminal versions, and has now broken them.

**Comment by xenlo** [comment]
Hi, 
I got the same issue. But I assume that this happen to me because on my laptop, I use the Chocolatey to update my Joplin. And their (https://chocolatey.org/packages/joplin) the last version is still 1.0.143.
