### ISSUE TITLE
[Feature Request] search for a string in a word.

### ISSUE THREAD

**Issue by jeanantoine** [laurent22/joplin#1506]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

Searching for a string in a word can only be done when the word begins with the string:
search for "abc" in  "abcde"  can be done with the search pattern "abc*".
but I cannot search for "bcd" with search pattern "\**bcd**" or any sub-string of "abcde" if the sub-string does not begin with "a".
Such a search function is standard in every text editor/ note taking app and should be easy to add.
The search function in a note taking app is an important tool, and this request is needed when searching for proper nouns when you remember only a part of a name for example (not necessary the beginning).
You app is well made and very useful and I should be glad to have this function.

**Comment by laurent22** [comment]
There's no plan to support this at the moment.

**Comment by jeanantoine** [comment]
hope you can find some time in future , since it should be easy to implement ...

**Comment by laurent22** [comment]
One thing I've learnt in IT is never to assume that something is easy to implement, especially when I know nothing about the project.

In fact it's quite logical: what you described is an obvious feature so if it was easy to implement, it would already been done, wouldn't it? Or, if it's easy for you, you'd provide a pull request, right? But none of this is going to happen so surely there's something no so easy in there...

**Comment by jeanantoine** [comment]
Sorry for the late response, 
You are right saying that one should never assume that something is easy to implement (and I know nothing about the project nor I will provide a pull request), but you are right too saying that it is an obvious feature for a note taking app. I have since switched to Standard Notes with less futures for sure than your app, but I'm more confident that I can retrieve my notes (fuzzy or phonetics search à la google  would be even better)
C'est un peu dommage ...
