### ISSUE TITLE
[Feature Request] "Search in all the notes" should also include the note name

### ISSUE THREAD

**Issue by dionjwa** [laurent22/joplin#1509]
### Operating system

- macOS

### Application

- Desktop

Joplin for Desktop

Copyright © 2016-2019 Laurent Cozic
Joplin 1.0.143 (prod, darwin)

A note is named "xyz", but there is no "xyz" in the note content. Searching for "xyz" shows no results. This feels like an oversight?

**Comment by tessus** [comment]
Sorry, I can't reproduce this problem.

I just created a note called `xyz` with the text `Bla bla bla...`. When I search for xyz, the note shows up.

**Comment by laurent22** [comment]
Please provide the exact note title and exact search query (not "xyz"), as there might be something specific to your notes.

**Comment by dionjwa** [comment]
The note is here:

![image](https://user-images.githubusercontent.com/260221/57552102-ac18d600-731f-11e9-8f17-9bea2090e48f.png)

But doesn't show up with that search:
![image](https://user-images.githubusercontent.com/260221/57552089-a0c5aa80-731f-11e9-9fe7-2a850ef8ad13.png)

**Comment by tessus** [comment]
@dionjwa I don't understand what you are saying. the picture clearly states that it shows up in the search.

**Comment by tessus** [comment]
It looks like you cannot click on the note, because it is already open. What do you expect? The note shows up in the right part. What else do yoiu want? I really do not understand what you are saying.

**Comment by laurent22** [comment]
I don't understand either. You can clearly see in the screenshot that the note is there and even that "xyz" is highlighted in the title.

**Comment by tessus** [comment]
@dionjwa here you go:

![57552089-a0c5aa80-731f-11e9-9fe7-2a850ef8ad13](https://user-images.githubusercontent.com/223439/57565072-c507a280-7384-11e9-8ed8-2d450ac7db42.png)

**Comment by dionjwa** [comment]
Ok, you're right. I feel stupid. For whatever reason, I could not see what was in front of me. Maybe because the behaviour of the note list was different when the note is already open. In any case, yeah, it works. Ugh, sorry for the time waste.

**Comment by tessus** [comment]
@dionjwa don't worry, sometimes one can't see the forrest for the trees. It happens. I'm just glad that everything works...
