### ISSUE TITLE
[Feature Request] Don't require a title for notes, or use date/time instead of title

### ISSUE THREAD

**Issue by vpopescu** [laurent22/joplin#151]
Asking for a title for notes is a bit distracting. It would be nice if the "new note" would let me enter the node body, rather than ask for a title. Right now, every time I try to save a snippet of something, I have to rack my brain to give it a title. Google Keep does this, a "new note" focuses on the note body, with the title being optional.

I use apps such as these more like reminders of things I've seen. I just want to be able to paste a snippet into a text box, and have it indexed by date, so later on I can get a chronological list of my snippets. Similar to a ChangeLog organization, if you will.

### Operating system

- [x ] Windows
- [ ] macOS
- [ x] Linux
- [ ] Android
- [x ] iOS

### Application

- [x ] Desktop
- [ ] Mobile
- [ ] Terminal

---

**Comment by laurent22** [comment]
Yes this is actually partially implemented in the [better-new-note](https://github.com/laurent22/joplin/tree/better-new-note) branch. My plan is to get rid of the title prompt altogether and allow typing the note directly. The title will be, optionally, automatically populated based on the note body.

**Comment by vpopescu** [comment]
Great, will check it out. 

What I was trying to find is an app that looks somewhat like this Day One view: http://dayoneapp.com/wp-content/uploads/DayOne-1-Graphics-1.jpg. 

Maybe that would make a good view for the notes list, then I could collapse the note details, and just scroll and view my notes in that view (especially if it would show the full note). 

But I realize my needs are not everyone's needs. Some people love EverNote, I never got used to it, i find it messy. There is a strong need for this type of application, so thank you for the great work. 

Should I close this, if it's already in plan, or do you plan to keep it open until the "better" branch is released?

**Comment by jpetso** [comment]
I think a "diary" (or "log") feature like you request would be intriguing, but I also appreciate having notes that are not tagged by date. If I have a notebook with recipes, or research on a particular topic, or even just a near-term to-do list, then I'd find the date a distraction and would rather have it sorted organizationally, maybe with manual reordering.

How about making it a property of the notebook? In the Android app, there could be an extra "Sort by..." button next to "Search", which would pop up a menu with items "By date" and "Manually". For "By date", a note could have the date shown on its side, like in @vpopescu's picture of Day One. For "Manually", instead of the date you could show a (vertical triple-dot) drag handle to let the user reorder the items. In the title bar, you can regain the lost space by removing the "Back" button (i.e. no empty start page after the initial notebook has been created) and putting "New Notebook" into the app menu.

**Comment by Abijeet** [comment]
I would like to add to this discussion my request here - https://github.com/laurent22/joplin/issues/166

**Comment by laurent22** [comment]
This is done in the latest release - https://github.com/laurent22/joplin/releases/tag/v0.10.47

**Comment by vpopescu** [comment]
@jpetso I don't want to design the diary feature since I'm not the only customer, and I understand if my needs may not correspond to the goal of the project. But my ideal workflow would be something like this:

1. Click on tray icon, select "Add new note". A small interface pops up (not the full interface) where I can write my note. Click and close it. (btw, would be nice if this would also work on linux/gnome!).

2.  When I want to review my "diary" I can open the full app, where I have some sort of view where I see my history of all notes I added, as a chronological list, latest at top, with as little other fluff as possible, and no need to click on notes one by one to review them. (a pretty version of Emacs [ChangeLog](https://www.gnu.org/software/emacs/manual/html_node/emacs/Format-of-ChangeLog.html#Format-of-ChangeLog), basically)

Maybe a scripting/CLI interface would allow people to create the "add new note" and the "view journal" as external add-on, while using joplin as the engine. Then everyone could implement their own workflow. 
Something as simple as:

Add a note:
joplin --add-note "note data as whatever encoding"

Get diary:
joplin --get-all-notes  --order-by-date-desc

**Comment by laurent22** [comment]
@vpopescu, with the terminal app you can actually do more custom things. For example:

Add a note with title "my note" and body "note body":

    joplin mknote "my note"
    joplin set "my note" body "note body"

Get the last 10 notes by date:

    joplin ls --sort updated_time --reverse --limit 10

See command usage for the full list of commands and arguments: http://joplin.cozic.net/terminal/
