### ISSUE TITLE
Web Clipper images not loading

### ISSUE THREAD

**Issue by diver-down** [laurent22/joplin#1510]
### Operating system

- Linux (Ubuntu Studio)

### Application

- Brave Version 0.63.55 **Chromium: 74.0.3729.131** (Official Build) (64-bit)
- Web Clipper Version 1.0.13 (Chrome Web Store)

### Report:

When attempting to use the Web clipper on most web pages (I'm using the AV1 article on Wikipedia just as an example), images don't appear to load or save. In the attached screenshot, the problem can be seen in the preview window. 

Just in case the link is needed, the example webpage used is:  https://en.wikipedia.org/wiki/AV1

Thanks! :)

![Screenshot_2019-05-10_00-58-32](https://user-images.githubusercontent.com/35608185/57503772-a7243a00-72bf-11e9-8800-3201b536285a.png)

**Comment by laurent22** [comment]
When I try your page, the page gets imported correctly into Joplin, including the AV1 logo. The preview is not right though but it's more minor issue. Could you confirm that the page is imported correctly for you?
