### ISSUE TITLE
iOS sync: Single note isn't updated

### ISSUE THREAD

**Issue by bwrst** [laurent22/joplin#1511]
### Operating system

- iOS

### Application

- Mobile 10.0.31

I have a single note that isn't updated if I press `Synchronize` on the iOS client although there's a newer version on the sync target. The sync is shown as completed without errors, but that one pesky note is left in its old state. I tried force closing the app/rebooting the phone and doing it again, but the same thing happens.

If I make changes via the iOS client and synchronize, this modified old version is pushed to the sync target and overwrites the existing version (no conflict, just overwrite). If I make changes via the desktop client, these changes are once again ignored on iOS.

It's like the iOS client thinks this one note is always up-to-date, even if it isn't. My two desktop clients (Win/Linux) are happily updating each other's changes on this note. 

I use a WebDAV share on my own nginx server with encryption enabled.

My local timezone is **GMT+2 including DST**.

### Metadata after sync in the desktop client (1.0.145 prod win):
![meta-desktop-client-after-sync](https://user-images.githubusercontent.com/17462823/57540712-9d491800-734d-11e9-927c-e71ff4055e01.PNG)

### Metadata after sync on the WebDAV share:
[meta-webdav-share.txt](https://github.com/laurent22/joplin/files/3167399/meta-webdav-share.txt)

### Metadata after sync in the iOS client:
![meta-ios-client-after-sync](https://user-images.githubusercontent.com/17462823/57541658-cec2e300-734f-11e9-8f86-e1bf916898be.PNG)

### Sync log iOS client:
![ios-sync-log-1](https://user-images.githubusercontent.com/17462823/57540727-a508bc80-734d-11e9-8c64-12b99735fe34.png)
![ios-sync-log-2](https://user-images.githubusercontent.com/17462823/57540730-a639e980-734d-11e9-89c1-9460ee5474c5.png)

**Comment by Dasymi** [comment]
This looks like the same problem I reported here: https://discourse.joplinapp.org/t/data-loss/2305. I use WebDAV on a Synology NAS without encryption.

Since then it has happened once more.

**Comment by bwrst** [comment]
Yes, that seems to be the same problem. Sorry, I didn't see your report.

**Comment by laurent22** [comment]
Thanks for the detailed report @bwrst, I can see there's indeed something not right. The logic to sync a note is to look at the "sync_time" property of the note (the time when the item was last synced) and, if it's older than the "updated_time" property of the note on the sync target, it is updated locally.

This `sync_time` property is not visible above but you can get it by creating a debug report. You can get this by going to Config -> Show Advanced Options, then in the top right corner menu, press "Export debug report".

You can either post the whole report here or the lines relevant to this note (the ones with ID "8eade..."). If you could do this that would be great and it might help making sense of this issue.

My guess at this point is that iOS is doing some "smart" caching and giving and old version of the note instead of the new one, but since this bug is not so common I'm not sure.

**Comment by bwrst** [comment]
Sorry, I don't seem to have this menu entry, only `Log` and `Status` appear:

![IMG_3437](https://user-images.githubusercontent.com/17462823/57546489-20be3580-735d-11e9-92ff-70c5e015dfc0.PNG)

![IMG_3438](https://user-images.githubusercontent.com/17462823/57546494-21ef6280-735d-11e9-916a-4006d5880dca.PNG)
 
In `Status` there is no link like on the desktop version.

Output from the desktop client (not much help I guess):

    type,id,updated_time,sync_time,is_conflict
    1,8eadef8a87dd4bd08b7498780297c8e9,1557503273172,1557503273172,

**Comment by bwrst** [comment]
Follow-Up: The update to 10.0.32 didn't change anything at first &ndash; the note was still not updated.

I pulled the nginx logs to see if there was something wrong there, but Joplin only did the expected MKCOL, PROPFIND and a few GET commands for other notes.

However: After changing something in the note on one of the desktop clients, **the note was updated and appears to behave itself now**. This didn't work on the old version. Maybe the new history function shook something loose?

**Comment by laurent22** [comment]
> However: After changing something in the note on one of the desktop clients, **the note was updated and appears to behave itself now**. This didn't work on the old version. Maybe the new history function shook something loose?

It's hard to tell what the issue was exactly, but if it works now let's close the issue. Feel free to comment here if you get a similar issue.
