### ISSUE TITLE
[Bug] No syntax highlight in edit mode

### ISSUE THREAD

**Issue by noraj** [laurent22/joplin#1513]
### Issue

Syntax highlight works only for the render/preview mode not for the edit/editor mode.

![image](https://user-images.githubusercontent.com/16578570/57573138-ba501a80-7423-11e9-8017-7d10f20fc391.png)

This happens for both light and dark themes.

I tried with `php` and `ruby` which are very common languages.

By searching for old closed issues I found someone talkign about `javascript`.

So I tried a javascript code block and it works (but it is not even the same theme):

![image](https://user-images.githubusercontent.com/16578570/57573181-11ee8600-7424-11e9-8ba9-e3caed55d557.png)

Why only javascript has syntax highlight in edit mode?

### Idea

[highlightjs](https://highlightjs.org/) is a JavaScript syntax highlight lib that supports 185 languages and 89 styles. It is available for node.js.
By implementing it we would be able to have syntax highlight for tons of languages but also having tons of different themes.

### Operating system

Linux: ArchLinux (installed via the AUR package).

### Application

- Desktop

### Version

Joplin 1.0.145

**Comment by dayfuaim** [comment]
Confirm this issue in Joplin 1.0.182 (Mac OSX 10.10.5).

**Comment by innocuo** [comment]
Joplin uses Ace for the editor via react-ace, which depends on [brace](https://github.com/thlorenz/brace), which hasn't been updated for a while.

The markdown mode for Ace used to add syntax highlight only to js, xml, html and css, but it looks like they've updated that to use more languages. 

Unfortunately, Joplin won't get these updates until brace updates their version of Ace.

**Comment by noraj** [comment]
bump

**Comment by dayfuaim** [comment]
Still here (Ubuntu 18.04, Joplin 1.0.167).

**Comment by noraj** [comment]
Yeah let's close that I'm just using [VSCode](https://code.visualstudio.com/) + [Nested Tags](https://marketplace.visualstudio.com/items?itemName=vscode-nested-tags.vscode-nested-tags) now which has far better support for all of that and is not limited to note taking.
