### ISSUE TITLE
Android edit view placement - doesn't keep the cursor position in memory

### ISSUE THREAD

**Issue by shbach** [laurent22/joplin#1515]
### Operating system

- Android

### Application

- Mobile

In the Android app it would be useful if when the edit button is pressed the edit view would start in the currently viewed section instead of going to the bottom. This would make editing long notes at least somewhat more practical. Right now because this and [scrolling momentum](https://github.com/laurent22/joplin/issues/202) don't exist, editing long notes in the Android app is completely impractical.

**Comment by foxmask** [comment]
I thought joplin kept the cursor position in memory.
I have to admit that, with long text I entered, going back to half of the content to fix a typo, is not very fun.

**Comment by shbach** [comment]
> kept the cursor position in memory

That's a much better way of phrasing it... too bad I can't change the title anymore haha But yes, not very fun.
