### ISSUE TITLE
Bug in search system with long string

### ISSUE THREAD

**Issue by marcorighi** [laurent22/joplin#1516]
### Operating system

- Linux
Debian

### Application

- Desktop
xfce

**Comment by tessus** [comment]
Can you please be more specific? What is the bug? What happens? What are the steps to reproduce?

**Comment by marcorighi** [comment]
Sorry, my previous message has ben cut.

I have a note containing an IBAN  (a "bank address"). The IBAN is a long string.

In my case I have a note containing a string similar to

XY12F034501230000004567995

If I search the string "XY12F034501230000004567995" Joplin found the correct note.

If I use the 'query' "*4567995*" or the query "*4567995", Joplin do not found the note.

**Comment by laurent22** [comment]
Please see the search documentation, it works as expected.
