### ISSUE TITLE
IOS Sync. Error on file .md Unknown type: 13

### ISSUE THREAD

**Issue by SergeyShevelev** [laurent22/joplin#1517]
### Operating system

- iOS

### Application

- Mobile

### Symptoms

While syncing a desktop app (mac) and an IOS one I get an error (Unknown type: 13).
Both apps are uptodate. I guess the error has been started appearing since the desktop app update. More specifically I'm not able to sync a new task has been made in the desktop app.
I hope it helps.

![IMG_1722](https://user-images.githubusercontent.com/899820/57602882-5b98b700-7571-11e9-812a-69e27308fbfb.PNG)
![IMG_1723](https://user-images.githubusercontent.com/899820/57602883-5c314d80-7571-11e9-870b-2dfca0726f41.PNG)
![IMG_1724](https://user-images.githubusercontent.com/899820/57602884-5c314d80-7571-11e9-86ba-8ce1bd42e3a6.PNG)
![IMG_1725](https://user-images.githubusercontent.com/899820/57602885-5c314d80-7571-11e9-8529-67b1d1c6959f.PNG)

**Comment by mang-design** [comment]
I am also getting this error on Ubuntu 18.04.2
Joplin Version: 1.0.127

`Completed: 13/05/2019 12:46
Last error: Error: On file xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.md: Unknown type: 13`

**Comment by schemen** [comment]
I also get that issue on iOS on newly created notes.

**Comment by donaldtone** [comment]
Just wait for the ios version update to be compatible with history function.

**Comment by Dasymi** [comment]
Hurray! Updated Joplin is on the App Store now.

**Comment by SergeyShevelev** [comment]
Excellent! It is fixe :)
