### ISSUE TITLE
Error "Error: Error: ENOENT ... " Android

### ISSUE THREAD

**Issue by mang-design** [laurent22/joplin#1519]
### Operating system

- Android (8.1.0)

### Application

- Mobile (1.0.251, Database v21)

Screenshot of error:

![joplin_error- 05 13 2019](https://user-images.githubusercontent.com/38485786/57617114-424b3700-7580-11e9-878c-b8895f832f02.png)

I know that particular file does not exist because I checked, that's fine - however, is there any way to resolve the error so it doesn't show up every time I sync?

### Actions taken prior to receiving error

- Reverted phone to factory settings (complete wipe)
- Restored backup of phone

**Comment by laurent22** [comment]
Normally, the app only tries to access files that can be listed so is this file definitely not present? Can you post the log before this message happens?

**Comment by foxmask** [comment]
can you try last version 1.0.252 ?

**Comment by mang-design** [comment]
> can you try last version 1.0.252 ?

Same error on 1.0.252

**Comment by mang-design** [comment]
> Normally, the app only tries to access files that can be listed so is this file definitely not present? Can you post the log before this message happens?

I modified the note that I thought may have been causing the problem, in order for the app to generate a new name, but now I'm getting this error

![joplin_error-2- 05 13 2019](https://user-images.githubusercontent.com/38485786/57619601-8c371b80-7586-11e9-84a0-5bc587b4010e.png)

**Comment by laurent22** [comment]
That error means aecda....md exists on the sync target but its content is empty.

**Comment by mang-design** [comment]
> That error means aecda....md exists on the sync target but its content is empty.

It's 2.06kB.

**Comment by laurent22** [comment]
Maybe some permission issue then. The app first gets the metadata of a file (size, etc.) then it gets the content. In your case, it can get the metadata, but then it gets empty content, which I'm not sure why.

**Comment by mang-design** [comment]
> Maybe some permission issue then. The app first gets the metadata of a file (size, etc.) then it gets the content. In your case, it can get the metadata, but then it gets empty content, which I'm not sure why.

Okay, after trying a bunch of things I think I have resolved it.

### Things I tried that didn't work
- Formatting the SD card with my phone
- Deleting suspected notes (not sure how to find the notes by the .md title)
- Changing the syncing location from 'File system' to Dropbox (still gave the same errors - was getting errors on both Android and Linux -- big clue here)

### WHAT WORKED
- Updating both Android AND Linux client (to 1.0.151)
- Syncing on the Linux client first (was seemingly the weakest link at version 1.0.127) -- no error
- Sync'd on Android -- no error

So, the lesson - make sure everything is up-to-date! Should have done this before adding an issue, but I thought it was updated using the script.

**Comment by laurent22** [comment]
Ok, glad this is fixed, but it's not clear to me why this was happening as it didn't seem related to the recent update.

**Comment by Lennox-Elaphurus** [comment]
I had the same issue. Your story reminds me that I changed the permission of Joplin on my phone recently. The problem was solved after I grant it the permission "Access and change files on internal storage".
