### ISSUE TITLE
Revision history list date format isn't granular enough

### ISSUE THREAD

**Issue by mgrandi** [laurent22/joplin#1522]
when in the revision history screen, the date of the revisions that are available seems to be only down to the minute, but for me at least, i have at least one note with two revisions within the same minute (is that because i keep hitting ctrl+s to sync?)

i feel like editing the date format to also have seconds would be a good enough compromise

<img width="332" alt="screenshot_1278" src="https://user-images.githubusercontent.com/802786/57712897-4af64880-7626-11e9-8671-4f5f5741fc7a.png">

**Comment by laurent22** [comment]
Normally there's only at most one revision every 10 minutes (unless one change was made on one device and the other on another within less than 10 min) so displaying seconds shouldn't be necessary.

I see that some of my notes have this problem too though, so I'm going to add more logging to understand what's going on.

**Comment by mgrandi** [comment]
did you determine this was a result of the phone app editing the note and adding a revision entry?

**Comment by laurent22** [comment]
Not yet but it's on my list.
