### ISSUE TITLE
Linux command not rendered correctly

### ISSUE THREAD

**Issue by Shamp0o** [laurent22/joplin#1523]
### Application
- Desktop

The pipe to bash in the wget command (Linux desktop version) is missing in README.md. It should say 
`wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash`
but instead it says
`wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh

The syntax seems to be correct though.

**Comment by laurent22** [comment]
Fixed in c546b7076a40108834506d22d0931a54a263c6bd
