### ISSUE TITLE
[Feature request] Export to odt / Libreoffice format

### ISSUE THREAD

**Issue by JFMALBI** [laurent22/joplin#1525]
### Operating system

- Windows
- Linux
- Android

### Application

- Desktop
- Mobile

First of all, thanks for the job !!
I use Joplin with NextCloud between Mobile (Android) and Desktops (Linux/Windows) in a professional environment. It wouldbe great to export notes in ODT format which is the format we use in our company for office documents

**Comment by Stele77** [comment]
Would be great indeed, but this could be solved with the Pandoc support that has already been proposed on discourse and here on Github so please vote for it too: 
#1167 
https://discourse.joplinapp.org/t/feature-request-pandoc-markdown-with-preview-and-export/1471/4
