### ISSUE TITLE
Can't clip local files anymore

### ISSUE THREAD

**Issue by bwrst** [laurent22/joplin#1526]
### Operating system

- Windows
- Linux

### Application

- Web Clipper 1.0.14 / Firefox 66.0.5

The Clipper is broken for **local** pages (file://). It worked before.

![error](https://user-images.githubusercontent.com/17462823/57803028-aecc5e80-7757-11e9-9d53-fc27ba905816.png)

I think it's because of [this commit](https://github.com/laurent22/joplin/commit/34323042d5b0f990c43b6d8abc431fcf48c697e4#diff-df1f209bcaf06622ab44cbc68d7ca4ff). It introduces the use of `location.origin`. For local files on my version of Firefox this property returns `null`.

You can see the bug via the **Clip URL** preview:
![null](https://user-images.githubusercontent.com/17462823/57803027-ad9b3180-7757-11e9-84bc-05e1bc68d635.png)

.

**Comment by ckaemper** [comment]
In Chrome the clipper won't even load. I see the following message.

> The Joplin extension is not available on this tab due to: tabsExecuteScript: Cannot load {"file":"/content_scripts/JSDOMParser.js"}: Cannot access contents of url "file:///C:/Users/user/AppData/Local/Temp/filename.html". Extension manifest must request permission to access this host.

- Windows 7
- Chrome Version 74.0.3729.157 (64-Bit)
- Joplin Web Clipper 1.0.14

**Comment by tessus** [comment]
Actually I was not able to reproduce this. I just opened a local html file and clipped it without a problem.
I'm using Firefox 67.0 and Clipper 1.0.14.

**Comment by bwrst** [comment]
Thanks for looking into this! To confirm I just did the following:

1. Created a fresh profile in Firefox (now 67.0/Linux) and changed no settings.
2. Installed Web Clipper from addons.mozilla.org (1.0.14).
3. Opened a HTML file from the desktop.

Result: None of the clip commands work. The error message is the same from the original report.

It doesn't seem to depend on the content of the file. I get this result even on a very simple test file like this:
```
<html>
<head>
<title>Bla</title>
<body>
<h1>Hi</h1>
</body>
</html>
```

**Comment by tessus** [comment]
Just tried your html file and it works for me. I'm on macOS though, but there is no difference in the clipper code, so I don't understand what is going on.

**Comment by ckaemper** [comment]
In Chrome I was able to get the clipper working with local files by explicitly allowing access to file urls in the Chrome extension manager.
