### ISSUE TITLE
Sync status unexpected numbers

### ISSUE THREAD

**Issue by q-wertz** [laurent22/joplin#1528]
### Operating system
- Linux

### Application
- Desktop v1.0.142

### Description
Not sure if this is a bug or a feature. 
As you can see on the screenshot ![Screenshot](https://user-images.githubusercontent.com/20948931/57852938-c56cc700-77e4-11e9-9b5d-e9173d44be89.png) the sync status (synced items / total items) shows an unexpected behavior.
Also under Folders only two are listed, so why does it show 3 folders as synchronized?

**Comment by q-wertz** [comment]
I think the origin somehow comes from the deleted notes:
- Look into Sync status -> e.g. Note 47/33 
- Make a new note and sync -> Note 47/34
- Delete note -> Note 48/33

I think there is an error in the calculation of the number of synced items...
It probably should be 33/33 -> 34/34 -> 33/33

**Comment by foxmask** [comment]
When you leave Joplin , and clean it's presence from the application list of your android, then come back to joplin, are the counters still wrong ?

**Comment by q-wertz** [comment]
I only have the bug in the Linux Client.
On Windows everything seems fine and in the Android app I don't even find the menu for the sync status.

**Comment by q-wertz** [comment]
Updated today on Linux and in v1.0.160 on Linux the problem is still persistent...

**Comment by q-wertz** [comment]
Checked it, now it looks good.
Still on v1.0.160 but works now. Don't know why.
