### ISSUE TITLE
Back button does not return to last viewed note on mobile

### ISSUE THREAD

**Issue by schemen** [laurent22/joplin#1529]
### Operating system

- Android (?)
- iOS

### Application

- Mobile

Pressing the back button does not return to the previous note when following a link to another note.
I think this is the code section, sadly I can't do JS.
https://github.com/laurent22/joplin/blob/e2a64e21a2432b64270eac175a044f4f74d5d3f6/ElectronClient/app/gui/NoteText.jsx#L1399

If I understand it right, this should return yourself to the last note viewed when clicked. On iOS I get returned to the folder view of the last note viewed, not the note itself.
This is working fine on desktop, thus I believe this might be a bug, somewhere.

Cheers!

**Comment by schemen** [comment]
Can maybe someone confirm this occurence on Android?

**Comment by Dasymi** [comment]
I can confirm that’s the way it works in IOS. Can’t confirm on Android as links have stopped working completely in latest version. I’ll mention it on the forum.
