### ISSUE TITLE
Cannot configure sync on headless machine

### ISSUE THREAD

**Issue by duckpuppy** [laurent22/joplin#153]
### Operating system

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [X] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---

In order to configure sync you have to visit a URL which will redirect you to the login page for Microsoft and, upon successful authentication, will redirect back to a localhost callback URL (typical OAuth flow).  The problem is that if I'm running a terminal version of joplin, it will potentially be because there's no graphical interface available (running over SSH, etc.).  There's no way to configure sync.

It's possible to connect to the URL from another machine (`<machine-ip>:<port>/auth`) and complete the login, but obviously the callback isn't going to work then as the redirect will always be to localhost.

It might be possible to construct the callback URL from the request headers such that it can redirect to the host used in the initial connection (the `<host>:<port>/auth` connection).  Could that be a way to make this work?

**Comment by laurent22** [comment]
The auth token can be manually set using `joplin config sync.3.auth <TOKEN_VALUE>`. I'm not sure if you can get this token directly from OneDrive and copy and paste it there. Alternatively, you might be able to generate it on a machine where you have a browser and then copy it in your ssh machine.

You would do something like this:

- Run `joplin sync` to setup the OneDrive synchronisation
- Type `joplin config sync.3.auth` to get the token
- Copy the part after `sync.3.auth =` and paste it in your SSH session as `joplin config sync.3.auth <TOKEN_VALUE>`
- Try to sync from your ssh machine to see if it works

I assume tokens are not tied to a particular machine so hopefully it should work.

**Comment by duckpuppy** [comment]
I was able to get things working by simply copying the `.config/joplin` folder from another machine.  I think I may have broken something else, though - I've filed a new bug.
