### ISSUE TITLE
Feature Request Please add tags list to Windows Desktop

### ISSUE THREAD

**Issue by whisperdancer** [laurent22/joplin#1535]
The Android app has a very elegant interface for adding tags to notes. One can select existing tag(s) or create new one. Please add this functionality to the Win Desktop. I often find myself adding duplicate tags using Windows because I forgot I had already added a similar tag. So I end up with many similar tags. 

Thank you.

**Comment by Dasymi** [comment]
Yes, usually desktop apps have a better UI than mobile ones; in this case Joplin could do better.

**Comment by christianlupus** [comment]
I think the same holds true for the Linux client where I am more intersted but still....
