### ISSUE TITLE
Orphaned Note

### ISSUE THREAD

**Issue by pconrad-fb** [laurent22/joplin#1536]
### Operating system

- Windows

### Application

- Desktop

**Comment by pconrad-fb** [comment]
Seems to be related to maybe an unresolved diff between notes? I'm also getting an "unknown type: 13" error on a .md file with the following contents:

id: 303737d3aa824537bd831aef9257f670
parent_id: 
item_type: 1
item_id: cc5831cd16ea43e4b15d51e2076cc70c
item_updated_time: 1557800081884
title_diff: "@@ -0,0 +1,21 @@\n+Fleet Fuel Management\n"
body_diff: "@@ -0,0 +1,4408 @@\n+https://www.lytx.com/en-us/fleet-services/program-enhancements/fleet-fuel-reporting%0A%0ALytx identifies the impact of driver and vehicle factors on fuel consumption to help you curb gas-guzzling behaviors and optimize every vehicle%E2%80%99s fuel potential. With fuel reporting, you can:%0A%0A- Identify and improve inefficient drivers%0A- Find inefficient vehicles%0A- Reduce fleet fuel consumption and annual fuel costs%0A- Access important vehicle data automatically%0A%0A### Pinpoint the True Cause of Fuel Inefficiency in Your Fleet%0A%0AAggressive driving, inefficient vehicles, and idle time are just some of the many factors that could be impacting your fleet%E2%80%99s fuel consumption%E2%80%94and your bottom line. Most fleet fuel management solutions only track behaviors; Lytx provides a robust, report-based solution that tracks both driver behavior and vehicle MPG performance.%0A%0AFuel reporting with Lytx gives you a data-driven, objective view of what%E2%80%99s causing excess fuel consumption in your fleet, and has proven to help reduce fleet fuel consumption and increase fuel efficiency by up to 12%25.%0A%0A### Know Where to Focus, Thanks to Robust Reporting%0A%0AAdvanced reporting distills dozens of distinct data readings to help you quickly pinpoint and correct the cause of excess fuel consumption. When driver performance is a factor, you%E2%80%99ll know which drivers and which behaviors require coaching. When a vehicle is using more fuel than it should, you can bring it in for a closer look and possibly intervene before costly repairs are needed.%0A%0A### Simplify Data Capture with ECM Connection%0A%0AWith Lytx, you can remove the time-intensive manual process of collecting mileage data. By connecting directly to your vehicle%E2%80%99s engine control module (ECM) data is automatically uploaded to your Lytx account for simple and easy access.%0A%0A### Focus on Inefficient Drivers%0A%0AUse Lytx to focus on your most inefficient drivers. Then, drill down to identify and correct the specific driving behaviors that are contributing to excess fuel consumption.%0A%0A### Monitor Inefficient Vehicles%0A%0ATo get the most out of each vehicle%E2%80%99s fuel economy, pinpoint which vehicles are using the most fuel. Track fuel consumption by vehicle and compare your vehicles with similar vehicles that Lytx tracks in other fleets. Benchmark poor-performing vehicles to decide which to bring in for maintenance.%0A%0A### Use ECM and GPS-Based Solutions%0A%0AConnect directly to your vehicles%E2%80%99 engine control module (ECM) to track driving behaviors and collect vehicle readings. Use this option to quickly identify inefficient vehicles and repair them before they become costly problems. Built-in GPS and accelerometer systems combine to determine vehicle MPG.%0A%0A%3E%E2%80%9CI wanted a holistic driver risk management solution that offered more than just training. The DriveCam program enables DS Waters to reinforce the safe driving habits we have instilled in our drivers and make them stick.%E2%80%9D%0A&mdash;Michael Belcher, Director of Safety, DS Waters%0A%0Ahttps://resources.lytx.com/topic-reduce-costs/7-fuel-saving-tips%0A%0AThe Lytx Fuel Score%E2%84%A2 provides a snapshot of one of the key factors that impacts fuel performance %E2%80%93 driver behavior. Assessing multiple behavior categories, a driver%E2%80%99s fuel score helps you identify driving habits that consume excess fuel and opportunities to enhance fuel efficiency. Use the following tips to educate your drivers on ways to save fuel and improve their fuel scores.%0A%0AA typical heavy-duty engine burns about 0.8 gallons of fuel per hour. Turn off your engine whenever your vehicle is parked. Restarting your vehicle uses much less fuel (only about 10 seconds%E2%80%99 worth at idle) than letting the engine run.%0A%0ARegularly accelerating hard enough to trigger the g-force sensors indicates wasteful jump-starts or speed changes. %0A%0AHard acceleration consumes excess fuel without getting you to your destination any faster. When starting your vehicle from a parked or idling position, give yourself enough time and space to gain speed slowly. As you accelerate, avoid shaking your vehicle back and forth.%0A%0AIf you are already driving and need to gain speed, make sure to look ahead and plan accordingly. It is best to avoid accelerating when nearing an intersection or if there isn%E2%80%99t enough room to pass someone with even acceleration%0A%0ARegularly braking hard enough to trigger the g-force sensors indicates wasteful last-minute stops.%0A%0Ahttps://www.wexinc.com/solutions/fleet-management/%0A%0A\n"
metadata_diff: {"new":{"id":"cc5831cd16ea43e4b15d51e2076cc70c","parent_id":"6e65d0628a9c4a43906c22812e5ef6c3","latitude":"37.33820000","longitude":"-121.88600000","altitude":"0.0000","author":"","source_url":"","is_todo":0,"todo_due":0,"todo_completed":0,"source":"joplin-desktop","source_application":"net.cozic.joplin-desktop","application_data":"","order":0},"deleted":[]}
encryption_cipher_text: 
encryption_applied: 0
updated_time: 2019-05-14T02:14:57.677Z
created_time: 2019-05-14T02:14:57.677Z
type_: 13

**Comment by tessus** [comment]
`unknown type 13` means that you use several versions of Joplin and the one where you receive this error is still an older version that does not have the "note history" feature.

**Comment by pconrad-fb** [comment]
But the result was a note that disappeared. If I upgrade, will the note come back?

**Comment by tessus** [comment]
I'm glad that you got your note back.

Adding info to the FAQ is always a good idea. However, I believe that this special case only manifested itself when the note history code was added.
The `unknown type 13` error came up a few times in the forum, but I think Laurent already changed the message to something more specific (e.g. Joplin has to be upgraded).

**Comment by tessus** [comment]
I think your problem is resolved thus we can close this issue. If not, let me know and I will re-open it.
