### ISSUE TITLE
Joplin Data

### ISSUE THREAD

**Issue by fostercoburn** [laurent22/joplin#1538]
### Operating system

- Windows

### Application

- Desktop

I had Windows go bad. I have all files from the .config folder and have copied them into a new Windows installation. But they are not showing up in Joplin. What is the easiest way for a NON-PROGRAMMER to load the data file again?

**Comment by tessus** [comment]
This question would be better for the forum.

But copying your profile folder is all that is needed. The folder contains the database, which holds the notes and the resource folder that holds the attachments.
The easiest way is to export your notes to .jex format and then import them again.

**Comment by tessus** [comment]
Were you able to get it working?

Maybe you copied it to the wrong folder or there are permission errors where Joplin can't access the folder. So unless your database went bad (as the rest of your Windows) this will work.

**Comment by fostercoburn** [comment]
Unfortunately it has not worked for me. The issues with Windows are completely unrelated so I'm not concerned that the data was bad and I've moved the entire folder to another computer. Looking at the file with a text editor (don't worry, no saving) shows the data is still there. Just crazy jumbled and unusable. Given that I have the data files, I just wish there was an easy way to import them. Then I'll turn on Sync so I don't have to worry about it in the future.

**Comment by tessus** [comment]
Which file. The `database.sqlite` file? There are GUI apps to inspect sqlite files, or you could use the sqlite command line tool, although not sure if that's available on Windows.

Anyway, if the database file is intact you have to be able to get it back. I know that this works, so I'm not sure why it's not workin g in your case.
Maybe @laurent22 has additional info.

**Comment by laurent22** [comment]
If no note or notebook is showing up, then there's probably no data in the database either. Can't really say for sure without opening the db and checking though. Can you open it with an SQLite database browser and check if there's something in the "notes" table?

**Comment by fostercoburn** [comment]
Remember, I am not a programmer or a database expert. Just a frustrated end user. So editing a SQL database (or even looking at it) is not my thing.

Again, ALL DATA IS INTACT on the machine that I had to reinstall Windows. I installed Joplin on a different computer. I copied the entire joplin-desktop folder and yet the new install shows the "default" note. I have a perfectly good data file, how do I get it into Joplin?

**Comment by fostercoburn** [comment]
I have successfully recovered the data and have synchronized with Dropbox so this won't be an issue in the future.

**Comment by tessus** [comment]
So what was the problem? Wrong location? Wrong permissions?

Next time please post usability questions in the forum. This might help others as well. (People never search for closed topics on github.)

**Comment by fostercoburn** [comment]
If there is a forum, I have no clue where to find it. I simply followed a link on the Web site and got here.

As I've said earlier, there was zero doubt about location, permissions and viability of data. A reboot did the trick, but I have no idea why.

**Comment by tessus** [comment]
You probably didn't close Joplin, but only closed the window.

The forum link is on the main joplin web site, right at the top, but here it is: https://discourse.joplinapp.org/

**Comment by laurent22** [comment]
There's some link to update somewhere I guess, because support should indeed not be on the GitHub issue tracker.
