### ISSUE TITLE
Mobile - App crashes within 5s (Android)

### ISSUE THREAD

**Issue by jemag** [laurent22/joplin#1540]
### Operating system
- Android

### Application

- Mobile

### Description

App crashes within 5 sec after opening it. I was able to receive all my synced notes from dropbox and provide the master password for the decryption. About midway through decrypting the notes, the app crashed. Now, if I open the app, it will crash within approximately 5 seconds.

I have sent the low level bug report to your email with the issue number in subject. Unfortunately, I cannot access the advanced options for the logs as the app crashes too quickly.

Let me know if I can do anything more.

**Comment by jemag** [comment]
First error was on oneplus 3T device. Similar error has been replicated on Xiaomi Mi pad 4 (app crashes within 5 sec).

However, Joplin seems to be working fine on both my Windows 10 machine, as well as my Arch Linux one.

**Comment by tessus** [comment]
I don't even know, if @laurent22 received your log file, so it's hard to comment on this problem. It always makes sense to provide some basic information when opening an issue:

- version of Joplin
- version of Android
- debug log

Currently this issue has none of that info.

**Comment by jemag** [comment]
Version is the latest from the google play store, 1.0.252 according to the  App Info.

As mentioned, the problem occurs on both my mobiles device. I doubt the android version will be of any impact but here goes:
OnePlus3T: Android 9 through Lineage 16.0 (lineage-16.0-20190517-nightly-oneplus3)
Xiaomi mi pad 4: Android 8.1.0 through MIUI 10.3.1.0 (ODJCNXM)

For the applications logs, so far I have not been successful in accessing them before the application crashes and I would rather not post publicly the detailed android report, since it may contain more private information.

I will try accessing the logs again a few more times tonight, see if my fingers can become quicker than the crash. Unless you know another way to access them?

**Comment by jemag** [comment]
Tried a couple more times tonight, this time I was able to catch a screenshot of the status and get a sync report:
![image](https://user-images.githubusercontent.com/7985687/58139990-d4140d80-7c2c-11e9-9321-25007022daf1.png)
[syncReport-1558474182259.txt](https://github.com/laurent22/joplin/files/3205097/syncReport-1558474182259.txt)

**Comment by laurent22** [comment]
@jemag, I think I got your crash log but it's hard to make sense of because I don't know at what point the crash occurred. If you could send them again and tell me at what point (minutes and seconds) the crash happened, I might be able to find it.

Alternatively, the best way would be if you could install adb: https://www.xda-developers.com/install-adb-windows-macos-linux/

Then, enable developer mode in Android. Plug the Android phone to your computer. And on your computer (Linux, macOs or Windows), type `adb logcat`. Now replicate the crash in Joplin. As soon as it happens, stop adb (Ctrl+C). And finally, post here the last few lines as they should tell us exactly what happened.

**Comment by jemag** [comment]
Hi, did the logging with `adb logcat`. Seems there is perhaps a resource not closing properly and the application goes into OOM.

Logs:

>  I ReactNativeJS: OPEN database: joplin.sqlite
05-22 19:34:43.702  2221  2258 I QcrilOemhookMsgTunnel: [0]processOemHookIndication length=22
05-22 19:34:43.754  2066  2066 D ServiceStateProvider: subId=1
05-22 19:34:44.174 23841 23886 I WebViewFactory: Loading com.android.webview version 72.0.3626.121 (code 362612150)
05-22 19:34:44.219 23841 23886 I cr_LibraryLoader: Time to load native libraries: 2 ms (timestamps 897-899)
05-22 19:34:44.226 23841 23886 I chromium: [INFO:library_loader_hooks.cc(42)] Chromium logging enabled: level = 0, default verbosity = 0
05-22 19:34:44.226 23841 23886 I cr_LibraryLoader: Expected native library version number "72.0.3626.121", actual native library version number "72.0.3626.121"
05-22 19:34:46.681 23841 23850 W System  : A resource failed to call close.
05-22 19:34:49.502 23841 23850 I chatty  : uid=10118(net.cozic.joplin) FinalizerDaemon identical 101 lines
05-22 19:34:49.502 23841 23850 W System  : A resource failed to call close.
05-22 19:34:50.843 23841 23866 W System.err: java.lang.Exception: File does not exist
05-22 19:34:50.843 23841 23866 W System.err:    at com.rnfs.RNFSManager.unlink(RNFSManager.java:559)
05-22 19:34:50.843 23841 23866 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
05-22 19:34:50.843 23841 23866 W System.err:    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
05-22 19:34:50.843 23841 23866 W System.err:    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
05-22 19:34:50.843 23841 23866 W System.err:    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-22 19:34:50.843 23841 23866 W System.err:    at android.os.Handler.handleCallback(Handler.java:873)
05-22 19:34:50.843 23841 23866 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
05-22 19:34:50.843 23841 23866 W System.err:    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
05-22 19:34:50.843 23841 23866 W System.err:    at android.os.Looper.loop(Looper.java:193)
05-22 19:34:50.843 23841 23866 W System.err:    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
05-22 19:34:50.843 23841 23866 W System.err:    at java.lang.Thread.run(Thread.java:764)
05-22 19:34:50.903 23841 23850 W System  : A resource failed to call close.
05-22 19:34:50.909 23841 23850 I chatty  : uid=10118(net.cozic.joplin) FinalizerDaemon identical 33 lines
05-22 19:34:50.909 23841 23850 W System  : A resource failed to call close.
05-22 19:34:51.205 20801 20866 I WorkerManager: dispose()
05-22 19:34:51.207 20801 20866 W ThreadPoolDumper: Queue length for executor EventBus is now 11. Perhaps some tasks are too long, or the pool is too small.
05-22 19:34:52.262 23841 23850 W System  : A resource failed to call close.
05-22 19:34:52.406 23841 23850 I chatty  : uid=10118(net.cozic.joplin) FinalizerDaemon identical 34 lines
05-22 19:34:52.407 23841 23850 W System  : A resource failed to call close.
05-22 19:34:52.733 23841 23909 I et.cozic.jopli: Waiting for a blocking GC Alloc
05-22 19:34:52.778 23841 23852 I et.cozic.jopli: Background concurrent copying GC freed 7245(562KB) AllocSpace objects, 5(120KB) LOS objects, 10% free, 211MB/235MB, paused 55.509ms total 203.237ms
05-22 19:34:52.778 23841 23850 W System  : A resource failed to call close.
05-22 19:34:52.779 23841 23850 I chatty  : uid=10118(net.cozic.joplin) FinalizerDaemon identical 6 lines
05-22 19:34:52.779 23841 23850 W System  : A resource failed to call close.
05-22 19:34:52.779 23841 23909 I et.cozic.jopli: WaitForGcToComplete blocked Alloc on HeapTrim for 46.869ms
05-22 19:34:52.779 23841 23909 I et.cozic.jopli: Starting a blocking GC Alloc
05-22 19:34:52.780 23841 23909 I et.cozic.jopli: Starting a blocking GC Alloc
05-22 19:34:52.780 23841 23850 W System  : A resource failed to call close.
05-22 19:34:52.780 23841 23850 W System  : A resource failed to call close.
05-22 19:34:52.806 23841 23909 I et.cozic.jopli: Alloc concurrent copying GC freed 904(135KB) AllocSpace objects, 1(24KB) LOS objects, 10% free, 211MB/235MB, paused 71us total 25.965ms
05-22 19:34:52.806 23841 23909 I et.cozic.jopli: Starting a blocking GC Alloc
05-22 19:34:52.806 23841 23850 W System  : A resource failed to call close.
05-22 19:34:52.806 23841 23850 W System  : A resource failed to call close.
05-22 19:34:52.830 23841 23909 I et.cozic.jopli: Alloc concurrent copying GC freed 111(33KB) AllocSpace objects, 0(0B) LOS objects, 10% free, 211MB/235MB, paused 60us total 23.650ms
05-22 19:34:52.830 23841 23909 I et.cozic.jopli: Forcing collection of SoftReferences for 55MB allocation
05-22 19:34:52.830 23841 23909 I et.cozic.jopli: Starting a blocking GC Alloc
05-22 19:34:52.862 23841 23909 I et.cozic.jopli: Alloc concurrent copying GC freed 3664(223KB) AllocSpace objects, 0(0B) LOS objects, 10% free, 211MB/235MB, paused 62us total 32.262ms
05-22 19:34:52.862 23841 23909 W et.cozic.jopli: Throwing OutOfMemoryError "Failed to allocate a 58425200 byte allocation with 25165824 free bytes and 44MB until OOM, max allowed footprint 246762192, growth limit 268435456"
05-22 19:34:52.863 23841 23909 I et.cozic.jopli: Starting a blocking GC Alloc
05-22 19:34:52.863 23841 23909 I et.cozic.jopli: Starting a blocking GC Alloc
05-22 19:34:52.864 23841 23850 W System  : A resource failed to call close.
05-22 19:34:52.885 23841 23909 I et.cozic.jopli: Alloc concurrent copying GC freed 561(96KB) AllocSpace objects, 1(24KB) LOS objects, 10% free, 211MB/235MB, paused 55us total 22.263ms
05-22 19:34:52.885 23841 23850 W System  : A resource failed to call close.
05-22 19:34:52.885 23841 23909 I et.cozic.jopli: Starting a blocking GC Alloc
05-22 19:34:52.909 23841 23909 I et.cozic.jopli: Alloc concurrent copying GC freed 138(51KB) AllocSpace objects, 0(0B) LOS objects, 10% free, 211MB/235MB, paused 95us total 23.682ms
05-22 19:34:52.909 23841 23909 I et.cozic.jopli: Forcing collection of SoftReferences for 55MB allocation
05-22 19:34:52.909 23841 23909 I et.cozic.jopli: Starting a blocking GC Alloc
05-22 19:34:52.939 23841 23909 I et.cozic.jopli: Alloc concurrent copying GC freed 655(94KB) AllocSpace objects, 0(0B) LOS objects, 10% free, 211MB/235MB, paused 57us total 29.682ms
05-22 19:34:52.939 23841 23909 W et.cozic.jopli: Throwing OutOfMemoryError "Failed to allocate a 58425200 byte allocation with 25165824 free bytes and 44MB until OOM, max allowed footprint 246760168, growth limit 268435456"
05-22 19:34:52.940 23841 23850 W System  : A resource failed to call close.
05-22 19:34:52.940 23841 23909 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
05-22 19:34:52.940 23841 23909 E AndroidRuntime: Process: net.cozic.joplin, PID: 23841
05-22 19:34:52.940 23841 23909 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 58425200 byte allocation with 25165824 free bytes and 44MB until OOM, max allowed footprint 246760168, growth limit 268435456
05-22 19:34:52.940 23841 23909 E AndroidRuntime:        at java.lang.StringFactory.newStringFromChars(StringFactory.java:267)
05-22 19:34:52.940 23841 23909 E AndroidRuntime:        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:252)
05-22 19:34:52.940 23841 23909 E AndroidRuntime:        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:65)
05-22 19:34:52.940 23841 23909 E AndroidRuntime:        at android.util.Base64.encodeToString(Base64.java:456)
05-22 19:34:52.940 23841 23909 E AndroidRuntime:        at com.RNFetchBlob.RNFetchBlobFS.readFile(RNFetchBlobFS.java:199)
05-22 19:34:52.940 23841 23909 E AndroidRuntime:        at com.RNFetchBlob.RNFetchBlob$6.run(RNFetchBlob.java:226)
05-22 19:34:52.940 23841 23909 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-22 19:34:52.940 23841 23909 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-22 19:34:52.940 23841 23909 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
05-22 19:34:52.943  1028  2894 W ActivityManager:   Force finishing activity net.cozic.joplin/.MainActivity
05-22 19:34:52.950 23841 23909 I Process : Sending signal. PID: 23841 SIG: 9
05-22 19:34:52.954  1028  1176 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
05-22 19:34:52.954  1028  1176 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
05-22 19:34:52.956   570   570 E lowmemorykiller: Error writing /proc/23841/oom_score_adj; errno=22
05-22 19:34:53.011  1028  3889 I ActivityManager: Process net.cozic.joplin (pid 23841) has died: vis  +99TOP
05-22 19:34:53.011  1028  1683 W InputDispatcher: channel 'b8efb20 net.cozic.joplin/net.cozic.joplin.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
05-22 19:34:53.011  1028  1683 E InputDispatcher: channel 'b8efb20 net.cozic.joplin/net.cozic.joplin.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
05-22 19:34:53.013  1028  1990 I WindowManager: WIN DEATH: Window{b8efb20 u0 net.cozic.joplin/net.cozic.joplin.MainActivity}
05-22 19:34:53.013  1028  1179 W libprocessgroup: kill(-23841, 9) failed: No such process
05-22 19:34:53.013  1028  1990 W InputDispatcher: Attempted to unregister already unregistered input channel 'b8efb20 net.cozic.joplin/net.cozic.joplin.MainActivity (server)'
05-22 19:34:53.020   573   629 W SurfaceFlinger: Attempting to set client state on removed layer: net.cozic.joplin/net.cozic.joplin.MainActivity#0
05-22 19:34:53.021   573   629 W SurfaceFlinger: Attempting to destroy on removed layer: net.cozic.joplin/net.cozic.joplin.MainActivity#0
05-22 19:34:53.054   461   461 I Zygote  : Process 23841 exited due to signal (9)
05-22 19:34:53.056  1028  1179 W libprocessgroup: kill(-23841, 9) failed: No such process
05-22 19:34:53.056  1028  1179 I libprocessgroup: Successfully killed process cgroup uid 10118 pid 23841 in 44ms

**Comment by laurent22** [comment]
Yes, looks like OOM. Do you have any particularly large resource on your sync target? What would be the largest one?

**Comment by laurent22** [comment]
And I guess it crashes during synchronisation, is that right? When you open the app, it should start syncing soon after. What if you stop the sync process? Does it still crash? (just trying to understand where it comes from)

**Comment by jemag** [comment]
> Yes, looks like OOM. Do you have any particularly large resource on your sync target? What would be the largest one?

I have a 23.1 MB note, because of an attached pdf

> And I guess it crashes during synchronisation, is that right? When you open the app, it should start syncing soon after. What if you stop the sync process? Does it still crash? (just trying to understand where it comes from)

I only have my cellphone and not the tablet on me at the moment, but for the cellphone it seems it crashes while decrypting. So as soon as I open the application it starts decrypting, and there doesn't seem to be a way to cancel that. So the crash pretty much always happen and fairly quickly.

Also, if you check the sync status I posted a couple comments above, it seems like the synchronization of notes is actually complete. Only the revisions are missing.

**Comment by laurent22** [comment]
Hmm, that's quite annoying if it happens during decryption as there's currently no mechanism to handle this, and it will indeed keep trying to decrypt the same resource and crash again. I'll add something to handle this in a future version, but in the meantime I don't think you have any option other than uninstalling and reinstalling the mobile app. Just make sure you delete the large resource (any resource greater than 10MB) on the sync target before syncing again.

**Comment by jemag** [comment]
The problem is that I just transitioned from Evernote and I actually have a fair amount of notes with resources greater than 10MB.

 Will the handling in the future version actually allow me to use such notes or  would it only prevent the application from crashing while not being able to use such notes on mobile? Ideally I would prefer to keep those notes even if that means I can only use the application on my Windows and Arch linux desktops for a little while.

**Comment by laurent22** [comment]
The latest version normally saves the resource size as metadata, then when the mobile app sees a resource greater than 10MB it should skip it.

I'm not sure if you have this problem because you've started using Joplin before that version, or if there's a bug somewhere in the resource management.

If you open on your desktop the file ~/.config/joplin-desktop/database.sqlite, and then the `resources` table. Can you check that all of them have the `size` field set (i.e. with a value greater than 0)?

**Comment by jemag** [comment]
I only installed the app 3-4 days ago and I don't think I received any update for it, so I'm pretty sure I was always on the latest version.

I'm a bit rusty with my sqlite use but :
`select size from resources where size is null;`
returns nothing

and 
`select size from resources where size=0;`
also returns nothing

I'm happy to provide more information as needed, but it might have to wait tonight or my next break at work

**Comment by laurent22** [comment]
By default the size is set to -1, so could you also try ` select size from resources where size=-1;`?

**Comment by jemag** [comment]
> By default the size is set to -1, so could you also try select size from resources where size=-1;?

Same thing, does not return anything either

**Comment by tessus** [comment]
which means all resources should have set their size.

You can easily verify this by running the following 2 statements:

```
select count(*) from resources;

select count(*) from resources where size > 0;
```

if they are the same, all sizes are set....

**Comment by jemag** [comment]
Yes they are indeed the same and sizes are set

**Comment by laurent22** [comment]
I have an idea to improve the app when it crashes like that, so hopefully it should be better in the coming release.

**Comment by jemag** [comment]
Cleared files/cache and reinstalled the application with the new version. The same problem is still occurring (similar logs to what was posted above)

**Comment by jemag** [comment]
Formatted my phone, reinstalled the app with the latest version. 

I was able to fully sync and decrypt all the notes. However, a couple hours later I used the desktop application to update one note. Later on, after re-opening the app on mobile, the app tried to fetch resources and decrypt and crashed.

Now it seems I am back to square 1, as the mobile application will crash quickly after opening trying to fetch resources and decrypt items (the initial problem).

**Comment by laurent22** [comment]
Can you give a try to the latest version there? https://github.com/laurent22/joplin-android/releases With this version normally it should try only twice to decrypt the item (so two crashes) and then will skip it. I assume the item is too large for the phone so probably it cannot be decrypted on that device.

**Comment by jemag** [comment]
Tried multiple times (10+) with version 1.0.261 and app always crashes and I am still getting the same OOM error.

**Comment by laurent22** [comment]
Just to be sure could you try with the very latest one 1.0.271? This is strange because now the app normally should save a counter whenever it tries to decrypt a resource and after two attempts it should stop.

Could you provide the last few messages in the log just before the crash?

**Comment by jemag** [comment]
Same problem with 1.0.217. A resource is still failing to call close and going into OOM. The logs are similar to what was posted above: 

```
06-24 09:26:20.647  9784  9796 W System  : A resource failed to call close.
06-24 09:26:20.648  9784  9796 W System  : A resource failed to call close.
06-24 09:26:20.668  9784  9866 I et.cozic.jopli: Alloc concurrent copying GC freed 176(87KB) AllocSpace objects, 0(0B) LOS objects, 10% free, 211MB/235MB, paused 55us total 21.449ms
06-24 09:26:20.669  9784  9866 I et.cozic.jopli: Forcing collection of SoftReferences for 55MB allocation
06-24 09:26:20.669  9784  9866 I et.cozic.jopli: Starting a blocking GC Alloc
06-24 09:26:20.669  9784  9796 W System  : A resource failed to call close.
06-24 09:26:20.702  9784  9866 I et.cozic.jopli: Alloc concurrent copying GC freed 383(110KB) AllocSpace objects, 1(24KB) LOS objects, 10% free, 211MB/235MB, paused 50us total 33.180ms
06-24 09:26:20.702  9784  9866 W et.cozic.jopli: Throwing OutOfMemoryError "Failed to allocate a 58425200 byte allocation with 25165824 free bytes and 44MB until OOM, max allowed footprint 247451608, growth limit 268435456"
06-24 09:26:20.702  9784  9796 W System  : A resource failed to call close.
06-24 09:26:20.703  9784  9866 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
06-24 09:26:20.703  9784  9866 E AndroidRuntime: Process: net.cozic.joplin, PID: 9784
06-24 09:26:20.703  9784  9866 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 58425200 byte allocation with 25165824 free bytes and 44MB until OOM, max allowed footprint 247451608, growth limit 268435456
06-24 09:26:20.703  9784  9866 E AndroidRuntime:        at java.lang.StringFactory.newStringFromChars(StringFactory.java:267)
06-24 09:26:20.703  9784  9866 E AndroidRuntime:        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:252)
06-24 09:26:20.703  9784  9866 E AndroidRuntime:        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:65)
06-24 09:26:20.703  9784  9866 E AndroidRuntime:        at android.util.Base64.encodeToString(Base64.java:456)
06-24 09:26:20.703  9784  9866 E AndroidRuntime:        at com.RNFetchBlob.RNFetchBlobFS.readFile(RNFetchBlobFS.java:199)
06-24 09:26:20.703  9784  9866 E AndroidRuntime:        at com.RNFetchBlob.RNFetchBlob$6.run(RNFetchBlob.java:226)
06-24 09:26:20.703  9784  9866 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-24 09:26:20.703  9784  9866 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-24 09:26:20.703  9784  9866 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
06-24 09:26:20.706   930   964 W ActivityManager:   Force finishing activity net.cozic.joplin/.MainActivity
06-24 09:26:20.714   930  1023 I ActivityManager: Showing crash dialog for package net.cozic.joplin u0
06-24 09:26:20.727   930  1022 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
06-24 09:26:20.728   930  1022 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
06-24 09:26:20.761   573  1706 D SurfaceFlinger: duplicate layer name: changing com.android.launcher3/com.android.launcher3.lineage.LineageLauncher to com.android.launcher3/com.android.launcher3.lineage.LineageLauncher#1
06-24 09:26:20.803   930  4063 I OpenGLRenderer: Initialized EGL, version 1.4
06-24 09:26:20.803   930  4063 D OpenGLRenderer: Swap behavior 2
06-24 09:26:20.811  3023  3401 W SessionLifecycleManager: Handover failed. Creating new session controller.
06-24 09:26:20.871  9784  9784 D ReactNative: ReactInstanceManager.detachViewFromInstance()
06-24 09:26:20.872  3023  3401 I StreamController: registerScope: nowcards-15-526f5ef-f8d1
06-24 09:26:20.897   573  1706 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{f88b85f token=Token{d4e98fe ActivityRecord{6792cb9 u0 net.cozic.joplin/.MainActivity t570}}}#0
06-24 09:26:20.959  1845  1868 I ndroid.systemu: NativeAlloc concurrent copying GC freed 26991(1100KB) AllocSpace objects, 0(0B) LOS objects, 68% free, 5MB/17MB, paused 82us total 103.825ms
```

**Comment by hckrgod** [comment]
hi I am new here.Do you mind if i download ur App I think I may no whats happening ? Im not 100% but pretty close i wanna try something it peaked my interest when i cam across it I will repost after i try what i think is happening i dont like getting anyones hopes up since god knows i have been wrong before thankks...

**Comment by laurent22** [comment]
Hi, feel free to download it, it's available there: https://github.com/laurent22/joplin-android/releases

**Comment by hckrgod** [comment]
thanks i will get back you asap...

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by jemag** [comment]
Is there more information I can provide to help fix this problem?

**Comment by laurent22** [comment]
No, I know what I can try to fix it but haven't had time yet.

**Comment by jemag** [comment]
Seems like it is no longer crashing for me on mobile. However I can see it continuously decrypting items every 1-2 seconds (goes up to "decrypting items: 9/9" and start again 1-2 sec later)

**Comment by tessus** [comment]
Well, then this issue is resolved.

For the other part, see: 

https://discourse.joplinapp.org/t/constant-prompt-of-decrypting-items/3159
and
https://github.com/laurent22/joplin/issues/1758
