### ISSUE TITLE
Android File System Sync to SDcard Error

### ISSUE THREAD

**Issue by Likivik** [laurent22/joplin#1543]
### Operating system

- Android 7.1.2 (Lineageos 14.1) 

### Application

- Mobile v1.0.252

Issue: Syncing to file system (sd card) option throws errors (see attachments). Syncing to internal memory does work properly. 
log: (search for EUNSPECIFIED) 
[syncReport-1558455033102.txt](https://github.com/laurent22/joplin/files/3203491/syncReport-1558455033102.txt)

First sync attemp to /storage/580F-1405/Notes produced this:
![Screenshot_20190521-185815_1](https://user-images.githubusercontent.com/11075952/58112650-9d260380-7bfc-11e9-89ed-e9fb254dc3c0.png)

Then I created .sync and .resources folders and got this: 
![Screenshot_20190521-185900_1](https://user-images.githubusercontent.com/11075952/58112806-e6765300-7bfc-11e9-8801-a9e515450251.png)

Which seems similar to  issue #1519
Feels like a permission issue

Sorry for poor presentation, will fix from desktop. Also, it's an older OS, so might not be worth messing with it. I shall test on other devices/sdcards.

**Comment by contriba1** [comment]
Can reproduce on regular Android 7.1.2 + Joplin 1.0.271 when syncing to internal memory.
