### ISSUE TITLE
Joplin Web Clipper (Firefox) creates notes twice

### ISSUE THREAD

**Issue by xthursdayx** [laurent22/joplin#1544]
### Operating system

- macOS

### Application

- Desktop

When I use the Joplin Web Clipper in Firefox to create notes in Joplin I find that about 90% of the time the notes are created twice, meaning that I have to go through and manually delete each duplicate note. This seems to happen whether I'm "clipping" a simplified version of the page, or the complete page.

**Comment by tessus** [comment]
Hmm, I remember @laurent22 added a fix for this a while back so this shouldn't be the case anymore. Does this happen on certain sites or on all of them?
/ref 91ecab51c57398b53b2c8f58e24f56e92c25d92b (although that particular fix was for Chrome)

**Comment by xthursdayx** [comment]
It's not all websites, but definitely more than half the time. I'd say it happens with between 70-90% of the websites I clip. I'm only using the clipper in Firefox, so I can't compare with Chrome.

**Comment by Dasymi** [comment]
This happened when I was saving a web page yesterday with Firefox. That's the only time it's happened so far.

**Comment by laurent22** [comment]
Can you check what version of the clipper extension you are using, and what version of the desktop application?

**Comment by Dasymi** [comment]
Desktop version is 1.0.152. Clipper extension was 1.0.13.

I clipped the page that was duplicated yesterday and it only imported it once today, so seems a bit random. I've updated to 1.0.14 of extension now.

**Comment by laurent22** [comment]
You might want to update to 1.0.14 because that's when that particular bug was fixed. If you can't upgrade (we had some problems with Mozilla though I hope they didn't block the upgrade), let us know.

**Comment by Dasymi** [comment]
Updating to 1.0.14 on Mozilla was no problem.

**Comment by tessus** [comment]
@xthursdayx what's the status? Do you experience this problem with clipper version 1.0.14?

**Comment by xthursdayx** [comment]
Sorry, I was travelling for work. I too had been using version 1.0.13 of the web clipper (as well as desktop version 1.0.152) and just updated to 1.0.14 earlier today. So far, it seems that this has fixed my issue. Thanks @tessus and @laurent22 !

**Comment by tessus** [comment]
@xthursdayx glad that it works now. if you still experience this issue with 1.0.14, please let us now.
