### ISSUE TITLE
Suggestion based on the event of note loss (partially)

### ISSUE THREAD

**Issue by mmahmoudian** [laurent22/joplin#1547]
### Operating system

- Linux
- Android

### Application

- Desktop
- Mobile

I sync with Dropbox

### background

I write daily work diary/log to keep track of my research. For this I found it best to have one Notebook per year and one note per month, and in that one section per day. I typically write the diary when ever I feel something should be logged, so it does not have specific time.

### Incident

Today I opened Joplin and realized this months' note has very few lines of text and it has only log for the first 5 days of May! I understandably panicked and jumped into my Dropbox account hoping I can find the markdown file for this month and I can restore/recover. This is where I had the first problem: File names are not intuitive and all of them are stored in the same directory. (Probably having them in the same folder structure in the app would be optimal)

I downloaded the Joplin folder and grep a string that was unique to that specific file and finally found it. Then using the filename I went to Dropbox, tracked down the file, went to revisions and realized that the file size have drastically changed:

![20190522-1448](https://user-images.githubusercontent.com/390889/58172486-7241bb00-7ca1-11e9-814b-b250533d38d6.png)

At the end what I did instead if restoring the file (considering all the talks about database in #1197), I just downloaded that version and copied it's content to the note in Joplin and Synced again (hence the top most row in the screenshot). I have lost few bulletpoints, but fortunately they are so recent that I can still remember them.

By this, I would like to propose two things to provide ease in pinpointing the issue and prevent any data loss:
1. Storing files in the same folder structure as the app
2. Have some system in-place so that if the file size change and line count change are not changing hand in hand, the app raise the flag

**Comment by tessus** [comment]
There's an entry in the FAQ why files at the sync target use hashes a filenames. You are not supposed to read or change files on the sync target. The sync target is for syncing the files. That's all.
So item 1 will not happen. see FAQ.

The question is why the files would not be the same as in the Joplin app. Maybe you generated conflicts which you didn't resolve.

To item number 2: there's a system in place. As soon as you edit a note, the changes are synced within 1 min to the sync target. The sync interval is an additional sync run to grab changes maybe created by other Joplin clients.
The latest version of Joplin also has a note history. So every time you change a note, a new snapshot will be made (I think after 10 minutes - otherwise you have a new snapahot for every letter you type).

**Comment by mmahmoudian** [comment]
You are right, and also the Patreon post was very informative:
[Note history now in Joplin](Note history now in Joplin https://www.patreon.com/posts/note-history-now-27083082?utm_medium=social&utm_source=twitter&utm_campaign=postshare)

Regarding your first remark, I was not questioning my the file names are in hashes, I was implying that there is no dictionary file that contains filename to hash conversion.

Also to tackle the lack of folder structure (considering your comment and the post in Patreon, I think from now on, to add one more layer of redundancy and safety-net for my own peace of mind, I will export the whole note library in markdown format (since it creates the folder structure during export) and sync that with Dropbox or private git repo.

I think the case is closed.

**Comment by tessus** [comment]
@mmahmoudian 

> Regarding your first remark, I was not questioning my the file names are in hashes, I was implying that there is no dictionary file that contains filename to hash conversion.

Actually there is. It's in the table `resources` in `database.sqlite` in your config folder.
