### ISSUE TITLE
The default notes will continue to increase each time Joplin is initialized

### ISSUE THREAD

**Issue by tanshanli** [laurent22/joplin#1548]
# Operating system
- Windows
- Android

### Application
- Desktop
- Mobile

### Version
Joplin 1.0.152（prod,win32）

### Description
every time I delete the initialization notes for the Joplin, I find that the sync directory still exists.
the default notes continue to increase every time I sync from a new device.

**Comment by i-need-to-tell-you-something** [comment]
By "default notes continue to increase" do you mean that "default notes re-appear"? 

If yes, the workaround is to delete the default notes before setting up sync on the new device. But I guess ideally it could be useful if, when syncing a new device to an existing repository of notes, the default notes would get deleted in the process. Though this would result in unintuitive app behavior for users. I might expect these notes to appear in my repository and be negatively surprised by them just disappearing.

**Comment by tanshanli** [comment]
@i-need-to-tell-you-something no，I can delete the default notes through Joplin. When I sync OneDrive, they still appear in my OneDrive, but it's not shown in Joplin.When I often initialize Joplin (or replace a new device) to synchronize OneDrive, the number of default notebooks in OneDrive will always increase, even hough they are not visible in Joplin

**Comment by i-need-to-tell-you-something** [comment]
Very interesting. Thanks for clarifying. :+1:

**Comment by tanshanli** [comment]
@i-need-to-tell-you-something You can easily reproduce it.
1. Open Joplin  settings directory(Tools--General Options--General--Notes and settings are stored in)
2. Close Joplin,Delete all files in the directory
3. Open Joplin（It initializes the notes.）
4. Delete default notes
5. Change [Synchronization target]= File system (Tools--General Options--Synchronization)
6. Setting [Directory to synchronize with (absolute path)] = D:\test\Joplin
7. Click the [Apply] button,Click the [cancel] button to quit settings
8. Click the [Synchronize] button
You can see that there are a lot of notebook files under directory "D:\test\Joplin".

If you repeat the steps above,"D:\test\Joplin" will continue to add default notebook files(Not overwrite)

**Comment by tessus** [comment]
@laurent22 had previously used dedicated hashes for the welcome notes, but reverted that code. I am not sure, but new welcome notes should only be created for new installations of Joplin.

**Comment by andre68723** [comment]
@tessus what about setting up new devices for sync? 

In my case, I use dropbox at home & on mobile and installed joplin additional at work.
Started the Desktop App (with the default welcome notes) and added dropbox sync.

Now I have the default notes (which came with the work installation) again everywhere. Eventually a "Restore via Sync option" on first startup would be helpful here

**Comment by tessus** [comment]
@andre68723 please ask usability questions in the forum.

Yea, unfortunately there's no way to disable the creation of welcome notes on new devices.
I also wished there was a menu item instead, something like `Help -> create welcome notes`. On clicking that item would create the notes. Maybe Laurent would accept a PR in that regard. You could start a discussion on the forum.

**Comment by laurent22** [comment]
There's no plan to make this optional at the moment.

However the Welcome notes have been improved since this issue was created. For example, tags are no longer created, so you just need to right click the notebook and delete it. Even if you accidentally sync it, you can still delete it and there won't be left-over items (previously the tags would stay).

**Comment by tessus** [comment]
True, this makes it a lot easier to handle. Whenever you think that optional is a good idea, please let me know and I'll create a PR.
