### ISSUE TITLE
Strange with russian letters in editor in Windows

### ISSUE THREAD

**Issue by nrukin** [laurent22/joplin#155]
### Operating system

- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---

Hello,
i've found strange behavior with russian letters in editor - real cursor position and displayed cursor position are different. Longer the string - bigger the differ

in attached gif i've writed some letters, then put cursor in the middle of the string and pressed backspace.

![joplin_rus](https://user-images.githubusercontent.com/35288125/34759540-0d76e88a-f5ed-11e7-9da4-d81730115acc.gif)

Thanks!

**Comment by laurent22** [comment]
Does it do this in this demo too? https://ace.c9.io/build/kitchen-sink.html

**Comment by nrukin** [comment]
yes

**Comment by laurent22** [comment]
I have filed a report on the text editor component and will see if they have any solution to propose. Otherwise, I will see if it works with a different font.

https://github.com/ajaxorg/ace/issues/3506

**Comment by nrukin** [comment]
Thanks!
i've tested it on three different computers (win10, win8), but problem occurred only at one of them

i've found some issues with ace and other apps using ace: seems to be it should use only monospace font

https://github.com/swagger-api/swagger-editor/issues/703
https://github.com/ajaxorg/ace/issues/1078
https://github.com/jpillora/docker-dnsmasq/pull/4
https://stackoverflow.com/questions/15183031/ace-editor-cursor-behaves-incorrectly

**Comment by laurent22** [comment]
Ok that should be fixed in the release after the next one (so after 0.10.47). It was due to the editor not using monospace font.
