### ISSUE TITLE
F2 to rename notebooks and notes

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [laurent22/joplin#1558]
### Operating system

- Linux

### Application

- Desktop

---

I get the impression of a convention that stuff can be renamed with F2. Should at least work for notebooks. In case of notes, it should ideally focus on the title. For both notebooks and notes it should also select all of the title/name text (for easy replacement of all text). Maybe people locked into the Apple ecosystem are used to something different.

**Comment by laurent22** [comment]
I tend to press F2 too to rename thing too, even on macOS (which usually results in nothing happening), so wouldn't mind a pull request for this.

**Comment by tessus** [comment]
Hmm, we already have the shortcut `Cmd/Ctrl+Shit+N` to focus on the note title, which is currently the way to rename a note.
So we could use `F2` to rename a notebook, even though F keys are hardly used on a Mac.
