### ISSUE TITLE
Enter key in note title should focus on note body

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [laurent22/joplin#1561]
### Operating system

- Linux

### Application

- Desktop

---

Enter key while focused on note title should take the input focus from note title to note body.

**Comment by foxmask** [comment]
you can go to the body with `TAB` key instead

**Comment by i-need-to-tell-you-something** [comment]
Thanks. It is nice that this is achievable with a keyboard, but ideally I would like (not only for myself, but other future and (even some) present users) to keep the familiar common workflow. Especially since the enter key isn't needed for anything else in that a spot.

**Comment by foxmask** [comment]
I think we don't use Enter because we have the habit to press TAB in web page form.

**Comment by i-need-to-tell-you-something** [comment]
It is likely that if Enter were the default there would be an issue opened for adding Tab. :smile:
I believe my specific habit came from Evernote among other apps.

**Comment by foxmask** [comment]
I forgot evernote ; sorry ;D

**Comment by i-need-to-tell-you-something** [comment]
Wasn't this marketed as an Evernote replacement?
