### ISSUE TITLE
ALT+D as hotkey for Delete note popup dialog.

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [laurent22/joplin#1562]
### Operating system

- Linux

### Application

- Desktop

---

~When deleting a note with the delete key, there is no way to reach "Delete" option in the confirmation dialog by only using the keyboard~. To me personally Enter would be an intuitive option, but I would even settle for ALT+D or something. I tried the whole keyboard with ALT+something_else, and ALT+C (for cancel) was the only thing that the dialog box seemed to react to.
A downside would be that people using other locales (which don't have the letter D in that word) would have difficulty finding out about the shortcut key. So some kind of tooltip or such would be nice to have, if it isn't going to be Enter. 

Some people find Delete+Enter being a too big of a risk to accidentally hit for permanent deletion (#1123). Implementing a trash folder (#483) would solve that problem.

**Comment by foxmask** [comment]
tab key does that for me with version 1.0.160 (at least)

**Comment by i-need-to-tell-you-something** [comment]
Thanks. Yup seems Tab and Left key both switch to the delete button and when followed by Enter, a note can be deleted with keyboard only. I don't understand how did I miss that. I thought I was very methodical.

Ideally I think, having ALT+D would still be nice to have and more consistent as the cancel button has ALT+C.
