### ISSUE TITLE
[Bug] Note editor underscore syntax highlight

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [laurent22/joplin#1566]
### Operating system

- Linux

### Application

- Desktop

---

![image](https://user-images.githubusercontent.com/9165395/58254443-6b837880-7d73-11e9-84bb-66360c5e1a01.png)

Note viewer is functioning as expected. In the note editor side (left in default layout), underscores shouldn't get syntax highlighted in the middle of a word since that does not get converted to italics in the viewer pane (the right side in default layout). Asterisks and double asterisks do also function in the middle of words to start or end bold/italics.
For comparison StackExchange and Github also work the same way as I suggested in the aspects mentioned here. More specifically they don't have syntax highlighting for the editor, and in the view mode asterisks in the middle of words **do** format text and underscores in the middle of words **don't**.

**Comment by innocuo** [comment]
Joplin uses [Ace](https://github.com/ajaxorg/ace) for its text editor (through a couple other third party wrappers), so in general, editor specific bugs should be reported at and fix by that project, not Joplin.

In this case, I see the same behavior in the [Ace demo editor](https://ace.c9.io/build/kitchen-sink.html), so it's clearly not unique to Joplin.

I'm going to close this issue, you should report this on Ace. It seems there's an [open issue about this exact same problem already](https://github.com/ajaxorg/ace/issues/3750).
