### ISSUE TITLE
[Bug] Note editor header syntax highlight

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [laurent22/joplin#1567]
### Operating system

- Linux

### Application

- Desktop

---

![image](https://user-images.githubusercontent.com/9165395/58253941-4cd0b200-7d72-11e9-9090-9e53bda85a04.png)

Note viewer is functioning as expected. Note editor doesn't show header syntax highlighting if the preceding line is part of a bullet list or numbered list. In case of a quote, the header even (only in editor) takes on the syntax highlighting of the quote.

**Comment by innocuo** [comment]
See #1566 for why I'm closing this issue, too. It looks like there's a [similar open issue about this on the Ace project](https://github.com/ajaxorg/ace/issues/2978).
