### ISSUE TITLE
Notebooks appear in the wrong place momentarily

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [laurent22/joplin#1569]
### Operating system

- Linux

### Application

- Desktop

---

Minor cosmetic issue.
When creating a new notebook it gets spawned at the bottom of the list and then half a second later it flickers into its rightful place (what ever the sorting is). Notes are fine - they spawn in the correct place right away.

**Comment by IrosTheBeggar** [comment]
Just came to report that I'm seeing this on OSX as well
