### ISSUE TITLE
Codeblock scroll without focusing

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [laurent22/joplin#1571]
### Operating system

- Linux

### Application

- Desktop

---
Currently I cannot scroll horizontally in a codeblock without clicking into the code block. Generally in Linux (more specifically KDE) I'm used to being able to scroll where-ever my cursor can go, regardless of which element or which window the focus is on. A small nuisance.

**Comment by alinuxfan** [comment]
Any other information? I am on Linux Mint Cinnamon with Joplin version 1.0.158 and I can mouse wheel right and left on codeblocks.

**Comment by i-need-to-tell-you-something** [comment]
Yup, seems to work for me as well now. Very odd. I was convinced I observed it not working at that time.
