### ISSUE TITLE
Code theme minor adjustments

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [laurent22/joplin#1573]
### Operating system

- Linux

### Application

- Desktop

---
## Example in light theme:
![image](https://user-images.githubusercontent.com/9165395/58260763-ae4b4d80-7d7f-11e9-8ca5-fccb64cfebca.png)
## Same example in dark theme:
![image](https://user-images.githubusercontent.com/9165395/58259928-3b8da280-7d7e-11e9-9b2f-8fdba6c09fdc.png)

Unless themes are easily customizeable I have two small problems with these themes, personally in many light conditions anyway - maybe your screen is amazing and therefore it is less of a problem for you.
1. In the light theme, I feel the background of the **codeblocks** does not contrast from the background of plaintext very well. Maybe a bit darker light grey? Maybe as dark as the inline code is in the light theme? Inline code is great here. Personally I also like the vibrant, intense colors of dark theme's code block syntax highlighting. But different people have different opinions here probably.
2. In the dark theme, I feel that **inline code** does not contrast from plaintext very well. Difficult to notice it in plaintext. One option would be to make the font color of inline code to be a bit darker. Maybe like that of code blocks in dark theme? Or maybe lighter background to inline code? Codeblocks are awesome here.

**Comment by CalebJohn** [comment]
See my comment on #1575

**Comment by laurent22** [comment]
I think there are ways to improve these themes a bit but not sure how. Maybe copy the themes from another app from a major company, maybe Apple or Microsoft? As they would have done the usability study to get the contrast and colours right.

**Comment by CalebJohn** [comment]
The codeblocks are standard themes, I think it's just a matter of personal preference? We could target higher contrast themes since that seems to be the issue here.

**Comment by v-marinkov** [comment]
Perhaps some of Jupyter's or TexStudio's themes can be adapted? I am not familiar with Atom but maybe its too.
Is there documentation on how to provide user themes? I think this will unlock a massive flow of creativity from the community.
