### ISSUE TITLE
[Bug] Search box quirk with second attempt at same search

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [laurent22/joplin#1574]
### Operating system

- Linux

### Application

- Desktop

---

### Process:

1. Click on search box.
2. Type a search term (that actually gives some results).
3. Press Enter.
3. Click on any notebook to navigate away from the results.
4. Click on search box.
5. Press Enter.

#### Observed:

The second Enter press does nothing. Still showing the contents of the notebook I clicked.

#### Expected:

The second Enter press shows the same results as first Enter press showed.

**Comment by innocuo** [comment]
This behavior is outdated now because of PR #1504 
Now, when you click on a notebook after a search, the search box gets emptied, so when you click on it again, there's no other option but to start a new search.

I'm closing this one.
