### ISSUE TITLE
Dark theme bold text not contrasted enough

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [laurent22/joplin#1575]
### Operating system

- Linux

### Application

- Desktop

---

## Example in light theme:
![image](https://user-images.githubusercontent.com/9165395/58265022-8fe95000-7d87-11e9-8a27-92d5cf308068.png)
## Same example in dark theme:
![image](https://user-images.githubusercontent.com/9165395/58265215-e9ea1580-7d87-11e9-9a75-43b11f5e93d0.png)

If I understand correctly, customizing themes or changing the font isn't easy, therefore I made this issue. I feel that (at least on my screen) telling apart bold text from non-bold text in the dark theme is very difficult. 
The easiest solution maybe (what I would use for myself if I knew how to edit themes, and if I didn't think this might be a deterrent for others as well) would be to just add some kind of light color to bold text. Maybe there are alternatives to increasing the contrast between the two somehow?

**Comment by CalebJohn** [comment]
The markdown viewing pane style can be easily customized using CSS. Please check the info on userstyles
https://github.com/laurent22/joplin/blob/master/README.md#custom-css
