### ISSUE TITLE
Web Clipping from Mobile

### ISSUE THREAD

**Issue by boramalper** [laurent22/joplin#1576]
### Operating system

- Android
- iOS

### Application

- Mobile

Add web clipping support from mobile devices too please. =)

**Comment by laurent22** [comment]
Not possible as of now

**Comment by gwerbin** [comment]
On iOS, wouldn't it be possible to add a [sharing menu](https://i1.wp.com/9to5mac.com/wp-content/uploads/sites/6/2015/07/img_0323.png) integration?
