### ISSUE TITLE
 1.0.152 - Code blocks with 4 spaces or tab indentation and empty lines before and after do not render correctly.

### ISSUE THREAD

**Issue by Stavros0x00** [laurent22/joplin#1577]
### Operating system

- Linux

### Application

- Desktop

Hello!

Code blocks with 4 spaces or tab indentation and empty lines before and after do not render correctly. I tried with dark and light theme.

Expected behavior - Examples:
https://gist.github.com/MohamedAlaa/2961058 <-- https://gist.githubusercontent.com/MohamedAlaa/2961058/raw/ddf157a0d7b1674a2190a80e126f2e6aec54f369/tmux-cheatsheet.markdown

If this is a bug but this code block functionality is not expected by Joplin then you can close this i will find other alternatives. :)

Thank you and Great Job as always!

![image](https://user-images.githubusercontent.com/3338620/58321706-93341880-7e27-11e9-8a36-4d930f11401e.png)

**Comment by innocuo** [comment]
see point [3 in my comment here](https://github.com/laurent22/joplin/issues/1514#issuecomment-495485912), I think this is about the same issue. So, the code on the right version isn't supposed to render the tabs/spaces, or have syntax highlight, but it is missing a background color, right?

**Comment by Stavros0x00** [comment]
Exactly, i missed your comment. I am closing the issue. I will try your suggestion. Thanks!
