### ISSUE TITLE
No sync to Win7 when notes have been created with Win10?

### ISSUE THREAD

**Issue by creactiv** [laurent22/joplin#1579]
### Operating system

- Windows

- Linux

### Application

- Desktop

Well, 

i got a webdav folder on one of my servers in a datacenter, and i can sync all my devices to my Joplin content. When i edit some data on my desktop, i find them on Android mobile or tablet and one of my laptops too. The second laptop, running on windows7 bears the samesettings as my desktop pc and laptop, both which use Windows 10, does not sync any of the notes which are in the according folder on my webdav server. All Joplin's have the same current version 1.0.15.2, so i am confused. 

The only thing, which is different seems to be the operating system. Do i need to upgrade to win10?

Thanks and best.
cr

btw: the Win7 system only syncs 36 items, which are the ones which have been created there, the other 120 items from sync folder don't seem to be read.

**Comment by creactiv** [comment]
By digging deeper i found out, that the link on windows 10 joplin ended with /joplin and the one on windows 7 ended with /joplin/. So i fixed the link in windows 7, copied the extra data to the /joplin folder and restarted windows 7 joplin. Unfortunately, this didn't work :-( Will try a windows restart and a reinstallation, if restart doesn't work to get all my data on second laptop. ...

**Comment by creactiv** [comment]
Well, the notes, i copied from the wrong folder to the correct one can now be found anywhere, but the win7 Joplin does not honor the corrected path, although i restarted win 7 and also un-installed and re-installed joplin. 
I will give it a try, by using a link, which cannot work and reset it afterwards, but this is confusing at best. 

Best
..

**Comment by creactiv** [comment]
Weird Stuff is happening. If i create a note on Win 7, i will see it in win10. If i remove it in win10, where all other notes are located, it removes it on Win 7. But it won't sync existing notes from win 10 to win 7...

Even weirder: if i create a new note, and move another note on it, it will sync the existing note, but without any content... So any help to fix this would be really appreciated, because this drives me crazy. 

If everything else fails, i will upgrade to win 10 and hope, it will work, somehow, afterwards, otherwise i would have to reinstall everything with a new win 10 version ,what i wanted to get around.

**Comment by tessus** [comment]
Please use the forum for support questions.

When it comes to Joplin it does not matter if it runs on Win7 or Win10.

**Comment by tessus** [comment]
Btw, without a debug log or error message from the machine where sync does not seem to be working, it is impossible to figure out what the problem is.

**Comment by tessus** [comment]
Any update on this?

**Comment by creactiv** [comment]
Just came back today from vacation, will check into it and try to figure out an error message, after i upgraded to the latest version on all my machines and let you know. In my opinion the windows7 joplin does not see the notes from windows 10 machines; whether it does not recognize them at all or whether it thinks, that it has already synced, i don't know. When i create a new note on win7, i can see them on win10 machines, but not vice versa. 

Will get back later today on that...
Best

**Comment by creactiv** [comment]
A side note: 
I created a new notebook Linux yesterday under Windows 10 and now i see the new notebook under windows 7 but it does not contain any notes, although i created some notes yesterday. 

Weird.

even if it does not matter whether joplin runs on win10 or win 7, i just keep that "naming", so i can tell them apart ;-)
