### ISSUE TITLE
Mac desktop app pegs CPU and freezes every 2 min for 10 sec or so

### ISSUE THREAD

**Issue by mapledyne** [laurent22/joplin#158]
### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---

On the Mac (10.11.6) desktop version (0.10.43, though it was present in prior versions):

Approximately every two minutes, my CPU is pegged at 100% by Joplin (the process is called "joplin_helper") for 10 seconds or so. During this time Joplin is unresponsive. After this time anything I'd typed will quickly catch up from the buffered keystrokes. 

I've enabled logging mode per the docs here and the console logging doesn't show any more information. This is the only message I'm seeing come to the log regularly: 
`Jan 10 10:01:05 LOSX-341303-MCG-N QuadroNGui[1389]: Sending {"type":"Focus","message":"net.cozic.joplin-desktop"}`

The debug console that comes up in Joplin with the dev tools enabled have lots of information but I don't know how to read it well enough to spot anything, but have watched several panes to look for changes there while this freeze/CPU spike was happening and didn't see anything.

I'm syncing to/with the filesystem but have turned off sync to test and had the same results.

Not sure how I can tease out other details to be helpful with this, but happy to do anything.

**Comment by laurent22** [comment]
Whenever it is very slow, could you note the time, then please could you check log.txt (in ~/.config/joplin-desktop) and see what the app was doing at this time?

When you sync with the filesystem, is it to a local hard drive or a network share? Is there something special about the drive, or is it a standard macOS file system (HFS+)?

**Comment by mapledyne** [comment]
Oh, hm. I somehow got under the impression that the logs would be in the system log dir (/var/log) and didn't check that file.

More info, then:

It's just syncing to a local hard drive (I'd love a remote sync, but am a Dropbox user so needing to decide if Joplin is enough to change/add providers) currently, on a standard file system. I currently have sync disabled, yes, and experiencing the same thing.

Now on to the log.txt files. I did a tail of the file and watched log.txt get written to as the problem came up, and while the app was frozen and the CPU was pegged, the log was being madly written to with "`get <path to .md file>`" for what seemed to be for every note in the system.

After the whole mad "list all the notes" list a summary of sorts comes up saying:
`
2018-01-10 10:59:35: "Sync: finished: Synchronisation finished [1515610736527]"
2018-01-10 10:59:35: "Reducer action", "SYNC_REPORT_UPDATE"
2018-01-10 10:59:35: "Operations completed: "
2018-01-10 10:59:35: "updateRemote: 1"
2018-01-10 10:59:35: "createRemote: 1"
2018-01-10 10:59:35: "Total folders: 3"
2018-01-10 10:59:35: "Total notes: 488"
2018-01-10 10:59:35: "Total resources: 5699"
2018-01-10 10:59:35: "Reducer action", "SYNC_COMPLETED"
2018-01-10 10:59:35: "Recurrent sync is disabled"
`

This would seem to imply that it's attempting a sync even though it's disabled? I'm reading this otherwise from ignorance though.

**Comment by mapledyne** [comment]
As an experiment, I deleted the entry in "Directory to synchronise with" and saved that (in addition to changing the sync interval to disabled which I'd done prior). This continued to reference the local directory I had in there during this CPU spike/freeze, so even after hitting "save" I had to quit Joplin and restart it (which doesn't seem to be intended behavior but isn't a huge deal).

After deleting that entry the app started reacting much better.

I'm seeing this error:
```
2018-01-10 11:20:30: "Reducer action", "SYNC_REPORT_UPDATE"
2018-01-10 11:20:30: "Operations completed: "
2018-01-10 11:20:30: "Total folders: 3"
2018-01-10 11:20:30: "Total notes: 488"
2018-01-10 11:20:30: "Total resources: 5699"
2018-01-10 11:20:30: "There was some errors:"
2018-01-10 11:20:30: "Error: Error: EACCES: permission denied, mkdir '/.sync'
Code: EACCES
Error: Error: EACCES: permission denied, mkdir '/.sync'
    at FileApiDriverLocal.fsErrorToJsError_ (/Applications/Joplin.app/Contents/Resources/app/lib/file-api-driver-local.js:24:16)
    at fs.mkdirp (/Applications/Joplin.app/Contents/Resources/app/lib/file-api-driver-local.js:172:19)
    at xfs.stat (/Applications/Joplin.app/Contents/Resources/app/node_modules/fs-extra/lib/mkdirs/mkdirs.js:55:43)
    at /Applications/Joplin.app/Contents/Resources/app/node_modules/graceful-fs/polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:114:15)"
```

which still seems sync related, but may not be an issue. I don't know if it's really trying to make a `.sync` directory on the root of the system, but it seems instead like it was trying to build a sync directory by cat'ing something else together (I'm presuming the "Directory to synchronise with" config setting) and now is failing because that field is empty.

Still, from my end, a quick failure here is having dramatically less impact on my system than the constant re-get (/check?) of all of the notes were having.

**Comment by laurent22** [comment]
Ok I see, it's because there are many notes and resources and the file system driver currently is quite inefficient. Each Joplin driver provides a "delta" API which gives a list of the items (in this case, files) that have changed since the last check. However, since a file timestamp can be inaccurate I don't rely on this and instead fetch the content of each file and look at the (application-controlled, thus accurate) timestamp in there.

So it means in your case on every sync it's opening and getting the content of 6000 files every time. OneDrive (or soon Nextcloud) doesn't have this issue since they provide a built-in delta API or provide accurate timestamps.

At the moment there's unfortunately no workaround for this. I can think of some optimisations which I might implement at some point, or if someone has any suggestion, I'm open to any idea.

Regarding the fact that it syncs even when disabled, that sounds like a bug which has probably a quick fix.

**Comment by r618** [comment]
Why is filesystem timestamp inaccurate ?

**Comment by laurent22** [comment]
There are some comments about it in the source [here](https://github.com/laurent22/joplin/blob/d659d975cd4061ee9dac2061167cca2afdcd2c4f/ReactNativeClient/lib/file-api-driver-local.js#L7)  and [there](https://github.com/laurent22/joplin/blob/master/ReactNativeClient/lib/synchronizer.js#L239).

It's possible I'm looking at it the wrong way though, but basically so far I've privileged reliability over performances. As sync is getting more and more stable, maybe there's some optimisations that can now be added.

**Comment by r618** [comment]
right, I was wondering mainly because you surely can get the time of a file modification with resolution higher than a second on a sane filesystem; thanks for the links

**Comment by laurent22** [comment]
Hello, the [latest version](https://github.com/laurent22/joplin/releases/tag/v0.10.48) addresses this problem.  The file sync logic has been optimised so that it doesn't fetch the content of all the files on each sync operation. Also the items are processed in batch of 1000 max so that it doesn't slow down when many items need to be synced.
