### ISSUE TITLE
Sync not working on Android

### ISSUE THREAD

**Issue by ChrisWiegman** [laurent22/joplin#1580]
### Operating system

- Android

### Application

- Mobile

On mobile only, with a new install of the app, I am no longer able to sync, instead getting a 401 error. Note, all other connections to the server work fine (Joplin on Desktop, other webdav clients, etc). I have regenerated and tried new passwords, reypted credentials about 100 times and tried pretty much everything else I can think of on the android app. Here's some of what I'm seeing:

Output from server logs including the successful sync from the desktop Joplin client followed by the broken mobile client:

`nextcloud_1    | 172.25.0.4 - --- [25/May/2019:16:40:28 +0000] "MKCOL /remote.php/webdav/Joplin/.sync/ HTTP/1.1" 405 1463 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
nextcloud_1    | 172.25.0.4 - --- [25/May/2019:16:40:28 +0000] "MKCOL /remote.php/webdav/Joplin/.resource/ HTTP/1.1" 405 1457 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
nextcloud_1    | 172.25.0.4 - --- [25/May/2019:16:40:29 +0000] "PROPFIND /remote.php/webdav/Joplin/ HTTP/1.1" 207 8265 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
nextcloud_1    | 172.25.0.4 - - [25/May/2019:16:40:33 +0000] "GET /remote.php/webdav/Joplin/.sync/ HTTP/1.1" 401 1535 "-" "okhttp/3.11.0"
nextcloud_1    | 172.25.0.4 - - [25/May/2019:16:40:35 +0000] "PROPFIND /remote.php/webdav/Joplin/ HTTP/1.1" 401 1523 "-" "okhttp/3.11.0"
nextcloud_1    | 172.25.0.4 - - [25/May/2019:16:40:37 +0000] "GET /remote.php/webdav/Joplin/.sync/ HTTP/1.1" 401 1521 "-" "okhttp/3.11.0"`

A Sync Report from the mobile app:
[syncReport-1558802139585.txt](https://github.com/laurent22/joplin/files/3219537/syncReport-1558802139585.txt)

A screenshot of the error on mobile:
![Screenshot_20190525-123744](https://user-images.githubusercontent.com/394675/58372405-b7a4f900-7eea-11e9-88e4-9e1fd3881ed7.png)

For sake of my own sanity (if nothing else), a screenshot of the success message from a sync to the same server on Desktop: 
![Screenshot from 2019-05-25 12-44-19](https://user-images.githubusercontent.com/394675/58372418-db683f00-7eea-11e9-9a03-90c76e0f4ace.png)

Any advice here would be appreciated. Note, I was able to get this working about two weeks ago, on mobile, using the same server. I had to factory reset the phone at which point it can no longer connect.

**Comment by tessus** [comment]
Whenever there is an issues like this, it always comes down to a problem that has nothing to do with Joplin.
Maybe it's better to post this in the forum. I believe more people are reading the forum than the gh tracker, which should really only be used for bugs. There have been several similar issues on the forum already.

Most people mistype their password (I've never understood why copy and paste never comes to mind). Others forget to create the directory on the server. Others mistype the URL (copy and paste seems to be really hard).
If none of the above was the problem, it's most likely a server (related) issue. e.g. When 2FA is activated, people don't understand that they have to use tokens instead, even though this is explained in all server manuals.

I don't want to be dismissive, but it has worked before accrording to your last sentence, so why should it be a problem with Joplin?
In any case, I'm confident we'll be able to solve this.

**Comment by tessus** [comment]
I haven't heard anything back since my comment, so what's the status?

**Comment by ChrisWiegman** [comment]
I found an alternative notes solution that actually works.
