### ISSUE TITLE
non-English WebDAV URL

### ISSUE THREAD

**Issue by ShuiHuo** [laurent22/joplin#1581]
### Operating system

- Linux

### Application

- Desktop

![深度截图_选择区域_20190526090555](https://user-images.githubusercontent.com/7471938/58376127-7cabcf80-7f95-11e9-8853-c8d596ef4465.png)

https://pan.example.com/remote.php/webdav/文档/笔记/joplin/
![https://pan.example.com/remote.php/webdav/文档/笔记/joplin/ set](https://user-images.githubusercontent.com/7471938/58376144-d57b6800-7f95-11e9-9f66-c6a7ed99eb1a.png)
![https://pan.example.com/remote.php/webdav/文档/笔记/joplin/ error](https://user-images.githubusercontent.com/7471938/58376166-64888000-7f96-11e9-83ad-2f0839cec0b9.png)

https://pan.example.com/remote.php/webdav/%E6%96%87%E6%A1%A3/%E7%AC%94%E8%AE%B0/joplin/
![https://pan.example.com/remote.php/webdav/%E6%96%87%E6%A1%A3/%E7%AC%94%E8%AE%B0/joplin/ set](https://user-images.githubusercontent.com/7471938/58376089-b29c8400-7f94-11e9-9434-51ef2458edd2.png)
![https://pan.example.com/remote.php/webdav/%E6%96%87%E6%A1%A3/%E7%AC%94%E8%AE%B0/joplin/ error](https://user-images.githubusercontent.com/7471938/58376091-b8926500-7f94-11e9-889e-821cafc26f10.png)

https://pan.example.com/remote.php/webdav/Documents/Notes/joplin/
![https://pan.example.com/remote.php/webdav/Documents/Notes/joplin/ set](https://user-images.githubusercontent.com/7471938/58376175-de206e00-7f96-11e9-92d7-ed90f6e9cc6a.png)
![https://pan.example.com/remote.php/webdav/Documents/Notes/joplin/](https://user-images.githubusercontent.com/7471938/58376176-deb90480-7f96-11e9-9172-bfd3ccbe245c.png)

**Comment by tessus** [comment]
@laurent22 are we using a module to do the webdav connect? This seems like a bug to me, but I can't say if it is a bug in Joplin or upstream.

**Comment by laurent22** [comment]
Looks like it would work if you use lowercase: `https://pan.example.com/remote.php/webdav/%e6%96%87%e6%a1%a3/%e7%ac%94%e8%ae%b0/joplin/` Could you try that? It's a bug in Joplin I guess or an inconsistency in some WebDAV servers maybe. I think it could be improved.

**Comment by ShuiHuo** [comment]
Looks fine
![https://pan.example.com/remote.php/webdav/%e6%96%87%e6%a1%a3/%e7%ac%94%e8%ae%b0/joplin/ set](https://user-images.githubusercontent.com/7471938/58386974-0e6d1880-803a-11e9-9f1c-57c5f2797217.png)
![https://pan.example.com/remote.php/webdav/%e6%96%87%e6%a1%a3/%e7%ac%94%e8%ae%b0/joplin/](https://user-images.githubusercontent.com/7471938/58386975-0f05af00-803a-11e9-9271-8a8effd16fd1.png)

**Comment by ShuiHuo** [comment]
After changing the link, joplin did not sync the content of the old link to the new link, and changed the link back to the old link again without displaying the content of the old link.

**Comment by laurent22** [comment]
I don't understand the last part, could you give me details or provide more screenshots showing the problem?

**Comment by ShuiHuo** [comment]
Maybe I am not saying well, there is a recorded video here, which may be helpful. (This may need to create a new issue) - Google Translate

https://mega.nz/#F!9R9SiSpB!wglbbq9hm4OPyuytUyc59w
