### ISSUE TITLE
Question: Does E2EE Setting Store Notes On Device In An Encrypted Format?

### ISSUE THREAD

**Issue by trymeouteh** [laurent22/joplin#1582]
Does E2EE Setting Store Notes On Device In An Encrypted Format? Or are the notes stored in plain text and only encrypted in transit?

**Comment by tessus** [comment]
Notes are encrypted in transit and on the sync target. They are NOT encrypted locally.

see also: https://joplinapp.org/faq/#could-there-be-a-password-to-restrict-access-to-joplin

P.S.: Please ask questions on the [forum](https://discourse.joplinapp.org/).
