### ISSUE TITLE
Template in Joplin (YALM / rmarkdown)

### ISSUE THREAD

**Issue by bepolymathe** [laurent22/joplin#1585]
### Operating system

- Linux

### Application

- Terminal

---

Is there a solution to integrate "templates" into note creation. I use a lot of YALM headers for markdown and rmarkdown documents. 

Moreover, would it be possible for documents in rmarkdown (.rmd) format to be recognized in Joplin?

Thank you for this software anyway.

**Comment by CalebJohn** [comment]
This is something I've been thinking about lately and how to get a pull request in for soon (on the desktop version). For now you can do what I do, write a Python script that uses the API to create a note with some template.

**Comment by bepolymathe** [comment]
Have you put this kind of script somewhere (site, github...) ?

**Comment by CalebJohn** [comment]
I haven't but @foxmask has some stuff up on [github](https://github.com/foxmask/joplin-api) that you can check out. Also you can see from the [api documentation](https://github.com/laurent22/joplin/blob/master/readme/api.md) that it's very simple.

**Comment by bepolymathe** [comment]
Ok thanks ! I'll see that...
