### ISSUE TITLE
Internal markdown link not working by clicking.

### ISSUE THREAD

**Issue by bugcaptor** [laurent22/joplin#1587]
### Operating system
- Windows

### Application
- Desktop(Portable)

v1.0.153: OK, it's ALL working. 
v1.0.157: Broken. Hyperlink showing properly only, not working by clicking it.

**Comment by navlar** [comment]
v1.0.157: Broken for me too. I concur.

**Comment by tessus** [comment]
Yes, it is: https://discourse.joplinapp.org/t/joplin-1-0-157-links-of-notes-between-notes-broken/2485/
