### ISSUE TITLE
iOS: Encryption input hidden behind keyboard

### ISSUE THREAD

**Issue by alexdevero** [laurent22/joplin#159]
The input for setting a password for encryption is hidden behind keyboard and scrolling doesn't work.

### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*
![img_0901](https://user-images.githubusercontent.com/4237724/34812857-d4dc3438-f6a7-11e7-80af-2284528ca7a5.PNG)

**Comment by laurent22** [comment]
Oh well, maybe the whole app should be wrapped in that KeyboardAvoidingView so that it applies to all the screen. Any thoughts on this @marcosvega91 ? Can your fix be applied globally without individually modifying each screen?

**Comment by laurent22** [comment]
@alexdevero, the latest iOS version should have a fix for this normally. Is it working for you now?
