### ISSUE TITLE
Malwarebytes reported file as suspicios! 

### ISSUE THREAD

**Issue by srj-github** [laurent22/joplin#1592]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

**Comment by srj-github** [comment]
Sorrry, not the file, but the website when downloading new version!

**Comment by CalebJohn** [comment]
What was the website you downloaded from?

**Comment by srj-github** [comment]
I have followed the upgrade link from the app, which lead me to the github's repository.

**Comment by tessus** [comment]
So malwarebytes reported github as suspicous. Well, I find this suspicious.
Can you please send them a false positive report?
