### ISSUE TITLE
[Feature Request] Choose Sort Order for Notebooks and Notes Lists

### ISSUE THREAD

**Issue by homofortis** [laurent22/joplin#1598]
### Operating system
- macOS
- Linux
### Application
- Desktop

First of all, Joplin is a great application and the idea of using markdown really rocks. I've been using it for five mounts and I really enjoy it - great work! 
The only thing I've been missing all the time is the ability to select the order in which notes and notebooks appear in their lists. Especially when the list gets rally long (e.g. a diary). It would be nice if the items could be sorted by name, creation date, update date, or (why not?) arbitrary by manually arranging them.

**Comment by CalebJohn** [comment]
If you look at the top bar of joplin you should see the View header, if you look under view you should see the sort options for notebooks and notes. Currently supported is Title, Creation Date and Updated Time. 

For more information about manually sorting refer to #51 

You can close this issue as sorting is already supported (except in the case of manual sorting which already has an existing issue).

**Comment by tessus** [comment]
Closing.
