### ISSUE TITLE
Resizable columns

### ISSUE THREAD

**Issue by tobipch** [laurent22/joplin#16]
Manually resizable columns would let me adapt my layout and use Joplin more effective.

**Comment by Karrthik12** [comment]
Is there a possibility that the enhancement can be given to joplin for draggable by using following ideas.

### Idea 1
is wrapping only note-list component of joplin with a resizable component such that it can be resizable on both sides and other columns depend on note-list component for width. So when ever we change the size of resizable component  we will be passing the same css parent properties to child so make it look like the note list component is moving not the resizable component. If the note-list component is moving to the left then the side bar size would be the size of two components combined subtracted to the width of note width. Same with the Note text as well.

Changes that should be done are 
1. Adding the Resizable component as parent to the note list component.
2. Passing the styles of resizable component to note list component and other components as well when the resizable component is resized.
3. Rendering the DOM every time the application is resized.

### Idea 2 
is adding the event listener functions in the code for note list and when ever the mouse event is done the following click listeners like onMouseUp, onMouseMove, onMouseDown are called. Using these functions we can make note list resizable. Rendering should be done when application is resized.

Changes that should be done are 

1. Adding event listeners to the component.
2. Passing the styles of resizable component to note list component and other components as well when the event is occurred.
3. Rendering the DOM every time the application is resized.

_Instead of making a single component dragable in both sides, we can make side bar and note list resize to their right._

**Comment by jgreth** [comment]
+1 

Would be nice to be able, to resize the sidebar width manually

**Comment by edhilgendorf** [comment]
+1 
Would love to be able to resize columns in Terminal:
![image](https://user-images.githubusercontent.com/7498517/46496446-e9871500-c7cc-11e8-8232-c19354116c33.png)

**Comment by seth100** [comment]
+1

**Comment by aerioeus** [comment]
so, it doesnt exist, right?

**Comment by subi54** [comment]
@aerioeus, not yet.

**Comment by aerioeus** [comment]
ok, merci for letting me know

**Comment by metronidazole** [comment]
@laurent22 I'll paypal you $20 if you implement this within a month from this comment.

**Comment by theerror** [comment]
> @laurent22 I'll paypal you $20 if you implement this within a month from this comment.

it's actaully good idea. I second it. :)

**Comment by aerioeus** [comment]
me too ;)

**Comment by laurent22** [comment]
> @laurent22 I'll paypal you $20 if you implement this within a month from this comment.

For bounty, the best probably is to add the request to something like https://www.bountysource.com/ . That would give the issue more visibility and that way anybody can pick the issue and make the changes.

**Comment by laurent22** [comment]
Done
