### ISSUE TITLE
[Feature Request] Character count in notes

### ISSUE THREAD

**Issue by alexdevero** [laurent22/joplin#160]
It could be useful to have some information about the number of characters in current note. For example, one may use Joplin app to write blog posts, diary or just some random notes. And she may have a goal of always writing a certain number of characters.

For example, note taking app Day One shows character count on the bottom of the note (not during editing or writing). Joplin could also use some space on the very end of the note to show character count, if user allows this option in config. Or, this information could be displayed in some summary or information about opened note, something similar to status.

### Operating system

- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

### Application

- [x] Desktop
- [x] Mobile
- [ ] Terminal

**Comment by laurent22** [comment]
There's already a "metadata" pane on mobile (should be added to desktop too at some point). Maybe that pane could be cleaned up by removing the technical/debugging info from it, and adding useful info like word or character count.

**Comment by alexdevero** [comment]
That sounds like a good idea. Metadata are also a place where I would look for character count, as a type of note metadata.

**Comment by taw00** [comment]
Vote from me as well. Writers (disciplined writers) typically set daily time and word count goals. I would love to see a means to easily query a document's word count.

**Comment by taw00** [comment]
Here's what gedit does (Menu --> Tools --> Document Statistics). Simple. Useful.
![Screenshot from 2019-05-06 17-00-33](https://user-images.githubusercontent.com/6908872/57255101-f4cf4700-7020-11e9-9fd4-8c77c0bb5810.png)

**Comment by rootion** [comment]
Any update on this?

**Comment by bmcgonag** [comment]
This would be a great feature on all platforms.  I'm  Linux and Mac user myself, but character count would be great.

**Comment by laurent22** [comment]
Thanks, that would be great. The way I see it could be implement like this:

- Either create a new dialog like the Document Statistics one above, which would include various stats.

- Or add the info the existing Information dialog (that shows up when clicking on the "i" button).

I suppose the first option might be preferable but it's up to you. Any of these would be fine.

**Comment by rayrrr** [comment]
Loving this app and am looking for this feature as well. From a UI perspective, might I suggest renaming the existing "metadata" pane to "technical metadata" and then creating a new pane called "content metadata" or similar for the Character Count (as well as Word Count and any other useful info like that)? Just those two data points would be a great start.

**Comment by taw00** [comment]
Note: It would be worth looking at how other editors do the same thing. I just used GEdit as an example. Here are other examples (906 words and 6103 characters): Atom, Google Docs, and LibreOffice (I find it interesting that LibreOffice and Atom came up with a different character count -- probably counting newlines or some such). Note: the wordcount for Atom is on the bottom status line.

![wordcount-atom-via-atom-wordcount-package](https://user-images.githubusercontent.com/6908872/67791553-046a9e00-fa4e-11e9-9191-9ada5ffede89.png)
![wordcount-google-docs](https://user-images.githubusercontent.com/6908872/67791548-02084400-fa4e-11e9-8e11-03a1fd063e1f.png)
![wordcount-libreoffice](https://user-images.githubusercontent.com/6908872/67791549-03397100-fa4e-11e9-964b-427f9af8fbad.png)

**Comment by gorf** [comment]
This feature is very useful. Now I write articles at joplin and paste it to other editor like gedit or word to count word.

**Comment by rayrrr** [comment]
Sounds like we have total buy-in here. We know we agree on the "what" so let's agree on the "how" next. This looks to be a great option: https://sacha.me/Countable/ and if no one makes a PR by the new year I will try.

**Comment by jdrobertso** [comment]
I would like to give this a try, unless someone else is working on it.

I don't think Countable is going to be the best choice here, because the React-Ace library doesn't make it easy to find just the text, since it's split up into multiple elements. However, I think I could add a couple of functions to the NoteText object to create a dialog that contains a count of words, characters, and characters excluding spaces.

**Comment by rayrrr** [comment]
@jdrobertso go for it!

**Comment by jdrobertso** [comment]
I am not sure the best icon to use here, @laurent22 do you have any input? The one I added is on the far right.

![image](https://user-images.githubusercontent.com/3140223/73806503-47e05100-478f-11ea-89b7-61be416af441.png)

I am not sure about the 'Paragraphs' section, it gets a bit weird with list items. But it is again another design decision that I'm not sure of. I could use your help here as well, @laurent22 .

![image](https://user-images.githubusercontent.com/3140223/73806412-12d3fe80-478f-11ea-9080-e13decfc8065.png)

**Comment by AdamIsrael** [comment]
Ideally, I'd love to have the word count in a status bar on the bottom of the Joplin window. For those of us writing to length, it's nice to have a realtime counter rather than having to navigate the menu or use a short-cut key to see the information.

**Comment by AdamIsrael** [comment]
One other thing that should be considered in the word count: not counting comments.

For example, as I write I use comment blocks to outline or leave notes to myself. For the word count, though, I'm only interested in the count of the rendered text.
