### ISSUE TITLE
main website bug: `Persian` flag  image is not loading

### ISSUE THREAD

**Issue by mgrandi** [laurent22/joplin#1605]
As of 2019-05-28, on the `https://joplinapp.org/` website, if you scroll down to the languages, the flag for `Persian` is not loading. According to "right click -> view image info" in firefox, it says the url is `https://joplinapp.org/images/flags/country-4x3/.png`, but that seems wrong since the other flag image urls are of the format `https://joplinapp.org/images/flags/country-4x3/us.png`

![screenshot_1284](https://user-images.githubusercontent.com/802786/58522207-18933200-8174-11e9-92ff-2f334e7cf4e2.png)

**Comment by tessus** [comment]
Thanks, it's fixed.
