### ISSUE TITLE
No notebook hierarchy drag&drop anymore

### ISSUE THREAD

**Issue by MM2forever** [laurent22/joplin#1607]
### Operating system

- Windows

### Application

- Desktop

Im getting the phenomena that in current version 1.0.158 win32 prod its not possible to drag and drop notebooks to change their position in the hierarchy anymore. The "paste"-icon or whatever usually appeared just briefly pops up and dissappears and I cant move the notebook no matter what I do.

Edit: Its also not possible to drop Tasks or Notes into Notebooks, so no drag & drop at all anymore.

I compared it to a client where I still have 1.0.157 on and it still works there.
Just to do everything right I tried to give you the console output from debugging mode when reproducing the error, but nothing shows up there.

Little extra:
Regarding your instructions at https://joplinapp.org/debugging/
I think its midly weird that you ask to put that flags.txt in that .config folder that is also only possible to create via the mkdir command on Windows because this is not a proper foldername instead of calling the Joplin exe with those parameters. Also using that flags.txt in my profile didn't even work btw.

**Comment by tessus** [comment]
I can't reproduce the problem, but I don't have a Windows machine. However, the code is the same for all desktop versions.
There were no code changes between 1.0.157 and 1.0.158 that have anything to do with what you are describing.

**Comment by MM2forever** [comment]
I am really sorry, yes it seems that this was just an issue of my windows enviroment and I was to quick to file a bug report where I should have tested a bit more.
