### ISSUE TITLE
Can't synchronize joplin between devices?

### ISSUE THREAD

**Issue by originalnickname** [laurent22/joplin#1608]
### Operating system
- Linux
- Android

### Application
- Desktop
- Mobile

I don't know if this was already addressed:

I can't synchronize joplin between devices.
it does synchronize with nextcloud.

I use the same webdav url, username and password between devices however the devices do not synchronize.

is it possible to synchronize joplin between devices?
thanks

**Comment by tessus** [comment]
Please use the forum for user questions. https://discourse.joplinapp.org/

Reading the documentation and FAQ would answer all your questions.
