### ISSUE TITLE
dark theme: readability of days

### ISSUE THREAD

**Issue by merlinuwe** [laurent22/joplin#1609]
### Android 
all releases of Joplin
 since this function was added. 
Also with at least Windows 10. 

![Screenshot_20190529_222115_net cozic joplin](https://user-images.githubusercontent.com/4138869/58588753-aa786900-8260-11e9-86dd-8e58b83c1843.jpg)

The amount of days should be white, not black. One cannot read the number and the text "91 Tage".

**Comment by laurent22** [comment]
Thanks for reporting this bug, it will be fixed in the next release.
