### ISSUE TITLE
Joplin tries to contact Amazon AWS

### ISSUE THREAD

**Issue by acicovic** [laurent22/joplin#1610]
Hello there,
I'm testing the Windows portable version. Auto-updates and sync are disabled.

Each time I add a to-do or a note, Joplin tries to contact Amazon AWS at different IP addresses. For example:

54.225.171.237
23.21.121.219
50.16.229.140
54.243.198.12

I find this rather puzzling. Can anybody explain what's happening?

**Comment by laurent22** [comment]
When you add a note, it gets the geo location from a server, but it's strange there are so many ips. Are you sure it comes from Joplin? What if you disable geo location in the options?

**Comment by laurent22** [comment]
And do you have something to check the payload? It should be a GET query.

**Comment by acicovic** [comment]
Well, I had missed the geolocation setting. I don't have a tool to monitor the payload but turning the setting off stopped the requests.

Perhaps it tried several IPs because it was getting blocked, or if you're using a ready made package perhaps there's a file with a list of IPs? These are just guesses. It's clear though that all these IPS belong to Amazon AWS and that they were initiated by Joplin.

I'm closing this but if you want to research the multiple IPs issue feel free to re-open this.

Thanks!
