### ISSUE TITLE
Sync on Linux with Nextcloud via webdav not seeing notes

### ISSUE THREAD

**Issue by mostlybob** [laurent22/joplin#1615]
### Operating system

- (Windows)
- Linux
- (Android)

### Application

- Desktop

I have clients running on Windows, Android and Linux. Recently, I reinstalled Linux on my laptop and installed Joplin. I have all three pointed at the same webdav address on a Nextcloud instance. I also have encryption enabled. Prior to the reinstall, the Linux install of Joplin I had running synced everything as expected. Since the reinstall, however, the Linux client is not seeing any of the notes. 

My Android client sees the key(s) created by the Linux client, but doesn't see the notebooks/notes created on the Linux client. The other clients don't see notes created on the Linux client either.

**Comment by tessus** [comment]
Can you please post support questions in the forum?

https://discourse.joplinapp.org/

**Comment by ezy** [comment]
I came here looking for answers to nextcloud sync issues on ubuntu with the Joplin client. I had a nextcloud server with 1Gb of joplin notes in a /joplin sub-dir, but Joplin was saying no notes were detected. I solved the issue by switching the synchronisation target in Joplin settings from "nextcloud" to "webdav" and Joplin synced properly.
