### ISSUE TITLE
Syncing issue on PC (Windows, Linux)

### ISSUE THREAD

**Issue by 101lols** [laurent22/joplin#1617]
### Operating system

- Windows
- Linux

### Application

- Desktop

I have Joplin installed on Linux (Pop_OS) and Windows 10. And I have the same problem on both of them. Here is what happened with Windows 10.

It's basically the client isn't syncing, and keeps printing **Created remote items: 1.**
Nothing gets synced after this bug gets triggered.
The unsynced changes are:
- A edit to a note
- A new to-do
- A change to a to-do from another device (and the change have been synced with Dropbox)

[Here is the log.txt](https://github.com/laurent22/joplin/files/3245307/log.txt)

I use Dropbox for syncing, and E2EE encryption.
Edit: Just saw that the encryption config page is *empty* ![Screenshot of encryption config](https://user-images.githubusercontent.com/29000894/58768173-7faf4d00-859f-11e9-9fcb-f275a0669e24.png)

I didn't care to report it when it happened on Linux a couple hours back (new to Linux).
I don't know what triggers the problem.

**Comment by mostlybob** [comment]
hi 101. I got redirected to the support forum, so I'm going to take this over there. Good hunting! https://github.com/laurent22/joplin/issues/1615#issuecomment-498058715
