### ISSUE TITLE
feature suggestion: add GIT as storage backend + GPG for encryption

### ISSUE THREAD

**Issue by glowinthedark** [laurent22/joplin#1619]
How feasible would it be to add GIT as a remote storage backend and GPG for notes encryption similar to how [passwordstorage](https://www.passwordstore.org/) does it? 

This would allow delegating the transportation, versioning and encryption to already existing tools which are well tested and supported by an established community.

Has this already been considered and were there any arguments pro/against it?

**Comment by tessus** [comment]
Maybe this topic would be better in the forum?

**Comment by laurent22** [comment]
That's not technically possible at the moment.
