### ISSUE TITLE
Script tag breaking markdown rendering

### ISSUE THREAD

**Issue by dddjjjbbb** [laurent22/joplin#1620]
### Operating system

- macOS

### Application

- Desktop

Unfortunately debugging yielded no meaningful output for me.

The following markdown renders only without the opening `<script>` tag in the heading, is this expected?

# In spotifyLoginFinish.html's <script>:

```
$('document').ready(function(){
        //i leave 'parseHash()' as an exercise for the reader, all it does is take the uri string(see above ex of what this looks like) and get the access_token from it
        var spotifyAccessToken = parseHash(String(window.location.hash));
        //you must clear localStorage for main page listener to trigger on all(including duplicate) entries
        localStorage.clear();
        localStorage.setItem('accessToken', spotifyAccessToken);
        window.close();
});
```

**Comment by laurent22** [comment]
The Markdown renderer supports HTML so while it won't execute any script it still process `<script>` as an HTML tag. To prevent this, you can escape it like this;

`# In spotifyLoginFinish.html's \<script>:`
