### ISSUE TITLE
Plain text passwords can be derived from password field

### ISSUE THREAD

**Issue by Abul22** [laurent22/joplin#1624]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application
- Desktop
- Mobile
- Terminal

The way the passwords are given as **********, you can delete the last character and input a known char, test if valid, and repeat on each char till you have the entire pass.
Eg. (show = known)
****
**e? [x]
**g [+]
*hg [x]
*og [+]
eog [x]
dog [+]

Solution: Don't pre-populate it...

**Comment by laurent22** [comment]
If you have access to someone's computer and have enough time to do that, you probably also have time to install a keylogger. I see what you mean but I don't see that as a massive issue at the moment since it's only possible in a scenario where the attacker has full access to your computer.
