### ISSUE TITLE
Notes not syncing on Android but no error

### ISSUE THREAD

**Issue by PopeRigby** [laurent22/joplin#1627]
I have my correct password, username, and Nextcloud WebDAV URL, but no notes are showing up in the Android app. I check the sync configuration and I get no errors. I tried an app password as well. My Nextcloud folder for Joplin is full of notes, but none of them show up.

**Comment by laurent22** [comment]
Maybe try uninstalling and reinstalling the app?

**Comment by PopeRigby** [comment]
That didn't work. It just kept saying it was fetching items but none were showing up. It even gave me a prompt to decrypt them. I have some screenshots if you think they might be useful
![](https://i.imgur.com/eIOMR4U.png)
![](https://i.imgur.com/LFOu9dy.png)
It seems to be fetching more notes than I actually have. I'm pretty sure I don't have over 300, but it was going up to 500.

**Comment by laurent22** [comment]
You need to let it finish syncing. The other items might be tags, revisions, or other things. It's not just notes.

**Comment by PopeRigby** [comment]
Really? OK. I'll let it run and see what happens.

**Comment by PopeRigby** [comment]
Alright. It finished. Still nothing there.

**Comment by xuhcc** [comment]
Could be related to #1301

**Comment by PopeRigby** [comment]
I made a new Nextcloud account and transferred the notes over. The previous account had the same email, so I changed that to something else. Connected my new account up to Joplin and synchronized. Still nothing. Could my notes be corrupted or something?

**Comment by laurent22** [comment]
So everything is downloaded and decrypted? What does the status screen say?

**Comment by PopeRigby** [comment]
![](https://i.imgur.com/aWzJOGq.png)

**Comment by PopeRigby** [comment]
![](https://i.imgur.com/eiyw2zh.png)

**Comment by laurent22** [comment]
There's probably an error in the log, could you check? https://joplinapp.org/debugging

**Comment by PopeRigby** [comment]
I exported the debug log. [Here](http://distbin.com/activities/450ec04d-2c03-46ae-aecc-d162950e21d3).

**Comment by laurent22** [comment]
From the look of it it's working, but there's just no notes or notebooks on the sync target. Does it work if you sync with a desktop app?

**Comment by PopeRigby** [comment]
No, desktop doesn't work either. I definitely have notes in that exact Nextcloud directory.
![](https://i.imgur.com/EmWuxcL.png)

**Comment by laurent22** [comment]
The .md file might just be revisions, you don't have any notes or notebooks in there. You might want to restore from a previous backup or device if you have your notes somewhere in there.
