### ISSUE TITLE
[Feature request] Add new sub-notebook or note in right click menu

### ISSUE THREAD

**Issue by v-marinkov** [laurent22/joplin#1629]
### Operating system
- Linux

### Application
- Desktop

### Feature
Allow for adding a new sub-notebook by right-clicking on an existing notebook. Right now it the context menu only shows _Delete_, _Rename_ and _Export_. It would be great to have a _Add sub-notebook_ entry or similar as well.

This could also be useful for notes as a _New note_ entry, but it is less of an issue.

**Comment by Dasymi** [comment]
Yes, would be great in Windows too. It's quite a pain to have to go searching for a newly created sub-notebook to then drag it into another location.

**Comment by gerroon** [comment]
I asked for the same thing last year, feel free to follow that one too

https://github.com/laurent22/joplin/issues/898

**Comment by laurent22** [comment]
Duplicate of #898
