### ISSUE TITLE
[UI request] swap the buttons for new note and notebook

### ISSUE THREAD

**Issue by v-marinkov** [laurent22/joplin#1630]
### Operating system
- Linux

### Application
- Desktop

### Request
I think it makes much more intuitive sense if the _New note_ button is on the right above the notes sidebar and _New notebook_ is on the left above the notebooks sidebar.

Thanks!

**Comment by tessus** [comment]
If you toggle the sidebar, or resize the notebooks and/or the note list, none of your statements are valid anymore.

**Comment by v-marinkov** [comment]
Yes, but why would I press the _New notebook_ button if the notebooks sidebar is hidden?

**Comment by laurent22** [comment]
As tessus said, the toolbar and sidebars are two independent control so there's no alignment or dependencies between both. If we were to redesign the toolbar and sidebar (maybe we should) it would be a big change which would need to be discussed properly on the forum, so for now I'm closing this.

**Comment by v-marinkov** [comment]
I was expecting this response and understand the concern. I will move the discussion to the forums then. Thanks
