### ISSUE TITLE
wrap meta data into code block?

### ISSUE THREAD

**Issue by vlaw** [laurent22/joplin#1635]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

IMHO, moving the meta data into a special type code block(like below) will make the md file looks more readable in other APPs like OneDrive.

<pre><code>
```joplin
id: 019636767d244c989370fd2e9aaed56b 
created_time: 2018-12-18T10:02:03.375Z 
updated_time: 2018-12- 18T10:02:03.375Z 
user_created_time: 2018-12-18T10:02:03.375Z 
user_updated_time: 2018-12-18T10:02:03.375Z 
encryption_cipher_text: encryption_applied: 0 
type_: 5
```
</code></pre>

**Comment by innocuo** [comment]
There's been similar suggestions to change improve/change the metadata section. It looks like you suggestion is to make it easier to display the file, while others are about making it easier to edit the file with other editors. Either was, this would be a change in Joplin's file format.

@laurent22 has mentioned multiple times that the file format won't change. So I'm going to close this issue.

For reference, you can read issues #508 and #264 (#1080 is also related to this type of change).
