### ISSUE TITLE
Android Webclipper

### ISSUE THREAD

**Issue by Gankaku** [laurent22/joplin#1636]
I'm having some issues with the webclipper on Android. It works fine on my PC.

I have it installed for Firefox. I know Chrome doesn't have addons. I have tried it for Kiwi (my preferred browser) but there's a strange error and I figured it didn't work.

However, the clipper installs to FFX, it just says at the bottom of the clipper (when I try to clip a page) Service status: Not found. There's no way to clip anything to notebooks (nothing selectable) or to clip anything (nothing happens).

When I go to Help, I've either checked the suggestions okay (like, Webclipper on desktop running) or the items are not applicable. Not clocked by firewall or proxy. So I've come to report it like suggested.  I cannot seem to debug in Firefox on Android (doesn't work and not sure if it can for Android?) 

I really need help with this if I'm to use the app. Copy and paste is NOT copying hyperlinks from a webpage. It's just copying the links in as plain text.

Oh and Share to Joplin from Kiwi only shares a link, not the entire page with links (so I can work on a project from that page).

Thanks for any help.

### Operating system

- Android

### Application

- Mobile

**Comment by laurent22** [comment]
WebClipper is not supported in Android and it's unlikely it will be.
