### ISSUE TITLE
[Bug] Undo action in notes exhibits strange behavior  

### ISSUE THREAD

**Issue by desk7** [laurent22/joplin#1642]
- Windows 10
- Desktop

When Ctrl-Z is pressed, the last action *in note* should be undone and the prompt should position itself where the change occurs. But it doesn't work when you use buttons in toolbar. 
How to reproduce the bug:
- click on any button of toolbar (Bold, Italic, Hyperlink, code, numbered list, bulleted list, checkbox, Heading, Horizontal rule, Date & time)
- press Ctrl-Z
- the prompt never positions itself where change occurs but all the text in the note gets selected
- in addition, with some buttons, undo doesn't work.

**Comment by alinuxfan** [comment]
Confirming same behavior in Linux

**Comment by hb20007** [comment]
This also happens if keyboard shortucts (e.g., `Ctrl` + `B` for bold) are used instead of toolbar buttons.

**Comment by Perkolator** [comment]
Not fixed. Do not close. (damn that bot is annoying)

**Comment by siddhugolu** [comment]
Confirming that this is still happening. Can reproduce across all the desktop platforms - Linux, Windows and Mac.

**Comment by superfreeman1989** [comment]
I just started trying Joplin today and this is the very first annoying thing I noticed. Ctrl-Z loses my focus and brings me to end of document.

**Comment by Perkolator** [comment]
Still relevant.

**Comment by siddhugolu** [comment]
Please don't close this issue. It's still relevant.

**Comment by Snaxeko** [comment]
Sooo after 1 year, is this a bug, or an intended behavior ?

**Comment by hb20007** [comment]
Not fixed

**Comment by hb20007** [comment]
Not fixed.

**Comment by hb20007** [comment]
Not fixed.

**Comment by hb20007** [comment]
Not fixed.

**Comment by hb20007** [comment]
Not fixed.

**Comment by hb20007** [comment]
Not fixed.

**Comment by hb20007** [comment]
Not fixed.

**Comment by hb20007** [comment]
Not fixed.

**Comment by hb20007** [comment]
Not fixed.

**Comment by hb20007** [comment]
Not fixed.

**Comment by roman-r-m** [comment]
I can't reproduce this, neither in markdown editor nor in Rich Text mode.
Can you post a screenshot or a video?

**Comment by hb20007** [comment]
@roman-r-m You are right, it seems to have been fixed between v1.0.245 and v1.1.1. I believe this issue can be closed.

**Comment by roman-r-m** [comment]
Thanks for confirming!
