### ISSUE TITLE
[mobile] Ability to keep the app running in background

### ISSUE THREAD

**Issue by keymaker91** [laurent22/joplin#1645]
### Operating system

- Android
- iOS

### Application

- Mobile

### Problem

Start up time is slow. If you mistakenly close Joplin and not leave it running in background, start up time before you can add a note is long. Not to mention you need to wait for sync as well if you are trying to access a note that was updated/created on desktop. I tend to open Google Keep instead, then move the notes at the end of the day. Albeit, I am experiencing this on an older Android phone - Xperia Z3.

### Solution

Add a field in mobile config to keep the app running in background, keep Joplin running even after you close the app and keep syncing as well.

Not sure how easy or possible is this.

**Comment by laurent22** [comment]
Most likely not possible. Android phones these days have services that kill off apps that aren't used, whether you want to keep them running or not. https://dontkillmyapp.com/
