### ISSUE TITLE
Problem with encrypted attachments

### ISSUE THREAD

**Issue by satoroboto** [laurent22/joplin#1646]
I have my Joplin directory in Cryptomator. I have also tried to use the encryption built into Joplin. My problem is, when I click on an attachment that I have added to a note, it points to an unencrypted file on my local drive. Is there a way to point to the original file, which lives in a vault that I can lock?

Thank you very much for any help!

### Operating system

- Windows

### Application

- Desktop

**Comment by laurent22** [comment]
In that case, you need to manually link to the file using something like `[my file](file:///path/to/file)`. But of course that file won't be synced or managed by Joplin in any way.

**Comment by satoroboto** [comment]
Is there any way to manually set where pdfs and other attachments brought into Joplin live instead of C:\Users\YOUR_NAME\.config\joplin-desktop\resources

**Comment by laurent22** [comment]
The best is to use the portable app, in which case the settings will be wherever you put the executable, so you can put it for example on an encrypted drive.

Otherwise you can use the unsupported `--profile` argument to specify a different profile path.
