### ISSUE TITLE
Joplin freezes/lags when typing in a large note

### ISSUE THREAD

**Issue by mgrandi** [laurent22/joplin#1649]
### Operating system

- macOS

### Application

- Desktop (Joplin 1.0.159 (prod, darwin))

It seems that having a large note, and then typing in it, even with the layout set to not show the rendered HTML view, it lags when typing for a few seconds every so often. The note is only 500 lines long, but it does contain a few large blocks of text that are preformated (triple backticks) , that are the console log for something I was working on for work. I can sanitize or create a example file if needed

I enabled the developer tools and took a performance profile and the purple spikes on it seem to correspond to when the lag / freezes happen

Screenshot and the saved profile (you can right click in the performance pane in the dev tools and select "load profile" after extracting the .json file from the tarball)) are attached

![screenshot_1294](https://user-images.githubusercontent.com/802786/59463034-d7d52300-8dd9-11e9-8055-5df38f0f4e14.png)
[Profile-20190613T124430.json.tar.gz](https://github.com/laurent22/joplin/files/3287871/Profile-20190613T124430.json.tar.gz)

**Comment by laurent22** [comment]
Yes if you could create an example note that shows the issue that would be great.

**Comment by mgrandi** [comment]
here is a archive file with 2 notes i experienced it in (including one where i just copy and pasted lorem ipsum over and over) and the chrome dev tools profile json


[joplin_lag_bug_bug1649.tar.gz](https://github.com/laurent22/joplin/files/3303426/joplin_lag_bug_bug1649.tar.gz)

**Comment by SkyWheel** [comment]
Hmmmm... I'm experiencing similar issue but in Joplin for Android

**Comment by mgrandi** [comment]
The "lorem ipsum' test one doesn't really show it, but looking at the performance test for the other one, it shows some red bars saying :

WARNING: [Forced reflow](https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing#avoid-forced-synchronous-layouts) is a likely performance bottleneck.

and references this:

```
maxScrollTop | @ | /Applications/Joplin.app/Contents/Resources/app/gui/note-viewer/index.html:246
-- | -- | --
```

**Comment by laurent22** [comment]
There was indeed an optimisation to make by caching the code blocks. In my case it went from 800ms per rendering to 15ms, so about 50 times faster.
