### ISSUE TITLE
Can not locate correctly after switch two screen to one 

### ISSUE THREAD

**Issue by zhengxinchang** [laurent22/joplin#1650]
### Operating system

- Windows

### Application

- Desktop

I have a extend screen for my laptop computer, and I usually use joplin in my extend screen, however I can not find joplin when I use only one screen. and it seems joplin still  located in second screen even the screen had been removed.  restart joplin does not work.

**Comment by laurent22** [comment]
If you press Win+Tab it should show you all the windows and allow you to move them to the correct screen.
