### ISSUE TITLE
Right clicking a notebook should have an option to create a sub-notebook

### ISSUE THREAD

**Issue by IrosTheBeggar** [laurent22/joplin#1651]
In the desktop application you can create a notebook and drag and drop it to make a sub-notebook.  I'm working on a new project that requires a lot of sub-notebooks and it would be convenient if there was an option when right clicking a notebook to add a sub-notebook under it.

**Comment by StoltHD** [comment]
I agree with this, it would be a really useful feature...
I was actually going to create a feature request myself with this exact function.

**Comment by aritrakoley** [comment]
I would love the ability to create sub-notebooks in the android app. I don't know if this feature request should be part of this thread or I should start a new thread for "Subnotebook creation in Android app".
