### ISSUE TITLE
Can not save images from medium.com through webclipper simple mode

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [laurent22/joplin#1652]
### Operating system

- Windows

### Application

- Desktop
- web clipper

If you are reporting a bug, did you try enabling debug mode? No

I tried saving this webpage through clipper
https://onezero.medium.com/should-we-and-can-we-advertise-in-space-c8322d850dd9
The image did not get saved through simple mode ,

also while saving multiple web pages simultaneously in simple mode from different sites images do not get saved properly or do not get saved like from fossbyte.com,theguardian,thehackernews,protonmail inbox
![Screenshot_20190614-125256](https://user-images.githubusercontent.com/38154154/59491020-b04a8d00-8ea3-11e9-8e85-4d46bd5dd091.png)

**Comment by laurent22** [comment]
This is normal as this is simple so certain things aren't saved, like some images. The clipper simply use the Readability lib to clip simplified page, so any bug or comment should go on that page: https://github.com/mozilla/readability
