### ISSUE TITLE
File system sync is not working on android

### ISSUE THREAD

**Issue by xuhcc** [laurent22/joplin#1654]
### Operating system

- Linux
- Android

### Application

- Desktop
- Mobile

### Description

Steps to reproduce:

1. Start joplin-desktop 1.0.159 with fresh data directory. It will show "Welcome! (Desktop)" notebook.
2. Configure joplin-desktop to use File System sync.
3. Create new notebook and new note inside of it.
4. Wait for joplin to copy its files to sync directory.
5. Copy sync directory to android device (I'm using Syncthing for that).
5. Start joplin-android 1.0.261 with fresh data directory. There will be "Welcome! (Mobile)" notebook.
6. Configure joplin-android to use File System sync, select sync directory received from desktop.
7. Hit sync button.

Result:

Notebooks from desktop are not appearing. The journal contains the following error:

```
06-14T14:57:16,30,"""Total resources: 3""
06-14T14:57:16,30,"""Total folders: 1""
06-14T14:57:16,30,"""Total notes: 4""
06-14T14:57:16,30,"""createRemote: 1""
06-14T14:57:16,30,"""Operations completed: ""
06-14T14:57:16,10,"""Error: Error: ENOENT: no such file or directory, open '/storage/emulated/0/Sync/joplin-test/84fcd68288b646aaa095d10f2b8f3afe.md'. Path: /storage/emulated/0/Sync/joplin-test/84fcd68288b646aaa095d10f2b8f3afe.md
Code: ENOENT
value@index.android.bundle:1144:328
index.android.bundle:1144:4003
k@index.android.bundle:144:3838
index.android.bundle:144:4912
index.android.bundle:144:4020
k@index.android.bundle:144:3838
n@index.android.bundle:144:4070
index.android.bundle:144:4248
f@index.android.bundle:109:155
index.android.bundle:109:882
index.android.bundle:112:1815
y@index.android.bundle:112:657
C@index.android.bundle:112:1021
callImmediates@index.android.bundle:112:3216
[native code]
value@index.android.bundle:25:3011
index.android.bundle:25:1402
value@index.android.bundle:25:2703
value@index.android.bundle:25:1372
[native code]
value@index.android.bundle:25:1307
[native code]""
06-14T14:57:16,30,"""Starting scheduled sync""
```

**Comment by xuhcc** [comment]
Solved by adding SD card permission. Does it make sense to show a more specific error to user in this case?

**Comment by laurent22** [comment]
> Solved by adding SD card permission. Does it make sense to show a more specific error to user in this case?

If you can find how to do that, then yes. Otherwise we could at least mention it in the FAQ.
