### ISSUE TITLE
Add a password verification field when enabling E2EE

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#1656]
### Application

- Desktop

In Encryption Options, when enabling encryption, the dialog box asks the user to input the master key password. We should add a second field to ask to confirm the password.

Then when the user clicks OK, the code should check if the passwords in the two fields match. If they don't, both fields should be cleared and the user should enter the passwords again.

The proper way would be to create a custom dialog for it, or a component, which does password, second password and confirmation, all in the same place.

**Comment by tessus** [comment]
@laurent22 if the fields are HTML input fields, isn't there a show password option directly in HTML? Or is this functionality something else?

I would prefer a "show password" icon next to the input field, but that's just a personal preference. If you insist on 2 fields, how about making the "Ok" button only active when both fields contain the same value?
Without any feedback, it would be confusing for the user, if their input were cleared and you had to start over.

Input masks use different hints, like a green check mark, if the passwords are equal, or a red X, if they are not. 
Or a grey text below the second input field that says "Enter password again for verification.", which changes to "Passwords are not the same." as soon as you start typing characters into the second input field, until they are the same by which time it should say "Passwords match. Ok.".

**Comment by sciurius** [comment]
I'd strongly prefer to (also) have the 'show password' eye. Not just here, but also when entering the password later (and this applies to all passwords, e.g. cloud passwords).

I've seen situations where the system suddenly decided to upcase the first letter of the password. It can take a long time to find out why the password that you are 100% sure you typed correctly is not accepted...

**Comment by tessus** [comment]
> the system suddenly decided to upcase the first letter

yep, that's why I thought the "show password" feature would be more useful...

**Comment by laurent22** [comment]
Step 1 is adding two fields. In another issue we can add the "Show password" feature. I'm trying to keep this simple because it's a "good first issue".

**Comment by slowdog12** [comment]
Very sound advice.

**Comment by slowdog12** [comment]
Enjoyed this issue.

**Comment by CharlieRoseMarie** [comment]
I would like to jump into the codebase to help contribute. Mind if I snag this issue to work on?

**Comment by tessus** [comment]
Nope, have fun! It's first come, first served. ;-)

**Comment by dietercastel** [comment]
Wouldn't this be just as useful in the terminal application? That might even lower the bar for a hacktoberfest contribution. ;-)

Maybe you could also provide a couple pointers where to look since you're so familiar with the codebase. These hints might further lower the bar for contributions, @laurent22. Anyway kudos to all the contributors here!

**Comment by dietercastel** [comment]
E.g. this might be a good pointer for the Desktop App: https://github.com/laurent22/joplin/blob/5db7502fe475343af98ebd8501b314ba36e426a9/ElectronClient/app/gui/EncryptionConfigScreen.jsx

**Comment by laurent22** [comment]
@dietercastel, this is true but I think implementing this for the three apps might be a bit too much for a "good first issue". Let's say if someone can implement this for any of the three apps that's a win already, and we can maybe create new issues later for the other apps.

For desktop, you've indeed pointed to the right file.

**Comment by nathanleiby** [comment]
I made a PR for just the desktop app change, here: https://github.com/laurent22/joplin/pull/1936

**Comment by laurent22** [comment]
For information, the desktop part still need to be done if someone is interested. Have a look at @nathanleiby PR as you might be able to re-use some of the code: https://github.com/laurent22/joplin/pull/1936

**Comment by sciurius** [comment]
Can someone disable that stupid stale bot?

**Comment by tessus** [comment]
@sciurius not really. As you can see nothing has happened for 90 days. So either someone works on it or this issue will be closed. We can also mark it so that the stalebot won't touch it.
Either way, the stalebot stays. This project is getting to big to handle the issues manually.

**Comment by sciurius** [comment]
While this is a reasonable assumption for bugs (certain kinds of bugs -- the ones that are waiting for additional input or resources), I think it doesn't really apply to feature requests. These can sit for longer periods of time in open state until someone takes a shot at them.
Closing a feature request means it gets lost.

**Comment by tessus** [comment]
@sciurius I partly agree. But if nobody picked it up in 90 days, noone will pick it up later. That's why a feature request should be discussed on the forum first. Only accepted FR should be added to gh.

However, I believe this one is an accepted one, so it won't be closed by the stalebot.

**Comment by sciurius** [comment]
Thanks!

**Comment by anjulalk** [comment]
I'd like to fix this issue on the Desktop client. Correct me if I'm wrong, but since the library that is used to display prompts ([smalltalk](https://www.npmjs.com/package/smalltalk)) does not support this use case, I see two options here. 

Either we can replace it with another library and rewrite alert, confirm and prompt dialogues, or we can use another library just for this specific use case.

I think replacing the library would be a good idea. [react-modal](https://www.npmjs.com/package/react-modal) seems like a good candidate. What do you guys think?

**Comment by tessus** [comment]
I'm not sure, if @laurent22 wants 2 packages, so if react-modal can do what smalltalk is (without too many UI design differences), I don't see a reason why we shouldn't replace smalltak.

But ultimately it's Laurent's decision.

**Comment by jerrybuks** [comment]
would Love to work on this issue, can I

**Comment by anjulalk** [comment]
Replacing smalltalk with react-modal turned out to be quite a complex task since smalltalk is promise-based and react-modal is a component.
I suggest a simpler approach as in the following screenshot.
![image](https://user-images.githubusercontent.com/26695184/75167955-2817c980-574c-11ea-99ca-91835ab1dae6.png)

Both password, and confirm password fields are right in the encryption config screen.
@laurent22 I'll start working on this, if this is fine.

**Comment by marwanatef2** [comment]
Are you still working on this issue? @anjulalk 
If not then i'd like to work on it.

**Comment by anjulalk** [comment]
No, please go ahead!

**Comment by nmagoulis** [comment]
Hello there,
Is anyone working on this issue? I'd like to work on it together with a colleague of mine, in the terms of a University Assignment for contribution to oss. Thus, we strongly look forward in contributing to Joplin.
Thanks in regard,

**Comment by marwanatef2** [comment]
No, you can go ahead. @nmagoulis 
But notice that "smalltalk" library which is used to make the dialog in the file below only prompts the user for one input per time, so popping up a dialog with two inputs will require using another library.
https://github.com/laurent22/joplin/blob/5db7502fe475343af98ebd8501b314ba36e426a9/ElectronClient/app/gui/dialogs.js

**Comment by kowalskidev** [comment]
I'm working on it

**Comment by kowalskidev** [comment]
I was looking for good libraries to create good modal dialogs and found this package: https://github.com/trendmicro-frontend/react-modal 
which I think this package is a good candidate for creating password prompt dialog and also package has good design and features

@laurent22  Should I add this package to create prompt dialog ? Or you can suggest a better way to achieve the same.

**Comment by zozolina123** [comment]
Is this issue still relevant?
If it is, can you provide some directions for how we should implement the feature?
As pointed above smalltalk doesn't allow for a good UX as it only takes one input at a time.
Is using a package like react-modal a good approach if we style it like a smalltalk dialog?

**Comment by zozolina123** [comment]
I would like to work on this, I think I can come with a good solution.

**Comment by roman-r-m** [comment]
Just go ahead, no one seems to be working on it at the moment.
