### ISSUE TITLE
Feature - Associate TODO notes with date

### ISSUE THREAD

**Issue by Abijeet** [laurent22/joplin#166]
### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [x] Android
- [x] iOS

### Application

- [x] Desktop
- [x] Mobile
- [x] Terminal

I'm the creator of a pretty small TODO app called [Pustam](https://github.com/Pustam/app). I spent quite a bit of time on it and it meets almost all my needs so I've been using it all this time. 

When Joplin came out, I gave it a try and it had a lot of things that I **wanted** to have in Pustam but could not implement.

1. Encryption
2. Search
3. Synchronization
4. Works on Android

But there is one thing that is missing that I feel is needed in a TODO app, that is the concept of dates. 

My workflow with Pustam is as following,

1. Have a daily notebook.
2. Create notes with dates attached to them. Notes in the future can also be added.
3. Marking a note as done. This ensures that the note does not come forward the date to the next day.

This allows me to maintain the same notebook for my daily use. It also allows me to go back and see when I completed a certain note. It also acts as a reminder where the thing that I've to do in the future automatically appear in my notebook on that date.

I'd like this feature in Joplin but I'd understand if this does not meet your plans for the application. This would be quite a big change.

If you are OK with this feature being added, I will review with you my plans for implementing it, and then work on it.

Finally, I'd like to thank you for your work on this application.

**Comment by laurent22** [comment]
This is indeed a very specific workflow. I guess it could be work out in a more generic way: by adding something like "Smart Notebooks" which would display notes according to specific criteria (in this case, notes where the date is today's date).

Then we'd need something like a "due date", which is the property that would need to be added.

**Comment by Abijeet** [comment]
There would not only be a due date but a completed date as well. I don't see the point of displaying notes to a user beyond the date on which they were completed.

This makes the notebook more like a diary with dates where,

1. I can put notes for the future
2. I can refer to my past work on a given date.
3. I can see and focus on only things that I've to do for today.
4. If I can't finish a note on a given day, its automatically there on the next day as well.

Regarding the name, we may use "Diary" itself, or we could name it as "Smart Notebook" too.

Oh and I forgot to mention one more thing that I like about Joplin, Reminders. :)
