### ISSUE TITLE
New created date for duplicated notes

### ISSUE THREAD

**Issue by tristil** [laurent22/joplin#1668]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

It looks like the original created date is carried from an original note to its duplicate. I think this is probably unexpected behavior.

Use case: I maintain a journal in Joplin where each entry has some boilerplate todo items. I duplicate each item or duplicate from a template note. I was surprised when I tried sorting by created date and everything appeared in a confused order. 

Also, I'm happy to open a PR to change this behavior, but I want to confirm that setting a new created date is the desired behavior first.

**Comment by laurent22** [comment]
Yes it's indeed a bug as the created date should be changed. If you can create a PR for it, I'll accept it.

**Comment by laurent22** [comment]
You'll probably need to set autoTimestamp to false when saving the note and manually set created_time.

**Comment by laurent22** [comment]
Come to think of it, it's actually working as expected. The note should be entirely duplicated including user timestamps. It's also how files are duplicated in a file system, so we'll leave it as it is for now.

**Comment by tristil** [comment]
Hmm... okay. Sounds like I should wait for a template feature to be merged then: https://github.com/laurent22/joplin/pull/1647
