### ISSUE TITLE
Application closing on it's own on Windows 10

### ISSUE THREAD

**Issue by anirbanmu** [laurent22/joplin#167]
### Operating system

- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

---

On Windows 10, after opening Joplin, it closes automatically after around 15 seconds. It does not show any errors or anything. I can help with debugging if someone can guide me in what to look at. Any logs I can take a look at?

**Comment by alexdevero** [comment]
@anirbanmu is this happening in the latest version, v0.10.47?

**Comment by laurent22** [comment]
If it's indeed happening with the latest version please could you provide log and debug info? https://github.com/laurent22/joplin/blob/master/README_debugging.md

**Comment by anirbanmu** [comment]
@alexdevero this has happened to me with various versions (at the moment it's happening on v0.10.43). It seems like every time I update (because there's a new version) the problem disappears and then reappears after some random period of using the application (I'd say somewhere between a few days and a week).

@laurent22 I checked the console after enabling debug log-level & did not see anything being outputted.

I will give v0.10.47 a try & report back. FYI, the link on http://joplin.cozic.net/ is still pointing to 0.10.43.

**Comment by anirbanmu** [comment]
Well, as per the usual, upon upgrading to v0.10.47 the problem has for the moment disappeared. I will report back if it recurs (like it has in the past).

**Comment by alexdevero** [comment]
@anirbanmu if the problem occurs again, please try to also provide the debug log as mentioned @laurent22. That will make it much easier to replicate the issue and fix it.

**Comment by anirbanmu** [comment]
Will do.
