### ISSUE TITLE
Please consider move microblogging to Mastodon

### ISSUE THREAD

**Issue by SkyWheel** [laurent22/joplin#1670]
Just found your app. I like the approach of similar experience on all my devices.
Please join any Mastodon instance. There is big community that will highly appreciate your apps.
Thank you.

**Comment by laurent22** [comment]
We looked into it but it seems a bit complicated to automatically post our news to it (as we do for Twitter), so we won't be able to have an account on Mastodon at this point.

**Comment by foxmask** [comment]
We are working on something for it *teasing* 🤫

**Comment by foxmask** [comment]
You can now follow us on mastodon @joplinapp@mastodon.social
