### ISSUE TITLE
Image attachments not downloading on Joplin for iOS

### ISSUE THREAD

**Issue by n00b12345** [laurent22/joplin#1677]
### Operating system

- iOS

### Application

- Mobile

On iOS, file attachments don’t download and show up as a blank box (screenshot attached).

![IMG_0417](https://user-images.githubusercontent.com/17707852/59784521-41749600-92e0-11e9-96f3-d70ad8a88626.jpeg)

On Android, the same notes show up just fine. 

Could you please look into it?

Thanks. 

Edit:

Actually iOS attachments don’t work. When I attach a photo to a note, this is what I get:

![IMG_0418](https://user-images.githubusercontent.com/17707852/59788381-34a87000-92e9-11e9-8616-253c3694555f.png)

Kindly look into it.

**Comment by laurent22** [comment]
Could you try the latest version on app store and let me know if it works?

**Comment by n00b12345** [comment]
> Could you try the latest version on app store and let me know if it works?

Everything is working as expected again. Issue resolved after the update. Thank you *so* much!
