### ISSUE TITLE
Reminders do not show notifications

### ISSUE THREAD

**Issue by h-b** [laurent22/joplin#1678]
I just saw that https://github.com/laurent22/joplin/issues/321 is closed, so I assume it makes sense to open a new issue.

My configuration: iPhone 7 plus, iOS 12.3.1, Joplin 10.0.35.

On iOS, sometimes a notification appears right after creating a todo that has an alarm. But there is never a notification at the time of the alarm, though in the settings Joplin is allowed to do all notification types.

This is how Joplin's iOS notification looks like: ![joplin_notification](https://user-images.githubusercontent.com/24413995/67008521-f03bae00-f0e9-11e9-9553-c801370995a5.png)

This is how a typical iOS notification looks like: 
![iOS_notification](https://user-images.githubusercontent.com/24413995/67008539-fa5dac80-f0e9-11e9-9296-bc0c0095319c.jpeg)

On iOS, notifications of various apps all look similar to the one above. I personally never saw a notification like the one of Joplin and, as explained above, it does not appear at the time of the alarm. It also does not appear in iOS' notification area. Maybe the notification library that Joplin uses on iOS does not generate native iOS notifications?

On MacOS, sometimes a notification appears at the configured alarm time. Unfortunately, even if it appeared reliably, it wouldn't be of any use, because it just appears shortly and does not appear in the notification area of MacOS, like e. g. notifications of Wunderlist. In addition, when clicking into it, Joplin does not open. My configuration: MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports) MacOS 10.14.5, Joplin 1.0.160.

Don't get me wrong, I'm really a fan of Joplin, using it for lots of stuff and I really want to use it also for todos with notifications. It's a pity that it does not work, at least in my configuration.

**Comment by foxmask** [comment]
I don't know how it's working on iOS but for me that was due to an energy saver (like you may already read here https://github.com/laurent22/joplin/issues/321#issuecomment-485236096), is there something like that on iOS that could do that ?

**Comment by h-b** [comment]
I don't use an energy saver on iOS. Indeed there are no energy saving apps available in the store, because iOS more restrictive about apps that change the system. The only energy saving possibility is the one that is built into iOS, but I never use it.

**Comment by foxmask** [comment]
on the doc https://joplinapp.org/ it's said to use 
> macOS: >= 10.8 or Growl if earlier.
I suppose you already installed it ?

**Comment by h-b** [comment]
Regarding MacOS, I put the version into my posting. It is the latest MacOS version, i. e. later than 10.8. But iOS would be more important.

**Comment by matthewb96** [comment]
On Windows 10 the reminder does not seem to be sending any notification at all. If I set the alarm it appears in the toolbar showing what time it is supposed to go off and it disappears at the set time but it  doesn't produce a sound or notification.

**Comment by PhilipVis** [comment]
> On Windows 10 the reminder does not seem to be sending any notification at all. If I set the alarm it appears in the toolbar showing what time it is supposed to go off and it disappears at the set time but it doesn't produce a sound or notification.

I have the same behaviour on macOS 10.14.6

**Comment by olasoloi** [comment]
I have the same behaviour on Joplin desktop application version 1.0.170
My computer is a Macbook Air with MacOS Catalina 10.15.1

**Comment by CypherNL** [comment]
Got the same issue on my iPhone XR running 13.2.3 with Joplin version 10.0.40.

**Comment by ANH25** [comment]
I also have the same issue on Windows 7.

**Comment by h-b** [comment]
As far as I can see, this issue is still open. So notifications do not reliably work on iOS, MacOS X or Windows 10. I justed checked them on PureOS (a Linux Debian fork) with Joplin 1.0.167. They do not work there either.
