### ISSUE TITLE
tag popup opened from shortcut not working

### ISSUE THREAD

**Issue by matse** [laurent22/joplin#1679]
### Operating system

- Linux

### Application

- Desktop

Version: 1.0.160 (prod, linux)

1. Open a note or edit existing one
2. hit `CTRL+ALT+t` to open tag edit field
3. empty tag edit field opens (even if the note has tags)
4. enter a tag
5. tab to OK or click on it
6. error in debug console appears, see file
7. tag view closes and does not reopen again, neither shortcut or mouse click

[-1561039915390.log](https://github.com/laurent22/joplin/files/3310803/-1561039915390.log)

**Comment by laurent22** [comment]
This is a known issue and will be fixed in the next release. In the meantime, it's better to only use the toolbar button to add tags.
