### ISSUE TITLE
bad md crashes joplin

### ISSUE THREAD

**Issue by jasobar** [laurent22/joplin#168]
### Operating system

- [ ] Windows
- [ ] macOS
- [x ] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [x] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---
I messed up my markdown syntax. 
I put a tripple back tick on the same line as the code. 
joplin crashed, and now won't start. crashes with error: 
```
Unhandled promise rejection Promise {
  <rejected> Error: Unknown language:`__` is not registered
```

**Comment by laurent22** [comment]
Please update the app and try again.
