### ISSUE TITLE
Embed Image

### ISSUE THREAD

**Issue by fullcavediver** [laurent22/joplin#1685]
### Operating system

- Windows

### Application

- Desktop

Please allow embeding images from clipboard or disk as base64 content. With this feature it will be possible to make a parfect personal documentation with joplin.

Thank you!

**Comment by laurent22** [comment]
Why would it make a different to embed as base64? You can also paste images and embed them but it's saved as a separate file.

**Comment by fullcavediver** [comment]
That's the problem. When I sync my documents or export to MD, I get an .md file and several attachements. That's not nice for creating a knowledge base. It is better to have a documentation sheet like this one (see attachment).

[Navigation.md.txt](https://github.com/laurent22/joplin/files/3328499/Navigation.md.txt)
