### ISSUE TITLE
REST API: notes does not support is_todo

### ISSUE THREAD

**Issue by charles-e** [laurent22/joplin#1687]
### Operating system
- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop

### Symptom 

Attempting to create a todo does not result in a todo.
> curl --data '{ "title": "My note", "body": "Some note in **Markdown**", "is_todo" : "1" }' http://localhost:27583/notes 
> {"title":"My note","body":"Some note in **Markdown**","parent_id":"f96453ec305b4b70abbda31786f85cce","source":"joplindev-desktop","source_application":"net.cozic.joplin-desktop","id":"6dab981c1a0549f6a447896884e397f0","updated_time":1561409169644,"created_time":1561409169644,"user_updated_time":1561409169644,"user_created_time":1561409169644,"type_":1}%

**Comment by hckrgod** [comment]
hmm. want some help with your issues ? i decided to get back into this stuff lil rusty but after a few days its all back i just joined to day im also doing some stuff with mozilla  also nice meeting u

**Comment by charles-e** [comment]
Sorry - slow to see your comment here.  It looks like my fix will be merged. Next time.

**Comment by laurent22** [comment]
Fixed in #1688
