### ISSUE TITLE
Some Notes not Syncing

### ISSUE THREAD

**Issue by mollusko** [laurent22/joplin#1689]
### Operating system
- Linux
- Android

### Application
- Desktop
- Mobile

### Incident
Typed several notes on Android; saved notes & hit 'Sync'; sync succeeds with no errors.

### Expected Behavior:
Open Joplin on Linux desktop, hit sync, review new notes from mobile.

### Actual Behavior:
Open Joplin on Linux desktop, hit sync; receive following feedback:
Completed: 25/06/2019 12:55
Last error: Error: On file 0f8593c3fd15406a97d2cd650ba17588.md: Unknown type: 13
Find one of the new notes, created in the past few days; do NOT find new notes made several weeks ago; do NOT find new note 'Test' created for testing this bug.

Sync Status of Desktop:

![Screenshot_2019-06-25_12-57-50](https://user-images.githubusercontent.com/7399828/60117834-ed870880-9748-11e9-9195-a57d0edb2e4b.png)

Sync Status of Mobile:

![Screenshot_20190625-125728_edit](https://user-images.githubusercontent.com/7399828/60118262-f75d3b80-9749-11e9-94ce-4be4ace46d14.png)

**Comment by laurent22** [comment]
Please get the latest version on desktop.

**Comment by mollusko** [comment]
@laurent22 Ideally that would resolve this, however two issues with that instruction:
1) Desktop app is currently set to automatically update; I ought to have to latest version by default.
2) Since #1 isn't performing as expect, I quit the app & ran your linux install instructions, ostensibly confirmed working on Ubuntu: 
`wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh \\| bash
--
`
### This also fails, due to a syntax error: missing a space before '| bash'; resolution of this syntax error allows me to update to the latest version.
