### ISSUE TITLE
Update deletes Joplin's contents from Program Files 

### ISSUE THREAD

**Issue by Carlos487** [laurent22/joplin#169]
### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---

When an update is available, the Windows 10 notification shows constantly several times. In that case I proceed to close Joplin for the update to install. Then you can't open Joplin anymore. If you check the Program Files\Joplin directory is empty. After a manual reinstalation or installation of the new update, notes and settings are found as normal.

Is there any way to disable auto-update?

I'm using Joplin in Windows 10 Professional 64-bits inside a corporate network with an authenticated proxy. Maybe the issue is related to the download of the installer contents.

Thanks for your help, and keep your amazing work Joplin is awesome.

**Comment by laurent22** [comment]
Auto-update can be disabled in the config.

It's currently based on [electron-builder](https://github.com/electron-userland/electron-builder) implementation but it seems to be unreliable and makes the app crash (another user is reporting this today), so I think I'll switch to something simpler and just prompt the user to manually install.

**Comment by Carlos487** [comment]
Thanks @laurent22 I overlooked that option. Also while trying to disable it I experienced an erratic behavior of the checkboxes in the config page. When you click the label it works perfectly but when you hit the chechbox box (square) it was erratic.
