### ISSUE TITLE
Automatic Update not working - desktop app, linux

### ISSUE THREAD

**Issue by mollusko** [laurent22/joplin#1691]
### Operating system
- Linux

### Application
- Desktop

### Expected Behavior
Desktop app is set to automatically update itself; app should update whenever a new version is available as soon as the app is launched.  This prevents sync issues due to version mismatching.

### Actual Behavior
Desktop app does not update itself, resulting in sync errors; since the app is set to automatically update, app version mismatch does not immediately occur as a viable cause of these issues despite being the sole cause of the issue

**Comment by laurent22** [comment]
I can't replicate this. For me if the option is enabled it checks for update on startup, then every x hours.
