### ISSUE TITLE
npm audit failures with v1.0.160

### ISSUE THREAD

**Issue by WhoNeedszZz** [laurent22/joplin#1693]
### Operating system

- Linux

### Application

- Desktop
- Terminal

When trying to update to this version npm is reporting many critical vulnerabilities due to the versions of dependencies being used. Please update the dependency versions of the affected packages.

**Comment by laurent22** [comment]
Yes dependencies are upgraded now and then.

**Comment by WhoNeedszZz** [comment]
Excuse me...how do you just close this issue with that kind of response? The current dependencies have at least 11 major vulnerabilities. There's no way I'm going to install this latest version if I'm going to have to accept those vulnerabilities. I asked you to UPDATE them so that the `npm audit` passes.

**Comment by laurent22** [comment]
So? Don't install it then.

And by the way, I also watch the joplin-pkgbuild repo and it's weird to come here with *demands* and at the same time insulting the person you're asking to.
