### ISSUE TITLE
notes with no tags

### ISSUE THREAD

**Issue by spirit8ball** [laurent22/joplin#1697]
is it possible to find the notes that has no tags at all?

**Comment by laurent22** [comment]
Not in an easy way. You could do it yourself with the API (Get all the notes, then get all the notes with tags, and intersect) but it's not straightforward.

**Comment by tessus** [comment]
@spirit8ball such questions are better directed to the form. Maybe someone has come up with a script that does exactly that. Who knows?
Furthermore, maybe some others find this useful and you could collaborate with others to add that feature to Joplin.
