### ISSUE TITLE
[request] copy-paste functionality for rendered markdown

### ISSUE THREAD

**Issue by ryansyah** [laurent22/joplin#170]
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal
---

Currently, I can only cmd-c, cmd-v text from within the markdown editor pane. Any attempts to cmd-c, cmd-v from the rendered markdown pane are currently ignored.

**Comment by laurent22** [comment]
Currently it is possible to cmd-c from the rendered markdown but not cmd-v since this pane is only a viewer, so it is unlikely to change.
