### ISSUE TITLE
Android app won't decrypt

### ISSUE THREAD

**Issue by boringusername99** [laurent22/joplin#1701]
### Operating system
- Android

### Application
- Mobile

I've been using Joplin for a while, but recently started migrating from Dropbox target to Nextcloud. As part of that, I ended up having to move from one Nextcloud target (which had been fully synced to across all my devices) to a brand new Nextcloud target. Not reading any docs, I did lose all my notes on one device when I synced, but restored from backup and synced everything back up to it. I now have Mac and Windows clients syncing & decrypting properly.

I have been struggling to get Android syncing properly again. To cut to the chase, I ended up deleting the app entirely and starting over from scratch. I finally seem to have everything syncing, but not decrypting. I think the screenshots below tell the whole story. I've checked the log and don't see any errors.

![2019-07-01 18 42 27](https://user-images.githubusercontent.com/1314250/60484735-6b6a7880-9c4f-11e9-9f3a-f49a233cdd48.png)

![2019-07-01 18 42 35](https://user-images.githubusercontent.com/1314250/60484744-70c7c300-9c4f-11e9-8ecb-1e01c39ddc86.png)

![2019-07-01 22 23 17](https://user-images.githubusercontent.com/1314250/60484755-758c7700-9c4f-11e9-8ad3-3d6726939e60.png)

FWIW, what led me to completely delete the app is that it was previously stuck decrypting only partway through, and multiple restarts/kills couldn't get it to advance any further.
![2019-07-01 16 12 37](https://user-images.githubusercontent.com/1314250/60484808-98b72680-9c4f-11e9-80b8-c95a79b3fb91.png)

My Mac encryption config:
![image](https://user-images.githubusercontent.com/1314250/60484841-bdab9980-9c4f-11e9-952e-82d48a638295.png)

**Comment by foxmask** [comment]
when you start to use encryption, the first sync on android is very very long
so a little patience...

**Comment by boringusername99** [comment]
I'm not sure I understand... The app is reporting that sync is complete, so it doesn't seem to be doing anything. It's now been about 16 hours and everything still looks the same as in the screenshots, so it doesn't appear the app is attempting to do anything? 

One addition - I do see the following in the log, which I assume is related but not a root cause. I'm including just in case.

```
Date,Level,Message
07-02T05:50:26,30,"""Aborted deletion of old revisions for item  because one of the revisions is still encrypted", "Error: One of the revision to be deleted is encrypted
Code: revision_encrypted
construct@[native code]
c@index.android.bundle:523:482
f@index.android.bundle:521:363
s@index.android.bundle:520:219
index.android.bundle:884:6109
p@index.android.bundle:151:423
index.android.bundle:151:1740
p@index.android.bundle:151:423
n@index.android.bundle:151:898
index.android.bundle:151:1047
f@index.android.bundle:113:155
index.android.bundle:113:882
y@index.android.bundle:118:657
C@index.android.bundle:118:1021
callImmediates@index.android.bundle:118:3216
callImmediates@[native code]
value@index.android.bundle:28:2873
index.android.bundle:28:1264
value@index.android.bundle:28:2565
value@index.android.bundle:28:1234
value@[native code]
value@[native code]""
07-02T05:50:26,30,"""RevisionService::maintenance: Done in 345ms""
07-02T05:50:26,30,"""RevisionService::collectRevisions: Created revisions for 0 notes""
07-02T05:50:25,30,"""RevisionService::maintenance: Service is enabled""
07-02T05:50:25,30,"""RevisionService::maintenance: Starting...""
07-02T05:49:55,30,"""RevisionService::maintenance: Done in 209ms""



```

**Comment by boringusername99** [comment]
I'm also finding with testing that the Mac client is not syncing properly. When I click Synchronise, it completes _immediately_ (faster than it should) and I see "Created 1 remote items" but it's not getting created and the next time I sync, it says the same thing about creating one item. I found this in the log, which seems to explain:
```

2019-07-02 06:11:37: "Setting up recurrent sync with interval 300"
2019-07-02 06:11:37: "Updating all notifications..."
2019-07-02 06:11:37: "Garbage collecting alarms..."
2019-07-02 06:11:38: "DecryptionWorker: cannot start because no master key is currently loaded."
2019-07-02 06:11:43: "Scheduling sync operation..."
2019-07-02 06:11:43: "Preparing scheduled sync"
2019-07-02 06:11:43: "Starting scheduled sync"
2019-07-02 06:11:43: "Sync: starting: Starting synchronisation to target 5... [1562073103798]"
2019-07-02 06:11:43: "mkdir .sync"
2019-07-02 06:11:43: "mkdir .resource"
2019-07-02 06:11:44: "stat 171427964db94ef7b8833436d1255282.md"
2019-07-02 06:11:44: "Sync: createRemote: remote does not exist, and local is new and has never been synced: Note: (Local 171427964db94ef7b8833436d1255282)"
2019-07-02 06:11:44: "No master key is defined as active. Check this: Either one or more master keys exist but no password was provided for any of them. Or no master key exist. Or master keys and password exist, but none was set as active."
2019-07-02 06:11:44: "Sync: finished: Synchronisation finished [1562073103798]"
2019-07-02 06:11:44: "Operations completed: "
2019-07-02 06:11:44: "createRemote: 1"
2019-07-02 06:11:44: "Total folders: 6"
2019-07-02 06:11:44: "Total notes: 3497"
2019-07-02 06:11:44: "Total resources: 236"
2019-07-02 06:11:44: "Setting up recurrent sync with interval 300"
2019-07-02 06:11:56: "ResourceService::indexNoteResources: Start"
2019-07-02 06:11:56: "ResourceService::indexNoteResources: Completed"
2019-07-02 06:11:56: "ResourceService::deleteOrphanResources:", "[]"
```

Sync status also reports Masterkey: 0/0

Finally, encryption config shows encryption enabled, but no keys. The other screenshot I showed above is the encryption config from the Windows client.

I've been using Joplin for about 9 months always with encryption, so I'm puzzled as to why this is happening now. From reading the docs, it seems like I should be getting a prompt for a password to unlock the master key after it syncs.

What's the best way to proceed here?

**Comment by laurent22** [comment]
From your status screen, there's no master key on the Android app so it indeed can't decrypt anything. If you search for the master key ID on the sync target, can you find them?

**Comment by tessus** [comment]
@boringusername99 you are mixing 2 issues here. macOS and Android. The log you sent in your last comment was apparently from macOS, but Laurent thought it was from Android.

Please do mark the logs and your statements clearly to which client they belong to. It's rather confusing keeping them apart otherwise.

**Comment by boringusername99** [comment]
Sorry about that. I've made edits to clarify. I do think the issues maybe are related, just manifesting on multiple platforms.

I've searched the sync target and cannot find the master key ID of either of the keys I'm seeing in my Windows PC client. What's the best way to correct this? Disable encryption on all devices, and then re-enable?

**Comment by laurent22** [comment]
I can't think of a way to get the master keys to force sync, and there's currently no easy way to manage them.

The best way would to export your data to JEX from the working client, then delete all local data, uninstall the mobile apps, and delete all data on sync target. Then re import the JEX file and setup sync and E2EE again.

**Comment by boringusername99** [comment]
Well that was quite an adventure, but it went smoothly and with not too much effort thanks to the clear instructions. Thank you!

**Comment by boringusername99** [comment]
One last thought. I wonder if it would make sense to reset Nextcloud sync settings when another sync target is selected (or maybe if a new None option is selected). I was trying to effectively do that but I noticed changing to file sync and back to nextcloud still retained my settings. 

My hope was to make Joplin think of my new Nextcloud target as a new, empty repository to create in, rather than emptying my local storage.
