### ISSUE TITLE
Copy Images from rendered Markdown pane

### ISSUE THREAD

**Issue by adityakeyal** [laurent22/joplin#1702]
### Operating system

- Windows

### Application

- Desktop

I am unable to copy images from the rendered pane. 
After selecting the entire note, and copy (using Ctrl+c or Right Click > Copy) the entire text is copied however the images are not copied.
There is no option to copy an image by right clicking them also.

It would be very helpful since then we can copy+paste rendered markdown into emails directly.
Note: This works if pasting into Word but not when pasting into Gmail (Chrome browser)

**Comment by laurent22** [comment]
If it works in Word I guess it's an issue with Gmail rather than Joplin?

**Comment by adityakeyal** [comment]
Not sure. Because the following flow works:
 Joplin -> Word --- Works
Same image copy again in Word -> Chrome (Gmail)  --- Works

Note: I also tried to replicate using Gmail in Edge. Exact same behavior. (I believe edge is still not on chromium)

I tried the below:

I added an additional option on right-click of images (context menu)
![image](https://user-images.githubusercontent.com/2504556/60529220-d1203880-9d13-11e9-9a61-c877292316f4.png)

This works perfectly fine.

**Comment by adityakeyal** [comment]
I have done some further analysis on this issue.
There are multiple formats which are copied into clipboard (by design)

Copying from rendered markup (webview) using ctrl+c:
 - Text format
 - Html format

Copying text + image from word using ctrl+c:
 - Text format
 - Html format
 - RTF format
 - many others (native,embed source, object link etc.)

 Webview > Right+Click > Copy:
 - Text 
(This time the image is not rendered in word also).

Images attached below.

![image](https://user-images.githubusercontent.com/2504556/60554502-790a2600-9d55-11e9-900f-295a3d399449.png)
![image](https://user-images.githubusercontent.com/2504556/60554520-86271500-9d55-11e9-96da-c65674dab866.png)

![image](https://user-images.githubusercontent.com/2504556/60554568-b1116900-9d55-11e9-8938-f500f11237a2.png)

I am trying to find some literature on which clipboard content does chrome/gmail read from. 

One issue I can foresee is a difference between the behavior of ctrl+c and Right_Click + Copy
