### ISSUE TITLE
Cut Copy Paste in a note title does not work

### ISSUE THREAD

**Issue by QL8-6754** [laurent22/joplin#1703]
### Operating system

- Windows 10 x64 (1903)
- Linux Mint 19.1 x64

### Application

- Joplin Desktop 1.0.160

When editing, if I highlight the text in a note **title** and right-click I am presented with the options to “Cut”, “Copy”, “Paste”.

None of these functions appear to work. It seems to work perfectly in the body of the note but not the note title field.

**Comment by lmbrt** [comment]
Confirmed on Windows 10 x64.  I did note that hitting Ctrl+C / Ctrl+V does copy/paste, just not the menu items.

**Comment by tessus** [comment]
I can't reproduce this on macOS. The context menu, the menu items, and the shortcuts work on macOS.
@laurent22 Seems to be another Electron issue. (e.g. on macOS the `defaultId` does not work for message boxes).

**Comment by adityakeyal** [comment]
Tried with win 10 1.0.160 - The same issue exists for both 
1. Note Title 
2. Search box

Seems the default context menu handler for text boxes is not working by default in windows / electron.
