### ISSUE TITLE
White bars in notes in iOS and Android apps

### ISSUE THREAD

**Issue by n00b12345** [laurent22/joplin#1706]
### Operating system

- Android
- iOS

### Application

- Mobile

***

There are white bars in the top and bottom of notes on both iOS and Android apps. I’m attaching a note with arrows depicting the issue. 

If possible, please look into it. 

![IMG_0465](https://user-images.githubusercontent.com/17707852/60606448-017dda80-9dd9-11e9-9339-8651d2d16b25.jpeg)

**Comment by laurent22** [comment]
This is the margin on top of the notes, and there's no plan to remove it.
