### ISSUE TITLE
Adding Tags via hotkey breaks tags and notebook renaming

### ISSUE THREAD

**Issue by MarkQueppet** [laurent22/joplin#1715]
### Operating system

- Windows

### Application

- Desktop

### Issue
For some reason, if I add a tag to a note using the ctrl+alt+t shortcut, it breaks both tagging and notebook renaming. If I try to do either of those operations nothing happens. I need to restart the application to regain the functionality. 

This does not happen if I add the tag using the tag icon.

**Comment by tessus** [comment]
I'm sorry, I don't have Windows and can't reproduce this behavior. It does not happen on macOS. This is apparently specific to Windows and maybe Linux.

**Comment by Dasymi** [comment]
I think this is the same behaviour reported here: https://discourse.joplinapp.org/t/version-1-0-160-shortcut-for-tags/2665. It's still broken in Windows.

**Comment by tessus** [comment]
@Dasymi it can't be that issue, because it was fixed. The fix was not OS dependent.

**Comment by tessus** [comment]
@Dasymi sorry, you might be right after all. I added the fix after the release. There has yet to be cut a new release.

@MarkQueppet please include the version number in future bug reports.

**Comment by Dasymi** [comment]
@tessus this is still an issue in Windows:

"There’s also some strange behaviour. I used the shortcut and then selected a tag that I knew the note already had. After closing this, the tags button on the toolbar would do nothing for any note and the shortcut for tags wouldn’t work either. The shortcut and the tags button worked again after restarting Joplin, but this behaviour is repeatable."

**Comment by tessus** [comment]
@Dasymi 

> this is still an issue in Windows:

The OP is most likely using 1.0.160, which does not have the fix. Maybe there's a side effect, I can't say. As long as someone hasn't tried to run git master on Windows, there's nothing that can be done.

**Comment by MarkQueppet** [comment]
> @Dasymi sorry, you might be right after all. I added the fix after the release. There has yet to be cut a new release.
> 
> @MarkQueppet please include the version number in future bug reports.

Nice, yes I'm using 1.0.160 - glad to hear it will be fixed in the next release. 

I should have though to add it, but if you always want version numbers it would be helpful to have that on the submission template.

**Comment by tessus** [comment]
> it would be helpful to have that on the submission template.

You are absolutely right. I've been meaning to change that for a while now. Argh, you know how it is...

**Comment by tessus** [comment]
I fixed this issue a while back and a new release has been cut since then. Closing.
