### ISSUE TITLE
Feature Request: Search Notebook names

### ISSUE THREAD

**Issue by jpmv27** [laurent22/joplin#1716]
When searching notes in the Desktop app, the search only finds notes containing the search words.

It would be nice for search to also look at the Notebook names for matches, although I'm not sure how to incorporate those matches into the search results.

Perhaps when displaying the search results the list of Notebooks could be reduced to only those notebooks with a matching name or containing a note with matching text.

**Comment by tessus** [comment]
`Goto Anything...` to the rescue. `Ctrl+G` or `Cmd+G`:

<img width="797" alt="image" src="https://user-images.githubusercontent.com/223439/60771901-5f9e0c80-a0bc-11e9-9bb7-3a817664734b.png">

Thus, enter: `@notebook-name` et voilà...

**Comment by jpmv27** [comment]
@tessus 
Thank you, was not aware of that feature
MV
