### ISSUE TITLE
Feature Request: Admonition support

### ISSUE THREAD

**Issue by nbo21** [laurent22/joplin#1719]
Hello,

I would like to request an additional plugin to support markdown admonitions (https://squidfunk.github.io/mkdocs-material/extensions/admonition/). I find this feature very useful just like the other plugins that are already included in Joplin.

**Comment by CalebJohn** [comment]
For a future implementors reference, it looks like there is a [markdown-it plugin to do this](https://github.com/docarys/markdown-it-admonition)

**Comment by tessus** [comment]
Adding the plugin is easy, but adding the proper css will most likely be the culprit.
