### ISSUE TITLE
Tab and Shift-Tab for easier indentation of lists?

### ISSUE THREAD

**Issue by wOstensen** [laurent22/joplin#172]
### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---

Making lists of several levels of indentation takes longer than when using other text-editing software like Word and Evernote. Is it possible to add the usage of tab and shift-tab to indent and unindent lists?

**Comment by oujunhao** [comment]
You can use ctrl+] and ctrl+[ for indenting out and in, respectively

**Comment by laurent22** [comment]
List editing was improved in recent versions.
