### ISSUE TITLE
Show tags on note list

### ISSUE THREAD

**Issue by dlip** [laurent22/joplin#1721]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile

I would like to be able to see the tags next to each note in the list in small text so I can tell if a note has a tag without opening the tag settings.

**Comment by foxmask** [comment]
https://github.com/laurent22/joplin/issues/1396 could fill that needs ?

**Comment by dlip** [comment]
It is similar to the "inkdrop" feature from that issue, I just worry that issue is so large there is less chance of it being done.  If this was done first that issue could re-use some of the code.
