### ISSUE TITLE
Version mismatch on Ubuntu

### ISSUE THREAD

**Issue by Kukanani** [laurent22/joplin#1722]
### Operating system

- Linux

### Application

- Desktop

I am unable to sync my Ubuntu and Windows Joplin notes because of a version mismatch between the two platforms, so I attempted to upgrade my Ubuntu Joplin install to 1.0.160.

```
$ wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash
```
```
...
Joplin version 1.0.160 installed.
Bye!
```

But the synchronization errors continue and I get the following behavior:
```
$ cat .joplin/VERSION
1.0.160
```
When I run `.joplin/joplin.AppImage` and go to Help > About Joplin, the dialog reads

> Joplin for Desktop
> 
> Copyright © 2016-2018 Laurent Cozic
> Joplin 1.0.119 (prod, linux)

**Comment by Kukanani** [comment]
The issue seems to have been resolved by restarting the computer. Does Joplin run a background daemon?

**Comment by CalebJohn** [comment]
No, but if you have the tray icon enabled the window will be closed but Joplin will still be running.

**Comment by Kukanani** [comment]
Makes sense, thanks!
