### ISSUE TITLE
Importing enex breaks audio links

### ISSUE THREAD

**Issue by yuxiliu1995** [laurent22/joplin#1723]
### Operating system
- Windows 10

### Application
- Desktop

### To reproduce
1. Make an Evernote note with a recording.
2. Export to enex.
3. Import to Joplin.
4. Attempt to open the link to the recording file in Joplin.

### Current hack
I could hack this problem away manually by 
1. right click and save the audio files from the folder to desktop
4. drag and drop it back into Joplin.

**Comment by foxmask** [comment]
what is the rendering of that audio link once into joplin ?

**Comment by yuxiliu1995** [comment]
It looks like `C:\Users\dell\Desktop\JoplinProfile\resources\4d8c05f2c2c3acc8f9b44fe395ca907b`

**Comment by foxmask** [comment]
ok so the current markdown looks like this 
```
[Audio file](c:\Users\dell\Desktop\JoplinProfile\resources\4d8c05f2c2c3acc8f9b44fe395ca907b)
```
instead of 
```
[Audio file](:/4d8c05f2c2c3acc8f9b44fe395ca907b)
```
I hope it should be easy to fix

**Comment by yuxiliu1995** [comment]
Actually, in the text editor on the left, it looks like
```[Audio file](:/4d8c05f2c2c3acc8f9b44fe395ca907b)```

but in the view on the right, there is just a link, which, if I click "Copy path to clipboard", I get 

```C:\Users\dell\Desktop\JoplinProfile\resources\4d8c05f2c2c3acc8f9b44fe395ca907b```

**Comment by foxmask** [comment]
ok
