### ISSUE TITLE
Fail to sync attachments larger than 4MB to OneDrive

### ISSUE THREAD

**Issue by carlu** [laurent22/joplin#173]
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

I have imported a large set of notes from Evernote to Joplin and I am now trying to sync those notes to an otherwise empty OneDrive.  This has mostly worked but I get a message saying "Some items cannot be synchronised.", looking at the details it says "Resource exceeds OneDrive max file size (4MB)" for each of the unsynchronised files.  However I can upload those same files individually to OneDrive without issue.  

OS X version: High Sierra 10.13.2
Joplin version: 0.10.47 (prod, darwin)

![image](https://user-images.githubusercontent.com/660775/35111940-75a4d268-fc74-11e7-877c-b008dc3bec51.png)

---

**Comment by carlu** [comment]
I see from the OneDrive documentation that this is a limit imposed by the API's upload [method](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content).  There is an alternative method for [large files](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession).  I'm not sure if there's a reason Joplin uses the small file method, maybe if I figure it out I can help...

**Comment by lazylionca** [comment]
I can live with the size limitation for now, but I haven't been able to copy & paste the list of failed uploads so that I can go back and correct them. There is a saved report but it doesn't contain any meaningful information (possibly because my notes are encrypted.

**Comment by fuzzy76** [comment]
I came here because this is the only cross platform note client that supports onedrive sync (which I need if I am gonna store work-related notes there). Too bad the support isn't usable (I need to attach documents larger than 4 MB).

**Comment by abdcef** [comment]
Will this help?
https://stackoverflow.com/questions/56335586/upload-file-4mb-to-onedrive-using-graph-api
