### ISSUE TITLE
Virus Total Scan 2/64

### ISSUE THREAD

**Issue by inimitablemind** [laurent22/joplin#1730]
### Operating system

Windows Portable Executable
Desktop Version

Virus detected. I know its Chinese anti-virus engines but is there any way to clean it up?

https://www.virustotal.com/gui/file/0f6496e9cc39e57ba3ee0be0bb47c50cd421992b32583fd235eff2eb7c2d51cd/detection

**Comment by laurent22** [comment]
For avast I've contacted them about their false positive and they removed it. If someone could contact these chinese anti virus companies maybe they'll remove them too.

But false positives come and go anyway. I think avg also flagged the app at some point but not anymore.

**Comment by tessus** [comment]
Closing, due to no more feedback from OP.
