### ISSUE TITLE
Uninstall Script

### ISSUE THREAD

**Issue by winters-brown** [laurent22/joplin#1736]
### Operating system

- Windows
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

There is an option to install, But same as that there should be a script to uninstall the application. This is my first time trying. I'm not saying that I don't like it just at first glance that's what I notice

**Comment by laurent22** [comment]
You need to clarify what app and what system because on Windows, Android, iOS, desktop, mobile and even terminal there's a way to uninstall the app. That leaves the desktop app on Linux, so is that what you mean?

**Comment by winters-brown** [comment]
Sorry about that, Yes for linux

**Comment by tessus** [comment]
@winters-brown you delete the app image and the directory `.config/joplin-desktop`.
