### ISSUE TITLE
API : no more body returned

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#1737]
this
``` 
curl GET http://127.0.0.1:41184/folders/<noteid>/notes
```
does not return the body anymore :(

same with 
``` 
curl GET http://127.0.0.1:41184/notes?token=xxx
```

**Comment by laurent22** [comment]
Ah, this is actually because these end points by default return the "preview" of a note. However, in recent versions I've changed what a preview is to exclude the body, which in many places mean smaller memory usage and faster loading. I've checked that it didn't cause any issue but completely missed this part.

Unfortunately this is a breaking change as going forward, I prefer not to include the body in the preview, so now from the API it needs to be requested explicitly with the `field` parameter.

I assume that this should work:

    curl GET http://127.0.0.1:41184/folders/<noteid>/notes?fields=id,title,body

If not, please let me know.

**Comment by foxmask** [comment]
An Idea

```
curl http://127.0.0.1:xxxx/?preview=0
```
This will use all the fields instead of having to name all of them.

I'll test the fields parm

**Comment by foxmask** [comment]
we can't provide all the note fields (from the doc https://joplinapp.org/api/) :
```
curl -X GET http://127.0.0.1:41184/notes/ffb46c02586c43fb8b59fd74c372bde6?token=<token>\&fields=id,parent_id,title,body,created_time,updated_time,is_conflict,latitude,longitude,altitude,author,source_url,is_todo,todo_due,todo_completed,source,source_application,application_data,order,user_created_time,user_updated_time,encryption_cipher_text,encryption_applied,crop_rect
```
returns 
```
{"error":"Internal Server Error: Error: SQLITE_ERROR: no such column: crop_rect: SELECT `id`,`paren
```
same with `body_html`, `base_url`, `image_data_url`

**Comment by laurent22** [comment]
Right, it's not documented but some of these fields are input only. Like crop_rect or image_data_url is only used when creating a note and discarded afterwards.

I don't think there should be an API to retrieve all the fields as it's not future-proof. For example, if later a field is added that returns a lot of data, or that's resource-intensive to compute, clients that request all data might break or slow down, even though they don't need this new field.

This the current list of default note fields:

'id'
'title'
'is_todo'
'todo_completed'
'parent_id'
'updated_time'
'user_updated_time'
'user_created_time'
'encryption_applied'

so to this you could add "body".

Maybe we could also improve the "fields" parameter as well to allow returning all the default fields + custom ones.

**Comment by foxmask** [comment]
ok :) 
I fixed joplin-api with that
 thanks

**Comment by tessus** [comment]
> Maybe we could also improve the "fields" parameter as well to allow returning all the default fields + custom ones.

This is a good idea. We could use the virtual "field name" `default` for that.
