### ISSUE TITLE
[Feature Request] Ability to Change the Save Directory

### ISSUE THREAD

**Issue by jvarghe** [laurent22/joplin#1740]
I played with Joplin today. The first thing I tried to do was choose where to put my notes. I wanted to put my notes in a folder in my data partition, but I can't find any way to change the save directory for my notes. Under Tools > General Options, there is a line that says: 

`Notes and settings are stored in: C:\Users\<UserName>\.config\joplin-desktop`

That's not very helpful. I don't want my private files sitting in the Windows partition. I never want my notes or other data files there. Its better for security and backing up if notes are only saved to a specific folder I choose.  

If this is not currently possible, can you add this feature, please?

**Comment by CalebJohn** [comment]
It's already possible using a command line flag `--profile` for example you could run

```
joplin.exe --profile C:\Something\else
```

although in your case I might suggest using the portable version of joplin.
