### ISSUE TITLE
metadata no longer available, properties use wrong date format

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#1745]
### Operating system

- Android
- iOS

### Application

- Mobile

---

The menu item `show metadata` is gone. Some of the info is available in the new item `Properties`.

However, the dates are not shown in the format set in the configuration.

**Comment by tessus** [comment]
I have the fix for the date/time already.

Unfortunatelty I can't test it, because I can't run `react-native run-android` as mentioned in the forum.
I really could need some help.

**Comment by tessus** [comment]
@laurent22 what about the metadata? Is it on purpose that only create and update time are shown?
If yes, we can close this issue.

**Comment by foxmask** [comment]
We also lost the URL of the website where the note comes from

**Comment by laurent22** [comment]
> We also lost the URL of the website where the note comes from

It's not on the sidebar?

**Comment by foxmask** [comment]
We have a link "Aller URL source" but not the text if the URL itself so we don't know / remember ;)

**Comment by laurent22** [comment]
For the source URL, I'm not sure how to present that since there's not so much space in the sidebar. If you have a suggestion for it, please open another issue.
