### ISSUE TITLE
Fix sidebar swipe right

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#1746]
https://discourse.joplinapp.org/t/android-ui-and-ux-is-meh/2301/9?u=laurent

**Comment by tessus** [comment]
additional info. when you click on properties, the next time you swipe will show you the properties.

I suspect that side window isn't initialized when opening a note, but only when getting the properties.

**Comment by CalebJohn** [comment]
An interesting (maybe unrelated thought). What if swiping while in a note, instead of showing properties (or nothing) had a list of markdown inserts like the desktop has on the top bar. The using could insert bold, italics, date, etc... This would solve that issue in what I think is a fairly intuitive way.

**Comment by tessus** [comment]
Great idea. Maybe we can even use the sidebar to show the properties when in view mode and the  markdown toolbar buttons in edit mode.

**Comment by laurent22** [comment]
My plan for note formatting was to have a toolbar that collapses so you can hide and show it as needed. The sidebar is to display info that takes more space like currently, geolocation, source url, created and updated time (basically what the "metadata" option was before). Other things could be added over time.

For the toolbar it's already partially implemented it: https://github.com/laurent22/joplin/commits/mobile-toolbar but I've dropped it back then because React Native text input was too buggy to position the cursor and select text. Maybe it's improved since then so would be worth checking.
