### ISSUE TITLE
General UI Improvement

### ISSUE THREAD

**Issue by Immortalin** [laurent22/joplin#1747]
### Operating system

- Android
- iOS

The general UI on mobile is quite lacking compared to some of its competitors. There is lag when editing large notes and features like double tap on character to edit, scrolling with inertia etc. are all non-existent. Another app built with React Native however implements all these and feels quite native:

https://github.com/standardnotes/mobile

I propose Joplin borrow some components (the editor especially) from them. This would help greatly improve the UX.

**Comment by laurent22** [comment]
Hi, these are known issues which are being improved over time.

**Comment by laurent22** [comment]
By the way, in which way is the editor of Standard Notes better? I'm just curious as, as far as I can see, it's just plain text too, or am I missing something?

**Comment by Immortalin** [comment]
It's a lot smoother and doesn't have all the UI issues. Feels native. Joplin's feels like a glorified textbox in a web browser.

**Comment by laurent22** [comment]
The last release includes performance improvements, in particular when typing on large notes, and other many things more subtle, but which leave room for more improvements. If you notice a specific performance issue and how to replicate it, feel free to report it here.
