### ISSUE TITLE
The application crashes when I try to use a take  photo option and try to take the picture.

### ISSUE THREAD

**Issue by friendsmobile** [laurent22/joplin#1750]
# Project Information

* Repository:   https://github.com/laurent22/joplin
* Project Name:  Joplin
* My Github Account: https://github.com/friendsmobile
* Download the application:   https://github.com/laurent22/joplin/releases

# Expected behavior

When I use the take option and try to take more photos, the application should not crash.
 When I take a picture, this picture should be automatically displayed on the profile

# Actual behavior

The application crashes when I try to use a take photo option and try to take the picture.

#### How to reproduce

* [Download ](url)the application
*   open the application
* click on PLUS button and create new to do file
* click on 3 verticals dots at top right 
* click on Attach option
* select the Take photo option and try to take any pictures with the help of your back camera from a mobile 
* Note the Error

* Browser/App version: v1.0.161
* Operating system: 6.0

#### Recording Of The Bug

![20190716_144149](https://user-images.githubusercontent.com/51118734/61285079-15302600-a775-11e9-80ed-4dc07ca165cf.gif)

#### Logcat

<pre><code>E/AndroidRuntime(  828): FATAL EXCEPTION: AsyncTask #4

E/AndroidRuntime(  828): Process: net.cozic.joplin, PID: 828

E/AndroidRuntime(  828): java.lang.RuntimeException: An error occured while executing doInBackground()

E/AndroidRuntime(  828): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)

E/AndroidRuntime(  828): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)

E/AndroidRuntime(  828): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)

E/AndroidRuntime(  828): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)

E/AndroidRuntime(  828): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

E/AndroidRuntime(  828): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

E/AndroidRuntime(  828): 	at java.lang.Thread.run(Thread.java:818)

E/AndroidRuntime(  828): Caused by: java.lang.OutOfMemoryError: Failed to allocate a 51121164 byte allocation with 12737262 free bytes and 12MB until OOM

E/AndroidRuntime(  828): 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)

E/AndroidRuntime(  828): 	at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)

E/AndroidRuntime(  828): 	at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:719)

E/AndroidRuntime(  828): 	at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:742)

E/AndroidRuntime(  828): 	at org.reactnative.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:92)

E/AndroidRuntime(  828): 	at org.reactnative.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:26)

E/AndroidRuntime(  828): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)

E/AndroidRuntime(  828): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

E/AndroidRuntime(  828): 	... 3 more
</code></pre>

**Comment by laurent22** [comment]
I've created a new release which could possibly prevent this out of memory error:

https://github.com/laurent22/joplin-android/releases/download/android-v1.0.282/joplin-v1.0.282.apk

Any chance you could give it a try and let me know if it fixes the crash?

**Comment by foxmask** [comment]
It works for me

**Comment by laurent22** [comment]
it's only a some devices, probably those with less memory. @friendsmobile, if you could give it a try that would be great.

**Comment by friendsmobile** [comment]
also work for me thanks u
