### ISSUE TITLE
Calendar integration

### ISSUE THREAD

**Issue by mkwork** [laurent22/joplin#1751]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

It would be nice to have any way to calendar integration. At least export task as ical (ics) one.

**Comment by tessus** [comment]
Please move discussions about features to the [forum](https://discourse.joplinapp.org/). You can use your github credentials to login.

We really try to use this tracker only for reproducible/confirmed bugs and accepted feature request.

**Comment by mkwork** [comment]
I got it, sorry. Corresponding [topic](https://discourse.joplinapp.org/t/tasks-calendar-integration/3009) was created.
