### ISSUE TITLE
URL upper/lower case eror

### ISSUE THREAD

**Issue by AlexIs72** [laurent22/joplin#1753]
### Operating system

- Windows
- macOS
- Linux
- [x] Android
- iOS

### Application

- Desktop
- [x] Mobile
- Terminal

URL with upper case protocol (e.g. HTTPS://webdav.host, htTPs://webdav.host) cause synchronization error

**Comment by AlexIs72** [comment]
No problems on Linux desktop version

**Comment by laurent22** [comment]
What's the error message?
