### ISSUE TITLE
Sync failed on Android with Nextcloud

### ISSUE THREAD

**Issue by general03** [laurent22/joplin#1754]
### Operating system

- Linux
- Android

### Application

- Android Joplin 1.0.281 (Database v23)

### Issue

I used Nextcloud to store the Joplin notes through webdav.
However when I try to sync with my Android Phone I can't.
In the app configuration setting when I click on "Check Synchronisation Configuration" I got `PROPFIND : Unknown error 2 (405) : Code 405`
I check my credentials and path, all it's good because I can access it through WebDav protocol on my computer

**Comment by laurent22** [comment]
This error usually mean you've provided the wrong WebDAV URL. What URL did you use? (you can replace the domain name by "example.com")

**Comment by general03** [comment]
https://example.com/remonte.php/webdav/Notes

**Comment by laurent22** [comment]
How about with "remote" instead of "remonte"?

**Comment by general03** [comment]
So sorry I not see this mistake

**Comment by tessus** [comment]
Great, this seems to be solved. I'm closing this.
