### ISSUE TITLE
Android: 405 Method Not Allowed (HTTPS)

### ISSUE THREAD

**Issue by greygoosey** [laurent22/joplin#1755]
### Operating system

- Windows
- macOS
- Linux
- [X] Android
- iOS

### Application

- Desktop
- [x] Mobile
- Terminal

I only get this error message on Android. Browser and Linux client work without issue.

405 Method Not allowed
"The Requested method GET is not allowed for the URL /seafdav/Joplin"

Any ideas? I am using a SSL Cert from LetsEncrypt.

**Comment by laurent22** [comment]
Someone had the same error yesterday and it was because they've mistyped the URL. So I'd start by checking it.

**Comment by greygoosey** [comment]
URL is the exact same as on the Linux client as well as browser (copy and pasted it).

Today though, the error changed from "Method GET not allowed" to "Method PROPFIND not allowed".

It is still only the Android app not working.

**Comment by greygoosey** [comment]
This can be closed. It has been fixed.

Sorry about that.

**Comment by laurent22** [comment]
How did you fix it eventually?

**Comment by greygoosey** [comment]
I added "DirectoryIndex disabled" into apache2.conf

I'm not sure why the Linux client worked and the Android app didn't before that, though.

**Comment by laurent22** [comment]
Ok thanks. Based on the DirectoryIndex doc I don't understand how it can fix the issue either, but it's good to know anyway.
