### ISSUE TITLE
Nginx WebDav MKCOL problems

### ISSUE THREAD

**Issue by mightyBroccoli** [laurent22/joplin#1756]
At first I used Joplin with the integrated Nextcloud Sync function, but the continuing change of different files spammed my activity feed, to the point that it lost nearly all its functionallity.
Therefore I wanted to switch to the native nginx webdav implementation to handle this. Which works great but there are some issues with it.

## Environment

Joplin version: 1.0.161
Platform: Android/ Linux/ Windows

## Steps To Reproduce

1. setup nginx's webdav
2. configure joplin to use said sync target
3. profit?

I configured Joplin to use the endpoint `example.tld/joplin` for its sync activity with the following nginx setup.
```nginx
	location /joplin {
		alias /var/www/webdav/joplin;
		client_body_temp_path /var/www/webdav/tmp;

		# log
		access_log /var/log/nginx/joplin_access.log;
		error_log /var/log/nginx/joplin_error.log error;

		# define methods to use
		dav_methods PUT DELETE MKCOL COPY MOVE;
		dav_ext_methods PROPFIND OPTIONS;

		# dav options
		create_full_put_path on;
		dav_access user:rw group:rw all:r;
		autoindex on;

		# auth
		auth_basic "restricted";
		auth_basic_user_file /etc/nginx/auth/htpasswd_joplin;
	}
```

Describe what you expected to happen:
I would expect that Joplin checks if everything it needs is present and then syncs everything it needs to sync. 

What actually happend:
Joplin connects and authenticates correctly, thats that. After that some mandatory directories are checked (`.sync` and `.resource`).  I completly get that, for each connection those folders are checked and an error is thrown that `mkdir()` failed because the directory is already present.

## Logfile
```
77.22.232.153 - [21/Jul/2019:18:21:52 +0200] "MKCOL /joplin/.sync/ HTTP/1.1" 405 166 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
2019/07/21 18:21:52 [error] 31790#31790: *659788 mkdir() "/var/www/webdav/joplin/.sync" failed (17: File exists), server: example.tld, request: "MKCOL /dav/.sync/ HTTP/1.1", host: "example.tld"
77.22.232.153 - [21/Jul/2019:18:21:52 +0200] "MKCOL /joplin/.resource/ HTTP/1.1" 405 166 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
2019/07/21 18:21:52 [error] 31790#31790: *659789 mkdir() "/var/www/webdav/joplin/.resource" failed (17: File exists), server: example.tld, request: "MKCOL /dav/.resource/ HTTP/1.1", host: "example.tld"
```

**Comment by laurent22** [comment]
This looks like a config issue that should be posted on the support forum. What doesn't work actually? Is it just that you don't like the log entry on the nginx log?

**Comment by mightyBroccoli** [comment]
I am not quite sure that this is a config issue. It seems that the application is not recognising the already existing folders throwing errors left and right for every sync run for each device every x minutes.
4 devices * 5 min Intervall is quite a lot of entries, and I would actually like a usable error logfile.

There's nothing to like about thrown errors in any log. Why does Joplin try to recreate those folders every time? The support forum does not list any nginx posts that actually resolve this issue, therefore I though that this actually is a bug.

**Comment by tessus** [comment]
This has nothing to do with nginx nor webdav. It has to do with how the sync algorithm works.
Don't get me wrong, I do understand your concern, but this is not a bug.
In Apache httpd one can filter log entries (exclude the ones which are useless), maybe there's something similar in nginx.
While I get your point, there are more pressing issues to tackle than cosmetic changes. 
However, I'm sure Laurent would accept a PR for that. Although I reckon there must have been a reason for doing a mkdir every sync op. In any case, these things are better discussed on the forum, which has a broader user base.

We really try to stop gh issues to be created that are not bugs or have previously been discussed (on the forum) as feature requests.

**Comment by laurent22** [comment]
This is a known issue that has been discussed a few times.
