### ISSUE TITLE
Stuck retrying failed resource decryption 

### ISSUE THREAD

**Issue by joesfer** [laurent22/joplin#1758]
The android client seems to be getting stuck when decrypting batches of pending resources after a successful syncing. One or more assets failing to decrypt will be logged and flagged as skip, but the client keeps retrying. 

## Environment

Joplin version: 1.0.281
Platform: Android 
OS specifcs: Android 9

## Steps To Reproduce

1. Install joplin on desktop, and import a large number of notes. 
2. Configure encryption 
3. Configure Dropbox sync and let the client syncing overnight. 
4. Install android client, configure Dropbox. 
5. Let sync finish, then configure encryption. 
6. Start decryption of resources. Eventually one or more will fail to decrypt and the process will get stuck. 

**Describe what you expected to happen:**

I am not sure if this is android specific, but I have only been able to verify this behaviour with the android client. I've attempted the process a few times with vanilla installations, but eventually they all seem to get caught in the syncing process. 

I assume this is a problem with one or more of my resource files (some of them are large, so this could be related to the 10MB file limit on android?). 

The issue is not so much the failure on decryption, but the fact that this seems to prevent the process from completing for other pending resources. 
The cycle will be
* decrypting 1/60 resources
* one file fails to decrypt 
* decrypting 1/60
* decrypting 1/1 (failed again) 
* decrypting 1/60
* decrypting 1/1 (failed again) 
* ... 

It is hard to say from the log or client whether the other 60 (or N) are the same files or different every time, so I let the process repeat for almost a full day to see if it would change in any way, though it doesn't seem to recover. 

Happy to provide any more information that can serve debugging this problem. Thank you for help! 

## Logfile

```
Date,Level,Message
07-22T07:31:20,30,"""DecryptionWorker: starting decryption...""
07-22T07:31:19,30,"""DecryptionWorker: Some resources have been downloaded but are not decrypted yet. Scheduling another decryption. Resource count: 1""
07-22T07:31:19,30,"""DecryptionWorker: completed decryption.""
07-22T07:31:19,20,"""DecryptionWorker: 81c157e9bffb24a026a9e4ae76395065 decryption has failed more than 2 times - skipping it""
07-22T07:31:17,30,"""DecryptionWorker: starting decryption...""
07-22T07:31:16,30,"""DecryptionWorker: Some resources have been downloaded but are not decrypted yet. Scheduling another decryption. Resource count: 1""
07-22T07:31:16,30,"""DecryptionWorker: completed decryption.""
07-22T07:31:16,20,"""DecryptionWorker: 81c157e9bffb24a026a9e4ae76395065 decryption has failed more than 2 times - skipping it""
07-22T07:31:12,30,"""DecryptionWorker: starting decryption...""
07-22T07:31:11,30,"""DecryptionWorker: Some resources have been downloaded but are not decrypted yet. Scheduling another decryption. Resource count: 1""
07-22T07:31:11,30,"""DecryptionWorker: completed decryption.""
07-22T07:31:11,20,"""DecryptionWorker: 81c157e9bffb24a026a9e4ae76395065 decryption has failed more than 2 times - skipping it""
07-22T07:31:09,30,"""RevisionService::maintenance: Done in 158ms""
07-22T07:31:09,30,"""RevisionService::collectRevisions: Created revisions for 0 notes""
07-22T07:31:09,30,"""RevisionService::maintenance: Starting...""
07-22T07:31:09,30,"""RevisionService::maintenance: Service is enabled""
07-22T07:31:09,30,"""DecryptionWorker: starting decryption...""
07-22T07:31:09,30,"""ResourceService::deleteOrphanResources:", "[]""
07-22T07:31:09,30,"""ResourceService::indexNoteResources: Completed""
07-22T07:31:09,30,"""ResourceService::indexNoteResources: Start""
07-22T07:31:08,30,"""DecryptionWorker: Some resources have been downloaded but are not decrypted yet. Scheduling another decryption. Resource count: 1""
07-22T07:31:08,30,"""DecryptionWorker: completed decryption.""
07-22T07:31:08,20,"""DecryptionWorker: 81c157e9bffb24a026a9e4ae76395065 decryption has failed more than 2 times - skipping it""
07-22T07:31:06,30,"""DecryptionWorker: starting decryption...""
```

**Comment by laurent22** [comment]
Hmm, yes that looks like a bug. Not long ago I've added a mechanism to skip failing resources, but it should keep decrypting the other ones which doesn't seem to be happening here.

**Comment by CalebJohn** [comment]
I had a similar problem (I fixed by removing the resource). It was a JPG image that caused the failure. You can see the problem image here https://www.dropbox.com/s/bavihn47a0b9i3w/4d7926ce1e1a42eea9ef94d76fd4a539.jpg?dl=0
