### ISSUE TITLE
[Feature Request] Export entire notebook to PDF

### ISSUE THREAD

**Issue by kontakt** [laurent22/joplin#1760]
It would be useful to be able to print an entire notebook to PDF, rather than having to string together notes manually.

**Comment by tessus** [comment]
The instructions for opening a ticket are quite clear. Tickets that do not follow the instructions are closed.

**Comment by kontakt** [comment]
Ah I see, the templates don't appear when you open a ticket on mobile.

**Comment by tessus** [comment]
Hmm, this should not be the case, unless you use a gh app that does not support issue templates.

Anyway, your feature request has been requested and discussed on github and the forum. It might be better to comment in those issues/topics.

**Comment by kontakt** [comment]
Looks like fasthub has a couple of closed issues with wontimplement and a writeoff as impossible due to the lack of an api for template locations and the trouble of scanning a repository.

I don't see any discussion on this topic in an issue here, and two threads over on the site. Should I create an issue linking to the thread to add it here, even though I am not the thread owner?
