### ISSUE TITLE
syntax highlighting of link by reference is buggy

### ISSUE THREAD

**Issue by taw00** [laurent22/joplin#1762]
Minor, but annoying.
For reference, this is the spec for MD links (to include link by reference):
https://daringfireball.net/projects/markdown/syntax#link

A link by reference in markdown can look like this...
```
[anchor text] [REF_ID]

[REF_ID]: <https://example.com/> "Title text"
```
There are acceptable alternatives. For the first bit...
```
[anchor text] [REF_ID]
...or...
[anchor text][REF_ID]
```
are both correct.

And for the 2nd bit...
```
[REF_ID]: <https://example.com/> "Title text"
...or...
[REF_ID]: https://example.com/ "Title text"
...or...
[REF_ID]: https://example.com/ 'Title text'
...or...
[REF_ID]: https://example.com/ (Title text)
```
...are all correct.

They do not all syntax highlight though. In fact, only the double quote version does.

Thanks! -t

**Comment by CalebJohn** [comment]
This is an upstream issue with the [editor that Joplin uses](https://github.com/securingsincity/react-ace). If this is critical for you the issue can probably be raised there. Otherwise there is a long term plan to replace the editor with something better and this will probably be resolved at that time.

**Comment by taw00** [comment]
I filed it here: https://github.com/securingsincity/react-ace/issues/679

**Comment by CalebJohn** [comment]
@taw00 Codemirror became the default editor in #3703 . This means the highlighting has changed. Please take a look at the below example of the highlighting and let me know if we can close this issue.
One thing to note is that the sections in square brackets are not highlighted but they do have the `cm-link-text` css class, which means you can colour them however you want using userChrome.css.

![image](https://user-images.githubusercontent.com/2179547/92337184-13a27b00-f065-11ea-9c99-c88cbbd1ba20.png)

**Comment by taw00** [comment]
Looks good.
That being said, the `[anchor text] [REF_ID]` syntax does not work according to the spec when rendering, though `[anchor text][REF_ID]` does.

I'm closing it. The issue I just mentioned is a different issue. But I think it is minor. I leave it to @laurent to determine it is worthy of an issue.
