### ISSUE TITLE
Sync on linux/windows downloading forever gbs of datas

### ISSUE THREAD

**Issue by dotgreg** [laurent22/joplin#1766]
Thanks for the work done so far, it is moving quite fast!

I happened to have a problem since 2 days that is quite a big one, as I am working using metered 4g connections.
Joplin seems indeed downloading files from my server forever.

I was not aware of it yesterday and it just sucked my whole 50gb data plan. After some reseachs I managed to isolate joplin.

I am using it with a nextcloud server sync, encryption.

Dont know how to provide logs infos on joplin side, but on linux side, joplin is clearly downloading something forever at 6.8mb/s while my whole joplin folder is only 211mb

Any clue?

=> sudo iftop shows massive amount up/down to my nextcloud server
![d0e8655df924423dbd5e236c30cc43fe](https://user-images.githubusercontent.com/2981891/61886799-a84d2680-af00-11e9-87eb-ec8fd5ecb629.png)

=> the biggest process network wise on the computer is joplin
![eba59de9195a47e5bb793204ddced6a4](https://user-images.githubusercontent.com/2981891/61886890-d0d52080-af00-11e9-8c64-26871a817569.png)

=> yet my joplin folder on nextcloud is only 210mb
![image](https://user-images.githubusercontent.com/2981891/61887088-3aedc580-af01-11e9-8c4b-2d45b0a0840b.png)

![e27b7da24b484c90a34d35e6a4442f3b](https://user-images.githubusercontent.com/2981891/61886865-c4e95e80-af00-11e9-87c9-99680011f1c9.png)

## Logfile

no errors on the console

**Comment by foxmask** [comment]
just a notice in case you're in that situation

When we set encrpytion ; joplin encrypts notes and send all of them from the current device to the hosting service. and the same behavior occurs when we unset encryption.
So when we do that from device A and sync is complet on the hosting service, it will take also a long time to sync the device B

**Comment by dotgreg** [comment]
@foxmask that's an interesting notice indeed.

In my case, my total folder is ~210mb on the cloud. And is almost synced on local. But the traffic however is massive in my case (it reached 50gb of transfer from cloud->joplin local), suprisingly, the download rate is super constant and massive, took all my bandwidth (reached 11mb/s) making me thinking the file being downloaded is a big one and not lots of small files (in that case, the download speed would be much smaller).

Hope it can help

**Comment by laurent22** [comment]
Can you provide the debug log for it? Maybe it fails to download some resource and then keeps trying which could eat up bandwidth.

**Comment by dotgreg** [comment]
Hello @laurent22, I tried to follow the procedure to get the logs (enable the console) but that one stayed empty. Is there a way to get the network console working with all the assets getting downloaded? seems the network tab does not show it, no?

**Comment by foxmask** [comment]
Or a snapshot of the log page when the resource is downloading ? I'm not in front of my PC to check 🤔

**Comment by laurent22** [comment]
I meant the log file as described here https://joplinapp.org/debugging

**Comment by laurent22** [comment]
Yes and i guess it would be useful to check how much bandwidth one sync operation take. For example a sync with no changes, and a sync where one note had been modified.

**Comment by laurent22** [comment]
Closing this for now. Feel free to ask to re-open when more info is provided.
