### ISSUE TITLE
Android search not working

### ISSUE THREAD

**Issue by cloo** [laurent22/joplin#1767]
Android search bug #1690 was not fixed in version 1.0.281

## Environment
Joplin version: 1.0.281
Platform: Android 9

## Steps To Reproduce

1. Enter search terms with titles or content of your notes
2. Empty results window _(no indication that search completed and nothing found)_

## Extra checking

I have launched "fix search index" several times, but I have no idea if it finished successfully.
_(The only indication that operation is finished is that the button became active [blue] again after some time.)_

Complete reinstalling Joplin (also the whole Android OS), removal of online storage and complete resync from windows client (which can find all notes) did not fix the issue.

I tried to add a new note, to see if newer or older notes are not found. 
Newest note "namams" was not found.

![Screenshot_20190725-202421](https://user-images.githubusercontent.com/651760/61895422-51a11600-af1b-11e9-9367-4361aab7c597.png)
![Screenshot_20190725-202442](https://user-images.githubusercontent.com/651760/61895423-51a11600-af1b-11e9-89cc-1428009aa41b.png)

## Logfile

[syncReport-1564073713617.txt](https://github.com/laurent22/joplin/files/3432650/syncReport-1564073713617.txt)

**Comment by foxmask** [comment]
try v 1.0.282

**Comment by laurent22** [comment]
Is fts enabled? (At bottom of config screen) Any error in the log?

**Comment by laurent22** [comment]
Sorry i missed it was a follow up of the previous issue, and i didn't see the report link.

It seems it's still the too big row error. I can only guess you have one particularly large note that makes the search engine database reaches its limits, or perhaps your device has relatively low memory.

I couldn't replicate this on emulator even with massive notes. On the sync target what is the largest .md file?

**Comment by cloo** [comment]
Hi, 
1.0.282 didnt help.
FTS is enabled.
Largest .md is 4.04 mb. (according to Dropboxs sorting "by size" column)

**Comment by laurent22** [comment]
@cloo, I've released another version that might fix the issue, could you give it a try to see if it works for you? https://github.com/laurent22/joplin-android/releases/download/android-v1.0.303/joplin-v1.0.303.apk

**Comment by cloo** [comment]
@laurent22  
Fixing search index did not help. 
I ditched dropbox for Nextcloud, but now sync does not work at all. 
I'll try complete resync and report back on this search problem after I manage to [get Joplin back on Android](https://github.com/laurent22/joplin/issues/1890)...

**Comment by laurent22** [comment]
If you could let me know like before the errors you had in the log that would be great.
