### ISSUE TITLE
High CPU when sync target unreachable

### ISSUE THREAD

**Issue by gholt** [laurent22/joplin#1768]
## Environment

Joplin version: 1.0.161
Platform: Linux
OS specifcs:

## Steps To Reproduce

1. Disconnect network
2. Run Joplin
3. Wait for it to start syncing
4. Notice it spins seemingly forever, using a lot of cpu.

Describe what you expected to happen:

I expected a sync error indicating it couldn't reach the sync target. Or, it could spin forever if it wants, but use very little cpu. Currently, it's not really great to run Joplin while disconnected from the Internet, as it will use a lot of cpu, spinning up the fans and draining the battery as well as making the rest of the system sluggish.

**Comment by tessus** [comment]
Looks like this one: https://discourse.joplinapp.org/t/connection-timeout-for-sync-not-working/2575?u=tessus
I'm not sure, if Laurent has found a solution for this yet.

**Comment by laurent22** [comment]
I don't have a Linux box to test and I also can't really replicate on macOS. I did notice it was repeating failed requests more than needed (3 x 5 times) and indeed that could not be cancelled. So I've changed it so that it only repeats up to 3 times, which should improve the issue.
