### ISSUE TITLE
[Feature request] Notebook's title as filename

### ISSUE THREAD

**Issue by mcrainydrop** [laurent22/joplin#1770]
Hello together,
I want to suggest using the note‘s title as real filename instead of the currently used hash/uuid value.
This would allow much more flexibility when browsing the notes in filebrowsers (eg. if client cannot be installed, or used due to for instance proxy issues). Additionally, existing apps from sync targets (eg. Nextcloud Notes) could be used for easy viewing (or basic editing), which isn‘t really possible right now. 

From my understanding, it should be rather easy without loosing anything. Of course, for filesystem compatibility reasons, a sanitized name should be used without any icons or symbols, but those can be generated rather easy. And the full featured title can still be available in the note’s meta information, in which also the sanitized note's title/filename can be used for references.

Furthermore, Notebooks could be easily managed using folders in such a setting, avoiding (or limiting the need) for notebooks meta information files, just having the type and notebook name.

**Comment by laurent22** [comment]
https://joplinapp.org/faq/#is-it-possible-to-use-real-file-and-folder-names-in-the-sync-target
