### ISSUE TITLE
Row too big to fit into CursorWindow

### ISSUE THREAD

**Issue by b1n4ryj4n** [laurent22/joplin#1771]
Decryption won't work anymore. Always 'Row too big to fit into CursorWindow' occurs.
My largest Note (md file) is 3,4MB remove this Note affect nothing same error occurs.

https://imgur.com/a/4xhWRAV

Info: All my notes are ToDo's without attachments.

## Environment

Joplin version: 1.0.284 (edit: tested it with v1.0.293 both versions now too, same result)
Platform: Android
OS specifcs: Android 9, 3GB RAM, 1,2GB Free RAM, Qualcomm 2.7 GHz quad-core Krait 450

## Steps To Reproduce

0. Disable revisions and set day to 1.
0.1. Add lots of notes in my case 11100 Notes
0.2 Enable Encryption
1. PC (x64) Sync to a Nextcloud instance
2. Sync to Android from Nextcloud (disable also revisions and set day to 1 before initial sync)
3. After first sync is done set the password for decryption
4. After a few seconds this error occurs (https://imgur.com/a/4xhWRAV).

Describe what you expected to happen:

Decrypt my notes.

## Logfile
https://pastebin.com/apTweBsr

**Comment by laurent22** [comment]
Could you try the 32-bit version to see if it makes any difference?

https://github.com/laurent22/joplin-android/releases/download/android-v1.0.293/joplin-v1.0.293-32bit.apk

**Comment by b1n4ryj4n** [comment]
done this already no difference

**Comment by laurent22** [comment]
By the way, do you know what was the 3.4 MB note? I wonder how such a note got into the database initially?

**Comment by b1n4ryj4n** [comment]
Unfortunately i don't know it exactly because all my ToDo's are pretty big i think. Maby ~400 Notes are < 1MB all others are >=1MB

https://imgur.com/a/aG6zb8Z

**Comment by laurent22** [comment]
version?

**Comment by b1n4ryj4n** [comment]
android-v1.0.309

**Comment by laurent22** [comment]
Need to see latest log then.

**Comment by b1n4ryj4n** [comment]
i can post it here if im at home later

**Comment by b1n4ryj4n** [comment]
this is the error i got:
https://imgur.com/a/AL9p6Ha

**Comment by laurent22** [comment]
How large is your largest .md file in the sync target? I've added a limit of 50MB but it looks like you have something that's over 52MB. I guess I will simply increase to 100MB, but I'm wondering if it's just your .md files that are large, or some other issue.
