### ISSUE TITLE
Templates not appearing

### ISSUE THREAD

**Issue by CollinChaffin** [laurent22/joplin#1772]
Latest available build for Windows (installable) 1.61 followed directions on `README.MD` as well as tracked https://github.com/laurent22/joplin/pull/1647 and despite creating the proper `templates` directory within my `C:\Users\USERNAME\.config\joplin-desktop` directory that is in fact indicated as the working config dir in options, and creating a `daily.md` file there (and restarting joplin), I cannot get the templates menu item to appear nor any prompt to use a template.

Is there something else required to get the templates feature to function?  TIA!

**Comment by CalebJohn** [comment]
Unfortunately this is an issue with the way the GitHub documentation works. Templates will be available in the next release (presumably 1.6.11) but are not yet available. 
If you want them now you'll need to build Joplin from source. You can look at build.md for an idea of how that is done.

**Comment by CollinChaffin** [comment]
Okay understood but perhaps just updating the main repo front page README.MD and either removing that section until it's actually implemented or adding a sentence clarifying what build is required would be best. :)

I'm excited to try it but I'm sure you can understand that anyone visiting the repo literally sees that as an active configuration option today as it makes no mention of specific version requirement and even the PR I see (I did dig before opening issue) wasn't very clear as it really does look like it's even gone through several revisions (prompts etc.).

Either way thanks for clarifying and the great work on adding what I'm sure will be a widely-used feature!
