### ISSUE TITLE
"text" mode (no syntax highlighting) is not available in code blocks.

### ISSUE THREAD

**Issue by tsumare** [laurent22/joplin#1773]
Code blocks do not respond correctly when 'text' or 'plain' is listed as the language.  This means that anything that is not in a known language, or which should be treated in a similar 'pre' style manner to code will be highlighted as... I would guess javascript, in Joplin.

Example:
````text
```text
this comes out as code
```
````

Github rendering:
```text
this comes out as code
```

Joplin rendering:
![image](https://user-images.githubusercontent.com/7296913/62000863-bab59480-b0a7-11e9-813e-b4f935533909.png)

## Environment

Joplin version: 1.0.160
Platform: Linux
OS specifics: Ubuntu Xenial

## Steps To Reproduce

1. Create a code block in markdown and attempt to find a language specifier that will render it as text.
2. Try "text", "plain", "unknownLanguageHere"

## Describe what you expected to happen:

Rendering as a code block without syntax highlighting, similar to other renderers such as Github

**Comment by laurent22** [comment]
Triple ticks is for code blocks with syntax highlighting. If you don't want this, you can indent the code block with 4 space or a tab instead.
