### ISSUE TITLE
All deleted notes is a design error

### ISSUE THREAD

**Issue by claudiojulioferraz** [laurent22/joplin#1774]
It's sad that developers don't consider all notes arbitrarily deleted as a bug or bad design. See how the official Nextcloud client works. If your cloud folder is empty will it delete all your files? Think about it.

**Comment by laurent22** [comment]
> If your cloud folder is empty will it delete all your files? Think about it.

Of course it will, that's how two-way sync works. The fact that Joplin doesn't display a warning to prevent users from deleting their own data is a missing feature, not a bug.
