### ISSUE TITLE
TLS errors when trying to sync from terminal app with self-signed certificate

### ISSUE THREAD

**Issue by benallan** [laurent22/joplin#1779]
## Environment

Joplin version: 1.0.141 (prod)
Platform: Linux
OS specifcs: Ubuntu 18.04 terminal

## Steps To Reproduce

1. joplin version
```
joplin 1.0.141 (prod)
```

2. joplin config net.ignoreTlsErrors true 

3. joplin sync
```
Synchronisation target: Nextcloud (5)
Starting synchronisation...
Completed: 2019/08/01 13:28 Last error: FetchError: request to https://cloud.stat.local/nextcloud/remote.php/webdav/Joplin/.sync/ failed, reason: self signed certificate
Downloading resources...
```

Describe what you expected to happen:
Expected the sync to succeed, since I can do the same operation in the Desktop client and it works fine. As far as I can see the settings look the same in both the Desktop and CLI clients too.

## Logfile
Logfile attached.

**Comment by benallan** [comment]
[log.txt](https://github.com/laurent22/joplin/files/3455046/log.txt)

**Comment by tessus** [comment]
Out of curiosity, does it work when you set:

`net.customCertificates`

Comma-separated list of paths to directories to load the certificates from, or path to individual cert files. For example: /my/cert_dir, /other/custom.pem.

But I agree, if `net.ignoreTlsErrors` is set, you shouldn't get any errors. Has this happened with previous versions as well? I'm just trying to narrow down the issue. e.g. is it a regression with this version.

But @laurent22 knows the internals better. Maybe an update of one or more modules screwed things up.

**Comment by benallan** [comment]
It's been happening for me since last year (I think), so I don't think it's due to a recent change. And unfortunately I don't have the certificates on the machine where I'm using Joplin (it's a nextcloud instance set up on an internal company network), so I've left `net.customCertificates` blank.

Since it works fine in the desktop client I'm assuming I've configured the cli wrongly somehow.

**Comment by tessus** [comment]
Doesn't the company provide a cert for their root CA? Anyway, no matter, I was just curious.

>  I'm assuming I've configured the cli wrongly somehow.

No, I think it's a bug, but we'll have to wait for @laurent22's analysis.

**Comment by laurent22** [comment]
Probably the init sequence of the CLI app is not quite right. I'll need to do some tests.
