### ISSUE TITLE
Error on versión update 0.10.48

### ISSUE THREAD

**Issue by Grimpow** [laurent22/joplin#178]
### Operating system

- [ X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [ X] Desktop
- [ ] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*
When applications close and try to install new versión, it fails and only uninstall actual versión but not install new one.

*If there is an error, please copy and paste the full error message*

---

**Comment by laurent22** [comment]
Any additional info?

**Comment by Grimpow** [comment]
I don't hace more info.
I close de program after update notification and then the program only desapears after system permisions alert. Nothing else happens.
I have to install again to use.

**Comment by laurent22** [comment]
It sounds like the app is not handling permissions properly. In which folder did you install the application? Is it in the default one or a custom one? Also what was the permission alert?

**Comment by Grimpow** [comment]
I install the application into the default folder. One alert is the program one, and the other is the system one (I can't get this one into image, but is the windows one), but I accept allways
![joplin alert 1](https://user-images.githubusercontent.com/2331098/35432192-9023a0d6-027f-11e8-8548-81e045498d10.png)

**Comment by Grimpow** [comment]
I tried to install aplication only for me (don't need admin permissions to install), but the problem repeats again

**Comment by laurent22** [comment]
I haven't managed to replicate this yet but in the meantime please download the latest version directly from http://joplin.cozic.net/ as that should fix the issue for now.

**Comment by Grimpow** [comment]
I had download last version directly from your web, but about Windows last version link is: https://github.com/laurent22/joplin/releases/download/v0.10.43/Joplin-Setup-0.10.43.exe
I have problems with update to 0.10.48

**Comment by laurent22** [comment]
Right, looks like I forgot to update the links. Please download it from there for now: https://github.com/laurent22/joplin/releases/tag/v0.10.48

**Comment by Grimpow** [comment]
OK. Thanks and very good job. If I can help you with anything tell me

**Comment by laurent22** [comment]
The new version has a new way to check for update so at least crashes should not happen anymore, so I'm closing for now but feel free to re-open if it happens again.
