### ISSUE TITLE
Question: How can I synchronize my different devices?

### ISSUE THREAD

**Issue by IzyI** [laurent22/joplin#1782]
Friends.  I am trying to make synchronization via file system on my desktop computer.  Everything works and is saved to the /home/user/my_note folder. Then I sync via megasync with my laptop. Then I try to sync my laptop with this folder and change one of the notes. But I get a conflict when saving. The same thing I got when synchronizing my desktop computer and laptop via yandex disk WebDAV.  Why is this happening? And how can I sync multiple of my devices?

**Comment by tessus** [comment]
🚨 The issue tracker is not for questions. 🚨

As it happens, support requests that are created as issues are likely to be closed. We want to make sure you are able to find the help you seek.

## Questions and Help

Please read the [documentation](https://joplinapp.org/) and [FAQ](https://joplinapp.org/faq/) first.

### https://discourse.joplinapp.org/

If you have still questions related to Joplin, please open a topic in the [forum](https://discourse.joplinapp.org/).
You can use your GitHub credentials to login to the forum.

## Links

- Documentation: https://joplinapp.org
- FAQ: https://joplinapp.org/faq/
- Forum: https://discourse.joplinapp.org
- How to enable end-to-end encryption: https://joplinapp.org/e2ee/
- API documentation: https://joplinapp.org/api/
- How to enable debug mode: https://joplinapp.org/debugging/
