### ISSUE TITLE
Pipes in clipped table data break markdown table format.

### ISSUE THREAD

**Issue by philwrenn** [laurent22/joplin#1783]
## Environment

Joplin version: 1.0.160
Platform: Linux
OS specifics: Mint 19.2

## Steps To Reproduce

1. Clip a page that uses tables and has a `|` in the table data. 

Describe what you expected to happen:

Characters essential to building a table with markdown could possibly be escaped. `\|` if contained in the table data.

**Comment by laurent22** [comment]
When reporting a clipper bug, please always include a URL as an example. Even if your description is clear, we still have to search the net for a page like you describe, which can be time consuming.

**Comment by laurent22** [comment]
Fixed in https://github.com/laurent22/joplin-turndown-plugin-gfm/commit/3358d85996313ab18f66b2b75a079a3200d024dd
