### ISSUE TITLE
Webclipping HTML of some websites results in bad styling

### ISSUE THREAD

**Issue by personjerry** [laurent22/joplin#1784]
# Webclipping HTML of some websites results in bad styling

## Steps To Reproduce

1. Clip (HTML) https://science.nasa.gov/science-news/news-articles/3d-biomanufacturing-aboard-the-ISS or https://www.scientificamerican.com/article/the-hunt-is-on-for-alpha-centauris-planets/
2. Observe the styling is all broken in the desktop app rendering

## What Was Expected

Articles that look like the originals

1. <img width="1063" alt="Screen Shot 2019-08-05 at 10 43 13 PM" src="https://user-images.githubusercontent.com/160582/62507445-6eb6ce00-b7d2-11e9-83f1-7a641623231a.png">

2. <img width="1027" alt="Screen Shot 2019-08-05 at 10 42 53 PM" src="https://user-images.githubusercontent.com/160582/62507446-6eb6ce00-b7d2-11e9-8155-94019667fdc4.png">

## What Happened

Styling was completely broken

1. <img width="944" alt="Screen Shot 2019-08-05 at 10 41 40 PM" src="https://user-images.githubusercontent.com/160582/62507394-3b743f00-b7d2-11e9-9edb-e6c43a31aaa6.png">

2. <img width="939" alt="Screen Shot 2019-08-05 at 10 41 02 PM" src="https://user-images.githubusercontent.com/160582/62507393-3b743f00-b7d2-11e9-9f45-a927aa79cccc.png">

**Comment by personjerry** [comment]
Looks like the inliner node app correctly inlines these, could utilize their code: https://github.com/remy/inliner

**Comment by laurent22** [comment]
I've checked but don't know how to fix this at this point. The inliner package would work but we can't use it as we also want to support pages where the user is logged in, and for that we need to process the page directly from the extension.

**Comment by personjerry** [comment]
What is the cause of the problem in particular? CSS not being retrieved properly?

**Comment by laurent22** [comment]
I don't really know. It might also be due to the media queries which results in a particular rendering on the web and a different one on the note.
