### ISSUE TITLE
Import MD with external local images with "Import catalog (MD)"

### ISSUE THREAD

**Issue by mrkingmidas** [laurent22/joplin#1785]
## Environment

Joplin version: 1.0.161
Platform: Windows
OS specifcs: Win10 x64

## Steps To Reproduce

1. Choose MD file OR catalog with MD to import. File contain relative link to local image
2. Notes are created, but image does not import

File:
```MD
# test

![Test](C:/Other/Temp/1.jpg)
```

I am try 
- relative with "\" and "/"
- absolute path
- [comment](https://github.com/laurent22/joplin/issues/640#issuecomment-399492373), but image does not attach to note and link still exist this - at preview its showing, but from "C:/Other/Temp/1.jpg'

Question: How to link to local image in MD for import into Joplin ?

## Logfile
Nothing about import in log files

**Comment by tessus** [comment]
This is not a bug. Images are not imported during import. There are a few topics about this in the forum.

e.g.:
[Embed remote images](https://discourse.joplinapp.org/t/embed-remote-images/2849)

Please use the forum for support questions.
