### ISSUE TITLE
Unable to install it on 32bit windows

### ISSUE THREAD

**Issue by janos-szenfner** [laurent22/joplin#179]
### Operating system

- [ ] Windows

### Application

- [ ] Desktop

Unable to install it on 32bit windows.
Please create a 32bit installer as well.

Thanks

---

**Comment by laurent22** [comment]
I'm afraid it won't be possible to support Windows 32-bit due to a lack of proper support in Electron Builder (it can create the 32bit installer but doesn't compile correctly other modules, Sharp in particular).

**Comment by laurent22** [comment]
Windows 32-bit is supported as of version v1.0.84
