### ISSUE TITLE
Deleted notes are not removed from the Database file

### ISSUE THREAD

**Issue by Perkolator** [laurent22/joplin#1792]
## Environment

Joplin version: 1.0.161
Platform: Windows
OS specifcs: 8.1(.1)

## Steps To Reproduce

1) New installation/database (I just deleted .sqlite and log files from the `C:\Users\<user name>\.config\joplin-desktop` folder, I had no files in resources or tmp folder.
2) Start Joplin.
3) General Options -> Note History -> Disable!
4) Delete "Welcome! (Desktop)" notebook.

	= NOTE! At this point, database.sqlite has 30 items in "deleted_items" table.

5) General Options -> Note History -> Enable & 2 days.
6) Create new "Test" notebook.
7) Create new "Note1" note with "Note1_text" content.
8) Repeat previous step, creating in total 5 different notes with distinct numbers. ("Note2" & "Note2_text" and so on, until "Note5" & "Note5_text")
9) Quit Joplin.

	= NOTE! At this point, database.sqlite has 5 items in "revisions" table. And still 30 items in "deleted_items" table.

10) Wait 1 day (I'm not sure if this is needed, I wanted to make sure that Joplin would make revisions when I edit some of the notes later.)
11) Start Joplin
12) Add "Note1_text_revision" text to Note1, Note3 and Note5, changing the number to match the note number.
13) Quit Joplin.

	= NOTE! At this point, database.sqlite has 9 items in "revisions" table. And still 30 items in "deleted_items" table.

14) Wait 3 days.
15) Start Joplin.
16) Quit Joplin.

	= NOTE! At this point, database.sqlite has 0 items in "revisions" table. And now 48 items in "deleted_items" table.

17) Start Joplin.
18) Remove all "Note1_text" and (where present) "Note1_text_revision" texts (with distinct numbers) from all 5 notes. Add new "Replaced1" texts (with distinct numbers) to all notes.
19) Quit Joplin.

	= NOTE! At this point, database.sqlite has 0 items in "revisions" table. And 48 items in "deleted_items" table.

20) Start Joplin.
21) Quit Joplin.

	= NOTE! At this point, database.sqlite has 5 items in "revisions" table. And 48 items in "deleted_items" table. (I have no idea why I had to start/quit Joplin the second time for the revisions to appear in the database)

22) Wait 3 days.
23) Start Joplin.
24) Quit Joplin.

	= NOTE! At this point, database.sqlite has 0 items in "revisions" table. And 48 items in "deleted_items" table. This time also opening the database.sqlite in plaintext, e.g. with Notepad, I found many occurences of "Note(1-5)_text" strings. Also found "Note1_text_revision" string 1 time and "Note3_text_revision" & "Note5_text_revision" strings 3 times! All of these string should NOT be there anymore!! All of the texts that were in notes and then later replaced with other texts are still in the database file.

25) Start Joplin.
26) Delete the whole "Test" notebook which has the 5 notes.
27) Create new notebook "Something".
28) Create new note "Weird" with "happening" content.
29) Quit Joplin.

	= NOTE! At this point, database.sqlite has 0 items in "revisions" table. And this time 84 items in "deleted_items" table.

30) Wait 3 days.
31) Start Joplin.
32) Quit Joplin.

	= NOTE! At this point, database.sqlite still has 0 items in "revisions" table. And 84 items in "deleted_items" table. Opening the database.sqlite in plaintext, ALL of the note texts that had been deleted or replaced ("Note(1-5)_text", "Note(1,3,5)_text_revision", "Replaced(1-5)") are STILL in the database file! There should be only "Something" notebook, with "Weird" note and "happening" content saved in the database. Either Joplin doesn't do proper cleaning to the database, or SQLite is somehow borked.

## Describe what you expected to happen:
When notes are deleted, they should be removed from the database file (instantly or after revisions expire if the feature is enabled).

The database file could balloon in size if cleanups are not done properly. This poses a problem with e.g. taking automatic backups of the database file to a cloud service that has limited space for storing files.

Also, it's a problem in that when users delete something, they expect that those records are actually deleted and not retained in hidden. This poses a security risk for users as well (even if it is recommended/acknowledged that the system where Joplin operates should be secured by somehow, e.g. full disk encryption).

**Comment by laurent22** [comment]
It seems to work as expected since there's 0 revisions at the end, and deleted_items is just for sync.

I don't know sqlite internal but i assume the data you see is just unreferenced rows, that will be written over by new rows after some time. The database should not balloon in size.

At this point I'm not sure there's a bug here. It's just the way sqlite works. Perhaps we could call VACUUM from time to time, but that has drawbacks too and doesn't feel necessary.

**Comment by Perkolator** [comment]
> I don't know sqlite internal but i assume the data you see is just unreferenced rows, that will be written over by new rows after some time.

That seems to be the case. I tested with importing my Evernote enex file over and over again. It's still shame that SQLite waste space like this. Especially if I'm about to backup the DB to cloud with versioning.

One thing I noticed when I did my "import enex to overwrite" tests; when I had imported the enex file 5 times (added ~300 KB to DB file size every time) and then deleted all the imported notebooks, after a quit->start cycle, reading from the log, "RevisionService" did some operation(s) at the start and the DB grew in size again (about as much as importing my enex file once). That felt unnecessary as no note data was actually added, only DB items to "revisions" table I guess, which would then expire after configured dates.. but, I guess that this won't lower the DB size when that happens. So here is a mechanism that might sometimes in some cases grow the DB file size. But I guess there's nothing that can't be fixed because of SQLite.

After some time, when DB has grown in size, deleted notes might reside in the DB for quite some time, depending of course how much notes are written/deleted.

> The database should not balloon in size.

Should not, but everything I have experienced and read about SQLite, it _might_ be quite the opposite in real life. I vaguely remember some 1-2 years ago I was looking at the ballooning problem of Firefox SQLite DB file. Back then I had the same situation as it is now, I was planning to backup data.

> Perhaps we could call VACUUM from time to time, but that has drawbacks too and doesn't feel necessary.

Here's a good reading IMO of SQLite and vacuuming: https://blogs.gnome.org/jnelson/2015/01/06/sqlite-vacuum-and-auto_vacuum/

> any application using SQLite should devise a VACUUM policy early on.

> One bit of lore spread around is that an SQLite database will grow without bounds if you don’t VACUUM.  That’s not true; free pages will be reused.  Without vacuuming, an SQLite database will expand to its largest size and remain that size.  That’s a little different than growing without bounds.

> At the end of the day, I’ve yet to see a major application relying on SQLite that wasn’t worried about its performance.

***

On a side note/question, related to the DB file size; are there any differences with "notes_fts" and "notes_normalized" tables? Seems to be same data. Could this data be trimmed to just one table?

**Comment by Perkolator** [comment]
> ballooning problem of Firefox SQLite DB file

I found a way to fix that, an addon called "Places Maintenance" (not available anymore, but you can read about it [here](https://www.ghacks.net/2013/09/03/resolve-firefox-bookmarks-history-issues-places-maintenance/)), which did some DB maintenance, including vacuuming.

**Comment by Perkolator** [comment]
I just remembered something about Evernote, it has a similar problem with database file growing. However, in Evernote, pushing CTRL +"help" menu, Evernote reveals lots of hidden commands/settings, including an "optimize database" command.

Implementing at least that kind of manual command would be nice. I'd prefer some kind of automatic maintenance though.

**Comment by laurent22** [comment]
> On a side note/question, related to the DB file size; are there any differences with "notes_fts" and "notes_normalized" tables? Seems to be same data. Could this data be trimmed to just one table?

"notes_normalized" is needed for the search engine. And note_fts is only a view of that other table, (so doesn't take much space) which is needed by FTS.

Regarding the vacuum issue, running it on startup would be slow, and even having tools to do it inside Joplin could cause issues. For example, if sync or other service is running in the background and the database is being vacuumed at the same time. The services would normally fail and recover later but still it's not great.

What you can do if you care about this would be to run it yourself from a cron for example, and using the sqlite command line utility. Personally I think the best is simply to encrypt the whole drive, then you don't have to worry about what each app is putting on your hard drive, you just know that everything is secure.

**Comment by Perkolator** [comment]
> Regarding the vacuum issue, running it on startup would be slow, and even having tools to do it inside Joplin could cause issues. For example, if sync or other service is running in the background and the database is being vacuumed at the same time. The services would normally fail and recover later but still it's not great.

I can't believe a developer would say something like this. Of course one would have to implement the optimizing so that it would not interfere with anything else! For example putting sync/etc. on hold while optimizing. And scheduling the optimizing for example when Joplin/PC is idling.

> Personally I think the best is simply to encrypt the whole drive, then you don't have to worry about what each app is putting on your hard drive

Yeah, but you still don't seem to understand the other problem with DB file size. Taking daily (or even more frequent) versioning backups of even somewhat smallish DB (e.g. 3-5 MB), let alone bigger, to cloud will add up quite quickly. For example my Evernote backups in cloud take 11.83 GB (without dedup), while the DB file size is currently ~5 MB (this is about the low average of what my Evernote DB size is all the time, if I remember to optimize the DB sometimes). So obviously keeping the DB file size at minimum possible will have an effect.

**Comment by laurent22** [comment]
> I can't believe a developer would say something like this. Of course one would have to implement the optimizing so that it would not interfere with anything else! For example putting sync/etc. on hold while optimizing. And scheduling the optimizing for example when Joplin/PC is idling.

You write this as if it's trivial stuff to implement. The app is just not architectured to be able to start and pause services like this, detect idle time, etc. as that would be unnecessary complexity (it's an app not a full blown OS).

Doing what you suggest would take months of development to indeed re-architecture the ap like an OS, and for what? To save a few MB when doing cloud backups? That wouldn't make sense. This is a small app with very few developers working on it, so we need to focus our efforts on things that benefit everyone.

**Comment by Perkolator** [comment]
> The app is just not architectured to be able to start and pause services like this

So the foundation is not that great then if a dev can't "control" his/her creation better. For a dev, hearing some other dev explaining that they can't control their creation is rather surprising.

**Comment by laurent22** [comment]
> So the foundation is not that great then if a dev can't "control" his/her creation better. For a dev, hearing some other dev explaining that they can't control their creation is rather surprising.

It just sounds like you don't know much about software development. You're free to implement you're own note taking app, then you'll understand the challenges.

**Comment by Perkolator** [comment]
Unfortunately it sounds quite the opposite. For example I built a CRM solution to private sector over a decade ago, so I think I know something about the challenges of software development.

**Comment by laurent22** [comment]
Who cares honestly. This is a bug tracker, not the place to discuss what you think or what you did or didn't do.
