### ISSUE TITLE
[Request]  Signed Binaries

### ISSUE THREAD

**Issue by jayma777** [laurent22/joplin#1793]
Please sign the release binaries, and provide the public signing key.   
More info here:    https://gist.github.com/cyphar/21a1b213901a0a0ec19764ac03646ebe

Any released binary (exe, Appimage, apk, etc) should be signed to verify that it is actually coming from you, and has not been altered in transit.

**Comment by tessus** [comment]
👉 Please follow one of these issue templates:
- https://github.com/laurent22/joplin/issues/new/choose

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

Please discuss new features on the forum first - https://discourse.joplinapp.org
(It's possible to sign in with gh credentials.)

P.S.: I'm about to change the feature request template. Only accepted feature requests can be opened on the the gh tracker.
