### ISSUE TITLE
[Feature request] provide .asc file to verify authenticity 

### ISSUE THREAD

**Issue by JayOceans** [laurent22/joplin#1796]
this is a basic security measure!

How can we trust the authenticity of the download without verifying ?

this is Not hard to do...

Thanks !

**Comment by tessus** [comment]
👉 Please follow one of these issue templates:
- https://github.com/laurent22/joplin/issues/new/choose

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

Please discuss new features on the forum first - https://discourse.joplinapp.org
(It's possible to sign in with gh credentials.)

P.S.: I'm about to change the feature request template. Only accepted feature requests can be opened on the the gh tracker.
