### ISSUE TITLE
Import image when paste it with external editor

### ISSUE THREAD

**Issue by m4sk4r4** [laurent22/joplin#1801]
Is it possible implement something where Joplin can import images when we add them using an external editor?

I've added image through clipboard using an external editor like typora or marktext but Joplin does not import it.

![Screenshot from 2019-08-14 22-21-03](https://user-images.githubusercontent.com/36697458/63066717-dad7b700-bee1-11e9-9b61-a1d10c328319.png)

**Comment by tessus** [comment]
It's apparently hard to read. Why the hell don't you read the template??????

🚨 A feature request that has not been accepted on the forum will be closed! 🚨
