### ISSUE TITLE
[LINUX] After latest update all notes are gone.

### ISSUE THREAD

**Issue by RebelCoderRU** [laurent22/joplin#1805]
Latest update made all the notes go away and synchronization option tells me everything is synced. WebDAW settings are still there as wall as all the other settings.

![image](https://user-images.githubusercontent.com/20476773/63103365-de684e00-bf74-11e9-8d22-44365fa48613.png)

![image](https://user-images.githubusercontent.com/20476773/63103379-e7f1b600-bf74-11e9-914e-0541537320ea.png)

![image](https://user-images.githubusercontent.com/20476773/63103434-0a83cf00-bf75-11e9-9a0a-92cee7be30d5.png)

Out of 4 devices that were synced with this WebDAW folder - 0 are visible:
![image](https://user-images.githubusercontent.com/20476773/63103486-27200700-bf75-11e9-8b2a-668e4ef9e651.png)

Few other devices, pointed to that WebDAW notes folder still work just fine.

**Comment by RebelCoderRU** [comment]
UPDATE: Removing all configs and re-setting up Jopling helped:

`sudo rm -r ~/.config/joplin-desktop/`

**Comment by tessus** [comment]
Why do you think, there's a template? So that you can just delete it?

As mentioned min the template, how do you think we shall figure anything out without a debug log file?

**Comment by tessus** [comment]
I'm sorry, but this is really getting annoying that people just ignore the template.

Also, I didn't have this problem, thus I cannot reproduce it. Without a log file that might hint to an error, there's nothing we can do.

**Comment by RebelCoderRU** [comment]
I agree with you, sorry. I should have used the Template. This issue is still there. All notes are gone after a reboot. How do I get a Log file please ?

**Comment by tessus** [comment]
As mentioned in th template:

    Please attach a debug log. Issues without a debug log are likely to stall.
    For information on how to collect a log file: https://joplinapp.org/debugging/

Anyway, there's also a discussion on the forum: [Data lost after update](https://discourse.joplinapp.org/t/data-lost-after-update/3206?u=tessus) Maybe additional info can be found there or you could join the discussion with your info.
