### ISSUE TITLE
Updating Joplin causes the main window to reset dimentions

### ISSUE THREAD

**Issue by narFnarF** [laurent22/joplin#1807]
Every time I install a new update of Joplin, the main Joplin window is resized to it's default dimentions.

## Environment

Joplin version: 1.0.165 (prod, win32)
Platform: Windows
OS specifcs: Windows 10
Note: Does not happen on macOS (I tested on 10.11.6)

## Steps To Reproduce

1. Resize Joplin to the desired dimention, without going fullscreen. For example, I like mine to be around 1200x800px. Screenshot: https://i.imgur.com/R0sFrfQ.png
2. Close Joplin
3. Install a new version of Joplin (for example, I just updated from 1.0.161 to 1.0.165)
4. Launch Joplin
5. Observe that Joplin's window has returned to default dimention. Screenshot: https://i.imgur.com/pL4vjRM.png

Describe what you expected to happen:
Joplin's remember the dimention of its window after updating.

Of course, I understand this is a minor issue, but I though I should submit anyway in case it's an easy fix. Thanks!

**Comment by tessus** [comment]
This is kind of strange, because the dimensions are persistent between Joplin restarts.

I have no idea why the dimensions are reset after an update. @laurent22 would you know why that is?

**Comment by narFnarF** [comment]
I just updated on macOS and I didn't experience the issue. I updated the first post to reflect that.
