### ISSUE TITLE
No automated focusing of the actual line

### ISSUE THREAD

**Issue by nr458h** [laurent22/joplin#181]
### Operating system
- [x] Android

### Application

- [x] Mobile

Actual behavior
When I write that much text, that the whole screen is already used, new lines are behind the keyboard and I need to scroll for every new line.

Expected behavior
When I write a bunch of lines and come closer to the keyboard, there will be an automated focusing of the currently written text, so I always see what i'm writting

**Comment by laurent22** [comment]
This cannot currently be fixed due to the way React Native works.
