### ISSUE TITLE
userstyle.css not loading

### ISSUE THREAD

**Issue by JLKM** [laurent22/joplin#1814]
It seems impossible for me to load my own `userstyle.css` from my Windows 10 notebook.

The issue has previously been reported in the [forum](https://discourse.joplinapp.org/t/userstyle-css-does-not-seem-to-work-in-windows-10/2294), but the proposed solution (total restart) has no effect on my case.

The file is located here: C:\Users\my-name\.config\joplin-desktop\userstyle.css

Bonus info: The new templates load seamlessly from C:\Users\my-name\.config\joplin-desktop\templates\test.md

## Environment

Joplin version: 1.0.165
Platform: Windows 10

**Comment by CalebJohn** [comment]
How do you know that userstyle.css isn't loading? Loading templates and loading userstyle use basically the same code, so it's really odd to have an issue with one and not the other.

**Comment by JLKM** [comment]
Perhaps I could have been more precise. What is evident is, that nothing changes, and the `userstyle.css` is full of colors and other stuff.

**Comment by tessus** [comment]
The location is wrong.

It should be `C:\Users\my-name\.config\joplin-desktop\userstyle.css`

**Comment by tessus** [comment]
I definitely can't reproduce this on macOS and I don't have a Windows machine to test.
Somebody else will have to look into it.

**Comment by JLKM** [comment]
Yes, the location is ok. I just made a typo. But this morning `userstyle.css` shines through. Everything works fine. Thanks for all feedback.
