### ISSUE TITLE
PDF-Export broken: Exporting to PDF causes note content to be cut-off

### ISSUE THREAD

**Issue by evilSwanson** [laurent22/joplin#1815]
## Environment

Joplin version: 1.0.165
Platform: Linux
OS specifcs: Kubuntu 18.04.3 LTS x86_64

## Steps To Reproduce

1. Right-click on any note -> Export -> PDF
2. Open PDF file and see that most of the text is missing

Describe what you expected to happen:
In older versions of Joplin it was possible to export a ordinary markdown note to PDF without any of the content missing in the PDF file. With 1.0.165 only the text which is currently seen in the Joplin markdown-editor is exported and the rest is cut-off. If I scroll down the note only the end of the note is exported to the PDF and the rest is missing. See attached file:
[Example_Export.pdf](https://github.com/laurent22/joplin/files/3513220/Example_Export.pdf)

## Logfile

NO log is generated when exporting to PDF!

**Comment by tessus** [comment]
Yes, we think it is an upstream issue and we are trying to figure out what caused the regression.

see also https://discourse.joplinapp.org/t/pdf-export-and-or-print-issues-with-1-0-165/3197?u=tessus

**Comment by tessus** [comment]
According to Caleb's `git bisect` session, the culprit is 30d0dfb42410c82fdbacc572d6eac98e0c7bd674.

By removing the following line, the problem is fixed.

`document.getElementById('content').style.height = window.innerHeight + 'px';`

@laurent22 do you have any idea why this line screws up PDF export and printing? why was it added in the first place?

**Comment by laurent22** [comment]
Not sure yet but will check.

**Comment by tessus** [comment]
@laurent22 thx. maybe off-topic, but every time I export to PDF (when using a dark theme), the entire UI reverts to a light time for a flash (I guess maybe 1-2s) and then it goes back to the dark theme. Is there any chance we can avoid this?

**Comment by tessus** [comment]
@laurent22 Ok, found something out: removing the line breaks something else. The preview pane does not scroll and is not scrollable anymore.
