### ISSUE TITLE
Android - Tapping Add Body with New Note doesn't work

### ISSUE THREAD

**Issue by Perkolator** [laurent22/joplin#1816]
##  Environment

Joplin version: 1.0.281
Platform: Android
OS specifcs: version 9

## Steps To Reproduce

1. Tap the plus icon, select "new note"
2. Try to tap "Add body" section

= Caret on the text body just flashes quickly then goes off and Android keyboard doesn't come up. Tapping first on "Add title" (not inputting anything, keyboard pops up at this point) and then next tapping the "Add body" finally shows the blinking caret and allows to input data. This doesn't happen when creating a "New to-do".

**Comment by CalebJohn** [comment]
Which version of Android are you on? Can you consistently repeat this? What happens if you uninstall, then reinstall the app?

I'm on Android 8.0.0 and can't repeat this.

**Comment by Perkolator** [comment]
Android 9 like I listed in the report. Security patch level: July 1, 2019. Reproducible.

I'm hesitant to uninstall/reinstall, it's a pain in the rear to add all sync and encryption passwords (very very long). Do you think that it would help in any way? I'm skeptical but if nobody can't confirm this on their devices, I might have to do what you ask just to rule that out. Hopefully more users would comment on this issue with their experience.

**Comment by tessus** [comment]
> Do you think that it would help in any way? 

I doubt it. I can reproduce it as well and Android 9, Joplin 1.0.281.

**Comment by Perkolator** [comment]
Still relevant.

**Comment by plibither8** [comment]
Still not working. Using Android 10. What other details should I furnish?

**Comment by laurent22** [comment]
Strange,I can replicate too and somehow it doesn't affect to-dos
