### ISSUE TITLE
Android - Tapping TOC link in note doesn't jump to correct position at first

### ISSUE THREAD

**Issue by Perkolator** [laurent22/joplin#1817]
## Environment

Joplin version: 1.0.281
Platform: Android
OS specifcs: version 9

## Steps To Reproduce

1. Create a note with a "toc" on top of the note.
2. Add few headers (e.g. H1) and add several lines of text between the headers, simple one letter per line suffices for this test (so that in mobile, the note scrolls, i.e. not a short note that fits mobile screen without scrolling).
3. Save/exit editing mode.
4. Tap any of the toc links on top of the note.

= Screen flashes quickly, like the view is trying to go to the header you just tapped but doesn't eventually. The second tap on any of the toc links finally jumps to the header you tapped.

This problem doesn't happen in Windows desktop version.

**Comment by tessus** [comment]
I can confirm this. Happens on Android, but not on desktop (macOS bin my case) version.

**Comment by Perkolator** [comment]
Not sure if this is fixed by the PR in #2141, I will check the next update and close this if it's fixed.

**Comment by Perkolator** [comment]
This is fixed now, most likely by the #2141.
