### ISSUE TITLE
Android - Tapping same TOC link again doesn't jump to correct position

### ISSUE THREAD

**Issue by Perkolator** [laurent22/joplin#1818]
## Environment

Joplin version: 1.0.281
Platform: Android
OS specifcs: version 9

## Steps To Reproduce

1. Create a note with a "toc" on top of the note.
2. Add few headers (e.g. H1) and add several lines of text between the headers, simple one letter per line suffices for this test (so that in mobile, the note scrolls, i.e. not a short note that fits mobile screen without scrolling).
3. Save/exit editing mode.
4. Tap any of the toc links on top of the note. (you might need to tap it 2 times if #1817 bug is affecting you or hasn't been fixed yet)
5. Now when the view is jumped to the header you tapped, scroll back up and tap the SAME toc header link you tapped in the previous step.

= Nothing happens, the view is not jumped to the header you tapped. Tapping any other toc header link works.

This problem doesn't happen in Windows desktop version.

**Comment by tessus** [comment]
I  remember that we had a similar issue on desktop, but @CalebJohn fixed it.

**Comment by Perkolator** [comment]
Not sure if this is fixed by the PR in #2141, I will check the next update and close this if it's fixed.

**Comment by Perkolator** [comment]
While the "sister issue" #1817 was fixed by #2141, this issue is still not fixed.

**Comment by hetanthakkar1** [comment]
@tessus  @CalebJohn  can i work on this issue.i see no contributors so i can start right!?

**Comment by CalebJohn** [comment]
@hetanthakkar1  Of course go ahead, no need to get permission.

**Comment by Perkolator** [comment]
Still not fixed. Tested again with android version 1.0.329.

**Comment by Perkolator** [comment]
Still not fixed. Tested again with android version 1.0.331.

**Comment by Perkolator** [comment]
Not fixed. Tested again with android version 1.0.333.

**Comment by Perkolator** [comment]
I have never seen a "bug tracker" handled this way, is the goal to piss off users who report issues here? Currently once a month, the idiotic stale bot wants to close issues, 6 times for this issue already. You don't want people reporting issues? You want them to go away?

**Comment by Perkolator** [comment]
I'll close this so you don't have to bother anymore..
