### ISSUE TITLE
support checkbox markdown plugin

### ISSUE THREAD

**Issue by nr458h** [laurent22/joplin#182]
### Operating system
- [x] Android

https://www.npmjs.com/package/markdown-it-checkbox

It would be cool to create checkboxes especially for tasks, so i can see whats done or to be able to create checklists for repeatedly tasks

**Comment by mikeziri** [comment]
you can use "[ ]" and "[X]"

**Comment by laurent22** [comment]
Yes the syntax would be `- [ ]`. I've added this to the doc

**Comment by richardcmckinney** [comment]
@laurent22 Just to confirm, that would provide check boxes but wouldn't support repeated tasks - is that right?

**Comment by laurent22** [comment]
@richardcmckinney, yes this is just to provide checkboxes. Repeated, or recurring, tasks are not currently supported.
