### ISSUE TITLE
Note History doesn't show note texts of revisions made in mobile

### ISSUE THREAD

**Issue by Perkolator** [laurent22/joplin#1820]
## Environment

Joplin version: Windows 1.0.165, Android 1.0.281
Platform: Windows, Android
OS specifics: Windows 8.1(.1), Android 9

## Steps To Reproduce

This is a bit tricky since sometimes a revision is created (shown in Note History) (almost?) after just creating/editing a note but sometimes not. There must be a "revision worker" or something like that that runs periodically which affects this behavior.

1. On mobile, create new note.
2. Add one word in note, e.g. "Mobile1", and exit note.
3. Sync mobile, then desktop.
4. Wait at least 15 minutes.

5. On desktop, edit the note and add one word to the note, e.g. "Desktop1".
6. Sync desktop, then mobile.
7. Wait at least 15 minutes.

8. On mobile, edit the note and add one word to the note, e.g. "Mobile2".
9. Sync mobile, then desktop.
10. Wait at least 15 minutes. (Maybe optional, I got 3 revisions on desktop without waiting this period.)

11. On desktop, go to Note History (i-icon -> "Previous versions of this note")

= There should be three revisions in the drop-down box, and first one (latest made in mobile) is selected. The note view doesn't show the note revision text at all.

Selecting the 3rd revision (first made in mobile) the note view doesn't show note revision text at all.

Selecting the 2nd revision (made in desktop) shows the note revision text (with "Mobile1" and
"Desktop1" words). After that, selecting the 1st or 3rd revision (both made in mobile) doesn't change the revision note text view, the 2nd note revision text is still shown.

Restoring a note revision that doesn't show the text in the Note History still works ok.

**Comment by Perkolator** [comment]
Anyone able to reproduce?

**Comment by laurent22** [comment]
Can't replicate

**Comment by Perkolator** [comment]
Seems that some recent change has fixed this problem too. Can't reproduce with latest versions anymore.
