### ISSUE TITLE
Contrast of Message in Tool-Encryption Options Theme solarized (both)

### ISSUE THREAD

**Issue by merlinuwe** [laurent22/joplin#1826]
The text in Tools-Encryption Options

`For more information about End-To-End Encryption (E2EE) and advices on how to enable it please check the documentation: 
![Contrast-light](https://user-images.githubusercontent.com/4138869/63578026-e7b67380-c58f-11e9-85dc-290de4dd1be2.png)
![Contrast](https://user-images.githubusercontent.com/4138869/63578038-eedd8180-c58f-11e9-96f3-ff0779f9f85b.png)

rg/e2ee/`

has a bad contrast and is difficultly readable.

The problem is mainly visible in the dark solarized-dark but also in the solarised Light Theme.

## Environment

Joplin version: 1.0.165
Platform: Windows (I suspect, that this ocures on every platform)
OS specifcs: Windows 10

**Comment by merlinuwe** [comment]
The text "Weitere Informationen zur Ende-zu-Ende-Verschlüsselung (E2EE) und Hinweise zur Aktivierung findest du in der Dokumentation (auf Englisch):" is still not really readable.

(How can I label the issue as "backlog"?)

**Comment by laurent22** [comment]
@merlinuwe, no need to add the backlog tag. I've assigned it to myself so it shouldn't be auto-closed.
