### ISSUE TITLE
Reminder prompt bug

### ISSUE THREAD

**Issue by whisperdancer** [laurent22/joplin#1829]
## Environment

Joplin version: Windows desktop 1.0.165
Platform: Windows
OS specifcs: Windows 10

## Steps To Reproduce

1. Add a new to do note, set the reminder to Nov 10, 2019
2. Every time I start Jopline, the reminder pops up. It should prompt me until Nov 10

Describe what you expected to happen:

I set a to do note and set the reminder. It should prompt me at the date and time I set the reminder. Not before then.

**Comment by tessus** [comment]
I can confirm this.

The reminder also shows up right after I have added a reminder. I'm on macOS. @laurent22 can you direct me to the reminder and notification code? I can have a look.

**Comment by tessus** [comment]
@laurent22 Can you confirm this on your side? I still have the same issues as the OP and the one I described.

**Comment by laurent22** [comment]
I don't know I've never tested this, but I'll check.

**Comment by foxmask** [comment]
Same on linux

**Comment by foxmask** [comment]
fixed with 1.0.170
