### ISSUE TITLE
Android typing in note super slow

### ISSUE THREAD

**Issue by whisperdancer** [laurent22/joplin#1830]
## Environment

Joplin version:1.0.281
Platform: Android Pi
OS specifcs:

## Steps To Reproduce

1. Add new note or edit existing note. I noticed that now Joplin saves the note as I'm typing. Problem is typing lags very badly. I can type several characters and they lag before showing up.  I suggest making auto save an option, off by default. I surmise the lag is due to saving the note after each keystroke.
2.

Describe what you expected to happen:

**Comment by virtadpt** [comment]
Can confirm.  It's been happening on my Android tablet (Nexus 7, Android v6.0.1) (Joplin v1.0.281) and phone (Samsung SM-G965U, Android v9) (Joplin v1.0.281) (though to a lesser extent on my phone) for a couple of weeks now.

**Comment by m-p-3** [comment]
Could be related to #1493

**Comment by shreyasbharath** [comment]
Thanks for the great work on this app, I love it.

However, the app is near unusable for me, note taking should be unhindered and buttery smooth.

Can we do something about this laggy typing experience?

**Comment by laurent22** [comment]
Closed as donate
