### ISSUE TITLE
IOS App Encryption bug during sync

### ISSUE THREAD

**Issue by whisperdancer** [laurent22/joplin#1831]
## Environment

Joplin version: Latest version
Platform: IOS
OS specifcs:

## Steps To Reproduce

1. Sync notes and see note displayed as encrypted. It stays that way. Tapping on it does nothing. I have to swipe off the app and start again. Then the encrypted note disappears and I can see the note as normal.
2.

Describe what you expected to happen:

**Comment by tessus** [comment]
@whisperdancer `lastest version` might be understood right now (on the day of opening the bug), but in 2 months it won't tell us anything. Also, I certainly do not know the version off the top of my head.

@laurent22 wasn't there a topic on the forum? I'm not sure, but this might be fixed already. It's hard to tell. The iOS release is once again very far behind.
