### ISSUE TITLE
Markdown checkboxes uncheck themselves upon Synchronization

### ISSUE THREAD

**Issue by deisner** [laurent22/joplin#1832]
## Environment

Joplin version: 1.0.165 (prod, win32) 
Platform: Windows
OS specifcs: Windows 10 Enterprise

## Steps To Reproduce

1. Create a new note (Ctrl + N)
2. Create a few checkbox items with Markdown (e.g. `* [ ] Here is an item`).
![image](https://user-images.githubusercontent.com/742277/63717497-6886a100-c816-11e9-8ce8-66e199cdbb6b.png)

3. Check-off a checkbox:
![image](https://user-images.githubusercontent.com/742277/63717528-7e946180-c816-11e9-8dfe-9f00a543e994.png)

4. Wait for Joplin to Syncrhonize.

Describe what you expected to happen:
I expect the checkbox to remain in the checked state after Joplin synchronizes, but what happens instead is it unchecks itself:
![image](https://user-images.githubusercontent.com/742277/63717657-bac7c200-c816-11e9-9e70-3d4be9d06455.png)

## Logfile

webdev console:
![image](https://user-images.githubusercontent.com/742277/63718272-3413e480-c818-11e9-9a15-11195e9b0352.png)

Last 500 lines of log.txt:

[log-tail-500.txt](https://github.com/laurent22/joplin/files/3542662/log-tail-500.txt)

**Comment by laurent22** [comment]
Yes let's leave it open. I'll change the plugin so that it doesn't render that markup as a checkbox to make it less confusing. Only supported syntax is with a dash.
