### ISSUE TITLE
Icon missing on Gnome

### ISSUE THREAD

**Issue by m0rph84** [laurent22/joplin#1839]
## Environment

Joplin version: 1.0.165
Platform: Linux
OS specifcs: Pop!_Os (Ubuntu) - 5.0.0-25-generic x86_64

## Steps To Reproduce

1. Icon not showing up after installation

I've found a similar issue reported [here](https://github.com/laurent22/joplin/pull/1110) that was fixed in January.

![Screenshot joplin](https://user-images.githubusercontent.com/13459076/64017836-1e553680-cb1a-11e9-9318-0ce7bc7093f9.png)

**Comment by m0rph84** [comment]
Weird thing, the icon showed up after installing the Alacarte app.
No actions required, just launched the app and the icon was there.

**Comment by CalebJohn** [comment]
I think it might have appeared if you had logged out and back in as well. This looks to me like a gnome issue. But I wonder if there's something that can be done on the Joplin end to refresh the desktop files.
