### ISSUE TITLE
Terminal Client: Editor save does not save changes to note in joplin

### ISSUE THREAD

**Issue by Gidgidonihah** [laurent22/joplin#184]
### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [X] Terminal

I've been testing out joplin for my work notes over the past week and there is one issue that interferes with my workflow. **Saving a node in my `EDITOR` does not save the changes within joplin until I quite the editor**

Throughout my workday I have a terminal tab open where I add/remove notes. Until now I've simply used a .md file in the root of the repo for which my notes applied. I simply kept the file open in vim and saved as I made changes. Time Machine took care of making sure I had a backup. It was super simple and there were downsides. So I gave joplin a try.

After switching over, I simply open my note from joplin, it will open it in my editor (VIM) and I  can then work as I had before. Very quickly I found out that regardless of how many saves I made to the file, none of them were saved to joplin. If I left that file open after saving many changes and maybe accidentally closed the terminal tab, all my changes would be lost. If I opened joplin in another tab to maybe edit a different note, the changes were not reflected.

I'd like to have the changes synced to joplin any time the editor saves changes to the temporary file that was opened.

### To Reproduce:
1. Create a note in joplin and begin editing it
1. make changes and save the file without exiting the editor. (Expect that the changes are reflected in joplin)
1. kill the joplin process in any way that you choose (close tab, manually kill the process, run out of batter)
1. Restart joplin and notice that the changes you made and saved in your editor are missing.

**Comment by laurent22** [comment]
Agree, ideally the edit command should watch the file and commit changes automatically. By the way, if you ever lose any change due to a crash you can find the file you were editing under $HOME/.config/joplin/tmp

**Comment by zsunberg** [comment]
Is this the same problem as #710/#766/#1614? or does the terminal use something different than ExternalEditWatcher?
