### ISSUE TITLE
Android - Empty or incorrect note properties when Swiping from right edge

### ISSUE THREAD

**Issue by Perkolator** [laurent22/joplin#1840]
Here's steps to reproduce two very similar bugs, which I believe stems from the same code problem, hence I coupled both cases in this one report.

## Environment

Joplin version: 1.0.281
Platform: Android
OS specifics: version 9

## Case 1 - Empty properties - Steps To Reproduce

1. Exit Joplin & close it from the system app switcher. (this needs to be done in case user has already once opened the properties view from the 3 dots menu and Joplin is still running)
2. Open Joplin.
3. Select any existing note.
4. Swipe from the right edge of the screen to the left.

= Properties view is empty.

## Case 2 - Incorrect properties - Steps To Reproduce

Prerequisite: Two different notes that have different "Created" or "Updated" dates!

1. Open the first note.
2. Open "Properties" from the 3 dots menu.
3. Remember the dates shown in the properties view.
4. Close note and open a different note.
5. Swipe from the right edge of the screen to the left.

= Properties view shows the previous note properties. You can confirm this by opening "Properties" from the 3 dots menu for this note too, now the dates change to correct ones.

***

It seems that the note properties view is not "loaded/initialized" when opening it with a swipe gesture.

Also the note properties on Android (all mobiles?) lacks information that is available in e.g. Windows desktop application.. unfinished feature?

**Comment by laurent22** [comment]
I believe this has been fixed in the latest version.
