### ISSUE TITLE
Android - Date Format not honored in Note Properties

### ISSUE THREAD

**Issue by Perkolator** [laurent22/joplin#1841]
## Environment

Joplin version: 1.0.281
Platform: Android
OS specifics: version 9

## Steps To Reproduce

1. Go to "Configuration".
2. Select any other date format than the first in the list (30/01/2017), e.g. "2017-01-30".
3. Save and exit.
4. Open any note.
5. Open "Properties" from the 3 dots menu.

= Wrong date format is shown for "Created" and "Updated" dates.

**Comment by tessus** [comment]
fixed in d45d1b4225d6409997356e31323f8fa8fdc9efa1

will be available in the next release
