### ISSUE TITLE
TOC with lots of Headings affects the Raw & Rendered view sync

### ISSUE THREAD

**Issue by Perkolator** [laurent22/joplin#1842]
## Environment

Joplin version: Windows 1.0.165
Platform: Windows
OS specifics: Windows 8.1(.1)

## Steps To Reproduce

1. Download and import/paste this md test file to Joplin: [test.md.txt](https://github.com/laurent22/joplin/files/3561612/test.md.txt)
2. Change the layout to side-by-side raw & rendered view.
3. Scroll the note.

= The side-by-side view is badly synced, the bigger the TOC, the more it gets out of sync obviously. The view catches up the further one scrolls.

Real world scenario (if somebody wondered): List of books to read/rent, author names used in headings.

**Comment by tessus** [comment]
We are using a plugin for toc.

Can you please open a ticket with the [markdown-it-toc-done-right](https://github.com/nagaozen/markdown-it-toc-done-right) repo?

**Comment by Perkolator** [comment]
Maybe there's a misunderstanding, the problem is with Joplin's side-by-side raw & rendered view sync when scrolling. I don't see how the TOC plugin author would fix this.

The problem is that the synced side-by-side view in Joplin doesn't take account the difference of raw text Vs. rendered view of the TOC. The raw text of TOC is only 1 line, while the rendered view of TOC might be tens/hundreds/x of lines.

I don't have a clue how this could be fixed... except implementing a WYSIWYG editor view (which I see you have discussed about in the forum). :) But even after that (hopefully it happens some day), the side-by-side view would still be affected.

**Comment by tessus** [comment]
Ah, I see. Yes, you are right, this is a Joplin issue. My bad. Let's see if @laurent22 has an idea how this could be fixed.

**Comment by laurent22** [comment]
Yes that's a limitation of the current editor, when the Markdown text results into a much bigger rendering (i.e. toc is one line in Markdown, but potentially dozens in HTML), in that case the scrolling will be out of sync. There's no fix unless we change the Markdown renderer.

**Comment by Perkolator** [comment]
And the Markdown renderer is imported component and can't be fixed?

**Comment by laurent22** [comment]
Probably not. As I understand, fixing that issue would require a complete rewrite.

**Comment by Perkolator** [comment]
> There's no fix unless we change the Markdown renderer.

I was reminded of this now after I submitted another bug (#1867) and wondered if that is also not fixable, unless the renderer is rewritten. Is the renderer Joplin's own code, or is it another project imported to Joplin? I mean could we delegate this to upstream? Or is it up to Joplin repo to rewrite it?
