### ISSUE TITLE
Date variables in templates are using time of app startup, not system time

### ISSUE THREAD

**Issue by xtyfus** [laurent22/joplin#1844]
## Environment

Joplin version: 1.0.165
Platform: Windows 
OS specifcs: Windows 10 (1903)

## Steps To Reproduce

1. Create template with text `{{datetime}}` in it.
2. Refresh templates
3. Use `ctrl + alt + i` to insert template in current note

Same happens, if new note created.

## Logfile

Nothing related in logfiles

**Comment by tessus** [comment]
AFAIK this has been fixed already, but @CalebJohn would know for sure.
If it has, it will be available in the next release.

**Comment by CalebJohn** [comment]
@tessus, you're right, it's been fixed and merged.

**Comment by tessus** [comment]
Thanks for the info. In this case we can close this ticket.
