### ISSUE TITLE
[Feature request] Any possibility to have an AppImage of the cli build?

### ISSUE THREAD

**Issue by sevaho** [laurent22/joplin#1848]
🚨 A feature request that has not been accepted on the forum will be closed! 🚨

**Comment by sevaho** [comment]
reason to close?

**Comment by tessus** [comment]
I think it should be obvious. In the template (not even as a comment) it says it very clearly:

🚨 A feature request that has not been accepted on the forum will be closed! 🚨

Then right after it says:

Feature requests without a link to the discussion/topic on the forum will be closed.
