### ISSUE TITLE
NoteTag do not get deleted when associated Note or Tag gets deleted

### ISSUE THREAD

**Issue by personjerry** [laurent22/joplin#1849]
NoteTag objects in the database do not get deleted when associated Note or Tag gets deleted, but they should be because they are no longer meaningful at that point. The result is gradual but permanent bloat in the size of the database.

## Environment

Joplin version: 1.0.165
Platform: All
OS specifcs: All

## Steps To Reproduce

1. Make a few notes
2. Add tags to some of them
3. Delete all the notes
4. View the sqlite database
5. Observe note_tags still has rows

Describe what you expected to happen:

When a Note or Tag is deleted, related NoteTags association should eventually also be deleted.

**Comment by personjerry** [comment]
Since

1) existing users may already have such bloat

2) there's no system in place for cascading deletion of objects

3) there's relatively few cascading objects

I think setting up a periodic cleanup is the best choice

**Comment by tessus** [comment]
Can you please use the forum for discussions? The tracker is only for reproducible bugs and for accepted feature requests (only if there's been a discussion on the forum and the FR was accepted or if asked by a moderator to open a FR on gh).

**Comment by personjerry** [comment]
@tessus The database bloat is indeed reproducible. Is this not considered a bug?

**Comment by tessus** [comment]
This is a good question. It could be, but that's why the forum should be the first place to go.

I can re-open the issue, if you use the template. e.g. maybe @laurent22 has already fixed it, but we don't know which version you are talking about. steps to reproduce also makes it easier to read a bug report. The template is there for a reason. I get that people don't want to read what it says, but it's important for us to ascertain the validity of a report and helps with narrowing down a problem.

**Comment by laurent22** [comment]
This is a more complicated problem to solve than it seems. If a note_tags item refer to a note that doesn't exist, it can mean two things:
- The note has been deleted
- The note has not been received via sync yet.
In the first case, we can delete the note_tags item, but in the second we cannot. That's why it hasn't been done yet, and I'm open to suggestion on how to implement this in an efficient way.

**Comment by personjerry** [comment]
@tessus I've edited with the recommended format.

@laurent22 One solution may be to have the garbage collection system check for synchronizer idle state, or even better share a mutex with the synchronizer.

**Comment by tessus** [comment]
@laurent22 I've re-opened the issue to track it.

> One solution may be to have the garbage collection system check for synchronizer idle state, or even better share a mutex with the synchronizer.

Idle state alone would probably not be enough to query the state. e.g. what would happen, if you killed the sync process by killing the app? or if you had no internet connection (turned off data on your phone, or no connection on your desktop)?

Maybe we could create a lock (a status entry in the settings table) in the database until a sync is truly complete. Only when the "lock" record is gone, we can start deleting the `note_tags` items.
@laurent22 Would that approach work?

**Comment by laurent22** [comment]
> Maybe we could create a lock (a status entry in the settings table) in the database until a sync is truly complete. Only when the "lock" record is gone, we can start deleting the `note_tags` items.

It wouldn't work if another client is syncing at the same time. In that case, client 1 might think sync is finished, but in fact client 2 is still going to send more items. It might even send these items several days later, for example if the device was switched off before sync is finished.

For resources, I've implemented a service that keeps track of what resource is associated with what notes and use various heuristics to decide when a resource can be safely deleted. But it's a bit complex so I'd prefer to find a better solution for tags.

**Comment by tessus** [comment]
Thanks for the info.

**Comment by personjerry** [comment]
> It wouldn't work if another client is syncing at the same time. In that case, client 1 might think sync is finished, but in fact client 2 is still going to send more items. It might even send these items several days later, for example if the device was switched off before sync is finished.

I believe this is the same problem with syncing and deleting anything else in general, and my understanding is that we solved this with the DeletedItems table. Is there any reason that doesn't apply here?
