### ISSUE TITLE
[Feature request] Simple text editing

### ISSUE THREAD

**Issue by beefeater7** [laurent22/joplin#1855]
I'm looking for a Markdown editor without fancy automation. When I enter text, I don't want the program to inject indentation at line breaks or whatnot. Just notepad style behavior. My reason is a bit niche; I use an alternative input method that demands predictable behavior... Plover stenography if you're curious. 

I figured it's easy to implement if you know the code base, you're just stripping away functionality right? If it's a hassle though, I can look into it... just give me some pointers.

**Comment by tessus** [comment]
Did you read the template?
