### ISSUE TITLE
Request: Joplin in ipad Appstore

### ISSUE THREAD

**Issue by sunjam** [laurent22/joplin#186]
Joplin is not listed in the **ipad** iOS Appstore at all, but I was able to retrieve it directly from the link on your github page.  Sizing of the screen is off, all elements of the screen are very large on the 2017 ipad retina display, so I’m assuming the app was just formally released for the iphone.  I’m not sure what is needed for an ipad-specific release, but just want to let you know. Thanks.
    
![b87a9fa1-2a5a-4a2c-bc04-fc777788fdfb](https://user-images.githubusercontent.com/1787238/35485754-a7ab2f68-0418-11e8-9622-daaa4ca8caef.png)

**Comment by laurent22** [comment]
The latest version should work with iPad. Any chance you could test and confirm?

**Comment by jcgerhard** [comment]
I have installed it on my iPad Air today. Will run some tests (create/edit/delete/...) tomorrow during the run of the day. Hope I can write some comments tomorrow evening. 👍

**Comment by sunjam** [comment]
Ipad 2017 retina display of notes work on version 1.0.15

**Comment by jcgerhard** [comment]
Joplin 1.0.15 on iPad Air 2 (late 2014) works as expected! 👍

**Comment by laurent22** [comment]
Great, thanks @sunjam and @jcgerhard for confirming it works!
