### ISSUE TITLE
Upgrade styles in the import screen

### ISSUE THREAD

**Issue by devonzuegel** [laurent22/joplin#1862]
_Original discussion: [discourse.joplinapp.org/t/upgrade-styles-in-the-import-screen/3446](https://discourse.joplinapp.org/t/upgrade-styles-in-the-import-screen/3446)_

Right now, when you do a new import (`File` > `Import` > `[importer of choice]`), you get a simple page that asks you nicely to please wait until it's complete. Let's spruce it up a bit by simplifying the language, shortening the path, adding a little loader animation, and adding some nice styles to it.

![image](https://user-images.githubusercontent.com/6979755/64496877-46514200-d25e-11e9-9c23-4d648a8464fe.png)

**Comment by CalebJohn** [comment]
This same screen appears during export, should be possible to apply the same face lift to both!

**Comment by tessus** [comment]
added via #1888
