### ISSUE TITLE
[Feature request] Dracula dark theme

### ISSUE THREAD

**Issue by codeshiftr** [laurent22/joplin#1863]
An option for choosing the awesome Dracula dark theme would be highly appreciated.
[https://draculatheme.com/](https://draculatheme.com/)

![vim](https://user-images.githubusercontent.com/44362668/64560273-7bd25a00-d348-11e9-8364-a35e1436fb26.png)

**Comment by tessus** [comment]
I'm sorry. Did you read the trmplate?
