### ISSUE TITLE
Rendered Markdown hyperlinks are preceeded with Joplin "J" logo.

### ISSUE THREAD

**Issue by deisner** [laurent22/joplin#1864]
## Environment

Joplin version: 1.0.66 (prod, win32)
Platform: Windows
OS specifcs: Windows 10 Enterprise v. 1903

## Steps To Reproduce

1. Add a hyperlink to a Markdown note, where the URL does not end in a forward slash.

Describe what you expected to happen:

I expect to see the link rendered without a Joplin 'J' logo character, but one is there. If I add a trailing slash to the URL, there is no 'J' logo.

![image](https://user-images.githubusercontent.com/742277/64561937-cb4d6180-d319-11e9-814f-8ef11de6c99e.png)

## Logfile

There's an error in the devtools console, but I think it's unrelated -- the error happens even if I don't use Ctrl+K to add the URL.

![image](https://user-images.githubusercontent.com/742277/64561977-de603180-d319-11e9-83b5-bd002094f166.png)

No errors in log.txt.

**Comment by genneko** [comment]
I see this on 1.0.166, too. A URL rendered with "J" logo looks clickable but doesn't work as a hyperlink.

**Comment by seth100** [comment]
Yes I have this issue too. All of my links now are not clickable anymore O.o, it says something like "element with ID ... does not exist".

**Comment by laurent22** [comment]
Fixed in e03ef78049c8da066dc93f0c97fdabf660e15439
