### ISSUE TITLE
Clicking TOC link doesn't scroll the RAW view to correct position in side-by-side editor layout view

### ISSUE THREAD

**Issue by Perkolator** [laurent22/joplin#1867]
## Environment

Joplin version: 1.0.167
Platform: Windows
OS specifcs: Windows 8.1(.1)

## Steps To Reproduce

Note! If you test this multiple times (or try the optional choices), you first need to scroll the test note back to the top, then go to another note and back to the test note.

Prerequisite: Select side-by-side RAW & rendered view.

1. Paste/import the following test file to Joplin: [test2.md.txt](https://github.com/laurent22/joplin/files/3600678/test2.md.txt) (or test with your own note that has several TOC links)
2. Click any of the TOC header links.

= The rendered view is scrolled to correct position, but the RAW view isn't.

3. (Optional)

    A) Scroll down or up with mouse on top of the rendered view -> the RAW view finally scrolls/syncs to correct position.

    B) Scroll down with mouse on top of the RAW view -> the rendered view is scrolled/synced to the top of the note.

**Comment by laurent22** [comment]
I cannot replicate it. If for example, I click on "J", both views scroll down to "J".

**Comment by Perkolator** [comment]
I can still replicate it on 1.0.170 Windows, every time.

Did you follow the following advice?

> Note! If you test this multiple times (or try the optional choices), you first need to scroll the test note back to the top, then go to another note and back to the test note.
