### ISSUE TITLE
ElectronClient: menu bar missing

### ISSUE THREAD

**Issue by mhdry** [laurent22/joplin#1869]
May not be a bug, but: I've recently upgraded from Joplin 1.0.165 to 1.0.167. The ElectonClient doesn't show the menu bar anymore. 
I'm compiling from source/git-checkout with npm. Maybe I've missed something? This is the case for 32-Bit and 64-Bit compiles (Ubuntu LTS with npm from Node-Repository).

Joplin version: 1.0.167
Platform: Ubuntu 18.04 LTS
OS specifcs: NPM from deb.nodesource.com/node_8.x repository

**Comment by tessus** [comment]
This does not seem to be reproducible. Can you please try 1.0.170? If you run into any issues, please post on the [forum](https://discourse.joplinapp.org/). This tracker is for reproducible bugs.
