### ISSUE TITLE
[Feature request] Dark Menu Bar Desktop APP

### ISSUE THREAD

**Issue by MKastuv** [laurent22/joplin#1873]
I have been using desktop Joplin app in a dark-mode, would be great to see menu bar in a dark theme just like VS-CODE. 

- JOPLIN Dark Mode:
![image](https://user-images.githubusercontent.com/26562660/64972920-bcadff80-d86f-11e9-8b8a-accf93d03303.png)

- VSCODE Dark Mode:
![image](https://user-images.githubusercontent.com/26562660/64973207-36de8400-d870-11e9-8b82-50ecea536767.png)

**Comment by vBLFTePebWNi6c** [comment]
Why this issue was closed?

**Comment by tessus** [comment]
Because the OP ignored the template. Feature requests are done in the forum.
