### ISSUE TITLE
Web capture only captures the question from Stackexchange pages

### ISSUE THREAD

**Issue by gerroon** [laurent22/joplin#1874]
Hi

It seems like anytime I try to capture anything from Stackexchange in a simplified way, it captures only the original question and not the answers.

Open the page below and capture the page with "Clip simplified page"

https://blender.stackexchange.com/questions/7779/python-api-multiple-types-in-single-uilist-dynamic-memory-allocation-for-seria

**Comment by laurent22** [comment]
Joplin uses Readability to capture simplified pages, so you might want to report that to them: https://github.com/mozilla/readability Since it concerns a major website, they might do something about it.
