### ISSUE TITLE
Web Clipper doesn't format heading anchors correctly

### ISSUE THREAD

**Issue by charmanjoe** [laurent22/joplin#1876]
```
Clipper version 1.0.18 for Firefox
Joplin for Desktop version 1.0.167 on Windows 10
Joplin 10.0.37 iOS
```
For example try "Clip complete page" of [this ](https://wiki.52pi.com/index.php/ICE-Tower_CPU_Cooling_Fan_for_Raspberry_Pi_SKU:_EP-0107).  The first link under "## Contents" is:
`*   [1 ICE-Tower CPU Cooling Fan for Raspberry Pi](#ICE-Tower_CPU_Cooling_Fan_for_Raspberry_Pi) ` 
Clicking this link does nothing. Changing it to the following makes it work:
`*   [1 ICE-Tower CPU Cooling Fan for Raspberry Pi](#ice-tower-cpu-cooling-fan-for-raspberry-pi)`
According to [this](https://gist.github.com/asabaylus/3071099#gistcomment-1593627), the code should:
1.  Downcase the string
2.  remove anything that is not a letter, number, space or hyphen (see the source for how Unicode is handled)
3.  change any space to a hyphen.
4.  If that is not unique, add "-1", "-2", "-3",... to make it unique

And it seems to only work on the desktop application. On the iOS app, when I tap a heading link the screen flashes and remains at the top of the page. Any heading link just sends you to the top of the note.

**Comment by dayfuaim** [comment]
Yes, I confirm this.

**Comment by NJannasch** [comment]
I would like to work on this.
