### ISSUE TITLE
Search engine improvements

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#1877]
This issue is to list the features that need to be improved on the search engine.

- Remove the need for wildcard queries - for example instead of typing "search*", it will be possible to simply type "search" and results that contain "search" or "searching" will be included. Those that contain the exact match will come first.

- Search within certain tags (eg. "tag:software search" to search within the notes tagged with "software" and that contain the word "search").
- Improve relevance algorithm (give a weight to certain criteria, and allow adding new criteria more easily)

- Allow fuzzy search (for example return results that contain "saerch" for the query "search")

**Comment by jjon** [comment]
especially boolean tags yes? search: tag:linux and tag:osx

**Comment by laurent22** [comment]
> especially boolean tags yes? search: tag:linux and tag:osx

I don't think boolean queries are still a thing in search engines. Rather, results are sorted by relevance - those that contain both terms come first. Those that contain only some of them come next, or are not included in the results at all.

**Comment by foxmask** [comment]
i created #293 about that ;)

**Comment by indirection** [comment]
"Search in all notes" ideally would move to the next matching occurrence of the search string as the key "return" or "Enter" is pressed and released; placing the next found highlighted sting in the middle of the displayed text.

**Comment by ergcode** [comment]
I think it would be better to do a search as follows:
- We need modifiers (interface buttons) "strict match" and "search by case". Remember the modifier state on a new search or restart.
- By default, need to set the search to "searchString*", that is, search by part of the word. But without specifying "*".
- Search for tags with the substitution "#tag". Add the ability to use the combination "#tag searchString". However, search modifiers should not affect the tag.
- Maybe should do a search everywhere. By string and tags simultaneously, without specifying the type "tag searchString". But then a more sophisticated search engine will already be needed, since relevance will be needed.


P.S. Thanks for the app! It is most suitable for programming tasks and storing snippets.

**Comment by 20manas** [comment]
Hey everyone,
This seems like a really interesting issue to work on. I'd love to work on this.

**Comment by JekRock** [comment]
Searching notes by tags and tags combination is really cool feature to have

**Comment by 0xMH** [comment]
Is it possible to search within a note list? In my case, I've this huge notebook with dozens of notes and It'd be awesome to search within the notebook itself for the note's subject. Maybe adding a small search bar on top of a note list.
![image](https://user-images.githubusercontent.com/12420351/77908431-c63b0a00-728b-11ea-9836-9bc853344f04.png)

**Comment by 3ter** [comment]
I find myself often wanting to use leading wildcard searches. I understand that they [can slow searches](https://communities.bmc.com/docs/DOC-47935), so I vow to at least make it optional.

I've read the [issue on this topic](https://github.com/laurent22/joplin/issues/1288) which has been closed, but I think it deserves another thought when the system is improved. There are [people thinking about it](http://developforperformance.com/MakingWildcardQueriesScalable.html).

**Comment by 0xMH** [comment]
I think this issue should be kept active.

**Comment by jjon** [comment]
I don't know if boolean queries are still "a thing" but it's certainly possible in sqlite or any other sql engine. And the ability to filter by multiple tags is pretty ubiquitous. Whatever you call it, the functionality to "show me all notes with both tagA and tagB" is a much needed feature. And a related feature request in the desktop ui is to be able to SEE the tags for current note without having to click the tags icon.

**Comment by malnoxon** [comment]
I think this issue should be kept active.

**Comment by heurihermilab** [comment]
I frequently find myself wanting to search within a particular notebook (say, documentation for a particular model of widget), and the inclusion of results from other notebooks is something I'd like to turn off.

**Comment by naviji** [comment]
@heurihermilab https://discourse.joplinapp.org/t/search-syntax-documentation/9110

This will soon be possible.
