### ISSUE TITLE
How is this possible?

### ISSUE THREAD

**Issue by kcrossen** [laurent22/joplin#1883]
Here's Laurent's version:
![unnamed](https://user-images.githubusercontent.com/1951504/65289826-5ac4f280-db1a-11e9-9a48-535d912abdc7.png)
Here's my version:
![screenshot_191](https://user-images.githubusercontent.com/1951504/65289841-67494b00-db1a-11e9-9e47-faf1ef314f4b.jpg)
Left-hand pane identical, right-hand pane different.
How is this possible w/ the same code base?

**Comment by laurent22** [comment]
First version is indented with tabs, the second is not

**Comment by kcrossen** [comment]
Do you not see that your screenshot shows:
```
WHEN /* LURKER */ 0 THEN 'Hidden (0)'
WHEN /* MEMBER */ 1 THEN 'Member (1)'
```
while my screenshot shows:
```
WHEN /* LURKER / 0 THEN 'Hidden (0)'
WHEN / MEMBER */ 1 THEN 'Member (1)'
```
Mine is missing the asterisk after "LURKER " and the asterisk before " MEMBER".
