### ISSUE TITLE
Web Clipper has stopped showing Preview

### ISSUE THREAD

**Issue by chriswayg** [laurent22/joplin#1889]
Expected behaviour: to see a Preview

![image](https://user-images.githubusercontent.com/13681327/65424424-1ef19c00-de3e-11e9-89cb-3b5094e38764.png)

Oh well, so I just found your comment in github history regarding this: 

> Clipper: Disabled preview for now as too many problems with it and not so useful
https://github.com/laurent22/joplin/commit/3e48992eb41c77ac88475edf64f2e583ae61c233#diff-f8e1cd374cd63a334f831b44d301bdd9

Why isn't this mentioned in the changelog? https://github.com/laurent22/joplin/blob/1578188fde92547da8e2c280e5dfaca67f14374b/readme/changelog.md

I really liked it to be able see the preview, which set Joplin apart form other web-clippers. I found it to be very useful, as it gave me a good idea of what I would see in Joplin. Now I have to switch to Joplin to check what the clipped version looks like.

When will the feature be fixed and return? Please at least give us the option to enable it again!

**Comment by laurent22** [comment]
It probably won't return I'm afraid. It's too broken for general use.
