### ISSUE TITLE
Nextcloud sync on android does not work

### ISSUE THREAD

**Issue by cloo** [laurent22/joplin#1890]
I have a working sync of Joplin desktop (windows) to my personal nextcloud via http (not https):
http://my_server/remote.php/webdav/my_folder/Joplin

Android client fails connecting to nextcloud with same credentials. 
Error: Network request failed:

![Screenshot_20190923-225438](https://user-images.githubusercontent.com/651760/65458231-d645dd00-de55-11e9-8b89-f11bde726757.jpg)

## Environment

Joplin version: 1.0.305
Platform: Android 9
 

## Logfile

 
[syncReport-1569268970048.txt](https://github.com/laurent22/joplin/files/3643943/syncReport-1569268970048.txt)

**Comment by laurent22** [comment]
Unfortunately http for sync doesn't work anymore, you'd need to use https. There are a few threads here and on the forum about this.

**Comment by cloo** [comment]
thx

**Comment by cloo** [comment]
Finally I can find my "cursed" note by searching. I hope the issue is gone.
