### ISSUE TITLE
Hide editing toolbar buttons when text editor is hidden

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#1896]
The "Layout" button in the desktop app allows toggling between editor and viewer state and split view. When it is in viewer-only mode, some toolbar buttons should be hidden, in particular those related to editing the note.

In particular those should be hidden:

- Bold
- Italic
- Link
- Code
- Attachment
- Bullet list
- Numbered list
- Checkbox list
- Heading
- Horizontal bar
- Insert date/time

The code to hide/show buttons is in `NoteText::createToolbarItems(note)`.

**Comment by KarlaChen** [comment]
hi, @laurent22 . I am interested in it, can I work on it?

**Comment by laurent22** [comment]
Yes sure, please go ahead.

**Comment by pratap87** [comment]
hi @laurent22 .I am interested in it ,can i work on it

**Comment by nathanleiby** [comment]
PR here: https://github.com/laurent22/joplin/pull/1940 

--

@pratap87 apologies if I stepped on your toes. Happy to assist you in finding another issue or giving feedback on a later PR!
