### ISSUE TITLE
List indentation with TAB

### ISSUE THREAD

**Issue by the-reverend** [laurent22/joplin#1898]
I don't know why this FR hasn't been created yet; I found the topic in the forum and it seems like a simple gap to fill. In my opinion, the solution doesn't even need to be `TAB` ... other markdown clients I use have hotkeys for indent/unindent, e.g. MacDown has `CMD-[` and `CMD-]`. If this was configurable in general options, that would be great. `TAB` and `SHIFT-TAB` would be great; `SHIFT-TAB` currently works as expected for unindent.

## Has it been discussed in the forum? Link to topic.

https://discourse.joplinapp.org/t/list-indentation-with-tab/1322

**Comment by laurent22** [comment]
There's no plan to improve the editor at this point as we are going to change it
