### ISSUE TITLE
Use subfolder for WebDAV / Nextcloud sync

### ISSUE THREAD

**Issue by kstevens715** [laurent22/joplin#190]
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

I started using the NextCloud integration today. That's a pretty nice feature. Before finding this project, I almost gave up trying to find an Open Source app and went back to Evernote.

Anyway, I had the same issue as mentioned in this comment by @chbmb:
https://github.com/laurent22/joplin/issues/4#issuecomment-361101161

The issue is that all notes seem to sync to the root directory in Nextcloud. Do you think it would be possible to setup notes to go to a subfolder instead? I might even be able to work on implementing this myself if you think it's a good idea. If not, I could perhaps setup a separate NextCloud account just for syncing my notes.

Thank you for this great app!

**Comment by seeseekey** [comment]
Only use a webdav url with a (existing) subfolder and then it works, for example:

> https://example.com/remote.php/webdav/Folder1/Folder2

**Comment by CHBMB** [comment]
If you see my edit you'll realise you are having the same problem I had.....

Not reading the f******* manual.... 

:)

**Comment by laurent22** [comment]
Yes you can specify any folder or subfolder (and it's recommended to do so) and the app will use that. I realise it might not be obvious though since Nextcloud only provides the root URL, so maybe there should be a description below the URL field in the desktop and mobile app to make that clear.

**Comment by CHBMB** [comment]
To be honest @laurent22 I'm going to have to shoulder the blame for my mistake, it is pretty clear in the readme, I'm just an idiot.  Act first, think later.

**Comment by kstevens715** [comment]
Oh man, I can't believe I didn't look in the README before creating an issue! Sorry about that. I did actually try the recommended approach yesterday just because it seemed like the obvious thing to do. It didn't work. But maybe the folder I chose did not already exist. Let me try that again and if I still run into issues I'll open a new issue. Thanks everyone.

**Comment by CHBMB** [comment]
@kstevens715 Yeah I too had that facepalm moment, you're in good company mate! Honest.....

**Comment by arnowelzel** [comment]
I just tried this - and it does not work :-(.

The existing folder path: /personal/Joplin

Setting for the WebDAV url in Joplin: https://example.com/remote.php/webdav/personal/Joplin

Result: All files go to the root folder and NOT /personal/Joplin.
