### ISSUE TITLE
Allow selecting what views should be available from the Layout button

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#1900]
The layout button toggles between Editor, Viewer and Split View. There should be an option to decide what mode should be available. For example, some users might only want the Editor and Viewer modes, but never need the Split View one.

To do so, a dropdown option named "Available layouts" should be added to the Config screen, with the following settings:

- Editor / Viewer / Split View
- Editor / Viewer
- Editor / Split View
- Viewer / Split View

And that option should be linked to the behaviour of the Layout button.

The config option should be added to `models/Setting.js` while the `NOTE_VISIBLE_PANES_TOGGLE` action should be modified to support this new option.

**Comment by pmielnik** [comment]
Hi! Do you still need help with this? If so I'd be glad to pick up this issue.

**Comment by laurent22** [comment]
Sure, please do.

**Comment by BackSeat** [comment]
Hmm. Better still, I suggest, would be the option of multiple buttons, one per layout. The cycling/toggling feels a bit cumbersome. Ack that it's easy to stand here and chuck rocks: not my intention to be be negative.

**Comment by SubodhDahal** [comment]
@laurent22 This issue doesn't seem to have been worked on in quite some time, so I created a solution for it and sent PR at https://github.com/laurent22/joplin/pull/2028.
