### ISSUE TITLE
Add a Nord theme

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#1903]
Add a new Nord theme to the desktop application: https://www.nordtheme.com/

It means adding the CSS colours to the relevant files and adding the new theme to Setting.js.

See the recent PR that added the Solarized theme as an example: https://github.com/laurent22/joplin/pull/1733/files but in this case there's no need to add both a Light and Dark theme. Just a regular Nord theme is fine.

**Comment by Kullsno2** [comment]
I will do this.

**Comment by laurent22** [comment]
Ok @Kullsno2, if you need help feel free to post here.

**Comment by Kullsno2** [comment]
https://github.com/laurent22/joplin/pull/1921

**Please review and merge**

**Comment by laurent22** [comment]
There are various issues with the PR so it won't be merged for now, but feel free to improve it.

**Comment by laurent22** [comment]
A pull request for it was started [here](https://github.com/laurent22/joplin/pull/1946) but not completed, so this issue is up for grab again.

**Comment by tessus** [comment]
@laurent22 I can take it, but I suggest that as a second part, we do a refactor of the current code. The last OP did move the theme to its own file. I would like to do that for the other themes as well.
