### ISSUE TITLE
Event Hacktoberfest 2019

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#1904]
Hi,
[Hacktoberfest](https://hacktoberfest.digitalocean.com/) is back this year again for our great pleasure ^^

here are the rules to participate:
> To qualify for the official limited edition Hacktoberfest shirt, you must register and make four pull requests (PRs) between October 1-31 (in any time zone). PRs can be made to any public repo on GitHub, not only the ones with issues labeled Hacktoberfest. If a maintainer reports your pull request as spam or behavior not in line with the project’s code of conduct, you will be ineligible to participate. This year, the first 50,000 participants who successfully complete the challenge will earn a T-shirt.

To participate go on [https://hacktoberfest.digitalocean.com/](https://hacktoberfest.digitalocean.com/) log in (with you github account) and you are ready to get in.

Next, go dive into the Joplin issues list labelled [“Hacktoberfest” ](https://github.com/laurent22/joplin/labels/hacktoberfest)

Start hacking, submit PR the 1rst of October, not before.

We hope you will enjoy that event this year again like the previous one :jack_o_lantern: :tada:

*PS: the 4 Pull Request don’t have to be done **only** on Joplin project, those can be done on any FOSS projects. Even PR for issue not tagged as 'hacktoberfest'*

**Comment by Whizkevina** [comment]
Any issue to contribute too.

**Comment by foxmask** [comment]
> Any issue to contribute too.
Hi, 
To start by something not to hard, You can checkout any  :
- https://github.com/laurent22/joplin/labels/hacktoberfest 
- https://github.com/laurent22/joplin/labels/good%20first%20issue
