### ISSUE TITLE
Linux client Image Attachment  failed !

### ISSUE THREAD

**Issue by airvb** [laurent22/joplin#1907]
In linux client ( ubuntu ) , when opening a note with image attachment , the image isn't visible, instead i have things like that : 
![DSC_0048_4.JPG](:/e49aca0c811e4611872b7f92cdfbd1c1)

![jolplin1](https://user-images.githubusercontent.com/18460569/65814157-801ec400-e1de-11e9-9ee2-14043937c7ff.png)

Image is visible on android & ios 

Any idea ?

**Comment by laurent22** [comment]
Il faut cliquer sur "Disposition" pour voir le rendu HTML.
