### ISSUE TITLE
 "Goto Anything..." in iOS App

### ISSUE THREAD

**Issue by quertest** [laurent22/joplin#1908]
Currently you can only search for notes in the iOS app, but not for notebook names. In addition, you can't jump from a currently found note directly to the notebook to see the other notes on the same topic. This makes it difficult to work with a large number of thematic notebooks that are hierarchically structured. 

Most helpful would be the same implementation of the "Goto Anything" tool as in the desktop app. When selecting a search hit, the complete superordinate structure opens immediately in the sidebar to the corresponding subnotebook. With the recently introduced additional layout for subordinate notebooks, differentiated by depth, navigation has become much easier at this point.

**Comment by starlessblack** [comment]
Agreed. Seems like just a couple more things like this to being near feature-parity to the mobile apps.
