### ISSUE TITLE
On mobile app running dark theme, document properties are nearly illegible

### ISSUE THREAD

**Issue by starlessblack** [laurent22/joplin#1910]
Running latest release of the Joplin iOS app.

In Configuration > Appearance > Theme > Dark > Save

Open any note, tap ellipses menu in top-right, tap properties. Text appears black on dark menu background, making it nigh impossible to read.

Thank you.

**Comment by reinhart1010** [comment]
Reproducible in Android, too. Possibly a `good first issue` for contributors.

**Comment by robintom** [comment]
Can i give this a go ? This is my first time trying to contribute to Open Source and would need some help from the team if i run into any issues.

**Comment by Puranjay-del-Mishra** [comment]
What is the recomended profiler, and the language that should be used? I`m new here, so i would really appreciate any advice and help.

**Comment by robintom** [comment]
@laurent22 Sure. I was busy with work this week , will look into this over the weekend and will get back to you.

**Comment by robintom** [comment]
@Puranjay-del-Mishra If you are talking about this specific issue , the Native mobile part is made using React Native (Javascript) and then build for iOS and Android.
