### ISSUE TITLE
Joplin force close

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#1916]
## Environment

Joplin version: **1.0.307**
Platform: **Mobile**
OS specifcs: **Android**

## Steps To Reproduce

1. from the desktop, create a note and add drag&drop 50 others notes (all that notes have to be in a list) to create a "summary note"
2. sync
3. use the mobile and edit that note

Describe what's  happened:

* edit the summary note, as the cursor is at the bottom, move the cursor to the top
* the keyboard does not respond until 1min (I can't add a star immediatly by pressingthe key "?123" to switch to the other caracters)
* As I try to enter text and fix what I entered, the backspace key, moves the cursor **randomly** and **erases** unexpected text inside of the links, so the links are broken as the whole note is immediatly save ...

Expected behavior : 
* no loss :( 
* no lag

## Logfile

synReport in comment below

## Questions:

* How to disable auto save ? 
* Is it possible to set an elapsed time to trigger a *save* action ?
* How to rollback a note (from that history) to a previous version, from mobile ?
* I thought that the "note history" allow to rollback to a normal situation, but it seems not.

edit for the last 2 https://github.com/laurent22/joplin/issues/1820

**Comment by foxmask** [comment]
![Screenshot_20190930-073725](https://user-images.githubusercontent.com/208212/65853735-c7ca5a80-e35a-11e9-9685-a8909ad9fee8.png)
![Screenshot_20190930-073314](https://user-images.githubusercontent.com/208212/65853736-c862f100-e35a-11e9-8a98-1bb1a2eed2bd.png)

**Comment by laurent22** [comment]
I'm not sure what the bug is? Is it that the text field is slow?

For note history, you can sync and then open the history on desktop.

**Comment by foxmask** [comment]
yes but also, the backspace erase random letters.
As if the autosave keep in memory a position of the cursor that is not the right one, and once I use backspace, go to that position and drop letters

**Comment by laurent22** [comment]
Ok I see, thanks. Do you have an example of note that can be used to replicate the problem?

**Comment by foxmask** [comment]
I could provide one in JEX if you prefer on a shared folder on dropbox ?

**Comment by foxmask** [comment]
i'll do that this evening.

**Comment by laurent22** [comment]
hmm, I cannot replicate this at all, at least on emulator. I could just be an incompatibility between React Native text input and your phone. Maybe something that will be fixed in a future React Native upgrade.

**Comment by foxmask** [comment]
So let's give up😑

**Comment by foxmask** [comment]
i still have that issue ...
except that I can scroll faster than before but:
1) when I scroll ; Joplin close the app. So I open again joplin and return to the opened note
2) when I enter text at the bottom, the cursor move somewhere else in the text and add random text i did not enter ...
3) so I open the desktop note I am editing on the mobile to fix the typo to roolback the original text.
then save the note
4) I open the note again and joplin jump to the bottom all alone .... (why am I not in the place I was when the cursor move randomly ?) So I could add some text w/o issue.
5) once I scroll to the top and enter text at the first line, joplin restart its weird behavior... change text at a random place 
I suppose the react native 0.62 is still not merged/integrated ?
Maybe as it lasts 6 months I should not expect anything I give up the project completly :/
