### ISSUE TITLE
Joplin Web Clipper: Images don't export in actual size

### ISSUE THREAD

**Issue by dayfuaim** [laurent22/joplin#1917]
## Environment

Joplin version: 1.0.167
Web Clipper: 1.0.18 (Chrome)
Platform: Linux
OS specifcs: Ubuntu 18.04

## Steps To Reproduce

1. Open https://medium.com/javascript-in-plain-english/javascript-in-3d-an-introduction-to-three-js-780f1e4a2e6d
2. Clip Complete Webpage

See Screen#1 (first 2..4 images)
![Снимок экрана от 2019-09-30 13-11-01](https://user-images.githubusercontent.com/1274699/65869937-edb82500-e383-11e9-816b-b1d2b82fdc06.png)

Describe what you expected to happen:

See Screen#2 (first image, I have insterted the right code manually)
![Снимок экрана от 2019-09-30 13-11-32](https://user-images.githubusercontent.com/1274699/65869955-f3156f80-e383-11e9-8c10-c601653bb1f2.png)

## Logfile

[log-clipper.txt](https://github.com/laurent22/joplin/files/3670392/log-clipper.txt)

As I can see - no error in this log.

**Comment by laurent22** [comment]
Medium is a website hostile to readers and even more to scrappers, so unfortunately I don't think that can be fixed.

There would have to be bespoke code just to support Medium, and they will make sure that bespoke code stops working whenever they change something.

**Comment by dayfuaim** [comment]
Got it.

Then... The bug is going to be closed, I think.
Or suspended until «Medium» turn its face to readers.

**Comment by tessus** [comment]
Medium does this on purpose. They want you to use their web site. If you could easily scrape the content, that would no longer be the case.
Thus I wouldn't hold your breath for Medium to change their presentation.
