### ISSUE TITLE
Allow custom CSS when printing

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#1918]
Custom CSS for a note can be specified [using userstyle.css](https://joplinapp.org/#custom-css). However this CSS currently is disabled when printing. It should be enabled again so that users can customise the print if they want to.

To do so, the `useCustomCss` option should be remove and it should be assumed that it is always `true` (currently it's set to `false` when printing).

The following are the test cases: 
- How does it look when exporting a PDF when no userstyle is present (is the default print style applied?)
- How does it look when exporting a PDF and a userstyle is present, but not media query (default print style should *not* be used)
- How does it look when exporting a PDF and a userstyle is present, and media query too (it should apply these queries to the print style)

**Comment by dikshagoyal26** [comment]
I would like to work on it.

**Comment by laurent22** [comment]
That's great, please do.

**Comment by JRaiden16** [comment]
I like to help with this if is not solved yet

**Comment by dikshagoyal26** [comment]
Thanks, I will work on it today, if required any help will ping you @JRaiden16.

**Comment by tessus** [comment]
@dikshagoyal26 @JRaiden16 this is still up for grabs.

**Comment by SFoskitt** [comment]
@laurent22  @tessus  It seems this may not be actively worked on.  I have a solution and will submit a PR in a few minutes.

**Comment by tessus** [comment]
@SFoskitt Great, the most important part is that you have run through above test cases.

**Comment by SFoskitt** [comment]
@tessus   The only test case that did not pass 100% was printing or exporting with media queries.  The screen renders as expected with media queries but I can't produce PDF or printed doc to respond to media queries.  There may be some operator error, though, I'm not sure.

**How does it look when exporting a PDF when no userstyle is present (is the default print style applied?)**

Conditions:
1. `useCustomCss` is default TRUE
2. `userstyle.css` file is absent
3. custom HTML with class names is present

Result:  The PDF export is black and white.  HTML markup is rendered.  No custom styles are applied.

**How does it look when exporting a PDF and a userstyle is present, but not media query (default print style should not be used)**

Conditions:
1. `useCustomCss` is default TRUE
2. `userstyle.css` file is present
3. `userstyle.css` has no media queries
4. custom HTML with class names is present

Result:  The PDF export is rendered with the document styled as the custom CSS.

**How does it look when exporting a PDF and a userstyle is present, and media query too (it should apply these queries to the print style)**

Conditions:
1. `useCustomCss` is default TRUE
2. `userstyle.css` file is present
3. `userstyle.css` contains media queries for max-width 480px
4. `userstyle.css` contains media queries for min-width 481px and max-width 750px
5. custom HTML with class names is present

Result:  Media query styles work as expected for screen rendering *but do not work for PDF export or printing.*  (Mac Mojave)

**Comment by tessus** [comment]
Thank you very much for the detailed report. We'll have to look into the last case. Although I'm not sure how useful `media min-width` would be in `userstyle.css`.

What about a media query like this:

```
@media print {
   /* something here that should only be applied when printing */
}
```

That would probably be the most important one. I think this was what Laurent meant anyway.

**Comment by SFoskitt** [comment]
@tessus  My apologies, there was an operator error.  My media queries were incorrect.  With the following CSS and note content, this *does* print to paper *and* export to PDF with the correct styles.  The last test case does pass 100%.

```
.purple {
	color: #a020f0;
}

.green {
	color: #00ff00;
}

@media all and (min-width: 481px) and (max-width: 768px) {
	.narrow-text {
		color: #a020f0;
		font-size: 26px;
	}
}

@media all and (max-width: 480px) {
	.narrow-text {
		color: #00ff00;
		font-size: 26px;
	}
}
```

```
<s class="purple">Apply CSS here. </s>

Do not apply CSS here please.

<i class="green">Print the document.</i>

<h1 class="purple">
Custom CSS for a note can be specified using userstyle.css. However this CSS currently is disabled when printing. It should be enabled again so that users can customise the print if they want to.
</h1>

To do so, the `useCustomCss` option should be remove and it should be assumed that it is always true (currently it's set to false when printing).

<p class="narrow-text">The styles for this text are inside a media query.</p>
```
