### ISSUE TITLE
Rework towards reproducible builds?

### ISSUE THREAD

**Issue by dietercastel** [laurent22/joplin#1919]
Hi all,

I searched the forum and github but didn't find anything yet on reproducible builds so I was wondering wether this is on the roadmap. 

Reproducible builds would be a nice thing to have imho. But don't take my word for it, read up on the benefits of reproducible builds here: [https://reproducible-builds.org/docs/buy-in/](https://reproducible-builds.org/docs/buy-in/)

I haven't looked into how to achieve this yet, but what would be a way forward if desired? Anyone any experience in making builds reproducible? I guess finding the sources of differences in builds and eliminating them. I'm guessing build environment standardisation could be helpful. Using e.g. docker could be a useful tool for that I think?

**Comment by laurent22** [comment]
Isn't the build already reproducible?

**Comment by laurent22** [comment]
Let's discuss this on the forum. But I think the only thing to do about it is to try - does the same commit always produce the same binary files? If we don't know that to begin with, there's not much to discuss.
