### ISSUE TITLE
Webversion?

### ISSUE THREAD

**Issue by petrk94** [laurent22/joplin#192]
Hello,

I would like to know whether a WebVersion is in plan?
It looks very well and offer this what Im looking for. If it would have a multiuser server backend support, it were perfect and would be the best available.

Thanks

**Comment by laurent22** [comment]
There is currently no plan for a web client, however I would take pull requests if someone's interested in developing it.

**Comment by oktayaa** [comment]
Is there an API for a web client?

**Comment by laurent22** [comment]
Closing, as unfortunately this is out of scope. A web client would require a Joplin server to be developed while the focus of this app is to leverage existing infrastructures (OneDrive, Dropbox) or server apps (Nextcloud).

I would take pull requests thought if someone has some ideas on how to do this.

**Comment by mat-m** [comment]
What if the electron client is "backported" to a webapp like what Framasoft did with https://turtlapp.com for https://framanotes.org (https://framagit.org/framasoft/framanotes-js)

**Comment by jbriales** [comment]
Is the "backporting" approach plausible? I would be also interested in working with a local webapp rather than the Electron type :)
