### ISSUE TITLE
Relax bold and italic formatting for pages imported from web

### ISSUE THREAD

**Issue by larissa-k** [laurent22/joplin#1943]
# Environment

Joplin version: 1.0.169
Platform: Windows 10
Browser/clipper: Firefox 69.0.1, clipper 1.0.18

## Steps To Reproduce

1. Clip a webpage.
2. Open clipped page in Joplin.
3. Discover that the author of the page didn't write their page in perfect HTML, so the markdown is likewise a bit of a mess.

This is most obvious with bold and italic formatting -- if there's a space between the asterisks or underscores, then the formatting doesn't work. I mostly use Joplin as a web clipper, so it's a headache having to fix bad HTML on every page.

Screenshot example:

![image](https://user-images.githubusercontent.com/16738991/66080009-3a8e2e00-e533-11e9-9ad8-7f89f9515584.png)
![image](https://user-images.githubusercontent.com/16738991/66080446-20a11b00-e534-11e9-93b1-8adfb52440d9.png)

(from [here](https://www.pbs.org/wgbh/americanexperience/features/whaling-history-whaling-america/))

I can get a debug log if necessary but I think this is on the clipper side. Sorry if this is already an issue, I searched and didn't see it.

**Comment by laurent22** [comment]
That's strange, it looks like your document had non breaking spaces. I'll check

**Comment by laurent22** [comment]
That can't be fixed unfortunately. The HTML is wrong although it renders fine in the browser, but converting it to valid Markdown is not really possible.
