### ISSUE TITLE
Make the info dialog more visible

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#1944]
There are lots of important info in there and many users don't know it exists.

Maybe it should be made a collapsible panel on the right side, which would be consistent with the mobile app. Opened by default.

**Comment by devonzuegel** [comment]
You're referring to this infobox right? I'd love to have this info more visible! Good idea. 

![image](https://user-images.githubusercontent.com/6979755/71636381-bcaef100-2c0d-11ea-8938-b79985ce89ba.png)


There isn't a ton of info in there, so maybe instead of taking up an entire vertical panel, it could be something that takes a little less space. Perhaps something like the footers in text editors:  

![image](https://user-images.githubusercontent.com/6979755/71636402-11526c00-2c0e-11ea-8152-f60cea176a46.png)

**Comment by laurent22** [comment]
Hmm, I don't know. I've created this info box so that we can move all kind of info there and make it easily editable. If we move it to the status bar, we'll be restricted in how much info we can have and it's also trickier to make it editable. That doesn't mean we shouldn't have a status bar (and clicking on its items could open the info box), but I think that's two different issues.

**Comment by devonzuegel** [comment]
Oh, that makes sense. I like the idea of keeping it where it is and _also_ displaying the information in a smaller format in the status bar!

**Comment by rabeehrz** [comment]
Is this something that still needs to be implemented? If yes, can you give me the implementation details for this?

**Comment by rabeehrz** [comment]
@bedwardly-down Can you loop Laurent into this and let him share his thoughts? I really want to work on this issue.

**Comment by bedwardly-down** [comment]
@rabeehrz, I’ll see what i can do.

**Comment by laurent22** [comment]
I don't know, I've just checked Bear and Evernote and I see their note info panel is like in Joplin, a popup, so I think we should keep it as it is.

The main issue is that the Info button is a bit lost in the toolbar, even though it's quite important. Could you perhaps move it to right of the note title row?

![image](https://user-images.githubusercontent.com/1285584/78508812-aa4ed100-7781-11ea-9ab3-6ce90db462e4.png)

**Comment by rabeehrz** [comment]
Yep. I’m on it.

**Comment by bedwardly-down** [comment]
What about moving it to the left of the Input Box so when a user is typing the name, they’ll instantly see it?

**Comment by rabeehrz** [comment]
> What about moving it to the left of the Input Box so when a user is typing the name, they’ll instantly see it?

I think moving it to the right would be a better idea along with date and time. That would look better UI wise.

**Comment by laurent22** [comment]
> What about moving it to the left of the Input Box so when a user is typing the name, they’ll instantly see it?

The two examples I've checked, Evernote and Bear, have it at the right, so it seems to be semi-standard.
