### ISSUE TITLE
getting resources by note 

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#1956]
Today, the API does not allow us to get the resources of a given note something like `/note/:id/resources` could be helpful. 

The hidden reason is to use the `store` of the JS framework to keep the resource for the note and avoid to trigger a request for each resource :)

**Comment by foxmask** [comment]
```
curl -XGET http://localhost:41184/notes/f5f101e5d57c4df6b1afff256da80b74/resources?token=<token>
```
gives
```
{"error":"Internal Server Error: Cannot read property 'body' of undefined"}
```

**Comment by laurent22** [comment]
Please open a new bug for this, otherwise it's hard to keep track of things.
