### ISSUE TITLE
HTML notes with no color spec do not respect dark mode

### ISSUE THREAD

**Issue by msbentley** [laurent22/joplin#1960]
Using the new ENEX/HTML import I have many notes with no specific font color, but in dark mode the font color is still black:

![image](https://user-images.githubusercontent.com/1671065/66311577-148bd380-e90f-11e9-8d6c-c82373bd6ba3.png)

## Environment

Joplin version: 1.0.169
Platform: linux
OS specifcs:ubuntu 18.04

## Steps To Reproduce

1. Import ENEX as HTML
2. Switch theme to Dark or Solarized Dark

Describe what you expected to happen:

**Comment by laurent22** [comment]
Could you provide an example ENEX file that shows this issue please?

**Comment by msbentley** [comment]
Sure, find attached (and the corresponding screenshot):

![image](https://user-images.githubusercontent.com/1671065/66333475-592b6500-e937-11e9-8d50-8169de2031ed.png)

[ENEX test.zip](https://github.com/laurent22/joplin/files/3698672/ENEX.test.zip)
