### ISSUE TITLE
Enhancement: Multiple Sync accounts

### ISSUE THREAD

**Issue by vsatmydynipnet** [laurent22/joplin#1961]
Hi,

thank you for this cool peace of software. Works nice with webdav against owncloud.  

There is only one part missing:

I would prefer to have private and business accounts separated. So it would be cool if one could define more then one webdav account and bind each book to an account.

so one could open books private1, private2..... bind to webdav account 1 and business1, business 2 ... bind to webdav account 2. this way multi user for business would work if sharing the webdav account and private account still would remain priate with different e2e keys.

Thank you!

**Comment by laurent22** [comment]
Not a bug, so please use the forum.
