### ISSUE TITLE
Joplin backup not working

### ISSUE THREAD

**Issue by slubman** [laurent22/joplin#1970]
## Environment

Joplin executable: JoplinPortable.exe
Joplin version: 1000169(prod,win32)
Joplin revision: bcb44aa5 (HEAD)
Platform: Windows 10

## Steps To Reproduce

1. Try to create a backup with "File > Export > Jex - Joplin Export File"
2. Application window stay on a page with the message `Exporting to "E:\...\JoplinBackup.jex" as "jex" format. Please wait...`
3. I can leave this page by going to the options or synchronisation status then back, however, the backup is not created.

## Describe what you expected to happen:
I expected a backup of my notes to be created.
I even let the application running all night long, without success.

## Logfile
By enabling the debug output as suggested in https://joplinapp.org/debugging/ , I got the following log file: [1570657796893.log](https://github.com/laurent22/joplin/files/3709582/1570657796893.log)
There is no error message in the log.txt file.

**Comment by slubman** [comment]
Looking at the log, and the "Please wait for all items to be decrypted and try again."

I changed my T"ools > Options > Synchronisation > Attachement download behaviour configuration" from "Auto" to "Always".

After the sync finished fetching all attachments, doing a backup is finally working.

Perhaps starting a backup should (with a question to the user?) start a full attachment download ?

**Comment by laurent22** [comment]
It shouldn't initiate any forced download or decryption, however it should definitely display an error message, which is missing here.
