### ISSUE TITLE
Ctrl+Backspace behaves weirdly

### ISSUE THREAD

**Issue by MarkQueppet** [laurent22/joplin#1971]
This is for both the windows and linux desktop apps. 

In most standard text entry fields you can press ctrl + backspace to delete a whole word. This also will delete a space or punctuation mark when attached to a word.  

This is perhaps one of the most useful general shortcuts that I know of for quickly deleting text or simply fixing misspelled words. 

So for example take the sentence below:

`This, is a test sentence.`

In a normal text box, you can 

1. Place your cursor at the end of the sentence
2. Hold down control
3. Press backspace **5** times and delete the whole sentence. 

In Joplin, the same sentence will take **11** presses of ctrl+backspace because it treats every space and symbol as its own "word". 

I'd like Joplin editor to behave the same way that most other editors behave as it is much more efficient.

**Comment by laurent22** [comment]
This is the behavior of the text editor we use - Ace Editor so you might want to file a report there.
