### ISSUE TITLE
WebDav sync on iOS Error

### ISSUE THREAD

**Issue by BoehmFloh** [laurent22/joplin#1972]
## Environment

Joplin version: 10.0.37
Platform:
OS specifcs:

- [x] iOS

## Steps To Reproduce

1. Configure Nextcloud Synchronisation
2. "Check synchronisation configuration"

### Describe what you expected to happen:
A successful connection to nextcloud.
Instead:
After checking the configuration (which is exactly like Desktop/Linux) the error "Network request failed" appeared. I already checked a few similar bug reports which guided me to the possible problem. I'have a self signed certificate installed for my nextcloud server. I already installed the certificate on my iPhone but the handshake doesn't work at all. Is there a plan to implement something like in Linux/Desktop-Version to allow self signed certificates?

## Logfile
```
[date + time]: "TypeError: Network request failed"
value@/private/var/containers/Bundle/Application/E634770D-3EDD-4288-AA52-98CBDC11F462/Joplin.app/main.jsbundle:28:794
value@[native code]
```

**Comment by laurent22** [comment]
Self-signed certificate won't work on iOS and there's no plan to support it. The recommendation in general is to use a valid certificate like Let's Encrypt.
