### ISSUE TITLE
Add command to list all the tags of a note

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#1974]
The current `tag` command allows listing all the notes associated with a tag. However it does not allow listing the tags associated with a note.

A new sub-command `notetags` should be added to the `tag` command, which would allow listing all the tags associated with a note. For example:

    tag notetags abcdefgh12345678

would list all the tags associated with the note with ID "abcdefgh12345678"

The command to update is in `command-tag.js` and the method `Tag.tagsByNoteId()` can be used to retrieve the tags of a note.

The documentation of the command will also need to be update in the `description()` method.

**Comment by laurent22** [comment]
Sure, please go ahead.

**Comment by homofortis** [comment]
It may be nice also if the tags are visible with the content of the note.
