### ISSUE TITLE
Help:About Not Reporting Correct(?) Version

### ISSUE THREAD

**Issue by dalexnagy** [laurent22/joplin#1979]
I have installed V1.0.169.540 but when Help:About is clicked, the window reports a back release level.

## Environment

Joplin version:  1.0.169.540 (I think!0
Platform:  Ubuntu 18.04.3

Reporducing:
1. Click Help:About
2.

Describe what you expected to happen:

Window would report latest release

![Screenshot from 2019-10-12 14-04-40](https://user-images.githubusercontent.com/47158532/66705850-0b797880-ecfa-11e9-89f4-c9feb0c70fe8.png)

**Comment by laurent22** [comment]
How did you install it? I guess you're still running the old version.

**Comment by dalexnagy** [comment]
According to what I see on the top of the screen (on my screen shot), it says I'm running 1.0.169.540
I have deleted the old appimage file and installed it via the instructions on joplinapp.org for linux (wget....).  
Are there any other locations that I might find an old version of this app?

**Comment by tessus** [comment]
@dalexnagy just FYI: this is not a bug and should be discussed on the forum. Also you have to exactly tell us the commands you typed or used, or web links you used to download the version.

**Comment by tessus** [comment]
please open a topic on the forum.

**Comment by laurent22** [comment]
Too many things weird here:
- You have a version from 2018
- You've downloaded a version 1.0.169.540 but there's no such version (version num should be 1.0.x, not 1.0.x.y).
So yes please provide more details on the forum.
