### ISSUE TITLE
Add menu item to toggle note list

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#1988]
A new option should be added in the View menu to toggle the note list (to hide and show it). No keyboard shortcut needs to be associated with it.

You can do that by adding a new "toggleNoteList" action and make it work like the existing "toggleSidebar" action.

**Comment by tbergeron** [comment]
Glad my feature request is now here :D Thanks a lot!
I'm trying to do it myself, it's been a while since I wanted to collaborate, improving the app I use everyday seems to be a very good idea! I'll push the PR soon.

**Comment by tbergeron** [comment]
Here it is! https://github.com/laurent22/joplin/pull/1991
