### ISSUE TITLE
Feature Request: setting a mobile reminder from the terminal app

### ISSUE THREAD

**Issue by rgalbo** [laurent22/joplin#199]
### Operating system

- [ ] Windows
- [ ] macOS
- [X ] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ X] Mobile
- [X ] Terminal

This is regarding the teminal application. I recently find my self making todo tasks in the terminal application and then grabbing my phone to set reminders on the important todos. It would be really nice to include a terminal reminder that when sync is called sets the reminder on the mobile device.

**Comment by laurent22** [comment]
Technically it can already be done using the `set` command and providing a timestamp in milliseconds. For example to set a reminder for the current note on the 02/10/2018 @ 12:00pm (UTC):

    :set $n todo_due 1518264000000

The Unix timestamp in milliseconds is not particularly user friendly so maybe that could be improved by supporting date strings instead.

**Comment by rgalbo** [comment]
Yeah I think even just using 
```` $date "+%s" -d "02/08/2018 16:40"
1518129600
```
to get the unix timestamp from a tmux split is workable for now
