### ISSUE TITLE
Bad scrolling behavior in editor on Android

### ISSUE THREAD

**Issue by da2x** [laurent22/joplin#1992]
## Environment

Joplin version: 1.0.308
Platform: Android
OS specifcs: Samsung S8, Android 9

## Steps To Reproduce

1. Open a long note for editing.
2. Place a finger on the screen, and quickly drag upwards and release.

Describe what you expected to happen:

The text editor should scroll downwards with momentum. The text should start scrolling downwards quickly and then slow down before coming to a complete stop.

Instead of this, the view only carolla while your finger is pressed against the screen. The amount scrolled is also way less than other apps.

Compare the scrolling experience with any other app.

**Comment by axq** [comment]
I've also noticed this (also Android 9).  In my personal use, I add to notes at the top, with the oldest content at the bottom.  When opening a note to view, it's showing the top, and scrolling has momentum.  But after clicking the edit button, the view jumps to the bottom of the note, and I have to scroll all the way back to the top to add to it, without momentum.

**Comment by axq** [comment]
This essentially duplicates the older existing issues #1838 #899 #202 
Partial fix suggested in #2025

**Comment by laurent22** [comment]
Can't be fixed as of now
