### ISSUE TITLE
Top bar shrinks when selecting a note

### ISSUE THREAD

**Issue by da2x** [laurent22/joplin#1993]
## Environment

Joplin version: 1.0.308
Platform: Android
OS specifcs: Samsung S9, Android 9

## Steps To Reproduce

1. Open any notebook.
2. Long press any note to select it.

The top bar shrinks by about 4 px when it switches from normal to selection mode.

Describe what you expected to happen:

The top bar should maintain a consistent height.

**Comment by laurent22** [comment]
The top bar layout should be reviewed and when doing that it's likely this bug will be fixed.
