### ISSUE TITLE
Text selection illegible color contrast

### ISSUE THREAD

**Issue by da2x** [laurent22/joplin#1994]
## Environment

Joplin version: 1.0.308
Platform: Android
OS specifcs: Samsung S8, Android 9

## Steps To Reproduce

1. Open any note for editing
2. Select any text 

![joplin text selection contrast](https://user-images.githubusercontent.com/1102886/66884649-2ab22780-efd2-11e9-82ac-18c6da80bec2.jpeg)

Describe what you expected to happen:

The selected text should change color to be more legible. White is a common choice.

https://webaim.org/resources/contrastchecker/?fcolor=316F9A&bcolor=0196FE

**Comment by laurent22** [comment]
It's hard to customise this as it's often overridden by system. It's not good now but not bad enough that it needs to be fixed.
