### ISSUE TITLE
1.70: setup error under win7-64, not under win10-64.1809

### ISSUE THREAD

**Issue by opsi-gei** [laurent22/joplin#1995]
* tested with three win7-machines

![grafik](https://user-images.githubusercontent.com/13107653/66888388-8d112500-efde-11e9-9146-bf9a68902a31.png)

**Comment by laurent22** [comment]
Which means?

**Comment by opsi-gei** [comment]
Setup was not sucessfull, the application is not avalaible.
We install with a clientmanagmentsystem (OPSI), this is a part of the installation log:

> (202)     [6] [Okt 16 05:56:42:859] [gei_joplin-notice]   Call "p:\gei_joplin-notice\Joplin-Setup-1.0.170.exe /S /D="C:\Program Files\Joplin""
> (203)     [6] [Okt 16 05:56:42:859] [gei_joplin-notice]      Waiting until the called process is finished
> (204)     [6] [Okt 16 05:56:42:860] [gei_joplin-notice]   Start process as invoker: SYSTEM
> (205)     [6] [Okt 16 06:03:41:151] [gei_joplin-notice]   ExitCode -1073741819    Executed process "p:\gei_joplin-notice\Joplin-Setup-1.0.170.exe /S /D="C:\Program Files\Joplin""
>

**Comment by laurent22** [comment]
Does it work if you install directly, without OPSI?
