### ISSUE TITLE
Joplin does not start under MacOS X Catalina

### ISSUE THREAD

**Issue by h-b** [laurent22/joplin#1996]
After the latest MacOS X Update to Catalina, Joplin does not start any more. Screen screenshot.

<img width="431" alt="Joplin start problem Catalina" src="https://user-images.githubusercontent.com/24413995/66905055-6a463700-f005-11e9-91e5-265dedf6f8c4.png">

_"Joplin cannot be opened, because Apple cannot search in it for malware."_

**Comment by tessus** [comment]
Duplicate of #1983 

(also, non-English screenshots are useless)
