### ISSUE TITLE
OneDrive Login doesn't work on iOS

### ISSUE THREAD

**Issue by CJKinni** [laurent22/joplin#20]

**Comment by CJKinni** [comment]
When I attempt to login, I can sign into my account, but then get an Alert:

'Could not retrieve auth code: 400: undefined: {"error":"invalid_grant" ...

**Comment by laurent22** [comment]
Was it OneDrive Business by any chance? As it's currently not compatible with Joplin. It's strange that it works in Windows though but not iOS.

**Comment by CJKinni** [comment]
It was.  I'll admit that I didn't actually test that it was synchronizing successfully.  It could be that the Windows version just doesn't throw an error.

Thanks!

**Comment by laurent22** [comment]
No problem, I think indeed the issue was that it also didn't work on Windows but it wasn't showing an error (which should now be "fixed").
