### ISSUE TITLE
Mermaid support

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#2001]
Adding back Mermaid support

- [x] check out latest Mermaid version
- [x] is there a usable markdown-it plugin?
- [x] make clear that there won't be any support
- [ ] make it available on Desktop and Mobile
- [ ] add documentation

**Comment by tessus** [comment]
# Info

Latest Mermaid version is 8.3.1 (versions prior to 8.2.3 are vulnerable to XSS)

# markdown-it plugins

All markdown-it mermaid plugins are using old mermaid versions and don't seem to be actively maintained. However, https://github.com/liradb2000/markdown-it-mermaid seems to be the most recent one and can be used as a starting point for creating a plugin for Joplin.

**Comment by bip91** [comment]
I try Joplin with Mermaid in version 1.0.135 to add sequence and Gantt diagrams to my notes. 
This works quite well with Linux but not with Windows. But I stay with this version to be able to maintain my notes. (I was using PlantUML previously, what is better for UML, but I finally switch to Mermaid to handle Gantt and other diagrams)

Do you have some draft or early versions to test and improve ?  
How can I help you to add Mermaid again to Joplin as a Markdown-it plugin ?

**Comment by tessus** [comment]
@bip91 I'm using this issue for myself to track my work. Please use the forum for questions. There are a few topics about Mermaid.
I'm currently working on it, but the architecture of Joplin has changed since it was added to 1.0.135.
I will add a branch as soon as something is ready to be tested.

**Comment by tessus** [comment]
I will unlock this issue as soon as there's a branch to test or further discussion is needed to proceed.
