### ISSUE TITLE
WebDAV XML namespace limitation

### ISSUE THREAD

**Issue by filerun** [laurent22/joplin#2002]
Trying to use Joplin against a WebDAV server which does not use "D:", or any other XML namespace (xmlns="DAV:").
While most of the example XML code from the RFC include a "D:" namespace, it is not specified as a requirement for the protocol.
Here's even an example without: https://www.ietf.org/rfc/rfc5323.txt

Expecting a particular namespace makes it a bit limited for no particular reason: https://github.com/laurent22/joplin/blob/b099c811cc7205c8b37f0e6a8305b5e720cd784b/ReactNativeClient/lib/WebDavApi.js#L86

P.S. Filling the entire XML code output of a WebDAV server with "D:"s is completely pointless.

**Comment by laurent22** [comment]
Do you have a server that can be tested with?

**Comment by filerun** [comment]
https://demo.filerun.co/dav.php/@Home/
Username: admin
Password: admin

**Comment by laurent22** [comment]
Thanks, I'll check
