### ISSUE TITLE
Few questions on search

### ISSUE THREAD

**Issue by prog20901** [laurent22/joplin#2011]
1. Does it brings Number of hits matches found be while typing for a given text? If not, is it possible to bring it

2. Can we highlight the lookup text and also, change the highlighted colour to blue or red?

3. Is it possible to integrate multi-lingual keyboard in web and similar functionality in desktop app since a user may know huge languages - https://keymanweb.com

4. Is it possible to have more themes to change the colour and themes of the application? how many themes available for now

5. Is there a idea to create a fund raising concept whenever a user asks for a new feature like https://issuehunt.io/r/BoostIO/Boostnote to priortize the requested feature or enhancement....

**Comment by tessus** [comment]
Dude, seriously?

⚠🚨⛔ The issue tracker is not for questions. ⛔🚨⚠

As it happens, support requests that are created as issues are likely to be closed. We want to make sure you are able to find the help you seek.

## Questions and Help

Please read the [documentation](https://joplinapp.org/) and [FAQ](https://joplinapp.org/faq/) first.

### https://discourse.joplinapp.org/

If you have still questions related to Joplin, please open a topic in the [forum](https://discourse.joplinapp.org/).
You can use your GitHub credentials to login to the forum.

## Links

- Documentation: https://joplinapp.org
- FAQ: https://joplinapp.org/faq/
- Forum: https://discourse.joplinapp.org
- How to enable end-to-end encryption: https://joplinapp.org/e2ee/
- API documentation: https://joplinapp.org/api/
- How to enable debug mode: https://joplinapp.org/debugging/
