### ISSUE TITLE
Multiple selection does not apply formatting as expected

### ISSUE THREAD

**Issue by Self-Perfection** [laurent22/joplin#2012]
Joplin desktop allows selection of multiple fragments of the text, but contrary to expectations formatting gets applied only to the first fragment

## Environment

Joplin version: 1.0.170
Platform: GNU/Linux
OS specifcs: Arch Linux

## Steps To Reproduce

1. Open any note
2. Select portion of the text in markdown editor
3. Hold Ctrl key and select another non-overlapping fragment
4. You should now have to distinct fragments of the text selected
5. Click "bold" formatting button
6. Only the first fragment becomes wrapped with `**`!

Describe what you expected to happen:
Both fragments should get new formatting. Just like happens in LibreOffice, for instance.

## Logfile
It seems It is described well enough and log file would not help. But I'll collect and attach logs if you say that this will help.

**Comment by tessus** [comment]
This is not a bug. This was never supported in the first place.

**Comment by Self-Perfection** [comment]
This breaks user's expectations. There are multitude of apps that does not support multiple selection, like lots of plain text editors. In such apps attempt to select additional portion of text with ctrl removes previous selection, so at any time not more than one text fragment is selected.

So I'd say this is a bug (though I admit that minor one) and should be fixed either by prohibiting multiple selection or by implementing its proper support.

**Comment by tessus** [comment]
The multiple selection comes from the editor we use: ACE.

It's supposed to be used to mark occurrences of the same word and change them at the same time. 

You are the first one who ever brought this up. But let's see what Laurent has to say. Removing multiple selection would remove a great feature and I definitely advise against such a thing.

**Comment by laurent22** [comment]
Let's leave it as it is. It's not too bad but it would be hard to fix.
