### ISSUE TITLE
note field not working with screen readers

### ISSUE THREAD

**Issue by devil418** [laurent22/joplin#2013]
## Environment

Joplin version: 1.0.173
Platform: Windows 7
OS specifcs: NVDA used as the screen reader in question

## Steps To Reproduce

1. Launch a screen reader, a program that lets blind people navigate the computer by reading the screen contents aloud
2. Open any document, in any other app *NOT Joplin*. Notice that, when moving with the arrow keys, the document contents are being read.
3. Open a Joplin note and click on the edit field. Moving with arrow keys doesn't read the note's contents.

The screen reader should interact with this edit field the way it interacts with all other fields, i.e. by reading the note.

**Comment by tessus** [comment]
There  is no version 1.0.173

**Comment by ShaneKilkelly** [comment]
This is a known problem with Ace, the javascript-based editor component which Joplin uses to render the Note area: https://github.com/ajaxorg/ace/issues/2164

The solutions would be to either wait until Ace fixes this problem on their end (unlikely), or to consider changing the editor component to something more modern, like ProseMirror, CodeMirror 6, or Slate.
