### ISSUE TITLE
Add TLS v1.3 support

### ISSUE THREAD

**Issue by misaka00251** [laurent22/joplin#2016]
## Environment

Joplin version: 1.0.170
Platform: Windows
OS specifcs: Windows 10 x64 LTSC

## Steps To Reproduce

1. Add TLS v1.3 in nginx
2. Boom

Describe what you expected to happen:

It works?

## Logfile

```
Code: EPROTO
FetchError: request to https://example.com/remote.php/webdav/Joplin/.sync/ failed, reason: write EPROTO 1980367112:error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION:../../third_party/boringssl/src/ssl/tls_record.cc:586:SSL alert number 70

    at ClientRequest.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at TLSSocket.Socket._destroy (net.js:613:3)
    at TLSSocket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:790:10)"

```

**Comment by daenney** [comment]
Joplin on Windows appears to be built with Node 8: https://github.com/laurent22/joplin/blob/1be26e4497f104296ac083aed42fa5a1ddefcbc4/appveyor.yml#L12. Node 8 wasn't released with TLSv1.3 support (and predates it by quite a bit) and support to it wasn't backported either.

The quick fix would likely be to build Joplin with Node 12, which has TLSv1.3 support. This should work and be fine given that the Arch Linux package is built with Node 12 from what I can see, and is fully functional.

**Comment by daenney** [comment]
Given TLSv1.3 is only a year old it's probably not a good idea to only enable TLSv1.3 on your servers, you should leave TLSv1.2 enabled for now too.

**Comment by daenney** [comment]
Took a slightly deeper look, everything appears to be built with Node 8 so regardless of the platform TLSv1.3 won't be supported right now. Unsure how much work it would be to upgrade to the current Node LTS but given Node 8 is losing support in January 2020 it's probably something worth considering doing.

**Comment by laurent22** [comment]
We'll look at it when it's more widespread
