### ISSUE TITLE
Notes deleted on android not deleted on desktop

### ISSUE THREAD

**Issue by olitala** [laurent22/joplin#2017]
I sync joplin between Android 8.0 and windows 7-64 bit via shared file (I  use resilio sync as sharing software). I use encrypted notes. Last versions of joplin on both platforms.
If I delete a note on Android, (and obviously update the shared file) the desktop version doesn't delete the note whan I run synchronization. The reverse works: a note deleted on desktop is deleted on Android when synced.
It seems similar (but not equal) to the problem reported by jcgerhard in issue #154.
I tried to attach all the log files I could (trying to follow your suggestions). 
Please, let me know which kind of data or log can I add to make the problem visible to you. 
Steps to reproduce
1. Create a note on desktop (same if created on android)
2. Sync via file sharing on desktop version, then on android version
3. Delete note on android
4. Sync via file sharing on android version, then on desktop version

Thanks anyway for your work
 
[Desktop_sync_status_copied_from_prog.txt](https://github.com/laurent22/joplin/files/3763633/Desktop_sync_status_copied_from_prog.txt)
[log.txt](https://github.com/laurent22/joplin/files/3763634/log.txt)
[syncReport-1571851237957.txt](https://github.com/laurent22/joplin/files/3763635/syncReport-1571851237957.txt)
[bugreport-judyln_lao_com-OPR1.170623.032-2019-10-23-19-20-59.zip](https://github.com/laurent22/joplin/files/3763636/bugreport-judyln_lao_com-OPR1.170623.032-2019-10-23-19-20-59.zip)

**Comment by foxmask** [comment]
it's working at least with android <=> dropbox <=> desktop , maybe the support for "file sharing" is not so good

**Comment by olitala** [comment]
I discovered the problem. Joplin works perfectly. My problem comes from how Resilio sync manages some types of shared folders. 
Thanks

**Comment by laurent22** [comment]
@olitala, what was the problem exactly? Just so that it happens to other user we might be able to explain.

**Comment by olitala** [comment]
I have in my smartphone some folders synchronized with my desktop via Resilio sync. 
Resilio suggests to configure in the smartphone the folders in "selective sync" way: it is analogue to other softwares; it means that in the phone there is only a symbolic link to each file inside the folders but they are phisically downloaded only if the are really necessary, to save space in the phone.
Anyway Resilio allows to create inside a folder with "selective sync" a subfolder completely synchronized, I mean without selective sync, so all the files inside it are phisically also in the phone and for them, I supposed, the rules of creation, modification and deletion should be those of their parent: instead this is partially true, because if an app deletes a files in this folder, it is phisically deleted only in the phone, but not in the desktop. I created a subfolder for Joplin "not selective", but given that, the notes deleted in the phone are not canceled in the desktop, without a real synchronization.
I have just written to the Resilio assistance. 
In the meantime the solution with Resilio is to create a root folder for Joplin that has to be configured as "non selective" also in the phone. so there is no risk to inherit synchronization rules not completely bidirectional. 
I hope my explanation is clear. Excuse my bad english and feel free to ask for other details.
Regards

**Comment by laurent22** [comment]
Thanks for the explanation @olitala, it's always good to understand these issues.
