### ISSUE TITLE
Scrolling momentum is missing when in edit mode on Android.

### ISSUE THREAD

**Issue by dmncr** [laurent22/joplin#202]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

When in markup edit mode and swiping with the finger to scroll, the scrolling stops as soon as the user releases their finger from the screen. To provide a better user experience it should continue scrolling while slowing down until it stops completely, i.e the scrolling should have momentum.

**Comment by laurent22** [comment]
This is something that would need to be fixed on React Native
