### ISSUE TITLE
Error when trying to sync with Caddy server WebDAV

### ISSUE THREAD

**Issue by makeworld-the-better-one** [laurent22/joplin#2022]
## Environment

Joplin version: 1.0.170
Platform: Linux
OS specifics: Arch Linux

## Steps To Reproduce

1. Setup a WebDAV server using [Caddy](https://caddyserver.com/v1/) and the [WebDAV module](https://caddyserver.com/v1/docs/http.webdav)
2. Try to sync with Joplin

Describe what you expected to happen:
I expected it to sync, but instead I get this error in the sidebar:
`Last error: Error: PROPFIND .lock: Unknown error 2 (404): Not Found`

## Logfile

The log in the desktop app was blank.

**Comment by marianobianchi** [comment]
Having the same problem in android with version 1.0.308

**Comment by makeworld-the-better-one** [comment]
Here's the output from my webserver
```
<?xml version="1.0" encoding="UTF-8"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>//</D:href><D:propstat><D:prop><D:getlastmodified>Fri, 25 Oct 2019 13:05:02 GMT</D:getlastmodified><D:supportedlock><D:lockentry xmlns:D="DAV:"><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock><D:resourcetype><D:collection xmlns:D="DAV:"/></D:resourcetype><D:displayname></D:displayname></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat></D:response></D:multistatus>
```
Formatted:
```


<?xml version="1.0" encoding="UTF-8"?>
<D:multistatus xmlns:D="DAV:">
  <D:response>
    <D:href>//</D:href>
    <D:propstat>
      <D:prop>
        <D:getlastmodified>Fri, 25 Oct 2019 13:05:02 GMT</D:getlastmodified>
        <D:supportedlock>
          <D:lockentry>
            <D:lockscope>
              <D:exclusive />
            </D:lockscope>
            <D:locktype>
              <D:write />
            </D:locktype>
          </D:lockentry>
        </D:supportedlock>
        <D:resourcetype>
          <D:collection />
        </D:resourcetype>
        <D:displayname />
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
</D:multistatus>
```

**Comment by makeworld-the-better-one** [comment]
@laurent22 @tessus @hacdias Any idea why this is happening?

**Comment by laurent22** [comment]
I'm not sure but it looks like Caddy gives a special meaning to the ".lock" directory.

**Comment by tessus** [comment]
No, I don't. I've never used Caddy, so I have no exerience with it. However, I don't understand how the logfile can be empty when there is an error. I guess the OP did not turn on debugging, but I'm not sure if there's more detailed info in the log than the error message already posted.

**Comment by makeworld-the-better-one** [comment]
@laurent22 
What is this .lock directory? Is it part of the WebDAV spec or something that Joplin requires? 

@tessus 
I will try again. I thought I had debugging on, but maybe not.

**Comment by marianobianchi** [comment]
I'm having this error using https://hub.docker.com/r/bytemark/webdav, which is an apache server. Desktop app works ok, the problem is with android version.

**Comment by laurent22** [comment]
>  What is this .lock directory? Is it part of the WebDAV spec or something that Joplin requires?

Something that Joplin requires.

**Comment by laurent22** [comment]
Can anyone share a test user on your WebDAV server so that I can check?

**Comment by makeworld-the-better-one** [comment]
@laurent22 so it looks like the error means Joplin can't find the directory. Why didn't it create it? I will try to create the .lock directory in that folder and report back.

**Comment by laurent22** [comment]
> @laurent22 so it looks like the error means Joplin can't find the directory. Why didn't it create it? I will try to create the .lock directory in that folder and report back.

Obviously if it didn't create it the app would be severely broken and we would have a lot more reports. So it does create it, and it's a different issue.

**Comment by makeworld-the-better-one** [comment]
But shouldn't it create it if it gets a 404? The directory is not there, you can see that in the XML I posted [above](

**Comment by laurent22** [comment]
> But shouldn't it create it if it gets a 404?

> So it does create it, and it's a different issue.

**Comment by makeworld-the-better-one** [comment]
I will double check, but last I saw, there was no lock directory.

**Comment by makeworld-the-better-one** [comment]
I tried to sync again and got the same error, which makes me think Joplin is not creating the directory.

**Comment by makeworld-the-better-one** [comment]
After some experimentation, I found [this bug](https://github.com/hacdias/caddy-webdav/issues/6) in the Caddy WebDAV module, and fixed my configuration, but some testing with [cadaver](http://www.webdav.org/cadaver/) reveals that my WebDAV server in general is having issues with files or folders being created. I'm closing this, since it's not a Joplin issue, but I'll post an update here when I figure out what the issue with Caddy WebDAV is.

**Comment by makeworld-the-better-one** [comment]
Filed issue hacdias/caddy-webdav#24
