### ISSUE TITLE
Custom TLS Certificates do not work on Windows

### ISSUE THREAD

**Issue by chaserhkj** [laurent22/joplin#2023]
## Environment

Joplin version: 1.0.170
Platform: Windows
OS specifcs: Windows 10 1903

## Steps To Reproduce

1. Setup a WebDAV server using certificate signed by a private CA
2. On a windows machine, in Joplin, set Custom TLS Certificates to a path containing the private CA certificate
3. Check Synchronization Configuration

Describe what you expected to happen:
unable to verify the first certificate (Code UNABLE_TO_VERIFY_LEAF_SIGNATURE)

## Comments

Another post reporting the same issue is [here](https://discourse.joplinapp.org/t/desktop-cant-get-custom-tls-certificates-to-work/2365)

Furthermore, the private CA was installed on my Windows system certificate store, but Joplin seems to ignore that.

It seems that the problem is with using `syswide-ca` module to resolve certificates, which, from my perspective of view, does not mention any Windows support in its main page and documentations.

**Comment by laurent22** [comment]
For support please try the forum
