### ISSUE TITLE
Synology WebDAV access forbidden (non-standard port)

### ISSUE THREAD

**Issue by kurisu-gh** [laurent22/joplin#2024]
## Environment

Joplin version: 1.0.170
Platform: Desktop
OS specifcs: Windows 10 and macOS (Catalina)

## Steps To Reproduce

1. Set WebDAV URL to my Synology (https://xxxxx.synology.me:5558/home/joplin). `joplin` folder already created. I can provide a test account, PM me for access.
2. Clicked test synchronization settings -> reason: connect ECONNREFUSED 60.108.225.201:5558 (Code ECONNREFUSED)
3. The WebDAV can be connected using macOS's "Connect to a folder..." feature and I'm successfully using the WebDAV with Zotero on Windows.
4. Issue is similar to https://github.com/laurent22/joplin/issues/531

## Describe what you expected to happen:
To be able to connect with my WebDAV.

## Logfile
[log.txt](https://github.com/laurent22/joplin/files/3773374/log.txt)

**Comment by laurent22** [comment]
Sounds like a server config error

**Comment by kurisu-gh** [comment]
> Sounds like a server config error

It does sound like a server config error but it doesn't explain why I could successfully use the server with other services as I mentioned in my report.

**Comment by laurent22** [comment]
For this it's better to post on the forum, in case someone else knows about it, and once the cause is found, maybe to post an issue with steps to replicate it here.
