### ISSUE TITLE
Download links are not working.

### ISSUE THREAD

**Issue by lazylionca** [laurent22/joplin#203]
None of of the download links seem to work for me, either on the web page or the github.

Just FYI.

Good work on the new version.
Thanks for a great app.

### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [ ] Terminal

**Comment by laurent22** [comment]
It's fixed now. I had taken out v0.10.59 since it was broken but forgot to replace it by the latest one.
