### ISSUE TITLE
[Bug] Not Starting In Tray

### ISSUE THREAD

**Issue by zero77** [laurent22/joplin#2031]
## Environment

Joplin version:1.0.170
Platform:Linux
OS specifcs: Ubuntu 18.04 / i3 desktop

## Steps To Reproduce

At login i have enabled Joplin to start in the polybar system tray using --start-in-tray which works.

Although, Instead of loading completely in the system tray, at start up before it's finished loading it opens up a blank white window which eventually closes.

Describe what you expected to happen:

Unless i have missed the point, when using --start-in-tray Joplin should start with in the tray not as an open window which then closes to the tray.

## Logfile

Startup debug log:
https://pastebin.com/raw/AG5e7kkW

**Comment by pr3c0g** [comment]
The same is true for Mac OS X. I have enabled "Start application minimised in the tray icon" and it opens a blank window which quickly disappears.
