### ISSUE TITLE
WebDAV PUT resource failing

### ISSUE THREAD

**Issue by raf-ets-github** [laurent22/joplin#2038]
Added a 100MB video file to a notebook. Expected behaviour - it uploads.
Actual behaviour: file failed to upload fully over WebDAV. The upload goes into a loop failing after around 2 mins / 12 MB.

(this has occurred using both Owncloud and Nginx WebDAV - removed Owncloud in case PHP was the issue - and on the Windows client also, but don't have debug trace from that session.)

I can upload the file to the server using cadaver and the connection doesn't drop and there are no error messages, which is why I think it could be a Joplin issue rather than a server problem.

Nginx logs:
```
/var/www/log/access.log: [28/Oct/2019:21:30:43 +0000] "PROPFIND /joplin/d767c9bbcea34988bd85a433f38ebc45.md HTTP/1.1" 404 169 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
/var/www/log/access.log: [28/Oct/2019:21:33:10 +0000] "PUT /joplin/.resource/d767c9bbcea34988bd85a433f38ebc45 HTTP/1.1" 400 0 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
/var/www/log/access.log: [28/Oct/2019:21:35:23 +0000] "PUT /joplin/.resource/d767c9bbcea34988bd85a433f38ebc45 HTTP/1.1" 400 0 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
/var/www/log/access.log: [28/Oct/2019:21:37:28 +0000] "PUT /joplin/.resource/d767c9bbcea34988bd85a433f38ebc45 HTTP/1.1" 400 0 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
[28/Oct/2019:22:01:01 +0000] "PUT /joplin/.resource/d767c9bbcea34988bd85a433f38ebc45 HTTP/1.1" 400 0 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"

```
Repeated PUT attempts roughly every 2 minutes.

One example from the Joplin debug log:
```
2019-10-28 21:56:33: "get .sync/version.txt"
2019-10-28 21:56:33: "put .sync/version.txt", "null"
2019-10-28 21:56:35: "SearchEngine: Updating FTS table..."
2019-10-28 21:56:35: "SearchEngine: Updated FTS table in 3ms. Inserted: 0. Deleted: 0"
2019-10-28 21:56:35: "stat d767c9bbcea34988bd85a433f38ebc45.md"
2019-10-28 21:56:36: "Sync: createRemote: remote does not exist, and local is new and has never been synced: Resource: (Local d767c9bbcea34988bd85a433f38ebc45)"
2019-10-28 21:56:36: "put .resource/d767c9bbcea34988bd85a433f38ebc45", "{"path":"/home/work/.config/joplin-desktop/resources/d767c9bbcea34988bd85a433f38ebc45.mp4","source":"file"}"
2019-10-28 21:56:55: "ResourceService::indexNoteResources: Start"
2019-10-28 21:56:55: "ResourceService::indexNoteResources: Completed"
2019-10-28 21:56:55: "ResourceService::deleteOrphanResources:", "[]"
2019-10-28 22:01:25: "Running background sync on timer..."
2019-10-28 22:01:25: "Scheduling sync operation..."
2019-10-28 22:01:25: "Preparing scheduled sync"
2019-10-28 22:01:25: "Starting scheduled sync"
2019-10-28 22:01:25: "Synchronisation is already in progress. State: in_progress"
2019-10-28 22:01:25: "Setting up recurrent sync with interval 300"
```

A temporary file is created in the DAV directory of the webserver which seems to disappear after around 12MB / approximately 2 minutes of upload.
```
root@server:/var/dav# du -sh temp/*
12M	temp//0000000004
root@server:/var/dav# du -sh temp/*
5.9M	temp//0000000005
...etc
```

Version: Joplin for Desktop 1.0.170 (prod, linux) Revision: 22c3646 (head)
Nginx: nginx-full                            1.14.2-2+deb10u1
Debian: 10

WebDAV config in Nginx:
```
  location /joplin/ {
    root      /var/dav;
    client_body_temp_path /var/dav/temp;
    client_max_body_size 0;
    dav_methods     PUT DELETE MKCOL COPY MOVE;
    dav_ext_methods   PROPFIND OPTIONS;
    create_full_put_path  on;
    dav_access    user:rw group:rw all:rw;
    autoindex     on;
    auth_basic "restricted";
    auth_basic_user_file /etc/nginx/joplincreds;
  }
```

**Comment by laurent22** [comment]
Uploading 100 MB files is not a use case we support, but anyway it seems your server responded 400, so it doesn't look like it's a problem with the app.

**Comment by raf-ets-github** [comment]
Thanks for quick response - as cadaver transferred the file I thought it was worth mentioning.

400 prints when the server acknowledges the PUT request but for some reason the transfer then fails partially through.

>Uploading 100 MB files is not a use case we support
I'm producing several GB/month of images and videos so good to know in advance to look for another solution.

Great software though, very useful for smaller filesizes, thanks!

**Comment by raf-ets-github** [comment]
> Uploading 100 MB files is not a use case we support, but anyway it seems your server responded 400, so it doesn't look like it's a problem with the app.

The HyperText Transfer Protocol (HTTP) 400 Bad Request response status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
https://tools.ietf.org/html/rfc7231#section-6.5.1

**Comment by raf-ets-github** [comment]
Would it be useful for me to try to reproduce this issue with a smaller file size?

**Comment by laurent22** [comment]
> Would it be useful for me to try to reproduce this issue with a smaller file size?

Maybe. If it happens with a small file size too, there's a good chance it's an issue with your WebDAV server, as normally small files are handled fine by the app (larger files too I guess, but we don't have support for resuming uploads).

**Comment by laurent22** [comment]
That seems to be a server issue and would be better suited for the forum.
