### ISSUE TITLE
How to sync or migrate notes between terminal and desktop versions?

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#204]
### Operating system

- [ ] Windows
- [x ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x ] Desktop
- [ ] Mobile
- [x ] Terminal

**Comment by laurent22** [comment]
The recommended way is to sync both clients to the same sync target, for example by syncing them both with the same OneDrive account.

Alternatively you can make the terminal client use the desktop profile by starting it with `joplin --profile ~/.config/joplin-desktop`

**Comment by gingerlime** [comment]
I just installed both joplin and joplin-desktop on my Mac (using `brew install joplin` as well as downloading the `dmg` and installing it). Both are working fine it seems, but if I try to load the joplin CLI with `--profile ~/.config/joplin-desktop` I'm getting an error

```
joplin --profile ~/.config/joplin-desktop/
Fatal error:
Error: Unknown profile version. Most likely this is an old version of Joplin, while the profile was created by a newer version. Please upgrade Joplin at https://joplin.cozic.net and try again.
    at JoplinDatabase.upgradeDatabase (/usr/local/Cellar/joplin/1.0.116_1/libexec/lib/node_modules/joplin/lib/joplin-database.js:258:38)
    at JoplinDatabase.initialize (/usr/local/Cellar/joplin/1.0.116_1/libexec/lib/node_modules/joplin/lib/joplin-database.js:425:31)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

I'm also wondering why the profile isn't the same by default. Is there a particular reason to keep separate profiles for the desktop and CLI? seems like a bit of an odd default to me.
