### ISSUE TITLE
Support for MathJax

### ISSUE THREAD

**Issue by sapphire008** [laurent22/joplin#2041]
KaTex cannot render equations when they are inside an html table

```
<table>
    <tr>
        <td>$p_1$</td>
    </tr>
</table>
```

Although it can render inside a `<span>` (perhaps only `<span>`; `<div>` also does not allow rendering)

`<span>$p_1$<span>`

With Atom's Markdown Preview Enhanced as a test (which allows both KaTex and MathJax modes), this issue is probably related to KaTex itself rather than Joplin.

**Comment by tessus** [comment]
Please use the forum.

**Comment by laurent22** [comment]
@tessus, I'm keeping open as i want to check if it's something we can fix it not.

**Comment by laurent22** [comment]
Can't fix
