### ISSUE TITLE
[request] user-agent header setting for webdav (or other remote) sources

### ISSUE THREAD

**Issue by Ardakilic** [laurent22/joplin#2042]
Heya,

It would be awesome if we could set our own user agent for Joplin through the settings pages.

I'm blacklisting various user-agent strings to blacklist some known crawlers from my self-hosted Seafile instance, however, because Joplin uses node-fetch's user agent directly, which is `node-fetch/1.0 (+https://github.com/bitinn/node-fetch)` currently, it gets stuck on my blacklist word list because it contains the word github.

I can simplify my wordlist, or make a whitelist for node-fetch, however, these won't be a proper way to whitelist Joplin on my server directly, or won't let me write rules specifically for Joplin. 

## Environment

Joplin version: Joplin 1.0.170 (prod, darwin) (but possibly for all versions)
Platform: OSX (but possibly for all versions)

## Steps To Reproduce

1. Create a dummy http bin to check headers such as https://postb.in/
2. Set webdav url to this bin to check user-agent header
3. It's `node-fetch/1.0 (+https://github.com/bitinn/node-fetch)`

I would appreciate if this would be considered.

Thanks in advance,

**Comment by AlexPaphitis** [comment]
Hi hope you're well :)

I submitted this pull request to solve this https://github.com/laurent22/joplin/pull/2050

Thank you,
Alex

**Comment by Ardakilic** [comment]
Hey @AlexPaphitis , awesome! Thanks for the work you've done over this 👍
