### ISSUE TITLE
Installation script fails on Ubuntu with zsh

### ISSUE THREAD

**Issue by serpro69** [laurent22/joplin#2045]
## Environment
Joplin version: NA
Platform: Linux (Ubuntu 18.04)
Shell: ZSH

## Steps To Reproduce

1. Run Joplin_install_and_update.sh from zsh shell

**Result:**
Script fails after printing "Linux Installed and Updater" while trying to get the latest version on this line:
```
RELEASE_VERSION=$(wget -qO - "https://api.github.com/repos/laurent22/joplin/releases/latest" | grep -Po '"tag_name": "v\K.*?(?=")')
```
I executed that line in the terminal and it fails as well. 
The culprit is the last grep, for some reason it does not evaluate correctly in zsh (though it could be something else, not necessarily zsh, haven't debugged that deep.)

## Describe what you expected to happen:
Should proceed with installation.

**Comment by tessus** [comment]
I'm sorry this makes no sense.

The script invokes a bash which means the script is run in bash and not zsh.

**Comment by tessus** [comment]
Btw, I've just tested on zsh and the line you quoted does not fail.

**Comment by tessus** [comment]
I suggest you find a zsh forum and find out why it does no work in YOUR environment.
As mentioned before, the script runs in bash, so you must have som other mess on your system.
Closing this.
