### ISSUE TITLE
Please fix viewing rtl notes

### ISSUE THREAD

**Issue by 3j9fkyahunqoxwqu** [laurent22/joplin#2047]
## Environment 

Joplin version: 1.0.308
Platform: Android (haven't tested other platforms yet) 

OS specifcs: Android 9 (pie)

  

## Steps To Reproduce 

Exactly as described in #631 

I would like to explain more about it but that issue was locked by bot so i forced to create another one. Excuse me for that.

that the simplenote app that is open-source and also supports markdown don't have this problem,  may you please look at it if you had time so may be it can help you to fix this issue ? 
Also i think it uses same programing language as joplin.

I mean this app: https://github.com/Automattic/simplenote-android

May be they fixed it by disabling showing notes as markdown by default and enable it only when user explicitly turn markdown button on.
but this is my assumption and i didn't tested markdown rtl writing in it to test if it also has problem for showing rtl like joplin or not (as i don't know about markdown syntax)

But i will test it (i will turn on that button and write a text using markdown and will update this issue in one hour)

Joplin is so great and the only problem is this issue that unfortunately made it unusable for most of my notes.

Also i don't know why but the main page of the app (joplin) that shows note titles show them completely correct and also the title direction is correct in note page. 

I attached some screenshots about these.
Thanks 

 

Describe what you expected to happen: 
App show content of RTL notes correctly.

## Screenshots:

This is when when we are writing:

![Screenshot_20191031_150700_net cozic joplin](https://user-images.githubusercontent.com/49192003/67945795-0884f000-fbf5-11e9-9864-6c6b28add3bc.jpg)

This is when writing completed and the app shows note:

![Screenshot_20191031_150708_net cozic joplin](https://user-images.githubusercontent.com/49192003/67945803-0fabfe00-fbf5-11e9-8398-1865f6dc8b2a.jpg)

This is the main page of the app:

![Screenshot_20191031_150910_net cozic joplin](https://user-images.githubusercontent.com/49192003/67945818-176ba280-fbf5-11e9-9084-0320aecffb7b.jpg)

**Comment by laurent22** [comment]
So is the only issue when the note is rendered as HTML? The text editor is fine? I'm completely ignorant about ltr language so I'm not sure I can do much about it, but it might be good to narrow down the issue.

**Comment by 3j9fkyahunqoxwqu** [comment]
Excuse me for being late

Yes, text editor don't have problem and the problem only is when note is in viewing mode.

Also i tested in simplenote app and when i enabled the markdown, it also had same problem in its view tab.

------------------------------

Edit tab:

![Screenshot_20191031_184228_com automattic simplenote](https://user-images.githubusercontent.com/49192003/67959814-336d4500-fbf1-11e9-8a5f-d360e2f0a627.jpg)


Preview tab:

![Screenshot_20191031_184233_com automattic simplenote](https://user-images.githubusercontent.com/49192003/67959815-336d4500-fbf1-11e9-8b1e-79b052aa9f04.jpg)

**Comment by laurent22** [comment]
Does it work if you paste your Markdown text in there? https://markdown-it.github.io/

**Comment by 3j9fkyahunqoxwqu** [comment]
No, it doesn't work.
Now i remembered, Also github has same issue
 (https://github.com/dear-github/dear-github/issues/147)

I think this is not Joplin's bug.
This problem is for markdown or may be its interpreter to html.

There are two workaround for this i think:
1. Making markdown viewing optional.
2. May be we should workaround this in our notes (by css or html)

Is there an easy way to do this?
Something like template or such that we make it one time and set it as default template or such may be?

What do you think about this problem?

**Comment by laurent22** [comment]
It's unfortunate markdown-it (the lib we use) doesn't support RTL but it means we can't do much about it. Based on [this issue](https://github.com/markdown-it/markdown-it/issues/554) it looks like there's no easy fix either.

Making markdown viewing optional is not an option as that would be too complex and doesn't even feel like a good solution (how about images, formatting, etc.).

I think we'd need someone familiar with rtl text and willing to spend lots of time to update markdown-it and add support for it. That would be the ideal solution. Perhaps a bounty or something could help achieve that, but that's something to check with the markdown-it repository.

**Comment by 3j9fkyahunqoxwqu** [comment]
Oh, Thanks.
Is there any easy workaround for user to fix it by html and/or css ?
I read that Joplin supports css and html.
Has Joplin something like templates so we can add needed html or css codes to it and make it default so all notes inherit it without inserting those codes to every new note by hand?

**Comment by laurent22** [comment]
>  Is there any easy workaround for user to fix it by html and/or css ?

I would expect there's no easy workaround, however if you do find one, please share as in this case we might be able to add it to the app directly. See here for info on how to setup custom CSS: https://joplinapp.org/#custom-css

**Comment by 3j9fkyahunqoxwqu** [comment]
Oh, Thanks.

Does mobile devices also support css?
I read in the Github issue ([+](https://github.com/dear-github/dear-github/issues/147)) that this can fixed with css with this code: `direction: rtl; text-align: right`

In the end, Thank you very much for the time and energy spent for this issue and for developing Joplin.
Best Regards.

**Comment by laurent22** [comment]
@3j9fkyahunqoxwqu, could you post an example of Markdown with Arabic text, as well as an image on how it should render? I have no idea about anything here because I can't read Arabic. If I have an example then I can try to add these CSS properties you mentioned to see if they make a difference.

**Comment by CalebJohn** [comment]
@3j9fkyahunqoxwqu if you copy and paste the following code into your notes it should work.

```html
<style>
body {
    direction: rtl;
    text-align: right
}
</style>
```

I tested this on my computer.
![image](https://user-images.githubusercontent.com/2179547/68342904-d1a55300-00a8-11ea-8c2a-25ab32eecaf2.png)
(Ace editor doesn't seem to support rtl either)

rendered
![image](https://user-images.githubusercontent.com/2179547/68342920-e08c0580-00a8-11ea-8d23-0afca014a7a4.png)

**Comment by 3j9fkyahunqoxwqu** [comment]
> @3j9fkyahunqoxwqu, could you post an example of Markdown with Arabic text, as well as an image on how it should render? I have no idea about anything here because I can't read Arabic. If I have an example then I can try to add these CSS properties you mentioned to see if they make a difference.

Hello
Thank you very much.
Excuse me, i have no access to PC till about two days.
I will check and send to you what i can as soon as i have access.

**Comment by 3j9fkyahunqoxwqu** [comment]
> @3j9fkyahunqoxwqu if you copy and paste the following code into your notes it should work.
> 
> ```
> <style>
> body {
>     direction: rtl;
>     text-align: right
> }
> </style>
> ```
> 
> I tested this on my computer.
> ![image](https://user-images.githubusercontent.com/2179547/68342904-d1a55300-00a8-11ea-8c2a-25ab32eecaf2.png)
> (Ace editor doesn't seem to support rtl either)
> 
> rendered
> ![image](https://user-images.githubusercontent.com/2179547/68342920-e08c0580-00a8-11ea-8d23-0afca014a7a4.png)

Oh, Thank you
I will test it.

**Comment by 3j9fkyahunqoxwqu** [comment]
Hello
Excuse me for being late.

I tested the code that @CalebJohn wrote and it was exactly what i read about it in that github issue but because i didn't know css, i didn't know how it should be written.

This css make RTL notes far better.
The only problem will be English only lines (or if i explain it better, lines that starts with English word) in notes that have this css so user can't wrote English word in start of lines in notes that have this css code, but i think this will be a very good workaround for casual users.

This is the texts i wrote:

![Screenshot_20191112_020833_net cozic joplin](https://user-images.githubusercontent.com/49192003/68626797-6c5ec100-04f1-11ea-9299-fcd60eb394c5.jpg)

And this is the texts that rendered on viewing mode:

![Screenshot_20191112_014348_net cozic joplin](https://user-images.githubusercontent.com/49192003/68626347-703e1380-04f0-11ea-954e-a087783bd4bd.jpg)

As you see in the screenshot the only problem with this workaround is lines that starts with LTR word but i think it is far better than before.

Although i think heavy user can face this problem more (for example when quoting or web clipping may be) but untill someone can fix it and send pull request, or at least has more knowledge than me to help, i think this workaround at least make joplin usable for most of personal notes and ideas.

Thank you @laurent22 @CalebJohn
