### ISSUE TITLE
Layout button is disabled

### ISSUE THREAD

**Issue by xtemp09** [laurent22/joplin#2053]
## Environment

Joplin version: 1.0.170 (prod, win32)
Platform: Windows 7 Ultimate
OS specifcs: x64

## Steps To Reproduce

1. Press the Layout button to see the rendered rich text document
2. Create a new notebook
3. Create a new note
4. The program will write: 

> This note has no content. Click on "Layout" to toggle the editor and edit the note.

But the Layout button is disabled! Of course, there is always work around, like, choosing another notebook, note, changing layout and going back to the empty note.
A simpler way is to press Ctrl+L twice.

Describe what you expected to happen:

1. Press the Layout button to see the rendered rich text document
2. Create a new notebook
3. Create a new note
4. The Layout button is enabled

**Comment by tessus** [comment]
Nope, this is not correct.

-   Change layout to preview
-   Go to an empty folder
-   Click New note

You can edit the title. As soon as there’s one character in the title field, the Layout button is no longer greyed out.

/ref https://discourse.joplinapp.org/t/cannot-switch-layout-in-empty-notebook/4117/3
