### ISSUE TITLE
Web clipper screenshot not working properly

### ISSUE THREAD

**Issue by dinesh3434** [laurent22/joplin#2055]
when I use clip screenshot option and take a screenshot (say half the screen), Only part of the screenshot image gets saved in joplin app.

For example, when a tried to clip screenshot for the joplin website (https://joplinapp.org/) the following image 
![image](https://user-images.githubusercontent.com/8008967/68083768-eab4c680-fe52-11e9-909a-0f3681d300bc.png)

The result I see in the application is as follows. I am using a 4K monitor laptop (Lenovo yoga 730). Let me know if you need more information

![image](https://user-images.githubusercontent.com/8008967/68083783-0ddf7600-fe53-11e9-96ec-46c19c18e120.png)

## Environment

Joplin version:
![image](https://user-images.githubusercontent.com/8008967/68083798-3a938d80-fe53-11e9-8222-514b265315e5.png)
 I am using the portable version
Platform: Windows 
OS specifcs: windows 10

**Comment by laurent22** [comment]
I've looked at this before and there's currently no fix. Please search the issues or forum for more information.
