### ISSUE TITLE
Webdav Sync not working with HAProxy / Reverse Proxy + SSL Termination

### ISSUE THREAD

**Issue by Frankstar** [laurent22/joplin#2057]
The Test Button in the Settings is working fine. -> Success
Android Client says its Synced but he didnt sync anything (empty folder still empty and if i use an folder with existing notes from the linux client he doesnt anything either)

Im using a lets encrypt certificate.
Googled around and found that the most with the following error had used http or self signed certificates -> im not.

i found the following error in the Logs:

```
"TypeError: Network request failed
onerror@index.android.bundle:139:2655
value@index.android.bundle:124:1505
value@index.android.bundle:123:6095
value@index.android.bundle:123:2835
value@index.android.bundle:49:1280
value@index.android.bundle:28:3311
index.android.bundle:28:822
value@index.android.bundle:28:2565
value@index.android.bundle:28:794
value@[native code]""
```

im using a simple Apache Webdav plugin.
Its working fine with the Linux Client.

i realized the app creates the hidden folders `.lock` , `.resource` and `.sync` 
but he doesnt sync any files / notes.

Log:
[syncReport-1572814411161.txt](https://github.com/laurent22/joplin/files/3802119/syncReport-1572814411161.txt)

**Comment by laurent22** [comment]
What's the error in Apache log?

**Comment by Frankstar** [comment]
no errors everything fine.
i see the connection in the access.log.
```
10.0.100.11 - xx [03/Nov/2019:23:21:16 +0100] "MKCOL /notes/.sync/ HTTP/1.1" 405 235 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
10.0.100.11 - xx [03/Nov/2019:23:21:54 +0100] "MKCOL /joplin/.sync/ HTTP/1.1" 405 236 "-" "okhttp/3.12.1"
10.0.100.11 - xx  [03/Nov/2019:23:21:55 +0100] "MKCOL /joplin/.lock/ HTTP/1.1" 405 236 "-" "okhttp/3.12.1"
10.0.100.11 - xx [03/Nov/2019:23:21:55 +0100] "MKCOL /joplin/.resource/ HTTP/1.1" 405 240 "-" "okhttp/3.12.1"
10.0.100.11 - xx [03/Nov/2019:23:21:55 +0100] "PROPFIND /joplin/.lock HTTP/1.1" 301 254 "-" "okhttp/3.12.1"
10.0.100.11 - xx [03/Nov/2019:23:22:00 +0100] "PROPFIND /joplin/.lock HTTP/1.1" 301 254 "-" "okhttp/3.12.1"
10.0.100.11 - xx [03/Nov/2019:23:22:07 +0100] "PROPFIND /joplin/.lock HTTP/1.1" 301 254 "-" "okhttp/3.12.1"
10.0.100.11 - xx [03/Nov/2019:23:22:20 +0100] "PROPFIND /joplin/.lock HTTP/1.1" 301 254 "-" "okhttp/3.12.1"
```

I dont get it either, it looks good and still the error and no files synced.

**Comment by tessus** [comment]
Hmm, just FYI, I'm using Android 10, I also use Let's Encrypt, and I'm using Nextcloud, but I've also tried Apache WebDAV and everything works without any issues.

**Comment by Frankstar** [comment]
well, thats bad an good news.
Bad cause therefor its an even more "weird" behavior.
Good cause its not a common problem with joplin.

the problem is the whole "android only works with https" - that limiting my testing environment.

**Comment by Frankstar** [comment]
i just realized that it also isn't syncing on Linux anymore.
So the "Problem" is the same for Linux and Android.

the only thing i did before it stopped working on linux (and also not working on android) is to add 
https.
i did that via HAProxy, SSL Termination and reverse proxy.
Like i do with alot of other things im running on my servers.

i can only imagine that that thats the hickup.
the certificate (and the whole chain) looks good to me.
But i cant see any error. since some of the access is working (see access.log above)

maybe someone has an idea/hint

**Comment by Frankstar** [comment]
Yeah im Pretty sure its the SSL Termination/reverse Proxy.
Linux-Client-Error-LOG:

```
2019-11-04 09:23:09: "FetchError: request to http://webdav.franzholzer.com:86/testnote/.lock/ failed, reason: connect ECONNREFUSED 10.0.100.11:86
Code: ECONNREFUSED
FetchError: request to http://webdav.franzholzer.com:86/testnote/.lock/ failed, reason: connect ECONNREFUSED 10.0.100.11:86
    at ClientRequest.<anonymous> (/tmp/.mount_JoplinGdX1Ik/resources/app/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:391:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)"
```

I use `https://webdav.franzholzer.com/testnote/` in the config settings.
The log says `http://webdav.franzholzer.com:86/testnote/.lock/` which is totaly incorrect.
there is nothing listening on Port 86 for that URL (webdav.franzholzer.com = 10.0.100.11)

10.0.100.11 = haproxy server.
The webdav server is 10.0.100.12:86

so it looks like webdav / joplin is not working via haproxy out of the box.
the interresting thing for me is the **Check synchronization configuration**-Button for me, cause thats working fine.

**Comment by Frankstar** [comment]
i realy dont get why or from where joplin gets and use the internal Port 86.
`2"FetchError: request to http://webdav.franzholzer.com:86/testnote/.lock/ failed, reason: connect ECONNREFUSED 10.0.100.11:86`

also it cuts out the "https" and redirect to "http" - which is also wrong.
i played around with haproxy but i cant find a solution or a problem on that side.
I pretty sure there should be an option - but i could find it yet.

if i connect with curl via `curl -v --user user:pass  https://webdav.franzholzer.com`

the response is on Port 443. (as expected) and its work fine.
```
*   Trying 10.0.100.11:443...
* TCP_NODELAY set
* Connected to webdav.franzholzer.com (10.0.100.11) port 443 (#0)
```

**Comment by tessus** [comment]
Yep, this is really strange. I've noticed that there can be issues with apps behind a reverse proxy, when (I don't know the HA-proxy equivalent) `ProxyPass` is set but not `ProxyPassReverse`. But this does not seem to apply to you,  because curl, cadaver, and other clients don't have an issue.
Is there any chance that you could create a test user for Laurent?

@laurent22 if this only occurs with Joplin, maybe the module for doing the webdav connection is doing something wrong. I don't even understand how Joplin would know of the internal port behind the reverse proxy. This should be absolutely transparent to a client. Also the switch from https to http is very strange. Why? How? I'm confused.

**Comment by laurent22** [comment]
I'm clueless to be honest. If someone has an idea and can create a pull request I'm happy merge though.

**Comment by Frankstar** [comment]
tested a few haproxy settings but without success.
While the "Check synchronization configuration"-Button works the sync does not.

mayb someone has an idea whats going on with joplin OR has an real clue about an 
HAProxy equivalent of ProxyPassReverse (if needed at all - i dont think so)

**Comment by Frankstar** [comment]
Looks like you changed something on the Android app?
its working now!
i didnt change anything - was just curious and tested it again.

-----
after i saw its working - i spend more time investigating the desktop app.
the haproxy / wrong URL problem was a faulty reasoning on my end.
im using a Split-DNS in my own network - so the URL gets changed by that.

i will test it on my Notebook from "outside" my own network - comment and close the issue then.

**Comment by tessus** [comment]
The only fix that was added in that regard was a workaround for servers which redirected requests.

**Comment by Frankstar** [comment]
just a follow up.
no errors anymore - everything good.
