### ISSUE TITLE
Writing in Windows seems to have quite a bit of lag?

### ISSUE THREAD

**Issue by TobiasDev** [laurent22/joplin#2058]
I'm currently trying to work on some of my notes (big and small notes), but I'm currently struggling because of how much Joplin is lagging. I can't really say why it happens (since I don't have anything else open), but it makes it really difficult to work on my notes as I type a few letters, have to wait a few seconds and then the letters appear.

**Comment by TobiasDev** [comment]
Actually for me it does it on both new and old notes. So even just creating a new one has this problem.

**Comment by axq** [comment]
Is the raw view lagging for you, or just the rendered view?  The rendered view doesn't update for me at all while I continue typing, but I assume this is intentional.

**Comment by TobiasDev** [comment]
Hmm, good question. I usually have the split-view, so I will test without that and see if it still lags.

**Comment by TobiasDev** [comment]
I have the same issue when typing without the splitview. That is keeps on lagging behind.

**Comment by Wenzel** [comment]
Hi,

I'm **confirming this issue** on the latest Joplin(1.0.174) , and on **Linux**.

Since recently, the application will freeze right after editing a note, for 2 seconds or more.

It's really annoying as it makes editing unusable.

**Comment by laurent22** [comment]
> Could you provide an example of note that shows this lag? If you could export it as JEX that would be great.

**Comment by Wenzel** [comment]
Weird, the problem is gone now.
I will watch this issue and post the JEX file when the problem will be back :)
