### ISSUE TITLE
Custom sorting of notebooks

### ISSUE THREAD

**Issue by adamblank** [laurent22/joplin#206]
### Operating system

- [X] Windows
- [X] macOS
- [X] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [ ] Terminal

### Summary

Providing a way to customize how notebooks are sorted (e.g. by `created time`, `recently updated`, (etc) in _ascending / descending_ order; ) would be a minor but meaningful UX improvement.

**Comment by rammjet** [comment]
+1

Lots of notebooks.  I need to look at them in alphabetical order.

**Comment by foxmask** [comment]
+1 on Android

**Comment by tessus** [comment]
just a thought: maybe a search field above the notebooks with incremental seach functionality would be helpful (if one has lots of notebooks).

Also, I'd like to see this enhancement (original request) on all platforms: desktop, mobile, terminal.

**Comment by foxmask** [comment]
add the possibility to use drag&drop as requested in #406

**Comment by jgreth** [comment]
+1 
alphabetical ordering is what i miss most

**Comment by pointbre** [comment]
+1
Manual order by drag and drop works fine on one device. As soon as synced with other device, on other device,  notes are displayed in the different order which is what I want a fix.

**Comment by TobiasDev** [comment]
"alphabetical ordering is what i miss most" - Same for me, this is what I would love. Custom ordering I don't really need. :) But alphabetical would be really nice!

**Comment by johnz1** [comment]
+1
I put all of my notes in one notebook ("All Notes") because any sorting other than alphabetical is just as good as random to me.  Notebook sorting options similar to those for notes would be great

**Comment by inovek** [comment]
+1
Not nice 2 have, for a note taking application `must to have`

**Comment by vxdIOT** [comment]
+1
Need the ability to order notes and notebooks

**Comment by sebastienjust** [comment]
Created Pull Request #768 where notebooks are sorted alphabetically

**Comment by rafikiphoto** [comment]
https://github.com/laurent22/joplin/labels/essential

**Comment by homofortis** [comment]
+1 "must have" + display of date and time  of creation

**Comment by justusthane** [comment]
@alexdevero Thanks for this. How do I add an index to a note though?

**Comment by jdrox** [comment]
I'm confused.  Why is this issue closed?  The feature isn't implemented yet, is it?

This feature is necessary for a decent notes application.  I'm trying Joplin now after OneNote doesn't support dark themes (except in the upcoming version that will not run on Windows 7...), Boostnote doesn't allow reordering of notebooks, Simplenote doesn't support dark themes without paying money, CherryTree is clunky, and Zim... well I'm not sure about that one yet.

My point is this simple feature would set your program apart from the competition.  (It would also allow me to use it... This is a literal must for me.)

I frequently create new notebooks.  I have about 20 right now, each holding notes of a single subject.  When I create new notebooks, I need to be able to sort them.  

Please and thank you.

**Comment by tessus** [comment]
The commit referenced allows you to sort notebooks:

- alphabetically
- by last modified note

The change is already included in the 2 latest pre-releases.

**Comment by jdrox** [comment]
OK, I found this page: https://github.com/laurent22/joplin/blob/833d4732685206f6f36d7f64039d5417537bf283/CliClient/tests/models_Folder.js

But I can't find any file called "models_Folder.js" in my Windows-based installation... I'm using v1.0.135.

Can I start using this feature now somehow?  Or will the feature be included in the Windows build soon?  

Thanks.

**Comment by laurent22** [comment]
It will be part of the next release on desktop.

**Comment by tessus** [comment]
> Can I start using this feature now somehow? Or will the feature be included in the Windows build soon?

Yes, you can. I mentioned before that it is available in the 2 latest pre-releases: https://github.com/laurent22/joplin/releases/tag/v1.0.138

**Comment by rafikiphoto** [comment]
Thank you so much. It works great!

**Comment by jdrox** [comment]
Thank you, @laurent22 !

Thank you, @tessus - I scoured these pages for several minutes and would not have found the prerelease download links if it wasn't for you.  (I still don't know what I'd click to find them again... :confused: )

One thing I've noticed is that new notebooks aren't sorted alphabetically automatically, even though the menu setting is enabled.  Closing and relaunching the program has no effect.  Sorting by last updated then going back to sorting alphabetical does properly sort them.  

(This is kind of a neat little quirk... you could take advantage of this knowledge; with some planning, you could sort the first notebooks created alphabetically, then add other notebooks which would be sorted manually, based on time of creation.)

Thanks again.  I'm getting everything merged into Joplin now and I can't wait to really start using it!

**Comment by tessus** [comment]
@jdrox 

> I still don't know what I'd click to find them again...

- In the Joplin configuration `General Options` in the section `Application` click: `Get pre-releases when checking for updates`.

- On the main github page for joplin you can click on Releases or follow this link directly: https://github.com/laurent22/joplin/releases
The latest releases are always at the top.

**Comment by laurent22** [comment]
> One thing I've noticed is that new notebooks aren't sorted alphabetically automatically, even though the menu setting is enabled.

This should be fixed in the next release
