### ISSUE TITLE
Bug: Web Clipper catches code snippets incomplete

### ISSUE THREAD

**Issue by xdeveloper4711x** [laurent22/joplin#2069]
Hi everybody,

the web clipper in Google Chrome shows off a bug - it catches code snippets only partially. I use Joplin in Version 1.0.170 in Manjaro Linux. The Version of Joplin Web Clipper is 1.0.18. It happens when I use "Clip Complete Page" or "Clip selection".

I assume that there is a conflict with specific characters or combinations of characters that are often used in code snippets for specific languages. 

An example:
The source in Google Chrome is as follows:

fn main() {
   let result = 10;    // i32 by default
   let age:u32 = 20;
   let sum:i32 = 5-15;
   let mark:isize = 10;
   let count:usize = 30;
   println!("result value is {}",result);
   println!("sum is {} and age is {}",sum,age);
   println!("mark is {} and count is {}",mark,count);
}

The html-code is as follows:
fn main() {
   let result = 10;    // i32 by default
   let age:u32 = 20;
   let sum:i32 = 5-15;
   let mark:isize = 10;
   let count:usize = 30;
   println!("result value is {}",result);
   println!("sum is {} and age is {}",sum,age);
   println!("mark is {} and count is {}",mark,count);
}

The clipped code in the markdown editor is as follows:
```
fn main
```
That happens approx. 100 times in that document.

The link is as follows:
https://www.tutorialspoint.com/rust/rust_quick_guide.htm

## Logfile
log-clipper.txt

log-database.txt

**Comment by laurent22** [comment]
Fixed in https://github.com/laurent22/joplin/issues/2015 (not yet released (
