### ISSUE TITLE
Selecting Nextcloud crashes the app

### ISSUE THREAD

**Issue by raboof** [laurent22/joplin#207]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

On the Configuration screen, when I change the 'Synchronization target' from 'OneDrive' to 'Nextcloud (beta)', the app immediately stops. This is on version 0.10.91 downloaded from the website.

**Comment by raboof** [comment]
Wow that's quick, thanks! Guess it's time for me to learn how to build from source :D

**Comment by laurent22** [comment]
Yes the latest version 1.0.94 should work fine: https://github.com/laurent22/joplin-android/releases/download/android-v1.0.94/joplin-v1.0.94.apk
