### ISSUE TITLE
Unencrypted "edit-" file is not being synced to Dropbox when working with external editors. Typora edits are not being saved. 

### ISSUE THREAD

**Issue by titanomachy** [laurent22/joplin#2072]
Edit: I just read #1854 and see it was fixed for an unreleased version. Not sure if this was exactly the same behavior, because the file contents are not being erased in my case. There is also no sync to Dropbox in case edits are being saved successfully.

## Issue
Unencrypted "edit-" file is not being synced to Dropbox when working with external editors. Typora edits are not being saved. 

Reported in issue #1854 and #1299 too.

I think it is an issue partly with Joplin, but also partly with Typora.

Setup:
- Joplin v1.0.173 (encrypted notes enabled)
- Dropbox
- Typora v0.9.79
- Notepad++
- Windows

I have encryption enabled for Joplin and sync the notes to Dropbox with the builtin feature.

When I edit the unencrypted file in Joplin, Joplin creates a file under $USER/.config/joplin-desktop with "edit-" prepended to the filename of the encrypted file that lives on Dropbox.

Eg. Dropbox has file:
56b5fdf943324ce18606e4febe2e1610.md

$USER/.config/joplin-desktop/ has an unencrypted file:
edit-56b5fdf943324ce18606e4febe2e1610.md

## No saves with Typora
If I do a CTRL+S in Joplin it does not remove the 'edit-..' file and syncs the file to Dropbox. I can see the file was being synced in Dropbox self.

Now if I try to edit that file via the "external editor" feature in Typora when the "edit-" file was not there already it gets created just like when you would edit it in Joplin. 

When making edits in Typora and do a CTRL+S it is not being saved to the file. The "changed on" timestamp on the "edit-" file is not changing. 

## Typora removes "edit-" file
Then when you close Typora it (Joplin/Typora don't know) also removes the "edit-" file. 

## Notepad++ saves edits to "edit-" file, but no sync to Dropbox
If I do an edit in Joplin the edit-56b5fdf943324ce18606e4febe2e1610.md file is created and stays in $USER/.config/joplin-desktop/ after doing a CTRL+S inside Joplin. If I then open the file directly from the system file explorer with a plain text editor (notepad++) then make an edit and CTRL+S it saves the changes to the file, but it still isn't synced to Dropbox and the edit also isn't visible in Joplin.

So clearly there is issue in Typora not saving changes to the "edit-" file.

## Three separate issues?
1. Typora does not save to the "edit-" file, but a plain text editor does.
2. Typora removes the "edit-" file when being closed, but a plain text editor or Joplin does not.
3. If edited by an external text editor (Notepad++) and successfully being saved the "edit-" file is not being synced to Dropbox so the edits are never visible in Joplin.

**Comment by laurent22** [comment]
edit- files are an internal feature, and should not be saved it synced anywhere.

**Comment by titanomachy** [comment]
I don't save or sync those edit-files or use them in any way. I just enabled the integrated Dropbox feature. I was describing how I think Joplin behaves in this specific case and what I see happening with the edit-files. That something is off in the behavior using different external editors.
