### ISSUE TITLE
Each update adds Desktop icon and remove pinned icon from taskbar

### ISSUE THREAD

**Issue by GameBurrow** [laurent22/joplin#2078]
## Environment

Joplin version: All
Platform: Windows 10 x64
OS specifcs: -

## Steps To Reproduce

1. Install the update

## Describe what you expected to happen:

Each time Joplin update is released and I install it, my taskbar pinned icon dissapears. I need to pin it again. Also, each update puts the Joplin icon on desktop. Since I don't use any icons on desktop, I need to delete it everytime

**Comment by laurent22** [comment]
That should be reported on electron-builder repo as that's what we use for installation.
