### ISSUE TITLE
not support Java code snippet highlight

### ISSUE THREAD

**Issue by lzp4ever** [laurent22/joplin#208]
Java code snippet has no highlight and grey background.
![2018-02-12 11-04-01](https://user-images.githubusercontent.com/13364543/36082444-77d01006-0fe4-11e8-979d-d0517a58450d.png)

**Comment by laurent22** [comment]
This is a bug in the library highlight.js so unfortunately we'll have to wait for them to fix it - https://github.com/isagalaev/highlight.js/issues/1387
