### ISSUE TITLE
HTTP is not permitted on Android 9

### ISSUE THREAD

**Issue by KennethCipriano** [laurent22/joplin#2081]
## Environment

Joplin version: 1.0.310
Platform: Android
OS specifcs: 9 - Pie

## Steps To Reproduce

1. Change Nextcloud WebDAV URL to use HTTP
2. Press check sync config

Sync fails with error "Network request failed"

## Expected

Sync should have started without throwing "Network request failed"

## Additional Note

HTTPS is also failing with the same error when using a **self-signed** cert even when added to the Android trusted certificates store.

I have found an issue on [stackoverflow ](https://stackoverflow.com/questions/51902629/how-to-allow-all-network-connection-types-http-and-https-in-android-9-pie) describing a fix for HTTP traffic on Android 9, maybe you could check it out?

## Logfile
[syncReport-1573560267816.txt](https://github.com/laurent22/joplin/files/3836030/syncReport-1573560267816.txt)

**Comment by kamilko** [comment]
I'm having the same problem. Using local nextcloud instance - it doesn't matter if I use WebDav sync or Nextcloud login.

**Comment by laurent22** [comment]
We already set usesCleartextTraffic but looks like it makes no difference.

In general Google and Apple aren't willing to support neither http nor self signed certificates, so we don't really support it either beside providing a few options which may or may not work.

Eventually you should switch to a proper certificate from LE for instance as it will only get harder and harder to get anything else working.

**Comment by kamilko** [comment]
But if this is local instance without access or expose to Internet, then generating LE certs for such site is real big deal.
And also if self signed cert is used, then still Android version missing some settings which are present in desktop version (like "Ignore TLS certificate errors").
