### ISSUE TITLE
Shortcut keys differ between platform

### ISSUE THREAD

**Issue by fladd** [laurent22/joplin#2082]
Some shortcut keys differ between platforms for no obvious reason. For instance, Globals Search on MacOS is Shift-Cmd-F, but F6 on Windows (instead of Shift-Ctrl-F).

## Environment

Joplin version:1.0.173
Platform: Windows, OS X
OS specifcs:

## Steps To Reproduce

1. Open Joplin
2. Hit Shift-Cmd-F
3. Hit F6

Describe what you expected to happen:

I expect the same behaviour on both plaforms.

**Comment by laurent22** [comment]
There's a plan to clean up and make shortcuts customisable.
