### ISSUE TITLE
Parenthesis in title change to underscores when using "Copy Markdown Link"

### ISSUE THREAD

**Issue by jimfarrand** [laurent22/joplin#2085]
## Environment

Joplin version: Joplin 1.0.174 (prod, darwin) Revision: 0ca96ee (HEAD)
Platform: macOS 
OS specifcs: High Sierra 10.12.6

## Steps To Reproduce

1. Create a note, with parenthesis in the title.  For example: This (is) a test
2. Right click on the note and select: Copy Markdown Link
3. Right click in the editor pane, and select: Paste

Link is pasted, but parenthesis are replaced by underscores.  Eg:
```
[This _is_ a test](:/b761b196bb7e4367993b5bf7e6a66e50)
```

This feels like it might have been implemented deliberately, but it is not obvious why - parenthesis seem to work just fine inside links.  If I manually correct the content to what I expect, it is displayed correctly and works correctly, so the change seems to be a bit purposeless.

If someone is relying on this behaviour, maybe there could be an option to switch it off?

Describe what you expected to happen:

Link is pasted with correct title:
```
[This (is) a test](:/b761b196bb7e4367993b5bf7e6a66e50)
```

**Comment by laurent22** [comment]
Good furst issue: Code that escapes title should be changed to allow parentheses.

**Comment by Runo-saduwa** [comment]
Can this issue be assigned to me or is it solved?

**Comment by tessus** [comment]
@Runo-saduwa sorry, I have just fixed this, because I didn't see your comment.
