### ISSUE TITLE
Feature Request: Updater for the Portable Windows build

### ISSUE THREAD

**Issue by bernd-wechner** [laurent22/joplin#2087]
Let's face it, what's not to love about Joplin (aside from https://github.com/laurent22/joplin/issues/176 and https://github.com/laurent22/joplin/issues/1085)?

I use it on Linux, Android and Windows.  On Windows alone, where I Use a portable JoplinPortable.exe I find the updates bothersome. Stressfully so because I LOVE that there are so many updates, that it's a vibrant tool with huge community behind it and being incrementally improved. It epitomizes functional FOSS. BUT Windows updates just notify me, send me to the web page, I download it, then I have to move the downloaded .exe to where it lives, stopping Joplin first then starting it.

It would be nice, and a classic use case, to simply click Yes, and have Joplin do that for me.

I suggest so knowing that:

1. Probably the windows installer installs an updater and would save me this hassle (but I have a habit and preference for portable instances on Windows for various reasons, and doubt I'm alone).

2. Appreciate that this may be difficult, possibly impossible, and very likely need some Windows specific code and savvy to write as it needs to download the new Exe but then overwrite its own running image which Windows doesn't make easy, so I expect you need some what to schedule some jobs to run on exit then exit, and the scheduled job then overwrites the exe and restarts Joplin. I'm not sure off hand if Windows has such a mechanism available (a kludgy work around is run it from a .bat file which can wrap this intelligently - if the Joplin binary exists with a particular error code, the batch file can do the download overwrite the exe and Goto its top again etc, else just exit, but it means the portable version has two files which is cruddy in a way).

**Comment by laurent22** [comment]
There's no plan to improve this at this point as it's quite complex. Ideally it should be handled by a portable app platforms like PortableApps or PortableFreeware but neither of them accepted Joplin.
