### ISSUE TITLE
Comments inside code block

### ISSUE THREAD

**Issue by ondrousn** [laurent22/joplin#2089]
Hello, I am having issue with writing comment blocks inside my code.

When I have a line of code and put # and some comment next to it, everything is fine until some specific word is used in the comment (e.g. "to").  When some of the specific words is used the comment is displayed as a text. 

Please how can I avoid this?

Without specific word: 
![image](https://user-images.githubusercontent.com/38654744/68944139-757bb680-07ad-11ea-9034-01b2ed252e1f.png)

With specific word: 
![image](https://user-images.githubusercontent.com/38654744/68944172-89bfb380-07ad-11ea-9266-114581487f51.png)

Thanks in advance

**Comment by laurent22** [comment]
Can't replicate since you didn't post the markdown code.

**Comment by laurent22** [comment]
And please use the forum for support requests.
