### ISSUE TITLE
Feature Request: Open the new note in external editor if set.

### ISSUE THREAD

**Issue by gerroon** [laurent22/joplin#2090]
Hi

It will ne nice if the external editor is opened when a new note created if external editor is set and when the note mode is set to preview. Maybe an optional setting for forcing to open it?  

If it is set to force external mode, then when a new note is created Joplin enables the preview mode (if note) and opens the new note in the external editor.

At the moment, if the preview is set to viewer mode, and a new note is created the user just looks at an empty view.

thanks

**Comment by laurent22** [comment]
Not a bug
