### ISSUE TITLE
Mail.Ru Cloud WebDAV sync issue

### ISSUE THREAD

**Issue by serenitatis** [laurent22/joplin#2091]
## Environment

Joplin version: 1.0.174
Platform: Windows
OS specifcs: Windows 10 1909 (18363.476)

## Steps To Reproduce

1. Install Joplin
2. Add Mail.ru Cloud as WebDAV (requred subscribtion)
3. Try to start sync

Describe what you expected to happen:

Sync must be complete. Actuallly I got a `Cannot read property '0' of null` error even on sync test. 

## Logfile

> 2019-11-15 22:17:14: "Req 22:16:53: MKCOL https://webdav.cloud.mail.ru/Joplin/.sync/ {"headers":{"Authorization":"********","If-None-Match":"JoplinIgnore-93997","User-Agent":"Joplin/1.0"},"timeout":120000,"maxRetry":0}"
> 2019-11-15 22:17:14: "Res 22:16:53: Created"
> 2019-11-15 22:17:14: "Req 22:16:53: MKCOL https://webdav.cloud.mail.ru/Joplin/.lock/ {"headers":{"Authorization":"********","If-None-Match":"JoplinIgnore-97193","User-Agent":"Joplin/1.0"},"timeout":120000,"maxRetry":0}"
> 2019-11-15 22:17:14: "Res 22:16:53: Created"
> 2019-11-15 22:17:14: "Req 22:16:53: MKCOL https://webdav.cloud.mail.ru/Joplin/.resource/ {"headers":{"Authorization":"********","If-None-Match":"JoplinIgnore-29666","User-Agent":"Joplin/1.0"},"timeout":120000,"maxRetry":0}"
> 2019-11-15 22:17:14: "Res 22:16:53: Created"
> 2019-11-15 22:17:14: "Req 22:16:53: PROPFIND https://webdav.cloud.mail.ru/Joplin/.lock {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-60358","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
> 2019-11-15 22:17:14: "Res 22:16:53: <?xml version="1.0" encoding="utf-8"?>
> <d:multistatus xmlns:d="DAV:">
> 	<d:response>
> 		<d:href>/Joplin/.lock</d:href>
> 		<d:propstat>
> 			<d:status>HTTP/1.1 200 OK</d:status>
> 			<d:prop>
> 					<d:resourcetype><d:collection/></d:resourcetype>
> 			</d:prop>
> 		</d:propstat>
> 	</d:response>
> </d:multistatus>"
> 2019-11-15 22:17:14: "Req 22:16:57: PROPFIND https://webdav.cloud.mail.ru/Joplin/.lock {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-29868","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
> 2019-11-15 22:17:14: "Res 22:16:57: <?xml version="1.0" encoding="utf-8"?>
> <d:multistatus xmlns:d="DAV:">
> 	<d:response>
> 		<d:href>/Joplin/.lock</d:href>
> 		<d:propstat>
> 			<d:status>HTTP/1.1 200 OK</d:status>
> 			<d:prop>
> 					<d:resourcetype><d:collection/></d:resourcetype>
> 			</d:prop>
> 		</d:propstat>
> 	</d:response>
> </d:multistatus>"
> 2019-11-15 22:17:14: "Req 22:17:04: PROPFIND https://webdav.cloud.mail.ru/Joplin/.lock {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-9378","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
> 2019-11-15 22:17:14: "Res 22:17:04: <?xml version="1.0" encoding="utf-8"?>
> <d:multistatus xmlns:d="DAV:">
> 	<d:response>
> 		<d:href>/Joplin/.lock</d:href>
> 		<d:propstat>
> 			<d:status>HTTP/1.1 200 OK</d:status>
> 			<d:prop>
> 					<d:resourcetype><d:collection/></d:resourcetype>
> 			</d:prop>
> 		</d:propstat>
> 	</d:response>
> </d:multistatus>"
> 2019-11-15 22:17:14: "Req 22:17:14: PROPFIND https://webdav.cloud.mail.ru/Joplin/.lock {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-9776","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
> 2019-11-15 22:17:14: "Res 22:17:14: <?xml version="1.0" encoding="utf-8"?>
> <d:multistatus xmlns:d="DAV:">
> 	<d:response>
> 		<d:href>/Joplin/.lock</d:href>
> 		<d:propstat>
> 			<d:status>HTTP/1.1 200 OK</d:status>
> 			<d:prop>
> 					<d:resourcetype><d:collection/></d:resourcetype>
> 			</d:prop>
> 		</d:propstat>
> 	</d:response>
> </d:multistatus>"
> 2019-11-15 22:17:14: "Operations completed: "
> 2019-11-15 22:17:14: "Total folders: 1"
> 2019-11-15 22:17:14: "Total notes: 4"
> 2019-11-15 22:17:14: "Total resources: 3"
> 2019-11-15 22:17:14: "There was some errors:"
> 2019-11-15 22:17:14: "TypeError: Cannot read property '0' of null
> TypeError: Cannot read property '0' of null
>     at WebDavApi.resourcePropByName (D:\temp\nsuE49B.tmp\app\resources\app.asar\lib\WebDavApi.js:205:19)
>     at FileApiDriverWebDav.statFromResource_ (D:\temp\nsuE49B.tmp\app\resources\app.asar\lib\file-api-driver-webdav.js:61:41)
>     at FileApiDriverWebDav.statsFromResources_ (D:\temp\nsuE49B.tmp\app\resources\app.asar\lib\file-api-driver-webdav.js:116:22)
>     at FileApiDriverWebDav.list (D:\temp\nsuE49B.tmp\app\resources\app.asar\lib\file-api-driver-webdav.js:274:22)
>     at process._tickCallback (internal/process/next_tick.js:68:7)"

**Comment by laurent22** [comment]
@serenitatis, any chance you could provide a username and password to test with your server? You can send them to me by email or PM if you'd like.

**Comment by serenitatis** [comment]
I can't find any valid e-mail here. Send login and password to translation mailbox.

**Comment by laurent22** [comment]
Didn't get it. Please send to support at joplinapp dot org

**Comment by serenitatis** [comment]
Done

**Comment by ioogithub** [comment]
I am getting these errors trying to sync to the webdav server at pcloud.com: 

MCKOL, timeout and .lock file errors:

2019-11-30 19:29:17: “FetchError: response timeout at https://webdav.pcloud.com/Applications/Joplin/ over limit: 120000
FetchError: response timeout at https://webdav.pcloud.com/Applications/Joplin/ over limit: 120000
at /tmp/.mount_JoplinsXVknw/resources/app/node_modules/node-fetch/lib/body.js:117:12”
2019-11-30 19:29:17: “Req 19:12:25: MKCOL https://webdav.pcloud.com/Applications/Joplin/.resource/ {“headers”:{“Authorization”:”********",“If-None-Match”:“JoplinIgnore-59363”,“User-Agent”:“Joplin/1.0”},“timeout”:120000,“maxRetry”:0}"
2019-11-30 19:29:17: "Res 19:12:25:
405 Method Not Allowed
Method Not Allowed
The requested method MKCOL is not allowed for the URL /Applications/Joplin/.resource/.
Apache/2.4.10 (Debian) Server at webdav.pcloud.com Port 443.

Should I open a new issue thread or do you think it is the same problem?

I reported in in the thread here: https://discourse.joplinapp.org/t/feature-request-pcloud-synchronisation/3530/22

**Comment by laurent22** [comment]
That should work in the next version.
