### ISSUE TITLE
iOS webdav 405 PROPFIND not allowed

### ISSUE THREAD

**Issue by xwzy** [laurent22/joplin#2093]
I am using Synology Nas to sync my file, and failed when checking config. When I was using Notability Webdav sync with the same config, it works. 

![IMG_9655](https://user-images.githubusercontent.com/13077117/68996279-c638ff80-08d2-11ea-990d-80e44030f0bd.jpg)

## Environment

Joplin version: 10.0.39
Platform: iOS
OS specifcs: iOS 13.1.3

## Steps To Reproduce

1. Webdav url: https://mynasdomain.com:23456/joplin, with correct user name and password
2. Check failed

Describe what you expected to happen:
Also, the same error happen on my Mac.

## Logfile
```
PROPFIND : Unknown error 2 (405): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>405 Method Not Allowed</title> </head><body> <h1>Method Not Allowed</h1> <p>The requested method PROPFIND is not allowed for the URL /joplin/.</p> </body></html> (Code 405)
```

**Comment by laurent22** [comment]
Any chance you could provide a username and password to test with your server? You can send them to me by email or PM if you'd like.

**Comment by xwzy** [comment]
Sorry, due to the regulation in my location, there are some risks to expose webdav port with a domain to get HTTPS encryption on the public Internet. So I only visit my Nas in LAN and may use some tools get me back home. I have not upgraded my Nas for some time and maybe the latest version have fixed this issue. 
The simplest way to test with Synology Nas is to use SynologySkyNAS on aliyun. https://market.aliyun.com/products/56014009/cmjj024350.html

This could be inconvenient, feel free to close this issue.

**Comment by laurent22** [comment]
Fixed in 2103
