### ISSUE TITLE
Add warning in log if a large resource is about to be uploaded

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2097]
If a very large resource is about to be uploaded, say larger than 10MB, a warning should be printed on the log. This is because such upload can last a long time and get the sync process stuck. The log message won't fix the problem but will at least tell what is happening.

To do so, have a look at `lib/synchronizer.js`. Just before a resource is about to be uploaded you'd check its size and log a warning if it's too big.

**Comment by marcushill** [comment]
I've taken a stab at this here: #2102 . Wasn't sure if you preferred it here or down closer to line 444. 

Btw, I found this project a couple weeks ago and I think it's awesome!
