### ISSUE TITLE
Alarm dates not visible

### ISSUE THREAD

**Issue by jazzabeanie** [laurent22/joplin#2098]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/13114475/69002986-1309ee00-0946-11ea-9e7f-f8eb7389e7e4.png">

## Environment

Joplin version: 10.0.39
Platform: iOS
OS specifcs: 13.2.2, dark mode enabled.

## Steps To Reproduce

1. Create a new to-do
2. Give it a name
3. Set alarm
4. tap Select date box or calendar icon

Describe what you expected to happen:

A date selection window pops up from the bottom, but no values are visible. They seem to be there because I can scroll through their values and feel the haptic feedback. I can also select a value and it populates the datetime box after tapping confirm.

My 2 cents:

Seems like there is white text on a white background. I changed from dark mode to normal mode in iOS settings and it works. I changed back to dark mode and set Joplin to the dark appearance theme, but the issue persists.

It would be good if Joplin in inherited light/dark mode appearance from iOS and the date selection popup (and other windows btw), had an appropriate background colour.

**Comment by loganwedwards** [comment]
@laurent22 Since Joplin on iOS does not seem to inherit any specific dark mode properties, we can either just enforce the light appearance in the iOS configuration as a simple change. Alternatively, we could apply some css styles to `react-native-datepicker`.

**Comment by loganwedwards** [comment]
This appears to be fixed already in `master`. Here is an iOS simulator running 13.2 in dark mode:

<img width="480" alt="Screenshot 2020-02-17 08 46 54" src="https://user-images.githubusercontent.com/2034000/74659334-1fc6f980-5162-11ea-9f16-dc974e1f5b7e.png">

**Comment by jazzabeanie** [comment]
It's still an issue for me, now running Joplin 10.0.43, and iOS 13.2.2 on iPhone 11.

**Comment by ishammahajan** [comment]
Can confirm. This isn't an issue on simulators at least. @loganwedwards maybe this is an issue with physical devices, although I cannot find an issue relating to that.

https://github.com/xgfe/react-native-datepicker/issues/376 could be a solution.

Also doesn't seem like master does anything to fix this.
```js
				<View style={{ flex: 1, margin: 20, alignItems: 'center' }}>
					<DatePicker
						date={this.state.date}
						mode="datetime"
						placeholder={_('Select date')}
						format={this.dateTimeFormat()}
						confirmBtnText={_('Confirm')}
						cancelBtnText={_('Cancel')}
						onDateChange={(date) => { this.setState({ date: this.stringToDate(date) }); }}
						style={{ width: 300 }}
						customStyles={{
							btnConfirm: {
								paddingVertical: 0,
							},
							btnCancel: {
								paddingVertical: 0,
							},
						}}
					/>
				</View>
```

**Comment by ishammahajan** [comment]
Another solution could be to automatically check what appearance mode ios is running under the hood using `react-native-appearance` and enforcing styles according to that. The mentioned module is integrated in react-native 0.62 core.

**Comment by rabeehrz** [comment]
Couldn't replicate this on Joplin 10.0.47, on iPhone 8 running iOS 13.3
It might be fixed.

**Comment by rabeehrz** [comment]
@bedwardly-down Could you check this out and see if this problem still persists? If not, the issue can be closed.

**Comment by bedwardly-down** [comment]
![519E21A1-5545-4303-9F79-B7DAD098D7DD](https://user-images.githubusercontent.com/59133880/79768509-80082200-82f0-11ea-9ca3-a21160d6ace9.png)
![44FFBF6B-E50E-48C4-8A17-D92CC2B3564A](https://user-images.githubusercontent.com/59133880/79768520-826a7c00-82f0-11ea-9520-21a6415ec060.png)
![0EEC87D3-C3F9-4DDC-BE0F-AD8B1ECD1A0B](https://user-images.githubusercontent.com/59133880/79768521-83031280-82f0-11ea-8663-03e3bfa26372.png)

Looks good to me on all themes.

iOS 13.4.1
iPhone 11
