### ISSUE TITLE
Options checkmarks not showing visually (OSx, Mac)

### ISSUE THREAD

**Issue by MichaelWTA** [laurent22/joplin#21]
When checking/unchecking settings in the options menu they do not visually change (check appears or disappears) 
When leaving settings and coming back, they show up properly

**Comment by laurent22** [comment]
Hello, this issue should be fixed as of v0.10.30 now available on the website. Please give it a try and let me know if it's fixed.

**Comment by MichaelWTA** [comment]
Yup! All fixed, as well as the copy-paste issue!
