### ISSUE TITLE
Dropbox synchronisation?

### ISSUE THREAD

**Issue by threkk** [laurent22/joplin#210]
### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [x] Android
- [x] iOS

### Application

- [x] Desktop
- [x] Mobile
- [x] Terminal

Hello! First of all, thank you for all the great work you are doing here. I have been trying joplin and it adapts to all my needs... but the Dropbox integration. I know that it is planned once this [issue](https://github.com/facebook/react-native/issues/14445) is fixed. However, there is a [workaround](https://github.com/facebook/react-native/issues/14445#issuecomment-352965210) for the problem. Wouldn't be possible to implement the Dropbox driver using this workaround?

**Comment by laurent22** [comment]
Not sure if his solution would work for binary data too (which is required for resources), but yes it might be worth a try.

**Comment by threkk** [comment]
Fingers crossed then 🤞 Thank you very much 😄

**Comment by calpa** [comment]
Waiting for dropbox also :+1:

**Comment by nicoh88** [comment]
Me too. 🥇 Waiting for dropbox also!

**Comment by dayfuaim** [comment]
I second this :1st_place_medal:

**Comment by laurent22** [comment]
Just a reminder to up-vote issues you support, since then it's possible to view the [most requested features](https://github.com/laurent22/joplin/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by laurent22** [comment]
Dropbox synchronisation is now available for Android, desktop and CLI (will be available on iOS soon). The feature passes the unit tests so it should be safe to use, but to be safe I'd recommend making a backup of your notes to JEX format before switching the sync target. If you notice any bug, please post here.

**Comment by threkk** [comment]
Great news! Is there an ETA for the iOS release? 😄

**Comment by laurent22** [comment]
Probably in a week or so, once it's confirmed that everything works fine with the Android version.

**Comment by ww2** [comment]
One issue: in the OSX desktop app, I wasn't able to paste in the Dropbox authorization code -- while I was interacting with the dialog box to enter that code, the Edit menu wasn't displayed, and the standard Mac shortcut for paste didn't work.  (Had a similar issue on Android, for that matter.)  Synchronization itself, with encryption, appears to be working :-)

**Comment by threkk** [comment]
Same happen for me. I found a workaround using KeePassXC auto type feature but I guess it is not a proper solution.
