### ISSUE TITLE
iOS Joplin app - WebDAV sync not working anymore

### ISSUE THREAD

**Issue by ncartron** [laurent22/joplin#2103]
Hi, 

I am a super happy user of Joplin, both on MacOS and iOS.
I am sync'ing using WebDAV, against an Apache web server.

Sync works fine on MacOS, and used to work fine also on iOS.
But now I am getting the below error:

<img width="249" alt="PNG image" src="https://user-images.githubusercontent.com/22927685/69048372-96d2e180-09fd-11ea-8489-c75cc0e22828.png">

I have deleted the Joplin app, installed it again, and reconfigured WebDAV sync, with no success.

## Environment

Joplin version: iOS 10.0.39
Platform: iOS
OS specifics:
iOS 13.1.3 - iPhone 8

## Steps To Reproduce

1. install the Joplin iOS app
2. configure WebDAV sync
3. check that sync parameters are OK with "Check synchronisation configuration" (Joplin should tell you "Success! Synchronisation configuration appears to be correct"
4. Launch the sync manually
5. I am getting the error message described above.

Describe what you expected to happen:
Synchronisation should work.

**Comment by laurent22** [comment]
Any chance you could provide a username and password to test with your server? You can send them to me by email or PM if you'd like.

**Comment by ncartron** [comment]
Hi Laurent,

I could, but you would then have access to all my notes :)
I'm using a basic htpasswd files, so any user has access to all notes.

**Comment by ncartron** [comment]
right, I have created another vhost on my Apache, sending you the info via PM

**Comment by laurent22** [comment]
Not sure if you've sent it, but I haven't received it yet.

**Comment by ncartron** [comment]
I sent an email to joplin at noreply dot github dot com - just for testing
is that the correct one? if so i’ll send the credentials on this address

**Comment by laurent22** [comment]
Please send it to this address: https://github.com/laurent22/joplin/blob/master/Assets/AdresseSupport.png

**Comment by ncartron** [comment]
done!

**Comment by achos42** [comment]
Hello,

As far as I can see in the network dump Joplin 1.0.39 does not send http authorization header for the PROPFIND request. For the MKCOL request the auth. header was properly set-up.
The first wrong PROPFIND request is for dav-url/.lock

**Comment by laurent22** [comment]
I'm pretty sure the auth header is sent as the algorithm is the same for all platforms, and it works everywhere except with maybe certain versions of iOS and certain WebDAV servers.

**Comment by ncartron** [comment]
just to reiterate: Joplin works perfectly fine on MacOS with my WebDAV server, and the iOS mobile app used to work fine till one week ago. I didn't change anything on my WebDAV server.

**Comment by achos42** [comment]
I have the same enviroment. Apache webdav, MacOS client (works fine - version: Joplin 1.0.161 - Revision: d066350 (HEAD) ), IOS client (not working - Version: 1.0.39). I can also provide a test if needed.

**Comment by achos42** [comment]
Just one more thing. I check the same webdav with the Android client (Joplin 1.0.310) and it's works OK.

**Comment by laurent22** [comment]
Thanks for providing the test user @ncartron. It was indeed an issue with iOS and Apache (Nginx would probably have a problem too) and that should be fixed now. @achos42 you were correct that, while the app sends the auth headers, the underlying network stack would drop them in this particular case.

**Comment by ncartron** [comment]
Thanks Laurent - I guess I'll just have to wait for the update to be available on Apple's App Store? :)

**Comment by laurent22** [comment]
> Thanks Laurent - I guess I'll just have to wait for the update to be available on Apple's App Store? :)

Should be there soon as this is quite a big issue for the few users affected by it.

**Comment by ncartron** [comment]
and here it is, in the App Store - and works on my iPhone - thanks @laurent22 !

**Comment by achos42** [comment]
Thanks! It's work great after the upgrade.
