### ISSUE TITLE
Android - endless sync

### ISSUE THREAD

**Issue by tatoosh** [laurent22/joplin#2105]
## Environment

Joplin version: 1.0.310
Platform: Android 
OS specifcs: Samsung S9, current OS updates

Sync: https nextcloud webdav

## Steps To Reproduce

Connet mobile App to Joplin Adnroid App and sync.
Sync will start but the Notebooks are not shown and the sync will never finish.

On Desktop App (Manjaro AppImage (https://github.com/laurent22/joplin/releases/download/v1.0.174/Joplin-1.0.174-x86_64.AppImage)
the sync is fine.
Also on the iOS App with iPad Pro 11 2019.

## Tests

I deleted the App, reconfigured the App - same issue.

**How to completely remove the App AND the Joplin data on Android??**

## Logfile

From https://joplinapp.org/debugging/ i did not find the `In the options, enable Advanced Option`.
Do you need a logfile?

Thx

**Comment by laurent22** [comment]
Do you have a particularly large file on the sync target?

**Comment by tatoosh** [comment]
Yes i had 5 files there and deleted them on Desktop App. I saw that files on Error log. Now the error log is empty. On Windows in the **.resource** i still have big files. Can i remove them there manually?

![image](https://user-images.githubusercontent.com/3670907/69052795-2ed5c880-0a08-11ea-8ed1-0f2d975c3dab.png)

**Comment by tatoosh** [comment]
I moved the big resource files from that folder, hope that is okay.
Is it still correct, that Joplin needs 48h to delete resources after deleting notes?

**Comment by laurent22** [comment]
If you delete them directly from the sync target, they are gone right away, which in your case is what you need. Does sync work now?

**Comment by tatoosh** [comment]
> If you delete them directly from the sync target, they are gone right away, which in your case is what you need. Does sync work now?

Thx

Sync is still running, i imported 7000 Evernote notes. So i give you info again.

**Comment by tatoosh** [comment]
Deleting big files from. Ressource folder solved the issue.
