### ISSUE TITLE
webdav error

### ISSUE THREAD

**Issue by powersee** [laurent22/joplin#2107]
```
已新建远程项目:1。已完成：19/11/2019 09:36最后错误： Error: PUTb25098e84fa5453abbca1b196865668c. md: The resource of this location does not exist( Exception ObjectNotFound)(404):<? xml version="1.0" encoding=" UTF-8" standalone=" no"?>< d: error xmlns: d=" DAV:" xmlns: s="http://ns.jianguoyun.com">< s: exception> ObjectNotFound</ s: exception>< s: message> The resource of this location does not exist</ s: message></ d: error>
```
when i sync it show this

**Comment by laurent22** [comment]
Please provide the complete log as I can't make sense of this line alone. Also what operating system is it? What's the sync target?

**Comment by powersee** [comment]
![Screenshot_2019-11-19-09-34-40-947_net cozic jopl](https://user-images.githubusercontent.com/38074760/69146148-2e255b00-0b0a-11ea-9eeb-281049a19773.jpg)

I use it on Android phone , want to sync to jianguoyun.com using the webdev. I can found  3 folder in this web 

![QQ20191119-202422](https://user-images.githubusercontent.com/38074760/69146340-996f2d00-0b0a-11ea-99ec-3a61eced1ba3.jpg)

But nothing in this 3 floders.

**Comment by laurent22** [comment]
Would you be able to share a test account so that I can try to replicate the issue? If so, please send the test username/password to https://github.com/laurent22/joplin/blob/master/Assets/AdresseSupport.png

**Comment by studycwq** [comment]
@powersee 你先在坚果云创建个目录然后webdav的链接指定该目录就可以了，可能是坚果云的dav限制了根目录创建文件的权限

这个是我的配置
![我的坚果云 - 坚果云 - 云盘_网盘_企业网盘_同步_备份_无限空间_免费网络硬盘_企业云盘 -  (2)](https://user-images.githubusercontent.com/1407451/69850845-36745780-12bb-11ea-8e28-2afbbefe044f.png)
![Joplin - 选项 2019-11-29 15 13 48 (1)](https://user-images.githubusercontent.com/1407451/69850848-3b390b80-12bb-11ea-8480-6f0911fbbfa6.png)
![Joplin 2019-11-29 15 12 24](https://user-images.githubusercontent.com/1407451/69850856-40965600-12bb-11ea-95f8-f4ec533ff7dc.png)
![我的坚果云 - 坚果云 - 云盘_网盘_企业网盘_同步_备份_无限空间_免费网络硬盘_企业云盘 -  (1)](https://user-images.githubusercontent.com/1407451/69850871-45f3a080-12bb-11ea-8890-23fd9541eb2d.png)

**Comment by powersee** [comment]
@studycwq 
谢谢，但我看你的截图，你应该是用电脑版吧，我用的是安卓手机同步，按你说的试了一下，还是不行。我原本那样是可以在网盘根目录建立像你图片中的那三个 `.` 开头的文件夹的。所以这个应用应该是可以在网盘里读写文件的。

不过按你说的，建立一个 joplin 的文件夹后，再改 webdav 的网址，发现并不能在 joplin 这个文件夹里生成新的内容了，里面一直是空的。

总之谢谢您的告知，不过我在手机上试了并没有效果，可能电脑上就行吧。

**Comment by laurent22** [comment]
@powersee, this is a configuration issue. The WebDAV URL you gave me is read-only so you can't sync with this at all (and the server responds with improper and misleading 404 errors).

Instead (and I think that's what you've been discussing with studycwq), you need to sync with a subdirectory: `https://dav.jianguoyun.com/dav/joplin`. I've tried that on your server and it synced without any problem, so please give it a try.

**Comment by powersee** [comment]
@laurent22 Yes, i can see the files in subdirectory` joplin `, there have two md file.Thank you, i can sync the file to the server.

@studycwq  抱歉，下午添加子目录后，在手机上更改 webdav 的网址后，点了`检查同步配置`，却忘记了保存配置，才导致同步依然失败。谢谢您。
