### ISSUE TITLE
Pin to taskbar doesn't persist in Windows 10

### ISSUE THREAD

**Issue by lazylionca** [laurent22/joplin#211]
Hey bud, loving the app.
Just wish I could pin it to make it quicker to get to.
Not a huge issue.

Where's your donate button?
I'd like to support this app's continued development.

### Operating system

- [ x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [ x] Desktop
- [ ] Mobile
- [ ] Terminal

Also the word "read" seems to be missing from the sentence below. 
Unless I'm supposed to be offering sacrifices to some spiritual guide.

Please the guide first! https://github.com/laurent22/joplin/blob/master/CONTRIBUTING.md

**Comment by laurent22** [comment]
As far as I can tell pining the app is working? Could you try again?

Thanks for the support but there's currently no donate button. A good way to support the app is to give it a good rating on the Play Store or Apple Store :-)

**Comment by lazylionca** [comment]
The Feb 15, 2018 update fixed it.

Thanks for being responsive. It's appreciated.

**Comment by travelkaefer** [comment]
Work's perfecty great

**Comment by laurent22** [comment]
Not clear how to fix this as it probably depends on the installer. Maybe it is a bug in electron-builder that will eventually get fixed.
