### ISSUE TITLE
Cannot sync via WebDAV on iOS

### ISSUE THREAD

**Issue by mplorentz** [laurent22/joplin#2111]
My iPhone and iPad recently update to Joplin 10.0.39 and I can no longer synchronize.

Trying to sync produces the following error: `Error: PROPFIND .lock Unknown error 2 (401)`

I have checked the permissions on my WebDAV server and Joplin's directory is rwx. 

It looks like Android may have this issue [as well](https://discourse.joplinapp.org/t/latest-android-joplin-began-to-fail-webdav-synchronization/3906). I cannot reproduce on my macOS install.

## Environment

Joplin version: 10.0.39
Platform: iOS
OS specifcs: iOS 13.1.3

## Steps To Reproduce

1. Install iOS version from App Store
2. Set up WebDAV synchronization
3. Try to synchronize

Describe what you expected to happen:
Syncronization should work as it did in the last update.

**Comment by laurent22** [comment]
This is fixed and will be part of the next update. See #2103
