### ISSUE TITLE
brew install joplin on Catalina yields error regarding sqlite3

### ISSUE THREAD

**Issue by kalexmills** [laurent22/joplin#2112]
Instructions for installing on Mac OSX (Catalina) yields the below error regarding sqlite3. Seems to be the case that OSX users need to use the Linux / WSL installation to get the installation working properly for their version of node. This worked for me, although the symbolic link is being a bit uppity at the moment.

Had to stick an alias in .bash_profile to get it to work.

Please update your docs.

## Environment

Joplin version:
Platform: Terminal
OS specifcs: OSX Catalina

## Steps To Reproduce

1. `brew install joplin`
2. `joplin`

Describe what you expected to happen:

Start joplin. Instead, `sqlite3` error. q.q

**Comment by kalexmills** [comment]
Related to #29

**Comment by laurent22** [comment]
Please report this on Homebrew as they often know better than us what the issue is. I think they have a script to automatically build the Homebrew package.
