### ISSUE TITLE
Search in Linux desktop app does not find notes that were just imported

### ISSUE THREAD

**Issue by shankargopal** [laurent22/joplin#2113]
## Environment

Joplin version: 1.0.174
Platform: Linux
OS specifcs: Linux debian 5.2.0-2-amd64 #1 SMP Debian 5.2.9-2 (2019-08-21) x86_64 GNU/Linux

## Steps To Reproduce

1. Export notes from Simplenote, unzip to a bunch of txt files.
2. Change file extension of these files to md.
3. After ensuring desktop app is closed, run terminal app with profile pointing to desktop profile to import each note into a special notebook (previously created using terminal app). Notes show up in correct notebook in desktop app after finishing.
4. Try to search for these notes using either "Goto Anything" or "Full Search" 

Result: Some notes are found - especially if I edit them. Most of those that are not edited are not found. 

Describe what you expected to happen:

All notes would be found. This seems to work fine in the ANdroid app, after these notes have been synced.

**Comment by laurent22** [comment]
The search engine takes some time to build the index. Does it still not work now?

If not please could you provide your log?

**Comment by shankargopal** [comment]
Thanks for the response! Have been using Joplin off and on since the report (not very frequently, but at least opened say 20 times?) and no, it still does not work.  Attaching the log I just generated. When I freshly opened Joplin and tried a search just now (one that failed), I got this in the console:

`2019-11-21 11:57:48: "Starting Clipper server on port 41184"
/tmp/.mount_joplinaqBllV/resources/app/gui/NoteText.min.js:721 Got ipc-message: setMarkerCount [0]
/tmp/.mount_joplinaqBllV/resources/app/gui/NoteText.min.js:721 Got ipc-message: setMarkerCount [0]
/tmp/.mount_joplinaqBllV/resources/app/gui/NoteText.min.js:721 Got ipc-message: setMarkerCount [0]
/tmp/.mount_joplinaqBllV/resources/app/gui/NoteText.min.js:721 Got ipc-message: setMarkerCount `
And here is the log

[log.txt](https://github.com/laurent22/joplin/files/3873100/log.txt)

**Comment by laurent22** [comment]
In the log I can't see any issue.

> * After ensuring desktop app is closed, run terminal app with profile pointing to desktop profile to import each note into a special notebook (previously created using terminal app). Notes show up in correct notebook in desktop app after finishing.

The `--profile` flag is undocumented and unsupported so if something doesn't work after using it, the best is to try again without it.

For example, the desktop app can already import files so you don't need to use the CLI app at all. I would try that - just start over and import the files the normal way via the desktop app.
