### ISSUE TITLE
Added space when copying text with "Code Block" from the viewer

### ISSUE THREAD

**Issue by adyton** [laurent22/joplin#2118]
## Environment

Joplin version: 10.174
Platform: Linux
OS specifcs: Fedora 30 KDE

## Steps To Reproduce

1. Create code block entry 
2. copy text from the viewer

[Screenshot](https://i.imgur.com/DcgnNgM.png)

Describe what you expected to happen:

Expected each line to not include a space at the end
When I copy the code to run in Bash, it fails.

**Comment by tessus** [comment]
I can confirm this. This doesn't happen in the [demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%60%60%60%5CnThis%20is%20a%20codeblock%5Cnover%20several%20lines%5CnTo%20check%2C%20if%20there%5Cnare%20spaces%20at%20the%20end%20of%20each%20line.%5Cn%60%60%60%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D).

Unfortunately I haven't found the reason in Joplin's code. Maybe @laurent22 has an idea.

**Comment by laurent22** [comment]
I can't replicate this on Windows, but I think an issue like that came up before. What's in the rendered view is formatted HTML, not plain text, so you might have artefacts depending on the operating system, and where you paste the text.

So really to be sure you have the source code, you should copy the source code and not the formatted text. Perhaps some day we can add a small "Copy" button next to code blocks that will put the unformatted text in the clipboard.

**Comment by tessus** [comment]
@laurent22 I was able to reproduce this on macOS. I still find it a bit weird that the rendering process adds random artefacts.
