### ISSUE TITLE
Sync with phone app

### ISSUE THREAD

**Issue by danut2006** [laurent22/joplin#212]
### Operating system
Hello,
i have a nextcloud server, and joplin it is sync whit that, i work on my laptop,the app is ok it is sync whit the server but when i check my phone is say that the sync is ok but i don't have the same information like on my laptop.
what should I do to work correctly?

- [x ] Windows
- [ ] macOS
- [ ] Linux
- [ x] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x ] Mobile
- [ ] Terminal

**Comment by laurent22** [comment]
It might be the same bug as this one: https://github.com/laurent22/joplin/issues/209#issuecomment-364920662 Please download the latest mobile and desktop version for a fix.

**Comment by danut2006** [comment]
Hello,
i have install the last version for the app (android) and for the windows and is the same problem. i attache a log from my phone  maybe help to solve the problem.tks. 
[log.TXT](https://github.com/laurent22/joplin/files/1724471/log.TXT)

**Comment by laurent22** [comment]
This appears to be the same problem as #209. The file 44437377c2fb48e393084c7749aade65.md is corrupted on Nextcloud. To fix it you can add "type_: 1" at the end of it so the end of it would look like this:
```
...
...
user_created_time: 2018-02-12T10:12:59.594Z
user_updated_time: 2018-02-12T10:13:09.425Z
encryption_cipher_text: 
encryption_applied: 0
type_: 1
```

Or if this note is not important you can simply delete it and sync again.

**Comment by danut2006** [comment]
Hello, tks for the support, i try what you say and it's work.

tks you again.
