### ISSUE TITLE
Back Button on iOS returns to "root notebook"

### ISSUE THREAD

**Issue by Fab21000** [laurent22/joplin#2120]
## Environment

Joplin version: 10.0.40
Platform: iOS 13
OS specifcs:

## Steps To Reproduce

1. Open a specific note in Joplin.
2. Open a link to another note.
3. Press the back button.
4. You will return to the "root note" and not to the last viewed note.

The same thing like in bug report #1529.

Describe what you expected to happen:
-> Pressing the back button should switch to the last viewed note.

**Comment by laurent22** [comment]
Not really a bug as it's just not implemented on mobile.

**Comment by Fab21000** [comment]
It is still relevant for me.
I use Joplin with a huge library of notes. Always start from the root directory is not the easiest way. 
It would be great to navigate back and forward in the app too.
