### ISSUE TITLE
Deleting the last note in what tag that tag remove

### ISSUE THREAD

**Issue by 2jaeyeol** [laurent22/joplin#2121]
## Environment

Joplin version:
Platform: application
OS specifcs: ubuntu 18.04

## Steps To Reproduce
1. delete last note, to do belong to tag_name1 
2. remain tag_name(0)

I want the tag to remain better even if i delete the last note

now, deleting the last note that belongs to the tag will delete the tag, automatically

delete tag already exists in tagline 

the tags i what to use again have the hassle of creating new ones

so i want change if tag_name has 2 notes tag_name(2) -> delete 2 notes -> tag_name(0)

what do you think?

**Comment by laurent22** [comment]
Tag is still there but hidden if no notes are associated, so you need to manually type it. There's no plan to change this behaviour at this point.
