### ISSUE TITLE
Web client?

### ISSUE THREAD

**Issue by piranna** [laurent22/joplin#2124]
Is there a joplin web client, so could be hosted somewhere and access without needing to install a local client? In the same way, is it possible to show the notes on a web page, similar like a blog engine? I'm not too much into blogging, but I do a lot of notes and web clips that would like to publish and keep organized.

**Comment by tessus** [comment]
No. There isn't. Check the forum for a 3rd party web app.

Also what is unclear about the following statement:

⚠🚨⛔ The issue tracker is not for questions. ⛔🚨⚠

As it happens, support requests that are created as issues are likely to be closed. We want to make sure you are able to find the help you seek.

## Questions and Help

Please read the [documentation](https://joplinapp.org/) and [FAQ](https://joplinapp.org/faq/) first.

### https://discourse.joplinapp.org/

If you have still questions related to Joplin, please open a topic in the [forum](https://discourse.joplinapp.org/).
You can use your GitHub credentials to login to the forum.

## Links

- Documentation: https://joplinapp.org
- FAQ: https://joplinapp.org/faq/
- Forum: https://discourse.joplinapp.org
- How to enable end-to-end encryption: https://joplinapp.org/e2ee/
- API documentation: https://joplinapp.org/api/
- How to enable debug mode: https://joplinapp.org/debugging/
