### ISSUE TITLE
Unable to sync with Nextcloud on Android

### ISSUE THREAD

**Issue by maximelouet** [laurent22/joplin#213]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

**App version**: `android-v1.0.95`
**Android version**: `7.0 (MIUI 9.0.3.0)`

Hi,

I'm trying to sync the Joplin Android app with my personal Nextcloud, but when I synchronise (or "Check synchronisation configuration"), the status won't go past "in_progress". After ~3 minutes, the request timeouts with the error "Network request failed" (see log file below).

Here is a screenshot of the log after the timeout :

![joplin-sync-android](https://user-images.githubusercontent.com/8074940/36119892-b2a539ba-1041-11e8-96ef-1573800c6a06.png)

I don't know if it's a problem with the app or with my phone. My Nextcloud credentials are correct, since I use the same on desktop.

Thank you for your help :)

**Comment by laurent22** [comment]
It might be the same bug as this one: https://github.com/laurent22/joplin/issues/209#issuecomment-364920662 Please download the latest mobile and desktop version for a fix.

**Comment by maximelouet** [comment]
Thank you for your answer. I downloaded the latest desktop version (`Joplin 1.0.62 (prod, linux)`), and I already have the latest on my mobile (`android-v1.0.95`).

I can confirm the problem is still the same, even after deleting all Joplin data on Nextcloud, re-syncing the Desktop app to Nextcloud, and trying to sync the mobile app with Nextcloud. Nothing is fetched from the mobile app and the log error is "Network request failed".

**Comment by laurent22** [comment]
After you setup the Nextcloud config, if you click on "Check synchronisation configuration" on the config screen, does it work?

**Comment by maximelouet** [comment]
No, it's the same behaviour.
Here is the result after 3 minutes of loading:

![media-20180213](https://user-images.githubusercontent.com/8074940/36143469-77c81e10-10ab-11e8-99fb-f6ad8bf3cc16.png)

**Comment by laurent22** [comment]
This is strange, it means the app cannot access the internet or the Nextcloud service. Can you access your Nextcloud website from the device's browser? Also do you know if syncing with eg. OneDrive works?

**Comment by maximelouet** [comment]
I can access the Nextcloud website from the device's browser. But sync with OneDrive does not work either :

![media-20180213 1](https://user-images.githubusercontent.com/8074940/36144101-50d8372a-10ad-11e8-9a81-a2bfe5c67b43.png)

**Comment by laurent22** [comment]
I'm confused by this bug as it seems the app simply does not have access to the network. Is it going through a proxy or VPN?

**Comment by furbysingh** [comment]
Seems like this is a [bug in Android 7.0](https://code.google.com/p/android/issues/detail?id=224438) fixed by 7.1.1 being 7.0 only supports ONE elliptic curve: prime256v1 

One workaround for Nginx is adding `ssl_ecdh_curve prime256v1;` to `/etc/nginx/snippets.d/ssl_default`

More details: [Stack Exchange](https://stackoverflow.com/questions/39133437/sslhandshakeexception-handshake-failed-on-android-n-7-0)

**Comment by maximelouet** [comment]
Wow... Yeah it was the problem. I changed the setting in nginx and it works now. Thank you for your help :)
