### ISSUE TITLE
Take photo don’t work in iOS

### ISSUE THREAD

**Issue by lgabryel** [laurent22/joplin#2130]
Can’t Take photo. Jest black screen. I Allos Joplin to access camera. 

![AA680ECC-8C67-4B89-B01E-F91BB01E45CF](https://user-images.githubusercontent.com/15322615/69852350-54729580-1284-11ea-8d33-613a5fad123c.png)

## Environment

Joplin version: 10.0.40 from AppStore
Platform: iPhone 8 iOS
OS specifcs: 13.1.3 

## Steps To Reproduce

1. Go inside note
2. Attach -> Take a photo

**Comment by szakeetm** [comment]
Bug confirmed on iPhone 11 Pro.

**Comment by szakeetm** [comment]
This issue is still open. You can't take a photo with the iOs app, which would be extremely important (scanning documents, etc).

**Comment by lgabryel** [comment]
I resovle this issue by buing android phone, but meaby other still need this?

**Comment by szakeetm** [comment]
Joplin is a note taking app. One of its basic functions (take a photo of a document, like a drawing or a bill and add it to the note) doesn’t work for more then a year. “Maybe others still need this” is strange, I suggest the function should either be fixed or removed.

**Comment by szakeetm** [comment]
It seems that this issue is duplicate of [#658](https://github.com/laurent22/joplin/issues/658)

**Comment by szakeetm** [comment]
Issue still open.

**Comment by szakeetm** [comment]
Issue still open.

**Comment by szakeetm** [comment]
still not fixed

**Comment by ZKTKZ** [comment]
Replicated on iPhone 11 Pro. However, pressing the reverse camera button fixes this for me. But yes, the initial black screen remains unresolved.

**Comment by szakeetm** [comment]
I confirm that the reverse camera fixes it, thank you @ZKTKZ 
As recommended, the issue could be closed if the initial black screen is fixed

**Comment by szakeetm** [comment]
issue still open as of today

**Comment by szakeetm** [comment]
Bug seems fixed on iOs14 / Joplin 10.0.53 / iPhone11 Pro.
