### ISSUE TITLE
FetchError: unable to vertify certificate [OneDrive]

### ISSUE THREAD

**Issue by palemon** [laurent22/joplin#2132]
## Environment

Joplin version: JoplinPortable (latest version that exist 2019-11-29)
Platform: Windows
OS specifcs: Windows

## Steps To Reproduce

1. Start Joplin, and try to sync using Onedrive
2. Error appears. 

The syncronization doesn't work, using OneDrive. The certificate cannot be vertified. 

I have tried to remove Joplin completely (JoplinProfile & AppData\Roaming\Joplin), and later reinstall it. The error still appears however. 

## Logfile

`Last error: FetchError: request to https://public.dm.files.1drv.com/y4m36W6OXi7gHy_l2B1HhcLKVp1kbRWcU8eOwd2fc8FTTk1Fr16Zn5AVbBffFkdObuGLTrmEYYMPeMzQ_JjxRAvXbD0U5Rwyc_DfQ2GpYqQ1Dp6_hER5Zjg4Ik8y5IkMaD0z7AJQ8dKK4giWe_ywIq5hRg9904p6tncMXawaCWpGIeQhcHGC7JUj7qvulgypL-rfpbm4ctvgcsy-8_yAhwpv9B-1naOgkTeOSUiBca2hjA/version.txt failed, reason: unable to verify the first certificate`

**Comment by laurent22** [comment]
Do you have something like a custom certificate set on the Nextcloud or WebDAV options?
