### ISSUE TITLE
pCloud Webdav sync issues with Joplin

### ISSUE THREAD

**Issue by ioogithub** [laurent22/joplin#2136]
## Environment

Joplin version: Bug has been seen with versions 1.0.170-1.0.174
Platform: PC
OS specifics: Bug has been seen on Debian 10.2, Debian 10.1,  Fedora 30 and Windows 10

## Steps To Reproduce

1. Launch a new instance of Joplin from a clean jex backup
2. Setup webdav sync with pcloud
3. Sync to pcloud.
4. Sync goes fine for some time. After a while, errors start to appear.
5. On several different tests, different next steps were observed:
5.1 The sync reported "Complete" however the Synchronization Status page shows only half the items were synced. Looking at pCloud it can be observed that all the files are not there.
5.2 The sync doesn't report complete however the webdav error messages are spit out into the Joplin status window and Sync stops. It can be restarted several times manually.
5.3 The sync gets stuck in a sync loop and never finishes.

## Errors observed in the logs:

```
<title>500 Internal Server Error</title>
2019-11-30 20:09:32: "**FetchError: response timeout at https://webdav.pcloud.com/Joplin/ over limit: 120000**
FetchError: response timeout at https://webdav.pcloud.com/Applications/Joplin/ over limit: 120000
    at /tmp/.mount_JoplinsXVknw/resources/app/node_modules/node-fetch/lib/body.js:117:12"
```

```
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method **MKCOL is not allowed for the URL** /Joplin/**.lock/**.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at webdav.pcloud.com Port 443</address>
</body></html>
```

```
### 404 Note found errors
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /Joplin/817e8c55f67f45979ac5be28ce3466e6.md **was not found on this server**.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at webdav.pcloud.com Port 443</address>
</body></html>
```

## Describe what you expected to happen:
I would expect the syn to finish successfully.

The never completes successfully however several files have been corrupted in the process. This can be tested by creating a new Joplin instance, connecting to pcloud, syncing to download all notes. At a certain point, Joplin will go into a "sync loop" and the error log will be filled up with infinite instances of this message:

019-11-30 21:41:46: "DecryptionWorker: starting decryption..."
2019-11-30 21:41:46: "DecryptionWorker: 1d3ef47fb59a419bae5f1f6dd8afdf74 decryption has failed more than 2 times - skipping it"
2019-11-30 21:41:46: "DecryptionWorker: f9e7e97f7d5447748d55c10b1acb1f49 decryption has failed more than 2 times - skipping it"
2019-11-30 21:41:47: "DecryptionWorker: d69f7d42f1b7442ab3101fbf9cf6ab80 decryption has failed more than 2 times - skipping it"
2019-11-30 21:41:47: "DecryptionWorker: completed decryption."
2019-11-30 21:41:47: "DecryptionWorker: Some resources have been downloaded but are not decrypted yet. Scheduling another decryption. Resource count: 3" 

## Logfile
1. Log file when attempting to upload data to pcloud 
[1upload.txt](https://github.com/laurent22/joplin/files/3908580/1upload.txt)

2. Log file of a second instance attempting to upload data to pcloud.
[2upload.txt](https://github.com/laurent22/joplin/files/3908581/2upload.txt)

3. Log file when attempting to download data from pcloud.
[3download.txt](https://github.com/laurent22/joplin/files/3908582/3download.txt)

## Other Information
Further discussions is here: https://discourse.joplinapp.org/t/feature-request-pcloud-synchronisation/3530/24

Similar webdav error logs were posted in this bug report: https://github.com/laurent22/joplin/issues/2091

**Comment by ioogithub** [comment]
There is another discussion here of a pCloud sync issue here: https://discourse.joplinapp.org/t/feature-request-pcloud-synchronisation/3530/28

**Comment by laurent22** [comment]
Could you provide a test username and password so that i can try to replicate the issue locally? You can send it to the support address or pm on the forum.

**Comment by ioogithub** [comment]
Are you looking for a pCloud username and password? You can easily create a free account (https://www.pcloud.com/) and try to do some test syncing. The server is at **https://webdav.pcloud.com**

I have tested syncing to pCloud on Windows 10 and various Linux distros as well as various Joplin clients. One think I noticed is that it appears to sync find for a while. It isn't until after around an hour or so that errors start to be thrown. If you take a dataset with 3 or 4 gig and around 1000 notes and 1000 attachments it would be similar to what I have been trying to sync with.

As an aside, I did open a support ticket with pCloud and asked them about the various errors we are seeing in the log as recorded above.

**Comment by laurent22** [comment]
If it works fine with a few files but fail after a while it's most likely a pCloud issue.

**Comment by ioogithub** [comment]
I am not certain that it actually does work fine with a few files because when I did the test to pull the data back down from pCloud, I got the error decrypting files issue right away so it is possible that it doesn't work at all but I do know that I didn't see the errors in the log until after a period.

**Comment by zoltix** [comment]
Hi, 
I have the same issue with pcloud.
I think it's related with the numbers of notes because this error is more and more occur with the number of notes.

**Comment by ioogithub** [comment]
I only have less than 2000 notes. Do you think this small number could be causing the problem?
