### ISSUE TITLE
Android attachments can't be downloaded

### ISSUE THREAD

**Issue by RPDiep** [laurent22/joplin#214]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

I'm seeking the possibility to attach a file to a note and download the file in the android client.

I have a note with a pdf file attached and it's displayed as `(Resource not yet supported: example.pdf)`

Is this just an issue with the file or something that needs to be implemented?

Thanks for a great app and the nextcloud sync!

**Comment by laurent22** [comment]
Closed as duplicate
