### ISSUE TITLE
In Spanish there are texts that cannot be translated

### ISSUE THREAD

**Issue by tanrax** [laurent22/joplin#2140]
## Environment

Joplin version:
Platform:
OS specifcs: macOS and Linux

In Spanish there are texts that cannot be translated

![Screenshot 2019-12-02 at 13 50 25](https://user-images.githubusercontent.com/4553672/69961038-2f438880-150b-11ea-89a3-a40ba7ca2839.jpg)
![Screenshot 2019-12-02 at 13 51 25](https://user-images.githubusercontent.com/4553672/69961043-31a5e280-150b-11ea-9a13-50f0ca461aaa.jpg)

**Comment by tessus** [comment]
Hmm. Can you please pull the latest changes from master. They are translsated in the .po file:

Cambia la lista de notas
Tamaño de página para exportar
Orientación de la página para exportar PDF

**Comment by tanrax** [comment]
There is a bit of a mess, for example the string "Open template directory" in the .po is like this
```
#, fuzzy
#~ msgid "Open template directory"
#~ msgstr "Directorio para exportar de Joplin"
```
That's why it's not rendered.

"Toggle note list" does not exist.

And finish "Page size for PDF export" exists correctly in the .po but is not shown.

1.0.174 version

What if the .po is compiled again?

**Comment by tessus** [comment]
I'm not sure what is going on.

@laurent22 it seems that some strings are missing in the `.pot` file. `build-translation.js` does not add them thouugh.

**Comment by laurent22** [comment]
Isn't it the same issue that we fixed but we haven't released yet? Dropped strings indeed were commented out but shouldn't be anymore.

**Comment by tessus** [comment]
Yes and no. I checked the `.pot` file on git master. I also ran `build-translation.js`, but the string "Open template directory" is not in the .pot file. And in the Spanish .po file, it is commented out.

So something is off, because the string "Open template directory" is clearly used in the app, but does not show up in the translation files. At least not in the pot file or in es_ES.po. I haven't check the other files.

Building the pot file should not have anything to do with the change to guard against deleting strings.... So I'm not sure what's going on.

**Comment by laurent22** [comment]
Indeed it seems it doesn't pick up the strings [in this array](https://github.com/laurent22/joplin/blob/840cdf551273d5da8111bc91e7922f79c1d2d570/ElectronClient/app/app.js#L549) but it used to as the translations are in the .po files, but commented out. Running gettext 19.x doesn't fix it, so I don't have a fix at this point. It might be that we have to wait a few months for a non-broken version of gettext.

**Comment by tessus** [comment]
This is really strange, because I'm using gettext 0.19.8.1 for some time and I remember that thlose strings were in the translations. I just don't understand why.

**Comment by laurent22** [comment]
That's what I'm using too, and it's a mystery to me why they don't show up anymore. Unlike the previous issue where dozens of strings disappeared, this one is not bad enough that I want to spend time investigating.

The good news is that we now have something to detect when strings disappear from files so it shouldn't happen again.

**Comment by tessus** [comment]
I understand, but is it possible to add them manually or will they be removed the next time we run `build-translation.js`?

**Comment by laurent22** [comment]
They'll be removed the next time we run gettext unfortunately.

**Comment by tessus** [comment]
Hmm, even newer translations are not picked up. e.g. `Custom stylesheet for rendered Markdown` is [missing](https://github.com/laurent22/joplin/blob/21cac248b3b52def8211465b3374a495de712f3f/ReactNativeClient/lib/models/Setting.js#L434), but the one a few lines below is there.

This is very puzzling.
