### ISSUE TITLE
Box.com Webdav sync issue with Joplin, error 503 and stops syncing

### ISSUE THREAD

**Issue by ioogithub** [laurent22/joplin#2145]
## The Issue
Joplin won't sync with Box.com, generated errors in the log then reports "Complete"

## Environment
Joplin version: 1.0.174
Platform: Linux
OS specifcs:

## Steps To Reproduce

1. Create a box.com account
2. Install fresh copy of Joplin
3. Setup Encryption and Sync
4. Start Syncing, after around 2 or 3 minutes errors are thrown.
5. Joplin doesn't recover, the Sync button is stuck in a "Cancel" status with nothing happening.

Describe what you expected to happen:
I would expect that Joplin syncs notes to box.com.

## Logfile
From the log:

Code: 503
Error: PUT da5c76949a5a489c85e8fca5977ee470.md: [credence3264.lv7.box.net] Too many waiters on semaphore for connection pool app-db00015.us-las-b.dc001.prod.box.net_3306_7de0c15d-1692-4731-8459-36a8040526b1_a432d720-a2d5-4d0e-8a27-221f5f9ac884 serving mysql://box_live_crd_rw:*****@app-db00015.us-las-b.dc001.prod.box.net:3306 (Exception DataAccessRetryRequestException) (503): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>DataAccessRetryRequestException</s:exception>
  <s:message>[credence3264.lv7.box.net] Too many waiters on semaphore for connection pool app-db00015.us-las-b.dc001.prod.box.net_3306_7de0c15d-1692-4731-8459-36a8040526b1_a432d720-a2d5-4d0e-8a27-221f5f9ac884 serving mysql://box_live_crd_rw:*****@app-db00015.us-las-b.dc001.prod.box.net:3306</s:message>
</d:error>

This error is shown in the log several times then it returns to this:

2019-12-03 16:06:28: "Running background sync on timer..."
2019-12-03 16:06:28: "Scheduling sync operation..."
2019-12-03 16:06:28: "Preparing scheduled sync"
2019-12-03 16:06:28: "Starting scheduled sync"
2019-12-03 16:10:49: "RevisionService::maintenance: Starting..."
2019-12-03 16:10:49: "RevisionService::maintenance: Service is enabled"
2019-12-03 16:10:49: "RevisionService::collectRevisions: Created revisions for 0 notes"
2019-12-03 16:10:49: "RevisionService::maintenance: Done in 106ms"
2019-12-03 16:11:28: "Running background sync on timer..."
2019-12-03 16:11:28: "Scheduling sync operation..."
2019-12-03 16:11:28: "Preparing scheduled sync"
2019-12-03 16:11:28: "Starting scheduled sync"
2019-12-03 16:11:28: "Synchronisation is already in progress. State: in_progress"

Joplin is stopped and restarted, sync reports "Completed 2019-12-03 16:06:28:"  it does not start syncing again. Can't recover from this.

**Comment by laurent22** [comment]
503 is server error most likely we can't fix. You'll need to report to box.com

**Comment by laurent22** [comment]
How many simultaneous connections do you have setup in your config screen? Have you tried setting it to 1?

**Comment by ioogithub** [comment]
I have the default of 5 connections. I have not tried setting it to 1, I can try this.

Is box.com known to work reliably with Joplin?

**Comment by laurent22** [comment]
It was, but they have deprecated WebDAV support so it probably doesn't anymore. https://community.box.com/t5/Box-Product-Updates/Update-WebDAV-Support/idi-p/67050

I'm going to remove it from the Readme.
