### ISSUE TITLE
Whats the file size limit for an attachment in Android?

### ISSUE THREAD

**Issue by filisko** [laurent22/joplin#2146]
Hi,

I attached a pdf of 44mb and when I sync in Android it says something like 'resource not available for [id].md' but i synced from another laptop and it worked perfectly. Small files around 3-4mb work nice.

Any help?

**Comment by tessus** [comment]
⚠🚨⛔ The issue tracker is not for questions. ⛔🚨⚠

As it happens, support requests that are created as issues are likely to be closed. We want to make sure you are able to find the help you seek.

## Questions and Help

Please read the [documentation](https://joplinapp.org/) and [FAQ](https://joplinapp.org/faq/) first.

### https://discourse.joplinapp.org/

If you have still questions related to Joplin, please open a topic in the [forum](https://discourse.joplinapp.org/).
You can use your GitHub credentials to login to the forum.

## Links

- Documentation: https://joplinapp.org
- FAQ: https://joplinapp.org/faq/
- Forum: https://discourse.joplinapp.org
- How to enable end-to-end encryption: https://joplinapp.org/e2ee/
- API documentation: https://joplinapp.org/api/
- How to enable debug mode: https://joplinapp.org/debugging/
