### ISSUE TITLE
Joplin showing an innacurate "Fetching resources" number.

### ISSUE THREAD

**Issue by ioogithub** [laurent22/joplin#2149]
When downloading notes, Joplin is showing a huge number of "fetching resources", ten times more than all the resources in the data set.

##  Environment

Joplin version: 1.0.174
Platform: Linux

## Steps To Reproduce

1. Create a fresh instance of Joplin
2. Setup syncronization, click Syncronize to start
3. Observe the syncronization statistics in the status window. The number is incorrect.

Describe what you expected to happen:
I expect the correct number of resources to be displayed.

## Logfile

Fetching resources is showing 11311 resources but there are only 2049 resources in total in the whole dataset:

![joplin](https://user-images.githubusercontent.com/58017942/70106431-89dc0200-163b-11ea-8bc1-91e1eda3d3ad.png)

**Comment by tessus** [comment]
What is the output of Total in menu item `Synchronization Status`?

**Comment by ioogithub** [comment]
Sync status (synced items / total items)
Note: 750/750
Folder: 73/73
Resource: 1200/1200
Tag: 3/3
NoteTag: 21/21
MasterKey: 1/1
Revision: 12/13
Total: 2060/2061

So it finished synchronizing but it went though and counted down from 11,311 to 0 then did other syncing after that. No idea where that number comes from.

I also noticed that during the sync, the little sync icon stopped for around 15 minutes then started again. That is unusual as well.

**Comment by tessus** [comment]
@laurent22 any idea why the number is so much off?

**Comment by laurent22** [comment]
No, no idea, I haven't been able to replicate this.
