### ISSUE TITLE
PRIMARY selection does not work on Linux Desktop.

### ISSUE THREAD

**Issue by matoken** [laurent22/joplin#215]
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

Hello
I am importing evernote data and using Joplin.
I use it on the Linux Desktop. Clipboard can be used, but PRIMARY selection (https://en.wikipedia.org/wiki/X_Window_selection) does not work.

I heavily use this, so I am glad that you can respond.

**Comment by laurent22** [comment]
Hmm I'm not sure what can be done about this, shouldn't it "just work"? I guess each application shouldn't need custom code to handle this?

Or maybe it's a bug in Electron? Do you know if the PRIMARY selection works with other Electron apps like Skype for instance?

**Comment by matoken** [comment]
I'm sorry I do not understand Electron.

I tried PRIMARY selection in some applications.
It seems to work with Skype and Marp.

-|Joplin|skype|Marp
----|----|----|----
shift + Ins | x | o | o
middle-mouse| x | o | o

The copy source is Leafpad 0.8.18.1.
I tried with Joplin 1.0.64-x86_64, Skype 8.15.0.4 and Marp v0.0.11 (https://yhatt.github.io/marp/).
Distribution is Debian sid amd64.

**Comment by daniellandau** [comment]
For me primary selection works in the direction other apps -> Joplin, meaning I can middle click in Joplin and the contents of the primary selection are pasted. Selecting text in Joplin from the rendered pane correctly fills the primary selection, but from the edit pane it does not.

Does the edit view do something strange with the selection?

**Comment by daniellandau** [comment]
Yes this is still a problem.

**Comment by daniellandau** [comment]
On further testing the direction other apps -> Joplin works for me with an actual mouse middle click, but not on a trackpad triple click. I don't know what to do about that one.
