### ISSUE TITLE
[Feature Request] iOS: Swipe Left Edge of Screen to Go Back from Note/To-Do View

### ISSUE THREAD

**Issue by jgallias** [laurent22/joplin#2151]
## Environment

Joplin version: 10.0.40
Platform: iOS
OS specifics: 13.2.3

## Steps To Reproduce

1. Try to swipe-left-edge of screen to go back to Notebook from Note/To-Do Item view
2. Nothing will happen; you have to tap the upper-left back arrow.

Describe what you expected to happen:
View would go back to Notebook from Note/To-Do Item when using swipe-left-edge

If you are already in Notebook view then the swipe-left-edge gesture works and shows the left sidebar.

**Comment by tessus** [comment]
where's the link to the discussion on the forum?

**Comment by tessus** [comment]
Only accepted festure requests (on the forum) can be opened on gh.
