### ISSUE TITLE
Control clicking links in the editor doesn't open the link

### ISSUE THREAD

**Issue by jtagcat** [laurent22/joplin#2155]
![Screenshot from 2019-12-05 03-30-20](https://user-images.githubusercontent.com/38327267/70195934-0b489880-16ff-11ea-8652-cd2cc9fd4c62.png)
Holding down `Ctrl` and clicking `https://joplinapp.org/markdown/` normally opens the link in other editors.

### Environment
Revision: 0ca96ee
Appimage, Fedora 31

**Comment by laurent22** [comment]
This is not supported
