### ISSUE TITLE
Sync Error through Onedrive

### ISSUE THREAD

**Issue by mk2016a** [laurent22/joplin#2158]
Created remote items: 1.
Completed: 12/06/2019 11:55
Last error: SyntaxError: OneDriveApi::exec: Cannot parse JSON error: <!DOCTYPE html>
 <html>
 <head>
 <title>Runtime Error</title>
 <meta name="viewport" content="width=device-width" />
 <style>
 body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
 p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
 b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
 H1 { font-family:"Verdana****

**Comment by tessus** [comment]
Do you think the template is optional? Open a proper bug report. Thank you.

**Comment by laurent22** [comment]
@mk2016a, that's the fourth invalid bug you post in a few days. For the last time, please read the template and post your issues according to it. For support requests, please use the forum.
