### ISSUE TITLE
Add zoom controls to desktop application menu

### ISSUE THREAD

**Issue by eschafer** [laurent22/joplin#2162]
Most apps let you globally zoom in, zoom out, and reset back to 100% through the application menu (and with keyboard shortcuts). I know there's the global zoom percentage setting, but that changes font sizes rather than scaling the whole page uniformly.

Here's what it currently looks like with the global zoom percentage set to 200:
<img width="1198" alt="Screen Shot 2019-12-08 at 1 02 19 AM" src="https://user-images.githubusercontent.com/1136332/70384975-650bc580-1980-11ea-9734-a2cddaab0803.png">

And here's what it would look like zoomed in at 200%, using [Electron's webFrame.setZoomFactor()](https://electronjs.org/docs/api/web-frame#webframesetzoomfactorfactor):
<img width="1196" alt="Screen Shot 2019-12-08 at 1 02 21 AM" src="https://user-images.githubusercontent.com/1136332/70384997-dc415980-1980-11ea-9814-c8803b713398.png">

I already have this running locally - let me know if you're interested in a PR!

**Comment by laurent22** [comment]
Thanks for the info and the second version indeed looks much better. Is there any drawback using this method, did you notice any bug or something not working properly? If not then yes I'd accept a pull request with this change.

**Comment by eschafer** [comment]
I don't think there are any drawbacks, and it wouldn't be changing any existing functionality. There are still some edge cases where if you zoom in far enough and have enough panels open you won't be able to see everything, but I figured that was out of scope based on how much extra work that would take.

**Comment by tessus** [comment]
> There are still some edge cases where if you zoom in far enough and have enough panels open you won't be able to see everything

I think we can ignore this edge case. That's the same thing has holding a sheet of paper 5 cm away from your eyes. ;-)
