### ISSUE TITLE
Error syncing with OneDrive

### ISSUE THREAD

**Issue by jlgarnier** [laurent22/joplin#2166]
## Environment

Joplin version: 1.0.175
Platform: Windows
OS specifics: Windows 10, up-to-date

## Steps To Reproduce

1. Sync with OneDrive
2. Highly dependant on the items synced... :-(

Describe what you expected to happen:
First sync was error-free (one machine with OneDrive), then added two additional machines (Android 9 smarphone + second laptop, same config than above). Couldn't find any similar issue in the repository but apologize in case of any duplicates.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/3936572/log.txt)

**Comment by CollinChaffin** [comment]
As soon as I attached 2 local file links into a note, for the very first time now Joplin refuses to sync to Onedrive with the following error shown in the GUI:

```
Created remote items: 1.
Completed: 12/11/2019 12:49 PM
Last error: SyntaxError: OneDriveApi::exec: Cannot parse JSON error: <!DOCTYPE html>
 <html>
 <head>
 <title>Runtime Error</title>
 <meta name="viewport" content="width=device-width" />
 <style>
 body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
 p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
 b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
 H1 { font-family:"Verdana
```

As soon as I simply delete the file links, the very next sync it works again with the remainder of that same note intact.

**Comment by laurent22** [comment]
Hmm, it seems they've changed something to their API as it's not normal to get this HTML code back.

**Comment by CollinChaffin** [comment]
Sorry also should have included my version running latest 1.0.175/Windows.

**Comment by guqinglei123** [comment]
I also encountered the same situation, how to solve it？

**Comment by CollinChaffin** [comment]
Now I'm actually getting sync errors even without attached file links.  In essence, I'm unable to figure out a way to push the sync to work at all.

**Comment by jlgarnier** [comment]
Same, no sync with OneDrive whatever the direction...

**Comment by laurent22** [comment]
I cannot replicate this, but "runtime error" means a bug on OneDrive side so please report this to them too.

In your log, please could you post the complete error message, including all the HTML code that starts with `<!DOCTYPE html><html><head><title>Runtime Error</title>`? As maybe there's a clue in there as to why the OneDrive server is crashing.

**Comment by jlgarnier** [comment]
Hi Laurent,

I've copied herebelow the latest entry in the log file. Hope this is what you expect... 

> 2019-12-15 19:17:42: "SyntaxError: OneDriveApi::exec: Cannot parse JSON error: <!DOCTYPE html>
<html>
    <head>
        <title>Runtime Error</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Runtime Error</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.
            <br><br>

            <b>Details:</b> To enable the details of this specific error message to be viewable on remote machines, please create a &lt;customErrors&gt; tag within a &quot;web.config&quot; configuration file located in the root directory of the current web application. This &lt;customErrors&gt; tag should then have its &quot;mode&quot; attribute set to &quot;Off&quot;.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;Off&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre></code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Notes:</b> The current error page you are seeing can be replaced by a custom error page by modifying the &quot;defaultRedirect&quot; attribute of the application&#39;s &lt;customErrors&gt; configuration tag to point to a custom error page URL.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;RemoteOnly&quot; defaultRedirect=&quot;mycustompage.htm&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre></code>

                  </td>
               </tr>
            </table>

            <br>

    </body>
</html>
 Unexpected token < in JSON at position 0
SyntaxError: OneDriveApi::exec: Cannot parse JSON error: <!DOCTYPE html>
<html>
    <head>
        <title>Runtime Error</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Runtime Error</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.
            <br><br>

            <b>Details:</b> To enable the details of this specific error message to be viewable on remote machines, please create a &lt;customErrors&gt; tag within a &quot;web.config&quot; configuration file located in the root directory of the current web application. This &lt;customErrors&gt; tag should then have its &quot;mode&quot; attribute set to &quot;Off&quot;.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;Off&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre></code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Notes:</b> The current error page you are seeing can be replaced by a custom error page by modifying the &quot;defaultRedirect&quot; attribute of the application&#39;s &lt;customErrors&gt; configuration tag to point to a custom error page URL.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;RemoteOnly&quot; defaultRedirect=&quot;mycustompage.htm&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre></code>

                  </td>
               </tr>
            </table>

            <br>

    </body>
</html>
 Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at OneDriveApi.exec (C:\Program Files\Joplin\resources\app.asar\lib\onedrive-api.js:189:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)"

**Comment by laurent22** [comment]
> Description: An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.

> Details: To enable the details of this specific error message to be viewable on remote machines, please create a &lt;customErrors&gt; tag within a &quot;web.config&quot; configuration file located in the root directory of the current web application. This &lt;customErrors&gt; tag should then have its &quot;mode&quot; attribute set to &quot;Off&quot;.<br><br>

Just to be sure you use regular OneDrive, not OneDrive Business, is that correct?

Because the message makes it look as if you're running something custom with your own config, etc., even suggesting to run a browser on the local server, which makes no sense. If that's not OneDrive Business and you don't have a custom server or config, that's a bug in OneDrive that should be reported to them.

It could be that Joplin is sending the wrong request, but we can't debug anything if they hide the error for "security reasons".

**Comment by jlgarnier** [comment]
You guessed right: I'm using the regular OneDrive Win10 application that comes with Office 365 yearly license (Office 365 Personnel, OneDrive version 2019 build 19.1920926.0012, no custom server), with no custom settings. Microsoft has recentyl added the "vault" features to their product, which adds a 2FA-secured folder on your disk: any clue here?

By the way, I could try to reinstall the local app but it seems the issue lies with the communication with the server... Tell me if you need help to put some pressure onto MS, I'm an old friend! :-)

Thanks for your support!

**Comment by laurent22** [comment]
Hmm, perhaps it's 2FA but the error still makes no sense so we can't know for sure. If you can report this to MS that might help, as their engineers are sometimes receptive to these kind of issues.

**Comment by jlgarnier** [comment]
OK, will try to find my way to the support and push a message, forum in cc...

**Comment by jlgarnier** [comment]
Got an answer from Micosoft asking for a screenshot of the error message: can you please capture one and send it by PM? Or maybe give an email address so I can put you in CC of my return to MS...

Thanks in advance!

**Comment by zytomorrow** [comment]
> > Description: An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.
> 
> > Details: To enable the details of this specific error message to be viewable on remote machines, please create a <customErrors> tag within a "web.config" configuration file located in the root directory of the current web application. This <customErrors> tag should then have its "mode" attribute set to "Off".
> 
> Just to be sure you use regular OneDrive, not OneDrive Business, is that correct?
> 
> Because the message makes it look as if you're running something custom with your own config, etc., even suggesting to run a browser on the local server, which makes no sense. If that's not OneDrive Business and you don't have a custom server or config, that's a bug in OneDrive that should be reported to them.
> 
> It could be that Joplin is sending the wrong request, but we can't debug anything if they hide the error for "security reasons".

if I use OneDrive Business,I would not ues jolpin? Now， I passed the login page ,but the sync function don't work.
![image](https://user-images.githubusercontent.com/16175551/71402311-7f73bd80-2667-11ea-8b49-8be46a46e9d8.png)

**Comment by eagleonfire** [comment]
I have this same problem on one of my Windows machines, but not the other. I am using Windows OneDrive as part of Office 365 Personal (not Business) on both.  

My working Joplin uses Windows 10 Home to OneDrive  at version 1809 and OS build 17763.914   My non working Joplin uses Windows 10 Home to OneDrive at version 1903 and OS build 18362.535. 

Both are at Joplin .175.  Both are using OneDrive version 19.192.0926.0012

Synch error on non working Joplin 
Created remote items: 1.
Completed: 12/29/2019 5:06 PM
Last error: SyntaxError: OneDriveApi::exec: Cannot parse JSON error: <!DOCTYPE html>
 <html>
 <head>
 <title>Runtime Error</title>
 <meta name="viewport" content="width=device-width" />
 <style>
 body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
 p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
 b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
 H1 { font-family:"Verdana

**Comment by jlgarnier** [comment]
Hi Laurent,

I'm still waiting for an answer to my previous message: "Got an answer from Microsoft asking for a **screenshot of the error message**. Can you please capture one and send it by PM? Or maybe **give an email address** so I can put you in CC of my return to MS..."

Microsoft now wants to close the case and I asked them to wait a bit, as I'm (officially ;-)) on holidays, but I'm afraid we lose contact on next Monday...

Thanks in advance!

**Comment by jayhill** [comment]
I am seeing this error every time as well, also on Win 10 with Joplin 1.0.175, except for the most part my note changes seem to be synchronizing successfully. _Something_ isn't working, but it isn't a total failure to connect and upload/download changes.

**Comment by jlgarnier** [comment]
Agreed. Unfortunately, the sync doesn't go through on desktop terminals: notes updates or notebook creation do not display out of the desktop used to perform them and I always use desktop to edit. However, updates are correctly displayed by the Android app, which is supposed to pull data from the same OneDrive source...

**Comment by eagleonfire** [comment]
So I spent some time looking into my use case and it appears as though my notes adds/changes are going up to OneDrive from Joplin 1.0.175 from every one of my devices (Android phone/tablet, Mac, and two Win 10 PCs), but the add/changes do not come down to the Win 10 configuration that has Windows 10 Home to OneDrive at version 1903 and OS build 18362.535. That is my machine that gives the "Last error: SyntaxError: OneDriveApi::exec: Cannot parse JSON error:"  So something changed between the two Windows OS levels that is preventing updates from coming back down to a Win 10 machine at the more current OS level.

**Comment by jlgarnier** [comment]
This is great diagnosing! Looks like I also fell into this trap, as my OS/OneDrive config is the same... Is there any logfile we could throw to Microsoft for debugging this? I've opened a ticket with their customer support for this case.

**Comment by laurent22** [comment]
Anyone has a packet inspection tool like Wireshark? It would be useful to see what request exactly is giving this error message, then we could provide this along with the error messages I've extracted [above](https://github.com/laurent22/joplin/issues/2166#issuecomment-566969841) to Microsoft.

They want a screenshot but they should know it's an API so all we can provide is a screenshot of the error message in Joplin, or of our text editor looking at the response, which is not relevant to them.

**Comment by jlgarnier** [comment]
Yes Laurent, I'll try to install Wireshark and catch the exact transaction data exchange. I'll let you know later of the outcome and will add your comments before sending it back to Microsoft...

**Comment by jlgarnier** [comment]
Installed Wireshark but it seems the tool doesn't allow to capture network traffic from a specific application. I'm investigating other tools and will let you know...

**Comment by RenatoXSR** [comment]
I was having the same issues (sync error with OneDrive, due to its API throwing the same html error reply in the json error body, just like OP).

What fixed the issue for me was deleting a .png resource which had more than 4MB, as suggested in [this forum discussion](https://discourse.joplinapp.org/t/onedrive-sync-error-in-desktop-app/1738/12).

I also recreated an empty file with the same name, in order to stop receiving a "file not found" sync error.

Hope this helps.

Cheers.

**Comment by jayhill** [comment]
Nice find, Renato.

That discussion indicates that there is no plan to support the large file upload API for OneDrive. If I got that working and submitted a PR, is there a product rationale that would block it from being incorporated?

I would certainly benefit from being able to synchronize larger attachments via OneDrive.

**Comment by jlgarnier** [comment]
Nice catch indeed! I've checked the files stored on OneDrive and found a pdf file which weighs 3.95Mb. It's close to the 4Mb limit, so there probably some overhead which crosses the limit and crashes the app. Too bad the large files API is not supported as I can't really name it a "large file"...

In the meantime, I'll switch to Dropbox which seems to not suffer the same issue.

Thanks a lot for the hint!

**Comment by leonp5** [comment]
I'm not sure if it is the same error message but thats what i found, when i googled it. I use an android device (LOS16) a linux machine with Linux Mint 19.3 and an iPhone and synchronize my notes between this devices. Seems, that this error is caused by the iPhone in my case. But i'm not able to understand the message correctly so i post it here. Maybe it helps.

```
Cannot parse JSON: <!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="de" data-locale="de_DE" >
	<head data-user="username" data-user-displayname="username" data-requesttoken="token">
		<meta charset="utf-8">
		<title>
			Dateien - Nextcloud		</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="referrer" content="no-referrer">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
		<meta name="apple-itunes-app" content="app-id=1125420102">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
		<meta name="apple-mobile-web-app-title" content="Nextcloud">
		<meta name="mobile-web-app-capable" content="yes">
		<meta name="theme-color" content="#0082c9">
		<link rel="icon" href="/core/img/favicon.ico">
		<link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#0082c9">
		<link rel="manifest" href="/index.php/apps/theming/manifest?v=0">
		<link rel="stylesheet" href="/core/vendor/select2/select2.css?v=1adcabf4-0">
<link rel="stylesheet" href="/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=1adcabf4-0">
<link rel="stylesheet" href="/index.php/css/core/cd70-5805-jquery-ui-fixes.css?v=7a173342cb0e112d3b11053e87e64a8e?v=1adcabf4-0">
<link rel="stylesheet" href="/index.php/css/core/cd70-5805-server.css?v=7a173342cb0e112d3b11053e87e64a8e?v=1adcabf4-0">
<link rel="stylesheet" href="/index.php/css/core/cd70-5805-css-variables.css?v=7a173342cb0e112d3b11053e87e64a8e?v=1adcabf4-0">
<link rel="stylesheet" href="/apps/files_versions/css/versions.css?v=91a57076-0">
<link rel="stylesheet" href="/index.php/css/firstrunwizard/70e2-5805-firstrunwizard.css?v=7a173342cb0e112d3b11053e87e64a8e?v=1adcabf4-0">
<link rel="stylesheet" href="/apps/files_pdfviewer/css/style.css?v=38dfe638-0">
<link rel="stylesheet" href="/apps/files_videoplayer/css/style.css?v=198068b3-0">
<link rel="stylesheet" href="/index.php/css/core/cd70-5805-jquery.ocdialog.css?v=7a173342cb0e112d3b11053e87e64a8e?v=1adcabf4-0">
<link rel="stylesheet" href="/index.php/css/core/cd70-5805-results.css?v=7a173342cb0e112d3b11053e87e64a8e?v=1adcabf4-0">
<link rel="stylesheet" href="/index.php/css/files/d16b-5805-merged.css?v=7a173342cb0e112d3b11053e87e64a8e?v=1adcabf4-0">
<link rel="stylesheet" href="/index.php/css/files_trashbin/1e6d-5805-trash.css?v=7a173342cb0e112d3b11053e87e64a8e?v=1adcabf4-0">
<link rel="stylesheet" href="/apps/activity/css/style.css?v=b1d71238-0">
<link rel="stylesheet" href="/index.php/css/comments/1bf6-5805-autocomplete.css?v=7a173342cb0e112d3b11053e87e64a8e?v=1adcabf4-0">
<link rel="stylesheet" href="/index.php/css/comments/1bf6-5805-comments.css?v=7a173342cb0e112d3b11053e87e64a8e?v=1adcabf4-0">
<link rel="stylesheet" href="/index.php/css/files_sharing/861d-5805-mergedAdditionalStyles.css?v=7a173342cb0e112d3b11053e87e64a8e?v=1adcabf4-0">
<link rel="stylesheet" href="/index.php/css/core/cd70-5805-systemtags.css?v=7a173342cb0e112d3b11053e87e64a8e?v=1adcabf4-0">
<link rel="stylesheet" href="/index.php/css/systemtags/1bf6-5805-systemtagsfilelist.css?v=7a173342cb0e112d3b11053e87e64a8e?v=1adcabf4-0">
<link rel="stylesheet" href="/index.php/css/files_texteditor/783c-5805-merged.css?v=7a173342cb0e112d3b11053e87e64a8e?v=1adcabf4-0">
<link rel="stylesheet" href="/apps/gallery/css/slideshow.css?v=f4d918f6-0">
<link rel="stylesheet" href="/apps/gallery/css/gallerybutton.css?v=f4d918f6-0">
<link rel="stylesheet" href="/apps/gallery/css/share.css?v=f4d918f6-0">
		<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/index.php/core/js/oc.js?v=1adcabf4"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/core/vendor/core.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/index.php/js/core/merged-template-prepend.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/core/search/js/search.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/core/l10n/de.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/index.php/js/core/merged-share-backend.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/apps/firstrunwizard/js/jquery.colorbox.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/apps/firstrunwizard/js/firstrunwizard.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/apps/files_pdfviewer/js/previewplugin.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/apps/files_videoplayer/js/viewer.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/apps/gallery/l10n/de.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/apps/ocloudadmin/js/script.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/core/search/js/searchprovider.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/core/js/jquery-ui-fixes.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/core/js/files/fileinfo.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/core/js/files/client.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/core/js/contactsmenu.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/apps/files/l10n/de.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/index.php/js/files/merged-index.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/apps/files_sharing/l10n/de.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/apps/files_sharing/js/app.js?v=1adcabf4-0"></script>
<script nonce="ZjN5ZXVjbWVsekx5N1M5aVBuVFN1UExZQ0Jnb0huL2RFT0NkOWc4QUlQOD06S2dUdDNZVHhvM3lBdVVrSFR3MnJ5Y3VVT0V0RFJnYTdaZGlrdFdWeFdaYz0=" defer src="/apps/files_sharing/js/sharedfilelist.js?v=1adcabf4-0"></script>
<script no
```

**Comment by eagleonfire** [comment]
I think I have solved my problem which was giving me the "Last error: SyntaxError: OneDriveApi::exec: Cannot parse JSON error: <title>Runtime Error</title> <style> body {font-family:"Verdana"

This is what I did. I decided to create a new Windows User on the machine where I was having the problem and install Joplin into that User. This meant no change in the OS Level, OneDrive, etc.  just a different Windows User. It worked.   I then went back to my original Windows User and did some poking around.  I decided to remove Joplin completely and noticed it was showing two version installed .175 and .179  I removed everything and reinstalled .179, but the problem still happened which led me to believe that there was some sort profile/config that was persisting.  I saw in the Options for Joplin that _**Notes and settings are stored in: C:\Users\Steve Curtis\.config\joplin-desktop**_   I went digging around in there and in the .config\joplin-desktop\resources I found a file 75e823a3a615b0a7d1fe73e330dfc869.jpg from 11/28/2015 and it was 15mb in size. Once I removed it my problem resolved.  This file was not connected to any notes within Joplin, because when I restored the file back to the directory and re-synched Joplin the problem didn't happen.  So even though I had gone through all my Joplin note attachments to ensure there weren't any files > 4MB, this file was somehow still in the resources directory and causing the  "Last error: SyntaxError:"

**Comment by jlgarnier** [comment]
Hi there,
Unfortunately, the issue has not been solved. The only workaround is to switch to a Dropbox sync, which has its own problems...

**Comment by lovelock** [comment]
I run into this problem too, please help

**Comment by jlgarnier** [comment]
Hi @lovelock, I just dropped OneDrive, which was my preferred location, in favor of Dropbox which works fine. I couldn't catch the issue and don't know if the team has fixed it, sorry...

**Comment by lovelock** [comment]
@jlgarnier Thanks but I am from China mainland and so Dropbox is not an option for me 😂

**Comment by eagleonfire** [comment]
If you're having the problem on Windows I would try the things I suggested to see if that helps.  Look in  .config\joplin-desktop\resources to see if any files are larger than the limit.  I would also try creating another Windows user ID, install fresh Joplin into that and try synching to see if the problem still occurs.  I no longer have the problem and I use all platforms Windows 10, MacOs and Android phone and tablets.

**Comment by lpbdev** [comment]
This bug still works in Joplin 2.8.8. Sad.
