### ISSUE TITLE
Add recheck delete when note delete 

### ISSUE THREAD

**Issue by 2jaeyeol** [laurent22/joplin#2169]
## Environment

Joplin version: 1.0.174 
Platform:
OS specifcs: window10 64

## Steps To Reproduce

1.  insert trashcan line down sidebar like "tags" line small 
2.  or anyway we can reuse already delete note

 

Describe what you expected to happen:
when we delete note and to-do check one time delete or cancle 
i want we have like trash can after delete note
we can reuse already delete note and to-do 
what do you think?

**Comment by laurent22** [comment]
Closed as duplicate
