### ISSUE TITLE
Can't enter text into new note body - Mac app

### ISSUE THREAD

**Issue by toontra** [laurent22/joplin#217]
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

Maybe I'm doing something stupid!

Set up android & Mac app & they are syncing fine.  Imported all my Evernote files OK.

Problem is on my Mac app. (latest version)  I create a new note & title fine but can't enter any text into the body window below.  What am I missing?  

Thanks.

BTW great alternative to Evernote!

**Comment by laurent22** [comment]
I'm not seeing this bug. Is it in v1.0.63?

**Comment by toontra** [comment]
Yes, but I noticed it on previous 2 revisions.  I've only had Joplin for 5 days do I'm pretty sure it's user error.

On the desktop app:  to create new note click on "new note" at top of window, enter title text and then?  Just can't find any way of entering text (or anything) in the note just created.

**Comment by laurent22** [comment]
I can't replicate this, could you provide more information?

In which language is the text you are trying to enter?

Does it do it for every note (including existing ones) or only new ones? Is it only for new notes or new to-dos too? 

Just in case could you try to run the app in [debug mode](https://github.com/laurent22/joplin/blob/master/README_debugging.md) and see if you're getting any error or warning in the log or console?

**Comment by toontra** [comment]
Using English.  

Yes, it does it for every note including those imported from Evernote.  Can't enter/edit anything in the note body.  Same for To-Do's.

I've set up debugging but nothing of interest in console.

Thanks for trying to help!

**Comment by fmrtn** [comment]
I'm getting the same behavior on linux desktop app (1.0.64).

This is the only what I found in console tab:

```
/tmp/.mount_JoplinBwPFga/app/resources/app/node_modules/brace/index.js:1390 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
```

**Comment by fmrtn** [comment]
It's a bug on [layer 8](https://en.wikipedia.org/wiki/Layer_8) :laughing:

@toontra Please, click on **Layout** icon and try again. I think was that.

**Comment by laurent22** [comment]
Great, hopefully that was @toontra issue too. Leaving it open as a bug anyway as it should be made clearer what is the current layout so that it's less confusing.

**Comment by toontra** [comment]
Confirmed working when in dual (side by side) layout mode.  Would be nice if didn't have to do this extra step but OK for now. Thanks for the help.
