### ISSUE TITLE
Extra newlines on image paste

### ISSUE THREAD

**Issue by shoshin71** [laurent22/joplin#2171]
## Environment

Joplin version: 1.0.174
Platform: OSX
OS specifcs: 10.14.6

## Steps To Reproduce

1. Copy an image from some source (e.g. using screenshot, or select all/copy from Preview)
2. Paste image into Joplin note

Describe what you expected to happen:
The string that is inserted into the document to reference the image is preceeded by two extraneous newlines. They are not visible in the preview pane, but clutters up the editing pane. I find it preferable to double-backspace on every paste to remove the newlines. 

Do the newlines serve a purpose, or can they be suppressed?

**Comment by laurent22** [comment]
Originally I put them there because if you attach a picture you don't want it to be right where the caret but below, and two lines below seems even better. However I'm not so sure that's the best way anymore. Perhaps there should be no newlines at all? How do other Markdown editors handle this?

**Comment by shoshin71** [comment]
I can't speak for others, but when I paste an image such as a screenshot while taking notes, I want to type after the screenshot. Perhaps placing the image reference on a line by itself and then placing the cursor below the image would work?
