### ISSUE TITLE
1.0.175 doesn't build from git

### ISSUE THREAD

**Issue by sciurius** [laurent22/joplin#2172]
Fedora 29 running on x86_64.
[npm-debug.log](https://github.com/laurent22/joplin/files/3947351/npm-debug.log)

A fresh checkout of Joplin from git and build according to the BUILD.md results in 

    npm ERR! Linux 5.3.11-100.fc29.x86_64
    npm ERR! argv "/usr/bin/node" "/home/jv/node_modules/.bin/npm" "install"
    npm ERR! node v10.16.3
    npm ERR! npm  v2.15.12
    npm ERR! code EPEERINVALID

    npm ERR! peerinvalid The package markdown-it@8.4.2 does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer markdown-it-anchor@5.2.5 wants markdown-it@*
    npm ERR! peerinvalid Peer markdown-it-toc-done-right@4.1.0 wants markdown-it@^10.0.0

    npm ERR! Please include the following file with any support request:
    npm ERR!     /bulk/tmp/joplin/ElectronClient/app/npm-debug.log

**Comment by laurent22** [comment]
I can't replicate this. Does it make any difference if you delete node_modules and re-install?

**Comment by sciurius** [comment]
No difference. As I said, it is a fresh git clone.

I updated my global npm modules and now the error is gone. It does puzzle me though since I thought that npm was designed to avoid version conflicts.

**Comment by laurent22** [comment]
npm is a mess so it can happen
