### ISSUE TITLE
导入md文件时，md对应的图片无法导入

### ISSUE THREAD

**Issue by qiruizheng** [laurent22/joplin#2174]
导入md文件时，md对应的图片无法导入
![image](https://user-images.githubusercontent.com/4271439/70589006-80d5cc80-1c09-11ea-86bd-69fffa30e9fa.png)

**Comment by tessus** [comment]
Please open tickets in English.

**Comment by qiruizheng** [comment]
When importing md file, the picture corresponding to md cannot be imported
