### ISSUE TITLE
cannot use $b when selecting a note

### ISSUE THREAD

**Issue by yuvalif** [laurent22/joplin#2175]
## Environment

Joplin version: joplin 1.0.149 (prod)
Platform: terminal application on Linux
OS specifcs: Fedora30 

## Steps To Reproduce

1. select a note inside a notebook
2. execute command: `mv $n $b`
3. Output is: `Cannot find "f9c9d2e72d9d43dabc4a5247107f7d4d". `

Describe what you expected to happen:
In this case I'm trying to move the note to its own book, so nothing should happen...
However, the intent is to be able to run something like that: `mv $n $b-archive`
So that I can easily move a note from a notebook called `foo` to a notebook called `foo-archive`

## Logfile

https://paste.centos.org/view/89d6a9f6

**Comment by laurent22** [comment]
It's not a bug, this kind of syntax is simply not supported
