### ISSUE TITLE
<video> in markdown with basic authentication

### ISSUE THREAD

**Issue by gwojcieszczuk** [laurent22/joplin#2181]
In markdown, I'm using the following code for embedding videos.

```
<video width="600" height="480" controls>

  <source src="https://user:password@hostname/file.mp4" type="video/mp4">
</video>
```

When no authentication is used, all works great. However if I include username and password in the url, things are not working. Is there some limitation in Joplin or markdown that doesn't allow the use of basic authentication in links?

**Comment by laurent22** [comment]
We don't support video as of now.
