### ISSUE TITLE
"Check for updates..." pops under application window

### ISSUE THREAD

**Issue by rockhazard** [laurent22/joplin#2182]
## Help>"Check for updates..." pops under application window
- Normal previous behavior is that the update pops up over the window.
- The popunder freezes the application window until it is dealt with, **which can lead users to believe the application has crashed** because of the update checker until this is discovered.
- At least once the application did crash after clicking "Okay" on the updater window, but no logs of the crash were created that I could see. I was using flags.txt and looking at the console at the time.

## Environment

Joplin version: v1.0.175 AppImage
Platform: Intel 8600k, 32g ram, nvidia rtx 2060 gpu, 1tb samsung evo860 nvme, ASRock Taichi Ultimate mobo
OS specifcs: Linux Mint v19.2, Cinnamon v4.2.4, kernel 5.0.0-27-generic

## Steps To Reproduce

1. Click on Help > Check for updates ...
2. Update checker is hidden behind the app window, freezing interface until it is closed.

## Logfile
No relevant logs found.

**Comment by laurent22** [comment]
We use the built in modal dialogs so if they don't work it's an issue with Electron and it might be fixed when we upgrade
