### ISSUE TITLE
Misleading cursor in edit window when not editing

### ISSUE THREAD

**Issue by jammon** [laurent22/joplin#2183]
When a note is selected but the focus is not in the edit window there is still a (grey, not blinking) cursor in the edit window, usually at the beginning of the text. This often made me think that I could start editing right away. But to insert text the user has to click on the edit window explicitly. 

## Environment
Joplin version: 1.0.175 (prod, darwin)
Platform: macOS
OS specifcs: Catalina 10.15.1 (19B88)

## Steps To Reproduce

1. Select any notebook/note.
2. See the grey cursor in the edit window at the last edit position or at the beginning of the note.

Describe what you expected to happen:
I see two ways to solve this:
- hide the cursor when the focus is not on the edit window (because there is no use for a visible cursor in this situation) or
- focus the edit window whenever "edit keys" are pressed. These could be any character key without Ctrl/Alt/Cmd etc. and the right/left keys, that have no function outside the edit window.

**Comment by laurent22** [comment]
It's often tricky to implement this focus-based features, and we don't plan to keep this editor so it wouldn't make sense to spend time on this.

**Comment by jammon** [comment]
Ok, I can understand that!
