### ISSUE TITLE
Joplin not storing window position

### ISSUE THREAD

**Issue by jlgarnier** [laurent22/joplin#2185]
## Environment

Joplin version: 1.0.175
Platform: Win10
OS specifcs: v1909

## Steps To Reproduce

1. Move the main window around and resize it
2. Exit the application
3. Restart the application and check whether the previous position/size are restored.

Describe what you expected to happen:
The previous position/size should be restored.

**Comment by Perkolator** [comment]
Can't reproduce on Windows 8.1(.1). Size and position is the same after restart.

**Comment by ioogithub** [comment]
Yes, I have had this issue however it is highly inconsistent. Sometimes it will work as expected, other times it will redraw the window in a completely random place. I haven't reported it yet because I can't reliable reproduce it but I have seen it on Windows and Linux for several months.

**Comment by mic704b** [comment]
Can't reproduce on Linux, and haven't noticed it.

@jlgarnier does it happen consistently?

**Comment by jlgarnier** [comment]
Wouldn't say "consistently" ;-) but it happens regularly and I can't pin it down to any action (move the window, minimize or whatsoever)...

**Comment by kowalskidev** [comment]
> 
> 
> Can't reproduce on Windows 8.1(.1). Size and position is the same after restart.

same in windows 10. Unable to reproduce. I just checked its working fine!

**Comment by blueorignal** [comment]
I am currently seeing this consistently (every time I open Joplin) with current Joplin (1.0.199) on Ubuntu Linux 18.04 LTS. It only started (for me) with the most recent update of Joplin (1.0.199). I am running the official AppImage of Joplin. All in all a very minor issue.

**Comment by blueorignal** [comment]
Seems to be working correctly for current version. Thank you. From my perspective, please feel free to close this issue.

Joplin 1.0.216 (prod, linux)
OS: Ubuntu 20.04 LTS

**Comment by jlgarnier** [comment]
Hi all, same for me: the issue has been fixed in the current version, so I'll close the ticket!

Thanks again for your support and such a great work!
