### ISSUE TITLE
No docs for soft break 'plugin'

### ISSUE THREAD

**Issue by jtagcat** [laurent22/joplin#2192]
Joplin version: 1.0.174

https://joplinapp.org/markdown/ -> Plugins does not have `Enable soft breaks` plugin listed.

**Comment by tessus** [comment]
Because it's not really a plugin. We added this for people who complained that they are used to the standard Markdown behavior. (line breaks are ignored, only 2 trailing spaces generate a line break.)

@laurent22 should we add something to the docs?

**Comment by laurent22** [comment]
@tessus, yes if you could add a line about it in the doc that would be great.

**Comment by tessus** [comment]
@laurent22 Ok, will do. PR or direct commit? I can work on this in probably one or two hours.

**Comment by laurent22** [comment]
Sure, direct commit is fine, thanks!

**Comment by tessus** [comment]
Ooops, I'm caught up in a few other things, so I will either do it later tonight or tomorrow.
