### ISSUE TITLE
Jianguoyun WebDAV sync failed

### ISSUE THREAD

**Issue by ustcltx** [laurent22/joplin#2195]
## Environment

Joplin version: 1.0.175
Platform: Windows
OS specifcs: Windows 10 1903 (18362.535)

## Steps To Reproduce

1. Configure WebDAV for Jianguoyun
2. Sync

WebDav Path: [https://dav.jianguoyun.com/dav/](https://dav.jianguoyun.com/dav/)

I think the jianguoyun WebDav server  only allows reading and writing in subdirectories, but Joplin can't support saving files in subdirectories.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/3968432/log.txt)

**Comment by F1ReKing** [comment]
+1

**Comment by KuiYang2017** [comment]
我也遇到了相同的问题

**Comment by MoonBegonia** [comment]
1. 在坚果云根目录新建 `Joplin` 文件夹
2. 将 webdev 地址改为 `https://dav.jianguoyun.com/dav/Joplin`
然后再同步试试。
其实这个 issue 已经有人提过了，可以看看 #2107

**Comment by tessus** [comment]
> I think the jianguoyun WebDav server only allows reading and writing in subdirectories, but Joplin can't support saving files in subdirectories.

I'm not sure what you mean. How about you create a Joplin directory on the webdav server and set the sync target to: `https://dav.jianguoyun.com/dav/Joplin`

Also, this is a user question, not a bug report. Please use the forum.

Another tip: read the documentation.
