### ISSUE TITLE
Keyboard cursor jumps while typing

### ISSUE THREAD

**Issue by 0xmohit** [laurent22/joplin#22]
Joplin 0.10.28 (prod, linux)

While creating a note, the cursor appears to *jump backward*.  The effect is essentially equivalent to pressing backspace a few times.

Please refer to the attached clip.

The first line of text being entered was: "The quick brown fox jumps over the lazy dog."

It was followed by a list of 5:
- Item one
- Item two
- Item three
- Item four
- Item five

As observed in the attached video, there are multiple instances where the cursor moves backwards erasing the last few characters.

The behavior was observed while creating several notes.

**Comment by 0xmohit** [comment]
[Clip exhibiting issue.](https://github.com/laurent22/joplin/files/1518442/vokoscreen-2017-11-30_20-35-45.mkv.gz)

**Comment by laurent22** [comment]
Thanks for the bug report and video, I will try to fix this next as it's quite a bad bug. It's probably the note being synced in the background, and the editor updating to the note that has just been synced.

**Comment by adamhammes** [comment]
I am also experiencing this bug :-( Hope to see a new release pushed!

**Comment by laurent22** [comment]
It's fixed and Travis is building the update as we speak (unfortunately it takes 2 hours for the macOS one), so I'll publish it tomorrow :)

**Comment by laurent22** [comment]
The fix is deployed now.
