### ISSUE TITLE
[feature request] - Hide application on macOS

### ISSUE THREAD

**Issue by jcgerhard** [laurent22/joplin#220]
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

----

Please add the possibility to **hide the application** (incl. shortcut **Cmd+H**) as it is implemented for most macOS apps. This would be a very comfortable feature for every-day-users. At the moment one can only open or quit the application.

#### Example

![hide-joplin](https://user-images.githubusercontent.com/29855366/36297210-bf342436-12f1-11e8-907c-a87c96ecf559.jpg)

**Comment by laurent22** [comment]
Done in 4218b65969f71ec470fc5ea2e60278060a0a5e49

**Comment by jcgerhard** [comment]
I was busy for the last days. So sorry for that late answer! Thank you for fixing the shortcuts. Everything works as anticipated except the hiding of the app. The shortcut CMD+H is going to „close“ the main window, but the rest is still there. The menubar is still visible and the app has the focus. Furthermore you can’t re-open the window and get back the focus. You have to open the settings or something like that and go back to the main window by using the „back“ arrow in the upper left corner. It would be desirable if the whole app is going to be hidden and could be „faded in“ again, as it is the normal behavior on macOS. Yesterday I read an article about that...must have something to do with the scope in which the hide() function is called...or something like that.

**Comment by jcgerhard** [comment]
@laurent22: Good evening! I used joplin extensively in the last 2 days (on work and private). Everything works really fine...but the hiding issue is something that is really annoying under macOS. Any chance to get this fixed in the near future?

**Comment by laurent22** [comment]
That should be fixed in version 70.

**Comment by jcgerhard** [comment]
Good morning @laurent22! I updated joplin a few minutes ago to the latest version (v1.0.70) and the bug is gone. The app behaves now in the way, an app should do under macOS. Thank you very much for fixing this! You can close this issue now.
