### ISSUE TITLE
Edit Firefox Extension Link

### ISSUE THREAD

**Issue by ivysrono** [laurent22/joplin#2203]
https://addons.mozilla.org/en-US/firefox/addon/joplin-web-clipper/

to

https://addons.mozilla.org/firefox/addon/joplin-web-clipper/

remove /en-US, then it will auto get local by users.

**Comment by tessus** [comment]
Yes, this is actually a valid observation. If @laurent22 doesn't have any objections, I will change the link in the docs accordingly.

**Comment by laurent22** [comment]
Yes sure, please go ahead and change it directly.
