### ISSUE TITLE
Joplin [IOS version] Put 503 Error

### ISSUE THREAD

**Issue by garywu520** [laurent22/joplin#2209]
Joplin IOS client [V10.0.40] synced to nextcloud error, the last error message: Error: PUT ......... Unknown error2 (503), the picture is the error details.

After my testing, I found that it is related to the nextcloud TLS setting certificate. I fixed the related errors. The Windows version Joplin [Joplin 1.0.175 prod win32] has been synchronized normally, but the Joplin IOS client problem still exists and the IOS version does not "ignore TLS Certificate error "option.

How do I fix it next?
![error](https://user-images.githubusercontent.com/26731482/71233982-3a335100-2332-11ea-984b-8de24c7fa714.JPG)

**Comment by tessus** [comment]
please use the forum for questions.
