### ISSUE TITLE
Add more supported LaTeX equation formats

### ISSUE THREAD

**Issue by N0rbert** [laurent22/joplin#2212]
## Environment

Joplin version: Joplin 1.0.175 (prod, linux)
Platform: Linux
OS specifcs: Ubuntu 16.04.6 LTS amd64

## Steps To Reproduce

1. Try to write scientific text with Joplin.
2. Add equations and some elements of [bookdown](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#equations), some of texts are presentations written with [xaringan](https://bookdown.org/yihui/rmarkdown/xaringan.html).

Use the code with many LaTeX equations notations below:

```
Block LaTeX equation without auto-numbering:

$$ g(x) = \cos(x)$$

---

Environment `\begin{equation}...\end{equation}`
with auto-numbering:

\begin{equation}
h(z) = \sinh(z)
\end{equation}

---

Environment `\begin{equation}...(\#eq:label)\end{equation}`
with auto-numbering and label (for bookdown):

\begin{equation}
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation}

---

Environment `\begin{equation}...\label{label}\end{equation}`
with auto-numbering label for xaringan

\begin{equation}
  g\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
\label{binom2}
\end{equation}
```

**Current actual behavior** - only the first equation is rendered, others are not rendered:
![only-first](https://user-images.githubusercontent.com/309456/71306891-acba3480-23f7-11ea-9645-2d0df51b1a86.png)

**Expected behavior:**

I expect that all these equations are shown in Joplin preview window.
This functionality is currently supported in VNote and ReText as they use MathJax.

## Logfile

I do not see anything latex-related in the log-file.

**Comment by tessus** [comment]
We don't use MathJax and we won't. We use Katex. Please open feature requests with Katex.
