### ISSUE TITLE
#1887 Not working for CLI

### ISSUE THREAD

**Issue by joelcarlton** [laurent22/joplin#2213]
## Description

I ran the CLI the command “joplin help import” and see that the output does not match the documentation located in the Terminal Index [L108](https://github.com/laurent22/joplin/blob/master/docs/terminal/index.html#L801).

Could the [change #1887](https://github.com/laurent22/joplin/commit/172d925f0f6431c68a94cc25598c881fecbe7269)  made to the file [InteropService.js](https://github.com/laurent22/joplin/blame/172d925f0f6431c68a94cc25598c881fecbe7269/ReactNativeClient/lib/services/InteropService.js#L44) be causing the output to display enex twice?

Here is an example of what I am seeing
```shell

➜  ~ joplin help import                                                         
import <path> [notebook]

    Imports data into Joplin.

    --format <format>  Source format: auto, jex, md, raw, enex, enex
    -f, --force        Do not ask for confirmation.

➜  ~ 
➜  ~ joplin version    
joplin 1.0.150 (prod)
➜  ~ 
➜  ~ 
➜  ~ joplin import --format html ~/Documents/Evernote/Export.enex
Importing notes...
Cannot load "importer" module for format "html"
➜  ~ 
```

I ran this command again with enex and it imported successfully as md and not html. I am not sure how I can set the format to html when `format: ‘enex’` is set for both md and html.

## Environment

Joplin version: 1.0.150
Platform: Terminal, zsh 5.3
OS specifcs: MacOS 10.14.6 (x86_64-apple-darwin18.0)

## Steps To Reproduce

1. joplin import file.enex
2. joplin import —format enex file.enex
3. joplin import —format html file.enex

### Describe what you expected to happen:

I would expect that interop service would autodetect the format or allow html to be specified

**Comment by joelcarlton** [comment]
@devonzuegel

**Comment by devonzuegel** [comment]
~Ah that's likely related to the note I left:~

https://github.com/laurent22/joplin/blob/2a63ecef2a21622a8e6ee117eb2367c68f555b04/ReactNativeClient/lib/services/InteropService.js#L56

UDPATE: Actually never mind, that's a separate issue.

I've never actually used the CLI myself, so I'm not familiar with the particular usage in this codebase at all. I imagine the key issue is that the CLI assumes that there's a 1:1 mapping between input formats and the types of processing you want to do. (That was the case for the desktop `Import` menu pictured below before I updated it.)  I'd be happy to review a PR to add the same on the CLI side!

![image](https://user-images.githubusercontent.com/6979755/71565000-767c5500-2a88-11ea-87d1-2b9c37a0d93e.png)

**Comment by joelcarlton** [comment]
I don't have any code for this. I created this issue as a bug but maybe it should be a feature request. Importing Evernote as MD has broken to many notes for me; html seems to be the only way to preserve the original contents. I would think the CLI import should mirror the application.
