### ISSUE TITLE
Joplin Desktop: Two consequtive 'Enters' should remove list prefix on last empty line

### ISSUE THREAD

**Issue by archont00** [laurent22/joplin#2221]
Joplin supports automatic creation of `- ` or `* ` or `1.` for lists after pressing Enter (new line). This is a usefull feature.

However, the user has to delete the prefix on the last empty line - Joplin keeps it there:
```
- the first item
- the second item
-
...Text continuation...
```
The last empty item of the list is still prefixed but it should not be.

## Environment

Joplin version: 1.0.175 AppImage
Platform: Linux
OS specifcs: Arch Linux

## Steps To Reproduce

In desktop app:

1. Create a new note
2. Start an unnumbered list `- first item`
3. Press Enter and Joplin would prepend a `- ` on a new line. You can continue typing any text.
4. Press Enter. Joplin will create a `- ` on any empty line. Do not type anything.
5. Press Enter. Joplin will not create `- ` on another new line.

**Describe what you expected to happen:**

In step 5, I would expect that Joplin automatically removes the `- ` on the previous empty line created in step 4 (and leaves there an empty new line).

```
- the first item
- the second item

...Text continuation...
```

**Comment by mic704b** [comment]
I think Joplin uses the [ACE](https://github.com/ajaxorg/ace) editor.  I tried it on their live demo and it didn't clear the line either, so raising an issue on that project might help.

**Comment by lennartb-** [comment]
This is still an issue and annoys me to no end because I use lists very frequently in my notes.
