### ISSUE TITLE
Bad version download in update action, and bad update dialog. 

### ISSUE THREAD

**Issue by lgabryel** [laurent22/joplin#2228]
When in portable version run Joplin, or check update, that update monit ask me if I want to download new wersion. When i exit by X then, download will start. That mean X work like "YES", but I think X should work like "NO". But this is no big problem. After download update, new version, this is still old version 1.0.174, and should be 1.0.175.

## Environment

Joplin version: 1.0.174
Platform: Win32
OS specifcs: Windows 10

## Steps To Reproduce

1. Run portable version
2. Check update

Describe what you expected to happen:
Download new version.

**Comment by laurent22** [comment]
Cannot replicate
