### ISSUE TITLE
File system sync should include resources / attachments etc.

### ISSUE THREAD

**Issue by msbentley** [laurent22/joplin#223]
### Operating system

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [ ] Terminal

I've just done my first "sync" - in this case via to a file system (in fact my Dropbox folder). This works fine, but note resources (images, attachments etc.) appear to only be stored in the resources folder in my `.config` directory. It would be great if they would also be stored in the filesystem folder in this case (optionally, perhaps) so that everything would be accessible from another machine pointing to the same sync'd folder...

**Comment by laurent22** [comment]
The resources should be in the ".resource" directory, so it might be hidden. Please could you double-check that it's indeed missing?

**Comment by msbentley** [comment]
Oops, yes - my bad - sorry to waste your time!
