### ISSUE TITLE
Share webpage to a new notebook

### ISSUE THREAD

**Issue by YussefR** [laurent22/joplin#2230]
From Chrome for android, when a page is shared to Joplin, it shows you existing notebooks to place your page URL in. Would be nice if there was an option to create a new notebook from that menu and move the URL there right away.

This is not a huge deal because you can put the URL anywhere, open Joplin, create the notebook, and then move your URL page there. But its just a suggestion/feature request.

Thanks!

Joplin version: 1.0.312
Platform: android
OS specifcs: 6.0.1

Describe what you expected to happen:

When i'm browsing in chrome. Then i click the share button. Then i select my app as Joplin. I would see all my existing notebooks where I can put yhe URL from chrome, AND a button to create a new notebook and put the URL in it directly.

**Comment by tessus** [comment]
Feature requests go to the forum.
