### ISSUE TITLE
Clicking a note in the should select the parent notebook in the navigation tree

### ISSUE THREAD

**Issue by glowinthedark** [laurent22/joplin#2232]
## Summary

After searching notes via the search field clicking a note in the result list does not select the parent notebook in the left navigation sidebar. 

## Environment
Joplin version: any
Platform: any
OS specifics: any

## Steps To Reproduce

1. Search for notes by entering some text in the search field.
2. Click any notes in the result list.

## Expected result
The parent notebook for the clicked note is selected in the sidebar and the corresponding parent notebook in the sidebar is scrolled into view if not currently visible.

## Actual result
Clicking on a note does _not_ highlight the parent notebook and does not scroll it into view.

**Comment by tessus** [comment]
This is not a bug. User questions go to the forum.

When you clivk on the note an icon appesrd under the title: 
<img width="51" alt="image" src="https://user-images.githubusercontent.com/223439/71553882-b5f16580-29e4-11ea-9283-4425fa098f8b.png">

click on it.

**Comment by glowinthedark** [comment]
@tessus: ok, that's a reasonable workaround; but there is still a defect here: clicking the notebook name in the `📙In:` icon (on the toolbar) _does_ highlight the notebook, but it _**does not scroll it into view**_ when you have  more notebooks that can fit in the sidebar viewport.
