### ISSUE TITLE
Lack of carriage returns from editing area is inconvenient on Windows

### ISSUE THREAD

**Issue by ImportTaste** [laurent22/joplin#2234]
I'm on Windows 10 and using Joplin 1.0.175. I picked up Joplin to start keeping track of my technical notes, and it performs this job admirably.

However, some of those notes involve the use of the Windows command prompt. If I attempt to copy some code over, like this:

![image](https://user-images.githubusercontent.com/53661808/71547419-6881e380-2965-11ea-91a0-6e7e97c782be.png)

If I paste it into powershell, the lack of carriage returns on the clipboard make the lines paste in reverse order. If I paste a similar command into conhost, it won't interpret any line breaks at all.

Now, if I copy from the preview pane on the right, I will get the expect behavior in both powershell and conhost. However, I keep forgetting about this problem, and I even if I did train myself to remember this caveat, I would still find it less convenient than just copying from the edit area so I didn't have to open or keep open the preview pane.

My suggestion would be to just always use CRLF and just filter out the carriage returns on other OSes. That will produce a result that doesn't have to involve adding another setting. Doesn't even have to be retroactive.

My apologies if this issue was addressed elsewhere, I do have a tendency to miss things that are right under my nose at times.

**Comment by ImportTaste** [comment]
The issue is still active.

**Comment by ImportTaste** [comment]
This is still an issue.

**Comment by ImportTaste** [comment]
Still an issue.

**Comment by ImportTaste** [comment]
Stillll an issue.

**Comment by ImportTaste** [comment]
Still an issue.

**Comment by barro350** [comment]
FYI, using CodeMirror as the editor instead of AceEditor solves this problem.

**Comment by ImportTaste** [comment]
> FYI, using CodeMirror as the editor instead of AceEditor solves this problem.

Isn't CodeMirror still in beta? I don't really like having to bring up a mini-window for every code block, it's clunky as hell.

**Comment by ImportTaste** [comment]
Still an issue.

**Comment by ImportTaste** [comment]
No longer an issue! :)

**Comment by ImportTaste** [comment]
Well, I'm not sure when it happened, but this is a problem again.

**Comment by aaronzgh** [comment]
interesting comments on this issue......
