### ISSUE TITLE
share vim clipboard with system clipboard

### ISSUE THREAD

**Issue by fam4r** [laurent22/joplin#2241]
## Environment

Joplin version: 1.0.175
Platform: Linux
OS specifcs: Arch Linux

## Steps To Reproduce

1. Enable Vim Mode: `Ctrl+Comma` > General > Keyboard Mode: `Vim`
2. Type notes...
3. copy/cut text using typical Vi shortctus: `y`, `yy` ...
4. go to an external text input (this issue, a word processor, a terminal...) and paste
5. note that nothing happens (if you copy&paste into Joplin it works properly)

Describe what you expected to happen: expecting to paste successfully the copied text

## Logfile

```
2019-12-30 00:52:48: "Starting Clipper server on port 41184"
```

**Comment by fam4r** [comment]
up

**Comment by anihm136** [comment]
This appears to be an issue of AceEditor. From what I read, the clipboard registers have not been implemented yet, so vim mode does not have an interface to the system clipboard. It might be possible to have a workaround by overriding the keyboard shortcuts, but I'm not sure if that's something that's wanted. @PackElend could you please give some insight to this?
If I'm wrong about this being an AceEditor issue, please feel free to correct me.

**Comment by PackElend** [comment]
> @PackElend could you please give some insight to this?

sorry I'm on Windows

**Comment by fam4r** [comment]
> This appears to be an issue of AceEditor.

I am moving the discussion into their repo. I will let you know if it is really related to ace, in that case I will close this issue.

https://github.com/ajaxorg/ace/issues/2680

**Comment by abrobston** [comment]
I'm used to the `+` register for this purpose, but Ace doesn't appear to support it:

https://github.com/ajaxorg/ace/blob/5524d248e3f82a70539bc0fbcded626b1c48b7f7/lib/ace/keyboard/vim.js#L11

Register handling appears to be:

https://github.com/ajaxorg/ace/blob/5524d248e3f82a70539bc0fbcded626b1c48b7f7/lib/ace/keyboard/vim.js#L1917

**Comment by guidomz** [comment]
`y` or `yy` are not even the way to copy to system clipboard. However, even the supposedly correct `"+y` does not work. Strange that the issue has not been resolved, despite @abrobston's [pointers](https://github.com/laurent22/joplin/issues/2241#issuecomment-660663756), but closed only for being stale. Pardon my ignorance about the rules on closing issues.
