### ISSUE TITLE
When markdown exports PDF, the directory cannot be redirected

### ISSUE THREAD

**Issue by taliove** [laurent22/joplin#2243]
## Environment

Joplin version: 1.0.175
Platform: Windows
OS specifcs: Windows 10

## Steps To Reproduce

1. Open markdown note
2. Export to a PDF file
3. check the exported file, you can't jump to the specified location if you click on the item in the directory

## Other problems:
- The style of exporting PDF cannot be specified
- When exporting, the screen will jump to the bright white style, and then back to the black style I set

ps: 在小众软件看到，赶紧试用了一下，还不错，但是有一些问题不得不说。由于我的英文一般，所以我尝试用google翻译一下吧。

**Comment by laurent22** [comment]
English language is preferred here, or else include screenshots that show the problem.

**Comment by taliove** [comment]
> English language is preferred here, or else include screenshots that show the problem.

I'm sorry, but my English is just so-so.
I'll try Google translate.

**Comment by laurent22** [comment]
This should be fixed in coming versions.
