### ISSUE TITLE
Joplin 1.0.177 won't display evernote exported notes

### ISSUE THREAD

**Issue by jacksonjzu** [laurent22/joplin#2258]
## Environment

Joplin version: 1.0.177
Platform: Windows, Mac
OS specifcs:

## Steps To Reproduce

1. Import an evernote note
2. Click on the imported note
3. The preview area won't be refreshed just stuck at the previous note.
4. Clicking other non-imported notes works fine.

## Describe what you expected to happen:
Joplin should display the imported notes.

**Comment by laurent22** [comment]
Imported as HTML or as Markdown?

**Comment by jacksonjzu** [comment]
> Imported as HTML or as Markdown?

Imported as HTML, the notes have something like <en-note> at the beginning tag
