### ISSUE TITLE
Import hidden directories

### ISSUE THREAD

**Issue by pihentagy** [laurent22/joplin#2259]
## Environment

Joplin version: 1.0.175 (prod, linux)
Platform: Linux
OS specifcs: Linux Mint 19.3

## Steps To Reproduce

1. File :arrow_right:  Import :arrow_right: MD - Markdown (Directory)
2. Hidden directories (like `.git` are incuded)

Hidden directories should be excluded by default or at least asked to be included or not.

**Comment by pihentagy** [comment]
Does it worth a new option in import, or not?

**Comment by pihentagy** [comment]
:raised_eyebrow:

**Comment by pihentagy** [comment]
Still curious wheter it worths an option…

**Comment by laurent22** [comment]
Working as designed. If some of the folders should not be imported you can delete them first, so an option is not needed
