### ISSUE TITLE
Import should skip empty directories

### ISSUE THREAD

**Issue by pihentagy** [laurent22/joplin#2260]
## Environment

Joplin version: 1.0.175 (prod, linux)
Platform: Linux
OS specifcs: Linux Mint 19.3

## Steps To Reproduce

0. A directory tree with some directories having zero markdown files 
1. File :arrow_right:  Import :arrow_right: MD - Markdown (Directory)

Empty directories (directories without any "real" [^1] content) should be excluded by default or at least asked to be included or not.

[^1]: navigable content, or simply said: no markdown file in the directory or any of subdirectories

**Comment by laurent22** [comment]
The tool expects a clean dir hierarchy so you would need to remove the empty dirs if you don't want them to be imported.
