### ISSUE TITLE
Cannot find module 'lib/JoplinServerApi.js'

### ISSUE THREAD

**Issue by ThomasChaffey** [laurent22/joplin#2263]
Get this module not found error (lib/JoplinServerApi.js) with a new installation of the latest version on a freshly updated Arch Linux machine.

(Unable to launch the desktop app either).

## Environment

Joplin version: 1.0.175-2 (Arch Linux AUR package: https://aur.archlinux.org/packages/joplin/)
Platform: Arch Linux
OS specifics: Just ran a system update

## Steps To Reproduce

1. run `joplin` in a terminal emulator.

## Error message

```
internal/modules/cjs/loader.js:969
    throw err;
    ^

Error: Cannot find module 'lib/JoplinServerApi.js'
Require stack:
- /usr/share/joplin-cli/lib/SyncTargetNextcloud.js
- /usr/share/joplin-cli/lib/BaseApplication.js
- /usr/share/joplin-cli/app.js
- /usr/share/joplin-cli/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/share/joplin-cli/lib/SyncTargetNextcloud.js:9:25)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/joplin-cli/lib/SyncTargetNextcloud.js',
    '/usr/share/joplin-cli/lib/BaseApplication.js',
    '/usr/share/joplin-cli/app.js',
    '/usr/share/joplin-cli/main.js'
  ]
}```

**Comment by tessus** [comment]
@ThomasChaffey we do not provide AUR packages. Please talk to the maintainer.

**Comment by laurent22** [comment]
@tessus, I didn't try the latest version of the CLI tool, but are we sure it's actually working? I seem to remember someone else filed a similar bug?

**Comment by tessus** [comment]
@laurent22 I'm running the latest CLI (available from npm) on Linux and macOS. Both work.

I also tried git master and it runs as well w/o issues. I think `npm i` was not run properly when building the AUR package. Or a wrong node version was used.

**Comment by ThomasChaffey** [comment]
Can confirm that it works fine when installed with npm directly.  Apologies for not checking this before filing the bug.

**Comment by alfredopalhares** [comment]
Hello, maintainer of the AUR package here, this issue should be fixed in the latest release of the package.
Next time please report the bug [here](https://github.com/alfredopalhares/joplin-pkgbuild/issues)
