### ISSUE TITLE
File system sync doesn't include resources

### ISSUE THREAD

**Issue by icopp** [laurent22/joplin#2265]
## Environment

Joplin version: 1.0.176
Platform: macOS
OS specifics: 10.15.2

## Steps To Reproduce

1. Set file system sync and point it at a path that you sync yourself via other means (rsync, iCloud Documents, etc)
2. Do the same on a different computer using the synced folder
3. See that none of the attached resources are included in the sync

**Describe what you expected to happen:**

Attached resources should be included in the file system sync, such as by being in a `.resource` folder in the synced path rather than living outside of the synced path.

**Comment by laurent22** [comment]
Can't replicate. Please use the forum for support
