### ISSUE TITLE
I failed to reinstall the app,the terminal always says "failed to parse joplin"

### ISSUE THREAD

**Issue by Kingxiao** [laurent22/joplin#2269]
**Enviroment**:
OS:Archlinux
Joplin version:v1.0.177

**Bug Details**:
when I run the command:
`yay -S joplin`
the terminal always reported me that:
`failed to parse joplin: Line 30: key "pkgbase" can not occur after pkgbase or pkgname: pkgbase = joplin
`
I've tried to follow the [tips ](https://aur.archlinux.org/packages/joplin/?O=0&PP=10),edit the ".SRCINFO"  file:
`
yay -G joplin
cd joplin
nvim .SRCINFO
`
and I delete the 30th line,which is "pkgbase = joplin ",and then run:
`
makepkg -si
`
but the Joplin was still failed to install.

So how can i reinstall the app?Thank you~

⚠🚨⛔ The issue tracker is not for questions. ⛔🚨⚠

As it happens, support requests that are created as issues are likely to be closed. We want to make sure you are able to find the help you seek.

## Questions and Help

Please read the [documentation](https://joplinapp.org/) and [FAQ](https://joplinapp.org/faq/) first.

### https://discourse.joplinapp.org/

If you have still questions related to Joplin, please open a topic in the [forum](https://discourse.joplinapp.org/).
You can use your GitHub credentials to login to the forum.

## Links

- Documentation: https://joplinapp.org
- FAQ: https://joplinapp.org/faq/
- Forum: https://discourse.joplinapp.org
- How to enable end-to-end encryption: https://joplinapp.org/e2ee/
- API documentation: https://joplinapp.org/api/
- How to enable debug mode: https://joplinapp.org/debugging/

**Comment by laurent22** [comment]
We don't support yay
