### ISSUE TITLE
Adjustable font sizes

### ISSUE THREAD

**Issue by bluefuzz** [laurent22/joplin#227]
### Operating system

- [ ] Windows
- [x ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x ] Desktop
- [ ] Mobile
- [ ] Terminal

Perhaps I'm missing something, but I see no way to adjust the type size in either the preview or markdown panes. Using Joplin on a 15" MBP the default typesizes are *way* too small to read comfortably.

So consider this a feature request. Also a way to select which fonts are used would be nice. Thanks.

**Comment by laurent22** [comment]
There's a "Set application zoom percentage" on the options that will apply to the viewer and editor.

**Comment by Minh049** [comment]
I'm not sure if the "Global zoom percentage is really working. It seems like it's not doing anything. Here's the editor in 100% (default):
![image](https://user-images.githubusercontent.com/20761088/39224866-8a5f0372-4873-11e8-8d0f-286589b127a0.png)

And this in 300:
![image](https://user-images.githubusercontent.com/20761088/39224911-bf32d75e-4873-11e8-8832-f49f4c383a33.png)

Just for a test, this is 1500:
![image](https://user-images.githubusercontent.com/20761088/39224924-d130f828-4873-11e8-8b75-77084c3eb7a2.png)

I don't see any difference :/

**Comment by stefan2904** [comment]
I can confirm that this is not working on Linux (Debian).

It behaves in the way described by @Minh049 - so it does not work at all. :-(

/cc @laurent22

**Comment by apoloval** [comment]
Also confirming here not working on MacOSX, version 1.0.104.

**Comment by foxmask** [comment]
this works with Linux Debian 9
After changing the value, I did "apply" then "ok" then I restarted the app.

**Comment by jbriales** [comment]
Didn't work for me in Windows 10,
but after following foxmask steps (click "apply", restarting app at the end), it worked!

**Comment by JaPyR** [comment]
Is it possible to change font size without changing zoom level?

**Comment by subi54** [comment]
@jaPyR did you try:
```
<style>
body { font-size: 2em; }
</style>
```

**Comment by laurent22** [comment]
Custom CSS is also supported via a stylesheet - https://joplin.cozic.net/#custom-css
