### ISSUE TITLE
Could not authenticate using NextCloud

### ISSUE THREAD

**Issue by maxadamo** [laurent22/joplin#2276]
## Environment

Joplin version: 1.0.175 (Linux)
Platform: either Linux and Android
OS specifcs: either Linux and Android

## Steps To Reproduce

1. I used my owncloud URL: `https://<MYUSER>.owncube.com` and it worked from one laptop. I came to the office to configure the second laptop and it threw the error: 
**PROPFIND : Unknown error 2 (405) : Code 405**
2. I tried from Android and I got the same error 
3. to circumvent the problem (either on Linux and Android), I switched to webdav, used the URL: `https://<MYUSER>.owncube.com/remote.php/webdav/` and it started working.

**Comment by laurent22** [comment]
It's a server config error. 405 means PROPFIND method is not allowed, so it needs to be allowed.

**Comment by maxadamo** [comment]
this evening I'll try again from home (in the laptop where it worked yesterday). 
I got this nextcloud account yesterday, and I am not understanding what could have changed over night. 
The only thing that I understand now, is that the WebDav url is using a GET, while the other doesn't.

**Comment by maxadamo** [comment]
on the other side, I assume this method is used by the NextCloud client as well, but that one is working.

**Comment by maxadamo** [comment]
@laurent22 I found out, that in order to use NextCloud I still need to suffix the URL with: `/remote.php/webdav/`. 
I thought it was guessing the suffix, and the first time it did! Anyway... there is more.  

As you can see from the screenshot below, I also need to add `/Applicazioni/Joplin` (yeah, that's the Italian for `Applications`) otherwise it starts syncing all the MD files in the root directory. 

Something is wrong IMO: you shouldn't sync hundreds of files in the root directory of the cloud. 

![image](https://user-images.githubusercontent.com/1710103/72010314-e7292b80-3257-11ea-90ac-00e2326e19ec.png)

**Comment by laurent22** [comment]
This is all documented in the readme.
