### ISSUE TITLE
Checkboxes with empty labels render raw markdown

### ISSUE THREAD

**Issue by wisp3rwind** [laurent22/joplin#2278]
Pretty minor, but I think it would be preferable to render a checkbox with no text following it in the example shown in the screenshot instead of showing the raw `- [ ]`.

## Environment

Joplin version: 1.0.175
Platform: Linux
OS specifcs: Arch

## Steps To Reproduce
(see screenshot)
![Screenshot_2020-01-07_14-00-56](https://user-images.githubusercontent.com/17089248/71897903-34be6f00-3158-11ea-8e42-49c2c36ab4ad.png)

**Comment by axq** [comment]
This happens for Windows as well.  Also agree it's very minor, I can't come up with real use cases for an unlabeled box.
Joplin version: 1.0.175
Win 10 Pro 1903

**Comment by laurent22** [comment]
The definition of a checkbox is quite strict: it's `- [ ] ` followed by at least one character, otherwise it's not considered a checkbox.

**Comment by wisp3rwind** [comment]
> This happens for Windows as well. Also agree it's very minor, I can't come up with real use cases for an unlabeled box.

Well, it can occur when writing a note and being interrupted midway. I found it rather unintuitive that the checkbox did not render. If however the markdown spec is explicit about this, it's clearly the correct behaviour, though.
