### ISSUE TITLE
Handle Thai language in search engine

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2279]
The search engine uses FTS, which works only with alphabetical languages. Non-alphabetical ones, like Japanese, Korean, etc. are detected and handled in a special way - in this case we don't use FTS but do a simple plain text search (called "basic search" in Joplin).

We need to add the Thai language to that list of special cases. For that, have a look at `SearchEngine::search` to see how the switch between basic search and regular search is handled. Then add some code to detect the Thai language (in `string-utils.js`), and add it to the list of "basic search" languages.

**Comment by Runo-saduwa** [comment]
please can you assign this issue to me?, but permit me to ask questions if i am stuck because i am trying to give my first open source contribution. is this issue a Desktop issue because i am more comfortable with the desktop technologies

**Comment by laurent22** [comment]
Ok that's done @Runo-saduwa. This change is on code shared by desktop, mobile and cli but you only need to test on one platform, so just desktop is fine.

**Comment by Runo-saduwa** [comment]
Please i dont understand what you mean by `SearchEngine::search`
where can i find this?

**Comment by Runo-saduwa** [comment]
@laurent22 , sorry for bothering you, but i'm a bit lost, i need some guide on how to implement this.

**Comment by laurent22** [comment]
@Runo-saduwa, I missed that it had already been implemented in this pull request so it's done already: https://github.com/laurent22/joplin/pull/2387 If you'd like I can assign another one to you, just let me know which one.

**Comment by Runo-saduwa** [comment]
Ok, Please assign this to me, thanks(#2383)[https://github.com/laurent22/joplin/issues/2383]
