### ISSUE TITLE
Add more info to the "Unknown profile version" dialog box

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2280]
It should include:

- App version number
- Profile version that the client expects
- Profile version of database.sqlite

Also add profile version to About box in desktop client.

**Comment by tessus** [comment]
I'd like to add a `Copy` button to the About dialog box to copy all necessary info to the clipboard. Maybe people stop pasting screenshots of the About box then ;-)
What do you think? Or no button, and we copy the info automatically to the clipboard  when opening the About dialog.
