### ISSUE TITLE
Line break in table cells

### ISSUE THREAD

**Issue by jogi4github** [laurent22/joplin#229]
### Operating system

- [x] Windows
- [ ] macOS
- [x] Linux
- [x] Android
- [ ] iOS

### Application

- [x] Desktop
- [x] Mobile
- [x] Terminal

I love to use tables in my notes. It looks like joplin/md language does not support linefeeds in cells. My Evernote imports ended up loosing all my linefeeds in table cells. Regarding [this article](https://github.github.com/gfm/#hard-line-break) a \ should break a line, but this seems to not work in table cells. Also a <br/> does not work. Any ideas how I can keep my line breaks in cells?

**Comment by laurent22** [comment]
I guess support for <br> would be the way to go. Do you have a sample ENEX file to test with?

**Comment by laurent22** [comment]
Possibly fixed in eca500880dd1b7a448b7d91a184eb8f43bb187c7 Release [65](https://github.com/laurent22/joplin/releases/tag/v1.0.65)

**Comment by jogi4github** [comment]
Attached you can find an example enex file.

[Test.zip](https://github.com/laurent22/joplin/files/1734121/Test.zip)

**Comment by jogi4github** [comment]
Great yes it working with Release 65 - by the way thanks for the amazing app :-)

**Comment by laurent22** [comment]
Good to know it's working. I'm trying to get the Enex parser as reliable as possible, so if you notice anything else strange feel free to post again.
