### ISSUE TITLE
Right-click to assign a note to a notebook

### ISSUE THREAD

**Issue by dbogdanov** [laurent22/joplin#2296]
Add a new option to assign a notebook for a note or multiple notes with a right-click.

Currently, the right-click leads to a popup menu which already contains "Add or remove tags". New option "Move to a notebook" would be very useful. 

Like "Add or remove tags", it would open a dialog where the user can select the notebook from a dropdown list with typeahed.

The problem with a current way to assign a notebook is that it can be only done by drag-n-drop. This is undesirable in some cases, such as when having too many notebooks as it becomes very tiring to scroll through the list of notebooks and then drag-n-drop the notes. 

## Environment
Joplin version:  1.0.175 
Platform: MacOS, Linux, Windows

**Comment by tessus** [comment]
Not a bad idea. Please open a topic on the forum to discuss the feature.

**Comment by dbogdanov** [comment]
Done: https://discourse.joplinapp.org/t/right-click-to-assign-a-note-to-a-notebook/5183

**Comment by tessus** [comment]
@dbogdanov the feature request was accepted. Now we only have to find someone to implement it...

**Comment by CaptainNick** [comment]
@laurent22 I would like to work on this issue.

**Comment by laurent22** [comment]
That's great @CaptainNick! I've assigned the issue to you and if you need some help let us know.

**Comment by tessus** [comment]
@CaptainNick please make sure that you also include a live search field in the popup, otherwise it will be very hard to scroll through a myriad of folders. Imagine 100-200 nested folders. Scrolling would be a mess and time consuming matter.

**Comment by laurent22** [comment]
@tessus, it's already in the spec

> dropdown list with typeahed

**Comment by tessus** [comment]
@laurent22 ahh, the last time I read the first comment that part was not there. This suggestion came only later in the forum.

**Comment by coderrsid** [comment]
Hey @laurent22. I would like to fix this issue. Is @CaptainNick is working on it?

**Comment by laurent22** [comment]
@CaptainNick, are you still working on it, or can I assign it to @coderrsid?

**Comment by CaptainNick** [comment]
@laurent22 yes I'm working on this. I'm getting hold of the codebase. Can you please allow 2 more days?

**Comment by laurent22** [comment]
@CaptainNick, sure we can wait, no problem.

**Comment by CaptainNick** [comment]
@laurent22 Looks like I might need more time. Kindly assign this issue to @coderrsid . I'll take up different issue later. Thank you. :)

**Comment by laurent22** [comment]
Ok thanks for letting me know. @coderrsid, feel free to go ahead and work on it then.

**Comment by coderrsid** [comment]
Sure, @laurent22

**Comment by tessus** [comment]
@coderrsid any update? It would be nice to keep us apprised.

**Comment by coderrsid** [comment]
Hey @tessus Sorry i couldn't reply although i am working on this issue instead https://github.com/laurent22/joplin/issues/2467

**Comment by coderrsid** [comment]
Hey @tessus I was just trying to fix this issue. I have one issue why there is two App.js, one in ElectronClient/App  and other in  app/dist/mac/.../Resources/app/app.js. Do i have to make changes to them both as they look same as my changes is not shown in the app.

**Comment by tessus** [comment]
Actually, there is no app directory anymore. If you pull the latest git master, you will see that.

If you are working on a local branch, create a new branch from your branch and do a `git rebase master`.
The file `app.js` is now in the directory `ElectronClient`.
The dist directory will be created when you create a release, so for testing this is not even necessary. Just do a `npm start run` in the `ElectronClient` directory.

**Comment by tessus** [comment]
The BUILD.md has been updated to reflect the changes to the build process.

**Comment by coderrsid** [comment]
Yeah i just saw that. Thanks @tessus

**Comment by coderrsid** [comment]
Hey @tessus I've updated my forked master branch but when i run it now with `npm start run`. It shows white screen in the app.
![image](https://user-images.githubusercontent.com/35633575/75088069-3ad4a780-556e-11ea-9560-583ee052fb22.png)

**Comment by tessus** [comment]
You probably didn't run `npm i` in the root directory of the project. (one up from ElectronClient)

**Comment by coderrsid** [comment]
I did. 
![image](https://user-images.githubusercontent.com/35633575/75088114-f39ae680-556e-11ea-9a1d-7abcecc2c0c1.png)

**Comment by tessus** [comment]
No, you did it in the `ElectronClient`. Do a `cd ..` and run `npm i`.

**Comment by coderrsid** [comment]
Ohh thanks. Now it's working. Now i have a query related to issue.
As only drag and drop is the only option to move notes to diff. notebooks. Here in `Sidebar.js` which of these three functions defines the instance of when i drag and drop a folder or note on another folder?
![image](https://user-images.githubusercontent.com/35633575/75088023-7e7ae180-556d-11ea-8873-c08caf54bfa0.png)

**Comment by tessus** [comment]
I'm not sure. I think it's the Drop function. I haven't really worked with this part of the code.

But @laurent22 can tell you for sure. There should be a moveNote function or something. You don't need the drag and drop functions.

**Comment by coderrsid** [comment]
No i just need to see how drag and drop is assigning the folder to the note so when i make a prompt to select the folder i can do the same. Thanks for calling @laurent22

**Comment by tessus** [comment]
`await Note.moveToFolder(noteId, folderId);`

**Comment by coderrsid** [comment]
Thanks @tessus for the information. Although you can assign me this, i am already working on this.

**Comment by coderrsid** [comment]
Thanks @tessus for the help. I am working on this issue. I'll reach out if i got any more query.
