### ISSUE TITLE
Strange Alt-button behaviour

### ISSUE THREAD

**Issue by m-angelov** [laurent22/joplin#2298]
I'm using two keyboard layouts and I switch between them with Alt+Shift. When I switch between layouts when editing a note, the editor gets stuck in the "Alt" mode - the first letter of the options in the menu get underlined. So I either have to press the Alt button again, or to click in the editing field to return the focus to the editor.

While trying to write this explanation better, I've found that actually "Alt" mode is not working - if I press Alt, the menu gets underlined, as it should be, but pressing "F", "E", "V", etc., doesn't activate the menu (this happens in both layouts). 

## Environment

Joplin version: 1.0.177 AppImage
Platform: Linux
OS specifcs: Arch with kernel 5.4.10, KDE Plasma 5.17.5

## Steps To Reproduce

1. Press Alt
2. Menu should be accessible by keyboard, but isn't

Describe what you expected to happen:
I expect the menu to be accessible when Alt is pressed and to switch keyboard layouts seamlessly with Alt-Shift.

## Logfile

That's the only thing that appears in the debugging window, and it's there from the beginning. When I use the keyboard there are no new things appearing.

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(ConfigScreenComponent)
/tmp/.mount_Joplin5e…evelopment.js:12357 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(ConfigScreenComponent)
/tmp/.mount_Joplin5e…NoteText.min.js:920 webview_domReady 
Connect

**Comment by AddictArts** [comment]
Joplin version: 1.0.177 AppImage on Windows doesn't exhibit this bug.
