### ISSUE TITLE
[Feature Request] Android app does not support alarms/reminders when creating a to-do item

### ISSUE THREAD

**Issue by rerpha** [laurent22/joplin#23]
I would like to be able to set up a to-do item on the android app (unsure if ios app is the same) and allow reminders/alarms like the desktop application.

**Comment by laurent22** [comment]
Yes this is actually already done, I just need to release the new Android and iOS versions on the app stores.

**Comment by igorrosenberg** [comment]
+1

**Comment by laurent22** [comment]
This has been released on the app stores now.
