### ISSUE TITLE
Android App does not show content of note

### ISSUE THREAD

**Issue by DrAxelbauer** [laurent22/joplin#2300]
I have installed Joplin and synced my notes via Nextcloud with my Android device. All the notes are synced and decrypted on the device. Problem is, that the content of the notes is not shown when I open them on my Android Device. I only see the name of the note and an error:
"Can't find variable: imageRegex"

If i edit the note on the android device the text is shown in markup. So the content of the note is synced and there but something is rotten with regard to the view. 

Besides: On my Linux Desktop Joplin is working like a charm!
Besides #2: The default notes of Joplin are showing up in the correct way. The error only occurs to the notes of my synced notebooks. 

## Environment

Joplin version: 1.0.315
Platform: Android 7.0 / Muiu 10.1 
Device: Xiaomi Mi-4c

## Steps To Reproduce

1. Open any synced and decrypted note.
[syncReport-1579000330776.txt](https://github.com/laurent22/joplin/files/4058809/syncReport-1579000330776.txt)

## Describe what you expected to happen:
Open Note and Show content

**Comment by laurent22** [comment]
This is fixed and will be in the next release.

**Comment by DrAxelbauer** [comment]
perfect! When will it be out?
