### ISSUE TITLE
Remove file system sync option on iOS

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2301]
It doesn't work but appears in the list of sync target.

**Comment by bedwardly-down** [comment]
By the way, this also shows up on my Samsung Galaxy S9+, so it's definitely not an iOS specific bug.

**Comment by laurent22** [comment]
> This also shows up on my Samsung Galaxy S9+, so it's definitely not an iOS specific bug.

But it's supported on Android so this fine.
