### ISSUE TITLE
MacOS top bar icon is invisible

### ISSUE THREAD

**Issue by andradei** [laurent22/joplin#2303]
The icon on the top bar of MacOS is invisible in light mode (you might have to click on it once for it to disappear).

## Environment

Joplin version: Joplin 1.0.175 (prod, darwin)
Platform: MacOS
OS specifcs: 10.15.2 (Catalina)

## Steps To Reproduce

1. Start machine :D
2. Start Joplin and (don't) see the icon at the top. But if you click there it suddenly appears (and turn invisible again when it loses focus)

Icon is invisible:
<img width="432" alt="Screen Shot 2020-01-15 at 10 11 44 AM" src="https://user-images.githubusercontent.com/2653546/72455131-70bc8a00-377f-11ea-8a05-c4ff419fb434.png">

But appears when clicked:
<img width="432" alt="Screen Shot 2020-01-15 at 10 12 54 AM" src="https://user-images.githubusercontent.com/2653546/72455199-99dd1a80-377f-11ea-9cbc-e309cd341154.png">

Describe what you expected to happen:
I expect an icon that isn't invisible in light mode (haven't tested dark mode).

**Comment by tessus** [comment]
Hmm, this makes no sense. The icon on macOS looks like this no matter of dark or light mode:

<img width="21" alt="image" src="https://user-images.githubusercontent.com/223439/72498663-e6673b00-37fd-11ea-86ba-f01d39c4600d.png">

**Comment by laurent22** [comment]
I can't replicate this either but I don't have Catalina. For me it's black in light mode and white in dark mode. The icon is a template so the OS should change its colour automatically based on the theme.

**Comment by andradei** [comment]
I had a suspicion it might be a Catalina problem. If I find more hints I'll post them here.

**Comment by andradei** [comment]
Well... If I switch to Dark Theme it show up, then when I switch back to Light Theme is starts working. The issue seems to be only on Catalina. I'm closing this as there's nothing wrong with the app.
