### ISSUE TITLE
Synchronization with Nextcloud not possible when using F2A

### ISSUE THREAD

**Issue by wsw70** [laurent22/joplin#2305]
## Environment

Joplin version: 1.0.312
Platform: Android 9 (likely to be the same everywhere)

## Steps To Reproduce

1. Set up 2FA authentication on Nextcloud (TOTP for instance)
2. Try to synchronize from Joplin

Describe what you expected to happen:

Several possibilities:
- either being prompted for a TOTP and set up some kind of long-lived auth token
- or have the ability to use an application-specific password (generated on nextcloud)

## What happened

The connection failed with 

    PROPFIND : Unknown error 2 (405) : Code 405

Note: the synchronization works fine without the 2FA.

**Comment by laurent22** [comment]
> or have the ability to use an application-specific password (generated on nextcloud)

As far as I know you can already do that.

**Comment by wsw70** [comment]
Ah, for some reason the first per-app password I tried would not go though.

**Everything works fine** - I confirm that F2A on Nextcloud + application-specific password work for Joplin synchronization. Thanks!
