### ISSUE TITLE
Ctrl-F search in a note always changes it to a dual-pane edit/view layout

### ISSUE THREAD

**Issue by dbogdanov** [laurent22/joplin#2308]
Ctrl-F for search in a note always changes its layout to dual-pane edit/view.

This can be annoying. For example when reading a note in view mode and willing to search for some text, I do not necessarily want to see markdown at all. Currently one has to press Ctrl-L to restore view layout every time after searching in a note. 

## Environment

Joplin version: 1.0.175
Platform: Linux, macOS

## Steps To Reproduce

1. Open a note in a single-pane layout (either view or edit)
2. Ctrl-F to find for some text
3. Layout switches to a dual-pane layout  (edit and view)

Describe what you expected to happen: The original layout should be kept when visualizing highlighted search results.

**Comment by tessus** [comment]
I can't reproduce this on macOS. The shortcut on macOS is `Cmd+F`.

**Comment by dbogdanov** [comment]
I've double-checked and in my case, I have this issue on macOS too.

**Comment by tessus** [comment]
Ah, ok. My bad. I misread the issue. Yes, I can see the same behavior.

However, this might have been intended. @laurent22 will have to decide, if this is a bug.

**Comment by AddictArts** [comment]
If it is a bug, I'd be happy to supply a pull request for NoteText.jsx to fix it. I was able to reproduce on Windows 10. Thanks

**Comment by dbogdanov** [comment]
> However, this might have been intended. @laurent22 will have to decide, if this is a bug.

If it has been intended, perhaps this behavior may be configurable.

**Comment by mic704b** [comment]
(Bump)

> Ctrl-F "search in note" always switches layout to dual-pane edit/view.

Hi @laurent22, is this intended behaviour, or can it be modified to not change layouts?

**Comment by anihm136** [comment]
> Ctrl-F for search in a note always changes its layout to dual-pane edit/view.

If I'm not mistaken, this is done because the matches are highlighted only in the view pane, so searching in editor-only mode would be futile. However, if this is the case, "search in note" could be enabled in view-only mode also without changing the layout.

**Comment by Rahulm2310** [comment]
Why don't we simply change the layout as soon as search input becomes empty ?

**Comment by dbogdanov** [comment]
This is not an issue anymore with the new WYSIWYG view.
