### ISSUE TITLE
Cyrillic letters shows using non-monospace font in the editor

### ISSUE THREAD

**Issue by evgeny-elkin** [laurent22/joplin#2309]
Then typing a text using russian letters, you get a wrong font and wrong cursor position.

![Screenshot from 2020-01-17 23-10-09](https://user-images.githubusercontent.com/60013368/72636597-2d316e00-3981-11ea-81fa-5a72ce687008.png)

## Environment

Joplin version: 1.0.177
Platform: Manjaro Linux Gnome 3.34.2
OS specifcs:

## Steps To Reproduce

1. Install Joplin on Manjaro Gnome.
2. Try to type in the editor using cyrillic (e.g. Russian) letters

Describe what you expected to happen:

Changes in app to fix wrong font face in the editor.

## Logfile
No errors in log.txt

**Comment by yuichi8** [comment]
The square letter (space?) appear when start typing Japanese.

![スクリーンショット 2020-01-22 9 49 57](https://user-images.githubusercontent.com/10018337/72857469-07012a80-3d01-11ea-90ae-21372404048f.png)

Joplin 1.0.178 (prod, darwin)
Revision: 953aa5d (HEAD)

**Comment by Sparsa** [comment]
Hi,
I am also facing the same problem when typing in Bengali(India) script, the cursor is going beyond the text. Joplin 1.0.179(prod. linux).
![image](https://user-images.githubusercontent.com/1224636/74080498-9f6e0d80-4a6a-11ea-9a29-c0fc411fd8aa.png)

**Comment by toftul** [comment]
Same here. Any updates?

**Comment by laurent22** [comment]
The text editor only supports monospace fonts. So you'll need to set that monospace font in the settings.

**Comment by yuichi8** [comment]
I didn't have this problem at the previous version (e.g. v1.0.175).
I'm using same monospace font.
