### ISSUE TITLE
Flatpak Release

### ISSUE THREAD

**Issue by crouthamela** [laurent22/joplin#231]
It would be great to get Joplin as a Flatpak for us Linux users. It's already released as an AppImage, so I don't see how there would be a technical issue. But if you release via Flatpak, and post it to Flathub (and include an [AppStream file](https://github.com/ximion/appstream)), it will show up in software stores such as GNOME Software and KDE Discover. 

### Operating system

- [ ] Windows
- [ ] macOS
- [ X] Linux
- [ ] Android
- [ ] iOS

### Application

- [ X] Desktop
- [ ] Mobile
- [ ] Terminal

**Comment by laurent22** [comment]
There's currently no plan for another type of release unless someone wants to do it independently based on the AppImage.
