### ISSUE TITLE
Android crash when attaching photo

### ISSUE THREAD

**Issue by mgrandi** [laurent22/joplin#2310]
so i noticed that attaching photos seems to crash joplin now, i don't have a way of getting a debug log but i did click 'submit feedback' with this github issue number in the feedback, maybe you can find the full report in wherever those get sent?

I have screenshots of the stack trace though:

![Screenshot_20200117-130458](https://user-images.githubusercontent.com/802786/72642942-c6816580-392a-11ea-98f2-8816a67a08b8.png)

![Screenshot_20200117-130505](https://user-images.githubusercontent.com/802786/72642985-e1ec7080-392a-11ea-8efa-adbc2bcc4ee3.png)

## Environment
Joplin version: 1.0.312
Platform: android 10 latest patch
OS specifcs: 

## Steps To Reproduce

1. select attach
2. select attach already existing photo
3. browse for photo in app
4. joplin crashes

Describe what you expected to happen:

to not crash and attach the photo

**Comment by tessus** [comment]
I can't reproduce this. I'm using the same Joplin version and also Android 10.

How big is the image?

**Comment by mgrandi** [comment]
the image is a screenshot so it should just be like <500 kb

i don't know much about android development, could this be caused by the photo gallery app i'm using to pick the image?

**Comment by mgrandi** [comment]
ok yeah, i used "photos" (the google app) instead of the other app i was using and that seems to work, i guess this is a bug report for the other gallery app i'm using o.o

i'll close this!
