### ISSUE TITLE
Undo does not work in note titles

### ISSUE THREAD

**Issue by dbogdanov** [laurent22/joplin#2315]
It is impossible to undo changes in note titles. The undo behavior on CMD + Z  should be the same as in the note body. This is a copy of #969 which was auto-closed due to inactivity. 

The missing undo is further aggravated by the fact that the note search field and note title fields are located very close to each other and they look similar, so it is easy to mistaken one for another (related to #915). This happened to me a few times already, and I lost my original note titles.

## Environment

Joplin version:
Platform: macOS
OS specifcs: macOS 10.13.6

## Steps To Reproduce

1. Click on the note title
2. Edit
3. Undo with CMD+Z does not work

Describe what you expected to happen:
Undo with CMD+Z should work just as it does in the note body.

**Comment by mic704b** [comment]
FWIW I tried with desktop on Linux using Ctrl-Z and couldn't reproduce the problem. It worked even when I changed focus and returned. Perhaps platform specific.

**Comment by dbogdanov** [comment]
I've checked this and indeed no issue on Linux, only macOS

**Comment by dbogdanov** [comment]
Not stale

**Comment by dbogdanov** [comment]
Isn't that an issue for anybody else on MacOS?
