### ISSUE TITLE
Android: no file picker for using the sync option in 'filesystem' mode

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [laurent22/joplin#2316]
## Environment

Joplin version: well, there seems to be no 'about' menu . . but: 'last updated 8 December 2019'.
Platform: Android
OS specifcs: Lollipop.

## Steps To Reproduce

1. Hamburger menu -> Configuration -> Syncronisation -> Target: file system,
2. The, 'Directory to synchronise with'  field opens no file picker.

Describe what you expected to happen:

There should be a file picker, especially since the two file managers that I have installed seem not to offer a way to copy the full path of a folder to the clipboard.

## Logfile

I don't know how to pull a log file of my phone, I'm afraid.

**Comment by tessus** [comment]
This is not a bug, but a feature request. Please open a topic in the forum to discuss this further.

**Comment by LinuxOnTheDesktop** [comment]
It is known, and perhaps even fully intended, that there is no file picker? Goodness! I would join the forum, only, because of this and other problems, I am abandoning Joplin,

**Comment by laurent22** [comment]
File system sync is available but has always been an advanced feature (initially I didn't want to make it available, it was just for testing), and it's possible it will stop working some day as Google locks down Android more and more.

For these reasons, this is a relatively bare feature, and it's unlikely we'll invest time on improving the UX.
