### ISSUE TITLE
single method to retrieve version number

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#2317]
There should be a single method to retrieve version number on all platforms. 

The method could be added to `shim.js`, then version number would be retrieved from
- from package-info on desktop
- package.json on CLI 
- version package on RN

**Comment by mic704b** [comment]
> version package on RN

Is this [react-native-version](https://www.npmjs.com/package/react-native-version) ?

**Comment by tessus** [comment]
@mic704b no, it's [react-native-version-info](https://www.npmjs.com/package/react-native-version-info) and we are already using it.

**Comment by tessus** [comment]
added via #2355
