### ISSUE TITLE
Wrong Linux filename breaks update script

### ISSUE THREAD

**Issue by akosma** [laurent22/joplin#2319]
## Environment

Joplin version: 1.0.178
Platform: Linux
OS specifcs:

## Steps To Reproduce

1. Run the Linux update script 
`wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash`
2. The script fails with "ERROR 404: Not Found."

The reason is that the AppImage file of the latest release does not contain the `x86_64` part in the filename: compare the file in version 1.0.178 to that of 1.0.175

https://github.com/laurent22/joplin/releases/tag/v1.0.178
https://github.com/laurent22/joplin/releases/tag/v1.0.175

Describe what you expected to happen:
The application should update as usual.

**Comment by Jairjua** [comment]
in the same file there are a problem with print function: it removes initial spaces making print wrong texts.

**Comment by joshjavier** [comment]
The fix https://github.com/doc75/joplin/commit/815766373c305a32c7b51012c28fa1453116d1bf is not yet merged to the master branch, so I tried the workaround as mentioned in https://github.com/laurent22/joplin/issues/2328#issuecomment-576464341. Works without any issues.

**Comment by tessus** [comment]
fixed in 1a1a1d3841b22e6a71e37c2113d458ffee0d251a
