### ISSUE TITLE
iOS sync troubles

### ISSUE THREAD

**Issue by fmrtn** [laurent22/joplin#232]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS 10.3.3 Joplin 1.0.12

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

![img_20180218_130157_5350](https://user-images.githubusercontent.com/10997189/36352989-c6926230-14c0-11e8-9a31-deb0815db268.PNG)

I can't sync on iOS. Seems the problem starts when I modified a note on my iPhone it stops update content but in left panel show thst syncronise was completed.

Yesterday I had the same problem, I remove and reinstall de app on the iPhone and works fine until I modified a note in the iPhone. All others devices syncs well (and of course they don't see the changes made on iPhone).

**Comment by laurent22** [comment]
Which sync target is it (OneDrive, Nextcloud, WebDAV...)? Is the URL http or https? If it's WebDAV/Nextcloud does it work when you click on "Check sync config" from the config screen?

**Comment by fmrtn** [comment]
Seafile (WebDAV)
It's https of course
When I check sync in configuration, show *Success!*
When I force synchronize in left panel, show *Completed:*

**Comment by laurent22** [comment]
Do you have access to the Seafile server logs and can you see what request is creating this error? Unfortunately I forgot to add the request info on the app log and without this it's going to be hard to fix it. My guess is that this error can be skipped by the synchronizer but can't be sure without knowing the request.

**Comment by laurent22** [comment]
Does the file 63e1f478fb9e4b8abd4f0fd3cee7e056.md exist on the server (I assume it does not but just want to be sure)?

**Comment by fmrtn** [comment]
Yes, exists and is the note that I modified on iPhone.

**Comment by laurent22** [comment]
Ok it's a bit of a tricky issue. It seems the network lib is kind of wrong to send an If-None-Match header for a PROPFIND request (it should only be for GET or HEAD), but Seafile is also being too pedantic to send a 412 error as a response.

At the app level I got it working on your test account by setting If-None-Match to a blank string, but I'll need to think it through a bit more as I don't want to break other WebDAV servers.

**Comment by laurent22** [comment]
@fmrtn, the latest iOS version should have a fixed for this, do you know if it's working now?

**Comment by fmrtn** [comment]
Seems fixed.

Thank you.
