### ISSUE TITLE
Note History shows error messages

### ISSUE THREAD

**Issue by Perkolator** [laurent22/joplin#2325]
## Environment

Joplin version: 1.0.178
Platform: Windows 
OS specifics: Windows 8.1(.1)

## Steps To Reproduce

1. Open any note that has note revisions.
2. Go to note history (Note properties->Previous versions of this note)

= Latest revision is shown, but also "undefined" text on top of the note text.

3. Select any other revision from the drop-down box.

= That revision is shown, but also 1 new "undefined" text row is added on top of the note text. Every time another revision is selected, 1 new "undefined" text row is added to the note view panel. Didn't notice this happening with earlier versions.

**Comment by laurent22** [comment]
Fixed in b6e0df57eb0dadbd889e6f164fab1494052b5c42
