### ISSUE TITLE
Feature Request: Sort/Reorder notes and notebooks manually

### ISSUE THREAD

**Issue by vertigo220** [laurent22/joplin#2326]
In the Android app, I'd like to be able to sort, preferably by drag-and-drop, the notes and notebooks.

**Comment by tessus** [comment]
Feuture request -> forum please.

Also, there's a issue already open on this topic.

**Comment by vertigo220** [comment]
I wasn't sure, since the contributing guidelines say to use the forum but the website says to use GitHub for requests. Also, the only open issue I could find was for desktop.

**Comment by tessus** [comment]
We use the tracker only for reproducible bugs and accepted feature requests.
The forum is a better place to discuss and bring up new ideas, since more people are reading the forum and others might even improve upon your idea.

Can you please point me to the text on the web site, so that I can change it accordingly?

**Comment by vertigo220** [comment]
"Community" section of the main page says the following:

For general discussion about Joplin, user support, software development questions, and **to discuss new features**, go to the Joplin Forum. It is possible to login with your GitHub account.

For bug reports and **feature requests**, go to the GitHub Issue Tracker.

This makes it sound like the intention is to propose new features on GitHub and discuss newly added ones on the forum.

Also, when posting on the forum, is it still preferred to make a separate post for each request or is it ok to just make one post with several? And it says it's possible to login with a GitHub account, but I don't see that option.

**Comment by tessus** [comment]
Thanks for the info. I will change it when I get to it.
