### ISSUE TITLE
Pressing back while showing sort order popup exits app

### ISSUE THREAD

**Issue by vertigo220** [laurent22/joplin#2327]
## Environment

Joplin version: 1.0.312
Platform: Android
OS specifcs: 8.0.0

## Steps To Reproduce

1. Open notebook and tap sort order icon in top-right corner
2. Press back key

Describe what you expected to happen:

Sort order window should close, but instead it backs out of the app.

**Comment by axq** [comment]
Reproduces on Android 9 as well.

**Comment by ykabusalah** [comment]
Can I try tackling this?

**Comment by axq** [comment]
No permission needed, just make sure you follow the guidelines for pull requests.  If this requires a change that is big or potentially controversial, you can always describe your proposed solution to get feedback.

**Comment by rossorp** [comment]
Still an issue with v1.0.329 on Android 9
