### ISSUE TITLE
Updating to 1.0.178 on Linux using the script fails

### ISSUE THREAD

**Issue by jmcastagnetto** [laurent22/joplin#2328]
According to the documentation, using:

```
wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash
``` 

should upgrade an existing install of Joplin, but with today's release, it fails.

## Environment

Joplin version: (wanted) latest
Platform: Ubuntu Linux 18.04 LTS
OS specifcs: Ubuntu Linux 18.04 LTS

## Steps To Reproduce

1. Run: wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash
2. Get a 404 error, and the old version is gone

```
$ ls -l ~/.joplin/Joplin.AppImage
-rw-rw-r-- 1 jmcastagnetto jmcastagnetto 0 Jan 20 18:40 Joplin.AppImage
```

Describe what you expected to happen:

- I'd expected to have the latest version of Joplin (1.0.178)

## What is the problem?

The error that is produced gives a hint about the solution to this issue:

**ERROR**

```
wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash
--2020-01-20 18:40:50--  https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.128.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4676 (4.6K) [text/plain]
Saving to: ‘STDOUT’

-                               100%[======================================================>]   4.57K  --.-KB/s    in 0s      

2020-01-20 18:40:50 (36.8 MB/s) - written to stdout [4676/4676]

_ _ _
| | ___ _ __ | (_)_ __
_ | |/ _ \| '_ \| | | '_ \
| |_| | (_) | |_) | | | | | |
\___/ \___/| .__/|_|_|_| |_|
|_|

Linux Installer and Updater
Downloading Joplin...
https://github.com/laurent22/joplin/releases/download/v1.0.178/Joplin-1.0.178-x86_64.AppImage:
2020-01-20 18:40:52 ERROR 404: Not Found.
```

The released AppImage is at: https://github.com/laurent22/joplin/releases/download/v1.0.178/Joplin-1.0.178.AppImage (missing "-x86_64")

**Comment by jmcastagnetto** [comment]
Workaround:

```
$ wget https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh
```

Remove the string "-x86.64" in line 69 
https://github.com/laurent22/joplin/blob/953aa5d0b5d53723402659f98b54c43cc1c8c4d0/Joplin_install_and_update.sh#L69

Run:

$ bash Joplin_install_and_update.sh

$ ~/.joplin/Joplin.AppImage

**Comment by dpoulton-github** [comment]
@jmcastagnetto 

For your information there appears to be a previous issue submitted re this and it looks like it has been actioned.

https://github.com/laurent22/joplin/issues/2319#issue-552469998

**Comment by jmcastagnetto** [comment]
Same issue as #2319, as mentioned by @dpoulton-github.
Closing this issue.
