### ISSUE TITLE
[Feature Request] Show version on mobile apps

### ISSUE THREAD

**Issue by fmrtn** [laurent22/joplin#233]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [x] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

Show version for troubleshooting. For instance in configuration screen.

**Comment by Jumanjii** [comment]
Nice job, 
Maybe this issue could be closed :-)

**Comment by tessus** [comment]
Yep, this can be closed. ;-)
