### ISSUE TITLE
Importing JEX file appends (X) on notebooks with same name

### ISSUE THREAD

**Issue by JunkyardCat** [laurent22/joplin#2331]
when importing a JEX file that has multiple notebook and subnotebook with same name. Joplin seems to append (n) at the end of the name. (where n increases in number.)

example
Notebook structure before Importing
ToDo
-->Cook
Market
-->ToDo
Science
-->ToDo

After importing the above joplin files to  new PC
ToDo
-->Cook
Market
-->ToDo (1)
Science
-->ToDo (2)

## Environment

Joplin version: 1.0.178
Platform: WIndows
OS specifcs: Win7/10

## Steps To Reproduce

1. create notebook and subnotebook which has identical name on one pc
2. export the whole notebook/notes in a JEX file
3. go to another pc which has joplin
4. import JEX file

Describe what you expected to happen:
after importing it should retain the name without the appended (n) as shown above

**Comment by JunkyardCat** [comment]
any updates on this?

**Comment by bedwardly-down** [comment]
@JunkyardCat, I don't have an update on this fix but at least can reproduce the bug. I posted a screenshot, some testing info, and a simple Jex file that can be used to reproduce it on [the forums](https://discourse.joplinapp.org/t/issue-importing-notebooks-created-with-parenthesis-and-a-number-inside-it/4697/9?u=bedwardly-down).

**Comment by JunkyardCat** [comment]
hi is anyone working on this?

**Comment by Rishgod** [comment]
@JunkyardCat it does not look like it, but I'll take a look and see what I can do :)

**Comment by JunkyardCat** [comment]
@Rishabh-malhotraa 

were you able to take a look at it?
