### ISSUE TITLE
e2ee instructions don't allow creation of a single master key with MacOS+iOS

### ISSUE THREAD

**Issue by jmesmon** [laurent22/joplin#2335]
## Environment

| Joplin version | 10.0.40 | 1.0.178
| Platform | iOS | macOS | 

## Steps To Reproduce

1. With e2ee disabled on both devices (but both connected to sync), start enabling e2ee on macOS by executing instructions 1,2,3, and 4 from https://joplinapp.org/e2ee/
2. Begin instruction 5: syncronize on the iOS device
3. Note that you are not prompted to enter a master key password
4. In the encryption menu, note that the new master key is listed but requires a password
5. enter a password for the new master key
6. note that encryption is not marked as enabled for the iOS device ("Encryption is: Disabled", option to enable encryption exists, etc).

Describe what you expected to happen:

Instructions from  https://joplinapp.org/e2ee/ currently:
 - imply that I'll be prompted for the master key password on sync. I was not
 - indicate that entering the password for the other master key automatically enables encryption. The UI does not indicate it is enabled.
 - state that by following them one can end up with a single master key. I was unable to find a way given a "macOS -> iOS" e2ee enable sequence. The same appears true of "iOS -> macOS". 

Plausible that the instructions just need fixing

**Comment by bedwardly-down** [comment]
On your iOS device, have you uninstalled Joplin and then reinstalled it so that you've cleared all configs? Also, do you only have one Master Key under encryption settings on your Mac? You definitely are on the right track setting your Master Key on your Mac.

**Comment by dpoulton-github** [comment]
The password you create at step 2 is the password you enter at step 5.
