### ISSUE TITLE
Snap package

### ISSUE THREAD

**Issue by kornava** [laurent22/joplin#2342]
Hello,
How about a snap package for Joplin 
I think they have a good support for electron based desktop apps
https://snapcraft.io/docs/electron-apps
AppImage is really painful, even with the provided shell script its always better to have an automated solution for updates

How about an apt repository for debian users?

**Comment by laurent22** [comment]
Please use the forum

**Comment by nunesgh** [comment]
Why was this issue marked as invalid? It is similar to #738, just regarding another way to distribute software for Linux users.

Also, I would prefer a snap package rather than a flatpack one, since it is natively supported by Ubuntu and its derivative distributions.
