### ISSUE TITLE
Abbreviation Plugin Showing Blank On Multiple Platforms

### ISSUE THREAD

**Issue by bedwardly-down** [laurent22/joplin#2344]
## Environment

Joplin version: 1.0.178 (Desktop), 10.0.40 (iOS), 1.0.312 (Android)
Platform: Linux, iOS, Android
OS specifcs: Artix Linux (kernel: 5.4.12-artix1-1), iPhone XR, Samsung Galaxy S9+

## Steps To Reproduce

1. Enable `Abbreviation syntax plugin` on all 3 platforms
2. Copied and Pasted the example Abbr code from the [Markdown Plugins Guide](https://github.com/laurent22/joplin/blob/master/readme/markdown.md#plugins)
3. Synchronize across all platforms

## Describe what you expected to happen:
I'm not 100% sure how it's supposed to look since there is no live example given or a screenshot in the guide.

## Result:
![Abbreviation-Plugin-Broken](https://user-images.githubusercontent.com/59133880/72903067-2f355d00-3cf2-11ea-8f85-c7e3fe280874.png)

Completely Blank space with no ability to interact with it like described in the guide

## Logfile

[debug.txt](https://github.com/laurent22/joplin/files/4097858/debug.txt)

**Comment by laurent22** [comment]
Did you check the Abbr documentation? This work for me:

```
*[HTML]: Hyper Text Markup Language
*[W3C]:  World Wide Web Consortium
The HTML specification
is maintained by the W3C.
```

**Comment by bedwardly-down** [comment]
I did just check it. It is still broken on my end on all 3 platforms.
