### ISSUE TITLE
Empty space between letters and cursor

### ISSUE THREAD

**Issue by ricciotto-in-nebbia** [laurent22/joplin#2349]
1. Opened the site: https://habr.com/ru/news/t/485112/ (any page is possible)
2. Copy text (cmd + C)
3. Inserted into a new note (cmd + V)

The essence of the error: visually there is some distance between the text and the cursor. 
Something like this: "Text text...............|" (dots is empty space). 
But if you click "backspace" the last character will be deleted.
I tried to make plain text and paste it again - it did not help.
This problem on macOS only. I don't have it on Windows.

![image](https://user-images.githubusercontent.com/28513073/72962435-5f99fb80-3dc5-11ea-847a-dd6eb52e89a5.png)

Joplin for desktop
Joplin 1.0.178 (prod, darwin)

macOS Catalina 10.15.2
MacBookPro

**Comment by dpoulton-github** [comment]
Not a dev just a user...
Have you set a non-monospace editor font on your Mac?
