### ISSUE TITLE
Joplin 1.0.178 window invisible in MacOS X Catalina 10.15.2 (19C57)

### ISSUE THREAD

**Issue by seisenreich** [laurent22/joplin#2350]
I've got a problem using Joplin since it prompted to me there is a new version of Joplin and I installed it.
It will open, but be invisible. It's not even shown by the "show all open windows" feature of macOS.
When I try to install an older version of Joplin, as e.g. the current latest brew cask version 1.0.174, I get the message prompt "Unknown profile version. [...]" when I try to run Joplin. Full error message is added as screenshot. ![Bildschirmfoto 2020-01-23 um 10 15 23](https://user-images.githubusercontent.com/6771616/72971209-9245f300-3dc9-11ea-8d5b-a3d5de67864c.png)

## Environment

Joplin version: 1.0.178
Platform: macOS X Catalina
OS specifcs: 10.15.2 (19C57)

## Steps To Reproduce

1. Download official latest release from Joplin website https://github.com/laurent22/joplin/releases/download/v1.0.178/Joplin-1.0.178.dmg
2. Install it using the dmg.
3. Open it, trusting the developer (mac security)
4. You'll see Joplin running in the right side of the top menu bar
5. The window simply does not show up. Not even when using the "show all open windows" feature of macOS
6. After selecting "Open Joplin" from the icon in the top menu bar, you can even click on the mac menu bar options from Joplin, as View, Settings and so on, but no windows appear after all.

## What I expected to happen:

I expect to see the Joplin window an be able to use the software.

## Logfile

 After following the steps to add the debug flags here: https://joplinapp.org/debugging/
(I couldn't use the console obviously, because I can't see it, but I did all steps before this one.)
I restarted the app and zipped these files for you, so you should be able to debug, hopefully:
* flags.txt
* log.txt
* log-autoupdater.txt
* log-database.txt
[logs.zip](https://github.com/laurent22/joplin/files/4102207/logs.zip)

## Conclusion

If you need any further information from me just reach out to me. Thank's for your time on this in advance.

**Comment by tessus** [comment]
https://discourse.joplinapp.org/t/installing-joplin-1-0-174-on-macos-catalina-results-in-no-visible-window/4425

https://discourse.joplinapp.org/t/cant-open-joplin-after-latest-update/4680

**Comment by seisenreich** [comment]
Thank you very much for linking these cases for me. I could not find them by myself.
I will definitely try to find a tiny pixel window to drag it bigger tomorrow.

**Comment by seisenreich** [comment]
@tessus it worked!
I could not find the window visually, but after clicking "Open Joplin" I could use my Magnet window manager shortcut for fullscreen and the Joplin window came up.

If I had known the window is actually there, even if I can't see it, I would've tried this one out earlier 😄 .

Thank you very much for your support!
Finally I can continue to work with my favourite cross-plattform note taking app on my Mac.

Awesesome!

Best Regards.

**Comment by tessus** [comment]
Glad it worked.

The forum is a good place to searrch for problems/issues or to discuss Joplin in general.
