### ISSUE TITLE
Share notes: Unsopportes WebDAV format

### ISSUE THREAD

**Issue by ricciotto-in-nebbia** [laurent22/joplin#2351]
![image](https://user-images.githubusercontent.com/28513073/72975580-1dcb7e00-3de2-11ea-9388-4bcef35881f8.png)

![image](https://user-images.githubusercontent.com/28513073/72975627-30de4e00-3de2-11ea-9880-8895de0e8321.png)

Windows 10 Pro x64

**Comment by laurent22** [comment]
Please use the forum for support (also try what's written in the dialog box before asking for support)
