### ISSUE TITLE
Joplin 1.0.178 on macOS Catalina 10.15.2 not syncing with OneDrive 

### ISSUE THREAD

**Issue by qvantvm** [laurent22/joplin#2354]
Joplin 1.0.178 stopped syncing with OneDrive on Catalina 10.15.2: clicking the "synchronize" button has apparently no effect.

Rollback to version 1.0.167 is correctly working.

## Environment
Joplin version: 1.0.178
Platform: macOS 
OS specifcs: 10.15.2

## Steps To Reproduce
1. Upgrade from 1.0.164 to 1.0.178
2. Test OneDrive synchronization
3. Joplin asks to open a link on the web browser (SAFARI) to authorize access to OneDrive, immediately the browser says that the app is authorized and Joplin acknowledge that but the syncing is not happening.

Looking at the log the error I see is:
"DecryptionWorker: cannot start because no master key is set"

**Comment by bedwardly-down** [comment]
Have you upgraded to [v1.0.179](https://github.com/laurent22/joplin/releases/tag/v1.0.179) that just released the other day? Its changelog doesn't show any fixes related to what you're referring to directly but it still wouldn't hurt to upgrade to it. If you have concerns, feel free to post them on the forums (after searching to make sure someone else hasn't started a post about it already). ☺️

**Comment by qvantvm** [comment]
I haven't upgraded yet to the new version mainly because to solve the issue I had to downgrade to a previous version, but I will certainly do that.

Regarding the master key I am not using encryption so I guess I do not have/need a master key.
In the future I will update the entire log.

Thanks.

**Comment by shartf** [comment]
No improvement as of Joplin 1.0.200 - OneDrive sync is still not functional.
