### ISSUE TITLE
Support command aliases in CLI tool (eg. quit = exit)

### ISSUE THREAD

**Issue by fmrtn** [laurent22/joplin#236]
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [x] Terminal

I'm trying to customize keymap like vim, I get working move keys but I can't map *exit* command.

    { "keys": ["quit", "q"], "type": "exec", "command": "exit" },

```
> quit
No such command: quit
```

**Comment by fmrtn** [comment]
I realized that it works typing **q** only.
What would be the right way to map like vim with **:q** ?

**Comment by laurent22** [comment]
That would be a command alias which indeed is not currently supported. Maybe there should be something like `alias q=exit` to define them.
