### ISSUE TITLE
Logging out of Dropbox in Desktop App

### ISSUE THREAD

**Issue by TylerBrock** [laurent22/joplin#2362]
Hi folks, I'm logged into a dropbox account that ran out of space so I made a new account that has plenty but I cannot figure out how to log out of the Dropbox account I originally logged into inside of Joplin.

Is there a trick to doing so?

**Comment by tessus** [comment]
Please use the forum for questions. Also please make sure you have a backup (export -> JEX) before you do anything. If the sync target is empty all your local notes will be removed.
