### ISSUE TITLE
dedicated folder in Nextcloud

### ISSUE THREAD

**Issue by blub4747** [laurent22/joplin#2364]
Hi community,

I wanted to know if it possible create dedicated folder on a nextcloud instance and to tell the Joplin client to use this dedicated folder. Instead of dumping everything into the folder.
Thank you and regards,
blub4747

👉 Please follow one of these issue templates:
- https://github.com/laurent22/joplin/issues/new/choose

⚠️
The GitHub issue tracker is for **bugs** and **security issues** ONLY. For feature requests and support, please use the forum:
https://discourse.joplinapp.org/
⚠️

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by dpoulton-github** [comment]
See the forum:
https://discourse.joplinapp.org/t/nextcloud-notes-folder/5200
