### ISSUE TITLE
Joplin will not start minimised if quit when maximised

### ISSUE THREAD

**Issue by dpoulton-github** [laurent22/joplin#2365]
## Platform

Version: Joplin v1.0.179
Version: Joplin v1.0.178
OS: Windows 10 x64 (1909)
OS: Linux Mint x64 (19.03)

Version: Joplin v1.0.175
OS: Windows 10 x64 (1909)
OS: Linux not tested

## Steps to reproduce

1. Open Joplin.
2. In Joplin settings (**Tools** > **Options** > **Application**) tick the box "Start application minimised in the tray icon".
3. **Apply** > **Back** / **OK**
3. **Maximise** the Joplin window
3. **Quit** Joplin
4. Start Joplin

## Expected behaviour

Joplin should start minimised in the notification tray. 

## Actual Behaviour

- If Joplin has been maximised to full screen before **Quitting**, Joplin ignores the setting and starts maximised.
- If Joplin has **NOT** been maximised prior to quitting it will restore minimised as per the setting.

### Additional information

If a **Windows Shortcut** for Joplin is set to **Right-click** > **Properties** > **Shortcut** > **Run: Minimised** the application **will** start minimised regardless of what the application window state was prior to quitting.

May be the same issue as [#2207](https://github.com/laurent22/joplin/issues/2077) and [#2297](https://github.com/laurent22/joplin/issues/2297) both of which could not be reliably reproduced and so were closed. Neither mentioned quitting from a maximised window state. In my testing the above occurs every time Joplin is quit when maximised.

**Comment by hexclover** [comment]
I can confirm this.

In addition, when I replaced the relevant `if` statement in `apps.js` with the following (please note that the `bridge().window().show()` line had been commented out) and started the application again:

```javascript
		if (Setting.value('startMinimized') && Setting.value('showTrayIcon')) {
			// Keep it hidden
			console.log('Hidden');
		} else {
			// bridge().window().show();
			console.log('Shown');
		}
```

The main window *still* popped up and I got `Hidden` on console.
