### ISSUE TITLE
[Feature Request] Export to PDF / Print feature

### ISSUE THREAD

**Issue by fmrtn** [laurent22/joplin#237]
### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [x] Android
- [x] iOS

### Application

- [x] Desktop
- [x] Mobile
- [x] Terminal

Export notes to pdf, specially in desktop versions.

**Comment by laurent22** [comment]
An option to print the note would probably solve this since it's possible to print to PDF from there.

**Comment by jasobar** [comment]
Yes! Just got on to suggest printing as a feature enhancement
