### ISSUE TITLE
Desktop: Joplin crash when changing menu

### ISSUE THREAD

**Issue by mic704b** [laurent22/joplin#2370]
## Environment
Joplin version: Desktop v179
Platform: Linux 
OS specifcs: Ubuntu 18.04

## Steps To Reproduce
1. Start Joplin
2. Click `View` menu
3. Quickly click `Tools` menu

Expected result: `Tools` menu is shown
Observed result: Segment fault

It doesn't happen 100% of the time, but will happen within one to three attempts. It can happen between any menus, not just `View` and `Tools`

**Comment by laurent22** [comment]
We don't have a special handler when menu are shown so that would be an Electron crash. Maybe post the seg fault dump to their issue tracker, in case they can do something about it.
