### ISSUE TITLE
Last keystroke gets undone at random times

### ISSUE THREAD

**Issue by Babber** [laurent22/joplin#2373]
Joplin 1.0.178 on x64 Win10 Pro with syncing via Dropbox

On a few occasions, I have noticed that a few seconds after the last keystroke, the editor undoes that action, that is it removes the last character or undoes the last delete. This happens quite rarely and at random, unpredictable times. It certainly looks like a bug to me but I am not sure (yet) how to reproduce it. Because of the latency, I assume that it might be related to syncing activity?..

**Comment by bedwardly-down** [comment]
This doesn't happen on my desktop but definitely happens on my iPhone at random times, especially when creating a new note while its syncing

**Comment by Babber** [comment]
Apparently, it happens elsewhere too: https://github.com/laurent22/joplin/issues/310#issuecomment-614070792 I think, this is a separate issue, but it would probably manifest less frequently, if #310 was solved. Nevertheless, I still think, that this is a bug, and it shouldn't happen however frequently we save and sync.

**Comment by Babber** [comment]
I am still experiencing this problem and I am not aware of any progress being made in this regard. I would leave this issue open.
