### ISSUE TITLE
checkForUpdates.js bug in code causing #2363

### ISSUE THREAD

**Issue by bedwardly-down** [laurent22/joplin#2377]
## Environment

Joplin version: v1.0.178
Platform: Linux 64
OS specifcs: Artix Linux

## Steps To Reproduce

1. Open Joplin v1.0.178.Appimage
2. Select Help->Check For updates. 
3. Click yes or no and nothing happens with no console or log output. 

Describe what you expected to happen:

Open release page to allow the user to save the new release to their system.  

## Logfile

There are no relevant log files because this bug doesn't get logged in the code. 

## Extra Information 

After experiencing #2363 on my Linux system for Joplin v1.0.178, I went and checked out v177 and v178 from the git repo and inserted console.info('buttonIndex is: %s', buttonIndex); after line 152 where buttonIndex is created from a popup window about new versions.

My console outputs buttonIndex is: Promise { <pending> } when running the app and going to Help->CheckForUpdates because the Yes and No buttons do nothing and the conditions are never met for the two if statements below.

For anyone else that wants to test it out and see what I mean, check out my UpdateTestBed branch on my fork.

One thing that definitely bothers me about this bug is that there’s no logging for Check For Updates either, so I had to find it by just searching the code and seeing something that seemed off to me.

**Comment by laurent22** [comment]
See https://github.com/laurent22/joplin/releases/tag/v1.0.179

**Comment by bedwardly-down** [comment]
This is definitely where having more user friendly bug foxes would come in handy.
