### ISSUE TITLE
Can't share Notes: Unsupported WebDAV URL format

### ISSUE THREAD

**Issue by heyizhang** [laurent22/joplin#2378]
I use the latest version of Joplin. It's configured to use WebDAV well because I can see  it works well from the WebDAV I use, which is jianguoyun.  So I cannot understand  why report "Unsupported WebDAV URL format", Or this feature can only work with nextcloud?

## Environment
Joplin version: 1.0.179 
Platform: macOS
OS specifcs: 10.15.2

## Steps To Reproduce

1. find a note, right click, and share note
![image](https://user-images.githubusercontent.com/33022132/73153089-70bc7280-410d-11ea-9801-8ba14928d069.png)

2. copy sharable link, report 
"Could not connect to the Joplin Nextcloud app. Please check the configuration in the Synchronisation config screen. Full error was:

Unsupported WebDAV URL format: "

![image](https://user-images.githubusercontent.com/33022132/73153103-7b770780-410d-11ea-8b6e-8b8a6d49d963.png)

I expected to get the share URL.
I don't know why it report Joplin Nextcloud app. Or this feature can only work with Nextcloud?

**Comment by bedwardly-down** [comment]
Check this [post](https://discourse.joplinapp.org/t/sharing-notes-or-notebooks/67/4)  out on the forums. It's still live (despite being started two years ago) and looks like it's Nextcloud only for the time being

**Comment by heyizhang** [comment]
Thank you！I‘ll try Nextcloud.
