### ISSUE TITLE
suggest to add catalogue on article right

### ISSUE THREAD

**Issue by ulfyyang** [laurent22/joplin#2380]
add a catalogue on article right, for long article can jump by click catalogue easily.

like that:

<img width="990" alt="图片" src="https://user-images.githubusercontent.com/31947736/73157783-188d6c80-411d-11ea-88a6-61f100d844d1.png">

**Comment by tessus** [comment]
Feature requests **must be opened and discussed on the [forum](https://discourse.joplinapp.org/c/features)**. After they have been accepted, they can be added to the GitHub tracker.

Please check that your request has not already been posted on the forum or the [Github Issue Tracker](https://github.com/laurent22/joplin/issues?utf8=%E2%9C%93&q=is%3Aissue). If it has, **up-voting the issue or topic** increases the chances it'll be noticed and implemented in the future. "+1" comments are not tracked.

search for TOC, table of contents, overview, ....
