### ISSUE TITLE
Prompted to update, no update to be found

### ISSUE THREAD

**Issue by derikb** [laurent22/joplin#2381]
In Mac OS 10.14.6 and Joplin 1.0.178, I've been prompted at consistent periods over the past few days to update to 1.0.179 but clicking "Yes" produces no results, and 1.0.179 doesn't seem to exist on the website so I can manually download. 

I guess some step went missing or wrong in the last release process?

## Environment

Joplin version: 1.0.178
Platform: macOS
OS specifcs: 10.14.6

## Steps To Reproduce

1. (Open desktop app, wait for update prompt) or...
2. Click "Check for Updates" in the Joplin menu in the OS menu area.

Describe what you expected to happen:
Download the update.

**Comment by dpoulton-github** [comment]
According to a closed issue on this matter this was fixed for v1.0.179
https://github.com/laurent22/joplin/issues/2363
https://github.com/laurent22/joplin/releases/tag/v1.0.179

v1.0.179 available directly from:
https://github.com/laurent22/joplin/releases

**Comment by derikb** [comment]
Sorry! Missed that one. Closing.
