### ISSUE TITLE
iOS Set Alarm doesn't show Date/Time widget

### ISSUE THREAD

**Issue by andradei** [laurent22/joplin#2384]
When setting an alarm on a to-do or note, A window shows up at the bottom, but it is mostly blank and the date/time sliders/widgets are invisible.

## Environment

Joplin version: 10.0.43
Platform: iPhone 6S
OS specifcs: iOS 13.3

## Steps To Reproduce

1. Select a to-do or note
2. Touch the three-dot icon on the top-right corner
3. Touch "Set alarm"
4. Touch the "Select date" field or the Calendar icon
5. A new view will show up at the bottom of the screen, the button "Cancel" and "Confirm" will be visible, but there aren't any widgets or controls visible to pick a date and time. Touching "Confirm" still saves the alert though, and blindly swiping and touching the blank area randomly picks a date and time, which means the widget exists, but it isn't being rendered to the screen.

Describe what you expected to happen:

## Logfile

There are only geo location errors because I disabled that feature.

**Comment by bedwardly-down** [comment]
Can verify this issue on iPhone XR running iOS 13.3. 

![777BDEAA-694C-4204-915F-4864FE9BDE34](https://user-images.githubusercontent.com/59133880/73500213-b4baac00-4387-11ea-82df-aeb4d627934a.png)

**Comment by nielsk** [comment]
I have this problem as well. iPhone XR, iOS 13.3.1

**Comment by mavensecurity** [comment]
Here’s a screenshot on an iPhone showing the time and date selector for “set alarm “feature being blank. You can still scroll through the phantom dates and if you’re lucky you’ll get the date you want, you just can’t see what you’re doing.
![54097327-891D-4702-A835-423836D34620](https://user-images.githubusercontent.com/8443691/73594415-5d7a2000-44dc-11ea-89d2-24e68ec30ae2.png)

**Comment by loganwedwards** [comment]
I can confirm on iOS that this is when the OS dark mode is on.

**Comment by loganwedwards** [comment]
I have experienced the same issue on other projects (using `react-native-datepicker`) and am happy to supply a bug fix, but am out of town for the week

**Comment by fab4x** [comment]
I'm having the same problem as well on an iPhone 11, iOS 13.3.1

**Comment by loganwedwards** [comment]
@laurent22 Is this really fixed? I see another issue #2098 open as well and they seem to be duplicates.
