### ISSUE TITLE
[Feature Request] On new note toggle layout

### ISSUE THREAD

**Issue by fmrtn** [laurent22/joplin#239]
### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

An UX improvement.
When click on new note, force to toggle the layout editor to edit mode.

**Comment by laurent22** [comment]
That can't be done I think, as when creating a new note the user might just want to set a title, so we shouldn't automatically change the layout.
