### ISSUE TITLE
Starting from 1.0.177 version the AppImage does not start in Debian Buster

### ISSUE THREAD

**Issue by onocrotal** [laurent22/joplin#2391]
When I try to execute the application I get the following error:
[6873:0128/085551.920553:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_Joplin8BvBnr/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

**Comment by shubhamvaidya604** [comment]
+1

**Comment by bedwardly-down** [comment]
> When I try to execute the application I get the following error:
> [6873:0128/085551.920553:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_Joplin8BvBnr/chrome-sandbox is owned by root and has mode 4755.
> Trace/breakpoint trap

Have you tried running Joplin as root? I wouldn't recommend that for daily usage but that error definitely shows that for some reason, the chromium backend that's part of Electron isn't being given access for your current user.

**Comment by tessus** [comment]
We switched to Electron 7. Apparently that was not a problem with Electron 4 or the builder which creates the image. Unfortunately there is nothing we can do in Joplin.

So how do you run other Electron apps on Debian buster? This is not Joplin specific.

- @bedwardly-down already referenced the Electron issue.
- Please use the forum for further discussions: https://discourse.joplinapp.org/t/unable-to-start-1-0-179-on-linux/5373?u=tessus
