### ISSUE TITLE
MacOS: UI is missing on fresh install

### ISSUE THREAD

**Issue by fear-the-beaver** [laurent22/joplin#2396]
## Environment

Joplin version: Joplin 1.0.179 (prod, darwin)
Platform: macOS
OS specifics: Catalina 10.15.1 (19B88)

## Steps To Reproduce

1. Fresh install Joplin.
2. Open the app.

**Describe what you expected to happen:**

1. App starts.

**Actual results:**

1. App start as 1 pixel size (i.e., invisible).

**Workaround:**

1. Using Spectacle, expand the app with a hot keys combo.

or

2. Pay attention to a 1 pixel window at the bottom right corner. Drag it to the center of the screen and to enlarge it.

**More info:**

https://discourse.joplinapp.org/t/cant-open-joplin-after-latest-update/4680/4

**Comment by tessus** [comment]
see #2350

**Comment by fear-the-beaver** [comment]
> see #2350

I saw this before opening that one. The reason why I've logged that bug is because forums mention workarounds and the github issue got closed without code fix.

**Comment by dandee** [comment]
> see #2350

it's been locked but the issue hasn't been resolved.

**Comment by dandee** [comment]
**Joplin 1.0.179 (prod, darwin); first-time ever installation on Mojave 10.14.6 (18G3020); is missing main window.**

Upon application launch you can see "Window" section of menu briefly visible along the rest of menu then it disappears. Main window never shows up and it's not present in Applications Windows view. Clicking on Joplin->About Joplin presents "about" window and then main window materializes out of nowhere, you can use the main application window from then on but you can't bring "about" window to front nor close it by clicking "OK" button - it just stays there, beneath the main window. "Window" section of the menu is still missing after that.

**Comment by tessus** [comment]
see #2476 
Somebody is workibg on it....

**Comment by fear-the-beaver** [comment]
I've recently updated Joplin to:

`Joplin 1.0.200 (prod, darwin)
Client ID: 3468ebd5b3a6457fb6e7bd01427d3719
Sync Version: 1
Profile Version: 28
Revision: 142976f (master)`

Mac OS version:
`10.15.3 (19D76)`

After the restart the app screen appeared normally.
