### ISSUE TITLE
View goes up whenever something new is added

### ISSUE THREAD

**Issue by Vitorvlv** [laurent22/joplin#2397]
Here is a short video showing the error, is easier this way: https://streamable.com/gzd82#

But basically whenever I write anything on the text box, the view goes up.

This is quite a long note, and it wasn't happening when I started. So it might have something to do with how long the note is. I also used some chemical notations in it $\ce{}$, which always slow performance down for me. 

Restarting Joplin fixed it for now.

Joplin version: 1.0.179
Platform: Linux
OS specifcs: Manjaro

**Comment by mic704b** [comment]
Nice video demo.

Same issue as #1546?

**Comment by Vitorvlv** [comment]
It has better wording than my issue, for sure. But yeah, I think that's it, I'll close this one.

**Comment by mic704b** [comment]
Thanks @Vitorviv -- in that case, make sure to add your info to that issue.
