### ISSUE TITLE
Font Ligatures Rendering Offset in Editor But Not Rendering At All In Preview

### ISSUE THREAD

**Issue by bedwardly-down** [laurent22/joplin#2399]
## Environment

Joplin version: 1.0.179
Platform: Linux 64
OS specifcs: Artix Linux

## Steps To Reproduce

1. Download and install the [FiraCode Nerd Fonts](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode)
2. Set Joplin's font to FiraCode (as shown in example below)
![2020-01-29-011901_1920x1080_scrot](https://user-images.githubusercontent.com/59133880/73336105-9002ef00-4236-11ea-8197-48eeee28038b.png)
3. Type ==> to create an arrow

Describe what you expected to happen:
Ligatures like this are used by many programmers and even people that make visually linked notes and ideas (similar to how Mermaid works). What is supposed to occur is showing in the Editor Pane (albeit offset by a few pixels) while the Preview Pane shows what was typed without rendering the ligature.

![2020-01-29-011908_1920x1080_scrot](https://user-images.githubusercontent.com/59133880/73336302-10295480-4237-11ea-909f-0795d8367531.png)

## Logfile

I'd like to thank one of the members of the Joplin Discord for asking about this very topic and getting me to test it out.

**Comment by dpoulton-github** [comment]
Could this be because the two panes use different font settings? One set in Joplin (editor) and one set in `userstyle.css` (preview)?

**Comment by dpoulton-github** [comment]
As a test I added the FiraCode font to a `userstyle.css` for the element **code** and typing `==>` gave this:
![2020-01-29 15_08_19-Window](https://user-images.githubusercontent.com/60117449/73368854-9bdbc900-42a9-11ea-8e4d-af0a76e55d82.png)

**Comment by bedwardly-down** [comment]
@dpoulton-github that could definitely be the case. I would think that the options would have the ability to set fonts for both afterall.

**Comment by dpoulton-github** [comment]
Just for info the I tested the above on Win10 however I have now tried a Linux (Mint) machine and in both cases I have not found a problem with the ligature being offset in either the editor or the render / viewer pane. BTW, brilliant find, this font is really good when paired with Joplin. It's quite amazing that just a font can add such functionality.

**Comment by bedwardly-down** [comment]
The offset issue could very well be my non standard desktop and window manager. It could also be drivers or a plethora of other things. Thanks for testing all this out. I hope this will benefit others quite a bit

**Comment by dpoulton-github** [comment]
At this stage possibly not a "bug" issue?

**Comment by bedwardly-down** [comment]
I'm closing this issue. In case others are curious about this, @dpoulton-github , I'd love to see you share your findings on the forum. They would definitely useful to more visual types.

**Comment by dpoulton-github** [comment]
https://discourse.joplinapp.org/t/interesting-font-for-code/5513
