### ISSUE TITLE
Copy paste does not work on Mac

### ISSUE THREAD

**Issue by clamport** [laurent22/joplin#24]
Copy paste does not work on Mac in the note or ToDo edit pane

Mac OSX - Sierra
Joplin 0.10.28

**Comment by brycereynolds** [comment]
Looks like Cmd-H (hiding Joplin) also doesn't work. Could be that the keyboard shortcuts are being hijacked. 

On that note, just doing Edit > Paste still doesn't allow you to paste from clipboard on mac. 

Sierra: 10.12.6
Joplin: 0.10.28

**Comment by laurent22** [comment]
The copy/cut/paste issue on macOS should now be fixed as of v0.10.30. Please give it a try and let me know if there's still any issue.

**Comment by MarcoBatista** [comment]
No issues here with High Sierra and Joplin 0.10.30
