### ISSUE TITLE
Issues with tags

### ISSUE THREAD

**Issue by jogi4github** [laurent22/joplin#240]
### Operating system

- [X] Windows
- [ ] macOS
- [X] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [ ] Terminal

Hello,

I'm having problems with the tag system. I've imported about 1600 notes from evernote incl. tags. The tags contains capital letters.
If I try to change a list of assigned **imported** tags on a note and if I only use **existing** tags (incl. capital letters) I end up loosing all tags upto the last I entered. EG. having a note with a list of tags: `Test1, Test2, Test3` and if I change this list to `Test1, Test2, Test4` I end up with only the last tag Test4`

The other issue I have is if I add new tags, they are automatically converted to small letter tags like mentioned in #129. However with new tags, creating lists of tags do work (only small letter tags), so the situation seems to differ between imported tags with capital letters and new ones which are automatically converted to small letters.

As I would really like to start using Joplin productively  is there a way to convert my current tags with capital letters to small letters without doing that task manually (eg. using sed running agains the md files)?

**Comment by jogi4github** [comment]
Ah I missed to mention that I'm using the last version Joplin 1.0.66

**Comment by laurent22** [comment]
Yes there was indeed some issue with the way tags with uppercases were handled. This will be fixed in the next version.
