### ISSUE TITLE
Last error: Error: On file cc0e6915b30947edb5698361e8baf592.md: Item cannot be null

### ISSUE THREAD

**Issue by D4nte** [laurent22/joplin#2405]
I added a bunch of new notebooks on my desktop.
It synchronise to my phone via syncthing. Then I started to notice the same error on both devices when synchronising.

I am not able to see these new notebooks on my phone despite the folder (on filesystem) being full synchronised.

### Desktop
Joplin version: 1.0.178 (prod, darwin)
Client ID: d0cffdc90adb49d0a7e9fcd2d1f7fc79
Sync Version: 1
Revision: 953aa5d (HEAD)
Platform: macOS
OS specifics: 10.14.6

### Mobile
Android Joplin 1.0.316
Database v27
Android OnePlus 7
Android version 10
Build number Oxygen OS 10.3.0.GM57AA

## Steps To Reproduce

A bit hard to "reproduce" now that my sync is broken.

## Content of the cc..92.md file (on desktop)
[syncReport-1580337579570-android.txt](https://github.com/laurent22/joplin/files/4131168/syncReport-1580337579570-android.txt)

```
id: cc0e6915b30947edb5698361e8baf592
parent_id: dce4b501c98b437f8ebb53aaa2f92a2f
created_time:
updated_time: 2020-01-24T00:00:29.831Z
is_conflict:
latitude:
longitude:
altitude:
author:
source_url:
is_todo:
todo_due:
todo_completed:
source:
source_application:
application_data:
order:
user_created_time:
user_updated_time:
encryption_cipher_text: JED01000022012daf68976b0340b8a533be3364ada71b0003d2{"iv":"PXIYKIp/GqZvocI+SVMv+Q==","v":1,"iter":1000,"ks":128,"ts":64,"mode":"ocb2","adata":"","cipher":"aes","salt":"noOLojCA5Gg=","ct":"i/bQ2R2Hcy8POBBCGP8KtGsiqHaabMuHSsZoK/NYOQYftCoQR8+RlLeEPm5PpVsv/sh72Z9MxKQJGc2XWkxZ6i4eFP5LnHiWDfEYgR2M1qHpnwRgoBVNLMWaanXC8icB5HWNywOPs5nBKoqJxjMD8RQTd8KFEGRqLU/M7HZeuB7or9ayv7iAWgoT7LY2WGVaFQCD7dqCjojxv1R3zox1H+E91bL6QWDs87Keh+SYbM2IQGSCMSaTf605IpEb0zjoBHCbrv9H4yZrrYN2VIRwMkx61lJSQ5n2WnJVowQgmaByVAKu3g3T9QeoS0h7i+hNwn6TrGtjaTR0BvAhQLMqLm0kYr7ki+kmLATtRh9GK8Br/cbcqSeoXAv9x1tdAjH2ctw1V/TIC4wekGSL8wk44gxly2RIJ7JvZIV2GWzAZ86ubJyZedGp80l2F2rCHQMrT2suxGnC/SvRzb7sk50anEWlX8zHRvAgr+bKy/FKuzlzlK9CfcIVeH57gs9QRthrAROxmyQJivMLD9WUDyDRa6+44MIAvJUr81hQb4HDrq0/u0hTME168l59pqi3T+s+N4wddoCpXVpxANYAPOGa3BGOnaSywJzqdwY7Afi7VpFgwgJZAxEYQRjVA0tIzWKEAmj6SeZh7GnVNByKDNF+X/OQpDA2nWH20M8pHxRc49e4DCUtIQVV8VOemjIhvukGbjH593H+FMEeRxgeob/8YZHhK45PT8ghRIJmckpTCo5sAC5JwijXwVPlxipB8mfMTBiMwsOLj+Eb3CYMeiW3m8lTTntGio24N0/3J9bcMMVN0HBHhiIDrAY+Mm79IA+gfMKiy0A="}
encryption_applied: 1
markup_language:
type_: 1ddw=="}
encryption_applied: 1
markup_language:
type_: 1
```

## Logfile

[log-desktop.txt](https://github.com/laurent22/joplin/files/4131071/log-desktop.txt)

**Comment by D4nte** [comment]
Once I remove the file the problem is fixed.
Is it possible to manually decrypt a file so I can check the content and see what in the content created the issue?

**Comment by mic704b** [comment]
FYI  https://discourse.joplinapp.org/t/item-cannot-be-null-error/3001

**Comment by tessus** [comment]
Yep, should be fixed in 1.0.179. Please try the new release and open a new issue should you still run into the same problem.

**Comment by D4nte** [comment]
Is it possible the retrieve the content of the corrupted file? I upgraded to 1.0.179 on the desktop and the error still occurs on this file.

**Comment by tessus** [comment]
@D4nte first make sure you have a backup of your note. I think the following might help: 
Edit the metadata by deleting the line

```
type_: 1ddw=="}
```

Make sure when you save the text file that there's no line ending at the last line.

**Comment by D4nte** [comment]
Thanks,
For some reason, it is not possible to recover. I tried manythings including copy-pasting a valid note and just copying the the `id` and `encryption_cipher_text` from the corrupted text, and I always get the following error:

```
Last error: Error: On file cc0e6915b30947edb5698361e8baf592.md: Missing required property: type_: id: cc0e6915b30947edb5698361e8baf592 parent_id: dce4b501c98b437f8ebb53aaa2f92a2f created_time: updated_time: 2020-01-24T00:00:29.831Z is_conflict: latitude: longitude: altitude: author: source_url: is_todo: todo_due: todo_completed: source: source_application: application_data: order: user_created_time: user_updated_time: encryption_cipher_text: JED01000022012daf68976b0340b8a533be3364ada71b0003d
```

Despite the `type:_ 1` being in (with no line ending, as I copied a full valid file).

Can't the serialisation be a bit less brittle to help recover from corruptions?

**Comment by mic704b** [comment]
I know nothing about this.

But the last lines of your file are:

```
encryption_applied: 1
markup_language:
type_: 1ddw=="}
encryption_applied: 1
markup_language:
type_: 1
```

Have you tried after just removing all those duplicate lines?

```
encryption_applied: 1      <--------------- delete this one
markup_language:           <--------------- delete this one
type_: 1ddw=="}            <--------------- delete this one
encryption_applied: 1
markup_language:
type_: 1
```

**Comment by tessus** [comment]
@mic704b thx, I missed 2 of the duplicates!

**Comment by laurent22** [comment]
Also I don't know if you copied `type:_ 1` from your file but it should be `type_: 1`. And no, de-serialisation won't be less "brittle" and try to guess the content of broken files - that's how you end up silently corrupting user data.

**Comment by D4nte** [comment]
Thank you all 3 of you.

Yes, I did noticed the dupe lines and removed as per @mic704b's suggestion but still get `Missing required property: type_: id cc...` error.

Yes indeed @laurent22 it was a typo.

> Make sure when you save the text file that there's no line ending at the last line.

I think this is my issue.

When I `cat` the corrupted file it shows:

```
...
type_: 1%
```

I assume the `%` (It's black font on white background, my terminal is configured  white font on black background) is here to display the fact that there is no end of line.

However, whenever I tried to manipulate the file with vim or grep, the `%` disappears. I am guessing an end of line is added.

I guess I just need to somehow preserve the fact that there is no line ending while restoring the file.

**Comment by tessus** [comment]
Most editors are configured to add an EOL at EOF because a line without EOL is not a proper line according to POSIX.
However, Joplin requires the last line to be without an EOL otherwise the import will fail.

There's no `truncate` on macOS, but you can use the following to remove the last EOL at EOF:
(make a backup of the file though)

```
file=test.txt
length=$(wc -c <$file)
dd if=/dev/null of=$file obs="$((length-1))" seek=1
```

**Comment by D4nte** [comment]
@tessus I was just going here to mention exactly that.

`truncate` can be installed on mac: `brew install truncate`

Then modify the file and run `truncate -s -1 <file>` and that's how I did it.

Thanks!

ps: I guess it would be good to ahve valid POSIX files generated by Joplin.
