### ISSUE TITLE
Canceling print will put the UI in a locked up state without an obvious resolution (Linux only)

### ISSUE THREAD

**Issue by taw00** [laurent22/joplin#2407]
UPDATED description.

Joplin 1.0.179
OS: Fedora 31, Gnome 3.34

1. Open Joplin
1. Go to print something with CTRL-P
1. Cancel it.
1. Observe notification window that opens, but can't be removed excepted with the escape key which is perhaps non-obvious. Joplin is unusable until this action is taken.
1. Closing Joplin does not remove the notification window and Joplin cannot be restarted in a useful state. ... until that ESCAPE key is hit. There is not indication that the user needs to hit the escape key.

Fun! See attachment that shows the little window that opens up.
![Screenshot from 2020-01-29 10-28-57](https://user-images.githubusercontent.com/6908872/73418759-bbdfac80-42ea-11ea-8339-e792ce86b153.png)

**Comment by taw00** [comment]
log.txt had no error. Nor did any other log files. But I was able to produce this. I hope it helps.
![Screenshot from 2020-01-29 23-05-00](https://user-images.githubusercontent.com/6908872/73419303-9e134700-42ec-11ea-8c88-c6277aea10ab.png)

**Comment by tessus** [comment]
Hmm, this might be a Linux issue. It's also strange how the message looks like.

However, when cancelling, there should not be an error message at all. So there are actually 2 issues:

- error message after cancelling
- error message can't be dismissed (Linux)

With git master on macOS it looks like this:

<img width="531" alt="image" src="https://user-images.githubusercontent.com/223439/73427445-cc048580-4304-11ea-85ad-96e32cde2546.png">

**Comment by mic704b** [comment]
It works on Ubuntu 18.04, though I do get the warning dialog without any button, which I clear by Escape key.

**Comment by mic704b** [comment]
> So there are actually 2 issues:
    error message after cancelling
    error message can't be dismissed (Linux)

The PR resolves the first issue.

The inability to dismiss a dialog box (@taw00) and a dialog box without OK button (me) are perhaps separate issues.

**Comment by mic704b** [comment]
>  a dialog box without OK button (me) are perhaps separate issues.

Upon investigating in the code, this is intentional. So this part is not a bug.

**Comment by tessus** [comment]
> Upon investigating in the code, this is intentional.

This can't be. Otherwise there wouldn't be a button on macOS. Alao, please note the differences.
On macOS the dialog is bound to the main app window. On Linux it just pops up in the middle of the screen? Something is off.

**Comment by mic704b** [comment]
> Otherwise there wouldn't be a button on macOS

The Joplin error message is defined without specifying buttons.  The Electron doc says:

> buttons String - Array of texts for buttons. On Windows, an empty array will result in one button labeled "OK".

but doesn't specify what will happen on other platforms.

If I explicitly add an `OK` button to the Joplin error message, then I get one (on Linux).

Perhaps we should do this? Or do we leave it up to the Electron default behaviours on the different platforms?

**Comment by tessus** [comment]
I think we should add an `OK` button to `bridge.js` for `showErrorMessageBox`. But this is @laurent22's decision to make.

**Comment by taw00** [comment]
Oh, geez. I was able to dismiss it with the ESC key as well. GAH! I'm an idiot.  
Still... that shouldn't be the behavior. :)

**Comment by laurent22** [comment]
> I think we should add an OK button to bridge.js for showErrorMessageBox. But this is @laurent22's decision to make.

Yes I agree, there should be an OK button by default. I can only assume that this is a bug in Electron that it's missing.

**Comment by mic704b** [comment]
> Yes I agree, there should be an OK button by default. I can only assume that this is a bug in Electron that it's missing.

Great! The bug might be platform specific. In any case, the pending PR includes a work around for it, so it will work on all platforms regardless.
