### ISSUE TITLE
Markdown rendering issues with headers

### ISSUE THREAD

**Issue by dbogdanov** [laurent22/joplin#2411]
The markdown headers are often rendered incorrectly: sometime they work properly, but they often fail to be recognized and it becomes very annoying. See an example on the screenshot.

![Screen Shot 2020-01-30 at 14 25 53](https://user-images.githubusercontent.com/409668/73453637-c17dd680-436c-11ea-9a12-85b67256f61a.png)

I could not narrow down in which exact conditions this happens. It feels pretty random... For comparison, Typora always recognizes headers well. 

## Environment

Joplin version:  1.0.179 
Platform: macOS (will confirm on Linux later) 

## Steps To Reproduce

1. Copy-paste the following text to a new note:
```
# H1 header
## H2 Header
### H3 header
```
2. The markdown headers may be rendered incorrectly

**Comment by laurent22** [comment]
Can't replicate with what you posted, but isn't it just an issue with non-breaking spaces being accidentally inserted?

**Comment by dbogdanov** [comment]
The spaces in H1, H2 and H3 in this example are exactly the same.

**Comment by laurent22** [comment]
Can you export a note that shows the problem as JEX and attach it here?

**Comment by dbogdanov** [comment]
Here is [the example from above](https://www.dropbox.com/s/22neatptph4aaix/test_headers.jex?dl=0).

**Comment by tessus** [comment]
@dbogdanov I don't know what you did, but the first 2 lines do not have a space between the `#` and the text. It's the following character: https://unicode-table.com/en/00A0/  (No-Break Space)

**Comment by dbogdanov** [comment]
My bad. Thanks a lot for finding this out!

I thinks this happened without me realizing because, on a Spanish layout, to type `#` one need to press `alt-3`, so if you type the following space faster then releasing `alt` it will be treated as `alt-space` too. I did not know that's a shortcut for a No-Break Space on Mac 😈

**Comment by tessus** [comment]
You are welcome.
