### ISSUE TITLE
Weird gaps in notes on Android

### ISSUE THREAD

**Issue by shubhan-shu** [laurent22/joplin#2412]
Notes on Android show weird gaps after some words. Please see the attached screenshot, the gaps have been denoted by yellow marks.

![IMG_20200130_193144](https://user-images.githubusercontent.com/60474261/73456634-3d414880-4398-11ea-9662-0e231a83b6d1.jpg)

P.S.- You guys are doing an amazing job. I have just started using Joplin and I love it. This is my first GitHub post, I don't know anything about GitHub.

## Environment

Joplin version: 1.0.316
Platform: Mobile
OS specifcs: Android 9.0

**Comment by laurent22** [comment]
Non-breaking spaces? If you could export the note as JEX and attach it here, I can check.

**Comment by shubhan-shu** [comment]
I can't share JEX, I'm on mobile only. Here is the markdown code:
```
Citizenship (Amendment) ACT 

* The Citizenship (Amendment) Act, 2019 amended the **Citizenship Act of 1955** and provided Indian citizenship to the members of **Hindu, Sikh, Buddhist, Jain, Parsi, and Christian** religious minorities, who had fled persecution from **Pakistan, Bangladesh and Afghanistan** and entered India *illegally* before or on <span style="color:green">**31st December 2014**</span>. *Muslims were not given such eligibility*.


* It was passed by the Parliament of India on <span style="color:green">**11 December 2019**</span>.

* According to Intelligence Bureau records, the immediate beneficiaries of the Amended Act will be <span style="color:green">**31,313 people**</span>.
# Anti CAA Protests

* Protests have been taking place in India (specially in **Delhi and in Seven Sister States**) and overseas against this act.
  * Many protesters view this Act discriminatory against Muslims.
  * People in Seven Sister States fear that legalization of immigrants in their area will cause **demographic imbalance**.

* <span style="color:green">**27 people**</span> (including 3 minors) have lost their lives in these protests.

# Arguments against CAA

1. It excludes muslim immigrants, especially muslim minorities like **Muhajirs** who are persecuted in Pakistan.

2. India is already struggling with taking care of its own poor citizens, addition of more citizens will make the situation more difficult for the people and for the nation. From this perspective it can be interpreted as a hastily made political move and not a well though out humanitarian effort (an opinion).

# Arguments supporting CAA

1. It keeps the options open for everybody, including muslims, to attain Indian citizenship as Adnan Sami did the same.

3. Humanitarian Grounds. It is a step for India on the path of becoming *Vishwa Guru*, as the Prime Minister has mentioned it several times.
```

**Comment by laurent22** [comment]
I can't replicate.

**Comment by shubhan-shu** [comment]
I copy-pasted the markdown in a few other markdown editors/viewers, still same problem. Appears to be an issue with my phone. I am using Xiaomi Redmi Note 5 Pro.

**Comment by bedwardly-down** [comment]
@shubhan-shu are you using the MiUI launcher (the one that comes as its default UI)? If so, iirc, there may be a font option in its settings menu that could fix the issue. I used to collect import phones and I still have that exact on my shelf. It still works just on my WiFi only since it doesn't have a sim.

**Comment by shubhan-shu** [comment]
I tried changing font in my phone (there is an option in the 'Themes' app in Xiaomi), it does change the font in Joplin app **while editing** a note but not **while viewing** it.

In the 'configuration' section of the Joplin Android app there is an option to change 'Editor Font' but it only applies to the font while editing a note. Perhaps the 'Viewing Font' is different from monospace and it can't be rendered properly on Xiaomi.

**Comment by bedwardly-down** [comment]
@laurent22 does the mobile version also have the viewer font only changeable through a css file like desktop version?

**Comment by bedwardly-down** [comment]
@shubhan-shu i may have a solution. Go into Joplin Configuration, scroll down to Appearance, and you'll see a Font option below Theme. Change that to monospaced. Then save it. 

You may need to restart the app but how's that?

**Comment by bedwardly-down** [comment]
@shubhan-shu that may be the case. I just saw the line about that and was responding the same. If you join the discord (link on the main joplin page), when i get home from work for lunch, i can test some things out. My username on there is the same

**Comment by shubhan-shu** [comment]
@bedwardly-down Thanks for trying to help me. But this is not a problem with Joplin app. The same problem persists in other markdown editors/viewes too (changing phone's font changes font while editing md but not while viewing it). It is likely a problem with the way my Xiaomi phone handles fonts. I will, perhaps, have to live it for a while.

**Comment by bedwardly-down** [comment]
I was meaning, because i have that phone, i can troubleshoot some things to see if i can figure it out

**Comment by shubhan-shu** [comment]
@bedwardly-down I don't have a discord. I'll contact you later there.

#To recreate recreate the situation you can.

1. Install Joplin on Xiaomi Redmi Note 5 Pro.

2. copy-paste the markdown code I shared earlier in this thread.

**Comment by bedwardly-down** [comment]
@shubhan-shu If you can close this issue since it's not a Joplin one, thanks. ☺️
