### ISSUE TITLE
The update popup doesn't trigger the download when clicking YES.

### ISSUE THREAD

**Issue by narFnarF** [laurent22/joplin#2416]
When Joplin detects a new version and offer to download the update, clicking the Yes button doesn't start the download like it used to. Pressing the Yes button is equivalent of clicking the No button.

I first noticed this issue when updating from 1.0.177 to 178. I also got the issue when updating from 178 to 179. 

I use Joplin on Mac and Windows and they both have the issue.

## Environment

Joplin version: 177 and 178 (I can't test yet on 179 because there's no new release)
Platform: Windows 10 and macOS10.11
OS specifcs:

## Steps To Reproduce

1. Wait for Joplin to announce that there's a new update.
2. In the update popup, click Yes
Result: The popup closes. Nothing else happens. The download doesn't start like it used to.

Describe what you expected to happen:
The download should start.

**Comment by laurent22** [comment]
Thank you, this is fixed in 179
