### ISSUE TITLE
Sync on iOS does not sync everything

### ISSUE THREAD

**Issue by nielsk** [laurent22/joplin#2419]
I created notebooks and notes on the desktop and mobile. The notebooks that I created on the mobile device appear in the Electron- and in the Terminal-app. But the notebooks  I created on the desktop do not appear in the mobile app. 
Notes that I do in the notebooks created in the mobile app, sync either way (if created on desktop they turn app everywhere etc).
Only notebooks make a problem
I sync via nextcloud.

iOS 13.3.1, iPhone XR, Joplin 10.0.43

**Comment by tessus** [comment]
This is not a reproducible bug. You ignored the template. For problems please use the forum.

Also, seriously, how is anyone supposed to help with no log files and no steps to reproduce? Anyway, check the forum. There are several suxh posts
