### ISSUE TITLE
Passive sync on mobile clients

### ISSUE THREAD

**Issue by jurgenhaas** [laurent22/joplin#242]
Would it be possible to provide a sync mode for mobile devices where only metadata (notebook, title, tags) will be synced but not the note bodies and their attachments? I'm asking because I imported my Evernote notes into Joplin which comes with almost 1 GB of data and that is certainly too much for my mobile devices. So I'm running out of space there.

**Comment by laurent22** [comment]
That probably won't be possible as the apps are designed with the assumption that the entire data can be stored on the device.
