### ISSUE TITLE
Add support for Bibtex

### ISSUE THREAD

**Issue by avarf** [laurent22/joplin#2433]
Hi, thanks for the software.

I was searching for an alternative for LaTex and I found you. The only thing is as I found out you are not supporting Bibtex (I couldn't find anything related to supporting Bibtex).

I suggest and request that you add Bibtex support to your software and I am sure you will become a strong alternative for LaTex since you have a good tool and Markdown is much simpler to work with than Tex.

**Comment by laurent22** [comment]
Joplin supports Katex (not Latex) and there's no plan to support Latex or Latex extensions.
