### ISSUE TITLE
Too slow to use

### ISSUE THREAD

**Issue by tornadoyi** [laurent22/joplin#2438]
I download latest version of Joplin. It is too slow to use. When I press any button on the keyboard, The reaction that I can see on the editor layout cost few seconds. I test the latest version on Mac and windows, then I got same problems. My Joplin version on Mac  as below.

Joplin for Desktop

Copyright © 2016-2019 Laurent Cozic
Joplin 1.0.179 (prod, darwin)

Client ID: c79f1bf956ba455d8b82b940f499a2c0
Sync Version: 1

Revision: 66356d8 (HEAD)

**Comment by zyzhu2000** [comment]
I am having exactly the same problem since a recent update happened in December or January,

**Comment by virtadpt** [comment]
I've pretty much given up on this getting fixed because it's an upstream bug.  On Android, Joplin is utterly unusable for editing anything.

**Comment by proinsias** [comment]
Same problem on macos:

Joplin 1.0.201 (prod, darwin)

Client ID: 1925653ac73840c89b95aa29bf822197
Sync Version: 1
Profile Version: 28

Revision: e65af8c (master)

**Comment by virtadpt** [comment]
Gave the latest version for Android a spin last night - same problem, not fixed.

**Comment by dbogdanov** [comment]
I experience slow editing on very long notes.

**Comment by freecodecampster** [comment]
I experience slow editing on very long notes as well using WYSIWYG, however on macOS Big Sur with a 2013 i5 16GB RAM SSD once the note is loaded it becomes very responsive and I can edit fine but on a much more recent PC with 2020 i5 10400 32GB RAM NVME the Windows app keeps becoming unresponsive in WYSIWYG view.  Appears Windows performs worse with WYSIWYG editing than macOS.

Joplin 2.9.17 (prod, win32)

Latest version on macOS as well.
