### ISSUE TITLE
When accessing configuration or encrypt configuration option while making a note and the going back, the note gets erased and you're directed to the front page of the app. 

### ISSUE THREAD

**Issue by earlpayton** [laurent22/joplin#244]
#### Expected behavior
Once accessing the configuration or encrypt config from the nite and then pressing the back button should take us back to our note. 

#### Actual behavior
While going back from these two options we are directed to the homepage of the app, and not letting us complete the note we were making. Doesn't save the draft either and results in all the time and effort wasted. 

#### How to reproduce
Launch the app. 
Click on the plus button. 
Write a note. 
Go to the options by clicking the button at top right side. 
Click on configuration or encrypt cinfig. 
Now press the back button. 
Your all work is lost, you're directed to the homepage. 

* App: Joplin Notepad v1.0.95
* Operating system:Android Nought (7.0)
*  Device: Motorola moto g5 plus 

#### Recording Of The Bug
![20180216_102737.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518757103/vksd30tqdt3q8a8aw0el.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@earlpayton/when-accessing-configuration-or-encrypt-configuration-option-while-making-a-note-and-the-going-back-the-note-gets-erased-and-you">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by fmrtn** [comment]
Same behavior on iOS 1.0.13
