### ISSUE TITLE
Feature - provide smart notebooks

### ISSUE THREAD

**Issue by the42** [laurent22/joplin#2448]
Some users in the past reported a functionality I got to love after some time in other personal knowledge management systems / GTD like Emacs org-mode or OneNote: Diaries, which help to keep track about todo items in different notebooks.

The following collects suggestions made in the past which all petered out due to lack of interest for implementation or unresponsive reporters:

#166  - Feature - Associate TODO notes with date
This feature is required to define a date an item is due to. During the course of conversation the reporter rightly adds that once an item has been marked as done, the associated due-date need no longer be the signal for an item to be "open". Additionally, other GTD system have the notion of scheduling todos which is different from a due-date in that it marks more or less the date when action has to be taken and the due-date when the task has to be done.

#1134  - [Feature Request] In-note todo due dates and global agenda
With #166 describing the data basics needed to assign dates to todo items, this feature request stitches these bits and peaces together and actually describes a smart notebook _which is created by the system_ instead the user himself. Open / active Notebooks contained todo items with associated dates are assembled to create a journal or agenda of upcoming todo items and their due dates. This provides the productivity gains joplin could offer and would easily make it the perfect GUI-based / cross platform / mobile PIM/GTD tool of choice.

Lastly on a discussion https://discourse.joplinapp.org/t/global-todo-list/2592/10 about that missing feature.

Make joplin great!

(Thank you for providing this absolutely wonderful and outstanding self-organisation tool)

**Comment by tessus** [comment]
Feature requests must be posted and discussed on the forum first. The gh tracker is for bugs only (and accepted feature requests).

I'm not sure why people ignore this all the time. I think we've been clear about this in the template, on the web site and in CONTRIBUTING.md.
