### ISSUE TITLE
Unable to export each note to MD format proplerly in Window10 Joplin 1.0.179

### ISSUE THREAD

**Issue by tiroring09** [laurent22/joplin#2449]
# Unable to export each note to MD format proplerly in Window10 Joplin 1.0.179
## Environment

Joplin version: 1.0.179
Platform: Window10
OS specifcs: Window10

## Steps To Reproduce
Hi, here is one big fan of Joplin. Recently I've just bumped into a tiny problem and that's what brought me here. As you know, there are two options in exporting notes into .md format; (1) export entire notebook, (2) export each note.

Since upgraded to 1.0.179(not sure), all exporting options work well except exporting each notes to .md format. I tried several things, and I figured out that this problem might have something to do with directory creating method.

Here are some screenshots of bug log below. Have a look and let me know if the cause was on my site. Thanks!

<BR><BR><BR><BR>

---
### CASE 1. exporting entire notebook >>>>> works well
![31aef96e32274750a5a2d469f7c6b16c](https://user-images.githubusercontent.com/54842445/73893977-7dd02300-48be-11ea-9881-32443943d0b4.png)

![307faee5b23442a99fca2f40db325bb2](https://user-images.githubusercontent.com/54842445/73893982-80327d00-48be-11ea-9353-73e64b83c659.png)

![eb66b9a5b35840b4bfe04cc841a2d57b](https://user-images.githubusercontent.com/54842445/73893984-80327d00-48be-11ea-9a9d-2b3e2541a689.png)

<BR><BR><BR><BR>

---
### CASE 2. exporting each note >>>>> not work

![568f216858084e5fb2e8c6d32fc7abab](https://user-images.githubusercontent.com/54842445/73893996-845e9a80-48be-11ea-9ee4-ab1a3d4f88ef.png)

![ca57931faf234281a2d22847fe91e50f](https://user-images.githubusercontent.com/54842445/73893998-845e9a80-48be-11ea-8596-f4d41bfabe67.png)

![4ec6c88a0bab40b593ff3d31d3b9ee7d](https://user-images.githubusercontent.com/54842445/73893994-83c60400-48be-11ea-83f6-c22475a20b66.png)
<BR><BR><BR><BR>

---
### CASE 3. Creating directory before exporting each note >>>>> work
![db5a7fe6d9924190be0432439693ee44](https://user-images.githubusercontent.com/54842445/73894007-87f22180-48be-11ea-937b-09b8b3a95b24.png)

![5cbdb02351f34215935961ff6d72d6a3](https://user-images.githubusercontent.com/54842445/73894002-86c0f480-48be-11ea-8428-a1ad5bd411ac.png)

![08d7d3cc7ec24e8a9f7f4043cdaefced](https://user-images.githubusercontent.com/54842445/73894003-87598b00-48be-11ea-921c-7d06f8e68d1f.png)

![8d194aa42e1b48e581aeda4e67fa4888](https://user-images.githubusercontent.com/54842445/73894004-87598b00-48be-11ea-8688-7dca477e7f87.png)

![91bfe623875a464ba85dbb6be56eedff](https://user-images.githubusercontent.com/54842445/73894006-87f22180-48be-11ea-8ef3-92c4fe31f84f.png)

<BR><BR><BR><BR>

---
## Logfile

[log.txt](https://github.com/laurent22/joplin/files/4162583/log.txt)

**Comment by tiroring09** [comment]
Here's jex file requested. Appreciate for reply :)
 tiroring09.jex
<https://drive.google.com/file/d/1YbBtDquTpbUv1-JQByVpuA46_ayGq38A/view?usp=drive_web>

2020년 2월 6일 (목) 오전 9:15, Laurent Cozic <notifications@github.com>님이 작성:

**Comment by laurent22** [comment]
I don't have access to this file. Please could you attach it directly to the GitHub issue (I think that should work)?

**Comment by tiroring09** [comment]
it is said that github doesn't support this file type unfortunately. 
![image](https://user-images.githubusercontent.com/54842445/73927480-d6320f80-4914-11ea-8f67-a88a6943f12b.png)

Could you please try access the upper link again? I've changed permission option.
Or link below.
https://www.dropbox.com/s/lqh9j8yyt5errky/tiroring09.jex?dl=0

Hope it will work. Thanks.

**Comment by laurent22** [comment]
Thanks, I got it now.

**Comment by tiroring09** [comment]
[Plus] I tested the same experiment on my roommates laptop as well, the whole new & fresh environment(window10/ Joplin 1.0.179/ new notebook). and the result was the same.

(I feel like penpaling with K-pop star, or being spider man sitting next to stark on his van! whoe)

**Comment by bedwardly-down** [comment]
This bug is showing up on Linux too and is matching the issue linked above.
