### ISSUE TITLE
Missing documentation for filesystem sync in the CLI application

### ISSUE THREAD

**Issue by ReekyMarko** [laurent22/joplin#245]
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [x] Terminal

There's absolutely no documentation on how to sync your notes from/to filesystem on the CLI application, not here on GitHub nor in the separate CLI application documentation. I dare say I'm quite experienced on Linux but I couldn't figure it out.

EDIT: I just reread this and thought it might come off as a bit offensive. I meant nothing like that, just trying to improve Joplin by making setting it up easier :smile:

**Comment by fmrtn** [comment]
Try with ` :help config ` :wink:

<hr/>

```
     sync.target           Synchronisation target.                                                                                                                                            
                            The target to synchonise to. Each sync target may have additional parameters which are named as `sync.NUM.NAME` (all documented below).                            
                            Type: Enum.                                                                                                                                                        
                            Possible values: 2 (File system), 3 (OneDrive), 4 (OneDrive Dev (For testing only)), 5 (Nextcloud), 6 (WebDAV).                                                    
                            Default: 3                                                                                                                                                         
                                                                                                                                                                                               
     sync.2.path            Directory to synchronise with (absolute path).                                                                                                                     
                            The path to synchronise with when file system synchronisation is enabled. See `sync.target`.                                                                       
                            Type: string.                
```

**Comment by ReekyMarko** [comment]
Ah thanks! But I still couln't find this anywhere in the docs. I believe I also looked through the help in the application itself and I didn't see any mention of `:help config` there. Not a hundred percent sure though, since I can't have a look right now.

**Comment by fmrtn** [comment]
On README.md in this section https://github.com/laurent22/joplin#terminal-application you can found this link [Joplin Terminal Application Documentation](http://joplin.cozic.net/terminal)

On application if you type ```:help``` you get

> Type `help [command]` for more information about a command; or type `help all` for the complete usage information.
>
> The possible commands are:                                                                                                                                                                     
>                                                                                                                                                                                               
> attach, cat, **config**, cp, done, e2ee, edit, exit, export, geoloc, help, import-enex, mkbook, mknote, mktodo, mv, ren, rmbook, rmnote, search, set, status, sync, tag, todo, undone, version
