### ISSUE TITLE
[Dropbox] Ignore TLS errors & Custom TLS certificates options needed

### ISSUE THREAD

**Issue by jaklan** [laurent22/joplin#2451]
## Environment

Joplin version: 1.0.179
Platform: macOS
OS specifcs: macOS Mojave 10.14.6

## Steps To Reproduce

1. Run affected VPN (e.g. corporate VPN).
2. Try to sync notes.

Describe what you expected to happen:

In a nutshell - for some e.g. corporate network configurations it's not possible to connect to given hosts without specifying additional certs or just ignoring TLS errors. Workaround is already done, but only for WebDAV and Nextcloud - we need exactly the same options for Dropbox and, probably, OneDrive.

## Logfile

```
2020-02-06 02:14:03: "FetchError: request to https://api.dropboxapi.com/2/files/create_folder_v2 failed, reason: self signed certificate in certificate chain
Code: SELF_SIGNED_CERT_IN_CHAIN
FetchError: request to https://api.dropboxapi.com/2/files/create_folder_v2 failed, reason: self signed certificate in certificate chain
```

**Comment by jaklan** [comment]
Actually these settings are unrelated to chosen sync target - they work for all types (e.g. when ignoring TLS errors via WevDAV Advanced Settings, it also works for Dropbox), so the bug is only about not displaying these options in Dropbox/OneNote Advanced Settings.

**Comment by laurent22** [comment]
Isn't it a misconfigured VPN though? Sounds like it's MITM the connection and adding self-signed certificates, which the app should indeed reject.

**Comment by jaklan** [comment]
> Isn't it a misconfigured VPN though? Sounds like it's MITM the connection and adding self-signed certificates, which the app should indeed reject.

Well, I’m not a network specialist, I can just assume there's something weird in a corporate network configurafion.  I've just internally requested to add Dropbox API to the whitelist of domains, but anyway - as for now it's enough to ignore errors / add folder with missing additional certs, which was possible via WebDAV Advanced Settings, but not Dropbox Adv. Settings. Looking at CLI you can see these options are target-agnostic, ao as for now the bug is just about missing options in GUI.
