### ISSUE TITLE
Window cannot be restored from minimized

### ISSUE THREAD

**Issue by ambidexi** [laurent22/joplin#2454]
Opening Joplin the window doesn't appear. Minimizing and restoring the window on the taskbar does not make it reappear. Trying to make maximize to full screen / left side of screen etc. does not help either (Windows key + up / left).

Cannot reproduce but happened multiple times.

Tried downgrading to compatible versions (178, 177), did not resolve the issue.

## Environment

Joplin version: v1.0.179
Platform: Windows
OS specifcs: Windows 10 Pro Build 18362

## Steps To Reproduce

Cannot reproduce intentionally.

Happened multiple times, don't remember how I solved before.
Now realized "C:\Users\USER\AppData\Roaming\Joplin\window-state-prod.json" got corrupted:
```
{"width":166,"height":44,"x":-14224,"y":-14224,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1707,"height":960}}
```
Fixed the `x` and `y` coordinates as `0` restored the window.

## Logfile

Nothing in the logs when opening with the corrupted config.

**Comment by ambidexi** [comment]
see #2476
Still don't understand why the config gets corrupted, as mentioned above.

**Comment by PackElend** [comment]
still valid?

**Comment by ambidexi** [comment]
Same as #2476 
The window can be restored as it is just 0 size. Config corruption still occurs occasionally.

**Comment by PackElend** [comment]
> Config corruption still occurs occasionally

any change to save this on cloud storage or other place where versioning is active, so we may see what change caused the corruption

**Comment by ambidexi** [comment]
I use Win10 Pro and Docker Desktop. If you can suggest Win settings or docker image that can version a folder rigorously, I will try to reproduce the error.
Also I was still on 1.0.179, now upgrading.

**Comment by PackElend** [comment]
> Also I was still on 1.0.179, now upgrading.

than let's wait if situation improves

**Comment by ambidexi** [comment]
Did not get this problem in the updated version, thanks.
