### ISSUE TITLE
MD files not being generated when using export fuction, single files or bulk number of. (Mac Desktop.)

### ISSUE THREAD

**Issue by tirrip** [laurent22/joplin#2455]
When using the export function on one note present in Joplin, to "MD - Markdown Format", it creates "_resources" folder (I chose my Documents folder) with no MD file present. The same occurs when using the export function on several (more than one) number of notes. A "_resources" folder is created, with no files present inside. When trying the newly created "_resources" folder, it creates a "_resources" folder within that, with no MD files present.

## Environment

Joplin version: 1.0.179
Platform: macOS
OS specifcs: macos mojave version 10.14.6

## Steps To Reproduce

1. Right Click on one file.
2. Choose Export/ MD - Markdown format
3. Choose Documents folder.
4. Check "_resources" created.
5. Nothing present in "_resources" folder.

Describe what you expected to happen:

One markdown format file created, or a multiple number of markdown files, as according to the ones chosen for export.

## Logfile

Attached log.txt when duplicating action, export one note to MD, export multiple notes to MD.
[log.txt](https://github.com/laurent22/joplin/files/4166991/log.txt)

**Comment by bedwardly-down** [comment]
This bug is present on Windows 10 and is probably a duplicate: #2449
