### ISSUE TITLE
Wrong display of pipe in code formatting

### ISSUE THREAD

**Issue by Spansky** [laurent22/joplin#2458]
Following markup...

```
Col 1 | Col 2
 ------|-------
```Test\|Test```|Test
```

... is displayed like this in Joplin:
![image](https://user-images.githubusercontent.com/5704072/73997189-c3611e80-4998-11ea-9761-fb6496d27a82.png)
,but it should be displayed like this (Github):
![image](https://user-images.githubusercontent.com/5704072/73997231-db38a280-4998-11ea-8ad2-dd6aa8ae460b.png)

## Environment

Joplin version:
Platform: macOS 10.15.3
OS specifcs:

## Steps To Reproduce

1. Type in a new joplin note

```
Col 1 | Col 2
------|-------
```Test\|Test```|Test
```

2. Check the render

Describe what you expected to happen:
![image](https://user-images.githubusercontent.com/5704072/73997231-db38a280-4998-11ea-8ad2-dd6aa8ae460b.png)

## Logfile
no logfile

**Comment by Spansky** [comment]
One more thing: In Joplin 1.0.175 it was OK to put the | symbol unescaped into a code section. No issues. The table looked good, the code looked good.

**Comment by tessus** [comment]
You use the wrong code formatting. 3 backticks are used for code blocks and start at the beginning of a line followed by the language (to highlight) and a newline. The last 3 backticks are on a separate line gain.

You have to use a single backtick. 

Pease check the markdown specs before reporting a bug.
