### ISSUE TITLE
emacs key binding, cannot toggle layout with keyboard 

### ISSUE THREAD

**Issue by whudwl** [laurent22/joplin#2459]
Reproduce the issue:
1. go to options, general section 
2. switch to emacs keyboard mode.  
3. open a note, try to use CTRL+L to toggle layout.  it doesn't work.  

version:1.0.179 
OS: windows 10

**Comment by tessus** [comment]
If Ctrl+L has a meaning in Emacs, it won't work. The Emacs key bindings override everything else. This was known from the beginning and accepted as a drawback for using those keyboard modes.
How would you ever solve this problem?

Maybe @ShaneKilkelly who implemented this has an idea. I'm sorry, but we won't be able to fix this.
