### ISSUE TITLE
Linux AppImage not loading ERROR :GL_INVALID_OPERATION

### ISSUE THREAD

**Issue by ruben-mar** [laurent22/joplin#2460]
[log.txt](https://github.com/laurent22/joplin/files/4170117/log.txt)

I run the AppImage but the window is not showing in the desktop.

## Environment

Joplin version: .joplin/VERSION 1.0.179
Platform: Linux
OS specifcs: Ubuntu 19.10  kernel 5.3.0-29-generic

## Steps To Reproduce

1. At the shell `$ ~/.joplin/Joplin.AppImage`

2. The output is
```
[8763:0207/102854.466401:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
(node:8777) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:8777) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information

```
Clicking on the icon on Ubuntu's desktop opens up a window of the Ubuntu Software application with the warning 
> Unable to find "window:169"

Describe what you expected to happen:
The GUI is made available and the window displaying the notes.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/4170131/log.txt)

**Comment by bedwardly-down** [comment]
> [5008:0208/214103.054597:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
(node:5023) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:5023) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
[5008:0208/214110.465966:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[5008:0208/214111.534638:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command

I get a similar error too upon starting up. Although, I have noticed that this error happens with other apps too like my browser (Brave). It seems to show up with other apps that use Chromium as their backend.

**Comment by ruben-mar** [comment]
The issue persisted for version 1.0.179. It is not happening with version 1.0.193.

**Comment by takov751** [comment]
Hello there.

Joplin version: Joplin-1.0.201.AppImage 
Platform: Linux
OS specifcs: Ubuntu 20.04 5.4.0-28-generic

So far no crash at this point only warns about a deprecate function and this error message still persists  and its spawns over the terminal every time you open any of the  menu bar items.

**Comment by neural-oD** [comment]
Hi, I'm getting the same issue. I'm on Manjaro Linux (Arch Based).
I really do love Joplin, but this is making it unusable.

I came across another article regarding this issue, and I don't know the build environment with Joplin, but assume it's electron?
On the other issue - it was mentioned running electron with the flag: 
`electron --disable-gpu /path/to/the/app`
I would assume that we could probably mention this flag somewhere within the Joplin build, then build it from source with that flag??
