### ISSUE TITLE
Make "All Notes" Section on Desktop

### ISSUE THREAD

**Issue by BengaloBongali** [laurent22/joplin#2461]
On Android, there is an "All Notes", "Alle Notizen" section. This is missing on Desktop (Mac). Especially when wanting to search in all notes, this is essential. I have to search in each notebook now, if I'm not sure, where I put it or I only use one notebook for ease of use.

## Environment

Joplin version: 1.0.179
Platform: Mac OS
OS specifcs: 10.12.6

## Steps To Reproduce

1. Open Joplin
2. See there is no "All Notes" section

Describe what you expected to happen:
An "All Notes" section like on Android

Apart from search and the missing all notes, Joplin is awesome with Syncthing.

**Comment by tessus** [comment]
⚠️
The GitHub issue tracker is for **bugs** and **security issues** ONLY. For feature requests and support, please use the forum:
https://discourse.joplinapp.org/
⚠️

**Comment by BengaloBongali** [comment]
Did, thanks!

**Comment by tessus** [comment]
Thanks for opening it in the forum.
