### ISSUE TITLE
edit menu items and shortcuts not disabled in preview mode

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#2467]
## Environment

Joplin version: 1.0.179 (and git master 639712c003b09d5652b5e25a681e93f6a29474f9)
Platform: all desktop apps
OS specifcs: macOS (but irrelevant)

## Steps To Reproduce

1. Set the layout to `Preview only`
2. Open `Edit` nenu or use a shortcut like `Cmd+B` 

Result: text is added to the top of the note, even though I shouldn't be able to edit/add text in preview mode

Describe what you expected to happen:

Certain commands should be disabled in preview mode (the same way as the toolbar buttons are removed).

When multiple notes are selected these commands are disabled. See function `updateMenuItemStates` in `app.js`.

This is a great first issue to start with, if you want to participate in the upcoming GSoC 2020.

**Comment by coderrsid** [comment]
Hey @tessus, so i just want to confirm 1 query related to this issue
![image](https://user-images.githubusercontent.com/35633575/74266567-809d9e80-4d2a-11ea-80cc-b845ece4c808.png)


As you said, "strongtext" & "emphasizedtext is added on top of the note when i used Cmd+B(Bold) and

**Comment by coderrsid** [comment]
Hey @tessus , are we talking about this "strongtext" and "emphasizedtext" added in note content even in preview only layout here when i used Cmd+B and Cmd+I respectively?

![image](https://user-images.githubusercontent.com/35633575/74266813-f0138e00-4d2a-11ea-8e29-935b2d2a673f.png)
![image](https://user-images.githubusercontent.com/35633575/74266851-fe61aa00-4d2a-11ea-95e7-6a41e792a5fc.png)

**Comment by tessus** [comment]
I was talking about all actions that can be taken in th editor. But yes, this is what happens when you can still trigger actions in the preview only mode. Those are only 2 examples though.

Create an empty notebook or select multibple notes. Then click on the menu item `Edit`:

<img width="232" alt="image" src="https://user-images.githubusercontent.com/223439/74278694-9dfd4900-4ce7-11ea-91a6-7a2fd11d8eb7.png">

Apparently you haven't check the function `updateMenuItemStates` in `app.js`. It shoes which menu item (thus functions) are disabled.

**Comment by coderrsid** [comment]
Yeah i saw the function, but i have a query that which one of the case is preview only mode? Viewer, Editor or Both? I guess it's Viewer. But just want to confirm.

![image](https://user-images.githubusercontent.com/35633575/74348895-6a9ae700-4dd9-11ea-8f8a-62b62e024b3d.png)

**Comment by coderrsid** [comment]
and one more thing is that after i built the application and made this changes .. do i need to relaunch the electron client ./run.sh or will it render the changes itself? coz changes made by me is not shown i guess.

**Comment by tessus** [comment]
`viewer` should be the correct one. But the code block you've pasted only defines which combinations will be allowed when using `switch layout (Cmd+L`.

I'm not sure what you mean by _after i built the application_. You don't have to do a `npm run dist`. During the development you only have to run the script `./run.sh`. And you have to run it every time you make a code change.

**Comment by coderrsid** [comment]
Thank you so much @tessus. I've started getting the hang of the codebase. Here in the `generalMiddleware() `function, on note and folder select and for devtools,` updatedMenuItemStates()` is called. We have to similarly call `updatedMenuItemStates()` from the `if(NOTE_VISIBLE_PANES_TOGGLE..)`too right?

![image](https://user-images.githubusercontent.com/35633575/74436209-084eee80-4e8c-11ea-8a4a-bc25d1b6e015.png)

**Comment by tessus** [comment]
Sorry, I don't have the code in front of me. The pasted code is too less to be sure, but I think it could work.
But hey, just try it out. You'll see, whether it works or not. No harm done. Just play around.

**Comment by tessus** [comment]
@coderrsid any update?

**Comment by Runo-saduwa** [comment]
Hello @tessus , I started working on this issue a few hours ago and after looking at `updateMenuItemStates` Function I came up with the exact code needed to get this bug squashed, but my problem is where to insert the code exactly, I know after some extra hours of dabbling with the codebase I might land at the solution but in order to save time can you kindly point out areas in the `app.js` I should keep my focus on to know where to modify.

**Comment by coderrsid** [comment]
Hey @tessus Sorry to reply late i was a little busy. I tried changing the code and calling `updateMenuItemStates` function from the `generalMiddleware` if the case of `NOTES_VISIBLE_PANES_TOGGLE` similarly as it is called upon if the case is `NOTES_SELECT` AND `NOTE_DEVTOOLS_TOGGLE`. But i see no changes. The real problem is i am not able to understand the `updateMenuItemStates` function. Can you just elaborate a little how the menu is getting updated here. Below is the code.

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/35633575/74806613-6d7f6580-530c-11ea-9665-91ef2c14afea.png">

**Comment by Runo-saduwa** [comment]
Hey there @coderrsid , the function is called anytime a note is clicked upon or when a notebook is opened, it takes the state of the application as an argument and tries to get the exact note the user selected using `state.selectedNoteIds` , then the for loop simply loops over the menu items and disables them based on if there is no note found or no markdown. 

That’s basically a brief summary, @tessus might want to give a more elaborate explanation but that’s the major part of the story

**Comment by coderrsid** [comment]
Thanks @Runo-saduwa, i figure out this too. But not the exact meaning of 
<img width="908" alt="image" src="https://user-images.githubusercontent.com/35633575/74809519-585a0500-5313-11ea-96f2-e1518bb8a116.png">
