### ISSUE TITLE
find a good geolocation service (https)

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#2469]
Joplin curently uses ip-api.com (80) as the geolocation service. Additionally it uses api.ipify.org (443) to retrieve the IP address, which is then fed into ip-api.com (80).

There were reports that the geolocation service does not always provide accurate results.

This change involves 2 parts:

- use a more accurate API, which is free and uses https
- maybe get rid of the separate request to api.ipify.org (443)

The files involved are:

```
ReactNativeClient/lib/geolocation-node.js
ReactNativeClient/lib/net-utils.js
ReactNativeClient/lib/shim.js
```

**Comment by tessus** [comment]
@laurent22 I've been looking into this and here are the results:

`ip-api.com` is actually quite precise. I suspect the person who had an issue either used a VPN or there was a glitch in the geo database. However, I'm really concerned about unencrypted traffic on port 80. To use SSL with that provider one has to buy a pro account, which we couldn't use in Joplin anyway, because the API key would be for everyone to read in the code.

I found another provider that looks promising: `freegeoip.app` They allow 15,000 request per hour. Thus, even if 150 people behind a company LAN were to use Joplin, they would have to create 100 new notes per hour to reach the limit. They also support SSL out of the box.

I suggest the following: A setting where people can choose between `freegeoip.app (443)` (default) and `ip-api.com (80)`.
While the setting is not absolutely necessary, it makes it easier to add or replace a geo provider in the future. (e.g. the returned json uses different keys for longitude and latitude).

Please let me know what you think. I can either get this done tomorrow or on Monday.

**Comment by tessus** [comment]
@laurent22 what's the plan? Is it ok to create a setting for the geo location service (it would only show up, when people check the `Save geo-location with notes`.

**Comment by RizkyRajitha** [comment]
hi @tessus , 
i did some research in this issue .
i found another good Geo location service i used . it give 1500 requests per day , which will not be enough i think in this requirement.
https://ipdata.co/pricing.html

i checked free geo api and i think it is better . 

and also there is a good alternative for http://api.ipify.org/ 

which has https 
https://ipv4.icanhazip.com/

how can i contribute to this .
thank you

**Comment by tessus** [comment]
Thanks for looking into this as well. There's already a PR open, so now it's Laurent's decision how to proceed. You can check out the discussion at #2503
