### ISSUE TITLE
location displayed incorrectly in note properties

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#2470]
The coordinates `40.712776, -74.005974` are shown as `40° 42' 45"' 74° 0' 21"'`, which is not only inprecise, but also wrong. Instead it should show the following:

`40° 42' 45.9936"' N, 74° 0' 21.5064" W`

While the number of decimals places can be discussed (2 or 3 should be fine as well), the **N S W E** designations are essential!

This is a great first issue to start with, if you want to participate in the upcoming GSoC 2020.

**Comment by anjulalk** [comment]
Hi, can I work on this?

**Comment by tessus** [comment]
Sure, please go ahead.
