### ISSUE TITLE
problem with cyrilic fonts in text editor

### ISSUE THREAD

**Issue by handleman** [laurent22/joplin#2471]
## Environment

Joplin version: 1.0.179 (prod, darwin)
Platform: MacOs Catalina 10.15.3

## Steps To Reproduce

1. switch to cyrilic font in your operation system ( in my case Russian) 
2. try to  write some text with spaces - several paragraphs of text.
3. You will easily note wrong behaviour: wrong places for "space" character and wrong text wrapping. 

For example when you are trying to split one word to next line you will note that it would be divided in wrong random letter - doesent matter where exactly cursor was at that time. 

### Describe what you expected to happen:

I am expecting normal behavior of text editor, as it was in versions prior to 1.0.178. So it is a kind of regression bug in latest version.

**Comment by laurent22** [comment]
As I can't write in cyrilic, could you please post an example that shows the problem?

Please note that the text editor only supports monospace fonts though, so if your system forces a non monospace font in Joplin it won't work. The only way might be to specify a cyrilic monospace font in Joplin settings.

**Comment by dbogdanov** [comment]
The helper text in the settings for the font is misleading: "If the font is incorrect or empty, it will default to a generic monospace font." so it appears that this default did not not apply to cyrilic, only latin. How do I setup a monospace cyrilic font?

**Comment by shartf** [comment]
@dbogdanov On macOS, setting Monaco as font seems to solve the problem. Iosevka seems to work, too. A possibility to select fonts in Joplin's preferences would be of great help, since a wrong Font name will cause fallback to default which cannot handle cyrillic text.

**Comment by repman** [comment]
https://github.com/laurent22/joplin/issues/2587
I see that the update 1.0.193 has been released , but it also does not solve the problem. Did you manage to understand and find the bug?

How do I change the font to Monaco?

**Comment by laurent22** [comment]
Settings -> Appearance, then set the font family to "Monaco". Also makes sure this font is installed in your system.

This bug is because Ace Editor only supports monospace font so we cannot fix it ourselves.
