### ISSUE TITLE
Electron deprecation

### ISSUE THREAD

**Issue by kakila** [laurent22/joplin#2473]
The following output is produced by starting from command line
```
(node:14891) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:14891) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information

```
## Environment

Joplin version: Revision: 66356d8 (HEAD)
Platform: Linux 
OS specifcs: Ubuntu 19.10

## Steps To Reproduce

1. Install using the bash script 
``
wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash
``
2. Start using 
```
~/.joplin/Joplin.AppImage
```

**Comment by laurent22** [comment]
Not a bug, just a warning.
