### ISSUE TITLE
Joplin 1.0176.2323 and 1.0.179.2330 not display gui when loaded

### ISSUE THREAD

**Issue by garretzou** [laurent22/joplin#2475]
## Environment

Joplin version: 1.0176.2323 and 1.0.179.2330
Platform: Windows 10 Pro
OS specifcs:  17763.973

## Steps To Reproduce

1. Joplin 1.0176.2323 suddenly can't display any gui when the Joplin app starts. 
2. After upgrade it to version 1.0.179.2330, still nothing show up. I found in Win+Tab window, the Joplin window is there, but when select that window, the Joplin window still do not display. 

![image](https://user-images.githubusercontent.com/7679315/74088368-ce1ecf00-4ad0-11ea-8c56-c78bdaa5bb18.png)

Describe what you expected to happen:

How to make Joplin gui work fine?

**Comment by tessus** [comment]
see #2476 
Somebody is workibg on it....
