### ISSUE TITLE
Check and fix window dimensions and position when the application start

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2476]
It happens that the Joplin window, when starting, is off-screen or has invalid dimensions, like 1x1 pixel.

After the app is started (1 or 2 seconds after to make sure it's properly initialised), there should be two checks:

- Check that the window has correct dimensions (for example a minimum of 100x100 pixels)
- Check that the window rectangle is within one of the active screens.

If it's not, the window should be moved to the right location and set to the right dimensions.

You will need to make sure that it works also when the "Start minimised" option is enabled in the settings. In other words, the code shouldn't make the window visible when it should in fact be minimised.

**Comment by daukadolt** [comment]
Can I take on the issue?

**Comment by laurent22** [comment]
Yes please, go ahead.

**Comment by tessus** [comment]
@daukadolt any update? It would be nice to keep us apprised.

**Comment by daukadolt** [comment]
@tessus hi! Sorry for inactivity. Due to force majeure could not start until recently.
I've resolved the window size issue and am currently working on the second issue. I hope to open up a pull request today (UTC+6) or by tomorrow midday.

**Comment by marijawo** [comment]
Can I try this issue?

**Comment by alishamohanty** [comment]
Is the issue still open?

**Comment by tessus** [comment]
Yep, a PR is already available.

**Comment by FlinnBurgess** [comment]
For those experiencing this issue I've realised that when I open joplin there's a very tiny section of the window that appears on the left-hand side of my screen. I was able to expand the window to full size using this.
