### ISSUE TITLE
AppImage for 1.0.67 not available

### ISSUE THREAD

**Issue by fmrtn** [laurent22/joplin#248]
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

In latest release 1.0.67 there isn't AppImage package

https://github.com/laurent22/joplin/releases/tag/v1.0.67

**Comment by laurent22** [comment]
Build is currently failing on Linux due to this issue - https://github.com/electron-userland/electron-builder/issues/2599

**Comment by laurent22** [comment]
Fixed in https://github.com/develar/app-builder/commit/7079542b8359bb5860bb0c54d9de4819ccebf213
