### ISSUE TITLE
Problem with non-western texts

### ISSUE THREAD

**Issue by sciurius** [laurent22/joplin#2483]
Joplin has problems handling non-western texts like Devanagari.

This is actually surprising since most modern toolkits support this. Most programs using these toolkits support this, even classic tools like vim and Emacs do it right.

![scrot20200210094837](https://user-images.githubusercontent.com/1118804/74134703-48437680-4beb-11ea-8110-5954f0dfe2dc.png)

The image shows the Joplin edit and display views. Note the text following "Also" . This should look like तमाङ्ग, as can be seen in yellow window at the right (GNU Emacs).

## Environment

Joplin version: 1.0.179
Platform: Linux
OS specifcs: Fedora 29

**Comment by amitsin6h** [comment]
@sciurius I don't see this as a problem as the both words have same meaning also it can be written both the ways so its perfectly fine

**Comment by sciurius** [comment]
I have been told otherwise but I am the first to admit that this is far beyond my realm of expertise.
