### ISSUE TITLE
[feature request] todo.txt for todo notes there is parser available

### ISSUE THREAD

**Issue by pcause** [laurent22/joplin#2484]
The todo's are currently pretty basic.  I'd like to suggest you support todo.txt format for todos.  There is a javascript parser:

(https://github.com/roufamatic/todo-txt-js)

with apis.  You can make the contexts, priority, and projects all joplin tags.    the due date can be an alarm.  lots of folks use todo.txt and i think this would be a nice step forward.  you cna make it an option to use todo.txt or your existing format for dotos.

**Comment by laurent22** [comment]
For feature request, please use the forum.

**Comment by stefan2904** [comment]
here is the mentioned forum entry: https://discourse.joplinapp.org/t/todo-txt/612
