### ISSUE TITLE
Up and down arrow keys don't work

### ISSUE THREAD

**Issue by aardvarkk** [laurent22/joplin#2486]
The up and down arrow keys don't seem to do anything. I'm a first time user so maybe I'm crazy here? I can't scroll through the console output to read the help output. I'm able to open and close the console, call help, and exit, but I'm trying to look up the config info so I can sync to my filesystem and there doesn't seem to be a way to read through the config options from start to finish because I can't scroll in the console output.

## Environment

Joplin version: 1.0.153
Platform: CLI Client within iTerm2 v3.3.8 and Terminal v2.10 (443)
OS specifcs: macOS 10.15.3 

I should also mention I'm using an Ergodox EZ keyboard (and the letter keys are in Dvorak layout), but I haven't had any trouble with my arrow keys in any other application.

## Steps To Reproduce

1. Type `:help config` in the client
2. Try to scroll around -- nothing happens

Describe what you expected to happen:

The `:help config` output in the console exceeds the visible bounds of the console. I would expect it to fill the console and then act like `less` or something where I could scroll through the output.

**Comment by aardvarkk** [comment]
It seems like `UP` and `DOWN` do work correctly when I am moving between notebooks and notes, but I still don't know how to show the whole console output to know about all of the config options.

**Comment by tessus** [comment]
This is a user question and should be posted to the forum. 

If you have a lot of output in the console, go to the console (3x `Tab`) and you can use the arrow keys and fn+up and fn+down.

**Comment by aardvarkk** [comment]
Thanks for the tip -- the problem was that I assumed when the console was open that it was the "active window". Hitting tab a bunch of times to get the focus there made the arrow keys work as expected. Thanks again!
