### ISSUE TITLE
Desktop launcher not properly created for Linux builds

### ISSUE THREAD

**Issue by ma-sadeghi** [laurent22/joplin#2494]
## Environment

Joplin version: 1.0.179
Platform: Ubuntu 19.10

## Steps To Reproduce

1. Install Jopling using:
```
wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash
```

Describe what you expected to happen:
I expected that a desktop icon be created, and indeed it was created. But, an IP address (X.X.X.X) was appended to the last line of the `.deskop` file, which I had to manually remove with a text editor for the launcher to work.

**Comment by tessus** [comment]
fixed in ca5d6c5cfed51873b64d8a310777b20ded32c309 literally a few seconds ago
