### ISSUE TITLE
Android: Image with http-url cannot be rendered

### ISSUE THREAD

**Issue by licheedev** [laurent22/joplin#2496]
## Environment

Joplin version:  joplin-v1.0.318(64-bit)
Platform: Android
OS specifcs: Android 10 (Redmi K20 Pro-MIUI11.0.5)

## Steps To Reproduce
It just cannot show the image on Android like this:
![mark](http://notefiles.licheedev.com/pics/20200212/JPIFGHm2jwdV.jpg?imageslim)

The markdown content is:
```
![中文版](http://notefiles.licheedev.com/pics/20200212/RTYT0iIlSvKr.jpg?imageslim)
```

.

**Comment by amitsin6h** [comment]
I am working on this issue.

**Comment by rankaiyx** [comment]
> I have started to work on this issue.

Reason and solutions may be here:
Cleartext HTTP traffic not permitted.
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by rankaiyx** [comment]
> I have started to work on this issue.

Maybe the same reason
https://github.com/laurent22/joplin/issues/2517

**Comment by amitsin6h** [comment]
![WhatsApp Image 2020-02-22 at 8 05 56 AM](https://user-images.githubusercontent.com/12906090/75084968-37c7c000-554a-11ea-8b3a-daf2355d66d2.jpeg)


@rankaiyx @licheedev could you confirm about this issue again, as I don't see any problem rendering the image in android

**Comment by licheedev** [comment]
@amitsin6h
My phone is Android 10. 
All http-images can be rendered on desktop-editon, but failed on Android.
![mark](http://notefiles.licheedev.com/pics/20200222/5XL5SfXSIBcd.jpg?imageslim)

> Starting with Android 9 (API level 28), cleartext support is disabled by default
https://developer.android.com/training/articles/security-config.html
https://developer.android.com/guide/topics/manifest/application-element#usesCleartextTraffic

Add `android:usesCleartextTraffic="true"` on <application/> tag can solve this problem.

**Comment by amitsin6h** [comment]
@licheedev ok thanks for your reply. I will look after it

**Comment by rankaiyx** [comment]
> @licheedev ok thanks for your reply. I will look after it
I would appreciate it if you could fix this issue:
https://github.com/laurent22/joplin/issues/2517

**Comment by gitknd** [comment]
same here with http and cleartext issue on android10 since a few days.
switching to https resolve in an error playing any video files which worked before with http connection
