### ISSUE TITLE
Export all chapters of nootbook to single PDF file + support PlantUML

### ISSUE THREAD

**Issue by s1ng0c** [laurent22/joplin#2501]
It would nice to have such as feature which allow user to export notebook to single PDF file (by merge all chapters to single markdown file -> render -> export), and with custom header/footer is so nice.

Additional, with PlantUML integrated will make **Joplin** to be the  best for technical documentation writer.

## Environment

Joplin version:
Platform:
OS specifcs:
- All

**Comment by tessus** [comment]
Feature requests are disussed on the forum. Mermaid was just added and will be available in the next release. As for the other feature, @mic704b just added a commit to export a notebook to several PDF files. Combining them is another story.
