### ISSUE TITLE
Having Install Issues

### ISSUE THREAD

**Issue by gregory-lum** [laurent22/joplin#2504]
**I'm running Arch (Linux noob) and haven't had any issues setting up my system that I've been running for six months now. When I try install joplin either cloning in or with an AUR helper I keep getting the same error. This is the output:**

:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 1]  joplin-1.0.179-1

  1 joplin                                   (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> a
:: Deleting (1/1): /home/greg/.cache/yay/joplin
:: Downloaded PKGBUILD (1/1): joplin
  1 joplin                                   (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> n
:: Parsing SRCINFO (1/1): joplin
==> Making package: joplin 1.0.179-1 (Thu Feb 13 21:50:17 2020)
==> Retrieving sources...
  -> Found joplin.desktop
  -> Found joplin-desktop.sh
  -> Found joplin.sh
  -> Downloading joplin-1.0.179.zip...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   123    0   123    0     0    266      0 --:--:-- --:--:-- --:--:--   266
100 22.6M    0 22.6M    0     0  7902k      0 --:--:--  0:00:02 --:--:-- 9464k
==> Validating source files with sha256sums...
    joplin.desktop ... Passed
    joplin-desktop.sh ... Passed
    joplin.sh ... Passed
    joplin-1.0.179.zip ... Passed
==> Making package: joplin 1.0.179-1 (Thu Feb 13 21:50:21 2020)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found joplin.desktop
  -> Found joplin-desktop.sh
  -> Found joplin.sh
  -> Found joplin-1.0.179.zip
==> Validating source files with sha256sums...
    joplin.desktop ... Passed
    joplin-desktop.sh ... Passed
    joplin.sh ... Passed
    joplin-1.0.179.zip ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting joplin-1.0.179.zip with bsdtar
bsdtar: Failed to set default locale
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Pathname cannot be converted from UTF-8 to current locale.
bsdtar: Archive entry has empty or unreadable filename ... skipping.
bsdtar: Error exit delayed from previous errors.
==> ERROR: Failed to extract joplin-1.0.179.zip
    Aborting...
Error making: joplin

**When I check my _locale_ output I get:**

Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8

**I've checked everything on the Wiki and my locale appears to be properly generated (I've tried regenerating locale, export LC_ALL, as well as checking the config file, which on the Wiki are all potential errors but doesn't seem to be an issue here). Again, I have been running this system for 6+ months and haven't had any other package install issues, so I'm at a loss. I'm sure it's probably a quick fix due to my user error, but need some help in identifying potential issues. **

**Comment by tessus** [comment]
👉 Please follow one of these issue templates:
- https://github.com/laurent22/joplin/issues/new/choose

⚠️
The GitHub issue tracker is for **bugs** and **security issues** ONLY. For feature requests and support, please use the forum:
https://discourse.joplinapp.org/
⚠️

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.
