### ISSUE TITLE
Sandbox helper binary not configured correctly. Linux, Parrot OS

### ISSUE THREAD

**Issue by VasilyKaiser** [laurent22/joplin#2505]
## Environment

Joplin version: 1.0.179
Platform: Linux
OS specifcs: Linux parrot 5.4.0-3parrot1-amd64

## Steps To Reproduce

1. Download AppImage from site or using CLI
2. Run from command line, otherwise you'll see nothing.

Describe what you expected to happen: Open App Window.

## Logfile
![Screenshot_20200214_063357](https://user-images.githubusercontent.com/50267052/74527565-0f114c00-4ef4-11ea-990d-17e16c1ba8c1.png)

**Comment by tessus** [comment]
Duplictate of  #2246
