### ISSUE TITLE
webdav sync error (possibly related to %40 in url ?)

### ISSUE THREAD

**Issue by naspert** [laurent22/joplin#2506]
I tried the webdav sync using (on owncloud, hosted by 'switch' https://help.switch.ch/drive/faq/) 
As per switchdrive settings, the webdav base url for an account is: 
https://drive.switch.ch/remote.php/dav/files/user%40host.com/
(I replaced my email by `user@host.com` -> in url becomes `user%40host.com`)
and got the following error:

```Completed: 14/02/2020 17:13
Last error: Error: href /remote.php/dav/files/user@host.com/joplin/.lock/ not in baseUrl https://drive.switch.ch/remote.php/dav/files/user%40host.com/joplin nor relativeBaseUrl /remote.php/dav/files/user%40host.com/joplin
```
And no files are synced. 

## Environment

Joplin version: 1.0.179
Platform: Windows and Android

## Steps To Reproduce

1. Configure joplin to sync using webdav with a url containing '%40'
2. Test sync (succeeds)
3. Actual sync (fails

Describe what you expected to happen:

Proper sync

## Logfile
[log.txt](https://github.com/laurent22/joplin/files/4205448/log.txt)

**Comment by tessus** [comment]
Joplin does not support webdav urls with `%`. Use the `@` instead.

https://discourse.joplinapp.org/t/bug-here-or-in-my-webdav-not-syncing-when-40-in-url/5819?u=tessus

**Comment by naspert** [comment]
aha yes that fixes the problem (but this is an invalid url, help section of switchdrive explicitely warns about it :/ )
Thanks for the link (did not now about the other bug tracker).

**Comment by tessus** [comment]
Yea, well, it all depends on the SW. These days we can use unicode characters in URLs, so why not a @. Either way, the webdav module we use apparently can't handle encoded URLs, so you can follow up with them upstream, we certainly won't fix it.

**Comment by naspert** [comment]
using unicode characters in URL is certainly one of the worst possible ideas (phishing capabilities with almost identical characters...). Just saying :)

**Comment by tessus** [comment]
@naspert I agree. It was not my idea to allow unicode characters in domain names. This is ICANN's fault.

The problem you are hitting has either to do with WebDAV itself or the module we are using. It's not something we can fix.
