### ISSUE TITLE
Firefox web clipper, where can I get it from?

### ISSUE THREAD

**Issue by habamax** [laurent22/joplin#2510]
I did press the button:

![image](https://user-images.githubusercontent.com/234774/74586602-39e5c800-4ffa-11ea-8c14-9ae6e14ec9cc.png)

But there there is no firefox extention:
![image](https://user-images.githubusercontent.com/234774/74586594-25a1cb00-4ffa-11ea-95c1-6c0d61a790b2.png)

**Comment by habamax** [comment]
@tessus is this a widely known not an issue? Sorry, about the question then.

**Comment by tessus** [comment]
there were like 5 topics about this on the forum. and the web clipper is already available again.

**Comment by tessus** [comment]
also. you totally ignored the template. I'd call that ignorant.

**Comment by habamax** [comment]
Thank you. I got a notification issue is closed and no info about resolution. Thus my question.

I did search GitHub issues before asking.

**Comment by habamax** [comment]
> also. you totally ignored the template. I'd call that ignorant.

Well, call it whatever u like, i am out.

**Comment by tessus** [comment]
How would you call it, if someone ignored this:

⚠🚨⛔ The issue tracker is not for questions. ⛔🚨⚠

As it happens, support requests that are created as issues are likely to be closed. We want to make sure you are able to find the help you seek.

## Questions and Help

Please read the [documentation](https://joplinapp.org/) and [FAQ](https://joplinapp.org/faq/) first.

### https://discourse.joplinapp.org/

If you have still questions related to Joplin, please open a topic in the [forum](https://discourse.joplinapp.org/).
You can use your GitHub credentials to login to the forum.

## Links

- Documentation: https://joplinapp.org
- FAQ: https://joplinapp.org/faq/
- Forum: https://discourse.joplinapp.org
- How to enable end-to-end encryption: https://joplinapp.org/e2ee/
- API documentation: https://joplinapp.org/api/
- How to enable debug mode: https://joplinapp.org/debugging/

**Comment by habamax** [comment]
Sorry, I didn't pay attention to the template.

Don't worry, no more issues from me.

**Comment by tessus** [comment]
You can open as many questions as you like in the forum (or reproducible bugs on github). The issue tracker is for bugs only. The project has reached a size where we have to move questions off the tracker. And it certainly doesn't help when people ignore the templates again and again.

Please don't think that we don't want to help you, because that's not true.

**Comment by habamax** [comment]
> You can open as many questions as you like in the forum (or reproducible bugs on github). The issue tracker is for bugs only. The project has reached a size where we have to move questions off the tracker. And it certainly doesn't help when people ignore the templates again and again.

I got your point, and again I am sorry about that.

I will use forum for the questions, not problem.

> Please don't think that we don't want to help you, because that's not true.

Thanks for clarification!

**Comment by tessus** [comment]
> I will use forum for the questions, not problem.

Thank you. Btw, you can use your gh credentials to log into the forum.
