### ISSUE TITLE
Android accents path Webdav

### ISSUE THREAD

**Issue by cayenne17** [laurent22/joplin#2511]
## Environment
Joplin version:1.0.316
Platform:android
OS specifcs:android 8

## Steps To Reproduce

Hello,
When the webdav path contains one or more accents (éàèç), it puts me "Not a valid URL"
![image](https://user-images.githubusercontent.com/47927025/74593527-66b2d300-502c-11ea-9a28-ffe915387332.png)

**Comment by bedwardly-down** [comment]
Is there any way you could test using `\` before each accented character? That might solve the issue.

**Comment by cayenne17** [comment]
Hello, I just tested adding an "\" before each accent and I have the same mistake.
![Screenshot_20200303-184843](https://user-images.githubusercontent.com/47927025/75804405-2ec3c380-5d80-11ea-859d-23aea5333ab5.png)

**Comment by bedwardly-down** [comment]
Why'd you choose using quotation marks? My suggestion in many apps forces string parsers to read characters as they are.

**Comment by cayenne17** [comment]
I hadn't checked the display

**Comment by bedwardly-down** [comment]
Thanks. For testing that. We'll need to wait until someone that knows more about this comes here and checks it. I can't currently help beyond this.

**Comment by cayenne17** [comment]
Hello, the problem is still present even with the latest version (1.0.327)

**Comment by cayenne17** [comment]
Hello, the problem is still present even with the latest version (1.0.329)

**Comment by cayenne17** [comment]
Hello, the problem is still present even with the latest version
