### ISSUE TITLE
Syntax highlighting wrong when line starts with '*'

### ISSUE THREAD

**Issue by AlphaKoder** [laurent22/joplin#2527]
Text beginning with an asterisk ('*') is not highlighted correctly when a bolded word exists on the line: For example:
`*.py files usually contain **python** source code.`
In the above example, the text before the word "python" is highlighted instead of the bolded word "python", as shown in the image below. The markdown text is rendered correctly, though.

![image](https://user-images.githubusercontent.com/18623097/74865241-d66fd900-531e-11ea-8c65-8f4594a66ee7.png)

## Environment

Joplin version: 1.0.179
Platform: macOS
OS specifics: macOS Sierra 10.12.6

## Steps To Reproduce

1. Create a new note
2. Enter the text `*.py files usually contain **python** source code.`

Describe what you expected to happen:

I expected the text before the word "python" to not be highlighted (normal), and for the bolded word "python" to be highlighted.

**Comment by tessus** [comment]
This is normal and not a bug, because `*` is the start of an emphasised text in markdown.

The only way around this is to encapsulate it:

```
`*.py` files usually contain **python** source code.
```

**Comment by laurent22** [comment]
`*` is indeed reserved Markdown character so you either need to escape it or quote it.
