### ISSUE TITLE
integral symbol not exported properly

### ISSUE THREAD

**Issue by superfreeman1989** [laurent22/joplin#2528]
On windows, the integral symbol is not exported properly.
When exported to pdf or html, sometimes it's missing, sometimes it becomes smaller:
![2020-02-19 15_48_29-Tests](https://user-images.githubusercontent.com/15226945/74874839-5736d100-532f-11ea-887e-c17ee76300c9.png)
![2020-02-19 15_48_17-test2 pdf - SumatraPDF](https://user-images.githubusercontent.com/15226945/74874840-57cf6780-532f-11ea-81ce-7e9d8266e7cc.png)

How it properly renders in app:
![2020-02-19 15_48_36-Joplin](https://user-images.githubusercontent.com/15226945/74874881-63bb2980-532f-11ea-8f56-39100167569d.png)

**Comment by laurent22** [comment]
Sometimes? It doesn't always do it?

**Comment by laurent22** [comment]
Also please could you post an example of katex code that can be used to replicate the issue?

**Comment by tessus** [comment]
We added additional katex fonts after 1.0.179, so maybe it's already fixed. (Maybe a different font is used for printing.) Or maybe the `.woff2` font files are not good for printing on Windows.

I can't replicate this on macOS. The PDF is exported perfectly (although I'm using an unreleased version).

@laurent22 
```
$$
f{x} = \int_{-\infty}^\infty \hat f(\xi) e^{2 \pi \xi x} d \xi
$$
```

**Comment by superfreeman1989** [comment]
> Also please could you post an example of katex code that can be used to replicate the issue?

It’s the example in the markdown guide on Joplin site:
$$
f(x) = \int_{-\infty}^\infty
	\hat f(\xi)\,e^{2 \pi i \xi x}
	\,d\xi
$$
I’m on windows and I’m never able to export it correctly.

**Comment by superfreeman1989** [comment]
> Sometimes? It doesn't always do it?

It switches randomly between either too small or missing, but never correct.

**Comment by laurent22** [comment]
The way it prints is that it first load the note and render the note in a hidden window, then print. I think we need to give it a small delay to make sure everything is fully loaded before printing.

**Comment by anjulalk** [comment]
I'm using Windows 10 Pro 1909 Build `18363.657`. I'm unable to reproduce the issue. Above katex code was rendered perfectly in both PDF and HTML. (Screenshot below)
![Integral](https://user-images.githubusercontent.com/26695184/75010200-6e5de780-5431-11ea-91fa-26fb75b65f6d.JPG)

**Comment by anjulalk** [comment]
@superfreeman1989 Which version are you using?

**Comment by superfreeman1989** [comment]
> 
> 
> @superfreeman1989 Which version are you using?

Exact same version as yours.

**Comment by Liuhaai** [comment]
![PDF_output](https://user-images.githubusercontent.com/55118568/75132994-d872c880-568d-11ea-8c48-607f30a536af.jpg)
Here is my PDF export result of the expression from tessus on my windows 10 laptop
`$$
f{x} = \int_{-\infty}^\infty \hat f(\xi) e^{2 \pi \xi x} d \xi
$$`
Actually, I am preparing the application of GSOC of this project. I can have a try on solving this bug as a beginning.

**Comment by laurent22** [comment]
Yes please go ahead and give it a try. My guess is that, after creating invisible window, you might need to wait a second or so to make sure all the fonts are loaded, and then print.

**Comment by Liuhaai** [comment]
> ![PDF_output](https://user-images.githubusercontent.com/55118568/75132994-d872c880-568d-11ea-8c48-607f30a536af.jpg)
> Here is my PDF export result of the expression from @tessus on my windows 10 laptop
> `$$ f{x} = \int_{-\infty}^\infty \hat f(\xi) e^{2 \pi \xi x} d \xi $$`
> 
> Actually, I am preparing the application of GSOC of this project. I can have a try on solving this bug as a beginning.

Suspicious reason: Font(katex_size2) loading failure in Windows
I found that the style of the character f has corrupted in the stage of generating HTML file. 
![image](https://user-images.githubusercontent.com/55118568/75143853-b3408300-56aa-11ea-8435-09dfb83015fe.png)
Compared with good HTML file generated by Mark Text app, I found that the expression will look as the above one if style{font-family:KaTeX_Size2} is commented out. I fixed the corrupted character by using a font loading code from the good html file. The good html file, the corrupted html file, and the font loading code are zipped in the HTML_files.zip. In joplin, pdf file is generated from html file, but I am unsure this is related to the missing character in PDF file. But the font loading bug can be fixed at first. Because I have some courses and projects in the college, the date to commit is not guaranteed. So if someone want to fix it, write some css font loading code in the head part of html file, the html generation function is in NoteText.min.js

[HTML_files.zip](https://github.com/laurent22/joplin/files/4244071/HTML_files.zip)

**Comment by laurent22** [comment]
>  in NoteText.min.js

Please note that this is auto-generated from NoteText.jsx. So if you submit a pull request, please make the changes on the JSX file.

**Comment by Liuhaai** [comment]
> > in NoteText.min.js
> 
> Please note that this is auto-generated from NoteText.jsx. So if you submit a pull request, please make the changes on the JSX file.

Only three KaTeX fonts are found under generated ./pluginAssets/katex/fonts folder. So instead of inserting katex font loading code into html file, your solution might be easier.

**Comment by Liuhaai** [comment]
> > @superfreeman1989 Which version are you using?
> 
> Exact same version as yours.

What version of Joplin you use? I can only reproduce this bug on version 1.0.179 which is downloaded from(https://github.com/laurent22/joplin/releases/download/v1.0.179/Joplin-Setup-1.0.179.exe). However, bug can not be reproduced when starting Joplin with latest compiled github code.

**Comment by superfreeman1989** [comment]
> 
> 
> > > @superfreeman1989 Which version are you using?
> > 
> > 
> > Exact same version as yours.
> 
> What version of Joplin you use? I can only reproduce this bug on version 1.0.179 which is downloaded from(https://github.com/laurent22/joplin/releases/download/v1.0.179/Joplin-Setup-1.0.179.exe). However, bug can not be reproduced when starting Joplin with latest compiled github code.

1.0.179

**Comment by Liuhaai** [comment]
> > > > @superfreeman1989 Which version are you using?
> > > 
> > > 
> > > Exact same version as yours.
> > 
> > 
> > What version of Joplin you use? I can only reproduce this bug on version 1.0.179 which is downloaded from(https://github.com/laurent22/joplin/releases/download/v1.0.179/Joplin-Setup-1.0.179.exe). However, bug can not be reproduced when starting Joplin with latest compiled github code.
> 
> 1.0.179

I build a portable program from latest code (https://drive.google.com/file/d/1yMjc_8h1krFgxbf7vtVlYnxcPgwP2lBm/view?usp=sharing). Could you test on it?

**Comment by laurent22** [comment]
@superfreeman1989, can you replicate this with the latest version 1.0.193?

If it still happens, could you please provide the HTML file that is generated? Also maybe the PDF file but that's harder to inspect.

**Comment by superfreeman1989** [comment]
> 
> 
> @superfreeman1989, can you replicate this with the latest version 1.0.193?
> 
> If it still happens, could you please provide the HTML file that is generated? Also maybe the PDF file but that's harder to inspect.

Working properly now
