### ISSUE TITLE
Sync issues

### ISSUE THREAD

**Issue by jogi4github** [laurent22/joplin#253]
### Operating system

- [x] Windows
- [ ] macOS
- [x] Linux
- [x] Android
- [ ] iOS

### Application

- [x] Desktop
- [x] Mobile
- [ ] Terminal

Hello,

I face sync issues with my nextcloud Joplin setup. After importing lots of notes from evernote (about 1600) the upload sync to my nextcloud drive worked fine. However when starting to change note titles and tag assignments, they are not uploaded to the my nextcloud webdav folder. By checking the database.sqlite file on the system where I did my changes, I'm not able to see my changes in the db file. I have the impression all changes are only present in my local Windows Joplin application.
Do I'm right assuming that the changes should be reflected in the sqlite file? And if yes how can I force Joplin to update that file and start to sync my changes?

Sync status of my windows Joplin app on which I ran the changes:
Synchronisationsstatus (synchronisierte Objekte / gesamte Objekte)
Note: 701/687
Folder: 5/6
Resource: 454/599
Tag: 65/91
NoteTag: 298/409
MasterKey: 0/0
Insgesamt: 1523/1792
 
In Konflikt 0
Zu löschen: 16

**Comment by jogi4github** [comment]
I just recognized that only the tags are not in sync. Neither in the sqlite db file nor on the server nor if I download the files manually from my nextcloud Joplin folder and run a local folder sync agains that folder. All ends up without having the tag assignment changes in sync... Can someone reproduce this issue, or is this problem only present in my environment?

**Comment by laurent22** [comment]
Actually, looking at your stats it seems synchronisation is being interrupted. Could you enable [debug mode](https://github.com/laurent22/joplin/blob/master/README_debugging.md) and let me know if there's any error or warning?

**Comment by jogi4github** [comment]
Again a big thank you for your fast reply and for the hint to the debug mode. To be honest in the meantime I gave up troubleshooting and started everything from the scatch.
1) I reorganized my notes in evernote to meet the restrictions in Joplin 1.0.66 (prod, linux)
 * that new tags are converted to lower case letters
 * that there is no "notebook in notebook" possiblity (in evernote stack notebooks)
 * that there is no sub tag possiblity
 * that there is currently no AND/OR search string concatenated search
2) Created a new empty sync directory on my nextcloud system. This time not on the extrenal drive. Don't know if this makes a difference, but before my Joplin sync folder was located on an external nas which is accessable in nextcloud via external local storage. During my test before I tried to configure Joplin to sync with local storage folder. That folder was synced by the nextcloud client with the nextcloud folder on the external storage. This setup ended in lots of file locked messages during the nextcloud client sync job. Although the file itself was not locked...
3) Reimported the newly organized evernote notes and synced one joplin client in order, one after the other  (Windows, Android, Linux).

Up to now I don't have any sync issues anymore :-). However I would like to know if I can rename tags and note titles in the sqlite db file, without corrupting the sync? This would give me the possibility of batch renaming titles and tags.

**Comment by laurent22** [comment]
Ok good to know it's working now. The issue might have been due to the tag lowercase/uppercase bug, which is fixed in v67, but unfortunately not currently available for Linux.

You can indeed rename the tags directly in the database, however make sure you also set the field `updated_time` (to the current timestamp in milliseconds) to make sure it gets synced afterwards. You could script this using the sqlite command line tool, but I'd definitely create a backup first :-)

The good thing is that the association between notes and tags will be preserved even if you rename the tags, because the link is based on the ID.

**Comment by nr458h** [comment]
I also face sync issues - new notes are not synced and changes don't show up. I tried already to change to "type 1" that didn't work.

When i went into debug mode i found this:

-02T22:21:49,30,"""Reducer action", "SYNC_COMPLETED""
03-02T22:21:49,20,"""Error: PROPFIND 0f9ba6ad7fef44a39cd4799bada1501c.md: client not allowed to access end-to-end encrypted content (Exception OCA\DAV\Connector\Sabre\Exception\Forbidden) (403): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:o="http://owncloud.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\Forbidden</s:exception>
  <s:message>client not allowed to access end-to-end encrypted content</s:message>
  <o:retry xmlns:o="o:">false</o:retry>
  <o:reason xmlns:o="o:">client not allowed to access end-to-end encrypted content</o:reason>
</d:error>

Code: 403
r@index.android.bundle:437:251
i@index.android.bundle:903:5076
index.android.bundle:903:5994
n@index.android.bundle:76:245
index.android.bundle:76:1662
index.android.bundle:76:427
n@index.android.bundle:76:245
r@index.android.bundle:76:502
index.android.bundle:76:619
u@index.android.bundle:74:133
index.android.bundle:74:921
index.android.bundle:24:1784
o@index.android.bundle:24:571
u@index.android.bundle:24:880
callImmediates@index.android.bundle:24:3178
value@index.android.bundle:19:2598
index.android.bundle:19:790
value@index.android.bundle:19:2426
flushedQueue@index.android.bundle:19:760
callFunctionReturnFlushedQueue@index.android.bundle:19:304""
03-02T22:21:49,20,"""There was some errors:""

**Comment by laurent22** [comment]
@nr458h, that seems to be a Nextcloud bug - https://github.com/nextcloud/server/issues/8379
