### ISSUE TITLE
fail to connect to an https with no certificate. Similat to #1056

### ISSUE THREAD

**Issue by jubeormk1** [laurent22/joplin#2533]
iOS joplin app is not able to connect to a self-certificated nextcloud. It works from a desktop client and it did before adding https from the iOS app.

## Environment

Joplin version: 10.0.43
Platform: iOS
OS specifcs: 13.3.1

## Steps To Reproduce

1. Configure a connection to Nextcloud 16.0.8 self certificate (https) by targets 'webDav' or 'Nextcloud'.
2. Check synchronization configuration

Describe what you expected to happen:
I expect to get a clean connection as with the Joplin version: 1.0.179 Platform: linux, OS specifcs: 18.04 LTS

## Logfile
![image](https://user-images.githubusercontent.com/48457722/74921856-73676a80-5422-11ea-84ce-681c8566f4db.png)

**Comment by michkern** [comment]
I can reproduce the same problem, issue occurred when switched to https with a self-signed certificate, on Windows the sync works perfectly when 'Ignore TLS certificate errors' is on. This option seems to be missing in the iOS app.

iOS: 13.3.1
Joplin iOS app version: 10.0.45
Joplin Windows 10 version: 1.0.193

<img width="375" alt="2020-03-10 09-47-52-1" src="https://user-images.githubusercontent.com/8256822/76328204-515b5c80-62eb-11ea-8bfa-a6469f0d57d3.png">

**Comment by michkern** [comment]
I have found out that in my case it is not a bug, just inexperience - I solved it by issuing my own certificate, made nextcloud use it and then make my iOS trust the certificate and CA. If  there is interest I can post the process.

**Comment by michkern** [comment]
I have posted my process on the [forums](https://discourse.joplinapp.org/t/nextcloud-webdav-sync-not-working-in-ios-works-in-windows/6788). If @jubeormk1 had the same problem, perhaps the issue can be closed.

**Comment by jubeormk1** [comment]
My scenario is **exactly the same** if it works for you I am quite confident that with the detailed instructions you add in the forum I should be able to follow that workaround.

Since it is reasonable that a non valid certificate should not be used unless the user knows what is doing maybe is reasonable not add the option Ignore TLS certificate errors. Said so it would be good to have the same options in every platform but probably there are detail in the iOS layer that prevent this connections to work.

So I agree on closing this issue and only can thank @michkern for the [contribution](https://github.com/laurent22/joplin/issues/2533#issuecomment-598329682).
