### ISSUE TITLE
problem with curly brackets rendering

### ISSUE THREAD

**Issue by as3ii** [laurent22/joplin#2539]
When using  _cases_ there is a bug in the rendered open curly bracket
example code:
```
$$
\rho(\lambda)+\epsilon(\lambda)=1 \rightarrow
\begin{cases}
    \cdot\text{ corpo nero}
        \begin{cases}
            \space\rho(\lambda) = 0 \\
            \space\epsilon(\lambda) = 1
        \end{cases} \\
    \cdot\text{ superfice perfettamente riflettente}
        \begin{cases}
            \space\rho(\lambda) = 0 \\
            \space\epsilon(\lambda) = 1
        \end{cases}
\end{cases}
$$
```
![immagine](https://user-images.githubusercontent.com/29260716/74963669-68a4d980-5412-11ea-865d-f422215a3951.png)
^ runtime rendering

![immagine](https://user-images.githubusercontent.com/29260716/74963736-86723e80-5412-11ea-9a39-0f0bafbf7ab0.png)
^ pdf (note the sign on the first page where the parenthesis is in the second page)

## Environment

Joplin version: 1.0.179
Platform: Linux
OS specifcs: Archlinux

## Steps To Reproduce

write the lines previously written in joplin and see the rendered pdf

Describe what you expected to happen:
curly brackets correctly rendered

## Logfile

index.html:127 GET file:///usr/share/joplin/resources/app/gui/note-viewer/pluginAssets/katex/fonts/KaTeX_Size4-Regular.woff2 net::ERR_FILE_NOT_FOUND
GET file:///usr/share/joplin/resources/app/gui/note-viewer/pluginAssets/katex/fonts/KaTeX_Size4-Regular.woff net::ERR_FILE_NOT_FOUND
index.html:133 GET file:///usr/share/joplin/resources/app/gui/note-viewer/pluginAssets/katex/fonts/KaTeX_Size4-Regular.woff2 net::ERR_FILE_NOT_FOUND
GET file:///usr/share/joplin/resources/app/gui/note-viewer/pluginAssets/katex/fonts/KaTeX_Size4-Regular.ttf net::ERR_FILE_NOT_FOUND

[log.txt](https://github.com/laurent22/joplin/files/4232441/log.txt)

**Comment by tessus** [comment]
this has been fixed already. it will be available inthe next release
