### ISSUE TITLE
Word count for notes.

### ISSUE THREAD

**Issue by tuqueque** [laurent22/joplin#2540]
Hi, I've done a quick search here and over the forum in Discourse and the only thing I found was a feature request from 2018 where nobody even cared to reply to the poor guy who asked...

Is there a "word count" feature in Joplin?... If so, I can't find it anywhere... if there isn't, would it be too much to ask for such a simple feature? I'm considering Joplin for my writing work, but the absence of such a simple feature is almost a deal breaker for me.

Thank you in advance!

**Comment by amitsin6h** [comment]
@tuqueque thanks for mentioning this, I truly agree that we should have this on our Joplin. I can add this feature for both android and desktop versions. Can any mentors let me know if I can proceed with this feature enhancement

**Comment by laurent22** [comment]
It's being developed in a PR and should be in soon.
