### ISSUE TITLE
Desktop and CLI application has different Notebooks

### ISSUE THREAD

**Issue by duvaldt** [laurent22/joplin#2553]
Thanks for a great application!

My desktop application and cli application doesn't use the same notebooks.

Afterwards I installed the CLI application using:

## Environment

Joplin version: 10.1.0.79
Platform: Linux
OS specifcs: Ubuntu 19.10

## Steps To Reproduce

1. Install desktop application with: 
wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash

2. Install CLI application with:
NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin
sudo ln -s ~/.joplin-bin/bin/joplin /usr/bin/joplin

3. Open joplin in terminal, and open joplin desktop app by clicking on the icon.

Describe what you expected to happen:
I expect both applications to open the same notebook. But whenever I write something in one of the apps it's not visible in the other.

**Comment by mic704b** [comment]
By default desktop and CLI use different profiles.  You might be able to use the `--profile` switch to get them to use the same profile.  Be careful not to run them at the same time though, you will corrupt the data.

**Comment by duvaldt** [comment]
Thank you for the clarification! :)
