### ISSUE TITLE
Electron client start script doesn't compile .ts/.tsx files

### ISSUE THREAD

**Issue by anjulalk** [laurent22/joplin#2555]
Existing or new `.ts` or `.tsx` files are not compiled into `.js` when running `npm start` in the ElectronClient folder. But they are successfully generated when running `npm install` in the root folder. 

## Steps To Reproduce

1. Locate a `.tsx` file (e.g. `ShareNoteDialog.tsx`) 
2. Delete the corresponding `.js` file
3. Run `npm start`

**Comment by tessus** [comment]
Not a bug. Please read https://github.com/laurent22/joplin/blob/master/BUILD.md#watching-files
