### ISSUE TITLE
Flow's config available in `/ReactNativeClient` but flow-bin doesn't exist in `/ReactNativeClient/package.json`.

### ISSUE THREAD

**Issue by ishammahajan** [laurent22/joplin#2568]
## Environment

Joplin version: Latest Master

Describe what you expected to happen: Flow should be included as a package to be installed if it is enforced.

**Comment by ishammahajan** [comment]
This isn't a bug, but I didn't know how to file the issue otherwise.

**Comment by laurent22** [comment]
We use TypeScript, not flow.

**Comment by ishammahajan** [comment]
Umm.
From what I understand, TypeScript doesn't require flow, this repository used to use flow, but has since removed the dependency because of shifting to TypeScript. Is that correct?

**Comment by laurent22** [comment]
We've never used flow, what you are seeing most likely is from the React Native package (which does use flow) but we don't make use of it.

**Comment by ishammahajan** [comment]
Ah, that clears it! I wasn't aware ReactNative included flowconfig along with it (automatically generated at root).

Thanks for clarifying!
