### ISSUE TITLE
[Feature request] Shortcuts to focus differents layout components

### ISSUE THREAD

**Issue by hughwilliams94** [laurent22/joplin#257]
### Operating system

- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

Hi while trying to use the desktop client in keyboard -heavy fashion, I have been frustrated by having to click into the editor pane or cycle through the tab key many times to allow me to type. Is there any way shortcuts could be defined to focus each component (e.g. ctrl+1 focuses side bar, ctrl+2 focuses note list, ctrl + 3 focuses editor pane)?

**Comment by laurent22** [comment]
Is there any standard in applications to select a particular pane? I see that Thunderbird and Firefox use F6 / Shift+F6 to cycle through panes so maybe we could use this.

Ctrl+1, etc. might too simple and might cause issue for the text editor in particular (either pressed accidentally or could be reserved for something else).

**Comment by hughwilliams94** [comment]
Some text editors (e.g. Sublime Text) use ctrl+1 etc. and it seems to work well. More conventionally browsers etc. use ctrl+tab to cycle tabs which could work here if we treat the panes as tabs.

**Comment by eitland** [comment]
Ctrl - f  for searching (find) already works and is fine. 

Some ideas: The ones I immediately looked for and tried to see if they existed were:

esc (to go back to previous thing, e.g. after I press ctrl - f I pressed esc to see if that would take me back to the open note, I also tried pressing esc in the note to see if that would take me back to the current note in the notebook.)

ctrl - e for edit (to go from any other place to the current note)

arrow right to go from a selected notebook to note list and from note list back top notebook list

arrow up and down in the notebooks and notes list (I have to tab and then press enter)

**Comment by pvdh** [comment]
I've been using joplin for only three days now and lack of keyboard-navigation is quite annoying.
ctrl+f is nice, but if you find more than to notes, how do you select one or switch between them? 
And if you find only one note, how do you move the focus from the search-field to the markdown-editor?

My suggestions would be to navigate notes with ctrl+pageup/ctrl+pagedown, notebooks with ctrl+shift+pageup/ctrl+shift+pagedown. And some other hotkey "move focus to editor". Having several notebooks, I just had to hit TAB 29 times(!) to get from search-entry to the editor.

**Comment by borisrorsvort** [comment]
@laurent22 would this issue track all keyboard related issues? Or shall we add individual issues for each?

**Comment by laurent22** [comment]
It's been implemented.
