### ISSUE TITLE
iOS: White splash screen with dark theme enabled

### ISSUE THREAD

**Issue by Rakleed** [laurent22/joplin#2570]
## Environment
Joplin version: 10.0.43
Platform: iOS
OS specifics: 13.3.1

## Steps To Reproduce
1. In the application settings, select a dark theme and save.
2. Unload the application from memory.
3. Open the application.

### Describe what you expected to happen:
The initial splash screen will be dark.

## Logfile

Screen recording: [RPReplay_Final1582544347.zip](https://github.com/laurent22/joplin/files/4244378/RPReplay_Final1582544347.zip)

**Comment by bedwardly-down** [comment]
I can verify this. It's not unnerving but I can see where you're coming from, @Rakleed.

Joplin version: 10.0.43
Platform: iOS
Version: 13.3.1

**Comment by Rakleed** [comment]
The problem is still not resolved.

**Comment by rabeehrz** [comment]
I'll give it a shot.

**Comment by Rakleed** [comment]
@rabeehrz how is the progress?

**Comment by Rakleed** [comment]
The problem is still not resolved.
