### ISSUE TITLE
White-Space preventing selected text to be converted into Bold/Italics if the selected text ends or starts with a white-space

### ISSUE THREAD

**Issue by Rishgod** [laurent22/joplin#2573]
# BUG 
If you select a line and press the bold button if the line has a white space, in the end, the text does not get bold(or italics) 

**Problem**

- White space in the beginning 

- White space at the end

![BUG](https://user-images.githubusercontent.com/54576074/75180326-f90c5280-5761-11ea-937a-ae81ffe9c03b.gif)

**EXPECTED BEHAVIOR**     

![DEBUG 2](https://user-images.githubusercontent.com/54576074/75179961-358b7e80-5761-11ea-8816-f00592609eac.gif)

**Comment by Rishgod** [comment]
Can I work on this @laurent22 @PackElend ,

 plus the solution to this seems pretty straight forward, just remove the white spaces I believe before and after the selected text -> add the Markdown-code -> and the readd the white space
for example 

**Suppose the selected text is**   " Hello world  "  (double quotes are just placeholders to show whitespace)
- Remove the white space "Hello world"
- Add the Markdown rule "*Hello world*"
- Re-add the white spaces again " *Hello world* "

I'm not really sure about the third step, should I

**Comment by PackElend** [comment]
what tool you are using for the screen records?

**Comment by PackElend** [comment]
but check changes in https://github.com/laurent22/joplin/pull/2565

**Comment by Rishgod** [comment]
> what tool you are using for the screen records?

[Screen to gif](https://www.screentogif.com/)

**Comment by Rishgod** [comment]
> but check changes in #2565

Alright, I'll do the same and get you back with the PR ASAP ^^
