### ISSUE TITLE
Web clipper service does not auto-start

### ISSUE THREAD

**Issue by mohsen-mohammadi** [laurent22/joplin#2574]
## Environment

Joplin version: 1.0.179
Platform: Linux
OS specifcs: Arch Linux 5.5.5

After every reboot, the web-clipper service does not start automatically. It's needed to launch the Joplin desktop app to be able to clip a web page. This has always been the case for me since I've started using Joplin.

Thanks!

**Comment by laurent22** [comment]
This is by design
