### ISSUE TITLE
White Overlay Across Joplin on Windows 10 v1909

### ISSUE THREAD

**Issue by triDcontrols** [laurent22/joplin#2578]
Happens more often than not, When opening Joplin on Windows 10, I get a white overlay. I do have dark mode enabled on Windows and Joplin. After Closing down Joplin by pressing the X button, and opening it again, same issue is present, Until I close Joplin and exit the system tray, then Open Joplin, things work fine. 

## Environment

Joplin version: 1.0.179
Platform: WIndows 10
OS specifics: Dark Mode enabled, running v1909

## Steps to reproduce

1. Open Joplin, get a white overlay across the app, 
2. Close Joplin by pressing X upper right corner, close Joplin system tray icon, 
3. Open, and is fine there after, happens from time to time.

## Describe what you expected to happen

Not to have the white overlay on startup. 

## Logfile

![joplin_desktop_issue](https://user-images.githubusercontent.com/22411662/75251415-65ea1180-578f-11ea-8b84-38ad63046cf5.PNG)

**Comment by meyash** [comment]
I faced a similar error

![Screenshot from 2020-02-26 04-29-55](https://user-images.githubusercontent.com/21121279/75299056-16bce300-585a-11ea-94c3-e0182d635c4d.png)

**Comment by laurent22** [comment]
Could you start the app with dev console? https://joplinapp.org/debuggin

**Comment by letian304** [comment]
I faced a similar error， My temporary solution is maximize the window，or other ways to change the window size。
