### ISSUE TITLE
Add support for Rule of Hooks plugin

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2579]
Add the eslint [Rule of Hooks plugins](https://reactjs.org/docs/hooks-rules.html#eslint-plugin), then run `npm run linter ./` from the root of the project, and fix the reported linter errors (if any).

**Comment by Rishgod** [comment]
can I work on this?

**Comment by arshmakker** [comment]
I would like to work on this one

**Comment by Runo-saduwa** [comment]
@arshmakker there is already a pull request for it and it solves the issue
