### ISSUE TITLE
(Desktop) Multiline code unexpected behaviour

### ISSUE THREAD

**Issue by coderrsid** [laurent22/joplin#2580]
### Environment

Joplin version: 1.0.179
Platform: macOS
OS specifics: Catalina 10.15.3

## Steps to reproduce

1.  Type ``` and try to write multiline code
2. After closing the multiline code ```, type anything in the same line.
3. The application considers it inside the multiline code.
4. If we start a new multiline code after the previous one, it shows it's text in plain-mode.

## Describe what you expected to happen

Either application should itself place the cursor into next line or user should be notified to resume the note from the next line or it behaves weirdly.

### Screen Recording of Issue
![record](https://user-images.githubusercontent.com/35633575/75268012-f4f13b00-581c-11ea-8f6b-5fc3eeb58e05.gif)

**Comment by dpoulton-github** [comment]
This does not look like a bug more expected behaviour, in that you are not using fenced code markdown correctly.

Once you open up a fenced code block it treats all subsequent text as fenced code until terminated by three back-ticks **on its own** on a line.

This you did but when you added `abcd` to create:

```text
```abcd
```

at the end, you are changing a fenced code block terminator to just a text entry so it ignores the back-ticks and continues treating all subsequent text as fenced code, awaiting a proper three back-tick terminator to tell it to stop.

**Comment by tessus** [comment]
Yes, this is the way how code blocks work.

The text after the first 3 backticks is used to denote the code language, which is also used by highlighters.

This is not a bug, but as @dpoulton-github mentioned the way it is supposed to work.

**Comment by coderrsid** [comment]
Ohh cool. Although i thought that as we are the developers, we know how to work this out. But a simple user can get a little lost by this behaviour. Shouldn't we show a notification or popup or something?

**Comment by tessus** [comment]
Well, this is standard Markdown syntax, so everyone who uses markdown (and Joplin uses markdown) should know this. A popup is too intrusive to explain basic functionality.

**Comment by coderrsid** [comment]
Oh great. Then we can leave it as it is.
