### ISSUE TITLE
The indentation of the cursor on Cyrillic

### ISSUE THREAD

**Issue by repman** [laurent22/joplin#2587]
If you type the text of a note in Cyrillic, the indent from the last printed character to the cursor increases as the characters in the line increase. There is no such problem with the Latin alphabet.

## Environment

Joplin version: 1.0.179 (prod, darwin)
Platform: macOS
OS specifics: 10.15

**Comment by laurent22** [comment]
Closed as duplicate

**Comment by repman** [comment]
When is the fix planned approximately?
