### ISSUE TITLE
Error while importing JoplinServerApi.js for ReactNativeClient

### ISSUE THREAD

**Issue by ani4aniket** [laurent22/joplin#2588]
## Describe what you expected to happen
For ReactNativeClient there is no JoplinServerApi.js file inside lib directory as mentioned below:
https://github.com/laurent22/joplin/blob/16fb1bda5305be5e3538f6fbc7de4a997920f555/ReactNativeClient/lib/SyncTargetNextcloud.js#L9

Actually, the file is JoplinServerApi.ts
https://github.com/laurent22/joplin/blob/master/ReactNativeClient/lib/JoplinServerApi.ts

Log:
![Screenshot 2020-02-26 at 2 00 27 PM](https://user-images.githubusercontent.com/31184591/75326335-6de5a680-58a0-11ea-83f0-afa6632bcf21.png)

**Comment by ani4aniket** [comment]
@laurent22 May you please check this, if this is the issue?

**Comment by laurent22** [comment]
For support requests, please use the forum. But try building again from scratch using BUILD.md
