### ISSUE TITLE
Multiple Evernote, Evernote(1) and Evernote(2) notebooks on Evernote import.

### ISSUE THREAD

**Issue by adrianharabula** [laurent22/joplin#259]
### Operating system

- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

When importing from evernote I have the same notes in 3 'Evernote' notebooks. Is there a way to debug this further?

I deleted extra notebooks but I wonder why that happened.

**Comment by laurent22** [comment]
I wonder if it's the same bug as this one https://github.com/laurent22/joplin/issues/205 ? Which Joplin version is it?

**Comment by laurent22** [comment]
If I'm not mistaken the issue you had is that the same file was imported multiple times. This has been fixed in a recent version.

**Comment by adrianharabula** [comment]
Updated to latest version available 1.0.67, redid the import. Now it is working!

Thank you very much!!! This was a really quick fix.
