### ISSUE TITLE
DESKTOP:Adding functionality to the toolbar

### ISSUE THREAD

**Issue by Rishgod** [laurent22/joplin#2590]
## Enhancement
I was going through other note-taking apps online and one thing that everyone had was a strike-text button just like <s>LOREM IPSUM</s>

like this
<img width="351" alt="Annotation 2020-02-26 155151" src="https://user-images.githubusercontent.com/54576074/75335725-f881d200-58af-11ea-88ed-5054334848d7.png">

<hr/>

<img width="351" alt="Improvements" src="https://user-images.githubusercontent.com/54576074/75337504-20bf0000-58b3-11ea-93f7-8c7e71a88bc6.jpeg">

(we can also implement the Underline button too)

@laurent22 @PackElend @tessus  what do you think about it

If you think that this feature should be implemented, I would like to work on this and create a pull request

**Comment by laurent22** [comment]
Hi, for feature suggestion, please use the forum. And we don't support strike-through because it's not part of the Markdown spec.

**Comment by Rishgod** [comment]
Okay @laurent22  noted next time I'll add this in the forums, but I guess you can add strike using 
~~ () ~~  ~~()~~

<img width="1128" alt="Annotation 2020-02-26 163338" src="https://user-images.githubusercontent.com/54576074/75339259-2e29b980-58b6-11ea-81a8-21409503ae53.png">

**Comment by PackElend** [comment]
forum topic: https://discourse.joplinapp.org/t/adding-functionality-to-the-toolbar/6315/

**Comment by PackElend** [comment]
for the record, high level discussion here
https://discourse.joplinapp.org/t/high-level-discussion-on-plug-in-architecture-template-library/6554
