### ISSUE TITLE
No undo/redo functionality on Android

### ISSUE THREAD

**Issue by XTerminatorGR** [laurent22/joplin#2595]
OS: Android
App: Mobile
As mentioned in the title there is no option to undo/redo in Android while editing a file (AFAIK). This along with aggressive auto-save make a annoying combo in case of accidentally deleting something in a note, especially big texts.

**Comment by amitsin6h** [comment]
I am working on this

**Comment by XTerminatorGR** [comment]
Ok! Thx for the response!

**Comment by coderrsid** [comment]
>(AFAIK)
What do you mean by this?

**Comment by amitsin6h** [comment]
> > (AFAIK)
> 
> What do you mean by this?

It means As Far As I Know (AFAIK) 
Its an abbreviation :sweat_smile:

**Comment by coderrsid** [comment]
Thanks @amitsin6h 👍

**Comment by coderrsid** [comment]
@laurent22 is this still an issue?

**Comment by XTerminatorGR** [comment]
@coderrsid Unfortunately yes....

**Comment by coderrsid** [comment]
Ohh.. i'll look what i can do.

**Comment by Rahulm2310** [comment]
@coderrsid I am already working on it, so could you please look on some other issue

**Comment by coderrsid** [comment]
Although @Rahulm2310  i'll suggest you to discuss the feature on the Discourse forum as it will increase the understanding of the feature for you and the community better.

**Comment by teddyzhai** [comment]
the scope of this issue is not only Android, but also desktop (win/Linux).
tested version: 1.0.201

**Comment by Rahulm2310** [comment]
@teddyzhai I think we have undo/redo functionality on the desktop app.

**Comment by teddyzhai** [comment]
@Rahulm2310 , I am on version 1.0.201 for Linux.
![image](https://user-images.githubusercontent.com/25607359/80372728-42793b00-8894-11ea-8104-f7bf5e8c99ca.png)

Under Edit tab, there is no `undo` or `redo`. Can you please point me to the right place? thanks.

**Comment by coderrsid** [comment]
> Under Edit tab, there is no `undo` or `redo`. Can you please point me to the right place? thanks.

Yeah we know that. But if the focus of cursor is in editor. Press Ctrl+Z for undo & Ctrl+Shift+Z for redo, it will work till the last note sync.

**Comment by XTerminatorGR** [comment]
@stale[bot] yes the issue is still at large
