### ISSUE TITLE
Multi-sync

### ISSUE THREAD

**Issue by supersaiyansubtlety** [laurent22/joplin#260]
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

The description of the app states that you can sync to multiple services, but in the mac version this doesn't appear to be possible. I would like to have this feature on the mac version because I want to sync between desktops on LAN (using local folder) and use one of the sync services for my iPhone.

**Comment by laurent22** [comment]
Duplicates #61
