### ISSUE TITLE
macOS ctrl+f and ctrl+p support

### ISSUE THREAD

**Issue by att14** [laurent22/joplin#2601]
When using the macOS client certain control modifiers do not work, e.g. `ctrl+f` (forward one character) and `ctrl+p` (up one line). Other control modifiers, such as `ctrl+b` (backward one character) and `ctrl+n` (down one line), work as expected.

## Environment

Joplin version: 
Joplin for Desktop

Copyright © 2016-2019 Laurent Cozic
Joplin 1.0.179 (prod, darwin)

Client ID: ac4a81affe494edc81fa78650cd44668
Sync Version: 1

Revision: 66356d8 (HEAD)
Platform: macOS
OS specifics: Mojave 10.14.6

## Steps to reproduce

1. Press `ctrl+f`.

## Describe what you expected to happen

Cursor moves forward one character.

**Comment by PRASHANT1104** [comment]
['F', 'T', 'P', 'Q', 'L', ',', 'G', 'K']  + CMD/CTRL. 
These keys are marked as cancelled keys in the code. This is done to override their expected behaviour . I am still not sure why .

**Comment by att14** [comment]
This is still an issue.

**Comment by coderrsid** [comment]
@att14 you've said to reproduce this issue press `Ctrl + (P,F, etc)` on mac. But i guess you're trying to say `Cmd` button instead as pressing the buttons you said are not doing anything. Can you just reconfirm what you're trying to say here.

**Comment by att14** [comment]
No I do not mean `cmd`. In any other text editing application on MacOS if you press `ctrl+f` your cursor will move forward one character. Since this is a pretty commonly used shortcut, it makes editing in Joplin harder for people who are used to using this shortcut.

**Comment by coderrsid** [comment]
Oh , i get it. Don't worry i'll look through the issue and revert ASAP.

**Comment by att14** [comment]
This is still an issue.

**Comment by att14** [comment]
This is still an issue.

**Comment by att14** [comment]
This issue is up to date and the problem is present in the latest build.

**Comment by Fly163-star** [comment]
It's a really common shortcut on macOS. It can be used in almost all the MacOS app, safari. It can be used in Joplin except markdown editor. Who should we speak to to fix this problem?

**Comment by chizhang21** [comment]
This is still an issue.
