### ISSUE TITLE
[Android app] Sync with nextcloud fail.

### ISSUE THREAD

**Issue by zhangcheng142** [laurent22/joplin#2603]
## Environment

Joplin version: 1.0.318
Platform: Android
OS specifics: MIUI 11.0.5 based on Android 10
Nextcloud: 18.0.1

## Steps to reproduce

1. Install with default setting.
2. configure Synchronizaiton target: Nextcloud, with WebDAV URL link: http://sample.f3322.net:3344/remote.php/webdav/Joplin
3. 'Check Synchronizaiton Configuration' fail.

The nextcloud server is work well with Windows & iOS client.

## Logfile

02-28T14:58:20,10,"""TypeError: Network request failed
onerror@index.android.bundle:134:7285
dispatchEvent@index.android.bundle:125:5676
value@index.android.bundle:120:6095
value@index.android.bundle:120:2835
value@index.android.bundle:46:1280
value@index.android.bundle:26:3685
index.android.bundle:26:841
value@index.android.bundle:26:2939
value@index.android.bundle:26:813
value@[native code]""

[syncReport-1582873158172.txt](https://github.com/laurent22/joplin/files/4265809/syncReport-1582873158172.txt)

**Comment by bedwardly-down** [comment]
I have a redmi 5 plus at home i should be able to quickly test this on when i get home for lunch. What model do you have?

**Comment by bedwardly-down** [comment]
I can't reproduce this bug. Is that nextcloud server a home one or through a service? And, in my url, i have no need for a port number but instead have ssh going through my firewall and ports 80 and 443 open on a Digital Ocean server since they are required by nextcloud to function properly. 

Have you tried without that port number or tried to open that port in your firewall so your phone has access? It could possibly be a certificate issue if you don't have that setup correctly. That's what happened to me the other day. 

My phone specs. 

![6323BA8A-AAAE-46DA-8E12-3ABA18DEF8D4](https://user-images.githubusercontent.com/59133880/75724542-3d3cad00-5ca4-11ea-875b-0844bec9d6fd.jpeg)

**Comment by zhangcheng142** [comment]
I think the problem maybe url parse with port.  The server is build at home under Gateway,  the DNAT rule is work well.
I have tested it using Joplin windows client and iOS app，that's ok.
Our ISP blocked port 80, 443... , cheng142.f3322.net is an dynamic DNS.
I have add an test accout for you, you can try with my server.
Account name: test
Password: for_test
My Andorid phone:
![phone](https://user-images.githubusercontent.com/12950177/75738169-84767c80-5d3c-11ea-8b39-b7933bbc8436.png)

**Comment by bedwardly-down** [comment]
Sorry, i didn't test that url. I tested on my own nextcloud server, but I'll be home from work shortly. My Redmi 5 is just a remnant of my old import phone collection, so I'll test that test account when i get home.

**Comment by bedwardly-down** [comment]
I tested this and I'm not completely sure how to reproduce this at all

**Comment by zhangcheng142** [comment]
[Screenrecorder-2020-03-04-14-19-49-236.zip](https://github.com/laurent22/joplin/files/4285452/Screenrecorder-2020-03-04-14-19-49-236.zip)
Attachment is a screenrecord video, please check it.
Thanks.

**Comment by zhaoxiangyu** [comment]
I encountered the same problem.
   My phone is Mix2s
   app version:1.0.316
   OS:MIUI 11.0.1 based on Android 10

The nextcloud server is work well with Mac & iOS client.

![151583590671_ pic](https://user-images.githubusercontent.com/5743071/76145122-84baa300-60c1-11ea-8d01-fd8ed42007f4.jpg)

**Comment by bedwardly-down** [comment]
I couldn't reproduce it possibly because my phone is an unlocked international model. There have been other issues reported with Xiaomi phones, so it may be Miui specific bugs that aren't directly related to Joplin

**Comment by zhaoxiangyu** [comment]
> [Screenrecorder-2020-03-04-14-19-49-236.zip](https://github.com/laurent22/joplin/files/4285452/Screenrecorder-2020-03-04-14-19-49-236.zip)
> Attachment is a screenrecord video, please check it.
> Thanks.

“android-v1.0.319-rc1” has been released.
It works on my Mix2s~
Good Luck

**Comment by zhangcheng142** [comment]
android-v1.0.319-rc1 is ok, so close this issuse
