### ISSUE TITLE
Implement font picker in desktop application

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2605]
It is already possible to set the font used in the editor from the config screen:

<img width="387" alt="image" src="https://user-images.githubusercontent.com/1285584/75550299-89c88400-5a29-11ea-892b-ae517b7bf8c2.png">

However, the user has to manually type the name of the font, which is not convenient.

We would like to add a font picker to make this process easier. It would work like so:

- The existing text input field remains unchanged
- Next to it, add a button "Pick font" which will open the font picker
- The font picker will only display monospace fonts
- Once a font is picked, the font name populates the text input field
- It needs to work on Windows, macOS and Linux. If one or more of the OS cannot be supported, the button should be hidden.

**Comment by daukadolt** [comment]
Can I take the issue?

**Comment by Rishgod** [comment]
Looks good I'd like to work on it!

**Comment by Rishgod** [comment]
> It is already possible to set the font used in the editor from the config screen:
> 
> <img alt="image" width="387" src="https://user-images.githubusercontent.com/1285584/75550299-89c88400-5a29-11ea-892b-ae517b7bf8c2.png">
> 
> However, the user has to manually type the name of the font, which is not convenient.
> 
> We would like to add a font picker to make this process easier. It would work like so:
> 
> * The existing text input field remains unchanged
> * Next to it, add a button "Pick font" which will open the font picker
> * The font picker will only display monospace fonts
> * Once a font is picked, the font name populates the text input field
> * It needs to work on Windows, macOS and Linux. If one or more of the OS cannot be supported, the button should be hidden.

Suggestion rather than incorporating a button incorporate a drop-down button which has all the monospace fonts. 
<br>
![slider](https://user-images.githubusercontent.com/54576074/75577010-0e95bb00-5a87-11ea-8315-97e3015e8204.gif)



What do you think about it?

**Comment by laurent22** [comment]
Dropdown lists with type-in introduce all kind of problems so I prefer a separate button for now.

**Comment by AkshatSachan** [comment]
@laurent22  @PackElend  I would like to work on this issue. Can you assign it to me.

**Comment by AkshatSachan** [comment]
@laurent22 @PackElend , I would like to work on this issue.
Can you please assign it to me.

**Comment by rabeehrz** [comment]
@AkshatSachan Hey I think @Rishgod is working on this.

**Comment by AkshatSachan** [comment]
Ok , thats fine I will look into some other issue.

**Comment by daukadolt** [comment]
@Rishgod can you comment on your status? Because I'm halfway there, and I thought that you were working on [this](https://github.com/laurent22/joplin/issues/2618) issue

**Comment by Rishgod** [comment]
> @Rishgod can you comment on your status? Because I'm halfway there, and I thought that you were working on [this](https://github.com/laurent22/joplin/issues/2618) issue

@daukadolt you can go ahead with completing this, I'm just done 20% :)

**Comment by daukadolt** [comment]
> > @Rishgod can you comment on your status? Because I'm halfway there, and I thought that you were working on [this](https://github.com/laurent22/joplin/issues/2618) issue
> 
> @daukadolt you can go ahead with completing this, I'm just done 20% :)

thanks @Rishgod :)

**Comment by bedwardly-down** [comment]
I wonder if adding a font directory to where Joplin stores it config files and then reading the fonts from there would be a compromise that would work better long term? That's a pretty standard way of handling it for many other apps. Then Joplin would just read the fonts in that directory and give those as an option.

**Comment by Rishgod** [comment]
> > > @Rishgod can you comment on your status? Because I'm halfway there, and I thought that you were working on [this](https://github.com/laurent22/joplin/issues/2618) issue
> > 
> > 
> > @daukadolt you can go ahead with completing this, I'm just done 20% :)
> 
> thanks @Rishgod :)

Hey, @daukadolt just let me know if you need any help or if you want to abandon the PR okay? :)

**Comment by daukadolt** [comment]
> > > > @Rishgod can you comment on your status? Because I'm halfway there, and I thought that you were working on [this](https://github.com/laurent22/joplin/issues/2618) issue
> > > 
> > > 
> > > @daukadolt you can go ahead with completing this, I'm just done 20% :)
> > 
> > 
> > thanks @Rishgod :)
> 
> Hey, @daukadolt just let me know if you need any help or if you want to abandon the PR okay? :)


Last few days were very busy, but I'm finally more or less free. If you have any ideas or suggestions, I could possibly use some

**Comment by Chhekur** [comment]
Is anybody currently working on this ?
if not then could I work on this one ?

@Rishgod @daukadolt

**Comment by Rishgod** [comment]
you should ask @daukadolt I'm not working on it.

**Comment by daukadolt** [comment]
@Chhekur I'm working on the issue, it's just that I'm kinda slow 😅

**Comment by rabeehrz** [comment]
@daukadolt Are you still working on this? Can I take up this issue?

**Comment by rabeehrz** [comment]
I was thinking of using this package, [font-manager](https://github.com/foliojs/font-manager).

It supports all the platforms.

**Comment by bedwardly-down** [comment]
@rabeehrz, if you decide to use that, you’ll need to understand how to fix it if it breaks. It doesn’t have much active development on it with most of the latest commits being quite old. But super cool find, nonetheless

**Comment by rabeehrz** [comment]
Well, that is the only way I found to get system fonts for Electron. Other way is adding a fonts directory to Joplin, like you suggested.

> I wonder if adding a font directory to where Joplin stores its config files and then reading the fonts from there would be a compromise that would work better long term? That's a pretty standard way of handling it for many other apps. Then Joplin would just read the fonts in that directory and give those as an option.

**Comment by bedwardly-down** [comment]
Are React Native libraries only usable for mobile apps or could they be leveraged for Desktop also? I found a highly active one that could possibly be used to allow picking fonts on mobile but might be usable here, too.

https://www.npmjs.com/package/expo-font

**Comment by roman-r-m** [comment]
> Are React Native libraries only usable for mobile apps or could they be leveraged for Desktop also?

There's this: https://github.com/microsoft/react-native-windows but seems it's only Windows 10 and it's not yet stable

**Comment by bedwardly-down** [comment]
Joplin is cross platform so it has to be a library that supports Windows, mac and Linux.

**Comment by roman-r-m** [comment]
Quick googling returned this: https://github.com/status-im/react-native-desktop

**Comment by rabeehrz** [comment]
> Quick googling returned this: https://github.com/status-im/react-native-desktop
> It seems actively developed.

But doesn't this mean that we'd have to convert Electron to React Native Desktop?

**Comment by roman-r-m** [comment]
I guess I misunderstood the original question.

**Comment by daukadolt** [comment]
I've had this picture in my mind, please correct me if I'm wrong.
<img width="1136" alt="Screen Shot 2020-04-13 at 21 06 17" src="https://user-images.githubusercontent.com/26189247/79131743-ed84f180-7dca-11ea-9e7b-efd16b1af811.png">

1. Selection button in the "Appearence" tab of the Configuration page.

<img width="1092" alt="Screen Shot 2020-04-13 at 21 06 24" src="https://user-images.githubusercontent.com/26189247/79131759-f1b10f00-7dca-11ea-945f-69d740ce860b.png">

2.1. Child BrowserWindow which opens a new React Component that utilizes library like the one @rabeehrz has mentioned.

<img width="1136" alt="Screen Shot 2020-04-13 at 21 07 02" src="https://user-images.githubusercontent.com/26189247/79131764-f37ad280-7dca-11ea-82cc-936bd4f513d2.png">

2.2. Alternative, modal child BrowserWindow.

Looking forward for a feedback on the vision in screenshots.

The problem I've had was with opening a React component inside this very child BrowserWindow. I a little new to React, so I've been having issues with opening it inside Electron. The examples on screenshots use plain html page.
The exact procedure of how [these](https://github.com/laurent22/joplin/tree/master/ElectronClient/gui) components are mounted and navigated inside Electron app is what, unfortunately, I've failed to understand.

**Comment by rabeehrz** [comment]
I was thinking of implementing a dialog with a simple drop-down, like the note properties.

But Laurent had said we need to have a proper dialog framework in place before he accepts any more PR related to it. That's why I've waited on this. I do plan to work on this.

**Comment by daukadolt** [comment]
> I was thinking of implementing a dialog with a simple drop-down, like the note properties.
> 
> But Laurent had said we need to have a proper dialog framework in place before he accepts any more PR related to it. Also, there are a lot of bugs to fix and he's not going to accept any more new features as of now. That's why I've waited on this. I do plan to work on this.

could you help me out with my problems above? If you want, I won't proceed any further with the feature request, but I'd like to learn how to integrate my custom React components.

**Comment by rabeehrz** [comment]
> I'd like to learn how to integrate my custom React components.

If you take a look at the folder gui inside ElectronClient, You can see a lot of .jsx files. Most of them (if not all) are custom components. Let us take ToolbarButton.jsx for example. It takes in some parameters and ultimately generates an anchor tag `<a>`. Then we just export it and use <ToolbarButton> else where. This is somewhat basic.

I think it would really help if you create a Topic in the forums so that everyone can give their input.
