### ISSUE TITLE
side menus stop working

### ISSUE THREAD

**Issue by taw00** [laurent22/joplin#2607]
joplin 1.0.179 -- my builds (see https://github.com/taw00/joplin-rpm)
fedora 31
Kernel: Linux localhost.localdomain 5.5.6-201.fc31.x86_64 #1 SMP Mon Feb 24 20:24:13 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

The sidebar menus sporadically cease to function. I am still investigating, but I figured I would log it as an issue. If I find out more, I will add to this issue. I have not found a pattern yet. At some point, you can click all you want on the items in the notebook or note menus and the item you are editing (or viewing) doesn't change. If you continue to edit everything saves fine, etc. But you just can't change what you are working on.

-todd

**Comment by laurent22** [comment]
Maybe try to always keep the console open to see if there's any error or warning when it happens. https://joplinapp.org/debugging

**Comment by bedwardly-down** [comment]
Open a terminal. Could you paste what `uname -a` says here for me?

**Comment by bedwardly-down** [comment]
@laurent22, I'm almost certain this is a duplicate of #2518 . Fedora 31 just released a new mainline kernel in their repos and I believe it's one of the problem ones. There's already been a report from that distro about just this.

**Comment by taw00** [comment]
@laurent22 -- Yes. The next time I have significant time at using Joplin, I will do so. Just haven't had the opportunity and felt I should get the issue filed.

@bedwardly-down -- I have updated the original description with the kernel info you requested.

**Comment by bedwardly-down** [comment]
> @bedwardly-down -- I have updated the original description with the kernel info you requested. Mind you, I don't know that it was the same kernel as when I originally reported the issue

Kernel 5.5 and 5.6 are causing freezing issues like you described for a large chunk of Linux users and about 3 days ago a Fedora 31 user reported the same issue. I'm currently tracking down the broken kernel commits that are causing the problem while others are trying to figure out the issue from the code end since this seems like one of those weird edge case bugs that i haven't found any major GH tracker reports on upstream.

**Comment by taw00** [comment]
Hey, stale-bot. Yes, this is still an issue and I even lost data. :(  
As recent as joplin-1.0.201 and Fedora 31

**Comment by taw00** [comment]
Dupe of 3114, closing.
