### ISSUE TITLE
ctrl + L and  toggle editor layout button is not disabled in empty notebook

### ISSUE THREAD

**Issue by Runo-saduwa** [laurent22/joplin#2608]
## Environment

Joplin version: Joplin 1.0.178
Platform:  Windows
OS specifics: Windows 10

I'm not sure if this was deliberately designed to do this,  **but ctrl + L and  toggle layout button is not disabled in an empty notebook** (notebook without notes), the Pane toggle icon is disabled when a notebook is empty and i believe this should also apply to the shortcut associated with this functionality. 

## Steps to reproduce

1. Create an empty note
2. On the menu, go to **views**
3. click on  **Toggle editor layout** or type CTRL + L
4. Go to an existing notebook (or create one) with notes and you'll notice that the layout changes.

## Describe what you expected to happen
1. Create an empty note
2. Go to **views**
3. **Toggle editor layout** and CTRL + L should be disabled like the toggle layout icon

**Comment by Runo-saduwa** [comment]
I would like to work on this if it is indeed a bug

**Comment by Runo-saduwa** [comment]
@tessus can i go ahead with this?

**Comment by tessus** [comment]
Let's wait for Laurent's input.

**Comment by Runo-saduwa** [comment]
Alright then
