### ISSUE TITLE
iCloud Sync

### ISSUE THREAD

**Issue by supersaiyansubtlety** [laurent22/joplin#261]
### Operating system

- [x] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

### Application

- [x] Desktop
- [x] Mobile
- [ ] Terminal

I would find the ability to sync via iCloud useful.

**Comment by laurent22** [comment]
Unfortunately that cannot be implemented as iCloud does not have an API for Android, Windows or Linux.
