### ISSUE TITLE
Back button iOS

### ISSUE THREAD

**Issue by wedvjin** [laurent22/joplin#2611]
## Environment

Joplin version: 10.0.43
Platform: iOS 
OS specifics: iPhone SE

## Steps to reproduce

1. Open the note
2. Edit it
3. Go back
4. Pop up message to keep changes
5. Staying on the same note, as in not going back to the list of notes

## Describe what you expected to happen

You go back to the list of notes

**Comment by bedwardly-down** [comment]
This isn't actually a bug but a design choice. What's happening is the back button is taking you back to the Preview Mode which shows what the note will look like after processing the markdown and whatnot.

**Comment by wedvjin** [comment]
Shall we question this design choice? There is a save button just next to back button, which can be used for the exact same purpose. And it is reasonable to expect the back button to take you to the previous screen, not back in terms of application state.

**Comment by bedwardly-down** [comment]
That's honestly the kind of thinking i personally enjoy. I'm not the one who makes these choices and there is the possibility that that's tied to the Ace Editor and not Joplin exclusively. Either way, are you a member of the Joplin forums? There are multiple topics open where we'd gladly have your thoughts.
