### ISSUE TITLE
Uneven Behavior of List Elements

### ISSUE THREAD

**Issue by mhimanshu712** [laurent22/joplin#2614]
An issue with ElectronClient.

After adding a few elements in a list item ( NumberList, BulletedList ), if we **press the Enter key**, the **last unused row should get deleted automatically** which doesn't happen in Joplin.<br><br>

Here is how it behaves:<br>
![jopnote](https://user-images.githubusercontent.com/41316051/75602267-87c5fa00-5ae9-11ea-907f-09f769e20d19.gif)

Here is how it should behave:<br>
![expectnote](https://user-images.githubusercontent.com/41316051/75602281-a62bf580-5ae9-11ea-8cad-a5d5fc6bf7e3.gif)

**Comment by mhimanshu712** [comment]
Also, I would like to work on it.

**Comment by PackElend** [comment]
second is how I'm used to it in MS TEAMS,
go ahead

**Comment by coderrsid** [comment]
I guess it's not a bug , it's a note, user can leave the number for future addition to the list, that all depends on user. What do you suggest @tessus ?

**Comment by tessus** [comment]
This is really a matter of opinion. I've found the current behavior a bit annoying. But that's just me.

If I wanted to add a new item, I would just position the cursor at the end of the last item and hit enter.

**Comment by PackElend** [comment]
> If I wanted to add a new item, I would just position the cursor at the end of the last item and hit enter.

me too, I like it slim

**Comment by Rishgod** [comment]
@laurent22 what do you think about this, should I go ahead trying to fix this?

**Comment by tessus** [comment]
There's a PR available. I've been using the code for weeks now and it works splendidly.

It will get merged eventually.
