### ISSUE TITLE
Desktop: Header Bar title disappears on switching themes

### ISSUE THREAD

**Issue by rabeehrz** [laurent22/joplin#2615]
While switching themes, the title for menu bar items ( Toggle Sidebar, New Notebook etc.)
The titles come back when I restart the App.

[![bugc9d94c3b9de67ad0.gif](https://s5.gifyu.com/images/bugc9d94c3b9de67ad0.gif)](https://gifyu.com/image/IzpE)

## Steps to reproduce

1. Open Joplin
2. Go to Appearance and change theme
3. Go back and see the bug

## Environment

Joplin version: Joplin 1.0.185 (dev, darwin)
Platform: Desktop
OS specifics: macOS

## Describe what you expected to happen

The header titles should be retained.

**Comment by rabeehrz** [comment]
I would like to work on this issue if this is a bug.

**Comment by tessus** [comment]
As a matter of fact this also happens in other situations. I haven't been able to reproduce it, because it only happens intermittently. I guess the PR might fix those issues as well.
