### ISSUE TITLE
expand tree when cilcking on 'In: Folder ...' in search result

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#2616]
## Environment

Joplin version: 1.0.179 and git master 6542a60d
Platform: macOS (but irrelevant)
OS specifics: 10.14.6

## Steps to reproduce

1. create a folder (`A`) with a sub-folder (`A.1`) and a sub-sub-folder (`A.1.1`)
2. create a note `xyz` in `A.1.1`
3. collapse the folders and sub-folder in `A`
4. global search: `xyz`
5. click on the folder icon `In: Folder A.1.1`
<img width="125" alt="image" src="https://user-images.githubusercontent.com/223439/75602538-4bb47a00-5a94-11ea-8798-ca34c47ad016.png">

## Describe what you expected to happen

I expect the folder structure to be expanded for folder `A.1.1`. Currently only the folder is selected, which you can't see, because the tree is collapsed.

This is a regression, since that has worked before. Or at least I think it did.

However, only the relevant tree should be expanded. If there are other sub-folders which are collapsed, they should not be touched. Expanded folders within the folder should not be touched either.

This is a fairly easy fix. Start at the target folder id and retrieve its parent ids, until you hit the root. Then use this list of ids to expand the tree.

It would be even better, if the tree only expanded when the folder icon `In: Folder ...` was clicked a second time. Although this might be a bit too complicated for a `good first issue`.

**Comment by rabeehrz** [comment]
I will look into this.
