### ISSUE TITLE
Renaming a Tag adds it to SelectedNoteTags list regardless if such a NoteTag exists

### ISSUE THREAD

**Issue by vsimkus** [laurent22/joplin#2618]
## Environment

Joplin version: 1.0.178
Platform: Linux
OS specifics: Debian Bullseye (Testing)

## Steps to reproduce

1. Create a note and attach a tag.
2. Create another note without tags.
3. Rename the tag using the sidebar context menu.

Renaming a tag adds it to the top editor bar even though the note is not tagged with this particular tag. The note is not actually tagged, it only shows up in the top bar. If you switch the selected note to another one and back, then the tag will have disappeared from the top bar.

## Describe what you expected to happen

Renaming a tag that is not associated with the currently selected note should not add the tag item to the top bar in the editor.

## Screencast

The screencast doesn't show the renaming dialog, but I just change the name of the tag from "coding" to "coding_2".
![demo](https://user-images.githubusercontent.com/5730052/75604557-319d8a80-5ada-11ea-8d9a-8275c0fd09df.gif)

**Comment by laurent22** [comment]
Indeed there's a bug here.

**Comment by Rishgod** [comment]
@vsimkus I'll look into it, thanks for pointing it out

**Comment by PRASHANT1104** [comment]
@Rishgod are you working on it ? If not , I would like to work on it.

**Comment by Chhekur** [comment]
@laurent22 I have fixed this issue and made a PR : https://github.com/laurent22/joplin/pull/2680
