### ISSUE TITLE
On my ArchLinux

### ISSUE THREAD

**Issue by LWF666** [laurent22/joplin#2621]
I installed  joplin with "pacman -S joplin",then I open the joplin,It happened a Fatal Error，
this is the screenshot：
 [joplin-1](https://cdn.lovezy.online/joplin-1.png)
 [joplin-2](https://cdn.lovezy.online/joplin-2.png)
 [joplin-3](https://cdn.lovezy.online/joplin3.png)

Can who help me?Thanks!

**Comment by tessus** [comment]
⚠🚨⛔ The issue tracker is not for questions. ⛔🚨⚠

As it happens, support requests that are created as issues are likely to be closed. We want to make sure you are able to find the help you seek.

## Questions and Help

Please read the [documentation](https://joplinapp.org/) and [FAQ](https://joplinapp.org/faq/) first.

### https://discourse.joplinapp.org/

If you have still questions related to Joplin, please open a topic in the [forum](https://discourse.joplinapp.org/).
You can use your GitHub credentials to login to the forum.

## Links

- Documentation: https://joplinapp.org
- FAQ: https://joplinapp.org/faq/
- Forum: https://discourse.joplinapp.org
- How to enable end-to-end encryption: https://joplinapp.org/e2ee/
- API documentation: https://joplinapp.org/api/
- How to enable debug mode: https://joplinapp.org/debugging/

**Comment by Dave-van-der-Meer** [comment]
I have the same issue. The GUI application does not work while the terminal version does work.
