### ISSUE TITLE
Rendering problem with matrices

### ISSUE THREAD

**Issue by ges7** [laurent22/joplin#2622]
Hello,
There is an issue when rendering a matrix or column vector. The matrix renders like this :
![wrong_render](https://user-images.githubusercontent.com/1526152/75623975-17ce7700-5bb0-11ea-9af4-acb0bdd992cc.PNG)

## Environment

Joplin version: 1.0.179 (prod, win32)
Platform: win32
OS specifics: Windows 10

## Steps to reproduce

1. Create a markdown note
2. Write in it :  
```
matrice :
e.g. $A=\begin{pmatrix}1&2\\3&4\\5&6\end{pmatrix}$
```
3. See the result in the rendering

## Describe what you expected to happen

We expect this result :
![image](https://user-images.githubusercontent.com/1526152/75623858-d6899780-5bae-11ea-976d-333d2f299dd8.png)

## Logfile

Failed to load resource: net::ERR_FILE_NOT_FOUND
C:\Users\myuser\AppDa…app.asar\app.js:635 Revision: 66356d83 (HEAD)
C:\Users\myuser\AppDa…NoteText.min.js:920 webview_domReady 
Connect
KaTeX_Size4-Regular.woff2:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
KaTeX_Size4-Regular.woff:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
KaTeX_Size4-Regular.ttf:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
index.html:133 GET file:///C:/Users/myuser/AppData/Local/Programs/Joplin/resources/app.asar/gui/note-viewer/pluginAssets/katex/fonts/KaTeX_Size4-Regular.woff2 net::ERR_FILE_NOT_FOUND
KaTeX_Size4-Regular.woff:1 GET file:///C:/Users/myuser/AppData/Local/Programs/Joplin/resources/app.asar/gui/note-viewer/pluginAssets/katex/fonts/KaTeX_Size4-Regular.woff net::ERR_FILE_NOT_FOUND
KaTeX_Size4-Regular.ttf:1 GET file:///C:/Users/myuser/AppData/Local/Programs/Joplin/resources/app.asar/gui/note-viewer/pluginAssets/katex/fonts/KaTeX_Size4-Regular.ttf net::ERR_FILE_NOT_FOUND
﻿
​

**Comment by laurent22** [comment]
Should be fixed in next version.
