### ISSUE TITLE
Unexpected behavior when exporting from menu/window bar dropdown as opposed to secondary click context menu

### ISSUE THREAD

**Issue by TheManchineel** [laurent22/joplin#2625]
When I select a note to view it, then click on the "File" button in the menu bar and choose Export --> JEX, Joplin exports a JEX containing all of my notebooks, containing all of my notes. When I right click on an entry in the sidebar, instead, Joplin only exports the selected entry.  
It seems weird for Joplin to behave like this and it might lead to a user accidentally sending confidential information in another notebook, believing they were just sharing the selected note. It has almost happened to me once (I checked the tar before sending it via Email) and happened to my friend who just started using Joplin today. It should at least warn you that everything will be exported, though IMO this feature should be buried deeper down in the UI, since it would only be used for migrating to a different app.

## Environment

Joplin version: 1.0.179
Platform: macOS, Windows, Linux
OS specifics: tested on latest versions of Catalina and Windows 10, and on Ubuntu Linux 18.04

## Steps to reproduce

1. Select a single note, so that it appears on the view/edit panel(s) depending on view mode.
2. Click on File in the menu bar or window bar (depending on platform)
3. Select "Export", then pick "JEX - Joplin Export File" as format
4. Save the file to a location, then open it with your favorite TAR-compatible archive viewer.
5. All of your notes will be there.

## Describe what you expected to happen

The TAR should only contain the note I was viewing, or alternatively it and all of the other notes currently selected in the sidebar.

**Comment by tessus** [comment]
This works as designed.

- `File -> Export -> xxx` exports all data
- `right click on notebook and export` exports the notebook
- `right click on note and export` exports the note

This is highly logical and intuitive.
