### ISSUE TITLE
[Feature request] - New entry type "Chapter"

### ISSUE THREAD

**Issue by jcgerhard** [laurent22/joplin#263]
### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [x] Android
- [x] iOS

### Application

- [x] Desktop
- [x] Mobile
- [x] Terminal

----
**Preface**

While joplin runs very stable on macOS/iOS now and has IMHO the capability to rise above a simple todo-list or note-taking app, I am going more and more over to use it in a wiki- or maybe rather a knowledgebase-like style. That means, having longer articles/entries that contains a lot of different headings and paragraphs. This is a perfect and fast way to build up portable and "syncable" wikis and manuals for desktop and mobile - available at any time, no matter where you are or where you create or edit them.

----
**Problem**

It is very hard to navigate through such kind of content because of its length and complexity.

----
**Idea**

A new feature respectively a new type of entry that I would like to call a **chapter**.

----
**Description**

Basically, a chapter is an extended note type that adds an additional view/column with an auto-generated table of content next to the content area.
The table of content and its numbering is created by recognizing and counting every element that follows the markdown header formatting syntax like...
```
# Heading Level 1
## Heading Level 2
### Heading Level 3
```
...and furthermore, the counting is used for auto-numbering the headings in the content and the toc view consecutively.
The toc entries are clickable links so that you can jump directly to the corresponding positions.
The toc has a fixed position so that you can scroll through the content but always have it in reach.
On mobile it's stucked directly under the title and stays there even if scrolling through long pages.

For a better understanding please see the preview examples below...

----
#### Preview Desktop

![joplin-chapters](https://user-images.githubusercontent.com/29855366/36843869-9bf1c0fa-1d50-11e8-9228-bc59c1490529.jpg)

----
#### Preview Desktop Menu

![joplin-menu](https://user-images.githubusercontent.com/29855366/36845340-a2c8cd14-1d56-11e8-813d-90401eedfbb1.jpg)

----
#### Preview Mobile

![joplin-mobile](https://user-images.githubusercontent.com/29855366/36845588-a4b24096-1d57-11e8-995a-1ef4f45062f2.jpg)

----
**Conclusion**

This would be an outstanding usefully and unique feature setting joplin apart from its "competitors". I didn't find a comparable app that offers such a function and from my point of view it makes joplin an allround-information-management tool for daily and extensive usage even if you have to deal with large notes.

**Comment by jcgerhard** [comment]
...maybe it's better to be able to toggle (show/hide) the table of content on the mobile app, because it could also get very long and hog to much of the display.

**Comment by laurent22** [comment]
I guess it's mostly a UI thing since the existing Markdown format can already support multiple levels of headings.

Perhaps it should be something like in Word - a table of content that can be added to a note and be automatically updated? If that TOC is built in Markdown (with hash links) it will automatically work in all the apps without a need for custom UI.

**Comment by jcgerhard** [comment]
Good morning @laurent22,

absolutely right...should be an UI/UX thing. All needed information for a TOC can be taken out of the markdown code of the respective note.
Maybe you can have a look at https://typora.io/. In my opinion one of the best and well-designed markdown editor available. It has an "**outline**"-view that does exactly what I meant.
While typing headlines and subs and subsubs using the markdown hashtag syntax (#,##,###...and so on) it builds a very nice table of content instantly on the left side.
I made an example as you can see below. Typora also has a settings-feature to choose, if you want to have the TOC collapsible or not. If you have to read long notes/articles every day this is an outstanding feature that brings a lot of comfort!

## Example - Settings

![example-3](https://user-images.githubusercontent.com/29855366/37139492-58f9b8c6-22ae-11e8-9df4-376c645a9593.jpg)

## Example - Non-Collapsible TOC

![example-2](https://user-images.githubusercontent.com/29855366/37139599-cac321ae-22ae-11e8-8f87-c48256b9c49b.jpg)

## Example - Collapsible TOC

![example-1](https://user-images.githubusercontent.com/29855366/37139629-e391aaca-22ae-11e8-8563-424548bdacf8.jpg)

----
I could imagine, that the mechanism in the background is just iterating over the markdown code, recognizes each hashtag-headline and creates an appropriate nested html-list or something like that.
Maybe it's possible to add such a function to joplin...would be absolutely awesome, unique and first and foremost very helpful!!!

**Comment by inmabermejo** [comment]
This feature would be the greatest addition and a clear advantage over Evernote and similar apps. It has been requested by Evernote community for years (I'm following this up since 2011), but no answers about it yet.

For the ones that work with long notes, this is a lifesaver.

**Comment by xvol** [comment]
@laurent22 @jcgerhard 
Hey. Please check out my [repo](https://github.com/xvol/generatetoc). Maybe we can implement this into Joplin?

**Comment by cast-away** [comment]
not stale
