### ISSUE TITLE
Document or auto detect dependencies when building app

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2631]
Building the app requires a few external tools such as CocoaPods on macOS, rsync on Linux and macOS and windows-build-tools on Windows.

That should either be documented, or perhaps there's a way to auto-detect these dependencies when building the app and report it to the user.

**Comment by mhimanshu712** [comment]
I am on it!

**Comment by laurent22** [comment]
Could you describe first what's your plan of action please?

**Comment by Runo-saduwa** [comment]
@laurent22 this issue looks quite interesting, it wouldn’t be much of a heavy duty to add this information to the documentation for me, because I’m already working on the new build_troubleshooting.md file that you proposed in a PR some days ago. 

But the other part is what I don’t quite get, when you say “auto-detect the dependencies when building the app”, do you mean that there should be a message printed in the command line to inform the user about these other dependencies?

**Comment by laurent22** [comment]
For auto-detection, it's more like checking if, for example, rsync is installed, CocoaPod is installed, etc. and warn the user if they are not.

**Comment by mhimanshu712** [comment]
We can have a preinstall script, to check for dependency and warn the user if, they are not installed.
@laurent22

**Comment by mhimanshu712** [comment]
Or we can display a message before npm install using preinstall script that if the install fails then run some other script say "xyz.js", in xyz.js we will detect the OS, and install the appropriate build tools, for that OS.
This will be very easy to implement.

**Comment by bedwardly-down** [comment]
Is there anyway to check if the required programs are available in the common directories they usually would be installed in or check if the binaries are usable (like run a brief rsync test using the system's installed version; if it fails, stop and ask the user to check if they have it installed with their current package manager)? There are so many package managers and possible install directories for all of these things that it'd be a nightmare to support each individual one.

**Comment by laurent22** [comment]
@bedwardly-down, you can run `type rsync` and that will tell you if it's installed or not. For windows-build-tools that might be more complicated, but perhaps a `type node` followed by some node-specific command that tells if a package is installed globally or not.

**Comment by bedwardly-down** [comment]
> @bedwardly-down, you can run `type rsync` and that will tell you if it's installed or not. For windows-build-tools that might be more complicated, but perhaps a `type node` followed by some node-specific command that tells if a package is installed globally or not.

What I'm referring to is having that be in the preinstall script above. If you're going to check to see if it's installed and working and if not, you'll want to have them auto installed, that won't work unless you either account for all package managers or have the user manually install the required ones.

**Comment by bedwardly-down** [comment]
> @bedwardly-down, you can run `type rsync` and that will tell you if it's installed or not. For windows-build-tools that might be more complicated, but perhaps a `type node` followed by some node-specific command that tells if a package is installed globally or not.

That'd be a very good way to check it. If it's not installed, ask the user to make sure it's installed

**Comment by Runo-saduwa** [comment]
@laurent22 that’s the exact approach I’m using, `type rsync` Will return the version of rsync installed, as well as `pod —version` For cocoaPods. The only problem is with `windows-build-tools`, it doesn’t have a specific command to check if it’s installed but I’ll come up with a hack.

**Comment by mhimanshu712** [comment]
`windows-build-tools` installs two packages, one of them is `python` which is installed in the, `C:\Users\darkpunk\.windows-build-tools\python27`, it's also added to the systems `PATH` variable. So we can simply run _python -v_ to test.
The other package is Visual Studio Build Tools, which gets installed at `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools` but has no entry in the `PATH` variable.
VS Build Tools might be creating some registry entries upon installation, which I was not able to check.

**Comment by Runo-saduwa** [comment]
i don’t think checking for python is enough to judge if `windows-build-tools` Is installed because some users already had Python installed for other purposes before they installed `windows-build-tools`, I think
We should instead check if `windows-build-tools` Is installed globally

**Comment by laurent22** [comment]
To check if a package is installed globally: https://www.npmjs.com/package/is-installed-globally

Keep in mind that this check should be done on Windows only.

**Comment by Runo-saduwa** [comment]
Yeah, thanks I’m on it

**Comment by mhimanshu712** [comment]
@laurent22 We have a problem here with `npm list -g`.
These two packages(which are being installed by `windows-build-tools`, are very common, what if they haven't been installed by npm but by some other installer.

**Comment by mhimanshu712** [comment]
Have read my last comment @laurent22
