### ISSUE TITLE
sqfs_traverse_open error

### ISSUE THREAD

**Issue by wushifu32** [laurent22/joplin#2633]
## Environment

Joplin version:  1.0.179
Platform: lenovo-T440
OS specifics: ubuntu18.04

## Steps to reproduce

1. Download the AppImage package
2. Use the `Joplin_install_and_update.sh` to extract the AppImage
3. Can't use joplin from Gnome
4. Run the Joplin.AppImage in terminal, it turned out as the following:
```bash
colin@T440:~/.joplin$ ./Joplin.AppImage --appimage-extract
sqfs_traverse_open error
```
(I have installed the FUSE following this [wiki](https://github.com/AppImage/AppImageKit/wiki/FUSE))

**Comment by tessus** [comment]
Please move usaer questions to the forum.
