### ISSUE TITLE
Improve resource list screen

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2639]
1. There should be a warning at the top of the page saying: "This is an advanced tool to show the attachments that are links to your notes. Please be careful when deleting one of them as they cannot be restored afterwards."

2. When clicking "Delete", add a confirmation dialog saying: "Delete attachment "%s""?

3. There should be a vertical scroll bar on this screen

4. Style should match that of other setting screen - in particular use `theme.fontFamily` for the text.

5. Make sure that it works with themes, and the dark theme in particular (it currently does not).

5. Rename menu item from "Resources" to "Note attachments..."

6. If a resource does not have a title, display "Untitled"

6. Enforce a width of 100% for the table so that it doesn't look like the screenshot below. In that screenshot, the first resources don't have a title so they are blank row. There's also a resource with a very long name, which means the title row goes off screen, and the rest of the table is somewhere on the right. The title row should be constraint so that it doesn't make the list goes off-screen.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/1285584/75717635-67ed2c80-5cc9-11ea-96ee-aac742f4d165.png">

**Comment by laurent22** [comment]
@talkdirty, there are a few issues with the resource list as listed above, and in case you're interested in looking into it. Otherwise I've tagged it as a good first issue so perhaps someone else will take it.

**Comment by rabeehrz** [comment]
@talkdirty Will you be looking into this? If not, I would love to work on this.

**Comment by RedDocMD** [comment]
I am interested in applying for GSoC 2020. Can I work on this as a first issue?

**Comment by talkdirty** [comment]
Go for it @rabeehrz !

**Comment by rabeehrz** [comment]
> Go for it @rabeehrz !

Thank you! I'm working on it.

**Comment by deadpool1999** [comment]
Hello I am a open source programming aspirer , am I qualified for any contributions , if yes please do advice me anything.

**Comment by Rolograaf** [comment]
As a suggestion, it would be nice if resources that are an image, besides the name of the image a little thumbnail would be displayed?

**Comment by rabeehrz** [comment]
> As a suggestion, it would be nice if resources that are an image, besides the name of the image a little thumbnail would be displayed?

Yeah, but how would that work with other types of resources?

**Comment by Hardik500** [comment]
I would like to work on this issue if it's still open.

**Comment by pranavmodx** [comment]
Please assign it someone to avoid multiple people working on the same issue. If it is open, I could take this up.

**Comment by laurent22** [comment]
Done

**Comment by rabeehrz** [comment]
@laurent22 Urmm, I was still working on this.

**Comment by laurent22** [comment]
Is there someone already working on this though? Please let me know.

**Comment by rabeehrz** [comment]
> Is there someone already working on this though? Please let me know.

Yeah. I was working on this. 😅

**Comment by laurent22** [comment]
Ok I've re-assigned it to you. It's actually a big task so we can also split it if you prefer.

**Comment by rabeehrz** [comment]
Yeah it is kind of big, that’s why it is taking me some time. But I’ll get it done.

**Comment by rabeehrz** [comment]
The PR for this might be delayed a bit, as I’m in the middle of drafting my proposal.

**Comment by matthewb96** [comment]
There are two additional columns I think would be useful to have:
- Location - the name of the note that contains the resource, and maybe a link to the position in that note; and
- File Type -  the file extension of the resource, this could be useful if it also had a filter so just images could be selected for example.

**Comment by laurent22** [comment]
Any news on these changes @rabeehrz? Would it make sense to let someone else working on it?

**Comment by rabeehrz** [comment]
> Any news on these changes @rabeehrz? Would it make sense to let someone else working on it?

Yep @laurent22. I'm mostly focused on my proposal right now. You can assign this issue to someone else.

**Comment by talkdirty** [comment]
Feel free to assign to me - I'll have plenty of Covid related free time this weekend

**Comment by laurent22** [comment]
Great, I've assigned it to you @talkdirty

**Comment by Veyska** [comment]
Couple thoughts (hopefully this is the right/a good place for 'em):
* With regards to possible orphans, presuming it's possible to determine this maybe just a column for "Known embeds" count and let the user beware, given the warning that's already being added?
* I'd pruned a few overly large embeds early on and finally used Resources to prune the in-app data for them (which is wonderful) but this also led to me discovering that clicking on a link to a non-existent file just does... nothing.  Possible to have some sort of pop-up letting the user know?  And/or maybe some sort of indication for "file not found", I've pruned a few other files (mostly from pages that clipped messily) and trimming the Resources internally to match would be nice.
