### ISSUE TITLE
Internal anchors no longer working

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2640]
Not working:

```
<a href="#end">Goto End</a>
bla
bla
...
<a id="end"></a>
```

Goto End is rendered to plain text, no link.
With version 1.0.179 no problem.

Also affects note links to headers using the format:

`[test](:/d7d6c9c9e6444b5e8336eebb633477d9#target2)`

**Comment by RedDocMD** [comment]
@laurent22 This is again an issue with the new `CommonMarkdown` syntax. Please see the comments I made in  [Issue #2643](https://github.com/laurent22/joplin/issues/2643#issuecomment-594044131)

**Comment by tessus** [comment]
Hmm. `<a href="#internal-link2">Goto Internal Link 2</a>` does not even render a link. Even after the commit above.

**Comment by tessus** [comment]
Sorry, forgot to run `npm run build`.
