### ISSUE TITLE
build issue? husky issuing a git error

### ISSUE THREAD

**Issue by taw00** [laurent22/joplin#2641]
Joplin 1.0.187
RPM build on Fedora 31
Using joplin source tarball

Husky is trying to do something with git. But the source archive is not a git repository, so an error is generated. The source build continues and the binary functions, but I don't know if this leads to some corner-case instability or not.

From within the build:
```
+ npm install

> husky@3.0.2 install /builddir/build/BUILD/joplin-1.0/joplin-1.0.187/node_modules/husky
> node husky install

husky > Setting up git hooks
Command failed: git rev-parse --show-toplevel --absolute-git-dir
fatal: not a git repository (or any of the parent directories): .git
husky > Failed to install

> husky@3.0.2 postinstall /builddir/build/BUILD/joplin-1.0/joplin-1.0.187/node_modules/husky
> opencollective-postinstall || true

Thank you for using husky!
```

**Comment by laurent22** [comment]
Should be fine as Husky is used only on pre-commit hook.

**Comment by taw00** [comment]
Okay. Closing for now until something suggests I should re-open it.
