### ISSUE TITLE
Foldable sections and hidden elements not working any more

### ISSUE THREAD

**Issue by nemesis5** [laurent22/joplin#2643]
# Environment

Joplin version: v1.0.187
Platform: Linux
OS specifics: Manjaro Linux, latest updates

The issue does not occur with v1.0.179, so it is new in v1.0.187.

## Steps to reproduce

I will describe two maybe different issues here, because I think they are coming from the same issue in the Joplin code base. 

I use Joplin in dark mode (normally with nord theme). This is necessary to see the right behavior for the hidden elements.

### Foldable sections not working

1. Insert the following code inside the markdown editor
```
<details markdown='1'><summary>

Screenshot
</summary>
    
test
</details>
```
2. Inside the rendered view, it should display a foldable section which is closed by default. --> With V1.0.187, the folding arrow is not shown.

### Hidden elements not working

1. Take my complete userstyle.css into the .config/joplin-desktop/userstyle.css
```
/* Make complete font size smaller */
/*
body { font-size: 12px; }
*/

/* Background image in rendered markdown image */
body {
  background-image: url("/home/dasc/.config/joplin-desktop/background-images/arch-linux/yellow-arch-tri_without-Text.jpg");
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-position: center;
  background-color: black;
}

/* Code boxex:
 *	- Makes all code boxes transparent - background image can be seen through 
 *  - Makes code blocks more compact 
*/
.hljs {
	opacity: 0.9;
	font-size: 12px;
	line-height: 1.5;
}

/* Code to also make inline code transparent - makes all inline-code less readable and brings no high effect */
/*
.inline-code {
	opacity: 0.9;
}
*/

/* Configuration of hidden text - can be used by inserting <span class="hidden">password</span> into any markdown text in joplin. 
 * This will hide the text in the preview and as soon as you hover over it with the mouse it is fade in */
.hidden {
  opacity: 0;
  transition: opacity 0.5s ease;
}
.hidden:hover {
  opacity: 1;
}
```
2. Use the following code inside the markdown editor:
```
This is a text with a hidden text containing "<span class="hidden">magic text</span>". Markdown syntax in hidden area is fully supported, e.g. for <span class="hidden">`hidden magic code snippets`</span>.

The following multiline stuff is also hidden:
<div class="hidden">

- [x] hidden list element 1
- [x] hidden list element 2

</div>
```
3. Inside the rendered view, it should not display the hidden content and show it as soon as you hover over with the mouse --> With V1.0.187, the folding arrow is not shown.

## Describe what you expected to happen

I created first a complete new joplin-desktop folder and added my userstyle.css to it. Afterwards I did the test with Joplin V1.0.179. Then I just closed this Joplin and opened a V1.0.187 Joplin.

Here you can see the screen recording with Joplin V1.0.179:
![Joplin-179](https://user-images.githubusercontent.com/10476509/75757983-a3bcdc00-5d33-11ea-843b-64c305a69665.gif)

Here you can see the screen recording with Joplin V1.0.187:
![Joplin-187](https://user-images.githubusercontent.com/10476509/75757986-a4ee0900-5d33-11ea-81ec-aa9b456f79f1.gif)

**Comment by tessus** [comment]
It seems that `<div>` sections in general do not work anymore.

**Comment by RedDocMD** [comment]
@laurent22 @PackElend Can I work on this issue?

**Comment by laurent22** [comment]
This sounds like an issue with custom CSS and not something we explicitly support, or am I missing something? For info JavaScript event handler have been disabled in the latest version so maybe it's affecting this.

**Comment by tessus** [comment]
Maybe the second part has to do with custom css. But the first part is simple html that doesn't work anymore.

**Comment by RedDocMD** [comment]
Has the markdown engine been changed recently?

**Comment by laurent22** [comment]
We also don't explicitly support HTML (we just pass it to the iframe but don't do anything special with it), so not sure there's something to fix here.

@RedDocMD, if you can find a fix and it's not too complicated, I guess we could merge the PR though.

**Comment by RedDocMD** [comment]
I believe that the html generated by the Markdown renderer can be manipulated with JS to fix this.

**Comment by laurent22** [comment]
> I believe that the html generated by the Markdown renderer can be manipulated with JS to fix this.

That's where it would be too complicated. We don't do any special processing for HTML, it's outside the scope of this project. We basically pass it as is to the browser and normally it renders fine.

But maybe we don't need to do anything complicated in this case. The first step would be to find what's causing the bug, and if it's something straightforward maybe we can fix it.

**Comment by RedDocMD** [comment]
Actually, if we directly pass that HTML in CodePen, it works. It also works in Chrome as far as I can tell. So it should work for the desktop app at least (which uses the Chromium engine).

**Comment by RedDocMD** [comment]
@laurent22, the foldable section issue is **not** a bug but just how `markdown-it` works based on the `CommonMarkdown` specification. Taking an excerpt from the latest `CommonMarkdown`  specification([link to it](https://spec.commonmark.org/0.29/#html-blocks)):
![image](https://user-images.githubusercontent.com/54888685/75795740-bf0e0280-5d98-11ea-9c70-d93df6dad753.png)
Therefore the correct markdown for the foldable sectionn is:
`<details>`
`<summary>Screenshot</summary>`
`test`
`</details>`

It then works as follows:
<details>
<summary>Screenshot</summary>
test
</details>

**Comment by RedDocMD** [comment]
@laurent22 The second problem is also related to the `CommonMarkdown` specification. In particuklar `<span>` elements are no longer recognized as HTML. Taking it from their site:
 
![image](https://user-images.githubusercontent.com/54888685/75797374-14e3aa00-5d9b-11ea-82c5-33740c1a62e8.png)

**Comment by RedDocMD** [comment]
Therefore I propose that this **bug be closed** because it is not really a bug but a limitation of the Markdown syntax.

**Comment by tessus** [comment]
@RedDocMD you just disproved your own statement.

According to above excerpt of the specifications, `<div class="xxx">` is still supported, but it no longer works in Joplin.

So both items in this issue are perfectly valid.

**Comment by tessus** [comment]
So either Joplin follows the Markdown specs or it does not. If we ignore this issue, it's the latterr.
It's as simple as that.

**Comment by RedDocMD** [comment]
@tessus 
No, it is the blank lines that are disallowed.
If you look at the examples given in the spec, it says that there are **two** HTML blocks instead of one. The point is that if you remove the blank lines it works fine. That is a limitation of Markdown not Joplin.

**Comment by tessus** [comment]
I'm talking about:

```
<div class="xxx">

- [x]  list element 1
- [ ]  list element 2

Text here.

</div>

Text there.
```

This is perfectly valid, unless I missed anything in the specs.

**Comment by RedDocMD** [comment]
> I'm talking about:
> 
> ```
> <div class="xxx">
> 
> - [x]  list element 1
> - [ ]  list element 2
> 
> Text here.
> 
> </div>
> 
> Text there.
> ```
> 
> This is perfectly valid, unless I missed anything in the specs.

If you remove the blank lines it still works.
The blank lines are disallowed

**Comment by RedDocMD** [comment]
The blank lines after the <div> and before </div>, that is

**Comment by RedDocMD** [comment]
The blank line after the `<div>` specificaly

**Comment by tessus** [comment]
Ok, I've now read almost the entire commonmark spec.

**You are correct.**

I didn't know that it was different to Gruber's, but even that didn't throw me off.
It was rather the fact that Joplin allowed things that were not supposed to work, but did.

Unfortunately this new behavior makes certain things impossible. It won't be possible to change the styling for a single note by defining a `div`. See also [this discussion](https://discourse.joplinapp.org/t/toggle-headings-numbering/6490?u=tessus) on the forum.

**Comment by laurent22** [comment]
You were indeed correct that there was an issue with HTML rendering in the latest version, but it was a problem with Markdown compliance. Instead I've recently added a filter to sanitize HTML and it was incorrectly closing certain tags after filtering, which resulted in broken HTML. This should be fixed in cb2df32d914f20de694b6c9742d541b5bef9ca25

**Comment by taw00** [comment]
Thank you @laurent22 for addressing the sanitation issue.

As for this larger issue, `<span>` no longer being valid is really, really inconvenient. Alas.

**Comment by laurent22** [comment]
> As for this larger issue, <span> no longer being valid is really, really inconvenient. Alas.

This is fixed too. The issue was with inline elements which were incorrectly converted from `<span>hello</span>` to `<span></span>hello`. So the next release should fix this. It doesn't happen within DIV because block elements were processed differently.

**Comment by tessus** [comment]
Please also have a look at the follwing [comment](https://discourse.joplinapp.org/t/toggle-headings-numbering/6490/15?u=tessus), which is quite interesting.

**Comment by taw00** [comment]
> Please also have a look at the follwing [comment](https://discourse.joplinapp.org/t/toggle-headings-numbering/6490/15?u=tessus), which is quite interesting.

Maybe someone needs to reach out the commonmark people. They are listed and the various forums/chats are on the https://commonmark.org/ page. Clarification as to what is intended would be good. Maybe they have a buggy implementation of the spec. ? Maybe ?

**Comment by nemesis5** [comment]
@laurent22 I tried the same test with Joplin V1.0.189, where your fix should be in, but there changed exactly nothing on the original bug behavior:
![Joplin-189](https://user-images.githubusercontent.com/10476509/75957107-9893b880-5eb9-11ea-8100-37d9a78332a9.gif)

Shouldn't we reopen that bug? As far as I understood, you just fixed some missbehavior with `<span>` tag handling, but also the span tags in my example did not work with V1.0.189.

**Comment by RedDocMD** [comment]
@nemesis5, have you read the comments above? If you do, you will see that it says that the problem lies in the Markdown spec and not Joplin itself.

**Comment by nemesis5** [comment]
## Foldable sections not working

@RedDocMD , yes, I have read all the comments and I understood, that the empty lines are producing the issue with the folding sections. I have the following issue with the folding section stuff:

The code from your comment
```html
<details>
<summary>Screenshot</summary>
test
</details>
```
generates a foldable section, yes, but the content is not rendered as markdown. If you e.g. use 
```html
<details>
<summary>Screenshot</summary>
- [ ] test
- [ ] test2
</details>
```
there is no checkbox list, as you would expect it from markdown renderers. This is why I introduced an empty line after the `</summary>` tag, because then the content is rendered as markdown. But then the section is not foldable any more because of the newline.

**So maybe the missing markdown interpretation is here the issue,** if I have to delete all new lines.
I hope that there will start a discussion between the right Joplin people and the common markdown people, because @tessus is right, "this new behavior makes certain things impossible. It won't be possible to change the styling for a single note by defining a div. See also this discussion on the forum."

## Hidden elements not working

@RedDocMD, I mentioned that you are right, the following code works, so the paragraph must be embedded into a html tag:
```
<dummy>
This is a text with a hidden text containing "<span class="hidden">magic text</span>". Markdown syntax in hidden area is fully supported, e.g. for <span class="hidden">`hidden magic code snippets`</span>.
</dummy> 
```

My previous code did not work:
```
This is a text with a hidden text containing "<span class="hidden">magic text</span>". Markdown syntax in hidden area is fully supported, e.g. for <span class="hidden">`hidden magic code snippets`</span>.
```
In this issue I had a look at the produced rendered html output and mentioned, that the `<span>` tags were completely removed. 
```
<p>This is a text with a hidden text containing "magic text". Markdown syntax in hidden area is fully supported, e.g. for <code class="inline-code">hidden magic code snippets</code>.</p>
```
@laurent22, you talked about your changed sanitation of the `<span>` tags: Are you sure this is working correctly in V1.0.189?

**Comment by RedDocMD** [comment]
@nemesis5, of course, it is not rendered as Markdown within the`<details>` tag. According to the current `CommonMarkdown` spec, all text within the start and end tag is not processed as Markdown at all, but is rather left as is.
When you add a blank line after the `<summary>` tag, that is treated as an end tag according to rule 6. Thereafter, it is processed as markdown (and you see the checkbox), while the end `</details>` tag is just ignored (or processed as garbage). 
As for the `<span>` issue, I don't see anything unexpected happening. Would you please explain a bit more what is the new issue?

**Comment by nemesis5** [comment]
@laurent22 Your latest prerelease V1.0.189 fixed both issues (I think your official work ticket for that topic was  #2567. Thank you.
