### ISSUE TITLE
Embedding javascript

### ISSUE THREAD

**Issue by sciurius** [laurent22/joplin#2645]
Assume we have the following content somewhere in a note:

    <script>alert("Foo")</script>

The Android client (1.0.312) dutyfully displays the alert.
The Linux desktop (1.0.187) seems to ignore this.

I'm not sure what would be the correct/desired/intended behaviour.

**Comment by laurent22** [comment]
The bug is that it works in Android, so I'll disable it.

**Comment by sciurius** [comment]
Good!

**Comment by tessus** [comment]
We should note this in the documentation. According to the specs, `<script>` is allowed.
In fact we should disclose all differences to the CommonMark specs, if there were any.

(I have recently brushed up my commonmark spec knowledge. ;-))

**Comment by laurent22** [comment]
@tessus, I'm definitely not as familiar was you are with the CommonMark spec. Besides the `<script>` tag, are there any other differences? I suppose the way we now strip off all the event handlers is a difference too.

**Comment by tessus** [comment]
@laurent22 I'm not sure. I hoped you could tell me that, since you might have deactivated something else. So basically anything that was disabled should be mentioned.

I only read most of the specs today because of the other issue that turned out not the be an issue after all....

**Comment by laurent22** [comment]
Fixed in 71d1e6eb82117b5b3c2d541eb358007ea31d0fc9
