### ISSUE TITLE
Supressing checkboxes

### ISSUE THREAD

**Issue by sciurius** [laurent22/joplin#2646]
Assume we have the following content somewhere in a note:

````
<style>
.md-checkbox input[type="checkbox"]:not(:checked),
.md-checkbox input[type="checkbox"]:not(:checked)+label {
	display:none;
}
</style>
## Topic
## Topic
- [ ] Seitan
- [ ] Blanke bonen
- [ ] Berglinzen
- [ ] Couscous
- [ ] Citroensap
- [ ] Limoensap
## Topic
- [ ] Seitan
- [ ] Blanke bonen
- [x] Berglinzen
- [x] Couscous
- [ ] Citroensap
- [ ] Limoensap
## Topic
## Topic

````

The Android client (1.0.312) suppresses all the unchecked checkbox lines.
![Screenshot_20200303-135210_Joplin](https://user-images.githubusercontent.com/1118804/75777480-59008b80-5d56-11ea-91c8-9161abe37bf4.jpg)

The Linux desktop (1.0.187) does not show the unchecked checkbox lines, but some additional vertical space is added. 
![scrot20200303134919](https://user-images.githubusercontent.com/1118804/75777203-d24bae80-5d55-11ea-865e-c6adb678a2f3.png)

AFAIK this is a regression since I'm pretty sure the Linux desktop used to behave the same as the Android cient.

**Comment by laurent22** [comment]
The HTML structure might have changed, so you might need to update your CSS. There's unfortunately not guarantee that the HTML will remain stable from one version to the next. In general userstyle.css is "use at your own risk" (or better, don't use it, but that's up to the user).

**Comment by laurent22** [comment]
Sorry I've spoken too quickly and there was indeed a bug with HTML rendering in the latest version. Normally this commit should fix it cb2df32 and it will be part of the next release.

**Comment by sciurius** [comment]
I tried git 880134ce804a4b555463c6a7b5409f41aa914366 (that includes this) but the rendering is still affected.

**Comment by laurent22** [comment]
Could you check the HTML with the dev tools? Where does the new lines come from?

**Comment by laurent22** [comment]
These blank spaces seem to be a different issue. The md-checkbox class has a margin, which you would need to remove with your CSS.

<img width="824" alt="image" src="https://user-images.githubusercontent.com/1285584/75867979-527a1e80-5dff-11ea-9bac-e3f8fc8730ab.png">

Don't think that was changed recently, but even then it doesn't seem to be a bug.

**Comment by sciurius** [comment]
Rendering was ok up to previous release (1.0.179, January 24) so it is a recession due to a recent change.

**Comment by sciurius** [comment]
In 1.0.190, hiding the checkboxes seems to not work at all anymore.
I'd suggest re-opening this issue.
