### ISSUE TITLE
Links appear to be prefixed with working directory

### ISSUE THREAD

**Issue by edrich49** [laurent22/joplin#2647]
## Environment

Joplin version: 1.0.187 (prod, linux)
Platform: Linux
OS specifics: Debian

## Steps to reproduce

1. View the "Welcome to Joplin!" note in the "Welcome! (Desktop)" notebook.
2. In the viewer pane, click a link such as "Markdown syntax".
3. 

## Describe what you expected to happen

I expected the link to be navigated to, as exhibited by the tooltip -- "https://joplinapp.org/markdown/", whereas what actually happened was that I received an error dialog box: "/home/richard/Downloads/Joplin/https:/joplinapp.org/markdown: No such file or directory". ["/home/richard/Downloads/Joplin" was my working directory at the time I invoked the program.]

This error also occurs with Joplin version 1.0.179.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/4282429/log.txt)

**Comment by bedwardly-down** [comment]
If you can remove the log text above and just upload the log.txt file, that should be enough. It's under your `joplin-desktop` directory.

**Comment by edrich49** [comment]
Apologies. Hope this is now satisfactory.

**Comment by rabeehrz** [comment]
I couldn't reproduce this issue on Joplin 1.0.187 desktop.

**Comment by bedwardly-down** [comment]
I can't reproduce this either. @rabeehrz, what Linux distro are you using? I'm on Artix Linux.

What browser are you using, @edrich49? Maybe it's tied to that specific one and that build version for Debian?

**Comment by mhimanshu712** [comment]
Couldn't reproduce in Ubuntu.

**Comment by edrich49** [comment]
Apologies. Hope this is now satisfactory.

**Comment by edrich49** [comment]
@bedwardly-down, I'm using the Firefox browser, version 68.5.0esr (64-bit) running under Debian Linux.

**Comment by edrich49** [comment]
I still have this problem. Any more ideas, anyone, please?

**Comment by edrich49** [comment]
The problem is still present in 1.0.199.
