### ISSUE TITLE
HTML within the markdown no longer renders

### ISSUE THREAD

**Issue by taw00** [laurent22/joplin#2651]
1.0.187
Fedora 31
My own build ( https://github.com/taw00/joplin-rpm )
`<div>` tag no longer functions and leaves a `<` behind in rendering.
`<span>` doesn't work (but leaves nothing behind.
`<b>` etc doesn't work.
Oddly, `<br />` _does_ work still.

I'm sorta hoping this is a general problem and not just a problem with my build. I haven't had functional bugs specific to my builds in the past and I hope not to start now.

See attached screenshot and I have attached two log files. There were no errors in log.txt.
![Screenshot from 2020-03-03 17-40-19](https://user-images.githubusercontent.com/6908872/75826996-b3a9df80-5d76-11ea-91b9-0adbc5aa865e.png)
[commandline-output.txt](https://github.com/laurent22/joplin/files/4284000/commandline-output.txt)
[console-log-1583275188164.log](https://github.com/laurent22/joplin/files/4284001/console-log-1583275188164.log)

**Comment by tessus** [comment]
Yep, this is not a bug. see also #2643

**Comment by taw00** [comment]
For folks stumbling upon this issue. The larger problem I was reporting is indeed not a bug. But that pesky little `<` left behind in the rendering is indeed a bug. I'm not going to change the labeling of this issue for something that was mentioned in passing, but you can find the resolution to that problem within the comments of the issue that tessus linked-to above.
