### ISSUE TITLE
[Feature Request] Option to have a visual note

### ISSUE THREAD

**Issue by PRASHANT1104** [laurent22/joplin#2654]
Hi all ! Why don't we have visual note option , where we can draw something and save it ? I think it'd be cool idea to have it . If it is desired , i would love to get started on it.

**Comment by laurent22** [comment]
Is that a bug though?

**Comment by PRASHANT1104** [comment]
@laurent22 My bad , It got labelled as bug . Anyways , i tried implementing a part of it . What should i do when the window size is changed , scrollbar or change the image size as well ?

**Comment by Rishgod** [comment]
> @laurent22 My bad , It got labelled as bug . Anyways , i tried implementing a part of it . What should i do when the window size is changed , scrollbar or change the image size as well ?

Just a side note, issues are strictly for bugs and enhancements.
For any feature request go to [discourse forums](https://discourse.joplinapp.org/latest)
