### ISSUE TITLE
Missing Next/Previous navigation buttons

### ISSUE THREAD

**Issue by glowinthedark** [laurent22/joplin#2655]
There is no way to jump to the previous/next note in the history stack. In fact there is no history stack to begin with, at least not in the current UI.

Filing this as a bug since I see it as a failure to identify the core functionality for a note taking app. Go to previous/next is a higher priority use case than, for example, note versioning and revision tracking which most people would probably never use yet there has been significant effort and time spent on it.

**Comment by laurent22** [comment]
Not a bug, and there's a PR for it.
