### ISSUE TITLE
Notes appear and disappear when creating new notes with Cmd+N

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2656]
> When I use the shortcut (Cmd+N) or the menu item, the following weird thing happens:

![](https://aws1.discourse-cdn.com/standard14/uploads/cozic/original/2X/4/4c880c840a35f96f1bd64744f62dd2da0e8f8ab6.gif)

>This does not happen, when I click on New note in the tool bar.

https://discourse.joplinapp.org/t/please-help-test-the-new-desktop-pre-release/6445/48?u=laurent

**Comment by Hardik0307** [comment]
@laurent22, I'm looking at this and working on this. 
May I go ahead with this issue#2656?

**Comment by rabeehrz** [comment]
Also happens on File->New Note.
