### ISSUE TITLE
Joplin updater opens over fullscreen windows / games

### ISSUE THREAD

**Issue by krc** [laurent22/joplin#2658]
I had previously opened Joplin, but the window was closed, so it was just in the system tray. I was playing Overwatch in fullscreen mode when Joplin decided to try and update. 

Normally I would expect a program in the system tray to just change the icon there to indicate there was an update available, or perhaps at most do that and make a noise.

However Joplin popped up a full window, and in the process minimized my full screen game. Even if it was going to put up a window (which it shouldn't), it definitely should not raise it over other windows and most especially not over a fullscreen program.

Beyond this issue, there was some outright bug in how it did it, my mouse was stuck in the center of the screen and only vibrated when I tried to move it. I am not sure if the keyboard input was fully working or not, I was in a bit of a rush to try to get back to my team in the game. I did manage to bring up task manager and kill Joplin, at which point the mouse control returned and I was able to return to my game.

## Environment

Joplin version: 1.0.178
Platform: Windows 10
OS specifics: current

## Steps to reproduce

Have Joplin running
play a fullscreen game
wait for Joplin to try to pull down an update

## Describe what you expected to happen

Joplin would notify me there was an update in an unobtrusive and non-disruptive way

**Comment by bedwardly-down** [comment]
I'm sorry this happened. I'm not on Windows or have Windows on any of my hardware, so I can't reproduce this, but I can definitely see this being a big problem. Joplin is a work in progress that is always needing improvements and whatnot. Do you have any suggestions on how to make this less obtrusive for you that others may be able to relate to?

**Comment by krc** [comment]
I don't know much about windows programming myself, nor electron programming, but I think something with this might be good https://www.electronjs.org/docs/tutorial/notifications

Possibly a non-modal (i.e. you aren't forced to interact with it) pop-up window could be ok if Joplin has a window open already (not just running in the tray), or better yet, only if the window already has focus.

Even that though I feel isn't too ideal, I would much rather have something appear in the main UI than even a non-modal pop-up. Firefox is a good example, it has a "toast" pop-up when there is a new version, but it is part of the main UI, not a separate window from an OS/window manager PoV. And as such it doesn't/can't raise the window if it isn't already focused.

**Comment by tegkhanna** [comment]
Can anyone familiar with the repo lead me to files where I should be looking regarding this bug?
