### ISSUE TITLE
Tags with spaces will collapse to 2 lines

### ISSUE THREAD

**Issue by wazabees** [laurent22/joplin#2659]
## Environment

Joplin version: 1.0.187 (pre-release)
Platform: Windows 10
OS specifics: Version 1909

## Steps to reproduce

1. Make some tags with spaces
2. Decrease the Joplin application window width

![Joplin_lrR3UyhevX](https://user-images.githubusercontent.com/14857141/75913476-4ddf5580-5e53-11ea-904e-715280390130.png)

## Describe what you expected to happen
Either that the tag boxes grew to accommodate multiple lines, or text to be cut off.

**Comment by laurent22** [comment]
For Good First Issue: tag names should not be allowed to wrap. If there are too many tags, we let them go off-screen for now.

**Comment by PRASHANT1104** [comment]
@laurent22 Can you assign this to me ? I would like to work on it .

**Comment by Runo-saduwa** [comment]
I’ll also look into this

**Comment by laurent22** [comment]
> What would be the solution for the future? Add another row for tags?

I think we could put a small double-arrow at the end of the tag bar, then when the user clicks on it, they see the complete list (which can be scrollable). This is relatively standard, at least that's how the bookmark bar works in Firefox and Chrome.

**Comment by PRASHANT1104** [comment]
@laurent22 did that PR close the issue ?

**Comment by tessus** [comment]
As soon as it is merged it will close this issue.

**Comment by tessus** [comment]
> I think we could put a small double-arrow at the end of the tag bar, then when the user clicks on it, they see the complete list (which can be scrollable). This is relatively standard, at least that's how the bookmark bar works in Firefox and Chrome.

maybe a new `good first issue` presents itself.... ;-)
