### ISSUE TITLE
[Feature Request] Custom font in Editor

### ISSUE THREAD

**Issue by dayfuaim** [laurent22/joplin#266]
### Operating system

- [x] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [x] Desktop
- [x] Mobile
- [ ] Terminal

%SUBJ%.

Because "Courier [New]" at Windows is not very readable (and usable) having very small size.
And Roboto at Android... Monospace font (at least) would be more usable.

**Comment by Munchotaur** [comment]
+100 for this. Joplin is great as a note-taking app *for those with good eyesight*. For the rest of us it's a painful squint -- lousy for accessibility.
