### ISSUE TITLE
1.0.189 -- HTML sanitizer code still seems broken

### ISSUE THREAD

**Issue by taw00** [laurent22/joplin#2662]
Fedora 31 build (my own)
The console had no relevant errors, nor does log.txt

The sanitation code is still not quite ready for primetime.
![Screenshot from 2020-03-04 23-37-07](https://user-images.githubusercontent.com/6908872/75948729-31064a80-5e72-11ea-8190-0524ba1a6c1c.png)

**Comment by laurent22** [comment]
Fixed in 71d1e6eb82117b5b3c2d541eb358007ea31d0fc9
