### ISSUE TITLE
label <s>and <u> don't works in Windows 10

### ISSUE THREAD

**Issue by letian304** [laurent22/joplin#2664]
label `<s>`and `<u> `don't works in Windows 10, but works very well in android.
## Environment

Joplin version: 1.0.189
Platform: windows 10

**Comment by Rishgod** [comment]
Hey @letian304 , I checked, I don't have a problem using `<s>` or the `<u>` tag

<img width="839" alt="Annotation 2020-03-05 151731" src="https://user-images.githubusercontent.com/54576074/75969220-9e5abf80-5ef4-11ea-8e52-878826cbb5d1.png">

**Comment by laurent22** [comment]
Fixed in 71d1e6eb82117b5b3c2d541eb358007ea31d0fc9
