### ISSUE TITLE
Support automatic dark/light theme switching according to OS settings

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2665]
Joplin should honour the dark/light theme settings of the operating system.

Add the following settings to config screen:

- Auto Detect Theme (`theme.autodetect`): a checkbox
- Prefered Dark Theme (`theme.preferedDarkTheme`): dropdown with all the themes
- Prefered Light Theme (`theme.preferedLightTheme`): dropdown with all the themes

So you need three new setting values: `theme.autodetect`, `theme.preferedDarkTheme` and `theme.preferedLightTheme`.

When `theme.autodetect` is **true**, the `theme.preferedDarkTheme` and `theme.preferedLightTheme` dropdown are visible, and the "Theme" dropdown is hidden.

When `theme.autodetect` theme is **off**, the `theme.preferedDarkTheme` and `theme.preferedLightTheme` dropdown are hidden, and the "Theme" dropdown is visible.

Whenever the theme is auto-updated, the `theme` setting value should be set to the relevant theme ID.

Related to: https://discourse.joplinapp.org/t/night-mode-button/6581

**Comment by Rishgod** [comment]
I'm working on it!

**Comment by anjulalk** [comment]
> I'm working on it!

Hey, are you working on the mobile app or desktop? I'd like to implement this on the desktop application.

**Comment by Rishgod** [comment]
> > I'm working on it!
> 
> Hey, are you working on the mobile app or desktop? I'd like to implement this on the desktop application.

Hey @anjulalk , I am working on the desktop first almost done with solving this issue, and I don't want to scrap my work now 😕 , can you please work on some other issue thanks! 
**_You are more than welcome to work on this if I'm unable to solve this_**(I let you know about that in a day or two)

**Comment by raghavg27** [comment]
did anyone got this done?

**Comment by Rishgod** [comment]
> did anyone get this done?

I'm working on it @raghavg27

**Comment by kowalskidev** [comment]
@Rishgod  are you still working on it? would you mind if I work on this issue.

**Comment by kowalskidev** [comment]
After working for 3 days I able to add `autodetect `checkbox and two other drop downs based on selected checkbox and also able to detect operating system theme. 
Now the issue I'm facing is I unable to save changes made on 'public' property of all three drop downs after saving configuration when I restart app the public property set to it's default values. There's no function for setting public value like `setValue()` for changing values. 

I tried making new function similar to `setValue()` i.e. `setPublic() `but it return some SQLITE error!
please help me how to change public property and save it state

There's also **show** property in metadata I didn't get what show property does? please enlighten me.

**Comment by kowalskidev** [comment]
Finally I have fixed this issue.
@laurent22  I have one doubt, Do we need dark mode button like mention here ? [Night Mode Button](https://discourse.joplinapp.org/t/night-mode-button/6581) because as you mentioned in the issue

> When `theme.autodetect` is **true**, the `theme.preferedDarkTheme` and `theme.preferedLightTheme` dropdown are visible, and the "Theme" dropdown is hidden.
> 
> When `theme.autodetect` theme is **off**, the `theme.preferedDarkTheme` and `theme.preferedLightTheme` dropdown are hidden, and the "Theme" dropdown is visible.

if we are adding Dark Mode button then are we providing this options for Dark mode button or Auto Detect checkbox or both?

**Comment by kowalskidev** [comment]
@laurent22  I have one question: By clicking on Auto Detect checkbox how can we notify the user about detected theme? whether detected theme is dark or light?
Here I thought that we can show only one option based on detected theme like if detected theme is dark we only show Preferred Dark Theme drop down and vice-versa.

Any other solution?

**Comment by xplosionmind** [comment]
There is a further improvement which could be made to implement this: along with the option to follow system light/dark theme, a button to arbitrarily switch between dark theme and light theme could be added.

This improvement is further described on the [Discourse Forum](https://discourse.joplinapp.org/t/feature-idea-automatic-dark-light-theme-switching-according-to-os/6010/11?u=xplosionmind)

**Comment by kowalskidev** [comment]
> There is a further improvement which could be made to implement this: along with the option to follow system light/dark theme, a button to arbitrarily switch between dark theme and light theme could be added.
> 
> This improvement is further described on the [Discourse Forum](https://discourse.joplinapp.org/t/feature-idea-automatic-dark-light-theme-switching-according-to-os/6010/11?u=xplosionmind)

Did you mean NIGHT MODE BUTTON which toggle between dark theme and light theme?
If So, then it's already implemented in my PR though 😉

**Comment by xplosionmind** [comment]
> If So, then it's already implemented in my PR though 😉

Yeah I meant this. I love you. I didn't read this issue comments well enough.

How about `userchrome.css` and `userstyle.css`? Are they going to be splitted in two, the dark and the light one, or who customizes them can't toggle between light and dark mode?

**Comment by kowalskidev** [comment]
> 
> How about `userchrome.css` and `userstyle.css`? Are they going to be splited in two, the dark and the light ones, or who customize them can't toggle between light and dark mode?

Yeah that's a very good question I didn't thought about it, I'll try to add USERCHROME AND USERSTYLE theme option in Preferred Light Theme and Preferred Dark Theme drop downs respectively that way you'll be able to toggle between light and dark mode. But before that, let's wait for Laurent's opinion

**Comment by xplosionmind** [comment]
> that way you'll be able to toggle between light and dark mode. But before that, let's wait for Laurent's opinion

That would be wonderful. Thanks a lot!

**Comment by Terrance** [comment]
Was the mobile side of this ever implemented?

I can see this issue is tagged for both desktop and mobile, but as far as I can tell the option doesn't exist on Android, and several Discourse threads ([1](https://discourse.joplinapp.org/t/easier-night-mode-switching-in-android/20874), [2](https://discourse.joplinapp.org/t/android-app-system-wide-dark-theme-intagration/10173), [3](https://discourse.joplinapp.org/t/auto-theme-change-depending-on-system-settings/5789)) have requested it but have been left unanswered and/or closed.

**Comment by almadorx** [comment]
I experienced that automatic theme switching working a little glitchy on my laptop.
So basically theme is switching, but the main note area remains black for example and I need to go to settings and change the theme back and forward from dark to light to make this area look light.

Did someone notice the same behavior? 

I'm on windows 10 21H2 and my Joplin is 2.9.17

**Comment by julianfairfax** [comment]
> Was the mobile side of this ever implemented?
> 
> I can see this issue is tagged for both desktop and mobile, but as far as I can tell the option doesn't exist on Android, and several Discourse threads ([1](https://discourse.joplinapp.org/t/easier-night-mode-switching-in-android/20874), [2](https://discourse.joplinapp.org/t/android-app-system-wide-dark-theme-intagration/10173), [3](https://discourse.joplinapp.org/t/auto-theme-change-depending-on-system-settings/5789)) have requested it but have been left unanswered and/or closed.

It doesn't seem like it. @laurent22
