### ISSUE TITLE
Mobile: Attaching Images / Files doesn't place them at cursor but bottom of Note

### ISSUE THREAD

**Issue by bedwardly-down** [laurent22/joplin#2669]
## Environment

Joplin version: 10.0.43 / 1.0.316
Platform: iOS Android
OS specifics: iOS 13.3.1, Android 9

## Steps to reproduce

1. Place cursor anywhere in note
2. Tap hamburger buttons on top right 
3. Tap Attach 
4. Tap any selection from menu

## Describe what you expected to happen
Attachments be placed at cursor but instead always placed at bottom.

**Comment by coderrsid** [comment]
I'll work on this issue.

**Comment by coderrsid** [comment]
Hey @bedwardly-down, so if i attach any image from any of the three method, the image will be inserted in a newline from before the cursor and the remaining text after cursor will be appended after the image in a newline. Is that what you expect?

**Comment by bedwardly-down** [comment]
That's what should happen but it always inserts the attachments on the bottom line.

**Comment by coderrsid** [comment]
That's fine. I've identified where and why the problem is,  i am working on this.

**Comment by prakhar28** [comment]
Is the issue still open?
