### ISSUE TITLE
different DropBox storage locations for GUI app and Terminal app

### ISSUE THREAD

**Issue by Tycholiz** [laurent22/joplin#2671]
Can't say for certain how this issue came to be, but when I open joplin from the terminal, it seems I am accessing a different database. I have attempted to go into the SQLite database and change all sync.7 rows of the Terminal app to match the ones listed in the GUI, but no luck.

How can I ensure that both Terminal version and GUI version are accessing the same database?

**Comment by tessus** [comment]
⚠🚨⛔ The issue tracker is not for questions. ⛔🚨⚠

As it happens, support requests that are created as issues are likely to be closed. We want to make sure you are able to find the help you seek.

## Questions and Help

Please read the [documentation](https://joplinapp.org/) and [FAQ](https://joplinapp.org/faq/) first.

### https://discourse.joplinapp.org/

If you have still questions related to Joplin, please open a topic in the [forum](https://discourse.joplinapp.org/).
You can use your GitHub credentials to login to the forum.

## Links

- Documentation: https://joplinapp.org
- FAQ: https://joplinapp.org/faq/
- Forum: https://discourse.joplinapp.org
- How to enable end-to-end encryption: https://joplinapp.org/e2ee/
- API documentation: https://joplinapp.org/api/
- How to enable debug mode: https://joplinapp.org/debugging/
