### ISSUE TITLE
Supressing checkboxes (issue #2646 cont'd)

### ISSUE THREAD

**Issue by sciurius** [laurent22/joplin#2676]
See issue #2646 for history.

1.0.189: Rendering was ok up to previous release (1.0.179, January 24) so it is a regression due to a recent change.

1.0.190: hiding the checkboxes seems to not work at all anymore.

1.0.191 fixed the 1.0.190 problem, so now we're at 1.0.189 behaviour again. Still a regression since 1.0.179.

**Comment by laurent22** [comment]
How about v192?

**Comment by sciurius** [comment]
Still the same.

**Comment by sciurius** [comment]
Can you reproduce it using the small sample I started issue #2646 with?
I do not have additional userchrome/userstyle css.

**Comment by laurent22** [comment]
As mentioned before you need to update your CSS to take into account the checkbox margin. In general the HTML structure of the app might change from one version to the next, so usercss needs to be updated from time to time.

**Comment by sciurius** [comment]
If the same document suddenly starts rendering differently on Android and desktop (without userstyle css) then I think it is an regression.
