### ISSUE TITLE
Mermaid item was so big on andriod 1.0.319

### ISSUE THREAD

**Issue by letian304** [laurent22/joplin#2677]
When  I tried 1.0.319 on  Android， The Mermaid item was so big 。
Joplin version: 3.0.319
Platform: android
![image](https://user-images.githubusercontent.com/50763102/76133832-248e1780-6055-11ea-8952-f6affb11b9d5.png)

**Comment by Rahulm2310** [comment]
@letian304 can you please describe what needs to be done here

**Comment by letian304** [comment]
> scribe what needs to be done here
When I use mermaid,The graph was very very big in android. and always out of the screen.
I want the make the graph smaller,  like rendered in windows.
![image](https://user-images.githubusercontent.com/50763102/76513737-b2249980-6491-11ea-9581-fba2d8578435.png)

![image](https://user-images.githubusercontent.com/50763102/76513457-4b9f7b80-6491-11ea-8755-3c1d11fec8a0.png)

**Comment by laurent22** [comment]
Please could any of you post the Mermaid code to replicate this issue?

**Comment by laurent22** [comment]
And does it still happen with the latest Android version?
