### ISSUE TITLE
Clear provisional flag as soon as note is modified

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2681]
Currently does it when saved, but would be best to do it as early as possible.

**Comment by jerrybuks** [comment]
I'm working on it

**Comment by jerrybuks** [comment]
> Currently does it when saved, but would be best to do it as early as possible.

could you please add a photo(or any guide to reproduce this issue), as I'm unable to reproduce it from end

**Comment by jerrybuks** [comment]
> > Currently does it when saved, but would be best to do it as early as possible.
> 
> could you please add a photo(or any guide to reproduce this issue), as I'm unable to reproduce it from end

@laurent22, please

**Comment by hetanthakkar1** [comment]
@jerrybuks are you currently working on it whats the status i also want to work

**Comment by jerrybuks** [comment]
No, I'm not

**Comment by anihm136** [comment]
@hetanthakkar1 if you're not working on this, I'd like to take this up.
