### ISSUE TITLE
export to JEX doesn't exit "Please wait..." screen (intermittent issue)

### ISSUE THREAD

**Issue by taw00** [laurent22/joplin#2682]
1.0.192 on Fedora 31 (my builds).

I exported to .jex. It did it usual black screen with the message that it was being saved. But there it remained. _It doesn't do this every time._ Issue #1970 looks similar.

Screenshot attached.
debug file attached (though I see nothing useful in it).
I ran it from the command line and I see this (but that looks like just noise, right?):
```
[47676:0307/204339.892196:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
```

![Screenshot from 2020-03-07 14-42-55](https://user-images.githubusercontent.com/6908872/76155111-99913980-60b5-11ea-9cbf-e6f11e3604e3.png)
[joplin-debug-1583631752964.log](https://github.com/laurent22/joplin/files/4302720/joplin-debug-1583631752964.log)

**Comment by anjulalk** [comment]
I'd like to take a look at this. The error is background noise indeed. I get it when opening the app menu. So I don't think its related to this. (It's something to do with GPU acceleration in Chromium?)

I'll give an update soon.

**Comment by laurent22** [comment]
> I'd like to take a look at this. The error is background noise indeed. I get it when opening the app menu. So I don't think its related to this. (It's something to do with GPU acceleration in Chromium?)

Indeed it doesn't need to be fixed.

**Comment by laurent22** [comment]
> I exported to .jex. It did it usual black screen with the message that it was being saved. But there it remained. _It doesn't do this every time._ Issue #1970 looks similar.

From the log you provided, it seems the operation was complete? It has the "Export result" message, which shows up once the export is complete.

**Comment by taw00** [comment]
I will continue to experiment. I don't know if it is relevant, but the `.jex` file was already in existence (I write over the same one most of the time. I should have checked the timestamp. I will do a bit more troubleshooting and see if I can determine that it is indeed saving. I really don't want to do a full restore to see if that file is valid though. Is there another way to see if it is a valid archive? Is it a zip file or something?

**Comment by tessus** [comment]
@taw00 

>  Is it a zip file or something?

Yep, it's a tar.

**Comment by bedwardly-down** [comment]
I don’t remember this being closed by me but it could have been a fluke or something I didn’t put together properly (I don’t remember), but i had a similar problem with importing here: https://github.com/laurent22/joplin/issues/2481

Any of that similar to what’s happening here, @taw00 ?

**Comment by taw00** [comment]
@bedwardly-down 
It may be related. I think the jex export hangs up or gets confused (in the UI?) if the syncing process is delayed? Unsure.

A digression . . .
@laurent22 I have to mention, I am on Satellite Internet out here in Rural 'Murica. Sometimes my dropbox sync is laggy and odd things happen in general because of this. I think anyway. So, if there is any process that waits on a sync success, there is a point of potential failure right there. Or even if the process depends on a timely response to whether a remote action was successful or a failure (latency). For example, GitHub HATES latency and is inefficient in dealing with its foibles. Anyway, I digress. Most things work. I even do video conferencing though it becomes quite clear which platforms are designed to be more robust (Bluejeans is great, Zoom is so-so). Again, I digress.

**Comment by taw00** [comment]
I'm closing this. I think it is associated to (or is the same bug) as  https://github.com/laurent22/joplin/issues/3114
I haven't seen this crop up in two weeks.
