### ISSUE TITLE
Search in note body using GotoAnything

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2683]
Currently GotoAnything allows searching within note titles, notebook titles and tags.

We want to add this feature: When pressing the `/` key, followed by a query, GotoAnything should search within the note body.

All code should be in GotoAnything.jsx

Forum thread: https://discourse.joplinapp.org/t/what-shortcut-for-gotoanything-to-search-in-note-body/2148

**Comment by chamathabeysinghe** [comment]
Hello! I am a new contributor. I will work on this issue.
