### ISSUE TITLE
Remove usage of deprecated UIWebView

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2684]
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from December 2020 . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

More info on what needs to be checked after switching to WebKit: https://github.com/react-native-community/react-native-webview/issues/312

In particular these two bugs need to be checked:

Bug 1: https://github.com/react-native-community/react-native-webview/issues/312#issuecomment-501988732

Bug 2: https://github.com/react-native-community/react-native-webview/issues/312#issuecomment-503754654

**Comment by ani4aniket** [comment]
@laurent22 I want to work on this. Is it ok to use wkwebview instead?

**Comment by laurent22** [comment]
Yes the alternative would be wkwebview. Please make sure you read the linked thread (in particular my posts since they are relevant to Joplin) and check that everything works as expected. It's possible that they fixed the bugs I mentioned there since then.

**Comment by laurent22** [comment]
@ani4aniket, I've added the two bugs that need to be checked.

**Comment by hetanthakkar1** [comment]
@laurent22 can i work on this issue? any updates from @ani4aniket  are you working?

**Comment by ani4aniket** [comment]
@hetanthakkar1 feel free to take this up.

**Comment by demslob** [comment]
Hello guys, I am having issues with submitting my app to app store because of deprecated UIWebView. Any updates on changing it to wkwebview instead?

**Comment by laurent22** [comment]
@demslob, what app? And we don't have a solution for that webview issue as of yet.

**Comment by demslob** [comment]
@laurent22 thank you. Will probably remove webviews and change it to some native representation of my content

**Comment by tanhao8** [comment]
大家好，由于UIWebView已过时，我无法将自己的应用提交到应用商店。请问有解决方案吗？

**Comment by tanhao8** [comment]
Hello, I can't submit my app to the store because uiwebview is out of date. Is there a solution?
