### ISSUE TITLE
Quick actions are not working on Android

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#2685]
I'm using the latest available version 1.0.320 on Honor 9 OS version 9.

If Joplin is not running in background then using quick action (regardless whether it's new note or new todo) brings up notes list. If the app was running then instead I get a blank screen with only back button.
![Screenshot_20200308_094047_net cozic joplin](https://user-images.githubusercontent.com/995612/76160313-0261cb80-6121-11ea-997c-a038c062f81e.jpg)

There's nothing obviously wrong in the log, there are some errors but they seem unrelated:
```
TypeError: Network request failed
```

**Comment by amitsin6h** [comment]
Let me check what is causing the issue

**Comment by roman-r-m** [comment]
Having looked into this for a few days I have to admit I've got no idea how it was supposed to work in the first place. (I'm no expert on React or Android though)

The reason it fails (for me at least) is that noteId is set to null at https://github.com/laurent22/joplin/blob/cdb8a1e98c1d7e934b8cfb85b17ac0e0494eab58/ReactNativeClient/setUpQuickActions.ts#L35

Then when it gets to https://github.com/laurent22/joplin/blob/cdb8a1e98c1d7e934b8cfb85b17ac0e0494eab58/ReactNativeClient/lib/components/shared/note-screen-shared.js#L197 it can't load the note and fails when trying to get parentId here
```
const folder = Folder.byId(comp.props.folders, note.parent_id);
```

**Comment by roman-r-m** [comment]
Raised https://github.com/laurent22/joplin/pull/2796

**Comment by roman-r-m** [comment]
@devonzuegel could you take a look please as the author of this feature

**Comment by laurent22** [comment]
Probably that's the recent addition of the provisional note concept that broke this. Now notes cannot have a null ID, instead they need to be created with `await Note.save({ title: "my note" }, {isProvisional:true})`

**Comment by roman-r-m** [comment]
Nope, still not fixed.
