### ISSUE TITLE
Scrolling error and persistent scrollbar in app

### ISSUE THREAD

**Issue by xplosionmind** [laurent22/joplin#2687]
Joplin version: [v1.0.193](https://github.com/laurent22/joplin/releases/tag/v1.0.193)
Platform: MacOS Catalina 10.15.3

#### Bug description

When I’m scrolling down in a note, even if it’s short and it completely fits in the page, I have a white blank margin coming up from below. As you can see in [this screen recording](https://youtu.be/KSkzE-eEO1k), even when not scrolling, there’s also a persistent scrollbar on the right. I'm experiencing this since [v1.0.189](https://github.com/laurent22/joplin/releases/tag/v1.0.189)

<br>

Debugging console warnings seem to be unrelated to this graphical issue, but if requested I can add them below.

**Comment by xplosionmind** [comment]
I'm gonna add two images below to add some context to the [screen recording](https://youtu.be/KSkzE-eEO1k)

<img width="1440" alt="graphical bug in Joplin on Mac" src="https://user-images.githubusercontent.com/42862428/76227461-a03bc000-621f-11ea-8edf-b79767d9f0d2.png">

<img width="1440" alt="graphical bug in Joplin on Mac" src="https://user-images.githubusercontent.com/42862428/76227575-cfeac800-621f-11ea-92e0-d076d198cea1.png">

**Comment by Medi223** [comment]
Joplin version: v1.0.193
Platform: Windows 10 1909 18363.693
Hi, I also have a scrolling related bug, but haven't been able to reproduce it. I was switching between Word and Joplin on dual-monitors, but Joplin suddenly started flashing black and white whenever I scrolled before completely going white. It also wouldn't close via the hiddon icon area, and took Task Manager several tries before it completely closed. https://streamable.com/x8kvc

**Comment by xplosionmind** [comment]
@Medi223 it seems to me like an unrelated issue, the thing about Joplin flashing and going white (especially immediately after opening the app) happens occasionally to me, but it goes away alone after a while.

**Comment by xplosionmind** [comment]
Btw, I further investigated the issue by opening the app in debug mode, it doesn't seem like an HTML issue: the resolution of the screen in the `<div>` tag is right.

**Comment by laurent22** [comment]
I cannot replicate this. Does it happen every time for you on only on certain notes?

**Comment by xplosionmind** [comment]
it happens on any page! It seems like an app display issue. Tell me what do I have to do to provide more information, it's driving me crazy!

**Comment by xplosionmind** [comment]
To tell the truth I don't know why, but I changed both my `userstyle.css` and `userchrome.css` files and it went away.

Thanks a lot for your help, sorry if I posted here but I had no idea those file could influence this issue
