### ISSUE TITLE
Add option to "Retry all" when multiple items failed decrypting

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2688]
When an item cannot be decrypted, it appears on the synchronisation page, and there's a "Retry" link next to it to tell the decryption worker to process the item again.

If there's more than 1 item, there should be a "Retry all" button to send all the items for decryption in one go. That button should be at the top of the list.

**Comment by fhfuih** [comment]
Hi! I am a newcomer and I would like to try solving this issue. However, I don't know how to trigger a decryption failure. I just tried disconnected from the internet but it just says `Completed: <time here>` with no `fetch items x/x`

**Comment by fhfuih** [comment]
So I just probably done writing the codes without seeing how it's gonna be like... And I would like to know if there is only one "retry all" button for all the sections, or many button for each section? (I assume the former choice is better.) And should we care about adding new fields to the localization template?

**Comment by tessus** [comment]
I'm not very familiar with the decryption worker code that Laurent will have to answer your questions.

**Comment by Hardik500** [comment]
I would like to work on this issue if it's still open.
