### ISSUE TITLE
Make menu bar black with dark themes

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2689]
When using a dark theme, the menu bar stays white:

![image](https://user-images.githubusercontent.com/1285584/76162173-e2d39e80-6132-11ea-9092-5c90d5cb7ebd.png)

Instead the app should check the current theme and if it's a dark one, the menu bar should be made black (assuming Electron supports this).

**Comment by RedDocMD** [comment]
@laurent22 I would like to work on this issue. Please assign it to me.

**Comment by RedDocMD** [comment]
By the way, Electron does not directly support a dark theme. Rather, we must make the menu bar from scratch and change its colour

**Comment by Rahulm2310** [comment]
@laurent22 I don’t know if we can change the menu bar color without changing the system UI theme, but we can create a frameless window and build our own menu in our app’s HTML.

**Comment by laurent22** [comment]
If it means building our own menu, then we'll leave it as it is.

**Comment by Rahulm2310** [comment]
Okay

**Comment by pranavmodx** [comment]
@laurent22, Please correct me if I am wrong, but I think we can easily create a custom menu bar with the help of this [package](https://www.npmjs.com/package/custom-electron-titlebar).
There is also an example tutorial on it [here](https://ourcodeworld.com/articles/read/938/how-to-create-a-custom-titlebar-inspired-on-visual-studio-code-title-bar-in-electron-framework).

Keeping all other styling intact, we could just the change the color, according to the theme selected by the user, by passing it as an attribute (backgroundColor) to the function (Titlebar) provided in the package.

If the solution sounds valid to you, I could take this issue up.

**Comment by kowalskidev** [comment]
I figured it out that the menu bar color is based on our system theme. I have dark theme in my system so in my case menu bar is dark and another thing is Electron doesn't support changes against system theme unless we create our own menu bar which we don't want to! and yes we can detect system theme using Electron which I have implemented for this issue #2665
.
> 
> 
> If it means building our own menu, then we'll leave it as it is.

**Comment by blairdrummond** [comment]
In the interim, is there a way to toggle the menu bar?

**Comment by Rishgod** [comment]
> In the interim, is there a way to toggle the menu bar?

No you have to make a custom title bar, once you make a custom title bar you can pass the theme object and it can be changed according to the theme, till then I don't think so you can

**Comment by itpropaul** [comment]
For folks that already have a dark system theme as I and still had the white title bar. Try Windows>"Themes and Related Settings">Color>Choose a color like Dark Gray in custom or wherever (it won't let you choose black or even past a certain degree of darkness)>Show accent colors on the following surfaces>Title bars and window borders

**Comment by itpropaul** [comment]
https://www.npmjs.com/package/custom-electron-titlebar This also may be worth looking into.

**Comment by rahil1304** [comment]
Hey, is somebody working on this issue or can I take it up?

**Comment by omega3** [comment]
I also have white menu bar with default dark theme in the latest 1.2.6 appimage on Linux. Please fix it.
https://i.imgur.com/6poyD9b.png

**Comment by elsiehupp** [comment]
> I also have white menu bar with default dark theme in the latest 1.2.6 appimage on Linux. Please fix it.
> https://i.imgur.com/6poyD9b.png

I have the same issue on Ubuntu 20.04.1. I had a different thought for addressing it, though: color themes aside, could there be the option to have the title bar and menu bar auto-hide when the window is maximized? I mean, this is the default behavior on macOS, and it would be nice if it were an option on Linux and Windows, as well. (I can create a separate linked issue, if that would help.)

**Comment by elsiehupp** [comment]
I've been browsing the forums for related issues, and someone made a request to combine the title bar and tool bar like they are in Firefox, macOS Big Sur, and Gnome:

https://discourse.joplinapp.org/t/feature-request-add-support-for-integrated-menu-bar-beneficial-to-all/10264/4

**Comment by jb33k** [comment]
I'm running on Windows 10 and I also have light title bar. I also would love it for to be dark with the dark theme.

**Comment by lbrink** [comment]
> 
> 
> I'm running on Windows 10 and I also have light title bar. I also would love it for to be dark with the dark theme.

I could fix that by applying instructions posted above by [itpropaul](https://github.com/laurent22/joplin/issues/2689#issuecomment-663024381).
You've tried them?

**Comment by thebodzio** [comment]
Will it work for inactive window as well?

I do use settings suggested by [itpropaul](https://github.com/laurent22/joplin/issues/2689#issuecomment-663024381). It's all fine as long as the window is active, but whenever it becomes inactive… the blinding whiteness is still there :}.

It's a minor issue, but an issue none the less :}

**Comment by goferito** [comment]
I was trying to get that bar dark. If someone is interested, on ubuntu I managed to change it by changing the gtk preferences, editing the fie  `~/.config/gtk-3.0/settings.ini`, and adding the next content:

```
[Settings]
gtk-application-prefer-dark-theme=1
```

**Comment by number-25** [comment]
> I was trying to get that bar dark. If someone is interested, on ubuntu I managed to change it by changing the gtk preferences, editing the fie `~/.config/gtk-3.0/settings.ini`, and adding the next content:
> 
> ```
> [Settings]
> gtk-application-prefer-dark-theme=1
> ```

I can confirm this works on Arch too, cheers

**Comment by almadorx** [comment]
I could confirm that issue is still there, at least for Windows 10 and Joplin 2.8.8

> For folks that already have a dark system theme as I and still had the white title bar. Try Windows>"Themes and Related Settings">Color>Choose a color like Dark Gray in custom or wherever (it won't let you choose black or even past a certain degree of darkness)>Show accent colors on the following surfaces>Title bars and window borders

I've tried this solution and it's working, but if you have changing the theme from dark to light automatically you'll have to change this color every time you are switching the theme. Another software is working properly, Thunderbird and Chrome for example, but not Joplin.
![image](https://user-images.githubusercontent.com/90159151/201753978-0a3e3b31-66b5-46be-a1f9-2df3f2eda443.png)

**Comment by richardroberts** [comment]
Hello, in case this is affecting anyone else using the Flatpak version of Joplin on Linux, I got the menus to successfully follow the system light/dark theme by using Flatseal to enable Wayland and disable X11 for Joplin.  I haven't yet seen any problems with Joplin using Wayland natively so far.  I'm using KDE 6.4 with Wayland... any other setup I'm not sure if this solution will work for you.

**Comment by faretek1** [comment]
> Hello, in case this is affecting anyone else using the Flatpak version of Joplin on Linux, I got the menus to successfully follow the system light/dark theme by using Flatseal to enable Wayland and disable X11 for Joplin. I haven't yet seen any problems with Joplin using Wayland natively so far. I'm using KDE 6.4 with Wayland... any other setup I'm not sure if this solution will work for you.

This worked for me; i'm using kde on arch
