### ISSUE TITLE
Zooming out deforms table borders in v1.0.193

### ISSUE THREAD

**Issue by memophen** [laurent22/joplin#2690]
## Environment
Joplin version: 1.0.193
Platform: macOS
OS specifics: 10.14.6 Mojave

### Content of the note
```
Table rendering in v1.0.193
===========================
| Table                       ||
| First header | Second header |
| ------------ | ------------- |
| One          | Alpha         |
| Two          | Bravo         |

| Three        | Charlie       |
| Four         | Delta         |

<style>
  table {
    border-collapse: collapse;
    border: 2px solid orange;
  }
   tbody {
    border-bottom: 2px solid lightgreen;
  }
   td {
    border: 1px solid black;
  }
   th {
    border: 1px solid white;
    border-top: 1px solid red;
    border-bottom: 1px solid red;
  }
</style>
```
### Expected
Thicker borders always win from thinner ones. In this case: all 2px border should prevail.

### Rendering at normal size (Cmd-Zero) or zoomed in (Cmd-Plus)
![image](https://user-images.githubusercontent.com/4470470/76162593-7317e080-613f-11ea-8309-fb1d503419b0.png)
As expected: orange table border and green tbody borders are visible.

### Rendering when zoomed out (Cmd-Minus), one step or more
![image](https://user-images.githubusercontent.com/4470470/76162617-99d61700-613f-11ea-9f1f-9923fb647867.png)
Not conform expectation: the red, white and black 1px borders cover the 2px borders.

**Comment by laurent22** [comment]
The following HTML also doesn't do what you expect in Chrome:

```html
<style>
  table {
    border-collapse: collapse;
    border: 2px solid orange;
  }
   tbody {
    border-bottom: 2px solid lightgreen;
  }
   td {
    border: 1px solid black;
  }
   th {
    border: 1px solid white;
    border-top: 1px solid red;
    border-bottom: 1px solid red;
  }
</style>

<table>
<thead>
<tr>
<th colspan="2">Table</th>
</tr>
<tr>
<th>First header</th>
<th>Second header</th>
</tr>
</thead>
<tbody>
<tr>
<td>One</td>
<td>Alpha</td>
</tr>
<tr>
<td>Two</td>
<td>Bravo</td>
</tr>
</tbody>
<tbody>
<tr>
<td>Three</td>
<td>Charlie</td>
</tr>
<tr>
<td>Four</td>
<td>Delta</td>
</tr>
</tbody>
</table>
```

So that should be reported to the Chrome project.

**Comment by memophen** [comment]
It's even worse: same misbehavior in Firefox and Safari. Surprisingly only IE 11 and the pre-chromium-based Edge version stay on track at all zoom levels.

Instead of fighting a loosed battle, it seems better to avoid overlapping of borderlines. That will make the CSS more complicated, but I think it's doable. I will publish about it when I've found time to sort this out.

Anyway, it's a far from urgent matter. How often do we want to zoom out after all?
