### ISSUE TITLE
Font size has drastically decreased in v1.0.193

### ISSUE THREAD

**Issue by luckydays** [laurent22/joplin#2691]
Please see the screenshot below:

![image](https://user-images.githubusercontent.com/10942891/76163334-701fee80-6145-11ea-8c11-3e4234ce422e.png)

The same relates to the left sidebar with the notebooks and tags.
It's as it was "zoomed-out"

**Comment by laurent22** [comment]
Can you try to reset the zoom, in View menu?

**Comment by luckydays** [comment]
Thanks for the tip @laurent22 (never used this feature before :slightly_smiling_face: ).

OK, I've zoomed in a couple of times. The font size looks better indeed, however, the vertical space between the lines seems to be bigger than it was in the previous version of the app. But maybe it's a part of this latest update?

And trying "Actual Size" in the View menu - got back that decreased font size.

**Comment by laurent22** [comment]
Hmm, not sure, we changed the toolbar button font size, but it was a while ago. Your screenshot seems about right. Maybe the default font size should be increased but that's something to be discussed on the forum.
