### ISSUE TITLE
HTML not working in v1.0.193

### ISSUE THREAD

**Issue by Phieldar** [laurent22/joplin#2692]
In previous version, HTML tag such as imbedded video (from Youtube) were working, now it isn't. I tried in Windows.

<iframe width="560" height="315" src="xyz" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Environment

Joplin version: v1.0.193
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Add some HTML from Youtube

**Comment by RedDocMD** [comment]
I believe you problem is same as the following [issue](https://github.com/laurent22/joplin/issues/2643#issuecomment-595168606)

**Comment by laurent22** [comment]
iframes, script and object tags have been disabled for security reasons. If the goal is to insert a YouTube video, I think the solution would be to create a markdown-it plugin for it.

**Comment by laurent22** [comment]
Feature request: https://github.com/laurent22/joplin/issues/2706
