### ISSUE TITLE
Fix gap on top of mobile app

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2694]
It doesn't seem to always happen. Maybe just with dark theme?

The screenshot below is from Android.

![image](https://user-images.githubusercontent.com/1285584/76165042-a6f90300-614b-11ea-90f6-558e89cbb900.png)

**Comment by DeadManIV** [comment]
Yeah that's the UI issue I mentioned in my thread here: https://discourse.joplinapp.org/t/android-app-constant-crashes-after-sync-setup/6633/6

For me, the bar is always there. Light or dark theme. It's just white in the light theme, then half white (as in your screenshot) in the dark theme. But yeah the bar is always there. It wasn't in version 316, but every version after 316 had this issue. So something that changed there caused this. I've installed all versions after 316 trying to see if it fixed that issue in my thread.

**Comment by laurent22** [comment]
@DeadManIV, it doesn't happen on my device. What is the screen resolution on your device?

**Comment by laurent22** [comment]
Does your device has a notch by any chance? There's some new logic to add a gap if the device has a notch, but obviously it shouldn't do that. Or perhaps the logic to detect notch is faulty.

**Comment by DeadManIV** [comment]
I believe my resolution is 1080p. But yeah it does have a notch. That might indeed be the cause of the issue.
I have a OnePlus 6.

**Comment by ev-w** [comment]
![207834E6-5BD2-4ED1-831F-FA4EEBD41BC1](https://user-images.githubusercontent.com/9102534/76168770-b161cf80-6140-11ea-98ba-a4ae027e260c.png)

Same issue here on iPhone 11 Pro Max

**Comment by JefferyT51** [comment]
Ditto here on the iPhone X.  iOS 13.3.1.  Happens in "Dark" and "OLED" Dark themes.

![Joplin-iOS-DarkMode-Bugged-1](https://user-images.githubusercontent.com/37882530/76168961-bbcc9b00-6139-11ea-9cf9-54cb0b7684dc.JPG)
![Joplin-iOS-DarkMode-Bugged-3](https://user-images.githubusercontent.com/37882530/76168962-bc653180-6139-11ea-9da5-10463bca425a.jpg)
![Joplin-iOS-DarkMode-Bugged-2](https://user-images.githubusercontent.com/37882530/76168963-bcfdc800-6139-11ea-9ccb-ba10b8178fc9.jpg)

**Comment by DeadManIV** [comment]
@JefferyT51 @ev-w Do you guys have this issue within notes as well? Using the new OLED dark mode theme? If that's available on iOS. Version 1.0.320
https://github.com/laurent22/joplin/issues/2695

**Comment by ev-w** [comment]
@DeadManIV yes, the images @JefferyT51 posted above mirror my experience; the white part moves to the left side in a note view

**Comment by DeadManIV** [comment]
> @DeadManIV yes, the images @JefferyT51 posted above mirror my experience; the white part moves to the left side in a note view

Ah no,  I meant the issue I linked. Sorry for the confusion. This issue: https://github.com/laurent22/joplin/issues/2695

**Comment by uavana** [comment]
also got a gap on Android Version with notch

**Comment by foxmask** [comment]
same as @uavana

**Comment by axq** [comment]
No notch no gap for me on Android.

**Comment by ethan42411** [comment]
Same issue on iPhone XR.
![A6646B35-FCB0-4086-98C7-8AE19BBC0ECE](https://user-images.githubusercontent.com/5001259/76263483-f51c1c80-6299-11ea-9dd5-6199e8cfe583.png)

**Comment by coderrsid** [comment]
Hey @laurent22, why you closed this issue? I was thinking of working on it.

**Comment by laurent22** [comment]
@coderrsid, this is my fix https://github.com/laurent22/joplin/commit/b367955e566f10ab6c29c63419845520de022084, but I'm not sure it's correct at all, so if you can find a better solution and especially test on a device with a notch, it would still be worth it

**Comment by serenitatis** [comment]
I have same issue on my Xiaomi Mi 9.
