### ISSUE TITLE
Cannot exit from New Note / New to-do when nothing is typed

### ISSUE THREAD

**Issue by MuizU** [laurent22/joplin#2696]
When the new note or new to-do is clicked and the  there is no way to exit that view.  

## Environment

Joplin version: 1.0.179-1
Platform: Linux
OS specifics: EndeavourOS

## Steps to reproduce

1. Open Joplin.
2. Click new note / new to-do.
3. click escape.

## Expected Behavior
   There should be a close button to exit the new note section or it should close on escape

**Comment by laurent22** [comment]
The note is temporary. If you don't want to create it, just select something else and it will go away.
