### ISSUE TITLE
note added from mobile shows up as encrypted in linux desktop

### ISSUE THREAD

**Issue by pcause** [laurent22/joplin#2698]
I have version 1.0.320 on my mobile (android) and added a note.  Just updated linux desktop to 1.0.193 and after opening and sync the new note from mobile shows up as encrypted on the linux desktop.  Never happened before on previous releases.  I then created a note from linux and it synced to mobile.  created a mobile note again and synced to linux.

I then deleted the test notes I created and synced on linux then mobile and the notes were still there on mobile.  Deleted on the mobile and synced and gone from both.

Something strange on sync.  Using OneDrive as cloud storage sync.

**Comment by alexdevero** [comment]
I have the same issue on desktop Win and iOS app.

When I create note on desktop and sync Joplin, the app appears in iOS app as encrypted. I already have +100 notes on mobile that are encrypted.

Joplin desktop: 1.0.193 (Win)
Joplin iOS: 10.0.45

**Comment by axq** [comment]
I had a similar issue after updating on Android to 1.0.320.  Created a new note, that wouldn't decrypt on Windows desktop, until I updated to 1.0.193 for Windows.  My guess is that it's due to the introduction of CCM encryption in the latest releases.

Are you on the latest releases for each platform?  Has CCM been added to iOS yet?

**Comment by alexdevero** [comment]
@axq I don't think so. I've been encountering issues with encryption for the last 5-6 days. Since I always download the latest version right when it is released, the bug could to be introduced in one of the last ~3 version.

**Comment by laurent22** [comment]
If you have the latest version of mobile and desktop, you can go in the Synchronsiation Status screen, and click "Retry" for each item that could not be decrypted.

**Comment by alexdevero** [comment]
Hope this will be helpful, screen from iOS app:
![IMG_4623](https://user-images.githubusercontent.com/4237724/76220499-e3923080-6217-11ea-8cd7-bb144cf67aac.PNG)

Note: I didn't change my master encryption key for the last year. For some reason, the app started showing this message few days ago.

**Comment by laurent22** [comment]
A few things:
- The latest iOS version with CCM mode support has not been released yet (waiting for Apple)
- If you're still having issues decrypting items, please check the sync status screen to see if you can retry decryption
- Post your log if it still doesn't work

**Comment by laurent22** [comment]
My bad, the iOS is actually released now. So if it doesn't please post your log.

**Comment by alexdevero** [comment]
I tried to export debug log, but it does nothing - button is grayed out but nothing happens. How long does it take to export the log?

**Comment by laurent22** [comment]
This button doesn't work in iOS (and should be removed). If you could take a screenshot of the relevant lines (errors related to encryption) in the log that could help.

**Comment by alexdevero** [comment]
Here is the screenshot:
![IMG_4626](https://user-images.githubusercontent.com/4237724/76225885-679ae700-621d-11ea-85da-e9c22ef94d27.PNG)

**Comment by laurent22** [comment]
Those are network errors, not encryption errors. Did you try actually setting the master key password?

**Comment by alexdevero** [comment]
Yes, twice. I set the password in 2018 and didn't change it since then. I've been using the same pass for almost two years and it worked, until few days ago. I also didn't reinstall the app, desktop or mobile.

**Comment by laurent22** [comment]
If it says it's decrypting on startup, but it's not actually doing anything, there should be some info in the log, not necessarily an error. Could you look through it and see if there's anything about encryption?

**Comment by alexdevero** [comment]
There is only message about `DecriptionWorker` being started and then completing decryption.

**Comment by alexdevero** [comment]
I think the problem may not be specifically in the encryption/decryption process, or missing master keys. I noticed that even though there were +100 encrypted notes in the mobile app (iOS), there were also encrypted notes that matched the notes in desktop app (Windows). Put simply, it looks like those encrypted notes were duplicates of the notes that were encrypted.

Or, another option, there was one encrypted note duplicated many times. I created only few notes in the past days. Yet, there were more than 100 encrypted notes. That doesn't make sense. Based on this, I think there is some issue in the sync process.

**Comment by nardyn** [comment]
Had the same problem from MacOsX to Linux client, so it's not a mobile problem. Just wrote 3 notes on 1.0.193 on MacOsX and read it on older version on Manjaro, still at 1.0.173. 
Than i've upgraded the linux version to 1.0.193 but nothing, still encrypted. In my case i've just resolved deleting that 3 notes and wroting it again from MacOsX and all went to normal, but of course that's something wrong there

**Comment by Flnch** [comment]
I had the same issue: Mobile (Android) at 1.0.320 and Linux desktop at 1.0.179. New and edited notes from the mobile device were shown as "encrypted" on desktop. After updating the desktop to 1.0.193, they were still shown as "encrypted".

My solution: After upgrading the desktop client to the most recent version, I made duplicates of the affected notes on the mobile device. After syncing, the duplicates work fine on the desktop client. Originals then can be removed.

**Comment by johodh** [comment]
I have the same issue on Linux desktop 1.0.179 and Android 1.0.322. Syncing over Nextcloud. All notes created on mobile appears "encrypted" and is unreadable on desktop (the only right-click option is delete). Notes created on desktop shows as expected on mobile. 
 
- Followed the encryption tutorial
- Sync status -> retry: results in failed items just re-appearing in list 
- @Flnch:s workaround does not work for me. 

Posting mobile log from seconds after deleting a note and creating a new note and syncing (22:39:30). Appears clean to me. 

![2020-03-14-224117_800x1316_scrot](https://user-images.githubusercontent.com/54511377/76690881-0c199080-6645-11ea-91ab-585c0f6f1fb8.png)

Let me know if i can help in some way, i'd be happy to see this function as expected.

**Comment by laurent22** [comment]
I cannot replicate this and I suspect it was due to the encryption upgrade which normally should be fixed now.
