### ISSUE TITLE
Where is the "Global Zoom Percentage" in settings?

### ISSUE THREAD

**Issue by JACK-THINK** [laurent22/joplin#2699]
## Environment

Joplin version: 1.0.193
Platform: Windows
OS specifics: Windows 10 LSTC 2018 17763.1075

## Describe what you expected to happen

Where is the "Global Zoom Percentage" in settings?

![bandicam 2020-03-09 10-26-46-163](https://user-images.githubusercontent.com/21015855/76177922-8cc53080-61f0-11ea-96ba-451b930fe433.jpg)

Plus, I think it's better to separate the settings from the database `database.sqlite` and make them into a individual file. In this way, people can modify settings without using database manager.

Thanks a lot.

**Comment by tessus** [comment]
⚠🚨⛔ The issue tracker is not for questions. ⛔🚨⚠

As it happens, support requests that are created as issues are likely to be closed. We want to make sure you are able to find the help you seek.

## Questions and Help

Please read the [documentation](https://joplinapp.org/) and [FAQ](https://joplinapp.org/faq/) first.

### https://discourse.joplinapp.org/

If you have still questions related to Joplin, please open a topic in the [forum](https://discourse.joplinapp.org/).
You can use your GitHub credentials to login to the forum.

## Links

- Documentation: https://joplinapp.org
- FAQ: https://joplinapp.org/faq/
- Forum: https://discourse.joplinapp.org
- How to enable end-to-end encryption: https://joplinapp.org/e2ee/
- API documentation: https://joplinapp.org/api/
- How to enable debug mode: https://joplinapp.org/debugging/

**Comment by JACK-THINK** [comment]
@tessus 

I'm so sure this is a bug, not support request.

The "Global Zoom Percentage" in settings just disappeared in version 1.0.193.

The "Global Zoom Percentage" in settings exists in version 1.0.179.

**Comment by tessus** [comment]
It's not a bug. It's been removed.
