### ISSUE TITLE
Delete not working in terminal tool [bug]

### ISSUE THREAD

**Issue by pablojmarti** [laurent22/joplin#27]
In the documentation you have that the delete key would remove a highlighted item. However the only way I can remove a notebook / note / todo currently is by using the `rmnote` or `rmbook` functionality.

**Comment by laurent22** [comment]
On which operating system is it?

**Comment by pablojmarti** [comment]
OSX 10.12.6

**Comment by laurent22** [comment]
Does it work when pressing Fn+Backspace?

**Comment by pablojmarti** [comment]
YEP! Was that outlined in the readme? Maybe i missed it. Thanks!

**Comment by laurent22** [comment]
No it's just that on the macOS keyboard, the "delete" key is actually Fn+Backspace. However, I will add support for just Backspace too, as this is more intuitive in macOS.

**Comment by laurent22** [comment]
Fixed in ede1ed8b227f2295bd86138664c7853db47342d9
