### ISSUE TITLE
Bug on Joplin App: Data typed is Cleared when airplane mode is re-activated. 

### ISSUE THREAD

**Issue by gutzygwin** [laurent22/joplin#270]
#### Expected behavior
Joplin note is a note taking and a to-do list andriod application with synchronizing capabilities. Upon joting down or typing down information or data on the app's note display,  it is expected for the app to run perfectly and fine and keep the data typed intact. 

#### Actual behavior
Upon joting down or typing down information or data on the joplin app, when the airplane mode is de-activated on the mobile phone, data is lost (cleared away)  which leaves the user work gone and important information is lost. 

#### How to reproduce
* Download the joplin application from playstore. 
* open application and type down data or information. (do not save your data yet)  keep on typing. 
* Activate airplane mode, then De-activate airplane mode to test-run. 
* Data typed is cleared away. 

--------------------------------------------------------

* Browser: Google Playstore/Joplin
* Operating system: Android 7.0 . Infinix Note 4.

#### Recording Of The Bug

https://youtu.be/hNpuNyIcKbI
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@gutzygwin/bug-on-joplin-app-data-typed-is-cleared-when-airplane-mode-is-re-activated">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by laurent22** [comment]
There's something weird about this video - there's no fade-in/fade-out animations in the app, but somehow the video shows one at 0:48. I'm removing the bug tag until this clarified.

**Comment by laurent22** [comment]
What's this utopian.io website anyway? I can't find any FAQ or who's behind it. I think it might encourage users to submit issues (possibly even fake ones) to earn credits, so unless there's some explanation I'm considering automatically closing them so as not to waste anyone's time.

**Comment by gutzygwin** [comment]
Utopian-io is a platform for promoting open source contributions done on
open source application which rewards users on the basis of steem
decentralized platform.
I'm sorry if the bug reported isn't technical. Apologies from my end, you
sounded annoyed with the context of your message.  I'm Godwin by the way,
nice meeting you... Will like to work with you, how can I be of service?
I can also do a promotion add on facebook on joplin app for the makers to
reach a minimum of 5000 people, are you interested?
