### ISSUE TITLE
Prevent toolbar buttons from wrapping

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2700]
Toolbar buttons wrap but they shouldn't:

![image](https://user-images.githubusercontent.com/1285584/76215734-43341000-6207-11ea-930b-864505268ca5.png)

We'd need to make sure they don't wrap, and that the media queries still work so it shows only the buttons below a certain width.

**Comment by anjulalk** [comment]
I'd like to work on this. Hiding or showing button labels is decided by the following media query in `Header.jsx` file:
```
window.matchMedia(`(max-width: ${550 * this.props.zoomFactor}px)`)
```

If width is less than `550 * this.props.zoomFactor` labels are not displayed. So increasing this value should do the trick, right?

**Comment by laurent22** [comment]
We only need to prevent the label from wrapping. But at the same time we need to check, after having disabled wrapping, that the existing media queries still work, maybe they still do.

**Comment by anjulalk** [comment]
I've prevented the labels from wrapping and made the break point `800*zoomFactor` which works fine in default zoom level, but with other different zoom levels it doesn't work well (see below recordings) It seems like hard-coding this value is not a good choice.
![Peek 2020-03-10 00-30](https://user-images.githubusercontent.com/26695184/76247971-6e018100-6266-11ea-8c5e-16f84450481e.gif)

Any suggestions?

**Comment by laurent22** [comment]
You could maybe use `setting.windowContentZoomFactor` to set the min width dynamically?
