### ISSUE TITLE
Remove "Export debug report" button in iOS

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2701]
This button is enabled in the Config screen, however it does nothing in iOS, so it should be removed.

**Comment by jerrybuks** [comment]
I would love to work on this

**Comment by Rahulm2310** [comment]
@jerrybuks I am already done with this brother.I request you to choose some other issue.

**Comment by jerrybuks** [comment]
> @jerrybuks I am already done with this brother.I request you to choose some other issue.

okay
