### ISSUE TITLE
Create a Markdown-it plugin to support embedded videos

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2706]
Videos would be embedded like so:

    [My YouTube video](https://www.youtube.com/watch?v=StTqXEQ2l-Y)

So it is valid Markdown that works as a simple link by default.

However, when the plugin is enabled, it would parse the Markdown links in the page and, when it is a video, display a video player. For now, we only need to support YouTube, but the code should be generic enough to add more video platforms later on.

**Comment by jerrybuks** [comment]
@laurent22 I want to work on this, but it seems to be a plugin that already does this, [here](npmjs.com/package/markdown-it-video) is it okay to just integrate it into the codebase?

**Comment by laurent22** [comment]
I saw it but it's not good because it unecessarily introduces non standard markup. Perhaps it can be used as a starting point to generate the html markup.

**Comment by jerrybuks** [comment]
okay, so you basically want the same functionality replicated, but should generate standard markup(semantic HTML)?

**Comment by laurent22** [comment]
No I mean the input Markdown should be standard. The output HTML I don't mind so much as long as it's reasonably clean.

Their Markdown looks like this:

    @[youtube](dQw4w9WgXcQ)

But that's not good as it's not standard and, if the plugin is not enabled, it won't work at all. So our Markdown should look like this:

    [youtube](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

which is standard. It's actually even easier to implement since markdown-it already parses this by default. You'll need to hook into link_open I think.

**Comment by jerrybuks** [comment]
> No I mean the input Markdown should be standard. The output HTML I don't mind so much as long as it's reasonably clean.
> 
> Their Markdown looks like this:
> 
> ```
> @[youtube](dQw4w9WgXcQ)
> ```
> 
> But that's not good as it's not standard and, if the plugin is not enabled, it won't work at all. So our Markdown should look like this:
> 
> ```
> [youtube](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
> ```
> 
> which is standard. It's actually even easier to implement since markdown-it already parses this by default. You'll need to hook into link_open I think.

okay, I will give this a try

**Comment by Rahul-Shaikh** [comment]
> No I mean the input Markdown should be standard. The output HTML I don't mind so much as long as it's reasonably clean.
> 
> Their Markdown looks like this:
> 
> ```
> @[youtube](dQw4w9WgXcQ)
> ```
> 
> But that's not good as it's not standard and, if the plugin is not enabled, it won't work at all. So our Markdown should look like this:
> 
> ```
> [youtube](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
> ```
> 
> which is standard. It's actually even easier to implement since markdown-it already parses this by default. You'll need to hook into link_open I think.

Do you mean to install the plugin then open the plugin's source code where the link destination is parsed and then only keep the code with accepts the standard format?

**Comment by laurent22** [comment]
> Do you mean to install the plugin then open the plugin's source code where the link destination is parsed and then only keep the code with accepts the standard format?

I'm not sure what you mean. You're free to start from that existing plugin if you want. But to be honest the bulk of the work will be in detecting and parsing the YouTube URL and this is not in the existing plugin. Maybe start from scratch with a new plugin, and copy/paste the parts of the other plugin that might be useful (in particular the part to render the YouTube HTML code).

**Comment by coderrsid** [comment]
@laurent22  I read the conversation in the @Rishgod 's PR. Can i still work on this issue?

**Comment by KoushikSahu** [comment]
Considering the last PR wasn't merged can I work on this issue?

**Comment by Rahul-Shaikh** [comment]
Yeah sure. I am not working on that currently.

**Comment by iamtalwinder** [comment]
Hey, I'm trying to solve this issue but run into this problem.

**Any change in Setting.ts does not reflect in UI.**

Like here, I changed the label of a plugin, but it didn't change in UI.

https://user-images.githubusercontent.com/61012185/111434166-3a80ee80-8725-11eb-89ee-63df16348259.mp4

I was trying to add my plugin here; as you can guess, it didn't show up in the UI. 

Am I doing something wrong?

**Comment by roman-r-m** [comment]
Your video isn't working for me, says the file is corrupt

**Comment by laurent22** [comment]
Actually we already support videos so this issue can be closed now.

**Comment by iamtalwinder** [comment]
Ok, then I'll find some other issue. :smiley:

**Comment by Rahul-Shaikh** [comment]
I am not working on this feature.

**Comment by seanieb** [comment]
> Actually we already support videos so this issue can be closed now.

@laurent22 Is there documentation for this feature?  This doesn't work.
`[My YouTube video](https://www.youtube.com/watch?v=StTqXEQ2l-Y)`

**Comment by padreputativo** [comment]
This still doesn't work, and it's basically the only reason why I can't switch from Obsidian to Joplin.
