### ISSUE TITLE
A note in “CONFLICTS” keeps appearing and disappearing when editing

### ISSUE THREAD

**Issue by tangodev** [laurent22/joplin#2709]
When having conflicted notes and editing the one in CONFLICTS folder, it starts to disappear and reappear.

## Environment

Joplin version: 1.0.193.1388 Appimage
Platform: Linux
OS specifics: Ubuntu 18.04 LTS (KDE Neon) 64-bit

## Steps to reproduce

1. Create a conflict
2. Wait for the CONFLICT folder to appear
3. Start editing the note in the CONFLICT folder
4. The note vanished from view

When a note vanishes, you have to click on a different notebook+note and then refocus back to the note in the CONFLICTS folder.

## Describe what you expected to happen

I expected the note to stay visible and allow me to edit it.

**Comment by superfreeman1989** [comment]
I keep getting conflicts generated on ios

**Comment by mic704b** [comment]
I think I understand what's going on here and can fix it.

Laurent, I don't think the comment in the sync code matches the behaviour.  Should the parent of the conflict note (duplicate) have its parent set to the conflict folder?

```
// ------------------------------------------------------------------------------
// Create a duplicate of local note into Conflicts folder
// (to preserve the user's changes)
// ------------------------------------------------------------------------------

if (mustHandleConflict) {
	const conflictedNote = Object.assign({}, local);
	delete conflictedNote.id;
	conflictedNote.is_conflict = 1;
	await Note.save(conflictedNote, { autoTimestamp: false, changeSource: ItemChange.SOURCE_SYNC });
}
```

**Comment by mic704b** [comment]
BTW my understanding the way it's meant to work is that the duplicate note is created in the parent folder of the original note, but the duplicate note appears in the Conflicts folder (due to the `is_conflict` field being one).

I think this code snippet agrees with that.

The bug is elsewhere where it assumes otherwise, but I just want to be sure I understand correctly.

**Comment by laurent22** [comment]
> BTW my understanding the way it's meant to work is that the duplicate note is created in the parent folder of the original note, but the duplicate note appears in the Conflicts folder (due to the `is_conflict` field being one).
> 
> I think this code snippet agrees with that.
> 
> The bug is elsewhere where it assumes otherwise, but I just want to be sure I understand correctly.

Yes that's correct. The conflict note has all the same attributes as the original note, including parent_id, but it has is_conflict set to 1 so that it is handled differently. But otherwise I'm not sure exactly what happens when a note is edited directly in the Conflict directory.
