### ISSUE TITLE
Sorting is always falling back to the same order

### ISSUE THREAD

**Issue by alexdevero** [laurent22/joplin#271]
The sorting (reverse sort order/non reverse sort order) between Joplin app on Windows 10 and iOS app are different even though the settings are the same. Also, enabling or disabling "Reverse sort order" option in Windows 10 desktop app always leads to sorting from the oldest to the newest, oldest on top as shown on image (My sorting settings are by date created).

### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [X] iOS

### Application

- [X] Desktop
- [X] Mobile
- [ ] Terminal

### Screens (titles of notes are the same as date of creation):
Desktop - top of the list (wrong order):
![jop-top](https://user-images.githubusercontent.com/4237724/36943477-76ff938a-1f8a-11e8-82d2-0f4afd55fc8e.PNG)

Desktop - bottom of the list:
![jop-bottom](https://user-images.githubusercontent.com/4237724/36943480-867e8dca-1f8a-11e8-973a-a13e6a1627a5.PNG)

iOS - top of the list (correct order):
![jop-ios](https://user-images.githubusercontent.com/4237724/36943484-8d9a70ec-1f8a-11e8-83ba-41598d85063f.PNG)

The correct desktop order should follow the order in iOS app - item "03.03.2018" should be on the top as first and latest, not on the bottom.

**Comment by alexdevero** [comment]
It seems that sorting may be actually the same between devices. The real issue is that it the Reverse order option doesn't work properly. The sorting always falls back to the same order, with the oldest entry on top. This happens either after editing the note or re-launching the app.

**Comment by laurent22** [comment]
Hmm, I can't replicate this. For example, if I modify a note, then sort by updated time, that modified note is at the bottom. If I click Reverse Sort Order, that note is on top as expected. I can also see that the created time order is respected.

Could you double-check and see if you can replicate it? If so, post here the steps you followed (including changing screen, restarting app, etc.)

**Comment by alexdevero** [comment]
Here you go:
https://www.dropbox.com/s/h3liiiiz0ipf0jd/joplin.mp4?dl=0

**Comment by alexdevero** [comment]
Thank you!

**Comment by alexdevero** [comment]
@laurent22 when will be released new version with this being patched?

**Comment by alexdevero** [comment]
@laurent22 it seems that this issue is still present in iOS app.
