### ISSUE TITLE
Sidebar not closing if map id is not present

### ISSUE THREAD

**Issue by ishantgupta777** [laurent22/joplin#2715]
The sidebar has an option that says view on the map and if there is an error it just stays there and shows an error on the main screen, where the error is not properly visible. So if we get an error, the sidebar should close, this is really important in terms of user experience. 

## Environment

Joplin version: 1.0.320
Platform: windows
OS specifics: No

## Steps to reproduce

1. Click on add a note and then click on three dots option at the top right and then click on properties
2.  Then you will get an option saying view on the map and if you doesn't have aid, it will show an error " This note doesn't have geolocation information ". 
3. The error will be on the next screen partially visible.

![Screenshot_1583844780](https://user-images.githubusercontent.com/27751740/76314347-9dfb6380-62fc-11ea-9781-35f0ef15e97f.png)

## Describe what you expected to happen

The sidebar should have close and error dialog should be fully visible

 I would like to work on this issue

**Comment by laurent22** [comment]
Thanks for investigating this. If you could create a pull request for it that would be great.

**Comment by ishantgupta777** [comment]
Sure, I will do it asap. Thanks.

**Comment by ishantgupta777** [comment]
@PackElend  can you please add gsoc2020 label in this PR.
