### ISSUE TITLE
Export: Internal Links Not Maintained

### ISSUE THREAD

**Issue by varian93** [laurent22/joplin#2716]
When exporting notes to Markdown internal links are broken if both the source & destination notes are not exported together (the internal link will point to "../undefined"). If both notes are exported at the same time then the link will be maintained.

When exporting notes to HTML internal links are always broken. They point to the name of the of the original source HTML file with a "#" appended to the end. If a note titled foo.html contains a link to bar.html then upon exporting the 2 notes, the link in foo.html that points to bar.html will be: foo.html#

## Environment

Joplin version: 1.0.193
Platform: Windows
OS specifics: Windows 10 64 bit

## Steps to reproduce

1. Export any note that contains internal links to either Markdown or HTML.

## Describe what you expected to happen

**Expected Markdown Exporting Behavior:**

I expected internal links to be properly exported even if the exporting procedure did not involve both the source & destination note.

**Expected HTML Exporting Behavior:**

I expected the internal links to be properly maintained through the exporting process.

## Logfile

Obviously anything pertinent will be closest to the bottom of the [log file](https://github.com/laurent22/joplin/files/4312636/log.txt).

I also noticed several warnings in the debug console as soon as I opened Joplin. I saved this information as [console.txt](https://github.com/laurent22/joplin/files/4312649/console.txt)

**Comment by RedDocMD** [comment]
Can you provide an example file because I don't seem to be able to reproduce this error.

**Comment by varian93** [comment]
Certainly.

I created a notebook named "Example". I exported it in JEX format.

It contains 2 notes. "I Like a Little Magic in My Life" & "~My Music". The former contains a link to the later. 

I also exported both notes individually as Markdown, so that you can see the "../undefined". If I were to have exported them simultaneously the link would have been maintained.

All 3 files were archived in a zip file & attached. 

Those were the original 2 notes that I noticed the issue with. I significantly shortened them, but maintained their filenames in case that had anything to do with it.

[example.zip](https://github.com/laurent22/joplin/files/4320114/example.zip)

**Comment by agnoldo** [comment]
Hi,

I can confirm the same problem when exporting a notebook to HTML. I've used the "Welcome! (Desktop)" notebook on Windows app and created a note called index, so it could be exported to an index.html file.

This worked perfectly for index note but the links that it contained were not corrected when exporting to HTML.

Here's "index" note in Markdown:
```
# Welcome! (Desktop)

- [1. Welcome to Joplin! 🗒️](:/ce2fff22682544309ce2d01b69ca34a3)
- [2. Importing and exporting notes ↔️](:/a653606a78bf41be93031ae8e72a59b7)
- [3. Synchronising your notes 🔄](:/5d6479d2a59240c98bdb65e6e9c09369)
- [4. Tips 💡](:/7b0e3cdac1494689bedd4b0e75af1283)
- [5. Privacy](:/9b76c6b3494244049de4a8e8c4210a7d)
```

And here's "index.html":
```
<div id="rendered-md"><h1 id="welcome-desktop">Welcome! (Desktop)</h1>
<ul>
<li><a data-from-md data-resource-id='ce2fff22682544309ce2d01b69ca34a3' title='' href='#' type=''>1. Welcome to Joplin! 🗒️</a></li>
<li><a data-from-md data-resource-id='a653606a78bf41be93031ae8e72a59b7' title='' href='#' type=''>2. Importing and exporting notes ↔️</a></li>
<li><a data-from-md data-resource-id='5d6479d2a59240c98bdb65e6e9c09369' title='' href='#' type=''>3. Synchronising your notes 🔄</a></li>
<li><a data-from-md data-resource-id='7b0e3cdac1494689bedd4b0e75af1283' title='' href='#' type=''>4. Tips 💡</a></li>
<li><a data-from-md data-resource-id='9b76c6b3494244049de4a8e8c4210a7d' title='' href='#' type=''>5. Privacy</a></li>
</ul>
</div>
```

**Comment by agnoldo** [comment]
Exporting internal links to HTML correctly is a huge advantage for Joplin, since it can be used to build simple documentation sites, for instance. In the future I can see templates being used in order to export notebooks using CSS frameworks like Bootstrap. Wouldn't it be cool?
