### ISSUE TITLE
No option for select all in notes

### ISSUE THREAD

**Issue by ishantgupta777** [laurent22/joplin#2721]
In any notebook, while selecting notes, let just I have so many notes in a notebook and I want to delete most of them, for that, there is no option of select all in the navbar. It's necessary for users if they want to edit or delete most of the notes except few, so they need to select all features.

![Screenshot_1583891971](https://user-images.githubusercontent.com/27751740/76374908-7b079880-636a-11ea-8998-95a91b8bd6c0.png)

## Environment

Joplin version:  1.0.320
Platform: Mobile
OS specifics: No

## Describe what you expected to happen

I expected it to have an option to select all, so that if I want to delete most of them at a  time. I can just select all and deselect the few I don't want to delete. It would be so much easier for users.

I would like to work on this.

**Comment by laurent22** [comment]
How do other apps allow selecting all items? Do you have some examples?

**Comment by Rishgod** [comment]
> How do other apps allow selecting all items? Do you have some examples?

I believe you press on the note for a second it gets selected and then your drag your finger down to the bottom to select all or tap on the notes you want to delete

**Comment by ishantgupta777** [comment]
> How do other apps allow selecting all items? Do you have some examples?

Mostly there is a button with tick icon on navbar,  by clicking that we can select all the items.

**Comment by ishantgupta777** [comment]
> > How do other apps allow selecting all items? Do you have some examples?
> 
> I believe you press on the note for a second it gets selected and then your drag your finger down to the bottom to select all or tap on the notes you want to delete

Dragging can work, but it's more complicated for users than just clicking a button. But can also work.

**Comment by DeadManIV** [comment]
This is an example of how it could work. Long press to select multiple notes, then a button at the top to select all. Or something like that.
![Select all example](https://user-images.githubusercontent.com/9134591/76456726-5e517c00-63cf-11ea-8e9b-fb2610f39262.gif)

**Comment by ishantgupta777** [comment]
> This is an example of how it could work. Long press to select multiple notes, then a button at the top to select all. Or something like that.
> ![Select all example](https://user-images.githubusercontent.com/9134591/76456726-5e517c00-63cf-11ea-8e9b-fb2610f39262.gif)

Yeah exactly, this is what I am trying to implement.
