### ISSUE TITLE
Note is present even after removing title and body

### ISSUE THREAD

**Issue by ishantgupta777** [laurent22/joplin#2722]
If I make a note and save it. And if I come back and delete the title of the note and its body also and save it. There is literally nothing in that note remained. So it should be automatically deleted. But it's not happening. An empty untitled note is getting saved.

## Environment

Joplin version: 1.0.320
Platform: Mobile
OS specifics:  No
![untitled](https://user-images.githubusercontent.com/27751740/76376186-b5bf0000-636d-11ea-8947-111090a5f009.gif)

## Steps to reproduce

1. Save any note with some text
2. Open that note again and delete title and body from the note
3. Save it

## Describe what you expected to happen

I expect it automatically gets deleted if I remove the title and body from the note.

I would like to work on this.

**Comment by Rahulm2310** [comment]
@ishantgupta777  i don't think that's a bug.That's the way it should be..

**Comment by ishantgupta777** [comment]
@Rahulm2310 I know it's debatable that it's a bug or feature.  But if you see in most applications like this,  if you delete title and body, the note will get deleted. For ex: gTasks. And also this is also bad for user experience, some users have a habit of just clearing tasks and going back,  they never delete it,  for them, there will be a alot of empty notes, which are just useless. There shouldn't be any empty notes.

**Comment by sinkuu** [comment]
> There is literally nothing in that note remained.

That's not always true. Joplin has [note history feature](https://discourse.joplinapp.org/t/note-history-feature-now-in-joplin/2469), which means you can possibly restore the previous state even from an empty note.

**Comment by ishantgupta777** [comment]
@sinkuu oh okay okay,  I didn't know that. Thanks for the info.

**Comment by virtadpt** [comment]
If you want to really delete a note, right-click (or control-click) on it in the notes list, then select "delete."
