### ISSUE TITLE
Proper extension for all files

### ISSUE THREAD

**Issue by ishantgupta777** [laurent22/joplin#2725]
All the files in the ReactNative folder which are React components are also in the js file extension. This messes up with extension like Prettier and changes the code if anyone using Prettier or similar extension didn't change the extension. Even without that, giving .jsx extension is better for the overall React environment. So @laurent22  should I change the file extensions for react components in which we have used jsx.

**Comment by tessus** [comment]
The js files are generated from the jsx files and only local (they are in gitignore).

- No, do not change the Joplin source tree.
- Don't use the gh tracker for dev questions - the forum has a `Development` category.
- fix your editor / prettier behavior
