### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ferencdv** [laurent22/joplin#273]
### Operating system

- [X ] Windows
- [ ] macOS
- [ ] Linux
- [X] Android
- [ ] iOS

### Application

- [X] Desktop
- [X] Mobile
- [X] Terminal

Would it be possible to have an option for "stacks" of notebooks. So for example in my work I can have a stack labeled "Projects" and another say "Courses" that I teach. These essentially act as folders.
Fantastic software by the way! Congratulations and thanks for your generosity making this available!

**Comment by laurent22** [comment]
I guess that would be a special case of duplicate #122

**Comment by laurent22** [comment]
Dupicates #122

**Comment by laurent22** [comment]
Duplicates #122

**Comment by laurent22** [comment]
Duplicate #122

**Comment by laurent22** [comment]
Duplicate of #122
