### ISSUE TITLE
App closes when i hit Configuration button

### ISSUE THREAD

**Issue by hrqmonteiro** [laurent22/joplin#2732]
Hi, i was using the app on LineageOS for a while, but since the next update, i simply am not being able to open configurations, when i hit it, app simply closes.

I tried reinstalling, cleaning cache and storage, and even downloading an older version doesn't help with it.

**Comment by tessus** [comment]
You either use the template or you can ignore it and we close the issue.

**Comment by hrqmonteiro** [comment]
Fucking moron
