### ISSUE TITLE
Save and discard dialog has no affect

### ISSUE THREAD

**Issue by ishantgupta777** [laurent22/joplin#2738]
Platform: Mobile
OS specifics: No 

## Steps to reproduce

1.  Make a new note or edit a note.
2.  Click back arrow key before it gets saved automatically.
3. You will get a dialog that has options of saving and discarding, but clicking discard doesn't discard changes.

## Describe what you expected to happen

I expected either shouldn't have discard options or it should discard changes after I click on that.

@laurent22  @tessus  can you please tell how should I work on this, I mean, should I remove discard option or discard changes after clicking discard button.
![save_dialog](https://user-images.githubusercontent.com/27751740/76513944-1be67880-647d-11ea-8df9-c2e758b209ca.gif)

**Comment by laurent22** [comment]
The dialog should be removed and the note saved automatically instead.

This dialog was from it was necessary to manually save the notes, but now it's done automatically.

**Comment by ishantgupta777** [comment]
> The dialog should be removed and the note saved automatically instead.
> 
> This dialog was from it was necessary to manually save the notes, but now it's done automatically.

Okay so I will remove it and add a PR.
