### ISSUE TITLE
Cannot sync other devices

### ISSUE THREAD

**Issue by KlugFR** [laurent22/joplin#274]
### Operating system
- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] Android
- [X] iOS

### Application
- [X] Desktop
- [X] Mobile
- [ ] Terminal

### Sync Server
- NextCloud

The "main" computer is a desktop under OSX.
Some notes were imported from Evernote (4 notebooks, a couple hundreds notes).
This main computer can sync with the server (NextCloud).

There's a backup computer (MacBook), an ipad and an iphone too.

On these three other devices, sync fails with (error seen in debug on the iphone):
"Error: Missing required property: type_: Sans titre".

This brings two issues.

First, we made some cleaning on the main computer and there's no more "Sans titre" notes. There was something like a dozen of them in several notebooks, they were renamed or deleted.
I've found out they're still there, marked as "deleted" but not delete.
Can we force the deletion?

Second, why does the other devices try to sync these deleted notes?

**Comment by laurent22** [comment]
> "Error: Missing required property: type_: Sans titre".

It means it's a corrupted notes, which was created by an old version of Joplin. Normally new versions don't have this bug.

Even though you might have deleted it locally that corrupted note is still on your Nextcloud folder. One solution would be to search for it on Nextcloud (maybe search for "Sans titre" or, directly, for the ID, which should appear in the log), and delete it.

**Comment by KlugFR** [comment]
I'm trying.
But I'm not sure it will work in the end.

I've already deleted 23 out of 407 notes this way and it's not finished yet, each time I try to sync it fails on another note.
The notes I have to delete are not empty, they contain important data.
So this is not a good way to deal with the problem.

Also, considering 99% of the current notes are actually Evernotes imported and were imported at the same time (with a bad Joplin version?), does it mean I will have to delete them all in the end?
Then re-import them?

**Comment by laurent22** [comment]
Do you have all the correct data on the macOS version? If so, I would do this:

- Export it to JEX format from the macOS app
- Delete all the data in Nextcloud
- Uninstall all the apps on all the devices, delete all the profiles (in ~/.config/joplin-desktop) and reinstall.
- Reimport the JEX file in macOS
- Re-sync all the devices

Also make absolutely sure you have the latest Joplin version on all the devices.

Because this is a one-off issue due to a bad Joplin version there's unfortunately no automated way to deal with this. If such an issue happens again, I might provide a better way to deal with the corrupted data.

**Comment by KlugFR** [comment]
I did about what you suggested:
 . exported the new/modified notes since the "big Evernote import" (a dozen, easy thanks to "sort notes by editing date") 
 . deleted the Joplin folder on NextCloud
 . synced Joplin on the Mac (lost all notes)
 . import the new/modified notes
 . re-import the Evernote notes

It seems it worked, I have all the notes (and notebooks) on the Mac, in NextCloud and on the ipad.

Merci.

**Comment by laurent22** [comment]
De rien, good to know it's working now.
