### ISSUE TITLE
Android sharing doesn't work (other app --> Joplin)

### ISSUE THREAD

**Issue by cselti** [laurent22/joplin#2745]
## Environment

Joplin version: 1.0.320 (released on 8th of March in Play Store)
Platform: Android
OS specifics: 10 Q, MIUI 11

## Steps to reproduce

1. open an app with share feature (Brave browser, gReader RSS, Simplenote, etc)
2. choose the Joplin from the possible app list
3. Joplin doesn't create a note, just shows the content of the actual notebook/

## Describe what you expected to happen
It should create a new note - but nothing happens.
It works in the previous version, 

## Logfile

[syncReport-1584097643387.txt](https://github.com/laurent22/joplin/files/4329201/syncReport-1584097643387.txt)

**Comment by ishantgupta777** [comment]
This is one of the ideas for GSoC-2020.  You can go through the list of ideas and suggest your new ideas in the Joplin forum ( https://discourse.joplinapp.org/ ).
https://joplinapp.org/gsoc2020/ideas.html#4-sharing-on-mobile

**Comment by cselti** [comment]
it's not a feature request, it's simply a bug. This worked in the previous version.

**Comment by ishantgupta777** [comment]
> It's not a feature request, it's simply a bug. This worked in the previous version.
> 
> I already written to joplin forum to this topic (https://discourse.joplinapp.org/t/use-page-title-or-h1-when-sharing-url-to-joplin-on-android-and-i-assume-ios/2037/6) a couple week ago that mobile app sharing function should be improved a little (~a basic sharing functionality).
> 
> The GSoC idea is an "advanced" sharing capability - I hope it will come true 😃

Thanks for the info, I thought you are talking about that feature. I will look at your topic in the forum.  And also this bug.

**Comment by bedwardly-down** [comment]
One thing about this bug is that sharing is currently indefinitely broken on mobile devices. The only functional react native library for this feature has currently been abandoned by its maintainer and no one has stepped up to fix its current issues or updated it to work properly with new react versions.

If anyone here is willing to take the mantle as its maintainer, have at it.

**Comment by ishantgupta777** [comment]
> One thing about this bug is that sharing is currently indefinitely broken on mobile devices. The only functional react native library for this feature has currently been abandoned by its maintainer and no one has stepped up to fix its current issues or updated it to work properly with new react versions.
> 
> If anyone here is willing to take the mantle as its maintainer, have at it.

I would like to help, can you please tell the name of library and help me with the procedures.

**Comment by bedwardly-down** [comment]
https://discourse.joplinapp.org/t/android-share-and-send-functionality/1898

The share functionality was removed from Joplin but this thread should help you get an idea

**Comment by ishantgupta777** [comment]
> https://discourse.joplinapp.org/t/android-share-and-send-functionality/1898
> 
> The share functionality was removed from Joplin but this thread should help you get an idea

I looked at the library and the author. Let me see if I'll be able to help and contribute to it. Thankds for help.

**Comment by bedwardly-down** [comment]
> > https://discourse.joplinapp.org/t/android-share-and-send-functionality/1898
> > The share functionality was removed from Joplin but this thread should help you get an idea
> 
> I looked at the library and the author. Let me see if I'll be able to help and contribute to it. Thankds for help.

One thing about it: if it’s fully abandoned and the author is no longer available to transfer permissions of the repo to you, you’ll need to fork it and possibly register the library under a new name on npmjs.org (the main database for all node libraries currently available). I don’t know the steps for doing just that and you’d most likely have to do quite a bit of considerable work and have an active userbase to get approved.

**Comment by tessus** [comment]
This is not a bug. The feature was removed to do the upstream package not working with the react-native version we had to upgrade to.

This will come back eventually.

**Comment by cselti** [comment]
I hope that will be solved somehow in the future (library update and/or GSoC).
I choose the app downgrade to 1.0.316 version from an alternative play store.
Thanks for your help and quick reply!

**Comment by tessus** [comment]
I couldn't agree more. It's a key feature that we all want.

But Joplin uses 2 major frameworks: React-native and Electron. Sometimes we keep them stable for as long as possible. e.g. we still used Electron 4, when Electron 7 was out.
But there come a point where we have to upgrade these frameworks.

Unfortunately Facebook does not care about backwards compatibility. So the last react-native upgrade broke a lot of things, which we could all fix, but the sharing extension. Which I have to say has not only been unmaintained for the last 2 years, but had massive issues to begin with.
Why do you think that it was only possible to share text with Joplin and why wasn't there something similar on iOS?

> Could it cause dropbox sync issue?

This depends. We changed the encryption algorithm, so if the clients are not all on the same level (which is kind of hard to see from the versioning scheme), there might be issues when you use encryption. e.g. if you are using the latest desktop client but an older mobile client.

Currently the sync hasn't changed, so you should be fine. E2EE could present an issue.

**Comment by bedwardly-down** [comment]
I think it’s less about not caring and more about being in a rapidly expanding and changing market with multiple external factors all affecting how much support Facebook and other companies like it can offer to older versions. 

Either way, if somebody who’s much smarter than i can either get an alternative going or get the original project working, that would definitely be beneficial to everyone, especially Joplin. Good work guys working with what you can and keeping things together like this.

**Comment by cselti** [comment]
I understand the problem - the used 3rd library has not been maintained for 2 years and it isn't compatible with the newer react-native version...

Thanks for the information, and I'm really appreciate your efforts of Joplin development. Joplin is such an application that I'm looking for couple years ago :smiley:
