### ISSUE TITLE
Small font size in the left panel of linux appimage.

### ISSUE THREAD

**Issue by tigos2** [laurent22/joplin#2746]
Since v. 1.0189 (all be good), font in the left panel and subpanel, where is "All notes" and subnotes - is very small. Change theme in Settings not been effect.

## Environment
Joplin version: 1.0.193 (prod,linux)
Platform: Linux Unknown 5.5.8-200.fc31.x86_64 #1 SMP Thu Mar 5 21:28:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
OS specifics: Fedora 32 (KDE Spin)

## Steps to reproduce

1. 
2. 
3.

**Comment by dpoulton-github** [comment]
Possibly not a bug. I have found that on laptops with a higher dpi the default interface text size can look a bit small. 

Therefore you can use **View** > **Zoom In** or `CTRL` + `=` to increase the font sizes. If you go too far, `CTRL` + `-` reduces it, `CTRL` + `0` sets it back to default.

If you have already set a larger editor font size in settings to compensate you may have to drop it back down a few points if you wish the interface / editor fonts to be of similar size.
