### ISSUE TITLE
Tag creation does not support case preservation (Case preservation is supported for imported tags, however).

### ISSUE THREAD

**Issue by JoshDesmond** [laurent22/joplin#2750]
Note: This issue has been discussed before, but I believe the discussion was left incomplete. References to past discussions are included 

## Issue:
Tags in Joplin are case insensitive, and I am **not** suggesting that be changed. However, support for [case preservation](https://en.wikipedia.org/wiki/Case_preservation) is inconsistent. When tags are imported, case preservation is supported; and thus, notes with mixed case are supported in Joplin. When a new tag is created or a tag is renamed, however, case preservation is not supported. This discrepancy is unintuitive, and thus warrants "fixing".

## Previous Discussion
It appears that case sensitivity was an issue for imported tags sometime ago, and some issues addressed this, along with the problem of case preservation. @laurent22 addressed these concerns, stating,

- "This is not a bug. In Joplin, tags are case-insensitive, however if they are imported from somewhere else they are left as-is."
- "Yes there was indeed some issue with the way tags with uppercases were handled. This will be fixed in the next version." (The referenced bug caused by mixed case was indeed fixed).
- "Case-insensitivity is a feature, not a bug, so that it cannot be changed. If there's a bug related to it though, there might be other ways to fix it."

The issue I'm raising, however, is **not** about case sensitivity. It is about case preservation, which is a different issue. Case insensitivity should remain, but case preservation should be supported for the creation and renaming of tags.

See  
- https://github.com/laurent22/joplin/issues/651
- https://github.com/laurent22/joplin/pull/660#issuecomment-401756830
https://github.com/laurent22/joplin/issues/129

## Environment

Joplin version: 1.0.193 (prod, win32)
Platform: Windows
OS specifics: Windows 10 Pro, Version 10.0.18362 Build 18362

## Steps to reproduce

1.) I created a new note, and entered the "Add or Remove tags" view for that note. I then type .Test as a new tag name, and the suggestion appears that I create a new tag.
![First Image](https://user-images.githubusercontent.com/8055127/76671127-f3d54300-656a-11ea-9c14-e506a8e78ac9.png)
2.) I accept the option to create a new tag by clicking on the suggestion, and my new tag, ".Test", appears to be accepted with the correct capitalization.
![Second Image](https://user-images.githubusercontent.com/8055127/76671151-ffc10500-656a-11ea-8fc0-216670f0f1e9.png)
3.) Once I exit the tag view for the note, the tag is then converted to lowercase.
![Third Image](https://user-images.githubusercontent.com/8055127/76671102-cbe5df80-656a-11ea-8d51-6824eb4c417a.png)

In the images, however, you'll see that a similar tag is in place which _does_ use capitalization. I managed to get that note by importing from Evernote, suggesting that perhaps there is something unnecessarily converting text to lowercase at the time of tag creation.

## Describe what you expected to happen

- Tags should support mixed case input. 
- Renaming a tag and entering the same text with different casing should update the tag's casing. 
- Two tags with different casing should never exist, or rather, two tags with the same text but different casing should be considered the same tag. (Ensuring this remains true probably involves a few user stories across different platforms, i.e.:
- If a user tries to create a tag with different casing than an existing tag, it should automatically convert the tag to whatever casing is used in the existing tag.

**Comment by dpoulton-github** [comment]
In addition to the stated previous GitHub issues something very similar has also previously been raised on the Joplin forum:

https://discourse.joplinapp.org/t/tags-lower-case-only/4220
