### ISSUE TITLE
The touchable opacity effect should not overflow the add button, new todo & new note buttons

### ISSUE THREAD

**Issue by Rahulm2310** [laurent22/joplin#2751]
## Environment

Joplin version: 1.0.322
Platform: Mobile
OS specifics: No

![20200314_125757](https://user-images.githubusercontent.com/54268438/76677383-b23caa80-65f3-11ea-8f09-5b87ad5b0813.gif)

## Describe what you expected to happen
The touchable opacity effect must not have the square overflow on the add, new todo,new note buttons.

I would love to work on this issue.

**Comment by Dharmesh-Poddar** [comment]
@Rahulm2310  are you working on it?

**Comment by Rahulm2310** [comment]
@Dharmesh-Poddar Go ahead brother!
