### ISSUE TITLE
Wrong calendar display in desktop version

### ISSUE THREAD

**Issue by xplosionmind** [laurent22/joplin#2753]
OS: MacOS 10.15.3
App Version: v1.0.194

### BUG DESCRIPTION

When the calendar is opened to select an alarm date and time, this is what I see:

<img width="658" alt="Screenshot" src="https://user-images.githubusercontent.com/42862428/76679816-c7114200-65e3-11ea-9fe8-356fe65245ec.png">

This is happening since I upgraded to version v1.0.189

### IMPROVEMENT

Since I'm here, may I suggest a little and simple calendar redesign? I know there is on the table an overall app redesign, but the calendar is to me the ugliest thing, other stuff layout and design is ok.

**Comment by RedDocMD** [comment]
This seems to be a Mac OS X specific problem. On Linux it is:
![image](https://user-images.githubusercontent.com/54888685/76686764-d58f4600-6643-11ea-8b22-a739ce913fd0.png)

**Comment by RedDocMD** [comment]
@tessus, can you please confirm?

**Comment by xplosionmind** [comment]
@RedDocMD if you watch closely on both sides of your calendar there's a less noticeable difference in your bezels, too. Maybe it could be a display or resolution thing

**Comment by Rolograaf** [comment]
![calendarUI_joplin](https://user-images.githubusercontent.com/6130902/76687835-f8abfc80-6627-11ea-9ac2-9799f7b6d592.png)
For your information the UI in Windows 10. However Joplin has never asked me for permission to show me alarms in Windows and it does not work for me.

**Comment by tessus** [comment]
Yep, something is off. I don't know what though.

**Comment by kowalskidev** [comment]
It seems like problem is in "node_modules/react-datetime/css/react-datetime.css". in the class `rdtPrcker` where I changed from `width:40px` to `width:auto` by doing so date picker dialogue adjust its width on any resolution screen. This bug is in **react-datetime** module.

**Comment by HOLTVENE** [comment]
There's a less noticeable difference in your bezels, too. Maybe it could be a display or resolution thing,,

**Comment by anjulalk** [comment]
I can also recreate it. Also, the whole calendar looks off from the rest of the app.

**Comment by xplosionmind** [comment]
this issue hasn’t been fixed yet

**Comment by xplosionmind** [comment]
again, not fixed yet.

**Comment by xplosionmind** [comment]
still an issue

**Comment by xplosionmind** [comment]
still an issue.
