### ISSUE TITLE
Mac minimise keyboard shortcut does not work

### ISSUE THREAD

**Issue by b-a0** [laurent22/joplin#2755]
On a Mac there is a keyboard shortcut to minimise a window into the dock. By default the keyboard shortcut is <kbd>⌘</kbd><kbd>M</kbd> and it refers to the menu option `Window -> Minimise`.
Unfortunately this menu option and keyboard shortcut are not available in Joplin and I cannot minimise the window via a keyboard shortcut, only via the the yellow button in the titlebar.

## Environment

Joplin version: 1.0.193 (prod, darwin), revision 58e2d7b (master)
Platform: macOS
OS specifics: 10.15.3

## Steps to reproduce

1. Open Joplin
2. Press the keys <kbd>⌘</kbd><kbd>M</kbd> simultaneously

## Describe what you expected to happen

I expect the Joplin window to minimise into the Dock.

## Describe what actually happens

Nothing happens, the Joplin window stays active and is not minimised.

## Logfile

No log entry is written.

**Comment by tessus** [comment]
This is not a bug. It's not been implemented. You can use `Cmd+H` or `Cmd+W`.

Please open feature requests on the forum.
