### ISSUE TITLE
Question: How to update terminal app?

### ISSUE THREAD

**Issue by fmrtn** [laurent22/joplin#276]
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [x] Terminal

How should I update the terminal application?

I run `npm update` inside ` ~/.joplin-bin/lib/node_modules `

``` fmrtn@ZenBook3:~/.joplin-bin/lib/node_modules$ npm update ```

Are there a better way to do that?

**Comment by laurent22** [comment]
It might depends on how you installed it. In my case I just do `npm -g i joplin` and it works.
