### ISSUE TITLE
Extra block for inline LaTeX in preview after opening with WYSIWYG editor

### ISSUE THREAD

**Issue by ruivieira** [laurent22/joplin#2760]
## Environment

Joplin version: 1.0.194 (prod, darwin)
Platform: macOS
OS specifics: 10.15.3

## Steps to reproduce

1. Open an existing note with inline LaTeX in the WYSIWYG editor and then switch back to split layout.

## Describe what you expected to happen

When switching back the split layout, I expected to see an inline equation only as in previous versions. Instead I see an extra block as in the attached screenshot.

Markdown:
![image](https://user-images.githubusercontent.com/327909/76693408-42aed580-665c-11ea-9cce-6858b375a953.png)

Preview:
![image](https://user-images.githubusercontent.com/327909/76693413-51958800-665c-11ea-825d-2c6f2597fdb4.png)

**Comment by anjulalk** [comment]
Duplicate of #2811?
