### ISSUE TITLE
When the editor is in Viewer mode, enable "Open in external editor" menu item

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2762]
This item was recently disabled in a pull request, but it should always be enabled in all views.

Forum thread: https://discourse.joplinapp.org/t/external-editor-shortcut-available-in-any-layout-view-mode/6958?u=laurent

**Comment by Hardik500** [comment]
I would like to work on this issue.

**Comment by Rahulm2310** [comment]
@laurent22 can you please describe the version of the desktop app.It seem to be working in 1.0.194

**Comment by laurent22** [comment]
Yes actually because the implementation was so sloppy it sometimes works, sometimes doesn't. For example if you go to the setting, then back to the notes, "Edit in External Editor" is enabled. If you toggle between notes however it is disabled.

For now, let's just make it enabled all the time. It's the item "Edit in External Editor" below:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/1285584/76699528-2041aa00-66a6-11ea-9947-9932d7710c9a.png">

**Comment by 3sne** [comment]
@Rahulm2310 Hey there. Bear with me as I am new here :smile: 
Since we want `edit:commandStartExternalEditing` to be enabled all the time, should we remove it as a target candidate during `updateMenuItemStates` by removing it as iterable in the for loop, or add it a special condition to set it to `true` on every update event (as you have done)? Wouldn't Approach 1 be cleaner? 
@laurent22 What are your thoughts on this?

**Comment by Rahulm2310** [comment]
> @Rahulm2310 Hey there. Bear with me as I am new here 
> Since we want `edit:commandStartExternalEditing` to be enabled all the time, should we remove it as a target candidate during `updateMenuItemStates` by removing it as iterable in the for loop, or add it a special condition to set it to `true` on every update event (as you have done)? Wouldn't Approach 1 be cleaner?
> @laurent22 What are your thoughts on this?

I don't think brother that completely removing "commandstartexternalediting" from the for loop is better.This is just a temporary fix for the issue so removing something doesn't seem to a good approach to me.Rest all depends on @laurent22 .

**Comment by Rahulm2310** [comment]
@Hardik500 I think you didn't saw that I already linked a PR to fix this issue.This is not the right way of contributing to a open source org.

**Comment by anihm136** [comment]
@Rahulm2310 I was working on it and made a PR, noticed that it was already resolved by your PR afterwards. Now I'm just trying to find out why the tests are failing. No hard feelings?

**Comment by Rahulm2310** [comment]
>No hard feelings?
Not at all. Just that you should declare when you pickup a issue to work on

**Comment by Hardik500** [comment]
@Rahulm2310 if you noticed I already commented before you, since I am new to this it took me a time to understand what to do. And in between you created a pull request which I didn't notice until I created a pull request.

**Comment by laurent22** [comment]
See https://github.com/laurent22/joplin/pull/2763#issuecomment-602041823
