### ISSUE TITLE
Mobile: Length of the note title should have a limit.

### ISSUE THREAD

**Issue by Rahulm2310** [laurent22/joplin#2771]
## Environment

Joplin version: 1.0.322
Platform: Mobile

![Screenshot_2020-03-16-01-16-37](https://user-images.githubusercontent.com/54268438/76709435-b2889300-6724-11ea-8f3d-2117af1f1fdc.png)

![Screenshot_2020-03-16-01-24-09](https://user-images.githubusercontent.com/54268438/76709468-f4b1d480-6724-11ea-9548-7581d63a116d.png)

## Describe what you expected to happen
There should be a limit to the length of the note title & if the limit is exceded, there should be some a alert  saying "input limit reached" or something like that.

**Comment by sinkuu** [comment]
That would prevent editing notes with long titles synced from Desktop app. What about using ellipsises on the lists?

**Comment by laurent22** [comment]
Yes I don't think we'll implement this. It should be done at the backend level, but doing so indeed is very complex as soon as sync is involved. Also it means we should truncate all existing note titles to 60 characters, thus losing user data.

**Comment by Rahulm2310** [comment]
Yeah, you are right.My bad
