### ISSUE TITLE
Save passwords to system keychain

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2773]
The current version of Joplin saves the sync passwords to the database. Normally, this is secure as long as the system itself is secure.

However for improved security, the passwords should be saved to the system keychain. This can be done in a cross platform way using https://github.com/atom/node-keytar

The difficulty will be too read and write these passwords in a transparent way from the Setting class.

**Comment by Rishgod** [comment]
Seems like a nice improvement!

**Comment by ishriom53tyagi** [comment]
i would like to work on it
