### ISSUE TITLE
Folders and real Filenames

### ISSUE THREAD

**Issue by ch1988** [laurent22/joplin#278]
### Operating system

- [ x] Windows
- [x ] macOS
- [ x] Linux
- [ x] Android
- [x ] iOS

Hi. It would be a really cool feature if Joplin would have
- subfolder for the notebooks - and real Folders
- real filenames instead of the cryptic names

So it would be a real useful notes appllication for nextcloud. I could work on my notes in nextcloud with the markdown editor app.
### Application

- [ x] Desktop
- [x ] Mobile
- [x ] Terminal

**Comment by laurent22** [comment]
Duplicate of #264
