### ISSUE TITLE
Inconsistent local search behavior

### ISSUE THREAD

**Issue by anihm136** [laurent22/joplin#2780]
When the layout is set to Viewer-only, "search in note" option (and keyboard shortcut) is disabled in the menu. However, if the search is initiated in a different layout and then switch to Viewer-only mode, local search is still open and works as expected (highlights matches in viewer, able to navigate through matches etc).

This is probably related to #2308 

What is the expected behavior here? If this is unexpected behavior, I would like to work on it.

**Comment by laurent22** [comment]
Again something that was disabled but shouldn't have been. Could you check if it works if you revert this commit? 0be982c798222282ab88cf6383ad2d4a56961ad6 If you could test and it works please create a pull request with it.

**Comment by anihm136** [comment]
Just to be clear, is it expected that the display mode changes to split when "search in note" is triggered from viewer-only mode?
If so, reverting the commit solves that problem

**Comment by anihm136** [comment]
However, it brings back the issues in #2467 , which it was meant to resolve. The issue is that some unnecessary menu items are checked and disabled in viewer-only mode, I feel. I think only the text manipulation commands i.e, "cut", "paste", "bold", "italics", "link", "code" and "insert datetime" need to be disabled.
If this is the right approach, it would simultaneously solve #2762 , as that option was also disabled in the same commit.
@laurent22 Let me know how you would like me to proceed

**Comment by anihm136** [comment]
>  I think only the text manipulation commands i.e, "cut", "paste", "bold", "italics", "link", "code" and "insert datetime" need to be disabled in viewer mode.
@laurent22 may I proceed to implement this?
