### ISSUE TITLE
On iOS, the status bar is not displayed correctly when the dark theme is on

### ISSUE THREAD

**Issue by Rakleed** [laurent22/joplin#2781]
## Environment

Joplin version: 10.0.45
Platform: iOS
OS specifics: 13.3.1

## Steps to reproduce

1. Enable Dark theme and Save
2. Open main screen

## Describe what you expected to happen

On iOS, the status bar is correctly displayed when the dark theme is on.

## Logfile

<details>
<summary>Screenshot</summary>

![IMG_0731](https://user-images.githubusercontent.com/19418601/76788157-6e9c9900-67cb-11ea-9f33-dfc12a9248bc.PNG)

</details>

**Comment by tessus** [comment]
Fix is already in master. Will be available in the next release.

**Comment by Rakleed** [comment]
@tessus in the newly released update (10.0.46) the problem is still relevant.

**Comment by tessus** [comment]
It's not even in the AppStore yet, so what are you talking about?

**Comment by Rakleed** [comment]
@tessus what do you mean? Yesterday I became available update to version 10.0.46, and I updated.
![image](https://user-images.githubusercontent.com/19418601/77364856-1edb4600-6d66-11ea-831e-17d2d3fde6d2.png)

**Comment by tessus** [comment]
Ok, I haven't received any updates on my iPad, so maybe they roll it out on iOS first. So when you go to the configuration screen is shows 10.0.46 at the bottom?

Well, in that case, I'll re-open the issue. As soon as I get the new version on my iPad, I'll reproduce the issue and post a screenshot.

**Comment by Rakleed** [comment]
> So when you go to the configuration screen is shows 10.0.46 at the bottom?

Yes, it is.
![image](https://user-images.githubusercontent.com/19418601/77365518-539bcd00-6d67-11ea-8849-6ea27b7a37d5.png)
