### ISSUE TITLE
In iOS, the Joplin icon has black edges

### ISSUE THREAD

**Issue by Rakleed** [laurent22/joplin#2787]
## Environment

Joplin version: 10.0.45
Platform: iOS
OS specifics: 13.3.1

## Steps to reproduce

1. Download Joplin
2. Go to the Home screen, where the Joplin icon appeared

## Describe what you expected to happen

In iOS, the Joplin icon at the edges is completely filled with blue.

## Logfile

<details>
<summary>Screenshot</summary>

![B89A2C8E-03D2-4839-89CC-D7C333DBA1E5](https://user-images.githubusercontent.com/19418601/76832907-59f7e980-683b-11ea-9677-31663ed0a8dc.png)

</details>

**Comment by Rahulm2310** [comment]
@Rakleed this issue has been previously reported -> #2604
