### ISSUE TITLE
Feature Request: Make resources editable

### ISSUE THREAD

**Issue by BengaloBongali** [laurent22/joplin#279]
### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [x] Terminal

### Intro
In some cases, creating a TXT (or RTF... for the single reason of line breaks, or MD) is still the best way to take a note. That's when it needs to be editable for everybody and/or it has to be in a specific place.
My suggestion is to create a way to include such notes in Joplin.

### Specification

[See below](https://github.com/laurent22/joplin/issues/279#issuecomment-490052513)

### How would this work?
Let's say I create the RTF on a computer without Joplin on a USB stick. Then I put the USB stick in a computer with Joplin. Then I "Open With..." it there and choose Joplin. Joplin creates a note with the file's name as a title in its local folder **and keeps the RTF's text and name in sync with it from now on**. ID could be added at the end of the RTF to recognize it if the file name changes.

Is that understandable?

**Comment by fmrtn** [comment]
Sounds like you're requesting an import feature.

Joplin can import from some file formats, see this https://github.com/laurent22/joplin#importing

**Comment by BengaloBongali** [comment]
Only if Joplin keeps the file and the imported note synchronized as in propagates changes in the created Joplin note to the imported RTF on the USB stick and vice versa. Does it?

**Comment by laurent22** [comment]
I think what would be needed is a way to make the resources editable, which is currently not supported.

**Comment by siliconninja** [comment]
Maybe a temporary directory to store files? For example, when you open the file, keep a copy of it in there temporarily (with a timestamp to differentiate it, maybe a unix millisecond timestamp), then replace the updated file. When you go back to Joplin, ask "replace the file?" or have a mark next to it indicating that it has been modified, and if you click on it, then ask that same question. If it's deleted from the note, keep the file as a backup just in case.

**Comment by laurent22** [comment]
Implementation:

- Add an "Edit" icon when hovering over a resource link or image.
- Open resource in editor and display dialog: "Attachment is being edited. Click 'Apply changes' when done." (Buttons: "Apply changes" / "Cancel")
- Once resource is saved, create a new resource and replace the old resource ID with the new one in the note.
- Need to handle case where resource is used in more than one note (Initially, maybe leave the other notes as-is, so they'll still be linked to the old resource files).

Creating a new resource every time means everything else will work the same (sync, encryption, resource indexing, etc.).

**Comment by cast-away** [comment]
not stale
