### ISSUE TITLE
Joplin terminal application 

### ISSUE THREAD

**Issue by yashwanthambati** [laurent22/joplin#2792]
## Environment

Joplin version: 1.0.161
![Screenshot 2020-03-18 at 11 57 13 AM](https://user-images.githubusercontent.com/42468133/76931893-aad91200-690f-11ea-9737-e4aace47ec71.png)

Platform: Macos
OS specifics: mojave

## Steps to reproduce

1. terminal application is not working.
2. When i type joplin is terminal,it shows internal modules not found.
3. 

## Describe what you expected to happen
Start joplin in terminal

**Comment by tessus** [comment]
Let me guess. You used brew. Check the forum. Solutions are there.

**Comment by tessus** [comment]
We are not responsible for the brew package. If you have an issue with it, please contact brew.
