### ISSUE TITLE
Shortcut keys for renaming and deleting notebooks and sub-notebooks

### ISSUE THREAD

**Issue by pranavmodx** [laurent22/joplin#2797]
## Description
Not exactly a bug but a possible enhancement. There are no shortcut keys for renaming and deleting notebooks and sub-notebooks. It would be handy if there were.

## Screenshot
![Screenshot 2020-03-18 at 11 06 37 PM](https://user-images.githubusercontent.com/42793024/76989925-27e6a480-696d-11ea-8d05-69ee2e5132ea.png)

## Environment
Joplin version: Joplin 1.0.193 (prod, darwin)
Platform: macOS Mojave

## Steps to reproduce
1. Right click on notebook/sub-notebook
2. Observe there's no shortcut keys

**Comment by tessus** [comment]
These can be disxussed during the GSoC project that is called `custom keyboard shortcuts`.

This bug tracker is for bugs only (or accepted feature requests.) This issue is neither.
