### ISSUE TITLE
iOS bright keyboard with dark mode and dark theme

### ISSUE THREAD

**Issue by kopfuss** [laurent22/joplin#2798]
## Issue

Starting with update to Joplin 10.0.45 choosing Joplin Dark Theme or OLED Dark Theme both use the bright style iOS keyboard.

## Environment

Joplin version: 10.0.45
Platform: iPhone 6
OS specifics: iOS 13.3.0

## Describe what you expected to happen

Everything as dark as possible, except text and buttons.

**Comment by laurent22** [comment]
Do other apps display a dark keyboard in dark mode? I'm on Android in dark mode but I see the keyboard is still white, but not sure about iOS

**Comment by anjulalk** [comment]
It's only supported on iOS
https://reactnative.dev/docs/textinput.html#keyboardappearance

**Comment by anjulalk** [comment]
Looks like React Native supports it, but this feature only exists in iOS.
See https://reactnative.dev/docs/textinput#keyboardappearance
