### ISSUE TITLE
No validation error on creating notebooks/sub-notebooks without title

### ISSUE THREAD

**Issue by pranavmodx** [laurent22/joplin#2799]
## Description
There is no validation error/prompt on creating notebooks/sub-notebooks without title. Instead the dialog simply closes.

## Screenshot
![Screenshot 2020-03-18 at 11 04 50 PM](https://user-images.githubusercontent.com/42793024/76991010-ebb44380-696e-11ea-8505-afafdffbfc4b.png)

## Environment
Joplin version: Joplin 1.0.193 (prod, darwin)
Platform: macOS Mojave

## Steps to reproduce
1. Create new notebook/sub-notebook without adding title
2. Observe dialog simply closes.

## Describe what you expected to happen
An error message asking user to enter a valid title (length > x)

**Comment by ishriom53tyagi** [comment]
i am working on it.

**Comment by coderrsid** [comment]
I don't think this issue is fixed. Are you still working on it?

**Comment by ishriom53tyagi** [comment]
@coderrsid  yeah i am working on it. But if you have solution than you could also try it.

**Comment by coderrsid** [comment]
Sure i'll try the steps mentors suggested in the above PR.
