### ISSUE TITLE
[Feature request] Option to disable auto-save

### ISSUE THREAD

**Issue by alexdevero** [laurent22/joplin#280]
At this moment, app automatically saves any edits after a short delay. It could be useful to have an option to disable this auto-saving.

### Operating system

- [X] Windows
- [X] macOS
- [X] Linux
- [X] Android
- [X] iOS

### Application

- [X] Desktop
- [X] Mobile
- [ ] Terminal

**Comment by laurent22** [comment]
Duplicate of #310
