### ISSUE TITLE
minor GUI optimizations

### ISSUE THREAD

**Issue by kopfuss** [laurent22/joplin#2800]
### Environment

Joplin version: 10.0.45
Platform: iPhone 6
OS specifics: iOS 13.3.0

### Describe what you expected to happen

- the pane to the note's right (created: updated: view on map) is not delimited by a fine line which in regards to consistency would fit the main menu to far left). the issue is more salient when using dark mode.

- the 'new note' button is nice red, when tapped two violet buttons appear. all three buttons in red color would be more pleasing to the eye. dark blue and red matches nicely.

- several dialog boxes (sort notes, delete confirm, notebook edit, undo-cut-copy-paste-redo-toolbox) appear bright in dark mode.

**Comment by tessus** [comment]
Please add suggestion to the forum. There's areason for the templates.
