### ISSUE TITLE
No search feature in Help Menu [mac-only]

### ISSUE THREAD

**Issue by pranavmodx** [laurent22/joplin#2804]
## Description 
Not actually a bug but a possible enhancement. There is a search feature in Help Menu (only for Mac OS) which shows you where certain menu items are present based on the search. This is currently not enabled in the desktop app.

## Screenshots
For non-Mac users,
![Screenshot 2020-03-19 at 10 05 47 AM](https://user-images.githubusercontent.com/42793024/77032069-7033b000-69c9-11ea-8666-2f3fc516b0dc.png)

For Mac users,
![Screenshot 2020-03-19 at 10 06 41 AM](https://user-images.githubusercontent.com/42793024/77032101-86417080-69c9-11ea-8a20-e7f1d123901d.png)

## Environment
Joplin version: Joplin 1.0.193 (prod, darwin)
Platform: Mac OS Mojave

## Steps to reproduce
1. Go to Help Menu (Mac device)
2. Observe no search feature 

## Solution
Explicitly add a role of 'help' to the menu

**Comment by coderrsid** [comment]
Hey @pranavmodx , it's great to see your PR. But all the enhancements must be discussed in discourse first with all the mentors. Then only it should be implemented. So, you can first try discussing it with community then implement it. Isn't it @PackElend ?

**Comment by PackElend** [comment]
> Can you guide him with more information @PackElend ?

nothing to add here, you said it all.
The feature category in the forum is the right spot to discuss this.
If there is agreement over there we can reopen it
