### ISSUE TITLE
Mobile: Pressing the back button exits the app without any alert 

### ISSUE THREAD

**Issue by Rahulm2310** [laurent22/joplin#2807]
## Environment

Joplin version: 1.0.322
Platform: Mobile

## Steps to reproduce

1. Start the app
2. Press the back button 
3. App closes instantly without any alert

![20200319_181545](https://user-images.githubusercontent.com/54268438/77071222-a9900e00-6a11-11ea-9a2f-3a2b41651963.gif)

## Describe what you expected to happen
There should be a confirmation alert to ask the user if he/she really want to quit the app.

**Comment by Rahulm2310** [comment]
@PackElend please label me

**Comment by PackElend** [comment]
> @PackElend please label me

we only label PRs

**Comment by axq** [comment]
There is a related issue in https://github.com/laurent22/joplin/issues/2327.
