### ISSUE TITLE
When in Viewer-only mode, Ctrl+Shift+B should focus the viewer panel

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2810]
Currently, the Ctrl+Shift+B shortcut is assigned to focus the note editor. However, when the current layout is viewer-only, it doesn't make sense to focus the editor. Instead it should focus the viewer panel.

**Comment by flozender** [comment]
Hi, may I try to work on this issue?

**Comment by ykabusalah** [comment]
Can I try working on this?

**Comment by flozender** [comment]
Sorry, I'm already on it.

**Comment by yourcontact** [comment]
#2979 #2999 have not fixed this.

Ctrl+Shift+B shortcut is still assigned to focus the note editor when the current layout is viewer-only.

 cc @flozender

**Comment by zomglings** [comment]
Hi @laurent22 , @yourcontact : Pushed a proposed fix for this issue - https://github.com/laurent22/joplin/pull/4537

**Comment by shrey** [comment]
@laurent22 In the editor instance, the cursor appears on Crtl+shift+B, however in the viewer instance, how would you like to see the focus on the viewer only window, perhaps an outline over the view window?
