### ISSUE TITLE
"Joplin can't be opened" error after installation via Homebrew on macOS Catalina

### ISSUE THREAD

**Issue by sealch** [laurent22/joplin#2813]
When opening downloaded and installed Joplin via Homebrew following error displays:
```"Joplin" can't be opened because Apple cannot check it for malicious software.```

![image](https://user-images.githubusercontent.com/28362310/77114587-6e9fd180-6a35-11ea-8081-cc8d495ec419.png)

## Environment

Joplin version: v1.0.194
Platform: macOS
OS specifics: 10.15 (19A583)

## Steps to reproduce

1. ```brew update```
2. ```brew cask install joplin```
3. Open Joplin app

## Describe what you expected to happen
The app was expected to open and run

## Logfile

```/joplin-desktop``` folder in ```~/.config``` was not created

**Comment by rabeehrz** [comment]
Try right clicking and opening

**Comment by laurent22** [comment]
dup
