### ISSUE TITLE
Markdown Editor Chinese punctuation is not supported, the format is garbled

### ISSUE THREAD

**Issue by louisiy** [laurent22/joplin#2814]
## Environment

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1. 
2. 
3. 

## Describe what you expected to happen
Editor Chinese punctuation is not supported, the format is garbled

**Comment by sinkuu** [comment]
Duplication of https://github.com/laurent22/joplin/issues/2674.
