### ISSUE TITLE
[Request] Features: Start Page view / Most Recent view

### ISSUE THREAD

**Issue by lazylionca** [laurent22/joplin#282]
Hi ya

Three suggestions:

1. I'd love to be able to set a start view for when the app first opens. Say a particular tag or notebook.

2. A "most recent" view that shows the last notes edited sorted by date.

3. Sort notebooks by name or last edited. Also sort Notes in a Notebook.

Thanks all, keep up the great work.

**Comment by laurent22** [comment]
Also as suggested by @foxmask - "On the welcome page, may be it could be useful to list the reminders to come and those ones that are already passed but still not checked"

**Comment by ftastisch** [comment]
In my previous to-do app had the following options, which I found to be very helpful:
- today
- tomorrow
- current week
- all open to-dos

Just as an idea.

**Comment by blazerunner80** [comment]
I'd like to see all notes/tasks of the current selected notebook including all subnotebooks.
[Detailed description](https://discourse.joplin.cozic.net/t/see-to-dos-of-subnotebooks-in-parent-notebook/306/3?u=blazerunner80)
