### ISSUE TITLE
Invalid SSL certificate on requested API url (broken HTTPS)

### ISSUE THREAD

**Issue by sealch** [laurent22/joplin#2822]
I was looking at outgoing app requests and saw that it was trying to connect to github API at some IP address at HTTPS port (443). 

<img width="489" alt="Screenshot 2020-03-19 at 23 35 13" src="https://user-images.githubusercontent.com/28362310/77117250-49fa2880-6a3a-11ea-829a-64e597719c8c.png">

When I went to this IP (`https://140.82.118.6`) in my browser I saw that it has invalid certificate, HTTPS connection is broken and all requests are processed with HTTP.

<img width="521" alt="Screenshot 2020-03-19 at 23 37 04" src="https://user-images.githubusercontent.com/28362310/77117364-8cbc0080-6a3a-11ea-83eb-5eccb8f3feab.png">

Github says their API is 100% healthy and working now, so there could be a problem in request.

## Environment

Joplin version: v1.0.194
Platform: macOS
OS specifics: 10.15 (19A583)

## Steps to reproduce

1. Open Joplin app
2. Monitor outgoing requests
3. See request to GitHub API
4. Proceed to requested IP

## Describe what you expected to happen
HTTPS connection and valid SSL certificate

**Comment by tessus** [comment]
I can't reproduce this issue. Maybe your network uses a transparent proxy or you hit MITM scenario.

Btew this is the check for a new release and can be triggered by the `Check for updates...` menu item.

**Comment by sealch** [comment]
> I can't reproduce this issue. Maybe your network uses a transparent proxy or you hit MITM scenario.
> 
> Btew this is the check for a new release and can be triggered by the `Check for updates...` menu item.

Have you tried accessing requested ip (https://140.82.118.6) directly from your browser? It still has invalid certificate in my case

**Comment by tessus** [comment]
Of course it is invalid, because the `CN` is for `*.github.com`. We are not acessing `140.82.118.6`, but `api.github.com`.

**Comment by tessus** [comment]
Every web site has an invalid certificarte when you access it via its IP address.
