### ISSUE TITLE
Desktop: Upper border of selected icon outline is not inline with gray menu border

### ISSUE THREAD

**Issue by sealch** [laurent22/joplin#2824]
When hovering over any icon in app, outline is few pixels higher than it should be

<img width="507" alt="Screenshot 2020-03-21 at 00 01 15" src="https://user-images.githubusercontent.com/28362310/77209513-1802c800-6b07-11ea-865b-11c2c67bf98a.png">

![image](https://user-images.githubusercontent.com/28362310/77209595-4a142a00-6b07-11ea-84af-de4b3f09ed79.png)

## Environment

Joplin version: v1.0.194
Platform: macOS
OS specifics: 10.15

## Steps to reproduce

1. Open Joplin app
2. Hover over any icon

## Describe what you expected to happen
Icon outline was expected to be inline with gray border

**Comment by Rishgod** [comment]
Um I'm on windows and I don't have the same problem

![Screenshot (1)](https://user-images.githubusercontent.com/54576074/77215911-dab92d00-6b3c-11ea-8328-fab20f8fbdf2.png)

**Comment by Rahulm2310** [comment]
Yeah, it is perfect on Windows.May be something specific to Mac.

**Comment by rabeehrz** [comment]
I can confirm this behavior on Mac.

**Comment by coderrsid** [comment]
Yes, it's over the button size on top on my mac. I'll look into this issue.

![image](https://user-images.githubusercontent.com/35633575/77228239-ed1e7f80-6bab-11ea-9b73-67ad722ba0e8.png)
