### ISSUE TITLE
Picture is not shown in the "Viewer Mode", if I start wit joplin with "--profile <path>"

### ISSUE THREAD

**Issue by RrobertRr** [laurent22/joplin#2826]
If I start Joplin with the parameter "--profile <my_path>", I can't see pictures in the "Viewer Mode". Look the screenshot:
This problem is for every Picture in the hole profile. If I open the file markdown editor with the red marked Icon (see picture), I can see the picture in the other MarkDown editor I used. But only here not.
![image](https://user-images.githubusercontent.com/25011725/77223474-401d1600-6b5d-11ea-91f7-add83fa6e544.png)

If I start joplin.exe **without** any parameter, it will start Joplin with the default profile and in this profile, I can see every picture.

## Environment
![image](https://user-images.githubusercontent.com/25011725/77223517-9c803580-6b5d-11ea-9462-01fbf9cdb598.png)

**Comment by RrobertRr** [comment]
I testet this on another pc. There is the same failure.

**Comment by RrobertRr** [comment]
I tested it also with the portable version.
And there is the same failure.

But I found out, that this failure is only if I start the portable version on my "D:" drive.
On my "C:" drive I can run the portable version without this failure.

**Comment by sgflux** [comment]
I have the problem with my "#Apps" folder, where I store my portable apps. Without the number sign "#" the pictures are visible in the "Viewer Mode".
