### ISSUE TITLE
Desktop: To-do in the list in not filled with blue completely on hover

### ISSUE THREAD

**Issue by sealch** [laurent22/joplin#2830]
When hovering over to-do item in the list it is not selected (filled with blue) completely

![Screen Recording 2020-03-21 at 18 37 06](https://user-images.githubusercontent.com/28362310/77231378-27cfea00-6ba3-11ea-9a8c-ec155f43b065.gif)

## Environment

Joplin version: v1.0.194
Platform: macOS
OS specifics: 10.15

## Steps to reproduce

1. Open Joplin app
2. Create new to-do if there are no existing
3. Hover cursor over to-do

## Describe what you expected to happen
To-do was expected to be filled with blue completely

**Comment by Rahulm2310** [comment]
I will fix this.

**Comment by Rahulm2310** [comment]
@coderrsid  When I said I will fix it, you could have picked some other issue. We all are here to contribute.

**Comment by coderrsid** [comment]
@Rahulm2310 Didn't see your comment earlier. Although it was an easy fix. So did it.
