### ISSUE TITLE
Desktop: When the query in the search bar is not present in the note body, the blank grey screen appears

### ISSUE THREAD

**Issue by Rahulm2310** [laurent22/joplin#2835]
## Environment

Joplin version: 1.0.194
Platform: Windows

## Steps to reproduce

1. Search a string which is not present in the note body 
2. Blank grey screen appears same as which appears when no notes exist.

-> When the query matches 
![Error-1](https://user-images.githubusercontent.com/54268438/77245297-851b7800-6c43-11ea-9d3a-ab1b47ad84af.JPG)

->When the query doesn't matches
![Error-2](https://user-images.githubusercontent.com/54268438/77245306-949ac100-6c43-11ea-8b43-506eb86e943d.JPG)

## Describe what you expected to happen
The editor should remain present with no matching text highlights in the view pane.

**Comment by mic704b** [comment]
I'm not sure what you describe is a bug. There is no matching note to show or edit.  At worst, the message in the note list could be more relevant.
