### ISSUE TITLE
Feature Request - note as reminder

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#284]
Hi,
First of all many thanks for the project, I could import my 2500 Evernote notes (for 700mo) in 10 minutes :)

### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

Could it be possible to add note as reminder ? (by pressing a watch icon to set a date and hour for example) 

edit : I just saw that the desktop app already owns that feature, but not the android one.

**Comment by laurent22** [comment]
There's also a reminder feature in the mobile app (under the top right menu -> Set alarm). It is only available for to-dos (not for regular notes).

**Comment by foxmask** [comment]
yes thanks !
