### ISSUE TITLE
Inconsistient Toggle Feature

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [laurent22/joplin#2842]
#### Description

The current toggle functionality is really inconsistent

#### Current Behavior

![TOGGLE](https://user-images.githubusercontent.com/54576074/77249661-be1a1380-6c68-11ea-84fb-a5dc51605c46.gif)

#### Desired Behaviour

![TOGGLE-desired](https://user-images.githubusercontent.com/54576074/77249664-c07c6d80-6c68-11ea-8626-1b9406c0cd76.gif)

**Comment by tessus** [comment]
Some of the PRs are not merged yet, one of which is yours. So I'm not sure why you opened this issue.

**Comment by Rishgod** [comment]
> Some of the PRs are not merged yet, one of which is yours. So I'm not sure why you opened this issue.
😞 I was just pointing it out

**Comment by tessus** [comment]
Ah, so we don't have issues enough? I mean we know about it, that's why there's a PR open.

**Comment by Rishgod** [comment]
> Ah, so we don't have issues enough? I mean we know about it, that's why there's a PR open.

No @tessus I guess you misunderstood me, this bug is different from the open PR's(_I checked_) 
It's about toggling text.

**Comment by tessus** [comment]
I'm seriously confused. You also had a PR open that changed the toggle behavior. Or am I wrong? Or was that somebody else?

Anyway, I'd rather have a follow-up PR, referencing the one related to it, instead of a new issue, but ok. Let's keep this open.

**Comment by Rishgod** [comment]
> I'm seriously confused. You also had a PR open that changed the toggle behavior. Or am I wrong? Or was that somebody else?
> 
> Anyway, I'd rather have a follow-up PR, referencing the one related to it, instead of a new issue, but ok. Let's keep this open.

No that wasn't me, it was this issue #2560

**Comment by Rishgod** [comment]
@tessus , I have fixed this bug locally but there is an open PR #2737 , this use component introduced in that PR, so should I close that PR, and open a new one with both the changes?
or wait for the earlier to get merged. 


![toggler](https://user-images.githubusercontent.com/54576074/77486267-452bdf00-6e55-11ea-8604-60c7ba9eed26.gif)

**Comment by tessus** [comment]
I don't know, since I can't merge any PRs which are not related to translations or documentation.

**Comment by Rishgod** [comment]
> I don't know, since I can't merge any PRs which are not related to translations or documentation.

I was just hoping that it would be great if you can review it so it can be fast-tracked on getting merged, so I can make another PR closing this bug, its totally fine if you don't have the time right now and are occupied.
