### ISSUE TITLE
Mobile: Text and Buttons are overlapping in dropbox sync screen

### ISSUE THREAD

**Issue by ishantgupta777** [laurent22/joplin#2843]
## Environment

Joplin version: 1.0.322
Platform: Mobile
OS specifics: No

## Steps to reproduce

1.  Go to the sync screen of dropbox on mobile. 
![Screenshot_1584880562](https://user-images.githubusercontent.com/27751740/77249719-3680d480-6c69-11ea-83f5-e65e6f04c84a.png)

I tested and this is the case only when we don't have any notes. I will see if there any other case and will fix it.
I would like to work on this issue.

**Comment by Rahulm2310** [comment]
Yes it happens with me sometimes

**Comment by ishantgupta777** [comment]
> Yes it happens with me sometimes

I found the issue, almost fixed it. Its because there is no condition check-in note list component for the dropbox sync page. The overlapping text was from the note list component when there are no notes.
