### ISSUE TITLE
Desktop: Problem with app responsiveness when reducing window size

### ISSUE THREAD

**Issue by sealch** [laurent22/joplin#2848]
App interface is not responsive on smaller widow sizes.

![Screen Recording 2020-03-22 at 17 53 10](https://user-images.githubusercontent.com/28362310/77253957-9aee6480-6c66-11ea-9c93-25dbb5039777.gif)

## Environment

Joplin version: v1.0.194
Platform: macOS
OS specifics: 10.15 

## Steps to reproduce

1. Open Joplin app
2. Start reducing window size horizontally

## Describe what you expected to happen
App was expected to have responsive interface

**Comment by anjulalk** [comment]
Please fetch the latest commits. The menu interface should not wrap. It has been fixed.
Other than that, are you suggesting that the sidebar and note list should be collapsed?

**Comment by sealch** [comment]
> Please fetch the latest commits. The menu interface should not wrap. It has been fixed.
> Other than that, are you suggesting that the sidebar and note list should be collapsed?

This is latest version of the app. Yes, probably sidebar should collapse, so most important UI elements and content are still visible.

**Comment by Rahulm2310** [comment]
Working on this !

**Comment by laurent22** [comment]
Working as designed.
