### ISSUE TITLE
IOS: Switching colour theme does not work properly

### ISSUE THREAD

**Issue by sealch** [laurent22/joplin#2853]
When switching the colour theme from light to Dark or OLED Dark it does not switch completely.

![RPReplay_Final1584903811](https://user-images.githubusercontent.com/28362310/77258230-ebbf8680-6c81-11ea-87da-1452e87b42cf.gif)

## Environment

Joplin version: 10.0.45
Platform: IOS
OS specifics: 13.3.1

## Steps to reproduce

1. Open Joplin app
2. Go to configuration
3. Switch colour theme to Dark or OLED Dark

## Describe what you expected to happen
Colour theme was expected to switch completely.

**Comment by ishantgupta777** [comment]
Bro, it's working properly, did you merge latest commits.

**Comment by rabeehrz** [comment]
#2781 
Saw this after linking the PR.

**Comment by bravosierramike** [comment]
Why is this "dark theme bug" closed? Will this be fixed in the next version (using now 10.0.47)?
