### ISSUE TITLE
IOS: Note history slider lags and changes its length

### ISSUE THREAD

**Issue by sealch** [laurent22/joplin#2854]
![RPReplay_Final1584904720 3](https://user-images.githubusercontent.com/28362310/77258681-e7e13380-6c84-11ea-919c-b5612fd4e1f0.gif)

Length comparison using the Photoshop ruler tool:

- minimum length:

![image](https://user-images.githubusercontent.com/28362310/77258746-51f9d880-6c85-11ea-89d7-2160132e0354.png)

- maximum length:

![image](https://user-images.githubusercontent.com/28362310/77258738-43abbc80-6c85-11ea-87e8-c0b832d47a6a.png)

## Environment

Joplin version: 10.0.45
Platform: IOS
OS specifics: 13.3.1

## Steps to reproduce

1. Open Joplin app
2. Go to Configuration
3. Start changing note history slider

## Describe what you expected to happen
No lag while toggling slider and constant length

**Comment by Rahulm2310** [comment]
I am working on this
