### ISSUE TITLE
Code blocks in OLED dark theme

### ISSUE THREAD

**Issue by shbach** [laurent22/joplin#2859]
When using OLED dark theme, code block does not have different background color or syntax highlighting. Inline code works though:
![image](https://user-images.githubusercontent.com/5298745/77274671-b318b080-6c73-11ea-9f49-f817d5504057.png)

Example in regular dark theme:
![image](https://user-images.githubusercontent.com/5298745/77274437-27068900-6c73-11ea-907c-0a477352af6c.png)

Joplin version: 1.0.323
Platform: Android

**Comment by ishantgupta777** [comment]
I will take that issue and will fix that.

**Comment by ishantgupta777** [comment]
Can you please tell me what version are you using and if the latest version, then what markdown syntax are you using. Because it's working fine for me with a code block.

**Comment by shbach** [comment]
> Can you please tell me what version are you using and if the latest version, then what markdown syntax are you using. Because it's working fine for me with a code block.

I just updated from version 1.0.323 to  1.0.324 and the issue is still occurring. Here is a picture of the markdown syntax: 
![Screenshot_20200323-093457__01](https://user-images.githubusercontent.com/5298745/77339959-d41be880-6ce9-11ea-9cdf-9ecff852bb7c.jpg)

**Comment by ishantgupta777** [comment]
> > Can you please tell me what version are you using and if the latest version, then what markdown syntax are you using. Because it's working fine for me with a code block.
> 
> I just updated from version 1.0.323 to 1.0.324 and the issue is still occurring. Here is a picture of the markdown syntax:
> ![Screenshot_20200323-093457__01](https://user-images.githubusercontent.com/5298745/77339959-d41be880-6ce9-11ea-9cdf-9ecff852bb7c.jpg)

Thanks. I will try it and fix it.

**Comment by ishantgupta777** [comment]
Sir, I fixed it.

**Comment by shbach** [comment]
Great work, thanks!
