### ISSUE TITLE
Feature Request - add the folder name to the note render

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#286]
Hi,

### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [x] Android
- [ ] iOS

### Application

- [x] Desktop
- [x] Mobile
- [ ] Terminal

When I click on a folder, I have the list of note and then I can open a note by knowing from which folder I came.

When I make a search of the desktop app, and open a note, I don't know from which folder I came

Could you add the folder name to the render of the note somewhere near the tag button ?

**Comment by laurent22** [comment]
This was done in a recent pull request.
