### ISSUE TITLE
[Desktop] Markdown rendering not working

### ISSUE THREAD

**Issue by anihm136** [laurent22/joplin#2860]
## Environment

Joplin version: 1.0.195
Platform: Linux Desktop
OS specifics: Ubuntu 19.10

## Steps to reproduce

1. Create a note
2. Switch to split view / viewer mode
3. Nothing is rendered, errors shown in developer console

Can someone verify if this is reproducible? This is observed on the latest master. It was last working for me on commit 6027725fae63fff905c21892fb64e38f74c5adc4

## Logfile

```
Uncaught (in promise) TypeError: Cannot read property 'install' of undefined
    at MdToHtml.render (/home/anirudh/Projects/forks/joplin/ElectronClient/lib/joplin-renderer/MdToHtml.js:286)
    at MarkupToHtml.render (/home/anirudh/Projects/forks/joplin/ElectronClient/lib/joplin-renderer/MarkupToHtml.js:37)
    at NoteTextComponent.updateHtml (/home/anirudh/Projects/forks/joplin/ElectronClient/gui/NoteText.min.js:1078)
    at processTicksAndRejections (internal/process/task_queues.js:85)
```

**Comment by anihm136** [comment]
Ah, that was the issue. I hadn't needed to run it before, so it did not occur to me. Thanks!

**Comment by coderrsid** [comment]
I am still having this issue on macOS

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35633575/77436532-9ada9a00-6e09-11ea-989f-0d305402edfc.png">

**Comment by laurent22** [comment]
@coderrsid, if I may make a suggestion. When you don't need to explicitly notify someone, as in this case, please use the name without `@`. As in "as laurent22 said". Otherwise you're sending emails to specific people, even though anybody can potentially answer your question. In fact, I keep getting notifications from you because you have a tendency to do that, so just remove the `@` please.

**Comment by coderrsid** [comment]
Sure laurent, as you say! But please do suggest a solution.

**Comment by coderrsid** [comment]
@anihm136  how did you solve this?

**Comment by coderrsid** [comment]
Solved it by running the command `npm run build` in the root folder of joplin.

**Comment by anihm136** [comment]
@coderrsid yeah, that was the thing. If I'm right, that command needs to be run whenever the typescript components are updated

**Comment by coderrsid** [comment]
Exactly!
