### ISSUE TITLE
删除笔记不会删除资源文件

### ISSUE THREAD

**Issue by GwkangDev** [laurent22/joplin#2862]
## Environment

Joplin version:  Last Release
Platform: Windwos
OS specifics: Windows 10

## Steps to reproduce

1.  创建一个笔记
2.  往里面插入一张图片
3.  删除笔记
4.  图片没有被删除，还存在本地

## Describe what you expected to happen
笔记中的图片一起删除

**Comment by Rahulm2310** [comment]
@GwkangDev Could you please provide translation to English

**Comment by ishantgupta777** [comment]
> @GwkangDev Could you please provide translation to English

Bro, you can select text and translate it. He's saying in windows 10 if we add an image to a note and then delete the note, the image is still there locally.

**Comment by GwkangDev** [comment]
> @GwkangDev Could you please provide translation to English

https://github.com/laurent22/joplin/issues/2862#issuecomment-602474469

**Comment by GwkangDev** [comment]
> > @GwkangDev Could you please provide translation to English
> 
> Bro, you can select text and translate it. He's saying in windows 10 if we add an image to a note and then delete the note, the image is still there locally.

thanks

**Comment by laurent22** [comment]
This is normal, the image gets deleted after a while.
