### ISSUE TITLE
Side bar not resizable when "Toggle Note list" is not selected (edited)

### ISSUE THREAD

**Issue by techguybiswa** [laurent22/joplin#2865]
## DESCRIPTION ##  

**The Side Bar is not draggable in desktop when "Toggle Note List" is not selected**

<img src="https://i.ibb.co/nntTs1V/Screenshot-2020-03-23-at-2-45-35-PM.png" />

## Environment

Joplin version: Joplin 1.0.195 (prod, darwin)
Platform: Desktop 
OS specifics: macOS MOJAVE 10.14 , Win10 Pro x64 ,  Linux Mint 19.3 x64

**EDIT**
Actually the issue of not being able to resize the sidebar appears specifically when the "Toggle Note List" is not selected.

## Steps to reproduce (edited)

1. Open Joplin desktop app.
2. Create a few Notebooks
3. Make sure "Toggle Note List" is turned off.
4. Try resizing the sidebar.

## Describe what you expected to happen

1. The sidebar should be resizable on drag even when "Toggle Note List" is not selected.

**Comment by dpoulton-github** [comment]
> Or the width of the sidebar should be draggable

That seems odd because on both the Windows and Linux platforms it **is** draggable.

**Comment by techguybiswa** [comment]
Yeah, but in the environment, I mentioned the issue persists.
I restarted the app but even then I cannot get any option to drag it.

**Comment by coderrsid** [comment]
>Or the width of the sidebar should be draggable

It is scrollable on macOS. I can confirm that but it is indeed behaving weirdly. You can see below in the GIF.

![Screen-Recording-2020-03-23-at-1](https://user-images.githubusercontent.com/35633575/77345851-36610180-6d5b-11ea-9cf6-00a617df1e37.gif)

**Comment by techguybiswa** [comment]
@coderrsid  please click on the "Toggle Node List" and then try resizing it.
Check my screen recording at: https://gifyu.com/image/dxir

**Comment by coderrsid** [comment]
Yes, that's an issue there. Please mention it too in the description of issue.

**Comment by techguybiswa** [comment]
Yes, actually in my case the "Toggle Note LIst" was unselected by default and hence I could not figure out when it is working and when it is not. 
Now that I understand it, I am updating the issue.
Thanks @coderrsid  for pointing it out.

**Comment by coderrsid** [comment]
Are you willing to fix the issue too? because i can look into the fix too.

**Comment by techguybiswa** [comment]
@dpoulton-github can you please try in your Linux and windows environment to unselect "Toggle Note List" and then try to drag and see if it works or not?

**Comment by coderrsid** [comment]
I have a macbook, sorry can't test that.

**Comment by techguybiswa** [comment]
> Are you willing to fix the issue too? because i can look into the fix too.

Yeah sure go ahead and try to fix it. I am currently having some issues with running Joplin from the  source code.  (https://discourse.joplinapp.org/t/npm-start-throws-uncaught-error/7267/7)

**Comment by dpoulton-github** [comment]
> @dpoulton-github can you please try in your Linux and windows environment to unselect "Toggle Note List" and then try to drag and see if it works or not?

Tried on Win10 Pro x64 and Linux Mint 19.3 x64 and toggling the note list off **prevents** the sidebar from being adjusted.

**Comment by techguybiswa** [comment]
> > @dpoulton-github can you please try in your Linux and windows environment to unselect "Toggle Note List" and then try to drag and see if it works or not?
> 
> Joplin Desktop 1.0.195 - Tried on Win10 Pro x64 and Linux Mint 19.3 x64 and toggling the note list off **prevents** the sidebar from being adjusted.

Thanks for the update. 
I am editing the issue accordingly.

**Comment by techguybiswa** [comment]
> Yes, that's an issue there. Please mention it too in the description of issue.

Hi, I have updated the issue. Seems like the entire description and the title had to be edited.
Let me know if you have any more edits to suggest.

**Comment by anihm136** [comment]
@coderrsid Are you working on this? If not, I'd like to try it

**Comment by coderrsid** [comment]
I am working on some other issue. But i looked into it, the draggable property of sidebar is true all the time though. I didn't try to go deeper. You can go for it
