### ISSUE TITLE
Mobile : Newlines are not rendered in the view mode

### ISSUE THREAD

**Issue by Rahulm2310** [laurent22/joplin#2866]
## Environment

Joplin version: 1.0.323
Platform: Mobile

## Steps to reproduce

1. Open a note
2. Add newlines anywhere in the note body 
3. Go back in the view mode. The newlines are not rendered.

![20200321_143031](https://user-images.githubusercontent.com/54268438/77304583-a9965380-6d1a-11ea-9f96-cf2bc9e175cd.gif)

## Describe what you expected to happen
Newlines should be rendered in the view mode.

**Comment by ishantgupta777** [comment]
Working perfectly fine for me bro, are you using the latest branch?

**Comment by Rahulm2310** [comment]
Yes, it persists

**Comment by ishantgupta777** [comment]
> Yes, it persists
Oh, I am sorry my bad, I thought you are talking about any text entered not only empty line. But is this bug or not, that's debatable, but yeah go ahead. This issue is there I just tested.

**Comment by Rahulm2310** [comment]
@laurent22 Sir what are your views on this ?

**Comment by laurent22** [comment]
It works as expected

**Comment by Rahulm2310** [comment]
What if user wants to add new lines intentionally? It should work like other note taking apps such as Evernote where newlines are rendered in view mode.
