### ISSUE TITLE
Uncomplete French translation

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#287]
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

the sub menus of the menu "Affichage"  are not translated

![sans titre](https://user-images.githubusercontent.com/208212/37286320-e0077ac8-2601-11e8-98d7-394f98de8679.png)

**Comment by laurent22** [comment]
If I'm not mistaken that should be translated in the next version.

**Comment by foxmask** [comment]
The popup to set the alarm is in English. The date format is in the form MM/DD
