### ISSUE TITLE
Mobile: If the title of the notebook is too big, the note-list screen misbehaves.

### ISSUE THREAD

**Issue by ishantgupta777** [laurent22/joplin#2875]
On mobile, When I use too big a title for notebooks or paste a very big text by mistake, I see this screen and there is no button to go back and delete it. Even when the app restarts, this screen is there. So, there should be a limit to the title of the notebook.

![Screenshot_1584988959](https://user-images.githubusercontent.com/27751740/77352020-8b554580-6d64-11ea-8007-b1d7cee960f7.png)

**Comment by Kenki3** [comment]
Thanks for this tip, I believe I can get into everything as I am sitting in my [property in Spain ](url=https://tranio.com/spain/)on quarantine and want to use my time effectively.
