### ISSUE TITLE
TOC not updated & functionality lost in WYSIWYG editor

### ISSUE THREAD

**Issue by armaccloud** [laurent22/joplin#2884]
When opening a TOC-containing note within the WYSIWYG editor, the TOC functionality is lost.

## Environment

Joplin version: 1.0.195
Platform: Manjaro Gnome Stable

## Steps to reproduce

1. Open a not, containing a TOC in the WYSIWYG editor
2. Add a new header to the note
3. Verify the header is not updated into the TOC
4. Switch layout to markdown
5. Verify the [TOC] is not present anymore, but instead a bullet list replaced it

## Describe what you expected to happen
The TOC functionality to stay intact

>A word of appreciation; I have waited for the WYSIWY functionality for a while and now very happy to see that it arrived. Great job!

**Comment by laurent22** [comment]
Yes it's a know bug
