### ISSUE TITLE
Editor removes embedded html 

### ISSUE THREAD

**Issue by sciurius** [laurent22/joplin#2886]
The new WYSIWYG editor, introduced in 1.0.195, removes embedded html from the document.
This includes html that is generally considered part of the markdown specification, like <sup> and <sub>.

To reproduce:

Create a note with the classic editor, insert `foo<sup>bar</sup>`.
Switch to preview: it shows "bar" as superscript.
Switch to WYSIWYG editor: it shows "bar" as superscript.
Switch to classic editor: it shows `foo<sup>bar</sup>`
Switch to WYSIWYG editor _and modify something_.
Switch to classic editor: it shows `foobar`. The HTML is lost.

**Comment by anihm136** [comment]
I am able to reproduce this. It seems to be an issue with the html-to-markdown parser, which is removing the  `<sup>` tag

**Comment by laurent22** [comment]
There's no need to open bugs for this editor for now because it's still beta.

**Comment by sciurius** [comment]
Isn't it closed already?
