### ISSUE TITLE
katex produces two lines of mathematical formulas

### ISSUE THREAD

**Issue by Eloco** [laurent22/joplin#2889]
## Environment

Joplin version: 1.0.195
Platform: Windows
OS specifics: win10

## Steps to reproduce

1. Enter $ a + b = c $ 

## Describe what you expected to happen
It should output one line (katex), but it outputs two lines repeatedly, which is the same in ios, but the android client does not have this problem.

## Screenshot
![Joplin_Eeb7ET7Jva](https://user-images.githubusercontent.com/22910374/77421229-66b1aa00-6e06-11ea-97b6-f4f41079faac.png)

**Comment by laurent22** [comment]
That will be fixed in next release
