### ISSUE TITLE
IPAD client cannot perform webdav synchronization

### ISSUE THREAD

**Issue by Eloco** [laurent22/joplin#2890]
## Environment

Joplin version: latest(app store)
Platform: IOS
OS specifics: IpadOS

## Steps to reproduce

1. All notes can be synced when just installed
2. Then modify existing notes in PC Client and sync
3. My Android client can display changes after syncing, but my IPAD cannot display changes after syncing, and the same after restarting.
4. There is also a problem in the reverse. After modification in the iPad, a conflict folder will be displayed after synchronization.

**Comment by bimac** [comment]
I seem to have the same issue with my iPhone.

Sync status on both Linux and Windows Clients:

> **Attachments**
> Not downloaded: 0
> Downloading: 0
> Downloaded and decrypted: 54
> Downloaded and encrypted: 0
> Error: 0
>
> **Sync status (synced items / total items)**
> Note: 50/50
> Folder: 9/9
> Resource: 57/57
> Tag: 0/0
> NoteTag: 0/0
> MasterKey: 1/1
> Revision: 83/83
> Total: 200/200
>  
> Conflicted: 0
> To delete: 0

On iOS:

> **Attachments**
> Not downloaded: 3
> Downloading: 0
> Downloaded and decrypted: 0
> Downloaded and encrypted: 0
> Error: 0
>
> **Sync status (synced items / total items)**
> Note: 35/30
> Folder: 4/4
> Resource: 14/14
> Tag: 0/0
> NoteTag: 0/0
> MasterKey: 1/1
> Revision: 23/77
> Total: 77/126
>  
> Conflicted: 0
> To delete: 0
