### ISSUE TITLE
Mobile: The slider & buttons on the config page does not look good in OLED theme.

### ISSUE THREAD

**Issue by Rahulm2310** [laurent22/joplin#2891]
## Environment

Joplin version: 1.0.322
Platform: Mobile 
OS : Android

Light Theme:
![img-1](https://user-images.githubusercontent.com/54268438/77423656-b9369a80-6df5-11ea-812d-03fbcac051a8.JPG)

![img-2](https://user-images.githubusercontent.com/54268438/77423661-bcca2180-6df5-11ea-82ee-5848228b67ee.JPG)

OLED Theme:
![img-3](https://user-images.githubusercontent.com/54268438/77423680-c489c600-6df5-11ea-8a38-28080e7d484a.JPG)

![img-4](https://user-images.githubusercontent.com/54268438/77423682-c6538980-6df5-11ea-8281-333175b202f5.JPG)

## Describe what you expected to happen
They should be visible properly.

**Comment by ishantgupta777** [comment]
Bro, are you working on this issue? Or can I solve this?

**Comment by Rahulm2310** [comment]
>Bro, are you working on this issue?
Yeah

**Comment by ishantgupta777** [comment]
Go ahead bro, tell me if you need help.
