### ISSUE TITLE
Issue with HTML to Markdown conversion

### ISSUE THREAD

**Issue by anihm136** [laurent22/joplin#2892]
## Environment

Joplin version: 1.0.195
Platform: Linux Dsktop
OS specifics: Ubuntu 19.10

## Steps to reproduce

1. Add a checkbox in html (using `joplin-checklist` class on the list)
2. Rendered output has a regular list item instead of a checkbox

## Describe what you expected to happen
List should render into a checklist

The issue seems to be with the `joplin-turndown` package. Although I noticed there was an update 4 days ago to solve this issue, it still seems to fail. This is also causing the related tests to fail.

Here's a screenshot showing the issue (HTML list taken from the test case):
![html2mderror](https://user-images.githubusercontent.com/49116134/77423748-e6834880-6df5-11ea-9fc8-37f0b82e2bd6.png)

**Comment by laurent22** [comment]
not a bug

**Comment by anihm136** [comment]
Then is the test case wrong and should it be removed? Because it is failing on this case
