### ISSUE TITLE
Android: Bold text is black color in dark and oled dark themes

### ISSUE THREAD

**Issue by shbach** [laurent22/joplin#2900]
Both the dark theme and oled dark themes on android are showing bold text in a black color when in view mode. This is particularly bad in oled dark as the text becomes invisible. 

![image](https://user-images.githubusercontent.com/5298745/77523516-160c7200-6e43-11ea-96f7-1274b7effa8d.png)

![image](https://user-images.githubusercontent.com/5298745/77523465-02f9a200-6e43-11ea-9390-a4fc5444a105.png)

![image](https://user-images.githubusercontent.com/5298745/77523577-31777d00-6e43-11ea-94e4-39ff6a10f2ee.png)

![image](https://user-images.githubusercontent.com/5298745/77523648-47853d80-6e43-11ea-80bf-dda0658b4e8b.png)

## Environment

Joplin version: 1.0.324
Platform: Android

**Comment by Rahulm2310** [comment]
I am fixing this.

**Comment by ishantgupta777** [comment]
> I am fixing this.

Bro, I was already working on this. Please choose any other issue.
