### ISSUE TITLE
Desktop: Electron client fails to start up.

### ISSUE THREAD

**Issue by flozender** [laurent22/joplin#2903]
## Environment

Joplin version: v1.0.195 (latest)
Platform: Desktop
OS specifics: Windows 10

## Steps to reproduce

1. Fresh clone of the Joplin repo
2. run npm install on root dir
3. cd ./ElectronClient/ and run npm start

The desktop client fails to open after the latest release update. 
![Screenshot (48)](https://user-images.githubusercontent.com/40818234/77540831-ccb33580-6ec9-11ea-9d57-fe1f60105c52.png)

## Describe what you expected to happen
Electron app should start up normally.

## Logfile

https://pastebin.com/Z08xB7QH

**Comment by laurent22** [comment]
not a bug

**Comment by flozender** [comment]
How can I get the app to run then, I was able to get it running following the same procedure earlier. Sorry for bothering you.
