### ISSUE TITLE
Empty backticks causing crash

### ISSUE THREAD

**Issue by false-mirror** [laurent22/joplin#291]
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [x] Android
- [ ] iOS

### Application

- [x] Desktop
- [x] Mobile
- [ ] Terminal

Adding the following to any note causes a crash:
```
`  `
```
Window remains open with no UI. After closing and reopening everything is fine, and the above does not include the second backtick.

Update: Tested to confirm the same bug on Android

**Comment by jcgerhard** [comment]
Confirm that issue on macOS and iOS. App crashes on desktop and mobile!
