### ISSUE TITLE
 could not work after upgrade install by brew  while by clicks works fine

### ISSUE THREAD

**Issue by lightnoway** [laurent22/joplin#2911]
could not work after second install by brew; 
   the first install is double click dmg file  at version 1.0.193
   the second install is by brew  at version 1.0.195
the report is "old version config blabla" sorry without screenshot

## Environment

Joplin version: 1.0.195
Platform: macOS 10.15.2 (19C57)
OS specifics:  MacBook Pro (Retina, 15-inch, Late 2013)

## Steps to reproduce

1. install by click dmg file ,drag app to Application folder. app version is 1.0.193
2. install by brew `brew cask install joplin`
3. the install in 2 is done; open the app ,show "old version config blabla ...", the menu is none by "quit",the window is just white
4. when 3 ,i try reinstall as below. The result is all same as in 3
   `brew cask reinstall joplin`
   `brew cask uninstall joplin`
5. At last i give install by brew , just install 1.0.195 by 1. everything is right

**Comment by laurent22** [comment]
Needs to be reported on Homebrew repo
