### ISSUE TITLE
Android: syntax highlighting missing in edit mode

### ISSUE THREAD

**Issue by shbach** [laurent22/joplin#2912]
Syntax highlighting is not present in the edit mode of the android app:

![image](https://user-images.githubusercontent.com/5298745/77613152-3857cb80-6ee7-11ea-8334-5a8e4d68218d.png)

Compare this to the desktop version which has it:

![image](https://user-images.githubusercontent.com/5298745/77612971-bf587400-6ee6-11ea-82cb-43149e3fe26f.png)

## Environment

Joplin version: 1.0.324
Platform: Android
OS specifics: 9

**Comment by laurent22** [comment]
not a bug, just not implemented
