### ISSUE TITLE
Attaching an image or a file to a new empty note puts markdown tag into the title

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#2915]
Steps to reproduce:

1. Create a new empty note
2. Attach any file or image
3. Save the note

Maybe set the title from the file name instead or just "Untitled"?

**Comment by rajprakash00** [comment]
Without giving any title it's obvious that whatever you write in editor comes in title be it image or file.So is with the markdown tag too.
Can you explain your issue more properly?

**Comment by roman-r-m** [comment]
Firstly, I should have clarified that I obverve this on mobile, though I suspect desktop version behaves the same.

What I mean is when I'm attaching a file, say, `very_important_document.pdf`  it would be very conventien to have the note titled `very_important_document.pdf`  rather than something like `![1584638208-17ceb24b997bbec28cab243c87d649cf.jpeg](:/a0ec092858ac4fc28881437d85)`. Makes search much easier.

Does this make sense?

**Comment by rajprakash00** [comment]
Yes,I got what you are saying. looking that way also if you write any bold or italic sentence instead of attaching file/image asteriks come in the title  like `**bold**` in title it becomes `bold**` but according to you it should be `bold`

**Comment by coderrsid** [comment]
This issue is already discussed in #1731

**Comment by roman-r-m** [comment]
> 
> 
> This issue is already discussed in #1731

I don't think it's the same, unless I have missed something - that thread is quite long.

From what I saw that issue is about inserting urls and fetching the page title while what I had in mind was attaching files that already have names, just showing this name differently in note title.

**Comment by coderrsid** [comment]
Ohh so you want the title of the file to the note title right? But would that make sense always?

**Comment by roman-r-m** [comment]
I can't think of a scenario where having markdown tag as title has more sence than file name.

But to be clear this is only for the scenario where you create a new note, attach a file and save and the title is generated automatically. Obviously you can always set title youself and this will have priority over auto generated title.

**Comment by coderrsid** [comment]
@PackElend and @bedwardly-down , can surely bring some insights here..

**Comment by PackElend** [comment]
idea sounds reasonable for me

**Comment by anihm136** [comment]
I'd like to take this up
