### ISSUE TITLE
Upgrade pop-up for 0.7.2 directs to a 0.7.0 download

### ISSUE THREAD

**Issue by placeybordeaux** [laurent22/joplin#292]
### Operating system

- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

I am currently running 0.7.0 and it is giving me the upgrade popup to upgrade to 0.7.2, however clicking through just yields another 0.7.0 download

**Comment by laurent22** [comment]
0.7.0 is old and maybe doesn't work properly, please get the latest version from there - https://github.com/laurent22/joplin/releases/tag/v1.0.70

**Comment by placeybordeaux** [comment]
Whoops I meant v1.0.70 & v1.0.72
