### ISSUE TITLE
enhancing the file system synchronisation target

### ISSUE THREAD

**Issue by Dharmesh-Poddar** [laurent22/joplin#2920]
## Issue:
  Currently when we select synchronisation target as file system we manually need to specify whole    path .
![WhatsApp Video 2020-03-27 at 10 45 56 AM](https://user-images.githubusercontent.com/32756751/77725874-9803c300-701c-11ea-9065-36572fdc2346.gif)

## Environment

Joplin version: 1.0.324
Platform: Android
OS specifics: Android 10

## Steps to reproduce

1. open the android app of joplin 
2. go to configuration tab
3.  In synchronisation tab select file system 

## Describe what you expected to happen
User should be able to browse through the files in mobile.

## Would you like to work on it
Yes

**Comment by Rahulm2310** [comment]
Yeah, I also feel it would be better if user could browse the file path

**Comment by roman-r-m** [comment]
Keep it open, I'll fix it. Someday.
