### ISSUE TITLE
Android: Some text are in black colour in dark and oled dark theme 

### ISSUE THREAD

**Issue by Dharmesh-Poddar** [laurent22/joplin#2921]
on welcome page we have some notes like welcome to joplin , importing and exporting notes etc.
 When the theme is dark or oled dark ,there are some texts inside the notes that are in black colour and that is why these texts are not visible properly and hence are not user-friendly.

![WhatsApp Image 2020-03-27 at 11 30 28 AM](https://user-images.githubusercontent.com/32756751/77727221-cfc03a00-701f-11ea-9038-263f173c71c5.jpeg)
![WhatsApp Image 2020-03-27 at 11 30 27 AM-1](https://user-images.githubusercontent.com/32756751/77727224-d0f16700-701f-11ea-9b92-731d2bbaed9d.jpeg)
![WhatsApp Image 2020-03-27 at 11 30 27 AM](https://user-images.githubusercontent.com/32756751/77727234-d3ec5780-701f-11ea-9a80-2132852b525e.jpeg)

## Environment

Joplin version: 1.0.324
Platform: Android
OS specifics: Android 10

## Steps to reproduce

1. open the joplin app in your android device.
2.  switch to the dark theme by selecting dark in theme (option present in configuration tab).
3. open the notes available on welcome page.

## Describe what you expected to happen
all the texts written in the notes should be properly visible and user-friendly.

## would you like to work on it
Yes

**Comment by anihm136** [comment]
I believe this issue was with bold text only, and resolved by a recent PR

**Comment by ishantgupta777** [comment]
Hey bro,  this issue is for bold text, I just solved it, and issue and my PR is already there

**Comment by Dharmesh-Poddar** [comment]
@ishantgupta777 @anihm136 Thanks guys !! I will close it.
