### ISSUE TITLE
Store tags inside notes

### ISSUE THREAD

**Issue by JekRock** [laurent22/joplin#2925]
It would be nice if tags were stored inside notes content so tags would remain when you export/import notes to/from a different app

**Comment by coderrsid** [comment]
Oh, that's a great idea. To which application are you trying to export/import the notes with tags? TBH, every note application has a different framework for assigning `tags` to a `note`. So, i guess it wouldn't be much possible for the tags to transfer. But, laurent can tell is there is any chance?

**Comment by JekRock** [comment]
There is the [QOwnNotes](https://github.com/pbek/QOwnNotes) app that supports tags inside notes. If tags are stored in a specific format you can convert them with just "Find and Replace" in any text editor.

It's more about saving the context than about exporting/importing. Notes that are stored in plain text can be opened with any editor no matter how they have been taken. And tags are an important part of notes that allow you to find what you need fast.

**Comment by coderrsid** [comment]
> you can convert them with just "Find and Replace" in any text editor.

I don't understand this.

> It's more about saving the context than about exporting/importing

That's what i am saying there needs to be a compatible framework in both the apps (importer and exporter) for inclusion of tags, and i perfectly support this feature, it will be really helpful if it could be implemented. You can discuss this feature in Discourse instead where you'll get better insights 
https://discourse.joplinapp.org/c/features/

**Comment by JekRock** [comment]
If you store all tags inside notes as plain text all apps that support such tagging will be able to work with them. They may have different tag formats but they will still be just a text. So you will be able to convert tags with a regex in any text editor if you need to.
I don't think there must be any framework to support this feature. Tags will be just a text. No matter how they work in a specific app. An app should index and keep track of tag changes inside notes.

I'll post it to Discourse

**Comment by deferredreward** [comment]
I'd love this too. Notable (https://notable.md/) does this with what Typora calls YAML Front Matter and doesn't display it in the app. It appears as such when seen in a different editor:
---
favorited: true
pinned: true
tags: [books, ideas, kids]
title: kid book ideas
created: '2020-04-19T18:40:12.397Z'
modified: '2020-04-20T02:39:16.154Z'
---

**Comment by MiguelTVMS** [comment]
Bear notes let you add note tags whatever you want. Just add #tagname and it adds the document to a tag. It also allows you to remove a tag added automatically from the note. And adding tags manually, without adding to the note. You can see more in [https://bear.app/#features](https://bear.app/#features)

**Comment by dylanmorroll** [comment]
I would also be interested in this! I have a lot of tags and am worried if I ever mess up my Joplin and restore from a backed up .jex file I will lose all my tags!

**Comment by JackGruber** [comment]
@dylanmorroll the tages also stored inside the jex export. 
Therefore a JEX export is a full note backup including tag and resources.

**Comment by dylanmorroll** [comment]
@JackGruber ahh that's great news! I imported a backup the other day as I had accidentally deleted a note, then once I deleted all the duplicate notes couldn't see any duplicate tags so presumed they had not been imported, but perhaps the tags were just identical! Cheers.

**Comment by ameuret** [comment]
CORRECTION: I found out by looking at the exporter source that tags are now exported in the _front matter_. My tests were bodged by a faulty sync.

I was surprised too that such a valuable metadata is not exported by the MD+FrontMatter formatter. I'm sure that most people care more about their tags than about the altitude metadata. 🫤
