### ISSUE TITLE
OneDrive sync fails on random files with UknownError

### ISSUE THREAD

**Issue by abjrcode** [laurent22/joplin#2927]
After upgrading to the latest version (1.0.195) of Joplin on Desktop which includes the new encryption algorithm; I decided to re-encrypt everything which forces a full re-sync to the target, in my case OneDrive.

It seemed like it managed to sync everything, at least it appears so, as I have pulled everything on the iOS app and I didn't see any missing data.
But when I try to install on another PC, I do see that it's not fetching the full set. Both PCs are failing randomly during sync with UknownError shown in the log file.

## Environment

Joplin version: 1.0.195
Platform: Windows 10
OS specifics: N/A

## Steps to reproduce

1. For me, just triggering the sync at this stage produces it every time.

## Describe what you expected to happen
I didn't see this issue before this version, what makes it more weird is that the mobile app doesn't seem to have any problem with the data being synced. Always getting and pushing works from mobile.

## Logfile
[log.txt](https://github.com/laurent22/joplin/files/4395745/log.txt)

**Comment by abjrcode** [comment]
I went in and started debugging to find out what is causing this.
My suspicion was initially that OneDrive API is throttling the client.
I checked [their documentation](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/?view=odsp-graph-online#throttling) and according to that, the client would get a `429 Too Many Requests` but wasn't observing this in any of the responses.
Instead I was seeing `Gateway Timeout`s happening randomly and on random files.
I couldn't determine if it is actually OneDrive servers or whether it is a node in between causing this.
I managed to work around it by inserting a manual sleep [in the code right after this line](https://github.com/laurent22/joplin/blob/master/ReactNativeClient/lib/synchronizer.js#L628) (inside the loop of course) for **one entire second** in order to overcome this timeout.
I am in doubt whether this is something to actually fix in code, after all a one second sleep is very nasty and I am still not sure if it is OneDrive or the routing during the epidemic causing this!

**Comment by LaBonave** [comment]
Hi
I'm experiencing as well random gateway timeouts when trying to set up another sync box (linux) while gathering encrypted notes from a OneDrive (live.com)

> 8875.5.png (73c0a73005234e2e9e295662f3103876) : OneDriveApi::exec: Cannot parse JSON error: Gateway Timeout Unexpected token G in JSON at position 0Réessayer
