### ISSUE TITLE
sync by WebDAV with jianguoyun.com

### ISSUE THREAD

**Issue by hahagood** [laurent22/joplin#2928]
## Environment

Joplin version: desktop 1.0.195-1
Platform: linux
OS specifics: Arch

## Steps to reproduce

1. After last update, sync by WebDAV with jianguoyun.com has something out of control.
![2020-03-28_20:26:43](https://user-images.githubusercontent.com/40338/77824425-89f99380-713d-11ea-83d1-a8202ec18960.png)
2. the message shown :
```
Updated remote items: 1.
Completed: 28/03/2020 08:06
Last error: Error: Could not encrypt item 000d7a35802047d2bc0bae19f7546c81: No master key is defined as active. Check this: Either one or more master keys exist but no password was provided for any of them. Or no master key exist. Or master keys and password exist, but none was set as active.
```

3. I try to uninstall the joplin and delete all of its directory, and then, re-install it, seems it's OK at that moment. But the same error messages show again at the second day.

4. When I check the "Options" => "Encryption" and found something unusually.
![2020-03-28_08:18:57](https://user-images.githubusercontent.com/40338/77809916-dc4e9c00-70cc-11ea-834b-e48eac012bc3.png)

**Comment by CalebJohn** [comment]
Hi, it's not clear here what issue you're experiencing. From the error it looks like you have encryption enabled but no master key set. Without more information it's impossible to say.

**Comment by hahagood** [comment]
> Hi, it's not clear here what issue you're experiencing. From the error it looks like you have encryption enabled but no master key set. Without more information it's impossible to say.

Thank you.
Maybe, something wrong happened with the WebDAV server, I change sync from WebDAV to OneDrive, it's OK now.
