### ISSUE TITLE
[Feature Request] filtering the results of the search

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#293]
### Operating system

- [X] Windows
- [x] macOS
- [x] Linux
- [x] Android
- [x] iOS

### Application

- [x] Desktop
- [x] Mobile
- [x] Terminal

Hi,
It will be great if we could filter the result of the search for a given folder/notebook/tags. Or even, I select a folder/notebook, trigger a search, then the result will be based on that folder

Other filtering, from a (range of) date(s) (for example), creation date, modified date etc.

**Comment by kstevens715** [comment]
@foxmask When you say "folder", do you mean "Notebook"?

If so, I agree this would be a very powerful feature for me also. I have my notes synced with Nextcloud and keep both my work notes and personal/home notes together. They are each in their own notebook. I use the same tags between both notebooks. When I'm in my work context, it would be very nice to be able to search only that notebook or only see notes with a certain tag in that notebook.

**Comment by foxmask** [comment]
@kstevens715  Yes

**Comment by 3d73a4a412** [comment]
+5!
if I understand thes then it would be grate. I dont understand how to search multipl tags at once? if joplin has ability to search many tags at one time and or select many tags at one time with mouse those would be so nice! Thank you!!

**Comment by cast-away** [comment]
not stale

**Comment by foxmask** [comment]
yes not stale, would like something like that.

https://discourse.joplinapp.org/t/notes-notebook-tag-task-filtering-and-searching/873

actually we can do full text search or filter on the title or the body

enter the search ourselves would be great as explain if the forum post so we could filter by tag , folder + title and body

**Comment by mic704b** [comment]
Also search by notebook, using search keyword in:

**Comment by mic704b** [comment]
WIP

**Comment by Poldi1977** [comment]
With an improved search, I could use Joplin even more effectively. Are there any plans for this?

**Comment by mic704b** [comment]
> Are there any plans for this?

https://joplinapp.org/gsoc2020/ideas.html#7-search

**Comment by foxmask** [comment]
i do my "stale bot"
nobody for this issue.
