### ISSUE TITLE
[Feature Request] Autosaving for the terminal application when modifying a file

### ISSUE THREAD

**Issue by axsaucedo** [laurent22/joplin#2933]
Reopening #1118 with a focus specifically into automatically syncing whenever a file is saved/modified or deleted, as it woudl be very useful to trigger a sync whenever a file is saved / edited.

Operating system

* Windows
* macOS
* Linux

Application

* Terminal

**Comment by coderrsid** [comment]
We can use the similar feature script from Desktop platform for this, i guess.

**Comment by coderrsid** [comment]
Although you should start discussing the feature in the discourse [feature channel](https://discourse.joplinapp.org/c/features/)
