### ISSUE TITLE
Issue with math rendering

### ISSUE THREAD

**Issue by MulintiShaikWajid** [laurent22/joplin#2934]
Writing 
Let $G=L\cup R$ 
renders incorrectly as (the source code for rendering is also being displayed)
![Screenshot (70)](https://user-images.githubusercontent.com/53876204/77851272-d6a0a580-71f5-11ea-9e82-143fdcf50eb8.png)
while writing
\* Let $G=L\cup R$
renders correctly as
![Screenshot (71)](https://user-images.githubusercontent.com/53876204/77851302-ffc13600-71f5-11ea-80f8-0d8d45418297.png)
Joplin version: 1.0.195
OS: Windows 10

**Comment by vsimkus** [comment]
It's fixed on master already https://github.com/laurent22/joplin/issues/2811.

**Comment by yangtfu** [comment]
same issue on linux 1.0.195, it's not fixed!

**Comment by tessus** [comment]
If it has been fixed after 1.0.195 how can it fixed in 1.0.195? Closing this issue to avoid other useless comments.
