### ISSUE TITLE
Adding strikethrough style on android app not working

### ISSUE THREAD

**Issue by lucker999** [laurent22/joplin#2938]
Add a `stikethrough` style (~~like that~~) to a existing note in the android app has no effect on the styled text. If a note with such style synced with windows, the styled text in the not in both windows Joplin app and in Typora show tildas instead of striked through text

## Environment

Joplin version: Latest 1.0.324
Platform: Android 5.1
OS specifics: 

## Steps to reproduce

1. Open a note in android app in edit mode
2. Add two tildas `~~` before and after some text in the note
3. Save the note
4. Look at the note and see that it renders tildas instead of striked through text
5(optiona) Sync the note with windows device - s.4.

Please note that applying the same style in windows app or in Typora (windows) works without any problem

## Describe what you expected to happen

The apps displays striked through text when the corresponding style applied

**Comment by ishantgupta777** [comment]
It worked for me, but I am on android 10, so may its problem with the android version and not the Joplin itself.
![Screenshot_1585737666](https://user-images.githubusercontent.com/27751740/78128373-6b441700-7433-11ea-9b87-d83751f85332.png)

**Comment by lucker999** [comment]
Thank you for the report. Strangely after I updated the Joplin apps on windows machines (and android re-fetched and re-decrypted all notes) it is working indeed. My guess it's somehow concerns with ecryption or other things in the latest update.

Sorry for the disturbance.

**Comment by lucker999** [comment]
Since it's working, I suggest to close
