### ISSUE TITLE
Inline LaTeX in a note

### ISSUE THREAD

**Issue by yschutz** [laurent22/joplin#2942]
The first inline LaTeX in a paragraphe shows a problem as illustrated in the screen capture below.
The inline text appears on a separate line as regular text and is then repeated as LaTeX formatted text on a new line. The second inline LaTeX does not show this feature.  

<img width="2236" alt="Capture d’écran 2020-03-30 à 16 51 20" src="https://user-images.githubusercontent.com/5189142/77926691-b11fa480-72a6-11ea-9fa8-f649e04c6856.png">

## Environment

Joplin version: 1.0.195
Platform: Mac OS
OS specifics: Catalina 10.15.4

## Steps to reproduce

1. Create a new note and type as shown in the screen caption

**Comment by anihm136** [comment]
This issue has been solved on the latest master branch

**Comment by Zpzuo** [comment]
I met the same problem. Thank you for your bringing up the bug!

**Comment by laurent22** [comment]
I believe that should be fixed in the latest release. Please check and let us know.
