### ISSUE TITLE
Android app crashes on startup

### ISSUE THREAD

**Issue by foxMclion** [laurent22/joplin#2943]
I have a setup with Linux and an android 9 phone. I first installed joplin on desktop and then tried the android app. I'm using dropbox for cloud storage. I have successfully synchronized the devices the first time. Changes fly back and forth the desktop and mobile. But then when I close the android app and relaunch it I can see it tries to sync but it crashes seconds after.

I also noticed the Android app says 'fetching resources' in the drawer menu but the message doesn't say 'syncing' with the rotating arrows. Then it suddenly stops. The Linux app works fine. Clicking sync and then cancel on startup does nothing and it still crashes. 

## Environment

Joplin version: 1.0.324
Platform: Android
OS specifics: version 9

Joplin version: 1.0.195
Platform: GNU/Linux
OS specifics: Ubuntu 18.04 x64

## Steps to reproduce

1. Install desktop app add some notes, sync with dropbox. Install android app pull the existing sync.
2. wait till android sync finished and close the app.
3. Relaunch the app. Wait two seconds and the app crashes. Android shows message about the app keeping crashing all the time with a feedback option.

## Describe what you expected to happen
joplin for android syncs my files all the time on reboot, not only the first time of syncing.

## Logfile
adb logcat:

```
03-30 17:42:16.055 26274 26358 I et.cozic.jopli: Alloc concurrent copying GC freed 493(83KB) AllocSpace objects, 0(0B) LOS objects, 7% free, 312MB/336MB, paused 65us total 31.620ms
03-30 17:42:16.055 26274 26358 W et.cozic.jopli: Throwing OutOfMemoryError "Failed to allocate a 86567928 byte allocation with 25165824 free bytes and 71MB until OOM, max allowed footprint 352730376, growth limit 402653184"
03-30 17:42:16.059 26274 26358 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
03-30 17:42:16.059 26274 26358 E AndroidRuntime: Process: net.cozic.joplin, PID: 26274
03-30 17:42:16.059 26274 26358 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 86567928 byte allocation with 25165824 free bytes and 71MB until OOM, max allowed footprint 352730376, growth limit 402653184
03-30 17:42:16.059 26274 26358 E AndroidRuntime:        at java.lang.StringFactory.newStringFromChars(StringFactory.java:267)
03-30 17:42:16.059 26274 26358 E AndroidRuntime:        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:252)
03-30 17:42:16.059 26274 26358 E AndroidRuntime:        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:65)
03-30 17:42:16.059 26274 26358 E AndroidRuntime:        at android.util.Base64.encodeToString(Base64.java:456)
03-30 17:42:16.059 26274 26358 E AndroidRuntime:        at com.RNFetchBlob.RNFetchBlobFS.readFile(RNFetchBlobFS.java:215)
03-30 17:42:16.059 26274 26358 E AndroidRuntime:        at com.RNFetchBlob.RNFetchBlob$6.run(RNFetchBlob.java:227)
03-30 17:42:16.059 26274 26358 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-30 17:42:16.059 26274 26358 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-30 17:42:16.059 26274 26358 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
03-30 17:42:16.060 26361 26361 D QcDataStatusNotification Service: WiFi status changed to 3
03-30 17:42:16.062  2281 12584 W ActivityManager:   Force finishing activity net.cozic.joplin/.MainActivity
```

I use this dropbox account only for the joplin app and this is the space it's using:

![image](https://user-images.githubusercontent.com/61948432/77933240-1ae78080-729e-11ea-9586-01171cbf5d95.png)

**Comment by foxMclion** [comment]
It's also worth mentioning that on previous app update the android app asked me to update encryption methods because they were outdated, this also happened during one of my reinstalls I did to see if that fixed the crash. Before that I've also successfully tried to attach a big file to a note, I think it was about 50MB file. The big file synced but I don't remember if it was at that time that things started crashing. But Joplin worked fine on android at one time before that, I'm sure.

**Comment by laurent22** [comment]
Possible solution is discussed there: 

https://discourse.joplinapp.org/t/whats-the-file-size-limit-for-an-attachment-in-android-2146/4545/14?u=laurent

The app should keep track of number of download attempts and stop trying after more than two attempts.
