### ISSUE TITLE
iOS app not scrooling anymore in notes (Edit mode)

### ISSUE THREAD

**Issue by zohozer** [laurent22/joplin#2944]
I am using the iOS version of Joplin 10.0.46 and unfortunately this latest update is introducing a quite serious bug.

More exactly, I can't scroll anymore into the notes in EDIT mode. I can edit only the top of the page, but it is impossible to make the keyboard to disappear and to scroll down up to the bottom of the note.

Please help to fix this issue.

**Comment by rabeehrz** [comment]
I tried this on my phone. It happens sometimes and it scrolls just fine at times. Any idea what is causing this?

**Comment by laurent22** [comment]
I cannot replicate this. If it happens for you all time with a particular note, please paste the content of it here.

**Comment by zohozer** [comment]
I have two iPhones. On the 6s everything is fine but on the iPhone X are certain notes that are refusing to scroll down in edit mode.
