### ISSUE TITLE
Clipper not adding original URL to note

### ISSUE THREAD

**Issue by plainspace** [laurent22/joplin#2946]
The Evernote clipper appends the original URL so that you can easily get back to the page you clipped from. Is it by design that the Joplin clipper does not?

**Comment by laurent22** [comment]
It does, you need to click on the Info button

**Comment by nickdex** [comment]
My first instinct was to go here and search in issues to find about it :smile: 
Joplin doesn't have full-featured docs yet right? I only found FAQs, MD and API guides. Nothing about clipper. 
P.S. - I like this project a lot, I recently migrated from evernote and chose jopling out of some 10 candidates. Its still a bit rough around the edges but owning my data and clipper made the decision. Good work!!
