### ISSUE TITLE
Certain sections not responsive

### ISSUE THREAD

**Issue by verma-anushka** [laurent22/joplin#2947]
The list of notebooks section is not responsive.
The text "Notebooks" gets hidden on upon resizing.
![issue](https://user-images.githubusercontent.com/46157435/77953498-05e50e80-72eb-11ea-8bc6-e9710ad53532.jpg)

## Environment

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1. 
2. 
3.

**Comment by laurent22** [comment]
It's by design, it's meant to be manually resized
