### ISSUE TITLE
Bug on Joplin App: "View On Map" function not working

### ISSUE THREAD

**Issue by gutzygwin** [laurent22/joplin#295]
#### Expected behavior
Joplin notes app is an open source andriod application which allows note taking and preparation of to-do list. Currently while using the joplin notes application, the "view on map" function is expected to redirect the application to search specific notes which has been already synched on the application. 

#### Actual behavior
Upon Note taking, clicking on **"View on Map"** function is not responding. When clicked on, the **"view on map"** function has no use making the option null & void. 

![Screenshot_20180309-202028.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520626161/hjwz37n8lgrrcs0u21sg.png)

#### How to reproduce
* Download the joplin application from Google playstore. *(version 1.0.3)* 
* Install and open the application.
* create a random note of any kind. 
* (make sure to synchronize it to your account) **soft recommendation.**
* Click on **"View On Map"** option. 
* Application display remains the same,  no function or operation is carried out. 

--------------------------------------------------------

* Browser: Google Playstore/Joplin Application.
* Operating system: Android 7.0. Infinix Note 4.

#### Recording Of The Bug

https://youtu.be/wYsKaVGIYeI
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@gutzygwin/bug-on-joplin-app-view-on-map-function-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by laurent22** [comment]
Do you have a default browser set?

**Comment by laurent22** [comment]
Unfortunately I cannot replicate this.
