### ISSUE TITLE
Desktop: Layout option not working at time

### ISSUE THREAD

**Issue by verma-anushka** [laurent22/joplin#2952]
The layout option doesn't work on the first click at times. It has to be selected multiple times before the layout section appears on the screen.

## Environment

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1. 
2. 
3.

**Comment by coderrsid** [comment]
Can you please elaborate the issue in hand? with addition of some screenshots too.

**Comment by coderrsid** [comment]
@laurent22 or @tessus . Can you close this issue, please?
