### ISSUE TITLE
IP Address Sort Feature

### ISSUE THREAD

**Issue by b4ndit** [laurent22/joplin#2954]
When sorting by title, notes starting with an IP address are sorted alphabetically. For example, given the note titles: 10.10.1.1, 10.10.1.123, and 10.10.1.4; the current sorting method puts the titles in that exact order. Adding "IP address awareness" to the sorting method would place the 10.10.1.123 note at the end.

<img width="505" alt="Joplin-ip-address-sort-feature" src="https://user-images.githubusercontent.com/7825877/78035962-bf69d100-7337-11ea-813e-67d178a4e3a0.png">

## Environment

Joplin version: Joplin 1.0.197 (prod, darwin)
Platform: MacOS
OS specifics:  Mojave

## Steps to reproduce

1. Create test notebook
2. Add several notes starting with IP addresses in the title (e.g. "10.10.1.1" or "10.10.1.1 - Hostname")
3. Set note sort options to "Title" and uncheck "Reverse sort order"

## Describe what you expected to happen
IP addresses should be sorted so that they appear in the proper order. For example, "10.10.1.123" should appear after "10.10.1.4".

## Logfile
N/A

**Comment by tessus** [comment]
You can either have alphabetical ordering or numerical ordering. We use alphabetical since the beginning. This is not a bug. If you wish to open a feature request or discuss Joplin in general, please use the forum.

This is works as designed, thus not a bug.
