### ISSUE TITLE
[Desktop] The app lags completely out when syncing

### ISSUE THREAD

**Issue by SleeplessSloth** [laurent22/joplin#2956]
## Environment

Joplin version: 1.0.195
Platform: GNU/Linux
OS specifics: Arch Linux, package from the AUR

## Steps to reproduce

1. Enable file system sync
2. Add a lot of one line notes (in my case it were ~2700 notes I added via the command line app via a script)

## Describe what you expected to happen

I expected it to sync once after I added the notes (even if it took a lot of time) and then only sync the changes. After that I intended to sync the directory with my Android phone with Syncthing. The phone does actually have the notes synced but the desktop app still stays unresponsive and doesn't stop "syncing"

## What actually happens

When it starts, the app lags out completely with no way to add/edit/delete notes and notebooks, while syncing infinitely. The cancel button doesn't work. The only thing that still works/opens is the settings menu. There are no errors in the console.

## Screenshots

The cancel button after being pressed

![The cancel button after being pressed](https://user-images.githubusercontent.com/37976824/78070677-8152c880-739c-11ea-987e-c49ee7c5d88e.png)

Sync settings

![Sync settings](https://user-images.githubusercontent.com/37976824/78071005-ff16d400-739c-11ea-8c92-b66b3051ba5f.png)

[log.txt](https://gist.github.com/SleeplessSloth/4b378d9416d4c246ab7d477dfd698189) (the last two lines are after I've pressed "Cancel")

**Comment by bedwardly-down** [comment]
#2518

**Comment by SleeplessSloth** [comment]
@bedwardly-down, thanks, for some reason couldn't find it by myself. Closing this in favor of the one you provided
