### ISSUE TITLE
App crashes on macOS Catalina

### ISSUE THREAD

**Issue by Ardakilic** [laurent22/joplin#2958]
## Environment

Joplin version:  1.0.1.197, downloaded manually from the releases page here in GitHub
Platform: macOS Catalina
OS specifics: 10.15.4

## Steps to reproduce

1. App updated from 1.0.195 to 1.0.196, it had build issue and blank page issue
2. Uninstalled v1.0.196 using CleanMyMac or deleting the folder at /Applications
3. v1.0.197 does not start at all

## Describe what you expected to happen
App simply does not run, macOS tries to send report to Apple. App should start without issues.

## Logfile

```
Process:               Joplin [668]
Path:                  /Applications/Joplin.app/Contents/MacOS/Joplin
Identifier:            net.cozic.joplin-desktop
Version:               1.0.197 (1.0.197.1757)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Joplin [668]
User ID:               501

Date/Time:             2020-04-01 11:23:45.457 +0300
OS Version:            Mac OS X 10.15.4 (19E266)
Report Version:        12
Anonymous UUID:        B44D6CAD-7927-860E-1CED-3388E6068265


Time Awake Since Boot: 140 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Joplin.app/Contents/MacOS/Joplin
  Reason: no suitable image found.  Did find:
	/Applications/Joplin.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/Joplin.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x101c44000 -        0x101c6cfff +net.cozic.joplin-desktop (1.0.197 - 1.0.197.1757) <CD315A0C-AE44-3040-8C05-F56E5800F953> /Applications/Joplin.app/Contents/MacOS/Joplin
       0x107113000 -        0x1071a4eff  dyld (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> /usr/lib/dyld
    0x7fff3d082000 -     0x7fff3d139ff1  com.apple.MediaPlayer (1.0 - 1.0) <74DF946F-09C6-3053-BED6-EB83374261AE> /System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer
```

**Comment by Ardakilic** [comment]
Strangely, `brew cask install joplin` worked nicely, which I believe simply downloads and extracts the app.

However, after checking the [formlae](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/joplin.rb), I realized it has ,zap trash, entries for some files/folders such as saved state, maybe I should have deleted these files (which I didn't know unless I checked the joplin formulae).

**Comment by fdterr** [comment]
I am also having this issue - using Joplin version 1.01.199 on Mac OS Catalina version 10.15.3

**Comment by Quexint** [comment]
I found this issue happened when installing Joplin by downloading `Joplin-1.0.xxx-mac.zip`.
Instead, use `Joplin-1.0.xxx-mac.dmg` to install.

**Comment by Ardakilic** [comment]
I'm almost sure that deleting the files/folders in `trash` section on the formulae which I linked above fixed the issue on my end. I didn't close the issue, because I believe this should be mentioned somewhere in the documentation (sorry if it's already, couldn't find at all).
