### ISSUE TITLE
[Feature Request] pinned notes

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#296]
### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [x] Android
- [x] iOS

### Application

- [x] Desktop
- [x] Mobile
- [x] Terminal

It could be great if we could pinned notes  and then display its title on top of all folders and tags in the menu at left.

That way we could access them without searching it nor following the path of folders or tags.

For example, I never have any loyalty card in my pocket, but I could find the loyalty card number to provide it when needed :)

**Comment by alexdevero** [comment]
@foxmask @laurent22
1) What if you already have one pinned item and pin another one? Will the second, new, pinned item be as second pinned item, under the previously pinned, or as first?
2) Should option to pin be in note context menu (right-click on note)?
3) When you unpin the note, should it be sorted by your default settings (date creation, modification, etc.)?

**Comment by dasmurphy** [comment]
Just my 2cents here.

> 1. What if you already have one pinned item and pin another one? Will the second, new, pinned item be as second pinned item, under the previously pinned, or as first?
Easy answer: Sort it like the normal list.

> 2. Should option to pin be in note context menu (right-click on note)?
Good idea.

> 3. When you unpin the note, should it be sorted by your default settings (date creation, modification, etc.)?
Sure. I would sort it normally then.

**Comment by esa1975** [comment]
Nothing new to add other than this would be a very helpful feature. If I could pin at least one note to be the first item in a notebook regardless of sort order it significantly increase my productivity within Joplin. Hopefully this will be considered in a future release. Thanks for creating and continuing to improve this application.

**Comment by alexdevero** [comment]
@esa1975 For now, you can convert note to a to-do. This will keep the note (now to-do) at the top.

**Comment by renjujv** [comment]
This is still a relevant one. For example, I have a couple of To-do notes and I want to keep two of them on the top always. However, it is always sorted automatically.

Pinned notes are not to be sorted. They just stay on top on the order they were pinned.

> Just my 2cents here.
> 
> > 1. What if you already have one pinned item and pin another one? Will the second, new, pinned item be as second pinned item, under the previously pinned, or as first?
> 
> Easy answer: Sort it like the normal list.
> 
> > 1. Should option to pin be in note context menu (right-click on note)?
> 
> Good idea.
> 
> > 1. When you unpin the note, should it be sorted by your default settings (date creation, modification, etc.)?
> 
> Sure. I would sort it normally then.

Just to add one thing,
> > > 1. Sort the pinned notes on the order they are pinned. When you are pinning a second one, it goes to the top. This allows bypassing the sorting which is useful sometimes.

**Comment by vertigo220** [comment]
Commenting to keep the issue open. Seems silly to auto-close a fairly highly upvoted issue just because it hasn't been commented on in a while. Anyways, I agree this is a must-have feature for this type of app, and as for how to sort pinned items, just make it an option so the user can choose whether to place most recently pinned items at the beginning or end of all pinned items or even to ask every time. And of course allow them to be manually sorted. When unpinning, I agree that it should be sorted normally. As for where to put the pin action, the context menu would be a good place, but I'd also like an actual pin button when editing the note to make it easy to create a note, type, and press the pin button. For the many things I don't like about Keep, there are obviously some things I do like about it, and that feature, and the corresponding pin button, is one.

**Comment by jaklan** [comment]
+1, great it could be a great use-case for GSoC 2020 @laurent22

**Comment by anihm136** [comment]
I'd like to try this.
My initial thoughts are - add a 'pinned' attribute to the note, and while sorting the note list, process the pinned notes first. This can then be toggled by an option in the note context menu.
Please share your thoughts on this.

**Comment by PackElend** [comment]
feel free to work on it.
It is clearly labeled that it is very welcome

**Comment by RealAct** [comment]
Please add this as soon as possible, I really miss this while I use Joplin.

**Comment by renjujv** [comment]
> I'd like to try this.
> My initial thoughts are - add a 'pinned' attribute to the note, and while sorting the note list, process the pinned notes first. This can then be toggled by an option in the note context menu.
> Please share your thoughts on this.

@anihm136 Your suggestion seems to be good and it seems there's no objection. Please proceed with the same after checking with one of the maintainers.

**Comment by vertigo220** [comment]
My only concern with that approach is that it seems possible the notes might be sorted randomly, so one time they might be in order 1,2,3,4,5,6 and the next time they might gets sorted 2,4,1,5,6,3, which would be chaotic. Not sure if that's the case.

Also, it would be really great if there could be priorities, so when pinning a note could be assigned P1, P2, P3, and so on, so they're sorted in that order.

**Comment by anihm136** [comment]
This feature is being discussed on the forum right now. Could you please share your ideas there?

**Comment by hutson** [comment]
For cross reference - https://discourse.joplinapp.org/t/pinned-notes/1909

**Comment by hutson** [comment]
I assume it's alright, and encouraged, to continue this conversation on the cross-referenced forum post?

**Comment by PackElend** [comment]
it is properly better continue there

Le lun. 6 juil. 2020 à 06:45, Hutson Betts <notifications@github.com> a
écrit :

**Comment by jonnydee** [comment]
What about implementing pinned notes using a special tag? Let's say all notes with a tag "pinned" would be sorted to the front of all notes in a notebook. Then there wouldn't be much to change. In fact, only the sorting logic would have to be extended in order to take into account the existence of the "pinned" tag. Furthermore, synchronization with older clients would be possible out of the box as well as listing all "pinned" notes of all notebooks.

Instead of hardcoding the tag name "pinned", one could even let the user configure such a special tag (or even more) himself. He might, for instance, configure that all notes containing one of the tags "pinned", "important", "todo" should be treated as pinned ones.

**Comment by k-slava** [comment]
Evernote experience here.
Pinned notes veryuseful. I usually work with 2-3 main notes at once where I have links to other notes. By pinning these notes I can faster my routine.
In Evernote it works like:
1. A button for note "Pin the note". 
2. All pinned notes can be found by clicking on special Logo above Notebooks.
3. In this window pinned notes can be rearranged, unpinned or oppened.

Simple and very useful for work.

**Comment by althedoc** [comment]
BUMP!

**Comment by ronilaukkarinen** [comment]
Considering about moving to Joplin from Simplenote (as it doesn't have a graphical markdown support like Joplin has) but just noticed Jopling is missing Pinned Notes feature that I really got used to in Simplenote. So it has not implemented (yet)? +1 from me to this feature.

**Comment by JojoBr0** [comment]
Are there any Updates related to this topic? 
I would love to see a feature to get pinnable notes or a favourites list...

**Comment by kpspu** [comment]
> Are there any Updates related to this topic? I would love to see a feature to get pinnable notes or a favourites list...

It is not a problem.
You can create tags "pinned" and "favourites". Functionality is the same.
If you wish some notes to ignore sorting algoritm and be always on the top, just change their type to "todo".

Hope I don't offend you by my suggestions, it is only how I use it.

**Comment by manouchk38** [comment]
@kpspu I would like much more the pinned annotation than a tag. Maybe I did not develop specific habilities to use efficiently tags. 
I was wondering: the idea is to pin annotation inside a folder? rigth?
Or would it include also pinned annotation of all subfolders too? (or could it have different options: with or withour pinned annotation in subfolder).
Edit: I've seen what @anihm136 said on the forum (https://discourse.joplinapp.org/t/pinned-notes/1909/9?u=manouchk) and it answers partially my question.  It could consist of pinned annotation in folders and of a virtual folder of pinned annotations. Interesting!

**Comment by mapperfr** [comment]
Adding my voice to support this feature request! I'm missing the ability to simply pin notes and find them easily without having to open any folder. 

My workaround for the moment is to create turn my wannabe-pinned-notes as tasks, because tasks stay above notes. It works but it's not ideal and clutters the experience (seeing a task instead of a note makes me wanna check it, or get it done!).

**Comment by tburny** [comment]
I just started with Joplin and I instantly miss this feature: As a user I'd like to pin notes in a notebook to the top of the list.
For instance I have a "Reading list" notebook and a note for the list of books which I'd like to pin. Then I can add notes on a per-book basis, keeping the list pinned to the top. If there are multiple pinned notes, they would have the same ordering (within the pins) as the other notes.

Is it possible to sponsor this feature somehow?

### Workaround: 

1. Add a 📌 emoji in front of an entry title
2. Change sorting to "Alphabetically"

Now the "pinned" entry is displayed at the top.

**Comment by n00b12345** [comment]
It would really be a useful feature. Please consider it.

**Comment by d73** [comment]
> If you wish some notes to ignore sorting algoritm and be always on the top, just change their type to "todo".

@kpspu - yours is the BEST workaround for pinning notes that I've found! thanks!

**Comment by ghost** [comment]
6y later ;)

**Comment by lorrin** [comment]
There is a Joplin Plugin, [Joplin Note Tabs](https://github.com/benji300/joplin-note-tabs) that lets you pin notes to a tab bar. That's a little different than pinning them within a notebook's note list, but I prefer it.

**Comment by AlecRust** [comment]
@foxmask why did you close this?

**Comment by jonnydee** [comment]
> @foxmask why did you close this?

I was about to ask this question, too.

Actually, the requested feature hasn't yet been implemented and, at least for me, the suggested workaround(s) don't serve well enough as a replacement.

**Comment by trajano** [comment]
My workaround is to make the note a TODO

**Comment by tburny** [comment]
I would also love to see this happen.
