### ISSUE TITLE
Opening files with cmd+g temporarily disables cursor when using Vim

### ISSUE THREAD

**Issue by Tycholiz** [laurent22/joplin#2960]
## Environment

Joplin version:  1.0.178 (Desktop)
Platform: OSX
OS specifics: Catalina

## Steps to reproduce
1. Turn on Vim mode
2. hit `cmd + g` and type in a file name
3. see that the cursor is placed at the top correctly, but cannot be moved immediately with `hjkl`. You need to first click inside the textbox to enable it.

**Comment by 3ter** [comment]
I can confirm this on Joplin 1.0.197 (prod, win32) but it is independent of using Vim mode for me.
### Steps to reproduce
1. Start Joplin
2. Press <kbd>Ctrl</kbd> + <kbd>G</kbd> (for the **first** time since opening)
3. The cursor is placed as described above

This only happens the **first** time for me. Subsequent searches with <kbd>Ctrl</kbd> + <kbd>G</kbd> work as intended.

**Comment by coderrsid** [comment]
I am not able to reproduce the issue. In my case, cursor is placed directly into the search bar.

>(for the first time since opening)

What do you mean by this? Opening for the first time after installing Joplin or just opening it in the OS.

![Screen-Recording-2020-04-05-at-3](https://user-images.githubusercontent.com/35633575/78471797-8ecbd200-7751-11ea-948a-fbc3b50a26ee.gif)
### Version
![image](https://user-images.githubusercontent.com/35633575/78471794-8d020e80-7751-11ea-95d3-9b8a0629ead1.png)

**Comment by coderrsid** [comment]
Can you guys add the GIF for the issue you faced ?

**Comment by 3ter** [comment]
Thanks for asking. I've tested it again:
* In windowed mode it works as expected
* If the app was in fullscreen before the last close and starts in fullscreen then the focus is misplaced
  * This happens again when the app is closed and reopened (in fullscreen)
  * After the focus has been set it works for the time the app is not closed

**Comment by coderrsid** [comment]
Thanks for telling. I tried the steps you're telling but still haven't faced the issue.

![Screen-Recording-2020-04-05-at-3 (1)](https://user-images.githubusercontent.com/35633575/78472220-c12afe80-7754-11ea-91c2-970c4f120497.gif)

**Comment by coderrsid** [comment]
I tried the way you said. But still couldn't see any issue.
![Screen-Recording-2020-04-05-at-3 (2)](https://user-images.githubusercontent.com/35633575/78472553-84143b80-7757-11ea-92db-655f067a730f.gif)

**Comment by 3ter** [comment]
![joplin_ctrl_g_bug_on_fullscreen](https://user-images.githubusercontent.com/11499929/78472886-a2b90900-773c-11ea-97d5-3609beae6d38.gif)

**Comment by coderrsid** [comment]
Ohh so you're on windows platform i see. Lemme see into this.

**Comment by 3ter** [comment]
> I can confirm this on Joplin 1.0.197 (prod, win32) [...]

I'm going to markup the `win32` a little more strikingly next time 😉.

**Comment by Tycholiz** [comment]
I'm running on Mac facing this issue, so it won't be a platform dependent issue. 

The issue occurs for me independent of if the app is closed at all. in other words, each time I cmd+g I get the same issue.

![optimized](https://user-images.githubusercontent.com/39745457/78503827-ec462b80-771d-11ea-86ce-31d8425eb2da.gif)

**Comment by walkie** [comment]
I think there is some confusion in this issue thread.

The original report by @Tycholiz is that *after* going to a file via "goto anything", the *note* is not in focus. This seems to actually be independent of the editing mode, and I see the same issue on Linux.

The issue reported by @3ter is that the goto search bar is not in focus after hitting `ctrl+g` in some situations.

**Comment by Tycholiz** [comment]
@walkie yes good point. I actually did this thread a disservice by including the "turn on vim" step in the reproduce steps. I didn't intend to imply that it was part of the bug, more of the steps I took to encounter the bug.
