### ISSUE TITLE
Desktop : Layout in the nord theme has a different background.

### ISSUE THREAD

**Issue by Rahulm2310** [laurent22/joplin#2961]
## Environment

Joplin version: 1.0.195
Platform: Windows

## Steps to reproduce

1. In the editor, press Ctrl+L
2. The background of the layout is different

![nord-theme-overlay-issue](https://user-images.githubusercontent.com/54268438/78175004-d1eb2400-7477-11ea-825e-a83d7151a3af.JPG)

It only persists in nord theme. In all other themes, it is consistent.Ex: In dark theme
![joplin-dark](https://user-images.githubusercontent.com/54268438/78175070-eb8c6b80-7477-11ea-923a-26e1c183264b.JPG)

## Describe what you expected to happen
The background should remain consistent in the editor and layout.

**Comment by tessus** [comment]
I don't underatand. Who says this is not on purpose. Who created the Nord theme? You will have to ask the designer of the Nord theme - not the one who added it to Joplin.

**Comment by Rahulm2310** [comment]
Nothing is wrong with the Nord theme. I just thought that using the same color for the editor as well as the layout would be better but if it is on purpose then this is not an issue.
