### ISSUE TITLE
Desktop: Sync issues with encrypted notes - note name shows "Encrypted" in title, no content visible

### ISSUE THREAD

**Issue by martinblaha** [laurent22/joplin#2966]
## Environment

Joplin version: 1.0.169 (prod, linux), Revision 0c552fe
Platform: Linux and Android App
OS specifics: Fedora 31
Syncing via Nextcloud

## Steps to reproduce

I'm using notes encryption.

1. Create a note within the Android app
2. Start syncing on Android
3. Start syncing on Desktop
4. The desktop app shows "Encrypted", in German "Verschlüsselt" in the note name. No content is visible.

[Screenshot of the error in the Desktop app](https://ibb.co/7NtjP0Z)

## Describe what you expected to happen

I'm expecting to see the note title and note contents in plan text as it is the case with all other notes.

## Logfile

No errors shown in the Console on Desktop.

**Comment by dpoulton-github** [comment]
> Joplin version: 1.0.169

If you are using the latest Andoid version its new notes will likely use the new encryption method. It looks like your desktop version is too old to support the new encryption. Try upgrading.

**Comment by martinblaha** [comment]
Thank you, @dpoulton-github, updating to a new version of Joplin did it. Awesome! :+1:
