### ISSUE TITLE
WYSIWYG - Image path breaks

### ISSUE THREAD

**Issue by armaccloud** [laurent22/joplin#2968]
When I open an note with images in WYSIWYG mode, the image path for the images in it, get the following attached in front of them, causing the image from not being shown.

`../../../..`

![image](https://user-images.githubusercontent.com/9272078/78247530-46ab7600-74eb-11ea-961a-72f8b5f4d474.png)

After I remove these dots and slashes, the image is shown again. It seems not ot happen each time but when it does, it changes for each image in the note.

## Environment

Joplin version: 1.0.197
Platform: Linux Manjaro Gnome Stable

## Steps to reproduce

1. Open an existing note with images
2. Switch to the WYSIWYG mode
3. Switch back to another view/edit mode and back to WYSIWYG
4. Verify the image paths have been corrupted

**Comment by laurent22** [comment]
I can't replicate this in the latest version, and indeed I thought I had fixed it in the previous version. If it happens again, see if you can find the exact steps to replicate the issue.

**Comment by armaccloud** [comment]
Hi @laurent22 
Yes it is still occuring and I can reproduce it now.

1. Make sure the split view is active
2. Create a note, ctrl-v a picture into it
3. Switch view to WYSIWGY
4. Add a line of text
5. Click open any other note
6. Reopen the created note
7. Verify the picture path is now broken

**Comment by laurent22** [comment]
Still can't replicate for some reason. Could you check in the About box that it really is v1.0.197?

**Comment by armaccloud** [comment]
Yes, it is version 1.0.197

![image](https://user-images.githubusercontent.com/9272078/78405868-b7dd4d00-7601-11ea-9c48-ad7acc6ebd6b.png)

I do see two different AUR packages, from which the -0 version is installed. Could that make a difference?

![image](https://user-images.githubusercontent.com/9272078/78406284-9df03a00-7602-11ea-9616-77fb7baa613c.png)


I can reproduce it in less steps too; shown in this gif.

![Joplin broken image path](https://user-images.githubusercontent.com/9272078/78406172-5ff31600-7602-11ea-8890-b3ff6d3e2352.gif)

**Comment by laurent22** [comment]
Thanks for the gif, I'll try to do the same. Are there any special characters in your home path, like accents, spaces, etc?

**Comment by armaccloud** [comment]
You're welcome Laurent, I do not ave any special characters, accents or spaces in my home directory. Let me know if there is anything I need to test, logging, etc. Thank you.

**Comment by laurent22** [comment]
Hmm, I definitely can't replicate this for some reason. I suggest trying again with the next version in case it's something I've fixed on a dev version but didn't deploy yet.

**Comment by armaccloud** [comment]
Hi @laurent22 I now have version 1.0.199 installed. Still the issue is occurring unfortunately. Is there any way to troubleshoot this?

**Comment by laurent22** [comment]
Are you able to build the app from source? If so, I could tell you where to add log statements so that we can see how the paths are being converted. Otherwise, I will add the statements myself but to test it will have to wait till the next release.

**Comment by laurent22** [comment]
@armaccloud, in the latest version I've added more log statements to try to debug this issue: https://github.com/laurent22/joplin/releases/tag/v1.0.200

Could you try to replicate it, then copy and paste the log statements here please? The two relevant statements would be those that start with `replaceResourceInternalToExternalLinks` and `replaceResourceExternalToInternalLinks`

**Comment by armaccloud** [comment]
Thank you @laurent22  I am searching where I can find the logfiles.
Where are they written to?

**Comment by laurent22** [comment]
It should be in `~/.config/joplin-desktop`

**Comment by armaccloud** [comment]
Thank you, I already got an error within the console. These were the steps.
Layout = split view, add image
Switch layout to wysiwyg, add text
Switch back to split view, get the error

> GET file:///tmp/.mount_JoplinxLJG56/resources/..:/20bcd52107c043a892f7975e243d803e net::ERR_FILE_NOT_FOUND



`
/tmp/.mount_JoplinxLJG56/resources/app.asar/gui/editors/TinyMCE.js:534 loadDocumentAssets: files to load (6) ["css/fork-awesome.min.css", "gui/note-viewer/pluginAssets/highlight.js/atom-one-light.css", "pluginAssets/katex/katex.css", "/home/arnom/.config/joplin-desktop/tmp/4c9dcdfd361090f4c6a5c21488671afd.css", "/home/arnom/.config/joplin-desktop/tmp/90ff7c48f1c4298e570e9516b7576462.css", "/home/arnom/.config/joplin-desktop/tmp/c6446da69e9e26701d8d96aac114a41b.css"]0: "css/fork-awesome.min.css"1: "gui/note-viewer/pluginAssets/highlight.js/atom-one-light.css"2: "pluginAssets/katex/katex.css"3: "/home/arnom/.config/joplin-desktop/tmp/4c9dcdfd361090f4c6a5c21488671afd.css"4: "/home/arnom/.config/joplin-desktop/tmp/90ff7c48f1c4298e570e9516b7576462.css"5: "/home/arnom/.config/joplin-desktop/tmp/c6446da69e9e26701d8d96aac114a41b.css"length: 6__proto__: Array(0)concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}__proto__: Object (3) ["gui/editors/TinyMCE/content_script.js", "pluginAssets/mermaid/mermaid.min.js", "pluginAssets/mermaid/mermaid_render.js"]0: "gui/editors/TinyMCE/content_script.js"1: "pluginAssets/mermaid/mermaid.min.js"2: "pluginAssets/mermaid/mermaid_render.js"length: 3__proto__: Array(0)
/tmp/.mount_JoplinxLJG56/resources/app.asar/gui/editors/TinyMCE.js:534 loadDocumentAssets: files to load []length: 0__proto__: Array(0) []length: 0__proto__: Array(0)
/tmp/.mount_JoplinxLJG56/resources/app.asar/gui/NoteText.min.js:921 webview_domReady Connect {props: {…}, context: {…}, refs: {…}, updater: {…}, version: 9, …}context: {store: {…}, storeSubscription: Subscription}notifyNestedSubs: ƒ ()props: {viewerStyle: {…}, onDomReady: ƒ, onIpcMessage: ƒ}propsMode: falserefs: {}renderCount: 0selector: {shouldComponentUpdate: false, props: {…}, error: null, run: ƒ}setWrappedInstance: ƒ ()state: {}store: {dispatch: ƒ, subscribe: ƒ, getState: ƒ, replaceReducer: ƒ, Symbol(observable): ƒ}subscription: Subscription {store: {…}, parentSub: Subscription, listeners: {…}, onStateChange: ƒ, unsubscribe: ƒ}updater: {isMounted: ƒ, enqueueSetState: ƒ, enqueueReplaceState: ƒ, enqueueForceUpdate: ƒ}version: 9wrappedInstance: NoteTextViewerComponent {props: {…}, context: {…}, refs: {…}, updater: {…}, initialized_: true, …}__reactInternalMemoizedMaskedChildContext: {store: {…}, storeSubscription: Subscription}__reactInternalMemoizedMergedChildContext: {store: {…}, storeSubscription: Subscription}__reactInternalMemoizedUnmaskedChildContext: {store: {…}, storeSubscription: Subscription}_reactInternalFiber: FiberNode {tag: 1, key: null, stateNode: Connect, elementType: ƒ, type: ƒ, …}_reactInternalInstance: {_processChildContext: ƒ}isMounted: (...)replaceState: (...)__proto__: Component
/tmp/.mount_JoplinxLJG56/resources/..:/20bcd52107c043a892f7975e243d803e:1 GET file:///tmp/.mount_JoplinxLJG56/resources/..:/20bcd52107c043a892f7975e243d803e net::ERR_FILE_NOT_FOUND
Image (async)
ipc.setHtml @ index.html:153
(anonymous) @ index.html:67
(anonymous) @ lib.js:179
postMessage (async)
send @ /tmp/.mount_JoplinxLJG56/resources/app.asar/gui/NoteTextViewer.min.js:114
render @ /tmp/.mount_JoplinxLJG56/resources/app.asar/gui/NoteText.min.js:2085
finishClassComponent @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17039
updateClassComponent @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16994
beginWork$1 @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18505
beginWork$$1 @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23193
performUnitOfWork @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22208
workLoopSync @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22185
renderRoot @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21878
runRootCallback @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21554
(anonymous) @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11353
unstable_runWithPriority @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:643
runWithPriority$2 @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11305
flushSyncCallbackQueueImpl @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11349
flushSyncCallbackQueue @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11338
scheduleUpdateOnFiber @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21431
enqueueSetState @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13100
Component.setState @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react/cjs/react.development.js:325
updateHtml @ /tmp/.mount_JoplinxLJG56/resources/app.asar/gui/NoteText.min.js:1087
processTicksAndRejections @ internal/process/task_queues.js:85
async function (async)
updateHtml @ /tmp/.mount_JoplinxLJG56/resources/app.asar/gui/NoteText.min.js:1066
UNSAFE_componentWillMount @ /tmp/.mount_JoplinxLJG56/resources/app.asar/gui/NoteText.min.js:435
processTicksAndRejections @ internal/process/task_queues.js:85
async function (async)
UNSAFE_componentWillMount @ /tmp/.mount_JoplinxLJG56/resources/app.asar/gui/NoteText.min.js:416
callComponentWillMount @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13371
mountClassInstance @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13461
updateClassComponent @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16986
beginWork$1 @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18505
beginWork$$1 @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23193
performUnitOfWork @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22208
workLoopSync @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22185
renderRoot @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21878
runRootCallback @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21554
(anonymous) @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11353
unstable_runWithPriority @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:643
runWithPriority$2 @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11305
flushSyncCallbackQueueImpl @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11349
flushSyncCallbackQueue @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11338
discreteUpdates$1 @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21677
discreteUpdates @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:2359
dispatchDiscreteEvent @ /tmp/.mount_JoplinxLJG56/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:5979
`

I will check the config path now for the log.

**Comment by armaccloud** [comment]
When I look in the database log, it shows me the following (using a picture, because Github changes the paths somehow)

![image](https://user-images.githubusercontent.com/9272078/79134027-52315380-7dad-11ea-957b-9d22bc2cacdb.png)

**Comment by armaccloud** [comment]
And these are from the same time in the log.txt

2020-04-13 17:23:55: "Scheduling sync operation...", "30000"
2020-04-13 17:24:02: "Scheduling sync operation...", "30000"
2020-04-13 17:24:03: "Scheduling sync operation...", "30000"
2020-04-13 17:24:05: "SearchEngine: Updating FTS table..."
2020-04-13 17:24:06: "SearchEngine: Updated FTS table in 105ms. Inserted: 1. Deleted: 0"
2020-04-13 17:24:08: "Scheduling sync operation...", "30000"
2020-04-13 17:24:10: "Attaching /home/arnom/.config/joplin-desktop/tmp/f48ffb62ec56f976f64f783b40a5576a.png"
2020-04-13 17:24:10: "File was attached."
2020-04-13 17:24:10: "Scheduling sync operation...", "30000"
2020-04-13 17:24:18: "SearchEngine: Updating FTS table..."
2020-04-13 17:24:18: "SearchEngine: Updated FTS table in 92ms. Inserted: 1. Deleted: 0"
2020-04-13 17:24:40: "Preparing scheduled sync"
2020-04-13 17:24:40: "Starting scheduled sync"
2020-04-13 17:24:56: "TaskQueue.stop: syncDownload: waiting for tasks to complete: 0"
2020-04-13 17:24:56: "TaskQueue.stop: syncDownload: Done, waited for 0"
2020-04-13 17:24:56: "Operations completed: "
2020-04-13 17:24:56: "createRemote: 2"
2020-04-13 17:24:56: "Total folders: 12"

**Comment by armaccloud** [comment]
@laurent22 Great work Laurent, thanks!
