### ISSUE TITLE
add vi-mod keymap in CLI

### ISSUE THREAD

**Issue by hahagood** [laurent22/joplin#2976]
## Environment

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1. I tried to add vi-mod keymaps step by stey acording the homepage, but failed.
2. 
3. 

## Describe what you expected to happen
Every update complete, I always change some codes as shown below to add the vi-mode keymaps:
			{ keys: ['TAB','l'], type: 'function', command: 'focus_next' },
			{ keys: ['SHIFT_TAB','h'], type: 'function', command: 'focus_previous' },
			{ keys: ['UP','k'], type: 'function', command: 'move_up' },
			{ keys: ['DOWN','j'], type: 'function', command: 'move_down' },
			{ keys: ['PAGE_UP','['], type: 'function', command: 'page_up' },
			{ keys: ['PAGE_DOWN',']'], type: 'function', command: 'page_down' },
Last update, the codes is in /u/s/j/app.js line 319 ~ 324.
I hope it will change in next version.

**Comment by laurent22** [comment]
Why do you change the source code directly? You can add a keymap.json file in your config dir instead. See doc on how to do that.
