### ISSUE TITLE
Editing encrypted notes on iOS makes them unavailable on other devices

### ISSUE THREAD

**Issue by mitrakov** [laurent22/joplin#2977]
I have several devices with Joplin installed and e2e enabled. All the notes are synchronized.

**Steps to reproduce the bug**:
1) edit note on my iPhone
2) click Synchronize
3) in some seconds this note turns into:
![image](https://user-images.githubusercontent.com/23196292/78422414-c2cac880-7667-11ea-9494-c0906b11ddb0.png)
on all other devices except iPhone

Version: version 10.0.46

**Comment by roman-r-m** [comment]
Isn't it the same issue as https://github.com/laurent22/joplin/issues/2966 ?

**Comment by mitrakov** [comment]
@roman-r-m, yep! The same misbehabiour but for iOS app.
Please close this issue if the trouble is the same

**Comment by dpoulton-github** [comment]
You do not mention what other software versions you use but a suggestion is to make sure all your other apps are up to date and support the latest encryption method.

**Comment by mitrakov** [comment]
After updating Desktop version 1.0.110 -> 1.0.224 it said:
```
One of your master keys use an obsolete encryption method. View them now
```
so looks like it was a problem with inconsistent versions.

Issue may be closed. Thanks!
