### ISSUE TITLE
Strange checkbox size scaling on iPad 

### ISSUE THREAD

**Issue by yuyichao** [laurent22/joplin#2980]
## Environment

Joplin version: 10.0.46
Platform: iPad (mini 5)
OS specifics: iPadOS 13.4

## Steps to reproduce

1. Create a note with checkbox and long text.
2. Get out of edit mode
3. The checkbox in front of the long line of text is extremely small. See screenshot below, both items are simple checklist items started with `- [ ] ` followed by the visible text.
    ![38C145A8-C40E-4D71-99A6-2B64C7A80F07](https://user-images.githubusercontent.com/712232/78459061-5d390500-7684-11ea-9e8f-7b33378b8233.jpeg)

## Describe what you expected to happen
All the check boxes should be of the same size.

**Comment by laurent22** [comment]
I think that's fixed in next version.
