### ISSUE TITLE
No .desktop files generated when AppImage file is executed on Ubuntu 18.04 with version 1.0.197?

### ISSUE THREAD

**Issue by qqlovekerry** [laurent22/joplin#2984]
## Environment

Joplin version: 1.0.197
Platform: Linux
OS specifics: Ubuntu 18.04 LTS

## Steps to reproduce

1. download the AppImage file from <https://github.com/laurent22/joplin/releases>
2. change the permissions with `chmod +x Joplin-1.0.197.AppImage`
3. run Joplin with `./Joplin-1.0.197.AppImage`

## Describe what you expected to happen
When the AppImage file is executed, an `appimagekit-joplin.desktop` file can be generated as the way the previous version (version 1.0.176) does. It seems the previous version also do some jobs which make it more convenient to run Joplin on Ubuntu, I am not fully aware of all the procedures. But the newest version 1.0.197 seems to do nothing.

**Comment by taw00** [comment]
I'd also be curious if the _other_ expected desktop element is also generated, the joplin.appmeta.xml file. I have not tried, so I don't know.

**Comment by qqlovekerry** [comment]
@taw00 Hi, do you mean I need to check whether the `joplin.appdata.xml` is generated? Could you please tell me what is the path of this file?

**Comment by sinkuu** [comment]
Desktop integartion (i.e. installing .desktop files etc.) is removed in the recent update to electron-builder 22 (https://github.com/laurent22/joplin/commit/cd19cedd46843643ddbfc47104b65867d165b55c).

https://www.electron.build/configuration/appimage.html:
> Since electron-builder 21 desktop integration is not a part of produced AppImage file. AppImageLauncher is the recommended way to integrate AppImages.

**Comment by qqlovekerry** [comment]
@sinkuu Hi, I am sorry I do not know much about the professional knowledge for building the AppImage. Does that mean the desktop integration will not be included anymore in the future?

**Comment by sinkuu** [comment]
AppImage devs [recommend](https://github.com/AppImage/AppImageKit/issues/948#issuecomment-484138051) not to implement desktop integration per application and use their solutions (appimaged or AppImageLauncher).

**Comment by qqlovekerry** [comment]
@sinkuu It seems complicated for an end-user like me. And it is less convenient for Linux desktop users I think. Hopefully, the developers of Joplin can give normal users some instructions on how to solve this.

**Comment by taw00** [comment]
> @sinkuu It seems complicated for an end-user like me. And it is less convenient for Linux desktop users I think. Hopefully, the developers of Joplin can give normal users some instructions on how to solve this.

This is why projects need to foster native packaging communities, IMHO. But it is a lot to ask for even medium-sized projects.

If they can't do that, I recommend they publish the lowest common denominator package format: Flatpak or even snap. AppImage is last resort packaging IMHO. It's one step removed from a tarball and I am not a fan.

Rolling out software in a two-step process (1) make the application work, (2) package it correctly for all platforms targeted. #2 is hard for small project communities to achieve and many punt and use an AppImage or a Flatpak that is not compiled to the native operating system.

So, what to do: Ideally identify and work with individuals who now how to package applications and encourage them to assist with all the target platforms to to be part of the release process.

So, I suppose what I am saying is cut them some slack., but it is good that you point it out.

(This was originally just going to be an explanation. Then I stood on some soapbox or something. Apologies.)
