### ISSUE TITLE
Incomplete commenting mermaid code block

### ISSUE THREAD

**Issue by JonathanPlasse** [laurent22/joplin#2985]
Hello,
To mask a mermaid graph. I commented it with `ctrl-/`, but not everything was commented.

```
```mermaid
graph TD
	a --> b
	b --> c
``
```

![mermaid_comment](https://i.imgur.com/lJpAaeE.gif)

**Comment by laurent22** [comment]
Do you know if this is actually supported by mermaid?

**Comment by anihm136** [comment]
From what I see, mermaid has its own comment syntax ('%%' at the beginning of the line), and using that inside the mermaid block works fine. Otherwise, commenting the region as a block instead of linewise also does the trick (as the comment ending delimiters are outside the mermaid syntax).

**Comment by laurent22** [comment]
Thanks for checking @anihm136. So not a bug then.

**Comment by JonathanPlasse** [comment]
Sorry, my explanation was not clear.

The problem was not about mermaid itself but about the incomplete commenting of the line caused by `-->` in the middle.
For example:
```
a --> b
```
When commented become
```
<!--a --> b-->
```
And the rendering display 
```
b-->
```
but I was expecting nothing would be rendered.

So should `-->` in the middle of the line be escaped ?

**Comment by laurent22** [comment]
We don't explicitly support comments in the Markdown text so I think anything within comments may be rendered anyway, and indeed produce unexpected results. There's currently no plan to support this I'm afraid.

**Comment by JonathanPlasse** [comment]
Thank you for the response
