### ISSUE TITLE
Dark and OLED Dark themes show white bar near status bar

### ISSUE THREAD

**Issue by duarteocarmo** [laurent22/joplin#2990]
While using the Joplin app on iOS with Dark or OLED Dark modes, a white bar appears next to the status bar, making the themes rather unpleasing. 

## Environment

Joplin version: 10.0.46
Platform: iOS
OS specifics: iOS 13.3.1 on iPhone 11 Pro Max

## Steps to reproduce

1. Open app 
2. Navigate to settings
3. Switch theme to either dark or oled dark

## Describe what you expected to happen
The white bars on top should not appear in OLED Dark theme:
<img src="https://user-images.githubusercontent.com/26342344/78534825-5f69a380-77eb-11ea-849f-75b1e71e81a3.PNG" width="200">

The white bars on top should not appear in Dark theme:
<img src="https://user-images.githubusercontent.com/26342344/78534829-61336700-77eb-11ea-98de-5ba37e94d7f1.PNG" width="200">

## Logfile

Not applicable.

**Comment by tessus** [comment]
I guess you didn't check previous issues (open and closed) not the forum.

**Comment by duarteocarmo** [comment]
Ah sorry, just saw it now, apologies for noise!

**Comment by duarteocarmo** [comment]
#2853 if someone ends up here.

**Comment by tessus** [comment]
No worries. I would have posted the link, but I don't have all the issue numbers and forum links in my head.

**Comment by duarteocarmo** [comment]
Of course, keep up the great work @tessus, great stuff you guys are building!!
