### ISSUE TITLE
Russian language cursor is not correctly placed in editor

### ISSUE THREAD

**Issue by wedvjin** [laurent22/joplin#2991]
When writing in cyrillic (russian), the cursor is placed way outside (to the right of) the actual text. It makes it impossible to jump to another portion of text. It most likely happens due to the font, as when the text is surrounded by any of the specifiers (*text*) it behaves correctly.
![Screenshot 2020-04-06 at 11 11 48](https://user-images.githubusercontent.com/7052086/78537006-6eeee980-77f7-11ea-86c9-b295cb2bbba9.png)

## Environment

Joplin version: Joplin 1.0.197 (prod, darwin)
Platform: macOS
OS specifics: Mojave 10.14.6

## Steps to reproduce

1. Write the text in cyrillic
2. See how the cursor misplaced
3. Try jumping into the middle of the word typed without success

## Describe what you expected to happen
Correct behavior as when with latin letters

## Logfile

Not-applicable

**Comment by tessus** [comment]
As the text under the editor font states:

This must be *monospace* font or it will not work properly. If the font is incorrect or empty, it will default to a generic monospace font.

**Comment by tessus** [comment]
https://discourse.joplinapp.org/t/the-wrong-letters-are-deleted/7379

**Comment by wedvjin** [comment]
On macOS (on Linux its fine) it does not default to monospace font for cyrillic languages.
The fix is to find suitable font in Font Book app (or on the web) and specify the font by typing its name in Settings >> Appearance >> Editor font family.
