### ISSUE TITLE
Copying the note cleared all the content in both original and copied note - iOS app

### ISSUE THREAD

**Issue by bakharzy** [laurent22/joplin#2994]
## Environment

Joplin version: 10.0.46
Platform: iOS mobile (iphone 6s)
OS specifics: iOS 13.3.1

## Steps to reproduce

1. Chose a note to copy (name: "sample")
2. Hold on your note till the copy button appears on top right
3. Click on the copy button
4. A new note is created with name "sample (1)"
5. The content of both notes is cleared (only titles stays) 

## Describe what you expected to happen
I expected the note to be copied with all its content (e.g. body and title). However, the content was cleared from both original and copied version of the note. 
note: The encryption is enabled

**Comment by laurent22** [comment]
I cannot replicate this. Does it happen all the time for you?

**Comment by bakharzy** [comment]
To be honest, I want to first get my note back before trying to mess with the notes and replicate (which I am happy to do after I know I am not going to mess with my notes). I asked help in the forum about how to recover my lost note. Would you check it out? I explained a bit more in details how this happened. 
https://discourse.joplinapp.org/t/recover-my-note-after-bug-clearing-it/7697/2
