### ISSUE TITLE
Checkbox position isn't centered for long text

### ISSUE THREAD

**Issue by kowalskidev** [laurent22/joplin#2996]
## Environment
Joplin version:  1.0.197 (dev, win32)
Platform:  Windows, Linux
OS specifics: Windows 10, Ubuntu 19.04

## Steps to reproduce

1.  Create Checkbox (`- [ ]`) with long text in editor
2.  Check rendered markdown
3. Rendered markdown will look like:
![checkbox_bug](https://user-images.githubusercontent.com/15380913/78648083-1f80ea00-78d9-11ea-9683-d5fd6f5a6c7c.png)

- checkbox remains at the top and text get rendered below the checkbox.

## Describe what you expected to happen

 - By following same steps in Android, the rendered markdown look like:

 ![Screenshot_20200407-134632](https://user-images.githubusercontent.com/15380913/78648284-67077600-78d9-11ea-8b5d-c3862bab72b1.png)

- Here checkbox position remains centered for long text unlike in desktop version. I think this same should render in Desktop also
- Related to similar issue: https://github.com/laurent22/joplin/issues/2980

**Comment by coderrsid** [comment]
>checkbox remains at the top and text get rendered below the checkbox.

On mac, text is rendering after checkbox though.. 
![image](https://user-images.githubusercontent.com/35633575/78657989-37f80100-78e7-11ea-8ea5-c8e687c6cd5f.png)
and for centered textbox, i don't think it will be a good idea though.
What do you think @tessus @PackElend ?

**Comment by kowalskidev** [comment]
Okay...if not in center like Android then still the checkbox looks off a bit, as you said in Mac OS checkbox remains at the top which seems fine and perfectly aligned with paragraph but still in windows and Linux results are not same it should look like as in Mac OS

**Comment by kowalskidev** [comment]
I'm still confused why checkbox output varies from platform to platform 🤔

**Comment by tessus** [comment]
Laurent already mentioned that we won't accept PRs tuning rendering for a specific platform.

**Comment by yuyichao** [comment]
Got here from the mention of my issue.

The checkbox appears in the center for me on linux. The version is 1.0.97 (Gtk 3.24.17). I'm not sure what other versions is important but here's the [PKGBUILD](https://github.com/archlinuxcn/repo/blob/d547345f89d9350d41cdc93f5656f3071c1624ab/archlinuxcn/joplin/PKGBUILD)

Personally I much prefer having the checkbox at the top like the mac one above. That's how github renders it on all browsers I've seen and IMHO it's much easier to figure out where to start reading that way.

**Comment by kowalskidev** [comment]
> 
> 
> Laurent already mentioned that we won't accept PRs tuning rendering for a specific platform.

Then I think I should close this issue, as the issues are related to specific platform.

**Comment by tessus** [comment]
Well, it doesn't mean that there isn't an underlying issue which just manifests itself differently. Maybe Laurent has an idea. Until then we should leave it open.

**Comment by kowalskidev** [comment]
Yea you are right! I should be waiting for Laurent's response before closing this issue.

**Comment by coderrsid** [comment]
Yeah sure, there are some internal dependencies issue. But we can wait for it.

**Comment by yuyichao** [comment]
Andoid phone, iPad and Linux desktop all show the checkbox on the first like just like github for me on the latest versions.
