### ISSUE TITLE
Add box.com support

### ISSUE THREAD

**Issue by Zhomart** [laurent22/joplin#30]
Please add box.com support.

**Comment by laurent22** [comment]
As box.com supports WebDAV, it should be possible to use this for sync. Actually, if you do try, please let me know as I'm trying to keep a list of compatible services.

**Comment by Zhomart** [comment]
Thanks @laurent22 for letting me know about it. Just tested it. It seems working.

https://community.box.com/t5/Upload-and-Download-Files-and/WebDav-with-Box/ta-p/310
