### ISSUE TITLE
Mobile: Automatic Scroll

### ISSUE THREAD

**Issue by kianenigma** [laurent22/joplin#3002]
While typing a note on mobile, the page does not scroll as you type, hence very soon your new text goes below the keyboard. This can be be very annoying for typing, as similar to a typewriter, you'd have to scroll down at the end of each line to see what you will type next. 

## Environment

Joplin version: 10.0.46
Platform: IOS
OS specifics: IOS 13.3.1 (IPhone SE)

## Steps to reproduce

Just strat typing. 

## Describe what you expected to happen

As you type, the page should automatically scroll to the bottom. 

## Logfile

![2020-04-07 20 06 39](https://user-images.githubusercontent.com/5588131/78703916-52dc6c80-790b-11ea-835c-c836fe6c8767.jpg)

**Comment by Rahulm2310** [comment]
@kianenigma working perfectly on android

**Comment by kianenigma** [comment]
Could be, my device is IOS as mentioned. You can see the bug even in the screenshot, how the word 'eventually' is almost no longer visible. I started typing that as I would naturally.

**Comment by jonastheis** [comment]
I have the same issue with the exact same environment. On top of that there are some scrolling issues sometimes where I can't really scroll and it sort of bounces back to its previous position.

Not sure when exactly it appeared but it must've been a recent update. Before it was working just fine.

**Comment by coderrsid** [comment]
We have some increasing platform dependent issues @tessus . It'd be great if we could discuss this overall issue on Discourse, isn't it?

**Comment by Ymetro** [comment]
> I have the same issue with the exact same environment. On top of that there are some scrolling issues sometimes where I can't really scroll and it sort of bounces back to its previous position.
> 
I am experiencing the same problem. Sometimes after scrolling ends after bouncing back (waiting a sec) it lets me scroll the page to the end or to the part where I want to edit, but mostly it bounces back to the top of the note, making it impossible to add or edit on the go. 
Maybe a dev can lay it side bij side with Apple Notes app to compare UX?

**Comment by kianenigma** [comment]
the issue is not yet resolved.
