### ISSUE TITLE
Android: image resizing is not working correctly

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#3005]
According to https://github.com/facebook/react-native/issues/22145 Image.getSize might return scaled down dimensions for large images.

I am attaching 5120x3840 image and not getting the dialog asking me whether I want to resize. In the log I can see:
```
Original dimensions  {width: 1280, height: 960}
```

**Comment by laurent22** [comment]
There's no dialog so it works as expected

**Comment by roman-r-m** [comment]
Yeah, forgot to mention this was a version built from master. Sorry about that.

There's the dialog there:
https://github.com/laurent22/joplin/blob/6d56bb8afdc0a8a3e28a4b578672f6a63018eeb1/ReactNativeClient/lib/components/screens/note.js#L431

Since Image.getSize might not return the true size, sometimes this dialog is bypassed even for images that are larger than the limit.

Plus the logging is misleading here:
https://github.com/laurent22/joplin/blob/6d56bb8afdc0a8a3e28a4b578672f6a63018eeb1/ReactNativeClient/lib/components/screens/note.js#L426
