### ISSUE TITLE
Android: Export Profile is not working

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#3010]
Joplin Android version 1.0.324

1. If Joplin has no write permissions (e. g. it has just been installed) then exporting profile fails without requesting permissions.
<img src="https://user-images.githubusercontent.com/995612/78917351-49274600-7a7e-11ea-8f9a-67feb0fcfd1a.png" width="300">

2. If Joplin has permissions then it still fails but the error is different. 
<img src="https://user-images.githubusercontent.com/995612/78917390-56443500-7a7e-11ea-8352-2eb14b58c13c.png" width="300">

It even manages to write several files before the error occurs.
<img src="https://user-images.githubusercontent.com/995612/78917420-5ba17f80-7a7e-11ea-80e9-88a70f371f45.png" width="300">

**Comment by kowalskidev** [comment]
I'm working on it

**Comment by laurent22** [comment]
Yes this dir can be skipped as we only need profile related data. Unfortunately config and app state is a bit mixed up in the profile directory.

**Comment by kowalskidev** [comment]
Alright then! I'll come up with PR soon.

**Comment by roman-r-m** [comment]
The PR is merged but it only fixes half of the issue - the import still silently fails if Joplin has no write permissions

**Comment by laurent22** [comment]
Right, i missed that, it should at least print an error in this case.
