### ISSUE TITLE
Desktop: Visibility of checkbox of list item in Note body

### ISSUE THREAD

**Issue by coderrsid** [laurent22/joplin#3015]
## Environment

Joplin version: Joplin 1.0.197 (prod, darwin)
Platform: Desktop

## Steps to reproduce

1. Write ` - [x] LIST ITEM ` in notebody 
2. Watch the opacity of checkbox decreases too with the text in the rendered-text.

![image](https://user-images.githubusercontent.com/35633575/78997596-82d27c80-7b64-11ea-9c5f-359a3f8d69af.png)

## Describe what you expected to happen
The checkbox opacity shouldn't be decreased when clicked as the text whose opacity decreases.

**Comment by tessus** [comment]
Yet again, I think this is working as designed.

**Comment by coderrsid** [comment]
Ohh, it's okay. I thought it should work like the to-do. As i fixed the checkbox opacity in to-do item too.

**Comment by tessus** [comment]
In that case, the handling of the to-do seems inconsistent. But you should discuss this on the forum, before opening an issue. It may very well be intended.

**Comment by coderrsid** [comment]
Oh sure. As it was just a small thing so didn't think like making out a discussion. But sure, i'll keep in mind. Thanks tessus.
