### ISSUE TITLE
The software will automatically delete the notes

### ISSUE THREAD

**Issue by githubWangHC** [laurent22/joplin#3017]
All the text in the notes suddenly disappeared, and there is no information in the history records, that is, it cannot be undone and restored.
Appeared twice within a month.

## Environment

Joplin 1.0.197 (prod, win32)

客户端 ID：2eb13c5e616f42b6af0f9ebe7e22f5ba
同步版本：1
最新版本：28

调整： 719afba0 (master)

## Steps to reproduce
When the bug appeared, I was using the external editor Typora to edit the text. Since pictures inserted by external editors are not supported by joplin, I have to insert pictures in joplin. The bugs appear when I want to edit the picture name after inserting the picture. When the bug appeared, the notes of about tens of thousands of words all disappeared, and this automatic deletion operation could not be recorded from the history.

在bug出现时，我在用外部编辑器Typora编辑文字。由于外部编辑器插入的图片joplin不支持，所以不得不在joplin中插入图片，bug 都是在我插入图片后想编辑图片名字的时候出现的。bug出现时大约几万字的笔记都全部消失，且不能从历史记录中找到这种自动删除操作。

**Comment by taw00** [comment]
I wonder if this is related: https://github.com/laurent22/joplin/issues/3110
