### ISSUE TITLE
Title auto-update doesn't work

### ISSUE THREAD

**Issue by alexdevero** [laurent22/joplin#3019]
In earlier versions, when I created a new note, the first line of the note was used as the note title. If I edited this line the title would change as well. This doesn’t happen in the last version. instead, the note title field remains blank, and in the note list it shows as “Untitled”.

## Environment

Joplin version: v1.0.199
Platform: Windows 10 (64bit)

## Steps to reproduce

1. Crete new note
2. Add the first line in the line
3. Observe that note tile will not change from blank, and in list from "Untitled”

## Describe what you expected to happen

The first line of the note was used as the note title.

**Comment by coderrsid** [comment]
Thanks for reporting. I am facing that issue of macOS platform too.
