### ISSUE TITLE
[Feature] - password to decrypt on open

### ISSUE THREAD

**Issue by mikeziri** [laurent22/joplin#302]
### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [x] Android
- [x] iOS

### Application

- [x] Desktop
- [x] Mobile
- [x] Terminal

I just discovered encryption mode on Joplin but after enabling it and setting a password, It just encrypts the data but after restarting the application (desktop and mobile) it doesn't ask me for the password again. it stores it cyphered (as I understand) on the master_keys sqlite (on mac os at least).

would be awesome to be requested for the master key upon app restart and maybe a lock/unlock on mobile.

**Comment by laurent22** [comment]
Duplicate of #289
