### ISSUE TITLE
Android: (+) button gets disabled

### ISSUE THREAD

**Issue by coderrsid** [laurent22/joplin#3022]
## Environment

Joplin version: 1.0.318
Platform: Android

## Steps to reproduce

1. Go to `All Notes` section. 
2. Then try to create a new notebook, but don't create one, just press back  at it will take you to `All Notes` section again
3. Try to press the (+) button, it's disabled.

## Describe what you expected to happen

It should be enabled whether a new notebook is created or not.

## GIF of issue
![20-04-11-03-27-24](https://user-images.githubusercontent.com/35633575/79041199-76552f00-7c0b-11ea-980d-fdf9cd03f46c.GIF)

**Comment by coderrsid** [comment]
@ishantgupta777 Can you have a look over this issue?

**Comment by roman-r-m** [comment]
not stale
