### ISSUE TITLE
My note and notebook disapeared after the moblie sync failed.

### ISSUE THREAD

**Issue by snowyu** [laurent22/joplin#3025]
## Environment

Joplin version: 
1. Joplin Desktop 
  - Joplin 1.0.199 (prod, linux)
  - Client ID: 8568589a7f224a0ca861d9130a4b7615
  - Sync Version: 1
  - Profile Version: 28
  - Revision: 53a857b (master)
2. Joplin Mobile
  - 1.0.324
  - Android@10

## Steps to reproduce

1. Joplin Desktop sync to the webdav server successful.
2. New mobile empty joplin client add the webdav server and begin to sync
3. the mobile joplin client report some notes can not sync for size limited.
4. Joplin Desktop begin to sync and report sync conficted.
5. my some notes and notebook lost!!!

## Describe what you expected to happen

Where to find my lost notes? in note history??

## Logfile

It seems I've run into the issue #1673.

**Comment by snowyu** [comment]
I wish split the sync feature to upload and download two way options.

**Comment by laurent22** [comment]
For support, please use the forum. Maybe your notes are in the conflict notebook?

**Comment by snowyu** [comment]
No, only two notes in the conflict notebook. and It is modified note too(some attachment disapeared).

**Comment by snowyu** [comment]
I guess the mobile upload the wrong notes for attachment size limits and the desktop download them.
