### ISSUE TITLE
Joplin.AppImage 1.0.200 does not show proper Version (or is not this version)

### ISSUE THREAD

**Issue by kingfisher77** [laurent22/joplin#3035]
Looking at "About Joplin" shows still Version 1.0.197 after download of

https://github.com/laurent22/joplin/releases/download/v1.0.200/Joplin-1.0.200.AppImage

Yet it seems to be the latest version ...

**Comment by laurent22** [comment]
Probably some issue with the way the app is started on your system.

**Comment by kingfisher77** [comment]
After a reboot of the machine the version number displayed right. Maybe a cache issue? Arch, Gnome 3.36.1. I just use this to install `wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash`
