### ISSUE TITLE
New editor is unusable on Android

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#3036]
Firstly the edit area is completely obscured by keyboard.

And on top of that the editor breaks SwiftKey autocomplete, see the video (in case it's not clear I was typing "test"):

![ezgif com-gif-maker](https://user-images.githubusercontent.com/995612/79104659-8af60c00-7d5e-11ea-9238-c2879c861a5e.gif)

**Comment by kowalskidev** [comment]
Is your issue is same as I reported here: https://discourse.joplinapp.org/t/android-joplin-keeps-stopping-while-using-editor-mode/7905 ? If so this bug is already reported here: https://github.com/laurent22/joplin/issues/2939

**Comment by roman-r-m** [comment]
Not quite as it does not crash in my case but I suspect the underlying issue might be the same or closely related.

**Comment by kowalskidev** [comment]
> And on top of that the editor breaks SwiftKey autocomplete, see the video (in case it's not clear I was typing "test"):

here you specifically mentioned ` SwiftKey autocomplete` I think this issue might be related to your keyboard features because I unable to reproduce this bug in my phone (I'm using default Google Keyboard though) can you please try to reproduce this bug using your system default keyboard?

**Comment by roman-r-m** [comment]
I could but what's the point? Even if this was fixed the editor is still completely broken on Android (I refer to the other issues where it crashes the app with ArrayIndexOutOfBounds or something like that).

**Comment by MisterY** [comment]
I've just installed the app and the editor in 1.0.329 seems quite usable. No issues experienced while testing some markdown features and general behaviour.

**Comment by roman-r-m** [comment]
@MisterY just to be clear - did you enable "Opt-in to the editor beta" in Settings?

**Comment by MisterY** [comment]
@roman-r-m , no. That probably means that "New editor" is too vague? I don't see a single reference to specific version numbers.

**Comment by virtadpt** [comment]
I gave the latest rev (Joplin v1.0.329) another try last night on Android 10 running on a Samsung SM-G965U - same thing.  Writing anything on my phone is next to impossible due to the lag.

I'm also giving the beta editor a spin, and I can't say I'm any more pleased with it.  The amount of time it takes to scroll to the bottom of a note alone is frustrating.  On Android, Joplin is still pretty much read-only.

Is there something I can do to provide some debugging information?
