### ISSUE TITLE
Formatting text in long lines is not rendered

### ISSUE THREAD

**Issue by homofortis** [laurent22/joplin#3038]
Formatting multiline paragraph  is not rendered if the text has been line wrapped .

## Environment
Joplin version: 1.0.200
Platform: Desktop
OS specifics: Linux/Ubuntu 19.10

## Steps to reproduce
1. Insert a long paragraph which spans on multiple lines.
2. format (e.g. bold/italic) a word or several words (which are not on the first line).
3. observe the result in preview showing the format characters being displayed instead of rendered.

**Comment by kowalskidev** [comment]
Can you please show snapshot of your note. I just checked into my system having same config as yours (Ubuntu 19.10) but I couldn't able to reproduce your bug... everything is working fine.

**Comment by homofortis** [comment]
Strange, it is working fine for me now. Sorry, for ringing the bell :disappointed: . Closing it now.

**Comment by homofortis** [comment]
![Screenshot from 2020-04-13 13-13-59](https://user-images.githubusercontent.com/3680999/79119637-ba217300-7d88-11ea-845f-4562ac811592.png)
I've closed the issue because I couldn't reproduce it with selecting a single word but could reproduce it by selecting a couple of paragraphs (I don't know if it's the desired effect according markdown standards).

**Comment by kowalskidev** [comment]
Ahh! got it. No need to check with long paragraph just write two words with line and space between them like:
**hello

world**

I don't think it's a bug, blank new line is not allowed in between (**). You are right!
>it's the desired effect according markdown standards
