### ISSUE TITLE
Bulleted List - Indentation Fails at Line Space?

### ISSUE THREAD

**Issue by aakashsinghbais** [laurent22/joplin#3039]
![image](https://user-images.githubusercontent.com/56718090/79115328-2dd07980-7da3-11ea-8524-33915d9cae1c.png)
I guess this one is self explanatory. The indentation is failing at `Example`, but comes back on the next bullet. (these are sub-bullets)

An extra `TAB` is needed to get `Example` back in proper indentation.
![image](https://user-images.githubusercontent.com/56718090/79117224-29f32600-7da8-11ea-8180-7584b5aac46d.png)

I dunno if this is an issue or a feature of MarkDown. Just wanted to make sure it is seen.

## Environment

Joplin version: version 1.0.200 (prod, win32)
Platform: Windows 
OS specifics: Windows 10

**Comment by laurent22** [comment]
yes this is fine
