### ISSUE TITLE
Joplin fails to launch after update

### ISSUE THREAD

**Issue by alexdevero** [laurent22/joplin#304]
Joplin version: v1.0.74

Screen:
![vystrizek](https://user-images.githubusercontent.com/4237724/37513721-1e2b8874-2906-11e8-8fa4-92f4a04a627a.JPG)

### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [ ] Terminal

**Comment by laurent22** [comment]
This error happens when trying to open a recent version of a profile with an older version of Joplin. Did you install something from one of the development branches by any chance? Could you open database.sqlite in SqliteStudio and check what version you have in the "version" table?

**Comment by alexdevero** [comment]
I don't have SqliteStudio.

**Comment by alexdevero** [comment]
Solved by removing Joplin and removing Joplin directory in `C:\Users\[user]\AppData\Roaming\`

**Comment by nenadandric** [comment]
I have the same issue, but uninstall of previous version and deleting dir in .\Roaming\ didn't help
![2018-03-16 10_36_19-joplin_1074](https://user-images.githubusercontent.com/22467540/37514568-9a085380-2908-11e8-982d-5cbed4bbee7c.png)

**Comment by alexdevero** [comment]
@nenadandric Do you have any left over files from Joplin on disk?

**Comment by laurent22** [comment]
Right, it seems the CI uploaded a dev branch to version 72, so it means it's not possible to upload from this one to 73 or 74.

I'm going to take these two versions out and release 75 which should fix this issue.

**Comment by nenadandric** [comment]
Ok, i found solution. I had to delete joplin-desktop folder from "C:\Users\[user]\.config". But that leaves me without notes if I don't synchronize/backup them

**Comment by laurent22** [comment]
@nenadandric, for now please install v72

**Comment by nenadandric** [comment]
It is working now with 1.0.77
Thank you
