### ISSUE TITLE
No Way To Escape Formatted Bulleted Lists?

### ISSUE THREAD

**Issue by aakashsinghbais** [laurent22/joplin#3040]
While creating a bulleted list, I have noticed:
- Pressing `Enter` after adding a `Space` automatically creates a new bullet below the existing.
- Pressing `Enter` without a `Space` exits the list and goes to the beginning of next line maintaining proper indentation.

But, I found: 
**If the list element is formatted (Like: `- **My name is Joplin**`), using `**` for **bold**, `++` for *italics* or `__` or `==` etc., pressing `Enter` with / without `Space` (at the end) leads to a new bullet being created. Then the only way to get rid of it is to manually delete it...and this is a pain when doing repeatedly.**

## Environment
Joplin version: version 1.0.200 (prod, win32)
Platform: Windows 
OS specifics: Windows 10

## Describe what you expected to happen
In a bulleted-list, pressing `Enter` without a `Space` at the end should escape the list always (irrespective of whether the list element is formatted or not.)

**Comment by Rahulm2310** [comment]
@aakashsinghbais  Did this happened with the previous versions also ?

**Comment by aakashsinghbais** [comment]
@Rahulm2310 I am not sure, will have to check.

**Comment by virtadpt** [comment]
It did.

**Comment by Rahulm2310** [comment]
@aakashsinghbais  can't replicate. If possible, please provide a GIF.

**Comment by aakashsinghbais** [comment]
Even I can't replicate it now!
