### ISSUE TITLE
MacOS: App blocked from opening after installation

### ISSUE THREAD

**Issue by wesimpson** [laurent22/joplin#3042]
## Environment

Joplin version: 1.0.200
Platform: MacOS Catalina
OS specifics: 10.15.4

## Steps to reproduce

1. Update or install de novo Joplin
2. Install is ok, when opening for the first time receive an error message (see screenshot)
3. 

## Describe what you expected to happen

- As with all previous updates, I expected it to just open after I installed.
- Received an error message instead
- Joplin was open and previously working before I updated. I tried rolling back to previous functioning versions and they no longer work either. 
- It appears to be something re new software installs on MacOS.
<img width="422" alt="Screen Shot 2020-04-13 at 9 13 41 AM" src="https://user-images.githubusercontent.com/37227874/79123106-62bedb00-7d67-11ea-8581-efb53656bda4.png">

**Comment by wesimpson** [comment]
Update: Installation via homebrew works fine.

**Comment by laurent22** [comment]
Closed as duplicate
