### ISSUE TITLE
Android: Text Editor doesn't show any text if its pretty large

### ISSUE THREAD

**Issue by i1qwert** [laurent22/joplin#3043]
## Environment

Joplin version: 1.0.327 (Android) | 1.0.197 (Win10)
Platform: Android
OS specifics: 8.1 | MIUI 10

## Steps to reproduce

1. create large note (with cyrillic symbols i guess) on desktop
2. sync on both devices
3. try to edit this note

## Expected
Wanted to see text that i'm editing
https://imgur.com/a/12pxRvb

Also, I still able to edit text and save it

## Logfile
I checked errors and there were no errors when i tried to edit note, can show only this https://imgur.com/a/DLvqRSv

**Comment by Kiel97** [comment]
Looks like we have the same issue: #3041

**Comment by laurent22** [comment]
Closed as duplicate
