### ISSUE TITLE
Installer removing custom tray icon on each update

### ISSUE THREAD

**Issue by Nixellion** [laurent22/joplin#3045]
Whenever installing a new Joplin update installer removes current Joplin icon even if it was moved to Tray. Meaning after each update I have to move the icon down to the tray and delete it from the desktop.

Makes updating a bit more annoying than it should be.

**Comment by ShadeAnimator** [comment]
No, tried latest version updater, installer still removes my existing icon even if it was moved to tray and creates a new one on desktop. I. Want. It. In. The. Tray.

**Comment by Nixellion** [comment]
No, tried latest version updater and installer still removes icon that was moved to tray and creates new one on the desktop. I. Wan.t It. In. The. Tray.

**Comment by Nixellion** [comment]
Leave it open, installer still removes default icon even if it was moved to tray.

**Comment by pomeloy** [comment]
The installer also re-creates a previously deleted desktop icon. There should be an option to install either desktop or tray icon.

**Comment by pomeloy** [comment]
Issue still requires attention.

**Comment by Nixellion** [comment]
Moreso, I created a NEW icon from scratch and named it differently "Joplin_" and pinned that to tray, and it STILL GOT REMOVED! Extremely annoying!

**Comment by pomeloy** [comment]
Not fixed yet.

**Comment by pomeloy** [comment]
Not fixed yet.

**Comment by Nixellion** [comment]
Still not fixed

**Comment by Nixellion** [comment]
Cool. F you too then.

**Comment by pomeloy** [comment]
See #4155.

**Comment by Nixellion** [comment]
@pomeloy Ah, thank you!
