### ISSUE TITLE
API: PUT method doesn't support all properties that POST method supports for notes

### ISSUE THREAD

**Issue by jyuvaraj03** [laurent22/joplin#3046]
Some of the [properties of POST method for notes](https://joplinapp.org/api/#properties) (such as body_html, image_data_url, crop_rect, etc) do not work with PUT method. 

For example:
```
$ curl --data '{"title":"my note1", "body_html":"<h1>My h1 header</h1>"}' http://127.0.0.1:41184/notes
{"title":"my note1","body":"# My h1 header","markup_language":1,"parent_id":"782863aa5e2a4959ba8f4f01e3124deb","updated_time":1586787552281,"created_time":1586787552281,"source":"joplindev-desktop","source_application":"net.cozic.joplin-desktop","id":"c24350c549f1465dbcaa36d4395127c2","user_updated_time":1586787552281,"user_created_time":1586787552281,"type_":1}
$ curl -X PUT --data '{"body_html": "<h2>My h2 header</h2>"}' http://127.0.0.1:27583/notes/c24350c549f1465dbcaa36d4395127c2/?token=my_token
{"id":"c24350c549f1465dbcaa36d4395127c2","parent_id":"782863aa5e2a4959ba8f4f01e3124deb","title":"my note1","body":"# My h1 header","created_time":1586787552281,"updated_time":1586787750204,"is_conflict":0,"latitude":"0.00000000","longitude":"0.00000000","altitude":"0.0000","author":"","source_url":"","is_todo":0,"todo_due":0,"todo_completed":0,"source":"joplindev-desktop","source_application":"net.cozic.joplin-desktop","application_data":"","order":0,"user_created_time":1586787552281,"user_updated_time":1586787750204,"encryption_cipher_text":"","encryption_applied":0,"markup_language":1,"is_shared":0,"type_":1,"body_html":"<h2>My h2 header</h2>"}
```
The first command creates a new note with POST method. This method uses the `body_html` property and the note body is properly formatted and saved. 

The second command attempts to update the body using the `body_html` property with the PUT method. But, the body does not change at all. Instead in the API response JSON, the `body_html` value is just echoed back. This is, I believe because the special properties have not been implemented at all for the PUT method. 

## Environment

Joplin version: 1.0.200
Platform: Terminal
OS specific: no

## Describe what you expected to happen

I expect that all the properties that work in the POST method works in PUT method also. 

As I have worked on a similar issue #2649, I would like to continue from there and work on this issue.

**Comment by laurent22** [comment]
We won't be adding this at this point, as it doesn't appear anybody needs this feature. Also it's possible to achieve this with other means.
