### ISSUE TITLE
blockquote without language is highlighting first word

### ISSUE THREAD

**Issue by pcause** [laurent22/joplin#3047]
I have some plain text.  I put 3 back ticks in the from and end.  

```
line1
line2
line3
```

As you can see, Github and others treat this as plaintext if no language is specified.  However, in Joplin 1.2.200 if I don't specify a language in splitview the first word of each line is highlighted.  If I put 

>```plaintext

as the blockquote then things are treated as just text.  The same issue happens when I use the new WYSIWYG editor to view the markdown

**Comment by laurent22** [comment]
Closed as duplicate
