### ISSUE TITLE
Missing Carriage Returns / Line feeds on Layout in Windows

### ISSUE THREAD

**Issue by thomascrisan** [laurent22/joplin#3048]
Starting with version 1.99 on Windows, the layout screen is not displaying carriage returns / line feeds correctly.  It ignores single CR LFs, recognizes double ones, and ignores more than two in a row.

To reproduce, create a new note and try formatting the note with carriage returns.

Screen captures attached.
![2020-04-13_12-11-53](https://user-images.githubusercontent.com/26765643/79137796-619aa780-7d81-11ea-826b-8effdcb343c7.png)
![notepad++_2020-04-13_12-18-45](https://user-images.githubusercontent.com/26765643/79137812-695a4c00-7d81-11ea-9621-cb8dc680af76.png)

**Comment by laurent22** [comment]
Do you have "soft break" on in the Plugin options by any chance?

**Comment by thomascrisan** [comment]
Yes, turning that off corrected the problem.

**Comment by thomascrisan** [comment]
Apologies for reporting this behavior.  I did not realize the behavior of soft breaks plugin is to not only recognize two spaces as a line break but to also ignore hard breaks.

**Comment by laurent22** [comment]
Yes it reflows the text when soft break is on, perhaps that should be mentioned in the doc.
