### ISSUE TITLE
"move to notebook" list not sorted in alphabetic order

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#3052]
## Environment

Joplin version: 1.0.200
Platform: linux
OS specifics: debian

## Steps to reproduce

1.  when moving note to another notebook the popup list is not sorted in alpha order

**Comment by coderrsid** [comment]
Hey @foxmask, thanks for reporting. I just checked again for the error you specified, but i don't see any. You can see in the below GIF it is rendering properly according to the notebooks listed in sidebar.  

![Screen-Recording-2020-04-14-at-3](https://user-images.githubusercontent.com/35633575/79212954-02629300-7e66-11ea-943e-6c3252970304.gif)

Can you provide any screenshot or GIF for the problem you're facing? 😄

**Comment by foxmask** [comment]
@coderrsid you can see a screencast I made here https://github.com/laurent22/joplin/issues/3053 when I move note ; you can see "Tech" before "Projet" before "Maison" it looks like sorted in the other side.

**Comment by coderrsid** [comment]
Thanks for telling but that link is expired and can i ask why we have two different issues for a similar problem?
![image](https://user-images.githubusercontent.com/35633575/79213513-f1665180-7e66-11ea-8a15-975de77487a3.png)

**Comment by foxmask** [comment]
because it's 2 issues ...

**Comment by coderrsid** [comment]
![image](https://user-images.githubusercontent.com/35633575/79213859-86694a80-7e67-11ea-8806-7f94e44bb9f4.png)
 
Although i see there is a sorting issue in here. I'll just fix this ASAP.

**Comment by foxmask** [comment]
https://send.firefox.com/download/33e37cab4250e811/#A1PBqx5T9u5cgRh9EUgWyg

**Comment by coderrsid** [comment]
Great. Now i can see the issue. Thanks for reporting. 😄

**Comment by tessus** [comment]
@coderrsid btw, the cursor looks really weird in the dialog:

![mtnb](https://user-images.githubusercontent.com/223439/79282073-42377380-7e82-11ea-952a-f6b96b3317cb.gif)

Maybe, because it doesn't blink. It only starts blinking when you pick a folder.

**Comment by coderrsid** [comment]
Thanks @tessus . I'll look into this too.

**Comment by coderrsid** [comment]
@foxmask Can you add the GIF here too please. Unfortunately, the last one is removed again. 😄

**Comment by coderrsid** [comment]
And one more thing i want to ask is that the order of notebooks shown in your sidebar is perfectly right, the way it should be?

**Comment by foxmask** [comment]
yes the order in the right sidebar is the right one.

here is the gif
![joplin-move-bug](https://user-images.githubusercontent.com/208212/79451535-fc47f000-7fe6-11ea-9d91-c6298ef6590b.gif)

**Comment by coderrsid** [comment]
Thanks! I'll see what i can do.

**Comment by coderrsid** [comment]
@laurent22  Will it be right if i change the way how `Folder.allAsTree( )` returns the folders tree in a sorted way instead of just rendering parent and children together but also sort them or instead i should just make them sort for the `moveToNotebook` . I believe it will be helpful in future use cases.

**Comment by coderrsid** [comment]
@tessus In my case, the cursor is working as expected. Although if it is an issue, it should be in all the dialog boxes using `inputType: 'dropdown'` . Can you check the cursor in the dialog box of `Create note from Template` or `Create to-do from template` or `Insert Template`
![Screen-Recording-2020-04-18-at-4 (2)](https://user-images.githubusercontent.com/35633575/79636062-ad3ebe00-8192-11ea-9f5c-30f279449372.gif)

**Comment by tessus** [comment]
>  Will it be right if i change the way how Folder.allAsTree( ) returns the folders tree in a sorted way

How is this done by the web clipper? I believe the function returns a sorted result set. Either way, something like a boolean argument with a default is a good option `(sort = true)`. On the other hand, why would someone ever want a not sorted result? 
But maybe people would like the same order they set in `Sort notebooks by`. This is certainly an architectural question and this is something only Laurent can answer.
If it were me, I'd create a function that takes the sort order as argument, which is called with the order that is set in the menu. IMO that would be the most logical and consistent approach.

> Can you check the cursor in the dialog box of `Create note from Template` or `Create to-do from template` or `Insert Template`

In those cases the cursor blinks right away. Not so with the `Move to notebook` dialog.

**Comment by coderrsid** [comment]
> How is this done by the web clipper? I believe the function returns a sorted result set. Either way, something like a boolean argument with a default is a good option `(sort = true)`. On the other hand, why would someone ever want a not sorted result? 

That's why i asked laurent if i can change it to always return a sorted array by title. 😄

> But maybe people would like the same order they set in `Sort notebooks by`. This is certainly an architectural question and this is something only Laurent can answer.

Yeah that would be something he can answer for sure.

> If it were me, I'd create a function that takes the sort order as argument, which is called with the order that is set in the menu. IMO that would be the most logical and consistent approach.

that's a great idea, we can add a function which returns the order of the notebooks in the same option set in `Sort notebooks by` 


> In those cases the cursor blinks right away. Not so with the `Move to notebook` dialog.

Although it shouldn't have any problem as the dialog is a part of a simple dropdown which is similarly used in the other components i ask you to test in .. 😅 Still i'll just look at it again but do tell me how to reproduce the issue. Than k you so much for suggesting tessus. 😄

**Comment by coderrsid** [comment]
> Will it be right if i change the way how `Folder.allAsTree( )` returns the folders tree in a sorted way instead of just rendering parent and children together but also sort them or instead i should just make them sort for the `moveToNotebook` . I believe it will be helpful in future use cases.

@PackElend @bedwardly-down 
what do you think about this?

**Comment by bedwardly-down** [comment]
This is honestly less us and more the dev team. Tessus and Laurent didn’t respond to that post directly, so I’d take that as them probably being indifferent to it. With everything going on, it might be better to take a step back here also and just patiently wait for more feedback or ask on the forums.

**Comment by coderrsid** [comment]
Sure. As you say sir.

**Comment by tessus** [comment]
@coderrsid 

> but do tell me how to reproduce the issue.

Not really much to it. right-click a note and click `Move to notebook`. The cursor does not blink.
