### ISSUE TITLE
Desktop: Disable syntax highlighting inside Katex code

### ISSUE THREAD

**Issue by anjulalk** [laurent22/joplin#3054]
When using `<` inside Katex, the editor falsely recognize it as a HTML tag and messes up syntax highlighting. See below:

![image](https://user-images.githubusercontent.com/26695184/79230113-c0dfe100-7e81-11ea-8c90-5d8b2d2d3590.png)

Use following snippet for reproducing:
```
Equation1

$$
\sum_{i<j}
$$


This text should not be highlighted. But it is.
```

## Environment

Joplin version: 1.0.200
Platform: Linux
OS specifics: Ubuntu 19.10 (5.3.0-46-generic)

## Steps to reproduce

1. Copy the above snippet into editor
2. See editor highlighting text incorrectly

## Describe what you expected to happen

The editor should ignore `<` or other mathematical symbols inside Katex.

**Comment by laurent22** [comment]
That's probably tricky to fix as it seems to be a bug in Ace Editor itself, but if you have some ideas feel free to give it a try.

**Comment by tessus** [comment]
Yep, the Ace editor has a few bugs in that regard. It also highlights italics in the middle of a word (`text_not-italics_text`), which is definitely one of the most annoying bugs ever.

**Comment by Rishgod** [comment]
Can't you just escape that letter, to prevent its default behaviour or am I missing something? 🤔

![image](https://user-images.githubusercontent.com/54576074/79267610-1682b080-7eb7-11ea-9b41-0115fb54eba7.png)

**Comment by anjulalk** [comment]
@Rishgod I guess you can do that. You can also add spaces near the `<` and it will also work. But the regular user won't know about that since it's not really standard in Katex.

If we can process Katex code like how comments are parsed in the Ace editor, we can maybe get the desired result? Katex blocks start with `$$` and end with `$$`. So if anything between can be considered as a comment (like between `<!--` and `-->`) it will ignore the `<` as well.

**Comment by Rishgod** [comment]
Don't get me wrong you definitely can do that, but this looks too much of a work for something which could just be solved by adding a white-space.


![image](https://user-images.githubusercontent.com/54576074/79277914-5c944000-7ec8-11ea-8245-8beae44a2012.png)

**Comment by laurent22** [comment]
The problem is that `$$` as a fence is not standard Markdown so Ace Editor highlights the block as if it was just any other text.

At some point Devon added custom rules to override syntax highlighting there https://github.com/laurent22/joplin/blob/c5c379f38a4a302be5a4659461d2f3d9be027461/ElectronClient/gui/NoteText.jsx#L58 so maybe it's possible to do something similar to handle Katex blocks.

**Comment by anjulalk** [comment]
It looks pretty straight forward. I'll give this one a go.
https://cloud9-sdk.readme.io/docs/highlighting-rules is a good reference if anyone else wants to try.

**Comment by thofma** [comment]
I see something similar with underscores. Is this the same issue?

![image](https://user-images.githubusercontent.com/11231648/82077455-c24e3480-96df-11ea-8771-c30f2218eaed.png)

**Comment by anjulalk** [comment]
Yes, it's very similar to this one.

**Comment by tessus** [comment]
https://github.com/ajaxorg/ace/issues/3942
