### ISSUE TITLE
Encryption specification does not detail the "new" encryption method

### ISSUE THREAD

**Issue by tensojka** [laurent22/joplin#3057]
I updated Joplin on Linux today (176 to 200). It suggested I re-encrypt my data:

> You may use the tool below to re-encrypt your data, for example if you know that some of your notes are encrypted with an **obsolete encryption method**.

> The following master keys use an **out-dated** encryption algorithm

What is the new encryption method? What was the old method? Should I be worried?

This _should be_ detailed in the [encryption specification](https://joplinapp.org/spec/) or in [about End-To-End Encryption](https://joplinapp.org/e2ee/).

I found the commit 03146ed85f4f6ddb04984cf2559f8ac25c191235 , but it does not detail **why** the change took place. I can update the docs, but don't know what to write.

**Comment by laurent22** [comment]
It was detailed there https://www.patreon.com/posts/joplin-informal-35719724 and also posted on the forum, but otherwise it's true that the in-app message is quite generic, as it's meant for any type of encryption upgrade.
