### ISSUE TITLE
Katex not rendering in PDF export

### ISSUE THREAD

**Issue by jeremyfreedman** [laurent22/joplin#3058]
## Description
When exporting documents to PDF with Katex present, the Katex portions appear as whitespace. 
As an example, the below images are the same note, the first being a screenshot from the Joplin application and the second from my PDF renderer (I tried multiple): 
![image](https://user-images.githubusercontent.com/2095570/79271479-dcd98780-7e6d-11ea-9346-98b7b7fe3d5d.png)
![image](https://user-images.githubusercontent.com/2095570/79271491-e2cf6880-7e6d-11ea-9e25-c0c492e92971.png)

## Environment

Joplin version: 1.0.200
Platform: Windows 10 Pro 
OS specifics: x64 Version 1909 (18363.720)

## Steps to reproduce

1. Create a new note.
2. Write some in-line math using Katex (ie. $1+1=2$)
3. Export to PDF using File -> Export -> PDF - PDF File
4. Open the PDF in any PDF viewer and check if the Katex you entered is visible.

## Describe what you expected to happen
The lines should be visible and typesetted properly using Katex.

## Logfile
The console raises no errors or warnings when exporting. The log file (`log.txt`) does not print anything when exporting whatsoever.

**Comment by laurent22** [comment]
Please provide a full note that can be used to replicate the bug.

**Comment by tessus** [comment]
I can't reproduce this, but I'm on macOS. Here's a test file:

```
# Matrix

$$
\begin{pmatrix}
    a & b & c\\
    a & b & c\\
    a & b & c\\
    a & b & c
\end{pmatrix}
$$

# Standard Deviation

$\bar{x}$ = the mean, or average, of all data points in the problem 
x = an individual data point 
N = the number of points in the data set

$$
\sigma = \sqrt{\frac 1 N \sum_{i=1}^N(x_i-\bar{x})^2}
$$

# Katex Documentation

https://katex.org/docs/supported.html

# Color Test

$\colorbox{red}{A}$

# Symbols

$$ 
\text{\textasciicircum}
$$

$$ 
\text{\textasciitilde} 
$$
```

However, for some reason the matrix looks like this in the PDF: 

<img width="128" alt="image" src="https://user-images.githubusercontent.com/223439/79281468-c5f06080-7e80-11ea-9b94-4ba62a1ee5de.png">

while in Joplin it looks perfectly fine:

<img width="91" alt="image" src="https://user-images.githubusercontent.com/223439/79281501-daccf400-7e80-11ea-8b0b-2c05ad34da13.png">

**Comment by jeremyfreedman** [comment]
> 
> 
> Please provide a full note that can be used to replicate the bug.
Github wouldn't take an .md file, I had to rename to .txt. I included the Joplin-produced PDF as well, which is missing Katex rendering.

[Test Katex.md](https://github.com/laurent22/joplin/files/4478253/Test.Katex.txt)
[ENGRD 2300 - Test Katex.pdf](https://github.com/laurent22/joplin/files/4478256/ENGRD.2300.-.Test.Katex.pdf)
