### ISSUE TITLE
After enabling encryption on Linux desktop the syncronization fails with "Error: The maximum request length supported is 4mb

### ISSUE THREAD

**Issue by rsramkis** [laurent22/joplin#3060]
When enabling encryption on a Linux Manjaro 19 desktop I am getting the following error when trying  to sync to ONEDRIVE.

"Error: The maximum request length supported is 4mb"

I did see this error on in the FAQ, but I don't believe I have any attachments of this size.

**To Troubleshoot:**

(1) I disabled encryption and confirned the syncronization would complete.

(2) Enable Encryption with a new key.
 
(3) Checked the application directory "\Home\.config\joplin-desktop\resources" for files over 4mb: 

-  fa86d79f859240faaa87392b92db021a.crypted 4.6mb

- 81b3b6f1ebaf4e07b89b8904e131ce9d.crypted 4.3mb

Question, How do I get around this problem?

**Joplin Version**
Joplin 1.0.197 (prod, linux)

Client ID: 70463d14b0de41a1938ae6f92e949ff3
Sync Version: 1
Profile Version: 28

Revision: 719afba (master)

**Comment by laurent22** [comment]
This is a limit of OneDrive
