### ISSUE TITLE
Focus on note body after "Goto Anything" or "Toggle editor layout"

### ISSUE THREAD

**Issue by walkie** [laurent22/joplin#3066]
## Rationale

I'd like to use Joplin while using the mouse as little as possible. The current focus behavior makes this difficult.

### Expected / Desired

If I'm in an "editing" layout already, here's what I'd like:

1. `ctrl-g` + type note name + `enter`
2. Start editing the note

### Currently

1. `ctrl-g` + type note name + `enter`
2. Use mouse to click in note body editor
3. Start editing the note

Instead of step 2, I could also use the `tab` key, but the focus is on the top-level window, so it requires 13 tabs to get to the note body.

At the very least, I believe the focus should be changed in the same way that it would if the note had been clicked on, which would require just two tabs to get to the note body.

## For Ctrl-L (Toggle editor layout)

Similarly, if I toggle to an editor layout, I'd like the focus to be automatically moved to the note body.

### Expected / Desired

1. `ctrl-l`
2. Start editing the note

### Currently

1. `ctrl-l`
2. Use mouse to click on note body
3. Start editing the note

If I navigated to the note originally using the mouse, then the note (but not the note body) is in focus, so using `tab` at step 2 is not too bad, requiring just two tabs.

However, if I navigated to the note using `ctrl-g`, then the focus is still on the top-level window after `ctrl-l`, so tabbing to the note body is not a good option.

## Environment

Joplin version: 1.0.200
Platform: Linux
OS specifics: Fedora

## Related

Issue #2960 is describing the same desired behavior but got derailed by a separate issue. The description here is more precise and complete.

**Comment by laurent22** [comment]
Note that you can always press Ctrl+Shift+N or +B to focus the note title or body.

**Comment by walkie** [comment]
Good to know, thanks! I still think it would be nice to change the default focus behavior, but this definitely eases my immediate problem.

**Comment by rabeehrz** [comment]
I'll look into this.

**Comment by Rolograaf** [comment]
I have the same annoyance with Ctrl-L (why do I need 2 shortcuts Ctrl-L + Ctrl-Shift-B to start editing?) But since release 1.1.201 Ctrl-G does not choose the top item of the list on `Enter` but item number 16, I need to scroll down to find it. This is repeatable.

I tried again and instead entering, when I push down-arrow, it goes to item 17 in the list. I think there is a bug in the pointer?

**Comment by rabeehrz** [comment]
> I tried again and instead entering, when I push down-arrow, it goes to item 17 in the list. I think there is a bug in the pointer?

Yeah. This is a bug. It has been reported [here](https://discourse.joplinapp.org/t/strange-goto-anything-behavior/8139/5).
