### ISSUE TITLE
Android tablet: encryption password "save" button doesn't work

### ISSUE THREAD

**Issue by NadineNB** [laurent22/joplin#3068]
## Environment

Joplin version: 1.0.327
Platform: Andoid
OS specifics: Android 4.4.2

## Steps to reproduce

1. Follow steps 1-5 here: https://joplinapp.org/e2ee/

## Describe what you expected to happen

I managed to successfully synchronize my Dropbox account with the Android app on my smartphone (Android version 5.0.1) , but on my tablet (Android 4.4.2), I cannot get the encryption password saved in the Joplin app because clicking on the "save" button does not do anything.

## Logfile

![Screenshot_2020-04-16-13-20-19_2a](https://user-images.githubusercontent.com/6593341/79454356-5e0a5900-7feb-11ea-9661-9513ae50ee5b.jpg)

**Comment by 38569459** [comment]
I workaround it by pressing ok button in the keyboard, then click save. If it not work, try several times.

**Comment by NadineNB** [comment]
I followed your instructions and unfortunately, it still doesn't work. I turned on the keyboard sound and pressing on "save" never generates any sound. Not sure what to do next, maybe the app is just not compatible with Android Kitkat?

**Comment by laurent22** [comment]
I don't quite understand the issue: the button is not supposed to turn gray. You simply need to input the password, press Save, and if the password is correct the red cross will turn to a green tick. If it doesn't turn to a green tick, it means the password is not right, so please check it again.

**Comment by NadineNB** [comment]
It's ok, I'll uninstall Joplin from my tablet and focus on the smartphone and desktop app for now. Thanks for looking into it anyway!
