### ISSUE TITLE
Joplin Icon Unpinned From Taskbar On Upgrade

### ISSUE THREAD

**Issue by denevin** [laurent22/joplin#3070]
Joplin Windows 10 taskbar icon is unpinned each time the application is upgraded to latest version.

This becomes cumbersome for frequent user of application as often it's simple to forget to pin it back to taskbar and having to look for the program in system tray.

## Environment

Joplin version: 1.0.200
Platform: Windows 10
OS specifics: None

## Steps to reproduce
1. Install older version of Joplin on Windows 10
2. Pin Joplin to Windows 10 taskbar.
3. Upgrade Joplin to latest version and notice that Joplin icon is unpinned from taskbar

## Describe what you expected to happen
Joplin should remain pinned to Windows 10 taskbar after upgrade.

**Comment by coderrsid** [comment]
Does this happen only with joplin or all apps ?

**Comment by denevin** [comment]
> 
> 
> Does this happen only with joplin or all apps ?

The programs that I have pinned and are updated frequently stay pinned after the upgrade: Firefox, Chromium, Notepad+.

**Comment by coderrsid** [comment]
Although i am not facing the problem on macOS. I guess a windows user can confirm that.
