### ISSUE TITLE
[Feature Request] Option to change Editor/View to View/Editor layout

### ISSUE THREAD

**Issue by SkyWheel** [laurent22/joplin#3072]
Hi folks,
Is it possible to toggle Editor/View layout to View/Editor layout?
Currently only 3 modes available:
- Editor Only
- View only
- Editor(left)/View(right)
It would be really nice to have 4th option:
- View(left)/Editor(right) layout
Thanks.

**Comment by rabeehrz** [comment]
It seems like a really good addition, but some discussion needs to be done on the forums before opening up an issue here. There are multiple [topics](https://discourse.joplinapp.org/t/feature-request-a-split-view-option-to-switch-sides-around/5259) on the forums asking for the same.

**Comment by coderrsid** [comment]
Although like how will it be useful anyway. As much as i know it's like a standard way of rendering anything to it's right-side.
