### ISSUE TITLE
Joplin fails to remember window state on Ubuntu Linux when application is closed

### ISSUE THREAD

**Issue by blueorignal** [laurent22/joplin#3073]
When Joplin is initially launched, it opens up with a non-maximized window that is half-way up the screen. If Joplin is then manually maximized, or the window is resized, everything works as expected. When Joplin is closed and re-opened, it fails to remember the prior state of the main window and opens with the original window setting on each launch.

## Environment

Joplin version: Joplin 1.0.119 (prod, linux)
Platform: Ubuntu
OS specifics: 18.04 LTS

## Steps to reproduce

1. Open Joplin
2. Application opens with non maximized window
3. Application window needs to be manually adjusted each time

## Describe what you expected to happen

1. Open Joplin
2. Manually adjust window
3. Close application
3. Re-open application and have the application launch with the previously selected window setting

## Logfile

n/a

**Comment by Rahulm2310** [comment]
@blueorignal I think this issue is already reported here #2185

**Comment by blueorignal** [comment]
Thank you and please accept my apologies for the double post. I did search before posting, but did not find the #2185. I will add my update to the appropriate thread.
