### ISSUE TITLE
CLI: External markdown links not showing properly in preview

### ISSUE THREAD

**Issue by Datamance** [laurent22/joplin#3080]
Version: joplin 1.0.163 (prod)
System: Darwin myhost.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
OS: Mac OS X Catalina

Here's the markdown:
![image](https://user-images.githubusercontent.com/8699411/79595775-7347bc00-80ad-11ea-99dd-eb4ba6baa77c.png)

And here's the link that shows up in preview:

![image](https://user-images.githubusercontent.com/8699411/79595827-89557c80-80ad-11ea-858b-cb3b41b04cf1.png)

Love the software. Interested in contributing to it soon!

**Comment by laurent22** [comment]
It's a feature - the link is shortened to take less space.
