### ISSUE TITLE
[Synchro difficulty] HiDrive

### ISSUE THREAD

**Issue by Ada-lover** [laurent22/joplin#309]
(I use Mobile Application on Android)

Dear Laurent,
Thanks a lot for your great project Joplin.
I would like to use the HiDrive cloud for synchro (provided by Strato.com) with WebDAV.
I follow the instructions given in the FAQ of this Cloud provider
(link = https://www.strato.fr/faq/article/2046/Quels-sont-les-differents-chemins-dacces-pour-FTP-SMB-WebDav-Rsync-etc.html)
The synchronisation test in Joplin works well (says "Success").
But synchro ends by an html message saying "You don't have permission to access on this server".
(I checked my username, my password a lot of times and tried both http and https access which are allowed by HiDrive).
May be it's because the HiDrive directory is split in two subdirectories "Public" and "Users" ?
Thanks for your help.

**Comment by Ada-lover** [comment]
Solution found !
I simply added "/users/myaccount" at the end of the WebDAV URL and it works ! (with "myaccount" = the real name of my account).
Sorry for having disturbed you without having tried this simple test. I hope my hint will help other users.
You can add HiDrive in the list of clouds working well with Joplin.
Thanks a lot

**Comment by laurent22** [comment]
Great thanks, I've added it to the list along with a link to this post for help.
