### ISSUE TITLE
Android: Attachments are not downloaded with encryption enabled.

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#3090]
Steps to reproduce:
- on one client (I used windows but suspect it does not matter) set up Dropbox sync and encryption
- add a note and attach any file
- sync
- on mobile authorize with Dropbox and synchronize
- when prompted enter the password

When synchronization completes notes are availble but attachments are not.
Without the encryption attachments are downloaded during the first sync.

Only if I kill the app and restart then the attachments are downloaded. Or another way I've found is to go to configuration and switch "Attachment download behaviour" from the default Always to something else and back to Always.

Note that this was reproduced on a version I built from sources not the one from Play Store.

**Comment by laurent22** [comment]
Which version? Normally I've recently fixed this bug in master

**Comment by roman-r-m** [comment]
Ah yes, I do not have this change. Thanks.
