### ISSUE TITLE
Goto Anything freezes when you type punctuation marks

### ISSUE THREAD

**Issue by desk7** [laurent22/joplin#3093]
- 1.0.201
- Windows 10 64bit

When you use Goto Anything, it dynamically changes the results as you type.

But if you enter a punctuation mark (e.g. `.`  `*`  `!`), the result list completely freezes. Even deleting and writing something else it no longer works. You have to exit the goto box and press Ctrl+G to make it work again.

**Comment by coderrsid** [comment]
I can confirm this behaviour on mac too. Let me look into this.  😄

**Comment by anjulalk** [comment]
I'll take a look at this.
