### ISSUE TITLE
Fix table rendering in dark mode

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#3098]
Reported on mobile but probably happens on desktop too.

https://discourse.joplinapp.org/t/darkmode-problem-visualisation/7570/9?u=laurent

**Comment by kowalskidev** [comment]
>  probably happens on desktop too.

Yaa I tested on desktop the issue is with renderer looks like CSS issue.

**Comment by kowalskidev** [comment]
I can reproduce it in android but unable to reproduce in desktop.
I'm using Joplin version: 1.0.327

**Comment by rabeehrz** [comment]
<img width="856" alt="Screenshot 2020-04-20 at 6 08 54 PM" src="https://user-images.githubusercontent.com/44024553/79752505-098c1400-8332-11ea-8154-cb089461333b.png">

This is the view of the table on Desktop. It isn't present on Desktop?

**Comment by rabeehrz** [comment]
The table colour style is missing from the css. I'll open up a PR right away.

**Comment by kowalskidev** [comment]
>  It isn't present on Desktop?

Isn't looks fine?

**Comment by rabeehrz** [comment]
> Isn't looks fine?

Yep, It does.
