### ISSUE TITLE
Allow zooming

### ISSUE THREAD

**Issue by DiThi** [laurent22/joplin#31]
I'd like to make all the content bigger for my HiDPI screen which has the zoom set to 100% for several reasons.

**Comment by laurent22** [comment]
This is now implemented.

**Comment by MichaelTunnell** [comment]
this is not working :(

as reported in another thread about font size, this function doesn't do anything.

**Comment by htjain** [comment]
+1. It would be great to have dynamic zoom with Ctrl+MouseScroll or something similar. Sometimes clipped note has very small fonts and impossible to read.

**Comment by bernd-wechner** [comment]
I set a Global Zoom Percentage of 500 and Apply and nothing happens! I too would cherish CTRL+MouseScroll zoom like any web browser today supports. It's second nature and in low light I'm having trouble reading my Joplin notes!
