### ISSUE TITLE
Light stripe in dark mode on iphonex and ipad2018

### ISSUE THREAD

**Issue by TianHongZXY** [laurent22/joplin#3101]
There is a light stripe on the right side in dark mode on my iphonex and ipad2018. Please fix it. Thank you

**Comment by rabeehrz** [comment]
Can you provide screenshots please?

**Comment by TianHongZXY** [comment]
![IMG_0292](https://user-images.githubusercontent.com/39355004/79778361-33156180-836b-11ea-9971-83511e7a95d9.PNG)
![IMG_2154](https://user-images.githubusercontent.com/39355004/79778398-41fc1400-836b-11ea-8f4c-8f6fe1346b06.PNG)

**Comment by rabeehrz** [comment]
This is fixed via #3055 
Duplicate issue of #2853 
This will be fixed in the next version of the App.

**Comment by TianHongZXY** [comment]
OK,thanks！
