### ISSUE TITLE
Global shortcut to show/hide Joplin doesn't work in MacOS Mojave

### ISSUE THREAD

**Issue by 0xMH** [laurent22/joplin#3103]
## Environment

Joplin version: Joplin 1.0.201
Platform: MacOS
OS specifics: Mojave

## Steps to reproduce

1. Click `Cmd+Opt+J`  from within the App.

## Describe what you expected to happen
I expect Joplin to get hidden but that doesn't happen. Also if I clicked `Cmd+Opt+J` when It is hidden it doesn't appear.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/4506657/log.txt)

**Comment by tessus** [comment]
Yes, we had to revert this, because too many people complained that it interfered with existing shortcuts. (Not really sure why Joplin had to fix this and not the other programs, but ok.)
It will be added back when we develop our custom shortcut code.

**Comment by mrozekma** [comment]
@tessus Not sure how the website gets updated, but it's still referenced there: https://joplinapp.org/#global-shortcut

**Comment by axq** [comment]
@mrozekma you can just submit a PR to fix here: https://github.com/laurent22/joplin/blob/a4cc2076d70a19a50730a98615c86eaab448e358/docs/index.html#L632
