### ISSUE TITLE
UX Proposal: Provide three buttons instead of one - each for one layout

### ISSUE THREAD

**Issue by furusiyya** [laurent22/joplin#3106]
I want to propose a UX related adjustment. Joplin provides three type of layouts. 

1. Full screen writing
2. Full screen viewing
3. Split screen (write and view in parallel)

Speaking of my self, I don't like Split screen writing. So every time when I want to switch from full screen writing to viewing or vise versa, I have to click twice which is very uncomfortable.  And I believe it would same for someone who prefer Split screen view. 

It would be great if you provide three buttons, one for each layout instead of one. I am attaching a quick drawing that will help you to understand my point.
![image](https://user-images.githubusercontent.com/11066354/79833624-24f42f00-83c5-11ea-84c8-d81b7c5f2146.png)

**Comment by coderrsid** [comment]
Thanks for the suggestion @furusiyya . But you should discuss this on [Discourse-Forum](https://discourse.joplinapp.org/) . You'll get better reponses. 😄

**Comment by dpoulton-github** [comment]
Joplin already has a solution to this.

**Tools** > **Layout Button Sequence**

If you set it to **Editor / Viewer** it will save you a click and just toggle between the two full-screen options like you want.

![editor_viewer](https://user-images.githubusercontent.com/60117449/81479816-9e8d7900-921d-11ea-87ef-c7169e88bbb1.png)
