### ISSUE TITLE
Display of entered letters is very slow for notes with a lot of text

### ISSUE THREAD

**Issue by Atalanttore** [laurent22/joplin#3115]
On a middle class smartphone from 2018 with Android 9 I have freshly installed Joplin. Then I set up the encrypted synchronization with a NextCloud via WebDAV.

I inserted a lot of text from another app in 1 note in Joplin. The text exported as PDF file in the Joplin desktop app has over 20 pages in A4 format.

## Issue
When entering additional letters to this note, it now takes several seconds before they are displayed.

## Environment

Joplin version: 1.0.327
Platform: Android 9
OS specifics: Android One

## Steps to reproduce

1. Create a new note
2. Insert enough text for 20 pages in A4 format
3. Enter additional letters

## Describe what you expected to happen
No slowdown when entering additional letters.

**Comment by roman-r-m** [comment]
Seems like a known issue: https://github.com/laurent22/joplin/issues/1493
