### ISSUE TITLE
Formatting: Code Block vs. Inline Code 

### ISSUE THREAD

**Issue by snakyjake1** [laurent22/joplin#3116]
Can we get the code block and inline code to look the same?

This is what I get:
![image](https://user-images.githubusercontent.com/8312560/80006663-0bf98580-847a-11ea-8661-c4d0efaddd29.png)

1)  Notice the syntax highlighting.  Code blocks have syntax highlighting, but inline code does not.  This should be the same.  There should be no syntax highlighting by default.
2)  Notice the background shaded color.  This should be the same.
3)  Notice the border around the inline code.   This should be the same.  
4)  The font may not be the same either.

## Environment
Joplin 1.0.201 (prod, win32)
Sync Version: 1
Profile Version: 28
Revision: e65af8c1 (master)

**Comment by rabeehrz** [comment]
This might not be a bug actually. Because even GitHub doesn't do that I guess.

**Comment by Rishgod** [comment]
This is not a bug, it is a convention to do that

**Comment by tessus** [comment]
It's not a bug. With specifying a highlighting language, it tries to autodetect.

You have to use ` ```plaintext`

**Comment by snakyjake1** [comment]
According to https://wordpress.com/support/markdown-quick-reference (I can probably find other sources too), there's a difference between:
"Code block"
vs.
"Syntax highlighting"

**Comment by tessus** [comment]
I'm not sure what you are trying to say.

In Joplin and other editors, code blocks are syntax highlighted. If you don't want a code block to use syntax highlighting, you'll have to explicitly state that as I've descfribe earlier.

**Comment by tessus** [comment]
If you are not happy with the current behavior you can open a topic in the forum and start a discussion.

This tracker is used for bugs only.
