### ISSUE TITLE
Joplin freezes completely on Arch Linux

### ISSUE THREAD

**Issue by nikoloskid** [laurent22/joplin#3118]
## Environment

Joplin version: joplin-1.0.201-1
Platform: 
OS specifics: Arch Linux 5.6.5-arch3-1

## Steps to reproduce

1. I open Joplin and start to edit my notes 
2. After few minutes of using, Joplin freezes, I can't move from noteboot to notebook, I can't create one, nothing works.
3.

**Comment by laurent22** [comment]
Duplicate of #3114
