### ISSUE TITLE
Tabs display error on Android app

### ISSUE THREAD

**Issue by xplosionmind** [laurent22/joplin#3120]
OS: Android 10 (Oxygen OS on OnePlus 6T)
Joplin app version: 1.0.329

## BUG DESCRIPTION

As displayed in the following screenshot, Joplin automatically alternates light grey and black background for each row. The problem is that on light background white text is not visible.

![Screenshot_20200424-085600](https://user-images.githubusercontent.com/42862428/80214629-77d71c00-863b-11ea-9594-0634fd0da6c0.jpg)

## EXPECTED BEHAVIOR

The rows background, if alternated, should be darker, to allow a better reading of the text.

**Comment by rabeehrz** [comment]
Hey,
Thank you for reporting. This has been fixed via #3100 and will be released in the next update.
