### ISSUE TITLE
Globl shorcut (Ctrl+Alt+J) does not work

### ISSUE THREAD

**Issue by aleksandr-amirkhanov** [laurent22/joplin#3121]
When the global shortcut (Ctrl+Alt+J) is pressed the application is not shown or hidden. The global shortcut worked fine for me in the version 1.0.199, but in the current version it does not work.

## Environment

Joplin version: 1.0.201
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Open Joplin
2. Collapse the application
3. Press Ctrl+Alt+J

## Describe what you expected to happen

The application must be shown or hidden.

**Comment by coderrsid** [comment]
Sorry to say, but it was reverted. You can find more specific reason in the below link. 
https://github.com/laurent22/joplin/issues/3103

**Comment by tessus** [comment]
But we have a GSoC project for custom keyboard shortcuts, which will allow you to specify the shortcut you want for this.
