### ISSUE TITLE
Samsung Note spd file from Evernote

### ISSUE THREAD

**Issue by rajil** [laurent22/joplin#3126]
Hello,

I imported notes from Evernote which included some spd files created using Samsung Note phone. In the Android app there is no way to download these files, although a download icon does appear on the left.

Thanks

**Comment by roman-r-m** [comment]
How big are those files?

**Comment by rajil** [comment]
After a full sync on the phone, I can now see them. The files are pretty small, and if I try to open them in Joplin there is no way to save them or open then in Samsung Notes.
