### ISSUE TITLE
The modified pdf cannot be synchronized to oneDriver

### ISSUE THREAD

**Issue by githubWangHC** [laurent22/joplin#3129]
## Environment

Joplin 1.0.201 (prod, win32)

客户端 ID：07c34fde26074b6996991c148e0423c8
同步版本：1
最新版本：28

调整： e65af8c1 (master)

## Steps to reproduce

Can be reproduced
**in device 1 do Operate as follows**
1. add pdf attached 
2.  synchronize to oneDriver
3. modify pdf(write text on pdf,  Mark on pdf)
4. synchronize to oneDriver again
**in device 2 do Operate as follows**
1. synchronize from oneDriver.
2. i can find the pdf file  synchronized to oneDriver before.
3. **But i can not find the text marked on pdf.**

**Comment by kuraci** [comment]
check this: onedrive sync files limit at 10m. if your pdf file is over 10m , sync would fail.
