### ISSUE TITLE
Feature Request: Runtime Permissions

### ISSUE THREAD

**Issue by derrafa** [laurent22/joplin#313]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

Hello thanks for the great App. Is there any plan to update the Android mobile app to runtime permissions?

Regards

**Comment by laurent22** [comment]
Sorry what runtime permission do you mean?

**Comment by derrafa** [comment]
When I install Joplin on Android I have to give access to all requested permissions. With Runtime permissions the app just asks for access when it they really needed. As far as I understand it is a newer API level (>=23).

https://developer.android.com/training/permissions/requesting.html
"You declare that your app needs a permission by listing the permission in the app manifest and then requesting that the user approve each permission at runtime (on Android 6.0 and higher). "

**Comment by xuhcc** [comment]
Filesystem permission request added here: https://github.com/laurent22/joplin/pull/1665
Camera and location permissions are also requested at runtime.

So probably we can remove permission notice from the config screen (https://github.com/laurent22/joplin/blob/v1.0.163/ReactNativeClient/lib/components/screens/config.js#L387)  and close this issue.
