### ISSUE TITLE
[Desktop] Long URL break UI

### ISSUE THREAD

**Issue by NothingCtrl** [laurent22/joplin#3131]
On Joplin Desktop version, a very long URL break UI in note properties pop-up, button _OK_ or _Cancel_ is hide (out of view), _ESC_ is not close the pop-up, click outside is not close the pop-up, so user cannot close the pop-up properties.

![bug_joplin_ui](https://user-images.githubusercontent.com/5380820/80300597-4cce0300-87c8-11ea-9a61-b0006735a02f.jpg)

## Environment

Joplin version: 1.0.193, 1.0.201
Platform: Linux
OS specifics: Ubuntu 18.04

## Steps to reproduce

1. Create a note
2. Open note properties
3. Add very long URL

## Describe what you expected to happen

URL should wrap in side the view port

**Comment by rabeehrz** [comment]
I'll look into this.

**Comment by Rahulm2310** [comment]
@rabeehrz @NothingCtrl It is fixed by a recent PR (#3096)
You can see it below:
![dialogboxfix](https://user-images.githubusercontent.com/54268438/80306082-b0632b00-87de-11ea-96c4-703b4a04a224.gif)

**Comment by rabeehrz** [comment]
That is not fixed @Rahulm2310
