### ISSUE TITLE
When entering Chinese quotation marks, the Chinese in the editor is misaligned

### ISSUE THREAD

**Issue by Micalson** [laurent22/joplin#3134]
Hello, thank you for your contribution. The note is very helpful. 
I have found the following problem:
When entering Chinese quotation marks, the Chinese in the editor is misaligned. As shown below.
![image](https://user-images.githubusercontent.com/45941423/80328393-cb32af80-8871-11ea-82c4-7b1a41d0c010.png)
The more Chinese quotation marks entered in a line, the greater the offset.
How to fix this? thank you for you reply.

Regards,

**Comment by CalebJohn** [comment]
Hi @Micalson would it be possible for you to copy and past that note into a comment on here? I'd like to test this issue but can't enter those characters on my computer.
I have tried pasting the following characters into a note
、””「…『…』…」『 』﹁﹂「 」“…‘…’…”."。"、
But I don't have the same problem.
