### ISSUE TITLE
Regression - Joplin terminal application

### ISSUE THREAD

**Issue by digdug999** [laurent22/joplin#3140]
Joplin terminal application was working fine until today (despite the various electron issues).

Today joplin terminal refused to start with a 'MODULE_NOT_FOUND' error.  Was working fine yesterday.  Didn't see any obvious candidates in /var/cache/pacman/pkg that would have broken this since yesterday.

`
% joplin
internal/modules/cjs/loader.js:1017
  throw err;
  ^

Error: Cannot find module '/usr/share/joplin-cli/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_s
Require stack:
- /usr/share/joplin-cli/node_modules/sqlite3/lib/sqlite3.js
- /usr/share/joplin-cli/lib/database-driver-node.js
- /usr/share/joplin-cli/lib/BaseApplication.js
- /usr/share/joplin-cli/app.js
- /usr/share/joplin-cli/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)
    at Function.Module._load (internal/modules/cjs/loader.js:884:27)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/share/joplin-cli/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/joplin-cli/node_modules/sqlite3/lib/sqlite3.js',
    '/usr/share/joplin-cli/lib/database-driver-node.js',
    '/usr/share/joplin-cli/lib/BaseApplication.js',
    '/usr/share/joplin-cli/app.js',
    '/usr/share/joplin-cli/main.js'
  ]
}

`

## Environment

Joplin version: joplin 1.0.201-1 (AUR)
Platform:  Linux
OS specifics: 5.6.7-arch1-1

## Steps to reproduce

1. Have joplin installed.
2. Regular update packages.
3. Attempt to start joplin from terminal by typing "joplin".
4. Error string above results.

## Describe what you expected to happen
Start joplin terminal.

## Logfile
Per debug instructions:

> CLI application🔗
> Start the app with joplin --log-level debug
> Check the log.txt as specified above for the desktop application and attach the log to the GitHub issue (or just the warnings/errors if any)

log.txt file is not created in the places indicated.  Also the log.txt file that's usually slowing growing in 
~/.config/joplin does NOT result in any additional lines from this aborted start.

**Comment by tessus** [comment]
The only supported way to install the terminal app is to use `npm -g install joplin`. Please report this problem to the AUR package maintainer.
