### ISSUE TITLE
Using Token in HEADER instead of query parameters

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#3141]
Could it be possible to move the usage of the token from the query parameter to a HEADER like X_JOPLIN_TOKEN or something like that, which could be little be more secure and avoiding to be exposed by intermediaries ?

**Comment by foxmask** [comment]
it could be better to avoid to be able to clearly read it in the logs

**Comment by Strubbl** [comment]
pls dont close. thanks

**Comment by foxmask** [comment]
that will be te last time I keep it opened.
After that "tant pis"

**Comment by foxmask** [comment]
any chance to see that issue revolved ? that will avoid us to let the log told "secret" things

**Comment by foxmask** [comment]
no!

**Comment by foxmask** [comment]
https://discourse.joplinapp.org/t/joplin-api-token-in-header-vs-query-parameters/12573/5
