### ISSUE TITLE
White top  and bottom bars dark theme iOS app

### ISSUE THREAD

**Issue by arkeane** [laurent22/joplin#3142]
In the iOS app part of the top and bottom bars remain white when switching to dark mode 
![IMG_0174](https://user-images.githubusercontent.com/47981941/80493462-bb949300-8965-11ea-81eb-172d6271b599.PNG)

## Environment

Joplin version: 10.0.47
Platform: iOS
OS specifics: iOS 13.4.1 on iPhone 11

## Steps to reproduce

1. Go to settings
2. Change the theme from light to dark or dark OLED

## Describe what you expected to happen

The white parts should be the same as the rest of the theme

**Comment by rabeehrz** [comment]
Hey @arkeane ,
This has been fixed via #3055 and will be released in the next update.

**Comment by arkeane** [comment]
Sorry I did not see it

**Comment by arkeane** [comment]
When will it be released?
