### ISSUE TITLE
Some mathematical symbols appear as bullets 

### ISSUE THREAD

**Issue by Ahmed-E-86** [laurent22/joplin#3145]
Whenever I add mathematical symbols like (+),  (-), and (*) at the beginning of any line, they appear as bullets.

**Example:**

![Screenshot_20200428_201437](https://user-images.githubusercontent.com/29783425/80522466-e80fd580-898c-11ea-90b5-02f5331d6b60.png)

![Screenshot_20200428_200958](https://user-images.githubusercontent.com/29783425/80522091-48524780-898c-11ea-92aa-f3540c5681a5.png)

## Environment

Joplin version: 1.0.201
Platform: Linux
OS specifics: Kubuntu 20.04

**Comment by dpoulton-github** [comment]
I believe that this is intended behaviour and not a bug as these symbols at the start of a line and followed by a space are Markdown codes for bullet points.

If you want to see them as mathematical symbols you can either omit the space or "escape" the symbol (i.e. tell Joplin it is not a Markdown code) by preceding it with a backslash.

![Markdown](https://user-images.githubusercontent.com/60117449/80528887-8e100f80-898e-11ea-8ae0-dcae5cb7740b.png)

**Comment by Ahmed-E-86** [comment]
Thanks :+1:
