### ISSUE TITLE
A missing feature

### ISSUE THREAD

**Issue by Ahmed-E-86** [laurent22/joplin#3146]
There is no ability to align the text to the right, everything is always aligned to the left side, and that is not good with languages that can be written from right to the left like Arabic, Persian, Urdu, and Hebrew.

## Environment

Joplin version: 1.0.201
Platform: Linux
OS specifics: Kubuntu 20.04

**Comment by Rahulm2310** [comment]
@Ahmed-E-86 Feature requests must be discussed in the forum instead of cluttering up the Issues.

**Comment by Ahmed-E-86** [comment]
I have just read this discussion, and I fell like it is a dead end.

Someone make a project to help Writing Markdown in Arabic >>> https://github.com/ahmadajmi/markdown-arabic
