### ISSUE TITLE
Scroll Past End in Editor

### ISSUE THREAD

**Issue by nickian** [laurent22/joplin#3147]
This is more of a feature request than a bug, but would you consider setting this option to a value that would give some bottom padding to the Ace editor used in Joplin?

`scrollPastEnd: number|boolean`

https://github.com/ajaxorg/ace/wiki/Configuring-Ace

I'm not sure if it's possible to include this as a setting in Joplin's settings. That would be even better.

**Comment by coderrsid** [comment]
I'm working on this.
/claim

**Comment by coderrsid** [comment]
Well, i tried adding `scrollPastEnd` to the ace-editor options @nickian . So, below is the gif with a value of `0.2`, does that seems like enough space? coz adding more space can make an inconsistency between the scrolling of editor / renderer. Do tell me if you think of some change! Thanks. Laurent, you too please!

![edited](https://user-images.githubusercontent.com/35633575/80585093-59549480-8a30-11ea-80f1-27491b322a76.gif)

**Comment by nickian** [comment]
That looks awesome! I just don't like it being right up against the edge.

**Comment by coderrsid** [comment]
Thanks. I'll just add a pull request.

**Comment by CalebJohn** [comment]
fixed by #3703
