### ISSUE TITLE
Joplin not working on Fedora 32

### ISSUE THREAD

**Issue by kurtis318** [laurent22/joplin#3151]
I got the following window when I tried to run Joplin on Fedora 32 today.

![image](https://user-images.githubusercontent.com/8187747/80651553-bb66c700-8a3b-11ea-84ff-31b9c9881627.png)
Not sure if this is a bug with Joplin or Fedora 32.  Would be nice to use it on my laptop again.

## Environment

Joplin version: 1.0.201
Platform: x86_64
OS specifics: Fedora 32

## Steps to reproduce

1. Run the comand-line installer for Joplin
2. Find the Jopin icon in KDE
3. Error window pops up.

## Logfile

I followed the debugging documentation and still got the same error.  The GUI never appeared.
Here is the output on the command line that results in the same error pop-up.
```
[kurtis@xps15 .joplin] $ ./Joplin.AppImage --log-level debug
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
(node:3429) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:3429) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
```

**Comment by laurent22** [comment]
What command did you run to install the app?

**Comment by kurtis318** [comment]
I used:
```
wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash
```

**Comment by jhscheer** [comment]
Hi,
I just upgraded to Fedora 32 and did a fresh install of Joplin with `Joplin_install_and_update.sh`.
I'm using Gnome not KDE, and so far Joplin works fine.

**Comment by kurtis318** [comment]
I just verified on two new installs of Fedora 32 KDE spin that Joplin does work properly.  Not sure what my original problem was but it looks like there is no bug.  Sorry for not doing better testing.

**Comment by kurtis318** [comment]
FYI.  I tried re-installing Joplin on my XPS 15 with Fedora 32.  Same issue as before.  I found this issue:  [Fatal error: unknown table: settings #2670](https://github.com/laurent22/joplin/issues/2670).  I noticed there was a reference to ~/.config/joplin-desktop.  Deleting this directory made Joplin work properly.

**Comment by boaspartes** [comment]
Hi.

I have the same error as Curtis318 in Fedora 32, Cinnamon.
