### ISSUE TITLE
Desktop :  Viewer scroll behavior

### ISSUE THREAD

**Issue by Rahulm2310** [laurent22/joplin#3152]
## Environment

Joplin version: 1.0.201
Platform: Windows
OS specifics: Windows 10

## Part 1 
The viewer adjusts it's position to top after every line. It is similar to #2702 

## Part 2
The viewer doesn't start scrolling until the editor starts to scroll. 

## Steps to reproduce

1. Add an image or create a mermaid graph
2. Start typing below it 
3. Keep typing until the img/graph is completely out of view pane.

## GIF of the issue

![mermaidissue](https://user-images.githubusercontent.com/54268438/80676541-9c684380-8ad4-11ea-9452-28e9043391cc.gif)

## Describe what you expected to happen

**Part 1**
The viewer should not adjust it's position after every new line and should scroll smoothly.

**Part 2**
Viewer should start scrolling as soon as the content starts overflowing even if the editor has not started to scroll.

**Comment by coderrsid** [comment]
Are you working on this too?

**Comment by butterflyx** [comment]
I have the same issue.
Only on pages with Mermaid diagrams in it.

OS: Win 10 home, 1903
Version: Joplin 1.0.201 (prod, win32) and 1.0.200 as well

**Comment by puckwang** [comment]
Me too...

Joplin version: 1.0.201
Platform: MacOS
OS specifics: macOS Catalina 10.15.4
