### ISSUE TITLE
Goto Anything doesn't work when typing Chinese

### ISSUE THREAD

**Issue by ylc395** [laurent22/joplin#3153]
## Environment

Joplin version: 1.0.201
Platform: macOS
OS specifics: 10.15.4

## Steps to reproduce

1. Type some Chinese characters in Goto Anything
2. Nothing show up even if delete Chinese characters and type some English characters util reopen Goto Anything

## Describe what you expected to happen
Goto Anything can work with non-English characters

## Logfile

```
/Applications/Joplin.app/Contents/Resources/app.asar/plugins/GotoAnything.min.js:215 Uncaught (in promise) TypeError: Cannot read property 'includes' of undefined
    at /Applications/Joplin.app/Contents/Resources/app.asar/plugins/GotoAnything.min.js:215
    at Array.find (<anonymous>)
    at Dialog.updateList (/Applications/Joplin.app/Contents/Resources/app.asar/plugins/GotoAnything.min.js:215)
    at processTicksAndRejections (internal/process/task_queues.js:85)
    at async /Applications/Joplin.app/Contents/Resources/app.asar/plugins/GotoAnything.min.js:160
```

This issue is maybe related to #3093

**Comment by Rahulm2310** [comment]
@ylc395 I checked it. Goto Anything is perfectly working with `arabic`, `cyrillic`and `hindi` . So it is not about all non-english characters. But yeah, there is issue with chinese

**Comment by ylc395** [comment]
@Rahulm2310 I've been checked out the source code. While search with ja, zh, ko, th, the `SearchEngine` will return a basic search result instead of a standard search result, and this breaks the code

**Comment by jivi20029** [comment]
the same .
