### ISSUE TITLE
Desktop: Mermaid rects are very tall

### ISSUE THREAD

**Issue by svalaskevicius** [laurent22/joplin#3155]
in a simple mermaid graph, the boxes are very tall. This is not the case in a standalone mermaid.

## Environment

Joplin version: 1.0.200, rev 142976f
Platform: linux
OS specifics: nixos

## Steps to reproduce

create a note with 

```mermaid
graph TD
 A
```

## Describe what you expected to happen

Box A should be of reasonable size

**Comment by coderrsid** [comment]
I see them like the exact size which is shown in the library [here](https://mermaid-js.github.io/mermaid/#/flowchart?id=an-open-link)

![image](https://user-images.githubusercontent.com/35633575/80696738-7c954780-8af5-11ea-80f2-014f33cab79a.png)

**Comment by svalaskevicius** [comment]
Hmm. I'll play around a bit more then, will reopen the ticket if it looks it's not some other local config. Thanks :)

**Comment by svalaskevicius** [comment]
![2020-04-30-120849_2272x542](https://user-images.githubusercontent.com/893660/80703829-6aa6ab00-8adb-11ea-90a9-842783ff0ce0.png)

All default settings, not sure what else could impact it.

I'm using nixos btw - could packaging have affected it?

**Comment by coderrsid** [comment]
Maybe, i don't have much idea about Linux related stuff. But @bedwardly-down , can you please help him if it's related to nixos. Thanks.

**Comment by bedwardly-down** [comment]
@svalaskevicius, are you running the version released from the Joplin repo directly or one released by your package manager? If the latter, they may have done something funky with it that is beyond my personal knowledge.

I'm on Artix Linux and this is what I'm getting:

![2020-04-30-100815_1919x1079_scrot](https://user-images.githubusercontent.com/59133880/80726964-b9981480-8aca-11ea-9d05-375c1cc0affb.png)

Another possibility is that your system's default font might not be monospaced. If that's the case, you would need to change it. I personally love the Hack Nerd Mono Font, but a favorite among many users is FiraCode. :D

**Comment by Westie1012** [comment]
I'm having the same issue on Linux Mint and my default font is ubuntu mono.

**Comment by Rahulm2310** [comment]
I can confirm this on Windows as well

**Comment by svalaskevicius** [comment]
Btw I checked the svg using inspector, it actually has high height values on the boxes. So would be natural to blame mermaid, however running mermaid alone works OK.

So are there any parameters/config passed to mermaid that confuse it? Also I only tried the latest mermaid from git, could it also be a problem in some earlier version that's used in joplin?

**Comment by bedwardly-down** [comment]
If it is that, it’d very likely be an issue with the library Joplin uses to integrate mermaid support.

**Comment by coderrsid** [comment]
Exactly! We're here just rendering the graphs using library named mermaid-js. All the internal style props of graphs are from there.
