### ISSUE TITLE
Problem with tags for duplicate note

### ISSUE THREAD

**Issue by blowin** [laurent22/joplin#3157]
When you make duplicate note and start remove tags. The record on the basis of which the copy was made loses all the tags.

Joplin 1.0.201 (prod, win32)

**Comment by G1TE5H** [comment]
I tried to reproduce this but my duplicated note doesn't have any tags.
@laurent22  What is the right behavior for this?

Using Joplin 1.0.201 (prod, win32)

**Comment by Rahulm2310** [comment]
I think tags from the original note are not added to duplicate ones

**Comment by jyuvaraj03** [comment]
> I tried to reproduce this but my duplicated note doesn't have any tags.

Yep, that seems to be the behavior. I looked at the code and it looks like the tags were not copied at all to the duplicated note. 

Still not sure if it's intended by Laurent though. But, I would actually expect the duplicated notes to have the tags duplicated too.

**Comment by G1TE5H** [comment]
> But, I would actually expect the duplicated notes to have the tags duplicated too.
Same

@blowin Share the steps, so we can reproduce.

**Comment by blowin** [comment]
I tried to reproduce and understood. Tags disappear from the main record when I transfer the duplicate to another book.

**Comment by blowin** [comment]
I tried to reproduce and understood. Tags are not copied to duplicate.

**Comment by lcmar** [comment]
That 's an important issue for me. When we duplicate a note, tags need to be copied to the new note.

**Comment by lcmar** [comment]
I appreciate the good work you have done with Joplin. I'm mutch better organized with both desktop and android apps.

Problems identified:
 - When a note is duplicated it losts its tags.
 - When there is a tag selected (in the toggle sidebar) and a note is dragged into another tag , the note keeps the original tag. Shouldn´t is be removed? Or at leats, it would be nice if there is a way to remove it (holding down shift ou ctrl, e.g).
