### ISSUE TITLE
Export Human-readable Filenames and Folders

### ISSUE THREAD

**Issue by janmattfeld** [laurent22/joplin#316]
### Operating system

- [x] Windows
- [X] macOS
- [X] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [X] Terminal

### Problem

I see how the current file naming is required by Joplin. This is not a duplicate of #278 or #264.

However, my main motivations to use Joplin are openness and thus, portability.

Yet, the cryptic, non-human-readable file naming makes it impossible to use my notes with any other application in a sane way–I am just a lost as with any other proprietary note-taking tool.

### Goal

Using the export function to:

1.    Create a plain text backup, usable without additional software
2.    Get my notes conveniently out of Joplin in case I finally switch to another app

### Proposal

There could be an **additional**, clean export option, preserving custom naming within

1. Notebooks as folders and
2. Notes/To-dos as separate files.

Knowing, with the current sync and import/export functions, there is no way to conveniently view them again in Joplin. (Too bad.)

**Comment by laurent22** [comment]
Yes but once it's exported it won't be possible to view these notes again Joplin (since it won't be possible to match a file back to its original note), is that not an issue?

**Comment by janmattfeld** [comment]
Correct. With the current sync and import/export functions, there is no way to conveniently view them again in Joplin. And that's too bad.

But I would rather use the clean export function to:

1. Create a plain text backup, usable without additional software
2. Get my notes conveniently out of Joplin in case I finally switch to another app

**Comment by laurent22** [comment]
Have you had a look at the raw format export? It's already quite straightforward, expect indeed the filenames which are just id.md

**Comment by janmattfeld** [comment]
Yes, and I realize, the first line of each file contains my note or notebook name. So it would be easy to write a script, renaming each file. While doing that, I'd need to detect folders first and sort all corresponding files into them. Also, taking care of identical names...

Thanks to the open format that's manageable. But I would rather expect Joplin to do it, at least as an export.

**Comment by laurent22** [comment]
Fair enough, that would indeed make sense to have this option part of the app. Marking it as "good first issue" since it's relatively straightforward to implement.

**Comment by domoenergytics** [comment]
To have the best human readable data, an HTML export will be appreciable.
Having a read only web page with tree structure of notebook & notes, notes content being visible with a click on the note title.

**Comment by janmattfeld** [comment]
@domoenergytics HTML export is another issue. 

Here I really just ask to export
1. Notebooks as folders and
2. Notes/To-dos as separate files

Both preserving my custom cleartext names.

**Comment by laurent22** [comment]
That was implemented.
