### ISSUE TITLE
typora: picgo upload image failed

### ISSUE THREAD

**Issue by konglhui** [laurent22/joplin#3163]
1. Failed to open typora in joplin using picgo to upload image.
![图片](https://user-images.githubusercontent.com/33919041/80950915-635c0600-8e29-11ea-8603-0573d996db09.png)

2. open typora desktop ,Image can upload succeed.
![图片](https://user-images.githubusercontent.com/33919041/80950988-8b4b6980-8e29-11ea-8a25-3e579a7044df.png)

I don't know what append.

**Comment by luckyfatpig** [comment]
this bug still not fixed in version 2.4.12
