### ISSUE TITLE
Joplin Web Clipper

### ISSUE THREAD

**Issue by 14SHIKE** [laurent22/joplin#3167]
Please save web pages and screenshots from mobile  browser,not just desktop app

**Comment by dpoulton-github** [comment]
This isn't really a **bug** for the Joplin Web Clipper as the Web Clipper is a desktop browser feature only.

This seems to be more a feature request and should really be posted on the [Joplin forum](https://discourse.joplinapp.org) so as to leave the GitHub Issues list for confirmed bugs and to try to keep the list under control.

Please don't be disappointed if one of the devs just closes this issue.
