### ISSUE TITLE
Sync to "file system" targeting a directory within a local cloud folder?

### ISSUE THREAD

**Issue by datashow** [laurent22/joplin#3168]
I have tried to sync through OneDrive and Dropbox, and both had issues.

My question is, since we can choose to sync to "File system", is it OK for me to just set the directory to be a folder within my local cloud folder, such as "*/Dropbox/Joplin" or "*/Onedrive/Joplin"?

The reasoning of this is that the syncing will no longer go through the OneDrive or Dropbox API, so we won't receive weird error messages like "the maximum request length supported is 4mb", and OneDrive / Dropbox can still sync the data to the cloud as regular files.

I tested this on my desktop and it seems to be working. Not sure if there is any hidden issue with it, such as conflicting?

The apparent downside of this is that it may not work on mobile devices, but I guess I can live with that.

**Comment by what-name** [comment]
I use MEGA for syncing and I do exactly this. I also have a sync setup for the `joplin-desktop` folder in order to sync my attachments (resources) and .css configs as well between computers. Been working great for a while now.

**Comment by laurent22** [comment]
For support please use the forum
