### ISSUE TITLE
Synchronization error Seafile

### ISSUE THREAD

**Issue by brusapa** [laurent22/joplin#3169]
Hello everyone,

I have been using Joplin for about two months without problems, and I think it is a really nice software. However, since a few days ago I'm experiencing synchronization issues.

This is the error that I get when I use the "Check synchronization configuration"
```
Error. Please check that URL, username, password, etc. are correct and that the sync target is accessible. The reported error was:
PROPFIND : Unknown error 2 (502): <!DOCTYPE html> <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]--> <!--[if IE 7]> <html class="no-js ie7 oldie" lang="en-US"> <![endif]--> <!--[if IE 8]> <html class="no-js ie8 oldie" lang="en-US"> <![endif]--> <!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]--> <head> <meta http-equiv="refresh" content="0"> <title>sea.brusapa.com | 502: Bad gateway</title> <meta charset="UTF-8" /> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" /> <meta name="robots" content="noindex, nofollow" /> <meta name="viewport" content="width=device-width,initial-scale=1" /> <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" /> <!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]--> <style type="text/css">body{margin:0;padding:0} (Code 502)
```

I haven't changed the configuration since the first day, so I'm guessing that the problem has nothing to do with the synchronization settings.

## Environment

Joplin version: 
Joplin 1.0.201 (prod, win32)

Client ID: 2765cd4e3fd74ac4a1db4b3ea1cb6972
Sync Version: 1
Profile Version: 28

Revision: e65af8c1 (master)

Platform: Microsoft Windows 10 Pro x64
OS specifics: Version	10.0.18363 Build 18363

Synchronization server:
It's a [Seafile Server](https://www.seafile.com) Version 7.1.3 running in a [docker container](https://hub.docker.com/r/seafileltd/seafile-mc), behind a [Traefik](https://docs.traefik.io) reverse proxy, also running in a [docker container](https://hub.docker.com/_/traefik).
I'm also using Cloudflare services in front of that Traefik.

Synchronization settings:
- Target: WebDAV
- WebDAV URL: https://sea.mydomain.com/seafdav/Joplin
- WebDAV username: my seafile user
- WebDAV password: my seafile password

## Describe what you expected to happen

The notes sync correctly with my WebDAV server.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/4584950/log.txt)

**Comment by roman-r-m** [comment]
`502: Bad gateway` looks like a server-side issue to me. Have you checked traefik or seafile logs for any issues?

**Comment by brusapa** [comment]
You are totally right, I had the address checked through a web browser, initially thinking that was a Traefik problem, and since it worked I thought it was a Joplin problem. But now I have noticed I can access to seafile, but not to the /seafdav path...

Sorry for not minding this before opening the issue...

Thank you very much!
