### ISSUE TITLE
Evernote Import - issue with image

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#317]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

After having imported my notes, some of them display the images that illustrate the article, at the bottom of the note intead of inside of the note where they should be.

In case I can provide snapshot of those notes.

**Comment by laurent22** [comment]
Yes if you have an example of ENEX file I could test, please post it here.

**Comment by foxmask** [comment]
to avoid to flood the issue I pasted one note here https://gist.github.com/foxmask/35e0c4bdebdafdfed5d7774b1c8bef95

**Comment by laurent22** [comment]
Thanks for the note sample, that should be fixed in the latest version.
