### ISSUE TITLE
Goto Anything: Keyboard selection starts at bottom of visible results

### ISSUE THREAD

**Issue by thororm** [laurent22/joplin#3170]
## Environment

Joplin version: v1.0.201
Platform: Windows
OS specifics: 10

## Steps to reproduce

1. Open Goto Anything search
2. Enter a search term where the number of results triggers the scrollbar
3. Press the arrow up or down key
4. The selection will be at the bottom of the result list

## Describe what you expected to happen

That the first element of the results is highlighted/selected.
The same as the behavior with search terms that do not trigger the scrollbar.

**Comment by naviji** [comment]
Can't reproduce.
![test](https://user-images.githubusercontent.com/30305957/81284227-76661480-907b-11ea-8d05-a26c357f8819.gif)

**Comment by Rolograaf** [comment]
I can reproduce since I reported this bug on the forum https://discourse.joplinapp.org/t/strange-goto-anything-behavior/8139/3

**Comment by naviji** [comment]
Okay, can give me some more details.

For example, in this issue, it says that the up or down arrow keys are causing the problem.
In the forum, the "enter" key is causing the problem.

Also, does the selection always go to the 16th entry (last?) or does it change? 
Try adding what you searched for in the note body. Does it change the selection position?

**Comment by ylc395** [comment]
I have located the problem. `selectedItemId` is reused between two calls of `updateList`. I will submit a PR to fix this.
