### ISSUE TITLE
Version wrong after update

### ISSUE THREAD

**Issue by ShaneCarr** [laurent22/joplin#3173]
## Environment

Joplin 1.0.199 (prod, linux)
Client ID: 20561063b4ac44b8bf330077e7724115
Sync Version: 1
Profile Version: 28
Revision: 53a857b (master)
## Steps to reproduce

1. take  v1
2. check for update and download
3. swap/update the appimage file
4. continues to report previous version.

**Comment by dpoulton-github** [comment]
Possible explanation where the appimage launcher caches the previous appimage of the same name?

https://discourse.joplinapp.org/t/desktop-app-version-issue/8020
