### ISSUE TITLE
[Terminal App] Map a key to nothing (or overwrite it)

### ISSUE THREAD

**Issue by BaksiLi** [laurent22/joplin#3174]
## Environment

Joplin version: joplin 1.0.163 (prod)
Platform: **terminal**
OS specifics: macOS Catalina

## Steps to reproduce

This is a BUG/Feature request.

I usually use Joplin in a TMUX panel alongside with my project, so that I can switch between the two. Switching panels in TMUX has the default keymap `CTRL_V <direction>`, where `<direction>` being HJKL.

Since Joplin terminal app takes `CTRL_H` for delete the note, sometimes I mistakenly trigger it when I want to switch panel. So I decided to **map `CTRL_H` to something else or nothing so that I will not accidentally delete a note**.

However, it appears to me that Joplin can neither map a key to nothing nor overwrite a keymap in `keymap.json`.

## Describe what you expected to happen

I want to be able to unmap a key, or overwrite a key that's been preoccupied.

## Logfile
<img width="1257" alt="Screenshot 2020-05-06 at 22 20 15" src="https://user-images.githubusercontent.com/26314680/81229537-e460fc00-8fe7-11ea-8ceb-91697eea4b7c.png">

**Comment by keks24** [comment]
It would be nice, if this could be implemented.

I am trying to overwrite `r restore $n` with `r ren $n`, but it seems, that the [`hardcoded shortcuts`](https://joplinapp.org/help/apps/terminal/#shortcuts) always have precedence.

`${HOME}/.config/joplin/keymap.json`:
```json
[
    [...]
    { "keys": ["r"], "type": "prompt", "command": "ren $n \"\"", "cursorPosition": -2 }
]
```


```bash
> :help "keymap"
[...]
r      restore $n
[...]
r      ren $n ""
```

---

System information

<details><summary>Expand</summary><p>

### Joplin version
```bash
$ npm list --global joplin
/home/<some_username>/.local/lib64
└── joplin@3.6.2
```

### Platform
```bash
$ uname --all
Linux <some_hostname> 6.18.39-gentoo #1 SMP PREEMPT_DYNAMIC Mon Jul 27 15:32:24 CEST 2026 x86_64 Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz GenuineIntel GNU/Linux
```
</details></p>
