### ISSUE TITLE
Creating a new note deletes current note from view history

### ISSUE THREAD

**Issue by RobAlexander** [laurent22/joplin#3177]
## Environment
Joplin version: 1.0.201
Platform: Windows 
OS specifics: Windows 10 build 18362

## Steps to reproduce
1. Observe which note you are currently viewing
2. ctrl-N to create a new note
3. Set title 
4. Click back button in note toolbar
5. Observe that you are now on a different note to that observed in (1)
6. Play around with back/forward, and observe that the note from (1) has disappeared from the view history

## Describe what you expected to happen
At (5), you should be back at the note from (1)

**Comment by laurent22** [comment]
The back/forward buttons are being redone, so that issue should be solved.
