### ISSUE TITLE
UI issue - back button moves around

### ISSUE THREAD

**Issue by RobAlexander** [laurent22/joplin#3178]
Sometimes I try to click "back" several times in a row, to reach a note I was viewing several transitions ago, and on the the second or later click a dialog pops up saying "Insert Hyperlink". That's because sometimes notes are shown with an "In:<notebook name>" label, and sometimes they're not, so the position of the back button varies between notes.

NB a keyboard shortcut for "back" would mostly remove this problem for me.

## Environment
Joplin version: 1.0.201
Platform: Windows 
OS specifics: Windows 10 build 18362

## Steps to reproduce
1. Run a search that will include notes in multiple notebooks
2. Click "back"
3. Click again where "back" was before your previous click
4. Observe the dialog that appears

## Describe what you expected to happen
On (3), the icon under my mouse pointer is still "back"
On (4), I am viewing the next page back in the history

**Comment by laurent22** [comment]
The back/forward buttons are being redone, so that issue should be solved.
