### ISSUE TITLE
Different todo checkbox behavior in Android vs Desktop

### ISSUE THREAD

**Issue by hackhowtofaq** [laurent22/joplin#3179]
Hello

In desktop version when you are editing a checkbox and press enter a new checkbox appears in the new line.

![joplin](https://user-images.githubusercontent.com/1138336/81379579-0b1b5180-9112-11ea-9e68-a2f8502efe99.gif)

This is not happening on Android version.

Thank you

**Comment by hackhowtofaq** [comment]
It still requires the community's attention

**Comment by hackhowtofaq** [comment]
It still requires the community's attention

**Comment by vmichals** [comment]
This would improve the usability on Android significantly!

**Comment by hackhowtofaq** [comment]
I agree but no luck.

**Comment by pkoevesdi** [comment]
I agree too. Typing "- [ ] " on Android for every line of my shopping list is a pure pain and renders the checkbox feature almost useless.
Would be easier, if #1397 would not have been closed. :-(
See also #1419. The arguments of a small screen size are simply wrong. other apps (Google keep) show, it's possible. You could put an item "add checkboxes to list" in the menu, for instance.

**Comment by lciti** [comment]
Is there any progress on this? I agree that something to speed up entering lists on mobile would be very useful. Either this or the toolbar.
