### ISSUE TITLE
Does the software not have bulk import function

### ISSUE THREAD

**Issue by AceCandy** [laurent22/joplin#3182]
Can only be imported individually
on MacOS

**Comment by roman-r-m** [comment]
File - Import - MD Markdown (Directory) will import all files from a directory. Is that what you're looking for?

**Comment by AceCandy** [comment]
but I used to use a enernote ，the exported format is enex 😥

**Comment by roman-r-m** [comment]
There are 2 different options to import enex? Are they both not working for you?

**Comment by AceCandy** [comment]
Single import successful，but  I have hundreds of files。。。It's hard to deal with

**Comment by roman-r-m** [comment]
It's been a while since I've last used Evernote but I think you can export all your notes to a single enex file and import it to Joplin

**Comment by AceCandy** [comment]
Maybe it's because of the leanote I used before, it exported multiple files. .
