### ISSUE TITLE
Drag & Drop Reorder Functionality

### ISSUE THREAD

**Issue by mlphresearch** [laurent22/joplin#3184]
While it is possible to drag-and-drop notes from one notebook to another, it would great if you could also manually reorder both notebooks and notes by simply dragging them to a new location. This would be additional to the "Sort by" functionality.

Apologies for not raising this on the forum.

**Comment by rabeehrz** [comment]
Probably should raise this on the forum before opening up an issue here. 😅

**Comment by javvylim** [comment]
Same! Would love to have a functionality on drag and drop reorder!

**Comment by mlphresearch** [comment]
Relevant thread on the forum: https://discourse.joplinapp.org/t/is-there-a-way-to-reorganize-notes/5676
