### ISSUE TITLE
webdav connect 403

### ISSUE THREAD

**Issue by AceCandy** [laurent22/joplin#3185]
Previously connected successfully,but after using baiduyunCDN, I can't connect,the website can be opened normally. Seeking a solution
![image](https://user-images.githubusercontent.com/6278583/81470841-9b938800-921f-11ea-9144-ea78d1d0868f.png)

**Comment by ylc395** [comment]
这是 CLI 版本的？你具体怎么配置的

**Comment by AceCandy** [comment]
就是正常下载的桌面版本最新版(1.0.201)  之前是用起来是没问题的  今天在服务器上使用了百度云的cdn  然后报错了

**Comment by ylc395** [comment]
你是自己架设的同步服务？

**Comment by AceCandy** [comment]
对，用的 cloudreve

**Comment by ylc395** [comment]
你是把这个云盘系统部署在公网上，并通过百度云给这个域名加速吗？

**Comment by AceCandy** [comment]
对   就是很正常的自建dav  然后之前用的好好的  加了百度云cdn就不行了  不知道是为啥

**Comment by ylc395** [comment]
<img width="679" alt="图片" src="https://user-images.githubusercontent.com/12264626/81472596-b7049000-922b-11ea-83b0-5c25ce979523.png">

你在这里把完整的报错信息贴出来看看

**Comment by AceCandy** [comment]
上面的图就是完整的信息了

![image](https://user-images.githubusercontent.com/6278583/81473106-03050400-922f-11ea-8c21-4f953c5a21f9.png)

**Comment by sulisu** [comment]
It seems that the webdav server didn't reply correctly. Can you access it with web browser or other webdav clients, such as the winscp, normally?

**Comment by AceCandy** [comment]
I didn't think of a good way.
Finally I closed cdn,now normal

**Comment by AceCandy** [comment]
I found out the reason！
Because I opened the general security protection of baiduyunCDN.
The problem was solved after I closed
