### ISSUE TITLE
Nextcloud dav errors

### ISSUE THREAD

**Issue by jorgensoares** [laurent22/joplin#319]
### Operating system

- [ ] Windows
- [X ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

Hello, 

First of all nice work!! :) Second I found what I believe are 2 bugs:
These are both using nextcloud as backend for data store

1 - Every time I change the user password I need to restart the client on the mac to pass takes effect.. this can lead to looks on nextcloud side due to the brute force feature of nextcloud.

2 - I see a lot of this type of errors on nextcloud log when the client is synchronizing:
  | Sabre\DAV\Exception\MethodNotAllowed: The resource you tried to create already exists/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 590:  Sabre\DAV\Server->createCollection('files/jorge/Not...', Object(Sabre\DAV\MkCol))[internal function] Sabre\DAV\CorePlugin->httpMkcol(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:  call_user_func_array(Array, Array)/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:  Sabre\Event\EventEmitter->emit('method MKCOL', Array)/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:  Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/html/nextcloud/apps/dav/lib/Server.php - line 283:  Sabre\DAV\Server->exec()/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:  OCA\DAV\Server->exec()/var/www/html/nextcloud/remote.php - line 164:  require_once('/var/www/html/n...'){main}
-- | --

All the configurations are standard following the docs provided.

Thanks

**Comment by laurent22** [comment]
> 1 - Every time I change the user password I need to restart the client on the mac to pass takes effect.. this can lead to looks on nextcloud side due to the brute force feature of nextcloud.

Yes it's actually already fixed and will be part of the next release.

> 2 - I see a lot of this type of errors on nextcloud log when the client is synchronizing:

This is working as expected. The synch algorithm doesn't check if the directory exists but attempts to create it and if there's this error it is simply ignored. So it's a bit annoying that this error (which is not really one) appears in the log but not much can be done about it.

**Comment by jorgensoares** [comment]
Hi Laurent! thank you I will test then the fix. Yes regarding the error It does not affect the NC installation as you said is just annoying and scary to see all those `fatal` messages :D

**Comment by laurent22** [comment]
Yes it is. I wonder if this is kind of a Nextcloud bug since creating a directory that already exists is not exactly a "fatal" error, it should basically be a no-op.
