### ISSUE TITLE
Please consider updating Mermaid to 8.5.1

### ISSUE THREAD

**Issue by deftdawg** [laurent22/joplin#3193]
As of May 10, 2020, Joplin is built against Mermaid 8.4.6

```json
ElectronClient/package.json:147:    "mermaid": "^8.4.6",
ReactNativeClient/package.json:48:    "mermaid": "^8.4.6",
```

I'm working on Use Case diagrams and would like to make use of the "autoNumber" keyword added to Mermaid in releases [after 8.4.6](https://github.com/mermaid-js/mermaid/issues/1257).   The use of this word breaks rendering inside Joplin (though it does work with [Markdown Preview Mermaid Support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid) plugin for vs code).

Please consider updating, thanks! 😄 

![image](https://user-images.githubusercontent.com/4991612/81509786-1f5e7a80-92db-11ea-9eed-5f3e777d6cb2.png)

**Comment by deftdawg** [comment]
A little bit more complicated then just updating package.json files it seems...

[ElectronClient/pluginAssets/mermaid/mermaid.min.js](../blob/master/ElectronClient/pluginAssets/mermaid/mermaid.min.js) is actually a static copy of mermaid "version":"8.4.6" from [Joplin's git](https://github.com/laurent22/joplin/commit/1d14c8a706822deda19fdbdbafe8eae1460b9e1b#diff-b261bbd882d7de221bd2b6b68bda62f8) placed there by [ElectronClient/tools/copyPluginAssets.js](../blob/master/ElectronClient/tools/copyPluginAssets.js) from [ReactNativeClient/lib/joplin-renderer/assets/mermaid/mermaid.min.js](../blob/master/ReactNativeClient/lib/joplin-renderer/assets/mermaid/mermaid.min.js)

I would think this should probably be sourced from the mermaid node_modules directory at build time.

**Comment by deftdawg** [comment]
Copying over all the old versions of mermaid.min.js I was able to get it to render properly:
![image](https://user-images.githubusercontent.com/4991612/81511978-170e3b80-92eb-11ea-9d2f-caec43f09172.png)

**Comment by roman-r-m** [comment]
If you've managed to updagre it why don't you just create a pull request?

**Comment by deftdawg** [comment]
@roman-r-m  Copying over the files resolves the symptoms but doesn't address the underlying problem of how mermaid is not being upgraded when the build deps change.   When I have a bit more time I'll mess around with modify with changes on a clean branch and see if I can fix it properly... then I'll PR it.

**Comment by deftdawg** [comment]
Still a problem...

Remove stale
