### ISSUE TITLE
When switching between WYSIWYG and oder editor [toc] is replaced by normal link list

### ISSUE THREAD

**Issue by TiberiusRegenschein** [laurent22/joplin#3194]
Joplin 1.0.201 (prod, win32)

Client-ID: 24f5a6aa3d414d23862ada6e923d8107
Sync-Version: 1
Profil-Version: 28

Revision: e65af8c1 (master)

## Steps to reproduce

1. Add [toc] on plain editor
2. Move to WYSIWYG editor => Display as expected
3. Go back to plain editor => [toc] is replaced with link list

Thanks for fixing

**Comment by laurent22** [comment]
Please see Plugin screen in Option panel
