### ISSUE TITLE
Error syncing with local nextcloud server

### ISSUE THREAD

**Issue by rkyleg** [laurent22/joplin#320]
### Operating system

- [ ] Windows
- [x ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x ] Desktop
- [ ] Mobile
- [ ] Terminal

I am getting an error when trying to sync with a local nextcloud server. 
The synchronization check succeeds in the General settings page.
Screenshot of error is attached. 
<img width="564" alt="nextcloud_sync_error" src="https://user-images.githubusercontent.com/4260414/37745857-3fc9eb7c-2d45-11e8-92fe-6d60c5784888.png">

**Comment by laurent22** [comment]
Is that using a self signed certificate?

**Comment by rkyleg** [comment]
No, it is a bare http endpoint. I am able to load Nextcloud in the browser at that address and also ping it.

**Comment by laurent22** [comment]
I wonder if it's due to the non standard port. Do you have any way to test with port 80 just to confirm?

**Comment by rkyleg** [comment]
You were right about the non standard port. I dont get any errors now when syncing; however, my remote items do not show up in Joplin desktop. They do show up in the sync_items table in the database and the tags seem to sync fine, just not the folders and notes from the remote.
<img width="334" alt="joplin_desktop" src="https://user-images.githubusercontent.com/4260414/37867976-d8f7c7e0-2f6d-11e8-8c73-d7a1ce7b069b.png">
<img width="845" alt="sync_items" src="https://user-images.githubusercontent.com/4260414/37867977-d90a5dec-2f6d-11e8-90d3-3fd237d398b8.png">

**Comment by laurent22** [comment]
If you enable debug mode, is there any other error in the log? https://github.com/laurent22/joplin/blob/master/readme/debugging.md

If there are entries in sync_items it means the notes are there, but maybe their parent folder hasn't been synced yet.

**Comment by rkyleg** [comment]
No other errors when syncing. I reinstalled and imported my notes from jex and things seem to be working so far. However, I am still using port 80, so there may still be an issue with non-default ports.

**Comment by laurent22** [comment]
I cannot replicate this but the issue was indeed probably the non-default port.
