### ISSUE TITLE
Joplin 1.0.207 breaks inserting images

### ISSUE THREAD

**Issue by Gamegenorator** [laurent22/joplin#3200]
As of Joplin 1.0.207 when trying to paste an image with ctrl+v, dragging and dropping an image into Joplin, or even clicking the "attach file" button in the toolbar and locating the image manually, the main view goes white and Joplin becomes unresponsive until forced to restart through the icon in the tray.

![image](https://user-images.githubusercontent.com/38223298/81595471-5da97780-9377-11ea-999d-1b95d608374c.png)

## Environment

Joplin version: 1.0.207
Platform: Windows 10
OS specifics: Win 10 1909 Feature Update

## Steps to reproduce

1. Copy and image to the clipboard
2. Attempt to paste the image in Joplin

## Describe what you expected to happen

The image will be attached to the note

## Logfile

There are no errors that display in log.txt, however when creating a flags.txt and watching the console 3 errors show up when attempting to add an image:

![image](https://user-images.githubusercontent.com/38223298/81596821-90ed0600-9379-11ea-951e-30fe4c4f92a3.png)

![image](https://user-images.githubusercontent.com/38223298/81596852-9a766e00-9379-11ea-939e-2067f421b0f4.png)

![image](https://user-images.githubusercontent.com/38223298/81596952-c2fe6800-9379-11ea-8a34-a3fb755376d4.png)

Here is a txt containing the pasted errors so that you can find and search in necessary: 
[Errors.txt](https://github.com/laurent22/joplin/files/4611376/Errors.txt)

My knowledge of NodeJS, NPM, React, Electron, etc varies from extremely little to nonexistent so I may not be much help beyond this point, but I'll do my best to provide more data in necessary.

**Comment by laurent22** [comment]
I can't replicate this. Does it happen all the time for you?

**Comment by Gamegenorator** [comment]
@laurent22 Yes, it happens every time on both my Windows systems.

**Comment by Gamegenorator** [comment]
Something I've just noticed while doing more extensive testing, it's working fine if I attempt to attach images to notes that are located within a standalone notebook. I only the get the problem if I attempt to attach an image to a notebook that's nested within several other notebooks.

So attaching an image to a note in my "Inbox" notebook works fine. While attaching an image to a note that's located within "School" -> "Science" -> "Earth and the universe" -> "Physics and chemistry" causes the problem.

But I have images that have been added to notes in this notebook from 1.0.206 that are still there and still work as intended, so something about 1.0.207 causes an error when adding images to notes in nested notebooks while showing images added to the same note in previous versions on Joplin just fine.

**Comment by laurent22** [comment]
Does it happen if you disable "Show note counts" in Options > General > Advanced Options?

**Comment by Gamegenorator** [comment]
@laurent22 Yes, it appears to have no affect whether it is on or off.

**Comment by laurent22** [comment]
Would you be able to export a notebook that can be used to replicate this problem?

By the way, what resource download mode do you use? And do you have encryption enabled?

**Comment by Gamegenorator** [comment]
[Link to reproducible copy in .jex format](https://send.firefox.com/download/dc72f67a26903c04/#my4E8SjZH-fSjPMwpNI7gg)

I imported that .jex file onto my other Windows system and found the bug 100% reproducible. I then imported the file in Joplin on an Ubuntu VM and was enabled to reproduce the bug in any form. I don't own a Mac but I would assume if it doesn't work on Linux it won't work on Mac.

After further testing I found the reason I thought it was related to notebook nesting was entirely inaccurate and can be replicated simply by having text above and below where you attach the image. The only thing I haven't found is exactly how much text is required before it the problem occurs.

I have encryption enabled and am using Dropbox as my sync target. I use `Always` download mode on the laptop I first discovered the issue with, and `Auto` download mode on the desktop I was able to reproduce it on.

**Comment by Gamegenorator** [comment]
As a more permanent link (And for archival purposes), I put the .jex in a zip which allowed me to upload it to github directly.

[Image Attachment Error Demo.zip](https://github.com/laurent22/joplin/files/4620072/Image.Attachment.Error.Demo.zip)

**Comment by roman-r-m** [comment]
Yep, I'm getting the same error with your JEX file.

**Comment by laurent22** [comment]
Thanks for the sample file @Gamegenorator. I can replicate on v207 but cannot anymore on the latest dev version so I think I might have fixed it as I've changed several things related to resource attachment in the latest version. So let's close it for now and if it happens again with the coming version, please let me know.

**Comment by Gamegenorator** [comment]
@laurent22 v209 appears to have solved to issue if you copy and paste the image into Joplin with the usual ctrl+c and ctrl+v, However both dragging and dropping an image into Joplin and attaching a file with the button in the toolbar still causes the problem. 

The criteria for how much text needs to be in the note before attaching the image causes the problem does not appear to have changed so it won't be necessary to upload a 2nd sample file.

**Comment by AllFunThing** [comment]
in v209, i have same issue.

![joplin_drag_image](https://user-images.githubusercontent.com/50653394/82308074-3fd5b580-99fc-11ea-9ca9-e61a353453ea.gif)
image drag and drop, then it's look like freeze.

![cap_img_019](https://user-images.githubusercontent.com/50653394/82308171-5f6cde00-99fc-11ea-8d2d-4ed5db951bb1.png)

![cap_img_020](https://user-images.githubusercontent.com/50653394/82308564-ec179c00-99fc-11ea-893b-92d60f6874a6.png)

and

[log.txt](https://github.com/laurent22/joplin/files/4649360/log.txt)

**Comment by sttrebo** [comment]
Still there in 1.0.211

**Comment by Gamegenorator** [comment]
It does appear at least that there has been no change in v211 compared to v209 regarding the image attachment bug.

**Comment by Gamegenorator** [comment]
There still appears to be no change in v212

**Comment by Gamegenorator** [comment]
In v214, ctrl+c and ctrll+v is still working. Attaching with the "Attach file" button in the toolbar has been fixed (It does add a full 2 lines above and below the reference, which is odd, but minor). And Dragging and Dropping mostly works, there is no crash, but it automatically places the images reference at the top of the markdown file instead of where the cursor was when the image was dragged and dropped, again, odd, but minor.

**Comment by Gamegenorator** [comment]
I don't know if this issue is still being monitored but there is no change regarding image attachments in v216 compared v214, meaning dragging and dropping images still throws to reference image at the top of the markdown file in the instead of where the cursor was when the image was dragged and dropped.

**Comment by Veyska** [comment]
Also seeing the drag-and-dropped images inserting at the top of a note behavior as well, FWIW.  On 1.0.216, not sure if I had the same behavior in 214 though.

**Comment by zxy960307** [comment]
Today it still exists.Anyone could fix it?
