### ISSUE TITLE
Render Mermaid diagrams with Dark theme when darker Joplin themes are on

### ISSUE THREAD

**Issue by deftdawg** [laurent22/joplin#3201]
Mermaid supports a dark theme that would be a bit easier on the eyes (less extreme contrast) when Joplin's darker themes are active.

Not sure how easy it would be to do with Joplin, but in vs code studio's [mermaid markdown preview](https://github.com/mjbvz/vscode-markdown-mermaid) plugin's the code that changes themes is here:
https://github.com/mjbvz/vscode-markdown-mermaid/blob/master/page.js

Here's how Joplin with a dark theme currently renders Mermaid diagrams:
![image](https://user-images.githubusercontent.com/4991612/81636468-f248bf80-93e1-11ea-8387-8f81412be53c.png)

Here's what VS Code Markdown Mermaid looks like with a Dark theme applied:
![image](https://user-images.githubusercontent.com/4991612/81636546-2328f480-93e2-11ea-95ff-c149c0baa2be.png) 

(The black on black title is a [mermaid bug](https://github.com/mermaid-js/mermaid/issues/1399))

**Comment by YusufMavzer** [comment]
I would love to see this feature get implemented

**Comment by DawMatt** [comment]
This would be useful. It would also be great to have a way to specify the default theme used by the Mermaid plugin, so we could update it even if swapping to dark theme wasn't automated.

**Comment by itpropaul** [comment]
Please look into this. I'd love to use mermaid, but want it to be easy on the eyes with dark mode, otherwise I may pass.

**Comment by jasonwilliams** [comment]
I would be keen to see this

**Comment by deftdawg** [comment]
No stalebot, the issue remains present

**Comment by deftdawg** [comment]
...

**Comment by personalizedrefrigerator** [comment]
This would be very nice to have.
