### ISSUE TITLE
v207 - lot of clickable boxes crash joplin

### ISSUE THREAD

**Issue by kreisklasse** [laurent22/joplin#3205]
## Environment
Joplin 1.0.**207** (prod, win32) - **Portable Version**
Sync-Version: 1
Profil-Version: 29
Revision: 22b58886 (master)
 
Platform: Windows 10 - 1909 - 64bit

## Problem
when opening a note with a lot (about 50+) of 
`- [ ]`
Joplin screen blanks out and only shows the menu bar (see picture attached)
Menu bar is unresponsive, only "Exit" in menu works, all others show no response.

Last working version for me is 201. I can't go back to 201 on this computer , cause Joplin says something about an updated database which can not work in 201 anymore.

![joplin207blank](https://user-images.githubusercontent.com/25295915/81692196-8c921d00-944d-11ea-9257-2042448a9917.png)

## Logfiles
from flags.txt  --> https://paste.debian.net/1146317/

from log.txt --> https://paste.debian.net/1146321/

**Comment by laurent22** [comment]
Could you post the markdown text that's causing this problem?

**Comment by kreisklasse** [comment]
@laurent22 
> Could you post the markdown text that's causing this problem?

i re-counted it and the document cointains about 250+ lines as the example below


```

***
### BlaBlaBla
- [ ] BlaBlaBla
- [ ] BlaBlaBla
- [ ] BlaBlaBla
    
***
***
### BlaBlaBla
- [ ] BlaBlaBla

***
```

**Comment by laurent22** [comment]
I cannot replicate this with. Could you post the markdown text that's causing this problem? And by that I mean the **exact Markdown**, something that can be copied and pasted and it causes the bug.

**Comment by kreisklasse** [comment]
Sorry, I can't do that due to to many private informations in the 200+ lines.

But I played around with my different Joplin versions on different PCs yesterday.
So i copied the whole markdown from the working note from Joplin v201 and started a new note with the full markdown in v201,
then i synced it, and i could open this new note in an other v207 without a problem. 

Then I updated also the v201 to v207 and i could still open the newly made note, but 
now the old note "crashes" (same white screen as in my first report) in joplin v207, which was ok in v201.

Presently i dont have more info/logs for you.
I think you can close the bug report cause it cant be replicated for now.

Thanks for your help.

**Comment by laurent22** [comment]
Thanks for the info. I've fixed a white screen related crash recently, which I suspect was due to the same bug as yours. I'm closing the issue for now, but if it still happens in the next version (not released yet) please let me know.
