### ISSUE TITLE
Notes from subnotebooks are not displayed when parent notebook selected

### ISSUE THREAD

**Issue by sitnarf** [laurent22/joplin#3206]
## Environment

Joplin 1.0.201 (prod, linux)
Client ID: 5d96584c0f094d16a668148fada4525f
Sync Version: 1
Profile Version: 28
Revision: e65af8c (master)
Platform: Untutu
OS specifics: 20.04

## Steps to reproduce

1.  Create nested notebooks
2. Add notes to a subnotebook
3. Press super notebook in the left panel

## Describe what you expected to happen
To display all nested notes.

![Screenshot from 2020-05-12 17-51-23](https://user-images.githubusercontent.com/289991/81716801-19eb6680-947a-11ea-8d25-b8b09dc891fe.png)

## Logfile

[-1589299022304.log](https://github.com/laurent22/joplin/files/4616764/-1589299022304.log)

**Comment by lemonballoons** [comment]
This would be awesome

**Comment by simonmeggle** [comment]
I think this issue should not be closed. This feature would be great.

**Comment by simonmeggle** [comment]
I still think this issue should need attention. 
There are in general two ways the folders could work: 

- Show only the content of the folder itself (current behaving)
- Show the content and subcontent. The notes itself could show the folder they belong to.

If you organize and review tasks in a hierarchical manner, the first way is unintuitive. There is no way e.g. to show the tasks of all customer_projects if you have one folder per customer. 

Just my 2 cents. 
Thanks, 
Simon

**Comment by pirtleshell** [comment]
funny that it went stale an hour ago. i was just looking around to see if this feature existed. sounds like its desired. i'd be happy to try to take a swing at supporting it. 

@laurent22 would you accept a PR with this feature? if so, you you prefer it to be an optional thing or an always thing?

**Comment by simonmeggle** [comment]
@laurent22 Can we get your opinion about this issue?

**Comment by hffaust** [comment]
This would be an awesome feature. Someone please revive.

**Comment by melvin-suter** [comment]
Don't want this issue to die again. This is really important to me. I expected this if you have a tree-based view.

**Comment by simonmeggle** [comment]
I left Joplin disappointed and went to [obsidian.md](obsidian.md) - and couldn't be happier with it.

**Comment by tomasz1986** [comment]
> I expected this if you have a tree-based view.

Is it really expected though, at least by most people? I'd assume the notebooks resemble a folder tree in file explorer, and there files from subfolders aren't normally displayed when viewing the parent folder. I've seen advanced file explorers that offered such an option, but it was never enabled by default.

> went to [obsidian.md](obsidian.md)

Yeah, but for those that care, this one isn't open source software. Same as Evernote, OneNote, etc.

**Comment by simonmeggle** [comment]
> this one isn't open source software

You're absolutely right. But with hundreds of **Open Source Plugins** that rock. Ok, I am shut up again. ¯\_(ツ)_/¯

**Comment by hffaust** [comment]
There could be an option where you can see all of the notes in a the child folder, and then at the top there is a divider that says "Parent Folder" and will show all the notes from the parent folder.
A rough example could look something like this:
```
Parent A
|---Child B
|---Child C
```

So if you have Child B Selected in the sidebar, then the viewable notes options bar could look like this:

```
----------
Parent A
----------
- Parent Note 1
- Parent Note 2
- Parent Note 3
...
----------
Child B
----------
- Child Note 1
- Child Note 2
- Child Note 3
```

And then perhaps there's an option to combine them into one list and sort alphabetically, by last opened note, etc.

The button to toggle this could go in the normal notes view sidebar (see screenshot).
![image](https://user-images.githubusercontent.com/15644021/178789294-ae77589e-2af7-4c50-9aec-84509a04af71.png)

**Comment by hffaust** [comment]
Can we please re-open this issue? 

There is a plugin for Obsidian that accomplishes this exact feature beautifully https://github.com/ozntel/file-tree-alternative

I would love to see an option to toggle this in Joplin because it is already so close to being a reality.

**Comment by grotesque** [comment]
@laurent22 
this really needs to be implemented.

**Comment by agathakazar** [comment]
@laurent22 this would be very useful

**Comment by arthurmccray** [comment]
Agreed this would be a useful feature!
