### ISSUE TITLE
Note sharing and collaboration features

### ISSUE THREAD

**Issue by remissao** [laurent22/joplin#3209]
I really like this projects, but I feel 2 crucial things are missing.

1- Note sharing and collaboration: it's really necessary for to have ability to share notes via a link or invite other Joplin users to edit a note.

2 - Web app : another project has already taken care of this (https://github.com/foxmask/joplin-web) but it would be nice to maybe see it merge with this project to increase integration. Also, until sharing features get added, it's not worth deploying the web app by  myself, in my case.

**Comment by dpoulton-github** [comment]
Could you please close this issue and make feature requests via the forum?

The Feature Request GitHub template itself says,

>If this is a feature request or a support query, please note that you'll not get an answer here.
>Instead we recommend using the forum where you'll are a lot more likely to get an answer: https://discourse.joplinapp.org/
>The forum is also the right place to submit a feature request so that it can be discussed by other users.

The maintainers are trying to keep the GitHub issues list under control and for bugs only.

Thanks.

BTW, posts on the forum indicate that note-sharing is being developed.

**Comment by remissao** [comment]
ok, sorry
thanks for the reply

**Comment by AkechiShiro** [comment]
Is there any news on Note Sharing and collaboration feature, I would be interested in helping to merge this feature inside Joplin as well as participating during Google Summer of Code 2022.
