### ISSUE TITLE
Don't block electron CLI switches

### ISSUE THREAD

**Issue by lann** [laurent22/joplin#3210]
In my case I just wanted to use `--force-device-scale-factor` to work around a HiDPI issue, but there are other useful switches. Consider removing the strict checking (in BaseApplication), or at least adding e.g. `--electron-switch="--force-device-scale-factor=1.5"`, which could work with [`app.commandLine.appendArgument`](https://www.electronjs.org/docs/api/command-line#commandlineappendargumentvalue).

**Comment by lann** [comment]
The check in question: https://github.com/laurent22/joplin/blob/91ec0dce37a703777eadbfa966326b1da3b74330/ReactNativeClient/lib/BaseApplication.js#L216

**Comment by laurent22** [comment]
That's difficult to fix because we don't use a proper argument parser, so we can only support the flags that are recognised.

**Comment by ldotlopez** [comment]
Sorry to reopen this issue but... I have been bitten by this.
Any updates or fixes?
