### ISSUE TITLE
Error : Missing required property: type_: 

### ISSUE THREAD

**Issue by lin0kin** [laurent22/joplin#3212]
when i synchronize my note through nextcloud , got this error
i dont even know which note is.
```Error: On file 6d4b64173d2740dd89d10501a05ac754.md: Missing required property: type_: id: ```

and how to name stored files with the title of notes?
i can't find error note everytime

and realy need Retrieving deleted notes!

**Comment by stefan2904** [comment]
I had a similar issue recently. 

Try opening `6d4b64173d2740dd89d10501a05ac754.md` on your nextcloud and look for the metadata stored at the end of the file. 

Make sure there is no newline after this block (so the line with `type_:` needs to be the last line). This did the job for me.

**Comment by gamejunkie** [comment]
Hello! I am seeing this issue as well now, and it appears to be an issue with every file that I attempt to edit. I checked the .md file on NextCloud and all appeared to be in order.

id: e62af337869a4bcdade7cd58025368c3 parent_id: e231a3b071e1419abce813b44fb82715 created_time: 2020-06-24T20:56:20.508Z updated_time: 2020-06-24T20:56:52.029Z is_conflict: 0 latitude: 0.00000000 longitude: 0.00000000 altitude: 0.0000 author: source_url: is_todo: 0 todo_due: 0 todo_completed: 0 source: joplin-desktop source_application: net.cozic.joplin-desktop application_data: order: 1593032180508 user_created_time: 2020-06-24T20:56:20.508Z user_updated_time: 2020-06-24T20:56:52.029Z encryption_cipher_text: encryption_applied: 0 markup_language: 1 is_shared: 0 type_: 1
