### ISSUE TITLE
L sep is suddenly shown before the caret when IME is used

### ISSUE THREAD

**Issue by Wakusei** [laurent22/joplin#3214]
## Environment

Joplin version: 1.0.201 (prod, win32)
Platform: Windows
OS specifics: Windows 10, x64, Spanish, ver 1909
Revision: e65af8c1 (master)

## Steps to reproduce

1. Select a note
2. Input characters with Japanese IME (MS-IME. This is the default Japanese input method on Windows 10)
3. "L Sep" unicode character suddenly appeared before the caret position

![Sin título](https://user-images.githubusercontent.com/2468628/82053336-2846b600-96f8-11ea-9204-c638bbe18bf9.png)

## Describe what you expected to happen

No "L Sep" is appeared.

## Logfile

I enabled the debug console, but error log lines were not found.

**Comment by sinkuu** [comment]
(This is a known bug: #1210 #1497)

This is a [Ace editor](https://github.com/ajaxorg/ace)'s problem described in [this article](https://anopara.net/2018/01/19/ace-editor%E3%81%A7l-sep%E3%81%A8%E3%81%84%E3%81%86%E6%96%87%E5%AD%97%E3%81%8C%E5%87%BA%E3%82%8B/). For non-Japanese speakers: the problem is that some fonts (e.g. Meryo) renders U+2028 as a displayable character.

**Comment by Wakusei** [comment]
On a ACE demo page( https://ace.c9.io/build/kitchen-sink.html ) L sep is not shown with the Chrome browser. Is there difference on Electron hosting?

**Comment by sinkuu** [comment]
I don't know, I have not even encountered the issue. At least Joplin uses an outdated version of Ace (1.2.9) and applies some CSSs, so it's different from the demo for sure.

**Comment by Wakusei** [comment]
What font are you using? NoLSep font? Which IME are you using?

**Comment by sinkuu** [comment]
I don't set editor font in options and I don't see LSEP. It may be MS Gothic or something. I'm using MS IME on Windows 10.

Okay, I can reproduce the bug if I specify Meiryo font. Could you try setting "Editor font family" in Options to the other fonts?

**Comment by Wakusei** [comment]
I tried and found only MS Gothic and MS Mincho don't display L Sep, but all the other fonts displayed it including Segoe UI, Yu Gothic, Noto(fixed width) and Han Source(fixed width). I tried all the installed fonts with Microsoft Word.
MS Gothic and MS Mincho are outdated, so I think they cannot display special characters.

This may be a problem of ACE editor, but I don't think it's a font problem.

**Comment by sinkuu** [comment]
Right, fonts may contain glyphs for special characters, and browsers should not render them: https://bugs.chromium.org/p/chromium/issues/detail?id=550275
I meant it can be a workaround to use a font without such glyphs.

**Comment by nowayhaze** [comment]
This issue still persists in 1.0.245
