### ISSUE TITLE
Add keys to navigate between links in terminal application

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#3217]
The CLI app displays links as shortened URLs: https://joplinapp.org/terminal/#urls

![image](https://user-images.githubusercontent.com/1285584/82122898-3e9f5100-978e-11ea-9f3f-df7b5f705230.png)

To open one of these links, the user currently either need to copy and paste them in their browser, or right-click them, if their terminal emulator supports it.

Additionally it would be good to support navigating between these links. For example the <kbd>b</kbd> and <kbd>n</kbd> keys would be used to select, respectively, the previous and next link. Then the user can press <kbd>o</kbd> to open the note.

**Comment by j-krl** [comment]
Seems like a great first issue. I'll take a crack at it if no one else had claimed it!

**Comment by aditianshu** [comment]
Could I give it a shot at solving this? I'm starting out in this project.

**Comment by j-krl** [comment]
I'm working on it already! I'll pass it off if I can't figure it out

**Comment by aditianshu** [comment]
Sure!
