### ISSUE TITLE
Desktop: Note shows incorrect parent folder in editing toolbar

### ISSUE THREAD

**Issue by mic704b** [laurent22/joplin#3219]
The incorrect parent folder is shown in the note edting toolbar, when viewing notes in `All notes`

## Environment
Current development master:
Joplin 1.0.207 (dev, linux)
Revision: d9601f31 (master)

## Steps to reproduce
1. Create two folders, each containing a note
2. Select "All notes"
3. Select a note in the note list, and check the parent folder indicated in the toolbar
4. Select the other note in the note list, and check the parent folder in the toolbar

Observed: the parent folder shown in the toolbar is not updated in steps 3 and 4
Expected: the parent folder is updated whenever a new note is selected

In the below example, the toolbar is incorrectly showing the parent of `note 1` is `Folder B` when it should show `Folder A`.

![bug-parent-folder](https://user-images.githubusercontent.com/1732810/82137531-7d034180-985c-11ea-847e-6b9006b76485.gif)

**Comment by laurent22** [comment]
Yes I had noticed that this was broken after a GSoC PR, but that should be fixed now.
