### ISSUE TITLE
Numbered list preview doesn't match in editor

### ISSUE THREAD

**Issue by amcginn** [laurent22/joplin#3222]
When making a list and skipping numbers within the list, the preview shows the numbers in order instead of what is in the editor. 
![Joplin numbered list](https://user-images.githubusercontent.com/22381097/82156667-24bf4600-9842-11ea-8edf-4549075de8b8.png)

## Environment

Joplin version: 
Platform: 
OS specifics: Tested with Windows and iOS

## Steps to reproduce

1. Create numbered list (1. 2. 3.)
2. Add number not in sequence (1. 2. 3. 25.)
3. View in preview pane

## Describe what you expected to happen
Preview should match editor

**Comment by laurent22** [comment]
This as expected and not supported in Markdown
