### ISSUE TITLE
images got lost after notes  edited in external editor

### ISSUE THREAD

**Issue by devopjj** [laurent22/joplin#3223]
## Environment
Joplin 1.0.201 (prod, win32)

Client ID: 88bb9f13e33d468fb02318d48527ddaa
Sync Version: 1
Profile Version: 28

Revision: e65af8c1 (master)

Joplin version: 1.0.201(prod,win32)
Platform: Windows 10
OS specifics: Build 1909 ,18363.836

## Steps to reproduce

1.  Set external editor: Typero.
2.  Select a note with Edit in external editor.
3.  Modify some texts and also insert a image to the note in Typero and then save note.
4. Check the note in Joplin: texts has been updated while new images inserted in Typero got lost.

## Describe what you expected to happen
I think it could be a goodthing  to allow user specify the resource path below the Joplin path (now the path is: resources, where Joplin store images).
Especially useful when I import MD file made by  other editor.
Thank you concerning.

**Comment by stefan2904** [comment]
There is also a discussion about this in the forum: 
https://discourse.joplinapp.org/t/auto-attach-images-as-resources-after-external-editor/3121

**Comment by stefan2904** [comment]
Where would an external tool need to put a picture for Joplin to import it into `resources`?

**Comment by macrosalt** [comment]
Same problem. Images cannot be referred by just typing the filename. I must turn back to Joplin editor to paste the image, renaming the filename according to Joplin disicipline and the image properly shows in note attachment. Is there anyway to insert images in an external editor, like Typora?
