### ISSUE TITLE
Linux bash installed not updated?

### ISSUE THREAD

**Issue by zohozer** [laurent22/joplin#3224]
I do had installed Joplin v1.0.201 on my Ubuntu 20.04 machine using the following script:
`wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash`

and if I do check for updates using the "Help/Check for updates...." it is saying that there are no updates. On the [https://github.com/laurent22/joplin/releases](https://github.com/laurent22/joplin/releases) page however, seems that there is the v1.0.209 version available.

How can I update to the newest version in this case?

**Comment by Shamp0o** [comment]
v1.0.209 is a pre-release and is therefore ignored by the script. You're on the latest stable version.

**Comment by Stele77** [comment]
Hi, is it update to pre-release with the script, maybe by adding some arguments to the command line?
I am on Ubuntu 20.04, have installed by script, and changed setting in Joplin to download pre-release.
But when i check for update in Joplin, it only opens the Github release page.
How can i update to pre release, without having to abandon the script install method? I dont want to use appimage, it is often problematic regarding system integration (unable to pin to dock, etc, the typical Appimage problems).
Thanks in advance!

**Comment by TheOnlyTrueJonathanHeard** [comment]
@Stele77 This option has just been added yesterday. You can update to pre-releases running the following command: 

```
wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash -s -- --prerelease
```
