### ISSUE TITLE
Joplin keeps synchronizing despite disabled synchronization interval

### ISSUE THREAD

**Issue by Kiel97** [laurent22/joplin#3225]
I set up a Joplin to synchronize with Dropbox every 5 minutes by default. One day I wanted to disable it as I was moving large part of notebooks and notes so the synchronization would not mess up. But when I disabled synchronization intervals, Joplin keeps synchronizing with it. What I expect is to app stop automatically synchronizing with Dropbox every 5 minutes and synchronize only on user demand. I haven't tested this issue with other OSes and Joplin versions.

## Environment

Joplin version: 1.0.201
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Make sure Joplin's synchronization target is set to Dropbox
2. Set synchronization interval to Disabled
3. Make some changes to files and notebooks
4. After some time (5 minutes in my case) Joplin automatically synchronizes notes with Dropbox 

## Describe what you expected to happen
I expect Joplin to stop automatically synchronize changes when synchronization interval is set to Disabled

**Comment by rmnof** [comment]
I have the same problem even worse. I set up Joplin to synchronize with Onedrive and Webdav, it seems that Joplin will sync to Onedriv and Webdav at the same time, and worsely **there is no way to turn off one of the synchronization**.

**Comment by Kiel97** [comment]
@stale, keep it open. It's not resolved yet.

**Comment by trusty-fox** [comment]
The same problem here.
I only enabled synchronization with Nextcloud (WebDAV) and no matter which sync interval I choose, it synchronizes (kinda randomly) every few minutes (I feel like it doesn't sync as long as I am typing, but I can't quantify that).

## Environment
Joplin version: 1.0.233
Platform: Linux
OS specifics: Ubuntu 18.04 LTS, Kernel _4.15.0-109-generic_

**Comment by trusty-fox** [comment]
I don't think this is solved yet, is it?

**Comment by th3W3n** [comment]
not solved

**Comment by teleportpast** [comment]
Hi team, 
It seems we’re still facing an issue where disabling the sync interval doesn't fully prevent synchronization upon app startup. While I understand the reasoning behind this behavior, many users – including myself – would greatly benefit from having a true 'disabled' option that allows us to initiate sync manually. This request has been raised several times over the past few years (as evidenced by issues #12568, #4314 and #8073 and in the forum), and implementing this would enhance user control and flexibility for those who prefer on-demand syncing.
