### ISSUE TITLE
 Desktop : Viewer scroll behavior

### ISSUE THREAD

**Issue by AllFunThing** [laurent22/joplin#3228]
## Environment

Joplin version: 1.0.209
Platform: windows
OS specifics: windows 10

## Steps to reproduce

1. normally, when scrolling viewer's scroll bar, editor's scroll bar is scrolled at the same time.
2. change mode to code view and then back
3. now, viewer's scroll bar move independent of editor's scroll bar.

## gif
![joplin_scroll_4](https://user-images.githubusercontent.com/50653394/82288783-3a697280-99de-11ea-9daa-7600b964da49.gif)

## Describe what you expected to happen

i don't know what kind of action is right.
but, at least I wish I could choose it.
often, text in editing is not show in viewer because viewer's auto scroll is incorrect. such case, i'll choose independent scroll mode(?).

Thank you for providing a good application :)

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/4648457/log.txt)

**Comment by taw00** [comment]
Holy cow. Whatever you did, @laurent22 ... I don't know it was this or something else, but the bouncing around in the editor ... well, it is simply far more stable now. Thank you. Thank you. Thank you.
