### ISSUE TITLE
Highlight is buggy when combined with LaTeX equations

### ISSUE THREAD

**Issue by RMeli** [laurent22/joplin#3229]
When two distant LaTeX equations contain the symbol `_` (used for subscripts in LaTeX and for italic in Mrkdown), the text in between is highlighted as italic text. 

The same problem also occurs within the same equation if two `_` are present.

## Environment

Joplin version: 1.0.201 (e65af8c)
Platform: macOS
OS specifics: 10.14.4

## Steps to reproduce

Type the following in a note:

```
$x_i$ Lorem Ipsum $y_i$.
```

The text between `_` will be highlighted incorrectly as italic: `i$ Lorem Ipsum $y`

## Describe what you expected to happen

I expect `_` within equations to be ignored by the highlighter.

**Comment by RMeli** [comment]
I see now this a duplicate of #3054.

**Comment by tessus** [comment]
https://github.com/ajaxorg/ace/issues/3942

**Comment by CalebJohn** [comment]
fixed by #3703

**Comment by RMeli** [comment]
Nice, thanks!
