### ISSUE TITLE
theme.js not found in CLI

### ISSUE THREAD

**Issue by devopjj** [laurent22/joplin#3230]
## Environment

Joplin version: joplin 1.0.164 (prod)
Platform: Ubuntu 18.04.4 LTS #WSL
OS specifics: Windows 10

## Steps to reproduce

1. create new note with tag:tag1,tag2
2. use cli to export: 
`
joplin export --format html /home/user/joplin_export
`
3. error msg:

> Cannot find module ../../theme.js
> Require stack:
> - /home/eric/.joplin-bin/lib/node_modules/joplin/lib/services/InteropService_Exporter_Html.js
> - /home/eric/.joplin-bin/lib/node_modules/joplin/lib/services/InteropService.js
> - /home/eric/.joplin-bin/lib/node_modules/joplin/command-export.js
> - /home/eric/.joplin-bin/lib/node_modules/joplin/app.js
> - /home/eric/.joplin-bin/lib/node_modules/joplin/main.js

**Comment by laurent22** [comment]
Duplicate: https://github.com/laurent22/joplin/issues/3092
