### ISSUE TITLE
Window goes blank when typing in search term

### ISSUE THREAD

**Issue by BackSeat** [laurent22/joplin#3232]
## Environment

Joplin version: 1.0.207 and also tried 1.0.209
Platform: Linux
OS specifics: Debian 10.4

## Steps to reproduce

1. Open Joplin
2. Start to type in search box
3. Jopin window goes blank, menu bar only.

I'm also experiencing it just trying to display different notes.

Video of problem: https://www.loom.com/share/d61784655a724af3862383495f63afd3

## Describe what you expected to happen

Note list to be populated with matching notes.

## Logfile

Two attached: one of console errors when starting Joplin, and the second when the error occurs.
[joplin-console-on-error.log](https://github.com/laurent22/joplin/files/4651490/joplin-console-on-error.log)
[joplin-console-at-start.log](https://github.com/laurent22/joplin/files/4651492/joplin-console-at-start.log)

**Comment by laurent22** [comment]
Thanks for the report, I think that should be fixed in this commit 7a1eecc81523e7760562ad8918e3b8cc49683ff0
