### ISSUE TITLE
Surround selected text with Emphasis

### ISSUE THREAD

**Issue by pakosel** [laurent22/joplin#3233]
At the moment it's possible to surround (in the editor) the selected text with parenthesis or quotes by selecting part of the text and pressing one of the following characters `( [ "` or `'`. For example in a sentence
```
Feature requests and support
```
one can select the word `requests` and **press** `(` which results surrounding this word with parenthesis:
```
Feature (requests) and support
```

It's extremely useful because it speeds up editing notes. 
**Why not to extend the supported types of surrounding to the following characters:**
- `*` italic
- `**` bold
- `_` italic
- `__` bold
- `` ` `` (code block)

Seems quite obvious extension in my opinion

**Comment by dpoulton-github** [comment]
Could you please close this issue and make feature requests via the forum?

The Feature Request GitHub template itself says,

>If this is a feature request or a support query, please note that you'll not get an answer here.
>Instead we recommend using the forum where you'll are a lot more likely to get an answer: https://discourse.joplinapp.org/
>The forum is also the right place to submit a feature request so that it can be discussed by other users.

The devs are trying to keep the GitHub issues list under control and for bugs only.

**Comment by pakosel** [comment]
OK, I'll post it on the forum. Thanks
