### ISSUE TITLE
Nord theme markdown syntax needs improvement

### ISSUE THREAD

**Issue by pr3c0g** [laurent22/joplin#3236]
After the last update the markdown syntax highlighting for the Nord theme had some colors changed. 

This is relevant only for the code editor, the preview is working fine.

This is how it looks at the moment:
![image](https://user-images.githubusercontent.com/11090205/82429971-3724c400-9a7c-11ea-9ebd-8d65215a6e15.png)

## Environment

Joplin version: Joplin 1.0.211 (prod, darwin)
Platform: Mac OS

## Steps to reproduce

1. On settings, change the theme to "Nord"
2. Create new note
3. Type markdown syntax on the code editor and check the syntax highlight

## Describe what you expected to happen

This is how it should look, based on the Nord theme applied on other text editors

VSCode:
![image](https://user-images.githubusercontent.com/11090205/82429750-f036ce80-9a7b-11ea-8527-79e445482794.png)

SublimeText:
![image](https://user-images.githubusercontent.com/11090205/82429801-fdec5400-9a7b-11ea-9313-479ad20443f9.png)

Thank you so much for your hard work!

**Comment by shbach** [comment]
I just created #3269 before noticing yours. Mine reports issue with all the themes and I guess it encompasses this as well though you have more detail on the Nord theme.
