### ISSUE TITLE
Geo-location not saved on Android

### ISSUE THREAD

**Issue by ei-ke** [laurent22/joplin#3240]
## Environment

Joplin version: 1.0.329
Platform: Android
OS specifics:  build 9.1.0.252

## Steps to reproduce

1. Newly set up app on Android
2. Create a new note
    * No request to allow Joplin using geo-location data, thus enabled this manually
3. Go to "Show on map" in the note properties
    * No location information available for the note

## Describe what you expected to happen
I expected the geo-location to be saved as it's done on the desktop (in the latter case by the IP location).

## Logfile
```
Date,Level,Message
05-21T09:51:50,10,"""Could not get lat/long for note bbdd10ad62294c4d8b3339d0398e9d7f: ", "TypeError: undefined is not an object (evaluating 'navigator.geolocation.getCurrentPosition')
index.android.bundle:969:652
c@index.android.bundle:108:205
b@index.android.bundle:108:1623
_@index.android.bundle:108:488
value@index.android.bundle:969:616
index.android.bundle:449:11699
p@index.android.bundle:112:423
index.android.bundle:112:1740
p@index.android.bundle:112:423
n@index.android.bundle:112:898
index.android.bundle:112:1273
c@index.android.bundle:108:205
b@index.android.bundle:108:1623
_@index.android.bundle:108:488
u@index.android.bundle:112:1257
_invoke@index.android.bundle:112:1309
async@index.android.bundle:112:3681
index.android.bundle:1251:2338
p@index.android.bundle:112:423
index.android.bundle:112:1740
p@index.android.bundle:112:423
n@index.android.bundle:112:898
index.android.bundle:112:1047
f@index.android.bundle:108:155
index.android.bundle:108:882
y@index.android.bundle:114:661
C@index.android.bundle:114:1025
callImmediates@index.android.bundle:114:3100
callImmediates@[native code]
value@index.android.bundle:26:3247
index.android.bundle:26:1283
value@index.android.bundle:26:2939
value@index.android.bundle:26:1253
value@[native code]
value@[native code]""
05-21T09:51:50,30,"""Fetching geolocation...""
```

**Comment by laurent22** [comment]
Does the app has geo-location permission?

**Comment by ei-ke** [comment]
Yes, I manually set this permission for the app as there was no request for that permission as other apps commonly do.

**Comment by roman-r-m** [comment]
Has it ever worked before for you?
Currently the code throws an exception here
https://github.com/laurent22/joplin/blob/2de30f8b821a9ded29745af845fefca139ef9da1/ReactNativeClient/lib/geolocation-react.js#L27

I think it's because `navigator` is not defined. I looked through the code and could not find where it's set.

**Comment by ei-ke** [comment]
I've just recently started using Joplin, so I can't anwer this for the past.

**Comment by roman-r-m** [comment]
Looks like it has been broken when React-Native was upgraded. Navigator has been removed from React-Native code. 
It is now recommended to use https://github.com/react-native-community/react-native-geolocation

**Comment by laurent22** [comment]
Oh I can't believe that, it's indeed been broken for a while then, thanks for checking @roman-r-m. Makes me wonder if there should be some option to display an in- app notification when there's a background error, instead of going to the log.

**Comment by ei-ke** [comment]
I guess something like the 10MB attachment hint could be useful to let "common users" (like me) stumble upon this earlier without explicitly looking if a feature is doing what it promises.
