### ISSUE TITLE
Cycling layouts scrolls the editor up by a few lines

### ISSUE THREAD

**Issue by v-marinkov** [laurent22/joplin#3249]
Joplin version: 1.0.201
Platform: Linux, appimage
## Steps to reproduce

1. Open a note in markdown which is taller than the viewport. Open the note in split view or markdown and scroll to the end.
2. Change the layout with Ctlr+L to markdown/split view and notice that the note has been scrolled up by a few lines. Going further to the viewer layout still has the note scrolled at the bottom. But in both split view or markdown it remains scrolled up by a few lines.

## Describe what you expected to happen
I would expect the cursor and the viewport to stay at the bottom from where I started in the markdown.

**Comment by j-krl** [comment]
I'll take a look at this

**Comment by laurent22** [comment]
This was an issue with Ace Editor which we'll no longer use from the next version. If it still happens with CodeMirror (after the new version has been released) please open a new bug report.
