### ISSUE TITLE
Username with spaces not supported 

### ISSUE THREAD

**Issue by reinerj** [laurent22/joplin#325]
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [x] Terminal

We are using Joplin on the desktop and mobile phones without issue, On the CLI we run in the problem that when you have a username with space the login fail.

The username is something like "Firstname Lastname"

We try to sync again Nextcloud server.

Sabre\DAV\Exception\NotAuthenticated: No public access to this resource., No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, Username or password was incorrect

**Comment by laurent22** [comment]
It's working for me. How did you set the username? It should be `config sync.5.username "Firstname Lastname"` with double-quotes around the name.

**Comment by reinerj** [comment]
Hi,

I just tried it again. It work now. I had to restart Joplin from the command line after i did set the password. Then it worked.

Thanks!
