### ISSUE TITLE
Can not Edit properly on joplin on linux

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [laurent22/joplin#3254]
## Environment

Joplin version: 1.0.214
Platform: Linux
OS specifics: Manjaro Linux 20 with KDE 5.18.5

## Steps to reproduce

1. Open Joplin

2. Create a note

3. Type a sentence and try to bold it , delete words in the middle and other edits

4.Now the word you wan to bold will not get bold instead something else will,same is with delete ,italics and other editing.

## Describe what you expected to happen

Everything should work fine

## Logfile

Here's a small clip which explains the issue in more detail:
![Peek 2020-05-23 06-28](https://user-images.githubusercontent.com/38154154/82718386-d7b6f600-9cbf-11ea-9f8f-f602a650ceeb.gif)

**Comment by laurent22** [comment]
use a monospace font
