### ISSUE TITLE
关于边栏与笔记列表的优化建议

### ISSUE THREAD

**Issue by yimisunrise** [laurent22/joplin#3255]
- 现状：
1. 若左侧边栏目录内只有子目录，则选中该目录后笔记列表中将展示为空（我首次使用时一脸懵逼）

- 建议：
1. 选中左侧目录时，将目录内的子目录也展示在笔记列表中（当然“笔记列表”这个称呼是否应该修改一下才更贴切）
2. 双击进入笔记列表中的子目录后，左侧目录自动定位至该子目录

(以上建议纯属个人使用体验，因人而异，所以如果要实现，我觉得采用配置开关是最好的)

**Comment by laurent22** [comment]
In English please, or provide a Google translation.
