### ISSUE TITLE
Edit in external editor button disappeared 

### ISSUE THREAD

**Issue by SilvM** [laurent22/joplin#3256]
## Environment
Joplin version: 1.0.214 (prod, win32)
Platform: Windows
OS specifics: Windows 10 Home edition

## Steps to reproduce
1. Upgrade to latest prod version
![image](https://user-images.githubusercontent.com/11724527/82721819-a821e100-9cf3-11ea-9f45-1cfc5d6fa5e5.png)

## Describe what you expected to happen
I don't see any note on this in the version release changelog so I'm not sure if it's deliberate or not. I know there's a shortcut for it, but I used to pressing the button

**Comment by laurent22** [comment]
It's under Note menu, or press Ctrl+E

**Comment by stefan2904** [comment]
This is not super convenient if you use external editing a lot. 

Can we make the button appear again, e.g. only if an external editor is configured?

**Comment by riversHYD** [comment]
I agree with stefan2904's words. Now it‘s inconvenient if we finish editing in external editor because there is not shortup keys of stop external editing. So can we add the shortup key of stop  stop external editing or make the button again?

**Comment by Neurogami** [comment]
The lack of the button removes an important visual indicator that a note is or is not still open in an external editor.   It's also, as others have mentioned, just convenient.  I cannot understand the value in removing this.   Is it safe to go back to an earlier version until this is fixed?

**Comment by SilvM** [comment]
you can still see them being open in an external editor but I agree it's like the feature is hidden away in the menu
![image](https://user-images.githubusercontent.com/11724527/84001703-c0ebf100-a999-11ea-8196-fe424ab7671b.png)

**Comment by Neurogami** [comment]
Interesting. Hadn't noticed that (which may mean it is took small an indicator).  

Still have no idea what user problem was solved or user value  created by removing the button.

**Comment by laurent22** [comment]
That button is back in the latest version

**Comment by Neurogami** [comment]
Thank you.
