### ISSUE TITLE
Note history on mobile devices

### ISSUE THREAD

**Issue by ei-ke** [laurent22/joplin#3258]
I'd like to know if the 730 day limit can be increased (maybe a text field instead of a slider?):
https://github.com/laurent22/joplin/blob/b27a215c7f0a785440385facca3c9ae853822aa6/ReactNativeClient/lib/models/Setting.js#L644-L651
On the desktop app there is no such limit.

PS: Please let me know if it is okay to open an issue for this or if this belongs to the forum.

Greetings
Eike

**Comment by laurent22** [comment]
We could increase the limit I guess, but any reason you need more than 2 years of history? Beyond that you can also create JEX backups if needed.

**Comment by ei-ke** [comment]
No specific reason except being an data hoarder. Exporting notes would be the better idea instead of maybe slowing everything down or corrupting something with an unreasonable long history.
Then it should be limited on the desktop version to 730 days, too. Just in case someone doesn't notice the hint that the smallest history duration of any device is the one that counts. Maybe one could also introduce reading the history from some kind of config file in de note storage location to set it tonthe same duration on all devices.

**Comment by jtagcat** [comment]
I've also wondered this.

As for me, I don't see a good reason for deleting a trivial amount of data, where it could benefit me in the future. Archives have helped me before, and likely, will again.
