### ISSUE TITLE
Faster sync

### ISSUE THREAD

**Issue by benwaffle** [laurent22/joplin#3263]
It would be ideal if we had real-time sync. Some ideas to get us closer:

- [ ] Sync a note right when it is created
- [ ] Sync a note on every change
- [ ] Nextcloud app as a backend for calculating deltas
- [ ] Nextcloud app as a way to notify clients when to sync

**Comment by Perkolator** [comment]
> * [ ]  Sync a note right when it is created

Why? Before even creating a title for the note?

> * [ ]  Sync a note on every change

What do you mean, on every little change, e.g. adding/removing a single character? Please no. Joplin already has a "quick sync after 30 seconds of inactivity after editing a note" feature (users can't turn this off) and personally I don't even like that, it's too fast for my liking.

**Comment by dpoulton-github** [comment]
@benwaffle 

Could you please close this issue and make feature requests via "Features" in the forum?

The Feature Request GitHub template itself says,

>If this is a feature request or a support query, please note that you'll not get an answer here.
>Instead we recommend using the forum where you'll are a lot more likely to get an answer: https://discourse.joplinapp.org/
>The forum is also the right place to submit a feature request so that it can be discussed by other users.

The maintainer is trying to keep the GitHub issues list under control and for bugs only.

Thanks.
