### ISSUE TITLE
install_and_update: passing arguments while piping to bash

### ISSUE THREAD

**Issue by jtagcat** [laurent22/joplin#3264]
You need to use `... | bash -s -- --argument` to pass arguments while piping to bash. I would like to include it in the script, but you can't call help, without already knowing this (or looking at the script's source).

Where should the 'tip' be included? As a comment at the top of the script? Printed on no-argument execution?

**Comment by jtagcat** [comment]
Not fixed. I'll make a PR in a day or so.

**Comment by jtagcat** [comment]
or a few months
:/ stuff keeps piling up

**Comment by JonathanPlasse** [comment]
Still interested

**Comment by jtagcat** [comment]
Yes

**Comment by jtagcat** [comment]
Yes I promise I'll try to work on it within 6 months.

**Comment by JonathanPlasse** [comment]
The tip could be added next to the [download instruction for Linux](https://github.com/laurent22/joplin/blob/dev/README.md#user-content-desktop-applications).

**Comment by jtagcat** [comment]
I frankly don't have the time in the scope of 6-18 months. @JonathanPlasse could you please make a PR doing so? Thanks.
