### ISSUE TITLE
"Network request failed" on two iOs devices with WebDAV sync

### ISSUE THREAD

**Issue by wealthychef1** [laurent22/joplin#3266]
## Environment

Joplin version:  10.0.47
Platform: iOS (both my iPad and iPhone)
OS specifics: latest iOS

## Steps to reproduce

1.  Choose WebDAV as sync target
2.  enter username and password and URL to a WebDAV server that works fine for other clients
3.  click "Check synchronisation configuration"

I get an error in the GUI:  

> "Error: Please check that the URL, username, password, etc. are correct and that the sync target is accessible.  The reported error was: 
> 
> Network request failed"

I can connect to the WebDAV server using the OS X desktop client and it synchronizes successfully.  
I have uninstalled and reinstalled the client.  No good.  Tried both phone and iPad and get the same errors.  The logs do not show any errors that I can tell.  I am enclosing a few screen shots for what it's worth.  (Side note:  why not make the log text easier to share other than a screen shot?  I can't select and copy text from it...)  
Thanks for any help!  

## Describe what you expected to happen

I expect an entry in my log file on apache on the server.  I see when other clients connect or things are rejected, but the iPad does not trigger anything in the server logs.  

## Logfile

![D9529A37-D717-42C9-A931-D69DF324ECFF_1_105_c](https://user-images.githubusercontent.com/4825448/82752378-d254cb00-9de7-11ea-8dc1-c1bf4d92f8b7.jpeg)
![9D0EF2ED-D877-4F7E-A6D7-0C9D60EC5A4C_1_105_c](https://user-images.githubusercontent.com/4825448/82752379-d54fbb80-9de7-11ea-8e28-c29f634e5f98.jpeg)
![4C4115EF-EC98-4F90-89D9-3907B4C7D695_1_105_c](https://user-images.githubusercontent.com/4825448/82752381-d680e880-9de7-11ea-8816-a97bb6286a02.jpeg)

**Comment by roman-r-m** [comment]
Can you try using ip address instead of the host name instead? I had a similar issue here: https://github.com/laurent22/joplin/issues/3211

**Comment by wealthychef1** [comment]
> Can you try using ip address instead of the host name instead? I had a similar issue here: #3211

Thanks for the suggestion.  Doing so made no difference in behavior for me.

**Comment by roman-r-m** [comment]
I see, thanks for checking. Might be something else then.
Can you connect to your webdav server using web browser on the same device where you're getting the error?

**Comment by wealthychef1** [comment]
> I see, thanks for checking. Might be something else then.
> Can you connect to your webdav server using web browser on the same device where you're getting the error?

Yes, every other client, including an app called WebDAV Nav on the same iPad, has no trouble connecting to the server.  The Joplin client on my Mac connects to it fine and I can go there with another WebDAV client and see the files it has put there.  Just not Joplin on iOS.

**Comment by wealthychef1** [comment]
I was able to set up NextCloud and get that working.  I never did figure out how to make apache2 WebDAV work with the iOS client.  Very disappointing because nextcloud is even slower to sync.  The terrible sync performance I'm seeing is probably going to be a deal killer as I have thousands of notes to sync.

**Comment by platzh** [comment]
Hey @wealthychef1,

I had a similar issue the other day.

I use Joplin on an iPhone, iPad and my Macbook.
Jopllin syncs to a Nextcloud instance that I host on my Synology Diskstation only available via VPN or if you are in the local network.
When I changed the settings in Apache that you can now only reach nextcloud via https. Joplin stoped working with the "Network request failed" error.
I encountered this beforehand but could get around with using plain http. This is now, obviously, not possible anymore.

The solution for me was to create my own self signed certificate on the Diskstation and import it to my mobile devices. Since then it works fine again.

Maybe you can try something similar (if you not already have done so)

**Comment by dantezhu** [comment]
it happen again, in lastes version.

**Comment by wowodavid** [comment]
still happens on latest joplin on ios/ipados

**Comment by charles-997** [comment]
I am having this issue in the iOS app.  I have confirmed that I can connect to the webDAV share using safari on iPhone, but Joplin will not connect.  I can confirm that this did work before, but is now broken.

I am getting an error showing "Network request failed."

Does anyone know what version of the iOS app this became broken? Hopefully I can downgrade as it looks like this might not be resolved.

Joplin for iOS 12.3.1, database v39.
iOS 15.0 Public Beta 8
iPhone 12 Pro Max

**Comment by SteveCrowBro** [comment]
This is still an issue, even when using the host ip.

**Comment by banjuer** [comment]
still happens on latest joplin on ipados

**Comment by hjstrauss** [comment]
Still happens for me on ios. Joplin 12.7.1, database v41

**Comment by Foiler-NZ** [comment]
I have a similar error message with Joplin 12.7.1 and Database v41 running on iOS 15.4.1 syncing to Dropbox. 

The error is:
Synchroniser: TypeError: Network request failed @/private/var/containers/Bundle/Application/blah-blah-blah

If I delete the app and reinstall it then it does one full sync ok (more than 5,000 items), but then any further syncs all fail with the above error message showing in the log. 

I have two Mac's both syncing to the same Dropbox just fine .. they are running ver 2.7.15, Sync Version: 3, Profile Version: 41.

**Comment by Foiler-NZ** [comment]
> I have a similar error message with Joplin 12.7.1 and Database v41 running on iOS 15.4.1 syncing to Dropbox.
> 
> The error is: Synchroniser: TypeError: Network request failed @/private/var/containers/Bundle/Application/blah-blah-blah
> 
> If I delete the app and reinstall it then it does one full sync ok (more than 5,000 items), but then any further syncs all fail with the above error message showing in the log.
> 
> I have two Mac's both syncing to the same Dropbox just fine .. they are running ver 2.7.15, Sync Version: 3, Profile Version: 41.

.. this came right for me some time during the past week or so .. no changes made that I am aware of .. after a couple of weeks of not syncing on the phone it has suddenly started syncing.

**Comment by danielzhou82** [comment]
I use synology webdav server for joplin storage, seems only http works, not https

**Comment by yonggithub** [comment]
Still happens for me on ios. 
The same configurations on PC is working.
![image](https://user-images.githubusercontent.com/25076827/191162690-8f332c2f-8f3c-4bd2-836f-d35e7776cbc9.png)

**Comment by wangshuang235** [comment]
Still exist on ios ，Joplin 12.8.1, database v41（2022-10-20）

**Comment by lfu2000** [comment]
same issue.
simple resolution: replace the webdav server from dsm to caddy.

**Comment by willtchambering** [comment]
On iPadOS 16.1.1:

'Check synchronization configuration' returns:

"Success! Synchronization configuration appears to be correct."

The 'lock' and 'temp' directories are updated (mtime-wise), as is the 'Readme.md' file, but the logs have the 'synchronizer: "TypeError: Network request, failed…" 

Joplin: 12.8.1
Database v4 y1
FTS enabled: 1

NextCloud: 25.0.1

**Comment by lizhiwei8061** [comment]
我遇到同样问题

**Comment by AreChen** [comment]
Same issue on iPad os16

**Comment by lizhiwei8061** [comment]
turn to sb. for help，I encountered the same problem，Using HTTPS is also not feasible

**Comment by SCZeiDan** [comment]
Same issue on iphone13 ios16, joplin version 12.11.3

**Comment by shaopengyuan** [comment]
> I use synology webdav server for joplin storage, seems only http works, not https
Is http working on your synology webdav server? Mine is still not working.

**Comment by LonestarLondoner** [comment]
Same issue on iPadOS using IP. Works on mac and android.

**Comment by noru** [comment]
please add `ignore tsl errors` options like the other platforms

**Comment by ih9u98hijk** [comment]
As @noru  said - this I believe would solve the issue easier than creating a custom DNS redirect from api.joplincloud.local to IP address as has been the only workaround I've seen for this issue.
