### ISSUE TITLE
Code View toggle (going back from the WYSIWYG editor) breaks images

### ISSUE THREAD

**Issue by alfredbaudisch** [laurent22/joplin#3267]
The WYSIWYG editor breaks all existing images from a Markdown note. It adds the full local path to images previously added through Markdown.

For example, the image was `63545214c69fcaff3f19afd2b0e0e651` and correctly placed with Markdown, when going to WYSIWYG, it changed to a full local path. It is possible to see the change in the attached log.

```
!\[63545214c69fcaff3f19afd2b0e0e651.png\]([file://C:/Users/1545](file://C:/Users/1545) IRON
 V4/.config/joplin-desktop/resources/40270689124e42cbb6ac2fddbcf621d8.png)
```

![image](https://user-images.githubusercontent.com/248383/82760404-a0496600-9df3-11ea-85bf-d5ac4c82dd35.png)

## Environment

Joplin 1.0.216 (prod, win32)

Client ID: 88172fdc238748cabba691cc30d18a14
Sync Version: 1
Profile Version: 29

Revision: 4eb680d6 (master)

Windows 10

## Steps to reproduce

1. Create a note in the default Markdown editor or open an existing note
2. Add an image.
3. Now switch to the WYSIWYG editor by using the new **"Code View"** button from the top bar
4. Make any kind of change in the node (which is not related to the images). For example, add a new character somehwere.
5. Now switch back to the default editor by clicking "Code View" again
6. Images are now broken.

## Describe what you expected to happen
Do not break the images when going to WYSIWYG and back, i.e. keep as relative path:
```
![5ed17f4f1a544e592751dbd18d5d3e1e.png](:/6b1f0d790184435586ffbf5e4fce9e1a)
```

## Logfile

[debug.log](https://github.com/laurent22/joplin/files/4674064/debug.log)

**Comment by laurent22** [comment]
Is that the portable version?

**Comment by alfredbaudisch** [comment]
No, installed. 

On May 25, 2020 12:51:10 AM GMT+02:00, Laurent Cozic <notifications@github.com> wrote:
>Is that the portable version?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/laurent22/joplin/issues/3267#issuecomment-633312259

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
