### ISSUE TITLE
"code" query parameter is missing

### ISSUE THREAD

**Issue by derekdonyen** [laurent22/joplin#3272]
When I use onedrive to sync my notes will meet this error message. ("code" query parameter is missing)
I suspect it is a problem with the student account.
Thanks

**Comment by Goldenspirits** [comment]
When I use onedrive to sync my notes will meet this error message. ("code" query parameter is missing)
me too。。。

**Comment by YtJz** [comment]
I have the same situation when I use student account.("code" query parameter is missing) 
But it's ok when I use other onedrive account to sync.
Why can't I use srudent account?
