### ISSUE TITLE
"Fatal error Unknown table: settings" When trying to open the joplin-desktop.

### ISSUE THREAD

**Issue by PanTrakX** [laurent22/joplin#3273]
I have downloaded and built Joplin from the AUR using yay and when i try to open the joplin-desktop i get the following message 
![2020-05-25-170059_3286x1080_scrot](https://user-images.githubusercontent.com/62219596/82807491-87db5900-9e90-11ea-9a7a-970919e6ed8f.png)

## Environment

Joplin version: joplin 1.0.163 (prod)
Platform: Linux
OS specifics: 5.6.12-1-MANJARO

## Steps to reproduce

I don't know.

## Describe what you expected to happen
I expected the joplin-desktop to open!

## Logfile
[log.txt](https://github.com/laurent22/joplin/files/4676896/log.txt)
[log-database.txt](https://github.com/laurent22/joplin/files/4676897/log-database.txt)

**Comment by laurent22** [comment]
Please report this in the aur package page, as this error is specific to it.
