### ISSUE TITLE
Add option to disable "New todo" button

### ISSUE THREAD

**Issue by xearonet** [laurent22/joplin#3278]
Hi. I would be nice to have ability to turn this button off in settings. I've often make mistake and tap this button instead "New Note".
If this is not possible, please consider color change for this button to distinguish from "New note" which is a lot more often used or even set "New Note" button to appear always on top do the job.

![image](https://user-images.githubusercontent.com/22504894/82884819-91be9400-9f44-11ea-9a54-dd6fbedf41a8.png)

**Comment by dpoulton-github** [comment]
Could you please close this issue and make feature requests via "Features" in the forum?

The Feature Request GitHub template itself says,

>If this is a feature request or a support query, please note that you'll not get an answer here.
>Instead we recommend using the forum where you'll are a lot more likely to get an answer: https://discourse.joplinapp.org/
>The forum is also the right place to submit a feature request so that it can be discussed by other users.

It's just that the maintainer is trying to keep the GitHub issues list under control and for bugs only.

Thanks.

**Comment by xearonet** [comment]
Moved to Joplin forum. Thanks
