### ISSUE TITLE
[Feature Request] Navigation on document's chapters

### ISSUE THREAD

**Issue by aventrax** [laurent22/joplin#3279]
I'm coming from another software and Joplin is a way better but I miss a feature that is very useful.

Notes have sections and sub-sections created with markdown '#' and '##', I think being able to navigate these sections quickly without scrolling down manually would be a great improvement. There is space on the Joplin's left sidebar for a document index created as a tree from markdown sections of the notes.

Is it possible to implement? Anyway, this component can be made optionally visualizable.

**Comment by dpoulton-github** [comment]
You can switch on the plugin "Enable table of contents extension" and put `[[TOC]]` at the top of the note. This will create links to all your headings.

If that is not what you require could you please close this issue and make feature requests via "Features" in the forum?

The Feature Request GitHub template itself says,

>If this is a feature request or a support query, please note that you'll not get an answer here.
>Instead we recommend using the forum where you'll are a lot more likely to get an answer: https://discourse.joplinapp.org/
>The forum is also the right place to submit a feature request so that it can be discussed by other users.

It's just that the maintainer is trying to keep the GitHub issues list under control and for bugs only.

Thanks.

**Comment by aventrax** [comment]
Ok. I totally missed the plugins. Sorry for asking in the wrong place.
