### ISSUE TITLE
update on windows can't sync to iphone

### ISSUE THREAD

**Issue by jhb92** [laurent22/joplin#3280]
on windows  i installed joplin 1.0.216,and config with own nginx webdav. I take a note, and sync,the note sync to mac ,but can't sync to iphone. 

## Environment

Joplin version: 1.0.216 database version is v29
Platform: windows
OS specifics: windows 7

Joplin version: 1.0.216 database version is v29
Platform: mac
OS specifics: macOS catalina 10.15

Joplin version: 10.0.47  database version is v28
Platform: iphone
OS specifics: iphone xr

## Steps to reproduce

1. take note on windows,and sync
2. switch to iphone ,and sync 

## Describe what you expected to happen
notes on windows sync to iphone

**Comment by chrisbeardy** [comment]
I am seeing a similar problem. I use nextcloud for syncing. Notes created on android or windows are syncing everywhere. But notes created Linux are only syncing to my Android.

**Comment by chrisbeardy** [comment]
> I am seeing a similar problem. I use nextcloud for syncing. Notes created on android or windows are syncing everywhere. But notes created Linux are only syncing to my Android.

Just for information, I've updated all my apps, and had to rename my note folders, then it seemed to pick it up and resync everything properly.
