### ISSUE TITLE
Editing in WYSWYG editor replaces messes TOC 

### ISSUE THREAD

**Issue by sumitkchauhan** [laurent22/joplin#3283]
## Environment

Joplin version: Joplin 1.0.216 (prod, darwin)
Platform: MacOS
OS specifics: Catalina - 10.15.4

## Steps to reproduce

1. Create a [TOC] in note-Code View
![image](https://user-images.githubusercontent.com/20319679/82990109-488c4400-a019-11ea-9358-58172ed60817.png)
2. Edit the note in WYSWYG editor
![image](https://user-images.githubusercontent.com/20319679/82990204-6eb1e400-a019-11ea-87c5-d4ac22380c27.png)
3. [TOC] is replaced by static hyperlinks, which no longer automatically update
![image](https://user-images.githubusercontent.com/20319679/82990344-ade03500-a019-11ea-889e-1295e6fac234.png)

## Describe what you expected to happen
Note should be updated with no impact on TOC

**Comment by armaccloud** [comment]
This issue doesn't seem to be fixed and I for one am missing this quite a bit. Since I write larger texts and want to us the TOC, would hereby like to keep this issue open. Is there any news on when it might be picked up?

**Comment by laurent22** [comment]
This is a known and documented limitation of the editor. We don't keep separate issues for each unsupported md plugin
