### ISSUE TITLE
Toggling WYSIWYG Editor changes HTML tables to markdown

### ISSUE THREAD

**Issue by j-krl** [laurent22/joplin#3289]
Joplin v1.0.216
Electron Client
macOS 10.13.6

Steps to reproduce:
1. Create an HTML table in Code View
2. Switch to the WYSIWYG editor and then switch back to Code View

I was making a rather large table with bullet points in it and it seemed easier to create the table using pure HTML as it was easier to read the table contents. I switched to the WYSIWYG briefly just to explore and then switched back to AceEditor. It appears that switching to WYSIWYG had reformatted my tables to be in markdown, which was unfortunate because it made them difficult to read (no line breaks). This may be inherent to the editor and difficult to change but I feel that switching editors should not modify any of the source.

**Comment by WiliTest** [comment]
It would be great if we could prevent Joplin from converting the table from HTML to Markdown
