### ISSUE TITLE
iPhone app crashes reliably after freezing

### ISSUE THREAD

**Issue by d1rewolf** [laurent22/joplin#3290]
Hello there. I just switched from Apple Notes to Joplin yesterday. After transporting most of my notes (encrypted, synced via Dropbox), the Joplin iOS app now will open. It opens to a specific folder, and I'm able to click and view either of the two notes there. But, after I click the "hamburger" menu in the upper left-hand corner, it freezes (won't respond to finger presses), and then eventually crashes. A crash takes less than 15 seconds, and occurs every time. 

Note, if I don't first click one of the displayed notes in the default opened folder at startup, but instead click the hamburger menu first, it works. I can select another folder, at which time the contents are displayed. But then, the app immediately freezes and crashes approx. 15 seconds later.

I dismayed, because desktop Joplin is *EXACTLY* what I've been looking for, but I really need a mobile interface.

I do note that each time I've opened the app, there's something listed under "Synchroise" button. For example, it currently says "Fetching resources: 1/1"

I appreciate any help you can provide, and happy to gather more info!

## Environment

Joplin version: 10.0.47, Database v28, FTS enabled: 1
Platform: iOS, iPhone XR
OS specifics: 13.4.1

## Steps to reproduce

1. Open app.
2. Click around, as described above, or go into Settings and try to select Logs
3. App freezes, and then crashes.

## Describe what you expected to happen
App to function normally.

## Logfile

I would attach the log file, but the name format promised after "The logs will be named in the format: " here (https://joplinapp.org/debugging/) is noticeably absent, and I don't see anything with joplin in it in the readable part of the name (iOS doesn't make this the friendliest list to scroll through). If you'd let me know, I'd be happy to update that page. Additionally, the navigation path to get to the logs has changed in newer versions of the OS.

**Comment by laurent22** [comment]
Unfortunately without a log it's going to be hard to fix, but crashes usually are due to dealing with too large files. Do you have any particularly large resources on your sync target (in the .resources) directory? Also how many notebooks do you have?

**Comment by charlesdaniels** [comment]
I think this might be the same problem I am having, see #2758. As I noted there, gathering logs is problematic.

My suspicion is that it may be related to using encryption, because I didn't start seeing the problem until I turned on E2EE. I think the app is trying to decrypt resources in the background, but it's taking too long and something is timing out.

Usually mine will seem to work for a few seconds to a minute, then it will freeze, then ultimately crashes.

**Comment by jbwiv** [comment]
> Unfortunately without a log it's going to be hard to fix, but crashes usually are due to dealing with too large files. Do you have any particularly large resources on your sync target (in the .resources) directory? Also how many notebooks do you have?

I currently have approx. 50 notes (top-level and sub).

From ncdu:

`   

   74.1 MiB [##########]  26b69de9cf4043a18ea1cb420ace1144                                                                                                                                                                                           
   49.0 MiB [######    ]  42191f6696724325a21d3bf83bb49f42
   33.0 MiB [####      ]  81e93b85bea948a1af95f0c5feef4a7b
   12.7 MiB [#         ]  9ae8883aa7564c459ab47677cd01bf8d
    8.7 MiB [#         ]  b3a9e1a26d93434f975bc23734eb55e6
    7.6 MiB [#         ]  a5bec9dea8a641b7a4cf0d77753b9fd1
    7.3 MiB [          ]  5ca24efd89b44f55b1d6f621944016c6
    7.3 MiB [          ]  96797d38b2494fec9721f9385223de9d
    6.9 MiB [          ]  c127ff2587b94a68aa5071ff5cc3d5b6
    6.7 MiB [          ]  5e6247ae91164886b0e1839fb254907f
    5.4 MiB [          ]  400ff47d13094b8e8fbdd9d4a9ec2e42
    5.0 MiB [          ]  8dc7d57fddd74b189a183e724b3e9675
    4.6 MiB [          ]  f5f4bd787f2c4a9b92ef39b0eeb41aec
    4.3 MiB [          ]  cc40a5070fa4438fbe3bf512218e5422
    3.1 MiB [          ]  94dd0b35be064c3a86a01dffca17aad7
    2.8 MiB [          ]  d47aecaf15a44068ae29c796822254b3
    2.7 MiB [          ]  f786f35515df4b5aa1d8e0565c6630c9
    2.4 MiB [          ]  dff92c508bb44d5e8cc486a1df7f4b64
    2.3 MiB [          ]  aaf2817e9b794df085c150438fa0c8a0
    2.2 MiB [          ]  582e748cc78840c18b0266e835985d7f
    1.9 MiB [          ]  f2456d5387974c67ae3b9e2c41aebe64
    1.6 MiB [          ]  f83a4b761e2841b380fc882e2199014d
    1.4 MiB [          ]  37bb08d114c74640bc775072409d7b64
    1.4 MiB [          ]  496e988460a14edc983fd31bd3b74279
    1.1 MiB [          ]  e88a3d7578564c90906b79968f23e5be
    1.1 MiB [          ]  699304367c7e40b188b275a15b258a69
    1.1 MiB [          ]  0f5e35b863f64d03b433250adae8e958
    1.0 MiB [          ]  4120652810884fac8585192ad772b20f
  960.0 KiB [          ]  aafdf7be48c14849be9e2c3f24b56697
  940.0 KiB [          ]  3f9945e68b5c46f4af5683adb77c65b8
  932.0 KiB [          ]  7999bb1718d14c66b839385256f726a2
  876.0 KiB [          ]  cf273fcb220c484bbc2cff30863226e0
  864.0 KiB [          ]  d1e44a337da74b03814f57211d434a75
  728.0 KiB [          ]  24ba1d977a264a1aa7821622bc3600f5
  652.0 KiB [          ]  d4e69c7f35884efba34d6e1d9030ec8d
  636.0 KiB [          ]  9acd9c39cdac46339fcafb0dd7ab3bfa
  636.0 KiB [          ]  20ce630803064f9f9c843aaf03a942d5
  612.0 KiB [          ]  3b2dfd19b9d54de091e31f56c499afb8
  608.0 KiB [          ]  9e4964f613c443eba29d66007a16242f
  600.0 KiB [          ]  1145ffdfa7c343f6acc5eb94e9709479
  564.0 KiB [          ]  03412c1972eb4533917864e9419dea61
 Total disk usage: 273.0 MiB  Apparent size: 272.9 MiB  Items: 64   

`

**Comment by jbwiv** [comment]
@laurent22 Can you tell me the naming format of the log file? Perhaps it's there...Apple doesn't allow you to view the full name on the phone, just a truncated version.

Thanks!

**Comment by roman-r-m** [comment]
You have a few 'big' notes which might be the root cause. If that's the case then it will be fixed in the next version.

**Comment by d1rewolf** [comment]
Ok, thanks. Anything I can do to help test this next version?

**Comment by roman-r-m** [comment]
If you're able to build the app from sources you can do that and see if this resolves your issue.

**Comment by d1rewolf** [comment]
I will do so. Also, just so I know, could you share the log file naming format?

**Comment by roman-r-m** [comment]
Which log?

**Comment by d1rewolf** [comment]
Sorry, I mentioned it in the initial report...the iOS log mentioned here: https://joplinapp.org/debugging/

See #4 under "Creating a low-level bug report on iOS"...

**Comment by roman-r-m** [comment]
Ah, I see. I'm afraid I am not familiar enough with iOS to know the naming format

**Comment by roman-r-m** [comment]
Apparently the format is `<AppName>_<DateTime>_<DeviceName>`

**Comment by d1rewolf** [comment]
Thanks. I'll experiment a bit.

**Comment by roman-r-m** [comment]
So the fix is released, @d1rewolf can you confirm if you still see the issue on the latest version?
