### ISSUE TITLE
Add megasync as Synchronization target

### ISSUE THREAD

**Issue by Zorin-Dev** [laurent22/joplin#3292]
Hello, joplin team

Please add MEGA.nz (megasync) as synchronization target option.

Thanks,

**Comment by dpoulton-github** [comment]
Could you please close this issue and make feature requests via "Features" in the forum?

The Feature Request GitHub template itself says,

>If this is a feature request or a support query, please note that you'll not get an answer here.
>Instead we recommend using the forum where you'll are a lot more likely to get an answer: https://discourse.joplinapp.org/
>The forum is also the right place to submit a feature request so that it can be discussed by other users.

It's just that the maintainer is trying to keep the GitHub issues list under control and for bugs only.

Thanks.

**Comment by Zorin-Dev** [comment]
Ok, done.

**Comment by aha999** [comment]
@ZorinArch which new issue are you referencing to ?

**Comment by aha999** [comment]
if anyone is searching for it: https://discourse.joplinapp.org/t/add-megasync-as-synchronization-target/9006
