### ISSUE TITLE
Add fonts color to WYSIWYG Editor

### ISSUE THREAD

**Issue by Zorin-Dev** [laurent22/joplin#3293]
Please add fonts color to WYSIWYG Editor.

Thanks,

**Comment by dpoulton-github** [comment]
https://discourse.joplinapp.org/t/to-the-founder-of-this-incredible-program-app-plus-those-working-hard-on-it-please-read/8337/2

***

Could you please close this issue and make feature requests via "Features" in the forum?

The Feature Request GitHub template itself says,

>If this is a feature request or a support query, please note that you'll not get an answer here.
>Instead we recommend using the forum where you'll are a lot more likely to get an answer: https://discourse.joplinapp.org/
>The forum is also the right place to submit a feature request so that it can be discussed by other users.

It's just that the maintainer is trying to keep the GitHub issues list under control and for bugs only.

Thanks.

**Comment by Zorin-Dev** [comment]
Ok, done.
