### ISSUE TITLE
Joplin won't open on MacOS Catalina: EACCES: permission denied

### ISSUE THREAD

**Issue by aretenidas** [laurent22/joplin#3294]
OS: MacOS Catalina 10.15.4 (19E287)
Joplin: 

error:
`
Fatal error:

Error: EACCES: permission denied, unlink '/Users/username/.config/joplin-desktop/tmp'. Path: /Users/username/.config/joplin-desktop/tmp

Error: Error: EACCES: permission denied, unlink '/Users/username/.config/joplin-desktop/tmp'. Path: /Users/username/.config/joplin-desktop/tmp
    at FsDriverNode.fsErrorToJsError_ (/Applications/Joplin.app/Contents/Resources/app.asar/lib/fs-driver-node.js:9:18)
    at FsDriverNode.remove (/Applications/Joplin.app/Contents/Resources/app.asar/lib/fs-driver-node.js:54:15)
`

## Steps to reproduce

1. Download Joplin v1.0.216 https://github.com/laurent22/joplin/releases/download/v1.0.216/Joplin-1.0.216.dmg
2. Open .dmg file
3. Move Joplin to Apps directory
4. Open Joplin
5. Get error that "MacOS Catalina Cannot Scan this file for malicios malware", click OK
6. Go to Settings=> Security and privacy => General => Open anyway
7. Receive another error as in 5 => click Open
8. Receive above error. 

## Describe what you expected to happen

Open app

## Logfile
system.log
`
May 28 15:51:32 computer xpcproxy[1130]: libcoreservices: _dirhelper_userdir: 557: bootstrap_look_up returned (ipc/send) invalid destination port
May 28 15:51:32 computer VTDecoderXPCService[1132]: DEPRECATED USE in libdispatch client: Changing the target of a source after it has been activated; set a breakpoint on _dispatch_bug_deprecated to debug
May 28 15:51:32 computer VTDecoderXPCService[1132]: DEPRECATED USE in libdispatch client: Changing target queue hierarchy after xpc connection was activated; set a breakpoint on _dispatch_bug_deprecated to debug
`
Console log:
`
default	15:53:00.682133-0400	Path Finder	LAUNCHING:0x0-0x78078 Joplin foreground=1 bringForward=1 seed=204 userActivityCount=0
default	15:53:00.690993-0400	runningboardd	Resolved pid 1155 to [executable<Joplin(501)>:1155]
default	15:53:00.693563-0400	loginwindow	-[PersistentAppsSupport applicationReady:] | App: Joplin, ready, updating active tracking timer
default	15:53:00.693662-0400	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Joplin
default	15:53:00.696599-0400	runningboardd	[executable<Joplin(501)>:1155] This process will not be managed.
default	15:53:00.696626-0400	runningboardd	Now tracking process: [executable<Joplin(501)>:1155]
default	15:53:00.697046-0400	runningboardd	Acquiring assertion targeting executable<Joplin(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:173] with description <RBSAssertionDescriptor; foregroundApp:1155; ID: 350-173-351; target: 1155> attributes = {
    <RBSDomainAttribute: 0x7fb1ef60f570; domain: com.apple.launchservicesd; name: RoleUserInteractiveNonFocal; sourceEnvironment: 0x0>;
}
default	15:53:00.697151-0400	runningboardd	Assertion 350-173-351 (target:executable<Joplin(501)>) will be created as active
default	15:53:00.697851-0400	runningboardd	Acquiring assertion targeting executable<Joplin(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:173] with description <RBSAssertionDescriptor; foregroundApp:1155; ID: 350-173-352; target: 1155> attributes = {
    <RBSDomainAttribute: 0x7fb1f1417800; domain: com.apple.launchservicesd; name: RoleUserInteractiveNonFocal; sourceEnvironment: 0x0>;
}
default	15:53:00.697921-0400	runningboardd	[executable<Joplin(501)>:1155] Ignoring jetsam update because this process is not memory-managed
default	15:53:00.698008-0400	runningboardd	[executable<Joplin(501)>:1155] Ignoring resume because this process is not lifecycle managed
default	15:53:00.698021-0400	runningboardd	Assertion 350-173-352 (target:executable<Joplin(501)>) will be created as active
default	15:53:00.698069-0400	runningboardd	[executable<Joplin(501)>:1155] Set darwin role to: UserInteractiveNonFocal
default	15:53:00.698160-0400	runningboardd	[executable<Joplin(501)>:1155] Ignoring GPU update because this process is not GPU managed
default	15:53:00.698604-0400	runningboardd	Finished acquiring assertion 350-173-352 (target:executable<Joplin(501)>)
default	15:53:00.698627-0400	runningboardd	Invalidating assertion 350-173-351 (target:executable<Joplin(501)>) from originator 173
default	15:53:00.698776-0400	runningboardd	Finished acquiring assertion 350-173-351 (target:executable<Joplin(501)>)
default	15:53:00.729581-0400	Joplin	FRONTLOGGING: version 1
default	15:53:00.729598-0400	Joplin	Registering, pid=1155
default	15:53:00.731107-0400	Joplin	CHECKIN: pid=1155
default	15:53:00.741091-0400	launchservicesd	CHECKIN:0x0-0x78078 1155 net.cozic.joplin-desktop
default	15:53:00.741281-0400	Joplin	CHECKEDIN: pid=1155 asn=0x0-0x78078 foreground=1
default	15:53:00.741621-0400	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Joplin
default	15:53:00.752223-0400	Joplin	Registered, pid=1155 ASN=0x0,0x78078
default	15:53:00.752358-0400	Joplin	Registered, pid=1155 cgConnectionID=3d7b7
default	15:53:00.754256-0400	Joplin	BringForward: pid=1155 asn=0x0-0x78078 bringForward=1 foreground=1 uiElement=0 launchedByLS=1 modifiersCount=1 allDisabled=0
default	15:53:00.754306-0400	Joplin	BringFrontModifier: pid=1155 asn=0x0-0x78078 Modifier 0 hideAfter=0 hideOthers=0 dontMakeFrontmost=0 mouseDown=0/0 seed=0/0
default	15:53:00.754509-0400	Joplin	BringForward: pid=1155 asn=0x0-0x78078
default	15:53:00.754637-0400	Joplin	SetFrontProcess: asn=0x0-0x78078 options=0
default	15:53:00.757354-0400	runningboardd	Acquiring assertion targeting executable<Joplin(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:173] with description <RBSAssertionDescriptor; frontmost:1155; ID: 350-173-353; target: 1155> attributes = {
    <RBSDomainAttribute: 0x7fb1f100f2a0; domain: com.apple.launchservicesd; name: RoleUserInteractiveFocal; sourceEnvironment: 0x0>;
}
default	15:53:00.757503-0400	runningboardd	Assertion 350-173-353 (target:executable<Joplin(501)>) will be created as active
default	15:53:00.758076-0400	runningboardd	[executable<Joplin(501)>:1155] Ignoring jetsam update because this process is not memory-managed
default	15:53:00.758394-0400	runningboardd	[executable<Joplin(501)>:1155] Set darwin role to: UserInteractiveFocal
default	15:53:00.758691-0400	runningboardd	[executable<Joplin(501)>:1155] Ignoring GPU update because this process is not GPU managed
default	15:53:00.758855-0400	runningboardd	Finished acquiring assertion 350-173-353 (target:executable<Joplin(501)>)
default	15:53:00.760667-0400	Joplin	Current system appearance, (HLTB: 2), (SLS: 1)
default	15:53:00.764533-0400	Joplin	Post-registration system appearance: (HLTB: 2)
default	15:53:00.777116-0400	distnoted	register name: com.apple.xctest.FakeForceTouchDevice object: net.cozic.joplin-desktop token: f426c pid: 1155
default	15:53:00.903075-0400	Joplin	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x600003b45b80
 (
    "<NSDarkAquaAppearance: 0x600003b45080>",
    "<NSDarkAquaAppearance: 0x600003b44200>",
    "<NSSystemAppearance: 0x600003b44680>"
)>
default	15:53:00.933250-0400	Joplin	Registering for test daemon availability notify post.
default	15:53:00.933502-0400	Joplin	notify_get_state check indicated test daemon not ready.
default	15:53:00.943932-0400	distnoted	register name: com.apple.nsquiet_safe_quit_give_reason object: net.cozic.joplin-desktop token: f42a2 pid: 1155
default	15:53:00.989348-0400	kernel	AGC:: [Joplin Helper (G pid:1157 mux-aware] starting, non-mux-aware app count 0 WS-ready 1 switch-state 0 IG FBs 0 EG FBs 3:1f power-state 0 3D busy HDA busy system-state 1 power-level 20:20 power-retry 0:0 connect-change 0
default	15:53:00.998936-0400	Joplin	SignalReady: pid=1155 asn=0x0-0x78078
default	15:53:01.999787-0400	Joplin	SIGNAL: pid=1155 asn=0x0x-0x491640
default	15:53:01.000432-0400	loginwindow	-[PersistentAppsSupport applicationReady:] | App: Joplin, ready, updating active tracking timer
default	15:53:01.016596-0400	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier net.cozic.joplin-desktop, type: 0: 0x7fb198319ad0 at /Applications/Joplin.app
error	15:53:01.025233-0400	tccd	Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for ACC:{ID: net.cozic.joplin-desktop, PID[1155], auid: 501, euid: 501, binary path: '/Applications/Joplin.app/Contents/MacOS/Joplin'}, REQ:{ID: com.apple.appleeventsd, PID[384], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}
default	15:53:01.040026-0400	hidd	Connection added: IOHIDEventSystemConnection uuid:7C2EB97B-07DE-44CF-9BF6-D32C3A3A3925 pid:1155 process:Joplin type:Monitor entitlements:0x0 caller:GameController: _GCHIDEventCallback + 96 attributes:(null) state:0x0 events:0 mask:0x0
default	15:53:01.050745-0400	hidd	Connection added: IOHIDEventSystemConnection uuid:16DC53C2-60B4-4F60-9CE9-83346877772A pid:1155 process:Joplin type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) state:0x0 events:0 mask:0x0
default	15:53:01.158499-0400	Joplin Helper (GPU)	MessageTracer: Falling back to default whitelist
default	15:53:01.158617-0400	Joplin Helper (GPU)	XPC connection invalidated (daemon unloaded or disabled)
default	15:53:01.158636-0400	Joplin Helper (GPU)	Can't open default search tree file: Operation not permitted
default	15:53:01.192234-0400	Joplin Helper (GPU)	GVA info: preferred scaler idx 1
default	15:53:01.202233-0400	Joplin Helper (GPU)	MessageTracer: Falling back to default whitelist
default	15:53:01.202295-0400	Joplin Helper (GPU)	Can't open default search tree file: Operation not permitted
default	15:53:01.301189-0400	hidd	Connection added: IOHIDEventSystemConnection uuid:C7F76AA3-3FEA-41C7-BBF9-6E5B295EFCAA pid:1155 process:Joplin type:Passive entitlements:0x0 caller:HIServices: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) state:0x0 events:0 mask:0x0
default	15:53:01.800806-0400	syspolicyd	temporarySigning type=1 matchFlags=0x0 path=/var/folders/mp/pclb8rs56tq3n4f25cw1zlk80000gn/T/.net.cozic.joplin-desktop.w8xGqa
default	15:53:01.929723-0400	Joplin	nw_path_evaluator_start [4D8A558C-D92B-4502-9224-DC6DFB1DC8E0 <NULL> generic, indefinite]
	path: satisfied (Path is satisfied), interface: en7, ipv4, dns
default	15:53:02.168540-0400	Joplin Helper	nw_path_evaluator_start [395DFF4C-3F1A-4FC1-B4BE-EC97247562DE <NULL> generic, indefinite]
	path: satisfied (Path is satisfied), interface: en7, ipv4, dns
default	15:53:03.464967-0400	kernel	AGC:: [Joplin Helper (G pid 1157 mux-aware] exiting, non-mux-aware app count 0, runtime: 0:00:02.476
default	15:53:03.470542-0400	hidd	Connection removed: IOHIDEventSystemConnection uuid:16DC53C2-60B4-4F60-9CE9-83346877772A pid:1155 process:Joplin type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) state:0x1 events:0 mask:0x0
default	15:53:03.470592-0400	hidd	Connection removed: IOHIDEventSystemConnection uuid:7C2EB97B-07DE-44CF-9BF6-D32C3A3A3925 pid:1155 process:Joplin type:Monitor entitlements:0x0 caller:GameController: _GCHIDEventCallback + 96 attributes:(null) state:0x1 events:0 mask:0x0
default	15:53:03.470824-0400	hidd	Connection removed: IOHIDEventSystemConnection uuid:C7F76AA3-3FEA-41C7-BBF9-6E5B295EFCAA pid:1155 process:Joplin type:Passive entitlements:0x0 caller:HIServices: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) state:0x1 events:0 mask:0x0
default	15:53:03.474028-0400	runningboardd	Invalidating assertion 350-173-353 (target:executable<Joplin(501)>) from originator 173
default	15:53:03.477767-0400	runningboardd	[executable<Joplin(501)>:1155] Death sentinel fired!
default	15:53:03.481491-0400	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:Joplin, _appTrackingState = 2
default	15:53:03.481379-0400	runningboardd	Invalidating assertion 350-173-352 (target:executable<Joplin(501)>) from originator 173
default	15:53:03.481539-0400	loginwindow	-[PersistentAppsSupport applicationQuit:] | App: Joplin, quit, updating active tracking timer
default	15:53:03.578869-0400	runningboardd	[executable<Joplin(501)>:1155] Ignoring jetsam update because this process is not memory-managed
default	15:53:03.578999-0400	runningboardd	[executable<Joplin(501)>:1155] Ignoring suspend because this process is not lifecycle managed
default	15:53:03.579230-0400	runningboardd	[executable<Joplin(501)>:1155] Ignoring GPU update because this process is not GPU managed
default	15:53:03.579576-0400	runningboardd	Removing process: [executable<Joplin(501)>:1155]
default	15:53:03.584016-0400	runningboardd	Removing assertions for terminated process: [executable<Joplin(501)>:1155]
`

**Comment by larryboy307** [comment]
I had the same issue and was able to find a work around. In a terminal enter:

sudo spctl --master-disable

This is from [https://www.imore.com/how-open-apps-anywhere-macos-catalina-and-mojave](https://www.imore.com/how-open-apps-anywhere-macos-catalina-and-mojave)

It appears that a recent update to Apple's Gatekeeper software hides the ability to run software from any source.

Joplin developers please address this and become a supported program.

Currently using OS 10.15.5

**Comment by aretenidas** [comment]
@larryboy307 @laurent22 

I decided not to disable gatekeeper but go a different route:

Reassigning user config permissions back to the user solved the issue:

chown yourusername: /home/yourusername/.config

**Comment by aretenidas** [comment]
For some reason my solution wasn't posted here after submission.

Problem was is that Mac user /Users/myuser permissions were assigned to root:root, thus Joplin was not able to access /Users/myuser/.joplin folder.
Solution is to change permissions of /Users/myuser folder to myuser:myuser
chown myuser:myuser /Users/myuser

**Comment by joker2009** [comment]
> 

感谢~
