### ISSUE TITLE
Build fails Failed at the joplin@1.0.0 postinstall script - Failed at the sqlite3@4.1.1 install script.

### ISSUE THREAD

**Issue by chwba** [laurent22/joplin#3299]
How can I make it build?
https://pastebin.com/raw/RD8fxnQi

**Comment by ylc395** [comment]
What's your Node version?

**Comment by chwba** [comment]
v14.3.0

**Comment by ylc395** [comment]
sqlite3 fail happened to me, but after I changed my node version, it worked. Just try Node 10 or Node 8.

**Comment by chwba** [comment]
i tried a lower version but got the same error. then i went back to the node installation page and found, that `To compile and install native addons from npm you may also need to install build tools:`, so I isntalled the package and it worked. might be helpful to include this in the requirements

**Comment by ylc395** [comment]
Glad to know it worked. Maybe we can close this issue now.
