### ISSUE TITLE
Option Checkbox UI issue :: Mac OSX

### ISSUE THREAD

**Issue by dev-head** [laurent22/joplin#33]
Hi There, 

Just reporting a UI issue related to the Options view on this app. 

Environment
-------------
- mac osx: 10.11.6
- Joplin: v0.10.28

When under the "Tools" > Options view there are three available checkboxes. When I uncheck them the UI does not show them as unchecked. If i then navigate using the "back" link, and then go back into the options view the checkboxes then show they've been deselected. Looks like the option is working but the UI is not showing the change when you click the checkbox.

**Comment by dev-head** [comment]
sorry, this is a dup of #21

**Comment by laurent22** [comment]
Hi, no problem, thanks for reporting the issue anyway, it's always good to know. This issue should be fixed as of v0.10.30 now available on the website. Please give it a try and let me know if it's fixed.
