### ISSUE TITLE
Pasting images doesn't work on macOS

### ISSUE THREAD

**Issue by petrz12** [laurent22/joplin#330]
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

I often makes screenshots into the Clipboard with e.g. Control-Shift-Command-4. Unfortunately pasting them into the desktop app doesn't work. Pasting it on Github (here) works (Firefox).

It would be nice to have.

**Comment by zelvik** [comment]
Duplicate of #200
