### ISSUE TITLE
Password  or Lock PIN is required when the software is opened

### ISSUE THREAD

**Issue by youmuyou** [laurent22/joplin#3301]
It is recommended to provide a password function, 

which can be made optional when the software is opened,

 if it is not difficult to implement

**Comment by anjulalk** [comment]
Hi @youmuyou,
Would you mind closing this issue and posting it on the forum instead? GitHub issues are used for mostly bugs and accepted feature requests. As stated in the issue template:

>  🤔 Feature requests and support
For non-bug issues we recommend using the forum, where you'll be more likely to get an answer: https://discourse.joplinapp.org/

Thanks!

**Comment by youmuyou** [comment]
> Hi @youmuyou,
> Would you mind closing this issue and posting it on the forum instead? GitHub issues are used for mostly bugs and accepted feature requests. As stated in the issue template:
> 
> > 🤔 Feature requests and support
> > For non-bug issues we recommend using the forum, where you'll be more likely to get an answer: https://discourse.joplinapp.org/
> 
> Thanks!


ok 
Thanks!
