### ISSUE TITLE
Android editor beta crashes on backspace (also randomly moves cursor)

### ISSUE THREAD

**Issue by TeknikalDomain** [laurent22/joplin#3303]
## Environment

Joplin version: 1.0.329
Platform: Android
OS specifics: Android 10, Kernel 4.19.81

## Steps to reproduce

1. Enable editor beta in settings
2. Attempt to edit a note - the cursor may randomly move backwards, you'll be typing with a few letters in front of the cursor
3. Press backspace, the app will immediately crash, with nothing noted in the logs at all.

## Describe what you expected to happen

1. The app to not crash on attempt to delete text.
2. The editor beta to not move the cursor behind text as it's being typed.

## Logfile

[syncReport-1590809105814.txt](https://github.com/laurent22/joplin/files/4705042/syncReport-1590809105814.txt)

**Comment by roman-r-m** [comment]
Duplicate: https://github.com/laurent22/joplin/issues/3199
