### ISSUE TITLE
Audio Recording Feature

### ISSUE THREAD

**Issue by imp1sh** [laurent22/joplin#3306]
I would love a feature that let me directly record audio.
I know I can attach any kind of file but I would love to see a very simple audio recording feature for the connected microphone so I don't need a third party application for that.

**Comment by roman-r-m** [comment]
Work in progress:
https://github.com/laurent22/joplin/pull/3027
https://github.com/laurent22/joplin/pull/3079

**Comment by roman-r-m** [comment]
Also this issue duplicates https://github.com/laurent22/joplin/issues/468

**Comment by dpoulton-github** [comment]
Also could you please close this issue and make feature requests via "Features" in the forum?

The Feature Request GitHub template itself says,

>If this is a feature request or a support query, please note that you'll not get an answer here.
>Instead we recommend using the forum where you'll are a lot more likely to get an answer: https://discourse.joplinapp.org/
>The forum is also the right place to submit a feature request so that it can be discussed by other users.

It's just that the maintainer is trying to keep the GitHub issues list under control and for bugs only.

Thanks.
