### ISSUE TITLE
Error when installing on Linux

### ISSUE THREAD

**Issue by hrqmonteiro** [laurent22/joplin#3307]
## Environment

Joplin version: Latest
Platform: Linux 
OS specifics:  Void Linux

## Steps to reproduce

1. Just trying to install and getting this error 
2. Is shows me this error and i'm unable to open Joplin by typing or terminal or trying to select on my apps menu
3. 

## Describe what you expected to happen

I expected to work...

The error:
![2020 05 30-16 53 13 screenshot](https://user-images.githubusercontent.com/17055027/83337967-10de0000-a296-11ea-843f-bfaffadcbee5.png)

**Comment by dpoulton-github** [comment]
1 - It would appear that the Joplin appimage installer is unable to create a desktop icon as the desktop environment you have on Void Linux is not known to it. Hence "NOT DONE, unknown desktop". The install script script you ran shows it is looking for `$DESKTOP =~ .*gnome.*|.*kde.*|.*xfce.*|.*mate.*|.*lxqt.*|.*unity.*|.*x-cinnamon.*|.*deepin.*|.*pantheon.*|.*lxde.*`

2 - Joplin is "installed" as an AppImage not a package. Default location `~/.Joplin/Joplin.AppImage`. You can try running that.

If for any reason you need further support installing Joplin could you please raise it in the [forum](https://discourse.joplinapp.org)? It's just that the maintainer is trying to keep the GitHub issues list under control and for bugs only.

Thanks.
