### ISSUE TITLE
WYSIWYG editor escapes markdown syntax

### ISSUE THREAD

**Issue by MilanRusev** [laurent22/joplin#3308]
When writing markdown in the WYSIWYG editor (directly, without using the toolbar buttons), the formatting isn't applied and when switching to code view the special characters are escaped.

**Writing in WYSIWYG editor:**
![image](https://user-images.githubusercontent.com/15890495/83338642-0724be80-a2cf-11ea-9008-72c5958af48b.png)
**Switching to code view:**
![image](https://user-images.githubusercontent.com/15890495/83338647-1c99e880-a2cf-11ea-968b-8625a232b0aa.png)

## Environment
Joplin version: 1.0.216 (prod, win32)
Revision: 4eb680d6 (master)
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. In WYSIWYG editor write some markdown syntax (without using the toolbar buttons), e.g. a header: `# my title`
2. The text in the WYSIWYG editor isn't formatted as a header
3. Switch to code view, the `#` is escaped: `\# my title`
4. The same thing is not only for headers but for all markdown syntax - lists, links, bold, code blocks etc

## Describe what you expected to happen
You should be able to write markdown in the WYSIWYG editor and the special characters shouldn't be escaped behind the scenes. And you should be able to see the formatting as you type (I guess it'll happen if you just don't escape the special characters).

**Comment by virtadpt** [comment]
Ye gods, this.  It's messed up more of my notes than I can keep track of.

**Comment by dpoulton-github** [comment]
@MilanRusev

Not a dev just a user.

The WYSIWYG editor does not convert markdown codes typed in the editor. That's actually what the toolbar and keyboard shortcuts are for. When you type `# My Title` the WYSIWYG editor interprets that literally and so escapes the markdown.

IIRC the feature you were expecting has been suggested by others on the [Joplin forum](https://discourse.joplinapp.org) as a way forward as it is developed.

@virtadpt

I guess that's why this message appears when switching WYSIWYG on!

>This is an experimental WYSIWYG editor for evaluation only. Please do not use with important notes as you may lose some data! See the introduction post for more information. TO SWITCH TO THE MARKDOWN EDITOR PLEASE PRESS "Code View".

**Comment by MilanRusev** [comment]
I see, so it's like that by design. Personally for me it'll be a stopper from using it though, it's more intuitive for me if it didn't escape the special characters. Maybe have it as an option in the settings?

Joplin is a great app though, huge thanks to the developers.

**Comment by Derkades** [comment]
WYSIWYG = What You See Is What You Get.

If you see a hash or asterisk, you will get a hash or asterisk, not a heading or bullet point. If you want to use markdown, use the markdown editor.

**Comment by cadolphs** [comment]
If markdown in WYSIWYG wasn't escaped, then how would you expect to enter markdown characters? You'd need to then escape them manually, which is the opposite of what you want to do in a WYSIWYG editing experience.

**Comment by Yeboster** [comment]
As @Derkades said, at least some keyboard shortcuts would help a lot. Otherwise the implementation of WYSIWYG in Notion is not a bad idea: adding a special command char `/` to trigger a list of all possibles typography styles (Headings, bold, tables, ...).
