### ISSUE TITLE
Desktop version for Windows 32 bits

### ISSUE THREAD

**Issue by Ada-lover** [laurent22/joplin#331]
Dear Laurent,

When I download the 1-0-79 Windows version from your "https://joplin.cozic.net/" page, and try to install it under Windows 10, I get an error message "Windows 64 bits is required".
1) Don't you provide a 32 bits version ?
2) If no (I'm sad) could you notice it on your main page ?

Thanks a lot

**Comment by laurent22** [comment]
I'm afraid a 32-bit version will be not supported, unless someone can build and maintain it.
