### ISSUE TITLE
Integrated drawing bed software

### ISSUE THREAD

**Issue by SuperDan1** [laurent22/joplin#3317]
Is it possible to call picgo and other software to directly upload the pictures in markdown to the picture bed, similar to typora If this is a feature request or a support query, please note that you'll not get an answer here.

Instead we recommend using the forum where you'll are a lot more likely to get an answer: https://discourse.joplinapp.org/

The forum is also the right place to submit a feature request so that it can be discussed by other users.

**Comment by dpoulton-github** [comment]
> If this is a feature request or a support query, please note that you'll not get an answer here.
> 
> Instead we recommend using the forum where you'll are a lot more likely to get an answer: https://discourse.joplinapp.org/
> 
> The forum is also the right place to submit a feature request so that it can be discussed by other users.

Could you please close this issue and make feature requests via "Features" in the forum just as the template text you left in your posting asks.

It's just that the maintainer is trying to keep the GitHub issues list under control and for bugs only.

Thanks.
