### ISSUE TITLE
Please add an option to set the app to don't do any auto sync with cloud untill sync button tapped.

### ISSUE THREAD

**Issue by 3j9fkyahunqoxwqu** [laurent22/joplin#3319]
Hello
Thank you for your great app.
i had a problem with joplin that can considered as a bug so i created issue here. sorry if it is in wrong place.

I use android version and disabled auto sync of joplin and setted it to manual synchronization with onedrive.

but when i create a note joplin instantly tries to sync it with cloud and this behavior can cause issues in some scenarios:

(actually it caused one conflict issue that fortunately i could solve it because of great conflict notebook that appeared.)

scenarios:
1. in unstable networks
2. when we frequently switch and copy paste some texts from several other apps on mobile to gather them all in joplin. specially in middle range and low end phones with low amount of RAM available. 

it is occurred many times for me that i switched from joplin to another lightweight app (say for ex. a clipboard manager like clipper that is very light on RAM and resource usage) and when i switched back to joplin, joplin was killed in the middle of auto synchronization of newly created note. 

i also did rather every workaround available for it (like force closing all other apps that is not needed before using joplin and disabling all battery optimizations for joplin and etc but the problem still occur many times.

what i suggest here is that please add an advanced option to settings in android so we can completely disable cloud sync untill we manually tapped on sync button.

Please add this.

with many more manufacturers using strict killing algorithms in android nowadays, this will prevent many future issues.

Also this helps in reducing number of api calls for the cloud sync provider so it will reduce the probability of may be temporary or permanent account ban, ip ban and etc from cloud storage provider.

Thank you very much.
Stay safe.
Regards.

**Comment by 0xRustlang** [comment]
Unstale

**Comment by 0xRustlang** [comment]
@laurent22 what do you think about this proposal?

**Comment by laurent22** [comment]
Sorry this is a bug tracker, it's not for feature requests
