### ISSUE TITLE
systray icon disappears after upgrade to 1.0.216 on Manjaro Linux

### ISSUE THREAD

**Issue by imraven** [laurent22/joplin#3320]
## Environment

Joplin version: 1.0.216 and 1.0214 (haven't tried others)
Platform: Linux
OS specifics: Manjaro 64-bit (XFCE4) up to date with pacman as of 6/1/2020

## Steps to reproduce

1. Upgrade Manjaro to latest `pacman -Syu`
2. Pull down latest AUR for joplin `https://aur.archlinux.org/packages/joplin/` which pulls joplin source 1.0.216
3. Go through usual steps to compile package `makepkg`, etc. and install.
4. Launch Joplin, tray no longer appears.  Joplin is obviously running in the background and comes forward if the bin is called.

## Describe what you expected to happen

Systray icon to appear.

## Logfile

[console.log](https://github.com/laurent22/joplin/files/4718097/console.log)

**Comment by m-angelov** [comment]
Unfortunately the package in AUR is not supported by the developers. Try contacting the maintainer of the package.

A bit off topic - I just updated to the 1.0.216 AppImage on Arch and the tray icon works. It even fixed a bug I had, where clicking on the tray icon with the left mouse button opened the right click menu, so I had to click "open" to get the program to show.
