### ISSUE TITLE
White bars and unreadable status on mobile dark theme (not duplicated: read description)

### ISSUE THREAD

**Issue by duarteocarmo** [laurent22/joplin#3325]
When switching to dark theme on mobile, there are two white bars,  on top and bottom of the screen. Turning the interface very unpleasant. 

Moreover, the OLED theme makes it impossible to see the current time on iOS. (See screenshot on the right)

I know that this has been previously mentioned in #2694. But **this issue has been closed and locked for some reason**. 

And there are also two possible [fixes](https://github.com/Rahulm2310/joplin/commit/3eaeba24228b2ae31298a5a6e4a8a893981a71ac) that I have found. 

The issue is still the same: 

<p align="center">
<img src="https://user-images.githubusercontent.com/26342344/83725767-c87e6380-a642-11ea-8051-388e2763935b.PNG" alt="drawing" width="175"/>
<img src="https://user-images.githubusercontent.com/26342344/83725771-c916fa00-a642-11ea-8810-c3bed2ff4086.PNG" alt="drawing" width="175"/>
</p>

## Environment

Joplin version: 10.0.47
Platform: iOS
OS specifics: iOS 13.4.1 on iPhone 11 Pro Max

## Steps to reproduce

1. Open App
2. "Configuration" settings
3. Scroll down to "Appearance"
4. Select Dark or OLED Dark

## Describe what you expected to happen
- Expect to see color coherence on the dark themes. 
- Expect time, signal and battery to remain white. 

Thanks a lot for all of the work in this great app, I really love it ❤️ !

**Comment by laurent22** [comment]
It's fixed but the fixed version hasn't been released yet.

**Comment by duarteocarmo** [comment]
@laurent22, status bar coloring also? Just making sure you read that part 😄 

Thanks for great work btw, love the product :)
