### ISSUE TITLE
WebDav does not sync in iOS

### ISSUE THREAD

**Issue by rapedapeda** [laurent22/joplin#3329]
## Environment

Joplin version: 10.0.47
Platform: iOS
OS specifics: iOS

## Steps to reproduce

1. Install Joplin on iOS
2. Connect to webdav server (which I use with the Joplin desktop (MacOS) app.
3. Connection test is successful
4. Click sync

I get the exact error as described in [#2103](https://github.com/laurent22/joplin/issues/2111). The error came up after a switch of phones in late 2019. Because of that I have used Joplin exclusively on my laptop. FF to today, the error seems to be still in place.

![IMG_0426](https://user-images.githubusercontent.com/22884864/83861332-bd016a00-a720-11ea-82e6-16c0844b01eb.png)
![IMG_0427](https://user-images.githubusercontent.com/22884864/83861335-be329700-a720-11ea-8d71-fd04964c6065.png)

**Comment by kuraci** [comment]
image lost.

**Comment by randomthought** [comment]
I was previously getting this on my mobile using NexCloud. I was able to resolve it by ensuring that the WebDav url is using `https` instead of `http`. Please give that a try.

**Comment by rapedapeda** [comment]
Thanks for the suggestion. I am using a https server url. The problem sadly still exists.

**Comment by randomthought** [comment]
Are you using Nginx? If you are using Nginx, please post your Nginx configurations, I might be able to help. If Apache, post your configurations here as well, someone else might be able to help.

**Comment by rapedapeda** [comment]
No I am not, I use a solution called [Stack by TransIP ](https://www.transip.nl/stack/).

**Comment by metbril** [comment]
See #2153 for Stack @rapedapeda

**Comment by GanbaruTobi** [comment]
My iOS App also isn't able to pull changes excluding the initial setup. After that it can upload changes but doesnt download changes successfully OR isnt displaying the changes. There is no error in the logs. It says it synced successfully but it didnt change the text files shown.
