### ISSUE TITLE
Synchronization isn't a backup feature

### ISSUE THREAD

**Issue by Ada-lover** [laurent22/joplin#333]
Dear Laurent,

Another question.
My previous smartphone fell in water and I lost some of my data (I had to backup more often, I know ...). So before using Joplin each day I need to be sure that the notes I write with the Android app can be saved in Cloud, and reversely restored from Cloud to a new phone if needed.
I tried to do that with the synchronization feature of Joplin (on Android) but when I erase all my notes on Joplin and starts synchronization with the Cloud, this empties the Cloud repository instead of downloading the saved Cloud notes to my phone. (I imagine you think : it's normal, this guy doesn't understand what is a synchronization function ...)
So what do I have to do for my backup need ?

Thanks a lot

**Comment by laurent22** [comment]
The recommended way to backup is to use the export functionality of the desktop or CLI app. Otherwise if you want to start fresh on a mobile app you need to uninstall and re-install it. Otherwise, the sync info will indeed stay and can cause unexpected behaviours.

**Comment by scollovati** [comment]
A question: can you create an easy export function for all the notebooks? 
In this way creating a backup will be much more fast and efficient.

**Comment by zhang-ray** [comment]
@scollovati it seems like that's not an easy work https://github.com/laurent22/joplin/issues/698
