### ISSUE TITLE
joplinapp.org contains two links that lead to GitHub error 404 pages

### ISSUE THREAD

**Issue by avanderberg** [laurent22/joplin#3330]
The page https://joplinapp.org/ contains two links that lead to GitHub error 404 pages:

- The link `What is a conflict?` in the menu links to https://joplinapp.org/conflict/
- The link `command-line mode` in the section `Importing from Markdown files` (which is the second occurence on this page, the first one works correctly) links to https://joplinapp.org/terminal.md#command-line-mode

## Environment

Platform: Chrome, and Firefox
OS specifics: macOS

## Steps to reproduce

1. Open https://joplinapp.org/ in the browser
2. Click on the links mentioned above

## Describe what you expected to happen

The links lead to the corresponding README files.

**Comment by tessus** [comment]
The first error is easy to fix.

The second one will be a bit harder because it does not make any sense. The same function is used to generate the link. And the links in the source are the same, so the results should be the same. Very puzzling.

**Comment by laurent22** [comment]
Thanks for the info @avanderberg! The second issue was due to using a greedy vs non-greedy match.
