### ISSUE TITLE
Last error: Error: The maximum request length supported is 4MB

### ISSUE THREAD

**Issue by techandsec** [laurent22/joplin#3336]
When trying to sync my encrypted notes with OneDrive I am receiving the following error in the bottom left corner of the desktop app. 

<img width="245" alt="Screen Shot 2020-06-06 at 20 54 20" src="https://user-images.githubusercontent.com/61643810/83957692-fc6eaa00-a837-11ea-81c8-dfdba8451504.png">

I have checked "Tools > Notes Attachments" for attachments over 4MB but didn't see anything over 3.8MB. To be on the safe side I deleted it and now the biggest attachment is 2.8MB. When I try to sync with OneDrive again I still receive the same error. When I log into my other laptop and phone I do not see the notes that I have created and updated.

## Environment

Joplin version: 1.0.216 (prod, darwin)
Platform: Joplin Desktop
OS specifics: MacOS 10.14.6

## Steps to reproduce

1. 
2. 
3. 

## Describe what you expected to happen

I expect my notes to be able to sync to my OneDrive so that I can access them from any of my devices.

## Logfile

[syncReport-1591490565256.csv.zip](https://github.com/laurent22/joplin/files/4741256/syncReport-1591490565256.csv.zip)

**Comment by TheOnlyTrueJonathanHeard** [comment]
I don't know why this error occurs but can you upgrade to 1.0.217 (Per-Release)? In this Version the onedrive 4 MB Limit has been solved.

**Comment by techandsec** [comment]
I have upgraded to the Pre-Release and it seems to be resolved now. Thanks @TheOnlyTrueJonathanHeard

**Comment by techandsec** [comment]
I have upgraded to the Pre-Release and it seems to be resolved now. Thanks @TheOnlyTrueJonathanHeard
