### ISSUE TITLE
Code editor with dark themes is unreadable in v1.0.217

### ISSUE THREAD

**Issue by alexdevero** [laurent22/joplin#3337]
Code editor with any dark theme is unreadable in v1.0.217.

_Note: I am not using any custom CSS._

## Environment

Joplin version: v1.0.217
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Dowload v1.0.217
2. Apply dark theme from presets
3. Make sure to use Code view

## Describe what you expected to happen

The text will be readable as it was in previous version.

## Screenshot

![joplin v1 0 217](https://user-images.githubusercontent.com/4237724/83960402-bee63d00-a888-11ea-9659-e82894a800fa.PNG)

**Comment by CalebJohn** [comment]
Thanks for reporting this, this was a stupid mistake on my part (typo). Since you're on the cutting edge please do try out the new beta code editor (can be toggled under the note settings). The editing experience should be a bit nicer.
