### ISSUE TITLE
Feature Request: add checksums for the desktop applications

### ISSUE THREAD

**Issue by kuekerino** [laurent22/joplin#334]
### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

It would be nice if you could add some checksums for the desktop applications :)

**Comment by laurent22** [comment]
You mean just the SHA-1 of the apps? Do you have an example of project that does this (just to see how they present this)?

**Comment by kuekerino** [comment]
Exactly.

Unfortunately I do not and it is hard to find a project that provides them on github. One I found was:
https://github.com/Genymobile/scrcpy
For the Windows versions.

I think I have seen projects where they just add a third column to the download matrix. Maybe you could try that
