### ISSUE TITLE
Local notes get deleted after updating from 1.0.201 to 1.0.216

### ISSUE THREAD

**Issue by jeanmarie18** [laurent22/joplin#3340]
## Environment

Joplin version: 1.0.216
Platform: Linux
OS specifics: Ubuntu 18.04.4 LTS x86_64

## Steps to reproduce

1. Had the 1.0.201 installed before (using it since the 28 april)
2. Yesterday I set up Joplin encryption + synchronization with my Nextcloud share
3. I was faced to the problem described in #3004 (could however upload 254 items by clicking on and off on the "Toggle notes list" button). Was happy to discover at the end of the post that the 1.0.216 would handle the problem.
4. ran the Linux update script: no error
5. launched Joplin
6. after may be 1 minute, synchronization started automatically (btw, i would like it does not start automatically but I don't understand why it does so)
7. all my local notes disappeared from Joplin ! (I did a JEX export yesterday before implementing synchonisation) and only the most recent one is till there but in conflict.
8. In my Nextcloud there are 341 encrypted .md files (I don't know if they represent all my 83 or so notes).

## Describe what you expected to happen
1. No automatic synchronisation at startup
2. All my local notes should have been left untouched ! (fortunately I did a JEX export before implementing encryption + sync).

## Logfile
Sorry I have no debug file because it was not activated before this problem.
However I have the log.txt file if needed and it does have errors (don't want to publish it as there is a encryption_cipher_text in it which I guess is secret data but I am not sure if this is important).

**Comment by jeanmarie18** [comment]
I want to have my notes up and running again so I start right away to recover them with my JEX file :-)

**Comment by jeanmarie18** [comment]
One last thing before I restore my notes: yesterday just after having setup my Nextcloud webdav share and having clicked on "Check status" it said (and still does):
_"The Joplin Nextcloud App is either not installed or misconfigured. Please see the full error message below:
Unsupported WebDAV URL format: https://myncsrv.com/remote.php/dav/files/myAccountNumber/myTargetFolder"_
I don't know what is this "Nextcloud App" ... I see there is a "Notes" app in my nextcloud server but I don't use it as I use Joplin...

**Comment by jeanmarie18** [comment]
I tried a second sync after the JEX restore: again it deleted my local notes, but this time not all of them.
I concluded my joplin contents was not clean although I did not do incorrect file manipulations. The only one I know is the renaming of the WebDav target folder during my second sync (before the restore) while the sync was executing; as a first user I did not pay attention to the short 5 minutes cycle.
So I completely uninstalled Joplin and re-downloaded and installed the latest 1.0.216 version, then restored my JEX file.
Then I re-enabled encryption and could successfully sync: and yes, the #3004 problem is not here anymore :-)
I still don't understand why I still have the above message when I click "Check status" ... ?

**Comment by tessus** [comment]
Please see the following wntry in the FAQ:

[All my notes got deleted after changing the WebDAV URL!](https://joplinapp.org/faq/#all-my-notes-got-deleted-after-changing-the-webdav-url)

> I still don't understand why I still have the above message when I click "Check status" ... ?

This is for the experimental sharing functionality which requires a Nextcloud app. If you don't know what it is.... There's a help link, right next to it. Click on it.

Neither of those things are bugs. Please use the forum for user questions.
