### ISSUE TITLE
Links broken in Android app

### ISSUE THREAD

**Issue by shbach** [laurent22/joplin#3344]
## Environment

Joplin version: 1.0.330
Platform: Android
OS specifics: 9

## Steps to reproduce

1. Have link in note
2. Click link

![Screenshot_20200607-101314](https://user-images.githubusercontent.com/5298745/83975285-f9130700-a8a7-11ea-8233-9803f21e8f47.jpg)

## Describe what you expected to happen

The link should work. Instead, clicking a link to another Joplin note does nothing and clicking a web link opens inside the Joplin app...

![Screenshot_20200607-101321](https://user-images.githubusercontent.com/5298745/83975335-337ca400-a8a8-11ea-9789-a39a1d7dcc61.jpg)

**Comment by nshtg** [comment]
Attachments like pdf files don't open either.

**Comment by roman-r-m** [comment]
This is where it's broken:
https://github.com/laurent22/joplin/blob/071ea5854f894c0faabe02e10d68c747535caa74/ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/link_open.js#L66

On mobile it renders this:
```
onclick='window.ReactNativeWebView.postMessage("joplin://51993dd55b0543e0ab4977123cd8d33d", { resourceId: "51993dd55b0543e0ab4977123cd8d33d" }); return false;'
```

whereas previously it used to be
```
onclick='window.ReactNativeWebView.postMessage("joplin://51993dd55b0543e0ab4977123cd8d33d"); return false;'
```
