### ISSUE TITLE
Losing focus on keyboard layout change

### ISSUE THREAD

**Issue by faerics** [laurent22/joplin#3345]
When editing a note sometimes I need to change the language of writing. and it causes a caret to disappear. After the change I need to click in the editor to continue typing. If I type not doing that click, the text will not appear in the note.

## Environment

Joplin version: Joplin 1.0.216 (prod, linux)
Commit: 4eb680d (master)
Platform: Linux x86_64, Windows 
OS specifics: Linux mint 19, Win 10

## Steps to reproduce

1. Open any note in Joplin, place the cursor in the text editor.
2. Change the language via hotkey (`Alt+Shift` for me).
3. See that a caret diappeared,
4. Type something in a new language and see that the text has not been written.

## Describe what you expected to happen

The caret should stay where it was before changein the language and I should be able to type without any additional clicks.

## Debug log

I collected the log as described [here](https://joplinapp.org/debugging/).

In console I saw that when I hit `Alt+Shift` changing the language this message appears (after two the same messages that appeared on the start):
```
Got ipc-message: noteRenderComplete [undefined]
```

In `log.txt` there is no information logged by this action.

**Comment by tessus** [comment]
The cursor position is always lost when you switch to another note. It's always reset to the first line.

The view position in the editor/viewer is retained though.

**Comment by faerics** [comment]
@tessus nice to know such a things!

Howewer, let me clarify that the issue is not about switching between the notes, it is about losing caret while you are working on one perticular note.
Sorry if the initial comment was unclear...

**Comment by tessus** [comment]
For Joplin this is the same thing. Joplin moves away from the note when you open the preferences (to change the language) and Joplin opens the note, when you close the preference window.

**Comment by roman-r-m** [comment]
I think @faerics means switching keyboard layout not the UI language.

**Comment by tessus** [comment]
Thank you. I missed that part, but yes "language of writing" points to that.

**Comment by faerics** [comment]
@roman-r-m thank you for pointing that out!
Yes, the word I needed was 'layout'.

**Comment by roman-r-m** [comment]
I can't reproduce on 
Joplin 1.0.218 (prod, win32)

Client ID: 8129c25cca08408db9608fbf677fee34
Sync Version: 1
Profile Version: 30
Keychain Supported: No

Revision: 5be8c2cd (master)

**Comment by faerics** [comment]
@roman-r-m Well, it is quite difficult to reproduce, I did some testing for about 30m to find out.
First of all, this seems to be the issue with an `Alt` key.

- If I change the hotkey to something that do not use `Alt`, like `Ctrl+Shift`, the caret is in place, no bug.
- If I press the `Alt` key and then release it, the note will lose a caret - bug
- If I press `Alt`, then press `Shift`, then release `Shift`, then release `Alt` the layout changes and there is no bug.
- If I press `Alt`, then press `Shift`, then release `Alt`, AND THEN release `Shift` the layout changes and there IS the bug.

So the steps to reproduce are now:

1. Open any note in Joplin, place the cursor in the text editor.
2. Press `Alt`
3. Release `Alt`
3. See that a caret diappeared.

Maybe something is bind on that key? This is definetely Joplin specific, there's no such a problem in any other app.

Could you try to reproduce it now?

**Comment by roman-r-m** [comment]
> If I change the hotkey to something that do not use `Alt`, like `Ctrl+Shift`, the caret is in place, no bug.

I am using Alt+Shift to switch and that's how I tested it.



> If I press the `Alt` key and then release it, the note will lose a caret - bug

This isn't a bug -- this is to access the menu without using the mouse, many (most?) apps have it e..g Notepad++, Firefox, SublimeText etc

**Comment by faerics** [comment]
@roman-r-m 
Yes, but it works only if `Alt` is the only key pressed. Thank's for the hint -- now I see that when I press `Alt + Shift`, the top memu bar option `File` is selected. 
Note that the order of releasing keys matters, see the discussion above.

Well, I think you agree that this should not happen when `Alt` pressed in combo.
But it does happen.

**Comment by m-angelov** [comment]
I have the same issue since 1.0.177 - submitted here: https://github.com/laurent22/joplin/issues/2298

**Comment by roman-r-m** [comment]
I saw a few related issues in electron issue tracker, haven't had time to look into this yet

**Comment by m-angelov** [comment]
I did some testing before seeing your comment, the results of which are written up below. Now I checked in Code (also an Electron app) and it has the same issue. I haven't ran into it, because I never switch the layout in it. So I've changed Joplin with Electron in the notes below :)

I can replicate this on Windows as well. Check this [short video](https://u.pcloud.link/publink/show?code=XZWSyOkZtgIyV3bJJhJH6FJlfsGElm2Cl0Fy):
- at ~ 8 seconds in, I press `Alt`, and you can see the menu changing. Then I spam `F`, but the menu is not showing up - the keyboard is "stuck". Then I press `Alt` again and contunue writing in the note.
- I do this again at ~23 to ~27 seconds.
- After that I _hold_ `Alt` and press `F` (`Alt+F`) and the menu is working as expected.

So ~~Joplin~~ Electron should either:
- enable the "sticky toggle" mode as in Firefox - press `Alt`, activate the menu and wait for shortcut keys.
- do "anticipation toggle" - while `Alt` is pressed, activate the menu and wait for shortcut key, but when `Alt` is released, the focus should be returned to the editor.

On Windows I wasn't able to replicate the `Alt+Shift` issue with layout change, that I have using Linux - it works okay. But I feel that if the second "anticipation toggle" mode is applied, this issue will be fixed on Linux.

**Comment by faerics** [comment]
IMO better to keep this open to make guys at Electron act faster on this issue.

**Comment by IvanovAndrew** [comment]
This issue still requires the attention

**Comment by kioan** [comment]
This issue still exists on Joplin 1.4.19 (prod, Linux).
When changing keyboard layout using the Alt+Shift shortcut, if the Alt key is released after the Shift, the focus is lost as it is described [here](https://github.com/electron/electron/issues/28088#issuecomment-800089637).

**Comment by roman-r-m** [comment]
> This issue still exists on Joplin 1.4.19 (prod, Linux).
> When changing keyboard layout using the Alt+Shift shortcut, if the Alt key is released after the Shift, the focus is lost as it is described [here](https://github.com/electron/electron/issues/28088#issuecomment-800089637).

1.4.19 is very old, the latest is 1.7-something

**Comment by kioan** [comment]
I have downloaded the latest Joplin app from the official [website](https://joplinapp.org/). The site claims that the version of the downloaded file is 1.7.11 (the filename of the Linux binary is Joplin-1.7.11.AppImage).
After running this app, the [about screen shows 1.4.19](https://i.imgur.com/0WHo9zp.png). At first I thought that I installed a wrong version, so I tried it again. Perhaps there is something wrong in the site?

**Comment by kioan** [comment]
The bug when changing keyboard layouts using the Alt+Shift shortcut, still exists in the latest Joplin version 1.7.11.

```
Joplin 1.7.11 (prod, linux)

Client ID: d2bb797b625c47a3bb9bc775c38c043a
Sync Version: 2
Profile Version: 34
Keychain Supported: No

Revision: f560563 (master)
```
