### ISSUE TITLE
Please add an option to Associate multiple external editors. For example: the table can be opened with Excel.

### ISSUE THREAD

**Issue by XXXXSSSS** [laurent22/joplin#3346]
关联多个外部编辑器。比如：表格可以用excel打开，文章可以用word打开，发送到博客Markdown文章可以用typora打开。
Associate multiple external editors. For example: the table can be opened with Excel, the article can be opened with word, and the article sent to the blog markdown can be opened with typora.

**Comment by dpoulton-github** [comment]
Could you please close this issue and make feature requests via "Features" in the [forum](https://discourse.joplinapp.org)?

The Feature Request GitHub template itself says,

>If this is a feature request or a support query, please note that you'll not get an answer here.
>Instead we recommend using the forum where you'll are a lot more likely to get an answer: https://discourse.joplinapp.org/
>The forum is also the right place to submit a feature request so that it can be discussed by other users.

It's just that the maintainer is trying to keep the GitHub issues list under control and for bugs only.

Thanks.
