### ISSUE TITLE
Multiple Sync Issues

### ISSUE THREAD

**Issue by ho1ger** [laurent22/joplin#3350]
Since some time I have sync issues both with the MacOS app and the iOS apps. I use nextcloud 19 as a backend.

On the MacOS app I suddenly got sync errors like

```
Abgeschlossen: 05/06/2020 11:23
Letzte Fehlermeldung: Error: Invalid property format: so: <<--text from note-->> - id: 55...4e parent_id: 55...38
```

Other, similar errors, complain about Invalid property format: "is_shared".

Somebody on reddit suggested to me to remove the conflicting notes and see what happens. After removing the conflicting notes, the MacOS app was able to sync changes from/to the server. So I thought everything is fine. 

But, I also tried to update my iOS apps' notes and here I found the sync process to be stuck. 

![2020-06-09_15-06-58_IMG_1737](https://user-images.githubusercontent.com/8535968/84151374-923a4d00-aa63-11ea-9abe-fd0a07ade505.PNG)

I do not know if bot issues are related or something totally different. If I can provide more detail, please tell me what to provide.

**Comment by stepanpos** [comment]
I have the same problem - Joplin on Android and Joplin on Windows 10. Both version can't sync with Nextcloud 19. Some notes are incompletle - Ivalid property format. There missing ends of notes. 
But on the server is Notes complete. 
Can you help me?

**Comment by mahibi** [comment]
Same problem here.
- Nextcloud Version 19
- Joplin Desktop Version 1.0.201 (running on Linux Mint 19.3)
- Android Version 1.0.331

**Comment by mrtpcet** [comment]
Same issue for me with NC 19

**Comment by Derkades** [comment]
Same issue on Nextcloud 19.
```
Last error: Error: On file 672566b9cdd04a72b500f4293c222138.md: Missing required property: type_:
```
File on the server:
```
id: 672566b9cdd04a72b500f4293c222138
parent_id: 5c8ab1500c2b44f7b29e712dcf64de05
created_time: 2020-07-13T23:34:21.917Z
updated_time: 2020-07-13T23:34:31.783Z
is_conflict: 0
latitude: [removed]
longitude: [removed]
altitude: 49.5367
author: 
source_url: 
is_todo: 1
todo_due: 0
todo_completed: 0
source: joplin
source_application: net.cozic.joplin-mobile
application_data: 
order: 1594683261913
user_created_time: 2020-07-13T23:34:21.917Z
user_updated_time: 2020-07-13T23:34:31.783Z
encryption_cipher_text: 
encryption_applied: 0
markup_language: 1
is_shared: 0
type_: 1# 
```
The `#` at the end is added by zsh, indicating that there is no newline character on the last line.

**Comment by mahibi** [comment]
For me Joplin is nearly not usable since this bug appears. The Android app shows the error log (below the sync button) which is quite large depending on the failing note, so that often the overview oft the notes is not visible.

Can't grade down to nextcloud 18 because i use a managed NC hosting.

Please let me know if any more information is necessary form the logs etc..

**Comment by julieni** [comment]
Hi,

just to mention I have reproducible issue with nextcloud 19 corrupting files due to wrong size reporting, which leads to potential file truncate. See https://github.com/nextcloud/server/issues/21315#issuecomment-659423374 for tests reports.

**Comment by mahibi** [comment]
@julieni so at https://github.com/nextcloud/server/issues/21315 the comments look like it is fixed with NC 19.0.1

my hosting provider updated to 19.0.1 but the android joplin APP keeps complaining (can't test the dektop APP at the moment). Can the corrupted files be fixed somehow with NC 19.0.1 or do i have to use backups of these files to replace the corrupted ones?

**Comment by julieni** [comment]
Hi, upgrading will not recover your files I think. I mean, if file is corrupted on the nextcloud server's storage, it still will be after upgrading. But after upgrade, you should not see any new corrupted file.

**Comment by Derkades** [comment]
It is possible to restore corrupted files. If it's a local note that won't upload, the easiest way is to create a new note and copy note contents over. In some cases you have to modify the files on the remote. Edit the file on the remote and remove the line with `is_shared:`. Make sure there is **no trailing newline** or joplin will give new errors. Many text editors, for example nano, automatically add a newline. Remove it using `truncate -s -1 <file>` after editing.

**Comment by prayingmantis287** [comment]
I had this same issue after upgrading to Nextcloud 19, and may have accidentally discovered a fix for it. Unfortunately, I cannot re-test to confirm.

I began removing the `is_shared:` line from some of the offending files, but then decided against proceeding further in case it caused some unintended future issues. After restoring from backup the files that I had edited the properties on, some of them were not showing up in the Nextcloud UI or syncing to devices. I recalled from previous Nextcloud issues the command to rescan for orphaned files in users' Nextcloud directories, and proceeded to do so on the directory containing the Joplin markdown files.

Once the scan completed, the restored files showed up in the Nextcloud UI and synced to other devices. I then opened Joplin, and the sync completed with no errors.

A possible theory is the metadata on some of the Nextcloud files gets corrupted after the upgrade and rescanning the directory writes the correct values.
<br>

Nextcloud file scan on single user's Joplin directory:

- `sudo -u abc php /config/www/nextcloud/occ files:scan --path="/nextcloud_user_id/path/to/Joplin/md_files"`

To scan all users and directories (this can take a few hours, depending on the number of files users have):

- `sudo -u abc php /config/www/nextcloud/occ files:scan --all`

I run Nextcloud as a docker, so the username is `abc`. I believe the username for non-container instances is `www-data`. One of the two should work.
<br>

Again, I can't confirm this will work for everyone, but hoping it does.

**Comment by mahibi** [comment]
This Issue apeared again. Might have been caused by the upgrade to Nextcloud 19.0.2.
See https://github.com/nextcloud/server/issues/21315#issuecomment-686980682

Server:
Nextcloud 19.0.2

Desktop:
Nextcloud Desktop Client 2.6.5 (KDE)
Joplin 1.0.201 (prod, linux)

Android:
Joplin 1.0.336

PS:
After i decided to delete the corrupt files, the Issue https://github.com/nextcloud/server/issues/21170 appeared. Dont't know if this could be related to the bug dicussed here..
