### ISSUE TITLE
Sync error "item cannot be null" due to duplicated file contents

### ISSUE THREAD

**Issue by samtuke** [laurent22/joplin#3351]
I was getting "item cannot be null" sync errors. After checking the two notes concerned, I saw that the contents within those files was duplicated. Where the file should have ended, it looked like:

```
encryption_applied: 1
updated_time: 2020-06-09T14:06:03.402Z
created_time: 
type_: 13id: 5088f892d59f415fb8a8c6b3f25895ec
parent_id: 
item_type: 
item_id: 
```

Note: `type_: 13id: ` which is invalid.

It appears that the whole note content was duplicated and appended. I deleted the duplicate content, but then got other errors about missing properties, including `parent_id`. I don't know why those properties would be missing. Error message:

```
Fetched items: 1/1.
Completed: 09/06/2020 16:26
Last error: Error: On file 5088f892d59f415fb8a8c6b3f25895ec.md: Missing required property: type_: id: 5088f892d59f415fb8a8c6b3f25895ec parent_id: item_type: item_id: item_updated_time: title_diff: body_diff: metadata_diff: encryption_cipher_text: ...
```

So far my solution was to simply delete those notes, which means I've lost access to the content for now (due to encryption).

I didn't notice any crashes or other possible causes of the problem.

Using two Joplin clients: Linux Desktop and Android, with E2EE, and private Nextcloud as sync host.

## Environment

Joplin version: 1.0.175
Platform: Linux
OS specifics: Fedora 31

## Steps to reproduce

Not sure what precisely triggered this issue unfortunately

**Comment by laurent22** [comment]
We had this issue at some point due to a bug in an Android lib we were using, but it was fixed a while back. You mention v175 for desktop, which is quite old. What mobile version do you use?

**Comment by samtuke** [comment]
> We had this issue at some point due to a bug in an Android lib we were using, but it was fixed a while back. You mention v175 for desktop, which is quite old. What mobile version do you use?

1.0.331, Database v30

Thanks - I'll try updating the desktop version.
