### ISSUE TITLE
Cannot Paste Gif Images

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [laurent22/joplin#3352]
## Environment

Joplin version: 1.0.216
Platform: Linux 
OS specifics: Manjaro 20.0.3 Lysia

## Steps to reproduce

1. Open Joplin
2. Paste Gif Image
3. Done

## Describe what you expected to happen

Gif should work as gif and do not get converted to PNG.

**Comment by laurent22** [comment]
Then it's a png in the clipboard

**Comment by laurent22** [comment]
When you copy the image, the software you're using puts a png in the clipboard, even if the edited file is a gif. So there's nothing special to do on Joplin side. If you want to get an exact format you need to import the file as gif in Joplin directly.
