### ISSUE TITLE
android: no access to external editor

### ISSUE THREAD

**Issue by aisbergde** [laurent22/joplin#3355]
Reading the description of Joplin it should be possible to edit in external editor.
This works on desktop but I can't find how to use external editor in Android

## Environment

Joplin version: 1.0.331
Platform: Android
OS specifics: MIUI Global 11.0.8 (Android 10)

## Steps to reproduce

1. open a note to edit 
2. search everywhere (there are not so many places where to search)
3. 

## Describe what you expected to happen

I should be able to edit a note in an external editor

**Comment by roman-r-m** [comment]
It's not supported on Android
