### ISSUE TITLE
Multitable with checkboxes dont get saved

### ISSUE THREAD

**Issue by yann1cks** [laurent22/joplin#3356]
## Environment

Joplin version: Joplin 1.0.216 (prod, win32) & Joplin (1.0.329, Android)
Platform: Windows, Android
OS specifics: Windows 10 (1909), Android 10

## Steps to reproduce
1. Activate the multitable plugin.
2. Create a Multitable and add checkboxes in any cell (a simple example can be found below)
3. Switch to the rendered markdown and mark the checkbox. I will be checked in the rendered markdown, but in the markdown code it will not be checked. And therefore the change will not be saved.

![Multitable checkbox](https://user-images.githubusercontent.com/50637827/84259213-6cbb4b00-ab18-11ea-9c16-d15e7c63fbed.gif)

## Describe what you expected to happen
I would expect that the checkbox is saved as checked. If you check the checkbox in the markdown code it will show in the rendered view and will be saved correctly. 

## Example-Table in Markdown
````
| Column 1	| Column 2    |
|--------------	|--------------|
| some text	| - [ ] Item 1  | \
|   			| - [ ] Item 2  |
`````

**Comment by laurent22** [comment]
Checkboxes in tables are not supported
