### ISSUE TITLE
Import from Evernote ENEX as HTML is skipping large number of articles

### ISSUE THREAD

**Issue by test32443** [laurent22/joplin#3359]
## Environment

Joplin version: 1.0.216 Portable
Platform:  Windows
OS specifics: Windows 10 x64

## Steps to reproduce

1. Export 985 Notes from Evernote into ENEX file
2. Import ENEX file as HTML into Joplin
3. 

## Describe what you expected to happen
I expected to see 985 notes in Joplin, instead I see 710 notes only

## Logfile
[Console.log](https://github.com/laurent22/joplin/files/4762265/Console.log)

Comments:
1. I saw a similar issue opened in the past: https://github.com/laurent22/joplin/issues/55, but that issue seems to be closed and it does not seem to list a resolution or workaround and I am still experiencing it on the latest version of Joplin.
2. I can attach log-database.txt file if needed, but it is huge (>200MB uncompressed, 17MB zip file)
3. No obvious errors in log.txt file, so I am not attaching it

**Comment by laurent22** [comment]
I'd like to fix these issues but it's difficult without looking at the ENEX file, I don't assume you can share it? If not, I see there's for example an issue on a note titled "macosxhints.com - An advanced script/web solution to track stolen Macs". Could you export just this one as ENEX and upload it here?

Otherwise could you identify a few notes that are present in Evernote but not in Joplin, and export just these ones and attach them here?

**Comment by test32443** [comment]
I don't mind sharing notes, since most of them are captures of public web pages. I've attached macosxhints.enex (and I can confirm that it does not import into Joplin even as a single note) - please let me know if you would like to see any other notes.
[macosxhints.zip](https://github.com/laurent22/joplin/files/4767265/macosxhints.zip)

**Comment by laurent22** [comment]
Somehow I have no problem importing this particular enex file. Are you able to share a set of notes that show the problem you're having? It doesn't have to be the 985 notes, but let's say if you can replicate it with 20 notes and it only import 18 of them, then it should be enough to fix the bug.

**Comment by test32443** [comment]
Hmm, strange. Here is another export of 22 notes - I was able to import only 3 of them in Joplin
[22notes.zip](https://github.com/laurent22/joplin/files/4775685/22notes.zip)
I should mention that I am using Portable version and I wonder if it might be impacting anything.

**Comment by laurent22** [comment]
Thanks for the note samples, the bug should be fixed from the next version.
