### ISSUE TITLE
Multi-user team capability

### ISSUE THREAD

**Issue by maraymer** [laurent22/joplin#336]
Is it within scope of the project to produce a team collaboration version?

**Comment by laurent22** [comment]
It would be within the scope of the project. I guess it's already partially possible by having multiple apps syncing to the same sync target.

**Comment by maraymer** [comment]
Ah.  That sounds perfect.  My company is working to move our note taking to a self-hosted app and, so far, you are the most attractive choice.  

So, we'll try setting it up and giving it a try.  Your technology stack matches ours pretty close so we might even contribute to the project should we find a need for a feature it lacks.

**Comment by laurent22** [comment]
That would be great, any contribution is welcome.

**Comment by despens** [comment]
When using nextcloud for storage, it would be enough to enable certain notebooks be synced to different directories on the server. Then nextcloud users could decide with whom to share which notebook.

**Comment by cast-away** [comment]
@maraymer any joy with your tests? highly interested in how to progress multi user collaboration within Joplin

**Comment by maraymer** [comment]
@cast-away your project is still on our goal list for moving to replace EverNote this year.  We've been sidetracked with acquiring new clients as well as writing some of our own code -- plus adopting Mattermost instead of Slack and Kimai to replace our 3rd party time-tracking.  Lots of migration to private cloud stuff this year!

**Comment by cast-away** [comment]
@maraymer thanks for the heads up, it seems you are busy! I really like Joplin but it's not my project though :)

**Comment by instantlinux** [comment]
+1 for enabling shared notebooks under separate Nextcloud / webdav folder (and for being able to move/copy between private and shared content).

**Comment by ebousse** [comment]
In my case I would be interested in something closer to #778: I would need to define a different storage server for each root notebook that I have. The reason is that I may have notes taken for different projects/contexts that each has its own storage place (eg. nextcloud, mostly).

**Comment by lord-aerion** [comment]
I'd like to add my vote to this feature request.

I've fully replaced Google Keep and Evernote with Joplin and have permanently closed my Evernote account this week. I've even made a donation to Laurent this week to show my support for this project.

However, the one Evernote feature that Joplin is lacking for me personally is the loss of the ability to share notes, whether as read-only or editable.

It would also need support for encryption for those using 3rd party services such as Dropbox or OneDrive. I use Syncthing myself, but still have encryption enabled as, well, one never can be sure :-)

Ideally this feature would allow the use of separate sync solutions on a per folder basis, so that I could use Syncthing to sync notes between my devices, and, say, WebDAV and Nextcloud for shared notes/notebooks with friends/family/colleagues.

**Comment by chrisalbertson** [comment]
If this is ever implemented, you might start by making to user(s) deal with accdess control by deling driectly with the access control system of the base storage system but this requires a sophisticarted user.    It really needs to be handled at the applications level.

There is all kind of issues, for example, "cut and paste" between pages that have overlapping but non-identical access control lists.   A good idea is to do all the back-end storage with a "real" SQL based DBMS and let the DBMS handle both access control and remote syncing to different DBMS servers to data safty.  Bt this completely changes the nature of the storage and required something like MySQL or Postgressql of the server.

Access control is have to get right, one way is to not bother and make the each user control this at the WebDAV level or to tag each chunk (chunk=page?) of data with access control and have a DBMS apply the access rues.

You also have an issue with concurrency and the need for a possible rollback of edits where one person "stomps" on another person's work.    PostgreSQL is gd for "point in time" rollbacks even if there are hundreds of concurrent "atomic" changes that overlap.

My point is that a multi-user note-taking app that keeps data secure and prevents users for stomping on each other is a TOTALLY different beast and is 10X more complex and will likely need a more sophisticated storage model.  What you would be building would be more like a WIKI and you can see how Wikis don't use flat files for storage.

This is a bigger project that might be out of scope.  It would place Joplin into the enterprise space.

**Comment by maraymer** [comment]
This is still a relevant issue but I have no time at present to address it.
