### ISSUE TITLE
Text dragging doesn't work in code view

### ISSUE THREAD

**Issue by alexdevero** [laurent22/joplin#3361]
In earlier versions o Joplin it was possible to select text in editor (code view) and drag it elsewhere to change the line(s) at which it is placed. This feature no longer works in the latest v1.0.218.

## Environment

Joplin version: 1.0.218
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Add text to a note
2. Select text
3. Try to drag the text to change its location

## Describe what you expected to happen

I will be able to drag the text and change the line(s) at which it is placed.

**Comment by laurent22** [comment]
Unfortunately that was never officially supported (just a feature of Ace Editor) and I've disabled it as it's not that commonly used, and had serious problems that could cause data loss.

**Comment by alexdevero** [comment]
@laurent22 Okay, got it.
