### ISSUE TITLE
Allowing to select custom fonts

### ISSUE THREAD

**Issue by despens** [laurent22/joplin#337]
It would be nice if the application would respect the desktop environment's fonts or allow to set them manually. I believe there is only a proportional and a non-proportional option required?

### Operating system

- Linux

### Application

- Desktop

**Comment by dayfuaim** [comment]
Yes, and I think that Android version also needs this.
Especially, monospaced font in editor.

**Comment by despens** [comment]
This is already "50% done" since it has become possible to change the editor monospace font :smiley:

**Comment by despens** [comment]
The monospace font is not used when rendering backticked markdown:

![selection_00640](https://user-images.githubusercontent.com/571494/38833763-c02f2f58-41c6-11e8-8ef4-b755065c77e3.png)

**Comment by laurent22** [comment]
> The monospace font is not used when rendering backticked markdown

This is as expected since the font at the moment is only to customise the editor.

**Comment by Tommy-01** [comment]
- Linux
- Windows

The font in the writeable note window, is just to small. 
An option to change the size of the font, without knowing of css or anything like this would be nice.
Like the most simple text editors can do.

**Comment by Torsten-K** [comment]
> The font in the writeable note window, is just to small.
> An option to change the size of the font, without knowing of css or anything like this would be nice.

The font size is too small for me, too.

**Comment by josegarciaclm95** [comment]
Yup, the size is a problem. 

I had to switch to the dark theme because, with the white one, the part of some letters was barely visible. 
Being able to customize the font family and size on the writable note window would be awesome.

**Comment by subi54** [comment]
@josegarciaclm95 did you try changing font & font size in userstyle.css?

**Comment by Torsten-K** [comment]
> […] did you try changing font & font size in userstyle.css?

I cannot find such a file on Ubuntu 18.04, I looked for it in _/home/[…]/.config/Joplin/_ and _/home/[…]/.config/joplin-desktop/,_ and Catfish (a file searcher) did not find userstyle.css or any other CSS file.

**Comment by josegarciaclm95** [comment]
@subi54 I didn't know about the existance of that file, but your comment made me look closely on the General settings page and I found the `Editor font size` and the `Editor font` options.

I might make a pull request after modifying the layout, UX can be improved easily as far as I can tell.

Thank you for pointing that out @subi54 !

**Comment by subi54** [comment]
@Torsten-K I'm unfamiliar with Linux/Ubuntu but try making a new file: `userstyle.css`. It might work.

@josegarciaclm95 css doesn't work for you?
```
body {
    font-face: Menlo;
    font-size: 12px/em;
}
```
Should work or whatever your preferences are. Also, I am unsure if vw(viewport) value works with this. Something to look into.

You'll have to restart after changing the css values.

**Comment by josegarciaclm95** [comment]
@subi54 I didn't find that file, but my comment was made from a user point of view. Setting the general preferences worked for me.

**Comment by subi54** [comment]
@josegarciaclm95 Alright, good to know.

**Comment by dayfuaim** [comment]
Editor in Android build _still_ needs monospace font.

**Comment by rcarmo** [comment]
Another call for custom font selection - I need that in iOS since the defaults are hard to read for me.

**Comment by Torsten-K** [comment]
@subi54: Making a new file called userstyle.css with font stylings does not have any effect in my case.
@josemariagarcia95: Changing the font for the editor in the preferences at least works,

Anyway, it would still be nice to be able to change the font for the preview pane.

**Comment by Torsten-K** [comment]
Since version 1.0.169 or so, the editor’s font size is configurable, so from my side the topic can be closed.

**Comment by dayfuaim** [comment]
@Torsten-K Yes, of course.

And what about not only Default or Monospace, but custom `.ttf`?
At least in plans.

**Comment by funkrusher** [comment]
in visual-studio code i can import fonts via the css import-command. This does not seem to work in the userstyle.css of joplin.

For example: 
i want to use the exellent LaTeX Font "Computer Bright" which is available as a web-font. See. https://github.com/dreampulse/computer-modern-web-font

In visual-studio code i can just drop the font into the folder on the local filesystem and load it with the following import-commands: 

<pre>
@import url("./font/Bright/cmun-bright.css");
@import url("./font/Bright Semibold/cmun-bright-semibold.css");
@import url("./font/Classical Serif Italic/cmun-classical-serif-italic.css");
@import url("./font/Concrete/cmun-concrete.css");
@import url("./font/Sans/cmun-sans.css");
@import url("./font/Sans Demi-Condensed/cmun-sans-demicondensed.css");
@import url("./font/Serif/cmun-serif.css");
@import url("./font/Serif Slanted/cmun-serif-slanted.css");
@import url("./font/Typewriter/cmun-typewriter.css");
@import url("./font/Typewriter Light/cmun-typewriter-light.css");
@import url("./font/Typewriter Variable/cmun-typewriter-variable.css");
@import url("./font/Upright Italic/cmun-upright-italic.css");

body {
  font-family: "Computer Modern Serif", "Segoe UI", Roboto, Helvetica, Arial, sans-serif; 
  font-size: 20px;
}
...
</pre>
