### ISSUE TITLE
README Sponder table ill-formatted

### ISSUE THREAD

**Issue by hirokihokari** [laurent22/joplin#3370]
In Sponsor section of the README, the markdown table is not formatted properly, which results in raw text render.
![Screen Shot 2020-06-15 at 18 01 29](https://user-images.githubusercontent.com/7416486/84639148-f1e89a80-af32-11ea-9191-845d73a8754a.png)

The bug was introduced here: ff232480173fa2826503894915fbfedf0bb8bde7

Now the header says 3 columns, divider says 4 columns.

## Describe what you expected to happen
Not sure if it should be 4 column table or 3 like done previously so, but I think you can afford 4 even on a narrow display. But for mobile, have 3 and put the 4th sponsor on the second row should be fine, too.

**Comment by CalebJohn** [comment]
Thanks for the bug report, this has been fixed in #3362
