### ISSUE TITLE
Weird scrolling behaviour on iPhone

### ISSUE THREAD

**Issue by Pimon1** [laurent22/joplin#3371]
When opening a note that is longer than one screen height, I can scroll it in the view mode (as expected), but when I tap on the edit button, scrolling becomes a little weird. See here:

![joplin](https://user-images.githubusercontent.com/40452746/84640719-5c311900-aefa-11ea-8903-fac6faf51f30.gif)

## Environment

Joplin version: 10.0.47
Platform: iPhone 11 Pro
OS specifics: iOS 13.3.1

## Steps to reproduce

1. Create a note like `Line 1 <insert a few line breaks> Line 2 <line breaks>Line 3 <line breaks>` until you have some text that exceeds the height of the edit view
2. (Let it save, go back to the overview, re-open the note and tap on the edit button)
3. Tap on the Line with "Line 2" and try to scroll down.

The rubber band effect is visible, but it doesn't scroll down.

## Describe what you expected to happen

Scrolling in the edit view should work as in the view mode.

## Logfile

If required, I'll attach it.

**Comment by tmoravec** [comment]
Can confirm on iPad and iPhone 8, too. Moving the cursor somewhere else (possibly several times) "unlocks" the scrolling.

**Comment by tmoravec** [comment]
Looks like it has been fixed by a recent update. I can't reproduce the behaviour on either iPad or iPhone.
