### ISSUE TITLE
Cannot read in files unless launching appimage with sudo

### ISSUE THREAD

**Issue by roof98** [laurent22/joplin#3379]
The problem I am having.
I have set up filesystem sync of joplin files across multiple devices and added a device running PopOs to that. When syncing from the main screen, it will not display any files others than the ones I have created on that device. I have set r w permissions for all files in the sync folder. 

However, it is able to sync them in fine when I launch the program with sudo ./Joplin.appimage --no-sandbox. In this case, with the exact same sync settings, I am able to read in and properly display and edit *all* .mb files in the folder, not just ones I created on that device. 

I hesitate to call this a bug, as it is most likely good ol user error, so maybe if there were some recommended fixes that would be appreciated. The file permissions on this version are the same as on the other devices which are problem free.

Latest and release versions seem to have this error for me

**Comment by NRGLine4Sec** [comment]
Same error for me
