### ISSUE TITLE
Set StartupWMClass=Joplin in the appimage.desktop file

### ISSUE THREAD

**Issue by shuhaowu** [laurent22/joplin#338]
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

Without StartupWMClass=Joplin, the desktop environment will not associate the GUI app launched with the desktop file (and thus the icon). Adding this line will fix this problem.

**Comment by laurent22** [comment]
That would be an issue for electron-builder I think. It seems there's already one open actually - maybe add your comment there? https://github.com/electron-userland/electron-builder/issues/2098

**Comment by milankni** [comment]
I am wondering if adding an icon (as per https://github.com/electron-userland/electron-builder/issues/2098 ) would really solve this issue - not even mentioning https://github.com/joshwcomeau/guppy/pull/267#issuecomment-425242410 which states that 1 % of Linux users is not much of an interest for the dev.

Similarly, running digikam AppImage leads to two icons in the launch bar - one icon is for the "favourite" (as per desktop file) and another one for the running window. StartupWMClass groups the two icons together.

As a workaround, would it be possible to patch the desktop file to include the StartupWMClass?

**Comment by CalebJohn** [comment]
It looks like this has been fixed in recent versions.
source: I can see it in my appimagekit-joplin.desktop

**Comment by archont00** [comment]
Indeed. The current AppImage has it and "works for me".
