### ISSUE TITLE
Feature Request: Import SpringPad-Notes

### ISSUE THREAD

**Issue by asraelvudogel** [laurent22/joplin#339]
### Operating system

- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

Please add the feature to import notes from the shutdown SpringPad. 
They are all stored in single json file. The attachments are stored as normal files in a attachments subfolder and linked within the json file.

If you have any interest to integrate that, I can give you an example.

**Comment by asraelvudogel** [comment]
okay, let's give an example:
[{
  "tags":[],
  "text":"<div>\r\n<p><b><font class=\"page2rssins\">Sonntag, 25. Mai 2014<\/font><\/b><\/p>\r\n<div>\r\n<table>\r\n<tr>\r\n<td>\r\n<p><font><span class=\"page2rssins\">Umwoben von Lenz und Bl&uuml;tenduft feiert heute K&ouml;nig Friedrich August seinen 49. Geburtstag, und mit dem Landesherrn feiert sein patriotisches Volk, mit ihm empfinden die unz&auml;hligen Tausende, die in Liebe und Verehrung der Person des Monarchen sich verbunden f&uuml;hlen. Dem sch&ouml;nen und innigen Familienverh&auml;ltnis, das den K&ouml;nig mit seinen Kindern verbindet, einem Verh&auml;ltnis, das sich in seiner Lieblichkeit jedem aus dem Volke t&auml;glich offenbart, entspricht in weiterem Rahmen ein Vertrauensverh&auml;ltnis zwischen F&uuml;rst und Volk. K&ouml;nig Friedrich August hat es vom ersten Tage seiner Regierung an verstanden, in nahe Beziehungen zu seinem Volke zu treten und sich die Sympathie weiter Volkskreise zu sichern. ...<\/span><\/font><\/p>\r\n<\/td>\r\n<\/tr>\r\n<tr>\r\n<td>\r\n<p><img src=\"http:\/\/ift.tt\/1pnHtt1\" class=\"page2rssins\"><\/p>\r\n<\/td>\r\n<\/tr>\r\n<tr>\r\n<td>\r\n<p><font class=\"page2rssins\">Auch heute noch wird das Wirken des letzten S&auml;chsischen K&ouml;nigs verkl&auml;rt aber dennoch Alles Gute zu nunmehrigen 149. Geburtstag des Friedrich August. Auf dieser Ansichtskarte mit Tochter Anna in einem Lokal zu sehen, ehrfurchtsvoll von den &uuml;brigen G&auml;sten betrachtet. Kann mir vielleicht sagen um welches Etablissement es sich handeln k&ouml;nnte? Also ich kann es nicht deuten.<\/font><\/p>\r\n<\/td>\r\n<\/tr>\r\n<\/table>\r\n<\/div>\r\n<p><font class=\"page2rssins\">Bildquelle: Ansichtskarte. Bestand eigenes Archiv<\/font><\/p>\r\n<\/div>\r\n<br>\r\nThis post has been generated by <a href=\"http:\/\/page2rss.com\/\">Page2RSS<\/a> <img style=\"display: none;\" width=\"1\" height=\"1\" src=\"http:\/\/ift.tt\/TIRXsS\"><img style=\"display: none;\" src=\"http:\/\/ift.tt\/1pnHtJf\"><br>\r\nhttp:\/\/ift.tt\/1pnHtt1<br>\r\nfrom Das t&auml;gliche Dresdenbild http:\/\/ift.tt\/1pnHtJh<br>",
  "liked":false,
  "notebooks":["2638b7b5-7709-4251-a99f-d1ec6d6620f4"],
  "image":"attachments\/26389d50-a6a8-4f65-a3ec-cc9f8758b380.jpg",
  "type":"Note",
  "modified":"2014-05-25T03:57:42+0000",
  "created":"2014-05-25T03:57:41+0000",
  "complete":false,
  "name":"Sonntag, 25. Mai 2014",
  "attachments":[
      {
      "image":"attachments\/26389d50-a6a8-4f65-a3ec-cc9f8758b380.jpg",
      "type":"Photo",
      "url":"attachments\/26389d50-a6a8-4f65-a3ec-cc9f8758b380.jpg"
      }],
  "uuid":"26372cb1-1bae-413f-8a35-8cb94b51adab",
  "rating":0.0,
  "public":false
  },
  {
  "tags":[],
  "text":"<div>\r\n<p><b><font class=\"page2rssins\">Sonnabend, 24. Mai 2014<\/font><\/b><\/p>\r\n<div>\r\n<table>\r\n<tr>\r\n<td>\r\n<p><font><span class=\"page2rssins\">...<\/span> <span class=\"page2rssins\">In dem Kasten befand sich eine auf Pergament geschriebene Urkunde aus dem Jahre 1722 und 1728, durch die Kurf&uuml;rst August der Starke, K&ouml;nig von Polen, dem damaligen Besitzer der sogenannten Lohsch&auml;nke, die fr&uuml;her an Stelle des jetzigen Gasthofes zum Wei&szlig;en Adler stand, die Konzession zum Beherbergen und zum Ausschank von Bier und wein erteilte, weil der Inhaber der Lohsch&auml;nke, Gottfried G&uuml;nzel, dem Kurf&uuml;rsten &#132;von einem sehr gef&auml;hrlichen Falle&#147; gerettet habe.<\/span> <span class=\"page2rssins\">...<\/span><\/font><\/p>\r\n<\/td>\r\n<\/tr>\r\n<tr>\r\n<td>\r\n<p><img src=\"http:\/\/ift.tt\/1p3hPw7\" class=\"page2rssins\"><\/p>\r\n<\/td>\r\n<\/tr>\r\n<tr>\r\n<td>\r\n<p><font class=\"page2rssins\">Ich wusste auch noch nicht, seit wann an diesem Orte eine Schankgenehmigung vorliegt und vor allem, wer diese erteilte. Allerdings wird heute schon l&auml;ngst nicht mehr ausgeschenkt und auch wenn aus der Ruine wieder einmal etwas geworden ist, dann wird man wohl kaum im Wei&szlig;en Adler wieder einkehren k&ouml;nnen. Das heutige Bild des einstigen bekannten Ball-etablissements wurde mir freundlicherweise zur Verf&uuml;gung gestellt. Danke.<\/font><\/p>\r\n<\/td>\r\n<\/tr>\r\n<\/table>\r\n<\/div>\r\n<p><font class=\"page2rssins\">Bildquelle: Ansichtskarte. Sammlung Hirsekorn.<\/font><\/p>\r\n<\/div>\r\n<br>\r\nThis post has been generated by <a href=\"http:\/\/page2rss.com\/\">Page2RSS<\/a> <img style=\"display: none;\" width=\"1\" height=\"1\" src=\"http:\/\/ift.tt\/1twFpRP\"><img style=\"display: none;\" src=\"http:\/\/ift.tt\/1p3hQAg\"><br>\r\nhttp:\/\/ift.tt\/1p3hPw7<br>\r\nfrom Das t&auml;gliche Dresdenbild http:\/\/ift.tt\/1twFq85<br>",
  "liked":false,
  "notebooks":["2638b7b5-7709-4251-a99f-d1ec6d6620f4"],
  "image":"attachments\/2638e66e-1b67-4a87-8f6f-3e8ba9f5d2b0.jpg",
  "type":"Note",
  "modified":"2014-05-24T07:11:16+0000",
  "created":"2014-05-24T07:11:15+0000",
  "complete":false,
  "name":"Sonnabend, 24. Mai 2014",
  "attachments":[
      {
      "image":"attachments\/2638e66e-1b67-4a87-8f6f-3e8ba9f5d2b0.jpg",
      "type":"Photo",
      "url":"attachments\/2638e66e-1b67-4a87-8f6f-3e8ba9f5d2b0.jpg"
      }],
  "uuid":"263e8a0b-7d0f-4933-8c07-258fed0d4477",
  "rating":0.0,
  "public":false
  }]

These are two notes with a text (formated in html) and an attachment.

**Comment by laurent22** [comment]
It's very unlikely that would be supported given how complex it would be to parse the HTML, resources, etc. However if Springpad exports to ENEX format (Evernote export file), you can use this, and then import these files into Joplin.

**Comment by asraelvudogel** [comment]
I tried to import them into Evernote, but it doesn't work. So I think, I have to write some kind of python-script to convert the notes to md-files (one note, one file). Maybe this could work.

**Comment by laurent22** [comment]
Converting HTML to Markdown is complicated, so maybe an easier solution would be to convert them to ENEX files (which have HTML content so you won't need to convert).
