### ISSUE TITLE
CodeMirror adds inner shadow for solarized theme

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#3395]
@CalebJohn one issue I've noticed, which might be a Code Mirror feature, but looks like a bug in this context is that they add an inner shadow when the theme is solarized light (and maybe on other themes too?), and as a result it looks a bit strange:

<img width="917" alt="image" src="https://user-images.githubusercontent.com/1285584/85227250-31e8cb00-b3d4-11ea-929a-7e9c4cfe4b35.png">

Just to be sure, I think it would make sense to add a `.CodeMirror` CSS rule that always disable shadows regardless of the theme, what do you think?

**Comment by CalebJohn** [comment]
Yes I agree, I actually thought I had disabled that earlier, but I did slip the fix into #3360 . I can split it into another pull request if you want.

**Comment by CalebJohn** [comment]
#fixed in #3360
