### ISSUE TITLE
Images not copied from Layout view

### ISSUE THREAD

**Issue by vectisere** [laurent22/joplin#3403]
Copying from Layout view doesn't seem to copy image data correctly. 

Pasting into MS Word or Outlook has an image inline with the text, but it is a blank image. 
![image](https://user-images.githubusercontent.com/60317513/85286265-34a5f780-b48a-11ea-8f67-1f5c055cab58.png)

Pasting into Google Docs or Word pad shows no indication of any image at all.

Copying it from Outlook into Paint shows it to be a 32 x 32 pixel image:
![image](https://user-images.githubusercontent.com/60317513/85286200-1809bf80-b48a-11ea-8be6-90f232070b21.png)
## Environment

Joplin version: 1.0.221
Platform: Desktop
OS specifics: Windows 10 x64

## Steps to reproduce

1. In Joplin Welcome! notebook, select text and image 
2. Use keyboard shortcut Ctrl + C to copy (copy from right click context menu loses even more formatting)
3. Paste into Word or Outlook. Text is copied, but images are replaced with white 32 x 32 pixel images.

## Describe what you expected to happen
Expected image data to be copied. Opening the image in Paint, copying and pasting into Outlook or Word works as expected, with the image appearing inline with the text.

## Logfile
With debugging enabled, nothing appears in the console upon copying with keyboard shortcut Ctrl + C.

**Comment by vectisere** [comment]
Hi @laurent22 
May I ask why the bug label doesn't apply to this?
Is this out of scope for Joplin or has this never worked, making this a feature request?
Thanks

**Comment by laurent22** [comment]
Yes I wouldn't expect this to work out of the box, so that would be more like a feature request.

Office can be special in many ways and there are efforts to make certain things work (like editing an attachment in Excel), so maybe this feature will be implemented some day but unfortunately it's relatively low priority for now.
