### ISSUE TITLE
links can't be copied anymore

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#3404]
## Environment

Joplin 1.0.224 (dev, darwin)

Client ID: e354a932e6e143c782264aad4112b674
Sync Version: 1
Profile Version: 30
Keychain Supported: Yes

Revision: f61c4c13 (master)

## Steps to reproduce

1. Create link in note: `[Joplin Forum](https://discourse.joplinapp.org/)`
2. Goto to Preview
3. Right-click on `Joplin Forum` and click `Copy`
4. The text `Joplin Forum` is copied instead of the link

## Describe what you expected to happen

The link `https://discourse.joplinapp.org/` should have been copied to the clipboard.

## Logfile

No errors in log or console.

Update: I can't recall when this stopped working, but I remember it did work before. But I don't know, whether there was a separate menu item `Copy link` or not.

**Comment by laurent22** [comment]
There should indeed be a "Copy link" option. On v224 on Windows, if I right-click on a link I have the option "Copy link", which works as expected. If I select the text first, there will only be the "Copy" option which copies the text.

**Comment by tessus** [comment]
Not on macOS. The text is automatically selected when doing a right-click. Very strange.

![rc-link](https://user-images.githubusercontent.com/223439/85325668-ff090a80-b499-11ea-8764-9cff05e42074.gif)

**Comment by tessus** [comment]
Problem still exists with:

Joplin 1.0.229 (dev, darwin)

Client ID: e354a932e6e143c782264aad4112b674
Sync Version: 1
Profile Version: 31
Keychain Supported: Yes

Revision: 7f1f5a8c (master)

**Comment by tessus** [comment]
Unfortunately the problem still exists in:

Joplin 1.0.233 (dev, darwin)

Client ID: e354a932e6e143c782264aad4112b674
Sync Version: 1
Profile Version: 32
Keychain Supported: Yes

Revision: d13f54c2 (master)

**Comment by tessus** [comment]
No fix yet.

**Comment by laurent22** [comment]
Fix in this pull request, but waiting for UI update: https://github.com/laurent22/joplin/pull/3474
