### ISSUE TITLE
Import-Export folders appends extra line in the begining = note's title

### ISSUE THREAD

**Issue by safronov-nikolai** [laurent22/joplin#3406]
## Environment

Joplin version: Joplin 1.0.220 (prod, win32), Joplin 1.0.220 (prod, linux)
Platform: Windows, Linux
OS specifics: Windows 7, Ubuntu 18.04

## Steps to reproduce

1. File -> Export -> MD (Markdown) in the Windows Desktop version. Now I got a folder with sub-folders with all of the notes on that machine (one level of recursion only = I did not use sub-notebooks). I pick one of the sub-folders (with notes inside) and copy it on to a USB, as I need only this one notebook.
2.  Transfer it to my Linux machine.
3. On the Linux machine I use: Import -> MD - Markdown (Directory) on the sub-folder I transferred. 
4. All of the imported notes have a new extra line on top that equals a copy of the note's title.

I tested it a number of times with the same effect.
This export-import bug happens on win32 to win32, too. Probably not system dependent.

## Describe what you expected to happen

I do not expect to append extra lines in the beginning of the note's body after importing.

**Comment by laurent22** [comment]
If you want to export, then import, you should use the JEX or RAW. Export to Markdown doesn't preserve metadata, such as whether the first line of the file is the title or not.
