### ISSUE TITLE
Editing attachments/resources (xlsx / Excel 2010 specifically) is unreliable?

### ISSUE THREAD

**Issue by zakeryooo** [laurent22/joplin#3407]
After seeing editable resources in 1.0.217 I was really excited to try it out but unfortunately while trying to work with attached spreadsheets (xlsx, with Excel 2010 being my editor) it hasn't been reliable enough to use. 

I can follow the _exact_ same steps (as listed below) multiple times (10+) in a row, sometimes it'll sync, sometimes it won't, probably about 50/50 whether it syncs an edit to the attachment or not. 

When it's not working clicking sync just shows "Completed: {Date} {Time}" whereas the times it works, it shows: "Updated remote items: 1, Fetched items: 1/1, Completed: {Date} {Time}"

It seems to be more reliable if I'm working with basic attachments (I tested with a txt file), but not so much with spreadsheets.

## Environment

Joplin version: 1.0.220
Platform: Windows
OS specifics: Window 10 May 2020 Update

## Steps to reproduce

1. Attach a spreadsheet (xlsx) to a Joplin note
2. Click the attachment in the markdown preview to open it (I'm editing it in Excel 2010)
3. Make a change (small or big) to the file
4. Save the file
5. Close Excel
6. Click Sync in Joplin
7. Open Joplin on another device and sync
8. Hope the edit you made to the resource is there

## Describe what you expected to happen

Sync the edits every time.

**Comment by zakeryooo** [comment]
One thing I forgot to mention with this; it seems to happen in waves, i.e. it'll work a few times in a row, then not work a few times in a row, then start working again a few times, etc. Not sure if that information is helpful

**Comment by laurent22** [comment]
Do you sometimes change notes while you have the Excel file open?

**Comment by zakeryooo** [comment]
Nope, I saw a previous post about the watcher stopping if you change note so I've always made sure I keep the same note (the one containing the attachment) open while editing the attachment
