### ISSUE TITLE
Syncing with Dropbox - user limit reached

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#341]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [x] Desktop
- [x] Mobile
- [ ] Terminal

> This app has reached its user limit. Contact the app developer and ask them to use the Dropbox API App Console to increase their app's user limit.

_version : v1.0.79_

**Comment by laurent22** [comment]
That should work now, could you try again?

**Comment by foxmask** [comment]
it's ok now.
thanks.
