### ISSUE TITLE
Joplin suddenly unusable on Windows (window never drawn)

### ISSUE THREAD

**Issue by slalaurette** [laurent22/joplin#3413]
## Environment

Joplin version: 1.0.223
Platform: Windows 8.1 64bit
OS specifics: Kaspersky recently installed

## Steps to reproduce

1. Start your computer.

## Describe what you expected to happen

Usually Joplin starts minimized and I can invoke it from its icon in the tray. But the icon never appears. Bringing up the Task Manager reveals four instances of the Joplin process, two of which can be killed, the other two seemingly immortal. 

One thing to note is that I recently switched my antivirus from Avast to Kaspersky. This was pretty much simultaneous with updating Joplin to the latest version, but I **think** Joplin was working fine with Kaspersky installed before the update.

Joplin Portable brings up an empty window with a basic menu. The only option in "File" is "Exit". This window can't be closed.

## Logfile

The procedure for generating a debug file doesn't seem to work in these circumstances.

**Comment by laurent22** [comment]
If you have the empty window with basic menu, please open the development tools (maybe under View or Tools) and please post the warnings or errors in the console here.

**Comment by laurent22** [comment]
Also to be sure please use v224 as 223 had an issue.

**Comment by slalaurette** [comment]
Aha! This is the error stream: 

Uncaught Error: Cannot find module 'lib/services/rest/ActionApi.desktop'
Require stack:
- C:\bin\ed\Joplin\resources\app.asar\lib\ClipperServer.js
- C:\bin\ed\Joplin\resources\app.asar\app.js
- C:\bin\ed\Joplin\resources\app.asar\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:798)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (reset-search-paths.ts:40)
    at Module._load (internal/modules/cjs/loader.js:691)
    at Module._load (electron/js2c/asar.js:717)
    at Function.Module._load (electron/js2c/asar.js:717)
    at Module.require (internal/modules/cjs/loader.js:853)
    at require (internal/modules/cjs/helpers.js:74)
    at Object.<anonymous> (C:\bin\ed\Joplin\resources\app.asar\lib\ClipperServer.js:7)
    at Object.<anonymous> (C:\bin\ed\Joplin\resources\app.asar\lib\ClipperServer.js:232)
    at Module._compile (internal/modules/cjs/loader.js:968)
DevTools failed to parse SourceMap: file:///C:/bin/ed/Joplin/resources/app.asar/fence.js.map
DevTools failed to parse SourceMap: file:///C:/bin/ed/Joplin/resources/app.asar/sanitize_html.js.map
DevTools failed to parse SourceMap: file:///C:/bin/ed/Joplin/resources/app.asar/checkbox.js.map
DevTools failed to parse SourceMap: file:///C:/bin/ed/Joplin/resources/app.asar/mermaid.js.map
DevTools failed to parse SourceMap: file:///C:/bin/ed/Joplin/resources/app.asar/markdownItAnchor.js.map
DevTools failed to parse SourceMap: file:///C:/bin/ed/Joplin/resources/app.asar/markdownItTocDoneRight.js.map
DevTools failed to parse SourceMap: file:///C:/bin/ed/Joplin/resources/app.asar/JoplinServerApi.js.map
DevTools failed to parse SourceMap: file:///C:/bin/ed/Joplin/resources/app.asar/SettingUtils.js.map
DevTools failed to parse SourceMap: file:///C:/bin/ed/Joplin/resources/app.asar/KeychainService.js.map
DevTools failed to parse SourceMap: file:///C:/bin/ed/Joplin/resources/app.asar/KeychainServiceDriver.node.js.map
DevTools failed to parse SourceMap: file:///C:/bin/ed/Joplin/resources/app.asar/KeychainServiceDriverBase.js.map
DevTools failed to parse SourceMap: file:///C:/bin/ed/Joplin/resources/app.asar/errors.js.map

**Comment by slalaurette** [comment]
For the record, installing the 1.0.224 version seems to have solved the issue. I'll report any further developments.
