### ISSUE TITLE
Error: GET .sync/version.txt: Unknown error 2 (500) 

### ISSUE THREAD

**Issue by Kemwer** [laurent22/joplin#3416]
Please I am not too tech-savy but I have had no problems with Joplin until now. I saw someone asking about the same problem but the solution was to backup and reinstall everything. Is there another way of fixing this? if not can someone guide me through the process of backing up encrypted files? what should I delete and what to keep?

## Environment

Joplin version: 1.0.224
Platform: Linux, iOS
OS specifics: Manjaro Linux, iPhone 11 Pro latest update

## Steps to reproduce

1. Open Joplin
2. Try to syncronize
3. Error : Error GET .sync/version.txt Unknown error 2 (500)

The error started after I updated versions from 1.0.218 to 1.0.224 but if I go back to version 218 it shows the same error now 

## Logfile

2020-06-24 13:43:14: "Error: GET .sync/version.txt: Unknown error 2 (500): <
Code: 500
Error: GET .sync/version.txt: Unknown error 2 (500): <
    at newError (/tmp/.mount_JopliniEAhyH/resources/app.asar/lib/WebDavApi.js:399:11)
    at WebDavApi.exec (/tmp/.mount_JopliniEAhyH/resources/app.asar/lib/WebDavApi.js:429:10)"

**Comment by laurent22** [comment]
Error 500 is a server error so you need to check your server logs
