### ISSUE TITLE
Syncing with Dropbox - how to reset auhorization

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#342]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

_version : v1.0.81_

I made a mistake and allowed joplin on the wrong dropbox account

So:
* I dropped the authorization from dropbox 
* on the mobile I switched from dropbox to onedrive and saved then switched back from onedrive to dropbox and saved
* launched the sync 

Then instead of having the screen to ask me to provide the token I got an error:

```
Error: POST file/create_folder_v2: Error (400) Error in call to API function "files/create_folder_v2": Must provide HTTP header "Authorization" or "URL parameter "authorization"

```

**Comment by laurent22** [comment]
There's nothing at this point to allow switching accounts, so your best option would be to uninstall and reinstall the app.

On desktop, sync the notes to Dropbox, then sync then back to Android to restore them.

**Comment by foxmask** [comment]
I understand, but it is confusing. I spent 4days to sync all my evernote notes on each device. I know, It's my fault and the project is young so I'll figure it out.:)
