### ISSUE TITLE
Alt keyboard shortcut is inconsistent with Windows' Shift + Alt

### ISSUE THREAD

**Issue by trespda** [laurent22/joplin#3423]
## Environment
Joplin version: 
Joplin 1.0.224 (prod, win32)

Revision: 1899d866 (master)
Platform: 
OS specifics: 
USB portable installation
Win 10, 1909
OS build: 18363.900

## Steps to reproduce

1. Write in the editor in one of the languages installed on Windows, e.g English
![1 eng Annotation 2020-06-26 205221](https://user-images.githubusercontent.com/34583545/85888696-c4cd9f00-b7f2-11ea-8865-61de5a88e24a.png)

2. Type Shift + Alt. This replaces the language to the next one you have installed on Windows. But it also changes the focus in Joplin, to the menu.
![2 defocus Annotation 2020-06-26 205329](https://user-images.githubusercontent.com/34583545/85888716-d151f780-b7f2-11ea-8140-2128c06d7b44.png)
![3 heb Annotation 2020-06-26 210035](https://user-images.githubusercontent.com/34583545/85888776-e890e500-b7f2-11ea-8721-3163eac50b2f.png)

3. Type Alt , or Esc, or click the editor to regain focus.

## Describe what you expected to happen

The usual behaviour in Windoes language selection is that the Shift key overrules the original function of the Alt key, so that the language is switched and the focus stays in the text area. E.g. in the github text box I now write in. This is the first time I encounter something else.

To be fair, it looks like a small bug. But untill I tested today, I didn't notice that the focus stays within Joplin, in the menubar, so I thought the program loses it completely.  And so I thought the only option to retrieve focus to the editor is by mouse, which I wasn't happy about. Now I noticed both Alt and Esc will do.

## Logfile
I couldn't find ".config" folder.

**Comment by roman-r-m** [comment]
Seems like a duplicate of https://github.com/laurent22/joplin/issues/3345

**Comment by trespda** [comment]
Just checked this.

Shift + alt works in both directions, with the caret staying active in the editor. :)

It turns out that, a single tap on Alt, with the purpose of changing focus to the menus, doesn't always work:
When in English mode, both Alt keys will work.
When in Hebrew, only the left one will work, the right Alt (Alt Gr) will not.
**This is the case in all apps I checked, so it's not a bug.**
Go figure.

Thanks
