### ISSUE TITLE
Dragging and dropping a file inserts file link at very top of note

### ISSUE THREAD

**Issue by mgrandi** [laurent22/joplin#3425]
## Environment

Joplin 1.0.224 (prod, win32)
Client ID: 72f5283434534b0ab880e4f2ce4c565d
Sync Version: 1
Profile Version: 30
Keychain Supported: Yes
Revision: 1899d866 (master)

OS specifics: windows 10 build 2004

## Steps to reproduce

1.  open note
2. position cursor anywhere in the note
3. drag file from desktop / explorer onto joplin
4. file link appears at the very top of the note

## Describe what you expected to happen

the file link should not be inserted at the top of the note, it should be where the cursor is, or somewhere calculated from where the mouse is when the dropping finishes (released mouse button)

Also to note , I think this is a regression, I believe this worked before (might have been inconsistent with with where it placed the note vs where i actually wanted it to go) but now it seems to 100% put it at the start/top of the note no matter where the cursor is or where I drag the file to 

## Logfile

[2020-06-26 - joplin drag drop insert at top - bug report log.txt](https://github.com/laurent22/joplin/files/4839778/2020-06-26.-.joplin.drag.drop.insert.at.top.-.bug.report.log.txt)

**Comment by rsrahul1000** [comment]
Hi @mgrandi , I am new to open source contribution and I would like to work on this issue.
Can you please assign it to me?

**Comment by dpoulton-github** [comment]
Added for info only: Other references to this issue on the forum / GitHub

https://discourse.joplinapp.org/t/attachments-behavior-change-in-win32-1-0-216/9223
https://discourse.joplinapp.org/t/testing-1-0-209-drag-and-drop/8779
https://github.com/laurent22/joplin/issues/3200#issuecomment-633241193

**Comment by mgrandi** [comment]
@rsrahul1000 sorry, i don't think i can assign it to you as i'm not a contributor on the project

**Comment by mgrandi** [comment]
this still happens

**Comment by mgrandi** [comment]
@laurent22 sorry to bother you but the stale bot closed this cause i missed the email, can this be reopened? this bug still happens with the latest version:

```plaintext
Joplin 1.0.233 (prod, win32)

Client ID: bc6ab7b0d1f44b97865d5f83cb8a5dc8
Sync Version: 1
Profile Version: 32
Keychain Supported: Yes

Revision: e63eee89 (master)
```

**Comment by mgrandi** [comment]
this seems to be fixed as of 

```
Joplin for Desktop

Copyright © 2016-2020 Laurent Cozic
Joplin 1.1.4 (prod, win32)

Client ID: 72f5283434534b0ab880e4f2ce4c565d
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: 9610b7e6 (master)
```
