### ISSUE TITLE
Printing garbled with _italics_

### ISSUE THREAD

**Issue by yadayadaydadaa** [laurent22/joplin#3426]
Printing or exporting PDF of a document with `_italics_` has the text completely garbled: e.g. the document consiting of just
```
_testing this thing_
```
gets rendered as:
<img width="508" alt="image" src="https://user-images.githubusercontent.com/9931928/85939012-aee5da00-b8d7-11ea-9ee1-df568a681aec.png">

Joplin 1.0.224 on latest MacOS.

**Comment by laurent22** [comment]
I can't replicate this. Could you send note as a JEX file? What language do you use for the application? Do you use custom CSS?

**Comment by yadayadaydadaa** [comment]
It's the same with out without custom CSS (where I only reduce the font size). I tried to export a JEX, but it's 10MB?!?!? Contains all my notes?

**Comment by yadayadaydadaa** [comment]
Oh, wait, if I restart after removing the custom css, then the print works. (Always gets me, having to restart after modifying the css.)

**Comment by laurent22** [comment]
Could you share your CSS to see what could be causing this?

**Comment by yadayadaydadaa** [comment]
Actually, the font-size sitting alone does not cause problems. The font settings I found from some from do.

```
/* For styling the rendered Markdown */
body{
     /*font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI
     /Emoji";*/
     font-size: smaller;
}
```

**Comment by laurent22** [comment]
I can't replicate this, even with the provided CSS, so will need complete info to be able to fix this.
