### ISSUE TITLE
Windows: minimize Joplin-Window with activ Pen: no reaction

### ISSUE THREAD

**Issue by lighthousebulb** [laurent22/joplin#3427]
I'm on Windows 10 with my MS Surface device. When I try to minimize, maximize or closing the window with my activ Pen with the Window-Title-Bar, nothing happens.  
The Window accepts touch-events (without the Pen) just fine. Mouse-Events are just fine two, as well as Keyboard-Actions.
If I open the Window-Menu (Alt+Space) I can use the Pen just fine, to "click" on the menu-entries.

## Environment

Joplin version: 1.0.224
Platform: Windows
OS specifics: Microsoft Windows 10 Home (Build 18363) (MS Surface Go 2 with active Pen)

## Steps to reproduce

1. open Joplin
2. try to use the Window-Toolbar-Buttons (minimize, maximize, close) with a activ Pen

## Describe what you expected to happen
I expect the Joplin-Window to act on a "click" with a activ Pen on the minimize, maximize or close Buttons of the Window

**Comment by laurent22** [comment]
We don't explicitly support pens, so it could be some upstream issue.
