### ISSUE TITLE
The Joplin application icon isn't showing after installing appimage

### ISSUE THREAD

**Issue by armaccloud** [laurent22/joplin#3428]
Since the latest Joplin version, the application icon isn't showing anymore after installing it with the appimagelauncher. This had worked well before. Has anything changed that is preventing the icon to be shown?

## Environment

Joplin version: 1.0.224
Platform: Pop!_OS
OS specifics: 20.04 LTS

## Steps to reproduce

1. Download Joplin 1.0.224 appimage
2. Open the downloaded appimage by opening it, appimagelauncher 
3. Verify the application icon isn't shown

![image](https://user-images.githubusercontent.com/9272078/85958048-fb422000-b992-11ea-9153-22fa13824cfe.png)

## Describe what you expected to happen
When searching for Joplin, the blue application icon is shown as normal.

**Comment by laurent22** [comment]
How did you install the app?

**Comment by armaccloud** [comment]
By using the application appimagelauncher. Normally it's a matter of clicking the file, clicking OK on appimagelauncher and it is installed.

![image](https://user-images.githubusercontent.com/9272078/85958863-29c2f980-b999-11ea-85f6-f0374bc64ade.png)

**Comment by laurent22** [comment]
I think on Linux you have to run the install script to get the icon, but I'm not sure as I don't use this version.

**Comment by chrisbeardy** [comment]
You can also create.edit the desktop file in /usr/share/applications/joplin.desktop to point to the correct image:

This is the contents of desktop file my file:
```
[Desktop Entry]
Name=Joplin
Comment=An open source note taking and to-do application with synchronisation capabilities
Type=Application
Exec=/home/chris/AppImages/Joplin-1.0.224.AppImage %U
Icon=/home/chris/AppImages/joplin.png
Terminal=false
Categories=Utilty;TextEditor;
```

**Comment by armaccloud** [comment]
Thank you @chrisb86 for this option. I have applied this and it works fine.

**Comment by dbogdanov** [comment]
Still, this is a workaround. Other apps install with AppImageLauncher just fine without any missing application icon.

**Comment by Dotrar** [comment]
I'd argue for this :point_up_2: 

it is a workaround and I haven't experienced it from any other appimage.

for what it's worth, `appimagelauncher` gave me the following Joplin desktop file, 
we can see that it sets an Icon value, but I don't know where it filled it out from, perhaps you guys will know better? 

```conf
[Desktop Entry]
Name=Joplin (2.8.8)
Exec=/home/dre/.bin/Applications/Joplin-2.8.8_4030a351986a6eaff99fecbe383e65aa.AppImage --no-sandbox %U
Terminal=false
Type=Application
Icon=appimagekit_8decaa98bb1309f43a27dd0764aefc23_joplin
StartupWMClass=Joplin
X-AppImage-Version=2.8.8
MimeType=x-scheme-handler/joplin;
Comment=Joplin for Desktop
Categories=Office;

TryExec=/home/dre/.bin/Applications/Joplin-2.8.8_4030a351986a6eaff99fecbe383e65aa.AppImage
X-AppImage-Old-Icon=joplin
X-AppImage-Old-Name=Joplin
X-AppImage-Identifier=8decaa98bb1309f43a27dd0764aefc23
Actions=Remove;
X-AppImageLauncher-Version=2.2.0 (git commit 0f91801), built on 2020-09-29 21:36:15 UTC
```

**Comment by Daeraxa** [comment]
So it seems different distros have issues with this. I use appimage launcher using the Cinnamon DE on Linux Mint and everything seems to be fine.
I did however have this issue on Fedora with GNOME 42 where the appimage .desktop was fine until AppimageLauncher integrated it. I found if I just changed the `Icon` value to `joplin` then it worked.

**Comment by evakdev** [comment]
Spent a lot of time trying to make the icon appear on Linux Mint, @Daeraxa's solution worked perfectly.
