### ISSUE TITLE
The encrypted content cannot be decrypted, what should I do?

### ISSUE THREAD

**Issue by ourfor-pp** [laurent22/joplin#3429]
I know the password, but there is no way to decrypt

![image](https://user-images.githubusercontent.com/45449335/85992127-08a8ea00-ba27-11ea-88df-6cf25c84f065.png)
![image](https://user-images.githubusercontent.com/45449335/85992199-1b232380-ba27-11ea-9ea7-47b69e238836.png)

**Comment by dalwk** [comment]
I have the same issue on iPhone, it can't seem to save the decryption password it still prompts me to set the password after I've done it. 

e2ee works fine on Android on the other hand.

**Comment by FatmanUK** [comment]
Same issue with Linux desktop version 1.0.169 revision 0c552fe. Multiple "items that cannot be decrypted" in the sync log including notes, resources, revisions and folders.

[syncReport-1594459856890.csv.gz](https://github.com/laurent22/joplin/files/4906557/syncReport-1594459856890.csv.gz)

**Comment by laurent22** [comment]
Please head to the forum for support
