### ISSUE TITLE
The editor cannot handle combining (and some other) unicode characters 

### ISSUE THREAD

**Issue by yadayadaydadaa** [laurent22/joplin#3435]
The editor seems to loose track of the column when combining Unicode characters (e.g. `x` followed by U+0303: “x̃”) are used. It counts the combining character as its own. Editing a line with a combining character then becomes a challenge, as the cursor does not point to the editing position. The same with double-width characters, such as many mathematical symbols (e.g. “⟹”).

**Comment by laurent22** [comment]
Did you try with Code Mirror? (in Setting => Note)

**Comment by yadayadaydadaa** [comment]
> Did you try with Code Mirror? (in Setting => Note)

It does not seem to have this problem, but the syntax highlighting (with latex-math, https://github.com/laurent22/joplin/issues/3054) is broken even more so than with the basic editor. Basically the whole document is set in italics! Also it highlights [Reference to an article] as if it were a markdown link—although the citation doesn't have the following link component. (It's actually quite nice effect, but I think should be considered a bug.)

**Comment by laurent22** [comment]
Could you post an example of Markdown note that looks broken in Code Mirror? Eventually we'll want to switch to that one permanently so it would be good to know about these issues.

**Comment by yadayadaydadaa** [comment]
> Could you post an example of Markdown note that looks broken in Code Mirror? Eventually we'll want to switch to that one permanently so it would be good to know about these issues.

Done in https://github.com/laurent22/joplin/issues/3440

**Comment by mitrakov** [comment]
Dear @laurent22, I've downloaded 1.0.233, and found out the issue is NOT resolved.
I applied a workaround with "PT Mono" as a non-default font (suggested by @seslav in [this thread](https://github.com/laurent22/joplin/issues/3487)) but for new users it would seem as a bug.

I am very appreciate your help to fix it in future releases. Thanks!
