### ISSUE TITLE
Fatal Error : Unknow profile version

### ISSUE THREAD

**Issue by japafrite** [laurent22/joplin#3437]
Hello,
At launching I got this message :

![image](https://user-images.githubusercontent.com/49430437/86175779-345dca00-bb24-11ea-8174-87f117612e50.png)

## Environment

Joplin version: 1.0.224 (all computers)
Platform: Windows 10
OS specifics: 19041.329

## Steps to reproduce

1. Use synchronisation by WebDav on a NAS
2. Launch Joplin on one computer and synchonize
3. Launch on second computer : fatal error
4. Resinstall version 1.0.224 on second computer : launching ok
5. Launch on 1rst computer : fatal error, then your can reinstall, it is ok, but not on 2nd computer, etc...

## Describe what you expected to happen

Synchronization and launch at several computers with webdav sync

## Logfile

[log-autoupdater.txt](https://github.com/laurent22/joplin/files/4854413/log-autoupdater.txt)
[log-database.txt](https://github.com/laurent22/joplin/files/4854414/log-database.txt)
[log.txt](https://github.com/laurent22/joplin/files/4854415/log.txt)

**Comment by vascowhite** [comment]
Sorry for digging up an old issue, but I have just upgraded to 2.5.12 and have experienced this error.

![joplinerror_000](https://user-images.githubusercontent.com/874109/146244854-900ea178-17d5-42ea-b91c-1d6f77855a06.png)

Any suggestions on how I can resolve it?

I am running Debian Testing with I3wm and installed Joplin using the appimage.
