### ISSUE TITLE
Cursor Misaligned with Text (English UK and US)

### ISSUE THREAD

**Issue by Logos-Coder** [laurent22/joplin#3439]
When writing a note, the cursor slowly becomes misaligned. It may be related to #2991. the cursor can traverse the whole line, but can go out of the bounds of the text, which is where it will actually modify the text.

![Joplin-mis-cursor](https://user-images.githubusercontent.com/47828239/86256940-6dd81900-bba8-11ea-8ce3-beca66b3b34a.png)

## Environment

Joplin version: 1.0.224
Platform:  Linux
OS specifics:  Endevour OS (Basically arch)
Install Method: AUR: [joplin](https://aur.archlinux.org/packages/joplin/)

## Steps to reproduce

1. start a new note
2. Happy writing out of line!

I Hope this isn't an intended feature.

## Logfile
Not Applicable.

**Comment by CalebJohn** [comment]
It looks like you've set a custom editor font. The default joplin editor doesn't support non-monospace font, we're migrating to a new editor so if you need this font please toggle the CodeMirror beta under Tools -> Options -> Note. Otherwise you'll need to change your custom font to a monospace variant.

**Comment by Logos-Coder** [comment]
Ah ok, It just started using the default general font on my system. It didn't use my monospace font I had set on my system.

**Comment by CalebJohn** [comment]
Thats odd, the joplin default is to use monospace not the system default. This should only happen if you changed the editor font setting. The AUR is provided by a third party, so maybe something has failed there?
Either way the beta editor will soon become the default and this issue won't exist anymore.
