### ISSUE TITLE
[request] Search by title field

### ISSUE THREAD

**Issue by dsummersl** [laurent22/joplin#344]
I frequently like to search by the title of the note; it would be grand if that were possible! I suppose people might want to search by different metadata fields in notes, and that this might fall into that category of things to search by (but I'd be perfectly happy with just title). Evernote has the idea of using a colon to specify where to search like `"field:searchvalue"` (I only offer that as a possible syntax, as it is one I'm familiar with. I'm sure others could be dreamed up!).

**Comment by foxmask** [comment]
May be duplicate with #293
