### ISSUE TITLE
Code Mirror syntax highlighting bugs

### ISSUE THREAD

**Issue by yadayadaydadaa** [laurent22/joplin#3440]
As discussed in https://github.com/laurent22/joplin/issues/3435#issuecomment-652420777, also relevant https://github.com/laurent22/joplin/issues/3054, the syntax highlighter in Code Mirror has even more severe issues with latex-math and even other things than the basic editor.  Here's an example
```markdown
# Example note

## braces

I don't think this citation to [Some Book, p. 12] should be highlighted, although I also don't really mind it. It shouldn't however happen within latex-math, as it right now does:
$$
	[x].
$$
It even detects within math stuff that is not a link:
$$
	[f+g](x).
$$

## Italics

This works
$$
	x_k = a
$$
so does (with respect to syntax highlighting) this
$$
	x_k_y = incorrect LaTeX code,
$$
(not even rendere by KaTeX), but this correct latex code
$$
	{x_k}_y = THIS  NOT BE HIGHLIGHTED IN ITALICS.
$$
fails the highlighter. It italics even flows out of the math environment.

Can you just please add a detector (and a specific highlighting colour) for math blocks?
```

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/9931928/86271125-fb5c3e80-bb91-11ea-92c4-f55bb72cee5b.png">

**Comment by laurent22** [comment]
@CalebJohn, do you think it's possible to add a special rule for Katex blocks, so that they are either highlighted as Katex, or highlighting is disabled within the block?

Ace Editor handles this as expected:

![image](https://user-images.githubusercontent.com/1285584/86347001-9bc76700-bc55-11ea-8dfb-26e90758833b.png)

Also `[Some Book, p. 12]` indeed shouldn't be highlighted because it's not a complete Markdown link.

**Comment by yadayadaydadaa** [comment]
I just noticed that also `TV:three_letters_or_more` is underlined. Why? the `TV:` bit is critical, other combinations like `AB:` don't trigger the underlining.

**Comment by CalebJohn** [comment]
@yadayadaydadaa Thanks for reporting these issues. Personally I disagree that katex is more broken than in the old editor (although your note does seem to be more broken!) I would say that it is **just as** broken :).  Looking at @laurent22 's screenshot the old editor seems to fail in all the same locations (except the last one where it still fails but differently), but the highlighting is more subtle. I digress. This [can be fixed](https://github.com/codemirror/CodeMirror/issues/2942) as suggested by @laurent22 . I'll start looking into it right away.

In regards to the `TV:three_letters_or_more` this was an un-needed highlighting feature, which I'm not sure the purpose of. I disabled it in #3448.

And for `[Some Book, p. 12]` according to the [commonmark spec](https://spec.commonmark.org/0.29/#link-reference-definitions) this is a valid markdown link (which is supported by the Joplin renderer). I suspect this isn't a commonly used feature, so I added a commit to #3448 that disables highlighting for link text. There is still a css class associated with text in a square bracket, so users can turn highlighting back on by adding the `.cm-link-text` class to userchrome.css.

Source View
![image](https://user-images.githubusercontent.com/2179547/86402512-2bc2dc00-bc69-11ea-85a2-754f855c5166.png)
Rendered
![image](https://user-images.githubusercontent.com/2179547/86402521-31202680-bc69-11ea-8829-03bc06c9db1e.png)

Updated
![image](https://user-images.githubusercontent.com/2179547/86402568-4a28d780-bc69-11ea-980c-eb318dd4c718.png)
(rendered doesn't change)
