### ISSUE TITLE
Code Mirror jumps back-and-forth

### ISSUE THREAD

**Issue by yadayadaydadaa** [laurent22/joplin#3443]
Sometimes when editing a somewhat long note, the Code Mirror editor view just suddenly jumps to a completely different location within the document. The cursor stays where it was (outside view), so editing can be continued. So far I've only paid attention to this problem within latex equations, in particular when the equation becomes unrenderable by KaTeX. This can happen in  particular when you enter an opening brace `{` but the closing brace is still missing, or if you type the name of a non-existent command.

This bug could possibly related to #3341 (out of sync panes), as the rendered view can completely change when KaTeX decides it can no longer render the equation. The rendered view can suddenly become *significantly* shorter when editing a multi-line `$$\begin{align} …  & \\ … & \\ … \end{align}$$` equation environment.

**Comment by CalebJohn** [comment]
Thanks for this detailed report, I believe that your correct to say that it's related to #3341 . Do you mind testing this bug with the ace editor enabled as well? I suspect it will have the same problem but I can't test myself now (don't have a computer at the moment).

**Comment by yadayadaydadaa** [comment]
I did not notice the bug in the old ace editor in the days before, editing the same note, so I suspect it is not affected. When I run to the problem again, I'll try to check exactly the same actions in ace as well.
