### ISSUE TITLE
Slow rendering and rendering interval

### ISSUE THREAD

**Issue by yadayadaydadaa** [laurent22/joplin#3444]
When editing long notes full of latex equations, the rendering by KaTeX can take a noticeable amount of time, and result in significant flashing of the viewing pane. Ideally the rendering could be optimised (only rendering changed parts, storing previous KaTeX state such as global `\gdef` macros), but in the meanwhile, and even despite of that, I propose that
1. the rendering trigger should be smarter / slower / adjustable,
2. to reduce the flashing that would be present even at the longer rendering intervals, there should be some kind of buffering of the rendered output.

To make the rendering trigger smarter, Joplin could, for example,

1. monitor the time it took to render the note, and
2. what kind of pauses the user makes in typing,

and adapt the rendering to that, only rendering when it is highly likely that the rendering will be finished before the user will start typing again.

**Comment by IvanaGyro** [comment]
I face the same problem. Rendering is slow for the notes with a lot of equations.
