### ISSUE TITLE
Synchronisation error banner doesn't go away without restart

### ISSUE THREAD

**Issue by yadayadaydadaa** [laurent22/joplin#3447]
(On iOS) the orange banner saying “Some items cannot be synchronised. Press for more info.” does not go away even after the error has been resolved (the sync status page indicates no errors). Pressing “Refresh“ on that page also does nothing, or the entire sync having been completed successfully. Only forcibly shutting down (swiping up in the iOS app switcher) and restarting the app made it go away.

**Comment by matcharles** [comment]
Mine doesn't even go away after force shutdown. Would like to have a dismiss option maybe?
![Screenshot 2020-07-12 at 20 52 59](https://user-images.githubusercontent.com/16296847/87419049-cba13380-c5a0-11ea-9c0a-41ed97aa1765.png)

**Comment by weiss-d** [comment]
I have similar problem in desktop version in Linux (Pop!_OS 20.04).
After a fresh install of an app I pulled all the notes from Dropbox, and at first there were some errors, but after restart second attempt of synchronization was successful except one item, a resource.
This banner keeps appearing every time the program starts.

![image](https://user-images.githubusercontent.com/62437174/92503003-4d13eb80-f209-11ea-932a-404b1b2b282d.png)

When I click the link it shows me the report where this one item ID is provided, but I have no idea how to find it in all of my 300+ notes (search doesn't work if I enter this ID).
![image](https://user-images.githubusercontent.com/62437174/92503554-15597380-f20a-11ea-997c-9ad7ac91e9fb.png)
When I hit `Retry` the banner disappears,  but it pops up again after restart, it's very irritative.
Could someone help me at least to delete this undecrypted resource or whatever it is?

**Comment by weiss-d** [comment]
Finally, I managed to remove this banner.
In the latest version of the app I went to `Tools > Note attachments...` (don't remember if this option was there before the update), here I've found a list of all the attachments and I had to search the guilty item by the hash copied from report message, manually, because there is no search option. Among several hundred items. It was 😢
