### ISSUE TITLE
Mac OS opening issues

### ISSUE THREAD

**Issue by Infinitive-team** [laurent22/joplin#3453]
👉 Please follow one of these issue templates:
- https://github.com/laurent22/joplin/issues/new/choose

⚠️
The GitHub issue tracker is for **bugs** and **security issues** ONLY. For feature requests and support, please use the forum:
https://discourse.joplinapp.org/
[⚠️M](url)

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.
<img width="1440" alt="Screenshot 2020-07-03 at 23 00 08" src="https://user-images.githubusercontent.com/67503004/86497217-0e813100-bd81-11ea-8132-17c328239799.png">

**Comment by laurent22** [comment]
Please search related issues on forum and GitHub.
