### ISSUE TITLE
Sync with lighttpd webdav  PUT 412

### ISSUE THREAD

**Issue by idreamerhx** [laurent22/joplin#3457]
joblin can not sync to webdav hosted with lighttpd (mod_webdav)

The http PUT operator get 412 response.

## Environment

Joplin version: Joplin 1.0.220 (prod, win32)

Client ID: ef5ccdaee3bd4ff0b4bb4e72631fb6cb
Sync Version: 1
Profile Version: 30
Keychain Supported: Yes

Revision: 83e0bac5 (master)
Platform:  Archlinux arm64
OS specifics: lighttpd/1.4.55 (ssl) , with mod_webdav valid configured

## Steps to reproduce

1. joblin config sync webdav:  http://192.168.1.15:8082/joplin  ...   username .... passwd

## Describe what you expected to happen

I use WinSCP to create and edit a file, and the webdav server works ok.
BUT joplin NOT.

I think this is not a bug to lighttpd.
This seam like [this]( https://github.com/laurent22/joplin/issues?q=webdav+412)

## Logfile

**Wireshark joplin PUT header:**

PUT /joplin/fb7d720f120346ae800fce32733a49a9.md HTTP/1.1
authorization: Basic aHgxOmh4MQ==
if-none-match: JoplinIgnore-74610
user-agent: Joplin/1.0
content-length: 11252
accept-encoding: gzip,deflate
connection: close
accept: */*
Host: 192.168.1.15:8082

**WinSCP PUT header:**

PUT /joplin/ssss.md HTTP/1.1
User-Agent: WinSCP/5.17.6 neon/0.31.1
Connection: TE
TE: trailers
Host: 192.168.1.15:8082
Content-Length: 6
Authorization: Basic aHgxOmh4MQ==

**joplin lighttpd assesslog**

192.168.1.10 192.168.1.15:8082 hx1 [05/Jul/2020:23:35:25 +0800] "MKCOL /joplin/.sync/ HTTP/1.1" 405 359 "-" "Joplin/1.0"
192.168.1.10 192.168.1.15:8082 hx1 [05/Jul/2020:23:35:25 +0800] "MKCOL /joplin/.lock/ HTTP/1.1" 405 359 "-" "Joplin/1.0"
192.168.1.10 192.168.1.15:8082 hx1 [05/Jul/2020:23:35:25 +0800] "MKCOL /joplin/.resource/ HTTP/1.1" 405 359 "-" "Joplin/1.0"
192.168.1.10 192.168.1.15:8082 hx1 [05/Jul/2020:23:35:25 +0800] "PROPFIND /joplin/.lock/ HTTP/1.1" 207 430 "-" "Joplin/1.0"
192.168.1.10 192.168.1.15:8082 hx1 [05/Jul/2020:23:35:25 +0800] "GET /joplin/.sync/version.txt HTTP/1.1" 200 1 "-" "Joplin/1.0"
192.168.1.10 192.168.1.15:8082 hx1 [05/Jul/2020:23:35:25 +0800] "PUT /joplin/.sync/version.txt HTTP/1.1" 204 0 "-" "Joplin/1.0"
192.168.1.10 192.168.1.15:8082 hx1 [05/Jul/2020:23:35:25 +0800] "PROPFIND /joplin/fb7d720f120346ae800fce32733a49a9.md HTTP/1.1" 404 341 "-" "Joplin/1.0"
192.168.1.10 192.168.1.15:8082 hx1 [05/Jul/2020:23:35:25 +0800] "PUT /joplin/fb7d720f120346ae800fce32733a49a9.md HTTP/1.1" 412 361 "-" "Joplin/1.0"
192.168.1.10 192.168.1.15:8082 hx1 [05/Jul/2020:23:35:30 +0800] "PUT /joplin/fb7d720f120346ae800fce32733a49a9.md HTTP/1.1" 412 361 "-" "Joplin/1.0"

**winscp lighttpd assesslog**

192.168.1.10 192.168.1.15:8082 hx1 [05/Jul/2020:23:36:35 +0800] "PROPFIND /joplin/fb7d720f120346ae800fce32733a49a9.md HTTP/1.1" 404 341 "-" "WinSCP/5.17.6 neon/0.31.1"
192.168.1.10 192.168.1.15:8082 hx1 [05/Jul/2020:23:36:37 +0800] "PROPFIND /joplin/fb7d720f120346ae800fce32733a49a9.md HTTP/1.1" 404 341 "-" "WinSCP/5.17.6 neon/0.31.1"
192.168.1.10 192.168.1.15:8082 hx1 [05/Jul/2020:23:36:37 +0800] "PUT /joplin/fb7d720f120346ae800fce32733a49a9.md HTTP/1.1" 201 0 "-" "WinSCP/5.17.6 neon/0.31.1"
192.168.1.10 192.168.1.15:8082 hx1 [05/Jul/2020:23:36:37 +0800] "PROPPATCH /joplin/fb7d720f120346ae800fce32733a49a9.md HTTP/1.1" 207 345 "-" "WinSCP/5.17.6 neon/0.31.1"
192.168.1.10 192.168.1.15:8082 hx1 [05/Jul/2020:23:36:37 +0800] "PROPFIND /joplin/ HTTP/1.1" 207 4308 "-" "WinSCP/5.17.6 neon/0.31.1"

**Comment by idreamerhx** [comment]
BTW,

the joblin/.sync/version.txt I create by hand, and chown chgrp to http. incase joplin can not put the version.txt ...

**Comment by laurent22** [comment]
What's the bug?

**Comment by idreamerhx** [comment]
joblin can not sync to webdav hosted with lighttpd (mod_webdav)

**Comment by idreamerhx** [comment]
> 
> 
> What's the bug?

I update in description.

**Comment by laurent22** [comment]
I see 405 (method not allowed) and 404 (not found) errors in your logs so not something that Joplin can fix. Most likely you need to double-check that the URL is valid or the server config.

**Comment by idreamerhx** [comment]
[root@rk3399 litmus-0.13]# ./litmus  http://192.168.1.15:8082/joplin/ xx1 xx1
-> running `basic':
 0. init.................. pass
 1. begin................. pass
 2. options............... pass
 3. put_get............... pass
 4. put_get_utf8_segment.. pass
 5. put_no_parent......... pass
 6. mkcol_over_plain...... pass
 7. delete................ pass
 8. delete_null........... pass
 9. delete_fragment....... pass
10. mkcol................. pass
11. mkcol_again........... pass
12. delete_coll........... pass
13. mkcol_no_parent....... pass
14. mkcol_with_body....... pass
15. finish................ pass
<- summary for `basic': of 16 tests run: 16 passed, 0 failed. 100.0%
-> running `copymove':
 0. init.................. pass
 1. begin................. pass
 2. copy_init............. pass
 3. copy_simple........... pass
 4. copy_overwrite........ pass
 5. copy_nodestcoll....... pass
 6. copy_cleanup.......... pass
 7. copy_coll............. pass
 8. copy_shallow.......... pass
 9. move.................. pass
10. move_coll............. pass
11. move_cleanup.......... pass
12. finish................ pass
<- summary for `copymove': of 13 tests run: 13 passed, 0 failed. 100.0%
-> running `props':
 0. init.................. pass
 1. begin................. pass
 2. propfind_invalid...... pass
 3. propfind_invalid2..... FAIL (PROPFIND with invalid namespace declaration in body (see FAQ) got 207 response not 400)
 4. propfind_d0........... pass
 5. propinit.............. pass
 6. propset............... pass
 7. propget............... pass
 8. propextended.......... pass
 9. propmove.............. pass
10. propget............... pass
11. propdeletes........... pass
12. propget............... pass
13. propreplace........... pass
14. propget............... pass
15. propnullns............ pass
16. propget............... pass
17. prophighunicode....... pass
18. propget............... pass
19. propremoveset......... pass
20. propget............... pass
21. propsetremove......... pass
22. propget............... pass
23. propvalnspace......... pass
24. propwformed........... pass
25. propinit.............. pass
26. propmanyns............ pass
27. propget............... pass
28. propcleanup........... pass
29. finish................ pass
<- summary for `props': of 30 tests run: 29 passed, 1 failed. 96.7%
See debug.log for network/debug traces.


This should be a bug of joplin

**Comment by laurent22** [comment]
What you need to do is test for example MKCOL /joplin/.sync as that seems to fail. It would fail if you try with curl so not something related to Joplin. Either the URL is not valid WebDAV or you need to change some settings to allow mkcol on that particular case.

**Comment by gstrauss** [comment]
lighttpd mod_webdav returns 412 Precondition Failed when a conditional part of the request fails.  Does the request pass `If-Match`, `If-None-Match`, or `If-Modified-Since` headers?  If necessary, does the request provide an appropriate lock token in `If`?  If the target exists, does Joplin pass `Overwrite: T` (if that is what is intended)?

Please capture the full request and response headers.  In lighttpd.conf:
`debug.log-request-header = "enable"`
`debug.log-response-header = "enable"`

**Comment by laurent22** [comment]
Closing as not a Joplin bug

**Comment by gstrauss** [comment]
This issue was fixed in lighttpd 1.4.64 (and would have been fixed sooner if reported to lighttpd developers sooner).
(nobody responded to my post above on 29 July 2020)

Latest lighttpd release as I write this is lighttpd 1.4.65.
