### ISSUE TITLE
PDF export without internet links

### ISSUE THREAD

**Issue by rafacouto** [laurent22/joplin#346]
In desktop, exporting to PDF document renders the links without address.

I have explored the code to [this line](https://github.com/laurent22/joplin/blob/613fa20806c5e17eaeb462b1b82329c2427c3347/ElectronClient/app/gui/NoteText.jsx#L460):

    this.webview_.printToPDF({}, (error, data) => {

and it seems an external dependency from the webview React component, but not sure...

**Comment by laurent22** [comment]
Yes it's a function of Electron: https://electronjs.org/docs/api/web-contents#contentsprinttopdfoptions-callback

It doesn't look like there's any option to handle links though
