### ISSUE TITLE
Please release the latest version on NPM

### ISSUE THREAD

**Issue by build3r** [laurent22/joplin#3462]
Hi the latest release is **v 1.0.224** but the current version released on npm is **v 1.0.164** [link](https://www.npmjs.com/package/joplin).
Because of this we are not able to share notes between GUI and CLI version and gives the below error .
```Fatal error:
Error: Unknown profile version. Most likely this is an old version of Joplin, while the profile was created by a newer version. Please upgrade Joplin at https://joplinapp.org and try again.
Joplin version: 1.0.164
Profile version: 30
Expected version: 29
```
Also can we list out steps to build and install the CLI version directly from Github?

**Comment by laurent22** [comment]
Did you use the `--profile` flag? It's not supported and it's going to be removed in a future version (due to causing too many problems, like the problem you have now). If you want to sync two clients, use sync.

**Comment by build3r** [comment]
Thanks will try syncing, I wanted to avoid syncing as both the clients where on same system. Anyways can you also please update the version on NPM.
