### ISSUE TITLE
Improper file names while exporting in MD format

### ISSUE THREAD

**Issue by build3r** [laurent22/joplin#3464]
On Joplin CLI version joplin 1.0.164 (prod) when we export notes though the directory is empty the file names are appended with " (1)\<filename\>.md" or " (2)\<filename\>.md". Also there are empty directories being created of the form (1), (2). 
This leads to duplicate files if we are trying to use git for version control and backup.

## Environment

Joplin version:  1.0.164
Platform: terminal
OS specifics: macOSX Catalina

## Steps to reproduce

1. run command `joplin export --format md  ./` on an empty directory
2. Look at the files 

## Describe what you expected to happen
expectation = proper file names.
Reality: All notes are appended with a prefix " (\d)".

## Logfile
Doesn't have much info 
```
2020-07-07 00:54:36: "Profile directory: /Users/Shabaz/.config/joplin"
2020-07-07 00:54:36: "Trying to load 0 master keys..."
2020-07-07 00:54:36: "Loaded master keys: 0"
2020-07-07 00:54:36: "ResourceFetcher: Auto-add resources: Mode: always"
2020-07-07 00:54:36: "ResourceFetcher: Auto-added resources: 0"
```

**Comment by build3r** [comment]
If any one is facing this issue I'm currently using this script to rename them
```
for d in ./*/  
do 
 if [ -d "$d" ]; then
        cd "$d"
        echo "$d"
        for file in *.md; do 
            if echo "$file" | grep -q " (\d)"; then
                output=$(echo "$file" | grep -o " (\d)")
                mv "$file" "${file#$output}"; 
            fi
        done
        cd ..
 fi       
done
```
Also if anyone is interested can share the whole script which auto exports the specified notes and commit, pushes them to github.

**Comment by laurent22** [comment]
Please give a real example:

- How do the notes and notebooks look Joplin
- How do the files and folders look when you export

**Comment by build3r** [comment]
Hi,
Please find the screen shots
Original File name
<img width="420" alt="image" src="https://user-images.githubusercontent.com/6481548/86909699-1d2b6780-c136-11ea-9fdb-62841fe22d43.png">
Exported File names
<img width="794" alt="image" src="https://user-images.githubusercontent.com/6481548/86909731-274d6600-c136-11ea-9e69-08dc2b6a5b2c.png">
