### ISSUE TITLE
How to work with a tiddlywiki (tiddlywiki.com)?

### ISSUE THREAD

**Issue by merlinuwe** [laurent22/joplin#347]
### Operating system

- [x ] Windows 10
- [ ] macOS
- [x ] Linux Mint 18.3
- [ x] Android
- [ ] iOS

### Application

- [ x] Desktop
- [x ] Mobile
- [ ] Terminal

Hi,

I would like to link to a tiddlywiki file. This is a html-file with javascript. The content is changeable and saved to the file itself. How can I do this and sync it to all my devices (Windows 10, Android, Linux Mint 18.3)?

Thanks for any help.

Greetings,

merlinuwe

BTW: Thank you for this great piece of software!

**Comment by laurent22** [comment]
Duplicate of #279
