### ISSUE TITLE
Improper file names while exporting in MD format 

### ISSUE THREAD

**Issue by build3r** [laurent22/joplin#3473]
Reopening with screen shots as the old issue was closed.
On Joplin CLI version joplin 1.0.164 (prod) when we export notes though the directory is empty the file names are appended with " (1)\<filename\>.md" or " (2)\<filename\>.md". Also there are empty directories being created of the form (1), (2). 
This leads to duplicate files if we are trying to use git for version control and backup.

screen shots
Original File names
<img width="420" alt="image" src="https://user-images.githubusercontent.com/6481548/86909699-1d2b6780-c136-11ea-9fdb-62841fe22d43.png">
Exported File names
<img width="794" alt="image" src="https://user-images.githubusercontent.com/6481548/86909731-274d6600-c136-11ea-9e69-08dc2b6a5b2c.png">

## Environment

Joplin version:  1.0.164
Platform: terminal
OS specifics: macOSX Catalina

## Steps to reproduce

1. run command `joplin export --format md  ./` on an empty directory
2. Look at the files 

## Describe what you expected to happen
expectation = proper file names.
Reality: All notes are appended with a prefix " (\d)".

## Logfile
Doesn't have much info 
```
2020-07-07 00:54:36: "Profile directory: /Users/Shabaz/.config/joplin"
2020-07-07 00:54:36: "Trying to load 0 master keys..."
2020-07-07 00:54:36: "Loaded master keys: 0"
2020-07-07 00:54:36: "ResourceFetcher: Auto-add resources: Mode: always"
2020-07-07 00:54:36: "ResourceFetcher: Auto-added resources: 0"
```

**Comment by build3r** [comment]
Was debugging this issue on my machine it looks like the same directory is passed multiple times to `findUniqueFilename(name, reservedNames = null)` from `makeDirPath_(item, pathPart = null)` function with creates a directory path like "parent_dir/sub_dir/ (1)" 

Also does export need to maintain unique folders?
In my case removing this `output = await shim.fsDriver().findUniqueFilename(output);`  line fixed the problem.
```
async makeDirPath_(item, pathPart = null) {
		let output = '';
		while (true) {
			if (item.type_ === BaseModel.TYPE_FOLDER) {
				if (pathPart) {
					output = `${pathPart}/${output}`;
				} else {
					output = `${friendlySafeFilename(item.title, null, true)}/${output}`;
					//output = await shim.fsDriver().findUniqueFilename(output);
				}
			}
			if (!item.parent_id) return output;
			item = await Folder.load(item.parent_id);
		}
	}
```

**Comment by laurent22** [comment]
Could you try with the recently released v165?

**Comment by build3r** [comment]
Just tried the problem still exists.
