### ISSUE TITLE
Joplin Terminal Installation Fails - Ubuntu 20.04 | Nodejs10+

### ISSUE THREAD

**Issue by rgreg51** [laurent22/joplin#3475]
Hi laurent (apologies if this is something silly from my end)
- currently using joplin for desktop 1.0.218(prod,linux)
- attempting to install joplin terminal (to setup daily backups via cron)
- following installation instructions from: [https://joplinapp.org/terminal/#command-line-mode](url)
- Pre-req: Install Node 10.21.0 (successful on Ubuntu 20.04) --- npm 6.14.4
- Run: 
$ NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/laurent22/node-emoji.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rg/.npm/_logs/2020-07-09T10_37_05_528Z-debug.log

## Environment

Joplin version: Terminal
Platform: Linux
OS specifics: Ubuntu 20.04

## Steps to reproduce

1. NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin

## Describe what you expected to happen
joplin terminal installation to succeed

## Logfile

2051 http fetch GET 200 https://registry.npmjs.org/emphasize/-/emphasize-1.5.0.tgz 48ms
2052 silly pacote range manifest for emphasize@^1.5.0 fetched in 762ms
2053 silly resolveWithNewModule emphasize@1.5.0 checking installable status
2054 timing stage:rollbackFailedOptional Completed in 2ms
2055 timing stage:runTopLevelLifecycles Completed in 26319ms
2056 verbose stack Error: spawn git ENOENT
2056 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
2056 verbose stack     at onErrorNT (internal/child_process.js:468:16)
2056 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
2057 verbose cwd /home/rg
2058 verbose Linux 5.4.0-37-generic
2059 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "joplin"
2060 verbose node v14.5.0
2061 verbose npm  v6.14.5
2062 error code ENOENT
2063 error syscall spawn git
2064 error path git
2065 error errno -2
2066 error enoent Error while executing:
2066 error enoent undefined ls-remote -h -t https://github.com/laurent22/node-emoji.git
2066 error enoent
2066 error enoent
2066 error enoent spawn git ENOENT
2067 error enoent This is related to npm not being able to find a file.
2068 verbose exit [ -2, true ]

**Comment by jrmy911** [comment]
Yep, same here.

**Comment by cedarice** [comment]
The reason for this issue may be that git is not installed.

**Comment by rgreg51** [comment]
Thanks @cedarice ... I knew it was something silly from my end....
