### ISSUE TITLE
[feature request] Kanban board using TODO.md format

### ISSUE THREAD

**Issue by ribtoks** [laurent22/joplin#3478]
Hi

First of all, thanks a lot for developing Joplin!

I don't know Joplin/plugins architecture and I'm curious how hard will be to integrate [coddx](https://github.com/coddx-hq/coddx-alpha) library to visualize kanban boards in Joplin using TODO.md format?

This would be absolutely awesome and really help me and others to transition from Notion.so since that's pretty much the last big feature missing in Joplin.

Any tips on how to integrate it would be very helpful, as I don't have any experience in Electron.

**Comment by ribtoks** [comment]
Hey @laurent22 any pointers/help would be very welcome. Any ideas how to start?

**Comment by deverton** [comment]
Related? https://github.com/laurent22/joplin/issues/3567

**Comment by ribtoks** [comment]
@deverton Yup, looks cool!

**Comment by ribtoks** [comment]
Not stale!

**Comment by ribtoks** [comment]
Not stale

**Comment by ribtoks** [comment]
Not stale

**Comment by ribtoks** [comment]
Not stale
