### ISSUE TITLE
Syntax orgmode

### ISSUE THREAD

**Issue by uGeek** [laurent22/joplin#348]
Do you plan to add the orgmode syntax in the notes?

### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [x] Android
- [ ] iOS

### Application

- [x] Desktop
- [x] Mobile
- [x] Terminal

**Comment by Nebucatnetzer** [comment]
This would be great.
IMO it's much nicer than Markdown.

**Comment by laurent22** [comment]
There's currently no plans to add new syntaxes and I think that would be out of scope due to the complexity of handling this for all the clients.
