### ISSUE TITLE
Add BibTex support

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#3480]
Adding support for BibTex references should be possible via the upcoming plugin API. It would require hooking into the config screen, note editor and note viewer:

# Config screen

Add a way to import a BibTex file. That file could be updated outside the application by Zotero, so it should be watched for changes.

# Note editor

Create a new `addBibTexReference` command that does the following:

- Displays a dropdown list with type-ahead, where user can enter a citation key - for example "SmithStatisticalMechanics2015". When user starts typing "Smith", it should auto-complete
- Add the citation to the text in this format:

```markdown
[@SmithStatisticalMechanics2015](http://dx.doi.org/10.1002/andp.19053221004)
```

Adding it that way means that it is valid Markdown that works in any Markdown tool

- The `addBibTexReference` command should be available as a menu item and associated shortcut.

# Note viewer

- Create a new markdown-it plugin that parses URLs and find those that start with @. It will then map these keys to the corresponding BibTex reference. This is then used to display the references as **(Smith 2015)** in the rendered view.
- At the bottom of the rendered note, the references should be displayed in full: eg. "*Statistical mechanics describes how macroscopic observations are related to microscopic parameters that fluctuate around an average (Smith 2015)*", then **(Smith 2015)** should link to it.

**Comment by antonDigitalMagic** [comment]
Hello!

When it will be possible to start working on this feature?

**Comment by turian** [comment]
I am also curious about this

**Comment by MirceaDavidEsc** [comment]
Would be an amazing plug-in, especially with Zotero integration. Definitely interested in this.

**Comment by Klemet** [comment]
I am extremely interested in this feature too. I use references in Markdown very often, and it's dearly missing from Joplin for me.

If I might just add a suggestion : I think that such a plugin would benefit to [imitate the way that the `citeproc` extension of Pandoc works](https://pandoc.org/demo/example19/Extension-citations.html). I imagine that it will also make older documents, made with Pandoc in mind, more compatible with this plugin.

Indeed, the citeproc extension allows for different ways to cite in text, all leading to a reference at the end of the document. Some quick examples to explain what I mean : 

**Inline citation**
`As said by @dijkstra1965` -> As said by Dijkstra (1965)

**In-braket citation**
`This algorithm works [@dijkstra1965]` -> This algorithm works (Dijkstra, 1965)

**Citation without author name**
`Dijkstra said it in one of his best articles [@-dijkstra1965]` -> Dijkstra said it in one of his best articles (1965)

**Multiple citations in one pair of brackets**
`This algorithm works [@dijkstra1965; @MacThingy1968]` -> This algorithm works (Dijkstra, 1965; MacThingy, 1968) 

**Multiple citations in one pair of brackets AND other things inside the brackets**
`This algorithm works [as said by @dijkstra1965; and @MacThingy1968]` -> This algorithm works (as said by Dijkstra, 1965 and MacThingy, 1968) 

Maybe it would be best to just recognize a character chain starting with @ and ending with a space ? This way, the presence of brackets can be detected to imitate the way that `citeproc` does it. If square brackets are detected around this character chain, then the rest could be done too ?

**Comment by xUser5000** [comment]
@Klemet 
Just in time!
BTW, I'm the one who is working to implement that plugin during the period of the Google Summer of Code Program. I was wondering yesterday about how I will format the inline citation and your answer is of great help to me. Thanks a  lot.

Also, you might want to track the development lifecycle of the plugin [here](https://discourse.joplinapp.org/c/gsoc-projects/bibtex-plugin/21). This is where we discuss all things related to the plugin, so you can add whatever you want there.

**Comment by Klemet** [comment]
Wow, that's an amazing timing indeed ! Thanks a lot, @xUser5000 ! I'll be sure to help as I can there.
