### ISSUE TITLE
Cannot create a new sub-notebook.

### ISSUE THREAD

**Issue by d4rk-d4nph3** [laurent22/joplin#3486]
I cannot create a new-subnotebook. The first update broke it. Then, another update came and the bug persisted even after updating to the latest one.

## Environment

Joplin version: 1.0.227
Platform: Mac
OS specifics: MacOS Catalina 10.15.5

# Steps to reproduce

1. Attempt to create a sub-notebook.

I have reverted back to 1.0.224 for now.

**Comment by laurent22** [comment]
Cannot replicate
