### ISSUE TITLE
Cursor is moving further away when typing in Cyrillic

### ISSUE THREAD

**Issue by seslav** [laurent22/joplin#3487]
Hi,

First of all thanks for this amazing app, it really changed a lot in my day-to-day work. 

I encountered an issue when typing in Cyrillic the cursor is moving further away thus making this tool bit hard to use in Cyrillic.
I tested it with Joplin 1.0.227 (prod, darwin)

## Environment

Joplin version: 1.0.227 (prod, darwin)
Platform: MacOS
OS specifics: Mac OS Catalina 10.15.5

## Steps to reproduce

1.  Create new note
2. Start typing in Cyrillic (Bulgarian in my case)

Gif to reproduce: 
![2020-07-12 19 08 38](https://user-images.githubusercontent.com/5594036/87251459-9e576700-c474-11ea-8adf-975f3239fbee.gif)

**Comment by hb20007** [comment]
Related: https://github.com/laurent22/joplin/issues/3435

**Comment by dpoulton-github** [comment]
Is the editor font you are using monospace?

**Comment by seslav** [comment]
I haven't change the font, it should be the default one.
<img width="904" alt="Screenshot 2020-07-17 at 14 08 05" src="https://user-images.githubusercontent.com/5594036/87780290-120fc000-c837-11ea-904c-f847ea86ffe7.png">

**Comment by dpoulton-github** [comment]
You could try a Cyrillic font that you know is monospace. I think others have posted about this here or on the forum and suggested that the default font offered up by the mac is not actually monospace. That could be a false memory!! Unfortunately I do not have the time at the moment to try to track the post down....

**Comment by seslav** [comment]
The issue you mentioned seems the same. 

I tried with **PT Mono** as font and it looks fine.

**Comment by banan314** [comment]
I had a similar issue (I don't remember which version it was), I changed the font to **OpenSans** and it looks fine as well.
