### ISSUE TITLE
Secrity Issue - plain text passphrase in sqlite db

### ISSUE THREAD

**Issue by dincsi** [laurent22/joplin#349]
### Operating system

- [x ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x ] Desktop
- [ ] Mobile
- [ ] Terminal

I have experienced a security issue in Joplin: The passphrases are stored in plain text in sqlite db, so anyone who can access your files locally are able to decrypt all your notes. Please consider an option not to store passphrase or other way to store password more secure way locally.

**Comment by laurent22** [comment]
This was discussed in another issue, but the local data is not protected in any special way, it relies on built-in OS security features. We just make sure that passwords aren't logged to files but anything required by the application will be in plain text at some point or another (even if it was encrypted on file, it would be decrypted in memory).

If you require more security it's recommended to put your Joplin profile on a Truecrypt partition or similar.

**Comment by dincsi** [comment]
I already have a VeraCrypt volume for storing sensitive information, so my first plan to use this for storing Joplin notes too, but it seams to me I cannot access files in an EDS container by Joplin android app. That's why I tried to use the inbuilt webdav sync with e2ee in Joplin. But, I get your point, thanks for your respond.

**Comment by foxmask** [comment]
"Secrity" typo un the subject 😎
