### ISSUE TITLE
No popup appears on the second invokation of "move to notebook"

### ISSUE THREAD

**Issue by alusiani** [laurent22/joplin#3493]
When I mouse-right-click on a note, and then select "Move to Notebook", a popup appears. I select a notebook from the popup list and then confirm. The note however is not moved to the selected notebook. Furthermore, if I retry, no popup appears. Also, if I click on "New Notebook" no popup appears any more. To recover all functionality, Joplin must be restarted.

## Environment

Joplin version: 1.0.227
Platform: Linux
OS specifics: Fedora 32

## Steps to reproduce

1. select a note
2. right-mouse-click on the note title in the note titles panel
3. select "Move to Notebook"
4. select an existing Notebook
5. press "Confirm"
6. nothing happens
7. right-mouse-click on the note title in the note titles panel
8. nothing happens, no popup appears

## Describe what you expected to happen

The actions should move the note on focus to another Notebook.

## Logfile

[joplin-debug-jul20.log](https://github.com/laurent22/joplin/files/4917081/joplin-debug-jul20.log)

## Note

After having looked at the logfile, I see several error messages that appear to be related just to the specific package prepared for Fedora 32. Therefore it may be that the reported issues are specific to the Fedora 32.

**Comment by laurent22** [comment]
Should be fixed in latest pre-release 1.0.229
