### ISSUE TITLE
Encrypted attachment file (.crypted) not deleted when attachment is deleted

### ISSUE THREAD

**Issue by articlecat** [laurent22/joplin#3494]
Deleting an attachment from `Tools -> Note attachments...` when encryption is enabled results in the attachment file being deleted, but not the associated `.crypted` file.

## Environment

Joplin version: 1.0.227
Platform: Linux (desktop)

## Steps to reproduce

With encryption enabled:

1. Attach a file to a note.
2. In a file manager or terminal, verify that `~/.config/joplin-desktop/resources/[filename].[extension]` and `~/.config/joplin-desktop/resources/[filename].crypted` exist.
3. Go to `Tools -> Note attachments...`.
4. Delete the attachment.
5. In a file manager or terminal, see that `~/.config/joplin-desktop/resources/[filename].[extension]` was deleted, but `~/.config/joplin-desktop/resources/[filename].crypted` still exists.

## Describe what you expected to happen

After deleting an attachment from `Tools -> Note attachments...` when encryption is enabled, both `~/.config/joplin-desktop/resources/[filename].[extension]` and `~/.config/joplin-desktop/resources/[filename].crypted` should be deleted.

**Comment by articlecat** [comment]
Reproducible in v1.0.233

**Comment by manuerwin** [comment]
Is there a way for this to be re-opened? It's still a bug....

**Comment by thomaschampagne** [comment]
Still a bug today in v3.0.15
