### ISSUE TITLE
import cause notes lost

### ISSUE THREAD

**Issue by verneSil** [laurent22/joplin#3495]
## what happend:

i use this application for a long time. i sync to a directory every now and then. and i would use git to backup this dir to my github.
however i reinstall my computer operation system yesterday. and today i try to import notes from these backup dir. i failed . and i receive a message.i put the screenshot and you can see it.
![image](https://user-images.githubusercontent.com/63391767/87408258-cc17e980-c5f5-11ea-9be0-0ce9c3936507.png)

## Environment

Joplin version: 
Platform:  manjaro linux
OS specifics: Linux version 4.19.126-1-MANJARO

## Steps to reproduce
i can't reporduce. but here is my backup of notes. only part of these notes could be import .you can try on your computer to import .
some time it could import .but after imported,you can see it has lost many files which the directory has.
but i lost many files.i could remember i had at least 450 notes in total before i reinstalled my system.and i'm sure i backup them to github . and you can see the commit history of github i just update yesterday.
but now i can only get about 200+ note back;

backup: https://github.com/verneSil/joplinNotebook.git

**Comment by laurent22** [comment]
That's not a backup but a sync directory, so you can sync with it but not import it.

**Comment by verneSil** [comment]
wow? i'm confused~~   is that mean i can't import files which are synced ?
personally i don't think this is a good design

**Comment by laurent22** [comment]
What? no, what you have is essentially a database - it's an efficient format that Joplin uses to sync data. So you can sync with this if you want.

If you want to import/export data, you need to export the data as a JEX or RAW archive.

But you can't import a sync directory, and you can't sync with an exported archive. Those are different things.
