### ISSUE TITLE
feature request: add support for "open in ..." for unsupported attachments 

### ISSUE THREAD

**Issue by dastrobu** [laurent22/joplin#350]
It would be great to have the option to open attachments of a note in an app that can open it on iOS. 
Currently there is just a note, which states "Resource not yet supported: ...". Since it is unlikely, that Joplin will be ever capable of supporting all possible files, the better strategy would be to provide the option to open the resource in the app that can support the specific file type.

### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [X] iOS

### Application

- [ ] Desktop
- [X] Mobile
- [ ] Terminal

**Comment by valmar** [comment]
@laurent22 Can I do something (testing, etc.) to help developing this functionality?
