### ISSUE TITLE
Editing window no longer resizes when sidebars are toggled

### ISSUE THREAD

**Issue by CalebJohn** [laurent22/joplin#3503]
## Environment

Joplin version: master 3807317
Platform: Linux
OS specifics: Ubuntu 20.04

## Steps to reproduce

1. Toggle the sidebar or notes list

## Describe what you expected to happen
The Editor component (Ace, CodeMirror, WYSIWYG) should resize to the new dimensions, instead there is a whitespace left on the right hand side of the window

![image](https://user-images.githubusercontent.com/2179547/87587583-7f88e880-c69f-11ea-8f15-60f11b51be9a.png)

**Comment by tessus** [comment]
This also happens when toggling sidebar and/or notelist.

**Comment by CalebJohn** [comment]
Thanks @laurent22
