### ISSUE TITLE
Incorrect handling of cyrillic symbols

### ISSUE THREAD

**Issue by mitrakov** [laurent22/joplin#3504]
Recently updated on v.1.0.224 (MacOS) and cyrillic symbols stopped working correctly in edit mode (cursor position gets shifted):

![bug](https://user-images.githubusercontent.com/23196292/87588110-c56b9e00-c6eb-11ea-80f7-b9256b591441.gif)
The same bug remains for v.227.

## Environment

Joplin version: Joplin 1.0.227 (prod, darwin)
Platform: MacOS
OS specifics: Catalina 10.15.4

## Steps to reproduce

1. Start typing Cyrillic symbols in edit area

## Describe what you expected to happen
Correct working of any layout input, as it was in previous versions.

**Comment by dpoulton-github** [comment]
Same as https://github.com/laurent22/joplin/issues/3487 ?

**Comment by mitrakov** [comment]
Yes. The same. Closing as a duplicate.
I hope we'll see a fix soon 👍
