### ISSUE TITLE
Tags sorting in (apparently) random order

### ISSUE THREAD

**Issue by bladewolf55** [laurent22/joplin#3507]
## Issues
In version 1.0.229, tags no longer sort alphabetically.

![image](https://user-images.githubusercontent.com/2903411/87623115-e7f8b980-c6e1-11ea-8d08-62db8512bb2a.png)

## More Information
I don't have Joplin running on multiple Windows 10 machines, so haven't confirmed the behavior, but the issue only appeared after the upgrade so I'm assuming it's due to that.

## Environment
Joplin 1.0.229 (prod, win32)
Revision: d0b3e159 (master)
Windows 10 Professional

**Comment by laurent22** [comment]
Will be fixed in next release

**Comment by bladewolf55** [comment]
Thank you!
