### ISSUE TITLE
Adjustable middle window

### ISSUE THREAD

**Issue by ferencdv** [laurent22/joplin#351]
### Operating system

- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

**Comment by ferencdv** [comment]
Dear Laurent,
Would it be possible to have a button so that the middle window disappears while editing? In this case it might make more efficient use of real estate.
Keep up the great work! Very happy with the pdf export.
Ferenc

**Comment by laurent22** [comment]
Yes that will be implemented at some point. Closed as duplicate for now.

**Comment by ferencdv** [comment]
Thanks Laurent,  I am looking forward to it.
Ferenc

----------------------------------------------------------------
Dr. Ferenc (Jacob) Dalnoki-Veress
Scientist-in-Residence & Adjunct Professor
James Martin Center for Nonproliferation Studies (CNS)
Middlebury Institute of International Studies at Monterey
460 Pierce Street, Monterey, CA, 93940
Phone: +1 (831) 647-4638   Fax:+1 (831) 647-3519
www.miis.edu/academics/faculty/FDalnokiVeress
Email: jdalnokiveress@miis.edu
Email: ferencdv@protonmail.ch
@ferencdv
