### ISSUE TITLE
WYSIWYG - Empty lines are automatically removed

### ISSUE THREAD

**Issue by armaccloud** [laurent22/joplin#3511]
## Description
When adding empty lines to a note in the WYSIWYG editor, the empty lines are removed from the text after switching to another note and back. The empty lines are not saved with the note.

## Environment

Joplin version: 1.0.227
Platform: Linux
OS specifics: Pop!_OS 20.04 LTS

## Steps to reproduce

1. Create a new note using the WYSIWYG editor
2. Create a text containing several lines and empty lines in between them
3. Switch to another note and then back to this newly created note
4. Verify the empty lines have been removed

## Describe what you expected to happen
The text retains its formatting with empty lines

**Comment by laurent22** [comment]
Fixing this might be tricky but I'll check. Just to see if there's not alternative fix, what's your use case for adding multiple empty lines to a note?

**Comment by armaccloud** [comment]
The ability to insert an empty line makes sure that I can do formatting on the texts where its needed. Not necessarily multiple empty lines, but at least single empty lines with a text.

For example, making a list of explanations with a name in bold, without using headers (otherwise they would become too many headers for an eventual TOC) for this, such as the following

**Text 1**
TextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTe

**Text 2**
TextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTe

**Text 2**
TextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTe

Also for making study or meeting notes. For clarity & overview, using empty lines I can keep overview of slight deviations within subjects (they are not supposed to get their own headings) by showing them a bit separate with empty lines.

**With empty lines** (formatting removed after switching notes)
![image](https://user-images.githubusercontent.com/9272078/88387146-2bbe8380-cdb2-11ea-8237-22814153906b.png)

**Without empty lines**
![image](https://user-images.githubusercontent.com/9272078/88387099-10537880-cdb2-11ea-9dc1-1a14fe350d44.png)

**Comment by laurent22** [comment]
I've had a look but there's no easy way to handle this case. The underlying format is Markdown and thus anything we can do is limited by it, and Markdown always collapses multiple new lines into one. One way to separate content is to use for example rulers or other conventions you might want to pick, but multiple new lines most likely won't be supported.

**Comment by armaccloud** [comment]
Hi @laurent22 I'm sorry to hear that, but if it's not possible then it stops. I will use separators from now on. Thanks for looking into it.

**Comment by alexgoussev** [comment]
> Markdown always collapses multiple new lines into one
You are wrong. Markdown renderers nut not Markdown itself. For example Typora can render multiple new lines as empty lines.

**Comment by Samvdg** [comment]
@laurent22 Is this perhaps able to be revisited? It's been a while and I'd really benefit from being able to add atleast 1 whiteline.

**Comment by MrBrownSound** [comment]
Hello @laurent22 It has been a while this has been addressed. Would you be able to take a look again. Many of my users I want to onboard to Joplin cannot use markdown. If there can be some programmatic way for the rich text editor to add a hidden "/br" (brackets removed) when the user hits enter to go to new line, it would solve the issue. Similar to how user can bold text in rich editor mode, and markdown automatically gets generated.

**Comment by rpld** [comment]
Hi, seems it's been resolved? 
With 2.14.22 and I realized multiple empty lines just work now.
I don't know what caused the change or when.

**Comment by laurent22** [comment]
Yes this has been fixed
