### ISSUE TITLE
Desktop: undo/redo is not working when editing note title

### ISSUE THREAD

**Issue by danielb2** [laurent22/joplin#3513]
Similarly to [Mobile](https://github.com/laurent22/joplin/issues/3399), undo/redo isn't working in desktop

## Environment

Joplin version: Joplin 1.0.227 (prod, darwin)
Platform: macos
OS specifics: Mojave

## Steps to reproduce

1. create a new note
2. edit the title of the note
3. hit ctrl+z for undo

## Describe what you expected to happen

typed text to be undone like in note body

**Comment by RedDocMD** [comment]
The title is not a part of the editor, and changes to it are handled separately. I guess it is more of a feature addition than a bug fix.
@laurent22, what are your thoughts on this?

**Comment by danielb2** [comment]
@RedDocMD  I would argue it's a bug because it's _expected_ behavior.  Show me any other note taking app, or app which doesn't allow undo in the title.

**Comment by laurent22** [comment]
Yes I guess it's not broken, just not implemented, but it should be.

**Comment by laurent22** [comment]
Note: it seems to be macOS only

**Comment by danielb2** [comment]
this appears to work as expected now
