### ISSUE TITLE
Binary delta updates for Linux users

### ISSUE THREAD

**Issue by developomp** [laurent22/joplin#3514]
AppImage has a feature to download the difference in the binary file and update it without having to download everything over again ([6th point in this site](https://github.com/AppImage/AppImageKit/wiki#-why-should-i-bundle-my-application-as-an-appimage)).

Downloading 100 ish megabyte a file is nothing for most people but for people with telephone line speed like me, this will be a welcomed feature. This is especially true considering that Joplin has a release coming out every week or two (sometimes several updates within a week).

**Comment by laurent22** [comment]
Why would you update the app several times a week if you are on a mobile connection? I'm also sometimes on a metered connection and just switch off automatic update for everything. It's more than enough to update the app once or twice a month if you don't need to get the very latest features.

**Comment by developomp** [comment]
It's for the sake of having an option, but it's still a good option to have when you have a really slow internet.
I get around 100kbps on average and it takes forever to download Joplin appimage.
