### ISSUE TITLE
Joplin Appimage does not have correct Icon (Pop!_OS, Linux)

### ISSUE THREAD

**Issue by Tiger862000** [laurent22/joplin#3529]
Hi, in this #https://github.com/TheAssassin/AppImageLauncher/issues/323#issuecomment-660677262 issue I already reported 
on the issue the author asked me to report directly in Joplin repo.

Joplin App does not have the correct application icon on my desktop panel (see screenshot). It instead uses a different one. Yet the icon in the Topbar is the correct one...

The author of AppImageLauncher suggested to analyze via  `appimagelint` - see log below.

What can I do against? Where are icons stored in Appimages? Please help. Thank you!

## Environment

Joplin version: 1.0.227
Platform: Linux 64Bit 
OS specifics: Pop!_OS 20.04

## Steps to reproduce

1. Install Joplin via Appimage and manage via Appimage Launcher
2. Open Joplin
3. Use Joplin normally

## Describe what you expected to happen
Joplin icon should appear on the left panel.

![Screenshot from 2020-07-19 20-07-58](https://user-images.githubusercontent.com/12417480/87881909-d32b6700-c9fc-11ea-9804-147f7fec9422.png)

## Logfile

<pre><font color="#3465A4">appimagelint.cli[5281]</font> <font color="#06989A">[INFO]</font> Running check &quot;Icons validity and location check&quot;
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> Extracting icon name from desktop file: /tmp/.mount_JoplinRIiES4/joplin.desktop
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> Checking resolution of icon: /tmp/.mount_JoplinRIiES4/joplin.png
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> [<font color="#73C48F">✔</font>] Valid icon in AppDir root
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> Checking resolution of icon: /tmp/.mount_JoplinRIiES4/.DirIcon
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> [<font color="#73C48F">✔</font>] Valid icon file in .DirIcon
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> Checking resolution of icon: /tmp/.mount_JoplinRIiES4/usr/share/icons/hicolor/0x0/apps/joplin.png
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[ERROR]</font> <font color="#CC0000">Icon resolution doesn&apos;t match resolution in path: (0, 0) (file resolution is (256, 256))</font>
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[WARNING]</font> <font color="#C4A000">no other icons found</font>
<font color="#3465A4">appimagelint.icons_check[5281]</font> <font color="#06989A">[INFO]</font> [<font color="#F15D22">✖</font>] Other integration icons valid</pre>

**Comment by armaccloud** [comment]
This could be related to #3428 (also on Pop!_OS)
A workaround is to use the app `appeditor` to select an icon to Joplin after installing a new version, which is what I do now.

![image](https://user-images.githubusercontent.com/9272078/88389143-311dcd00-cdb6-11ea-9e82-37fc3cb1aca2.png)

**Comment by Jesssullivan** [comment]
Looks `./Joplin_install_and_update.sh` doesn't run  `update-desktop-database` on the icons directory- added this in PR #3570 , 
did the trick in Budgie Desktop.  @Tiger862000 LMK if this doesn't do the trick in Pop!_OS

**Comment by Tiger862000** [comment]
@armaccloud thank you! Your workaround fixed the problem for me. Still, it is strage why the icons aren't installed by default.
