### ISSUE TITLE
macOS: Alarm does not work

### ISSUE THREAD

**Issue by petzi53** [laurent22/joplin#3531]
To set up an alarm on my macOS does not work. When the time comes the alarm does not show up. But alarms do work on the iPad.

I used a time outside my “do not disturb” time. I tried it with Joplin open and Joplin closed. My ToDo Note was not checked.

As far as I understand Joplin should be listed in my Mac Notification Center. But Joplin doesn’t show up in the notification center.

I’m using macOS Catalina 10.15.5 and Joplin 1.0.227 (prod, darwin)

## Environment

Joplin version: Joplin 1.0.227 (prod, darwin)
Platform: macOS
OS specifics:  Catalina 10.15.5

## Steps to reproduce

1. Create a new To-Do (macOS: Cmd-T)
2. Enter title and (optional) body text
3. Set Date & Time for the alarm
4. Confirm with "OK"

## Describe what you expected to happen

At the dedicated time, a notification should appear.

## Logfile

[Log file](https://github.com/laurent22/joplin/files/4944387/from-file-log.txt)

[Console](https://github.com/laurent22/joplin/files/4944386/from-console.txt)

**Comment by laurent22** [comment]
should be fixed on 229
