### ISSUE TITLE
notes on MacOS have no geolocation info

### ISSUE THREAD

**Issue by LeoK987** [laurent22/joplin#3532]
## Environment

Joplin version: 1.0.227
Platform: MacOS
OS specifics: 10.15.5

## Steps to reproduce

1. create a new note
2. check properties of the note
3. location is empty

**Comment by robertour** [comment]
Same issue here:

```
Joplin version: 1.0.242 (prod, linux)
Platform: Ubuntu 18.04
```

and

```
Joplin version: 1.0.242 (prod, win32/win64)
Platform: Windows 10
```

**Comment by LeoK987** [comment]
Ya, the issue is clearly still here on the Mac.  Why close this?
