### ISSUE TITLE
Undo corrupts entire note

### ISSUE THREAD

**Issue by smiller86** [laurent22/joplin#3534]
## Environment

Joplin version: 1.0.227
Platform: Desktop, Windows
OS specifics: Windows 10

## Steps to reproduce

1. Create a note or edit an existing note
2. Add some text or make changes to the note
3. Press Ctrl+Z several times

Once all recent changes have been reverted back to the original state, pressing Ctrl+Z again will erase the entire note and replace it with text from a different note. Must go to Note History to recover a previous version (thankfully this saved my work).

## Describe what you expected to happen
Pressing Ctrl+Z should stop taking action once recent changes have all been undone.

## Logfile

I'm not that smart.

**Comment by laurent22** [comment]
which editor?

**Comment by smiller86** [comment]
I was using the WYSIWYG editor at the time. My apologies for not mentioning that in the original post.
