### ISSUE TITLE
WYSIWYG - Table gets header row added after switching notes

### ISSUE THREAD

**Issue by armaccloud** [laurent22/joplin#3535]
## Environment

Joplin version: 1.0.227
Platform: Linux
OS specifics: Pop!_OS 20.04

## Steps to reproduce

1. Create a simple table, 2 rows, 2 columns
2. Enter some data in the cells
3. Switch to another note
4. Switch back to the note with the table
5. Verify a new (top) row has been added to the table

## Describe what you expected to happen
There should not be an additional row be added, the table should contain the top row as part of the creation process.

## Screencast
![Added top row Joplin](https://user-images.githubusercontent.com/9272078/87976847-11dd2200-cace-11ea-953c-c959b50b8712.gif)

**Comment by laurent22** [comment]
This is as designed because Markdown requires tables to have row. So even if you don't have them when you add them, they are added back when saving.

**Comment by armaccloud** [comment]
Hi @laurent22 
This sounds logical to me as a technical requirement, but not from a UI / end user perspective.
When I create a table using the wysiwyg interface, it would be logical if the markdown top row would already be included.
So, when I choose 2x2 table, there would be 1 row header and one normal row. Could you reopen this issue to address this?

**Comment by laurent22** [comment]
@armaccloud, the problem is that we rely on TinyMCE table editing for this and it's quite flexible, more flexible than what's allowed by Markdown. That means even if we add a header, the user could delete it... and it will be back when saving and reopening the note. It's a known limitation for which there's no easy fix (other than rewriting the TinyMCE table editing tool which would be a huge undertaking).

**Comment by armaccloud** [comment]
@laurent22, maybe I don't understand completely or thinking about it too simply, but it doesn't really sound like that much of an issue that the top row is added back if the user would delete the top row if the functionality is in.

My point is that a row is added outside of view unexpectedly, which basically means that if you want to create a table, you have to follow the following process

1. Create a table
2. Switch away from the note
3. Switch back to the note
4. Start filling the table

Reason is because if you start adding header row info immediately after creating the table, that info will end up in the second row (non-bold) when you reopen the note and have to edit the table to correct this. This is not user friendly in my experience.

Maybe the table functionality from the TinyMCE editor doesn't allow to add a top row in the format that is needed for markdown as part of the table creation process?
In that case, would it be an option to have separate code converting the top row into a markdown top row, so that it is immediately in the correct format after adding the table in the view? I think that an additional top row should not be created (this would provide the user with an additional row that wasn't chosen from the table picker), but the first row should somehow become a top row in the format required by markdown.

Thank you for looking into this.

**Comment by laurent22** [comment]
Yes it's true, ideally it should at least add the header automatically from the start. I'll re-open for now and will see if that can be improved.
