### ISSUE TITLE
web clipper screenshot not matching mouse rectangle

### ISSUE THREAD

**Issue by LeoK987** [laurent22/joplin#3537]
## Environment

Joplin version: 1.0.227
Platform: MacOS
OS specifics: 10.15.5

## Steps to reproduce

1. Tap the Joplin button on browser
2. Choose clip screenshot
3. Drag and release the mouse to define a rectangle
4. check the clipped note in Joplin

## Logfile

https://apple.stackexchange.com/questions/32297/how-can-i-reassign-the-copy-paste-keyboard-shortcuts

Brave browser Version 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)

**Comment by laurent22** [comment]
This is an issue with HDPI screens for which there's currently no solution
