### ISSUE TITLE
opt-in to the editer beta bug

### ISSUE THREAD

**Issue by currencyporter** [laurent22/joplin#3538]
## Environment

Joplin version: 1.0.333
Platform: android
OS specifics: 

## Steps to reproduce

1. After choosing opt-in to the editer beta,
2. When inputting text, the cursor will jump randomly,Can not edit text normally
3. If you press backspace, you will exit joplin directly.

**Comment by laurent22** [comment]
Yes unfortunately this editor doesn't currently work in Android.
