### ISSUE TITLE
http://127.0.0.1:41184/tags response error 500

### ISSUE THREAD

**Issue by luguohong** [laurent22/joplin#3539]
when i use web clipper and it access "http://127.0.0.1:41184/tags"
the response is that
{"error":"Internal Server Error: Cannot read property 'length' of undefined: \n\nTypeError: Cannot read property 'length' of undefined\n    at Api.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/lib/services/rest/Api.js:290:31)\n    at Api.action_tags (/Applications/Joplin.app/Contents/Resources/app.asar/lib/services/rest/Api.js:312:29)\n    at Api.route (/Applications/Joplin.app/Contents/Resources/app.asar/lib/services/rest/Api.js:110:42)\n    at execRequest (/Applications/Joplin.app/Contents/Resources/app.asar/lib/ClipperServer.js:160:39)\n    at Server.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/lib/ClipperServer.js:203:7)\n    at Server.emit (events.js:210:5)\n    at parserOnIncoming (_http_server.js:745:12)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)"}
so i can't use the web clipper

joplin version mac 1.0.229
system version mac catalina 10.15.5

**Comment by laurent22** [comment]
@vsimkus, I think that might be related to the tag hierarchy update. Any idea how to fix it?

**Comment by vsimkus** [comment]
Yes, the web clipper should be released as well. But I think I should also provide a default empty fields list - in case a fields query key is not provided in the query. I will open a PR for this.
