### ISSUE TITLE
Share on Android

### ISSUE THREAD

**Issue by koulaxizis** [laurent22/joplin#354]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [X] Android
- [ ] iOS

### Application

- [ ] Desktop
- [X] Mobile
- [ ] Terminal

First of all, thank you for this wonderful app, I use it with Nextcloud and I absolutely love it! <3

Are there any plans to intergrate Joplin with the android "share" option?

For example: Send/Share/Save a link from browser to Joplin via the Share menu, without Copy-Paste.

**Comment by Avizini** [comment]
Yes I also looked for this first. Meanwhile get an editor or even NC Notes and first take your shared stuff there, then copy and paste in Joplin.

Would love direct integration.

**Comment by laurent22** [comment]
Duplicate of #354

**Comment by gerroon** [comment]
This is #354? You seemed to close this #354 for being duplicate of #354

**Comment by laurent22** [comment]
Right, it should have been that one: https://github.com/laurent22/joplin/issues/110
