### ISSUE TITLE
Headless server fails to start in 1.0.165

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#3541]
https://discourse.joplinapp.org/t/headless-server-fails-to-start-in-1-0-165/10191

**Comment by laurent22** [comment]
Duplicate of #3350

**Comment by SebastianSeltmann** [comment]
I don't understand how this us a duplicate of [#3350](https://github.com/laurent22/joplin/issues/3350).

This issue is unrelated to syncing.

**Comment by laurent22** [comment]
Sorry should have been #3548
