### ISSUE TITLE
Adding multiple sources / syncronisation directories

### ISSUE THREAD

**Issue by eazy** [laurent22/joplin#3546]
Hi,

it would be very cool to sync multiple Joplin folders to realize something like permissions and organize all kind of documentation in one tool.

As an example:
1. webdav - knowledgebase of my company
2. dropbox - shopping list of my wife
3. nextcloud - documents of an society

Thanks

**Comment by jakobjoachim** [comment]
i too would like this feature

**Comment by guenth** [comment]
It would be nice to be able to sync work things from one source (not owned/controlled by me) and personal things from another source (that is controlled by me).

I could do this with profiles, but I don't think searches work between profiles -- maybe having at least "read-only" access to other profiles would be enough in my case.  That would let me at least find things easier, and switch to the right profile if necessary.
