### ISSUE TITLE
Cannot Start Joplin Server from Arch Package

### ISSUE THREAD

**Issue by alfredopalhares** [laurent22/joplin#3548]
Hello,

I am the maintainer for the Joplin package for Arch Linux, and i am trying from the terminal app, and I get the following error:

```
> server start
Cannot find module 'electron'
Require stack:
- /usr/share/joplin-cli/lib/services/ExternalEditWatcher.js
- /usr/share/joplin-cli/lib/services/rest/actionApi.desktop.js
- /usr/share/joplin-cli/lib/ClipperServer.js
- /usr/share/joplin-cli/command-server.js
- /usr/share/joplin-cli/app.js
- /usr/share/joplin-cli/main.js
```

Its missing a dependency (it seems), but I do install everything on `package.json` like on the [PKGBUILD](https://github.com/alfredopalhares/arch-pkgbuilds/blob/master/joplin/PKGBUILD#L38).

Am I doing something wrong ?

**Comment by laurent22** [comment]
I will check but I think some file that's desktop-only is getting loaded in the CLI app, maybe via the API.

**Comment by laurent22** [comment]
By the way @alfredopalhares, it's probably not a good idea to build your package based on master. In general it's relatively stable but occasionally (like now) I might change something in desktop or mobile which might break something in CLI. I'm thinking about changing the git structure, maybe renaming "master" to "dev" to make that more obvious. In the meantime, if you can I'd suggest building the package based on tags - the CLI ones would be named `cli-v1.0.y` and desktop just `v1.0.y`

**Comment by alfredopalhares** [comment]
@laurent22 thank you for the response.

I am not building from master btw, I am building only from stable releases fetching the source from the releases page.

**Comment by laurent22** [comment]
> I am not building from master btw, I am building only from stable releases fetching the source from the releases page.

The GitHub releases are only for the desktop versions, so the CLI code might not be stable in these. For that, you would need to get the source from the tag I mentioned, or I guess from npm.
