### ISSUE TITLE
Undo can replace contents of a note with those of a previously opened one

### ISSUE THREAD

**Issue by 0xmohit** [laurent22/joplin#355]
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

Undo can replace contents of a note with those of a previously opened one

- Open a note, say foo
- Observe the contents of foo
- Switch to another note, say bar
- Press Ctrl+Z

The contents of the note bar are replaced by those of foo.

**Comment by cast-away** [comment]
same happened to me with the windows client
