### ISSUE TITLE
Cursor is offset from what it's doing

### ISSUE THREAD

**Issue by Frivolous2** [laurent22/joplin#3550]
The cursor doesn't "act" where it is, but a bit to the left of itself:
![Peek 2020-07-23 15-41](https://user-images.githubusercontent.com/57101103/88300222-24886e80-ccfb-11ea-93e5-29d666d0f8a8.gif)

## Environment

Joplin version: 
Joplin 1.0.227 (prod, linux)
Client ID: 919c928fceab49e89e38b3df18544466
Sync Version: 1
Profile Version: 30
Keychain Supported: No
Revision: 4913fdb (master)

Platform: Linux

OS specifics: Fedora 32; Joplin downloaded from the website using the cli command.

## Steps to reproduce
I don't know how it got to this, but:
1. Open any note.
2. Start typing.
3. New text will be offset from cursor, as well as any deletion. If you go on a new line, the cursor will progressively get more offset as you go on.

## Describe what you expected to happen
Normal text entry.

## Logfile
[-1595515110504.log](https://github.com/laurent22/joplin/files/4966693/-1595515110504.log)

**Comment by CalebJohn** [comment]
Hi @Frivolous2 It looks like you're using a non-monospace font with the markdown editor. This is only supported with the beta codemirror editor (which can be turned on under Options -> Note) and does not work with the default editor. We are in a period of transition and unfortunately the warning under the font setting isn't as stern as it used to be. 

You can either change your font to be monospaced, or switch to the beta editor.

Thank you for detailed report and including the screenshot, adding those details really does help us debug issue.
