### ISSUE TITLE
Cannot create a new sub-notebook (Proof)

### ISSUE THREAD

**Issue by d4rk-d4nph3** [laurent22/joplin#3555]
I again open this issue which was closed by commenting "Cannot replicate". 

## Problem

I cannot create a new-subnotebook. The option "New sub-notebook" is replaced by "New notebook". I have attached the screenshot before and after I had installed the update.

## Environment

Joplin version: 1.0.227
Platform: Mac
OS specifics: MacOS Catalina 10.15.5

# Steps to reproduce

1. Attempt to create a sub-notebook.

I have reverted back to 1.0.224 for now, which does not have this issue.

### Before

![image](https://user-images.githubusercontent.com/61026070/88404280-6560b000-cded-11ea-9066-94ade39d8d31.png)

### After

![image](https://user-images.githubusercontent.com/61026070/88404290-6b569100-cded-11ea-83da-8c9cbb05d7b9.png)

**Comment by laurent22** [comment]
duplicate
