### ISSUE TITLE
Desktop: macOS: Undo (CMD+Z) and Select All (CMD+A) shortcuts do not work. Instead, one has to use CTRL+Z and CTRL+A.

### ISSUE THREAD

**Issue by aism** [laurent22/joplin#3558]
Hello there,

## Environment

Joplin version: Joplin 1.0.227
Platform: macOS
OS specifics: 10.15.5 (19F101)

## Problem description

The Undo (CMD+Z) and Select All (CMD+A) keyboard shortcuts do not work. Instead, one has to use CTRL+Z and CTRL+A.
At the same time, the Copy (CMD+C) and Paste (CMD+V) shortcuts work just fine (however, the CTRL+C and CTRL+V work as well, which is rather uncommon for macOS).

Joplin is the only app in my system that I know to exhibit this behavior.

**Comment by laurent22** [comment]
Closed as duplicate
