### ISSUE TITLE
Move Note dropdown menu can be very narrow

### ISSUE THREAD

**Issue by narFnarF** [laurent22/joplin#3564]
On iOS, when attempting to move a note to a different Notebook from the Edit Note view, the dropdown menu can sometime be quite narrow, making it difficult to see the name of each notebooks.

## Environment

Joplin version: 10.0.50
Platform: iOS
OS specifics: 12.4.6

## Steps to reproduce

1. Create a new note or edit an existing one
2. Write something to make the "Undo" button appear
3. Write something again
4. Press the Undo button
5. (This should make both the Undo and Redo buttons visible)
6. Tap the Notebook dropdown menu (top middle) to start the process of moving the note to a different Notebook

Current result: The dropdown menu is very narrow, showing only the first ~12 characters of the name of each notebook.

![](https://i.imgur.com/3S6otI9.png)

## Describe what you expected to happen
The dropdown list uses the full width of the device to provide maximum visiblilty.

**Comment by Priyaraj17** [comment]
May I work on this issue?

**Comment by entrymaster** [comment]
@laurent22 I have started working on this.

**Comment by entrymaster** [comment]
![image](https://user-images.githubusercontent.com/55127997/158657888-a9a750e2-aa38-400a-9ec2-1b0f0c578189.png)
The dropdown is taking full width of its parent `titleComp` in `screen-header.js` which is correct. The problem is when undo and redo both buttons are active the space left for `titleComp` is less which is translated for dropdown too

**Comment by laurent22** [comment]
Don't forget to read the [pull request guidelines](https://joplinapp.org/gsoc2022/pull_request_guidelines/), in particular the part where it says to not `@mention` people.

**Comment by laurent22** [comment]
Reopened due to https://github.com/laurent22/joplin/pull/6306#issuecomment-1161575676
