### ISSUE TITLE
Editing attachments is unreliable? 02

### ISSUE THREAD

**Issue by p2635** [laurent22/joplin#3568]
## Environment

Joplin version: 1.0.227 
Platform: Linux
OS specifics: Kubuntu 20.04

## Steps to reproduce

Note: I am not using the sync feature so my notes are local only.

1. Create a blank spreadsheet (.ods) and attach it to a note
2. On the same note, edit the spreadsheet by clicking on the link in the Viewer (blue link on the right of the pic)
![image](https://user-images.githubusercontent.com/4522927/88544310-1abf7d80-d011-11ea-9aab-c93db5185a7a.png)

3. This opens it in LibreCalc 6.4.4.2 for me, make any kind of edits, save and close

## Describe what you expected to happen
When I checked the file after editing it on the same day, it did indeed keep all the changes.

However, the problem happened when I opened it after a day passed. It lost some of the changes for some reason.
See exercise log below:
![image](https://user-images.githubusercontent.com/4522927/88544025-b4d2f600-d010-11ea-82d4-31551a6b1467.png)

I definitely filled in the columns yesterday but they are all blank now with the exception of the dates. I'm not sure the root cause is actually waiting one day or whether there is something else going on here.

This has happened to me twice though so far, I think I need to keep the files separately because I am worried this will happen again.

## Logfile

Nothing seem unusual immediately after editing but here it is anyway.
[console.log](https://github.com/laurent22/joplin/files/4982137/console.log)

Related to #3407

**Comment by laurent22** [comment]
Could you try the latest pre-release? As I think it should be fixed in that one - https://github.com/laurent22/joplin/releases

**Comment by p2635** [comment]
HI @laurent22 , I don't really want to replace my current install in case it messes it up or something. I think I'll rather wait until the pre-release has been released. Is that ok?

**Comment by laurent22** [comment]
Yes sure

**Comment by p2635** [comment]
I did a basic test of filling fields with text and waiting a day, I did not lose my data so just confirming here.
