### ISSUE TITLE
Cancelling Notebook Creation not Possible

### ISSUE THREAD

**Issue by Tim-Erwin** [laurent22/joplin#3573]
## Environment

Joplin version: 1.0.333
Platform: Android
OS specifics: 9

## Steps to reproduce

1. Open side bar
2. Click "new notebook"
3. Try to cancel / go back via the top-left arrow or the phone's back button

**Expected**: go back
**Actual**: nothing happens, I have to restart the app in order to proceed

**Comment by laurent22** [comment]
Should be fixed in latest release.
