### ISSUE TITLE
Apache WebDav sync issue: Joplin only supports BASIC authentication type?

### ISSUE THREAD

**Issue by alanzhucn** [laurent22/joplin#3574]
Hi, 

I try to use Apache WebDav as WebDav server for joplin to sync notes.
It seems that Joplin does not suport Digest authentication type.
And after I switch to use BASIC authentication type, Joplin sync works.

If it is the limiation of Joplin, would you mind to add a short description?  So others don't need to waste time for it.

## Environment
Joplin version:  Joplin for android v1.0.333-32bit.apk and Joplin for Desktop 1.0.220 (prod, win32)
Platform:  Android, windows
OS specifics: N/A
Note: Apache version 2.4 packed in XAMPP 3.2.4 for windows.

## Steps to reproduce

1.  configure the apache webdav to use Digest authencation type.
I omit the detail steps as I cannot describle the conf in a few sentense.

2.  verify apache webdav via a webdav client, for example bitkinex.
     connect the webdav, create a file then delete it.
     Note: windows explorer is fine, but bitkinex could show the log (HTTP headers)
3.  configure the Joplin (ether android, or win)  and try to check sync status. Joplin reports 401 error code.
    check the error.log of apache, found folllowing line:
```
[Sun Jul 26 22:36:02.238775 2020] [auth_digest:error] [pid 10036:tid 1648] [client 192.168.188.98:16166] 
AH01781: client used wrong authentication scheme `Basic': /mydav/

```
4. re-configure apache webdav to use BASIC authencation type.
5.repeat step 2-3 and Joplin works with BASIC authencation type.

## Describe what you expected to happen
If it is the limiation of Joplin, would you mind to add a short description?  So others don't need to waste time for it.

## Logfile

```
[Sun Jul 26 22:36:02.238775 2020] [auth_digest:error] [pid 10036:tid 1648] [client 192.168.188.98:16166] 
AH01781: client used wrong authentication scheme `Basic': /mydav/

```

**Comment by maltokyo** [comment]
I have this issue too

**Comment by rikmeijer** [comment]
I also have this issue using sabre/dav with a SQL backend

**Comment by driftregion** [comment]
FWIW, the [apache docs for `mod_auth_digest`](https://httpd.apache.org/docs/2.4/mod/mod_auth_digest.html) recommend using basic auth + SSL instead of digest auth.

> This module implements HTTP Digest Authentication (RFC2617), and provides an alternative to mod_auth_basic where the password is not transmitted as cleartext. However, this does not lead to a significant security advantage over basic authentication. On the other hand, the password storage on the server is much less secure with digest authentication than with basic authentication. Therefore, using basic auth and encrypting the whole connection using mod_ssl is a much better alternative.
