### ISSUE TITLE
when i create, how would i set the new note in the top of list

### ISSUE THREAD

**Issue by luguohong** [laurent22/joplin#3576]
when i create, how would i set the new note in the top of list

mac

![image](https://user-images.githubusercontent.com/17562682/88752386-5c286800-d18c-11ea-80c4-adad338d61df.png)

**Comment by CalebJohn** [comment]
Hi @luguohong the github issue tracker is only for tracking actual issues with Joplin. For support please ask on the [joplin forum](https://discourse.joplinapp.org/). This helps us properly track issues vs support.

I don't understand your question, so when you ask again on the forum please add more details.

**Comment by luguohong** [comment]
thx！
