### ISSUE TITLE
[Import] When importing Markdown Enex file, empty lines are lost

### ISSUE THREAD

**Issue by PhiLhoSoft** [laurent22/joplin#3578]
When I import a Enex file in Markdown format, generated with the https://github.com/rpgd60/simplenote2enex/ script, the empty lines, corresponding to a CR LF CR LF sequence, are lost.

Example, in Simplenote:

![image](https://user-images.githubusercontent.com/1087902/88805832-f0f08d00-d1af-11ea-92c0-97328a61d383.png)

Generated Enex file (after some fixes on my side):

![image](https://user-images.githubusercontent.com/1087902/88805936-0d8cc500-d1b0-11ea-99c2-f057bf92fd4a.png)

Resulting import in Joplin:

![image](https://user-images.githubusercontent.com/1087902/88806025-2ac19380-d1b0-11ea-8802-8317605ea5dc.png)

Notice the lack of empty line between the first line and the sub-title. Other empty lines in the note are missing as well.

## Environment

Joplin version: Joplin 1.0.227 (prod, win32)
Platform: Windows
OS specifics: Windows 10, 64-bit

## Steps to reproduce

1. Export a Simplenote file.
2. Convert it with simplenote2enex
3. Import it in Joplin

## Describe what you expected to happen

I expect that when importing Markdown from an Enex file, consecutive end-of-line are not collapsed into one.
Or, perhaps, provide a workaround?
[EDIT] Found one: `content.replace('\r\n\r\n', '\r\n<br>\r\n')` but it shouldn't be necessary, IMHO.

**Comment by laurent22** [comment]
We don't support Markdown ENEX files as this is not an official format. If you want to import an ENEX file, it needs to be in ENEX (XML) format. If you want to import Markdown it needs to be a .md file.
