### ISSUE TITLE
Hyperlinks with `$` can get completely messed up.

### ISSUE THREAD

**Issue by deftdawg** [laurent22/joplin#3583]
I was attempting to hyperlink a couple prices on Amazon within a Table Cell and my first link gets totally messed up....  It only works if I manually add a `\` in front of it.   

The image shows what is happening:

![image](https://user-images.githubusercontent.com/4991612/89005762-407ba980-d2d3-11ea-982f-b26690508f06.png)

Here is the markdown for testing:
```
### Two lines in a Table Cell

[$625 + Tax](https://www.amazon.ca/Artillery-Sidewinder-Pre-Assembled-300x300x400-Ultra-Quiet/dp/B07ZCXTYDK)<br><br>[$617 + Tax](https://www.amazon.ca/Artillery-Sidewinder-SW-X1-Printer-Version/dp/B07QKJMJKG)

### Replace with Space

[$625 + Tax](https://www.amazon.ca/Artillery-Sidewinder-Pre-Assembled-300x300x400-Ultra-Quiet/dp/B07ZCXTYDK) [$617 + Tax](https://www.amazon.ca/Artillery-Sidewinder-SW-X1-Printer-Version/dp/B07QKJMJKG)

### New Line

[$625 + Tax](https://www.amazon.ca/Artillery-Sidewinder-Pre-Assembled-300x300x400-Ultra-Quiet/dp/B07ZCXTYDK) 
[$617 + Tax](https://www.amazon.ca/Artillery-Sidewinder-SW-X1-Printer-Version/dp/B07QKJMJKG)

### Two New Lines Between (Good / Expected)

[$625 + Tax](https://www.amazon.ca/Artillery-Sidewinder-Pre-Assembled-300x300x400-Ultra-Quiet/dp/B07ZCXTYDK) 

[$617 + Tax](https://www.amazon.ca/Artillery-Sidewinder-SW-X1-Printer-Version/dp/B07QKJMJKG)

### Work Around: Two lines in a Table Cell (put a \ in front of the first link title)

[\$625 + Tax](https://www.amazon.ca/Artillery-Sidewinder-Pre-Assembled-300x300x400-Ultra-Quiet/dp/B07ZCXTYDK)<br><br>[$617 + Tax](https://www.amazon.ca/Artillery-Sidewinder-SW-X1-Printer-Version/dp/B07QKJMJKG)
```

## Environment
Joplin 1.0.232 (prod, darwin)

Client ID: 6f19d2068d784848aa561b4780922135
Sync Version: 1
Profile Version: 32
Keychain Supported: Yes

Revision: 729c8c6 (master)

**Comment by laurent22** [comment]
This line is actually parsed as katex code:

```
[$625 + Tax](https://www.amazon.ca/...)<br><br>[$617 + Tax](https://www.amazon.ca/....)
```

because it starts and ends with "$". I don't think that can be fixed in Joplin but you have several options on your end:

- Add a `\` before the "$"
- Or add a new line between each link
- Or disable math expressions (in the plugin options)
