### ISSUE TITLE
Add/remove tags to multiple notes

### ISSUE THREAD

**Issue by benallan** [laurent22/joplin#359]
Is there any way to add or remove tags from multiple notes at the same time? I tried selecting multiple notes then using the right-click menu, but "Add or remove tags" was greyed out and unavailable. 

If it's currently unsupported I think this would be a really useful feature to add in future. To give a bit more detail about why I need to use it: I'm in the process of importing notes originally made in onenote through a slightly convoluted route of onenote -> evernote -> joplin. The original note structure from onenote had an extra layer of heirarchy below notebooks (called "sections" in onenote) which Evernote converts to simple tags. So instead of a section called "todo this week", all the notes from that section will be tagged "todo this week". Because of this, I quite often need to select all the notes with a certain tag and either re-tag them or move them somewhere else. 

### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [ ] Terminal

**Comment by foxmask** [comment]
+1 on mobile / android

**Comment by foxmask** [comment]
I come back on that, because I'm in a state where tag on my mobile are not dropped but are on desktop.
In the status of joplin desktop I can see some resources not sync because not here (?!) but I dont see this tag on desktop at all. So I really like to see this on mobile :)

**Comment by mighelch** [comment]
Editing one tag at a time is a bum. Definitely need multiple tag handler.

**Comment by i-need-to-tell-you-something** [comment]
On Evernote, in addition to the context menu, this is also available in the right hand display panel when you have multiple selected notes. Joplin also has this panel, so my point is, "Add tags" should also be an option from that place in GUI.

**Comment by desk7** [comment]
I hope that feature will be implemented!

**Comment by christianlupus** [comment]
Please also add support for the Linux version... Thanks

**Comment by cast-away** [comment]
not stale

**Comment by benmca** [comment]
one more vote for this

**Comment by steveardis** [comment]
I was able to do this by selecting multiple notes and then dragging them over on top of the tag name on the sidebar.

**Comment by christianlupus** [comment]
This seems to work. I was not aware of this UI "trick" to **add** tags.

However, you cannot batch-remove them. I tried removing the note when in the tag filter (clicking left on the tag name) but this removed the note completely.

**Comment by mic704b** [comment]
@laurent22 would you be open to a PR (desktop) for `add or remove tags` to multiple notes?

With the spec being:

When multiple notes are selected and `add or remove tags` is actioned
- the common tags are presented,
- changes are applied to each selected note

When one note is selected and `add or remove tags` is actioned:
- behaviour is unchanged from current

**Comment by laurent22** [comment]
@mic704b, yes that makes sense, I would accept a PR with this spec.
