### ISSUE TITLE
ISO 8601 dates

### ISSUE THREAD

**Issue by jtagcat** [laurent22/joplin#3592]
[![xkcd: iso 8601](https://imgs.xkcd.com/comics/iso_8601.png )](https://xkcd.com/1179/)

I might potentially do it tomorrow or in 3 months.

**Comment by CalebJohn** [comment]
Hi @jtagcat ISO 8601 dates are already support in Joplin, what are you looking to add?

![image](https://user-images.githubusercontent.com/2179547/89253377-b769b880-d5d9-11ea-8932-99fa9be3ab17.png)

**Comment by jtagcat** [comment]
Questioning the world

I looked at it, three times. Very confused at myself.
