### ISSUE TITLE
Failed to export pdf on Windows 10

### ISSUE THREAD

**Issue by Downtime111** [laurent22/joplin#3594]
## Environment

Joplin version: 1.0.233
Platform: Windows
OS specifics: 10

## Steps to reproduce

1. When exporting pdf every time

## Describe what you expected to happen
When I was about to export the pdf, there was no response. I tried several times and it didn't work. So I uninstalled Joplin and installed it again, but it still didn't work. What's wrong?

## Logfile

C:\Program Files\Joplin\resources\app.asar\lib\services\CommandService.js:142 CommandService::execute: exportPdf {noteIds: Array(1)}noteIds: Array(1)0: "ea9e8a4f005d4031b68c21deeda7068f"length: 1__proto__: Array(0)length: 0constructor: ƒ Array()concat: ƒ concat()copyWithin: ƒ copyWithin()fill: ƒ fill()find: ƒ find()findIndex: ƒ findIndex()lastIndexOf: ƒ lastIndexOf()pop: ƒ pop()push: ƒ push()reverse: ƒ reverse()shift: ƒ shift()unshift: ƒ unshift()slice: ƒ slice()sort: ƒ sort()splice: ƒ splice()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()entries: ƒ entries()values: ƒ values()forEach: ƒ forEach()filter: ƒ filter()flat: ƒ flat()flatMap: ƒ flatMap()map: ƒ map()every: ƒ every()some: ƒ some()reduce: ƒ reduce()reduceRight: ƒ reduceRight()toLocaleString: ƒ toLocaleString()toString: ƒ toString()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}__proto__: Object__proto__: Object
C:\Program Files\Joplin\resources\app.asar\InteropServiceHelper.js:29 Export HTML result:  {warnings: Array(0)}warnings: []__proto__: Object
C:\Program Files\Joplin\resources\app.asar\lib\services\CommandService.js:142 CommandService::execute: exportPdf {noteIds: Array(1)}
C:\Program Files\Joplin\resources\app.asar\gui\MainScreen\MainScreen.min.js:147 Printing C:\Users\25114\Desktop\whatshouldtodo.pdf to pdf disallowed, already printing.

**Comment by laurent22** [comment]
I cannot replicate this and it looks like some hardware problem. If it happens again please open a new issue and perhaps provide a JEX file with the note that's causing issue.

**Comment by Ethnical** [comment]
Hello there, 
I have the exact same issue 
![image](https://user-images.githubusercontent.com/23560242/133245416-aaf956d0-bf16-4594-bebf-6b1de91740c2.png)
if someone has an idea?

**Comment by gdnzz** [comment]
Guys, I found the solution. Go to windows features, and check the microsoft print as pdf option. @Ethnical @laurent22 @Downtime111
