### ISSUE TITLE
Change "Sort by Title" to work numerically as well as alphabetically

### ISSUE THREAD

**Issue by itpropaul** [laurent22/joplin#3595]
It would be nice for notes that are titled as 1.1.4, 1.2, 1.10, etc, to have 1.10 be greater than 1.2 for example.

![image](https://user-images.githubusercontent.com/30813009/89293081-579bfd80-d62b-11ea-8719-7d4dd033d207.png)

**Comment by kingebere** [comment]
Please can you reproduce the issue using screenshots or videos to illustrate better

**Comment by itpropaul** [comment]
I did include a screenshot.

My recommended alphanumerical sorting  mechanism would look like:
1.1
1.2
1.3
1.4
1.5
1.6
1.7
1.8
1.9
1.10
1.11

But instead it looks like:
![image](https://user-images.githubusercontent.com/30813009/89410297-76fd5e00-d6f1-11ea-904e-20ffa44ca42c.png)
or in text format again:
1.1
1.10
1.11
1.2
1.3
1.4
1.5
1.6
1.7
1.8
1.9

**Comment by hqh0803** [comment]
I have the same problem with Joplin 1.5.7
