### ISSUE TITLE
Bug: Android App not starting on Samsung S8+

### ISSUE THREAD

**Issue by ChristianAEDev** [laurent22/joplin#360]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

The App is not starting on my Samsung S8+.
The screen just stays white. Waiting for several minutes. This also prevents me from accessing the options to access the logs.
Is there any other way I can access the logs or provide more details on the issue?

Here how it looks:
![screenshot_20180401-142834_joplin](https://user-images.githubusercontent.com/10501258/38173617-61556d94-35b9-11e8-995c-e17a5a97d250.jpg)

**Comment by laurent22** [comment]
Hello, is it on a fresh install of the app? Do you have any way to connect your phone to a PC and use `adb logcat` to check the log?

**Comment by ChristianAEDev** [comment]
@laurent22 Thank you for getting back to me.

It is a fresh install on a "new" device. (The device has been reset to the factory settings.) It is the first time the app is installed on this device.

There is a lot of logs produced. What stuck out is the following error. If this is not enough: Could you provide a filter (regex?) to limit it to relevant messages?
```
04-03 14:31:48.623 18963-18997/? E/ReactNativeJS: Error: Theme not set
    
    This error is located at:
        in s
        in Connect(s)
        in RCTView
        in t
        in i
        in RCTView
        in RCTView
        in t
        in Connect(t)
        in t
        in Connect(t)
        in t
        in t
        in RCTView
        in RCTView
        in t
04-03 14:31:48.632 18963-18998/? E/unknown:ReactNative: Error: Theme not set
    
    This error is located at:
        in s
        in Connect(s)
        in RCTView
        in t
        in i
        in RCTView
        in RCTView
        in t
        in Connect(t)
        in t
        in Connect(t)
        in t
        in t
        in RCTView
        in RCTView
        in t, stack:
    t@652:371
    value@862:4466
    f@44:14370
    c@44:14240
    T@44:17029
    l@45:81
    d@45:641
    h@45:1584
    T@45:4353
    P@45:3717
    enqueueSetState@44:12480
    setState@52:3007
    handleChange@372:5008
    c@376:730
    <unknown>@304:5120
    n@76:245
    <unknown>@76:1662
    <unknown>@76:427
    n@76:245
    r@76:502
    <unknown>@76:1232
    f@74:183
    d@74:1609
    c@74:465
    n@76:1216
    e@76:1268
    <unknown>@76:427
    async@76:3319
    <unknown>@304:4944
    <unknown>@304:9199
    n@76:245
    <unknown>@76:1662
    <unknown>@76:427
    n@76:245
    r@76:502
    <unknown>@76:619
    u@74:133
    <unknown>@74:921
    <unknown>@24:1784
    o@24:571
    u@24:880
    callImmediates@24:3178
    value@19:2598
    <unknown>@19:790
    value@19:2426
    flushedQueue@19:760
    invokeCallbackAndReturnFlushedQueue@19:718
```

**Comment by laurent22** [comment]
Thanks the "theme not set" error is quite clear but it's strange it happens so early. I'll see if I can replicate it here.

**Comment by ChristianAEDev** [comment]
@laurent22 can you say, when a new release will be published to the Play Store?

**Comment by ChristianAEDev** [comment]
After the last release it is working now. Thank you.
