### ISSUE TITLE
Codemirror vim cancel search selection

### ISSUE THREAD

**Issue by TonyZTYang** [laurent22/joplin#3604]
When using vim mode in codemirror, the selected search result (when searching with _**/**_) can't be dismissed conveniently.

## Environment

Joplin version: Joplin 1.0.233 (prod, darwin)
Platform: macOS
OS specifics: macOS catalina 10.15.5 (19F101)

## Steps to reproduce

1. Open Joplin.
2. Set keyboard mode to vim, set editor to codemirror.
3. Open any note in editor view and focus on the note body (in vim command mode)
4. Search for an existing pattern in the note with _**/**_
<img width="500" alt="Screen Shot 2020-08-06 at 6 04 37 PM" src="https://user-images.githubusercontent.com/60953182/89519674-53303a00-d80f-11ea-87da-32a0d2d75da0.png">

## Describe what you expected to happen
To dismiss such search selection in ace editor you can simple type _**/**_ again and hit enter.
That doesn't seem to be working in codemirror editor. A workaround is to use `:noh`.

## Logfile

No extra logs were generated when recreating this issue but there is a long list of warnings generated when loading the app.
[warning.txt](https://github.com/laurent22/joplin/files/5034210/warning.txt)

**Comment by laurent22** [comment]
It seems to be working as designed, as that's how the demo works too: https://codemirror.net/demo/vim.html

In general we can only support whatever CodeMirror supports so maybe something to be reported upstream.

**Comment by TonyZTYang** [comment]
Ahh I see, thanks for the feedback
