### ISSUE TITLE
Multiline editing shortcut causes conflicts

### ISSUE THREAD

**Issue by mbuc** [laurent22/joplin#3605]
## Environment (where steps occurred)

Joplin version: 1.0.232 729c8c6f (master)
Platform: Windows 10
OS specifics: Version 1909 Build 18363.959

### Android version (where second conflict occurred)
Joplin version: 1.0.329
Platform: Android 7.0 
OS specifics: Build NRD90M

## Steps to reproduce

1. Used keyboard shortcut `Alt + Shift + up/down arrow`.  Expected result: multiline (column) selection.  Actual result: The line above/below the cursor was duplicated.
2. Used keyboard shortcut `Alt + Shift + right arrow`.
3. Suddenly I had conflicts on both devices.  I had one note with a conflict on Android, and a different note with a conflict on Windows.

## Describe what you expected to happen

I expected multiline editing to work, as it worked perfectly when I used it yesterday.  Instead, I got duplicate lines and conflicting notes.

## Logfile

Will upload a log if requested, but I keep a lot of personal information in Joplin.

**Comment by mbuc** [comment]
I just realized that the conflict on the Android side is an old version of a note that I've been updating continuously - it's several versions behind, actually.

A few minutes ago everything was synced perfectly.  As soon as I hit `Alt + Shift + right arrow`, I got a conflict for one note on the desktop, and immediately had a conflict for the older version of a different note on Android.

**Comment by mbuc** [comment]
How can I export a debug log from the desktop application?  I was able to export one on Android but can't find it on the desktop.

**Comment by mbuc** [comment]
[joplin_desktop_2020.08.06.txt](https://github.com/laurent22/joplin/files/5037287/joplin_desktop_2020.08.06.txt)
[joplin_desktop_database_2020.08.06.txt](https://github.com/laurent22/joplin/files/5037289/joplin_desktop_database_2020.08.06.txt)

Attached are the logs from Joplin on Windows 10.  They have been reduced to the log activity from today and anonymized - let me know if you need more, though.  I'll upload the logs from the Android client in a separate comment.

**Comment by mbuc** [comment]
[android_syncReport-1596736919787.txt](https://github.com/laurent22/joplin/files/5037496/android_syncReport-1596736919787.txt)

Attached is the log for the Android client.

I was able to resolve the conflicts - but it was odd that multiline editing worked yesterday but didn't today.  And odd that the conflicts occurred right as I used those keyboard shortcuts.  Let me know if you'd like any more info.

**Comment by CalebJohn** [comment]
It looks like you used the wrong keys, Joplin uses the ace editor for the code editor (for now) and according to the [documentation](https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts) Alt+shift+up/down are copy line up/down.
This has been a problem with joplin for awhile (not having explicitly states key bindings in the editor). So going forward we will soon only support a [limited set of key bindings](https://github.com/laurent22/joplin/blob/dev/ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx#L137) The long term plan is to add plugins which will have support for extended functionality.

For I more powerful editing experience I would suggest using sublime text or vscode with the joplin external editor. Both of these will always have a better editor than joplin is capable of.

Is it alright if we close this?
