### ISSUE TITLE
iOS Bug: iPhone 11 - last line of text hidden, unable to scroll down to see

### ISSUE THREAD

**Issue by siliconninja** [laurent22/joplin#3607]
This was introduced in issue #1437 already, but it still happens on the iPhone 11 with iOS 13.6. It is fixed on my iPad Air 2 with iOS 13.6, though.

When creating or editing a note, I cannot edit the last line unless I manually position my cursor at the end.
I cannot view the last line until I add another new line, line, which is one of the fixes described in #1437.

## Environment

Joplin version: 10.0.52
Platform: iOS
OS specifics: iPhone 11, iOS 13.6

## Steps to reproduce

1. Create or edit a note.
2. Type a bunch of lines of text.
3. Eventually, when the whole screen is filled with text, the last line of text on the note will go behind the keyboard.

Even if I scroll down to the bottom, I cannot scroll any further to see the last line of text until I add another new line.

Disabling "Predictive Text" on the iOS keyboard does not fix this issue.

## Describe what you expected to happen
I am able to see the last line of text without having to enter a new line at the end of the note.

### Bug on iPhone 11
With predictive text:
![298155C1-BDA5-4B58-B8CC-7F55B37B94A1](https://user-images.githubusercontent.com/29907828/89597509-613e8480-d828-11ea-868d-110b1ceb4634.jpeg)

Without predictive text:
![B793CF57-2966-4522-AC64-9DBD6FCDB13E](https://user-images.githubusercontent.com/29907828/89597518-6996bf80-d828-11ea-8e99-9c8dc4acf9d5.jpeg)

### Working fine on iPad Air 2

With predictive text:
![B21F1560-6A03-4C06-ADE8-3D9688EB3C69](https://user-images.githubusercontent.com/29907828/89597698-d5792800-d828-11ea-8450-00eb546a2c74.jpeg)

Without predictive text:
![37F53081-25C0-4E39-8698-606EC40674CA](https://user-images.githubusercontent.com/29907828/89597771-05283000-d829-11ea-874e-947db73c4d63.jpeg)

**Comment by siliconninja** [comment]
This issue still requires attention. I have not seen any commits on the repo that directly fix this issue, and I haven't seen any updates to the iOS Joplin app that I can test.

**Comment by siliconninja** [comment]
The bug still exists in version 10.0.53.
![3408A0C7-7AF1-4A45-832C-EBB4D40B5233](https://user-images.githubusercontent.com/29907828/92327222-1e89eb00-f026-11ea-8ae4-e25389ce4fcc.png)

**Comment by siliconninja** [comment]
Yes, the issue still exists on Joplin 10.1.0 and iOS 13.7.

**Comment by siliconninja** [comment]
Yes, the issue still exists on Joplin 10.3.1 and iOS 14.2. This issue seems to be related to #4021 now.

**Comment by siliconninja** [comment]
Issue still exists on Joplin 10.4.1 and iOS 14.2.

**Comment by siliconninja** [comment]
Issue still exists on Joplin 10.5.1 and iOS 14.3.

**Comment by siliconninja** [comment]
Issue still exists on Joplin 10.6.2 and iOS 14.3.

**Comment by siliconninja** [comment]
Still relevant.

**Comment by cjdaniel** [comment]
I see this issue too. My workaround for now is to add a couple blank lines at the bottom of anything I'm typing in Joplin on my phone.

**Comment by siliconninja** [comment]
@cjdaniel Yeah, I've been using that workaround for a long time. It's still very annoying though, because I have to remember to do it. After doing some research, I wonder if there's a way to use custom CSS that would fix this issue?

**Comment by siliconninja** [comment]
Still relevant.

**Comment by innkuika** [comment]
I've reproduced your bug, will work on it 😉
