### ISSUE TITLE
Seperate note sort setting for each notebook

### ISSUE THREAD

**Issue by electricar** [laurent22/joplin#3608]
Hi,
is it possible to change the sort order for the notes seperately for each notebook?
E.g. sort the notes in notebook1 by title and in notebook2 by the updated date?
Thank you in advance.
Cheers

**Comment by jlnbdt** [comment]
I think it’s a very good idea :+1: 
Notebooks can be of different types. For example, cooking recipes could be arranged alphabetically in one notebook, and meeting notes by date in another notebook.

**Comment by electricar** [comment]
It's open, still no answer. Perhaps this is a suggestion rather than an issue?

**Comment by Sergih28** [comment]
+1 To this request!
Without this feature, I can't find a way to sort my notes in a good way for every notebook.
In my case, the Inbox notebook requires creation order, Diary notebook reverse sort (for dates), and the others alphabetically pretty much.
This sorting types already exist, just need to be able to chose one for each notebook.
