### ISSUE TITLE
Improvement of the tag function

### ISSUE THREAD

**Issue by electricar** [laurent22/joplin#3609]
Hi,
I am missing some features from the tags and found one post which summarizes everything I could ask for:
https://discourse.joplinapp.org/t/practical-use-of-tags/3379/23

Here are my main requests:
- Suggestion of tag operations:
        tags:tag1,tag2,tag3: presents results for notes with all those tags at same time
        tags:tag1,+tag2,+tag3: presents results for all notes with one of the tags
        tags:tag1,-tag2,tag3: presents all notes with tag1 AND tag3, except to the ones tagged also with tag2.
        tags:tag1,-tag2,+tag3: presents all notes with tag1 OR tag3, except to the ones tagged also with tag2.
- Exact matches are mandatory for tags search. tags:"this is" and tags:"this is not" should not return fuzzy results

Cheers

**Comment by electricar** [comment]
Hi this "issue" is still open and should be seen as an idea for future releases.

**Comment by salman-q** [comment]
After fumbling with Joplin for a few minutes, coming onto GitHub to find some help. Finding nothing. Then searching for open requests only to find this gem of feature hidden under "stale" tag. Why isn't this already a feature? At least let us search multiple tags if more advanced functionality as OP mentioned isn't feasible. Isn't that the whole point of tags? To filter content?
