### ISSUE TITLE
FR: Desktop - Move selected line up/down with keyboard shortcut (Ctrl+Shift+ Up/Down)

### ISSUE THREAD

**Issue by RCJacH** [laurent22/joplin#361]
### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

This is a feature from sublime text, where you use a shortcut to move selected lines up or down in relation to other lines. It's a great way to organize existing notes without endless copy/pasting.
Currently I have to copy everything to an empty file in sublime text, move passages, and then copy back to Joplin. It would be nice to be able to do so directly in Joplin.

**Comment by GROwen** [comment]
@RCJacH I'm using the macOS version (1.0.83) and can use `option + up/down arrow` in the editor. I'd love to know what all the keyboard shortcuts are, especially for how to duplicate a line (that'd save me heaps of time when creating tables).

@laurent22 if you point me to where these are getting set I could write up a doc for them.

**Comment by RCJacH** [comment]
@GROwen Thank you for pointing that out. It's Alt + up/down arrow in windows.
It would be great to have a complete list of key shortcuts available.
