### ISSUE TITLE
Single dollar sign ($) breaks Codemirror highlighting

### ISSUE THREAD

**Issue by wjbuys** [laurent22/joplin#3610]
## Environment

Joplin version: 1.0.233, using CodeMirror editor.
Platform: Windows 10
OS specifics: 64 bit

## Steps to reproduce

1. Make a new note with Codemirror as the editor. I don't even have math expressions enabled in the preferences.
2. Type the following:
   ```md
   # Test
   The thing costs $10. That's pretty cheap.
   
   # Broken
   Now all of my *highlighting* is _broken_. :'(
   ```
3. Observe the sadness: 
    ![sadness](https://user-images.githubusercontent.com/31602/89672615-cf6f5f80-d899-11ea-9a7b-512be9155c2f.png)

## Describe what you expected to happen
I expected CodeMirror to ignore the $, and keep highlighting the rest of my note.

## Logfile
I didn't find anything relevant in the logs.

**Comment by CalebJohn** [comment]
Thanks for the bug report @wjbuys ! This was already fixed in #3582 and will be available in the next release.
