### ISSUE TITLE
Codemirror macos cmd-z not undoing

### ISSUE THREAD

**Issue by TonyZTYang** [laurent22/joplin#3612]
When using codemirror as default editor on macos, cmd-z doesn't undo the previous action but ctrl-z does.

## Environment

Joplin version: Joplin 1.0.233 (prod, darwin)
Platform: macOS
OS specifics: macOS catalina 10.15.5 (19F101)

## Steps to reproduce

1. Open Joplin.
2. Set editor to codemirror.
3. Make modification to any note.
4. Press "command + z"

## Describe what you expected to happen

Cmd-z is supposed to undo the last action just like in the ace editor. Yet in code mirror it seems that only ctrl-z works and cmd-z does nothing.

I did manage to find [codemirror user manual](https://codemirror.net/doc/manual.html#keymaps) but according to the manual this should work.

## Logfile

No extra logs were generated when recreating this issue but there is a long list of warnings in console when loading the app.
[warning.txt](https://github.com/laurent22/joplin/files/5044732/warning.txt)

**Comment by CalebJohn** [comment]
Hi @TonyZTYang thanks for the report, this has already been reported and fixed and will be available in the next release
https://github.com/laurent22/joplin/issues/3499
