### ISSUE TITLE
remote markdown images not download

### ISSUE THREAD

**Issue by godamos** [laurent22/joplin#3613]
if i want to clip selection on normal notes . the remote images is downloaded but
if  i want to clip selection on markdown note , the remote images is not be downloaded

**Comment by ylc395** [comment]
Every note in Joplin is a markdown note, so what is so-called "normal notes"?

**Comment by godamos** [comment]
> Every note in Joplin is a markdown note, so what is so-called "normal notes"?

不是markdown的文章，用webclip复制下来图片会自动下载图片，markdown的就不会下载，而是直接调用远程图片

**Comment by ylc395** [comment]
> > Every note in Joplin is a markdown note, so what is so-called "normal notes"?
> 
> 网页上的不是markdown的文章，用webclip复制下来图片会自动下载图片，markdown的就不会下载，而是直接调用远程图片

网页不都是 HTML 么？markdown 网页是啥意思...能给个示例网页么？

**Comment by godamos** [comment]
> > > Every note in Joplin is a markdown note, so what is so-called "normal notes"?
> > 
> > 
> > 网页上的不是markdown的文章，用webclip复制下来图片会自动下载图片，markdown的就不会下载，而是直接调用远程图片
> 
> 网页不都是 HTML 么？markdown 网页是啥意思...能给个示例网页么？

就是说你普通网页上复制下来的内容，图片会自动下载，而网页是markdown写出来的，图片就不会下载，而是调用原图片链接，比如你从github上任意一个带图片的readme，用webclip复制下来，图片引用还是giyhub上的图片链接，并不会下载到本地

我现在就是想把github上的readme和图片都下载到本地，不知道就是这样设计的还是个bug，

**Comment by ylc395** [comment]
> 如你从github上任意一个带图片的readme，用webclip复制下来，图片引用还是giyhub上的图片链接，并不会下载到本地

<img width="919" alt="图片" src="https://user-images.githubusercontent.com/12264626/90107501-7ad95200-dd7b-11ea-8959-e5cdbc0ac7df.png">

没有吧，我用 joplin 的 README 页面试了下，没啥问题

**Comment by godamos** [comment]
![image](https://user-images.githubusercontent.com/23711955/90182999-67fb6780-dde5-11ea-83a3-dc7028610d37.png)
我的就不下载

**Comment by godamos** [comment]
> > 如你从github上任意一个带图片的readme，用webclip复制下来，图片引用还是giyhub上的图片链接，并不会下载到本地
> 
> <img alt="图片" width="919" src="https://user-images.githubusercontent.com/12264626/90107501-7ad95200-dd7b-11ea-8959-e5cdbc0ac7df.png">
> 
> 没有吧，我用 joplin 的 README 页面试了下，没啥问题

我用的最新版，webclip是chrome 默认配置
