### ISSUE TITLE
Filtering on first character is ignored on dropdown for adding tags (second starts filtering)

### ISSUE THREAD

**Issue by ambrt** [laurent22/joplin#3616]
Linux Desktop v 1.0.233

So basically the problem is that when menu for adding tags is opened 
and first letter is typed the **non filtered** dropdown list of all tags is opened.

Filtering happens only after second letter being typed.

I'm not sure if this is a bug or feature but i think that even typing first 
letter should show filtered list (filtered by that letter, ofc).

I'm opened for discussion.

**Comment by ambrt** [comment]
Ok, things go even weirder.

Filtering doesn't happen on letters from _a_ to _f_ but is working for all next letters in alphabet. (g to x)

**Comment by laurent22** [comment]
I cannot replicate this on v1.2. For me it starts filtering on first keypress.

**Comment by ambrt** [comment]
I still have it in 1.2.2, mind that i had db created in 1.0 (maybe that's a culprit)
![screen](https://user-images.githubusercontent.com/10456131/94702160-bb962600-033d-11eb-9896-98d92ea621b2.png)

**Comment by ambrt** [comment]
![joplin tags](https://user-images.githubusercontent.com/10456131/98957681-bd890280-2501-11eb-83b1-f90e1a0704cb.png)
I can reproduce it on fresh 1.4.7 (dev version, using AppImage).
