### ISSUE TITLE
Terminal app: 'Operation not permitted' when symlinking ~/.joplin-bin/bin/joplin 

### ISSUE THREAD

**Issue by jlarusso** [laurent22/joplin#3617]
When installing the terminal app, I could not symlink the joplin bin even with root permissions.  Could be due to:
https://support.apple.com/en-us/HT204899

Instead I symlinked into `/usr/local/bin` via `ln -s ~/.joplin-bin/bin/joplin /usr/local/bin/joplin`

Docs could be updated to account for this?

**Comment by jt196** [comment]
Tried an install today and the same issue - this was running in zsh/iterm on a modern Mac with the 2 line installation. I had to sudo the symlink command above.
