### ISSUE TITLE
Remove hyphens / list marks from multiple lines [feature request]

### ISSUE THREAD

**Issue by mireianievas** [laurent22/joplin#3619]
I am trying out your app. It looks pretty neat, but I was wondering if there is an option to remove list marks (the hyphens, * or []) from multiple lines at the same time (I found a way to add them by selecting them all together, but when I click to add those markers again they are appended to the previous ones instead of removed (I would have expected to get back the original unformatted text). I also tried pressing control, option or command in the mac before clicking the button but nothing happens.

**Comment by CalebJohn** [comment]
Hi @mireianievas 

Joplin has been experimenting with maybe switching to a [new editor](https://github.com/laurent22/joplin/issues/3560) which supports this behaviour. For now you can try it out by selecting the beta under Tools -> Options -> Note -> Use Codemirror.
In the current release it isn't yet 100% stable so I'd recommend waiting for the next one!

**Comment by CalebJohn** [comment]
Fixed when we switched editors.
