### ISSUE TITLE
[bug?] after the search,  autosave replaces the item displayed in the search with the selected display item

### ISSUE THREAD

**Issue by naototty** [laurent22/joplin#362]
### Operating system

- [o] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [o] Desktop
- [ ] Mobile
- [ ] Terminal

After searching, autosave replaces the item displayed in the search with the selected display item.
I do not debug.
However, I understood that my memorized data was broken.

I think that this phenomenon was reproduced several times.

**Comment by laurent22** [comment]
Thanks for the report. Are you able to replicate this consistently and, if so, what steps do you follow?

**Comment by laurent22** [comment]
Closed inactive issue. If the issue is still happening, please comment here with more information.
