### ISSUE TITLE
Can I customize the location of notes

### ISSUE THREAD

**Issue by lostblackknight** [laurent22/joplin#3623]
Can I customize the location of notes

**Comment by CalebJohn** [comment]
hi @lostblackknight github is just for tracking issues related to joplin any questions should be asked on the [forum](https://discourse.joplinapp.org/). But to answer your question, if you're on windows you can use the portable app to store your notes (and joplin) anywhere you like. And on other platforms you can use the [unsupported --profile flag](https://discourse.joplinapp.org/t/is-there-any-way-to-use-as-a-portable-app/35/3)

If you have any more questions please ask on the [forum](https://discourse.joplinapp.org/) or search the forum as questions like this have probably already been answered there.
