### ISSUE TITLE
Defective input of arrow symbol

### ISSUE THREAD

**Issue by ina6ra** [laurent22/joplin#3625]
If you enter a specific character, the input will be misaligned.
Confirmed with the following 4 symbols.
Often used as an arrow symbol in Japan.

|Symbol|Unicode|Sense|
|---|---|---|
|←|U+2190|Left Allow|
|↑|U+2191|Up Allow|
|→|U+2192|Right Allow|
|↓|U+2193|Down Allow|

## Environment

Joplin version: 1.0.233 (prod, win32)
Platform: Windows 10 Pro
OS specifics: 2004 19041.450

## Steps to reproduce

1. Show Viewer
2. Input Unicode Arrow
3. Input letter on the same line as the arrow

**Comment by CalebJohn** [comment]
I think this is the same as #3134, the issue being that the current code editor doesn't properly handle unicode. To address this we're working on a new code editor available as a toggle in settings. Would you mind giving it a try? It's under `Tools -> Options -> Note -> Use CodeMirror as the code editor (WARNING: BETA).`

**Comment by ina6ra** [comment]
Thanks!!
Solved by the proposed method.

**Comment by CalebJohn** [comment]
fixed by #3703. CodeMirror is now the default!
