### ISSUE TITLE
Scrolling breaks drag and drop reordering of notes

### ISSUE THREAD

**Issue by franekp** [laurent22/joplin#3628]
## Environment

Joplin version: 1.0.233
Platform: Linux
OS specifics: Debian 8

## Steps to reproduce
It seems farily common to have a notebook with more notes than can fit on one screen, such that the note list has a scrollbar. Let's say we have scrolled until the end of this list. When we try to drag and drop a note, it will be moved into the top of the list, sometimes even outside the currently visible area.

In the screenshot below, I have tried dragging a note titled "--- section header ---". You can see that the black bar indicating where it will be dropped is in a different position than the mouse.

![joplin_drag_and_drop_scroll_not_working](https://user-images.githubusercontent.com/9804230/90124769-393bad80-dd61-11ea-82ab-ba0bb1c0510e.png)

This is because current implementation seems to be using window coordinates to determine the target position (indicated by the black bar in the UI). I guess it should be simple to fix, something like changing [MouseEvent.pageY](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/pageY) to [MouseEvent.clientY](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientY). I didn't look into the source code though, so this is just my speculation based on how drag and drop is usually implemented.

**Comment by franekp** [comment]
A workaround for anyone else having this problem: you can zoom out, reorder your notes, and zoom back in.

**Comment by DarinDev1000** [comment]
I can work on this.
Does this also happen on any list besides the note list?

**Comment by DarinDev1000** [comment]
Currently, there is no offset for when the list is scrolled down.

**Comment by DarinDev1000** [comment]
Here is the [pull request](https://github.com/laurent22/joplin/pull/3651) for the ui_update branch.
