### ISSUE TITLE
Checkboxes not indented on Desktop version

### ISSUE THREAD

**Issue by despens** [laurent22/joplin#363]
Markdown like this

```markdown
- [ ] task a
  - [ ] sub task 1
  - [ ] sub task 2
- [ ] task b
  - [ ] sub task 1
  - [ ] sub task 2
```

renders without indents on Desktop:

![selection_00565](https://user-images.githubusercontent.com/571494/38190293-e3d532cc-3663-11e8-8565-e02c145c1e88.png)

It seems to work OK on Android.

### Operating system

- Linux

### Application

- Desktop

**Comment by ab-ti** [comment]
Hello, I believe the issue described by @despens still seems to exist on the desktop version as of 3/13/2019, or at least it is a issue persisting on my installation.  

# Technical Information
* Operating system: Windows 10
* Application: Desktop
* Joplin Version: 1.0.140 (prod, win32)
* Date updated: 3/13/2019

# Example:
## Markdown 
```
- [ ] task one
- [ ] task two
   - [ ] sub task two
- [ ] task three 
```

## Renders
- [ ] task one
- [ ] task two
- [ ] sub task two
- [ ] task three 

Please let me know if I am formatting incorrectly or there is an alternative way to do this. I would love indented / nested checkboxes!

**Comment by laurent22** [comment]
Should be fixed in next version ;)

**Comment by ab-ti** [comment]
@laurent22, looking forward to it, thank you!
