### ISSUE TITLE
outline view

### ISSUE THREAD

**Issue by zczhangchun** [laurent22/joplin#3630]
The forum is also the right place to submit a feature request so that it can be discussed by other users.
But I found the lack of an outline in reading mode very inconvenient, similar to wiznote.
![image](https://user-images.githubusercontent.com/42573478/90194767-920b5480-ddfa-11ea-8282-be6f2d52d4f3.png)

**Comment by CalebJohn** [comment]
Have you tried using the table of contents? It's under Tools -> Options -> Plugins -> Enable table of contents extension
