### ISSUE TITLE
After changing layout (toggle editor layout) there is lost focus in editor and you have to click inside to continue writing

### ISSUE THREAD

**Issue by theerror** [laurent22/joplin#3631]
After changing layout (toggle editor layout) there is lost focus in editor and you have to click inside to continue writing.

It's way annoying, when I need to take a look if my markdown is ok and after switching back to editor, I have to click to be able to write again. After switching, cursor is greyed. 

Could be related to #2810? 

Reproduce steps:
1) Open note and start editing
2) Switch to view layout (i'm using command+L) and then back to code view

Actual: Cursor is on position as previous, but greyed out and I can't type, until I change focus back to editor
Expected: I can continue write without any clicking into text area.  

MAC OS.

Joplin 1.0.233 (prod, darwin)

Client ID: 5fe9e037aacf4dd3b3206ed37b854cd4
Sync Version: 1
Profile Version: 32
Keychain Supported: Yes

Revision: e63eee8 (master)

**Comment by rs4231199** [comment]
It's very annoying to press `Shift+Ctrl+B` again and again, when it can and should be automated.

**Comment by CalebJohn** [comment]
For anyone following this issue, this fix was only implemented for the codemirror editor, because that one will become the default in the future (if it isn't already by the time this is in a release)
