### ISSUE TITLE
GitHub issue template: confusing use of checkboxes

### ISSUE THREAD

**Issue by despens** [laurent22/joplin#364]
The issue template uses checkboxes to select platforms and applications. When users report using the template, on GutHub it looks like the issues are already worked on.

GitHub issue display (5 of 8 tasks completed):

<table><tr><td>
<img src="https://user-images.githubusercontent.com/571494/38193067-5ce31060-3670-11e8-8d6a-670b50cc65ed.png">
</td></tr></table>

User submitted this issue (checked 2 operating systems and 5 applications):
<table><tr><td>
<img src="https://user-images.githubusercontent.com/571494/38193092-77e92458-3670-11e8-8931-007c75231880.png">
</td></tr></table>

Please change the template.

**Comment by laurent22** [comment]
Fixed
