### ISSUE TITLE
Synchronization mode switch results in note loss

### ISSUE THREAD

**Issue by DreamSaddle** [laurent22/joplin#3649]
## Environment

Joplin version: 1.0.201
Platform: win10
OS specifics: 

## Steps to reproduce

1. Switch synchronization type is nextcloud
2. Click on the sync button
3. synchronously complate
4. Then I lost all my notes from my previous file system, However, my synchronization record still exists, And my database also exists

## Describe what you expected to happen
How can I retrieve notes That I previously synchronized to the file system

**Comment by LeoK987** [comment]
My Mac app version is 1.0.233.  I am just having a very similar issue related to changing sync to nextcloud.

I switched sync from Dropbox to nextcloud which I just set up on a Ubuntu server.  Before syncing, I backed up Joplin to a jex file.  After the sync, I noticed the storage size on nextcloud is about the same size as the backup file: 600MB, but 2 folders out of 4 were deleted on the local Joplin app (and I believe they are not stored on nextcloud).  So I imported the jex file.  The 2 missing folders are now back, but the 2 existing folders are imported as redundant ones, so I removed the redundant folders.  I did a sync again.  Now it looks no files are missing, but the storage size on nextcloud is 1.2GB.  What is happening?
