### ISSUE TITLE
Cannot paste Dropbox auth code in on OS X Desktop

### ISSUE THREAD

**Issue by flyinggrizzly** [laurent22/joplin#365]
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

I've just switched from OneDrive to Dropbox for sync, and ran into an issue where I wasn't able to paste the API auth code from DB into the field in the sync setup screen.

After enabling debug mode, I also wasn't able to paste it into the `value` attribute on the input element.

It is also not possible to call up the context menu on the sync screen (right click has no effect).

This doesn't appear to be an OS issue, as paste works elsewhere. It also works in note bodies.

I was able to type the code in longhand, but it's tedious and error prone (especially when your auth code has the same character 8+ times consecutively...)

I run Joplin on Debian on another machine, and I'll be switching that to DB later today--will update with results on that.

**Comment by flyinggrizzly** [comment]
Also, sorry I haven't disabled sync and tried to pull more debug info for you. Now that it's syncing, I kind of need to keep cracking with my other work.

**Comment by laurent22** [comment]
There's no context menu in this dialog, but does Cmd+v work?

**Comment by flyinggrizzly** [comment]
Sorry, should have specified that was what I tried first before trying the context menu

**Comment by flyinggrizzly** [comment]
Also, it’s weird that it doesn’t even include the basic copy/paste options in a context menu

**Comment by flyinggrizzly** [comment]
Just checked, this isn't presenting on Debian testing (my other main device).

**Comment by lanox** [comment]
Hi, I also have the same problem where I can't copy and paste on the mac.

On the other note I am not sure If you like me to open a new ticket for this, but when I type the code I get following error.

![screen shot 2018-04-03 at 9 31 09 am](https://user-images.githubusercontent.com/7599183/38221237-cb1d3c34-3721-11e8-837c-201fe2d20fe9.png)

**Comment by GROwen** [comment]
I'm experiencing the same issue as described by @lanox and @flyinggrizzly

**Comment by laurent22** [comment]
A fix for this will be available in a day or so.
