### ISSUE TITLE
Can't rename a folder on desktop

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#3661]
## Environment

Joplin version:  1.0.234 pre
Platform: linux
OS specifics: ubuntu 20.04

## Steps to reproduce

1. create a folder 
2. right click on it 
3. select rename.... nothing happens

## Describe what you expected to happen

I expected to see a popup or something that allows me to rename the folder

This works on android with version 1.0.337

**Comment by JackGruber** [comment]
This was a Bug in pre 1.0.234, in pre 1.0.235 renaming works again.

**Comment by foxmask** [comment]
thank you.
I tested, it's ok now.
