### ISSUE TITLE
How to remove the reminder bar？

### ISSUE THREAD

**Issue by ivysrono** [laurent22/joplin#3662]
## Environment

Joplin version: 1.0.235（All）
Platform: Windows Android
OS specifics: 

## Steps to reproduce

1. 
2. 
3. 

## Describe what you expected to happen
![图片](https://user-images.githubusercontent.com/2649544/91062764-b0294e00-e65f-11ea-8ae5-ec613bcfbb45.png)
I have disabled Encryption. How to remove all Master keys, at least the reminder bar?

**Comment by CalebJohn** [comment]
You should try asking this on [the forum](https://discourse.joplinapp.org/) I think there's some people on there that have experience with this. The github tracker is used for confirmed bugs so issues like this are often ignored.

I don't have experience with this, but my guess is that there are some files that haven't been decrypted yet and thats why you're getting the banner.
If you're sure thats not the case you could take a backup of you notes (File -> Export -> JEX), remove the joplin config files and re-import. That would get rid of it for sure, but it's a pain. You might want to check on the forums first.
