### ISSUE TITLE
Viewer and editor panes are not in sync

### ISSUE THREAD

**Issue by dongguaguaguagua** [laurent22/joplin#3663]
## Environment

Joplin version:
- Joplin 1.0.233
- Joplin is already the latest while I am writing this issue.

Platform: MacOS 10.14

## Steps to reproduce

1. add a [toc] or a header
2. add a picture
3. joplin:

<img width="1552" alt="" src="https://user-images.githubusercontent.com/57585727/91195900-0cf23a80-e72c-11ea-9bef-6c13cfecc54d.png">

4. vscode:
<img width="1552" alt="" src="https://user-images.githubusercontent.com/57585727/91248108-72731500-e786-11ea-9336-156d72207314.png">

preview in VScode is at the cursor's position.

## description
When I put a pictrue in the editor,the length of the picture is only one line.
in addition,the font size in editor and viewer are different espicially when I write a header or a long table of contents,
If viewer and editor panes are not in sync,Previewing is meaningless.

the problem fixed perfectly in [markdown-it](https://markdown-it.github.io/) and [maxiang](https://maxiang.io/)

hope to fix it.

**Comment by dongguaguaguagua** [comment]
It is not like [the issue](https://github.com/laurent22/joplin/issues/3341) in Code Mirror.

**Comment by omega3** [comment]
I run appimage and there is a mismatch between font size of editor and preview:
https://i.imgur.com/J0Cw3JY.png

**Comment by nudomarinero** [comment]
The issue is still present in Joplin for Desktop 1.1.4 in MacOs.

**Comment by p2635** [comment]
This is happening for me as well on Linux Kubuntu 20.10 Joplin 1.3.18

**Comment by dsancheznet** [comment]
On Elementary 5.1 the bug is present.

It is better than before, when the panels would scroll at different speeds, but it is now offset by the length of the TOC.

**Comment by dsancheznet** [comment]
I can confirm that in version 1.4.19 on Linux, the bug is still present. In my case, the MD file contains an index (a long one) and numerous online images.

Regards

**Comment by laurent22** [comment]
Duplicate

**Comment by p2635** [comment]
What's this a duplicate of so I can follow the main ticket?
