### ISSUE TITLE
MacOS - save dialog

### ISSUE THREAD

**Issue by zelvik** [laurent22/joplin#367]
### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [ ] Terminal
### Version
1.0.79

### Problem
When I want export pdf and I click in the save dialog to "expand", the dialog isn't expanded correctly, see picture.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/7302263/38205269-4aafb674-36a6-11e8-9d22-828ca51d2f17.png">

Correct is something like https://cdn1.tekrevue.com/wp-content/uploads/2014/11/safari-save-as-expanded.png

**Comment by laurent22** [comment]
This is an issue with Electron I think, so it would need to be posted there.
