### ISSUE TITLE
Geo-location is zero

### ISSUE THREAD

**Issue by holefrog** [laurent22/joplin#3675]
## Environment

Joplin version: 1.0.336
Platform: Android 10
OS specifics: Google pixel 2xl

## Steps to reproduce

1. Create note
2. Open note properties
3. View on map
4.the gps data is 0.00000° S, 0.00000° W

## Describe what you expected to happen

Geo_location of the note

**Comment by laurent22** [comment]
I cannot replicate this issue, so it might be some problem with the device or permissions. The app needs to have access to gps data.

**Comment by holefrog** [comment]
> I cannot replicate this issue, so it might be some problem with the device or permissions. The app needs to have access to gps data.

I have given the gps access to it. Have no idea why
