### ISSUE TITLE
Logic of "code view" and the view switch icons reversed after upgrade to 1.0.236

### ISSUE THREAD

**Issue by msbentley** [laurent22/joplin#3676]
After upgrade to 1.0.236 on opening Joplin the hiding of the icon to change between MD, dual or rendered view is inverted - i.e. it appears when the WYSIWYG editor is open, and is hidden when this is disable - see screenshot:

![Peek 2020-08-28 13-56](https://user-images.githubusercontent.com/1671065/91586238-5d98ac00-e955-11ea-9f78-7cd90fd50616.gif)

## Environment

Joplin version: 1.0.236
Platform: linux
OS specifics: ubuntu 18.04

## Steps to reproduce

1. Open Joplin
2. Toggle Code View
3. Note the status (visible, greyed out) of the view switcher

Note that the view switcher _does_ still work, but that you have to be in the WYSIWYG editor to use it :)

**Comment by laurent22** [comment]
This is fixed in this branch https://github.com/laurent22/joplin/pull/3586 so it will work once the UI update is released.

**Comment by msbentley** [comment]
Fantastic, thanks @laurent22

**Comment by laurent22** [comment]
It seems to work as expected in v1.2
