### ISSUE TITLE
[Feature request] YouTube video's preview

### ISSUE THREAD

**Issue by Nomadicraty** [laurent22/joplin#368]
Like a Boostnote:
![36940685-66eae1ba-1f59-11e8-8ee7-b111c6814046](https://user-images.githubusercontent.com/32388532/38233694-1b165570-3724-11e8-9abc-14ba3914d004.png)

---

### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [x] Android
- [x] iOS

### Application

- [x] Desktop
- [x] Mobile
- [ ] Terminal

**Comment by laurent22** [comment]
Closed as out of scope.
