### ISSUE TITLE
Joplin Terminal App on Ubuntu 20.04

### ISSUE THREAD

**Issue by ljflyaway82** [laurent22/joplin#3682]
Unable to install terminal application in Ubuntu 20.04, with nodejs 10 or 14. 

Get the following output:

gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.0-42-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/larry/.npm-global/lib/node_modules/joplin/node_modules/keytar
gyp ERR! node -v v14.9.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@5.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@5.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by laurent22** [comment]
Please try `sudo apt-get install -y libsecret-1-dev`

**Comment by ljflyaway82** [comment]
This helped—- it was able to advance the installation further. Unfortunately after what appeared to be some compiling I get another error:

node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/larry/.npm-global/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/larry/.npm-global/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/larry/.npm-global/lib/node_modules/joplin/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1047:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 5.4.0-42-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/larry/.npm-global/lib/node_modules/joplin/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/larry/.npm-global/lib/node_modules/joplin/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/larry/.npm-global/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/larry/.npm-global/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/larry/.npm/_logs/2020-08-31T02_28_56_274Z-debug.log

**Comment by laurent22** [comment]
how do you install it?

**Comment by ljflyaway82** [comment]
I follow the instructions on the site, which is mostly:
npm -g install joplin.

**Comment by Kriechi** [comment]
I'm successfully installing joplin in a docker container based on Ubuntu 20.04:
```
FROM ubuntu:20.04
RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get -y install \
        git \
        libsecret-1-dev \
        pkg-config \
        nodejs \
        npm
RUN npm install -g --unsafe-perm joplin
CMD ["joplin"]
```

**Comment by jfsicilia** [comment]
Same steps followed by @ljflyaway82 and same result.

I'm trying to install joplin terminal app in WSL (windows 10) running Ubuntu 20.04.

Used: `NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin` to install.

Executed: `sudo apt-get install -y libsecret-1-dev` after keytar installation error.

```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/juan/.nvm/versions/node/v14.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.19.104-microsoft-standard
gyp ERR! command "/home/juan/.nvm/versions/node/v14.7.0/bin/node" "/home/juan/.nvm/versions/node/v14.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/juan/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/juan/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v83-linux-x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/juan/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3
gyp ERR! node -v v14.7.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/juan/.nvm/versions/node/v14.7.0/bin/node /home/juan/.nvm/versions/node/v14.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/juan/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/juan/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/juan/.joplin-bin/lib/node_modules/joplin/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 4.19.104-microsoft-standard
node-pre-gyp ERR! command "/home/juan/.nvm/versions/node/v14.7.0/bin/node" "/home/juan/.joplin-bin/lib/node_modules/joplin/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/juan/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/home/juan/.nvm/versions/node/v14.7.0/bin/node /home/juan/.nvm/versions/node/v14.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/juan/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/juan/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/juan/.npm/_logs/2020-09-04T18_35_38_700Z-debug.log
```

Unabled to install joplin.

**Comment by jfsicilia** [comment]
Fixed!

Taking a thorough look through the log I found that there was an error telling that python executable was missing in my Ubuntu installation. I had python3 installed, so I executed:

```
sudo ln -s /usr/bin/python3 /usr/bin/python
```

After that I execute the installation command:

```
NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin
```

and after some compiling, everything went right and I'm able to launch joplin terminal app.

**Comment by ljflyaway82** [comment]
Excellent. I confirm this solves the issue.
