### ISSUE TITLE
Suddenly a bunch of attachments became 288 bytes of size

### ISSUE THREAD

**Issue by luckydays** [laurent22/joplin#3683]
Hey guys.
Something weird happened here.
I wasn't using Joplin for some time (I neither added attachments, nor removed them). Just removed the encryption (Linux Desktop and iOS), and somehow a lot of notes stopped having attachments being displayed.
I went to the `resources` folder and... crap, a bunch of attachments (images in particular) are 288 bytes now and obviously do not open up.

Please see a screenshot of `/home/username/.config/joplin-desktop/resources/`
![image](https://user-images.githubusercontent.com/10942891/91662267-8baaf700-eae1-11ea-8e23-5445442e9355.png)

How this can be fixed? Can anyone help with this, please?

**Comment by laurent22** [comment]
Not sure what happened here. What's the content of these files? How do you sync?

**Comment by luckydays** [comment]
Those are mainly screenshots pasted from the clipboard. Previously loaded and were visible just fine.
Syncing via NextCloud's WebDav.

**Comment by laurent22** [comment]
could you upload one of these files here? It might help to see what the 288 bytes are.

**Comment by luckydays** [comment]
@laurent22 Sure. Thank you for jumping into this.

Attaching it below. And somehow there is a file with the same name and `crypted` extension right next to it.
file:///home/yome/.config/joplin-desktop/resources/d78f1b374e844d909d959b388bc3c9e1.png
file:///home/yome/.config/joplin-desktop/resources/d7a0b5d4258641c18d8b0c1945884054.crypted

**Comment by laurent22** [comment]
Hmm, it seems Nextcloud could not locate the file and sent back some XML response instead:

```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name MegaSync/JoplinYo/.resource/d78f1b374e844d909d959b388bc3c9e1 could not be located</s:message>
</d:error>
```

I don't think it's possible to recover from this as the files are simply gone from the sync target for some reason. Did you move files or folders around or change the sync config in Joplin recently? Also which Nextcloud version is it?

**Comment by luckydays** [comment]
Wow... that's really weirdo...

I didn't move the files or folders around, that's for sure.
The only thing in the sync config that was changed, as I mentioned above, was that I was disabling the encrypting on Desktop (Linux). Maybe switching it back on may help?

And it's Nextcloud 18.0.4

**Comment by laurent22** [comment]
Enabling encryption wouldn't help in this case. How are the files on the sync target, in the .resources directory. Are they also 288 bytes?

**Comment by luckydays** [comment]
Could you specify what exactly you mean by "the sync target" in this case?

**Comment by laurent22** [comment]
I mean the files that are on your Nextcloud Joplin folder.

**Comment by luckydays** [comment]
Ah, OK.
So I went to the Joplin's folder in the Nextcloud, opened the `.resource` directory and interestingly enough all files there are without extensions (encrypted) and some of those again have some tiny little size. See:
![image](https://user-images.githubusercontent.com/10942891/91757345-6d6ef500-ebce-11ea-9dc3-be5d6edd77d1.png)

**Comment by laurent22** [comment]
Yes it's all gone unfortunately and it's not clear why. The best you can do is restore from backup if you have one, or maybe from Nextcloud if they kept older versions of the files.
