### ISSUE TITLE
French Missing Translations

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#3684]
On Desktop version 1.0.236, the menu "Fichier"  displays "Synchronize" instead of "Synchronisation" or "Synchroniser" .

**Comment by foxmask** [comment]
In menu "Options > Options > Apparence" this is in english

>This should be a *monospace* font or some elements will render incorrectly. If the font is incorrect or empty, it will default to a generic monospace font.

and also when clicking on "montrer options avancées"
> CSS file support is provided for your convenience, but they are advanced settings, and styles you define may break from one version to the next. If you want to use them, please know that it might require regular development work from you to keep them working. The Joplin team cannot make a commitment to keep the application HTML structure stable.

**Comment by foxmask** [comment]
In menu "Note > statistique": 

> "read time "

**Comment by devpaulw** [comment]
And, do you have this missing translation too?
https://github.com/laurent22/joplin/issues/3727

**Comment by foxmask** [comment]
> And, do you have this missing translation too?
> #3727

yes but personnaly, I don't need that to be translated. That does not disturb me, as this is also the name of a function.

**Comment by tessus** [comment]
This should be fixed in 1.1. If not, please let me know and I'll re-open this issue.

**Comment by foxmask** [comment]
The 1.1.1 does not have those fixes, 1.1.2 has the fix about "Fichier > Synchroniser" option otherwise everything else is still in english 
the sentences in italic In menu "Options > Options > Apparence" this is in english + in "montrer options avancée" too

and "Note > Statistique" : "Read time" still here
