### ISSUE TITLE
Scrolling is broken in editor on Android

### ISSUE THREAD

**Issue by Retew** [laurent22/joplin#3686]
## Description

I write a lot of long notes, which can take up to several mobile screens, so I need to be able to scroll through them and edit them on my mobile device. However, scrolling only works fine in "reading mode", but doesn't work properly in editing mode. 

Scrolling through a note in editor is very frustrating, slow, and leads to unwanted typing and opening of the keyboard. I have recorded a video of the issue, so you can see what I mean, see it below.

Can be seen in this [video](https://youtu.be/SmNvVfq--r4)

## Environment

Joplin version: 1.0.337
Platform: Android 10
OS specifics: Lineage OS

## Steps to reproduce

1. Open a long scrollable note
2. Open it in editor
3. Try scrolling through it

## Describe what you expected to happen

Fast scrolling as in the viewing mode

**Comment by axq** [comment]
Duplicate of #2287
