### ISSUE TITLE
Android sync to nexcloud - External Storage folder

### ISSUE THREAD

**Issue by Svarto** [laurent22/joplin#369]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

I have an odd problem with the Android Joplin app not syncing to Nextcloud, it throws the error:

`"Error: MKCOL .sync: Could not create directory /external_media/Joplin/.sync (Exception Sabre\DAV\Exception\Forbidden) (403)"`

It is weird because when I go into Nextcloud the folder is actually created, however, nothing is synced?

The "Check Synchronisation Configuration" button in settings works fine and I get a Success! message. Does anyone have an idea what is wrong?

Worth noting, the folder in Nextcloud is mounted through the "External Storage" as an SMB/CIFS share. Would this impact the synchronization?

**Comment by Svarto** [comment]
In case anyone else runs into this problem, in linux samba share you have to put the following into the smb.conf of the specific share:

```
[external_media]
   hide dot files = no
```

Now it works and the .sync folder is visible and writable by Joplin and Nextcloud.

**Comment by khiladiusman** [comment]
I have Installed NextCloud on ubuntu 16.04. Do I need to Install samba share or here other options possible? Thanks
