### ISSUE TITLE
Markup showing in Win10 reminder notification card

### ISSUE THREAD

**Issue by amiablechief** [laurent22/joplin#3690]
Windows 10 notification center card popup shows HTML markup of the Joplin note

## Environment

Joplin version: 
Joplin 1.0.233 (prod, win32)

Client ID: 77ff06be716c40ae86d74fb64cdb2ccc
Sync Version: 1
Profile Version: 32
Keychain Supported: Yes

Revision: e63eee89 (master)
Platform: Windows
OS specifics: Windows 10 version 2004 (19041.450)

## Steps to reproduce

1. Set a reminder on a note
2. Reminder pops up
3. Check in notification center - preview card shows the HTML markup instead of text
See screenshot - [Notification card shows markup](https://imgur.com/zYWcmv6)

## Describe what you expected to happen
The plaintext from the note should be shown instead of markup

## Logfile

Logfile not needed, as this has to do with the visual display of the note within notification center

**Comment by tanaykhajanchi** [comment]
where can i fix this

**Comment by amiablechief** [comment]
Still an issue, would be great if it could be resolved.
