### ISSUE TITLE
[AWS S3 Sync] Custom Bucket Access Domain Name/Url Needed!

### ISSUE THREAD

**Issue by maghsk** [laurent22/joplin#3691]
I am using Huawei Cloud as OBS service supplier. Huawei Cloud has a different url suffix. For example, if my bucket id is "_myid_", then my access domain name is "_myid_.obs.cn-north-4.myhuaweicloud.com". So custom url is needed.

**Comment by jleighton** [comment]
This would also allow the use of Backblaze's S3 Compatible Storage service

**Comment by maghsk** [comment]
> This would also allow the use of Backblaze's S3 Compatible Storage service

Hi jleighton!
I would like to know if you have solved this problem with custom edition on Joplin source code?

**Comment by myoung34** [comment]
I'm on 1.1.4 and would like this also so i can use [minio](https://min.io/) which just needs me to be able to specify the endpoint and region
