### ISSUE TITLE
sync version of the target does not match sync version supported by client

### ISSUE THREAD

**Issue by maichai** [laurent22/joplin#3692]
## Environment

Joplin version: 10.0.52
Platform: iOS
OS specifics: 13.6.1 

## Steps to reproduce

1. tap on sync on iOS app
2. App says: sync version of the target (2) does not match sync version supported by client (1). Please upgrade your client.
3. The macOS (10.15.6) app (1.0.237) has working sync, sync is on WebDAV

## Describe what you expected to happen

Sync succeeds

**Comment by JackGruber** [comment]
Hi, you have i stalled on on client a pre version!
For iOS is no pre version available.
`IMPORTANT: This pre-release will ask you to upgrade your sync target and, once it is done, only the latest clients will be able to sync with this sync target. Currently that includes the desktop app (v1.0.234+) and Android app (v1.0.337+). It means if you are using these two clients you'll be fine. However if you are using the iOS or CLI clients you might want to wait till these clients are updated. Any issue with the sync target upgrade, please post on the forum.`

Wait for iOS version or export all notes and reinstall Joplin with a not pre release version!

**Comment by nshtg** [comment]
Thanks to however updated the AUR package to this pre-release which automatically upgraded my Joplin installationen. iOS clients are not usable anymore...

**Comment by laurent22** [comment]
It seems a number of distribution channels we don't control have been distributing pre-releases as regular releases for some times, but it's only apparent now due to the sync target upgrade. The following needs to be checked and contacted:

- [ ] AUR package
- [x] Homebrew package - https://github.com/Homebrew/homebrew-cask/pull/88528
- [ ] Chocolatey package (seems they are already skipping pre-releases)
- [ ] Android F-Droid package

**Comment by alfredopalhares** [comment]
AUR Package maintainer here.

@nshtg What version are you using ? I only package final release versions, the latest [AUR version is @ 1.0.233](https://aur.archlinux.org/packages/joplin/)

Please let me know which version are you using..

**Comment by nshtg** [comment]
@alfredopalhares 
My bad, it was actually the homebrew version that did the damage. Mea culpa.

**Comment by taw00** [comment]
Fedora and OpenSUSE packages here.
I have not been building and distributing pre-release packages. Cuz ... (a) I actually read the release notes and (b) "pre-release". :)
I do maintain test repos, but they are clearly labeled test repos and I believe I am the one and only one subscribed to them.

https://github.com/taw00/joplin-rpm

**Comment by AddictArts** [comment]
Has anyone done this "export all notes and reinstall Joplin with a not pre release version!"

I have a feeling it is not that simple, what about ~/.config/joplin-desktop 

Is there anyway to test an import without using a different user?

**Comment by n00b12345** [comment]
Facing the same issue. Upgraded Joplin from Play Store yesterday and now sync with iOS isn't working.

**Comment by Kinchilla** [comment]
I'm having the same issue. I just updated Joplin on desktop, and it gave me an orange prompt to update my sync client (or something along those lines). I did so, and the desktop version is syncing fine, but now the iOS app is giving the "sync version of target does not match sync version supported by client" message.

Windows Joplin version: 1.0.242
iOS Joplin version: 10.0.52

I tried installing an older version of the desktop app to try and revert this (because the inability to sync is really stressing me out), but to no avail.

**Comment by n00b12345** [comment]
The new version on iOS is out now. I just updated it and it works great.

**Comment by neilsimp1** [comment]
Using Joplin for Android and Joplin from the [AUR](https://aur.archlinux.org/packages/joplin/) (1.0.242-1) I am seeing the same error on both and am unable to sync.

Nextcloud is v19.0.2 and has Joplin Web API v0.0.25.

**Comment by igbanam** [comment]
Seems like this issue is still on the CLI app

```
> help sync
sync

     Synchronises with remote storage.

     --target <target>  Sync to provided target (defaults to sync.target config value)
     --upgrade          Upgrade the sync target to the latest version.
> sync --upgrade
Synchronisation target: Dropbox (7)
Sync version of the target (3) is greater than the version supported by the client (2). Please upgrade your client.
> version
joplin 1.8.1 (prod)
```

Any ideas on how to fix this?

**Comment by laurent22** [comment]
> Sync version of the target (3) is greater than the version supported by the client (2). Please upgrade your client.

Is there something ambiguous about this message?

**Comment by igbanam** [comment]
That's why I showed the version of Joplin CLI here. It's at the latest.

Please let me know if there's some other client I should be updating.

**Comment by Daeraxa** [comment]
Where are you getting it from? I updated my CLI client the other day, it downloads the current 2.3.2 version needed for sync version 3.

**Comment by normajeane-m** [comment]
same problem..

**Comment by igbanam** [comment]
yarn add global ***@***.***

This is what fixed it for me. I was pinned at 1.8. So the normal upgrade
just upgraded within that range.

Thank you!

**Comment by igbanam** [comment]
That would be "yarn global add ***@***.***"
