### ISSUE TITLE
Show notebook title in title bar

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#3695]
https://discourse.joplinapp.org/t/show-actual-note-book-in-title-bar/10193

**Comment by voiddata** [comment]
maybe i can try to do this.

**Comment by devpaulw** [comment]
I am on it and I will deliver a PR soon.

**Comment by tessus** [comment]
@devpaulw Somehow this never really got any attention, because a PR was never opened. Any chance you can make the changes to the current code? e.g. `app.js` is no longer used, since it was replaced by `app.ts`.

**Comment by asrient** [comment]
@devpaulw are you still working on this issue? If not I would like to take this up. @tessus

**Comment by tessus** [comment]
There was never a PR created and I never got any reply to my previous comment.

Sure @asrient please go ahead and take it.

**Comment by asrient** [comment]
Thanks. I'm on it.

**Comment by arpitg24** [comment]
Is the issue still open?

**Comment by asrient** [comment]
> Is the issue still open?
> 
> 
I'm currently working on it
https://github.com/laurent22/joplin/pull/4390

**Comment by aashimawadhwa** [comment]
is this issue still upon? i am interested in working upon this.

**Comment by asrient** [comment]
Sorry I didn't got enough time, I'm planning to complete the open pr #4390 in a few days.

**Comment by coderrsid** [comment]
![image](https://user-images.githubusercontent.com/35633575/112717764-aed14400-8f14-11eb-85ba-60217d0f7ed4.png)

Did everyone agree to this design at the end @tessus ? or we need to see if there are more options?

**Comment by tessus** [comment]
I can't recall this conversation. It's been a while. But I don't decide on design changes.

**Comment by bkidwell** [comment]
The utility of the new undocumented "--profile" switch is hindered by having nothing identifying the current context in the titlebar. I hope this issue is resolved soon.

**Comment by tomasz1986** [comment]
> The utility of the new undocumented "--profile" switch is hindered by having nothing identifying the current context in the titlebar. I hope this issue is resolved soon.

While it would surely be nice to have some kind of an indication when using `--profile`, the switch itself isn't newly added at all. I can't find when exactly it was added to Joplin at the moment, but it's at least a few years old by now. Please note that support for multiple profiles has indeed been added to Joplin recently, but it's completely separate from the undocumented `--profile` switch.

**Comment by didierm** [comment]
_(not sure whether commenting on a closed issue is appropriate)_
@bkidwell 
I am running parallel (private & work) Joplin desktop instances following this [guide](https://github.com/laurent22/joplin/issues/591#issuecomment-878490533), and hence require the profile in the window title to distinguish between them.

The following script+patch downloads and patches the Linux x86_64 AppImage (no source patching & building required) to show the ; HTH somebody.
Note : to provide the required `npx` command,  `npm` needs to be installed ([7-Zip plugin alternative](https://sourceforge.net/p/sevenzip/discussion/45797/thread/74cf1dec/) not tested).

```
JDIR="$HOME/misc/joplin"
JVER="2.9.4"
ARCH=x86_64
```

```
APP_ORIG="Joplin-${JVER}.AppImage"
APP_PTCH="Joplin-${ARCH}.AppImage"
PATCH="$JDIR"/joplin-windowtitle.patch

cd "$JDIR"
```
```
# optional
wget https://github.com/laurent22/joplin/releases/download/v${JVER}/${APP_ORIG}
chmod a+x $APP_ORIG
```
```
./$APP_ORIG --appimage-extract	 # --appimage-help
cd ./squashfs-root/resources/
npx asar extract app.asar app_extracted
cd app_extracted/
patch -b -u -d gui/ < "$PATCH"
cd ../
npx asar pack app_extracted app.asar
rm -rf app_extracted/
cd ../
ln -s @joplinapp-desktop.png joplin.png	 # mitigate appimagetool build error
cd ../
ARCH=${ARCH} appimagetool -v ./squashfs-root/
rm -rf ./squashfs-root/
```


[joplin-windowtitle.patch.gz](https://github.com/laurent22/joplin/files/9482906/joplin-windowtitle.patch.gz)
