### ISSUE TITLE
Joplin doesn't start; expects profile version 32 but found 33

### ISSUE THREAD

**Issue by micheldebree** [laurent22/joplin#3701]
When I open Joplin desktop app, it gives a fatal error and does not start:

<img width="418" alt="Screenshot 2020-09-04 at 14 01 23" src="https://user-images.githubusercontent.com/4125356/92237628-f8ded380-eeb7-11ea-900a-761368b248b1.png">

## Environment

Joplin version: 1.0.233
Platform: macOS
OS specifics: Mojave (10.14)

## Steps to reproduce

1. Open Joplin

## Describe what you expected to happen

I expect Joplin to start.

**Comment by duncanlivingston** [comment]
I have this behaviour too, for both the dmg and homebrew versions of Joplin 1.0.233 on macOS Catalina.

**Comment by AddictArts** [comment]
I had this problem as well, due to homebrew upgrade. I manually installed the latest release 1.0.241 I believe, here from dmg. Just replace the one on /Applications. Eventually home-brew will catch up, but this resolved the issue for me.

**Comment by duncanlivingston** [comment]
> I had this problem as well, due to homebrew upgrade. I manually installed the latest release 1.0.241 I believe, here from dmg. Just replace the one on /Applications. Eventually home-brew will catch up, but this resolved the issue for me.

Interesting... the version offered by the website (direct link) and homebrew are both 1.0.233, not the version 1.0.241 that you have.

**Comment by AddictArts** [comment]
@duncanlivingston you can find the latest release always here on github on the releases page https://github.com/laurent22/joplin/releases

**Comment by micheldebree** [comment]
Upgrading to 1.0.241 fixed it for me, thanks!
Homebrew is up to date with 1.0.241 version now so I just used that.
Issue can be closed as far as I am concerned.

**Comment by laurent22** [comment]
Should be solved with latest release
