### ISSUE TITLE
sync_desktop json constantly getting deleted at regular intervals in latest update

### ISSUE THREAD

**Issue by GreatestFool** [laurent22/joplin#3705]
## Environment

Joplin version: 1.0.242
Platform: Windows
OS specifics: 1809 17763.1397

## Steps to reproduce

I'm using Dropbox sync for my main profile, but don't have the possibility to test the one using OneDrive, so it could be a dropbox specific issue for all I know.

1. Update to 1.0.242
2. Click the link to rebuild the sync target or whatever
3. Wait
4. Will eventually get a notification saying sync_desktop json file having been deleted about every few minutes

## Describe what you expected to happen

Not for the file to get deleted every so often.

## Logfile

Console log: https://pastebin.com/5Fk4P8ti
Log.txt does not contain any errors.

**Comment by ambrt** [comment]
Same for Linux, latest version

**Comment by sdreger** [comment]
Confirming. The same behavior on macOS Catalina 10.15.6

**Comment by laurent22** [comment]
This is discussed there: https://discourse.joplinapp.org/t/joplin-i-love-you-but-this-is-driving-me-nuts-dropbox/10842/7
