### ISSUE TITLE
Add a file to the macOs DMG to show how to enable Joplin to run on Catalina

### ISSUE THREAD

**Issue by unixorn** [laurent22/joplin#3706]
Embed a **READ_WHEN_JOPLIN_WONT_OPEN_ON_CATALINA** textedit file in the dmg file that basically says "macOs is paranoid and won't run the app. To run it anyway, go to the Security pane in System Preferences and select **Run Anyway**."

**Comment by tristinDLC** [comment]
Until this is implemented, you can just disable this warning all together when installing apps from unidentified developers. Open up Terminal and run this command `sudo spctl --master-disable`. Now if you go to System Preferences > Security and Privacy > General, you'll notice that Anywhere is now once again an option for where to allow apps to be installed.

**Comment by unixorn** [comment]
Cool, I didn't know you could toggle that off. Adding that instruction to the Catalina warning file is probably a good idea too.

**Comment by tristinDLC** [comment]
It will turn off that security check for all apps you're installing. There will still be a pop-up letting you know you are opening an app you downloaded off the internet, but you can just hit ok to continue. You no longer have to go into Preferences > Security, individually authorize the app, and then attempt to open it again. 

Running that code will just blanket allow all apps to be installed.
