### ISSUE TITLE
Repeated Sync in Android Tablet

### ISSUE THREAD

**Issue by metalg0su** [laurent22/joplin#3708]
## Environment

Joplin version: 1.0.339 at Goople Play Store
Platform: Android
OS specifics: 10
Device: SM-T975N (Galaxy Tab S7+)
Sync type: WebDAV

## Steps to reproduce
> I don't know what is the bug triggers. So please be patient of my long story below.

1. I opened the app as usual on my tablet
1. The app said "initialize sync target". Maybe it is automatically updated.
1. and I see "initilaizing...." with joplin logo on the white screen.
1. I'm worried about any possible sync problem. So I try to sync on my mobile phone. 
1. joplin on my phone says "need to be update", So I updated the app on my phone and it has no sync problems.

...

## Describe what you expected to happen
1. I returned to my tablet and open the app.
1. After initializing screen, I see my settings are set to initial state, with white theme.
1. I fixed my sync target from Dropbox (initial) to my WebDAV target.
1. it re-sync notes normally...
1. But when I unlock the device to re-open the app, it is re-initialized! again!

### Details
- All settings are restored to the initial values. Also welcoming tutorial notes are generated.
- Thus, the app tries to re-sync to inital target  **DropBox** and fails.

### Possible triggers
1. Re-focusing the app which is running at background?

> Note that my mobile phone is safe. I think this issue is related to latest devices or OS, especially on  Galaxy Tab S7+.

## Logfile
> I want to re-produce it and provide you logs but I'm scared that all my note
s are overwritten.

**Comment by metalg0su** [comment]
+ It seems that the issue is valid on mobile phone too.. I suffered same issue now. 
> Environment: I watched YouTube on small sub screen (premium feature) and I opened Joplin. Possible related?

> I temporarily stop using Joplin on my mobile devices. I hope this issue will be resolved soon 🙏

**Comment by laurent22** [comment]
Sorry I don't understand what the issue is from your post. For example there's no "initialize sync target" message anywhere in the app.

Please be more precise: if you start the app what do you see? And what did you expect to see?

**Comment by metalg0su** [comment]
Sorry for my bad writing. I was overemphasized and trying to describe that my sync target is set as Dropbox(default). 
Please forget it.

If I open the app, I see:
- Sync target is set as DropBox (default)
- Joplin theme is set as `Light` (default)
- `Welcome! (Mobile)` notebook is generate.

**Comment by berserkk** [comment]
Hello,

I got absolutely the same annoying issue on 2 different devices and on 1 of them it was reproduced 2 times (after the 1st time I've reset application and manually synced it once again).
Reproducing is super simple: just open the application.

It shows `Initialising application...` and then resets all settings to their defaults, but keeps previous notes.
In 1 case it showed me the last error:

```
Error: Unknown table: folders
```

Joplin version: 1.0.340
Platform: Android
OS specifics: 10

`.sync/version.txt` is `1` (if that's somehow can be useful).

**Comment by metalg0su** [comment]
I think you can reproduce this by re-sizing joplin app.

**Comment by metalg0su** [comment]
related:
https://github.com/laurent22/joplin/issues/3800

**Comment by metalg0su** [comment]
> tested at 1.2.6
It seems resolved and I cannot reproduce this issue both on mobile and tablet.
