### ISSUE TITLE
Apple sees v1.0.242 as malicious software.

### ISSUE THREAD

**Issue by rasulkireev** [laurent22/joplin#3709]
<img width="452" alt="Screen Shot 2020-09-06 at 1 03 20 AM" src="https://user-images.githubusercontent.com/8257474/92318643-39843d00-efdd-11ea-85e7-439f34472e5f.png">

## Environment

Joplin version: 1.0.242
Platform: MacOS Catalina
OS specifics: Version 10.15.6

**Comment by laurent22** [comment]
Please see other threads about this

**Comment by rasulkireev** [comment]
Sorry @laurent22 , did not see the other thread.

https://github.com/laurent22/joplin/issues/1983

Solution is to launch via the safe method. In other words right click on Joplin and the click Open. You should then have an option to open anyway.
