### ISSUE TITLE
in the WYSIWYG editor, Link are not clickable

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#3715]
## Environment

Joplin version: 1.0.242
Platform: ubuntu
OS specifics: 20.04

## Steps to reproduce

1.  get a page of your choice with the webclipper
2. open the editor to that grabed article
3. put the cursor of the mouse on the link, you can't click on it. If you swith the WYSIWYG off the link can be clicked

## Describe what you expected to happen
cf point 3 ;)

**Comment by laurent22** [comment]
Did you try Ctrl+Click by the way?

**Comment by foxmask** [comment]
No, but that works.
The main issue is the cursor that does not have the expected form (https://pnghut.com/png/m2tXH592NP/computer-mouse-pointer-cursor-text-transparent-png) when we move it over the link.
As the textarea becomes an editor ; the cursor always looks like that : https://www.iconfinder.com/icons/446140/cursor_mouse_pointer_text_write_icon
it is misleading.

**Comment by laurent22** [comment]
Yes this is quite difficult to change the cursor depending on the context, but maybe that could be fixed at some point.

**Comment by foxmask** [comment]
the bot should take into account the last who've spoken (moderator/owner) to avoid to trigger a warning one month later.
as the one who made the request is expecting something from the last person who's spoken, (s)he doesn't | I dont have anything to add ; just waiting :)

**Comment by foxmask** [comment]
already one month?

**Comment by foxmask** [comment]
ce bot fait n'importe quoi, c'est chiant :(

**Comment by laurent22** [comment]
I don't think that can be implemented unfortunately, so it might be best to just close it.
