### ISSUE TITLE
Option to inline resources / images

### ISSUE THREAD

**Issue by alexanderadam** [laurent22/joplin#3719]
Usually there are different options to link resources in markdown.

#### 1. Either linking to an external path
```markdown
![image](https://avatars1.githubusercontent.com/u/372620?s=460&u=9c18ddb233cbcbe6b40d89e77fea229410654520&v=4)
```

#### 2. Inlining as a base64 encoded source

```markdown
![image](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAYAAACAvzbMAAAGRElEQVR4nOzYoYrUURiH4f8s6wUI2wzG3SDIBoMYdrwgb8EZr2CDWo1Gm3mnmc1aVpimIGLY5MhU41vOEZ7nCn7hgxe+0wX+8ebB9mZZlvXoHczj7GS/PLv3YfQMJnMyegAA/ycBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIFm93j28GT2CyXx89HP1/snn0TOYx8Xdj6uLP1/Xo3cwl2NADqNHMJ1XL9a329EjmMd+eXm8h83oHczFCwuAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIDk9Mvd5egNTOby/v7q8P12O3oH8/i1+fT499unu9E7mMtqefftMHoEc9meXy+b8+vRM5jLbnW2PB89grl4YQGQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAImAAJAICADJ3wAAAP//7v0qd0kF2T0AAAAASUVORK5CYII=)
```

The Joplin renderer already seem to support it anyway (you can test it with the example source above) and therefore only an easy way to integrate (and/or migrate) the resources is needed.

This could solve the [orphaned resources issue](https://github.com/laurent22/joplin/issues/932) and simplify resource handling in general, right?

<div align = "center">

![you can't forget deleting external resources if you don't have any external resources](https://user-images.githubusercontent.com/372620/92387529-ff6a8680-f115-11ea-88a2-ca5bb361bff8.png)

</div>

I don't know how you're storing resource at the moment and what's the relation of SQLite in Joplin right now. If resources were stored as external files before and would now be stored within the SQLite database with this option, then this could impact the performance.

**PS:** There are also browser extensions like [`img2base64`](https://github.com/Arryboom/img2base64), that allow to copy an image as base64 directly

**Comment by laurent22** [comment]
Whether resources are embedded or not is mostly an implementation detail. What you suggest could equally be solved by enforcing a one-to-one relationship between resources and notes. Neither solutions is very easy to implement so not sure when it will be done.

Of course one issue with embedding resources is that you lose the ability to optionally download resources as is currently allowed.
