### ISSUE TITLE
Update chocolatey package to latest version

### ISSUE THREAD

**Issue by thiagomajesk** [laurent22/joplin#372]
@laurent22 As the author, can you update the chocolatey package for windows to the latest version? 
The version available in the chocolatey repo is still 1.0.67.

**Comment by laurent22** [comment]
I didn't submit or manage this package. It seems to be maintained by @peterbeck so please check with him.

**Comment by thiagomajesk** [comment]
@laurent22 Oh, I'm sorry. I went directly to the "Software Author(s)" section and forgot about "Package Maintainer(s)". Indeed @peterbeck is the maintainer.

**Comment by laurent22** [comment]
No problem. Maybe there's a way to automate publishing the package based on the .exe?
