### ISSUE TITLE
goBackInTime test randomly fails

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#3722]
I can replicate it with this seed:

    npm test -- --seed=38559

It happens as of this commit: 08d4b5a71417ab620c6180c3622b833be3089a21 on this line: https://github.com/laurent22/joplin/blob/08d4b5a71417ab620c6180c3622b833be3089a21/CliClient/tests/timeUtils.js#L32

```
$ npm test

> joplin@1.0.167 test /.../CliClient
> gulp buildTests -L && node node_modules/jasmine/bin/jasmine.js --fail-fast=true --config=tests/support/jasmine.json

Testing with sync target: memory
Randomized with seed 38559
Started
....................................................................................................................F

Failures:
1) timeUtils should go back in time
  Message:
    Expected '1597014000000' to be '1596927600000'.
  Stack:
    Error: Expected '1597014000000' to be '1596927600000'.
        at <Jasmine>
        at /.../CliClient/tests-build/timeUtils.js:32:51
        at UserContext.<anonymous> (/.../CliClient/tests-build/test-utils.js:531:10)
        at <Jasmine>

117 specs, 1 failure
Finished in 123.943 seconds
Randomized with seed 38559 (jasmine --random=true --seed=38559)
npm ERR! Test failed.  See above for more details.
```

**Comment by laurent22** [comment]
@naviji, maybe it will make sense to you? It seems that the test should be deterministic and independent however it always fails with that particular seed and always with error "Expected '1597014000000' to be '1596927600000'". If I run the test in isolation then it passes. Any idea what can be causing this?

**Comment by naviji** [comment]
This is strange. I'll take a look.

**Comment by naviji** [comment]
I still have no idea what's causing this! Sorry.

**Comment by laurent22** [comment]
Yes I can't make sense of it either. I think what it is testing, going back 0 week in time has not a particularly obvious behaviour either so it could be related. I've disabled the test for now and hopefully no user will hit this edge case.
