### ISSUE TITLE
[Feature request] Multiple notes tags

### ISSUE THREAD

**Issue by Nomadicraty** [laurent22/joplin#373]
![mspaint_2018-04-04_10-51-40](https://user-images.githubusercontent.com/32388532/38295381-784b2a4a-37f6-11e8-9613-8fead557818c.png)

---

### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [x] Android
- [x] iOS

### Application

- [x] Desktop
- [x] Mobile
- [x] Terminal

**Comment by laurent22** [comment]
Closed as duplicate.

**Comment by christianlupus** [comment]
Just for reference: see #359
