### ISSUE TITLE
Using bulleted list, numbered list, or checkbox list together does not work in WYSIWYG mode

### ISSUE THREAD

**Issue by BryanWall** [laurent22/joplin#3731]
Using lists (bullets, numbers, or checkboxes) together works as expected in Editor, Viewer, or Split View, but does not work in WYSIWYG view. in WYSIWYG, using bullets under checkboxes causes it to display bullets and checkboxes overlapping each other. 

## Environment

Joplin version: 1.0.242
Platform: Macos
OS specifics: v10.15.6

## Steps to reproduce

1. Create any type of list using any edit mode
2. On the next line, create a different type of list, either at the same level or indented under the previous list
3. View the result in WYSIWYG mode

## Describe what you expected to happen

I expect the output in WYSIWYG to match the output in Viewer mode

![Bullets-under-checkmarks-2](https://user-images.githubusercontent.com/5903057/92504498-c2af9580-f1d0-11ea-9325-e53cb49ae49d.gif)

**Comment by BryanWall** [comment]
I just noticed that after working in one of the files for a while, and switching to other notes and back, bullets that were underneath checkboxes get **_changed_** to checkboxes in the markdown

**Comment by BryanWall** [comment]
Is this something that will be fixed when one of the already-planned UI changes is implemented?

**Comment by thiemjoerg** [comment]
When will this be fixed. It is still an issue.

Joplin 2.5.12 (prod, win32)

Client-ID: 2af31b6b698c4384b9198e5d3dcbbe4e
Sync-Version: 3
Profil-Version: 39
Unterstützter Schlüsselbund: Ja

Revision: 884b86f
