### ISSUE TITLE
Layout button becomes grayed out and not clickable 

### ISSUE THREAD

**Issue by BryanWall** [laurent22/joplin#3732]
Since v1.0.242 the layout button grays out and becomes unclickable after being pressed once regardless of Layout Button Sequence chosen. I think the issue might be that the toggle is being changed incorrectly between WYSIWYG and non-WYSIWYG because the button is sometimes clickable in WYSIWYG mode but not Editor/Viewer mode. See GIFs below.

I can make Layout mode work by toggling WYSIWYG off, select a different note, then select the note I want to edit. Switching to WYSIWYG "breaks" the Layout button until I disable WYSIWYG, select a different note, and then select the first note again. 

## Environment

Joplin version: 1.0.242
Platform: Macos
OS specifics: v10.15.6

## Steps to reproduce

1. Switch to WYSIWYG mode
2. Select a note, then select a different note
3. Click Code View button (Layout is grayed out)
4. Click Code View again (Layout is clickable in WYSIWYG mode)
5. Click Layout button (Layout button becomes unclickable and layout doesn't change)

## Describe what you expected to happen

I expect the Layout button to be clickable when in Editor / Viewer / Split View mode

![Layout-button-stops-working](https://user-images.githubusercontent.com/5903057/92506167-073c3080-f1d3-11ea-8937-423920225977.gif)

![Layout-button-stops-working-2](https://user-images.githubusercontent.com/5903057/92506207-191dd380-f1d3-11ea-9b61-be63222db45f.gif)

[log.txt](https://github.com/laurent22/joplin/files/5189759/log.txt)

**Comment by laurent22** [comment]
It is fixed in the UI upgrade, which should be out relatively soon.

**Comment by sebadrude** [comment]
I have the same or a similar problem, I believe it started after updating to 3.0.15 (Windows).
THe Ctrl+L option in the menu is greyed out, and so is the button on the top right corner of the editor pane.  some notes appear formatted, others only show the markdown code, as far as I can tell.
I restarted the app. a number of times, reset the layout, but I do not get the choice between WYSIWYG and MarkDown any more.

**Comment by sebadrude** [comment]
Seems it resolved itself this morning, although I already had rebooted yesterday...
