### ISSUE TITLE
Error: Sync fails to fetch all remote items after upgrading to 1.0.242 - Linux Desktop App

### ISSUE THREAD

**Issue by iyga** [laurent22/joplin#3733]
Syncing does not complete after updating Linux Desktop app to 1.0.242. Sync Target is Dropbox. The error reads "Error: On file 3fdd8c6dd52b4969bf19d632f8767f1c.md: Missing required property: type_: id: ...". The error occurs while fetching remote items (which occurs after successfully creating remote items).

Uninstalling (by removing both `~/.config/Joplin` and `~/.config/joplin-desktop`) and re-linking Joplin to Dropbox did not fix the problem. This error does not occur in the iOS app (Joplin 10.0.53).

**Meanwhile, synchronisation was successful (both creating and fetching of remote items completed without any error) with version 1.0.233 (when Sync Target is set to Dropbox) and version 1.0.242 (when Sync Target is set to File System)**.

### version 1.0.233 + Dropbox

- Backed up Notes (Export to RAW)
- Disconnected and Deleted Joplin from Connected Apps in Dropbox
- Uninstalled Joplin (by removing both *~/.config/Joplin* and *~/.config/joplin-desktop*)
- Downloaded and Launched Joplin version 1.0.233
- Import Notes -- RAW - Joplin Export Dictionary
- Enabled Encryption
- Synchronise to Sync Target (Dropbox)

**Outcome**: No Error was encountered

### version 1.0.242 + Dropbox

- Disconnected and Deleted Joplin from Connected Apps in Dropbox
- Uninstalled Joplin (by removing both *~/.config/Joplin* and *~/.config/joplin-desktop*)
- Launched Joplin version 1.0.242
- Import Notes -- RAW - Joplin Export Dictionary (same back up used with version 1.0.233)
- Enabled Encryption
- Synchronise to Sync Target (Dropbox)

**Outcome**: Fetched items: 10/117.
Completed: 08/09/2020 20:33
Last error: Error: On file 3fdd8c6dd52b4969bf19d632f8767f1c.md: Missing required property: type_: id: 3fdd8c6dd52b4969bf19d632f8767f1c parent_id: e3566ceb61a542f980296e1af551effd created_time: updated_time: ..."

### iOS app (Joplin 10.0.53) + Dropbox

Did this after reinstalling version 1.0.242 + Dropbox (as described above)

- Deleted and re-downloaded Joplin from the App Store
- Connected to Sync Target (Dropbox)
- Set encryption password
- Synchronise to Sync Target (Dropbox)

**Outcome**: Sync Completed without Errors. Notes are also up to date.

### Reinstalled version 1.0.242 + File System

- Disconnected and Deleted Joplin from Connected Apps in Dropbox
- Uninstalled Joplin (by removing both *~/.config/Joplin* and *~/.config/joplin-desktop*)
- Launched Joplin version 1.0.242
- Import Notes -- RAW - Joplin Export Dictionary (same back up used with version 1.0.233)
- Enabled Encryption
- Synchronise to Sync Target (File System)

**Outcome**: No Error was encountered.

## Environment

Joplin version: 1.0.242
Platform: Linux
OS specifics: Ubuntu 18.04.5 LTS

## Steps to reproduce

1. Update to Joplin 1.0.242
2. Make sure Encryption is Enabled
3. Attempt to Sync to Dropbox Target

## Describe what you expected to happen

I expect Sync to Complete without errors (i.e. successful creation and fetching of remote items)

## Logfile

[Debug Log](https://github.com/laurent22/joplin/files/5190956/-1599597186116.log)

[log.txt](https://github.com/laurent22/joplin/files/5193223/log.txt)

**Comment by RedDocMD** [comment]
Please upload `log.txt` from `~/.config/joplin-dev`.

**Comment by iyga** [comment]
> Please upload `log.txt` from `~/.config/joplin-dev`.

[log.txt](https://github.com/laurent22/joplin/files/5193223/log.txt)

**Comment by nigomeza** [comment]
I'm having the same issue in Debian Buster 10 running with KDE plasma. I tried to remove config and storage files and reinstall but didn't work either. Anything on mind? 
The specs of my system are: Linux  4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux

**Comment by iyga** [comment]
I switched Synchronisation Target from Dropbox to WebDAV.

**Comment by nigomeza** [comment]
Thank you @iyga. I solved it, I just re-encrypt my notes and both in my Dell Latitude E6230 Debian Buster 10, Acer Spin Sp13 Ubuntu 20.04 and Samsung S8 the problem didn't reapper any more and the sync is working as usual as before. Thank you for your suggestion.
