### ISSUE TITLE
[Feature request] Tag renaming

### ISSUE THREAD

**Issue by Nomadicraty** [laurent22/joplin#374]
![mspaint_2018-04-04_10-54-57](https://user-images.githubusercontent.com/32388532/38295460-bf88241c-37f6-11e8-8750-a9c83269940b.png)

---

### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [x] Android
- [x] iOS

### Application

- [x] Desktop
- [x] Mobile
- [x] Terminal

**Comment by laurent22** [comment]
Done in #543
