### ISSUE TITLE
Missing Master Key / Error: Lock has expired

### ISSUE THREAD

**Issue by tim-hub** [laurent22/joplin#3742]
## Environment

Joplin version: 1.0.340
Platform:  Android
OS specifics:  Android 10 

## Steps to reproduce
This happened since 2 days ago.

I added a new encryption key on android client.

On desktop side, I see `Missing Master Key`, while all notes edited on android side kept encrypted.

For debugging.
- I checked the remote side, cannot find the file with the name of missing encryption key.
- Also on the android side, I tried find on `sdcard` and `/data/data/net.co...joplin` for the file, I cannot, it seems like this encryption key only exist on local android sqlite databse, but not on local/remote sync folder.

## Describe what you expected to happen
The new master key should be generated and synced to the remote

## Logfile

Please see the attached log.

Something I see related to `Error: Lock has expired`
[joplin-log.txt](https://github.com/laurent22/joplin/files/5213321/joplin-log.txt)

**Comment by laurent22** [comment]
I see errors like "Error: json decode: this isn't json!" which indicates that some of your data is corrupted, so the best would be to restore from a backup. Do you use jianguoyun? As it is known to cause various problems like this.

**Comment by tim-hub** [comment]
> I see errors like "Error: json decode: this isn't json!" which indicates that some of your data is corrupted, so the best would be to restore from a backup. Do you use jianguoyun? As it is known to cause various problems like this.

no, box/webdav is what I use.

it seems currently, my android client cannot sync and my desktop client, warn me to set password for the unsynced master key/missing key + 3 encrypted items.


quite annoying?


I synced to web dav, so I did not have a backup, when you see restore, do you mean, uninstall android app and re-synce from remote?

The other question is that,

Is it safe for me to delete that encrpyted items on desktop side, will deleting and uninstalling android make `missing master key`  disappear?

**Comment by tim-hub** [comment]
> I see errors like "Error: json decode: this isn't json!" which indicates that some of your data is corrupted, so the best would be to restore from a backup. Do you use jianguoyun? As it is known to cause various problems like this.

How to restore?

do you mean uninstall it and resync from remote?

**Comment by tim-hub** [comment]
this is more link webdav/box syncing issue on android.

close it, this problem un-perfectly solved after switch to dropbox.
