### ISSUE TITLE
Huge number of HTTP sessions created by WebDAV sync

### ISSUE THREAD

**Issue by sdeleuze** [laurent22/joplin#3744]
When synchronizing my pCloud drive using WebDAV sync, I see a huge number of tokens (it seems to be something like number of syncs x number of connections x number of devices) created on pCloud side, and those tokens are long lived (1 year) so they quickly accumulate. It would be nice from a security perspective to reuse tokens instead of creating new ones.

**Comment by laurent22** [comment]
What do you mean by token exactly?

**Comment by sdeleuze** [comment]
Indeed, sorry I should have been more specific. By tokens I mean HTTP sessions created on the server. In my pCloud admin interface I can see which devices has created which sessions. I usually see one session by application on a specific device, allowing me to be sure which one can access to my data.

But with Joplin installed on my Iphone and my desktop (Ubuntu 20.04) using WebDAV I see hundreds of HTTP sessions created:
![image](https://user-images.githubusercontent.com/141109/93718380-18deea00-fb7c-11ea-8010-eb651a38cff5.png)

Maybe HTTP connection keep-alive is not enabled or something like that?

**Comment by woodwolfzhu** [comment]
I meet this question too. When I want to sync notes in a new device,there are so many requests that my free webdav has occured error(limited 500 requests per minute). In fact I do not have so many notes.

**Comment by sdeleuze** [comment]
I think this issue is still relevant, I have currently not the bandwidth to learn the project and send a PR, I hope somebody from the team will be able to have a deeper look.
