### ISSUE TITLE
Rest api allows unauthenticated POST to tags and GET to folders

### ISSUE THREAD

**Issue by ambrt** [laurent22/joplin#3747]
I'm running cli server, and it allows to post to /tags/:id:/notes endpoint without token. Listing tags titles and listing folders is also allowed.

I think that those endpoints should be protected.

**Comment by tessus** [comment]
https://discourse.joplinapp.org/t/joplin-rest-api-why-are-certain-endpoints-whitelisted/10696/3?u=tessus
