### ISSUE TITLE
CodeMirror not continuing lists (emacs mode)

### ISSUE THREAD

**Issue by meznak** [laurent22/joplin#3749]
When making a list, making a new line doesn't auto-insert the list markdown. This behavior is new since the switch to CodeMirror.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/1106662/93117651-05131f80-f674-11ea-91de-6ccb1af896d1.png
[log-snipped.txt](https://github.com/laurent22/joplin/files/5220038/log-snipped.txt)
">

## Environment

Joplin version: 1.1.1
Platform: macOS
OS specifics: 10.14.6 (Mojave)

## Steps to reproduce

0. Use Emacs editor mode
1. Create a new note
2. Start a list (ordered, unordered, checkbox)
3. Enter text for the first line
4. Press Return

## Describe what you expected to happen
New line should contain the appropriate list markdown (-, 2., - [])

## Logfile

[log-snipped.txt](https://github.com/laurent22/joplin/files/5220039/log-snipped.txt)

**Comment by CalebJohn** [comment]
Hi @meznak it looks like you didn't attach an image this would be helpful in assisting you in troubleshooting as I can't reproduce your issue. 
Can you check your behaviour in the [codemirror website markdown mode](https://codemirror.net/mode/markdown/)? It works for me here as well, so maybe this is an issue with your setup

**Comment by meznak** [comment]
The codemirror site isn't continuing lists for me, either.

Here's a quick demo: 
[Screen Recording 2020-09-15 at 8.55.05 AM.mov.zip](https://github.com/laurent22/joplin/files/5226329/Screen.Recording.2020-09-15.at.8.55.05.AM.mov.zip)

**Comment by meznak** [comment]
This functionality is missing from the Emacs keyboard mode, per @CalebJohn . He's looking into it.
