### ISSUE TITLE
iOS AWS S3 Sync Failure - Raw buffer output not supported for FsDriverRN.readFile

### ISSUE THREAD

**Issue by bschmittel** [laurent22/joplin#3751]
iOS version results in sync failure when using S3 sync method.  Notes are not encrypted.

## Environment

**Sync Source**
Joplin version: 1.0.245
Platform: MacOS
OS specifics: Catalina 10.15.6

**Sync Target**
Joplin version: 10.0.53
Platform: iPadOS
OS specifics: 13.6.1

## Steps to reproduce

1.  Initiate a new sync from the desktop client to AWS S3 (Beta), all remote items created.
2. Setup iOS app with same S3 target location.  Initiate sync
3. Result:
> Created remote items: 1.
> ...
> Last error: Error: Raw buffer output not supported for FsDriverRN.readFile

## Describe what you expected to happen

Synchronization to occur without issue.

**Comment by bschmittel** [comment]
Looks to be same as #3601, though #3601 references Android and the above is iOS.

**Comment by waynema02** [comment]
I am experiencing the same issue for iOS client.
