### ISSUE TITLE
Tags are all lower case

### ISSUE THREAD

**Issue by MHoeller** [laurent22/joplin#3752]
A tag new created tag with a capital first letter is changed to all lower case

## Environment
Joplin for Desktop
Joplin 1.1.2 (Ubuntu 20.04 LTS)
Revision: c9451d8 (master)

## Steps to reproduce
1. Create Tag
![grafik](https://user-images.githubusercontent.com/11714953/93228686-10e70a80-f776-11ea-8f93-4325164f9eff.png)
![grafik](https://user-images.githubusercontent.com/11714953/93228718-193f4580-f776-11ea-960f-079f96909946.png)

2. check the tags in the sidebar
![grafik](https://user-images.githubusercontent.com/11714953/93228794-2f4d0600-f776-11ea-8a17-c68469b65e73.png)

## Describe what you expected to happen
I would expect that the tag is not changed

**Comment by tessus** [comment]
You can follow the different discussions about this on the forum. This is not a bug.
