### ISSUE TITLE
Error: Cannot acquire sync lock after upgrading on Android

### ISSUE THREAD

**Issue by paulcable** [laurent22/joplin#3753]
After forced update I cannot use Joplin app on Android. Desktop app works great, but not Android. 
Btw desktop app is 1.0.245. 

## Environment

Joplin version: 1.0.339 , 1.0.340
Platform: Android
OS specifics: Android 10

## Steps to reproduce

1. Go to Google Play store (1.0.339) or direct link to download (1.0.340).
2. Use Nextcloud for sync.
3. Check error message. 

## Describe what you expected to happen

I expected to sync my files.

**Comment by laurent22** [comment]
I assume it's some clock sync issue which will be fixed in the next release. For now, make sure the time on your server and device is exactly the same.
