### ISSUE TITLE
TUI Joplin sync failed 

### ISSUE THREAD

**Issue by bnsv** [laurent22/joplin#3763]
Hello, I have installed Joplin on mobile (Android & iOS), Linux desktop (GUI & TUI). After updating all mobile apps and updating Desktop app via wget and sucessfully updating automaticaly. The GUI working normally but unfortunately Joplin in terminal failed to sync. Updating using wget npm sh only updating the GUI version to 1.0.245. The Joplin TUI stay at version 1.0.164 (prod). 

## Environment

Joplin version: 1.0.164 (prod)  
Platform: Joplin TUI
OS specifics: Ubuntu LTS

## Steps to reproduce

1. Open Joplin via terminal
2. Send :sync command
3. Syncing failed

## Describe what you expected to happen
All Joplin version stay able to sync even in different version.

## Logfile
> :sync
> sync [Press Ctrl+C to cancel]: Completed: 17/09/2020 23:18 Last error: Error: Sync version of the target (2) does not match sync version supported by client (1). Please upgrade your client.

**Comment by Anode194** [comment]
I've been having the same problem and reinstalling via npm is crapping out on my mac for some reason.

**Comment by laurent22** [comment]
This version is 4 months old. Try v1.0.168

**Comment by bnsv** [comment]
> This version is 4 months old. Try v1.0.168

I am sorry. How can I upgrade to that version since upgrading via terminal only upgrading the GUI version not the TUI?

**Comment by laurent22** [comment]
How did you install it?

**Comment by bnsv** [comment]
I am forgot and not really sure, but I think it is from Snap, or  "wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash",  or NPM install. The NPM update seems updating the GUI version only not the TUI. But for sure that I have both GUI (1.0.245(prod)) and TUI (1.0.164 (prod)) Installed in my machine.
