### ISSUE TITLE
Android App: Search only matches full words

### ISSUE THREAD

**Issue by mvonmaltitz** [laurent22/joplin#3769]
Search on Android only matches full words. If a part of a word is searched, the expected matches are not found. 
E.g. I have a supermarket list, which contains a To-Do "carrots". If I search for "carrot", the To-Do does not show up.

## Environment

Joplin version: Android App 1.0.340
Platform: Android

## Steps to reproduce

1. Enter a To-Do with title "abcdefghi"
2. Search for "abc"

## Describe what you expected to happen

The To-Do "abcdefghi" is found.

Reality: The mentioned To-Do is not found.

**Comment by CalebJohn** [comment]
Hello @mvonmaltitz 

Fuzzy search (the feature you have requested) was included in release [v1.1.1](https://github.com/laurent22/joplin/releases/tag/v1.1.1) which is in pre-release mode for the desktop and not yet available for Android. I don't know when the next Android release will happen, but when it does this should be fixed.
