### ISSUE TITLE
Certain characters result in unclickable entries in TOC in exported PDF and HTML

### ISSUE THREAD

**Issue by hexclover** [laurent22/joplin#3780]
## Environment

Joplin version: 1.1.3
Platform: Windows 10

## Steps to reproduce

Try the following Markdown file:

```markdown
[toc]
## Clickable title
## クリックできない
## クxxx
## 😊
## 😊a
```

The last four headings contain Unicode characters: the second and the third contain katakana in Japanese, and the last two have emojis.

**To PDF**: On my machine it is exported as this PDF file: [Test Note.pdf](https://github.com/laurent22/joplin/files/5251959/Test.Note.pdf). Only **the first** and **last** TOC entries are clickable.

**To HTML**: On my machine, in the produced HTML file, all entries are clickable links, but the fourth does not work properly. The emojis are stripped from the anchor names and the Japanese characters are preserved.

**Comment by laurent22** [comment]
Fixed again
