### ISSUE TITLE
Android sync - slow and lags

### ISSUE THREAD

**Issue by Svarto** [laurent22/joplin#379]
### Operating system

- Android

### Application

- Mobile

I have around 402 notes, with some attachments from Evernote that creates around 1500 items (not sure how this is calculated).

My problem is that the sync is slow, probably takes more than 2 hours to do a full sync from my Android phone to the Nextcloud WebDav. This means that the app is constantly syncing and it slows it down to the point where it is unusable. Is this normal behaviour? Should I just put it as manual sync and only sync when I change something?

I don't know why the Android app fetches all 1500 items, one by one, during each sync even though none of them have changed...?

**Comment by foxmask** [comment]
I had to migrated 2500 evernote notes during 5days on onedrive, for a total of 8800 objects.
And with dropbox it's worst, the sync of a bunch of 100 took for several hours :/
I think it's related to the API of the cloud service.

**Comment by Svarto** [comment]
thanks foxmask, but then basically once the sync is done, it stops and only syncs the updates? Or is it a full sync everytime?

Because it seems like the app is in constant sync, and keep "fetching" the full 1500 items all the time...

**Comment by foxmask** [comment]
That does not restart each time but continue.

**Comment by laurent22** [comment]
One thing to keep in mind is that the first sync when there are many items can take a long time.  This will be improved in a future version but for now just let it run over night without interruption. After that it will only fetch and upload what has changed.

**Comment by laurent22** [comment]
Also is there any error or warnings in the log?

**Comment by Svarto** [comment]
Yes, I can't for some reason export the debugging log, it isn't created in the folder where it says it is created.

Anyway, look at the log, I have 2 errors that keep repeating:

1) DecryptionWorker: Error for: "random number" (resources), Error: Invalid encryption identifier. Data is not actually encrypted? ID was: null

2) DecryptionWorker: error for: "random number" (resources), Error: json decode: this isn't json!

I also see now that my tags are not decrypted on my phone but the notes are - they are all using the same decryption masterkey as I enabled the encryption initially from the desktop app and then entered the same password into the Android phone app to decrypt the files when syncing to the phone. 

Any idea what I can do to fix this? 

Thanks a lot for your help Laurent!!

**Comment by Svarto** [comment]
By the way, I take it back about my tags not being decrypted, it just seems the app needed some time and now they are decrypted. Still get the errors though.

**Comment by laurent22** [comment]
@Svarto, these errors would not prevent sync to complete. Could you try letting it run to completion over night to see if really there's a bug or if it's just slow?

**Comment by Svarto** [comment]
I have tested it a fair bit now, no bug and the sync completes. It is just unfortunate that it is incredibly laggy to the point of unusable when starting the Android app until the sync is done (even just to check that a sync is not necessary).

**Comment by laurent22** [comment]
It's probably just the initial decryption being slow. I guess it could be improved and maybe there should be better messages to show the progress.
