### ISSUE TITLE
Editing notes on Android 10 is difficult due to slow/stopping scrolling. This is kind of an issue if you have a very long note.

### ISSUE THREAD

**Issue by dede321** [laurent22/joplin#3790]
Open/View a very long note. One can scroll from top to bottom (and vice versa) nicely. Now click edit. One starts at the bottom. If one wants to reach the top within the editor, we have to slide our fingers across the display a lot of times in order to reach the top given the note is very long.

**Comment by axq** [comment]
Duplicate of https://github.com/laurent22/joplin/issues/2287 and https://github.com/laurent22/joplin/issues/3686.
