### ISSUE TITLE
Codeview code block font color too close to Nord theme background

### ISSUE THREAD

**Issue by SilvM** [laurent22/joplin#3793]
![image](https://user-images.githubusercontent.com/11724527/93836670-1aacc880-fcb6-11ea-8341-b25e9329062c.png)

## Environment
![image](https://user-images.githubusercontent.com/11724527/93836696-2e582f00-fcb6-11ea-8b07-fa4f9402cd17.png)

Joplin version: 1.1.4
Platform: Mac
OS specifics: desktop app

## Steps to reproduce
1. Write a code block with yaml, bash syntax highlighting (see screenshot)

## Describe what you expected to happen
Syntax highlighting should still work, or at least be readable

**Comment by carlosedp** [comment]
@SilvM Added a couple new languages (including YAML) in #3786.

**Comment by SilvM** [comment]
thanks @carlosedp . Now I only need to find out how to change the headline color back to the nice green. Not a fan of the purple in the new version

**Comment by CalebJohn** [comment]
@SilvM I dropped a couple links in [this forum post](https://discourse.joplinapp.org/t/unannounced-text-color-scheme-change/11205) that should help you change that. Let me know if its not clear.

**Comment by SilvM** [comment]
Thanks @CalebJohn , that will be a good start. I'll need to dustoff my CSS knowledge. Are you aware of any threads for community-made themes?

**Comment by SilvM** [comment]
actually one of your links contained the theme I was hoping to find :D: [gruvbox](https://github.com/robotcorner/joplin-theme-dark-gruvbox)

**Comment by carlosedp** [comment]
Sorry to hijack the Issue but @CalebJohn, is it possible to have the full code block with a different background?

**Comment by CalebJohn** [comment]
@carlosedp 

> Sorry to hijack the Issue but @CalebJohn, is it possible to have the full code block with a different background?

Not really, you can identify the different classes used in code blocks and set a uniform background color, and if you combine that with setting display to inline-block then you kinda get a block, but it's not ideal.
