### ISSUE TITLE
Option to disable new editor gone, app crashes if it was already enabled before v1.1.2

### ISSUE THREAD

**Issue by carestad** [laurent22/joplin#3797]
I had enabled the new editor in the app, and now after the v1.1.2 in Android, I can not disable it. And it crashes continuously. Please either auto-disable this for me in a newer release or give me the config option back to disable it.

I have also tried downloading older APKs from the joplin-android repo, but it will not install. My only option is then to wipe the Joplin data and set it up from scratch.

## Environment

Joplin version: 1.1.2
Platform: Android
OS specifics: Android 10

## Steps to reproduce

1. Install a version of Joplin on Android before v1.1.2 and enable the new editor
2. Upgrade Joplin to v1.1.2
3. Try and add or edit a note and see that the new editor is still there and it causes the app to crash

## Describe what you expected to happen

The new editor not to be present at all.

**Comment by laurent22** [comment]
If you download the latest pre-release it should work: https://github.com/laurent22/joplin-android/releases/tag/android-v1.2.1
