### ISSUE TITLE
Feature request:  Please add "Copy Link Location"

### ISSUE THREAD

**Issue by izhakjakov** [laurent22/joplin#3799]
Please add "Copy Link Location" option when left clinking on a hype link in viewer mode.
Currently there is only a "Copy" option which copies the text and not the link:

Example:
![image](https://user-images.githubusercontent.com/18270061/93885197-e46d4a00-fcb1-11ea-897e-d36250a0865f.png)

**Comment by CalebJohn** [comment]
Hi @izhakjakov thanks for the request, however it is a duplicate of #3404 , luckily there is already a patch available which will hopefully be merged soon #3474

**Comment by izhakjakov** [comment]
> Hi @izhakjakov thanks for the request, however it is a duplicate of #3404 , luckily there is already a patch available which will hopefully be merged soon #3474

Awesome can't wait.  Thank you :)
