### ISSUE TITLE
web site documentation inconsistencies

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#380]
https://joplin.cozic.net/#synchronisation

First it says `https://example.com/nextcloud/remote.php/webdav/Joplin` then a few sentences later it mentions `https://example.com/nextcloud/remote.php/dav/files/USERNAME/Joplin`.

**Comment by Torsten-K** [comment]
https://example.com/nextcloud/remote.php/dav/files/USERNAME/Joplin is correct (if you have created a subfolder named Joplin in your Nextcloud); at least this way it works for me.

**Comment by tessus** [comment]
Well, I also use a subfolder called `Joplin`, but I use this API endpoint (the first one):
`https://example.com/nextcloud/remote.php/webdav/Joplin`

So it seems that both endpoints work. However, for consistency the documentation should only mention one endpoint. Either one or the other, not both. Wouldn't you agree?

**Comment by Torsten-K** [comment]
Oh, I did not realize that both of those endpoints do work. And yes, I agree with you, that only one of those optons should be named – or both of them, but in the same sentence as alternative A and B.

**Comment by Torsten-K** [comment]
Very confusing, in deed.
