### ISSUE TITLE
Android App regularly looses path sync settings and then creates "Welcome! (Mobile)" Notebook

### ISSUE THREAD

**Issue by dede321** [laurent22/joplin#3800]
It occurred for the third time within 2 days that the Android App Joplin 1.0.339 lost its path sync settings on a Samsung S10 with Android 10, which has all latest updates installed. It  then also creates "Welcome! (Mobile)" notebook. Don't get confused by the wrong time order of the screenshots. I just "faked" the screenshots to show the before and after state, once this issue occurs.

### State before the issue happens
<img width=70% height=70% src="https://user-images.githubusercontent.com/16488606/93895889-9592d500-fcf0-11ea-9af7-b9f32cfeb15a.jpg">
<img width=70% height=70% src="https://user-images.githubusercontent.com/16488606/93895896-975c9880-fcf0-11ea-8415-74974f3c29d2.jpg">

### State after the issue happens
<img width=70% height=70% src="https://user-images.githubusercontent.com/16488606/93895893-975c9880-fcf0-11ea-98e1-465759cc0dd7.jpg">
<img width=70% height=70% src="https://user-images.githubusercontent.com/16488606/93895891-96c40200-fcf0-11ea-8f54-d0f69d7fd22e.jpg">

**Comment by fireball74** [comment]
Confirmed this on a Sony Xperia 5 (with Android 10 and Joplin 1.0.339). Previous Joplin versions on the same phone did not behave in this way.

**Comment by siebenbrodt** [comment]
And version 1.0.336 can't sync no more:
"Error: Sync version of the target (2) does not match sync version supported by client (1). Please upgrade your client."

**Comment by fireball74** [comment]
@siebenbrodt I think your problem is not related to what is described here. Please have a look at [issue #3692](https://github.com/laurent22/joplin/issues/3692).

Now running Joplin (Android) 1.1.2 I had a couple of days not losing my Nextcloud sync settings. What happened now is that I long-pressed a link in Firefox and shared it with Joplin in order to save it. I was expecting to end up in the latest used notebook but Joplin opened up and sent me to "Welcome! (Mobile)" notebook (that did not exist when I left Joplin prior to that). When seeing this I went into "Configuration" and saw that now "Dropbox" was the default (with empty settings) instead of the expected Nextcloud settings (now also empty but previously working just fine).

**Comment by siebenbrodt** [comment]
@fireball74 No, unfortunately my problem is also in new "Welcome! (Mobile)" notebook and resetting sync settings. It's just that the android client 1.0.336 was too old to sync with my desktop version.
Another thing is interesting: in my case, sharing does not affect the reset of the sync settings. Yesterday I successfully shared a link from Firefox and even a track from a sports app in a note (Joplin Android 1.1.2). But today at some point when I opened the application, I found that the settings were reset to the "Dropbox" again (I'm using Nextcloud too). I still don't understand what triggers this event. Now I'm trying Pre-release version 1.2.2.

**Comment by fireball74** [comment]
@siebenbrodt Aha, I see. I am also still trying to figure out if I can capture the triggering event.

**Comment by dede321** [comment]
Today, it happened again. It lost its local file path. This time, I was only using the Android app as reader and Synchronize Ultimate was set to one-way sync (nextcloud server to files). So, I guess it has nothing to do with Synch. Ultimate.

**Comment by siebenbrodt** [comment]
Resetting settings when I tried to share a link from Firefox, Joplin Android Pre-release 1.2.2:
```
10-01T15:20:04,30,"""SearchEngine: Updating FTS table...""
10-01T15:20:02,30,"""DecryptionWorker: completed decryption.""
10-01T15:20:02,30,"""DecryptionWorker: starting decryption...""
10-01T15:20:01,30,"""Settings have been saved.""
10-01T15:20:01,30,"""Saving settings...""
10-01T15:20:01,30,"""DecryptionWorker: completed decryption.""
10-01T15:20:01,30,"""Synchroniser is missing credentials - manual sync required to authenticate.""
10-01T15:20:01,30,"""Updating all notifications...""
10-01T15:20:01,30,"""Garbage collecting alarms...""
10-01T15:20:01,30,"""Saving updated Dropbox auth.""
10-01T15:20:01,30,"""Preparing scheduled sync""
10-01T15:20:01,30,"""DecryptionWorker: starting decryption...""
10-01T15:20:00,30,"""ResourceFetcher: Auto-added resources: 0""
10-01T15:20:00,30,"""Application initialized""
10-01T15:20:00,30,"""ResourceFetcher: Auto-add resources: Mode: always""
10-01T15:20:00,30,"""Trying to load 1 master keys...""
10-01T15:20:00,30,"""Loaded master keys: 1""
10-01T15:20:00,30,"""Loading folders...""
10-01T15:20:00,30,"""PluginAssetsLoader: Assets are up to date. Hash: f4a92e18907bd8e77b014e1dc3d454cd""
10-01T15:20:00,30,"""Sync target: 7""
10-01T15:20:00,30,"""Trying to load 1 master keys...""
10-01T15:20:00,30,"""Loaded master keys: 1""
10-01T15:20:00,30,"""KeychainService: checking if keychain supported""
10-01T15:20:00,30,"""KeychainService: check was already done - skipping. Supported:", "0""
10-01T15:20:00,30,"""Database is ready.""
10-01T15:20:00,30,"""Loading settings...""
10-01T15:20:00,30,"""Converting database to version 34""
10-01T15:20:00,30,"""Current database version", "33""
10-01T15:20:00,30,"""Database was open successfully""
10-01T15:20:00,30,"""Checking for database schema update...""
10-01T15:20:00,30,"""====================================""
10-01T15:20:00,30,"""Starting application net.cozic.joplin-mobile (prod)""
10-01T15:19:57,30,"""Fetching geolocation...""
10-01T15:19:55,30,"""DecryptionWorker: completed decryption.""
10-01T15:19:55,30,"""DecryptionWorker: starting decryption...""
10-01T15:19:55,30,"""Settings have been saved.""
10-01T15:19:55,30,"""Saving settings...""
10-01T15:19:54,30,"""Received shared data""
10-01T15:19:54,30,"""Application initialized""
10-01T15:19:54,30,"""SearchEngine: Updated FTS table in 264ms. Inserted: 0. Deleted: 1""
10-01T15:19:54,30,"""Settings have been saved.""
10-01T15:19:54,30,"""ResourceFetcher: Auto-added resources: 0""
10-01T15:19:54,30,"""ResourceFetcher: Auto-add resources: Mode: always""
10-01T15:19:54,30,"""Trying to load 1 master keys...""
10-01T15:19:54,30,"""Loaded master keys: 1""
10-01T15:19:54,30,"""Loading folders...""
10-01T15:19:54,30,"""Sync target: 7""
10-01T15:19:54,30,"""PluginAssetsLoader: Assets are up to date. Hash: f4a92e18907bd8e77b014e1dc3d454cd""
10-01T15:19:54,30,"""db.ftsEnabled = ", "1""
10-01T15:19:54,30,"""FTS check succeeded""
10-01T15:19:54,30,"""Trying to load 1 master keys...""
10-01T15:19:54,30,"""Loaded master keys: 1""
10-01T15:19:54,30,"""KeychainService: checking if keychain supported""
10-01T15:19:54,30,"""KeychainService: could not set test password - keychain support will be disabled""
10-01T15:19:54,30,"""Database is ready.""
10-01T15:19:54,30,"""Loading settings...""
10-01T15:19:54,30,"""RevisionService::maintenance: Done in 138ms""
10-01T15:19:54,30,"""RevisionService::collectRevisions: Created revisions for 0 notes""
10-01T15:19:54,10,"""RevisionService::collectRevisions:", "Error: Fields have not been loaded yet
value@index.android.bundle:1258:1241
value@index.android.bundle:430:2214
value@index.android.bundle:430:11306
value@index.android.bundle:430:11124
f@index.android.bundle:108:155
index.android.bundle:108:882
y@index.android.bundle:114:661
C@index.android.bundle:114:1025
callImmediates@index.android.bundle:114:3100
callImmediates@[native code]
value@index.android.bundle:26:3247
index.android.bundle:26:1283
value@index.android.bundle:26:2939
value@index.android.bundle:26:1253
value@[native code]
value@[native code]""
10-01T15:19:54,30,"""Saving settings...""
10-01T15:19:54,30,"""Converting database to version 34""
10-01T15:19:54,30,"""Current database version", "33""
10-01T15:19:54,30,"""Database was open successfully""
10-01T15:19:54,30,"""Checking for database schema update...""
10-01T15:19:54,30,"""Starting application net.cozic.joplin-mobile (prod)""
10-01T15:19:54,30,"""====================================""
10-01T15:19:54,30,"""RevisionService::maintenance: Starting...""
10-01T15:19:54,30,"""RevisionService::maintenance: Service is enabled""
10-01T15:19:54,30,"""SearchEngine: Updating FTS `table...""
```

**Comment by JackGruber** [comment]
Hi have the same Problem on Android 10 with Joplin 1.1.2.

https://discourse.joplinapp.org/t/webdav-config-encryption-config-randomly-lost-on-android/11364

**Comment by fireball74** [comment]
I am getting more and more confident in that the corrupted settings are connected to sharing something with Joplin using the Android version. All settings are lost, not only the sync settings. Was not able to catch the actual event. All I see is:

10-04T11:58:25,30,"""Converting database to version 34""
10-04T11:58:25,30,"""Current database version", "33""
10-04T11:58:25,30,"""====================================""
10-04T11:58:25,30,"""Starting application net.cozic.joplin-mobile (prod)""
10-04T11:58:25,30,"""Database was open successfully""
10-04T11:58:25,30,"""Checking for database schema update...""
10-04T11:58:25,30,"""Synchroniser is missing credentials - manual sync required to authenticate.""
10-04T11:58:25,30,"""SearchEngine: Updating FTS table...""
10-04T11:58:25,30,"""Saving updated Dropbox auth.""
10-04T11:58:25,30,"""Preparing scheduled sync""
10-04T11:58:18,30,"""RevisionService::maintenance: Done in 1211ms""
10-04T11:58:17,30,"""RevisionService::collectRevisions: Created revisions for 2 notes""
10-04T11:58:17,30,"""Settings have been saved.""
10-04T11:58:17,30,"""Saving settings...""

So definitely after the fact unfortunately. Never used Dropbox in any form. Please advise on how to catch the "actual trigger" if anyone has a method available.

**Comment by Sono-Gomorrha** [comment]
I also can report this (Pixel 3a with latest Android installed). Joplin still has all my old notes from previous syncs, but now reset to the default (?) sync settings, that is Dropbox and no encryption password for the master key. Before I was syncing using WebDAV and this worked fine with a Windows, Linux and Mac machine, as well as an iPad.

**Comment by frogger72** [comment]
Seeing the same issue here on 1.1.2.

**Comment by JackGruber** [comment]
from the forum:
>https://discourse.joplinapp.org/t/webdav-config-encryption-config-randomly-lost-on-android/11364/13
>
>For those having this issue could you please try v1.2? https://github.com/laurent22/joplin-android/releases/tag/android-v1.2.3
>I've changed the way the app is launched to prevent multiple instances from running at the same time as I suspect that's what the problem is.

**Comment by fireball74** [comment]
Tried it and no luck. I replied in the forum instead to keep the ongoing discussion there consistent. Thanks for highlighting @JackGruber .

**Comment by PetrVladimirov** [comment]
> 
> 
> @siebenbrodt I think your problem is not related to what is described here. Please have a look at [issue #3692](https://github.com/laurent22/joplin/issues/3692).
> 
> Now running Joplin (Android) 1.1.2 I had a couple of days not losing my Nextcloud sync settings. What happened now is that I long-pressed a link in Firefox and shared it with Joplin in order to save it. I was expecting to end up in the latest used notebook but Joplin opened up and sent me to "Welcome! (Mobile)" notebook (that did not exist when I left Joplin prior to that). When seeing this I went into "Configuration" and saw that now "Dropbox" was the default (with empty settings) instead of the expected Nextcloud settings (now also empty but previously working just fine).

I can confirm - the same behavior - after sharing a link from Firefox to Joplin, Joplin sync settings were reset from NextCloud to Dropbox.
Android 10, Samsung

**Comment by PetrVladimirov** [comment]
> 
> 
> @siebenbrodt I think your problem is not related to what is described here. Please have a look at [issue #3692](https://github.com/laurent22/joplin/issues/3692).
> 
> Now running Joplin (Android) 1.1.2 I had a couple of days not losing my Nextcloud sync settings. What happened now is that I long-pressed a link in Firefox and shared it with Joplin in order to save it. I was expecting to end up in the latest used notebook but Joplin opened up and sent me to "Welcome! (Mobile)" notebook (that did not exist when I left Joplin prior to that). When seeing this I went into "Configuration" and saw that now "Dropbox" was the default (with empty settings) instead of the expected Nextcloud settings (now also empty but previously working just fine).

I can confirm - the same behavior - after sharing a link from Firefox to Joplin, Joplin sync settings are reset from NextCloud to Dropbox.
Joplin 1.1.2, Database v.34 on Android 10, Samsung

**Comment by fireball74** [comment]
https://discourse.joplinapp.org/t/webdav-config-encryption-config-randomly-lost-on-android/11364/26
