### ISSUE TITLE
Cannot remove search highlight

### ISSUE THREAD

**Issue by paradogks8** [laurent22/joplin#3802]
## Environment

Joplin version: Joplin 1.1.4 (prod, win32)
Platform: Windows 64-bit

## Steps to reproduce

1. Search for a term (e.g. 'welcome', in the search bar at the top of the program)
2. Click the cross to remove the search term from the bar
3. Highlights from the search (shown in blue in the attached image) will remain until a new search is made

## Describe what you expected to happen
I expected clicking the cross to remove the search highlights that were made, but I find that they persist. The only way to remove them is to search for a new term, though that simply creates new highlights, or to restart Joplin entirely. Is there a way to remove the search highlights that I am missing? Or is this a bug?
![image](https://user-images.githubusercontent.com/71715144/93897933-8f015f00-fcea-11ea-89b0-065c956ede08.png)

**Comment by CalebJohn** [comment]
Hi! This was fixed in #3717 and will be working in the next release.
