### ISSUE TITLE
Android App regularly looses encryption settings and I need to re-enter the password & activate the encryption...

### ISSUE THREAD

**Issue by dede321** [laurent22/joplin#3804]
I did not change anything, started the app, and it asks me again for my decryption password, despite having it set already.

Android 10
Joplin 1.1.2 (Updated it a few hours ago and after the update encryption/synching was working) with local file sync + Ultimate sync.

![Screenshot_20200922-195612_Joplin](https://user-images.githubusercontent.com/16488606/93919657-48256080-fd0e-11ea-893b-df0dfea2e373.jpg)

The Android app seems to be very buggy in combination with file synching. I would love to, but can't test the webdav on Android, as it does not accept self-signed certificates.

**Comment by laurent22** [comment]
I can't replicate this issue but I've noticed that another user had this issue after sharing some text or image with Joplin (from another app). Do you often share data with Joplin from other apps?

**Comment by dede321** [comment]
> I can't replicate this issue but I've noticed that another user had this issue after sharing some text or image with Joplin (from another app). Do you often share data with Joplin from other apps?

I never used an app to share text or images in Android, but I have the habit to kill apps by opening the Android's "current apps running overview" and sliding (terminating them) apps away,  so this could potentially be an issue.

Or it has something to do with the local file sync? For now, I have set Ultimate Sync as a one way sync (nextcloud server to local file) and I only use Joplin as viewer. If the bug re-appears (loosing any settings), I will drop a quick message here.

**Comment by dede321** [comment]
like deftdawg I also do not use webdav. I use local file synching.

**Comment by dede321** [comment]
deftdawg: I do no use webdav. I use local file synching in combination with Ultimate Sync.

**Comment by siebenbrodt** [comment]
Same here. Never shared anything, lost Nexcloud sync settings today apparently due to auto-update. Unfortunately did not look at the version number. Installed 1.2.1.apk, synced - and then sync settings and encryption password cleared again. Uninstalled, installed 1.0.340.apk - synced everything - then app added Welcome! (Mobile) notebook and the settings were reset again, asking to Login with Dropbox.

**Comment by deftdawg** [comment]
This morning my settings reset again ☹️ 

Still 1.1.2, the app was closed when I started.  Is it possible a file handle is being left open to the configuration and that the file becomes corrupted when the app is killed by Android?

**Comment by deftdawg** [comment]
I noticed in logs section of the android app some complaints about "Could not update database to v34"... Not sure if it's related
![Screenshot_20200926-084321](https://user-images.githubusercontent.com/4991612/94342528-8907c880-ffdf-11ea-8b28-ef51641331a2.jpg)

**Comment by kikoqiu** [comment]
Changing the size of joplin window in a split-screen (multi window)  situation will lead to the bug, too.

**Comment by q6r** [comment]
I experienced the same. After sometime it removes webdav settings and requests E2EE key again seems like all configuration is reset but notes still appear from the cache. I've re-added the sync settings and it synced all notes again in plaintext format causing me to ssh to the webdav and do some manual work to make sure no plaintext left on the server.

This started to happen since last update 1.1.2. I will try to replicate it and create some useful logs.

**Comment by fgrove** [comment]
I've just had Joplin lose the encryption settings for the second time in a few days. On Android, version 1.1.2, syncing to Nextcloud.

**Comment by JackGruber** [comment]
Hi, look at: Issue: https://github.com/laurent22/joplin/issues/3800

and the forums discussion:
https://discourse.joplinapp.org/t/webdav-config-encryption-config-randomly-lost-on-android/11364

In the version 1.2.5 the problem should be fixed: https://github.com/laurent22/joplin-android/releases/

**Comment by dspacejs** [comment]
I have the same problem. I have the latest version installed on F-Droid, and this just happened today.

**Comment by dede321** [comment]
Since this fix, I have not had this issue, anymore. S10 or Tab 10.1.

**Comment by dspacejs** [comment]
This just happened again. Honestly really disappointed with the quality of the mobile app, it's been very buggy. The desktop app works great, though.
