### ISSUE TITLE
Markdown syntax highlighting in the code view with the Dark theme became worse

### ISSUE THREAD

**Issue by hb20007** [laurent22/joplin#3805]
## Environment

Joplin version: 1.1.1 and later
Platform: Windows, possibly others too
OS specifics: Windows 10 Home Single Language version 1809

## Steps to reproduce

1. Compare the syntax highlighting between v1.1.1 and v1.0.245.

**v1.1.1**:

![v1.1.1 screenshot](https://user-images.githubusercontent.com/8860322/93922724-fe8f4280-fd1a-11ea-837c-2fd22f68782b.png)

**v1.0.245**:

![v1.0.245](https://user-images.githubusercontent.com/8860322/93922838-2aaac380-fd1b-11ea-9d0e-211ae42ce849.png)

## Describe what you expected to happen

I expected the colors to remain the same. This could be a feature and not a bug, but I don't think so since I believe the old colors look better, and since it is not listed as a feature in the release notes of v1.1.1.

**Comment by CalebJohn** [comment]
The new release versions included a move to a new editor component which did not have the same themes available. You can customize the colours however you want with the userchrome.css file.
Take a look at [my comment on the forums](https://discourse.joplinapp.org/t/unannounced-text-color-scheme-change/11205/2) for some information about customizing further.

If you're really stuck changing the colours yourself, feel free to drop a comment below and I can try to help you out.

**Comment by m-ad** [comment]
Just to clarify: Does this issue being closed mean that there won't be dark theme syntax highlighting included in Joplin in the foreseeable future?

**Comment by hb20007** [comment]
@m-ad Take a look at the [link](https://discourse.joplinapp.org/t/unannounced-text-color-scheme-change/11205/4) posted by CalebJohn above. In that forum, a user called dpoulton posted some CSS that you can place in the userchrome.css file for more colorful syntax highlighting. As for whether there are plans to make this the default in the future, I don't know.

**Comment by CalebJohn** [comment]
Just to clarify, there are no current plans to change the default syntax highlighting.
