### ISSUE TITLE
View notes on sidebar (and not on notelist)

### ISSUE THREAD

**Issue by Athalef** [laurent22/joplin#3806]
Dear team
It feels like every time this feature suggestion comes up it gets misunderstood by someone that suggest something else.

as discussed [here](https://github.com/laurent22/joplin/issues/3767) on the git and [here](https://discourse.joplinapp.org/t/show-notes-on-notebook-tree/10915/4) on the forum and in some more feature requests by users, It would be nice to be able to see the notes from a notebook on the same sidebar (below the notebook they are in) instead of showing them on a separate notes list.

Something tells me it should be easy to implement but my coding skill are quit low to tell.
If that's something that can be done by editing userchrome.css file in the profile folder - I'd love to know how to.

Thank you and stay safe

**Comment by Athalef** [comment]
Hey stale. I'm commenting to let you know that the issue is not fixed yet.
Anything I can do the get some attention from the development team? Can we solve this issue?

**Comment by Athalef** [comment]
Just realized stale is a bot :)

**Comment by wrein** [comment]
I think this would be a good and useful feature, but it would be valuable only to people having less notes per notebook and many notebooks, so it should be a selectable preference option:
- Note list separated from notebooks list, as it is now.
- Notes listed with notebooks in the sidebar (as a filesystem kind of view)
