### ISSUE TITLE
Add notebook "+" button moves depending on if side bar is scrollable

### ISSUE THREAD

**Issue by msbentley** [laurent22/joplin#3809]
In the (great looking!) new UI design, I noticed that the add notebook button at the top-right of the side bar moves left or right depending on if the side bar has a scroll bar (e.g. if I fold or unfold the tag list):

![jopling_icon_moving](https://user-images.githubusercontent.com/1671065/93973989-72f6cf80-fd75-11ea-9f50-9ad57c0b82e7.gif)

It's a very minor thing, but it would be nice to squash it so as not to distract from the shiny new UI ;-)

## Environment

Joplin version: 1.2.2
Platform: linux
OS specifics: ubuntu 18.04

**Comment by msbentley** [comment]
Yes, this still occurs in 1.3.7 preview

**Comment by msbentley** [comment]
This still occurs in 1.4.11

**Comment by msbentley** [comment]
This still happens in 1.5.8

**Comment by msbentley** [comment]
Still present in 1.7.3

**Comment by msbentley** [comment]
Still present in 1.7.11

**Comment by ankitpal1029** [comment]
I actually tried this out and the plus is infact moving when the scroll bar comes up.

**Comment by msbentley** [comment]
Hmm, OK. But it doesn't do this when I fold and unfold the notebook list, for example, which in my case is well over a page...

**Comment by coderrsid** [comment]
Working to fix it. Probably one solution can be shifting it to a little left, so that when scrollbar comes up, it won't move. 
That'd be the right way @roman-r-m ?

**Comment by roman-r-m** [comment]
> Working to fix it. Probably one solution can be shifting it to a little left, so that when scrollbar comes up, it won't move.
> That'd be the right way @roman-r-m ?

Maybe, haven't looked much into this. Give it a try and we'll see

**Comment by coderrsid** [comment]
> > Working to fix it. Probably one solution can be shifting it to a little left, so that when scrollbar comes up, it won't move.
> > That'd be the right way @roman-r-m ?
> 
> Maybe, haven't looked much into this. Give it a try and we'll see

Absolutely, on it. Actually my PR earlier has not been approved yet, can you please review that too #4773.

**Comment by msbentley** [comment]
Still around in 2.0.4

**Comment by msbentley** [comment]
Still present in 2.1.8

**Comment by msbentley** [comment]
Still present in 2.2.5
