### ISSUE TITLE
keyboard shortcut: export produces empty file

### ISSUE THREAD

**Issue by tbdal** [laurent22/joplin#3811]
behaviour: settings -> keyboard shortcuts -> export -> creates empty "keymap-desktop"-file

## Environment

Joplin version: Joplin 1.1.4 
Platform: (prod, linux) & (prod, win32) tested

## Steps to reproduce

1. go to settings 
2. click keyboard shortcuts
3. click export

## Describe what you expected to happen
export the keyboard mapping in a file

## Logfile

* log.txt: `2020-09-23 12:34:17: "KeymapService: Saving keymap to file: /home/a/Desktop/temp/keymap-desktop"`
* debugging tools are not working: clicking on export is not possible:
![image](https://user-images.githubusercontent.com/6881189/94002224-e7dc0080-fd99-11ea-9412-edc872b2692e.png)

**Comment by laurent22** [comment]
It doesn't export default shortcut
