### ISSUE TITLE
The latest android version report"Can't find variable:btoa"

### ISSUE THREAD

**Issue by rankaiyx** [laurent22/joplin#3815]
![25d52f0909d14e82e0cf38a88ebd6ed](https://user-images.githubusercontent.com/39045067/95661875-f1a88680-0b43-11eb-9418-2fe1e35a0efd.png)

![3d0ec3568c58e8fe744585dc702f6b1](https://user-images.githubusercontent.com/39045067/95661867-e6edf180-0b43-11eb-963e-d60b1ed15c33.png)

## Environment

Joplin version: android joplin 1.2.1
Platform:Android
OS specifics: Android 9

## Steps to reproduce

1. Create a note
2. Input or paste a line of Chinese sentences
3. Enter a new line similar to "--------"(Quotation marks are not included)
4. Will be displayed "Can't find variable:btoa"(Quotation marks are not included)

## Describe what you expected to happen

It can display normally
@laurent22

**Comment by hexclover** [comment]
Hello, I can replicate this with:

```markdown
## 😀
```

Can this be related to <https://github.com/laurent22/joplin/commit/26ac7454198855c05b99d92670d06b481a96b072>?

**Comment by z49x2vmq** [comment]
> Hello, I can replicate this with:
> 
> ```gfm
> ## 😀
> ```
> 
> Can this be related to [26ac745](https://github.com/laurent22/joplin/commit/26ac7454198855c05b99d92670d06b481a96b072)?

Hello,

This is reproducible with '##'

Android 10
Joplin 1.2.5

**Comment by Sigma911** [comment]
Me too.  Android 9, Joplin 1.2.5

**Comment by rankaiyx** [comment]
> Hello, I can replicate this with:
> 
> ```gfm
> ## 😀
> ```
> 
> Can this be related to [26ac745](https://github.com/laurent22/joplin/commit/26ac7454198855c05b99d92670d06b481a96b072)?



> > Hello, I can replicate this with:
> > ```
> > ## 😀
> > ```
> > 
> > 
> > Can this be related to [26ac745](https://github.com/laurent22/joplin/commit/26ac7454198855c05b99d92670d06b481a96b072)?
> 
> Hello,
> 
> This is reproducible with '##'
> 
> Android 10
> Joplin 1.2.5



> Me too. Android 9, Joplin 1.2.5

I don't know why laurent22  removed the bug tag

**Comment by rexzhang** [comment]
Me too, iOS 14, Joplin 10.2.0

**Comment by jtfrom9** [comment]
Me too. Android 11, Joplin 1.2.5

**Comment by jtfrom9** [comment]
1.1.2 no problem
https://github.com/laurent22/joplin-android/releases

**Comment by kikoqiu** [comment]
`## 中文` , too.

**Comment by laurent22** [comment]
I've probably removed the tag because there's not enough details to replicate the bug. Could someone paste an example of Markdown note that would show the problem? A screenshot might help too.

**Comment by rankaiyx** [comment]
Screenshot has been added.
It's not just Chinese. It seems that SBC cases are like this.
such as Japanese and Korean
such as   "？"    "《》"

**Comment by rankaiyx** [comment]
> I've probably removed the tag because there's not enough details to replicate the bug. Could someone paste an example of Markdown note that would show the problem? A screenshot might help too.

Screenshot has been added.
It's not just Chinese. It seems that SBC cases are like this.
such as Japanese and Korean
such as "？" "《》"

**Comment by barro350** [comment]
As @hexclover mentioned, [slug](https://github.com/Trott/slug/search?q=btoa) is emitting the error. The relevant code in that package is:

```js
base64 = function (input) {
  return btoa(unescape(encodeURIComponent(input)))
}
```

**Comment by rankaiyx** [comment]
It's not about language
The first line is abc
The second line is #
It can be reproduced

**Comment by laurent22** [comment]
Patch submitted upstream: https://github.com/Trott/slug/pull/120

**Comment by laurent22** [comment]
For those who are having this issue, please could you give a try to this release and let me know if it works? https://github.com/laurent22/joplin-android/releases/tag/android-v1.2.6

**Comment by rankaiyx** [comment]
> 对于那些遇到此问题的人，请尝试一下此版本，让我知道它是否有效吗？https://github.com/laurent22/joplin-android/releases/tag/android-v1.2.6

The problem has been solved, but it seems that the performance has been reduced a lot, including the journal that has no problem before, and even the app will be blank for a period of time when it starts

> For those who are having this issue, please could you give a try to this release and let me know if it works? https://github.com/laurent22/joplin-android/releases/tag/android-v1.2.6

The problem has been solved, but it seems that the performance has been reduced a lot, including the notes that has no problem before, and even the app will be blank for a period of time when it starts.

**Comment by rankaiyx** [comment]
Sorry, the performance problem seems to be caused by only 1% of my battery. Now there is no problem.

**Comment by laurent22** [comment]
Perfect, thanks for checking.
