### ISSUE TITLE
Editor font size doesn't change

### ISSUE THREAD

**Issue by KarelVO** [laurent22/joplin#3816]
Changing the editor font size in options > appearance doesn't do anything - the font stays the same size (I'm guessing 10 or 12 - either way very small).

## Environment

Joplin version: 1.2.2
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Change editor font size
2. See that it doesn't change in size

## Describe what you expected to happen

I expect the font size to have the size according to the one I specify in the appearance tab

**Comment by cat-in-a-box** [comment]
Encountered the same issue, can confirm. Does not matter which font you use - font size still stays the same

**Comment by laurent22** [comment]
Will be fixed in next release, thanks for reporting
