### ISSUE TITLE
Highlighted search term stays that way even after search is cancelled

### ISSUE THREAD

**Issue by n00b12345** [laurent22/joplin#3819]
## Environment

Joplin version: 1.1.4
Platform: macOS
OS specifics: 10.14.4

## Steps to reproduce

1. Search for a term
2. The results show up as highlighted terms in the notes
3. Cancel or end the search by clicking on the "X" button in the search bar
4. Highlighted search terms in the notes cannot be removed

## Describe what you expected to happen

Selected search terms should no longer be highlighted in the notes once the "X" button is clicked in the search bar.

**Comment by CalebJohn** [comment]
Hi! This was fixed in #3717 and will be working in the next release.
