### ISSUE TITLE
[Feature Request] Search inside a note

### ISSUE THREAD

**Issue by miwie** [laurent22/joplin#382]
### Operating system

- Android

### Application

- Mobile

I'd like to be able to search **inside** a note.

**Comment by gradinaruvasile** [comment]
+1 for all platforms. I have long notes and searching them is very handy.

**Comment by ComputingFroggy** [comment]
+1

**Comment by dbethke** [comment]
+1.
I'm surprised this feature is somehow not already included. The current search only half as useful as it should be. 
When I search, it filters my list of notes to just the notes containing the word, but it doesn't highlight the word?! I have to manually scan through the doc to find where it was used inside the doc.

**Comment by ClaudiusCluever** [comment]
+1

**Comment by Duke-Igthorn** [comment]
+1

**Comment by nicolasdejong** [comment]
Search now shows what notes contain the text. What is missing is:

- Found text is highlighted, but only in the viewer-layout, not in the editor layout. I only use the editor layout, so it took me a while to figure this out.
- The search does not scroll to the first found highlight. So you have to scroll manually to find where the highlights are.

I'm quite surprised that this basic functionality is not in, like it is in any other text-editor. Perhaps my needs don't overlap with Joplin's features. I haven't used OneNote, so perhaps it is the same there.

**Comment by laurent22** [comment]
Perhaps the way Thunderbird does search within an email could be replicated.

**Comment by subi54** [comment]
+1, useful for longer notes.

**Comment by ComputingFroggy** [comment]
Why is this closed ?

**Comment by altsalt** [comment]
I was searching for an issue related to my particular [FR] and this seems the nearest.

Could we allow searching within the MD itself? For instance, I often want to see if I have a duplicate URL, but the search is looking at the rendered panel.

Thanks!

**Comment by Pilastr** [comment]
Appreciative thanks to any collaborators who can speak to likelihood/timelines for this feature.

This basic functionality is now so stale it has to be tagged #mouldering. How I can be looking at a screeen of editable text, but deprived of an essential function like simple search? Is it somehow super difficult to implement, such that it's really time for those who require it to abandon Joplin? I've hung on this long but unsearchable notes is, for me, a dealbreaker.

**Comment by danielb2** [comment]
I'd like to hear something about this too. It makes using the android app a total chore. Is this because the developers are not using the android app?

**Comment by laurent22** [comment]
This has been implemented
