### ISSUE TITLE
Search results keep resetting note view

### ISSUE THREAD

**Issue by AaronOldenburg** [laurent22/joplin#3820]
This is similar to bug reports #3819 & 3802, and the solution to them might partially solve this, but not totally.

I perform a search in the search bar and choose one of the relevant documents. The text I search for is highlighted at the top of the document. I go to the bottom of the document and begin typing, and after a few seconds it jerks the view back up to where the text is highlighted. I type some more and the view moves back down, but is jerked back up at regular intervals.

There appears to be an auto-focus on the search text. I can see the utility of this when you first open the note, but I don't think it should essentially lock you to the search text after you've begun navigating the document.

Interestingly, it only happens while I'm typing or making other changes to the document, like pasting, not when scrolling with the mouse.

And of course, once we're able to clear the search, I imagine that will free us from this issue, but it would be nice to be able to leave the text highlighted and not have to be jerked back to it over and over as well.

## Environment

Joplin version: 1.1.4.
Platform: Linux
OS specifics: Manjaro, Plasma 5.19.5, Kernel 5.8.6-1

## Steps to reproduce

1. Search for a note. Make sure it's a relatively long note and the search term is found near the top.
2. Scroll down to the bottom of the document.
3. Begin typing.

## Describe what you expected to happen

Stays focused where I'm typing.

**Comment by CalebJohn** [comment]
Hi @AaronOldenburg 

Thank you for the detailed report.

This was fixed in #3787 and will be working properly in the next release.
