### ISSUE TITLE
Upgrading to 1.1.4 breaks some syntax highlighting in the editor view

### ISSUE THREAD

**Issue by millerj** [laurent22/joplin#3821]
## Environment

Joplin version: 1.1.4
Platform: Mac OS
OS specifics: Catalina/10.15.6

## Steps to reproduce

1. Create a note
2. Paste in this text: 
```
## foo

<foo><bar>
<foo><bar>

## bar
```
3. Observe in the editor view that `## foo` is higlighted but `## bar` is not.

## Describe what you expected to happen
I have some notes that use the structure in the example I gave in "steps to reproduce" (I simplified it quite a bit, but the issue still applies). Prior to upgrading to 1.1.4, both H2 headings (## foo and ## bar) were syntax highlighted in the editor view. After Upgrading to 1.1.4 the second H2 heading (## bar) is no longer syntax higlighted in the editor view.

**Comment by laurent22** [comment]
It’s invalid html markup so I don’t think this is a bug.

**Comment by millerj** [comment]
It wasn't meant to be html. I encountered this in documentation for another project. The actual text (which I abbreviated in the initial report) was this:
```
* To monitor a shared network drive, enter the path manually:
	* Linux: <host>/<path>
	* Windows: \\<host>\<path>
```
Prior to 1.1.4, this was in a note and didn't cause any problem, but after upgrading to 1.1.4, the rest of the note following this portion lost syntax highlighting in the editor view. Perhaps you can try pasting this into the middle of a note and see what happens to the syntax highlighting below it? Thanks for looking!

**Comment by laurent22** [comment]
Ok I see what you mean. The issue is that Markdown syntax highlighting has been changed in the new release and it highlights HTML code differently too. In that particular note, the `<host>` and `<path>` look like HTML, although they are not, and as a result get highlighted in an invalid way.

One way to fix this is to put spaces around the `<` `>` as in `< host >` so that it's no longer HTML code, or to put backticks around the paths, as in:

![image](https://user-images.githubusercontent.com/1285584/94115245-59bb5500-fe41-11ea-8709-b4c6cb3ddd73.png)

**Comment by diver-down** [comment]
I've found another case of broken syntax highlighting, with v. 1.1.4:  Code blocks don't highlight in the editor view when combined with bullet points of any level.

Using _Nord_ theme in this screenshot. You can see how the code blocks outside of bullet points are highlighted in editor view, and not highlighted inside bullet points (but they all work nicely in proof/read view):

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/35608185/95003200-e3d68c80-05aa-11eb-8220-0e6ef9374f17.png">

- - -

```
Joplin for Desktop

Copyright © 2016-2020 Laurent Cozic
Joplin 1.1.4 (prod, darwin)

Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: 9610b7e (master)
```

**Comment by millerj** [comment]
laurent22's suggestion to put backticks is a reasonable fix for me for the issue I initially posted about. The behavior is still different from earlier versions, but I'll leave it to you as to whether you consider this a bug or not. Thanks for your attention on this issue and for Joplin in general!
