### ISSUE TITLE
Make uninstall script and enable changing install location, for linux

### ISSUE THREAD

**Issue by coughingmouse** [laurent22/joplin#3824]
The issue of uninstalling script was first mentioned [here](https://github.com/laurent22/joplin/issues/1736), but I felt the need to ask again.

As far as I know as a user, Joplin on linux is not a traditionally proper install but rather simply just an appimage. Even with the official install you get an appimage with a desktop file. This not only means it will not be getting updates by package manager but also that it lacks a proper uninstall method.

In case of having downloaded just the appimage, you only need to erase the appimage file and the folder at
~/.config/joplin-desktop

But in the case of the official install, at least
~/.joplin, where the appimage is
~/.config/joplin-desktop, where configuration is (and maybe data too? I haven't checked)
~/.local/share/applications/appimagekit-joplin.desktop, where the desktop file is
~/.local/share/icons/hicolor/512x512/apps/joplin.png, where the icon (png) for the desktop file is
need to be uninstalled.

As Joplin installs through a rather peculiar approach, including where it installs into, when it comes to uninstalling these locations are rather unintuitive for inexperienced regular users like myself, especially the desktop icon. This is why I suggest making an uninstalling script.

It's also related to the issue of enabling install location. As far as I'm concerned, ~/.joplin seems like an odd place to get it installed. Non-standard executables on linux are to be installed on /opt (like is suggested when installing [Zotero](https://www.zotero.org/support/installation)). I guess it may also be installed for a single user by being installed on ${HOME}/Applications/, although I don't think this is a very common location either. To be fair, it would be nice if choice of install location were to be given.

I personally would not mind other user and prefer to install on /opt because I'm running it on a personal laptop. I believe most users would be in the same situation, although their preferences may vary.

Speaking of preferences, it would be nice if the [install script](https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh) included a symbolic link for instance to /usr/local/bin so that Joplin can be opened from the terminal. There are Desktop Environment users without the usual desktop like on Qubes OS so the desktop file may be useless.

All in all, none of this would be necessary if Joplin were to be installed by a package manager (or more) or at least by snap. I wish it gets ported one day.

**Comment by riveravaldez** [comment]
Even better than snap: flatpak (flathub).
Thanks a lot.

**Comment by Hellboy913** [comment]
> But in the case of the official install, at least
> ~/.joplin, where the appimage is
> ~/.config/joplin-desktop, where configuration is (and maybe data too? I haven't checked)
> ~/.local/share/applications/appimagekit-joplin.desktop, where the desktop file is
> ~/.local/share/icons/hicolor/512x512/apps/joplin.png, where the icon (png) for the desktop file is
> need to be uninstalled.

Thanks for this.
Really helped out.
