### ISSUE TITLE
Search in All Notes <escape> not working anymore

### ISSUE THREAD

**Issue by ipentest** [laurent22/joplin#3826]
## Environment

Joplin version: 1.2.2 prod
Platform: Mac OS 10.15.6
OS specifics: Catalina

Thanks a lot for the awesome product

**Comment by ipentest** [comment]
When I opened this bug to read once again, I thought I had not given enough details, so writing it here: Steps to reproduce:

1. In Joplin go to any notebook and note or todo
2. Press Command+Shift+F or go to Edit > Search in all notes
3. Enter any value to search
4. Press <Escape> key
Current behavior: Nothing happens
Desired behavior: The field should be emptied so that we can search for a new term
This was working fine in 1.1.x but 1.2.2 seems to have an issue with this functionality

Hope this helps. Keep up the great work

**Comment by eduardokimmel** [comment]
I think its the same bug so I'll comment here.

When I global search for something I can't 'unsearch', the words get highlighted and keep highlighted after I click on the 'X', clear the search or press escape.

Joplin version: 1.1.4 Desktop
Platform: Linux AppImage

**Comment by pcwii** [comment]
Confirmed same issue with me.

Joplin for Desktop
Joplin 1.1.4 (prod, win32)
Revision: 9610b7e6 (master)

**Comment by vorpleblade** [comment]
Confirmed same issue.
Joplin for Desktop
Joplin 1.1.4 (prod, darwin)
Revision: 9610b7e (master)

**Comment by ardhill** [comment]
Same Issue here:
Clear the search field and previous searched word is still highlighted in the text and the page keeps trying to jump to the highlighted word - a right pain when you are trying to type notes. Corrected by closing down and re-starting.

```
Joplin for Desktop
Copyright © 2016-2020 Laurent Cozic
Joplin 1.1.4 (prod, linux)
Client ID: 169e8b97f37440e3be0b88c37aa945ba
Sync Version: 2
Profile Version: 34
Keychain Supported: No
Revision: 9610b7e (master) 
```
