### ISSUE TITLE
Persistent error message "Some items cannot be synchronized".

### ISSUE THREAD

**Issue by renaldofreire** [laurent22/joplin#3828]
## Environment

Joplin version: 1.1.4-1-x86_64
Platform: Linux
OS specifics: Arch Linux x86_64
DE: Gnome

## Steps to reproduce

1. Sync all notes;
2. Then I decrypt all notes;
3. Persistent error message "Some items cannot be synchronized";

## Describe what you expected to happen
The message has been understood, but I cannot remove it.

## Screenshot

![error_02](https://user-images.githubusercontent.com/35435780/94210960-91101d00-fea6-11ea-88e5-8def6efecea8.png)
![error_01](https://user-images.githubusercontent.com/35435780/94210965-92d9e080-fea6-11ea-8b19-53e3b933d6ae.png)

**Comment by hello-sea** [comment]
I encountered the same problem.

**Comment by trinenine** [comment]
I'm currently experiencing this error. 
I have resolved all conflicts to zero.
![Error - 2021-04-23](https://user-images.githubusercontent.com/8539445/115907466-ea3d3080-a436-11eb-93ee-db272767b0fb.png)
![Error-detail](https://user-images.githubusercontent.com/8539445/115907488-f1643e80-a436-11eb-9cd6-55e15859c6ed.png)


Joplin v 1.7.11 on  Mac OS 10.14.6

**Comment by gavinr** [comment]
I'm getting the same error. Same issue. Any way to resolve this?

**Comment by majidasgari** [comment]
I found just one solution for it (as a user of the application, not a programmer). Write down the name of the problematic resources. Close the Joplin. Then open the remote location (e.g. Dropbox) and delete all the files from `.resource` folder. Then go to local `~/.conf/joplin-desktop/resources` folder and remove corresponding files from it. Then open `~/.conf/joplin-desktop/database.sqlite` and go to `resources` table and remove all problematic rows. Open the Joplin and click on synchronize button. Obviously in this solution you will miss all the data where contained in the deleted files !!

**Comment by bbervel** [comment]
It is not the right way. Problem is actual - files more then 10mb have problems with sync
