### ISSUE TITLE
Seafile sync dav on android mobile

### ISSUE THREAD

**Issue by ludwigvon100** [laurent22/joplin#383]
### Operating system

- Android

### Application

- Mobile

Hi,

I have a self hosted "Seafile" server running on a RaspberryPi.
I succeeded in syncing my Desktop Joplin app on both computers (Mac and Linux) with the "Webdav" option, but my Mobile Joplin app on my android phone is unable to log in to my webdav 
Seafile account…
Here is the message:

_Error: Please check the URL, username, password, etc. are correct and that the sync target is accessible. The reported error was:
**Network request failed**_

Here is the debug log on the phone:
![joplin debug](https://user-images.githubusercontent.com/38143435/38443191-d9fc5372-39b8-11e8-946e-4633b3f97003.jpg)
I checked several times URL, login and password, and I tried to connect via webdav from the phone through Firefox succesfully. I also have the seafile client working on the phone.
Any idea on what may cause this error?!…

For information, I also succeeded in another webdav connection with the Mobile Joplin app with my "https://www.netcourrier.com/" mailing account, so I think the connection should also work with my Seafile Server?!…

**Comment by laurent22** [comment]
Is there something special about the server such as non standard port or self signed certificate ?

**Comment by ludwigvon100** [comment]
No, the server is running on standard port 443 (https) via nginx as described on their documentation.

https://sea.couleurscaraibes.fr

**Comment by laurent22** [comment]
Hmm, I cannot replicate this in Android. It's just working for me.

**Comment by laurent22** [comment]
Closing for now as cannot replicate. Feel free to comment here with more info if it's still happening.
