### ISSUE TITLE
Joplin crashes when using external editor gvim

### ISSUE THREAD

**Issue by cfair-beckman** [laurent22/joplin#3831]
Whenever I use an external editor (gvim) and I save and exit I get a white screen briefly where the editor was and then joplin crashes.

## Environment
Revision: f11b13a (master)
Joplin version: 1.1.4 
Platform: Linux
OS specifics: Manjaro

## Steps to reproduce

1. Create note
2. Edit the note with gvim (8.2) from the external editor option
3. :wq to exit

## Describe what you expected to happen
This worked perfectly well at first so my expected effect was for the changes I made to be incorporated into the note without crashing the app

**Comment by laurent22** [comment]
Any log? https://joplinapp.org/debugging

**Comment by cfair-beckman** [comment]
I updated to the most recent version and it is good to go.   I only saw it in version 1.0.4

________________________________
