### ISSUE TITLE
Android app configuration directory not deleted upon "clear all data" and app deletion

### ISSUE THREAD

**Issue by maltokyo** [laurent22/joplin#3833]
In android I can't figure out how to reset Joplin to a clean slate. 

When I "clear all data" and delete the app and reinstall it, the settings (sync etc) are still as I'd set them before and not the default (Dropbox). 

How to reset everything including settings on Android ?

**Comment by JackGruber** [comment]
When you youse the "clear all data" from the android apps setting. Then Joplin is reset to the default.
The syncronisation target "Dropbox" is the default after the reset. But sync is not workin, because no valid oAuth token for Dropbox.

**Comment by maltokyo** [comment]
Hi @JackGruber actually that's the behaviour I want!!! I want to reset everything. 

What actually happens is that my WebDAV config remains in the settings and old encryption keys that I don't want remain too. 

How to delete it all and start fresh? My device does NOT behave as you mentioned and that's the issue. Thanks!

**Comment by JackGruber** [comment]
Hm ... I have testet it actualy on one of my android phones and all my settings are gone. Also my WebDav settings.

**Comment by maltokyo** [comment]
OK, I have found the solution.  Let me paste it here for other users.

So, long press on the app icon and then "clear all data" does NOT work.

You have to do this:
https://discourse.joplinapp.org/t/how-to-delete-the-android-app-completely-with-data/1131/9

That worked for me.  Seems like the long press option should work also.
