### ISSUE TITLE
Search hits are not highlighted (Joplin-Android)

### ISSUE THREAD

**Issue by feensucher** [laurent22/joplin#3834]
## Environment

Joplin version: joplin-v1.1.2
Platform: Android 10
OS specifics: Huawei P30 Pro

## Steps to reproduce

1. 
2. 
3. 

## Describe what you expected to happen

Unfortunately, the Android version of Joplin
Search hits are no longer visually highlighted.
I tried it on different devices - and also with all "topics" that are available in Jolin.
The last version where I am aware that it worked was joplin-v1.0.333
Unfortunately the downgrade is with an older version of Joplin Android. Tried - but refused. So I don't add any comparative screenshots
Do you have a solution?
Thank you, Wolfgang

## Logfile
[syncReport-1601114472049.txt](https://github.com/laurent22/joplin/files/5286500/syncReport-1601114472049.txt)
![screenshot_search](https://user-images.githubusercontent.com/66973751/94338434-75199200-fff2-11ea-8a32-7ad74049f789.jpg)
![screenshot_search2](https://user-images.githubusercontent.com/66973751/94338436-75b22880-fff2-11ea-8621-c72ad8881e74.jpg)
![screenshot_search3](https://user-images.githubusercontent.com/66973751/94338438-76e35580-fff2-11ea-95b1-63a43304bc5c.jpg)

**Comment by laurent22** [comment]
@CalebJohn, I wonder if that was remove in the CodeMirror update, since some of the code is shared with mobile, and if it is do you know if it’s easy to restore the feature?

**Comment by CalebJohn** [comment]
@laurent22 In terms of highlighting the codemirror changes only touched files in `ElectronClient/gui` and didn't remove the highlighting completely. I suspect this was added somewhere else, but I'm not sure where.

**Comment by laurent22** [comment]
OK thanks for letting me know. It could be related to the search changes too, I’ll take a look.

**Comment by laurent22** [comment]
That was indeed due to the fuzzy search update, and will be fixed in v1.2
