### ISSUE TITLE
numbered list in descending order shows ascending order in preview panel

### ISSUE THREAD

**Issue by Tycholiz** [laurent22/joplin#3837]
![image](https://user-images.githubusercontent.com/39745457/94355761-beda9a80-003b-11eb-8865-55284a32022e.png)
As we can see from the image, creating an ordered list that descends will be misinterpreted and will instead ascend.

This bug does not particularly bother me. I'm just being a good citizen and reporting it's occurrence. Feel free to do whatever is best with this issue.

## Environment

Joplin version: 1.0.227
Platform: OSX
OS specifics: Catalina

**Comment by rahil1304** [comment]
Hey, is anybody working on this issue or can I take it up?
