### ISSUE TITLE
Grid View to take Quick Glances for Notes

### ISSUE THREAD

**Issue by RuthlessRuler** [laurent22/joplin#3838]
I think a Grid View would be nice, especially on Mobile, as it looks a bit bland. Plus it gives a quick overview of the contents of the Notes, so you dont have to open and close them all the times. 

This feature is already there in many Notes Apps: Keep and etc, and should be a nice addition to this App!

**Comment by RuthlessRuler** [comment]
Not Solved

**Comment by payrim** [comment]
uh, i very much like a grid-view plugin like [Trilium](https://github.com/zadam/trilium)
