### ISSUE TITLE
search term highlights not cancelled

### ISSUE THREAD

**Issue by TeresaM12** [laurent22/joplin#3840]
After searching for a term and cancel it (e.g. using the cross next to the search box), the highlight from the former search are still visible.

## Environment
Joplin version: Desktop 1.1.4 (prod, darwin or win)
Platform: mac or win
OS specifics: MacOS 10.15, Win 10

## Steps to reproduce

1. search for a word such as `joplin` 
2. word is highlighted in all documents which contain the word
3. empty the search box or press the cross to delete its content 
4. even though no note selection is active anymore the highlights stay on in the notes

## Describe what you expected to happen

If there is no active search there should be no highlights from a former search

However I would consider it a feature to have the ability to tick a box somewhere to keep the highlights and allow (different colored) highlights for the next search.

**Comment by CalebJohn** [comment]
Thanks for the bug report, however this one has already been reported in
