### ISSUE TITLE
search highlights only first instance in code view in Win version

### ISSUE THREAD

**Issue by TeresaM12** [laurent22/joplin#3841]
When searching for a word  only the first occurrence of the word is highlighted (in WYSIWYG word is highlighted in the whole note).

## Environment

Joplin version: desktop 1.1.4
Platform: win
OS specifics: 10

## Steps to reproduce

1. search for a word in all notes
2. in the code view only the first time the word occurs a highlight is visible 

## Describe what you expected to happen

if something is highlighted in code view (yes there should be in my opinion) then all occurrences. In the mac version this is the case.

**Comment by CalebJohn** [comment]
Hi @TeresaM12 

You are correct this is a bug that was recently introduced. I went into detail about it [on the forum](https://discourse.joplinapp.org/t/bug-joplin-1-1-4-unable-to-edit-a-note-found-after-a-search/11157/5?u=calebjohn) so if you have any suggestions for a nice way to handle this, let me know!

**Comment by TeresaM12** [comment]
Ah I see. What I do not understand is why the fuzzy search of the MacOS desktop does not have the same problem. Something like just highlighting was possible in Firefox or Multi-highlight plugin for Chrome, but I have no idea, how it is implemented.

But what I mean is a bit different (an on page multi color highlight like a permanent highlighter for some words):
1. search for one word or phrase e.g I search for "a word" then only the complete phrase is highlighted
2. now I lock this highlight (good would also be the bar at the side indicating the places the word was found - at the moment it is the scrollbar)  
3. search for another word and highlight this one as well + add the highlight color to the scrollbar area (I would even prefer to make it wider to have the second color next to the first one)

The only solution I have for this problem would be something like different search boxes for different colors of search highlighters. It might not be useful to use this search to identify notes (this could still be done with the "normal" search box) but to search within the notes. `Liquid text` has something like that but only for the highlights marked by myself + one additional search.
If I have a page (or even several pages) with `joplin` and `markdown` and `export` I will often search for the place in the note where those three words are close together. I would find that easier to handle than a regex search because it is easier to construct and I might even remember the "image" of highlights for the window size I use.  To be able to put into each of the highlight (search) boxes a regex would be the cherry on the cake. 
Sorry that I now combined a bug report with a feature request. If this is also interesting for others I would put it into a feature request.

**Comment by laurent22** [comment]
@CalebJohn, there's a good chance we're going to remove support for fuzzy search due to the performance issues. So I believe that should fix that bug too?

**Comment by CalebJohn** [comment]
@laurent22 yes, it would fix this bug as well.

**Comment by laurent22** [comment]
Ok thanks for confirming. Let's close the issue then as I've now disabled fuzzy search. The fix will be in v1.2
