### ISSUE TITLE
Note (markdown) editor regression

### ISSUE THREAD

**Issue by zor-el** [laurent22/joplin#3842]
Hi guys.

I've been quite enthusiastic about Joplin for some time, and I really enjoyed the powerful markdown code editor. Thanks for the great work! 👍 

I'd like to bring to your attention though that version 1.1 has almost completely diminished my markdown code editing experience. 😞 

Before 1.1 (i.e. up to 1.0.245) all of the power key bindings in the markdown editor (like _duplicate line_, _select next occurrence_, _column cursor_, to name just a few) are gone.

I suppose those were built in into the ACE editor, and the switch to CodeMirror - proverbially "threw out the baby with the bath water".

I'd like to suggest to get the power key bindings  back in, or at least provide equivalent alternatives, in order to keep markdown editing actually usable. (Imagine converting bullet lists to task lists in markdown without multiple cursors...)

Thanks for considering this.

**Comment by CalebJohn** [comment]
You can see an explanation [here](https://discourse.joplinapp.org/t/ctrl-d-doesnt-work-in-code-mirror/11305)

Something that would be helpful from you would be if you could explicitly state what functions you're missing and what key combos trigger them. 

The problem that we were facing prior to this update is that ace editor supported a large number of key combos that weren't necessarily well documented, and from the Joplin side they weren't documented at all. This mostly meant accidentally upsetting users who depended on certain functionality that we didn't know about (this issue is sort of an example of that). 

Part of the change to codemirror was a transition from supporting a large number of undocumented key combos to only explicitly supporting a small number. From here we need help from people like you to actually tell us what you need and why.

**Comment by zor-el** [comment]
> Something that would be helpful from you would be if you could explicitly state what functions you're missing and what key combos trigger them. [...] The problem that we were facing prior to this update is that ace editor supported a large number of key combos that weren't necessarily well documented.

To me they were documented just fine [here](https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts), and I've been using most of them, the **multicursor**, **copy/move lines up/down** and **duplicate selection** in particular.

> Part of the change to codemirror was a transition from supporting a large number of undocumented key combos to only explicitly supporting a small number.

That by definition is a regression (something that worked stopped working accidentally) and breaking change. It broke the editing experience for users who did know how to use those advanced editing features (like myself). I'm not sure you guys are following semantic versioning, but a breaking change would have called for a 2.x, not a 1.1. It was unexpected to say the least. 

For an actual smooth transition. perhaps better to announce such breaking changes explicitly in advance and offer a sufficiently long "experimentation/grace period" with a kind of a user-settable feature toggle? As it stands, I had to roll back and pin my Joplin app to get my editing experience back.

> You can see an explanation [here](https://discourse.joplinapp.org/t/ctrl-d-doesnt-work-in-code-mirror/11305/2)

Uhm... one user's issue with the Mac's keyboard doesn't strike me as much of an explanation, even less as a good reason, for a breaking change like this. 😉 

Sorry if I'm coming across as nitpicking or something. After years of jumping from note app to note app b/c they were all lacking something, Joplin has been the one app of which I really really loved where it was going. So if I'm nitpicking, it's only out of love and care. 😍 😀

**Comment by CalebJohn** [comment]
> To me they were documented just fine here.

Documented by the Joplin project I meant.

> For an actual smooth transition. perhaps better to announce such breaking changes explicitly in advance and offer a sufficiently long "experimentation/grace period" with a kind of a user-settable feature toggle? As it stands, I had to roll back and pin my Joplin app to get my editing experience back.

[Announced on the forum](https://discourse.joplinapp.org/t/new-editor-editable-attachments-dark-mode-support-and-more-in-latest-pre-release/9251) over 3 months ago with a friendly toggle . [Announced](https://discourse.joplinapp.org/t/roadmap/10897) that the it would become default 3 weeks ago.

> Uhm... one user's issue with the Mac's keyboard doesn't strike me as much of an explanation, even less as a good reason, for a breaking change like this

I linked my response which included a brief description of the change to Codemirror.

> Sorry if I'm coming across as nitpicking or something

Actually, your last response came across as rude. Please try to have a bit of compassion and perspective in the future.

> multicursor, copy/move lines up/down and duplicate selection

Can you please be specific about which key combos you use? It won't be possible to copy over every keybinding from ace editor, but I'll try to copy over some of the ones you actually need.

**Comment by zor-el** [comment]
> Actually, your last response came across as rude. Please try to have a bit of compassion and perspective in the future.

Sorry you felt that way. Not intended at all. And apparently the smileys didn't help much either. (Speaking of compassion and perspective though, if actions speak louder than words, breaking users' editing experience hasn't been that considerate and empathetic either. Just saying. 😉  <<< wink smiley here)

> Announced on the forum over 3 months ago with a friendly toggle . Announced that the it would become default 3 weeks ago.

What I meant was that the _breaking nature of change_ hasn't been pointed out at all. IMO there was no way to conclude from those posts the switch would break stuff.

> Can you please be specific about which key combos you use? It won't be possible to copy over every keybinding from ace editor, but I'll try to copy over some of the ones you actually need.

The ones I mentioned particularly would be a very good start. See the [table entries on ACE's page](https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts). It's the entire _Multicursor_ table, Line 2-4 in the _Line Operations_ table, and _Duplicate selection_ in the _Selection_ table.

**Comment by CalebJohn** [comment]
@zor-el I'm sorry if I came across as dismissive or trying to downplay what I know was a frustrating change for you. I really do want to improve the editor and make it the best possible for all users. However, I really don't appreciate the way you're communicating with me, specifically unnecessary comments like this

> (Speaking of compassion and perspective though, if actions speak louder than words, breaking users' editing experience hasn't been that considerate and empathetic either. Just saying. 😉 <<< wink smiley here)

With that said, I will be turning off notifications for this issue and I won't reply anymore. 
Not to worry though, I'm just a random contributor to Joplin. Hopefully someone else with more patience will pick this up.

**Comment by laurent22** [comment]
I think there's not much to add here, and a bit more respect for the work of others would be welcome. @CalebJohn has been continuously improving the CodeMirror editor and we got a lot out of the great work he's done.

To be clear, this is not a regression. Not only the Ace Editor shortcuts were not supported, but they were **explicitly not supported**, as had been stated in the forum a few times (and as the lack of documentation should make clear). Whether we should start supporting certain shortcuts is another discussion better suited for the forum.
