### ISSUE TITLE
joplin 10.1.0 ios 14.0.1 fails to sync on WebDav connection Nextcloud

### ISSUE THREAD

**Issue by mschindl** [laurent22/joplin#3843]
macOS Joplin syncs to Nextcloud and it works well.
iOS can't sync, because of following error:

![1015 1](https://user-images.githubusercontent.com/26382876/94408968-cdc56800-0175-11eb-9537-860ac103da62.PNG)

## Environment

Joplin version: 10.1.0
Platform: iOS 14.0.1
OS specifics: Nextcloud 19.0.3

## Steps to reproduce
iPadOS will be tested soon.

## Describe what you expected to happen
iOS syncs the content which macOS uploaded to Nextcloud.

## Logfile
Can't get it from iOS.

Any ideas?

**Comment by laurent22** [comment]
I have been trying to replicate this bug a few times but I cannot. By any chance would you be able to create a test user on your server that I could use to replicate and fix this problem?

**Comment by mschindl** [comment]
I can't explain it, but after retry it works now. Strange...

Thank you for your offer and fast response!
