### ISSUE TITLE
joplin config locale fails

### ISSUE THREAD

**Issue by dbogdanov** [laurent22/joplin#3847]
Running `joplin config locale en_US` fails with the following message:

```
app(...).onLocaleChanged is not a function
```

## Environment

Joplin version: joplin 1.0.164 (prod)
Platform: macOS 
OS specifics: 10.15.4 

## Steps to reproduce

1. `joplin config locale en_US`
2. See the error output

## Describe what you expected to happen
Locale should successfully switch to the new value.

**Comment by laurent22** [comment]
I guess few people ever change the locale as it looks like this code has never worked for several years and it's the first it's reported :) It should be fixed in the next release.
