### ISSUE TITLE
element.style overriding userchrome.css

### ISSUE THREAD

**Issue by elsiehupp** [laurent22/joplin#3848]
## Environment

Joplin version: Joplin 1.1.4 (prod, darwin)
Platform: macOS
OS specifics: 11.0 Beta (20A5374i)

## Steps to reproduce

1. Using the button in Joplin preferences, edit `userchrome.css`. In my case I am removing borders for all `div`, `input`, and `a` tags.
2. Save `userchrome.css` and relaunch Joplin.
3. Toggle development mode and select, for instance, the note-title field.
4. See that `<input style="...">` has precedence over `userchrome.css`. It would seem that any CSS styles specified directly in the HTML cannot be modified. (See screenshot)

## Describe what you expected to happen

I expected to actually be able to modify the style of the application chrome using `userchrome.css`.

## Logfile

I don't think this is applicable here, but I can get one if necessary, I guess. I have attached a screenshot instead.

## Screenshot

<img width="336" alt="Screen Shot 2020-09-29 at 3 59 12 PM" src="https://user-images.githubusercontent.com/9206310/94610217-ee70e900-026d-11eb-8094-d398d212615b.png">

**Comment by CalebJohn** [comment]
@elsiehupp you can use the `!important` specifyer to overrule element.style

[Here](https://css-tricks.com/when-using-important-is-the-right-choice/) is an article that will show you how to use it. It will also go into a detailed discussion of when to use it, but you don't need to read that far.

Please close this issue if that solves it for you. Otherwise let me know and I'll try to help further.

**Comment by elsiehupp** [comment]
Thanks. This seems to do it (as an extremely preliminary starting point), and it makes the interface appear much, much more modern:

> div, input, a {
> 	border: 0px !important;
> }

It may be worth adding this tip to the "[Custom CSS](https://github.com/laurent22/joplin/blob/dev/README.md#custom-css)" section of the main [README.md](url). I don't have enough experience with GitHub to know how to do that myself. Is that something you would be able to do?

**Comment by CalebJohn** [comment]
There is a [wiki page](https://discourse.joplinapp.org/t/joplin-customization/11195) for css tweaks. I'll add a link in the README to help make it discoverable, thanks for the suggestion.

There is also a thread for [sharing customization](https://discourse.joplinapp.org/t/share-your-css/1730/110).

Before you go too far down the rabbit hole of customization I should point out that the [current pre-release](https://discourse.joplinapp.org/t/pre-release-1-2-is-available-for-testing/11207) includes an overhaul of the Joplin interface. So stay tuned for that.
![image](https://user-images.githubusercontent.com/2179547/94623577-bbc8ef80-0271-11eb-9c5c-11b98e3f01dd.png)
