### ISSUE TITLE
Double click while being in note to enter edit mode (Android)

### ISSUE THREAD

**Issue by szpak** [laurent22/joplin#3849]
## Feature description
After the note is open I would like to just double tap on any non-link place in my note to enter the edit mode.

## Addition notes
Currently, I have to tap an edit icon which is fine, but my proposal makes it even easier.

Android. Tested with Joplin1.1.2.

**Comment by dpoulton-github** [comment]
Could you please close this issue and make feature requests via "Features" in the [forum](https://discourse.joplinapp.org)?

The Feature Request GitHub template itself says,

>If this is a feature request or a support query, please note that you'll not get an answer here.
>Instead we recommend using the forum where you'll are a lot more likely to get an answer: https://discourse.joplinapp.org/
>The forum is also the right place to submit a feature request so that it can be discussed by other users.

It's just that the maintainer is trying to keep the GitHub issues list under control and for bugs only.

Thanks.

**Comment by szpak** [comment]
Thanks for pointing that :-).

Created: https://discourse.joplinapp.org/t/android-double-click-while-being-in-note-to-enter-edit-mode/11559
