### ISSUE TITLE
The search for tags with umlauts (like ä ö ü) does not work

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#3857]
The search for tags with umlauts (like ä ö ü) does not work. 

## Environment

Joplin version: 1.2.2
Platform: Windows, Androis
OS specifics: Windows 10 Pro 2004, Android 10

## Steps to reproduce

1. Search for a Tag with a umlaut (like ä ö ü) `tag:Zähler` 

2. No notes are found, even if there are notes with the tag
![grafik](https://user-images.githubusercontent.com/24863925/94844878-2c613f00-041f-11eb-97d8-7a675be1a26e.png)
![grafik](https://user-images.githubusercontent.com/24863925/94845153-94178a00-041f-11eb-85f0-6f47398d680f.png)

## Describe what you expected to happen

Find all the notes with the searched Tag witch contains a umlaut.

**Comment by laurent22** [comment]
Does it work with lowercase "tag:zähler" ?

**Comment by JackGruber** [comment]
Lowercase dosen't change the result. 
If I search for tags that are without umlauts, I can combine uppercase and lowercase as I like (`tag:BesCheiNigung`) and there is always a hit.

With `tag:Z*hler` i can find the notes with the tag `Zähler` but with `tag:Zaehler` there is no match.  

Its also possible to search tags which contain the following characters `- µ + ! & / .` , but I cannot search for tags containing the following characters: `Ö ö ü Ü Ä ä ß`

**Comment by alexgeirby** [comment]
The same problem with tag names with some cyrillic letters, `л` for example. Search OK with search string `tag:сде*ать` but fails if I specify full tag name: `tag:сделать`.

**Comment by laurent22** [comment]
Should be fixed from next pre-release.

**Comment by alexanderadam** [comment]
Awesome, thank you so much for your fix @naviji :+1:
