### ISSUE TITLE
Horizontal view split (bump)

### ISSUE THREAD

**Issue by jtagcat** [laurent22/joplin#3858]
Unstale of #3659

I can add it to my to-do list, but here's the to-do list stats:

![image](https://user-images.githubusercontent.com/38327267/94850724-e2745b00-0416-11eb-8ced-50814ec8da30.png)

(quite a backlog there!)

**Comment by laurent22** [comment]
I've re-opened the original issue and tagged it so that it doesn't get auto-closed. It's a reasonable request although not that common, so let's see if someone can pick it up. Also perhaps that's the kind of thing that could be customised later on once the plugin system is ready.
