### ISSUE TITLE
Joplin doesn't start on Apple Silicon

### ISSUE THREAD

**Issue by scrumit** [laurent22/joplin#3859]
## Environment

Joplin version: v1.1.4
Platform: MacOS
OS specifics: Big Sur on Apple silicon 11.0 Beta 9 (20A5384c)

## Steps to reproduce

1. Installed home-brew 
2. brew cask install Joplin
3. ran Joplin and a large blank window appears.

Here's the output from the brew install.

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 5 formulae.

==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 127, done.
remote: Counting objects: 100% (127/127), done.
remote: Compressing objects: 100% (108/108), done.
remote: Total 482770 (delta 64), reused 34 (delta 19), pack-reused 482643
Receiving objects: 100% (482770/482770), 219.86 MiB | 3.58 MiB/s, done.
Resolving deltas: 100% (342571/342571), done.
Tapped 1 command and 3672 casks (3,790 files, 235.6MB).
==> Downloading https://github.com/laurent22/joplin/releases/download/v1.1.4/Jop
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'joplin'.
==> Installing Cask joplin
==> Moving App 'Joplin.app' to '/Applications/Joplin.app'.
🍺  joplin was successfully installed!

## Describe what you expected to happen

start Joplin.

## Logfile

I cannot find a log file. If there a way to capture log then let me know and I'll supply it.

**Comment by laurent22** [comment]
Any log? https://joplinapp.org/debugging

**Comment by dpoulton-github** [comment]
> Apple silicon 11.0 Beta 9 (20A5384c)

Is this an ARM device? Will Joplin work on ARM architecture, even Apple?

**Comment by scrumit** [comment]
> > Apple silicon 11.0 Beta 9 (20A5384c)
> 
> Is this an ARM device? Will Joplin work on ARM architecture, even Apple?

Yes, Joplin works on most phones and they are mostly Arm processors. It certainly works on my iPhone.

Yes, this is an Arm Mac Mini running "Big Sur". The last time I looked the failure was in Joplin Helper (Renderer). In answer to the log question, I'll attach the 95kbyte file from the mac console.

**Comment by scrumit** [comment]
> Any log? https://joplinapp.org/debugging

There is no UI so I can't start logging. I've attached today's crash report .

Basically it's Electron.



[Joplin Helper (Renderer)_2020-10-23-085516_Mels-Mac_crash.log](https://github.com/laurent22/joplin/files/5428254/Joplin.Helper.Renderer._2020-10-23-085516_Mels-Mac_crash.log)

**Comment by scrumit** [comment]
draw.io relies on Electron and they assume that release 11 will support Mac Arm.

**Comment by scrumit** [comment]
I'll keep adding comments, just to stop stale bot closing this.

Electron might be working on ARM Macs now, It's up to [v13](https://github.com/electron/electron/releases).

A rebuild should solve it.

**Comment by laurent22** [comment]
Does the bug also happen with the DMG file we release? Because we don't support the Homebrew version - for that you'd need to ask on the Homebrew repo.

**Comment by jonathanstokes** [comment]
I have a similar problem, running the DMG file on the MacOS Big Sur release, but with Intel hardware. It installs, but then on startup says:
![image](https://user-images.githubusercontent.com/7317544/102794243-b5c64480-4370-11eb-9a38-bd7bcd2eb0ae.png)

Clicking "OK" just closes the app, so Joplin is DOA.

**Comment by laurent22** [comment]
Latest pre-release is notarized: https://discourse.joplinapp.org/t/pre-release-v1-5-is-available-with-support-for-media-players-updated-20-12-20/12885/11

**Comment by scrumit** [comment]
leaving this as my beta Arm Mac has now gone back (I had it 8 months). I'll get an M1 Mac mini soon and will try this again.

**Comment by bjbk** [comment]
I am running this on my M1 MacBook Pro with no issue.  (Rosetta) will see if I can submit a PR for making a Universal binary.  Very easy with Electron Builder which Joplin uses.

**Comment by Muzosh** [comment]
@bjbk Hello, were you successful with making a Universal binary?

**Comment by bjbk** [comment]
> @bjbk Hello, were you successful with making a Universal binary?

I did not fork Joplin and try it.  It should be easy enough. I have an Electron app that I distribute as a universal binary without issue.  Sorry not to be of much help here.
