### ISSUE TITLE
Notes disappeared after successful file system synchronization (Android)

### ISSUE THREAD

**Issue by szpak** [laurent22/joplin#3861]
## Environment

Joplin version: 1.1.2
Platform: Android
OS specifics: Android 11

## Description

I've been using Joplin on Android for a while and I like it. Recently, I wanted to make a manual backup of my notes, but I wasn't able to find any "export" option (is there any?). Therefore, I configured file system synchronization (in the fail-safe mode). Some files were exported, but the new day I was surprised seeing Joplin with just the build-in notes and with the settings restarted (e.g. the theme switch back to white unless I set it to black at the beginning).
> Completed: 29/09/2000 23:11
> Last error: Error: Error: Could not read directory /storage/emulated/0/Download/Backup/joplin/locks: Attempt to get length of null array. Path: /storage/emulated/0/Download/Backup/joplin/locks

Another suspicious thing is the fact that in the configured directory there is subdirectory with name (one space). My notes and other files lies in it. In hindsight, I might accidentally define path as /storage/...../joplin/ (with a space at the end). However, the new directory is fine (and there is no space at the end for sure, nor the directory is created), but the error is the same. The locks directory is empty in all cases.

While I still have exported .md files, I can get access to my notes. Nevertheless, I would like to:
 - ~be able to bring it back to Joplin~ - I've accidentally noticed that in the side menu I see two "Welcome! (Mobile)" entries under the "Notebooks" node. The first one contains my old items, while the second one the new "stock ones".
 - find a better way to just export the notes manually
 - explain the situation, maybe there is something what can be done in code to prevent that behavior

Originally [reported](https://discourse.joplinapp.org/t/notes-disappeared-after-successful-file-system-synchronization-android/11358) on the support forum.

## Steps to reproduce

1. Setup "File system" synchronization to some local directory
2. Perform sync
3. Try to sync again (I'm not sure if the error occurred in point 2 as currently every sync generates the same error)
4. The following error is visible in the menu:
> Completed: 29/09/2000 23:11
> Last error: Error: Error: Could not read directory /storage/emulated/0/Download/Backup/joplin/locks: Attempt to get length of null array. Path: /storage/emulated/0/Download/Backup/joplin/locks
5. My notes and the Joplin settings (such as selected theme) were restarted to the default ones.

## Describe what you expected to happen

Synchronization performs successfully and can be re-run later on.

## Logfile

![image](https://user-images.githubusercontent.com/148013/94950417-e7064580-04e2-11eb-8cff-170d794e1ca9.png)

(sorry for the screenshot, but the exported log file is not accessible for me on Android 11 - permission denied and I can't copy/paste the text directly from the Joplin debug window)

**Comment by bgruszka** [comment]
Same issue here (mac app and android)

**Comment by ilikeorangutans** [comment]
Same issue here on android.

**Comment by basnappl** [comment]
Same issue here on Android version 1.2.6

**Comment by roachsinai** [comment]
Same issue and synced by WebDAV.

**Comment by mmBesar** [comment]
Same issue on android 10 Joplin 1.3.10

**Comment by SMEETT** [comment]
Same here, Android 10, Joplin 1.3.13

**Comment by szpak** [comment]
Unfortunately, this error is still valid for 1.4.11 (tested on Android 11).

**Comment by basnappl** [comment]
I am no longer having this issue. It's fixed for me.

**Comment by szpak** [comment]
The latest version available (for me) in Google Play is 1.6.7 and I still observe the problem. I will try with 1.6.8 once ready.

@basnappl Which version do you use?

**Comment by basnappl** [comment]
I am on 1.6.7.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by SMEETT** [comment]
I had a similar issue when trying to sync my android folder "/storage/emulated/0/MEGA/Joplin" with, well, MEGA. Since I don't want to use Dropbox I had to use the Joplin "Filesystem Sync", always resulting in an error message. Turned out that I had to add the (hidden) folder .resource to my /Joplin folder on Android. Since then everything works smoothly.

**Comment by szpak** [comment]
I still observe this in 1.7.5.

**Comment by szpak** [comment]
@stale I commented after your message. Why the `state` tag was not removed? Please re-open.

This issue still occurs in 1.8.5 on my phone.

**Comment by szpak** [comment]
Reproducible with 2.1.4.

**Comment by szpak** [comment]
It's still valid with 2.1.4 on my system.

**Comment by szpak** [comment]
Still here with 2.3.4.

**Comment by szpak** [comment]
Still valid with 2.4.3.

**Comment by szpak** [comment]
It seems to change in 2.6.3. The sync succeeded, to some degree. All the cards are in the "Conflicts" notebook :-/. I tried to check it with an empty directory, but the "fail-safe" mode kicked in and prevented all my cards removal.

As a result, I don't know if it is "fixed", as I don't know, how to start a fresh file system sync with a new directory. Any hints?

**Comment by szpak** [comment]
Let's keep it closed as the original problem no longer occurs starting with 2.6.3. However, I created #6025 as a follow-up - unable to sync notes to a new directory.
