### ISSUE TITLE
Option to "search for selected text"

### ISSUE THREAD

**Issue by codecat** [laurent22/joplin#3862]
In my daily use of Joplin, it would be very useful to be able to select some text, right click, and search for the currently selected text globally in all my notes.

Is this a desired feature? I'd love to try and work on this in a pull request, if it's not too complex for a new contributor!

**Comment by dpoulton-github** [comment]
Could you please close this issue and make feature requests via "Features" in the [forum](https://discourse.joplinapp.org)?

The Feature Request GitHub template itself says,

>If this is a feature request or a support query, please note that you'll not get an answer here.
>Instead we recommend using the forum where you'll are a lot more likely to get an answer: https://discourse.joplinapp.org/
>The forum is also the right place to submit a feature request so that it can be discussed by other users.

It's just that the maintainer is trying to keep the GitHub issues list under control and for bugs only.

Thanks
