### ISSUE TITLE
Support for Zettlekasten along with back-linking and graph-view

### ISSUE THREAD

**Issue by kprohith** [laurent22/joplin#3864]
Support for Zettelkasten along with back-linking and graph-view, similar to Zettlr or Obsidian.md would make Joplin the perfect note-taking app!

**Comment by dpoulton-github** [comment]
Could you please close this issue and make feature requests via "Features" in the [forum](https://discourse.joplinapp.org)?

The Feature Request GitHub template itself says,

>If this is a feature request or a support query, please note that you'll not get an answer here.
>Instead we recommend using the forum where you'll are a lot more likely to get an answer: https://discourse.joplinapp.org/
>The forum is also the right place to submit a feature request so that it can be discussed by other users.

It's just that the maintainer is trying to keep the GitHub issues list under control and for bugs only.

Thanks
