### ISSUE TITLE
Android: open or share image from a note

### ISSUE THREAD

**Issue by rankaiyx** [laurent22/joplin#3868]
Hi,

I just wanted to copy & paste image from Joplin app to email app and did not find a way how to do it (other than looking up the attachment ID directly in Android file system).

Would it be possible to long-press on an image and choose “Share to” or “Copy to clipboard”?

(“Share to” should send the full underlying image, while “Copy to” might apply only to the currently displayed buffer.)

This is a very important function. I believe that many people used to keep scans of documents in evernote and download them when they need a copy on the go. Please implement this basic feature. Thank you.

**Comment by roman-r-m** [comment]
https://github.com/laurent22/joplin/pull/3367

**Comment by rankaiyx** [comment]
> #3367

Great! Can you release your enhanced version? I'd like to try it first!
