### ISSUE TITLE
Copy keyboard shortcuts don't work anymore in Vim mode

### ISSUE THREAD

**Issue by AaronOldenburg** [laurent22/joplin#3869]
In Vim mode, selecting text and hitting CTRL+C, or even "+y, doesn't copy anything to the clipboard, either in Normal, Visual or Insert mode. Right-clicking, then selecting "copy" does work. Yanking also works for copying and pasting within Joplin.

Joplin version: 1.1.4
Platform: Linux
OS specifics: Manjaro KDE

## Steps to reproduce

1. Set Joplin to Vim mode
2. Select text with the mouse (or V)
3. Hit CTRL+C
4. Try to paste into another program
5. Does not paste what you think you copied

## Describe what you expected to happen

Text is copied and pasted.

**Comment by laurent22** [comment]
Closed duplicate

**Comment by haraldpost** [comment]
> Closed duplicate
Could you please have linked the other thread?

**Comment by pluma9** [comment]
Duplicate of #3870
