### ISSUE TITLE
[Feature request] automatically add tag to note

### ISSUE THREAD

**Issue by cast-away** [laurent22/joplin#387]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile

Say you are viewing notes with a tag through the UI filter. IMHO it would make sense that newly create notes while the filter is applied inherited the tag automatically (much like when you are browsing a notebook). What do you think?

**Comment by christianlupus** [comment]
+1 This would be a nice idea.

**Comment by cast-away** [comment]
not stale

**Comment by christianlupus** [comment]
@laurent22 Could you please reopen this issue as it is not solved according to my knowledge. Thank you.
