### ISSUE TITLE
Search with colons will confuse search

### ISSUE THREAD

**Issue by alexanderadam** [laurent22/joplin#3871]
## Environment

Joplin version: `1.1.4`
Platform: Linux
OS specifics: doesn't matter

## Steps to reproduce

1. search for `https://github.com`, `ActiveSupport::Duration` or any other thing with colons

## Describe what you expected to happen

Finding only my notes with the terms `https://github.com` or `ActiveSupport::Duration`. But the search will simply show some notes that don't contain the term.

**Comment by alexanderadam** [comment]
Hi Stalebot! 👋

**Comment by renesugar** [comment]
Joplin for Desktop
Joplin 1.2.6 (prod, darwin)
Revision: f5f117c (master)

Searches with URLs used to work. But, now, I am seeing the same problem.

Any search containing a colon makes the Joplin UI unresponsive.

**Comment by JackGruber** [comment]
I think you should update and try your search again. Because the last stable version is `1.5.14`with many search fixes. 
I can search without a problem for URLs or something like this `"::-webkit"`

**Comment by alexanderadam** [comment]
> I can search without a problem for URLs or something like this `"::-webkit"`

I just tried and if is search something like `https://foobar.com` it still shows many notes that doesn't have the string `https://foobar.com` in it.

Could it be related to some setting or so? :thinking:

**Comment by renesugar** [comment]
Joplin 1.5.14 (prod, darwin)
Revision: 9e076bf (master)

I am still seeing a problem with the latest version.

- searching for **rt.live** (with no double quotes) works
- searching for **https://rt.live/** (with no double quotes) freezes the UI.
- searching for **"https://rt.live/"** (with double quotes) works

**Comment by JackGruber** [comment]
@alexanderadam please se doc https://joplinapp.org/#searching

>One drawback of Full Text Search is that it ignores most non-alphabetical characters

You have to use `/"https://foobar.com"`

@renesugar 
Please also note the search syntax because of the non-alphabetical characters.
On windows I can't reproduce the freeze, no matter how I perform the search

**Comment by alexanderadam** [comment]
> @alexanderadam please se doc https://joplinapp.org/#searching
> 
> > One drawback of Full Text Search is that it ignores most non-alphabetical characters

Well, it would be perfectly fine if this would _actually_ be the case. :wink: 
And this is also what I would expect.
Because in this case `https://foobar.com` and `https foobar com` would have the _same_ outcome, right?
But they clearly don't have the same output. The first one seem to match to all(?) notes whereas the latter is working like it should.

I have rather the feeling that `https:…` is wrongfully interpreted as a search filter (although it is none, according to the documentation that you mentioned).

**Comment by alexanderadam** [comment]
Hey stalebot! :wave:

**Comment by alexanderadam** [comment]
Hi stalebot

**Comment by JackGruber** [comment]
It's a bug. The last time when I took a look at it the word bevor `:` was interpreted as a filter key word. 
I just haven't had time to fix the bug yet
