### ISSUE TITLE
Default Note on open.

### ISSUE THREAD

**Issue by Impostor-syndrome** [laurent22/joplin#3874]
I have what I believe to be a relatively simple feature request, but it would /might make sense in lots of people's workflow.

It would be great if I could take a specific note, right-click and select something like  "Set as default note on open". 
So that each time I open up my note editor I would end up in the same note.   I could imagine that Joplin would revert back to its current default state if it was unselected.
Each time I open Joplin, I would like to set it to open my TODO list, no matter what pane I was sitting in prior to closing Joplin. I think it would be a good way to tweak productivity.  
I hope it makes sense :)

Thanks for an amazing alternative to everything else iv tried so far.

**Comment by dpoulton-github** [comment]
It';s a good idea but could you please close this issue and make feature requests via "Features" in the [forum](https://discourse.joplinapp.org)?

The Feature Request GitHub template itself says,

>If this is a feature request or a support query, please note that you'll not get an answer here.
>Instead we recommend using the forum where you'll are a lot more likely to get an answer: https://discourse.joplinapp.org/
>The forum is also the right place to submit a feature request so that it can be discussed by other users.

It's just that the maintainer is trying to keep the GitHub issues list under control and for bugs only.

Thanks
