### ISSUE TITLE
[feature request] custom css for rendering note

### ISSUE THREAD

**Issue by cast-away** [laurent22/joplin#388]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

would it be possible to customise the note look with a custom styles.css file?

**Comment by Torsten-K** [comment]
I think this would be a great feature. I would like to change the font size in the Markdown area and also in the preview, but it seems not possible.

**Comment by t3ax** [comment]
Would be really great to have this feature to give my notes a more personal touch. 

Also the standard font size is too low for my taste.

**Comment by laurent22** [comment]
It cannot really be done since the app don't use a stylesheet, but more themes could be implemented.
