### ISSUE TITLE
Backtick behaviour changed without corresponding patch note, now very unusable for code blocks

### ISSUE THREAD

**Issue by RobKillilea** [laurent22/joplin#3885]
## Environment

Joplin version: 1.2.6 Joplin for Desktop 1.2.6 (prod, win32) Revision: f5f117cb (master) and at least the version before
Platform: Windows
OS specifics: WIn 10 Pro v2004

## Steps to reproduce

1. Use a backtick to start some inline code, nothing happens, hit it again and a pair of backticks appear, now you must go back a space to insert your code between them rather than type to the end and complete as usual. Note this does not act in the same way as a single or double quote where a pair is inserted on hitting the key once and the cursor is positioned between
2.  Similarly, to make a code block we hit the backtick key three times, we get two backticks, now we hit it again and get four, we must then delete the last before proceeding to insert our code block, at the end repeat and delete

## Describe what you expected to happen
I expect hitting the backtick key to insert a backtick. If the intent is to create smart quote as with the single and double quotes then the behaviour should mirror that, as it is now inserting code is a huge PITA and that's mostly what I do!

## Logfile
No debug log applies, activated debugging and checked both console and log.txt, no associated output

**Comment by laurent22** [comment]
I can't replicate this as on a French keyboard you always have to press twice backtick anyway or nothing happen. @CalebJohn, do you know if it's some issue with CodeMirror?

**Comment by CalebJohn** [comment]
I can't replicate this either, I'm using a US English keyboard on Ubuntu 20 with version 1.2.6. 

I've done some searching online and I can't find any existing codemirror reports of this behaviour.

@RobKillilea does this happen only in Joplin? Could it maybe be a system wide issue? Does it continue to happen after restarting your computer?

**Comment by dpoulton-github** [comment]
Same Joplin version & OS as OP. UK English keyboard. 

Unable to reproduce. Auto-pairing behaves as expected.

**Comment by RobKillilea** [comment]
My bad, I have zero clue how it happened by somehow my win10 installation decided to enable a US keyboard (despite me never having one and always removing that option at install time). Switched back to a UK layout and everything works as expected. Thanks for the effort on this, apologies for the false alert!
