### ISSUE TITLE
Button isn't changing to "Stop external editing"

### ISSUE THREAD

**Issue by Technik-J** [laurent22/joplin#3886]
Prior to new update and new design when you click a button for "Edit in external editor" in the toolbar it will change to "Stop external editing" button. With new update the button isn't changing.

Is it now how it supposed to work in the new design or is it a bug?

## Environment

Joplin version: 1.2.6
Platform: Windows 10
OS specifics: Windows 10

**Comment by laurent22** [comment]
In itself it doesn't make a difference because that stop button was what they call an [Idiot Button](https://cdn2.hubspot.net/hubfs/454487/ebooks/Idiot_Buttons__The_Placebo_in_UX_Design.pdf) (no offense intended). But I'll look if it can be restored.

**Comment by Technik-J** [comment]
Why is it "Idiot Button"? What other option do I have to stop external editing? Except right clicking on the note in the note list and choosing "Stop external editing".

Or you saying that stooping external editing in it self is a placebo?

**Comment by laurent22** [comment]
It's mainly because even if you leave external editing on, it simply won't do anything as long as you don't change the file. I guess it can be a problem if you plan to modify the file without the note being updated, but I don't expect that's a common use case.
