### ISSUE TITLE
UI Rendering error in note & notebook section

### ISSUE THREAD

**Issue by Adama2312** [laurent22/joplin#3891]
Bottom third of the notes section seems to not be rendering 

![image](https://user-images.githubusercontent.com/26538900/95650723-e1a58e00-0ad4-11eb-824d-add99d80ca89.png)

## Environment
Joplin for Desktop

Copyright © 2016-2020 Laurent Cozic
Joplin 1.2.6 (prod, win32)

Client ID: e15b613851ea41a59b0cf37d89608689
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f5f117cb (master)

Windows  Version	10.0.18363 Build 18363

## Steps to reproduce
I have not been able to reproduce as of yet

## Logfile
N/A will enable logging and see if I come across the issue again.

**Comment by laurent22** [comment]
I can't replicate either. Is it maybe when your screen size change or when you plug an external monitor or something like this?
