### ISSUE TITLE
Fullscreen Broken on Gnome / Extraneous Title Bar Above Header Bar on Gnome

### ISSUE THREAD

**Issue by elsiehupp** [laurent22/joplin#3894]
A while back [someone requested the ability to hide the menu bar](https://github.com/laurent22/joplin/pull/1752) ([Issue](https://github.com/laurent22/joplin/pull/1752) #1752); however, the author of that issue closed it, so it has disappeared from the list of open issues, despite some support in the forums:

Last commented August 2020:
[Hide menubar](https://discourse.joplinapp.org/t/hide-menubar/8731)

Last commented November 2019:
[Toggle tool bar and menu bar / distraction free mode](https://discourse.joplinapp.org/t/fr-toggle-tool-bar-and-menu-bar-distraction-free-mode/4430)

A somewhat related issue, last commented today:
[Make menu bar black with dark themes](https://github.com/laurent22/joplin/issues/2689) ([Issue](https://github.com/laurent22/joplin/issues/2689) #2689)

My suggestion is a slight variation of the previous issue, in that I would recommend there be an option, preferably in the View menu, rather than hidden in the Preferences, for the title bar and menu bar to auto-hide when the application is maximized. This is already the default behavior on macOS, so defining the scope and desired behavior should be pretty straightforward.

I'm not familiar with whether implementing this feature would be particularly straightforward in Electron, but [Issue](https://github.com/laurent22/joplin/pull/1752) #1752 linked to [an Electron API call suggesting it might be](https://www.electronjs.org/docs/api/browser-window#winsetautohidemenubarhide).

Again, the main variation I would suggest is offering the option of having the menu bar and title bar *both* auto-hide when the application is in "full screen". It may be desirable to distinguish "full screen" from "maximized", with a standard keyboard shortcut (`alt` + `enter` on Windows), a View menu item, and/or a toolbar icon (opposing diagonal arrows).

If the two modes are distinguished, one possible preference (which, again, should be in the View menu, not buried in the preferences) could be for "maximize" to always enter "full screen," though it could be implicitly "remembered" whether or not maximize implies full screen based on whether the application was full-screen the last time it was maximized.

The other variation I would suggest is that, as on macOS, the menu bar could slide in from the top of the screen after a short delay whenever the cursor remains at the top of the screen. This slide-in behavior could co-exist with the standard Linux and Windows `alt` keyboard shortcut, just to make everyone happy.

(This slide-in behavior may conflict with [a Gnome extension auto-hiding the top bar](https://extensions.gnome.org/extension/545/hide-top-bar/), so this case may require additional compatibility testing.)

Any other thoughts? I will link to this issue from the existing forum threads in order to try and create a critical mass of support.

**Comment by elsiehupp** [comment]
I've been browsing the forums for related issues, and someone made a request to combine the title bar and tool bar like they are in Firefox, macOS Big Sur, and Gnome:

https://discourse.joplinapp.org/t/feature-request-add-support-for-integrated-menu-bar-beneficial-to-all/10264/4

**Comment by dpoulton-github** [comment]
... and on the GitHub create issues page as well as the create feature request template it says to do this on the forum... The devs ask that GitHub is used for confirmed bugs.

**Comment by elsiehupp** [comment]
> ... and on the GitHub create issues page as well as the create feature request template it says to do this on the forum...

I created this issue specifically because of the previously existing issue's having been closed without explanation. I can copy and paste some of this over to the forum, though it seems like no one with any technical understanding has read the threads I linked, and comments on the closed issue are of technical importance to the.

> The devs ask that GitHub is used for confirmed bugs.

Very well, I will reframe/rewrite this as a bug, rather than a feature request.

On Gnome:
- The title bar being separated from the toolbar is noncompliant with the Gnome design pattern of the "[Header Bar](https://developer.gnome.org/hig/stable/header-bars.html.en)." The existence of a largely blank title bar is, on Gnome, an unexpected behavior, ergo a bug.
- "[Fullscreen](https://developer.gnome.org/hig/stable/fullscreen.html.en)" is an expected behavior on Gnome. Ergo, its non-existence is a bug.
- Gnome discourages allowing the "[Menubar](https://developer.gnome.org/hig/stable/menu-bars.html.en)" to be hidden, aside from in the above-mentioned "Fullscreen" view (as is the norm on macOS). However, the "Menubar" may be considered a deprecated design pattern, as Gnome encourages the adoption of other design patterns in its place.

Joplin does support [fullscreen on the Mac](https://developer.apple.com/design/human-interface-guidelines/macos/app-architecture/fullscreen-mode/). While Joplin's [separate title bar and toolbar are technically compliant with the macOS HIG, a Gnome-style integrated title bar and toolbar is also explicitly allowed](https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/window-anatomy/), so bringing Joplin into compliance with Gnome would not create issues on the Mac.

I have very little familiarity with KDE, but the Joplin menu bar appears to be in compliance with [the KDE HIG guidance on menu bars](https://hig.kde.org/components/navigation/menubar.html).

I'm browsing on the MSDN, and while the guidelines are significantly more technical and less conceptual than on macOS and Gnome, one could impute that they are largely similar.

**Comment by robotcorner** [comment]
Not sure why this would even be considered a bug. If you fix it on Gnome, I don't see how that fixes windows. This is part of the programming for the app, NOT really a bug at all. Also it seems foolish the devs would ask for only bugs through Github, that honestly doesn't make sense.

**Comment by elsiehupp** [comment]
> If you fix it on Gnome, I don't see how that fixes windows.

If implementing the Header Bar were done in a cross-platform manner, the result should be perfectly acceptable on platforms other than Gnome. Again, macOS explicitly allows for Gnome-style combo title bars, and Windows and KDE seemingly DNGAF.

Among Joplin's desktop platform, seemingly only macOS requires a menu bar (since it's system-wide), but the menu bar is supposed to be fully redundant with the rest of the interface, other than the bare minimum of system-wide menu items (like window management and the clipboard), which are freebies in Electron. If all menu bar items are redundant with the rest of the interface (as is mandatory in macOS), the menu bar could be eliminated (or made optional in the preferences) on all platforms except for macOS, which, again, hides the menu bar in full screen anyway.

> Not sure why this would even be considered a bug. This is part of the programming for the app, NOT really a bug at all.

Calling a bad design decision a bug is a purely semantic distinction that I decided to make based on the fact that only bugs are supposed to be submitted as GitHub issues. Categorizing bad design decisions as bugs is particularly defensible when said design decisions violate a given platform's Human Interface Guidelines and consequently represent "unexpected behaviors".

> Also it seems foolish the devs would ask for only bugs through Github, that honestly doesn't make sense.

I agree that it's foolish to bifurcate the fora in such a way, and indeed GitHub supports labeling Issues with different categories, so it would be entirely possible to sort bugs by priority, if indeed that is the maintainers' reason for doing so.

**Comment by robotcorner** [comment]
I agree with you on classifying however necessary to get attention, considering the lack of alternatives. It's just dumb to even need to do it this way.

**Comment by elsiehupp** [comment]
I'm migrating this issue over to https://github.com/elsiehupp/joplin/issues/2 so it will be more topical as I don't anticipate anyone else working on it anytime soon.
