### ISSUE TITLE
Not possible to UnNest a nested notebook

### ISSUE THREAD

**Issue by cardassian-tailor** [laurent22/joplin#3896]
If you create a new notebook and then attempt to move it down the list - most often the new notebook will end up being nested inside another. Like this. 

Notebook 1
Notebook 2
-->New Notebook

Once this occurs - there doesnt appear to be any way to "un-nest" it. 

Notebook 1
Notebook 2
Notebook 3 

## Environment

Joplin version: 1.2.6
Platform:  win10 x86_64
OS specifics: 

## Steps to reproduce

1.  Create a new notebook in a joplin installation that already has other notesbooks
2. Try to move that  New notebook either  to the bottom of the list, or the middle without it being nested
3. Try to then un-nest it.

**Comment by rahulkiller104** [comment]
@cardassian-tailor I am a beginner , so please can you help me, how to set up this project locally??

**Comment by dpoulton-github** [comment]
Drop it on "NOTEBOOKS"

**Comment by JonasLoos** [comment]
> Drop it on "NOTEBOOKS" and it will be placed in the notebook root at the position determined by your set notebook sort order.

This works perfectly, but it's not obvious if you don't know it. It might be good if it would also work when moving a notebook to `All notes` or the blank space at the bottom of the list.

**Comment by tessus** [comment]
Can you please use the forum for user questions?

**Comment by SolarDesalination** [comment]
Is this not a UI/UX bug?

**Comment by jharohit466** [comment]
can anyone tell me how to undo accidentally neted notebooks?

**Comment by dpoulton-github** [comment]
Fourth post above yours ...

> Drop it on "NOTEBOOKS" and it will be placed in the notebook root at the position determined by your set notebook sort order.

**Comment by oriongonza** [comment]
I agree that dropping it on notebooks is not obvious, I had to come here to figure it out!

**Comment by Samvdg** [comment]
Must say it's still not obvious. Glad this issue was here. Maybe when dragging a notebook, highlight the 'Notebooks' title with lines around it or something to make it look more 'interactable'?
