### ISSUE TITLE
`o` keymap broken in vim mode

### ISSUE THREAD

**Issue by mandre** [laurent22/joplin#3898]
Pull request at https://github.com/laurent22/joplin/pull/3823 changed `o` in vim mode to map to `insertListElement`. This breaks the expected behavior of vim editor since `o` no longer enters insert mode. This is also now inconsistent with `O`.

## Environment

Joplin version: v1.2.6
Platform: Linux
OS specifics: 

## Steps to reproduce

1. Enable vim mode
2. Press `o` to enter `insert` mode on a new line
3. It creates a new line, but we're still in normal mode

**Comment by CalebJohn** [comment]
This was already reported in the comments of #3823 and a fix is available in #3897. This will be fixed in the next release.
