### ISSUE TITLE
Layout button sequence is unchangeable

### ISSUE THREAD

**Issue by jaklan** [laurent22/joplin#3899]
## Environment

Joplin version: 1.3.1
Platform: macOS
OS specifics: Mojave (10.14.6)

## Steps to reproduce

1. Go to `View` -> `Layout button sequence`
2. Try to change the sequence
3. You can't, because everything is greyed out:
![image](https://user-images.githubusercontent.com/24907857/95685451-43124d80-0bf8-11eb-9a29-2f480468d332.png)

## Describe what you expected to happen

Being able to change the sequence.

**Comment by laurent22** [comment]
Thanks for the report, it will be fixed in the next pre-release.
