### ISSUE TITLE
h2 support?

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#390]
### Operating system

- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

Is there away to force the client to use h2 instead of http/1.1?

**Comment by laurent22** [comment]
No, not at the moment.

**Comment by tessus** [comment]
What would be involved in this? Changing a dependency/library for http/s connections in this project?

Is this planned? Do you think it's a good idea? Shall I open a `Feature request`?

Btw, since there's no forum or email address, let me do this here: Joplin is a great application and I'm very happy that someone finally came up with a great note taking app. You have done a great job so far. Thank you.
