### ISSUE TITLE
v1.2.6 GUI editor loses formatting of edits added to an imported note (JEX file)

### ISSUE THREAD

**Issue by mindfulsource** [laurent22/joplin#3908]
## Environment

Joplin version: v1.2.6
Platform: macOS
OS specifics: Catalina 10.15.7
Joplin encryption: yes

## Steps to reproduce and observation of the problem

1. Create a new note
2. Choose the GUI editor
3. Apply formatting such as cmd-b to make a word bold.
4. Export the note to a JEX file
5. Delete the original note
6. Import the JEX file back in
7. Edit the note by adding new (and formatted) text to it
8. Go out of the note by opening another note
9. Go back to the note and you'll see that the new formatting applied in the GUI editor has disappeared. Only the original formatting from the JEX import stays.

## Other observation

If i even press synchronise on the imported note, I see in front of my eyes new formatting disappears instantly on hitting the sync button. Not always, but often, and repeatedly.

**Comment by mindfulsource** [comment]
Actually, this is happening on 1.2.6 too. I'm testing importing of files into the app. Not exactly sure the root cause of it yet then.

**Comment by laurent22** [comment]
If you could narrow down how to replicate this bug that would be great. Perhaps it happens with a particular note, in which a JEX file of it would be useful.

**Comment by mindfulsource** [comment]
OK I've simplified this into two separate bugs.

Please see #3914 for the v1.3.2 macOS one.

This one seems easier to reproduce. If you cannot reproduce with my updated steps, please advise and I'll provide you JEX file code of an example?

**Comment by laurent22** [comment]
Closing this in favour of the two other bug reports.
