### ISSUE TITLE
Could not refresh lock on android client

### ISSUE THREAD

**Issue by tim-hub** [laurent22/joplin#3912]
This is bit of annoying. I got the similar problem in September. Now it showed up again in October.

Is it a manually way to fix it, such as 
- delete some file at the dropbox folder?

## Environment

Joplin version: 1.2.6
Platform:  Android
OS specifics: 10

## Steps to reproduce

1.  Upgrade to 1.2.6

## Describe what you expected to happen

Synced without pain

## Logfile
- attached
[syncReport-1602629308945.txt](https://github.com/laurent22/joplin/files/5374585/syncReport-1602629308945.txt)

## References
- https://github.com/laurent22/joplin/issues/3729
- https://github.com/laurent22/joplin/issues/3742

**Comment by laurent22** [comment]
This message perhaps shouldn't be displayed because it's an implementation details. What happens if you try to synchronise again, does it still display the message?

**Comment by tim-hub** [comment]
> This message perhaps shouldn't be displayed because it's an implementation details. What happens if you try to synchronise again, does it still display the message?

yes, i tried at least 5 times, all the same

**Comment by laurent22** [comment]
Do you have a particularly slow connection, or maybe very large files? I guess it shouldn't happen even in this case but it could.

**Comment by timothy-mccarthyfinch** [comment]
> Do you have a particularly slow connection, or maybe very large files? I guess it shouldn't happen even in this case but it could.

my internet is very fast, 

large files as I know, no files larger than 10MB

**Comment by timothy-mccarthyfinch** [comment]
the way I know to fix it is to remove app then reinstall and resync, which is painful

**Comment by laurent22** [comment]
What's in your "locks" folder on the sync target? It seems some servers treat the files in there in a special way, which break Joplin's lock mechanism.

**Comment by tim-hub** [comment]
only one file.

![image](https://user-images.githubusercontent.com/2884320/96090676-19874980-0eb8-11eb-892a-6e64a3584296.png)


will deleting it help?

@laurent22
