### ISSUE TITLE
Joplin macOS 1.3.2 the GUI editor loses it formatting in the same client when you press the synchronise button

### ISSUE THREAD

**Issue by overseeing** [laurent22/joplin#3914]
Split from #3908 which originally had two bugs:

## Environment

Joplin version: v1.3.2
Platform: macOS
OS specifics: Catalina 10.15.7
Joplin encryption: yes
**I may have to provide more environment and app settings to make this reproducible. I cannot reproduce it in a Catalina mac VM, only happened on my original Mac before moving to the more stable 1.2.6.**

## Steps to reproduce

1. Create a new note
2. Choose WYSIWYG editor
3. Apply formatting such as cmd-b to make a word bold.
4. Synchronise to save the note.

## Describe what you expected to happen

The formatting should obviously not be stripped away upon synchronise.

I now cannot reproduce this in a macOS VM!

(It doesn't apply to Linux, just my main macOS machine.)

**Comment by laurent22** [comment]
I can't replicate this. Could you maybe leave the console open while your replicate this bug to see if there's any error? https://joplinapp.org/debugging

**Comment by mindfulsource** [comment]
OK, in my main macOS (originally observing the problem) I just downloaded 1.3.3 and enabled console. I tried my steps both with and without console open. I can no longer reproduce it on this main macOS machine.

I guess ticket should be closed then. If it happens later, I can bring it up again and try to observe console errors.

---

BTW is 1.3.2/1.3.3 officially 'stable' and considered fine to use for normal daily use? It's not linked from the github/site as the default release number. (So am thinking it's like an 'unstable' more for testing? Please correct if I'm wrong. I might observe less bugs if I use the newer version, but with 2000 notes I will soon be importing permanently where I cannot afford to lose data, I'd instead use what you recommended in that case...)

**Comment by tessus** [comment]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/223439/96358962-11f3ba80-10db-11eb-8361-00d4997b6f0a.png">
<img width="269" alt="image" src="https://user-images.githubusercontent.com/223439/96358966-19b35f00-10db-11eb-842f-4710fbfebebb.png">
<img width="282" alt="image" src="https://user-images.githubusercontent.com/223439/96358972-22a43080-10db-11eb-8b56-897c423a06e5.png">

https://github.com/laurent22/joplin/releases
