### ISSUE TITLE
VIM keybind o doesn't work properly.

### ISSUE THREAD

**Issue by juxuanu** [laurent22/joplin#3916]
## Environment

Joplin version: 1.2.6
Platform: Linux
OS specifics: Kernel 5.8.14-arch1-1, Desktop Environment: Gnome 3.38.1, ArchLinux.

## Steps to reproduce

1. Create a note / edit one
2. Set the use of vim mode in preferences.
3. Press `o`.

## Describe what you expected to happen

 It should create a new line, jump into it and set Insert mode. But the last step doesn't happen.

## Logfile

I followed the steps to get the Console show up, but no error nor warning appears.

**Comment by laurent22** [comment]
I believe that was fixed in https://github.com/laurent22/joplin/pull/3897 so should be part of the next release.
