### ISSUE TITLE
Numbered lines

### ISSUE THREAD

**Issue by boistordu** [laurent22/joplin#3917]
When using the numbered lines option on a section of a text, it should detect the lines and so have different numbers for each lines.
Right Now it's a succession a 1. In the left section. The good appearance works in the preview part so the right part. 

## Environment

Joplin version: 1.2.6
Platform: windows 10 pro
OS specifics: 

## Steps to reproduce

1. 
2. 
3.

**Comment by xmatic** [comment]
I agree with OP. This is strange behavior.

If I select the following list with my mouse cursor:

item
item
item

And click on the "Numbered List" icon, it turns into:

1. item
1. item
1. item

This renders correctly in the Markdown output, however, the correct input would be:

1. item
2. item
3 item

**Comment by ambrt** [comment]
Just let you guys know, this syntax (just "1."s) is how Markdown is designed to work (see https://guides.github.com/features/mastering-markdown/  "Ordered" section, for example).

I agree that it's a bit confusing and Joplin might create incremental numbers in editor pane too.
