### ISSUE TITLE
New inverted monochrome menubar icon not white

### ISSUE THREAD

**Issue by csemken** [laurent22/joplin#3918]
Since the logo change, the inverted monochrome menubar icon is no longer white and thus does not match the system design (at least in Gnome 3 and Windows 10 dark theme).  Here are the old and new icons for both systems:

OS | Old icon (white) | New icon (grey)
------------ | ------------ | -------------
Ubuntu | ![stretchly_icon_old_lin](https://user-images.githubusercontent.com/39151322/96018080-1c982080-0e4b-11eb-9ae3-8a83efdf2b74.png) | ![strechly_icon_new_lin](https://user-images.githubusercontent.com/39151322/96018098-21f56b00-0e4b-11eb-9497-3550993b3af0.png)
Windows | ![strechly_icon_old_win](https://user-images.githubusercontent.com/39151322/96018046-10ac5e80-0e4b-11eb-97cd-c403af440e2f.png) | ![strechly_icon_new_win](https://user-images.githubusercontent.com/39151322/96018058-15711280-0e4b-11eb-8c20-1fbab0a8f498.png)

## Environment

Joplin version: 1.2.0
Platform: Linux and Windows
OS specifics: Ubuntu 20.04 and Windows 10

## Steps to reproduce

1. Install Joplin
2. Change settings: “Theme” → “Menubar icon” to “Monochrome” and tick “Inverted Monochrome”
3. (On Windows: change to dark theme)

## Describe what you expected to happen

Menubar icons on major desktop systems (incl. Gnome 3 and Windows 10 dark theme) are white.  The monochrome Joplin icon should also be white to blend in.

**Comment by laurent22** [comment]
I'm not seeing the Joplin icon on none of these screenshots.

**Comment by CalebJohn** [comment]
Also there is no v1.2.0 release of Joplin, and there is no "Theme" menu in settings or any controls for the icon colouring as far as I'm aware.

**Comment by csemken** [comment]
Indeed, @laurent22 and @CalebJohn. Lack of coffee -> wrong app name, wrong repository. I am very sorry to have wasted your time! I am closing the bug, but feel free to delete it entirely, since the issue has nothing to do with Joplin.

**Comment by CalebJohn** [comment]
No problem @csemken , just to satisfy our curiosity, what is the right app name?

**Comment by csemken** [comment]
[Stretchly](https://github.com/hovancik/stretchly). It wasn’t due to name similarity…
