### ISSUE TITLE
Add keyboard shortcut to minimize Joplin

### ISSUE THREAD

**Issue by pedrorrivero** [laurent22/joplin#3920]
In macOS it is standard for windows to minimize on cmd-M, this would be a nice feature to include and a natural convention to adopt.

**Comment by pedrorrivero** [comment]
This feature has not been implemented yet

**Comment by EjPlatzer** [comment]
Any update on this? It's very odd to have a Macos desktop app that doesn't respect the Cmd+M minimize shortcut. Every other desktop app I use respects this shortcut.
