### ISSUE TITLE
Notifications not working in AppImage on Pop_OS 20.04

### ISSUE THREAD

**Issue by Steve-Z** [laurent22/joplin#3925]
## Environment

Joplin version: 1.2.6 (AppImage)
Platform: Linux
OS specifics: Pop!_OS 20.04

## Steps to reproduce

1. Created new To-Do and set alarm at nearby future time
2. No notification
3. `sudo apt install notify-osd` with restart for good measure
4. Reset alarm time in step 1 with same result. `tail ~/.config/joplin-desktop/log.text > ~/joplin_error_with_notify-osd.txt` (see attached)
5. `sudo apt remove notify-osd`
6. `sudo apt install libnotify-bin`
7. `notify-send Summary Message` works fine
8. Reset alarm time in step 1 with same result. `tail ~/.config/joplin-desktop/log.text > ~/joplin_error_with_libnotify-bin.txt` (see attached)
9. Added flags.txt file to enable debugging
10. Tried again, same result
11. Deleted old To-Do, created new one and tried again. Same result. (full log.txt attached)

## Describe what you expected to happen
I expected notification bubble (sound would be nice too)

## Logfile

[joplin_error_with_notify-osd.txt](https://github.com/laurent22/joplin/files/5386605/joplin_error_with_notify-osd.txt)
[joplin_error_with_libnotify-bin.txt](https://github.com/laurent22/joplin/files/5386607/joplin_error_with_libnotify-bin.txt)

After enabling debugging here is complete log.txt:

[log.txt](https://github.com/laurent22/joplin/files/5386763/log.txt)

I tried `libnotify-bin` based on what I read in Ubuntu Manpages on [notify-send](https://manpages.ubuntu.com/manpages/focal/en/man1/notify-send.1.html):
"Provided by: libnotify-bin_0.7.9-1ubuntu2_amd64"

UPDATE:
I think I solved this, partially at least. I noticed this line (1856) in log.txt:
```
Unknown option - [ ] Did it work?\n\n
```
My note was written as `- [ ] Did it work?` (to render a checkbox) _without any preceding text_. It seems the app tried to interpret the text following " - " as an option.

I changed the note to:
```
Did it work?
- [ ] Yes
```
**Notifications now work** (but still no sound). So I think the "bug" is a minor one. Notes cannot start with " - " (and perhaps other characters that break the app?). I don't know if that is fixable in the app, but maybe this could be pointed out in the documentation.

It is also worth pointing out that, at least for my Pop OS system, libnotify-bin needed to be installed.

**Comment by Steve-Z** [comment]
The issue is fixed for me, as I stated above. The issue is that notes beginning with "-" (and perhaps other special characters?) break the notification system. In the case of "-" this is because "-" looks like a command option. This is a minor problem, but it would be helpful to warn users in advance not to begin notes with "-" (or with any other characters that might cause a problem).

**Comment by trap000d** [comment]
I've just caught it.
It seems `notify-send` uses standard shell parser for command-line arguments, so fix might be to either strip all leading special characters (- \ | ? : e.t.c. ) from message body or escape them. For example, the following command doesn't working:
```
notify-send "To Read" "- [x] Book To Read\n" --icon "/usr/share/joplin-desktop/resources/build/icons/512x512.png" --expire-time "10000"
Unknown option - [x] Book To Read\n
```
whereas with escaping of leading minus sign all works fine - notification appears on the screen:
```
notify-send "To Read" "\- [x] Book To Read\n" --icon "/usr/share/joplin-desktop/resources/build/icons/512x512.png" --expire-time "10000"
```
