### ISSUE TITLE
VIM Mode: 'Insert new line below' doesn't switch modes

### ISSUE THREAD

**Issue by mike-lloyd03** [laurent22/joplin#3926]
## Environment

Joplin version: 1.2.6
Platform: Windows and Linux
OS specifics: Windows 10 and Manjaro (ArchLinux)

## Steps to reproduce

1. Set keyboard mode to VIM
2. Enter `NORMAL` mode
3. Type `o` to insert a new line below the current one
4. Mode is not switched to `INSERT`

## Describe what you expected to happen

Mode should switch to `INSERT` when pressing `o`.

**Comment by CalebJohn** [comment]
Hi @mike-lloyd03 , thanks for the pull request, luckily this was already fixed in #3897 so will be made available in the next release (v1.3.3).

**Comment by mike-lloyd03** [comment]
Ah okay thanks so much! I love the support!
