### ISSUE TITLE
Add navigation bar for Markdown document

### ISSUE THREAD

**Issue by uname2p** [laurent22/joplin#3928]
For long Markdown documents, hopefully a new navigation bar feature can be added to quickly jump to the section you want to read without having to scroll multiple times. Of course, if we can support the "continue to read" function would be better, for a long document did not finish reading, the next time you open it, continue to the last position. For the missing navigation bar problem, my mitigation measures is to add a document [toc] tag, and then add the following custom style in the document(userstyle.css), but the results are not ideal, somtimes it will block the contents of the document. 
```
.table-of-contents{
    display: block;
    position: fixed;
    right: 20px;
    border: 1px solid gray;
    height: 80%;
    overflow-y: scroll;
}
```
I hope to add a shortcut (similar to F12), you can call up the current document directory information. If the navigation bar can be synchronized to highlight the current chapter would be even better. Thank you.

![2020-10-16_153226](https://user-images.githubusercontent.com/19523804/96226596-791f4b00-0fc5-11eb-8216-de565bd1e67b.png)

**Comment by CalebJohn** [comment]
Take a look at [this forum post](https://discourse.joplinapp.org/t/toc-as-the-sidebar/5979/34) a user there provides improved CSS that you might find solves this issue for you. 

By the way, you should make posts like this in the forum first, the GitHub issues are for bug tracking and are not read by most of the community.

**Comment by uname2p** [comment]
@CalebJohn Thank you so much.
