### ISSUE TITLE
Vim Mode: regression of "o"-cmd

### ISSUE THREAD

**Issue by lockejan** [laurent22/joplin#3931]
When using the `o`-cmd in vim mode adds another line and moves with the cursor to it as expected but it doesn't enter insert mode then.
This used to work but it's not anymore. 
So instead of switching to insert mode one stays in command mode.

## Environment

Joplin version: Joplin 1.2.6
Platform:  macOS
OS specifics: Catalina 10.15.7 (19H2) - installed via homebrew

## Steps to reproduce

1. Activate vim-mode
2. Open a note and hit `o`
3. cursor move to a new line under the current position (but stays in cmd mode)

## Describe what you expected to happen

Adding another line at cursor position and switching to insert mode.

## Logfile

The logs and console outputs aren't including any errors or warnings. This seems to be rather an logical bug than anything else.

**Comment by laurent22** [comment]
Is that what this pull request is fixing? https://github.com/laurent22/joplin/pull/3897

**Comment by lockejan** [comment]
> Is that what this pull request is fixing? https://github.com/laurent22/joplin/pull/3897

Yes, indeed.👍
Didn't see it while I was searching for a similar issue. Thx.

**Comment by CalebJohn** [comment]
Just a tip when searching for previous issues. Try to keep the search as vague as possible while remaining on topic. For example, if you search for "vim" using the gihub search, 4 of the first 6 matches are duplicates of this issue. All titles are some variation of "vim is broken". This won't work in all cases, but it's a good starting point for most issue searches.

Anyways, thanks for the report, I'll close this now.
