### ISSUE TITLE
Add support for plugin content scripts

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#3933]
Plugins run in a different process and thus do not have direct access to the application content. IPC calls between the plugin process and the app process also doesn't allow transferring any complex data such as functions or entire modules.

For that reason it would be useful to introduce the concept of "content scripts" like in Web Extensions. A plugin would provide a script path to the plugin API, and this will then be loaded (using `require()`) inside the main app.

This will allow for example adding support for markdown-it or CodeMirror plugins.

The advantage of this approach is that most plugin operations are still done in their own process (with the associated benefits), but for specific cases we can get more customisations and performances using content scripts.

# Specification

- Add support for `joplin.registerContentScript(type:string, path:string)`
- When called, it stores in the plugin Redux state (perhaps under a new "contentScripts" key) the script type and path
- The script type is an arbitrary string which will indicate how the script should be used. It could be for example "MarkdownItPlugin" or "CodeMirrorPlugin".
- Once a script is registered, hooks need to be added in the relevant places to load them. For example, in MdToHtml, there should be some place that check the list of content scripts with type "MarkdownItPlugin" and load them using `require()`. The same with CodeMirror, in the place where CodeMirror plugins are normally loaded.

**Comment by nishantwrp** [comment]
I'd like on this issue.

**Comment by roman-r-m** [comment]
Umm, I think this has been implemented already

**Comment by nishantwrp** [comment]
Oh, ok. Is there any issue involving plugins that I can work on. I'm asking so that I could also get to know better how plugins work in Joplin for Google Summer of Code.

**Comment by roman-r-m** [comment]
That's not necessary at this point, what's more important is to demonstrate your skills.

**Comment by roman-r-m** [comment]
But to answer your question - the best way to learn how plugins work is to build one.

**Comment by nishantwrp** [comment]
> That's not necessary at this point, what's more important is to demonstrate your skills.

Oh, ok. Got it. What would be the best way to do that? Solving issues labeled "high"? Mostly all the issues labelled high or medium are claimed.

**Comment by roman-r-m** [comment]
> Mostly all the issues labelled high or medium are claimed.

Apologies for the delay, I've just tagged a bunch of issues with medium, feel free to take one.

**Comment by laurent22** [comment]
Has been implemented
