### ISSUE TITLE
Search "Any" operator can not be separated

### ISSUE THREAD

**Issue by k-slava** [laurent22/joplin#3934]
## Environment

Joplin version: Windows 1.2.6, Android 1.2.1
Platform: Android, Windows
OS specifics: Android 9, Windows 10

## Steps to reproduce

1. Task: we are trying to find any notes in a notebook with tag B or C.
2. Create the query notebook:A any:1 tag:B tag:C
3. Will be filtered all notes with notebook A or tag B or tag C. So it might be notebook Z if note has tag B or C. Or it might be any note from notebook A with any tags. It is wrong behaviour.
4. There is no way now to find any notes in notebook A with tags B or C. Or find any notes with ((tag D and B) or (tag D and C)). In short, where D is obligatory and B and C interchangeable.

## Describe what you expected to happen

On the step 2, everything before "Any" operator has AND logic, everything after "Any" operator has OR logic.
So it would work:
notebook:A any:1 tag:B tag:C = (notebook:A)AND((tag:B)OR(tag:C))

Another solution is to implement brackets () as it made in Evernote.
So it would work:
notebook:A (any:1 tag:B tag:C) = (notebook:A)AND((tag:B)OR(tag:C))

**Comment by k-slava** [comment]
@laurent22 What are your plans for this feature? Ok, it is not a bug, but it is impossible to form queries "A and (B or C)" now. It is critical for searching for notes. Is there any possibility to see this feature soon? E.g. open the bid or helping you with implementation in some other way? I am not a programmer, so range of my help can not be extended to implement it myself.

**Comment by laurent22** [comment]
To be honest I don't really know about this issue, but maybe @naviji will have some ideas.

**Comment by k-slava** [comment]
The problem is that ANY operator should work with AND.
For example, in Evernote, the query will be "-tag:A tag:B any:(tag:C tag:D)." It would be equal to "find without tag:A but with tag:B and with any of tag:C or tag:D."
But here, we have only "any:1" when all conditions work with OR.
I can contribute in any way. Except learning programming and writing code myself :) it is too long.
It is a handy feature; you can find similar approaches not only on Evernote but on Google search or many other applications.

**Comment by naviji** [comment]
> There is no way now to find any notes in notebook A with tags B or C

Actually, this is a bug. Here's what the [Evernote spec](https://dev.evernote.com/doc/articles/search_grammar.php) of the "notebook" filter says.

> The notebook is not included in the "union" created by the "any:" operator. E.g.:

    notebook:"Bob's first notebook"
        Matches all notes in this notebook 
    notebook:"Hot Stuff" any: mexican italian
        Matches all notes in the "Hot Stuff" notebook that have the word "mexican" or the word "italian" in them. 
I'll make a PR for this.

**Comment by k-slava** [comment]
Maybe it is possible to fix it with Aand(BorC) logic? Like I mentioned above?

**Comment by bela53** [comment]
@naviji Why not make it better than Evernote as mid/long term goal?

I also think, an advanced search with `AND`, `OR` operators and parentheses `( )` to change precedence/order of applied logic operations would make an awesome feature.

To make this as simple and intuitive as possible, I would favor uniform searching behavior for all entities. E.g. it is hard to remember, if notebooks get their own deviating rules.

**Comment by k-slava** [comment]
> better than Evernote

Evernote didn't document "tag:A any: tag:B tag:C" example in the link above. But it works in Evernote as (tag:A)and((tag:B)or(tag:C)). And it works not only with tags, with everything. An excellent feature. It is possible with it to specify queries for all situations.

**Comment by bela53** [comment]
@k-slava interesting, didn't know that. I would have loved that feature at the time still using Evernote.

One could also argue, why using both `any` and `or` operators. Syntax becomes more uniform (and in my book more intuitive). Like:
```
tag:A or tag:B or tag:C
vs
any:1 tag:A tag:B tag:C
```

**Comment by k-slava** [comment]
> why using both `any` and `or` operators

I don't care about syntax :) In Anki, for example, I can use AND, OR and ( ) that give me tremendous opportunity to write the query in logical operators.
But I am OK with using "any", just give the possibility to multiple by OR only statements after "any" and before "any" all statements should multiply by AND.

**Comment by k-slava** [comment]
Leave it open please.

**Comment by laurent22** [comment]
Was it not resolved by the linked PR? https://github.com/laurent22/joplin/pull/3946

**Comment by k-slava** [comment]
> Was it not resolved by the linked PR? #3946

I checked on Windows yesterday; it was impossible to filter in one notebook for several tags; I will check if I have the latest version.

**Comment by k-slava** [comment]
Yes, I was not on the latest version. Now "any" operator is separated from the notebook.
I still have hope we will implement more elaborate queries for any attributes, but this issue can be closed.
