### ISSUE TITLE
PHP decryption of notes is impossible due to a missing line

### ISSUE THREAD

**Issue by Lars-** [laurent22/joplin#3937]
PHP (incorrectly) forces an IV length, therefore PHP simply can't decrypt the notes. A quick fix that doesn't have any consequences would be to add one line at: https://github.com/laurent22/joplin/blob/dev/ReactNativeClient/lib/services/EncryptionService.js#L327

It should be:
```js
return sjcl.json.encrypt(key, escape(plainText), {
    v: 1, // version
    iter: 101, // Since the master key already uses key derivations and is secure, additional iteration here aren't necessary, which will make decryption faster. SJCL enforces an iter strictly greater than 100
    ks: 128, // Key size - "128 bits should be secure enough"
    ts: 64, // ???
    mode: 'ccm', //  The cipher mode is a standard for how to use AES and other algorithms to encrypt and authenticate your message. OCB2 mode is slightly faster and has more features, but CCM mode has wider support because it is not patented.
    // "adata":"", // Associated Data - not needed?
    cipher: 'aes',
    iv: sjcl.random.randomWords(3, 0)
});
```

The last line (`iv: sjcl.random.randomWords(3, 0)` would make it compatible with the OpenSSL implementation of PHP.

Code to test with in PHP:
```php
<?php
//Change these variables to test
$password  = 'test';
$encrypted = '{"iv":"RcKW62RNKNY=","v":1,"iter":101,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","salt":"82WrYXCjUBQ=","ct":"QgTRmWEfn/qz0K4="}';

$input  = json_decode( $encrypted, true );
$digest = hash_pbkdf2( 'sha256', $password, base64_decode( $input['salt'] ), $input['iter'], 0, true );
$cipher = $input['cipher'] . '-' . $input['ks'] . '-' . $input['mode'];
$ct     = substr( base64_decode( $input['ct'] ), 0, - $input['ts'] / 8 );
$tag    = substr( base64_decode( $input['ct'] ), - $input['ts'] / 8 );
$iv     = base64_decode( $input['iv'] );
$adata  = $input['adata'];

$dt = openssl_decrypt( $ct, $cipher, $digest, OPENSSL_RAW_DATA, $iv, $tag, $adata );
var_dump( $dt );
```

To clarify: it won't work when you don't add the line `iv: sjcl.random.randomWords(3, 0)` and it will work if you add it.

References:
https://stackoverflow.com/questions/11982073/encrypt-in-javascript-with-sjcl-and-decrypt-in-php/41323920#41323920

**Comment by laurent22** [comment]
Hmm, I don't know about any of this but we won't take the risk to change the encryption as that would affect sync and everybody who uses E2EE.

**Comment by tessus** [comment]
> PHP (incorrectly) forces an IV length

In this case I suggest to open a ticket with PHP. We can't take the risk of breaking every E2EE installation, just because PHP is once again inconsistent and wrong.
