### ISSUE TITLE
Publish on PortableApps now might be possible

### ISSUE THREAD

**Issue by hunhejj** [laurent22/joplin#3938]
@laurent22 , have you seen John T. Haller's [comment](https://portableapps.com/comment/243227#comment-243227) on your portableApps thread?
> Please update and I'll see about getting it released next week. I posted folding@home last week and am working on BOINC next. I'm focusing on apps to help folks help with COVID, keep in touch with each other, and work from home. Organization apps fit into the latter.

Maybe the chance has come to finally release Joplin on portableApps?!

**Comment by laurent22** [comment]
Yes but unfortunately I can't build the app, and the lack of proper error message and documentation makes it hard to sort it out.

**Comment by hunhejj** [comment]
Too bad :( I am a big fan of both portableApps and Joplin.

**Comment by laurent22** [comment]
Ideally someone would take care of this part, build the launcher, publish it to PortableApps, etc. If you are interested I can give you a hand.

I've setup everything in there already and at least one person was able to build it (not me): https://github.com/laurent22/joplin/tree/dev/Tools/PortableAppsLauncher

What's needed is to replace JoplinPortable.exe with the latest version when there's a new release, then rebuild and resubmit.
