### ISSUE TITLE
WYSIWYG table breaks when todos are added

### ISSUE THREAD

**Issue by melissasage** [laurent22/joplin#3941]
This image shows several bugs that I found using the WYSIWYG table, particularly when attempting to combine it with todos.
![image](https://user-images.githubusercontent.com/25471399/96346815-cc4bd900-106b-11eb-85cc-3ea8f0b5c422.png)

Markdown source code for this table:
```Markdown
| this header row wasn't here when i added the table |     |
| --- | --- |
| I added this table using the WYSIWYG view on desktop | typed in this column after i came back to the note |
| - [ ] I used WYSIWYG to add a todo here  <br>- [ ] clicked another note and then came back  <br>- [ ] and it's no longer rendered as a todo | - [ ] whereas this one I also used WYSIWG to add correctly renders<br>- [ ] but that will go away as soon as i click another note and come back |
```
As far as I can tell from my own testing, it's impossible to get a todo to render inside a table without using WYSIWYG; it will always be rendered as plain text.

## Environment

Joplin version: Joplin 1.2.6 (prod, win32)
Platform: Windows
OS specifics: 1903

## Steps to reproduce

Described in above image: add table with WYSIWYG editor, add a todo with WYSIWYG editor, then leave that note and come back and it will have an additional row on top and the todos will no longer be rendered.

## Describe what you expected to happen

Todos should stay rendered as todos within a table and not be rendered as plain text; that phantom header row that was added should not be added. when i add a 2x2 table, the first row should be presumed to be the header.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/5395953/log.txt)

**Comment by laurent22** [comment]
Indeed checkboxes inside table are not currently supported. It's been looked at before and due to the Markdown renderer we use we can't implement this.
