### ISSUE TITLE
Importing from .jex file or from RAW joplin directory sees the new notebooks as duplicates

### ISSUE THREAD

**Issue by georgebrianb** [laurent22/joplin#3943]
## Environment

Joplin version: 1.2.6
Platform: Linux/Windows 10
OS specifics: Linux and Windows 10 same behaviour

## Steps to reproduce

1. Create a notebook with subsequent notebooks underneath it
2. Export it as .jex or RAW joplin directory
3. Import via File->Import->JEX file or RAW joplin directory

## Describe what you expected to happen
I'm expecting that this new notebook (that has a different name than any other notebook in my Joplin) to be imported without appending (1) to each of it's notebooks inside.

## Logfile

- Didn't think this is necessary, however if it is, I will gladly upload it!

**Comment by laurent22** [comment]
This is working as expected, it appends (1) when there are already notebooks by that name.
