### ISSUE TITLE
iOS and Android - Impossible to set a specific note history duration

### ISSUE THREAD

**Issue by danpeig** [laurent22/joplin#3944]
It is impossible to set a specific duration for the history using the sliders in the mobile versions.  If I try to set, for example, 15 days  I get anything from 3 days to 110 days because the slider resolution is too low.

 ## Environment

Joplin version: 1.2.6
Platform: Android or iOS
OS specifics: Screen smaller than 6.5 inches: Galaxy S9, iPhone 8, iPhone 7, iPhone SE2, etc...

## Steps to reproduce

1. Run the app from mobile phone with a 6.5inch screen or smaller
2. Try to set a specific history duration: 7 days, 15 days, 30 days and 60 days.

## Describe what you expected to happen

This is a UI control problem. React Native provides some alternatives:

1. Use bigger steps, for instance 7 or 15 days. I personally don't like this option because it limits the user customization options with big steps and continues with the same problem at lower steps.
2. Use a select box like the one used in the _sync interval_ with fixed options that decrease the resolution over time: 1 day, 2 days, 3 days, 4 days, 5 days, 7 days, 10 days, 15 days, 21 days, 30 days, 45, days, 60 days, 90 days, 120 days, 150 days, 180 days, 360 days, 540 days and 720 days.
3. Use an input<number> like in the Desktop version: this would break the mobile configuration UI standard but would provide maximum customization options.

**Comment by Jip-Hop** [comment]
I experience this issue on an iPhone 6S with Joplin 10.7.2. Information in the issue still looks relevant/up-to-date to me. Can this be reopened?

**Comment by mo-han** [comment]
Stupid design, just replace the slider with a number field, same as desktop version.
