### ISSUE TITLE
Strikethrough is removed when going to WYSIWYG mode and back

### ISSUE THREAD

**Issue by scippie75** [laurent22/joplin#3948]
## Summary

In my analysis notes, I start thinking about some concepts and afterwards, when I start noticing that some ideas are not that great, I use the markdown for strikethrough so that it is still there, but obviously, striked through. I do this by enclosing the line of text with ~~.

## Environment

Joplin version: 1.2.6
Platform: Linux
OS specifics: Arch latest

## Steps to reproduce

1. Create some document and then add ~~ in front and at the end of some lines
2. Go to WYSIWYG mode and change just one character in one of the striked through lines - it might be that it also happens when changing something outside of these striked through lines, not sure
3. Go back to markdown editor mode and see that all ~~ have changed to ~ (even on other places) which means the lines are no longer striked through

## Describe what you expected to happen

The ~~'s should stay unchanged, strikethrough should not disappear

**Comment by mrkskwsnck** [comment]
I can confirm this bug on my system.

> Joplin for Desktop version: 1.2.6
> Platform: GNU/Linux
> OS specifics: Linux Mint 20 (Ulyana)

A possible workaround is to use the HTML tag \<s>SOME ARBITRARY TEXT\</s> for striking through and toggling the editor layout between the markdown editor and the rendered preview.

As soon as you switch to the WYSIWYG editor the HTML tag gets replaced by \~tildes~ which are not going to be rendered as a strike through line.

**Comment by scippie75** [comment]
No this has not been fixed yet.

**Comment by mrkskwsnck** [comment]
This issue definitely was not fixed in Joplin 1.3.18 (prod, linux). But just now I updated to Joplin 1.4.19 (prod, linux) and I cannot reproduce the issue anymore. Can someone confirm that?

**Comment by jkuester** [comment]
This is still broken for me (prod, win32, 1.4.19).

**Comment by scippie75** [comment]
I thought I was already on the latest version, but I wasn't. I am on 1.4.19 too now and for me it's still not fixed.
@mrkskwsnck are you sure you are testing it correctly?
Steps to test:
- Take an existing note in the standard editor, not the wysiwyg editor.
- Pick a word and enclose it with ~~, for example: test -> \~\~test\~\~
- It will be shown striked through
- Go to the wysiwyg editor
- Pick another word and just change it, for example: foo -> bar
- Go back to the standard editor.
- On my document, the striked through text is now no longer striked through and looks like this: \~test\~

By the way, it seems that enclosing a word with one ~ does a strike through on this issue board too. Both ~ and ~~ enclosing works. Maybe the wysiwyg editor actually corrects ~~ to ~ but forgets to show it as striked through text?

**Comment by mrkskwsnck** [comment]
@scippie75 Thanks for clarifying the steps to reproduce this issue. I confirm this issue still exists with Joplin 1.4.19 (prod, linux)

**Comment by esotericist** [comment]
it seems fairly like the issue is around here

https://github.com/laurent22/joplin/blob/dev/packages/turndown-plugin-gfm/src/strikethrough.js#L5

i'd test the change and submit a pull request, except i don't seem to be able to successfully build joplin locally.

**Comment by SugoiDev** [comment]
This might be related to #2886
