### ISSUE TITLE
Error in Plugin API docs

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#3950]
The code snippet for `register` (https://joplinapp.org/api/references/plugin_api/classes/joplincommands.html) seems incorrect.

```
await joplin.commands.register({
    name: 'testCommand1',
    label: 'My Test Command 1',
    iconName: 'fas fa-music',
    execute: () => {
        alert('Testing plugin command 1');
    },
});
```

Execute takes `props` and returns `Promise<any>` so it should be something like
```
await joplin.commands.register({
    name: 'testCommand1',
    label: 'My Test Command 1',
    iconName: 'fas fa-music',
    execute: (props) => {
        alert('Testing plugin command 1');
        return null;
    },
});
```

**Comment by laurent22** [comment]
Indeed the doc wasn't right - commands can either return something or nothing and can take a list of arguments. I've updated the doc there: https://joplinapp.org/api/references/plugin_api/classes/joplincommands.html
