### ISSUE TITLE
mermaid.min.js missing on Note Export to PDF; saves null file

### ISSUE THREAD

**Issue by lpartan** [laurent22/joplin#3952]
Exporting to PDF a Note having a mermaid diagram results in empty file

## Environment

Joplin version: 1.3.2
Platform:  Windows 10 Home
OS specifics:  Version	10.0.19042 Build 19042

## Steps to reproduce
1`. add a note like this:
**class diagram
```mermaid
classDiagram
class Player{
-string name 
-string email
}
```
a line of text**

2. Right-click Note name in Notes list
3. choose Export, choose PDF, choose a location
4. open saved file; it is empty. (809 BYTES)

## Describe what you expected to happen
See the diagram in the PDF.  The PDF was empty.  No text.  No diagram.

## Logfile
In developer debug mode there are 2 errors.
Second error probably due to first error.
First error reports a file missing in app.asar as follows:

C:\Program Files\Jop…teropService.js:309 Error: Error: ENOENT, lib\gui\note-viewer\pluginAssets\mermaid\mermaid.min.js not found in C:\Program Files\Joplin\resources\app.asar. Path: C:/Program Files/Joplin/resources/app.asar/lib/gui/note-viewer/pluginAssets/mermaid/mermaid.min.js
    at FsDriverNode.fsErrorToJsError_ (C:\Program Files\Jop…fs-driver-node.js:9)
    at FsDriverNode.copy (C:\Program Files\Jop…-driver-node.js:168)

**Comment by CalebJohn** [comment]
Hi @lpartan , thanks for the detailed report.
This issue was fixed in #3927. That fix is included in [the latest pre-release](https://github.com/laurent22/joplin/releases/tag/v1.3.5).
