### ISSUE TITLE
A way to open a note with a link

### ISSUE THREAD

**Issue by Lars-** [laurent22/joplin#3953]
Both Android and iOS support deep links, which essentially is something like this: joplin://6226f7cbe59e99a90b5cef6f94f966fd
Example on implementation: https://stackoverflow.com/questions/11421048/android-ios-custom-uri-protocol-handling

That way, it is possible to create (for example) a link on your homescreen to a specific note. I checked the Android source, but couldn't find anything that looked like this is already implemented.

**Comment by JackGruber** [comment]
At the moment not supportet.
See the discussion on the forum. 
https://discourse.joplinapp.org/t/are-url-links-on-the-roadmap/599/18
