### ISSUE TITLE
Vim keyboard mode: "o" does not enter insert mode

### ISSUE THREAD

**Issue by liammeck** [laurent22/joplin#3954]
In Vim the correct behavior of "o" is:
1. Create a new line below the cursor.
2. Move the cursor to the new line.
3. _Enter insert mode_.

In Joplin 3) is no longer happening. This may seem minor but it makes editing difficult as it's a very common command. 

## Environment

Joplin version: 1.2.6
Platform: macOS
OS specifics: Catalina (Version 10.15.6)

**Comment by CalebJohn** [comment]
Hi @liammeck thank you for the bug report. This has been fixed #3897 and will be available in the next release.

**Comment by liammeck** [comment]
Sorry for the duplicate, I should have searched closed issues. Thanks!
