### ISSUE TITLE
ENEX import: some attachments silently dropped in HTML import

### ISSUE THREAD

**Issue by msbentley** [laurent22/joplin#3957]
I have an ENEX file containing 60 notes, including a few with only PDF files attached. Importing as MD, these appear fine. When I import at HTML, however, _some_ of the notes silently drop the attachment, such that the note body is only:
```
<en-note>
  <div></div>
</en-note>
```
In this case it is obvious that they are missing, but I'm concerned that when I import my 6k notes, I might silently lose some attachments.

## Environment

Joplin version: 1.3.7
Platform: linux
OS specifics: ubuntu 20.04

## Logfile

In the console I see these errors/warnings:

![image](https://user-images.githubusercontent.com/1671065/96604844-d97bf880-12f5-11eb-99fb-67e94b44bb8a.png)

but actully they appear both during the "good" MD import and the "bad" HTML import.

From `log.txt` however I see this error:
```
2020-10-20 16:38:06: "Error: Error: Could not create directory: . Path: 
Error: Error: Could not create directory: . Path: 
    at FileApiDriverLocal.fsErrorToJsError_ (/tmp/.mount_Joplin50PDvu/resources/app.asar/lib/file-api-driver-local.js:20:18)
    at FileApiDriverLocal.mkdir (/tmp/.mount_Joplin50PDvu/resources/app.asar/lib/file-api-driver-local.js:120:15)"
```
but I'm not sure if it's related or not...

**Comment by laurent22** [comment]
Would you mind sharing the ENEX file that's causing problem? (can be just the ENEX file of whatever note is showing this)

**Comment by msbentley** [comment]
Here is a link to it: https://www.dropbox.com/s/18t77qyqpckc98s/Lab%20notebooks.zip?dl=0

The main notes I'm concerned with are those with attached PDFs, with titles "Labbook 1", "Labbook 2" etc. In my attempt to import the entire notebook notes Labbook 1, 2, 4 5 were broken. If I separate out "Labbook 1" into a separate .enex it imports OK...

**Comment by laurent22** [comment]
This is the same bug as #3958 as far as I can see, at least it's no longer happening in the latest dev version.

**Comment by msbentley** [comment]
Fantastic, thanks!
