### ISSUE TITLE
ENEX import: import as HTML causes Joplin to freeze for some notebooks

### ISSUE THREAD

**Issue by msbentley** [laurent22/joplin#3958]
Some .enex files when imported as HTML cause Joplin to freeze. Watching the `log.txt` (--log-level debug) or database filesize/time, updates stop very quickly after the start of the import (e.g. there are no "refreshing notes" entries in the log). Killing Joplin shows a few notes imported before the freeze. Killing and repeating the process results in the same number of notes imported before the freeze.

I have tried manually chopping the .enex file into several pieces, in case one note was bad, but still hit problems with specific .enex files.

Importing the same notebooks as Markdown works fine - albeit with various errors and warnings in the console (see below).

This particular notebook is rather large, but the error occurs with several - I can try to cut one of the problematic ones down to a small enough size to attach, otherwise please let me know if there are other debug steps I can/should take.

## Environment

Joplin version: 1.3.7
Platform: linux
OS specifics: 20.04

## Logfile

During the (successful - but perhaps not completely?) Markdown import I have the following console log:

[joplin_enex_md.log](https://github.com/laurent22/joplin/files/5409930/joplin_enex_md.log)

During the (failed) HTML import there are no console entries, and no interesting `log.txt` entries - the entire log from this point is:
```
2020-10-20 17:58:33: "CommandService::execute:", "showModalMessage", "["Importing from \"/home/mbentley/Desktop/evernote/MIDAS.enex\" as \"enex\" format. Please wait..."]"
2020-10-20 17:58:33: "Scheduling sync operation...", "30000"
2020-10-20 17:58:34: "Scheduling sync operation...", "30000"
2020-10-20 17:58:34: "Refreshing notes:", "2", "527dbd6157894c7abaae1a86c07c20bc"
2020-10-20 17:58:34: "Scheduling sync operation...", "30000"
2020-10-20 17:58:34: "Refreshing notes:", "2", "527dbd6157894c7abaae1a86c07c20bc"
2020-10-20 17:58:34: "Scheduling sync operation...", "30000"
2020-10-20 17:58:34: "Scheduling sync operation...", "30000"
2020-10-20 17:58:35: "Refreshing notes:", "2", "527dbd6157894c7abaae1a86c07c20bc"
2020-10-20 17:58:35: "Scheduling sync operation...", "30000"
2020-10-20 17:58:35: "Refreshing notes:", "2", "527dbd6157894c7abaae1a86c07c20bc"
2020-10-20 17:58:35: "Scheduling sync operation...", "30000"
2020-10-20 17:58:35: "Refreshing notes:", "2", "527dbd6157894c7abaae1a86c07c20bc"
2020-10-20 17:58:36: "Scheduling sync operation...", "30000"
```

**Comment by laurent22** [comment]
Again without an ENEX file it will be hard to replicate the issue. Any chance you can upload it somewherE?

**Comment by msbentley** [comment]
Sure: https://www.dropbox.com/s/6v5qwig6c9p6uyd/Cometary%20DEM_hack1.zip?dl=0

This is a "hacked" version of the original ENEX; I tried to cut down the size and find the "bad" note, but didn't manage - this smaller version still gives problems on import.

**Comment by laurent22** [comment]
Thanks for the sample @msbentley. Your ENEX file certainly stress-tested the app! (at some point there was more than 3200 nested `<strong>` tags with no content) And I could identify and fix two issues thanks to it:

First was some random bug that could prevent resources from being imported. Second was what was causing the freeze - it was a third party package we use to make the HTML prettier, but the crazy HTML generated by Evernote managed to make this package freeze, and the whole app with it. So I've removed this for now, and it seems to work well now.

If you can give it another try in the next pre-release that would be great.

**Comment by msbentley** [comment]
Great - yes, in going through the migration process I've seen some pretty crazy notes ;-) I'll test again in the next pre-release - thanks for the bug fixes!

**Comment by msbentley** [comment]
Hi @laurent22 - looks good so far - I no longer have freezes or obviously missing attachments! There are still some errors in the console log during import, but I don't know if these are relevant or not? e.g. of type

`/tmp/.mount_JoplinVenYeC/resources/app.asar/lib/reducer.js:301 Uncaught (in promise) TypeError: In reducer: Cannot read property 'id' of undefined Action: {"type":"TAG_UPDATE_ONE"}`

and others - log attached: [joplin_import_console.log](https://github.com/laurent22/joplin/files/5421273/joplin_import_console.log)

**Comment by laurent22** [comment]
Yes I've noticed that at some point and forgot to get back to it. It's more like a warning in the UI and not related to the import process.

**Comment by msbentley** [comment]
OK, great - thanks!
