### ISSUE TITLE
[Feature request] theme customization 

### ISSUE THREAD

**Issue by jrfVP42bLiUWAYOShp5r** [laurent22/joplin#396]
### Operating system

- Android

### Application

- Mobile

It would be very nice if there were some more options to customize the appearance of the app. like:
true black themen (AMOLED)
switch for turning off the animations.

thanks!

**Comment by Kachilero** [comment]
I would like this as well. As someone with "night blindness" the white background is a real strain on my eyes and a dark theme is much easier to read.

**Comment by laurent22** [comment]
Duplicate of #93
