### ISSUE TITLE
Release instructions for CLI on Linux need to be updated

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#3960]
Just tried to install Joplin CLI on Ubuntu and found by trial and error that there are a couple steps missing:
`sudo apt-get install pkg-config`
and
`sudo apt-get install libsecret-1-dev`

Without this `NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin` was failing for me.

**Comment by tessus** [comment]
Some node modules have pre-reqs.

The problem is that the `libsecret-1-dev`package is called differrently on other distros. Also `apt-get` is Debian specific.

Maybe we can add something like: `pkg-config` and the development version of `libsecret` are required.

**Comment by riteshjn** [comment]
Also affects me on Fedora 32. The packages are called `libsecret` and `libsecret-dev` - they need to be installed before installing Joplin CLI.

**Comment by Tackoa** [comment]
Worked, thank you!! :)
