### ISSUE TITLE
ENEX import: some notes get turned into "To Do" notes

### ISSUE THREAD

**Issue by msbentley** [laurent22/joplin#3961]
Some notes (originally from the Evernote web clipper) get turned into Joplin "To Do" notes on import.

See the attached example: 

[Casa o chalet independiente en venta en Villanueva de la Cañada.zip](https://github.com/laurent22/joplin/files/5411349/Casa.o.chalet.independiente.en.venta.en.Villanueva.de.la.Canada.zip)

This happens when importing either as Markdown _or_ HTML.

## Environment

Joplin version: 1.3.7
Platform: linux
OS specifics: ubuntu 20.04

**Comment by laurent22** [comment]
This is actually expected - it converts reminders (presence of `reminder-order` attribute) to "to-do" notes. In Evernote this is the list you see at the top of your notes, in detailed view:

![image](https://user-images.githubusercontent.com/1285584/96747475-3b089980-13c0-11eb-8967-f60a4f6c3b2f.png)

As you can see they have a checkbox next to them, so they are imported as to-do in Joplin to preserve this checkbox information. So this is working as expected and that probably won't be changed, but you can easily toggle between to-do and notes in Joplin by selecting all the to-do, then right-clicking on them.

**Comment by msbentley** [comment]
OK, many thanks - as you say it's an easy fix to toggle. I just wasn't sure where this info was coming from - now I understand!
