### ISSUE TITLE
Ctrl+S no longer triggers synchronisation

### ISSUE THREAD

**Issue by Derkades** [laurent22/joplin#3962]
## Environment

Joplin version: 1.3.7
Platform: Linux
OS specifics: Ubuntu 20.04 KDE

## Steps to reproduce

1. Ctrl+S
2. Observe nothing happens

Clicking the Synchronize button works

## Describe what you expected to happen
Synchronise

**Comment by benji300** [comment]
For me also the following commands do not work. Neither with shortcut nor by clicking in the menu:
- New note
- New to-do
- Focus > Note list
