### ISSUE TITLE
Error with Nextcloud Certificate

### ISSUE THREAD

**Issue by AnemoiThuellai** [laurent22/joplin#3963]
## Environment

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1. Log into self hosted NextCloud
2. Navigate to apps
3. Click "Download and enable" on Joplin Web API app listed
![2020-10-20 21_08_29-Apps - Nextcloud](https://user-images.githubusercontent.com/19896015/96672899-1eb22180-131a-11eb-9527-bc5fe1546c9b.png)

**Comment by unixfox** [comment]
Bump

**Comment by unixfox** [comment]
Bump
