### ISSUE TITLE
Additional features needed: text highlighting and highlighting

### ISSUE THREAD

**Issue by ZhuningS** [laurent22/joplin#3966]
Additional features needed: text highlighting and highlighting.
Like that：HTML5  use<mark>to highlight text that is highlighted.

**Comment by CalebJohn** [comment]
Hi @ZhuningS 

I cannot understand your request. Please post your feature request on the [Joplin forums](https://discourse.joplinapp.org/). The forum has more users so please post in both English and the original language, I'm sure somebody will be able to understand.
