### ISSUE TITLE
Problems with synchronization on iOS

### ISSUE THREAD

**Issue by Festus-Jena** [laurent22/joplin#397]
### Operating system

- iOS

### Application

- Mobile

On iOS the synchronization unfortunately works only very rarely when using WebDAV which I certainly prefer. In most cases I receive an error message that an 'Authorization is required' and that I might have supplied the wrong credentials or that the browser/app does not understand how to supply the credentials. The credentials I supply are correct because it sometimes works. It seems to be a bug in the iOS-app. Everything works fine on Android and on WINDOWS and I will try on MAC later.
I would love to use your Joplin note taking apps - please try to fix this issue.
Kind regards,
Olaf

**Comment by t3ax** [comment]
Simlier for me. When I enter the Nextcloud (which is also WebDAV) login credentials I get a „Network request failed“ error. 

The credentials are corret though. App and iOS are both on the latest version.

No problems with the macOS and Windows apps.

**Comment by t3ax** [comment]
How do you get it to work? I don't know what else to try?

**Comment by crequill** [comment]
I just follow instructions [here](https://github.com/laurent22/joplin#synchronisation).

**Comment by Festus-Jena** [comment]
Is there anybody being successful synching the notes to HiDrive (Strato) from iOS. In my case it works on all other platforms (Android, Mac and WINDOWS) but not for iOS

**Comment by laurent22** [comment]
@Festus-Jena, do you have a test login I could use to try HiDrive sync on iOS?

**Comment by laurent22** [comment]
It seems there's a strange network connection issue on iOS but so far not enough info to be able to replicate it.
