### ISSUE TITLE
Pop up message text fails to render on Linux (Manjaro KDE)

### ISSUE THREAD

**Issue by jangboolee** [laurent22/joplin#3970]
![Screenshot_20201023_073857](https://user-images.githubusercontent.com/11282732/96937743-d0607680-1503-11eb-8cfb-aa4cf59d8f43.png)

## Environment

Joplin version: v1.2.6
Platform: Linux
OS specifics: Manjaro KDE

## Steps to reproduce

1. Create new note
2. Delete note
3. Check popup text

## Describe what you expected to happen

The popup text is rendered in a readable manner

## Logfile

Unable to locate debugging function on Linux client

**Comment by CalebJohn** [comment]
Hi @jangboolee thank you for the bug report.

How did you install Joplin? We have seen a similar issue with the snap package (packaged by a third party), but I'm guessing thats not how you installed it.

**Comment by jangboolee** [comment]
Sorry, I should have been more clear. I indeed used the snap package to install Joplin.

I first used the [arch user repo](https://aur.archlinux.org/packages/joplin/) to install it, but I was seeing some bugs, so I re-installed it using [snap](https://snapcraft.io/joplin-james-carroll).

**Comment by CalebJohn** [comment]
No problem.

The snap package (and the arch aur) are packaged by third parties and aren't supported by us. If you have have issues with these packages you'll need to take it up with the package maintainers. 

I'd suggest installing Joplin using the [install script](https://github.com/laurent22/joplin#desktop-applications) we provide. I know it's a bit weird to package like this, but it reduces the burden on the Joplin maintainers. If you want I can send you the .desktop file that I use to trigger the install, which makes it fairly trivial to update Joplin when you get the new version popup.

**Comment by MrCarroll** [comment]
Issues with fonts in snaps rendering fonts incorrectly is a generic problem in the snap ecosystem related to font caches. There's some brief discussion and a fix for Joplin below, but the fix is a manual process that can't be automated by a single snap itself. The extreme majority of people don't have this issue, but those who do tend to have it for a significant amount of snaps beyond just Joplin.

https://github.com/MrCarroll/joplin-snap/issues/3

You would probably find that the official appimage works fine, but I'd also love to know if you could fix it with the commands in the linked issue so I have some assurance that it works reliably in the meantime.

**Comment by jangboolee** [comment]
@CalebJohn Thank you for the information. It would be great if I could get the .desktop file to automate the installation process.

@MrCarroll Thank you for the useful information. The commands didn't work for my system, but I will try using the official appimage.

**Comment by jangboolee** [comment]
Update: I tried using the [installation script](https://github.com/laurent22/joplin#desktop-applications), but I kept getting an HTTP400 error for the wget command. Upon more web searching, I came across [this website](https://www.addictivetips.com/ubuntu-linux-tips/joplin-app-linux/) that provided the below wget command that worked on my system:

`wget https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh`

I followed the remaining commands, and now everything works, including the popup message text

**Comment by CalebJohn** [comment]
@jangboolee Here is the .desktop file that I use to update Joplin.
```
[Desktop Entry]
Name=Update Joplin
Comment=Update Joplin to the latest pre-release
Exec=/home/caleb/programming/github/joplin/Joplin_install_and_update.sh --prerelease
Icon=joplin
Type=Application
Terminal=true
```

When looking this up for you I noticed that I use a local copy of the update script, so you'll need to change the Exec command if you want to use this.
