### ISSUE TITLE
Automatic theme switching don't work on Gnome DE

### ISSUE THREAD

**Issue by dziaineka** [laurent22/joplin#3979]
## Environment

Joplin version: 1.2.6
Platform: Linux
OS specifics: Fedora 32, Gnome, Wayland

## Steps to reproduce

1. Open Gnome Tweaks.
2. Appearance -> Themes -> Applications -> Adwaita-dark
3. Other applications (e.g. Firefox, Telegram) switched to dark theme.
4. Joplin stayed on lihgt theme.

## Describe what you expected to happen

Joplin automatically switched to dark theme if such option choosen in Joplin settings.

Thank you for awesome app!

**Comment by rkunschke** [comment]
I have the same problem with both the standard and the beta version of joplin(1.3.18-1 and 1.4.9-1)
I can confirm the behavior in plasma5/xorg and on gnome/wayland.

**Comment by dziaineka** [comment]
It works partially now.

Joplin theme switches according to system theme variant (light or dark) if it fresh run. But if system theme has been changed when Joplin is running then Joplin stayed on old variant.

Many other applications can switch to dark/light theme dynamically.

**Comment by dziaineka** [comment]
> It works partially now.
> 
> Joplin theme switches according to system theme variant (light or dark) if it fresh run. But if system theme has been changed when Joplin is running then Joplin stayed on old variant.
> 
> Many other applications can switch to dark/light theme dynamically.

The issue hasn't been fixed.

**Comment by Agraphie** [comment]
Still doesn't work for me :(
