### ISSUE TITLE
Notes created by Joplin API with body_html drop some spaces

### ISSUE THREAD

**Issue by dubiousjim** [laurent22/joplin#3982]
When I create a note using the Joplin API using the `"body_html"` key, some spaces in the html are erroneously dropped.

I provide a small example below (using a simplified version of html that Chrome puts in my pasteboard when I copy styled text from a webpage). In that example, the dropped spaces are wrapped as `<span> </span>`. And removing the `<span>` tags (but leaving the space) removes the problem. But I haven't established that there aren't other ways to produce the same issue.

Leaving the `<span>`s in place but adding a `class` and/or `style` attribute to the opening tag does not eliminate the problem.

If the body of the `<span>`s contains two spaces instead of one, we only get one space in the generated note's Markdown.

If the body of the `<span>` consists of a space, followed by a letter, followed by a second space, all three characters show up in the generated note.

## Environment

Joplin version: Joplin for Desktop, Joplin 1.2.6 (prod, darwin), Revision: f5f117c (master)
Platform: macOS, terminal
OS specifics:  10.15.6

## Steps to reproduce

1. In terminal: `curl -sS --data '{"title":"test", "body_html":"<meta charset='utf-8'><span>Prefix<span> </span></span><span class=\"nowrap\"><code>native</code></span><span><span> </span>Suffix</span>"}' http://localhost:41184/notes`
2. A Joplin note is successfully created, with contents: ``Prefix`native`Suffix``

## Describe what you expected to happen

In the created note, there should be a space after `Prefix` and another space before `Suffix`.

## Logfile

* Creating a `flags.txt` file in `~/Library/Application Support/Joplin` had no effect: when Joplin was restarted, no Console tab is visible.

* Was able to start Joplin from command-line using `/Applications/Joplin.app/Contents/MacOS/Joplin --debug --log-level debug`. Then Console tab does show up. Repeating the request to create a note seems to log no errors:

  ```
  12:13:46 Request: POST /notes
  /Applications/Joplin.app/Contents/Resources/app.asar/lib/logger.js:126 12:13:46 Request (1603642426069): Downloading images: 0
  /Applications/Joplin.app/Contents/Resources/app.asar/lib/logger.js:126 12:13:46 Request (1603642426069): Creating resources from paths: 0
  /Applications/Joplin.app/Contents/Resources/app.asar/lib/logger.js:126 12:13:46 Request (1603642426069): Saving note...
  /Applications/Joplin.app/Contents/Resources/app.asar/lib/logger.js:126 12:13:46 Request (1603642426069): Created note 10ca7adc488042b59bb51c07a302a68a
  ```

**Comment by laurent22** [comment]
Don't know if that would help, but the HTML code should be wrapped in some tag, eg. in `<div></div>`. The meta tag is also invalid there.

**Comment by dubiousjim** [comment]
You're right. Probably it was valid html before I started minimizing it.

Executing this at commandline:

`curl -sS --data '{"title":"test", "body_html":"<div><span>Prefix<span> </span></span><span class=\"nowrap\"><code>native</code></span><span><span> </span>Suffix</span></div>"}' http://localhost:41184/notes`

still improperly swallows the space after `Prefix`, but no longer swallows the space before `Suffix`.

Not sure what's needed to trigger the behavior with `Suffix` I was seeing before. Indeed, now when I enter the `curl` commands in my original report, I no longer get the swallowed spaces before `Suffix` (though it was definitely happening before). I've been using Joplin in the meantime, but didn't change any settings. Perhaps it depends on the application state in some way?

**Comment by dubiousjim** [comment]
This issue still requires attention.

**Comment by dubiousjim** [comment]
This issue still requires attention.

**Comment by dubiousjim** [comment]
Just tested with 1.6.8, at some point this issue was resolved.
