### ISSUE TITLE
fail at export .md to pdf, from WYSIWYG editor: table and lists no rendering 

### ISSUE THREAD

**Issue by C00kie-** [laurent22/joplin#3988]
Hello,
Joplin fails to render style in export pdf from WYSIWYG editor, in this case (see pictures links below), tables.
There is no style applied to the export while you can see it in the WYSIWYG with Joplin.

Thanks

screenshots:
[screenshot markdown](https://github.com/C00kie-/cheat-sheet/blob/master/bugreport/joplin1.png)
[screenshot pdf](https://github.com/C00kie-/cheat-sheet/blob/master/bugreport/joplin2.png)

**Comment by laurent22** [comment]
Headers inside tables aren't supported properly. You might want to use bold or put the headers outside of the table.
