### ISSUE TITLE
Slow rendering of KaTeX on W10 with global definitions

### ISSUE THREAD

**Issue by CalebUsadi** [laurent22/joplin#3993]
This issue is very similar to [this](https://github.com/laurent22/joplin/issues/2357) one. When rendering a file with a large number of equations and a significant number of `\gdef` commands, Joplin freezes while any new change renders, which occurs very slowly. I show the example similarly to how it's done in the example in the issue linked, [here](https://github.com/laurent22/joplin/issues/2357#issuecomment-578404948).

[example.zip](https://github.com/laurent22/joplin/files/5452705/example.zip)
![example](https://user-images.githubusercontent.com/15961844/97453192-e27b5400-190b-11eb-9b35-a3c875b16f14.gif)

## Environment

Joplin version: 1.26 (prod, win32)
Platform:  Windows
OS specifics:  Version 10.0.18362 Build 18362

## Steps to reproduce

1. Open note with a significant amount of KaTeX
2. Experience slow render time
3. Make any edits to the file
4. Experience lag when updating render

## Describe what you expected to happen
Expect fast render time and fast updating.

## Logfile
[log.txt](https://github.com/laurent22/joplin/files/5452578/log.txt)
[console.txt](https://github.com/laurent22/joplin/files/5452577/console.txt)

I don't really see any major issues in either file. There is that one final KaTeX error, but I find it hard to believe that that's the biggest issue. I wonder if it may also be because I have a lot of large files already saved in Joplin.

**Comment by laurent22** [comment]
Please could you provide a sample note that shows this issue?

**Comment by CalebUsadi** [comment]
[example.zip](https://github.com/laurent22/joplin/files/5454377/example.zip)

This is the same file as the one linked above as well as in the gif, GitHub wouldn't let me upload just a .jex file.

**Comment by laurent22** [comment]
Katex saves the macros in a very complex structure which was slow to cache, so I've added bespoke code just to cache this, which should improve performance. You have some errors in your file though, and currently it means you will incur a cache miss every time the note is re-rendered. You can find the errors simply by checking the Katex code that appears as non rendered, or in the console (Help menu, Dev tools).
