### ISSUE TITLE
Sort order direction for notes always bottom up

### ISSUE THREAD

**Issue by AndreasMartin72** [laurent22/joplin#3999]
When sorting notes by title, the order is always bottom up. _View->Sort notes->Reverse sort order_ has no effect.

## Environment

Joplin for Desktop

Copyright © 2016-2020 Laurent Cozic
Joplin 1.2.6 (prod, linux)

Client ID: f5491c5cad674ae38fe206b36920f449
Sync Version: 2
Profile Version: 34
Keychain Supported: No

Revision: f5f117c (master)

## Steps to reproduce

1. View->Sort notes->By Title
2. View->Sort notes->Reverse sort order

**Comment by JackGruber** [comment]
I can't replicate this bahavior in Joplin pre-release 1.3.10
The `Reverse sort order` change the order.
![grafik](https://user-images.githubusercontent.com/24863925/97608015-0fb22a00-1a12-11eb-8165-d04e85d70b70.png)

![grafik](https://user-images.githubusercontent.com/24863925/97607903-e85b5d00-1a11-11eb-8f93-14712ec40f31.png)

**Comment by laurent22** [comment]
I believe that was fixed in 1.3 pre-release
