### ISSUE TITLE
Dialog box missing fonts

### ISSUE THREAD

**Issue by babsher** [laurent22/joplin#4001]
![2020-10-29_12-04](https://user-images.githubusercontent.com/636472/97620527-edeb7f80-19de-11eb-8a0b-23725c58548b.png)

## Environment

Joplin version: v1.3.10
Platform: Linux
OS specifics: Ubuntu 20.04.1 LTS 

## Steps to reproduce

1. Open help dialog

## Describe what you expected to happen
I would expect the font to render

**Comment by babsher** [comment]
I do use a 3rd party snap package for the install so I also created a bug over there https://github.com/MrCarroll/joplin-snap/issues/7

**Comment by laurent22** [comment]
We don't support this package and indeed it's s bug upstream.
