### ISSUE TITLE
HTML5 `<iframe>` tag

### ISSUE THREAD

**Issue by DikBSD** [laurent22/joplin#4003]
Please make support for embedded Youtube videos (HTML5 `<iframe>` tag) in Markdown and WYSIWYG editors, as well as in Web Clipper.

For example:

```html
<iframe src="https://www.youtube.com/embed/B9htFxREhNI" title="TOP 6 SMART DIY INVENTIONS" frameborder="0" width="560" height="400" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="" frameborder="0"></iframe>
```

When pasting this code into the Joplin Markdown editor, the Joplin WYSIWYG editor does not display the embedded video.

And conversely, when pasting a copied video from the Internet into the Joplin WYSIWYG editor, the Joplin Markdown editor does not display the `<iframe>` tag.

Thanks.

**Comment by andryx77** [comment]
I wish this feature too. Please add support for the `<iframe>` tag.

**Comment by vidbaz** [comment]
yeah... at least that they support with the iframe tag... since looks like they dont want to do it for a native way... such a pity, this is so handy feature... I would say now a days.. a basic and very important feature...
