### ISSUE TITLE
`o` key with vi key bindings does not enter insert mode as expected

### ISSUE THREAD

**Issue by Nitrodist** [laurent22/joplin#4007]
## Environment

Joplin for Desktop
Joplin 1.2.6 (prod, darwin)
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes
Revision: f5f117c (master)

## Steps to reproduce

1. Edit a document in vi mode. 
1. Go into normal mode (`esc`). 
1. Type`o` to open a new line and enter insert mode (this is how vim works)
1. Newline is created, but the mode is still in normal mode - it should be in insert mode 

## Describe what you expected to happen

The editor should be in insert mode when using `o` key in normal mode with vi-bindings.

**Comment by CalebJohn** [comment]
1.3 is now the current stable release so this is officially fixed!
