### ISSUE TITLE
Electron dialog unreadable font, Snap installation

### ISSUE THREAD

**Issue by vanheck** [laurent22/joplin#4016]
When I install program by `sudo snap install joplin-james-carroll` then dialog font is unreadable. After start, go to `Help->About`:
![obrazek](https://user-images.githubusercontent.com/9953249/97802308-cdbbfa80-1c42-11eb-86dd-15be22529fde.png)

Or File->Export->*:
![obrazek](https://user-images.githubusercontent.com/9953249/97802331-022fb680-1c43-11eb-9059-bc343f1a1039.png)

I found some probably useful info:
- the problem is in all electron app installed by snap
- https://github.com/ubuntu/snapcraft-desktop-helpers/issues/89
- https://forum.snapcraft.io/t/fonts-fail-to-load-when-desktop-plug-added/3414

## Environment

**Joplin version:** 
```sh
$snap list | grep joplin
joplin-james-carroll  v1.3.11                     31     latest/stable  james-carroll  -
```
**Platform:** opensuse-tumbleweed  20201029
**OS specifics:**
```sh
$snap version
snap                 2.47.1-3.6
snapd                2.47.1-3.6
series               16
opensuse-tumbleweed  20201029
kernel               5.9.1-1-default
```

## Steps to reproduce

1. `sudo snap install joplin-james-carroll`
2. run joplin desktop program
3. Help->About

## Describe what you expected to happen

This version is classically installed by `wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash`:
![obrazek](https://user-images.githubusercontent.com/9953249/97802633-0b218780-1c45-11eb-9def-041fe728324a.png)

## Logfile

[console-warnings.txt](https://github.com/laurent22/joplin/files/5470808/console-debug.txt)
[log.txt](https://github.com/laurent22/joplin/files/5470809/log.txt)

**Comment by JackGruber** [comment]
There are already issues and threads in the forums. 
>We don't support this package and indeed it's s bug upstream. https://github.com/laurent22/joplin/issues/4001
