### ISSUE TITLE
Please add table of contents support.

### ISSUE THREAD

**Issue by dsancheznet** [laurent22/joplin#4019]
I am the author of the python 3 driven Markdown viewer `pymd` ( [🔗](https://github.com/dsancheznet/pymd) ). I use the library `mistune` by Hsiaoming Yang. This library contains an incredibly useful plugin for generating tables of contents. Just by adding...
```
.. toc::
```
...it is possible to generate a beautiful and very convenient index.

Please consider adding a comparable feature in joplin since large notes are easier to navigate this way.

Thanx in advance
D.Sánchez

**Comment by CalebJohn** [comment]
Hi @dsancheznet 

Joplin already supports this feature using the syntax `[toc]`. You need to enable it in settings before using it in notes.
It should be under the plugin menu in Tools -> Options

**Comment by dsancheznet** [comment]
Please forgive my ignorance 😅 but this is awesome. Thanks for the info...

Best regards an keep up the good work!

**Comment by CalebJohn** [comment]
No problem @dsancheznet enjoy!
