### ISSUE TITLE
Keyboard covers last line of text on iPhone

### ISSUE THREAD

**Issue by haroldmackenzie** [laurent22/joplin#4021]
The keyboard on an iPhone covers the last line of text and you cannot see what you are typing. 

This issue occurs on both native iPhone keyboard and Google Gboard for iOS.

The issue seems to be related to issue #1437

## Environment

Joplin version: 10.2.1
Platform: iOS 14.1
OS specifics: iPhone 12

## Steps to reproduce

1. Create or edit an existing note
2. If note has many lines, the last line will be covered by the keyboard and you cannot see what you are typing
3. If you try to scroll up to see the line, screen will scroll up but then snap back down and the last line will be covered.

## Describe what you expected to happen

I should be able to see the last line when I type on an iPhone, just like I can on an Android phone.

**Comment by adrenalinecowhouse** [comment]
#4021
