### ISSUE TITLE
Layout is messed up in Android with Arabic Locale

### ISSUE THREAD

**Issue by sabo3** [laurent22/joplin#4024]
## Environment

Joplin version: 1.2.6.2097583
Platform: Android
OS specifics: Android 9, Locale set to Arabic

I'd like to report that when using Joplin on android with Arabic locale, the app layout is messed up. The side menu looks misoriented as shown in the attached photo.
<img src="https://user-images.githubusercontent.com/73824046/97859017-e63a1c80-1cf7-11eb-8c07-b653178e4fe9.png" width="200" height="400">

I think the menu should appear on the right side if possible, or at least to be shown properly as if the locale is set to any left to right language, without that empty white column at the left.

**Comment by asalthobaity** [comment]
Ditto here.  Since my note titles are in Arabic they don't show properly since they are aligned to the right of the middle pane of the user interface.  No items shown at all at the first pane (pane leftmost).

**Comment by asalthobaity** [comment]
![Joplin-on-android](https://user-images.githubusercontent.com/8325984/98208227-fe0ade00-1f4d-11eb-8594-ddf7326b5371.png)

Test environment : 
Joplin: 1.2.6.
Android : 7.0
Device : Samsung Galaxy Tab S2 
Device Locale : ar-sa

**Comment by asalthobaity** [comment]
Any possible update or fix ?
