### ISSUE TITLE
Cyrillic L (Л) replaced by 'n' when searching

### ISSUE THREAD

**Issue by danil-tolkachev** [laurent22/joplin#4025]
## Environment

Joplin version: 1.3.11
Platform: Linux
OS specifics: Linux Mint 19.3 (based on Ubuntu 18.04)

## Steps to reproduce

1. Create note titled with cirillic symbol "Л"
![image](https://user-images.githubusercontent.com/12847693/97864970-7f7a2a80-1d1a-11eb-8236-9b9398794ad1.png)

2. Press `Ctrl+P` and type some text from title

3. In search results you can see that "Л" was replaced with "n"
![image](https://user-images.githubusercontent.com/12847693/97864931-70937800-1d1a-11eb-864f-b3b163dab690.png)

**Comment by danil-tolkachev** [comment]
The same bug is on Windows 10 too. Can anybody else reproduced this? I checked another symbols but all symbols except 'л' are rendered correctly.

**Comment by roman-r-m** [comment]
Yep, can reproduce it, though it does not highlight "n" for me but still finds notes containing "n".

**Comment by roman-r-m** [comment]
Tracked down to these line in `node-diacritics`
https://github.com/andrewrk/node-diacritics/blob/a58b04da01ce92f1635918fef563e3286ea5a32e/index.js#L233-L224

No idea why is it changing "л" to "n", it has nothing to do with diacritics.

**Comment by roman-r-m** [comment]
Ah! There's even an issue for this: https://github.com/andrewrk/node-diacritics/issues/32
That repo seems abandoned though.

**Comment by danil-tolkachev** [comment]
@roman-r-m Thanks for the investigation.

**Comment by danil-tolkachev** [comment]
I don't know javascript, but i've found that Joplin contains its own implementation of [removeDiacritics](https://github.com/laurent22/joplin/blob/dev/packages/lib/string-utils.js#L90). May be it's possible not to use [andrewrk/node-diacritics](https://github.com/andrewrk/node-diacritics/)? The probable place is [here](https://github.com/laurent22/joplin/blob/dev/packages/lib/services/searchengine/SearchEngine.js#L8).

**Comment by roman-r-m** [comment]
> 
> 
> I don't know javascript, but i've found that Joplin contains its own implementation of [removeDiacritics](https://github.com/laurent22/joplin/blob/dev/packages/lib/string-utils.js#L90). May be it's possible not to use [andrewrk/node-diacritics](https://github.com/andrewrk/node-diacritics/)? The probable place is [here](https://github.com/laurent22/joplin/blob/dev/packages/lib/services/searchengine/SearchEngine.js#L8).

Good catch, thanks. I've not noticed there was already an implementation of this function in lib

**Comment by danil-tolkachev** [comment]
I've tested 1.5.7 version, and it works well now for newly created notes. 

But there is steel 'n' for _old_ notes instead of 'Л'. Anybody knows how to update search index?

**Comment by roman-r-m** [comment]
The only thing comes to mind is export, delete your DB and start from scratch

**Comment by danil-tolkachev** [comment]
@laurent22 Could you please make it clear, is there another way to update search index except of re-importing all DB?

**Comment by laurent22** [comment]
If there's only a few notes, you can also manually modify each of them (like add a space) for example, which will retrigger indexing for those notes.
