### ISSUE TITLE
\r is falsely read as newline or carriage return?

### ISSUE THREAD

**Issue by wstolp** [laurent22/joplin#4026]
## Environment

Joplin version: 1.3.11 and 1.3.10
Platform: Windows (& Linux)
OS specifics: Windows 10

## Steps to reproduce
1.  Use external editor (I tried 2, neovim and notepad++)
2. write some text that includes \r, for example $\rightarrow$
3. This part of the text is not shown in the viewer. Only $ightarrow$ makes it and the latex code breaks.
1. When you close the external editor and open it again, the \r has disappeared and made place for a newline? Or carriage return? I'm not very knowledgable on these things, just learned about them. Sometimes in neovim there's a ^M instead of the \r.

When the internal editor is used the issue doesn't occur. In version 1.3.9 there's no issue either, so I went back to that one.

I hope it's clear enough without a log file.

Edit: My (Windows) Joplin is synced through dropbox with Joplin on a Linux computer that's always on and syncing, although I'm not actually using it.

**Comment by imlonghao** [comment]
I believe I have similar issue like the op said.

I have two computers both sync to Nextcloud, I wrote the following line in computer A and sync to Nextcloud.

```
a = a.split('\n')
```

Then I use computer B and fetch this note, it became

```
a = a.split('
')
```

It's hard for me to sync code block between computers, hope can be fixed later. :)

**Comment by ewal31** [comment]
I have also experienced this with the version 1.3.15 on Windows. On Linux, however, with the same version I don't have the problem.

**Comment by wstolp** [comment]
For some reason the bug label was removed. Is it because I didn't attach a log file or what does this mean?

**Comment by devbf** [comment]
I also have the issue with `\n`. If I write a Latex formula with e. g. `\not=`, it renders perfect on my Windows machine, after syncing via Dropbox and viewing the file on my Android phone, there´s a newline and the Latex is broken.

**Comment by JeWe37** [comment]
I am experiencing the same issue, in my case with syncing from Linux to my iPad via Dropbox, in particular with \rightarrow as well. Could it be due to encoding differences between how the systems handle newlines? \n\r vs \r vs \n?

**Comment by gunnarvoet** [comment]
Same problem here in version 1.3.18: Typing `$\rho$` in an external editor (vim running in terminal) results in `ho`. Same for `$\nu$` which renders as `u`. \r and \n seem to be replaced in the source code as new lines.

**Comment by laurent22** [comment]
I believe that should be fixed in the latest version?

**Comment by devbf** [comment]
> I believe that should be fixed in the latest version?

It is fixed when using an external editor like VSCode in Windows where the problem also appeared, couldn't yet test it on Android. But thank you anyway, great fix!
