### ISSUE TITLE
file always loses

### ISSUE THREAD

**Issue by Aoing** [laurent22/joplin#4027]
My notes always missing after update the joplin

**Comment by adsteel** [comment]
I've been losing information recently, too. For me it's information I've added to a note. I noticed this error the last time I attempted to synchronize, not sure if it's related:

```
Completed: 04/11/2020 15:07
Last error: Error: Error: SQLITE_READONLY: attempt to write a readonly database: DELETE FROM sync_items WHERE sync_target = ? AND item_type = ? AND item_id = ?: 7,1,e9f3ef337361436197f5e42ee6b71b0e
```

**Comment by adsteel** [comment]
Too bad stale bot closed this issue. I've stopped using Joplin because this has become too much of a liability.
