### ISSUE TITLE
Provide a preference to disable prompt to install application menus and icons on launch

### ISSUE THREAD

**Issue by 0xmohit** [laurent22/joplin#403]
The following message keeps up showing on every launch if the user chooses not to install the application menus and icons.

```
Would you like to integrate /home/mohit/utils/Joplin-1.0.83-x86_64.AppImage with your system?

This will add it to your applications menu and install icons.
If you don't do this you can still launch the application by double-clicking on the AppImage.
```

It would be nice to have a preference that could disable this prompt on every launch.

### Operating system

- Linux

### Application

- Desktop

### Version

Joplin 1.0.83 (prod, linux)

**Comment by laurent22** [comment]
It would be something for electron-builder but I don't think there is such an option.

**Comment by ebousse** [comment]
Actually there is now it seems: https://github.com/electron-userland/electron-builder/issues/1962
