### ISSUE TITLE
Can't set function keys as shortcuts

### ISSUE THREAD

**Issue by 190n** [laurent22/joplin#4032]
## Environment

Joplin version: 1.3.11-1
Platform: Arch Linux
OS specifics: I installed `joplin-appimage` from the AUR

## Steps to reproduce

1. Open preferences and go to "keyboard shortcuts"
2. Click on any shortcut to edit it (I was originally trying to set the shortcut to toggle the sidebar)
3. Press <kbd>F10</kbd>
4. <kbd>Y</kbd> is listed as the shortcut. If I save changes, focus the sidebar (so I'm not typing into a note) and press <kbd>Y</kbd>, the sidebar is toggled.

Generally, the function keys seem to map to letters somehow: pressing <kbd>F1</kbd> gives me <kbd>P</kbd>, <kbd>F2</kbd> gives me <kbd>Q</kbd>, etc. Other keys, including modifiers, seem to work as expected.

## Describe what you expected to happen

The shortcut should be listed as <kbd>F10</kbd> and pressing that key should toggle the sidebar.

## Logfile

No errors are reported when I follow those steps. In `keymap-desktop.json`, <kbd>Y</kbd> is listed:

```json
[
  {
    "command": "toggleSideBar",
    "accelerator": "Y"
  }
]
```

**Comment by tessus** [comment]
fixed with #4022
