### ISSUE TITLE
Unable to click on links inside notes

### ISSUE THREAD

**Issue by joplinuser** [laurent22/joplin#4033]
Doesn't open links.

## Environment

Joplin version: v1.3.10
Platform: Android
OS specifics: Samsung GALAXY Note 20 Ultra, Android 10

## Steps to reproduce

1. Create a note with links `[link](https://www.example.com/)`
2. Click on the "Link"
3. No response

## Describe what you expected to happen
Open links in browser / any respective apps.

**Comment by CalebJohn** [comment]
Are you returning to the note view before clicking the link or are you in the edit view? Can you share an example of a link that doesn't work. I just tested this on my android phone and it works, so the issue might be something specific to you.

**Comment by berserkk** [comment]
Having the same issue on 2 devices, Joplin v1.13.10, Android 10.

> Are you returning to the note view before clicking the link or are you in the edit view?

For me it's in the view mode. When you click on any link, nothing happens.

**Comment by CalebJohn** [comment]
@berserkk Can you share an example of a link that doesn't work?

**Comment by berserkk** [comment]
@CalebJohn any link, including the one from the 1st post:

```
[link](https://www.example.com/)
```

**Comment by CalebJohn** [comment]
@berserkk @joplinuser 

How did you install Joplin on your device? The current Joplin version is v1.2.6, somehow both of you have an out of date version. I suspect that it's not a coincidence that ypu're both on the same version.

**Comment by berserkk** [comment]
https://github.com/laurent22/joplin-android/releases

**Comment by berserkk** [comment]
Sorry, I copy pasted version from the 1st post. Of course it's v1.3.10, not v1.13.10...

**Comment by joplinuser** [comment]
> Are you returning to the note view before clicking the link or are you in the edit view? 
Yes

> How did you install Joplin on your device? The current Joplin version is v1.2.6, somehow both of you have an out of date version. I suspect that it's not a coincidence that ypu're both on the same version.
Sorry the version I have should be v1.3.10, my bad. It works fine on version 1.2.6

**Comment by CalebJohn** [comment]
Oh I see, thanks for that clarification. I know theres been some work to the mobile version lately, but unfortunately I haven't kept up with it.

@laurent22 if you have some time can you take a look at this?

**Comment by laurent22** [comment]
Yes indeed I broke links in the previous version (we really need test units for this) and that will be fixed in the next 1.3 release.

**Comment by CalebJohn** [comment]
Thanks @laurent22 !
