### ISSUE TITLE
Automatic unwanted movement of notes

### ISSUE THREAD

**Issue by AndreasMartin72** [laurent22/joplin#4038]
After doing the steps listed below, editing a note surprisingly moves it back in an earlier notebook hosting it.

## Environment

Joplin version: 1.3.11
Platform: Windows 10 64 bit
OS specifics:

## Steps to reproduce

1. Create a notebook A
2. Create a child to A notebook B
3. Create a note N in notebook A
4. Move note N from notebook A to notebook B
5. Edit note N
   note N moves then back to notebook A

**Comment by vaibhav135** [comment]
Hii @AndreasMartin72 
can I work on this issue

**Comment by AndreasMartin72** [comment]
@vaibhav135 , sure.
