### ISSUE TITLE
Search for ‘kamera’ does not find ‘Videokamera’

### ISSUE THREAD

**Issue by piefel** [laurent22/joplin#4044]
Search for ‘kamera’ does not find ‘Videokamera’.

## Environment

Joplin version: 1.2.6
Platform: Linux; also Android
OS specifics: 

## Steps to reproduce

1. I have notes (two, in fact) that contain the word ‘Videokamera’.
2. When I perform a global search (using F6) and search for ‘kamera’, no notes are found. Both are found when using for ‘Videokamera’ or ‘videokamera’; none are found for ‘Videokamer’.
3. This is not only a problem for German composite words, but also in English: ‘manners’ is not found when searching for ‘manner’

## Describe what you expected to happen

* I expect notes to be found on parts of words.
* Why: _Not_ finding my notes is worse than finding too many. I often do not remember exactly what I wrote.
* Additionally, I expect incremental search results instead of having to start the search

**Comment by JackGruber** [comment]
This is no bug!
>For example, searching for cat will return all the notes that contain this exact word. Note: it will not return the notes that contain the substring - thus, for "cat", notes that contain "cataclysmic" or "prevaricate" will not be returned.

https://github.com/laurent22/joplin#searching

**Comment by piefel** [comment]
So it is a documented bug? :-)

I need to read the documentation to find stuff? I need to prefix 90% of my searches with `/`, instead of forcing exact matches with some prefix? This is contrary to intuition.

Anyway, thank you for explicitly pointing me to the relevant bit I overlooked. It’s even incremental. Great!

**Comment by piefel** [comment]
I very much disagree with your assessment. Database queries (FTS) are not for end users. What’s the point of them anyway? How many notes do I need to have that I cannot eyball the result list of a search that is more forgiving and may, on occasion, return too many results?

**Comment by jniggemann** [comment]
I came to open a new issue but found this one instead. After reading https://joplinapp.org/#searching, I think @piefel is right.
From a user POV, I enter some characters in a search field and expect the search to return everything and anything that contains this substring. IMHO the issue with the current implementation is the FTS limitation that the wildcard can't be at the beginning. This results in me needing to prefix almost the entirety of my searches with a `/` which is not intuitive.

Possible solution: Make search configurable to either use FTS or basic search. Whoever prefers basic search can set this and is no longer forced to prefix all of his/her searches with a slash.
