### ISSUE TITLE
App not starting on iOS 9.3.5

### ISSUE THREAD

**Issue by accidentalexponential** [laurent22/joplin#4054]
Joplin shows splash screen and directly exits. IMHO there's no need to further support such an old os, but could you remove the compatibility in the app so i can use the older version?

## Environment

Joplin version: 10.3.1
Platform: iPad 3
OS specifics: iOS 9.3.5

## Steps to reproduce

1. Download App from AppStore
2. Try to start App
3. See it failing

## Describe what you expected to happen

Normal app startup

**Comment by laurent22** [comment]
But are you sure it's just a compatibility issue and not some other error? Could you maybe check the log to find out? https://joplinapp.org/debugging

It looks like I'd need to release a new version to set the compatibility so I'm not sure that would even solve your problem, as the app store would still give you 10.3.1 as latest version.

**Comment by benjaminoliverhofmann** [comment]
Seems like a compatibility issue to me.

```
Dyld Error Message:
Dyld Message: Symbol not found: _UITextContentTypeAddressCity
  Referenced from: /var/containers/Bundle/Application/9B7FD959-5BBF-4778-9B0F-CC0357D40F6C/Joplin.app/Joplin
  Expected in: dyld shared cache
 in /var/containers/Bundle/Application/9B7FD959-5BBF-4778-9B0F-CC0357D40F6C/Joplin.app/Joplin
  Dyld Version: 390.7
```

<img width="966" alt="Bildschirmfoto 2020-11-06 um 18 33 02" src="https://user-images.githubusercontent.com/39745590/98396878-bf187d80-205e-11eb-97ce-09ab9cb09356.png">

**Comment by laurent22** [comment]
Hmm, as often we lose compatibility for features we don't even need. I guess that dependency was pulled by one of the packages. I'll try to see if I can replicate and keep the compatibility.

**Comment by Hamschta** [comment]
If the compatibility is not possible, would it be possible to put up an older version of the app for ios 9 only so at least the app is working?

**Comment by subhead** [comment]
Yea an old version that is working with ios 9.3 would be awesome.

**Comment by bearsylla** [comment]
Seems like it is still not fixed in the latest version. Is there any update on this?

**Comment by bearsylla** [comment]
Is there any update on this?

**Comment by vmatyushin** [comment]
Still reproduced (iPad 3, iOS 9.3.5).

**Comment by vmatyushin** [comment]
Still reproduced (iPad 3, iOS 9.3.5).

**Comment by vmatyushin** [comment]
Still reproduced (iPad 3, iOS 9.3.5).
