### ISSUE TITLE
Crash on Android 4.4.4

### ISSUE THREAD

**Issue by venetin** [laurent22/joplin#4057]
The latest version 1.3.13 is force closing on startup on Android 4.4.4. On Android 7 and Androjd 10 the app is working as expected.

**Comment by laurent22** [comment]
Could you provide the crash log? https://joplinapp.org/debugging

**Comment by venetin** [comment]
[2020-11-07-22-04-44.txt](https://github.com/laurent22/joplin/files/5505373/2020-11-07-22-04-44.txt)
Hello,
I can't get log from the app, because it crash on startup. Also the option "Take bug report" is not present in the developer options on 4.4.4. But I am attaching a logcat export. I hope it will help.

**Comment by roman-r-m** [comment]
Your log does not show the reason for the crash, you seem to have filtered it. Can you search for the line that has FATAL and post it and the whole stack trace here?

**Comment by venetin** [comment]
[2020-12-11-15-43-39.txt](https://github.com/laurent22/joplin/files/5679444/2020-12-11-15-43-39.txt)
Please check this fresh logcat.
The issue is still present even after the latest update.

**Comment by roman-r-m** [comment]
From reading [this thread](https://github.com/facebook/react-native/issues/29983) it seems that Android 4.x is not supported by react-native 63
This comment specifically
https://github.com/facebook/react-native/issues/29983#issuecomment-716612072

**Comment by laurent22** [comment]
Thanks for checking @roman-r-m. That's unfortunate but it means we don't support Android 4 anymore then.
