### ISSUE TITLE
Development Plugins not loaded in version v1.3.18 (works in pre-release v1.4.7)

### ISSUE THREAD

**Issue by lepuso** [laurent22/joplin#4064]
## Environment
Joplin version: v1.3.18
Platform: MacOS
OS specifics: 10.15.7, Node: v14.15.0, NPM v6.14.8

## Steps to reproduce
1. Follow Instructions on https://joplinapp.org/api/get_started/plugins/
2. Check Development Console for output

AR: Messages are not being printed in console (nor in log-plugins.txt)
ER: Messages are printed (however this functionality works in v1.4.7). 

## Logfile (from v1.3.18)
2020-11-08 12:55:33: "PluginService: Loading plugin from <path>/JoplinPlugins"
2020-11-08 12:55:34: "Starting plugin: joplinplugins"
2020-11-08 12:55:34: "Finished running onStart handler: joplinplugins (Took 44ms)"

**Comment by laurent22** [comment]
Does it work with prerelease 1.4?

**Comment by laurent22** [comment]
Yes you might need to use the prelease for now to develop plugins
