### ISSUE TITLE
Open in External Editor no longer capturing changes

### ISSUE THREAD

**Issue by bladewolf55** [laurent22/joplin#4065]
I believe this started in v1.4.7

## Environment

Joplin version: Desktop 1.4.7 (prod, win32)
Platform: Windows Pro 2004
External Editor: [Markdown Monster](https://markdownmonster.west-wind.com/) 1.24.18.6

## Steps to reproduce

1. Select a note
2. Enable external editing (e.g. Ctrl+E)
3. Add text in the external editor and Save

Expected: new text is visible in Joplin note
Actual: no change in Joplin note

**Comment by bladewolf55** [comment]
FYI, I confirmed this isn't MarkdownMonster-specific today by setting Notepad as the editor. Same behavior, saved changes not updated into Joplin.

**Comment by ameisbe** [comment]
I think I  experienced that problem already with he v1.4.6 using Typora as the external editor.
Changes made in Typora were not tracked by Joplin and therefore not saved after closing Typora.

platform: Windows 10.0.19041

**Comment by laurent22** [comment]
Fixed in a808281dd2b12fd1bd6b0a6cdebccdc8eb66b431

**Comment by bladewolf55** [comment]
Thank you, I'll confirm behavior when released.
