### ISSUE TITLE
Backup plugin idea

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#4067]
A plugin that backups the complete user data to an external directory, every x hours.

- Add a new config screen "Backup"
	- Add two options:
		- `interval`: the number of hours between each backup (Default: 12)
		- `max_backups`: Number of backups that should be kept (Default: 4)
		- `backup_dir`: Where to save the backups to (Default: `~/JoplinBackup`)
- Every `interval` hours, the plugin:
	- Creates a new sub-directory in `backup_dir` named "Backup-YYYYMMDD-HHmm"
	- Export all the data to it as JEX
	- If there's more than `max_backups` directories, delete the oldest one

Currently, a way to export/import data from a plugin is missing, so that would need to be added first.

**Comment by dpoulton-github** [comment]
Sounds **really** useful. Can I ask why RAW and not a single JEX with a "Backup-YYYYMMDD-HHmm.jex" filename?

**Comment by laurent22** [comment]
I haven't thought about it actually, but I think it wouldn't be in the scope of the first version. The backup plugin is to allow users from recovering their notes when they accidentally delete or change them, or they disappear due to sync issue. I'm less concerned about the local files, at least for this plugin.

However, it's true that as we add more features I would like to clean up a bit the profile folder. For example by putting all user settings in one folder and application state (like sync state, cache, etc.) in a separate one, and just doing that would make it easier to backup and restore. Unfortunately at the moment, user settings are a bit mixed with application state in the database.

**Comment by dpoulton-github** [comment]
That's fine just wanting to make sure that as things develop two different "backup" solutions don't use the same file extension when they don't do the same thing.

**Comment by laurent22** [comment]
Yes indeed, JEX would be only for note-related data. User settings if we support this would be in a separate archive, could be a simple ZIP file for example.

**Comment by sttrebo** [comment]
I would add an additional option to periodically copy a backup to another location.  For me, I have an autohotkey script that makes a .jex backup every night.  And once a month it copys the latest backup to a cloud account.  Just in case of catastrophic failure of my backup location.

**Comment by th-ros** [comment]
It would be nice if the destination location for the backupfiles will support also file system, webdav, dropbox, ... like the syncronisation but with it's own configuration. So the backup ca be stored to another location as the synchronisation.

**Comment by stavpup** [comment]
https://en.wikipedia.org/wiki/7-Zip is superior that zip  in compression and compatibility between OS's.

**Comment by JackGruber** [comment]
Such a plugin is available: 
https://github.com/JackGruber/joplin-plugin-backup

**Comment by alexanderadam** [comment]
@laurent22 can this be closed then?

**Comment by laurent22** [comment]
Thanks @JackGruber for implementing this as a plugin!

 https://github.com/JackGruber/joplin-plugin-backup
