### ISSUE TITLE
Support for markdown table calculations 🧮🖩

### ISSUE THREAD

**Issue by alexanderadam** [laurent22/joplin#4072]
I just learned about the Atom [`markdown-table-calc`](https://atom.io/packages/markdown-table-calc) package (or [the corresponding vscode package](https://libraries.io/github/oswida/vscode-markdown-table-calc)) and thought, that this feature would definitely be a nice addition for Joplin, too. And now that I investigated into it, I saw that [Evernote users want this, too](https://discussion.evernote.com/forums/topic/112314-basic-calculation-in-tables/). So I guess it'd also be a good 'selling point' for Joplin. :wink: 

The implementation allowed to create a comment on the end of a markdown table and calculate things in the last row.
For instance:

```markdown
| Column A | Column B | Column C |
|:---------|:---------|:---------|
| 123      | 456      | 789      |
| 0        | 0        | 0        |
<!--TBLFM C2=A1+A2; C1=56*78/4 -->
```

Personally, I find `TBLFM` pretty cryptic if you're new to this feature and would rather prefer a more speaking `CALCULATE` keyword instead — but I guess that's just a detail.

It used [`markdown-it`](https://github.com/markdown-it/markdown-it) and the mighty [`formula-parser`](https://github.com/handsontable/formula-parser) (although nowadays there's the package [`hyperformula`](https://github.com/handsontable/hyperformula) from the same folks, which claims to have "_a high-performance_").

## Features

* Define table formulas in Markdown files
* Recalculate all formulas in a file using custom command

## Usage

To define a set of table formulas, you can add a special HTML comment **below** a given Markdown table (TBLFM is a tribute to an Emacs Org mode :) . Only the first comment under the table will be taken into account.

```markdown
| Column A | Column B | Column C |
|:---------|:---------|:---------|
| 123      | 456      | 789      |
| 0        | 0        | 0        |
<!--TBLFM C2=A1+A2; C1=56*78/4 -->
```

The comment can span multiple lines and contain multiple formulas separated by a semicolon. Formulas are calculated in the order they are written. Table cells are described using spreadsheet notation, columns designated with letters like **A,B,C .. Z** (and even more AA, AB etc.) and rows with integers **1,2,3 ...** You can also use range notation like **A1:E23**. Moreover, [hot-formula-parser](https://github.com/handsontable/formula-parser) contains also a big set of predefined functions which can be used in formulas.

**PS:** It seems that @oswida removed [the source](https://github.com/oswida/markdown-table-recalc) at one point but maybe it would be possible to republish it again?

**Comment by oswida** [comment]
Oh my, that was so long ago... my first (and only) plugin for Atom. I have rushed to search through my archives,  but unfortunately, I do not see the code at the moment. In fact, I can't remember removing this code from Github and any reason to do it... Nevermind, if this is a desired feature, I can try to excercise a little and recreate the implementation.

**Comment by alexanderadam** [comment]
> Nevermind, if this is a desired feature, I can try to excercise a little and recreate the implementation.

Oh wow! This is a fantastic offer! :pray: 
Does that mean that you might provide a PR for Joplin? :star_struck:

**Comment by oswida** [comment]
> Does that mean that you might provide a PR for Joplin? 🤩

I've just started to play with Joplin plugins :-).  It seems I will be able to prepare something, but I need some time...

**Comment by alexanderadam** [comment]
> I would appreciate any suggestions regarding the syntax for including formulas into Markdown tables.

What are you thinking about this?

```markdown
| Column A                | Column B           | Column C                   |
|:------------------------|:-------------------|:---------------------------|
| 123                     | 456                | 789                        |
| 0                       | 0                  | 0                          |
| <!--FORMULA A3 * B3 --> | <!--FORMULA B3 --> | <!--FORMULA SUM(C2:C3) --> |
```

It would probably gain more flexibility if every cell could have it's own formula.
Also a cell could get the static value for most of the time.
So for instance:

```markdown
| <!--FORMULA A3 * B3 --> 56088 | <!--FORMULA…
```

This way the code could be copied and even markdown interpreters who don't know about the comments would show it correctly. The formulas only would have to be updated on table changes. Otherwise the static value could stay the same.

> You have mentioned "hyperformula" from the same company as previous parser, however it is distributed under different license

I didn't have a look on that. You're right! `hyperformula` surely isn't compatible. I'm sure that `formula-parser` is fine anyway. It seems that it's still one of the most maintained parsers anyway.

**Comment by oswida** [comment]
> It would probably gain more flexibility if every cell could have it's own formula.

Yes, that would be very intuitive. 
Do I understand correctly that after calculation we are inserting computed value next to the formula comment as it is shown on the second example?

**Comment by alexanderadam** [comment]
> Do I understand correctly that after calculation we are inserting computed value next to the formula comment as it is shown on the second example?

It's just an idea, since it would allow to gain compatibility to 'regular' markdown. What's your opinion on that?

**Comment by oswida** [comment]
I like the idea of putting formulas directly inside the cell. The only concern is the "readability" of the cell with the formula and computed value. On the other hand - formulas are not shown on the preview, so there is a possibility to get the clear table view. And, additionally, HTML comments mostly have different colors in the editor.
Let's try it. I would also propose  to use some shorter prefix than "<!--FORMULA". It is needed only to distinguish formulas from other comments, could it be just **<!--FM** ?

**Comment by alexanderadam** [comment]
Sure, or even just a small f (like the function in mathematics).
You could also add the verbose alias `FORMULA` case this isn't any significant effort. This way everybody you use whatever they prefer (short or verbose).

**Comment by tessus** [comment]
I would disuss this on the forum as github is for bugs only.
Also, mre people are reading the forum than github issues.

The new plugins system is perfect for adding something like this. But here are a few comments:

```
| Column A                | Column B           | Column C                   |
|:------------------------|:-------------------|:---------------------------|
| 123                     | 456                | 789                        |
| 0                       | 0                  | 0                          |
| <!--FORMULA A3 * B3 --> | <!--FORMULA B3 --> | <!--FORMULA SUM(C2:C3) --> |
```
Somehow I don't undertand this. `A3` is the cell with the formula. So, if you want to `123*456`, it should be `A1*B1`.

Also, I have to say that `<!--TBLFM C2=A1+A2; C1=56*78/4 -->` is a lot more readable and less work to write than putting that stuff in every cell.

e.g. I'd probably not use a plugin that makes me write formulas inline, but that's just me.

**Comment by alexanderadam** [comment]
> Somehow I don't undertand this. `A3` is the cell with the formula. So, if you want to `123*456`, it should be `A1*B1`.

ah yes, you're right. I referenced the wrong cells but I guess you get the idea (I'm fixing this).

> Also, I have to say that `<!--TBLFM C2=A1+A2; C1=56*78/4 -->` is a lot more readable and less work to write than putting that stuff in every cell.

Readable is relative, since it won't be rendered in regular markdown without any extensions. Also it gives far less flexibility.
What if you just want to have a single cell calculated? Or cells from two rows?

**Comment by oswida** [comment]
I've put initial implementation to https://github.com/oswida/joplin-markdown-calc. It is definitely not finished, I was not able to select the whole note text for replace, but the calculation mechanism should work. I've included both syntaxes - inline cell formulas and formula list below the table. 

I agree with @tessus  that this topic could be moved to the Joplin forum, so please @alexanderadam, could you specify the feature request there?

**Comment by alexanderadam** [comment]
> I've put initial implementation to https://github.com/oswida/joplin-markdown-calc.

Oh wow, this is great! :+1: 

> could you specify the feature request there?

[done](https://discourse.joplinapp.org/t/support-for-markdown-table-calculations/12381) :+1:

**Comment by tessus** [comment]
> What if you just want to have a single cell calculated? Or cells from two rows?

I don't understand these questions. You can still do that and a lot faster with something like:
`<!--TBLFM C2=A1+A2; C1=56*78/4; D4=C2+C1 -->`

Otherwise I would have to go to cell C2, put a formula there, go to cell C1, put a formula there, and then go to cell D4 and put another formula there. Do you see where I'm going with this?

**Comment by Awbmilne** [comment]
I agree with @tessus that using formulas inside the cell is more physical typing, Which in some cases is best to be avoided. On the other hand, When I write my notes (particularly ones that I update often) I prefer to have the raw markdown well organized and easy to edit. To me, having the formulas in the cells is less conceptually tasking and makes the organization gremlin in my head just that much happier. @oswida seems to have implemented both syntax in his [Joplin-Markdown-Calc](https://github.com/oswida/joplin-markdown-calc) plugin, Which to me seems like the best way to handle that.

I would prefer to have a shorter syntax inside the array cells than the full HTML comment syntax, But for abvious reasons, this would be problematic. If someone has a better idea for shorter syntax and how to make it work... I could get behind that.
