### ISSUE TITLE
Attachments in rich text editor do not open (link has appended info)

### ISSUE THREAD

**Issue by msbentley** [laurent22/joplin#4073]
When attaching a file in the rich text editor, or in my case when importing from Evernote html and viewing with the rich text editor, links to attachments no longer seem to work.

When switching to Markdown, everything is fine.

Inspecting the link from the rich text editor there is an additional "parameter" in the link (a timestamp?), e.g.

`file:///home/mbentley/.config/joplin-desktop/resources/27ff38464a554b38aa080a003329e74c.txt?t=1605111029329`

this last prevents the link opening (e.g. with xdg-open). If I remove this last part, the link resolves correctly to the attachment.

## Environment

Joplin version: 1.4.7
Platform: linux
OS specifics: ubuntu 20.04

## Steps to reproduce

1. Enter rich text editor
2. Attach a file
3. Ctrl+click on the link - observe that nothing happens
4. Click to edit the link - observe that there is an extra "parameter" in the link:

![image](https://user-images.githubusercontent.com/1671065/98836180-ab478f80-2441-11eb-9261-89e8461e482e.png)

5. Switch to markdown viewer, observe that the link opens correctly. The markdown is:

`[dbeaver.desktop_example.txt](:/27ff38464a554b38aa080a003329e74c)`

## Describe what you expected to happen

Click the attachment link should open the file.

**Comment by laurent22** [comment]
Hmm that's tricky. This `?t=` parameter is necessary to make sure the resource is visually updated in the editor after it has been edited (applies in particular to images), and it works fine in Windows. Not sure how it can be fixed but I'll take a look.

**Comment by laurent22** [comment]
Come to think of it, this query parameter is only necessary for images, so I've removed it from other link types.

**Comment by msbentley** [comment]
OK, that's perfect - many thanks!
