### ISSUE TITLE
filesystem sync fails if locks directory is missing

### ISSUE THREAD

**Issue by wararjey** [laurent22/joplin#4075]
I am using Joplin Arch Linux and a few android devices. Recently I noticed that my Linux Desktop Client failed to sync because the "locks" directory was missing in the Joplin sync dir.

Error message looks like this:
Error: Error: ENOENT: no such file or directory, scandir '/path_to_joplin_dir/Joplin/locks'. Path: /path_to_joplin_dir/Joplin/locks

After creating that directory manually, syncing seems to work again.

I suggest the client creates the locks dir automatically, if it does not exist yet.

Regards,

**Comment by laurent22** [comment]
It does

**Comment by wararjey** [comment]
Well, for me it did not. I had to create the locks directory manually in order to make it work.

Regards,

**Comment by laurent22** [comment]
@wararjey, normally when the sync target is created or updated, the "locks" directory is created. It's an all or nothing operation - either the folder is created or it is not and the complete upgrade/creation fail, so in theory it shouldn't be possible that the sync target is v2 but the "locks" doesn't exist. It works well with all sync targets except it seems with filesystem sync in some cases.

Do you know if it could be for example a permission issue on your device? For example, the app can create and read files, but not directories?

Also what do you use for sync? Is it possible that whatever software you use treats empty folders differently ("locks" can be empty) for example by not syncing them or deleting them? Just trying to make sense of it so that the next user with this issue will know what to do.

**Comment by wararjey** [comment]
Hello Laurent,

I have been using Joplin for a while, before the v2 sync got implemented. I guess that v1 sync did not need the locks/ dir?
I am using file-based sync with syncthing as backend. I sync to a dual-boot Laptop (which is the main editing device), 3 Android devices and two servers. The servers are there just for backup purposes and do not have Joplin installed.
Syncthing does replicate empty directories, I did just test that. I know that syncthing on android can have permissions issues, but syncthing has an option to ignore the file/dir permissions. That normally avoids any issue with file/dir permissions on the android/windows devices.
I noticed that there are other dot-directories in the sync dir: .lock/ , .resource/ .sync/
So if there is a .lock/ directory, the need for an extra locks/ directory seems a bit unclear to me. Perhaps it is not necessary once all sync targets have switched to v2 sync?
Anyway, I think that the upgrade to v2 sync already happened a while ago. However, the sync error just appeared quite recently, perhaps a week or two before I filed this report.
Back then, when the sync version got upped, I did not check if the locks/ directory got created. Perhaps it never did and Joplin just did not complain about that before.
Regards,

**Comment by soumitrimishra** [comment]
I am having same issue with joplin 2.3.5. Earlier i used nextcloud for sync.
Now I use central GIT Repo. Local repos in each machine use push/pull with central repo for sync.
All joplin instances sync from local repo. I had to manually create  lock directory for joplin to work.

**Comment by 616b2f** [comment]
same for me failed until I created manually lock directory. Used fedora silverblue 34 and flatpak package for joplin v2.4.9

**Comment by jiayoustone** [comment]
i am having same issue with joplin 2.1.8(prod linux) used File System for sync

**Comment by sbszcz** [comment]
Same problem here with MacOS. I cannot understand why this is still ignored.

**Comment by nokturna1** [comment]
Joplin 2.8.8, once sync to another device using the original joplin folder, the "locks" folder missing

**Comment by zuckerruebe** [comment]
Same here. Using

```
Joplin 2.12.18 (prod, win32)

Client ID: 1e015366b2d447a0a59cb48f19a77d5b
Sync Version: 3
Profile Version: 43
Keychain Supported: Yes

Revision: a0a4a81
```

on my Windows Laptop syncing with file system (which is itself a Wasabi mount using Mountainduck).

Worked after creating a `locks` dir.

**Comment by cynber** [comment]
This may cause other issues down the road, but I stopped this from happening by leaving an empty text file in the `locks` directory. The directory no longer goes missing, so the error doesn't show up
