### ISSUE TITLE
Unable to copy images to Word from rendered preview

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [laurent22/joplin#4077]
I am trying to copy an article from full rendered preview to Word but images never get copied to clipboard. The images' file format is jpeg. Not sure if it is related to #1702.

## Environment

Joplin version: 

```
Joplin 1.3.18 (prod, win32)
修订(Revision): 6b75485a1 (master)
```

## Steps to reproduce

1.  Download this and unpack to get the jex note file in question:
[【诡秘之主】22全途径魔药徽章UI设计_UI_图标_Delaro - 原创作品 - 站酷 (ZCOOL).zip](https://github.com/laurent22/joplin/files/5530260/22.UI._UI_._Delaro.-.-.ZCOOL.zip)

 - Note: Because zip doesn't handle encoding well so you might see garbled in filename due to differences between GB2312 and UTF-8. You could safely rename the unpacked jex's name to anything.
2. Open it in Joplin
3. Select all the rendered preview and press Ctrl+C, then open Word and paste.

## Describe what you expected to happen
Images should have been pasted but they are not.
![yOhpNdfIn6](https://user-images.githubusercontent.com/32929636/98934883-b1ab3980-251d-11eb-824c-ca679445e121.gif)

**Comment by paramecie** [comment]
It seems to correspond to what I signaled in forum?
https://discourse.joplinapp.org/t/copy-paste-a-note-with-a-screen-copy-in-thunderbird-or-other-docs-makes-an-invalid-e-mail-doc/12519

Thank you to solve this, it's extremely important for us, at least.

**Comment by paramecie** [comment]
Uh uh...
#1702 has been closed after stale.
#4077 is about to stale. As of 1.3.18 it doesn't work. For the 1.4 version I didn't see any change logged about this, but I didn't try. A forsaken bug?
