### ISSUE TITLE
JEX Format and Joplin E2E Encryption Documentation

### ISSUE THREAD

**Issue by sunjam** [laurent22/joplin#408]
It would be helpful to have detailed JEX format documentation and Joplin's E2E Encryption documentation since this is an open source project, plus this would help developers be better integrate Joplin into projects such as [NextNote](https://github.com/brantje/nextnote/) and [Nextcloud / Owncloud.](https://github.com/laurent22/joplin/issues/228)

**Comment by laurent22** [comment]
E2EE doc is on the website. JEX format is indeed not documented yet.

**Comment by laurent22** [comment]
I will document this if another project needs to use the format.

**Comment by e-alfred** [comment]
@laurent22 Nextnote (https://github.com/brantje/nextnote) wants to adopt the JEX format to integrate well with Joplin.

**Comment by laurent22** [comment]
@e-alfred, is there a thread where they are discussing this?

**Comment by e-alfred** [comment]
It is already linked above my post, but here is the comment from their lead designer: https://github.com/nextcloud/notes/issues/183#issuecomment-394701589

**Comment by sunjam** [comment]
@laurent22 Nextcloud Note devs are interested in adding compatibility with JEX format (see link above).  Please consider releasing documentation on the JEX format so other developers will be able to use it. :)

**Comment by laurent22** [comment]
I didn't see any new message about this? Doing the spec for the JEX format is quite easy and I can do it if needed, but I'm not seeing any clear interest or plan for integration, or am I missing something?

**Comment by sunjam** [comment]
Hi! There is a [discussion thread here](https://github.com/nextcloud/notes/issues/248) on the Nextcloud Notes app.  Seems that all of you are quite busy, but [you can connect with Nextcloud devs directly on IRC.](https://nextcloud.com/contribute/)  Perhaps @jancborchardt can advise.

**Comment by jancborchardt** [comment]
> Doing the spec for the JEX format is quite easy and I can do it if needed

That would be cool! :) It’s always easier to gauge the feasibility of something if the spec is published. At Nextcloud we only use open formats for that reason.

**Comment by PackElend** [comment]
> Doing the spec for the JEX format is quite easy and I can do it if needed
so @laurent22 just do it :), I would say you just to do the first step. There are many just waiting for it, I read it in several threads in the nextcloud forum.

**Comment by dtzWill** [comment]
Ping!

**Comment by Stele77** [comment]
IMHO Nextcloud is the Nr. 1 FOSS project in its area, as is Joplin too. And both project naturally should integrate as much as possible.

Nextcloud users are badly waiting for many years for what Joplin offers, and if Joplin has the chance to work on a shared open source standard, or even let its Joplin format alone be the standard, than it would be not understandable for most FOSS people to throw that chance away.

NIH has killed so many good projects, and when Joplin could integrate into Nextcloud directly, it would also open up to millions of new users (and push their resources, time, effort and money into Joplin too).

IMHO this should be one of the top prioritys, as it is a huge and one of a kind chance for Joplin.. 

So please understand if i ask if there are any news on this issue?

**Comment by laurent22** [comment]
My current thinking about the web app is that I won't do it as maintaining a fourth app (there's already mobile, desktop and terminal) will require more time than I currently have and as a result the overall quality of the project will suffer.

That being said, if someone is motivated and can make a Nextcloud web app for Joplin, I'm happy to help with that effort. @foxmask already made a web client, which can work for some people, although as I understand it is not a Nextcloud app.

**Comment by foxmask** [comment]
if you want a clue of what it does https://discourse.joplinapp.org/t/joplin-web-a-webapp-for-our-joplin-editor/555/21

**Comment by PackElend** [comment]
there is a new drive in [nextcloud/notes](https://github.com/nextcloud/notes), see [SimpleMDE maintenance status #204](https://github.com/nextcloud/notes/issues/204#issuecomment-497450095). 
I know it is not easy to convince someone to abandon its work but it is a bit of wasted energy pursuing both projects. 

Does anyone with coding experience want to reach out to all of them and trying to join forces? As work is very advanced but a merge still possible it would be worth a try, even if only basic functionality would be available in the very beginning. 
Deeper integration, such as accessing nextcloud resources from within Joplin could be pushed by making it a Google Summer of Code project next year.

**Comment by sunjam** [comment]
[Nextcloud Text](https://github.com/nextcloud/text/) has been [released as the new collaborative text editor](https://nextcloud.com/blog/nextcloud-introduces-collaborative-rich-text-editor/) for Nextcloud.  [Plans are underway to incorporate it into the Nextcloud Notes app to replace SimpleMDE](https://github.com/nextcloud/notes/issues/331).  Now would be a great time to join those discussions on how to incorporate the Jex format along with their standard markdown!

**Comment by PackElend** [comment]
I may know a student who would make himself familiar with all things and try to get the basic done. All that should end up in a Google Summer of Code 2020 project for him.

**Comment by sunjam** [comment]
From an email conversation with Laurent on 5/20...

"I'll create a document with the JEX spec, but to be honest I'm not sure it will be useful to
anyone... I'll create the spec and let's see."

**Comment by chr15m** [comment]
The `.jex` file format appears to be a simple tarfile containing the markdown files + attachments. This is beautifully simple. Great work @laurent22!

You can examine it yourself as follows:

```
mkdir myjexfile
tar -xvf myjexfile.tar -C myjexfile
ls -alh myjexfile
```
