### ISSUE TITLE
markdown preview doesn't render manually typed TODOs

### ISSUE THREAD

**Issue by patzm** [laurent22/joplin#4083]
The markdown preview doesn't render manually typed TODOs. Example:
![Peek 2020-11-13 15-46](https://user-images.githubusercontent.com/5219726/99124255-6d747380-25c7-11eb-9d77-8e419ea0ea2f.gif)
This seems to only happen with imported notes. Editing the markdown of a _new_ note gets reflected correctly in the rendered view. I think that these todo items get rendered as bullet list items instead. This would explain, why the bullet point is rendered and not an `*`. Also: why is the first word rendered in black font, and all subsequent words in blue? For successfully parsed todo items, all text is rendered in blue. Maybe it is also confusing the `[ ]` for the beginning of a link?

## Environment

Joplin:
- Version: Joplin 1.4.9 (prod, linux)
- Client ID: c58bd723996e4ddd9c655bd9a482a569
- Sync Version: 2
- Profile Version: 34
- Keychain Supported: No
- Revision: da69775 (master)

Platform: Linux, Manjaro
OS specifics: Linux Kernel 5.8.18-1 Manjaro

## Steps to reproduce

1. Import [this JEX file](https://cloud.patz.app/s/AHXpSkMTFzkgydb) with _File_ `>` _Import_ `>` _JEX - Joplin Export File_
2. edit the note as shown in the animated GIF above
3. observe that the preview doesn't refresh correctly

## Describe what you expected to happen

I would expect the rendered markdown to show rows that begin with either
```
- [ ] or
- [x] this
```
to be rendered like
- [ ] or
- [x] this

## Logfile

https://pastebin.com/VvgAsKKC

**Comment by laurent22** [comment]
We also need a copy of the note that has this problem (preferable as a JEX file) because what you are showing should work.

**Comment by patzm** [comment]
The Jex file should already be linked above in the reproduction steps :wink: Thx for the quick response :+1:
Again: https://cloud.patz.app/s/AHXpSkMTFzkgydb

**Comment by laurent22** [comment]
Ok I see that the issue is that there's a non-breaking space between `- [ ]` and the label. So if you replace them with regular spaces it will work. What was the note imported from?

**Comment by patzm** [comment]
Interesting :laughing:, I didn't know there were different kind's of spaces. But typing in the Joplin editor doesn't insert regular spaces then? How could I achieve this then? I don't want to go through my notes manually. Should I repeat the export-import "trick" described below? And if yes, how do I make sure to insert normal spaces instead of non-breaking spaces?

Where they are from? Attention: long story coming up:
* import OneNote notebook into EverNote desktop (Windows) with Evernote 6.x (the latest EverNote 10.x dropped support for that import and I couldn't find 9.x installation files online)
* export as a `.enex` files
* import into Joplin on Linux
* realize that somewhere on the way, all TODOs got converted to images (a checked and unchecked box)
* export the whole Joplin database using _Joplin Export Directory_
* use SublimeText search and replace across all files (sadly Joplin doesn't support that yet, I read [this discussion](https://discourse.joplinapp.org/t/find-replace-in-all-notes/1740)) to replace `![ToDo](:/<resource-ID>)` with `- [ ]`. This is then where the _non-breaking_ spaces were inserted probably?
* import into Joplin again

**Comment by laurent22** [comment]
> I didn't know there were different kind's of spaces

Yes, so much pain has been caused by them :) In Joplin, there's rule to prevent them from being introduced in the codebase as they can cause weird nonsensical bugs. If you are on macOS, non-breaking spaces can be inserted when you accidentally press Cmd+Space (or maybe Option+Space) instead of just Space. So I guess you could repeat your Sublime Text search and replace and make sure that all spaces after `- [ ]` are replaced by regular spaces.

**Comment by patzm** [comment]
I exported one note which isn't rendered "correctly" in various ways:
* `MD - Markdown`
* `RAW - Joplin Export Directory`

Then, I tried to search this file for non-breaking spaces with the following commands, but nothing was returned:
* `grep -P "\xa0" <filename>.md`
* `grep $'\xc2\xa0' <filename>.md`

Also `sed` didn't work:
* `sed -i 's/\xA0/X/g' <filename>.md` doesn't change the file
* `sed -n 's/\xA0/X/g' <filename>.md` also doesn't print any lines that are replaced

I uploaded the exported markdown file [here](https://cloud.patz.app/s/7MDePYBrbLCBri5). Could I ask you to try finding NBSP in this file? And if you find NBSP there, how could I replace them?

**Comment by laurent22** [comment]
I'm not an expert in Posix commands so I wouldn't know, but maybe on the forum someone could help.

**Comment by pr3c0g** [comment]
I used Vim, because it's where I'm most comfortable:

 `:set list` -> This will show symbols where a NBSP is (on mine it shows a `+` sign.
`:%s!\%xA0! !g` -> replacing all those 0xA0 for a space.

With sed you probably need to set LANG first, probably LANG=C, but this is something that I haven't tested. 
Hope it helps

**Comment by patzm** [comment]
Thx @pr3c0g that workded! Sadly, I couldn't import them again afterwards. Joplin compalined about not finding `_type`, even though it was in the file. Maybe something with search & replace went wrong, but I guess I messed that up.
