### ISSUE TITLE
Android app is incredibly slow on startup 

### ISSUE THREAD

**Issue by dspacejs** [laurent22/joplin#4084]
Whenever I start the app, it freezes and takes about 10 seconds to respond before I can do anything. This doesn't happen every time.

I thought this may be because of encryption, so I disabled it. The same problem still exists.

## Environment

Joplin version: 1.0.340
Platform: Android
OS specifics: Android 11, Pixel 2 XL, Graphene OS

## Steps to reproduce

1. Open the app using this environment
2. It should load incredibly slowly (if not, try adding lots of notes and attachments, maybe this will replicate it)

## Describe what you expected to happen

It should be fast and responsive. Things like this shouldn't happen.

## Logfile

It seems to happen randomly, so I haven't been able to get a logcat for it yet.

**Comment by laurent22** [comment]
What do you sync with? With WebDAV or Nextcloud sync this kind of freeze is unfortunately expected, especially if you have many notes.

**Comment by dspacejs** [comment]
@laurent22 to the file system with Syncthing.

Why is it expected? That's a major performance issue, therefore something needs to be fixed. I do have a lot of notes, and I'm going to have a lot more as time goes on. A lot of other users are probably the same.

**Comment by laurent22** [comment]
Closed as duplicate

**Comment by seth100** [comment]
@laurent22 duplicated of what issue?
I have the same issue on Android 11 and file system sync with Syncthing! My OS storage is encrypted too!
