### ISSUE TITLE
Infinite vibration on to-do reminder notification

### ISSUE THREAD

**Issue by WebMaster50** [laurent22/joplin#4086]
When you set an alarm for a to-do, the phone keeps vibrating when Joplin gives you the reminder at the set time. This does not stop until you unlock your phone and lock it again.

## Environment

Joplin version: 1.3.12
Platform: Android
OS specifics: Android version 8.1

## Steps to reproduce
1. Create a new to-do
2. Set an alarm for that to-do

## Describe what you expected to happen
I expected that at the set date and time, I just got a reminder and that the phone vibrates ones or twice as normal.

## What actually happened
When I got the notification, my phone keep giving short vibration burts where I should normaly give only one or two. To stop the vibration, you would have to unlock your phone and re-lock it. Also, take a look at the screenshot below. Not sure if I have seen the "-' below the notification title before

[screenshot](https://i.imgur.com/JZCxjBU.png)

## Logfile
I copied only the part of the bug report from the moment when I created a test notification (19:01) and above. The notification was set for 19:05. I didn't know how to upload the full report.

Date,Level,Message
11-14T19:13:10,30,"""RevisionService::maintenance: Done in 332ms""
11-14T19:13:10,30,"""RevisionService::collectRevisions: Created revisions for 0 notes""
11-14T19:13:10,30,"""RevisionService::maintenance: Service is enabled""
11-14T19:13:10,30,"""RevisionService::maintenance: Starting...""
11-14T19:11:47,30,"""RevisionService::maintenance: Done in 30865ms""
11-14T19:11:47,30,"""RevisionService::collectRevisions: Created revisions for 0 notes""
11-14T19:11:46,30,"""RevisionService::maintenance: Done in 25ms""
11-14T19:11:46,30,"""RevisionService::maintenance: Service is enabled""
11-14T19:11:46,30,"""RevisionService::maintenance: Starting...""
11-14T19:11:16,30,"""RevisionService::maintenance: Service is enabled""
11-14T19:11:16,30,"""RevisionService::maintenance: Starting...""
11-14T19:10:40,20,"""Could not refresh lock - cancelling sync. Error was:", "Error: Item does not exist
Code: itemNotFound
Header: {"map":{"x-ms-ags-diagnostic":"{\"ServerInfo\":{\"DataCenter\":\"West Europe\",\"Slice\":\"SliceC\",\"Ring\":\"5\",\"ScaleUnit\":\"003\",\"RoleInstance\":\"AGSFE_IN_47\"}}","client-request-id":"6a1df85d-b365-4959-9125-b3d46d9fe491","content-length":"285","strict-transport-security":"max-age=31536000","request-id":"6a1df85d-b365-4959-9125-b3d46d9fe491","cache-control":"private","content-type":"application/json","date":"Sat, 14 Nov 2020 18:10:40 GMT"}}
Request: PUT https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/locks/sync_mobile_346c7610744d4536beac6080ad0f1492.json:/content null "{\"type\":\"sync\",\"clientType\":\"mobile\",\"clientId\":\"346c7610744d4536beac6080ad0f1492\",\"updatedTime\":\"1605377267776\"}" {"headers":{"Content-Type":"text/plain","Authorization":"bearer EwCAA8l6BAAU6k7+XVQzkGyMv7VHB/h4cHbJYRAAAU0hYvhV2m8buP9gDZTIa9WU1AxSkFfChqD114j/LxflKbYapiCldR7oNsseSvIGxspO8WXHDJrRJmdV9H37zOJ+t4MaRIIT8vlpU8fqQbDuSBBkXKsJ2kKjol1220XKmiIHRW13QYMOUuJYjKfzxD61H6ZI4dPm1a0WR9X5K4vGfgnFwvLvRLotjkMhH192s+/aQtFDi6E9k4kkczgjgVGfmXt2MAcOj/l+5ywlIIhC8sNjIUMdlK6BvaeVgoLMP00mNjzaLGnTHF63bH1718iw2tSGQNcjrGYMh3qARqh8VHMRAReHPC5YfpDz3QQtbVKASZWf6p7Bq8u171Z9Ul4DZgAACJRLvnNLVQ5uUALA/iZ0Cw4k5hvkzrZv+0YVr2MHjMSoKi7C3rDNNRZfHXSTvTLghCxuHF6FI9lSFLp7apaAZlADgJFUrkBn8wXfTYK+cpv5bO4LVusccqEVbjowlyPOpq51QBSw9pAKfY+RNomyAqd4qRxZn51TaZgETK+rjg4ifP9WFcRvWD6018WV/Vnjh0IcX3ot1yJ9KlIHYP1y77rsBPdcVnxwlU3JI9q18mG/KcKZzTm/sHzX2YM0hnldQKlG8i4p+/WYoz72e9wYpbmSGiVfJLx44bEZsZfo+sufn+8O36IPU
value@index.android.bundle:1258:2933
index.android.bundle:1258:6903
y@index.android.bundle:109:587
index.android.bundle:109:1890
y@index.android.bundle:109:587
o@index.android.bundle:109:1066
index.android.bundle:109:1209
f@index.android.bundle:125:155
index.android.bundle:125:864
y@index.android.bundle:130:581
C@index.android.bundle:130:947
callImmediates@index.android.bundle:130:3004
value@index.android.bundle:27:2919
index.android.bundle:27:1095
value@index.android.bundle:27:2611
value@index.android.bundle:27:1065
value@[native code]
value@[native code]""
11-14T19:10:40,30,"""Total resources: 55""
11-14T19:10:40,30,"""Total folders: 25""
11-14T19:10:40,30,"""Total notes: 137""
11-14T19:10:40,30,"""createRemote: 1""
11-14T19:10:40,30,"""Operations completed: ""
11-14T19:10:40,30,"""updateRemote: 1""
11-14T19:10:39,30,"""TaskQueue.stop: syncDownload: Done, waited for 0""
11-14T19:10:39,30,"""TaskQueue.stop: syncDownload: waiting for tasks to complete: 0""
11-14T19:10:39,30,"""RevisionService::maintenance: Done in 321ms""
11-14T19:10:39,30,"""RevisionService::collectRevisions: Created revisions for 0 notes""
11-14T19:10:39,30,"""RevisionService::maintenance: Service is enabled""
11-14T19:10:39,30,"""RevisionService::maintenance: Starting...""
11-14T19:07:45,30,"""RevisionService::maintenance: Done in 337ms""
11-14T19:07:45,30,"""RevisionService::collectRevisions: Created revisions for 0 notes""
11-14T19:07:45,30,"""Synchronisation is already in progress. State: in_progress""
11-14T19:07:45,30,"""Starting scheduled sync""
11-14T19:07:45,30,"""Preparing scheduled sync""
11-14T19:07:45,30,"""Running background sync on timer...""
11-14T19:07:45,30,"""RevisionService::maintenance: Service is enabled""
11-14T19:07:45,30,"""RevisionService::maintenance: Starting...""
11-14T19:05:14,30,"""SearchEngine: Updated FTS table in 2474ms. Inserted: 1. Deleted: 0""
11-14T19:05:13,30,"""Settings have been saved.""
11-14T19:05:13,30,"""RevisionService::maintenance: Done in 2386ms""
11-14T19:05:13,30,"""RevisionService::collectRevisions: Created revisions for 1 notes""
11-14T19:05:13,30,"""Settings have been saved.""
11-14T19:05:13,30,"""Settings have been saved.""
11-14T19:05:12,30,"""ResourceService::deleteOrphanResources:", "[]""
11-14T19:05:12,30,"""Sync target info:", "{"version":2}""
11-14T19:05:12,30,"""ResourceService::indexNoteResources: Completed""
11-14T19:05:12,30,"""Saving settings...""
11-14T19:05:12,30,"""Saving settings...""
11-14T19:05:12,30,"""Saving settings...""
11-14T19:05:11,30,"""Starting scheduled sync""
11-14T19:05:11,30,"""SearchEngine: Updating FTS table...""
11-14T19:05:11,30,"""Preparing scheduled sync""
11-14T19:05:11,30,"""RevisionService::maintenance: Service is enabled""
11-14T19:05:11,30,"""RevisionService::maintenance: Starting...""
11-14T19:05:11,30,"""ResourceService::indexNoteResources: Start""
11-14T19:01:03,30,"""AlarmServiceDriver: Created new alarm:", "{"id":5}""
11-14T19:01:02,30,"""Scheduling notification for note 3cdfb1483a3a4975b77aa8caf6b26b71", "{"id":24,"noteId":"3cdfb1483a3a4975b77aa8caf6b26b71","date":"2020-11-14T18:05:00.000Z","title":"Test notification"}""
11-14T19:00:50,30,"""DecryptionWorker: completed decryption.""
11-14T19:00:50,30,"""Settings have been saved.""
11-14T19:00:50,30,"""DecryptionWorker: starting decryption...""

**Comment by laurent22** [comment]
This is most likely this upstream issue: https://github.com/emekalites/react-native-alarm-notification/issues/82

**Comment by roman-r-m** [comment]
I had a look at `react-native-alarm-notification`, basically stopping an alarm after clicking a notification is just not implemented. I think the author misunderstood the API and assumed it will happen automatically.

I can try submitting a PR to that lib but it looks abandoned. Worst case I can just fork it.

**Comment by Yajo** [comment]
I just wanted to clarify that discarding the notification also doesn't stop the noise.

**Comment by roman-r-m** [comment]
> I just wanted to clarify that discarding the notification also doesn't stop the noise.

Only if Joplin is not running in background. If it does, then the sounds stops upon dismissing the notification

**Comment by laurent22** [comment]
> I can try submitting a PR to that lib but it looks abandoned. Worst case I can just fork it.

Indeed there's no point submitting a PR as you won't get an answer from the author, but if you create a fork that fixes this bug many people are likely to be interested.

**Comment by roman-r-m** [comment]
@laurent22 forgetting about this issue for a moment, do we want this to be an alarm or a notification (on Android). The difference is an alarm is always looping whereas a notification only plays once. And they use different channels too.

I think it should be a notification. I'd find it quite annoying if Joplin would keep playing a sound until dismissed. But then again, I don't use alarms in Joplin.

**Comment by laurent22** [comment]
Right, that should indeed be a notification. It makes a sound or vibrate once, and display a notification message.

**Comment by roman-r-m** [comment]
FYI - I am still working on fixing this and a few other issues related to alarms. That lib is really badly written - at least on Android side - so it's going to take some time.

**Comment by laurent22** [comment]
That's good to hear. The standard for notifications on React Native is Firebase, but I moved away from this package because of how big it is and the analytics stuff in it. I thought that other package we're using now was pretty good, but looks like it isn't and the owner is no longer active, so if you can come up with an improved version of it that would be great, and I think would be of interest for many people.

**Comment by WebMaster50** [comment]
Is this issue now going to solved by changing the notification from an alarm to a notification? That would be a perfect fix for me. A single vibration/sound on the time I want is fine.

**Comment by roman-r-m** [comment]
> Is this issue now going to solved by changing the notification from an alarm to a notification?

Not quite. In fact right now it uses the media channel, not the alarm one. It's looping because of another bug there.
