### ISSUE TITLE
External Editor Quirks

### ISSUE THREAD

**Issue by mohmad-null** [laurent22/joplin#4087]
1.3.18 Desktop on Windows 7

A) Click "External Editing" - An external editor does not appear, however Joplin switches to "external editing" mode. I assume this is because Joplin can't auto-guess at an editor. However given that Joplin evidently hasn't tried to open an editor, it shouldn't switch into "this is open in an external editor" mode.

B) The FAQ https://joplinapp.org/faq/ - Says:
> If this does nothing or you want to change it for Joplin, you need to configure it in the Preferences -> Text editor command.

There is no "Preferences - > Text" "command". I assume it means the menu: `Tools -> Options; General`?

B2) Trivial, but that same FAQ goes on to say:
> Note that the path to directory...

This is grammatically invalid.

C) Continuation of (A), but more a feature suggestion: If Joplin can't open an editor it should tell the user in some way explicitly (a dialog), rather than make the user wonder why Joplin hasn't done anything in response to a command.

**Comment by matt99991** [comment]
Another external editor issue is with BBEdit. I ran across the same problem reported by another user on the [Joplin discourse forum](https://discourse.joplinapp.org/t/bbedit-for-osx-as-an-external-editor-is-empty/3357) when trying to set up BBEdit 13.5.2 as my external editor. I posted to the BBEdit discussion group and it sounds like it's something on Joplin's side but potentially resolvable if there would be a way to tell Joplin to run a command-line tool for the external editor.
