### ISSUE TITLE
Notepad++ Opens as ANSI

### ISSUE THREAD

**Issue by mohmad-null** [laurent22/joplin#4088]
1.3.18 Desktop on Windows 7

I've pointed Joplin at Notepad++.

Using the default "Welcome to Joplin" note - Open in External Editor

It opens in Notepad++. But the file it opens is encoded with ANSI. This means all the Unicode characters are appearing as funky stuff. I.e., this is the first unicode character (the spiral notepad):
ðŸ—’ï¸

**Comment by CalebJohn** [comment]
Isn't this an issue with Notepad++ not correctly detecting the encoding?

**Comment by mohmad-null** [comment]
Hmmm, Notepad++ correctly detects the coding of every other file I open with it so I assumed it was Joplin. (I've been using NPP for years and Joplin for hours...).

PilotEdit opens the file as UTF8

Other applications I tried just default to UTF8 for everything.
