### ISSUE TITLE
v.1.3.13

### ISSUE THREAD

**Issue by Befo** [laurent22/joplin#4090]
Hi, I have noticed my apps do not sync encryption key among themselves.
I have moved from Standard Notes using the guide I have found on the welcome notes. After having imported the notes on the desktop I enabled there encryption and then started syncing over OneDrive.

Opening the mobile app I can see it is downloading all of the encrypted items but it does not seem to share any encryption key.
I then tried to set it manually but it is only adding new keys with the same passphrase, which also I cannot delete.

Is this a bug?

## Environment

Joplin version:  1.3.13
Platform: Ubuntu / Android
OS specifics: Ubuntu 20.04 / Android 10 (Motorola stock)

## Steps to reproduce

1.  Encrypt with desktop
2.  Sync over OneDrive from desktop
3.  Sync over OneDrive on mobile

## Describe what you expected to happen
I would expect encryption keys to be synced as well.

## Logfile

Inside the log  of the mobile app the DecryptionWorker states that it cannot start because no master key is loaded and perhaps a more helpful error is that the app logs as an actual error that it cannot upgrade to database v34 with a message of "no such module: spellfix1".

**Comment by Befo** [comment]
Update:
After clearing the OneDrive backup and having re-synced the desktop with OneDrive, the mobile app is not trying to synch over the "App/Joplin 1/" folder instead out of the current "App/Joplin" one.

**Comment by laurent22** [comment]
Please use the forum for support and consider giving proper titles to your posts.

**Comment by Befo** [comment]
OK, I believe I have been too friendly, this is a bug. The only options I have to sync over OneDrive is which account to use and that cannot be changed after setting it the first time. Your app is doing random things instead of syncing with a folder on OneDrive. Please read the OneDrive Api doc and please consider proper development and feature documentation.

For sure I won't use this app.
Have a nice day.
