### ISSUE TITLE
joplin-desktop doesn't start after update

### ISSUE THREAD

**Issue by diggidong** [laurent22/joplin#4091]
The joplin-desktop application is not starting after the update. Seems, that a file "/usr/bin/joplin-desktop/joplin" is missing.

## Environment

Joplin version: 1.3.18-1
Platform: Linux
OS specifics: Arch Linux, installed joplin with "yay"

## Steps to reproduce

1. starting joplin-desktop: ` joplin-desktop` 
error message: `/usr/bin/joplin-desktop: line 12: ./joplin: No such file or directory`
2. inspecting "/usr/bin/joplin-desktop": ` head /usr/bin/joplin-desktop -n 15`
`[...]
readonly joplin_dir="/usr/share/joplin/"
[...]
cd $joplin_dir
./joplin "$@"`
3. no "joplin" file in that directory: `ls -al /usr/share/joplin |grep joplin`

**Comment by laurent22** [comment]
please bring the issue with the package developer
