### ISSUE TITLE
Android 11 permission issue

### ISSUE THREAD

**Issue by j710** [laurent22/joplin#4092]
Fresh install on Android 11 / Pixel 5 /Joplin 1.3.13. Joplin asks for permission to Media and not files. On same version installed on Android 11 (upgraded from Android 9) Joplin has permission to Files.

This prevents any syncing to local filesystem and therefore breaks the app entirely for that use case.

Thanks

**Comment by j710** [comment]
@laurent22 
I downgraded to 1.2.5 and it fixed the scope issue. Works as expected.  I'd edit and do a PR if I could but it's beyond me. Hopefully that's helpful

**Comment by 12ian34** [comment]
Also experiencing this issue on same versions as @j710. Will downgrade to 1.25 for now.

**Comment by j710** [comment]
@12ian34 I should also mention I successfully updated to the latest from the play store and it inherited the prior permissions

**Comment by 12ian34** [comment]
@j710 appreciate the update. Just done the same and it worked for me too.

**Comment by 12ian34** [comment]
Perhaps this issue should be closed. It's duplicated by the (newer..) #4122
