### ISSUE TITLE
Export of a conflict does not create a file

### ISSUE THREAD

**Issue by Pete-C2** [laurent22/joplin#4095]
## Environment

Joplin version: 1.2.6
Platform: Windows
OS specifics: 7

## Steps to reproduce

1. Create a conflict between devices
2. In the Conflicts section, right click on the conflicted note and Export Markdown
3. The only results is an empty _resources folder (in this case I don't believe that there should have been any files), but NO markdown file.

## Describe what you expected to happen

The conflicted note should be saved in the chosen folder as a .MD file.

## Logfile

CommandService::execute: showModalMessage {message: "Exporting to "C:\bin\Joplin" as "md" format. Please wait..."}
C:\Program Files\Joplin\resources\app.asar\InteropServiceHelper.js:161 Export result:  {warnings: Array(0)}
C:\Program Files\Joplin\resources\app.asar\lib\services\CommandService.js:141 CommandService::execute: hideModalMessage null

**Comment by laurent22** [comment]
Most features aren't available within the conflict notebook because it's special, so there shouldn't have been any export item in there (I've now removed it). You could do what you want by first moving the note to a regular notebook.

**Comment by Pete-C2** [comment]
Since there is no way within Joplin to do a conflict comparison/merge, it would be more useful to be able to export conflicts. I resorted to editing the conflict (so that I could see the source markdown text), copying and saving as a markdown file, exporting the equivalent note and then using a file comparison application to find the differences so that I could copy the bits I needed.

**Comment by laurent22** [comment]
In fact it's easier to enable export for conflict notes than to disable everything, so it should work from next version.
