### ISSUE TITLE
Joplin did not automatically update despite checking that option

### ISSUE THREAD

**Issue by Steve-Z** [laurent22/joplin#4096]
## Environment

Joplin version: 1.2.6.AppImage
Platform: Linux
OS specifics: Pop!_OS 20.04

## Steps to reproduce

1. Open Joplin > Tools > Options > Application
2. Confirm that "Automatically update application" is checked
3. Joplin > Help > About Joplin to show current version (1.2.6)
4. Joplin > Help > Check for updates... to confirm new version is available (1.3.18)
![Screenshot from 2020-11-16 16-36-40](https://user-images.githubusercontent.com/31359112/99319634-78c9d800-282f-11eb-9b6e-5cfbc76dedde.png)

## Describe what you expected to happen
I expected Joplin to either update itself silently or to notify me that a new version is available for download (without my having to manually "Check for updates".

## Logfile
Most recent 200 lines of log.txt with debugging enabled which includes all of today.

[Joplin_log.txt](https://github.com/laurent22/joplin/files/5550233/Joplin_log.txt)

**Comment by CalebJohn** [comment]
For reference, here is the relevant bit of code
https://github.com/laurent22/joplin/blob/a808281dd2b12fd1bd6b0a6cdebccdc8eb66b431/packages/app-desktop/app.ts#L640

**Comment by Steve-Z** [comment]
@CalebJohn Thanks for pointing that out. Of course, one should not expect a user to search through code.

Perhaps a notation could be added to that Tools > Options > Application pane, similar to how it says 

- [ ] Show tray icon... 

> Note: Does not work in all desktop environments.

Under 
- [ ] Automatically update...

it could say

> Note: Does not work in LInux

in the same gray italic font. I would close this issue, but perhaps you could change the status to "Suggestion", if that is possible.

Thanks again.

**Comment by CalebJohn** [comment]
@Steve-Z Sorry about that, I didn't mean to imply that everyone should be checking the code. It was more of a reference for myself or whoever else happens over this and was surprised to see that there was even the option to enable automatic updates on linux.

You propose a good easy to implement solution. I'm going to mark this as a good first issue and hopefully someone interested will  pick this up!

**Comment by anshuman9999** [comment]
Hello, I want to work on this issue but I am not able to locate the tsx file in which the gray text is available. Can you please guide me on how to find it.
Thanks

**Comment by laurent22** [comment]
That makes sense, but I would rename "Note: Does not work in all desktop environments." (as it's too vague) to "Note: Does not work in Linux" and indeed use the same string for the Automatic Update option.

**Comment by CalebJohn** [comment]
@anshuman9999 The file you're looking for is `packages/lib/models/Setting.ts`

**Comment by anshuman9999** [comment]
@CalebJohn Thank you so much for helping me there. I have found the code for adding the description. Should I add this description for all platforms - "Note: Does not work in linux" or should I add something else for linux.
Thanks

**Comment by CalebJohn** [comment]
> Should I add this description for all platforms - "Note: Does not work in linux" or should I add something else for linux.

Actually for this one you can changes the `public` key to `platform !== 'linux'` which will disable the option entirely on linux.

> should I change the description for the show tray icon label to "Note: Does not work in linux" as pointed above?

Yes please

**Comment by anshuman9999** [comment]
@CalebJohn OK, I'm on it

**Comment by anshuman9999** [comment]
@CalebJohn Thank you so much for helping me out. I have made the changes discussed above and created a PR  for it. Please review it.
Thanks

**Comment by anshuman9999** [comment]
@laurent22 can you please tell me what I have to do exactly to get this to work.
Thanks

**Comment by Steve-Z** [comment]
@anshuman9999 I am not certain, but perhaps line 705:
`autoUpdateEnabled: { value: false, type: SettingItemType.Bool, section: 'application', public: true, ...`
Change `public: true` to `public: platform !== 'linux' `
Does that make sense? While we are waiting for an authoritative answer.

**Comment by anshuman9999** [comment]
@Steve-Z I made the same change in the PR that I created. Along with this, I also changed the show tray icon's button description from 'Note: Does not work in all desktop environments' to 'Note: Does not work in linux' as pointed above. But, that PR was closed because I wrote 'linux' in place of 'Linux'. Should I make the change to 'L' and make a PR again?

**Comment by imkaran315** [comment]
i want to work on the issue. Plz assign me the issue.

**Comment by Daeraxa** [comment]
You want to work on a closed issue? What do you propose you would do when it has already been solved over two years ago?
