### ISSUE TITLE
Can not import  NixNote nnex file

### ISSUE THREAD

**Issue by Drreeww** [laurent22/joplin#4097]
## Environment

Joplin version: Joplin 1.3.18 (prod, linux)
Platform: Linux
OS specifics: Ubuntu 16.04

## Steps to reproduce

1. file->import->ENEX-Evernote Export File(as Markdown)
2. 
3. 

## Describe what you expected to happen
enex file can be import

## Logfile
but enex  file doesn't appear in the dialog box

**Comment by CalebJohn** [comment]
Nixnote exports are not necessarily the same as enex exports. From what I remember they try to conform as close as possible, but it's challenging. Joplin does not support importing nnex files.

To get around this you can try changing the extension of your exports from .nnex -> .enex or use [a tool](https://github.com/exomut/evernote-dump) to convert your exports into markdown files that Joplin can import.

**Comment by Drreeww** [comment]
the tool you mentioned  is available for Mac and Window, but my computer os is ubuntu. 
I also tried rename .nnex to .enex, joplin can import .enex, but can not display normally

**Comment by CalebJohn** [comment]
Probably the easiest option would be to get access to a windows desktop and install the evernote client. From there you can export an actual enex and import it into Joplin.

Alternatively you can find a tool that can convert nnex to markdown format. You can ask [on the forum](https://discourse.joplinapp.org/) to see if other users have done this.
