### ISSUE TITLE
Fatal error: Trying to access React before it has been set!!!

### ISSUE THREAD

**Issue by elmaester** [laurent22/joplin#4098]
Updated Joplin from 1.0.227 to 1.4.10 by replacing the AppImage.

Seeing this error when running Joplin, the app won't start anymore.
![image](https://user-images.githubusercontent.com/54346168/99417625-cb27f900-2902-11eb-94ae-f2c7fd000d06.png)

Can't go back to the older version either, getting this error now
![image](https://user-images.githubusercontent.com/54346168/99418068-48536e00-2903-11eb-9399-1636b77bf9d1.png)

## Environment

Joplin version: 1.4.10
Platform: Linux
OS specifics: Manjaro

## Steps to reproduce

1. Have Joplin v1.0.227 installed as AppImage
2. Start using the v1.4.10 AppImage instead
3. Accept the suggestion in the orange nagbar, I can't recall what it said, but required a restart afterwards
4. Optional: be me?

## Describe what you expected to happen

Expected the app to launch as usual and not crash with the error seen in the screenshot.

## Logfile

The app won't start at all, so I can't follow instructions to obtain a log.

**Comment by saimn** [comment]
Same here.

**Comment by macearl** [comment]
I'm also facing this issue, running an arch (-based) system and updated the appimage through the AUR package.

If there are any debug steps you need me to try let me know.

**Comment by saimn** [comment]
Thanks for the fix (and for the great software btw !) :slightly_smiling_face:

**Comment by elmaester** [comment]
Many thanks from me too!
