### ISSUE TITLE
Sync Issues

### ISSUE THREAD

**Issue by Curtis-Mortensen** [laurent22/joplin#4107]
![Debug](https://user-images.githubusercontent.com/56660391/99560893-9f992300-2983-11eb-8017-ab1e6d487136.jpg)

## Environment
Joplin for Desktop

Joplin 1.2.6 (prod, win32)

Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f5f117cb (master)

OS specifics: Windows 10 Home 1909

## Steps to reproduce

1. Open Joplin
2. Auto-sync should start
3. 

## Describe what you expected to happen
I expected it to sync, it showed that it had 190 items left to sync and had create 53 new local items, but then the console showed that sync failed to start. I am running one update behind on Windows, but the update is from Lenovo...

## Logfile
[-1605717665726.log](https://github.com/laurent22/joplin/files/5561412/-1605717665726.log)

**Comment by CalebJohn** [comment]
@Curtis-Mortensen Your screenshot and attached log file don't show any errrors. And from your description it's not clear what exactly your issue is.

Is the issue that you are missing sync items? If so please us what sync method you use. Also if you could check the synchronisation status page (Help -> Synchronization Status), that might be able to give you some more information.

**Comment by Curtis-Mortensen** [comment]
Yes, to be clear, the issue is that it showed that it had initiated sync, but it wasn't actually syncing. Within the command log it showed 
"C:\Program Files\Joplin\resources\app.asar\lib\services\CommandService.js:141 CommandService::execute: synchronize {syncStarted: false}"
That was the same output when I made my previous bug, which was also a sync issue. 
In my screenshot it showed that it created 145 items but that was incorrect, it didn't create any. It also showed that it was fetching 589 items, although it really needed to update less than 10. In addition, the screenshot shows that it labeled the sync as "completed" although it hadn't synced all 589 items. 
All in all, the sync display seemed to be random and have no bearing on what Joplin was actually doing. It changed every time, but never synced. Hopefully that helped. 

I use Microsoft OneDrive sync, with encryption.

**Comment by CalebJohn** [comment]
Thanks for following up on this, I'm glad to hear that things seem to be working now!

Unfortunately there really just isn't enough to go on here, as far as I can tell there wasn't an error here but more likely the sync system taking a couple of syncs to get caught up. I've removed the bug label, hopefully this doesn't happen again!
