### ISSUE TITLE
Android - Note with checkbox, goes to the top anytime I check/uncheck a box

### ISSUE THREAD

**Issue by deneb2** [laurent22/joplin#4108]
## Environment

Joplin version: Android app 1.3.13, Database v34
Platform: Android 10
OS specifics: Oxygen OS 10.0.14

## Steps to reproduce

1. Create a note long enough to have the scrollbar on the side;
2. at the end of the note add a checkbox: `- [ ] something`;
3. exit from edit mode to see the note;
4. scroll down and check the box clicking on it;
5. _BUG_: the note goes back to the top.

## Describe what you expected to happen
Whenever I check/unckeck checkboxes, I would like to maintain the same position. 
_Example_: Suppose you have a shopping list and you are just checking one think after another, starting all the times from the beginning of the note, makes the app unusable.

**Comment by laurent22** [comment]
Fixed in next version
