### ISSUE TITLE
Keyword cannot be searched in F6 search mode, but CTRL + Shift + P can be searched

### ISSUE THREAD

**Issue by qljiong** [laurent22/joplin#4111]
## Environment

Joplin version: Joplin 1.4.10 (prod, win32)
Platform: windows 10 home
OS specifics: 20H2  19042.630

## Steps to reproduce

1. Create a Markdown file and write a piece of SQL code
2. The [timestamp] keyword is included in the code
3. If the keyword [timestamp] is searched by F6 search mode, the relevant markdown file cannot be searched
4.But by CTRL + Shift + P direct search keyword [timestamp], you can find the correct results.

## Describe what you expected to happen
I want the F6 search mode to be consistent with CTRL + Shift + P mode .

## Logfile
not have

**Comment by laurent22** [comment]
I think you need to search for `/[timestamp]` https://joplinapp.org#searching
