### ISSUE TITLE
andriod app can not sync up with Webdav 

### ISSUE THREAD

**Issue by Drreeww** [laurent22/joplin#4112]
## Environment

Joplin version: Joplin 1.0.320
Platform: andriod
OS specifics: miui 11.1.19

## Steps to reproduce

1. click sync button on android app

## Describe what you expected to happen
sync up with Webdav

## Logfile
Last Error: Error: Sync version of the target (2) does not match sync version supported by client (1).Please upgrade your client.

-->

**Comment by konamichou** [comment]
Your Joplin version is to old.
Install the new version,the problem will go  
Download from here :https://github.com/laurent22/joplin-android/releases
