### ISSUE TITLE
Search/new note layout broken in empty notebooks

### ISSUE THREAD

**Issue by Derkades** [laurent22/joplin#4113]
Non-empty notebook:
![image](https://user-images.githubusercontent.com/15892014/99663320-b19fc200-2a66-11eb-8957-428eb26d1339.png)

Empty notebook:
![image](https://user-images.githubusercontent.com/15892014/99663299-a9e01d80-2a66-11eb-9731-210ff4cf7a49.png)

## Environment

Joplin version: 1.4.10
Platform: Linux
OS specifics: Ubuntu 20.10 (KDE)

## Steps to reproduce

1. Create empty subnotebook

**Comment by laurent22** [comment]
Will be fixed in next version.
