### ISSUE TITLE
Pasted links are text-only

### ISSUE THREAD

**Issue by ipentest** [laurent22/joplin#4114]
## Environment

Joplin version: 1.4.7 (prod, darwin)
Platform: Mac
OS specifics: macOS Big Sur 11.0.1 (but this has been happening even with the earlier versions of OSX)

## Steps to reproduce

1. Copy a link you've visited
2. Paste the link into a note or todo in Joplin
3. The link is not clickable. Earlier, just clicking on the link in the preview mode would open it in the default browser. Now however, it needs to be explicitly selected, copied and pasted into the browser

## Describe what you expected to happen

The link is not clickable. Earlier, just clicking on the link in the preview window would open it in the default browser. Now however, it needs to be explicitly selected, copied and pasted into the browser

Thanks and have a wonderful day,
Kiran

**Comment by dpoulton-github** [comment]
I believe that what you have noticed here is that Joplin has been brought into line with Markdown standards. In Markdown nothing is **assumed** to be a URL unless you tell it so. Assuming what is a URL can cause problems:

- when the text is in fact a file name that looks like a URL such as **python_script.py**
- when the text is wanted as text and not an active link such as, "Do not click on https://malware.com" (as you will see, GitHub will present anything that looks like a URL as a URL)

Joplin 1.4 now requires the user to confirm that what appears to be a URL is, in fact, a URL **AND** that the user wants it to be "live". 

This is done either by making it a "named" link

`[link_name](https://example.com)`

or a plain link

`<example.com>`

So if you want any pasted text to be a "live" link just surround it in angled brackets.

**Comment by paramecie** [comment]
I'm not sure to get it, very sorry.
In 2020, Notepad++, Word, Evernote, Wordpad, Open office, many many docs/notes apps show pasted links as "live links".

It would be very nice to have this in Joplin especially while using WYSIWYG.

Right now when pasted in WYSIWIG (Rich Text editor), it doesn't appear as a link, but when changing to another note and coming back, it then appears as an link... Which is also a strange behaviour.

**Comment by ipentest** [comment]
Awesome, it seems to be working fine in the WYSIWYG editor in 1.4.12! I would also like to take this opportunity to thank each and every contributor of Joplin for making it what it is! Happy Thanksgiving team J
