### ISSUE TITLE
Toggle Editors loses formatting

### ISSUE THREAD

**Issue by Tyrewt** [laurent22/joplin#4115]
Toggling Editors from _Rich Text_ to _Markdown_ and then back to _Rich Text_, the formatting (spacing) is lost on the document.
One incorrect keypress (Toggling editor) and all your formatting is lost. I've provided screenshots of this behaviour below.

**Most likely this issue can be overcome with the following two feature requests**
1. [Toggle Editor lock](https://discourse.joplinapp.org/t/please-add-an-option-to-set-editor-toggle-limitations/12336)
2. [Viewer Toggle](https://discourse.joplinapp.org/t/rich-text-editor-viewer-toggle/12449)

**Rich Text**
![1](https://user-images.githubusercontent.com/21961083/99703764-810b5880-2a65-11eb-9e9c-a2a0802a556c.png)

**Rich Text toggled to Markdown**
![2](https://user-images.githubusercontent.com/21961083/99703781-88cafd00-2a65-11eb-8574-b24cb15509e7.png)

**Markdown toggled back to Rich Text**
![3](https://user-images.githubusercontent.com/21961083/99703803-8ec0de00-2a65-11eb-89d1-9df8de4766b6.png)

**Comment by dpoulton-github** [comment]
I think that what you have found is that Joplin is a "Markdown" note-taking app. The WYSIWYG editor (beta, experimental) allows actions that Markdown does not. In Markdown additional blank lines are ignored. So, as you move away from WYSIWYG into Markdown, Markdown rules are applied and the extra lines disappear. When you move back to WYSIWYG the changes have been made and the extra lines have gone.

**Comment by Tyrewt** [comment]
Understood. Perhaps those two feature requests would be useful in addressing this concern?
