### ISSUE TITLE
Attachment error in notes imported from ENEX to HTML containing PDFs

### ISSUE THREAD

**Issue by betamaxdroid** [laurent22/joplin#4119]
## Environment

Joplin version: 1.3.18 (prod,win32)
Joplin 1.3.18 (prod, win32)

Client ID: b49bbff1aadf415fa1f50edd8279c71d
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: 6b75485a1 (master)
Platform: Windows
OS specifics: Win10 20H2 Build 19042.572)

## Steps to reproduce

1. Import an evernote enex with note(s) containing pdf into Joplin's HTML format
2. Navigate to the note, and click on the PDF link
3. 

## Describe what you expected to happen
Expect for the PDF to open.

**Comment by DG0lden** [comment]
I can confirm the bug.

By clicking on PDF attachment I get following error message:
![зображення](https://user-images.githubusercontent.com/2138893/99781546-46162d00-2b18-11eb-888c-ec0a3f8e07ca.png)


Joplin 1.3.18 (prod, darwin)

Client ID: 07ed4916edaf4b5b9724de47a47d20ee
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: 6b75485 (master)

**Comment by laurent22** [comment]
Please provide an ENEX sample file

**Comment by DG0lden** [comment]
Compressed, since Github doesn't allow `.enex` to be attached directly.
[TestNoteWithPDF.enex.zip](https://github.com/laurent22/joplin/files/5572895/TestNoteWithPDF.enex.zip)

**Comment by fellowweb** [comment]
Hi Laurent, could we please reopen this?

I'm experiencing this again with multiple notes exported from Evernote Legacy v6.25.3 on Windows 11 into ENEX and importing them as HTML into Joplin 2.12.19 (prod, win32). Example ENEX [attached](https://github.com/laurent22/joplin/files/13328324/Lego_Duplo_Family_House.zip) (contains a LEGO building manual as PDF as sole content).

This is what the imported note looks like:

![grafik](https://github.com/laurent22/joplin/assets/150602852/cb7ac429-95f1-4d46-9ed9-bd0ad2657408)

**Comment by laurent22** [comment]
Please open a new issue for this

**Comment by fellowweb** [comment]
Thank you, Laurent! [Done](https://github.com/laurent22/joplin/issues/9288).
