### ISSUE TITLE
Adding notes to nextcloud

### ISSUE THREAD

**Issue by steliosmilidonis** [laurent22/joplin#412]
### Operating system

- Android

### Application

- Mobile

Adding files to nextcloud created .md files both for notebook as well as the notes themselves. Is this intended?

**Comment by laurent22** [comment]
Yes, it's working as intended. There's more info about it in the faq.

**Comment by james-at-purism** [comment]
A better UX would be for these .md file to be dumped into a Joplin folder when syncing to Nextcloud (and probably others) as opposed to filing up the home folder.  Could this change be easily implemented?
