### ISSUE TITLE
Desktop: Clearing search field changes focus to another note

### ISSUE THREAD

**Issue by archont00** [laurent22/joplin#4123]
## Environment

Joplin version: 1.3.18
Platform: Linux
OS specifics: AppImage

## Steps to reproduce

1. Search for a note (F6 + "pattern").
2. In the list of matched notes, select one.
3. Clear the search field (to get rid of the highlighted search pattersn in the note text or from whatever other reason).
4. Joplin will change focus to a different note (actually to the first note in the previously selected notebook)

## Describe what you expected to happen

Joplin should keep focus on the note, which was selected during the search. (Either by user or as a result of the search.)

This issue was already fixed some time ago, so it seems to be a regression. See bug https://github.com/laurent22/joplin/issues/862 (although differently described, the problem is as explained above).

**Comment by laurent22** [comment]
Fixed in v1.4 pre-release
