### ISSUE TITLE
Certain string with double underscore makes the line render as bold

### ISSUE THREAD

**Issue by overseeing** [laurent22/joplin#4126]
## Environment

Joplin version: 1.3.18
Platform: tested on macOS and Linux
OS specifics: macOS Catalina and Linux Mint 20

## Steps to reproduce

1. Create a new note and have it in code edit mode
2. Type this, two underscores and a dot, no spaces: `__.` 
3. It mistakenly emboldens the line. Keep typing more text in that line to clearly see.

## Describe what you expected to happen

AFAIK no Markdown syntax means that should make it render as bold, thus the code line shouldn't bold.

**Comment by CalebJohn** [comment]
@overseeing 
This is an interesting case, thank you for bringing it up. Joplin follows the CommonMark markdown specification (with a few exceptions). So your question prompted me to look into the specification to see what the correct behaviour is.

Based on [section 6.4](https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis) the behaviour you described is actually to spec. I'll copy below the relevant bits

> First, some definitions. A delimiter run is either a sequence of one or more * characters that is not preceded or followed by a non-backslash-escaped * character, or a sequence of one or more _ characters that is not preceded or followed by a non-backslash-escaped _ character.

> A left-flanking delimiter run is a delimiter run that is (1) not followed by Unicode whitespace, and either (2a) not followed by a punctuation character, or (2b) followed by a punctuation character and preceded by Unicode whitespace or a punctuation character. For purposes of this definition, the beginning and the end of the line count as Unicode whitespace. 

> A double __ can open strong emphasis iff it is part of a left-flanking delimiter run and either (a) not part of a right-flanking delimiter run or (b) part of a right-flanking delimiter run preceded by punctuation.

I also tested this on my local copy for Joplin and it works exactly as described in the spec.

With that said, I understand that it can be frustrating when behaviour of an application deviates from what you would expect. Joplin's plugin ecosystem is still young and actively being worked on, but I imagine eventually there will be plugins that allow you to customize the rendering to your satisfaction.

**Comment by overseeing** [comment]
Right, I forgot about underscore doing bold and italic! So long as one knows it's in spec, makes sense! Obviously as confusing as I could not emulate it if there was a space after the (double) underscore. I appreciate you conveying that info, maybe we both learned something, and will now close. :)
