### ISSUE TITLE
Tag list not updated in GUI after moving a note to another notebook

### ISSUE THREAD

**Issue by th-ros** [laurent22/joplin#4128]
When I move a note from one notebook to another notebook the the tag list on the bottom line of the GUI isn't updated.

## Environment

Joplin version: v1.4.12
Platform: Windows Portable
OS specifics: -

## Steps to reproduce

1. Create two notes in one notebook "NB_1"
    - note "note_1" with tag "tag_1"
    - note "note_2" with tag "tag_2"
2. Click on note "note_1" and in the tag list on the bottom of the GUI the tag "tag_1" is shown correctly. 
3. Move note "note_1" to another notebook "NB2" via drag & drop.
4. Now (the "first") note "note_2" in notebook "NB1" is shown with title, body and preview. But in the tag list there's still the "old" tag "tag_1" and not the note's "note_2" tag "tag_2".

**Comment by colorzzr** [comment]
Hi! I also reproduce this bug in the Linux version. if nobody is working on this bug, I will take this issue...

**Comment by colorzzr** [comment]
@laurent22 Hi Laurent! Just double-check can I take this issue?

**Comment by laurent22** [comment]
@colorzzr, yes of course, feel free to give it a try. If you need some help let me know.
