### ISSUE TITLE
Android start up screen improvements

### ISSUE THREAD

**Issue by despens** [laurent22/joplin#413]
### Operating system

- Android

### Application

- Mobile

The Android app's "Welcome" screen could be much improved by showing what is in the lefthand menu. 

At the moment the screen just contains a short welcome message and a + button. Instead, it could show notebooks, tags, the sync functionality AND the + button. This would make possible comfortable hierarchical navigation using the back button.

**Comment by laurent22** [comment]
Closed as duplicate of another issue.
