### ISSUE TITLE
Desktop: Bold and italics keybindings broken when spellchecking is enabled for markdown editor

### ISSUE THREAD

**Issue by CalebJohn** [laurent22/joplin#4130]
## Environment

Joplin version: v1.4.12
Platform: Linux
OS specifics: Ubuntu 20.04

## Steps to reproduce

1. Enable spellchecker for markdown editor
2. Try pressing ctrl+b or ctrl+i when the editor has focus, nothing happens

I've spent some time looking into this but have so far come up short, I'll spend more time debugging, but please let me know if you have an insight into what the cause might be. From testing it seems to be specific to the key bindings, for example I can change the bold command to ctrl+r and it works fine, but ctrl+b doesn't.

**Comment by antoniopaolini** [comment]
This happens also in Windows 10.
Also if the spell checker is deactivate (but enabled in options).
It should be disabled from the advanced options page.
