### ISSUE TITLE
Can not save picture by using firefox Joplin cliper

### ISSUE THREAD

**Issue by Drreeww** [laurent22/joplin#4131]
Joplin version:Joplin 1.3.18 (prod, linux)
PC: ubuntu 16.04
brower: firefox 
issue: can not save picture when use "firefox joplin cliper" -"clip simplified page/clip complete page/clip complete page(HTML)(beta)
![Screenshot from 2020-11-25 13-38-30](https://user-images.githubusercontent.com/38975592/100187680-94199f00-2f23-11eb-8758-ec8f8b38f041.png)

**Comment by laurent22** [comment]
What URL?

**Comment by Drreeww** [comment]
https://cloud.tencent.com/developer/ask/187636

**Comment by laurent22** [comment]
There's a complicated loading mechanism for images on this site. I can't even load them in a browser so it's unlikely it will work with the clipper.
