### ISSUE TITLE
Please PGP sign the AppImage or sha512 hash value

### ISSUE THREAD

**Issue by sanawu** [laurent22/joplin#4138]
Please PGP sign the AppImage or sha512 hash value

How can we verify the appimage and/or hash file is valid?

What is a valid hash anyway?

There is no point in giving a hash value if there is nothing signed to verify it against

Oh look, hash value, so what? what then? Twiddle our thumbs? We need a secure reference value, generally we PGP sign those or the appimage itself

**Comment by tessus** [comment]
This is nlot the place to suggest features. Read the template.

**Comment by sanawu** [comment]
> This is nlot the place to suggest features. Read the template.

FUCK OFF with your run around "oh sign up to another service". simply FUCK OFF and keep it

I will stop reporting bugs from now on

**Comment by tessus** [comment]
How delightful. Your parents must be so proud.

Please stay away, we don't want ignorant people to waste our time.

In case you learn how to read and open issues properly you are welcome to join us adults again. Until then have fun at the kiddie table.
