### ISSUE TITLE
Multi level nested itemisation is not working as expected

### ISSUE THREAD

**Issue by sanawu** [laurent22/joplin#4139]
Multi level nested itemisation is not working as expected

Joplin version
1.4.12

Repro steps

Start a numbered itemisation
1. item 1
Press TAB to indent
   item 2

Actual (github is messing up my levelling)
1. item 1
-> 1 item 1.1
->->     1 item 1.1.1

Expected
1. item 1
    a. item 1.a
       i. item 1.a.i

OR

1. item 1
   i. item 1.i

Could be configurable on the nesting itemisation behaviour

1
->   1
->->      1

Is not the appropriate way to indent itemise imo

You may want to see how it is done with LaTeX or other typesetting markups

I have to end up manually doing the itemisation which defeats the point of the function

**Comment by sanawu** [comment]
I suggest making this configurable and with the ability to change enumeration in the lists

**Comment by sanawu** [comment]
This may be of use https://www.latex-tutorial.com/tutorials/lists/

**Comment by CalebJohn** [comment]
AFAIK markdown does not have a concept of changing the symbol on sub lists. You can however manually type (a) or (i) whatever you want
1. something
    a. something

You can also use the following css

```css
li ol li ol li {
	list-style-type: lower-roman;
}
li ol li {
	list-style-type: lower-alpha;
}
```

to get the behavior you want in the render view
![image](https://user-images.githubusercontent.com/2179547/100392859-1aea7c80-2ff5-11eb-88b5-094b10ee6f47.png)

**Comment by sanawu** [comment]
> AFAIK markdown does not have a concept of changing the symbol on sub lists. You can however manually type (a) or (i) whatever you want
> 
> 1. something
>    a. something
> 
> You can also use the following css
> 
> ```css
> li ol li ol li {
> 	list-style-type: lower-roman;
> }
> li ol li {
> 	list-style-type: lower-alpha;
> }
> ```
> 
> to get the behavior you want in the render view
> ![image](https://user-images.githubusercontent.com/2179547/100392859-1aea7c80-2ff5-11eb-88b5-094b10ee6f47.png)

I can do it manually and override it in Markdown, I just want the tools for it to do it automatically in the Joplin editor

**Comment by tessus** [comment]
Right, this is a disussion for the forum. Also, as Caleb mentioned, markdown itself does not care about the format.
If you want to render it differently, use userstyle.css.

**Comment by sanawu** [comment]
I do not intend to sign up to yet another forum just to request features or report issues

I recommend you create a feature request category

**Comment by tessus** [comment]
> I do not intend to sign up to yet another forum just to request features or report issues

That's why you can use your gh credentials to log into the forum.

> I recommend you create a feature request category

No.

> I shall now STOP reporting ISSUES

You did not report a bug, but a usability issue. As stated in the template and in CONTRIBUTING, user questions go to the forum.
