### ISSUE TITLE
webdav sync problem with android and owncloud

### ISSUE THREAD

**Issue by jsl123** [laurent22/joplin#414]
### Operating system

- Android

### Application

- Mobile

Yes, I enabled the debug mode... ;-)

Desktop app (win10) working fine with sync to owncloud server via https.
Cert. is officially signed and trusted on Win10 and Android browsers.

On Android, app always fails with the same URL, Name and PW after approx. 20 secs.
Saying "Network request failed"
The logs in the OC instance show something like:
> Fatal webdav Exception: {"Message":"HTTP\/1.1 405 The resource you tried to create already
> exists","Exception":"Sabre\\DAV\\Exception\\MethodNotAllowed","Code":0,"Trace"

Trace omitted here.
The URL is something like this:
`https://www.servername.tld/owncloud/remote.php/webdav/home/me/private/Joplin`
Also tried with a leading "/" slash, but to no avail.
Also tried the same data as nextcloud entry data but also nothing. (This must be this way when nextcloud and webdav implementations are completely the same... :-)

OC is working with Win10/Webdav, Android browser and OC app on android. Also with the same webdav data...

Will attach a screenshot from the phone log too. That shows a (stack?) trace which says nothing to me.

The files on the Desktop and therefore on the OC are encrypted (e2ee). But I don't think that that's the problem? :-)

But either way: Thank you Laurent (et all) for this nice and very appreciated software! :-)

![screenshot_20180411-185743](https://user-images.githubusercontent.com/752061/38632227-5f5242e6-3dbc-11e8-9af8-249312c87248.png)

**Comment by laurent22** [comment]
The 405 "error" is normal, it's Nextcloud treating a no-op as an error. For the "Network request failed" error it sometimes means there's something unusual with the server, like non-default port, custom SSL certificate, etc. Is that the case with your server?
