### ISSUE TITLE
Latex Code Breaking after WebDav Sync (possibly with mobile)

### ISSUE THREAD

**Issue by digitalillusions** [laurent22/joplin#4140]
Yesterday I went through some of my older notes and noticed that all of them which contained `\n` for example in`\nabla` or `\r` in `\rho` were broken. The `\n` was replaced by a newline and `\r` was replaced by, I think, also a new line. 

I didn't think much of it, since I assumed it might have been an issue when updating the database to newer versions or something and that it would not occur again.

However, today a note that I started taking yesterday experienced the same issues. I think there was always a back and forth sync to Android involved before it happened, but I cannot be certain.

## Environment

Joplin version: 1.3.18 (Desktop), 1.3.13 (Android)
Platform: Linux, Android
OS specifics: Kubuntu 20.10, Android 10

## Steps to reproduce

These are the necessary steps for me

1. Make a new note with the content `$\rho \cdot \nabla$` and synchronise 
2. Synchronise on Android, the content of the note is now 
```
$ ho \cdot 
abla$
```
3. Wait for these changes to be synchronised back to the desktop client

## Describe what you expected to happen

I would expect the contents of latex blocks to be retained verbatim without substituting things like "\n" and "\r", because backslashes are kind of the backbone of the entire latex syntax.

**Comment by laurent22** [comment]
This was an issue with the desktop app, but it should be fixed now. Please give a try to v1.4
