### ISSUE TITLE
Joplin Diet Template

### ISSUE THREAD

**Issue by WinkoErades** [laurent22/joplin#4144]
I created a template I wanted to share, I am extremely sorry I can't find how to contribute templates.

[diet.md.zip](https://github.com/laurent22/joplin/files/5605187/diet.md.zip)

**Comment by laurent22** [comment]
Thanks for sharing, but best place would be in the forum, where users are already sharing themes, plugins, etc. I don't think we had much templates being shared and yours could be useful.

**Comment by WinkoErades** [comment]
Thank you for the idea, I will add it to the forum.

**Comment by tessus** [comment]
Awesom, thanks for sharing.
