### ISSUE TITLE
some note and Notebook lost,  there's a notebook called Conflicts

### ISSUE THREAD

**Issue by Drreeww** [laurent22/joplin#4147]
Joplin version:Joplin 1.3.18 (prod, linux)
PC: ubuntu 16.04
brower: firefox

I found one my note in Notebook A, and Notebook B lost, some notes in Notebook B were moved into Conflicts.
Is there a way to recovery them?

**Comment by CalebJohn** [comment]
Please ask questions like this on [the forum](https://discourse.joplinapp.org/). This isn't a bug.

Short answer, it looks like you edited notes on multiple devices at the same time which resulted in a conflict.

**Comment by tuchang** [comment]
I have the same issue. A whole notebook has gone. There is no Conflicts forder for this notebook. And another notebook moved into conflicts.
My joplinapp in other devices are not in use for days.
I use webdav to sync.
