### ISSUE TITLE
Version 1.4.12 Not working on MacOS BigSur

### ISSUE THREAD

**Issue by sahilchopra0003** [laurent22/joplin#4148]
When I updated from Version 1.3.18 to Version 1.4.12, Joplin stopped working. It doesn't even open properly, crashes right away.

## Environment

Joplin version: 1.4.12
Platform: macOS
OS specifics: BigSur 11.0.1

## Steps to reproduce

1. Open the App and it crashes right away.
2. 
3. 

## Describe what you expected to happen
The app should open properly.

<img width="623" alt="Screenshot 2020-11-27 at 2 23 49 PM" src="https://user-images.githubusercontent.com/11456136/100429994-310f4000-30bc-11eb-979f-d4177370ce28.png">

**Comment by laurent22** [comment]
Do you use plugins by any chance?

**Comment by laurent22** [comment]
Also just to be sure try the latest version 1.4.15

**Comment by sahilchopra0003** [comment]
> Do you use plugins by any chance?

No. I do not use any plugins.

**Comment by sahilchopra0003** [comment]
> Also just to be sure try the latest version 1.4.15

There was no update available for 1.4.15 at that time.

**Comment by sahilchopra0003** [comment]
> Also just to be sure try the latest version 1.4.15

It's working fine with version 1.4.19
