### ISSUE TITLE
Missing file after installing Joplin 1.4.12 over previous version

### ISSUE THREAD

**Issue by roadster31** [laurent22/joplin#4149]
Missing file after installing Joplin 1.4.12 over previous version

![image](https://user-images.githubusercontent.com/2197734/100440294-f6e67400-30a4-11eb-830a-d841483b6557.png)

## Environment

Joplin version: 1.4.12
Platform: Windows 10 Pro 64
OS specifics: 

## Steps to reproduce

1. Install Joplin 1.4.12
2. Run it
3. 

## Describe what you expected to happen

A normal startup :)

**Comment by laurent22** [comment]
What if you uninstall and re-install?

**Comment by roadster31** [comment]
After uninstalling, then re-installing, the problem is solved.

Thanks you @laurent22 :)
