### ISSUE TITLE
After update to 1.4.15, Fatal Error calling setSpellChckerLanguages

### ISSUE THREAD

**Issue by bladewolf55** [laurent22/joplin#4153]
**Note: The issue below is fixed in version[ 1.4.16](https://github.com/laurent22/joplin/releases/tag/v1.4.16)** 

## Environment

Joplin version: 1.4.15 pre-release
Platform: Windows 10 Pro
OS specifics: 

## Steps to reproduce

1. Error below after updating from previous pre-release.

![image](https://user-images.githubusercontent.com/2903411/100480921-e4256c80-30af-11eb-9528-bc9e5c3241ba.png)

**Comment by laurent22** [comment]
Please give a try to the latest version and let me know if there's still an issue https://github.com/laurent22/joplin/releases/tag/v1.4.18

**Comment by bladewolf55** [comment]
Fix in 1.4.16 and still working in 1.4.18. Thank you!
