### ISSUE TITLE
Joplin Portable v1.4.16 strange start behaviour

### ISSUE THREAD

**Issue by graphixillusion** [laurent22/joplin#4154]
Hi there. I'm just using the last 1.4.16 portable version under Windows and i noticed this strange behaviour: when you start the exe, the process starts but without GUI. In the system's temp folder it creates a tmp folder named with a random string (like 1ksvDmTTQ25l3KbZiazQpmNO06z) and it will starts to populate with files inside. The folder will become about 470MB with 28260 files inside. Only when this process is ended, the GUI will shows up. I think that something went wrong with some flags during the last build.

**Comment by laurent22** [comment]
I've disabled asar packing to fix notifications on macOS, but looks like it means it's unpacking the whole app every time it starts now. I'll re-enable it and try to find a better fix.

**Comment by ina6ra** [comment]
I also had this problem so I reverted to [v1.4.12](https://github.com/laurent22/joplin/releases/tag/v1.4.12).
It has not been improved even in v1.4.16.

**Comment by alexdevero** [comment]
On Windows 10 Joplin v1.4.16 will not show. The process is started and get ~95 MB of memory. However, the app window never appears.

**Comment by laurent22** [comment]
Could you try the latest version to see if it solves the issue? https://github.com/laurent22/joplin/releases/tag/v1.4.18

**Comment by graphixillusion** [comment]
@laurent22 Yes with .18 everything back to normal: fast startup, temp dir size is still 440MB but only 150 files in it.

**Comment by alexdevero** [comment]
With 1.4.18 Joplin starts quickly and without any error.

**Comment by laurent22** [comment]
Brilliant, thanks for confirming.

**Comment by luckycalf** [comment]
I'm using the portable version ,still having this  problem, even with the latest version 1.6.7. Most of the time it doesn't show the window, sometimes it shows the blank window with only menu bar,and you can not close it, only to kill the process.
OS: windows 7 pro sp1 32bit
