### ISSUE TITLE
Error PROPFIND locks after format my computer

### ISSUE THREAD

**Issue by general03** [laurent22/joplin#4157]
After reformatted my computer I can't get my notes, I get error 
My notes are store on Notes folder in nextcloud instance

## Environment

Joplin version: 1.4.18
Platform: Linux Ubuntu 20.10
Nextcloud 20.0.2

## Steps to reproduce

1. I put this config in my joplin app
url : https://mynextcloud.tld/remote.php/webdav/Notes
I got this => Success! Synchronization configuration appears to be correct.
2. When I click on Synchronize button I get the error see below

## Describe what you expected to happen

I can't get all my notes, nothing in the joplin app

## Logfile

```
Last error: Error: PROPFIND locks/: File with name Notes/locks could not be located (Exception Sabre\DAV\Exception\NotFound) (404): <?xml version="1.0" encoding="utf-8"?> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"> <s:exception>Sabre\DAV\Exception\NotFound</s:exception> <s:message>File with name Notes/locks could not be located</s:message> </d:error>
```

**Comment by laurent22** [comment]
What's in the Notes folder? Is there a "locks" folder?

**Comment by general03** [comment]
Notes folder is my folder in root folder where there are the notes

And there are not file or folder inside

**Comment by HiperFall** [comment]
I have the same issue on MacOS 10.15.

**Comment by general03** [comment]
@laurent22 the locks file id generated by JOPLIN ?

I unlock the files in nextcloud, no change

**Comment by general03** [comment]
On my mobile I can't sync my folder too, but on this device I change nothing,

@laurent22 can you help me to understand what happened ?

**Comment by general03** [comment]
On my mobile I can't sync my folder too, but on this device I changed nothing,

@laurent22 can you help me to understand what happened ?

**Comment by alipsky** [comment]
same issue here. latest joplin/nextcloud.   Had working nextcloud/joplin setup on multiple computers. Got a new m1mac mini, installed Joplin the way I normally do.

Completed: 16/12/2020 09:57
Last error: Error: PROPFIND locks/: File with name Joplin/locks could not be located (Exception Sabre\DAV\Exception\NotFound) (404): <?xml version="1.0" encoding="utf-8"?> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"> <s:exception>Sabre\DAV\Exception\NotFound</s:exception> <s:message>File with name Joplin/locks could not be located</s:message> </d:error>

**Comment by kstka** [comment]
Same here, NextCloud + Joplin. Fixed by manually creating folder "locks" in the root of my Joplin data directory

**Comment by general03** [comment]
> Same here, NextCloud + Joplin. Fixed by manually creating folder "locks" in the root of my Joplin data directory

FIX ISSUE => I also create "locks" folder and resync after install joplin again

**Comment by The-Inamati** [comment]
I have the same issue. Created the locks folder and it does sync with success but no notes are downloaded. Any ideas?
