### ISSUE TITLE
v1.4.18: Program start lasts several minutes

### ISSUE THREAD

**Issue by Hoffenbar** [laurent22/joplin#4158]
I'm using the **latest portable version on windows**. With this release, it takes several minutes (10 or so) before the program window appears on the screen. I Cannot attach any log etc. as I don't know where the relevant ones are stored. I see a `@joplin` folder under `%appdata%/roaming` with some logs within, and an older `joplin`  folder.

**Comment by laurent22** [comment]
Is that definitely 1.4.18? Because the bug should be fixed on that version

**Comment by Hoffenbar** [comment]
Just looked in the .exe: 1.4.16. I thought it was 1.4.18, because I've downloaded this earlier this day...  Now I downloaded again, and that's now 1.4.18, and yes: startup only lasts a few seconds. Thanks, and sorry I was wrong. Maybe some caching problem on github or a mistake of me. I have to review the other two tickets I opened, too!
Many thanks.

**Comment by laurent22** [comment]
No worries, glad it's working now.
