### ISSUE TITLE
v1.4.18: HTML export yields no html file

### ISSUE THREAD

**Issue by Hoffenbar** [laurent22/joplin#4160]
Latest portabel version on windows.
Trying to export the attaches jex yields no html file;  only some resource files are produced.
[startwrap.zip](https://github.com/laurent22/joplin/files/5611182/startwrap.zip)

**Comment by Hoffenbar** [comment]
Please close this issue; I think I tested with 1.4.16 by mistake. Sorry. With 1.4.18, this works now.

**Comment by laurent22** [comment]
Thanks for confirming it works now.
