### ISSUE TITLE
Export to JEX file turns '\right(' to <cr>ight(

### ISSUE THREAD

**Issue by AndreasMartin72** [laurent22/joplin#4163]
I exported a note to a JEX file. In the note there are formulas using latex '\right(' syntax.
After importing this file, all '\r' parts are converted to carriage returns and only 'ight(' remains.

Example:
$$ f(x) = \left( x^2 \right) $$

After import:
$$ f(x) = \left[ x^2 
ight] $$

## Environment

Joplin version: Joplin 1.4.18 (prod, linux)
Client-ID: 2d591b8fc4dd437697aa021c149ea8ae
Sync-Version: 2
Profil-Version: 34
Unterstützter Schlüsselbund: Nein
Revision: 76c4d99 (master)
Platform: Linux, Ubuntu
OS specifics:

**Comment by laurent22** [comment]
There was unfortunately a problem with exporting notes in the earlier version. That should be fixed now so if you re-export and re-import the notes it should work.

**Comment by AndreasMartin72** [comment]
This is strange, I had used the newest version (1.4.18). Same version (and same old JEX file!) today succeeds...

Regards, Andreas
