### ISSUE TITLE
All a notebook disappear in Notebooks

### ISSUE THREAD

**Issue by tuchang** [laurent22/joplin#4165]
All notes in a notebook disappear in Notebook but they are still in All Notes.
And they are unsearchable now.

## Environment
Joplin 1.4.18 (prod, win32)

Client ID: 1f5ad3d6b5d24b4aafe12e0d725524e0
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: 76c4d99b8 (master)

Platform:  Windows 10 + Ubuntu20.04

## Steps to reproduce
it happened 2 times, maybe when syncing in the background

## Describe what you expected to happen
Notes keep staying in the Notebooks

**Comment by Drreeww** [comment]
today, I open Joplin on my ubuntu PC, found one folder were disappeared, some notes were moved  to Conflicts. I do not open Joplin on my phone. Is there a way to avoid this.

**Comment by tuchang** [comment]
> today, I open Joplin on my ubuntu PC, found one folder were disappeared, some notes were moved to Conflicts. I do not open Joplin on my phone. Is there a way to avoid this.

It happened many times recently on my ubuntu PC too. I consider exporting all my notes and editing them using a local markdown editor for a period.
