### ISSUE TITLE
Joplin for linux creates endless copies of note

### ISSUE THREAD

**Issue by MD4HASH** [laurent22/joplin#4167]
Using Joplin appimage 1.4.1.8 on Kali Linux.  When the sync process kicks off it starts creating endless duplicates of a note that I recently created (not even the note that I created most recently).   It creates these copies in whatever notebook I happen to have open, not where it actually belongs.  This is not a problem in my mac/windows clients.

## Environment

Joplin version: appimage 1.4.18
Platform: Ubuntu
OS specifics: Kali Linux

## Steps to reproduce

1. open appimage and wait for sync to kick off

## Logfile
I enabled logging in the cli as described in the instructions, but I was unable to find `log.txt` in ~/.config/Joplin

## Screenshot
![joplin](https://user-images.githubusercontent.com/55195229/100614150-ac066f80-32e3-11eb-95cb-df845909c48d.png)

**Comment by MD4HASH** [comment]
![image](https://user-images.githubusercontent.com/55195229/100749225-62388a80-33b2-11eb-813d-0a5b5ae79279.png)
This is now happening in the windows client as well

**Comment by MD4HASH** [comment]
Is there anything I can do to fix this?  It is now affecting all but one of my clients, and I would really like to get back to using Joplin again.  Thanks.

**Comment by byronkg** [comment]
What version of Kali Linux are you using? And what method(s) of syncing?

Also log.txt should be found under the following:
/<username>/.config/joplin-desktop/log.txt

**Comment by MD4HASH** [comment]
Thank you.

I'm using dropbox to sync

Description:    Kali GNU/Linux Rolling
Release:        2020.3
Codename:       kali-rolling

[log.txt](https://github.com/laurent22/joplin/files/5629536/log.txt)

**Comment by MD4HASH** [comment]
I now have thousands of copies of this note on every one of my clients.   Is there anything I can do to fix this?  Joplin is completely unusable for me at this point.

**Comment by byronkg** [comment]
I'd say try with another version. Can't seem to figure out why. My guess is that the syncing keeps trying to happen and it does not update the revision instead of incrementing.
