### ISSUE TITLE
codemirror_content_script example plugin not working (MacOS, v1.4.18)

### ISSUE THREAD

**Issue by jannes** [laurent22/joplin#4170]
## Environment

Joplin version: 1.4.18
Platform: macOS
OS specifics: macOS 10.14.6

## Steps to reproduce

1. Add https://github.com/laurent22/joplin/tree/dev/packages/app-cli/tests/support/plugins/codemirror_content_script to plugins directory
2. `npm install && npm run dist`
3. enable debugging mode with flags.txt
4. Restart Joplin

## Describe what you expected to happen

The console should log "Something" when pressing 'ctrl-U'.
I changed the shortcut to multiple other values, such as 'cmd-5' and they all didn't work.

I also added a call to console.log in the beginning of the 'plugin' function that is registered,
and I could not see the output in the console.

The plugin is loaded though, I can see that in the console.
```
joplin.plugins: Finished running onStart handler: org.joplinapp.plugins.MatchHighlighter (Took 2968ms)
```

**Comment by CalebJohn** [comment]
Plugins each get their own console for debugging purposes. These console windows should pop up when the application loads. Is it possible that the console is just hidden behind another window and you're missing it?

**Comment by jannes** [comment]
Ah good to know,
I indeed missed the extra console, I can now see the log output I added in the 'plugin' function.
However, I still can't get the 'printSomething' command to trigger, neither with 'Ctrl-U', nor with another
command I tried ('Cmd-5').

**Comment by CalebJohn** [comment]
@jannes Thanks for pointing that out. I took look at that plugin to see if I could see the issue. The example script only sets a keybinding for windows and linux desktops! You will need to changes this line

```javascript
CodeMirror.keyMap.basic["Ctrl-U"] = "printSomething"
```
to
```javascript
CodeMirror.keyMap.default["Ctrl-U"] = "printSomething"
```

If you want the keybinding to work.

Just a warning, the CodeMirror keybinding system will change after #4136 is merged and doing the above (and what is demonstrated in the example) will no longer work, so be ready for this to stop working again soon :).

**Comment by jannes** [comment]
Ah okay, my bad, I could have checked the CodeMirror docs for that.
Yea I was just trying to get this example to work to get familiar with how the Plugin system work:)
