### ISSUE TITLE
releases after 1.4.12 are missing latest-mac.yml

### ISSUE THREAD

**Issue by luckman212** [laurent22/joplin#4171]
Joplin [1.4.12](https://github.com/laurent22/joplin/releases/tag/v1.4.15) was the last release to include the `latest-mac.yml` asset descriptor file.

Newer releases (including today's [1.4.19](https://github.com/laurent22/joplin/releases/tag/v1.4.19)) only contain `latest.yml` (Windows) and `latest-linux.yml`, even though the Mac `Joplin-1.4.19.dmg` file seems to have built fine.

This has broken my auto-updater script, so it would be really nice if it was brought back!

**Comment by laurent22** [comment]
Yes these files aren't supposed to be there, but you could use latest.yml instead as it should tell you the version number.

**Comment by luckman212** [comment]
`latest.yml` does not contain the asset URLs (dmg) nor the hashes though...

**Comment by laurent22** [comment]
The dmg url can be easily constructed as it's the same in each release, with only the version number changing. Why would you need the hash for?

**Comment by luckman212** [comment]
The hash could be useful for 2 reasons:

- Ensuring the download was successful / not corrupt (true, not really needed since DMG format has its own checksum verification I think)
- Ensuring nobody has tampered with the packages

I agree these are not very strong arguments, but they could be mildly useful. And, they were there before, which is really the main reason I asked.
