### ISSUE TITLE
网页剪辑花屏，并且在使用mermaid时花屏

### ISSUE THREAD

**Issue by feizoule** [laurent22/joplin#4174]
进行网页剪辑设置时会花屏，并且在使用mermaid时使用loop笔记也会花屏

```mermaid
sequenceDiagram
H5->>服务器: 发送请求（包括url,has_cookie）
    loop 含有has_cookie,且true
        服务器->>服务器:，存储cookie,生成cookie_head
    end
服务器->>远程服务器:获取页面内容
远程服务器-->>服务器:返回页面数据，包含cookie
服务器->>服务器:使用cookie_head存储cookie
服务器-->>H5:返回页面内容
H5->>服务器: 发送请求（包括url）
```

![image](https://user-images.githubusercontent.com/4022711/100845571-6949c080-34b8-11eb-8135-4006d3b33a11.png)
![image](https://user-images.githubusercontent.com/4022711/100845595-71096500-34b8-11eb-9abe-b210f75090e6.png)

**Comment by laurent22** [comment]
Looks like you found the Matrix in Joplin. And also for me it doesn't happen, although I don't have the Chinese font installed in WSL.

![image](https://user-images.githubusercontent.com/1285584/100856803-cb3c0300-3483-11eb-915c-688b1df45447.png)

**Comment by feizoule** [comment]
谢谢回复，升级到最新版本之后，问题消失了
