### ISSUE TITLE
Sync conflict

### ISSUE THREAD

**Issue by Kevin-CodeHub** [laurent22/joplin#4177]
My clients are PC, Mac OS and Android,
The sync of notes is realized by WebDAV;
However, when I edit notes or synchronize on the mobile phone, there will always be errors, synchronization conflicts and conflicting notes;
I wonder if we can set whether we can manually select single synchronization or bidirectional synchronization;
For example, on Android, I mainly look up and edit very little. Can I choose to synchronize only WebDAV data instead of syncing new content on Android;

**Comment by JackGruber** [comment]
No Only two-way synchronization can be set up.

>here will always be errors, synchronization conflicts and conflicting
Are both systems ready with the inital sync? meaning they have all the data?
`Help->Syncronisation Status` on the Desktop App, `Configuration->SYNC STATUS` on the Mobile App. 

When you open a new issue for a bug, it will also tell you what is needed. Without this information nobody can help.

**Comment by tribbloid** [comment]
Thanks a lot! Also affects me, and conflict cannot be resolved
