### ISSUE TITLE
Joplin-desktop windows becomes white and unresponsive, throws "Out of memory" error.

### ISSUE THREAD

**Issue by gfrein** [laurent22/joplin#4179]
## Environment

Joplin version: 1.4.19 (AppImage)
Platform: Linux
OS specifics: openSUSE Tumbleweed with GNOME desktop

## Steps to reproduce

1. Edit any note.
2. Seemingly at random, the entire application window except for the menu bar becomes completely white and unresponsive (can only be killed by killing the process using e.g. xkill or kill). Sometimes this happens a few minutes after starting to edit the note, sometimes it takes a little longer before it crashes.

The "white window" symptom is similar to #3635, but it in this case it happens after Joplin has already be launched while editing a note, so it's probably unrelated. My notes are rather large (+300 lines) and contain a lot of KaTeX equations, so having to render a lot of equations might have to do with it. The crash does not necessarily happen while editing an equation though.

This started a couple of days ago. Since I update Joplin regularly, this means probably around 1.4.15 or later.

## Describe what you expected to happen

It shouldn't crash, obviously.

## Logfile

When running it from a console, Joplin prints out the following error message after the crash:

```
<--- Last few GCs --->

[12021:0xbdc00000000]   690893 ms: Mark-sweep (reduce) 185.8 (215.4) -> 185.6 (214.9) MB, 39.6 / 0.0 ms  (average mu = 0.944, current mu = 0.002) last resort GC in old space requested
[12021:0xbdc00000000]   690930 ms: Mark-sweep (reduce) 185.6 (199.9) -> 185.3 (202.7) MB, 37.1 / 0.0 ms  (average mu = 0.894, current mu = 0.001) last resort GC in old space requested


<--- JS stacktrace --->

[12021:1203/142639.546491:FATAL:memory.cc(40)] Out of memory. size=0
```

**Comment by laurent22** [comment]
Any message in the console or log? https://joplinapp.org/debugging

**Comment by gfrein** [comment]
There's only a `KaTeX parse error` (I forgot a "s" in "\Reals" in one equation) that gets repeated every time it re-parses the KaTeX equations for the preview window and also a bunch of warnings related to DevTools (`DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_Joplin...`).

In log.txt, the last two entries before the last crash are `"Saving note... "`, followed by `"Scheduling sync operation...", "30000"` (I'm syncing with Nextcloud). The "Saving note..." entry contains what looks like JSON data related to the note, including `"body":` followed by the entire content of the +300 lines note I was working on, which seems weird to have in the log. The oldest of those huge "Saving note ..." entries I could find is only from yesterday though, and the crashes started happening before that.

**Comment by gfrein** [comment]
Update: I started a new, shorter note and included a bit of text with the same KaTeX error. It still crashed, so it's not about the size/length of the note. This time, the last log.txt entries before the crash were different, so apparently it's not related to saving or syncing either:

```
2020-12-05 13:26:29: "Saving settings..."
2020-12-05 13:26:29: "Settings have been saved."
2020-12-05 13:26:29: "SearchEngine: Updated FTS table in 90ms. Inserted: 1. Deleted: 0"
```

After that crash, I removed the erroneous bit of KaTeX code and it hasn't crashed since - but that might be coincidence since the crashes seem to happen in random intervals. I'll keep monitoring it.

**Comment by laurent22** [comment]
What's the katex code?

**Comment by gfrein** [comment]
The KaTeX parse error in the console was about this tiny bit: `$\rho \in \Real$` (the `s` in `\Reals` was missing). 

If it's related to KaTeX, the seemingly random intervals between the crashes might be related to how much I type: when I enter a lot of new text (it"s mainly math lecture notes) in a short amount of time, the KaTeX re-parsing in the preview window is triggered more frequently and might lead to a quicker crash. But that's just speculation - I tried to trigger a crash by entering a lot of random text (while the KaTeX error was still there), but no "luck" so far.

**Comment by gfrein** [comment]
I haven't had a single crash since I corrected the KaTeX error.

So it seems like the repeated attempts to re-parse the erroneous KaTeX code make Joplin crash after a while (depending on how often KaTeX re-parsing gets triggered by entering more text). Unfortunately, I don't know any JavaScript, so I don't know how to verify or investigate this further.

**Comment by laurent22** [comment]
Ok good to hear, it's working now. If it happens again and you can narrow it down to some particular Katex code, feel free to open a new issue with the problematic Katex code.
