### ISSUE TITLE
Question: is there a place for asking questions?

### ISSUE THREAD

**Issue by zblesk** [laurent22/joplin#418]
Hello, 

is there any place where I can ask questions regarding Joplin development? 
I'm new to this stack and could use some pointers, but even though I've been crawling up and down the repo and website for the last few days, I haven't found any. Is there some forum, or discord, or whatever? 

Thanks a lot!
(Also, sorry for opening this as an issue. Though it could be considered an issue with the docs, I guess. 😇 )

**Comment by foxmask** [comment]
At the beginning, when I installed the project some times ago, I had the same question, but I think Laurent is all alone to dev. So patience is the master world, for him and the project :)

**Comment by zblesk** [comment]
Well, hopefully he swings by anyway. :D

**Comment by foxmask** [comment]
I think you'll see the wolf soon :)

**Comment by alwashe** [comment]
You just asked a question. 😊

**Comment by tessus** [comment]
A place for asking questions (not only about development) would be great.

As a matter of fact I have about 20 of them (dev and non-dev), but what is the legitimate way to ask them? 

- Send Laurent an email?
- Open one ticket for all questions?
- Open one ticket per question?

**Comment by zblesk** [comment]
Opening an "issue" because I have a question feels wrong to me. I would have gone with the e-mail, but I couldn't find any. :D

**Comment by alwashe** [comment]
Google Play Store -> Joplin - > Ende of Page -> Send Mail

Why not here?

**Comment by laurent22** [comment]
I've been meaning to open some place for user support because it's true GitHub is not the best for this. The issue tracker is mostly for bug and feature reports.

Any suggestion on what would a good platform for user support? Is Discord any good? Ideally it should be something reasonably open (so not Slack) and easy to use.

**Comment by foxmask** [comment]
there is https://www.discourse.org/ used by [vuejs](https://forum.vuejs.org/) and [apistar](https://discuss.apistar.org/) for example.
you can have a look at the [demo](https://try.discourse.org/)

**Comment by tessus** [comment]
Discourse seems like a good choice. Previously a lot of people used phpBB as a forum platform, but lately most of new forum installs are Discourse.
The recommended way is to do the install via Docker, which takes less than 20 minutes. You don't want to manually install all the requirements a Ruby on Rails app actually needs. ;-)

**Comment by laurent22** [comment]
Thanks, I see the project might be eligible for free hosted Discourse so I'm going to try to apply for it.

**Comment by zblesk** [comment]
Good luck with the Discourse application. Joplin doesn't quite meet the requirements, but they seem to be flexible in this. 
Discord is also good, but more similar to Slack than to a standard forum. (So great for things like brainstorming or support, less so for any 'knowledge-base'-like articles.)

**Comment by laurent22** [comment]
Yes maybe both a Dicord (for chat) and Discourse (for more permanent stuff) would be good. The project indeed is a bit short in terms of contributors, but let's see if they allow it anyway.

**Comment by zblesk** [comment]
Sounds great. 

In the meantime, until they're up, one of the questions I wanted to ask initially 😇 : 

I'd like to hack on Joplin a bit, but I have never used this stack. I'd managed to build the windows app, but I have no idea what my workflow should be, or whether there are any specific tools that the community recommends. 
I figure I _could_ just try modifying files and then doing a `yarn dist`, but since that seems to take a long time, I hope there is some other way? 

Second question: when I ran the instance that I built from source, it has shown all my notes. I'd like to have a separate set of notes for the version I'm currently hacking on. Is this possible?


Thanks!

**Comment by sbstn87** [comment]
Maybe matrix.org\Riot.im could be a better option than Discord? It is open source and federated, whereas Discord is proprietary software that collects all user data.

**Comment by tessus** [comment]
IMO a forum or discussion board is more useful than a chat system. Maybe I'm biased because I truly dislike IRC, but a forum gives you a chance to pin threads, add guides and FAQs in special read-only folders. With a forum it's easier for people to find a solution.

I'm not saying that a chat system shouldn't be considered but the main focus should be on a forum.

**Comment by foxmask** [comment]
Things like https://gitter.im allow us to exchange easily and follow the changes on issues etc,  and for FAQ and other guides, there could be the place of https://github.com/laurent22/joplin/wiki

**Comment by laurent22** [comment]
The forum is now created and available at https://discourse.joplin.cozic.net (Discourse has eventually accepted free hosting for the project). I will link to it from the Readme and other places, it will be the official place for development-related questions and discussions and for user support.

**Comment by tessus** [comment]
What about ideas for feature requests and their discussions (e.g. if they make sense, how feasible they are, ...). Can we add them there too? Or shall feature requests be posted to github?

**Comment by tessus** [comment]
Oh, btw, any chance you can activate signup or login with a github account?

**Comment by tessus** [comment]
@laurent22 awesome, thanks

**Comment by laurent22** [comment]
GitHub login is now enabled on the forum.
