### ISSUE TITLE
Latest update turned writing area dark in dark mode

### ISSUE THREAD

**Issue by armaccloud** [laurent22/joplin#4180]
I was using the dark theme in Joplin, where the menu's, etc would be dark but the writing pane was white.
Since the latest update (1.4) now also the writing pane has become black. Reading and writing white letters on a black background is not pleasant for my eyes. How can I keep the dark theme, but only have the writing pane (wysiwyg) in white?

**Comment by laurent22** [comment]
I can't replicate this. I use the rich text editor in dark mode and text is white.

**Comment by CalebJohn** [comment]
It sounds like maybe you were using the light theme before? In the light theme the sidebar is dark, and the rest is light. In dark mode the editor background has always been dark.

![image](https://user-images.githubusercontent.com/2179547/101072653-9602e400-355b-11eb-8d0b-694214e844e2.png)

![image](https://user-images.githubusercontent.com/2179547/101072684-a0bd7900-355b-11eb-976b-62c47066fc44.png)

**Comment by laurent22** [comment]
Right, for some reason I read that you had black text over black background. Indeed it's normal that the writing area has a dark background too in dark mode. I don't think it was ever different or else it was a bug.

**Comment by armaccloud** [comment]
Oh my, didn't expect it to be so simple :)
Apparently with installing the new version, it defaulted to dark mode since I didn't go into the settings.
Changing to light got me the old version back. Should have tried that before.
Thanks @CalebJohn & @laurent22 !
