### ISSUE TITLE
Cannot login to OneDrive on mobile app

### ISSUE THREAD

**Issue by L0WNUT** [laurent22/joplin#4182]
Hello,

I am new to Joplin. I have tried to install the Windows version (which didn't work) but managed to get the portable one and sync it to OneDrive and also encrypt the files.

Trying to do the same on the mobile app, however i cannot sync to OneDrive as I can't login (all i can do is refresh or go back)

![joplin](https://user-images.githubusercontent.com/59209356/101139922-27c92a80-360a-11eb-9693-93d7a64d2787.jpeg)

Joplin version: 1.4.11
Platform: Android
OS specifics: 10

Thank you!

**Comment by xuchuang199636** [comment]
中国区的话，手机端科学上网之后就能同步了

**Comment by xuchuang199636** [comment]
If you are in China, you can login and synchronize the data to OneDrive  after scientific Internet access（科学上网）.
