### ISSUE TITLE
Joplin supports Katex (not Latex) and there's no plan to support Latex or Latex extensions.

### ISSUE THREAD

**Issue by Mauricinho** [laurent22/joplin#4183]
Joplin supports Katex (not Latex) and there's no plan to support Latex or Latex extensions.

_Originally posted by @laurent22 in https://github.com/laurent22/joplin/issues/2433#issuecomment-581327606_

**Comment by Mauricinho** [comment]
Just for my understanding, as I was searching for some kind of reference/bibliographic support in Joplin:

As far as I understand BibTex is not an 'extension' of LaTeX (can be used as the standard in a bibliographic extension of LatTeX) but a bibliographic standard based on Donald Knuth's typesetting standard for TeX that is applied in all kinds of context. Situation is similar to the use of KaTeX for math typesetting in Joplin (which is nice).

So supporting BibTex would be the natural way to extend bibliographic support in Joplin and would probably substantially accelerate and strengthen (at least my) research workflow.

**Comment by Mauricinho** [comment]
Just saw that htere is a more extensive discussion in the forum, so I'll move there :-)

**Comment by laurent22** [comment]
Yes and there's also a feature request about it with a plan to create a plugin for it.
