### ISSUE TITLE
The character "\n" in MacVim cannot synth back to Joplin

### ISSUE THREAD

**Issue by brucejuz** [laurent22/joplin#4184]
## Environment
Joplin 1.3.18 (prod, darwin)
Platform:  macOS 
OS specifics: Catalina 10.15.7

MacVim: Custom Version 8.2.1719 (166)

## Steps to reproduce

1. Open Joplin
2. Then open " External Editing" , Then I using MacVim as my text editor.
3. Any character strings include "\n" "\neq" or "\ne..." in MacVim editor will not save into Joplin editor.  "\n" will become a new line in Joplin.
For example: 
In MacVim:
$\neq$

When you save, In Joplin editor, it will change to
$
eq$

**Comment by laurent22** [comment]
That should be fixed in v1.4.
