### ISSUE TITLE
Minor issue with tray icon

### ISSUE THREAD

**Issue by cshrimpt** [laurent22/joplin#4190]
On KDE 5.20.4 and Joplin 1.2.6 I was able to simply click the tray icon (when the app was minimized to tray) and the app would open. Now on 1.4.19 when I click the tray icon, it opens the the "Open Joplin/Quit" dialog requiring two clicks to open the app. Previously that dialog only opened with a right click.

Again, very minor detail.

Thanks.

**Comment by ben2talk** [comment]
Yes, I believe that the 'quit' should be a right click option, and a simple click should pop up Joplin.

**Comment by zorkerz** [comment]
This has not been fixed (assuming its going to be and is not intentional functionality). It sure would be nice to cut the clicks to open Joplin from the tray icon in half.
