### ISSUE TITLE
Right-click menu on the right half of a note in note list would blink and disappear

### ISSUE THREAD

**Issue by jimewu** [laurent22/joplin#4201]
## Environment

Joplin version: 1.4.12, 1.4.15, 1.4.16, 1.4.18, 1.4.19
Platform: Linux
OS specifics: Manjaro Linux

## Steps to reproduce

1. Right-click on the right half of a note in note list
2. The right-click menu would appear and disappear instantly
3. If right-clicked on the left ~20% of a note in note list, the menu thus appeared would be normal
4. The latest version that I have tested without this issue  is 1.3.18

## Logfile

No log entry was generated

**Comment by roman-r-m** [comment]
Same for me on Windows 8. Only that for me it's right ~20% where right click is **not working**

**Comment by laurent22** [comment]
I can't replicate this. Does it happen every time for you?

**Comment by roman-r-m** [comment]
Yes, except for the 1st note in a notebook.
Here's my version btw (also it's portable)
```
Joplin 1.4.18 (prod, win32)

Client ID: 8129c25cca08408db9608fbf677fee34
Sync Version: 2
Profile Version: 34
Keychain Supported: No

Revision: 76c4d99b8 (master)
```

**Comment by jimewu** [comment]
> I can't replicate this. Does it happen every time for you?

- This issue only appears on 1 of my 2 laptops, both of them run Manjaro linux + Plasmashell + Joplin.AppImage
- The one that has this issue is a Thinkpad X1 Carbon 4th gen, and the one without this issue is a Thinkpad + AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx

**Comment by laurent22** [comment]
Could someone post a video to show how it looks exactly? I can't replicate neither on Windows nor WSL (equivalent to Linux).

**Comment by roman-r-m** [comment]
Strangely, I can't reproduce it when running directly from source code either, though it's a different commit compared to what my portable version is built off. I'll try again with the same exact commit later.

**Comment by jimewu** [comment]
> Strangely, I can't reproduce it when running directly from source code either, though it's a different commit compared to what my portable version is built off. I'll try again with the same exact commit later.

Sure, please watch [this youtube video](https://youtu.be/3R_ItPz8rI8).

**Comment by laurent22** [comment]
Thanks @jimewu. Indeed that's strange and for now I'm not sure what can be causing this, especially since it doesn't happen for me.

**Comment by swiesmann** [comment]
There's a catch. I was able to reproduce it on Manjaro Linux Gnome using Joplin-1.4.19.AppImage. But ONLY when I have  ZOOMED IN. So when I hit CTRL + PLUS once or twice I can reproduce it reliably - when I reset the zoom by using CTRL + 0 (zero) the issue is gone.

**Comment by jimewu** [comment]
> There's a catch. I was able to reproduce it on Manjaro Linux Gnome using Joplin-1.4.19.AppImage. But ONLY when I have ZOOMED IN. So when I hit CTRL + PLUS once or twice I can reproduce it reliably - when I reset the zoom by using CTRL + 0 (zero) the issue is gone.

Exactly! I did use Joplin zoomed in always, and maybe that is why this issue appear.
