### ISSUE TITLE
Building for over 10 minutes, then aborting

### ISSUE THREAD

**Issue by maeckha** [laurent22/joplin#4204]
Please provide a clear and concise description of what the bug is. (In the section Steps To Reproduce.)
  Include screenshots if needed.
  Please test using the latest Joplin release to make sure your issue has not already been fixed.

==> Creating package "joplin"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Starting package_joplin-desktop-electron()...
  -> Building Desktop with packaged Electron...

> @joplin/app-desktop@1.4.19 dist /var/tmp/pamac-build-meck/joplin/src/joplin-1.4.19/packages/app-desktop
> electron-builder "--publish=never" "--linux" "tar.xz" "--x64" "--dir" "-c.electronDist=/usr/lib/electron" "-c.electronVersion=10.1.5"

  • electron-builder  version=22.9.1 os=5.4.80-2-MANJARO
  • loaded configuration  file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=linux arch=x64 electron=10.1.5 appOutDir=dist/linux-unpacked
  • copying Electron  source=/usr/lib/electron destination=/var/tmp/pamac-build-meck/joplin/src/joplin-1.4.19/packages/app-desktop/dist/linux-unpacked
  • building        target=tar.xz arch=x64 file=dist/@joplin/app-desktop-1.4.19.tar.xz
  ⨯ [object Object]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @joplin/app-desktop@1.4.19 dist: `electron-builder "--publish=never" "--linux" "tar.xz" "--x64" "--dir" "-c.electronDist=/usr/lib/electron" "-c.electronVersion=10.1.5"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @joplin/app-desktop@1.4.19 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/meck/.npm/_logs/2020-12-08T16_37_20_043Z-debug.log
==> ERROR: A failure occurred in package_joplin-desktop-electron().
    Aborting...

## Environment

Joplin version: 1.4.19-2
Platform: Linux 5.4.80-2
OS specifics: Manjaro x86_64

## Steps to reproduce

1. Installing AUR - Package
2. 
3.

**Comment by ericschdt** [comment]
1) AUR is not supported
2) See https://github.com/alfredopalhares/arch-pkgbuilds/issues/63

**Comment by alfredopalhares** [comment]
Just for closure, this was while I was packaging to the lerna format.
