### ISSUE TITLE
Dekstop, Linux, search results are not cleared after clicking x

### ISSUE THREAD

**Issue by PaperTsar** [laurent22/joplin#4208]
Using the search bar at the top on the Desktop application and then clicking the x that appears (to cancel the serach) does not clear highlighted results in notes. Cursor keeps jumping to it while typing.    

## Environment

Joplin version: 1.1.4 (9610b7e (master))
Platform: Linux
OS specifics: Debian 10 buster x64, i3 window manager

## Steps to reproduce

1. Use the search bar on the top.
2. Click x that appears next to "usage".
3. Searches are still highlighted. Navigating to another notebook or note does not clear it. Cursor keeps jumping to search result while typing.
4. Restarting Joplin fixes the problem.

## Describe what you expected to happen

I expect the search results to be cleared after I click x.

## Logfile

(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397

**Comment by CalebJohn** [comment]
Hi @PaperTsar,
You're currently using an old version of Joplin. This was fixed and is working as expected in the current stable release [(v1.4.19)](https://github.com/laurent22/joplin/releases/tag/v1.4.19).

The recommended update procedure is to use the following command (assuming this is how you installed Joplin in the first place).

```
wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash
```
