### ISSUE TITLE
Horizontal Lines being rendered in the markdown pane on Solarized Themes 

### ISSUE THREAD

**Issue by mtpiercey** [laurent22/joplin#4210]
## Environment

Joplin version: Joplin 1.4.19 (prod, win32)
Platform: Windows
OS specifics: Windows 10 Home 20H2

Revision: de123ee58 (master)

## Steps to reproduce

1. Use Solarized Light or Solarized Dark them
2. Create a horizontal line (like with `****`, `---`, etc.
3. Notice that line shows up in the markdown editor panel

![image](https://user-images.githubusercontent.com/22581026/101670105-c4336880-3a20-11eb-9d59-afbb455796c2.png)

![image](https://user-images.githubusercontent.com/22581026/101670122-ca294980-3a20-11eb-823e-86a863c665b7.png)

![image](https://user-images.githubusercontent.com/22581026/101670082-be3d8780-3a20-11eb-9e34-1d918279715a.png)

Same as above but for the Solarized Light theme:
![image](https://user-images.githubusercontent.com/22581026/101670273-f2b14380-3a20-11eb-98c6-b6dad09613b6.png)

## Describe what you expected to happen

I don't think this is expected behaviour. On the Solarized Light theme, it shows both the characters used to make the line and the line itself, but I think it only shows the line on the Solarized Dark theme.

AFAIK, it only happens on the Solarized themes. To me it's rather strange (especially on Solarized Dark) since the characters used to make the line are invisible or nearly invisible after the line appears, and me cursor is left on the next line a few characters down.

Maybe this is how it's supposed to go? I personally don't mind the lines themselves in the editor - they do their jobs of separating sections of content. But the characters used to make them disappearing or nearly disappearing is kind of strange.

**Comment by CalebJohn** [comment]
If anyone else is seeing this and wishing their theme supported it, you can put the following code in your userchrome.css file

```css
.cm-hr {
  color: transparent !important;
  border-top: 1px solid black; /* Replace black with any color you want */
  display: block;
}

```

**Comment by mtpiercey** [comment]
Alright, that's actually really cool. I actually like the line, but personally I don't like having the characters disappear.

So it's great to be able to change it like that.

![image](https://user-images.githubusercontent.com/22581026/101788585-4168e700-3ace-11eb-893e-fb930ba4da5d.png)

I guess I'll close the issue - if anyone else runs into the situation I did, now they have a workaround. Thanks!
