### ISSUE TITLE
Naming a new note on a smaller screen pushes the editor/preview panel out of view

### ISSUE THREAD

**Issue by mtpiercey** [laurent22/joplin#4211]
## Environment

Joplin version: Joplin 1.4.19 (prod, win32)
Platform:  Windows
OS specifics: Windows 10 Home 20H2
Revision: de123ee58 (master)

## Steps to reproduce

1. Open a Joplin window on a smaller screen (like a vertical monitor - I think mine is 1024x1280)
2. Open both sidebars
3. Create a new note, and try to name it
4. Notice how the note title starts scrolling eventually with the start of the name moving to the left and out of sight, but the right side as you're typing it bumps into the editor/preview and pushes it first.

^ On larger screens, the time and other stuff goes beside the note name, and stop the displacement from happening

![image](https://user-images.githubusercontent.com/22581026/101671899-268d6880-3a23-11eb-9833-bb68c253d656.png)

![image](https://user-images.githubusercontent.com/22581026/101671939-32792a80-3a23-11eb-9b5d-57ff01ca983b.png)

![image](https://user-images.githubusercontent.com/22581026/101671838-0e1d4e00-3a23-11eb-863b-4e590321e112.png)

I think it pushes the notebooks panel too.

## Describe what you expected to happen

I guess the note name scrolling should just be a bit more aggressive. After it moves the editor/preview panel over by about 6 characters the scrolling works and the displacement doesn't get worse.

Obviously it's a minor thing, but I figured it was worth documenting. Obsessively toggling the sidebars tends to work the issue out. Funny enough, a longer note name is OK for notes you've already named, but if you try to move the cursor to the end of a longer name, new or not, the displacement occurs.

**Comment by CalebJohn** [comment]
I think this was fixed by 01cf0de974c6ec8d46f4af3036d09e7ba56b422a

**Comment by mtpiercey** [comment]
Great! Literally squashing bugs faster than they can be reported.

Just tested the latest dev version, and I can confirm that it is indeed fixed. 

![image](https://user-images.githubusercontent.com/22581026/101683135-8c352100-3a32-11eb-826c-319dc0f84132.png)
