### ISSUE TITLE
iOS AWS S3 Sync Failure - Raw buffer output not supported for FsDriverRN.readFile

### ISSUE THREAD

**Issue by weak-head** [laurent22/joplin#4218]
Sync failure when using S3 sync method on iOS. No encryption.

## Environment

**Sync Source:**
Joplin version: 1.4.18
Platform: MacOS
OS specifics: BigSur 11.0.1

**Sync Source:**
Joplin version: 1.4.18
Platform: Ubuntu/PopOS
OS specifics: 20.10 nvidia

**Sync Target:**
Joplin version: 10.4.1
Platform: iPadOS
OS specifics: 14.2

**Sync Target:**
Joplin version: 10.4.1
Platform: iPhone 11
OS specifics: 14.2

## Steps to reproduce

1. Sync notes using MacOS or PopOS to AWS S3 (Beta). All good and consistent.
2. Setup iOS app with the same S3 target location and access / secret token and sync it.
3. Result:

> Created remote items: 1.
> Completed: 12/12/2020 13:18
> Last error: Error: Raw buffer output not supported for FsDriverRN.readFile

Exactly the same behavior on iPhone and iPad, sync fails with the same error.

## Describe what you expected to happen

It should sync between all devices and there should be no problem.

This issue is similar or same to #3751 and #3601. 
Creating a new one, as requested in the comments.

**Comment by s0c1** [comment]
I'm having (probably) the same issue. For me: 
Sync Source is Windows 1.4.19 and target (with error) is Android 1.4.11

**Comment by wenbert** [comment]
Having the same issue.
MacOS Catalina 10.15.7 on an Android Phone

**Comment by weak-head** [comment]
🐞 up

**Comment by alexanderadam** [comment]
Just to be sure: did you keep the App open and the screen on on your mobile devices?

Because [there's currently no background sync implemented](https://github.com/laurent22/joplin/issues/3872), thus this can result in some sync errors (i.e. app started sync, screen goes off, app is killed and you have some weird state on your mobile device).

**Comment by weak-head** [comment]
Yes, the app is open and the screen is on. Actually, I was forcing the sync manually. Unfortunately, the app is unusable on Apple and Android mobile devices if you go with S3 synchronization because you cannot fetch your notes from the S3 bucket. I would say that this is a pretty critical bug for S3 sync.

**Comment by weak-head** [comment]
up 🐛
