### ISSUE TITLE
Search results in wrong order

### ISSUE THREAD

**Issue by andkopp** [laurent22/joplin#4220]
When searching notes, the entries in the result list might not be in the correct sort order. If a change is made to one of the entries, the result list will get sorted correctly.

## Environment

Joplin version: 1.4.19 (prod, darwin)
Platform: macOS
OS specifics: 10.15.7

## Steps to reproduce

1. Select View -> Sort notes by -> Title
2. Select notebook or "All notes".
3. Fill in any search term, e. g. "Joplin".
4. Result list might not be in alphanumerical sort order.

<img width="342" alt="Before" src="https://user-images.githubusercontent.com/10760101/102016474-83f62200-3d61-11eb-9868-a0866fae3a08.png">

5. Do a small change on any note in the result list. Result list entries will then automatically get sorted correctly.

<img width="344" alt="After" src="https://user-images.githubusercontent.com/10760101/102016481-8f494d80-3d61-11eb-80fe-0a2198c04883.png">

## Describe what you expected to happen

The sort order should be correct without needing to change a note.

**Comment by JackGruber** [comment]
The search is sorted according to certain criteria:  
https://joplinapp.org/spec/search_sorting/

But I think the order should not change after the edit.

**Comment by andkopp** [comment]
I did not assume it could be a feature, but you could be right.
Is there an option to get the sorting order like it is setup? I often use notes with the naming scheme YYYY-MM-DD, so I want the alphanumeric sorting also in the result list.

**Comment by louisdante9** [comment]
@andkopp is this ticket available ?

**Comment by JackGruber** [comment]
@louisdante9 i think yes, since no one else has commented on this yet and I don't have the experience to fix this.

**Comment by andkopp** [comment]
Still open.

**Comment by andkopp** [comment]
Still open.

**Comment by andkopp** [comment]
Not solved.
