### ISSUE TITLE
⚠️ Joplin Nextcloud app is deprecated ⚠️

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#4221]
[Joplin Nextcloud app](https://joplinapp.org/nextcloud_app/) is deprecated and will no longer be supported from Joplin v1.6.

It is deprecated in favour of [Joplin Server](https://discourse.joplinapp.org/t/joplin-web-api-for-nextcloud/4491/72?u=laurent), so if you are relying on it please do not upgrade to Joplin v1.6 till you are ready to migrate to Joplin Server or some other alternative.

### Will I still be able to sync my notes with Nextcloud?

Yes, syncing with Nextcloud is not and will not be deprecated. Only the Nextcloud app is deprecated and it was used only to share notes with others.

**Comment by tessus** [comment]
I think you mean Nextcloud 16....

Anyway, even nc16 and nc 17 are EOL and out of support. Soon nc18 is EOL.

Nextcloud 15 was EOL in December last year, so I really doubt that there are still Nextlcloud instances out there that are version 15.

**Comment by laurent22** [comment]
I meant Joplin 1.6.x actually, I've updated the post.

**Comment by PrzemekSkw** [comment]
I install Joplin because I can sync notes in my Nextcloud server with wedav. Why it will be no longer supported?

**Comment by tessus** [comment]
@PrzemekSkw you misunderstood. Syncing with Nextcloud is not deprecated. The Nextcloud app is deprecated. The Nextcloud app was used to share notes with others.

**Comment by tessus** [comment]
@laurent22 I think we can cloae this. What do you think?

**Comment by laurent22** [comment]
Yes I think so, it's now unpinned anyway.
