### ISSUE TITLE
Linking a stylesheet for stylesheet-icons no longer works

### ISSUE THREAD

**Issue by HermasciousLevander** [laurent22/joplin#4222]
## Environment

Joplin version: 1.4.19 (coming from 1.0.245)
Platform: Windows 10 Enterprise
OS specifics: v1909 - 18363.1198

## Steps to reproduce

1. Not be on Joplin v1.0.245
2. Not sure about any versions between, but be on Joplin v1.4.19
3. Add stylesheet in note `<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">`
4. Add what you want from the stylesheet, in my case an icon, `<code class="inline-code"><i class="fa fa-windows" aria-hidden="true" style="font-size: 0.73em;"></i></code>`

## Describe what you expected to happen

Like in v1.0.245, I expected it to render the icon.

## Logfile

There were no errors in the console log. But I'll add the logfile regardless.
[log.txt](https://github.com/laurent22/joplin/files/5687876/log.txt)

---

I make heavy use of Joplin at work (and at home for that matter) both for normal work notes and easily making guides for users. I hadn't updated from v1.0.245 because I updated at home, and with the issues with styling like #3887 and other smaller annoyances such as the second (very unnecessary) line being added after a linebreak and such. 

I needed to make use of mermaid today, and apparently it was broken in v1.0.245. It worked fine for most of it, but more advanced applications of it didn't work. Tested it out and updated after it worked.

However, apparently in v1.4.19 linking a stylesheet no longer works. I make heavy use of this to make guides easier to follow for users.

Please fix the implementation of this feature.

**Comment by HermasciousLevander** [comment]
Looking at how things are rendered inside of `rendered-md`, I see that a `<link>` is never created. There is also something different in how things are exported, as even when manually adding it, exporting to .pdf does not include the icon like v1.0.245.

v1.0.245 rendered-md DOM:
```html
<div id="rendered-md">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css" class="jop-noMdConv">
     <p>
          <code class="inline-code jop-noMdConv">
               <i class="fa fa-windows jop-noMdConv" aria-hidden="true" style="font-size: 0.73em;"></i>
          </code>
     </p>
</div>
```

v1.4.19 rendered-md DOM:
```html
<div id="rendered-md">
     <p>
          <code class="inline-code jop-noMdConv">
               <i class="fa fa-windows jop-noMdConv" aria-hidden="true" style="font-size: 0.73em;"></i>
          </code>
     </p>
</div>
```

**Comment by dpoulton-github** [comment]
This post on the forum seems to be similar regarding stylesheet linking. If so it contains a plugin that apparently makes stylesheet linking work.

https://discourse.joplinapp.org/t/external-css-per-note-is-being-ignored/13016/6

**Comment by HermasciousLevander** [comment]
Oh, that's pretty nice. It's still not properly working when I test, but at least I got a square, which is a step closer than earlier.

![image](https://user-images.githubusercontent.com/75787425/102094161-4c02e380-3e22-11eb-9c69-d03933dded29.png)

I'll have to check closer tomorrow, the only issue is that this actually makes things worse in the second reason for why I use a stylesheet like this.

When exporting to pdf, the codeblock is included in the export and the square (makes no difference if the icon is rendered or not(I can force it by manually editing the DOM again)).

![image](https://user-images.githubusercontent.com/75787425/102094669-dea38280-3e22-11eb-9b0e-cb327d13f4b4.png)

I'm just editing out my org-username, not really necessary but eh ¯\_(ツ)_/¯

You don't happen to know another way to get a similar effect?

**Comment by laurent22** [comment]
Closing as this is working as expected, but feel free to continue the discussion on the linked forum thread.
