### ISSUE TITLE
iOS and macOS client do not verify against trusted self-signed root CA certificate in iOS trust store / macOS keychain

### ISSUE THREAD

**Issue by maichai** [laurent22/joplin#4225]
## Environment

Joplin version: 10.4.1
Platform: iOS
OS specifics: 14.2

## Steps to reproduce

1. upload root CA certificate with Apple Configurator 2
2. enable full trust for the root CA certificate in the iOS trusts store
3. use WebDAV or Nextcloud to connect the Joplin app
4. check synchronization configuration
5. error: Network request failed

## Describe what you expected to happen

iOS (and macOS) have a trust store /key chain as the official mechanism to support own Certification Authorities. Self-signed CA certificates can be expicitly marked there as fully trusted. So we you are independent from cumbersome or expensive external solutions.

Such self-signed CA certificates work well with Apple apps after trusting the root CA certificate. So obviously this is a valid solution in this ecosystem.

However, Joplin for iOS and Joplin for macOS do not support this. This means that you have to get a certificate from an external CA to make Joplin for iOS work at all. For macOS Joplin there is the option to "trust" the self-signed root CA certificate by pointing Joplin to the PEM file.

Overall it makes more sense to just use the OS mechanisms as they are provided. E.g. Apple Mail, Calendar and Contacts would tell you that there is a verification error and you can then inspect the certificate and mark it as trusted.

With Joplin for iOS you are just plain stuck until you switch to LE certificates. I don't think that is the best we can do here, at least it is not at all user-friendly.

And yes, using your own self-signed root CA and trusting that certificate is perfectly secure as long as you follow best practices.

**Comment by derekyerger** [comment]
+1

This used to work on iOS when I set it up a year ago, but after getting my phone replaced under warranty I'm hitting a brick wall trying to set Joplin up again with the same self-signed certs. Importing the cert into profiles did not make the "Network request failed" go away.

Since my Nextcloud instance is intranet-only, LE isn't an option.

**Comment by devChad** [comment]
I can confirm this is still an issue with the iOS app

**Comment by maichai** [comment]
The problem is not yet fixed. Is actually someone working on this, has it made its way on the list of bugs to be fixed?

**Comment by maichai** [comment]
The problem is not yet fixed. Is actually someone working on this, has it made its way on the list of bugs to be fixed?

**Comment by maichai** [comment]
Keeping this alive, as the problem is not yet fixed. Is actually someone working on this, has it made its way on the list of bugs to be fixed?
