### ISSUE TITLE
Can't see what text I'm typing on notes after a few lines (iOS 14.2, iPhone X)

### ISSUE THREAD

**Issue by B0BIC** [laurent22/joplin#4226]
Image posted as a link because I don't know how to make it smaller:

https://user-images.githubusercontent.com/3453126/102292129-6bb90b00-3ef9-11eb-8366-e34a7b6cf38d.jpeg

## Environment

Joplin version: Latest on iOS
Platform:  iPhone X
OS specifics: iOS 14.2

## Steps to reproduce

1. Open up a new note/start editing an existing note.
2. Write more than a few lines
3. Misalignment occurs

## Describe what you expected to happen

I expected the full line to be visible while I was typing, not the top 10%.

**Comment by B0BIC** [comment]
Issue still unresolved

**Comment by CalebJohn** [comment]
Thanks for reporting this (with a screenshot).

Closed in favour of #3607
