### ISSUE TITLE
GUI Issue: screen flashes white in iOS dark theme

### ISSUE THREAD

**Issue by B0BIC** [laurent22/joplin#4228]
IMO this sort of defeats the point of having a dark theme, which is to reduce eye strain. It's not that bad in the day, but at night it can be quite jarring. Note: this is in the OLED dark mode but it happens in other dark modes as well, and it happens irrespective of whether the full iOS system is in dark or light mode.

Video of issue:

https://streamable.com/a3uh43

## Environment

Joplin version: latest iOS
Platform: iPhone X
OS specifics: iOS 14.2

## Steps to reproduce

1. 
2. 
3.

**Comment by therealkrispet** [comment]
I'd like to report the exact same issue. Is it possible to reopen this, or should I just create a new one?
