### ISSUE TITLE
export to PDF does not convert inline links `[text](link)`

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#423]
### Operating system

- macOS

### Application

- Desktop

---

When I export a note to PDF, inline links like `[text](link)` are not converted to a link in the PDF.

Example:

```
Test note

[Joplin](https://joplin.cozic.net/) is a great app.

If the link is written as plain text, it is converted to a link https://joplin.cozic.net/
```

Generated PDF file:

[test.pdf](https://github.com/laurent22/joplin/files/1909880/test.pdf)

**Comment by tessus** [comment]
I'm not sure, if this is a duplicate of #346, since plain links are converted to links in the PDF.

**Comment by laurent22** [comment]
Yes in terms of implementation, it's indeed the same as #346
