### ISSUE TITLE
Irregular sorting

### ISSUE THREAD

**Issue by hqh0803** [laurent22/joplin#4232]
## Environment

Joplin version: 1.5.7
Platform: Windows
OS specifics: Wondiws 10

## In my opinion, the rules of sorting are like mine
1
2
3
4
5
6
7
8
9
10
11
12

## The Joplin classification rule is like this
1
10
11
12
2
3
4
5
6
7
8
9

![image](https://user-images.githubusercontent.com/39184866/102599792-efbcfe00-4158-11eb-928f-4bee744f9dce.png)

## In my opinion, it should be a bug, but so far it has not been fixed

**Comment by tessus** [comment]
> but so far it has not been fixed

Because this is not a bug. Please read up on alphanumeric and numeric sorting. Joplin has always used alphanumeric order.

Btw, this has come up a few times in the forum, which is used for usability questions.
