### ISSUE TITLE
Cannot Update Joplin on Ubuntu

### ISSUE THREAD

**Issue by wbswbs** [laurent22/joplin#4234]
When trying yesterday evening several times to update my ubuntu installation with update_and_install.sh, connection was very slow, and stopped working after 20 Minutes or so.

Today I tried to download the App for Ubuntu with Chromium, and after 15 MB it timed out.

What can I do?

(See Error Message when trying to restart the download) 

<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<X-Amz-Expires>300</X-Amz-Expires>
<Expires>2020-12-19T11:09:36Z</Expires>
<ServerTime>2020-12-19T11:37:24Z</ServerTime>
<RequestId>0FEF0DFEF382871D</RequestId>
<HostId>kLABrFkvEzgmo184veu+8T3K94PCkGILv8fNOdELJKKMrbO1uDYPGytJzLYER7eSEUqWPzqXCew=</HostId>
</Error>

## Environment

Joplin version: 1.0.174
Platform: Linux
OS specifics: Ubuntu 18.04 

## Steps to reproduce

1. Try to download https://github.com/laurent22/joplin/releases/download/v1.4.19/Joplin-1.4.19.AppImage

**Comment by wbswbs** [comment]
Seemed to be a temporary problem, Download worked now

**Comment by CalebJohn** [comment]
Joplin hosts it's files with GitHub, we've had this issue a few times where it seems that GitHub slows downloads to almost almost nothing (or nothing in this case). Sorry that it happened to you, but glad you got it eventually!

It looks like you're making a pretty big jump in versions, I hope you're not too shocked by the changes!
