### ISSUE TITLE
Using Ctrl+Shift+V to paste unformatted text in the Rich Text Format editor pastes the unformatted text twice.

### ISSUE THREAD

**Issue by laribA** [laurent22/joplin#4243]
## Environment

Joplin version: 1.5.8
Platform: Windows
OS specifics: Windows Version 20H2 Build 19042.685

## Steps to reproduce

1. Enable the Rich Text editor
2. Copy formatted text
3. Use the shortcut Ctrl+Shift+V to paste unformatted text

## Describe what you expected to happen

The unformatted text would paste only once, such as:
Example

## Describe what actually happened

The unformatted text pastes twice, such as:
ExampleExample

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/5730968/log.txt)

**Comment by Philipp91** [comment]
I can still reproduce this in Joplin 1.7.11.
