### ISSUE TITLE
Scope of user defined Macro

### ISSUE THREAD

**Issue by derrring** [laurent22/joplin#4244]
## Environment

Joplin version:  1.4.19
Platform:  Win10, IOS

## Steps to reproduce

Minimal Working Example:
```
$$\newcommand{\norm}[1]{\left\Vert #1 \right\Vert}$$

$\norm{x}$
```
There is a pre-defined marco:

```tex
$\newcommand{\norm}[1]{\left\Vert #1 \right\Vert}$
```
or eqivalently 

```tex
$\gdef{\norm}[1]{\left\Vert #1 \right\Vert}$
```
this command could have been later used in math mode l by `\norm{x}`  and appeared as ||x||. However, command `$\norm{x}$
` is still verbatim rendered.

But this works:
```tex
$ \newcommand{\norm}[1]{\left\Vert #1 \right\Vert} \norm{x}$
```
Maybe the user defined macro is not globally defined, it can only work in current `$...$` block, which is not desired.

## Logfile

[-1608659536804.log](https://github.com/laurent22/joplin/files/5731333/-1608659536804.log)

**Comment by laurent22** [comment]
Hmm, yes I don't know enough about Katex to help here. All I know is that we pass around macros defined with gdef. So your newcommand will be valid within a block, but not across multiple blocks. For that you need to use gdef.

And your gdef example is not valid so I couldn't test if it works or not. I would suggest opening the dev tools (under Help menu) when something doesn't work with Katex as it will give more detailed information.
