### ISSUE TITLE
Android (LineageOS) File System Sync Error: Attempt to get length of null array

### ISSUE THREAD

**Issue by jublaze** [laurent22/joplin#4248]
I am having the same issue highlighted below on a phone running LineageOS 17. The app has permissions. I same steps work on my android tablet running stock Android 7. Is it just a lineage problem?

https://github.com/laurent22/joplin/issues/538

I'm trying to sync the joplin files via file system to a folder, and then use resilio sync to keep sync'd across devices. Regardless of whether the folder is being sync'd, I can't get the joplin add to (a) create its own folders and (b) if I create the folders manually, I get the error "Error: Attempt to get length of null array. Path: /storage/emulated/0/ ... "

## Environment

Joplin version: 1.4.11
Platform: Android
OS specifics: LineageOS 17

## Steps to reproduce

1. Install app
2. Set synchronization config to use File system
3. Specify location, e.g. /storage/emulated/0/joplin
4. If joplin folder doesn't exist, sync is non-responsive
5. If I manually create joplin folder, error message says it failed to create locks folder
6. If I create locks folder manually, error creating temp
7. Once both subdirectories are available: "Error: Attempt to get length of null array. Path: /storage/emulated/0/joplin/locks"

**Comment by cncser** [comment]
me too!

**Comment by jublaze** [comment]
Was fixed for me in latest release.

**Comment by cncser** [comment]
Thanks!


发件人: jublaze
发送时间: 2021年1月8日 11:12
收件人: laurent22/joplin
抄送: cncser; Comment
主题: Re: [laurent22/joplin] Android (LineageOS) File System Sync Error:Attempt to get length of null array (#4248)

Was fixed for me in latest release.

**Comment by jublaze** [comment]
Has been working for a dew releases now.
