### ISSUE TITLE
Evernote Import - issue with image

### ISSUE THREAD

**Issue by r0b2g1t** [laurent22/joplin#425]
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop - 1.0.83
- [ ] Mobile
- [ ] Terminal

After having imported my notes from a enex-file, some of image are not shown. I see the hash entry in the markdown and a broken image symbol in the rendered view.

Link to an enex example file: https://gist.github.com/r0b2g1t/0b22c4bddaa6ae638c64585c4a25a3cf

**Comment by r0b2g1t** [comment]
I did some investigation of the code and find a restriction of the max. dimension of the attached image.
It is set "Resource.IMAGE_MAX_DIMENSION = 1920;" in the file: [Resource.js - Line 163](https://github.com/laurent22/joplin/blob/613fa20806c5e17eaeb462b1b82329c2427c3347/ReactNativeClient/lib/models/Resource.js#L163)

And my note image has the dimension width: 1697 height: 2400.

What is the reason for this limitation and it is possible to increase or remove it?

**Comment by laurent22** [comment]
Resolution has to be capped since not all devices can support potentially unlimited image sizes, but this is not the issue here. This max size is only used when resizing a picture.

**Comment by laurent22** [comment]
I can import the file in both macOS and Windows and can see the image, so it's working for that particular file.

**Comment by r0b2g1t** [comment]
I disabled my webdav sync to hiDrive, removed the local notes and imported it again, for now it works.
