### ISSUE TITLE
Add tags to a note is extrem slow

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#4251]
Adding Tags to notes is extrem slow (nearly one second for each Tag) if you have a lot of tags/notes. 

## Environment

Joplin 1.5.7 (prod, win32)

Client ID: fea0ba97613b45d8b1c8ee33e9f08413
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f1bbcea64 (master)

**Sync status (synced items / total items)**
```
Note: 5318/5318
Folder: 48/48
Resource: 8945/8945
Tag: 1697/1697
NoteTag: 18333/18333
MasterKey: 0/0
Revision: 562/562
Total: 34903/34903
```

## Steps to reproduce

1. Open a note
2. Add some Tas
3. Save

![0e54e8d8e2a16a24c6648afdb1ae130164afc4c5](https://user-images.githubusercontent.com/24863925/103170564-689d1380-4845-11eb-98e5-c8bff52d96d6.gif)

All this in an dev installation with only a few notes and tags is much faster. 
![3dc4d73a0fa9eeed9b2a4e9cb88e34042a386d3e](https://user-images.githubusercontent.com/24863925/103170590-96825800-4845-11eb-9ba2-3e2d2d32415b.gif)

## Describe what you expected to happen

Adding tags should work significantly faster and not take almost 1 second per tag. 

## Logfile

[console.txt](https://github.com/laurent22/joplin/files/5744532/console.txt)
[log.txt](https://github.com/laurent22/joplin/files/5744533/log.txt)

**Comment by laurent22** [comment]
Hmm, yes that's not great. Although I'd be tempted to put that aside for now, since if we add support for hierarchical tags we'd need to review all this anyway and work on the performances.

When it takes one second to display each tag, is it frozen in the meantime or can you do something else. What if you add the tags, close the note, and come back. Are the tags saved?

**Comment by JackGruber** [comment]
If you select another note, it jumps back after each tag was added.

**Comment by JackGruber** [comment]
Not fixed

**Comment by roman-r-m** [comment]
Another, probably related, issue:
* Select a few notes (the more, the better) and add a few tags to them.
* At this point Joplin becomes almost unresponsive

Additionally, trying to open Tools > Options produces this exception in console
```
main-html.js:48 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by ResizableLayout)
    in div (created by styled.div)
    in styled.div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in ResizableLayout (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
```

**Comment by JackGruber** [comment]
Still a issue

**Comment by Jip-Hop** [comment]
I just selected 1767 notes and added one tag to all of them. I can see in the tags sidebar on the left that the tags are being applied to the notes one by one at a rate of 1 tag per second. Currently waiting for 13 minutes and it's not half way done.

Joplin for Desktop
Joplin 1.7.11 (prod, darwin)
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f560563 (master)

If it matters, it's also syncing simultaneously with the Joplin server on Docker.

**Comment by personalizedrefrigerator** [comment]
Related to https://discourse.joplinapp.org/t/performance-issue/37207/23

**Comment by personalizedrefrigerator** [comment]
This also seems to be making sync and JEX import much slower when importing/downloading many tags and notebooks.
