### ISSUE TITLE
bug : code copy and code block issues

### ISSUE THREAD

**Issue by darkworks** [laurent22/joplin#4254]
## Environment

Joplin version: 1.5.11
Platform:  windows
OS specifics:  win 10 

**step to reproduce**
- create new note
- in note body type : **this is sample code**
- select what u wrote and click **inline code** button 
- now exit note and come back to note by clicking some note on left notes menu

**issue #1 copy issue** 
- select inline code : **this is sample code**   with mouse and right click and click copy
- open note pad and do paste you will find that its not pasted  aka blank.
**issue #2 ? sign with copy content** 
- select inline code : **this is sample code**   with mouse and press Ctrl + C to copy
- open note pad and do paste you will find something like this : `this is sample code?` this ? symbol occur sometime it start and sometime it end.

issue #3 : extra copy of code with code block
- sometime when i add code block and i click code block button and add code then extra copy of it is created 
![image](https://user-images.githubusercontent.com/12841788/103191543-3350fe00-48f7-11eb-93ac-5b2fc8f8a2bf.png)
![image](https://user-images.githubusercontent.com/12841788/103191567-49f75500-48f7-11eb-851b-8ad38d1a4351.png)

## Describe what you expected to happen

should copy code without any ? sign

**Comment by isdnfan** [comment]
the problem still exists and much worse the most important issue is not mentioned: 
- it is impossible to select (and copy) snippets marked as multi-line code using \`\`\`

example:
```
test copy from code snippet
```
echo "123"
```
`echo "123"`
```

produces following output:

![image](https://user-images.githubusercontent.com/18125597/106669111-76178d00-65ab-11eb-8944-0ad6a887f3ba.png)

**Comment by isdnfan** [comment]
unchanged in Joplin 1.7.11 (prod, win32)

**Comment by isdnfan** [comment]
unchanged in Joplin 1.8.5 (prod, win32) - copy of multi-line code blocks doesn't work in reach editor

**Comment by isdnfan** [comment]
looks good in **Joplin 2.1.7 (prod, win32)**
copy&paste works for both multi-line and single line code blocks!
