### ISSUE TITLE
Menu icon is not visible in top right corner in low resolution

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#426]
### Operating system

- Android

### Application

- Mobile

And note is sometimes displayed as HTML code.

Its a Samsung Galaxy Fame Model Number GT-S6810P  Android version 4.1.2

![screenshot_2018-03-26-17-35-34](https://user-images.githubusercontent.com/1285584/38802976-1ac6a706-416e-11e8-84a2-614a6b4ce358.png)
![screenshot_2018-03-26-17-35-51](https://user-images.githubusercontent.com/1285584/38802979-1aefff16-416e-11e8-8f38-8ed27fc22e36.png)

**Comment by mm64** [comment]
I experience the problem that the menu icon is not visible on a LG G2. I can tap on the upper right corner and the menu appears, but the icon is not visible. The problem affects portrait as well as landscape orientation. Some more information about the system:
- Joplin 1.0.116
- LG G2 (model D802, no operator-branding)
- Android 4.4.2
- No custom ROM, no root
- Google play services 11.9.51 (030-177350961)
- Full HD display (1920 x 1080)

![screenshot_2018-04-30-13-14-04](https://user-images.githubusercontent.com/22786238/39425254-cf76232c-4c7a-11e8-8df1-b76d4f04fd2b.png)
![screenshot_2018-04-30-13-14-15](https://user-images.githubusercontent.com/22786238/39425255-cfb422e4-4c7a-11e8-92e8-2ab17640884b.png)

**Comment by laurent22** [comment]
@mm64, do you also sometimes have the note displayed as HTML?

**Comment by mm64** [comment]
Not until now, but I still haven't used the app much.
