### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Jomme5** [laurent22/joplin#4264]
Joplin starts with black screen. Even after 'quit' and restart. Latest version on Windows 10 Home. Standard webbrowser: Opera.
No log-file found. Path?

![joplin](https://user-images.githubusercontent.com/4696640/103301031-b01bcf00-4a00-11eb-9b8e-25e48854d79d.png)

**Comment by tessus** [comment]
Please attach a debug log. Issues without a debug log are likely to stall.
  For information on how to collect a log file: https://joplinapp.org/debugging/

**Comment by Jomme5** [comment]
Can't reproduce anymore after changing altered usersstyle.css with this one: devonzuegel/joplin-custom-css. Anyways; debug-flags are set.

**Comment by tessus** [comment]
Ok, it seems we can close this then.
