### ISSUE TITLE
[Feature Request] Publish Joplin in Microsoft store

### ISSUE THREAD

**Issue by Beowulf2** [laurent22/joplin#4265]
### Operating System
- Windows

### Application
- Desktop

***

**Related to #582** 

***

It would be nice if the app is published in the Microsoft Store, since the Surface devices have Windows 10 S installed by default. With this version, only programs from the Microsoft Store can be installed. Windows 10 S is supposed to be a better optimized and more resource efficient for the Surface devices, which is why you might not want to disable the Windows 10 S Mod.

**Especially when the pen integration ( #582 ) comes, this might make a lot of sense.**

Unfortunately, I couldn't find any tips/instructions on how to publish an app to the Microsoft Store.

**Comment by MarkGTI** [comment]
I can't install app on my work pc unless it's in ms store.
