### ISSUE TITLE
Syncing errors on Android 11

### ISSUE THREAD

**Issue by maxmopp** [laurent22/joplin#4266]
I am syncing Joplin (1.5.1 v34) to local filesystem on Android 11 /crDroid(Surya)
It does look as everything gets synced both directions, but joplin locks up for ... seconds
The corresponding logcat looks different from the one on Android 10 /LOS where the same sync does not lock the app.
[logcat.log](https://github.com/laurent22/joplin/files/5751956/logcat.log)

**Comment by maxmopp** [comment]
OK not a bug. What can I do on my end to remedy the problem?

**Comment by tessus** [comment]
Closing this. For questions how to use Joplin, the forum is the right place.

**Comment by maxmopp** [comment]
Yeah, sure that 
E/unknown:ReactNative(17243): ReactInstanceManager.createReactContext: mJSIModulePackage null
E/ReactNativeJNI(17243): logMarker CREATE_REACT_CONTEXT_END
E/ReactNativeJNI(17243): logMarker RUN_JS_BUNDLE_START
will be resolved in the forum.
Thanks anyway
