### ISSUE TITLE
Android AWS S3 sync Could not download resource. "Error: Not implemented"

### ISSUE THREAD

**Issue by adam-wolski** [laurent22/joplin#4268]
Syncing on android using S3 does not download resources.

## Environment

Joplin version: 1.5.1
Platform: Android
OS specifics: Android 10 (4.14.113-user+)

## Steps to reproduce

1. Enable AWS sync on PC and sync notes with resources(.png, .svg, seems to be any file)
2. Enable AWS sync on Android and try to sync

## Describe what you expected to happen
All resources being synced without errors.

## Logfile

![Joplin Bug](https://user-images.githubusercontent.com/6629924/103341237-a472eb80-4a86-11eb-948a-12859f63c3c8.png)

**Comment by andresmith** [comment]
Same for iOS

Joplin version: 10.5.1
Platform: iOS 14.3 (iPhone Xr )

![image](https://user-images.githubusercontent.com/4972767/103437021-e9d01e00-4c2a-11eb-805c-388473bb2941.png)
