### ISSUE TITLE
Cannot see URL and other meta data of evernote imported notes 

### ISSUE THREAD

**Issue by grotesque** [laurent22/joplin#427]
### Operating system

- Windows

### Application

- Desktop

Evernote's export contains some meta data about notes. Eg. the URL that the note was clipped from.
It should be possible for those who're migrating to this awesome project to search their notes with URL.

![untitled](https://user-images.githubusercontent.com/305091/38821507-5160409c-41be-11e8-9ba4-6edd7a4e5f3a.png)

**Comment by laurent22** [comment]
Yes the source URL is imported but indeed not visible at the moment.

**Comment by jgreth** [comment]
+1
**Is it save, the URL exported from Evernote is saved in the Joplin data und just not showed?**
Today i'm starting to migrate 6k+ notes form Evernote to Joplin and it would be a huge Problem if the URLs are gone...

**Comment by foxmask** [comment]
if you want to be sure, export one evernote note from the desktop application, import it with joplin and then have a look at the database.

```
sqlite3 ~/.config/joplin-desktop/database.sqlite
select * from notes; 
```

(I dont know if it "source" or "source_url" that store this info)

**Comment by jgreth** [comment]
It's the col "source_url" - and it's empty. I think it's just not implemented / saved to db. I'm not that deep in React (more the "old-PHP-guy" :) ) but i think if we want to have imported, it should be done in [import-enex.js#L355](https://github.com/laurent22/joplin/blob/3822309657eda6e06250df15e81760c53bb4f8ca/ReactNativeClient/lib/import-enex.js#L355) and following. 

Can you or @laurent22 approve that?

(I checked in Win10 and Ubuntu 18.04 with the clients linked from [the homepage](https://joplin.cozic.net/). )

**Comment by laurent22** [comment]
I was certain the URL was imported to source_url but apparently not. Do you have by any chance an example of ENEX note that has a URL so that I know what to map source_url to?

**Comment by foxmask** [comment]
[evernote api](http://dev.evernote.com/doc/reference/Types.html#Struct_ResourceAttributes) says sourceURL or [blog post](https://blog.evernote.com/tech/2013/08/08/evernote-export-format-enex/) says source-url.

**Comment by jgreth** [comment]
@laurent22 That's no problem. I'll upload an enex file, on monday.

**Comment by jgreth** [comment]
Ok @laurent22 here we go. The Evernote Client (Win10) i export from is Version `6.10.3.6921 (306921) Public (CE Build ce-1.39.4387)`.
The code inside the file can be found at: [https://gist.github.com/jgreth/bead69c0875ac3f4620987f3c874dc47](https://gist.github.com/jgreth/bead69c0875ac3f4620987f3c874dc47) or the file itself attached here.
[Testfile.zip](https://github.com/laurent22/joplin/files/2067261/Testfile.zip)
(Had to zip it, cause github won't let me upload enex files)

**Comment by jgreth** [comment]
Info / Update: my Evernote client just updated to version `6.11.2.7027 (307027) Public (CE Build ce-43.0.4829)`.
I exported the same Note and Diffed it with my previous posted one - format didn't change.

**Comment by jgreth** [comment]
@laurent22 Was that the infor you wanted? Or went something wrong?

**Comment by laurent22** [comment]
@jgreth, thanks for the providing the Enex sample - the source-url parameter will be supported in the next release.

**Comment by jgreth** [comment]
Nice! Tank you so much. Then i can finally switch away from Evernote. ;)

**Comment by jgreth** [comment]
@laurent22 looked in v1.0.107 didn't see. Am i blind or will it come in v1.0.108? ;)

**Comment by laurent22** [comment]
What is it you didn't see in v107? The source-url parameter is still not being imported?

**Comment by jgreth** [comment]
Yes ist was the source-url parameter. But I think it was a buggy enex. Tried now again, with a newer enex file and now it works - so everything ok. Sorry for the trouble! ;)

**Comment by onetom** [comment]
I can confirm too that and export with **Evernote** `macOS Version 7.10 (457750 Direct)` can be imported with **Joplin Desktop** `1.0.158 (prod, darwin)` and source URLs are preserved.

```
onetom@uhu /V/D/sqlite> nix-shell -p rlwrap sqlite --run 'rlwrap sqlite3 ~/.config/joplin-desktop/database.sqlite'
SQLite version 3.28.0 2019-04-16 19:49:53
Enter ".help" for usage hints.
sqlite> select count(*) from notes;
5545
sqlite> select count(*) from notes where source_url !="";
5405
```

This issue can be closed, IMHO.

**Comment by laurent22** [comment]
Thanks for the confirmation @onetom. The issue can indeed be closed.
