### ISSUE TITLE
WebClipper not saving the URL

### ISSUE THREAD

**Issue by homofortis** [laurent22/joplin#4270]
Please add an option in WebClipper to store the source page URL alongside clipped content.

**Comment by JackGruber** [comment]
Click on the i Icon. The URL is already saved!

**Comment by homofortis** [comment]
@JackGruber sorry, it's not working for me. When I use "Clip Screenshot" for example, it saves only the image. If later I want to explore the page from which the image was clipped I am out of options. The only way to store the URL with the clipped image is to store the URL (in a separated note) and then copy and paste to the note with the image.

**Comment by JackGruber** [comment]
Also an "Clip Screenshot" the URL is saved!
![grafik](https://user-images.githubusercontent.com/24863925/103412900-a7013e00-4b77-11eb-96ca-0e086bac0485.png)

When you have problems, then post more informations. Like in the description when you create a new issue. 
https://joplinapp.org/clipper/#troubleshooting-the-web-clipper-service

**Comment by homofortis** [comment]
Wow! Great, thank you!
