### ISSUE TITLE
Unable to Move a subnote out of a main note

### ISSUE THREAD

**Issue by ShobanChiddarth** [laurent22/joplin#4271]
## Platform

Joplin version: 1.5.14 (prod, win32)
Platform: Windows
OS specifics: x64

Revision: 9e076bf19 (master)

## Steps to reproduce

1. Create a notebook
2. Create another notebook
3. Move the another notebook to the notebook to make it subnotebook
4. Try to move it out again
5. You cant

[Recording](https://www.loom.com/share/b91cc8d19ac94e34a509ffc7f74ca57d)
I somehow tried to move those subnotes 1 and 2 but I'm not able to move them outside of Welcome

## I expect it to
Make that subfolder again a main folder (note)

## Logfile
[log.txt](https://github.com/laurent22/joplin/files/5754552/log.txt)

(Nothing came in the console)

**Comment by JackGruber** [comment]
Drag the Notebook the `NOTEBOOKS`
![grafik](https://user-images.githubusercontent.com/24863925/103360685-4a3f4e00-4ab9-11eb-8bfa-48897c9df08f.png)

**Comment by ShobanChiddarth** [comment]
Yes thanks, it worked and helped.
