### ISSUE TITLE
attachments - in and out 

### ISSUE THREAD

**Issue by ajay-gh** [laurent22/joplin#4282]
Please feel free to close this issue if it doesn't suit your guidelines. I have read them, but because of the nature of the subject it is half bug and half feature request. The table at the end of this issue provides a summary. More details are found in the Joplin discourse thread with the same title. 

Altogether, the different issues listed in the following table may best be described as "inconsistent handling of different attachment types across platforms". 

![7b969b6f0ae75533b0303d0fce98734ba5c233ce_2_1380x788](https://user-images.githubusercontent.com/46941311/103467084-3444be00-4d43-11eb-95b0-622917e87c00.png)

Joplin versions tested are mentioned in the table.

**Comment by laurent22** [comment]
Thanks for looking into this, but unfortunately this kind of table is not really actionable. An issue should contain only one bug report with detailed description and steps to replicate it. That makes it easier to try to fix it, or to discuss whether this is a bug or accepted limitation, and whether it's high or low priority.

Also if there are multiple bugs it makes it hard to ever close the issue or to reference it from a commit or pull request.

**Comment by roman-r-m** [comment]
Retrieving attachments on Android should be available again starting from the next version.

**Comment by ajay-gh** [comment]
issue to be replaced, closing now
