### ISSUE TITLE
Bug: Keyboard shortcut ctrl + ` not being recognised when in UK keyboard layout

### ISSUE THREAD

**Issue by Daeraxa** [laurent22/joplin#4284]
Unable to use the default 'ctrl + `' key shortcut (or assign any other command to this combination) to mark text in a code block when computer is set to UK layout keyboard.

## Environment

Joplin version: Joplin 1.5.14 (prod, linux)
Client ID: 3adaf3953f6d45ac86b4baa78d9d7be0
Sync Version: 2
Profile Version: 34
Keychain Supported: No

Revision: 9e076bf (master)
Platform: Linux 
OS specifics: Linux Mint 20, Linux 5.4.0-53-generic

(Also in Win 10, Joplin 1.5.14)

## Steps to reproduce

1. Highlight text and press 'ctrl + `'
2. Nothing happens
3. Open tools > options > keyboard shortcuts, attempt to assign 'ctrl + `' as a shortcut
4. ` key is not recognised
5. Change keyboard layout to English (US) from English (UK)
6. Both of the above methods are successful

## Describe what you expected to happen

Key combination should be possible regardless of layout

**Comment by laurent22** [comment]
Hmm, yes I wouldn't how to fix this. For me Ctrl+` and in fact many other shortcuts don't work because I'm on a French keyboard. If someone has a solution though I'd accept a pull request.

**Comment by Daeraxa** [comment]
It seems like it could be a problem with Electron? I found this online:
https://github.com/electron/electron/issues/17287

**Comment by tessus** [comment]
Let's put it that way. No matter which keyboard layout, dead keys won't work as shortcuts ever.

While I grew up in Europe and have been living in Canada for the past 15 years, I've never used any other keyboard layout than `us-en`.
IMO the layout is the best for programming, w/o having to use the shift key for many characters needed in programming. I'm not saying everybody should switch, but I'm rather trying to say that many people are using that layout, even though it's not their native language or locale.

**Comment by Daeraxa** [comment]
Even if many people do use that layout it is still a fairly arbitrary restriction. Almost nobody in the UK uses the US keyboard layout and Laurent clearly uses the French one. There isn't really a good reason to a regular end user as to why that key combination wouldn't work.
 
To me the solution would be either:
1) Rebind the default inline code shortcut to something globally available to all keyboards. Alternatives I've seen on some other editors include ctrl + . and ctrl + m.
or
2) I've just been having a look at Marktext which uses the same combination + electron to see what was done as a workaround there. It looks like it is using a couple of Electron modules to:
-  get the current keyboard layout and 
-  get the keypresses before they are passed to chromium and rebind them to virtual keys on the fly. - https://github.com/marktext/marktext/blob/develop/src/main/keyboard/shortcutHandler.js

**Comment by tessus** [comment]
I'm against changing the default. We created the shortcut editor so that people could assign shortcuts that work for them.
You will never make it work for ALL keyboard layouts.

At one point we'll run out of keys or nice defaults. Either way, IMO this is not a bug. e.g. on macOS I can press `opt+u` to create an umlaut or `opt+e` to create an accent aigu, and so on. However, I can't use these dead keys to create a shortcut.

**Comment by Daeraxa** [comment]
On the standard UK layout it isn't actually a dead key, in order to get a \` you only need a single keypress of the `¬| button, no modifiers. On US-intl and UK-extended it does indeed function as a dead key.
Looking back at the Marktext 'fix' I posted before, I'm not even 100% certain that the solution is even modifying UK keyboards as it isn't present in the list of codes but that is far, far beyond my knowledge.
I agree that the shortcut editor is present to allow changes for people but shouldn't the default be something that works for everybody (i.e standard letters) and the option granted to those who don't want the universal solution rather than actively forcing the change on those it (silently) doesn't work for?

**Comment by Daeraxa** [comment]
Actually I just noticed something is fundamentally more funky here.
If I go to the shortcuts editor and press the following keys as an assignment I get the following:
\' prints \`
\# prints \'
` prints nothing
All the other symbol keys (sans modifiers) enter correctly (, . \\ / [ ] ;)

**Comment by tessus** [comment]
It uses the keycode, not the key.

The keycode for `6` and `^` is the same on a certain layout. I just took the us-en layout. But on your, there would be other keys that have the same keycode.

Another example

Shift+5 = %, but `%` would never show up in the keyboard editor, because you have to press `Shift` and `5` to generate `%`. So the shortcut is `Shift+5` and not `%`. However, in the json file you can use `%` and it will be translated to `Shift+5`.

**Comment by Daeraxa** [comment]
I'm not sure if that entirely matches up though? No modifiers are used to get the \' symbol. I went to https://keycode.info/ to see what keycode and event was being registered - pressing the same 3 physical buttons on my keyboard, only changing the keyboard layout option:

UK
\` = 192 = Backquote
\' = 222 = Quote
\# = 163 = Backslash

US
\` = 192 = Backquote
\' = 222 = Quote
\\ = 220 = Backslash

The \` key is outputting the same keycode no matter if it is set to UK or US.

**Comment by tessus** [comment]
> # = 163 = Backslash

Is it pound or backslash? Or does the UK keyboard use the same key for both?

**Comment by Daeraxa** [comment]
The hash key is # and ~. Our backslash is on the \ | key (code 220 - IntlBackslash) (the third item is the event.code data rather than just my own description).

**Comment by tessus** [comment]
I think you missed my point. In your comment you have `pound sign = 163 = Backslash`. 

<img width="164" alt="image" src="https://user-images.githubusercontent.com/223439/103549629-ad443280-4e75-11eb-8f99-afd24c7670d7.png">

**Comment by Daeraxa** [comment]
The key we are talking about on a UK layout is the key next to return:
![image](https://user-images.githubusercontent.com/58074586/103552418-c95ec880-4ea3-11eb-8d8d-5c46491b6c7c.png)
Pressing this key produces # (unmodified) and ~ (+ shift).
Pressing this key on https://keycode.info/ with keyboard set to UK layout produces the following data:
event.code = Backslash
event.which = 163
event.key = #
Using a different tool - https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code
KeyboardEvent: key='#' | code='Backslash'

**Comment by tessus** [comment]
I still don't understand the problem. If you press `#` on your keyboard and the keycode is 163, everything is fine.

In the map it is listed as such, see https://github.com/laurent22/joplin/blob/dev/packages/lib/services/KeymapService_keycodeToElectronMap.ts#L167

As mentioned before, we look at the keycode.

If for some reason the wrong keycode is returned for a certain key, this is rather an upstream issue. I can only work with what is returned from the framework.

**Comment by Daeraxa** [comment]
Well that is the issue in itself. The editor, search bar, textboxes in options etc. all display the correct character when those three buttons are pressed. The _only_ area of the application where it is either not recognising or otherwise incorrectly mapping those keys is in the shortcut editor (and on trying to use the set shortcuts in-app) - and that is without even using a modifier of any kind:
Result of pressing those three keys in options > keyboard shortcuts > search (these all correspond correctly to the pressed button)
![image](https://user-images.githubusercontent.com/58074586/103557509-3b86db80-4eab-11eb-8ee7-77aa76e79989.png)
Result of pressing those exact same three keys in the shortcuts assignment column of the same page:
(pressing \` does not do anything)
pressing \' 
![image](https://user-images.githubusercontent.com/58074586/103557729-8b65a280-4eab-11eb-88cc-33e8bf7a4d58.png)
pressing # 
![image](https://user-images.githubusercontent.com/58074586/103557793-a20bf980-4eab-11eb-989e-2bd680900242.png)

**Comment by jamesfoxlee** [comment]
Interesting reading this. I'm on a UK keyboard layout and experiencing same issue as @Daeraxa

As they said, my ` key works perfectly in the text editor, titles etc and all other applications. But not in the Keyboard Shortcuts mapper in Options. No key is recognised.

I'm running Pop!_OS. Could this issue be reopened?

**Comment by SomeMichael** [comment]
Also facing this issue with a German keyboard.

I was not not able using the default shortcut for assigning code formatting. I tried to change the shortcut to `Ctrl-#`. But when pressing `Ctrl-#`, `Ctrl-/` shows up in the shortcut field on the settings page. So Joplin seams to think I'm on a US keyboard.

As mentioned above already: the `#` key works just fine everything else within Joplin.

This is not a big pain for me, since there are a lot of other options for setting shortcuts, but I wonder why this issue is closed. From an end-user perspective that is really weird. Probably lots of users are facing this, but not taking the time to bring it up here ;-)

Running Joplin 3.4.12
