### ISSUE TITLE
Bug: Strange behaviour of todo and checklist items in Rich Text editor

### ISSUE THREAD

**Issue by Daeraxa** [laurent22/joplin#4286]
From https://discourse.joplinapp.org/t/joplin-wysiwyg-editor-problem-windows/13572
Strange display issue in the Rich Text editor where bullet points are being displayed as todo items and can be unintentionally converted.

## Steps to reproduce

- Copy:

```
- bullet 1
    - bullet 2
    - bullet 3
- [ ] todo 1
    - [ ] todo 2
    - [ ] todo 3
```
into a note and press the Rich text editor button, Rich Text editor show below formatting

![image](https://user-images.githubusercontent.com/58074586/103481403-b62ff800-4dd2-11eb-856a-725d638a8696.png)

- Change back to MD editor, MD text did not change

- From Rich Text editor and tick the tickbox on 'bullet 1' (bullets 2 + 3 cannot be ticked) then change back to MD. MD now shows:

```
- [x] bullet 1
    - [ ] bullet 2
    - [ ] bullet 3
- [ ] todo 1
    - [ ] todo 2
    - [ ] todo 3
```
## Environment

Joplin version: Joplin 1.5.14 (prod, linux)
Client ID: 3adaf3953f6d45ac86b4baa78d9d7be0
Sync Version: 2
Profile Version: 34
Keychain Supported: No

Revision: 9e076bf (master)
Platform: Linux
OS specifics: Linux Mint 20, Linux 5.4.0-53-generic

(Also in Win 10, Joplin 1.5.14)

## Describe what you expected to happen

Rich text editor should display the boxes as per the markdown

**Comment by laurent22** [comment]
Yes that's a limitation of the rich text editor. All the items in the list must be of the same type, so it should be all checkboxes or all bullet points. To have different kinds, you can separate them with an horizontal ruler for example.

**Comment by Daeraxa** [comment]
Was about to ask if you wanted a PR for the doc but just noticed you have already updated it. Thanks
