### ISSUE TITLE
Code block not recognized by Joplin WebClipper

### ISSUE THREAD

**Issue by desk7** [laurent22/joplin#4287]
## Environment

Joplin version: 1.5.14; Firefox 84.0.1 with WebClipper 1.4.3
Platform: Windows 10 
OS specifics: 1909

## Steps to reproduce

1. Go to https://learning.lpi.org/en/learning-materials/010-160/1/1.2/1.2_01/
2. Clip semplified page

## Describe what you expected to happen
In the web page there are some blocks of code within pre tag. I expect Joplin to recognize them as code blocks.

However, it imports them as normal text.

**Comment by laurent22** [comment]
The simplified mode cannot produce exactly what you expect all the time. In some cases, like in this one, it's going to change certain parts that would like to preserve. When that happens, it's best to clip the complete page, which for this URL works fine. I'd say in general any page with code blocks or complex HTML should be clipped as complete page for maximum compability.
