### ISSUE TITLE
Switching from md to WYSIWYG editor strips some html out

### ISSUE THREAD

**Issue by SugoiDev** [laurent22/joplin#4288]
## Environment
Joplin version: 1.5.14 (9e076bf19)
Platform: Windows
OS specifics: Windows 10 20H2 (build 19042.685)

## Steps to reproduce

1. Create a note with the following content
```
NORMAL
<p style="color: red;">RED</p>
```
All good:
![image](https://user-images.githubusercontent.com/7355630/103483853-dc509a80-4dc8-11eb-908b-b95d4588018c.png)

2. Switch to the WYSIWYG  and change anything
Before changing:
![image](https://user-images.githubusercontent.com/7355630/103483826-a90e0b80-4dc8-11eb-931f-054708e558d4.png)
Changed, but still ok:
![image](https://user-images.githubusercontent.com/7355630/103483832-b6c39100-4dc8-11eb-9ebb-7653a10925a8.png)

3. Switch back to md view and notice the html is gone:
![image](https://user-images.githubusercontent.com/7355630/103483836-c04cf900-4dc8-11eb-8b99-bc5d1576327c.png)

## Describe what you expected to happen
Data loss should not occur.

## Logfile
Relevant log is below

```
2021-01-03 13:42:54: "CommandService::execute:", "toggleEditors", "[]"
2021-01-03 13:42:54: "replaceResourceInternalToExternalLinks", "options:", "{"useAbsolutePaths":true}", "body:", "NORMAL
<p style="color: red;">RED</p>"
2021-01-03 13:42:54: "replaceResourceInternalToExternalLinks result", "NORMAL
<p style="color: red;">RED</p>"
2021-01-03 13:42:54: "Saving settings..."
2021-01-03 13:42:54: "Settings have been saved."
2021-01-03 13:43:00: "replaceResourceExternalToInternalLinks", "options:", "{"useAbsolutePaths":true}", "pathsToTry:", "["file://T:/Joplin/JoplinProfile/resources","file://T:/Joplin/JoplinProfile/resources","file://T:\\Joplin\\JoplinProfile\\resources","file://T:\\Joplin\\JoplinProfile\\resources"]"
2021-01-03 13:43:00: "Saving note...", "{"id":"c6c63da26fe649278eeedcf714a14dfa","parent_id":"0a00d4675bfb425680db49b65f1db632","title":"test","body":"NORMAL\n\nAnother normal\n\nRED"}"
```

I've seen this reported before in #2886 (now closed). This issue might also be related to #3948

**Comment by SugoiDev** [comment]
Extra information: not ALL html is stripped out.
For instance, the `<p>` tags were, but if the content is this:

```
<div style="background-color: black;">
<p style="color: red;">RED</p>
</div>
```
The `<div>` will survive the switching.

**Comment by tessus** [comment]
Switching between the editors is not really supported. The WYSIWYG was created for ppl who don't know or want markdown.

So you can either use WYSIWYG or markdown. There are also many markdown plugins not supported in WYSIWYG, see `Preferences -> Markdown`: `(wysiwyg: no)`
While I do understand the issue, I doubt that it is a bug. Maybe Laurent can elaborate a bit more.

**Comment by SugoiDev** [comment]
Interesting.
Do you think co-existance will be possible in the future?
Markdown is enough for me, but I share many notes with others that would not think so.

**Comment by tessus** [comment]
I can't answer that. Let's wait for Laurent's input. (I have never used the WYSIWYG editor and never will.)

**Comment by SugoiDev** [comment]
I thought about it a bit more, and if they can't coexist, maybe there should be a warning about the risk of data loss when first switching from one to another.
I did read the warning when I clicked the WYSIWYG editor, and didn't see anything in particular about this issue.

I'll try to familiarize myself with the codebase in the coming months to understand the issue better.

**Comment by tessus** [comment]
In the documentation it states that some things rae not compatible with the WYSIWYG editor, but maube it could be more specific.

**Comment by Daeraxa** [comment]
There was another limitation recently regarding the wysiwyg editor, Laurent simply added the new 'known' limitation (regarding bullet point/todo lists).

**Comment by SugoiDev** [comment]
I think increasing interop between the editors is nice, and I would be willing to work this html stripping issue myself (in a few months time) if no one with more experience wants it. 

That is, of course, as long as it is compatible with the community's vision.

If the consensus is that the rich text editor should never be used on the same note as the markdown one, then I think a stern warning alongside with adding this limitation to the 'known limitations' list will be enough.

**Comment by laurent22** [comment]
As a general rule the Rich Text editor can only support what Markdown supports, and Markdown doesn't do colours so it's unlikely we'll support this.

**Comment by SugoiDev** [comment]
Maybe we should add a warning when opening an html note in the Rich Text editor? Or even disabling the rich text editor for HTML notes.

I have a number of notes that were saved with Evernote's webclipper. Those will often need to be html.
Evernote has a feature where you can add some text that is prepended to the note when saving using the web clipper.
A common use for me is to give a "gist" or context for the note, or to add something to remind me better of the content of the clipped page. That text is often edited when re-reading the saved pages.
In that case, if one was to accidentally edit it in the rich text editor, it would drastically change the note's content.
Since many of those notes are shared, it could easily lead to heavy data loss, since I'm the only one that would be on the md editor 100% of the time.


Would you consider accepting a PR to add a new option to disable the rich text editor for html notes?

**Comment by laurent22** [comment]
I don't quite understand what you mean. The rich text editor can open and edit HTML notes just fine, or if it doesn't please provide an example JEX file. The limitation has to do with the Markdown/HTML conversion, which doesn't happen for HTML notes.

**Comment by SugoiDev** [comment]
I imported the notes from Evernote's enex format using the "as HTML" option, then edited one of the notes and noticed some formatting stripped out. 

Maybe I'm doing something wrong.
Are all notes with HTML content considered HTML notes? Or is there something else I must do to "mark" the notes as being HTML notes?

**Comment by laurent22** [comment]
> I imported the notes from Evernote's enex format using the "as HTML" option, then edited one of the notes and noticed some formatting stripped out.

Still need the jex or enex file, or we are just making assumptions about everything.

**Comment by Daeraxa** [comment]
I guess the question here is how does one change the "Markup" value (when clicking on the Note properties button) from Markdown to HTML or vice versa. What is it in Joplin that 'chooses' the correct one?
It seems this issue does not happen when a note is set to Markup > HTML, only when you have HTML in a note that is Markup > Markdown.

**Comment by SugoiDev** [comment]
Yes, I just tested against a clean environment with a single note and can't reproduce it when the markup is HTML. As Laurent said, rich text works.

It seems the import "as HTML" somehow imported some nomes as markdown (I'm investigating this right now), and the stripping was coming from that.

**Comment by kenricashe** [comment]
> As a general rule the Rich Text editor can only support what Markdown supports, and Markdown doesn't do colours so it's unlikely we'll support this.

The issue does not appear to be relevant to colors. In my testing I found that html tags in general remain intact, but the <p> tag is stripped even when it has no attributes.

So, the following survives edits in RTE and is even supported in the Markdown viewer pane:

Here is some <span style="color: red;">RED</span> text.

Side note: The <s> tag for strikethrough (as mentioned in the Markup Guide) is also stripped, whereas <strike> survives although converted to <span style="text-decoration: line-through;">.

Perhaps the documentation should be updated these details?
