### ISSUE TITLE
Release on PortableApps.com?

### ISSUE THREAD

**Issue by kr4z33** [laurent22/joplin#429]
### Operating system

- Windows

### Application

- Desktop

A humble feature request, could this application be released on PortableApps.com?

**Comment by kr4z33** [comment]
There is a discussion on their side:

https://portableapps.com/node/57914

Looks like they want a 32 bit executable - I cannot speak to their acceptance criteria, I am only a user of their program

**Comment by kr4z33** [comment]
If you, (or somebody) takes the trouble to figure it out, here's a bounty via FreedomSponsors. Anyone else that may find this useful can sweeten the offer as well.

https://freedomsponsors.org/issue/829/make-joplin-available-on-portableappscom
					
If you resolve this issue (see my acceptance criteria there) please use that site to request your payment.

**Comment by laurent22** [comment]
I made various changes to get it to compile to 32-bit and created a test package in PortableApps format there: https://github.com/laurent22/joplin/releases/download/v1.0.82/JoplinPortable.zip

Could you give it a try and confirm it's working? Not sure if they will accept it at portableapps.com but we can try to get it approved anyway.

**Comment by kr4z33** [comment]
Your test package seems to be working, thanks for the quick attention!

**Comment by quotengrote** [comment]
Yep, its working fine.

**Comment by laurent22** [comment]
There's now a .paf package available there for testing: https://portableapps.com/node/58085

**Comment by laurent22** [comment]
A portable version of Joplin will now be available with each new release: https://joplin.cozic.net/#desktop-applications The application can be installed on a USB drive, etc. however it is not an official "PortableApps" version.

It's not clear what apps PortableApps accept or not (it seems they neither accept nor reject any submitted app), so it's not sure at all Joplin will be available in their store.

**Comment by kr4z33** [comment]
Thanks for the quick progress on this. Per the PortableApps.com discussion, the update checker should point the user to the newer portable formatted app, it seems to grab the non-portable installer. 

I could not find any toggle for disabling automatic update checks, adding that as suggested by Ken @ PA.c might be nice for making the portable test versions a bit less nagging, if the test versions over at PA.c's testing discussion are going to lag the one released on joplin.cozik.net.

**Comment by laurent22** [comment]
As far as I can tell PortableApps no longer accept new applications. I think they release process is quite heavy and each new apps add to the burden of the maintainer so they can't really add more.

On the other hand, I've now submitted it to the Portable Freeware Collection. If any of you has an account there and could vote for the app that would be much appreciated. It needs to get 10 votes before it can become public:

https://www.portablefreeware.com/index.php?id=2977

**Comment by tessus** [comment]
@laurent22 what's the status of this? It doesn't seem to be public yet.
