### ISSUE TITLE
No hints or reference count shown when removing attachments from `Note attachments`

### ISSUE THREAD

**Issue by hysci** [laurent22/joplin#4290]
## Environment

Joplin version: 1.5.11
Platform: Windows 10
OS specifics: N/A

## Steps to reproduce

1. Open Joplin, new a note, toggle editors, attach a file from the local disk, source: [test.txt](:/7fc04ca690b64a13bfb4e3101a524bff)
2. Now I can get the renamed attachment `7fc04ca690b64a13bfb4e3101a524bff.txt` in `joplin-desktop\resources`
3. Remove `[test.txt](:/7fc04ca690b64a13bfb4e3101a524bff)`, now Joplin says it will not be watched if switching to another note.
4. Switch to another note, do some editing, the attachment `7fc04ca690b64a13bfb4e3101a524bff.txt` is sitll in `joplin-desktop\resources`, however, I've no ways to get that the reference count of this file is ZERO.
5. Add another attachment `[test2.txt](:/a5742e5696a24a2c99df3197102550de)` Go to `Note attachments` windows, click the buttons `delete` to delete both `test.txt` (reference count = 0) and `test2.txt` (reference count = 1), no hints are given to the users that the reference count if `test2.txt` is non-ZERO.

## Describe what you expected to happen

I would expect either
Option 1: Giving the user a hint that some file is referenced when deleting an attachment. Or
Option 2: Adding a column in the `Note attachments` windows to show the total reference number of the attachment.

Otherwise, the deleting operation is dangerous.

## Logfile

N/A

**Comment by tessus** [comment]
Usability issues go in the forum.

> Otherwise, the deleting operation is dangerous.

It is dangerous. That why there's a warning at the top:

**This is an advanced tool to show the attachments that are linked to your notes. Please be careful when deleting one of them as they cannot be restored afterwards.**

There's no reference count and there won't be one. See discussions on the forum.
