### ISSUE TITLE
The checkbox list disappears when switching from WYSIWYG view and Markdown view 

### ISSUE THREAD

**Issue by hysci** [laurent22/joplin#4291]
## Environment

Joplin version: 1.5.11
Platform: Windows 10
OS specifics: N/A

## Steps to reproduce

1. File -> new to-do
2. Go to WYSIWYG view, insert a 2x2 table, click the checklist button within a grid, a square is shown
2. Switch to Markdown view, the source is
|     |     |
| --- | --- |
| - [ ] test |     |
3. Switch back to WYSIWYG view, the square disappears instead of `- [ ] test`

## Describe what you expected to happen

One of the following actions is resonable: 
* It is claimed/hinted that a checkbox in a table is not supported.
* The square should not change when switching views.

**Comment by tessus** [comment]
Not a bug. 

Checkboxes are not supported in tables according to markdown specs.
Also -> https://github.com/laurent22/joplin/blob/dev/readme/rich_text_editor.md
