### ISSUE TITLE
Data lost when using the webdav to sync data

### ISSUE THREAD

**Issue by yanqingwang** [laurent22/joplin#4294]
I am using the joplin on arch linux, windows 10 and also Android. 

Recently i noticed that some notes will be lost when i start the synchronization. 10 minutes ago, i created the 3 notes on one computer, and I see the notes are saved successfully.

several minutes later, I found there is only one notes exist.

Before that, I found that the data lost quite often, especially when i deleted some notes or re-organize the notes.

I don't know which part lead the issue, webdav provider or jopline itself.

I am using the sites as webdav server: https://dav.jianguoyun.com/dav/joplin

**Comment by yanqingwang** [comment]
If  any more information is needed, please guide me and I can try to provide more information if necessary

**Comment by CalebJohn** [comment]
I think you might find the following link helpful.

https://discourse.joplinapp.org/t/joplin-deletes-local-file/8679/2

It seems that jianguoyun.com does not properly support the WebDav protocol and this leads to lost data.

You can try searching for the term jianguoyun here and on the [forum](https://discourse.joplinapp.org/) to see more discussion about the problem.

**Comment by laurent22** [comment]
Indeed we don't support jianguoyun due to their faulty WebDAV implementation.

**Comment by yanqingwang** [comment]
Thanks for your answer.

**Comment by yanqingwang** [comment]
> Indeed we don't support jianguoyun due to their faulty WebDAV implementation.

I contacted jianguoyun, and their reply confirmed Frank's estimation. Currently, 750 documents or folders are allowed for one time request.  And their server support multiple times, multiple pages request. 

I am not an expert about the webdav protocols, and I am wondering if Joplin support it. Will it be usefully when  we start the sync with a small package content?

You may not able to understand their reply directly, I still paste their reply here and hope we can work out something to make Joplin works with jianguoyun.

I saw some discussion in the form, and found they all agree that it Jianguoyun has a better performance.



Reply from: helpdesk@nutstore.net

目前坚果云的WebDAV协议单次请求文件数（包含文件和文件夹）为750个，支持分多页多次加载。如果您使用WebDAV的三方工具未实现按分页多次加载，可能会出现文件同步不完整的情况，建议您使用坚果云客户端进行直接同步。

我们推测可能是joplin不支持分多页多次加载，当文件数（包含文件和文件夹）超过限制后，就会导致文件无法上传，此时可能会导致文件无法直接保存导致的丢失。

我们也将该限制写在了坚果云帮助中心了：https://help.jianguoyun.com/?p=2064 

感谢您的理解与支持！

**Comment by laurent22** [comment]
It's unlikely jianguoyun will be explicitely supported.  As far as I know it's the only WebDAV implementation that drops requests past a certain limit, and Joplin does not handle this. The proper way for them would to throttle connections as other file cloud storages do, but I don't expect they'll change this.

**Comment by clzls** [comment]
Although it is closed but I want to mention that it may be better to mention new users to use file system sync + official app rather than to try to use WebDAV directly. (haven't try that myself, though)

虽然这个工单被关闭了，但我还想评论一下：或许改用文件系统同步+官方客户端能解决？我不确定。

**Comment by JackGruber** [comment]
>Although it is closed but I want to mention that it may be better to mention new users to use file system sync + official app rather than to try to use WebDAV directly. (haven't try that myself, though)

@clzls sorry, but this comment is absolute ... 
The problem is the WebDAV implementation from the provider. 
Many including me use the WebDAV syncronisatio without probleme with different providers!

**Comment by clzls** [comment]
> > Although it is closed but I want to mention that it may be better to mention new users to use file system sync + official app rather than to try to use WebDAV directly. (haven't try that myself, though)
> 
> @clzls sorry, but this comment is absolute ... The problem is the WebDAV implementation from the provider. Many including me use the WebDAV syncronisatio without probleme with different providers!

After reading this I realized that my words failed to express my thoughts... (blame my poor English for this)
I mean that (since it's the restrictions from the *Jianguoyun* side,) new *Jianguoyun* users may use file system sync with *Jianguoyun's* official app as a workaround...

**Comment by vivimillin** [comment]
I've just send an email to jianguoyun (helpdesk@nutstore.net), calling on them to make some improvements and provide a better standard interfacea as other file cloud storage providers. we will see...

On the other hand, however, Jianguoyun is almost the only cloud storage provider stable and accessible in China that provides webdav interface, so there are a large number of Chinese users who use a variety of "sync" software with it, such as Zotero, Joplin and so on.

**Comment by CyrusYip** [comment]
> On the other hand, however, Jianguoyun is almost the only cloud storage provider stable and accessible in China that provides webdav interface, so there are a large number of Chinese users who use a variety of "sync" software with it, such as Zotero, Joplin and so on.

You can try InfiniCLOUD, which is accessible in China.
