### ISSUE TITLE
math formulas don't wrap text

### ISSUE THREAD

**Issue by stavpup** [laurent22/joplin#4295]
he is an example of a math formula,
text does not wrap like regular text and it only shows in one line no matter the lenght.

'
$$ Τ.Μ.(€)=(ΒΚ)*Α+(ΒΚ)*Α*Β*(Κ-1)=780*1.33+(780*1.33*0.053)*(9-1)=1477,24 $$
'

Environment

Joplin version: Desktop 1.4.19
Platform: Android, windows
OS specifics: Android 10, windows 10

**Comment by stavpup** [comment]
![image](https://user-images.githubusercontent.com/10577035/103521741-ec788080-4e81-11eb-967b-996718385cd8.png)

**Comment by tessus** [comment]
This is not really a bug in Joplin. see https://github.com/KaTeX/KaTeX/issues/327

For a discussion what to set as the default in Joplin the forum might be the better choice. But according to the linked issue, you should be able to change that in your `userstyle.css`
