### ISSUE TITLE
[request] todo

### ISSUE THREAD

**Issue by pcause** [laurent22/joplin#43]
early i know, but this has promise.  I'd like to suggest a modification to a todo. usually a todo has a due date and then optionally an alarm.  you only have an alarm.  can we make todos work like other apps?  also, it would be good to have the due date show next to the todo title in the notebook notes list.

**Comment by tessus** [comment]
@laurent22 are due dates planned for todos? also I'm not quite sure what the OP meant. so a due date could be different from an alarm? in that case there could be several alarms set for one todo. This seems rather complex.
