### ISSUE TITLE
Ticked checkbox requires uppercase X

### ISSUE THREAD

**Issue by despens** [laurent22/joplin#430]
Checked checkboxes in Joplin require an uppercase `X`. Would be good if lowercase `x` would be supported as well:
![selection_00641](https://user-images.githubusercontent.com/571494/38834027-77d19a1a-41c7-11e8-93f4-7371095cb42f.png)

### Operating system

- Linux
- Android

### Application

- Desktop
- Mobile

**Comment by laurent22** [comment]
Fixed in #448. Thanks @solariz!
