### ISSUE TITLE
Comments in markdown get lost when editing in the rich text editor and switching back

### ISSUE THREAD

**Issue by asheeshr** [laurent22/joplin#4301]
## Environment

Joplin version: 1.5.14
Platform: Linux
OS specifics: Ubuntu 16.04

## Steps to reproduce

1. Add a comment in the markdown editor
2. Switch to the rich text editor
3. Make an edit
4. Switch to the markdown editor and comment will be lost

## Describe what you expected to happen

Comments in the markdown editor should persist when switching across different views/editors for the same note.

**Comment by tessus** [comment]
There are no comments in markdown, thus they are not preserved. This is not a bug.

**Comment by asheeshr** [comment]
It's standard HTML comment tags I'm using, not markdown, that get lost.

**Comment by asheeshr** [comment]
Can this be re-opened with updated information? I incorrectly stated markdown comments; I'm using HTML comment tags.

**Comment by laurent22** [comment]
When switching between rich text and Markdown editor, the rich text editor is only going to generate valid Markdown. Comments are not Markdown, which is why they are not going to be regenerated. It's a limitation of the current Rich Text editor.
