### ISSUE TITLE
How to open a note directly by using command (Windows/OSX versiong but NOT console version)

### ISSUE THREAD

**Issue by glight2000** [laurent22/joplin#4302]
Is ther any command usage like
```bash
 MacOS /Applications/Joplin.app/Contents/MacOS/Joplin --note-id dda184f6c1524a0b93bb6dfb3a0d2020
```
Or some api like this
`
http://localhost:41184/cmd/opennote/dda184f6c1524a0b93bb6dfb3a0d2020
`
If I want to start Joplin with the specific note/directory/etc... comes up directly.

**Comment by CalebJohn** [comment]
It's not currently possible, you can find more information [in this forum post](https://discourse.joplinapp.org/t/open-a-note-in-desktop-app-using-commandline/13433/2).

The plan is to eventually support x-callback-urls
