### ISSUE TITLE
Mobile: long press on images  to share them

### ISSUE THREAD

**Issue by rankaiyx** [laurent22/joplin#4312]
it works very well in version 1.3.7
but It doesn't seem to work in version 1.5.1 and 1.6.4

## Environment

Joplin version: 
Platform: android 9
OS specifics:

**Comment by roman-r-m** [comment]
Should work again starting from the next version

**Comment by rankaiyx** [comment]
> Should work again starting from the next version

Okay, look forward to it.

**Comment by tessus** [comment]
fix is here https://github.com/laurent22/joplin/commit/8492a7ee268ef76fcff99b366d925cb59976d5f2

so all pre-releases and releases after that will have the fix.
