### ISSUE TITLE
Desktop: spellchecker inserts corrections at random places in text when UI is zoomed

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#4317]
Joplin 1.5.14 (prod, win32)

Client ID: 8129c25cca08408db9608fbf677fee34
Sync Version: 2
Profile Version: 34
Keychain Supported: No

Revision: 9e076bf19 (master)

* Create a new note and paste text with errors, e.g.
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
```
* Set cursor at any word but the first
* The 1st work should be highlighted by spellchecker, right click and pick any suggested replacement
* Replaced text inserted at random position (somewhere around the middle of the line for me).

I'm using Joplin zoomed in, if I set zoom to 100% there's no issue,

**Comment by CalebJohn** [comment]
Thanks for reporting this, seeing the report completely sidetracked me for the last hour because I new exactly where the problem was, but wasn't sure why it would happen. Like a lot of random bugs, this one is unfortunately upstream, but we can get around it :).
