### ISSUE TITLE
Emoji support?

### ISSUE THREAD

**Issue by dariosalviwork** [laurent22/joplin#432]
### Operating system

- Windows

### Application

- Desktop

From the picture on the main Joplin page I can see that there some nice icons, but I have tried with some `:emoticon:` but was not successful.

**Comment by zblesk** [comment]
Not sure this needs specific support, except maybe a font that has emoticons. 
Hint: if you're on the newest Windows 10, you can use `Win + .` (that is, windows key plus dot) or `Win + ;` to display the system's emoji keyboard. Inserting them from there to Joplin works well for me.

**Comment by laurent22** [comment]
Emojis are displayed as normal but they need to be entered via the operating system built in method. It's generally easier on mobile but it's starting to be well supported on desktop too: https://blog.bufferapp.com/emojis-keyboard-shortcut-mac-windows
