### ISSUE TITLE
Error during ENEX file import on bad source xml

### ISSUE THREAD

**Issue by greyshine** [laurent22/joplin#4320]
I am running into an endlessly running import on Joplin.
Source file is a .enex-file from Evernote.
I did extract the (first) failing imported <note> from the xml to reproduce the issue.
Joplin does not further inform but stays on the import screen showing the import process but actually doing nothing.

The problematic enex/xml can be downloaded here: [https://we.tl/t-EHP6Sp1EdJ]()
(Size is 20MB, File will be deleted on 14Jan2021; ask me for a file if it is not there...) 

As recognized on the source file the failing section is wrapped into CDATA which is interpreted as Xml.
The xml is logically not valid. a &lt;li&gt; item is marked as wrong since it is not covered by an &lt;ul&gt; or &lt;ul&gt;.

As I come down there is actually two issues regarding joplin.  
1. Imported items in terms of evernote's notes should be handled seperately. One failing not must not terminate the whole process. Personally I think this is the more important issue.
2. Handling of evernote's data in terms of each &lt;note&gt;-Element could be improved due to errors.

## Environment

Joplin version: Joplin for Desktop, Joplin 1.5.11 (prod, darwin), Revision: c158878 (master)
Platform: MacOS Catalina 10.15.7

## Steps to reproduce

1. Take the source file and run import through menu //JOPLIN//File/Import/Enex - Evernote Export File (as Markdown)
2. Select file to import...
3. let it run...

## Describe what you expected to happen

I expect the process to terminate sooner or later. 
Showing failed imports would be nice. Telling the reason why it failed would be even nicer.
The process should import as much items (enex-xml: <note>...</note>) as possible instead of breaking the process on the first errornous item.

Probably (also) a 'back' or 'cancel' button would be of help.

## Logfile

I turned logging on as described on the page.
I did used the application / browser like log informations since they show a understandable and reporoducable state:

    main-html.js:58 Environment: prod
    main-html.js:79 appId: net.cozic.joplin-desktop
    main-html.js:80 appType: desktop
    /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:165 12:31:23: App: Profile directory: /Users/dirkschumacher/.config/joplin-desktop
    ...
    /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:165 12:32:39: CommandService::execute: showModalMessage Importing from "/Users/dirkschumacher/docs/progging/proj-temp/output/128.enex" as "enex" format. Please wait...
    
    loaded: 1
    created: 0
    updated: 0
    skipped: 0
    resourcesCreated: 0
    notesTagged: 0
    /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/import-enex-md-gen.js:422 Line 0:9985: Found <li> tag without being inside a list
    displaySaxWarning @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/import-enex-md-gen.js:422
    (anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/import-enex-md-gen.js:626
    emit @ events.js:310
    EventEmitter.emit @ domain.js:482
    me._parser.<computed> @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:258
    emit @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:624
    emitNode @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:629
    openTag @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:825
    write @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:1398
    SAXStream.write @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:239
    ondata @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/string-to-stream/node_modules/readable-stream/lib/_stream_readable.js:619
    emit @ events.js:310
    EventEmitter.emit @ domain.js:482
    addChunk @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/string-to-stream/node_modules/readable-stream/lib/_stream_readable.js:291
    readableAddChunk @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/string-to-stream/node_modules/readable-stream/lib/_stream_readable.js:278
    Readable.push @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/string-to-stream/node_modules/readable-stream/lib/_stream_readable.js:245
    (anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/string-to-stream/index.js:18
    processTicksAndRejections @ internal/process/task_queues.js:79
    /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/import-enex-md-gen.js:631 Uncaught TypeError: Cannot set property 'startedText' of undefined
        at SAXStream.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/import-enex-md-gen.js:631)
        at SAXStream.emit (events.js:310)
        at SAXStream.EventEmitter.emit (domain.js:482)
        at SAXParser.me._parser.<computed> [as onopentag] (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:258)
        at emit (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:624)
        at emitNode (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:629)
        at openTag (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:825)
        at SAXParser.write (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:1398)
        at SAXStream.write (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:239)
        at StringStream.ondata (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/string-to-stream/node_modules/readable-stream/lib/_stream_readable.js:619)
    (anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/import-enex-md-gen.js:631
    emit @ events.js:310
    EventEmitter.emit @ domain.js:482
    me._parser.<computed> @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:258
    emit @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:624
    emitNode @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:629
    openTag @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:825
    write @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:1398
    SAXStream.write @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/fork-sax/lib/sax.js:239
    ondata @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/string-to-stream/node_modules/readable-stream/lib/_stream_readable.js:619
    emit @ events.js:310
    EventEmitter.emit @ domain.js:482
    addChunk @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/string-to-stream/node_modules/readable-stream/lib/_stream_readable.js:291
    readableAddChunk @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/string-to-stream/node_modules/readable-stream/lib/_stream_readable.js:278
    Readable.push @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/string-to-stream/node_modules/readable-stream/lib/_stream_readable.js:245
    (anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/string-to-stream/index.js:18
    processTicksAndRejections @ internal/process/task_queues.js:79
    /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:165 12:33:07: Preparing scheduled sync
    
    ...

**Comment by laurent22** [comment]
Already fixed in latest version

**Comment by greyshine** [comment]
Yes. it works. Thank you for handling!
Import does not not terminate but handles all my items. Some are errornous but that is more likely another issue.
