### ISSUE TITLE
Missing scripts in JPL plugin file

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#4323]
`generator-joplin version 1.6.10`

No additional script files are packed into the jpl release file. 
![grafik](https://user-images.githubusercontent.com/24863925/103932206-c96bfc00-5121-11eb-9f80-a308779502f9.png)

I have seen the `content_scripts` section in the `generator-joplin`doc. But was thinking this is only for scripts when `registerContentScript` is used? 
Do JavaScript also have to be specified in the content_scripts section if they are not for `registerContentScript` at all? 
Because in my jpl after the `npm run dist` the `webwiev.js` is missing, if I add it via content_scripts it will be packed into the jpl.

**Comment by laurent22** [comment]
Right, I hadn't thought about that but webview script should be handled like content scripts. I think I'll simply add a "webviews" keys in manifest.json and that will be used to process them like the content scripts.

**Comment by laurent22** [comment]
That should be fixed in the latest generator version. If you update `npm install -g generator-joplin && yo joplin --update` and compile again, it should package it like before, without requiring to add the files as content scripts.
