### ISSUE TITLE
Printing and Notifications not working in Linux Mint 20

### ISSUE THREAD

**Issue by johnb0647** [laurent22/joplin#4326]
I don't know if this is a config issue (either Linux or Joplin) or a bug but....

## Environment Joplin 1.4.19 (prod, linux)
Platform:  Linux
OS specifics:  Linux Mint 20 Cinnamon

## Steps to reproduce

1. Select any note, select PRINT, --> "Could not print: no valid printers available.
          I CAN print from any other app.  I can cut note content and past into another app
          and it WILL print.

2.  Dozens of TO DO notes have alarms set.  None ever trigger alarm/notification.
3. 

## Logfile

Log.txt prior to setting debug flags

[log file pre set debug.txt](https://github.com/laurent22/joplin/files/5790001/log.file.pre.set.debug.txt)

Log.txt after setting debug and restart
[log file post Set Debug and reboot.txt](https://github.com/laurent22/joplin/files/5790010/log.file.post.Set.Debug.and.reboot.txt)

**Comment by laurent22** [comment]
In the log there are only notifications being scheduled to a later date, but none has been triggered. Just try a simple test: create an alarm in a few minutes, then if it doesn't start, check the log and post it here. Please also let us know at what time the alarm was supposed to be triggered.

**Comment by Daeraxa** [comment]
For reference I just tried this on Linux Mint 20 Cinnamon but on Joplin 1.5.14.
- Created a todo note, entered title + body text
- Added alarm
- Alarm triggers at correct time

**Comment by laurent22** [comment]
Thanks for confirming @Daeraxa, looks like we can close the issue then.

**Comment by johnb0647** [comment]
Problem Update -
RE: notification on joplin alarm. 
       Further google search revealed switch under Setup/Sound/Sound to turn notification sound on/off

RE: No Printing
1. Close Joplin and restart - printing does NOT work
2. physically disable LAN by unplugging ethernet cable
3. PRINTING WORKS
4.  plug ethernet cable in again
5. PRINTING DOES NOT WORK
6. unplug ethernet cable
7. PRINTING WORKS

[log.txt](https://github.com/laurent22/joplin/files/5793852/log.txt)

**Comment by johnb0647** [comment]
Further update - 
RE: notification on joplin alarm
       Previous to changing the setting of the Setup/Sound/Sound switch, the alarms WERE NOT generating notifications, silent or otherwise.
       Updating Linux Mint 20.0 this morning MAY have affected problem.
ISSUE CONSIDERED CLOSED.

Printer issue remains OPEN, IMO

**Comment by johnb0647** [comment]
Just realized that alarms and printing are two separate issues.

Do you want me to move the printing issue to a new topic?
