### ISSUE TITLE
Able to get data from Joplin Data API without token

### ISSUE THREAD

**Issue by pluma9** [laurent22/joplin#4327]
Joplin version: 1.6.5
Platform: Windows
OS specifics: 10

## Steps to reproduce

1. Enable the clipper service
2. Run the Powershell command: `Invoke-RestMethod  http://localhost:41184/tags`
3. The clipper service successfully responds with a list of tags.

## Describe what you expected to happen
The clipper service responds with an error because the caller did not pass any authorization token.

## Logfile
**log-clipper.txt**

```
2021-01-09 13:41:30: "Starting Clipper server on port 41184"
2021-01-09 13:41:44: "Request: GET /tags"
```

## Screenshots
Clipper service status:
![2021-01-09 13_46_15-Joplin - Options](https://user-images.githubusercontent.com/16544647/104085365-5c6f7800-5281-11eb-9467-ace36404a605.png)

Able to fetch tags without token:
![2021-01-09 13_49_07-D__temp ~ PowerShell 7 1 (26384)](https://user-images.githubusercontent.com/16544647/104085376-80cb5480-5281-11eb-8032-4d444a681f55.png)

**Comment by tessus** [comment]
https://discourse.joplinapp.org/t/joplin-rest-api-why-are-certain-endpoints-whitelisted/10696
