### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by GokdenizK** [laurent22/joplin#4328]
Sorry for opening the topic here. If help on Turkish translation is needed, I can help.

**Comment by laurent22** [comment]
Please see the documentation on how to help with translation.

**Comment by GokdenizK** [comment]
Oh, ı had not searched for it. I am working on two other open source localisation projects. Having finished them, I will do joplins'

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by GokdenizK** [comment]
Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
