### ISSUE TITLE
Ticking a checkbox scrolls to top of note

### ISSUE THREAD

**Issue by despens** [laurent22/joplin#433]
In a long Todo-Note with some checkbooks, ticking a checkbox will always scroll the note back to the top. The scroll position shouldn't change when a checkbox is ticked. 

### Operating system

- Android

### Application

- Mobile

**Comment by croulibri** [comment]
I face the same problem

**Comment by tiaga** [comment]
I decided to migrate from Notes only because of checkboxes support, but it appears that this bug makes checkboxes unusable, especially with a long list (shopping list as an example). Please fix it.

**Comment by fvictorio** [comment]
This happens to me in the desktop version on linux. Joplin version: `Joplin 1.0.117 (prod, linux)`.
