### ISSUE TITLE
Windows client no sync notes that was created in Android.

### ISSUE THREAD

**Issue by thevinirocks** [laurent22/joplin#4333]
## Environment

Joplin version: 1.5.14 (prod, win32) | 1.5.1 Android (last one so far).
Platform: Windows and Android
OS specifics: Windows 10 and Android 11

## Steps to reproduce

1.  When a note is created using the sharing button of Android OS the note is created and all seems to be synced.
![image](https://user-images.githubusercontent.com/6668172/104132599-33bcb080-535d-11eb-847e-1a7cbf3f1316.png)

2.  On Windows 10 this note and notebook that I made on Android is not synced
![image](https://user-images.githubusercontent.com/6668172/104132750-16d4ad00-535e-11eb-8baa-d6dc487b8abc.png)
![image](https://user-images.githubusercontent.com/6668172/104132771-353aa880-535e-11eb-89ee-0be29addda60.png)

3. 

## Describe what you expected to happen
sync itens that is created in android on Windows client too.

## Logfile
[log.txt](https://github.com/laurent22/joplin/files/5793173/log.txt)

**Comment by DawMatt** [comment]
What sync target are you using on each platform?

**Comment by thevinirocks** [comment]
Onde drive! On both Mon Jan 11 00:17:17 GMT-03:00 2021 laurent22/joplin <reply@reply.github.com>: What sync target are you using on each platform? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by roman-r-m** [comment]
There were lots of problems with OneDrive recently due to some issues on MS side. Might be related to the issue you're seeing.

**Comment by thevinirocks** [comment]
How could I check this? I tried on other clients (Arch Linux too) but its the same. If I reset and reinstall the android app those files previously created in android is sync but not in other clients.

**Comment by roman-r-m** [comment]
I think it's been fixed in the latest version but you may need to reinstall rather than update and also set up sync from scratch on windows.
I suggest you check the forum.

**Comment by thevinirocks** [comment]
Problem on 1.5.14
![image](https://user-images.githubusercontent.com/6668172/104508573-33bfe900-55c7-11eb-8d1c-11eb6083c51e.png)

A new release is out 1.6.7
Test
![image](https://user-images.githubusercontent.com/6668172/104508898-a92bb980-55c7-11eb-81eb-67b238c2cfa2.png)

Those itens made on android app seems to show now, so I think It's fixed. 

Yeah I took a look on the forum, a lot of people with the same problem. Thank you for your support. If I get into something I open another issue.
