### ISSUE TITLE
fuse mounted location can't be used

### ISSUE THREAD

**Issue by Miosame** [laurent22/joplin#4334]
## Environment

Joplin version: 1.5.11.3207
Platform: Linux
OS specifics: Linux Mint 20 64bit

## Steps to reproduce

1. mount a remote with rclone - https://rclone.org/commands/rclone_mount/ (or any other fuse based system)
2. try to set the mounted location to sync from
3. get `Error: ENOENT: no such file or directory, scandir /path/to/my/folder/locks
`

**Comment by Miosame** [comment]
Not resolved

**Comment by Miosame** [comment]
Not resolved

**Comment by Miosame** [comment]
Not resolved

**Comment by roman-r-m** [comment]
How did you install Joplin?

**Comment by Miosame** [comment]
@roman-r-m appimage, snap, flatpak - they all share the same issue

**Comment by Miosame** [comment]
Thanks for your continued worry bot, I'm still facing this issue indeed

**Comment by roman-r-m** [comment]
Works for me when mounted like this:
```
rclone --vfs-cache-mode=full mount ...
```

**Comment by Miosame** [comment]
@roman-r-m I have since moved over to simple file syncing, but a quick test seems to prove indeed fruitful, closing! cheers :partying_face:
