### ISSUE TITLE
Backblaze S3 compatible API decrypts forever

### ISSUE THREAD

**Issue by Miosame** [laurent22/joplin#4335]
## Environment

Joplin version: 1.5.11.3207
Platform: Linux
OS specifics: Linux Mint 20 64bit

## Steps to reproduce

1. Setup an S3 syncing remote in joplin with a backblaze bucket instead - https://www.backblaze.com/b2/docs/s3_compatible_api.html
2. It'll sync just fine
3. Now it'll decrypt forever at x/11 items per cycle
4. It'll stay in that mode forever, even with just 800 notes to decrypt, showing only a single item in the sidebar as "encrypted"

**Comment by Miosame** [comment]
Not resolved

**Comment by Miosame** [comment]
Not resolved

**Comment by Miosame** [comment]
Not resolved

**Comment by chevdor** [comment]
Such a bot can be really annoying...

**Comment by Miosame** [comment]
@chevdor in theory it's quite useful, but in practice I just have to each time login to tell the bot to get lost, most others won't bother and it'll drown genuine issues in this spam, truly a marvelous bot :+1:

**Comment by dreamflasher** [comment]
Please reopen and turn off the stale bot.
