### ISSUE TITLE
Windows Client - Text formatting with Ctrl Key not being saved

### ISSUE THREAD

**Issue by pier-da** [laurent22/joplin#4337]
When formatting note text with Ctrl+B (Bold) or Ctrl+I (Italic) for example the formatting is not saved when switching to another note. 

If the Bold/Italic buttons are pressed on the toolbar however it does save when switching.

**Comment by SugoiDev** [comment]
Could not reproduce on 1.6.6 on Windows.

**Comment by pier-da** [comment]
Thanks for checking. Just checked, I'm on 1.5.14 Windows.

On any part of note, select text and press Ctrl+B. Now choose another note under the search bar and go back to original note.

Formatting is gone. If you use the toolbar though, formatting persists.

**Comment by pier-da** [comment]
Upgraded to 1.6.6 same issue.

**Comment by Daeraxa** [comment]
I can replicate it in 1.5.14 on Windows but it is worth nothing this is only in the rich text editor and not the standard editor.

**Comment by kenricashe** [comment]
Confirmed in Windows and Ubuntu, both freshly installed, but again only in the Rich Text editor. Easy to replicate by just switching to Markup. Ctrl+B and Ctrl+I in Rich Text editor simply are ignored in the underlying Markup, but clicking the B and I buttons for bold and italic does work.
