### ISSUE TITLE
Display equations?

### ISSUE THREAD

**Issue by cossio** [laurent22/joplin#434]
### Operating system

- Linux

### Application

- Desktop

Both $$ \sum_i f(x)$$ and $\sum_i f(x)$ render as inline equations:

![image](https://user-images.githubusercontent.com/10637482/38944042-da9773e2-4300-11e8-8f96-1e908ba7d729.png)

What can I do to get a proper display equation (for example, the index in the sum should be *below* the sum), like this:

![image](https://user-images.githubusercontent.com/10637482/38944077-f1fd04fc-4300-11e8-875f-8db588e99760.png)

**Comment by cossio** [comment]
For some reason, 

$$
\begin{aligned}
\sum_i
\end{aligned}
$$

renders as a proper display equation.

**Comment by laurent22** [comment]
Is this one a valid notation anyway?

![](https://user-images.githubusercontent.com/10637482/38944042-da9773e2-4300-11e8-8f96-1e908ba7d729.png)

Or should both inline and block notations be changed to this one?

![](https://user-images.githubusercontent.com/10637482/38944077-f1fd04fc-4300-11e8-875f-8db588e99760.png)

**Comment by cossio** [comment]
@laurent22 Both are valid notations. The first one is commonly used when the equation is in the same line as the text, so it is more "compressed".

Maybe the issue is that Katex is not seeing both dollar signs together in $$ ... $$? Perhaps for some reason the parser is only capturing one of the dollar signs and therefore interpreting it as an inline equation?

**Comment by luriomer** [comment]
Since joplin lies on katex on this one, I don't think this is a bug in joplin itself.

**Comment by cossio** [comment]
@luriomer Katex renders display equations. Could it be a problem in the way the text is sent to katex?

**Comment by laurent22** [comment]
It probably renders the markdown too frequently. It's fine when it's just text to HTML, but the Katex formula as slower to render so it's causing an issue. I will add something to make it render less frequently when Katex is used.

@cossio, I'm not completely familiar with Katex notation but if, in the background (i.e. it won't be visible), we wrap all Katex blocks in `\begin{aligned}`  `\end{aligned}` would it fix the issue? Could this cause any problem if the user wants a different alignment?
