### ISSUE TITLE
Issue 386 still happens on a fresh install but this is the solution ...

### ISSUE THREAD

**Issue by paulfeakins** [laurent22/joplin#4342]
Dropbox with a large number of files seems to get stuck syncing on Ubuntu (Linux Mint XFCE in my case).

Running dropbox from the command line gives you the answer, but the GUI does not and many users seem to be stuck on this without finding the solution.

More info here:
*redacted*

**Comment by laurent22** [comment]
Thanks but this issue tracker is only for bug reports.
