### ISSUE TITLE
Arch Linux Packaging

### ISSUE THREAD

**Issue by masterkorp** [laurent22/joplin#435]
### Operating system

- Arch Linux

### Application
- Desktop
- Terminal

Hello, first of all, congratulations on the creation on this tool, its awesome.

I just created an package for Joplin both terminal and desktop version for Arch Linux, its currently on the [AUR](https://aur.archlinux.org/packages/joplin/) and on [github](https://github.com/masterkorp/joplin-pkgbuild). It can be easly installed with a AUR warper such as yay with:
```
yay -S joplin
```

Would you like to add this availability to the README on how to installl joplin?

Regards,
Alfredo Palhares

**Comment by laurent22** [comment]
Great, thanks for the package! I've now linked to it from the readme and website.

**Comment by masterkorp** [comment]
Hello @laurent22 

The way you added it to documentation makes it look like its the terminal only version that is packaged for Arch Linux.

By the way calling ``joplin`` opens the desktop version (which also has a .desktop icon), and ``joplin-cli`` open the terminal version.

Regards,
Alfredo Palhares

**Comment by masterkorp** [comment]
Oh, I did not know of that, I will make a fix.

**Comment by masterkorp** [comment]
Fixed, the binaries are now renamed, ``joplin`` opens the terminal one and ``joplin-desktop`` opens the dekstop.

**Comment by laurent22** [comment]
Thanks @masterkorp, I've updated the readme to mention the packaged desktop app too.
