### ISSUE TITLE
Search for no results

### ISSUE THREAD

**Issue by 0x2CA** [laurent22/joplin#4352]
## Environment

Joplin version: 1.6.7
Platform: Windows 10

## Steps to reproduce

1. Create a new notebook
2. Change the title to `项目适配AndroidX`
3. Content is `# 项目适配AndroidX`
4. Search `AndroidX ` in the search bar

## Describe what you expected to happen
This note should be displayed, but there are no notes displayed here

**Comment by bearzyj** [comment]
Looks the same issue as https://github.com/laurent22/joplin/issues/4482
