### ISSUE TITLE
Re-download, kill the app, and re-open it will crash

### ISSUE THREAD

**Issue by JiangAshao** [laurent22/joplin#4353]
## Environment

Joplin version: 10.5.1 and 10.6.2
Platform: iPhone7
OS specifics: iOS 10.3.3

## Steps to reproduce

1. Re-download
2. open Joplin
2. kill the app
3.  re-open
but,It is normal to open Joplin from AppStore

**Comment by JiangAshao** [comment]
It is normal to open Joplin from AppStore

**Comment by laurent22** [comment]
Could you provide a crash log please? https://joplinapp.org/debugging
