### ISSUE TITLE
problem rendering powershell code snippets

### ISSUE THREAD

**Issue by isdnfan** [laurent22/joplin#4354]
Notes including PowerShell commands render wrong, leading dollar sign is skipped and multiple lines are displayed as one line

## Environment
Platform:  Windows 10

Joplin 1.6.6 (prod, win32)

Client ID: efcf8f3e8e844c429af2bc335b89389f
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f58b7563e (master)

## Steps to reproduce

1. create a note with this text:

```
wrong powershell rendering

$SysInfo = Get-WmiObject -Class Win32_ComputerSystem
$ComputerFqdn = “{0}.{1}” -f $sysinfo.Name, $sysinfo.Domain

```
2. you will see the dollar sign in front of $SysInfo is skipped and the second line is added without line break to the first on ($ sign in front of ComputerFqdn skipped again). Screenshot show Joplin window and external editor with the plain text.

![image](https://user-images.githubusercontent.com/18125597/104456702-59d69080-55a9-11eb-91db-deef2229aafb.png)

## Describe what you expected to happen
code should be shown "as is"

**Comment by Daeraxa** [comment]
Surrounding text in $ is causing the "math expressions" plugin to activate. Either turn it off in options > Markdown or mark your code as code (backticks or 4 spaces)

**Comment by isdnfan** [comment]
@Daeraxa 
> Surrounding text in $ is causing the "math expressions" plugin to activate.

thank you for the hint regarding the math expressions. Looks like disabling math expressions solves the issue for me - but I think it's worth to think about generic solution. In my eyes the program should never accept an output if the parser fails. not only for this specific situation but for every other parser. I agree everything works well once the user format the notes in the right way, but good software is expected to help. same for #4355

**Comment by Daeraxa** [comment]
Isn't the failed parsing in a different issue? In this one it looks like it is behaving as intended with that plugin enabled

**Comment by laurent22** [comment]
>  In my eyes the program should never accept an output if the parser fails. not only for this specific situation but for every other parser.

The parser did not fail - it's your input that was invalid and the parser correctly displayed an error. You need to remember that the note content is Markdown, and things don't work if you input invalid Markdown. It's the same if you create an invalid HTML file and open it in the browser - you'll get broken content.

**Comment by isdnfan** [comment]
@Daeraxa  @laurent22 : yes it's true I mixed both issues, my statement is still true for #4355 where the parser definitely failed and throw an error. I'm sorry for confusion. But the root cause is the same: dollar sign always triggers math extension which is unexpected. 

> You need to remember that the note content is Markdown,
 dollar sign is not a special character in markdown, at least without math extension [basic-syntax](https://www.markdownguide.org/basic-syntax)

> if you input invalid Markdown
the markdown syntax is not wrong - the parser just gets a wrong portion of the file

I don't find a **comprehensive** description how KATEX must be formatted but at least [markdown-it-katex](https://www.npmjs.com/package/markdown-it-katex) you can see that single dollar is designed for **single-line** rendering and should not apply in my scenario where the two dollar characters are on different lines.

> Anything between two $ characters will be treated as TeX math. The opening $ must have a non-space 
> character immediately to its right, while the closing $ must have a non-space character immediately to its left,

I'm not sure if new-line is a **non-space** character and again it's definitely not **single-line**.

I don't understand the code but for me it looks like the problem is in the file [useJoplinMode.ts](https://github.com/laurent22/joplin/blob/17d835d694cf8afd459443f1ba279d8a9100eae5/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts) where opening and closing tags a defined separately.

```
		const inlineKatexOpenRE = /(?<!\S)\$(?=[^\s$].*?[^\\\s$]\$(?!\S))/;
		const inlineKatexCloseRE = /(?<![\\\s$])\$(?!\S)/;
		const blockKatexOpenRE = /(?<!\S)\$\$/;
		const blockKatexCloseRE = /(?<![\\\s])\$\$/;
```
this way the parser randomly picks up ´$´ from the text even on different line which don't belong together. I think the regex to find single-line KATEX should look like this:  
- opening dollar char, followed by non-space
- content (not greedy, no new line)
- closing dollar char, preceded by non-space
same applies to multi-line variant with ´$$´ just with the difference the content must accept multi-line. unfortunately the KATEX [markdown-it-katex](https://www.npmjs.com/package/markdown-it-katex) doesn't state anything about what is expected/required before opening and after closing dollar character - for me at least one white-space makes sense. 
For me this regex ´(?<!\S)\$(?=[^\s])(.*?)(?<!\s)\$(?!\S)´ works quite good (KATEX is in the capture group 1) . It matches only only a single line, maybe you can take a look if this improves parsing of math markdown.
