### ISSUE TITLE
Ubuntu AppIndicator (AKA Tray Icon)

### ISSUE THREAD

**Issue by elsiehupp** [laurent22/joplin#4362]
I'm copying this over from [the Discourse](https://discourse.joplinapp.org/t/ubuntu-appindicator-aka-tray-icon/13904) because I didn't realize that bug reports had moved to GitHub.

I recently discovered that I actually have a third-party Snap installation of Joplin installed on my system. In addition to the basics of Snap packaging, there seems to be one single difference between the Snap version and the official version, namely changes to `joplin.desktop` that allow Joplin to properly display its AppIndicator (AKA "tray icon") on Ubuntu. You can view the changes here:

https://github.com/MrCarroll/joplin-snap/commit/428d39046ba3e49076a6b1fb9a50a8262914f309

This specifically fixes the bug referenced in the Joplin code here:

https://github.com/laurent22/joplin/blob/fca8f71f4a1077feca26fed2b5aff00ad153e360/packages/lib/models/Setting.ts#L669

The link in the code suggests there's a fix:

http://www.webupd8.org/2017/04/fix-appindicator-not-working-for.html

I did some further digging online, and `StartupWMClass=Joplin` and `XDG_CURRENT_DESKTOP=Unity` appear to be two known workarounds for the AppIndicator not working in Ubuntu.

1. https://github.com/pop-os/pop/issues/84
2. https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/74

The main reason I discovered that Joplin's official distribution doesn't support the AppIndicator is that the AppIndicator for the Snap version is full-color, standing out from and kind of clashing with the monochrome AppIndicator icons adjacent to it:

![Linux tray](https://user-images.githubusercontent.com/9206310/104640953-26face00-5677-11eb-87a7-3e2bff75fbb4.png)

I guess my questions are as follows:

1. Could the AppIndicator fix from the Snap be integrated into the official Joplin distribution?
2. Could the AppIndicator icon on Linux (or at least Ubuntu, idk about other distros) be changed to use the same resource as the Menu Bar icon on macOS?

![Mac tray](https://user-images.githubusercontent.com/9206310/104640904-19454880-5677-11eb-8aa8-9bb16530f4d5.png)

Note: this function appears to be where it happens:

https://github.com/laurent22/joplin/blob/28f75449d70db1c92c0056459d50abcc713cfda4/packages/app-desktop/ElectronAppWrapper.ts#L267-L279

And,

3. Though this is kind of off-topic, would it feasible or realistic for Joplin to have an official Snap and/or Flatpak/Flathub distribution? (Having both would be ideal because different Linux distros have different preferred "app stores"; Ubuntu, for example only ships with Snap, and Flathub must be added manually.) I see this was requested in #738.

FWIW the Menu Bar icon also seems slightly out of scale with its neighbors on Big Sur, though this problem also affects Nextcloud Desktop:

https://github.com/nextcloud/desktop/issues/2584

(If you figure out the icon scaling issue, I might suggest the same fix over at Nextcloud.)

Thanks!

**Comment by elsiehupp** [comment]
This has not, to my knowledge, been fixed. (The conversation continued on the [Discourse](https://discourse.joplinapp.org/t/ubuntu-appindicator-aka-tray-icon/13904).)

**Comment by casasfernando** [comment]
I'm really interested on this as well.
I'm running the Linux AppImage on ElementaryOS 5.1.7 (Hera) and the tray icon works fine but it really looks out of place. Switching to a monochrome icon like in macOS is a great idea.

This is how it looks at the moment when an application is maximized and the panel has a black background:

file:///home/fernando/Pictures/Screenshots/Screenshot%20from%202021-03-02%2023.22.11.png

And other examples when no application is maximized and the panel backgrounds change according to the desktop background image (it becomes transparent or semi-transparent):

file:///home/fernando/Pictures/Screenshots/Screenshot%20from%202021-03-02%2023.24.12.png

file:///home/fernando/Pictures/Screenshots/Screenshot%20from%202021-03-02%2023.24.52.png

file:///home/fernando/Pictures/Screenshots/Screenshot%20from%202021-03-02%2023.26.35.png

Thanks.

**Comment by elsiehupp** [comment]
@casasfernando FYI there was significantly more discussion in [the Discourse thread](https://discourse.joplinapp.org/t/ubuntu-appindicator-aka-tray-icon/13904).

**Comment by casasfernando** [comment]
> @casasfernando FYI there was significantly more discussion in [the Discourse thread](https://discourse.joplinapp.org/t/ubuntu-appindicator-aka-tray-icon/13904).

Yup. I read the whole thread there. Just wanted to show my support for the tray icon change in favor of:

2. Could the AppIndicator icon on Linux (or at least Ubuntu, idk about other distros) be changed to use the same resource as the Menu Bar icon on macOS?

I really liked these two tray icon designs:

![image](https://user-images.githubusercontent.com/15861819/109725837-05678e80-7bb2-11eb-9b56-0b72dd212356.png)

**Comment by elsiehupp** [comment]
I've just been a bit absent from both the Discourse and the GitHub 😬, but I can create a draft pull request incorporating the changes discussed in the other thread.

**Comment by elsiehupp** [comment]
I'm unsubscribing from this thread, because it isn't worth my time to deal with this maintainer's toxicity.
