### ISSUE TITLE
Some strings aren't translated

### ISSUE THREAD

**Issue by Elaborendum** [laurent22/joplin#4363]
A lot of strings remain in english in other languages despite most having equivalents in their respective .po files. Examples:
![image](https://user-images.githubusercontent.com/71190696/104643488-81e1f480-567a-11eb-8635-bbd06e63a5a3.png)
![image](https://user-images.githubusercontent.com/71190696/104643502-860e1200-567a-11eb-95cb-d49f0aedea25.png)
![image](https://user-images.githubusercontent.com/71190696/104643517-8ad2c600-567a-11eb-9be5-fd33662aaf29.png)
![image](https://user-images.githubusercontent.com/71190696/104643751-d84f3300-567a-11eb-8174-1e785812e2e2.png)
![image](https://user-images.githubusercontent.com/71190696/104643757-db4a2380-567a-11eb-947b-5d5626a6d14a.png)
![image](https://user-images.githubusercontent.com/71190696/104652285-e440f200-5686-11eb-8b26-ebb7bcc715d1.png)

Of these images, only the last 3 aren't in the .po files if I recall correctly.

I've seen an issue about Goto Anything, #3727, but I guess it can just be the name of the feature. Regardless, its in the .po files.

## Environment

Joplin version: 1.67
Platform: Windows, Android
OS specifics: Windows 10, Android 10

## Steps to reproduce

1. Change language from English to any other.
2. Look for some of the examples. 

## Describe what you expected to happen
The strings would be translated according to the .po file.

**Comment by ProgramFan** [comment]
"Goto Anything..." and "Command Palette" are still not translated in the 1.7.4 pre-release. Both of these strings are in the po file and they are translated as in zh_CN.po. How can we fix this?

**Comment by ProgramFan** [comment]
The problematic code seems https://github.com/laurent22/joplin/blob/86610e756126a388f6b3394130f9d3553a98bdf7/packages/app-desktop/plugins/GotoAnything.tsx#L562 and https://github.com/laurent22/joplin/blob/86610e756126a388f6b3394130f9d3553a98bdf7/packages/app-desktop/plugins/GotoAnything.tsx#L569. Maybe they shall be changed to `() => _('XXX')` as in the fix  https://github.com/laurent22/joplin/commit/716a92944d8c915ab2a44ff289a5d8e4e51e6012 ?

**Comment by ProgramFan** [comment]
@laurent22

**Comment by ProgramFan** [comment]
Another request on this issue: the "Click to add tags..." button in the editor is localizable. Can it be fixed?

**Comment by laurent22** [comment]
The Goto Anything issue can't be fixed without some refactoring, however I've made the Click To Add button localisable now.
