### ISSUE TITLE
.desktop file isn't installed with the application when installing the Linux desktop app on Chrome OS / Crostini

### ISSUE THREAD

**Issue by Ratitack** [laurent22/joplin#4364]
When using the linux desktop installation script on Chrome OS, the application installs, but the .desktop file does not. I think this is because [this if statement](https://github.com/laurent22/joplin/blob/413ec1a93341b3b6a4babd3f03408bd664088a2c/Joplin_install_and_update.sh#L165) doesn't execute because $XDG_CURRENT_DESKTOP is empty on Chrome OS.

## Environment

Joplin version: 1.6.7
Platform: Linux
OS specifics: Chrome OS

## Steps to reproduce

1.  open a Linux terminal on Chrome OS
2.  Execute `wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash
`
3.  Be sad

## Describe what you expected to happen

If the desktop file was installed, the application would be added to the Linux apps folder to execute like any other installed linux application on the platform

**Comment by CalebJohn** [comment]
Can you confirm that desktop files can be installed to `.local/share/applications` under Chrome OS? I'm not familiar with it.

**Comment by Ratitack** [comment]
Yep, I can confirm that desktop files can be installed to that directory. I
manually wrote the .desktop file from the install script to that directory
and it worked. Linux on Chrome OS is pretty much just Linux in a container.
I had an issue with the icon part of the script, I had to change it to
reference the full path, but that might be a Chrome OS issue...

**Comment by bierbo** [comment]
I can confirm this problem. The problem is probably less writing to the directory than reading the environment variable.
Screenfetch gives me this:
![Screenshot 2021-01-15 at 23 22 11](https://user-images.githubusercontent.com/800307/104784466-a1ffd980-5788-11eb-961f-466f684430cd.png)
Maybe a good solution would be to check if the variable $SOMMELIER_VERSION exists.
Sommelier is the wayland implementation integrated in ChromeOS. But I am really not sure which ChromiumOS Version introduced Sommelier.
[Sommelier at Google](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/vm_tools/sommelier/)

![Screenshot 2021-01-15 at 23 23 54](https://user-images.githubusercontent.com/800307/104784705-27838980-5789-11eb-84bb-4ea15a77a64a.png)

**Comment by CalebJohn** [comment]
@Ratitack @bierbo can either of you confirm that the `.local/share/applications` exists in your environment? It's probably sufficient to check for that directory rather than checking the desktop environment.

**Comment by bierbo** [comment]
Directory _~/.local/share/applications_ did not exist on my system.

Executing lines 171 and 172 of current install skript manually in shell worked for me.

`mkdir -p ~/.local/share/applications
echo -e "[Desktop Entry]\nEncoding=UTF-8\nName=Joplin\nComment=Joplin for Desktop\nExec=${HOME}/.joplin/Joplin.AppImage\nIcon=joplin\nStartupWMClass=Joplin\nType=Application\nCategories=Office;" >> ~/.local/share/applications/appimagekit-joplin.desktop`

The program link is after executing this two lines in the app list and starts the application properly.
![Screenshot 2021-01-19 at 17 04 10](https://user-images.githubusercontent.com/800307/105060243-71fe5200-5a78-11eb-953a-41196c468543.png)
.

**Comment by CalebJohn** [comment]
@bierbo Does `/use/share/applications` exist?

**Comment by bierbo** [comment]
Yes, this directory actually exists.

**Comment by CalebJohn** [comment]
@bierbo Sorry to ask, but do you mind running the following command in a terminal?
```
type update-desktop-database
```
and
```
echo $XDG_DATA_DIRS
```

I'm just trying to understand what the limitations of ChromeOS are.
Thanks.

**Comment by bierbo** [comment]
I am glad to help.
Output is:
```
lukasbischof@penguin:~$ type update-desktop-database
update-desktop-database is /usr/bin/update-desktop-database
```
(Running `update-desktop-database` just gives no output)
and
```
lukasbischof@penguin:~$ echo $XDG_DATA_DIRS
/home/lukasbischof/.local/share:/home/lukasbischof/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share

```

**Comment by CalebJohn** [comment]
@bierbo Thanks for that, it confirms what I was hoping for. I think it will be possible to check for the existence of that command (update-desktop-database) instead of checking the desktop environment. When I have some time I'll write it up and I hope you'll be willing to test!

**Comment by bierbo** [comment]
Sounds great. Of course I could test it!

**Comment by CalebJohn** [comment]
@bierbo I've made the promised update! If you could please test and confirm that it works I'll make PR and hopefully get this fixed for everyone!
```
wget -O - https://raw.githubusercontent.com/CalebJohn/joplin/linux-update/Joplin_install_and_update.sh | bash
```

By the way, you might be on the latest version  (which means the update script won't run). Just delete the version file from `~/.joplin` to allow the script to re-run itself.

**Comment by bierbo** [comment]
I have tried it, it works on my machine. Before starting the install skript, I have deleted the folder `~/.joplin` and the folder `~/.local/share/applications`.
The installation has been completed successfully, the desktop icon has been created and a click on it starts the application.
