### ISSUE TITLE
Using uslug (emoji-support) in the toc plugin did not get the emoji name

### ISSUE THREAD

**Issue by cqroot** [laurent22/joplin#4371]
I tried the toc plugin and continued to develop based on it. But I found that using uslug (emoji-support) in the toc plugin did not get the emoji name.

**Comment by laurent22** [comment]
uslug doesn't support emojis properly, so I use my own fork for it: https://github.com/laurent22/joplin/blob/eb3493f648b85986ec3d5834aea766e72cbc7efa/packages/lib/package.json#L77

You might want to give it a try as I think it would work as you expect.

**Comment by cqroot** [comment]
Yes, when I create an empty nodejs project for testing, "git+https://github.com/laurent22/uslug.git#emoji-support" supports emoji. But it still does not get the emoji name correctly in the toc plugin.

I tested it, no matter the toc plugin I built or the toc plugin downloaded from 'https://github.com/laurent22/joplin/blob/dev/packages/app-cli/tests/support/plugins/toc/org.joplinapp.plugins.TocDemo.jpl', the title with emoji could not be redirected correctly.

**Comment by laurent22** [comment]
Since Joplin uses that same package, could you give an example note and how you expect the emoji to be converted?
