### ISSUE TITLE
enex import creates some "Todo" notes instead of only regular notes

### ISSUE THREAD

**Issue by jb261** [laurent22/joplin#4374]
When importing Evernote enex files, some of the notes are created as Todos in Joplin rather than as regular notes.

Per @laurent22's post [in this thread](https://discourse.joplinapp.org/t/switch-evernote-imported-to-do-notes-to-non-to-do-notes-overrides-the-last-modification-time/1496/9), my expectation is that all notes imported via enex should be imported into Joplin as regular notes, *not* as Todos, so this seems like a bug that is not yet fully squashed.

## Environment

Joplin version:  Joplin 1.6.7 (prod, win32)
Platform: Windows 10
OS specifics: Win 10 Pro v1909

## Steps to reproduce

1. Import following enex file as markdown: [nextcloud file link](https://nd.nl.tab.digital/s/Y7R2j7ZaobNNx2i)
2. observe two notes imported - both are imported as Todos, one marked completed, the other incomplete

## Describe what you expected to happen

I expected both notes to be imported as regular notes, not as Todo notes.

**Comment by laurent22** [comment]
The notes both have a "reminder-order" and "reminder-time", which in Joplin is imported as a to-do, so it's working as expected. You can always change the notes by rigth-clicking on them and selecting "Toggle between to-do and note"
