### ISSUE TITLE
Redo destroys note

### ISSUE THREAD

**Issue by LivingInABox** [laurent22/joplin#4378]
## Environment

Joplin version: 1.4.19
Platform: Windows
OS specifics:

I was using the richtext editor and copied a part to an other section. The part was pasted to the top.

I tried to redo this using Strg + Z. The option is not in the menu. However since I use it in other programms I tried it and it deleted my data.

**Comment by laurent22** [comment]
> Strg + Z

Did you mean Ctrl?

**Comment by LivingInABox** [comment]
Sorry, Strg is German. Crtl ist he same key on an english keyboard layout. -> Yes I used Ctrl + Z

 

Von: Laurent <notifications@github.com> 
Gesendet: Sonntag, 17. Januar 2021 12:54
An: laurent22/joplin <joplin@noreply.github.com>
Cc: LivingInABox <dirkbauer@posteo.de>; Author <author@noreply.github.com>
Betreff: Re: [laurent22/joplin] Redo destroys note (#4378)

 

Strg + Z

Did you mean Ctrl?

**Comment by laurent22** [comment]
Hmm, but ctrl+z is mapped to "undo", not "redo", so it's expected that whatever text you've pasted would be removed. It's not clear to me there's a bug here.

**Comment by LivingInABox** [comment]
Yes, you are right, I mean undo. I have been trying to reproduce this for a longer time. But I am sure that I pressed Ctrl + Z until nothing changed and the previously selected paragraph was gone. 

 

Possibly I really made a stupid mistake. Sorry. Please delete the bug report. As soon as I have the exact steps I will write again.

 

Von: Laurent <notifications@github.com> 
Gesendet: Sonntag, 17. Januar 2021 13:05
An: laurent22/joplin <joplin@noreply.github.com>
Cc: LivingInABox <dirkbauer@posteo.de>; Author <author@noreply.github.com>
Betreff: Re: [laurent22/joplin] Redo destroys note (#4378)

 

Hmm, but ctrl+z is mapped to "undo", not "redo", so it's expected that whatever text you've pasted would be removed. It's not clear to me there's a bug here.

**Comment by laurent22** [comment]
Also you're on an old version of the app, so you might want to try the latest version. Some fixes had been introduce regarding undo and that might have been after the version you have.

**Comment by LivingInABox** [comment]
Yes I will download the latest version. Sorry for the bug report before being able to reproduce. I have donatet 50 Euro for joplin development to compensate. 
    	
    	Holen Sie sich Outlook für iOS
    
  
 Von: Laurent <notifications@github.com>Gesendet: Sonntag, Januar 17, 2021 5:50 PMAn: laurent22/joplinCc: LivingInABox; AuthorBetreff: Re: [laurent22/joplin] Redo destroys note (#4378) 
Also you're on an old version of the app, so you might want to try the latest version. Some fixes had been introduce regarding undo and that might have been after the version you have.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/laurent22/joplin/issues/4378#issuecomment-761842568",
"url": "https://github.com/laurent22/joplin/issues/4378#issuecomment-761842568",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by laurent22** [comment]
Thank you for your support! Much appreciated!
