### ISSUE TITLE
Couldn't use backspace in command mode.

### ISSUE THREAD

**Issue by JiagengDing** [laurent22/joplin#4384]
## Environment

Joplin version: Joplin 1.6.3
Platform: terminal Joplin in macOS
macOS 11.2

**Comment by laurent22** [comment]
Yes I just can't figure out why it happens and I can't replicate it in dev mode, which makes it very hard to fix. For now, you can use <kbd>Ctrl</kbd>+<kbd>H</kbd>

**Comment by tessus** [comment]
This is a weird one. e.g. backspace works when ssh'ing to my Linux server and running joplin there. When I run Joplin cli on my macOS, I have a problem with backspace.

I think it's a combination of the terminal (esc seq sent by backspace) and the new terminal kit module.

**Comment by JIagengDing** [comment]
Thanks to Joplin for providing a lot of help for my study. 

Thank you for your reply too, but I couldn't delete a char with Ctrl+h in command mode. When I press it, Joplin will go back to normal mode. Should I configure it?

**Comment by v1sion** [comment]
> Yes I just can't figure out why it happens and I can't replicate it in dev mode, which makes it very hard to fix. For now, you can use Ctrl+H

Thank you , Cmd+h works, but the backspace does not

**Comment by amcooper** [comment]
I was able to get this working by checking out this: https://stackoverflow.com/questions/13017392/how-to-make-iterm2-send-control-h-for-backspace-so-it-works-for-all-linux-shells#13017432 —The comment under the answer works for iTerm2. The question contains a fix for macOS Terminal (which I did not try).

**Comment by JIagengDing** [comment]
> I was able to get this working by checking out this: https://stackoverflow.com/questions/13017392/how-to-make-iterm2-send-control-h-for-backspace-so-it-works-for-all-linux-shells#13017432 —The comment under the answer works for iTerm2. The question contains a fix for macOS Terminal (which I did not try).

Thank you, backspace could work in command mode after I change this.

`iTerm2 -> Preference -> keys -> key bindings -> add -> press backspace -> select 'Send ^H Backspace`

**Comment by tessus** [comment]
Still not sure why this happened "all of a sudden". It has worked for me for a long time. Then at one point, it didn't. This is why I think it has something to do with terminal-kit. Upstream issue?

Let's leave this open for now.

**Comment by laurent22** [comment]
> Still not sure why this happened "all of a sudden". It has worked for me for a long time. Then at one point, it didn't. This is why I think it has something to do with terminal-kit. Upstream issue?

I don't get it either as we aren't changing the CLI app much, so indeed it could be some lib that changed under us, or maybe Node that works differently. It would surprise me if it was a change in terminal-kit as we're on such an old version of it, it's unlikely it would have received an update. We're on 1.13.11, and it could have been automatically updated to 1.13.13, but that's still a 4 years old version so we've probably been using it for a while.

In fact, maybe it's a matter of upgrading terminal-kit to the latest version, as it could come with a fix for this issue.

**Comment by jottr** [comment]
> > I was able to get this working by checking out this: https://stackoverflow.com/questions/13017392/how-to-make-iterm2-send-control-h-for-backspace-so-it-works-for-all-linux-shells#13017432 —The comment under the answer works for iTerm2. The question contains a fix for macOS Terminal (which I did not try).
> 
> Thank you, backspace could work in command mode after I change this.
> 
> `iTerm2 -> Preference -> keys -> key bindings -> add -> press backspace -> select 'Send ^H Backspace`

For me, this breaks backspace completely. `iTerm 3.4.4`

**Comment by matthewblott** [comment]
I just fixed this for the macOS default terminal. Add the last entry below on the Keyboard tab of your Profile. It was driving me nuts!

![Screenshot 2022-09-15 at 11 24 01](https://user-images.githubusercontent.com/1231417/190380497-53a8049c-f328-4b77-92cf-b046e971be75.jpg)
