### ISSUE TITLE
Installing Joplin on Manjaro takes > 8 hours

### ISSUE THREAD

**Issue by LSchueler** [laurent22/joplin#4388]
Hi!

I want to install Joplin, but as I got from issue #4234, Github seems to throttle the bandwidth down to basically zero.
Is there any other way to install Joplin without having to wait for many hours? Using the Manjaro software repo does not help, as it gets built there too from source.

## Environment

Joplin version: 1.6.7
Platform: Linux
OS specifics: Manjaro

## Steps to reproduce

1. paste `wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash` into terminal
2. execute
3. wait

**Comment by laurent22** [comment]
That's a GitHub issue.

**Comment by JackGruber** [comment]
Use a other ISP or a VPN connection. I have the same problem with GitHub AWS S3 backend.

**Comment by LSchueler** [comment]
> Use a other ISP or a VPN connection. I have the same problem with GitHub AWS S3 backend.

Thanks! Using a VPN helped.

**Comment by LSchueler** [comment]
> That's a GitHub issue.

Joplin is the only repository where I've experienced theses issues.

**Comment by JackGruber** [comment]
I have this on every GitHub doownload :(

**Comment by laurent22** [comment]
> Joplin is the only repository where I've experienced theses issues.

Regardless we don't host the files so if it's slow there's nothing we can do. If you search online, you'll find it happens to many people with many repositories. It's just something weird about GitHub CDN.

**Comment by LSchueler** [comment]
> I have this on every GitHub doownload :(

Wow, that sounds terrible! - My first reaction to your suggestion "use a other ISP" was more like "Joplin is great, but changing my ISP is a pretty big step", but I get your point now. I hope this is not getting too much off topic, but maybe you could have a look into this [Firefox plugin](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/) if it is a problem with CDN redirections?

> Regardless we don't host the files so if it's slow there's nothing we can do. If you search online, you'll find it happens to many people with many repositories. It's just something weird about GitHub CDN.

I guess my searches for solutions where too Joplin specific.

Anyway, thank you so much for Joplin, I think it's great!
