### ISSUE TITLE
"Ctrl+Shift+V" pastes content twice

### ISSUE THREAD

**Issue by hhermas** [laurent22/joplin#4391]
"Ctrl + Shift + V” is commonly used to paste plain, non-formatted text.
In Joplin, it pastes the copied content twice.

## Environment
Joplin 1.4.19 (prod, win32)

Sync Version: 2
Profile Version: 34
Keychain Supported: Yes
Revision: de123ee58 (master)
Windows 10 Pro

## Steps to reproduce

1. Copy text
2. "Ctrl+Shift+V" to paste into a Joplin note.
3. Text pasted twice.

**Comment by CalebJohn** [comment]
Hi @hhermas 

I think this has been fixed already. The latest version of Joplin is v1.6.7. Please update and let me know if the issue continues

**Comment by hhermas** [comment]
No reproducible in latest version. Thanks!
