### ISSUE TITLE
Plugin Search Box Greyed Out/Unsearchable - 1.7.3

### ISSUE THREAD

**Issue by joshcsullivan** [laurent22/joplin#4394]
## Environment

Joplin version: 1.7.3
Platform: Windows
OS specifics: Win 10 2004

## Steps to reproduce

1. Open Joplin 1.7.3
2. Open Plugins tab within Options
3. Attempt to search, and cannot click inside the search box, or on the magnifying glass to begin typing.

## Describe what you expected to happen

Click into the search box and start typing.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/5843181/log.txt)

**Comment by JackGruber** [comment]
can confirm the same problem on the pre release 1.7.3
![grafik](https://user-images.githubusercontent.com/24863925/105206361-932d7400-5b46-11eb-9f92-01c836880bfa.png)

**Comment by laurent22** [comment]
Just some problem with the repo itself, which is now fixed.
