### ISSUE TITLE
Plugin Search shows no results on Linux

### ISSUE THREAD

**Issue by Shamp0o** [laurent22/joplin#4395]
## Description
The plugin search seems to be broken on Linux Manjaro and possibly other distributions. Entering a search query yields no results. An uncaught error is reported when doing the search (cf. Logfile below).
The search is working fine on Windows 10 using the same version of Joplin. 

## Environment

Joplin version: 1.6.7
Platform: Linux
OS specifics: Manjaro

## Steps to reproduce

1. Install Joplin 1.6.7 on Manjaro via the wget command
2. Go to Tools > Options > Plugins
3. Search for a plugin that's in the repository
4. No search results are shown

## Expected behavior
Search results are shown.

## Logfile
[-1611158813364.log](https://github.com/laurent22/joplin/files/5843691/-1611158813364.log)

**Comment by laurent22** [comment]
Closed as duplicate
