### ISSUE TITLE
joplinapp.org Desktop App download links point to old release binaries

### ISSUE THREAD

**Issue by hmhackmaster** [laurent22/joplin#4404]
### Issue summary

The JoplinApp.org web site links to outdated downloads of the Desktop Apps (and the APKs of the Android app as well).

### Details

The portable link can be replaced with a direct link to the latest release file (`https://github.com/laurent22/joplin/releases/latest/download/JoplinPortable.exe`) but since the the other binaries include the version number in the filename (`Joplin-Setup-1.6.8.exe`) the GitHub method of direct linking to the latest release* won't work (since `/latest/download/Joplin-Setup-1.6.8.exe` won't always be the latest binary).
*: https://docs.github.com/en/github/administering-a-repository/linking-to-releases

I know the latest release was yesterday so a lag time is certainly to be expected but I spent quite a few minutes trying to figure out why a plugin didn't seem be working (not yet familiar with the UI, I assumed I was just missing where it was) but an eventual check of the logs revealed that the plugin was refusing to load as my install was out of date (after being installed only for half an hour):
```
Error: Plugin "outline" was disabled because it requires Joplin version 1.6.7 and current version is 1.6.6.
```

@laurent22, at your incredibly rapid release rate I certainly imagine having to update yet another file is tedious but sadly I don't see another *good* way around it other than changing your binary names (and I personally love binary names that include versions) or just linking to the releases page and letting the user locate the file (certainly not the best user experience).

**Comment by Daeraxa** [comment]
I came across this before when I was updating the documentation. There is a release script that runs to update the readme (and therefore website). I guess the script wasn't run for the last release or it failed.

**Comment by hmhackmaster** [comment]
@Daeraxa Ah, that makes sense. I see that [update-readme-download.js](https://github.com/laurent22/joplin/blob/dev/packages/tools/update-readme-download.js) does that particular bit of work. 
I guess it will have to be rerun or manually updated at some point.

Thanks for the insight into that!

**Comment by hmhackmaster** [comment]
It looks like the website's download links got correctly updated for the 1.7.11 release which occurred after this issue was created, so this issue can be closed.
