### ISSUE TITLE
Syncs, no errors, but no notes.

### ISSUE THREAD

**Issue by caibbor** [laurent22/joplin#4408]
I'm on Android 11 using the latest Joplin app version as of last night on a Pixel 4a. I also have Joplin installed on several other devices, albeit with no problem (Linux computers and a Pixel 1). This is the first time I've had problems with Joplin. I've cleared the app cache and storage, reinstalled it, reconnected it several times, and still it just syncs my thousands of items and then brazenly declares that it has finished with no error whatsoever in the log, yet no notes. Zarro noots. And when I let it finish, and close and reopen joplin, it re-fetches all the thousands of items all over again to no avail.

This feels like a write permission problem to me, I believe the sync is happening but that no notes are actually being written once they're transferred.

Someone else had this problem about 7 months ago, but then one of the bug tracker folks came along and said there's no problem and closed the issue. *shrug* there's definitely still an issue. That link is here: https://github.com/laurent22/joplin/issues/1627

Ont other person had the issue (presumably a different person) but meandered off before anyone could help them: https://discourse.joplinapp.org/t/sync-but-no-notes-visible/2372/3

I use Dropbox to sync.
I had been using Joplin without encryption during all of this (didn't need it). I turned on encryption last night, let it run it's course through the night, and finished successfully. After then reinstalling a brand-spakin' new Joplin app on my Pixel 4a, I once again let it sync, still resulting in no notes, but also notices that it didn't say a stinkin' think about decrypting. I double checked that I was connected to the same dropbox account on both devices - and I am. For certain.

Linux desktop's ~/.config/joplin/database.sqlite is 3.4mb (the log.txt is 18mb, woah, it goes all the way back to March of 2020 when I first started using Joplin...)
joplin folder in Dropbox is 16mb.

I wanted to check the size of the joplin folder on my Pixel 4a, but I don't understand how Google has further obfuscated the directory structure here, and I can't go outside of them without getting permission errors (ie, with a terminal or file browser). I'll be 
rooting my phone soon so that I can at least see wtf is on it.

Database v34
FTS enabled: 1

Android 11, Jan 5, 2021 security update, Jan 1 2021 Play system update. Build RQ1D.210105.003
kernel4.19...

## Environment

Joplin version: 1.6.7
Platform: Android
OS specifics: Android 11

## Steps to reproduce

1. I wish
2. I knew
3. 

## Describe what you expected to happen

To see notes.

## Logfile

Can't provide a log, the app doesn't allow me to copy the log text and I can't browse to the file without rooting my phone. I can provide screenshots but there are no discernible errors regarding syncing.

**Comment by roman-r-m** [comment]
> I wanted to check the size of the joplin folder on my Pixel 4a

You can use "export profile" function for this. It should also help with getting the sync log.

Are there any errors in the system log? You can get it via `adb logcat` from your PC and there were some apps for this in the Play Store as well.

**Comment by caibbor** [comment]
first I've used adb, the log floods up quite good even with some filters. so I did ./adb logcat  | egrep '( E |oplin)'

output is here. 
https://pastebin.com/sbt74YRh

the lines I notice immediately as interesting are below (not necessarily consecutive output, I just grepped for them)

`01-25 23:26:47.023 24162 24162 D SoLoader: libjscexecutor.so not found on /data/user/11/net.cozic.joplin/lib-main
01-25 23:26:47.023 24162 24162 D SoLoader: libjscexecutor.so found on /data/app/XXXXX/net.cozic.joplin-No_RotpiG3piYiG1qe1VWw==/lib/arm64

01-25 23:26:47.048 24162 24186 D SoLoader: libreactnativejni.so not found on /data/user/11/net.cozic.joplin/lib-main
01-25 23:26:47.049 24162 24186 D SoLoader: libreactnativejni.so found on /data/app/XXXXX/net.cozic.joplin-No_RotpiG3piYiG1qe1VWw==/lib/arm64

01-25 23:26:47.052 24162 24186 D SoLoader: libfbjni.so not found on /data/user/11/net.cozic.joplin/lib-main
01-25 23:26:47.053 24162 24186 D SoLoader: libfbjni.so found on /data/app/XXXXX/net.cozic.joplin-No_RotpiG3piYiG1qe1VWw==/lib/arm64
`

That strings that looked like Base64 encoded strings, I wasn't sure if that might be sensitive data so I replaced them with XXXX

**Comment by caibbor** [comment]
Or perhaps this:

`01-25 23:26:47.577   585   585 E Layer   : [Surface(name=Task=1)/@0x9404eae - animation-leash#0] No local sync point found`

**Comment by roman-r-m** [comment]
I think these all are false alerts. Well, not false but unrelated to the issue.
If you still have the original log, can you try filtering by the PID `24162` or `ReactNativeJS` instead as in
```
01-25 23:26:48.148 24162 24188 I ReactNativeJS: Running "Joplin" with {"rootTag":1}
```
Plus check for any lines with `Exception` as well.

**Comment by caibbor** [comment]
Sorry it took so long. Been working.

I still apparently have the original log, this is what I got after grepping for that PID:

https://pastebin.com/FZVnRikc

**Comment by roman-r-m** [comment]
No errors there, are you sure there are no more lines for this PID or with `ReactNativeJS`?
