### ISSUE TITLE
Wrong count in tags

### ISSUE THREAD

**Issue by dot-clear** [laurent22/joplin#4411]
A to-do task completed in a notebook, it’s not counted when it is not show (as expected).
A to-do task completed in a tag, it’s counted  when it is not show (that make confusion)

## Environment

Joplin version:  Joplin 1.6.8
Platform:  Win10
OS specifics: no

## Steps to reproduce

1. Ctrl + T, to create the task and add a tag
2. Count the number of notes/tasks in your selected tag and check the task box
3. Be sure the option “show completed to-dos” is unchecked (View menu)
4. Count the number of notes/tasks in your selected tag

![Tag count](https://user-images.githubusercontent.com/77929203/105636244-6be4e880-5e5f-11eb-8f63-8707153861b0.png)

## Describe what you expected to happen
Not count not showed tasks

**Comment by dot-clear** [comment]
Yes the issue still requires the community's attention.

**Comment by HOLLYwyh** [comment]
emmm. In my Joplin 1.7.11 win10 , I meet the same problem. I'm trying to solve it

**Comment by dot-clear** [comment]
Thank you @JackGruber !
