### ISSUE TITLE
Problem entering hyphens on iOS

### ISSUE THREAD

**Issue by bradleysmith** [laurent22/joplin#4413]
## Environment

Joplin version: 10.6.3
Platform: ipadOS
OS specifics: 14.3

## Steps to reproduce

1. Create new notebook 
2. Create a new note
3. Start typing hyphens. First hyphen appears, second press of hyphen key does nothing, next press adds hyphen, next press “joins” the hyphens together and so on. Result is that you can’t create markdown tables for example.

## Describe what you expected to happen

Pressing hyphen multiple times should enter multiple hyphens

## Logfile

**Comment by bradleysmith** [comment]
Caused by smart punctuation in iOS. Disable by going to Settings->General->Keyboard->Smart Punctuation->Off.

THIS IS NOT A BUG

**Comment by MarcS1975** [comment]
thanks. I could not find the solution to this one. So thanks. How did you know this?
