### ISSUE TITLE
Icons of plugins in WYSIWYG are broken

### ISSUE THREAD

**Issue by ambrt** [laurent22/joplin#4414]
In 1.6.7 and 1.7.4 icons for plugins in WYSIWYG go to default icon:
![icons plugin joplin](https://user-images.githubusercontent.com/10456131/105713809-d8bdb880-5f1b-11eb-8c8a-7ddb7f5fe2cb.png)

For example there should be icon `fas fa-star`

**Comment by laurent22** [comment]
It's just not implemented for this editor. That might be done some day but in the meantime it will indeed default to the cog icon.
