### ISSUE TITLE
title sort order changed - "natural" vs "naive"?

### ISSUE THREAD

**Issue by krc** [laurent22/joplin#4415]
Sort order changed when viewing sorted by title

I have a notebook with historical deploys, current/upcoming deployments, and some templates
to get the correct order, I was sorting by title, and using a format like this:

```
2021-01-25 11:00 CRC non-prod patching
2021-01-26 10:00 BEA non-prod patching
90 - Deploy template 
95 ## Patching template
z - 2020-07-20 15:00 DLX non-prd patching
```

prefix with `z - ` to put the historical ones lower down

but now it is putting 2021-01-25 after 90 and 99
I guess before it was sorting on first digit and now is doing "natural" sort order with the whole number?

Anyway I need naive sort back please.

## Environment

Joplin version: 1.6.8
Platform: Mac OS x86
OS specifics: 10.15

## Steps to reproduce

1. create notes with titles starting with numbers
2. order by title

**Comment by tessus** [comment]
It was changed here: https://github.com/laurent22/joplin/pull/4272

I don't think is a bug, but rather a design decision. Let's see what Laurent says.
