### ISSUE TITLE
No code syntax highlighting for x86asm in editor

### ISSUE THREAD

**Issue by TyPR124** [laurent22/joplin#4417]
## Environment

Joplin version: 1.6.8 (portable) rev fc7bd41
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Create a new note and add a code block for `x86asm`

![joplin_asm_highlight](https://user-images.githubusercontent.com/29851190/105774169-fc402d80-5f32-11eb-9001-69ce01915b3d.PNG)

## Describe what you expected to happen

The code block should be have syntax highlighting in the editor.

**Comment by laurent22** [comment]
Have you tried other language names, like just "asm" for example?

**Comment by TyPR124** [comment]
I did try plain "asm" which has the same behavior as "x86asm"

"rust" on the other hand does highlight in both places.

**Comment by TyPR124** [comment]
So it seems that the "x86asm" is probably not standard, although it does work in my VSCode setup for rendered markdown (disabled all extensions, just in case, and it still worked, although I supposed something could have been incorrectly cached)

In trying to get this working in another project I'm testing out, I ended up adding [this file](https://gist.github.com/TyPR124/7d6cc329a97749117ebfc012ef8d92ed) to CodeMirror, which registers the "x86asm" mode. It almost an exact copy of CM's gas.js, except it doesn't take any parameters and is hardcoded to x86 instead of selecting between x86 and arm.

I'm sure the same could be done for arm.

In my testing (in Joplin and any similar app I've been testing) having something like

````
```gas
mov eax, -1
```
````

does not work.

Having said that, it seems like Joplin is using a more advanced assembly highlighting in the preview pane than what CodeMirror provides, so I'm not sure what the right approach is. It also seems like the preview pane is able to detect that it is assembly even if I don't include an explicit mode value.

**Comment by andi0b** [comment]
It's the same with F#, probably more languages. 

Editor:
![grafik](https://user-images.githubusercontent.com/2432095/113476409-aaa8a780-947b-11eb-8ea9-344bbd61b5cc.png)

Preview:
![grafik](https://user-images.githubusercontent.com/2432095/113476428-c57b1c00-947b-11eb-8642-75d0862bfb31.png)

**Comment by roman-r-m** [comment]
#F is probably too obscure to have highlighting available by default (no offence to any F# devs out there!)

**Comment by andi0b** [comment]
@roman-r-m: obscure or not, I think all languages supported by highlight.js/codmirror should be highlighted also in the editor and not just in the preview.

It’s not like it is not supported at all, it works in the preview!

**Comment by roman-r-m** [comment]
Is F# supported by CodeMirror though? Does not seem so.

It does work in webview because it uses highlight.js which is a library that specializes in syntax highlight, so to me it makes sense it supports more languages than a general purpose editor does.

I left a comment here on the forum https://discourse.joplinapp.org/t/any-suggestions-on-what-plugins-could-be-created/9479/158?u=roman_r_m maybe someone will be interested in picking this up.

**Comment by andi0b** [comment]
F# and assembler are both supported by code mirror. It probably need some mapping between the highlight.js identifiers and the CodeMirror MIME types. I will check it out.

F#: https://codemirror.net/mode/mllike/index.html
And also assembler: https://codemirror.net/mode/gas/index.html

**Comment by andi0b** [comment]
It seems like this is a CodeMirror limitation, you would need to load all language modes, to get highlighting for all languages. This is maybe not advised because of performance issues. And adding a setting for that may be also be a bit of an overkill...

Currently Joplin only loads the modes for the most common languages: https://github.com/laurent22/joplin/blob/bfacf71397e21fda5c7c1675365c4199d29de9e7/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx#L36-L69

**Comment by roman-r-m** [comment]
> F# and assembler are both supported by code mirror. It probably need some mapping between the highlight.js identifiers and the CodeMirror MIME types. I will check it out.

Ah, I was looking for something like `fsharp`. I stand corrected.

**Comment by CalebJohn** [comment]
> This is maybe not advised because of performance issues

This is correct, we were trying to find a balance between performance and usability. I've seen that @roman-r-m has already added this to the list of suggested plugins. I'll add that of anyone is interested in making such a plugin, please feel free to message me and I can help guide you as needed.

**Comment by andi0b** [comment]
The best solution would be to load all modules on demand. This is partly supported by CodeMirror (https://codemirror.net/doc/manual.html#addon_loadmode). 

It would probably increase performance for the editor, as most people won't use any fenced code blocks at all and add support for additional languages at the same time. A plugin would be a compromise.
