### ISSUE TITLE
Cannot edit note consisting only of fenced code in Rich Text editor

### ISSUE THREAD

**Issue by Daeraxa** [laurent22/joplin#4418]
Noticed this when looking at the problem described in https://github.com/laurent22/joplin/issues/4416. 
I noticed that if you have a note made from only fenced code created in the standard MD (codemirror) editor and swap to Rich Text mode, it isn't possible to obtain a cursor. The only method I found to get one (double clicking etc. didn't work) was to click to select the code block and press `enter` which removed the fenced code block before giving a flashing cursor.

## Environment

Joplin 1.6.8 (prod, win32)

Client ID: a4ed20b9be424a1c8c3e5f3cc355c345
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: fc7bd41c1 (master)

Windows 10

## Steps to reproduce

1. Create note in MD editor with a single fenced code block and no other text
2. Swap to rich text editor
3. Attempt to obtain cursor for editing

## Describe what you expected to happen
Clicking above or below the code block would grant a flashing cursor for text entry

**Comment by unquenchedservant** [comment]
This appears to have to do with data-mce-bogus <p> tag, every time I try to click in that region it flashes the cursor for a second and then goes away. 

A quick fix i found code wise was to add a <p>&nbsp;</p> right after the jopin-editable codeblock div. Thus giving the user an area to click that the cursor will work on. This has the behavior I believe intended by the bogus <p> noted above that clicking anywhere outside the codeblock puts the cursor in the <p>&nbsp;</p> spot. 

A good place to check this out is probably https://github.com/laurent22/joplin/blob/f7a457fb6c56d4236e1f6a6963e7ba4d3fde1984/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/plugins/lists.js#L984

**Comment by Daeraxa** [comment]
Tried a bit more, on the rich text editor if you press the right arrow on your keyboard you get a cursor at the start of the code block, press it again and you get it at the end. From there you can edit the note as expected. It isn't immediately obvious though (unless it is, I rarely use the rich text editor so it might be something people are accustomed to?)

**Comment by bytrangle** [comment]
Here's a screencast of the problem.

https://user-images.githubusercontent.com/28924121/106574767-e56e8c00-656d-11eb-90df-87497b5062b5.mp4

What could be suggested solution for this problem?

**Comment by laurent22** [comment]
I gave it a try and this is working as expected as far as I can see.

The fenced code block is just an element like any other, like image, so if you click on it and try to press some keys it won't do anything. You indeed need to press left or right to unselect the code block and give the focus to the text area. That might be a bit confusing if you're not used to Rich Text editors but it's a normal behaviour, or at least I'm not sure how it could be improved.

**Comment by isdnfan** [comment]
For me the main reason to store code blocks in my notes is to use them later - which is impossible as you can't select/copy the code from the code block. In opposite to other objects like images code block holds specially formatted text - so it should behave like text - allow select/copy/paste/edit.

**Comment by isdnfan** [comment]
unchanged

**Comment by coderrsid** [comment]
@isdnfan , in which editor you're saying.. Markdown or WYSIWYG editor?

Although, for WYSIWYG editor, you can copy/paste/select/cut the code block to different editors.

**Comment by isdnfan** [comment]
@coderrsid it's all about rich editor 
![image](https://user-images.githubusercontent.com/18125597/113128875-8dc16980-921a-11eb-80d5-9420c357fcfa.png)
- in rich-text editor it's impossible to select/copy from multi-line code blocks. the only workaround is to use "edit mode" by double-click on the code block.
- in rich-text editor select/copy only works for single-line code blocks. 
- In MD editor it's possible to select/copy from singe and multi-line code blocks.

**Comment by coderrsid** [comment]
>     * in rich-text editor it's impossible to select/copy from multi-line code blocks. the only workaround is to use "edit mode" by double-click on the code block.

That's absolutely right @isdnfan , didn't know that. I'm gonna create a new issue for this error and try to find the solution too. Thanks for noticing the error.
