### ISSUE TITLE
Table of contents is not generated correctly, only the first link is clickable

### ISSUE THREAD

**Issue by HermasciousLevander** [laurent22/joplin#4422]
## Environment

Joplin version: 1.6.8
Platform: Win32NT 10.0.18363.0
OS specifics: Microsoft Windows NT 10.0.18363.0

Tested this using the newest available version of JoplinPortable as well.

## Steps to reproduce

1. Create note
2. Add titles and $toc
3. Export to PDF

## Describe what you expected to happen

The table of contents to be generated like it is, but also clickable to easily jump between different titles as in older versions.

## Logfile

Having looked through it, there are no logs about the exports as far as I can see, only a OneDriveApi error at line 14. I don't think it'll be much help, but [here it is](https://hatebin.com/ifqtqfbpum) regardless.

**Comment by unquenchedservant** [comment]
This appears to be related to OneDrive specifically, although I can't account for other platforms. 

Just tried to replicate not having linked OneDrive yet and it was able to export with the TOC as expected. 

Version: 1.6.8
Platform: Win32NT 10.0.19041.0
OS Specifics: Windows NT 10.0.19041.0

**Comment by HermasciousLevander** [comment]
Strange. Was going to say it might have been related to #4305, but since you can't recreate it after linking it then it might be something else.

Debug console output:
`12:06:46: CommandService::execute: exportPdf ["e6edc4e7262e44908a56f861c26845dd"]`

`DevTools failed to load SourceMap: Could not load content for file:///C:/Users/user/AppData/Local/Programs/Joplin/resources/app.asar/InteropService_Exporter_Html.js.map: 
`

Nothing more than this in the log file when exporting though:
`2021-01-26 12:06:46: "CommandService::execute:", "exportPdf", "[["e6edc4e7262e44908a56f861c26845dd"]]"`

**Comment by HermasciousLevander** [comment]
Tried again now, this is still an issue. Seems it isn't affecting only the first choice though, kind of random.

Current test let me click on the first one, but not the second and third, but does work for the fourth and fifth, yet not the sixth, then works again for the seventh and eight. Weird. The only seeming relation between this is that the third and and sixth are both h3's, yet so is the eight which is clickable. Not really sure if it is random or if there is something else but pretty sure it has nothing to do with OneDrive or not considering this is export and that should not be affected by whatever sync target you choose.
