### ISSUE TITLE
JoplinServer : App: 404: GET /api/files/root://locks:/children : file not found: "" on parent "[...]"

### ISSUE THREAD

**Issue by xXZaretXx** [laurent22/joplin#4426]
Hello i try to set up the JoplinServer via Docker and the Docker Compose example.
The website loads and i can login with admin.
i created a user in the web interface and try to sync notes with the Joplin Windows client and only get error.

## Environment

Joplin version client:  1.6.8
Platform: Windows 10 2004
Joplin Server Node Version: 12.20.1
Joplin Server Yarn Version: 1.22.5
Joplin Server Node Env : development
Server Plattform: Ubuntu Server 18.04.5 LTS
Kernel 4.15.0.-132-generic

## Steps to reproduce

1.  use example docker-compose with password,user,base_app,db.. https://github.com/laurent22/joplin/blob/dev/docker-compose.server.yml
2. docker-compose up
3. login as admin and create user
4. set up the login data at the client
5. check configuration (success)
6. try to sync

## Describe what you expected to happen
an successfull sync..

## Logfile
(i only change the parent in the log)
```
app_1  | 2021-01-26 20:52:47: App: POST /api/files/root:/:/children
app_1  | 2021-01-26 20:52:47: App: POST /api/files/root:/:/children
app_1  | 2021-01-26 20:52:47: App: GET /api/files/root://locks:/children
app_1  | 2021-01-26 20:52:47: App: GET /api/files/root://locks:/children
app_1  | 2021-01-26 20:52:47: [error] App: 404: GET /api/files/root://locks:/children : file not found: "" on parent "aaBBcc"
app_1  | 2021-01-26 20:52:47: [error] App: 404: GET /api/files/root://locks:/children : file not found: "" on parent "aaBBcc"
```

**Comment by laurent22** [comment]
What did you put as sync directory? An empty string?

**Comment by xXZaretXx** [comment]
> What did you put as sync directory? An empty string?

mhm ..yes, on my first try an not empty value didn't work but i think there was another problem.
now it works with a value for the directory. So it was my fault. Maybe it would be helpfull if the client provide a check if the value is empty or only "/" because this work neither

**Comment by laurent22** [comment]
Yes sure, I was just double-checking what dir you used. It should indeed work with "/" and if it's a blank string, I guess it should assume it's "/". Thanks for the report, I'll look into it.

**Comment by hqh0803** [comment]
@xXZaretXx I have the same trouble as you

Joplin version client: 1.6.8
Platform: Windows 10
Joplin Server Node Version: current newest
Server Plattform: CentOS Linux release 8.3.2011
Kernel：4.18.0-193.14.2.el8_2.x86_64
Docker version：20.10.2, build 2291f61

client error log：
Error: GET api/files/root://locks:/children: Unknown error (404): {"error":"file not found: \"\" on parent \"eY2NXhRWS40K9YJp5yYil8DqvbvuhSnK\""}

**Comment by hqh0803** [comment]
Docker start log：

[root@hsdb test]# docker run --env-file .env -p 22300:22300 joplin/server:latest
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.

@joplin/server@1.7.1 start /home/joplin/packages/server
node dist/app.js

2021-01-21 07:46:40: App: Starting server (prod) on port 22300 and PID 24...
2021-01-21 07:46:40: App: Running in Docker: true
2021-01-21 07:46:40: App: Public base URL: http://xx.xx.xx.xx:22300
2021-01-21 07:46:40: App: Log dir: /home/joplin/packages/server/logs
2021-01-21 07:46:40: App: DB Config: {
client: 'pg',
name: 'joplin',
user: 'postgres',
password: '********',
port: 5432,
host: 'host.docker.internal'
}
2021-01-21 07:46:40: App: Trying to connect to database...
2021-01-21 07:46:40: App: Connection check: { latestMigration: null, isCreated: false, error: null }
2021-01-21 07:46:40: App: Migrating database...
2021-01-21 07:46:41: App: Call this for testing: curl http://xx.xx.xx.xx:22300/api/ping
2021-01-21 07:47:13: App: GET /api/ping
2021-01-21 07:47:13: App: GET /favicon.ico
2021-01-21 07:47:13: [error] App: 404: GET /favicon.ico : Path not found: favicon.ico

**Comment by laurent22** [comment]
@hqh0803, what directory did you use to sync?

**Comment by hqh0803** [comment]
@laurent22 , I don't know what you mean by synchronous directory,  I should synchronize all the data on my client Joplin

After I started the Joplin server through docker, the web page successfully appeared and the default account password was modified

Then I synchronize the data of Joplin client

1.Setting login data on client
2.Check configuration (successful)
3.Try to synchronize

4.Error: GET api/files/root://locks:/children: Unknown error (404): {"error":"file not found: "" on parent "eY2NXhRWS40K9YJp5yYil8DqvbvuhSnK""}

At this time, I check the web page, he already has two such directories named TMP and lock, but did not synchronize my data, and the error

**Comment by laurent22** [comment]
Here, what did you put as server directory, it's "App/Joplin" by default:

![image](https://user-images.githubusercontent.com/1285584/106122158-4520fd80-6150-11eb-98ac-cc3423344847.png)

**Comment by hqh0803** [comment]
My God, my here is empty, I will try again, thank you

**Comment by hqh0803** [comment]
@laurent22 Now it looks normal. Maybe it's because I had a problem in the first operation, and then I deleted this directory. Thank you

**Comment by laurent22** [comment]
Indeed for now you can set it to some directory. In the next version, I'll fix handling of empty directory, as that should mean "/".

**Comment by hqh0803** [comment]
I see. Thank you for your answer

**Comment by MrPeanut12** [comment]
Should this be working on the latest Docker server image (1.7.2) and Windows client (1.7.11)? I am still getting this error when my Joplin Server Directory is empty.

> 2021-03-15 14:37:42: "Error: GET api/files/root://locks:/children: Unknown error (404): {"error":"file not found: \"\" on parent \"nRqRj....\""}
