### ISSUE TITLE
Sync using dropbox missing folders and notes

### ISSUE THREAD

**Issue by sleekspeed22** [laurent22/joplin#4427]
## Environment
PC1
Joplin version: 1.6.8
Platform: Windows Desktop
OS specifics: Windows10 Home 20H2 Build 19042.746

PC2
Joplin version: 1.6.8
Platform: Linux Laptop
OS specifics: Lubuntu 20.10 (5.8.0-40-generic)

Phone
Joplin version: 1.6.7
Platform: Android
OS specifics: Android 10 One UI v2.5 Kernal v4.14.117-19529858

## Steps to reproduce

1. On PC1 create some folders and notes... some nest folders where the parent is empty exept for child folder (that has the notes)
2. Import some notes from Evernote (ENEX as Markdown)... I had about 700 notes across ~5 notebooks
3. created a new folder name Archive and move a couple notebooks into it
4. created a new folder name Work and move a couple notebooks into it 
5. created a new folder name Personal and move a couple notebooks into it 
6. setup sync to use dropbox and go through login steps then hit synch button 
7. Install Joplin in Linux and Android and setup synch through dropbox
8. click synch button on each and watch files sync keeping joplin in forground
9. rename the root folder Archive to Archive1 (to try to get the other joplins to see the folder)
10. create a new folder Ark (to see if any syncs were pickup up)
11. reimport one of the evernote notebooks (to see if lots of notes is the issue)

https://discourse.joplinapp.org/t/how-to-deploy-a-synchronized-joplin-instance-on-a-second-device/13719/12?u=sleekspeed22

## Describe what you expected to happen

see the screen shots... I expected all folders and notes would be replicated to Linux and Android.  But on synch on only got 1 parent folder and 1 child folder and it seemed like most of the notes but missing folders.

On renaming (step9), my folder and notes seemed to have been deleted from dropbox

(step 10) Creating new folder synched properly on Android but not on Linux

(step11) reimport of evernote notebook seemed to work correctly on Android but not on Linux

## Logfile
[linux_log.txt](https://github.com/laurent22/joplin/files/5876313/linux_log.txt)
[win10_log.txt](https://github.com/laurent22/joplin/files/5876314/win10_log.txt)
![android_log](https://user-images.githubusercontent.com/78045979/105909417-8781f780-5ff5-11eb-9bed-94423fba98a8.jpg)

**Comment by alexanderadam** [comment]
Just to be sure: did you keep the App open and the screen on, on your Android device?
Because [there's currently no background sync implemented](https://github.com/laurent22/joplin/issues/3872), thus this can result in some sync errors (i.e. app started sync, screen goes off, app is killed and stale lock is still there).
