### ISSUE TITLE
Date & Time: Insert does neither work with hotkey nor with Edit/"Insert Date Time" in Joplin 1.6.6 on Windows 10

### ISSUE THREAD

**Issue by l-p-r** [laurent22/joplin#4430]
Joplin 1.6.6 (prod, win32)

Client ID: e4f0cab9e8fd4565a0e4f08320efb770
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f58b7563e (master)

## Environment

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1. 
2. 
3.

**Comment by CalebJohn** [comment]
I think this is the same bug as #4339. Please update to the current version of Joplin (v1.6.8) and try again. If you still have any issue, feel free to add a comment below and I'll re-open this.

**Comment by l-p-r** [comment]
I upgraded to the latest version

Joplin 1.6.8 (prod, win32)

Client ID: e4f0cab9e8fd4565a0e4f08320efb770
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: fc7bd41c1 (master)

The bug still exists.

Thanks!

**Comment by CalebJohn** [comment]
@l-p-r do you think your issues is similar to [this one](https://discourse.joplinapp.org/t/keyboard-shortcuts-not-working-in-note-body/14405)?
