### ISSUE TITLE
Task: New Task - content entry does not allow for editting in traditional layout mode

### ISSUE THREAD

**Issue by l-p-r** [laurent22/joplin#4431]
When creating a new Task by Ctrl-T, I can enter in the Subject line but not in the content area.  I need to switch to the WYSIWYG editor mode to be able to enter content

Joplin 1.6.6 (prod, win32)

Client ID: e4f0cab9e8fd4565a0e4f08320efb770
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f58b7563e (master)

## Environment

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1. 
2. 
3.

**Comment by Daeraxa** [comment]
What settings do you have set in Options>Note?

**Comment by CalebJohn** [comment]
@l-p-r you probably have the viewer open, you'll need to toggle the markdown editor if you want to edit with it. This can be done in the menu View -> Toggle Editor Layout.
Or by Pressing Ctrl-L.

Or by hitting this button ![image](https://user-images.githubusercontent.com/2179547/106041533-26136480-6099-11eb-89d9-070ce071fb12.png)

**Comment by l-p-r** [comment]
Your suggestion was right.  After toggling the editor layout, I can 
insert text into the content again.

However, it still remains unclear to me why I can create a new task with 
the editting capability disabled, i.e. the need to switch the editor 
layout first, see screenshot.


After hitting the button, I can enter content.

Thanks
