### ISSUE TITLE
Import of markdown directory only adds linked images

### ISSUE THREAD

**Issue by ab791520b4** [laurent22/joplin#4433]
When importing Markdown from a directory I can successfully import linked images such as `![image](/uploads/c9e3d083363999c2486dfdc97d642bc6/image.png)`. These get transformed into something like `![image](:/ac0125f1effe4bd19ed096d6135fcec8)`. However, other files such as pdfs or pptx cannot be successfully imported. The link remains as is and the file cannot be opened from within Joplin.

## Environment

Joplin version: 1.4.19
Platform: Windows

## Steps to reproduce

1.  Create a directory with a markdown file refering to a non-image file within this directory.
2.  Import this directory into Joplin

## Describe what you expected to happen

The non-image file does not get imported.

**Comment by ab791520b4** [comment]
The issue still persists and should be fixed/implemented.

**Comment by HOLLYwyh** [comment]
I'm trying to solve it...

**Comment by HOLLYwyh** [comment]
> The issue still persists and should be fixed/implemented.
Could you please tell me the method you use to import the pdfs or ppt into your note?

**Comment by mightomi** [comment]
I looked into this issue, I found that `![pdf haha](some.pdf)` won't work since markdown doesn't support PDF. 
And also something like `<embed src="some.pdf" type="application/pdf"> ` wont work because of directory issue. 
@ab791520b4 can you share how you were adding the .pdf to the markdown.

**Comment by roman-r-m** [comment]
> @ab791520b4 can you share how you were adding the .pdf to the markdown.

Just a guess but probably something like `[](file://path/to/file.pdf)`

**Comment by ab791520b4** [comment]
I am trying to import Markdown files as I get them via the Gitlab API [1]. I am trying to import Gitlab issue comments I exported to a local directory tree. The way gitlab stores links to attached files is

`[something](/uploads/subdir/filename.extension)`

I store the files analogously in the directory I am trying to import into Joplin. Meaning there exists a top-level uploads directory in the directory to import.

[1] https://docs.gitlab.com/ee/api/notes.html#list-project-issue-notes

**Comment by ron-debajyoti** [comment]
Perhaps [this](https://github.com/laurent22/joplin/issues/4332#issuecomment-804933250) issue is similar and can resolve the current issue.

**Comment by ab791520b4** [comment]
I created a small example directory for importing:

[joplin-import-test.zip](https://github.com/laurent22/joplin/files/6262855/joplin-import-test.zip)
