### ISSUE TITLE
Search behavior and UX

### ISSUE THREAD

**Issue by marceljay** [laurent22/joplin#4435]
- Search finds "similar" words without asking. When I search for `invariant` the first match would be `invoking` even though, there are exact matches for `invariant`.  Sometimes words are found, that have nothing in common but the first letter.

- It's seemingly not possible to jump to the next match from the top bar search. 

In some instances I copied my into VS Code to find the lines I've been looking for.

## Environment

Joplin version:  1.1.4
Platform: Linux
OS specifics: Ubuntu 20.04.1

## Steps to reproduce
I tried but I can't. No idea how the indexing works, but the words in testing notes were not found at all.

**Comment by laurent22** [comment]
That's a rather old version of the app. Have you tried with 1.6?

**Comment by marceljay** [comment]
Updated now. New UI. But still not possible to directly jump to matches. Only lists the notes, in which you have to search again via find&replace. Would be great to have highlighting straight away.

**Comment by marceljay** [comment]
If I search for "b" I find the any word that string "b" is part of at any position. If search for "bac" the word "background" won't be found anymore. Even the note containing the headline "# Invariants" would not be found searching "Invariant" (s missing).
