### ISSUE TITLE
https self-signed certificate

### ISSUE THREAD

**Issue by ZER0-X** [laurent22/joplin#4439]
## Environment

Joplin version: 10.6.3
Platform: iphone 6
OS specifics: iOS 12..5.1

## Steps to reproduce

1. Have a nextcloud with **https self-signed certificate**.
2. Try to link it to my phone.
3. It's giving me "Error. Please check that URL, username, password, etc. are correct and that the sync target is accessible. The reported error was:    Network request failed"

## Describe what you expected to happen
I think there should be a button like in the desktop version "Ignore TLS certificate errors".

**Comment by kimyle** [comment]
The same problem, waiting for solution...

**Comment by roman-r-m** [comment]
@laurent22 I can try exposing [this flag](https://github.com/joltup/rn-fetch-blob#user-content-self-signed-ssl-server) to see if it helps. Will you accept such PR?

**Comment by laurent22** [comment]
I expect there would be more than this flag as regular fetch is also used.

**Comment by roman-r-m** [comment]
OK, I'll give it a try and see. Regular fetch can be replaced with rn-fetch-blob, I suppose.

**Comment by laurent22** [comment]
You make it sound easier than I think it is :)

Fetching data on mobile is not the most stable thing - for example there are already a few workarounds for bugs in React Native fetch or the underlying lib they use (both Android and iOS have a few quirks). If we switch to a different package I would be surprised if they aren't new bugs for which we'll have to find workarounds. And it's possible we won't know about these bugs till someone tries the app with their weird WebDAV server, which suddenly no longer works with the ap. Now the question is - is it worth it?

**Comment by roman-r-m** [comment]
Finally looked at this. In theory this isn't very hard to implement, however `rn-fetch-blob` does not support WebDAV atm.
It can be fixed with a trivial one-line change, but on the main page of this lib it says the project is no longer maintained, so my PR would probably be ignored.

**Comment by finzzz** [comment]
I also encounter this problem. Joplin works on desktop.

**Comment by brunoamaral** [comment]
Seeing the same issue on iOS 14.6 for the iPhone and iPad.

**Comment by uselpa** [comment]
Probably same error with Joplin 2.4.9 on MacOS
```
Last error: FetchError: request to https://xx.yy.zz/remote.php/webdav/Joplin/info.json failed, reason: certificate has expired
```

Worked fine minutes ago with the previous version of Joplin.

**Comment by voodoohoo** [comment]
+1 for iPad and iPhone with latest iOS. Would be great to use Joplin on these devices as well. Desktop Version on LinuxMint works like a charm

**Comment by zer0-x** [comment]
I heard that it's complicated to implement in iOS, so i can't expect any fix for it soon from the joplin side. However, you can fix it yourself by adding your nextcloud server's CA-certificate to your trusted certificates in the iOS settings, after having a compatible one.

This is a tutorial written in Arabic explain everything: https://discourse.aosus.org/t/topic/2189
Here is a tutorial in Germany (less explained): https://bob.gatsmas.de/caldav-sync-erinnerungen-app-ios-13-und-macos-1015
You are able to use a translator and you will get good results.
