### ISSUE TITLE
Copy-paste does not work in 'wysiwyg editor only mode'

### ISSUE THREAD

**Issue by spamattacklenrok** [laurent22/joplin#4441]
## Environment
Joplin version: 
Joplin 1.6.8 (prod, win32)

Client ID: 57eb5538cdab4eb4a69cddd00c2ecd35
Sync Version: 2
Profile Version: 34
Keychain Supported: No

Revision: fc7bd41c1 (master)

Platform: 
OS specifics: 
Windows 10 Enterprise, version 2004

## Steps to reproduce

1. Start portable version (I have not tested this on installer version)
2. Create new notebook and note, or just use "Welcome to joplin" note
3. by default there is this wysiwyg and markdown editor side by side.
4. copy any text from wysiwyg editor, or markdown editor, and paste into external application(tested on notepad++). Everything is fine. Copy-paste works from both editors to external application.
5. Switch to only wysiwyg editor. Copy any text, and try to paste into external application. It does not work. Clipboard is empty.

Looks like copy-paste is not working in wysiwyg only mode from joplin to external_application.

**Comment by laurent22** [comment]
It works for me.

**Comment by spamattacklenrok** [comment]
I will add some recording and try to attach this, but I need to find some software for this.

**Comment by spamattacklenrok** [comment]
![APGHRNpj2c](https://user-images.githubusercontent.com/78206918/106275297-de760f80-6235-11eb-96ed-7be925d1ba5a.gif)

**Comment by spamattacklenrok** [comment]
As you can see copy-paste does not work after switching to only WYSIWYG mode.
It is fresh startup of portable version, new profile has been created, I have not changed any settings/options in joplin (everything is default)

**Comment by laurent22** [comment]
Ok I see, thanks for the video. I've tried with Cmd+C earlier and that works, but indeed it looks like the Copy menu item doesn't.

**Comment by spamattacklenrok** [comment]
Thanks for workaround - I have not checked ctlr+c/v 


Maybe wrong place, but I am using joplin for last few days for notes (previously just bunch of text files). 
It is very good application. I really like it. You (and the rest of team) are doing great job. Thanks to all of you.
