### ISSUE TITLE
Library too big, iOS + Dropbox won't sync

### ISSUE THREAD

**Issue by gxcross** [laurent22/joplin#4445]
I have 22,028 items in my Joplin library, synced to Dropbox. On my macs and pcs, I can sync completely fine. However, on my iPhone, I can't get it to sync. I disabled auto-sleep and let it sync (takes over an hour), and it completes. However, even after it seems to have finished, it only shows ~10-15 notes (out of 1,700) and no notebooks or anything else. I have a lot of attachments in my notes, which makes the library extra big. Based on the error log, maybe it's timing out because the sync is taking too long?

## Environment

Joplin version: 10.6.3
Platform: iOS (also running the Mac and Windows versions)
OS specifics: iPhone 12 Pro Max running iOS 14.3 

## Steps to reproduce

1. Clean install of Joplin on iOS via Apple App Store
2. Settings (app) > Display & Brightness > Auto-Lock: Set to Never 
3. Open Joplin
4. Authorize Dropbox synchronization
5. Start sync on a large library (my library has 22k items, consisting of 1.7k notes, 80 folders, 2.3k resources, 124 tags, 14k notetags, 3.6k revision). On disk, my Joplin folder takes up 3.23 GB.
4. Sync completes in an hour+, but the library is not here. Only a handful of notes are viewable.

## Describe what you expected to happen
Expected the notebooks & notes to be available in the app.

## Logfile

![IMG_1341](https://user-images.githubusercontent.com/10765800/106382032-a74f5c00-63f7-11eb-804f-9feecdf4a3b6.jpeg)
![IMG_1342](https://user-images.githubusercontent.com/10765800/106382034-aa4a4c80-63f7-11eb-89dd-7b312f367d99.jpeg)
![IMG_1343](https://user-images.githubusercontent.com/10765800/106382037-ad453d00-63f7-11eb-9164-beefc75af4f7.jpeg)

**Comment by alexanderadam** [comment]
I'm not sure whether this is the reason but keep in mind that [there's no background sync yet](https://github.com/laurent22/joplin/issues/3872).
Did you keep Joplin in foreground?

**Comment by gxcross** [comment]
Yeah, I turned off auto-sleep and kept the app in the foreground the whole time.

**Comment by gxcross** [comment]
Sadly, it is still happening.

**Comment by gxcross** [comment]
still happening..

**Comment by gxcross** [comment]
It works now! Thankl you to whoever fixed it!
