### ISSUE TITLE
"search in all notes" can't find check boxes: `[ ]`

### ISSUE THREAD

**Issue by manihamidi** [laurent22/joplin#4447]
Search doesn't return the "checkbox" items: `- [  ]` or `[ ]` etc. Tried putting in quotations i.e. `"[ ]"` and also escaping them i.e. `\[ \]` and none of these worked either. 

I simply would like to be able to see all my "to do" items in one place. 

## Environment

Joplin version: Joplin 1.6.8 (prod, linux) Revision: fc7bd41 (master)
Platform: Linux 
OS specifics: Ubuntu 20.04

## Steps to reproduce

1. Go to "search in all notes". 
2. Put in `[ ]` (assuming you have some notes with `- [ ]` (aka a checkbox) in them. 
3. Note that there are no hits. 

## Describe what you expected to happen

I'd expect to see all the notes with these check boxes listed, like a proper search for any other string. 

## Logfile

Can't load logfile because of the other open issue i made a little while ago:  #4389 

![image](https://user-images.githubusercontent.com/15459064/106396673-5f601300-63be-11eb-89db-b76f31cf30a6.png)
![image](https://user-images.githubusercontent.com/15459064/106396723-9fbf9100-63be-11eb-9e83-47030d1ef88d.png)
![image](https://user-images.githubusercontent.com/15459064/106396736-a948f900-63be-11eb-8c89-2ecb0a2d505c.png)
I definitely do have notes with these `[ ]` characters in them. 
![image](https://user-images.githubusercontent.com/15459064/106396770-e319ff80-63be-11eb-9f17-d4a2f6cb06e8.png)

**Comment by JackGruber** [comment]
Thi is a limitation of the search.

https://joplinapp.org/#searching
You can use the basic search.
`/"[ ]"`
