### ISSUE TITLE
Edit in External Editor Not working - still/again

### ISSUE THREAD

**Issue by plc5700** [laurent22/joplin#4448]
According to the last comment on this issue: https://github.com/laurent22/joplin/issues/2076
this problem was fixed back a long time ago.
"This issue seems to be fixed in the latest version I got today: Joplin 1.0.174 (prod, darwin)"

However the case described in Issue 2076 - I'm experiencing today using 1.7.10.

This is my Joplin Version
Joplin 1.7.10 (prod, darwin)
Client ID: 3f66013f710b4bf1bf799c55efa76986
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes
Revision: fb1c876 (master)

Running on macOS Big Sur v. 11.1

After entering an external editor in the setup, I was expecting to open a note in the external editor and to be able to edit and save the note from this external editor.

**Comment by tessus** [comment]
It works without issues for me. This looks like a user error and should be discussed on the forum.

Furthermore you should be a bit more specific. What does not work? Opening the editor? Saving a file in the editor isn't reflected in Joplin? What are the path and arguments for the editor in settings?

**Comment by plc5700** [comment]
Well I refer to a case where the desciption ig given and I have the excact same setup, expectations and errormessage. Maybe i should have written that.

Anyway - Today i Switched to use Typora as my external editor. That works as expected and I don't get the error messages.
However - when I use Hawkmark as an editor I get the exact same error as in the referred case.

So - Anyway - I'm happy using Typora, as I allows me to solve other issues also.
So Maybe the documentation should just be updated with a list of tested and verified applications that works and then let that be it.

**Comment by tessus** [comment]
Maybe you have to use a commandline option (argument) for Hawkmark. Some editors require that. Also, I asked what you entered in the field. e.g. just `/Applications/whater.app` usually does not work. Most editor provide a separate script or binary to start it from the command line. This is the one you have to use.
