### ISSUE TITLE
Background flashes white when opening notes in the iOS app

### ISSUE THREAD

**Issue by therealkrispet** [laurent22/joplin#4450]
This is the same issue described in [4228](https://github.com/laurent22/joplin/issues/4228), which was closed due to inactivity.
See the screen recoding from the old issue: [https://streamable.com/a3uh43](https://streamable.com/a3uh43)

## Environment

Joplin version: 10.6.3
Platform: iOS
OS specifics: iOS 14.3

## Steps to reproduce

1. Select any theme with a dark background, for example the appropriately named "Dark" theme (Configuration -> Appearance -> Theme)
2. Save the configuration
3. Open any note or todo

## Describe what you expected to happen

The note or todo to open smoothly with a background color matching the one from the selected theme.
Instead, the background of the note flashes white (once) and then correctly resets to the background color of the theme.

**Comment by Jegber** [comment]
This bug also occurs in macOS 10.15.7, Joplin version 1.7.11

**Comment by jleighton** [comment]
Occurs in Joplin 1.7.11 (prod, win32) when using any dark theme

**Comment by Jonta** [comment]
Happens on Android when tapping on note to bring up keyboard (AnySoftKeyboard)

Joplin version: 1.7.5, Database v34, FTS enabled: 1
Platform: Android
OS specifics: 10

**Comment by Jonta** [comment]
Still requires the community's attention

**Comment by roman-r-m** [comment]
Looks like it's been fixed. Maybe hasn't been released yet.

**Comment by Jonta** [comment]
Still happens

**Comment by Jonta** [comment]
Still happens

**Comment by laurent22** [comment]
On what version?

**Comment by Jonta** [comment]
> On what version?

@laurent22 2.1.4 Android

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.1.4 - Database v39

**Comment by Jonta** [comment]
@laurent22

Can no longer reproduce

Android

Joplin 2.3.4 - Database v39

**Comment by therealkrispet** [comment]
Can confirm as well:
I am no longer able to reproduce the issue on iOS 15.0, Joplin app version 12.3.1.
I will close this issue as it seems to be fixed, thank you for the attention & work.
Joplin is coming along really nicely!
