### ISSUE TITLE
Sync error when parsing 503 service unavailable from OneDrive

### ISSUE THREAD

**Issue by matt32106** [laurent22/joplin#4451]
The sync mechanism has trouble processing 503 Service unavailable from OneDrive. It displays the following at the bottom left of the screen.
```
Last error: SyntaxError: On file 127eaff83d0c4cebb64cdce58169671b.md: OneDriveApi::exec: Cannot parse JSON error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd"> <HTML><HEAD><TITLE>Service Unavailable</TITLE> <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD> <BODY><h2>Service Unavailable</h2> <hr><p>HTTP Error 503. The service is unavailable.</p> </BODY></HTML> Unexpected token < in JSON at position 0
Search...
```

## Environment

Joplin version: 1.2.6
Platform: Win10
OS specifics: 

## Steps to reproduce

1. Sync when onedrive is unavailable
2. 
3. 

## Describe what you expected to happen
More friendly error message.

**Comment by CalebJohn** [comment]
@matt32106 it looks like you're on an old version of Joplin. The current release is v1.6.8. You might find an update will fix this bug (there have been some changes to the OneDrive sync, but I'm not sure if this will be affected)
