### ISSUE TITLE
MarkdownIt plugin isn't called when switching between to exact notes 

### ISSUE THREAD

**Issue by ambrt** [laurent22/joplin#4453]
If two notes have same body and one will switch between them  - markdown isn't refreshing the view and plugin's command isn't called.

Basically the last rendered view stays in pane.

No errors from main console nor from console of plugin.
And it happens for both markdown fence and adding markdown rule.

Its reported here with video of the issue https://github.com/ambrt/joplin-plugin-referencing-notes/issues/3

**Comment by laurent22** [comment]
Hmm I think the current behaviour is correct - if nothing has changed the view shouldn't be rendered again. Is it not possible to solve this by listening to the note change event?

**Comment by laurent22** [comment]
I've looked again at it and I'm not certain there's anything to fix on the app, and in particular there's an expectation that the same Markdown content should produce the same HTML, although indeed you can change this to an extend with markdown-it plugins.

I feel that two notes producing two different renderings is an indication that something is not quite right with the plugin design. Have you considered any of these alternatives?

- Add the backlinks directly to the note body. In that case the two notes will be different and thus will have different outputs.
- Create a separate panel and add the backlinks to it, in which case you can manage this view any way you want.
- Failing that, perhaps you can get something working with onNoteSelectionChange

**Comment by ambrt** [comment]
Here's simplest possible reproduction version:
Plugin is just registering Markdown script and scripts prints to log when it's used.

https://github.com/ambrt/joplin-plugin-embed-search/tree/fence-bug (fence-bug branch)

```
 return {
        plugin: function (markdownIt, _options) {
                const defaultRender = markdownIt.renderer.rules.fence.bind(markdownIt.renderer.rules)

                markdownIt.renderer.rules.fence = function(tokens, idx, options, env, self) {
                    let token = tokens[idx];

                    if (token.info !== 'search') return defaultRender(tokens, idx, options, env, self);
    
                    console.log('should log this for every preview')
                    
                    return "fence should show this in preview"
                };
            },  
}
```
So i guess its not on plugin's side.
There's no triggering of plugin's function when the switched bodies are same.

> perhaps you can get something working with onNoteSelectionChange
Can this function be listened for from ContentScript?
Some logic could check for it  and update content.

**Comment by laurent22** [comment]
What I mean is that it's not a bug, it's a feature: if the Markdown content has not changed, then the note is not rendered again.

> Can this event be listened for from ContentScript?

No, but you can listen to it from the plugin.

But it's possible that what you want to do currently cannot be done. Having the same Markdown renders to different HTML is not something I particularly want to support, I feel it should be done differently.

**Comment by ambrt** [comment]
Ok i agree.
So the way i think to work around this is to save NoteId in plugin and make polling  ContentScript to check if there's a change of it.
Maybe 5 seconds interval.
