### ISSUE TITLE
Strange behavior of compound keys

### ISSUE THREAD

**Issue by antoniopaolini** [laurent22/joplin#4460]
I made a custom keyboard with MSKLC (Microsoft Keyboard Layout Creator).
I have a Italian keyboard, then I 've added some things to simplify writing markdown, like:
- AltGr + ' to insert ` (Alt+096)
- AltGr + ì to insert ~ (Alt + 126)
- AltGr + - to insert -AP- (my name)

This keyboard works fine in any application, i.e. notepad, VSCode, Vim, etc.

In the Joplin Rich Text editor the first two shotcuts works well but the last not.
If I push the AltGr + - I obtain that the cursor go to the first row, in "home" position and insert only the last character (I tried with some modifications to the keyboard to see if the hyphen inserted whas the first or the last character).

Maybe this issue is related with #4284 ?

## Environment

Joplin version:  Joplin 1.6.7 (prod, win32) Revisione: b74b84983 (master)
Platform: Windows 10

## Steps to reproduce
I can't attach a dll keyboard or setup.exe, then I'll attach the source file for MSKLC.
If you need and trust them, I can send Layout dll.
[tastiera AP.zip](https://github.com/laurent22/joplin/files/5917215/tastiera.AP.zip)

**Comment by antoniopaolini** [comment]
Is it solved?

**Comment by antoniopaolini** [comment]
the problem is still there

**Comment by dz2106** [comment]
https://github.com/laurent22/joplin/issues/4579

I describe this issue here more, but basically this is a persistent problem across multiple applications. It is best to close this issue.
