### ISSUE TITLE
Preferences->Plugin->Search Box is unclickable

### ISSUE THREAD

**Issue by novelx** [laurent22/joplin#4462]
## Environment

Joplin 1.7.10 (prod, darwin)

Client ID: 4a077b89ba834d6ba39d8fe420fea048
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: fb1c876 (master)

Platform: MacOS
OS specifics:  Catalina

## Steps to reproduce

1. Goto Preferences
2. Goto Plugin
3. Click the search box, either the editbox or the search icon on the very right. It is unclikable and can't input anything.

## Describe what you expected to happen

Input text and search for plugins.

## Logfile

[-1612350453085.log](https://github.com/laurent22/joplin/files/5917966/-1612350453085.log)

**Comment by laurent22** [comment]
I can't replicate this with 1.7.10

**Comment by tessus** [comment]
Tried on the Mojave and Catalina. It works on both for me.

**Comment by novelx** [comment]
Just upgraded to 1.7.11 and remain the same.
## Snapshot and video link
![image](https://user-images.githubusercontent.com/230644/106841851-d60e5080-66dd-11eb-8ab2-455ef3a43846.png)

[**Here's a link to a video**](http://novelx720p.quickconnect.cn/d/s/601956540645162942/IchjRNHz4aSpjCWfDJRsGptOhi9Yxwh--4r9gC1KUWgg_) **<<=======**

## Config dir & files
** List config dir **
XHs-MBA:joplin-desktop xiaohan$ ll
total 33924
-rw-r--r--@   1 xiaohan  staff   6.0K  2  3 18:54 .DS_Store
drwxr-xr-x    5 xiaohan  staff   160B  2  3 17:14 cache/
-rw-r--r--    1 xiaohan  staff    33M  2  4 11:41 database.sqlite
-rw-r--r--    1 xiaohan  staff    43B  2  3 18:59 flags-disable.txt
-rw-r--r--    1 xiaohan  staff   192B  1 29 10:50 keymap-desktop.json
-rw-r--r--    1 xiaohan  staff    18K  2  4 09:57 log-autoupdater.txt
-rw-r--r--    1 xiaohan  staff   3.1K  2  4 09:57 log-clipper.txt
-rw-r--r--    1 xiaohan  staff    62K  2  4 11:47 log.txt
drwxr-xr-x    3 xiaohan  staff    96B  2  3 18:27 plugins/
drwxr-xr-x  979 xiaohan  staff    31K  2  2 18:24 resources/
drwxr-xr-x    2 xiaohan  staff    64B  1 21 10:08 templates/
drwxr-xr-x    7 xiaohan  staff   224B  2  4 11:19 tmp/
-rw-r--r--    1 xiaohan  staff     0B  1 22 10:12 userstyle.css
XHs-MBA:joplin-desktop xiaohan$ ll cache/
total 0
drwxr-xr-x  6 xiaohan  staff   192B  2  2 12:15 Outline/
drwxr-xr-x  7 xiaohan  staff   224B  2  2 12:15 joplin.plugin.note.tabs/
drwxr-xr-x  4 xiaohan  staff   128B  2  3 17:14 osw.joplin.markdowncalc/
XHs-MBA:joplin-desktop xiaohan$ ll plugins/
total 1624
-rw-r--r--  1 xiaohan  staff   1.6M  1 21 18:28 joplin.plugin.note.tabs.jpl
XHs-MBA:joplin-desktop xiaohan$ ll templates/
XHs-MBA:joplin-desktop xiaohan$ ll tmp/
total 52
-rw-r--r--  1 xiaohan  staff   907B  2  4 09:57 22495897ff0bef0e6a2ba2610458a681.css
-rw-r--r--  1 xiaohan  staff    17K  2  4 09:57 5bc8f0452fc46d310825a3197db74564.css
-rw-r--r--  1 xiaohan  staff    51B  2  4 09:57 c6446da69e9e26701d8d96aac114a41b.css
-rw-r--r--  1 xiaohan  staff    20K  2  4 09:57 plugin_joplin.plugin.note.tabs.js
-rw-r--r--  1 xiaohan  staff   2.2K  2  4 11:41 plugin_joplin.plugin.note.tabs_theme_1.css

## Environment
Joplin 1.7.11 (prod, darwin)

Client ID: 4a077b89ba834d6ba39d8fe420fea048
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f560563 (master)

**Comment by novelx** [comment]
I just removed Joplin Desktop using app cleaner, renamed '.config' to '.config1' and do a fresh install of 1.7.11, and it remains the same. Any idea?

**Comment by laurent22** [comment]
Please provide the log again

**Comment by novelx** [comment]
> I removed 1.7.11 and installed 1.6.6 and 1.6.8 respectively, and the plugin search box is editable. Then I removed Joplin Desktop using app cleaner, renamed '.config' to '.config1' and did a fresh install of 1.7.11, and it remains the same (all my notes fly away and the plugin search box remains unclickable). Any idea?

## log 1
1. delete ~/.config
2. install 1.6.8 and create ./config/joplin-desktop/flags.txt with content `--open-dev-tools --debug --log-level debug`
3. relaunch Joplin, ⌘+',', plugin, type 'outline' in the search box and type enter
[joplin-1.6.8-launch-settings-plugin-search-1612431384574.log](https://github.com/laurent22/joplin/files/5924665/joplin-1.6.8-launch-settings-plugin-search-1612431384574.log)

## log 2
1. delete 1.6.8 app
2. install 1.7.11 app
3. launch Joplin, ⌘+',', plugin, trying to type something in the search box but failed
[Uploading joplin-1.7.11-launch-settings-plugin-search-1612431498619.log…]()

**Comment by jiqingshanhe** [comment]
I had the same problem.

The plug-in search box has been unavailable since the plug-in function was launched (the search box cannot be searched).

Joplin 1.7.11 (prod, win32)

客户端 ID: f4563b666d2244d58cd5118e654b44a9
同步版本: 2
配置文件版本: 34
支持的密钥链: 是

修订: f560563d8 (master)


[log.txt](https://github.com/laurent22/joplin/files/5931756/log.txt)
[log-autoupdater.txt](https://github.com/laurent22/joplin/files/5931758/log-autoupdater.txt)
[log-clipper.txt](https://github.com/laurent22/joplin/files/5931761/log-clipper.txt)
[log-database.txt](https://github.com/laurent22/joplin/files/5931762/log-database.txt)

**Comment by novelx** [comment]
Is it possible a networking problem?

Today I found that the search box works and there's 'update' button next to the 'delete' button in a particular plugin box. And I found it works from time to time this morning. It looks like a user side networking caused problem while the behavior of the searchbox confused me.  @laurent22

**Comment by JIagengDing** [comment]
Are you in China? 

I think it's a network problem and I also can't search when I'm not using a proxy. When you install the plugin you can turn on proxy mode.

Can it solve your problem?

**Comment by novelx** [comment]
> Are you in China?
> 
> I think it's a network problem and I also can't search when I'm not using a proxy. When you install the plugin you can turn on proxy mode.
> 
> Can it solve your problem?

Yes in China.
The search works from time to time, and I'm quite sure it's a network caused problem.

**Comment by JIagengDing** [comment]
So it is not a bug of Joplin.

**Comment by novelx** [comment]
> So it is not a bug of Joplin.

I think it is. Joplin should give proper feedback in case of any problem connecting to the plugin server. At this moment, Joplin just make the search box unclickable and this confuses the user.

**Comment by JIagengDing** [comment]
I think this should be due to our government.

**Comment by novelx** [comment]
> I think this should be due to our government.

The point is not the network failure but Joplin's behavior on network failure.

**Comment by gravypower** [comment]
I agree with @novelx, I was very confused with what was going on. A non technical user would not resort to github issues to find out.

**Comment by 4SM** [comment]
Please set DNS
[Imgur](https://imgur.com/SWC5he8)

**Comment by Entreprenerdz** [comment]
I have this issue as well... this post has given me some knowledge that it's most likely because my VPN is landing me in Germany.

So some documentation would go a long way.  I've been getting by until now by finding .jpl or using npm.

Plus, I don't know where I should be setting my VPN to (doesn't even state here).  So, I'll have to use trial and error.  Canada (my actual location) first, then USA,then I'm gonna guess.... North Korea???

**Comment by Entreprenerdz** [comment]
Actually neither Canada or USA VPN location has changed it's disabled state.

Where is your plugin server located?
Cheers

**Comment by laurent22** [comment]
> I have this issue as well... this post has given me some knowledge that it's most likely because my VPN is landing me in Germany.

Are you sure it's really the VPN? Could you provide more information about it? Because normally the app just fetches a file from GitHub so VPN or not it shouldn't matter, unless GitHub is blocking it (but that'd be surprising).

**Comment by Entreprenerdz** [comment]
Definitely not sure it's the VPN... could be my DNS??? (I'm using a 3rd party malware, ad-blocker). I'll reboot into safe mode, set DNS back to autoconfig, and see what's up.  Works fine on WinX, no love on macOS, and I haven't had the pleasure of firing Joplin up on Android just yet.

Stay tuned!

**Comment by dvictori** [comment]
I'm having a similar problem but I think it's because I'm behind a network proxy. I don't need to use proxy for Sync since my webDav server is internal. But I can't see the plugin list due to a network timeout. 

My current system uses
```
Joplin 2.13.15 (prod, linux)

Client ID: ae22ec5fb4b045b6bbe172ec61b1836f
Sync Version: 3
Profile Version: 44
Keychain Supported: No

Revision: 7d2c1c0

Simple Backup: 1.3.6
```

When I start joplin-desktop at the CLI I get 

```
[1122417:0124/090200.392720:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.portal.Error.NotFound: Requested setting not found
```

And when I try to search for plugins in the preferences, I see the following message on the development console


```
09:09:52: RepositoryApi: findWorkingMirror: Could not connect to https://raw.githubusercontent.com/joplin/plugins/master: 
FetchError {message: 'network timeout at: https://raw.githubusercontent.com/joplin/plugins/master/.gitignore', type: 'request-timeout', stack: 'FetchError: network timeout at: https://raw.github…/lib/node_modules/node-fetch/lib/index.js:1484:13'}
message
: 
"network timeout at: https://raw.githubusercontent.com/joplin/plugins/master/.gitignore"
type
: 
"request-timeout"
stack
: 
"FetchError: network timeout at: https://raw.githubusercontent.com/joplin/plugins/master/.gitignore\n    at /tmp/.mount_JoplinXogxAZ/resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/lib/index.js:1484:13"
[[Prototype]]
: 
Error
```

I believe this tread mentions a similar problem
https://discourse.joplinapp.org/t/proxy-exceptions-by-domain/35443

**Comment by guidomz** [comment]
I am still having the same problem in 2026 and turning off my VPN enables the search input form. However, I prefer not to work without my VPN. I am using the desktop version 3.6.15 AppImage release on Debian Bookworm, without any network proxies. On the other hand, 3.6.20 on the android, proxied via orbot, does not have this problem.
