### ISSUE TITLE
Created "Приложения" instead of "Apps" folder for OneDrive sync

### ISSUE THREAD

**Issue by Inrumpo** [laurent22/joplin#4463]
## Environment

Joplin version: 1.7.10 / 10.7.2
Platform: Windows 10 PC / iPhone SE 2020 
OS specifics: Win10 64 Bit Home build 2004 / iOS 14.4

## Steps to reproduce

1. Download iOS app on iPhone (language set to Swiss-German)
2. Enable sync to OneDrive
3. Joplin will create a folder called `Приложения` in OneDrive.

Google tells me that this is in "Prilozheniya" (Russian?).

I assume that having set my iOS device to Swiss-German (which is pretty rare and _not_ German) might have confused Joplin and led it to create that folder in this language.

## Describe what you expected to happen

Joplin should have created a folder called `Apps` in OneDrive.

## Logfile

No errors, since there isn't really an error. Sync is working. It's a cosmetic issue.

## Questions

Can I rename that folder to e.g. Apps without introducing sync issues?

**Comment by roman-r-m** [comment]
Might be a problem with OneDrive rather than Joplin.

**Comment by laurent22** [comment]
Yes just another idiotic change that Microsoft introduced recently. You might want to report this on the OneDrive repo.

**Comment by Inrumpo** [comment]
Thank you for your quick feedback. I did file a report to the OneDrive team.

If others should come across this topic and are experiencing the same issue, here is what I did:

1. Backup your Joplin notes (Export).
2. Backup the `Приложени` folder from OneDrive.
3. Rename the `Приложени` folder in `OneDrive` to `Apps`.

That's it. This was surprisingly easy. In case something went wrong you can still import files from the export or the backup `Приложени` folder to the renamed sync environment.

**Comment by Inrumpo** [comment]
I just got a reply in from the Microsoft OneDrive support. They simply say that OneDrive does support a multitude of languages and that the problem is caused by the Joplin App that created the folder in the wrong language. Now we're in a loop.
