### ISSUE TITLE
Sample import plugin code is broken

### ISSUE THREAD

**Issue by lostfictions** [laurent22/joplin#4468]
## Environment

Joplin version: 1.6.8
Platform: Linux (flatpak)
OS specifics: Ubuntu 20.04

## Steps to reproduce

1. Grab the JSON Export sample code here https://github.com/laurent22/joplin/tree/dev/packages/app-cli/tests/support/plugins/json_export (it also includes a stubbed-out sample importer, which is enough to repro our bug.)
2. Enter the directory and run `npm i`. (It seems like it errors on first install -- the `prepare` script defined in the sample's `package.json` should [probably be named `prepublishOnly` instead](https://docs.npmjs.com/cli/v6/using-npm/scripts#prepare-and-prepublish).)
3. Run `npm run dist` to build the plugin without modifications.
4. Open Joplin, go to Options > Plugins > Advanced > Development plugins. Enter the plugin directory name. Reload Joplin.
5. Select File > Import > JSON - JSON Export Directory and select any directory.

The following will be emitted:

```
PluginRunner: "Could not send IPC message:", "pluginMessage", ": ", "{"callbackId":"cb_org.joplinapp.plugins.JsonExportDemo_1612423614426_2","target":"plugin","pluginId":"org.joplinapp.plugins.JsonExportDemo","eventId":"___plugin_event_onExec_6","args":[{"sourcePath":"<selected directory>","options":{"format":"json","destinationFolderId":null,"destinationFolder":null,"path":"<selected directory>","outputFormat":"md"},"warnings":[]}]}", "Error: An object could not be cloned.
Error: An object could not be cloned.
    at EventEmitter.i.send.i.send (electron/js2c/renderer_init.js:71:259)
    at ipcRendererSend (/app/joplin-desktop/resources/app.asar/services/plugins/PluginRunner.js:24:28)
    at /app/joplin-desktop/resources/app.asar/services/plugins/PluginRunner.js:52:13
    at Generator.next (<anonymous>)
    at /app/joplin-desktop/resources/app.asar/services/plugins/PluginRunner.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/joplin-desktop/resources/app.asar/services/plugins/PluginRunner.js:4:12)
    at Object.onExec (/app/joplin-desktop/resources/app.asar/services/plugins/PluginRunner.js:47:29)
    at InteropService_Importer_Custom.<anonymous> (/app/joplin-desktop/resources/app.asar/node_modules/@joplin/lib/services/interop/InteropService_Importer_Custom.js:21:33)
    at Generator.next (<anonymous>)"
```
Inspecting the object in question, it appears to contain functions:
![image](https://user-images.githubusercontent.com/567041/106859952-bfdaa300-6691-11eb-9213-69ca3a353ce3.png)

[Electron IPC uses the structured clone algorithm since 8.0](https://www.electronjs.org/docs/breaking-changes#behavior-changed-values-sent-over-ipc-are-now-serialized-with-structured-clone-algorithm), throwing an exception when you try to send functions.

## Describe what you expected to happen

The plugin code should be passed the path/context object without issue.

## Logfile

See above for relevant section of log.

**Comment by lostfictions** [comment]
(On an additional note, I am trying to refer to https://github.com/laurent22/joplin/blob/dev/packages/lib/services/interop/InteropService_Importer_Raw.ts as recommended in the comment for that sample, but I'm finding it pretty difficult to understand how this should map to an import plugin -- any kind of hints or sample would be appreciated!)

**Comment by lostfictions** [comment]
Unfortunately, in the end I abandoned the idea of using Joplin since there was no clear way to efficiently import my (several years of) notes/bookmarks from another service. (I wrote a script to import via the HTTP API, but it was going to take over 24 to complete from the looks of it -- and it got slower as more notes were added. Maybe the importer is accidentally quadratic?)

**Comment by nitinkatyal1314** [comment]
> Unfortunately, in the end I abandoned the idea of using Joplin since there was no clear way to efficiently import my (several years of) notes/bookmarks from another service. (I wrote a script to import via the HTTP API, but it was going to take over 24 hours to complete from the looks of it -- and it got slower as more notes were added. Maybe the importer is accidentally quadratic?)

I faced the similar issue, and this does seem like a dead end. Adding the forum link to discussion on this matter for future reference and others: 
https://discourse.joplinapp.org/t/how-to-create-import-module-in-joplin/16348?u=nitinkatyal1314
