### ISSUE TITLE
Caret stays active in editor when dialog is opened with keyboard shortcut

### ISSUE THREAD

**Issue by ambrt** [laurent22/joplin#4473]
v1.7.11, latests plugins api.
![Peek 2021-02-04 20-42](https://user-images.githubusercontent.com/10456131/106946548-88b7d080-6729-11eb-8a4f-78acae6567d1.gif)

Steps:
1.Focus editor to have caret
2.Press accelerator ("Ctrl+Alt+N")
3.Text in editor can still be edited with dialog over it.

Doesn't happen when using ToolbarButton or triggering from Goto Anything
Smallest reproduction of the bug with accelerator
https://github.com/ambrt/dialog-shortcut-bug

**Comment by laurent22** [comment]
Makes sense, thanks for the report, I'll take a look.
