### ISSUE TITLE
Note editor does not have focus after switching notes

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#4476]
Joplin 1.7.10 on Windows 8

When in split mode I change to a different note by clicking on it in the list, I'd expect the editor to receive focus, but this doesn't happen. Not sure what is focused, but it's not the editor.

**Comment by laurent22** [comment]
The note list has focus and it’s expected because you might want use the keyboard arrows to move up and down the list, and that wouldn't work if the focus changes.

**Comment by roman-r-m** [comment]
Hmm, I guess on one had it makes sense but on the other hand I personally never look for a note by scrolling the list with arrow keys, I either use mouse to click or use search.
Maybe a config option could be added?

**Comment by roman-r-m** [comment]
Not fixed
