### ISSUE TITLE
Android app does not sync with Nextcloud

### ISSUE THREAD

**Issue by misterhsp** [laurent22/joplin#4479]
Joplin's Android app does not sync with Nextcloud. I get the error ==> Network request failed. Nothing more happens.

What can I do?

Thanks...

**Comment by roman-r-m** [comment]
Does your Nextcloud instance use self-signed certificate?

**Comment by misterhsp** [comment]
Yes and no, I self-signed and tried my own CA. The same for both.

**Comment by roman-r-m** [comment]
I suspect your own CA is essentially the same as self-signed for this purpose.

**Comment by misterhsp** [comment]
Yes, how do I get the sync to work?


Am 05.02.21 um 10:39 schrieb Roman Musin:

**Comment by roman-r-m** [comment]
Atm there's no way, some details here: https://github.com/laurent22/joplin/issues/4439

**Comment by roman-r-m** [comment]
Actually, with your CA you can try adding your root cert to your Android.

**Comment by misterhsp** [comment]
Already done, same problem.

...

**Comment by misterhsp** [comment]
This makes the Android app useless for me.

...

**Comment by misterhsp** [comment]
Is there a solution for the problem in sight?
Many other Android apps have an option to accept an unknown certificate.

...
