### ISSUE TITLE
Can't sync when pCloud's 2FA is enabled. 

### ISSUE THREAD

**Issue by xchan14** [laurent22/joplin#4480]
When I enable 2FA in pCloud, I receive an error when syncing. 

` Unknown error 2 (401): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>401 Unauthorized</title> </head><body> <h1>Unauthorized</h1> <p>This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.</p> <hr> <address>Apache/2.4.10 (Debian) Server at webdav.pcloud.com Port 443</address> </body></html> (Code 401)`

## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Elementary Hera

## Steps to reproduce

1. Enable 2FA in pcloud.
2. Ryn sync in Joplin
3. 

## Describe what you expected to happen
A webpage will open where I can enter the 6-digits code.

**Comment by tessus** [comment]
usability issues are discussed in the forum.

When using 2FA most systems require to use tokens instead of passwords. They can be created within the app that has the 2FA, in cour case pCloud. If not, it's another thing that pCloud screwed up.
