### ISSUE TITLE
Security flaw - encrypted notes can easily be recovered after using 'Edit in external editor'

### ISSUE THREAD

**Issue by huzibizi** [laurent22/joplin#4481]
Encrypted notes are currently converted to plain text for editing when using the 'Edit in external editor' feature. 

The file that is created is stored unencrypted. It is deleted when editing is completed, but can easily be recovered from the hard drive using basic recovery tools. 

_some possible solutions: export to encrypted zip file instead of plain text, export to pgp encrypted text, export to small encrypted virtual drive instead of main hard drive or even, disable the feature completely when encryption is enabled unless a setting is enabled in settings, or at least have a warning popup, giving the user a chance to go back, and not convert it to plain text.._

## Steps to reproduce

1. encrypt a notebook, then verify it's all encrypted.
2. make a note, right click on it, click 'Edit in external editor', and note down the file name created along with location.
3. right click again, click 'Stop external editing'.
4. Verify the file is deleted
5. Use free file recovery software such as Recuva to recover the file. 

## Describe what you expected to happen
I expected the edit in external editor feature to be disabled when encryption is enabled, or I would have at least expected a warning popup, prompting me to enable a special advanced setting to allow the feature. 

i don't think this feature should be enabled by default when using encryption, imo it is a security flaw, especially if the user's main hard drive isn't encrypted. I'm lucky mine was!

Thank you for the lovely software though, guys!

**Comment by JackGruber** [comment]
The E2EE encrypts only the data in the Sync target, but not the local ones!
