### ISSUE TITLE
[Joplin 1.7.11] search engine doesn't work accurate

### ISSUE THREAD

**Issue by bearzyj** [laurent22/joplin#4482]
## Environment

Joplin version: Joplin 1.7.11 (prod, darwin)
Platform: macOS
OS specifics:  BigSur 11.1 (20C69)

## Steps to reproduce

1. Create a folder naming "Python"(a subfolder of some other folder)
2. Create 20 notes under "Python" folder, and each notes title contains "python" and some unicode letters(Chinese characters), all notes body also contain many English letters and unicode letters
3. Issue1: When directly search "python", it cannot list all 20 items under "Python folder"
4. Issue2: When search "python <Unicode letters>", it cannot show any items(which is called a "Multiple word" search). I mean, it fond nothing.

## Describe what you expected to happen

Searching is the most important function for a notes APP, and in most time I think two kinds of searching are frequently used:
- `Single word` searching
- `Multiple words` searching
I am not sure if Joplin already support unicode searching?
Here are my expectation:
1) When searching "python", it shall list all items/lable/subject that contain "python"(case insenstive) 
2) When searching "python <unicode letters>", it shall list all  items/lable/subject that contain "python" and the "<unicode letters>"

Thanks.

**Comment by bearzyj** [comment]
Hi @laurent22 , seems you removed `bug` label from this subject.

I am trying to understand why, and from current document: https://joplinapp.org/#searching, it looks not achieving the expectation, like:

>For example, searching for cat will return all the notes that contain this exact word. Note: it will not return the notes that contain the substring - thus, for "cat", notes that contain "cataclysmic" or "prevaricate" will not be returned.

>dog cat - will return any notes that contain the words "dog" and "cat" anywhere in the note, no necessarily in that order nor next to each other. It will not return results that contain "dog" or "cat" only.

Totally understand you are very busy on taking care so many issues, requirements, refinements...

Just please kindly let me know, is the behavior mentioned in this subject expected? Or indeed need a refinement?

Thanks

**Comment by bearzyj** [comment]
Issue remains, also refers to: https://discourse.joplinapp.org/t/search-optimization-suggestions/7427/6

**Comment by batlittle** [comment]
I came up with the same issue. Hope this issue will be recognized as bug and be fixed soon.
