### ISSUE TITLE
Android and Ipad Sync not working with WebDAV

### ISSUE THREAD

**Issue by zork2112** [laurent22/joplin#4484]
Originally I had been syncing with OneDrive, but that was such a mess I gave up and switched to WebDAV.  I'm using the host Cloudamo.  Sync is working fine between my work & home Win10 machines, but is not working on either Ipad or Android.   

It has a partial sync - missing notes / notebooks / tags 

Checking Sync Config works for both.

Both logs show the error:
"Could not refresh lock - cancelling sync.  Error was: "Error lock has expired" Code: Lock Expired"

## Environment

Joplin version: 1.7.5 
Database v34
Platform: Android
OS specifics: Version 9 

Joplin version: 10.7.2
Database v34
Platform: Ipad
OS specifics: version 13.7

## Steps to reproduce

1. Set up sync parameters 
2. Tested sync connection
3. Ran sync - 

## Describe what you expected to happen
Sync to complete.

**Comment by zork2112** [comment]
Turns out it was the WebDAV host.  Switched to DriveHQ and while it was a bunch of work getting everything switched over, it finally is syncing.

**Comment by l-ucky** [comment]
I also use cloudamo. Has this switch resolved the issue still?

**Comment by zork2112** [comment]
It has been working very well.  The only issue I've come across is that on one occasion the database for one install has entries in the deleted_items that don't exist on the sync target and when I try to sync it bombs.   I've gotten around this by using DB Browser for SQLLite and opening the offending install database and manually deleting these items.  I'm not sure if there are any downstream effects for this, but hopefully not.  My hypothesis is that the items were deleted by another install and did not propagate correctly.
