### ISSUE TITLE
docs: 404 for URL "joplinapp.org/spec/server_sharing/"

### ISSUE THREAD

**Issue by NGenetzky** [laurent22/joplin#4485]
## Environment

- documentation website

## Steps to reproduce

1. Oen docs: [https://joplinapp.org/spec/server_sharing/](https://joplinapp.org/spec/server_sharing/)

## Describe what you expected to happen

> 404
> 
> File not found
> 
> The site configured at this address does not contain the requested file.
> 
> If this is your site, make sure that the filename case matches the URL.
> For root URLs (like http://example.com/) you must provide an index.html file.
> 
> Read the full documentation for more information about using GitHub Pages. 

## Logfile

NA

**Comment by rxliuli** [comment]
So, 2 weeks have passed, is there any progress?

**Comment by NGenetzky** [comment]
This should be a quick fix. Could someone take a quick look?

**Comment by NGenetzky** [comment]
Confirmed Fixed. Thanks @roman-r-m
