### ISSUE TITLE
Joplin not connecting with nextcloud on ubuntu localhost through ipadOS or Android

### ISSUE THREAD

**Issue by patwards** [laurent22/joplin#4487]
I have setup nextcloud on Ubuntu 20.04 on a mac through parallels. I have installed self-signed certificate on Apache. Joplin is installed on the mac and it works perfectly fine through https.
I also tried connecting through another MacBook on the network by installing Joplin and connecting to the nextcloud on ubuntu and it works fine.

The issue is that I am not able to connect Joplin from Android phone or iPad. I have used exactly same URL that I have used on Mac where it is working. I have installed the self-signed certificate on Android and iPad and the https is working on both devices. I am able to access Nextcloud through web browser on both devices.

Whereas the error message on both mobile devices is same as follows:

"Error: Please check that the URL, username, password, etc. are correct and that the sync target is accessible. The reported error was:
Network request failed"

Steps to reproduce:

1. Install and setup Nextcloud (nextcloud-19.0.6) on Ubuntu 20.04 with Apache and self signed certificate installed.
2. Install self signed-certificate on Android and iPad and test that the url https://192.168.1.XXX/nextcloud works fine
2. Install Joplin on Android and iPad
3. Setup as WebDav
4. URL: https://192.168.1.XXX/nextcloud/remote.php/dav/files/nextcloud/JOPLIN (This is exactly as shown in Nextcloud settings with JOPLIN folder added at the end

## Environment 1

Joplin version: 1.7.5 Database v34
Platform: Android
OS specifics: Oxygen OS 10.0.1 on OnePlus

## Environment 2

Joplin version: 10.7.2 Database v34
Platform: iPAD
OS specifics: iPadOS 14.4

## Steps to reproduce
1. Install and setup Nextcloud (nextcloud-19.0.6) on Ubuntu 20.04 with Apache and self signed certificate installed.
2. Install self signed-certificate on Android and iPad and test that the url https://192.168.1.XXX/nextcloud works fine
2. Install Joplin on Android and iPad
3. Setup as WebDav
4. URL: https://192.168.1.XXX/nextcloud/remote.php/dav/files/nextcloud/JOPLIN (This is exactly as shown in Nextcloud settings with JOPLIN folder added at the end

## Logfile

![log](https://user-images.githubusercontent.com/36577889/107125848-14ee0300-68a4-11eb-90f4-0a1249718834.png)

**Comment by JackGruber** [comment]
The problem is the self-signed certificate.

There are already several issuses https://github.com/laurent22/joplin/issues/4225  https://github.com/laurent22/joplin/issues/4439 for the self-signed certificate on the mobile apps.

**Comment by patwards** [comment]
Hello, I checked both the bugs referred above but could not find a solution. can you suggest anything I can try to fix the issue please.

**Comment by JackGruber** [comment]
self-signed certificates currently not supported on the mobile apps.
You have to use certificates from a Android/iOS trustet authority like let's encrypt.

**Comment by patwards** [comment]
Lets Encrypt needs a registered domain, so I need to find alternative solution since I only intend to use this within home network and not public network.

**Comment by patwards** [comment]
The issue is not closed. Need Android/IOS to allow self-signed certificates.

**Comment by patwards** [comment]
Issue is open

**Comment by roman-r-m** [comment]
For Android it will be fixed in the next release.

**Comment by silo82** [comment]
Will this also be fixed on the iOS and MacOS app as well?

I've got my own (personal) CA that I trusted the root cert for in both iOS and MacOS, but both the iOS app and MacOS app refuse to accept the server certificate which was signed by my root CA.

**Comment by roman-r-m** [comment]
> Will this also be fixed on the iOS and MacOS app as well?

Maybe but not by me - I don't know a single thing about iOS/MacOS so can't help here.
