### ISSUE TITLE
WebDAV sync only supports Basic Auth, not Digest Auth

### ISSUE THREAD

**Issue by muelli** [laurent22/joplin#4488]
I'm trying to synchronise with a WebDAV server. The server implements Digest Auth, only, i.e. no Basic Auth, because it doesn't want to have passwords in clear text stored on disk.

## Environment

Joplin version: 1.7.11
Platform:  linux
OS specifics: 

## Steps to reproduce

1. set up WebDAV sync with Digest Auth
2.  see how it requests with basic auth
3. fail

## Describe what you expected to happen

I expected the synchronisation to just work.

This is [a](https://github.com/laurent22/joplin/issues/531) [known](https://github.com/laurent22/joplin/issues/3574) [issue](https://github.com/laurent22/joplin/issues/3785). But the obnoxious bot closes the issues.
I want to address a comment made [here](https://github.com/laurent22/joplin/issues/531#issuecomment-503361424):
> Implementing Digest seems quite complex and I'm not sure it makes sense to support it today? The connection should use TSL anyway and in this case it doesn't matter how the username and password are transmitted.

TLS is for securing the connection in transit (well, it doesn't, really, that's why protocols like SRP exist, but let's save that for another discussion). Digest Auth is, additionally, about protecting the password at rest. Also, TLS implementation may have flaws that leak their buffers (heartbleed, anyone?) or accept malicious certificates.

This is an Electron app, no? It seems that Electron supports Digest Auth natively: https://www.electronjs.org/docs/api/net
There seems to be a Javascript implementation, too: https://github.com/perry-mitchell/webdav-client

**Comment by muelli** [comment]
:-/

**Comment by muelli** [comment]
:(

**Comment by jeff47** [comment]
I don't understand why a more secure method of authentication appears to not even be considered.  @laurent22:  Is it a complex programming issue, or a prioritization issue?  Just curious why this issue has been opened and closed a few times with no comments from dev.
