### ISSUE TITLE
iOS app, issue with URLs which contain special characters

### ISSUE THREAD

**Issue by MirrorDM** [laurent22/joplin#4494]
First, thanks for developing such a great app! Recently I have met an issue with URL on iOS app, the details are as following:

## Environment

Joplin version: 10.7.2
Platform: iOS
OS specifics: iOS 12.4.1

## Steps to reproduce

1. Create a note in Joplin app, which contains an URL which has special characters. For example `https://telegra.ph/马斯克开房聊天中外网友在线求码Clubhouse一夜火遍全球-02-07`
2. Exit the edit mode, now the URL link turns into blue color, shows it is clickable
3. Click the link, the link is opened in Safari. If we observe the URL that Safari gets, we found that the URL is wrongly parsed
4. In Joplin, if we select the URL, copy it, and paste it into Safari's address bar, the link leads to correct place

This issue happens in both mode:
- links form, such as `[title](url-with-special-char)`
- plain text form, such as `url-with-special-char` which turns into clickable in normal mode

URL with special chars, no matter encoded or not, would trigger this issue. For example:
- Direct one: `https://telegra.ph/马斯克开房聊天中外网友在线求码Clubhouse一夜火遍全球-02-07`
- Encoded one: `https://telegra.ph/%E9%A9%AC%E6%96%AF%E5%85%8B%E5%BC%80%E6%88%BF%E8%81%8A%E5%A4%A9%E4%B8%AD%E5%A4%96%E7%BD%91%E5%8F%8B%E5%9C%A8%E7%BA%BF%E6%B1%82%E7%A0%81Clubhouse%E4%B8%80%E5%A4%9C%E7%81%AB%E9%81%8D%E5%85%A8%E7%90%83-02-07`

Thanks :-)

**Comment by laurent22** [comment]
Does it work if you try with a different browser? For me it works fine with your URL but I use Vivaldi.

**Comment by MirrorDM** [comment]
Hi Laurent, Thanks for your reply. Just to confim, do you mean the Vivaldi on iOS? Because this issue happens on iOS (I have tried with my Windows PC, and it works just fine).

On iOS 12 I cannot set the default browser (it is supported after iOS 14, [reference](https://support.apple.com/en-us/HT211336)). So If I want to use another browser, I need to manually copy the URL in Joplin, and paste it into address bar. As I mentioned before, if I manually copy it, it works just fine with Safari.

Thanks ,and hope the above information helps :)

**Comment by MirrorDM** [comment]
Just tried another device with `Joplin 10.7.2` on `iOS 13.1.3`, and it can reproduce the issue with the same URL

**Comment by pompeiifreckles** [comment]
Hey I think I understand the issue here, I believe this is due to the two unit codes i.e. the non ASCII codes (less used Chinese characters) introduce ambiguities during uri encoding in encoded Unicode text (url).

Can you point out the files associated with normalizing functions that are responsible for this, it would make it easier.

**Comment by innkuika** [comment]
I've reproduced your bug, will work on it
