### ISSUE TITLE
Unable to select File name for Markdown Export

### ISSUE THREAD

**Issue by danielfomin96** [laurent22/joplin#4495]
When exporting a single note to a .md file I get no possibility in the file explorer to specify the file name.
This results in a failure to create the file.
[File explorer](https://paste.pics/49b0d9e890f48564b242856cdb0fe881)

Issue is only with MD.

## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Arch Linux, i3-wm with sddm

## Steps to reproduce

1. Create a new note in the graphical app
2. Right click on the file name
3. Specify Export -> MD - Markdown

## Describe what you expected to happen
Ability to specify the file name, so that the file can be saved on the filesystem.

## Logfile
```
Export result:  {warnings: Array(0)}
```

**Comment by laurent22** [comment]
This is by design because when you export as Markdown, the resources and plugin assets also need to be exported, so in fact the app is asking you to specify a directory, not a file. The filename will be set automatically based on the note title.
