### ISSUE TITLE
[Feature Request] Evernote style check boxes

### ISSUE THREAD

**Issue by navdeepio** [laurent22/joplin#450]

**Comment by EBendinelli** [comment]
If you are talking about checkboxes in the body it's already supported using markdown: https://blog.github.com/2014-04-28-task-lists-in-all-markdown-documents/

`- [  ] //for an empty one`
`- [X] //for a checked one`

The checkboxes can also be ticked in the layout view.

If you are talking about reminder that's a completely different thing and it's indeed not supported.

**Comment by navdeepio** [comment]
can we not instantly turn markdown to it's output? like in typora https://typora.io/

**Comment by foxmask** [comment]
@navdeepio you should make a request by issue :)
otherwise every topics could risk to be mixed

**Comment by navdeepio** [comment]
ok, i'll close this one then
