### ISSUE TITLE
The button « Spell checker » still visible when it’s disabled

### ISSUE THREAD

**Issue by dot-clear** [laurent22/joplin#4500]
The button « Spell checker » still visible when it’s disabled

## Environment

Joplin version: 1.7.11
Platform: Windows
OS specifics: Win10

## Steps to reproduce

1. CTRL + , (Go to Options)
2. Uncheck “Enable spell checking in Markdown editor? (WARNING BETA feature)”
3. Reload Joplin and take a look here : 
![Spell Checker](https://user-images.githubusercontent.com/77929203/107276913-98962400-6a4b-11eb-9635-55417ca5e33a.png)

and here : 
![Spell Checker 2](https://user-images.githubusercontent.com/77929203/107272824-2c64f180-6a46-11eb-915d-71d8d3ab064c.png)

## Describe what you expected to happen

Not show any "Spell checker" button when it's disabled.

**Comment by laurent22** [comment]
This as designed, the button is there to easily switch spell checking on and off.

**Comment by dot-clear** [comment]
If always show, I'd rather a lighter icon as alarm or note properties.

**Comment by dot-clear** [comment]
If it's always visible, I'd rather a lighter icon as alarm or note properties.

**Comment by dot-clear** [comment]
If it's always visible, I'd rather a lighter icon as alarm or note properties. Or added to the toolbar editor.

**Comment by felixduvallet** [comment]
As a new Joplin user, I have to say it was very confusing that the "enable spell checker button" didn't actually do anything. I had to go enable another option before this actually did what it said, so in a way that UI element is lying to the user.

It's definitely great to keep the selector (and language choice) easily accessible, but I agree that graying it out would make it much more clear what is actually turned on.
