### ISSUE TITLE
Desktop: tags created via data API aren't visible in GUI

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#4501]
```
Joplin 1.7.10 (dev, win32)

Client ID: ec05e9c323374da0b8068f3494cb3251
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: 4a9d8033f (dev)
```

* Create a tag via the API: `await joplin.data.post(['tags'], null, { title: 'test-tag'});`
* Open any note, open add/remove tags dialog
* Expect to see newly created tag but this isn't the case.

From a cursory glance it seems that tags shown in GUI come from `await Tag.allWithNotes();` which calls `SELECT * FROM tags_with_note_count`.
Apparently this view isn't updated because newly created tag isn't associated with any notes.

**Comment by roman-r-m** [comment]
Go away, bot

**Comment by laurent22** [comment]
Currently we don't show tags that are not associated with any note. It's been discussed a few times and recommended workaround is to add a note to the tag, so that it shows up in the sidebar.

**Comment by roman-r-m** [comment]
Ok, not intuitive at all but as long as it's expected, fine with me.
