### ISSUE TITLE
Vertical image is displayed rotated

### ISSUE THREAD

**Issue by Stebeber** [laurent22/joplin#4503]
## Environment

Joplin version: 1.7.5 | Database v34
Platform: Android
OS specifics: Android 10 - MIUI 12.0 (Xiaomi Redmi Note 9 Pro)

## Steps to reproduce

1.  Create task/note
2.  Add image
3.  Save and display task

## Describe what you expected to happen

Corect orientation

**Comment by StephanBehm** [comment]
![Screenshot_2021-02-09-12-57-51-137_net cozic joplin](https://user-images.githubusercontent.com/6450906/107362050-8c0bdd00-6ad8-11eb-8ea0-044fa5692f01.jpg)

**Comment by dz2106** [comment]
![image](https://user-images.githubusercontent.com/36925633/118736128-cb507500-b80f-11eb-9ac9-12ec4f4b0368.png)
I was unable to recreate the issue on desktop

**Comment by dz2106** [comment]
![image](https://user-images.githubusercontent.com/36925633/118736377-6b0e0300-b810-11eb-8921-1b9cdbedefaf.png)
Unable to recreate issue on iOS

**Comment by dz2106** [comment]
If no one can recreate the issue, it is best to close it. I do not have an Android device to test on
