### ISSUE TITLE
Search / Note & Notebook Selection - Bugs and Suggestions

### ISSUE THREAD

**Issue by pier-da** [laurent22/joplin#4504]
*Listing this issue as a bug as I believe at least the first few points below are such. The rest are suggestions that I think would make the search function more intuitive as behaviour would follow expectations, and also smoother/faster with the addition of various amendments. 

**Search / Selection Bugs**

1. When searching via the search text entry box, and the Goto Anything search, the behaviours differ and using them is unintuitive as a result. In the Goto Anything, if you search for a word and select one of the results in the dropdown, the corresponding note is opened, the note highlighted in the search results pane and the notebook/subnotebook is opened and highlited in the notebook pane. This behaviour is expected. However, when searching from the search text entry box, selecting a result does not open/highlight the corresponding notebook/subnotebook. This would be confusing to those who have many similar notes and making it like the Goto Anything behaviour would allow a quick visual check as to the location of the selected note.

2. When searching via the search text entry box, the searched text in the editor panes is only highlighted when in the split view mode, not when in wysywig only mode. I imagine many like myself do not use the split mode, so lose this functionality.

3. Some notes can look empty in wysiwyg view, but actually contain info that is only seen when clicking on the split view. One example of this is a mermaid Gantt chart, it appears blank when the note is selected in the search results pane, but if you press the split view button, the Gantt chart and code appears. This may confuse users and cause notes to be deleted / info lost. 

**Search / Selection Suggestions**

- Show notebooks in the search results pane. It would be very useful to type the first few letters of a notebook to quickly navigate to it. It may be buried in subnotebooks for example. Clicking on the search result could open the corresponding notebook/subnotebook in the notebook pane and select the first note if necessary. 

- The Go To Anything search is powerful, but I did not know about it until I read a post here. Perhaps an icon button to open it would increase usability.

- Search highlight colours are: red in the search results pane, orange in the markup pane and orange in the wysiwyg pane. Can these be standardised to a single colour and preferably a more used highlight colour for contrast (i.e. FFFF00)

- When searching for a particular string in a long note, you have to search twice. Once in the search text box, then you have to press CTRL+F and retype in the string to search within the note. A suggestion, similar to other note apps would be to jump to the first instance of the string in a note when it is clicked on in the search results pane. The find and replace dialogue could be automatically opened with the field already filled with the search text, so the user just has to press find to search for the next instance.

- When searching via the search text entry box, results are listed in realtime only when the full word matches. Otherwise you need to keep typing * after typed text to see results. Can this requirement be removed, so as you type, results are updated in real time. Again, many users are probably not aware how to / the need to use wildcards.

- The selected note in the notes / search results pane is light grey, while the selected notebook is dark grey. When rolling over notes in the notes / search results pane, notes are highlighted in light blue, when doing the same in the notebook pane, it is a medium grey. Could this be standardised so the behaviours are the same, that colours are similar across both panes, and the colours are more contrasting (i.e. can be hard to detect the three various grey colours on the notebook pane)

Thanks for reading and great app!

## Environment

Joplin version: Joplin for Desktop 1.7.11
Platform: Windows 10
OS specifics: 1920x1080

**Comment by X-hood** [comment]
I have the same confusion about the search function. That is, after global search, you need to search in the current note again to locate keywords. In the global search, after selecting a note, can the cursor be automatically positioned to the keyword. Or add a new button "search for it in this note".
The function of "Goto Anything" is similar.
