### ISSUE TITLE
Joplin not opening but immediately crashing in Android 4.3 & 4.4

### ISSUE THREAD

**Issue by jdofo** [laurent22/joplin#4507]
First of all, thank you very much for such interesting and potential replacement of Evernote :)

Last time I installed Joplin app (probably around summer 2020) in my Android 4.3 and 4.4 mobile phones, it was working fine. 

However, I decided to update Joplin few days ago (planning to sync my computer and phones through "file sync" + Syncthing) but, unfortunately, it doesn't work anymore in none of my phones. After installing latest update, it simply doesn't allow me to even open the app: the screen gets white but after a while, there is a "CTD" message - "Joplin application stopped unexpectedly". I tried to uninstall and install from scratch several times, but encountering the same crashing behaviour.

I know these are nowadays considered "old" mobile phones, but Joplin app specifies as requirement: "Android 4.1 and newer versions". Is planned obsolescence also arriving to open-source and free software? If so, future is becoming even darker...

Thank you very much in advance! Cheers

**Comment by philip-n** [comment]
Came here for the same reason. This seems to be a known bug in an underlying component that Joplin uses (and that component might incorrectly have claimed it still supports 4.1 while in fact it does not), see https://github.com/laurent22/joplin/issues/4057

So I guess that there will be no fix, unfortunately. I just opened https://github.com/laurent22/joplin/issues/4585 to prevent other users from falling in the same trap. Assuming that there are other people who still use Android 4.x, that is :)
