### ISSUE TITLE
The order of notes in Android client is inconsistent with that in win client

### ISSUE THREAD

**Issue by QuinnTian** [laurent22/joplin#4510]
## Environment

Joplin version: 1.7.11
Platform: windows 10
 &
Joplin version: 1.7.5
Platform: Android 8.1

## Steps to reproduce

1. Create three notes in the notebook of win client, as shown in the figure
![image](https://user-images.githubusercontent.com/29975541/107499182-9b218680-6bcf-11eb-972c-42b634f0749e.png)
2. Drag to change the order of notes, as shown in the figure
![image](https://user-images.githubusercontent.com/29975541/107499418-ea67b700-6bcf-11eb-8f80-33e8a8e35021.png)
3. Click sync
4. Open the Android client and click sync. The order of opening notebook to view is inconsistent with that of win client. As shown in the figure
![image](https://user-images.githubusercontent.com/29975541/107500183-d83a4880-6bd0-11eb-84f6-d1e16fd1ec5d.png)

## Describe what you expected to happen
The order of notes in win client list should be consistent with that of Android client.

**Comment by dosoft** [comment]
Still be the issue on the latest Android client

**Comment by roman-r-m** [comment]
Not really a bug, it's just that note sort settings (like most other settings) are not syncing between devices.
