### ISSUE TITLE
Complex (Ligature-Using) Scripts Not Typable

### ISSUE THREAD

**Issue by ng4mf** [laurent22/joplin#4513]
When I use a script that uses ligatures, such as Devanagari, the result is not intelligible.

![image](https://user-images.githubusercontent.com/6548274/107566236-a2866700-6bb2-11eb-9cd9-9b401b961f21.png)
Also, all of क््् is treated as one single character instead of what appears to be four, the original क plus three copies of  ्  (क्््र is thus two characters, with the little forward-slash-like line in the bottom right being the र part of the ligature).

This seems to stem from the ्  character getting turned into three copies of itself each time it is typed.

I've only tried with Devanagari, but I know most, if not all, Brahmi-derived scripts have this type ( ् ) of half-letter marker, so I think it probably affects many others.

## Environment

Joplin version: 1.7.11
Platform: Linux 5.4.0-65-generic
OS specifics: Lubuntu 20.04

## Steps to reproduce

1. Go to a Joplin note
2. Type in क ् र
3. The result should be क्र, but instead we get क्््र

## Describe what you expected to happen
There are set ways in which particular sets of characters are supposed to combine in special ligature characters, and that doesn't seem to happen. In particular, the use of the "half-letter" marker, i.e. ्, behaves oddly (i.e., each typed instance turns into three copies)

**Comment by CalebJohn** [comment]
I'm assuming that you're using the markdown editor. Can you still reproduce this in the WYSIWYG editor (the rich text editor)?

**Comment by ng4mf** [comment]
Yes, the above screenshot was with the Markdown editor. I just tried with the WYSIWYG editor and got the same undesired result, though. Each ् gets turned into three copies of itself, but in the WYSIWYG editor, these three copies are not treated as a single character. That is, a [backspace] will delete only one copy instead of all three with a single key press.

**Comment by CalebJohn** [comment]
@ng4mf Do you mind playing around with the font settings under Tools -> Options -> Appearance? It's possible that this issue will be resolved by changing to a font that better supports ligatures. I am thinking that the editors that Joplin uses (CodeMirror, TinyMCE) don't properly support ligatures, so an actual solution for this might get complicated.

**Comment by ng4mf** [comment]
Sure, I'll give it a shot later and report back what I find. Like you suggested, this might stem from some problem in another library/tool that Joplin uses. I've noticed the exact same or similar problem in other applications; e.g., Brave browser.

**Comment by CalebJohn** [comment]
You can use [this link](https://codemirror.net/demo/theme.html) to test the upstream version of the Markdown editor. You should also try enabling spellcheck for the markdown view (Tools -> Options -> General). I'm not sure if it will help, but it's worth a try.

**Comment by ng4mf** [comment]
Hm, so I think this is linked not to the editor, but some underlying framework?
I tested the link you suggested in Brave, Chrome, Chromium, and Firefox. I can use ् correctly in Firefox but not the other three. I don't know if I'm grasping at straws but does Joplin use some library for text-rendering that Chromium also does, since all three of the non-usable browsers derive from Chromium?

**Comment by CalebJohn** [comment]
Thank you for being so detailed in checking this out.

> I'm grasping at straws but does Joplin use some library for text-rendering that Chromium also does, since all three of the non-usable browsers derive from Chromium?

Unfortunately yes, Joplin is built on Electron which is built on top of the Chromium engine. 

It seems that this is a deep issue. I'm not confident that this will be possible to fix on the Joplin end. You can fortunately use the external editor feature of Joplin (with an editor that supports Devanagari) to write in Devanagari and  I think the rendering should work.

**Comment by ng4mf** [comment]
Is there possibly some other common library or framework in addition to Electron?

On the Electron repo it says [Atom](https://github.com/atom/atom) is also based on Electron. Just to double check, I installed Atom and can successfully use ्, so I'm not sure this is an Electron issue.

**Comment by CalebJohn** [comment]
That's very encouraging, do you mind giving vscode a try as well? I can't seem to find if atom has an easily available editor exposed, but I know that vscode (also based on electron) has monaco which should be easier to use.

**Comment by ng4mf** [comment]
Good call - vscode also worked. If I understood you correctly, until this is resolved somewhere upstream I can use vscode as my editor for Joplin, right?

CodeMirror 6 in Brave, however, did not work, which still leaves the question of where this issue is stemming from. I can try to open this issue further upstream to try to figure out where the problem is. Before we close this issue out, though, could you please let me know if there are any other common libraries between Joplin and chromium that you're aware of?

**Comment by CalebJohn** [comment]
> until this is resolved somewhere upstream I can use vscode as my editor for Joplin, right?

Yes you can, there is even a plugin for vscode that allows you to use Joplin entirely from within vscode. You're also free to use any other editor that works for you (e.g. Atom).

The editor that Joplin uses (CodeMirror 5) leaves text rendering completely to the browser. Which explains why it renders correctly on Firefox but not on anything built with chromium. I'm guessing that Atom and VScode have integrated their own text rendering on top of Electron (chromium) in order to support more languages. 

> could you please let me know if there are any other common libraries between Joplin and chromium that you're aware of?

Not that I know of, the core rendering of Electron is built on top of chromium, so in a sense everything is shared. It seems to me that this is a core issue with the chromium text rendering engine.

**Comment by ng4mf** [comment]
Alright, thank you so much for all the help and suggestions! I'll open a bug upstream to see if we can get this fixed for downstream applications.

**Comment by CalebJohn** [comment]
@ng4mf 

One thought i had, do you mind checking the Monaco editor with chrome (or similar)? This is mostly for my curiosity

https://microsoft.github.io/monaco-editor/

**Comment by ng4mf** [comment]
Sorry for the delayed response.
Yes, Monaco worked in both chrome and brave! That was a good call, what made you think of it?
I suppose Monaco is doing font-rendering independent of whatever the chromium default is, then.

**Comment by ng4mf** [comment]
Oh, I see now. Monaco is the vscode editor, and since it worked in vscode it makes sense that it'd also work independently so long as vscode wasn't changing some property of the editor in the course of integration. I'll try enabling monaco inside joplin.

Thank you!
