### ISSUE TITLE
[Bug] Tray icon behavior and context menu adjustments

### ISSUE THREAD

**Issue by ParticleMon** [laurent22/joplin#4514]
For the benefit of those who enable the "Show tray icon" option:

1. Make left-clicking the tray icon show/hide the window instead of opening a context menu (with the options "Open Joplin" and "Quit"). This, in part, would remove a superfluous step required to show the window from the tray icon.

2. Remove "Open Joplin" from the (right-click) context menu.

Also:
3. Correct the wording of the option "Start application minimized in the tray icon" to "Start application minimized in the tray."

Joplin version: 1.7.11
Platform: Linux
OS specifics: Mint 20.1

**Comment by ParticleMon** [comment]
Bump.

**Comment by ParticleMon** [comment]
Bump.

**Comment by maxim-kukushkin** [comment]
It seems like it was partially implemented at some point (left click opens/closes main window), while right click opens "Open / Quit" context menu.
However, I see a strange behavior. I have 2 computers running exact same Linux (Arch Linux latest updates) with the same Desktop Environment (Plasma), same version of Joplin installed the same way.
- On one computer it follows the new behavior (left click to open the main window)
- On another computer it still has the old behavior (left click opens the context menu)

I fail find any difference in settings or elsewhere between the two setups.

**Comment by maxim-kukushkin** [comment]
The issue it still there. Please, don't close it

**Comment by maxim-kukushkin** [comment]
bump

**Comment by ParticleMon** [comment]
Indeed, what is the point of stale bot and auto-closing requests?
Why implicitly promote cluttering up unresolved tickets with a potentially endless series of "Bumps"?

Why not simply leave tickets open?

**Comment by maxim-kukushkin** [comment]
Well, I would totally understand it if maintainers said "we won't implement/do this. If community wants, you can do it yourself" and kick off the stale bot. In this case yes, totally makes sense to close if no updates. However, I don't see how "ignore" == "stale"

**Comment by maxim-kukushkin** [comment]
> Of course there are nuances in handling tickets. But without a specified reason, which is still lacking here, it does seem justifiable to just close it.
> 
> For whatever reason, this was labeled a bug temporarily. So, whether it's an enhancement or a bug doesn't matter to me. That's the dev's prerogative. But if I need to change it or anything else, just let me know.

See if you find the problem that I described relevant to you. I.e., it looks like in the latest version the behavior that you originally requested exists. But as I said it doesn't seem consistent across machines. So if you feel comfortable, the description can be changed to reflect this issue and the ticket can be changed to a Bug.
It's fine if not, I believe I can raise a separate bug for it myself. In which case you can close or leave it for the stale bot to collect, I won't be "bumping" anymore (it seems like it doesn't work anyway - despite all the comments, the "stale" label is still there)
