### ISSUE TITLE
Windows desktop app won't sync! Error: GET info.json: Unknown error 2 (502)

### ISSUE THREAD

**Issue by noteb00k** [laurent22/joplin#4518]
Title says most of it. Basically my desktop app won't sync at all with my storage provider (wöelkli) and keeps throwing me this error everytime I try to:
Error: GET info.json: Unknown error 2 (502)

In one of these attempts, it gave me this variation of the same error:
`Last error: Error: GET info.json: Unknown error 2 (502): <html> <head><title>502 Bad Gateway</title></head> <body bgcolor="white"> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx</center> </body> </html>
`

## Environment

Joplin version: 1.7.11 (honestly I am not so sure is a version problem, first thing I tried to do was downgrade the app in case it was a bug of the last release but in the version 1.6.8 (which is the one I've been using up to now before updating to the current one) still throws the same error)
Platform: Windows 10 Enterprise 2016 LTSB, **portable** desktop app
OS specifics: 64 operating system, x64-based processor. My cloud storage service to sync is wölkli (ppp.woelkli.com).

## Steps to reproduce

0. (Important because it may have something to do with it, but I am not completely sure) Basically I noticed this problem started happening after I tried to launch another instance of Joplin portable to test if I could run two different instances at the same time - i wanted a "school" notebook and a "personal" notebook where tags didn't get mixed; but it didn't launch at all so I didn't pay any mind. However I noticed this bug started happening shortly after I did this.
1. I launch the desktop portable app
2. it attempts to synchronize with the cloud storage
3. It throws:
```
 Completed: 11/02/2021 15:13
Last error: Error: GET info.json: Unknown error 2 (502):
```
And it doesn't sync anything. The android app is syncing perfectly well (same storage provider and everything), but the desktop one isn't sending or receiving any data at all.

## Describe what you expected to happen
Wanted it to synchronize my notebook and fetch all the notes I've written on my android app of course.

## Logfile
log from the development tools's console:
[console-1613061807991.log](https://github.com/laurent22/joplin/files/5966960/console-1613061807991.log)

I'll be attaching the log.txt entries since the February the 10th since it's the day this issue started. If more of the previous log is needed, please tell me.
[log02102021.txt](https://github.com/laurent22/joplin/files/5966973/log02102021.txt)

**Comment by noteb00k** [comment]
anyone?

**Comment by sykoram** [comment]
Same issue here:
I am also using wölkli.com NextCloud and have the same error (in desktop app): 
`Last error: Error: GET info.json: Unknown error 2 (502):`

When I click "Check synchronisation configuration" in settings, it says `Success! Synchronisation configuration appears to be correct.`

No issues with mobile app so far, it synchronizes successfully.

**Comment by sykoram** [comment]
Update: I kinda fixed the issue!

1. I've created a new folder ("joplin-data") in NextCloud,
2. (backed up all the Joplin data,)
3. copied all files and folders (some are hidden!) from the original "Joplin" to this new folder,
4. and updated the synchronisation URL in both clients.

Both clients synchronize perfectly now, and the "Unknown error 2 (502)" has disappeared!

**Comment by poopie-head** [comment]
> 
> 
> Update: I kinda fixed the issue!
> 
>     1. I've created a new folder ("joplin-data") in NextCloud,
> 
>     2. (backed up all the Joplin data,)
> 
>     3. copied all files and folders (some are hidden!) from the original "Joplin" to this new folder,
> 
>     4. and updated the synchronisation URL in both clients.
> 
> 
> Both clients synchronize perfectly now, and the "Unknown error 2 (502)" has disappeared!
> 
> Edit: I don't really know where the issue was, but this somehow works.

Also not sure why, but this worked for me.  
Just create a new folder in Nextcloud, then `Right-click old folder > Move or copy` then choose your target folder and hit Copy. Then update the sync URL in your joplin instances.
Notes are now syncing.

**Comment by ippocratis** [comment]
Enable encryption on client
Delete the info.json on server
Resync
Select the banner saying the server has to be updated on the client
Resync

Idk where this comes from
Corrupted info.json ?
Key pair missmatch?
File permissions? (Most likely)
Anyway deleting and re creating the info.json fixed it for me

**Comment by guidugli** [comment]
+1
Problem happened today after some automatic upgrade. Instead of deleting the info.json, I renamed it. After restarting the app and synchronizing, it did its magic and all is working fine now. Ran a diff betwenn the old and new info.json and they are identical. Permissions are also the same. Have no clue why this happens, but the work-around listed by ippocratis works.
