### ISSUE TITLE
A few things to improve: Sorting folders, alarm for reminders

### ISSUE THREAD

**Issue by Minh049** [laurent22/joplin#452]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

First of all, great program! I love the simplicity and encryption while still being useful!

I've noticed a few things, I think would make an improvement:

1. Make folders sortable. I consider this very important. I only have a few folders yet but they are already messy since they are not sorted at all. This could be either solved by moving them around manually or by just sorting them alphabetically in a automatic way. I'd be happy with either one.
2. The functonality of the to-do lists is almost enough already. The only thing I find difficult is to know what I need to do next. The overview under "Synchronisation status" isn't really helpful since it is a) at the wrong place (namewise) and b) unsorted. A list or something similar that shows all active to-dos (active = has reminder in the future). A short-term solution would be already to make the upcoming alarm lists under "Synchronisation status" at least sorted.

Thank you very much and please continue with your great work!

**Comment by foxmask** [comment]
duplicate with #206,  #282
