### ISSUE TITLE
Menu commands greyed out (in WYS. editor)

### ISSUE THREAD

**Issue by ajay-gh** [laurent22/joplin#4521]
Many menu commands in the Edit menu are greyed out when the WYSIWYG editor is selected.
However the same commands (undo, bold, ect.) can still be invoked by a simple keystroke.
In other words, the commands are available and they work. Seems a minor, but misleading 
to the user. In particular since s/he does not necessarily know or guess that the keystrokes 
work.

## Environment

Joplin version: 1.7.10
Platform: osx
OS specifics: irrelevant 

## Steps to reproduce

1. start WYSIWIG editor
2. open menu
3. look !

## Describe what you expected to happen
n/a

## Logfile
irrelevant

**Comment by ajay-gh** [comment]
still the same problem

**Comment by ioloughlin89** [comment]
I have same issue also. Even for blank notes as you can see from the image below.  I wouldnt mind using keystrokes as a workaround - but these often dont work either.  ctrl+i , ctrl+b, ctrl+k as well as cut/paste operations work. Everything else doesnt work on the ui or on the shortcut level.

https://imgur.com/7IV2Ie0
