### ISSUE TITLE
iOS edit mode needs one more line of padding/margin above keyboard.

### ISSUE THREAD

**Issue by wishinghand** [laurent22/joplin#4523]
## Environment

Joplin version: 10.7.2
Platform: iOS, iPhone 12 Pro Max
OS specifics: 14.3 

## Steps to reproduce

1. Create a new note, or open any existing one.
2. Type in enough text to fill the whole edit screen.
3. The keyboard covers up the bottom line of text. The cursor can also be located here, text can be entered, all without being visible.

## Describe what you expected to happen
Be able to easily read the entire note when editing.

## Logfile
Will have to figure this out after work.

**Comment by CalebJohn** [comment]
Can you confirm if this is the same as #4226 and #3607? I'm pretty sure they're all the same but I would appreciate if you could check.

**Comment by wishinghand** [comment]
This is a duplicate of those, sorry. I was searching various keywords but didn't turn either of those up. I can close if those two are being tracked for the roadmap.

**Comment by CalebJohn** [comment]
No worries, I was only able to find them after manually scrolling through several pages.

Closed in favour of #3607
