### ISSUE TITLE
Empty note list panel does not scale with the note content panel

### ISSUE THREAD

**Issue by ProgramFan** [laurent22/joplin#4524]
As in the following image, the note list panel does not scale with the note content panel when the note list is empty.
<img width="735" alt="图片" src="https://user-images.githubusercontent.com/32396/107838901-3dfe1e80-6de3-11eb-83a6-10a142713365.png">
However, when the note list panel is not empty, it scales perfectly.
<img width="968" alt="图片" src="https://user-images.githubusercontent.com/32396/107838978-be248400-6de3-11eb-8c00-1021e00cb755.png">

## Environment

Joplin version: 1.7.11
Platform: macOS Big Sur
OS specifics: 11.2.1

## Steps to reproduce

1. Just create a new notebook without any notes
2. Try to enlarge the note list panel by dragging the right boundary
3. You will see the note list panel stops growing.

## Describe what you expected to happen

The note list panel grows when dragging the right boundary.

**Comment by jalajcodes** [comment]
I am working on this.

**Comment by jalajcodes** [comment]
@roman-r-m I fixed the issue and as I can't make a PR until #4627 is merged, Can I start working on another issue?

**Comment by jalajcodes** [comment]
@roman-r-m I fixed the issue and as I can't make a PR until #4627 is merged, is it alright if I start working on another issue (something more complex) ?

**Comment by roman-r-m** [comment]
> @roman-r-m I fixed the issue and as I can't make a PR until #4627 is merged, is it alright if I start working on another issue (something more complex) ?

go ahead

**Comment by siddharthmagadum16** [comment]
Hi, I have resolved this issue. Can I make a PR?

**Comment by roman-r-m** [comment]
sure
