### ISSUE TITLE
new issue when closing app

### ISSUE THREAD

**Issue by lwb52** [laurent22/joplin#4525]
on latest Mojave, suddenly when closing am getting the attached JavaScript ”uncaught exception" error message:
![Screen- 2021-02-13 at 12 14 27 AM](https://user-images.githubusercontent.com/22728371/107845542-1ed6a100-6d91-11eb-91c6-30281c4bf64f.jpg)
did reinstall app, given the message that something was ”destroyed," but no relief…

**Comment by CalebJohn** [comment]
Can you try disabling your plugins and running again?

**Comment by lwb52** [comment]
Yes, and the problem went away.
So, re-tested app with every plugin individually active (turn_off>restart_to_enable >quit_to_obesrve; lordy that’s repetitive)—again, no more problem.
Ren-enabled /all/ plugins together—yet again, no problem!

Is that likely to be a cache effect? 

Thanks for the suggestion/reminder…

**Comment by CalebJohn** [comment]
My guess is that it's maybe an edge condition from having multiple plugins enabled. 
btw you're [not the only one with this problem](https://discourse.joplinapp.org/t/change-notes-back-and-forth-if-you-see-this/14812)

Do you mind listing all the plugins that you have/had enabled? It might help in trying to reproduce this.

**Comment by lwb52** [comment]
see screenshots—I admit to over-loving expanded capabilities ;^]
![Screen- 2021-02-13 at 1 29 40 PM](https://user-images.githubusercontent.com/22728371/107862180-e7eba400-6dff-11eb-97b3-3637ce483912.jpg)
![Screen- 2021-02-13 at 1 29 17 PM](https://user-images.githubusercontent.com/22728371/107862187-f5a12980-6dff-11eb-8ade-472b32e52258.jpg)
