### ISSUE TITLE
Android App: File System storage:  Not able to access SD removable storage

### ISSUE THREAD

**Issue by ZebulonGlitch** [laurent22/joplin#4527]
I get errors when trying to direct Joplin to use the microSD storage in my phone.  Seems that the app is not granting itself the necessary privileges when the user clicks the "authorize local storage access" OS prompt.
- Path that works fine: /storage/emulated/0/foo  
- No worky:  /storage/AB0D-B37/foo  

To confirm: Internal storage works, but I can't really switch my personal cloud storage solution to internal device memory as it's just not enough space..  I have a big 512 gig microSD clicked into my phone to expand it, and Joplin is one of several datasets I store in that sync folder.  But I love Joplin!  Hope this bug report helps.  :D

## Environment

Joplin version: 1.7.5
Platform: Android
OS specifics:  Android 10, - Fairphone 3.  Not rooted, vanilla, everything up to date.

## Steps to reproduce

1. Clear cache and app storage - wipe it all via Android system app admin screen to start fresh.
2. Enter any path to SD storage into the settings field.  (please add a file browsing button :) android paths aren't super friendly
3. Save the settings
4. When OS asks to grant storage permission, touch "allow"
5. Tap the sync button under the hamburger menu.
6. Observe an error under the sync button explaining how access is denied.
7. Change path to internal storage /storage/emulated/0/foo, press sync, observe it working perfectly. Awesome

Seems like a pretty cut and dry permission glitch in how SD card storage is handled by Android.

## Log File
For some reason Github is not letting me upload the "syncReport" error log file.  So I'll just fish through the syncReport-1613239767070.txt generated by the app and paste relevant looking entries here. I will just select just one among the many failed attempts using SD storage.

```
02-13T19:02:45,30,"""RevisionService::maintenance: Done in 286466ms""
02-13T19:02:45,30,"""RevisionService::collectRevisions: Created revisions for 0 notes""
02-13T19:02:45,30,"""RevisionService::maintenance: Done in 32ms""
02-13T19:02:45,30,"""Error: Error: Directory could not be created. Path: storage/AB0D-B137/JoplinNotes
Code: EUNSPECIFIED
value@index.android.bundle:1292:313
index.android.bundle:1292:3439
y@index.android.bundle:109:587
index.android.bundle:109:1890
y@index.android.bundle:109:587
o@index.android.bundle:109:1066
index.android.bundle:109:1238
f@index.android.bundle:125:155
index.android.bundle:125:864
y@index.android.bundle:130:581
C@index.android.bundle:130:947
callImmediates@index.android.bundle:130:3004
value@index.android.bundle:27:2919
index.android.bundle:27:1095
value@index.android.bundle:27:2611
value@index.android.bundle:27:1065
value@[native code]
value@[native code]""
02-13T19:02:45,30,"""Could not run background sync:""
02-13T19:02:45,30,"""Preparing scheduled sync""
02-13T19:02:45,30,"""Running background sync on timer...""
02-13T19:02:45,30,"""RevisionService::maintenance: Starting...""
02-13T19:02:45,30,"""RevisionService::maintenance: Service is enabled""
```
Looking at the many failed and successful log records, they don't look like they'd add any value.
Thanks a million and kind regards

**Comment by ZebulonGlitch** [comment]
Issue still exists.  I tested again about a week ago after an update, but the bug is still there.  I cannot sync to my micro SD card where my personal cloud software has it's sync folders.  No change to the errors and behaviour.

**Comment by roman-r-m** [comment]
It has to do with permission changes in Android 10 onwards. Apps can no longer access arbitrary directory on external storage. There may be a way around this but I'll need to check.

**Comment by ZebulonGlitch** [comment]
Yes, i think you are correct, i noticed the SD access behaved differently in this newer Android 10 phone compared to my older Android which i swapped out around 6 months ago.

FYI, i have other apps which are able to access external storage.  Total Commander is a fair example, powerful file manager from the same legendary dev of old.  At one point in time when I first got this phone i vaguely recall authorizing Storage Permissions, but I believe it made the OS pop up a dialog where i had to explicitly tell android to allow the SD storage location since it's above and beyond the default file access all apps get.  Also had to do this with my camera app when i told it to save photos on SD, team viewer, and a few others though my memory is murky.  I just know that many apps do need an extra step to use external storage.

Wish i could help on the details, but it's probably as simple as triggering the OS to ask the user to grant access if it detects that the specified path is being denied due to privileges.  Hopefully you get a different error raised if the user enters a bad path - very easy to do with copy paste, since when pasting Android seems to always drop the leading "/".  Typing the whole path out is not for the feint of heart (sigh), so a path browsing dialogue wouldn't hurt.  ;-)  But i don't want to be greedy.  <3  :D

**Comment by roman-r-m** [comment]
> FYI, i have other apps which are able to access external storage. Total Commander is a fair example, powerful file manager from the same legendary dev of old. At one point in time when I first got this phone i vaguely recall authorizing Storage Permissions, but I believe it made the OS pop up a dialog where i had to explicitly tell android to allow the SD storage location since it's above and beyond the default file access all apps get. Also had to do this with my camera app when i told it to save photos on SD, team viewer, and a few others though my memory is murky. I just know that many apps do need an extra step to use external storage.

Android has an option to allow more or less unrestricted access to external storage but it's limited to certain kinds of apps - file managers (like Total Commander) and such. More details here https://developer.android.com/training/data-storage/manage-all-files#all-files-access-google-play I doubt Joplin would qualify to get this permission.

There seems to be a way to ask the user for access to a folder on external storage and get access to it, the problem is it requires a different API and it has to be pretty much done from scratch. I may look into this but doubt it can be ready anytime soon.

> Typing the whole path out is not for the feint of heart (sigh), so a path browsing dialogue wouldn't hurt. ;-) But i don't want to be greedy. <3 :D

This btw is the easy part

**Comment by roman-r-m** [comment]
One thing you can try is see if your cloud storage app has unrestricted access to SD card and if it does, try pointing it and Joplin both to
```
/storage/AB0D-B37/data/net.cozic/joplin/
```
I think Joplin is allowed to access its own data dir even on external storage without any special permissions
