### ISSUE TITLE
New device can't sync with the sync directory

### ISSUE THREAD

**Issue by ddtuan99** [laurent22/joplin#4528]
## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: 

## Steps to reproduce

I copy the sync directory to another Linux laptop. Change Synchronization setting properly (set directory path). Click Synchronize but no note has sync and no error apprears.

My sync target on old device use encryptions so i did try enable encryption on new device with same encryption password on old device but nothing changes.

## Describe what you expected to happen
Notes in sync directory are sync (read) by Joplin in new device.

**Comment by CalebJohn** [comment]
This should work. I use file system sync on Ubuntu 20.04, so I can confirm that it does work on a Debian derivative. 

What you should do is completely delete your Joplin profile (`rm -rf ~/.config/joplin-desktop`) and try starting again. Don't enable encryption until Joplin prompts you to do so (at some point during the sync a yellow banner will appear along the top of the screen). Before starting you should confirm that all sync files are present and nothing was deleted during the first attempted sync.

Also worth checking, are there any special characters in the file path (spaces, unicode characters, etc.)? I don't know about any issues that currently exists with how Joplin handles file paths like that, but non-ascii file paths are a scourge on other applications.

It's also worth double checking the path that you passed to Joplin (and check the permissions on the files/folder). I'm sure you've already triple checked, but I think we all know how easy it is to overlook a mistaken character.

**Comment by ddtuan99** [comment]
Turns out it's Flatpak version's issue. I have downloaded the AppImage from github, it can now recognize my notes and prompt master key after import all notes.

It seems there is no support for Flatpak version but if anyone can take a look on log file i would really appreciate. If the issue with Flatpak version can be derive, i would deliver infos to the guys work on Flatpark version.

[log_.txt](https://github.com/laurent22/joplin/files/5976511/log_.txt)

**Comment by ddtuan99** [comment]
@CalebJohn  Really appreciate your guide. I have tried but it dosen't work.

Odd thing is after experiment with AppImage binary from github, i delete all left data of github version and try Flatpak version again and it works. Maybe i left some data? But i remember it imports the hold database again from the begining.

Because i'm exprerimenting so the directory is messy so i uninstall and delete complete Flatpak version. Then try again with proper set up for directory and it didn't work.

**Comment by CalebJohn** [comment]
@ddtuan99  I gave the log file a read and it looks completely normal.

I think filesystem sync can't work with Flatpacks because of the sandboxing (I'm not an expert so I could be wrong). I think if you ask the people responsible for the Flatpack version they might be able to help you set it up.
