### ISSUE TITLE
Toggle Editor Layout should also have editor on right, view on left.

### ISSUE THREAD

**Issue by pahowes** [laurent22/joplin#4530]
The various view toggles work well, but one thing that would make it stellar is to add another view that swaps the Markdown editor and the preview panels, so that the preview is on the left and the editor on the right.

This may not make a lot of sense at first, but think about it: When a note is opened, what is the first thing you do? View it. That should have the quickest access and be the closest to the note list. If the editor is on the right, then typing becomes the secondary operation.

**Comment by aashimawadhwa** [comment]
@pahowes  i will like to work on this issue ,please can u elaborate a little more about it?
you want to change the layout of the editor? can you please guide a little about the same.

**Comment by pahowes** [comment]
In the upper-right corner of the window, there's a button that cycles between the edit mode, preview mode, and a split-screen mode with editing on the left and the preview on the right.

I'd like to see an option for the split screen mode to put the preview on the left and the editor on the right.
