### ISSUE TITLE
synchronization doesnt work on nextcloud with clamav

### ISSUE THREAD

**Issue by dumprop** [laurent22/joplin#4531]
## Environment

Joplin version: all (1.7.11)
Platform: macos (especially ios)
OS specifics: big sur, ios 13

## Steps to reproduce

1. setup nextcloud w/ clamav
2. create 10-20 notes
3. try to create/update some notes on ios

## Describe what you expected to happen
Notes are synced
Sometimes it syncs on macos (but it takes some minutes for a note with a few words!) and always stuck on ios
So, I was forced to disable antivirus on nextcloud because it is incompatible with joplin 
Encryption on nextcloud is enabled

**Comment by dumprop** [comment]
Seems that joplin w/ nextcloud+clamav is incompatible 
So, for file syncing have to disable it

**Comment by dumprop** [comment]
Is possible to fix it on joplin side?

**Comment by roman-r-m** [comment]
any errors in Joplin's log or on the server?

**Comment by dumprop** [comment]
> any errors in Joplin's log or on the server?

Errors only on the Joplin side
as I remember, the application often makes small changes via WebDAV and the clamav does not have time to check, because of this, synchronization often ends with a timeout (and because WebDAV slow too), so there was bottleneck
but I'll come back with the logs sometime

**Comment by roman-r-m** [comment]
> as I remember, the application often makes small changes via WebDAV and the clamav does not have time to check

Any chance you can ask clamav support if there's any? Or if there's no support maybe there's some forum?

**Comment by dumprop** [comment]
Last error: Error: Cannot acquire sync lock: either the lock could be written but not read back. Or it was expired before it was read again.

**Comment by roman-r-m** [comment]
For locking Joplin creates a small text file on the server, looks like something went wrong there. As the error message suggest it might be that the server reported ok when writing file but when Joplin tried to read it again the file was not there.
