### ISSUE TITLE
JoplinPortable-1.7.11.exe does not start. 

### ISSUE THREAD

**Issue by mezzagianni** [laurent22/joplin#4532]
JoplinPortable-1.7.11.exe does not start. 

## Environment

Joplin version: JoplinPortable-1.7.11
Platform: Windows
OS specifics:  Windows 10 Pro 32 bits, ver. 20H2, build 19042.804

## Steps to reproduce

1. double clink on JoplinPortable-1.7.11.exe

## Describe what you expected to happen

The Joplin window does not appear, but by opening "task manager" i see the program is running 

## Logfile

`Uncaught Error: Cannot find module 'C:\Users\Gianni\AppData\Local\Temp\1nyFec1043st5vPqY5VMgIJPCkQ\resources\app.asar\node_modules\@joplin\lib\node_modules\sqlite3\lib\binding\napi-v3-win32-ia32\node_sqlite3.node'
Require stack:
- C:\Users\Gianni\AppData\Local\Temp\1nyFec1043st5vPqY5VMgIJPCkQ\resources\app.asar\node_modules\@joplin\lib\node_modules\sqlite3\lib\sqlite3-binding.js
- C:\Users\Gianni\AppData\Local\Temp\1nyFec1043st5vPqY5VMgIJPCkQ\resources\app.asar\node_modules\@joplin\lib\node_modules\sqlite3\lib\sqlite3.js
- C:\Users\Gianni\AppData\Local\Temp\1nyFec1043st5vPqY5VMgIJPCkQ\resources\app.asar\node_modules\@joplin\lib\database-driver-node.js
- C:\Users\Gianni\AppData\Local\Temp\1nyFec1043st5vPqY5VMgIJPCkQ\resources\app.asar\node_modules\@joplin\lib\BaseApplication.js
- C:\Users\Gianni\AppData\Local\Temp\1nyFec1043st5vPqY5VMgIJPCkQ\resources\app.asar\app.js
- C:\Users\Gianni\AppData\Local\Temp\1nyFec1043st5vPqY5VMgIJPCkQ\resources\app.asar\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:961)
    at Function.i._resolveFilename (electron/js2c/renderer_init.js:39)
    at Module._load (internal/modules/cjs/loader.js:844)
    at Function.Module._load (electron/js2c/asar.js:769)
    at Module.require (internal/modules/cjs/loader.js:1023)
    at require (internal/modules/cjs/helpers.js:77)
    at Object.<anonymous> (C:\Users\Gianni\AppData\Local\Temp\1nyFec1043st5vPqY5VMgIJPCkQ\resources\app.asar\node_modules\@joplin\lib\node_modules\sqlite3\lib\sqlite3-binding.js:4)
    at Object.<anonymous> (C:\Users\Gianni\AppData\Local\Temp\1nyFec1043st5vPqY5VMgIJPCkQ\resources\app.asar\node_modules\@joplin\lib\node_modules\sqlite3\lib\sqlite3-binding.js:7)
    at Module._compile (internal/modules/cjs/loader.js:1145)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166)`

`DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/JoplinSettings.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/JoplinContentScripts.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/immer.cjs.development.js.map: 
3DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/reducer.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/PluginRunner.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/BasePluginRunner.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/executeSandboxCall.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/bridge.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/PlatformImplementation.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/AlarmService.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/Alarm.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/AlarmServiceDriverNode.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/actionApi.desktop.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/ExternalEditWatcher.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/BaseApplication.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/KeychainServiceDriver.node.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/KeychainServiceDriverBase.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/KvStore.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/SyncTargetJoplinServer.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/file-api-driver-joplinServer.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/Synchronizer.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/LockHandler.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/types.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/MigrationHandler.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/1.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/2.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/MasterKey.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/JoplinServerApi2.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/EncryptionService.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/SyncTargetOneDrive.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Gianni/AppData/Local/Temp/1nyFec1043st5vPqY5VMgIJPCkQ/resources/app.asar/onedrive-api.js.map: `

**Comment by JackGruber** [comment]
If I remember correctly from a thread or issue, win 32 bit is no longer supported by the new electron version witch Joplin is using.
