### ISSUE TITLE
Can't synchronize using the official iOS app

### ISSUE THREAD

**Issue by t3ax** [laurent22/joplin#454]
### Operating system

- iOS (latest)

### Application

- Mobile (latest)

I'm trying to use the official Joplin iOS app to synchronize with my Nextcloud installation. 
When trying to set it up in the setting I get the error message "Network request failed".

I can't find out what is wrong since I'm using the right credentials (url, username and password) like I use in the macOS client - which works flawlessly.

Would be nice to finally get it working properly. 

I'm willing to share all the informations needed to resolve the issue and help this app/project.

**Comment by laurent22** [comment]
"Network request failed" are very hard to debug in general. Could you try to generate a low-level bug report as described there?

https://github.com/laurent22/joplin/blob/master/readme/debugging.md#low-level-debugging-on-ios

Basically get the error to happen and generate that report immediately after.

**Comment by lverissimo** [comment]
I have the same error trying to connect to the following Nextcloud synchronisation target:
https://mm.mm.mm:8177/nextcloud/remote.php/webdav/joplin/

![image](https://user-images.githubusercontent.com/8387568/45982606-435f4080-c051-11e8-9d9a-fb61b47cbef2.png)
I don't get an application crash, hence no additional files available as described in the file above.

**Comment by calihero** [comment]
Same problem for me. I'm using a Let's encryp multidomain certificate with Seafile and IIS . Other applications / Webbrowser (firefox, IE, Chrome) works fine.  HTTP only works as well. 
![grafik](https://user-images.githubusercontent.com/46417875/50736414-a074a180-11bd-11e9-9894-eaf00b3f308d.png)
