### ISSUE TITLE
Title of short note disappears

### ISSUE THREAD

**Issue by BertHammer** [laurent22/joplin#4543]
## Environment

Joplin version: 1.7.5
Platform: Android
OS specifics: 8.1.0

## Steps to reproduce

1. Tap the plus-button and select 'new note'.
2. Type a title: e.g. "Hello Bug!"
3. Tap the body area and type: "Short notice."
4. Tap the arrow at the top left (transition from edit to view).
5. Observe that the title "Hello Bug!" **disappears**. The body is rendered correctly.
6. Tap the arrow again (transition back to the note list).
7. Observer that the title is displayed correctly.
8. Tap the note title (transition to the note viewer).
9. Observe that first, while rendering of the body is being prepared, the title is displayed correctly. At the moment the body appears, the title **disappears**.
10. Tap the red edit button (transition to edit).
11. Observe that the title reappears.
12. Make the body longer, up to 18 lines. For example, after 'Short notice' type 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8, each on a new line.
13. Tap the arrow (transition to view).
14. Observe that the title still disappears.
15. Tap the edit button.
16. Add one more line to the body.
17. Tap the arrow (transition to view).
18. Observe that the title is **displayed correctly**.

## Describe what you expected to happen

The title should not disappear, long or short note.
![short notice 03](https://user-images.githubusercontent.com/79171171/108128005-6d937c00-70ac-11eb-93be-33b78c8d33c1.png)
![short notice 05](https://user-images.githubusercontent.com/79171171/108128025-72f0c680-70ac-11eb-98dd-fa03e078c441.png)
![short notice 09a](https://user-images.githubusercontent.com/79171171/108128094-8bf97780-70ac-11eb-9aba-a5b5e36ec0e3.png)
![short notice 09b](https://user-images.githubusercontent.com/79171171/108128103-8f8cfe80-70ac-11eb-885a-c3cba035c445.png)
![short notice 14](https://user-images.githubusercontent.com/79171171/108128108-91ef5880-70ac-11eb-8ed8-cdc401a20a77.png)
![short notice 18](https://user-images.githubusercontent.com/79171171/108128122-94ea4900-70ac-11eb-9e75-a81a70be9004.png)

**Comment by roman-r-m** [comment]
For reference - I was not able to reproduce it following the above steps.
