### ISSUE TITLE
Search is not focused on results

### ISSUE THREAD

**Issue by CapZhang** [laurent22/joplin#4544]
## Environment

Joplin 1.7.11 (prod, win32)
windows10

## My question
When I use Ctrl + P to search for a certain keyword, it just opens the specific Note.Not focusing on highlighted keywords

But using F6 searches can focus on results

**Comment by CalebJohn** [comment]
Hi @CapZhang 

Thanks for the issue. But this is by design, Ctrl+P is the goto anything feature. If you would like to search please use the search feature.
