### ISSUE TITLE
Can't enter sync password containing a quote on CLI

### ISSUE THREAD

**Issue by JazzXP** [laurent22/joplin#4545]
Try to set a password using
```
:config sync.5.password ab'c
```
and it will be rejected for containing an unclosed quote

## Environment

Joplin version: 1.6.4
Platform: terminal
OS specifics: macOS 10.14.6

## Describe what you expected to happen

The ability to set password, even if it has to be enclosed with double quotes

**Comment by pgy866** [comment]
Extension: **[Integrated mkdocs](#https://github.com/mkdocs/mkdocs)**
Export
