### ISSUE TITLE
Synchronization Error on macOs Big Sur 11.2.1

### ISSUE THREAD

**Issue by leohoppergit** [laurent22/joplin#4551]
Hey everyone,

since a few days I can't synchronize on my macOS and WebDAV (woelkli-nextcloud) without having changed any of the configuration.

Here's the message:
Error: GET info.json: Unknown error 2 (502)

Can anyone help? I'm on version:
Joplin 1.7.11 (prod, darwin)

Sync-Version: 2
Profil-Version: 34
Unterstützter Schlüsselbund: Ja

Revision: f560563 (master)

Regards!

## Environment

Joplin version: 1.7.11
Platform: macOS
OS specifics: OS version 11.2.1

## Logfile
see attached files
[-1613640518749.log](https://github.com/laurent22/joplin/files/6001708/-1613640518749.log)
[-1613640557525.log](https://github.com/laurent22/joplin/files/6001709/-1613640557525.log)
[-1613640563486.log](https://github.com/laurent22/joplin/files/6001710/-1613640563486.log)

**Comment by JackGruber** [comment]
The 502 Bad Gateway error is an HTTP status code means that the server received an invalid response from another server. 
So I think the error is on woelkli-nextcloud.

**Comment by leohoppergit** [comment]
> The 502 Bad Gateway error is an HTTP status code means that the server received an invalid response from another server.
> So I think the error is on woelkli-nextcloud.

I think that this is unlikely to be the issue, since the synchronization works just fine on my Android device as well as on the iPad - the configuration is the same (woelkli-nextcloud)
