### ISSUE TITLE
Copy/paste shortcuts in Vim mode

### ISSUE THREAD

**Issue by jrwrigh** [laurent22/joplin#4553]
## Environment

Joplin version: 1.7.11 (prod, linux), d6b77db
Platform: Linux
OS specifics: Manjaro

## Steps to reproduce

1. Enable vim mode
2. Try and use <kbd>Ctrl</kbd>+<kbd>c</kbd> or <kbd>Ctrl</kbd>+<kbd>v</kbd> in either normal or insert mode
3. Try and paste the contents. (contents do not paste)

## Describe what you expected to happen
I expect to be able to use use the copy/paste shortcuts like normal.

**Comment by pluma9** [comment]
Possible duplicate of  #3870?

**Comment by jrwrigh** [comment]
Yep, looks like it is.
