### ISSUE TITLE
Website: Menu link is inactive

### ISSUE THREAD

**Issue by chmac** [laurent22/joplin#4560]
On [the website](https://joplinapp.org) the "menu" link in the top doesn't do anything.

It seems to have been added in abcb1ac7603e79d9bb2e32d3b48e9456e3d5e5db about 3 years ago. Maybe the build process from md -> html has changed in the meantime?

I tried 2 browsers and it didn't do anything on either. It also doesn't have an ID or class so I figure it's unlikely that there's an event hooked onto it via javascript, but of course I could be wrong.

PS> Thanks a lot for joplin, it's wonderful to have a free(dom) alternative to evernote.

**Comment by tessus** [comment]
Hmm, we actually made the menu permanent, so I guess @laurent22 forgot the remove the link. ;-)
