### ISSUE TITLE
Mermaid diagrams truncate text inside nodes

### ISSUE THREAD

**Issue by codyburleson** [laurent22/joplin#4561]
## Environment

Joplin version: 1.6.8 (prod, win32)
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Reproduce the example mermaid snippet shown [HERE in the Mermaid live editor online](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBW0NocmlzdG1hc10gLS0-fEdldCBtb25leXwgQihHbyBzaG9wcGluZylcbiAgICBCIC0tPiBDe0xldCBtZSB0aGlua31cbiAgICBDIC0tPnxPbmV8IERbTGFwdG9wXVxuICAgIEMgLS0-fFR3b3wgRVtpUGhvbmVdXG4gICAgQyAtLT58VGhyZWV8IEZbZmE6ZmEtY2FyIENhcl0iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)
2. Notice the difference between the Joplin version and the expected version of the diagram as illustrated in screenshots below:

**JOPLIN version...**
![2021-02-19_mermaid-me](https://user-images.githubusercontent.com/7317733/108543572-7f3e7480-72a2-11eb-876e-81b01d74d3da.jpg)

**EXPECTED version...**
![2021-02-19_mermaid-expected](https://user-images.githubusercontent.com/7317733/108543658-967d6200-72a2-11eb-8d74-8bfb61a0dece.jpg)

## Describe what you expected to happen

I expect each diagram node to render the complete word or words within that node, but as you can see by comparing, the ends of the words are getting cut off in Joplin.

## Logfile

Attached, though there appears to be no relevant data in the log...

[log.txt](https://github.com/laurent22/joplin/files/6012061/log.txt)

**Comment by tessus** [comment]
I can't reproduce this. See here:

<img width="771" alt="image" src="https://user-images.githubusercontent.com/223439/108582817-8d70ad00-7303-11eb-99f2-bc033f9505e4.png">

I also checked the code. We haven't updated Mermaid after 1.6.8 came out, thus I'm not sure what the problem is.

**Comment by laurent22** [comment]
What's the zoom level on your app?

**Comment by codyburleson** [comment]
That was it! My Zoom Level was not at "Actual Size" and when I set it to "Actual Size," this resolved the issue. See below:

![image](https://user-images.githubusercontent.com/7317733/108606856-014d9c80-737a-11eb-9ff3-0fa06175b0e6.png)

**Comment by tessus** [comment]
This is unfortunately a Chrome upstream issue. Latex formulas have sometimes the same problem.
