### ISSUE TITLE
.CodeMirror-selected doesn't respect userchrome.css in Dark Mode

### ISSUE THREAD

**Issue by EmperorEarth** [laurent22/joplin#4563]
[Relevant code](https://github.com/laurent22/joplin/blob/fd390dff6b602bff7bf91b5b23bebe0d6740cd4b/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx#L374-L379)

**Comment by Blakelist7** [comment]
Hey, @EmperorEarth could you elaborate the issue?
also mention platform and ss

**Comment by EmperorEarth** [comment]
My bad, I pinned it on `dev` tip instead of a specific commit and commits after my OP adjusted what the line numbers.

[New, persistent link](https://github.com/laurent22/joplin/blob/fd390dff6b602bff7bf91b5b23bebe0d6740cd4b/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx#L374-L379) (updated OP as well)

Platform: all desktop apps

Explanation: When you modify `.CodeMirror-selected`'s style in `userchrome.css`, Joplin respects with your changes with `Dark Mode` off, but doesn't with `Dark Mode` on. The linked section is why, specifically, [`background: #6b6b6b !important;
` on Line 378](https://github.com/laurent22/joplin/blob/fd390dff6b602bff7bf91b5b23bebe0d6740cd4b/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx#L378) is applied after `userchrome.css` is applied. CSS, being last-write wins, will use `background: #6b6b6b !important;`, the last write.

**Comment by Blakelist7** [comment]
@EmperorEarth can you guide me how?

**Comment by aashimawadhwa** [comment]
i would like to work on this issue 
@EmperorEarth  the issue exactly says that joplin have a issue  in switching dark mode on or making changes while the dark mode is on?

**Comment by EmperorEarth** [comment]
Sure, I'll provide a bit more context; working on open source projects is a great way to gain experience! Sadly, I can't provide much more than this; I simply don't have the bandwidth.

Joplin allows users to [set custom styles](https://joplinapp.org/#custom-css) via two files, `userchrome.css` and `userstyles.css`. Joplin also allows users to a Dark Mode option. Sometime after Joplin added Dark Mode, [a user realized that the highlight used in selecting text in `Editor` mode has poor contrast](https://discourse.joplinapp.org/t/dragging-in-dark-theme/12433/1). @laurent22 applied a [quick band-aid](https://github.com/laurent22/joplin/commit/83ca33611b1c95362475fe9453c1b3759174f750) to improve the contrast in dark mode. His band-aid, however, is applied after `userchrome.css` is applied, meaning that it overrides any custom user styles for the class. The css class used for determining highlight color is `.CodeMirror-selected`. Refer to my previous comments in this thread for more info.

**Comment by aashimawadhwa** [comment]
can i start working on this issue?  @EmperorEarth

**Comment by EmperorEarth** [comment]
It's not my project and it's open source. Generally, first good pull request wins.

**Comment by aashimawadhwa** [comment]
i would like to work on this issue please assign it to me?

**Comment by roman-r-m** [comment]
We do not assign issues, just go ahead

**Comment by aashimawadhwa** [comment]
i am not able to find userchrome.css can someone please help me .

**Comment by aashimawadhwa** [comment]
can you please mark userchrome.css ?

**Comment by roman-r-m** [comment]
> can you please mark userchrome.css ?
> 

I'm not quite sure what you mean, please elaborate.

**Comment by noman2002** [comment]
I was unable to find userchrome.css. Can you please help me out.

**Comment by laurent22** [comment]
As a reminder, for GSoC you should only work on issues that have been triaged, which means labelled with either "medium" or "high". Also you should perhaps try a bit harder to find the answers to your own questions, because all of this is in the doc or code. EmperorEarth even gave a detailed description of the problem.
