### ISSUE TITLE
Joplin-server without docker?

### ISSUE THREAD

**Issue by misterhsp** [laurent22/joplin#4572]
Is there a howto for the joplin-server without docker?

Thanks...

**Comment by CalebJohn** [comment]
@misterhsp for your information, you're much more likely to get a response to this question [on the forum](https://discourse.joplinapp.org/) there are a few knowledgeable people there who might be able to answer your question (or write up a guide for you) that don't check the issues.

**Comment by misterhsp** [comment]
Don't have an account there, and won't have one there.

**Comment by misterhsp** [comment]
rm -rf joplin

...

done...
