### ISSUE TITLE
resource api get filename is empty

### ISSUE THREAD

**Issue by rxliuli** [laurent22/joplin#4575]
![image](https://user-images.githubusercontent.com/24560368/108645122-b99b5200-74ec-11eb-85ed-6331d974b9ed.png)

![image](https://user-images.githubusercontent.com/24560368/108645111-a7211880-74ec-11eb-8bc2-0a0c25b16b27.png)

## Environment

Joplin version: 1.7.11 dev win32
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Open Joplin Clipper Service
2. Use Data api to get information about a single resource
3. See that the `filename` obtained is an empty string

## Describe what you expected to happen

Get the filename of the attachment resource correctly

**Comment by nishantwrp** [comment]
I'd like to work on this.

**Comment by roman-r-m** [comment]
@rxliuli what do you expect to get in filename? Say you had a file `cat_picture.jpg`, you attach it, and it gets saved with id `1234567`.
Do you expect filename to contain the original name of the file, i.e. `cat_picture.jpg` or the name under which it's saved in Joplin i.e. `1234567.jpg`?

**Comment by rxliuli** [comment]
is `cat_picture.jpg`, exactly what I want is: when I open it in an external editor, Joplin creates a temporary file under `JoplinProfile\tmp\edited_resources` with the name `cat_picture.jpg` so I want to get the name by `filename`

![image](https://user-images.githubusercontent.com/24560368/111555568-a3b73f00-87c3-11eb-9359-2c4e9c1f0cbd.png)

**Comment by roman-r-m** [comment]
I think right now you can get it as `resource.title + resource.file_extension`

**Comment by roman-r-m** [comment]
Also sounds like you need the full path or else you'd be relying on internal implementation details. I mean the `tmp/edited_resources` part

**Comment by rxliuli** [comment]
> I think right now you can get it as `resource.title + resource.file_extension`

No, if I do this, there is a problem when I contain the subroutine name in Title.

For example

```js
{
  title: 'OtherApi.test.ts',
  file_extension: 'ts',
  filename: '',
  type_: 4
}

The name after the stitching is `Otherapi.test.ts.ts`, actually` TMP / edited_resources` is the file name is `Otherapi.test.ts`, just judgment` title` is a suffix, no suffix is ​​added Up to `file_extension`? Still have other rules?

**Comment by rxliuli** [comment]
> Also sounds like you need the full path or else you'd be relying on internal implementation details. I mean the `tmp/edited_resources` part

I hope REST API `/services/resourceEditWatcher/watch` can return the temporary file name, but it is not currently implemented. . .

**Comment by roman-r-m** [comment]
> The name after the stitching is `Otherapi.test.ts.ts`, actually` tmp/edited_resources` is the file name is `Otherapi.test.ts`, just judgment` title` is a suffix, no suffix is ​​added Up to `file_extension`? Still have other rules?

Yes, you're right. I thought I was building file name by stitching together title and extension in `useOnResourceLongPress` but no, it's just the title.
But then, if you already have the full name in `title`, why not use it?

**Comment by rxliuli** [comment]
> > The name after the stitching is `Otherapi.test.ts.ts`, actually` tmp/edited_resources` is the file name is `Otherapi.test.ts`, just judgment` title` is a suffix, no suffix is ​​added Up to `file_extension`? Still have other rules?
> 
> Yes, you're right. I thought I was building file name by stitching together title and extension in `useOnResourceLongPress` but no, it's just the title.
> But then, if you already have the full name in `title`, why not use it?

Because it is uncertain whether Title is a real file name. . .

**Comment by roman-r-m** [comment]
> Because it is uncertain whether title is a real file name. . .

Yeah, looks like it atm uses the title to generate the file name (`via Resource.friendlySafeFilename`), but I agree this is also an implementation detail and can be changed

**Comment by rxliuli** [comment]
This implementation details have an effect on external resource editing, mainly affecting accessory resources including secondary suffixes. For example Test.Drawio.svg, Test.km.svg
