### ISSUE TITLE
TOC plugin doesn't generate TOC correctly if single-line comment symbol in md code block.

### ISSUE THREAD

**Issue by sorochinskii** [laurent22/joplin#4577]
If a note contains a code block with a comment inside, then the comment is treated as a md heading.

## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Ubuntu 20.04

## Steps to reproduce

1. Create new note.
2. Insert code block with #-style comment on new line.
3. Look on TOC.

![Screenshot_6](https://user-images.githubusercontent.com/3678968/108702566-4402a680-752b-11eb-891b-3b3584d14af7.png)

## Describe what you expected to happen

The plugin ignores lines in a code block with #-symbol at the beginning.

**Comment by laurent22** [comment]
please report on toc plugin repo
