### ISSUE TITLE
Security, Android: Authenticating with internal Webview when connecting to OneDrive

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#4578]
Currently Joplin for Android uses an internal webview to log in to OneDrive.
This is undesirable for security reasons.
https://auth0.com/blog/oauth-2-best-practices-for-native-apps/

You should open an external browser and manually copy-paste the code displayed after authentication into the Joplin app.

## Environment

Joplin version: 1.7.5
Platform: Android

**Comment by yuguamax** [comment]
By using an external browser, the user can check the URL.
This is useful as an anti-phishing measure.

**Comment by yuguamax** [comment]
This issue has not been resolved.
