### ISSUE TITLE
Zooming in and out using Ctrl + +/- does not work on JIS keyboard.

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#4579]
On a US keyboard, you can use Control + +/- to zoom in and out.
On a JIS keyboard this will not work, instead use Ctrl + ^ to zoom in.([Reference image](https://commons.wikimedia.org/wiki/File:KB_Japanese.svg))
It should not work according to the location of the key, but according to the printed characters.
## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Arch Linux

**Comment by yuguamax** [comment]
Perhaps, but I think this problem also occurs with German and French keyboards.
https://commons.wikimedia.org/wiki/File:KB_Germany.svg
https://commons.wikimedia.org/wiki/File:KB_France.svg

**Comment by gonzalovsilva** [comment]
I would like to be able to zoom in with Ctrl + 'Num+'; zoom out with Ctrl + 'Num -'; actualSize with Ctrl + 'Num0'.
I've changed the actualsize keyboard shortcut to Ctrl + 'Num0' but it doesn't work. I think numpad isn't supported for shortcuts.
I would like to have those 3 options inside the keyboad shortcuts section (only actualSize is present now) and combinations with numpad don't work.

Thank you for this fantastic tool !

**Comment by dz2106** [comment]
Taking a look at this.

**Comment by dz2106** [comment]
https://github.com/laurent22/joplin/issues/4284
https://github.com/laurent22/joplin/issues/4460

These seem to all be related.

**Comment by dz2106** [comment]
https://tkainrad.dev/posts/why-keyboard-shortcuts-dont-work-on-non-us-keyboard-layouts-and-how-to-fix-it/

**Comment by dz2106** [comment]
Makes sense to close issue unless there is new information I have yet to come across.
