### ISSUE TITLE
editor view jumps around when using mermaid diagrams

### ISSUE THREAD

**Issue by charlesdaniels** [laurent22/joplin#4582]
When editing a document with multiple Mermaid diagrams, the editor view jumps every time the document is re-generated. In other words, when the user stops typing causing the preview pane to update, the editor and preview pane both scroll up.

## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: 

```
$ uname -a
Linux menelaus 5.10.16-arch1-1 #1 SMP PREEMPT Sat, 13 Feb 2021 20:50:18 +0000 x86_64 GNU/Linux
$ cat /etc/lsb-release 
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

## Steps to reproduce

1. Create a document with multiple Mermaid diagrams.
2. Scroll down a little ways.
3. Type something or change a diagram, then stop typing.
4. The view will jump.

The attached `demo.txt` file triggers this behavior. A screen capture is also included.

## Describe what you expected to happen

The view does not jump around while editing.

## Logfile

A logfile is attached.

---

Also worth noting:

* Disabling the one plugin I have installed (graph view) does not have any impact. 
* Changing the keyboard mode from "vim" to "default" does not have any impact.

https://user-images.githubusercontent.com/11738895/108751981-e6616080-7510-11eb-9905-1c03b51edd83.mp4

[log.txt](https://github.com/laurent22/joplin/files/6024243/log.txt)

[demo.txt](https://github.com/laurent22/joplin/files/6024248/demo.txt)

**Comment by shbach** [comment]
I've noticed this bug too and it's pretty annoying. It seems to only happens in split view. If I have the view as editor only it doesn't jump every time I edit something.

**Comment by shbach** [comment]
Still an issue. It seems to jump less than I remember though.
