### ISSUE TITLE
Android synchronize icon rotation direction is wrong

### ISSUE THREAD

**Issue by fenbox** [laurent22/joplin#4588]
## Environment

Joplin version: 1.7.5
Platform: Android
OS specifics: 

## Steps to reproduce

1. Click Synchronize button
2. The rotation direction of the icon animation is wrong

## Describe what you expected to happen

Android version is counterclockwise rotation, it's wrong.
![android](https://user-images.githubusercontent.com/360618/108826447-40d8ea80-75ff-11eb-96e1-dfb3446f3ad3.gif)

Desktop version is clockwise rotation, it's correct.
![desktop](https://user-images.githubusercontent.com/360618/108826462-459d9e80-75ff-11eb-88d1-61f709668b88.gif)

**Comment by tessus** [comment]
should be fixed by #4506
