### ISSUE TITLE
Request: “Add To Joplin” action for iOS Safari

### ISSUE THREAD

**Issue by bundito** [laurent22/joplin#459]
### Operating system

- iOS

### Application

- Mobile
<!--
 Love the app, escpecially the Linux terminal mode. But I’m also an iOS user. I’d use the hell out of a Safari action to add a link into Joplin. When I browse the news, I frequently come across ideas or articles I’d like to save for future reference. And where better to store them? Thanks for a fine product.

**Comment by tessus** [comment]
This looks like a duplicate of #110 

While the OP was about Android, I believe this ticket is used as the discussion point for this kind of thing.
It's basically the ability to share a link with or send copied text/images to Joplin.

**Comment by laurent22** [comment]
Duplicate of #110
