### ISSUE TITLE
Cursor moves to top of note after image paste

### ISSUE THREAD

**Issue by smiller86** [laurent22/joplin#4591]
## Environment

Joplin version: 1.7.11
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Copy part of the screen or an image using snipping or snapshot tool in Windows or similar software like PDF viewer
2. Paste the image into a note using WYSIWYG editor
3. Cursor is then found at the beginning of the note

## Describe what you expected to happen

I expect the cursor to either highlight the pasted item or be placed immediately after the pasted item. The latter is consistent with pasted text behavior.

**Comment by lbo34** [comment]
I found it it is not only when pasting. Very often cursor moves to the top and I have not identified why...

**Comment by lbo34** [comment]
I already started a thread for this which was closed: https://discourse.joplinapp.org/t/when-typing-cursor-suddenly-jumps-to-top/14482?u=lbo34

But I still have the problem with Joplin 1.7.11 (prod, darwin)

**Comment by lbo34** [comment]
I believe I have this behaviour only when the export to RStudio button is activated

**Comment by yu-soong** [comment]
I also found that the cursor moved to the top several times. I am using Windows 10

**Comment by coderrsid** [comment]
Yeah, i can reproduce this issue. I am working on this. Thanks.

**Comment by coderrsid** [comment]
I realised that every time the note is schedule saved with pasted image, the cursor moves to the top position.

**Comment by roman-r-m** [comment]
> @roman-r-m , can you please check if that's true

If you say you can reproduce, I believe you :)

**Comment by coderrsid** [comment]
Even, it happens when you just delete the image from the note, the cursor goes to the top.

**Comment by roman-r-m** [comment]
@Siddharth6121 just noticed that your PR has **your** dev branch as target, should be the dev branch in this repo instead.
