### ISSUE TITLE
Inline PDF preview freezes the application on Linux

### ISSUE THREAD

**Issue by banan314** [laurent22/joplin#4598]
## Environment

Joplin version: Joplin 1.7.11 (prod, linux)
Profile Version: 34
Platform: Linux
OS specifics: Mint 19.3 Cinnamon

## Steps to reproduce

1.  Create a note with a PDF inside
2. Open the  note in layout Viewer or Split View
3. scroll down on the Viewer side

Joplin sometimes freezes and strange graphical artefacts show up.

## Describe what you expected to happen

It should not freeze.

**Comment by Ishan-Saini** [comment]
I am using Mint  20.1 Cinnamon and I am not being able to reproduce this issue. Strange!

**Comment by casdidier** [comment]
I am using Ubuntu 20.4 / Joplin 2.4.9 , and I could  not reproduce

**Comment by banan314** [comment]
I don't see the issue in 2.4.6, I'm closing the issue as too old.
