### ISSUE TITLE
Can not paste password when signing into OneDrive

### ISSUE THREAD

**Issue by pgoodjohn** [laurent22/joplin#46]
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

---

Trying to log in my Microsoft account to enable sychronisation but I can't paste my password in the form. This is a bit of a hassle if one is using randomly generate passwords from a password manager (using 1Password here) as there is no integration to auto fill and thus the only solution remaining is to copy paste character by character the password.

**Comment by laurent22** [comment]
Thanks for the bug report, this is fixed in c72e0a14c0491ca706bd9bd59cd7c420eb3219c1 and will be in the next release.

**Comment by johnsaigle** [comment]
I am having a related issue with trying to synchronize with NextCloud (also on Mac, Desktop). I am unable to paste a password

**Comment by apfeiffer1** [comment]
Confirm. On Mac (Sierra-10.12.6) desktop, I can not paste into any of the text fields for synchronisation (neither password, nor WebDAV URL). Checked for "Nextcloud" and "WebDAV" targets on 1.0.62 and 1.0.63).

**Comment by jcgerhard** [comment]
Confirm this, too. Cannot copy and paste credentials from the clipboard to the form.

**Comment by laurent22** [comment]
Hmm yes not sure why I closed this, since clearly the referenced commit doesn't address this bug.

**Comment by laurent22** [comment]
Fixed in a37b599a6b55f2f2a58cccc3a583a3a0640af618

**Comment by jcgerhard** [comment]
Thank you for fixing it! Works perfect now on macOS and it's a real mercy while using long (hopefully) secure passwords and extensive syncing urls! **Thumbs-Up**
