### ISSUE TITLE
[feature request] Nextcloud app

### ISSUE THREAD

**Issue by tomthecat** [laurent22/joplin#460]
### Application

Joplin is a nearly perfect note taking and to do list solution available for mobile devices and all relevant desktop OS. 

I use my Nextcloud instance to sync notes and to do's between different devices. It would be the cherry on the cake to have a Nextcloud app for Joplin.

**Comment by foxmask** [comment]
fortunatly it's already the case, like the readme explains 

"**The notes can be synchronised with various cloud services including Nextcloud, Dropbox, OneDrive or the file system (for example with a network directory). When synchronising the notes, notebooks, tags and other metadata are saved to plain text files which can be easily inspected, backed up and moved around.**"

**Comment by tomthecat** [comment]
Synching is not the problem. There is no app in Nextcloud to edit Joplin notes.

**Comment by foxmask** [comment]
ok I understand

**Comment by milankni** [comment]
There is a more general thread for this feature request already. Not sure if there is any progress, though.

https://github.com/laurent22/joplin/issues/228#issuecomment-366537106

**Comment by laurent22** [comment]
Duplicate of #228
