### ISSUE TITLE
IOS App use awss3 synchronous show error "XMLParserError: Non-whitespace before first tag"

### ISSUE THREAD

**Issue by alexxux** [laurent22/joplin#4610]
## Environment

Joplin version: 10.7.2
Platform: iPhone12
OS specifics: IOS14.3

## Steps to reproduce

1.Import data from evernote
2. window use awss3 to sync
3. open e2ee
4. iphone complete synchronization
5. iphone input e2ee password start decryption
6. show the error message：“XMLParserError: Non-whitespace before first tag.”

## Logfile
![3e494a1811dfc309bb06e22e6ffa275](https://user-images.githubusercontent.com/41435733/109462311-3fe00700-7a9e-11eb-8c23-aecaeeb79e7b.jpg)
![5229a8c03ba2d4cffce17c0ec7a322f](https://user-images.githubusercontent.com/41435733/109462335-4a020580-7a9e-11eb-9da5-9d5569e51de0.jpg)

**Comment by JabinGP** [comment]
Same problem in my iPhone12mini and iPhone7.

**Comment by vbuser2004** [comment]
Experiencing a similar issue. Created notes on IOS. Sync'd fine at first to s3 (e2ee already enabled), but then it failed at some point (some notes were half completed upon sync with PC). 

Failure caused IOS app not to sync at all (in either direction), showing error below. 

Was able to get it working by doing the following: Within IOS application, in **Encryption Settings**, clicked on the '**SAVE**' button beside each password/checkmark. I did not re-enter the password as these were already correct and entered previously. 

After hitting save, it syncs correctly in both directions. 

However, after editing in IOS, the issue re-appears (below), and the 'SAVE' fix above doesn't work. 

```
XMLParserError: Non-whitespace before first tag. 
Line: 0
Column: 1
Char: i
```

**Comment by smcalilly** [comment]
I'm getting the same error with an iPhone SE. The encrypted notes successfully synced once, and now I can't sync the new notes that I've created on my desktop. The phone shows the same error as @alexxux.

**Comment by Jesssullivan** [comment]
Reproduced in ios simulator, I'll try to poke around and explore this bug this afternoon.

**Comment by idealclover** [comment]
Hello~any updates here?

**Comment by root-io** [comment]
#4810

**Comment by zxkmm** [comment]
#4810 Some progress here.

**Comment by raygervais** [comment]
Hello fellow note takers and developers!

Loving Joplin so far, but wanted to confirm that this issue has popped up for me as well when syncing to AWS S3. How far are we from an iOS release which includes the bugfix above? Thanks again for all the hard work! Hoping to contribute in the future as well.

**Comment by Tombert** [comment]
@raygervais For what it's worth, I found a workaround to get the iOS app working again after the that XML error happens.  

If you go to the configuration, and change the sync target to somewhere else than S3, synchronize with that service, then once it's done, change back to S3 and resynchronize there.

**Comment by raygervais** [comment]
Thanks for the suggestion @Tombert, sadly the workaround doesn't appear to work in my case. Same error

**Comment by scottharwell** [comment]
@raygervais I know this will be a pain, but removing the app from both my iOS devices, then reinstalling and reconfiguring the S3 sync, then applying the encryption key password got me past the issue on my end.

**Comment by mweitzel2005** [comment]
@scottharwell that worked for me too. 

**NB:** Anybody following this approach though that you potentially loose content created on the iOS device that hasn't been successfully sync'ed yet.

**Comment by crs1138** [comment]
Uff, I think I might have to ditch Joplin. Too grave of an error, too long no fix. 😞 It looked so promising.

**Comment by raygervais** [comment]
I ended up doing the same when Joplin didn't sync and notes I expected to have on my mobile for a meeting weren't there. Still love Joplin for local-based note taking, but can't leverage it for cloud sync via AWS just yet.

**Comment by raygervais** [comment]
So I've been leveraging Standard Notes happily since 2019, and wanted to move to Joplin for more of a Zettlekesten style of writing (aka Roam, Backlinks). Looks like I'll return to Standard Notes which hadn't let me down yet, just didn't have some of the features I was curious to try.
