### ISSUE TITLE
Mermaid Syntax Error (only in WYSIWYG)

### ISSUE THREAD

**Issue by Xanaxus** [laurent22/joplin#4612]
## Environment

Joplin version:  Latest 
Platform: Linux
OS specifics: Manjaro

## Steps to reproduce

1. Write A mermaid script
 
 ```mermaid
graph TD;
A[Management Protocol Of Primary Dysmenorrhea] --> |Assurance/Analgesic and Antispasmodic drugs| B[Fails];
B --> |No Contraindication for prostaglandin synthetase inhibiors but contradiction for 'Pill' - desiers pregnance| C[Prostaglandin synthetase inhibiors + LNG-IUD]
B --> |Dosent want to get pregnant| D[Oral Contraceptive pills]
C --> E[Fails]
D --> E
E --> |USG/Laproscopy|F{LUNA/LPSN}
```

## Describe what you expected to happen
Run the script
![image](https://user-images.githubusercontent.com/53279068/109485869-2ba10780-7aa8-11eb-8a55-0359826848b5.png)
![image](https://user-images.githubusercontent.com/53279068/109485944-3eb3d780-7aa8-11eb-916e-84d31532e632.png)

**Comment by tessus** [comment]
Hmm, seems to work here:

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/223439/109542689-62b8ee00-7a93-11eb-8a89-3796487690dc.png">

```
Joplin 1.8.0 (dev, darwin)

Client ID: e354a932e6e143c782264aad4112b674
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: 65b0d7f2f (dev)
```

It's the same Mermaid version though. Just a different OS.

**Comment by tessus** [comment]
> Joplin version: Latest

Seriously? I really hope that you are not that unspecific when it comes to contraception.

`Latest` means nothing to me. It could be the latest release/ pre-release/git dev. And in a few days/weeks/months it means something different as well.

**Comment by roman-r-m** [comment]
> Hmm, seems to work here:

The 2nd screenshot in the OP is WYSWYG and this is where the error occurs. I can reproduce it on 

Joplin 1.7.11 (prod, win32)

Client ID: 8129c25cca08408db9608fbf677fee34
Sync Version: 2
Profile Version: 34
Keychain Supported: No

Revision: f560563d8 (master)

**Comment by laurent22** [comment]
Right I think I saw this error at some point, but gave up on trying to fix it, because if I remember correctly the only info Mermaid gives is this idiotic image with a bomb.
