### ISSUE TITLE
Allow registering multiple settings in one call

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#4614]
The Joplin Plugin API currently provides the following methods:

[joplin.settings.registerSetting](https://joplinapp.org/api/references/plugin_api/classes/joplinsettings.html#registersetting)

to register one setting.

We need to add a new method:

`joplin.settings.registerSettings(settings:Record<string, SettingItem>)`

to register multiple settings in one call.

Additionally, `joplin.settings.registerSetting` should be marked as deprecated, as we should discourage its use (it causes too many IPC calls when the plugin starts). `joplin.settings.registerSetting` should be changed so that it calls `registerSettings`

**Comment by SumeshT** [comment]
I would like to work on this issue.

**Comment by Rash419** [comment]
could you please give some code pointers?

**Comment by arpitg24** [comment]
@laurent22 What does this segment of code mean -> settings:Record<string, SettingItem> , I looked for Record in the code but didn't find any reference, does it contain a list of keys and SettingItems?

**Comment by laurent22** [comment]
Hello, the good first issues are here so that you can familiarise yourself with the code base, by working on a relatively simple task. As such we won't provide much technical help about it. Either you can figure it out by yourself and, if so, you might want to apply for GSoC, or you aren't and in that case another project might be more suitable.

In fact, there's nothing specific about Joplin in the questions you asked. How do you find the relevant code? What does such or such type or variable mean? There's plenty of clues in the description and you can easily search for the keywords in the code. Finding your way around code is not something specific to Joplin, but an important skill you need to have anyway.

We can help however at a higher level, for example by discussing how such or such feature should work, but that probably doesn't apply to this particular issue.

**Comment by Rash419** [comment]
> Hello, the good first issues are here so that you can familiarise yourself with the code base, by working on a relatively simple task. As such we won't provide much technical help about it. Either you can figure it out by yourself and, if so, you might want to apply for GSoC, or you aren't and in that case another project might be more suitable.
> 
> In fact, there's nothing specific about Joplin in the questions you asked. How do you find the relevant code? What does such or such type or variable mean? There's plenty of clues in the description and you can easily search for the keywords in the code. Finding your way around code is not something specific to Joplin, but an important skill you need to have anyway.
> 
> We can help however at a higher level, for example by discussing how such or such feature should work, but that probably doesn't apply to this particular issue.

Cool :)

**Comment by jalajcodes** [comment]
Hi, I am having trouble finding out how to test the new method. I made some changes in some files inside `lib` directory but now how do I test if it works?

I created a new plugin using `testDemoPlugin.sh` and tried to test using it, but it gives me following error
```js
joplin.plugins: Uncaught exception in plugin "org.joplinapp.plugins.SettingsDemo": Error: Property or method "registerSettings" does not exist in "joplin.settings.registerSettings"
```

 This is probably because its still using the old code not the new code I wrote.

**Comment by Rash419** [comment]
> Hi, I am having trouble finding out how to test the new method. I made some changes in some files inside `lib` directory but now how do I test if it works?
> 
> I created a new plugin using `testDemoPlugin.sh` and tried to test using it, but it gives me following error
> 
> ```js
> joplin.plugins: Uncaught exception in plugin "org.joplinapp.plugins.SettingsDemo": Error: Property or method "registerSettings" does not exist in "joplin.settings.registerSettings"
> ```
> 
> This is probably because its still using the old code not the new code I wrote.

I think you need to this new method in plugins>ToggleSidebars>api>JoplinSettings

**Comment by roman-r-m** [comment]
What is `testDemoPlugin.sh`?

**Comment by jalajcodes** [comment]
> What is `testDemoPlugin.sh`?

https://www.github.com/laurent22/joplin/tree/dev/packages%2Fapp-desktop%2FtestPluginDemo.sh

**Comment by roman-r-m** [comment]
Github search couldn't find it, strange.

Yeah, that looks right, it starts dev desktop version.
Might a problem with your changes then. You can use a debugger to see if the method is there.

**Comment by jalajcodes** [comment]
Okay so I figured it out, will create a PR soon 😄

**Comment by aashimawadhwa** [comment]
is this issue still open?
i would like to work on this.

**Comment by jalajcodes** [comment]
> is this issue still open?
> i would like to work on this.

Hi, thanks for showing interest but I already created a PR and it's in review.

**Comment by Mariem166** [comment]
is this still a current issue ?
Can I work on it ?

**Comment by roman-r-m** [comment]
> is this still a current issue ?
> Can I work on it ?

It's already taken. In fact there's a comment right above yours confirming that.
