### ISSUE TITLE
Bug: Clipper stopped finding port in Brave, even with only Joplin extension enabled and Shields Down

### ISSUE THREAD

**Issue by rwperrott** [laurent22/joplin#4616]
Joplin is listening on port 41184, and a manual request to 127.0.0.1:41184/ping, in Brave address bar, returns the expected response, but somehow the port searching state-machine in the javascript file has stopped finding the port, and a re-install doesn't fix it.

It is rather annoying to see "net::ERR_BLOCKED_BY_CLIENT", with no specific cause of the seeming block provided.

So far I can only seem to find the Mozilla plugin flavour, so it would be useful if I had a link to the Chrome flavour of the extension, with JS packing and build instructions, so that I could make a debug version and side-load this, to attempt to discover on which state the failure actually occurs, and maybe if it is a premature timeout issue. 

## Environment

Joplin version: 1.7.11 (1.6.1 plugin)
Platform: Windows
OS specifics: Window 10 Profession 64-bit, 20H2 service pack.
Brave: v1.20.110

## Steps to reproduce

1. Enable extensions developer mode.
2. Disable all extensions except for Joplin.
2. Open an external page.
3. Left-Click on Joplin icon.
4. Joplin pane shows "not_found Service status: Not found [Help]".
5. Right-click on Joplin icon and select Inspect pop-up, so can copy console log.

## Describe what you expected to happen
Joplin pane shows that it is connected.

## Logfile
```
Popup: Init bridge and restore state...
00:09:10.863 main.chunk.js:1 Popup: Init bridge
00:09:10.864 main.chunk.js:1 Popup: Env: prod
00:09:10.864 main.chunk.js:1 findClipperServerPort: Trying 41184
00:09:10.864 main.chunk.js:1 Popup: Creating React app...
00:09:10.873 127.0.0.1:41184/ping:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
00:09:10.873 main.chunk.js:1 findClipperServerPort: Trying 41185
00:09:10.947 127.0.0.1:41185/ping:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
00:09:10.947 main.chunk.js:1 findClipperServerPort: Trying 41186
00:09:10.957 127.0.0.1:41186/ping:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
00:09:10.958 main.chunk.js:1 findClipperServerPort: Trying 41187
00:09:10.961 127.0.0.1:41187/ping:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
00:09:10.961 main.chunk.js:1 findClipperServerPort: Trying 41188
00:09:10.967 127.0.0.1:41188/ping:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
00:09:10.967 main.chunk.js:1 findClipperServerPort: Trying 41189
00:09:10.971 main.chunk.js:1 Sending message  Object
00:09:10.972 127.0.0.1:41189/ping:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
00:09:10.972 main.chunk.js:1 findClipperServerPort: Trying 41190
00:09:10.974 127.0.0.1:41190/ping:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
00:09:10.974 main.chunk.js:1 findClipperServerPort: Trying 41191
00:09:10.975 127.0.0.1:41191/ping:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
00:09:10.975 main.chunk.js:1 findClipperServerPort: Trying 41192
00:09:10.976 127.0.0.1:41192/ping:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
00:09:10.976 main.chunk.js:1 findClipperServerPort: Trying 41193
00:09:10.977 127.0.0.1:41193/ping:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
00:09:11.009 main.chunk.js:1 Popup: Got command: Object
00:09:11.010 index.html:1 Unchecked runtime.lastError: The message port closed before a response was received.
00:09:11.067 main.chunk.js:1 Popup: Saving state Object
00:09:11.382 DevTools failed to load SourceMap: Could not load content for chrome-extension://alofnhikmmkdbbbgpnglcpdollgjjfek/popup/build/static/js/runtime-main.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
00:09:11.383 DevTools failed to load SourceMap: Could not load content for chrome-extension://alofnhikmmkdbbbgpnglcpdollgjjfek/popup/build/static/js/2.chunk.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
00:09:11.383 DevTools failed to load SourceMap: Could not load content for chrome-extension://alofnhikmmkdbbbgpnglcpdollgjjfek/popup/build/static/js/main.chunk.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
00:09:11.383 DevTools failed to load SourceMap: Could not load content for chrome-extension://alofnhikmmkdbbbgpnglcpdollgjjfek/popup/build/static/css/main.chunk.css.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by laurent22** [comment]
You'd get this error ERR_BLOCKED_BY_CLIENT for example if an adblocker blocks a resource. Maybe that's what it is here too, or maybe some other extension.

**Comment by rwperrott** [comment]
@laurent22 I don't think that's the case, because I disabled all the other extensions, and that such behaviour would be inconsistent with being able to successfully request and display the ping URL reply from the address bar.

As requested, I'd like to a reference to the Chrome flavour of the "clipper" extension, including build instructions, so that I can build and side load a modified version of the clipper extension, to see if I can trace the cause of this issue and even find a more reliable way to do this test e.g. based upon https://betterprogramming.pub/chrome-extension-intercepting-and-reading-the-body-of-http-requests-dd9ebdf2348b?gi=17efb95412d9.

**Comment by tessus** [comment]
> As requested, I'd like to a reference to the Chrome flavour of the "clipper" extension.

Not sure what you mean. When you build the clipper, packages are created for Chrome and Firefox. The code is the same.

**Comment by rwperrott** [comment]
I found something in this repo, which mentioned Mozilla and the plugin *.js didn't look the same in the developer window.
Was I correct to assume that it was in this repo? If not where?

**Comment by rwperrott** [comment]
`npm install -g windows-build-tools` seems to have broken links for the (bloated) MS Window Build tools, but hopefully I won't need them.

I haven't used React before, but it looks like the async functions, in `joplin/packages/app-clipper/popup/src/bridge.js', must be compiled into switch-based state machine code I saw in the packed different name .js file, I saw inside Brace, so I'll need to figure out the conceptual mapping and event sequence.

I note on my 1st build attempt of app-clipper, that a surprising 144 MBs of dependencies were downloaded into node_modules/.staging, unlike shared local caches of dependencies used by some other build tools e.g. Maven.

**Comment by tessus** [comment]
> must be compiled into switch-based state machine code

Ok, I have no idea what you are talking about. There's a `BUILD.md` that explains how to build all the different apps including the clipper.

https://github.com/laurent22/joplin/blob/dev/BUILD.md

I suggest to use the forum for user questions. I have unsubscribed from this issue, thus I won't receive any notifications for it anymore.

**Comment by rwperrott** [comment]
Before my prior comment, I used the BUILD.md instructions, for app-clipper, to start building app-clipper/popup.

As for "no idea", reactive (event-based) processing can be implement by (event-based) state machines, e.g. in the generated main.chunk.js; I thought that an interesting optimisation.

My local build successfully completed, so I now have an _unpackaged_ directory of app-clipper files, so I can investigate loading these and attempting to debug this annoying issue.

**Comment by rwperrott** [comment]
It looks the `00:09:10.873 127.0.0.1:41184/ping:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT` log message must be being generated by the default `catch` promise for `fetch(address)`, in `js\main.chunk.js`, generated from line 141 in `src\bridge.js`.

I had a look at https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API and https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch, and it looks like the error input value for a replacement `catch` `Promise` is probably an `Error` object, so may not provide useful extra information, so error debugging this issue, from the extension end, may not be possible.

* It maybe a good idea to chain promises to the `fetch()` `Promise` object, via `.then(Promise)` calls, to reduce or even eliminate await keyword use.

**Comment by rwperrott** [comment]
Yes, not a bug in the extension, but rather in [Brave](https://github.com/brave/brave-browser) browser security.

I raised https://github.com/brave/brave-browser/issues/14445 and it appears that this was caused by a crude security bug in the [Brave](https://github.com/brave/brave-browser) browser, which appears to cripple other extensions too!

I'm temporarily using SRWare Iron for my clipping needs, and have suggested how [Brave](https://github.com/brave/brave-browser) could refine their 127.0.0.1/locahost blocking.
