### ISSUE TITLE
[Web Clipper] Command failed: 7z a -tzip chrome.zip *

### ISSUE THREAD

**Issue by bytrangle** [laurent22/joplin#4618]
## Environment

Joplin version: Joplin clipper 1.8.0
Platform: MacOS
OS specifics: Catalina

## Steps to reproduce
This happens on Mac, and probably Unix/Linux system. 
1. In the terminal, change into the `joplin` directory
2. Run `npm run releaseClipper` to create an optimized production build of the extension
3. You should see a new `dist` folder created in the `joplin/packages/app-clipper` directory. Inside it is a Chrome folder, which contains background script, content scripts, popup build, icons etc. However, the script exit with an error: 
```
Fatal error
Error: Command failed: 7z a -tzip chrome.zip *
/bin/sh: 7z: command not found
```
That's because `7z` is not available on Mac. On its documentation page, it's said that `p7zip` is the command line version of `7z` for Linux/Unix.

https://user-images.githubusercontent.com/28924121/109772042-1bb42f80-7c30-11eb-9037-bd9bf715734e.mp4

## Describe what you expected to happen
The extension files should be compressed in to `.zip` file with no error. I don't know much about archiving and compressing files in the command line, but I think the `release-clipper.js` file should contain a utility to detect Linux/Unix system and use a different CLI tool to compress files, like `tar` or `gzip`.

**Comment by tessus** [comment]
Did you run `npm i`? Afaik it installs 7z. If not, you can install it via brew or macports.

Btw, the package (macports, brew) for 7z is called `p7zip`, but the command line binary is `7z`.
For dev and user questions, please use the forum.

**Comment by bytrangle** [comment]
> Did you run `npm i`? Afaik it installs 7z. If not, you can install it via brew or macports.
> 
> Btw, the package (macports, brew) for 7z is called `p7zip`, but the command line binary is `7z`.
> For dev and user questions, please use the forum.

I don't mean to dilute the Issues question, but I've asked several times, albeit for different issues on the forum but got few views and no answer, so I thought it's better to ask here.

**Comment by tessus** [comment]
>  If developers are required to install p7zip globally, then the BUILD documentation should have made that clear.

The release clipper script is not for users.

> but I've asked several times, albeit for different issues

Yep, I didn't see anything like this in the development category on the forum. Anyway, this is not a bug thus does not belong here on github.

The BUILD.md is usually more than enough to build and run the different components of Joplin.
