### ISSUE TITLE
[issue] graphics and photos attached on a note do only show up in mobile apps

### ISSUE THREAD

**Issue by tomthecat** [laurent22/joplin#462]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile

(notes are encrypted)

Steps to reproduce:
1) attach foto (jpg, png, ...) to a note in Android app
2) foto will show up
3) open desktop app (Linux/Windows tested)
4) foto will not show up, only filename and a reference were shown, i.e.
![EvoMed-logo-01.png](:/47d3497d1be64c9e8d9cb9b89cb58682)

Same happens if you try to add a foto in desktop app: no foto, filename and reference instead.

Expected behaviour:
fotos and graphics attached on a note shoud be visible in Joplin regardless of the OS.

**Comment by laurent22** [comment]
Sounds like you are displaying the editor only on desktop. Click on the "Toggle layout" button in the taskbar and see if it helps.

**Comment by tomthecat** [comment]
You are right. A little bit embarassing for me...
