### ISSUE TITLE
Change strikethrough display behavior in markdown editor

### ISSUE THREAD

**Issue by shbach** [laurent22/joplin#4626]
In the markdown editor if there is `~~` in front of a line, a strikethrough is displayed regardless if there is a corresponding `~~`  at the end. The strikethrough shouldn't be displayed if it isn't a strikethrough yet. The current behavior preemptively makes it difficult to see the text particularly if you aren't intending to strikethrough the entire line. 
![image](https://user-images.githubusercontent.com/5298745/110198182-676c0200-7e05-11eb-8cc5-34983bb9c95d.png)

## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Solus 4.2

## Steps to reproduce

1. Type `~~` in front of text in the markdown editor

## Describe what you expected to happen

Display strikethrough in markdown editor only if text is enclosed by `~~`.

**Comment by CalebJohn** [comment]
This behaviour is from the editor component that Joplin uses. You can request a change [upstream](https://github.com/codemirror/codemirror)

**Comment by shbach** [comment]
@CalebJohn I [requested](https://github.com/codemirror/CodeMirror/issues/6617) a change upstream.

By the way I was using your excellent Rich Markdown plugin and the highlighting provided by the plugin has the desired behavior which was why I wanted consistent behavior for the strikethrough.

![image](https://user-images.githubusercontent.com/5298745/110252831-2a565b80-7f3c-11eb-8259-ae8a914f44f9.png)

**Comment by CalebJohn** [comment]
Thanks, I guess my plugin is the weird one because it has different behaviour for highlighting.

FYI, I tried to modify some CSS to get your desired behaviour for strike through but had no luck. Once CodeMirror 6 has been stabilized for awhile I'd like to migrate Joplin, so eventually this behaviour will be improved.

Something that you can try now is use the following css in userchrome.css

```css
.cm-strikethrough {
    text-decoration: inherit;
    background-color: red;
}
```
