### ISSUE TITLE
[feature request] allow grouping by priority of to do's 

### ISSUE THREAD

**Issue by tomthecat** [laurent22/joplin#463]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

It would be great to have the option to tag to do's with priority levels. For example, there is a to do list with different entries (random order as entered in Joplin):

buy milk
wash bicycle
play tennis
call mum
send flowers to wife

Assign priorities:

(3) buy milk
(3) wash bicycle
(2) play tennis
(3) call mum
(1) send flowers to wife

Order to do's according to set priorities:

(1) send flowers to wife
(2) play tennis
(3) buy milk
(3) wash bicycle
(3) call mum

**Comment by hdpjeffro** [comment]
Yes, please!  =)
