### ISSUE TITLE
Web Clipper Not Working

### ISSUE THREAD

**Issue by rossspaul** [laurent22/joplin#4630]
Web Clipper cannot connect to service.  I start the Joplin client application, web clipper is enabled and it's been working for months and just in the last few days stopped working.  I restored an image of my PC (Windows 10) to see if I did something and after restoring it stopped working again.  Not sure if windows defender or windows update is messing thing up or what?

![WebClippperScreenShot](https://user-images.githubusercontent.com/41873937/110216429-6621f000-7e6c-11eb-8ab4-32d87adc7416.jpg)

It doesn't matter what URL I try and clip, nothing works.  Here are a few:
-https://seekingalpha.com/article/4411371-5-safe-and-cheap-dividend-stocks-to-invest-in-march-2021
-https://www.marketwatch.com/story/buy-these-3-battery-stocks-to-play-the-electric-vehicle-party-but-stay-away-from-this-company-says-ubs-2021-03-06
-https://www.zerohedge.com/markets/when-yields-rise-narratives-fall

Windows 10, Brave Browser both latest versions and service packed.

Joplin version: 1.6.8
Platform: Windows
OS specifics: 10, latest version, serviced packed etc.

## Steps to reproduce

1. Try and clip any website, red dot in clipper at the bottom like it can't connect to the windows service and port

I just want it to clip my websites again.

[log-clipper.txt](https://github.com/laurent22/joplin/files/6095840/log-clipper.txt)

**Comment by markheck** [comment]
i have the same problem since the Brave 1.21.73 update.  looks like a Brave problem or a breaking change.  the error in my Brave console is: Failed to load resource: net::ERR_BLOCKED_BY_CLIENT.

Joplin Web Clipper still works fine with Chrome for me.

**Comment by CalebJohn** [comment]
Looks like brave has extended the trackers & ad blocking to extend to the Joplin web clipping (because it captures web page content it must be stealing user data I guess).

https://discourse.joplinapp.org/t/unable-to-use-the-web-clipper-extension/14964/4

You should probably send a bug report to the brave developers in order to get this fixed.

**Comment by jalajcodes** [comment]
I am currently on Brave 1.21.74 and the clipper extension is fine for me.
My Joplin version is 1.7.11

**Comment by markheck** [comment]
updating to Brave 1.21.74 fixed it for me.   Joplin Web Clipper works now.

Brave issue/fix [14473 ](https://github.com/brave/brave-browser/issues/14473)
