### ISSUE TITLE
WYSIWYG editor bugs -> bold text and lists breaking

### ISSUE THREAD

**Issue by jambon-beurre-vodka** [laurent22/joplin#4633]
Joplin 1.7.10, MacOS. 

I use the WYSIWYG editor (like most normal human beings). 
- When I use bold text and come back to this note later sometimes the text is not bold anymore and will appear as **my text ** 
- When I create a nested list and come back to that note later sometimes the list is broken. When I check the markdown it shows the nested list items had the "-" changed to "\-".

Anyway I don't know what's this autistic obsession with markdown editors from the joplin devs. It's unuseable. When I type notes I don't wanna think about formatting it, it should work magically. Apart from that and some other small issues (all related to WYSIWYG) Joplin is great and 10 times better than evernote but if you could fix these retarded issues that'd be great

**Comment by laurent22** [comment]
Yes, and next time try to be less insulting when you ask for something.
