### ISSUE TITLE
Joplin Window does not show at startup (Mac OS X 10.15.7)

### ISSUE THREAD

**Issue by rreijers** [laurent22/joplin#4635]
## Environment
Joplin 1.7.11 (prod, darwin)
Revision: f560563 (master)
Mac OS X 10.15.7

**Comment by theCollectiv** [comment]
Maybe similar to this one? (but I'm not using mac).
https://github.com/laurent22/joplin/issues/4646

**Comment by spelbergit** [comment]
I'm having the same problem. Seems to happen after change from external display to internal, or when switching user
