### ISSUE TITLE
Android sync stucks after image was shared with JoplinApp

### ISSUE THREAD

**Issue by rumatoest** [laurent22/joplin#4638]
## Environment

Joplin version:  1.7.5
Platform: Android 10
Sync type: WebDav

## Steps to reproduce

1.  Go to your image gallery app (anything that browse your media files)
2.  Share any jpeg image with Joplin
3. Joplin will create a note with image in it
4. Next sync will be indefinite
5. But on another Joplin installation you will be able to see new note, but image will be empty (there will be reference to image in note).
6. Looks like Android app syncs note, but fails to upload note image

**Comment by rumatoest** [comment]
Eventually sync fail with next error


```
03-08T10:10:49,20,"""Error: uploadBlob: PUT https://webdav.yandex.ru/joplin/.resource/5b69bcb4c41447d7a4ad861a448d4fa1: Error: unexpected end of stream

index.android.bundle:1217:3088

y@index.android.bundle:109:587

index.android.bundle:109:1890

y@index.android.bundle:109:587

o@index.android.bundle:109:1066

index.android.bundle:109:1238

f@index.android.bundle:125:155

index.android.bundle:125:864

y@index.android.bundle:130:581

C@index.android.bundle:130:947

callImmediates@index.android.bundle:130:3004

value@index.android.bundle:27:2919

index.android.bundle:27:1095

value@index.android.bundle:27:2611

value@index.android.bundle:27:1065

value@[native code]

value@[native code]""


```

**Comment by roman-r-m** [comment]
This looks more like a problem on the server-side

**Comment by rumatoest** [comment]
But there are no issues in Windows desktop app. I can upload any images by webdav.

**Comment by roman-r-m** [comment]
I think it may be related to https://github.com/laurent22/joplin/pull/4557 but I am not sure as I could not reproduce it.

**Comment by rumatoest** [comment]
It still active for me. Unfortunately I have no capacity to fix it by myself.

**Comment by roman-r-m** [comment]
If this was related to sharing then it has been fixed in one of recent versions. If you still have the issue can you try to reinstall the app on Android?
