### ISSUE TITLE
Export to PDF prints the # heading twice

### ISSUE THREAD

**Issue by GogoAkira** [laurent22/joplin#4640]
Export to PDF prints the title of the note which is just the first heading and then prints the first heading, so it gets printed twice

below is what my notes are and screen shot of PDF.

Win10

Joplin 1.7.11 (prod, win32)

Client ID: f042b9fabacc46a7a961dd454c8ecfeb
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f560563d8 (master)

![Screenshot 2021-03-08 090348](https://user-images.githubusercontent.com/9360410/110338969-3ea66100-7fed-11eb-9f03-e213496aceb8.jpg)

# Pointers as function arguments
### Calling function
```c 
int main()
```
a function that calls another function
### Called function
a function that is called by `main()`

**Comment by CalebJohn** [comment]
You can add a bit of CSS to your userstyle.css that will disable this. Take a look [here](https://discourse.joplinapp.org/t/remove-superfluous-note-names/9862/40)

The alternative is just to remove the h1 from the top of your note because it's just duplicating the title.

**Comment by GogoAkira** [comment]
well awesome :) I'll add CSS :)

**Comment by CalebJohn** [comment]
That's what I do as well :)
