### ISSUE TITLE
sync with nextcloud, onedrive between client of Android, and Linux failed

### ISSUE THREAD

**Issue by Kenarso** [laurent22/joplin#4644]
## Environment

Joplin version: Joplin 1.7.11 (prod, linux)

Client-ID: 9d929cc89ab747fcbb10e2a8678ebbb3
Sync-Version: 2
Profil-Version: 34
Unterstützter Schlüsselbund: Nein

Revision: f560563 (master)

Android 1.7.5
Platform: Android/Linux/ChromeOS
OS specifics: xubuntu 20.04, Android 10, ChromeOS (aktuell)

## Steps to reproduce

1. configure
2. synchronise
3. failure

## Describe what you expected to happen
I tried to start Joplin on my Linux desktop today and it disappeared.
I probably deleted the app image by mistake. No problem, quickly downloaded and reconnected to my Onedrive to sync. But what do I see. Nothing is synchronized. I only get error messages.
No matter, I thought, I wanted to "move" to my own Nextcloud. So simply reconfigure in the Joplin Android app to the nextcloud. That fails already once. Then I configure WebDav, which then worked, but synchronized still nothing.
Please refer to the log for the corresponding messages:

## Logfile
![Screenshot_20210309-112449](https://user-images.githubusercontent.com/9461091/110458091-a7640b00-80cb-11eb-9096-ea72ffc297db.png)

**Comment by Kenarso** [comment]
ok, with Linux it works now. But only if I enable the option "Ignore TLS certificate errors" here.
Unfortunately, I cannot do this with the Android version.
My nextcloud runs with a self-signed certificate and that seems to be the problem.
Is there a solution in sight in the foreseeable future?

**Comment by roman-r-m** [comment]
There's a PR pending.
