### ISSUE TITLE
Created image resource via API is scaled / reduced

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#4655]
When a new image is created as a resource (JPG, PNG, ...) via API, the file is automatically scaled and not the original file is attached as a resource. 

## Environment

Joplin 1.7.11 (prod, win32)

Client ID: fea0ba97613b45d8b1c8ee33e9f08413
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f560563d8 (master)

## Steps to reproduce

1. Create a image resource via API in a Plugin or with a web request
```
await joplin.data.post(
	["resources"],
	null,
	{ title: "test.jpg" }, // Resource metadata
	[
		{
			path: "/path/to/test.jpg", // Actual file
		},
	]
);
```

2. Check file in `.config\joplin-desktop\resources`

## Describe what you expected to happen

The original file should be uploaded, or there should be an parameter for scaling the image.

**Comment by roman-r-m** [comment]
As a workaround you can try uploading your picture with a fake file extension so that Joplin does not recognize it as an image and then change attributes using https://joplinapp.org/api/references/rest_api/#put-resources-id

**Comment by laurent22** [comment]
Yes the function that imports an image has a parameter to compress the picture or not, and I guess by default it's compressed. We should change that and make it not compressed when called via the API.

**Comment by nishantwrp** [comment]
Hi @laurent22, can I work on this issue?

**Comment by nishantwrp** [comment]
As @laurent22  suggested we can disable compressing of images uploaded through APIs. But also, as the same API is used by Plugins. There maybe a use case when a plugin wants to compress large images. So, should I also add a config option in the POST resources endpoint something like compress_images that if set to true will compress large images and it will be false by default?

**Comment by laurent22** [comment]
No let's not add an option. If it's called from the API or from a plugin, it should not compress the image.
