### ISSUE TITLE
how to display line number at left? like vscode

### ISSUE THREAD

**Issue by AllenLeic** [laurent22/joplin#4656]
## Environment

Joplin version: 1.7.11
Platform: Windows
OS specifics: 

## Steps to reproduce

1. 
2. 
3.

**Comment by roman-r-m** [comment]
This isn't a bug, is it? Should have checked the forum first: https://discourse.joplinapp.org/t/plugin-to-enable-line-numbers/12735/12

**Comment by CalebJohn** [comment]
@roman-r-m a lot of people see the GitHub issues as a method of communicating directly with the devs, and there's a perception that things on the forum are more likely to be ignored/not seen.
That's not true of this project, @AllenLeic please use the forum in the future.
