### ISSUE TITLE
[Feature Request][Question] Evernote synchronisation

### ISSUE THREAD

**Issue by ehhc** [laurent22/joplin#466]
Some of my colleagues are using evernote as a note taking app. This comes (besides other reasons) from the fact that collaborative working is possible there. I would wish for an evernote sync so that it’s possible to contribute to the shared notes from within boostnote.

Is this possible with your app? Might it be implemented?

**Comment by laurent22** [comment]
Sync with Evernote would be very complex since they use HTML and we use Markdown so that it's unlikely it will ever be supported.

**Comment by ehhc** [comment]
@laurent22 thanks for the quick answer and the clarification. Sad to hear that though
