### ISSUE TITLE
"joplin has stopped" on Mediatek android 9

### ISSUE THREAD

**Issue by johnb0647** [laurent22/joplin#4663]
## Environment

Joplin version:    1.7.5
Platform:             Android 
OS specifics:      V9

## Steps to reproduce

1.   Attempt to start app
2. 
3. 

## Describe what you expected to happen
I expected Joplin to load.

**Comment by roman-r-m** [comment]
Please provide a crash dump, see https://joplinapp.org/debugging/#creating-a-low-level-bug-report-on-android

**Comment by johnb0647** [comment]
Attempted to generate crash dump as outlined in link provided.

Started Device
Verified Developer Options ON
Attempted to start Joplin - Failed with "Joplin stopped" message
Pressed "Bug Report" on "shutdown" menu
    Clicked on "Take Bug Report"
        Msg:    "This will collect information....."
        click "Report"  @ 09:58
    90 min later no sign of a report or notification

Searched every folder I could think of where such a report might be filed.
Including "notifications" 
    No joy!

NOTE: Downloaded "ADB Android Platform tools for Linux" but so far I can't find any instructions for use.
  
      I continue to research.

**Comment by roman-r-m** [comment]
If have adb installed you can simply use it to get the log. You just need to enable USB debugging, connect your tablet, start adb logcat on your computer, open Joplin, and wait for it to crash.

Then in the output there should be a line containing `FATAL`, please share it and a few lines before and after for context. Make sure to check for any private information, though I doubt there's going to be any.

Here's a guide to using adb logcat: https://developer.android.com/studio/command-line/logcat

**Comment by johnb0647** [comment]
Per your instructions ran "adb logcat" and got a continuous stream of data lines at rate of several hundred per minute.  Disconnected WiFi and shut down everything I could think of on device to minimize.

Stopped logcat and ran again as "adb logcat > ~/Desktop/logcat.log

started Joplin, got failure message and request to report

Reported

stopped adb with Ctrl-C in terminal

Logfile consists of 6524 lines.
15 have "joplin" associated
2 have "fatal" associated and one or more "joplin" related lines are near.

I can send the entire log if desired.

Here are the two excerpts with both "joplin" and "Fatal" centered on about 20 lines for context

NUMBER ONE

W/System.err( 7516): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:87)
W/System.err( 7516): 	... 23 more
W/System.err( 7516): Caused by: java.lang.VerifyError: com/facebook/react/views/view/ReactDrawableHelper
W/System.err( 7516): 	at com.facebook.react.views.view.ReactViewManager.setNativeBackground(ReactViewManager.java:164)
W/System.err( 7516): 	... 26 more
W/dalvikvm( 7516): threadid=1: calling UncaughtExceptionHandler
E/AndroidRuntime( 7516): FATAL EXCEPTION: main
E/AndroidRuntime( 7516): Process: net.cozic.joplin, PID: 7516
E/AndroidRuntime( 7516): com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'nativeBackgroundAndroid' of a view managed by: RCTView
E/AndroidRuntime( 7516): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:102)
E/AndroidRuntime( 7516): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
E/AndroidRuntime( 7516): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
E/AndroidRuntime( 7516): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:49)
E/AndroidRuntime( 7516): 	at

NUMBER TWO

W/System.err( 7637): Caused by: java.lang.reflect.InvocationTargetException
W/System.err( 7637): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 7637): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 7637): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:87)
W/System.err( 7637): 	... 23 more
W/System.err( 7637): Caused by: java.lang.VerifyError: com/facebook/react/views/view/ReactDrawableHelper
W/System.err( 7637): 	at com.facebook.react.views.view.ReactViewManager.setNativeBackground(ReactViewManager.java:164)
W/System.err( 7637): 	... 26 more
W/dalvikvm( 7637): threadid=1: calling UncaughtExceptionHandler
E/AndroidRuntime( 7637): FATAL EXCEPTION: main
E/AndroidRuntime( 7637): Process: net.cozic.joplin, PID: 7637
E/AndroidRuntime( 7637): com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'nativeBackgroundAndroid' of a view managed by: RCTView
E/AndroidRuntime( 7637): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:102)
E/AndroidRuntime( 7637): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
E/AndroidRuntime( 7637): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)

**Comment by roman-r-m** [comment]
I found a bunch of bug reports with the same error, all seem to be for Android version 4.x. Apparently react-native, on which Joplin mobile is built, dropped support for Android 4 at some point.

I have initially thought you meant here that your device is running Android 9
```
Platform: Android
OS specifics: V9
```
but I am now starting to doubt it. Can you double-check the version please.

**Comment by johnb0647** [comment]
I've been reviewing my activities that might have had an impact on this problem.  At about the same time I was following some on line menu's of android background apps that eat up battery life but are usually unnecessary, except to advertisers perhaps, and can be disabled.  With this kind of thing I am very conservative and I disable one thing at a time and wait a few days to see if anything I care about is impacted.  However, as I remember, I was not using Joplin much on the android device at the time so something might have slipped through.

Is it possible to find a list of android services/background apps that Joplin (on android)  requires?

**Comment by roman-r-m** [comment]
> Is it possible to find a list of android services/background apps that Joplin (on android) requires?

I do not think there are any.

**Comment by johnb0647** [comment]
Issue has NOT been resolved.

I continue to update joplin on the device every new update with no improvement.
I found some older versions and tried them with no improvement.

As I said.... Joplin worked fine on this device for months then suddenly stopped.  Calling the app results in message "Unfortunately Joplin has had to stop"

**Comment by roman-r-m** [comment]
@johnb0647 can you confirm Android version your tablet runs?
As I wrote above, the error is similar to what I saw on Android 4.x. If you have this version there's not much we can do as react-native, on which Joplin is built, dropped the support for Android below version 5 sometime ago.
