### ISSUE TITLE
Sort order: Should be left- or right-aligned instead of centered

### ISSUE THREAD

**Issue by Jonta** [laurent22/joplin#4671]
## Environment

Joplin version: 1.7.5, Database v34, FTS enabled: 1
Platform: Android
OS specifics: 10

## Steps to reproduce

1. Open app for the 1st time
2. Tap 3-horisontal-line menu-button top right

## Describe what you expected to happen

Text was left-aligned because English and not a headline

See e.g. https://practicaltypography.com/centered-text.html =)

## Logfile

No errors in Configuration -> Log

**Comment by arjundashrath** [comment]
@Jonta is this issue sorted? I could not reproduce it

**Comment by Jonta** [comment]
> @Jonta is this issue sorted? I could not reproduce it

@arjundashrath Not sorted. Still an issue. I'll try to reproduce it in Android Studio

**Comment by Jonta** [comment]
I'm having problems even launching Android Studio these days, but I've confirmed with another Android-user (Android 9, I think) that they're also experiencing this

**Comment by roman-r-m** [comment]
Looks ok for me in Android 11 running in emulator:
![Screenshot 2021-03-22 20:52:51](https://user-images.githubusercontent.com/995612/112057010-a497fa00-8b50-11eb-88d0-b3133eec2f01.png)

**Comment by Jonta** [comment]
@roman-r-m You've reproduced the behaviour I found

**Comment by roman-r-m** [comment]
Oh, of course, you're right! And I apparently can't read.

I wouldn't say it's a bug though.

**Comment by Jonta** [comment]
=)

It may be intended behaviour, but I argue that centered is worse than right- or left-aligned

**Comment by roman-r-m** [comment]
I had a look at Google Keep and Evernote - both have left-aligned text. And I have to admit it looks nicer. Both have icons for each item of the list though, that probably helps too.

**Comment by Jonta** [comment]
Remember the right-alignment for [right-to-left-languages](https://en.m.wikipedia.org/wiki/Right-to-left). Joplin currently has translations for Arabic and Persian.

**Comment by Jonta** [comment]
Still requires the community's attention

**Comment by Jonta** [comment]
Still requires the community's attention

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.1.4 - Database v39

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.3.4 - Database v39

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.4.3 - Database v39

**Comment by Jonta** [comment]
@laurent22 Could this get a label from exemptLabels in stale.yml? =)

https://github.com/laurent22/joplin/blob/e06a6409001df1c6d0e6d249806f6c96ff40a9e5/.github/stale.yml

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.6.8 - Database v41

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.6.8 - Database v41

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.7.2 - Database v41

@laurent22 Please label this so I don't have to keep updating this

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.7.2 - Database v41

@laurent22 Please label this so I don't have to keep updating this

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.7.2 - Database v41

@laurent22 Please label this so I don't have to keep updating this

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.8.1 - Database v41

@laurent22 Please label this so I don't have to keep updating this

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.8.1 - Database v41

@laurent22 Please label this so I don't have to keep updating this

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.8.1 - Database v41

@laurent22 Please label this so I don't have to keep updating this

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.8.1 - Database v41

@laurent22 Please label this so I don't have to keep updating this

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.8.1 - Database v41

@laurent22 Please label this so I don't have to keep updating this

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.8.1 - Database v41

@laurent22 Please label this issue so I don't have to keep updating this

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.8.1 - Database v41

@laurent22 Please label this issue so I don't have to keep updating this
