### ISSUE TITLE
Build error while running command npm install

### ISSUE THREAD

**Issue by danis29ah** [laurent22/joplin#4674]
While trying to build joplin and running the command `npm install` from root package of Joplin i get the following messages:

```

> @joplin/app-desktop@1.8.0 postinstall /home/ubuntu/Desktop/projects/joplin/packages/app-desktop
> npm run build
npm ERR! code 1
npm ERR! path /home/ubuntu/Desktop/projects/joplin
npm ERR! command failed
npm ERR! command sh -c lerna bootstrap --no-ci

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-03-14T20_02_31_410Z-debug.log
npm ERR! code 1
npm ERR! path /home/ubuntu/Desktop/projects/gsoc/joplin
npm ERR! command failed
npm ERR! command sh -c npm run bootstrap --no-ci && npm run build

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-03-14T20_02_31_490Z-debug.log


```
**Contents of /home/ubuntu/.npm/_logs/2021-03-14T20_02_31_410Z-debug.log**

0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'run',
0 verbose cli   'bootstrap',
0 verbose cli   '--no-ci'
0 verbose cli ]
1 info using npm@7.6.3
2 info using node@v15.11.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/ubuntu/Desktop/projects/joplin/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/home/ubuntu/.npmrc Completed in 0ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 7ms
19 verbose npm-session 22744222078cd565
20 timing npm:load Completed in 15ms
21 timing command:run Completed in 19633ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:378:20)
22 verbose stack     at maybeClose (node:internal/child_process:1067:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
23 verbose cwd /home/ubuntu/Desktop/projects/joplin
24 verbose Linux 5.8.0-44-generic
25 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "bootstrap" "--no-ci"
26 verbose node v15.11.0
27 verbose npm  v7.6.3
28 error code 1
29 error path /home/ubuntu/Desktop/projects/joplin
30 error command failed
31 error command sh -c lerna bootstrap --no-ci
32 verbose exit 1

**Contents of /home/ubuntu/.npm/_logs/2021-03-14T20_02_31_490Z-debug.log**
0 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'install' ]
1 info using npm@7.6.3
2 info using node@v15.11.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/ubuntu/Desktop/projects/joplin/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/home/ubuntu/.npmrc Completed in 0ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 6ms
19 verbose npm-session 7d30c5f594d16367
20 timing npm:load Completed in 14ms
21 timing arborist:ctor Completed in 0ms
22 timing idealTree:init Completed in 608ms
23 timing idealTree:userRequests Completed in 0ms
24 silly idealTree buildDeps
25 timing idealTree:#root Completed in 0ms
26 timing idealTree:buildDeps Completed in 1ms
27 timing idealTree:fixDepFlags Completed in 1ms
28 timing idealTree Completed in 629ms
29 timing arborist:ctor Completed in 0ms
30 timing reify:loadTrees Completed in 1028ms
31 timing reify:diffTrees Completed in 24ms
32 silly reify moves {}
33 timing reify:retireShallow Completed in 0ms
34 timing reify:createSparse Completed in 0ms
35 timing reify:loadBundles Completed in 0ms
36 timing reify:unpack Completed in 8ms
37 timing reify:unretire Completed in 0ms
38 timing build:queue Completed in 0ms
39 timing build:deps Completed in 0ms
40 timing build Completed in 0ms
41 timing reify:build Completed in 0ms
42 timing reify:trash Completed in 0ms
43 timing reify:save Completed in 198ms
44 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 946ms
45 timing auditReport:getReport Completed in 951ms
46 timing metavuln:cache:get:security-advisory:ini:Ycq69/gaCzr/G/fbN43rDLIsHS7IdZHzW5bh0ju4uwHwvENyyzefC75bnxzsKQ1M+jh/75af+MnibiJLXd61Iw== Completed in 47ms
47 timing metavuln:cache:get:security-advisory:madge:ybdgjcpRZ4C3+Ev2az+sANhGQ801OwLa3lMb5rlCDHBTfj+p7/GCgOLaRK/eN4jDfjpn245X4/myF1a1PaFVSw== Completed in 40ms
48 http fetch GET 304 https://registry.npmjs.org/madge 113ms (from cache)
49 timing metavuln:packument:madge Completed in 116ms
50 timing metavuln:load:security-advisory:madge:1652 Completed in 1ms
51 timing metavuln:calculate:security-advisory:madge:1652 Completed in 118ms
52 http fetch GET 304 https://registry.npmjs.org/ini 216ms (from cache)
53 timing metavuln:packument:ini Completed in 221ms
54 timing metavuln:load:security-advisory:ini:1589 Completed in 1ms
55 timing metavuln:calculate:security-advisory:ini:1589 Completed in 226ms
56 http fetch GET 200 https://registry.npmjs.org/gitconfiglocal 23ms (from cache)
57 timing metavuln:packument:gitconfiglocal Completed in 24ms
58 timing metavuln:cache:get:security-advisory:gitconfiglocal:7khazJ4vKK2hW1ncyF57L8iczboD0gJUlqiFJfMYVCms/v3qOfDnlKhMpXjswhm0V0Ab5u/X17WxkglTQNO3FA== Completed in 24ms
59 timing metavuln:load:security-advisory:gitconfiglocal:Ycq69/gaCzr/G/fbN43rDLIsHS7IdZHzW5bh0ju4uwHwvENyyzefC75bnxzsKQ1M+jh/75af+MnibiJLXd61Iw== Completed in 0ms
60 timing metavuln:calculate:security-advisory:gitconfiglocal:Ycq69/gaCzr/G/fbN43rDLIsHS7IdZHzW5bh0ju4uwHwvENyyzefC75bnxzsKQ1M+jh/75af+MnibiJLXd61Iw== Completed in 24ms
61 timing metavuln:cache:get:security-advisory:global-prefix:2Y1tVIAOCQDQ7wuh0WDPOPCyHKpY0ClBm+v4U6dukj413sf6DLnn0+K5kGceXZ1HOmT7cfj8aBWZWnFE2DXNkg== Completed in 23ms
62 timing metavuln:cache:get:security-advisory:rc:/2MFlZ/T1CPQQswjJhNhhlG4q5EG45VjjuYqMInN8sTOeP2ga8AcQhNm9qWbv2d5ZF/9iKyTNk1faKbtVHHNYg== Completed in 20ms
63 timing metavuln:cache:get:security-advisory:config-chain:/wNYO5/PZ/TMyocbR/sMEk6kzCih8ZU0AJ1XlupzixBTzLGJD8M0PHlE/J6IADbzOMfA50f9F8q/TNbssGAIZw== Completed in 28ms
64 http fetch GET 304 https://registry.npmjs.org/global-prefix 86ms (from cache)
65 timing metavuln:packument:global-prefix Completed in 88ms
66 timing metavuln:load:security-advisory:global-prefix:Ycq69/gaCzr/G/fbN43rDLIsHS7IdZHzW5bh0ju4uwHwvENyyzefC75bnxzsKQ1M+jh/75af+MnibiJLXd61Iw== Completed in 0ms
67 timing metavuln:calculate:security-advisory:global-prefix:Ycq69/gaCzr/G/fbN43rDLIsHS7IdZHzW5bh0ju4uwHwvENyyzefC75bnxzsKQ1M+jh/75af+MnibiJLXd61Iw== Completed in 88ms
68 http fetch GET 304 https://registry.npmjs.org/config-chain 90ms (from cache)
69 timing metavuln:packument:config-chain Completed in 94ms
70 timing metavuln:load:security-advisory:config-chain:Ycq69/gaCzr/G/fbN43rDLIsHS7IdZHzW5bh0ju4uwHwvENyyzefC75bnxzsKQ1M+jh/75af+MnibiJLXd61Iw== Completed in 0ms
71 timing metavuln:calculate:security-advisory:config-chain:Ycq69/gaCzr/G/fbN43rDLIsHS7IdZHzW5bh0ju4uwHwvENyyzefC75bnxzsKQ1M+jh/75af+MnibiJLXd61Iw== Completed in 95ms
72 http fetch GET 304 https://registry.npmjs.org/rc 249ms (from cache)
73 timing metavuln:packument:rc Completed in 252ms
74 timing metavuln:load:security-advisory:rc:Ycq69/gaCzr/G/fbN43rDLIsHS7IdZHzW5bh0ju4uwHwvENyyzefC75bnxzsKQ1M+jh/75af+MnibiJLXd61Iw== Completed in 1ms
75 timing metavuln:calculate:security-advisory:rc:Ycq69/gaCzr/G/fbN43rDLIsHS7IdZHzW5bh0ju4uwHwvENyyzefC75bnxzsKQ1M+jh/75af+MnibiJLXd61Iw== Completed in 254ms
76 timing auditReport:init Completed in 494ms
77 timing reify:audit Completed in 1447ms
78 timing reify Completed in 2511ms
79 timing command:install Completed in 22487ms
80 verbose stack Error: command failed
80 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
80 verbose stack     at ChildProcess.emit (node:events:378:20)
80 verbose stack     at maybeClose (node:internal/child_process:1067:16)
80 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
81 verbose cwd /home/ubuntu/Desktop/projects/joplin
82 verbose Linux 5.8.0-44-generic
83 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "install"
84 verbose node v15.11.0
85 verbose npm  v7.6.3
86 error code 1
87 error path /home/ubuntu/Desktop/projects/joplin
88 error command failed
89 error command sh -c npm run bootstrap --no-ci && npm run build
90 verbose exit 1

**OS:Ubuntu 20.04.2 LTS
Node: v15.11.0
npm: 7.6.3**

**Comment by roman-r-m** [comment]
Try with node version 12

**Comment by danis29ah** [comment]
Thanks. It builds now!
