### ISSUE TITLE
[Feature Request] Audio notes

### ISSUE THREAD

**Issue by navxio** [laurent22/joplin#468]
Recording voice notes and storing them in the cloud.

**Comment by foxmask** [comment]
Hi,
can you elaborate your feature request ? 'cause it's a little bit empty.

**Comment by navdeepio** [comment]
@foxmask hi, done

**Comment by luckydays** [comment]
Totally support the request.
It would be really great to be able to record the audio notes in Joplin on the go (especially on iOS app 😄 )

**Comment by sunjam** [comment]
It is helpful to record audio into notes in the background while doing other things: writing text, attaching arbitrary files, taking photos.

**Comment by danielestevez** [comment]
More support here for the request! It's the only thing that keeps me still using Evernote!! :pray:

**Comment by IpeTek** [comment]
Really wish this feature would make it! Using short voice memos every day. But storing them on NC, for now, because the record-find-attach-delete-the-original process is so laborious with Joplin and a recorder app.

**Comment by archont00** [comment]
@IpeTek: How do you get your voice memos to NC? My way, however sub par:

- Use built in Voice recorder (Samsung in my case) + rename manually.
- Setup FolderSync app to one-way sync of Voice Recordings to my NC via WebDav and removing from local recordings folder. (Once a day schedule.)
- Search via file name in a dedicated NC folder (via NC Android App or any other interface).

Having the ability to make a voice recording directly via '+' button in Android app would be way easier. (Create a new note or add a new recording to an existing note.)

**Comment by nomatica** [comment]
Would  really like this feature.

**Comment by sunjam** [comment]
Open please.

**Comment by nomatica** [comment]
I am still interested in this feature. Ideally there might be a quick add  in the joplin app, that would allow me to choose a way to capture something quickly in both web and app. 
1) Text 2) audio 3) video 4) other???

**Comment by sunjam** [comment]
not stale

**Comment by sunjam** [comment]
Open please.

**Comment by sunjam** [comment]
Still important :)

**Comment by LightTemplar** [comment]
No chance?

**Comment by wisdom420** [comment]
Please, this is a much needed feature.

**Comment by nomatica** [comment]
@wisdom420 I agree

**Comment by CntrlX** [comment]
how is this completed?

**Comment by hyuri** [comment]
Sorely missing this feature. Even the bare-bones Google Keep has it.

Why was this marked `completed`?
