### ISSUE TITLE
Left panel of Preference / Settings doesn't scroll

### ISSUE THREAD

**Issue by amandamcg** [laurent22/joplin#4682]
## Environment

Joplin version: Joplin 1.7.11 (prod, darwin)
Platform: OSX
OS specifics: Big Sur

## Steps to reproduce

1. Open Settings / Preferences
2. Have lots of plugins installed
3. Have a small window size

## Describe what you expected to happen

Currently you cannot scroll to access all the Plugin settings if you have too many :-) installed and your window is too small. 

Expected it to scroll like the Notebook list.

## Logfile
n/a

**Comment by CalebJohn** [comment]
Hi @amandamcg 

This was added in 414b3636d95edd4f58a0bcdb6c5ea1015a37d146, it will be working in v1.8.0.

**Comment by amandamcg** [comment]
Awesome thanks for the update!
