### ISSUE TITLE
UI: Android: Undo- and redo-buttons should be right above the keyboard

### ISSUE THREAD

**Issue by Jonta** [laurent22/joplin#4685]
## Environment

Joplin version: 1.7.5
Platform: Android
OS specifics: 10

## Steps

1. New note
2. Type a word
3. Arrow-icon similar to a back-arrow appears near the top-left corner

## Expected

Arrows right above the keyboard, closer to my typing fingers, not having to maneuver my hand around to prevent myself from obscuring the text

If this is a setting I think right-above-the-keyboard should be the default

## Logfile

No relevant errors

**Comment by vasut02** [comment]
Hi Jonta, I would like to work on this issue

**Comment by Jonta** [comment]
Still requires the community's attention

**Comment by Jonta** [comment]
Still requires the community's attention

**Comment by Jonta** [comment]
Still requires the community's attention

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.1.4 - Database v39

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.3.4 - Database v39

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.4.3 - Database v39

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.6.8 - Database v41

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.6.8 - Database v41

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.7.2 - Database v41

@laurent22 Please label this so I don't have to keep updating this

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.7.2 - Database v41

@laurent22 Please label this so I don't have to keep updating this

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.7.2 - Database v41

@laurent22 Please label this so I don't have to keep updating this

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.8.1 - Database v41

@laurent22 Please label this so I don't have to keep updating this

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.8.1 - Database v41

@laurent22 Please label this so I don't have to keep updating this

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.8.1 - Database v41

@laurent22 Please label this so I don't have to keep updating this

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.8.1 - Database v41

@laurent22 Please label this so I don't have to keep updating this

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.8.1 - Database v41

@laurent22 Please label this so I don't have to keep updating this

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.8.1 - Database v41

@laurent22 Please label this issue so I don't have to keep updating this
