### ISSUE TITLE
Table popup in the WYSIWYG editor doesn't respect dark mode.

### ISSUE THREAD

**Issue by jalajcodes** [laurent22/joplin#4686]
## Environment

Joplin version: Dev, 1.7.11
Platform: Windows 10
OS specifics: 19043.867

## Steps to reproduce

1. Go to Tools > Options > Appearance > Theme
2. Switch to any dark theme.
3. Switch to the WYSIWYG editor.
4. Click on table popup.
5. See the white popup

![image](https://user-images.githubusercontent.com/17108695/111307828-f982ce80-867f-11eb-9d3e-4d38a6a54969.png)

## Describe what you expected to happen
Popup should be dark in dark themes.

## Logfile
Nothing interesting there.

**Comment by jalajcodes** [comment]
I would like to work on this if possible.

**Comment by CalebJohn** [comment]
Hi @jalajcodes 

Please have a look at the [Pull Request Guidelines](https://joplinapp.org/gsoc2021/pull_request_guidelines/). Specifically guideline number 1.
