### ISSUE TITLE
Goto Anything jumping away from "All notes" notebook

### ISSUE THREAD

**Issue by rodolf0** [laurent22/joplin#4697]
Selecting a Note by using "Goto Anything" functionality while viewing your notes through "All notes" triggers a Notebook change. 

- This is inconsistent with directly clicking on a note while in the same "All notes" notebook view.
- It loses user's current working context (visible list of all notes).

## Environment
Joplin version: 1.7.11 and earlier.
Platform: Linux (possibly All)

## Expected behavior
Triggering "Goto Anything" and selecting a note shouldn't change Notebook selection if currently focused on "All notes". Selected notebook should remain "All notes".

When viewing all notes, possibly sorted by most recently updated first, jumping through notes via "Goto Anything" shouldn't force the user to click back on "All notes" to regain visibility of full list after navigation.

**Comment by jalajcodes** [comment]
I am working on it. 😉

**Comment by jalajcodes** [comment]
@laurent22 is it alright if I also edit the wrong shortcut key [mentioned here](https://joplinapp.org/#goto-anything) in the same PR?

**Comment by rodolf0** [comment]
This has now regressed :-( Jumping to a note via Goto anything when "All notes" is selected navigates away from "All notes" to a specific notebook.

**Comment by jalajcodes** [comment]
> This has now regressed :-( Jumping to a note via Goto anything when "All notes" is selected navigates away from "All notes" to a specific notebook.

Oh. I'll check it this weekend.
