### ISSUE TITLE
Code Block doesn't work in tables in Rich text

### ISSUE THREAD

**Issue by aashrafh** [laurent22/joplin#4699]
## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Linux 5.10.15-1-MANJARO

## Steps to reproduce

1. Make a code block within a table in Rich Text
2. Switch to another note/notebook
3. Go back to the note with the table

## Describe what you expected to happen
The code should be displayed as a code block
![Screenshot_20210317_212012](https://user-images.githubusercontent.com/40968967/111525716-9324ab80-8766-11eb-9204-368dc39834ea.png)

## Logfile
The code is displayed in Markdown mode
![Screenshot_20210317_212036](https://user-images.githubusercontent.com/40968967/111525769-a0da3100-8766-11eb-9a8f-24ccc6c47f3b.png)

**Comment by aashimawadhwa** [comment]
i would like to work on this issue?

**Comment by aashimawadhwa** [comment]
hey stale bot.
