### ISSUE TITLE
Changed notes don’t update on sync if it’s already open

### ISSUE THREAD

**Issue by da2x** [laurent22/joplin#4700]
## Steps to reproduce

1. On PC 1, create a note. Sync it. Leave the note selected in Joplin and leave Joplin running.
2. On PC 2, find the note you created. Make change to it. Sync it.
3. On PC 1, sync.

## Expected results:

The note should update after sync on PC 1.

## Actual results:

The note doesn’t update. You need to click and select another note and then click back to select the updated not for it to refresh.

## Environment

Joplin version: 1.7.11
Platform: macOS, Linux, and Windows
OS specifics: n/a

**Comment by Philipp91** [comment]
+1 I think this is quite important because, when the user does not notice, they edit the old version and thus cause a conflict, which is always annoying to handle. If Joplin can't automatically resolve conflicts, then it should at least try to minimize their occurrence.

**Comment by Philipp91** [comment]
One could even go so far as to block the UI with a (closable) overlay when the user tries to edit a note for which the sync is overdue by more than 2x the sync interval.

**Comment by fakeYanss** [comment]
+1，I also got this unexpected result when I try to sync between mobile and desktop.

**Comment by Philipp91** [comment]
It has not been fixed. I encounter this every day with v1.8.5.

**Comment by da2x** [comment]
Still an issue.

**Comment by Philipp91** [comment]
Still an issue.
