### ISSUE TITLE
Language: Plural instead of singular when deleting 1 note

### ISSUE THREAD

**Issue by Jonta** [laurent22/joplin#4701]
## Environment

Joplin version: 1.7.5, database v34
Platform: Android
OS specifics: 10

## Steps to reproduce

1. Long-press a note
2. Tap rubbish-bin-icon
3. "Delete these notes?" appears

## Describe what you expected to happen

"Delete this note?" appears

Not only more grammatically correct, but removes the user wondering "wait, did I select more than 1 note"?

## Logfile

None relevant to issue

**Comment by Jonta** [comment]
And:

"Delete [name of note]?" would be better. Gives even more confidence that I'm deleting the note I want to delete

For selection of multiple, I suggest a bulleted list of them. To a point at least. Max of 10 or 20 perhaps

Related enough that it seems the same person might work on this at the same time as in the 1st post

**Comment by arpitg24** [comment]
Is this a valid bug, can anyone confirm this?

**Comment by lkiThakur** [comment]
@arpitg24  if you're asking in context of Gsoc;  I would like to share this guide i read [` do not submit a pull request just to fix some typo`](https://joplinapp.org/gsoc2021/index/#how-to-create-your-first-pull-request)

**Comment by tessus** [comment]
Either way, this can't be used for GSoC, since it was created after GSoC was announced.

Someonw didn't read the GSoC guide nor the PR guidelines. Definitely not a good start for GSoC. How can someome who's apparently not capable of reading and understanding a few pages, able to work on a SW project?

**Comment by Jonta** [comment]
Still requires the community's attention

**Comment by Jonta** [comment]
Still requires the community's attention

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.1.4 - Database v39

**Comment by Jonta** [comment]
Still requires the community's attention

Joplin 2.3.4 - Database v39
