### ISSUE TITLE
Plugin Controls Not Visible

### ISSUE THREAD

**Issue by lwb52** [laurent22/joplin#4704]
I have LOTS of plugins in the Mac version: in the ”preferences” window (or view), the left panel only shows a few of the control-tabs for plugins that need special configuration, and there is no way to scroll that left panel to show more. The only way to see more is to expand the entire window vertically, but there’s not enough space (even on a 40” monitor) to do that for all plugins. So, the only option left is the de-activate plugins until the ones I need to control show up.

**Comment by JackGruber** [comment]
This is fixed in the next release

**Comment by lwb52** [comment]
Thanks!!
