### ISSUE TITLE
Android client 1.7.5 not updating correctly after sync via WebDAV

### ISSUE THREAD

**Issue by CodicePauperem** [laurent22/joplin#4706]
## Environment

Joplin version: 1.7.5
Platform: Android 10
(Paired with the Win32 1.7.11 portable client)
Encryption turned off and note history turned off on both clients.
Starting with a clean WebDAV directory on a shared remote host. 

## Steps to reproduce

1. Create new notebook or note on desktop portable client, push changes, and sync Android client.
2. New notebook or note will successfully appear in Android client. 
3. Change the notebook (move / sub-tree under another notebook) and/or the content of the note, using the desktop client. Force sync on both clients in expected order.
4. Android client will not display any further changes (text changes or deletions) after the initial successful sync of the content.

On occasion, the Android client *will* accept changes made by the desktop client as would be expected, but it nearly always fails to do so. It appears to be reading from a local cache instead of pulling from the WebDAV directory.
Changes made by the Android client are successfully written to the WebDAV share, and are nearly always successfully read into the associated notebook or note by the Windows desktop client. 

## Logfile

[syncReport-1616092686781.txt](https://github.com/laurent22/joplin/files/6166506/syncReport-1616092686781.txt)

**Comment by CodicePauperem** [comment]
Still an issue. I'd still hope to find a resolution. As is, with the inability to sync correctly bidirectionally through WebDAV, Joplin is not usable for me.

**Comment by roman-r-m** [comment]
If you reinstall android app does it happen consistently?
Also, what's your webdav server?

**Comment by CodicePauperem** [comment]
It does happen on client delete and reinstall, unfortunately, yes.

I'm using shared hosting for WebDAV. The host is running Apache 2.4.29 and
I presume that is how WebDAV is being implemented but I'm not sure.

**Comment by roman-r-m** [comment]
Ok, I'll see if I can reproduce it. I've been using Apache's WebDAV for some tests but was not looking at each note so could've missed that easily.

**Comment by CodicePauperem** [comment]
Thank you!

I am wondering if some of this could be explained by a time zone difference between my location and the host datacenter. I'd presume everything is using UTC, but...?

**Comment by roman-r-m** [comment]
> I am wondering if some of this could be explained by a time zone difference between my location and the host datacenter. I'd presume everything is using UTC, but...?

Can you confirm what are the time zones in your location & the datacenter?

**Comment by CodicePauperem** [comment]
I am in Central Standard Time and last I heard my data center was Eastern
Standard Time, but the company is based on the west coast so could have
moved it back to Pacific Standard. Probably not though. :)

**Comment by roman-r-m** [comment]
@CodicePauperem I have reproduced the issue, now all is left is to find the bug. Thanks for the hint regarding time zones, this seems to be the most probable cause here.

**Comment by roman-r-m** [comment]
I'm seeing that GET `webdav/Joplin/<noteId>.md` returns old note content even when the file on server is updated. And I could not see this GET in my server's access logs. This looks like some caching going on.

Adding HTTP header `Cache-Control: no-store` seems to fix it.
