### ISSUE TITLE
Keep original image rather than compressing ALSO with API

### ISSUE THREAD

**Issue by eromawyn** [laurent22/joplin#4709]
## Environment

Joplin version: joplin 1.6.4 (prod)
Platform: Linux
OS specifics: 

## Steps to reproduce

When I add very big images as ressources with the API (using the outdated python joplin-api which does a POST /resources ), the image gets resized to 1920 px height. Since my original images wer 7-8k px height, the text become unreadable, image is not usable at all !

This is related to bug #1232 : « Keep original image rather than compressing, please » (same bug / unexpected feature on Electron interface).

## Describe what you expected to happen

- I don’t expect the API to resize image for me. I can resize them before uploading them !
- If you really think the API should resize the image, make it optionnal (it should be desactivated by default in my opinion)
- Best option : make it optionnal, and make max size configurable at upload.

**Comment by roman-r-m** [comment]
Already done in https://github.com/laurent22/joplin/pull/4660
Will be fixed in the next version
