### ISSUE TITLE
[Feature Request] Tag autocompletion in desktop and mobile app

### ISSUE THREAD

**Issue by archont00** [laurent22/joplin#471]
### Operating system
- Linux
- Android

### Application
- Desktop
- Mobile

### Autocompletion of tags
**Desktop app**
The desktop app should autocomplete the tags as the user starts typing (tab or enter to complete).

**Mobile app**
The mobile app does not support adding tags when a new note is not yet saved (?!). Once saved, tags can be added from a list of existing tags or a new tag can be created.
It would be easier if the entry field for a new tag used also autocomplete feature - i.e. kind of quick search of existing tags. If nothing is found, a new tag would be created.

**Comment by Abijeet** [comment]
@laurent22 - Planning to implement this using HTML5 [datalist](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) for the desktop applications.

**Comment by Abijeet** [comment]
Just wanted to give an update on this. A datalist isn't going to work very well because we need to have multiple selections.

**Comment by matsest** [comment]
+1 This would be a great enhancement for productivity.

Now that we have the fast full text search engine, or through another query for the tags, is there any way to be able to search for tags to create an auto complete function?

**Comment by alexdevero** [comment]
Could something like https://github.com/TarekRaafat/autoComplete.js work?

**Comment by archont00** [comment]
Autocomplete works for Linux desktop app, but not yet for Android app.

**Comment by archont00** [comment]
.
