### ISSUE TITLE
"Toggle Development Tools" button needs to be clicked twice to open Dev Tools.

### ISSUE THREAD

**Issue by harshitkathuria** [laurent22/joplin#4710]
**Toggle Development Tools** button under the help section of the title bar needs to clicked twice to open Dev Tools after the Dev Tools are closed by the close button (cross mark). 

## Environment

Joplin version: 1.7.11
Platform: Windows
OS specifics: 10

## Steps to reproduce

1. Click the 'Toggle Development Tools' under Help section of title bar. Dev Tools will be opened.
![image](https://user-images.githubusercontent.com/67231570/111804368-06a8f300-88f6-11eb-98cd-4234f6c8fc20.png)

2. Click the cross button on the dev tools panel to close it.
3. Perform Step 1 again

## Describe what you expected to happen
I expected the Dev Tools to be opened. Instead I had to click it twice to open the Dev Tools

**Comment by lkiThakur** [comment]
I was able to reproduce the bug but i think there is a typo in step 1 of your issue;  
did you meant `Click the 'Toggle Development Tools' under ~Home~ *help* section`?

**Comment by roman-r-m** [comment]
"Toggle development tool" is part of Electron on top of which Joplin is built. Not really a bug in Joplin itself.

**Comment by harshitkathuria** [comment]
> "Toggle development tool" is part of Electron on top of which Joplin is built. Not really a bug in Joplin itself.

@roman-r-m  Sorry, but I think it is actually a bug as this part is explicitly handled in the codebase, i.e in `packages\app-desktop\app.ts line 338`.

I have actually solved this bug, should I submit a PR for this issue?

**Comment by roman-r-m** [comment]
Hmm, you're right. I stand corrected.

Have you read the GSoC guide, [Pull request guidelines](https://joplinapp.org/gsoc2021/pull_request_guidelines/) specifically? It says 
> Pull requests must be based on an issue that existed before GSoC was started, or based on an issue created by a moderator.

**Comment by harshitkathuria** [comment]
I read the guidelines, but upon solving this issue, it just slipped out of my mind. 
Sorry :(

**Comment by Priyaraj17** [comment]
Is this issue open? May I work on it?

**Comment by roman-r-m** [comment]
> Is this issue open? May I work on it?

If this is for GSoC then you should take another issue (for reasons outlined 2 comments above). I've just tagged a few more issues with medium - feel free to take a look.

**Comment by Priyaraj17** [comment]
> > Is this issue open? May I work on it?
> 
> If this is for GSoC then you should take another issue (for reasons outlined 2 comments above). I've just tagged a few more issues with medium - feel free to take a look.
Okay Thanks sir

**Comment by tessus** [comment]
Additionally it would make sense to add a check mark to the menu item when it is active. Unless Laurent is against it. 

This is how it looks in the view menu:

<img width="250" alt="image" src="https://user-images.githubusercontent.com/223439/111879896-c5a8f100-897e-11eb-8b9d-8c94ef362afe.png">

@harshitkathuria Even though it might not count towards GSoC, you can still open a PR. Just make sure you add a comment that says you are aware it won't count towards GSoC.

**Comment by harshitkathuria** [comment]
Ok....I will raise a PR for this issue with that underlying comment. But @tessus, my another PR waiting for being merged. And as per the [Pull Request Guidelines](https://joplinapp.org/gsoc2021/pull_request_guidelines/), should I wait for that PR to be merged before raising a PR for this issue?

**Comment by tessus** [comment]
The new PR won't count towards GSoC, so it should be fine. I will also add a note to the PR. If someone mentions that it is against the PR guidelines, just refer them to me.
Right now we don't have a guideline for applicants opening PRs that don't count towards GSoC. (Or at least I don't think we do.) We only want to make sure that we don't get hundreds of half-baked PRs, b/c applicants might think they have a better chance to get in when they open more PRs.

However, if you are working on a PR that is for an issue that was created before GSoC started, you should wait until the other one has been merged. But that's clearly not the case in this situation.

**Comment by harshitkathuria** [comment]
Understood. Thanks

**Comment by harshitkathuria** [comment]
@tessus, When I am done making changes to a typescript file (.ts file), do I need to run `npm run build` and commit the respective _.js_ and _.js.map_ file with the typescript file, i.e If I make changes to **app.ts** which all files should I commit?

**Comment by tessus** [comment]
No, the js files are in the `.gitignore` file. After doing changes to the `.ts` files, you have to test them.
Did you read the build.md? You don't have to create a build for testing the desktop app.

You only commit `.ts` files. Even if this PR is not for GSoC, please tell us in the PR how you tested everything. Most of the time people forget to test or write test cases. There are no test cases for this part of the UI, thus testing must be done manually. (This is actually not only for GSoC. A PR is usually not merged, unless proper testing has been done.)

Testing is as important as coding. Especially in TDD (test driven development). You write the test cases (including all edge cases) before writing the code. It might not be the case for all code parts in this project, but it is good practice nonetheless.

**Comment by harshitkathuria** [comment]
Thanks for helping me out tessus. I read the build.md and tested the files, but got little confused with commiting them. Now it is cleared.

**Comment by laurent22** [comment]
Closing per guideline 1. Also I assume there are duplicates of this issue.
