### ISSUE TITLE
User-friendly functionalities

### ISSUE THREAD

**Issue by Priyaraj17** [laurent22/joplin#4712]
I wish to add a few functionalities which will make the desktop application more user-friendly.
Consider this image:
![image](https://user-images.githubusercontent.com/40101776/111874771-af218a80-89bc-11eb-8f29-8a4f896722b0.png)

## Environment

Joplin version: Desktop
Platform: Linux
OS specifics: Ubuntu

## Steps to reproduce

1. Create a new note

## Describe what you expected to happen
I was thinking of letting the users know where to write the name of their new note. The not is given a default title 'untitled'. I was thinking of adding functionalities such as the name of the note can't remain empty and also highlight the area where the user can give names to their notes.
May I work on this?

**Comment by roman-r-m** [comment]
New features should be discussed on the forum first.

**Comment by Priyaraj17** [comment]
> New features should be discussed on the forum first.

Okay sure. Sir.
