### ISSUE TITLE
Rendering: KaTeX: lines starting with tabs, as autoinserted by Joplin breaks rendering.

### ISSUE THREAD

**Issue by jtagcat** [laurent22/joplin#4713]
## Environment

Joplin 1.7.11 (prod, linux)
Platform: Flatpak
OS specifics: Fedora

## Steps to reproduce

Relevant tabs are shown with ⭾, spaces with ␠.
Input:
```
1. List
␠␠␠␠$$
⭾1+1
⭾$$
```

After writing the first `$$`, the user presses enter.
The next line gets preceded by a tab, braking KaTeX rendring.

### Example
Input (user pressed enter after the 3rd line):
```
1. List
    $$
    0+0 \\
	1+1 \\
    2+2 \\
	$$
```
Output:
![image](https://user-images.githubusercontent.com/38327267/111877529-b6846c00-899b-11eb-8f76-21003b873b94.png)

## Describe what you expected to happen

The tabs should be handled.
![image](https://user-images.githubusercontent.com/38327267/111877605-f9464400-899b-11eb-90ae-e8e327422cc7.png)

**Comment by tessus** [comment]
AFAIK Katex blocks must start at the beginning of the line. But @CalebJohn might know more. I think he made some changes to Katex rendering, but I'm not sure.

**Comment by CalebJohn** [comment]
I haven't worked on the actual katex rendering, just on the editor highlighting. But I believe @tessus is correct, a katex block needs to begin at the start of the line, not tabbed.

This renders as expected
```
1. List
$$
    0+0 \\
	1+1 \\
    2+2 \\
	$$
```

**Comment by jtagcat** [comment]
> AFAIK Katex blocks must start at the beginning of the line.

If that's the case, numbered lists and other items belonging to the same chunk should not break.


> This renders as expected
> ```
> 1. List
> $$
>     0+0 \\
> 	1+1 \\
>     2+2 \\
> 	$$
> ```
Now add `1. no2` to the end. It should be `2.`, not `1.` (starting a new ordered list).

**Comment by CalebJohn** [comment]
Right, that makes sense. In that case you will need to use the inline katex notation. This won't be centred like the block syntax provides, but I think that works in this case.
```
1. List
    $
    0+0 \\
    1+1 \\
    2+2 \\$
1. This will be 2.
```

![image](https://user-images.githubusercontent.com/2179547/111890908-9eb8e200-89b3-11eb-8fe1-f81d72a61000.png)

**Comment by jtagcat** [comment]
Indeed, I missed it in the md docs. I thought of making it more obvious, but don't really know how.

Adding a separate example with the list + inline?

***

@CalebJohn are you on the dev version or similar? Or are our md settings different (mine are all on, except for fountain, deflist and multimd table)?

![image](https://user-images.githubusercontent.com/38327267/111909062-a4660480-8a53-11eb-9545-bf64ff4e8284.png)


![image](https://user-images.githubusercontent.com/38327267/111909052-97e1ac00-8a53-11eb-8031-3620bf09aaff.png)


***
Centered within the block would be nice as well, but that's probably too much dev work.
![image](https://user-images.githubusercontent.com/38327267/111909001-5e10a580-8a53-11eb-9e39-a14ff58e89e5.png)

**Comment by CalebJohn** [comment]
> Indeed, I missed it in the md docs. I thought of making it more obvious, but don't really know how.
> Adding a separate example with the list + inline?

I'm not really sure either, this is somewhat advanced behaviour so it might be confusing to include in the md docs. Maybe a forum post would be better?

> @CalebJohn are you on the dev version or similar? Or are our md settings different (mine are all on, except for fountain, deflist and multimd table)?

v1.7.11. Your behaviour is caused by the enable soft breaks option. You can add an extra newline between the first line and the math to give better spacing, or add 2 spaces at the end of `1. Line  ` to get a break. (Your method works as well).
