### ISSUE TITLE
Alarms not working on Ubuntu 20.4

### ISSUE THREAD

**Issue by tpondant** [laurent22/joplin#4719]
## Environment

Joplin version: 1.7.11 (prod, linux)
Platform: Linux
OS specifics: Ubuntu 20.4
E2E Encryption: enabled

## Steps to reproduce

1. Create a new to-do and give it a title.
2. Set an alarm for a few minutes later (5m for example)
3. Minimize the Joplin application window but don't close it
4. Wait to see if the alarm is going to show up

## Describe what you expected to happen
I was expecting a notification at the top of my screen.

## Logfile

[-1616355182912.log - console warnings and errors ](https://github.com/laurent22/joplin/files/6178183/-1616355182912.log)
[log.txt](https://github.com/laurent22/joplin/files/6178185/log.txt)

**Comment by MrCarroll** [comment]
This is a problem with the Snap package, which isn't an official upstream distribution so doesn't recieve support here. However, I've uploaded a fix for this now, if you run `sudo snap refresh` in the terminal with Joplin closed, the notifications should work again properly after the update.

**Comment by tpondant** [comment]
> This is a problem with the Snap package, which isn't an official upstream distribution so doesn't recieve support here. However, I've uploaded a fix for this now, if you run `sudo snap refresh` in the terminal with Joplin closed, the notifications should work again properly after the update.

I was just curious to try the AppImage from https://joplinapp.org/, so I removed the snap and installed the AppImage. The alarms are still not working. I have libnotify-bin 0.7.9-1ubuntu2.

**Comment by CalebJohn** [comment]
I've just now tested on my computer (Ubuntu 20.04, Joplin v1.7.11, libnotify-bin 0.7.9-1ubuntu2) and it works as expected. I tried with the window both minimized and maximized.

Is it possible that you're accidentally running the snap still? Or maybe the application is closing and not minimizing?

**Comment by tpondant** [comment]
I tried again, and it works.

It is possible that, after removing the snap package, it just needed a
reboot.

Thanks.

Thomas PONDANT

[image:
https://www.youracclaim.com/badges/bed5421c-b53c-418c-94e8-b2145503df32/public_url]
<https://www.youracclaim.com/users/thomas-pondant/badges>

**Comment by tpondant** [comment]
I tried again, and it works.

It is possible that, after removing the snap package, it just needed a
reboot.
