### ISSUE TITLE
Notes disappear when I reload page, only fix is restarting Joplin

### ISSUE THREAD

**Issue by jcoholich** [laurent22/joplin#4721]
Occasionally, Joplin enters a state where it does not save any of the notes that I type. I can type notes, but whenever I reload the page (or navigate away then navigate back), the notes are gone. The only fix I have found is just to restart the app and work until the issue occurs again. I don't know why or when it will occur and only notice it when my notes have disappeared.

## Environment

Joplin version: 1.7.11 (This issue also occurred back when I was using 1.5.14 as well)
Platform: Linux
OS specifics: Ubuntu 20.04

## Steps to reproduce

Unfortunately, I don't know how to reproduce the issue. The issue seemingly happens at random. 

## Logfile

I saved the logfile below while Joplin was in a state of not saving my notes. 
[log.txt](https://github.com/laurent22/joplin/files/6184874/log.txt)

I have turned on the debug console and will update this issue with its contents when the problem occurs next.

**Comment by laurent22** [comment]
When it's not saving notes, is there any error message in the console? https://joplinapp.org/debugging

**Comment by jcoholich** [comment]
I actually turned on the console for the first time after reading https://joplinapp.org/debugging when I created this issue. Currently waiting for the issue to happen again to post the contents of the console.

**Comment by jcoholich** [comment]
Hi, 

The issue happened again. Here is what the log output. 
![Screenshot from 2021-05-12 00-02-43](https://user-images.githubusercontent.com/18234415/117916724-b3c83800-b2b5-11eb-9f1a-1fbf127c10bc.png)

Apologies for not copying the actual text, I clicked somewhere on the logs and the logs disappeared and the side panel went blank (white).

Is there somewhere on my system the log files the relevent log files are stored?

**Comment by JackGruber** [comment]
ok, you are using a snap packet.

Please go into the forum, there are the maintainer of the snap james-carroll, I do not know if he is watching the issues here.

But the problem is, that the filesystem (in the snap) is readonly, or the files. therefore nothing can be written into the database or the lofiles.

**Comment by JackGruber** [comment]
OK, I think this is the snap repro.
https://github.com/MrCarroll/joplin-desktop-snap

**Comment by jcoholich** [comment]
I see, so either submit the issue on the snap repo, or maybe reinstall Joplin via the method listed in the README of this repo and see if the issue still occurs. Thanks.
