### ISSUE TITLE
Desktop: Note list is empty if search field is cleared

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#4736]
This is on the dev branch.

* Click in the search input
* Type something to get a few results
* Now clear the field - the list of results  remains empty. I expect it to show all notes.

Video:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/995612/112617137-7d754d00-8e1c-11eb-924b-a0e21a8dcfe5.gif)

**Comment by heyapoorva** [comment]
I checked this. It seems that the onChange handler for the input currently does not handle the empty query string case. I fixed it at my end. Will post a PR.
