### ISSUE TITLE
Ooes this work with sync.com?

### ISSUE THREAD

**Issue by DanitiKain** [laurent22/joplin#474]
Anyone have any experience with whether this works with sync.com.  Sync.com doesn't work with standardnotes so thought maybe it might work with Joplin.

**Comment by TobiasDev** [comment]
Sync.com doesn't support thirdparty api's. So there is no software that can sync through sync.com since they don't offer an API for developers to use. Until they release one, this will never be able to have syncing  (expect by the user placing files inside the sync.com folder )

**Comment by laurent22** [comment]
sync.com won't be supported directly, but might work once filesystem sync is enabled on mobile
