### ISSUE TITLE
Android: Sync icon is not spinning

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#4743]
Worked on 1.7.5 but doesn't work on the current dev (3fa13828c)

Not sure if iOS is affected too.

**Comment by mablin7** [comment]
I noticed this too. Also the text under the button ("Completed: ...") does not show either. I tried debugging it and it seems the dispatch function is not passed correctly to the Synchronizer, but I can't figure out why. I'll keep trying later today.

**Comment by roman-r-m** [comment]
Thanks for confirming. Is it with physical device or emulator?

**Comment by mablin7** [comment]
I saw it on both an Android 9 emulator and my phone running Android 10.

**Comment by roman-r-m** [comment]
Ok, thanks, I thought maybe it has something to do with me running it in emulator.

**Comment by Amarpsp10** [comment]
not the only problem in icon spinning, it is also not showing sync report!!

**Comment by laurent22** [comment]
Indeed looks like build 1.8 is broken on Android.
