### ISSUE TITLE
Feature Request: Manual Sorting of Notebooks

### ISSUE THREAD

**Issue by BeatLink** [laurent22/joplin#4756]
It would be great if Jolpin could manually sort notebooks in the list instead of alphabetically. There could even be an option in the settings to toggle the sort mode. Implementation wise, it could be possible to have each notebook contain a sort order number that specifies its position in the list.

**Comment by JackGruber** [comment]
Feature requests should be posted on the forum and not as issue.

**Comment by tessus** [comment]
Yes, the feature request button when opening an issue opens the forum link, but people always ignore the template.

This is not a reproducible bug.
