### ISSUE TITLE
Unable to sync with webdav - new instance - all instances actually

### ISSUE THREAD

**Issue by ipentest** [laurent22/joplin#4758]
Dear Team,

Hope you're well...

I got a new laptop and the first thing I did was to install Joplin. I have a free webdav account with drivehq with all my documents in there. I provided the details and tried to synchronize.

The error I got is: (pasting from the console)

`
06:47:17: Error: DELETE d0ecfeb04053442582cc1f4347a611ba.md: Unknown error 2 (422): 
    at newError (C:\Users\Kiran\AppDa…ib\WebDavApi.js:406)
    at WebDavApi.exec (C:\Users\Kiran\AppDa…ib\WebDavApi.js:436)
    at async FileApiDriverWebDav.delete (C:\Users\Kiran\AppDa…river-webdav.js:206)
    at async tryAndRepeat (C:\Users\Kiran\AppDa…\lib\file-api.js:40)
`

## Environment

Joplin version: 
Joplin 1.7.11 (prod, win32)

Client ID: 0ab8ed573faa4d46b365fc7014598b78
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f560563d8 (master)

Platform: Win 10 Pro on Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz   2.71 GHz
OS specifics: Windows 10 Pro

## Steps to reproduce

1. Install Joplin for Windows
2. Go to Tools > Options > Synchronization > Webdav > Add URL and credentials
3. Click on "Check Synchronization Configuration"
4. It says "Success! Synchronization configuration appears to be correct"
5. Apply > Back
6. Click on Synchronize button
7. Leads to the above error
8. I manually created the above mentioned file (d0ecfeb04053442582cc1f4347a611ba.md) and tried to sync. It then shows a new file in the above error

## Describe what you expected to happen

I have other installs of Joplin on a mac, iphone and android, they all sync without any issue with the same webdav url

## Logfile

06:47:17: Error: DELETE d0ecfeb04053442582cc1f4347a611ba.md: Unknown error 2 (422): 
    at newError (C:\Users\Kiran\AppDa…ib\WebDavApi.js:406)
    at WebDavApi.exec (C:\Users\Kiran\AppDa…ib\WebDavApi.js:436)
    at async FileApiDriverWebDav.delete (C:\Users\Kiran\AppDa…river-webdav.js:206)
    at async tryAndRepeat (C:\Users\Kiran\AppDa…\lib\file-api.js:40)

Thank you team for the great work. Please do feel free to let me know if you need any other information

*EDIT* Dear Team: This issue is now with all the instances of Joplin that I have.. I am getting the exact same error and none of them are connecting to webdav... Please help

**Comment by ipentest** [comment]
Dear Team,

An update on the trials I did.

1. Checked with DriveHQ and they suggested that it could be because of my free subscription limits being reached. I upgraded to paid but the issue still exists
2. I created a 4shared account and tried syncing there but got an error as attached
3. The .lock and other files were created by Joplin so I know there were no write issues with 4shared

![joplin-4shared-error](https://user-images.githubusercontent.com/10952397/113140454-73759480-91f6-11eb-810e-3edd7cedb475.png)

Thanks and have a great day

**Comment by JackGruber** [comment]
Please attach a debug log. Issues without a debug log are likely to stall.
  For information on how to collect a log file: https://joplinapp.org/debugging/

**Comment by ipentest** [comment]
Thanks for the response @JackGruber 
Attached both the console output and the log.txt files here... Please do let me know if you need any other information

Thanks again and Happy Easter!

[console-joplin.txt](https://github.com/laurent22/joplin/files/6243329/console-joplin.txt)
[log.txt](https://github.com/laurent22/joplin/files/6243334/log.txt)

**Comment by JackGruber** [comment]
When I see it correct, the file `locks/sync_desktop_2a005362a11e4ea395ddb3cd263c9e8d.json` dosn't exist but drivehq response with a `422` for Item doesn't exist. The response code should be 404, but I'm not sure.

**Comment by ipentest** [comment]
Oh, thanks a lot for the speedy response @JackGruber. Really appreciate your help... I did check with DriveHQ if they had made any changes but they said there were no changes made. Attaching the screen shot from their support response here.

![drivehq-support-response](https://user-images.githubusercontent.com/10952397/113295342-19440480-92c6-11eb-9d81-2f63381691c8.png)

Thanks again

**Comment by ipentest** [comment]
Hi @JackGruber 

Can you please let me in on whether this issue is solvable please? I've been totally handicapped since more than a week as I haven't been able to access my notes. (I have different projects/ notebooks for home and work which need to sync and update...) Please please help me out and if it's not possible to resolve, kindly let me know too

Thank you so much and looking forward to your response

**Comment by ipentest** [comment]
@JackGruber I also tried to test with other WebDAVs and have the same issue, so it may not be the 422 response.

**Comment by JackGruber** [comment]
I'm only a Joplin user, no developer!

> I've been totally handicapped since more than a week as I haven't been able to access my notes.

Do you have only one device syncing and this device have no data or do you have you old PC also running with Joplin? 

> I tried to test with two other WebDAVs 

How did you test this? With a new Joplin installation (empty one) and a empty Synctarget or did you copy your files? 
Was there also a 422 error ? 


Maybe an option is to download all data from drivehq and set up a local file sync to get the data into joplin and make then a JEX export. 


You can try the commands listed below one after the other. I mean no 422 http status code should be returned. 

**Try to get info for non existing file**
`curl -X PROPFIND https://dhqidhcbxlhkg0xfmw0hyeq.webdav.drivehq.com/joplin/locks/test.md --user user:password -sw %{http_code}`

**Try to delete non existing file**
`curl -X DELETE https://dhqidhcbxlhkg0xfmw0hyeq.webdav.drivehq.com/joplin/locks/test.md --user user:password -sw %{http_code}`

**Upload file**
`curl -T C:\test.md https://dhqidhcbxlhkg0xfmw0hyeq.webdav.drivehq.com/joplin/locks/test.md --user user:password -sw %{http_code}`

**Get info from file**
`curl -X PROPFIND https://dhqidhcbxlhkg0xfmw0hyeq.webdav.drivehq.com/joplin/locks/test.md --user user:password -sw %{http_code}`

**Delete file**
`curl -X DELETE https://dhqidhcbxlhkg0xfmw0hyeq.webdav.drivehq.com/joplin/locks/test.md --user user:password -sw %{http_code}`

**Comment by ipentest** [comment]
Thank you so much for the quick response once again @JackGruber .. Will test based on your inputs and let you know. Thanks again

**Comment by roman-r-m** [comment]
Had a look at your logs and it seems to me this is a problem with your server.

This is what I see in logs. Here Joplin creates a file on the server:
```
2021-03-31 07:30:29: "Req 07:30:29: PUT https://webdav.4shared.com/locks/sync_desktop_2a005362a11e4ea395ddb3cd263c9e8d.json {"headers":{"Authorization":"********","Content-Type":"text/plain","If-None-Match":"JoplinIgnore-43794","User-Agent":"Joplin/1.0","Content-Length":"84"},"body":"{\"type\":\"sync\",\"clientType\":\"desktop\",\"clientId\":\"2a005362a11e4ea395ddb3cd263c9e8d\"}","timeout":120000,"maxRetry":0}"
```
It does not seem to log the reponse or it's empty but since it does not log an error either I assume the server acked it:
```
2021-03-31 07:30:29: "Res 07:30:29: "
```

Now Joplin tries to read back the same file, or rather the contents of the directory where it has just put the file:
```
2021-03-31 07:30:29: "Req 07:30:29: PROPFIND https://webdav.4shared.com/locks/ {"headers":{"Depth":1,"Authorization":"********","Content-Type":"text/xml","If-None-Match":"JoplinIgnore-27240","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
```
And the response does not contain the file:
```
2021-03-31 07:30:29: "Res 07:30:29: <?xml version="1.0" encoding="utf-8" ?>
<D:multistatus xmlns:D="DAV:">
<D:response>
<D:href>/locks/</D:href>
<D:propstat>
<D:prop>
<D:resourcetype>
<D:collection/>
</D:resourcetype>
<D:getlastmodified>Wed, 31 Mar 2021 11:30:29 GMT</D:getlastmodified>
</D:prop>
<D:status>HTTP/1.1 200</D:status>
</D:propstat>
</D:response>
</D:multistatus>
"
```

For comparison this is what a good reponse looks like (notice the 2nd `href` element and everything else that follows it):
```xml
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:ns1="http://owncloud.org/ns" xmlns:ns0="DAV:">
	<D:response xmlns:lp1="DAV:" xmlns:lp2="http://apache.org/dav/props/">
		<D:href>/webdav/Joplin/locks/</D:href>
			<D:propstat>
				<D:prop>
					<lp1:getlastmodified>Fri, 02 Apr 2021 20:32:58 GMT</lp1:getlastmodified>
					<lp1:resourcetype><D:collection/></lp1:resourcetype>
				</D:prop>
				<D:status>HTTP/1.1 200 OK</D:status>
			</D:propstat>
	</D:response>
	<D:response xmlns:lp1="DAV:" xmlns:lp2="http://apache.org/dav/props/">
		<D:href>/webdav/Joplin/locks/sync_desktop_093657b4d9ea43f3b3ff767ca9b85336.json</D:href>
		<D:propstat>
			<D:prop>
				<lp1:getlastmodified>Fri, 02 Apr 2021 20:32:58 GMT</lp1:getlastmodified>
				<lp1:resourcetype/>
			</D:prop>
			<D:status>HTTP/1.1 200 OK</D:status>
		</D:propstat>
	</D:response>
</D:multistatus>
```

I suggest you go back to your provider with this and see what they can say.

**Comment by ipentest** [comment]
Hi @roman-r-m 

Thank you so much for the help and sorry for the delay in responding. My concern is that as I was able to work on exactly the same webdav servers till around last 2 weeks ago & nothing changed on the servers (all of them at the same time) and also the fact that all of the webdavs I tried such as DriveHQ, 4shared and mydrive will give the same error makes me feel like it's an issue on Joplin's side... I tried installing various versions of Joplin and also deleting the files on both the server (.lock, .resource, .sync etc which were not recreated by Joplin) and the client (contents of profile directory).. Really dont know what else to do

Thanks for all your help but I think its time to move on. Will look into some other tool which is as promising as Joplin minus all the issues... It was a fantastic ride while it lasted... Thanks again to @roman-r-m & @JackGruber for all your help in this matter

**Comment by roman-r-m** [comment]
> Thank you so much for the help and sorry for the delay in responding. My concern is that as I was able to work on exactly the same webdav servers till around last 2 weeks ago & nothing changed on the servers (all of them at the same time) and also the fact that all of the webdavs I tried such as DriveHQ, 4shared and mydrive will give the same error makes me feel like it's an issue on Joplin's side...

That's possible. I almost wish it happened to me so that I can debug but alas (I am using Dropbox though)

> Will look into some other tool which is as promising as Joplin minus all the issues... It was a fantastic ride while it lasted...

Good luck. There are plenty of tools out there to try.
