### ISSUE TITLE
Command palette: Focus Issues

### ISSUE THREAD

**Issue by loozai** [laurent22/joplin#4759]
The note looses focus after inserting a checkbox/listbox/codeblock etc. using the command palette (ctrl-shift-p)

## Environment

Joplin version: 1.7.11
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. create a new note and enter some freetext
2. press ctrl-shift-p to activate the command palette
3. start typing "check" and then press enter
4. this creates a checkbox with highlighted text "List Item"
5. the note looses focus so that I can't immediately continue writing without clicking into the note to regain focus.

Affected items (as far as my short tests went): 
Horizontal rule, Checkbox, Bullet List, Numbered List, Heading

This happens in the marktown editor in both views (ctrl-L)
In the WYSIWIG Editor, the checkbox isn't even created.

## What I expect: 
press ctrl-shift-p and insert a hyperlink -> here, the cursor is placed between the square brackets and you can immediately continue typing.

**Comment by coderrsid** [comment]
I can reproduce this problem. But i guess there are more underlying problems too. Some of which i noticed.
1. After adding checkbox, it doesn't gives a new line space, instead adds checkbox before the current text/element in current line.
2. Checkbox, Horizontal rule, Checkbox, Bullet List, Numbered List, Heading cannot be added WYSIWIG editor by Cmd+Shift+P, weird and even if we add in markdown editor, the current behaviour does not match expected one.

**Comment by Aksh-Konda** [comment]
Hi @coderrsid, 
I couldn't understand the first point. For me, if the checkbox command is executed while the cursor is at the end of the line or in between a line, it is adding a new line along with a new checkbox. but if the cursor is at the start of a line, the new line is not appended. try to pull the latest code and run it.

**Comment by Aksh-Konda** [comment]
Hi @coderrsid,
I tried reproducing your mentioned problems and it is working as expected for me.

1. After adding a checkbox, the new line is added if there is text before the cursor in the current line i.e if the cursor is in between the text or at the end of the text it is adding a new line, checkbox, and text after the cursor (if there is any). which is what I think is the desired action.

can you please try pulling the latest code from the Joplin repo and executing it?

**Comment by Aksh-Konda** [comment]
Hi @loozai ,
Yes. Actually I was specifically talking about the checkbox inserted through command palette. 

The focus issue is definitely there and I fixed it. Waiting for @coderrsid to reply. So that I can make a PR if there are no other issues.

**Comment by coderrsid** [comment]
>     1. After adding a checkbox, the new line is added if there is text before the cursor in the current line i.e if the cursor is in between the text or at the end of the text it is adding a new line, checkbox, and text after the cursor (if there is any). which is what I think is the desired action. Can you please try pulling the latest code from the Joplin repo and executing it?

So @Aksh-Konda, the latest dev code responds this way..
![Screen-Recording-2021-03-31-at-1](https://user-images.githubusercontent.com/35633575/113182399-7ad98400-9270-11eb-8bce-0c02a899c125.gif)

So as you can see in TinyMCE, the checkbox is not even added and in MD editor, the checkbox is added where the cursor position was last set in TinyMCE without a new line space after it.
Can you please share if any other behavior is shown in your build?

**Comment by Aksh-Konda** [comment]
@coderrsid, I'm sorry I didn't check it in TinyMCE.

But, what I said is definitely applicable for the MD editor.

> 1. After adding a checkbox, the new line is added if there is text before the cursor in the current line i.e if the cursor is in between the text or at the end of the text it is adding a new line, checkbox, and text after the cursor (if there is any). which is what I think is the desired action.


> the checkbox is added where the cursor position was last set in TinyMCE without a new line space after it.

Yeah. Because there is no text before the position of the cursor and so the checkbox need not be on a new line.
