### ISSUE TITLE
flooded of annoying notifications

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#476]
## Operating system

- Linux

### Application

- Desktop

### Description

when editing a note (with a reminder), as the synchronisation is a little bit fast, the desktop is flooded of  notifications with the reminder text. While I enter more and more text, my screen become unreadable with blacks blocks all arround the screen :)

**Comment by laurent22** [comment]
When is the reminder set? Is it in the past or something like this?

**Comment by foxmask** [comment]
no it's for the 1st on june

**Comment by laurent22** [comment]
Strange, I can't replicate this and it shouldn't display any alarm, not even one, if the date is in June. I'll do more tests to see if I can reproduce it.

**Comment by laurent22** [comment]
On what Linux distro by the way?

**Comment by foxmask** [comment]
Debian 9.1

**Comment by laurent22** [comment]
Do you use a specific notification system (eg. growl)?

**Comment by foxmask** [comment]
arg :/ I reproduce it again.
I tested the sub directory features and the notifications raise again and again :(
I'm going to check what notification system could be the cause

**Comment by foxmask** [comment]
the daemon was xfce4-notifyd. I removed it for notify-osd / grawl.
seems to be better for the moment
make some additionals tests

**Comment by laurent22** [comment]
See also https://discourse.joplin.cozic.net/t/mystical-unwanted-notification-from-joplin/802

**Comment by danieldev** [comment]
I can reproduce this problem on MacOS. I get a notification for basically every character I modify (seems to be connected with notes that have an alarm). I use WebDAV to sync with my owncloud.

**Comment by gschleder** [comment]
I'm also reproducing the problem. Strangely, the notifications appear only for reminders between certain dates. As of now (July 4), the flood of notifications appears for reminders between July 29 and Aug 22.
Using Joplin 1.0.159 on Ubuntu with xfce and dropbox sync.
