### ISSUE TITLE
ordered markdown list wrong numbering 

### ISSUE THREAD

**Issue by lkiThakur** [laurent22/joplin#4760]
![image](https://user-images.githubusercontent.com/63918341/112830408-1d96d480-90b0-11eb-8b37-594f0ec538b4.png)
## Steps to reproduce
1. type `1. ` in a line and write something
2. press enter twice (to move to next line and end list one respectively)
3. add few newlines by pressing enter
3. write `1. ` again and type something
4. preview the note to see the anomoly

ps: I noticed the same problem  with github markdown too.

## Environment

Joplin version:1.8.0 ( dev branch)
Platform: linux 
OS specifics: mint

## Describe what you expected to happen
numbering in markdown preview pane should be same as that typed in editor

**Comment by roman-r-m** [comment]
I think "another list" on your screenshot is correct - it's an item on the 1st list. "one more list" however does not seem right.
Looks like there's no way to have 2 different lists unless there's some other text in between e.g.
```
1. a
2. b

<no matter how many newlines are here, it's all rendered as 1 list with 4 items>

1. c
2. d

```

**Comment by lkiThakur** [comment]
> unless there's some other text in between

lorem ipsum in my screenshot is a text in between ; still the lists are not considered seperate by the rendered markdown.
it's because of the genuine reason that program is considering "lorem ipsum" as part of 1st item of list 1 ( a workaround exists )

**Comment by mightomi** [comment]
@lkiThakur I guess this is expected behavior that "lorem ipsum" is being considered as a part of  "1. a list". You can add a new line after "1. a list" to avoid that. 

@roman-r-m I found that we can add an HTML comment to separate two different lists.
something like 
```
1. a
2. b
1. c
2. d
```
is previewed as 
1. a
2. b
1. c
2. d

whereas,  
```
1. a
2. b
<!--  -->
1. c
2. d
```

will be previewed as 
1. a
2. b 

1. c
2. d

**Comment by roman-r-m** [comment]
Sure, adding anything except newline solves it. Maybe my expectation was off but I thought with enough newlines these should have been parsed as 2 separate lists.
I'll try find a spec of markdown and see.

**Comment by lkiThakur** [comment]
> I'll try find a spec of markdown and see.

We should wait for this @stalebot
