### ISSUE TITLE
Need to update instructions to install the plugin in plugins.md

### ISSUE THREAD

**Issue by i-am-sank** [laurent22/joplin#4761]
**Configuration > plugin** section is not visible in joplin while running in development mode.

## Environment

Joplin version: 1.6.4(prod)
Platform: Desktop
OS specifics: Ubuntu 18(LTS)

## Steps to reproduce

1. [install the plugin](https://github.com/laurent22/joplin/blob/dev/readme/api/get_started/plugins.md#install-the-plugin)

## Describe what you expected to happen

The process of installing the plugin can be done using this instruction:
Tools > Options > Plugins > Show Advanced Settings

instead of Configuration > plugin.

**Comment by i-am-sank** [comment]
I would like to work on this.

**Comment by tessus** [comment]
Closing. PR guideline 1:

Pull requests must be based on an issue that existed before GSoC was started, or based on an issue created by a moderator.
