### ISSUE TITLE
Can't copy a single image to online editors like Google Docs

### ISSUE THREAD

**Issue by nishantwrp** [laurent22/joplin#4764]
## Environment

Joplin version: 1.8.1
Platform: Linux
OS specifics: Deepin

## Steps to reproduce

1. Insert a local image in Jolpin (In rich text view)
2. Select the image
3. Copy the image (Ctrl C)
4. Try to paste the image in any online editor like Google Docs

You will observe that image doesn't get pasted to Google Docs.

## Describe what you expected to happen

Expected the image to get pasted without any issues.

### References

https://github.com/laurent22/joplin/issues/4602#issuecomment-803774665

### Probable Solution

When a single image is selected and copied we should copy the image data instead of being dependent on the local file, so that would enable the image to be pasted anywhere.

**Comment by nishantwrp** [comment]
This is still an issue.

**Comment by nishantwrp** [comment]
This is still an issue.

**Comment by nishantwrp** [comment]
This is still an issue.

**Comment by jrwrigh** [comment]
This is still an issue.

**Comment by jrwrigh** [comment]
I was about to start compiling all the issues/forum threads regarding this problem in a new forum post, but I think this issue serves to keep track of it. 

Forum Posts Requesting feature:
- https://discourse.joplinapp.org/t/copy-image-from-note/7797
- https://discourse.joplinapp.org/t/copy-images-from-joplin/19353 
    - Said it was solved with Rich Text editor, but this is not the case for me. Still copies it as `![*.png](file:///path/to/file)`
- https://discourse.joplinapp.org/t/issues-while-copying-images/15991
   - Simply links back to the original GH issue that this stems from (#4602)
   
   
For my personal machine, I'm running on Manjaro and using the AUR copy of Joplin. This is a fairly important part of my general workflow.

**Comment by nishantwrp** [comment]
Still an issue

**Comment by jrwrigh** [comment]
Is there a way for me to put a bounty on this? I'm happy with almost everything about Joplin, but this is the one thing that (I think) most people would just assume works.

**Comment by nishantwrp** [comment]
Nice idea, I saw that there are sites like https://issuehunt.io/ that are used by a lot of projects & these allow people to put bounty on the issues that they want to be fixed.

**Comment by nishantwrp** [comment]
still an issue

**Comment by jrwrigh** [comment]
still an issue.

**Comment by jrwrigh** [comment]
still an issue

**Comment by nishantwrp** [comment]
still an issue

**Comment by nishantwrp** [comment]
still an issue

**Comment by jrwrigh** [comment]
still an issue

**Comment by nishantwrp** [comment]
Still an issue

**Comment by jrwrigh** [comment]
still an issue

**Comment by jrwrigh** [comment]
Actually, I think this is resolved now. Right clicking an image in the preview-window and using "Copy Image" from there allows me to copy the image to Google docs, slack, and anywhere else I try.

**Comment by nishantwrp** [comment]
Closing this issue (https://github.com/laurent22/joplin/issues/4764#issuecomment-1236374625).
