### ISSUE TITLE
Plugin dialog should not close when pressing ENTER on a text area

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#4766]
https://discourse.joplinapp.org/t/dialog-related-issue/16231/11?u=laurent

**Comment by Ahmad45123** [comment]
What would be a better fix ?
Simply prevent Enter from propagating when focused in any text area in any dialog view.
Or
Add to API the option to disable Enter key entirely in Dialogs. (wouldn't submit but still make new lines)
Or maybe a mix of both? Not entirely sure.,\

**Comment by laurent22** [comment]
Yes, this one:

> Simply prevent Enter from propagating when focused in any text area in any dialog view.
