### ISSUE TITLE
Jolpin doesn't create it's own copy of images while pasting

### ISSUE THREAD

**Issue by nishantwrp** [laurent22/joplin#4767]
(Note from moderator: Related to https://github.com/laurent22/joplin/issues/4602)

## Environment

Joplin version: 1.8.1
Platform: Linux
OS specifics: Deepin

## Steps to reproduce

1. Open an offline doc editor like LibreOffice.
2. Write some text. Insert an image below to it.
3. Select all and Copy (Ctrl A + Ctrl C)
4. Paste it in Joplin. (You can notice the image is dependent on the third-party file made by the local editor.)
5. Close LibreOffice without saving the document.
6. Restart Joplin.
7. Observe that image is not showing (it's broken).

## Describe what you expected to happen

The image should be present. It's a normal use case for example I start making a document in LibreOffice and now want to shift it to Joplin.

## Probable Solution

Maybe while pasting we could check if it contains any images, if it does we create a local Joplin resource for that image.

**Comment by laurent22** [comment]
Thanks for the detailed description, I wasn't aware of this bug. Since your first pull request has been merged now, feel free to give that new issue a try if you have some ideas.

**Comment by laurent22** [comment]
No, your first pull request has not been merged yet and is not complete since you've ignored the PR guidelines.

**Comment by TheSYNcoder** [comment]
Is anyone taking this or can i try solving this?

**Comment by TheSYNcoder** [comment]
@nishantwrp Okay sure.
