### ISSUE TITLE
highlight existing text in global search field

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#4769]
When using the shortcut (default: `CtrlCmd+Shift+F`) or the menu item `Edit > Search in all notes`, the focus is set to the global search field.

However, if there's already text in the field, the cursor is placed at the end and typing appends to the existing search term.

This change should highlight the current text, so that it will be replaced by the new search term.

/ref https://discourse.joplinapp.org/t/search-across-notes-selects-existing-search-terms/16252

# Before

![gsf1](https://user-images.githubusercontent.com/223439/112918930-08cc3800-90d4-11eb-913c-ede508992bc8.gif)

# After

![gsf2](https://user-images.githubusercontent.com/223439/112918945-0f5aaf80-90d4-11eb-8d09-2ed4edd7e598.gif)

**Comment by mightomi** [comment]
I like to solve this issue
