### ISSUE TITLE
How to retrieve files deleted by synchronization mechanism error

### ISSUE THREAD

**Issue by IMVector** [laurent22/joplin#4770]
## Environment

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1. 
2. 
3. 

## Describe what you expected to happen

How to retrieve files deleted by synchronization mechanism error

I used webdev to sync files and an error occurred, which caused all my notes to be deleted, I now want to recover these files is there any way to do so please?

**Comment by CalebJohn** [comment]
Do you know what the error was?
Also could you please fill out all the info you ignored?

**Comment by IMVector** [comment]
> Do you know what the error was?
> Also could you please fill out all the info you ignored?

I'm using joplin on ios to sync files on webdev, but I found that the records on my desktop were deleted, leaving only some of the files.
