### ISSUE TITLE
[Feature Request] make [TOC] available in markdown

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#478]
/ref https://discourse.joplin.cozic.net/t/make-toc-available-in-markdown

**Summary:**

I often have long notes and a Table of Contents would help a lot with navigating these notes.

The common markdown keyword for a table of contents section (collapsible or not) is `[TOC]`. The reason for a keyword is that people might want to have it at the top and the bottom of a note (or somewhere within the note as well).

---

The Markdown approach would indeed be simpler than creating custom UI for all three apps. Since we use markdown-it, this plugin maybe could be used:

https://github.com/Oktavilla/markdown-it-table-of-contents

**Comment by armaccloud** [comment]
Seems to be related to #263

**Comment by tessus** [comment]
@armaccloud yes, they are somewhat related, but if you read the [comments](https://discourse.joplin.cozic.net/t/make-toc-available-in-markdown/20/3) in discourse, you'll see the differences.

**Comment by laurent22** [comment]
Yes, if you can get it working in desktop and mobile. It will probably work automatically in both but we need to be sure.

**Comment by tessus** [comment]
I currently cannot test any code changes on mobile, because of issues with the build environment.
But I will try again when I have a bit more time. Until then maybe somebody else could verify my changes. Anyway, let's see if I can get it working in the Electron client first. ;-)

I was barely able to get the Electron client running. Only a workaround I found, which is most likely an unsupported hack, made it possible to actually run the dev code locally. (see https://discourse.joplin.cozic.net/t/issues-with-running-the-electron-client/421 for all the details)

**Comment by laurent22** [comment]
How did you get it working eventually? Is it something we can add to build.md?

**Comment by tessus** [comment]
I was **not** able to fix the `yarn dist error` nor the `npm run pack error`.

But I was able to get `./run.sh` working by creating a symbolic link. The error was stating that a module couldn't be found at a certain path. For some reason `npm install` or whatever named the directory on my machine `ElectronClient/app/node_modules/sqlite3/lib/binding/node-v57-darwin-x64` and not `ElectronClient/app/node_modules/sqlite3/lib/binding/electron-v1.8-darwin-x64`. Therefore I created a sym link.

I didn't mention any of this on discourse, because there must be a reason for the different name of the directory. Why is it on my system this way? Am I the only one who has this problem? What is responsible for giving the directory that name? I hoped I could get answers to these questions.

Also, it would be nice to fix the other 2 errors.

**Comment by tessus** [comment]
I tried to [add the plugins](https://github.com/tessus/joplin/tree/support-toc-and-anchor), but for some reason the TOC is not rendered.
I even tried a different toc plugin to no avail. I also tried to use different options for the anchor and toc plugins. This didn't help either. I really thought it shouldn't be too complicated to just add a plugin to the rendering engine, but apparently I was wrong (or I missed something).

Anyhow, I don't even know how to check what exactly is rendered in the Electron client. I know it is doing something. The `[[toc]]` keyword is recognized.
How can I see what the output of `MdToHtml.js` is? I would have assumed that one can use `./run.sh` to startup the dev environment and use the Developer Tools for exactly that. I couldn't find out how though.

**Comment by laurent22** [comment]
@tessus, Joplin markdown-it to parse the Markdown text and create tokens from it, but then there's some custom code to render these tokens into HTML. So probably there's something that need to be added to renderTokens_() to display the TOC.

**Comment by tessus** [comment]
Alright, I still can't figure out what I have to change in `renderTokens_()`. I've been using `console.log(t);` to investigate the tokens, but  it makes no sense to me.

I guess I will have to wait until someone, who actually knows this stuff, can have a look. Maybe this would be a nice issue for hacktoberfest.

**Comment by ivywong** [comment]
Hi, I was looking at this issue and I was wondering if I understood this correctly: if we want to add a TOC to a note, one way to to do this is to use the plugin mentioned above to so `markdown-it` will be able to parse TOC tokens for `[[toc]]`, which we can then use in `renderTokens_()` to figure out where to insert a TOC in the rendered HTML?

Since it appears Joplin renders HTML using some custom code, wouldn't we then have to manually extract all the headings from the document and use that information to generate the TOC? 

I assume the most extensible way to do this is to have a util to extract the document outline from the markdown document separately from the rendering process, and return the headings in some format that would then be reusable for #263 and other similar issues, but I'm not sure what the best design approach for this would be.

**Comment by tessus** [comment]
> Hi, I was looking at this issue and I was wondering if I understood this correctly: if we want to add a TOC to a note, one way to to do this is to use the plugin mentioned above to so markdown-it will be able to parse TOC tokens for [[toc]], which we can then use in renderTokens_() to figure out where to insert a TOC in the rendered HTML?

Yep, as far as I have understood this process, yes. But @laurent22 can answer this with clarity.

> Since it appears Joplin renders HTML using some custom code, wouldn't we then have to manually extract all the headings from the document and use that information to generate the TOC?

According to the plugin, the plugin reads the markdown to build the TOC. The markdown-it engine just uses tokens to create the html output. But that's where I'm stuck. I've never really worked with any of these technologies before.

> I assume the most extensible way to do this is to have a util to extract the document outline from the markdown document separately from the rendering process, and return the headings in some format 

Right, this is exactly what this plugin is supposed to do.

@laurent22 do you have any additional comments? Am I missing something here?

**Comment by ivywong** [comment]
@tessus 
> Right, this is exactly what this plugin is supposed to do.

I'm not familiar with these technologies either, but from what I've looked at, it appears that the plugin is supposed to provide additional functionality to markdown-it's `render` function. However, Joplin doesn't use that and has its own rendering process in `renderTokens_()`, which is why we aren't able to use the plugin to generate HTML for us.

**Comment by tessus** [comment]
>  However, Joplin doesn't use that and has its own rendering process in renderTokens_(), which is why we aren't able to use the plugin to generate HTML for us.

Right, but unless I'm mistaken the `tokens` which are used in markdown-it's `render` function are also used in `renderTokens_()`.

**Comment by subi54** [comment]
[[TOC]] might not have worked but in-page links worked till the last release. They still do on mobile. You could easily make a TOC with `<a id>` & `<a href>`.

**Comment by tessus** [comment]
@subi54 no, you don't want to create a toc manually, if you have a very long note with a lot of headings. that's why there's a toc plugin available. `[[toc]]` will create everything automatically for you. that's why there's this feature request.

> in-page links worked till the last release

this is a separate issue. please see #933. unless this is fixed toc won't work either (only partly). well, let's put it that way: if the toc is finally rendered correctly, a click on the link wont work unless internal anchors work again.

**Comment by tessus** [comment]
@subi54 I think you are missing the point. Joplin is a note taking app. I don't wan't to write lines over lines of html code for creating a toc that should be part of the functionality of a note talking app in the first place. (I don't care how many editors support this.)
Some of my notes are 1,000 lines long. Scrolling to the correct entry is a pain in the ass and a waste of my time. Creating a toc for these notes is tedious. I can't use search either, b/c it will search all notes and not only within one note (there's a feature request for this as well).

And yes, I have created manual tocs for some of my long notes, and it took me a very long time. that's why I still use 1.0.111 and not the latest version. However, I want to use an app to take notes and not spend time to organize a note. That's the job of the app.

**Comment by subi54** [comment]
Apologies @tessus if it seemed like I'm missing the point. I can assure you I'm not.

A few my notes have have over 8000 bullet points, seperated into sections. Each bullet is multi-line with either new lines or paragraphs or both. You can probably guess the trouble I have to go to, to get the formatting right everytime or navigating between them.

Both toc & search in-page is something I'm looking forward to in Joplin.

If I might suggest an alternative for the meantime, open note in Sublime Text, there is a toc plugin, helps me out a lot. Plus search-replace with regex.

**Comment by tessus** [comment]
@subi54 This is great advice:

> open note in Sublime Text, there is a toc plugin, helps me out a lot.

I'm using Sublime Text as my external editor and use it for regex replace and the cool cmd+d mark and replace feature. I never heard of the toc plugin, but I will search for it. Thank you.

**Comment by subi54** [comment]
@tessus, search for Outline or SublimeOutline. Found it here on [GitHub](https://github.com/warmdev/SublimeOutline) actually.

**Comment by laurent22** [comment]
One thing that bothers me with this `[[TOC]]` markup is that it's a non-standard extension - it's understood by the plugin above but if you drop the Markdown in a text editor or convert it with a standard md2html converter it won't do anything.

Basically, it seems we're moving away from the concept of durable data, which works and makes sense even if Joplin stops working, or even if you want to move that data to a different note taking app.

With that in mind, I'm thinking an alternative would to have this table of content auto-generated **as markdown** by a tool. It would work like Word where you have the full TOC and you can manually refresh it whenever you want (maybe we could have an option to do it automatically for Joplin).

The Markdown will be like this:

```
<!-- TOC -->
* [Heading1](#heading1)
    * [Sub-heading 1](#sub-heading1)
    * [Sub-heading 2](#sub-heading1)
* [Heading 2](#heading2)
<!-- /TOC -->
```

So it will be wrapped in something like `<!-- TOC -->` so that it's possible to detect the block of text and auto-update it. The rest will be pure Markdown so if it's exported anywhere it will still work.

Anyway, it's just a proposal at this point, let me know if you can think of some advantages/disadvantages to it, or if you have any suggestions on how to improve it.

**Comment by tessus** [comment]
> One thing that bothers me with this [[TOC]] markup is that it's a non-standard extension - it's understood by the plugin above but if you drop the Markdown in a text editor or convert it with a standard md2html converter it won't do anything.

> Basically, it seems we're moving away from the concept of durable data, which works and makes sense even if Joplin stops working, or even if you want to move that data to a different note taking app.

I'm not entirely sure, if I can agree with that. There are a lot of Markdown tools out there that use and understand a `toc` keyword. e.g. [MacDown](https://macdown.uranusjr.com/) uses `[toc]`, [Editor.md](https://pandao.github.io/editor.md/en.html) (online markdown editor) uses `[TOC]`, and I have seen several other apps that use `[[toc]]`.
Others (e.g. [Typora](https://typora.io/)) use an outline panel that shows the table of contents in a panel (like the one you use for the notebooks), which makes sense for an editor, but maybe less sense for a note-taking app.

> With that in mind, I'm thinking an alternative would be to have this table of content auto-generated as markdown by a tool. It would work like Word where you have the full TOC and you can manually refresh it whenever you want (maybe we could have an option to do it automatically for Joplin).

This is also not a bad idea. I just thought that the this would be much more work than just installing a plugin and adding it to your renderer.
As long as it is something that is done automatically, it is a good concept, but how do you denote the table of contents? In your example above, you would have to use something like this:

```
<!-- TOC -->
<!-- /TOC -->
```

A single `<!-- TOC -->` would not do the trick, if you wanted to use several tocs in your markdown, eg. also in the middle or the end of the text. But maybe I'm wrong, maybe a single marker works as well.

The only disadvantage I could perceive at the moment is that your approach requires you to change the source (your markdown file). What happens if it goes haywire and irrevocably screws up the note?
Without an included `Undo` option in the editor this could be dangerous.

However, maybe something like this could help with your idea:
https://github.com/adamjgrant/Smooth-ToCer

No matter how this is implemented in the end, I think we all can agree on the fact that a generated toc is a huge help for long and highly structured notes.

**Comment by ComputingFroggy** [comment]
any kind of TOC with markdown or not, would be a great help !

**Comment by laurent22** [comment]
Thanks for the feedback. It's good to know that other applications are also using this syntax. I haven't made up my mind yet about it - I think the right solution will be the one that's indeed simple to implement, but also with good compatibility with other existing Markdown apps.

**Comment by tessus** [comment]
The [following came up on the forum](https://discourse.joplin.cozic.net/t/example-of-good-looking-note-taking-apps/1345/34?u=tessus) and I think it is a great idea:

_I really liked how Zettlr does ToC: they’re not in the text itself, but as a handy button in the toolbar. So when I want to jump around in the doc while editing, it’s always just two clicks away, no scrolling to the Table of Contents._

Although I'd rather see a shortcut option (instead of or additionally to to the toolbar button mouse click). Also, it should be possible to navigate the TOC entries by keyboard and hit enter at the correct position to jump to the heaeder in the note.

**Comment by gmaosn** [comment]
Indeed, a TOC feature would be very helpful.

Thanks a lot for this great app!

**Comment by bogusred** [comment]
@tessus Typora also uses `[TOC]`

**Comment by xvol** [comment]
@tessus please check out my repo [generateTOC](https://github.com/xvol/generateTOC).
Looking to implement into Joplin after I clean it up. Then hopefully can integrate into the main app.

**Comment by laurent22** [comment]
@xvol, looks good but I don't think we can use it as it's done in Python and we use Javascript (node.js).

**Comment by xvol** [comment]
> @xvol, looks good but I don't think we can use it as it's done in Python and we use Javascript (node.js).

No issues. I'll rewrite in node and see if I can integrate with Joplin locally. I am a noob with programming but I'll do my best.

**Comment by tessus** [comment]
Your code would allow the implementation of the following:

_ToC not in the text itself, but as a handy button in the toolbar. So when I want to jump around in the doc while editing, it’s always just two clicks away, no scrolling to the Table of Contents._

(from a comment above and the forum)

I think the most important part is adding the internal anchors for the headers (replacing the existing HTML). What happens, if there are 2 headers with the same name? Does your 'slugify' function take such a case into account?
This is certainly one of the most wanted features (it's in the top 10). I can't wait to see your first crack at it. 👍

**Comment by peng19832** [comment]
I installed joplin.exe on win10, how do I load the markdown-it plugin？
I have not found a way to load the plugin in the documentation.

**Comment by tessus** [comment]
@peng19832 there's no way to activate the plugin in the UI yet. We are evaluating different options making TOC available to users.
Please be patient. I know, it's an important feature and believe me, I want to have it as much as you do.

**Comment by peng19832** [comment]
@tessus Ok, I hope this project is getting better and better.

**Comment by tessus** [comment]
added in 0c2f2667d3f202d1a18a751b884e6c3981ab5ae0

Available in release [1.0.142](https://github.com/laurent22/joplin/releases/tag/v1.0.142)

**Comment by bogusred** [comment]
W00t. Thank you @CalebJohn for this contribution! 🙏 and to everyone else who contributed to the discussion!

**Comment by starstuff** [comment]
Thank you for TOC!
