### ISSUE TITLE
iOS cursor jumps randomly when tapping new locations in long note

### ISSUE THREAD

**Issue by thekenshow** [laurent22/joplin#4784]
When editing a Note with the cursor in located in the visible text (keyboard is displayed):

- If a new location in the currently visible text is tapped, it works as expected. 
- If the Note is first scrolled so the current cursor position is no longer visible, tapping the desired new location causes the screen to scroll and the cursor is placed in an intermediate location.

## Environment

Joplin version: 10.7.2
Platform: iOS
OS specifics: 14.4.2 on iPhone 7

## Steps to reproduce

1. Create a note longer than available editing screen region.
2. Enter editing mode.
3. Tap a location in the displayed text.
4. Scroll so the current cursor location is no longer visible.
5. Tap a new location in the displayed text. 
6. Screen scrolls by itself and cursor is placed in a location between the original and requested new location.

## Describe what you expected to happen

The cursor moves to the new tapped location in the text.

## Logfile

Can't copy or export iOS log view. Screenshot of most recent log data attached.

![IMG_DF0BCA197F19-1](https://user-images.githubusercontent.com/998832/113144763-9d7d8580-91fb-11eb-970b-662547eeb150.jpeg)

**Comment by starlessblack** [comment]
I, too, have been plagued by this bug in the iOS app, and it's grown to the level of infuriating a few times recently. Thank you for posting a nice explanation of the issue.

**Comment by gbgbenton** [comment]
Hello, 

Could this be re-opened? I just did a new installation on a new ipad Mini 6 and I am experiencing exactly the described beahviour. If the cursor is in the invisible part of the screen it gets set to a seemingly random place when trying to position it somewhere.

Any help would be appreciated.

Gerd

**Comment by hhermerschmidt** [comment]
Hi,

I do have the same problem. The bug is still there. What kind of information do I need to provide, that it can be analyzed and fixed?

Best regards
Henning
