### ISSUE TITLE
Unable to clip page in Reader View (Firefox)

### ISSUE THREAD

**Issue by manthanf1** [laurent22/joplin#4785]
From Laurent: Readability library needs to be updated

* * *

Reader mode allows to strip down page to reading contents, and is built-in Firefox.
"Clip simplified page" is available but doesn't remove a lot of elements that Reader mode does.

When clipping page with Reader View enabled, the clipper extension outputs its not available on this tab due to: Missing host permission for the tab
`The Joplin extension is not available on this tab due to: Missing host permission for the tab`

Example URL: https://en.wikipedia.org/wiki/Marc_Rich

Joplin version: 1.7.11, prod
Platform: Kubuntu 20.10

From what I understand, about:reader and other internal privileged pages are unavailable to extension APIs that require host permissions. Extensions can still access some page content on privileged pages if they have right-click context menu integration.

What are your thoughts on this?

**Comment by manthanf1** [comment]
If you're referring to the library used by "Clip simplified page", then please do upgrade it to one used by FF v87.0

There's a lot of difference in terms of stripping content

**Comment by dz2106** [comment]
I am going to take a look at this issue
