### ISSUE TITLE
Unexpected behaviour with lists

### ISSUE THREAD

**Issue by TheSYNcoder** [laurent22/joplin#4786]
So in normal editors like this one in github when on pressing a numbered list icon or bulleted list icon should insert the new list afterwards in a new line however in this case all the lists are concatenated in a single line.
The attached video can make it more clear.
( I have changed some of the default outputs in my local, so it's showing Cool Bulleted Item instead of List Item etc).

If it really is a bug, i would like to work on it !

## Environment

Joplin version: 1.80
Platform: macOS
OS specifics: macOS Big Sur version 11.2.3

## Steps to reproduce

1. Go to the notebook
2. Click on numbered list
3. Click on bulleted list

https://user-images.githubusercontent.com/29038402/113150219-781b6680-9251-11eb-9be2-b6aaa0ba1c54.mov

**Comment by laurent22** [comment]
Per rule 1 of the guidelines, we only accept pull request on issues that existed before GSoC started - https://joplinapp.org/gsoc2021/pull_request_guidelines/
