### ISSUE TITLE
Date Picker Display on maOS 

### ISSUE THREAD

**Issue by thekenshow** [laurent22/joplin#4787]
Right edge of alarm date picker background (half of the Sat column) is transparent, making those dates hard to read. 

![Screen Shot 2021-03-31 at 7 51 20 AM](https://user-images.githubusercontent.com/998832/113148541-f18a6900-91ff-11eb-9bce-9341eab23647.png)

## Environment

Joplin version: 1.7.11
Platform: macOS 
OS specifics: 10.15.7

## Steps to reproduce

1. Create or select a to-do item.
2. Click Set Alarm (ringing bell) icon.
3. Click the **Set alarm** field.
4. Right side of date picker background is transparent. 

## Describe what you expected to happen

White background is consistently rendered behind date grid.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/6236853/log.txt)

**Comment by JackGruber** [comment]
Is fixed in v1.8.1  #4397
