### ISSUE TITLE
Copied text from Rich Text editor cannot be pasted outside of Joplin

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#4788]
- Select some text in Rich Text editor
- Try to paste it inside the editor itself - it works
- Try to paste it in an external editor - it doesn't work

on v1.8

**Comment by laurent22** [comment]
Caused by #4725

**Comment by nishantwrp** [comment]
@laurent22 That's weird. Can you please tell which editor did you try to use. So, that I can examine what went wrong. Thanks! (I tested it with LibreOffice Writer works well in that)

**Comment by laurent22** [comment]
VSCode. I assume that calling clipboard.writeHTML also clears the plan text part of the clipboard.
