### ISSUE TITLE
Windows desktop app issues

### ISSUE THREAD

**Issue by deljones** [laurent22/joplin#4789]
Hello all... 

A long-time user of Joplin. I have the app on my MAC, Windows desktops, and two Android devices.

I have updated the Windows version on a new Windows laptop. The install was fine and a connection to my Nextcloud instance is good.

> Joplin 1.7.11 (prod, win32)
> 
> Client ID: dedefad44c1e4e158673f8df2de0e1bc
> Sync Version: 2
> Profile Version: 34
> Keychain Supported: Yes
> 
> Revision: f560563d8 (master)

However, the NOTEBOOK structure does not appear on the Windows laptop as well as the TAGS. The "All Notes" is still visible, all of the notes are there. I can create a new note on any device and the note is synced everywhere. I am not able to create a NOTEBOOK or TAG on the new windows laptop installation, the entry box pops up for a new NOTEBOOK or a TAG, but I cant type anything into the box.

Am I missing something? I have uninstalled (successfully) and reinstalled (successfully) several times with the same result, I have even looked at the registry as per the Joplin FAQ.

Can anyone help...?

Dj

**Comment by laurent22** [comment]
Sounds like you just need to wait for sync to complete on all devices. The structure doesn't appear because the notebook object hasn't been downloaded yet.

**Comment by deljones** [comment]
Yes I thought that too, but its been on overnight with no change :(

I'll try one more reinstall...

dj

**Comment by laurent22** [comment]
Otherwise it means there's an error somewhere and we'll need to see the logs.

**Comment by deljones** [comment]
OK thanks for that... Where can i find the logs for the Windows version?

kind regards

dj

**Comment by JackGruber** [comment]
From the Issue template: 
>Please attach a debug log. Issues without a debug log are likely to stall.
>For information on how to collect a log file: https://joplinapp.org/debugging/

**Comment by deljones** [comment]
FIXED....
 For some reason the directory joplin-desktop from .config did not get deleted when uninstalling, so I reinstalled then deleted this directory, Opened Joplin. Of course all of the settings are default, empty so I just re-synced and now all is good.

Dj
