### ISSUE TITLE
clicking `New Note` deletes currently selected note (v1.0.84) !!!

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#479]
### Operating system

- macOS

### Application

- Desktop

I've just installed the new version of Joplin: v1.0.84.

Then I clicked on `New Note` and my currently selected note was gone. The title was still there, but the text was gone.
Now I have to find a way to get back my notes.

This is really a problem. Please do not release new versions without running basic tests first.

**Comment by laurent22** [comment]
Yes sorry about that, I took that version offline for now and it will be fixed in the next one.

**Comment by tessus** [comment]
Unfortunately restoring the note on the server and downgradig the client did not help.

The note is still empty. I suspect some timestamp is still in the local database, which always overwrites my remote note with the empty one.

**Comment by laurent22** [comment]
To recover the note, if you use Nextcloud you can use the versioning feature to restore the previous version.

**Comment by tessus** [comment]
Yes, I did that. However, the notes still show up as empty in the Joplin app.

**Comment by laurent22** [comment]
Right, it won't pick up the remote note because the local timestamp is newer than the remote one.

You can either change the remote updated_time property to something like 1525205272000 (now's timestamp) or simply copy and paste the note text back to the local client.

**Comment by tessus** [comment]
I see this is the note:
```
id: 23a0051df9e94d2b93d6f1145df11d3c
parent_id: d40906f82425412cbc64da2157d0a7db
created_time: 2018-04-07T07:41:16.216Z
updated_time: 2018-04-11T07:13:15.053Z
is_conflict: 0
latitude: 
longitude: 
altitude: 0.0000
author: 
source_url: 
is_todo: 0
todo_due: 0
todo_completed: 0
source: joplin-desktop
source_application: net.cozic.joplin-desktop
application_data: 
order: 0
user_created_time: 2018-04-07T07:41:16.216Z
user_updated_time: 2018-04-11T01:24:13.499Z
encryption_cipher_text: 
encryption_applied: 0
type_: 1
```

so what shall I change? `updated_time` or `user_updated_time`? is that UTC or what timezone is used?

**Comment by laurent22** [comment]
It should be updated_time, and it's UTC time so you could set it to for example 2018-05-01T20:15:00.000Z

**Comment by laurent22** [comment]
> I've noticed that the task items now (in 1.0.84) have bullets in front of them.

Yes it was to fix #363. Previously the bullets were removed in a hacky way, which was causing this bug. I'm aware of the issue but at the moment I don't know how to fix it.

**Comment by tessus** [comment]
Thanks for the info.

I checked the code you used. Why was it hacky? It should be perfectly legal to use `ul.style.listStyleType = 'none';`

I hope you find a solution though.

**Comment by tessus** [comment]
Oh, I totally forgot: Thank you for the quick fix.
