### ISSUE TITLE
Change location of synchronization will delete local file 

### ISSUE THREAD

**Issue by cyaomushen** [laurent22/joplin#4792]
Change location of synchronization will delete local file 

## Environment

Joplin version:  1.7.11
Platform:  windows
OS specifics: win 10

## Steps to reproduce

1.  change the lcoation of synchronization , and unselect Fail-safe
2.  start to synchronization 
3.  local file will be delete 

## Describe what you expected to happen

What I expected is when I change the location of  synchronization , 
if remote is empty ,program auto upload local file to remote 
if remote is not empty, and no file conflict , then merge all local and remote to a new verison
if some file is conflict ,tell user, then user decide which one will be saved

## Logfile

there are no log file

**Comment by tessus** [comment]
Joplin uses 2-way sync. There is no master/slave (server/client) concept.
This is not a bug.

This has been explained in the FAQ and on the forum many times.
