### ISSUE TITLE
Docs: joplin.views.panels.create() should be called with an argument

### ISSUE THREAD

**Issue by xUser5000** [laurent22/joplin#4796]
## Description
As per the [documentation](https://joplinapp.org/api/references/plugin_api/classes/joplinviewspanels.html#create), the method `joplin.views.panels.create();` have a required `id` parameter. However, the tutorial of the TOC plugin ([here](https://joplinapp.org/api/tutorials/toc_plugin/#creating-a-webview)) calls the method without providing the required parameter.

## Describe what you expected to happen
Calling `joplin.views.panels.create();` with an `id` argument.

**Comment by tessus** [comment]
already fixied in 99b55129f2c7a2ba6e05bb3ad04ad9ef0b4d575e
