### ISSUE TITLE
scroll position is not remembered

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#4797]
## Environment

Joplin version: 1.7.11 (I've just noticed this on git dev c044017ba as well)
Platform: macOS, Windows

## Steps to reproduce

1. Use Markdown editor (layout: `editor` or `split view`) 
2. Edit note a few pages down
3. Switch to another note
4. Switch back
5. The scroll position is reset and at the top of the note (or sometimes at a random location within the note)

## Describe what you expected to happen

The scroll position should be remembered properly and switching back to the note should allow me to edit where I left off

## Additional info

It seems that this issue is not consistent. It sometimes works, but most of the time it doesn't.
The fact that switching back also sometimes changes the scroll position to a random location points to maybe a corrupted state.

/ref https://discourse.joplinapp.org/t/return-where-you-were-before-instead-of-jump-to-top/16329?u=tessus
/ref https://discourse.joplinapp.org/t/plugin-note-tabs/12752/25?u=tessus

## Logfile

Nothing in the logs

**Comment by laurent22** [comment]
Looks like it still works with the rich text editor. So it's only in "editor" layout that it's broken, not split view?

**Comment by tessus** [comment]
Actually it's also in split view. I usually add text to the top of the note, so I haven't seen this issue for the longest time, but after seeing the issue on the forum I've been doing some tests and I can confirm it. Unfortunatelty I wasn't able to ascertain a pattern when this is happening. Neither when and how it manifests (top of the note / random location).
I forgot to add the split view to the repro steps. I'll change it in a sec.

**Comment by lkiThakur** [comment]
> Looks like it still works with the rich text editor. So it's only in "editor" layout that it's broken, not split view?
I think **only the viewer remembers the scroll position** 
so in split mode it will work or not depending upon whether before switching to other notes viewer or editor was in focus.

**Comment by lkiThakur** [comment]
> Neither when and how it manifests (top of the note / random location)

It's possible that  below situation occured to the user who was reporting random location jumping.
1. he/she scrolled to some section while focus was on viewer ; so viewer saved this scroll position
2. he/she switched focus to editor and scrolled to some other section in the note 
3. he/she switched note and when returned to it note auto scrolled to the section  that was saved in step 1

**Comment by tessus** [comment]
> I think only the viewer remembers the scroll position

If that were the case, it wouldn't work sometimes when using just the editor layout.

**Comment by roman-r-m** [comment]
Also noticed a related issue: if I go to another note via a markdown link, then go back, in my test the text was scrolled to the top but the scrollbar was showing as if it was at the bottom.

Video:
![ezgif com-gif-maker(4)](https://user-images.githubusercontent.com/995612/113449263-5c50c580-93f5-11eb-98a8-b5ab29b58854.gif)

**Comment by itge13** [comment]
> 
> 
> 
> I think **only the viewer remembers the scroll position**
> so in split mode it will work or not depending upon whether before switching to other notes viewer or editor was in focus.
I tried this and it doesnt work for me.

**Comment by jayhill** [comment]
I think it would be more useful if the caret position would be restored (i.e. line 208, column 29), and I'd expect the scroll position could follow easily from that.

The caret always seems to be at the top when I return to a note, even if the scroll position is restored, but then I often can't actually see where the caret is and I have to use the mouse to place the cursor in the desired location before I can continue editing.

**Comment by tessus** [comment]
@jayhill This was my initial idea when opening ticket #520. I think it has to be a combination of both. The scroll posiiton and the cursor position should be saved (and also restored) at the same time . Maybe it was a problem with the editor back then.

Laurent might be able to shed some light on this.
