### ISSUE TITLE
html ids bug

### ISSUE THREAD

**Issue by itge13** [laurent22/joplin#4798]
if you use html ids they only work once, after that, a click doesn't bring you anywhere

<p id="x"></p>
<a href="#x">X</a>

workaround: if you click a different id, the other works again (for one time).

newest version, win 10 x64

**Comment by itge13** [comment]
@tessus what do you mean with "no template"?

**Comment by tessus** [comment]
When you open a bug, there's template you are supposed to fill out. You deleted the template and the first version of your description did not make any sense - or at least I did not understand what the issue was.
