### ISSUE TITLE
error when opening app for first time after update

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#480]
### Operating system

- macOS

### Application

- Desktop

Joplin v1.0.85

When I double-click the app, I get the following popup:

<img width="445" alt="screen shot 2018-05-01 at 19 35 00" src="https://user-images.githubusercontent.com/223439/39498746-f724d6f4-4d77-11e8-8daa-3288954e2664.png">

After clicking ok, the app closes.

After that, everything is ok. The second time I tried opening the app, everything worked as expected and I've never seen the error since.

**Comment by laurent22** [comment]
Not sure where this flag comes from. The app is designed to exit if it is passed a flag it doesn't know (to avoid issues when a flag is misspelled), however there's no such -psn_... flag anywhere so maybe it's something that macOS passes to all app on startup. I will leave the issue open in case someone knows something about it.

**Comment by laurent22** [comment]
Ok found it - https://stackoverflow.com/questions/10242115 I will just add a case to ignore this argument.
