### ISSUE TITLE
Old image decryption errors persist

### ISSUE THREAD

**Issue by markrenier** [laurent22/joplin#4803]
I understand that the "large images not decrypting" issue was fixed a while back, but I am experiencing problems with "older versions" of those images. 

On PC "A" Joplin app, I added an image to a task, then synch to DropBox. 
On PC "B" Joplin app, I synch with DropBox and get decryption errors on those images. I am unable to edit the image on PC B. 
On PC A, I edit the image, cropping it, so that the image is smaller than 10 MB, then synch to DropBox. 
On PC B, I synch with DropBox and get a decryption error on those images. I go to the note in question and can see/view the image properly. I can edit the image properly. I synch PC B with DropBox. 
On PC A, I synch with DropBox, and get no decryption errors. I go to the note containing the image and can see/view the recent edits. I edit the image, save the note, and resynch to DropBox. 
On PC B, I synch with DropBox, and get a decryption error on that image. I go to the note containing the image and confirm my recent changes from PC A. 
On PC A, I go to Joplin> Tools> Options> Note History> and set "Keep note history (days)" to 1, then synch with DropBox.
On PC B, I go to Joplin> Tools> Options> Note History> and set "Keep note history (days)" to 1, then synch with DropBox. I still see the decryption error, but I can see and edit the image just fine. No errors on PC A ever. 
Assuming that the "1 day" setting is delayed somehow, i allow time to pass, to allow the clean-up mechanism on old notes/resources the ability to catch up. It's been over a month now and no new decryption errors appear, but the old decryption errors do not go away. 

It appears that older versions of files are "stuck" somehow? The notes above describe the issue with a single image in a single note, but I have this happen with 19 images actually. The time required to attempt the decryption of 19 images is getting to be a bother, but it does take noticeable time.

Both PC A and PC B have: 
Joplin 1.7.11 (prod, win32)
Client ID: 348634c19a984fbc80460ee0b23c7d45
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes
Revision: f560563d8 (master)

**Comment by roman-r-m** [comment]
Are there any errors in the log?

**Comment by markrenier** [comment]
No, there are no errors. There are a bunch of warnings though. 
![image](https://user-images.githubusercontent.com/7487055/113602792-594b1480-9643-11eb-97f0-88b35a232a9f.png)
