### ISSUE TITLE
Note converts to todo note when toggling complete/incomplete

### ISSUE THREAD

**Issue by benmordecai** [laurent22/joplin#4808]
Note converts to todo note when toggling complete/incomplete.

## Environment

Joplin version: joplin 1.7.0
Platform: Linux terminal
OS specifics: Manjaro

## Steps to reproduce

1. Select non-todo note
2. press space bar
3. 

## Describe what you expected to happen
Either no action, since the note is not a todo list, or for multiple presses of the spacebar to convert it back into the non-todo note.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/6253431/log.txt)

**Comment by axtyax** [comment]
I'd be happy to take this on as a first issue, if that's alright with you.

**Comment by laurent22** [comment]
Should be no action if it's not a to-do.

**Comment by hxing9974** [comment]
Quick work-around:

```
> set %n is_todo 0
```

should convert the TODO back into a NOTE

**Comment by laurent22** [comment]
See PR for details
