### ISSUE TITLE
Cannot install Terminal version of Joplin unter 

### ISSUE THREAD

**Issue by Tackoa** [laurent22/joplin#4809]
I have tried to install Joplin with following command:
`NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin`

I receive following error message:
npm ERR! code 127
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/laurent22/uslug.git
npm ERR! /bin/bash: git: command not found

node12 is install, also npm.

**Comment by CalebJohn** [comment]
As the error says, you must have git installed. Please install it and try again.

**Comment by Tackoa** [comment]
Git is installed, but now I receive the next error message:

npm ERR! code 1
npm ERR! path /home/krpi/.joplin-bin/lib/node_modules/joplin/node_modules/keytar
npm ERR! command failed
npm ERR! command sh -c prebuild-install || npm run build
npm ERR! > keytar@7.6.0 build
npm ERR! > node-gyp rebuild
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=12.22.0 runtime=node arch=arm libc= platform=linux)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@12.22.0 | linux | arm
npm ERR! gyp http GET https://nodejs.org/download/release/v12.22.0/node-v12.22.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v12.22.0/node-v12.22.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v12.22.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v12.22.0/SHASUMS256.txt
npm ERR! gyp info spawn /usr/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/krpi/.joplin-bin/lib/node_modules/joplin/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/krpi/.joplin-bin/lib/node_modules/joplin/node_modules/keytar/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/krpi/.joplin-bin/lib/node_modules/joplin/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/krpi/.node-gyp/12.22.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/krpi/.node-gyp/12.22.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/krpi/.joplin-bin/lib/node_modules/joplin/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/krpi/.node-gyp/12.22.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/krpi/.joplin-bin/lib/node_modules/joplin/node_modules/keytar',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Package libsecret-1 was not found in the pkg-config search path.
npm ERR! Perhaps you should add the directory containing `libsecret-1.pc'
npm ERR! to the PKG_CONFIG_PATH environment variable
npm ERR! No package 'libsecret-1' found
npm ERR! gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/krpi/.joplin-bin/lib/node_modules/joplin/node_modules/node-gyp/lib/configure.js:345:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
npm ERR! gyp ERR! System Linux 5.10.17-v7+
npm ERR! gyp ERR! command "/usr/bin/node" "/home/krpi/.joplin-bin/lib/node_modules/joplin/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/krpi/.joplin-bin/lib/node_modules/joplin/node_modules/keytar
npm ERR! gyp ERR! node -v v12.22.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/krpi/.npm/_logs/2021-04-04T18_39_13_029Z-debug.log

**Comment by roman-r-m** [comment]
>  npm ERR! Package libsecret-1 was not found in the pkg-config search path.

**Comment by roman-r-m** [comment]
also see here https://github.com/laurent22/joplin/issues/3960

**Comment by Tackoa** [comment]
Thank you for your support so far. I am nearing success but have now the problem that the process stuck at some point.

[                  ] \ reify:aws-sdk: timing reifyNode:node_modules/joplin/node_modules/lodash Completed in 27467ms

Do you have a solution for that?

**Comment by Tackoa** [comment]
Worked, many thank! :)
