### ISSUE TITLE
linking problems

### ISSUE THREAD

**Issue by itge13** [laurent22/joplin#4816]
1.
if you use html ids they only work once, after that, a click doesn't bring you anywhere and it just let you where you are.
```
<p id="x"></p>
<a href="#x">X</a>
```
workaround: if you click a different id though, the other works again (but all links work only one time until another is clicked).

2.
if you use links to other notes like 
`[blabla](:/c1715fe2498595944...)`
and click the return button it doesn't work.

_Joplin 1.7.11 (prod, win32)
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes
Revision: f560563d8 (master)_

**Comment by CalebJohn** [comment]
Hi @itge13 This was fixed by #4538 . The fix is available in pre-release v1.8.1.
