### ISSUE TITLE
onedrive default directory

### ISSUE THREAD

**Issue by johandeclercqdemocon** [laurent22/joplin#4825]
Hi, what is the default directory that Joplin uses when you sync with OneDrive ? 

## Environment

Joplin version: 1.7.11 (installed with snap)
Platform: Linus
OS specifics: Ubuntu 20.4

## Steps to reproduce

1. 
2. 
3.

**Comment by bdrewery** [comment]
"Apps/Joplin" unless that already exists then it tries "Apps 1/Joplin".
