### ISSUE TITLE
The Yeoman plugin scaffold generator is out of date

### ISSUE THREAD

**Issue by BeatLink** [laurent22/joplin#4828]
## Environment

Joplin version: 1.7.11 (application) 1.7.3 (yeoman scaffolding)
Platform: Linux
OS specifics: Linux Mint Cinnamon 20.1 (Flatpak)

## Steps to reproduce

1. Go to https://github.com/laurent22/joplin/tree/dev/packages/generator-joplin
2. Notice that the last update was 2 months ago, and the version is at 1.7.3
3. Certain plugin API features such as dataDir are unavailable until 1.7.10 https://joplinapp.org/changelog/

## Describe what you expected to happen

I would expect that the Yeoman scaffolding framework would have been updated to the latest version, 1.7.11, and that I can use the new API features by executing yo joplin --update

I am working on the following plugin https://github.com/BeatLink/joplin-plugin-repeating-todos and I require the dataDir capability to store the sqlite database that will be used by the plugin

**Comment by JackGruber** [comment]
You can manuel edit the files in the api folder or try a workaround like descriped by laurent in  https://github.com/laurent22/joplin/issues/4774

**Comment by BeatLink** [comment]
Wouldn't the best way to resolve this be to update the generator? Especially since any tinkering with the API folder would just be wiped out in a future update

**Comment by BeatLink** [comment]
To start with, what is currently blocking the update of the generator?
