### ISSUE TITLE
iOS: Image attachments not downloading, shows huge placholders

### ISSUE THREAD

**Issue by Jip-Hop** [laurent22/joplin#4829]
Image attachments don't download when "Attachment download behaviour" is set to "Auto" or "Manual". Instead I only see a huge placeholder (black download arrow icon).

![placeholder](https://user-images.githubusercontent.com/2871973/114298801-6428fd80-9ab8-11eb-9fa1-8a87180dd460.jpg)

## Environment

Joplin version: 10.7.2
Platform: iOS
OS specifics: 14.4.2
Joplin server (Docker): 1.7.2

![IMG_7099](https://user-images.githubusercontent.com/2871973/114299091-d817d580-9ab9-11eb-889d-8bb9af69d593.jpg)

## Steps to reproduce

1. Open a note with image attachments
2. See placeholder icon
3. Close Joplin (really quit, swipe it away in the 'task switcher')
4. Reopen Joplin and open the same note
5. This time no placeholder, the image loads

This happens to my notes imported from Evernote, and notes clipped in HTML format with the Joplin Web Clipper. I just made a new note in the WYSIWYG editor on my desktop, added an image, opened the note on iOS and it did immediately show the image (no placeholder) with "Attachment download behaviour" set to "Auto". But many of my notes never load the images an keep showing the placeholders...

**Comment by laurent22** [comment]
Could you provide an example ENEX file that has this problem?

**Comment by Jip-Hop** [comment]
Hopefully this helps to clearly reproduce the error: [image_load_error.jex.zip](https://github.com/laurent22/joplin/files/6292661/image_load_error.jex.zip)

It contains two notes clipped with the Joplin Web Clipper. I clipped the same site twice, once with "Clip complete page" and once with "Clip complete page (HTML) (Beta)".

1. Start with a fresh Joplin Desktop: remove default notes and notebook
2. Sync with a new user on Joplin Server
3. Import my jex export file
4. Sync from desktop to the server
5. Remove the Joplin iOS app, reinstall and start fresh (remove default notes and notebook)
6. In the iOS settings, set the "Attachment download behaviour" to Auto
7. On iOS fill in the credentials to sync with Joplin Server, test connection then close the app
8. Re-open the app, sync and wait for sync to complete
9. Then open the first note (the one tagged with HTML) and scroll down
11. Only the first image loads, the rest shows the huge placeholders (pinch to zoom out to see them better)
12. Open the second note and scroll down
13. All images load fine
14. Open the HTML note again to see if it loads the images on second try (still shows placeholders)
15. Go to home screen with home button and go back into the app to see if images will load (still shows placeholders)
16. Close the app by swiping it away in the task switcher
17. Open the Joplin again and go to the HTML note
18. This time all images load

I closed my Evernote account so I can't provide an ENEX file which has these problems, but as we can see the bug is not specific to Evernote.

**Comment by Jip-Hop** [comment]
This is still an issue for me on iOS (Joplin 10.8.1). HTML notes (clipped with the Firefox web clipper) load the placeholder icons instead of the images. I have to quit and reopen Joplin iOS for the images to be loaded.

**Comment by Jip-Hop** [comment]
Can this be reopened? Info is still relevant and issue isn't fixed.

**Comment by laurent22** [comment]
That should be fixed now since we set the width and height of imported images
