### ISSUE TITLE
Joplin do not display part of page in case it saved in html format

### ISSUE THREAD

**Issue by jabacrack** [laurent22/joplin#4830]
## Environment

Joplin version: 1.7.11
Platform: Windows
OS specifics:  Windows 10
Clipper version: 1.6.1
Browser: Firefox

## Steps to reproduce

1. Import attached note (it clipped from https://habr.com/en/post/551732/).
[Algorithms in Go_ Bit Manipulation _ Habr.zip](https://github.com/laurent22/joplin/files/6291592/Algorithms.in.Go_.Bit.Manipulation._.Habr.zip)
2. Look at imported note.
2. Only part of the article displayed.
3. Find and remove in html source `<a name="habracut"></a>`.
4. Now full article displayed.

## Describe what you expected to happen
Html page should render without editing.

## Logfile
Debug log doesn't contain any error.

**Comment by jabacrack** [comment]
I think this bug isn't connected with clipper, because you can remove this tag inside the note source and it starts working. Probably a problem with renderer.

**Comment by mablin7** [comment]
I see the problem too. I tried copying the whole clipped html and pasted into a newly created note and it displayed correctly. I have absolutely no idea what could cause this, but this is at least a workaround. 

Did you notice this problem with any other site?

**Comment by jabacrack** [comment]
> Did you notice this problem with any other site?

No, but I start use Joplin week ago, and this issue stop my migration from evernote. I'll try with other sites.

**Comment by jabacrack** [comment]
Check on 2.0.11, issue still here.
