### ISSUE TITLE
MacOS : can't paste without formatting in the WYSIWYG editor

### ISSUE THREAD

**Issue by AdvisedlyAlburn** [laurent22/joplin#4831]
OS : MacOS 11.2.3
Joplin version : 1.7.11

On evernote I can use CMD + SHIFT + V to paste some content without the formatting. 

On Joplin, on the WYSIWYG editor, there is no equivalent shortcut. Can you add one? It's super annoying because every time I copy something to the browser I must first paste it in the search box to remove formatting, then copy it again and then paste it on Joplin.

**Comment by laurent22** [comment]
Cmd+Shift+V should work

**Comment by AdvisedlyAlburn** [comment]
@laurent22 No it doesn't paste. Only if I do CMD + V, which keeps formatting.

**Comment by laurent22** [comment]
For me it works but I'm on 1.8 so it might be that there was some fix about this not long ago.

**Comment by AdvisedlyAlburn** [comment]
@laurent22 No, I have tried 1.8.1 and it's the same problem

**Comment by laurent22** [comment]
Then more info is needed. For me that's how it looks with Cmd+V:

![image](https://user-images.githubusercontent.com/1285584/114428783-899b3180-9bb4-11eb-8d01-056d287176fa.png)

And with Cmd+Shift+V:

![image](https://user-images.githubusercontent.com/1285584/114428841-99b31100-9bb4-11eb-980b-95f51082e585.png)

**Comment by AdvisedlyAlburn** [comment]
@laurent22 well when I go to the Help menu and I search "paste", it will only show "Edit > Paste" as CMD + V but there is no indication of how to paste without formatting, it doesn't appear in the Edit menu. Do you have something like "Edit > Paste without formatting" on your mac?

**Comment by laurent22** [comment]
CMD + SHIFT + V is to paste some content without the formatting.

**Comment by AdvisedlyAlburn** [comment]
I don't know what more can I say to help solving the bug. It just doesn't work, CMD + SHIFT + V does nothing. Anyway I don't really care as I will switch to Linux soon but it's a serious annoyance IMO
