### ISSUE TITLE
Low Contrast Text appears when "Could not find specified string." is displayed in darkmode.

### ISSUE THREAD

**Issue by Chris4942** [laurent22/joplin#4835]
## Environment

Joplin version: 1.7.11
Platform: Mac OS
OS specifics: Mac OS Big Sur 11.2.3

## Steps to reproduce

1. Put Mac In Dark Mode
2. Open jolin
3. Open a note
4. Press CMD+F
5. Type in a string that does not appear in the note you are looking at.
6. A popup will appear, but the text will barely be readable as it will be dark blue text and dark grey.

## Expected Results

The text on the popup would be easily readable.

***
_I did not include a log file as this seems to be a purely aesthetic issue and so the text coloring of the modal likely needs to be changed from secondary to primary or something like that_

![image](https://user-images.githubusercontent.com/64553509/114652074-68187380-9ca2-11eb-8f50-133e642273b4.png)

**Comment by axtyax** [comment]
In trying to reproduce this bug, I noticed using the CMD+F shortcut from a note gives regular find functionality and clicking on File->Search in current note gives the find and replace functionality OP used. Would it make sense to consolidate these two @laurent22 ?
