### ISSUE TITLE
Missing setting sync.9.url

### ISSUE THREAD

**Issue by mr-karan** [laurent22/joplin#4836]
## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Arch

## Steps to reproduce

1. As describe in [nextcloud-synchronisation](https://joplinapp.org/terminal/#nextcloud-synchronisation) docs, I was trying to setup the sync config for Joplin server.
2. `:config sync.9.url` returns this error `Unknown key: sync.9.url`                                                                                                                                         

## Describe what you expected to happen

It should be a valid setting.

It's missing in the schema: https://github.com/laurent22/joplin/blob/29a8e815d92c3f3cf8faef9056203085d713ceee/docs/schema/settings.json#L94

**Comment by laurent22** [comment]
should be sync.5
