### ISSUE TITLE
Lists are not listed in tables

### ISSUE THREAD

**Issue by thewholelifetolearn** [laurent22/joplin#4839]
## Environment

Joplin version: 1.7.11
Platform: Windows
OS specifics: 10
Joplin specifics: Softbreak is on

## Steps to reproduce

1. Create a table
2. Add a line with a list in one of the cells
3. The first line is in the cell as text and the other points are displayed outside the table as a list

## Describe what you expected to happen

```
|Foo|Bar|
|----|---|
|Cell 1| * lorem
* ipsum
* latin |
```
or
```
|Foo|Bar|
|----|---|
|Cell 1| 
* lorem
* ipsum
* latin |
```

At least the first proposition should work and display a list in the 2nd cell

**Comment by CalebJohn** [comment]
@thewholelifetolearn 

What you've shown is not a valid markdown table. Fortunately Joplin supports a multi-markdown table extension. You can enable under Options-> Markdown -> multi markdown tables

An example is below.

```
| Some | table |
|---|---|
| Cell 1 | - list item 1 \
|| - same cell as item 1 |
```
