### ISSUE TITLE
Execute joplin-cli command will delete joplin-desktop external editor file

### ISSUE THREAD

**Issue by cjc7373** [laurent22/joplin#4841]
## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Arch

## Steps to reproduce

1. Toggle external editting in joplin desktop.
2. Execute `joplin --profile $HOME/.config/joplin-desktop sync` or `joplin --profile $HOME/.config/joplin-desktop export`.
3. The md file `~/.config/joplin-desktop/edit-xxxxxx.md` will be deleted. So I'm unable to edit that note in external editor.

## Describe what you expected to happen

The file should not be deleted.

## Logfile

![image](https://user-images.githubusercontent.com/25873777/114752518-f535f800-9d88-11eb-8fd4-b7fc09bac33c.png)

**Comment by roman-r-m** [comment]
Do I understand it correctly - you had joplin desktop open and executed a command from joplin-cli pointed to the same profile?

**Comment by cjc7373** [comment]
Yes, exactly

**Comment by roman-r-m** [comment]
Running 2 instances concurrently off a single profile is not supported and may even lead to data loss.

**Comment by cjc7373** [comment]
Thanks for your clarification. Since this way is unsupported, I was wondering is there another way to export my notes using command line?

**Comment by roman-r-m** [comment]
> Thanks for your clarification. Since this way is unsupported, I was wondering is there another way to export my notes using command line?

You can do it just not when desktop app is open. You might also want to check backup plugin for Joplin desktop.

**Comment by cjc7373** [comment]
That would be helpful.

**Comment by roman-r-m** [comment]
https://discourse.joplinapp.org/t/backup-plugin/13964
