### ISSUE TITLE
Preserve whitespace and empty lines in non-markdown mode

### ISSUE THREAD

**Issue by mhatvan** [laurent22/joplin#4842]
## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Ubuntu 20.10

## Steps to reproduce

1. write text, enter some empty new lines
2. switch to a different note
3. switch back and the empty lines will be gone

## Describe what you expected to happen

Empty lines should be preserved, since they help me to visually distinguish between sections.

**Comment by mhatvan** [comment]
Bump

**Comment by AtticusBeachy** [comment]
Workarounds for separating sections:
1. Use *** to draw lines between sections.
2. If you are mainly trying to separate lists, edit the userstyle.css file to add more whitespace below each list. Or, if you have a header at the top of each section, you can add whitespace at the top of each header.
3. Switch to Obsidian.

For option 2, see:
https://discourse.joplinapp.org/t/removing-whitespace-at-paragraph-breaks/22598
https://discourse.joplinapp.org/t/introduction-to-customising-joplin-userchrome-css-userstyle-css/21370
