### ISSUE TITLE
Joplin with plantuml crash on add plantuml 

### ISSUE THREAD

**Issue by neepher** [laurent22/joplin#4843]
## Steps to reproduce

1.  add plantuml code block
2.  add component  with such style "component A { }"

## Logfile

Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
Version info
Joplin for Desktop

Copyright © 2016-2021 Laurent Cozic
Joplin 1.7.11 (prod, win32)

客户端 ID: 309fce02dca041e4b4b994499eff50ee
同步版本: 2
配置文件版本: 34
支持的密钥链: 是

修订: f560563d8 (master)
Component stack

    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by ResizableLayout)
    in div (created by styled.div)
    in styled.div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in ResizableLayout (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in ThemeProvider (created by RootComponent)
    in StyleSheetManager (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider

**Comment by mablin7** [comment]
This merged PR uphy/joplin-plantuml-plugin#4 fixed the issue, it just hasn't been released by the maintainer of the plugin. You should wait for a new release of the plugin.
