### ISSUE TITLE
Translation question

### ISSUE THREAD

**Issue by milotype** [laurent22/joplin#4846]
Please explain the following translation string:

#: packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/utils/setupToolbarButtons.js:27
msgid "Insert"

Which of the following does it represent (sorry, I'm not a programmer):

- [ ] underlined
- [ ] inserted string/inserting something
- [ ] link

**Comment by CalebJohn** [comment]
It corresponds to the `<ins>` html tag (insert). The default behaviour of insert is to render as an underline.
In the english translation of Joplin we use the word "insert" when the user hovers the button.

**Comment by milotype** [comment]
@CalebJohn Thank you for your answer!
Can you please also advise, wheter or not to translate strings in angle brackets and square brackets, like in the following example:

```
#: packages/app-cli/app/command-mv.js:14
msgid "Moves the notes matching <note> to [notebook]."
```

**Comment by CalebJohn** [comment]
@milotype 

[According to this forum post](https://discourse.joplinapp.org/t/translating-enclosed-strings/14638/3?u=calebjohn) you should not change strings in angle brackets or square brackets.
