### ISSUE TITLE
import md file with %20 (space) in a picture link

### ISSUE THREAD

**Issue by roooooc** [laurent22/joplin#4847]
## Environment

Joplin version:  1.7.11
Platform: windows
OS specifics: win10

## Describe what you expected to happen

mport a md file with a link of a picture  have a 

when import a md file with a  link of a picture , have space in it's name , like :

picture name : test .png
```
![picture](test%20.png)
```
the picture can't   displays well.

**Comment by Subhra264** [comment]
@roooooc  can you try adding 'file:///' at the beginning of the path( in the Joplin editor ), For example, 
```
[image](file:///path/to /your/image)
```

**Comment by Subhra264** [comment]
As far as I can see, the issue is with this line ---
https://github.com/laurent22/joplin/blob/ad09bd93d62a248f4741966a4983610ece826e3c/packages/app-desktop/gui/NoteEditor/utils/useMessageHandler.ts#L91

For example, if I write `[image](my%20file.png)`, the else part in the above file gets executed( as the path doesn't start with 'file:///' ), `openExternal` fails to find such file because the given local filepath is not decoded( `urlDecode` is not used, so it looks for `test%20.png` instead of `test .png`) and hence throws "Failed to open" error. 

Looks like, both `openPath` and `openExternal` don't work with URL-encoded paths not only when using the `file:///` protocol but also when the given path is actually a local file path( starting with 'C:' or 'home/' etc.).

**Comment by mablin7** [comment]
I can't reproduce this on 1.7.11 (win10). For me it's displaying perfectly:
![image](https://user-images.githubusercontent.com/7415668/115707885-961b4900-a36f-11eb-892c-e84596d40f5d.png)

@roooooc  are you sure the filename really has a space at the end? Windows normally doesn't let you name your files like that, I had to use the console to create a file for testing.

**Comment by roooooc** [comment]
@mablin7 Sorry, maybe I didn't express it clearly.

I means import it in joplin.

![图片](https://user-images.githubusercontent.com/10668973/122161291-06dc6e80-cea4-11eb-806e-5d7de10f531a.png)

examples：

1. test1

    before import
    ![图片](https://user-images.githubusercontent.com/10668973/122161571-88cc9780-cea4-11eb-97bb-eb69d86b6c79.png)
    
    after import
    ![图片](https://user-images.githubusercontent.com/10668973/122161793-ed87f200-cea4-11eb-9de9-adb9742eb2d9.png)

    the link of the image  is not converted normally .
    
2. test2

    before import
    ![图片](https://user-images.githubusercontent.com/10668973/122179552-38f8cb00-ceba-11eb-8579-c6d820e2f5e9.png)

    after import
    ![图片](https://user-images.githubusercontent.com/10668973/122183144-8a568980-cebd-11eb-8ca6-3449ef883ca0.png)

    
    the link is convert

3. test3

    before import
    ![图片](https://user-images.githubusercontent.com/10668973/122181189-b96bfb80-cebb-11eb-855f-d00ab2138e5a.png)
    
    After import
    ![图片](https://user-images.githubusercontent.com/10668973/122181306-d4d70680-cebb-11eb-8eb2-c036f9aac999.png)

4. test4

    Before import
    ![图片](https://user-images.githubusercontent.com/10668973/122181593-15368480-cebc-11eb-8d58-78208c783f45.png)

    After import
    ![图片](https://user-images.githubusercontent.com/10668973/122183005-66934380-cebd-11eb-8f03-656a1a874837.png)

so, I mean if I import a MD file in joplin, and there is a space in the path of the picture in the MD file, the link will not be converted well. 

Thanks.

**Comment by roooooc** [comment]
> 
> 
> @roooooc can you try adding 'file:///' at the beginning of the path( in the Joplin editor ), For example,
> 
> ```
> [image](file:///full/path/to/your/image)
> ```

hi
the picture can display if the link is full path.
![图片](https://user-images.githubusercontent.com/10668973/122215184-80dd1980-cedd-11eb-91c5-8ffb7f5aabf6.png)


but after import,  **the link was just copied. not convert to "hash link"  as expected like follow pictures** .

![图片](https://user-images.githubusercontent.com/10668973/122215508-e204ed00-cedd-11eb-94d3-f758861d3cc7.png)

**Comment by Cyb3rC3lt** [comment]
Just so you guys know this is still broken so not sure it should be closed. I have been trying to import MD files containing images with a space in their filename with no luck. Would be great to get a fix.

**Comment by laurent22** [comment]
That should be fixed in next release

**Comment by Cyb3rC3lt** [comment]
Excellent, thanks a lot
