### ISSUE TITLE
Sharing attachments from Joplin Android to external app fails

### ISSUE THREAD

**Issue by PetrVladimirov** [laurent22/joplin#4848]
There is a bunch of cross linked GitHub issues with regard to sharing, so my apologies if I create a duplicate.
This issue is about sharing from Joplin on Android to external app - it fails. 

## Environment
Joplin version: 1.7.5
Platform: Android 10
OS specifics: Samsung A41

### Stage 1
1. Open any note with attachment in Joplin
2. Image attachments are shown as pictures
2. Long press on the attachment or image
2. Click "Share"
3. Pickup external application
4. **External apps fail with app specific error** - e.g. "Error opening file" by Total Commander
5. No errors in Joplin logs

### Stage 2
... after playing for a quite a while. There was an Internet cut off and synchronization stuck (can it be an reason?). 
1. Open any note with attachment in Joplin
2. **Image attachments stopped showing as pictures**, but are shown as links
3. Long press on the attachment or image
2. Click "Share"
3. Sharing menu for external applications is not shown
4. Joplin pop-up: "an error occurred, check logs"
5. Joplin log error: "Could not handle link long press"
![e0b674447cd5466cacb0ae9750d4517e](https://user-images.githubusercontent.com/35421649/115011941-e306a780-9eb7-11eb-86dd-a0099e8c3654.jpg)

### Stage 3
1. Completely uninstall Joplin
2. Install Joplin
3. Sync notes via WebDav or Nextcloud methods
4. Environment resets to Stage 1

## Describe what you expected to happen
Joplin should be able to share attachments to an external apps

## Debug file
[Debug.txt](https://github.com/laurent22/joplin/files/6324318/Debug.txt)

**Comment by roman-r-m** [comment]
This will be fixed in the next release. The fix itself is [here](https://github.com/laurent22/joplin/pull/4718)

**Comment by PetrVladimirov** [comment]
@roman-r-m - thank you for the quick reply! When should we expect to have a new version pushed into PlayMarket?

**Comment by roman-r-m** [comment]
That's up to Laurent
