### ISSUE TITLE
[Feature Request] Search attached PDF files

### ISSUE THREAD

**Issue by bradns** [laurent22/joplin#485]
### Application

- Desktop

Based on my recent testing, it seems like it is possible to attach PDF files to notes in Joplin, but the content of those PDF files doesn't get searched when the user enters a search string. I think it would be handy for Joplin to search both the note text and the text in any attached PDF files. It would make Joplin more useful for managing academic papers and that sort of thing. Thanks for all the work you've done so far on this great app!

**Comment by xthursdayx** [comment]
I came to suggest the same thing. This is a fairly big issue for me given the fact that a large number of existing research notes I am importing from Evernote are PDFs. This feature could also be linked to the ability to natively view/preview PDFs within Joplin as per issue #877 .

**Comment by RobFisher** [comment]
I currently have lots of scanned and OCR-ed documents as PDFs in Evernote and rely on being able to search the text of them. So this feature is more important to me than preview of PDFs.

**Comment by mblennegard** [comment]
I totally agree with previous speakers.
For me, this is an essential piece for switching from Evernote, as I scan everything I receive in the mail.

The actual OCR can always be solved outside of Joplin, but searching already OCR:ed or otherwise searchable files is really needed.

I definitely see a potential complication with this though when searching on a mobile device where you might not sync all attachments. 
Can there be some kind of search index saved alongside each note perhaps?

**Comment by metbril** [comment]
Just a small comment to prevent the bot from closing this request.

**Comment by stloewen** [comment]
Don't close.

**Comment by kimini81** [comment]
I can only agree with the previous speakers. I scan almost all documents with a Fujitsu Scansnap ix500 and it would be absolutely awesome if you could search these PDFs in Joplin.

**Comment by wismie** [comment]
Hello, I'm just discovering Joplin and it really looks like the Evernote replacement I am looking for. But I use EN extensively to store pdf files and searching the PDF content is THE feature that I can find only in EN at the moment. Having it in Joplin would definitely convince me to do the switch. Thanks!

**Comment by mdscarrott** [comment]
Searching for the save thing and have the same use case. Lots of docs scanned to Evernote with OCR and need to be able to search them. This is preventing me from switching at present but I will keep an eye on progress. Otherwise looks great.

**Comment by theHausdorffMetric** [comment]
I also think within pdf search to be very important. Would an integration with something like [rga](https://github.com/phiresky/ripgrep-all) be possible. That is a command line utility based on ripgrep which also search within files.

**Comment by jfsicilia** [comment]
It would be great to add this feature. Any thoughts about integrating something like [rga](https://github.com/phiresky/ripgrep-all).

**Comment by TripHumphrey** [comment]
This would be an excellent feature.  I primarily use Evernote as a scanning and searching repository so to make the full switch from EN to Joplin would require this feature.

**Comment by mblennegard** [comment]
@laurent22 Any thoughts or ideas on how to move forward with this?

Maybe there are some obvious (but less obvious to me) reasons not to use something like pdf.js (https://github.com/mozilla/pdf.js), which already seems well established for reading and extracting text from PDF files.
Something like this combined with my previous suggestion of creating a plain text file that is saved alongside each note perhaps might work?

Granted, I have no idea how Joplin actually handles search internally, but if the contents of the PDF file is available as a plain text file, it at least seems reasonable for it to be picked up by Joplin's search, while at the same time offloading any reading/extracting of PDF files to some other time than when the user actually performs the search.

**Comment by daeh** [comment]
This is also an essential feature for me.

**Comment by Gnopps** [comment]
I'd love to see this as well.

**Comment by VETWorks** [comment]
Same here

**Comment by m2k-fr** [comment]
I add my vote. Would be a major enhancement for me as well !

**Comment by jottr** [comment]
This would be a super useful feature.
@laurent22 would there be interest that we add this feature?

If yes, should this be part of the core functionality or rather implemented as a plugin?

**Comment by GuybrushThreepwood75** [comment]
I would also like to see this feature in Joplin. 
@laurent22 Is there still the interest of implementing this feature?

**Comment by bytec77** [comment]
Same here. It is the only feature I'm missing before I switch from EN

**Comment by roman-r-m** [comment]
There's this plugin I wrote that kind of does that: https://discourse.joplinapp.org/t/search-in-resources-plugin/14443
It's a bit rough around edges and most importantly it does not have built-in OCR. This was supposed to be a project in scope of Google Summer of Code this year but it was not selected.

**Comment by laurent22** [comment]
I guess this is fixed in #8975
