### ISSUE TITLE
Fling scrolling broken in editor on Android

### ISSUE THREAD

**Issue by Philipp91** [laurent22/joplin#4850]
## Environment

Joplin version: 1.7.5
Platform: Android 10

## Steps to reproduce

1. See [here](https://developer.android.com/training/gestures/scroll#term) for a description of what fling scrolling is.
2. Open a note and fling-scroll -- it works.
3. Click the editor icon (FAB).
4. Try to fling-scroll now and it doesn't work. If it's a long note, it might take you forever to scroll to the other end.

## Describe what you expected to happen

The text field should keep scrolling when I quickly drag and lift my finger.

**Comment by Yajo** [comment]
Possibly related: when scrolling, the caret always moves to some position in the text on sight. However, you might be scrolling without any will to change the caret position.

**Comment by Yajo** [comment]
Bad bot!

![](https://media.giphy.com/media/THx4suzqEqMwDtBvGb/giphy.gif)

**Comment by Yajo** [comment]
You're right, we need activity. There you have: 🏋‍♂️

**Comment by Philipp91** [comment]
Still an issue, makes the Android app practically unusable for me.

**Comment by Yajo** [comment]
The new beta editor doesn't have that problem. 
-------- Mensaje original --------De: Philipp Keck ***@***.***> Fecha: 7/8/21  16:56  (GMT+00:00) Para: laurent22/joplin ***@***.***> Cc: Jairo Llopis ***@***.***>, Comment ***@***.***> Asunto: Re: [laurent22/joplin] Fling scrolling broken in editor on Android (#4850) 
Still an issue, makes the Android app practically unusable for me.

**Comment by Philipp91** [comment]
I can confirm that the new beta editor doesn't have this issue.

**Comment by spacezyan** [comment]
I can be sure that this issue has not been resolved. 
Hope this issue can be seen, because it really makes Joplin unusable for me.

**Comment by Daeraxa** [comment]
As the previous comment says, the beta edtior doesn't have the issue. Enable the beta editor in your options and you will have it.
