### ISSUE TITLE
"Stop" button overlaps with "bold" button during "external editing" in rich text editor( tinyMCE )

### ISSUE THREAD

**Issue by Subhra264** [laurent22/joplin#4853]
![joplin_external_editing_issue](https://user-images.githubusercontent.com/59690052/115101523-8e6c3680-9f62-11eb-9c7f-bb0522015be2.png)

## Environment

Joplin version: Joplin 1.8.1 (dev, win32)
Platform:  Windows 10
OS specifics: Windows 10 Home Single Language

## Steps to reproduce

1.  Create a note 
2.  Open the Rich Text Editor( the TinyMCE editor )
3.  Start external editing
4.  See the "stop" button

## Describe what you expected to happen
The "Stop" and "Bold" buttons should not overlap with each other, rather they should be placed one after another.

## Logfile
Logfile doesn't seem to be needed here.

**Comment by roman-r-m** [comment]
Can confirm for `Joplin 1.7.11 (prod, linux)`

**Comment by coderrsid** [comment]
Working on this. Thanks

**Comment by Subhra264** [comment]
@coderrsid Any update? coz I think I have found a good way to fix it and so might be able to help you in that case...

**Comment by coderrsid** [comment]
Sure. Please go ahead.

**Comment by Subhra264** [comment]
Thanks,
1)
https://github.com/laurent22/joplin/blob/80b16dd17e227e3f538aa221d7b6cc2d81688e72/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/styles/index.ts#L40
is changed to `width: 'auto'`

2)
https://github.com/laurent22/joplin/blob/80b16dd17e227e3f538aa221d7b6cc2d81688e72/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx#L1136 
the div is given an id `<div style={styles.leftExtraToolbarContainer} id='leftExtraToolbarContainer'>`

3)
https://github.com/laurent22/joplin/blob/80b16dd17e227e3f538aa221d7b6cc2d81688e72/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx#L511
is updated to `[editorReady, props.themeId, props.noteToolbarButtonInfos]` so that NoteBody renders updated css.

4)
https://github.com/laurent22/joplin/blob/80b16dd17e227e3f538aa221d7b6cc2d81688e72/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx#L399
is changed to `padding-left: ${document.getElementById('leftExtraToolbarContainer').offsetWidth}px;`

Would like to hear from you @coderrsid

**Comment by coderrsid** [comment]
Those changes doesn't solve for me @Subhra264, thanks anyways. Although i believe we should add the perfect width for both conditions and keep a perfect space between `tox-header` and `leftExtraToolbarContainer`. So if the state changes to true, the tox-header doesn't shift, i'd say that's bad UX. Sorry for the late reply, covid situation has taken over the internet at my place.

**Comment by Subhra264** [comment]
> Those changes doesn't solve for me @Subhra264, thanks anyways.

That's strange @coderrsid, it did work in my case...

https://user-images.githubusercontent.com/59690052/115980594-999b1400-a5ab-11eb-8d2e-691e1cac2923.mp4

> Sorry for the late reply, covid situation has taken over the internet at my place.

No worry brother, stay safe...

**Comment by coderrsid** [comment]
Ohh cool. You should go ahead and make a PR. Other things the mentors will tell you..

**Comment by Subhra264** [comment]
Okkk then,  but is it working on your machine???
