### ISSUE TITLE
Fatal error after resizing rendered Markdown region

### ISSUE THREAD

**Issue by thekenshow** [laurent22/joplin#4854]
Joplin throws fatal error after resizing rendered Markdown region.

## Environment

Joplin version:  1.8.1 
Platform: macOS
OS specifics: 10.15.7 (19H15)

## Steps to reproduce

1. Editing a note and wanted a wider view of rendered Markdown.
2. Dragged right edge of Joplin window to make it wider.
3. Dragged right edge of rendered Markdown display region to make it wider. 
4. Switched to another app.
5. Joplin threw up fatal error window.

## Describe what you expected to happen

Don't throw fatal error.

## Logfile

Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
Cannot use 'in' operator to search for 'CodeMirror-foldgutter' in null

Version info
Joplin for Desktop

Copyright © 2016-2021 Laurent Cozic
Joplin 1.8.1 (prod, darwin)

Client ID: a6059f5646c24575ada5ae37b968efb0
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: b3f950e
Stack trace
TypeError: Cannot use 'in' operator to search for 'CodeMirror-foldgutter' in null
    at /Users/kendow/.config/joplin-desktop/cache/joplin.plugin.ambrt.fold-cm/folding.js:1:2029
    at LeafChunk.iterN (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:5604:15)
    at Doc.iterN (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:5706:21)
    at Doc.iter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:6093:19)
    at n (/Users/kendow/.config/joplin-desktop/cache/joplin.plugin.ambrt.fold-cm/folding.js:1:1960)
    at signal (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:568:61)
    at DisplayUpdate.finish (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:4019:16)
    at endOperation_finish (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:3908:19)
    at endOperations (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:3807:9)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:3790:7
Component stack

    in ForwardRef(CodeMirror) (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by ResizableLayout)
    in div (created by styled.div)
    in styled.div (created by ResizableLayout)
    in div (created by Resizable)
    in Resizable (created by ResizableLayout)
    in div (created by ResizableLayout)
    in ResizableLayout (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in ThemeProvider (created by RootComponent)
    in StyleSheetManager (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider

**Comment by roman-r-m** [comment]
This seems to be coming from the text folding plugin. Paging @ambrt

**Comment by ambrt** [comment]
Which version of plugin is used?
In version 1.2.5 (latest) all searches for 'CodeMirror-foldgutter' 
are wrapped in `try/catch` block (in one of prior versions they wasn't).

But errors are logged with `console.log` - can `.log` crash Joplin on mac?

**Comment by laurent22** [comment]
On Joplin side, this issue is now handled by providing a "safe mode" option.
