### ISSUE TITLE
Can't restore a backup: a unique constraint error. 

### ISSUE THREAD

**Issue by Barafu** [laurent22/joplin#4856]
On Windows, I tried to remove a wrong driver, and ended up removing the user profile, because it is Windows. But I do have a backup of all C: drive! So, I have a copy of all user folders. I restarted Joplin and it looks like a first run, with Welcome notes and all. 

If I just copy an old .config/joplin-desktop instead of a new one, the notes do not appear. I still see only the welcome notes. I deleted it again afterwards.

If I try to use File - Import - RAW, I get this error: https://i.imgur.com/oJxBrU4.png

So, I can't restore my backup.

## Environment

Joplin version:  1.7.11
Platform:  Windows 10

## Logfile

The log shows nothing usable: https://pastebin.com/M5AUsVF3

**Comment by laurent22** [comment]
Try deleting the file 0a579....md

**Comment by Barafu** [comment]
There is no file that would start with 0a579 anywhere on my PC.

**Comment by roman-r-m** [comment]
Are there any errors in log if you delete .config/joplin-desktop and copy your saved version?

**Comment by Barafu** [comment]
Here is the log for that case: https://pastebin.com/V4aqHKfC

**Comment by roman-r-m** [comment]
Ok, this does not look like it saw your copied database
```
C:\Users\Barafu\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\Logger.js:181 00:03:24: Current database version null
```

Here's what it looks like for me when I open Joplin
```
22:20:09: Current database version 
Object
table_fields_version: 34
version: 34
__proto__: Object
```

Can you double check you copied everything correctly pls?

**Comment by Barafu** [comment]
After reading your comment, I had an idea. The database file was called database `(2021_03_01 15_58_42 UTC).sqlite`. I renamed it to `database.sqlite` and my notes where found immediately. So. my problem is almost solved - I would export and reimport everything for good measure. 

Thanks. 

Tell me if it is a sort of a bug and I can help to resolve it. (И всем привет).

**Comment by roman-r-m** [comment]
I don't know why it was called this way, should have been `database.sqlite`. Maybe it was your backup tool that renamed it?
И привет, да

**Comment by Barafu** [comment]
I guess it could be. Anyway, in the absence of a simple error message I'd never had found it myself. Closing the issue.
