### ISSUE TITLE
Error while loading shared libraries: libicui18n.so.68: cannot open shared object file

### ISSUE THREAD

**Issue by amiablechief** [laurent22/joplin#4858]
The package core/icu received an update to version 69 from version 68 and now Joplin-desktop won't load.

## Environment

Joplin version: 1.7.11
Platform: Linux x86-64
OS specifics: ArcoLinux (an ArchLinux variant)

## Steps to reproduce

1. Try to launch Joplin-desktop
2. console throws above error

## Describe what you expected to happen
Joplin desktop should launch

**Comment by naraesk** [comment]
Same here, joplin doesn't start at Arch Linux.

**Comment by tessus** [comment]
I'm sorry, but how is this Joplin's fault? If you remove a library from the system, which is needed by Jolin, how should we make Joplin work without it?

It's the same as: my car doesn't start when I remove the battery.

**Comment by naraesk** [comment]
Car metaphors are never a good idea in software engineering. :-)

The library was not removed but updated. Mainly I was wondering why Joplin was breaking while all other apps that depend on icu keep working. AFAIK icu is backward compatible so a new version should not break anything. So maybe something could improved on Joplin's side to prevent this problem in the future, maybe not. You certainly know more about it, feel free to correct me.

**Comment by tessus** [comment]
Ok, so `libicui18n.so.68` is still on your system? If an app references a file or link that does not exist anymore there's not much anyone can do. Joplin is built/packaged with electron-builder which creates an AppImage on Linux. This should bundle all the required libs. I do not know what the aur package dev did.

Either way, there's also #4859 which seams to be related.

**Comment by naraesk** [comment]
No, only `libicui18n.so.69`

**Comment by amiablechief** [comment]
From the bug linked by tessus, I installed aur/icu68 as someone on that thread suggested and it fixed the problem. Joplin-desktop works now.
