### ISSUE TITLE
Joplin-desktop don't start

### ISSUE THREAD

**Issue by 38569459** [laurent22/joplin#4859]
Today, i just update joplin to a new version and joplin-desktop just don't start.

## Environment

Joplin version: joplin 1.7.0 (prod)
Joplin-desktop version: joplin-1.7.10-1 and joplin-1.7.11-2 both have this problem
Platform: linux
OS specifics: arch linux

## Steps to reproduce

1. Type 'joplin-desktop' to terminal
2. See the hang

## Describe what you expected to happen

Seeing joplin desktop start with all my notes

## Logfile

Joplin don't start and no log is written

**Comment by 38569459** [comment]
Sometime, joplin-desktop start and look like this.
![2021-04-18-144359_1920x1080_scrot](https://user-images.githubusercontent.com/37035950/115138156-b0de7c80-a054-11eb-96cf-01991134da7b.png)

**Comment by roman-r-m** [comment]
When you get a blank window, can you open dev console (should be under the  "Help" menu) and see if there are any errors

**Comment by 38569459** [comment]
Here is what i got when open joplin with ``joplin-desktop --open-dev-tools --debug --log-level debug```

![image](https://user-images.githubusercontent.com/37035950/115147343-beabf600-a084-11eb-80ef-532a6b1dc02b.png)

**Comment by roman-r-m** [comment]
What's in the console tab?

**Comment by 38569459** [comment]
Here: 
![image](https://user-images.githubusercontent.com/37035950/115147549-a2f51f80-a085-11eb-8ccc-000dcaa62131.png)

**Comment by hubitor** [comment]
Joplin does not start (again...)

This is what I get, when I try to start it in the terminal:

```
$ joplin-desktop --open-dev-tools --debug --log-level debug
./@joplinapp-desktop: error while loading shared libraries: libicui18n.so.68: cannot open shared object file: No such file or directory
```

**Comment by CalebJohn** [comment]
@38569459 @hubitor 

How did you install Joplin?

**Comment by 38569459** [comment]
I install joplin by AUR, i also try to download the appimage file and run it but joplin still don't start

**Comment by MCWertGaming** [comment]
I have the same error here on archlinux. I have tried to install the programm with both the AUR packages (jublin-desktop wich just extracts the debian package and re-packages it as an archlinux package, juplin-appimage which is just the appimage), the appimage as standalone and the shell installer wich uses the appimage as well and all have the same error as descibed here. Also I get a slightly different error in the development console:

![image](https://user-images.githubusercontent.com/39553804/115152365-50553c80-a060-11eb-8f87-b414a8f08277.png)

**Comment by MCWertGaming** [comment]
This seems to be the line:
![image](https://user-images.githubusercontent.com/39553804/115152677-821ad300-a061-11eb-96be-ffa77a2bea38.png)
in this file
![image](https://user-images.githubusercontent.com/39553804/115152692-9f4fa180-a061-11eb-9ba0-e00670cd5585.png)

**Comment by tessus** [comment]
This is from the Joplin README:

Unsupported methods:

An Arch Linux package is available [here](https://aur.archlinux.org/packages/joplin/). To install it, use an AUR wrapper such as yay: `yay -S joplin`. Both the CLI tool (type `joplin`) and desktop app (type `joplin-desktop`) are packaged. You can also install a compiled version with the [chaotic-aur](https://wiki.archlinux.org/index.php/Unofficial_user_repositories#chaotic-aur) repository. For support, please go to the [GitHub repo](https://github.com/masterkorp/joplin-pkgbuild). If you are interested in [pre-release](https://joplinapp.org/prereleases/) you have [joplin-beta](https://aur.archlinux.org/packages/joplin-beta)

**Comment by MCWertGaming** [comment]
Well yes, but the official appimage and install script is not working either and those are supported options. Also I think that this problem is not caused by the packaging. I mean the appimage provides all dependencies itself so there shouldn't be a problem. I think that this is the same problem as dicussed here nodejs/node/issues/33741. It look likes require() is not a client side function so js has no reference because it's not provided. But as I'm not a web developer i can just note what i found.
Also is this issue just on archlinux, or also on other distibutions?

**Comment by roman-r-m** [comment]
>  Also is this issue just on archlinux, or also on other distibutions?
Ok for me on Mint

**Comment by MCWertGaming** [comment]
The version 1.8.1 (pre-release) has the following error:
![image](https://user-images.githubusercontent.com/39553804/115153323-dd01f980-a064-11eb-9180-e42b96dfb4d1.png)

**Comment by roman-r-m** [comment]
From a quick search looks like it can occur when `/tmp` is mounted as `noexec`

**Comment by hubitor** [comment]
@CalebJohn with joplin-desktop package from the AUR.

**Comment by miDeb** [comment]
What's the error printed in the console when running `joplin-desktop`? If it complains about `icu68`, try installing `icu68` from the AUR to check if it fixes the issue. (That was the case for me)

**Comment by amiablechief** [comment]
Joplin-desktop started working for me again after installing aur/icu68

**Comment by zuntik** [comment]
For me, after waiting a substantial number of minutes, aur/icu68 installation failed. The package build process had errors. :(
Any suggestions?

**Comment by amiablechief** [comment]
Can you try again and share error output? Difficult to tell without taking a look.

**Comment by 38569459** [comment]
For me, running joplin-desktop print nothing on terminal but after I install icu68 from AUR, joplin-desktop works again. This can be a workaround until the problem is fixed.

**Comment by 38569459** [comment]
After some testing, 1.7.11 install from AUR don't work, 1.6.8, 1.7.11 and 1.8.1 appimage work as expect after install icu68 from AUR.

**Comment by amiablechief** [comment]
I prefer to stay away from appimages, but that's not surprising given an appimage will bundle the executable and all its dependencies into 1 package. It never has to reach out into the installed library infrastructure of your OS.

**Comment by 38569459** [comment]
In this case, it does. Appimage only work after i install icu68, so maybe they should package icu into the appimage?

**Comment by hubitor** [comment]
@miDeb Thanks! That did the trick!

**Comment by john-cj** [comment]
I have the same issue on Windows 7. After installing the app and launching it, although the processes (as hown in Task Manager) start, GUI is not shown. If I launch the app again, it will show the GUI, but the GUI is blank.

**Comment by banan314** [comment]
It doesn't start for me on Windows as well. I installed 1.8.1, which solved the issue.

**Comment by 38569459** [comment]
I added ```contextIsolation: false,``` to line 91 in file joplin-1.8.1/packages/app-desktop/ElectronAppWrapper.ts, build the app and it works again. Need others to confirm this fix.

**Comment by michaldybczak** [comment]
It works for me on Manjaro testing from AUR:
joplin-desktop 1.7.13-3 and the previous versions work fine, no issues
icu 68 is installed

**Comment by laurent22** [comment]
This is the wrong forum to discuss this, since we don't maintain the AUR package. Please report this to the AUR package maintainer.

**Comment by 38569459** [comment]
So how about AppImage that also don't working? You do maintain the AppImage, right?

**Comment by laurent22** [comment]
The top post is about the AUR package, not the AppImage. If you have clear steps to replicate an issue with the AppImage, then feel free to open a new bug report about this.

**Comment by Vinicius-ufsc** [comment]
worked for me:

sudo apt install libfuse2 

try to open again, if it does not open,
try to open the Joplin using the Appimage from the site 
Joplin-2.8.8.AppImage

**Comment by modrozd** [comment]
For me also worked:

`sudo apt install libfuse2`

It's worth mentioning that I have a fresh Ubuntu 22.04.1 LTS install and here 
https://www.reddit.com/r/Ubuntu/comments/ukj2dq/what_is_fuse/
is mentioned that libfuse2 is needed when having a fresh install to use AppImage, which is how I installed Joplin.
