### ISSUE TITLE
Android lists don't update after sync

### ISSUE THREAD

**Issue by mzguy** [laurent22/joplin#4861]
There's a list refresh bug in Joplin for Android. I think this will reproduce it reliably:

1. Ensure Joplin Android is closed, but if necessary first configure the "All Notes" view to sort newest notes at the top, and leave that view open.
2. Use Joplin on another synced platform to create a new note.
3. Give that platform enough time to sync the new note.
4. Open Joplin Android and immediately look at the All Notes view.
5. Let sync finish. Notice the new note does not appear. Switch to another Notebook list, then back to All Notes, to see the note appear.

The above fails for any notebook, not just for the All Notes view. Basically, it appears list views don't get updated after a sync, unless they are reloaded manually by navigating around via a different Notebook or view.

What should happen: lists should refresh after a sync completes, to show updated notes.

Joplin version: 1.7.5 and at least several prior versions
Platform: Android
OS specifics: Android 10

**Comment by pjsgsy** [comment]
Still there for me, a couple of years later! Create notes in windows client. Sync. Sync OK on android client (sync reports it downloads OK the number of new notes creates on windows side). Notebooks list does not change. Does not show the new notebook or notes. Syncing appears to be working. The android client just never shows the new notes.
