### ISSUE TITLE
Installing the cli from git fails

### ISSUE THREAD

**Issue by 3v1n0** [laurent22/joplin#4866]
## Environment

Joplin version: git
Platform: Linux
OS specifics: Ubuntu 20.04

## Steps to reproduce

1. clone this repo
2. npm install && cd packages/app-cli
3. npm install -g --prefix=/tmp/INSTALL_PREFIX

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /tmp/INSTALL/lib/node_modules/joplin/main.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/tmp/INSTALL/lib/node_modules/joplin/main.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

Same happens also by just doing `npm install -g` without any install in the root project

## Logfile

https://paste.ubuntu.com/p/6Bp8Zh8k3b/

**Comment by laurent22** [comment]
where did you see this way of installing the app? It makes no sense at all.

**Comment by 3v1n0** [comment]
Well I was figuring out a way to install *only* the CLI with npm, but doesn't seem to work in any way I tried... What would be the proper way?

**Comment by 3v1n0** [comment]
And using the git code not, the one published in npm I mean.

**Comment by laurent22** [comment]
It's explained in the doc how to install it, and for now we only support this method.

**Comment by 3v1n0** [comment]
Sure but that's just for the npm version, not the git one, right?

**Comment by roman-r-m** [comment]
I think you might want to see how the CLI version is built for npm and do the same, except of course publishing to npm.

**Comment by 3v1n0** [comment]
Yeah, I also been doing the same of https://github.com/laurent22/joplin/blob/dev/packages/tools/release-cli.ts, but still at the install phase there's always the same failure on `main.js`.
