### ISSUE TITLE
In Vim mode, I want to use ctrl-c copy to Windows clipboard, how to config it

### ISSUE THREAD

**Issue by MaxSherry** [laurent22/joplin#4872]
## Environment

Joplin version: 1.7.11
Platform: winsows

In Vim mode, I want to use ctrl-c copy to Windows clipboard, how to config it.

**Comment by gagan-git-sardar** [comment]
Sir can you help me to understand the code I want to contribute

**Comment by roman-r-m** [comment]
> Sir can you help me to understand the code I want to contribute

If you want to contribute it's better to start with an issue that's been triaged - anything labelled high or medium

**Comment by gagan-git-sardar** [comment]
> > Sir can you help me to understand the code I want to contribute
> 
> If you want to contribute it's better to start with an issue that's been triaged - anything labelled high or medium

ok thankyou sir

**Comment by happyTonakai** [comment]
duplicate of #3870
