### ISSUE TITLE
a lot of things regarding searching 

### ISSUE THREAD

**Issue by jsjcjsjc** [laurent22/joplin#4874]
## Environment

Joplin version: 1.7.11
Platform: Windows
OS specifics: windows 10

first, Thank you so much for your great program, it is relly cool ;-)
I am testing search function in Joplin, i am not sure that is bugs or features

1. joplin can't find ```tail -n 3 log.txt log1.txt log2.txt```,
```log.txt log1.txt log2.txt``` is ok,but didn't highlight. details in the link below
https://s3.jpg.cm/2021/04/22/Txjk5.gif

2.joplin can't find ```search me```and ```searchme```, details in the link below
https://s3.jpg.cm/2021/04/22/Txg28.gif

3.joplin can't find ```tail -f log.txt```, details in the link below
https://s3.jpg.cm/2021/04/22/TxhVr.gif

4.the result of searching```# 查看 log.txt log1.txt log2.txt文件的前 3行内容```, there are so many highlight, details in the link below
https://s3.jpg.cm/2021/04/22/Tx0Li.gif

5.search is ok, but there is no highlight, details in the link below
https://s3.jpg.cm/2021/04/22/Tx2bk.gif

6.I think joplin should locate the result of searching, but highlight only , details in the link below
https://s3.jpg.cm/2021/04/22/TxCDy.gif

7.ctrl+F searching,I think joplin should locate the result of searching, but highlight only, details in the link below
https://s3.jpg.cm/2021/04/22/Tx34e.gif

test documents
http://disk.getpocket.in/uploads/share/test-documents.7z

**Comment by itge13** [comment]
is there a reason regex is not supported (yet)?

**Comment by vidbaz** [comment]
I'm facing many issues with the search functionality, I think is something that really needs to be on high priority I have many notes now... and searching is not accurate and productivity is impacted...

**Comment by itge13** [comment]
@vidbaz there is a plugin which may help a bit till we wait: https://discourse.joplinapp.org/t/note-overview/13962
