### ISSUE TITLE
when changing notebooks, Joplin glitches  in WYSIWYG mode

### ISSUE THREAD

**Issue by e4e6** [laurent22/joplin#4879]
## Environment

Joplin version:  Joplin 1.7.11
Platform:  Linux
OS specifics: Ubuntu 20 LTS

## Steps to reproduce

1.  i changed my default theme to dark
2.  i do use Joplin in WYSIWYG mode
3.  when i switch notebooks, the notes panel glitches , it seem it loads default white theme then switch back to dark one
4.  this happens only in WYSIWYG mode , in markdown mode i tried and everything is OK

##

![Peek 2021-04-22 18-45](https://user-images.githubusercontent.com/73366454/115747038-903c5c80-a39d-11eb-9b8e-ad52231c6801.gif)

**Comment by GrigorijST** [comment]
>     1. i changed my default theme to dark
> 
>     2. i do use Joplin in WYSIWYG mode
> 
>     3. when i switch notebooks, the notes panel glitches , it seem it loads default white theme then switch back to dark one
> 
>     4. this happens only in WYSIWYG mode , in markdown mode i tried and everything is OK

The same..

System:
  Kernel: 5.12.0-051200-generic x86_64 bits: 64 
  compiler: gcc v: 10.2.1 Desktop: Cinnamon 4.4.8 
  Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic

**Comment by tconsta** [comment]
Confirm the same on:
System: Linux 5.11.0-38-generic #42~20.04.1-Ubuntu
Joplin 2.4.12 (prod, linux)
and
System: Windows 10
Joplin 2.5.10 (prod, win32)

Switching notes is going smoothly. The only problem is switching notebooks in WYSIWYG mode.

**Comment by lull-by** [comment]
System: Linux 5.10.70-1-MANJARO
A white flash also occurs when you first enable the WYSIWYG mode.

**Comment by CalebJohn** [comment]
This was fixed in 2.6.3 (and above). Enjoy!
