### ISSUE TITLE
[Question] Relicts in the Cloud

### ISSUE THREAD

**Issue by HelmutL** [laurent22/joplin#488]
### Operating system
- Windows
- macOS
- Linux
- Android
- iOS

### Application
- Desktop
- Mobile
- Terminal

I see several files .davfs.tmp.... on the cloud storage. What are they good for? May the be deleted ?

Regards

**Comment by laurent22** [comment]
I don't know what they are and probably can be deleted. They aren't created nor used by Joplin.

By the way for user support questions like this please use the forum - https://discourse.joplin.cozic.net/
