### ISSUE TITLE
Special characters on letters (accolade and such) copies random text

### ISSUE THREAD

**Issue by TruffelNL** [laurent22/joplin#4881]
When I use special characters for letters (e.g. `´``¨` in `é` or `ë`) Joplin copies a random piece of text. It's not something I copy-pasted earlier. It's a piece of text from the same or a different note. I made a video to make it more clear what the problem is. You can see that I type `Gé` and as soon as I press the `e` after I pressed `´` the extra piece of text appears (`Een periode van 24 uur [...]`).
I restarted, reinstalled and updated Joplin. This is a vague description since I have not figured out yet what makes the problem appear, apart from using such characters. Sometimes it disappears on it's own, but it will reappear as well.

No errors are shown in the console.

## Environment

Joplin version: 1.7.11 prod, darwin
Platform: macOS
OS specifics: Big Sur 11.2.1

## Steps to reproduce
Since I'm not quite sure what needs to be done to get this behaviour and it doesn't happen all the time, I do not have 100% foolproof steps to reproduce. 

Steps which seem to make it reproducible:

1. Have Joplin open but not "fullscreen"
2. Resize Joplin by dragging the edges or double clicking to titlebar
3. Open a note
4. Enter a "special" character: `éüê`
5. Randomly inserted text appears.

## Describe what you expected to happen

I expect to be able to type text without something being added to my text.

## Logfile

[joplinlog.txt](https://github.com/laurent22/joplin/files/6365294/joplinlog.txt)

https://user-images.githubusercontent.com/16107161/115871154-76078a80-a440-11eb-9bf7-3b7803fd4e3d.mov

**Comment by laurent22** [comment]
This is such a weird bug. I've just tried a bit but it's not happening for me. So that text that's added is completely random? Can you identify if there's some pattern to it? Like maybe it comes from a note you had opened just before this one, or something like this?

**Comment by TruffelNL** [comment]
I've yet to find some kind of pattern. It doesn't have to be text from the previous note. It can be from the current note, and when I switch to a different note (or notebook) that same text from the first note is added. 
This is not confirmed and just a vague hunch but it seems to start with bigger notes and then continues to smaller notes. I believe that when it starts, it will remain the same text until it stops again. It has been persistent between restarting Joplin, but can disappear after a while and could need some time (hours) before it presents itself again. I can use all the other "special" characters without any problems (e.g. `: ; , . ! ?`), it's only the ones added to letters. 

I didn't think you would be able to solve this one quickly/easily since I'm unable to find any starting point for the debugging process: no patterns, no specific notes or notebooks where it starts, Joplin is the only program where I have this (so still could be a system thing, but it's a bit less likely), etc. This bug report is mostly to make you aware of the fact that there could be a problem (or maybe not, maybe it's my system) and for me to be able to try a bit more and add notes to this bug while I do that. Hopefully with some additional information over time, you are able to point me in a direction to further test/reproduce this.

> This is such a weird bug.

Yes it is, it's frustrating and funny at the same time.

**Comment by TruffelNL** [comment]
I stand corrected. I just had an epiphany when it seemed to be likely to occur. I have a macbook 13" with two additional 27" monitors. 
Steps which seem to make it reproducible:
- Have Joplin open on the 27" monitor
- Drag Joplin screen to 13" macbook screen
- Double click on the titlebar to resize to macbook screen
- Drag Joplin to 27" monitor
- Double click on the titlebar to resize to monitor
- Type special characters and watch the bug unfold

Tested it 4 times now and it seemed consistent behaviour. It makes sense that restarting Joplin didn't work as it will open the window on my 13" macbook and I always drag it to the 27" monitor.

**Comment by mablin7** [comment]
And if you just resize the window but not drag it between screens? I'm just
wondering whether it's connected to resizing or multiple screens.

**Comment by TruffelNL** [comment]
> And if you just resize the window but not drag it between screens? I'm just wondering whether it's connected to resizing or multiple screens.
> […](#)

Good point, just tried it and it has the same behaviour when just resizing it (by double clicking on the title bar) on the same (27") screen.

**Comment by mablin7** [comment]
And how do you input these characters? I've never used separate diacritics, I always just type `áé` directly. I guess it doesn't happen then, right? Also, does it happen if you just paste `´` into the note?

**Comment by TruffelNL** [comment]
> And how do you input these characters? I've never used separate diacritics, I always just type `áé` directly. I guess it doesn't happen then, right? Also, does it happen if you just paste `´` into the note?

I use `alt`+`e` or whatever character I would like to get. When pasting them, the bug doesn't occur. It also seems it needs to be a note with considerable length. So that the note cannot fit in the window without a scrollbar.

**Comment by mablin7** [comment]
I see. So I can't try this on neither my windows nor my linux machine. I'll try to get access to a macbook, because this seems super interesting.

**Comment by TruffelNL** [comment]
The problem is still there, so please leave the issue open.
