### ISSUE TITLE
Reopen of issue #488

### ISSUE THREAD

**Issue by HelmutL** [laurent22/joplin#489]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

Reopen of https://github.com/laurent22/joplin/issues/488

I doubt it is not coming from Joplin because
1) the direcery is assigned only to Joplin, there are no other files
2) example: the file `.davfs.tmp157249` contains:

`id: 0502e5c41b56444f9d4c28283e0c03de
note_id: 8f4d0d45258c4683931096a635a8b408
tag_id: 4b7fb5b392724c219409d062592aed0a
created_time: 
updated_time: 2018-05-04T07:26:42.303Z
user_created_time: 
user_updated_time: 
encryption_cipher_text: JED01000022019b9e99b3570e4090837ba46762ff4f8900025e{"iv":"lIHtn6He06dRkVkdSeLrJA==","v":1,"iter":1000,"ks":128,"ts":64,"mode":"ocb2","adata":"","cipher":"aes","salt":"y8NgPv/n3Rg=","ct":"P8krkcN6QNRjvAw6lTV1Trfixgb8rPHlitT2HORpG6AMZ/FmxJNTiX+hYV5KMLbK0gJadAbBLrtzsmlRT1voORHDU9tGrRMUxGN49MN85dtTJJ4uyxU/VxwhOZkE3gxLmr+7SKPz+euskC2VjVVbr4QFnOu18YinHVDVPY/F3Sk9aqkSSZUfgW8xiRaJ0FwSMulIwTItp4n1E/NIdcSYkuCEvFXe7FNBsFefFquYgWeurxIp+a87qtKHHrNit4fgpSel8GpgALv8eyit/opX9wWmpRVfSOJ01jJOdXmFKrAHw7hxJyh8AlJUHznpM3LcOJKtiomiAr2d3DCYQKcnZPWssDnmEBHiCLQxNIg6WIT08jUST2Ulsr2iMPP0Wm16B15nnUxTx2v4/lAvZbqFL/XlUeXUV5nCpBn/SMoT4flTWOVRzfD5dVN2++G6e8FoF4t2YbrIs9UJlTJYiA=="}
encryption_applied: 1
type_: 6`

and there is a file named 0502e5c41b56444f9d4c28283e0c03de.md in this directory. (seems to have the same content as the tmp file.

Maybe a relict of WEBDAV ?

**Comment by laurent22** [comment]
Yes that could be a relict of WebDAV, probably a temp file created while a file is uploaded. Maybe that one was interrupted and left behind.
