### ISSUE TITLE
Resource ID not provided error when click link with markdown pane closed

### ISSUE THREAD

**Issue by hp6393** [laurent22/joplin#4891]
A markdown link in one folder that points to a note in another folder does not work and throws a "Resource ID not provided" error when the markdown pane is closed (only the WYSIWYG editor is visible) but works fine when the markdown pane is visible.

## Environment

Joplin version: 
Platform: 
OS specifics: Windows 10 64-bit

Joplin 1.7.11 (prod, win32)

Client ID: 447e55cf95a4441ca8a84eb7ace2bb05
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f560563d8 (master)

## Steps to reproduce

1. Right-click on an existing note
2. Copy markdown link
3. Move to a new notebook
4. Create a new note
5. Paste the link into the markdown editor -- e.g., [Regression](:/99675cd0851a41af807c00390a27d30f)
6. At this point the markdown link appears in the Markdown editor and a clickable link labeled Regression appears in the WYSIWYG editor with the Joplin icon to the left of the link.

![image](https://user-images.githubusercontent.com/55008228/116178447-97d46c00-a6e3-11eb-92b8-aaddc4bd6133.png)

7. As long as the editor is toggled so that the markdown editor is in the left pane and the WYSIWYG editor is in the right pane, clicking on the link in the WYSIWYG pane behaves normally--clicking on the link takes you to the Joplin note. But...
8. Toggle the editor off (so that only the WYSIWYG editor is visible and the markdown editor is hidden.
9. Click the link in the WYSIWYG editor and nothing happens.
10. Right click and choose Open and an error window appears "Resource ID not provided"

![image](https://user-images.githubusercontent.com/55008228/116178382-783d4380-a6e3-11eb-900d-2c6ebf92b9f0.png)
 

## Describe what you expected to happen

I expect that clicking on the WYSIWYG link would take me to the Joplin note regardless of whether the markdown editor pane is open or closed.

**Comment by JackGruber** [comment]
>As long as the editor is toggled so that the markdown editor is in the left pane and the WYSIWYG editor is in the right pane

To clarify this is the `Split view` of the markdown editor and the viewer, not the WYSIWYG  editor!

I can reproduce the error with notelinks in the WYSIWYG editor in Joplin `1.8.2`.

- Splitview: `Works`
- Viewer: `Works`
- WYSIWYG  ctrl + click on link `Works`
- WYSIWYG right click on linkand  choose open: `Resource ID not provided`

**Comment by hp6393** [comment]
Thanks. I wasn't sure of the terminology.
________________________________

**Comment by nishantwrp** [comment]
I'm working on this issue.

**Comment by nishantwrp** [comment]
Ah okay no problem. I'll pick another issue to work on.
