### ISSUE TITLE
Unable to install terminal version MacOS 10.15.7

### ISSUE THREAD

**Issue by RCPhysics** [laurent22/joplin#4893]
## Environment

Joplin version: 
Platform: MacOS
OS specifics: 10.15.7

## Steps to reproduce

Run command NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin
sudo ln -s ~/.joplin-bin/bin/joplin /usr/bin/joplin

## Logfile
[2021-04-27T07_37_58_918Z-debug.log](https://github.com/laurent22/joplin/files/6382805/2021-04-27T07_37_58_918Z-debug.log)

**Comment by RCPhysics** [comment]
If this isn't a bug, is it possible to get some advice on troubleshooting?

**Comment by roman-r-m** [comment]
There's this in your log, sounds like a possible cause:
```
2940 error gyp: No Xcode or CLT version detected!
```

**Comment by RCPhysics** [comment]
One might thing that, but before posting this I checked and do, in fact, have CLT installed and at the latest version.

**Comment by roman-r-m** [comment]
Ok, I'm not familiar with MacOS but maybe the build tool can't see CLT for some reason even though it's there?

**Comment by amykhoover** [comment]
I was having a similar problem when trying to run npm install from the root of the joplin directory cloned from github. Not entirely sure why at this point, but removing and then installing CLT fixed my problem. Perhaps you could give it a go despite knowing you have it installed? I did as well.

sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install

**Comment by RCPhysics** [comment]
> I was having a similar problem when trying to run npm install from the root of the joplin directory cloned from github. Not entirely sure why at this point, but removing and then installing CLT fixed my problem. Perhaps you could give it a go despite knowing you have it installed? I did as well.
> 
> sudo rm -rf /Library/Developer/CommandLineTools
> xcode-select --install

This worked to fix the problem.  No idea why.  Everything else seemed to see CLT.  Thanks for the advice though.

**Comment by roman-r-m** [comment]
I am closing the issue now since you've managed to fix it.
