### ISSUE TITLE
react-native-alarm-notification - android build

### ISSUE THREAD

**Issue by rlarge** [laurent22/joplin#4897]
A problem occurred evaluating project ':react-native-alarm-notification'.
> Plugin with id 'maven' not found.

A problem occurred configuring project ':react-native-alarm-notification'.
> compileSdkVersion is not specified.

Just trying to build android? I've tried some of the fixes online for other react-native plugins without fixing the problem. Maybe a problem with updated build tools, its a fresh install following the instructions.

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

**Comment by roman-r-m** [comment]
What commands are you running?

**Comment by rlarge** [comment]
huh, ./gradlew installDebug
according to the docs

**Comment by rlarge** [comment]
So i just realized that I'm using the development version so I'm gonna close this issue. I'll post more information on the development forums. Sorry people
