### ISSUE TITLE
Sync on close

### ISSUE THREAD

**Issue by Yajo** [laurent22/joplin#4899]
## Environment

Joplin version: 1.7.11 
Platform: Linux + Android
OS specifics: Fedora 33 Silverblue

## Steps to reproduce

1. Open desktop app.
2. Edit a note.
3. Close.
4. Open mobile app.
5. Sync
6. The note is still old.

## Describe what you expected to happen

I expect Joplin (specifically the desktop app here) to sync before exiting if there were any local changes. Or, at least, to warn me somehow about the situation, so I can click on "Sync before exit" or something like that.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/6391462/log.txt)

**Comment by roman-r-m** [comment]
Sound like a duplciate of https://github.com/laurent22/joplin/issues/4861?

**Comment by Yajo** [comment]
Not really. That one says:

> Give that platform enough time to sync the new note.

This bug is about Joplin not syncing when we don't give it enough time.

**Comment by roman-r-m** [comment]
How can it sync if you don't give it enough time?
There's no background sync atm so Joplin has be running to sync.

**Comment by Yajo** [comment]
Then, just a confirm dialog would be enough to help. Something like:

> Joplin didn't finish syncing. Are you sure you want to close?
> <kbd>Close Joplin</kbd> --- <kbd>Go back and sync</kbd>

**Comment by mzguy** [comment]
That's not feasible / reliable. Just going to the home screen via system may be enough for Joplin to get closed (eventually). Can't have Joplin interrupt that process with a pop-up dialog.

What I think might be useful, is a small status window (bottom-left?) that's always visible in Joplin, and shows one of:

- Synced
- Unsynced changes
- Syncing x%

**Comment by Yajo** [comment]
> a small status window (bottom-left?) that's always visible in Joplin

In mobile that might probably occupy too much space. How about a sync button with a small counter of unsynced notes?

Also, another option for mobile would be to use a notification to sync, so when Joplin closes it could spawn that background job?

**Comment by Yajo** [comment]
🙋‍♂️

**Comment by Yajo** [comment]
![](https://media.giphy.com/media/28GHfhGFWpFgsQB4wR/giphy.gif)

**Comment by Yajo** [comment]
🍺
