### ISSUE TITLE
Some menus render blank and cause a freeze

### ISSUE THREAD

**Issue by headkaze** [laurent22/joplin#4901]
## Environment

Joplin version: Joplin for Desktop 1.7.11
Platform: Linux
OS specifics: Ubuntu 21.04 / 5.11.0-custom

## Steps to reproduce

1. Run Joplin
2. Click on a menu such as Go, Note or Tools (or right-click to show the context menu)

## Describe what you expected to happen

Some menus such as those listed above render as a blank window and will freeze Joplin for about 10 seconds (sometimes showing a "Joplin is not responding" message). The menus don't have any text and cannot be interacted with by the mouse.

## Logfile

I put Joplin in debug mode and nothing is output to the console indicating an error.

**Comment by laurent22** [comment]
Could you post a screenshot of it? Also do you use any plugin?

**Comment by headkaze** [comment]
When I create a screenshot the menus don't show up in them. I don't use any plugins.

After playing around trying to get a screenshot suddenly all the menus started working correctly again. I then restarted Joplin but again get the same problem. A reboot does not resolve the issue either.

**Comment by laurent22** [comment]
I suspect it's an issue with Electron or the window manage, probably not something we can fix.

**Comment by roman-r-m** [comment]
> When I create a screenshot the menus don't show up in them.

Next time this happens just take a picture with your phone. 

I suspect I am having similar issues on Mint, and it does seem to be a problem either with Electron or the window manager. Or both.

**Comment by headkaze** [comment]
> I suspect I am having similar issues on Mint, and it does seem to be a problem either with Electron or the window manager. Or both.
Which window manager are you using? Ubuntu 21.04 uses Wayland by default.

**Comment by roman-r-m** [comment]
Metacity

**Comment by headkaze** [comment]
I get the same issue with X11 and Wayland so my guess is it's Electron and not the desktop manager

**Comment by headkaze** [comment]
> I suspect it's an issue with Electron or the window manager, probably not something we can fix.

I tried the latest dev branch (Joplin 1.8.3) and the menus work fine. Do you have an eta on this release?

**Comment by headkaze** [comment]
@laurent22 FYI This bug appears to occur in another application I have installed as a snap package that uses Electron.
