### ISSUE TITLE
Exporting note to PDF produces a blank PDF

### ISSUE THREAD

**Issue by meldarionqeusse** [laurent22/joplin#4904]
## Environment

Joplin version: portable 1.7.11
Platform: Windows 10

## Steps to reproduce

1. Right click on note in side bar, export> PDF-PDFfile.
2. Open the created PDF file
3. PDF is generated by it is blank.

## Describe what you expected to happen

Expecting the PDF to contain the information written in the note.

**Comment by JackGruber** [comment]
Do this happens with every note?
Do you use coustem css?

**Comment by meldarionqeusse** [comment]
Ok I remove joplinprofile folder and start a fresh and it worked. I imported my notes and it worked. I installed all the plugins and it stopped working. I installed plugins one by one and narrowed it down to the spoiler card plugin. I will refer this issue to the related plugin
