### ISSUE TITLE
WYSIWYG should use monospace font while editing fenced code block

### ISSUE THREAD

**Issue by Yajo** [laurent22/joplin#4905]
## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Fedora 33 Silverblue, Flathub install

## Steps to reproduce

1. Open a note in markdown editor.
2. Add a fenced code block.
3. Switch to WYSIWYG editor.
4. Double-click that code block.
5. The font isn't monospace.

## Describe what you expected to happen

Editing a code block should happen with monospace font.

## Logfile

I think it's not relevant, since there's no error. Just a UX problem.

**Comment by dz2106** [comment]
Going to take a look at this issue.

**Comment by dz2106** [comment]
Unable to recreate issue on Windows 10

**Comment by Yajo** [comment]
Here I can't avoid reproducing it 🤷🏼‍♂️ 


https://user-images.githubusercontent.com/973709/120819076-1c1fd780-c54b-11eb-956f-8c93fab56c43.mp4
