### ISSUE TITLE
Alarms do not work on iOS

### ISSUE THREAD

**Issue by loganrv** [laurent22/joplin#4906]
## Environment

Joplin version: 10.7.2
Platform: iOS
OS specifics: 14.5

## Steps to reproduce

1. Make to-do
2. Set alarm for any time
3. Wait for alarm time

## Describe what you expected to happen

An audible alert and popup/notification on screen. Nothing happens instead.

**Comment by laurent22** [comment]
log?

**Comment by loganrv** [comment]
![008B9302-0FF3-450A-A376-868AEBF8B439](https://user-images.githubusercontent.com/78905069/116574117-b4ec8300-a90d-11eb-95e8-7c7281d5e65a.png)
![D7BFA12E-A70A-4CD5-B998-BCDCCD7FD705](https://user-images.githubusercontent.com/78905069/116574129-b7e77380-a90d-11eb-9c78-7f68bdf00536.png)

**Comment by loganrv** [comment]
I attached the log, I made an alarm to go off at 16:55 when I opened the app at 16:52. Thanks!

**Comment by loganrv** [comment]
Is there any more information that is needed?
