### ISSUE TITLE
Change alarm sound

### ISSUE THREAD

**Issue by Yajo** [laurent22/joplin#4908]
## Environment

Joplin version: 1.7.5
Platform: Android 
OS specifics: 10

## Steps to reproduce

1. Try to change or disable alarm sound

## Describe what you expected to happen

There should be an option for this.

**Comment by roman-r-m** [comment]
Doesn't it use the system alarm sound?

**Comment by Yajo** [comment]
Nope, it's a different sound.

Today I noticed it gets played through the "multimedia" sound channel (not the notifications one).

FTR I've had sound notifications turned off on this device since forever, but Joplin ignored that setting and sounded loud and clear. But yes, I double-checked, and it wasn't the default one that would have been in case it wasn't turned off.

**Comment by roman-r-m** [comment]
Found the issue in the library we're using, will fix it together with the other alarm-related bug.

**Comment by Yajo** [comment]
If it plays the notification sound chosen at system level, probably the lack of customization will not be such a big problem.
