### ISSUE TITLE
Tap on notification doesn't open the note

### ISSUE THREAD

**Issue by Yajo** [laurent22/joplin#4912]
## Environment

Joplin version: 1.7.5
Platform: Android
OS specifics: 10

## Steps to reproduce

1. Set an alarm.
2. Wait for it to appear.
3. Tap on the notification.

## Describe what you expected to happen

I expect Joplin to open directly the note that triggered the alarm. Instead, it just opens Joplin in the "all notes" section. The notification already disappeared, so I don't know which one it was. BTW, the sound keeps ringing (but that's #4086 probably)

**Comment by roman-r-m** [comment]
I can reproduce this, will take a look

**Comment by CaptainPackers** [comment]
I have this problem too. I have to kill Joplin to stop the alarm.

Joplin: 1.7.5
Android 11
Samsung Galaxy S21
