### ISSUE TITLE
Spellcheck correction in title, with markdown spellcheck

### ISSUE THREAD

**Issue by szuecs-andras** [laurent22/joplin#4913]
When using spellcheck on the title, with the beta markdown version of spellcheck, instead of changing the title, it pastes the correctly spelled word before the text under the title
## Environment
Joplin 1.7.11 (prod, win32)

Client ID: 97348e3d52dd4268bbfa57b1059d853c
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f560563d8 (master)

Edition	Windows 10 Home
Version	20H2

## Steps to reproduce

1. Incorectly spelled word in title
2. right click for spellcheck options
3. click on correct spelling

## Describe what you expected to happen

word in title corrected normally

**Comment by CalebJohn** [comment]
@szuecs-andras 

Can you test this in [v1.8.2](https://github.com/laurent22/joplin/releases/tag/v1.8.2)? I'm pretty sure this has already been fixed but I can't find anything to back that up. (I can duplicate this issue on v1.7.11 but not on v1.8.2).

**Comment by szuecs-andras** [comment]
oh sorry, i thought i was on the latest version, because the "check for updates" in the help tab said so. I will try on the newest version

**Comment by CalebJohn** [comment]
Oh no worries, v1.8.2 is in pre-release so you need to manually opt in to get those updates. I should have been more clear.
