### ISSUE TITLE
Jolpin 1.8.3 doesn't create it's own copy of images while pasting with some text

### ISSUE THREAD

**Issue by hxchtiewei** [laurent22/joplin#4916]
Environment
Joplin version: 1.8.3
Platform: windows 10

Steps to reproduce
1、Create a docx with microsoft word.
2、Write some text. Insert an image below to it.
3、Select all and Copy (Ctrl A + Ctrl C)
4、Paste it in Joplin Rich Text(WYSIWYG) editor. (You can notice the image "src= file:///C:/Users/xxx/AppData/Local/Temp/...")
5、Copy the image only.
6、Paste it in Joplin Rich Text(WYSIWYG) editor. (It's ok)

**Comment by hxchtiewei** [comment]
I'm sorry to say, Jolpin 1.8.4  the problem is still...

![test1](https://user-images.githubusercontent.com/48231900/117621183-e7b33880-b1a3-11eb-906b-249cd9042f3d.gif)

**Comment by laurent22** [comment]
That should be fixed in this release: https://github.com/laurent22/joplin/releases/tag/v1.8.5
