### ISSUE TITLE
Joplin Fails to Authenticate Dropbox Synchronization

### ISSUE THREAD

**Issue by aarograh** [laurent22/joplin#4917]
Joplin fails to use the authentication code provided by Dropbox:

![image](https://user-images.githubusercontent.com/9356636/117046690-fa7ac880-acde-11eb-8f8c-318437643e5d.png)

## Environment

Joplin version: 1.7.11, revision f560563d8
Platform:  Windows
OS specifics: Windows 10 Enterprise build 1909

## Steps to reproduce

1. Install Joplin Account
2. Set synchronization to Dropbox
3. Attempt to synchronise
4. Login to Dropbox to obtain code
5. Enter in Joplin

## Describe what you expected to happen

I expected the code to be accepted.  Instead, it complains about a self-signed certificate.  I have 2 different Dropbox accounts (personal & work) that each provided a unique code, but both failed in Joplin.

Admittedly this might be an issue on the Dropbox side and not the Joplin side, but I figured I'd start with Joplin since it's the part of this that's new to me and I haven't had issues with Dropbox before.

## Logfile

The log.txt that was automatically produce: 
[log.txt](https://github.com/laurent22/joplin/files/6423090/log.txt)

The output from the Console:
[console.log](https://github.com/laurent22/joplin/files/6423091/console.log)

I don't see any particular warnings or errors in the Console that seem clearly related to this issue.

**Comment by roman-r-m** [comment]
Can you try from a different PC on a different network? It sounds like you might be on some corporate network where you IT have messed with certificates. Either this or maybe you have some kind of malware.

Joplin recently got support for self-signed certificates but only for WebDAV/NextCloud as I've never thought it'd be needed for Dropbox.

**Comment by aarograh** [comment]
> Can you try from a different PC on a different network? It sounds like you might be on some corporate network where you IT have messed with certificates. Either this or maybe you have some kind of malware.
> 
> Joplin recently got support for self-signed certificates but only for WebDAV/NextCloud as I've never thought it'd be needed for Dropbox.

@roman-r-m You're correct that this is a corporate network & computer.  I just tried it using the Joplin app on my phone.  The sync worked successfully in the phone app (which does not actually have any of my notes), but I'm continuing to get failures on the desktop App even if I use the same code that worked on the Android app.  Any ideas on how to get them both to work?

**Comment by roman-r-m** [comment]
Can you use the Dropbox app on your PC? I think right now the only way you could get it to work is get the app to sync your notes to a local folder and use file system sync pointing Joplin to that folder.

**Comment by aarograh** [comment]
Oh, great suggestion.  I should have thought of that.  I pointed it to the same Dropbox folder on my laptop that my phone had synced it to and that seems to have worked.  All my notes now appear on my phone too, and the desktop app seems happy.  Thanks for the help!

**Comment by roman-r-m** [comment]
You're welcome.

Since this set up isn't quite standard I'd suggest you set up periodic backups. Check the forum, there's a plugin for this.

**Comment by roman-r-m** [comment]
Since this is now solved, I am going to close it.
