### ISSUE TITLE
Delete local data and re-download from sync target - hangs in loop

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#4919]
Joplin starts every time empty and need to resync. 

## Environment

Joplin 1.8.3 (dev, win32)

Client ID: 5097634875c14f03a591cb4aae8f7673
Sync Version: 2
Profile Version: 35
Keychain Supported: Yes

Revision: 26a91416c

## Steps to reproduce

1. Setup sync target
2. Let Joplin sync
3. Use `Delete local data and re-download from sync target`
4. After the app restart all notes are gone (what is right)
5. Let Joplin sync
6. Close Joplin
7. Start Joplin
8. All notes are gone, you ned to resync again

You can go from step 8 to 6 again and the same happens.

## Describe what you expected to happen

That the delete local data will stop after the first resync.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/6426702/log.txt)

**Comment by JackGruber** [comment]
The same happens for `Re-upload local data to sync target`

**Comment by laurent22** [comment]
Oh that's really bad, thanks for reporting this. Normally the flag to delete should be unset when the app starts but looks like it's not happening.
