### ISSUE TITLE
Richtext text colour and background wrong colours in dark themes

### ISSUE THREAD

**Issue by mlovizio** [laurent22/joplin#4920]
There is an issue with the colours of the background and the text in the rich text view and editor, pictures are attached below
## Environment

Joplin version: 1.8.2 (prod, win32)

Client ID: c04440e46cd54b9da77c8926a13ebe06
Sync Version: 2
Profile Version: 34
Keychain Supported: No
Revision: 2531e8945
Platform: Windows 10 Pro

## Steps to reproduce

1. Start Jopling portable
2. Tools/Options/Appearance/Theme->Dark
3. Write some text

## Text colour and background colour mismatch
![Joplin_e6CPjHMhk2](https://user-images.githubusercontent.com/74993598/117134954-b211e800-ad7c-11eb-8394-b0ef6db494cc.png)
* * *
This doesn't happen in the non-portable version, in that case the text and the background colours work as expected.

![image](https://user-images.githubusercontent.com/74993598/117136122-5183aa80-ad7e-11eb-9eaf-76dbddfb7d57.png)

In adition, if I switch to the rich text editor, the background colour doesn't follow the app theme, is just dark text over white background.

## Logfile

[log.log](https://github.com/laurent22/joplin/files/6426787/-1620214892283.log)

**Comment by laurent22** [comment]
Looks like it's not styled at all on the portable version. Does the app have write access to the device?

**Comment by dz2106** [comment]
I was unable to recreate this issue using the portable windows 10 version of Joplin.

**Comment by dz2106** [comment]
![image](https://user-images.githubusercontent.com/36925633/118735617-cfc85e00-b80e-11eb-9ff8-6723a3031baf.png)

**Comment by dz2106** [comment]
If no one can recreate the issue, it is best to close it.
