### ISSUE TITLE
How do I regularly back up my notes to a local disk or other cloud disk?

### ISSUE THREAD

**Issue by yzhengwei** [laurent22/joplin#4928]
## Environment

Joplin version: 1.7.11
Platform: windows 10

## Describe what you expected to happen
I set OneDrive as cloud disk for my notes, but I found that every time I started Joplin, I would synchronize it first. So if one day my OneDrive files were deleted, would it cause the local Joplin notes to be deleted after the synchronization? How to deal with this situation?Does Joplin support regular backup of notes to other specified directories or other cloud disks on your computer?

**Comment by roman-r-m** [comment]
Search on the forum for backup plugin

**Comment by CalebJohn** [comment]
https://discourse.joplinapp.org/t/backup-plugin/13964

**Comment by yzhengwei** [comment]
Thanks !
