### ISSUE TITLE
Onedrive sync not available in mobile

### ISSUE THREAD

**Issue by ShobanChiddarth** [laurent22/joplin#4935]
## Environment

Joplin version: 1.7.5
Platform: Android
OS specifics: Version 8

## Steps to reproduce

1. Set OneDrive as sync target in settings
2. Save it
3. And synchronise from sidebar

## Describe what you expected to happen
I need Joplin to start syncing with OneDrive but it doesn't do anything when clicked on that.

## Logfile
![Screenshot_20210508-212619](https://user-images.githubusercontent.com/68191453/117545590-0f8b8a80-b044-11eb-8af2-0a06e21bf68c.png)

## Screenshot
![Screenshot_20210508-212442](https://user-images.githubusercontent.com/68191453/117545541-d5ba8400-b043-11eb-9b47-9a7cdf81fd9e.png)

## Additional Resource
[Joplin Forum discussion](https://discourse.joplinapp.org/t/unable-to-setup-sync-with-one-drive-in-mobile/13609?u=shobanchiddarth)

**Comment by ShobanChiddarth** [comment]
![Screenshot_20210508-215710](https://user-images.githubusercontent.com/68191453/117546518-698e4f00-b048-11eb-8f65-ba99495ef698.png)
![Screenshot_20210508-215713](https://user-images.githubusercontent.com/68191453/117546520-6bf0a900-b048-11eb-8b2e-c8bb9511ca23.png)
It's working. I am able to use onedrive on a browser

**Comment by ShobanChiddarth** [comment]
![Screenshot_20210508-220137](https://user-images.githubusercontent.com/68191453/117546634-fdf8b180-b048-11eb-8668-ca754bc5026f.png)
Even onedrive android app is working

**Comment by CalebJohn** [comment]
This is strange, from my understanding Joplin opens the OneDrive website when sync is initiated.
Can you try uninstalling the application and re-installing?

**Comment by ShobanChiddarth** [comment]
I reinstalled and it's working now, thanks
