### ISSUE TITLE
Toggle External Editing - Interface glitch close button

### ISSUE THREAD

**Issue by armaccloud** [laurent22/joplin#4936]
After clicking the button 'Toggle external editing', the button extends into the Bold (B) button. In other words, the interface doesn't resize with the extension of the button.

## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Pop!_OS 20.10

## Steps to reproduce

1. Open a note
2. Click the button 'Toggle external editing'
3. Verify the button is shown on top of the **B** button

## Screenshots
**Not Clicked**
![image](https://user-images.githubusercontent.com/9272078/117546798-95034080-b02c-11eb-8fbb-0ee6bc4e3573.png)
**Clicked**
![image](https://user-images.githubusercontent.com/9272078/117546815-a6e4e380-b02c-11eb-8df1-2186a3fe82d6.png)

**Comment by JackGruber** [comment]
Dupplicate of #4853

**Comment by armaccloud** [comment]
Ah, cheers @JackGruber Closing this one.
