### ISSUE TITLE
Joplin Server does not support ARM, causes exec format error

### ISSUE THREAD

**Issue by water-sucks** [laurent22/joplin#4937]
It seems that the Joplin Server Docker image does not have support for ARM-based CPUs. I pulled the image on a Raspberry Pi 3B+ and the Docker logs report that there is an exec format error and keeps on restarting the container.

## Environment

Joplin version: server (latest)
Platform: Linux aarch64 Docker (Raspberry Pi 3B+)
OS specifics: Void Linux 64-bit ARM (aarch64 Raspberry Pi 3 rootfs), zsh shell

## Steps to reproduce

1. Write docker-compose file exactly as-is in the sample
2. Run command `sudo docker-compose up -d` 
3. Check logs using `sudo docker logs <container id> &> joplin-logs.log`

## Describe what you expected to happen

I expected the Joplin server to be up and running without any issues.

## Logfile

(using Docker logs, as there are no specific procedures listed in link for how to get logs for server)

[docker-logs.log](https://github.com/laurent22/joplin/files/6446426/docker-logs.log)

**Comment by dpoulton-github** [comment]
Your report appears to answer your own question,

>It seems that the Joplin Server Docker image does not have support for ARM-based CPUs.

However, *florider89* (*florider* on the forum) **has** created an ARM64 compatible docker image.

https://hub.docker.com/r/florider89/joplin-server

I have tried it and it works fine on RasPiOS x64.

I am just another user so I do not know if Laurent ever intends to release a server version that supports ARM.

**Comment by morning-sucks** [comment]
Ah, I did not see this. Great to know that there is such an image available. My apologies.

**Comment by TheGreatestJannet** [comment]
It would be nice to have an official arm64 image though!

**Comment by dpoulton-github** [comment]
> It would be nice to have an official arm64 image though!

Yes it would!

**Comment by TheGreatestJannet** [comment]
This issue isn’t fixed.

**Comment by dpoulton-github** [comment]
> This issue isn’t fixed.

I guess that's because it's not a bug. Joplin server is not built to run on ARM, so ARM support is a feature request. This feature request **is** being brought up on the forum and, it seems, @laurent22 is happy for someone to work on it.

https://discourse.joplinapp.org/t/major-breaking-change-in-coming-joplin-server-2-0/17254/93

**Comment by TheGreatestJannet** [comment]
This is true. Is there a feature request tag to add or are they meant to be on the forum?

**Comment by dpoulton-github** [comment]
> Is there a feature request tag to add or are they meant to be on the forum?

Feature requests currently get discussed on the forum with GitHub used for bug issues. They are mainly in the "Features" category, however they can appear in others such as "Beta Testing". I believe that this is because more users engage on the forum than here, so there is a wider set of opinions.

IIRC, if you actually try to raise a feature request on GitHub you get referred to the forum.

**Comment by mu88** [comment]
> 
> However, _florider89_ (_florider_ on the forum) **has** created an ARM64 compatible docker image.
> 
> https://hub.docker.com/r/florider89/joplin-server
> 
> I have tried it and it works fine on RasPiOS x64.

Which Raspberry Pi did you use? I was not able to pull the Docker image on my Raspberry Pi 4 ([see here](https://github.com/flosoft/docker-joplin-server/issues/7)).

**Comment by dpoulton-github** [comment]
I used a Pi4 but the important bit is that you use the RasPiOS Beta **64-Bit** image. The default / standard RasPiOS is only 32-bit.

https://downloads.raspberrypi.org/raspios_lite_arm64/images/

**Comment by abhilesh** [comment]
I have a 64 bit image, the output for my ```uname -a``` is 
```Linux raspberrypi 5.10.44-v8+ #1429 SMP PREEMPT Fri Jun 25 10:03:37 BST 2021 aarch64 GNU/Linux```
and yet I run into the ```no matching manifest for linux/arm/v7 in the manifest list entries``` while pulling ```florider89/joplin-server:latest```.

 I am confused as to why docker doesn't pull the right image

**Comment by dpoulton-github** [comment]
@abhilesh 

I can't replicate this. My Pi4 with RaspiOS x64 Lite pulls the image just fine.

Maybe you should join @mu88 on the GitHub issue they raised with the ARM image's dev?

https://github.com/flosoft/docker-joplin-server/issues/7

**Comment by abhilesh** [comment]
I was able to resolve this by making two modifications in my docker-compose file.

The first one was to use the ```master``` tag for the image, hence pulling ```florider89/joplin-server:master```.
The second was to explicitly declare the platform by adding ```platform: linux/arm64``` under app:

Hope this helps!

**Comment by dpoulton-github** [comment]
Did you see [florider's comments](https://hub.docker.com/r/florider89/joplin-server) about the tags / master tag?

> master[-alpine]: Images built testing CI / Image changes. Should not be used on systems you want to have a working instance of Joplin Server on. Currently V2 Beta - see notice at the top!

**Comment by abhilesh** [comment]
I missed that comment, thanks for bringing it to my attention. I am just starting out with joplin, so I don't mind being on the experimental build right now.

However, I can confirm all tags work by including the ```platform: linux/arm64``` in docker-compose
