### ISSUE TITLE
Add shortcut for underlining text 

### ISSUE THREAD

**Issue by aashimawadhwa** [laurent22/joplin#4940]
There exist  shortcut buttons for bold text , italic text but  there is no such shortcut and button for underlining text.

- add button for underling text
- add underling text feature
![Screenshot from 2021-05-09 00-37-52](https://user-images.githubusercontent.com/73706697/117553770-0e248700-b071-11eb-95c4-fa203f8f0718.png)

**Comment by lkiThakur** [comment]
Hi @aashimawadhwa ;thanks for your intrest in improving joplin. 
Joplin uses markdown format to store notes and  I got following info when I searched `underline markdown` on search engine.
> Text can't be underlined in Markdown. Although this is possible using the '<u>' tags in HTML, it's usually inadvisable to do so. 
> That's because underlined text is used for hyperlinks online and it's best to avoid confusing the two uses.

If you belive underline feature will be useful to significant number of joplin note takers consider discussing it on [Joplin Forum](https://discourse.joplinapp.org/ ) . I will be happy to **implement it as a plugin**.

**Comment by dpoulton-github** [comment]
There's a plugin now available that adds this.

https://discourse.joplinapp.org/t/menu-items-shortcuts-toolbar-icons/17372

**Comment by HackerInfo2024** [comment]
Yea... I wish this was available as well. Currently, I can tell my hyperlinks because I have them color coordinated to "cyan". But would be nice to be able to not only bold text, but to underline as well.

**Comment by dpoulton-github** [comment]
@skor21 

> Yea... I wish this was available as well.

If you use the *[Menu items, Shortcuts, Toolbar icons](https://github.com/tessus/joplin-plugin-menu-shortcut-toolbar#readme)* plugin (as mentioned previously) you will get **Markdown Editor** toolbar commands for:

![image](https://user-images.githubusercontent.com/60117449/201228442-ac4c3b36-1b08-48af-9f59-b26748d34485.png)

1. Highlight
2. Strike-through
3. Underline
4. Superscript
5. Subscript

Check the below options are switched on in **Tools** > **Options** > **Markdown**:

- Enable ==mark== syntax (wysiwyg: yes)
- Enable \~sub\~ syntax (wysiwyg: yes)
- Enable ^sup^ syntax (wysiwyg: yes)
- Enable ++insert++ syntax (wysiwyg: yes)

**Comment by HackerInfo2024** [comment]
I’m an idiot! Not sure how I missed this. Thanks! 😀👍
