### ISSUE TITLE
Code block cannot be copied

### ISSUE THREAD

**Issue by yzhengwei** [laurent22/joplin#4944]
## Environment

Joplin version: 1.7.11
Platform: windows 10

## Describe what you expected to happen
I want to copy part of the Markdown code block, but I find that I can only copy the whole block, and the copy becomes a single line of text, how to deal with this?In addition, a hyperlink inserted in the note does not automatically redirect to an external browser when clicked？

**Comment by dz2106** [comment]
Ok so I tried the external browser not opening when a link is clicked. I was unable to recreate this issue as my Windows install opened up my default browser.

**Comment by dz2106** [comment]
![image](https://user-images.githubusercontent.com/36925633/118913609-c8c94a80-b8f7-11eb-99b4-93f269cf5dde.png)
However, I was able to recreate your issue with the copy and pasting of code blocks. Going to take a look.

**Comment by dz2106** [comment]
https://github.com/laurent22/joplin/pull/4852#issuecomment-842638064

Looks like the new line error is related to this. Something broke with a recent pull.
