### ISSUE TITLE
iOS application cannot be released due to ShareExtension error

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#4945]
When trying to build the app from [release-1.8](https://github.com/laurent22/joplin/tree/release-1.8), the following errors show up:

> Failed to register bundle identifier: The app identifier "net.cozic.joplin.ShareExtension" cannot be registered to your development team because it is not available. Change your bundle identifier to a unique string to try again.

> No profiles for 'net.cozic.joplin.ShareExtension' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'net.cozic.joplin.ShareExtension'.

@sirnacnud, do you know what might be the issue by any chance? (I'm opening a bug report here as it's easier to track than a closed pull request)

**Comment by laurent22** [comment]
I've just tried again and it still doesn't work but with different errors:

> An Application Group with Identifier 'group.net.cozic.joplin' is not available. Please enter a different string.

> Provisioning profile "iOS Team Provisioning Profile: net.cozic.joplin" doesn't support the App Groups capability.

> Provisioning profile "iOS Team Provisioning Profile: net.cozic.joplin" doesn't support the group.net.cozic.joplin App Group.

> Provisioning profile "iOS Team Provisioning Profile: net.cozic.joplin" doesn't include the com.apple.security.application-groups entitlement.

I don't quite understand the issue. Does it mean that it's not possible for someone to take the project and compile it without having some IDs or keys set on their dev account?

**Comment by sirnacnud** [comment]
The problem is the app group "net.cozic.joplin" also was associated with my developer account. Xcode does this automatically when you try to build the project. I didn't think you could remove an app group from your developer account, but I just found out how to do it. So it should be all good now. 🤞

**Comment by roman-r-m** [comment]
Interesting, does this mean anyone can claim this group and prevent Laurent from releasing Joplin iOS?

**Comment by sirnacnud** [comment]
> Interesting, does this mean anyone can claim this group and prevent Laurent from releasing Joplin iOS?

Yes, technically someone could create the app group identifier in their developer account since I just removed it from mine. In that case we would just have to create a new one for Joplin.

**Comment by laurent22** [comment]
I managed to archive the app, but distribution eventually failed with these errors. Any ideas about them?

> App Store Connect Operation Error
> ERROR ITMS-90057: "The bundle 'Payload/Joplin.app/PlugIns/ShareExtension.appex' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring"

> App Store Connect Operation Error
> ERROR ITMS-90360: "Missing Info.plist value. A value for the key 'CFBundleShortVersionString' in bundle Joplin.app/PlugIns/ShareExtension.appex is required."

> App Store Connect Operation Error
> ERROR ITMS-90361: "Invalid Info.plist value type. The value type for the key 'NSExtensionActivationSupportsText' in bundle Joplin.app/PlugIns/ShareExtension.appex is not a boolean."

> App Store Connect Operation Warning
> WARNING ITMS-90473: "CFBundleVersion Mismatch. The CFBundleVersion value '1' of extension 'Joplin.app/PlugIns/ShareExtension.appex' does not match the CFBundleVersion value '64' of its containing iOS application 'Joplin.app'."

Being unable to release the iOS app due to an extension is kind of my worst fears coming true 😬 I'm hoping that once these issues are fixed, it will just work afterwards, but I appreciate anyway that sharing is never an easy matter on mobile.

**Comment by sirnacnud** [comment]
I went ahead and fixed the issues in the linked PR. In general when increasing the Build number of the Joplin app, you will need to also set the Build number of share extension to be the same.

**Comment by laurent22** [comment]
Thanks for the info. As I'm releasing off a different branch I've ended up manually applying these changes and it works now. I'm going to submit to the App Store now and hopefully all will be good. Many thanks for your prompt replies, much appreciated!

**Comment by laurent22** [comment]
The iOS app is now in the App Store so hopefully everything's good now 🤞

**Comment by laurent22** [comment]
@sirnacnud, I'm having an issue releasing the app again. When I try to build it, it says:

```
ld: warning: directory not found for option '-L/Users/xxxxxx/Library/Developer/Xcode/DerivedData/Joplin-fngngsifhfjkgkfsruhhrkgwoekn/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/JoplinCommonShareExtension'
ld: library not found for -lJoplinCommonShareExtension
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

So it looks like it cannot find "JoplinCommonShareExtension", any idea what can be done to fix this?

**Comment by laurent22** [comment]
Actually I think I fixed it. The problem was a mismatch between deployment targets.
