### ISSUE TITLE
Chrome extension not working 

### ISSUE THREAD

**Issue by ohthatflo** [laurent22/joplin#4947]
## Environment

Joplin version: 1.7.11
Platform: Windows 10/Chrome
OS specifics: Windows 10 Home 19042.928/ Chrome Version 90.0.4430.93 

## Steps to reproduce

1. Install Chrome extension from Chrome website
2. Try to use Chrome extension by clicking on the icon
3. It says 

_Joplin extension is not available on this tab due to: tabsExecuteScript: Cannot load {"file":"/content_scripts/JSDOMParser.js"}
The extensions gallery cannot be scripted._

## Describe what you expected to happen

Clip the site for Joplin, the app, installed on my PC 
![Capture](https://user-images.githubusercontent.com/84036661/117858194-7c6c7380-b242-11eb-9bca-e09726ea423d.PNG)

**Comment by laurent22** [comment]
This is normal, the extension doesn't have access to the Chrome gallery.

**Comment by ohthatflo** [comment]
> This is normal, the extension doesn't have access to the Chrome gallery.

How do I know if it's working properly? is there something I need to do on my end? should I just try another method of clipping?

**Comment by suixinio** [comment]
Please make sure that Joplin of the system is running.

**Comment by phanirithvij** [comment]
this can be closed I think.

**Comment by MarcS1975** [comment]
Hi - I still have this issue.
Running Joplin on Win10 and Chrome/Firefox both report an error when using the Plugin
Chrome Error:
The Joplin extension is not available on this tab due to: tabsExecuteScript: Cannot load {"file":"/content_scripts/JSDOMParser.js"}: Cannot access a chrome:// URL

**Comment by laurent22** [comment]
You need to run it from a non-special page. For example it won't work on setting page or Chrome extension page

**Comment by MarcS1975** [comment]
ok - thank you -> works

**Comment by MarcS1975** [comment]
super cool feature! works well now
thanks again

**Comment by caressofsteel** [comment]
I had this issue with the Vivaldi chromium browser. A restart of the browser solved the issue.
