### ISSUE TITLE
joplin-android 1.8.5 is labelled as pre-release

### ISSUE THREAD

**Issue by calvinbui** [laurent22/joplin#4955]
## Environment

Joplin version: 1.8.5
Platform: Android
OS specifics: N/A

## Steps to reproduce

1. Go to https://github.com/laurent22/joplin-android/releases
2. See v1.8.5 is shown as pre-release
3. On the Play Store, v1.8.5 is available and ready for download
4. Go to F-Droid ([IzzyOnDroid repo](https://android.izzysoft.de/repo/apk/net.cozic.joplin)) and it is not available as they only provide released versions

## Describe what you expected to happen

The pre-release label to be removed from v.1.8.5 on https://github.com/laurent22/joplin-android/releases

**Comment by laurent22** [comment]
That's done now, thanks.
