### ISSUE TITLE
Android app: RevisionService deadlocks main UI when syncing with file system and local target that is temporarily unavaliable.

### ISSUE THREAD

**Issue by ioogithub** [laurent22/joplin#4959]
## Problem
I am using the file system as a synchronization target and using another app (rclone) to sync. Rclone uses fuse to mount remote filesystems as local mounted drives. This solution works brilliantly and syncing is reliable except for one corner case:

If Joplin is started and the phone is offline, the main UI is completely blocked and unresponsive, no taps are registered. It will remain frozen until the phone is brought online again. This use case effectively disabled Joplin as being used in offline mode even though all of the files on the phone locally.

## Environment
Joplin version: 1.8.5
Platform: Android 10
OS specifics: LineageOS

## Steps to reproduce
1. Install Joplin and setup a local file system target.
2. Use a 3rd party syncing software to manage the file system target. In this case rclone.
2. Simulate making the the sync target unavailable.
3. Open Joplin
4. Observe the app is completely frozen and non responsive displaying the last used screen. It does not respond to any taps.
5. Bring the phone back online
6. Observe that Joplin actually had queued all of the taps and they are all executed in a flood of rapid fire secession.
7. The sync process continues.
7. The end result is that Joplin with this configuration loses the ability to be used offline due to the synchronization process blocking the main UI thread.

## Describe what you expected to happen
1. Since all of the files are actually still available in /data/data/net/cozic/joplin/files. Joplin should be able to work regardless of the synchronization function. It appears that the sync function is blocking the main process indefinitely, it never times out. I have tested it for up to 30 minutes and Joplin remains completely frozen.

## Proposed solutions
1. A proposed solution would be to implement a timeout on startup, if the sync process can't complete for any reason Joplin should still be available.
2. A better solution would be to move the RevisionService into a separate thread which does not block the main UI from rendering so that Joplin is still available to be used and is not completely frozen.

## Logfile

In the logfile there are no errors, everything is normal except the time to complete the RevisionService is a huge time which represents the time the phone was started offline until the time it was brought back online. During this time Joplin is completely frozen.

Here is the end result:

"RevisionService::maintenance: Done in 1683589ms" <-- Also the time Joplin was frozen.

**Comment by laurent22** [comment]
I don't expect we can solve this. If the drive is offline then the fuse driver should throw some error but instead it seems it makes the app wait, or it should keep some local cache of what is has synced before and expose this.

Making the app thread safe is not an option, and a timeout would only work if the JavaScript process was not frozen, but it is as it's waiting for the driver to respond.

**Comment by JackGruber** [comment]
This is not supported because **locale** file sync assumes that the directory is always there. 
If the app did not freeze, a sync would start and delete the notes or, depending on the setting, the fail safe would break the sync.
This is also the reason why you should not use mapped network drives for sync, but you can use a sync tool like `Syncthing`.

**Comment by ioogithub** [comment]
> I don't expect we can solve this. If the drive is offline then the fuse driver should throw some error but instead it seems it makes the app wait, or it should keep some local cache of what is has synced before and expose this.
> 
> Making the app thread safe is not an option, and a timeout would only work if the JavaScript process was not frozen, but it is as it's waiting for the driver to respond.

I just tested it with the Desktop version- Joplin 1.85 (prod. linux) using the exact same setup. Same rclone local syn target, config and dataset.

The desktop app works as expected, after a few seconds (maybe 2 or 3) the sync timesout and produces an error however the main UI is never frozen, it is always responsive and when the device is brought back online it picks up normally.

Is it possible to use the same method in the Android version as used in the desktop version so that the main UI is not blocked by the the sync function during startup? The desktop version works as I would expect. If the sync target is not available it shouldn't freeze the app, the process should just timeout, all of the data is local and available.

Everything else with this setup works flawlessly, I have been testing the syncing extensively and it is really an amazing solution except for this one corner case.

**Comment by roman-r-m** [comment]
> Is it possible to use the same method in the Android version as used in the desktop version so that the main UI is not blocked by the the sync function during startup?

I'm pretty sure the RevisionService is the same on mobile and desktop, it's the file system IO that is different.

**Comment by laurent22** [comment]
> The desktop app works as expected, after a few seconds (maybe 2 or 3) the sync timesout and produces an error however the main UI is never frozen, it is always responsive and when the device is brought back online it picks up normally.

Desktop and mobile hardware and drivers are very different, but the fact that it works on desktop means it's something outside our control because both apps share the same logic for syncing.

I don't think it's related to the revision service. If the process gets stuck, all running services take forever to complete but it doesn't mean it's due to the service. It just turns out that the revision service prints something but not the others.

**Comment by ioogithub** [comment]
> Desktop and mobile hardware and drivers are very different, but the fact that it works on desktop means it's something outside our control because both apps share the same logic for syncing.
> 
> I don't think it's related to the revision service. If the process gets stuck, all running services take forever to complete but it doesn't mean it's due to the service. It just turns out that the revision service prints something but not the others.

To clarify, in this case the revision service doesn't print anything, the app draws the last accessed screen, freezes indefinitely and never timesout. I got the message from the log afterwards.

I realize there are platform differences and I am investigating the differences. I have tested this same rclone mount with a variety of Android file accessing applications (file managers, password databases, music and photo apps etc.) when the device is offline using the same rclone remote IO sync target. They all behave as expected, they try to access to files and after a few seconds they all timeout with some sort of I/O error message.

The only app that completely freezes indefinitely and never recovers is Android Joplin. Unfortunately accessing notes offline is essential for a a note taking app, especially considering that the primary data store is on the device and fully accessible.

The reason I suspect the revision service is because I do not see a UI freeze if the device goes offline while Joplin is already loaded and running. It will only freeze when the sync process begins or when Joplin is launched (as it automatically syncs).

Is it possible to add error handling so that if the local sync target is not available when a sync initiates, it timesout with an IO error similar to what other apps are showing?

Or could a settings option be added to toggle automatically syncing when Joplin first starts?  This could be a work around as the sync function is a secondary to the main note taking function with the local data store.

**Comment by roman-r-m** [comment]
Hey @ioogithub can you share the steps to set up this with rclone or point me to a guide? I can then try looking into this.

**Comment by ioogithub** [comment]
> Hey @ioogithub can you share the steps to set up this with rclone or point me to a guide? I can then try looking into this.

Sure I can write up a mid level walk though. Rclone is perhaps the most intriguing software project I have ever encountered. Have you used rclone before or are you familiar with it in concept? There are two main ways to get rclone on Android. The best and easiest is a Magisk module (https://github.com/Magisk-Modules-Repo/com.piyushgarg.rclone), this requires a rooted device. There is also a Termux package (https://github.com/termux/termux-app) which will work on non-rooted devices but may be more limited.

I did some further testing and found 3 potential UI work around solutions that could be easier to implement than IO error handling. Each one would work to fix the problem:

1. Perhaps the sync could be delayed by 1 or 2 seconds after Joplin is launched so that the cancel button is still accessible before the UI becomes frozen.
2. When the user sets "Synchronization interval" to "disabled" make the sync at startup obey this setting, currently it does not.
3. Make an auto sync user toggle (on/off) setting.

**Comment by roman-r-m** [comment]
> Have you used rclone before or are you familiar with it in concept?

I have, just not on Android. Or was it rsync? I always mix up these 2.

I'll give it a try, probably sometime next week.
