### ISSUE TITLE
Spell correction of notebook title prompts undesired action

### ISSUE THREAD

**Issue by marcelglueck** [laurent22/joplin#4962]
## Environment

Joplin version: 1.7.11
Platform: Windows
OS specifics: Windows 10 , 10.0.19042 Build 19042

## Steps to reproduce

1. Into the title of a notebook, type in a misspelled word to prompt the spell correction
2. From the drop-down menu, select one of the spellings

## Describe what you expected to happen
The misspelled notebook name should be corrected in the title section. However, the word selected in the drop-down list is pasted into the editor of the notebook, while the word in the title remains uncorrected.

## Logfile
No errors were produced in the console or in the logfile. Hence, no attachment is provided.

**Comment by JackGruber** [comment]
Is fixed in pre release 1.8.2 (https://github.com/laurent22/joplin/issues/4913#issuecomment-830915330)
