### ISSUE TITLE
No Synchronization - 'Last Error' Complains of Lock

### ISSUE THREAD

**Issue by WilliamTotman** [laurent22/joplin#4964]
## Environment

Joplin version: *start:* 1.7.11 & *current:* 1.8.5
Platform: Linux
OS specifics: Fedora 33 & 34

## Steps to reproduce
This occurred under *seemingly* normal use - there may have been multiple clients working on the same 'open' note.
When a synchronization event occurs, there will be a "**Completed (*+ timestamp*)**" message but new notes are not shared and updated notes are not synced across clients.

There are three other clients between which synchronization works.

Other clients are:
- iOS (14.5) + Joplin app (10.7.2)
- MacOS (11.1) + Joplin app (1.7.11)
- Linux (Fedora 33) + Joplin app (1.7.11)

## Describe what you expected to happen
Synchronization between clients of new notes and changes to existing notes.

## Logfile
[joplin-sync-error_phantom-lock.log](https://github.com/laurent22/joplin/files/6480880/joplin-sync-error_phantom-lock.log)

**Comment by laurent22** [comment]
You need to install Redis for file locking on Nextcloud - https://discourse.joplinapp.org/t/file-locked-variation/17268/
