### ISSUE TITLE
Blank Screen in iOS 10.8.1

### ISSUE THREAD

**Issue by vicosoft** [laurent22/joplin#4967]
## Environment

Joplin version: 10.8.1
Platform: iOS
OS specifics: iOS 14.5.1

## Steps to reproduce

1. I have updated from the latest version that was yesterday.
2. When I open the application I only get a blank screen
![Imagen PNG](https://user-images.githubusercontent.com/197478/118354705-b902dc80-b56c-11eb-9b21-2cefdd29b55f.png)

3. 

## Describe what you expected to happen

I was hoping the update would go well and my notes would appear. But I can't access it on iPhone 12 128GB. If I can do it from Linux and Mac OS. Made a backup just in case of all the notes :-)

**Comment by vicosoft** [comment]
I have not tried uninstalling the application and reinstalling it in case you need me to do any tests or if you are doing some background task.

Add that my last backup of notes occupies 1.04GB.

I do not know if you are doing some background occupation that takes a long time.

**Comment by JackGruber** [comment]
In this version there is a database upgrade, so the first start takes a little longer. 
For me it took about 2 minutes for +5000 notes.

**Comment by vicosoft** [comment]
True, in my case it has cost a lot more. I closed the application several times. Now after more than 30 minutes my notes have appeared. Thank you all.

Note: 5927/5927
Folder: 180/180
Resource: 6416/6416
Tag: 245/245
NoteTag: 3498/3498
MasterKey: 1/1
Revision: 310/310
Total: 16577/16577

For if it helps, I include current statistics on the number of notes I handle. I have to do cleaning :-)

Thanks again to the team and @JackGruber for giving me hope :-D I close the case.
