### ISSUE TITLE
Importing ENEX note containing SVG image not shown properly

### ISSUE THREAD

**Issue by hhvitek** [laurent22/joplin#4968]
## Environment

Joplin version: 1.7.11
Platform: Windows
OS specifics: W10

## Steps to reproduce

1. Export note from evernote containing SVG image as ENEX
2. Import ENEX note to Joplin as Markdown

## Describe what you expected to happen

The SVG image should be rendered on screen.
Instead there is a link-text to actial SVG image.

If I import note containing PNG it works as expected. I noted there is a mark character (!) missing in markdown source code.
It actually may be intentional. I just think as a "picture" format it should work same as PNG...

## Logfile

![evernote](https://user-images.githubusercontent.com/52757477/118357186-1ef56100-b579-11eb-8a31-d5eee2372e2a.PNG)
![joplin](https://user-images.githubusercontent.com/52757477/118357194-29175f80-b579-11eb-9ac6-d8278e6d4091.PNG)
[State.enex.txt](https://github.com/laurent22/joplin/files/6485787/State.enex.txt)

**Comment by JackGruber** [comment]
Write a `!` in front of the link to render the svg inline, `![state.svg](....`

**Comment by hhvitek** [comment]
Yeah sure I can do that. 
For me as an user. It would be more convenient, if it is done automatically by Joplin during import...
