### ISSUE TITLE
S3 sync setup error

### ISSUE THREAD

**Issue by mweitzel2005** [laurent22/joplin#4970]
Got an error setting up S3 sync with the Mac client. The error message included the following text:
```
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided.
```

Came across the below reference for the AWS SDK for Javascript:
https://github.com/aws/aws-sdk-js/issues/86#issuecomment-476371303

My secret key also had a `/` inlcuded and replacing the Key and Secret with newly created ones that did not include a `/` seems to have fixed the issue. Interestingly, I was successfully using the intial Key/Secret (with the `/`) combination on Linux, Windows, iOS and Android. Only once I setup the Mac client did it give me the above error.

Screen shot of error in UI:
![Screen Shot 2021-06-01 at 11 25 04](https://user-images.githubusercontent.com/71587939/120327003-98b37b80-c2e9-11eb-9ae3-fd04c409451b.png)

**Comment by enboig** [comment]
I have the same problem. My key/secret have just "alphanumeric" characters (no slashes, neither spaces, ...). It worked on both linux machines, but fail on android. My only "odd character" is a dot "." in my bucket name.
Any idea of why this error happen, how to track it, or how to solve it?
Thanks
