### ISSUE TITLE
In windows dark mode window title bar is white

### ISSUE THREAD

**Issue by zd-dalibor** [laurent22/joplin#4971]
Can we have title bar black when windows dark mode is activated.

![image](https://user-images.githubusercontent.com/226822/118370200-f7b58880-b5a6-11eb-8873-c6e2e991e433.png)

I think all electron apps have this problem but I think it is fixed.
Please check this issue https://github.com/electron/electron/issues/23479

**Comment by MRog40** [comment]
Mine is black, try changing `AccentColor` and `AccentColorInactive` in regedit at `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM`

**Comment by dz2106** [comment]
Taking a look at this issue

**Comment by dz2106** [comment]
https://github.com/laurent22/joplin/issues/4361

**Comment by dz2106** [comment]
So I did some digging. It appears that this feature of Electron is not compatible with prebuilt versions of Electron. There are workarounds such as a custom title bar with CSS that appear to fix the issue. enable_win_dark_mode_window_ui to true would partially solve the issue if we were to build electron ourselves.

**Comment by dz2106** [comment]
Created a forum post on this issue: https://discourse.joplinapp.org/t/windows-dark-title-bar/17442

It seems others have had this concern for sometime now.

**Comment by dz2106** [comment]
Looking at the forum responses, it is best to close this issue as no solutions worked with the project goals

**Comment by jberlyn** [comment]
Can this issue be reopened? It's quite jarring having a light title bar when the entire system is set to dark mode.

![image](https://github.com/laurent22/joplin/assets/10014944/8b7d5dbd-1537-4f46-9a2a-b3ab9c839998)
