### ISSUE TITLE
Application window opens off screen.

### ISSUE THREAD

**Issue by christopherwoodall** [laurent22/joplin#4973]
## Environment

Joplin version: <=1.8.5 
Platform:  Windows 10
OS specifics: Windows

## Steps to reproduce

1.  Have a dual monitor setup
2.  Place Joplink on the external monitor
3.  Close Joplin
4. Remove the external monitor
5. Start Joplin

## Describe what you expected to happen
Monitor(s) should be detected dynamically. A workaround was mentioned [here](https://github.com/mawie81/electron-window-state/issues/38).

## Logfile

```
 I found that hitting ALT+Space when the window is selected brings up the menu, press maximize, then you can grab the window
```
https://github.com/electron/electron/issues/11349

**Comment by roman-r-m** [comment]
As a workaround you can also press Alt + left/right arrow to bring the window to the screen, might need to press several times.

**Comment by renzhuo** [comment]
this issue still exists, and alt+left/right won't solve the problem anymore

**Comment by ThatCoffeeGuy** [comment]
Yep, just encountering this, neither alt+left or shift on the taskbar icon and move option help.

**Comment by ThatCoffeeGuy** [comment]
Shift+win+arrow helped.
