### ISSUE TITLE
why always notice the file watched, where can I close the notice?

### ISSUE THREAD

**Issue by carldats** [laurent22/joplin#4974]
When opening the image , the top always alert the below msg. Where can I close the notice?

下列附件将被监控变化： ac57378673dd6da08f9b7e44b9010ed8.png
当您切换到其他笔记时，这些附件将不再被监控。
<img width="744" alt="Snipaste_2021-05-16_09-30-44" src="https://user-images.githubusercontent.com/25075365/118382599-df3a8200-b629-11eb-806d-2459c21137b2.png">

**Comment by JackGruber** [comment]
From opening this issue:

>Feature requests and support
>I have a question or feature request … 

Got to: https://discourse.joplinapp.org/
