### ISSUE TITLE
Delete the notebook or note, the attachments can not be deleted too

### ISSUE THREAD

**Issue by carldats** [laurent22/joplin#4975]
If I delete a note, the attachments still in resource folder. 
But I can find the status 'is_associated = 0' in sqllite, so I only manuelly delete them. 
And the overall attachments has no status in UI.

**Comment by JackGruber** [comment]
From opening this issue:

>Feature requests and support
>I have a question or feature request … 

Got to: https://discourse.joplinapp.org/



But as a tip:
https://joplinapp.org/note_history/
