### ISSUE TITLE
joplin-cli: 'ls' output appends whitespace to note title

### ISSUE THREAD

**Issue by jottr** [laurent22/joplin#4978]
## Environment

Joplin version: `joplin 1.6.4 (prod)`
Platform: `macOS`
OS specifics:
```
ProductVersion:	10.15.7
BuildVersion:	19H524
```

**Expectation:**

`$ joplin ls` should output a list of notes, delimited by `<CR>`. 

**What happens instead:**

`$ joplin ls` outputs a list of notes, appended by whitespace, delimited by `<CR>`. 

This is unexpected behaviour. 
The trailing whitespace needs to be stripped before the output of 'ls' can be consumed by other scripts.

**Example:**

```
$ joplin edit "$(joplin ls | fzf --reverse)"
# select an existing note 'mynote'
Note does not exist: "mynote  ". Create it? (Y/n)
```

Stripping traling whitespace from `ls` output fixes the issue:

```
$ joplin edit "$(joplin ls | sed 's/[ \t]*$//' | fzf)"
```

**Comment by tessus** [comment]
This is not an entirely correct report. The issue is not that one whitespace is added for every entry.

If you have X number of notes, all entries are padded to the length of the longest note.

But I do not know, if it is a bug or was intended. IMO it could have been. Imagine you want to generate a table....

**Comment by jottr** [comment]
Replacing whitespace with `_` and linebreaks with `$`:

```
$ joplin ls | tr ' \n' '_N'
xxxxxxxx__Nxxx_______Nxxx_______Nxxxxxxx___Nxxx-xxxxxxNxxxxxxx___Nxxxxx_____N
```
You are correct, that the padding seems to be exactly to the longest note, as can be seen above.

> But I do not know, if it is a bug or was intended. IMO it could have been. Imagine you want to generate a table....

Padding a list without the user explicitly specifying this behaviour is a surprising design choice.   
If there is a use case for padded lists, it should be made explicit, e.g.: `joplin ls --table` or `--pad`

Otherwise, using `printf` can be used to pad lists for tables and such.

**Comment by tessus** [comment]
It might be used internally by the terminal app. Laurent would know for sure.

**Comment by laurent22** [comment]
The result of this command is for display, it wasn’t meant to be parsed. If you want to parse the result you should use `-f json`

**Comment by jottr** [comment]
> Have machine-readable output where it does not impact usability. Streams of text is the universal interface in UNIX. Programs typically output lines of text, and programs typically expect lines of text as input, therefore you can compose multiple programs together. This is normally done to make it possible to write scripts, but it can also help the usability for humans using programs. **For example, a user should be able to pipe output to grep and it should do what they expect.** 

https://clig.dev/#output

Emphasis mine. 

It is non-obvious to the user, that `ls` output pads strings. I think joplin-cli is the first ever cli program I encountered, that behaves this way.    

Having to pipe `ls` through `jq` just to retrieve a simple list is overly complicated.

**Comment by jottr** [comment]
Not stale.
