### ISSUE TITLE
[Feature Request] Add MD bullet indentation when caret is at start of line

### ISSUE THREAD

**Issue by maqp** [laurent22/joplin#498]
First of all, many thanks for creating this awesome app, and especially for including client-side encryption.

Intuitive control over indentation is really important when quickly jotting down notes.

Currently, pressing `enter` after typing an entry `* foo` properly creates the next bullet point on the next line. At that point, if I'd like to indent that next bullet point, I annoyingly need to do `home` > `tab` > `end` to indent the asterisk. So I'm asking you to add a feature that indents the asterisk (and thus the bullet point) when pressing tab in situation, where the caret is located in the position of one space after the asterisk. The `shift+tab` already deindents properly when the caret is at that (and pretty much any other) position.

**Comment by michae1ho11ey** [comment]
Adding support for `cmd/ctrl+[` and `cmd/ctrl+]` to indent and deindents would be nice as well.

**Comment by takacsot** [comment]
IT should be working for all kind of list. "unordered" and "task" are clear enough.

For ordered list the following is a must have:

- when indented the numbering of the list should start from "1". 
- when deindenting it is not needed to change back to the next of the higher level list.
-

**Comment by etcSudoers** [comment]
This is probably my biggest item on my wish list.  If i'm in a meeting trying to keep up while taking notes, and i bullet items some stuff i get all messed up if i go to indent and it doesnt sub-bullet

**Comment by v-marinkov** [comment]
Agreed, this is a vital feature regardless of the keyboard shortcut.

**Comment by green-codes** [comment]
Will also appreciate this feature very much! A quick way to increment/decrement indentation is vital for the list-oriented :)

**Comment by mgbckr** [comment]
For me this also would be improving my Joplin experience a lot! :)

**Comment by kilejd** [comment]
Note taking for me is almost always hierarchical, I'm glad for the option to indent bullets already (Home, Tab, End), but those are excessive keystrokes and not at all intuitive.  Adding my vote.

**Comment by kir4h** [comment]
Adding also my vote, being able to indent directly without the `Home`/`End` overhead would come really handy.

And in the meantime: Thank you so much for Joplin!

**Comment by pandrija** [comment]
+1
Joplin is great! This is my single gripe with it. 
I'm sure that anyone using list indenting feels this.

**Comment by usernamenumber** [comment]
Adding my +1 and echoing others saying this is the #1 impediment I encounter as a daily Joplin user.

**Comment by maqp** [comment]
@laurent22 I get that you're very busy but given that many people seem to consider this a top priority issue (including myself), any thoughts on how complex the solution would be?
