### ISSUE TITLE
Low contrast on "sync target needs to be upgraded" link text

### ISSUE THREAD

**Issue by scitech** [laurent22/joplin#4983]
Hello, I just upgraded Joplin and was prompted to upgrade my sync target.

I found it hard to read the "Restart and upgrade" link, which is blue text on the blue banner here:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/4130722/118525383-baffa380-b704-11eb-8c40-ab37681e91ae.png">

## Environment

Joplin version: 1.8.5
Platform: macOS
OS specifics: 10.14.6

## Steps to reproduce

1. Start Joplin using a sync target that needs to be upgraded
2. Check out the text on the banner

## Describe what you expected to happen

The link text should be easier to read 

## Logfile

N/A

**Comment by Aaishpra** [comment]
Hi, Can I take this up?

**Comment by roman-r-m** [comment]
> Hi, Can I take this up?

Sure, go for it

**Comment by dz2106** [comment]
`		} else if (this.props.shouldUpgradeSyncTarget) {
			msg = (
				<span>
					{_('The sync target needs to be upgraded before Joplin can sync. The operation may take a few minutes to complete and the app needs to be restarted. To proceed please click on the link.')}{' '}
					<a href="#" onClick={() => onRestartAndUpgrade()}>
						{_('Restart and upgrade')}
					style="color:red"
					</a>
				</span>
			);`

**Comment by dz2106** [comment]
joplin-dev\joplin-dev\packages\app-desktop\gui\MainScreen\MainScreen.tsx

Line 557: else if (this.props.shouldUpgradeSyncTarget) { msg = ( <span> {_('The sync target needs to be upgraded before Joplin can sync. The operation may take a few minutes to complete and the app needs to be restarted. To proceed please click on the link.')}{' '} <a href="#" onClick={() => onRestartAndUpgrade()}> {_('Restart and upgrade')} style="color:white" </a> </span> );

Added in style="color:white" to ensure the contrast matched that of the plaintext to avoid the blue on blue characteristic of the original.

https://github.com/laurent22/joplin/pull/5036

**Comment by dz2106** [comment]
@roman-r-m I need a branch to be able to make a PR with these changes

**Comment by roman-r-m** [comment]
> @roman-r-m I need a branch to be able to make a PR with these changes

Sure, go ahead and create one then.

**Comment by dz2106** [comment]
> > @roman-r-m I need a branch to be able to make a PR with these changes
> 
> Sure, go ahead and create one then.

I do not have write access, I can create a fork but I cannot branch to laurent22/joplin

**Comment by roman-r-m** [comment]
> > > @roman-r-m I need a branch to be able to make a PR with these changes
> > 
> > 
> > Sure, go ahead and create one then.
> 
> I do not have write access, I can create a fork but I cannot branch to laurent22/joplin

That's not how it works. You need to fork, create a branch **in your fork**, commit your changes to that branch, and then create a pull request from `your-repo:branch-with-fix` to `laurent22:dev`

Here's an example for an open PR
![image](https://user-images.githubusercontent.com/995612/120342913-27c39200-c2f0-11eb-9a0e-df81f4cd7bb9.png)

Hope this makes sense, let me know if you need more clarification on this.

**Comment by dz2106** [comment]
> > > > @roman-r-m I need a branch to be able to make a PR with these changes
> > > 
> > > 
> > > Sure, go ahead and create one then.
> > 
> > 
> > I do not have write access, I can create a fork but I cannot branch to laurent22/joplin
> 
> That's not how it works. You need to fork, create a branch **in your fork**, commit your changes to that branch, and then create a pull request from `your-repo:branch-with-fix` to `laurent22:dev`
> 
> Here's an example from an open PR
> ![image](https://user-images.githubusercontent.com/995612/120342913-27c39200-c2f0-11eb-9a0e-df81f4cd7bb9.png)
> 
> Hope this makes sense, let me know if you need more help with this.

Thanks Roman, making the PR now with the fork
