### ISSUE TITLE
Bad request on S3 sync with Scaleway buckets

### ISSUE THREAD

**Issue by vin-6** [laurent22/joplin#4987]
## Environment

Joplin version: Joplin 2.0.1
Platform: Linux
OS specifics: Archlinux

## Steps to reproduce

1. Create S3 bucket in Scaleway provider
2. Configure Joplin to sync files in this bucket
3. Click on "Check synchronization configuration"

## Describe what you expected to happen

Hi, 

I'm facing a bad request when I try to setup a s3 sync with a Scaleway bucket.
![image](https://user-images.githubusercontent.com/30341969/118668975-a0f1be00-b7f5-11eb-9985-383049332f6e.png)

My s3 bucket is accessible as I can sync files using `s3cmd` tool.
I think the problem is around the URL construction.

**Comment by v-gatien** [comment]
I don't have it, but I can retry.
I followed [this doc](https://joplinapp.org/debugging/), but don't found any logs about it.
I'll retry it and give you a what I see

**Comment by v-gatien** [comment]
> Are there any more details in logs?

Hi, 

I just rechecked with debugging enabled but when I click on "Check synchronization configuration" I have nothing in console nor in `log.txt` file.
I tried to capture something interesting with tcpdump but got nothing more…

How can I help you to get more information about this ?

**Comment by vin-6** [comment]
:up: 
How can I help you on this issue ?

**Comment by leematos** [comment]
@vin-6 I have a pending Pull Request to update the s3 library in joplin. If that goes through, I'm happy to try and help you get to the bottom of this as I am now pretty familiar with the S3 portion of the codebase.

**Comment by vin-6** [comment]
Thanks @leematos 
I subscribed to your PR. Let me know if I can to something to help you :slightly_smiling_face:

**Comment by vin-6** [comment]
Hi,

I've tested with the following version, and it doesn't work anymore…
```
Joplin 2.3.5 (prod, linux)
Sync Version: 3
Profile Version: 39
Revision: 819af3c
```
I'll retry with debug mode to see if I can get  logs and I'll keep you in touch

**Comment by vin-6** [comment]
Hi 🙋‍♂️,

I've tested syncing my Joplin to a Scaleway S3 bucket and it works with this version : 

Joplin 2.6.10 (prod, linux)
Sync Version: 3
Revision: 98fba37
