### ISSUE TITLE
SQL Error when viewing items in joplin server 2.01 UI

### ISSUE THREAD

**Issue by jeffabailey** [laurent22/joplin#4988]
## Environment

Joplin server version: v2.0.1
Platform: Synology with the stock Postgresql server version, (PostgreSQL) 9.3.25
OS specifics: 

cat /etc/VERSION
majorversion="6"
minorversion="2"
major="6"
minor="2"
micro="4"
productversion="6.2.4"
buildphase="GM"
buildnumber="25556"
smallfixnumber="0"
nano="0"
base="25556"
builddate="2021/03/04"
buildtime="19:44:30"

## Steps to reproduce

1. Navigate to /items in the Joplin Server UI
2. See this error.

![image](https://user-images.githubusercontent.com/776901/118738624-558ede00-b7fc-11eb-83bf-26f8dac309de.png)

Raw SQL Error:

```
select "items"."id", "items"."name", "items"."updated_time", count(*) from "user_items" left join "items" on "user_items"."item_id" = "items"."id" where "user_items"."user_id" = $1 - column "items.id" must appear in the GROUP BY clause or be used in an aggregate function
```

## Describe what you expected to happen

A list of notes in the database.

**Comment by laurent22** [comment]
This is fixed and will be in next version
