### ISSUE TITLE
Cannot sort on Android

### ISSUE THREAD

**Issue by yajo** [laurent22/joplin#4989]
## Environment

Joplin version: 1.8.5
Platform: Android
OS specifics: Android 10, Device SM-T720

## Steps to reproduce

1. Open tasks folder
2. Set custom order
3. Try to reorder tasks, but you can't

## Describe what you expected to happen

I expect that tasks have some kind of handle that lets me drag and drop them to reorder them.

**Comment by ddnexus** [comment]
Applies also to the desktop app in a different way.
The drag and drop works only 1 out of 10 attempts, and when it does, it may drop the note as a subnote, instead of just moving it. Other times, it just drops the note at the end of the list.
I didn't find any keyboard shortcut to do the same.

Ubuntu 21.04

**Comment by Yajo** [comment]
.

**Comment by ddnexus** [comment]
🖐

**Comment by ddnexus** [comment]
🖐

**Comment by Yajo** [comment]
🐵

**Comment by Yajo** [comment]
👋

**Comment by yajo** [comment]
,

**Comment by AreaZone** [comment]
Still a problem 🤷‍♂️

**Comment by yajo** [comment]
https://user-images.githubusercontent.com/973709/174430032-56b4749d-eae8-4026-80f9-710c51c77223.mp4

**Comment by yajo** [comment]
🦑

**Comment by yajo** [comment]
😶‍🌫️

**Comment by yajo** [comment]
El lun, 19 de sep de 2022 a las 09:03:00 AM, github-actions[bot] 
***@***.***> escribió:
> Has the issue been fixed, or does it still require the community's 
> attention?

Still unfixed

**Comment by yajo** [comment]
🥲

**Comment by yajo** [comment]
🍸

**Comment by yajo** [comment]
🫠

**Comment by yajo** [comment]
👋

**Comment by TaoK** [comment]
Could we change the name of this issue to "Changing custom sort order of notes in Android App" please?

The other concerns are better represented (if mixed together a little) in #4162 already.

**Comment by ddnexus** [comment]
👍🏻

**Comment by yajo** [comment]
😶‍🌫️

**Comment by AreaZone** [comment]
👁️
