### ISSUE TITLE
Joplin-desktop fails to download all end-to-end encrypted notes from a NextCloud server

### ISSUE THREAD

**Issue by Atalanttore** [laurent22/joplin#4994]
## Environment

Joplin version: 2.0.1
Platform: Linux
Sync ersion: 2
Profile version: 37
Revision: 74d8fec

## Steps to reproduce

1. Joplin for Android: Set up the app
2. Joplin for Android: Set up end-to-end synchronization with a NextCloud server
3. Joplin for Android: Create a lot of notes
4. Joplin for Linux: Download and launch Joplin AppImage
5. Joplin for Linux: Set up end-to-end synchronization with the same NextCloud server
6. After some time Joplin cancels the synchronization process with an error message.

## Describe what you expected to happen
A smooth download of all existing notes.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/6518251/log.txt)

**Comment by be-we** [comment]
@roman-r-m Unfortunately, this is not my server and I do not have access to its logs.

According to the server operator, there are no issues with the server despite the error message.

**Comment by Atalanttore** [comment]
Since I've been using a different NextCloud server, the problem has not reoccurred.
