### ISSUE TITLE
Syntax highlighting for links within lists is inconsistent across themes

### ISSUE THREAD

**Issue by ImperialSquid** [laurent22/joplin#4995]
## Decription
When writing links in notes the link portion is highlighted differently, however, when in a list this is only sometimes applied.

For example, in Light, Dark, Solarised Light, Solarised Dark and OLED Dark themes, the link portion is coloured differently to the text of the link (and other text in the list)
Example in Light theme
![HighlightingBugLight](https://user-images.githubusercontent.com/44560551/119067922-02bf4d00-b9db-11eb-82b7-2d0806028a3d.PNG)
Example in Dark theme
![HighlightingBugDark](https://user-images.githubusercontent.com/44560551/119067924-02bf4d00-b9db-11eb-885b-2bea23d19584.PNG)

However, in Dracula, Atirim Dark and Nord, the link portion is the same colour as the text in the list
Example in Dracula theme
![HighlightingBugDracula](https://user-images.githubusercontent.com/44560551/119067963-21bddf00-b9db-11eb-942a-aa48c2b32541.PNG)
Example in Nord theme
![HighlightingBugNord](https://user-images.githubusercontent.com/44560551/119067967-22567580-b9db-11eb-90ce-2cdf08909096.PNG)
Example in Atirim Dark theme
![HighlightingBugAtirimDark](https://user-images.githubusercontent.com/44560551/119067964-22567580-b9db-11eb-8365-1516839957c4.PNG)

## Environment
Joplin version: 1.8.5
Platform: Windows (other platforms are untested)
OS specifics: Windows 10

## Steps to reproduce
1. Open a note
2. Make a link within a list
2. Change the theme to either Dracula, Nord or Atirim Dark

## Describe what you expected to happen
The syntax highlighting of links should also occur when in a list but doesn't

## Logfile
N/A

**Comment by CalebJohn** [comment]
Syntax highlighting is handled by the editor component that Joplin uses: CodeMirror. The CodeMirror themes used for Dracula, Aritim Dark, and Nord are: dracula, monokai, and nord. If you want these to see these themes updated, you should [request it from the CodeMirror project](https://github.com/codemirror/codemirror).

You can also use [userchrome.css](https://github.com/laurent22/joplin#custom-css) to customize any theme to your liking. You can take a look at this [wiki page](https://discourse.joplinapp.org/t/joplin-customization/11195) for useful tweaks.
