### ISSUE TITLE
Some strings can't be translated

### ISSUE THREAD

**Issue by Elaborendum** [laurent22/joplin#4996]
Certain strings aren't available for translation in the .po file, the ones I've found are:
![image](https://user-images.githubusercontent.com/71190696/119211885-867c4680-ba7a-11eb-84a4-9ff0712c4fca.png)
The find and replace dialog's title from the rich text editor.

![image](https://user-images.githubusercontent.com/71190696/119211886-88dea080-ba7a-11eb-8650-1780fab70578.png)
Some strings in Sync Status.

![image](https://user-images.githubusercontent.com/71190696/119211888-8c722780-ba7a-11eb-8197-8e4a768445dc.png)
The description of these two options in the Appearance settings.

![image](https://user-images.githubusercontent.com/71190696/119211889-9136db80-ba7a-11eb-94db-0cedf8e7a76f.png)
The beta spell checking option in the General settings (althought this might be because it's in beta?

![image](https://user-images.githubusercontent.com/71190696/119211933-dd821b80-ba7a-11eb-9732-ed0ec2da8853.png)
The descriptions of these two new options.

## Environment

Joplin version: 1.8.5
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Change language from English to any other
2. Look for any of the above strings. 

## Describe what you expected to happen
The strings should be available for translation in the .po file

**Comment by laurent22** [comment]
Actually @CalebJohn, do you think we can put the spell checking for Markdown editor out of beta? Do you know of any remaining issue with it?

**Comment by CalebJohn** [comment]
There are some issues where the cursor displayed does not reflect the actual location of the cursor. There are some workarounds in place but it's not a perfect experience. I was hoping to leave the beta in place until we upgrade the editor to CodeMirror 6.
My basic plan is to update the mobile editor to CodeMirror 6, and then eventually bring the desktop editor over as well. I think it should be possible to share the editor between desktop and mobile, which will be pretty nice. I don't have time right now to be doing big changes like that, but hope to look into this towards the end of the year.

**Comment by laurent22** [comment]
Ok sounds good, so let's leave the beta checkbox in place.

**Comment by laurent22** [comment]
@Elaborendum, thanks for reporting these issues. I've checked them all and it turns out we either won't change some of these (for example we don't translate the status screen because if someone send us a report in Arabic or something then it's harder for us to help), or we can't (the Find and Replace dialog, for which we need to wait for the translation from TinyMCE).

Others we don't translate because I'm not sure the option will stay. We wait for things to be stable before making things translatable.
