### ISSUE TITLE
Protocol "https:" not supported on Joplin 2.0.2

### ISSUE THREAD

**Issue by referi** [laurent22/joplin#4997]
I use Nextcloud Synchronisation target with https url. Resently I installed Joplin 2.0.2 and found that it is impossible to use Nextloud sync with htpps url. Please return this feature.
"Protocol "https:" not supported. Expected "http:" (Code ERR_INVALID_PROTOCOL)"

## Environment
Joplin 2.0.2 (prod, linux)
Client ID: 78ff642915a94fd8aacf3fa05c9cc083
Sync Version: 2
Profile Version: 37
Keychain Supported: No
Revision: 8930dac

**Comment by roman-r-m** [comment]
I do not think this error is coming from Joplin, looks more like your Nextcloud server.
Logs might be helpful btw.

**Comment by referi** [comment]
> 
> 
> I do not think this error is coming from Joplin, looks more like your Nextcloud server.
> Logs might be helpful btw.

You were right. fixed.

**Comment by ssmid** [comment]
I've got the same issue. No access/error log server side. According to the built in developer tools, no request has been made. The network tab stays empty.

@roman-r-m Could you consider reopening this issue?

JS-Traceback:
[ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:152)
    at request (https.js:314)
    at /tmp/.mount_JoplinK22Pb8/resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:119
    at new Promise (<anonymous>)
    at new Fetch (/tmp/.mount_JoplinK22Pb8/resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:49)
    at Fetch (/tmp/.mount_JoplinK22Pb8/resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:37)
    at /tmp/.mount_JoplinK22Pb8/resources/app.asar/node_modules/@joplin/lib/shim-init-node.js:350
    at Object.<anonymous> (/tmp/.mount_JoplinK22Pb8/resources/app.asar/node_modules/@joplin/lib/shim.js:156)
    at Generator.next (<anonymous>)
    at /tmp/.mount_JoplinK22Pb8/resources/app.asar/node_modules/@joplin/lib/shim.js:8

Joplin 1.8.5 (prod, linux) (AppImage Version, installed via bash script)
Sync Version: 2
Profile Version: 35
Keychain Supported: No
Revision: b28f087

OS: Linux Mint 20.1 Cinnamon

**Comment by ssmid** [comment]
Seems to be a duplicate: #5014

**Comment by burtton99** [comment]
![image](https://user-images.githubusercontent.com/35190595/119752172-141ec280-becf-11eb-847e-7125108ff8a7.png)
is 1.8.5
