### ISSUE TITLE
Plugin: unable to use bundled external scripts

### ISSUE THREAD

**Issue by chenlijun99** [laurent22/joplin#5000]
Apparently external scripts (i.e. webview scripts and content scripts) can only be JavaScript files that are directly copied to the dist folder. Scripts that are, instead, bundled by webpack don't work.

The error reported on the console of the main process is:

```
Uncaught ReferenceError: exports is not defined
```

I think that this [forum thread](https://discourse.joplinapp.org/t/loading-d3-js-in-webview/14397) mentions the same problem.

Inspecting the bundled external script, we see something like this: 

```js
exports.default=function(e){var t={};function r(n){if(t[n])return t[n].exports;var o=t[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}return r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(r.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)r.d(n,o,function(t){return e[t]}.bind(null,o));return n},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s=0)}([function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),console.log("Hello World")}]).default;
```

Now, I'm not savvy of the messy javascript module ecosystem, but on a hunch it seems that the external script is being bundled as a module, instead of a script that is supposed to be executed.

In fact, I noticed that a slightly different webpack config is being used for external scripts:

https://github.com/laurent22/joplin/blob/4760e5e8ba890b62d462a7b534ec72ae0a039c1a/packages/generator-joplin/generators/app/templates/webpack.config.js#L199-L201

By removing these lines, reexecuting webpack, everything works. The bundled script looks like:

```js
!function(e){var t={};function r(n){if(t[n])return t[n].exports;var o=t[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(r.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)r.d(n,o,function(t){return e[t]}.bind(null,o));return n},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s=0)}([function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),console.log("Hello World")}]);
```

Were there any particular reason why these 3 lines were added?

## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Ubuntu 20.04

**Comment by laurent22** [comment]
Sounds like you need to use plugin.config.json https://github.com/laurent22/joplin/tree/dev/packages/generator-joplin#external-script-files

**Comment by chenlijun99** [comment]
I'm using it.

**Comment by laurent22** [comment]
Do you have any example plugin that shows the issue?

**Comment by chenlijun99** [comment]
Give me a few minutes

**Comment by roman-r-m** [comment]
You can certainly write webview scripts in TS and even add dependencies to them separately from the main plugin code.
You just need to change webpack config to pack it all in a single js. For example I did it here https://www.github.com/roman-r-m/joplin-plugin-resource-search

**Comment by chenlijun99** [comment]
@roman-r-m Sure. In fact I got it working by removing these 3 lines from the default webpack configuration.

https://github.com/laurent22/joplin/blob/4760e5e8ba890b62d462a7b534ec72ae0a039c1a/packages/generator-joplin/generators/app/templates/webpack.config.js#L199-L201

I'm just wondering whether these 3 lines have a purpose or can be considered a bug.

**Comment by chenlijun99** [comment]
@laurent22 Please take a look at https://github.com/chenlijun99/joplin-issue-5000-demonstration.
The first commit is copied from the TOC example in the joplin codebase.
The second commit demonstrates the issue and the third applies the fix/workaround.

**Comment by laurent22** [comment]
Ok I think I know what the issue is. External scripts are compiled as libraries because that was done with Markdown or CodeMirror content scripts in mind, and those are included with `require()`. For webview scripts, they indeed need to be compiled as non-libraries since they are included as regular JS files in a web page.

We still need to keep the current library compilation as it's used in many plugins, however maybe we could add support for a different compilation style for webviews.

**Comment by chenlijun99** [comment]
Thanks for looking into this! 

> however maybe we could add support for a different compilation style for webviews.

I think that's exactly what @roman-r-m did.

**Comment by laurent22** [comment]
Maybe the way to go would to add support for a new entry in plugin.config.json? Now we have "extraScripts", which is really only for content scripts, so we could rename it "contentScripts". And then we can add a "webviewScripts" entry to, and these will be compiled without the library flags.

So something like this:

```json
{
	"contentScripts": [
		"markdownItScript.ts",
		"codeMirrorPlugin.js"
	],
	"webviewScripts": [
		"webview.ts"
	],
	"extraScripts": [
		"// We keep this key as as an alias for 'contentScripts'"
	]
}
```

Would that work?

**Comment by chenlijun99** [comment]
For me it would be perfect!

**Comment by roman-r-m** [comment]
That's won't let you to have dependencies e.g. only for webview or content script

**Comment by laurent22** [comment]
What kind of dependency do you mean? If it's for example a file that's imported from the main plugin script, it will be bundled by webpack so there's no need for a special entry for it.

**Comment by roman-r-m** [comment]
For example for my basic real-time collaboration plugin (https://discourse.joplinapp.org/t/collaborative-edit-plugin/14743) I needed CodeMirror content script to have a dependency on Yjs. 
Or for another plugin I have tried using some autocomplete lib in a webview script; that didn't work out for unrelated reason.

**Comment by laurent22** [comment]
I'd need to check the plugin, but if the content script imports the Yjs dependency (using require() or "import"), it should be bundled with the content script by webpack. Webpack basically follows all the require() and bundles everything it finds in a single JS file.

The content script would have to be registered under the "extraScripts" key.

**Comment by roman-r-m** [comment]
Ok, maybe for content script it's not relevant, I also don't remember, but it certainly is for webview scripts. But I suppose with your proposed changes it'll work just like content scripts.

**Comment by chenlijun99** [comment]
@roman-r-m I'm not sure to understand you. What you said in https://github.com/laurent22/joplin/issues/5000#issuecomment-846583749 and https://github.com/laurent22/joplin/issues/5000#issuecomment-846627231 seem to be quite contrasting.

Anyway, in the plugin I'm developing, by removing

https://github.com/laurent22/joplin/blob/4760e5e8ba890b62d462a7b534ec72ae0a039c1a/packages/generator-joplin/generators/app/templates/webpack.config.js#L199-L201

I've successfully incorporated rxjs and react.js into the webview scripts.
