### ISSUE TITLE
Keyboard shortcut export not functional

### ISSUE THREAD

**Issue by bytefluxio** [laurent22/joplin#5001]
I'm trying to export the default keyboard shortcuts (Haven't changed any shortcuts yet).
In the `Keyboard Shortcuts` tab, when I click on the `export button`, a `*.json file is created`.
The file only includes an empty array `[]`

Expected: Json file to include the whole key shortcut mapping, even those undefined ones.

## Environment

Joplin version: 1.7.11
Platform: Windows 10 Home
OS specifics: 21387.1

## Steps to reproduce

1. Open Joplin Keyboard Shortcuts tab in the Options
2. Click Export
3. Check created json file

**Comment by laurent22** [comment]
This button only exports the changes that you've made, not the default mapping.
