### ISSUE TITLE
Not enought contrast in Aritim Dark: Horizontal Rule and Inline Code are hard to read/see

### ISSUE THREAD

**Issue by Elaborendum** [laurent22/joplin#5002]
When writing something as inline code in the Aritim Dark theme, it's written in a barely visible dark green. (ignore the red line, I'm using a spell checker in another language)

Same thing happens if you create a horizontal rule, but this time both on Markdown and WYSIWYG view

Aritim Dark:
![image](https://user-images.githubusercontent.com/71190696/119268715-d57cc580-bbb9-11eb-973c-96eb46d61189.png)

Regular Dark:
![image](https://user-images.githubusercontent.com/71190696/119268731-e0375a80-bbb9-11eb-9369-5fb49762d328.png)

Horizontal Rule in Markdown view:
![imagen](https://user-images.githubusercontent.com/71190696/134271669-45b11fc7-c675-4587-9747-2743cacf8b83.png)

Horizontal Rule in WYSIWYG view:
![imagen](https://user-images.githubusercontent.com/71190696/134271712-bb7b4476-2e9e-4fab-bdb9-05e32701f51b.png)

## Environment

Joplin version: 1.8.5-2.3.5
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Change theme to Aritim Dark
2. Write something as inline code or create a horizontal rule
3. See the low contrast

## Describe what you expected to happen

Text/rule should be easier to read.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by calfzhou** [comment]
+1 all dark themes are hard to recognize inline code and code block.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/3761553/177509616-9fadff04-b6a3-42d5-a8cb-f09f1ef451ff.png">

**Comment by Daeraxa** [comment]
> +1 all dark themes are hard to recognize inline code and code block.

What theme is that? I just went through all the dark themes and none of the code blocks appear like that for me. Are you using any custom CSS?

**Comment by calfzhou** [comment]
I'm using Joplin for Desktop 2.8.8 on Mac OS.

It's strange. I reinstalled the desktop app, now it looks good. I guess it might caused by the `macOS theme` plugin, but not very sure. I did't use any custom themes.

Joplin 2.8.8 (prod, darwin)

Client ID: c7186efe5a5643a38d4b546e5a3a3663
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: c2a6a13

> > +1 all dark themes are hard to recognize inline code and code block.
> 
> What theme is that? I just went through all the dark themes and none of the code blocks appear like that for me. Are you using any custom CSS?

**Comment by calfzhou** [comment]
Ah, I find the root cause. When i use `Source Code Pro` font for monospace, the color changes ... Now I removed custom font setting.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.
