### ISSUE TITLE
The API search filtered all notes when showCompletedTodos is set to false

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#5007]
When searching for notes via the API and the showCompletedTodos is set to false and the fields is_todo and todo_completed should not be returned then all notes are filternd. 

```
overviewNotes = await joplin.data.get(["search"], {
  query: "joplin",
  fields: "id, title, body",
});
```

## Environment

Joplin 2.0.1 (dev, win32)

Client ID: 3786010df4424355b5ac92d208168602
Sync Version: 2
Profile Version: 37
Keychain Supported: Yes

Revision: 68b516998 (test)

## Steps to reproduce

1. Set `Show completed to-dos` to disable
2. Run a search query in a plugin or API without the todo fields
  http://localhost:27583/search?query=joplin&type=note&token=
3. No search results returned
4. Set `Show completed to-dos` to enable
5. run query again and the search results are returned

## Describe what you expected to happen

1) The API search does not consider the option `showCompletedTodos` and always returns all matches
or
2) The API search does consider the option `showCompletedTodos` and filterd the notes accordingly

@laurent22 what do you think is the best option for the API search to handel this behavior?
I think for the API is almost the option 1 the best?

The behavior occurs since #4951 

https://github.com/laurent22/joplin/blob/68b516998db8fe2e014ded5f2f35a730ebd764d1/packages/lib/services/searchengine/SearchEngineUtils.ts#L54

**Comment by laurent22** [comment]
Hmm, in fact what's returned by the API should not be affected by the settings, so I think it was a mistake to add this "showCompletedTodos" condition to SearchEngineUtils. Or maybe it's a mistake to use SearchEngineUtils in routes/search.ts

Actually we have a filter iscomplete:0/1, so is it not sufficient to filter based on whether a to-do is completed or not? Why do we need this support for showCompletedTodos in search?

**Comment by JackGruber** [comment]
The PR was not meant to filter notes based on the option, but not to show the notes after a search. 

In the `BaseApplication.ts`  and `refreshSearch.js` the `SearchEngineUtils.notesForQuery` is used for selecting the notes. 
Therefore I thought this function is only used for displaying the notes, but the other plase this function is used is `routes/search.ts`.

**Comment by laurent22** [comment]
Right, on the UI side it does make sense. So I guess the bug could be that it's used in routes/search.ts. Maybe some option could be added like "applyUserSettings", and if "false" we don't filter based on "showCompletedTodos". Would that fix the original issue?

**Comment by JackGruber** [comment]
Yes, I prepare fix.
