### ISSUE TITLE
Unknown flag: -psn_0_1007862

### ISSUE THREAD

**Issue by srossmia** [laurent22/joplin#501]
### Operating system

- macOS

### Application

- Desktop

Receiving the following error upon opening .dmg from Github.

<img width="420" alt="joplin error" src="https://user-images.githubusercontent.com/11378666/39792677-24f41e78-52ff-11e8-89e8-1b899d3ff505.png">

**Comment by tessus** [comment]
duplicate of #480 

fixed in 4c210d09568603da64decc1f9d032c0f58bebf8d

not released yet

**Comment by laurent22** [comment]
Duplicate of #480
