### ISSUE TITLE
Use webdav protocol to synchronize notes and prompt errors.

### ISSUE THREAD

**Issue by burtton99** [laurent22/joplin#5014]
Use webdav protocol to synchronize notes and prompt errors.
![image](https://user-images.githubusercontent.com/35190595/119644414-69b38a80-be4f-11eb-90db-50eba768f0bf.png)

![image](https://user-images.githubusercontent.com/35190595/119644048-09244d80-be4f-11eb-8e68-c91cecf64d8c.png)

![image](https://user-images.githubusercontent.com/35190595/119644081-12151f00-be4f-11eb-8e29-c3f2fecad3ae.png)

Before this, my configuration can be synchronized, and I also see my note files in this folder

版本：1.8.5，
平台Platform: windows10

**Comment by laurent22** [comment]
Did you try with a "http" instead? `http://pan.qita...`

**Comment by ssmid** [comment]
I've got the same issue with the Nextcloud setting (see #4997). Plain HTTP is not really an option for me, since it's online and HTTP is disabled therefore.

**Comment by roman-r-m** [comment]
Found the issue, will fix soon. For now as a workaround:
* restart Joplin
* go to sync settings
* set the url with https
* press "ok"
* restart Joplin again
* should work with https

**Comment by ssmid** [comment]
After tinkering a bit with the URL it now works perfectly fine. Thank you!

**Comment by burtton99** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    The computer side is fine, I have solved it, but there is a problem again on the mobile side. Model ios, the latest version. The same webdav parameter configuration is used
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                350174676
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 5/26/2021 ***@***.***> wrote： 



Did you try with a "http" instead? http://pan.qita...

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by burtton99** [comment]
> 您是否尝试使用“ http”代替？ `http://pan.qita...`
The computer side is fine, I have solved it, but there is a problem again on the mobile side. Model ios, the latest version. The same webdav parameter configuration is used

![IMG_1143](https://user-images.githubusercontent.com/35190595/119752055-df127000-bece-11eb-8d9b-48762742ed1c.PNG)

**Comment by burtton99** [comment]
> 稍微修改一下网址后，现在可以正常使用了。谢谢！

The computer side is fine, I have solved it, but there is a problem again on the mobile side. Model ios, the latest version. The same webdav parameter configuration is used

**Comment by burtton99** [comment]
> 发现了问题，将很快解决。现在作为解决方法：
> 
> * 重新启动乔普林
> * 去同步设置
> * 用https设置网址
> * 按“确定”
> * 再次重新启动Joplin
> * 应该与https一起使用
The computer side is fine, I have solved it, but there is a problem again on the mobile side. Model ios, the latest version. The same webdav parameter configuration is used
![IMG_1143](https://user-images.githubusercontent.com/35190595/119752272-47f9e800-becf-11eb-8fca-eeb5e0993295.PNG)

**Comment by burtton99** [comment]
> > 稍微修改一下网址后，现在可以正常使用了。谢谢！
> 
> 计算机端很好，我已经解决了，但是移动端还是有问题。型号ios，最新版本。使用相同的webdav参数配置
I checked, you mean that joplin supports the https protocol, but I use the https protocol but it prompts me not to support it. I changed it to the http protocol, which can be synchronized on a PC, but it cannot be synchronized on an Apple phone.

**Comment by laurent22** [comment]
@roman-r-m, are these issues related to the http/https bug you've just fixed?

**Comment by roman-r-m** [comment]
> @roman-r-m, are these issues related to the http/https bug you've just fixed?

I don't think so, the bug only affects the desktop version, must be something else.

**Comment by Sakura-oss1** [comment]
I am Getting the same Problem too in Arch Linux

**Comment by Sakura-oss1** [comment]
But the fix mentioned by @roman-r-m works

**Comment by DearChuck** [comment]
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"

![image](https://user-images.githubusercontent.com/42369972/170947876-ad871d1a-e611-49a5-a9ee-21e22cf9529f.png)

![image](https://user-images.githubusercontent.com/42369972/170948003-156463f2-93f7-428b-83ed-f7010472053f.png)

what should i do?
