### ISSUE TITLE
Removing notebook does not remove associated files

### ISSUE THREAD

**Issue by quamis** [laurent22/joplin#5019]
I installed Joplin via flatpak on Linux Mint, started a notebook, and deleted the default one.
I've noticed that the .resource still contains images from the default notebook

## Environment

Joplin version: 1.8.5 (prod, linux), installed from flatpack
Platform: Linux
OS specifics: Linux mint 20

I'm synchronizing the notebook in a folder in nextcloud (joplin syncs in a local folder, but that folder is synchronised by nextcloud).

## Steps to reproduce

1. Install
2. Remove default notebook
3. Open the .resource folder

## Describe what you expected to happen
I had expected that the resource folder to be empty

## Logfile
- will look it up if needed

Seems related to https://github.com/laurent22/joplin/issues/154 . Linux is not mentioned there, it might be a platform specific bug?

**Comment by JackGruber** [comment]
What is your config for history?

https://joplinapp.org/#note-history
https://joplinapp.org/note_history/

**Comment by quamis** [comment]
I do not have it enabled, and is set to 1. Yesterday I tried setting it 0, and it still didn't delete the files.

![image](https://user-images.githubusercontent.com/2966084/119961818-22441000-bfaf-11eb-9338-293d2ff346db.png)

**Comment by quamis** [comment]
It seems like it deleted the resource files, the folder is now empty, but the .md files from the default notebook are still present on disk, maybe it deletes them after 1-2 days, even if I unchecked the history checkbox?


[1cd98af0d1b44d07a0dfa81e3e77e02f.md](https://github.com/laurent22/joplin/files/6577600/1cd98af0d1b44d07a0dfa81e3e77e02f.md)

These are handled differently than image files? Should I open a new issue on github for this one?

**Comment by quamis** [comment]
It seems that the files are now deleted. It might be a timing issue, as they were left on disk for a long time. They are not present anymore.  This can be closed
