### ISSUE TITLE
Let the spinning arrows spin in the direction, that they are pointing which is clockwise.

### ISSUE THREAD

**Issue by mogoh** [laurent22/joplin#5026]
## Environment

Joplin version: 1.8.5
Platform: Android
OS specifics: 11

## Steps to reproduce

1. Synchronize
1. The arrows are spinning counter-clockwise

## Describe what you expected to happen

The arrows should spin in the direction that they are pointing, which is clockwise.

**Comment by mogoh** [comment]
Yes, this is still an issue.

**Comment by entrymaster** [comment]
Does the issue still persists ?

**Comment by roman-r-m** [comment]
> Does the issue still persists ?
> 

It's very simple to check yourself, isn't it?

Just install the app, set up synchronisation, and press the send button

**Comment by entrymaster** [comment]
![untitled](https://user-images.githubusercontent.com/55127997/158410341-57fe7643-6f3a-4c9f-bc81-94f8ef9c775e.gif)
@laurent22 @roman-r-m  Seems fine to me
