### ISSUE TITLE
Naming problems in exporting MD files

### ISSUE THREAD

**Issue by X-hood** [laurent22/joplin#5028]
When I export my notes to MD files, some of them have the same file name as the original notes, but some of them add a horizontal bar after the original notes, such as `note_.md`.

Joplin version: Joplin 1.8.5
Platform: Windows
OS specifics: win10 1909 (18363.1379)

I'm sure there are no duplicate notes.
When I export that note separately, it will also add a horizontal bar after the file name.
I don't understand what the problem is.
And how to avoid that.
Thanks a lot!

**Comment by laurent22** [comment]
Most like just a space after the note title?

**Comment by X-hood** [comment]
> Most likely just a space after the note title?

There is no space in the title.

**Comment by X-hood** [comment]
> Most likely just a space after the note title?

In a sense, you are right. After a variety of tests, I found the problem.

The problem is the external editor or note title setting.

Joplin will use the first line of the MD file as the title by default, or the title will be placed in the first line of the MD file. When creating a new note, if you directly open the external editor to write the note, the first line will be set as the title, and there will be a horizontal bar after the file name when exporting the note.

If you edit at least one line in Joplin before editing notes with an external editor, you won't have this problem.

Now I've found a temporary solution, and I understand that it's probably a carriage return or something. I don't know if this is a problem that can be solved. For example, we can use the external editor at any time in the future without this problem.

**Comment by laurent22** [comment]
This is probably a CRLF issue since you are on Windows. I think we handle CRLF properly in various places but maybe not in this case. In the meantime you can always make sure your editor only use Linux line endings (LF) when saving a file.

**Comment by X-hood** [comment]
> This is probably a CRLF issue since you are on Windows. I think we handle CRLF properly in various places but maybe not in this case. In the meantime you can always make sure your editor only use Linux line endings (LF) when saving a file.

thanks
