### ISSUE TITLE
Double ellipsis icons in WYSIWYG toolbar

### ISSUE THREAD

**Issue by yajo** [laurent22/joplin#5033]
## Environment

Joplin version: Joplin 1.8.5 (prod, linux)
Platform: Linux
OS specifics: Fedora 34 Silverblue, installed from flathub

## Steps to reproduce

See it live:

https://user-images.githubusercontent.com/973709/120218857-3f3c4580-c232-11eb-9709-5beb61080e3e.mp4

Thin windows have double ellipsis in the WYSIWYG toolbar.

## Describe what you expected to happen

Just one ellipsis.

## Logfile

I don't think it's needed here.

**Comment by Yajo** [comment]
Still happens.

**Comment by Yajo** [comment]
El mié, 4 de ago de 2021 a las 15:45:08 PM, stale[bot] 
***@***.***> escribió:
> Has the issue been fixed, or does it still require the community's 
> attention?

It still happens.

**Comment by Yajo** [comment]
It still happens.

**Comment by Yajo** [comment]
🙋‍♂️

**Comment by Yajo** [comment]
Still happening.

**Comment by Yajo** [comment]
🦶🏼

**Comment by Yajo** [comment]
hello

**Comment by yajo** [comment]
No, bot.

**Comment by yajo** [comment]
🍺

**Comment by yajo** [comment]
Hi

**Comment by yajo** [comment]
Bad bot

**Comment by yajo** [comment]
...
