### ISSUE TITLE
Inconsistent search highlighting in table

### ISSUE THREAD

**Issue by billygarrison** [laurent22/joplin#5038]
## Environment
Joplin version: 1.8.5
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce
1. Create table in new note `TestNote`:
```
| columnA | columnB | columnC |
| --- | --- | --- |
| ipsum lorem test | ipsum lorem | ipsum lorem |
| ipsum lorem | ipsum lorem test | ipsum lorem |
```
2. Search all notes for `test`
3. - A) If `TestNote` is the first note returned by the search, then both occurrences of `test` are highlighted in note as expected in the markdown side of the split view text editor, but not in the rendered markdown side. ![image](https://user-images.githubusercontent.com/30005204/120354973-4b2f1280-c2d9-11eb-9bb5-a2ab77bfef49.png)
	- B) If `TestNote` is not the first result in the search results pane and you have to click on it, or if you click a different note in the search results pane and then click on `TestNote` to return to it, then the search result highlighting works correctly in both panes. ![image](https://user-images.githubusercontent.com/30005204/120355040-597d2e80-c2d9-11eb-8c34-68ad569085d9.png)
	- Interestingly, in Case "A" (highlighting only shows on markdown pane), if you do `Ctrl + F` and search for `test`, then the syntax highlighting shows up properly in both panes (as expected) and then stays in place in both panes after exiting the `Ctrl + F` search box (unexpected, as it would normally disappear after closing the `Ctrl + F` search box). The highlighting goes away after you click the `X` in the "global" search bar as expected. So it seems that the `Ctrl + F` search somehow reminds the global search that it should be highlighting in both panes.

**Comment by billygarrison** [comment]
Bumping because of stale bot

**Comment by JackGruber** [comment]
I cant't reproduce this behaviour on Joplin `2.1.5`

![grafik](https://user-images.githubusercontent.com/24863925/124222233-a2efb200-db01-11eb-925e-8a99304f0b34.png)
