### ISSUE TITLE
Update fs-extra, when COW support will be merged

### ISSUE THREAD

**Issue by In-line** [laurent22/joplin#5047]
Copy-on-write copy is much faster on supported systems.

https://github.com/jprichardson/node-fs-extra/pull/906

**Comment by roman-r-m** [comment]
I can't think of a situation where file copy would be a bottleneck for Joplin so the benefits of upgrading aren't obvious to me

**Comment by In-line** [comment]
@In-line Sync from filesystem on slow drive (my case basically)

**Comment by roman-r-m** [comment]
Interesting, I wonder how slow should the disk be for this to become an issue.
