### ISSUE TITLE
Android application incredibly laggy on OnePlus3

### ISSUE THREAD

**Issue by TobiasDev** [laurent22/joplin#505]
### Operating system

- Android

### Application

- Mobile

Whenever I use the Joplin application on my phone it is super laggy. I have a oneplus3 and no other application I have does this. I tried re-installing but is still incredibly slow and laggy. Anyone know how to fix this?

**Comment by laurent22** [comment]
Doing what operation? Do you have many notes? Do you use E2EE?

**Comment by merlinuwe** [comment]
Since today (2 android releases), I also have this problem. There are only a few (< 10) notes with .jpg-pictures, one .pdf, one .xlsx, one html and I use E2EE for all my notes. (Wiko Robby is the brand of the smartphone.)
Syncronizing took a long time.
Reinstalling hasn't changed something.
I saw, that there were much more notes (~ 40) synchronized, than I originally had.

**Comment by laurent22** [comment]
The initial sync when E2EE is enabled can take a long time depending on the size of the resources. Basically each resource needs to be encrypted on the device and then uploaded to the sync target. Is it still slow once the initial sync is done?

In my case I use E2EE with Nextcloud and about 5000 items and it's fast enough (on an Xperia Z5).

By the way, when you see "40" it's the number of items - so notes + tags + notebooks + resources.

**Comment by TobiasDev** [comment]
I have e2e but it is always slow. Even after everything is loaded. And when I open the side to see all notebooks is it super laggy for me.

**Comment by laurent22** [comment]
I think I found the cause of this recent slow down. I wanted to limit the number of sync operations but accidentally increased them, so I will change this back for the next version and it should be like before (or, normally, a bit better).

**Comment by TobiasDev** [comment]
Not sure what your fix did, but now sadly it is even worse. Now the whole app is laggy for me, even when just typing. I took a video. Joplin is the only app that is laggy for me.

https://web.tresorit.com/l#m-Arh7QcdXO2QT8Xq4P48A

**Comment by laurent22** [comment]
@TobiasDev, is it any better with this release? https://github.com/laurent22/joplin-android/releases/download/android-v1.0.125/joplin-v1.0.125.apk

**Comment by TobiasDev** [comment]
Yep, tried it for a few hours now. No lag! :) Thanks!

**Comment by TobiasDev** [comment]
My laggy issue seems to be fixed. However, the side still feels a bit slow but maybe that is by design? 

I added another video showing the difference between Joplin and another app (Twidere) just so show what I mean. 

https://web.tresorit.com/l#xw9eJZmWOTTKCyRc6WbWGw

**Comment by TobiasDev** [comment]
Ah, I understand. Then I'll close the issue. :)
