### ISSUE TITLE
Wrong appimage's checksum for v2.0.4

### ISSUE THREAD

**Issue by Thynkon** [laurent22/joplin#5050]
## Environment

Joplin version: 2.0.4
Platform: Archlinux
OS specifics: makepkg (pacman) 6.0.0

## Steps to reproduce

1. Download appimage's checksum:
```bash
curl -v -L https://github.com/laurent22/joplin/releases/download/v2.0.4/Joplin-2.0.4.AppImage.sha512 -o Joplin-2.0.4.AppImage.sha512
```
2. Download the appimage file:
```bash
curl -L https://github.com/laurent22/joplin/releases/download/v2.0.4/Joplin-2.0.4.AppImage -o Joplin-2.0.4.AppImage
```
3. Generate appimage checksum and compare it with the one downloaded from github:
```bash
sha512sum Joplin-2.0.4.AppImage
```
```bash
cat Joplin-2.0.4.AppImage.sha512
```

## Describe what you expected to happen
As maintainer of the AUR package [joplin-appimage](https://aur.archlinux.org/packages/joplin-appimage/), I use the appimage provided in each pre-release to allow users of arch-based linux distributions to use Joplin without having to build it locally.

When version 2.0.4 was released, I tried to update the package I maintain but I was getting a file integrity error. So I manually checked the appimage checksum and found out that it was wrong.

If someone could correct it, I would be grateful.

**Comment by laurent22** [comment]
Yes that will be fixed in next release.

**Comment by Thynkon** [comment]
Thank you for your reply. I'm closing this issue.
