### ISSUE TITLE
Joplin app opens to white screen

### ISSUE THREAD

**Issue by jankuf** [laurent22/joplin#5054]
## Environment

Joplin version: 10.8.1
Platform: iPhone XR and iPhone 6s Plus
OS specifics: ios 14.5.1 and iOS 13.3.1 respectively

## Steps to reproduce

1. Open Joplin app
2. Blank white screen displays and user is unable to do anything.
3. Here is a video of the action: https://streamable.com/ot16ij

This happens on both an iPhone XR and iPhone 6s Plus with two different ios versions (ios 14.5.1 and iOS 13.3.1 respectively). I’ve tried closing, reinstalling the app, and restarting the phones, but no change has occurred. The previous version of Joplin was working as intended, but ever since 10.8.1 was released I haven’t been able to access the Joplin mobile app

## Describe what you expected to happen

I expected to:

1. open Joplin app
2. Be navigated to an open Joplin notebook
3. Perform any app functions (create a note, view a note, etc)

## Logfile

I can’t open the app so I can’t turn debugging on

**Comment by mdeweerd** [comment]
I have the same issue on windows:
```

**Comment by mdeweerd** [comment]
Joplin 1.8.5 (prod, win32)

ID client : e68929521707410f981f2f7b19bcfd34
Version de Synchro : 2
Version du profil : 35
Trousseau supporté : Oui

Révision : b28f087bb
````

I have set the "Appearance" to "Sombre" (<Dark>, second option in the relevant option list) and requested the application to start in the notification zone.  However that option does not seem to impact the behavior on subsequent starts in the same Windows session.

Also, I supposed that having the application start minimized would start it at the startup of the PC, but it doesn't.  And when I start the application, I do get the full application window.

To get a working interface, I close the app window (leaving the app running in the notification zone), and then reopen the app.

**Comment by JackGruber** [comment]
@jankuf is this a new installation or with an app upgrade from previous version?

**Comment by burtton99** [comment]
joplin  2.0.2 (prod, win32)Have the same problem:

**Comment by mdeweerd** [comment]
```
Joplin 2.0.11 (prod, win32)

ID client : e68929521707410f981f2f7b19bcfd34
Version de Synchro : 2
Version du profil : 39
Trousseau supporté : Oui

Révision : 981b1d845
```

I still observe the issue that Joplin is opening a blank window, but it seems to happen only when I request that Joplin starts minimized.

**Comment by filipevilaca** [comment]
I've been getting this problem since some past versions.  In Windows 10. [https://imgur.com/a/sWSzoBP](url) Closing and opening again normally fixes it.

**Comment by mdeweerd** [comment]
It seems there is progress.  Instead of getting a full white contents, it is now a full black contents (I hava a dark theme).

My current version:
```
Joplin 2.1.9 (prod, win32)

ID client : e68929521707410f981f2f7b19bcfd34
Version de Synchro : 2
Version du profil : 39
Trousseau supporté : Oui

Révision : 882d66383
```

**Comment by filipevilaca** [comment]
I would say that maybe that's a different issue. The white screen is fixed for me.

**Comment by JackGruber** [comment]
@mdeweerd this issue was for mobile app not desktop!

**Comment by mdeweerd** [comment]
@JackGruber Ok, but title says "app" and I commented on June 10th that I had the same issue on Windows.

Can this "Issue" also hold for the Windows App or must I create a new one.
