### ISSUE TITLE
File links not working in MacOS

### ISSUE THREAD

**Issue by Andy4K** [laurent22/joplin#5055]
## Environment

Joplin version: 1.85, 2.02
Platform: Mac OS 
OS specifics: 11.4 (Big Sur)

## Steps to reproduce

1. Create a file link by option-dragging a folder or file to a note.
2. Click on link
3. File or folder does not open

## Describe what you expected to happen
In version 1.7.11 clicking on a file link works as expected. In 1.8 and the alpha release, 2.02, the file links do not.

## Logfile

Not seeing any errors logged in the log or console, just entries when I click on a note:

08:53:16: Loading existing note df6fb0271bc2488eae69463ae4feefea
/Applications/Joplin 2.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 08:53:16: Loaded note: {id: "df6fb0271bc2488eae69463ae4feefea", parent_id: "88372a1a9c264707bfe0cd410ff0bd10", title: "Character Creation", body: "[**Unproven**](file:///Users/kaufmann/Documents/Ga…0%5BPrinter%20Friendly%20-%20Redesign%5D.pdf)↵↵↵↵", created_time: 1605579425528, …}

Log: 

[log.txt](https://github.com/laurent22/joplin/files/6602571/log.txt)

**Comment by laurent22** [comment]
Yes this will be fixed in the next version.

**Comment by Andy4K** [comment]
👍
