### ISSUE TITLE
Linux AppImage Version is wrong

### ISSUE THREAD

**Issue by dsancheznet** [laurent22/joplin#5059]
I have just downloaded the 1.8.5 AppImage for Linux and the about window states version 1.7.11:

![image](https://user-images.githubusercontent.com/4673828/121333601-dc713b00-c910-11eb-8bce-e463bce1fd16.png)

I'm on Elementary latest stable version.

Best Regards

**Comment by CalebJohn** [comment]
Most likely you are not running the new appimage but are running the previous run. Make sure to quit Joplin using File -> Quit and then launch the newly downloaded appimage.

**Comment by dsancheznet** [comment]
If have been troubleshooting this a bit;

As I said, I'm on Elementary and it does NOT show any icon in the upper corner that is not part of the system. I suspect that the TSR part of Joplin stayed open even after quitting it and thus did not open the new version. 

Let this be an advisory others. You may close this, I have solved the issue. Thanks
