### ISSUE TITLE
joplin The space at the beginning of each line is removed

### ISSUE THREAD

**Issue by toppemonkey** [laurent22/joplin#5060]
The space at the beginning of each line is removed,
how can I do?

**Comment by toppemonkey** [comment]
![image](https://user-images.githubusercontent.com/43023098/121338272-ee260300-c94f-11eb-826f-aa308e91b7de.png)

**Comment by CalebJohn** [comment]
This is the standard behaviour of markdown. You can search on the forum for work arounds.
