### ISSUE TITLE
Black screen when un-minimising

### ISSUE THREAD

**Issue by BackSeat** [laurent22/joplin#5062]
I've just set up a new Linux PC running Debian Bullseye (11).

After using Joplin, I minimise it. When restoring from being minimised, and only after the screensaver has been running, the window has a menu bar but the body is entirely black. Moving the mouse across the window I do see the cursor change shape as it moves over different elements of the window.

I have tried with a debug window but that too is entirely black. Closing and re-opening Joplin fixes the the problem.

## Environment

Joplin version: 1.8.5
Platform: Linux
OS specifics: Debian 11.0

## Steps to reproduce

1. Minimise Joplin
2. Run screensaver (light-locker)
3. Unlock PC and restore Joplin

## Describe what you expected to happen

App to be restored and be readable.

## Logfile

Not visible!

**Comment by BackSeat** [comment]
It's still a problem, but as no one else is seeing it and it isn't a show stopper, I'll close this.

**Comment by matse** [comment]
I gave up on this too, just closing and restarting joplin does the job, though it's not very comfortable workflow.
For now I'll watch #5374 - as it is in the same category.

**Comment by BackSeat** [comment]
What fixed it for me was changing to the `slock` screensaver. No problems since.
