### ISSUE TITLE
Add headers['Cache-Control'] = 'no-store'; after that it will not sync properly without webdav suggest setting it as an option

### ISSUE THREAD

**Issue by You66666666** [laurent22/joplin#5068]
Joplin 1.8.5 (dev, win32)

客户端 ID: 239e818b235542ce98b71a26416cebe3
同步版本: 2
配置文件版本: 35
支持的密钥链: 是

修订: b28f087bb
Add headers['Cache-Control'] = 'no-store'; after that it will not sync properly without webdav suggest setting it as an option

**Comment by roman-r-m** [comment]
What error are you getting? And what's your webdav implementation?

**Comment by You66666666** [comment]
webdav uses a mixed address to download using a different domain name

**Comment by roman-r-m** [comment]
I have tested this and it was working with Apache's WebDAV module. What WebDAV implementation are you using? And can you confirm the exact error you're seeing?
I'm not sure what this means

> webdav uses a mixed address to download using a different domain name

**Comment by You66666666** [comment]
Using Cloudreve the WEBDAV address of this software the file is stored on the S3 object store so the WEBDAV download address does not match the upload address.
