### ISSUE TITLE
Tags rendering "broken"

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#507]
### Operating system

- Linux

### Application

- Desktop

### Description

since version 1.0.89, (may be earlier but I did not notice it)
the render of the tags list is not well align like the folders list 

![sans titre](https://user-images.githubusercontent.com/208212/39831343-6f81e694-53c4-11e8-831c-e114851f5b56.png)

**Comment by laurent22** [comment]
Was already fixed in 74827e53244a5f0c66e6f71169d08621b3dec7f8 :)
