### ISSUE TITLE
Exporting and importing notebook as Jex causes broken links due to WYSIWYG editor

### ISSUE THREAD

**Issue by franciskcso** [laurent22/joplin#5077]
## Environment

Joplin version: 1.7.11
Platform: prod, win32
OS specifics: Windows Professional 64 Bit

## Steps to reproduce

1. Export notebook as Jex - Joplin Export File
2. Import notebook as Jex - Joplin Export File on another computer. In this case, it was a Windows Pro 64 Bit using Joplin 1.7.11.
3. Mouse over link which links to an internal note and the link appears blue and properly formatted but it behaves like text and not like a link. Toggling the WYSIWYG editor to show the code editor seems to "re-render" the link and the link will be clickable. However, toggling the code editor off to use the full screen WYSIWYG breaks changes it back to the original behaviour in which the link behaves like text.

## Describe what you expected to happen
I expected the link to be a clickable hyperlink.

**Comment by JackGruber** [comment]
In WYSIWYG use a right click + open or `Strg` and click to oben the link.

**Comment by franciskcso** [comment]
> In WYSIWYG use a right click + open or `Strg` and click to oben the link.

When I tried right clicking the link and using "Open". I get the message "Resource ID not provided".

![image](https://user-images.githubusercontent.com/6107137/121936297-b54aad00-cd06-11eb-9388-f37f9403f6f1.png)

**Comment by JackGruber** [comment]
https://github.com/laurent22/joplin/pull/4943 This is fixed in the pre-release v2.0.1

**Comment by laurent22** [comment]
Yes, bugs should reported using at least the latest stable version, which would be 1.8.x, or even better the latest pre-release.

**Comment by pmmontanari** [comment]
I am experiencing the same issue right now, after doing the same thing (Export note -> Import note). In my case I don't get a "Resource ID not provided" message, simply nothing happens and the links remain as text. I'm afraid I broke all my Markdown links.

Joplin info:
```
Joplin 3.3.12 (prod, win32)

Device: win32, 13th Gen Intel(R) Core(TM) i7-1355U
Client ID: 52e7ef7a091b4b78b73f8404f40d071c
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes
Alternative instance ID: -

Revision: 4d790b6

Backup: 1.4.3
Combine notes: 1.2.2
Enhancement: 1.2.1
Favorites: 1.3.2
Freehand Drawing: 3.0.1
Joplin Batch: 0.2.2
Joplin debug tool: 0.3.0
Link Icon: 1.0.0
Markmap: 1.7.0
Menu items, Shortcuts, Toolbar icons: 1.1.0
MultiMarkdown Table Tools: 1.2.1
Note Tabs: 1.4.0
Record: 1.5.0
Rich Markdown: 0.16.0
Tagging: 1.0.3
YesYouKan: 1.0.16
```

I don't know if I should open another issue or send a log, for example. I await for your directions.

Thanks!
