### ISSUE TITLE
Can't remove alarm

### ISSUE THREAD

**Issue by Hylders** [laurent22/joplin#5081]
When I'm adding a task and set an alarm. I'm not able to disable it without restarting my phone. I tried to set the task to done and not, using the function to remove the alarm and so on, but nothing works.

## Environment

Joplin version: 1.8.5
Platform: Android
OS specifics: Android 11 fork called CalyxOS version 2.5.0

## Steps to reproduce

1. Add a task
2. Set an alarm to the task
3. Wait until the alarm rings

**Comment by JackGruber** [comment]
Is fixed in the next release. Fix: https://github.com/laurent22/joplin/pull/4984
Bug report: https://github.com/laurent22/joplin/issues/4086
