### ISSUE TITLE
Images and attachments are not encrypted

### ISSUE THREAD

**Issue by aitorpazos** [laurent22/joplin#5084]
Having the following encryption configuration:
![image](https://user-images.githubusercontent.com/2015196/122201786-4d29d180-ce94-11eb-9743-1e2d362f103a.png)

and file system based sync:
![image](https://user-images.githubusercontent.com/2015196/122201904-6cc0fa00-ce94-11eb-8510-50228f7409fc.png)

I see text is encrypted, however attachments and images are stored in plain files:
![image](https://user-images.githubusercontent.com/2015196/122202620-228c4880-ce95-11eb-829d-dfc1b3db200d.png)

## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: KDE Neon. Plasma 5.22.1. Based on Ubuntu 20.04

## Steps to reproduce

1. Enable encryption
2. Create notes that includes images or other attachments
3. Note's text is encrypted, but images and attachments are not

## Describe what you expected to happen

Images and attachments are expected to be encrypted as well to prevent information leakages.

**Comment by JackGruber** [comment]
The locale data of Joplin is not encrypted, only the data on your sync target.

**Comment by aitorpazos** [comment]
Got you, confirmed that sync target files are encrypted. Got confused by the other `*.crypted` files existing along the images and thought those were expected to be encrypted as well.
