### ISSUE TITLE
Version 2.0.8: Headline of new note are generated / shown between tags like <p> my headline </p>

### ISSUE THREAD

**Issue by kai452** [laurent22/joplin#5085]
Best regards,
kai

**Comment by JackGruber** [comment]
Sorry, what?

Have you readed the information, when you create a issue? 

>Please provide a clear and concise description of what the bug is. (In the section Steps To Reproduce.)
  Include screenshots if needed.

**Comment by kai452** [comment]
Hi,
thought it was simple enough just to put in one sentence.
New Note - writing first line generates headline that looks than like
![image](https://user-images.githubusercontent.com/53316526/122338079-7eaba700-cf3f-11eb-9d08-b4d67308998d.png)
Thanks in advance,
Kai

**Comment by kai452** [comment]
Sorry,
closed the issue by fault,
Kai

**Comment by JackGruber** [comment]
When a new issue is created, there is a template with some information that should be filled out. 
Like, Joplin Version, Platform/OS and steps to reproduce. 

But I can`t reproduce youre issue, have you tried a clean installation with no plugins / css? 

![grafik](https://user-images.githubusercontent.com/24863925/122361737-d1915880-cf57-11eb-8aa6-c1b685097180.png)

**Comment by CalebJohn** [comment]
I can't reproduce this either using the WYSIWYG editor on v2.0.10.

**Comment by kai452** [comment]
Hi,

problem seems to be solved with update to 2.1.5.

Thank You all for help.

Kai

**Comment by kai452** [comment]
Hi,

this morning it worked ones, but it was a md-note (markup-language = 1).
Html doesn't work like before, so I reopen the issue.

Kai

**Comment by CalebJohn** [comment]
@kai452 can you provide some details on how to reproduce this issue? Step by step instructions would be helpful because we can't reproduce the issue.

**Comment by kai452** [comment]
@stale: Thanks for reminding.

The issue still exists.
Think I've mentioned, that it only occurs, when markdown language = 2 (html) is set ?
Tested it also without Rich Markdown v0.5.2 and so on.

In meantime I switched back to markdown, because of another heavier [issue](https://discourse.joplinapp.org/t/link-not-working-in-2-0-8/17945)

**Comment by kai452** [comment]
Hi,

after a while and after certain updates I just found the problem does no longer exists.
