### ISSUE TITLE
I saw the sync option of joplin Cloud in version 2.0.11win, but I don’t have an account. I want to know how to register to joplin Cloud email account. Please provide an address to register for joplin Cloud, thank you very much.

### ISSUE THREAD

**Issue by burtton99** [laurent22/joplin#5088]
I saw the sync option of joplin Cloud in version 2.0.11win, but I don’t have an account. I want to know how to register to joplin Cloud email account. Please provide an address to register for joplin Cloud, thank you very much.

**Comment by JackGruber** [comment]
1) A title should be short and concise and not a long sentence
2) This is not a bug, the issues are for bug
3) Her are the infos https://discourse.joplinapp.org/t/introducing-joplin-cloud-beta-program
