### ISSUE TITLE
Deleting a note does not delete embedded resources

### ISSUE THREAD

**Issue by jurgenhaas** [laurent22/joplin#509]
### Operating system

- Linux

### Application

- Desktop

Following up on #504 I wanted to clean up my notebooks and identified the notes which contained the large attachments. I went to the client and deleted those notes. My expectation was, that this would also delete the attached files, but that doesn't happen. They are still there. I checked in `~/.config/joplin-desktop/resources` and saw that the large files were still there.

As I'm syncing with Nextcloud, those big files haven't been deleted there either. So, what I had to do was to delete the file attachment objects in Nextcloud manually.

Shouldn't attachment being deleted as well if the hosting note is being deleted?

**Comment by laurent22** [comment]
Resources that are no longer linked in any note are [deleted after two days](https://joplin.cozic.net/#attachments-resources) ([rational](https://github.com/laurent22/joplin/issues/154#issuecomment-356582366)) so you'll either need to wait or indeed directly delete the data in Nextcloud.

I realise the two days delay is not ideal in this particular case, I think it's a feature that works well for normal use, but not so much for more advanced fixes like what you're doing.

**Comment by laurent22** [comment]
By the way, before the resource auto-deletion was implemented, @corona6 has this script to delete unused resources - https://gist.github.com/corona6/509264be060015d293c8d292e4637a72 Perhaps something you can use?

**Comment by jurgenhaas** [comment]
The rationale makes perfect sense and I think my reported issue is an edge case which doesn't require any changes. The answer to myself: RTFM. I've thought that a lot of users asking question about my own contributions and this time I got caught by it myself :-(

Thanks a lot @laurent22 for a great product and even better support.
