### ISSUE TITLE
Android app cannot sync with Joplin server: POST api/files/root/:/children: Not allowed to POST

### ISSUE THREAD

**Issue by aliakseiz** [laurent22/joplin#5093]
Android client cannot synchronize with a Joplin server anymore after updating the last one from 1.7.2 to 2.1.1.

## Environment

Joplin version: 1.8.5 (Database v35)
Platform: Android
OS specifics: 5.1.1

Joplin server: 2.1.1
Platform: Linux
OS specifics: Ubuntu

## Steps to reproduce

1. Open mobile application
2. Go to "Configuration"
3. Tap "Check synchronization configuration" -> `POST api/files/root/:/children: Not allowed to POST`

## Describe what you expected to happen
Successful synchronization check.

## Logfile
Server log:

```bash
joplin-server | 2021-06-17 18:42:38: App: POST /api/sessions (143ms)
joplin-server | 2021-06-17 18:42:38: [error] App: 400: POST /api/files/root:/:/children : Not allowed: POST
joplin-server | 2021-06-17 18:42:38: App: POST /api/files/root:/:/children (1ms)
```

**Comment by RiverDragon1** [comment]
Having the same issue on all of my devices. Happened after the update recently. 
Although at times i get "Not Allowed: DELETE" as well.

**Comment by JackGruber** [comment]
Joplin v1 Clients can't sync with v2 server!

Breaking change in Joplin Server v2 https://github.com/laurent22/joplin/issues/4948
https://discourse.joplinapp.org/t/major-breaking-change-in-coming-joplin-server-2-0/17254

**Comment by aliakseiz** [comment]
Indeed, the issue was gone, when the client was updated to v2.0.2.

Only that I received a new version today, though it was released on May 16. Is it kind of a rolling release, not for all countries/users at once?
