### ISSUE TITLE
Scrolling To Top On External Editor Change

### ISSUE THREAD

**Issue by deciacco** [laurent22/joplin#5094]
When a change is made in the external editor, the Joplin MD editor scrolls back up to the top instead of maintaining it's scroll position. 

## Environment

Joplin version: 2.0.11
Platform: win32
OS specifics: Windows 10

## Steps to reproduce

1. Open long note in MD editor mode and place cursor at bottom
2. Toggle the external editing button to start the external editor
3. Scroll to bottom in the external editor and make a quick change
4. When Joplin reloads to show the change, it scrolls back to the top

## Describe what you expected to happen

The MD editor to show the change without scrolling all the way back to the top

**Comment by deciacco** [comment]
yep... still happening.... just trying to keep the Stale Bot happy...

**Comment by iatmgu** [comment]
Keeping stale bot happy... this is still an issue. Thank you.
