### ISSUE TITLE
Unlock and unlimit conversation on issue #609

### ISSUE THREAD

**Issue by alemoh1234** [laurent22/joplin#5095]
#I ask that issue #609 be reopened to everyone, so that people like me (who want that feature) can participate on the conversation and give a +1.

To me it's a basic feature needed by joplin, the program is almost perfect as it is, only lacking few things and maybe clearer presentation (for instance I only got to know about the joplin server because of reddit, I think it should be on the applications part of the website, giving it more visibility (to me it's a **huge** feature, even more so on the colaboration aspect of it))

**Comment by laurent22** [comment]
I've unlocked but please don't add +1. It just sends an unnecessary notification to everybody. Instead you could thumb up the issue as we use this to sort issues and find out which ones are more popular.
