### ISSUE TITLE
[WYSIWYG] Bullet/numbered list broken if tabbed in from checklist

### ISSUE THREAD

**Issue by jeroen7s** [laurent22/joplin#5098]
If you create a checklist, and then add an indented bullet or numbered list, it shows a checkbox and bulletpoint on top of each other.
This only affects the WYSIWYG editor, the markdown editor's preview has no such issue.

## Environment

Joplin version: 1.8.5
Platform: Linux (Ubuntu)
OS specifics: Ubuntu 20.04

## Steps to reproduce

1. Create checklist in WYSIWYG mode
2. press tab to indent an option
3. change the type to numbered list or bullet list

## Describe what you expected to happen
![image](https://user-images.githubusercontent.com/10954827/122535603-036ff100-d024-11eb-9da0-fdccf248c16c.png)

Bulletpoints / numbers appear as normal

What happens instead is this
![image](https://user-images.githubusercontent.com/10954827/122535704-184c8480-d024-11eb-88cb-bd99d288144c.png)

The other way around works fine (numbered/bullet list with tabbed in checklist)

**Comment by thiemjoerg** [comment]
When will this be fixed? It is still an issue.

Joplin 2.5.12 (prod, win32)

Client-ID: 2af31b6b698c4384b9198e5d3dcbbe4e
Sync-Version: 3
Profil-Version: 39
Unterstützter Schlüsselbund: Ja

Revision: 884b86f
