### ISSUE TITLE
Re-order notes/to-dos

### ISSUE THREAD

**Issue by internetjanitor** [laurent22/joplin#51]
### Operating system
- [X ] Windows

### Application
- [X ] Desktop
---

When dragging a note, the cursor changes to indicate that it's being dragged but the order doesn't change.  It would be useful to re-order to-dos manually based on priority.

**Comment by laurent22** [comment]
For information, dragging the notes allow you to drop them on a notebook, but yes re-ordering them is currently not supported.

**Comment by ammoto** [comment]
Will this be a feature in the future?

**Comment by laurent22** [comment]
Most likely it will be. The back end supports arbitrary sort orders, so it's a matter of doing the front end.

**Comment by nof8** [comment]
So the frontend will be done simultaneously  for manual reordering and sorting by other things (like creation time, modification time, alphabetically)? Great.
I'd suggest configuration setting "Sort by" and add all the variants quoted above - alphabetically, creation date, modification date, manual.

Hope to have this feature soon :)

**Comment by cossio** [comment]
I would be happy with manual reordering alone.

**Comment by istodorionut** [comment]
![image](https://user-images.githubusercontent.com/42129745/43928422-80995e4a-9c39-11e8-9155-3854b2130bfe.png)


Hello guys,

They're is a problem with sorting notes manually by number 1 - 100.
Take a look at the picture.


![image](https://user-images.githubusercontent.com/42129745/43928575-11de62f6-9c3a-11e8-8171-140285a764a6.png)

Can you fix it ?

Thanks,

**Comment by robocopAlpha** [comment]
Has this been implemented already?
e.g. alphabetical sorting of notes?

Saw this issue merge commits:
#206  
#768  
[Issue #768 ](https://github.com/laurent22/joplin/pull/768/commits)

**Comment by dddjjjbbb** [comment]
Just bumping this. It's a small bugbear given how otherwise awesome Joplin is, but enough to prove persistently bothersome. Sorting on OSX is sporadic at best, same story on Linux (Debian). Is a solution likely to be implemented in the near future? @laurent22, you mentioned the back end supports arbitrary sorting, how involved do you estimate the front end fix being? Perhaps we can discuss a solution? I'd love to push this feature. Whatever the case, thanks for all your hard work :1st_place_medal:

**Comment by laurent22** [comment]
At the moment you can sort the notebooks and notes using various criteria, isn't it sufficient? Maybe we need to add more sorting options?

**Comment by laurent22** [comment]
Main difficulty with arbitrary sorting I suppose is to implement the drag and drop UI, which is tricky.

**Comment by dddjjjbbb** [comment]
The sorting criteria is welcome but unfortunately doesn't solve the use case. There are obviously a myriad of ways in which people sort their thoughts/notes. Although I'm sure there are cases in which stock sort would suffice, in general it will not. This would be resolved, as you said, by drag and drop. I'd vote this feature be marked as essential. It's fundamental to an intuitive UX. I'd be happy to take a look into implementing this if you'd consider including it in the current mini-roadmap.

**Comment by dddjjjbbb** [comment]
I just realised, perhaps the sorting you're referring to is the sorting of notes within a given parent directory? In which case, the stock sort would suffice, at least for me. My issue is rather relating to moving directories within the hierarchy as a whole. For example, say I have a sub directory "Ruby" in a parent directory "Programming" and wish to move this sub directory out, making it the parent. This is the functionality I am referring to. If you need any more detail I'd be happy to record it. Cheers.

**Comment by bmurphy1976** [comment]
I'm confused by what you mean when you say "various sort criteria." 

It seems my notes (OSX) are sorted by most recent created at the top?  In lieu of some other mechanism to reorder the notes, I'd prefer they were consistently sorted alphabetically, but that appears to not be the case.  Can I force them to be alphabetical?

**Comment by lando-cal** [comment]
Personally, manual sorting is essential to the to-do list functionality. 
I love Google Keep's way of allowing quick entry of simple to-do items, as it allows me to sort them at the end of the day with a quick flick. Although, Keep falls short for a myriad of other reasons.

After looking through dozens of options, it seems that Joplin is the closest solution for my use case. So, thank you kindly for making something proper in a niche that seems to be rife with a charge-more-release-less paradigm these days!

That said, this and the lack of widgets are my largest gripes thus far. I'd be more than willing to allocate to a feature bounty or something though, if a venue for such exists.

**Comment by i-need-to-tell-you-something** [comment]
> I'm confused by what you mean when you say "various sort criteria."
> 
> It seems my notes (OSX) are sorted by most recent created at the top? In lieu of some other mechanism to reorder the notes, I'd prefer they were consistently sorted alphabetically, but that appears to not be the case. Can I force them to be alphabetical?

Yes. For me on Linux I can find it in the menubar > View > Sort notebooks by > Title/Updated date/Reverse sort order.

**Comment by rpld** [comment]
As the difficult part would be implementing drag-and-drop, I'd like to suggest a simple alternative that addresses some of the use cases.

Suggestion: Add a "priority" numeric field to each note. For example, 1 to 10. Allow sorting by Priority. When editing a note, pressing on the priority box can bring up a nice slider to pick the new number, or just text entry for starters.

This addition would be very useful by itself. And later, drag-and-drop could be integrated into it- dragging would change the priority to be between the priority of the other notes - which would require it to be non-integer.

Generally, such a priority field is useful for quickly categorizing large lists. In contrast, drag-and-drop is best for micro-managing a small set of notes, such as the top priority todos (you wouldn't want to drag an item across 700 other notes). 

Also, the priority field can be a workaround for drag-and-drop.

Optional: have the scale configurable, instead of 1-10, could be any range the user enters.

**Comment by plibither8** [comment]
Even if manual re-ordering via drag-and-drop is not supported, I think it's essential that optional sorting of notes in a notebook should be allowed. What I mean by that is: the user is supplied with a few default sort methods such as _alphabetical_, _last modified_, _date created_ etc.

An simple implementation which I can quickly think of is a dropdown field with the sort methods.

**Comment by lando-cal** [comment]
> Even if manual re-ordering via drag-and-drop is not supported, I think it's essential that optional sorting of notes in a notebook should be allowed. What I mean by that is: the user is supplied with a few default sort methods such as _alphabetical_, _last modified_, _date created_ etc.
> 
> An simple implementation which I can quickly think of is a dropdown field with the sort methods.

I really tried to love Joplin, I promise!
But the lack of functionality here just wasn't worth the benefits of a preferred not taking syntax for me.  I went back to an alternative product that supports my Nextcloud sources, and I've been happy enough with it that I didn't recall the struggle until I got an email notifying me of your post..

There's a heavy argument to be made, that implenting this kind of stuff is a massive develoent burden on a team that likely has full time jobs to entertain, and it's very valid. Unfortunately, productivity won out in my case.

If you find some sort of workaround that doesn't involve spending more time appending prefixes to items than it does offering an increase in productivity, PLEASE do lete know. The spirit of the project is something I'd love to support, but I can only justify it if I can make it fit my usecase.

**Comment by silverark** [comment]
Priority sounds like a separate feature/option for sorting, which would still be useful but which could be as an alternative sorting method. 

Another quick fix, rather than the drag and drop would be options in the Right click menu for "Move Up" and "Move Down" so custom order is selected. You could then have shortcut keys to move the item up and down using Ctrl + Up or Ctrl and Down. That would work for me.

**Comment by Alkanov** [comment]
As a new Joplin user (loving it) we def need sorting. I honestly don't know how this has been stale for so long.

**Comment by jeppling** [comment]
If drag-n-drop hard to implement, how about ability to select a note and then have buttons for moving the note up or down in the note list?

**Comment by bernieke** [comment]
I for one am happy with the current note sort order options. The only thing missing for me would be to have the option (like in the evernote desktop client, windows explorer, solid explorer on android, ...) to have a separate sort order per notebook. Some notebooks I use as information dumps, where it makes most sense to see the last updated or created on top. Others are structured and would be sorted by Title. It would save me from having to change the sort order each time I switch between the different kinds of notebooks :)

**Comment by Rclardy** [comment]
So far I enjoy the note taking experience. Would like to be able to move notes up and down with in a notebook though.

**Comment by RelativeParadox** [comment]
Manual sort order is essential for functionality, even if it is just a keybinding to move the note up or down in the list. I also agree with bernieke, notebook by notebook configuration would be nice, is there anyone working on either?

**Comment by jabbalaci** [comment]
I tries Joplin for the first time and after writing a test note it was the first thing that I tried and failed to do. And I ran into this issues in the first 5 minutes. Not a good start with a new software :(

**Comment by JRamonB** [comment]
As a longtime Evernote & Linux user, it was a big & welcoming surprise to know Joplin and its multiplataform capability with almost all the characteristics & functions of Evernote.

But related to this topic, I missed the sort order of tasks by alarm date-hour. It would be helpful to see the things that have to be done first.

Thank you very much and congratulations to the team.
