### ISSUE TITLE
Windows build for 1.0.90 could not startup

### ISSUE THREAD

**Issue by ccstanley** [laurent22/joplin#510]
### Operating system
- Windows

### Application
- Desktop

Just downloaded the build for 1.0.90 https://github.com/laurent22/joplin/releases/download/v1.0.90/Joplin-1.0.90.exe and started it. It prompts error and I'm not able to use it:
![default](https://user-images.githubusercontent.com/24431739/39874095-66674640-549f-11e8-9d82-8333a46a7239.png)

Tried 1.0.89 and it works fine.

**Comment by laurent22** [comment]
Forgot to remove a reference to a now missing file. This will be fixed in the next release coming soon.
