### ISSUE TITLE
Sync error with June 16 Android app using WebDAV

### ISSUE THREAD

**Issue by markNZed** [laurent22/joplin#5104]
I have Joplin running on several clients using WebDAV. When adding a new Android client I get an error in the app:

409 Conflict: PUT parent must be a collection

Older android client continues to work with the same configuration (URL/username/password) so I guess an update to the Joplin android client has broken backward compatibility for WebDAV? 

Unfortunately this makes Joplin unusable on the new device.

**Comment by JackGruber** [comment]
When a new issue is opened, a template is included with a handful of questions that should be filled out and not simply ignored.

**Comment by markNZed** [comment]
Closed as above
