### ISSUE TITLE
some translated strings are not shown in UI

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#5109]
## Environment

Joplin 2.1.3 (dev, darwin)

Client ID: e354a932e6e143c782264aad4112b674
Sync Version: 2
Profile Version: 39
Keychain Supported: Yes

Revision: 5ecb870ff (dev)

Although I don't think it is OS specific.

## Steps to reproduce

1. open Joplin
2. select `Danish` as the language in preferences
3. check the menu:

<img width="181" alt="image" src="https://user-images.githubusercontent.com/223439/122790060-f2beb580-d285-11eb-95a1-2175c4471ecf.png">

The same is true for other strings, e.g. `Command palette`.

However, these string are in the `.po` and `.json` files. So the translations are definitely there.

`lib/locales/da_DK.json`:

```
[snip]   ,"Goto Anything...":"Gå til tilfældig...",   [snip]
```

`tools/locales/da_DK.json`:

```
#: packages/app-desktop/plugins/GotoAnything.js:471
#: packages/app-desktop/gui/KeymapConfig/utils/getLabel.js:20
msgid "Goto Anything..."
msgstr "Gå til tilfældig..."
```

## Describe what you expected to happen

The string `Goto Anything...` should be shown in Danish.

## Logfile

There's nothig in the log file that indicates a problem. :-(

**Comment by laurent22** [comment]
Yes this came up a few times but due to the strange way Goto Anything is implemented, it's not currently possible to translate these strings. I think its code would have to be cleaned up a bit first.

**Comment by tessus** [comment]
Thanks for the info, but what about the other strings e.g. `Command palette`? Or is this the same thing?

**Comment by laurent22** [comment]
Yes it's the same thing, both are defined by the Goto Anything class.

**Comment by tessus** [comment]
Ok, shall I close this issue then?

**Comment by laurent22** [comment]
Yes let's close for now. It will be solved when Goto Anything is refactored.
