### ISSUE TITLE
Stable and Beta Channels?

### ISSUE THREAD

**Issue by kevinmickey** [laurent22/joplin#511]
Given the frequency of releases, would it be possible to send releases first to "beta" and then to "stable"?  In options, users could opt into receiving notifications of a new beta release, but otherwise users would only receive notifications of stable releases.

See:

https://github.com/electron-userland/electron-builder/blob/master/docs/tutorials/release-using-channels.md

https://blog.atom.io/2015/10/21/introducing-the-atom-beta-channel.html

**Comment by laurent22** [comment]
An additional release channel is unfortunately not possible given the limited resources of the project (unlike Joplin, Atom have full time employees and the backing of a major company so they can afford multiple channels).

To receive less updates, it's recommended to simply disable the auto-updates and manually update the app from time to time.
