### ISSUE TITLE
Joplin Server 404 On Mobile IOS & Android

### ISSUE THREAD

**Issue by cnburke** [laurent22/joplin#5116]
Joplin Server 404 not found when using the "Check synchronization configuration" button in the options. Server still working correctly from desktop app.  Previously working configuration for both iOS and Android, not sure what changed. I tried uninstalling/reinstalling on both iOS and Android, no dice. Checked my user login via the desktop app, and that
 works fine. Checked that I could access the URL via browser on the Android and iOS device, and that also works fine, so I'm left with believing that Joplin itself is failing. 

Versions used listed below:

Joplin Server: 1.6.4
Desktop: 1.6.7
Android: 2.0.2
iOS: 12.0.2

Log screenshot from iOS (iPad)
![BAE5D0C1-2F12-431F-8E3A-D98184205EF3](https://user-images.githubusercontent.com/22404077/123172746-314d9f00-d443-11eb-934a-ae1051901237.png)

**Comment by JackGruber** [comment]
Please update your Joplin server and clients to the newst version!

**Comment by cnburke** [comment]
@JackGruber I mean, come on…That’s not really a solution. For me to do that (according to the docs), I’ll need to re-upload everything and migrate. I mean no offense, but this seems like the equivalent of “unplug it and plug it back in” answer…

**Comment by JackGruber** [comment]
Sorry, but the Joplin server is a beta/pre-release and no stable release!
So to get errors fixed you have to go with the pre-release versions for your server and clients.

**Comment by JackGruber** [comment]
and the combination of v1 and v2 clients/server is incompatible!

**Comment by cnburke** [comment]
So you’re saying this is due to incompatibility from the Joplin mobile apps, which I’m assuming auto-updated?

**Comment by laurent22** [comment]
As Jack mentioned Joplin Server is in beta state, and if you use beta software you can expect this kind of problems now and then. This, and the incompatibility issue has been pinned to GitHub and the forum for several weeks, and it's explained why there's no choice but to have this breaking change.
