### ISSUE TITLE
Notebook sorting by title does not take number into account, takes every digits insteads

### ISSUE THREAD

**Issue by noahboegli** [laurent22/joplin#5117]
Sorting of notebook by title does not take number into account (it takes individual digits into account)

![image](https://user-images.githubusercontent.com/39568628/123177272-39c6c980-d485-11eb-851a-024054f1317e.png)

## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: ArchLinux

## Steps to reproduce

1. Create a notebook called "Chapter 2"
2. Create a second notebook called "Chapter 10"
3. See the "Chapter 10" being before of "Chapter 2"

## Describe what you expected to happen
I expect the  notebook "Chapter 10" to be after the notebook "Chapter 2".

## Logfile
none

**Comment by ritwik-boringnews** [comment]
hi can i work on this issue

**Comment by roman-r-m** [comment]
Go for it, no need to ask

**Comment by ritwik-boringnews** [comment]
sure sir thanks .you can assign me if u want

**Comment by CalebJohn** [comment]
An example of this sort of fix can be seen in [the template plugin](https://github.com/joplin/plugin-templates/pull/34/files)

A [hint](https://github.com/laurent22/joplin/search?q=localeCompare) for getting started on this bug.

**Comment by madrix01** [comment]
Is someone working on this issue? If not can I work on it ?

**Comment by CalebJohn** [comment]
Absolutely, go ahead @madrix01

**Comment by qiuwch** [comment]
Why not use chapter 02, rather than doing chapter 2?

I don't think adding complexity for this is a good idea. Sorting by number will involve splitting the text into tokens, detect what is a number, and mix the sorting of characters and numbers. These are not difficult, but will certainly increase the code complexity; potentially make the program slower and introduce more bugs.

**Comment by CalebJohn** [comment]
@qiuwch I understand where you're coming from, but in this case it's just toggling an option on a built-in JavaScript sorting function. It should be trivial.

**Comment by madrix01** [comment]
Yes, it just do same sorting as earlier we just have to add some tweaks, it won't increase the complexiety

**Comment by madrix01** [comment]
![image](https://user-images.githubusercontent.com/51414879/130243947-8e76ffaa-58a5-461a-b1dc-e982609e8454.png)
I added a sort with ```localeCompare``` with ```{sensitivity: 'accent', numeric: true}``` to the ```render()``` method in ```sideBar.tsx```

**Comment by CalebJohn** [comment]
@madrix01 I'm surprised that you needed to edit sidebar.tsx, but i can't really comment on it without seeing the code. Please make a PR.

**Comment by madrix01** [comment]
I have created PR #5358 Can you please point out changes
