### ISSUE TITLE
Feature Request: Sync Delta log/Timeline

### ISSUE THREAD

**Issue by Immortalin** [laurent22/joplin#512]
Many applications like github and thunderbird have a log of changes that can be inspected to ensure one did not accidentally delete something etc. This also helps with security. Since Joplin already have timestamps and sync., it should be trivial to log the deltas etc.

**Comment by laurent22** [comment]
Joplin already logs a lot of info. You can log more by setting the log level to "debug" as described there: http://joplin.cozic.net/debugging/
