### ISSUE TITLE
search filter doesn't work

### ISSUE THREAD

**Issue by jaegyo** [laurent22/joplin#5120]
After update Ver. 2.1.5, when I input a [char] in the search filter, 
and then the [char] disappears in the search filter

## Environment
Joplin 2.1.5 (prod, win32)

Sync Version: 2
Profile Version: 39
Keychain Supported: Yes

## Steps to reproduce

1. place the mouse cursor on the search filter
2. keyin  [some char]
3. [some char] disappers in the search filter

**Comment by laurent22** [comment]
Any error in the console? https://joplinapp.org/debugging

And do you use any plugin?

**Comment by jaegyo** [comment]
> Any error in the console? https://joplinapp.org/debugging
> 
> And do you use any plugin?

**Comment by jaegyo** [comment]
thank your @laurent22 
i find error with `outline v1.1.7`, plugins

console log show me many information. thanks.
