### ISSUE TITLE
Hyperlinks / Links are not clickable in WYSIWYG Editor

### ISSUE THREAD

**Issue by franciskcso** [laurent22/joplin#5121]
## Environment

Joplin version: 2.0.11
Platform: Windows 64 bit
OS specifics: 10.0.19043 Build 19043

https://user-images.githubusercontent.com/6107137/123524366-f176f980-d686-11eb-9551-004837661230.mp4

## Steps to reproduce

1. Create a link to a note in Joplin in the Markdown editor.
2. If the Markdown editor is on, the link seems to work in the preview.
3. However, toggling the Markdown editor off, the link no longer seem to work.

## Describe what you expected to happen
I expected the link behaviour to continue to work when toggling the editors.  This is similar to this [forum post](https://discourse.joplinapp.org/t/hyperlinks-dont-open-a-browser-window-in-rich-text-editor/15892). However, after more experimentation I noticed the "toggle editor layout" seems to fix this issue. Is this behaviour intentional? Like, one of the screens is suppose to represent the WYSIWYG editor while clicking the "toggle editor layout" seems to change it to a rendered view.

**Comment by JackGruber** [comment]
Please right click and use open or use `Strg` and click.

**Comment by laurent22** [comment]
Also just to be sure, upgrade to the latest version

**Comment by franciskcso** [comment]
## Environment

Joplin version: 2.0.11
Platform: Windows 64 bit
OS specifics: 10.0.19043 Build 19043

I hope this is, the latest version as Joplin just asked to update. So I updated to 2.0.11 and the link behaviour is the same. Essentially, if you hit "Toggle editors" button, the link in the Markdown / WYSIWYG editor follows through. However, the only way to make the link click through when using the WYSIWYG is to hit "Toggle editor layout" Is this the intended behaviour or is this a bug?

https://user-images.githubusercontent.com/6107137/123561256-8996e080-d764-11eb-97bd-0b2255a00388.mp4

**Comment by JackGruber** [comment]
Yes this behaviour is so intended WYSIWYG editor. Because if a click opens the link, it could not be edited. 

You have to option, as I wrote:

1. Right click on the link and use the open menue
![grafik](https://user-images.githubusercontent.com/24863925/123580405-1039d500-d7da-11eb-8847-7d7b6a7e4573.png)
2. Hold the `Ctrl`/`Strg` key and click on the link
