### ISSUE TITLE
Resources not deleted / sync error

### ISSUE THREAD

**Issue by baek-sang** [laurent22/joplin#5126]
`~joplin-desktop\resources` directory
Not deleted resource.

Even if there is no item, try uploading and processing is completed. 
![sync1](https://user-images.githubusercontent.com/69100154/123570335-f5c82180-d802-11eb-8d2c-269de7da38b2.png)

## Environment

Joplin version: Desktop 2.1.7 / Server 2.1.6-beta
Platform: Windows 10
OS specifics: CentOS 8.4, Docker

## Steps to reproduce

1. Disable note history
![jjjjjj](https://user-images.githubusercontent.com/69100154/123569903-2bb8d600-d802-11eb-8364-ccd9b9846420.png)

2. Delete note/notebook
3. Click Synchronise

## Describe what you expected to happen
Deleted resource(image file)
Do not upload(sync) item

**Comment by JackGruber** [comment]
I think I read in the forum that roman wrote that if 0 is entered, a default value of 24 is used. 
But I am not sure right now.
