### ISSUE TITLE
[Feature Request] Quick access to notebooks in Android

### ISSUE THREAD

**Issue by archont00** [laurent22/joplin#513]
### Operating system
- Android

### Application
- Mobile

### Switching among available notebooks
Currently, the user has to open left-side menu to get an access to the available notebooks.
It would be faster to simply have a drop-down list when the user taps on the notebook name in the title bar.
("Welcome" might be replaced by "All", which would show notes from all the notebooks in the main pane. Relates to https://github.com/laurent22/joplin/issues/262.)

**Comment by foxmask** [comment]
I'd prefered the welcome screen with some info about my notes (the reminders to come, the total of notes I created, etc... ) and about the actual joplin version.
So may be a shortcut "all notes" in additionnal of my wish :)

**Comment by archont00** [comment]
I do not recall exactly how it worked before, however, the current status is that tapping on the "three lines" menu icon (placed left to the current notebook title)  directly opens list of notebooks (and "All notes"), hence the functionality is close to the original request and I consider it fixed.
