### ISSUE TITLE
clipper does not remember notebook

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#5130]
## Environment

Joplin version: 2.1.7
Platform: macOS
OS specifics: Mojave, Catalina
Clipper: 2.1.2 (Chrome, Firefox)

## Steps to reproduce

1. open clipper
2. choose a notebook 
3. clip page
4. open clipper again
5. notebook has not been remembered and the first one (alpabetically) is picked

## Describe what you expected to happen

The clipper should remember the last notebook used.

This worked before and looks like a regression.

## Logfile

no errors in the log file or console

**Comment by laurent22** [comment]
In both Chrome and Firefox?

**Comment by tessus** [comment]
Yes
