### ISSUE TITLE
The latest ios app is failed to sync with joplin-server

### ISSUE THREAD

**Issue by xzlxiao** [laurent22/joplin#5131]
## Environment

Joplin version: 12.0.2
Platform: ios
Server version: unknown, it was installed before 2021-03-16 

## Steps to reproduce

When I synchronized the ios app with version 12.0.2, it got error info -- Not allowed: PUT (Code 400). The old version of desktop and android are fine, such as version 1.7.11. The latest version on desktop and android were not tested yet.

**Comment by JackGruber** [comment]
Please update your Joplin server and clients to the newst version!
V2 clients can only sync with v2 server and v1 clients only with a old v1 server.
