### ISSUE TITLE
Cannot find module './ElectronAppWrapper'

### ISSUE THREAD

**Issue by Philipp91** [laurent22/joplin#5136]
## Environment

Joplin version: `dev` branch
Platform: Linux Mint, Node v16

## Steps to reproduce

1. Do what's listed in https://github.com/laurent22/joplin/blob/dev/BUILD.md:
2. Install Node and `sudo apt install libnss3 libsecret-1-dev python rsync`
3. Clone repo, then `npm install`. This resulted in:
```
...
lerna info lifecycle @joplin/app-clipper@1.0.8~postinstall: Failed to exec postinstall script

> @joplin/app-desktop@2.1.7 postinstall /home/philipp/repos/joplin/packages/app-desktop
> npm run build

npm ERR! code 1
npm ERR! path /home/philipp/repos/joplin
npm ERR! command failed
npm ERR! command sh -c npm run bootstrap --no-ci && npm run build

npm ERR! A complete log of this run can be found in:
npm ERR! ..../2021-06-28T12_00_11_416Z-debug.log (attached to this post)
```
That's already an error, but I ignored it given that `npm run build` works fine inside the `packages/app-desktop` directory.

4. `cd packages/app-desktop`
5. `npm start` fails with:

```
Error: Cannot find module './ElectronAppWrapper'
Require stack:
- /home/philipp/repos/joplin/packages/app-desktop/main.js
- /home/philipp/repos/joplin/packages/app-desktop/node_modules/electron/dist/resources/default_app.asar/main.js
- 
```

Indeed, only `ElectronWrapper.ts` exists, but not `.js` or `.min.js`. For `.jsx` and `.tsx` files in subdirectories, the corresponding `.js` file has been built, but not for `.ts` files. Is that intentional (is the expectation that node can load `.ts` files directly) or not (should the `.ts` files be compiled too)?

## Describe what you expected to happen

Application starts without error when I use the provided instructions.

## Logfile

[joplin-start-error.txt](https://github.com/laurent22/joplin/files/6743623/joplin-start-error.txt)

[2021-06-28T12_00_11_416Z-debug.log](https://github.com/laurent22/joplin/files/6743626/2021-06-28T12_00_11_416Z-debug.log)

**Comment by Philipp91** [comment]
I found that executing `npm run build` in the repository root results in those `.ts` files being compiled. If I _then_ return to the app-desktop directory, `npm start` works fine there.

So either this was caused by the postinstall hook failing, or there's a step missing in the instructions, _or_ the `npm run build` command wrongly doesn't build `.ts` files when executed from the subdirectory.

**Comment by roman-r-m** [comment]
```
1 info using npm@7.11.2
2 info using node@v16.0.0
```

I think it may be either one of these versions or their combination that's causing this. Try with npm 6 and note 12 or 14.

**Comment by laurent22** [comment]
Yes it's better to try to fix the Lerna error, as you might have issues if you try to run npm scripts from /app-desktop. For sure `npm i` will break, but possibly other scripts too like `npm run build` because it's not supported.

**Comment by Philipp91** [comment]
Related question: When I change (for example) the file `./packages/app-desktop/TinyMCE.tsx` and then run `npm start` or even `npm run build` in that directory, it does _not_ update `TinyMCE.js`. Isn't that supposed to happen? Does it happen on your machine? When I go to the repository root and execute `npm run build` _there_, it updates `TinyMCE.js` in the subdirectory.

**Comment by roman-r-m** [comment]
> Related question: When I change (for example) the file `./packages/app-desktop/TinyMCE.tsx` and then run `npm start` or even `npm run build` in that directory, it does _not_ update `TinyMCE.js`. Isn't that supposed to happen? Does it happen on your machine?

Haven't tried `npm run build` but `npm start` does not compile TypeScript for me either. I usually do `npm run tsc && npm start`.
I know there's also `npm watch` that watches for changes and recompiles automatically but for some reason I keep going back to compiling manually

**Comment by laurent22** [comment]
> Related question: When I change (for example) the file ./packages/app-desktop/TinyMCE.tsx and then run npm start or even npm run build in that directory, 

As I mentioned running scripts from the app-desktop (other than npm start) is not recommended, and will lead to many small issues like these. Read BUILD.md a second time maybe as everything is in there, including how to watch TypeScript files, how to install packages using Lerna, etc.

**Comment by Philipp91** [comment]
Thanks. According to the documentation, it's `npm run watch`, and indeed that works from either directory.

**Comment by laurent22** [comment]
> and indeed that works from either directory

Yes but my point is that it should be ran from the root. If you run it from app-desktop, then modify a lib file you'll be surprised again why that file hasn't been compiled. To avoid anything unexpected running things from root is better, and that's why only this is documented.
