### ISSUE TITLE
View starts at top, Edit (still) at bottom

### ISSUE THREAD

**Issue by gitoss** [laurent22/joplin#5140]
Please re-open bug ticket https://github.com/laurent22/joplin/issues/2287

## Environment

Joplin version: 2.0.13
Platform: Android
OS specifics: Q

## Steps to reproduce

1. Look at https://github.com/laurent22/joplin/pull/4998#issuecomment-8691993522

Thanks!

**Comment by laurent22** [comment]
Re-opened
