### ISSUE TITLE
Unknown error when posting various notes

### ISSUE THREAD

**Issue by jeffabailey** [laurent22/joplin#5144]
## Environment

Joplin version: 2.1.7
Platform: macOS
OS specifics: Big Sur

## Steps to reproduce

1. Try posting the note in this attached error stack while using Joplin Server 2.1.6-beta as the sync target
2. [error-stack.txt](https://github.com/laurent22/joplin/files/6749918/error-stack.txt)

## Describe what you expected to happen

No sync error

## Logfile

[log.txt.zip](https://github.com/laurent22/joplin/files/6750306/log.txt.zip)

**Comment by maxtruxa** [comment]
Relevant log snippet:
```
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 10:17:25: Error: Unknown error: 
    at newError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:191)
    at JoplinServerApi.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:231)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:5)
...
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 10:17:25: Details: PUT api/items/root:/4974f7bdedcc40b1a24512507d03030e.md:/content: Unknown error:  (400): 
```

I haven't looked very far, but the error originates [here](https://github.com/laurent22/joplin/blob/d34a92d581773ff1f39b51f8eb09c3e1222ed9b2/packages/lib/JoplinServerApi.ts#L234). The server seems to respond with status code of 400 and an empty body. If the source of that response is the Joplin server or a reverse proxy as hinted at by the comment in the source, I can't say.

Are you running Joplin server behind a reverse proxy (Caddy, Nginx, ...) and can you look at/provide their logs?

**Comment by jeffabailey** [comment]
I am running it in a container and am accessing the server directly.

**Comment by maxtruxa** [comment]
Could you post the server logs? You can export logs from Docker with something like this:
```sh
sudo docker logs $(sudo docker ps -q -f ancestor=joplin/server:2.1.6-beta) >joplin-server.log
```

**Comment by jeffabailey** [comment]
Hi, the log.txt.zip at the bottom of the issue description has the logs from the container.

https://github.com/laurent22/joplin/files/6750306/log.txt.zip

**Comment by jeffabailey** [comment]
I upgraded to the 2.1.8 client, and it appears to have fixed the issue after clicking **Re-upload local data to sync target**. I'll keep this open for a while to see if the problem comes back in the next several days.

**Comment by jeffabailey** [comment]
It has been stable the past several days.
