### ISSUE TITLE
When phone is in hebrew interface, main menu is not aligned properly

### ISSUE THREAD

**Issue by skliarie** [laurent22/joplin#5148]
My wife uses her phone using  hebrew (LTR) interface.
She created several notebooks that have hebrew names.
When main menu is opened, the names of hebrew notebooks are aligned properly (only ending is  visible) - see the screenshot.
Also, third of screen (on the left) remains empty, for no obvious reason, probably related.
![joplin_hebrew_ui_bug](https://user-images.githubusercontent.com/165600/124235112-8bbebd80-db1d-11eb-811f-1540ac5cc52d.jpg)

If the phone is switched to english mode, names of hebrew notebooks are visible properly:
![joplin_hebrew_ui_bug_english_mode](https://user-images.githubusercontent.com/165600/124235188-9f6a2400-db1d-11eb-803e-946a6d32dad7.jpg)

Language of joplin UI does not matter:
![joplin_hebrew_ui_bug_english_ui](https://user-images.githubusercontent.com/165600/124244226-620a9400-db27-11eb-84eb-7c246ab9396e.jpg)

## Environment

Joplin version 2.1.3
Android 10

## Steps to reproduce

1. Create notebook with hebrew name, for example this:
זה שם של נוטהבוק בעברית
2. Switch phone to hebrew mode
3. Run Joplin and switch to main menu

**Comment by skliarie** [comment]
It is still relevant..

**Comment by skliarie** [comment]
It is still relevant..

**Comment by tzvi11** [comment]
I also still have the same problem on Android and in fact you can not see the names of the notebooks ...

**Comment by skliarie** [comment]
It is still relevant..
