### ISSUE TITLE
Installing npm package fails due to vulnerability

### ISSUE THREAD

**Issue by nhumrich** [laurent22/joplin#515]
### Operating system

- Linux

### Application

- Desktop
- Terminal

Trying to install via the arch pkgbuild, which is installing joplin via npm, from the looks of it. During the npm install phase, I get this error:
```
npm WARN tools@1.0.0 No description
npm WARN tools@1.0.0 No repository field.

added 23 packages from 32 contributors in 0.769s@1.0.0 No repository field.
[!] 1 vulnerability found [27 packages audited]
    Severity: 1 high
    Run `npm audit` for more detail

npm ERR! write after end

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nhumrich/.npm/_logs/2018-05-11T15_36_48_765Z-debug.log
==> ERROR: A failure occurred in build().
    Aborting...

```

**Comment by foxmask** [comment]
Why not trying to update the packages reported bythe npm audit command?

**Comment by laurent22** [comment]
This seems to be specific to this Linux distro so out of scope for the project.
