### ISSUE TITLE
Can't start joplin desktop

### ISSUE THREAD

**Issue by oliversturm** [laurent22/joplin#5151]
## Environment

Joplin version: 2.1.7
Platform: Linux
OS specifics: Arch, using Sway (Wayland)

## Steps to reproduce

1. Install either the joplin-desktop or joplin-appimage package from AUR - I tried both, the result was the same
2. Attempt to run `joplin-desktop` or `/opt/appimages/Joplin.AppImage`. I tried all steps with both commands, there is no difference in the outcome.

At first, I received this error message:

```
> joplin-desktop
(@joplinapp-desktop:1847143): Gtk-WARNING **: 12:09:21.866: cannot open display: :0
```

`DISPLAY` is set to `:0` - and it works correctly with xwayland - I can run `xeyes` as a test, no problem.

However, I attempted to unset `DISPLAY` and run again. Now I saw a different error:

```
> DISPLAY= joplin-desktop
The futex facility returned an unexpected error code.
[1]    1853512 abort (core dumped)  DISPLAY= joplin-desktop
```

I saved the core dump, in case it helps - please let me know. Here is the "info" from the dump:

```
           PID: 1853512 (@joplinapp-desk)
           UID: 1000 (sturm)
           GID: 1000 (sturm)
        Signal: 6 (ABRT)
     Timestamp: Fri 2021-07-02 12:15:31 BST (12min ago)
  Command Line: /tmp/.mount_joplinhYVBDS/@joplinapp-desktop
    Executable: /tmp/.mount_joplinhYVBDS/@joplinapp-desktop
 Control Group: /user.slice/user-1000.slice/session-5.scope
          Unit: session-5.scope
         Slice: user-1000.slice
       Session: 5
     Owner UID: 1000 (sturm)
       Boot ID: 853dd81f76b747a8bd8398766469188d
    Machine ID: a7c5c4eac0f3459b949726faf245bb7b
      Hostname: odm1
       Storage: /var/lib/systemd/coredump/core.@joplinapp-desk.1000.853dd81f76b747a8bd8398766469188d.1853512.1625224531000000.zst (present)
     Disk Size: 4.7M
       Message: Process 1853512 (@joplinapp-desk) of user 1000 dumped core.

                Stack trace of thread 1853512:
                #0  0x0000642a924cfd22 raise (libc.so.6 + 0x3cd22)
                #1  0x0000642a924b9862 abort (libc.so.6 + 0x26862)
                #2  0x0000642a92511d28 __libc_message (libc.so.6 + 0x7ed28)
                #3  0x0000642a92511d5a __libc_fatal (libc.so.6 + 0x7ed5a)
                #4  0x0000642a93e21f05 sem_post@@GLIBC_2.2.5 (libpthread.so.0 + 0x11f05)
                #5  0x000009c8a62e1460 n/a (/tmp/.mount_joplinhYVBDS/@joplinapp-desktop + 0x7743460)
                #6  0x000009c8a0570ee7 n/a (/tmp/.mount_joplinhYVBDS/@joplinapp-desktop + 0x19d2ee7)
                #7  0x000009c8a0573fae n/a (/tmp/.mount_joplinhYVBDS/@joplinapp-desktop + 0x19d5fae)
                #8  0x000009c8a04f26d9 n/a (/tmp/.mount_joplinhYVBDS/@joplinapp-desktop + 0x19546d9)
                #9  0x000009c8a04f27ce n/a (/tmp/.mount_joplinhYVBDS/@joplinapp-desktop + 0x19547ce)
                #10 0x000009c8a1ebd8ec n/a (/tmp/.mount_joplinhYVBDS/@joplinapp-desktop + 0x331f8ec)
                #11 0x000009c8a1ebd9fe n/a (/tmp/.mount_joplinhYVBDS/@joplinapp-desktop + 0x331f9fe)
                #12 0x000009c8a1ec2242 n/a (/tmp/.mount_joplinhYVBDS/@joplinapp-desktop + 0x3324242)
                #13 0x000009c8a1ec1d38 n/a (/tmp/.mount_joplinhYVBDS/@joplinapp-desktop + 0x3323d38)
                #14 0x000009c8a1ebd450 n/a (/tmp/.mount_joplinhYVBDS/@joplinapp-desktop + 0x331f450)
                #15 0x000009c8a1d99630 n/a (/tmp/.mount_joplinhYVBDS/@joplinapp-desktop + 0x31fb630)
                #16 0x000009c8a1d990ab n/a (/tmp/.mount_joplinhYVBDS/@joplinapp-desktop + 0x31fb0ab)
                #17 0x000009c8a3f32eaf n/a (/tmp/.mount_joplinhYVBDS/@joplinapp-desktop + 0x5394eaf)
                #18 0x000009c8a10956f1 n/a (/tmp/.mount_joplinhYVBDS/@joplinapp-desktop + 0x24f76f1)
                #19 0x000009c8a04413bd n/a (/tmp/.mount_joplinhYVBDS/@joplinapp-desktop + 0x18a33bd)
                #20 0x0000642a924bab25 __libc_start_main (libc.so.6 + 0x27b25)
                #21 0x000009c8a04410ea n/a (/tmp/.mount_joplinhYVBDS/@joplinapp-desktop + 0x18a30ea)
```

**Comment by laurent22** [comment]
That should be reported on the AUR package issue tracker, as we don't maintain this release here.

**Comment by oliversturm** [comment]
I considered that, but I understand that the package joplin-appimage just repackages the AppImage created by you - so I decided this was the right place for the report.

**Comment by oliversturm** [comment]
I just tested it to help you out - this is the AppImage I just downloaded from [this link](https://github.com/laurent22/joplin/releases/download/v2.1.7/Joplin-2.1.7.AppImage).

```
> mv Joplin-2.1.7.AppImage Joplin-2.1.7-direct-download.AppImage

> chmod +x Joplin-2.1.7-direct-download.AppImage

> ./Joplin-2.1.7-direct-download.AppImage

(@joplinapp-desktop:1863023): Gtk-WARNING **: 12:42:53.567: cannot open display: :0

> DISPLAY= ./Joplin-2.1.7-direct-download.AppImage
The futex facility returned an unexpected error code.
[1]    1863200 abort (core dumped)  DISPLAY= ./Joplin-2.1.7-direct-download.AppImage
```

**Comment by oliversturm** [comment]
I have found a workaround:

```
> GDK_BACKEND=x11 XDG_SESSION_TYPE=x11 QT_QPA_PLATFORM=xcb SDL_VIDEODRIVER=x11 WINIT_UNIX_BACKEND=x11 SWAYSOCK= WAYLAND_DISPLAY= DISPLAY=:0 ./Joplin-2.1.7-direct-download.AppImage
```

I don't know right now which of the variables makes the big difference - I had all these accumulated for other scenarios where I was running an app explicitly on a Xephyr server. Obviously, they work together to make sure that the Electron app runs correctly on the X server on display `:0`.

Now, this does not explain why this is necessary. I use various Electron apps on a daily basis, and none of them requires any such settings. Some of them work pretty well with Wayland now (passing ` --enable-features=UseOzonePlatform --ozone-platform=wayland` - I did try this with Joplin btw, but it didn't make a difference), some others have trouble with this but run on Xwayland without issues.

**Comment by roman-r-m** [comment]
> Now, this does not explain why this is necessary. I use various Electron apps on a daily basis, and none of them requires any such settings.

Looks like Electron only started to support wayland from version 12.0. Joplin's on 10.x, maybe the other apps use newer versions.

**Comment by oliversturm** [comment]
> Looks like Electron only started to support wayland from version 12.0. Joplin's on 10.x, maybe the other apps use newer versions.

Well, before Electron introduced Wayland support - as you say, not long ago - all of the apps I use were running against Xwayland - just like any other X app. That's basically what happens in my workaround scenario as well, only I don't know why Joplin (maybe together with its Electron version?) has the unique (in my experience) requirement to see all relevant environment variable initialized as if Wayland didn't exist at all. 

In any case, interesting point about Electron there. What are the plans for an update to a current Electron version? Using latest Electron with Wayland support, high-dpi environments can take great advantage - running in Xwayland, Joplin currently looks pretty horrible on my 4k screen.
