### ISSUE TITLE
Sync arrows turn in the wrong direction - Android

### ISSUE THREAD

**Issue by NiceYoyo** [laurent22/joplin#5154]
The sync arrows on android are turning in the wrong (left) direction...possibly the lowest priority bug in history, but it strikes me since day one xD.

## Environment

Joplin version: 2.1.4 (also below)
Platform: Android
OS specifics: LineageOS 18.1 (Android 11)

## Steps to reproduce

1. Open Joplin App
2. Sync

## Describe what you expected to happen

The arrows turning in the right direction.

## Logfile
 I don't assume it is needed.

**Comment by JackGruber** [comment]
There is an open issue for this: #5026

**Comment by NiceYoyo** [comment]
Totaly my bad, should I close this issue?
