### ISSUE TITLE
Joplin cannot sync with nextcloud(Sabre/dav error)Sync loop

### ISSUE THREAD

**Issue by alexander-lamdan** [laurent22/joplin#5159]
Hello, Joplin cannot sync between 3 devices(2 pc and 1 android phone) from nextcloud.

Sync looped, I can't even cancel it. 

Last sync was in 12:00 moscow time.

There is the screenshots of errors from dev tools
![05-07-июля-Понедельник-22-22-45](https://user-images.githubusercontent.com/38505847/124503997-0dde0900-dde0-11eb-9b46-b642780aaeac.png)
![05-07-июля-Понедельник-22-23-58](https://user-images.githubusercontent.com/38505847/124504010-10d8f980-dde0-11eb-9dec-ddbe0f59d61f.png)

**Comment by roman-r-m** [comment]
Looks like a Nextcloud issue. I remember someone mentioned you need to set up Nextcloud to use redis for locking otherwise it's very unreliable. You may want to check this.

**Comment by alexander-lamdan** [comment]
> Looks like a Nextcloud issue. I remember someone mentioned you need to set up Nextcloud to use redis for locking otherwise it's very unreliable. You may want to check this.

But how? I don't have my own nextcloud server.

I using nextcloud as a cloud

**Comment by roman-r-m** [comment]
As their support then.
