### ISSUE TITLE
notes from sub-notebooks not shown when parent notebook selected

### ISSUE THREAD

**Issue by x-a-a-d** [laurent22/joplin#517]
### Operating system
- Windows
- Android

### Application
- Desktop
- Mobile

When notebook with some sub-notebooks is selected I would expect to see notes from the whole notebooks sub-tree.

**Comment by foxmask** [comment]
For me it is the normal behavior
If you are on sub folder on the filesystem, you dont expect to find all the files of all the sub-dir , do you ?

**Comment by x-a-a-d** [comment]
I'm not sure we should compare it with the raw filesystem, but even file managers (eg. Total Commander) allow you to display files from the whole subtree and it is quite usefull.

But I agree that it depends on a way how you organize your notes:
* notes only in "leaf" notebooks => you expect to see whole subtree otherwise you see nothing and it is useless to have notebook tree at all
* notes also in "node" notebooks => both behaviors make sense

From my point of view the default expected behavior is to display notes from the whole subtree.

**Comment by foxmask** [comment]
I do both, add note on leaf and node, like with Evernote

**Comment by tessus** [comment]
I also use notes in nodes and leafs. I still don't understand the usability of it. When you list all notes for a node and its subnodes, the organization goes down the drain.

What do you do, if you have notes with the same name? How are the notes supposed to be listed? In which format? e.g. node/note1, node2/note1, node2/subnode1/note1? In this case you might have very long names at one point. Also, it's starting to look like a filesystem after all.

Technically it's rather easy to achieve, it's just a tree traversal. And there's recursive SQL if the data is in a databse, although I doubt that sqlite has recursive SQL.
But I seriously doubt its usefulness.

**Comment by foxmask** [comment]
Database engines are able to use B-Tree, like postgresql (even SQLite). Also in the chess World, the opening database use trees too. Si it's not a matter of SQL ;)

**Comment by tessus** [comment]
@foxmask I think you misunderstood. to retrieve all notes of a notebook and its subnotebooks, one can use recursive SQL to retrieve the names of the notes. that is, if the filenames are stored in a database and given that the appropriate relations were set as well.

Please note that my SQL comment was only the second part and meant to show off how cool recursive SQL was. The first part was tree traversal.

Btw, I was in DB2 development for many, many years, so I think I know a little bit about databases and different tree algorithms. ;-)

**Comment by x-a-a-d** [comment]
nice to read the discussion about implementation details of the feature you don't like and don't understand its use case :)

The main use case of selecting whole subtree and not only single node I see when it also behaves as a pre-filter to the search function - currently it doesn't. So we can probably close this issue for now and maybe reopen in the future if the search function is limitted by selected notebook.
