### ISSUE TITLE
Checkboxs still appear but are nonfunctional if markdown is malformed

### ISSUE THREAD

**Issue by saarantras** [laurent22/joplin#5171]
[This issue](https://github.com/laurent22/joplin/issues/4070) is still a problem in the current release, and the bot told me to make a new issue, since the old one is "stale".

## Environment

Joplin version: Joplin 2.1.8 (prod, linux)
Platform: Linux (Desktop)

## Steps to reproduce

1.  Paste the following into a joplin note (**preserving whitspace**)
```
- [ ] CORRECT

-  [ ] INCORRECT

```
2. Switch to dual view : so you can see markdown and the rendered markdown.

3. Click both checkboxes on the right-side rendered view

4. Examine the markdown : CORECT has an ```x``` character inserted in between the square brackets, while INCORRECT does not.

**Note the one space between the - and [ characters in "CORRECT", and the two spaces between the - and [ characters in "INCORRECT".**

## Describe what you expected to happen

I expected either "INCORRECT" to not render as a check box OR for it to render AND function properly. This is a very frustrating bug, because you can make a giant checklist, switch to the rendered view, check a bunch of items, and have them "randomly" uncheck.

**Comment by laurent22** [comment]
Closing this one and re-opening https://github.com/laurent22/joplin/issues/4070
