### ISSUE TITLE
Contagious checkboxes : Rich-text editor destroys mixed-type (check-box & bullet point) lists

### ISSUE THREAD

**Issue by saarantras** [laurent22/joplin#5173]
## Environment

Joplin version: 2.1.8 prod Linux
Platform: Linux

## Steps to reproduce

1. Switch to dual markdown & rendered view
2. Paste the following into the markdown editor
```
- foo
- bar
- [ ] baz
```
3. Notice the expected result in the rendered view : `foo` and `bar` are bulleted, `baz` is checkboxed.
4. Switch to the rich-text editor
5. Notice that all three, `foo`, `bar`, & `baz` are **erroneously checkboxed**.
6. Switch back to markdown editor. Notice that the text has not (yet) changed.
7. Switch back to rich text editor, and click one of the checkboxes.
8. Return to the markdown editor. Notice that the text has become the following:
```
- [ ] foo
- [x] bar
- [ ] baz
```
(with whatever checkbox you clicked selected)

**Comment by laurent22** [comment]
This is a known limitation I'm afraid, as documented: http://joplinapp.org/rich_text_editor/

**Comment by saarantras** [comment]
...Are there any plans to fix this?
