### ISSUE TITLE
Whenever I start the webclipping tool, it shows "Permission required" and nothing else

### ISSUE THREAD

**Issue by badmotorfinger** [laurent22/joplin#5175]
When I start the web clipper in Brave, I get a "Permission Needed" followed by a "Starting..." message and nothing else. There is also no message in Joplin to authorize the web clipper extension.

## Environment

Joplin version: 2.1.8
Platform: Linux Mint
OS specifics: Linux Mint 19.3 Tricia x86_64

## Steps to reproduce

1. Start Brave
2. Start Joplin desktop app
2. Go to https://forum.arduino.cc/t/esp8266-not-responding/517371/3
3. Try to clip

## Describe what you expected to happen

For the web clipper to show me options for clipping

## Logfile

[logs.zip](https://github.com/laurent22/joplin/files/6795987/logs.zip)

**Comment by leematos** [comment]
do you know what version of clipper you are running? I believe 2.1.3 is the latest.

```
021-07-11 07:45:33: "Request: GET /ping"
2021-07-11 07:45:33: "Request: GET /auth/check?token=undefined"
2021-07-11 07:45:33: "Error: Not Found
Error: Not Found
    at Api.route (/tmp/.mount_JoplinRYsU3l/resources/app.asar/lib/services/rest/Api.js:107:41)
    at execRequest (/tmp/.mount_JoplinRYsU3l/resources/app.asar/lib/ClipperServer.js:162:39)
    at Server.<anonymous> (/tmp/.mount_JoplinRYsU3l/resources/app.asar/lib/ClipperServer.js:205:7)
    at Server.emit (events.js:210:5)
    at Server.EventEmitter.emit (domain.js:476:20)
    at parserOnIncoming (_http_server.js:745:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)"
```

This is the error in your logs, and it looks like it's upset about the lack of API token:
https://github.com/laurent22/joplin/blob/dev/packages/lib/services/rest/Api.ts#L116-L131

I'm not sure the call/request/response cycle to auth the clipper.

**Comment by badmotorfinger** [comment]
I downloaded the latest from the chrom store just before posting this issue. I would tell you the version but not at my desk right now.

Any ideas ?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by laurent22** [comment]
What if you restart your computer and try again? It just sounds like the clipper is connecting to an old version of Joplin that might still be running on your computer.

**Comment by laurent22** [comment]
By the way, let's limit the clipper discussions to one place - https://discourse.joplinapp.org/t/web-clipper-2-1-3-not-working/18582
