### ISSUE TITLE
Error: MKCOL locks/: Unknown error 2 (409)

### ISSUE THREAD

**Issue by gmaubach** [laurent22/joplin#5177]
## Error Message

This message appears when synchronizing with a remote host using WebDAV:
-- cut --
Abgeschlossen: 2021-07-11 10:15
Letzte Fehlermeldung: Error: MKCOL locks/: Unknown error 2 (409): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>409 Conflict</title> </head><body> <h1>Conflict</h1> <p>The server encountered an internal error or misconfiguration and was unable to complete your request.</p> <p>Please contact the server administrator at service@webmailer.de to inform them of the time this error occurred, and the actions you performed just before this error.</p> <p>More information about this error may be ava
-- cut --

## Environment

Joplin version: Joplin 1.5.14 (prod, linux), Sync-Version: 2, Profil-Version: 34, Unterstützter Schlüsselbund: Nein, Revision: 9e076bf (master)
Platform: Linux
OS specifics:  Ubuntu Linux 20.04 LTS, 5.8.0-59-generic, amd64

## Steps to reproduce

1. Create a document in JoplinApp using the attached file 
[2021-07-11_JoplinApp_Doc-producing-error-when-syncing.txt](https://github.com/laurent22/joplin/files/6796579/2021-07-11_JoplinApp_Doc-producing-error-when-syncing.txt)
2. Sync with a remote repository over WebDAV

## Describe what you expected to happen

Please check if the error is reproducable and tell if the syncing process fails in a way that I risk data loss.

## Logfile

Please find attached.
[log.txt](https://github.com/laurent22/joplin/files/6796578/log.txt)

**Comment by laurent22** [comment]
It says to contact your administrator, so why not do this? Or search on the forum or here for other users with this error.
