### ISSUE TITLE
[Feature Request]  Displaying the number of notes per folder 

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#518]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

Would it be interesting to have the number of notes per folder ?

Actually I have

    Django
    Python
    Database
    Java

Would like to see

    Django (144)
    Python (1259)
    Database (50)
    Java (33)

for example.

What do you think?

**Comment by luckydays** [comment]
Absolutely, that would be interesting :)
I use mostly tags than notebooks, it would be really helpful to see the number of notes under particular tags just in brackets next to the tag name.

Thank you, Joplin community!

**Comment by foxmask** [comment]
I still would like that on the desktop version at least
