### ISSUE TITLE
WebDAV Sync Joplin Client 2.1.8: various errors using Apache 2.4.41/Ubuntu 20.04.2

### ISSUE THREAD

**Issue by aremesch** [laurent22/joplin#5181]
Since a few updates (can't remember which version since I don't update very regularly) the WebDAV Sync with my Apache 2.4.41 fails sometimes but now always.

Typical error messages include:
~~~
Completed: 12.07.2021 18:14 (1s)
Letzte Fehlermeldung: Error: DELETE locks/sync_desktop_7e6c80f74f5d4082a43aea69687b49ef.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>403 Forbidden</title> </head><body> <h1>Forbidden</h1> <p>You don't have permission to access this resource.</p> </body></html>

Completed: 12.07.2021 18:15 (2s)

Completed: 12.07.2021 18:15 (1s)
Letzte Fehlermeldung: Error: DELETE locks/sync_desktop_7e6c80f74f5d4082a43aea69687b49ef.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>403 Forbidden</title> </head><body> <h1>Forbidden</h1> <p>You don't have permission to access this resource.</p> </body></html>

Completed: 12.07.2021 18:15 (0s)
Letzte Fehlermeldung: Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>403 Forbidden</title> </head><body> <h1>Forbidden</h1> <p>You don't have permission to access this resource.</p> </body></html>
~~~
As you can see, in between these error messages, the sync will sometimes work.

I have been using this Apache server & WebDAV config to sync Joplin for a few years and didn't do any changes to the server-side config since August 2019 (except for Ubuntu package updates).

Here is my server-side config:
~~~
DavLockDB /var/www/DavLock/DavLock
<VirtualHost *:443>
        ServerName (https://serevr-url)

        ServerAdmin (...)
        DocumentRoot /var/www/joplin-webdav
        <Directory /var/www/joplin-webdav>
                DAV On
                Options +Indexes
                AllowOverride None
                AuthType Basic
                AuthName "Anmedung zum WebDAV Verzeichnis"
                AuthUserFile /etc/apache2/users.password
                Require valid-user
        </Directory>

        SSLEngine on
        SSLCertificateFile (...)
        SSLCertificateKeyFile (...)
        SSLCACertificateFile (...)

        ErrorLog ${APACHE_LOG_DIR}/joplin-webdav-error.log
        CustomLog ${APACHE_LOG_DIR}/joplin-webdav-access.log combined

        Alias /webdav /var/www/joplin-webdav
</VirtualHost>
~~~

## Environment

Joplin version: 2.1.8
Platform: Windows
OS specifics: 10 21H1 19043.1083

Server: Ubuntu 20.04.2, Apache 2.4.41 WebDAV

## Logfile

The apache error log shows a lot of "client denied by server configuration" errors like so:
~~~
[Mon Jul 12 18:32:00.811015 2021] [evasive20:error] [pid 152691] [client <ip>:57435] client denied by server configuration: /var/www/joplin-webdav/locks/
[Mon Jul 12 18:34:42.729360 2021] [evasive20:error] [pid 152821] [client <ip>:65060] client denied by server configuration: /var/www/joplin-webdav/locks/
[Mon Jul 12 18:34:42.757272 2021] [evasive20:error] [pid 152821] [client <ip>:65060] client denied by server configuration: /var/www/joplin-webdav/locks/
[Mon Jul 12 18:34:42.795182 2021] [evasive20:error] [pid 152821] [client <ip>:65060] client denied by server configuration: /var/www/joplin-webdav/locks/sync_desktop_7e6c80f74f5d4082a43aea69687b49ef.json
~~~

Still the sync is working sometimes with this configuration. But it seems like Joplin tries to contact the server without authentification in some cases?

**Comment by JackGruber** [comment]
Your Server response with 403 error codes. Check your WebDav Server logs why access is not granted.

> HTTP Error Code 403
>
>The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested >resource. Unlike 401, the client's identity is known to the server.

**Comment by tessus** [comment]
I've been using Apache WebDAV for a while now, since Nextcloud's WebDAV implementation is horrible and way too slow.

Your config looks pretty much like mine. However, sometimes there are issues with Aliases and/or slashes at the end of the document dir. My config looks like this:

```
<VirtualHost IP:443>
    ServerName server.com:443
    DocumentRoot /data/dav

    SSLEngine On
    Include /etc/httpd/extra/certinfo-misc.conf

    <Directory "/data/dav/">
        Options FollowSymLinks
        AllowOverride none
        Require all denied
    </Directory>

    <Directory "/data/dav/Joplin/">
        DAV on
        Options Indexes FollowSymLinks

        AuthType Basic
        AuthName "WebDAV Joplin"
        AuthUserFile /d/Joplin.password

        Require valid-user
    </Directory>

</VirtualHost>
```

**Comment by tessus** [comment]
I don't think this is a bug. We should use the forum instead. You can use your gh creds for the forum.

**Comment by aremesch** [comment]
Thank You for the responses & sorry if I'm mistaken but I thought it is a bug for two reasons:
1) It worked in previous versions of Joplin with the same server & config
2) It works at times and fails immediately after it was working and then works again without any changes in configuration

Is there any way to trace the actual network data flow?

I will switch to the forum then.

**Comment by aremesch** [comment]
PS: I switched back to Joplin 1.8.5 on one of my Windows machines and there I can sync to the same WebDAV server without any errors or problems.,

**Comment by aremesch** [comment]
PPS: Joplin 1.3.18 on Linux syncs without problems too. Same with Joplin 2.1.4 on Android: no problems with sync with same server & config.

**Comment by roman-r-m** [comment]
> Is there any way to trace the actual network data flow?

Something like `tcpdump` should help. This way you'll see immediately if there's anything different about the requests that are being rejected.

**Comment by tessus** [comment]
I don't think this will work with TLS. At least not with forward secrecy. But I might be wrong.

I am using version 2.1.7 and I haven't seen any of those errors. Then I checked the commits between 2.1.7 and 2.1.8 and there's nothing related to WebDAV. I can't replicate this problem.

**Comment by roman-r-m** [comment]
> I don't think this will work with TLS. At least not with forward secrecy. But I might be wrong.

I remember there was a way to tell web browser to capture the certificate while opening a page, and then use it to decode traffic in wireshark. But agree it's not trivial

**Comment by aremesch** [comment]
I switched back to 1.8.5 on all my machines (except for Android) and that solved the problem for me. I'm still pretty sure it's a bug, cause why else would it work flawlessly in an older version? If you're interested in solving that issue, I'd be happy to reupgrade to any version and send you any diagnostic data you request. Otherwise pls close and reopen if it pops up elsewhere.

**Comment by tessus** [comment]
I still can't reproduce the problem. Maybe it's Windows specific. I don't have Windows anywhere, not even in a VM.

Laurent has a Windows machine (or at least he had at one point). Not sure about Roman.

**Comment by aremesch** [comment]
I'm able to reproduce it on my Linux Mint 20.1 box as well after upgrading from Joplin 1.3.18 to 2.1.8. It syncs only ~1 out of 3 tries and when fails shows the same error given above "Error DELETE locks/sync_desktop_<hex>.json" with 403 Forbidden. Manually deleting the lock on the server doesn't help.

Could it be because I have >68.000 fies in my joplin-webdav directory?

**Comment by aremesch** [comment]
You could try with my server if that helps since my notes are encrypted anyway?

**Comment by roman-r-m** [comment]
I could try if you share the details. Can you also check you server's logs to see if there are any hints there?
Just from the message it looks like it might be an issue on the sever rather than in Joplin.

**Comment by aremesch** [comment]
Server logs are at the bottom of my initial message, saying "client denied by server configuration". But still: this works in 2.1.8 sometimes w/o change in server config and in previous versions (1.8.5) without change in server config. So the problem must have at least a component on the client side.

I'd say the 2.1.7/2.1.8 desktop client seems to do part of its communication unathenticated under certain (seemingly rare) conditions.

I would happily share the details on a safe channel but of course not in a public forum.

**Comment by roman-r-m** [comment]
> I would happily share the details on a safe channel but of course not in a public forum.
Of course. You can send to roman.r.musin@gmail.com

From quick googling it looks like this error comes from the OS, not the webserver. Maybe it has something to do the number of files you have there, as you've said. Can it be that the reason it worked in 1.8.5 is simply because you've since accumulated more files there?

**Comment by aremesch** [comment]
No, it still works in 1.8.5, therefore I've started using this version again. Also, the permissions on OS-level are set correctly (rw for www-data).

**Comment by roman-r-m** [comment]
Can you try a few versions in between these 2 to narrow it down?

**Comment by roman-r-m** [comment]
I can think of a few changes that may have affected WebDAV API but not sure they were introduced after 1.8.5.
And I can't see how they could possibly trigger this but of course this need to be tested.

**Comment by tessus** [comment]
It is still very strange that I do not see this error. My setup is basically the same as the OP's.

Roman, which commits do you think could be responsible? Afaik the only thing that was changed on the transport level was the keepalive. Or was this even before 1.8.5?

**Comment by roman-r-m** [comment]
> Roman, which commits do you think could be responsible? Afaik the only thing that was changed on the transport level was the keepalive. Or was this even before 1.8.5?

Yes, keepalive, which is there in 1.8.5 but with a bug. That bug whoever was only occurring if you switch between http and https and was manifesting itself differently: https://github.com/laurent22/joplin/issues/5014

There was also the change to disable caching but it's there in 1.8.5.

But these are only the changes that I'm aware of.

**Comment by roman-r-m** [comment]
@aremesch if you could share the credentials, i could try and find which change introduced the issue.

**Comment by mrwulf** [comment]
I believe I am facing a possibly related issue on the macOS client (since at least v2.3.1) when doing a sync target upgrade. It looks like the webdav driver is writing a lock file and then trying to overwrite the same file. I'm not sure if this is new behavior or just part of the sync target upgrade (which doesn't happen very often). Normal sync seems to be working fine...

Here is the error
```
PUT locks/exclusive_desktop_aac0b4cdbc7e4b45a7de0457e64dffcd.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>403 Forbidden</title> </head><body> <h1>Forbidden</h1> <p>[me] cannot overwrite [/volume1/homes/me/Joplin/locks/exclusive_desktop_aac0b4cdbc7e4b45a7de0457e64dffcd.json].</p> </body></html>

Error: PUT locks/exclusive_desktop_aac0b4cdbc7e4b45a7de0457e64dffcd.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>[me] cannot overwrite [/volume1/homes/me/Joplin/locks/exclusive_desktop_aac0b4cdbc7e4b45a7de0457e64dffcd.json].</p>
</body></html>

    at newError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:414:11)
    at WebDavApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:444:10)
    at async FileApiDriverWebDav.put (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:201:10)
```

**Comment by aremesch** [comment]
> @aremesch if you could share the credentials, i could try and find which change introduced the issue.

![Bildschirmfoto vom 2021-08-23 19-31-38](https://user-images.githubusercontent.com/15725614/130491431-28eaed43-cfce-49ff-8532-7924d06ea6a3.png)

Pwd test1234

Pls let me know, when you finished testing, so I can remove this user!

**Comment by roman-r-m** [comment]
So I definitely can see the issue, maybe even a few different issues, although the underlying cause might be the same.

DELETE returning 403 I think may be caused by Joplin quickly creating and deleting the same file within a second.  But I've not been able to verify it yet.

**Comment by aremesch** [comment]
I had some problems since I was testing 2.3.5 and it was upgrading my database on the server to v3. I reverted to v2 so I am still able to use Joplin 1.8.5. The database should be v2 again now and should be ok, so please try again now since your tests might have been affected by my database restore. Thanks!!!

**Comment by aremesch** [comment]
@roman-r-m Since you have the credentials now and are able to test, I have deleted my previous post. Please let me know, when I can remove the test user. Thank you!!!

**Comment by mrwulf** [comment]
fyi, I just downloaded 2.4.2 and it still has the same error message (about no permissions to overwrite lock). I was hoping 06ed58b8090fd82f655caaa1e116ffd27fc761d4 might have given some relief.

**Comment by aremesch** [comment]
The problem is still there, so pls leave the issue open.

**Comment by aremesch** [comment]
This seems to work now in Joplin 2.6.10 (I didn't try all the versions since 1.8.5 so I can't say at which version exactly the issue has been fixed)
