### ISSUE TITLE
Copy-pasting in rich-text editor doubles line spacing.

### ISSUE THREAD

**Issue by saarantras** [laurent22/joplin#5196]
## Environment

Joplin version: 2.1.8
Platform: Linux

## Steps to reproduce

1. Write the following in the rich-text editor
```
foo
bar
baz
```
2. Copy-paste it to a new location
3. The line spacing as doubled, so you have the following:
```
foo

bar

baz

```

## Describe what you expected to happen
I expected the line-spacing not to double.

**Comment by saarantras** [comment]
This is still an issue as of joplin 2.3.3

**Comment by saarantras** [comment]
This is still an issue as of 2.3.5

**Comment by saarantras** [comment]
This is still an issue as of 2.5.12.

**Comment by danielberrones** [comment]
This is still an issue in 2.6.10  -- does anybody know how to turn the default double spacing to single?  Please advise.

**Comment by trex827** [comment]
same issue 2.6.10. What is going on with this.  Default double spacing is just plain annoying.

**Comment by saarantras** [comment]
This is still an issue as of joplin 2.6.10

**Comment by saarantras** [comment]
This is still an issue as of Joplin 2.7.15.

**Comment by saarantras** [comment]
Still an issue in 2.7.15

**Comment by saarantras** [comment]
This is still an issue as of Joplin 2.7.15.

**Comment by saarantras** [comment]
This is still an issue as of 2.7.15.

**Comment by saarantras** [comment]
Still an issue as of 2.8.8

**Comment by saarantras** [comment]
Still an issue

**Comment by saarantras** [comment]
This is still an issue

**Comment by wh201906** [comment]
> This is still an issue in 2.6.10 -- does anybody know how to turn the default double spacing to single? Please advise.

To input single line break, you can press `Shift+Enter`
To change the default behavior, this might help
https://www.tiny.cloud/docs/configure/content-filtering/#forced_root_block
BTW, we can't use this option to set single spacing in TinyMCE 5.10 or later

**Comment by saarantras** [comment]
> > This is still an issue in 2.6.10 -- does anybody know how to turn the default double spacing to single? Please advise.
> 
> To input single line break, you can press `Shift+Enter` To change the default behavior, this might help https://www.tiny.cloud/docs/configure/content-filtering/#forced_root_block BTW, we can't use this option to set single spacing in TinyMCE 5.10 or later

Thank you! Is this something that must be included during compilation, or something that can be placed in userchrome.css or userstyle.css?

**Comment by wh201906** [comment]
Seems like it should be included during compilation.

**Comment by saarantras** [comment]
Still an issue

**Comment by saarantras** [comment]
This is still an issue

**Comment by saarantras** [comment]
Fixed.
