### ISSUE TITLE
Create /events data API end point

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#5199]
The /events end point will return a paginated list of recent events, such as a note or notebook being changed or deleted. It will return rows from the existing `changes` table.

The user should provide a "cursor" property, which tells from what point in time the events should be returned. The API will also return a "cursor" property to tell from where to resume retrieving events.

## API call

`GET /events?cursor=CURSOR`

If "CURSOR" is empty, the API will return data from the beginning of the "changes" table.

## API output

```json
{
    "items": CHANGE_ITEMS,
    "cursor": CURSOR,
    "has_more": boolean,
}
```

Only up to 1000 items will be returned in one call. The next items can be fetched using the provided CURSOR.

When "has_more" is false, no more items are available and the client should stop calling the end point.

## Deleting old changes

There's logic in ItemChangeUtils::deleteProcessedChanges() to delete old changes. This should be changed so as not to delete changes too early. For example, in addition to the existing logic, we could set it to keep old changes for 60 more days, which should leave enough time to plugins to process the events.

**Comment by rxliuli** [comment]
It would be better if you can add relevant documents on the official website, maybe I have time this weekend to use this to complete the backup to an external git system

**Comment by laurent22** [comment]
The documentation for it will be available next time the website is built, is that what you mean?
