### ISSUE TITLE
android: after adding a list item it doesn't create a new list item when pressing return

### ISSUE THREAD

**Issue by webal** [laurent22/joplin#5207]
## Environment

Joplin version: 2.1.4
Platform: Android
OS specifics: Android Emui 9.1.0.405

## Steps to reproduce

1. Enter list item ('- [ ] item one')
2. press enter
3. 

## Describe what you expected to happen

the new line would be pre filled with '- [ ] '

**Comment by roman-r-m** [comment]
Is that with the new markdown editor? (https://discourse.joplinapp.org/t/new-beta-editor-for-the-mobile-app/18724)
If not then it's not a bug, it's just never been implemented.

**Comment by webal** [comment]
I'm using 2.1.4 and by the look of it the pre release is 2.2.1 so I don't think so.

But if the old editor is getting replaced I guess there's no point trying to fix a bug on something that's imminently going to be obsolete so I'll close the issue.
