### ISSUE TITLE
Search in all the notes loses focus

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#5208]
`Search in all the notes` lose focus when `Search in current note` is also used.

## Environment

Joplin 2.2.1 (prod, win32)

Client ID: 8d4ac0fa4a1840acb6db8ac8be29d7ce
Sync Version: 2
Profile Version: 39
Keychain Supported: Yes

Revision: 4e0ff1f

## Steps to reproduce

1. Open `Search in current note` an search some word 
2. Enter some search word in `Search in all the notes` and wait or press enter
 
![e9McZHZD4w](https://user-images.githubusercontent.com/24863925/126201652-ee00bf1a-6d3d-4806-be24-ebe150067316.gif)

after one second the `Search in current note` is triggerd again and gets focus. 

## Describe what you expected to happen

`Search in all the notes` should not lose focus 

## Discourse posts
https://discourse.joplinapp.org/t/in-the-process-of-inputting-search-terms-the-problem-of-automatic-search-is-triggered/18424

https://discourse.joplinapp.org/t/the-problem-of-focus-loss-when-input-in-joplin-search-box/18828

**Comment by Dominic-t3ch** [comment]
Hi,

This bug still exist. I use the portable version of Joplin, v. 2.9.17. When i begin to write something in the search field, it loose the focus to select the first note found if I stop to write a second.

Thanks

**Comment by JackGruber** [comment]
See https://github.com/laurent22/joplin/issues/6514
