### ISSUE TITLE
Not all notes downloading 

### ISSUE THREAD

**Issue by glynhudson** [laurent22/joplin#5209]
I'm running V1.7.11 on Ubuntu 18.04 using dropbox to sync notes. Usually it works fine, however sometimes notes don't get downloaded. Nothing I do will force the note to download. This is a small note without any attachments 

![Selection_003](https://user-images.githubusercontent.com/758844/126203876-0fbad3d5-2c9c-4886-9238-778f39f739d0.jpg)

Is this a known issue? Any ideas what I can do to fix?

**Comment by laurent22** [comment]
Any error in the log? https://joplinapp.org/debugging
