### ISSUE TITLE
Joplin incorrectly renders raw KaTeX in addition to the expected result

### ISSUE THREAD

**Issue by krallus** [laurent22/joplin#5210]
Create a note containing the following markup:
```
$$
\frac{1}{2}
$$
```
.. or any math expression.

Expected: The rendered note should show the fraction 1/2. Nothing else.

Actual: In addition to showing the fraction 1/2, the raw KaTeX notation is also rendered.

## Environment

Joplin version: 2.1.8 (flatpak)
Platform: Linux
OS specifics: Linux Mint 20.1 Cinnamon

**Important Note**: This only happens when pointing Joplin to a different configuration directory by starting it with the `--profile` command line option.  It also happens when using the 2.1.9 AppImage.

**Comment by laurent22** [comment]
The `--profile` is not supported (it's only there for development and testing) so I'm not sure there's something to fix here. We'd need to be able to replicate it without the flag.

**Comment by krallus** [comment]
There is no custom CSS in the other directory.  If the CSS is different, that is the way the directory was created when I first executed Joplin with `--profile`.  My only reason for using `--profile` parameter is because I have two different dropbox accounts -- a personal one and one for work, where I keep personal notes and work-related notes respectively.  If it's not supported, then I guess this is more a feature request to support multiple dropbox accounts than a bug report.  Thank you for the reply.

**Comment by laurent22** [comment]
Perhaps what's happening is that the app loads CSS files with a path relative to the profile path. So if it's modified with --profile it doesn't work. Just a guess. As for multiple profile support, there's already a discussion about in another GitHub issue.

**Comment by krallus** [comment]
Since this is only a problem when using "--profile" which is unsupported, I am linking this issue with #591 "[Feature Request] run multiple instances of Joplin"
