### ISSUE TITLE
Cannot completely sync all attachments/images/resources on Android via WebDAV.

### ISSUE THREAD

**Issue by ee7klt** [laurent22/joplin#5211]
I've synced up my notes over synology webdav (can't use docker because my nas does not use an intel chip). On all my desktops (mac os), images sync fine. but for some reason the android app just simply doesn't want to download ALL resources. I've tried "always", "automatic", "manual". I've trying clearing cache, clearing data. I even tried reinstalling. There was this one time it managed to download several thousand, but i had to painstakingly continuously fiddle around with the attachment download behavior it would download like a couple hundred, then a couple like tens etc. and eventually just stopped downloading when it got to like 3000. I have more than 10,000 images. Even if I wanna load each image individually within a note, when i click on the little download icon on an image it doesn't do anything. So bottom line I really can't get ALL images to display. ideally what i'd like to do is to be able to just transfer everything over usb since it's over 1GB of images directly to the resources folder, but it's buried in /data/data/ which i don't have access to because i'm not rooted. I see only one or two posts on this issue, so maybe there's something wrong with my android version. I'm running the latest OTA update on a Galaxy Note 9 if that helps.

**Comment by JackGruber** [comment]
Have you read the template on createing the issue?

>  Please provide a clear and concise description of what the bug is. (In the section Steps To Reproduce.)
>  Include screenshots if needed.
>  Please test using the latest Joplin release to make sure your issue has not already been fixed.
>
>  IMPORTANT: If you are reporting a clipper bug, please include an example URL that shows the issue.
>  Without the URL the issue is likely to be closed.
>
>## Environment
>
>Joplin version: 
>Platform: 
>OS specifics: 
>
>  Platform can be one of: macOS, Linux, Windows, Android, iOS, terminal (or a combination)
>  OS specifics: e.g. OS version, Linux distribution, Android/iOS version...
>
>## Steps to reproduce
>
>1. 
>2. 
>3. 
>
>  Issues without reproduction steps are likely to stall.
>
>## Describe what you expected to happen
>
>
>
>## Logfile
>
>  Please attach a debug log. Issues without a debug log are likely to stall.
>  For information on how to collect a log file: https://joplinapp.org/debugging/
