### ISSUE TITLE
Android - ToDo notifications are not coming

### ISSUE THREAD

**Issue by SnowFlakes0638** [laurent22/joplin#5216]
I recently started using Joplin and I like it very much.
I tried to use the ToDo function, but I didn't receive any notification at the set time.

English is not my native language, so I use a translation. Sorry if it's hard to understand.

## Environment

Joplin version: 2.1.4
Platform: Android
OS specifics: Android 11

## Steps to reproduce

1. Set To-Do Alarm
2. wait
3. notification is not coming

## Describe what you expected to happen

Notifications will be sent to smartphone at the specified time.

## Logfile

https://pastebin.com/kRi1Gdsr

**Comment by roman-r-m** [comment]
Maybe I'm missing something but it looks like you've set the date in the past (this is the only mention of alarm I could find in your log):

**07-20T22:34:09,30**,"""Scheduling notification for note e3cb30bcb1ab4db9b1c63fea56935558", "{"id":4,"noteId":"e3cb30bcb1ab4db9b1c63fea56935558","date":"**2021-07-20T13:35:00.000Z**","title":"Alarm Test","body":"Yay!"}""

**Comment by SnowFlakes0638** [comment]
> Maybe I'm missing something but it looks like you've set the date in the past (this is the only mention of alarm I could find in your log):
> 
> **07-20T22:34:09,30**,"""Scheduling notification for note e3cb30bcb1ab4db9b1c63fea56935558", "{"id":4,"noteId":"e3cb30bcb1ab4db9b1c63fea56935558","date":"**2021-07-20T13:35:00.000Z**","title":"Alarm Test","body":"Yay!"}""

I think it depends on the time zone. +9 hours and tried to adjust the numbers, but there was no notification.

```
07-21 09:09:00.788 30007 30007 D RNAlarmNotification: get alarm -> id:1, active:1, {"active":1,"alarmId":1626779519,"autoCancel":true,"bypassDnd":false,"channel":"net.cozic.joplin.notification","color":"blue","data":{"mClassLoader":{"packages":{"com.android.org.conscrypt":{"implTitle":"Unknown","implVendor":"Unknown","implVersion":"0.0","pkgName":"com.android.org.conscrypt","specTitle":"Unknown","specVendor":"Unknown","specVersion":"0.0"},"android.security.net.config":{"implTitle":"Unknown","implVendor":"Unknown","implVersion":"0.0","pkgName":"android.security.net.config","specTitle":"Unknown","specVendor":"Unknown","specVersion":"0.0"},"com.android.internal.telephony.dataconnection":{"implTitle":"Unknown","implVendor":"Unknown","implVersion":"0.0","pkgName":"com.android.internal.telephony.dataconnection","specTitle":"Unknown","specVendor":"Unknown","specVersion":"0.0"}},"proxyCache":{}},"mFlags":1536,"mMap":{"noteId":"7d1cf2321aff4f4f964e253356a11bfd","joplinNotificationId":"1"},"mParcelledByNative":false},"day":21,"hasButton":false,"hour":0,"id":0,"interval":"hourly","intervalValue":1,"largeIcon":"","loopSound":false,"message":"sample day","minute":0,"month":7,"playSound":true,"scheduleType":"once","second":0,"smallIcon":"ic_launcher_foreground","snoozeInterval":1,"soundName":"","tag":"","ticker":"","title":"todo","useBigText":false,"vibrate":true,"vibration":100,"volume":0.5,"year":2021}
07-21 09:09:00.789 30007 30007 E RNAlarmNotification: getAlarmList: exception cause java.lang.InstantiationException: Can't instantiate abstract class java.lang.ClassLoader message Failed to invoke protected java.lang.ClassLoader() with no args
07-21 09:09:00.789 30007 30007 E RNAlarmNotification: Failed to add alarm
07-21 09:09:00.789 30007 30007 E RNAlarmNotification: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.emekalites.react.alarm.notification.AlarmModel.toString()' on a null object reference
07-21 09:09:00.789 30007 30007 E RNAlarmNotification:   at com.emekalites.react.alarm.notification.AlarmReceiver.onReceive(AlarmReceiver.java:31)
07-21 09:09:00.789 30007 30007 E RNAlarmNotification:   at android.app.ActivityThread.handleReceiver(ActivityThread.java:4443)
07-21 09:09:00.789 30007 30007 E RNAlarmNotification:   at android.app.ActivityThread.access$1600(ActivityThread.java:301)
07-21 09:09:00.789 30007 30007 E RNAlarmNotification:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2159)
07-21 09:09:00.789 30007 30007 E RNAlarmNotification:   at android.os.Handler.dispatchMessage(Handler.java:106)
07-21 09:09:00.789 30007 30007 E RNAlarmNotification:   at android.os.Looper.loop(Looper.java:246)
07-21 09:09:00.789 30007 30007 E RNAlarmNotification:   at android.app.ActivityThread.main(ActivityThread.java:8512)
07-21 09:09:00.789 30007 30007 E RNAlarmNotification:   at java.lang.reflect.Method.invoke(Native Method)
07-21 09:09:00.789 30007 30007 E RNAlarmNotification:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
07-21 09:09:00.789 30007 30007 E RNAlarmNotification:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

I found an error in logcat that seems to maybe from Joplin.
I don't know much about it, but I hope it helps.

**Comment by roman-r-m** [comment]
I still don't know how to reproduce this but I have a rough idea of why this might be happening. Will have a look on the weekend

**Comment by roman-r-m** [comment]
Oh, looks like this one slipped through the cracks. I'll have a look.

**Comment by AKSoo** [comment]
Bumping this because to-do alarms do not work at all. I have checked all my mobile notification settings. Only Joplin fails to notify.

Joplin version: Joplin 2.3.4
Platform: Android 7.0

[syncReport-1632379087983.txt](https://github.com/laurent22/joplin/files/7215541/syncReport-1632379087983.txt)

**Comment by kurtisnotcurtis** [comment]
Confirming that alarm notifications do not work at all for me either.

Joplin version: 2.6.3
Platform: Android 8.1.0
