### ISSUE TITLE
[Feature Request] Collapse the tag list

### ISSUE THREAD

**Issue by zblesk** [laurent22/joplin#522]
The tag list in my database is quite long, I don't need it often, and I often have to scroll past it to see the sync status. 

I'd like to be able to collapse the list and hide the tags, so they don't take up space.

**Comment by foxmask** [comment]
a cheery on the cake would be to have "sub tag" like folders :)

**Comment by msbentley** [comment]
I second this - I have hundreds of tags imported from Evernote and have to scroll all the way down to get to the sync status. Clicking on the "Tags" title to fold the tree would be great!

**Comment by foxmask** [comment]
dup of #222

**Comment by MattCurryCom** [comment]
Bump, I have a ton of tags... dont need to see them all the time...
