### ISSUE TITLE
onedrive sync  error

### ISSUE THREAD

**Issue by dzhl** [laurent22/joplin#5220]
## Environment

Joplin version: 2.1.9
Platform: windows 10
OS specifics: 

## Steps to reproduce

1. 
2. 
3. 

## Describe what you expected to happen
set onedrive as sync destination,if onedrive set language to chinese,joplin will meet error when syncing.

**Comment by AyFun** [comment]
https://github.com/laurent22/joplin/issues/2406#issuecomment-901109336
