### ISSUE TITLE
Potential orphaned resources left on sync target on resource conflict

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#5223]
It looks like whenever there's a resource conflict, Synchronizer will create a new copy of the conflicted resource and attach it to a new note:
https://github.com/laurent22/joplin/blob/f611d7734b91460b6b1204af75c3f7a9fc38ab51/packages/lib/models/Resource.ts#L392-L402

The note is marked as conflict and so will be skipped during sync but it looks like the duplicated resource will still be uploaded to the sync target.

**Comment by laurent22** [comment]
Indeed I think the implementation is not quite right. It's also not logical to create a conflict note when it's the resource that's actually in conflict. Maybe the note should simply be added to a regular notebook, so that there's no special rules applying to it.
