### ISSUE TITLE
How can I sync pictures between typora and joplin

### ISSUE THREAD

**Issue by toppemonkey** [laurent22/joplin#5225]
When I use typora to edit notes, the pictures I inserted in typora cannot be synchronized to joplin. Is there a way to synchronize pictures, not just text

**Comment by roman-r-m** [comment]
This should work if you insert pictures to Joplin using links (something like `file:///my/picture.jpg`) But then such pictures won't be synchronized with e.g. mobile Joplin.

But this isn't a bug so such questions belong on the forum so closing this.
