### ISSUE TITLE
TOC plugin renders wrong depth

### ISSUE THREAD

**Issue by stloewen** [laurent22/joplin#5227]
## Environment

Joplin version: multiple (2.0.11 and 2.1.9)
Platform: Windows and Linux
OS specifics: Windows 10 and Debian testing

## Steps to reproduce

1. Create a note with the following structure
```
[toc]

# level 1
## level 2
### level 3
# level 1
#### level 4
```
2. See how the TOC plugin renders level 2 and level 4 at the same indent-depth: 
![grafik](https://user-images.githubusercontent.com/4498831/126630980-b632b647-3e07-439e-92c5-9c04715dc781.png)

## Describe what you expected to happen

The TOC should be rendered with level 4 at the correct depth:
![grafik](https://user-images.githubusercontent.com/4498831/126631411-95f08c25-09de-4585-9eae-aeeb681551f7.png)

So the `<li>` item for level 4 should be wrapped in two more layers of `<ul>...</ul>`

**Comment by laurent22** [comment]
Issues with plugins should be reported on the plugin repo.

**Comment by stloewen** [comment]
This feature is built into Joplin. I can't find a separate repo to report this to. Could you point me to it?
