### ISSUE TITLE
Does not play nice with nginx WebDAV

### ISSUE THREAD

**Issue by bradmcl** [laurent22/joplin#523]
### Operating system

- macOS
- Linux

### Application

- Desktop

Two issues so far:  

The first is that the `MKCOL` requests for the `.sync` and `.resource`do not have a trailing `/`  ( meaning `.sync/` and the nginx WebDAV module is very picky.  A work around for this is to add a rewrite like `if ($request_method = MKCOL) { rewrite ^(.*[^/])$ $1/ break; }`  to the nginx config, but it would be nice if Joplin was more conservative in its adherence to the RFC.

The second issue is that Joplin does not like to parse PROPFIND responses of the form 

> Bradleys-MacBook-Pro:documentation brad$ curl -i --basic --user '<removed>' -X PROPFIND https://<removed>/joplin/.sync --upload-file - -H "Depth: 1" <<end
> > end
> HTTP/1.1 100 Continue
> 
> HTTP/1.1 207 Multi-Status
> Server: nginx/1.12.1 (Ubuntu)
> Date: Mon, 14 May 2018 12:45:28 GMT
> Transfer-Encoding: chunked
> Connection: keep-alive
> 
> <?xml version="1.0" encoding="utf-8" ?>
> <D:multistatus xmlns:D="DAV:">
> <D:response>
> <D:href>/joplin/.sync</D:href>
> <D:propstat>
> <D:prop>
> <D:creationdate>2018-05-12T21:49:03Z</D:creationdate>
> <D:displayname>.sync</D:displayname>
> <D:getcontentlanguage/>
> <D:getcontentlength>4096</D:getcontentlength>
> <D:getcontenttype/>
> <D:getetag/>
> <D:getlastmodified>Sat, 12 May 2018 21:48:52 GMT</D:getlastmodified>
> <D:lockdiscovery/>
> <D:resourcetype><D:collection/></D:resourcetype>
> <D:source/>
> <D:supportedlock/>
> </D:prop>
> <D:status>HTTP/1.1 200 OK</D:status>
> </D:propstat>
> </D:response>
> </D:multistatus>
> 

  resulting in the error

> 2018-05-14 09:28:43: "Operations completed: "
> 2018-05-14 09:28:43: "Total folders: 1"
> 2018-05-14 09:28:43: "Total notes: 1"
> 2018-05-14 09:28:43: "Total resources: 0"
> 2018-05-14 09:28:43: "There was some errors:"
> 2018-05-14 09:28:43: "TypeError: Cannot read property '0' of null
> TypeError: Cannot read property '0' of null
>     at WebDavApi.resourcePropByName (/Applications/Joplin.app/Contents/Resources/app/lib/WebDavApi.js:166:19)
>     at FileApiDriverWebDav.statFromResource_ (/Applications/Joplin.app/Contents/Resources/app/lib/file-api-driver-webdav.js:58:41)
>     at FileApiDriverWebDav.stat (/Applications/Joplin.app/Contents/Resources/app/lib/file-api-driver-webdav.js:33:16)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:109:7)"
>

**Comment by bradmcl** [comment]
See https://github.com/laurent22/joplin/pull/541 which isn't pretty :(  On the plus side, it works.

**Comment by laurent22** [comment]
Hi, thanks for the patch, but I wonder if there's a better way to fix it? In particular I don't get why nginx responds with a multistatus when only a single request has been made. And if they can randomly respond with multistatus then the code should be made more generic to deal with this.

Do you have any test server that I could use by any chance to double-check all this?

**Comment by bradmcl** [comment]
Thought you might feel that way.  Relevant code is https://github.com/arut/nginx-dav-ext-module/blob/master/ngx_http_dav_ext_module.c starting near line 524.  It doesn't distinguish between single and multi requests.  That seems consistent with https://tools.ietf.org/html/rfc4918#page-35 section 9.1 ( the examples there do the same thing ), where it appears that the request level status code only addresses whether or not the request was legal, and then the individual D:propstat sections each contain the D:status for that item.

**Comment by laurent22** [comment]
@bradmcl, your fix should be part of the latest releases (Desktop and Android) so I guess we can close this issue?

**Comment by bradmcl** [comment]
Confirmed; release 1.0.100 synchronizes correctly with Nginx DAV running on Ubuntu from both an OSX desktop, and an Android phone.  Thanks!
