### ISSUE TITLE
Can no longer sync to webdav on iphone

### ISSUE THREAD

**Issue by Jegber** [laurent22/joplin#5231]
## Environment

Joplin version: 12.1.2, db v39
Platform: iPhone
OS specifics: iOS 14.6

## Steps to reproduce

1. Set Synchronization target to WebDAV
2. Enter WebDAV url as an https
3. Set correct WebDAV username and password
4. Click "Check synchronization configuration"
5. Observe error message: "Error. Please check that URL, username, password, etc. are correct and that the sync target is accessible. The reported error was: Network request failed"

## Describe what you expected to happen
Sync worked fine about a month ago. Suddenly stopped working only on iOS. Sync works on macOS with same settings.

## Logfile

07-22T15:44:31: "TypeError: Network request failed
/private/var/containers/Bundle/Application/05D9D03A-3CB0-465F-
AB41-4 BOBCFD3B485/Joplin.app/main.jsbundle:118:8117
y@/private/var/containers/Bundle/Application/05D9D03A-3CB0-465F-
AB41-4 BOBCFD3B485/Joplin.app/main.jsbundle:130:581
callTimers@/private/var/containers/Bundle/Application/
05D9D03A-3CB0-465F-AB41-4BOBCFD3B485/Joplin.app/
main.jsbundle:130:2630
value@/private/var/containers/Bundle/Application/05D9D03A-3CB0-465F-
AB41-4B0BCFD3B485/Joplin.app/main.jsbundle:27:3351
/private/var/containers/Bundle/Application/05D9D03A-3CB0-465F-
AB41-4 BOBCFD3B485/Joplin.app/main.jsbundle:27:748
value@/private/var/containers/Bundle/Application/05D9D03A-3CB0-465F-
AB41-4 BOBCFD3B485/Joplin.app/main.jsbundle:27:2611
value@/private/var/containers/Bundle/Application/05D9D03A-3CB0-465F-
AB41-4 BOBCFD3B485/Joplin.app/main.jsbundle:27:720
value@[native code]"

Thank you Joplin devs, I love you

**Comment by roman-r-m** [comment]
Does your sever use a self-signed certificate?

**Comment by Jegber** [comment]
You're right! The certificate couldn't renew after changing network routing. Renewed and everything is smooth as butter once again. Thanks!
