### ISSUE TITLE
Cursor is rendered at wrong position after toggling side bar or note list

### ISSUE THREAD

**Issue by zapateo** [laurent22/joplin#5233]
## Environment

Joplin version: **2.1.9**
Platform: **Linux**
OS specifics: **Fedora 34** Workstation, **Gnome** on **X11** (with proprietary Nvidia drivers)

## Steps to reproduce

1. Open a note and put cursor on a line

![step-1](https://user-images.githubusercontent.com/11294400/126794946-e8bcebb7-0538-46b9-83c5-254cb696dd58.png)

2. Press <kbd>F10</kbd> or <kbd>F11</kbd> to toggle the side bar or the note list. If the resizing of the editor causes some line wrapping, the cursor now is rendered at another position in the text:

![step-2](https://user-images.githubusercontent.com/11294400/126794965-2dcc1e62-6d1f-4ca8-b4cd-dcf352206865.png)

3. Start typing. The cursor returns to the correct position and the text is inserted as expected

![step-3](https://user-images.githubusercontent.com/11294400/126795013-8682f025-5e78-44b9-8934-381ed3640774.png)

## Describe what you expected to happen

The cursor position in the text should be kept when the side bar or the note list are toggled.

## Logfile

Nothing relevant is apparently reported in the log.

**Comment by CalebJohn** [comment]
Have you tested this on the [release version](https://github.com/laurent22/joplin/releases/tag/v2.1.9)? I can easily reproduce this on the development version, but not on the latest release, or the latest pre-release.

**Comment by zapateo** [comment]
> Have you tested this on the [release version](https://github.com/laurent22/joplin/releases/tag/v2.1.9)? I can easily reproduce this on the development version, but not on the latest release, or the latest pre-release.

I've tried both `Joplin-2.1.9.AppImage` and `Joplin-2.2.2.AppImage` (_pre-release_), downloaded from https://github.com/laurent22/joplin/releases/, I can reproduce the issue with the same steps mentioned above.

**Comment by tessus** [comment]
I cannot reproduce this on macOS.

**Comment by laurent22** [comment]
@CalebJohn, is it the same issue that is solved when the spellchecker is enabled?

**Comment by CalebJohn** [comment]
No, this isn't caused by zero width tokens, it's the changing of the editor size is causing CodeMirror to lose track of the cursor. I tested with spellcheck enabled and disabled and I'm able to reproduce in both cases. I fixed this same bug about a year ago, there must have been a regression that's brought it back. The fix should just be to manually refresh the editor when we toggle the sidebars (or ideally whenever the editor resizes).

**Comment by Ahmad45123** [comment]
>  (or ideally whenever the editor resizes).
I think I found a small package that could achieve this: https://www.npmjs.com/package/react-resize-detector
They have a small demo showcasing how it works, and it's our exact usecase. Demo: http://maslianok.github.io/react-resize-detector/

Hooking to that event and then calling refresh should fix the issue. I'm still new to Reach so do let me know if I'm not seeing something. Also am I allowed to use external packages ?

**Comment by CalebJohn** [comment]
@Ahmad45123 Ideally we wouldn't be using an external library for this because it should be fairly simple. In fact, we have [function](https://github.com/laurent22/joplin/blob/dev/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/index.ts#L93) which should be performing the same function as this package (almost). It should trigger he [refresh event here](https://github.com/laurent22/joplin/blob/dev/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx#L698) but for some reason it does not. Have you figured out why that's the case?

**Comment by Ahmad45123** [comment]
> It should trigger he refresh event here but for some reason it does not. Have you figured out why that's the case?

I actually did manage to pinpoint the issue to that function not being called. Wasn't able to figure out why it wasn't called at all tbh but I didn't try to debug that rootSize thing, I'll check that.

Quick question though, what is useEffect briefly? I tried looking on the docs but it's not clear what it does and it's literally everywhere in the codebase

**Comment by laurent22** [comment]
If there's a need to get a component size, you can use the `useElementSize` hook I've recently added:

https://github.com/laurent22/joplin/blob/fe4900d25469372e2092d788d28ad2e586725adf/packages/app-desktop/gui/SyncWizard/Dialog.tsx#L164

**Comment by CalebJohn** [comment]
@Ahmad45123 
`useEffect` is a special function that is part of react hooks. It takes arguments, the first is a function and the second is a list of "dependencies". The function is run every time a dependency changes. In the link I posted above, that anonymous function (which basically just calls refresh) will be called any time one of `rootSize`, `styles.editor` or `props.visiblePanes` changes. 


I highly recommend that you read through this [introduction to hooks](https://reactjs.org/docs/hooks-intro.html), I found it very helpful when Joplin made the transition to react hooks.

**Comment by Ahmad45123** [comment]
I'm honestly stuck, I've been able to notice a few things but still unsure how to actually fix it.
Check this video: 
https://user-images.githubusercontent.com/8184424/129980115-47dacf80-41ee-44e9-8d25-5d94710c4838.mp4

After some debugging, I found out that the State of width and height never get updated when I hide/show layout elements,. If I manually resize the window, the width and height get updated and therefore the useEffect is called normally.

Now, why does width/height not update after layout changes ? No idea frankly. One idea to fix this was to force React to "update".

**Comment by CalebJohn** [comment]
@Ahmad45123 This was definitely a challenging bug. I had previously attempted to fix it over a year ago, and as we can see it's still around...
I've created a PR (#5344) with a proposed fix and an explanation for what caused the bug and why the fix works. @Ahmad45123 can you take a look at it and let me know what you think?

**Comment by Ahmad45123** [comment]
> @Ahmad45123 This was definitely a challenging bug. I had previously attempted to fix it over a year ago, and as we can see it's still around...
> I've created a PR (#5344) with a proposed fix and an explanation for what caused the bug and why the fix works. @Ahmad45123 can you take a look at it and let me know what you think?

That indeed makes a lot of sense! Good stuff.  I was in the right direction but was unsure how to make the window "know" the layout has changed. This line here specifically: https://github.com/laurent22/joplin/blob/88d41ebc31f8d630073a1605f2b181ab3f2b8b4c/packages/app-desktop/gui/ResizableLayout/utils/setLayoutItemProps.ts#L22

Makes sense.
