### ISSUE TITLE
Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7

### ISSUE THREAD

**Issue by nocsg** [laurent22/joplin#5236]
## Environment

Joplin version: new
Platform: android studio in windows
OS specifics: android

## Steps to reproduce

1. 
2. 
3.

**Comment by roman-r-m** [comment]
Could you give more details? What were your trying to do, at what point did you get the error, etc. Showing a complete stack trace won't hurt either.

**Comment by nocsg** [comment]
when i import the project with AS ide in window platform&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "laurent22/joplin"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sat, Jul 24, 2021 04:48 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [laurent22/joplin] Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7 (#5236)





 
Could you give more details? What were your trying to do, at what point did you get the error, etc. Showing a complete stack trace won't hurt either.

**Comment by roman-r-m** [comment]
Did you run `npm install` from the project root? If not - do it and reimport.
