### ISSUE TITLE
Unable to open Joplin app on mac

### ISSUE THREAD

**Issue by f-x1-1** [laurent22/joplin#5239]
EACCES: permission denied, mkdir '/Users/fahadzafar/.config/joplin-desktop'

Error: EACCES: permission denied, mkdir '/Users/fahadzafar/.config/joplin-desktop'

## Environment

Joplin version: 2.1.9
Platform: macOS

**Comment by sif** [comment]
Hi, what version macOS? Can you give the steps to reproduce the bug?

**Comment by sif** [comment]
Hi, what version macOS? Can you give the steps to reproduce the bug?

**Comment by huliyanna** [comment]
Hi:
I have the same issue ....Mac OSX Big Sur 11.15.1.  Here is the error again:
EACCES: permission denied, mkdir '/Users/nkrishna/.config/joplin-desktop'

I have tried all earlier fixes:
defaults write com.apple.finder AppleShowAllFiles true; killall Finder 
sudo spctl --master-disable

No luck so far. 

Any help will be gratefully accepted.

Best

N Krishna

**Comment by huliyanna** [comment]
Hi:
I downloaded latest beta version 2.3.3 - but the same error as above cropped up. I resolved the issue by executing the following terminal command
sudo chown -R $USER /Users/nkrishna/.config/

Hope this helps .....

PS: replace nkrishna with your mac user name.

**Comment by huliyanna** [comment]
Sorry for reporting late....this was primarily a folder permissions issue.
I was able to resolve it successfully.

Thanks for the follow thru'

Norman
