### ISSUE TITLE
Desktop editor does not handle emoji (may be all utf8) well

### ISSUE THREAD

**Issue by benasse** [laurent22/joplin#524]
### Operating system
- Windows
- macOS
- Linux

### Application
- Desktop

It looks like the emoji (may be all utf 8) is not handled properly by the editor.

The cursor pointer is displayed in the middle of the emoji:
![initial](https://user-images.githubusercontent.com/5676729/40017473-c6e01822-57b9-11e8-82a1-f88b3097ab99.png)
Adding a space break characters:
![add-one-space](https://user-images.githubusercontent.com/5676729/40017578-147762de-57ba-11e8-82c5-bfa75e2c789f.png)

A other example:
![initial2](https://user-images.githubusercontent.com/5676729/40017607-26db7122-57ba-11e8-8224-7edb814808ea.png)
![add-one-space2](https://user-images.githubusercontent.com/5676729/40017611-2a26ed0c-57ba-11e8-9082-b006a1d515eb.png)

**Comment by foxmask** [comment]
maybe unicode is not supported

**Comment by laurent22** [comment]
Yes I'm afraid changing the editor is not planned, but also I suspect Ace Editor is the most stable out there. They all have their bugs and glitches, but Ace Editor has been around for longer and has a lot more contributors and commits than other editors.

**Comment by govvin** [comment]
Note: this also affects the Linux desktop app.

**Comment by casasfernando** [comment]
And it really becomes a problem with non-english languages like french or spanish and their special characters like: ñ, á, é, í, ó, ú.....etc.

Did anyone found any workaround? I'm thinking about using an external editor but that will only fix editing, not displaying the text in the desktop app.
