### ISSUE TITLE
install script terminate with error on opensuse tumbleweed

### ISSUE THREAD

**Issue by mess-maker** [laurent22/joplin#5240]
installing joplin with the recommended script
`wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash`

end with error
```
Installing Joplin...
OK
Installing icon...
OK
bash: line 164: lsb_release: command not found
bash: line 165: lsb_release: command not found
```

## Environment

Joplin version: 2.1.9
Platform: opensuse tumbleweed vm (vmware player) on win10 host
seems that `lsb-release` is not a default package and cause the script to fail

NOTA : installed the `lsb-release` package manually 
return
```
mess-maker@localhost ~> lsb-release
LSB Version:    n/a
```
but the script terminate with no issue
```
Installing Joplin...
OK
Installing icon...
OK
Create Desktop icon...
OK
Joplin version 2.1.9 installed.
Cleaning up...
OK
```

## Steps to reproduce

1. install opensuse tumbleweed
2. launch the install script
3. 

## Describe what you expected to happen

install with no error

**Comment by CalebJohn** [comment]
Do you know what the equivalent to the lsb_release package would be on opensuse?

**Comment by mess-maker** [comment]
hi,

sorry for the delay was on vacation
according to Opensuse documentation, here is the way to get OS info without 'lsb-release' package
https://en.opensuse.org/SDB:Find_openSUSE_version

**Comment by mess-maker** [comment]
here the output of `cat /usr/lib/os-release`

```
NAME="openSUSE Tumbleweed"
# VERSION="20210810"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20210810"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20210810"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo"
```

**Comment by CalebJohn** [comment]
Thanks for checking that, now that I'm starting on a fix I release it might not even be necessary. My apologies.

Just to confirm, once you installed lsb_release, you were able to launch the app?

**Comment by mess-maker** [comment]
yes after installing the `lsb-release` package manually the script execute normally

I reported that just to notify that the install is not seamless on opensuse distro and maybe this could be handled differently in the script to avoid this extra step

**Comment by CalebJohn** [comment]
I will add a check for the existence of the lsb_release binary. I just wanted to confirm that there weren't any other incompatibilities. I'll also add a note about `/usr/lib/os-release` in case it's needed in the future.
