### ISSUE TITLE
Dark theme not working on GNOME

### ISSUE THREAD

**Issue by Yajo** [laurent22/joplin#5242]
## Environment

Joplin version: 2.1.9
Platform: Linux
OS specifics: Fedora 34 Silverblue, GNOME desktop, installed from flathub

## Steps to reproduce

1. Install this GNOME extension that switches between light and dark modes: https://extensions.gnome.org/extension/2236/night-theme-switcher/ 
2. Refresh that page and click on the configure button that now appears.
3. Enable display controls always. A new "moon" icon appears on the top bar.
![image](https://user-images.githubusercontent.com/973709/126981392-ebdd0694-4c58-42fb-aac3-a93d8abb098a.png)

4. Run Joplin.
5. Switch desktop to dark mode.
6. Joplin keeps light theme: 
![image](https://user-images.githubusercontent.com/973709/126981612-fdfc41ae-473e-47e2-b90b-a0c513beebc4.png)

## Describe what you expected to happen

I expect Joplin to switch to using the dark theme that I have configured for it.

## Logfile

<pre><font color="#FF0000">❯</font> <font color="#005FD7">flatpak</font> <font color="#00AFFF">run</font> <font color="#00AFFF">net.cozic.joplin_desktop</font> <font color="#00AFFF">--open-dev-tools</font> <font color="#00AFFF">--debug</font> <font color="#00AFFF">--log-level</font> <font color="#00AFFF">debug</font>
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/joplin-desktop/joplin --type=zygote --log-level
Gtk-Message: 12:28:17.623: Failed to load module &quot;canberra-gtk-module&quot;
Gtk-Message: 12:28:17.623: Failed to load module &quot;canberra-gtk-module&quot;
[2:0726/122818.954562:ERROR:CONSOLE(1)] &quot;Uncaught TypeError: Cannot read property &apos;instance&apos; of undefined&quot;, source: devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@dd99ba552928fbb8e62435f09f35048370fd04af/&amp;can_dock=true&amp;toolbarColor=rgba(223,223,223,1)&amp;textColor=rgba(0,0,0,1)&amp;experiments=true (1)
</pre>

**Comment by CalebJohn** [comment]
Interesting, if you restart Joplin the correct theme will be used but it doesn't look like any interaction triggers it to switch.

**Comment by uzair-ali10** [comment]
Hey!
Are u using any Custom GTK theme?

**Comment by Yajo** [comment]
> Interesting, if you restart Joplin the correct theme will be used

Not here... Maybe because I use the flatpak?



> Are u using any Custom GTK theme?

No, just Adwaita with dark variant.

**Comment by tigexplorer** [comment]
Maybe, fyi, on Gnome on ubuntu 20.4, the dark theme of joplin works very well.
I use the Joplin Appimage.

**Comment by Yajo** [comment]
I don't know what happened, maybe I was testing wrongly, or maybe an update... well, now it's working fine (still using the flatpak). The only problem is that I have to close Joplin and open it again for it to switch to dark mode, which doesn't happen in other apps. Maybe it's a electron problem...
