### ISSUE TITLE
Rich text editor reverts to Markdown code display after leaving the note

### ISSUE THREAD

**Issue by cfjedimaster** [laurent22/joplin#5243]
## Environment

Joplin version: 2.19
Platform: Windows
OS specifics: 10

## Steps to reproduce

1. With the Rich Text editor selected, type some text and use ctrl+b to make text bold. This works fine.
2.  Leave the note and select another one.
3.  Return to the note, the previously bold text now shows the MD code, "foo **goo** zoo". I still have the RTE selected.

## Describe what you expected to happen

It should have continued to display the text in bold. 

Note - in my testing, this was not always consistent in terms of when it broke.

## Logfile

Nothing there seemed helpful.

**Comment by saarantras** [comment]
I think this is a duplicate of #5238.

**Comment by cfjedimaster** [comment]
I believe so - I had not intentionally added a space, but in the Markdown version I see there's a space before the end **.
