### ISSUE TITLE
Indentation on list items and checkbox list items is lost when line wraps

### ISSUE THREAD

**Issue by jamedeus** [laurent22/joplin#5248]
Reopening #3829 (closed by stale bot, still relevant)

![example-highlighted](https://user-images.githubusercontent.com/61995646/127436972-6c3b03de-8af7-4b5a-924c-58eb9c9b12e5.png)

Without highlighting:
![example](https://user-images.githubusercontent.com/61995646/127436983-3d13cea0-f35c-4576-af7a-adb874fa33e5.png)

## Environment

Joplin version: 2.1.9 (Issue has occurred since 1.1.4)
Platform: Linux
OS specifics: Kubuntu 20.04

## Steps to reproduce

1. Create new note
2. Create bullet list or checkbox list
3. Type until text reaches end of screen and wraps to next line. The next line begins at left edge of the editor (should be indented 2 characters so it lines up with the beginning of the list item on previous line).
4. Create another bullet/checkbox and indent it with the tab key. Then type until line wrap. The issue is the same but it is much more obvious, because now second line is a full tab to the left.

## Describe what you expected to happen

In Ace Editor the line always began at the same indent level after wrapping, even if it wrapped several times. First character of the wrapped line would always be directly underneath the first character of the parent line, at every indent level. This issue appeared after the update that switched to Code Mirror editor (which fixed many other minor issues btw, still an improvement!).

## Logfile

```
22:23:50: Saving note... {id: "ad6539a932ff4fd6976f8b4314dd115f", parent_id: "839ce15c72f24cc68b1e49e5e95fc88d", title: "Example", body: "Title↵- List item↵- Really really long list item t…available space and wrap to the next line↵	- [ ] "}
/tmp/.mount_JoplinYpXFPm/resources/app.asar/node_modules/@joplin/lib/Logger.js:188 22:23:50: Scheduling sync operation... 30000
/tmp/.mount_JoplinYpXFPm/resources/app.asar/node_modules/@joplin/lib/Logger.js:188 22:24:00: Saving note... {id: "ad6539a932ff4fd6976f8b4314dd115f", parent_id: "839ce15c72f24cc68b1e49e5e95fc88d", title: "Example", body: "Title↵- List item↵- Really really long list item t…ap to the next line↵	- [ ] Really long note that "}
/tmp/.mount_JoplinYpXFPm/resources/app.asar/node_modules/@joplin/lib/Logger.js:188 22:24:00: Scheduling sync operation... 30000
/tmp/.mount_JoplinYpXFPm/resources/app.asar/node_modules/@joplin/lib/Logger.js:188 22:24:00: SearchEngine: Updating FTS table...
/tmp/.mount_JoplinYpXFPm/resources/app.asar/node_modules/@joplin/lib/Logger.js:188 22:24:01: Saving settings...
/tmp/.mount_JoplinYpXFPm/resources/app.asar/node_modules/@joplin/lib/Logger.js:188 22:24:01: Settings have been saved.
/tmp/.mount_JoplinYpXFPm/resources/app.asar/node_modules/@joplin/lib/Logger.js:188 22:24:01: SearchEngine: Updated FTS table in 51ms. Inserted: 1. Deleted: 0
```

**Comment by laurent22** [comment]
This is supported using the Rich Markdown plugin: https://github.com/CalebJohn/joplin-rich-markdown

**Comment by jamedeus** [comment]
This is amazing, thanks for letting me know!

I suppose this is really less of an issue and more of a change from how it used to be, since it works fine in rendered markdown and WYSIWYG.
