### ISSUE TITLE
Issues in the new iOS version: CJK Input and display jumping to top

### ISSUE THREAD

**Issue by RCJacH** [laurent22/joplin#525]
### Operating system

- iOS

### Application

- Mobile

As of version 10.0.21, native input of CJK language no longer works properly. CJK input requires the system to take in alphabet input first before returning then into CJK symbols with the matching alphabet spelling, however it seems that upon every alphabet input, Joplin refreshes the display and breaks the input chain of the internal IME.

Also, upon each input, the display window jumps back to the title or top of the note, which did not happen in the previous versions.

Edit: Version 10.0.22 did not solve this problem
iOS 8.1.2

**Comment by laurent22** [comment]
Does the last iOS version work any better?

**Comment by laurent22** [comment]
Ok looks like the bug has been fixed on React Native and should be merged in a future version - https://github.com/facebook/react-native/issues/12599

I will update the framework once they get the fix in.

**Comment by RCJacH** [comment]
This is resolved in iOS v0.10.26.

**Comment by laurent22** [comment]
That's good to know, thanks @RCJacH
