### ISSUE TITLE
Joplin in 32bits

### ISSUE THREAD

**Issue by HHZZUUJH** [laurent22/joplin#526]
### Operating system

- Linux

### Application

- Desktop

I can not install the AppImage 64-Bit. I have a 31-Bit Ubuntu. Can you provide me with a 32-Bit AppImage.

Many Thanks

HH

**Comment by foxmask** [comment]
Hi,
can you edit the topic and add more details  ?  `Joplin` all alone means nothing
and in the description can you show us the error message when installing ?

**Comment by HHZZUUJH** [comment]
Thank you for your prompt reply. I could only install a 32-bit Xubuntu on my old Samsung NC-10. Since it will probably be nothing with Joplin.

 

Von: FoxMaSk <notifications@github.com> 
Gesendet: Dienstag, 15. Mai 2018 13:55
An: laurent22/joplin <joplin@noreply.github.com>
Cc: HHZZUUJH <hns376@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [laurent22/joplin] Joplin (#526)

 

Hi,
can you edit the topic and add more details ? Joplin all alone means nothing
and in the description can you show us the error message when installing ?

**Comment by Immortalin** [comment]
I am pretty sure electron supports 32 bits

**Comment by laurent22** [comment]
The app should work on both 32 and 64 bits. What's the error message?

**Comment by foxmask** [comment]
if i'm not wrong you need node 8 and + 
if you have a look at the README file on the front page of the repo, you can see above 

```
NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin
```
this requirements

```
Important: First, install Node 8+. Node 8 is LTS but not yet available everywhere so you might need to manually install it.
```

**Comment by laurent22** [comment]
What version of node is it? Also it's not compatible with node 10 at the moment?

**Comment by foxmask** [comment]
Error says node 4.2.6

**Comment by HHZZUUJH** [comment]
I updated everything. now this error comes:

NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/laurent22/node-emoji.git
npm ERR! 
npm ERR! fatal: failed to stat '.': Keine Berechtigung
npm ERR! 
npm ERR! exited with error code: 128

**Comment by HHZZUUJH** [comment]
npm install --save node-emoji

npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

**Comment by laurent22** [comment]
What does `npm --version && node --version` print?

**Comment by HHZZUUJH** [comment]
I have

npm 6.0.1

node v8.11.2

The Commands

NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin

or

npm -g install joplin

always result in this error:

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/laurent22/node-emoji.git
npm ERR!
npm ERR! fatal: failed to stat '.': Keine Berechtigung
npm ERR!
npm ERR! exited with error code: 128

and

npm install --save node-emoji

npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

**Comment by stucki-at-home** [comment]
I do run Joplin teleworking from home-PC(ubuntu) [on a friend's nextcloud] and at the workplace-PC(debian) and in between on mobile-phone(adroid). First time in my life this kept my notes nearly flaw/seam-less. But then I noticed, that I have the same Problem ('does not run' on a current(!) 32-Bit Debian).
Starting the Download always gives a Version `Joplin-1.0.*-x86_64.AppImage` with `*_x86_64*` in it. And therefore the AppImage begins with an ELF 64bit load.
(`file` magic is: "./Joplin-1.0.104-x86_64.AppImage: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2 ...")

How do we get either a real 32bit AppImage, or a sure way to compile Joplin on 32bit versions of linux(es) like ubuntu or debian (and others ?!). I  It would really be useful to include the older (but lightweight <1kg) small notebooks into the loop.

Thanks, Stucki

**Comment by obert99** [comment]
Seems to work quite when running the Windows version within "wine" (tested on lubuntu, 18.04.1)
Rgds, Oliver

**Comment by l4jos** [comment]
There are probably still alot of people with 32-bit like me. Im running Ubuntu Mate but AppImage seems to work on 64-bit only. Would like to try again if 64-bit AppImage is supported. Nice features anyway!

**Comment by michaelpeeters** [comment]
I got the Joplin terminal application working on Lubuntu 18.10, 32 bit install. 
```
sudo apt install libvips-dev npm
```
then follow with the regular joplin install with npm
```
NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin
sudo ln -s ~/.joplin-bin/bin/joplin /usr/bin/joplin
```

**Comment by shankargopal** [comment]
I can confirm that the AppImage doesn't execute in a 32 bit Debian environment. This is the output of `uname -a`: 

`Linux debian 4.15.0-2-686-pae #1 SMP Debian 4.15.11-1 (2018-03-20) i686 GNU/Linux`

And I get `exec format error` when trying to run it in zsh.

**Comment by HHZZUUJH** [comment]
Hey, I've followed all the suggestions and hints. Unfortunately I could not solve the problem with it. But for all I care the topic can also be closed
