### ISSUE TITLE
An error showing meanwhile I was using integation PlantULM plugin.

### ISSUE THREAD

**Issue by Eduardo3382** [laurent22/joplin#5266]
After doing several testing relate to this plugin, Joplin showed an error (please check the entire Joplin's error message attached in this report). Mainly I have done several testing making a different MindMapp diagram. As I read there is some incompatibility with mermaid functionality after installing the plugin, I unflagged the statement (Enable Mermaid diagrams support) in Tools > Option > markdown menu option. And I have created this kind of diagram under this setup all the time. After closing the app when showing the error and opening it again, Joplin seems running well, except when I tried to change the application layout to set up back as I have configured before showing this issue. Also I wanted to recover the previous layout set up, disabling all the plugins installed, but Joplin showing the same error.
Please check it, and let me know how I can fix it. means, how I can change the app layout without this problem. 

Joplin version: Joplin 2.1.9 (prod, linux)
OS specifics: Ubuntu 20.04

[Joplin error Aug 04 2021.md](https://github.com/laurent22/joplin/files/6935264/Joplin.error.Aug.04.2021.md)

**Comment by JackGruber** [comment]
I think it's the same as: https://github.com/laurent22/joplin/issues/5111
This issue should be fixed in `pre-release 2.2.2`, could you check if the pre-release fix the error for you?

**Comment by Eduardo3382** [comment]
Hi Jack 
Thanks for your prompt answer. Sorry but I could not find the mentioned previous issues. This looks like the same issue although the first was happened after updating Joplin and in my case was working using this plugin, but right, seems a similar issue. Unfortunately, I do not know how to update Joplin with a pre-release version, I used to update it first using appimage and recently using script recommended on Joplin website, both today are 2.1.9. How can I update Joplin with this pre-release version?

**Comment by JackGruber** [comment]
Both errors have to do with a layout change: `TypeError: Cannot read property 'maxSize' of null`

Download the pre-release from the GitHub release page: https://github.com/laurent22/joplin/releases/tag/v2.2.2
But I think when you wait one or two hours then possibly the version `v2.2.3` is released.

**Comment by Eduardo3382** [comment]
Hi Jack
I could updated with your suggested version 2.2.2 and finally I could restore my previous layout without any problems. I will close this issue accordingly. Thanks a lot.
