### ISSUE TITLE
"Dropped file type not supported" Notification

### ISSUE THREAD

**Issue by ehamminga** [laurent22/joplin#5268]
Using the WYSIWYG editor,  when I drop a file in my note that has a unknown extension to the editor (such as pptx or even txt), Joplin prompts me with a notification that the dropped file is not supported:
![image](https://user-images.githubusercontent.com/16200113/128330337-42244b4a-b203-4d4b-94bc-b4fe55bf6ec2.png)
But the file uploads just fine into Joplin and I can open them as well from the WYSIWYG editor. So should this notification even be here?

The other thing (this may be more of a feature request) is that the notification persists even when I change to other notes and the only way to dismiss it is to click the "X" next to it. This is becoming quite cumbersome when you have many links to add. Can we add an option to dismiss this notification permanently, or have it disappear after a while?

## Environment

Joplin version: 2.1.9
WYSIWYG editor
Platform: Windows 10
OS specifics: 2H20

## Steps to reproduce

1. Select a file with a .pdf extension (test page.pdf) in Windows Explorer
2. Drop the file in the WYSIWYG editor
3. Get prompted with "Dropped file type not supported" notification
4. Dismiss notification
5. Right click the dropped attachment in the WYSIWYG editor and open the file in its respective program

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/6937848/log.txt)

**Comment by githubrajodiya** [comment]
desrfeswrwe

**Comment by BabyLoves** [comment]
no one?

**Comment by laurent22** [comment]
no one what? The bug was fixed 2 years ago
