### ISSUE TITLE
Using KaTex to indicate that the fraction is displayed incorrectly

### ISSUE THREAD

**Issue by HuaWang135608** [laurent22/joplin#5279]
## Environment

Joplin version: 2.1.9
Platform: Linux
OS specifics: Ubuntu 20.04.2 LTS

## Steps to reproduce

1. Using \frac{a}{b} to display a fraction but there is not fraction line.
2. 
3.

**Comment by laurent22** [comment]
Probably you need to change your zoom level.

**Comment by JackGruber** [comment]
The same as https://github.com/laurent22/joplin/issues/4194, witch is a zoome problem ?

**Comment by HuaWang135608** [comment]
> Probably you need to change your zoom level.
The problem was resolved after adjusting to 1.0. But it was too small, so I went back to 1.25. Thanks for your answer.

**Comment by tessus** [comment]
Duplicate of #4194
