### ISSUE TITLE
Background sync not working in Android 8

### ISSUE THREAD

**Issue by hfccgit** [laurent22/joplin#5280]
Hi,
In my Android phone (Huawei P10) it never syncronised while the Joplin app is in background (in foreground works fine). It is not restricted in the battery saving configuration and I tried "locking" it (so it is always running) without success.

Just wanted to know if it's a particular thing in my case (maybe the old Huawei android version interferes with it) or if it's the way it works.

## Technical info
OS 1: Android 8.0.0 (Huawei P10 (VTR-L09) phone) with EMUI 8.0.0 (Huawei layer). In the battery saving options it is set to be allowed to run in background without limitations. I also tried "locking" it (so it is always running) without success.
OS 2: Windows 10 Pro 21H1 compilation 19043.1151 with Windows feature experience pack 120.2212.3530.0. 

Android App version: Joplin 2.1.4. (got the same result with much older versions as well, this never worked for me).
Windows App version: Joplin 2.1.9 rev. 882d66383.

Sync target: Dropbox with encryption.

## Reproduction steps
1-Delete a note in Joplin for Windows, then sync it with the button Synchronise.
2-Close/set the Android Joplin app to background. 
3-Wait more than 5 minutes (sync interval is set to 5 minutes).
4-In the Android client the note is not deleted. It will delete it (sync) as soon as you bring the app to the foreground.

## Describe what you expected to happen
I expected to have the notes already syncronised when I open the Android App.
Instead, when I bring to the foreground the app, it starts syncing and I have to wait until the notes are updated.

## Logfile
[syncReport-1628452662622.txt](https://github.com/laurent22/joplin/files/6951379/syncReport-1628452662622.txt)

Thanks.

**Comment by JackGruber** [comment]
Joplin has no backround sync on mobile devices at the moment!

**Comment by hfccgit** [comment]
Ok, thanks for confirming JackGruber.
