### ISSUE TITLE
Formatting Broken on Plugin Page

### ISSUE THREAD

**Issue by qdzlug** [laurent22/joplin#5285]
## Environment

Plugin Landling Page

## Steps to reproduce

1. Go to Landing Page
2. View formatting.

![image](https://user-images.githubusercontent.com/5490145/128880971-b1d6151e-e44f-4780-9155-54e752012c7d.png)

## Describe what you expected to happen
Formatting is correct.

## Logfile

None

**Comment by laurent22** [comment]
Thanks, that's fixed now.
