### ISSUE TITLE
After Joplin update from 2.2.2 to 2.2.4 LinkGraph-Plugin won't work

### ISSUE THREAD

**Issue by kai452** [laurent22/joplin#5289]
Hi,
even new build with workaround (https://discourse.joplinapp.org/t/19278) doesn't help, to make the plugin work.
Also the Plugin-Icon will not be shown anymore.

## Environment

Joplin version: 2.2.4
Platform: Win 7
OS specifics: Home

## Steps to reproduce

1. Update from 2.2.2 to 2.2.4
2. 
3. 
[-1628658236370.log](https://github.com/laurent22/joplin/files/6965984/-1628658236370.log)

**Comment by CalebJohn** [comment]
Hi @kai452, the link graph plugin has not been updated by it's author to work with Joplin version 2.2.4. Please file a bug report [with them](https://github.com/treymo/joplin-link-graph) to get this fixed.
