### ISSUE TITLE
Wrong cursor position display 

### ISSUE THREAD

**Issue by julienmthn** [laurent22/joplin#529]
### Operating system

- Windows

### Application

- Desktop 

### Version

1.0.93
32 bits

### Issue

Hi,

An issue with the cursor position display were it's off on the right (see below). 

[Cursor Display](https://www.dropbox.com/s/7oe1f6y7oc3racl/Joplin-cursor-entry.png?dl=0)
[Text placement](https://www.dropbox.com/s/2dh5haumrd0de9f/Joplin-after-typing.png?dl=0)

Thanks, julien

**Comment by foxmask** [comment]
Hi, your links lead to a 404 .

does this issue is related to #520 ?

**Comment by julienmthn** [comment]
Hi, sorry about the links its fixed now.

No it's not related, it's really about the cursor position in every notes that is not displayed where the text entry is.

**Comment by laurent22** [comment]
Right, please only use monospace fonts for the editor as non-fixed size fonts will indeed show this bug at the moment. I will add some info in the doc about it.
