### ISSUE TITLE
joplin not responding when draw mermaid with indentation

### ISSUE THREAD

**Issue by shelllee** [laurent22/joplin#5295]
platform：Windows10

![image](https://user-images.githubusercontent.com/11704124/129205487-04664577-3c88-4a78-8230-f9813a1740a9.png)

1. encryption is enabled
2. mermaid gitGraph works well without indentation 
3. i could click the menu but nothing render out, seems the render run into an infinite loop
4. i installed only one plugin: PlantUML

**Comment by laurent22** [comment]
what does it do? It's frozen or just slow?

**Comment by roman-r-m** [comment]
Are you sure it's about the indentation?

I was trying to reproduce it and was typing the note (a JEX would have helped btw :wink: ) and as I got to the 1st 
```
commit
commit
```
Joplin froze. This was without any indentation - was planning to add it later.

**Comment by roman-r-m** [comment]
Well, what do you know - there's an open issue in the mermaid-js repo with pretty much the same code: https://github.com/mermaid-js/mermaid/issues/1677

**Comment by laurent22** [comment]
Infinite loop crash that's not fixed after one year. A bit worrying but let's see if they'll eventually fix it.

**Comment by shelllee** [comment]
> what does it do? It's frozen or just slow?

1. seems frozen，the menu could clicked，but nothing popup (maybe the render not work?)
2. cpu 20%+

**Comment by shelllee** [comment]
> Are you sure it's about the indentation?
> 
> I was trying to reproduce it and was typing the note (a JEX would have helped btw 😉 ) and as I got to the 1st
> 
> ```
> commit
> commit
> ```
> 
> Joplin froze. This was without any indentation - was planning to add it later.

not sure, but joplin works well without indentation.
