### ISSUE TITLE
Desktop: Additional styling enhancements

### ISSUE THREAD

**Issue by CalebJohn** [laurent22/joplin#5297]
As a followup to a comment in #5174. 
This is how inline and block code used to look.
![image](https://user-images.githubusercontent.com/2179547/129234420-fc9415e9-023f-499a-b1a7-2adffa541b76.png)

And here is how they look now

![image](https://user-images.githubusercontent.com/2179547/129234227-306be85f-a9c4-4396-ac5c-df32e9c6a6ed.png)

As mentioned, the primary issue is that for certain fonts, the inline code is not distinct enough and can get lost in text. The possible fixes are
1. Revert the color change for comments
2. Update theme.codeColor to be a bit more colourful
3. Update the parser to apply a custom style to just inline code blocks (would also be nice to update the code block styling to be more colorful as well).

Let me know what you think, I don't have the availability to jump on this, but if one of the first 2 issues are preferred then we can make this a good first issue.

**Comment by a13xk** [comment]
The styles in older versions (at least in 2.1.9) were more convenient, imho. With new style it is much harder to distinguish inline code insets (wrapped in single ticks) from regular text. Code blocks (wrapped in tripple ticks) also look almost the same.

I vote for fix #2.

**Comment by laurent22** [comment]
So part of the issue I guess is that the comment and code blocks have the same colour? Is it possible to assign two different ones to them?

When I've implemented this I tried to apply the same style to inline code as in the preview, which is with a gray background and round border `like this`, however that cannot work in CodeMirror as the inline code is split into multiple elements.

However, I agree the difference between code and regular text is not sufficient at the moment so we should do something.

**Comment by CalebJohn** [comment]
> So part of the issue I guess is that the comment and code blocks have the same colour? Is it possible to assign two different ones to them?

I don't think this is part of the issue. They were the same colour before.

> When I've implemented this I tried to apply the same style to inline code as in the preview, which is with a gray background and round border like this, however that cannot work in CodeMirror as the inline code is split into multiple elements.

It might be possible to update the Joplin Codemirror mode to handle this. At the very least we could use a regex overlay. I can take a look.

**Comment by antoniopaolini** [comment]
I think that we should have an option to switch between the old beloved markdown editor's style and the new "enhanced" without mess with css.
There's possible?
This solution will be good for all not liked the change in https://github.com/laurent22/joplin/pull/5174#issue-687206305

**Comment by CalebJohn** [comment]
Hi @antoniopaolini you can check the forum to get updated on the plans of Joplin around this. Basically, the hope is to make it possible to easily switch styling.

**Comment by antoniopaolini** [comment]
> Hi @antoniopaolini you can check the forum to get updated on the plans of Joplin around this. Basically, the hope is to make it possible to easily switch styling.

Hi @CalebJohn ,  Thanks.
I spent a day wandering between github and discourse and saw all the discussions.
Maybe I wrote a couple of comments too in advance. :-)
