### ISSUE TITLE
Desktop: Note search bar should have a text warning with the background colour change.

### ISSUE THREAD

**Issue by CalebJohn** [laurent22/joplin#5299]
[ref](https://discourse.joplinapp.org/t/styling-the-background-of-search-box-when-nothing-found/19426)

Currently, a user's only indication that the text they are looking for is not found, is the background colour of the search box
![image](https://user-images.githubusercontent.com/2179547/129286835-439e0396-6b3f-40a0-af94-e5d70c30d8a9.png)
Not only is this an issue for accessibility, it's not always clear what the colour is trying to indicate
![image](https://user-images.githubusercontent.com/2179547/129286887-3585397c-f767-4892-ab4a-6f2a5e9a8a13.png)

This feature fix will have 2 parts
1. Check the [themes](https://github.com/laurent22/joplin/tree/dev/packages/lib/themes) and choose a more appropriate [`warningBackgroundColor`](https://github.com/laurent22/joplin/blob/dev/packages/lib/themes/dark.ts#L49).
2. Update the [`NoteSearchBar`](https://github.com/laurent22/joplin/blob/dev/packages/app-desktop/gui/NoteSearchBar.jsx#L113) to display the text `No matches` (or something similar)
  - Remember to localize the search task, please ask if you don't know how to do this

This is an example of how it's done in firefox, the text on the right is the important part here
![image](https://user-images.githubusercontent.com/2179547/129287493-93d23b8d-165a-4a86-9bb7-1de563696a2b.png)

**Comment by thesunshade** [comment]
I agree that the text message is most important. As far as colors, red is a universal (???) warning color. But red is also a common colorblind problem.

I like the FireFox color solution of using a red outline. Having a red background color would probably be too intense. I'd also question the logic of allowing themes to choose this color. To me it falls more in the realm of function rather than style. In any case having a text message is necessary.

**Comment by sif** [comment]
It may be a separate issue but this is for searching in notes itself. What about the search in the note panel? 

<img width="252" alt="a" src="https://user-images.githubusercontent.com/327998/129460493-5e221e59-bece-42e5-9a28-3d969ba28e0c.png">

**Comment by CalebJohn** [comment]
Hi @sif, I don't understand your comment. This issue is in regards to the in-note search box. The global search (as seen in your image) does not exhibit the same problem.

**Comment by nik-gautam** [comment]
Hi,
I would like to work on this issue.

**Comment by CalebJohn** [comment]
@nik-gautam Go ahead.

**Comment by nik-gautam** [comment]
Hi,

So, I tried a few things. Can you please tell me if they look fine?

For Dark Theme:
![Screenshot from 2021-08-19 22-58-15](https://user-images.githubusercontent.com/40800932/130116005-a4a3d3a3-754e-4eb4-8736-1117be180342.png)

For Light Theme:
![Screenshot from 2021-08-19 22-58-41](https://user-images.githubusercontent.com/40800932/130116036-3671b6b6-ffa5-467c-b198-162ba3254a4f.png)

**Comment by CalebJohn** [comment]
@nik-gautam looks like you've got it! The only issue i can see is in your choice of background colour. The white text on a red background is difficult to read. You should use the dev tools to ensure that the contrast is sufficiently high.

**Comment by nik-gautam** [comment]
@CalebJohn, I have a few doubts.

1> Is this color better?
![Screenshot from 2021-08-20 09-23-25](https://user-images.githubusercontent.com/40800932/130176730-93dbb63a-fe5e-4fd7-a672-c95712892b47.png)

2> The file  [`NoteSearchBar`](https://github.com/laurent22/joplin/blob/dev/packages/app-desktop/gui/NoteSearchBar.jsx) is in JS now, so should I be converting to TypeScript before sending a pull request?

**Comment by thesunshade** [comment]
> 1> Is this color better?
> ![Screenshot from 2021-08-20 09-23-25](https://user-images.githubusercontent.com/40800932/130176730-93dbb63a-fe5e-4fd7-a672-c95712892b47.png)

Were you able to try just putting a red border on the text box instead of using a background change? Like in the firefox example above?

That way there is no readability issue and it could be the same for both light and dark themes.

**Comment by CalebJohn** [comment]
@nik-gautam 
1. Much better, please also confirm that the warning bar in Tools -> Options -> Encryption looks good with this colour (they share the theme colour if I remember correctly). You'll also need to confirm that this looks good using the themes that inherit from the dark theme (or change them if not)
2. Since this is such a small change, I would say no.

> Were you able to try just putting a red border on the text box instead of using a background change? Like in the firefox example above?

It wouldn't hurt to look in to this, but users can often be resistant to change so I'm a bit hesitant to push this too far.

**Comment by nik-gautam** [comment]
@CalebJohn  and @thesunshade  

so, I tried changing the border colour like the firefox example.

Here are the screenshots:-

- Light Theme w/ Border Color:-
![Screenshot from 2021-08-20 11-49-58](https://user-images.githubusercontent.com/40800932/130190356-2759c809-7759-42c9-a1ba-11dffd5f720b.png)

- Light Theme w/ Background Color:-
![Screenshot from 2021-08-20 11-57-55](https://user-images.githubusercontent.com/40800932/130190550-f847481e-30a8-46d6-9de2-141cdb69c308.png)

- Dark Theme w/ Border Color:-
![Screenshot from 2021-08-20 11-49-29](https://user-images.githubusercontent.com/40800932/130190602-11b7fd24-8f82-4b8f-ada8-87482f2893f9.png)

- Dark Theme w/ Background Color:-
![Screenshot from 2021-08-20 11-58-19](https://user-images.githubusercontent.com/40800932/130190645-e614bb70-cc12-47d1-ae11-3d8a0a95d7c8.png)


Personally, I like the whole background colour red, as the input area is quite small and the larger area with red colour brings more attention.


Also, The encryption tab looks fine with the new warning color:-
![Screenshot from 2021-08-20 11-28-35](https://user-images.githubusercontent.com/40800932/130190721-bc66d956-4ef3-4edf-afe5-cae59776609e.png)
![Screenshot from 2021-08-20 12-05-29](https://user-images.githubusercontent.com/40800932/130190790-f7b3af57-38e2-48ce-978d-8018685cf121.png)

I also found one place where the warning colour was used:-
![Screenshot from 2021-08-20 11-51-08](https://user-images.githubusercontent.com/40800932/130190866-5d6c5ab2-fef1-4631-b122-1fde38cef89d.png)

I tried to look for more places where this colour is used this is all I found. If I am missing some place, please remind me.

Also, can you tell me how to go about the localization for the "Phrase not found" string?

**Comment by thesunshade** [comment]
> users can often be resistant to change so I'm a bit hesitant to push this too far.

Indeed they can! 

Thanks @nik-gautam for your work on this!!

**Comment by nik-gautam** [comment]
> Thanks @nik-gautam for your work on this!!

It's my pleasure :)

**Comment by nik-gautam** [comment]
@CalebJohn can you help out with this part? I am a bit confused about how to go about doing this.

> Remember to localize the search task, please ask if you don't know how to do this

**Comment by CalebJohn** [comment]
@nik-gautam please make a PR and we can continue the discusy there. At this point it's easier to talk about the code.
