### ISSUE TITLE
Resource link replacement doesn't work for <video> and <audio> like it does for <img>

### ISSUE THREAD

**Issue by ConstantineRudenko** [laurent22/joplin#5304]
## Environment

Joplin version:
```
Joplin 2.2.7 (prod, win32)

Client ID: 58b03205dc4940328a33b346b2771cb9
Sync Version: 2
Profile Version: 39
Keychain Supported: Yes

Revision: 6d1a2e2
```
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

Create a note with following text:

```markdown
# Images

This works:
<img src=":/aa9b4480d6e64bc8b3b78f9d12fff0fc" width="300px"/>

And this works:
![image.jpg](:/aa9b4480d6e64bc8b3b78f9d12fff0fc)

# Audio and Video

This works:
[video.webm](:/a0953eb8b04b4529a6caa79e578efe58)
[music.mp3](:/1c966fd87dfc4ffc9709b796d70b2e7c)

This doesn't work in joplin, but does work in HTML export:

<video width="200px" controls>
<source src=":/a0953eb8b04b4529a6caa79e578efe58" type="video/mp4">
</video>

<audio controls>
  <source src=":/1c966fd87dfc4ffc9709b796d70b2e7c" type="audio/mpeg">
Your browser does not support the audio element.
</audio>

Note: if I remove the empty line between the text and <video>, it doesn't work in HTML export
```

Resource links are always correctly replaced for images - both in `<img>` html tags and markdown images.

For videos resource links are not replaced in html tags when viewed in joplin, but they are replaced correctly in html export.

If there is no empty line between previous text and `<video>` or `<audio>`, the links are no longer correctly replaced in html export. `<img>` does not suffer from this issue.

**Comment by ConstantineRudenko** [comment]
I am unfamiliar with joplin code, but from looking at the repo I suppose this is responsible for replacing resource links in `<img>`

https://github.com/laurent22/joplin/blob/80b16dd17e227e3f538aa221d7b6cc2d81688e72/packages/renderer/MdToHtml/rules/html_image.ts#L29-L41

video and audio tags do not appear to have similar functions for handling them

**Comment by quancs** [comment]
Hi, is there any update for audio?
