### ISSUE TITLE
Black/White screen when Joplin is set to start minimized

### ISSUE THREAD

**Issue by zerog981** [laurent22/joplin#5305]
When Joplin is set to open minimized and close to tray, only a blank black/white window is shown. Despite not opening in background the full window can be activated by clicking on the tray icon. For better understanding I made a short recording of my screen:
[https://pasteboard.co/KfPGAqt.gif](https://pasteboard.co/KfPGAqt.gif)

Some other users reported presumably the same problem in issue #4361 and #5054.

## Environment

Joplin version: 2.2.7 (prod, win32)
Platform: Windows
OS specifics: 20H2 Build 19042.1165

## Steps to reproduce

1. Set Joplin to open minimized
2. Close Joplin
3. Open Joplin again
4. Click on the tray icon to see the full window

## Describe what you expected to happen
Joplin should open in background without showing any window at all.

## Logfile
I did run Joplin in debug mode, but there are no related issues in the logfile or the console. The console only shows a lot of warnings related to SourceMap ("DevTools failed to load SourceMap").

**Comment by fulljackz** [comment]
Hi,

Just to confirm I have the same behavior here with Ubuntu 21.04 and Joplin 2.3.5 (app image installed with script) on Gnome 3.38.4.

Regards,

**Comment by zerog981** [comment]
Resolved as of Version v2.5.8 (dbdb82d). Thanks for your hard work.
