### ISSUE TITLE
Markdown syntax highlight of list items disappears after searching and clicking on a note

### ISSUE THREAD

**Issue by davidcopano** [laurent22/joplin#5306]
## Environment

Joplin version: Joplin 2.2.7 (prod, win32)
Platform: Windows 10
OS specifics: Pro Edition, 21H1

## Steps to reproduce

1. In the "Search..." text input, type any text in order to find a note or notes
2. Click on a found note, syntax highlight of list items of the clicked note is missing
3. Currently I have to restart Joplin in order to appear syntax highlight for list items

## Describe what you expected to happen

Syntax highlight of list items should remain after searching notes

## Logfile
[-1628938455002.log](https://github.com/laurent22/joplin/files/6986334/-1628938455002.log)

![06f3b6799180ca0989763332a504afaf](https://user-images.githubusercontent.com/11613428/129444163-95731a7d-84c3-46eb-b152-a96d96b568ac.gif)

**Comment by nablabits** [comment]
I've been noticing this issue a few ago, it not only happens with the list of items but with code overall where, for instance, keywords loose their color.
After skimming the console this could be the bit creating the issue:
![image](https://user-images.githubusercontent.com/33068707/133893853-1bcadeb1-59e3-4eb4-8118-f13a95f2b3ac.png)

That leads to https://github.com/highlightjs/highlight.js/issues/2277 where the following is recommended:
```js
// before
html = highlight("vbscript","your code goes here", true)
// after
html = highlight("your code goes here", {language: "vbscript", ignoreIllegals: true })
```

As of today we have only a couple of calls to `highlight` here:
* https://github.com/laurent22/joplin/blob/43c594b6b21b703f7cb5c0ca32f382cc2d32d61c/packages/renderer/MdToHtml/rules/fence.ts#L24
* https://github.com/laurent22/joplin/blob/43c594b6b21b703f7cb5c0ca32f382cc2d32d61c/packages/renderer/MdToHtml.ts#L470

I'm not a ts expert but it feels pretty straightforward so happy to open a PR if needed

**Comment by Daeraxa** [comment]
I think there was a reference to this or something similar on discord. Does it still happen on the latest pre-release?

**Comment by nablabits** [comment]
Well, I spotted in [2.4.1](https://github.com/laurent22/joplin/releases/tag/v2.4.1) this folk https://github.com/laurent22/joplin/pull/5333 that looks a good candidate, however the way they solved is different and although it will work for lists, it might not fix the problem with the syntax highlighting...

**Comment by neunenak** [comment]
I'm also noticing this issue on Joplin desktop version 2.3.5 (I was just about to report it myself). In my case what I see is that for the very first note I open up in Joplin, I see the expected Markdown syntax highlighting. If I switch to any other note, the highlighting goes away; and switching back to the original note also now has no highlighting.
