### ISSUE TITLE
Desktop: Search not functioning properly

### ISSUE THREAD

**Issue by opsydev** [laurent22/joplin#5313]
The search in the sidebar only searches full words when searching for note titles. 

## Environment

Joplin version: Joplin 2.2.7 (prod, darwin)
Platform: MacOS 
OS specifics: Big Sur 11.5.2 

## Steps to reproduce

1. Have a few notes in the current notebook
2. Search in the sidebar for note titles
3. Some searches return as expected others return nothing

My current notes in a notebook:
![image](https://user-images.githubusercontent.com/3767518/129460130-d4783f8a-3ee5-4c8d-8d39-f498a684e79b.png)

Searching for `refund` returns correctly:
![image](https://user-images.githubusercontent.com/3767518/129460143-83f124a6-42a2-4bd0-b00f-4819399406cc.png)

But searching for `Flight` returns nothing, you have to search for full `flighthub`
![image](https://user-images.githubusercontent.com/3767518/129460153-80fd9e2e-38e6-4fd8-b0e2-a28d10654ea1.png)

Searching for a single character seems to return but only searches the note body  
![image](https://user-images.githubusercontent.com/3767518/129460217-b61a43e5-66e1-4378-8ad9-a7cd7e04725d.png)

But more than one character doesn't return anything
![image](https://user-images.githubusercontent.com/3767518/129460233-3405300f-90a6-4e39-853f-09b2eb848c70.png)

## Describe what you expected to happen

The search in the sidebar should work for partial words/characters just like it does in the global search
![image](https://user-images.githubusercontent.com/3767518/129460268-d4271afc-2185-4d12-898e-79cb8effc3ad.png)

## Logfile

Nothing additional was available in the console errors, hence not attaching anything.

**Comment by JackGruber** [comment]
No a bug, by design.
![grafik](https://user-images.githubusercontent.com/24863925/129461037-36e21750-30e7-4f7e-ac88-3158b8f68ef2.png)

https://joplinapp.org/help/#searching

**Comment by opsydev** [comment]
Ah,  I missed that. I'll close this bug.
