### ISSUE TITLE
mismatch between font size of code editor and viewer

### ISSUE THREAD

**Issue by omega3** [laurent22/joplin#5316]
This is follow-up  of 
https://github.com/laurent22/joplin/issues/3863
Still valid bug

**Comment by CalebJohn** [comment]
Hi @omega3 I don't quite understand what you're reporting. It seems like the bug is that when you change the editor font size, the viewer font size doesn't change to match? If so that's not a bug. By default the application sets the editor and viewer font sizes to be the same, but if the users adjusts the editor font size, it's expected that they would now be different.

**Comment by omega3** [comment]
Aha. That is strange to me. I don't understand the reasoning behind it. Why would someone want to have different font sizes in  editor and viewer?

Would it be possible to have separate settings in options for viewer font size so that they can match?

Feel free to change the label to feature request.

**Comment by Anubhav-developr** [comment]
can you provide sc of the issue

**Comment by omega3** [comment]
I don't understand what sc means. Sorry I am not a programmer. Do you mean why I need this? 
Because I read my notes in viewer mode and I like bigger fonts, above 30.
Even if it is possible to set font in some css file it is note very intuitive solution. I am a type of user that treat Joplin not as markdown editor but just a notebook with backlinks.

**Comment by CalebJohn** [comment]
@omega3 just for your information, the Joplin interface (and viewer) can be scaled in the View menu (Zoom in). That's the official way to get a larger font for the viewer.

**Comment by Anubhav-developr** [comment]
sc meant for screenshot , sorry sir for using short forms
i am new to this community but now i am understanding what's going on here
now i will try to see my own
does joplin had its code editor? like i had used it as a notes application from play store and i know nothing much about it.

**Comment by omega3** [comment]
@CalebJohn
> Joplin interface (and viewer) can be scaled in the View menu (Zoom in).

That is great that I can zoom in and I can live with that but it is very strange behavior that there is a difference between two views. I hope it will get attention of Joplin developers.

@Anubhav-developr
I linked to 3863 issue where I linked to screenshots. 

>  i had used it as a notes application 

So do I.

> does joplin had its code editor?

I don't know. Maybe ask on Joplin forum.
https://discourse.joplinapp.org/

**Comment by bradonomics** [comment]
Editing the stylesheet at `~/.config/joplin-desktop/userstyle.css` as discussed in the [forum thread](https://discourse.joplinapp.org/t/is-there-a-way-to-edit-the-preview-font-size/1778), does work, but I agree with @omega3, changing the editor font size should also change the viewer (rendered Markdown) font size.

@CalebJohn, perhaps a second option in the settings for changing the editor and the viewer font size would be a better approach than requiring users to edit stylesheets?

**Comment by CalebJohn** [comment]
@bradonomics the official way to change the viewer size is to zoom in app in and out. The userstyle is meant for advanced users that want more fine grained country over styling.

That said, having the ability to change the viewer font size alone make sense to me. In general, feature requests should start life on the [forum](https://discourse.joplinapp.org/) so the community has a chance to discuss and decide if it's broadly desirable.

**Comment by omega3** [comment]
@CalebJohn
This bug report is not about the viewer size but about mismatch between font size of code editor and viewer. The title and screenshots explain it. I think the font size setting in options should affect both the editor and viewer.

> In general, feature requests should start life on the forum so the community has a chance to discuss and decide if it's broadly desirable.

In general it is a good practice, but in this case there is much to discuss about. Anyway, I started a new [thread on forum](https://discourse.joplinapp.org/t/match-font-size-of-code-editor-and-viewer/20333) foe other users to discuss. 

Does someone need this  two different sizes as if it was a feature. I doubt. 

For example in MS Word you have editing mode and preview which shows how document may look like in printing. Would it make sense to have different font sizes in these two modes? No.

Viewer in Joplin is a preview of how you style text, so there is no logical explanation for this mismatch. 

> By default the application sets the editor and viewer font sizes to be the same, 

So it should stay this way. 

> but if the users adjusts the editor font size, it's expected that they would now be different.

What is the reason for increasing editor font size? To see better. How can I want to see better editor and not want to see better normal view? This just doesn't make any sense to me. 

 And if they don't match I need to spend time to adjust both font sizes which is counter intuitive application behavior for me.

> having the ability to change the viewer font size alone make sense to me. 
I don't get why it does make sense to you. What this mismatch gives you if you consider it a feature?
Do you personally use different font sizes for editing and reading? If this is the case why? Because if not, maybe it means that it is not a feature but not well thought solution that needs further development.

**Comment by CalebJohn** [comment]
> I don't get why it does make sense to you. What this mismatch gives you if you consider it a feature?
Do you personally use different font sizes for editing and reading? If this is the case why? Because if not, maybe it means that it is not a feature but not well thought solution that needs further development.

The simple answer is that many users do not use the same font for the editor and the viewer. Many fonts are not standard in terms of size. This means that even if I'm using a single font size, the editor could have text that is too large for my liking, and the viewer could be too small! 

By default (recently) Joplin sets the editor and viewer to be the same font with the same font size (this was only recently possible due to some internal changes). This makes it trivial to use the zoom to get both fonts scaled to an acceptable size for the user. Joplin does still allow the user to select a custom editor font, in which case it can be helpful to scale the editor font size independently (as discussed above).

**Comment by omega3** [comment]
Thank you for clarification.

But now when I forgot what was the default value of editor font and I want to get back to it so that I can use Zoom in to make the two font sizes match it becomes a bit troublesome task. Now I need to do it by try and error approach.  As I understand the default value of editor font is a starting point for using Zoom to keep font size equal. 

Therefore I think there should be separate option for preview font size along with editor font size, so that users can manually adjust the values to whatever their preferences are or an option should be added to make them equal in whatever current values state they are. But one solution doesn't exclude the other. Maybe there could be two options to set font size for editor end preview and on top of that an option to make them equal at any time available as shortcut.

The conclusion from this discussion is that users use Joplin for different purposes and in different way.
Although it is now possible to make fonts equal it would be great if there were some options to make it easy and in more intuitive, in more obvious way. I hope developers consider this request valid.

**Comment by omega3** [comment]
Up. Please fix it.

**Comment by omega3** [comment]
Up. Please fix it.

**Comment by omega3** [comment]
Up.

**Comment by omega3** [comment]
Up.
This stupid bot...

**Comment by omega3** [comment]
stupid bot...

**Comment by omega3** [comment]
up

**Comment by omega3** [comment]
Please disable this stupid bot. If you haven't addressed this issue it is still valid.
