### ISSUE TITLE
Joplin using 12 GB of memory 

### ISSUE THREAD

**Issue by AdvisedlyAlburn** [laurent22/joplin#5318]
OS : MacOS 11.4
Joplin version : 1.7.11

On "Activity Monitor" it shows it uses 12.22 GB of memory (I have 16 GB max on my laptop)

**Comment by roman-r-m** [comment]
I know Linux memory reporting can be misleading (see https://www.linuxatemyram.com/), not sure about MacOS.
Can you try Help -  Toggle development tools - Switch to Memory and check the usage there.

![image](https://user-images.githubusercontent.com/995612/129490846-980ae7f9-3b4d-4dde-9d36-5b50c58e0b48.png)

**Comment by AdvisedlyAlburn** [comment]
I'll check that next time it consumes a lot. After I restarted Joplin it went down to 90 MB. But it's slowly going up, now it's at 340 MB. Maybe there's a memory leak (electron issue?)

**Comment by Derkades** [comment]
Have a look at `top` or `htop` (better), there will be a "virt" and "res" column. Virt is virtual memory, res is actual memory usage. I'm not sure which one of these your "Activity Monitor" application uses.
