### ISSUE TITLE
Linux version does not sync to Dropbox target version 3

### ISSUE THREAD

**Issue by abzolv** [laurent22/joplin#5319]
The latest iOS version (12.3.1) of Joplin "upgraded the sync target", which is on Dropbox.

Since then the latest Linux version of Joplin (2.1.9) does not want to sync to Dropbox. It says, "Sync version of the target (3) is greater than the version supported by the client (2). Please upgrade your client." But there is nothing new to upgrade to. I've tried both the Flatpak install and the AppImage downloaded directly from the Joplin website.

**Comment by tessus** [comment]
https://discourse.joplinapp.org/t/attention-sync-version-has-been-changed-in-2-3/19449?u=tessus
