### ISSUE TITLE
margins change when toggling side bars and window > 1200px

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#5320]
## Environment

Joplin 2.3.3 (prod, darwin)

Client ID: f0fae9cf413944909b85dc74743c2b72
Sync Version: 3
Profile Version: 39
Keychain Supported: Yes

Revision: 5c50ee9b1 (dev)

also happens with dev HEAD.

## Steps to reproduce

1. deactivate any custom css
2. start joplin
3. make sure Joplin window is wider than 1200px
4. toggle side bars

![margins](https://user-images.githubusercontent.com/223439/129591946-69a7c5a4-898d-4def-8ad3-07d94900d5d4.gif)

## Describe what you expected to happen

The margin between border and text should stay the same.

## Logfile

No errors in the log file or console.

**Comment by laurent22** [comment]
Is that 2.3.3 or your own build? Because it looks like a change I've recently implemented to limit width of the editor content, but that's not in 2.3.3.

If that's what it is, you can disable this behaviour by setting the width to 0 in Config > Appearance.

**Comment by tessus** [comment]
Yes, it is a binary from an `npm run dist` on 5c50ee9 (dev). Same thing happens when I run it directly from the tree via `npm start`.

And you are correct. Setting the width to 0 in `Config > Appearance` fixes this.

Sorry for the noise.

**Comment by tessus** [comment]
Just to be clear. I usually read the commit messages and check the code when a message sounds like it could have anything to do with a problem I encounter.
I screwed up the tags and thus didn't even see that commit. I'll be more careful next time...

**Comment by laurent22** [comment]
No problem, it could have been a bug, and if that's what it was it's better to know about it now than later.
