### ISSUE TITLE
Multilevel list styles are broken

### ISSUE THREAD

**Issue by AKolomoets** [laurent22/joplin#5327]
## Environment

Joplin version: 2.2.3
Platform: Windows 8/1
OS specifics: 

## Steps to reproduce

1. Create Note with multilevel list, for example:
- Item 1
  - Item 2
    - Item 3
      - Item 4

- text style is the same for different list levels in edit window
- list markers are the same from 3d level in view window

## Describe what you expected to happen

- text style should be different depending on list level in edit window (as it were in previous Joplin versions, e.g. yellow for 2d level , violet for 3d level etc.)
- list markers should differ depending on the list level (or at least iterate over some sycle, as it were in previous Joplin versions, e.g. star, circle, square, triangle, star, circle, square, triangle...).

**Comment by AKolomoets** [comment]
Now it works like this: 
![image](https://user-images.githubusercontent.com/47663960/129744929-82e82f39-6b3b-4b6b-b470-f0ba8510c7b2.png)

**Comment by AKolomoets** [comment]
This is the log file
[log.txt](https://github.com/laurent22/joplin/files/7000902/log.txt)

**Comment by AKolomoets** [comment]
When I restart the Joplin app the color styles are applyed
![image](https://user-images.githubusercontent.com/47663960/129748072-28343eae-caef-417a-bbbd-6490283b0bfc.png)
When I switch between notebooks and return back colors disappear

**Comment by CalebJohn** [comment]
@AKolomoets 
Thanks for reporting this. A fix is on the way.
