### ISSUE TITLE
"Toggle Editors" changes list type

### ISSUE THREAD

**Issue by dima-0** [laurent22/joplin#5329]
## Environment

Joplin version: 2.3.3 (prod, win32)
Platform: Windows 10 Pro
OS specifics: 20H2, Buildversion 19042.1110

## Steps to reproduce

1. Create new note
2. Make a bullet list with one item
3. Make a separate check box after a new line
4. Press "Toggle Editors" to turn on the two sided layout (markdown editor + preview)
5. Press "Toggle Editors" to turn off the two sided layout (markdown editor + preview)

After turning off the two sided layout, both items are rendered as checkboxes.

initial state
![3](https://user-images.githubusercontent.com/45599680/129791214-677f4ce2-f871-42dd-9739-a6bdae4909f2.PNG)

two sided layout on
![1](https://user-images.githubusercontent.com/45599680/129790852-3d832321-eff4-4e41-a389-b51b9b1d58d6.PNG)

two sided layout off
![2](https://user-images.githubusercontent.com/45599680/129790944-8a46d8ee-0faf-498a-b4be-5ba1f4bc0b46.PNG)

## Describe what you expected to happen

List types should stay the same after toggle editors.

**Comment by Daeraxa** [comment]
Have a look at a similar issue I raised - its a limitation of the richtext editor where you cannot have multiple list types in the same list without some kind of non-list separator.
https://github.com/laurent22/joplin/issues/4286

**Comment by dima-0** [comment]
I see. Thanks for the hint.
