### ISSUE TITLE
Allow replacing parser?

### ISSUE THREAD

**Issue by umgupta** [laurent22/joplin#533]
I wanted to add an external image whose size is too big and want to control its size. There is no way to do this w/o HTML tags. See: https://stackoverflow.com/questions/14675913/changing-image-size-in-markdown

I am not sure as to why HTML tags are not supported but can I replace the parser or switch it on just for myself easily

**Comment by laurent22** [comment]
`<img>` tags aren't supported yet for security reasons, but might be as part of a future update.

**Comment by umgupta** [comment]
I can help with that (if provided guidance). I don't understand the "security issues", but I would really like to be able to customise the parser / or have the ability to change parser easily (at least on the desktop app).
