### ISSUE TITLE
Microsoft365的OneDrive同步失败

### ISSUE THREAD

**Issue by xavierror** [laurent22/joplin#5330]
![image](https://user-images.githubusercontent.com/32238934/129823342-e86e9c2f-881c-46e1-8374-a77dabf9c521.png)
![image](https://user-images.githubusercontent.com/32238934/129823378-80a5f255-35c4-446a-829e-5a136ed26407.png)

**Comment by lz170212** [comment]
The same here.

**Comment by AyFun** [comment]
进onedrive，把应用文件夹重命名为Apps，
退出joplin再进，
我这样成功了。

**Comment by xavierror** [comment]
> 进onedrive，把应用文件夹重命名为Apps，
> 退出joplin再进，
> 我这样成功了。

有用

**Comment by micro-coder** [comment]
> 进onedrive，把应用文件夹重命名为Apps， 退出joplin再进， 我这样成功了。

多谢，用了filesystem方法间接解决onedrive同步问题。今天找到你这种方法，更直接地解决了

**Comment by wenxin8023** [comment]
> 进onedrive，把应用文件夹重命名为Apps， 退出joplin再进， 我这样成功了。

Thanks a lot！！！！！！！！！
