### ISSUE TITLE
Indent before text in latest version 2.3

### ISSUE THREAD

**Issue by Aman-Anas** [laurent22/joplin#5339]
There is a strange "indent" before text in all notes and to-do's that is affected by window resizing. This was not the case before I updated Joplin to 2.3.5 (previous version was 2.3.3). Besides that, everything else seems to work fine. There are no indents when viewing the notes on my phone, so I think it is a visual bug.

![image](https://user-images.githubusercontent.com/41600372/129943597-bec036d5-1339-4d2f-b673-6ca2f5fa85b4.png)
![image](https://user-images.githubusercontent.com/41600372/129943620-20a27012-f4b2-4b32-b4b3-d22344d58421.png)
![image](https://user-images.githubusercontent.com/41600372/129943645-68ddccd7-b1f5-41e1-8306-394e1dd06d58.png)

## Environment

Joplin version: 2.3.5 (prod, win32)
Platform: Windows
OS specifics: Windows 10 21H1

## Steps to reproduce

1. Update to Joplin 2.3.5
2. Open a note or to-do that has text in it

## Describe what you expected to happen

I expected my text to be left-aligned as usual. 

This issue does not occur in split-screen view (with plaintext on left and markdown on right), but occurs in full plaintext, full markdown, and WSIWYG editor. Already have tried quitting and restarting Joplin a few times :P

**Comment by Daeraxa** [comment]
https://discourse.joplinapp.org/t/please-read-this-if-you-are-wondering-why-theres-now-a-margin-on-the-note-text/19585

does the above thread solve the problem?

**Comment by tessus** [comment]
Closing. It's pinned anyway.

**Comment by BeatLink** [comment]
My recommendation is that the width be set to 0 *by* default. This would be more in line with principle of least astonishment by having the interface act the same with previous versions. Users can then discover the new feature in their own time, either via the changelog, blog post or other update mechanism.

**Comment by MHoeller** [comment]
There was a change in the styling. class rendered-md has now magring-left: auto
i suggest to change this to margin-left: 10px 

![version 2 4](https://user-images.githubusercontent.com/11714953/133209976-fe2fd294-90d7-4a93-b939-437ceb6219c7.png)

**Comment by Cristy94** [comment]
> **My recommendation is that the width be set to 0 _by default._**
> 
> This would be more in line with principle of least astonishment by having the interface act the same with previous versions. Users can then discover the new feature in their own time, either via the changelog, blog post or other updates.
> 
> If the width is set to 0 by default, people would no longer be opening new issues regarding this change and this issue wouldnt need to be pinned

I completely agree with this, I was really surprised by the new alignment and it felt like the update failed or that Joplin is now broken. The biggest issue is that the new alignment doesn't look good by default/looks broken. The text is randomly floating (especially if the note is really short).

**Comment by zroug** [comment]
I like the idea of limiting the width but I feel that some kind of visual hint on the code side is missing. Currently it is very hard to navigate the indentation on lists, especially nested ones.

**Comment by dvogel** [comment]
I too think the max width should default to 0. However, if that isn't agreeable, then perhaps it could be explained better in the settings? I looked in the settings and was looking for something related to centering. The width setting didn't seem to apply because the vertical scroll bar was outside the extra space on the right side of the width-limited editor. You can see that in this cropped view of the lower right portion of the window:

![Screenshot from 2021-12-15 15-06-33](https://user-images.githubusercontent.com/45699/146265040-13698b77-b71d-4f3a-b63a-62f999e39f86.png)

Another reason the fixed width setting wasn't especially obvious to me is that I would be OK with that if it was left-aligned. IOW if all of the "extra" space around the editor was to the right of the editor pane.
