### ISSUE TITLE
[Feature Request] Show the notebooks name after searching for notes

### ISSUE THREAD

**Issue by alwashe** [laurent22/joplin#534]
### Operating system
- Windows

### Application
- Desktop

Sometimes I forget in which notebook I placed a note. I can find it by searching, but where is that note? It would be nice to display the name of the notebook I left the note.

**Comment by laurent22** [comment]
Closed as duplicate

**Comment by gerroon** [comment]
Duplicate of?

**Comment by laurent22** [comment]
This has actually been implemented. The notebook name is now displayed in the toolbar.

**Comment by gerroon** [comment]
@laurent22 

Thanks, would it be possible to clicking on it would take the user to the respective notebook?
