### ISSUE TITLE
Vertical line in all notes after upgrade to 2.3.5

### ISSUE THREAD

**Issue by g33k247** [laurent22/joplin#5343]
After upgrading to Joplin 2.3.5, all of my notes (and new notes) have a vertical line roughly 1/4-inch in from the left side:

![image](https://user-images.githubusercontent.com/8498814/129989556-2a69c693-cd8a-4a92-a949-640d65f6a6f4.png)

## Environment

Joplin version: 2.3.5
Platform: Windows 10
OS specifics: Latest insider build

## Steps to reproduce

1. Open any note in Joplin

## Describe what you expected to happen

1. No vertical line

**Comment by Daeraxa** [comment]
Are you using the text folding plugin by any chance?
https://discourse.joplinapp.org/t/persistent-text-folding-in-editor/16183/46

**Comment by mdgaa** [comment]
I had the same issue after upgrading to version 2.3.5 (MacOS). After I disabled the text folding plugin, the vertical line disappeared.
