### ISSUE TITLE
French translate mistake in update submit

### ISSUE THREAD

**Issue by jbfagotfede39** [laurent22/joplin#5345]
## Environment

Joplin version: 2.3.3
Platform: macOS
OS specifics: 10.13.6

## Steps to reproduce

1. Launch Joplin
2. Wait update check
3. Mistake in the ignoring button in French : `Ignorer cette versiojn`

## Screenshot
![Capture d’écran 2021-08-19 à 10 37 16](https://user-images.githubusercontent.com/15885207/130038753-4931d2bd-1d0d-46cb-901c-276301f267e8.png)

## Describe what you expected to happen
`Ignorer cette version` button
Mistake is in `fr_FR.po` file line 930 I think

**Comment by laurent22** [comment]
Thanks, it will be fixed in the next release
