### ISSUE TITLE
Web clipper can't connect to Joplin

### ISSUE THREAD

**Issue by WillRieske** [laurent22/joplin#5348]
The web clipper popup hangs on a 'Permission needed' screen instead of connecting to Joplin.

## Environment

Joplin version: 1.5.11 Portable
Platform: Windows
OS specifics: Windows 10 Pro 19042.1110
Browser: Firefox Portable 91.0

## Steps to reproduce
1. [Install the web clipper in Firefox](https://addons.mozilla.org/en-US/firefox/addon/joplin-web-clipper/)
2. Navigate to example URL: https://www.newyorker.com/magazine/2021/08/23/why-is-it-so-hard-to-be-rational
3. Start the web clipper service in Joplin options
 - shows:
```
The web clipper service is enabled and set to auto-start.
Status: Started on port 41184
```
![Joplin clipper service is started](https://user-images.githubusercontent.com/6845646/130072167-69d7227d-72d1-4b11-a877-b25442be6e6d.png)
4. Click the web clipper icon to activate it

## Describe what you expected to happen
Clipper windows opens and says:
```
Permission needed
Starting...
```
![Clipper 'Permission Needed' screenshot](https://user-images.githubusercontent.com/6845646/130072168-3a070dab-e233-47c3-a844-d963129f3a27.png)

## Logfile
```
Popup: Init bridge and restore state... index.js:111:9
Popup: Init bridge bridge.js:19:10
Popup: Env: prod bridge.js:82:10
Popup: Creating React app... index.js:115:9
findClipperServerPort: Trying 41184 bridge.js:254:12
findClipperServerPort: Got response: JoplinClipperServer bridge.js:257:12
Popup: Restoring saved state: 
Object { selectedFolderId: null }
bridge.js:242:10
Sending message  
Object { name: "isProbablyReaderable" }
bridge.js:392:10
Popup: GET auth/check bridge.js:398:10
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    e bridge.js:333
bridge.js:333:64
Uncaught (in promise) Error: {"error":"Not Found: \n\nError: Not Found\n    at Api.<anonymous> (C:\\Users\\rieskew\\AppData\\Local\\Temp\\1mFmFLDQjmu7zDBaoa6xNGTVwFI\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:71:23)\n    at Generator.next (<anonymous>)\n    at C:\\Users\\rieskew\\AppData\\Local\\Temp\\1mFmFLDQjmu7zDBaoa6xNGTVwFI\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\rieskew\\AppData\\Local\\Temp\\1mFmFLDQjmu7zDBaoa6xNGTVwFI\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:4:12)\n    at Api.route (C:\\Users\\rieskew\\AppData\\Local\\Temp\\1mFmFLDQjmu7zDBaoa6xNGTVwFI\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:64:16)\n    at execRequest (C:\\Users\\rieskew\\AppData\\Local\\Temp\\1mFmFLDQjmu7zDBaoa6xNGTVwFI\\resources\\app.asar\\node_modules\\@joplin\\lib\\ClipperServer.js:161:39)\n    at Server.<anonymous> (C:\\Users\\rieskew\\AppData\\Local\\Temp\\1mFmFLDQjmu7zDBaoa6xNGTVwFI\\resources\\app.asar\\node_modules\\@joplin\\lib\\ClipperServer.js:204:7)\n    at Server.emit (events.js:310:20)\n    at Server.EventEmitter.emit (domain.js:482:12)"}
    e bridge.js:427
    u runtime.js:45
    _invoke runtime.js:271
    t runtime.js:97
    Babel 10
    value main.chunk.js:1
    e bridge.js:129
    u runtime.js:45
    _invoke runtime.js:271
    t runtime.js:97
    Babel 6
    value main.chunk.js:1
    e bridge.js:104
    u runtime.js:45
    _invoke runtime.js:271
    t runtime.js:97
    Babel 8
    value main.chunk.js:1
    e App.js:187
bridge.js:427:9
Popup: Saving state 
Object { selectedFolderId: null }
```
![Console log](https://user-images.githubusercontent.com/6845646/130072164-7501e262-bc4a-4526-9013-f5b0573ffb82.png)

**Comment by JackGruber** [comment]
You need to upgrade to Joplin 2.1 or newer to use the new WebClipper.

**Comment by WillRieske** [comment]
Thanks! That solved it.
I noticed that after I upgraded, the 'Permission needed' screen in the clipper popup included a message (beyond just "Starting...") that indicated I needed to upgrade Joplin to 2.1.7. So, could we get something on the Joplin options page, or [add-on page](https://addons.mozilla.org/en-US/firefox/addon/joplin-web-clipper/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search), or [help page](https://joplinapp.org/clipper/) to indicate what version is required?
