### ISSUE TITLE
Latest AppImage (2.3.5) reports as 2.1.9 in About Joplin menu

### ISSUE THREAD

**Issue by madpipeline** [laurent22/joplin#5349]
## Environment

Joplin version: 2.3.5
Platform: Linux
OS specifics: Fedora 33 KDE

## Steps to reproduce

1. Download the latest app image either using the Joplin_install_and_update.sh or directly from the 2.3.5 tag page in GitHub
2. Run it and open the `Help` -> `About Joplin` menu
3. Check the version in the opened window.

## Describe what you expected to happen
The versions to be the same.

## Notes
I've discovered this when updating the client after I got the following error while syncing. Should I open a separate ticket for this error?

![Screenshot_20210819_163024](https://user-images.githubusercontent.com/3527534/130077208-4e36cba7-07af-499a-9845-1e34115a4629.png)

**Comment by laurent22** [comment]
That's not possible. Can you check again the About box - is that really 2.3?

**Comment by laurent22** [comment]
forum for support

**Comment by madpipeline** [comment]
Solved the issue by uninstalling Joplin and reinstalling, AKA `find . | grep -i joplin` and delete everything found by it.

Of course I did a full export before, and then forced `Re-upload local data to sync target`.

All is good now.
