### ISSUE TITLE
Never-ending "Fetched items: 1/1"

### ISSUE THREAD

**Issue by sif** [laurent22/joplin#5352]
I am getting "Fetched items: 1/1" even when there is nothing to synchronize. This doesn't seem to be a problem between the same OS. For example, iPad and iPhone synchronize fine. MacBook and another MacBook synchronize fine no matter times how I alternate-click synchronize between the two devices. 

## Environment

Joplin version: 2.3.5, 12.3.1
Platform: macOS, iOS
OS specifics: Big Sur 11.5.2, 14.7.1

## Steps to reproduce

1. Grab your desktop and phone with Joplin installed. 
2. Hit synchronize on desktop. Let it finish. Make sure you don't already have stuff you needed to synchronize.
3. Hit synchronize on mobile. Let it finish. Ditto.
4. Hit synchronize on desktop. Let it finish. You might not see anything.
5. Hit synchronize on mobile. You'll see the fetching line.
6. Hit synchronize on desktop, you should now see the fetching line.
7. If you go back to the mobile and synchronize..

You can repeat this, as long as it's in that order. The thing is, if you hit synchronize twice on desktop, it goes away until you hit synchronize on mobile. I'm not sure why. I can keep the "Fetched items: 1/1" going as long as I alternate between the two. I don't think this is normal behavior because I'm one of those that synchronize between devices a few times "just to be sure" and this is the first time I see this behavior. 

## Describe what you expected to happen

If there is nothing to synchronize, I expect to see the "Completed: [date and time]" and that's it. Otherwise, what's that 1/1? 

## Logfile

N/A, no error logged.

<img width="274" alt="ios" src="https://user-images.githubusercontent.com/327998/130115112-05cb0aa2-1540-48e5-a67c-cd61d475fb8a.png">
<img width="234" alt="macos" src="https://user-images.githubusercontent.com/327998/130115114-f4f4b5c9-6a2e-41cb-987c-958e6338098a.png">

**Comment by sif** [comment]
If this was too confusing, I could make a video and put it on YouTube or something..

**Comment by laurent22** [comment]
Could be the info.json file. What do you sync with?

**Comment by sif** [comment]
I use Dropbox.

**Comment by laurent22** [comment]
What does the log say when you sync?

**Comment by sif** [comment]
I'm not sure where the logs are so I looked in the console. The [removed] was because I wasn't sure if it was sensitive data. Everything else untouched.

14:27:03: Preparing scheduled sync
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:03: Starting scheduled sync
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:03: Synchronizer: Sync: starting: Starting synchronisation to target 7... supportsAccurateTimestamp = false; supportsMultiPut = false [removed]
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:03: Synchronizer: Indexing resources...
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:03: ResourceService::indexNoteResources: Start
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:03: ResourceService::indexNoteResources: Completed
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:04: Synchronizer: Sync target remote info: SyncInfo {version_: 3, masterKeys_: Array(1), e2ee_: {…}, activeMasterKeyId_: {…}}
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:04: Synchronizer: Sync target is already setup - checking it...
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:04: Synchronizer: Sync target local info: SyncInfo {version_: 3, masterKeys_: Array(1), e2ee_: {…}, activeMasterKeyId_: {…}}
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:04: Synchronizer: Sync target info differs between local and remote - merging infos:  {version: 3, e2ee: {…}, activeMasterKeyId: {…}, masterKeys: Array(1)}
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:08: Synchronizer: TaskQueue.stop: syncDownload: waiting for tasks to complete: 0
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:08: Synchronizer: TaskQueue.stop: syncDownload: Done, waited for 0
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:09: Synchronizer: Sync: fetchingTotal: Fetching delta items from sync target
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:09: Synchronizer: Sync: fetchingProcessed: Processing fetched item
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:09: Synchronizer: Sync: finished: Synchronisation finished [1629397623443]
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:09: Synchronizer: Operations completed: 
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:09: Synchronizer: fetchingTotal: 1
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:09: Synchronizer: fetchingProcessed: 1
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:09: Synchronizer: Total folders: [removed]
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:09: Synchronizer: Total notes: [removed]
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:09: Synchronizer: Total resources: [removed]
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:10: DecryptionWorker: starting decryption...
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Logger.js:188 14:27:10: DecryptionWorker: completed decryption.

**Comment by laurent22** [comment]
What if you set the log level to debug? https://joplinapp.org/debugging/

**Comment by sif** [comment]
I see that the log.txt is in the Profile Directory. Because there was no error, the output was the same except it looks like there are sensitive data. I still see:

2021-08-19 15:01:00: Synchronizer: "fetchingTotal: 1"
2021-08-19 15:01:00: Synchronizer: "fetchingProcessed: 1"

**Comment by sif** [comment]
Alright, I think you're right. It might be the info.json file. I decided to watch it live to see any changes. As I alternated the devices, I noticed that the file changed. 

I guess it's harmless then. Then it would be nice if "Fetched items: " popped up for actual notes that are changed. I can see why now. Should I close this issue then?
