### ISSUE TITLE
Sync errors in Debian (Joplin v2.3.3)

### ISSUE THREAD

**Issue by connorjlbrown** [laurent22/joplin#5353]
When trying to sync with my Nextcloud account after recent update to v2.3.3, this error is returned:

`Completed: 19/08/2021 15:53 (41s)
Last error: Error: PUT locks/sync_desktop_82415ee3c5d942b98d74a6b879e07c62.json: "locks/sync_desktop_82415ee3c5d942b98d74a6b879e07c62.json" is locked (Exception OCA\DAV\Connector\Sabre\Exception\FileLocked) (423): <?xml version="1.0" encoding="utf-8"?> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"> <s:exception>OCA\DAV\Connector\Sabre\Exception\FileLocked</s:exception> <s:message>"locks/sync_desktop_82415ee3c5d942b98d74a6b879e07c62.json" is locked</s:message> </d:error>`

It should be noted that I have already upgraded sync targets. If there's any more information I can provide, please let me know. 

## Environment

Joplin version: 2.3.3
Platform: Linux
OS specifics: Debian 10 (Buster)

## Steps to reproduce

1. Sign into (I assume) a Nextcloud provider
2. Synchronize notes with the server
3. Wait

## Describe what you expected to happen

Usually, synchronization is completed successfully. 

## Logfile

[-1629414250164.log](https://github.com/laurent22/joplin/files/7018102/-1629414250164.log)
[-1629414263393.log](https://github.com/laurent22/joplin/files/7018103/-1629414263393.log)

**Comment by dpoulton-github** [comment]
Looks similar to these posts which refer to a problem with Nextcloud itself.

https://discourse.joplinapp.org/t/sync-problem-with-nextcloud/19274
https://discourse.joplinapp.org/t/if-youre-getting-a-filelocked-error/10947
