### ISSUE TITLE
Window title bar is white in macOS dark mode

### ISSUE THREAD

**Issue by sbugzu** [laurent22/joplin#5354]
![image](https://user-images.githubusercontent.com/621770/130166909-b4505e5f-e863-473c-9386-45dca5be9568.png)

## Environment

Joplin version:  Joplin 2.3.5 (prod, darwin)
Platform:  macOS
OS specifics:  Big Sur 11.4 (20F71)

## Describe what you expected to happen
refer the title

**Comment by laurent22** [comment]
So the operating system is in dark mode, and the title bar is white? Because for me all title bar are dark, including for Joplin.

**Comment by sbugzu** [comment]
Yes, this has suddenly happened since a certain version.
PS: Joplin was installed using `brew`.

**Comment by sbugzu** [comment]
Is there any way to debug the issue?

**Comment by sbugzu** [comment]
I‘ve tried uninstall with `brew uninstall joplin`, uninstall with CleanMyMac X, remove the configuration folder `~/.config/joplin-desktop`.
Nothing happened. 😭

**Comment by sbugzu** [comment]
Solved. It's my fault.
It has been more than 100 days since I rebooted my mac. After reboot, everything is working.

Joplin is a very awesome software. 👍
