### ISSUE TITLE
Click the search result does not jump to original note

### ISSUE THREAD

**Issue by seanlook** [laurent22/joplin#5355]
Using quick command `Ctrl + p` to search notes, sometime clicking on one result won't jump to it's full note page. Try one more time, it jumps. Very stange:)

## Environment

Joplin version: 2.3.5
Platform: windows
OS specifics: win10

## Steps to reproduce

1. Press `Ctrl + p` and type phase to search
2. click on one result. Expecting it will jump to original note
3. it does't jump to the note occasionally. When I search again, maybe i's ok.

## Describe what you expected to happen
It will jump to original every time

**Comment by CalebJohn** [comment]
This will be [fixed in the next release](https://github.com/laurent22/joplin/commit/4f5ad86028de9123c2cfd4f7507356dbbb0b3c67).
