### ISSUE TITLE
After upgrading to 2.3.5, An Empty space is inserted before every line

### ISSUE THREAD

**Issue by sathyagnu** [laurent22/joplin#5356]
![image](https://user-images.githubusercontent.com/48686880/130231138-73d1342f-e456-44d5-a20d-3d716c2cb950.png)

## Environment

Joplin version: 2.3.5
Platform: Windows
OS specifics: Windows 10 

## Steps to reproduce

1. When opening the Joplin, I see the empty spaces, that cannot be removed or adjusted.

## Describe what you expected to happen

This was not see in previous upgrades . This causes inconvenience to view the content written to the notes.

**Comment by JackGruber** [comment]
You can disable this by going into Configuration > Appearance and set the width to "0".

**Comment by sathyagnu** [comment]
> Configuration > Appearance and set the width to "0".

This fixed the issue. Thank you!
