### ISSUE TITLE
Goto Anything feature only working with 2nd try

### ISSUE THREAD

**Issue by NinaOrtiz98** [laurent22/joplin#5361]
Hi. I've been using Joplin for quite some time now. One of the features I use frequently is the Goto Anything. But recently this feature hasn't been working like it used to including the most recent version. It no longer works on first try but only on the second. If you open the Goto Anything and search for a note the only thing that happens when you press enter or click the found note is the Goto Anything window will close. If you open the Goto Anything again and search once more it will work the second time. There seems to be a bug that is not allowing this feature to work the first time but only on the second.

I've seen that this bug was previously reported and marked as fixed. But I wanted to let you know that it's still happening. I really hope this issue is fixed soon because it saves a lot of time for people with lots of notes. It's a feature I and I'm sure many others use frequently. I've switched back to an older version for now (Joplin 2.1.8) and will update once this gets resolved.

**Comment by laurent22** [comment]
This is fixed and should be available very soon in the next pre-release (probably over the weekend).

**Comment by CalebJohn** [comment]
Duplicate of #5355

**Comment by NinaOrtiz98** [comment]
This is now working in the latest release... thank you! Just one question.. when switching between notes using Goto Anything, sometimes the editor is automatically in focus and sometimes it isn't. What I mean is that sometimes I can begin typing right away in a note when switching to it but sometimes I need to click in the note to begin typing. Is this a bug?

**Comment by laurent22** [comment]
If it's a to-do it should focus the title and if it's a regular note it should focus the body (that can be changed in Config > Note). If it's doing something different it's indeed a bug so feel free to create a new issue about it.

**Comment by NinaOrtiz98** [comment]
Ok, thanks!
