### ISSUE TITLE
Android: Keyboard disappearing in note editor

### ISSUE THREAD

**Issue by olucasjose** [laurent22/joplin#5362]
## Environment

**Joplin version:** 2.3.4
**Platform:** Android
**OS specifics:** Android 7.0

## Steps to reproduce

1. Open the app.
2. Create a note or choose an existing one and click on it.
3. Enter some text.
4. Click on your phone's "Back button" to hide the keyboard.
5. Wait 10 seconds.
6. Try editing your note again.

**If the same bug happens to you, your keyboard will not appear no matter how much you click on the screen.**

In case my explanation is confusing, I made a short video reproducing the bug: https://youtu.be/Y3rGysEYCL4

## Describe what you expected to happen

I usually like to hide the keyboard to get a better view of the note I'm editing and only show the keyboard again when I have something to add to the note.

## Logfile

I did my own analysis of the log provided by the app, but found no keyboard-related errors...

**Comment by mitej23** [comment]
I am not getting this bug on my android device. It is working correctly

**Comment by damufo** [comment]
Same error, on android, imposible edit content notes.
Very thanks.
![imaxe](https://github.com/laurent22/joplin/assets/4057369/2c566acb-74b4-4e0a-ac13-172b9f23b4a4)
![imaxe](https://github.com/laurent22/joplin/assets/4057369/4ce6db89-f36c-42f1-ae77-16505654c6ee)
![imaxe](https://github.com/laurent22/joplin/assets/4057369/5b948292-4c81-4121-85ee-bdf85400e6cf)
