### ISSUE TITLE
Text is centered in the WYSIWYG editor

### ISSUE THREAD

**Issue by jebr** [laurent22/joplin#5363]
The text is centered. After giving an enter, the text on the next line is displayed correctly. However, after closing and opening Joplin, the second line is also centered. I don't use any plugins in the application

![afbeelding](https://user-images.githubusercontent.com/7726815/130322216-76c8602b-cb8c-4e1c-9d9d-a6fa86ff82ba.png)

## Environment

Joplin version: 2.3.5
Platform: Windows
OS specifics: Windows 10 / 21H1

## Steps to reproduce

1. Create a new note
2. Write first and second line
3. Switch to another note
4. Switch back to created note
5. All text is centered

## Describe what you expected to happen
I would like all text to be left aligned.

I hope you can fix the problem soon, it's very annoying.

**Comment by squaregoldfish** [comment]
Could it be related to this?

https://discourse.joplinapp.org/t/please-read-this-if-you-are-wondering-why-theres-now-a-margin-on-the-note-text/19585

**Comment by jebr** [comment]
This solution fixes the problem. Thank you very much for the quick response.
