### ISSUE TITLE
Importing .jex results in duplicate notes

### ISSUE THREAD

**Issue by technicalguy** [laurent22/joplin#537]
### Operating system

- Linux

### Application

- Desktop

### Steps to reproduce:

1. Make a new notebook "Default"
1. Make a new note
2. Export as .jex
3. Import

### Observed behaviour:

New notebook "Default (1)" with duplicate copy of note

### Expected behaviour:

"1 Note(s) loaded in 1 Notebook(s). 1 Note(s) matched with existing notes. 0 New Note(s) added."

Joplin 1.0.93 (prod, linux)

**Comment by laurent22** [comment]
It works as expected (it works like Evernote for instance) because import is not sync, it's creating new notes only.
