### ISSUE TITLE
[Desktop] Sync wizard is rendred incorrectly when running dev Joplin

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#5373]
* Start Joplin Dev `cd packages/app-desktop && npm start`
* Open Settings - Synchronization
* Open Sync Wizard and scroll a little down:
![image](https://user-images.githubusercontent.com/995612/130504663-f7ad2fb1-7aef-4642-93d0-c5c452b1a7cd.png)

* Close Settings:
![image](https://user-images.githubusercontent.com/995612/130504716-51dabec4-f90f-4d6c-8b24-9d2924049ec7.png)

**Comment by Rishabhraghwendra18** [comment]
Hi @roman-r-m , I am not able to see bug . I am using v2.5.7(dev,linux) . May you guide me how I can reproduce the issue ?

https://user-images.githubusercontent.com/43534227/142380170-039a3146-7367-4fbf-a0ad-79e523779012.mp4

**Comment by roman-r-m** [comment]
I am not able to see the video - GitHub says the file is corrupt.
But I've just tried again and the issue is still there.
* Start Joplin dev
* Move the console to the bottom of the screen
* Open settings - Sync Wizard

**Comment by Rishabhraghwendra18** [comment]
That's weird because this video is playing on friend's account too . GitHub is not showing her the file is corrupt .

Anyways , I still don't see the issue . I hope this 8s video will play on GitHub , otherwise I will upload the video on forum:

https://user-images.githubusercontent.com/43534227/142404777-4be5293c-abd5-4ac1-bb0c-8527e1a4b48b.mp4

**Comment by Daeraxa** [comment]
Shows the same for me, both videos are "corrupt"

**Comment by Rishabhraghwendra18** [comment]
Ok. No worries I have posted on the forum . [Link](https://discourse.joplinapp.org/t/desktop-sync-wizard-is-rendred-incorrectly-when-running-dev-joplin/21819)

**Comment by tomasz1986** [comment]
> Shows the same for me, both videos are "corrupt"

Interesting. Both videos work here (Ungoogled Chromium / Windows 10).

**Comment by Daeraxa** [comment]
Maybe its a firefox issue then as I can't see it on the forum either.

**Comment by roman-r-m** [comment]
Yes, seems so. I can't see the it in Firefox but in Chrome it's fine.

**Comment by roman-r-m** [comment]
As for repeating the issue, try increasing the size of the dev console to around half of the screen height.

**Comment by Daeraxa** [comment]
@Rishabhraghwendra18 you also didn't actually try to close the settings window. If you press close you can see it. Check my other post above with more detailed steps (unless they aren't actually the right steps and I found a different issue...)

**Comment by Rishabhraghwendra18** [comment]
Thanks @Daeraxa I am on it
