### ISSUE TITLE
Blank window after screen unlock

### ISSUE THREAD

**Issue by ajgringo619** [laurent22/joplin#5374]
Whenever I unlock my screen, the Joplin window is blank. This happens whether the screen is locked manually or automatically when power management activates.

## Environment

Joplin version: 2.3.5 (AppImage)
Platform: Linux
OS specifics: Linux Mint 20.2, kernel 5.4.0-81, Nvidia v470-52

## Steps to reproduce

1. Lock screen with Joplin open
2. Unlock screen
3. Get blank window

**Comment by ajgringo619** [comment]
This is also happening if I close Joplin with the system tray icon activated, then return from a locked session.

**Comment by BackSeat** [comment]
As mentioned in #5062, what fixed this for me was changing to the `slock` screensaver.
