### ISSUE TITLE
Strange markdown/html formatting glitch

### ISSUE THREAD

**Issue by ajgringo619** [laurent22/joplin#5375]
Not really sure how to describe what's happening, but here goes...

When formatting certain code blocks of text, the last character of some fields is shown in a different color that the rest of the text. For example, here's a block I'm using to help describe a VM I've built (output is from the **distro** python module):

```
'name': 'FreeBSD',
'version': '13.0-RELEASE',
'version_id': '13.0',
'id': 'freebsd',
'ansi_color': '0;31',
'pretty_name': 'FreeBSD 13.0-RELEASE',
'cpe_name': 'cpe:/o:freebsd:freebsd:13.0',
'home_url': 'https://FreeBSD.org/',
'bug_report_url': 'https://bugs.FreeBSD.org/'
```

Now, when shown in the markdown editor, it looks like this:
![freebsd-joplin-glitch](https://user-images.githubusercontent.com/53413561/130542483-98bc090e-f557-414f-b831-ffb2f10e29c8.jpg)

Now, if I edit the original data to this:
```
'name': 'FreeBSD',
'version': '13.0-RELEASE',
'version_id': '13.0',
'id': 'freebsd',
'ansi_color': '0;31',
'pretty_name': 'FreeBSD 13.0-RELEASE',
'cpe_name': 'cpe:/o:freebsd:freebsd:13.0',
'home_url': 'https://FreeBSD.org/', 'bug_report_url': 'https://bugs.FreeBSD.org/'
```
the markdown page looks normal:
![freebsd-joplin-noglitch](https://user-images.githubusercontent.com/53413561/130542704-3bc3df31-4120-424c-90d5-48aa9cececa3.jpg)

Something is happening whenever I have (2) links on the same line; if I separate them, I get the error.
## Environment

Joplin version: 2.3.5 (AppImage)
Platform: Linux
OS specifics: Linux Mint 20.2 XFCE, kernel 5.4.0-81, Nvidia 470-52

## Steps to reproduce

1. Create code block with (2) hyperlinks
2. Separate them by carriage return
3. Last character of certain text is a different color than the rest

This is the source from a web page I made with Joplin. You can see where the <span> tags are being put in the wrong place:
```
<div class="joplin-editable"><pre class="joplin-source" data-joplin-language="" data-joplin-source-open="```&#10;" data-joplin-source-close="&#10;```">{'name': 'FreeBSD',
--
  | 'version': '13.0-RELEASE',
  | 'version_id': '13.0',
  | 'id': 'freebsd',
  | 'ansi_color': '0;31',
  | 'pretty_name': 'FreeBSD 13.0-RELEASE',
  | 'cpe_name': 'cpe:/o:freebsd:freebsd:13.0',
  | 'home_url': 'https://FreeBSD.org/',
  | 'bug_report_url': 'https://bugs.FreeBSD.org/'
  |</pre><pre class="hljs"><code>{<span class="hljs-symbol">&#x27;nam</span>e&#x27;: <span class="hljs-symbol">&#x27;FreeBS</span>D&#x27;,
  | <span class="hljs-symbol">&#x27;versio</span>n&#x27;: <span class="hljs-symbol">&#x27;13</span><span class="hljs-number">.0</span>-<span class="hljs-type">RELEASE</span>&#x27;,
  | <span class="hljs-symbol">&#x27;version_i</span>d&#x27;: <span class="hljs-symbol">&#x27;13</span><span class="hljs-number">.0</span>&#x27;,
  | <span class="hljs-symbol">&#x27;i</span>d&#x27;: <span class="hljs-symbol">&#x27;freebs</span>d&#x27;,
  | <span class="hljs-symbol">&#x27;ansi_colo</span>r&#x27;: <span class="hljs-symbol">&#x27;0</span>;<span class="hljs-number">31</span>&#x27;,
  | <span class="hljs-symbol">&#x27;pretty_nam</span>e&#x27;: <span class="hljs-symbol">&#x27;FreeBSD</span> <span class="hljs-number">13.0</span>-<span class="hljs-type">RELEASE</span>&#x27;,
  | <span class="hljs-symbol">&#x27;cpe_nam</span>e&#x27;: <span class="hljs-symbol">&#x27;cpe</span>:/o:freebsd:freebsd:<span class="hljs-number">13.0</span>&#x27;,
  | <span class="hljs-symbol">&#x27;home_ur</span>l&#x27;: <span class="hljs-symbol">&#x27;https</span>:<span class="hljs-comment">//FreeBSD.org/&#x27;,</span>
  | <span class="hljs-symbol">&#x27;bug_report_ur</span>l&#x27;: <span class="hljs-symbol">&#x27;https</span>:<span class="hljs-comment">//bugs.FreeBSD.org/&#x27;</span>
  |</code></pre></div>

```

**Comment by CalebJohn** [comment]
Just to clear up this issue for the next reader. This is a bug in the markdown **viewer** not the editor. It also appears to be present in the Rich Text editor. I can't reproduce with the light theme but I can with dark. I'm gonna guess this is a bug with highlight.js.

**Comment by ajgringo619** [comment]
I tried with the standard light theme - same issues.

**Comment by CalebJohn** [comment]
Not stale
