### ISSUE TITLE
Joplin won't open under macOS Big Sur

### ISSUE THREAD

**Issue by chrisihoeg** [laurent22/joplin#5383]
## Environment

Joplin version: 
Platform: macOS
OS specifics: Big Sur

## Steps to reproduce

1. Download Joplin
2. Open dmg file
3. Move Joplin to Apps directory
4. Open Joplin
5. Receive Error

Fatal error:

EACCES: permission denied, mkdir '/Users/chrisi/.config/joplin-desktop'
Error: EACCES: permission denied, mkdir '/Users/chrisi/.config/joplin-desktop'

I am not sure if this is really an issue with the app. I guess it is more some permission thing from my side but I can't get it to work. Maybe someone has any tips? I think I found a similar issue [here](https://github.com/laurent22/joplin/issues/3294) but that doesn't really help me.

Thanks!

## Describe what you expected to happen
Open App

**Comment by chrisihoeg** [comment]
Solved it :-)

**Comment by laurent22** [comment]
Could you share how you've done it, in case it helps other users?

**Comment by chrisihoeg** [comment]
Yes, you need to change the permissions of the /Users directory. It seems Joplin couldn't start because of the permissions set for the /Users directory. So if you get any "permission denied" errors, I suggest to have a look at the directories permissions for the user.
It helped me reading this post [here](https://github.com/laurent22/joplin/issues/3294).

**Comment by oseynnes** [comment]
Hi, I have the same issue but did not understand how to change permissions. When I look at permissions for Users/myuser, myuser already has read & write... What do I need to change?
