### ISSUE TITLE
PDF Export gibberish

### ISSUE THREAD

**Issue by NosillaCast** [laurent22/joplin#5387]
Exported to PDF and it created it with bullets and horizontal rules and such, but the characters are gibberish. 
Example: ć Ẃ ḁ Ḩ Ȁ .. ͯ  ḿ ∇ xi ḁ ḁ ʹ viiiḁ ḭ Ȁ ḁ ḁ Ǹ ǘ Ȫ xi viiiḁ ḭ ͪ Ṝ ḭ ǘ  ʹ ǘ Ṑ  ȗ ḿ

## Environment

Joplin version: 2.3.5
Platform: macOS desktop
OS specifics: macOS Big Sur 11.5.2

## Steps to reproduce

1. Right-click on any note
2. Choose Export
3. Choose PDF

## Describe what you expected to happen

Expected to be able to read the PDF.

## Logfile

[System Preferences for SBAMUG.pdf](https://github.com/laurent22/joplin/files/7050737/System.Preferences.for.SBAMUG.pdf)
[PDF export debug log.txt](https://github.com/laurent22/joplin/files/7050738/PDF.export.debug.log.txt)

**Comment by NosillaCast** [comment]
I don't use any custom CSS or fonts in Joplin @laurent22

**Comment by kirillz** [comment]
Hello. Confirmed. PDFexport not working, not creating .pdf file on win 10 x64
