### ISSUE TITLE
Hope to improve accessibility

### ISSUE THREAD

**Issue by cary-rowen** [laurent22/joplin#5388]
## Environment

Joplin version: 2.3.5
Platform: Windows
OS specifics: Windows 10 21H1 (x64) build 19043.1165

## Steps to reproduce

1. Use NVDA with Joplin.
2. The button to create new notebook is missing a label.
3. The search button is missing a label.
4. The default editor cannot read anything.
5. The focus may be trapped somewhere.
6. This is a copy of #4952 in a way, and I would love to see progress.

## Describe what you expected to happen

1. Able to report the correct label.
2. The editor can be used with NVDA (eg: Monaco editor)
3. Improve more focus errors, thereby enhancing navigation efficiency.

**Comment by cary-rowen** [comment]
Hope the communitys can pay attention to this issue

**Comment by laurent22** [comment]
Accessibility issues should go there, if they are not already included: https://github.com/laurent22/joplin/issues/4952
