### ISSUE TITLE
Joplin Starts With White Screen

### ISSUE THREAD

**Issue by parkel42** [laurent22/joplin#5393]
## Environment

Joplin version: 2.4.2 (prod, win32)
Platform: Windows 
OS specifics: Windows 10 x64 build 20H2

## Steps to reproduce

1. Start Joplin.
2. Joplin will start with a white screen. 
3. Wait for notifications area icon to appear, close the Joplin window.
4. Reopen the Joplin window through the notifications area icon and the GUI will display properly.

## Describe what you expected to happen

Joplin should display the GUI once it is opened without needing to close the window and reopening it.

## Logfile

[joplin-console.log](https://github.com/laurent22/joplin/files/7070027/joplin-console.log)
[joplin-log.log](https://github.com/laurent22/joplin/files/7070028/joplin-log.log)

**Comment by zerog981** [comment]
Seems to be the exact same issue I am experiencing. See #5305.

**Comment by parkel42** [comment]
Issue resolved as of version 2.5.8.
