### ISSUE TITLE
Code mirror css overwrite the original theme style

### ISSUE THREAD

**Issue by Edwardlin-zlt** [laurent22/joplin#5394]
## Environment

Joplin version: Joplin 2.4.2 (prod, darwin)
Platform: Mac 
OS specifics: Catalina 10.15.7

## Description

After upgrade to recent version, I found the markdown editor color have been wiped over. All text have been render to `#dddddd` which is not desired.

It seems like the CodeMirror styles have overwrite the theme styles.

<img width="1554" alt="image" src="https://user-images.githubusercontent.com/35733429/131204484-2d62988c-c1c2-4c59-9e65-156f3b804389.png">

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/35733429/131204462-d0e61dd2-124c-4a8b-8b76-8a40073b3f06.png">

**Comment by tessus** [comment]
https://discourse.joplinapp.org/t/talking-about-markdowns-codemirror-theme-update/19443?u=tessus
