### ISSUE TITLE
Notifications/Set Alarm button not working

### ISSUE THREAD

**Issue by blade1989** [laurent22/joplin#5395]
## Environment

Joplin version: 2.3.5 (AppImage) via [Joplin_install_and_update.sh](https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh)
Platform: Ubuntu 20.04.3 (Linux)
OS specifics: 

Note, I am using Nextcloud as my synchronization target. I don't know if that is of importance.

## Steps to reproduce

1. Install Joplin via Joplin_install_and_update.sh
2. create a note, add some text.
3. Try to click on the Alarm button, but it is not clickable.

## Describe what you expected to happen
I wanted to test out the notification, as I am a new Joplin user, but the Alarm icon is not clickable. 
I installed the packages I could install mention in the https://joplinapp.org/help/#notifications help page on my Linux system.
Restarted Joplin, even a system restart, but the `Set Alarm` button is still not clickable.

I enabled the dev tool - and saw nothing about the notification not working in the `Console` tab.

In the inspector I saw that the icon was disabled, for whatever reason.

```html
<a class="sc-fzqNJr dHufNm button disabled" disabled="" title="Set alarm" href="#">
    <span class="sc-fzoLag dtSABm icon-alarm"></span>
</a>
```

And the only entry I see about notification and alarms in the `log.txt`, is the following:

```
...
2021-08-28 19:22:52: "Updating all notifications..."
2021-08-28 19:22:52: "Garbage collecting alarms..."
...
```

**Comment by laurent22** [comment]
Alarms only work with to-dos - https://joplinapp.org/help/#notifications
