### ISSUE TITLE
Docker server image is huge

### ISSUE THREAD

**Issue by flo-at** [laurent22/joplin#5397]
This is not strictly a bug but also not a feature request. The docker server image has more than 780MB which is **huge**. This is most likely because all development dependencies are still included in the final image, although they are not required at run time.

## Environment

Joplin version: all versions until now (2.4.2)
Platform: Linux / docker

## Steps to reproduce

See [docker hub](https://hub.docker.com/r/joplin/server/tags).

## Describe what you expected to happen

A [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) can be used to reduce the size.

**Comment by Derkades** [comment]
Now, the latest version is 3.17GB uncompressed! That's quite insane for a simple sync server.
