### ISSUE TITLE
Inconsistent stacking of italics/bold  

### ISSUE THREAD

**Issue by Wdavery** [laurent22/joplin#5402]
## Environment

Joplin version: 2.3.5
Platform: Linux
OS specifics: Installed via Flatpak on OpenSUSE Snapshot 20210829

## Steps to reproduce

Italics + Bold
1. Highlight text
2. Press control-I (or the GUI button to italicize) - Text will be _italicized_
3. Press control-B (or the GUI button to bold) - Text will be **_bold and italicized_**

Bold + Italics
1. Highlight text 
2. Press control-B (or the GUI button to bold) - Text will be **bold**
3. Press control-I (or the GUI button to italicize) - Text will lose bold and gain _italics_
## Expected behavior
Both situations should act as Italics + Bold did. 
Both formatting options should be stacked, not removed in favour of the other.

**Comment by Daeraxa** [comment]
It looks like when you press the button to go from \*Italics\* and add \*\*Bold\*\* it simply adds two more \*s around the highlighted word.  
When you go from \*\*Bold\*\* and add \*Italics\* (with the whole word including markdown characters highlights) it 'undoes' the italics, essentially removing one set of \*s. If you highlight just the word in the middle without the markdown characters, it bolds it and makes it italics + bold.  
Is there a reason why it is using single \*s as italics as the default from button press/shortcut vs \_s? (which, for example, is what Github is doing).

**Comment by Wdavery** [comment]
Still valid

**Comment by Wdavery** [comment]
Unstale.

**Comment by Wdavery** [comment]
Unstale
