### ISSUE TITLE
Taking photos crashes the app

### ISSUE THREAD

**Issue by Xindi7** [laurent22/joplin#5404]
## Environment

Joplin version: Android 2.3.4
Platform: Android 
OS specifics: 7.1.1

## Steps to reproduce

1. Open a note
2. Take a photo by clicking attach and then choosing take photo.
3. When it opens, click the camera button.
4. A tick will appear, but nothing will happen. 
5. Click the tick one or twice 
6. App crashes 

## Describe what you expected to happen
I reproduced these steps in my ios device and after clicking the camera button a tick appeared but the photo was saved immediately without even me clicking tick button. I guess this is what should have happened as well.

## Logfile
I am not sure which button is this. Is it the log button or the export debug report button?

**Comment by laurent22** [comment]
Please provide a low level bug report https://joplinapp.org/debugging/

**Comment by Xindi7** [comment]
Hi. I am unable / cannot to provide a low level bug report. But I have successfully repeated the same bug in another android device. Perhaps if you could tell me what you are exactly looking for, I could extract that from the report.

**Comment by laurent22** [comment]
Anything crash related, so something that contains "error" maybe, or 
"fatal", and the associated stack trace.

**Comment by helper-uttam** [comment]
@Xindi7  they might be asking you to go through this link https://developer.android.com/studio/debug/bug-report and submit a report of the bug
