### ISSUE TITLE
When trying to synchronise with Nextcloud on Linux, only getting the option to use Dropbox 

### ISSUE THREAD

**Issue by Rawgravity** [laurent22/joplin#5406]
## Environment

Joplin version: 2.1.9
Platform: Linux
OS specifics: Linux Mint 20.2 

## Steps to reproduce

1. Launch Joplin on Linux
2. Click 'Synchronise' on the bottom left
3. Takes you directly to Dropbox instructions

## Describe what you expected to happen

I'd like to use Nextcloud to sync my Joplin notes. However, I'm sent to a page that gives me Dropbox instructions and I'm not able to find any way to change this in the app. 

## Logfile
20:35:45: CommandService::execute: synchronize false
/tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11494 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(DropboxLoginScreenComponent)
printWarning @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11494
lowPriorityWarning @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11513
ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11680
flushRenderPhaseStrictModeWarningsInDEV @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23134
commitRootImpl @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22428
unstable_runWithPriority @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:643
runWithPriority$2 @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11305
commitRoot @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22414
runRootCallback @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21554
(anonymous) @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11353
unstable_runWithPriority @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:643
runWithPriority$2 @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11305
flushSyncCallbackQueueImpl @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11349
flushSyncCallbackQueue @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11338
scheduleUpdateOnFiber @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21431
enqueueSetState @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13100
Component.setState @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react/cjs/react.development.js:471
onStateChange @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-redux/lib/components/connectAdvanced.js:222
notify @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-redux/lib/utils/Subscription.js:30
notifyNestedSubs @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-redux/lib/utils/Subscription.js:69
onStateChange @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-redux/lib/components/connectAdvanced.js:219
dispatch @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/@joplin/lib/node_modules/redux/lib/createStore.js:186
(anonymous) @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/@joplin/lib/BaseApplication.js:453
(anonymous) @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/@joplin/lib/BaseApplication.js:8
__awaiter @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/@joplin/lib/BaseApplication.js:4
generalMiddleware @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/@joplin/lib/BaseApplication.js:451
(anonymous) @ /tmp/.mount_JoplincYS86A/resources/app.asar/app.js:330
(anonymous) @ /tmp/.mount_JoplincYS86A/resources/app.asar/app.js:8
__awaiter @ /tmp/.mount_JoplincYS86A/resources/app.asar/app.js:4
generalMiddleware @ /tmp/.mount_JoplincYS86A/resources/app.asar/app.js:311
(anonymous) @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/@joplin/lib/BaseApplication.js:391
(anonymous) @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/@joplin/lib/commands/synchronize.js:30
fulfilled @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/@joplin/lib/commands/synchronize.js:5
Promise.then (async)
step @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/@joplin/lib/commands/synchronize.js:7
(anonymous) @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/@joplin/lib/commands/synchronize.js:8
__awaiter @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/@joplin/lib/commands/synchronize.js:4
execute @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/@joplin/lib/commands/synchronize.js:25
(anonymous) @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/@joplin/lib/services/CommandService.js:145
(anonymous) @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/@joplin/lib/services/CommandService.js:8
__awaiter @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/@joplin/lib/services/CommandService.js:4
execute @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/@joplin/lib/services/CommandService.js:136
onClick @ /tmp/.mount_JoplincYS86A/resources/app.asar/gui/Sidebar/Sidebar.js:458
onClick @ /tmp/.mount_JoplincYS86A/resources/app.asar/gui/Button/Button.js:189
callCallback @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:347
invokeGuardedCallbackDev @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:397
invokeGuardedCallback @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:454
invokeGuardedCallbackAndCatchFirstError @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:468
executeDispatch @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:600
executeDispatchesInOrder @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:622
executeDispatchesAndRelease @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:725
executeDispatchesAndReleaseTopLevel @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:733
forEachAccumulated @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:707
runEventsInBatch @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:750
runExtractedPluginEventsInBatch @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:881
handleTopLevel @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:5901
batchedEventUpdates @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:2344
dispatchEventForPluginEventSystem @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:5996
dispatchEvent @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:6025
unstable_runWithPriority @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:643
runWithPriority$2 @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11305
discreteUpdates$1 @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21672
discreteUpdates @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:2359
dispatchDiscreteEvent @ /tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:5979
Show 3 more frames
/tmp/.mount_JoplincYS86A/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11494 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(DropboxLoginScreenComponent)

**Comment by laurent22** [comment]
Go to Config > Synchronisation and select "Nextcloud".
