### ISSUE TITLE
Creation date and Modification date of files are not kept

### ISSUE THREAD

**Issue by mrkdineg** [laurent22/joplin#5407]
## Environment

Joplin version: 2.3.5
Platform: macOS and Windows
OS specifics: macOS 11.5.2 and Windows 8/10

## Steps to reproduce

1. Based on the thread: https://discourse.joplinapp.org/t/show-the-timestamps-of-the-image-file-and-keep-the-timestamps-created-and-modified/19956
2. Open Joplin on macOS and create a note. Add a picture file or other file to a note.
3. The Creation Date and Modification Date are not kept of the files.

Note: On Windows a user said this and only Creation Date were not kept. https://discourse.joplinapp.org/t/show-the-timestamps-of-the-image-file-and-keep-the-timestamps-created-and-modified/19956/10

## Describe what you expected to happen
The Creation Date and Modification Date are kept when adding files to a note in Joplin (macOS and Windows version) and when users export the files from the notes.

**Comment by laurent22** [comment]
Once it's imported into Joplin its an internal resource so the file timestamp has no relevance. Exif data may be preserved if that's what you need.

**Comment by mrkdineg** [comment]
> 
> 
> Once it's imported into Joplin its an internal resource so the file timestamp has no relevance. Exif data may be preserved if that's what you need.

I add not only image files, but also other files that do not have exif data, but use the timestamps from the file system.

Would it be possible to change this behavior or add an option where the timestamps (creation date and modification date) of files can be kept?

Why are there differences on Joplin Windows and macOS? According to the user in the forum, on Joplin Windows version for files, the Modification Date is kept, but on macOS it is not. Creation date are generally not kept on Joplin.

**Comment by laurent22** [comment]
Image or any file, it's the same, the timestamps are not relevant. Anyway you should say what you're trying to achieve instead of jumping to a solution that's never going to happen.

**Comment by mrkdineg** [comment]
> Anyway you should say what you're trying to achieve instead of jumping to a solution that's never going to happen.

Most of the time I add my image files (screenshots files, they don't have exif data) to notes and after months or years later when I extract these images I want to know when the image file was created and modified. It would be very handy if Joplin can keep the file timestamps. This would save me a lot of work.
