### ISSUE TITLE
I cannt use joplin web clipper

### ISSUE THREAD

**Issue by qinglin20056** [laurent22/joplin#5411]
I have upgrade my joplin from1.7 to 2.35 today.BUT now ,I can,t use zhe joplin web-clipper.IT reports zhe follow erros.what shuod I do ?please help me,thanks very much !

There was some error creating the note: {"error":"Missing \"token\" parameter: \n\nError: Missing \"token\" parameter\n at Api.checkToken_ (C:\\Users\\admin\\AppData\\Local\\Temp\\1wqN7VTtSt3e06nQuGOxSA3CVAV\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:181:19)\n at Api.<anonymous> (C:\\Users\\admin\\AppData\\Local\\Temp\\1wqN7VTtSt3e06nQuGOxSA3CVAV\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:146:18)\n at Generator.next (<anonymous>)\n at C:\\Users\\admin\\AppData\\Local\\Temp\\1wqN7VTtSt3e06nQuGOxSA3CVAV\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:8:71\n at new Promise (<anonymous>)\n at __awaiter (C:\\Users\\admin\\AppData\\Local\\Temp\\1wqN7VTtSt3e06nQuGOxSA3CVAV\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:4:12)\n at Api.route (C:\\Users\\admin\\AppData\\Local\\Temp\\1wqN7VTtSt3e06nQuGOxSA3CVAV\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:98:16)\n at ClipperServer.<anonymous> (C:\\Users\\admin\\AppData\\Local\\Temp\\1wqN7VTtSt3e06nQuGOxSA3CVAV\\resources\\app.asar\\node_modules\\@joplin\\lib\\ClipperServer.js:168:58)\n at Generator.next (<anonymous>)\n at C:\\Users\\admin\\AppData\\Local\\Temp\\1wqN7VT
![image](https://user-images.githubusercontent.com/83266731/131975419-fea7a1f5-2ebc-44f2-b0c7-01894526ea49.png)
![image](https://user-images.githubusercontent.com/83266731/131975517-7816b857-9f45-4265-a976-e45282e2110f.png)
![image](https://user-images.githubusercontent.com/83266731/131975558-d8b1f14b-01e7-4d26-8001-8781edd171c2.png)

**Comment by laurent22** [comment]
Try uninstalling and reinstalling the clipper?

**Comment by qinglin2005** [comment]
I HAVE ALLREADY SOLVED THIS QUESTION，THANK YOU！

**Comment by laurent22** [comment]
Would you mind sharing how you've done it? In case we can improve this on our side, or to help future users fix it themselves.

**Comment by laurent22** [comment]
So selfish to come for support on a forum, saying the problem is solved, and not saying what the solution was.
