### ISSUE TITLE
Rich text editor removes formatting in presence of trailing or leading spaces. #5238

### ISSUE THREAD

**Issue by saarantras** [laurent22/joplin#5413]
## Environment

Joplin version: 2.3.5
Platform: Linux

## Steps to reproduce

1. Create a new note
2. Switch to the rich-text editor
3. Press ctrl-B or click the "bold" button
4. Type the following, _where the underscore is a space_.
`foobar_`
5. Switch away from the note
6. Switch back
7. Notice that the text has become the following, and is not bolded
`**foobar **`

## Describe what you expected to happen
I expected the text to remain bolded.

## Logfile

Not relevant

**Comment by saarantras** [comment]
Re-created issue #5238, as I was directed to do by the bot.

**Comment by sds100** [comment]
Hi, I also have this issue and it is very disruptive. 😄 It would be great to get it fixed. I might investigate if I have time.

**Comment by saarantras** [comment]
This is still an issue.

**Comment by saarantras** [comment]
This is still an issue as of Joplin 2.6.10

**Comment by saarantras** [comment]
This is still an issue as of Joplin 2.7.14

**Comment by planefun2** [comment]
Not sure if this is precisely the same issue or not, but WYSIWYG tables become mangled and lose their formatting in the same way. Add colors to cells, change width, etc. in WYSIWYG, have spaces trailing, go to another page, and come back - and all your formatting is undone.

**Comment by saarantras** [comment]
This is still an issue as of Joplin 2.7.15

**Comment by saarantras** [comment]
This is still an issue as of v2.7.15.

**Comment by saarantras** [comment]
Still an issue.

**Comment by saarantras** [comment]
This is still an issue as of 2.8.8

**Comment by saarantras** [comment]
This is still an issue as of 2.8.8

**Comment by saarantras** [comment]
This is still an issue

**Comment by saarantras** [comment]
This is still an issue

**Comment by saarantras** [comment]
This remains an issue
