### ISSUE TITLE
Desktop integration missing in Joplin-1.0.93-x86_64.AppImage

### ISSUE THREAD

**Issue by cast-away** [laurent22/joplin#542]
### Operating system
- Linux

### Application
- Desktop

When run for the first time the desktop integration message was not shown. Running the desktop app from the terminal gave the following error:

`desktop-file-install is missing. Skipping /tmp/.mount_Joplin8oFmma/AppRun`

No warnings or errors in the log after enabling debug mode that I could see.

**Comment by laurent22** [comment]
What was the error exactly? Was something not working?

**Comment by cast-away** [comment]
The error is:
`desktop-file-install is missing. Skipping /tmp/.mount_Joplin8oFmma/AppRun`
The application is not integrated within the system, and needs to be launched either from the terminal or through a custom shortcut. Not the end of the world but not very convenient either.

**Comment by foxmask** [comment]
on debian install desktop-file-utils
```
aptitude install desktop-file-utils
```

**Comment by cast-away** [comment]
desktop-file-utils did the trick, thanks
