### ISSUE TITLE
Problem with new version of Simple Backup Plugin

### ISSUE THREAD

**Issue by flphotog** [laurent22/joplin#5420]
Joplin 2.3.5 (prod, linux)

Client ID: 675f26f8e7e542b3900bb8885dbf414a
Sync Version: 3
Profile Version: 39
Keychain Supported: No

Revision: 819af3c
I recently updated simple backup and when I backup to a single .jex file the size has dropped from 36mb to 8mb. I'm assuming this to be an issue, not going to try to recover and lose everything. When I do a backup to individual .jex files everything seems to be fine.
Any ideas on this. See log below.

/tmp/.mount_JoplinPo…n/lib/Logger.js:188 12:04:51: CommandService::execute: exportFolders 
(142) ["109652e22b7245498bcb043f27452a34", "792ad266486640aabddfac6c1b5a5fc8", "110c214d1f534c7aaf3ab1fa9b451509", "edf6a43fbc1e41769a534ae3054306c9", "10544b7d51f449dc8bfc9f9d51c260bf", "4004ecafefed4f9f872596b4ca58a18a", "e90c18741495432c89ced402108503d8", "8e7ba990b42b4d3ab29a613fcfd92d13", "d8205876388c473da942f347e85381f9", "e843b0ef135b43fa9f5cbe588249ffea", "ba47327dcc1d49a0a35ba1c5549114cb", "8cf3ea50742b4caf9172b501f96cee21", "b1f1dcfa02c44c688ce2b57687e1fe44", "d822e4e962134109870646179f793f01", "301ca44e6d954ebc862f5b9d9c951efb", "d48f0007237045f0a74db68196e11cc9", "cacd1051646e45999c57dbd9a3e024a8", "33acdbaf7f534a0185a7e6fe044b17e5", "071c1ea89c154e96bcc1573491cfd2f6", "5f9db68c3e364da380849fc7178eb34a", "d4323d631231498a9fa45acebe169b8f", "3317616964654e3fa2ab845a4188b04a", "cf3a471a340e40fcb1238efc0fdb8419", "6c49a7e757204ebf97dc352c81a0b2fb", "f254de83066544baa7575c503f9a03f7", "1ee90620fa6645fa803cc2ca9b2e1c68", "87d8959308454b6ca67e65724b5c158a", "8c7c67ac2fb84b5a95cb797a59429895", "15ca8d1e2e784108ac4452535923026f", "bea12e316d01485892edd0899b0e6467", "c5a904919a6b43a2a859d11c54061c7b", "8284c0807fe74d03808c27ce923ca2f1", "9f32620c8c3442b095c4e6c0c69c826a", "4f25f3cf35c944e5aa5be291075ba527", "576685a7bc3d4f478c8f46e828c7b893", "5eecc1f56f4c469e96c2f07b65233c26", "a735dcd782af41d3a4a0f5226d24c385", "fe2727f30a3a4cbeb99fd7ca07babcaf", "c393741ce71542d5a7dad75a4da33ac9", "b19f603ebdc44b92922e28d632972080", "b4a866906d1e478481d4f1c9cff2402d", "dde8d1145fe34e2ea80e2d13978d8a40", "79c6d051c1384833b261c50265565909", "fdb6b0ca1ee348ddb8845ae57c4f9cf8", "3dd1919240584dc9aaf385f643791bf5", "0532b574eff44a94a4ff2be7d7d55c49", "8cee0b973b8d49188f23cacf3ca04994", "c919e261980e4bedb02231077c7f664e", "57f5f52087434a408730016e585b0597", "d43b44b13ce34645b8232f39d8b4789a", "109652e22b7245498bcb043f27452a34", "792ad266486640aabddfac6c1b5a5fc8", "110c214d1f534c7aaf3ab1fa9b451509", "edf6a43fbc1e41769a534ae3054306c9", "10544b7d51f449dc8bfc9f9d51c260bf", "4004ecafefed4f9f872596b4ca58a18a", "e90c18741495432c89ced402108503d8", "8e7ba990b42b4d3ab29a613fcfd92d13", "d8205876388c473da942f347e85381f9", "e843b0ef135b43fa9f5cbe588249ffea", "ba47327dcc1d49a0a35ba1c5549114cb", "8cf3ea50742b4caf9172b501f96cee21", "b1f1dcfa02c44c688ce2b57687e1fe44", "d822e4e962134109870646179f793f01", "301ca44e6d954ebc862f5b9d9c951efb", "d48f0007237045f0a74db68196e11cc9", "cacd1051646e45999c57dbd9a3e024a8", "33acdbaf7f534a0185a7e6fe044b17e5", "071c1ea89c154e96bcc1573491cfd2f6", "5f9db68c3e364da380849fc7178eb34a", "d4323d631231498a9fa45acebe169b8f", "3317616964654e3fa2ab845a4188b04a", "cf3a471a340e40fcb1238efc0fdb8419", "6c49a7e757204ebf97dc352c81a0b2fb", "f254de83066544baa7575c503f9a03f7", "1ee90620fa6645fa803cc2ca9b2e1c68", "87d8959308454b6ca67e65724b5c158a", "8c7c67ac2fb84b5a95cb797a59429895", "15ca8d1e2e784108ac4452535923026f", "bea12e316d01485892edd0899b0e6467", "c5a904919a6b43a2a859d11c54061c7b", "8284c0807fe74d03808c27ce923ca2f1", "9f32620c8c3442b095c4e6c0c69c826a", "4f25f3cf35c944e5aa5be291075ba527", "576685a7bc3d4f478c8f46e828c7b893", "5eecc1f56f4c469e96c2f07b65233c26", "a735dcd782af41d3a4a0f5226d24c385", "fe2727f30a3a4cbeb99fd7ca07babcaf", "c393741ce71542d5a7dad75a4da33ac9", "b19f603ebdc44b92922e28d632972080", "b4a866906d1e478481d4f1c9cff2402d", "dde8d1145fe34e2ea80e2d13978d8a40", "79c6d051c1384833b261c50265565909", "fdb6b0ca1ee348ddb8845ae57c4f9cf8", "3dd1919240584dc9aaf385f643791bf5", "0532b574eff44a94a4ff2be7d7d55c49", "8cee0b973b8d49188f23cacf3ca04994", "c919e261980e4bedb02231077c7f664e", "57f5f52087434a408730016e585b0597", "d43b44b13ce34645b8232f39d8b4789a", …]
 jex /home/carson/pCloudDrive/Joplin/Backup/allNotebooks/joplin_active_backup_job/all_notebooks.jex
/tmp/.mount_JoplinPo…n/lib/Logger.js:188 12:04:52: PluginRunner: Got message (3): joplin.settings.value backupInfo
/tmp/.mount_JoplinPo…n/lib/Logger.js:188 12:04:52: PluginRunner: Got message (3): joplin.settings.setValue backupInfo [{"name":"202109041154","date":1630770863326},{"name":"202109041204","date":1630771491093}]
/tmp/.mount_JoplinPo…n/lib/Logger.js:188 12:04:52: PluginRunner: Got message (3): joplin.settings.value backupInfo
/tmp/.mount_JoplinPo…n/lib/Logger.js:188 12:04:52: PluginRunner: Got message (3): joplin.settings.setValue backupInfo [{"name":"202109041154","date":1630770863326},{"name":"202109041204","date":1630771491093}]
/tmp/.mount_JoplinPo…n/lib/Logger.js:188 12:04:52: PluginRunner: Got message (3): joplin.settings.value backupInfo
/tmp/.mount_JoplinPo…n/lib/Logger.js:188 12:04:52: PluginRunner: Got message (3): joplin.settings.setValue lastBackup 1630771491093
/tmp/.mount_JoplinPo…n/lib/Logger.js:188 12:04:52: PluginRunner: Got message (3): joplin.settings.value fileLogLevel
/tmp/.mount_JoplinPo…n/lib/Logger.js:188 12:04:53: Saving settings...
/tmp/.mount_JoplinPo…n/lib/Logger.js:188 12:04:53: Settings have been saved.

**Comment by laurent22** [comment]
That should be reported on the backup plugin page.
