### ISSUE TITLE
Application does not start minimised even though the option is active

### ISSUE THREAD

**Issue by Elaborendum** [laurent22/joplin#5424]
I turned off the option in Options>Application for Joplin to start minimized to system tray, but it opens maximized anyway and with no icon in the system tray. I also tried making a shortcut for it to open minimized, but it opens maximized regardless.

I've never used either option before, so I can't say for sure if it ever worked on any earlier version on my end.

## Environment

Joplin version: 2.3.5
Platform: Windows
OS specifics: 10

## Steps to reproduce

From Joplin:
1. Go to Options>Application
2. Turn on "Start application minimized in the tray icon"
3. Close Joplin
4. Open Joplin and see that it starts maximized and with no tray icon

From the OS itself:
1. Create a shortcut to open Joplin
2. Go to Properties>Shortcut
3. Select "Minimized" in Execute in the options below
4. Restart Joplin and see that it starts maximized

## Describe what you expected to happen

Joplin starts minimized (and with a tray icon with the first method)

## Logfile
From the console output:
https://gist.github.com/Elaborendum/6ed67a589ada6760fbf0f50e35255aa5

**Comment by roman-r-m** [comment]
Sorry if it's obvious but do you have "Show tray icon" checked? It must be for this to work.

**Comment by Elaborendum** [comment]
I've tried with that option enabled and disabled, it only makes the tray icon appear, but Joplin doesn't open minimized regardless. Instead, with "Show tray icon" enabled, it just opens into a maximized white screen that only seems to load if I close and open it again.

Side note: It's probably dumb on my part, but if that's the case, the "Start application minimized in the tray icon" should probably not be clickable unless the prior option is checked.

**Comment by zerog981** [comment]
Same behavior here. See #5305

**Comment by Elaborendum** [comment]
It hasn't been fixed yet, it's still present.

**Comment by Elaborendum** [comment]
It hasn't been fixed yet, it's still present.

**Comment by Elaborendum** [comment]
I was using 2.7.13, seems to be fixed somewhat in 2.7.15. I will probably open a new issue about https://github.com/laurent22/joplin/issues/5424#issuecomment-913236997.
