### ISSUE TITLE
Stuck in full screen (even after restart)

### ISSUE THREAD

**Issue by Eru-gg** [laurent22/joplin#5427]
## Environment

Joplin version:  2.3.5
Platform:  Windows
OS specifics:  8.1

## Steps to reproduce

1. Click to open Joplin
2. *While* it's opening, hit F11 (thinking it'll apply to Firefox)
3. Joplin is full screen now and there is no way to go back to a window
4. Even if I restart Joplin or restart the machine, Joplin always starts in full-screen mode

## Describe what you expected to happen

There should be a way to turn the full-screen off

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/7115603/log.txt)

**Comment by Eru-gg** [comment]
Solved by:
1. uninstalling the app
2. remove AppData/Local/@joplin
3. remove AppData/Roaming/@joplin
4. install again
(my old notes were still available, but maybe that's because of the Dropbox connection)

**Comment by Midnight1938** [comment]
I am facing the same problem, uninstalling and removing the data did nothing
