### ISSUE TITLE
Exporting a Notebook only exports its latest note

### ISSUE THREAD

**Issue by partisaani** [laurent22/joplin#5428]
Exporting a notebook or sub-notebook into .pdf or HTML exports only its latest note instead of all of the notes, sub-notebooks and the notes in those sub-notebooks.

## Environment

Joplin version: 2.3.5
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Create a Notebook
2. Create a two or more notes in the notebook
3. Right click Noitebook, `Export` -> `HTML - HTML file` 
**OR** 
5. `File` -> `Export all` -> `PDF - PDF file`
6. Generated file only contains the latest note in Notebook

## Describe what you expected to happen
1. Create a Notebook
2. Create a two or more notes in the notebook
3. Right click Noitebook, `Export` -> `HTML - HTML file` 
**OR** 
5. `File` -> `Export all` -> `PDF - PDF file`
6. Generated file contains all of the notes, sub-notebooks and their respective notes

## Logfile
```
Export HTML result:  
  { warnings: Array(0) }
```

**Comment by mitej23** [comment]
Notebook -> Export -> HTML - HTML file    ==> It will give the html version of the file which is selected.
If you want to get HTML file of the entire directory then click on HTML directory.

PDF of single file is only available.

PDF of the entire notebook would be a nice feature.  It can help people to share pdf form of their notebook. Let's see what others has to say.

**Comment by partisaani** [comment]
> Notebook -> Export -> HTML - HTML file ==> It will give the html version of the file which is selected.

If I have selected a Notebook or multiple notes I would expect this to aggregate the selected content(s) into a single .html file. This would bear a 1:1 resemblance to the way I'd expect the selected Notebook to PDF -export to function.
