### ISSUE TITLE
Automatically associate tags

### ISSUE THREAD

**Issue by Wusir2018** [laurent22/joplin#5430]
hello everyone,
Thanks for the open-source!
I use Joplin to record my thoughts on SCI papers! And I creat my template!

`How to realize the automatic association of tags in the template?`

For example, this is my template.
`**Publish：** 2021

**Journal：** IEEE Transactions on Smart Grid

**Rank：** SCI 1
`
The journal `IEEE Transactions on Smart Grid` belongs to `SCI 1`. 
Once I have determined the journal name, how can I automatically add tags “IEEE Transactions on Smart Grid” and "SCI 1"？

![image](https://user-images.githubusercontent.com/51500032/132296388-f40cc44f-7899-4936-8521-aeef3f4c9fac.png)

Best wishes!

**Comment by JackGruber** [comment]
GitHub issuses are only for error reports. If you have a question, please post it here: https://discourse.joplinapp.org/

**Comment by Wusir2018** [comment]
OK, thank you very much!
