### ISSUE TITLE
 Synchronisation Problem: Got metadata for path but could not fetch content

### ISSUE THREAD

**Issue by DrAxelbauer** [laurent22/joplin#5434]
Hi there!
I am using Joplin since some years now – Great App!!! Thanks :) 

My issue:
Synchronisation process fails with:
`Abgeschlossen: 07/09/2021 12:03 (7s)
Letzte Fehlermeldung: Error: Got metadata for path but could not fetch content: fcc23f85a7bf41e988e9465c8a81cc06.md`
I am facing this issue since about one month. The problem appears on both devices.

I facing the issue und my two devices:
1. Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.7
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-81-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-8565U CPU @ 1.80GHz
Memory: 15,4 GiB

2. Anroid
Joplin 2.3.4
on Lineage os 17.1. with Android 10

## Steps to reproduce

1. Start App
2. Try Synchronisation
3. Fails with above mentioned problem

Log Files attached....
[syncReport-1631010800799.txt](https://github.com/laurent22/joplin/files/7120826/syncReport-1631010800799.txt)
[syncReport-1631009464002.csv](https://github.com/laurent22/joplin/files/7120830/syncReport-1631009464002.csv)

**Comment by laurent22** [comment]
It means your server is listing some files, but some of these files don't exist. Probably some caching or server bug.

**Comment by DrAxelbauer** [comment]
Okay i will take a look. The file is present at the nextcloud instant but intrestingly it has 0 bytes ...

Am 7. September 2021 14:52:22 MESZ schrieb Laurent ***@***.***>:
>It means your server is listing some files, but some of these files don't exist. Probably some caching or server bug.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/laurent22/joplin/issues/5434#issuecomment-914280419
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by DrAxelbauer** [comment]
Okay the file in case is definitively present at the nextcloud instant. Any suggestions how i should proceed and solve the issue? I think the problem exists with more notes and i cannot reconstruct which i changed on my android device and which on my desktop, so i don't want to make a full resync on one of the devices....thx benjamin.

**Comment by laurent22** [comment]
You could simply delete the file in the sync target

**Comment by DrAxelbauer** [comment]
Okay i think you can close it. I deleted the file making troubles. It was a file which showed up on the NC with 0 bytes. But in fact it had content:
`id: 99b595fc4e1848b18e306b62f2b4f99a
parent_id: ac2a4a02206041baae5503a466c66ce8
created_time: 2021-08-06T19:14:39.215Z
updated_time: 2021-08-06T19:14:39.215Z
is_conflict: 0
latitude: 0.00000000
longitude: 0.00000000
altitude: 0.0000
author: 
source_url: 
is_todo: 0
todo_due: 0
todo_completed: 0
source: joplin
source_application: net.cozic.joplin-mobile
application_data: 
order: 1628277279210
user_created_time: 2021-08-06T19:14:39.215Z
user_updated_time: 2021-08-06T19:14:39.215Z
encryption_cipher_text: 
encryption_applied: 0
markup_language: 1
is_shared: 0
share_id: 
conflict_original_id: 
type_: 1`

Sync works again. Seems to be a workaround...Thx for help!

**Comment by janklostermann** [comment]
Unfortunately the problem occured exactly as described on my setup as well (Win Joplin 3.4.12, Nextcloud Hub 10 (31.0.7) (NC), Android Joplin).

The file is available on Win, on NC it has 0 Bytes, does not appear on Android. On Win the Joplin error message occurs: `Last error: Error: Got metadata for path but could not fetch content: 756ee0e4fde54e4788f7d1aa860ebb34.md`
Then I deleted the file on NC, synced on Win an got a Conflict, that I tried to resolve with the ConflictResolution-Plugin, which responded: `not found` 

Exporting the note from win into .jex and opening it via a text editor got me the text and metadata that I found in other notes on NC as well. Thus I just copied it into the 0 byte note `756ee0e4fde54e4788f7d1aa860ebb34.md` (that I had downloaded from NC, before I deleted it there) and uploaded it back to NC. Unfortunately this did not make the trick.

Beyond this the syncing on Win got me the same error message for a next note...

Interestingly new notes from Android do not reach Win through sync (probably due to the error), but new notes from Win reach Android.

Has someone experienced similar issues? Or found out, what the initial problem was? (Why there is a 0 byte note on NC, that should have content?) Help would be highly appreciated.

**Comment by janklostermann** [comment]
@DrAxelbauer or @laurent22 could you please reopen the issue?

**Comment by janklostermann** [comment]
maybe this could be helpful too: https://discourse.joplinapp.org/t/investigating-got-metadata-for-path-but-could-not-fetch-content/45051, eventhough I am not sure, if its exactly the same, as I haven't seen this reference to a second file yet, as described in there.

**Comment by janklostermann** [comment]
following this description 
https://discourse.joplinapp.org/t/error-got-metadata-for-path-but-could-not-fetch-content/14939
I was able to the rid of the error, it appeared again with the next file -> this time it resulted in an automatically started sync on win which created 381 remote item (catch up?) and ended in this error message
```
Created local items: 29.
Updated local items: 6.
Created remote items: 381.
Updated remote items: 1.
Fetched items: 158/160.
Completed: 2025-11-14 12:44 (334s)
Last error: Error: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: notes.id: INSERT INTO `notes` (`id`, `parent_id`, `title`, `body`, `created_time`, `updated_time`, `is_conflict`, `latitude`, `longitude`, `altitude`, `author`, `source_url`, `is_todo`, `todo_due`, `todo_completed`, `source`, `source_application`, `application_data`, `order`, `user_created_time`, `user_updated_time`, `encryption_cipher_text`, `encryption_applied`, `markup_language`, `is_shared`, `share_id`, `conflict_original_id`, `maste
```
I start getting worried about bigger data loss...

Deleting the concerned notes in Joplin (after saving the content (and links) to another note), the problem disappeared.
(The one note I messed with by deleting the corresponding file in Nextcloud manually, I had to delete twice -> probably the reason for the "UNIQUE contraint failed": the note was registered twice)

Therefore I could resolve the problem. But still have no idea how it appeared in the first place.
