### ISSUE TITLE
"Fatal Error: Cannot find module ' ../packagelnfo.js' require stack

### ISSUE THREAD

**Issue by lilmoancapystan** [laurent22/joplin#5436]
## Environment

Joplin version: 1.5.11
Platform: linux
OS specifics: ubuntu focal fossa 20.04

## Steps to reproduce

1. click in the icon of the app in the workplace 
2. get a popup message 
![image](https://user-images.githubusercontent.com/74574190/132448386-eeece584-cb90-41ce-835d-29e0ce7757c8.png)

3. 

## Describe what you expected to happen
well, open the app.

**Comment by laurent22** [comment]
Not sure what's causing this but it's an old version anyway. Try with the latest one.

**Comment by Tommy-01** [comment]
Same Problem here. 
Platform: Linux Mint 20.2
Joplin: 2.3.5

file:///home/blue/Schreibtisch/1.png

**Comment by Tommy-01** [comment]
For me the solution was:
Erase all Joplin folders and did an clean "install".
