### ISSUE TITLE
Joplin inserts \ character before _ inside a URL

### ISSUE THREAD

**Issue by michaelkowalczyk** [laurent22/joplin#5440]
Problem: When manually text-selecting a full URL in the Joplin Editor and copying the URL Joplin will insert a backslash \ character before a underdash _ and make the URL invalid.

However: right click URL > copy link does not lead to pasting a invalid url.

## Environment

Joplin version: 2.3.5
Platform: macOS 
OS specifics: Mojave 10.14.6 

## Steps to reproduce

1. In Joplin Editor manually text select and copy a full URL Link which includes a underdash "_" 
For example https://www.gew-saarland.de/images/pdf/Impulse_HattieStudie_Internet.pdf
2. Paste the URL in the browser and notice that the inserted text will include a backslash before the underdash "\_"
https://www.gew-saarland.de/images/pdf/Impulse\_HattieStudie\_Internet.pdf

Funny note: Github seems not to be able to actually show  \ _ withouth the space in between

## Describe what you expected to happen

Expected not to insert a character into a URL 

## Logfile

Debug seems not not record copy&paste

**Comment by Daeraxa** [comment]
Isn't that just because of markup? i.e. it has to put a backslash to escape the underscore that would otherwise make it _italics_?
If you right click->copy link address or ctrl+click it then it takes the url correctly.

**Comment by michaelkowalczyk** [comment]
> Isn't that just because of markup? i.e. it has to put a backslash to escape the underscore that would otherwise make it _italics_?
Not sure. In fact I do not use the markup editor at all.
This is what is written in the non-markup editor on the left side:
[https://www.gew-saarland.de/images/pdf/Impulse\_HattieStudie\_Internet.pdf]
(https://www.gew-saarland.de/images/pdf/Impulse_HattieStudie_Internet.pdf)

> If you right click->copy link address or ctrl+click it then it takes the url correctly.
yes
