### ISSUE TITLE
Attaching a file multiple times multiplies storage space usage

### ISSUE THREAD

**Issue by jl6** [laurent22/joplin#5441]
## Environment

Joplin version: 2.3.5, AppImage
Platform: Linux
OS specifics: Ubuntu 20.04

## Steps to reproduce

1. Drag a file onto a note to attach it.
2. Drag the same file onto a note.
3. Note that the file will be stored twice in the `.config/joplin-desktop/resources` folder.

This means the user's storage space requirement, and time required to sync, is doubled, or tripled or more, depending on how many times the file is attached. Efficient use of storage space is important for users that sync notes to mobile devices which typically have a much lower capacity than desktop devices.

It is true that a user could avoid duplicate storage space usage by copying & pasting the internal resource reference instead of re-attaching a file, but this is not guaranteed to happen. Users should expect applications to use their resources efficiently by default.

[Some previous discussion of the issue](https://discourse.joplinapp.org/t/resource-deduplication/6222).

## Describe what you expected to happen

Joplin could, for example, take a hash (e.g. SHA256) of files at the point of attachment, only store them if they are not already stored, and then reference them using the hash.

## Logfile

No warnings or errors.

**Comment by jango-fx** [comment]
+1

especially since the proposed solution (https://discourse.joplinapp.org/t/resource-deduplication/6222) seems like quite the easy fix to me…

**Comment by jl6** [comment]
It still requires the community's attention.

**Comment by jl6** [comment]
It still requires the community's attention.
