### ISSUE TITLE
When using `joplin.data.post(['notes'], null, item)` to insert a large number of notes, it will eventually get stuck

### ISSUE THREAD

**Issue by rxliuli** [laurent22/joplin#5443]
## Environment

![image](https://user-images.githubusercontent.com/24560368/132610309-743aee1b-b0f6-4649-8ac2-e6bee732086a.png)

## Steps to reproduce

1. Call `joplin.data.post(['tags', item.tagId,'notes'], null, {id: item.noteId, }) in the plugin
2. An error has occurred and all written data has been cleared

![joplin 大量写入 tag-note 关系时错误演示](https://user-images.githubusercontent.com/24560368/132610352-397f24ad-8b7c-47e0-a35e-f05b73b6d4d4.gif)

```js
Uncaught (in promise) Error: Not Found
    at Object.<anonymous> (C:\Users\rxliuli\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\services\rest\routes\tags.js:25:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\rxliuli\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\services\rest\routes\tags.js:5:58)
```

**Comment by rxliuli** [comment]
I now replace them all with joplin.data.* plugin api, but there are new problems, mainly when writing a lot of notes, it will get stuck in the end. . .

![image](https://user-images.githubusercontent.com/24560368/132626917-91dfbc02-e873-4bb4-8282-da76d7bfc3c3.png)

**Comment by laurent22** [comment]
Could you provide a simple code example please? Because the code you mentioned `joplin.data.post(['tags', item.tagId,'notes'], null, {id: item.noteId, })` doesn't correspond to what's on your link.

**Comment by rxliuli** [comment]
> Could you provide a simple code example please? Because the code you mentioned `joplin.data.post(['tags', item.tagId,'notes'], null, {id: item.noteId, })` doesn't correspond to what's on your link.

I already know the cause of this problem. I didn’t have await which caused the call to `joplin.data.post(['tags', item.tagId,'notes'], null, {id: item.noteId, })` Doesn't exist yet. . . The problem now is that creating notes in batches will eventually get stuck for a long time

**Comment by laurent22** [comment]
If you have some minimal code I can use to replicate the problem I can take a look.

**Comment by rxliuli** [comment]
I packaged a plug-in, you can install and then export and import all notes, you should be able to see this problem in the console of the plugin

[joplin-plugin-backup-prettier.zip](https://github.com/laurent22/joplin/files/7138005/joplin-plugin-backup-prettier.zip)

**Comment by rxliuli** [comment]
https://user-images.githubusercontent.com/24560368/132723415-319e9225-5bce-4416-9ba8-20579b759c5c.mp4

**Comment by rxliuli** [comment]
如果需要，你可以从源代码处获取更多细节

1. git clone https://github.com/rxliuli/joplin-utils.git
2. yarn
3. cd apps/joplin-plugin-backup-prettier/
4. yarn dev
5. Add plugin
6. Restart joplin
7. Set token/port, then export all notes to a temporary directory
8. Start joplin development mode from the command line (if any, you need to delete database.sqlite before starting)
9. Add plugin
10. Restart joplin development mode
11. Import all notes from the directory just exported
12. This problem occurs

**Comment by rxliuli** [comment]
Is there any progress?

**Comment by laurent22** [comment]
Sorry it doesn't work for me:

```
$ yarn dev
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/src/joplin-utils/libs/joplin-plugin-cli/dist/bin.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by rxliuli** [comment]
> Sorry it doesn't work for me:
> 
> ```
> $ yarn dev
> node:internal/modules/cjs/loader:936
>   throw err;
>   ^
> 
> Error: Cannot find module '/src/joplin-utils/libs/joplin-plugin-cli/dist/bin.js'
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
>     at node:internal/main/run_main_module:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> ```

Sorry, the second step should be yarn && yarn setup

**Comment by laurent22** [comment]
If I run `yarn dev` now it doesn't crash but it gets stuck forever and doesn't print any message. I wonder if the regular way to build a plugin, although less optimised, would have been better? At least it prints something and I could have figured out how to fix it, while now I can't help because I'm not familiar with the code.

**Comment by laurent22** [comment]
Is there any simple script that will show the problem? For example, something that loops and automatically creates notes or tags?

**Comment by rxliuli** [comment]
> If I run `yarn dev` now it doesn't crash but it gets stuck forever and doesn't print any message. I wonder if the regular way to build a plugin, although less optimised, would have been better? At least it prints something and I could have figured out how to fix it, while now I can't help because I'm not familiar with the code.

Yarn dev starts the monitoring mode, it will automatically see the code changes and automatically build to the dist directory, you can directly add the directory as a plug-in.

**Comment by rxliuli** [comment]
> Is there any simple script that will show the problem? For example, something that loops and automatically creates notes or tags?

I guess using the api to import hundreds of notes and then calling other apis should be able to reproduce it, but I am taking the subway now, and I will try to add a unit test that can reproduce the error later.
