### ISSUE TITLE
[feature request] duplicate note

### ISSUE THREAD

**Issue by jhf2442** [laurent22/joplin#545]
### Application

- Mobile

The desktop application allows duplicating a note by right-clicking on it.

We should add the same functionality to the mobile app. It could be done for example when a note is long pressed. In that case, add a new button (next to the delete button for example), and clicking on it would duplicate the note.

The code that handles displaying/hiding the buttons when a note is selected is in `screen-header.js` (search for `noteSelectionEnabled`).  Currently there's `deleteButton_press` to delete a note, so you'll need to add something like `duplicateButton_press` to handle note duplication. Search for `Note.duplicate` for examples on how to duplicate a note.

**Comment by jonathan-s** [comment]
I echo this. Though the way I would go about it. Create a new setting, templates. If a template exist you can create a note from a template. When creating a note from a template it'll be a copy of that note.

**Comment by Zboubinours** [comment]
+1.

Would really love to be able to create note templates.

**Comment by tessus** [comment]
Status: 

- `Duplicate` is currently available in the desktop clients (right click on a note)
- functionality is missing in mobile and terminal apps

**Comment by sgostelow** [comment]
+1 For either:

1) Add function to duplicate notes for mobile.  This is critical for my use on Android.  I have a pre-defined note (or it could be called template) for meeting minutes that I am unable to use on my phone.

OR

2) Add a more advanced template function to allow creating new notes based on a pre-defined list of templates.

Option 2 seems like a much bigger job, so I would vote for adding the "duplicate note" function to mobile apps as a short term fix.

**Comment by laurent22** [comment]
@jhf2442, this has been implemented on desktop, so I've updated your post so that's it's only about the mobile changes (for cli, the `cp` command has been there pretty much since day 1).

It's also a good-first-issue so I've added a more detailed spec in case someone wants to take it.

**Comment by alanfortlink** [comment]
Hi, I will work on this issue. One question that came up is, once the user chooses to duplicate a note, do I automatically create a new one named "<old_name> Copy" or something like that or do I give the option to choose a name?

**Comment by laurent22** [comment]
@alanfortlink, have a look at Note.duplicate - all the logic is in there, including to give a unique name to the note, so if you use this function you don't need to re-implement this.

**Comment by alanfortlink** [comment]
Thanks for the heads up!

**Comment by alanfortlink** [comment]
Is there any guide to building the ReactNative app? I am having a few errors when I try to do it. I think they can be solved by running `npm install` but when I do it, I get a few errors too. Could you point me in some direction?

**Comment by laurent22** [comment]
Yes it's documented there: https://github.com/laurent22/joplin/blob/master/BUILD.md

If you're still having errors after that, feel free to post here.

**Comment by alanfortlink** [comment]
https://github.com/laurent22/joplin/pull/1969

I just created the pull request for this. Please let me know if there is something that has to be changed and I'll be happy to do it. Thanks.

**Comment by tessus** [comment]
added via #1969
