### ISSUE TITLE
The children of the notebook cannot be moved to the root level

### ISSUE THREAD

**Issue by ystyle** [laurent22/joplin#5453]
## Environment

Joplin version:  2.3.5
Platform:  linux and widows 10
OS specifics:  Linux distribution and windows10

## Steps to reproduce

1.  Create multiple notebooks 
2.  Accidentally drag and drop notes to other notebooks to become children
3.  Cannot move the child's notebook back to its original location (root)

## Describe what you expected to happen
Can move the child's laptop back to root

**Comment by JackGruber** [comment]
From the documentation:
> To move it back to the root, drag and drop it on the "Notebooks" header. Currently only the desktop app can be used to organise the notebooks.

https://joplinapp.org/help/#sub-notebooks

**Comment by ystyle** [comment]
> From the documentation:
> 
> > To move it back to the root, drag and drop it on the "Notebooks" header.
> 
> https://joplinapp.org/help/#sub-notebooks

I get it, to move to "NOTEBOOKS +", not "All notes"
