### ISSUE TITLE
The recommended installation script AppImage on Linux should not ask for integration when used on a system with AppImageLauncher installed.

### ISSUE THREAD

**Issue by bjotte** [laurent22/joplin#5454]
## Issue:
Current recommended script installation method has a huge possibility of breaking desktop integration of Joplin AppImage when used on a system with AppImageLauncher installed. Causing non-functioning duplicate entries in app menus and program launchers. 

## Environment:

Joplin version: 2.3.5
Platform: Linux
OS specifics: Manjaro KDE, Running AppImageLauncher

## Description:
The fact that the AppImage is triggering the integration question when installed with the script makes it possible to easily break the integration work done by the script. The easy solution is to have a separate AppImage file for use with the script only. For anyone that only wishes to use the standard AppImage file and to let it integrate with the system using AppImageLauncher the current file is fine, but for those that use the script as well as using AppImageLauncher it breaks desktop integration work done by the script. This causes duplicate non-functioning entries in app menus and program launchers. The breakage comes from AppImageLauncher popping up a dialog box asking for integration, IF a user mistakenly clicks on "Integrate and run" instead of "Run once", then AppImageLauncher will remove the AppImage file from the current location to the default AppImage location and make a new desktop file. There is no way to blacklist an AppImage from integration in AppImageLauncher, and the convention is to make the internal desktop file in the  AppImage contain a flag to make it not trigger the integration question at all. As it stands the User will Have to click on "Run once" every time they run Joplin. 

## Steps to reproduce:

1. Have AppImageLauncher installed on system.
2. Use recommended installation script for Linux.
3. Run Joplin.
4. This box will pop up and ask about integration:
![image](https://user-images.githubusercontent.com/45982502/133066482-fd970967-4491-484e-8a01-d451b3cda88a.png)
5. If you click "Integrate and run" you have broken the integration work done by the script.

## Describe what you expected to happen:
Expected behavior is that installing with the recommended script will result in a AppImage that will not integrate with AppImageLauncher as the integration work is done by the script. 

## Solution:
The recommended installation script should use a separate AppImage file from the one found under releases for general use. This AppImage needs the internal .desktop file to include the line `X-AppImage-Integrate=false`. This will stop triggering the integration question from AppImageLauncher and thereby hindering any unintended breakage.

**Comment by Daeraxa** [comment]
I wasn't aware of AppImageLauncher before, is there any downside to just downloading the .appimage directly instead of using the script if you are using it?

**Comment by bjotte** [comment]
> I wasn't aware of AppImageLauncher before, is there any downside to just downloading the .appimage directly instead of using the script if you are using it?

The only downside to using AppImageLauncher instead of the script is the loss of app icon. While Joplin is unaffected by using AppImageLauncher to integrate it into the system, it creates a workflow issue to not have the app icon, at least it is a problem if you use a desktop environment that use icon only taskbar / app docks, or prefer to only use icon only taskbar. In some cases the app is invisible without the icon, in most cases you can infer where it is if there is a gap, but as I said it becomes a workflow issue when the app icon is missing.
