### ISSUE TITLE
Cannot insert text in markdown editor (Macos)

### ISSUE THREAD

**Issue by greendeth** [laurent22/joplin#5456]
I cannot insert any text into the markdown editor. 

## Environment

Joplin version: 2.3.5
Platform: macos
OS specifics: 

## Steps to reproduce

1. Switch to markdown editor
2. Press 'i' vim key to enter insert mode (or vim editor mode disabled just click on the blank space)
3. Try and type text. None will appear.

## Describe what you expected to happen

 No text will appear.

**Comment by laurent22** [comment]
Does it work in regular edit mode (not vim)?

**Comment by greendeth** [comment]
Yes. The error occurs in both the ‘Default’ and ‘Vim’ Keyboard modes.

Henry Green
________________________________
