### ISSUE TITLE
XMLParserError when syncing via S3

### ISSUE THREAD

**Issue by CR0CKER** [laurent22/joplin#5457]
When syncing with my S3 bucket from iPad and iPhone, I frequently get an XMLParserError that prevents any changes from being synced onto the server. 

## Environment

Joplin version: 12.3.1 on ios
Platform: ios 14.8
OS specifics: 

## Steps to reproduce

1. Edit tag and content of a note on ios
2. Sync with S3
3. See error

## Describe what you expected to happen

Successful syncing.

## Logfile

<img width="768" alt="2021-09-14 12-52-06-0" src="https://user-images.githubusercontent.com/6056387/133196435-56fa9030-dda9-4583-b7d7-5ab946e03b77.png">
<img width="468" alt="2021-09-14 12-50-28-0" src="https://user-images.githubusercontent.com/6056387/133196449-1eff5dee-7a88-4e49-86a2-2de6b2b62235.png">

**Comment by JackGruber** [comment]
I mean @leematos is working on it https://github.com/laurent22/joplin/issues/5287

**Comment by oliversturm** [comment]
I have this same problem, and while I see that #5287 reported success with a fix six weeks ago, this doesn't seem to help the iOS version. I'm on 12.3.1 like the OP - when will an update be published?

**Comment by leeh11** [comment]
IOS version 12.4.2 still has this bug.

**Comment by CR0CKER** [comment]
Can confirm the issue persists on iOS and prevents notes to get synced. Any fix in the pipeline?

**Comment by leematos** [comment]
@karl-gustav I'm not sure what you mean. The entirety of the stack trace is in the error message above. It's a problem with the AWS-SDK and parsing XML.

It's fixed by using a new AWS-SDK-V3.

**Comment by leematos** [comment]
ah, that's the entire crux of the issue. Something deep in the AWS-SDK causes some requests to generate this XML error, not all, and not consistently. Because of that, we've moved to AWS-SDK-V3 (which has it's own quirks) but uses a different XML parser and I've never seen this error (been running a aws-sdk-v3 joplin build for about a month on my iPhone)

**Comment by atrasatti** [comment]
> ah, that's the entire crux of the issue. Something deep in the AWS-SDK causes some requests to generate this XML error, not all, and not consistently. Because of that, we've moved to AWS-SDK-V3 (which has it's own quirks) but uses a different XML parser and I've never seen this error (been running a aws-sdk-v3 joplin build for about a month on my iPhone)

Do you have a log or trace to report this to AWS? Is this a known issue in the AWS SDK?

**Comment by CR0CKER** [comment]
Seems like it's working now - thanks!

Jan 15, 2022 1:04:32 AM github-actions[bot] ***@***.***>:

**Comment by karl-gustav** [comment]
@CR0CKER Can you try and make this document (as a todo), sync it, then change something and sync it again? We are at least 2 joplin users that can relyably re-produce this error with this document:

```markdown
# Next actions:
- [x] finn ut av model på microbølgeovn
- [x] finn ut kontaktinfo for Siemens Norge
- [x] finn ut av feilkode E0532
- [x] finn ut av SN
- [ ] ring siemens
# Model info:
E-Nr: BE634LGS1/03
FD: 9610
Z-Nr: B12305
Type: SS-42CS

# Div
Kontakt kundecervice: [22 66 06 00](tel:22660600)

#### Feilmld (s.64 i [manual](https://media3.bsh-group.com/Documents/9000967426_J.pdf)): 
Feilmelding "E0532": Åpne og lukk ovnsdøren igjen.
```

**Comment by leematos** [comment]
@karl-gustav thanks for sharing this example. Are you testing on 2.6.10?

II just copied this into my Joplin on my desktop, and synced. No error.

I synced from my phone and it loaded. No error.

I edited the file on my phone (what used to trigger the error for me) and then synced. No error.

Synced on my laptop, edits are visible, and no error.

2.6.10 uses a completely different S3 Lib with a different XML parser, so if you are still getting XMLParserError on 2.6.10 then something really strange is happening.

**Comment by karl-gustav** [comment]
@leematos This happens exclusively on the iOS app (v12.6.2). PC/Mac works fine. (I don’t have an android device to test with)

**Comment by leematos** [comment]
Extra weird. 12.6.2 is using the new lib and is the same version I just tested on my device.

Are your PC/Mac using 2.6.10? I'm wondering if there is some sort of cross-version compatibility issue at play.

**Comment by karl-gustav** [comment]
Yes 2.6.10

**Comment by atrasatti** [comment]
> @CR0CKER Can you try and make this document (as a todo), sync it, then change something and sync it again? We are at least 2 joplin users that can relyably re-produce this error with this document:
> 
> ```gfm
> # Next actions:
> - [x] finn ut av model på microbølgeovn
> - [x] finn ut kontaktinfo for Siemens Norge
> - [x] finn ut av feilkode E0532
> - [x] finn ut av SN
> - [ ] ring siemens
> # Model info:
> E-Nr: BE634LGS1/03
> FD: 9610
> Z-Nr: B12305
> Type: SS-42CS
> 
> # Div
> Kontakt kundecervice: [22 66 06 00](tel:22660600)
> 
> #### Feilmld (s.64 i [manual](https://media3.bsh-group.com/Documents/9000967426_J.pdf)): 
> Feilmelding "E0532": Åpne og lukk ovnsdøren igjen.
> ```

Works for me with Joplin 12.6.2 on iPhone

**Comment by spacemonkey** [comment]
Using 12.6.2 on iPhone X with database v41 - when I try to sync or refresh status nothing happens. When I check synch config it just says please wait and never comes back.

Now what? Can I help identify what is going on?

**Comment by leematos** [comment]
@spacemonkey -- If you aren't seeing an XMLParserError please open a new issue with versions and s3 provider and any logs you can share. If you don't have a region set it's possible that this is your problem (It's a new setting)

**Comment by spacemonkey** [comment]
Thanks @leematos - it was the new region requirement, all working now. Yay!
