### ISSUE TITLE
open... not working

### ISSUE THREAD

**Issue by jhf2442** [laurent22/joplin#546]
### Operating system

- Linux

### Application

- Desktop

using Joplin-1.0.93-x86_64.AppImage

using right-mouse menu "open..." on an attached file leads to following message output on stdout : 
```
   xdg-open -- opens a file or URL in the user's preferred
   application

Synopsis

   xdg-open { file | URL }

   xdg-open { --help | --manual | --version }

Use 'man xdg-open' or 'xdg-open --manual' for additional info.
```

and no other activity (means "nothing happens")

issue happens with JPEG and PDF attachements

**Comment by laurent22** [comment]
Electron opens the file in the default protocol handler, so I think it might be some configuration in the operating system.

https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenexternalurl-options-callback

If you do find how to fix it please post back here so I can add this to the faq.
