### ISSUE TITLE
[feature request] edit attached file

### ISSUE THREAD

**Issue by jhf2442** [laurent22/joplin#547]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

request to be able to edit "in place" attached files, especially pictures.
this would allow to edit a picture, resize it, add annotations to a PDF...

could be combined with the "open..." function but the output file would have to be fed back into joplin

alternative solution, much less user-freiendly, would be to be able to upload a new version of an attachement, overwriting the previous one. (I know I could simply upload a new version as a new file, remove the link to the old attachement and have the auto-cleaner tidy the stuff after 24h but that's the most user-unfriendly way)

**Comment by laurent22** [comment]
Closed as duplicate.
