### ISSUE TITLE
Tab/Space Automatic Indentation

### ISSUE THREAD

**Issue by ColonelPanicks** [laurent22/joplin#5470]
## Environment

Joplin version: 2.3.5
Platform: MacOS
OS specifics: Big Sur 11.5.2 (ARM)

### Tabs being used over spaces in indentation 

1. Create a new document
2. Press space 4 times
3. Add code block backticks (```)
4. Press enter
5. Note that the newline has indented with a tab instead of spaces

### Tabs incorrectly being inserted which breaks indentation

1. Create a new document
2. Press space 6 times 
3. Add code block backticks (```)
4. Press enter
5. Note that the newline is not aligned with that above (it seems to insert 1 tab and 2 "large" spaces which totals the width of 8 spaces)

## Describe what you expected to happen

I would expect the indentation to be matched. While the tab in the example above does match with the four spaces I find that in certain situations (e.g. code blocks embedded in bullet lists) that the tabs can be entered incorrectly such that the newline does not even line up properly for the start with the items above it. 

Would it be possible to set a tab/space preference for the application? 

I don't want to open up a "tabs vs spaces" debate here but I personally prefer spaces and the automatic tab indentation has been frustrating when using 2 spaces for indentation. 

## Logfile

There are no errors reported in the development console.

**Comment by NothingCtrl** [comment]
After update to latest Joplin Desktop, markdown editor seem try to be _"smart"_ when changing my note indent, I don't need behavior, I need note content exactly what I type in (as the reason why using markdow). This is a bug? or  a feature I can turn it off.

**Comment by timhughes** [comment]
Jumping in on this ticket as it is related but maybe more of a feature request. It would be good to have a preference to use spaces instead of tabs and be able to set the number of spaces that represents a tab (or maybe just lock it to a number initially)

**Comment by ylc395** [comment]
This is still an issue.
