### ISSUE TITLE
Incorrect spacing inside and outside editor layout

### ISSUE THREAD

**Issue by n01root** [laurent22/joplin#5472]
OS : Ubuntu 20.04.3 LTS
JOPLIN Version : 2.3.5 (App Image)

After updating joplin from 2.1.x to the current version I noticed that joplin isn't taking advantage of the space it has to expand inside outside editor layout as seen in the below screen shot... This is really annoying and I tried reinstalling it which obviously did not fix the issue. I'm running a note tab plugin of the latest version and I have the layout zoomed out by 3 times. The zoom is not the problem however as even in "Actual Size" it is still not working right and I know as I have been using Joplin for about a year now daily.

As you can see from the pictures below it will not even start at the far left... 
![CopyQ ggAbKo](https://user-images.githubusercontent.com/69567854/133688808-19c78763-1111-4455-9927-0735eed03caa.png)
![image](https://user-images.githubusercontent.com/69567854/133688871-29e15dc4-9ff3-4ca3-b06f-14d947c493af.png)
![image](https://user-images.githubusercontent.com/69567854/133688926-ed92e002-3025-4443-830f-4f1e77096638.png)

**Comment by Daeraxa** [comment]
https://github.com/laurent22/joplin/issues/5339
