### ISSUE TITLE
Unable to open the dialogue to use a custom CSS file

### ISSUE THREAD

**Issue by Nicryc** [laurent22/joplin#5485]
When trying to open the dialogue to load a custom stylesheet for both Markdown and Joplin-wide app nothing happens and an error message is caught.

## Environment

Joplin version: 2.3.5
Platform: Windows
OS specifics: 10

## Steps to reproduce

1. Go to the options
2. Go the "Appearance" tab
3. "Show advanced settings"
4. Try to click on the "Custom stylesheet for rendered Markdown" or "Custom stylesheet for Joplin-wide app styles" buttons
5. Nothing happens

## Describe what you expected to happen

A dialogue is supposed to open and we should be able to select a CSS file.

## Logfile

```
electron/js2c/renderer_init.js:107 Uncaught (in promise) Error: Failed to open
apply @ electron/js2c/renderer_init.js:107
(anonymous) @ electron/js2c/renderer_init.js:83
(anonymous) @ electron/js2c/renderer_init.js:83
(anonymous) @ electron/js2c/renderer_init.js:103
emit @ events.js:310
EventEmitter.emit @ domain.js:482
onMessage @ electron/js2c/renderer_init.js:91
```

**Comment by Rishabhraghwendra18** [comment]
Hi @Nicryc . I am looking to this . Please give me 2 days I will get back to you

**Comment by Dhamma-valence** [comment]
I wanted to mention, I am having the exact same issue with Joplin, version 2.5.10 (prod, linux)

**Comment by Nicryc** [comment]
Still not working on Windows 10 with version 2.6.10.

It's OK on Linux though, same version number using a Flatpak package.

**Comment by Daeraxa** [comment]
For reference this isn't universal, same joplin version on Win10 home 19043.1415. Both open normally.
