### ISSUE TITLE
Exporting Note to Markdown fails (no option to give name of file).

### ISSUE THREAD

**Issue by mattsmi** [laurent22/joplin#5487]
Running Joplin 2.3.5 (prod, linux) Revision 819af3c on Linux Mint 20.2 (current).
Right-click on Note and choose Export. Choosing HTML allows both a directory and a file name to be specified; this works. Choosing Markdown throws up a Choose the Directory dialog but there is no place to specify the file name. It looks like it works, but no output file is produced. (I am presuming this is due to the blank file name resulting from not having specified it.)

## Environment

Joplin version: 2.3.5
Platform: Linux Mint
OS specifics: 20.2 (the latest)

## Steps to reproduce

1. Right-click on Note.
2. Select Export.
3. Select Markdown.

## Describe what you expected to happen
I expected that it would either produce a markdown file in the selected directory having the same name as the Note, or that it would allow a change of file name, but defaulting to the name of the Note (which is the behaviour had HTML been chosen).

**Comment by Rishabhraghwendra18** [comment]
Hey @mattsmi . Sorry for the inconvenience . I am working on this issue

**Comment by Rishabhraghwendra18** [comment]
@mattsmi Everything is working fine on my machine . It will export the notes inside folder named same as the notebook whose notes you are exporting . Please check it once again

**Comment by mattsmi** [comment]
Tested and proved! Brilliant! Thank you so much!
