### ISSUE TITLE
No more action buttons

### ISSUE THREAD

**Issue by RGBYCP** [laurent22/joplin#5490]
I installed today some plugins, like MacOS theme and now I lost all action buttons. The look like squares. I attach a screenshot. How can I reverse this? I removed already some plugins, re-installed Joplin, but nothing. I don't want to lose my notes.

<img width="989" alt="Screenshot 2021-09-21 at 17 02 03" src="https://user-images.githubusercontent.com/52494421/134195871-b825f536-2dd2-44b8-ab7a-7017a843cf3b.png">

## Environment

Joplin version:  Joplin 2.3.5 (prod, darwin)
Platform:  MacOSX
OS specifics: 10.15.7

## Steps to reproduce
I cannot reproduce. Sorry. I cannot fix it either.

## Describe what you expected to happen

Have the action buttons back and not empty squares. Could somebody help maybe? It is pretty difficult to use Joplin like this.

**Comment by Daeraxa** [comment]
Do they come back if you uninstall the theme? Have you checked this section on the theme repo page? - https://github.com/ajilderda/joplin-macos-native-theme#no-icons

**Comment by RGBYCP** [comment]
@Daeraxa I uninstalled now all plugins. No, I was not aware of this repo page, but it looks beautiful.
Removal of all plugins brought back the icons. Previously, I removed some one by one, but maybe the right one wasn't among them. I will try again.

**Comment by PythonSchlumpf** [comment]
Sorry about this. All is good, the issue can be closed. I just don't know how. Sorry.
