### ISSUE TITLE
the APP_BASE_URL contain `path` will raise path not found error

### ISSUE THREAD

**Issue by runchard** [laurent22/joplin#5492]
As server [README.md](https://github.com/laurent22/joplin/blob/dev/packages/server/README.md) shows us 

> - `APP_BASE_URL`: This is the base public URL where the service will be running. For example, if you want it to run from `https://example.com/joplin`, this is what you should set the URL to. The base URL can include the port.

the `path` part, `joplin` in the example, will cause `path not found` error.

## Environment

Joplin version: `dev` @ dc08e1ded548115e731a9a930a4e07afb4fcdd8a
Platform: macOS node v16.9.1
OS specifics: BigSur 11.6

## Steps to reproduce

1. setup the APP_BASE_URL with `http://localhost:22300/joplin`.
2. access the `http://localhost:22300/joplin/api/ping` page.
3. see the `Path not found: joplin/api/ping` page.

## Describe what you expected to happen

1. should working smoothly and see the correct ping page..

## Logfile

```
2021-09-22 20:03:14: [error] App: 404: GET /joplin/api/ping: ::1: Path not found: joplin/api/ping
```

**Comment by andkopp** [comment]
I ran into the same issue. Removing the path also solved it for me.

### Environment

Joplin Server 2.6.10
Docker @ Synology DSM 7.0.1
