### ISSUE TITLE
Problem with the "Goto Anything" feature using shortcut (Ctrl-P)

### ISSUE THREAD

**Issue by guischmo** [laurent22/joplin#5497]
## Environment

Joplin version: Joplin 2.3.5 (prod, win32)
Platform: Windows 10

## Steps to reproduce

0. You have to be in Split view or Editor view as this bugs doesn't occur on the Layout only view.
1. Search any note via the Goto Anything shorcut (Ctrl-P)
2. Click on the wanted note from the resulting list
3. Clicking it won't do anything (sometimes), you will stay on the actual note, you have to do the procedure a second time for it to work correctely.  This also happens if you try to go to the note with the arroy key then Enter key instead of clicking the note.

This issue seems to only hapen with using the shorctut (Ctrl-P), NOT when you click manually on the menu -> Goto anything

## Describe what you expected to happen
Using the shortcut Ctrl-P, searching for a note, clicking on wanted note in the list should open the note.

**Comment by Daeraxa** [comment]
This should be fixed in the pre-release:
https://github.com/laurent22/joplin/issues/5184

**Comment by guischmo** [comment]
thanks, I tried to search for this bug but somehow did not find it this the bug list.
