### ISSUE TITLE
Vim normal mode cursor is narrower than normal

### ISSUE THREAD

**Issue by halian-vilela** [laurent22/joplin#5498]
Hey guys, I've noticed that after I've upgraded to 2.3.5, when using Vim key bidings and navigating in normal mode, the cursor is aprox. half its usual width:

<img  alt="Tela_inteira_23_09_2021_16_09" src="https://user-images.githubusercontent.com/1423653/134569527-bdffc3ef-1fa1-4e4f-9eb7-9d2aed02ad5f.png">

## Environment

Joplin version: 2.3.5
Platform: MacOS
OS specifics: tested in Mojave (10.14.3) and Big Sur (latest)

## Steps to reproduce

1.  Enable Vim Key Bidings in `Preferences > Advanced > Keyboard Mode: Vim`
2. Navigate through the text in Normal Mode

## Describe what you expected to happen
I would expect the cursor to cover characters entirely as it always did, so its easier to see over which character it currently is:

![Tela_inteira_23_09_2021_16_17](https://user-images.githubusercontent.com/1423653/134570027-1609a225-0894-4ced-bd0c-d7e7ed3edbf8.png)

**Comment by graphit0** [comment]
Could replicate it in linux as well.

**Comment by graphit0** [comment]
The bug has disappeared for me in 2.5.1 on linux. Can you confirm it on MacOS?
