### ISSUE TITLE
ToDos not sorting by uncompleted todos on top

### ISSUE THREAD

**Issue by richypops** [laurent22/joplin#5499]
## Environment

Joplin 2.3.5 (prod, win32)

Client ID: 95c4a47251274dac97f468892c8ce281
Sync Version: 3
Profile Version: 39
Keychain Supported: Yes

Revision: 819af3c

on W10 pro 19043

## Steps to reproduce

1. Create a new todo
2. Enter todos
3. Checkmark todos at top of list

## Describe what you expected to happen

Completed todos should move to bottom of list if View/Uncompleted to dos on top is selected

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/7221235/log.txt)

**Comment by Hitansh-Shah** [comment]
@richypops Are you facing this issue on the Desktop app? I use ubuntu 20.04 and i tried to reproduce the issue but the sorting was working fine. All the completed todos were showing below the uncompleted todos.

**Comment by richypops** [comment]
I'm using Windows 10, thanks.
