### ISSUE TITLE
Jopin can't import pictures in evernote

### ISSUE THREAD

**Issue by Daniel-W7** [laurent22/joplin#5505]
## Environment

Joplin version: 2.3.5
Platform: Windows
OS specifics: 11

## Steps to reproduce

1.  import my onenote files into Evernote
2. export notes for Evernote to .enex files
3. import .enex files into Joplin

## Describe what you expected to happen

 I tried to use joplin the first time.
I import my onenote files into Evernote,and everything is OK.
But when I import the notes from Evernote to Joplin,I can't see the pictures in my notes.

**Comment by laurent22** [comment]
Could please share an example ENEX file with this issue?

**Comment by Daniel-W7** [comment]
> Could please share an example ENEX file with this issue?

This one.

It is normal in Evernote,but can't show pictures in joplin

[51、bind9.zip](https://github.com/laurent22/joplin/files/7233549/51.bind9.zip)

**Comment by laurent22** [comment]
It's showing the images for me. I'll need to know what image specifically is not showing up for you, ideally with a screenshot comparing the Evernote and Joplin version of the note.

**Comment by Daniel-W7** [comment]
![image](https://user-images.githubusercontent.com/37373085/136727374-2d94f9be-a9d3-4429-b998-9e1741bafbe3.png)
![image](https://user-images.githubusercontent.com/37373085/136727407-8720898d-19c2-467f-b1ef-b77cb934b9b5.png)

Can you see the pictures in this comment?
My evernote and joplin is not the same
