### ISSUE TITLE
Global search does not properly return all hits for emojis/special characters

### ISSUE THREAD

**Issue by GlassWave** [laurent22/joplin#5506]
## Environment 

Joplin version: 2.3.4
Platform: Samsung Galaxy S9
OS specifics: Stock Android 10.0

## Steps to reproduce 

1. Create a number of regular notes
2. Add some emojis to the note title and note body
3. Search for those emojis using the global search function
4. Observe different responses with different characters despite the same search parameters

## Describe what you expected to happen 

when using the global search function I expect that any and all matches for the word or character - both in the note body and in the note title - will be returned. This tends to happen just fine with regular text. 

However, it does not seem to be the case with certain special characters or emojis. 

I noticed this since I use certain emojis to Mark out special links or other assets within notes to be able to find all of that type easily. 

However I have noticed that when using the global search function B behavior on this is extremely inconsistent. 

e.g. when I search for "🏷️" it will accurately return all hits, title or body, regardless of whether this is a separate character or it is appended to the end of a link or word. But with "✴️" this is not the case, and sometimes it will find it only if it is separate, other times it will identify it if it is part of another word. It will also only accurately find it in no titles about half the time, even if it is completely separate. These are two examples, but I have seen erratic Behavior with at least a dozen different emojis. 

Ideally this bug would be fixed so that if you search for any specific character, emoji or otherwise, you will simply get all of the hits 

## Logfile

[Uploading syncReport-1632627167871.txt…]()

**Comment by JackGruber** [comment]
This is not a bug, works as designed. 
https://joplinapp.org/help/
![grafik](https://user-images.githubusercontent.com/24863925/134810837-d8776f40-0379-406e-95e4-67866df29c75.png)

**Comment by GlassWave** [comment]
> This is not a bug, works as designed.
> https://joplinapp.org/help/
> ![grafik](https://user-images.githubusercontent.com/24863925/134810837-d8776f40-0379-406e-95e4-67866df29c75.png)

I don't know if that is accurate. It is intentional that it will return inconsistent results?

It is not just that it is parsing emojis or graphical icons different than regular tax, but that it is parsing certain emojis different from others, and even more so doing so differently depending on their placement in a sentence or line of text, with no discernible pattern. I cannot imagine that that is by design.

I did try the "/" technique mentioned in the paragraph you iincluded, but it does not seem to make a difference. I am still getting the same buggy behavior.
