### ISSUE TITLE
[Feature Request] adding definition lists to parser

### ISSUE THREAD

**Issue by DerUser** [laurent22/joplin#551]
### Operating system

- macOS

### Application

- Desktop

I suggest the inclusion of HTML Definition List in the parser.
e.g:
```
<dl>
<dt>joplin</dt>
<dd>a cool multiplatform note and checklists app</dd>
</dl>
```
becomes
<dl>
<dt>joplin</dt>
<dd>a cool multiplatform note and checklists app</dd>
</dl>

**Comment by laurent22** [comment]
Is there any way to express definition lists with markdown?

**Comment by DerUser** [comment]
no as far as I know. But markdown or at least most markdown standards include all/most of HTML...

**Comment by AluisioASG** [comment]
Since you seem to be using markdown-it, I found [a plugin](https://github.com/markdown-it/markdown-it-deflist) for definition lists using the [pandoc syntax](http://pandoc.org/MANUAL.html#definition-lists).

**Comment by DerUser** [comment]
As far as I can see this feature seems to be included now. So I'll close the issue
