### ISSUE TITLE
Import "RAW - Joplin Export Directory" does nothing on desktop

### ISSUE THREAD

**Issue by jdnixx** [laurent22/joplin#5515]
I've been having issues with sync for a long time (deserves its own separate issue honestly), I got a new phone recently and tried to sync from the old one to the new one with a freshly-installed Joplin from the play store, but it only synced a couple notebooks, not nearly as many as were on the old phone. Anyway I tried remedying this by using the "export profile" function on the old phone, copying the folder over to my desktop, purging all my notes/notebooks on it (actually just deleted the entire joplin-desktop folder under `.config`) and File > Import > RAW - Joplin Export Directory. Upon selecting the directory, nothing happens. No new notes show up and restarting the application shows no changes.

## Environment

Joplin version: 2.4.9
Platform: Linux
OS specifics: Kubuntu 21.04, latest joplin AppImage; app from old phone was on the latest Play Store version, Android 11

## Steps to reproduce

1. "Export Profile" into a JoplinProfileExport directory from the mobile app
2. Open fresh installation of joplin 2.4.9 on desktop
3. File > Import > RAW - Joplin Export Directory, select exported dir

## Describe what you expected to happen
Anything. But nothing seems to happen at all

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/7263858/log.txt)

**Comment by laurent22** [comment]
Could you check if you have any error or warning in the console? https://joplinapp.org/debugging

**Comment by jdnixx** [comment]
> Could you check if you have any error or warning in the console? https://joplinapp.org/debugging
Yeah sorry, thought the log.txt would include that. Here's the output when I right click & "save as..." from the console:
[-1633099428425.log](https://github.com/laurent22/joplin/files/7268025/-1633099428425.log)

I'm not totally sure that shows the full array either though so screenshot:
![2021-10-01_10-45-52](https://user-images.githubusercontent.com/24235975/135639886-ba3be121-8bbb-409f-9d04-44212d360153.png)

**Comment by jdnixx** [comment]
Still not fixed (just now tried it again; still nothing happens).

**Comment by jdnixx** [comment]
Still nothing on 2.5.12.

I understand this is an open source program & everything & I'm not owed anything, but especially as Joplin is launching paid services, it seems like kind of a game-breaking bug to me to not be able to import at all from an export directory? It wouldn't be that big of a problem except that's the only export option on mobile; and the sync has been broken (at least with Dropbox, what I use) for as long as I can remember, so I've truly been stuck with all my notes trapped on my phone (old phone now... I upgraded to a different one and so just have my big Migrate .zip with joplin + its data preserved "in stasis" inside it, sitting somewhere on one of my hard drives with all my old notes) until whatever point in the future I can figure out how to fix this and get them all back lol. It's pretty depressing honestly

Is it just me or is this a problem anyone else is having? If it's truly just a crazy one-off bug I'd be happy to concede that it's only happening on my end and keep waiting I guess... I'm really not sure what I might've done wrong though, I'm on the latest Kubuntu 21.10 if it matters, using the latest release appimage... seriously just want to get my notes back. Any tips for anything else i might try or could provide to devs to diagnose the issue would be appreciated

**Comment by Daeraxa** [comment]
Performing a profile export from Joplin mobile is not in RAW format (i.e. plain markdown + resources -see [Exporting](https://joplinapp.org/help/#exporting))
Instead you literally output your data as a profile, just like your desktop application profile therefore this isn't an issue with the importer as Joplin cannot ingest an sqlite database when expecting markdown files.

The databases should work between the two, that is to say if you backup your `.config/joplin-desktop` folder on desktop then replace the content within it with the ones from your mobile, (renaming the `joplin.sqlite` database to `database.sqlite`) then you should literally be able to open your mobile profile on desktop. 

If you want do that that then you should back everything up first - extra backups of your desktop profile and export the entire thing as JEX before trying it.

**Comment by jdnixx** [comment]
> Performing a profile export from Joplin mobile is not in RAW format (i.e. plain markdown + resources -see [Exporting](https://joplinapp.org/help/#exporting)) Instead you literally output your data as a profile, just like your desktop application profile therefore this isn't an issue with the importer as Joplin cannot ingest an sqlite database when expecting markdown files.
> 
> The databases should work between the two, that is to say if you backup your `.config/joplin-desktop` folder on desktop then replace the content within it with the ones from your mobile, (renaming the `joplin.sqlite` database to `database.sqlite`) then you should literally be able to open your mobile profile on desktop.
> 
> If you want do that that then you should back everything up first - extra backups of your desktop profile and export the entire thing as JEX before trying it.

OH gotcha, thank you lol that makes a TON more sense. Ok so that wasn't how I was supposed to be using it in the first place...makes sense. What *is* in a profile export anyway then?

Also I realized I could sync to "file system" with the mobile app and that did make what I'm guessing is a RAW directory (with the plain markdown+resources) so I think I should be good to go with importing that on desktop now. Good stuff. Also thought about going into the android app's files and grabbing the .sqlite directly, but there were a few different databases & wasn't sure which one I would need. Good to know they are interchangeable between desktop/mobile though that was another thing I was worried about before trying it.

**Comment by Daeraxa** [comment]
> What is in a profile export anyway then?
The profile export is exactly that, it exports your entire application profile i.e. it creates a copy of your notes database + resources folder, the exact same files your mobile application is working from and that is the mobile counterpart to the `.config/joplin-desktop` folder on desktop. The option is there because most people (without root) wouldn't be able to get a copy of that directory otherwise - as it mentions it is really for debug purposes rather than routine use.

> sync to "file system" with the mobile app and that did make what I'm guessing is a RAW directory 
Not exactly, it creates a sync target, not a RAW export. RAW export preserves the files within the folder structure which is how Joplin knows to import it. The data in the local filesystem sync target is the same as the one in dropbox etc. in that isn't an 'export', it is a sync database that works off deltas and changes. I don't actually know exactly what you would get if you tried to import it but you won't have your notebook structure (plus it stores a bunch of metadata which might be imported as text at the top of each note).

**Comment by jdnixx** [comment]
Ok gotcha. I didn't see a mention about the profile export being mainly for debug purposes but that makes sense, it's right near the other "export debug log" type buttons. In any case I got everything to work with the filesystem sync target thing. Awesomesauce thank you
