### ISSUE TITLE
sync on joplin start

### ISSUE THREAD

**Issue by bemdark** [laurent22/joplin#5519]
while this could be seen as a feature request, I would argue that without this feature, using joplin on desktop and on android becomes unbearable. Every time I write something on my Android phone, I forget to sync beforehand and then have to deal with the conflict. It would be reaally nice if this feature could be implemented.
Don't get me wrong, I really love Joplin otherwise, but I've stumbled upon this every second day since I use joplin and that's really frustrating.

**Comment by JackGruber** [comment]
The GitHub issue track is only for bugs, not for feature requests.
![grafik](https://user-images.githubusercontent.com/24863925/135707159-3f76f651-fdc5-40fe-9d75-97b932f023ff.png)

Post your feature reqest in https://discourse.joplinapp.org/ 

P.S.: The app (Desktop and Mobile) already syncs on start, when you have set a sycronisation time.

**Comment by bemdark** [comment]
> The GitHub issue track is only for bugs, not for feature requests.
I know, but if the android app already syncs on start, then how come that when I edit something on my android phone and have edited something on my desktop literally days ago, I still get conflicts? (either I have misconfigured it or it seems like a bug, thats why I report)
