### ISSUE TITLE
Sabre\DAV\Exception\MethodNotAllowed

### ISSUE THREAD

**Issue by danut2006** [laurent22/joplin#552]
### Operating system

- Linux -Nextcloud Server

### Application

- Desktop yes
- Mobile yes

Hello,

I have some issue regarding connection between the windows app and the Nextcloud server, every time wen the app is   synchronize I receive an error in Nextcloud server ( Sabre\DAV\Exception\MethodNotAllowed). I connect to the server using the WebDabURL.

Thank you!

**Comment by laurent22** [comment]
Closed as duplicate - https://github.com/laurent22/joplin/search?q=MethodNotAllowed&type=Issues
