### ISSUE TITLE
SSL certificate expired error

### ISSUE THREAD

**Issue by stavoltafunzia** [laurent22/joplin#5520]
Joplin refuses to connect to the webdav server with the following error:

> request to <url> failed, reason: certificate has expired (Code CERT_HAS_EXPIRED)

However the certificate is valid (still 2 months till expire date) and issue by letsencrypt. The same certificate works just fine on Firefox and Chrome to browse websites. Mounting the webdav address with davfs also works fine. From my phone the Joplin app works well with the same webdav server.

I'm running the latest AppImage on Debian 11. Even Joplin 2.3.5 (which I was using till before writing this post) was giving the same error though.

The debug console doesn't provide further information unfortunately:

> FetchError {name: "FetchError", message: "request to <url> failed, reason: certificate has expired", type: "system", errno: "CERT_HAS_EXPIRED", code: "CERT_HAS_EXPIRED"}

What is also weird is that this certificate was working fine with Joplin until yesterday, and the certificate hasn't been updated since then. I also verified that there is no man in the middle.

**Comment by CountCypher** [comment]
I observe the same error after upgrade to Joplin 2.4.9 under Fedora 33:

`FetchError {name: "FetchError", message: "request to https://example.com/seafdav/Joplin/J…info.json failed, reason: certificate has expired", type: "system", errno: "CERT_HAS_EXPIRED", code: "CERT_HAS_EXPIRED", …}`

I'm using Seafile WebDav as backend and certificate is valid until December 9th. Sync from Android Joplin App works without error.

**Comment by TuxOtaku** [comment]
I'm getting the exact same error on Joplin Server (2.5.1)

**Comment by uselpa** [comment]
Probably same error with Joplin 2.4.9 on MacOS
```
Last error: FetchError: request to https://xx.yy.zz/remote.php/webdav/Joplin/info.json failed, reason: certificate has expired
```

Worked fine minutes ago with the previous version of Joplin.

**Comment by laurent22** [comment]
See bug below yours
