### ISSUE TITLE
Search doesn't sort by Created Date

### ISSUE THREAD

**Issue by notehoarder** [laurent22/joplin#5524]
When searching in desktop app, the results returned are by Updated Date, despite having Created Date selected.
Thereafter, if one edits a random note in the search results, the search results then become sorted by Created Date. Odd.

If after searching, one goes to View menu and attempts to change the sorting behavior, it still remains Updated Date sorted.

## Environment

Joplin version:  2.3.5
Platform: macOS and WIndows

## Steps to reproduce

1. Search for any word

## Describe what you expected to happen

Sort by Created Date

**Comment by JackGruber** [comment]
The search use [BM25 for the result ordering](https://joplinapp.org/spec/search_sorting/), the selection for `Sort notes by` is not considered.
