### ISSUE TITLE
Joplin iOS app glitching when trying to log in to Joplin Cloud

### ISSUE THREAD

**Issue by breakfastpizza** [laurent22/joplin#5527]
## Environment

Joplin version: 12.4.1
Platform: iOS
OS specifics: 14.8

## Steps to reproduce

1. Go to Configuration menu
2. Synchronization Target > Joplin Cloud
3. Tap Joplin Cloud email field to enter email address
4. Type email address, tap return
5. See blank screen in below screenshot

## Describe what you expected to happen

I expect to enter my login credentials for Joplin Cloud and remain in Configuration menu 

## Logfile

I originally tried this with Joplin that I had installed syncing to Dropbox, the first time it happened I thought it may be I had an old release so I deleted the app and installed a fresh copy.

Here is the screen after entering my email address:
![IMG_6358D11B7AFD-1](https://user-images.githubusercontent.com/1478608/135766867-9e475232-e319-4e0f-a85d-6aec53a1ce36.jpeg)

I was able to tap the save icon as seen in the screenshot but swiping and tapping otherwise could not bring the Configuration menu back. I had to hard exit the app and re-launch to return to the menu.

**Comment by laurent22** [comment]
I think the same bug as this one, basically an iOS bug: https://github.com/laurent22/joplin/issues/4980

**Comment by breakfastpizza** [comment]
Thanks @laurent22, I can confirm that unchecking `Reduce Motion` seems to have corrected the issue. Glad it was so simple!
