### ISSUE TITLE
JoplinPortable can’t update to latest version of plug-ins

### ISSUE THREAD

**Issue by markrenier** [laurent22/joplin#5532]
As discussed in the Joplin Forum: 
https://discourse.joplinapp.org/t/joplinportable-cant-update-to-latest-version-of-plug-ins/20663/2

**Comment by laurent22** [comment]
As mentioned in issue template, there's quite a bit of info to provide such as version, etc. and description and screenshots should be posted here too.

To fix this, someone will have to spend maybe one hour to look into it, so please make our life easier by creating proper issues. And that doesn't take one hour, just 2 minutes.

**Comment by markrenier** [comment]
I opened a more complete issue with step-by-step instructions here: https://github.com/laurent22/joplin/issues/5788  
This issue 5532 is superceded by 5788. Closing this issue now
