### ISSUE TITLE
joplin-cli notes lost if terminal is closed, even after neovim saves the note

### ISSUE THREAD

**Issue by UtkarshVerma** [laurent22/joplin#5533]
## Environment

Joplin version:  joplin 2.4.1
Platform: terminal
OS specifics: Void Linux

## Steps to reproduce

1. Open joplin
2. Open a note. This opens `nvim` in the same terminal.
3. Save the note, and don't close `nvim`.
4. Close the terminal.
5. Reopen joplin only to find the edits made to the note have been lost.

## Describe what you expected to happen
Since I saved the file in `nvim`, I expected it to recover the saved file on reopening joplin. This is important because I never know when I need to stop taking notes, so quitting `nvim` and reopening the note in joplin every time doesn't make sense.

## Logfile
https://pastebin.com/Gi9nMcy3

> This is a critical bug in `joplin-cli`, therefore please see that this is fixed. I have lost my notes lots of times because of this bug.

**Comment by UtkarshVerma** [comment]
Related to https://github.com/laurent22/joplin/issues/184.

**Comment by laurent22** [comment]
The CLI app only works with modal editors so I don't know how neovim works but it shouldn't be possible to make an edit, then close the app, without closing the editor first. Basically you need to make sure it works in modal mode only when opening a note from the CLI tool. The app will wait for the app to close before updating the local note.
