### ISSUE TITLE
Changed syncing target -> all notebooks lost!

### ISSUE THREAD

**Issue by jlgarnier** [laurent22/joplin#5536]
## Environment

Joplin version:
```
Joplin 2.4.9 (prod, win32)
ID client : 4abbb6b47e5446ac89ef43d0d5060265
Version de Synchro : 3
Version du profil : 39
Trousseau supporté : Oui
Révision : bb44c4e
```

Platform: Windows 10 Family
OS specifics: none

## Steps to reproduce

What happened:
- Joplin was syncing with my Dropbox. So far so good.
- I wanted to sync another machine but have a limited Dropbox account, so decided to sync with OneDrive instead.
- Went to Settings > Synchronization and selected 'OneDrive'.
- Once authorized, Joplin started to sync with OneDrive.
- Once done, all my notebooks have vanished and I just have a 'Conflicts' notebook with a lot less items than before!

## Describe what you expected to happen

I was expecting Joplin to push all local notes to OneDrive.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/7286177/log.txt)
[new-log.txt](https://github.com/laurent22/joplin/files/7286200/new-log.txt)

**Comment by laurent22** [comment]
Did you sync with OneDrive before?

**Comment by jlgarnier** [comment]
No, that was the first time!

I've cross-posted to the forum and received an answer (https://discourse.joplinapp.org/t/change-sync-target-lost-all-notebooks/20784/2) but I'm now reaching a blank page when launching Joplin again!

**Comment by Daeraxa** [comment]
Shouldn't the failsafe be kicking in if Joplin detects that it is about to delete the entire database?
There is a similar incident on the fourm here - https://discourse.joplinapp.org/t/fail-safe-activated-what-now/20668

**Comment by jlgarnier** [comment]
I would have love receiving such a notice, but no failsafe when I started syncing with OneDrive!

**Comment by laurent22** [comment]
There's no fail safe for delta sync because we can't know in advance what will be deleted, and not everything was deleted anyway since it was moved to conflict folder.

But this kind of messy sync I think is only possible when there's already something on OneDrive, so I'm not sure we have the whole story.

**Comment by jlgarnier** [comment]
I've checked with OneDrive: Joplin properly created an Application/Joplin folder with roughly 540 .md files in it, along with .lock, .resource etc. Therefore it *seems* the initial sync has occurred but Joplin just displayed the Conflicts folder in the UI. Does this give you some clue?

**Comment by jlgarnier** [comment]
Hi Laurent,

You may close this case, as everything's back to normal operation, even if I don't understand why! 😉 
Thanks again for your help and support, I'm so happy to use Joplin again!
