### ISSUE TITLE
Updating to prerelease

### ISSUE THREAD

**Issue by Digharatta** [laurent22/joplin#5554]
Joplin version: 2.4.9
Platform: Ubuntu
OS specifics: 20.04

Sync stopped working on a desktop app, and I got a message:

"FetchError: request to https://nd.nl.tab.digital/remote.php/dav/files/...@gmail.com/info.json failed, reason: certificate has expired"

I struggled with this issue, and eventually found a solution by updating Joplin to the pre-release 2.5.1 version, using the Joplin_install_and_update.sh script with --prerelease option.

Please include in Read.me the way to easily update Joplin to the pre-release version.

Thank you for your work!

**Comment by Daeraxa** [comment]
There was a pinned issue on github about the certificate error - there was also a workaround for the current release by ticking "ignore TLS certificate errors" as well as topics on the fourms.
This is really a forum topic as it isn't a bug but it might be worth adding to the FAQ? (as most 'normal' users wouldn't be expected to use the pre-release for obvious reasons)
