### ISSUE TITLE
Synchronization problem

### ISSUE THREAD

**Issue by mmjoshi** [laurent22/joplin#5558]
## Environment

Joplin version: 2.5.1 portable 
Platform: Windows 10

## Steps to reproduce

1. Start Joplin on Windows.
2. Hit the synchronize button.
3. After some time get the error "Lock wait timeout exceeded; try restarting transaction".

Expected Joplin to sync with Nextcloud. This has been happening without any problem till today. Suddenly started getting this error.

## Logfile

<!--
  Please attach a debug log. Issues without a debug log are likely to stall.
  For information on how to collect a log file: https://joplinapp.org/debugging/
--
[log.txt](https://github.com/laurent22/joplin/files/7330003/log.txt)
[Joplin console.txt](https://github.com/laurent22/joplin/files/7330011/Joplin.console.txt)
>

**Comment by AndreasAZiegler** [comment]
I have the same issue. I don't think it is Nextcloud related. I'm having this issue since this week and there was no NextCloud update in the meantime.

**Comment by mmjoshi** [comment]
I agree. It's not a Nextcloud issue. It has started happening again for the last couple of days and again there was no change or upgrade of Nextcloud.

Both the desktop and Android versions just keep displaying the Cancel button for a long long time without doing any updates. So frustrating.

**Comment by mmjoshi** [comment]
Looks like the problem is solved for now.

**Comment by laurent22** [comment]
No
