### ISSUE TITLE
New notes not appearing at top of list

### ISSUE THREAD

**Issue by jhill-dci** [laurent22/joplin#5559]
New notes do not appear at the top of the note list.

Joplin version: 2.3.5 (prod, darwin)
Platform: MacOS
OS specifics: Big Sur 11.6

## Steps to reproduce
1. Install Joplin and import notes.
2. Create new note. Note appears at top of note list.
3. Create a second new note.  New note appears below previous new note (above imported notes).
4. Create a third new note.  New note appears above imported notes but below other notes.

## Describe what you expected to happen
New notes should always appear at the top of the list, not above imported notes/below new notes.

## Logfile
[log.txt](https://github.com/laurent22/joplin/files/7330472/log.txt)

**Comment by CalebJohn** [comment]
What do you have selected under View -> Sort notes by?

**Comment by jhill-dci** [comment]
Oh!  I was looking under Preferences for a sort order - changing it from Custom to Date Created does exactly what I wanted.  Thank you!
