### ISSUE TITLE
Joplin 2.4.3 (android 7.1.2) hangs on sync with dropbox

### ISSUE THREAD

**Issue by alcukcoder** [laurent22/joplin#5565]
Up until recently, Joplin was syncing fine on my mobile with dropbox.

Today, sync hangs with the spinner and "cancel" next to it.

It appears wifi is being used but nothing happens for several minutes in the app.

**Comment by Daeraxa** [comment]
You should probably attach logs at a bare minimum
https://joplinapp.org/debugging/

**Comment by IvanVas** [comment]
+1, I get the same.

**Comment by alcukcoder** [comment]
I have solved it:

I uninstalled the app completely, reinstalled it, re authenticated with dropbox, etc... and it works fine now
