### ISSUE TITLE
Export as MD broken

### ISSUE THREAD

**Issue by thwaller** [laurent22/joplin#5566]
## Environment

Joplin 2.5.1 (prod, linux)

Client ID: ceab1d7269024b78abbe7000fe08328e
Sync Version: 3
Profile Version: 39
Keychain Supported: No

Revision: b6b972b

Ubuntu 21.04

## Steps to reproduce

1. Right click -> Export -> MD -Markdown
2. 
3. 

## Describe what you expected to happen

The option to set a name for the file does not appear. In checking the other export options, the naming option is in the center of the top bar. With the MD export, it is no longer there. This prevents the export as MD from working.

**Comment by CalebJohn** [comment]
It is a bit confusing because the name doesn't specify that it's a directory export (in contrast to the html equivalent). Unfortunately, updating it to be more clear will require a re-translation of that name for not clear benefit.
