### ISSUE TITLE
Can't export pdf

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#5578]
I have the same issue as #3594
## Environment

Joplin version: 2.4.12
Platform: Windows 
OS specifics: Windows 10 home 64 bit

## Steps to reproduce

1. Right click on the note you want to export as pdf
2. Choose the directory you want to save
3. No file in that directory appears

## Describe what you expected to happen
Well, there should be pdf file. Other exporting options work as expected.

## Logfile
![image](https://user-images.githubusercontent.com/76991571/137488491-4b38a485-e833-42c8-a4a1-c2c029fa1aee.png)

**Comment by gdnzz** [comment]
Edit: I just found what the problem was and solved it; it was on my side. Go to windows features, and check the microsoft print as pdf option.

**Comment by Glidepixel** [comment]
This is still happening even with Microsoft Print to PDF enabled in Windows Features. This is the joplin I'm running.
Joplin 2.5.12 (prod, win32)

Client ID: 6d28d3f33a0b49dc808fc6d52abb876b
Sync Version: 3
Profile Version: 39
Keychain Supported: Yes

Revision: 884b86f
