### ISSUE TITLE
Sticky shift key on ipad

### ISSUE THREAD

**Issue by kr4z33** [laurent22/joplin#558]
### Operating system

- iOS

### Application

- Mobile

This bug is difficult to describe and does not seem to occur consistently. It's like the shift "key" gets stuck in a depressed state sometimes when going back to edit within previously entered blocks of text. this affects the on screen keyboard, as well as an external keyboard.

So far, I have only noticed it on an ipad. Fortunately I was able to catch this in a video, which is attached below.

[18-05-23 13-34-13 2519 Joplin Bug.zip](https://github.com/laurent22/joplin/files/2037555/18-05-23.13-34-13.2519.Joplin.Bug.zip)

**Comment by laurent22** [comment]
It seems to be a bug recently introduced in React Native - https://github.com/facebook/react-native/issues/19389 I'll update the framework once they fix it.

**Comment by tessus** [comment]
/ref https://discourse.joplin.cozic.net/t/persistant-caps-lock-on-ipad/121

**Comment by laurent22** [comment]
The framework has already been upgraded actually. Is this still happening?

Also is it only when the note contains emojis or all the time? I'm asking as this is the new issue tracking this - https://github.com/facebook/react-native/issues/21243

**Comment by laurent22** [comment]
Thanks for confirming it's working. Closing the issue for now.
