### ISSUE TITLE
Desktop: Synced note is not updated in display and lost with no conflict

### ISSUE THREAD

**Issue by ken1kob** [laurent22/joplin#5582]
When a selected note is synced, it is not updated in display. 
- When this symptom occurs, if you select another note and then select the original note again, it will be properly updated.
- If its un-updated old content is edited, the update by the sync is lost. Besides, nothing is added in the `conflict` folder.
- The symptom occurs in both the Markdown Editor and the WYSIWYG Editor.
- The condition of the symptom occurs:
	- Before the sync of the symptom, a note is edited and synced, in advance. After the in-advance sync and before the sync of they symptom, it has been never edited.

Though editing before a sync is just a conflict, in this case, there is no edit before the sync, and there is no conflict. Even though no conflict, the symptom behaves like a conflict. A user cannot recognize the symptom occurs. It is CRITICAL.

It is often the case when a long note is edited from multiple PCs. In my case, I have been suffering from this symptom ever since I started using Joplin.

## Environment

Joplin version: 2.4.9
Platform:  Windows
OS specifics: Windows10

Sync partner clients: Desktop app 2.4.9 (Win10) and Android app 2.4.3 (Android11)

## Steps to reproduce

1. Edit a note on Desktop A and manually sync. Keep the note displayed.
2. On Client B (Desktop or Android) manually sync, and then edit the same note and manually sync.
3. On Desktop A, manually sync to import Client B's edit.
4. At this time, the display should be updated with Client B's edit. But actually, there is no change.
5. Branch as follows.
  - 5a) If you select another note on Desktop A and return to the original note, you will see Client B's edit.
  - 5b) If you edit the note on Desktop A, Client B's edit will be lost, and it will not be saved in the `conflict` folder.
  
## Describe what you expected to happen

After sync, a note in display should be updated to reflect the changes made by other clients.

## See Also

The below may report the same symptom.

- [Changed notes don’t update on sync if it’s already open · Issue #4700 · laurent22/joplin](https://github.com/laurent22/joplin/issues/4700)

**Comment by ken1kob** [comment]
Overview of the symptom is here.

![image](https://user-images.githubusercontent.com/16041683/137701466-2619117a-8001-47e8-b12c-91957c736295.png)

**Comment by 9cat** [comment]
still has the same issues for the current new version.
