### ISSUE TITLE
how to give props

### ISSUE THREAD

**Issue by rkyleg** [laurent22/joplin#559]
Just wanted to thank you for a couple of features that I found very useful:

1) linking between notes
2) copy/pasting images from the clipboard

Again, I know opening an issue on Github isn't the right place for this type of feedback; however, I wanted you to see it and maybe the community, or yourself, can decide on how to provide this type of feedback to you in the future. 

Let me know, and again thank you for these two features, they were surprises to me and incredibly helpful!

**Comment by rkyleg** [comment]
donations are fine, but not public and I believe that some recognition should be public, i.e. have testimonials on your webpage or have a Twitter ( or other decentralized alternative) account where users can provide public feedback.

**Comment by foxmask** [comment]
[done](https://discourse.joplin.cozic.net/t/sharing-good-vibe/166)
