### ISSUE TITLE
Go => Focus => Note Body does not work with "Viewer" layout

### ISSUE THREAD

**Issue by brttbndr** [laurent22/joplin#5590]
## Environment

Joplin version: 2.4.12
Platform: macOS
OS specifics: 11.6

## Steps to reproduce

1. Start Joplin with a fresh config `/Applications/Joplin.app/Contents/MacOS/Joplin --env dev`
2. Toggle editor layout to Viewer (Cmd+L twice)  
3. Go => Focus => Note Body (or Cmd-Shift-B)

## Describe what you expected to happen

Expected: the focus is in the note body, such that up / down arrows scroll the content

Get instead: The focus is somewhere else (???), arrow keys do nothing. Hitting tab once will focus on the first link ("Markdown Format") and then the arrow keys will work to scroll the note contents. And if you click in the note body instead of using the command, focus works as expected.

Notably, after clicking to focus the note body, a subsequent focus note list command followed by a second focus note body command works as expected.

With the debugger, I see that this line is handling the "focus note body" command in both cases (before and after using a click in the note body):

https://github.com/laurent22/joplin/blob/6bcd80102817885984b0146284bc46db3b0ae573/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx#L150

I infer there's some setup or change in state accomplished by clicking in the note body (that isn't in place if you've only used the focus command).

<img width="900" alt="image" src="https://user-images.githubusercontent.com/60824/137602027-a916229d-4183-4bba-a087-d203541592a9.png">

## Logfile

```
13:54:46: Loading existing note 7dbb47dd46d54468b480295e15231109
main-html.js:48 13:54:46: Loaded note: {id: "7dbb47dd46d54468b480295e15231109", parent_id: "e53fe038cb1346b99334b0f89b16f6c2", title: "1. Welcome to Joplin!", body: "# Welcome to Joplin!↵↵Joplin is a free, open sourc…**, type `:help tag` for the available commands.↵", created_time: 1634416404815, …}
main-html.js:48 13:54:51: CommandService::execute: focusElementNoteBody
main-html.js:48 13:54:51: CodeMirror: execCommand {name: "editor.focus"}
```

**Comment by brttbndr** [comment]
This functionality was implemented for https://github.com/laurent22/joplin/issues/2810 That code is being executed, but does not behave as expected.

**Comment by laurent22** [comment]
I see that the right element gets the focus but indeed nothing happen when I use the down or up arrow. It only works if I click inside the view.

**Comment by brttbndr** [comment]
This seems similar (same root cause?) to this issue from Electron

https://github.com/electron/electron/issues/1773

From that issue, I got the idea of adding a `document.focus` in `dom-ready` handler

```
document.addEventListener('dom-ready', () => { document.focus() });
```

inserted here (near the definition of another event handler)

https://github.com/laurent22/joplin/blob/8d09ed3bacb5da17024402bd8a822549a5a74c3c/packages/app-desktop/gui/note-viewer/lib.js#L190

With this change, I get my expected behavior (Cmd-Shift-B focuses, arrow keys work, no click needed).

I don't know enough about Electron, React, etc. to know if this has any drawbacks. A few minutes of playtesting didn't find any side effects (like -- stealing focus when it shouldn't, or messing up focus for the editor or split view).

**Comment by brttbndr** [comment]
`document.focus` fails with `Uncaught TypeError: document.focus is not a function` after I hooked it up to the `DOMContentLoaded` event

Using `window.focus` instead executes w/out error, but makes no difference; the keyboard focus is still somewhere else.

I played around with `setTimeout`, and it also makes no difference.

However ... noticing that a tab keystroke moves focus "into" the iframe on the first anchor gave me an idea.

We can use IPC to ask the iframe to focus an element. If we ensure that there is such an anchor available, then we get the expected behavior -- keyboard focus lands in the iframe, arrow keys work. (And -- hitting tab will still advance to the first "real" link in the document).

I have a draft PR demonstrating this:

https://github.com/laurent22/joplin/pull/5597

I'm not sure this is a good approach, but it works. Feedback on the approach welcome!

To finalize it, I'd probably:

- consider whether to insert the "dummy" element only on demand, or always (prepending it when setting `contentElement.innerHTML = html`)
- see if I can preserve existing focus w/in the iframe if there is one (so focusing body, list, body preserves the focus w/in the body)

**Comment by mzguy** [comment]
Is this issue related?
https://discourse.joplinapp.org/t/persist-editor-layout-plugin/14411/48?u=mzguy

**Comment by brttbndr** [comment]
@mzguy No, I don't think these 2 issues are related (except that both are about focus). This issue is about focus not going to the note body when it has been explicitly requested by hotkey / command, while the issue you reported is about focus going to the note body when it wasn't requested (as a side-effect of toggling the editor layout).

**Comment by brttbndr** [comment]
This issue was resolved with https://github.com/laurent22/joplin/pull/5597
