### ISSUE TITLE
Use QOwnNotes API for NextCloud / OwnCloud?

### ISSUE THREAD

**Issue by x86dev** [laurent22/joplin#56]
Since a connector for NextCloud / OwnCloud is one of the most anticipated features, it would be at least worth a look at the QOwnNotes API which already exists as an official package. It's also Open Source and would benefit of not having yet another API / way of syncing notes with different apps (QOwnNotes vs. Joplin).

**Comment by laurent22** [comment]
Thanks, I'll check their implementation. It's C++ so I cannot re-use the code directly but it might be useful to see how they did it.

**Comment by x86dev** [comment]
Great, looking forward to it! Thanks.

**Comment by CHBMB** [comment]
Make that two of us looking forward to it!

**Comment by laurent22** [comment]
Resolved in #4

**Comment by sunjam** [comment]
So, will the upcoming version 1.0 release mentioned in the resolving issue above allow Qownnotes API to be used as the Nextcloud server backend for Joplin?
