### ISSUE TITLE
Not able to setup development environment

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [laurent22/joplin#5608]
Hi , I have just started my journey in open source . I want to contribute to joplin but having difficulty in setting up the environment . As per the [docs](https://github.com/laurent22/joplin/blob/dev/BUILD.md) . I have installed the required dependency for linux , since I have a linux machine.

Error I face when running `npm install` in the root directory:
![Screenshot from 2021-10-21 16-47-51](https://user-images.githubusercontent.com/43534227/138266861-66f3bd52-99e4-44fb-9002-7bba34110cab.png)

Afterward if I run `npm run watch` in root directory, then I will get this error:
![Screenshot from 2021-10-21 16-49-42](https://user-images.githubusercontent.com/43534227/138267099-e9c1d67b-bd3e-40fe-b5df-59bcd40f90ac.png)

I studied about the error which occured during `npm install` and found out that `fsevents@2.3.2` is not meant for linux machines , it's for mac . I searched about  it on stackoverflow and it suggested to remove this dependency from root directory's `package-lock.json` file since it's an optional dependency . I don't want to change any dependency on my own since I think there may be a better way to solve it .

## Environment 
Platform: Ubuntu 20.04 LTS
Node version: v14.18.0
NPM version: 6.14.15

## Steps to reproduce

1. just run `npm install` in the root directory and you will see the error

## Describe what you expected to happen
`npm install` should install all dependencies without any error

**Comment by Rishabhraghwendra18** [comment]
after this process is ended another process start executing automatically:
```
> @joplin/app-desktop@2.5.4 build
> gulp build

[19:55:17] Using gulpfile ~/Documents/contribution/joplin/packages/app-desktop/gulpfile.js
[19:55:17] Starting 'build'...
[19:55:17] Starting 'compileScripts'...
[19:55:17] Starting 'compilePackageInfo'...
[19:55:17] Starting 'copyPluginAssets'...
[19:55:17] Starting 'copyTinyMceLangs'...
[19:55:17] Starting 'updateIgnoredTypeScriptBuild'...
[19:55:17] Starting 'buildCommandIndex'...
[19:55:17] Starting 'compileSass'...
Copying to /home/rishabh/Documents/contribution/joplin/packages/app-desktop/tools/../gui/note-viewer/pluginAssets
Copying /home/rishabh/Documents/contribution/joplin/packages/app-desktop/tools/../../../Assets/TinyMCE/langs => /home/rishabh/Documents/contribution/joplin/packages/app-desktop/tools/../node_modules/tinymce/langs
Generating /home/rishabh/Documents/contribution/joplin/packages/app-desktop/commands/index.ts...
[19:55:18] Finished 'compileScripts' after 706 ms
Generated /home/rishabh/Documents/contribution/joplin/packages/app-desktop/packageInfo.js
[19:55:18] Finished 'compilePackageInfo' after 903 ms
Copying to /home/rishabh/Documents/contribution/joplin/packages/app-desktop/tools/../pluginAssets
Generated /home/rishabh/Documents/contribution/joplin/packages/app-desktop/style.min.css
[19:55:18] Finished 'compileSass' after 907 ms
[19:55:18] Finished 'updateIgnoredTypeScriptBuild' after 918 ms
[19:55:18] Finished 'copyTinyMceLangs' after 930 ms
Generating /home/rishabh/Documents/contribution/joplin/packages/app-desktop/gui/MainScreen/commands/index.ts...
[19:55:18] Finished 'copyPluginAssets' after 939 ms
Generating /home/rishabh/Documents/contribution/joplin/packages/app-desktop/gui/NoteEditor/commands/index.ts...
Generating /home/rishabh/Documents/contribution/joplin/packages/app-desktop/gui/NoteList/commands/index.ts...
Generating /home/rishabh/Documents/contribution/joplin/packages/app-desktop/gui/NoteListControls/commands/index.ts...
Generating /home/rishabh/Documents/contribution/joplin/packages/app-desktop/gui/Sidebar/commands/index.ts...
Generating /home/rishabh/Documents/contribution/joplin/packages/lib/commands/index.ts...
[19:55:18] Finished 'buildCommandIndex' after 961 ms
[19:55:18] Finished 'build' after 969 ms
```

**Comment by roman-r-m** [comment]
Maybe try running `npm ci` from the root. If that doesn't help check the full log here:

> ERR! A complete log of this run can be found in:
> npm ERR!     /home/rishabh/.npm/_logs/2021-10-21T14_25_16_002Z-debug.log
