### ISSUE TITLE
S3 compatible storage not fully usable

### ISSUE THREAD

**Issue by iFrozenPhoenix** [laurent22/joplin#5623]
Due to missing options in the advanced section (compared to other sync providers) self hosted S3 compatible storages
are not fully usable.
The missing options I refer to are "use path style" for buckets and ignore TLS errors.

The path style option is necessary for S3 compatible storages. The TLS option would be good for issues like https://github.com/laurent22/joplin/issues/5513 and / or for development purposes. 

## Environment

Joplin version: 2.4.12
Platform:  Windows 11
OS specifics:

**Comment by leematos** [comment]
I think my PR actually exposes path style so that's halfway to a solution: https://github.com/laurent22/joplin/pull/5312

I _think_ if this TLS field is exposed that would enable http? https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/s3clientconfig.html#tls

**Comment by iFrozenPhoenix** [comment]
@leematos 
Unfortunately it seems that there is no "tls skip verify" option in the aws s3 client apis, at least I haven't found it after reading the docs now, so the only alternative would be to just use plain http. The ref you mentioned would allow this.
But this would be completely insecure as the headers (Aceess and  Secrets keys) are unencrypted and vulnerable for men in the middle attacks.
Due to the mentioned reasons I would not recommend to expose this setting. As a workaround the self signed certificate can be imported to the local certificate store (OS).

I have tested the S3 pathStyle changes but couldn't connect successfully (v2.6.6 on windows). But I can confirm that the path style is probably working because the endpoint was found. I received the following error 'Error. Please check that URL, username, password, etc. are correct and that the sync target is accessible. The reported error was:'.
After looking at the code I found a possible reason. In the following line the regions are fixed to the predefined regions of amazon. I personally use other region definitions, maybe some other cloud providers also have their own region definitions. https://github.com/laurent22/joplin/blob/4ad4fdee499f903bbbbce8862ba8639621b95948/packages/lib/SyncTargetAmazonS3.js#L52

I'm unsure if this is the reason that the connection is not working because of the missing error context. Are there eventually log files that can help to investigate the error? If yes, could you provide a location where I can find them?

**Comment by iFrozenPhoenix** [comment]
You can close it in my opinion.

Mit freundlichen Grüßen / Kind regards
________________________________

**Comment by leematos** [comment]
@iFrozenPhoenix -- Sorrry I missed your earlier reply. That's actually interesting. I can't recall if 2.6.10 has this set or not, but it may have been the source of the problem that someone else was having: https://github.com/laurent22/joplin/issues/5875#issuecomment-1003540234
