### ISSUE TITLE
Getting Network Error when trying to access resources

### ISSUE THREAD

**Issue by filwi** [laurent22/joplin#5628]
For some reason, all the resources I've got (pdfs) show up as links instead of documents. 
On windows, I can see the link. On android, the link is just a download graphic. 
Nothing happens when I press download graphic on android.
On Windows, when I press the link, an error pops up: Network Error, Windows cannot access \\C:\Users...
The path (except for the first two slashes) is correct, and the resources is in the jopin-desktop\resources folder. Even the name is correct.
However, I still can't access it from Joplin itself.

All these were imported from Evernote about a year ago, and did work back then.

## Environment

Joplin version: 
Joplin 2.4.12 (prod, win32)

Client ID: c6cffa88d0c6446bad9107913dfc12d7
Sync Version: 3
Profile Version: 39
Keychain Supported: Yes

Revision: b45585d

Platform:  Windows

OS specifics: Windows 10 Pro / OS build: 19042.1237

## Steps to reproduce

1. 
2. 
3.

**Comment by filwi** [comment]
Problem still exists even after the last updates. Here's what's happening:

Joplin creates this link:

file://C:/Users/filwil/.config/joplin-desktop/resources/b66d0433ca6146b1a4c19ad1760182f2.pdf

Everything is correct, except the // at the beginning, which makes Windows think C: is a mapped network drive, and look for a drive named "C" rather than C:

**Comment by gerroon** [comment]
I have this issue on 2.7.8 Windows 10

**Comment by gerroon** [comment]
This is still broken my dear.

**Comment by gerroon** [comment]
Action,,

**Comment by gerroon** [comment]
shut up bot

**Comment by ScriptInfra** [comment]
Could anyone following this Issue check if they are still receiving the network error? I just attempted to load up a PDF and it loaded without error on v2.8.8 on Windows 11.

**Comment by filwi** [comment]
Solved!

Tried it in 2.8.8 on Win 10 and it worked just fine.
