### ISSUE TITLE
Solution: Fastmail webdav doesn't work?

### ISSUE THREAD

**Issue by valexandersaulys** [laurent22/joplin#563]
I have found that using my webdav on Fastmail results in a 403 Forbidden error. I have everything set up and use the Fastmail password, so I'm surprised to be getting this. Do I need to create a subfolder first?

I have tested this using webdav directly as a network drive on my linux machine with that password so it's not an issue of permissions. 

### Operating system

- Linux

### Application

- Desktop

**Comment by laurent22** [comment]
What's the full error message?

**Comment by jtrh** [comment]
I'm using Joplin's WebDAV sync with FastMail. These settings worked for me:

- **URL**: `https://myfiles.fastmail.com/example_dir/` (create `example_dir` directory before first sync)
- **Username**: `example@fastmail.example.com` (email address used for webmail login)
- **Password**: Generate _app password_ with _files_ permission.

I've tested the above settings on Windows, MacOS, Android, and iOS, so they'll probably work on Linux, too.

Sources:
- [Files - FastMail](https://www.fastmail.com/help/technical/servernamesandports.html#files)
- [WebDAV synchronisation - Joplin](https://github.com/laurent22/joplin/#webdav-synchronisation)
- [Nextcloud synchronisation - Joplin](https://github.com/laurent22/joplin/#nextcloud-synchronisation)

**Comment by borisrorsvort** [comment]
I can confirm on linux 18.4, that using standard webdav [https://www.fastmail.com/help/files/davnftp.html](url) config from fastmail doesn't work but using the config from @jtrh does work perfectly.

**Comment by borisrorsvort** [comment]
The error i was getting was a 403 even though the config said it was good in settings
