### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by goodforever** [laurent22/joplin#5636]
ubuntu 18.04
node -v
v16.13.0
npm -v
8.1.1
joplin v2.4.12

> postinstall
> npm run bootstrap --no-ci && npm run build

> bootstrap
> lerna bootstrap --force-local --no-ci

lerna notice cli v3.22.1
lerna info versioning independent
lerna info Bootstrapping 16 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 217 in 'joplin'
lerna ERR! npm install stderr:
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /home/linux/joplin/packages/app-cli/node_modules/sharp
npm ERR! dest /home/linux/joplin/packages/app-cli/node_modules/.sharp-7gMjeRUU
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/home/linux/joplin/packages/app-cli/node_modules/sharp' -> '/home/linux/joplin/packages/app-cli/node_modules/.sharp-7gMjeRUU'

npm ERR! A complete log of this run can be found in:
npm ERR! /home/linux/.npm/_logs/2021-10-27T09_13_13_470Z-debug.log

lerna ERR! npm install exited 217 in 'joplin'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
npm ERR! code 217
npm ERR! path /home/linux/joplin
npm ERR! command failed
npm ERR! command sh -c npm run bootstrap --no-ci && npm run build

npm ERR! A complete log of this run can be found in:
npm ERR! /home/linux/.npm/_logs/2021-10-27T09_13_13_624Z-debug.log

**Comment by goodforever** [comment]
@laurent22  errors still,after npm run clean

**Comment by kirilgorbachov** [comment]
+1

**Comment by laurent22** [comment]
Yes, +1, but that's never going to work because we don't even use npm anymore
