### ISSUE TITLE
Issue with Android version syncing

### ISSUE THREAD

**Issue by ToddPerkins81** [laurent22/joplin#5639]
## Environment

Joplin version: 2.4.3
Platform: Android
OS specifics: Android 10 - Blu G90 Pro

For the past few days now my mobile version hasn't been syncing.  I sync with Dropbox and my desktop version still works just fine.

**Comment by alcukcoder** [comment]
I had this issue on Android also. I uninstalled the app completely, reinstalled it, etc... and it works fine now

**Comment by Robin-Sch** [comment]
https://github.com/laurent22/joplin/issues/5691



> I had this issue on Android also. I uninstalled the app completely, reinstalled it, etc... and it works fine now
didn't worked for me

**Comment by betsythefc** [comment]
I've reinstalled Joplin on Android as well after encountering this issue and have the same problem.
