### ISSUE TITLE
Clipping anything just with global hotkey from any application

### ISSUE THREAD

**Issue by Twilightssuperb** [laurent22/joplin#5643]
AFAIK, Joplin can clip data only with clipper that installed into browser. But what about gathering text information from other soft (messengers, text editors, PDF viewers etc.)?

E.g., [CintaNotes](http://cintanotes.com/features/) provides me simple hotkey Ctrl+F12, so it's brilliant solution and highly convenient to use. No special clippers. no API, just a hotkey. Select almost everything that could be copied however, press Ctrl+F12 and get new note.

I need the same experience at Joplin.

**Comment by JackGruber** [comment]
The GitHub issue tracker is only for issues, post feature requests in the [forum](https://discourse.joplinapp.org/).
