### ISSUE TITLE
Error on iPad sync - XMLParserError

### ISSUE THREAD

**Issue by mbadros** [laurent22/joplin#5645]
I'm getting an error in syncing Joplin on my iPad to AWS S3. 

The error says: "XMLParserError: Non-whitespace before first tag. \n Line:0 \n Column: 1 \n Char: E" 

## Environment

Joplin version: iPad Joplin 12.4.2
Platform: iOS
OS specifics: iOS 14.8 running on an 8th gen iPad

## Steps to reproduce

1. I deleted Joplin from my iPad, re-installed it, re-entered my AWS S3 sync information and re-synced all of my Joplin notes (~80K synced total items; ~12K notes) from AWS S3 bucket.
2. After completing that sync, Joplin appeared fine and showed no errors. But subsequently (the next sync?), it started to report this sync error. No new notes created on my other Joplin instances (my desktop, for example) appear on the iPad after a sync due to this error.

## Describe what you expected to happen

I expected a clean sync with no errors. I expect new notes created on my other Joplin instances (e.g., on my desktop) to appear on the iPad after syncing.

## Logfile

![Joplin_log](https://user-images.githubusercontent.com/4357482/139511760-208616b8-f734-4ee9-a5ca-d448291bade4.jpeg)

**Comment by roman-r-m** [comment]
Looks like a duplicate of https://github.com/laurent22/joplin/issues/5457
