### ISSUE TITLE
Allow Android backups, again

### ISSUE THREAD

**Issue by billie80** [laurent22/joplin#5649]
I found that after some discussion in this [forum issue](https://discourse.joplinapp.org/t/cant-do-a-clean-re-install-on-android-using-joplin-cloud/18173) backup was disabled again in https://github.com/laurent22/joplin/pull/5114.

I understand that there might be problems in cases like the one mentioned in the forum thread. Still there are other use cases where a backup is useful, as allowBackup not only allows for a google drive backup, it also makes it possible to do a local backup using adb backup or [seedvault](https://github.com/seedvault-app/seedvault/). It is true that backing up the sync target is not important as it is just a copy from the server. However it would be convenient to enable backup and restore of the App settings.

The forum [thread](https://discourse.joplinapp.org/t/cant-do-a-clean-re-install-on-android-using-joplin-cloud/18173/8) mentions that it is not possible to control what is backed up however there is a method to do so. The attribute [fullBackupContent](https://developer.android.com/guide/topics/manifest/application-element#fullBackupContent) in the Manifest file allows fine grained control (including and excluding files) over what is included in the backup and what is not. More information can be found [here](https://developer.android.com/guide/topics/data/autobackup). As a reference the [seedvault FAQ](https://github.com/seedvault-app/seedvault/wiki/FAQ) mentions an App (https://github.com/grote/Transportr/commit/4dc38f429f75909a088d8bd8a5b3b5ddd8030f71) for which this has been implemented. Here they were mainly concerned about the security of the backup as fullBackupContent also enables forcing an encrypted backup but it also shows how to backup only parts of the App storage.

It would be great to add backup support again for the App settings only.

If you think this needs to be discussed in the forum we can do so but I think it should not be necessary.

**Comment by ToddPerkins81** [comment]
I would like a backup option as well on Android.  Currently sync isn't working for me on my phone anymore so it would be nice to have this feature.

**Comment by billie80** [comment]
Would be great if this could be implemented. Looking forward to feedback.

**Comment by JackGruber** [comment]
As it looks at the moment, this is unlikely to happen


>Android Backup is not an issue because it's not enabled, and probably won't.

https://discourse.joplinapp.org/t/is-my-joplin-master-password-being-exposed-to-google/22818/9?u=jackgruber

**Comment by billie80** [comment]
I don't see why the arguments in this discussion should prevent the implementation of a backup method. I do not hope that Joplin is storing the password in plain text even if it is supposed to be in a secure location.
Also it could be stored in a separate file which is excluded from backup.
Additionally as I have written above it is possible to force encryption.
Furthermore it should be possible to allow only local backup and disable cloud backup. This way adb backup and Seedvault could work and no data is stored on someone elses computer.

**Comment by billie80** [comment]
Please leave it open. I think options are there which would satisfy all needs as well as meeting all concerns.

**Comment by billie80** [comment]
Same as above.

**Comment by billie80** [comment]
Bump.
Please anybody who has something to say tell me if there is a chance for this to be implemented or not. I think if properly implemented it should be possible but as I can not code I can only read the documentation and might be wrong.
If it wont be implemented I can live with it perfectly fine. This would also saving me time to keep this ticket alive.

**Comment by Daeraxa** [comment]
In terms of the settings there is a possibility this could be partially resolved by the settings sync GSoC idea (or if not for GSoC it remains on the "wish list" for somebody to implement later if they should want to).

See - https://joplinapp.org/gsoc2022/ideas/#14-client-settings-sync
