### ISSUE TITLE
Error when synching "Your session has expired"

### ISSUE THREAD

**Issue by msartiano** [laurent22/joplin#5650]
Error when synching:

Completed: 31/10/2021 13:25 (0s)
Last error: Error: Your session has expired. Please login again.

I host Joplin Server on Cloudron, recently updated to the latest version: 2.5.7

![image](https://user-images.githubusercontent.com/30049751/139583345-e8cedd89-036c-4f10-a87b-e840cf7eaded.png)

I confirm I have logged in correctly, here's an example:
![image](https://user-images.githubusercontent.com/30049751/139583355-982d1a33-a672-4d19-84af-602ea0023906.png)

## Environment

Joplin version: 2.4.12
Platform: Win 10

## Steps to reproduce

1. Open Joplin
2. Save a note
3. The error shows on the bottom left corner

**Comment by laurent22** [comment]
v2.5 should fix this.
