### ISSUE TITLE
Joplin 2.5.8 (and later) Crashes when Printing

### ISSUE THREAD

**Issue by dfwdraco76** [laurent22/joplin#5651]
This morning I upgraded to 2.5.8.  I tried to print something, and as soon as I clicked the print button on the dialogue, Joplin crashed.  Now when I reopen Joplin, just opening the print dialog triggers a crash.

## Environment
Joplin 2.5.8 (prod, linux)

Client ID: --
Sync Version: 3
Profile Version: 39
Keychain Supported: No
Revision: dbdb82d

Linux Mint 20.2 x86_64

## Steps to reproduce

1.  Go to File, select Print
2. <crash>

## Describe what you expected to happen
Normal print behavior

## Logfile
If anything was displayed in the console, I couldn't see since the application crashes. Trying to attach log.txt but it's saying "is not included in the list"

**Comment by dfwdraco76** [comment]
Here is a link to the log.txt file:  https://mega.nz/file/3bJ0SRbT#BfRuBQtV1vGELq2q56wvF6FZ5vpfbR3T90qoXeocUqY

**Comment by laurent22** [comment]
Well I'm not going to download a 174 MB log. Could you copy and paste the relevant lines here please? (probably the last lines from your log)

**Comment by laurent22** [comment]
Probable upstream bug: https://github.com/electron/electron/issues/31151

**Comment by dfwdraco76** [comment]
Sorry, just followed the instructions.  The log really doesn't show much, I just reproduced it and have this in the log
`2021-10-31 17:23:43: "SearchEngine: Updating FTS table..."
2021-10-31 17:23:43: "SearchEngine: Updated FTS table in 1ms. Inserted: 0. Deleted: 0"
2021-10-31 17:23:43: "CommandService::execute:", "print", "[]"
2021-10-31 17:23:43: "DecryptionWorker: starting decryption..."
2021-10-31 17:23:43: "DecryptionWorker: completed decryption."`

**Comment by laurent22** [comment]
Could try to you start the .AppImage directly from the command line? Then when it creates it might print an error directly in the console

**Comment by dfwdraco76** [comment]
```
dfwdraco76@ncc-1701:~/Applications$ ./Joplin_56d10c0053a5732ac65b421a6685c360.AppImage
qt5ct: using qt5ct plugin
AppImageLauncher error: appimage_shall_not_be_integrated() failed (returned -1)
AppImageLauncher error: appimage_is_terminal_app() failed (returned -1)
xdg-settings: invalid application name
Try 'xdg-settings --help' for more information.
(node:81552) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `@joplinapp-desktop --trace-warnings ...` to show where the warning was created)
(node:81552) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(node:81552) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(node:81552) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(node:81552) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(node:81552) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(node:81552) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(node:81552) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(node:81552) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
Crashing due to FD ownership violation:
#0 0x563799b76f83 <unknown>
#1 0x563799c1dfbc <unknown>
#2 0x563799c1df81 close
#3 0x7f926c87bcdb <unknown>
Sun 31 Oct 2021 05:51:41 PM CDT
```

**Comment by laurent22** [comment]
Yes it's the same bug as the upstream one. It's probably not related to not having any printer, but something else. Pretty much every new Electron version brings new bugs and crashes related to printing unfortunately. In the meantime you can export to PDF and print that file, although it's obviously not as convenient.

**Comment by dfwdraco76** [comment]
I just upgraded to 2.5.10 and the same thing happens when I try to print.  I'd thought about the print to PDF functionality as a workaround too, but the dialog disappears and the app crashes before I can change the printer to "print to file".
Looks like the crash info is the same:
```
Crashing due to FD ownership violation:
#0 0x5561ffd1af83 <unknown>
#1 0x5561ffdc1fbc <unknown>
#2 0x5561ffdc1f81 close
#3 0x7f4c65855cdb <unknown>
```

**Comment by laurent22** [comment]
You get a crash when exporting PDF even with 2.5.10? Could you double-check the version in the About dialog?

**Comment by dfwdraco76** [comment]
```
Joplin 2.5.10 (prod, linux)

Client ID: ---
Sync Version: 3
Profile Version: 39
Keychain Supported: No

Revision: b80242d
```

I click File, then Print, and less than 1 second after the dialog box opens, Joplin crashes.  So I cannot change which physical printer or print to file option.

I see now I can right-click a note and export it to PDF - that's probably what you were referring to.  That works without issue, sorry for the misunderstanding.

**Comment by laurent22** [comment]
Ah ok, at least the pdf export bug is fixed :-) For the print one I'm not sure what can be done unfortunately. It's clearly low priority for the Electron team to get print working properly.

**Comment by philip-n** [comment]
No new information, just a "me too" post unfortunately. Just encountered the bug on Ubuntu 20.04.3 with Joplin AppImage 2.5.1, same output:

> (...)
(node:15470) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
Crashing due to FD ownership violation:
#0 0x55af0a4a9f83 <unknown>
#1 0x55af0a550fbc <unknown>
#2 0x55af0a550f81 close
#3 0x7f87bc9b1cdb <unknown>

**Proposal**
Would it be feasible to simply remove the "print" command from the menu bar for the time being?

Reasons:
* If the print functionality is broken anyways, I currently see no benefit in displaying the command
* An app crash on using "basic" commands from the menu bar IMHO is quite unexpected and does not improve the trust in the app itself (no matter in which component the bug originated)

**Comment by mseliger** [comment]
Same problem here with Ubuntu Mate 21.10 and with Joplin AppImage 2.7.6 and 2.7.12. You can see that the print dialogue is comming up - then everything crashes (print dialogue and Joplin). Export to pdf and other formats works.

**Comment by bertradio** [comment]
Same problem for me with Linux Mint 20.3. And a similar thing happens trying to print markdown from both Typora and MarkText. Seems like it has to do with rendering the markdown for printing.

**Comment by mcmxcdev** [comment]
I cannot reproduce this on Manjaro Linux with Gnome 42.1

I received a `Could not print: no valid printers available` popup which seems to be the expected behavior. Not sure about the behavior with printers connected though.

**Comment by The-Compiler** [comment]
Looks like the behavior perhaps changed slightly, but is not fixed: I can now select a printer and print successfully, but *then* Joplin crashes.

**Comment by taw00** [comment]
Still a problem. Maybe gray-out the print option in Release versions of Joplin on Linux?

**Comment by benbaker76** [comment]
I was successfully printing to pdf until I made a network printer available and then it would crash as soon as I selected File->Print. I can use right-click and Export->PDF menu to get around it.

```
Crashing due to FD ownership violation:
#0 0x562fead2c923 <unknown>
#1 0x562feadd895c <unknown>
#2 0x562feadd8921 <unknown>
#3 0x7f1ba281def3 <unknown>
Killed
```

Joplin 2.9.4 / Ubuntu 22.04.1 LTS

**Comment by philip-n** [comment]
Can confirm that I also have a network printer. Same behavior as described in posts above. Joplin 2.8.8 on Ubuntu 22.04.1 LTS.

---

After clicking File > Print, there is a short pause, then the OS print dialog is visible for a split-second, then Joplin crashes.

```
Crashing due to FD ownership violation:
#0 0x558c05fbcf83 <unknown>
#1 0x558c06063fbc <unknown>
#2 0x558c06063f81 close
#3 0x7efdf5057ef3 <unknown>
```

**Comment by philip-n** [comment]
Can we rename this issue to "Latest Joplin crashes when opening print dialog on Linux" or something similar? Current title is a bit misleading, as it explicitly mentions 2.5.8.

@laurent22

**Comment by bertradio** [comment]
The print issue continues. No idea what it is, but it is not fixed.

Thanks for the followup.

**Comment by dfwdraco76** [comment]
Confirmed it's still crashing for me as well.

**Comment by MSOlsen65** [comment]
Still a problem in :

" Joplin 2.8.8 (prod, linux)

Client ID: fa3bd10cfd7a4c81bec984d45551334c
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: c2a6a13"


Running openSuse Tumbleweed fully updated.  

Program crashes as soon as I click <Print> in the print dialogue.  It does this regardless of printing option chosen (direct printer, network printer of print to file).  

Program will export to PDF, but does not "print" to same when told to "Print to file" through the print dialogue. 

This has been a longstanding problem going back at least to version 1.7.0.  As such, the issue suggests that actual customer/user support is virtually non-existent.  The only answer provided it that the issue lies with a third party. 

Unfortunately, research into the third party shows that the only program having these issues is Joplin.  Given the third party is actively used in over 30 other industrial programs, none of which have this crashing when printing problem, the only reasonable conclusion is that the issues lies within the way Joplin developers have chosen to implement the "Print" functionality.

**Comment by benintech** [comment]
It seems it's an Electron bug, not a a Joplin one. See https://discourse.joplinapp.org/t/print-does-not-work/23802/4 :

> I think the problem is definitely related to Electron since I have it with Typora and MarkText as well. For me the workaround is to export to PDF and print that.

**Comment by bertradio** [comment]
The problem remains.

**Comment by bertradio** [comment]
The problem is still there in 2.10.3

**Comment by devbrones** [comment]
2.9.17 still has the same issue, am on windows

**Comment by jonasvp** [comment]
I can confirm that 2.9.17 has the same issue on Linux. It crashes directly after selecting "Print" from menu.

Output from `dmesg` says:

`traps: @joplinapp-desk[618570] trap int3 ip:558bf1022c25 sp:7ffc87f6c510 error:0 in @joplinapp-desktop[558bede5b000+6c46000]`

**Comment by jonasvp** [comment]
I just noticed that 2.9.17 is out-of-date so I installed 2.10.18: same issue. When printing it outputs this (when starting from command line):

```
Crashing due to FD ownership violation:
#0 0x55b60cdc8573 <unknown>
#1 0x55b60ce738dc <unknown>
#2 0x55b60ce738a1 <unknown>
#3 0x7f5c4b118ef3 <unknown>
```

**Comment by dawaldow** [comment]
2.10.19 ... same issue.  The good news is that the workaround is still working (export to PDF, print from PDF).

**Comment by ernstki** [comment]
Still an issue in 3.1.22 (AppImage on Ubuntu 20.04-based Linux), although [this comment](https://github.com/electron/electron/issues/31151#issuecomment-2205922710) in the upstream bug gave me a workaround: disable wifi.

It looks like Electron crashes when trying enumerate network printers. I mean, I'm sure it crashes lots of other times, but in _this_ particular case, in my particular circumstances, that appears to be the cause of the crash.

**Update**: In fact, having the printer dialog box even _open_ then re-connecting the network causes Joplin (or rather Electron) to crash. Inconvenient if your printer _is_ a network printer, but like everyone's mentioned, at least we have the PDF export workaround still.

**Comment by dpoulton-github** [comment]
> Still an issue in 3.1.22 (AppImage on Ubuntu 20.04-based Linux)...

This has not been a problem for me for some time with either of my Linux machines. I am not having any issue with 3.1.22 printing, however I am using the AppImage on an Ubuntu **24.04**-based Linux as well as a Debian 12.7-based Linux.

**Comment by bertradio** [comment]
Was a problem with many past builds. But prints with no problem now:

Linux Mint 22
Joplin 3.1.22

**Comment by ernstki** [comment]
> > Still an issue in 3.1.22 (AppImage on Ubuntu 20.04-based Linux)...
> 
> This has not been a problem for me for some time with either of my Linux machines. I am not having any issue with 3.1.22 printing, however I am using the AppImage on an Ubuntu **24.04**-based Linux as well as a Debian 12.7-based Linux.

Could very well be an old issue with Ubuntu 20.04 and derivatives then. This OS loses support in April next year, I believe, so maybe it's a moot point.

**Comment by taw00** [comment]
> Could very well be an old issue with Ubuntu 20.04 and derivatives then. This OS loses support in April next year, I believe, so maybe it's a moot point.

It was an issue with Joplin on Fedora as well. But, it now seems to be resolved. I am just posting this note so that if it reappears there is at least a comment that it is not exclusive to Debian/Ubuntu/etc.

**Comment by ernstki** [comment]
@laurent22 Upstream appears to have closed this bug: https://github.com/electron/electron/pull/46587

I'm not familiar with how Electron's versioning works, or offhand which version Joplin builds upon, but the activity on that PR makes it look like the fix will also be backported to several older release series.
