### ISSUE TITLE
Horizontal scrolling disabled in markdown viewer - 2.5.8 macOS 11.6.1

### ISSUE THREAD

**Issue by annoyedhumanoid** [laurent22/joplin#5652]
## Environment

Joplin version: 2.5.4, 2.5.8. 2.5.10
Platform: macOS
OS specifics: macOS 11.6.1

i tested prior versions and it seems 2.4.12 was the last release in which horizontal scrolling worked in the markdown viewer.

## Steps to reproduce

when a note contains an element that causes horizontal overflow (e.g. a large table, a pre-formatted line, etc.), horizontal scrolling via mouse/trackpad doesn't work in the markdown viewer window. horizontal scrollbar at the bottom still works.

1. in a new note, paste the following in the markdown editor: `<pre>mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm</pre>` (actual text is irrelevant, just a way to produce horizontal overflow)
2. in the _viewer_ window (either split screen with markdown editor or soloed, as long as there is still horizontal overflow), attempt to scroll horizontally via mouse/trackpad (e.g. two-finger horizontal swipe). viewer does not scroll.
3. click and drag horizontal scrollbar at the bottom. viewer successfully scrolls.

## Describe what you expected to happen

in a note with horizontal overflow, the viewer window should scroll horizontally when a user performs the appropriate mouse/trackpad horizontal scroll gesture.

## Logfile

Devtools console:
- 1 warning: DevTools failed to load source map: Could not parse content for file:///Applications/Joplin.app/Contents/Resources/app.asar/gui/note-viewer/pluginAssets/mermaid/mermaid.min.js.map: Unexpected end of JSON input
- 1 possible improvement: Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform

https://user-images.githubusercontent.com/46287328/139596743-1fbabca6-0e37-4796-acf8-79bbc20121ab.mov

**Comment by ken1kob** [comment]
> * in the _viewer_ window (either split screen with markdown editor or soloed, as long as there is still horizontal overflow), attempt to scroll horizontally via mouse/trackpad (e.g. two-finger horizontal swipe). viewer does not scroll.

Do you mean "mouse" is mouse-wheel?

**Comment by annoyedhumanoid** [comment]
> > * in the _viewer_ window (either split screen with markdown editor or soloed, as long as there is still horizontal overflow), attempt to scroll horizontally via mouse/trackpad (e.g. two-finger horizontal swipe). viewer does not scroll.
> 
> Do you mean "mouse" is mouse-wheel?

whatever the mouse’s function for horizontal scrolling is, like on mine you push the scroll wheel to the left or right.

**Comment by ken1kob** [comment]
Thanks for your answer.

I investigated behaviours of horizontal scrolling on Windows10:

|Joplin ver|Markdown Viewer (Wheel)|Markdown Viewer (Drag)|Markdown Viewer (Push Wheel & Move)|WYSIWYG Editor (Wheel)|WYSIWYG Editor (Drag)|WYSIWYG EDitor (Push Wheel & Move)|
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
|2.4.9|NG*|OK|OK|NG*|OK|OK|
|2.5.10|NG|OK|OK|NG*|OK|OK|

\* The first horizontal scroll works after the app start. The second and others don't work.

This is a problematic result, but it seems to be different from the report on Mac. Whenever a horizontal wheel event after the first happens,  `deltaX` property of `WheelEvent` is 0, and the horizontal scroll bar doesn't move.

@annoyedhumanoid, do you know which versions horizontal scroll work and doesn't work on macOS?
