### ISSUE TITLE
When exporting a note to markdown, everything in the title after 51 characters is cut off in the title of the note

### ISSUE THREAD

**Issue by supotnitskiy** [laurent22/joplin#5653]
When I exported to markdown, I noticed that if the length of the article name is more than 51 characters, then everything that is longer than this is cut off and not saved. The same happens with links to images. If the article contains more than 51 characters, everything beyond 51 characters in the file name is cut off. And all this leads to distortion of links.

Here is an example of a link that looks like

! [index_files / f6cabbe2-0b1f-436d-917c-a2895636b562.jpg] (../_ resources / index_files_f6cabbe2-0b1f-436d-917c-a2895636b562.j)

It can be seen that the expansion has been cut off. 

## Environment

Joplin version: v2.5 
Platform: Linux, Windows

## Steps to reproduce

All playable with normal markdown export

**Comment by Rishabhraghwendra18** [comment]
Hi, I am working on this issue . This issue still persists on v2.6.0

**Comment by Rishabhraghwendra18** [comment]
I think it's not a bug . It's set to 50 because windows supports path up to 255 characters and also there is no logic to for lengthy file names , so for safety purposes it set to 50 , as said in the comment of this [function](https://github.com/laurent22/joplin/blob/0cec4753d8afaa5673eba526c121d8b1e1062a5d/packages/lib/path-utils.ts#L76)
https://github.com/laurent22/joplin/blob/0cec4753d8afaa5673eba526c121d8b1e1062a5d/packages/lib/path-utils.ts#L77

**Comment by supotnitskiy** [comment]
In Linux, there are no restrictions on the file length, but when exporting from joplin, they still work.

May remove this limit of 50 characters as it complicates the export of markdowns and does not make much sense.
If someone in Windows has notes with a length of 240 characters, no one will bother to create a folder for exporting the type c:\1

**Comment by Rishabhraghwendra18** [comment]
type c:\1 ??

**Comment by supotnitskiy** [comment]
I meant the place of export to Windows disk  С: with the name 1

**Comment by supotnitskiy** [comment]
Thank you, images started exporting without truncated names.
But is it still possible to increase the length of the title to at least 100 characters

**Comment by Rishabhraghwendra18** [comment]
@laurent22 I was working on the issue

**Comment by supotnitskiy** [comment]
Will they increase the length of the file name? I believe that the problem is not closed and I do not understand what the problem is to fix the variable

**Comment by Daeraxa** [comment]
Have you tried the new pre-release that features the commit that closed the issue?

**Comment by supotnitskiy** [comment]
> Have you tried the new pre-release that features the commit that closed the issue?

This issue is partially closed, when exporting, markdown file names are still less than 51 characters 

As I understand it, you need to correct the variable here 
https://github.com/laurent22/joplin/blob/0cec4753d8afaa5673eba526c121d8b1e1062a5d/packages/lib/path-utils.ts#L77

**Comment by pmottishaw** [comment]
This bug still exists on windows with v2.6.

**Comment by laurent22** [comment]
This is working as expected since we have to limit the number of characters in the file path. We have tried many different limits and 50 is a good compromise.

The actual bug here was that the file extension was cut when it shouldn't, but this has been fixed.

**Comment by pmottishaw** [comment]
Thank you for the prompt response. I have found that the 50 character limit
is a real limitation on using the exported markdown files with other
apps, especially when exporting a lot of notes. Would it be possible to
enhance this by making it configurable?

**Comment by ferrouswheel** [comment]
the file extension being dropped is still a problem in 2.13.8
