### ISSUE TITLE
To do pages changing left right arrow keys are not working properly.

### ISSUE THREAD

**Issue by Devik225** [laurent22/joplin#5654]
At last to do the forward one not getting disabled and in between sometimes one is working and one is dead.
Those forward and backward both are functioning faulty.
![Screenshot (993)_LI](https://user-images.githubusercontent.com/67371806/139626868-ac952956-621b-4f3f-930f-2789b0a5e030.jpg)

**Comment by laurent22** [comment]
I don't know what you mean

**Comment by Devik225** [comment]
Those arrow keys to change the page. "Forward" and "Backward" button highlighted in red color are not working properly.

**Comment by Devik225** [comment]
https://user-images.githubusercontent.com/67371806/139678237-39b1f467-e183-4329-97d1-d60e4fe3ec8c.mp4

**Comment by kkoyung** [comment]
The "forward" and "backward" buttons follow the order the notes that you recently visited, just like the "forward" and "backward" buttons in web browsers. They work properly in my computer.
Can you describe the detailed process of reproducing the issue?
