### ISSUE TITLE
 "Error: Master key is not loaded" is displayed and cannot be synchronized. 2

### ISSUE THREAD

**Issue by sculpordwarfpiewolf** [laurent22/joplin#5655]
## Environment

Joplin version: 2.5.5
Platform: Android
OS specifics: Android 12

## Steps to reproduce

1. Set Synchronization target to Nextcloud and login.
2. Tap on Synchronize.
3. The message "Error: Master key is not loaded" is displayed.

## Describe what you expected to happen
No error message is displayed and the notes of the sync target are downloaded.

This problem is the same as #5585. The same problem occurs when Nextcloud is replaced with Webdav.

## Logfile
[Nextcloud](https://github.com/laurent22/joplin/files/7450936/syncReport-1635745181234.txt)

**Comment by laurent22** [comment]
Could you provide a screenshot of the encryption screen with the latest version of the app?

**Comment by sculpordwarfpiewolf** [comment]
It was a problem specific to my environment. I'm very sorry.

**Comment by laurent22** [comment]
No problem, but would you mind sharing what the issue was? In case it happens to someone else.

**Comment by CatbusDriver** [comment]
NGL I had the same Problem and the Solution was Stupid: 

I don't have my Notes Encrypted, Joplin just seem to try anyways and prints the following:

```
: "Sync has finished and note has never been changed - reloading it"
: "Trying to reload note that has been deleted:", "null"
: "DecryptionWorker: cannot start because no master key is currently loaded."
```

Anyways nothing helped, because nothing was broken.
My solution was just to press F10 and F11 to bring back the UI.

Hope that helps other People who also are new to Joplin.
