### ISSUE TITLE
All content in Rich Text is indented with Version 2.5.10

### ISSUE THREAD

**Issue by narcoma** [laurent22/joplin#5657]
Since either the 2.5.8 or 2.5.10 update all content (text, tables, etc.) is indented in the middle of the content screen. This might be a new feature to display text in the middle of the screen, but in the case of larger tables (weekday tables with 7 colums for example), it just shifts everything to the right and cuts of the last columns.

**Comment by laurent22** [comment]
Isn't it this issue? https://discourse.joplinapp.org/t/please-read-this-if-you-are-wondering-why-theres-now-a-margin-on-the-note-text/19585

**Comment by narcoma** [comment]
Yes, missed that. Thanks.
