### ISSUE TITLE
Offline build broken  

### ISSUE THREAD

**Issue by catsout** [laurent22/joplin#5658]
https://github.com/npm/cli/blob/2c6421576e8d4bb80718993047fad95c198cfb35/node_modules/%40npmcli/arborist/lib/arborist/reify.js#L629
> // in normal cases, node.resolved should *always* be set by now.
// however, it is possible when a lockfile is damaged, or very old,
// or in some other race condition bugs in npm v6, that a previously
// bundled dependency will have just a version, but no resolved value,
// and no 'bundled: true' setting.
// Do the best with what we have, or else remove it from the tree
 // entirely, since we can't possibly reify it.

node.**resolved** should always be set by now  

But how does this package-lock.json file get **no resolved** filed in most nodes?  
https://github.com/laurent22/joplin/blob/c49174124ea741a3ef9f3d188895a10df54de181/packages/app-cli/package-lock.json#L10577-L10583

It seems making the offline build broken

**Comment by laurent22** [comment]
Many of these lock files are quite old, so probably they should be rebuilt (although that could create dependency issues). However the app builds fine on GitHub Actions for example, so what's not working for you?

**Comment by catsout** [comment]
In my test, npm(not in flatpak) works fine without "resolved" filed  
Seems that there are some issue in generating npm cache for npm v8, and it can be solved in our side.  
I will reopen this, if I think this can't solved in our side.

**Comment by catsout** [comment]
solved.
