### ISSUE TITLE
Joplin will not boot due to SQLITE_CORRUPT error

### ISSUE THREAD

**Issue by JeremyCavanagh** [laurent22/joplin#5659]
Hi,
This is not what I would describe as a reproducible bug, more of a massive Balls-Up on my part. I am tryiing to update my old mac to an "incompatible" version of the OS. I've done it before with no problems. However, during the process of checking things out I started Joplin (which I think was 2.4.9) and got an update message so as usual I clicked. Update seemed to go fine and while I was doing some web clipping, my system completely locked up.

Now I am not blaming Joplin I really think it's one of the best note-taking apps around. I have been using Evernote for a fews years and apart from one little diffference between them, which to be honest I can work around, I am working towards dumping Evernote and relying totally on Joplin (still got quite a few months on my current subs for Evernote).

Well, the only way to unlock system was to restart it in the worst way possible (hold down the power button). Upon reboot Joplin will not start at all and I get a rather cryptic and unhelpful message:

Error: SQLITE_CORRUPT: database disk image is malformed: CREATE TABLE folders (id TEXT PRIMARY KEY, title TEXT NOT NULL DEFAULT "", created_time INT NOT NULL, updated_time INT NOT NULL);

Error: Error: SQLITE_CORRUPT: database disk image is malformed: CREATE TABLE folders (id TEXT PRIMARY KEY, title TEXT NOT NULL DEFAULT "", created_time INT NOT NULL, updated_time INT NOT NULL);
    at DatabaseDriverNode.sqliteErrorToJsError (/Users/jeremycavanagh/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database-driver-node.js:23:18)
    at JoplinDatabase.sqliteErrorToJsError (/Users/jeremycavanagh/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:34:30)
    at JoplinDatabase.<anonymous> (/Users/jeremycavanagh/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:133:36)
    at Generator.throw (<anonymous>)
    at rejected (/Users/jeremycavanagh/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

I have tried running diskutil and ran firstaid. Result no disk problems. I've tried removing and reinstalling with no change.
Any assistance would be much appreciated.

Regards

Jeremy Cavanagh

## Environment

Joplin version: 2.5.8
Platform: macOS
OS specifics: 10.15.7

**Comment by roman-r-m** [comment]
The database should be in your use home under `.config/joplin-desktop`. Delete it (or at least move elsewhere if you think there's still useful data in there) and try again.

**Comment by laurent22** [comment]
If you have important data in there, maybe there are some SQLite recovery tools. Although for sure some data has been lost and even if you recover it, it shouldn't be used with Joplin.
