### ISSUE TITLE
Android version 2.4.3 code box area display exception

### ISSUE THREAD

**Issue by huaqic** [laurent22/joplin#5661]
Hello, we provide you with the problems encountered in Android version 2.4.3: as shown in the figure, the code box area displays exceptions on the Android side, exceeding the width limit. 
![mmexport1635785477366](https://user-images.githubusercontent.com/40896822/139711323-0abe8726-0c08-4738-b974-cde07ea0d79e.jpg)

**Comment by laurent22** [comment]
Please copy and paste the Markdown content here.

**Comment by huaqic** [comment]
@laurent22 

hello,

markdwn code：

```shell
chroot /sysroot/      # 用chroot命令把根目录切换到我们原来的环境中，也可以理解为以ROOT权限登录原来的系统。
passwd                # 修改密码命令
1                     # 设置新的密码
1                     # 确认新的密码			
touch /.autorelabel   # 重置密码生效
exit                  # 退出紧急模式
reboot                # 重启机器设备
```

When there is too much text in a line, the width of the code box will overflow, and the width will be increased infinitely on the right to display the entire line of text.

**Comment by huaqic** [comment]
@laurent22 
I just found the latest 2.6.3.apk update package on the official website. I quickly checked issue: 5661 and found that the status has changed. With excitement, I downloaded the latest software package. After testing, the above problems have been solved. Thank the official technicians for their efforts to repair the problems, thank you!!!

**Comment by huaqic** [comment]
@laurent22 
Hello, I don't have foreign currency payment channels here. Is there an official "RMB sponsorship channel"?

**Comment by huaqic** [comment]
@Daeraxa This issue has been resolved and now appears normal。

**Comment by huaqic** [comment]
@Daeraxa My English is not good, and the translation of the translation software does not quite understand what you mean. This problem has been solved and it is normal.Been looking at this issue not being turned off and just found out I can turn it off myself.
