### ISSUE TITLE
Windows Desktop .CodeMirror-sizer's style is incorrect ... maybe

### ISSUE THREAD

**Issue by uzarnom** [laurent22/joplin#5664]
Issue:
==================
The contents pane in markdown does not seem to use the entire space available to it

The Fix (CSS)
======================
To fix:
in the  ".CodeMirror-sizer" class style
change "max-width: 600px !important"
to "max-width: 100% !important"

Device
==============
On windows 10 
Joplin 2.5.10 (prod, win32)

Client ID: 4910fb8830334c26bf14ec5b8365589f
Sync Version: 3
Profile Version: 39
Keychain Supported: Yes

Revision: b80242d

**Comment by uzarnom** [comment]
I seem to have messed up creating the ticket, I'll try again after court today

**Comment by CalebJohn** [comment]
Thanks for the report, please take a look at [this post from the forum](https://discourse.joplinapp.org/t/please-read-this-if-you-are-wondering-why-theres-now-a-margin-on-the-note-text/19585) to understand context for that setting.

**Comment by uzarnom** [comment]
Thanks for that, sorry for the wasted report

**Comment by CalebJohn** [comment]
No worries, I appreciate that you made an effort in reporting.
