### ISSUE TITLE
Cannot drag note from "All notes" to a notebook

### ISSUE THREAD

**Issue by hp6393** [laurent22/joplin#5667]
1. If I have a note in an existing notebook (e.g., a notebook named "Unprocessed").
2. I click on All notes in the NOTEBOOKS tree on the left
3. I select the note in the list (the note on the right clearly says "In: Unprocessed")
4. I click and drag the note to the "My Work Notes" notebook
5. A plus sign appears by the cursor and I drop the note onto "My Work Notes" in the NOTEBOOKS tree
6. Nothing happens. The note remains in the original folder and is not moved.

FYI, if I start in the "Unprocessed" notebook instead of "All notes," it works correctly. I can drag and drop the note from "Unprocessed" into "My Work Notes."

Joplin for Desktop 2.5.10 (prod, win32)
Windows 10 (64-bit)

**Comment by tessus** [comment]
`All notes` is a view. Please use the forum for your usability questions.

**Comment by hp6393** [comment]
I see. This was not the behavior in earlier versions so I thought it was a
bug. Sorry for posting in the wrong area.

**Comment by tessus** [comment]
In fact, the note is actually moved to a different notebook, but the `In:<notebook>` label is not updated unless you switch notes. However, the note will never be moved out of the `All notes` view, because it is not a folder, but a virtual area that shows all notes no matter in which notebook.
