### ISSUE TITLE
Cannot Open URLs

### ISSUE THREAD

**Issue by hp6393** [laurent22/joplin#5668]
In the Note Viewer, if I click or double-click on a link in a note, nothing happens. If I right-click and choose Open from the context menu, links to local files open, but URLs do not.

Here is an example of a link from the Note Editor:

`[Apple](:/890e83f71b76428badc15b824ab42502) (https://designingoutcomes.com/assets/PadWheelV5/PW_ENG_V5.0_Apple_iOS_PRINT.pdf)`

In the Note Viewer, the "Apple" link will open if I right-click, but the designingoutcomes.com link will not. Neither link will open by clicking or double-clicking on the link.

Joplin for Desktop 2.5.10 (prod, win32)
Windows 10 (64-bit)

**Comment by tessus** [comment]
`(https://designingoutcomes.com/assets/PadWheelV5/PW_ENG_V5.0_Apple_iOS_PRINT.pdf)` is not valid markdown.

**Comment by hp6393** [comment]
Helmut,

I did a little more experimentation. The link without brackets is what is
created when typing URLs directly into the Viewer. So *bug #1 is that while
the Viewer creates what appears to be a clickable link, it omits the square
brackets required for a valid Markdown link.*

If I fix the link so that it is valid Markdown:

[
https://designingoutcomes.com/assets/PadWheelV5/PW_ENG_V5.0_Apple_iOS_PRINT.pdf
](
https://designingoutcomes.com/assets/PadWheelV5/PW_ENG_V5.0_Apple_iOS_PRINT.pdf
)

**If the Editor is closed* and only the Viewer window is open, the URL will
still not work*. The cursor does not even change when hovering over the
link. Also right-clicking and choosing Open does not work.

**If the Editor and Viewer windows are both open* then the link in the
Viewer pane works* and behaves as it should. Given this, I think the real
problem is that links in the Viewer pane do not behave properly if the
Editor pane is closed.

**Comment by tessus** [comment]
Ok, I'm very confused. Maybe we should start which editor you are using. The markdown editor has 3 options: split view (editor and viewer), editor, viewer. The WYSIWYG editor has only one panel, which is the editor and the viewer at the same time.

Also, there's an option called `linkify`. Either way, a valid markdown link is `<https://google.com>`

Furthermore the WYSIWYG behaves differently when it comes to links than the markdown editor/viewer.

And.....

....this is something that should be discussed on the forum.  (There have been a few topic about this already.)

**Comment by hp6393** [comment]
Yes, the links work when in split view, but not in viewer only. I'll move this over to the forum.

**Comment by tessus** [comment]
Once again, it works in the viewer only mode as well. At least it works for me. I believe you mean the WYSIWYG editor, because you mix up the editors.

**Comment by tomasz1986** [comment]
> I believe you mean the WYSIWYG editor, because you mix up the editors.

For the record, in the WYSIWYG editor with Linkify enabled, those plain text URLs do appear as links, but they are not clickable, and right-click -> open does nothing too.
