### ISSUE TITLE
Apple ios settings hope to increase support for ios icloud synchronization, this will be a very convenient thing, many software are using ios icloud synchronization

### ISSUE THREAD

**Issue by burtton99** [laurent22/joplin#5674]
苹果ios设置希望可以增加支持ios icloud同步，这将是很方便的一件事，很多软件都在使用ios icloud同步
Apple ios settings hope to increase support for ios icloud synchronization, this will be a very convenient thing, many software are using ios icloud synchronization

**Comment by dpoulton-github** [comment]
This has been discussed on the forum.

https://discourse.joplinapp.org/t/what-about-icloud-sync/452/6

A main point raised was:

> One of the core issues with iCloud (and it’s one of being in opposition to the core design philosophy of Joplin) is that it is limited to only Apple platforms. There’s almost no real way that I know of to access iCloud content directly on Windows or Linux.

and the view of the person who created Joplin was:

> Yes I don’t see iCloud support ever happen unfortunately...
