### ISSUE TITLE
Web clipper can't change notebook

### ISSUE THREAD

**Issue by xijiang** [laurent22/joplin#5675]
No response when click the "in notebook" input bar to change notebook to store the webpage. 

The available notebook to clip in was a notebook that I moved before to another place.

I am running Fedora 34/35 + Firefox.

Remove and reinstall the add-on didn't solve the problem.

**Comment by Daeraxa** [comment]
What version of web clipper and what version of firefox?
I don't have this problem on clipper 2.1.3 and ff 92.0.1 on linux mint 20.2. 
Does the clipper still post the data to joplin if you select whatever notebook is still in the bar (if any)?
Have you tried disabling and re-enabling the clipper service?

**Comment by xijiang** [comment]
Clipper 2.1.3, Firefox 94. But this problem hanged on my desktop for quite a few months.

**Comment by Daeraxa** [comment]
Definitely something not right there. The right side isn't displaying correctly:
![image](https://user-images.githubusercontent.com/58074586/140332001-da7ec74a-d2a1-4844-be77-47b8424762ab.png)
Firefox does allow you to inspect the add-ons, something might show up in that?
about:debugging#/runtime/this-firefox > Inspect

**Comment by xijiang** [comment]
I am quite a layman. but does below give any clue
![Screenshot from 2021-11-04 18-47-19](https://user-images.githubusercontent.com/1819383/140392391-e6619b1c-7992-4e75-b658-0a43c9a077d2.png)
?

**Comment by xijiang** [comment]
If I enable it in a private mode (fedora+firefox), then the notebook notebook is changed also in normal mode. But still, not be able to change notebook in normal mode.
