### ISSUE TITLE
Joplin crashes on iOS

### ISSUE THREAD

**Issue by ajay-gh** [laurent22/joplin#5676]
After update on Apple's app store today, Joplin crashes immediately after open. 

Joplin version: 12.5.1
Platform: iOS Mini
OS specifics: iOS 12.5.5 (last available update for this iPad)

## Steps to reproduce

1. just update from Appstore and open
2. otherwise may require same iPad, same iOS version ???

## Describe what you expected to happen

Joplin to start as always / as before update

## Logfile

unaccessable

**Comment by laurent22** [comment]
See here https://github.com/laurent22/joplin/issues/5671

**Comment by ajay-gh** [comment]
Problem solved, thank you so much !!!
