### ISSUE TITLE
Cannot download -- virus detected

### ISSUE THREAD

**Issue by thdoan** [laurent22/joplin#5678]
I'm not able to download Joplin because of "virus detected" error:

![image](https://user-images.githubusercontent.com/4110567/140474819-59e4df9e-23b0-4126-82e9-6a6f8ea9d76e.png)

Windows threat report:

![image](https://user-images.githubusercontent.com/4110567/140476437-02024f3d-d64e-4deb-9d42-a42b3e1692e3.png)

## Environment

Joplin version: 2.5.10
Platform: Windows
OS specifics: 
Edition	Windows 10 Home
Version	21H1
OS build	19043.1288
Experience	Windows Feature Experience Pack 120.2212.3920.0

## Steps to reproduce

1. Go to https://joplinapp.org/help/#installation
2. Click to download Joplin-Setup-2.5.10.exe or JoplinPortable.exe in Chrome 95.0.4638.69 (Official Build) (64-bit)

## Describe what you expected to happen

Files should download.

**Comment by wow-yes** [comment]
Same error. Comfirm.

**Comment by bartolialberto** [comment]
Confirm.

Windows 10 Professional 10.0.19043 Build 19043

**Comment by laurent22** [comment]
Which anti-virus?

**Comment by Daeraxa** [comment]
> Which anti-virus?

I think people aren't even getting that far, the download from Chrome is failing so at that point I doubt most people know how to force it to download claiming it is a virus.

I downloaded it via Firefox and now Windows defender is freaking out:
![image](https://user-images.githubusercontent.com/58074586/140489214-22e24e8e-bd14-4ce9-9bb4-78affd45c46e.png)

**Comment by JackGruber** [comment]
Witch WIndows Defender signature update do you use?
I have no problems with the following versions:

Output from `Get-MpComputerStatus`powershell command.

```
AMEngineVersion                 : 1.1.18700.4
AMProductVersion                : 4.18.2110.6
AMServiceVersion                : 4.18.2110.6
AntispywareSignatureLastUpdated : 05.11.2021 03:20:28
AntispywareSignatureVersion     : 1.353.458.0
AntivirusSignatureLastUpdated   : 05.11.2021 03:20:29
AntivirusSignatureVersion       : 1.353.458.0
NISEngineVersion                : 1.1.18700.4
NISSignatureLastUpdated         : 05.11.2021 03:20:29
NISSignatureVersion             : 1.353.458.0
```

**Comment by tomasz1986** [comment]
> Windows defender is freaking out:

I wonder if it's got anything to do with Defender's "cloud-delivered protection". I've got it disabled on my syste, and there are no complaints here.

**Comment by Daeraxa** [comment]
Probably easiest if we stick to one method as the same conversation is in both github and discourse (https://discourse.joplinapp.org/t/joplin-setup-2-5-10-exe-might-have-a-virus/21518/)

**Comment by laurent22** [comment]
Yes let's close this issue and move to the forum.

https://discourse.joplinapp.org/t/joplin-setup-2-5-10-exe-might-have-a-virus/21518/12
