### ISSUE TITLE
Markdown preview do not show when plugin is installed

### ISSUE THREAD

**Issue by booora26** [laurent22/joplin#5685]
When a plugins related to Markdown are installed Markdown preview in not rendering content (when plugin is disabled or deleted rendering is working).

This case bellow is with Better Markdown Viewer plugin enabled, but this is happening with some other plugins that are related with markdown rendering.

<img width="1149" alt="Screenshot 2021-11-06 at 19 52 30" src="https://user-images.githubusercontent.com/25347153/140620751-eec51a5f-c7fd-4c48-9137-342b34ed3c3d.png">

In dev console this error is showing

<img width="679" alt="Screenshot 2021-11-06 at 19 59 52" src="https://user-images.githubusercontent.com/25347153/140620894-cb6c5258-2d71-4b7d-898b-e817c115514e.png">
## Environment

Joplin version: 2.5.10 (prod, darwin)
Platform: macOS
OS specifics: Big Sure

## Steps to reproduce

1.  Install Better Markdown Viewer
2. 
3. 

## Describe what you expected to happen

To render markdown preview

**Comment by laurent22** [comment]
You should contact the plugin author because the issue is that the plugin content script ID should be globally unique. "contentScriptMarkdownIt" is copied from the demo - but it should be changed.

**Comment by Rishabhraghwendra18** [comment]
Hi , is this issue open ?

**Comment by booora26** [comment]
I have opened this issue on plugins repository, so I will close it here.

thanks.

**Comment by Rishabhraghwendra18** [comment]
@booora26 ok..no problem
