### ISSUE TITLE
Tags order

### ISSUE THREAD

**Issue by dot-clear** [laurent22/joplin#5686]
The tag order between left panel and windows tag is different.

![tag order, PNG](https://user-images.githubusercontent.com/77929203/140651585-dea7a682-e351-4954-9121-0550bcc93801.jpg)

## Environment
Joplin version: 2.5.10
Platform: Windows 
OS specifics: Win10

## Steps to reproduce
1. Create tags with emoji, #, @, ...
2. Open tags windows, and check tags order in the drop-down menu

## Describe what you expected to happen
I expect the same order in the drop-down menu than the tag panel.

**Comment by dot-clear** [comment]
> it still require the community's attention?

Yes

**Comment by OmGole** [comment]
Can I work on this?

**Comment by dot-clear** [comment]
Yes anyone could work on this.

**Comment by dot-clear** [comment]
Thanks @OmGole !

**Comment by ghost** [comment]
I tried the new version today 2.7.15.
IMO, it would have been preferable to maintain the order of the left panel. Because the order has already been chosen by the user there. While on the drop-down panel the user does not have the option to order.
