### ISSUE TITLE
Caret is invisible when text is selected.

### ISSUE THREAD

**Issue by serenesensei** [laurent22/joplin#5689]
## Environment

Joplin version: Joplin 2.5.10 (prod, win32)
Platform: Windows
OS specifics: Windows 11 21H2 (OS Build 22000.282)

## Steps to reproduce

1. Select some text.
2. Caret is completely invisible on all themes. 

## Describe what you expected to happen

**Expected:** Caret should be visible/blinking.

This mainly creates problem when selecting text over multiple lines.

**Comment by CalebJohn** [comment]
I just had a look and it looks like this can be enabled by adding the showCursorWhenSelecting option to the editor. It's off by default, so I guess that's how many people like it? 

This kind of request is best to make on the forum of you don't mind. It's a preference that is really a matter of opinion, although i think you're right about the multi-line select,

**Comment by serenesensei** [comment]
I have opened a [thread](https://discourse.joplinapp.org/t/show-caret-when-selecting-text-by-default/21626) at the Joplin forum.

Thanks for your time, let's close this one.
