### ISSUE TITLE
How to make the code in the code block wrap automatically

### ISSUE THREAD

**Issue by toppemonkey** [laurent22/joplin#5692]
![image](https://user-images.githubusercontent.com/43023098/140877675-8c50e2a6-05c2-4e67-b4ce-8d9b3c5361b9.png)
When I did not manually wrap the code of the code block when I was writing it, it would not automatically wrap in the preview mode, and it exceeded the code block area, how can I make the code wrap automatically when previewing?

**Comment by hpkaiq** [comment]
I`m puzzled by the same problem.

**Comment by tomasz1986** [comment]
You need to add `code { white-space: pre-wrap !important; }` to `userstyle.css`.

Why is it even set to `pre` though? For context, all code editors I have ever used always wrapped lines by default. Otherwise you're forced to scroll horizontally, which usually results in horrible user experience.

**Comment by nluciano233** [comment]
I'm having the same issue
