### ISSUE TITLE
Opening a file with ctrl and click leads to an error in the Rich Text editor

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#5693]
Ctrl + Click on a file link lead to an error in the `Rich Text editor`  because a UNC path is prepended to the file path. 
![grafik](https://user-images.githubusercontent.com/24863925/140947835-5ad109c0-7c0f-4738-8cd7-f1570ee0be70.png)

Opening the file via context menu `Open ...` works fine. 

## Environment

Joplin 2.5.6 (dev, win32)

Client ID: 0a26e311ccea4bd5903ab8e3fd82597f
Sync Version: 3
Profile Version: 39
Keychain Supported: Yes

Revision: 7d70dea

## Steps to reproduce

1.  `Ctrl` + Click on a file in the `Rich Text editor`

## Describe what you expected to happen

Open the file

**Comment by laurent22** [comment]
Unfortunately I can't build the app on Windows at the moment so I can't even fix this.

**Comment by ajsteele** [comment]
I am also experiencing this bug. I recently upgraded from using OneDrive as a sync client to a paid Joplin Cloud account, and I’m unsure if the onset of this issue coincided with this change.

## Environment

Joplin version: Joplin 2.6.10 (prod, win32)
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 98fba37

Platform: Windows
OS specifics: 10

## Steps to reproduce

See above.

**Comment by laurent22** [comment]
You might want to open a new issue with detailed information on how to replicate the bug, because the issue described here is fixed.

**Comment by ajsteele** [comment]
Thanks for the rapid reply! Very happy to, but the issue I am experiencing manifests identically to what is described above so I thought it was better to comment on this issue rather than starting a new one. :)
