### ISSUE TITLE
Cannot open any attachment in Joplin android app

### ISSUE THREAD

**Issue by monnypython** [laurent22/joplin#5699]
## Environment

Joplin version: 2.6.1
Platform: android
OS specifics: GrapheneOS, (android 11)

## Steps to reproduce

1. create New Note
2. add attachment like pdf, png (from local storage, open this file from android files works with no issues)
3. exit editmode
4. click on attachment inside note
5. "No app associated with this mime type"
![image](https://user-images.githubusercontent.com/42573701/141084731-8db67b11-c4b7-4b74-8f4e-7ecf7d5244d6.png)

## Describe what you expected to happen
The attachment within the note should be opened with the standard app preset by the system.

**Comment by ehamminga** [comment]
Same issue here with Joplin 2.6.3 on Android 12. Reinstalling the app did not resolve the issue.

**Comment by rbender23** [comment]
Also same issue here with Joplin 2.6.3 on Android 11

**Comment by roman-r-m** [comment]
Looks like it's been fixed in https://github.com/laurent22/joplin/commit/6950c40b12cf8d270d3d86a3796f46209d209fd6
The fix is available starting from version 2.6.4

**Comment by monnypython** [comment]
Yes. Now it works as aspected. Thanks for the hint!
