### ISSUE TITLE
opening inline images does not work

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#570]
### Operating system

- macOS

### Application

- Desktop

Joplin 1.0.96

If I have an inline image `![image.jpg](:/1272d0d914b641708aeef9a8bc9aa9a2)`, neither a double-click on the image, nor the `Open..` menu item after a right-click works. Nothing happens.
In previous versions above 2 actions opened the image in the associated app for the file's mime type.

**Comment by laurent22** [comment]
Just on that particular image or on all images?

**Comment by tessus** [comment]
It happens with all images.

**Comment by laurent22** [comment]
Double-click was never implemented so it's normal it does not work. Not sure if it should as I assume it's not a very common action, so a right-click with context menu makes more sense.

> I've also noticed that the opened file has the same name as the resource + extension instead of the filename denoted in the markup:

Indeed, I'm going to add a new issue for this.
