### ISSUE TITLE
note text not starting from beginning on Mac

### ISSUE THREAD

**Issue by LeoK987** [laurent22/joplin#5701]
## Environment

Joplin version:  1.5.10
Platform: MacOS
OS specifics: 

## Steps to reproduce

1. create a note or to-do
2. input text into the editor pane
3. 

## Describe what you expected to happen

text should start from/near the edge of the pane

## Logfile

![Screen Shot 2021-11-10 at 11 23 27 AM](https://user-images.githubusercontent.com/6257601/141096050-6c2c0a0f-db0f-48e0-8e3a-978fbb1a24e4.png)

**Comment by JackGruber** [comment]
Not a bug, its a setting

#5339 

https://discourse.joplinapp.org/t/please-read-this-if-you-are-wondering-why-theres-now-a-margin-on-the-note-text/19585
