### ISSUE TITLE
Dark mode menu bar is very bright/intrusive

### ISSUE THREAD

**Issue by Githob2021** [laurent22/joplin#5706]
Joplin version: 2.5.12 (prod, linux)
Debian Linux flatpak

I'm not quite sure if this is a bug/oversight or a feature request or on purpose. But the "menu bar" (File Edit View Go Notebook .....) is in white with black text while Joplin is in dark mode. This creates a color clash as everything else on the screen is dark with light text.

I understand this may be to draw attention to the menu bar, however it would be nice to have the option to make the menu dark mode (even if a separate option) as well.

If Joplin should still have the menu bar colored in a way to draw attention but not match the rest of the dark mode, perhaps a different color could be used than white with black text. Something that does not clash so much would be preferred.

**Comment by Daeraxa** [comment]
That is controlled by your own desktop theme (its an electron thing, same thing happens in Atom for example).

For example (on Linux Mint) if I select my controls theme as "Mint-Y-Dark-Purple" I get a light menu bar, if I chose "Mint-Y-Darker-Purple" I get a dark menu bar. I don't know what theming or desktop environment you are using but it will be controlled from somewhere in there.

**Comment by Githob2021** [comment]
> That is controlled by your own desktop theme (its an electron thing, same thing happens in Atom for example).
> 
> For example (on Linux Mint) if I select my controls theme as "Mint-Y-Dark-Purple" I get a light menu bar, if I chose "Mint-Y-Darker-Purple" I get a dark menu bar. I don't know what theming or desktop environment you are using but it will be controlled from somewhere in there.

Thanks for the follow up. Joplin and its team rocks!

For anyone in the future wondering how to do this:

If you are using the flatpak version you can run the command below.

flatpak override --user --env=GTK_THEME=Adwaita:dark net.cozic.joplin_desktop
