### ISSUE TITLE
regression in command palette: text commands not shown

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#5707]
## Environment

Joplin 2.6.1 (dev, darwin)

Client ID: e354a932e6e143c782264aad4112b674
Sync Version: 3
Profile Version: 40
Keychain Supported: Yes

Revision: 725c79d1e (dev)

## Steps to reproduce

1. open Command Palette
2. try to find any commands in the Edit menu e.g. `bold`, `code`, .... (internally `textBold`, or actually all `textXXXXX` commands)
3. not found

## Describe what you expected to happen

The text commands should be shown in the command palette. I believe this is a regression. I am fairly certain this worked before.

## Logfile

No errors in console or log.

**Comment by laurent22** [comment]
Probably caused by this commit: https://github.com/laurent22/joplin/commit/23996e0efec608cc2aba13eacade796a1da7318e

I guess text commands are not quite integrated to the command system, and in particular their "enabled" property is not set correctly. Not sure what's the fix - either fix the text commands or revert the above commit I guess.

**Comment by tessus** [comment]
I'm not sure how to fix the text commands. At one point the code became so abstracted, thus one has to look in so many different files to verify a single thing. It's very confusing when you don't look at the code every single day.

**Comment by laurent22** [comment]
Probably related: https://github.com/laurent22/joplin/issues/5752

**Comment by SndChaser** [comment]
I think I have a related issue (if not I can open a new issue): assigning a shortcut to Insert Date Time in Tools->Options->Keyboard Shortcuts doesn't work.  IE, you can make the key assignment, but using it in the editor produces no output.  I assume that this has to do with changes made for the Command Palette (which I also note doesn't have an InsertDateTime command).

Environment: Linux Manjaro (Kernel 5.13.19) / XFCE 4.16
Joplin 2.5.12 (AUR AppImage)
