### ISSUE TITLE
Dark mode drag/drop of a note is blinding and text is unreadable

### ISSUE THREAD

**Issue by Githob2021** [laurent22/joplin#5710]
Version: 2.5.12 (prod, linux) stable

When using dark mode and drag/dropping a note, say from one Notebook to another. The entire note turns bright white/blinding and the text (circled in the screenshot) is barely readable. The text says "Drop notes or files here".

In this case there is text in the stop behind where that message would be, however even if that section is blank it's barely readable because it's dark text on a dark background that's highlighted white.

Both the "highlight" when dragging a note and the text should be optimized for dark mode.

![bright cannot read](https://user-images.githubusercontent.com/93590337/141313303-44a5ba49-27d2-4cbf-863c-2606e2fbcfac.png)

**Comment by Rishabhraghwendra18** [comment]
I am working on this issue
