### ISSUE TITLE
Custom ordering messes up order when creating a new note and dragging

### ISSUE THREAD

**Issue by SkyLionx** [laurent22/joplin#5713]
In have set custom ordering for my notebooks, but sometimes when I try to create a new note, instead of appearing at the bottom of the list, it is created in a random position. When I try to drag it and drop it at the bottom, it also changes the order of other notes.
It doesn't happen for all the notebooks though, and I cannot pinpoint a common factor of when this happens.
Here is a demonstration:
![2021-11-12_10-55-47](https://user-images.githubusercontent.com/23276420/141448194-6da66b34-fbb7-4cb6-8b02-253c84edd32e.gif)

## Environment

Joplin version: 2.5.12
Platform: Windows
OS specifics:  Windows 10 21H1

## Steps to reproduce

1.  Set `Sort notes by: custom order` from the view menu
2. Try to create a normal note
3. The note is not created at the end of the list
4. If you drag it to the bottom, other notes are moved

## Describe what you expected to happen
When a new note is created it should always be at the bottom of the list or below the currently selected note (it could be either for me). Also, dragging a note shouldn't change the order of other notes.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/7526645/log.txt)

**Comment by xavierpantet** [comment]
Hi everyone!

I have the same issue with Joplin v2.5.12 on macOS Big Sur (11.4).

**Comment by SkyLionx** [comment]
The issue is still there.
________________________________

**Comment by SkyLionx** [comment]
Still not fixed as of v.2.7.14.

**Comment by SkyLionx** [comment]
Any news on this? It's still not fixed on the lastest version (2.7.15) 😞

**Comment by struq** [comment]
Still not fixed, version 2.7.15.
