### ISSUE TITLE
Cannot sync between Joplin 2.5.12/Linux & Joplin 2.6.1/Android

### ISSUE THREAD

**Issue by EricBrunel** [laurent22/joplin#5716]
## Environment

Joplin version: 2.5.12 & 2.6.1
Platform: Linux & Android 11

## Steps to reproduce

1. I have a set of Joplin notes on my Linux computer which I synchronize via the file system (I actually use Syncthing to synchronize between devices, but it doesn't seem to be part of the problem). I go to the directory where all the Joplin files reside and copy everything.
2. I paste everything on my Android phone, at the location where Joplin is configured to look for its files.
3. I open the Joplin Android app and I ask for a synchronization.
4. The synchronization fails with an error about the file `version.txt`:
![Screenshot_20211113-141540](https://user-images.githubusercontent.com/22394592/141645480-a23b4db9-0806-41b7-a75c-ca14ca6b08f1.png)

## Describe what you expected to happen

The synchronization should work fine: the file `version.txt` exists, is not a directory and is writable (I can edit it with a text editor on my Android phone). I tried to rename the file `version.txt` but I got other errors about other files (namely `readme.txt` & `info.json`). If I rename these too, it messes up things even worse: all my notes disappear and a new category 'Conflicts' appear with a lot of my notes in it (but not all).

I noticed the file system access permission on Android for Joplin is set to 'media', and not all files. Could this be the origin of the issue, since `version.txt` is obviously not a media file? I had quite a few issues with this new "feature" in Android 11...

## Logfile
![Screenshot_20211113-142623](https://user-images.githubusercontent.com/22394592/141645514-50cd53f2-eda9-4c4b-ab1a-0b09cf10df64.png)

**Comment by Daeraxa** [comment]
Looks like a duplicate of https://github.com/laurent22/joplin/issues/5673
Also local file sync target

**Comment by EricBrunel** [comment]
Same bug indeed, I managed to miss it before entering this one. And downgrading to 2.5.5 works indeed, notes are syncing without problem now.
Thanks!
