### ISSUE TITLE
enable keychain on linux

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#5718]
currently, joplin just disables keychain via keytar on linux, which breaks things like https://github.com/JackGruber/joplin-plugin-backup
on linux.
Could this be fixed? 
I tried enabling it manually in the source code and saw the note (in `packages/lib/shim.ts:336`, the CI job doesn't even exist anymore, I guess it was fixed as the "fix" is over a year old), but it worked fine for me.

**Comment by CalebJohn** [comment]
The issue here was fixed in https://github.com/laurent22/joplin/commit/405b49569c1a4e4f765e405cda7e97621c8289a0 and tracked by #5720. 
The keychain still isn't utilized on Linux however, so I'll leave this up to you @r4pr0n if you'd consider this issue closed or not.
