### ISSUE TITLE
Value of `SettingItemType.String secure: true` is lost on restart

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#5720]
If a plugin uses `SettingItemType.String secure: true` and the installation does not support a keychain, the value is stored in the database.
However, on a Joplin restart, this value is deleted from the database and can no longer be read (except as a empty string).

**Values in the database**
```
SELECT * from settings WHERE key='plugin-io.github.jackgruber.backup.password'
```
Before the restart
![grafik](https://user-images.githubusercontent.com/24863925/141677000-965d74af-c136-4212-8feb-c3f7c74a3214.png)
After the restart
![grafik](https://user-images.githubusercontent.com/24863925/141677015-9bbaf2e1-e309-405d-bce2-1a8c5347a175.png)

## Environment

Joplin 2.5.12 (prod, win32) [Joplin Portable]

Client ID: e94350fb2e0f4f909ae03994878396d8
Sync Version: 3
Profile Version: 39
Keychain Supported: No

Revision: 884b86f

## Steps to reproduce

1. Use a Joplin installation with no keychain support
2. Install `Simple Backup` plugin
3. Enable `Password protected backups` in the Plugin
4. Set a password in `Password` and `Password (repeat)`
5. Close Joplin
6. Start Joplin
7. Password is no longer available

## Describe what you expected to happen

That the password for a system without keychain support remains in the database even after a reboot.

## Logfil
[console.log](https://github.com/laurent22/joplin/files/7533552/console.log)
[log.txt](https://github.com/laurent22/joplin/files/7533553/log.txt)

**Comment by xaa** [comment]
Thank you for the follow-up @JackGruber. I think this issue should be priority "high" as the backup option is broken silently in some situation.

**Comment by laurent22** [comment]
It will be fixed in the next version. In this particular case however the password would stil lbe reset if encryption is not enabled as implemented [here](https://github.com/JackGruber/joplin-plugin-backup/blob/557448c61f1a4d1fb76c7c16f0c1656cea0da959/src/Backup.ts#L114) but I guess that's on purpose?

The issue with the password being lost on restart is fixed though.

**Comment by JackGruber** [comment]
Thanks, I will test it.

I introduced this to prevent the setting of a empty password to the zip file, as it was not clear for me what caus the error with the empty zip passwords.
