### ISSUE TITLE
Can not unhook a notebook from a parent

### ISSUE THREAD

**Issue by onatbas** [laurent22/joplin#5723]
I have multiple notebooks added to other notebooks as children by mistake. However, I can't unparent them to be top-level notebooks as drag^drop doesn't  work to top level.
## Environment

Joplin version:  Any
Platform: Mac, Windows
OS specifics: 

## Steps to reproduce

1.  Add notebook A to another notebook *B* by dragging and dropping it on top of the other.
2. Obverse that A is a child of B.
3. Drag and drop A on top of "All notes" or the empty space between a notebook and "All Notes" to unhook it.
4. nothing happens.

## Describe what you expected to happen

Notebook A should not have a parent notebook anymore.

**Comment by roman-r-m** [comment]
You need to drop it onto "NOTEBOOKS" (just above "All notes")

**Comment by onatbas** [comment]
Wow. It was there all along. Thanks.
