### ISSUE TITLE
Hyperlink is lost when cuting and pasting Joplin note link in WYSIWYG editor

### ISSUE THREAD

**Issue by codyburleson** [laurent22/joplin#5724]
Hyperlink is lost when cuting and pasting Joplin note link in WYSIWYG editor

## Environment

Joplin version: Joplin 2.5.12 (prod, win32)
Platform: win32
OS specifics: Windows 11

## Steps to reproduce

1. Copy markdown link of another note.
2. While only in the WYSIWYG editor, paste the markdown link. It will display with a blue hyperlink.
3. Now, while still in the markdown editor, cut and past the same link. Cut it from one place in the body of the WYSIWYG editor and then paste it into some other spot in the body of the same editor. The text of the link will paste from the clipboard, but the hyperlink does not come with it.

## Describe what you expected to happen

I expect for the blue hyperlink to remain after pasting hyperlinks in the WYSIWYG, regardless if they are external links or markdown links to other notes within Joplin.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/7534566/log.txt)

**Comment by special0star1** [comment]
I also have the same problem

**Comment by ScriptInfra** [comment]
This might be related to 5576.
