### ISSUE TITLE
No synchronisation from Dropbox

### ISSUE THREAD

**Issue by hedonnn** [laurent22/joplin#5725]
I have Joplin sync through Dropbox (encrypted as well) on a Win10 laptop and Android phone.
I installed Joplin on a new Win10 laptop, activated Dropbox sync and encryption.
I run synchronisation, it runs and stops. Having fetched nothing at all...

## Environment

Joplin 2.5.10 (prod, win32)

Client ID: 3d74b7c0be5d49f29070ba40f355ec09
Sync Version: 3
Profile Version: 39
Keychain Supported: Yes

Revision: b80242d

## Steps to reproduce

1.  Install Joplin on a new Win10 laptop
2.  Activate dropbox sync and encryption
3.  Click synchronize, it runs, but nothing is fetched.

## Describe what you expected to happen

To get my notebooks and notes back!

## Logfile

No error in the console shown.

**Comment by eduardokimmel** [comment]
Same thing happening to me while trying to sync on a new iOS device.
