### ISSUE TITLE
Provide MimeType in linux desktop file

### ISSUE THREAD

**Issue by langdon** [laurent22/joplin#5728]
With the new "copy external link" returning a "joplin://" uri scheme, the desktop file should include a key to register the mimetype. For example ```MimeType=x-scheme-handler/joplin```

## Environment

Joplin version: 2.5.12
Platform: linux (flatpak)
OS specifics: 

## Steps to reproduce

1. ```xdg-open joplin://x-callback-url/openNote?id=<uuid>```
2. ```gio: joplin://x-callback-url/openNote?id=<uuid>: The specified location is not supported```

## Describe what you expected to happen

joplin to open to the specified note

**Comment by laurent22** [comment]
Isn't it what we have here? https://github.com/laurent22/joplin/blob/405b49569c1a4e4f765e405cda7e97621c8289a0/Joplin_install_and_update.sh#L221

We've tested on Linux and the urls were working.

**Comment by CalebJohn** [comment]
@laurent22 looks like this is an issue specific to the flat pack. Looks like they haven't updated the [joplin.desktop file on their end](https://github.com/flathub/net.cozic.joplin_desktop/blob/master/joplin.desktop). Maybe they're pulling it out of the AppImage directly and not using the install script?

In either case, I don't think this is our problem. Although i do notice that they're using the name "net.cozic.joplin" so maybe this is a sanctioned by you?

**Comment by langdon** [comment]
Tbh, I'm the middleman here. I filed a bug on the flatpak and they pointed me here. https://github.com/flathub/net.cozic.joplin_desktop/issues/26 /cc @tinywrkb

**Comment by catsout** [comment]
The desktop file is manually specified in the flathub repo.  
I can't remember where the desktop file comes from, and I didn't find the desktop file in the joplin's source, as it's written in the install script   
This will be fixed by adding the  `MimeType` section.

**Comment by CalebJohn** [comment]
Thanks @catsout nice to see it's fixed.
