### ISSUE TITLE
web clipper ignores <pre> html tag

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#573]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

### Description

when clipping a page (simplified or complete), the highlighting syntax content in `<pre>` (sometimes with attribute lang=python/shell/whatever) is not handled. And instead, a mardkonw table is made, because the pre in inside the table.

[example of blog with many many piece of python code](http://sametmax.com/comprendre-les-decorateur-python-pas-a-pas-partie-2/)

And as a workarround, using the "clip screenshot" is not a solution because their blog posts are often very very long

**Comment by vensko** [comment]
Still experience this with Web Clipper 1.0.6 in Firefox.
[Example page](https://www.ibuildings.nl/node/258) where `pre` is ignored.

**Comment by dayfuaim** [comment]
Still here in Web Clipper 1.0.8 (Brave Beta 0.60.19 Chromium: 72.0.3626.81, beta [64 bit]), Web Clipper 1.0.8 (Firefox 67.0a1 [64 bit]).
[Example page](https://medium.com/the-set-list/ruby-on-rails-security-be16bd1a8b02)
OSX 10.10.5.
