### ISSUE TITLE
ipone XR 13.6.1   Synchronise error

### ISSUE THREAD

**Issue by yiyinyiyang** [laurent22/joplin#5734]
ipone XR 13.6.1   Synchronise error 

## Environment

Joplin version: 12.5.3
Platform: ipone XR 13.6.1 

I am using AWS S3 (Beta) in the sync function
I'm using Tencent Cloud
I downloaded joplin from the iphone store and set up an automatic sync and then it appeared
Completed:15/11/2021 20:07(23s)
Last error: XMLParserError: Non-
whitespace before first tag.
Line:0
Column:1
Char:G
But using my other Android phone to sync
There is no error 
Maybe there is no bug in the sync function of Android phone, but I don't know what's wrong with the sync of Apple phone?

this is error pic
![joplin syn error](https://user-images.githubusercontent.com/55334719/141782040-bdeb3927-6d9e-413c-8981-9f24ea8af97a.jpg)

**Comment by zxkmm** [comment]
See [here ](https://github.com/laurent22/joplin/pull/5312)

**Comment by yiyinyiyang** [comment]
also no fixed

**Comment by leematos** [comment]
My PR was just merged to fix this -- The next iOS build should have it.

**Comment by yiyinyiyang** [comment]
well done looking forward it
