### ISSUE TITLE
Reminders don't work on Android 8.1

### ISSUE THREAD

**Issue by 5hay** [laurent22/joplin#574]
### Operating system

- Android 8.1 (Nokia 7 Plus)

### Application

- Mobile

### Description

Unfortunately reminders don't work on Android 8.1 (Nokia 7 Plus). They just won't trigger at all. The only errors in the Log are that my GPS is turned off so it cannot get my location.

**Comment by 5hay** [comment]
My bad, didn't see that issue (even searched before posting...). But yeah, no notification and no sound. Even tried short delay, doesn't work either.

**Comment by foxmask** [comment]
me too and I don't understand why yet. I suspect the "do not disturb" mode ... 
So I close this issue, we'll continue on #321  :)
