### ISSUE TITLE
Image from column 1 of a table displaced

### ISSUE THREAD

**Issue by MrMacvos** [laurent22/joplin#5741]
I notice since the last version that an image which should be displayed inside column 1 of a table, is not displayed there in split view, only in WYSISYG-view. Even stranger, in split view, the image is floating over the text in the editor (see screenshots).

## Environment

Joplin version: 2.5.12
Platform: macOS
OS specifics: 11.6.1

## Steps to reproduce

1. Create a table with 5 columns
2. Place a small image in column 1
3. Fill the other 4 columns with a few lines of text
4. View it on a laptop-size screen in normal editing view (split view) so the table is compressed a bit.
5. Start editing the table in the markdown-editor, and hopefully you see it too.
<img width="666" alt="Screenshot 2021-11-17 at 10 59 30" src="https://user-images.githubusercontent.com/1470464/142186624-10cc0eac-e36e-49ab-b75f-175ab2eac0ef.png">
<img width="713" alt="Screenshot 2021-11-17 at 10 59 38" src="https://user-images.githubusercontent.com/1470464/142186630-58e09d74-e841-4847-9f1e-340cacb2f691.png">
<img width="1245" alt="Screenshot 2021-11-17 at 11 37 18" src="https://user-images.githubusercontent.com/1470464/142186633-42236771-9925-4c96-a19d-a3e308f93fd1.png">

## Describe what you expected to happen

Image should not float around te screen, but be shown where it was placed.

**Comment by Daeraxa** [comment]
Works fine for me - Linux mint on 2.5.12 (also tried it with the lines at the start and end for the columns, same result)
![image](https://user-images.githubusercontent.com/58074586/142189177-cac52a89-3412-44d2-aeec-566231e8278f.png)
