### ISSUE TITLE
Window invisible after start

### ISSUE THREAD

**Issue by masgo** [laurent22/joplin#5744]
Sometimes when starting Joplin the window is not visible. Seems to be a variant of https://github.com/laurent22/joplin/issues/2454

I am using Joplin on a Notebook which is connected to various and changing displays. Sometimes I also access the notebook via RDP, with different resolutions. The result is, that sometimes the values in window-state-prod.json are in such a way that the window is "gone". For example
`{"width":1399,"height":960,"x":4101,"y":100,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":1920,"y":0,"width":1920,"height":1200}}
`

If I change `x` back to `0`, then Joplin starts again. 

## Environment

Joplin version: 2.5.12
Platform: Windows
OS specifics: Windows 10 21H1

## Steps to reproduce

1. Run Joplin
2. Connect via RDP while using multiple a high resolution screens.
3. Move Joplin window to the side.
3. Log in locally on a lower resolution screen.

## Describe what you expected to happen

It would be nice if Joplin would shomehow check if the position is outside of the area of the current monitor and then reset to something usful like `0`.

**Comment by masgo** [comment]
I am still having this issue from time to time.

**Comment by ccoenen** [comment]
I just had a problem extremely similar to this and #2454 with Joplin 2.10.19 from Flatpak on Fedora Linux with Wayland and GNOME.
In my case, updating the `~/.var/app/net.cozic.joplin_desktop/config/Joplin/window-state-prod.json` was the only thing that could restore the invisible window.
