### ISSUE TITLE
Can’t edit notes on iOS

### ISSUE THREAD

**Issue by Erik098** [laurent22/joplin#5746]
## Environment

Joplin version: 12.5.3
Platform: iOS
OS specifics: 14.8.1

## Steps to reproduce

1. Open Joplin
2. Press on the text
3. See nothing happening 

## Describe what you expected to happen
I want to edit my text but don’t get a cursor.
I can hold my press and then I can make a selection, cut and copy, but no cursor.
I can change the title of the note, just not the note itself.
I have the same issue on my iPhone 6s and iPad 6 generation, everything works well on my MacBook.
When I create a new note everything works normal as long as I don’t close Joplin, then I can’t edit it anymore.
And why is it so hard to report a bug… very annoying….

## Logfile
I can’t copy the text of the log and I’m not allowed to post a pic…

**Comment by Daeraxa** [comment]
To edit a note you don't press on the text, you need to press the orange edit circle thing, is that not showing up for you?

**Comment by Erik098** [comment]
I thought that was to make a new note…
This can be closed it’s working, thanks for the fast reply.

**Comment by Daeraxa** [comment]
No problem. The icon changes depending on the screen. It is a + to make a new note on the note list screen but changes to a pencil + paper icon when viewing a note.
