### ISSUE TITLE
Very light text when synchronising joplin with oneDrive

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [laurent22/joplin#5747]
After selecting `OneDrive` as an sync method . I see a white screen with a light gray text on which is a important message  . It's hard to see on the white background (as you can see in the pic below). It will be good to be text in black so that it doesn't strain on user's eye 

## Environment

Joplin version: v2.6.0 (dev,linux)
Platform: Linux
OS specifics: Ubuntu 20.04

## Steps to reproduce

1. Go to setting => open Sync Wizard 
2. Select OneDrive

## Describe what you expected to happen
Text to be in black for easy readability 
![Screenshot from 2021-11-18 17-20-23](https://user-images.githubusercontent.com/43534227/142412417-e08a1570-e9f6-42da-a902-ea3ee636d7e8.png)

**Comment by Rishabhraghwendra18** [comment]
I am working on this issue

**Comment by roman-r-m** [comment]
Isn't it the same as https://github.com/laurent22/joplin/issues/5726 ?
