### ISSUE TITLE
--joplin-background-color2 is not updated

### ISSUE THREAD

**Issue by shbach** [laurent22/joplin#5753]
As mentioned [here](https://discourse.joplinapp.org/t/notebook-note-to-do-tag-search-favorites-plugin/14049/75), `--joplin-background-color2` is not updated unless Joplin is restarted or if the setting are opened and then closed. Because of this, any plugins which add a panel such as [note tabs](https://github.com/benji300/joplin-note-tabs), [favorites](https://github.com/benji300/joplin-favorites), [Note Link System](https://github.com/ylc395/joplin-plugin-note-link-system), [Outline](https://github.com/cqroot/joplin-outline), etc can end up displaying a white background while the rest of the UI is black or vice versa.

## Environment

Joplin version: 2.5.12
Platform: Linux
OS specifics: Solus

## Steps to reproduce

1. Install any plugins that add a panel such as [note tabs](https://github.com/benji300/joplin-note-tabs), [favorites](https://github.com/benji300/joplin-favorites), [Note Link System](https://github.com/ylc395/joplin-plugin-note-link-system), [Outline](https://github.com/cqroot/joplin-outline), etc
2. Enable option to automatically switch theme to match system theme
3. Change system theme without closing Joplin

## Describe what you expected to happen

All panels should match the system theme.

**Comment by Rishabhraghwendra18** [comment]
sorry to post the screenshot but to be more accurate you mean UI looks something like this?
![Screenshot from 2021-11-23 10-46-33](https://user-images.githubusercontent.com/43534227/142974703-31417e02-3310-42b9-adaa-f339fe452663.png)

I switched system theme from dark to light while the joplin is open . I have tried this with note tabs

**Comment by shbach** [comment]
@Rishabhraghwendra18 Here is a screenshot which shows the issue:
![Screenshot from 2021-11-23 13-47-40](https://user-images.githubusercontent.com/5298745/143138615-e16a713e-d99e-447e-88f9-538a660a7095.png)

The screenshot you posted seems to have a different issue in that the editor panel is still white?

**Comment by Rishabhraghwendra18** [comment]
> 

Not now but at that time it happen . Now it's showing same as your screenshot . I am using joplin v2.6.1(dev,linux).

**Comment by Rishabhraghwendra18** [comment]
I have tried by manually changing value of `--joplin-background-color2` in chromium dev tools but nothing changed . Background colour remains the same(dark) . Please try yourself that whether manually changing the `--joplin-background-color2` color changes ? I feel like I am doing something wrong

**Comment by shbach** [comment]
> I have tried by manually changing value of `--joplin-background-color2` in chromium dev tools but nothing changed . Background colour remains the same(dark) . Please try yourself that whether manually changing the `--joplin-background-color2` color changes ? I feel like I am doing something wrong

@Rishabhraghwendra18 Sorry, I'm not technically proficient enough to understand how to do what you are describing.

Also, as a side note, as I've been making use of more extensions this issue is even more noticeable. Any plugin that adds a panel has this issue. Since I have set my theme to change between dark/night depending on the time of day, this causes issues twice a day which is pretty annoying.

**Comment by laurent22** [comment]
I cannot replicate this anymore. If it still happens, please provide the exact steps and plugins that are needed to replicate the bug

**Comment by shbach** [comment]
> I cannot replicate this anymore. If it still happens, please provide the exact steps and plugins that are needed to replicate the bug

@laurent22 I can still replicate this bug both on Windows 10 and Linux (Gnome) on Joplin 2.12.18. The steps for replicating are basically still the same as what I wrote in the original post.

1. Install any plugins that add a panel such as [note tabs](https://github.com/benji300/joplin-note-tabs), [favorites](https://github.com/benji300/joplin-favorites), [Note Link System](https://github.com/ylc395/joplin-plugin-note-link-system), [Outline](https://github.com/cqroot/joplin-outline), etc
2.    Enable option in Joplin to automatically switch theme to match system theme
3.    Change OS system theme without closing Joplin. In Windows this is done by going to colors and changing from light to dark and vice versa. On Linux you need to have Gnome tweaks installed and under appearance change the shell theme between a light and dark theme.

You should see the panels for the plugins not change color with the rest of Joplin.

**Comment by laurent22** [comment]
It's been fixed in 2.13
