### ISSUE TITLE
joplin server migrations: failed to add constraint "items_name_owner_id_unique", key duplicated

### ISSUE THREAD

**Issue by ahxxm** [laurent22/joplin#5761]
## Bug description and reproduce

steps to reproduce(might fail due to uniqueness of my database):
- upgrade from `2.5.9-beta` to `2.6.11-beta`
- recreate containers

error message from `docker-compose logs -f`:
```
db_1   | 2021-11-20 02:25:04.876 UTC [34] DETAIL:  Key (name, owner_id)=(.resource/97d9278f161ff786c69cb970f3f72c54, owner_id_redacted) is duplicated.
db_1   | 2021-11-20 02:25:04.876 UTC [34] CONTEXT:  parallel worker
db_1   | 2021-11-20 02:25:04.876 UTC [34] STATEMENT:  alter table "items" add constraint "items_name_owner_id_unique" unique ("name", "owner_id")
app_1  | migration file "20211030103016_item_owner_name_unique.js" failed
app_1  | migration failed with error: alter table "items" add constraint "items_name_owner_id_unique" unique ("name", "owner_id") - could not create unique index "items_name_owner_id_unique"
db_1   | 2021-11-20 02:25:04.880 UTC [1] LOG:  background worker "parallel worker" (PID 35) exited with exit code 1
db_1   | 2021-11-20 02:25:04.882 UTC [34] ERROR:  current transaction is aborted, commands ignored until end of transaction block
db_1   | 2021-11-20 02:25:04.882 UTC [34] STATEMENT:  update "knex_migrations_lock" set "is_locked" = $1
```

## Duplication

I found the duplication by:

```sql
select * from (
  SELECT name,
  ROW_NUMBER() OVER(PARTITION BY name, owner_id ORDER BY name asc) AS Row
  FROM items
) dups
where 
dups.Row > 1;
```

copy paste the hash to local client, the resource turns out to be a image file:

```
joplin-# ;
                    name                    | row
--------------------------------------------+-----
 .resource/97d9278f161ff786c69cb970f3f72c54 |   2
(1 row)
```

I deleted the resource locally, made a successful sync with server. 
But these 2 rows still exist in the database, thus the migration still fails

```
joplin=# select id,name,updated_time from items where name='.resource/97d9278f161ff786c69cb970f3f72c54';
                id                |                    name                    | updated_time
----------------------------------+--------------------------------------------+---------------
 QBaYa5gizQIIXliT4pXbbxn4IKL54REn | .resource/97d9278f161ff786c69cb970f3f72c54 | 1632132011366
 m5UHmyGAegmvssZpIWU0FeGoYE5WvMJY | .resource/97d9278f161ff786c69cb970f3f72c54 | 1624934599568
(2 rows)
```

## Describe what you expected to happen

~~...I expect a solution to this issue?~~ is it safe to just delete a random row among the two rows?

possibly related [commit](https://github.com/laurent22/joplin/commit/f7a18bac2a065fc865347c239801ddc4d731bf7a)

btw, postgresql supports ["Add Constraints Without Validating Immediately"](https://hakibenita.com/postgresql-unknown-features#add-constraints-without-validating-immediately)

**Comment by laurent22** [comment]
I think you need to delete the resource from Tools > Attachment then sync again.

**Comment by ahxxm** [comment]
> I think you need to delete the resource from Tools > Attachment then sync again.

thanks, that should cure the symptom, i'll try later

**Comment by ahxxm** [comment]
the symptom itself has been fixed, but i wonder why there were duplicate items

**Comment by ahxxm** [comment]
@laurent22 do you have any idea why there were duplicate items?
