### ISSUE TITLE
Tab key does not create indentation in WYSIWYG editor instead it moves to tag section and so on.

### ISSUE THREAD

**Issue by bube5h** [laurent22/joplin#5762]
## Environment

Joplin version: 2.5.12
Platform: Windows 10
OS specifics: I tried only in windows. I don't have Linux

## Steps to reproduce

1. Create a new note
2. Open WYSIWYG editor
3. Pressing Tab wont indent, instead it will make the tag section active. Press Enter to see.

## Describe what you expected to happen
When I press Tab, I would like an indentation.

Discussion: https://discourse.joplinapp.org/t/tab-key-working-in-the-rich-text-view/14141

**Comment by erikmd** [comment]
I've just faced this issue for the default Markdown editor,
then noticed the current version of Joplin offers a menu command to enable/disable this behavior → for the record:

<img width="378" height="772" alt="Image" src="https://github.com/user-attachments/assets/72323bb2-2897-4a52-842a-9f59a8d4b4ef" />
