### ISSUE TITLE
Cannot save notes after synchronization is turned on

### ISSUE THREAD

**Issue by CosmicExplorer-M** [laurent22/joplin#5765]
## Environment

Joplin version: Joplin 2.5.12 (prod, win32)
Platform: Windows 10 21H1  
OS specifics:  19043.1348

## Steps to reproduce

1.  start program
2. Create a note
3. Press `ctrl + s` at the same time

## Describe what you expected to happen

I use WebDAV for syncing and after doing a save, this should store a new note, but in fact my new note is deleted even though I have failsafe turned on

## Logfile

After checking the logs, there are no errors or exceptions, and I don't understand whether this is an exception or a feature. I can't upload my logs because of privacy issues. But for the record, this problem does not always occur, but only shortly after creating a new file, e.g., storing it by just typing a title.

**Comment by AtilioA** [comment]
Couldn't reproduce on W10 20H2 under same circumstances (Nextcloud through WebDAV)
