### ISSUE TITLE
Joplin tries to synch, although synch-intervall is deactivated

### ISSUE THREAD

**Issue by schwaschwa** [laurent22/joplin#5768]
Not sure, if it's a bug or an intended behavior: Joplin tries to synch, although auto-synching via synch-intervall is deactivated. If it is not a bug, i really wish there would be a way to stop Joplin from trying to synch my data for example in an public network.

## Environment

Joplin version: 2.5.12
Platform: Mac OS
OS specifics: Big Sur

## Steps to reproduce

1. Deactivate Synch Intervall
2. Open Joplin

## Describe what you expected to happen
Joplin doesn't try to synch.

## What happens
Joplin starts to try synching (visible in the left panel).

**Comment by Daeraxa** [comment]
You can set the sync type to none which will have the desired effect with the downside of having to change it back every time you want to sync again but I agree with the expected behaviour based on the wording, if you set the sync interval as disabled I would expect it to _only_ sync when manually triggered (and not at any other point like at the point of launching the app)

**Comment by tessus** [comment]
This has been like this since the beginning. The sync interval is used to sync all changes with the sync target. The sync that happens when changing a note only affects the respective note. A micro sync. It was designed this way to minimize conflicts. There is no way to change this behavior.

**Comment by Daeraxa** [comment]
The micro sync on note change is fine however I think the fact that Joplin still performs a sync on startup regardless of setting is the issue - I would expect the `disabled` setting to mean that it will only sync when requested - i.e. when creating/editing a note (micro sync) or when the sync button is manually pressed (full "fetch" sync).

**Comment by tessus** [comment]
> the fact that Joplin still performs a sync on startup regardless of setting is the issue

Hmm, I never tought of that, but maybe there's a reason for that as well. @laurent22 would know. e.g. since I never start Joplin unless when I upgrade, I would not really have that problem.
