### ISSUE TITLE
White space below editor

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#5774]
![image](https://user-images.githubusercontent.com/1285584/143004298-6ce4fba2-711f-4617-9e2a-1a34fbf7bd31.png)

**Comment by entrymaster** [comment]
I'm unable to reproduce this bug.

**Comment by laurent22** [comment]
@personalizedrefrigerator, I seem to remember you've made some changes related to the editor sizing. Do you know if that particular bug is fixed? I don't think I've ever managed to replicate it anyway.

**Comment by personalizedrefrigerator** [comment]
This looks like the same issue as https://github.com/laurent22/joplin/issues/6636 . It isn't fixed yet.

**Comment by personalizedrefrigerator** [comment]
I've experienced a similar issue with [a-Shell](https://github.com/holzschu/a-shell), which also has a scrollable frame within the main WkWebView.
