### ISSUE TITLE
Beta editor keyboard is gray even in dark mode

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#5775]
> I also noticed that the keyboard is always the "light mode" grey version regardless of the iOS theme setting. If you enable dark mode and open a text field in other applications you get the dark keyboard, Joplin always opens a light version. This is also specific to the beta editor and not the regular one which uses the correct iOS theme setting.

**Comment by laurent22** [comment]
Appears to be fixed (maybe by #6326 ?). When the app is using the dark theme, the keyboard is also dark.

**Comment by personalizedrefrigerator** [comment]
This doesn't seem to be fixed for me (this looks like an [upstream bug in react-native-webview](https://github.com/react-native-webview/react-native-webview/issues/1634)). The proposed solution involves creating/modifying Objective-C types during runtime (I think). I'm very new to Objective-C and have been unable to get `react-native-webview` to deploy to an iOS device.

Would someone with more iOS development experience be willing to work on this?
