### ISSUE TITLE
Crash with paste of a slightly complex plantUML

### ISSUE THREAD

**Issue by HeinerSpecht** [laurent22/joplin#5778]
## Environment

Joplin version: 2.5.12 (prod, win32)
Platform: Windows
OS specifics: 10 64Bit

## Steps to reproduce

1. Install plantUML Plugin
2. open new Note
3. paste following content:

        # Verzeichnisstruktur
        
        ```plantuml
        @startuml
        allowmixing
        
        skinparam linetype ortho
        
        folder GeoFM {
          package VG {
            class "Flächenblatt" as FB {
              GP-Nr:String
            }
          }
          package VF {
            class "Ergebnisblatt" as EB {
              GP-Nr:String
              GP-Nr-gemeldet:String
            }
          }
        }
        
        @enduml
        ```

## Describe what you expected to happen

The plantUML Plugin should have produced an image (what it seemingly did not, white page)  
AND the editor should have stayed active (which it did not, see the Error Message at the end)

### Error
The text editor encountered a fatal error and could not continue. The error might be due to a plugin, so please try to disable some of them and try again.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to restart in safe mode, which will temporarily disable all plugins.

#### Message
Unknown state undefined

### Version info
Joplin for Desktop

Copyright © 2016-2021 Laurent Cozic
Joplin 2.5.12 (prod, win32)

Client-ID: 6b62c25734164797a2f5f12e443c00e7
Sync-Version: 3
Profil-Version: 39
Unterstützter Schlüsselbund: Ja

Revision: 884b86f
### Plugins
```json
[
    {
        "id": "com.github.uphy.PlantUmlPlugin",
        "name": "PlantUML",
        "enabled": true,
        "version": "0.0.1"
    },
    {
        "id": "outline",
        "name": "Outline",
        "enabled": true,
        "version": "1.2.0"
    },
    {
        "id": "joplin.plugin.ambrt.fold-cm",
        "name": "Folding in Code Mirror Editor",
        "enabled": true,
        "version": "1.2.5"
    }
]
```
### Component stack

    in ForwardRef(Editor) (created by ForwardRef(CodeMirror))
    in div (created by ForwardRef(CodeMirror))
    in div (created by ForwardRef(CodeMirror))
    in div (created by ForwardRef(CodeMirror))
    in ErrorBoundary (created by ForwardRef(CodeMirror))
    in ForwardRef(CodeMirror) (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by ResizableLayout)
    in div (created by styled.div)
    in styled.div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in ResizableLayout (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in ThemeProvider (created by RootComponent)
    in StyleSheetManager (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary

**Comment by CalebJohn** [comment]
It looks like you're using the old (deprecated) version of the PlantUML plugin. There were some issues with that version (as you've seen) and the plugin was [forked](https://discourse.joplinapp.org/t/plugin-plantuml/20755?u=calebjohn). Please install PlantUML2 and give it a try. Here is the result of trying it on my computer

![image](https://user-images.githubusercontent.com/2179547/143194022-7b91809a-c2a2-48d9-b200-2091e21f0b46.png)

**Comment by HeinerSpecht** [comment]
Thanks a lot, that worked :+1:
