### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by quotengrote** [laurent22/joplin#578]
### Operating system

- Windows
- macOS (not tested)
- Linux
- Android (not tested)
- iOS (not tested)

### Application

- Desktop
- Mobile (not tested)
- Terminal (not tested)

There is a typo in [https://github.com/laurent22/joplin/blob/dcaaf50a5a54f0be484193f6b2017eb154b9a034/ReactNativeClient/lib/services/AlarmService.js](url)
"Updading" should be "Updating".

**Comment by laurent22** [comment]
Fixed
