### ISSUE TITLE
code block is not working properly, markdown editor is not compatible with markdown grammar

### ISSUE THREAD

**Issue by h888866j** [laurent22/joplin#5780]
code block could not ends correctly with ``` , a standard markdown grammar.  
Another bug about the code block https://github.com/laurent22/joplin/issues/5422 was found earlier,  but has not resovled in the last three month.

## Environment

Platform: win10
OS specifics: Microsoft Windows [Version 10.0.15063]
Joplin 2.5.10 (prod, win32)

Client ID: f1b2a3f4f2af42eea8e2b885bfa5ccea
Sync Version: 3
Profile Version: 39
Keychain Supported: Yes

Revision: b80242d

## Steps to reproduce

1. download this copy of md file [A heading.md](https://github.com/laurent22/joplin/files/7594077/A.heading.md) and open it in Joplin

## Describe what you expected to happen

correct parse of markdown grammar

## Logfile
no need for log file, open the md file and you will get the same result
![image](https://user-images.githubusercontent.com/16606957/143204565-bf9f370c-0082-4d1b-bd63-fbf7066417e8.png)

@laurent22

**Comment by Daeraxa** [comment]
There is no need to ping/mention anyone in an issue.
Interestingly if you remove the last three backticks then put them back in and CR it renders correctly

**Comment by h888866j** [comment]
> There is no need to ping/mention anyone in an issue. Interestingly if you remove the last three backticks then put them back in and CR it renders correctly

thanks for the reply, I checked, removed and add the three backticks abck, but it did not works as expected.
I then have more test and then pasted the whole content to notepad and show all characters, found that there is a TAB and a SPACE after the three ending backticks.  

I created a new markdown file, and test with tab and space, issue reproduced!!!

It is too vulnerable...
