### ISSUE TITLE
Clicking at the end of line does not moves the cursor to the end of line(text) in the list.

### ISSUE THREAD

**Issue by Bubesh958** [laurent22/joplin#5782]
## Environment

Joplin version: 2.5.12(prod, win32)
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Create a numbered list with two items. The second being nested inside first one
2. Click at the end of first item in the list.
3. The cursor will move to the start of text line.

![image](https://user-images.githubusercontent.com/34552173/143264437-3206f5fb-4b27-48cf-b395-428bf351f483.png)

Click at the arrow. But the cursor will not move to end of line.

## Describe what you expected to happen
The cursor should move to the end of line if we click at the line end.

**Comment by Bubesh958** [comment]
I can work on this. But need a little bit of help. Let me know where to look.

**Comment by laurent22** [comment]
You cannot work on an issue you create. See https://joplinapp.org/gsoc2021/pull_request_guidelines/
