### ISSUE TITLE
Urgent : sync failed since update to latest released version and worse in android

### ISSUE THREAD

**Issue by alexlavigne** [laurent22/joplin#5784]
I have updated my Joplin in android serveral days before, then it failed to sync, and the worse thing is , I can not see all my notebooks list in the popup left menu again. And an error message occur in the menu under the Synchronize icon.

the screenshot of it as follow:

![Screenshot_20211124_232704](https://user-images.githubusercontent.com/35389180/143316691-57c00383-e107-4d13-8103-c2380c7d1bdf.jpg)

In this case, I can just stay in the notebook which I open last time, can not go to see other notebook.

Since it is almost unusable in mobile, I downloaded the latest version of appimg tonight in archlinux system.But it failed to sync
too . The better thing is that I can still see my notebook list in left menu, so I can still find my notes in pc.
and the screenshot of it as follow:

![image](https://user-images.githubusercontent.com/35389180/143317433-a6d57c6d-ea85-4f28-8252-06b884ec6242.png)

## Environment
 - mobile  
Joplin version: 2.4.3
Platform: Android
OS specifics: android 4.14.116
(update from google play store)

- laptop
Joplin version: Joplin-2.5.12.AppImage
Platform: Linux
OS specifics: archlinux
(archlinux just upgrade to latest in 2021-11-25 )
![image](https://user-images.githubusercontent.com/35389180/143318705-0381ae8c-6ab0-429c-8455-7c6648e83327.png)

## Steps to reproduce

1. upgrade app/appImage to latest version
2. sync

## Describe what you expected to happen

sync success and all function be ok

## Logfile

>
[log.txt](https://github.com/laurent22/joplin/files/7598988/log.txt)
[log-in-console.log](https://github.com/laurent22/joplin/files/7598990/log-in-console.log)

**Comment by lemfre** [comment]
I'm dealing with the **same** issue.

Mobile:
======
Joplin: 2.6.3
OS: Android 11
Kernel: 4.14.187

Desktop:
======
Joplin: 2.5.12 (from flathub.org)
OS: Linux Mint 20.1 x86_64
Kernel: 5.4.0-90-generic

**Comment by alexlavigne** [comment]
> I'm dealing with the **same** issue.
> 
> # Mobile:
> Joplin: 2.6.3 OS: Android 11 Kernel: 4.14.187
> 
> # Desktop:
> Joplin: 2.5.12 (from flathub.org) OS: Linux Mint 20.1 x86_64 Kernel: 5.4.0-90-generic

I think I have found the reason.
It is something wrong in sync server.

In my case , the sync server is unaccessable, which I am deploying in vps with aliyun domain.
But the domain is not accessable again in recent, since the policy of ICP filing information has changed .

If you try to access any website deploy in the same domain, you will get error page like this :
![image](https://user-images.githubusercontent.com/35389180/143661557-5581e801-1ab8-44d4-b4b4-7b2cc2261167.png)

Bad news: If you using webdav service in a such domain, using ip address directly instead of domain is futile.
An possible solution will be  using vps outside of CN.
Appling for an ICP filing for your website should be a complicated solution.

**Comment by alexlavigne** [comment]
Sorry , this problem is caused by a problem of sync server in CN. 
It is not an issure of joplin project.

**Comment by alexlavigne** [comment]
I think there is one bug need to fixed:
in Android client, if we failed to sync, we should using meta-data of local, the menu should not show like a brand-new one.
