### ISSUE TITLE
macOS App Fails to Connect to Joplin Server on Ubuntu - Invalid header token

### ISSUE THREAD

**Issue by billkenney** [laurent22/joplin#5785]
I installed Joplin on Ubuntu 20.04 with docker, and I'm unable to connect to the server with the macOS app. The iPhone app connects perfectly fine. I've tried deleting the docker container/image and reinstalling, but the same thing happens. I'm running Joplin behind a caddy reverse proxy with a simple configuration file. The error messages is as follows:

Error. Please check that URL, username, password, etc. are correct and that the sync target is accessible. The reported error was:
request to https://joplin.domain.com/api/sessions failed, reason: Parse Error: Invalid header token (Code HPE_INVALID_HEADER_TOKEN)

**Comment by laurent22** [comment]
You need to check caddy's logs because that's not a Joplin Server error.
