### ISSUE TITLE
Redundant `npm install` script in Build docs for Clipper 

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [laurent22/joplin#5792]
The build [section](https://github.com/laurent22/joplin/blob/dev/BUILD.md#building-the-clipper) for clipper has a step to install node modules in `popup` directory of `app-clipper` . I think it's redundant because when we run `npm install` in the root folder it downloads the modules for all the packages . 

I have already found node modules installed in the `popup` directory and I have never run `npm install` in the directory so on this basis I think it's legitimate to remove this step . 

If I am correct then I will make a PR for it .
Thanks

**Comment by laurent22** [comment]
Yes that can be removed
