### ISSUE TITLE
Shared duplicated note keeps updating remote items

### ISSUE THREAD

**Issue by roadbearstudios** [laurent22/joplin#5796]
## Environment

Joplin version: 2.5.12
Platform: Linux
OS specifics: Manjaro
Joplin server version: 2.6.10(Docker-based)

## Steps to reproduce

1. Duplicate a note with resources 
2. Move the duplicated note to a shared notebook
3. Synchronize and see the note + resources being uploaded
4. Synchronize again, and see Joplin updating remote items
5. Repeat step 4, and it will keep doing the same update

The problem seems to be that Joplin doesn't copy resources when a note is duplicated, but refers to the same resources. This creates a problem when an (encrypted?) duplicated note is copied to a shared notebook. 

## Describe what you expected to happen
I would except the note with resources to be uploaded correctly, and not keep updating remote items.

## Logfile
This SQL-statement seems to be the problem:

db_1   | 2021-11-27 09:52:36.529 UTC [38] STATEMENT:  insert into "user_items" ("created_time", "item_id", "updated_time", "user_id") values ($1, $2, $3, $4)
db_1   | 2021-11-27 09:52:36.533 UTC [38] ERROR:  duplicate key value violates unique constraint "user_items_user_id_item_id_unique"
db_1   | 2021-11-27 09:52:36.533 UTC [38] DETAIL:  Key (user_id, item_id)=(FyhxSv9GlN6Ej4LDrCCxXEEYaglrGxj1, vIPozEiX5NULI5a1kXLTw6i1iVjoFVZm) already exists

**Comment by SuperXiaoxiong** [comment]
I think the problem doesn't sovled , I use window11 and macOS Monterey。 And the joplin app are both 2.8.8,  the joplin server is 2.7.4-beta, When both client app have the same resources, they will duplicate sync ,

**Comment by roadbearstudios** [comment]
Beste relatie,

Van zaterdag 23 juli t/m zondag 14 augustus heb ik vakantie. Ik zal in deze periode mijn e-mail maar sporadisch lezen. Voor dringende zaken kun je me bereiken op mijn mobiele telefoonnummer. Vanaf maandag 15 augustus pak ik openstaande zaken weer op.

Met vriendelijke groet,

Rene Diekstra
Roadbear Studios
