### ISSUE TITLE
Support Gnome App indicator in the Top panel

### ISSUE THREAD

**Issue by pled** [laurent22/joplin#580]
### Operating system
- Linux Ubuntu 18.04

### Application
- Desktop

Running Joplin-1.0.96-x86_64.AppImage, the option to display icon in the notification zone does not work with GNOME Shell 3.28.1. (as mentionned, it does work with any DE).
### More information :
Because Ubuntu is the most Linux desktop used, and because Ubuntu is now using Gnome as DE, it would be nice to have Joplin icon in the top panel once started, along with basic menus, etc...
Icon in the left bar (launchbar) should only be present when Joplin window is open.
(just like Tomboy does actually).

**Comment by foxmask** [comment]
Not everybody will agree with "the most linux desktop used" 
however this should be available for https://www.freedesktop.org/wiki/  thus gnome xfce kde and so on will be able to get it.
At least it's in the "notification zone" with XFCE 
![sans titre](https://user-images.githubusercontent.com/208212/40838821-13bf5858-65a0-11e8-842d-d0e94ce7914e.png) (we can see the **blue** J letter on top)

**Comment by foxmask** [comment]
may be duplicate with #86

**Comment by pled** [comment]
Hmm don't think so.  [#86](https://github.com/laurent22/joplin/issues/86) is about icon missing in the launchbar (left bar), which is resolved by StefanTT comment, adding to appimagekit-joplin.desktop file the following line :
StartupWMClass=Joplin

**Comment by pled** [comment]
Hmm don't think so. [#86](https://github.com/laurent22/joplin/issues/86) is about icon missing in the launchbar (left bar), which is resolved by StefanTT comment, adding to appimagekit-joplin.desktop file the following line :
StartupWMClass=Joplin

**Comment by Stele77** [comment]
Wasnt there all the fuzz about GNOME disabling the App indicators? 
I use a GNOME shell extension to get them back:
https://extensions.gnome.org/extension/1497/topicons-redux/
It is maintained by Pop_OS distro. There are some other extensions, but this should be the must up to date and best maintained.
So AFAIK this is GNOME ripping out useful features, not a Joplin specific problem.
Please correct me if i am wrong though.

**Comment by pled** [comment]
It's fixed now.
