### ISSUE TITLE
Inline HTML bug after toggling editors 

### ISSUE THREAD

**Issue by stephanoskomnenos** [laurent22/joplin#5800]
## Environment

Joplin version: 2.5.12
Platform: Windows x86_64
OS specifics: Windows 11

## Steps to reproduce

1. Open a markdown file with inline HTML.
2. Click 'toggle editor' to enter WYSIWYG mode.
3. Make some random changes.
4. Switch to source code mode.
5. Then we can see that HTML labels like `<image>`, `<strong>` has been changed to markdown format like `![img](link)`, `**txt**`, and cannot be displayed properly.

Before
![屏幕截图 2021-11-28 163542](https://user-images.githubusercontent.com/24674127/143735455-90a382e6-2696-4f20-8819-f23a56740155.png)

After
![屏幕截图 2021-11-28 162720](https://user-images.githubusercontent.com/24674127/143735256-60ffefba-7ae7-41d4-af6d-a35970756349.png)

Before
![屏幕截图 2021-11-28 163332](https://user-images.githubusercontent.com/24674127/143735393-d30a64b3-01f0-43de-90b3-260dbfb10641.png)

After
![屏幕截图 2021-11-28 163106](https://user-images.githubusercontent.com/24674127/143735323-aa5ebc17-ed22-4f33-9afb-09fa2e74a0cc.png)

## Describe what you expected to happen

The inline HTML should be kept and displayed properly.

## Logfile

No relevant event in debug logs. Here is the only warning message.

```
DevTools failed to load source map: Could not parse content for file:///C:/Users/Lin/AppData/Local/Programs/Joplin/resources/app.asar/gui/note-viewer/pluginAssets/mermaid/mermaid.min.js.map: Unexpected end of JSON input
```

**Comment by so1arin** [comment]
I confirm.
After placing in the editor with tags, switching to a regular editor, making several random changes and switching back to the editor with tags, all changes are reset to the usual selection.
**Before** 
`<mark style="background-color: #FFFF00 ">**GET**</mark> \- вид запроса;<br>
<mark style="background-color: #00FF00 ">**https://yandex.ru/**</mark> \- ресурс к которому мы обращаемся с запросом;<br>
<mark style="background-color: #00FFFF ">**HTTP/1.1**</mark> \- версия протокола. 1С умеет пока только с версиями 1.0 или 1.1. Сеть массово переходит на 2.0.<br>
<mark style="background-color: #A9A9A9 ">**Серым**</mark> выделены заголовки запросов<br>`
**After**
`==**GET**== \- вид запроса;
==**https://yandex.ru/**== \- ресурс к которому мы обращаемся с запросом;
==**HTTP/1.1**== \- версия протокола. 1С умеет пока только с версиями 1.0 или 1.1. Сеть массово переходит на 2.0.
==**Серым**== выделены заголовки запросов`

**Comment by so1arin** [comment]
Hello. The described situation is also observed in the latest version of 
the application. The error has not been fixed.

"github-actions[bot]" ***@***.***> 9 января 2022 г. 09:05:51 
написал:
