### ISSUE TITLE
Links in mermaid diagrams don't work

### ISSUE THREAD

**Issue by jg1969** [laurent22/joplin#5801]
Creating a mermaid diagram, as follows:
> \`\`\`mermaid
> flowchart
> Test
> click Test href "http://goo.gl/" "Tooltip"
> \`\`\`
Clicking on the "**Test**" box does not open the browser.  This is because the generated SVG contains an anchor element with `xlink:href` attribute (rather than the more usual `href`).

It looks like the following line explicitly tests for `href` and should be extended to test for `xlink:href` as well.
https://github.com/laurent22/joplin/blob/f224282a27a10982fda163827b8a97bb37bd87f3/packages/app-desktop/gui/note-viewer/lib.js#L204
e.g. simply adding another line below line 204:
```js
if (anchor.getAttribute('xlink:href')) webviewLib.options_.postMessage(anchor.getAttribute('xlink:href')); 
```

I did not test the above solution as don't have bandwidth to download/build the app.   I was able to confirm that adding `href` attribute to the anchor (in developer tools) solves the issue.

My investigation was on Windows 10, with:
> Joplin 2.5.10 (prod, win32)
> 
> Client ID: 1de3df5a8c83471badb9cb89e2642b40
> Sync Version: 3
> Profile Version: 39
> Keychain Supported: Yes
> 
> Revision: b80242d

**Comment by tessus** [comment]
I will try to reproduce and create a PR.

**Comment by tessus** [comment]
Ok, we can't add it to the file you suggested, because that file is generated from `packages/lib/renderers/webviewLib.js`.
But the fix itself works. Thanks.
