### ISSUE TITLE
No need of running `npm run watch` in root of project

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [laurent22/joplin#5806]
This [section](https://github.com/laurent22/joplin/blob/dev/BUILD.md#watching-files) of `BUILD.md` explains to run `npm run watch` in the root of the project to watch & rebuild the Typescript files you have changed . 

I think there is no need of running the watch command in the root of the project because every package (inside `packages` folder) has its own `npm run watch` command . Instead of running in the root which compiles all the typescript files in whole project (which increases load on CPU) we can simply run `npm run watch` on those directories only whose files we have changed . 
Even may be my explain is wrong here , I think it's good to mention it in the section that we can also do so for each package .

If this issue is legitimate , I will like to make a PR for it .
Thanks

**Comment by roman-r-m** [comment]
What if you need to change files both in `lib` and say `app-mobile` (pretty common situation in my experience)?
Would you have to remember to run `npm run watch` twice?

**Comment by Rishabhraghwendra18** [comment]
`app-mobile` uses `lib` as a package . It's not directly imported from the directory . I think making changes in `lib` doesn't show it's effect in `app-mobile` . Until you made some changes and then published those changes to some private package registry and then using it in the `app-mobile` .

**Comment by laurent22** [comment]
As Roman said, it's needed when modifying multiple package.
