### ISSUE TITLE
Android Error File sync : Attempt to get length of null array

### ISSUE THREAD

**Issue by pled** [laurent22/joplin#581]
### Operating system
- Android (LineageOS 7)

### Application
- Mobile

I am unable to sync the android app using "File system" type. The error is 
Error: Error: Attempt to get length of null array. Path : /storage/3865-6232/Android/data/com.nutomic.syncthingandroid/files/Joplin

![joplin-error](https://user-images.githubusercontent.com/2879483/40795951-d975c7aa-6503-11e8-8c45-56accc0be58e.jpg)

Where 3865-6232 is my SD-CARD, and the directory the one from Syncthing where Android allows r/w. Using similar directories to sync other apps without issue (ie tomboy).

**Comment by robojeb** [comment]
I am having the same problem. 
My path is "/storage/emulated/0/Download/Sync/joplin_notes"

**Comment by montgomeri** [comment]
You have to add storage permission for the app in the android settings manually.
Otherwise the app wont have any permission to read/write the sdcard.

A prompt should be added to ask the user for that permission if denied.

**Comment by laurent22** [comment]
Yes the last time I checked, the React Native API to request permissions was buggy, so instead for now I've added the info to the config screen.

**Comment by pled** [comment]
On my side, I moved to nextcloud sync, everything works well.
I confirm that looking at the app permissions, "stockage" was not set by default (LineageOS 7).
