### ISSUE TITLE
Joplin desktop on Macos : can't paste without formatting

### ISSUE THREAD

**Issue by Lycopode** [laurent22/joplin#5812]
I'm using Joplin 2.5.12 on Macos 12.0.1.

If I copy text and paste it in a Joplin notebook on the rich text editor, it keeps the formatting. I can't find any shortcut that says how to paste without formatting. Only "Paste" is available. I tried to use CMD + Shift + P but it does nothing. 

<img width="1037" alt="Screenshot 2021-12-01 at 12 13 20" src="https://user-images.githubusercontent.com/92934234/144224816-80429d40-773a-4ef9-b471-e309d01ab65d.png">
<img width="380" alt="Screenshot 2021-12-01 at 12 13 28" src="https://user-images.githubusercontent.com/92934234/144224822-320b886f-fa82-4618-97d2-6c6d9bd5d7e7.png">

**Comment by laurent22** [comment]
Cmd+Shift+V works fine for me on macOS.

**Comment by Lycopode** [comment]
@laurent22 following your comment I have tried to change my keyboard layout to azerty and it indeed works now. I'm actually using bépo (the french equivalent of dvorak), and it doesn't work on bépo. The letter "U" is the equivalent of "V", so if I use bépo I do CMD + U to paste, and it works. But if I do CMD + SHIFT + U it doesn't do anything. If I do CMD + SHIFT + V (it's a '.' on bépo) it does work. Maybe some other exotic keyboard layouts have this issue as well on joplin?

**Comment by Lycopode** [comment]
Edit : I just tried on dvorak and it has the same issue

**Comment by Daeraxa** [comment]
Other issues have been raised before about non en-US keyboard layouts - for example the default keybinding of ctrl + ` doesn't work on ISO en-GB.

**Comment by Lycopode** [comment]
Maybe it would be best to add "paste without formatting" to the menu then, because if an action is on a menu on mac you can customize its shortcut on the System Preferences

**Comment by Daeraxa** [comment]
I don't recall a consensus, it was near the start of me using Joplin (and markdown) so I just got more used to manually typing tags rather than using shortcuts so I kind of forgot about it.
See:
https://github.com/laurent22/joplin/issues/4284 (and other related issues that mentioned it)
