### ISSUE TITLE
Error: Could not upgrade from version 0 to version 1: MKCOL .resource/: Unknown error 2 (404):

### ISSUE THREAD

**Issue by s1-ranjan** [laurent22/joplin#5814]
## Environment

Joplin version: 2.6.2 (prod,linux)
Platform: Linux
OS specifics: Linux Mint

## Steps to reproduce

When tried to sync joplin notes with Nextcloud 21.0.7 this error occurred.

## Describe what you expected to happen
I was expecting Joplin would have successfully synced my notes using Nextcloud.

## Logfile
[log.txt](https://github.com/laurent22/joplin/files/7638851/log.txt)

**Comment by JackGruber** [comment]
This is a Nextcloud error, because `404` is a server error and the server response with `Oops! We couldn't find the page that you're looking for` for all requests.

**Comment by dsaderholm** [comment]
Did you guys ever come up with a solution for this?

**Comment by sambal0** [comment]
> Did you guys ever come up with a solution for this?

Same here
