### ISSUE TITLE
To-do note set alarm save and cancel options are not visible on Android 12 with Joplin 2.6.3

### ISSUE THREAD

**Issue by Reteip-v** [laurent22/joplin#5817]
## Environment

Joplin version: 2.6.3
Platform: Android
OS specifics: Android 12

## Steps to reproduce

1. Create New to-do
2. From the menu, choose Set alarm
3. Only a 'SET DATE' button is visible

## Describe what you expected to happen
Options for save or cancel should be visible, however the rest of the dialog is completely white regardless of  what theme is being used.

## Logfile

![Screenshot_20211202-202744](https://user-images.githubusercontent.com/45321919/144407037-723d70c2-8992-4664-8f0c-f5ef88108559.png)

**Comment by laurent22** [comment]
Please try latest pre-release https://github.com/laurent22/joplin-android/releases/tag/android-v2.6.4

**Comment by Reteip-v** [comment]
Yep, all good now. Thank you!
