### ISSUE TITLE
[Feature Request] Sort by Due Date / Alarm Date

### ISSUE THREAD

**Issue by BeatLink** [laurent22/joplin#5819]
This feature request has already been discussed on the forum here: https://discourse.joplinapp.org/t/feature-request-todo-expiration-dates-for-sorting/2867/7 and here https://discourse.joplinapp.org/t/feature-request-sort-reminders-by-reminder-date/21513, here https://discourse.joplinapp.org/t/feature-request-add-sort-option-by-alarm/5926 and somewhat here https://discourse.joplinapp.org/t/to-do-due-dates/14955 and here https://discourse.joplinapp.org/t/global-todo-list/2592/29.

As you can see, this feature request is quite popular 😄 

The basic premise would be to allow tasks to be sorted by the due date/alarm, both on mobile and desktop. This would allow tasks in notebooks, tags and other filters to be processed in a chronological order and would be just as, if not more useful than sorting tasks by their updated and created date. 

The implementation should be straightforward. A new menu item in the view menu that sorts notes/tasks by due date, in addition to the existing creation date, updated date, custom sort order and title. This should then affect sorting across notebooks, tags and search filters. A settings checkbox could determine whether tasks/notes without due dates/alarms would be saved to the top or bottom. 

Please let me know what you think about implementing this feature.

**Comment by shryasss** [comment]
@BeatLink  I would like to work on this. Can you assign me and send any relevant starter resource I need to check out?

**Comment by Daeraxa** [comment]
There is no assigning of tasks, if you want to work on this and contribute then you need to have a look at https://github.com/laurent22/joplin/blob/dev/CONTRIBUTING.md

**Comment by BeatLink** [comment]
Keep this open

**Comment by BeatLink** [comment]
bump

**Comment by thomaschampagne** [comment]
Keep this open?

**Comment by BeatLink** [comment]
Hey, havent used joplin for a while and i'm not sure id be able to help. Sorry

**Comment by thomaschampagne** [comment]
"[laurent22](https://github.com/laurent22) reopened this [3 hours ago](https://github.com/laurent22/joplin/issues/5819#event-11767249865)"

Yeah 👍

**Comment by ghost** [comment]
+1

I believe this is the one missing feature that would make this app completely perfect for my use cases. Sorting by due date please!
