### ISSUE TITLE
412 Error on Sync

### ISSUE THREAD

**Issue by nevetS-718** [laurent22/joplin#5820]
## Environment

Joplin version: 2.6.3
Platform: Chromebook (Play Store)
OS specifics: ChromeOS 94.0.4606.114

## Steps to reproduce

1. Enter sync credentials for Joplin Server (Beta)
2. Check synchronization configuration

## Describe what you expected to happen

The expected result is a successful connection, however it returns a 412 error with some html. Syncing to this server works on my PC and iOS device.

## Logfile

Log: ![log](https://img.nevets.tech/t8wet1.png)
I can’t access the debug report.

**Comment by laurent22** [comment]
you need to upgrade the server

**Comment by calvinbui** [comment]
@laurent22 i'm using the latest stable server version (2.5.1) with the latest stable android version from the play store (2.6.3) and still getting this error.

When will a 2.6 stable version be released?
