### ISSUE TITLE
Toggle development tool menu item "glitch"

### ISSUE THREAD

**Issue by antoniopaolini** [laurent22/joplin#5825]
Hello, 
this is a small bug, very low urgent, but present since I use Joplin, about two years.

Toggle development tools must *toggle* the development tools panel.
However, if I close the panel manually, the command in the HELP -> "Toggle Development tools " menu does not reopen the panel the first time, as if it had not noticed that it had been closed by the close button instead. 
At the next toggle, in fact, it reopens.

By "manually" I mean by pressing this button.
![image](https://user-images.githubusercontent.com/60228211/144647988-4af0bd82-f54d-4229-8640-2eee6596ed15.png)

## Environment

Joplin version: 2.6.2
Platform: Windows
OS specifics: Win 10, Joplin Portable

## Steps to reproduce

1. Menu  Help -> Toggle Development tools open the Development tool 
2. Repeat the previous operation to closes the panel.
3. Repeat the previous operation to reopen the panel.
4. Close the Tools Panel by the close button 
5. Repeat MENU Help -> "Toggle Development tools" does not reopen the panel.
6. Repeat MENU Help -> "Toggle Development tools";this time the panel was reopened.

## What I expected to happen

Toggle development tools must *toggle* development tools panel.

**Comment by Daeraxa** [comment]
I've been battling with this a bit recently myself.
Apps I use where I use this same feature (VSCode and Atom) both either watch the state of the tools or check for it when running the command).

**Comment by antoniopaolini** [comment]
Bump!

**Comment by antoniopaolini** [comment]
Yet present.

**Comment by antoniopaolini** [comment]
yet present

**Comment by antoniopaolini** [comment]
yet present
