### ISSUE TITLE
Wysiwyg editing window Flash White, when switching notebook or searching notes

### ISSUE THREAD

**Issue by special0star1** [laurent22/joplin#5836]
## Environment

Joplin version: 2.5.8
Platform: PC
OS specifics: Win10 

## Steps to reproduce

1. Wysiwyg editing window Flash White, when switching notebook or searching notes
2. MarkDown edit window does not have a similar problem

![JOPLIN](https://user-images.githubusercontent.com/92930690/144987887-b73b0175-77bb-4a28-8288-0a93c8fca256.gif)

## Describe what you expected to happen

Wysiwyg Edit window color is the same as the theme color, when switching notebooks or searching for notes

**Comment by CalebJohn** [comment]
This has been fixed in https://github.com/laurent22/joplin/pull/5793 and will be available in the next release.
