### ISSUE TITLE
Infinite sync loop

### ISSUE THREAD

**Issue by adraoo** [laurent22/joplin#5837]
## Environment
OS specifics: macos 11.6
Joplin for Desktop
Copyright © 2016-2021 Laurent Cozic
Joplin 2.5.12 (prod, darwin)
Client ID: 7ef90cc8a97a478daba4d136e023325c
Sync Version: 3
Profile Version: 39
Keychain Supported: Yes
Revision: 884b86f

android app : Joplin 2.6.3, database v41, FTS enabled

## Steps to reproduce
- Using dropbox for sync, encrypting the notes, the macos application and the android app.
- One notebook "Notes" only, a fraction of the notes associated with it, the others not associated with any note.
- On macOS, taking all notes and moving them to the notebook "Notes.

## Describe what you expected to happen
A infinite sync starts there, where all notes are updated on one frontend then the other.

Notes stay available and the regular Joplin functionalities are available.

**Comment by diogogomes** [comment]
I confirm the same issue with the version 2.6.1, Sync Version 3 and using Nextcloud to sync. This issue also makes Joplin slow and using more than 100% of a cpu core.

Joplin 2.6.9 (prod, linux)
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Debian Bookworm (testing) with Gnome (Wayland)

**Comment by diogogomes** [comment]
I resolved my issue by disabling the Untagged extension.

Check if you have the same extension activated.
