### ISSUE TITLE
Strange code block rendering in edit panel when it is in a list with multiple paragraph

### ISSUE THREAD

**Issue by antoniopaolini** [laurent22/joplin#5838]
Hello, 
when I put a code block in a list I see a strange rendering in the edit view. The code block is splitted in lines.
This happens when I put the code block in a list and the item text is so long that I have to split it into two or more paragraphs.
As you can see in the picture below if the list iten is a single paragraph (code block at bottom) the code is correctly rendered in the edit panel.

![image](https://user-images.githubusercontent.com/60228211/144997615-8aa0f300-9061-48b6-9b24-815c786f3128.png)

I don't know if this is a bug or my use is very "strange", nor I know if there's a standard way to do this.
I put two tab in front of the code block, as I read on this site: https://www.markdownguide.org/basic-syntax/#code-blocks-1

## Environment

Joplin version: 2.6.2 (portable)
Platform: Windows 
OS specifics:  Windows 10

## Steps to reproduce
I'll attach the file. 

Bye.

Example: [Esportazione.md](https://github.com/laurent22/joplin/files/7666921/Esportazione.md)

**Comment by antoniopaolini** [comment]
The issue is yet present.

**Comment by antoniopaolini** [comment]
yet present

**Comment by antoniopaolini** [comment]
yet present in 2.7.15

**Comment by Daeraxa** [comment]
My assumption is that it is because you have indented code blocks and code fences mixed up because of your indentations.

To me it looks like the first code block isn't actually a fenced code block but three lines of indented code where only the middle one is actually rendered on the right.

The second one works normally as it is just part of a list.

You should use indented code blocks *or* fenced code blocks, not a mix between the two.

**Comment by antoniopaolini** [comment]
I'm not sure I understood, but the stucture should be the same.  Also the first code block is part of a (unordered) list and actually the row "nel nostro caso" is rendered correctly, not as indented code, in the preview pane, as the code,
I can understand why the first code, part of a list, is rendered bad in the editor pane, while the second code, partof another list, block is rendered correctly.

**Comment by antoniopaolini** [comment]
I found the point. 
The solution to get the right formatting in the editor is to indent the other lines as well.
It seems to work for the indented code, but  it messes up the next list item (**Titolo**.....)
![image](https://user-images.githubusercontent.com/60228211/159433857-7a688d15-3426-44cd-95ad-cff54c97302e.png)
and 
![image](https://user-images.githubusercontent.com/60228211/159435328-6ee13b86-e780-4a77-b31b-450f768be40f.png)

**Comment by antoniopaolini** [comment]
yet present
