### ISSUE TITLE
IOS failed to synchronize via WebDAV

### ISSUE THREAD

**Issue by caifenglin** [laurent22/joplin#5839]
In windows, there is no problem synchronizing through WebDAV. When the URL in WebDAV has a port, IOS synchronization fails and it can succeed without a port

## Environment

Joplin version: 
Platform: iPhone12 iOS
OS specifics: ios 14.8

## Steps to reproduce

1. WebDAV is accessed through a tunnel, and the URL contains the port information
2. Synchronization is normal under win
3. Synchronization failed under IOS

**Comment by caifenglin** [comment]
It should have nothing to do with the port. I have tested that there is no problem with the PC, but the IOS WebDAV fails to connect through the intranet or tunnel. The PC can access the same URL normally

**Comment by caifenglin** [comment]
When the network is directly connected, both IOS and PC are normal

**Comment by JackGruber** [comment]
I use also on iOS devices a WebDav URL with a port and have no problem. 
Therefore, the problem lies elsewhere, more likely at the tunnel.

**Comment by caifenglin** [comment]
Through the intranet penetration domain name access, PC can, IOS can't

**Comment by caifenglin** [comment]
According to the truth, why can a PC fail IOS when accessing through a tunnel?

**Comment by caifenglin** [comment]
If you need tunnel testing, I can help, but I need your intranet IP

**Comment by caifenglin** [comment]
You can provide tests through wangchuanyun. You can get a free 1m tunnel by registering. I hope it can help you. The official website is http://www.neiwangchuantou.net/

**Comment by caifenglin** [comment]
Of course, you can also use FRP
