### ISSUE TITLE
force re-auth to Synchronization target

### ISSUE THREAD

**Issue by lazylionca** [laurent22/joplin#584]
### Operating system

- Windows

### Application

- Desktop

Hey bud, few minor annoyances.

1. On my windows client I regularly have to force a re-auth to Onedrive by switching targets, saving, then switching back and saving again. Otherwise Sync fails with error 'service not available'.

2. The sync failure doesn't give much of an readable error. Just a splatter of what looks like html, or some type of markup tags.

3. On the config tab, Synchronisation should be spelled Synchronization.  

Thanks Man. Keep up the great work!!

Roy

**Comment by laurent22** [comment]
Could you post the error message you're seeing?

**Comment by lazylionca** [comment]
![2018-06-01 12_41_51-joplin](https://user-images.githubusercontent.com/26557053/40864242-4ae2585c-65b0-11e8-9afa-07e0fab4f6f3.png)

**Comment by laurent22** [comment]
It seems the service is just temporarily unavailable. Doesn't it work if you try a few minutes (or maybe hours) later?

**Comment by lazylionca** [comment]
Trouble is the error keeps popping up and doesn't go away on its own for whatever reason.

**Comment by laurent22** [comment]
Closed as duplicate
