### ISSUE TITLE
Feature Request: Move Tags to seperate pane

### ISSUE THREAD

**Issue by BeatLink** [laurent22/joplin#5843]
I propose a change to the UI, to move the tags from the notebook panel into its own panel. This would allow for greater flexibility in the arrangement of the application layout by users.

**Comment by Daeraxa** [comment]
Github is for bugs and is not the place for feature requests.
There is an open forum conversation on this topic - https://discourse.joplinapp.org/t/removing-tags-from-the-sidebar-in-desktop-app/21276

**Comment by BeatLink** [comment]
Still not resolved. Keep this open bot.

**Comment by BeatLink** [comment]
Bump
