### ISSUE TITLE
Code no longer scrolls when using 3 backtick ( ` ) code blocks.  

### ISSUE THREAD

**Issue by hffaust** [laurent22/joplin#5847]
- When using code that is surrounded by 3 backticks to make a code block that spans multiple lines there is no longer a scrolling bar to keep the code confined to the Code block in rendered view. Code is just rendered in one continuous line even if it is too large to fit in the code box, it just expands beyond the boundaries. 

![image](https://user-images.githubusercontent.com/15644021/145504359-acd2d4fb-d37a-4a21-b80a-8869c233bcdc.png)

## Environment

Joplin version: 2.5.12 (sync version 3; profile version 39... if that matters...)
Platform: OS Version
OS specifics: Mac & Windows

## Steps to reproduce

1. Use 2 sets of 3 backticks (  ```  ) to enclose code that expands multiple lines inside a code block.  
2. Make a line really long ( 200 chars or so...).
3. Switch from editing view to Rendered view and you will see it expands beyond the boundaries of the code box. It didn't used to be this way in the last version I was running before updating (2.2.x I believe).

## Describe what you expected to happen
- The code blocks used to have scroll bars at the bottom to allow you to scroll for code that was longer than you could see in the width of your screen. Now the scroll bars are gone and looking at notes in the 'rendered' view you can see where code just keeps going past the boundaries of the code block box. 

## Logfile
- No error message rendered but I can attach a log file later if needed.

**Comment by CalebJohn** [comment]
https://github.com/laurent22/joplin/issues/5740
