### ISSUE TITLE
Evernote import enhancement: Convert internal links to Joplin note links

### ISSUE THREAD

**Issue by pmottishaw** [laurent22/joplin#585]
### Operating system

- Windows
- macOS
- Linux

### Application

- Desktop
- Terminal

When importing .enex file it would be great if the internal links to other Evernote notes are converted to Joplin note links if the target note has also been imported. It may be possible to do this by adding the Evernote GUID as metadata to an imported note. A second pass then could search for all links in imported (possibly all notes) and convert them to the correct Joplin note link.

An additional benefit could be to link back to Evernote for each imported note using the GUID. Very useful during the migrations phase.

**Comment by laurent22** [comment]
Do you have an example of Enex file that contains internal links? (I didn't even know Evernote had this feature)

**Comment by pmottishaw** [comment]
Here is a simple, but real example. I copied a few example notes into a
notebook and then created a note with a bullet list of links to all the
other notes. I could create something more complex if that was useful. By
the way, in using Evernote for nearly 10 years I have found internal links
one of the most useful ways of organising notes (more useful than tabs for
example).

I checked that the enex imports into Joplin. It does, but the bullet points
seem to get 2 new lines before the link. Any idea why this might be?

A very useful feature of the current Joplin implementation is that the
internal Evernote links in imported notes currently take me to the correct
note in the Evernote (I use Windows 10 and I recall having to register an
Evernote protocol so that Windows recognises these types of links). This is
useful if you are slowly or partially migrating from Evernote to Joplin and
want links to notes that have not been imported yet to work.

I don't know anything about how Joplin is implemented (so this may not make
sense), but the implementation ideas that came to mind are

   1. When a note is imported from Evernote its unique Evernote GUID should
   be included in its meta data in Joplin.
   2. Joplin should provide a tool that will check if this GUID is used
   anywhere in a link in a Joplin note and convert it to the correct internal
   Joplin link.
   3. It may be best to keep the import and conversion separate, so that
   the user can choose whether links are converted or not... need to think
   about this.
   4. It may be useful to be able to do link conversion on selected notes
   at a later date ... not sure about this.


By the way, it would be good to have internal links in a different colour
from external links. It makes it easier to navigate. It is also incredibly
useful if a "back button" appears after you have clicked on a internal
link. Happy to say some more about this in the forum if that would be
helpful.

Thanks for an amazing set of applications.

**Comment by laurent22** [comment]
How do you create a link to another note in Evernote? That's the part I'm missing.

**Comment by pmottishaw** [comment]
In the windows app it is "Copy Internal Link" under the "Note" menu or when
you right click on selected note, keyboard shortcut Ctrl-Alt-L.

In the web app it is "copy notelink" under the "..." menu.

In the android app it is "Copy internal link" when you are looking at a
note under the "three dots menu".

I don't know about Apple apps...




Mobile 07793989446
Email peter.mottishaw@gmail.com

**Comment by kiuuik** [comment]
As far as I see this can't work with enex files (and i wouldn't give a third party app that uses the evernote api access to my notes ....)

- the structure of internal links contains the userid and noteguid.
- the enex file definition doesn't contain the noteguid. I also checked an enex file of mine and didn't find any guid in it.

A similar conclusion was drawn in a similar discussion for a different markdown-software: https://www.reddit.com/r/bearapp/comments/766l9o/internote_links_from_evernote_import/

----

> How do you create a link to another note in Evernote? 

There are two versions: one that links to the website (new type, created as described above) and an older version that starts with (`evernote:///view/`). You create the latter type on the windows desktop app by right clicking on the note and in the context menu choose "copy internal link" WHILE you press ctrl. For the ios mobile client I think I saw some obscure solutions last year but can't find them and don't know if they still work.

**Comment by laurent22** [comment]
Yes I've just checked and indeed since Evernote doesn't export the note IDs, the links to notes cannot be preserved. Unfortunately another reason not to use Evernote since they don't allow exporting the complete data.

**Comment by kiuuik** [comment]
My conclusion might have been premature: There's a third party client named [nixnote2](https://github.com/baumgarr/nixnote2) for linux. I trust it because it's bundled with many popular linux distros. nixnote2 has its own export format named nnex which is very similar to evernotes enex but also includes useful entries like `<Guid>` and `<NotebookGuid>`. This might help.

Here's the structure of a nnex file. I removed some personal information.

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE NixNote-Export>
    <nixnote-export version="2" exportType="export" application="NixNote" applicationVersion="2.x">
        <Note>
            <Guid>1a59f8b5-a06f-49a8-8437-7493cfd612e9</Guid>
            <Title>title</Title>
            <Content><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">
    <en-note><div>some content</div></en-note>]]></Content>
            <ContentHash>voc4wrnu904cw09ucw8828292929292d</ContentHash>
            <ContentLength>674</ContentLength>
            <Created>1536004382121</Created>
            <Updated>1536004392432</Updated>
            <Active>true</Active>
            <UpdateSequenceNumber>9240</UpdateSequenceNumber>
            <NotebookGuid>672ab04c-9e67-47d4-adaf-707e2ee028fb</NotebookGuid>
            <Attributes>
                <Author>a@a.de</Author>
                <Source>desktop.win</Source>
                <SourceApplication>evernote.win32</SourceApplication>
            </Attributes>
            <Dirty>true</Dirty>
        </Note>
    </nixnote-export>

**Comment by pmottishaw** [comment]
It is disappointing that Evernote does not export the guid. Links are the
main way I organise notes; tags always seem a bit vague. The nixnote option
is promising, but adds some complexity.


Mobile 07793989446
Email peter.mottishaw@gmail.com
