### ISSUE TITLE
Joplin UI Display Issues When Window is in a Smaller Resolution

### ISSUE THREAD

**Issue by magic-ian** [laurent22/joplin#5851]
## Environment

Joplin version: 2.5.12
Platform: Linux Debian Bookworm 
OS specifics: Running on Pinephone with Mobian optimizations (would also apply to Librem 5, and other mobile Linux platforms like Steam Deck)

## Steps to reproduce

1. Download Joplin Flatpak, Snap, Appimage, or build from source onto a mobile Linux device (has a small 720p portrait resolution, portrait mode, and up to 250% scaling)
2. Open Joplin
3. Sadface :(

## Describe what you expected to happen
Ideally the app would be responsive to show only one sub-menu at a time when there is a small resolution, similar to the Android/iOS app. Right now it displays notebooks, notes, markdown editor, and preview all at once.

![Screenshot from 2021-12-11 17-13-45](https://user-images.githubusercontent.com/10818935/145693391-23a7236c-7cb5-4174-b0b5-24b6fb1798c5.png)

**Comment by graphit0** [comment]
Looks like a feature suggestion to support mobile desktop systems. Feature suggestions first go to the forum. Do you mind opening the topic there instead of this issue?

**Comment by tomasz1986** [comment]
> Looks like a feature suggestion to support mobile desktop systems. Feature suggestions first go to the forum. Do you mind opening the topic there instead of this issue?

This really isn't only about mobile systems. I use Joplin on a 1280x1024 screen and the GUI doesn't play nicely with it already (e.g. the notebook and note lists are too wide, leaving too little space for the note itself). The narrower the screen gets, the more difficult the GUI becomes to use. I would be nice if the default layout automatically adjusted itself following the available screen size (at least on the first run).

**Comment by graphit0** [comment]
> It would be nice if the default layout automatically adjusted itself following the available screen size (at least on the first run).

Ok, thanks for the idea but I believe OP would be just as happy to get the mobile react app on a certain desktop distro for a niche device. So, "auto layout of the desktop app" feature is quite different, isn't it?

Still, feature requests ideally need to be discussed on the forum first. Here, we have very small number of users to give early feedback on a potential feature.

So far, assuming you don't change the resolution that often, to achieve something similar you can use "zoom out" (ctrl+dash).

**Comment by tomasz1986** [comment]
> Ok, thanks for the idea but I believe OP would be just as happy to get the mobile react app on a certain desktop distro for a niche device. So, "auto layout of the desktop app" feature is quite different, isn't it?

Yeah, the OP was concentrated on mobile screens specifically. On the other hand, what I'm trying to say is that Joplin doesn't play nicely with non-wide screen in general 😉. I'd say the two aren't exclusive though, as mobile screens are also non-wide screens, and the OP is using the same desktop application too.

**Comment by magic-ian** [comment]
The scenario applies to larger resolution screens too. A use case would be when Joplin is snapped to one half of the screen, displaying 3-4 vertical containers is too crowded for the content displayed. 

[NewsFlash](https://gitlab.com/news-flash/news_flash_gtk) does a good job of managing this. It has 3 containers by default when fullscreen, goes down to 2 when half screen, and 1 when quarter screen. It also has overlap width zones for when it switches between these. E.g. when you stretch the window up from 1/4-1/3 it keeps 1 container column, but when you stretch the window down from 1/2-1/4 it keeps 2.
