### ISSUE TITLE
UI problems for setting alarms (Android 9)

### ISSUE THREAD

**Issue by rogerbordini** [laurent22/joplin#5852]
Joplin version 2.6.3
Android 9
Samsung Galaxy 8

After choosing the day and time to set the alarm for a To-Do, no option is displayed for confirmation and the screen seems to get stuck in this menu (image attached). It is possible to return to the main menu, but no other option is shown in this menu than the one shown in this screenshot.

![Screenshot_20211212-143403_Joplin](https://user-images.githubusercontent.com/7660777/145725804-196dfe6d-4304-4652-84f3-d0a5893b6f2c.jpg)

**Comment by laurent22** [comment]
Please try https://github.com/laurent22/joplin-android/releases/tag/android-v2.6.4
