### ISSUE TITLE
Sync from android to empty sync point

### ISSUE THREAD

**Issue by aclifton314** [laurent22/joplin#5857]
## Environment

Joplin version: 2.6.3
Platform: Android
OS specifics: Android 12

## Steps to reproduce

1. Delete sync target files
2. Try to sync from android

## Describe what you expected to happen
I was having some issues with what was being synced to my desktop app and my android app. I deleted the sync point target (a Nextcloud server). The notes and notebooks on my android device are the correct versions. I tried to sync from my android device but I get a response:
```
Last error: Fail-safe: Sync was interrupted because 100% of the data is about to be deleted. To override this behavior disable the fail-safe in the sync settings.
```
I'd like to upload the versions of the notes and notebooks that are on my android device to the sync point, then sync my desktop app to the sync point so everything is up to date across both apps.

## Logfile
See attached.
[syncReport-1639437402801.txt](https://github.com/laurent22/joplin/files/7707541/syncReport-1639437402801.txt)

**Comment by Daeraxa** [comment]
This isn't really a bug, what you have actually done (from the eyes of the mobile client) is delete all of your notes intentionally so it is trying to do the same (and you were saved by the fail-safe).
Your best bet is probably to sync to a different sync target type if possible (dropbox for example) then take the contents of that sync target and migrate the whole thing to your nextcloud server (a related example with instructions can be seen here - https://joplinapp.org/faq/#all-my-notes-got-deleted-after-changing-the-webdav-url) before re-enabling the sync.

You should do a number of backup related tasks before you touch anything further though.
- Backup your desktop profile + perform a JEX export (even if it isn't current it is surely better than nothing if you somehow lost your mobile data)
- Export your joplin profile from your mobile (configuration > export profile). This will create a backup copy of your mobile profile which you can copy to desktop and use if everything else should fail

If you have further questions it is probably better to open a topic on the forums about it as they are generally more active and have more people that can advise on any issues.

**Comment by aclifton314** [comment]
@Daeraxa thank you very much for your reply. I will do as you suggested!
