### ISSUE TITLE
Third heading of shared note is not displayed right with Joplin-Server

### ISSUE THREAD

**Issue by Mr-Kanister** [laurent22/joplin#5860]
## Environment

Joplin version: 2.6.6
Platform: Windows 10

Joplin-Server Version: 2.6.14
Platform: Raspberry Pi OS; Debian 10
OS specifics: Running on ARM -> Using floriders89's Image

## Steps to reproduce

1. Create new note with headings, e.g.
```
# # Heading
## ## Heading
### ### Heading
#### #### Heading
```
2. Share the note via Joplin-Server
3. Check the Link and compare the Headings

## Describe what you expected to happen
The third heading is not correctly "boldend". It's the normal font, just a little bit bigger.

## Screenshot
![Issue](https://user-images.githubusercontent.com/68117355/146065206-f3be82f3-f85b-4366-9958-4ab03c1fc21a.jpg)
![Issue2](https://user-images.githubusercontent.com/68117355/146065343-91977567-fc30-4817-9844-f303df86b133.jpg)

**Comment by laurent22** [comment]
Will be fixed in next release
