### ISSUE TITLE
Fatal Error: Unkown Profile version

### ISSUE THREAD

**Issue by vascowhite** [laurent22/joplin#5865]
## Environment

Joplin version: 2.5.12
Platform: Linux
OS specifics:  Debian Testing with I3wm

## Steps to reproduce

1. Install latest appimage
2. Launch Joplin
3. Look on in shock at this:

![joplinerror_000](https://user-images.githubusercontent.com/874109/146245991-bf90e81a-cc44-48b0-84c6-4599128a5510.png)

## Describe what you expected to happen
Jopllin displaying all my lovely notes

## Logfile

Unable to follow any of the steps at https://joplinapp.org/debugging/ as Joplin will not start.

## Aditional Info

I installed Joplin using the AppImage from the official download URL https://github.com/laurent22/joplin/releases/download/v2.5.12/Joplin-2.5.12.AppImage

This issue seems to be similar to the closed, but unresolved #3437

**Comment by Daeraxa** [comment]
Did you run a 2.6 pre-release client on your profile at any point?

**Comment by vascowhite** [comment]
> Did you run a 2.6 pre-release client on your profile at any point?

You know what, I did. I'm an idiot! I totally forgot I was using the pre-release version.

I shall now download and install the correct version.

Thanks for the prompt reply.
