### ISSUE TITLE
Text covered by keyboard

### ISSUE THREAD

**Issue by juanreppucci** [laurent22/joplin#587]
Hi!
I'm having a problem with long notes o  the Android app; when I try to edit them, the bottom part get covered by the keyboard and I can't find the way to scroll down to see that area and make the edits. 

Also as a suggestion, I would like to see a more evident the separation between notes, maybe a thicker line or something like that.

Thanks a lot for such a great app!
Bests
Juan 

### Operating system
- Android

### Application
- Mobile

**Comment by laurent22** [comment]
This is due to a bug in React Native, it might be fixed in a future release.

**Comment by jony0008** [comment]
@laurent22 I have the same problem. Will it be fixed? I hope so because I really like your app.
