### ISSUE TITLE
Desktop: Export to PDF/HTML file error on Linux

### ISSUE THREAD

**Issue by graphit0** [laurent22/joplin#5873]
The export to pdf/html file stopped working at 2.6.9

## Environment

Joplin version: 2.6.9 
Platform: prod, linux
OS specifics: Kubuntu 21.04

## Steps to reproduce

1. Select any note (including welcome pages packaged with the app)
2. Try to export into PDF or HTML File
3. Wait a few seconds
4. Get the error
![error-2021-12-18_00-15](https://user-images.githubusercontent.com/44114323/146612518-72f3fd8d-f89a-4ba5-941a-948a7a2dcc7b.png)
5. No note export is created at the export path

The text of the error
```
Could not export notes: ENOENT: no such file or directory, open '/export-path/pluginassets/mermaid/mermaid.min.js'
```

## Describe what you expected to happen
A note to be exported to pdf or html file 

## Notes

- The issue is not present at 2.5.12
- Sometimes error changes from mermaid.js to katex
- There are no mermaid or katex graphs at the notes causing the issue 
- HTML Directory, JEX, MD, etc export works fine
- Workaround: Enabling safe mode solves the problem, i.e. allows to export to pdf/html file. Yet the issue is still observed on cleanly installation, i.e. no user config related.  

## Logfile
The error is thrown at dev console in the moment the issue arises (pdf export)

```
Error: ENOENT: no such file or directory, open '/home/host/.config/joplin-desktop/tmp/pluginassets/mermaid/mermaid.min.js'
    at Object.openSync (fs.js:498)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5)
    at Object.readFileSync (fs.js:394)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5)
    at processScriptTag (index.ts:98)
    at Object.onopentag (index.ts:169)
    at Parser.onopentagend (/tmp/.mount_Joplinfw…2/lib/Parser.js:203)
    at Tokenizer._stateBeforeAttributeName (/tmp/.mount_Joplinfw…ib/Tokenizer.js:201)
    at Tokenizer._parse (/tmp/.mount_Joplinfw…ib/Tokenizer.js:605)
    at Tokenizer.write (/tmp/.mount_Joplinfw…ib/Tokenizer.js:585)
(anonymous)	@	MainScreen.tsx:419
rejected	@	/tmp/.mount_Joplinfw…een/MainScreen.js:6
Promise.then (async)		
step	@	/tmp/.mount_Joplinfw…een/MainScreen.js:7
fulfilled	@	/tmp/.mount_Joplinfw…een/MainScreen.js:5
processTicksAndRejections	@	internal/process/task_queues.js:95
Promise.then (async)		
step	@	/tmp/.mount_Joplinfw…een/MainScreen.js:7
(anonymous)	@	/tmp/.mount_Joplinfw…een/MainScreen.js:8
__awaiter	@	/tmp/.mount_Joplinfw…een/MainScreen.js:4
printTo_	@	MainScreen.tsx:396
(anonymous)	@	exportPdf.ts:47
fulfilled	@	/tmp/.mount_Joplinfw…ands/exportPdf.js:5
processTicksAndRejections	@	internal/process/task_queues.js:95
Promise.then (async)		
step	@	/tmp/.mount_Joplinfw…ands/exportPdf.js:7
fulfilled	@	/tmp/.mount_Joplinfw…ands/exportPdf.js:5
Promise.then (async)		
step	@	/tmp/.mount_Joplinfw…ands/exportPdf.js:7
fulfilled	@	/tmp/.mount_Joplinfw…ands/exportPdf.js:5
processTicksAndRejections	@	internal/process/task_queues.js:95
Promise.then (async)		
step	@	/tmp/.mount_Joplinfw…ands/exportPdf.js:7
(anonymous)	@	/tmp/.mount_Joplinfw…ands/exportPdf.js:8
__awaiter	@	/tmp/.mount_Joplinfw…ands/exportPdf.js:4
execute	@	exportPdf.ts:15
(anonymous)	@	CommandService.ts:236
(anonymous)	@	/tmp/.mount_Joplinfw…CommandService.js:8
__awaiter	@	/tmp/.mount_Joplinfw…CommandService.js:4
execute	@	CommandService.ts:229
(anonymous)	@	MenuUtils.ts:96
click	@	MenuUtils.ts:81
apply	@	/tmp/.mount_Joplinfw…acks-registry.js:54
(anonymous)	@	/tmp/.mount_Joplinfw…derer/remote.js:345
(anonymous)	@	/tmp/.mount_Joplinfw…derer/remote.js:327
emit	@	events.js:376
onMessage	@	electron/js2c/renderer_init.js:81
```

**Comment by Daeraxa** [comment]
No such issue on Windows 10, portable or normal.

**Comment by graphit0** [comment]
> No such issue on Windows 10, portable or normal.

Thanks, indeed, I tested it on Windows on the same hardware, the export works fine. Seems to be Linux specific. Wonder if only my distro is affected :thinking:

**Comment by Daeraxa** [comment]
I can replicate it on Linux Mint 20.2 but complaining about katex.css instead:
![image](https://user-images.githubusercontent.com/58074586/146624783-1a925de4-9cdd-4a7b-8cf5-a4a5b9801f2b.png)

**Comment by laurent22** [comment]
Could you provide an example of Markdown note that causes the issue please?

**Comment by laurent22** [comment]
I can't replicate this in macOS. How did you install the app on Linux? Could it be some permission issue due to the way it was installed?

**Comment by Daeraxa** [comment]
It is definitely the case sensitive thing, I renamed the folder to lowercase and it exports normally

> Could you provide an example of Markdown note that causes the issue please?

Literally any note, even just a single plaintext character with nothing else

**Comment by graphit0** [comment]
Indeed, the result is the same with any note but to settle the matter here's one of the notes from welcome pages that causes the error and contains only text 

[2. Importing and exporting notes.md](https://github.com/laurent22/joplin/files/7739107/2.Importing.and.exporting.notes.md)

**Comment by Daeraxa** [comment]
The problem is this commit:
https://github.com/laurent22/joplin/commit/98ed2be518d2d390199e18ae8a25a8882a8eacff# and I suspect it is the changes made to https://github.com/laurent22/joplin/blob/dev/packages/lib/services/interop/InteropService_Exporter_Html.ts

Building from the commit prior to that change works fine (https://github.com/laurent22/joplin/tree/5a82f5db934cbab22eb2a9a708f6e0b70f6d6b28). Building from first commit I linked brings up the error

**Comment by laurent22** [comment]
Thanks @Daeraxa, that was indeed this commit and more precisely in the htmlpack library that was used for the first time in there. I can't test unfortunately but I'm relatively confident this change should fix the issue (I don't remember why I've lower cased the html attributes but I don't think I broke something else).

**Comment by Daeraxa** [comment]
I pulled the latest commit, rebuilt it and it seems to work just fine now (for pdf exporting at least)

**Comment by niksingh710** [comment]
Currently, i get it working by changing the name of `pluginAssets` to `pluginassets` .
Is there any permanent solution?

**Comment by graphit0** [comment]
> Is there any permanent solution?

Next release will include the fix, stay tuned
