### ISSUE TITLE
S3 sync issues in 2.6

### ISSUE THREAD

**Issue by azazzel** [laurent22/joplin#5875]
after update to 2.6.9. on macOS Monterey, the sync stoped working, pressing sync doesn't do anything, no errors, no nothing

**Comment by Daeraxa** [comment]
Can you at least provide details as to what sync target you are using and provide the log files as requested on the issue template?

**Comment by azazzel** [comment]
S3 for sync target. Found the issue, after update the S3 region was blank. It's back to normal after inputing the region

**Comment by lanyun1103** [comment]
> S3 for sync target. Found the issue, after update the S3 region was blank. It's back to normal after inputing the region

Oh, I thought that this option does not need to be filled in, I just fill in one and can use it, thanks

**Comment by chenkehao1998** [comment]
I faced the same problem. 
I have downgrade the version to 2.5 by update the data of sqlite and reinstall it.

**Comment by chenkehao1998** [comment]
The config of s3 is differernt in version 2.6 which require region,I added it,but the sync problem is still existed.
I found a mistake in development mode.
![image](https://user-images.githubusercontent.com/60775060/146639191-b4278c0c-68e9-4e8a-a8ef-0f678c57fdc3.png)
But I am not good at js . So I don't know what makes this error occured.

**Comment by chenkehao1998** [comment]
The same problem occured in windows 10, too. Not just at macos

**Comment by leeh11** [comment]
Same issue occured.

![image](https://user-images.githubusercontent.com/24563847/146642086-1679be60-b854-417d-927c-af7d4fc7f217.png)

I used Oracle Cloud Object Storage with Amazon S3 Compatibility API. The old Joplin version worked fine.

I filled the  region,  but the  problem is still existed.

**Comment by laurent22** [comment]
Please let us know what URL you use to connect to S3. We need the complete URL to replicate the issue (you can replace the domain by `example.com` though)

**Comment by chenkehao1998** [comment]
my URL is s3-cn-east-2.qiniucs.com
I used Qiniu Cloud Object Storage with Amazon S3 Compatibility API. The oldder Joplin version 2.5.12 worked fine,too

**Comment by leeh11** [comment]
> Please let us know what URL you use to connect to S3. We need the complete URL to replicate the issue (you can replace the domain by `example.com` though).
> 
> @leematos, perhaps you would know what might be the issue?

My URL is : xxxx.compat.objectstorage.ap-seoul-1.oraclecloud.com

**Comment by laurent22** [comment]
Could try adding "https://" in front of the URL to see if the validation passes?

**Comment by leeh11** [comment]
> Could try adding "https://" in front of the URL to see if the validation passes?

It worked! But a new problem arises:
Hostname/IP does not match certificate's altnames: Host: joplin.mynamespace.compat.objectstorage.ap-seoul-1.oraclecloud.com. is not in the cert's altnames: DNS:swiftobjectstorage.ap-seoul-1.oraclecloud.com (Code ERR_TLS_CERT_ALTNAME_INVALID)

**Comment by chenkehao1998** [comment]
Thank u very much! My problem has solved.
I tried http:// before. But it did't worked. However,https is really valid.
And I didn't face the problem leeh11 said. Maybe,it's different between qiniu cloud and oracle.

**Comment by laurent22** [comment]
> It worked! But a new problem arises: Hostname/IP does not match certificate's altnames: Host: joplin.mynamespace.compat.objectstorage.ap-seoul-1.oraclecloud.com. is not in the cert's altnames: DNS:swiftobjectstorage.ap-seoul-1.oraclecloud.com (Code ERR_TLS_CERT_ALTNAME_INVALID)

@leeh11, if you type the URL directly in a browser, does it work? Or perhaps this service only supports plain http (not https)?

**Comment by leeh11** [comment]
> > It worked! But a new problem arises: Hostname/IP does not match certificate's altnames: Host: joplin.mynamespace.compat.objectstorage.ap-seoul-1.oraclecloud.com. is not in the cert's altnames: DNS:swiftobjectstorage.ap-seoul-1.oraclecloud.com (Code ERR_TLS_CERT_ALTNAME_INVALID)
> 
> @leeh11, if you type the URL directly in a browser, does it work? Or perhaps this service only supports plain http (not https)?

I tried both http and https in browser, no response.
Let me check the oracle cloud documentation to see if I need to add a certificate some where.

**Comment by anemyte** [comment]
@leeh11 I'm using OCI as well. Adding region resolved the issue for me:
![image](https://user-images.githubusercontent.com/44520858/146666357-a9a6c082-904e-4f38-b407-9ca713c6feef.png)

**Comment by leeh11** [comment]
> @leeh11 I'm using OCI as well. Adding region from the endpoint URL resolved the issue for me (at least on Linux). Here is my settings: ![image](https://user-images.githubusercontent.com/44520858/146666357-a9a6c082-904e-4f38-b407-9ca713c6feef.png)

I have the same config, but not worked on macOS and iOS(old version worked fine). If you have a iOS device please test it, tks.

**Comment by tessus** [comment]
Afaik, the region is part of the S3 specs. However, maybe there's a way to retrieve and use a default region, if one is set for a user. Maybe @leematos can answer this, since he probably know the SDK and S3 API better.

Regarding the endpoint: IMO the schema always belongs to the URL, even though an unencrypted endpoint makes not much sense, except for testing S3 locally. Thus automatically prefixing the URL with `https://` is not a good idea, unless it is only done, iff the URL does not start with a schema.

**Comment by hoonnn** [comment]
Same problem if you are using MinIO.

**Comment by tessus** [comment]
@hoonnn can you be a bir more specific? does it work when you enter a preoper URL with scheme and a region?

**Comment by hoonnn** [comment]
@tessus Same error on android and mac.
If you downgrade to v2.4.12 with the same settings, it is normal.
![Screenshot_20211220-142745_Joplin](https://user-images.githubusercontent.com/22929166/146716864-571807d5-a33c-4832-80fd-5d75864c5133.jpg)

**Comment by up-umop** [comment]
I'm also experiencing this issue on Windows 10 and mobile using the AWS S3 (beta) sync target. The sync button is present but doesn't do anything in Windows, and the sync errors on mobile.
 
![SmartSelect_20211220-085740_Joplin](https://user-images.githubusercontent.com/47707396/146787796-3f64d6dc-2b5e-4a37-99be-afdcc61f0477.jpg)

Note: 👆 before the update the AWS region was blank. I supplied a value based on the troubleshooting tips above.

![SmartSelect_20211220-085943_Joplin](https://user-images.githubusercontent.com/47707396/146787799-991d5953-821a-413f-a34e-2a26506b3d24.jpg)

Note: 👆I originally supplied `us-west-2` in the config, but changed it based on this message. I get this same error after supplying `us-east-1` and saving.

**Comment by laurent22** [comment]
I'm going to guess it's caching some auth token and not clearing it properly. Maybe you'll have to delete the app and reinstall it.

**Comment by leematos** [comment]
I'm the Dev that worked on this.

To anyone still having problems, attempt to toggle forcePathStyle on/off and do a test sync. See if that changes your behavior.

@up-umop In your screenshot i see "Success! Sync appears to be correct." which means on that device your settings are working and your client was able to auth and connect to your S3 provider. Use those settings on other clients and you should be successful.

---
I'll look to add OCI to our examples in the docs based on what the users above found.

**Comment by up-umop** [comment]
> @up-umop In your screenshot i see "Success! Sync appears to be correct." which means on that device your settings are working and your client was able to auth and connect to your S3 provider. Use those settings on other clients and you should be successful.

Correct! Based on @laurent22's comment I was able to clear my mobile app cache, which allowed the verified credentials to work correctly. Once that went though, I updated the region in the Windows desktop app, which again begin to successfully sync. 

Thanks!

**Comment by leematos** [comment]
Awesome! Glad you got it sorted! 💪

**Comment by leematos** [comment]
To other's still having trouble 

I'll set aside some time today and tomorrow to monitor this thread -- in your message highlight me @leematos today 12/20/2021 or tomorrow 12/21/2021 and I can help you get your settings right!

**Comment by leematos** [comment]
@leeh11 and @hoonnn I think you two are still having problems? Any progress on your sides?

**Comment by laurent22** [comment]
By the way @leematos, it seems one issue is that the region previously wasn't required and now it is, is that correct? If so, is there anything we can do to better handle this? I guess just setting a default region wouldn't do since it can be anything.

**Comment by leematos** [comment]
@laurent22 

i think the options are:

- set a default region which would be wrong for some % of people and they'd need to change it
- figure out a way to make the field highlight so that 2.5 -> 2.6 upgrade people know to fill it in. (not sure how hard)
- IIRC, it is required in the config now, so any new users can't save settings without it, so new clients aren't affected 

I intended to make sure this was communicated in the release notes, so we could update those to say "if using S3, be sure to set a region in your config as of 2.6."

**Comment by leematos** [comment]
Looking here https://github.com/laurent22/joplin/blob/dev/packages/lib/models/Setting.ts#L524-L537 It doesn't look to be "required". Do you have any examples of required fields? I didn't see any.

**Comment by leeh11** [comment]
> I'm the Dev that worked on this.
> 
> To anyone still having problems, attempt to toggle forcePathStyle on/off and do a test sync. See if that changes your behavior.
> 
> @up-umop In your screenshot i see "Success! Sync appears to be correct." which means on that device your settings are working and your client was able to auth and connect to your S3 provider. Use those settings on other clients and you should be successful.
> 
> I'll look to add OCI to our examples in the docs based on what the users above found.

Correct! I reinstall the app and turn forcePathStyle on, it worked(both macOS and iOS)!!!

**Comment by leeh11** [comment]
> @leeh11 and @hoonnn I think you two are still having problems? Any progress on your sides?

Reinstall the app and turn forcePathStyle on resolved the issue for me.

**Comment by heshikang-survivl** [comment]
我是中国用户，实用的腾讯云COS作为同步方式，在2.5升级到2.6.9时也发现无法完成同步，通过尝试上方的方法，最后成功，附一张腾讯云配置图，region是ap-beijing，需要看你的cos区域
I am a Chinese user. The practical Tencent cloud cos as a synchronization method was upgraded from 2.5 to 2.6.9, I also found that the synchronization could not be completed. I tried the above method and finally succeeded. I attached a Tencent cloud configuration diagram. The region is ap-beijing. It depends on your cos area
![image](https://user-images.githubusercontent.com/56349869/146859993-f49e55c7-b7f9-448b-9b43-7ce2ee2a77a5.png)

**Comment by 86band** [comment]
> 我是中国，实用的腾讯云COS作为同步方式，在2.5升级到2.6.9时也发现无法完成同步，通过试点本地的方法，最后成功，附一张腾讯云配置图，区域是ap-beijing ，需要看你的cos区域 我是中国用户。实用的腾讯云cos作为同步方式从2.5升级到2.6.9，我也发现同步无法完成。我尝试了上面的方法，终于成功了。附上一张腾讯云配置图。该地区是北京。这取决于你的cos区域 ![图片](https://user-images.githubusercontent.com/56349869/146859993-f49e55c7-b7f9-448b-9b43-7ce2ee2a77a5.png)

非常不错，以前不需要填写AWS region这个选项，现在必须填写才可以同步。已经搞定，3Q

**Comment by hoonnn** [comment]
@leematos, It works normally when checking the force path style in Android 2.6.8.

**Comment by shinglyu** [comment]
Can confirm that this happens on iOS Joplin 12.6.2 and macOS Joplin 2.6.10.

Here is my config: 
S3 URL: https://s3.amazonaws.com
region: blank after the update, I set it to eu-central-1 later

The log has the following lines: 
```
Could not acquire synchroniser.
Error: Region is missing
```

There is no clear error message when I click the Syncronize button. If I click "Check syncronization configuration" it just got stuck at "Checking...". 

A quick solution is to add a a clear error message when region is missing.

**Comment by laurent22** [comment]
> i think the options are:
> 
> * set a default region which would be wrong for some % of people and they'd need to change it
> * figure out a way to make the field highlight so that 2.5 -> 2.6 upgrade people know to fill it in. (not sure how hard)
> * IIRC, it is required in the config now, so any new users can't save settings without it, so new clients aren't affected

I agree with Shinglyu, a good error message like "The region is missing, please set it in the configuration screen" would be sufficient.

**Comment by leematos** [comment]
it's weird because in my testing, if you were missing a region and attempted a sync it would display the logged error (Error: Region is missing) in the UI. I'll play around with that to see why it's not happening with the prod build.

**Comment by aflip** [comment]
I am unable to sync. I Set up a new S3 bucket following the guide at https://blog.jfx.ac/syncing-joplin-notes-to-aws-s3.html
Server URL https://s3.amazonaws.com/, region ap-south-1

I've tried toggling the force path style on and off, but in all cases, the error is similar 

`Error. Please check that URL, username, password, etc. are correct and that the sync target is accessible. The reported error was:` 

the log with the details are attached







[joplinerror.txt](https://github.com/laurent22/joplin/files/7773205/joplinerror.txt)

**Comment by leematos** [comment]
@aflip -- I think this is a "temporary issue" see https://forums.aws.amazon.com/message.jspa?messageID=155631#155631 for AWS explaining that this is an AWS DNS issue. Are you still seeing the problem at this time?

Based on that log it looks like it's logging the "error" but it looked like a sync did complete?

**Comment by aflip** [comment]
The sync didn't complete, as in there doesn't seem to be any data in the
AWS bucket. Thank you for pointing out of could be temporary. Will check
again

**Comment by BrianBasor** [comment]
On Windows 10 and Joplin 2.6.10, I had the same behavior as @shinglyu where the suddenly the synchronization button doesn't do anything in the UI and the "Check syncronization configuration" button got stuck on "Checking..."

I added an S3 region into the blank field, restarted the desktop application, and now sync is just fine.

I like @shinglyu 's idea to add an error message when the region is blank and needs to be filled in.  That would have led me right to the fix without searching for a Github issue.

---

Joplin 2.6.10 (prod, win32)

Client ID: 368be69509194888a76f205818255f90
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 98fba37

**Comment by shinglyu** [comment]
I made a little progress. Now I can show the `Region is missing` error in the Synchronization settings page:
![screenshot_2021-12-27_15-28-33](https://user-images.githubusercontent.com/3250983/147480965-8285f68b-9dc5-48bc-95ae-5c73fa896eb8.png)
 Here is my change: 
https://github.com/laurent22/joplin/compare/dev...shinglyu:s3-region-error?expand=1

However, I'm not able to show the error when the "Synchronize" button is pressed on the side menu. There is a reducer command `SYNC_REPORT_UPDATE`, but it needs to be triggered in the `Synchronizer`. This region missing error will cause the `Synchronizer` to fail to initialize at all. Is there a quick and dirty way I can show an error in the side menu or as a popup?

**Comment by laurent22** [comment]
At what point does it fail when the Synchronize button is pressed? Can the error be caught and added to the sync report?

**Comment by aflip** [comment]
Update: The sync works, I can see the objects created in s3. But the sync message has this error attached to it. The data seems to be all synced. have ##ed out identifiable info. 

`
Last error: redirect location header missing at: https://s3.amazonaws.com/##/info.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=###ap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20211227T162017Z&X-Amz-Expires=3600&X-Amz-Signature=####-Amz-SignedHeaders=host&x-id=GetObject`

**Comment by leematos** [comment]
@aflip thanks. I recall seeing a variant of this in my testing. Are you using force path style toggled on or off? Can you try the _opposite_ of whatever you are using?

basically S3 exposes buckets in 2 ways (I can't remember off the top of my head the specific differences) but that toggle switches how requests are sent.

**Comment by aflip** [comment]
@leematos I had it toggled on, and then i sync'd again with it toggled off, and the sync happens, but the error remains.

**Comment by leematos** [comment]
@aflip would it be possible for you to make a test bucket I could use to see if I can generate this error to further debug?

my email is find (dot) creativity (at) githubusername (dot) com

**Comment by shinglyu** [comment]
@laurent22 sorry I was compiling the code in the wrong way so my changes were not picked up. I fixed it and created the PR #5923

**Comment by aflip** [comment]
@leematos   I restarted the app a few times and now the error has disappeared. Thank you very much for the support. Also, i don't really know how to make a test bucket. I made this bucket etc. following a guide I found online, step by step. [SOLVED]

**Comment by sbkg0002** [comment]
![image](https://user-images.githubusercontent.com/1254233/147848930-78b55253-00b9-418b-b30b-a3607b0d3834.png)
Results in a successfull test:(sorry Dutch)
> Succes! Configuratie van synchronisatie lijkt correct te zijn.

But sync results in an error:
```Completed: 01/01/2022 11:49 (22s)
Laatst gemelde fout: <?xml version="1.0" encoding="UTF-8"?><Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'sos-de-fra-1' is wrong; expecting 'de-fra-1'.</Message><Region>de-fra-1</Region></Error>
```

**Comment by leematos** [comment]
@sbkg0002 -- can you try toggling force path style on/off and trying a test sync and a real sync?

Did you ever attempt to set the region to `sos-de-fra-1`? I'm wondering if somewhere that setting is saved and hasn't been overridden based on your successful test sync.

**Comment by dinoandcat** [comment]
> normal.

请问七牛云的AWS region应该填什么?我这样设置检查同步配置都通过不了.

![dinoandcat_2022-01-03_23-03-06](http://blog.golang.chat/dinoandcat_2022-01-03_23-03-06.png)

**Comment by vichbb** [comment]
Joplin cos（tencent Cloud Object Storage,Storage object service compatible with S3 API) synchronization directory level error:
in mac: a have b c,when sync to windows:a,b,c

**Comment by leematos** [comment]
@vichbb -- I'm not sure I understand. Are you saying one folder won't sync? Can you share logs?

**Comment by vichbb** [comment]
> @vichbb -- I'm not sure I understand. Are you saying one folder won't sync? Can you share logs?

There is no error, just a problem with the folder level, just like this, I create a new notebook in MAC: MyNote, and then create two new notebooks under MyNote: Note1 and Note2. Note1 has a note testA, note2 also has a note testB. Now the two note levels are myNote/Note1 /testA and myNote/Note2 /testB. But when I fully synced into cosine of s3. Then use Windows to synchronize again and become Note1 /testA and Note2 /testB with an empty notebook myNote. Now the hierarchy is Note1 and Note2 are not in MyNote, they're in the same layer.

**Comment by leematos** [comment]
@vichbb thanks for this info. Let me do a test real quick:

- Parent Notebook
  - Child Notebook 1
    -  Note 1
  - Child Notebook 2
    -  Note 2

**Comment by vichbb** [comment]
> @vichbb thanks for this info. Let me do a test real quick:
> 
> * Parent Notebook
>   
>   * Child Notebook 1
>     
>     * Note 1
>   * Child Notebook 2
>     
>     * Note 2

Yes, that's it!

**Comment by leematos** [comment]
@vichbb what version of joplin are you using on Windows?

I just ran this test on Mac/iOS with both on latest and I did not see the effect you are talking about. Steps I followed:

On Mac:

make notebook p1. 
Inside of p1 make notebook c1. Inside of c1 make note note-c1. 
Inside of p1 make notebook c2. inside of c2 make note note-c2.
sync.

On iOS
make new note in c1 note-c1-2.
make new note in c2 note-c2-2.
sync.

On ios
edit notes.
sync.

The folder structure remained.

At this point I think it's either an issue with Tencent COS or something outside of this syncing change, or 2.5 and 2.6 versions of joplin making different structures.

**Comment by sbkg0002** [comment]
> @sbkg0002 -- can you try toggling force path style on/off and trying a test sync and a real sync?
> 
> Did you ever attempt to set the region to `sos-de-fra-1`? I'm wondering if somewhere that setting is saved and hasn't been overridden based on your successful test sync.

Not that I can remember. It keeps bugging me with that message about `sos-de-fra-1`, while I didn't use that as a regio. Any ideas on how to fix it?

**Comment by vichbb** [comment]
> 

windows:2.6.10
mac: 2.6.10
ios:12.6.2
I'm not sure if this is a problem caused by Tencent COS，By the way, it's worth mentioning that my Child laptop is not a new one, it's a drag and drop

**Comment by vichbb** [comment]
> @vichbb what version of joplin are you using on Windows?
> 
> I just ran this test on Mac/iOS with both on latest and I did not see the effect you are talking about. Steps I followed:
> 
> On Mac:
> 
> make notebook p1. Inside of p1 make notebook c1. Inside of c1 make note note-c1. Inside of p1 make notebook c2. inside of c2 make note note-c2. sync.
> 
> On iOS make new note in c1 note-c1-2. make new note in c2 note-c2-2. sync.
> 
> On ios edit notes. sync.
> 
> The folder structure remained.
> 
> At this point I think it's either an issue with Tencent COS or something outside of this syncing change, or 2.5 and 2.6 versions of joplin making different structures.

windows:2.6.10
mac:2.6.10
ios:12.6.2
I just tested it. There is no problem with the new and dragged notes. It's strange that only the previous notes have this problem.

**Comment by leematos** [comment]
@sbkg0002 and @vichbb if you can create a bucket for me to use on your platforms so I can test I should be able to take a look this week. My email is listed here:

https://github.com/laurent22/joplin/issues/5875#issuecomment-1001695735

At the moment I haven't been able to reproduce either of your issues so I'm out of testing ideas without a repro case in hand

**Comment by leematos** [comment]
@laurent22 -- I think https://github.com/laurent22/joplin/issues/5875#issuecomment-1004912669 is a different problem than S3 syncing. Any recent changes come to mind that could be related?

**Comment by vichbb** [comment]
> @sbkg0002 and @vichbb if you can create a bucket for me to use on your platforms so I can test I should be able to take a look this week. My email is listed here:
> 
> [#5875 (comment)](https://github.com/laurent22/joplin/issues/5875#issuecomment-1001695735)
> 
> At the moment I haven't been able to reproduce either of your issues so I'm out of testing ideas without a repro case in hand

It has been sent to you. Thank you for your inspection

**Comment by roman-r-m** [comment]
I suspect the issue @vichbb is seeing isn't related to S3. Seems that the top-level notebook failed to sync for some reason - can be a network blip or clocks going out of sync or something else.

You can try renaming the folder on the client where you have the folder (can even rename twice to keep the original name), then sync that client, and finally sync the other client.

**Comment by vichbb** [comment]
> I suspect the issue @vichbb is seeing isn't related to S3. Seems that the top-level notebook failed to sync for some reason - can be a network blip or clocks going out of sync or something else.
> 
> You can try renaming the folder on the client where you have the folder (can even rename twice to keep the original name), then sync that client, and finally sync the other client.

I tried. The folder name was changed normally, but the directory level after synchronization was still wrong.

**Comment by sbkg0002** [comment]
> @sbkg0002 and @vichbb if you can create a bucket for me to use on your platforms so I can test I should be able to take a look this week. 

You got mail. Thanks in advance!
