### ISSUE TITLE
Spell check no longer working.

### ISSUE THREAD

**Issue by nemo9000** [laurent22/joplin#5878]
## Environment

Joplin version: 2.5.12
Platform: Linux
OS specifics: Fedora 35 - GNOME 41

## Steps to reproduce

1. Type a misspelled word.

## Describe what you expected to happen
I expect misspelled words to be underlined in red.

**Comment by Daeraxa** [comment]
Which editor are you referring to?
Works fine for me using 2.6.9 on Win10 in the richtext editor and also works in the markdown editor if I enable the beta spellcheck option first.

**Comment by graphit0** [comment]
On Kubuntu 21.04 2.6.9 both rich text and codemirror editor spellcheckers work. Would be interesting to see, if Joplin update may help you.

**Comment by nemo9000** [comment]
> Which editor are you referring to? Works fine for me using 2.6.9 on Win10 in the richtext editor and also works in the markdown editor if I enable the beta spellcheck option first.

It only works in the richtext editor, not the markdown editor. I have the same problem on my other laptop that I just installed Joplin to, a ThinkPad X1 Nano, also running Fedora 35 with GNOME 41.

**Comment by Daeraxa** [comment]
Just to double check, the markdown spellcheck feature _is_ still turned on in your options isn't it? In case an update knocked the option off for some reason at some point.

**Comment by nemo9000** [comment]
> On Kubuntu 21.04 2.6.9 both rich text and codemirror editor spellcheckers work. Would be interesting to see, if Joplin update may help you.

I updated, but it only seems to work on the rich text editor, but not markdown. I'm having the same problem on another laptop that I just installed it on, also running Fedora 35 with GNOME 41.

**Comment by nemo9000** [comment]
> Just to double check, the markdown spellcheck feature _is_ still turned on in your options isn't it? In case an update knocked the option off for some reason at some point.

Yes, it's still turned on.

**Comment by Daeraxa** [comment]
And just to triple check - the option I'm talking about is the one in `Tools > Options > General > Enable spell checking in markdown editor?` and not the option in the top right of the main app screen/`Tools > Spell checker > User spell checker`

**Comment by nemo9000** [comment]
> And just to triple check - the option I'm talking about is the one in `Tools > Options > General > Enable spell checking in markdown editor?` and not the option in the top right of the main app screen/`Tools > Spell checker > Use spell checker`

Aha! I didn't know there was a separate setting for that. It's solved now. Thanks!
