### ISSUE TITLE
Joplin 2.6.9 sync issues

### ISSUE THREAD

**Issue by poudenes** [laurent22/joplin#5881]
## Environment

Joplin version: 2.6.9
Platform: MacOS
OS specifics: 10.13
Joplin Server Docker: Joplin Server 2.5.5, copyright © 2021 Laurent Cozic.

## Steps to reproduce

1. Sync everything with version before latest (in my case 2.5.12)
2. Update the app with 2.6.9
3. Try to sync but get a error
4. close the app
5. Goto ~/.config/joplin-desktop
6. Delete everything
7. Revert back to 2.5.12
8. Config sync and sync everything
9. Syncing is working again.

Try the steps again. Closed the app, update the app but the error message is there again:

## Logfile / ERROR Message

```
Error. Please check that URL, username, password, etc. are correct and that the sync target is accessible. The reported error was:
Error 412 Precondition Failed: <!doctype html> <html> <head> <title>Joplin Server - Error</title> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1" /> <link rel="stylesheet" href="https://js.hassio.nl/css/bulma.min.css" crossorigin="anonymous"> <!-- <link rel="stylesheet" href="https://js.hassio.nl/css/bulma-prefers-dark.min.css" crossorigin="anonymous"> --> <link rel="stylesheet" href="https://js.hassio.nl/css/main.css" crossorigin="anonymous"> <link rel="stylesheet" href="https://js.hassio.nl/css/fontawesome/css/all.min.css" crossorigin="anonymous"> <script src="https://js.hassio.nl/js/jquery.min.js"></script> <script src="https://js.hassio.nl/js/main.js"></script> </head> <body class="page-error"> <main class="main"> <div class="container"> <script> onDocumentReady(function() { const buttons = document.getElementsByClassName('close-notification-button'); for (const button of buttons) { button.addEventListener('click', function(event) { c (Code 412)
```

**Comment by CalebJohn** [comment]
There was also a Joplin server release. I think you'll need to update the server as well.

**Comment by poudenes** [comment]
The docker is latest version:

## 2.6.9 (18-12-2021)
- Update to latest version from laurent22/joplin

When i login at the server i see below:

Joplin Server 2.5.5

Maybe the docker is not updated?

**Comment by alexbelgium** [comment]
Indeed ! The maintainer of the image changed from "master" to "latest". I've updated the addon it should work!

**Comment by poudenes** [comment]
Updated the Addon and everything is working again!
