### ISSUE TITLE
Cannot scroll to begin/end of note using keyboard shortcuts on macOS

### ISSUE THREAD

**Issue by pravsripad** [laurent22/joplin#5882]
Keyboard shortcuts Cmd+Up/Down to go to begin/end of the does not work anymore after updating to 2.6.

The cursor moves to the begin/end of the note but page view does not get updated. The user is force to scroll up or down since the page does not seem to scroll along with the cursor. 

- the issue persists in editor / split views
- the issue persists in Safe Mode

It probably has something to do with the latest updates to improve scrolling, can someone check if they can reproduce it as well? 

## Environment

Joplin 2.6.9 (prod, darwin)
Client ID: 20e2a2bc858f4dce89aeffe2c7889ab0
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes
Revision: 58654d3
Platform macOS (intel)

## Steps to reproduce

1. Press Cmd+Up/Down arrows to go to beginning or end of the note. 
2. Cursor goes to the begin/end of note but the page view does not. 
3. User is forced to scroll to the begin/end of the note. 

## Describe what you expected to happen

Expect the page view also to go to begin / end of the note. 

## Logfile

Cannot see any errors in the log.

**Comment by Daeraxa** [comment]
This was identified as part of another issue and fixed pending a new release
https://github.com/laurent22/joplin/issues/5872#issuecomment-997192211

**Comment by pravsripad** [comment]
> This was identified as part of another issue and fixed pending a new release
> [#5872 (comment)](https://github.com/laurent22/joplin/issues/5872#issuecomment-997192211)

Right, thanks. Joplin 2.6.10 is now available and fixes the issue for me.
