### ISSUE TITLE
Joplin 2.16.10 - Labels of notebooks are missing

### ISSUE THREAD

**Issue by StefanPapp** [laurent22/joplin#5887]
![image](https://user-images.githubusercontent.com/415264/146736900-fc0edcdd-5dd7-4053-858b-3ddb1cedd389.png)

## Environment

Joplin version: 2.6.10
Platform: Mac OS 12.0.1
OS specifics: Mac OS 12.0.1

## Steps to reproduce

1. Install new version 
2. look at the notebooks
3. 

## Describe what you expected to happen
Notebooks should be displayed with their name tags

**Comment by Daeraxa** [comment]
Are you using the macos theme? What happens if you turn it off? I wonder if the method used to display the folders clashes with the new notebook icon function in 2.6

**Comment by StefanPapp** [comment]
The problem got resolved when I updated MacOs Theme Plugin to the latest version
