### ISSUE TITLE
could not use audio url in <audio> tag

### ISSUE THREAD

**Issue by quancs** [laurent22/joplin#5889]
markdown
```
<audio controls src=":/378bcb88e95a405994570cbe6012d9e9"> </audio>

[x](:/378bcb88e95a405994570cbe6012d9e9)

```

screenshot:
![图片](https://user-images.githubusercontent.com/16813683/146770218-c578fa59-ef26-4a5c-b3bb-bb91a7c8d960.png)

## Environment

Joplin version:  2.6.10
Platform: Windows
OS specifics: win 11

## Steps to reproduce

1.  create a new note
2. drag image to the note
3. copy the autogenerated link to audio tag

## Describe what you expected to happen

The audio tag should display the same with the markdown tag

**Comment by graphit0** [comment]
Summary of this issue: This is a feature request to support playing local audio files using audio tag `<audio controls src=":/ID"> </audio>`

As this is advanced functionality, I suggest to close this as "won't fix" and discuss the previous related FR regarding export of built-in players to HTML file in [this discourse topic](https://discourse.joplinapp.org/t/export-audio-to-html-using-audio-tag-not-a/22506/2?u=graphit0)

**Comment by quancs** [comment]
OK

**Comment by graphit0** [comment]
linking: related to #5304
