### ISSUE TITLE
Will not install from Google Playstore for Android on Chrome OS

### ISSUE THREAD

**Issue by davidjmurray** [laurent22/joplin#589]
### Operating system
- Android

### Application
- Mobile 

It states within the Play store entry that Joplin is not compatible.
Chromebook = Asus Chromebook 100CP

**Comment by laurent22** [comment]
Does the APK file work? https://github.com/laurent22/joplin-android/releases/download/android-v1.0.125/joplin-v1.0.125.apk

**Comment by davidjmurray** [comment]
Laurent,

My chrome book is not in developer mode, so I cannot side-load apps;
hence the interest in getting Joplin to work through the Google Play store.

Thanks,

Cheers,

djm

**Comment by laurent22** [comment]
As far as I know the app is not compatible with Chromebooks. There was an open thread about this before but it was close since it's not clear what needs to be done to make it compatible.
