### ISSUE TITLE
Search Button Not Working on Mac

### ISSUE THREAD

**Issue by llbster** [laurent22/joplin#5893]
I just upgraded to Joplin 2.6.10 (prod, darwin) and the Search Button (magnifying glass) on the main UI no longer seems to be working. 

Client ID: dd7d047904b343a49b088031b2804cce
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 98fba37

## Environment
Joplin 2.6.10 (prod, darwin) and the Search Button (magnifying glass) on the main UI no longer seems to be working. 

Client ID: dd7d047904b343a49b088031b2804cce
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Platform: Mac,  10.15.7
OS specifics: 

## Steps to reproduce

1. Launch Joplin
2. Click on Search Button
3. Verify no search pop-up or other possibilities for entering a search term

## Describe what you expected to happen
A search field to appear as in previous versions

**Comment by laurent22** [comment]
I think you need to expand the note list

**Comment by llbster** [comment]
Duh!!  Yes, that helps... what a fool!! 

 ;)

Many thanks!!!

**Comment by llbster** [comment]
User error!
 (Notes pane was minimized and I could not see the search field)
