### ISSUE TITLE
Indentation colors are broken [Bug] [Feature Regression]

### ISSUE THREAD

**Issue by hffaust** [laurent22/joplin#5898]
- I am not sure exactly where this regression occurred, but I was last using Joplin 2.1.9 and found the indentation coloring to be working perfectly. Now after the latest 2.6.10 update (also was a problem in the pre-release version), text no longer gets highlighted for indentations. 
    - I have no extensions running. Screenshots are from a fresh install of Joplin in a virtual machine. 
- See the screenshots for details:
- Joplin 2.1.9 showing working indentation coloring:
    ![Joplin 2 1 9 working indentation colors](https://user-images.githubusercontent.com/15644021/146970511-712a1529-3d69-40fd-b220-ca7df5f47ca2.PNG)
- Joplin 2.6.10 showing broken indentation coloring:
    ![joplin 2 6 10 non working indentation colors](https://user-images.githubusercontent.com/15644021/146970989-9dab9f59-3ded-46ca-8922-42d33e319ae3.PNG)

## Environment

Joplin version: 2.6.10
Platform: Windows (also affects Mac)
OS specifics: Windows Home x64 

## Steps to reproduce
1. Make a new note.
2. Make a parent bullet note, followed by a child note (indented 1 space over), and a grand-child note (indented 2 spaces over).

## Describe what you expected to happen
- I would expect the text to change colors with every child note (or every indentation) so that it is easier to read and see at a glance what text is a sub-bullet of other text. 

## Logfile
- Available upon request, but I don't think it is necessary for this issue.

**Comment by Daeraxa** [comment]
This was an intended change in, I think, 2.3.5. See https://discourse.joplinapp.org/t/rfc-update-markdown-editor-css-to-make-it-match-loaded-theme/18601 for the rfc post.

**Comment by hffaust** [comment]
@Daeraxa  can you direct me to where I can find them or how I could load them?

Is it here: using the "Custom stylesheet for Joplin-wise app styles" or "Custom stylesheet for rendered Markdown" ? Because neither of these buttons do anything when I press them which may be another issue in itself. 
![image](https://user-images.githubusercontent.com/15644021/146985558-96d8bff3-d4e4-4312-aed4-4a23cc34724b.png)

**Comment by Daeraxa** [comment]
https://discourse.joplinapp.org/t/introduction-to-customising-joplin-userchrome-css-userstyle-css/21370 is a guide to theming in general.

https://discourse.joplinapp.org/t/joplin-customization/11195/ is a list of css tweaks including how to restore the old CM theme.

**Comment by hffaust** [comment]
@Daeraxa  Thank you. That is very helpful.

**Comment by hffaust** [comment]
> https://discourse.joplinapp.org/t/introduction-to-customising-joplin-userchrome-css-userstyle-css/21370 is a guide to theming in general.
> 
> https://discourse.joplinapp.org/t/joplin-customization/11195/ is a list of css tweaks including how to restore the old CM theme.
@Daeraxa 
In the guide in the first link, I would just like to note that it references the  "Custom stylesheet for rendered Markdown" (which opens userstyle.css) or "Custom stylesheet for Joplin-wide settings" (which opens userchrome.css) buttons that I attached in the last screenshot... Clicking these buttons doesn't do anything on Windows. This is because for me the `.css` files had no file association. After correcting that and having them `.css` files be associated with VScode, clicking the button would open VScode but would not open the `userstyle.css` or `userchrome.css` files. So I believe that to be a bug as well.

**Comment by hffaust** [comment]
> > https://discourse.joplinapp.org/t/introduction-to-customising-joplin-userchrome-css-userstyle-css/21370 is a guide to theming in general.
> > https://discourse.joplinapp.org/t/joplin-customization/11195/ is a list of css tweaks including how to restore the old CM theme.
> 
> @Daeraxa In the guide in the first link, I would just like to note that it references the "Custom stylesheet for rendered Markdown" (which opens userstyle.css) or "Custom stylesheet for Joplin-wide settings" (which opens userchrome.css) buttons that I attached in the last screenshot... Clicking these buttons doesn't do anything on Windows. This is because for me the `.css` files had no file association. After correcting that and having them `.css` files be associated with VScode, clicking the button would open VScode but would not open the `userstyle.css` or `userchrome.css` files. So I believe that to be a bug as well.

Restarting a few times seemed to fix this issue.

**Comment by Daeraxa** [comment]
Yes, the CSS will only override to the colours it is set to.
I [recreated the dark mode theme](https://discourse.joplinapp.org/t/dark-theme-syntax-highlighting/21049/4) but not sure if anyone has done it for any of the others.

**Comment by hffaust** [comment]
I just did it for Solarized Dark as well:
```
/* Bullet point coloring solarized dark */
div.CodeMirror.cm-s-solarized span.cm-header {color: #268bd2;}
div.CodeMirror.cm-s-solarized span.cm-quote {color: #090;}
div.CodeMirror.cm-s-solarized span.cm-negative {color: #d44;}
div.CodeMirror.cm-s-solarized span.cm-positive {color: #292;}
div.CodeMirror.cm-s-solarized span.cm-header, span.cm-strong {font-weight: bold;}
div.CodeMirror.cm-s-solarized span.cm-em {font-style: italic;}
div.CodeMirror.cm-s-solarized span.cm-link {text-decoration: underline;}
div.CodeMirror.cm-s-solarized span.cm-strikethrough {text-decoration: line-through;}


/* Grandchild bullet */
div.CodeMirror.cm-s-solarized span.cm-keyword {color: #6c71c4;}

div.CodeMirror.cm-s-solarized span.cm-atom {color: #219;}
div.CodeMirror.cm-s-solarized span.cm-number {color: #164;}
div.CodeMirror.cm-s-solarized span.cm-def {color: #00f;}
div.CodeMirror.cm-s-solarized span.cm-variable,
div.CodeMirror.cm-s-solarized span.cm-punctuation,
div.CodeMirror.cm-s-solarized span.cm-property,
div.CodeMirror.cm-s-solarized span.cm-operator {}

/* Parent bullet */
div.CodeMirror.cm-s-solarized span.cm-variable-2 {color: #b58900;}

/* Child bullet */
div.CodeMirror.cm-s-solarized span.cm-variable-3, div.CodeMirror.cm-s-solarized span.cm-type {color: #dc322f;}

/* Code font color*/
div.CodeMirror.cm-s-solarized span.cm-comment {color: #2aa198;}

div.CodeMirror.cm-s-solarized span.cm-string {color: #a11;}
div.CodeMirror.cm-s-solarized span.cm-string-2 {color: #2aa198;}
div.CodeMirror.cm-s-solarized span.cm-meta {color: #555;}
div.CodeMirror.cm-s-solarized span.cm-qualifier {color: #555;}
div.CodeMirror.cm-s-solarized span.cm-builtin {color: #30a;}
div.CodeMirror.cm-s-solarized span.cm-bracket {color: #997;}
div.CodeMirror.cm-s-solarized span.cm-tag {color: #170;}
div.CodeMirror.cm-s-solarized span.cm-attribute {color: #00c;}
div.CodeMirror.cm-s-solarized span.cm-hr {color: #999;}
div.CodeMirror.cm-s-solarized span.cm-link {color: #00c;}

div.CodeMirror.cm-s-solarized span.cm-error {color: #f00;}
span.cm-invalidchar {color: #f00;}

/* Custom modification to make triple tick code blocks have black background */
div.CodeMirror.cm-s-solarized pre.cm-jn-code-block {background: rgba(0,0,0,0.7); display: flex;}
```

**Comment by hffaust** [comment]
Awesome thank you. I just made an override that I believe works with the "Solarized Dark" theme:

```
/* Bullet point coloring solarized dark */
div.CodeMirror.cm-s-solarized span.cm-header {color: #268bd2;}
div.CodeMirror.cm-s-solarized span.cm-quote {color: #090;}
div.CodeMirror.cm-s-solarized span.cm-negative {color: #d44;}
div.CodeMirror.cm-s-solarized span.cm-positive {color: #292;}
div.CodeMirror.cm-s-solarized span.cm-header, span.cm-strong {font-weight: bold;}
div.CodeMirror.cm-s-solarized span.cm-em {font-style: italic;}
div.CodeMirror.cm-s-solarized span.cm-link {text-decoration: underline;}
div.CodeMirror.cm-s-solarized span.cm-strikethrough {text-decoration: line-through;}

/* Grandchild bullet */
div.CodeMirror.cm-s-solarized span.cm-keyword {color: #6c71c4;}

div.CodeMirror.cm-s-solarized span.cm-atom {color: #219;}
div.CodeMirror.cm-s-solarized span.cm-number {color: #164;}
div.CodeMirror.cm-s-solarized span.cm-def {color: #00f;}
div.CodeMirror.cm-s-solarized span.cm-variable,
div.CodeMirror.cm-s-solarized span.cm-punctuation,
div.CodeMirror.cm-s-solarized span.cm-property,
div.CodeMirror.cm-s-solarized span.cm-operator {}

/* Parent bullet */
div.CodeMirror.cm-s-solarized span.cm-variable-2 {color: #b58900;}

/* Child bullet */
div.CodeMirror.cm-s-solarized span.cm-variable-3, div.CodeMirror.cm-s-solarized span.cm-type {color: #dc322f;}

/* Code font color */
div.CodeMirror.cm-s-solarized span.cm-comment {color: #2aa198;}

div.CodeMirror.cm-s-solarized span.cm-string {color: #df5c23;}
div.CodeMirror.cm-s-solarized span.cm-string-2 {color: #2aa198;}
div.CodeMirror.cm-s-solarized span.cm-meta {color: #555;}
div.CodeMirror.cm-s-solarized span.cm-qualifier {color: #555;}
div.CodeMirror.cm-s-solarized span.cm-builtin {color: #30a;}
div.CodeMirror.cm-s-solarized span.cm-bracket {color: #997;}
div.CodeMirror.cm-s-solarized span.cm-tag {color: #170;}
div.CodeMirror.cm-s-solarized span.cm-attribute {color: #00c;}
div.CodeMirror.cm-s-solarized span.cm-hr {color: #999;}
div.CodeMirror.cm-s-solarized span.cm-link {color: #859900;}

div.CodeMirror.cm-s-solarized span.cm-error {color: #f00;}
span.cm-invalidchar {color: #f00;}

/* Custom modification to make triple tick code blocks have black background that resizes if text is too long for screen*/
div.CodeMirror.cm-s-solarized pre.cm-jn-code-block {background: rgba(0,0,0,0.7); width: 100%;}
```
