### ISSUE TITLE
Can't use it :(

### ISSUE THREAD

**Issue by Vladeeno** [laurent22/joplin#59]
### Operating system

- [ ] Windows

### Application

- [ ] Desktop

*If it is a bug if possible please provide a screenshot showing the problem*
https://i.imgur.com/xPJTCoC.png

*If there is an error, please copy and paste the full error message*

---

**Comment by kellerjustin** [comment]
Same error here. I'm using Ubuntu.
![joplin](https://user-images.githubusercontent.com/31552409/33516545-2198a636-d73a-11e7-95c1-21196a558ada.png)

**Comment by laurent22** [comment]
Yes sorry the wrong version got released, please use 0.10.31 for now - https://github.com/laurent22/joplin/releases/tag/v0.10.31
I'm releasing another version that will fix this issue.

**Comment by laurent22** [comment]
Ok I've removed the broken version and replaced it by [0.10.34](https://github.com/laurent22/joplin/releases/tag/v0.10.34). Please give it a try and let me know if you're still having an error.

**Comment by zelvik** [comment]
Now it's working. Thank you for fix.

**Comment by laurent22** [comment]
Great, thanks for confirming.
