### ISSUE TITLE
Deletion of Notes/Notebooks is not synced properly via Nextcloud

### ISSUE THREAD

**Issue by jgreth** [laurent22/joplin#590]
### Operating system

- Windows
- Linux

### Application

- Desktop

I'm using Joplin 1.0.96 (prod, win32) and sync via Nextcloud 13.0.2

For testing purposes i deleted ALL of my Notes and Notebooks in Joplin and synced it to Nextcloud.
Joplin said sync completed and no errors occured.
I would now expect the data beeing deleted on Nextcloud (as is in Joplin) but it isn't.
The Nextcloud-Joplin-folder i'm syncing to is still around 1GB (!)

I think it's a bug, that the deletion of Notes / Notebook is not synced on file layer.

**Comment by TobiasDev** [comment]
It says (if you look at attachments) that it deletes them after 10 days if they aren't used in another note. Did you have attachments in your notes? (Sounds like it with that size, but just wanted to make sure). Because then it will most likely go away in about 10 days. Otherwise it is a bug.

**Comment by jgreth** [comment]
Ah... thanks for the hint. Yes i read it but didn't remind. The timespan beween deleting and syncing was only four days. My fault. Will close this - and thanks again.
