### ISSUE TITLE
Content not filling out whole page [Bug]

### ISSUE THREAD

**Issue by hffaust** [laurent22/joplin#5900]
- I am not sure if this is a feature request or a bug. I believe that this used to be a feature in the older versions of Joplin, but not sure if it was removed on purpose or not...

- When you go into single view mode, both in edit and rendered views, the body of text takes up very little space in the center of the page with HUGE margins on either side. 
- I believe that content used to flex to fill the entire page in single view mode but this is no longer the case. I would like to see the content cover as much of the page as possible (equal margins on either side). I think it is currently being rendered how it would appear in a PDF, which isn't bad, but on bigger desktop screens this wastes a lot of usable space which would make reading over content much more efficient (you wouldn't have to scroll as much in long notes to read text).
    - If this is intended behavior please suggest a fix that I could implement in `userchrome.css` (I have tried to fix it myself but can't seem to find the right CSS elements to use).

![image](https://user-images.githubusercontent.com/15644021/147013028-1153dc33-dd0f-494e-a1bb-2b921ff3d7ec.png)
![image](https://user-images.githubusercontent.com/15644021/147013381-52300c38-14d2-42c1-ac32-cec814566a58.png)

## Environment
Joplin version: 2.6.10
Platform: Desktop 
OS specifics: Windows 10 x64

## Steps to reproduce
1. Create a new note.
2. Make a series of bullet points that create word wrapping.
3. Observe.

## Describe what you expected to happen
- Content should flex and fill the majority of the page for maximum text viewing.

## Logfile
- Available upon request. See screenshots for details.

**Comment by Daeraxa** [comment]
https://discourse.joplinapp.org/t/please-read-this-if-you-are-wondering-why-theres-now-a-margin-on-the-note-text/19585

**Comment by hffaust** [comment]
Ok cool, thanks for this. For anyone wondering, you can just go to Settings > Appearance > Advanced >Set Maximum Width (default is 600, I raised to 1000 and now it looks great)
