### ISSUE TITLE
cannot enter or exit full screen with shortcut "Control + Command + F"

### ISSUE THREAD

**Issue by WzyPaopao** [laurent22/joplin#5901]
## Environment

Joplin version: Joplin 2.6.10 (prod, darwin)
Platform: MacBook Pro (13-inch, M1, 2020)
OS specifics: macOS Monterey 12.0.1

## Steps to reproduce

1. press "Control + Command + F"
2. cannot enter or exit full screen model
3.

**Comment by graphit0** [comment]
Looks like a feature suggestion. Feature suggestions first go to the forum. Do you mind opening the topic there instead of this issue?

**Comment by WzyPaopao** [comment]
> Looks like a feature suggestion. Feature suggestions first go to the forum. Do you mind opening the topic there instead of this issue?

sure, thank you for your advice
