### ISSUE TITLE
When changing sync target to an empty target, Joplin behaves very oddly.

### ISSUE THREAD

**Issue by hamishmb** [laurent22/joplin#5904]
## Environment

Joplin version: 2.5.12
Platform: Linux
OS specifics: Linux Mint 20.2 Cinnamon x86_64 (Linux 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)

## Steps to reproduce

I think this might be hard to reproduce, but here's exactly what happened for me:

1. Start with Joplin syncing with Dropbox with 1000s of notes, some small, some big with attachments, some webpages.
2. Create a new empty local filesystem sync target folder (in this case in pCloudDrive, but shouldn't matter as just behaves like local storage).
3. Check the failsafe to prevent deleting is on (it was).
4. Change settings in Joplin and click sync.
5. Joplin starts adding notes to the sync target, but then also starts deleting others, so some notes are synced and some are deleted (no pattern I could identify).

I wish this was something easier to reproduce, but I'm really not sure what happened.

## Describe what you expected to happen

Having read the docs, it seems like either Joplin should try to delete all the notes (and hence be stopped by the failsafe), or sync all of them (hopefully). I have no idea why it would do some of both.

Also, why exactly is it that when presented with a new empty folder, and knowing the settings have just changed, that pCloud would try to delete notes? Perhaps it could be improved to recognise that scenario and behave differently, or ask the user what to do?

## Logfile

Sorry, this was from a little while ago and I wasn't aware of this feature.

Now I've completed the template I've sort of realised that this isn't a very easy-to-diagnose/reproduce bug report. I will try to provide any more information if that would help though, or run some more tests (I have a spare machine which I can use for that).

**Comment by graphit0** [comment]
Looks like a support ticket, how about we discuss the behaviour on the forum, close the issue for now and reopen it once we could reliably reproduce it?

**Comment by hamishmb** [comment]
Okay, that sounds reasonable. I will post on the forum with the information from here and link back here in case we want to reopen later.

**Comment by hamishmb** [comment]
Topic created at: https://discourse.joplinapp.org/t/when-changing-sync-target-to-an-empty-target-joplin-behaves-very-oddly/22592

**Comment by hamishmb** [comment]
No one every really replied on the forum, but this is a pretty awful bug so I think I will reopen it now.

Happy to answer any questions and/or try to reproduce myself, subject to time and headspace constraints.

**Comment by hamishmb** [comment]
Still an issue as far as I know.

**Comment by hamishmb** [comment]
No evidence to suggest this is fixed.
