### ISSUE TITLE
marked Bold text color issue

### ISSUE THREAD

**Issue by Sharar-Lykourgos** [laurent22/joplin#5905]
## Environment

Joplin version: 2.6.9
Platform: Linux
OS specifics: Fedora 35

## Steps to reproduce

1. Select the text.
2. Make the text Bold
3. Highlight the text
Note: swapping the steps 2&3 will give the wanted outcome ("Text 2").

## Describe what you expected to happen
Depending on the steps the color of the text will change between black and white.
![image](https://user-images.githubusercontent.com/96591262/147276585-e236711b-f839-4641-8096-1915ec35f61d.png)

**Comment by graphit0** [comment]
I could not reproduce the behaviour in this environment

Environment: 
- clean 2.6.10 installation 
- any standard theme (tried Dark/Light, default, solarised, nord, drakula)
- Rich text editor and markdown viewer
- Rich markdown plugin on and off
- OS: windows, linux

Could you check the behaviour on any other system? Maybe some custom css causing it?

**Comment by Sharar-Lykourgos** [comment]
After further testing (Changing OS, removing all custom CSS, upgrading to Joplin 2.6.10), the problem was the **color property** of the Strong element.

- Before disabling the color property 
![Strong property before](https://user-images.githubusercontent.com/96591262/147322515-67de5a21-27ef-4f10-b50f-f09a2927d4b7.png)

- After disabling the color property 
![Strong property After](https://user-images.githubusercontent.com/96591262/147324148-191d61a0-a6ec-418d-aae4-9acd87121836.png)

**Comment by graphit0** [comment]
Thanks for providing the solution for this problem. Does it mean that the issue is no longer relevant and may be closed?
