### ISSUE TITLE
Automatically destroying text formatting by adding "/" or space between text 

### ISSUE THREAD

**Issue by nahidashraf2000** [laurent22/joplin#5906]
#### When I format text in Joplin like highlighting, bold, italic, or making checkbox they sometimes lose the formatting style. Then when I check out the markdown view, there I can see automatically added space between markdown codes or "/" inside markdown code that resulting broken text formating.
This "/" or space is added automatically when I switch between different notebooks or pages of notebooks or minimize the program. 
When It was happening at first, I thought that it might be my fault that, I mistakenly added these, but this is now happening over and over again and I am sure that some other thing is the reason for it. 

#### This issue is bothering me for almost 2 months. It first started when I installed a plunging from "Joplin Plugins Repository" named "Automatic Backlinks to note". 
I removed that plugin, updated Joplin, and reinstall it but the problem remains the same.

I try to get help on Reddit but no one is facing the problem like me. 

### Screenshorts
![formating problem in joplin](https://user-images.githubusercontent.com/96440743/147282657-00d01a7a-ac2c-48bf-9478-baeecf3c850a.png)
![jopline bug image 2](https://user-images.githubusercontent.com/96440743/147282663-f88d7311-7fa4-42ff-b6dc-a0b84487c408.png)

## Environment

Joplin version: 2.6.9
Platform: Windows
OS specifics: 10

## Steps to reproduce

1. Make some text and format it like bold, italic, or highlight. You may install the "Automatic Backlinks to note" plugin from the "Joplin Plugins Repository" first as I think the plugin is the main devil behind it.
2. Switch between notes and different modes like markdown or normal view mode.
3. You may see text formatting is broken (it happens sometimes not always.)

## Describe what you expected to happen
Formating should not lose and should not add automatic "/" or space between markdown codes.

**Comment by graphit0** [comment]
As it looks like a support ticket, how about we discuss the behaviour on the forum, close the issue for now and reopen it once we could reliably reproduce it?

**Comment by Daeraxa** [comment]
It looks like you are trying to add bullet points and checkboxes within a table which I do not believe is standard valid markdown syntax.

What you are calling "normal edit mode" is a little misleading as it is a different editor entirely and it can currently produce output that is valid in HTML but not in markdown which leads to the "escaping" behaviour you see in your notes (as the richtext editor does not support markdown tags directly it will escape them if it encounters them to make sure they are preserved in the saved markdown data - all note data is saved as markdown regardless of the editor used)

The "normal" way of saving lists in markdown tables is something like:
```
a | b | c
- | - | -
<ul><li>1</li><li>2</li></ul> | b | c
```

Which will be preserved in both editors.
