### ISSUE TITLE
Android: all notebooks structure is lost after re-sync via Dropbox API

### ISSUE THREAD

**Issue by luzhanov** [laurent22/joplin#5908]
**Shot description:** When syncing notes using Dropbox (uploading from Windows, downloading then on Android), all notebooks structure is lost, but notes are synced. 

## Environment

Joplin version: 2.6.10 (prod,win32), rev 98fba37
Platform: Windows
OS specifics: 

and

Joplin version: 2.6.8, database v41
Platform: Android 
OS specifics: Samsung S10, Android 11, One UI 3.1

## Steps to reproduce

On Windows:
1. Export all existing data with multiple notebooks to the JEX file
2. Set up a Dropbox sync configuration
3. Execute "Delete local data and re-download from sync target", get an new local database 
4. Import all data from JEX file from the step 1, notebooks are visible as it was before
5. Sync all data using Dropbox sync (I have about 8k notes, 30k resources) until it will be finished sucessfully

On Android:

6. Install Joplin app from scratch
7. Set up a Dropbox sync configuration 
8. Run sync process (with resources in Auto mode) and wait until sync will be finished (it shows correct number about 8k fetched notes)
9. BUG: in "All notes" I can see all synced notes, but I can't see any of the notebooks except the default "Welcome! (mobile)"

## Describe what you expected to happen
All notebooks created on Windows should be visible on Android

Probably, on Android, we need some functionality like "Delete local data and re-download from sync target"? 

## Logfile

[syncReport-1640367728205.txt](https://github.com/laurent22/joplin/files/7774954/syncReport-1640367728205.txt)

**Comment by graphit0** [comment]
So, the notebook structure is lost (not synced) only on mobile? On desktop notebook structure has been imported correctly? 

To test could you add another instance of Joplin Desktop to the same sync target and tell if the structure is synced?

**Comment by luzhanov** [comment]
@graphit0 , I've tried to sync the same target on second Windows machine (using  "Delete local data and re-download from sync target") and everything is fine, I can see the correct notebooks structure.
So it looks like mobile client issue, not data structure issue.

**Comment by luzhanov** [comment]
The problem seems to be related to the background sync issue: when I make screen always enabled and left the phone for 4 hours, all folder structure finally was able to sync. 

But anyway, it should be fixed somehow.

**Comment by xiaoyaole3** [comment]
It seems happened to me the same. The notebooks structure are also lost.

When I try to sync from the remote, the Synchronization status shows that all the notes synced successful. But the notebookes structure are lost. I can see the folder in the status, but can't see it in the ontebooks tree. 

Is there any way to restore the notebookes structure?

Best wishes. 

Joplin version: 2.6.10
Platform: Android & linux
