### ISSUE TITLE
Spell-checker doesn't work correctly with Polish language.

### ISSUE THREAD

**Issue by mdros** [laurent22/joplin#5914]
When using spell-checker with language set to Polish, it seems that it does not detect incorrect words.

![spell-checker-issue](https://user-images.githubusercontent.com/43322021/147416619-5cccfac1-4222-47a7-81d6-75fd51b01b3d.png)

Joplin version: 2.6.10
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Select polish language in spell-checker. 
2. Activate spell-checker.
3. Spell-checker doesn't highlight errors.

## Describe what you expected to happen

Spell-checker should highlight the first word on the screen as it's incorrectly written.

**Comment by Daeraxa** [comment]
Your screenshot shows the markdown editor. Do you have the spellcheck option turned on in your markdown options?

**Comment by mdros** [comment]
I don't see such option in the Markdown settings.  (Tools -> Options -> Markdown)

**Comment by roman-r-m** [comment]
It's in Tools - Options - General

**Comment by mdros** [comment]
You're right, I didn't have that turned on - it works after enabling the feature :). Thanks, I'm closing the issue
