### ISSUE TITLE
 Tag names containing uppercase characters are converted to lowercase characters.

### ISSUE THREAD

**Issue by kdzik** [laurent22/joplin#5917]
Adding a tag with uppercase characters is impossible because tag names containing uppercase characters are converted to lowercase characters after submitting the "Add tag" dialog with new tags.

![tag1](https://user-images.githubusercontent.com/50631913/147417116-966e6811-4298-4935-92f7-37e9c9f714c5.png)
![tag2](https://user-images.githubusercontent.com/50631913/147417118-037e0d08-9817-435b-ba81-e393a9d329ed.png)

## Environment

Joplin version: 2.6.10
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Open "Add tag" dialog on note or to-do item
2. Input a tag name with uppercase letters.
3. Submit the "Add tag" dialog
4. Newly added tag name has all of the uppercase characters converted to lowercase characters

## Describe what you expected to happen
Tags names aren't converted to lowercase characters.

**Comment by mak2002** [comment]
Can I work on this issue?

**Comment by roman-r-m** [comment]
I wouldn't recommend it as I don't think there has been an agreement if it should be done at all.

**Comment by mak2002** [comment]
ok no problem.

**Comment by TheEvilCoder42** [comment]
I too would like to see this implemented; reasons for it can be found here: https://discourse.joplinapp.org/t/tags-lower-case-only/4220/59

**Comment by Wizardling** [comment]
Shame this was closed, as I find lowercase only tags both limiting and silly looking - like I didn't know how to spell.
