### ISSUE TITLE
Multiple UI bugs after upgrading from AUR

### ISSUE THREAD

**Issue by ErPiotta** [laurent22/joplin#5922]
## Environment

Joplin version: 2.6.10-4
Upgraded from: 2.4.12-1
Platform: Linux
OS specifics: Endeavour OS

## Steps to reproduce

1. Upgrade to latest version on the AUR
2. Open App
3. See multiple UI bugs

## Describe what you expected to happen

I read it was a pain to upgrade this, but the last version I downloaded is not working at all.

For example no icons showing

![Screenshot from 2021-12-27 18-47-22](https://user-images.githubusercontent.com/21013752/147495547-64ed08dd-67b8-477b-a6ce-57db0f4853bc.png)

On top of every old note I see some series of Xs, for example

![Screenshot from 2021-12-27 18-49-35](https://user-images.githubusercontent.com/21013752/147495693-aa5007a2-4ec3-4b26-94c4-13b264d6723b.png)

Not showing in the live previews.

Also as shown in the above screenshot it's very hard if not almost impossible to edit notes and selection doesn't work.

**Comment by laurent22** [comment]
Wrong forum, we don't maintain the AUR package.
