### ISSUE TITLE
The onStart function in the plugin is executed out of the plugin context 

### ISSUE THREAD

**Issue by przemekd** [laurent22/joplin#5924]
Joplin version: 2.6.9
Platform: Desktop
OS specifics: Linux

## Steps to reproduce

1.  Create a simple plugin using the code below:
```{typescript}
import joplin from 'api';

let script =  {
	onStart: async function() {
		return this._onStart()
	},
	_onStart: async function () {
		console.log("This should be logged")
	}
}
joplin.plugins.register(script);
```
2. Load the plugin in the development mode
3. Observe that `This should be logged` string is not printed

**Comment by laurent22** [comment]
That probably won't be supported. As a general rule you should avoid using `this` anyway which indeed means different things depending on how the function is called. In your particular case you could move your utility functions outside of that script object.

**Comment by przemekd** [comment]
Ok, I got you. The reason why did I ask about it is because I wanted to develop my own Joplin plugin using Scala.js. Scala.js generates code that uses `this` very often.

**Comment by laurent22** [comment]
I think that's unrelated. `this` doesn't work in this case because onStart is executed on application side, and onStart_ is on plugin side. For Scala, I imagine the whole lib will be on plugin side so it should just work.

**Comment by tessus** [comment]
Many plugins use 3rd party libraries, thus it shouldn't be a problem to use it as Laurent mentioned. I suggest to open a topic on the forum to discuss specific issues.

I'm going to close this ticket, since it isn't a bug.

**Comment by przemekd** [comment]
Yep, it should work if the Scala.js module works only as a 3rd party library, but I really wanted to have the whole plugin written in Scala and to build it using Scala build tool. This plugin code doesn't work because of the reason above:
```{scala}
import api.Joplin

import scala.scalajs.js.annotation._
import scala.scalajs.js
import scala.concurrent.Future
import scala.scalajs.js.JSConverters._

object Main extends App {
  println("registering plugin...")
  Joplin.plugins.register(new Planner())
}

class Planner extends api.Script {
  @JSExport
  def onStart(): js.Promise[Any] = {
    implicit val ec: scala.concurrent.ExecutionContext =
      scala.concurrent.ExecutionContext.global
    println("Hello world")
    // Future.successful(null).toJSPromise
    Future.successful(null).toJSPromise
  }
}
```
If the only way to make it work is to implement the plugin initialization in the JS/TypeScript and the rest in Scala.js that means that the build process of the plugin gets much more complicated. But if there is no other way, then... ¯\_(ツ)_/¯
