### ISSUE TITLE
My note content does not align to the left of the content frame, leaving a wide blank area

### ISSUE THREAD

**Issue by TencentSZ** [laurent22/joplin#5926]
## Environment

Joplin version: 2.6.10
Platform:  Joplin for deskop
OS specifics:  Windows 10 21H1

## Steps to reproduce

1. Just open any note

## Describe what you expected to happen

My note content does not align to the left of the content frame, leaving a wide blank area
![joplin-bug-02](https://user-images.githubusercontent.com/52615214/147569494-ae496ebd-7a29-408d-b59f-e90432ca7976.png)

I think it is caused by the body margin. I recently updated my Joplin from 2.5 to 2.6.10, then this issue took place.
![joplin-bug-03](https://user-images.githubusercontent.com/52615214/147569502-2ed555e0-adc0-4142-9c00-232d9313e884.png)

## Logfile
I do not have a DOM log. Please tell me if I could upload more screen snapshots to help solve this issue.

**Comment by Daeraxa** [comment]
https://discourse.joplinapp.org/t/please-read-this-if-you-are-wondering-why-theres-now-a-margin-on-the-note-text/19585
