### ISSUE TITLE
Cannot change the language of items in several menus

### ISSUE THREAD

**Issue by TencentSZ** [laurent22/joplin#5927]
## Environment

Joplin version: 2.6.10
Platform: Joplin for deskop
OS specifics: Windows 10 21H1

## Steps to reproduce

1. Install an old version of Joplin and switch the language setting to Chinese Simplified.
2. Update Joplin to 2.6.10
3. Switch the language setting to English.

## Describe what you expected to happen
Some items are displayed in English while some are still in Chinese.
![joplin-bug-302](https://user-images.githubusercontent.com/52615214/147572963-abdf15de-b95b-445c-80ac-e86bbdbd6da3.png)
![joplin-bug-301](https://user-images.githubusercontent.com/52615214/147572969-36de640c-f9ca-404c-9f7c-2293475b86f1.png)

**Comment by laurent22** [comment]
You need to restart the app and it should work. But looks like there was a regression because they should update without restarting the app.
