### ISSUE TITLE
arm64 Linux Appimage

### ISSUE THREAD

**Issue by chromer030** [laurent22/joplin#5932]
## Environment

Joplin version: 2.6.10
Platform: Linux
OS specifics: Ubuntu

## Steps to reproduce

1. Currently there is no appimage for arm64 OSes.
2. 
3. 

## Describe what you expected to happen
Please provide arm64 binaries.

**Comment by dayue1984** [comment]
yes, need arm64 app support, please

**Comment by toplinuxsir** [comment]
for linux arm64 build need! 
Thanks !

**Comment by nmfretz** [comment]
Hi @laurent22, have you considered building and pushing multi-arch images to docker hub that support both amd64 and arm64 architectures?
