### ISSUE TITLE
UX inconsistency: Cannot add icon to a new notebook

### ISSUE THREAD

**Issue by yann1cks** [laurent22/joplin#5934]
I want to report a UX inconsistency, not really a bug. I tried to add icons to a notebook. So I created a new notebook. But in this dialogue it is not possible to add an icon. I have to create the notebook and edit it again to add an icon.

## Environment
Joplin 2.6.10 (prod, linux)
Sync-Version: 3
Profil-Version: 41
Platform: Ubuntu 21.10 (Snap)

## Steps to reproduce
1. Create a new notebook. It is not possible to add an icon. (see Image 1)
2. Right click that notebook and edit it.
3. In this menu it is possible to add a icon. (see Image 2)

Image 1:
![image](https://user-images.githubusercontent.com/50637827/147750237-d975d9e7-873e-4b0d-9723-6dbdc72a545c.png)

Image 2:
![image](https://user-images.githubusercontent.com/50637827/147750296-2dd1e181-6a85-4404-bbb5-4a2fd20a7fd0.png)

## Describe what you expected to happen
I think it would be more consistent if an icon could be added directly when I create a new notebook. I would also be much easier for a new user to find the feature. Currently a new user will create several notebooks and only find this feature if he has to edit a notebook.

**Comment by laurent22** [comment]
Yes I've noticed this and plan to update.
