### ISSUE TITLE
Joplin does not match Windows 11 system theme

### ISSUE THREAD

**Issue by chadalen** [laurent22/joplin#5936]
## Environment

Joplin version: 2.6.10
Platform: Windows 11 (64-bit)
OS specifics: Windows

## Steps to reproduce

1. Set Windows 11 theme to dark
2. Open Joplin
3. In Joplin settings Tools -> Options -> Appearance -> Check "Automatically switch theme to match system theme"

## Describe what you expected to happen

In this scenario I have Windows 11 Dark theme turned on.
![explorer_X1hlbv5rtt](https://user-images.githubusercontent.com/12568665/147784490-be663a03-e917-4ed0-a831-f65546750809.png)

When I use Joplin the window frame is still white although I'm using dark theme in windows. Joplin's window frame should look like the file explorer's window frame in the picture above.
![Joplin_91JWVi5RbV](https://user-images.githubusercontent.com/12568665/147784522-969832fc-f785-4b12-b366-6b1f45d8173a.png)

**Comment by chadalen** [comment]
Still an issue

**Comment by chadalen** [comment]
Still an issue

**Comment by cadamsdev** [comment]
Still an issue

**Comment by jabberwock** [comment]
This is happening to me. To make matters worse, I can't read the editor text. I have the Windows 11 theme set to Light, and Joplin set to match the OS. But even if I change Joplin explicitly to light, I still see this:

![image](https://user-images.githubusercontent.com/88205/203077705-4220c6ef-e93b-4115-bad5-f43a88715979.png)
