### ISSUE TITLE
Incorrect build instruction in documentation

### ISSUE THREAD

**Issue by jooji-san** [laurent22/joplin#5947]
The build documentation instructs to run this command to install `Windows Build Tools`:
`yarn install -g windows-build-tools --vs2015`
However I suspect this is an error as it resulted in an error on my system and replacing yarn with npm resolved the issue.

**Comment by jooji-san** [comment]
https://github.com/laurent22/joplin/blob/4ed7c340a04131f351676cf5f581ced8428e7d2f/BUILD.md

**Comment by jooji-san** [comment]
It turns out the command is correct, but was deprecated recently. 
`yarn global add windows-build-tools --vs2015` should work fine.

**Comment by Daeraxa** [comment]
See this topic as well - https://discourse.joplinapp.org/t/attempting-to-build-on-windows/22559/14
The command isn't needed at all in some versions of node, just not sure what version these came in on - 16.13.1 at least has them so the command isn't required at all

**Comment by jooji-san** [comment]
okay, got it,  but i think the issue still stands.

**Comment by Daeraxa** [comment]
It does, yes, I was going to write a PR when I had a chance to do it but I think the line either needs removing entirely (if the tools are included in all node 16+ versions) or needs a comment saying that it is required only for 16.x+ (whatever version that may be).
