### ISSUE TITLE
Beta editor on mobile (Android) not scrolling screen when keyboard opened

### ISSUE THREAD

**Issue by Daeraxa** [laurent22/joplin#5949]
## Environment

Joplin version: 2.6.8 
Platform: Android
OS specifics: 11

## Steps to reproduce

1. Enable beta editor 
2. Create or open long note
3. Whilst in edit mode but with no keyboard displayed, select text near bottom of screen to open keyboard

On editing the text the editor does scroll to the correct position but this should happen as soon as keyboard is displayed

## Describe what you expected to happen

Screen should scroll upwards to display line being edited (as it does with old editor)

Screenshots - selecting line "Hhh" each time at bottom of screen.

**Old** editor:

![image](https://user-images.githubusercontent.com/58074586/147896391-239a2f5c-8e74-464c-96f3-18c31bdcfbe0.png)

**Beta** editor:
![image](https://user-images.githubusercontent.com/58074586/147896438-f485cbd2-906a-4be4-ad8f-66fbde304ead.png)

## Logfile

No warning or errors in log

**Comment by graphit0** [comment]
I could reproduce the issue on Android 9, for easier reference it  works on a welcome note called `5. Privacy`. Here's an video illustration

https://user-images.githubusercontent.com/44114323/149032203-9c5ea396-3300-463e-911d-8188e648135c.mp4

**Comment by Daeraxa** [comment]
No change in behaviour

**Comment by Daeraxa** [comment]
Still up

**Comment by Daeraxa** [comment]
Still up

**Comment by Daeraxa** [comment]
Still up

**Comment by Daeraxa** [comment]
up

**Comment by laurent22** [comment]
Sorry completely missed that bug, it should have been labelled.
