### ISSUE TITLE
Mermaid code blocks cause jumping in editor

### ISSUE THREAD

**Issue by KhaaL** [laurent22/joplin#5951]
This is a issue related to 
https://github.com/laurent22/joplin/issues/1546

Resubmitting a bug report as the issue behind the behaviour is (mostly) established: while mermaid support  is enabled, and mermaid code block is present, the editors autoscroll jumps around very inconveniently.

## Environment

Joplin version: 2.6.6
Platform: desktop
OS specifics: been reported on windows 10  and different linux distributions

## Steps to reproduce

Please see issue 1546 for elaborate steps on how to reproduce it.

(Writing this bug report from phone - sorry for the low quality)

**Comment by rushi1222** [comment]
Hi! i have downloaded the code from github but how to run it?

**Comment by KhaaL** [comment]
I _belive_ this is a copy of https://github.com/laurent22/joplin/pull/5929 and/or https://github.com/laurent22/joplin/issues/5918, after quickly testing  v2.7.7 - this unwanted behaviour dosen't seem to appear. Will close the issue.
