### ISSUE TITLE
Sharing encrypted notes doesn't work when users already have encryption enabled.

### ISSUE THREAD

**Issue by TeraHz** [laurent22/joplin#5958]
I just enabled encryption for my notes and that completely broke the sharing feature. I assumed this works but maybe it's not implemented yet. If that's the case, consider this a feature request.

## Environment

Joplin version: 2.6.10 Desktop
Platform: macOS
OS specifics: 11.6
Joplin Server: 2.6.14

## Steps to reproduce

1. Create users A and B on the server
2. Enable encryption for both users following guidelines
3. Create item (notebook/note/todo) as A and share with B
5. After sync, B sees "Encrypted" notebook and "One or more master keys need a password" banner. Under Encryption B's key is properly setup and A's key ID is listed under Missing keys. If B authors and shares with A the same thing happens for user A.

## Describe what you expected to happen
When sharing an encrypted note, all users should be able to decrypt the data with their own private key. This can be done by encrypting the data with a common key and encrypting that key with the user's key (once per user). GnuPG does something like this when sending the same data to multiple recipients. 

## Logfile
Is the log sanitized enough for me to post it here?

**Comment by laurent22** [comment]
Do both sides have a public/private key pair? You can check that under Config > Encryption

And are you sure both clients are 2.6.10?

**Comment by TeraHz** [comment]
Yes, both users have their own key and  both are on 2.6.10 on the desktop.

 On mobile (Android) we're on 2.6.8 and we see the same behavior with the app reporting missing password for the key of the author's ID. 

Let me know what I can provide to make it easier to find the culprit.

**Comment by laurent22** [comment]
Seems like a basic setup which I've tested many times, so not sure why it doesn't work. I'll need to check if something's been broken in a recent release and I'll get back to you if logs or other things are needed.

Just in case, could you check the log to see if there's any error related to encryption or sharing? Ideally errors at the time when the notebook was shared and accepted by the other client.

**Comment by TeraHz** [comment]
Ok, I think I see what happened. 

Going through the logs on user B's desktop client I see a bunch of "DecryptionWorker: cannot start because no master key is currently loaded." around the first time a share was accepted. This makes me think the timing of enabling encryption and accepting the share is not as I reported above. It looks like User A had encryption, shared notes with user B. Then user B enabled encryption, and that caused the bad state. 

A simple unshare/share fixes the issue unless there are attachments. For those, I had to delete/create the attachments (thankfully only a handful).

Let me know how you want to proceed here.

**Comment by deuts** [comment]
Although this issue has been closed, I hope you can update the [docs](https://joplinapp.org/share_notebook/) for the benefits of others. Basically, in order to make sure that notebooks are encrypted on the server when sharing notebooks, make sure that the app has encryption enabled on the account of the sharer and also the sharee. Otherwise, you'll leave it unencrypted in the selfhosted Joplin server.
