### ISSUE TITLE
Expired SSL cert on joplin.cozic.net

### ISSUE THREAD

**Issue by leprasmurf** [laurent22/joplin#596]
Looks like the SSL cert expired on joplin.cozic.net yesterday.

It might be beneficial to consider [automatic renewal](https://certbot.eff.org/docs/using.html#automated-renewals).

**Comment by laurent22** [comment]
Thanks for letting me know, that's strange certbot was set to auto-renew and indeed did, it but somehow it's serving the expired cert. I've open a thread about it on letsencrypt.org

**Comment by laurent22** [comment]
Actually I was mistaken, the domain is hosted on GitHub and it seems they forgot to renew it on time. Thankfully it's fixed now so it should be fine.
