### ISSUE TITLE
Upgrade/Install plugin unable to get local issuer certificate

### ISSUE THREAD

**Issue by drcobra** [laurent22/joplin#5961]
## Environment

Joplin version: 2.6.10
Platform: Windows
OS specifics: Windows 10 Enterprise 20H2

## Steps to reproduce

1.  Tools > Options > Plugins
2. Try to install any plugin or upgrade an existing one
3. A OK Message box comes up "Could not install plugin: unable to get local issuer certificate"
![image](https://user-images.githubusercontent.com/13187283/148370714-c7cf33e0-7308-41b3-9df2-e6af2b9331f2.png)

## Describe what you expected to happen
Currently it blocks updates and installs of plugins.
This is happening only on my company laptop, not on my personal.
Any ideas how to overcome this? Install a specific certificate?

## Logfile
2022-01-06 10:40:15: useOnInstallHandler: "Error: unable to get local issuer certificate
Code: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1507:34)
    at TLSSocket.emit (events.js:376:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)"

**Comment by dpoulton-github** [comment]
Joplin / Electron has its own certificate store and does not use any that may have been installed on your system. It seems that this error has occurred to others using company networks as well. Basically, Joplin does not have access to the certificate your company has installed on your computer to allow it to monitor all your HTTPS traffic.

https://discourse.joplinapp.org/t/unable-to-get-local-issuer-certificate-company-firewall/22526
https://discourse.joplinapp.org/t/unable-to-check-for-update-or-sync-employer-firewall/6397
