### ISSUE TITLE
Links between Joplin Cloud published notes do not work

### ISSUE THREAD

**Issue by auyeunt** [laurent22/joplin#5977]
Two notes are published, verified separately. If each note contains a link using the ":/noteId" format, the link is verified to work in the Desktop App Viewer, but the corresponding links in the published HTML documents do not work. When clicked, "This note has not be shared" is reported.

## Environment

Joplin version: 2.6.10
Platform: Debian Linux
OS specifics: Linux version 5.14.0-3-amd64

## Steps to reproduce

1. Create two notes
2. Create a link from one note to the other using `[click here](:/noteId)`
3. Publish both notes
4. Click the corresponding link in the HTML document
5. Test it [here](https://nu5jakcc6e.joplinusercontent.com/shares/VogIcwMEVPAazvp0RvNOtx3epYlJsahS), scroll to the bottom of the page, neither the link to self nor the link to another note works. The other note is published [here](https://nu5jakcc6e.joplinusercontent.com/shares/SRbIvacrtd1X50f1YYB3AI4bGTDbFhgL).

Investigating https://joplincloud.com/js/items/note.js reveals the following code:
```javascript
	document.addEventListener('click', event => {
		const element = event.target;

		// Detects if it's a note link and, if so, display a message
		if (element && element.getAttribute('href') === '#' && element.getAttribute('data-resource-id')) {
			event.preventDefault();
			alert('This note has not been shared');
		}
	});
```
It appears that the click handler alerts 'This note has not been shared' whenever a link is a reference to another Joplin note. I think this is a crucial features to some users like myself.

## Describe what you expected to happen

The link should take the browser to the linked published note instead of returning a message of "This note has not been shared."

**Comment by laurent22** [comment]
See here for the rational: https://github.com/laurent22/joplin/blob/dev/readme/spec/server_sharing.md#linked-note

Basically we don't allow linked notes to be accessible because you could end up accidentally sharing more than you want.
