### ISSUE TITLE
SQLITE_DATABASE not use everywhere

### ISSUE THREAD

**Issue by tomamplius** [laurent22/joplin#5980]
Issue on migrate starting server with SQLITE_DATABASE=/var/lib/joplin-server/db.sqlite
application want to create database on /usr/lib/joplin-server/server/temp/joplin.sqlite
![image](https://user-images.githubusercontent.com/6951820/148645846-a63c4a72-dcc5-413a-abeb-c2237b1a62e7.png)
## Environment

Joplin version: 
Platform: linux debian 11

## Steps to reproduce
remove write on /server/temp/

## Work Arround 
Allow to create database not used
~~~
chown joplin-server:joplin-server /usr/lib/joplin-server/server/temp/
~~~

**Comment by laurent22** [comment]
That's a different db, more like a cache, and it's written inside the container.

**Comment by tomamplius** [comment]
Oh, sorry for my misunderstanding of this temporary db .
Just one question before closing, temporary folder can be defined on env variable?

Regards,

**Comment by laurent22** [comment]
No it's simply hard coded to `${serverRootDir}/temp` at the moment. Any reason why you would want to change that?

**Comment by tomamplius** [comment]
It's what i have understand when i have check source code.
I use joplin server on lxc( proxmox ) environement and i use deb file to deploy.
when i create deb file, i usually split source code on /usr and data in /var when i can. 
And when i can't, i do whiteout :-p

Thanks a lot for your time.
And tanks you about Joplin application used every days by my familly

**Comment by crivchri** [comment]
> It's what i have understand when i have check source code.
> 
> I use joplin server on lxc( proxmox ) environement and i use deb file to deploy.
> 
> when i create deb file, i usually split source code on /usr and data in /var when i can. 
> 
> And when i can't, i do whiteout :-p
> 
> 
> 
> Thanks a lot for your time.
> 
> And tanks you about Joplin application used every days by my familly

Hi @tomamplius,

Would you mind to share how you created a deb file for installing Joplin on Linux?

I would like to install **Joplin Server** in a LXC container with Debian 12, but I did not manage to make it work.

Thanks a lot and kind regards!

**Comment by tomamplius** [comment]
@crivchri https://git.lgy.fr/thomas/debmaker/src/branch/master/ressources/joplin-server
