### ISSUE TITLE
Can't sync from android to desktop after fresh install

### ISSUE THREAD

**Issue by aclifton314** [laurent22/joplin#5983]
Joplin Desktop for Linux: 2.6.10
Joplin for Android: 2.6.8
OS: Pop_OS 21.10
Android 12 
Sync provider: Nextcloud (Cloudamo)

I was having some sync issues between my android device and desktop so I decided to start fresh. Here is what I did:
1) Exported all notes and notebooks to a jex file and also to a joplin export directory (just to be safe).
2) Uninstalled Joplin on my desktop by removing the files in `~/.config/joplin-desktop`, `~/.joplin`, and `~/.local/share/applications/appimagekit-joplin.desktop`.
3) Removed the joplin sync folder in my nextcloud instance.
4) Uninstalled Joplin on my android device.
5) Used the following command to re-install joplin on my desktop: `wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash`
6) Opened joplin on my desktop and imported the jex file.
7) Set up the Nextcloud syncronization folder, configured the syncronization on my desktop, and syncronized.
8) Followed the instructions to set up end to end encryption.
9) Resynced from desktop. Waited until this completely finished.
10) Downloaded the joplin android app through the Aurora store.
11) Set up Nextcloud synchronization on the android app.
12) Synced to the joplin android app.

After doing this, everything that was on my desktop joplin was also on my android joplin. I then wanted to see if there were any syncing issues going both directions (desktop to android and android to desktop). Here is what I did:
1) Opened the desktop joplin app and made a change to a note.
2) Syncronized from the desktop joplin app. I have about 740 notes and this took 154 seconds. I then closed the desktop joplin app.
3) After about 15 minutes, I opened the android joplin app and synchronized. This syncronization took 21 seconds.

I first checked to see if there were any note conflicts and there weren't. I checked the note that had the change and the change had been successfully pushed. So at this point, it appears syncing from desktop to android works fine. 

To test the synchronization in the other direction I did the following:
1) Made an additional change to the same note from my android.
2) Synchronized from the android. This took 18 seconds. I then closed the android joplin app.
3) After 15 minutes, I opened joplin on my desktop and synchronized. This took 4766 seconds.

I checked for any conflicts and there weren't any. However, I did not see the additional change made on the android side. Any ideas what might be going on or if I'm messing something up? Thanks in advance for your help!

[log.txt](https://github.com/laurent22/joplin/files/7833828/log.txt)

**Comment by graphit0** [comment]
So, could moving to another Nextcloud provider solve the issue?

**Comment by aclifton314** [comment]
@graphit0 Thanks for your response. I've been working through this on the Joplin forum and it appears it might be specific to cloudamo. Syncing works when I switch to Dropbox. I'm testing out another Nextcloud provider now. I'll close this issue out and continue the updates on the forum: https://discourse.joplinapp.org/t/cant-sync-from-android-to-desktop-after-fresh-install/22966/6
