### ISSUE TITLE
Android beta editor Cursor 

### ISSUE THREAD

**Issue by Saturo78** [laurent22/joplin#5987]
## Environment

Joplin version: 2.6.8
Platform: Android
OS specifics: 

## Steps to reproduce

1. Switch to dark or nord theme
2. set beta editor
3. go to the editor page and look for the cursor

## Describe what you expected to happen
I would like to see the cursor, but its to dark.

**Comment by Saturo78** [comment]
Hey thats really nice. Nobody has done absolutely nothing and the ticket is closed.
This behavier motivates me extremly to open other issues.
Thank you very much!
*this is ironic*

**Comment by tessus** [comment]
> this is ironic

Not really. We apparently missed that issue and the bot added a comment 8 days ago. As mentioned in the comment:

**You may comment on the issue and I will leave it open.**

Well, since nobody replied, the bot closed the ticket.

**Comment by korg91** [comment]
I've opened a new bug [here](https://github.com/laurent22/joplin/issues/6174), thanks in advance to anyone who's going to look into this :)

**Comment by Daeraxa** [comment]
Why open a new one for the same issue?

**Comment by korg91** [comment]
Apologies, I didn't see that @tessus had reopened this. I've closed the new issue (but you can refer to it for some screenshots).

**Comment by personalizedrefrigerator** [comment]
I've also been experiencing this. With an external keyboard, the handle below the cursor is invisible and the cursor is very hard to see (screenshot is zoomed in):
![External keyboard: Very faint cursor](https://user-images.githubusercontent.com/46334387/156931300-cc75730f-87ef-4eac-ac15-a6bb3d1f0be4.jpg)

**Comment by personalizedrefrigerator** [comment]
> I've also been experiencing this. With an external keyboard, the handle below the cursor is invisible and the cursor is very hard to see (screenshot is zoomed in): ![External keyboard: Very faint cursor](https://user-images.githubusercontent.com/46334387/156931300-cc75730f-87ef-4eac-ac15-a6bb3d1f0be4.jpg) I'm on Android 11.
> 
> **Edit**: I've tested the beta editor on iOS and it the cursor is clearly visible when using a dark theme. This seems like an Android-specific issue.
> # Possibly-relevant Files
> 
>     * https://github.com/laurent22/joplin/tree/dev/packages/app-mobile/components/NoteEditor
> 
>     * https://github.com/laurent22/joplin/tree/dev/packages/lib/themes
> 
>     * There's also [`assets/highlight.js`, but I think this belongs to a dependency of Joplin](https://github.com/laurent22/joplin/tree/dev/packages/renderer/assets/highlight.js).
> 
> 
> We'll probably have to add [`caret-color: white;`](https://developer.mozilla.org/en-US/docs/Web/CSS/caret-color) to the CSS somewhere...

I think I was able to fix it locally!!! Expect a PR soon-ish!
