### ISSUE TITLE
[Desktop] Problems with search results + new note 

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#5993]
* Search for some text.
* While the search results are displayed, create a new note
* The new note is displayed in the search results even if does not contain the searched text

Another smaller issue is that until you created a new note it's not indicated in which notebook it's going to end up.

![image](https://user-images.githubusercontent.com/995612/148782454-416ae1a3-d7dd-4849-951d-cab87455143e.png)

**Comment by laurent22** [comment]
What would be the expected behaviour in this case?

**Comment by roman-r-m** [comment]
Initially I thought either prevent new note creation when search results are showing or clear search. I am not sure anymore. 

Had a look at VS Code but it's very different in that when I create a new file it's not saved. So even if I put the search text in, it won't show in search results until it's saved.

I found Joplin behaviour strange here but maybe it's not worth spending time on this. I'll close it.
