### ISSUE TITLE
Edit menu inside Options/configurations shows empty menu

### ISSUE THREAD

**Issue by yafp** [laurent22/joplin#6]
If i navigate via "Tools" -> "Options" to the configuration UI i found a small visual bug within the menu.

The Edit menu is enabled but shows an empty menu (at least that is what i am assuming).
Disabling the menu would most likely make more sense as long as there is no menuitems coming in the future.

System:  
* Joplin 0.10.25 (prod, linux)
* Joplin 0.10.28 (prod, linux)
Screenshot: 

![20171130_130330](https://user-images.githubusercontent.com/67605/33430071-7fdd2ada-d5cf-11e7-8d74-2c420d6fa9f0.png)

As a sidenote: calling the menu "options" and the options UI then  "configuration" is somehow misleading/(confusing ;)

**Comment by laurent22** [comment]
Thanks for the bug report, this issues should be fixed now.
