### ISSUE TITLE
npm install need a ssh private key

### ISSUE THREAD

**Issue by ytianxia6** [laurent22/joplin#6003]
I use a docker to install joplin, but it get error by the github Permission denied!
the `npm install -g joplin` command need a ssh key to download github!
Why? 

Joplin version: 2.6.2
Platform: docker
OS specifics: docker on windows

## Steps to reproduce

1.  create a new Dockerfile
```
FROM node:16
RUN su node -c "npm install -g joplin"
```
3. 
get the error 
```
#6 45.39 npm ERR! code 128
#6 45.39 npm ERR! An unknown git error occurred
#6 45.39 npm ERR! command git --no-replace-objects ls-remote ssh://git@github.co
m/laurent22/uslug.git
#6 45.39 npm ERR! Warning: Permanently added 'github.com,20.205.243.166' (ECDSA)
 to the list of known hosts.
#6 45.39 npm ERR! git@github.com: Permission denied (publickey).
#6 45.39 npm ERR! fatal: Could not read from remote repository.
#6 45.39 npm ERR!
#6 45.39 npm ERR! Please make sure you have the correct access rights
#6 45.39 npm ERR! and the repository exists.
```

## Describe what you expected to happen

I hope the terminal version can be install in a clear Dockerfile!

**Comment by laurent22** [comment]
We neither support npm nor installing the terminal app via a dockerfile

**Comment by ytianxia6** [comment]
Isn't it installed via npm? I find it in this page:
https://joplinapp.org/terminal/

**Comment by laurent22** [comment]
Oh, sorry, I thought you were trying to build the app. Installing it is indeed done with npm. But I don't know what you want to do with the dockerfile, as we don't support this.

**Comment by ytianxia6** [comment]
as I always write note on different pc, I want to make a server to do the sync and the publish blog.
I don't want to install the publisher everywhere.

**Comment by rxliuli** [comment]
> as I always write note on different pc, I want to make a server to do the sync and the publish blog. I don't want to install the publisher everywhere.

Maybe you can take a look here: https://joplinapp.org/terminal/
