### ISSUE TITLE
Error: Cannot find module '/tmp/.mount_JoplincwH1KJ/resources/electron.asar/browser/init.js'

### ISSUE THREAD

**Issue by lightzhan** [laurent22/joplin#601]
### Operating system

- Linux

### Application

- Desktop

I update it from 1.0.96 to 1.0.97,but when I run the latest version, it tells me "Error: Cannot find module '/tmp/.mount_JoplincwH1KJ/resources/electron.asar/browser/init.js'", the 1.0.96 is all ok!

**Comment by foxmask** [comment]
same 
```
module.js:487
    throw err;
    ^

Error: Cannot find module '/home/tmp/.mount_Joplin3G9Z5a/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
```

**Comment by laurent22** [comment]
Seems the latest release of Electron Builder [is broken](https://github.com/electron-userland/electron-builder/issues/2958). I'm going to downgrade it for now and that should fix the issue.

**Comment by laurent22** [comment]
Could you check the latest version to see if it solves the crash?

**Comment by foxmask** [comment]
it's working, yes

**Comment by lightzhan** [comment]
It is ok now! : ) Thank you!

**Comment by stupns** [comment]
It is now mistake 
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_IGdm.AB9DAcO/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
