### ISSUE TITLE
AUR versions did work for me this time, I had to fallback to Flatpak.

### ISSUE THREAD

**Issue by erm3nda** [laurent22/joplin#6015]
## Description

First, I was on the windows client, got update, and db was also updated.
When i moved to the linux box, joplin didnt' work due to new database, so I tried to update the usual way (yay -S joplin-desktop)
Then it complained compiligin a python3-module which name I dont remember, so I installed the libffi7 to make it compile.

- Compiled version from AUR repositories (joplin-desktop): Not fully working, bad fonts, unusable edit panel. I had to download first the libffi7 package, because the compiler is not able to do the work using the current version (libffi8).
Some xxxxxxx (which are not part of the text) appeared, and wasn't able to put the cursor at my will and write ( see it https://imgur.com/GRwmYvy.png).

- AppImage version from AUR repositores (joplin-desktop-bin): Didn't open due to be and older version (outdated AppImage ??).

**Reading the readme I found the **"Flatpak"** reference, and worked.**

## Environment

Platform: Linux
OS specifics: Manjaro

## Steps to reproduce

1. Update joplin database to latest from Windows
2. Update joplin-desktop with yay
3. Update joplin-destktop-bin with yay

I don't know if the prior database update from Windows is part of the issue, im just describing it accurately.

## Describe what you expected to happen

Expected to be blond and tall, did not happen.

## Logfile

I have undone everything and deleted all before come here and saw Flatpak option, so I don't hold anything.

**Comment by Daeraxa** [comment]
The AUR (and for that matter flatpak) distributions are not officially supported, the appimage is the only supported version on Linux.
