### ISSUE TITLE
[Feature request] Notebook / tag intersection searches

### ISSUE THREAD

**Issue by msbentley** [laurent22/joplin#602]
This is a general feature request across all supported platforms. Currently I can choose to browse by tag, or browse by notebook. Often I want to find notes within a specific notebook having a given tag. If not done via the GUI, I would be very happy with a search syntax that lets me specify this. 

For example in Evernote I often search like:

notebook:project1 tag:todo

or similar.

**Comment by foxmask** [comment]
could be dup of #293

**Comment by frogger72** [comment]
Totally agree - this could be impemented as parsing tag:mytag and notebook:mynotebook in the seach syntax
