### ISSUE TITLE
Some Pictures are Rotated to the Wrong Direction within Joplin

### ISSUE THREAD

**Issue by pdolinic** [laurent22/joplin#6023]
Issue: Some Pictures turn to the wrong direction within Joplin notes, even though they are correct in the Original.

Platforms: All, since it is based on the Original Import to Joplin.

Fix: Give some Possibility/Button that allows Pictures to Rotate within Joplin.

**Comment by Daeraxa** [comment]
Can you provide an import file that showcases this? Importing from what application or format?

**Comment by pdolinic** [comment]
Hi, I believe it might be how Joplin is treating the metadata, a toggle might still be a way to avoid it?

command:
file IMG_20220114_104041.jpg


output:

IMG_20220114_104041.jpg: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=7, model=Pixel 6 Pro, height=3072, manufacturer=Google, orientation=upper-right, datetime=2022:01:14 10:40:42, width=4080], baseline, precision 8, 4080x3072, components 3

**Comment by pdolinic** [comment]
Hi, I believe it might be how Joplin is treating the metadata, a toggle might still be a way to avoid it?

command:
file IMG_20220114_104041.jpg

output:

IMG_20220114_104041.jpg: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=7, model=censored, height=3072, manufacturer=censored, orientation=upper-right, datetime=2022:01:14 10:40:42, width=4080], baseline, precision 8, 4080x3072, components 3
