### ISSUE TITLE
Long path in "Export profile" prevents tapping OK button

### ISSUE THREAD

**Issue by szpak** [laurent22/joplin#6026]
Having long value in the "Export profile" path, the UI formatting gets corrupted and it is impossible to hit the OK button.

## Environment

Joplin version: 2.6.8
Platform: Android
OS specifics: Android 12, Pixel 3a

## Steps to reproduce

1. Type long path in the "Export profile" field (longer than a screen width)
2. Try to hit OK to start the export.

## Describe what you expected to happen

![image](https://user-images.githubusercontent.com/148013/149679552-31382460-d2a5-4a48-b000-46648482b7ac.png)

The UI formatting is broken and the OK button is no longer accessible.

It is a minor issue, as the phone orientation can be changed to horizontal or shorter path can be used. However, I report it, as it would be probably somehow "easy" to fix, together with some other changes in the Configuration UI.

## Logfile

Not needed.

**Comment by szpak** [comment]
The latest version from Google Play (2.6.8) is still affected by this problem. Please reopen.

**Comment by szpak** [comment]
It's still on with 2.7.2. @roman-r-m, could you reopen this issue?

**Comment by Tolu-Mals** [comment]
I'm working on this
