### ISSUE TITLE
[MacOS] Multiple version updates for Desktop version

### ISSUE THREAD

**Issue by sunjam** [laurent22/joplin#603]
### Operating system
- macOS

### Application
- Desktop

On MacOS I was received multiple, staggered version update notices to *97 and then to *99.  Unsure if there is any need to install them in a specific order.  It was confusing because as soon as I selected "Yes" on the *97 download and install notice I was then given a new notice for the *99 update.

**Comment by laurent22** [comment]
97 was a mistake (it crashed on Linux) so you only need 99.
