### ISSUE TITLE
Vertical line in the markdown editor 

### ISSUE THREAD

**Issue by RGBYCP** [laurent22/joplin#6030]
I see a strange vertical line in the markdown editor. Please see below in the picture. 
To be fair, I have a lot of plugins installed. I don't know if this is caused by one.
Thank you.

## Environment

Joplin version: Joplin 2.6.10 
Platform: MacOS
OS specifics:  Catalina

<img width="520" alt="Screenshot 2022-01-17 at 16 49 05" src="https://user-images.githubusercontent.com/52494421/149801242-ef2ea419-8728-4f00-b9e5-2ceba3c0c21e.png">

**Comment by graphit0** [comment]
It's a gutter from Folding plugin, it's not quite working with non-zero Editor maximum width. So you either disable the plugin or set Editor maximum width to 0. Does it solve the issue?

**Comment by RGBYCP** [comment]
Dear Graphit0, thank you. Indeed, this works with Editor maximum width = 0. The vertical line shifts left and is not over the text. I think I will disable for the moment the Athena plugin. Thank you.
