### ISSUE TITLE
[Flatpak] External editor won't open

### ISSUE THREAD

**Issue by 12people** [laurent22/joplin#6036]
## Environment

Joplin version: 2.6.10
Platform: Linux
OS specifics: Ubuntu 21.10

## Steps to reproduce

1. Open up the flatpak version of Joplin.
2. Specify any executable for the external editor in Settings.
3. Try to open up the external editor from any note.
4. Nothing happens.

## Describe what you expected to happen

Joplin should open the external editor.

**Comment by CalebJohn** [comment]
Please report this to the [flathub packager](https://github.com/flathub/net.cozic.joplin_desktop/issues). The flatpack version is maintained by a third party, and there's not much we can do in our end.
