### ISSUE TITLE
[Feature Request] Create Plain Text Note

### ISSUE THREAD

**Issue by sunjam** [laurent22/joplin#604]
I'd like to request the ability to create a note as plain text, with no formatting.  This could also benefit issue #316 and issue #228

**Comment by laurent22** [comment]
Markdown is already plain text though. How would this feature work exactly?

**Comment by sunjam** [comment]
Hi.  Well, in my experience Joplin does not save as plain text.  I'd like
to write a plain text file in either Joplin or my synchronized location and
be able to edit it in Joplin/synchronized location with no formatting
additions.

Example is to create testfile.txt
Contents:  This is a plain text file.  This is a test.

I'd like to edit this in Joplin, but also continue seeing it at my
synchronized location as testfile.txt with no other formatting at all.

**Comment by zblesk** [comment]
Are you sure Joplin is the right tool for you, then? Sounds like you just want text notes in folders. Why use Joplin at all?

**Comment by sunjam** [comment]
Because plain text files means that markdown files will also be properly
synced with Joplin.  Quite a useful thing to have!

**Comment by ReekyMarko** [comment]
I think you are referring to the meta information that Joplin keeps in the files. To my knowledge, this is the very basis Joplin is able to sync and attach files, etc. To remove this, the information would need to be stores elsewhere and require a serious rework of the whole application. I can imagine the owner wouldn't be too keen to do that.

**Comment by laurent22** [comment]
Removing the metadata is indeed not possible, however in the next release there will be feature to open a note [in an external editor](https://github.com/laurent22/joplin/issues/611) which might do the trick.

**Comment by kcrossen** [comment]
This fails, for example:
```
SELECT 
  tool.id, 
  tool.name, 
  user.name,
  CASE user.type
    WHEN /* LURKER */ 0 THEN 'Hidden (0)'
    WHEN /* MEMBER */ 1 THEN 'Member (1)'
    ELSE 'Unknown'
  END AS user_type 
FROM tools.tool AS tool 
JOIN tools.user AS `user` 
ON (tool.user_id = user.id) 
```
Some of the asterisks are removed and the backticks are removed from user, so the SQL fails when copied directly from note. To function correctly, must switch to edit mode before copying.

**Comment by kcrossen** [comment]
Would be great to have a method to direct copy a note entirely and have it be as entered rather than as displayed, though of course it's pretty frightening to have your entered text seem to have been massed with seemingly arbitrarily.

**Comment by kcrossen** [comment]
Possible workaround enclose code (as above) in:
```
code here
```

**Comment by laurent22** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/1285584/65193498-36faa180-da73-11e9-9cb9-d62566f4cffc.png)

**Comment by laurent22** [comment]
Also works:

![image](https://user-images.githubusercontent.com/1285584/65193531-55f93380-da73-11e9-9b77-c936f7edf00b.png)

**Comment by kcrossen** [comment]
On  macOS 10.12.6, Joplin downloaded and installed today, appears not to work:
![screenshot_191](https://user-images.githubusercontent.com/1951504/65206565-cd6f9880-da5c-11e9-914d-749aef50b53f.jpg)

**Comment by kcrossen** [comment]
Moreover, if you select all, copy in right-hand pane on macOS or in view (not edit) mode on Android Pie (both downloaded and installed today, i.e. the latest posted versions), the pasted text will look like the right-hand pane. In other words missing characters such that it will error out. On Android, if the text is enclosed in triple backticks, and is then select all, copied in view mode, after the text is pasted into SQL query app, it will execute correctly.

Not sure where the problem is but I've verified issue this several times on both macOS and Android.

The notebook itself was authored on macOS and is treated as readonly on Android.

**Comment by kcrossen** [comment]
Further problem: If on macOS (1.0.167,  32865f0) enclose the SQL in triple backticks, use the notebook/note on Android (1.0.305, September 10, 2019) (in view mode) select all, copy, then paste into RemoDB, the SQL will execute but all the newlines will have been removed (very hard to read).
```
SELECT TABLE_NAME, 
       CONCAT(CONCAT(TABLE_NAME, ':'), '\n',
              GROUP_CONCAT(COLUMN_NAME, '\t', 
                           TABLE_NAME, '.', COLUMN_NAME, '\t',
                           TABLE_NAME, '.', COLUMN_NAME, ' AS ', TABLE_NAME, '_', COLUMN_NAME, '\t',
                           ' {', COLUMN_TYPE, '}'
                           SEPARATOR '\n')) AS table_columns
FROM
(SELECT COLUMNS.TABLE_SCHEMA AS TABLE_SCHEMA, COLUMNS.TABLE_NAME AS TABLE_NAME, 
        VIEWS.TABLE_NAME AS VIEW_NAME, 
        COLUMN_NAME, DATA_TYPE, COLUMN_TYPE, COLUMN_KEY, EXTRA, 
        CASE WHEN (COLUMNS.TABLE_SCHEMA IN 
                   ('information_schema', 'mysql', 'performance_schema')) THEN 'META' 
             ELSE '' END AS SCHEMA_GROUP 
 FROM information_schema.COLUMNS AS `COLUMNS` 
 LEFT JOIN information_schema.VIEWS AS `VIEWS` 
 ON (COLUMNS.TABLE_SCHEMA = VIEWS.TABLE_SCHEMA) AND 
    (COLUMNS.TABLE_NAME = VIEWS.TABLE_NAME) 
 WHERE (COLUMNS.TABLE_SCHEMA NOT IN ('information_schema', 'mysql', 'performance_schema')) 
 ORDER BY SCHEMA_GROUP, COLUMNS.TABLE_SCHEMA, COLUMNS.TABLE_NAME) AS table_columns
GROUP BY TABLE_NAME;
```
becomes
```
SELECT TABLE_NAME, CONCAT(CONCAT(TABLE_NAME, ':'), '\n', GROUP_CONCAT(COLUMN_NAME, '\t', TABLE_NAME, '.', COLUMN_NAME, '\t', TABLE_NAME, '.', COLUMN_NAME, ' AS ', TABLE_NAME, '_', COLUMN_NAME, '\t',
...etc... arbitrarily wrapped...
```
On the other hand, if in edit mode on Android, I select all, manually exclude the triple backticks from the selection, copy, then the pasted text is fine (as in the top example above).

So apparently I have a choice (as my macOS/Android executables work anyway) between tedious extra work to use the SQL "cheatsheet" or wrong display of code that will copy correctly in edit mode.
