### ISSUE TITLE
[Regression] Scroll position is not remembered when a note is switched

### ISSUE THREAD

**Issue by ken1kob** [laurent22/joplin#6042]
The scroll position of Markdown Editor is sometimes not remembered when a note is switched.

It was almost suppressed in v2.6.7, but it sometimes happens again in v2.7.6. 

### Steps to reproduce
1. Set Editor Layout mode "Editor" or "Split".
2. Select a long note and scroll down it to its middle.
3. Select another note.
4. Select the first note again. Sometimes Editor's scroll position goes to the top of the note.

Its occurrence is probabilistic. If it doesn't happen, repeat the step 3 and 4 several times. If it doesn't happen after several trials, try another long note.

**Comment by ken1kob** [comment]
### Analysis

The figure below is the message diagram between Markdown Editor and Viewer when the symptom happens.

![bad-scpos](https://user-images.githubusercontent.com/16041683/150379208-be7d0111-c29f-4ab0-ae38-48fe62a616f4.png)

Its timeline is as follows.

1. A note is switched, and scroll positions are reset to 0.0. 
2. The note's content is sent to Viewer (*setHtml* message), and it is rendered in Viewer.
3. After the completion of the rendering, *noteRenderComplete* message is sent to Editor.
4. The previous scroll position of the note has been recorded in `scrollWhenReady` variable, and when *noteRenderComplete* message is sent, Editor remembers its value, 0.5.
5. The remembered scroll position (0.5) is sent to Viewer via a *scrollPercent* message.
6. Viewer receives the rembered scroll position (0.5).

In Viewer, after the completion of the rendering and before the receipt of the remembered scroll position, if a resize event happens (typically, caused by image loading), the pre-remembered scroll position (0.0) is sent to Editor via a *scrollPercent* message (the red arrow in the figure). Consequently, Editor's scroll position is overwritten by 0.0, and its remembered scroll position is lost. The message is the cause of the symptom.

### To Fix

Ideally, the message protocol about *noteRenderComplete* should be redesigned to erase a race condition. But, a quick practical treatment exists.

Concretely, by suppressing *scrollPercent* messages from Viewer in the term between a noteRenderComplete and its response (a light red zone in the above figure), the symptom can be suppressed.

This fix is implemented in PR #6043.

**Comment by tessus** [comment]
Great analysis once again. Just out of curiosity, what did you use to create the diagram?

**Comment by tessus** [comment]
When I started the conversation 2 years ago I was actually talking about remembering the cursor position. The scroll position is a rather messy workaround. However, the scroll position also has it use-cases. I am not saying it is useless.

But I still think it would make a lot of sense, if we kept track of the cursor position (x,y) as well.

**Comment by ken1kob** [comment]
>  what did you use to create the diagram?

Power Point  ;-)

**Comment by ken1kob** [comment]
> When I started the conversation 2 years ago I was actually talking about remembering the cursor position. 

Yes, I'd read [\[Feature Request\] save cursor position · Issue #520](https://github.com/laurent22/joplin/issues/520).

> But I still think it would make a lot of sense, if we kept track of the cursor position (x,y) as well.

I agree. Ideally, both scroll position and cursor position are remembered.

There are some points of discussion:
- The case that only Markdown Viewer is used (no cursor position)
- The case that cursor position and scroll position conflict
- Scroll/cursor position compatibility between Markdown Editor and WYSIWYG Editor
- Whether scroll/cursor position should be synced or not

**Comment by tessus** [comment]
Yep, these things I had on my list as well. But we actually need Laurent for this, because he makes the decisions.

**Comment by GwynethLlewelyn** [comment]
... and I presume that the decision was to close down this (and all related issues), in the hope that one of the applied fixes actually had some effect?

Unfortunately, at least on the Apple side of things (macOS, iOS, iPadOS...), this endless forgotten-cursor-position issue has been by no means "fixed".
