### ISSUE TITLE
Cursor moves to the starting position when pressing <Enter> and another character key simultaneously.

### ISSUE THREAD

**Issue by xlash123** [laurent22/joplin#6044]
## Environment

Joplin version: 2.6.10 (Appimage)
Platform: Linux
OS specifics: 5.15.12-1-MANJARO, KDE

## Steps to reproduce

I initially noticed this for the <Enter> and <Backslash> keys since my keyboard places them directly next to each other, but I noticed that this occurs with any other key that inserts a character into the note. When both keys are pressed simultaneously, the cursor will jump to the initial position in the note.

1. Put cursor anywhere except the starting position.
2. Press <Enter> and <Backslash> at the same time

## Describe what you expected to happen

A new line and a backlash are inserted, and the cursor is directly after those 2 characters.

**Comment by graphit0** [comment]
Could be an additional behaviour of #4924 or #5969.

Does unchecking markdown spellchecker (in the settings) help?

**Comment by xlash123** [comment]
No. Same effect regardless of the spellchecker status.

**Comment by graphit0** [comment]
![image](https://user-images.githubusercontent.com/44114323/150996345-c182204a-00d7-406e-9518-7921d945dac1.png)

Let me double check it, is this checkbox unchecked in your settings?

**Comment by xlash123** [comment]
Oh, I see. In that case, yes. Turning that setting off fixes the problem. However, having spell check turned off from the Tools > Spell Checker menu does not affect this behavior.
