### ISSUE TITLE
Duplicated tags

### ISSUE THREAD

**Issue by marpada** [laurent22/joplin#605]
### Operating system

- Linux
### Application

- Desktop

### Problem

Hi,

The synchronization process is duplicating my tags, for example:
 
```
sqlite> select count(*) from (select title,count(*) as count from tags group by title having count > 1) ; 
125
```

Currently I have two on-going  synchronizations on my work and home computer, which is taking ages to finish due to #562

**Comment by marpada** [comment]
Now I got duplicated Notebooks as well :confused:

**Comment by laurent22** [comment]
Not sure what's happening. Notebooks can't be duplicated since they are de-deuplicated by ID and these IDs are globally unique, however multiple notebooks with the same title are technically allowed. Did you try to import/export notebooks or something similar? As this could create duplicate notebooks. I don't think there's an issue with the sync, but if there is I will need a lot more information.

**Comment by marpada** [comment]
Initially I tried to bootstrap my second computer from scratch, but the sync was taking ages and the notebooks didn't show up so there was no use. I though it would be faster to remove the ~/.config/joplin-desktop folder and import a jex file from my work computer.

**Comment by laurent22** [comment]
Ok so this is normal then: When you import a JEX file it creates **new** notes and notebooks, and then when you sync with a target that already have this data you're going to get duplicates.

There's no easy solution to this - it's best to just let the full sync run overnight if needed.

**Comment by gerroon** [comment]
I have this issue on 1.0.135, I use WIn Lin and Android

![nxplayer bin_iv60twfo5u](https://user-images.githubusercontent.com/8519469/53899344-e7eaa300-4031-11e9-9b08-158b3b1944bf.png)

**Comment by gorovnev** [comment]
Hi guys,
I have the same issue.
Just installed app on Windows (desktop) and 2 mobile devices (phone and tab). After each adding of device for Dropbox sync my tags and notebooks have been duplicated.
![2019-05-03_02-04-20](https://user-images.githubusercontent.com/5181018/57112273-ff9b8a80-6d47-11e9-96e9-555ff0f7d155.png)
[log.txt](https://github.com/laurent22/joplin/files/3140234/log.txt)
[log-database.txt](https://github.com/laurent22/joplin/files/3140235/log-database.txt)

**Comment by jacobvenborg** [comment]
Hello!

Just wanted to chime in - I got duplicate tags as well after setting up synchronization on Android :) Have only been using Joplin on Windows Desktop up until now.
![Joplin duplicate](https://user-images.githubusercontent.com/42551051/57619277-d075ec00-7585-11e9-8106-8a759f055d88.png)
