### ISSUE TITLE
 Selecting 'enter' does not Create Line Break [WYSIWYG editor]

### ISSUE THREAD

**Issue by ScriptInfra** [laurent22/joplin#6055]
## Environment

Joplin version: 2.6.10
Platform: Linux
OS specifics: Ubuntu 21.10/Linux Kernel 5.13

## Steps to reproduce

1. Create a new note
2. Create a random unformatted list
3. Attempt to create a line break in the WYSIWYG editor by selecting 'enter'
4. Select another existing note
5. Select back to the newly created note
6. Confirm that the line break formatting is gone

## Describe what you expected to happen

I would expect that when selecting 'enter' a < br > would be created from a markdown perspective, and that the formatting would be retained. Currently, selecting 'enter' is purely cosmetic and is only retained until another note is selected, which is very confusing from a user perspective.

This is a copy of #5596.

**Comment by KRoy118** [comment]
I

**Comment by ScriptInfra** [comment]
This still requires the community's attention.

**Comment by ScriptInfra** [comment]
This remains an issue.

**Comment by ScriptInfra** [comment]
This remains an issue.

**Comment by ScriptInfra** [comment]
This still requires the community's attention.

**Comment by ScriptInfra** [comment]
This remains an issue.

**Comment by mrtpcet** [comment]
This remains an issue.

**Comment by ra3ggi** [comment]
I know how to make a empty line!
A registry setting is required.
HKEY_CURRENT_USER/Control Panel/Input Method
Create string parameter EnableHexNumpad =1. Type REG_SZ.
Reload.
At desired location: 
- Press and hold the Alt key.
- Press the + (plus) key on the numeric keypad.
- Enter the value 3164 on the numeric keypad..
- Release the Alt key.
You have a empty line

![image](https://user-images.githubusercontent.com/54127155/216787155-61cbe205-23b9-4ef4-8132-b957d7d25910.png)

Then you can copy this invisible symbol and paste as many times as you want. 

![image](https://user-images.githubusercontent.com/54127155/216787985-63789d96-5a92-4e3d-be79-c1f636050a56.png)

By these actions I insert the invisible character UNICODE "U-3164", which is not empty, unlike the space bar.
I hope that the developer will automate this process and add it to the program menu.

**Comment by personalizedrefrigerator** [comment]
This is still an issue.
