### ISSUE TITLE
 Table not Populated Properly [WYSIWYG editor]

### ISSUE THREAD

**Issue by ScriptInfra** [laurent22/joplin#6057]
## Environment

Joplin version: 2.6.10
Platform: Linux
OS specifics: Ubuntu 21.10/Linux Kernel 5.13

## Steps to reproduce

1. Create a new note
2. Insert a 2x2 Table
3. Type any random text into all 4 Table cells
4. Select another note
5. Select the newly created note with the Table
6. Note that there are now 2 unexpected cells above the original 2x2 table (the table is now 2x3). 

## Describe what you expected to happen

I would expect the 2x2 Table format to persist. It looks like the Table formatting is not being properly retained.

This is a copy of #5577.

**Comment by graphit0** [comment]
Ok, it is more like feature request to enable insert of a table with default "header" property. While it is not yet fixed, you can infact set this property manually by `click on first row > table (from the bar) > row > row properties > row type: header`

More on the solution to this [here](https://moodle.org/mod/forum/discuss.php?d=196505#p856196)

**Comment by ScriptInfra** [comment]
This still requires the community's attention.

**Comment by planefun2** [comment]
I'm seeing this in Joplin portable  -

Joplin 2.7.13 (prod, win32)

Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: 5b5165d

**Comment by ScriptInfra** [comment]
This still requires the community's attention.

**Comment by ScriptInfra** [comment]
Still an issue.

**Comment by ScriptInfra** [comment]
This remains an issue on v2.8.8.

**Comment by ScriptInfra** [comment]
This remains an issue.
