### ISSUE TITLE
Can’t sync with nextcloud

### ISSUE THREAD

**Issue by hrdlnk** [laurent22/joplin#606]
### Operating system

- Android

### Application

- Mobile

Can’t sync with nextcloud:
`"Username or password was incorrect, No 'Authorization Bearer' header found. Either the client didn’t send one, or the server is misconfigured."`

I’m using the same webdav link and credentials as with my other apps (nextcloud app, DAVdroid)

**Comment by laurent22** [comment]
Double check again the username, password and URL, maybe manually type them instead of copying and pasting, as sometimes this error happen when there are extraneous characters like newlines or spaces.
