### ISSUE TITLE
Alarm on To-Do not shown in the Android application

### ISSUE THREAD

**Issue by dcharalambous** [laurent22/joplin#6062]
## Environment

Joplin version: 2.6.8
Platform: Android
OS specifics: Android 10 (Samsung Galaxy S9+)

## Steps to reproduce

1. Open Joplin app
2. Add a To-Do
3. Specify Alarm Date and Time, Save Alarm

## Describe what you expected to happen

The alarm is not shown anywhere but, in fact, it works, i.e. when the date/time comes, the app will provide an alert. The same To-Do when opened on the desktop, the alarm date/time is shown on the top-right corner of the To-Do.

I am not sure whether this is a bug, a missing feature or whether this is caused by own device.

**Comment by franco-ruggeri** [comment]
Same issue here, on my Redmi Note 7.

I use Joplin on Windows, Linux, iOS, and Android. The notifications work anywhere but on Android.

**Comment by franco-ruggeri** [comment]
The issue is still present and in my opinion it is relevant.

**Comment by franco-ruggeri** [comment]
The notifications are now working on my phone. Here what I did (I'm not sure which one fixed it, but I guess the second one):
- Reset phone
- Enabled autostart
