### ISSUE TITLE
Time picker on desktop has reversed arrows

### ISSUE THREAD

**Issue by penn5** [laurent22/joplin#6064]
When setting an alarm, in the time picker dialog, the up arrow increases the time value. This is in contrast with established standards like most web browsers, Android, iOS, etc. It really threw me off at first.

## Environment

Joplin 2.6.10 (prod, win32)

Client ID: 6c6d2451b53a413e9d1c102400ef0e96
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 98fba37

## Steps to reproduce

1. Create a note
2. Set an alarm
3. Enter time picker

## Describe what you expected to happen

Down arrow on time picker increases time value, up arrow reduces it

**Comment by laurent22** [comment]
In the lift, do you also press down to go up and up to go down?

**Comment by penn5** [comment]
Is Joplin a lift?

**Comment by Daeraxa** [comment]
Do you have examples of time pickers that do it this way? Usually it is either because there is a "physical" metaphor (like rotating dials) or you are given a list to scroll through where the direction is unambiguous.
With a "plain" time picker like this where there is no clue given as to the "correct" scrolling direction then to me it makes perfect sense that up is up and down is down.

**Comment by tomasz1986** [comment]
I think the OP is right here. Below is how similar pickers look in various Android apps.

![image](https://user-images.githubusercontent.com/5626656/151701024-cc66f9c8-63f0-4313-908d-85ea4a8ed703.png)
![image](https://user-images.githubusercontent.com/5626656/151701026-3a4b7507-a86a-478b-b703-753e40b85364.png)
![image](https://user-images.githubusercontent.com/5626656/151701032-4f4511c4-09c7-401c-8dcb-6bfe26e6e7d3.png)

**Comment by laurent22** [comment]
But we're talking about the desktop app here, not mobile, and there's no arrows on these screenshots. When you tag and drag the controller, it's obviously different.

**Comment by tomasz1986** [comment]
But there are arrows on the third one... and there's also the following.

![image](https://user-images.githubusercontent.com/5626656/151703784-7ba1d406-e4d6-456b-8350-afe2d1bf5d2f.png)

**Comment by Daeraxa** [comment]
But those have a visual clue so there is no guesswork involved. What I mentioned before:
>Usually it is either because there is a "physical" metaphor (like rotating dials) or you are given a list to scroll through where the direction is unambiguous.
>With a "plain" time picker like this where there is no clue given as to the "correct" scrolling direction then to me it makes perfect sense that up is up and down is down.

**Comment by laurent22** [comment]
> But there are arrows on the third one… and there's also the following.

But again, all of these are on mobile. Isn't it telling that not a single one is from a desktop app? As for the arrows in that screenshot, I assume the UI is still draggable, and maybe the arrows can't even be tapped.

**Comment by tomasz1986** [comment]
Yeah, but the point raised by the OP appears to be that people are first and foremost accustomed to mobile date/time pickers, hence they will expect a similar behaviour from a desktop application too :thinking:.

For the record, this is how Windows does it.

Classic:

![image](https://user-images.githubusercontent.com/5626656/151707263-6eae9559-ffdf-414a-9264-2b98418cb720.png)

New:

![image](https://user-images.githubusercontent.com/5626656/151707300-c6caea99-77b9-4209-bc6d-9df6d49be38d.png)

In the classic version, the "up" arrow indeed does increase the value, and the "down" arrow decreases it. The new version doesn't use arrows at all.

My guess would be that the Joplin time selector with its looks kind of reminds the user of a mobile date picker (and clearly doesn't look native to the OS), but at the same time behaves unlike the mobile one, which then causes the confusion mentioned in the OP.
