### ISSUE TITLE
When "Add Tag" dialog is opened, the bottom of the application is not under overlay 

### ISSUE THREAD

**Issue by kdzik** [laurent22/joplin#6065]
When "Add Tag" dialog is opened, the bottom of the application is not under overlay.

![image](https://user-images.githubusercontent.com/50631913/151526122-b8a26d87-aefe-4cff-8bb4-f33a3b010e17.png)

## Environment

Joplin version:  2.6.10
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1.  Open "Add tag" dialog on note or to-do item
2.  The overlay does not cover 100% of height of the application

## Describe what you expected to happen

The overlay should cover 100% of height of the application.

**Comment by Daeraxa** [comment]
Fixed in pre-release
https://github.com/laurent22/joplin/pull/5998
