### ISSUE TITLE
After closing the application, processes stay in the background

### ISSUE THREAD

**Issue by kdzik** [laurent22/joplin#6067]
On Windows 10, when the application is opened and then closed, 5 processes stay in the background with low resource consumption.
![image](https://user-images.githubusercontent.com/50631913/151532277-e19eb7fb-a6e1-4a93-9973-97c9c106c34b.png)

## Environment

Joplin version: 2.6.10
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Open application
2. Close application
3. Check processes in background in the task manager

## Describe what you expected to happen

I expect 1 process to be in background

**Comment by Daeraxa** [comment]
How many plugins do you have enabled?

**Comment by roman-r-m** [comment]
See if you have "minimize to tray" enabled? (Not sure what exactly is called on windows)

**Comment by JackGruber** [comment]
In Joplin for windows it is the setting `Show tray icon`.  
![grafik](https://user-images.githubusercontent.com/24863925/151553858-f711825b-8261-4745-8017-5197f12f75d9.png)
