### ISSUE TITLE
Unable to Type Joplin Cloud Info After Wrong Password

### ISSUE THREAD

**Issue by KevDev13** [laurent22/joplin#6075]
## Environment

Joplin version: 2.6.10
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Click "Synchronise" while not logged into Joplin Cloud account
2. Select Joplin Cloud
3. Type in email and password, using incorrect password, and click Login
4. Close error message stating incorrect password was entered
5. Attempt to type in email or password (unable to enter text)
6. Sometimes unable to type even if I close the Syncronize box and re-open

## Describe what you expected to happen
Expectation: able to re-type password without having to restart the application

**Comment by pathange-s** [comment]
@KevDev13 `Type in email and password, using incorrect password, and click Login`
Can you please provide an email id which has an account with Joplin cloud ? Any other email id will give `invalid email` error and not `incorrect password` error.

![image](https://user-images.githubusercontent.com/76244077/151934494-6bbc8a3d-af41-4245-a0ef-86c1198e3b55.png)

**Comment by pathange-s** [comment]
@KevDev13 https://drive.google.com/file/d/1vIrr4fbeuZaqRCrf-JkH3IZt7RojR1qG/view?usp=sharing
check out this short clip. I am not able to replicate the issue.
