### ISSUE TITLE
Joplin flatpak version writes files outside sandbox

### ISSUE THREAD

**Issue by BeatLink** [laurent22/joplin#6079]
The joplin flatpak version writes files outside of its designated sandbox, namely, ~/.var/app/net.cozic.joplin_desktop. Instead, its core files are being saved to ~/.config/joplin-desktop and ~/.config/joplindev-desktop which has the potential to conflict with a natively installed version of Joplin. 

## Environment

Joplin version: 2.6.10
Platform: Linux (Flatpak)
OS specifics: Fedora 35 KDE

## Steps to reproduce

1. Install Joplin Via Flatpak
2. Run joplin at least once to allow its core files to be loaded and saved
3. Navigate to the ~/.config folder and note the presence of joplin files.

## Describe what you expected to happen
Joplin installed via flatpak should keep its files confined to the sandbox unless explicitly allowed by the user to do otherwise, for example by using the Filesystem based sync option with a path to a user selected folder.

A quick fix for the time being would be to add the following options to the flatpak manifest:

--persist=.config/joplin-desktop
--persist=.config/joplindev-desktop

A longer term solution would be to use the linux provided XDG environment variables instead of hard coding the config path.

**Comment by Daeraxa** [comment]
Flatpak isn't an official Joplin distribution, this needs to be brought up with whomever is maintaining it.
