### ISSUE TITLE
Password stored as plain text

### ISSUE THREAD

**Issue by r5r3** [laurent22/joplin#608]
### Operating system

- Linux

### Application

- Desktop

### Issue

The sqlite database contains the password used for synchnisation as plain text. This is a serious security risk in an environment with NFS-based home directories. Would it be possible to use the key-chain offered by the operating system? An alternative would be an encrypted sqlite database. In that case, the user would have to enter a password at the start of Joplin. Slightly inconvenient, but certainty better then plain text passwords.

**Comment by laurent22** [comment]
Closed as duplicate
