### ISSUE TITLE
Unable to copy and paste from 3rd party screencapture app into markdown editor or rich editor

### ISSUE THREAD

**Issue by brandontan** [laurent22/joplin#6082]
## Environment

Joplin version: Joplin 2.6.10 (prod, darwin)
Platform: MacOS 
OS specifics: 12.1 Monterey

## Steps to reproduce

1. Copy the captured screenshot from 3rd party apps like CleanShot
2. Paste it into rich editor
3. Image is not pasted

## Describe what you expected to happen
Image should be pasted

**Comment by brandontan** [comment]
Please see : https://recordit.co/aCiAglrjA3

**Comment by Daeraxa** [comment]
What other 3rd party apps don't work? No way of testing if it is paid software.
