### ISSUE TITLE
Simple Backup Plugin 1.0.5 not behaving as expected

### ISSUE THREAD

**Issue by Pacomio22** [laurent22/joplin#6090]
## Environment
IMPORTANT NOTE: I am not a programmer, just a user trying to find out and correct why a plugin does not work for me !!! I do not even know if I am posting in the correct place/forum. Apologies if not
Joplin version: 2.6.10
Platform: Mac desktop
OS specifics: 10.13.6

### Simple Backup Plugin 1.0.5. was installed and configured according to the procedure.  However, when I launch it, it prompts me to configure it again with the following message (even though it is already configured and relaunched)
**Backup plugin Please configure backup path in Joplin Tools > Options > Backup**

1. Please note that in my Joplin version (2.6.10), there is no **Tools > Options** menu: the backup configuration menu is located under **Joplin > Preferences > Plugins**
2. Even after having configured the plugin I continue to get the  
      **Backup plugin Please configure backup path in Joplin Tools > Options > Backup notice** again and again

So, what is that I am doing wrong? Any help will be appreciated.

## Describe what you expected to happen
I expected a backup file to be created

LOG
07:16:04.641384 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,Direct,libdyld.dylib
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

07:16:04.700869 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,CoreFoundation,Foundation
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

09:01:28.352252 -0500	diagnostics_agent	com.apple.message.domain: com.apple.usage.app_activetime
com.apple.message.signature: Joplin
com.apple.message.signature2: net.cozic.joplin-desktop ||| 2.6.10 (2.6.10)
com.apple.message.value: 909
com.apple.message.value2: 718
com.apple.message.value3: 1
com.apple.message.value4: 1
com.apple.message.value5: 3
com.apple.message.value6: 2
com.apple.message.value7: 909
com.apple.message.result: YES
com.apple.message.summarize: YES
SenderMachUUID: 46988FF9-8FDE-3A27-BA84-1781A9D2FA10

08:17:01.342264 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,Direct,libdyld.dylib
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

08:17:01.419513 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,CoreFoundation,Foundation
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

08:30:59.368242 -0500	diagnostics_agent	com.apple.message.domain: com.apple.usage.app_activetime
com.apple.message.signature: Joplin
com.apple.message.signature2: net.cozic.joplin-desktop ||| 2.6.10 (2.6.10)
com.apple.message.value: 838
com.apple.message.value2: 524
com.apple.message.value3: 1
com.apple.message.value4: 1
com.apple.message.value5: 1
com.apple.message.value6: 1
com.apple.message.value7: 523
com.apple.message.result: YES
com.apple.message.summarize: YES
SenderMachUUID: 46988FF9-8FDE-3A27-BA84-1781A9D2FA10

08:37:01.934961 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL2
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,CoreFoundation,Foundation,Direct,libdyld.dylib
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

08:37:28.046560 -0500	diagnostics_agent	com.apple.message.domain: com.apple.usage.app_activetime
com.apple.message.signature: Joplin
com.apple.message.signature2: net.cozic.joplin-desktop ||| 2.6.10 (2.6.10)
com.apple.message.value: 65
com.apple.message.value2: 30
com.apple.message.value3: 0
com.apple.message.value4: 0
com.apple.message.value5: 2
com.apple.message.value6: 2
com.apple.message.value7: 30
com.apple.message.result: YES
com.apple.message.summarize: YES
SenderMachUUID: 46988FF9-8FDE-3A27-BA84-1781A9D2FA10

11:45:42.085987 -0500	diagnostics_agent	com.apple.message.domain: com.apple.usage.app_activetime
com.apple.message.signature: Joplin
com.apple.message.signature2: net.cozic.joplin-desktop ||| 2.6.10 (2.6.10)
com.apple.message.value: 230
com.apple.message.value2: 67
com.apple.message.value3: 0
com.apple.message.value4: 0
com.apple.message.value5: 0
com.apple.message.value6: 0
com.apple.message.value7: 230
com.apple.message.result: YES
com.apple.message.summarize: YES
SenderMachUUID: 46988FF9-8FDE-3A27-BA84-1781A9D2FA10

06:41:19.428575 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,Direct,libdyld.dylib
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

06:41:19.466568 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,CoreFoundation,Foundation
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

07:02:50.596226 -0500	diagnostics_agent	com.apple.message.domain: com.apple.usage.app_activetime
com.apple.message.signature: Joplin
com.apple.message.signature2: net.cozic.joplin-desktop ||| 2.6.10 (2.6.10)
com.apple.message.value: 428
com.apple.message.value2: 428
com.apple.message.value3: 1
com.apple.message.value4: 0
com.apple.message.value5: 1
com.apple.message.value6: 1
com.apple.message.value7: 428
com.apple.message.result: YES
com.apple.message.summarize: YES
SenderMachUUID: 46988FF9-8FDE-3A27-BA84-1781A9D2FA10

07:17:18.807261 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,Direct,libdyld.dylib
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

07:17:18.871534 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,CoreFoundation,Foundation
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

07:53:10.497696 -0500	diagnostics_agent	com.apple.message.domain: com.apple.usage.app_activetime
com.apple.message.signature: Joplin
com.apple.message.signature2: net.cozic.joplin-desktop ||| 2.6.10 (2.6.10)
com.apple.message.value: 551
com.apple.message.value2: 551
com.apple.message.value3: 1
com.apple.message.value4: 0
com.apple.message.value5: 1
com.apple.message.value6: 1
com.apple.message.value7: 551
com.apple.message.result: YES
com.apple.message.summarize: YES
SenderMachUUID: 46988FF9-8FDE-3A27-BA84-1781A9D2FA10

06:59:45.548906 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,Direct,libdyld.dylib
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

06:59:45.607019 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,CoreFoundation,Foundation
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

07:40:57.546972 -0500	diagnostics_agent	com.apple.message.domain: com.apple.usage.app_activetime
com.apple.message.signature: Joplin
com.apple.message.signature2: net.cozic.joplin-desktop ||| 2.6.10 (2.6.10)
com.apple.message.value: 2473
com.apple.message.value2: 2158
com.apple.message.value3: 1
com.apple.message.value4: 1
com.apple.message.value5: 1
com.apple.message.value6: 1
com.apple.message.value7: 2157
com.apple.message.result: YES
com.apple.message.summarize: YES
SenderMachUUID: 46988FF9-8FDE-3A27-BA84-1781A9D2FA10

07:48:56.797322 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL2
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,CoreFoundation,Foundation,Direct,libdyld.dylib
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

08:07:01.992255 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,Direct,libdyld.dylib
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

08:07:02.032175 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,CoreFoundation,Foundation
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

08:07:57.158499 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,Direct,libdyld.dylib
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

08:07:57.214133 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,CoreFoundation,Foundation
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

08:22:27.015403 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,Direct,libdyld.dylib
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

08:22:27.058461 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,CoreFoundation,Foundation
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

08:40:37.937581 -0500	diagnostics_agent	com.apple.message.domain: com.apple.usage.app_activetime
com.apple.message.signature: Joplin
com.apple.message.signature2: net.cozic.joplin-desktop ||| 2.6.10 (2.6.10)
com.apple.message.value: 3030
com.apple.message.value2: 1491
com.apple.message.value3: 3
com.apple.message.value4: 1
com.apple.message.value5: 15
com.apple.message.value6: 2
com.apple.message.value7: 2628
com.apple.message.result: YES
com.apple.message.summarize: YES
SenderMachUUID: 46988FF9-8FDE-3A27-BA84-1781A9D2FA10

10:28:33.783385 -0500	diagnostics_agent	com.apple.message.domain: com.apple.usage.app_activetime
com.apple.message.signature: Joplin
com.apple.message.signature2: net.cozic.joplin-desktop ||| 2.6.10 (2.6.10)
com.apple.message.value: 4551
com.apple.message.value2: 0
com.apple.message.value3: 0
com.apple.message.value4: 0
com.apple.message.value5: 0
com.apple.message.value6: 0
com.apple.message.value7: 0
com.apple.message.result: YES
com.apple.message.summarize: YES
SenderMachUUID: 46988FF9-8FDE-3A27-BA84-1781A9D2FA10

11:36:18.280793 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL2
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,CoreFoundation,Foundation,Direct,libdyld.dylib
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

14:24:34.054941 -0500	diagnostics_agent	com.apple.message.domain: com.apple.usage.app_activetime
com.apple.message.signature: Joplin
com.apple.message.signature2: net.cozic.joplin-desktop ||| 2.6.10 (2.6.10)
com.apple.message.value: 13367
com.apple.message.value2: 1915
com.apple.message.value3: 0
com.apple.message.value4: 1
com.apple.message.value5: 7
com.apple.message.value6: 4
com.apple.message.value7: 3237
com.apple.message.result: YES
com.apple.message.summarize: YES
SenderMachUUID: 46988FF9-8FDE-3A27-BA84-1781A9D2FA10

11:03:49.554828 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,Direct,libdyld.dylib
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

11:03:49.646763 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,CoreFoundation,Foundation
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

11:20:12.683652 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,Direct,libdyld.dylib
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

11:20:12.729496 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,CoreFoundation,Foundation
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

11:23:31.330085 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,Direct,libdyld.dylib
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

11:23:31.376257 -0500	Joplin Helper (GPU)	com.apple.message.domain: com.apple.graphics.clients
com.apple.message.architecture: 64
com.apple.message.context_type: GL
com.apple.message.signature2: 2.6.10
com.apple.message.signature3: GL3 Core
com.apple.message.summarize: YES
com.apple.message.intermediate_frameworks: Electron Framework,CoreFoundation,Foundation
com.apple.message.signature1: net.cozic.joplin-desktop.helper.GPU
SenderMachUUID: A23DA476-93CB-3A2A-B513-24659092FC7C

**Comment by laurent22** [comment]
This is the wrong forum for this. Please post this to the Backup Plugin issue tracker instead.
