### ISSUE TITLE
"Toggle Editor Layout" works only for markdown editor - it should work for both

### ISSUE THREAD

**Issue by brandontan** [laurent22/joplin#6095]
## Environment

Joplin version: Joplin 2.6.10 (prod, darwin)

Platform: MacOS 
OS specifics: 12.1 Monterey M1

## Steps to reproduce

1. The button "Toggle Editor Layout" works only for markdown editor
2. Note that the button is greyed out for rich editor

See screen recording: https://recordit.co/5eAirMPz0h

If I copy from Jira or Confluence into rich editor, the white background is copied over well 

## Describe what you expected to happen

The "Toggle Editor Layout" option should be available to both editors

**Comment by Daeraxa** [comment]
There isn't a layout to toggle for rich text, a wysiwyg editor doesn't need a preview pane, it _is_ the preview pane and the button is greyed out to indicate that.

Not sure of the relevance of the Jira/Confluence line?

**Comment by brandontan-888** [comment]
Apologies.... please ignore that line

**Comment by Daeraxa** [comment]
I don't think you have it quite right.
There are two editors, markdown and richtext.
Markdown editor has three view options - editor only, preview only, dual pane
Richtext only has one editor because it is WYSIWYG, there is no need for a preview as the editor is the preview therefore no layout switcher (hence why it is disabled)

**Comment by brandontan** [comment]
> Richtext only has one editor because it is WYSIWYG
However, I can't click on the links or preview it as there's no preview pane for it

**Comment by Daeraxa** [comment]
Correct, there is no need for a preview as the rendered output would look exactly the same.

Links should be clickable via ctrl/cmnd + click.

**Comment by brandontan-888** [comment]
Understood. Closing issue

**Comment by brandontan** [comment]
Closed
