### ISSUE TITLE
Add right-click "save image" context menu to Mermaid graphs

### ISSUE THREAD

**Issue by ei8fdb** [laurent22/joplin#6100]
## Feature discussion

This feature request was discussed in [Joplin discourse](https://discourse.joplinapp.org/t/ability-to-save-export-mermaid-graphs-as-image/23491/3).

## Feature description

Enable the ability to save a Mermaid graph as an image for use outside of Joplin.

## Use case / User need

Using Mermaid graphs to document a process. [Here's an example](https://notes.saneux.ei8fdb.org/shares/pI92hWbkbGPe09lysF9fWH).

A common need would be to use the graph outside of Joplin -  embed it in a document, or a Github issue.

Currently this is not easily achieved.

## Current workarounds

Current note exports (MD, HTML, JEX, PDF,etc ), or screenshotting the graph do not support the need well.

This means that using the graph outside of Joplin is not practically possible.

## Possible approach

Joplin currently has a right-click context menu for saving images outside of Joplin - 

![image](https://user-images.githubusercontent.com/1899506/152554530-b94fa20f-48d8-4740-88a4-a318bdbe4abf.png)

This context menu could be re-used to allow a Joplin user to save the Mermaid graph as an image file.

It would be very nice if the image was an svg (to be scalable). If not, at least png or jpg. 

As illustration here's a simple mock-up of how it might work:

![image](https://user-images.githubusercontent.com/1899506/152555134-b5d0cb8f-6650-46bb-9fe8-441aaaf76a71.png)

Using this context menu the user could save the image in whatever format was supported.

**Comment by asrient** [comment]
Hi, is this issue up for grab? I would like to work on it.

**Comment by rinkydevi** [comment]
hey @ei8fdb ! I would love to contribute in this issue, can i proceed?

**Comment by ei8fdb** [comment]
@asrient @rinkydevi I opened the issue, but I'm not involved in the development. 

@laurent22 @tessus would you prefer to answer, I'm also happy to answer if you'd prefer me to.

**Comment by laurent22** [comment]
We don't currently assign issues as we had issues with this in the past, so anyone is free to work on it. If there's more than one person interested in it, they can also collaborate if they want.

**Comment by rinkydevi** [comment]
@ei8fdb would u like to collaborate with me on this issue?
i would love to learn and work with u..

**Comment by asrient** [comment]
Hello everyone here, I have created a PR for this, feel free to add your contributions and reviews there if you find something missing.

**Comment by ei8fdb** [comment]
@asrient maybe youd like to work with @rinkydevi on this together?

I am a UX designer, not a developer. Wwhen you have a solution can you 1) work with me to test it locally, 2) post a screengrab *video* not just a screenshot image of how it works?

I'll happily help with testing.

**Comment by asrient** [comment]
@ei8fdb sure sound great. I will remake the PR soon after fixing a few things as reported by @ laurent22. You can check it out and make sure it satisfies the original intent of yours or any changes that might be missing, then @rinkydevi and I can work on the changes that will be required.

**Comment by rinkydevi** [comment]
hey @asrient yeah sure!

**Comment by ei8fdb** [comment]
> you can check it out

This is the bit I might need help in achieving. I'd appreciate if you can help me with this. 

The rest is good with me. 👍

**Comment by tessus** [comment]
Just an additional note. Saving the SVG as PNG or JPG might be better in a plugin. The reason is that many SVG to PNG/JPG node modules have a lot of dependencies that will increase the size of Joplin even more.
I guess we'd have to test the size increase.

**Comment by ei8fdb** [comment]
> Just an additional note. Saving the SVG as PNG or JPG might be better in a plugin. The reason is that many SVG to PNG/JPG node modules have a lot of dependencies that will increase the size of Joplin even more.
> I guess we'd have to test the size increase. 

That's understandable. 

Just so I understand correctly - default saving would be SVG?

**Comment by laurent22** [comment]
It would be nice if it could be saved as an image too as that's more portable (you just paste it anywhere and it works, unlike an svg) but indeed I don't know how easy it would be. We have an svg renderer obviously in Chromium and perhaps we can leverage that to extract an image?

**Comment by asrient** [comment]
- Yes chromium can convert svg to png, take look at this [gist](https://gist.github.com/XianYeeXing/b5372e87e9485a2753b8e2a54136c3d9), we can use this function. But this needs to be run from contextMen right? Are there any consequences of using the native web apis directly there? (for eg: `document.createElement`, `canvas.toDataURL`). 
- If we add support for multiple export formats we need some gui changes too then, either:
    - We can pop a new dialog asking for the format to choose.
    - We can have separate options in the context menu itself, like `save as SVG`, `save as PNG`.

**Comment by laurent22** [comment]
> Are there any consequences of using the native web apis directly there?

It's not an issue, just make sure you remove the element once it's done.

> If we add support for multiple export formats we need some gui changes too then, either:

Whatever is simple in terms of implementation I guess as both options seem ok. But we need to make sure that the "Save as x" only show up for Mermaid items.

> As you can see in the gist we need to provide hight and width of the png we will generate, so question arises if we should decide on a hardcoded value or ask user for input.

We should try to set the size automatically. I think it could be determined based on the source element size?

**Comment by asrient** [comment]
Yes I think we can get an idea of the size from svg itself. Got it.

**Comment by znamazbayeva** [comment]
> Yes I think we can get an idea of the size from svg itself. Got it.

Hello, are you still working on it? I want to collaborate

**Comment by hologpt** [comment]
Hey, I would like to help with this as well.

**Comment by asrient** [comment]
@ei8fdb I have a PR in progress for this. Currently waiting for review https://github.com/laurent22/joplin/pull/6126

**Comment by ei8fdb** [comment]
@laurent22 That's great news. I guess I should have had a look at the PRs. Thanks to @asrient and you for working on this.

@laurent22 Is there a possibility of testing this before it's pushed into a release? Or maybe a better way to ask it: is there any testing process available to test the functionality is as the design suggested?

**Comment by laurent22** [comment]
> @laurent22 Is there a possibility of testing this before it's pushed into a release? Or maybe a better way to ask it: is there any testing process available to test the functionality is as the design suggested?

Not currently - when we need to do that we simply build the branch and run it. Alternatively perhaps @asrient can provide a screenshot or video if there's something in particular you'd like to see?

**Comment by asrient** [comment]
Sure, will add some more demos/videos soon.

**Comment by ei8fdb** [comment]
@asrient any chance you can post a demo of how this now works? I'm not sure when it will be released, so not sure when I'll get to see it! 😄 thanks.

**Comment by asrient** [comment]
Hi @ei8fdb you can check out the description of the PR here

https://github.com/laurent22/joplin/pull/6126#issue-1126096898

I have added a video screen recording and a screenshot for demo, hope that helps for now. I can’t say for sure when it will get released either but I guess will happen soon with the next version release. 
(Just an assumption though)

**Comment by ei8fdb** [comment]
Hea @laurent22 - whats the process for merging PRs? We're guessing it happens before the next release?

Also, thanks to you Laurent, @asrient, @tessusand everyone else for the help in getting this done. 👏

**Comment by laurent22** [comment]
The pull request is merged to the dev branch now, and so it will be part of the next desktop pre-release.

We have an issue now with the Windows app on CI as GitHub removed the env that we were using, so I'm not sure when the next release will be but hopefully sooner rather than later.

**Comment by ei8fdb** [comment]
Ok thanks for explaining that. I asked as it wasn't clear to me.

**Comment by ei8fdb** [comment]
@asrient sorry I didn't see the demo in the PR. I had a look now and that looks nice. I never thought about adding the path to the file. Nice addition.
