### ISSUE TITLE
Add "export" Mermaid graph button to Joplin note

### ISSUE THREAD

**Issue by ei8fdb** [laurent22/joplin#6101]
## Feature discussion

This feature request was discussed in [Joplin discourse](https://discourse.joplinapp.org/t/ability-to-save-export-mermaid-graphs-as-image/23491/3).

## Feature description

An easily discoverable method, visible in the UI, to export a Mermaid graph. 

## Use case / User need

Using Mermaid graphs is to document a process, [here's an example](https://notes.saneux.ei8fdb.org/shares/pI92hWbkbGPe09lysF9fWH). A common next step need would be to use the graph outside of Joplin - embed it in a document, or a Github issue.

Unless a user is very familiar with Joplin the ability to export/save a graph is not easily achieved.

## Current workarounds

This good first issue is not yet implemented https://github.com/laurent22/joplin/issues/6100. When it is, the user could use this method. 

Current note exports (MD, HTML, JEX, PDF,etc ), or screenshotting the graph do not support the need well. This means that using the graph outside of Joplin is not practically possible.

## Possible approach

A possible approach would be to provide an "export graph" button which the user can click to export the graph. 

When the user clicks this button they could be prompted to save the graph as an image file. It would be very nice if the image was an svg (to be scalable). If not, at least png or jpg.

As illustration here's a simple mock-up of how it might work:

![image](https://user-images.githubusercontent.com/1899506/152560144-7c2ffee3-975f-4a40-a9f7-ee8792ef2637.png)

### Reduce visual noise

In order to reduce the amount of visual noise, this button could be hidden/not visible until the user hovers over/highlights the graph.

(I'm unsure how this would affect accessibility for visually impaired users)

**Comment by laurent22** [comment]
And, as discussed in [this comment](https://discourse.joplinapp.org/t/ability-to-save-export-mermaid-graphs-as-image/23491/4?u=laurent) ideally it should be implemented in such a way that the button could also appear over images, code blocks, etc. to provide a similar functionality.

**Comment by asrient** [comment]
Can I claim this one? I have asked it for #6100 as well, either one works for me since both targets the same area.

**Comment by ei8fdb** [comment]
@asrient I don't know what the process is for claiming tickets. It's OK with me! 

@laurent22 @tessus can you advise?

@asrient I would be happy to work with you on the design. I am not a developer so when you have a solution can you work with me to test it locally? I'd be very happy to help you with this.

**Comment by Manish4044** [comment]
Is this feature implemented or someone is still working on it?

**Comment by asrient** [comment]
@Manish4044 I'm currently working on a different issue, might get back once I'm done if no one's working on it.

**Comment by ei8fdb** [comment]
@Manish4044 @asrient Have you had a chance to try this out?

**Comment by aniketrochwani** [comment]
Can I work on it?

**Comment by asrient** [comment]
@aniketrochwani I’m currently working on another issue so I guess no one is working on it right now

**Comment by ei8fdb** [comment]
@aniketrochwani I'm the one who opened the issue, so if I can help with any questions about design or in situations like "what should happen....?" let me know and I'll try to help. 👍

**Comment by Manish4044** [comment]
> @aniketrochwani I'm the one who opened the issue, so if I can help with any questions about design or in situations like "what should happen....?" let me know and I'll try to help. 👍

I thought somebody else was working on it. So, I was trying something else. If nobody is working on it. I will be happy to implement this.

**Comment by KaviiSuri** [comment]
Is this issue up for grabs? I'd love to give it a shot
