### ISSUE TITLE
Unable to indent to the left after copying text blocks from slack, jira or confluence in rich editor

### ISSUE THREAD

**Issue by brandontan-888** [laurent22/joplin#6103]
## Environment

Joplin version: Joplin 2.6.10 (prod, darwin)

Platform: MacOS 
OS specifics: 12.1 Monterey M1

## Steps to reproduce

1. Copy and paste text blocks from from apps like slack , jira or confluence
2. Unable to proceed - stuck in text block within rich editor
3. Had to switch to markdown editor

Please see screen recordig : https://recordit.co/fWWtQu6F2B

## Describe what you expected to happen

Able to move easily after block copy into rich editor ; enhancements to rich editor required

**Comment by Daeraxa** [comment]
Can you provide sample text to replicate it?

**Comment by brandontan** [comment]
Try this: https://www.atlassian.com/software/jira/guides/getting-started/overview

https://recordit.co/CkS8190weX

Thanks

**Comment by CalebJohn** [comment]
I wonder if we should have paste without formatting as the default. Joplin doesn't support most formatting anyways (background colour, centre, etc.) so there isn't really any value in it, and half the time it gets removed when the user reloads the note anyways.

**Comment by Daeraxa** [comment]
I feel it falls under the general umbrella of "Improve integration of the richtext/WYSIWYG editor" in the GSoC 2022 ideas where the overall integration just doesn't feel as tight as it should.

**Comment by brandontan** [comment]
Ok ... as long as it's in the roadmap ... closing the ticket.. thanks

**Comment by brandontan-888** [comment]
closed
