### ISSUE TITLE
Need to improve search on tag list

### ISSUE THREAD

**Issue by brandontan-888** [laurent22/joplin#6104]
## Environment

Joplin version: Joplin 2.6.10 (prod, darwin)

Platform: MacOS 
OS specifics: 12.1 Monterey M1

## Steps to reproduce

1. Create a long list of tags ( 100 )
2. Key in tag of choice 
3. It does not show up as 1st choice ; need to scroll down

Please see screen recordig : https://recordit.co/J7LrQzaKfL

## Describe what you expected to happen

The tag requested should appear as first choice ; search on tag needs improvements

**Comment by prajwalkulkarni** [comment]
Yes, observed a similar issue on Windows 10 too. I think I can take this up.
