### ISSUE TITLE
Creating a horizontal line will automatically set the above text as H1

### ISSUE THREAD

**Issue by brandontan** [laurent22/joplin#6105]
## Environment

Joplin version: Joplin 2.6.10 (prod, darwin)

Platform: MacOS 
OS specifics: 12.1 Monterey M1

## Steps to reproduce

1. Write something T1
2. Create a horizontal rule
3. T1 will be formatted as H1

Please see screen recording : https://recordit.co/CmwdR0mLFe

## Describe what you expected to happen

Creating a horizontal line should not format text above

**Comment by CalebJohn** [comment]
This is part of the common-mark markdown spec. It's actually pretty nice when taking plain text notes, but indeed can be annoying when you only use ATX style headers.

Joplin tries not to diverge from the common mark spec, so this will not be changed. Feel free to request a plugin to change this behaviour on the forum (or start building one yourself!).
