### ISSUE TITLE
Add an "Importing from other applications..." menu item

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#6108]
Under File > Import, there should be an item titled "Importing from other applications..." that simply links to the forum thread:

https://discourse.joplinapp.org/t/importing-notes-from-other-notebook-applications/22425

Users often don't know that there are various scripts and methods to import from other apps, and this item would help with that.

**Comment by dpoulton-github** [comment]
If it's just a link to information on a webpage shouldn't it be under "Help" (an information menu) rather than "File" (a "doing things" menu)?

**Comment by roman-r-m** [comment]
Maybe this should be  a "good first issue"?

**Comment by laurent22** [comment]
> If it's just a link to information on a webpage shouldn't it be under "Help" (an information menu) rather than "File" (a "doing things" menu)?

The idea is that the user opens the menu, scroll through the available items and see nothing for their file format. So they can click on that new item for more information. If we put it under Help, most users won't notice it.

**Comment by Daeraxa** [comment]
For this kind of thing I personally still champion the idea of a [welcome screen](https://discourse.joplinapp.org/t/joplin-welcome-landing-page-split-from-silent-updates/21973).
A menu item linking to guides quickly becomes redundant once the user has their data in where a dismissable welcome/guide screen is designed for precisely that job. Also is a lot more extensible it that it can just be in HTML/Javascript unlike the demo notes so has a lot more flexibility in layout and what can be shown.

**Comment by tessus** [comment]
> Under File > Import, there should be an item titled "Importing from other applications..." that simply links to the forum thread

If you really want to add an item, I suggest to name it differently:

We already have `Import` as a menu item. We also don't say in the sub menu: `Import JEX`, `Import MD`, etc.
So we should use the following instead: `From other applications...` or `Other applications...` (because `from` is implied by the word `import`).
