### ISSUE TITLE
Unable to use cmmand+z to undo action

### ISSUE THREAD

**Issue by brandontan** [laurent22/joplin#6113]
## Environment

Joplin version: Joplin 2.6.10 (prod, darwin)

Platform: MacOS 
OS specifics: 12.1 Monterey M1

## Steps to reproduce

1. Paste text as titled of note
2. No way to undo it

## Describe what you expected to happen

Command+z (mac) should be supported to undo last action

**Comment by CalebJohn** [comment]
Duplicate of #3513
