### ISSUE TITLE
Behaviour of numbered list

### ISSUE THREAD

**Issue by Mr-Kanister** [laurent22/joplin#6116]
## Environment

Joplin version: 2.7.8
Platform: Linux & Windows 10
OS specifics: Debian Bullsyeye

## Steps to reproduce

1. Create a note with a numbered list (e. g. 1., 2., 3.)
2. Add a new line with a new number 1 item

## Describe what you expected to happen
I expected the numbering of the list to begin at one again, but it just continued counting along.
I don't know if this is expected behaviour.

![grafik](https://user-images.githubusercontent.com/68117355/152681140-9515358a-5b7e-45b0-bf2c-8e4cb3c02d4c.png)

**Comment by Daeraxa** [comment]
I think this is just the behaviour of markdown.

> The [start number](https://spec.commonmark.org/0.30/#start-number) of an [ordered list](https://spec.commonmark.org/0.30/#ordered-list) is determined by the list number of its initial list item. The numbers of subsequent list items are disregarded.

Multiple lists need to be broken up so that a new `<ol>` can start counting from that start number.

**Comment by Mr-Kanister** [comment]
Alright then, thanks for the clarification!
