### ISSUE TITLE
Unable to include a Block Quote within a Code Block

### ISSUE THREAD

**Issue by brandontan** [laurent22/joplin#6122]
## Environment

Joplin version: Joplin 2.6.10 (prod, darwin)

Platform: MacOS 
OS specifics: 12.1 Monterey M1

## Steps to reproduce

1. Place a block of text in Code Block
2. Mark part of text with block quotes
3. The block quote does not get rendered

## Describe what you expected to happen

Block quotes should get rendered within a Code Block

## Logfile

![CleanShot 2022-02-07 at 17 35 25](https://user-images.githubusercontent.com/1005474/152762724-d528a99f-4106-46bf-bb7c-7bd29850b234.png)

**Comment by roman-r-m** [comment]
> Block quotes should get rendered within a Code Block

Should they really? Just tried this in https://spec.commonmark.org/dingus/ and in https://markdown-it.github.io/.  Both render it exactly the same way as Joplin does.

**Comment by dpoulton-github** [comment]
This appears to be working as Markdown intended.

When any text is wrapped in a Code **Block** the renderer is being told that **all** text in that block up until the end marker is to be treated as code. If the renderer acted upon anything that appered to be Markdown / HTML within that block you could never display the code as code...

**Comment by brandontan** [comment]
Can we have a Joplin flavour of this feature ?

**Comment by Daeraxa** [comment]
Commonmark spec makes it clear that all data inside the code block is treated as literal text:

> The content of a code fence is treated as literal text, not parsed as inlines.

https://spec.commonmark.org/0.30/#code-fence

The general consensus from the maintainers is that we should not be supporting nor creating a "JFM" (Joplin flavour markdown) as it means it is no longer technically markdown at all.
