### ISSUE TITLE
Mermaid graph displayed has excessive whitespace (the wider the graph, the more leading and trailing whitespace) 

### ISSUE THREAD

**Issue by ei8fdb** [laurent22/joplin#6124]
## Environment

Joplin version: Joplin 2.6.10 (prod, darwin), 98fba37 
Platform: MacOS
OS specifics: 11.5.2

## Steps to reproduce

1. create a note
2. add the following mermaid graph code

include " ```mermaid" before `sequenceDiagram`

```mermaid
sequenceDiagram
    autonumber
    Contractor->>PM Staff: Contractor submits invoice
		Note right of Contractor: Send notification to contractor
		Note right of Contractor: Send notification to PM Staff
		PM Staff-->>Contractor: PM Staff requests changes to invoice
		Note left of PM Staff: Send notification to Contractor
		Contractor-->>PM Staff: Contractor makes changes to invoice
		Note right of Contractor: Send notification to PM Staff
		PM Staff->>Finance 1: PM approves invoice
		Note right of PM Staff: Send notification to Finance 1
		Finance 1-->>PM Staff: Finance 1 requests changes to invoice
		Note left of Finance 1: Send notification to PM Staff
		PM Staff-->>Contractor: PM Staff requests changes to invoice
		Note left of PM Staff: Send notification to Contractor
		Contractor-->>PM Staff: Contractor makes changes to invoice
		Note right of Contractor: Send notification to PM Staff
		PM Staff->>Finance 1: PM Staff approves invoice
		Note right of Finance 1: Send notification to Finance 1
		Finance 1->>Finance 2: Finance 1 approves invoice
		Note right of Finance 1: Send notification to Finance 2
		Finance 2-->>Finance 1: Finance 2 requests changes to invoice
		Note left of Finance 2: Send notification to Finance 1
		Finance 1-->>PM Staff: Finance 1 requests changes to invoice
		Note left of Finance 1: Send notification to PM Staff
		PM Staff-->>Contractor: PM Staff requests changes to invoice
		Note left of PM Staff: Send notification to Contractor
		Contractor-->>PM Staff: Contractor makes changes to invoice
		Note right of Contractor: Send notification to PM Staff
		PM Staff->>Finance 1: PM Staff approves invoice
		Note right of PM Staff: Send notification to Finance 1
		Finance 1->>Finance 2: Finance 1 approves invoice
		Note right of Finance 1: Send notification to Finance 2
		Finance 2->>Intacct: Finance 2 automatically sends invoice to Intacct
		Note right of Finance 2: Send notification to PM Staff
		Intacct->>Contractor: Payment is sent to Contractor
		Note left of Intacct: Send notification to Contractor
		Note left of Intacct: Send notification to PM Staff 
```

Include "```" after `Note left of Intacct: Send notification to PM Staff `.

3. toggle the editor/viewer view the view

## Describe what actully happened

When I viewed the note, the graph was displayed with excessive amount of leading and trailling whitespace:

![image](https://user-images.githubusercontent.com/1899506/152787113-546ae24a-46bd-4dcd-a84d-09387a378f52.png)

It seems, the wider the Mermaid graph becomes, the more whitespace is displayed.

## Describe what you expected to happen

What I expected to happen was the mermaid graph would be displayed with a reasonable, small amount of leading and trailling whitespace. A resonable amount would be something like shown below:

![image](https://user-images.githubusercontent.com/1899506/152788540-f793a64d-acb9-4e53-be53-82cf6746a90e.png)

## Logfile

I followed [the tips on collecting a log file](https://joplinapp.org/debugging/), I could not see any errors in log.txt, and no errors mentioned in the console that are relevant to the note or mermaid.

**Comment by roman-r-m** [comment]
Isn't is a copy of https://github.com/laurent22/joplin/issues/6124 ?

**Comment by ei8fdb** [comment]
> Isn't is a copy of #6124 ?

Absolutely. I have no idea how 6124 was duplicated. I'll close this now. Thanks @roman-r-m for pointing that out.
