### ISSUE TITLE
First of two whitespaces is automatically replaced by dot

### ISSUE THREAD

**Issue by DarkPurpleKnight** [laurent22/joplin#6127]
## Environment

Joplin version: 2.6.8
Platform: Android 9
OS specifics: Android One

The following issue **only** affects the Joplin Android app.

## Steps to reproduce

1. Open a new or existing note.
2. Type a letter, number or special character.
3. Then type 2 whitespaces.

## Result
The first whitespace is automatically replaced by a dot.

Especially when creating a table using Markdown, this automatic character substitution is annoying.

## Describe what you expected to happen
No automatic replacement of entered characters.

## Logfile
[syncReport-1644246192718.txt](https://github.com/laurent22/joplin/files/8016320/syncReport-1644246192718.txt)

**Comment by roman-r-m** [comment]
I think this is your keyboard doing the replacement, not Joplin.

**Comment by DarkPurpleKnight** [comment]
@roman-r-m Thanks for the tip. Ditching my alternative keyboard app and using the default keyboard app solved the problem.
