### ISSUE TITLE
Can't type anything in Joplin-Desktop App

### ISSUE THREAD

**Issue by jinmax100** [laurent22/joplin#6128]
## Environment

Joplin version: 2.6.10-4
Platform: Linux
OS specifics: Arch Linux with BSPWM

## Steps to reproduce

1. Installed Joplin-Desktop App in Arch Linux,
2. Synchronized my notes using Dropbox. All the notes appeared in the App,
3. Can't edit notes in editor nor  write anything in new notes created. 

## Describe what you expected to happen

I expected that I could write new notes or edit the existing ones in editor layout as I did while I was in Manjaro and Vanilla Arch with KDE Plasma

## Logfile
Running the debug commands as suggested in Joplin website I saw one issue but I am not sure if this is completely related with my issue 

```
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. In a future version of Chrome, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
```

**Comment by r0nz-29** [comment]
Installed `joplin-desktop` from the AUR - and I'm facing this issue too. I'll try to find the reason.

**Comment by CalebJohn** [comment]
Please report Aur issues to the [aur package maintainer](https://aur.archlinux.org/packages/joplin) directly to ensure they get seen in a timely manner.

**Comment by jinmax100** [comment]
> Please report Aur issues to the [aur package maintainer](https://aur.archlinux.org/packages/joplin) directly to ensure they get seen in a timely manner.

Yes, I've issued a query in the comment section in AUR. Anyway solution would be much appreciated.

**Comment by jinmax100** [comment]
> Installed `joplin-desktop` from the AUR - and I'm facing this issue too. I'll try to find the reason.

Did you happen to find any solution for this issue?

**Comment by jinmax100** [comment]
I ended up installing joplin-desktop-bin from AUR and it seems to be working fine. I didn't get any help from AUR as well for the quoted issue. I don't think I will get anytime soon as well. Therefore, i am closing this issue.
