### ISSUE TITLE
Exported JEX notebook should not contain share metadata

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#6129]
When exporting as JEX or RAW, the note `share_id` should be unset (like `is_shared` is currently unset).

Otherwise when importing back the data, Joplin will think the notebook is shared even though it is not (because a new notebook is created).

See this thread for more info: https://discourse.joplinapp.org/t/unshare-notebook-after-return-from-joplin-cloud-to-own-server/23485/9?u=laurent

**Comment by adi611** [comment]
Please assign me this issue.

**Comment by itsritiksingh** [comment]
i'm too working on it

**Comment by itsritiksingh** [comment]
@laurent22 share_id is already being set to empty string while exporting.
here : private normalizeItemForExport(itemType: ModelType, item: any): any {
		if (itemType === ModelType.Note) {
			const output: NoteEntity = { ...item };
			output.is_shared = 0;
			output.share_id = '';
			return output;
		} else {
			return item;
		}
	}

**Comment by laurent22** [comment]
Resource and notebook can also have a share_id so that there's where it actually needs to be cleared.

**Comment by itsritiksingh** [comment]
ok i'm on it!

**Comment by laurent22** [comment]
Remember that we need unit tests. Please don't create a pull request without them.
