### ISSUE TITLE
PDF Export - Title Header always shown twice

### ISSUE THREAD

**Issue by AlexJH4U** [laurent22/joplin#6133]
When exporting to PDF, the Title of the note is always presented as the H1 item on the page.  The first line of the note displays under the H1 heading.  Since the title of the note is also the first line of the note, it results in the same text always being shown twice.

![Screen Shot 2022-02-07 at 7 59 45 PM](https://user-images.githubusercontent.com/24720091/152898212-89c41e92-3411-4df8-a713-e0698b7a7a32.png)
![Screen Shot 2022-02-07 at 7 59 21 PM](https://user-images.githubusercontent.com/24720091/152898213-830afb4c-b41c-472d-80f1-8f25417ba0e6.png)

## Environment

Joplin version: 
Mac OS X latest

## Steps to reproduce

1.  Create a new note with the title of Test
2.  For the note body, have the contents of `# Test`
3.  Export to PDF
4. Observe that "Test" is output twice.

## Describe what you expected to happen

I believe user preferences are needed for export customization: 
- Should the Title always be shown as H1   -or maybe-
- Don't include note title as heading in exports
 
If the application supported a custom note "Titles" that could be different in text from the first line of the note, then perhaps the approach would be different.

![Screen Shot 2022-02-07 at 7 48 33 PM](https://user-images.githubusercontent.com/24720091/152897818-fd2d7d68-fc6e-4565-a00a-dcf81c0f735a.png)
![Screen Shot 2022-02-07 at 7 48 20 PM](https://user-images.githubusercontent.com/24720091/152897819-c4cae578-6fec-4503-83ac-382feec44616.png)

---

![Screen Shot 2022-02-07 at 7 59 45 PM](https://user-images.githubusercontent.com/24720091/152897938-e8212cb0-6280-44ee-bd96-55477b571b9f.png)
![Screen Shot 2022-02-07 at 7 59 21 PM](https://user-images.githubusercontent.com/24720091/152897940-af162c54-f9b0-43a7-99cc-accbabdd1cb7.png)

**Comment by graphit0** [comment]
Well, I'm sorry but I think you're a bit confused about markdown document structure:

The title shouldn't be a part of TOC, whereas the header is. So if we don't include the title, all that's left is headless chapters of the document.

Also, If you just make the title to be header1, how'd you differentiate between the header1 and title of the note?

My suggestion to you is to use the title for its intended use: name of the document. So you may not to duplicate the title in the header, but use the header as a name of a chapter (if the chapter is needed in the document).

**Comment by CalebJohn** [comment]
@graphit0 Joplin allows using the first line of a note as the title, so @AlexJH4U's use case is valid here.

I agree that this should probably be an option.

> If the application supported a custom note "Titles" that could be different in text from the first line of the note, then perhaps the approach would be different.

Joplin does support this, and if I had to guess that's how most people use titles. You can have the Joplin auto focus the title bar when creating a new note under Tools->Options->Note->When creating note->"Focus title". You can also just click on the title and edit it as a separate field.
![image](https://user-images.githubusercontent.com/2179547/153144267-91a7e728-ab62-4db0-b928-61db4c973696.png)

**Comment by AlexJH4U** [comment]
>> If the application supported a custom note "Titles" that could be different in text from the first line of the note, then perhaps the approach would be different.

> Joplin does support this, and if I had to guess that's how most people use titles. You can have the Joplin auto focus the title bar when creating a new note under Tools->Options->Note->When creating note->"Focus title". You can also just click on the title and edit it 

Thanks very much for clarifying this and sorry for the confusion.

I am able to now edit the Title and First Line independently of one another.  Not sure why, at the time of writing this issue, I could not set focus on the Title.  I did try, but had issues — and assumed the “Focus Title” option wouldn’t solve my issue because the two were two-way bound.

As such, this might just be a feature enhancement request, to allow the hiding of the note title output from presenting on the document, always.  Being able to hide that output, whether on the Export options modal or in app configuration options would be very handy.

Looking forward to exploring the code base and getting involved.

Thanks,
Alex

**Comment by tessus** [comment]
> Joplin allows using the first line of a note as the title, so @AlexJH4U's use case is valid here.

@CalebJohn it's not valid, because in case the first line starts with a `#` to denote a header, the `#` sign would also be in the title.

In such a case the PDF would have looked like this:

```
# Title

Title

.....other text here

```

not like the OP stated.

The OP even had different text in their repro steps:

Title: `test`
First line: `# test`

----

As a general note for anyone who is reading this: I have specifically not replaced the title with a H1, otherwise the `Title` would show up as `1. Title` in the TOC.

**Comment by CalebJohn** [comment]
@tessus Joplin strips markdown characters out when copying the first line to a title. OP's examples are correct.

example
![image](https://user-images.githubusercontent.com/2179547/153314130-e70f06c1-b220-434b-b13e-6a17e17fc42b.png)

    # Title [some](link.ca)

**Comment by tessus** [comment]
Wow, ok. I haven't been using this featue for years, since I focus the title and not the body upon note/todo creation.

Has the stripping of markdown always been done since the beginning of Joplin? I remember it differently, but I can be mistaken of course.

**Comment by CalebJohn** [comment]
> Has the stripping of markdown always been done since the beginning of Joplin? I remember it differently, but I can be mistaken of course.

I don't think so, I remember it being worked on either last year or the year before. It might have been broken and fixed?

**Comment by tessus** [comment]
Ok, because I never realized that this change was implemented. I didn't even try, because thee repro steps are in this order:

1. Create a new note with the title of Test
2. For the note body, have the contents of `# Test`

But thanks for the info. It's good to know that generating the title from the first line strips markdown.

**Comment by akarzim** [comment]
My two cents. If I export a note into Markdown, I only get the body of the note.

```md
# Title

.....other text here
```

If I export a note into Markdown+Frontmatter, I get the title of the note as "metadata" in the frontmatter.

```md
---
title: My custom note title 
updated: 2023-04-17 12:57:27Z
created: 2022-11-13 20:16:48Z
---

# Title

.....other text here
```

So, IMHO the title of the note should be considered as metadata in the PDF file, and not displayed on the document.

<img width="416" alt="image" src="https://user-images.githubusercontent.com/130560/232495959-6fb2c10e-71b5-4a15-92b4-82168f1098fe.png">

Here we can clearly see that the "Title" field ("Titre" in french) is empty. It should be a choice location for "My custom note title".
