### ISSUE TITLE
Cannot go back in synchronise menu

### ISSUE THREAD

**Issue by itsritiksingh** [laurent22/joplin#6134]
If you choose dropbox in synchronise menu , after that you cannot go back to synchronise menu again

## Environment

Joplin version: joplin 2.6.10(prod,darwin)
Platform: win
OS specifics: win 11

## Steps to reproduce

1. Go to File>Synchronise and select dropbox
2. now you cannot go back and select other sync. options

video : https://recordit.co/xGQosaQ1ji

**Comment by laurent22** [comment]
Is it because the window is too small?

**Comment by itsritiksingh** [comment]
No back button takes you directly to home page rather than going back

**Comment by itsritiksingh** [comment]
Please assign me this issue so that i can start working on it.
