### ISSUE TITLE
Todo disappear in note list after "hide-show" operations of note list

### ISSUE THREAD

**Issue by Oaklight** [laurent22/joplin#6137]
After undo hiding of the note list, all the todo items disappeared, with a block of empty space above all note items
![image](https://user-images.githubusercontent.com/13076552/153385559-713ef665-4fec-41c2-9bf4-c677bc821505.png)
After changing btw notebooks, they came back
![image](https://user-images.githubusercontent.com/13076552/153385677-7c69a73c-ac3a-4644-9fc5-d896697769b3.png)

## Environment

Joplin version: 2.6.10 (prod, win32)
Platform: Windows 10 Pro
OS specifics: 10.0.19044 Build 19044

## Steps to reproduce

1. hide the note list
2. write some note
3. show / undo hiding of the note list

## Describe what you expected to happen

Todo items shouldn't disappear by any means.

**Comment by roman-r-m** [comment]
The important part seems to be having manual sort order.

I can reproduce it without any TODOs at all like this:
1. Set manual sort order
2. Hide note list (F11)
3. Create a new note (e.g. by pressing Ctrl+N), type something to make sure it's saved
4. Restore note list - it's empty

![image](https://user-images.githubusercontent.com/995612/153388521-d5d3a68d-16fc-471d-b5f7-7555e592249e.png)


This is on 
Joplin 2.7.0 (prod, linux)

Client ID: 934e50ae74a941f587912680f6d54c43
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: a6ff60aa9 (dev)

**Comment by itsritiksingh** [comment]
I'm on it

**Comment by Oaklight** [comment]
> I'm on it

any update? what's the cause?

**Comment by Oaklight** [comment]
I update my Jopin to the latest (Joplin 2.7.15 (prod, win32)) and the issue still exist
