### ISSUE TITLE
NextCloud Sync issue

### ISSUE THREAD

**Issue by TomoakiChenSinica** [laurent22/joplin#6138]
I have an issue, I create an NextCloud Server to sync my Joplin data.
in the past few days. One of my device cannot sync data correctly.
I got error below
<pre>
Completed: 2022-02-11 14:13 (28s)
Last error: Error: PUT locks/1_1_28c41dd9e2d647f39976b2d40e494548.json: File with name /locks/1_1_28c41dd9e2d647f39976b2d40e494548.json could not be located (Exception Sabre\DAV\Exception\NotFound) (404): <?xml version="1.0" encoding="utf-8"?> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"> <s:exception>Sabre\DAV\Exception\NotFound</s:exception> <s:message>File with name /locks/1_1_28c41dd9e2d647f39976b2d40e494548.json could not be located</s:message> </d:error>
</pre>

I have checked the sync status, it's ok.
and I have 「deleted my local data and re-download from sync target」 in synchronization page,
and it's still wrong.
![image](https://user-images.githubusercontent.com/18282066/153545654-04c9ebaa-7a78-40d4-955d-aed9d04f4a96.png)

please help me to solve the problem, and sorry for the poor english.
Thank you.

## Environment

Joplin version: Joplin 2.6.10
![image](https://user-images.githubusercontent.com/18282066/153545080-98e297b0-a39c-4aaf-94d6-c2206685dc96.png)
Platform: Windows
OS specifics:  Win10

**Comment by TomoakiChenSinica** [comment]
p.s It's ok in my other device

**Comment by leematos** [comment]
Please update the title to include NextCloud -> "NextCloud Sync issue" so that others who use nextcloud can more easily find it. 😄

**Comment by TomoakiChenSinica** [comment]
> Please update the title to include NextCloud -> "NextCloud Sync issue" so that others who use nextcloud can more easily find it. 😄

Thank you, I have changed the title.
