### ISSUE TITLE
Move to GitLab?

### ISSUE THREAD

**Issue by ReekyMarko** [laurent22/joplin#614]
I know I'm going to get a lot of flack for this, but this is just a friendly suggestion. I'm not trying to start a flamewar here.

So, as all of you probably know, Microsoft acquired GitHub a while ago. GitHub has never been open source but now that it's in the hands of a big company that has had a very unfriendly attitude towards open source in general, in my opinion everyone should be considering alternatives.

One great alternative is gitlab.com, which is FOSS (except of a few paid features). You could even host your own instance if you wanted.

Again, just an idea, not trying to offend anyone.

**Comment by laurent22** [comment]
Hmm, let's see how it turns out. Although I'd also prefer if GitHub was independent, for now there's no issue so let's wait and see.
