### ISSUE TITLE
Joplin appimage cannot show icon

### ISSUE THREAD

**Issue by newyorkthink** [laurent22/joplin#6142]
![image](https://user-images.githubusercontent.com/87791643/153706425-bc0d0cef-bdd5-416b-bbac-8e4ca7a856ee.png)

looking it ,the gnome dock cannot show icon

**Comment by Daeraxa** [comment]
But did you install from the script or download the appimage?

**Comment by newyorkthink** [comment]
> But did you install from the script or download the appimage?

yes

**Comment by newyorkthink** [comment]
> But did you install from the script or download the appimage?

looking like this 
![image](https://user-images.githubusercontent.com/87791643/153739030-874b02b9-1089-4176-b964-0abcec2f45c2.png)

**Comment by newyorkthink** [comment]
![image](https://user-images.githubusercontent.com/87791643/153739093-0eccf3b2-6b03-462e-ae6c-812894d89917.png)

just the one appimage. joplin icon in GNome not working

**Comment by Daeraxa** [comment]
I give up, can't help if you don't answer the question

**Comment by newyorkthink** [comment]
> Did you install from the script or just download the appimage?

i just download the appiamge,
not use install from the script

**Comment by newyorkthink** [comment]
> I give up, can't help if you don't answer the question

never give up ,go go go.

**Comment by Daeraxa** [comment]
The standard appimage download does not handle .desktop creation, that is what the install script does. So if you don't have one you will need to make it.

**Comment by newyorkthink** [comment]
> The standard appimage download does not handle .desktop creation, that is what the install script does. So if you don't have one you will need to make it.

i know it.

but author/coder can handle .desktop in appimage

**Comment by newyorkthink** [comment]
> The standard appimage download does not handle .desktop creation, that is what the install script does. So if you don't have one you will need to make it.

can you.

**Comment by Daeraxa** [comment]
That would be a feature request, not a bug and should be raised in the forum.
