### ISSUE TITLE
Opening a file with ctrl-click in the editor results in a ‘network error’ dialogue

### ISSUE THREAD

**Issue by ajsteele** [laurent22/joplin#6145]
## Environment

Joplin version:

Joplin 2.6.10 (prod, win32)
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 98fba37

Platform: Windows
OS specifics: 10

## Steps to reproduce

1. Ctrl-Click on a linked attachment (eg `[test.pdf](:/XXXXXX)`) in either the Markdown code editor or the rich text editor.
2. An error like this appears, I think because an unnecessary `\\` has been prepended to the file path:
![image](https://user-images.githubusercontent.com/6997662/153721626-2a220b18-d52f-4e19-90f2-081f80b1b1e7.png) 

## Describe what you expected to happen

The file opens.

## Update

Certain things work, for example:

- Open the attached file in Joplin's Markup version.
- Open in WYSIWYG by Ctrl+right clicking it and choosing 'Open file' from menu.

Which means whatever method is used there could be applied to the Ctrl-Click handler.

See https://discourse.joplinapp.org/t/cant-open-imported-notes-attachments/24647/3?u=laurent

**Comment by laurent22** [comment]
What's the full file path? Are there any special characters or spaces?

**Comment by ajsteele** [comment]
This happens with every file I’ve tried, and there are no special characters or spaces. In the file’s original name, there are just letters and underscores, and in its Joplin internal filename, just a long hex number.

**Comment by laurent22** [comment]
Does it happen with newly created notes too?

**Comment by ajsteele** [comment]
I just created a new note to doulbe-check, and yes.

I also noticed that my initial report was slightly mistaken: the problem only happens in the WYSIWYG editor, not the Markdown code editor. I’m not sure why I thought this—pretty sure it was doing it earlier but I can’t reproduce it now!

**Comment by Manish4044** [comment]
Hello, I am new to open source contribution. I want to fix this issue. So, is it fine if I start working on this bug?

**Comment by tessus** [comment]
Right below the `Comment` button you have clicked to post your question is a link to the contributing guidelines. Did you read them? If yes, you can create a PR.

**Comment by snipersteve** [comment]
I have the same issue, ctrl click on any file will popup the dialogue.

**Comment by Manish4044** [comment]
> Right below the `Comment` button you have clicked to post your question is a link to the contributing guidelines. Did you read them? If yes, you can create a PR.

I read the contributing guidelines. I am starting to work on this issue

**Comment by Manish4044** [comment]
I am trying on this issue since a few days. I wanted to confirm whether we are using electron shell to open files or are we using some other things.

**Comment by Manish4044** [comment]
Hey @laurent22 I have fixes this issue and it is working fine now. What should I do next to merge the code?

**Comment by tessus** [comment]
I thought you read the contribution guidelines. Where's th PR?

**Comment by Manish4044** [comment]
> I thought you read the contribution guidelines. Where's the PR?

I read it but I don't know how to make a PR request. I will learn it and make the request.

**Comment by tessus** [comment]
https://discourse.joplinapp.org/t/how-to-create-a-pull-request-pr/15052

**Comment by kauffy** [comment]
As a data point:

- I have this issue, running Windows 10 (10944).
- It happens with ANY attachment clicked on in the WYSIWYG/Rich editor.
- There is nothing remarkable about the file paths themselves and-- indeed-- it happens with both old and new Notes.
- I haven't recently updated my system in any significant way.
- I can confirm: Source for the rendered HTML in the WYSIWYG editor, the issue is simply that a "//" has been inserted in the UNC path for some reason, and editing this source to take the "//" out has the link work.
