### ISSUE TITLE
Unable to move folder way down below scroll 

### ISSUE THREAD

**Issue by brandontan** [laurent22/joplin#6146]
## Environment

Joplin version: Joplin 2.6.10 (prod, darwin)

Platform: MacOS 
OS specifics: 12.1 Monterey M1

## Steps to reproduce

1. Move a folder down

2. Joplin does not scroll down

See screen recording: https://recordit.co/JQkxeEFndt

## Describe what you expected to happen

I should be able to move the folder way down below the scroll. Enhancement : right click on source folder  and have a "Move To" option

**Comment by Daeraxa** [comment]
Can't replicate on Linux - folder list scrolls when item is held at bottom of pane
Possibly macOS specific?

**Comment by brandontan** [comment]
Possibly - please investigate. Thanks

**Comment by Daeraxa** [comment]
Can't replicate, works fine on macOS big sur.
2.6.10
OS: macOS 11.5.2 20G95 x86_64
