### ISSUE TITLE
Markdown editor and preview pane is not in sync

### ISSUE THREAD

**Issue by brandontan** [laurent22/joplin#6147]
## Environment

Joplin version: Joplin 2.6.10 (prod, darwin)

Platform: MacOS 
OS specifics: 12.1 Monterey M1

## Steps to reproduce

1. Scroll down the markdown editor

2. The preview pane does not sync up

See attached screenshot

## Describe what you expected to happen

The markdown editor should sync with preview pane

## Logfile

![CleanShot 2022-02-13 at 09 51](https://user-images.githubusercontent.com/1005474/153735011-7a3731db-688b-4d36-bb2f-73761f83c44e.png)

**Comment by ken1kob** [comment]
It looks completely sync-ed.
The top of the Editor is an image markup, which matches the image at the top of the Viewer.

**Comment by brandontan** [comment]
Preferably IMA <->IMA

**Comment by CalebJohn** [comment]
The sync scroll syncs the top of the editor with the top of the viewer, you have scrolled halfway through a line with an image, therefore the viewer is halfway through the corresponding image. 
Sync scrolling isn't magic, it can't guess which elements you think should be synced.
