### ISSUE TITLE
Block Quote is not applied to blocks with list tags

### ISSUE THREAD

**Issue by brandontan** [laurent22/joplin#6149]
## Environment

Joplin version: Joplin 2.6.10 (prod, darwin)

Platform: MacOS 
OS specifics: 12.1 Monterey M1

## Steps to reproduce

1. Add a ">" Block Quote to a text block with List tags
2. The first line is affected

## Describe what you expected to happen

The entire text block should be affected by the block quote

## Logfile

![CleanShot 2022-02-13 at 13 35 17](https://user-images.githubusercontent.com/1005474/153740432-a43699a5-4478-47f9-9a89-91cdcaa59b3e.png)

**Comment by Daeraxa** [comment]
Pretty sure this is expected behaviour as lazy continuation only works on continuous paragraphs.
> Laziness only applies to lines that would have been continuations of paragraphs had they been prepended with [block quote markers](https://spec.commonmark.org/0.30/#block-quote-marker).

https://spec.commonmark.org/0.30/#example-235

**Comment by brandontan** [comment]
Would be nice to enable this

**Comment by Daeraxa** [comment]
That probably won't be done, it doesn't conform to commonmark spec which would break portability. If you break the markdown spec then what you are writing is no longer markdown.
