### ISSUE TITLE
List tags should affect lines with text 

### ISSUE THREAD

**Issue by brandontan** [laurent22/joplin#6150]
## Environment

Joplin version: Joplin 2.6.10 (prod, darwin)

Platform: MacOS 
OS specifics: 12.1 Monterey M1

## Steps to reproduce

1. Create a spaced out text block
2. Use the "List" button on the text block
3. Empty lines are tagged with List tags as well

Please see : https://recordit.co/mzZW2PclX4

## Describe what you expected to happen

Lines with text should be impacted only by List tags

**Comment by graphit0** [comment]
Although, it's more like a feature request, same behaviour is observed with checkboxes as well
