### ISSUE TITLE
Joplin config folder does not work with symlinks

### ISSUE THREAD

**Issue by BeatLink** [laurent22/joplin#6151]
When creating Joplin's configuration folder at ~/.config/joplin-desktop as a symlink to a folder located elsewhere, joplin is unable to launch showing the error: 

`EEXIST: file already exists, mkdir /home/username/.config/joplin-desktop`

## Environment

Joplin version: 2.6.10
Platform: Linux
OS specifics: Linux Mint 20.3

## Steps to reproduce

1. Replace ~/.config/joplin-desktop with a symlink pointing to those files at another location
2. Launch Joplin
3. See the error

## Describe what you expected to happen
Joplin should be able to navigate the symlink to the actual files and launch normally

**Comment by tessus** [comment]
I have just tested this with the last commit in dev and I can't reproduce this.

Do you use flatpack or snap? Afaik they use a sandbox system. Not sure about appimage.
What happens, if you use the `--profile` parameter? I'm just rying to narrowing down the issue....

**Comment by tessus** [comment]
Have you checked if this is a known issue in the fs-extra package?

The strange thing is that I couldn't reproduce it, but I didn't use the Flatpak image. What about the AppImage?

**Comment by BeatLink** [comment]
You're right. After retesting, the problem seemed to have been my flatpak permissions. Closing this issue
