### ISSUE TITLE
[Linux] Use Freedesktop dark mode

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#6153]
As many applications and desktop environments are switching to brand new Freedesktop dark theme standard, I think it would be great to see Joplin using it. It would make Joplin look like first class citizen regardless of the desktop environment.

- https://github.com/flatpak/xdg-desktop-portal/pull/633/
- https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/49
- https://github.com/flatpak/xdg-desktop-portal/blob/d7a304a00697d7d608821253cd013f3b97ac0fb6/data/org.freedesktop.impl.portal.Settings.xml#L33-L45
- https://bugzilla.mozilla.org/show_bug.cgi?id=1734934

**Comment by Daeraxa** [comment]
This would be an enhancement/feature request so should be discussed on the forums.

**Comment by CalebJohn** [comment]
Also @MakeGnomeWebFaster can you provide more information? I'm interested in this but I'm not plugged into these things and don't really know what you're requesting. I'm guessing this is a way for the OS to indicate that an application should be opened in dark mode? I did some searching online, but it would be better to actually here from you what the request is.

**Comment by MakeGnomeWebFaster** [comment]
Sorry I should have probably have provided more info on this @CalebJohn but in a nutshell free desktop has started to provide a system wide light/dark theme option, freeing the user from tinkering the desktop environment (i.e switching between Adwaita and Adwaita dark via GNOME tweak tool). [This](https://blog.elementary.io/the-need-for-a-freedesktop-dark-style-preference/) and [this](https://www.omgubuntu.co.uk/2021/10/gnome-42-dark-style-preference) can provide more info.

**Comment by CalebJohn** [comment]
I found this post really helpful. 
https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference/

Looks like this requires using some native APIs. This is usually handled for us by Electron. I wonder if we'll get this support free once electron implements it, we already have the light/dark working for windows and macOS through the electron apis.

**Comment by MakeGnomeWebFaster** [comment]
Humm, Joplin Linux app has a toggle that allows to follow DE specific dark mode, so it already respects the GTK theme. I assume it wouldn't be a problem but I didn't know that Electron has to implement this feature first.

**Comment by CalebJohn** [comment]
Looks like I was mistaken, I thought that only worked on windows and macOS. In either case, we don't access the the DE stuff directly, it all comes through Electron.

**Comment by MakeGnomeWebFaster** [comment]
Hi, Discord app is also an electron app and it uses the aforementioned freedesktop theme. So, I think it is possible withouth touching any DE stuff. If you're interested, I am posting a few links here.

https://github.com/flathub/com.discordapp.Discord
https://github.com/flathub/net.cozic.joplin_desktop/
