### ISSUE TITLE
Web Clipper : Does not capture original URL in captured HTML

### ISSUE THREAD

**Issue by brandontan** [laurent22/joplin#6155]
## Environment

Joplin version: Joplin 2.6.10 (prod, darwin)

Platform: MacOS 
OS specifics: 12.1 Monterey M1

## Steps to reproduce

1. Use "Clip Simplified Page"
2. HTML is captured
3. No link to original HTML is included in header

## Describe what you expected to happen

URL to clipped page should be included

**Comment by Daeraxa** [comment]
URL of clipped notes is stored in the note properties.
Discussion of storing the URL elsewhere (like OneNote) is being discussed already

**Comment by laurent22** [comment]
That could be done with a plugin - it would just monitor newly created notes, check the metadata, and add the URL at the bottom of the note.

**Comment by brandontan** [comment]
Hope this will be implemented soon
