### ISSUE TITLE
Thanks for not spying on users

### ISSUE THREAD

**Issue by gerroon** [laurent22/joplin#616]
Hi

I would like to thank the devs for not implementing tracking into this app like Qownnotes does. Some devs think that they have natural born rights to implement all kinds of trackings in the name of improving their apps. 

I am not against tracking as long as it is concensual and the user is aware of such activity. I used to like qownnotes until I realized that it sends infromation to the devs. MAking an open source app does not justify tracking openly either, that is just stalking. 

Anyway keep up the good work.

**Comment by laurent22** [comment]
No problem, none of the apps have any tracking and there's indeed no plan to add any. By the way, for this kind of discussion the forum would probably be a better place :-) It works with GitHub login too.
