### ISSUE TITLE
Ask how to set CSS styles for the Joplin Android version, just like the desktop version.

### ISSUE THREAD

**Issue by huaqic** [laurent22/joplin#6160]
## Environment

Joplin version: 2.6.9
Platform: Android 11

On the desktop, you can use CSS styles to define title background colors.
The Android version has no background color.

 Windows Joplin：
![windows](https://user-images.githubusercontent.com/40896822/153895969-a0ea5c63-22c2-4721-a525-7a1b3476379d.png)

Android Joplin：
![android](https://user-images.githubusercontent.com/40896822/153896068-7cad1980-0afc-4842-a9f6-57225ee7c4a2.jpg)

**Comment by Daeraxa** [comment]
This would be a feature request, not a bug so should be opened on the forum for discussion.

**Comment by huaqic** [comment]
@Daeraxa ok
