### ISSUE TITLE
Multi-cursor editing: editor loses focus on alt-drag

### ISSUE THREAD

**Issue by zblesk** [laurent22/joplin#6161]
This is an issue with the behavior of multi-cursor editing in the MD editor. It does work, but the focus jumps around.

I'm talking about placing cursors on multiple lines, like this: 

![](https://aws1.discourse-cdn.com/standard14/uploads/cozic/original/2X/8/843e22ff69cdbaab6eae39c5ea9c2d8b21b88ad8.gif)

(Image taken from this [forum thread](https://discourse.joplinapp.org/t/blockquote-button-in-toolbar-in-desktop-app-or-keyboard-shortcut/4673/10?u=zblesk). The issue was present even back then, so it's not new. I just hadn't realized immediately that it happens always, not just sometimes.)

## Environment

Joplin 2.6.10 (prod, win32)

Client ID: bee3eb494cf64baa81d038c29abc497f
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: 98fba37

Windows 10

## Steps to reproduce

1. hold down <kbd>alt</kbd> in the MD editor
2. hold down the left mouse button, drag the mouse vertically over multiple lines of text
3. release mouse button
4. release <kbd>alt</kbd>

## Describe what you expected to happen

After releasing <kbd>alt</kbd>, a cursor should appear on every line I dragged the mouse over, letting me edit in multiple places at once.

Bug: instead, when I release <kbd>alt</kbd>, the MD editor loses focus and the Joplin menu is focused instead. 

Workaround: the cursor placement apparently _does_ happen correctly; when I press <kbd>ESC</kbd> once or twice, the focus moves back from the menu to the editor. I can then press an arrow and the cursors appear in expected places. 

My guess is that multilcursor editing might be present because it's a feature of the underlying editor? From the behavior it seems that it could be fixed by not letting <kbd>alt</kbd> focus the menu in case a mouse click also happened while it was pressed.

**Comment by Daeraxa** [comment]
I can't seem to replicate this from your steps (2.6.10, Linux Mint).
When I release alt the cursor shows and I can type with multi cursor.
Potentially Windows specific?

**Comment by zblesk** [comment]
Don't know, don't have a linux box with gui.

**Comment by Daeraxa** [comment]
Yup, seems specific to Windows, I can replicate it there but not Linux.

**Comment by Manish4044** [comment]
I tried replicating the problem. When the alt key is released, the focus changes to menubars, which is the default behavior of the alt key in the application. On pressing the alt key back again, the focus comes back to multiple lines, and then we can type.

**Comment by zblesk** [comment]
The issue still persists in latest Joplin.

**Comment by zblesk** [comment]
Not fixed afaict.

**Comment by zblesk** [comment]
Issue still persists.

**Comment by zblesk** [comment]
The issue still persists.

**Comment by zblesk** [comment]
The issue still persists.

**Comment by zblesk** [comment]
The issue still persists.

**Comment by zblesk** [comment]
The issue still persists.

**Comment by zblesk** [comment]
Issue still persists.

**Comment by zblesk** [comment]
Issue still persists.

**Comment by zblesk** [comment]
Issue still persists.

**Comment by zblesk** [comment]
Issue still persists.

**Comment by zblesk** [comment]
Issue still persists.

**Comment by zblesk** [comment]
Issue still persists.

**Comment by zblesk** [comment]
Issue still persists.

**Comment by zblesk** [comment]
Issue still persists.

**Comment by zblesk** [comment]
Issue still persists.

**Comment by zblesk** [comment]
:(
