### ISSUE TITLE
Characters dissappear in code blocks

### ISSUE THREAD

**Issue by udgithub** [laurent22/joplin#6162]
Hi all,

I'm using "*" and questions marks with a leading backslash like "\?" to mask the "?" in a regexp in a code block in the markup mode.

<code>
cd /mnt/old-apache-logs/2021
zcat ssl-access.log-2021*gz xyz*gz | egrep "GET /path\?param1=value1" | grep whatever 
</code>

As soon as I insert a newline after the "cd" line the "*" and the "\" vanish in my output window with the styled output.

<code>
cd /mnt/old-apache-logs/2021

zcat ssl-access.log-2021*gz xyz*gz | egrep "GET /path\?param1=value1" | grep whatever 
</code>

Presentation of the second line in the output window without markup:
zcat ssl-access.log-2021gz xyzgz | egrep "GET /path?param1=value1" | grep whatever

I'm using code blocks by using <code> or 3 backticks a lot.
And I realized this error when copying old code back and tried to run it which of course failed.

Thanks a lot for any help !

## Environment

Joplin version:  2.6.10 (prod, win32)
Platform: Windows 10 Pro
OS specifics: 

## Steps to reproduce

try my example from above !

## Describe what you expected to happen

I expect that the "*" and the backslash do not dissappear.

## Logfile

Console shows this error / warning:

DevTools failed to load source map: Could not parse content for file:///C:/Users/<username>/AppData/Local/Programs/Joplin/resources/app.asar/Dialog.js.map: Unexpected end of JSON input

**Comment by CalebJohn** [comment]
Hi @udgithub can you provide more info about your problem? For example what editor are you using when this happens? Do you have any custom css (userchrome.css)? Any plugins?

I wasn't able to reproduce this using your steps above.
![image](https://user-images.githubusercontent.com/2179547/154112373-ea2a2540-c611-4610-9240-f011cbe44405.png)

**Comment by udgithub** [comment]
Hi John,

thanks for the fast reaction.
I'm using the built-in editor of Joplin and I do not use my own css

Bye, Uwe

**Comment by Daeraxa** [comment]
I also can't seem to replicate this:
![image](https://user-images.githubusercontent.com/58074586/154503981-7fa3faa3-c350-4d12-8b0f-b966e709d905.png)

**Comment by CalebJohn** [comment]
@udgithub Joplin has 2 built in editors, can you clarify which one you use? Is it the split one that Daeraxa and I have taken screenshots of?

**Comment by udgithub** [comment]
I also use the split one.
Insert a newline after the line starting with "cd ...."

**Comment by Daeraxa** [comment]
> Insert a newline after the line starting with "cd ...."

Is that not what I did in my example? I have extra lines both inside and outside of the code fence

**Comment by udgithub** [comment]
In your screenshot the zcat-cmd is in the same line as the "cd".
Ah, I found the mistake.
In my first message I !!! wrote the "cd" and the "zcat" have been in the same line !
Sorry ! My bad !!

Try
```
cd /mnt/old-apache-logs/2021
zcat ssl-access.log-2021*gz xyz*gz | egrep "GET /path\?param1=value1" | grep whatever
```
vs

```
cd /mnt/old-apache-logs/2021

zcat ssl-access.log-2021*gz xyz*gz | egrep "GET /path\?param1=value1" | grep whatever
```

**Comment by CalebJohn** [comment]
Okay I've got it now. @udgithub please provide screenshots in the future, they can be very helpful for demonstrating visual issues like this.
![image](https://user-images.githubusercontent.com/2179547/154749146-82589ba0-64de-4471-8925-670c226c7be2.png)
![image](https://user-images.githubusercontent.com/2179547/154749192-1e53ca7d-57dc-4399-8a1e-51964f4bb401.png)
![image](https://user-images.githubusercontent.com/2179547/154749284-23b60e16-0253-408a-95fa-cb1e86848a30.png)

Looks like this only happens when using the html `<code>` tag.

**Comment by udgithub** [comment]
yes, or if you are using 3x backticks

**Comment by Daeraxa** [comment]
We can't seem to replicate it with the code fence (backticks).
Here are all 6 - code fence, `<code>` and indent styles. It only seems to show the problem in the code block.

![image](https://user-images.githubusercontent.com/58074586/155497545-d2107455-3c3f-4ec5-882a-b7c44f7635ab.png)

**Comment by udgithub** [comment]
yes you are right - sorry  !
I was only thinking that I got the same problem also with backticks syntax cause I'm using something the backticks and sometimes code
