### ISSUE TITLE
Menu List On Android Appears on Only Half the Screen

### ISSUE THREAD

**Issue by KevinStars** [laurent22/joplin#6163]
I just installed the Joplin App for the first time on my android phone and whenever I press the 3 lines in the top right corner I only see half the list (as seen in the screen shot). Why is this happening and how do I fix it?

**Comment by KevinStars** [comment]
![Screenshot_2022-02-15-23-02-51-48_97a2b898327add53e982bbebadc3de52](https://user-images.githubusercontent.com/99770441/154165516-de4459f8-379e-45c2-8b82-6e168bdd4b7d.jpg)

**Comment by Daeraxa** [comment]
Duplicate of https://github.com/laurent22/joplin/issues/5586

**Comment by Manish4044** [comment]
should sidebar cover entire space of android screen or just enough width to fit the content?

**Comment by Daeraxa** [comment]
It should cover a portion of the screen and the notebooks should fit within it.

**Comment by Manish4044** [comment]
I checked this thing. It is working fine on my android phone.

**Comment by KevinStars** [comment]
So no ideas how to fix it? it's so annoying

**Comment by roman-r-m** [comment]
I see you have some text in Hebrew (?) there in the background. May be something to do with RTL vs LTR text. What's the language on the device?

**Comment by KevinStars** [comment]
the language on the device is indeed hebrew but Ive seen comments before having the same problem with english only. anyway how do i solve this issue if its actually related to the rtl or ltr?

**Comment by roman-r-m** [comment]
If you could switch to english and see if the issue disappears this should tell if it's what causing the issue.
What model is your phone? Maybe you have some unusual screen size.

**Comment by KevinStars** [comment]
i switched the language to english and it still doesn't work. The phone is a Realme 7 pro

**Comment by KevinStars** [comment]
i switched the language and it still doesn't work. The phone is a Realme 7 pro

**Comment by KevinStars** [comment]
i switched the language and it still doesn't work. The phone is a Realme 7 pro

**Comment by KevinStars** [comment]
but you see here https://github.com/laurent22/joplin/issues/5586 other people have the same problem without any relation to hebrew

**Comment by roman-r-m** [comment]
Yes, just wanted to make sure. No idea what could be causing this, I'm afraid.

**Comment by prashantkr006** [comment]
Is this issue still happening? I can't figure it out on my phone? its working fine in my device

**Comment by Daeraxa** [comment]
Almost certainly yes but it seems there just isn't enough info for exact replication steps yet to determine the cause. It seems to be certain edge cases where this happens, certainly not global.

**Comment by KevinStars** [comment]
I stopped using the app because of this issue. No one bothered fixing it

**Comment by Daeraxa** [comment]
> I stopped using the app because of this issue. No one bothered fixing it

It isn't that nobody has "bothered" to fix it, it seems to be difficult to replicate and nobody has been able to provide repeatable replication steps.
