### ISSUE TITLE
Onedrive login second step not working on iOS/iPhone

### ISSUE THREAD

**Issue by jmjw** [laurent22/joplin#6164]
Using Onedrive for business I cannot login in Onedrive to synchronize. Works fine on iPadOS (same version of Joplin and OS).

## Environment

Joplin version: 12.7.1
Platform: iOS 15.3.1
OS specifics: 

## Steps to reproduce

1. Select OneDrive synchronization in Config
2. Start Sync, Microsoft login screen opens
3. Enter email address and tap on "Next"
4. Blank screen is shown

## Describe what you expected to happen

SSO/SAML Login page from company should open, I enter my credentials, login succeeds (which it does on iPadOS, same version of Joplin and OS).

## Logfile

No debug log available.

**Comment by jmjw** [comment]
OneDrive App is working fine, without login issues.

**Comment by WolfGangsta** [comment]
Bump to keep the issue active--it continues to affect Joplin on my iPhone.

I'm a bit inexperienced with bug reports, so please let me know if you need any more information.

**Comment by WolfGangsta** [comment]
Just found out about #4980--it looks like this issue is a derivative of it.

@jmjw do you have the accessibility option `Motion > Prefer Cross-Fade Transitions` checked? If you do, try unchecking it and see what happens. When I unchecked it and signed out of OneDrive, I was able to sign back in without any of the aforementioned problems.

**Comment by jmjw** [comment]
Now this is strange. Reading the Accessibility thing I checked, and on my phone Reduce Motion was off and therefore no cross-fade transitions switch was visible. Then I switched on „reduce motion“, switched off „cross-fade transitions“ and login pages were visible. 
Thanks!
