### ISSUE TITLE
Jump to position one on typing backticks

### ISSUE THREAD

**Issue by Grarie** [laurent22/joplin#6165]
When I try to edit a note and add a code block with backticks my cursor jumps to the beginning of the note.

## Environment

Joplin version: 2.6.10 (prod, win32)
Platform: Windows
OS specifics: 11

## Steps to reproduce

1. Create new node or todo
2. type something
3. put cursor at last position (behind a letter)
4. press backtick button ( ` ) two times 

## Describe what you expected to happen

Two backticks should occur with the cursor being behind the second backtick.

## Additionakl notes

* Step to avoid reproduction: cursor behind whitespace (e.g. \n oder space)
* Problem migth be keyboard layout or device related. But it only occurs in Joplin Desktop. (checked with editor, sublime text, electron clients as signal)
* Letters containing the use of backticks work: e.g. à, è, ì, ò, ù
* circumflex and ticks have the same problem (every key which has to be pushed twice seems to cause the problem but only in combination with itself. )
* workaround:
  * space
  * 2 x backtick
  * 2 x leftarrow
  * backspace
  * 2x rightarrow 

## Logfile

Logfile does only contain synchronization content (and is difficult to anonymize). I will add it if explicitly needed.

**Comment by Grarie** [comment]
Thanks for the suggestion. It does indeed work properly in the single view rich text editor. The issue occurs with the split view (left: markdown source; right: markdown rendered).

How should I share the Markdown file? Export via Joplin delivers foo.md only containing the string "bar" (without quotes).

PS: I just deactivated all plugins. The problem persists.

**Comment by JackGruber** [comment]
Do you have enabled spell checking ?
https://github.com/laurent22/joplin/issues/4924 https://github.com/laurent22/joplin/issues/6044 https://github.com/laurent22/joplin/issues/5969

**Comment by Grarie** [comment]
Disabling spell checking does indeed work. Thank you very much @JackGruber!
Sorry for not finding the issue via search.

So there seems to be no solution right now other than disabling spell check? Might I help in some way?

Would it be a good idea to link to known issues in the options (as there is a hint to the beta status)?
