### ISSUE TITLE
Android - Trying to set a note history duration lower than 90 days causes the slider to glitch out

### ISSUE THREAD

**Issue by Elaborendum** [laurent22/joplin#6169]
Somewhat related to issue #3944, which was closed due to inactivity. I will try to provide a recording of the issue itself.

## Environment

Joplin version: 2.6.9
Platform: Android
OS specifics: Android 11

## Steps to reproduce

1. Go to settings
2. Try to use the slider to change the note history duration
3. See that if you try to set it to lower it, the bar instead changes sizes and the value jumps up and down.

## Describe what you expected to happen
Being able to set a lower history duration

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by wh201906** [comment]
I can reproduce it in v2.9.2. I'm using an Android device with small screen.

**Comment by Elaborendum** [comment]
Issue is still present.

**Comment by wh201906** [comment]
I think we should replace the slider in mobile application to other widgets, such as spinbox(spinner) or just TextInput. But I haven't found a good solution.
