### ISSUE TITLE
Android: typing auto-correction does not work when using the beta editor

### ISSUE THREAD

**Issue by korg91** [laurent22/joplin#6175]
On Android, when using the beta editor, the typing corrections on my keyboard (Gboard) are shown but are not accepted automatically when I enter a space after the word.

![image](https://user-images.githubusercontent.com/3729408/154662510-7f23e75d-d4b7-49a9-b14a-de93fd1d28e4.png)

## Environment

Joplin version: 2.6.8
Platform: Android
OS specifics: 

## Steps to reproduce

1. Activate the beta editor
2. Edit a note and type some text with a wrong word for which the keyboard suggest a correction
3. Enter a space
4. The suggested correction is not used

## Describe what you expected to happen

I would expect the word to be auto-corrected when I enter a space, just like in the standard editor (note that the suggested correction is in bold here, meaning that entering a space will auto-correct the word):

![image](https://user-images.githubusercontent.com/3729408/154663089-a12f7fff-64c2-4739-8b02-336b700956fa.png)

**Comment by korg91** [comment]
Comment to keep alive the issue as it's still affecting me (@tessus anything else I should do?)

Also, I have the feeling that the problem behind this issue is the same as https://github.com/laurent22/joplin/issues/5987.

**Comment by personalizedrefrigerator** [comment]
I wonder if this is an issue with [CodeMirror6](https://codemirror.net/6/) (the library we're using for the beta editor).

Does something similar happen with the editor on [the library Joplin uses (CodeMirror's)](https://codemirror.net/6/) homepage? I'm interested in whether this problem stems from an issue with Joplin or an issue with CodeMirror (or maybe an issue with the version of CodeMirror we're using).

Because CodeMirror is a code-editor, it might be [disabling auto-complete intentionally](https://stackoverflow.com/questions/21163002/disable-autocorrect-autocompletion-in-content-editable-div)...

**Comment by personalizedrefrigerator** [comment]
> I wonder if this is an issue with [CodeMirror6](https://codemirror.net/6/) (the library we're using for the beta editor).
> 
> Does something similar happen with the editor on [the library Joplin uses (CodeMirror's)](https://codemirror.net/6/) homepage? I'm interested in whether this problem stems from an issue with Joplin or an issue with CodeMirror (or maybe an issue with the version of CodeMirror we're using).
> 
> Because CodeMirror is a code-editor, it might be [disabling auto-complete intentionally](https://stackoverflow.com/questions/21163002/disable-autocorrect-autocompletion-in-content-editable-div)...

From the CodeMirror6 implementation on codemirror.net, it looks like they **are** intentionally disabling autocorrect:
![codemirror div with autocomplete=off, spellcheck=false](https://user-images.githubusercontent.com/46334387/160067232-f03f6900-fa2b-4266-be5a-2596da4055a4.png)

We should be able to toggle this from within Joplin.  Please see [`CodeMirror.ts`](https://github.com/laurent22/joplin/blob/dev/packages/app-mobile/components/NoteEditor/CodeMirror.ts) (where we set up styling for the editor) and [`NoteEditor.tsx`](https://github.com/laurent22/joplin/blob/dev/packages/app-mobile/components/NoteEditor/NoteEditor.tsx) (where we create the editor).

**Comment by personalizedrefrigerator** [comment]
Still an issue!

**Comment by korg91** [comment]
Still an issue

**Comment by korg91** [comment]
Still an issue

**Comment by personalizedrefrigerator** [comment]
Still an issue.

**Comment by korg91** [comment]
Still an issue

**Comment by personalizedrefrigerator** [comment]
Spellcheck was enabled in the beta editor -- this might be fixed in the next release.

**Comment by korg91** [comment]
Still an issue (at least in the current stable release)

**Comment by korg91** [comment]
Still an issue (at least in the current stable release)

**Comment by korg91** [comment]
Still an issue (at least in the current stable release)

**Comment by korg91** [comment]
> Spellcheck was enabled in the beta editor -- this might be fixed in the next release.

@personalizedrefrigerator I've just updated to the latest stable version on Android (2.9.8), but it looks like the bug is still there. The spellcheck option is enabled. Am I missing something?

**Comment by personalizedrefrigerator** [comment]
See #7532. `autocorrect` was explicitly disabled by CodeMirror. Manually enabling autocorrect with spellcheck seems to fix the issue.

Sorry for not fixing this originally! (I personally use the "clip"/auto-replace feature of my keyboard, which **does** seem to auto-replace with `autocorrect` explicitly disabled by CodeMirror.)

**Comment by korg91** [comment]
@personalizedrefrigerator Thanks a lot for the quick Christmas fix! When you say "manually enabling", do you mean in the code for the next release or can it be done manually in the stable release?

And could you explain what you mean by "clip"/auto-replace feature?

**Comment by personalizedrefrigerator** [comment]
> When you say "manually enabling", do you mean in the code for the next release or can it be done manually in the stable release?

I mean in the code for the next release. While it's [possible to manually enable through the developer tools](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Debugging.md#android--chrome), doing so requires connecting the Android device to a computer with the Chrome developer tools running for each new instance of the editor.

> And could you explain what you mean by "clip"/auto-replace feature?

The keyboard I'm using (Microsoft SwitfKey) has a "clip" feature (under clipboard settings) that allows manually specifying a list of replacements. For example, `gt` might be replaced with `>`.  Samsung keyboard has a similar feature. The SwiftKey keyboard automatically replaces text in the list of replacements just after the user finishes typing it with the replacement. A space might be needed after the text for the automatic replacement to happen. This feature still seems to work if `autocorrect` is set to `false` by CodeMirror.
