### ISSUE TITLE
(Beta editor) Text cursor keeps jumping to bottom of note

### ISSUE THREAD

**Issue by da2x** [laurent22/joplin#6179]
## Environment

Joplin version: 2.6.8
Platform: Android
OS specifics: 12 (One UI 4) 

## Steps to reproduce

1. Enable beta editor
2. Write a long note. Needs to scroll off the screen. Multiple paragraphs. No markdown, just plain text.
3. Scroll up and click somewhere in the body of text. So, not top or bottom.
4. Wait oe type something. Maybe paste.

## Describe what you expected to happen
The text cursor should remain in place.

## Actual behavior:
The cursor jumps to the bottom of the note. If I scroll back up and place it where I want it, it'll jump down to the bottom again without me doing anything. Only happens with long notes.

Sometimes, the editor scrolls to the bottom without moving the cursor there. Every letter I type will trigger it to scroll up again, and then it'll jump to the bottom again.

## Logfile
N/A

**Comment by da2x** [comment]
This is onlg happens with the Samsung Keyboard. Switching to Google Keyboard makes the problem disappear. However, I'm leaving this open as the app is incompatibile with the default keyboard from the number one Android brand.

**Comment by personalizedrefrigerator** [comment]
Does something similar happen with the editor on [the library Joplin uses (CodeMirror's)](https://codemirror.net/6/) homepage? I'm interested in whether this problem stems from an issue with Joplin or an issue with CodeMirror (or maybe an issue with the version of CodeMirror we're using).

**Edit:** If so, consider [filing a bug report under the CodeMirror project as well](https://github.com/codemirror/codemirror.next/issues).

**Comment by da2x** [comment]
This is a manual reply saying this is still an issue.

**Comment by cochetti** [comment]
I dont have Joplin but its an IME problem between Samsung with Grammarly and other keyboards

This deacribes the behavior:
https://www.ctrl.blog/entry/ime-samsung-grammarly.html

I informed Samsung but not enough people have complained for them to recognize the issue yet
