### ISSUE TITLE
OneDrive android and pc

### ISSUE THREAD

**Issue by feboss** [laurent22/joplin#6181]
The onedrive sync seems broken. Sync upgrade the file in onedrive but the application is unable to load the new changed or new files.
So the upload work but not the download.
I changed to dropbox and everything works fine so it seems is a onedrive problem related

**Comment by cwebb77** [comment]
I had the same problem - just the other way around, it didn't update on dropbox, but works fine with onedrive

🤷

[https://github.com/laurent22/joplin/issues/6244#issue-1162512644](https://github.com/laurent22/joplin/issues/6244#issue-1162512644)
