### ISSUE TITLE
Segmentation fault on `require("sharp")`

### ISSUE THREAD

**Issue by JezerM** [laurent22/joplin#6182]
## Environment

Joplin version: 2.6.2
Platform: Terminal
OS specifics: Linux distribution

## Steps to reproduce

1. Run `npm install -g joplin`
2. Run `joplin`
2. See `Segmentation fault`

## Describe what you expected to happen

No `segmentation fault` when I run joplin.
## Logfile

The default log is this:

```
$ joplin
[1]    5035 segmentation fault  joplin
```

I did modify the code to see where it does happen (at `~/.npm-global/bin/joplin`):

<details><summary>Modified code</summary>
<p>

```javascript
const Revision = require('@joplin/lib/models/Revision').default;
const Logger = require('@joplin/lib/Logger').default;
console.log("After `require(\"Logger\")`");
const FsDriverNode = require('@joplin/lib/fs-driver-node').default;
console.log("After `require(\"FsDriverNode\")`");
const sharp = require('sharp');
console.log("After `require(\"sharp\")`");
const { shimInit } = require('@joplin/lib/shim-init-node.js');
const shim = require('@joplin/lib/shim').default;
```

</p>
</details>

```
$ joplin
After `require("Logger")`
After `require("FsDriverNode")`
[1]    5785 segmentation fault  joplin
```

**Comment by blumenschwein** [comment]
If you run `sudo joplin`, or first `ssh localhost` and then run `joplin` (without sudo), does it still crash?

**Comment by JezerM** [comment]
Yep, it did crash.

However, I managed to fix it~ Seems like I lost some libraries a few days ago, or something like that, so I just needed to install `libvips-devel` and recompile `sharp` with **node-gyp**. Now it works!
