### ISSUE TITLE
Cannot move notebook back to parent

### ISSUE THREAD

**Issue by ChrisHarries** [laurent22/joplin#6185]
## Environment

Joplin version: 2.6.10
Platform: MacOS
OS specifics: Big Sur

## Steps to reproduce

1. Create Notebook
2. Move notebook so it's a child of an existing notebook
3. attempt to move notebook back to the parent so it's not a child anymore. I cannot do it, and it's stuck as a child

## Describe what you expected to happen

I could move the notebook back to the parent and not a child of another notebook

**Comment by Daeraxa** [comment]
Not a bug. Drag folder to Notebooks header.
