### ISSUE TITLE
Joplin was completely jammed when I disconect from an external display

### ISSUE THREAD

**Issue by DingWB** [laurent22/joplin#6191]
I connected my laptop to external monitoring and move the Joplin to the external display and maximize the window when I was at my office, but when I back home, there is no external display, Joplin got completely jammed every time when I open my laptop at home, I have to force quit Joplin and restart it.

## Environment

Joplin version: Joplin 2.6.10 (prod, darwin), Revision: 98fba37
Platform: MacOS
OS specifics: MacBook Pro (13-inch, M1, 2020)

## Steps to reproduce

1. Connect your laptop to an external display
2. Move the Joplin window to the external display and maximize it.
3. Disconnect the external display (unplug the wire) and close the laptop (not shut down), open the laptop when back home.

**Comment by fvirdia** [comment]
A similar problem happens on Windows 10 21H2. Following exactly your steps, the window remains "stuck" in the external monitor. Restarting Joplin (or even the laptop) does not help in recovering the window, only plugging an external monitor works. 

Joplin version: 2.7.15
Platform: Windows
OS specifics: Windows 10 21H2 (OS build 19044.1586) on Thinkpad X1 Carbon 6th gen
