### ISSUE TITLE
Enter key does not trigger "OK" in dialog boxes

### ISSUE THREAD

**Issue by placoderm** [laurent22/joplin#6194]
## Environment

Joplin version: 2.7.12 prod win32
Platform: Windows 10

## Steps to reproduce

1. Create notebook 
2. type notebook name
3. type `Enter`

## Describe what you expected to happen
 Expect dialog box to close 

## What happens
Nothing

Thread on forum:
https://discourse.joplinapp.org/t/enter-doesnt-create-a-new-notebook/23824

## Other dialogs with the same behaviour:

    General > Text editor command > Path: and Arguments:
    Sync > Max concurrent connections
    Sync Wizard > Joplin Cloud select > Login, Password,
    Dropbox select > Step 2: Enter the code provided by Dropbox:
    Appearance > Editor font size, Editor font family, Editor monospace font family
    Plugins > Development plugins
    Note history > Keep note history for (days)
    Encryption > Manage master password >Current password, Enter new password

## Code for `OK`
https://github.com/laurent22/joplin/blob/8e87e64dea421be87607f8676175078f38d2b95d/packages/app-desktop/gui/DialogButtonRow.tsx#L52-L58

## Other
Discussion of related behaviour starts here: https://discourse.joplinapp.org/t/enter-doesnt-create-a-new-notebook/23824/11

**Comment by SanjaySinghRajpoot** [comment]
Hello, I am working on this issue. I found that the input field is missing `onKeyPress` function, which I added but it is still not working. The buttons are working fine. I will try few more methods to fix this issue. 

Thank You

**Comment by SanjaySinghRajpoot** [comment]
Hello, I have got the issue `e.keyCode` is returning 0 value for all keypress. I have changed it with `e.key === 'Enter'` for the input field, but there is one problem the `ok` and `cancel` buttons are imported from a different file. I am unable to call the `ok_button` function. One solution would be to implement `ok` and `close` in the dialogue file itself. OR if there is any other way around then please let me know.

Thank You

**Comment by rayrrr** [comment]
This whole class of functionality can be easily and cleanly handled by bringing in a very lightweight and powerful (and MIT licensed) dependency: Alpine.js. See https://alpinejs.dev/directives/on#keyboard-events

**Comment by NeerajGartia21** [comment]
Is this issue still there?

**Comment by kamalbuilds** [comment]
@laurent22  what are your views on using Alpine.js? Should we use it to implement the soln or should we not?

**Comment by laurent22** [comment]
What's your thoughts on this? Does it make sense to bring a framework just to handle the Enter key?

**Comment by laurent22** [comment]
Fixed in https://github.com/laurent22/joplin/commit/558e55090f12a90438bbe416619843826383a7c0

**Comment by kamalbuilds** [comment]
ok ok

**Comment by kamalbuilds** [comment]
Certainly not 🚫

I will see 👀  into this to provide a better solution !
