### ISSUE TITLE
jopinportable report TR/Dropper.Gen virus

### ISSUE THREAD

**Issue by changtianyu** [laurent22/joplin#6195]
![image](https://user-images.githubusercontent.com/8001045/155650559-fb6f4dab-eccb-4c0b-9be7-4a98aa594274.png)

**Comment by JackGruber** [comment]
This is a false positive of the virus scanner used!
![grafik](https://user-images.githubusercontent.com/24863925/155661132-87e62ed9-16f6-47f0-b50a-2ef5919382f4.png)
None of the virus scanners used there detect the portable version 2.7.13 as a virus


Which version of Joplin?
Which operating system?
Which virus scanner?

**Comment by changtianyu** [comment]
version 2.7.13， from the  ReadMe index page link; win 7; 360 antiVirus.
