### ISSUE TITLE
joplin automatically adding soft breaks

### ISSUE THREAD

**Issue by samfrixb** [laurent22/joplin#6199]
summary - 
when i hit enter, i want to go to the next line, with no space in between the lines. but it is adding a paragraph style break between them. this started after i turned on soft breaks in settings, then this started. but when i turned off the setting, it did not return to normal. happens in all documents. 

## Environment

Joplin version: 2.6.10
Platform:  windows
OS specifics:  10

## Steps to reproduce

1. turn on soft breaks
2. see that pressing return now leaves a gap
3. turn off soft breaks. still leaves a gap

## Describe what you expected to happen
be able to press enter and have no gap between lines

## Logfile
[log.txt](https://github.com/laurent22/joplin/files/8143373/log.txt)

**Comment by Daeraxa** [comment]
If you are using the richtext editor you need to press shift + enter to insert a `<br>` between lines rather than separate `<p>` elements.

**Comment by ghosttie** [comment]
This is still an issue

**Comment by catalin-catrina** [comment]
This is still an issue. Joplin automatically separates my lines with linebreaks by itself without me doing anything. I didn´t change any settings and if this is the default behaviour, it really needs to be changed. I don´t need Joplin for anything fancy, only for taking notes, and I simply can´t do that properly.
