### ISSUE TITLE
Revisions may contain corrupt data

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#6209]
Follow up on #5531.

A new line character 0D can sometimes occur inside the revision patch data, so some filtering should be put in place to prevent this data to break the revision system.

Sample data:

```
{"new":{"id":"b1a2ec6d85f945ca8039685549ac5055","parent_id":"093f0fcaca434b399bf02a3f9821c46f","latitude":"0.00000000","longitude":"0.00000000","altitude":"0.0000","author":"abcdefg@gmail.com","source_url":"https://www.google.ab/search?tbs=li:1&q=transfer+from+lumia+to+android&gws_rd=cr&ei=oz8rWOn8EYKWsAHp1ISgDw#tbs=li:1&q=android+for+dummies
","is_todo":0,"todo_due":0,"todo_completed":0,"source":"evernote.desktop.win","source_application":"net.cozic.joplin-desktop","application_data":"","order":0,"markup_language":1},"deleted":[]}
```

https://github.com/laurent22/joplin/issues/5531#issuecomment-1053587128

**Comment by Perkolator** [comment]
I was unable to test this with the new 2.7.15 version. I noticed that before the update, Joplin did not show the older revisions anymore (the problematic revision seems to have been removed somehow). I took a backup of the current database.sqlite file, disconnect internet (to stop dropbox sync) and copied older database.sqlite file from a backup to the Joplin config folder. Still, couldn't see the older revisions, dunno why.
