### ISSUE TITLE
Leading slashes in notebook title get stripped

### ISSUE THREAD

**Issue by marph91** [laurent22/joplin#6213]
## Environment

Joplin version: 2.7.13
Platform: Linux
OS specifics: Ubuntu 20.04

## Steps to reproduce

Simply create a new notebook with a leading slash. For example `/foo` will get `foo`, while `foo/bar` stays `foo/bar`. Same applies to backslashes. Other special chars (i. e. `!"#$%&'()*+,-.:;<=>?@[]^_`{|}~`) were fine.

## Describe what you expected to happen

The notebook should get the same title as written in the "Create notebook" dialog.

This behaviour doesn't affect my workflow. I only discovered it when testing. However, I wanted to document it, in case someone else stumbles upon it.

**Comment by laurent22** [comment]
Slashes and backslashes on the left are removed, although I forgot why exactly (maybe something to do with file paths):

https://github.com/laurent22/joplin/blob/dc991d4c0fca94b3a26f1345a38f0fe3ef9c39e4/packages/lib/models/Folder.ts#L723

So probably we're going to leave it that way, unless it causes a big issue.
