### ISSUE TITLE
Improving Readme

### ISSUE THREAD

**Issue by yashpalgoyal1304** [laurent22/joplin#6217]
The repo's readme.md file has some huge scope of cleanup to improve readability and maintainability

**Comment by mirchandani-mohnish** [comment]
As far as I know, the entire documentation is going to be replaced in the GSOC this year (although that depends on someone taking up that particular project). I think that the entire current documentation will be moved to a neater and cleaner website. Do correct me if I am wrong.

**Comment by yashpalgoyal1304** [comment]
ohkay. well, i would have liked to take that project, but if the requirement was to be in .md :wink: - i am pretty sure it would be competitive enough to the supposed website alternate (or might be wrong as well)

dont have any xp in website making

but anyways, closing the issue then, thanks for the info
