### ISSUE TITLE
Alarm not working

### ISSUE THREAD

**Issue by navyakrishna123** [laurent22/joplin#6235]
## Environment

Joplin version: 2.7.2
Platform: One Plus Nord
OS specifics: Android  10

## Steps to reproduce

1. Create task
2. Set alarm (Set date & time)
3. Wait till alarm time
4. Nothing happens

## Describe what you expected to happen

Expected alarm to ring.

**Comment by denaszune** [comment]
I also have this same exact problem.

Joplin version - 2.10.8
Pixel 7 Pro - Android 13
