### ISSUE TITLE
Text in the editor pane shows through plugin panes

### ISSUE THREAD

**Issue by TDMedina** [laurent22/joplin#6242]
## Environment

Joplin version: 2.6.10 (prod, Linux)
Platform: Linux
OS specifics: Ubuntu 20.04.3 LTS

## Steps to reproduce

1. Installed [Outline](https://github.com/laurent22/joplin/issues/new?assignees=&labels=bug&template=bug_report.md&title=#) plugin (or other pane-based plugin, like backlinks or Kanban)
2. Changed application layout so Outline pane is below editor pane, then exited change layout.
![image](https://user-images.githubusercontent.com/32261345/157047040-2c304c54-64ad-4ade-a991-699484c2bbfb.png)
3. Clicked and dragged to increase height of Outline pane
![image](https://user-images.githubusercontent.com/32261345/157047252-300b74b2-837c-46be-9dc4-63b1c08e165b.png)
5. When the editor is in editor or split view mode, the Outline pane does not cover the editor text
    - the plugin pane seems to be transparent, so text in the editor and text in the other pane are both visible
    - things like the dividing bar to click and drag pane height are no longer selectable "beneath" the editor
    - Rendered markdown in split view or in view mode both show expected behavior and are "covered" by the plugin pane

## Describe what you expected to happen
The plugin pane should cover the editor pane, as it does when in view mode:
![image](https://user-images.githubusercontent.com/32261345/157047492-e79c6323-4b7f-46cb-8b94-0329eb1e7618.png)

**Comment by asrient** [comment]
This looks like an issue of unset `z-index` of plugin iframe, I was able to fix it by setting `z-index: 2;`. But since I'm planning to participate in Gsoc and I already have a PR open so according to the guidelines I think I cannot open another PR right now.
