### ISSUE TITLE
Android Dropbox sync not working

### ISSUE THREAD

**Issue by cwebb77** [laurent22/joplin#6244]
## Environment

Joplin version: 2,7.2 (also tried 2.5.5 with same results)
Platform: Android
OS specifics: Android 11

## Steps to reproduce

1. install app
2. use Dropbox sync
3. notes get synced and decrypted
4. add or change note on Windows app
5. changes do not how up in Android
6. Android app stalls at syncing, I can only "cancel"

I am using the current windows version, I also tried downgrading to 2.5.5 on Android but got the same result

## Describe what you expected to happen
change note in Windows app
see changes in Android

## Logfile
[syncReport-1646734281326.txt](https://github.com/laurent22/joplin/files/8205487/syncReport-1646734281326.txt)

**Comment by Ankit3002** [comment]
Hi @cwebb77  I followed the steps that you have mentioned  and I don't see any issue in synchronization. Could you please elaborate your issue more

**Comment by marcorighi** [comment]
Hi there, I have the same issue. The sync seems going in deadlock. The icon of the sync remains at the bottom of the screen and the sync never ends. It is a bug that began with some upgrades ago. I still have the bug with Android  

DEVICE
Model: Redmi Note 9S (curtana_eea)
Manufacturer: Xiaomi
Java VM: ART 2.1.0
OS Version: R (11)
SDK: 30

and Joplin

Joplin 2.7.2
Database v41
FTS active 1

Sometimes Joplin syncs with the option (excuse me I am translating from another language) "max number of concurrent connection" = 1

Please, resolve the bug.

I am syncing notes using Dropbox. Should I change?
Write here or send me an email to have more information. I am willing to help to resolve the bug. Please ask me if you need more information.

**Comment by alexanderFell** [comment]
In my experience, it helped to delete any old lock files in the `./locks` directory on Dropbox. After deleting the files, the sync for my Android device started working again.

**Comment by marcorighi** [comment]
Is it safe?

> In my experience, it helped to delete any old lock files in the `./locks` directory on Dropbox. After deleting the files, the sync for my Android device started working again.

**Comment by alexanderFell** [comment]
I cannot say anything, since I didn't go through the source code. In my case, I don't have any critical data so I don't mind using the latest changes, if any. When I delete the file (it happens once every few months or so), I make sure that no device is currently synchronizing.

**Comment by marcorighi** [comment]
It seems to me that works... until next "starvation deadlock"

**Comment by gfdsa** [comment]
yep, locks are locking, removing locks is unlocking
just check the file's date, mine was from weeks ago when I've tried to sync and forgot about it

**Comment by marcorighi** [comment]
Hi, I have completely resolved the problem moving my data on owncloud and using webdav. It seems that Dropbox is the source of the problems.
