### ISSUE TITLE
Clipper unable to pull and store PDFs

### ISSUE THREAD

**Issue by RC-minn** [laurent22/joplin#6247]
I download and store a lot of PDFs that are technical papers. There are sites that have PDFs that are freely available and it would be great if the Joplin clipper could extract that PDF from the page and store it as well. Evernote was able to do this.

As far as I know - this is for all versions of Joplin.

**Comment by asrient** [comment]
I wanna work on it. @RC-minn can you provide a few sample webpages with those type of pdfs? I want to see if pdfs are there as links or as embeds.

**Comment by RC-minn** [comment]
Here are a couple examples. THe first one is probably a bit tougher - just a SWAG - as normally I would have to download the file, create a note, and then drag the PDF into the note and label it. 

https://www.researchgate.net/publication/343185267_Experimental_Study_on_the_Prospective_Use_of_PV_Panels_for_Chest_Freezer_in_Hot_Climate_Regions

Here is a pretty standard situation. 

http://www.doiserbia.nb.rs/img/doi/1450-5339/2008/1450-53390801039K.pdf

Hope that  helps. THanks!

Randy

**Comment by asrient** [comment]
Thanks for the links. On it!

**Comment by asrient** [comment]
### Some notes upon investigation

- The [researchgate page](https://www.researchgate.net/publication/343185267_Experimental_Study_on_the_Prospective_Use_of_PV_Panels_for_Chest_Freezer_in_Hot_Climate_Regions) linked above uses a non-standard pdf library to render pdfs to html, which the joplin clipper tries its best to parse (some parts of the rendered pdf were ignored but most of it was copied to joplin when I tried).
- Links to [raw .pdf files](http://www.doiserbia.nb.rs/img/doi/1450-5339/2008/1450-53390801039K.pdf) don't work with the clipper, something that can we worked on.
- Web pages with [embedded pdfs](https://pdfobject.com/) with `<embed/>` tags don't work for clipper as well, this can be fixed as well.

### Conclusion

I don't think the first point (if webpages uses 3rd party libraries to embed) can be worked on. But the next 2 points can be worked on. Hoping for comments from moderators and @RC-minn.

### Measurable goal

- Make clipper accept and honour `<embed/>` tags with `type="application/pdf"` attribute.
- When the `Content-Type` of the page is `application/pdf`, just export the pdf.

**Comment by RC-minn** [comment]
I'm not surprised by the inability to pull the PDF from ResearchGate, but having success with the last two situations would be great. Many thanks!

**Comment by laurent22** [comment]
I agree. I guess option 2 is the most common case so probably higher priority. Option 3 would be nice too though.

And indeed option 1 is a special case, so for now we don't need to consider it.
