### ISSUE TITLE
iOS webDAV synchronization error

### ISSUE THREAD

**Issue by Wartijn** [laurent22/joplin#6249]
## Environment

Joplin version:  12.7.1
Platform:  iOS
OS specifics:  iOS 15.3

Synchonisation settings:
- target: WebDAV
- URL:  `https://<subdomain>.<domain>.com/remote.php/webdav/Joplin`
- username: <username>
- password: <password>

## Steps to reproduce

1. Click `Check synchronization settings` 
    a.  This is successful 
3. Add a note on pc
4. Add a note in the iOS app
5. Click `Synchronize`

## Result
1. the note from iOS is uploaded
2. the note from pc is **not** downloaded on iOS
3. The iOS app gives the error: `Error: PROPFIND /: Unknown error 2 (401): 401 Unauthorized`

## Describe what you expected to happen
The note from pc is downloaded to iOS and there is no error

It seems to be the same bug as [this one in the formus](https://discourse.joplinapp.org/t/webdav-sync-one-way-on-ios-error-propfind-unknown-error-2-401-401-unauthorized/9391)

### What I think is happening
I logged the https requests that Joplin makes and noticed that a request is being made to `https://<subdomain>.<domain>.com/remote.php/webdav/Joplin//` when synchronizing, so with two trailing slashes. This request is redirected to `https://<subdomain>.<domain>.com/remote.php/webdav/Joplin/`. My guess is that the authorization headers are missing in this redirected request, so it fails. 

## Logfile

![Log screenshot 1](https://user-images.githubusercontent.com/10060747/157501073-558a8907-55d2-4dac-a290-0baca211da3c.jpeg)
![Log screenshot 2](https://user-images.githubusercontent.com/10060747/157501081-49f57b0d-22c3-4d48-94e9-f8a303eebe69.jpeg)

**Comment by JackGruber** [comment]
The error `401` means the user is not authorized to access the Files/Folder you have specified.
Please check username/password and the permissions in Nextcloud.

**Comment by Wartijn** [comment]
There are a few reasons why I'm convinced that's not what's going wrong:

- If I enter a wrong target, username or password and click `Check synchronization settings` it gives me a 401 when performing that check. This is not the case for me, the check works fine, I only get the 401 when synchronizing 
- Downloading notes from desktop works fine with the the same settings. To be extra sure, I installed Joplin on an Android phone and it works fine with those settings. So that should rule out wrong file permissions.
-  If any of these settings aren't correct, I assume I shouldn't be able to upload notes. But uploading notes from iOS works fine, I just can't download them.

**Comment by mke21** [comment]
That one is closed but not fixed?

**Comment by mke21** [comment]
Please open this again as this is still a bug
