### ISSUE TITLE
Save web pages with Clipper as HTML

### ISSUE THREAD

**Issue by mrtargaryen** [laurent22/joplin#625]
### Operating system

- macOS
- iOS

### Application

- Desktop
- Mobile

Is there any chance to have the option to save webpages with the clipper other than in just markdown. I wouldn't mind being able to save complete wepages. Is this a possibility?

**Comment by foxmask** [comment]
If i'm not wrong, I don't think so. To avoid injection from webpage to joplin.

**Comment by mrtargaryen** [comment]
Ahh, ok. That makes sense. I have say, however, that so far Joplin is the best Open Source Evernote alternative. I synced it with Dropbox, and enabled encryption. I checked all the notes and attachments in Dropbox and they're certainly encrypted. And Joplin on iOS has synced well.

**Comment by laurent22** [comment]
Yes at the moment HTML is disabled for security reason. If there's a way to re-enable it in a safe way, maybe it will be possible to have an HTML-mode in the Web Clipper.

**Comment by mrtargaryen** [comment]
@laurent22 Thanks for the reply. Let's hope there will be a safe way one day :-) ... Geat App nevertheless.

**Comment by foxmask** [comment]
Done by #1742
