### ISSUE TITLE
Question: Why are you not building/packaging the linux server files with a release?

### ISSUE THREAD

**Issue by Bockiii** [laurent22/joplin#6251]
Greetings,

this question might lead to a PR from me, but before I invest time: I can see that you provide packages for windows/mac and appimage files, but no packaged server files. Is there a reason for that other than "we didnt do it yet"?

Using pkg, you could package your created server dist files into a single executable, which would help server runners and especially the docker container.

Right now, the docker container is larger than 1gb. Thats insane. Using prebuild executables, I guestimate that you can bring it down to maybe 50mb.

And adding a pkg config and CI should not be that time intesive, since you are already building the server for the docker container.

I'm a docker guy, not a node guy, so if I tackle this, it would require a bit of time investment on my end, thats why i'm asking.

Greetings

**Comment by jivandabeast** [comment]
Interested to see where this goes, trying to see whats eating up my docker image and Joplin is taking up a good chunk of it.

**Comment by Bockiii** [comment]
Most likely nowhere since there have been 30-40 other issues after this that got handled/answered and this is still without any reaction :)

**Comment by Bockiii** [comment]
The cause is not adressed yet, also, there has not been any member involvement so far.

I wouldnt close it just because...

**Comment by Daeraxa** [comment]
The github issues log is for bugs/regressions only, not feature requests/enhancements which should be raised on the forum.
