### ISSUE TITLE
Joplin for Desktop display problem

### ISSUE THREAD

**Issue by cayenne17** [laurent22/joplin#6252]
Hello,

The text is not stuck on the left, it happens on all notes

![image](https://user-images.githubusercontent.com/47927025/157729177-2f6bfc4d-9928-4f18-995c-ce7d9aaab9d0.png)

## Environment

Joplin version: 2.7.13
Platform: Desktop
OS specifics: Windows10 build 19043

## Steps to reproduce

you have to "Toggle the editor".

## Describe what you expected to happen

That the text is stuck on the left

**Comment by Daeraxa** [comment]
Set Tools > Options > Appearance > Editor maximum width = 0

**Comment by cayenne17** [comment]
> Set Tools > Options > Appearance > Editor maximum width = 0

Thank you, the problem is solved
