### ISSUE TITLE
Link to location inside note not working in windows

### ISSUE THREAD

**Issue by lumogas** [laurent22/joplin#6255]
Hello, I create links to separate locations inside lengthy notes using anchors. On the Windows version, the links are ignored (clicking on them does nothing), but they work on Android and iOS.

## Environment

Joplin 2.7.13 (prod, win32)

Client ID: f36898bba6e94718bdaac85f1cbb3862
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 5b5165d

Windows

## Steps to reproduce

1. Create an anchor within a long note, for example `<a id="bottom"></a>`
2. Link to that anchor: for example `[Go to bottom](:/NOTE_PATH_HERE#bottom)`
3. Works in Android and iOS, nothing happens on Windows

## Describe what you expected to happen

I was expecting to be able to link within a note.

**Comment by SiddheshKukade** [comment]
Please add a video at least can't understand what you're trying to say.

**Comment by lumogas** [comment]
Hello, thanks for the reply.

A "link" is a clickable item that leads you to another location. An "anchor" is the tag in html (readable by
markdown) that provides a target to a link.
It is possible in Joplin to link between notes: the syntax used is `(:/NOTE_PATH)`. 
"Link between notes", means "click on one note, to take you to another note".
You can also link to targets within a note.
That means "click on section of a note, to go to another section of a note", as described here:

https://discourse.joplinapp.org/t/jumping-to-a-section-of-a-note-you-linked/2267/19

...however, this is not working in Windows. It works in Android and iOS, though. Unless
there is a setting in Windows that needs to be enabled?

**Comment by dkp** [comment]
Links between notes broken on Mac Catalina: 
Joplin for Desktop

Copyright © 2016-2022 Laurent Cozic
Joplin 2.7.15 (prod, darwin)

Client ID: 1d6cbc41f82d42ea9c401877a8d89842
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 8352e23

---

Steps to reproduce:
Right-click note=> choose "Copy Markdown Link"
Paste this markdown link into another note.
It looks like this: [afni display colors in gui](:/ed75c4f6d4e04f03afe9bf21f6c366c2)

Clicking the link does not go anywhere.  
Right-clicking the link reveals a `cut / copy /paste` menu with no `Open` option.

This used to work flawlessly but now is broken.

**Comment by dkp** [comment]
It seems to be working...thank you.  I'm not sure what changed--maybe me? : p
The issue can be closed...I don't see a close button.

**Comment by lumogas** [comment]
Hello,
No solutions? Links within a note are useful, especially for very long ones. "Go back to top", or "Go to bottom", for example.
Any idea why they don't work on the windows version of Joplin?
Links between notes work fine.

**Comment by dkp** [comment]
Thanks.  I've moved on.

**Comment by lumogas** [comment]
Hello, it would be extremely useful to have links within notes work on Windows. Especially on very long ones. Our when using a table of contents, for example.

**Comment by lumogas** [comment]
Hello, it would still be useful to link to locations inside the same note.
