### ISSUE TITLE
Error in setting Nextcloud WebDAV sync

### ISSUE THREAD

**Issue by maptile** [laurent22/joplin#6258]
## Environment

Joplin version: 12.7.1
Platform: iOS
OS specifics: 15.3.1
Nextcloud: 22.2.5

## Steps to reproduce

1. Open Configuration
2. Select Synchronization target: Nextcloud
3. Nextcloud WebDAV URL: http://cloud.xxx.net/remote.php/dav/files/USERNAME/files/notes (
4. Nextcloud username and password: USERNAME/********
5. Click "Check synchronisation configuration" button, receive error immediately which says: "Error. Please check  that URL, username, password, etc. are correct and that the sync target is accessible. The reported error was: Network request failed"
6. Also tried http://cloud.xxx.net/remote.php/dav/files/USERNAME/ and http://cloud.xxx.net/remote.php/dav/files/USERNAME/files and with or without the ending /
7. Also tried WebDAV with no luck

## Describe what you expected to happen

Check passed without error.

## Logfile

![image](https://user-images.githubusercontent.com/28569363/157894160-7fac7a84-d739-4a14-be65-c05f75f2e734.png)

![image](https://user-images.githubusercontent.com/28569363/157894192-87f401fc-6eb7-4aca-bf4e-026a0202bd94.png)

**Comment by laurent22** [comment]
You need to use https to avoid this error

**Comment by maptile** [comment]
Can add a checkbox to allow user use http? Which will be great suitable for the users in home LAN. Thanks

**Comment by banjuer** [comment]
> You need to use https to avoid this error
HTTP can be used in other clients. So can there be a setting option in **IOS** ? THANKS

**Comment by maptile** [comment]
Finally, I used a self signed SSL certificate to avoid this problem.
