### ISSUE TITLE
Search fails for word "Wöhler"

### ISSUE THREAD

**Issue by a-ma72** [laurent22/joplin#6259]
In my notebooks there are multiple occurrences of "Wöhler", "Wöhlerlinie", "Wöhlerdiagramm" and so on (body text), but when searching for "öhler" or "/öhler" (simple search) I get no hits. When searching for "/hler" or "/ö" I get the desired matches, but not for the part "/öhler".
Did I get it wrong or is there potentially a bug?

## Environment

Joplin version: 2.7.14
Platform: Windows 10
OS specifics:

**Comment by Abhinandan-Singh** [comment]
Tried it but it worked. Can you elaborate the bug generating process.

**Comment by a-ma72** [comment]
![2022-03-13 17_28_06-Clipboard](https://user-images.githubusercontent.com/11562654/158069321-c187c723-7f18-4a84-830f-757c8d252c1d.png)
![2022-03-13 17_28_12-Window](https://user-images.githubusercontent.com/11562654/158069324-0f7020cf-ec63-4b1b-b9eb-3c2e58c75e92.png)

**Comment by a-ma72** [comment]
![2022-03-13 17_30_36-Window](https://user-images.githubusercontent.com/11562654/158069424-efccbd41-76d7-4b17-a01e-29a518c292ed.png)

![2022-03-13 17_28_06-Clipboard](https://user-images.githubusercontent.com/11562654/158069433-72f3c954-2834-438d-9e02-2b20f77cd760.png)

**Comment by marph91** [comment]
I can reproduce. It might be a limitation of the search algorithm/engine.
