### ISSUE TITLE
Editor behaviour when entering lists

### ISSUE THREAD

**Issue by jammon** [laurent22/joplin#626]
### Operating system
- macOS

### Application
- Desktop

What I see:
- When entering a list by starting the line with e.g. `- `, hitting "return" starts a new line and inserts `- ` at the beginning. 
- Hitting "return" once again places the cursor on the next line without inserting anything. 
- Any text on this line (in the editor) has the color of the text in lists, suggesting that it belongs to the list, but it doesn't.

What I'd like to have:
- Hitting "return" on a line with no text but the `- ` at the beginning of the line deletes the `- ` and inserts a new line. (This is the behaviour of Sublime Text and it seems to me a quite natural way of ending a list.)

**Comment by tessus** [comment]
Since this issue's title is very generic, I'd like to also mention a few things I've noticed.
(I have no intention of hijacking the thread though.)

The following is true for lists and checkboxes.

- items are only continued on the first level
- A `tab` after the `-` does not indent the item to the next level (however, a `shift-tab` does unindent by one level each)

**Comment by laurent22** [comment]
I've ended up fixing this one: "items are only continued on the first level"

**Comment by tessus** [comment]
Ok, now I feel like I have hijacked the ticket. Any chance you could re-open it and we use it as a meta issue for list enhancements?

- [x] items are only continued on the first level
- [ ] Hitting "return" on a line with no text but the - at the beginning of the line deletes the - and inserts a new line. 
- [ ] A `tab` after the `-` does not indent the item to the next level (however, a `shift-tab` does unindent by one level each)

**Comment by laurent22** [comment]
I'm not planning to implement these two features at this point as I think the way it works at the moment is acceptable (some text editors might do it differently, but others do the same, so there's not just one correct way to do it).

**Comment by jammon** [comment]
I think you are right. It's an ace problem. I have to raise the issue there.
