### ISSUE TITLE
Hide message "One or more master keys need a password" when master key is missing

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#6264]
https://discourse.joplinapp.org/t/error-one-or-more-master-keys-need-a-password/24362

**Comment by 19shivii** [comment]
Hi I want to work on this.Please assign me

**Comment by JackGruber** [comment]
We don't assign issues!

**Comment by Abhinav-CHD** [comment]
Hey can anyone tell me how can I reproduce this issue?

**Comment by laurent22** [comment]
Hmm, can't replicate this anymore. It hides the banner when the key is disabled, as expected.
