### ISSUE TITLE
Filter keywords casesensetive

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#6266]
If a keyword is capitalized, the filter no longer works. 
On mobile devices, the keyboard setting `Automatically capitalize at the beginning of the sentence` causes the words at the beginning of a sentence to be capitalized, so you always have to switch to lowercase first when you want to set a filter.

![grafik](https://user-images.githubusercontent.com/24863925/158056244-4a0dbbf5-1133-4261-8e49-711cb66e6222.png)

Discourse: [Automatic capitalization of search string hides keywords](https://discourse.joplinapp.org/t/automatic-capitalization-of-search-string-hides-keywords/24281)

## Environment

Joplin 2.7.12 (prod, win32)

Client ID: 0e33609c84614b3092102ff00887b36e
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 4906087
OS specifics: Windows 10

## Steps to reproduce

1.  Create a note with the tag `TagA`
2. Use the following search query `Tag:TagA` => No search results
3. Use the following search query `tag:TagA` => Search results

## Describe what you expected to happen

Notes with the tag `TagA` should be found anyway

**Comment by laurent22** [comment]
Hmm, yes I'm not sure why it's that way. It's true it's an issue here, but there could be a reason we've been strict on case.

**Comment by JackGruber** [comment]
Currently you can find the note content `Tag:SomeTag` with the search `Tag:SomeTag`, but only because the filter validation is case sensitive, but the search term is already made lower case by `makeTerm`.
This behavior should only be the case since the commit 8cbcb78 / #5103.

**Comment by laurent22** [comment]
Right, I remember now, thanks for clarifying. In that case it indeed makes sense to make it case insensitive.

**Comment by 19shivii** [comment]
I want to on this,  Please assign me

**Comment by Daeraxa** [comment]
We do not assign issues, just state if you are planning to work on it

**Comment by 19shivii** [comment]
Yes Daeraxa, I have started working on this.
