### ISSUE TITLE
Broken Link - ideas.md

### ISSUE THREAD

**Issue by anwersayeed** [laurent22/joplin#6268]
The newly created markdown  ` joplin/readme/gsoc2022/ideas.md` contains a broken link. On clicking the `General Summer of Code Introduction` link, gives a 404 File not found error.
![1](https://user-images.githubusercontent.com/57287988/158059443-2817feec-862c-4f17-b686-cf4e4643b42e.jpg)

The broken URL - https://joplinapp.org/gsoc2022/index/
![2](https://user-images.githubusercontent.com/57287988/158059482-43063411-f77f-4d0f-87b6-4ddc3485549a.jpg)

## Steps to reproduce

1.  Go to https://github.com/laurent22/joplin/blob/dev/readme/gsoc2022/ideas.md
2.  Click on `General Summer of Code introduction`.
3. You can see that the page is directed to 404 File not found error.

**Comment by anwersayeed** [comment]
I want to fix this error, please assign this to me.

**Comment by roman-r-m** [comment]
We don't assign issues - just go ahead and submit a PR.
In fact for a minor issue like this there was no need to even create an issue.

**Comment by anwersayeed** [comment]
Thanks, @roman-r-m, I have created the required pull request.
https://github.com/laurent22/joplin/pull/6270

**Comment by laurent22** [comment]
Fixed in https://github.com/laurent22/joplin/pull/6269
