### ISSUE TITLE
Can't upload Pictures anymore - Files cannot be created in non-existent collections

### ISSUE THREAD

**Issue by AdrianBadertscher** [laurent22/joplin#6273]
Hi there,

I receive the following Error message, if there is somewhere a new Picture in a note:

`Created remote items: 1.
Completed: 14.03.2022 09:50 (24s)
Last error: Error: PUT .resource/339384c895e8427e9c4020339937166d: Files cannot be created in non-existent collections (Exception Sabre\DAV\Exception\Conflict) (409): <?xml version="1.0" encoding="utf-8"?> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"> <s:exception>Sabre\DAV\Exception\Conflict</s:exception> <s:message>Files cannot be created in non-existent collections</s:message> </d:error>`

I can't synchronize after that and have to remove the file "339384c895e8427e9c4020339937166d" in this case.

The used Version is:
Joplin 2.7.14 (prod, win32)

Client ID: 47db53fee7044b8b810e689d22bc5688
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 75cc9d7

But I receive the same Error on my mobile:
Joplin 2.7.2 on Android 11

## Steps to reproduce

1.  Insert a Picture in a note
2.  Click 'synchronize'
3.  Get the Error above

## Describe what you expected to happen
Only that the sync works like before this :)

**Comment by AdrianBadertscher** [comment]
Hi Laurent22,
I'm not sure - now I've copied the whole .resource and merged them to the new location.
But the Issue still appears. :(

Is there a possability to restore a safe state of my note repo? There are over 1'500 notes, and I will not loose my Notebook.
I use the new location since 3weeks, so there are many new notes on it.

Thank you for your answer.
Best regards,
Adrian

**Comment by AdrianBadertscher** [comment]
For answering your question directly:
Yes I've moved from a Nextcloud Instance to a Cloud Provider (infomaniak).

**Comment by laurent22** [comment]
On Nextcloud there's a . resource folder, which may be hidden, and you need to copy that folder too to Infomaniak

**Comment by AdrianBadertscher** [comment]
Thank you for your answer. I've copied the .resource folder to Infomaniak - and the Problem is not pre existing images, the problem is with new created images :( and then syncing.

**Comment by AdrianBadertscher** [comment]
Ok - I've solved the Issue.
The problem was, that the infomaniak nextcloud client not syncing .ressource folders. Because of the beginning '.' - the trick was, to upload the ressource folder, without '.' and rename it online.

The downside is, that there is no 'automatic' backup with the nextcloudclient of infomaniak.

But joplin makes a local copy of the content of the folder '.ressource' -> is this correct? I've seen, that in this folder, the ressources have the name from the source - and online the name is GUID-ized, correct?

So is there a possability to use the local copy of the joplin-folder - for a new instance of joplin? If there is by some reason a problem with the actual online version?

Or is the only way to make manual backups from time to time?

**Comment by JackGruber** [comment]
You can use the [Simple Backup](https://github.com/JackGruber/joplin-plugin-backup) plugin for automatic backups.

**Comment by AdrianBadertscher** [comment]
Thank you very much!
Joplin is greate!
