### ISSUE TITLE
Tag list truncated to screen width at the bottom bar

### ISSUE THREAD

**Issue by prajwalkulkarni** [laurent22/joplin#6276]
## Environment

Joplin version: 2.7.13
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1.  Add a large number of tags (at least 25) to an existing note or a new note.
2.  Observe the bottom bar to check all the tags associated with a note.
3.  You'll be able to see the tags only up to your screen width, beyond which the remaining tags are not visible. Addtionally, you'll not be able to add new tags to the note, because the `Click to add tags...` button is overflowing beyond the screen width.

## Describe what you expected to happen
Ideally, it'd to good to have a horizontal scroll, so that the user is able to look through all the tags and also add new tags if needed.

## Logfile
![issue (1)](https://user-images.githubusercontent.com/22348265/158108878-c90a36a3-a077-405a-b263-10df25d61206.PNG)

**Comment by laurent22** [comment]
Closed per rule 1 https://joplinapp.org/gsoc2022/pull_request_guidelines/

**Comment by prajwalkulkarni** [comment]
Hello Laurent. I understand that this issue was opened after GSoC. However, I think this addresses an important bug that hinders the UX. Is there any chance by which this issue can be considered outside of GSoC? Thanks.

**Comment by laurent22** [comment]
No, sorry, no exception.
