### ISSUE TITLE
display inconsistency when combining checkboxes and item lists

### ISSUE THREAD

**Issue by Estamin** [laurent22/joplin#6284]
## Environment

Joplin version: 2.7.14 (prod, win32)
Platform: desktop
OS specifics: Windows 10 pro

## Steps to reproduce

1. create a note combining checkboxes and item lists, or copy-paste the following text :

```
- [ ] checkbox 1
- [ ] checkbox 2
- List item A
- List item B
- [ ] checkbox 3
```

2. toogle editors and note the difference between splitview (editor/rich text) and WYSWYG, in the way that the note appears

splitview :
![image](https://user-images.githubusercontent.com/66172934/158432968-ef634ce1-2a65-4be0-a8e5-9abf0093f2d2.png)

WYSWYG :
![image](https://user-images.githubusercontent.com/66172934/158433082-fa386e5f-9213-4c49-9e42-7a73d774620b.png)

## Describe what you expected to happen

I expected the display result of my notes to be consistent when toggling editors. In the exemple above, the good result is given by the splitview editor.

## Logfile

No logfile needed here I guess, but let me know if you need one.

**Comment by Daeraxa** [comment]
Its a known limitation of the editor:

https://joplinapp.org/rich_text_editor/

> All items in a list must be of the same type, so for example all checkboxes, or all bullet points. If you require two different types, you should create two different lists separated by a horizontal rule or similar.

**Comment by Estamin** [comment]
Ok, thank you!
