### ISSUE TITLE
Incorrect rendering of strikethrough in rendered View when line wraps.

### ISSUE THREAD

**Issue by ZachHansonAmount** [laurent22/joplin#6288]
When editing in split view the rendered view does not display strikethrough when ~~the line wraps around~~ there is a space between the last non-whitespace character and the `~~`. The live-render on the edit side of the pane does still show it though which seems odd to me. 

For clarity the left-hand side is the editor pane, the right-hand side is the preview.
![image](https://user-images.githubusercontent.com/80707359/158674650-d51f709b-19b4-4391-927e-f0770bd506f3.png)

## Environment

Joplin version: 2.7.14 Revision: 75cc9d7
Platform: macOS
OS specifics: macOS 12.2.1 ARM

## Steps to reproduce

1. Use Split Editor View
2. Strike out text with `~~` leaving a space between the last character and the first `~`. ie `~~this text should be struck out ~~`

## Describe what you expected to happen

Text should be rendered with strikethrough in the preview pane.

## Logfile
[log_censored.txt](https://github.com/laurent22/joplin/files/8269683/log_censored.txt)

**Comment by tessus** [comment]
I don't think this is a bug. None of the markups allow a space between the last word and the markup character(s):

```
**bold **
*italics *
```

The above does not work either. Afaik the current behavior follows the spec.

**Comment by laurent22** [comment]
Seems fine then.
