### ISSUE TITLE
Webclipper extensions create Joplin notes without any content (Firefox/Chrome)

### ISSUE THREAD

**Issue by felmey** [laurent22/joplin#629]
### Operating system
- Linux
### Application
- Desktop

Running Joplin 1.0.96 in Arch Linux with Webclipper extensions in both Chrome and Firefox.  Using the Webclipper service creates a note in Joplin with a title but no content.  The images are neither attached or displayed. The Webclipper service is active and the port is open.

Attempted to post debug information from Firefox debug console but upon review there was much more information than just this app/service/extension.

EDIT: Corrected Joplin version typo thanks to @foxmask

**Comment by felmey** [comment]
@foxmask I am running Joplin 1.0.96.  Thanks for pointing that out.  I just updated the original post.

Tested Joplin again with Webclipper today and still the problem persists.  The note is created, with the proper title, but no content within the note.

**Comment by laurent22** [comment]
Just to be sure, please could you provide the version of Web Clipper and the version of desktop app your are using?

If the problem persists, could you provide the debug info as described there? https://joplin.cozic.net/clipper/

**Comment by felmey** [comment]
Sure,

Joplin 1.0.96
Joplin Web Clipper (Firefox): 1.0.5
Joplin Web Clipper (Chrome): 1.0.5

It will take me a while to sort through the debug info and delete all the non relevant entries...  When I went to do it for the original entry it contained entries for my password manager, etc.  But I'll see what I can do.  Thanks.

**Comment by laurent22** [comment]
For the desktop ap, please try with version 99 as the one you have is not compatible with the latest web clipper: https://github.com/laurent22/joplin/releases/tag/v1.0.99

**Comment by laurent22** [comment]
Fixed in cf4331c5af7aadfc0c916e0b72dd0f0457ab350b

**Comment by felmey** [comment]
I just installed Joplin 1.0.99 and the Web Clipper service is working properly now.  I've requested the Arch Linux AUR be updated.  Thanks again.
