### ISSUE TITLE
Item is kept stored on the server

### ISSUE THREAD

**Issue by pelijaro** [laurent22/joplin#6293]
Hi,

I have deployed through a docker container a Joplin server. I created a note, in my Joplin client connected to this server, with a PDF manual inserted in it and this PDF file was stored on my server. 
After deleting the note I see that the PDF file is still stored on the Joplin server even though it is not associated with any note.

I read that in principle this was corrected since in the past it was a bug, maybe I'm wrong, but supposedly the server should detect that the file is not linked to any note and therefore should remove it from the server, is this so or am I wrong?

The note with the file was deleted the same day of its creation, I attach a screenshot of it:

<img width="863" alt="image" src="https://user-images.githubusercontent.com/11003546/158962355-e61a08e9-0628-47b0-92b5-aca6bfcdcb27.png">

It is almost a month old and still there, will this file be deleted at some point? This is worrisome because the files are accumulating on the server even though the notes no longer exist.

## Environment

Joplin version server: 2.7.4
Joplin version client: 2.7.15
Platform: windows
OS specifics: 10

## Steps to reproduce

1.  Create a note and insert any file into it.
2. Delete note with the file inserted, see how the file remains on the server over time.

## Describe what you expected to happen

I hope that when the note is deleted with a file inside it, this file, which does not belong to any other note but only resides in the deleted one, will be deleted from the server.

Sorry if the solution or answer to this problem has already been published. I did a search before opening this application but I have not been able to find something that works for me.

Thank you very much.

Best regards.

**Comment by pelijaro** [comment]
Hi @laurent22 

Hi,

any help with this problem?

Thanks!

**Comment by Daeraxa** [comment]
What are your note revision settings? Resources younger than the setting won't be deleted as they will be associated with the old revision of the note.

**Comment by pelijaro** [comment]
> What are your note revision settings? Resources younger than the setting won't be deleted as they will be associated with the old revision of the note.

Hi @Daeraxa,

Thank you very much for your response. I have never had note history enabled as you can see in the screenshot:

<img width="177" alt="2022-04-22 09_27_28-Joplin - Options" src="https://user-images.githubusercontent.com/11003546/164627744-59c606b7-5320-4f38-b426-7181ca2d5845.png">

That's why I don't understand why the file attached to the note that I deleted some time ago and that didn't have the history enabled is kept.

Thanks.

**Comment by Daeraxa** [comment]
I guess that file could have become orphaned for some reason, I don't think Joplin is really aware that it exists as the sync is primarily driven from the client side. If there is a resource on the target that the clients think doesn't exist then I don't think anything will happen to it.

Generally I believe the clients tell the sync target that a resource is no longer needed when it is no longer associated with any note or note revision and should delete it. Short of checking in the local databases for any references to that ID or finding a way to directly replicate the behaviour I'm not sure what else can be done.

For example if you are able to reliably replicate adding a resource, deleting the note and show that the delete event doesn't happen with the related log files from the client and server then it would be easier to actually look into it properly.

**Comment by pelijaro** [comment]
Hi @Daeraxa,

Thanks for the extensive response, I'm trying to figure out what's going on from my short experience.
The problem is that that attachment of the note that no longer exists is taking up physical space on my NAS, I might try to repodrucir again the problem because I can't think of how to figure out why the file is still there, I don't have that much experience :)

For clarification, I understand that if note history is disabled, if I create a note with an attachment it is synced and stored on the server and then I delete that note along with the attachment and it is synced, it should immediately be deleted the file from the server, right?

Best regards.

**Comment by Daeraxa** [comment]
Part of the equation is the resource service and when it creates entries in the (client) database table `note_resources` (noteid, resource_id, is_associated). This apparently runs 30s after client startup or every 4 hours in the background.

So once one of those timers is met it should run and create an entry, if the resource is no longer associated with the note then `is_associated` should be 0 and I would expect the client to delete the resource and on next sync, delete the resource on the server.

**Comment by pelijaro** [comment]
Well, I'm going to try creating a new note and attaching a PDF, for example, and see what happens when I delete that note. The attachment should not be on the server for more than a day.

**Comment by pelijaro** [comment]
Hi @Daeraxa,

I just created a note and attached a PDF file as you can see here:

<img width="769" alt="2022-04-22 11_18_51-Configuración" src="https://user-images.githubusercontent.com/11003546/164678460-79001336-e17f-4bd1-bb62-ac6770c2b4d4.png">

I have synchronized it and it has been uploaded to the server:

<img width="862" alt="2022-04-22 11_19_44-Joplin Server - Items" src="https://user-images.githubusercontent.com/11003546/164678473-0cffe320-bd95-4f33-9518-bd335ab0f7b6.png">

After that I deleted the note, manually synchronized the client with the server. I closed the client to run the process after 30 seconds and the PDF remains on the server :(

What could be happening?

Thanks!

**Comment by Daeraxa** [comment]
Does the resource still exist on your profile directory?

Can you take a copy of your sqlite database from your local profile and check for that id in your note_resources table i.e. 

```sql
select * from note_resources where resource_id = 'aaabbbccc....'
```

Can you also post the logs for that timeframe?

**Comment by pelijaro** [comment]
@Daeraxa 

The file a exists in my profile directory:

<img width="521" alt="2022-04-22 12_13_43-resources" src="https://user-images.githubusercontent.com/11003546/164690065-afa5de4f-5f96-4576-a90b-6f3780fd39ec.png">

Here is the result of the query execution:

<img width="528" alt="2022-04-22 12_21_33-DB Browser for SQLite - C__Users_ejimenez_Desktop_database sqlite" src="https://user-images.githubusercontent.com/11003546/164690519-e1d90985-f623-4c75-a3c9-0ead09e5e0c9.png">


[log_from_11AM.txt](https://github.com/laurent22/joplin/files/8539961/log_from_11AM.txt)

**Comment by roman-r-m** [comment]
If I'm reading this correctly just unchecking "enable note history" isn't going to do anything, you also need to set the history duration to 0

https://github.com/laurent22/joplin/blob/bd917ae09c6b74bb8d146de794f556d3cc6bab79/packages/lib/services/ResourceService.ts#L118-L120

**Comment by pelijaro** [comment]
> If I'm reading this correctly just unchecking "enable note history" isn't going to do anything, you also need to set the history duration to 0

# **EDIT: Changing the number of days to 0 solved it, thank you very much!**

Hi @roman-r-m 

Thanks for your resply.

I just set the days to 0 in the desktop client and in the mobile client to 1 (it's the minimum it allows). Theoretically, according to the documentation, when there is discordance in configurations as it is this almost, it should apply the value 0.

<img width="155" alt="image" src="https://user-images.githubusercontent.com/11003546/164705518-2051dc05-ca04-49ba-b045-4d9cb4190dca.png">


For now the file still remains on the server...
