### ISSUE TITLE
Deleted notes aren't sent to the revision table

### ISSUE THREAD

**Issue by evoneon** [laurent22/joplin#6297]
I deleted an important note, probably while cleaning up some notes by accident. After looking up the Joplin documentation, I was glad to find a way to retrieve them using SQLiteStudio. Fortunately, I was able to recover A VERSION of the say deleted note. Unfortunately, I wasn't able to recover the note with the most updated content modifications. I don't understand how well established can be the revisions table (note history), so to track every single little change but not take into account a note deletion as well. My suggestion would be to add the deletion as an event to be included in the revisions table so when we need to retrieve a deleted note, we don't lose any recent modifications.

## Environment

Joplin version: Joplin 2.7.15 (prod, darwin)
Platform: macOS Monterey
OS specifics: 12.2.1

## Steps to reproduce

1. Make a note, add some content and save
2. Edit the content, delete the note and save
3. Use SQLiteStudio to access the revision table
4. You won't find the deleted note with it's latest content but rather the older version of it's content.

## Describe what you expected to happen

To find the deleted note with the most updated content in order to restore it without loosing any modification. How am I suppose to restore a deleted note with the most updated details?

**Comment by laurent22** [comment]
I think if you wait, the last version of the note, as it was when deleted, should eventually show up in the revision table. But in any case it's not a bug. What you want is a Trash folder, and there's already a feature request for this.
