### ISSUE TITLE
(webm) Files with only audio tracks take up the space of a video.

### ISSUE THREAD

**Issue by jtagcat** [laurent22/joplin#6299]
![image](https://user-images.githubusercontent.com/38327267/159151557-00db2113-3511-4e49-8bbb-1cc17df5f2b1.png)

expected: render it as audio, only the bottom bar

```
yt-dlp -f bestaudio <video>
ffmpeg -i xyz.mp3 xyz.webm
```

## Environment
Joplin version: 2.7.13 (prod, linux)
Platform: Fedora 35 Flatpak

**Comment by kxnakr** [comment]
Hey,

This is not a bug in Joplin. ```.webm``` format are [picked up as a video file](https://github.com/laurent22/joplin/blob/1b2046f2fa719832945de73f8eedb77c8693389c/packages/lib/mime-utils-types.js#L753), as the mime on it, is of "video/webm"

"audio/webm" requires [.weba](https://fileinfo.com/extension/weba) [extention](https://github.com/laurent22/joplin/blob/1b2046f2fa719832945de73f8eedb77c8693389c/packages/lib/mime-utils-types.js#L609)

[Mozilla Ref](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types)

I will suggest to use some other audio format

**Comment by jtagcat** [comment]
Notes for self
 - ffmpeg does not know what to do with weba
 - there are no video streams in the file

***

 - not possible to mass import/export (especially edit in place) a bunch of files, 8 files will probably take ~10m of manual work (like you can edit text in an external editor)
   - if you tamper with underlining raw files, probably possible
 - joplin: not possible to collapse as you can with images (by removing `!` from the beginning)

**Comment by personalizedrefrigerator** [comment]
>     * joplin: not possible to collapse as you can with images (by removing `!` from the beginning)

Try collapsing it by using an HTML link: `<a href=":/resource-id-here">Link text</a>`

**Comment by jtagcat** [comment]
> Try collapsing it by using an HTML link: `<a href=":/resource-id-here">Link text</a>`

sorry, not really usable daily: it is not really memorable, simple to use, nor compact in markdown + don't exactly know how the auto-delete for unused attachments works behind the scenes
