### ISSUE TITLE
Terminal - Keyboard navigation improvements

### ISSUE THREAD

**Issue by guyb7** [laurent22/joplin#63]
### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [x] Terminal

---

As a vim-like interface, I expected common vim navigation shortcuts:
- `j`/`k` to move up/down on items
- `Ctrl+ww` to focus on next pane
- `h`/`l` and `left`/`right` could also be used to focus on next/prev panes
- `o` to edit selected note

**Comment by laurent22** [comment]
Note: that can be done by making the shortcuts defined there configurable - https://github.com/laurent22/joplin/blob/7851b6b429b4f15226ff25f7db543ad4dc823536/CliClient/app/app-gui.js#L265

**Comment by laurent22** [comment]
Shortcuts can now be customised by adding a keymap.json to the profile directory. See [the documentation](http://joplin.cozic.net/terminal/#shortcuts) for more information, and if you have any question please post here.

**Comment by phlind** [comment]
Is it possible to configure a shortcut to go left, i.e. back to the notebooks pane from the notes pane? I would like to mimic the vim commands for navigation and while it works for going up and down and moving right by mapping "l" to "activate", I cannot map "h" to go back left.
