### ISSUE TITLE
Unable to drag in the second-level or other groupings to the first-level grouping

### ISSUE THREAD

**Issue by pgy866** [laurent22/joplin#6300]
Group 1
               Group 1
               Group 2
               Group 3
               Group 4

I can drag "Group 1" into "Group 2"
Drag "Group 4" into "Group 3":
Group 1
-------Group 2
Group 3
-------Group 4

After dragging in I can't drag them out to the first level,
Drag "Group 2" out to the first level group：
Group 1
Group 2
Group 3
-------Group 4

**Comment by Daeraxa** [comment]
You need to drag to the "notebooks" header to move back to the highest level.

**Comment by pgy866** [comment]
> You need to drag to the "notebooks" header to move back to the highest level.

thank you very much! It is effective

**Comment by pgy866** [comment]
@Daeraxa   Hi!
joplin://ca7a7a0........

Export HTML file + directory
How to make him automatically convert the link of 


joplin://ca7a7a0........ to      note_name.html

**Comment by Daeraxa** [comment]
I think I understand what you mean but could you ask this on the forum? I'm wondering if it is the correct behaviour or not.

**Comment by pgy866** [comment]
> I think I understand what you mean but could you ask this on the forum? I'm wondering if it is the correct behaviour or not.
HI, I can't find a place to post help in the forum, he needs me to add a user, I don't know who should I send it to?
Can you help me post it?
![截图_选择区域_20220323133734](https://user-images.githubusercontent.com/28694676/159631324-9ade0f94-8e3a-4edb-905d-df0d2a6a9382.png)

**Comment by pgy866** [comment]
> I think I understand what you mean but could you ask this on the forum? I'm wondering if it is the correct behaviour or not.
I record the requirements for GIT media, as follows,
I'm so sorry, my English is terrible,
I hope we can understand each other's meaning.


---- 


joplin://ca7a7a0........

Export HTML file + directory
How to make him automatically convert the link of

joplin://ca7a7a0........ to note_name.html


https://github.com/laurent22/joplin/issues/6300#issuecomment-1073901480

![录屏_选择区域_20220323132832](https://user-images.githubusercontent.com/28694676/159631433-f89627c0-3f45-48ae-9392-3f068dcf8839.gif)

![录屏_选择区域_20220323132916](https://user-images.githubusercontent.com/28694676/159631406-f8be123b-34d8-4f1f-919a-19c30e1c2edb.gif)

**Comment by Daeraxa** [comment]
Yes, I understand the issue but this github issue isn't the correct place to discuss it. You need to create a forum account and post it there in the support category. 
Alternatively raise it as a new github issue but I'm not sure if this counts as a bug or if this is deliberate.

**Comment by pgy866** [comment]
> Yes, I understand the issue but this github issue isn't the correct place to discuss it. You need to create a forum account and post it there in the support category. Alternatively raise it as a new github issue but I'm not sure if this counts as a bug or if this is deliberate.

Thank you, I have a registered account in the forum, trying to find how to post new posts, but I can't find a way.

I will submit a new line on GITHUB, please forgive me if I disturb the order
https://github.com/laurent22/joplin/issues/6312
