### ISSUE TITLE
Tag sorting (regression)

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#6301]
Since the Joplin desktop version 2.7.15, tag sorting is different between Joplin mobile app and desktop app. 

## Environment

Joplin version: 2.7.15
Platform: Windows
OS specifics: Win10

## Steps to reproduce

Compare new tag sorting and before 2.7.15 release.
Issue related with https://github.com/laurent22/joplin/issues/5686

## Describe what you expected to happen
Tags should be in the same sequence as the mobile application.

It would have been preferable to maintain the order of the left panel (from v2.7.14 and earlier versions), because :
- the sorting has already been chosen by the user there. While on the drop-down panel the user does not have the option to order.
- the mobile app succeeds in following the same order by selecting an existing tag and adding a tag to a note.

**Comment by laurent22** [comment]
@OmGole, do you know about this issue, and any idea how it could be fixed?

**Comment by laurent22** [comment]
@OmGole, I'm assuming you're not going to fix it? In that case we will revert it for the next version.

**Comment by laurent22** [comment]
Well let's revert then. Thanks for nothing omgole.

**Comment by OmGole** [comment]
Hey @laurent22 I really really apologize for not communicating quickly. I had something come up in my personal life and had some college work to do. I have looked into the mobile tag sorting and I will try my best to understand the issue and fix it as soon as I can. I hope you understand and give me another chance.

**Comment by OmGole** [comment]
Update: From what I have gathered this is happening due to the different sorting methods used in desktop and android/ios. This could be solved by using a single sorting method through the entire codebase(desktop and android/ios). As dot-clear mentioned above we could use the previous sorting method (without localeCompare) or the new one which CalebJohn suggested here #6136 . Which sorting method should be used @laurent22

**Comment by laurent22** [comment]
Yes we should use the same function for all apps, and it should be done with localeCompare.

**Comment by OmGole** [comment]
Ohkk I will change the sorting function for all platforms and keep you updated.

**Comment by ghost** [comment]
Could we have an example of the rendering ?
I will be able to try it in the next pre-release.

**Comment by OmGole** [comment]
@dot-clear I can send screenshots will that work?

**Comment by ghost** [comment]
Yes please.

**Comment by OmGole** [comment]
Here is sample of how it would look @dot-clear @laurent22 . I have referred #5686 for these tags.
These tags were sorted using localeCompare


![sidemenu tags](https://user-images.githubusercontent.com/90026187/161429587-7b04b5d5-e2e4-4dc9-852e-f740136161dc.png)
![dialog tags](https://user-images.githubusercontent.com/90026187/161429593-48182cbd-37a1-4c60-b10b-ccd6649cfccc.png)

**Comment by ghost** [comment]
Thanks @OmGole for sharing. Personally, I prefer the current sort of mobile app. Numbers in tags could be ordered first in the list. eg. : 1House, 2Computer, 3Wait, ...
But I can appreciate that the change is more complex on the desktop app drop-down menu.

**Comment by OmGole** [comment]
What to do now ? @laurent22

**Comment by laurent22** [comment]
Whatever is the easiest.

**Comment by OmGole** [comment]
I suggest using localeCompare should I make the changes and submit a PR?

**Comment by laurent22** [comment]
yes
