### ISSUE TITLE
Accidentally pasted large (1MB) text, now note freezes Joplin

### ISSUE THREAD

**Issue by Cristy94** [laurent22/joplin#6305]
## Environment

Joplin version: 2.7.15 (win 32) (also happens in previous versions like 2.4)
Platform: Windows 11
OS specifics: 21H2 build 22000.556

## Steps to reproduce

1. Paste large text (1MB+) in a `code` formatted section
2. The note will be frozen, trying to edit it in Markdown view will make the screen go white

## Describe what you expected to happen

I accidentally pasted 1MB+ of text in a code section inside a note, in editor view. Now I can not undo my changes nor open the note as it will freeze Joplin. Expected: Joplin doesn't crash when a large text is pasted in a ```code block```.

**Comment by laurent22** [comment]
You could start in safe mode (Under Help menu)
