### ISSUE TITLE
Possiblilities for right to left language support (RTL)

### ISSUE THREAD

**Issue by albacoretuna** [laurent22/joplin#631]
### Operating system
- Linux
- Android

### Application
- Desktop
- Mobile

I'm using the awesome Android and Linux apps. Do you have any desire to add support for right to left languages? 

In the android app when I'm typing in an RTL language (Farsi) the text boxes detect it correctly but after the note is saved, it's displayed left to right. 

For example: 
```
سلام. حال شما خوبه؟
```

Should appear right to left. 

I'd be happy to help.

**Comment by laurent22** [comment]
Unfortunately I don't know any RTL language so won't be able to look at this, but I leave the issue open in case someone can fix it.

**Comment by PromyLOPh** [comment]
Here are a few screenshots with Android’s UI set to Arabic. Usually not just text is RTL, the entire UI is flipped. But Joplin seems to hard-code a few UI items’ positions:

![screenshot_ -](https://user-images.githubusercontent.com/13182/45368870-e8efca00-b5e4-11e8-9c70-0ba79cbc3062.png)
![screenshot_ -](https://user-images.githubusercontent.com/13182/45368873-ebeaba80-b5e4-11e8-8dbe-a7388c2acdef.png)
![screenshot_ -](https://user-images.githubusercontent.com/13182/45368877-edb47e00-b5e4-11e8-8e05-3ae0cd4e0823.png)
