### ISSUE TITLE
Exporting HTML file + table of contents does not automatically convert links

### ISSUE THREAD

**Issue by pgy866** [laurent22/joplin#6312]
---- 

joplin://ca7a7a0........

Export HTML file + directory
How to make him automatically convert the link of

joplin://ca7a7a0........ to note_name.html

![录屏_选择区域_20220323132832](https://user-images.githubusercontent.com/28694676/159631433-f89627c0-3f45-48ae-9392-3f068dcf8839.gif)

![录屏_选择区域_20220323132916](https://user-images.githubusercontent.com/28694676/159631406-f8be123b-34d8-4f1f-919a-19c30e1c2edb.gif)

**Comment by Daeraxa** [comment]
Basically it seems that when an internal Joplin link e.g. `[mynote](:/99ef6ed69d4d4058a92a50ca08bc2c03)` is processed by the export HTML, it converts the link to an x-callback-url to the original note within Joplin.
My expectation is that if the linked note is also exported then that link should be a local reference, not an x-callback-url as it would be with markdown export.

## HTML export

```html
<p><a data-from-md data-resource-id='9bfe28808e724002bd281f1f67503046' href='joplin://9bfe28808e724002bd281f1f67503046'>Note 1</a></p>
```

## MD export

```md
[Note 1](../exportNotes/Note%201.md)
```

**Comment by Acvarium** [comment]
Tested 2.8.4. The issue is not resolved yet
