### ISSUE TITLE
Joplin slows down window manager

### ISSUE THREAD

**Issue by imkzh** [laurent22/joplin#6320]
I experienced HUGE lag (every time) after starting Joplin 

* i'm using Joplin-1.7.11 (for a long time, after realized the cause is Joplin, I downloaded the latest version Joplin-2.7.15, the problem persists)
* I'm on Ubuntu 16.04 x64 (Unity+Compiz desktop environment).

I usually have tons of apps running on my computer, they all work smoothly until I start Joplin.
The apps themselves are responsive (including Joplin), but the window manager will become extremely slow after Joplin started.

All window related operations become slow, including: creating window, switching between windows(take more than 1 second to focus a window), moving window around(framerate drop), switching between workspaces(virtual desktops), maximizing windows, ...

I also have other electron app running, but they do not cause similar problems.

The most strange part is, when I start OBS to record this, all lag disappeared, until 5 or 10 minutes after quitting OBS. It seems Joplin is requesting window manager to do some special window handling work (like `unredirect`-ed compositing?)

Please ask me if more information is needed.

## Environment

Joplin version: Joplin-2.7.15
Platform: Linux
OS specifics: Ubuntu 16.04
Compiz 0.9.12.3 
unity 7.4.5 (the Ubuntu shell)

## Steps to reproduce

1. Start Joplin
2. Experience above mentioned lag
3. Quit Joplin
4. Lag disappear

## Describe what you expected to happen
1. Start Joplin
2. Everything is smooth as always.

## Logfile
[log.txt](https://github.com/laurent22/joplin/files/8350839/log.txt)

**Comment by laurent22** [comment]
Do you use any plugin?

**Comment by imkzh** [comment]
@laurent22 If you mean Joplin plugin, no.
![image](https://user-images.githubusercontent.com/5917425/160150523-69bc9c5c-d4ce-4bf7-b42a-d30f856a3e0e.png)

(There are some builtin plugins in Compiz)

**Comment by Daeraxa** [comment]
So I just had a go with a VM running Ubuntu Unity (20.0.4, Compiz 0.9.14.1, Unity 7.5.0) and it is perfectly performant, I can't replicate any of the slowdown issues you mention.

Do you have issues with any other Electron apps? Do you have the appimage version or did you install from snap, flathub etc?

**Comment by imkzh** [comment]
@Daeraxa I have no issue with other electron app (also no issue with nwjs app, chromium based app and other app with webkit view)
I use the appimage version downloaded from official site.

**Comment by laurent22** [comment]
Maybe some display driver issue? Some people had this problem on Linux although with different symptoms.

Or is the app actually doing something like decrypting or synchronizing notes? (You can check that in the left sidebar)

**Comment by sibilus** [comment]
16.04 is EOL.

**Comment by imkzh** [comment]
After some digging, I found synchronize is turned on, and the lag always happen while synchronizing.

Since my synchronization server is down(due to restrictions in my organization LAN), the synchronize will take forever.

(I also found when the developer tool is opened, the lag disappear immediately)

While synchronization, there is a spinning icon `.bWLsHp` with following style:

    margin-right: 6px;
    font-size: 18px;
    animation: icon-infinite-rotation 1s linear infinite;

So I made following test:
* Turn off sync
* Start app, no lag
* Make a normal ui icon spinning, with custom style sheets (userchrome.css)
```
/* make the "new to-do icon" in note list spinning */
#react-root > div:nth-child(2) > div > div.resizableLayoutItem.rli-root > div.resizableLayoutItem.rli-noteList > div.sc-fznKkj.gCTJhE > div > div.sc-fznLPX.jOMZUp > div.sc-fzqMdD.kcnolE > button.sc-AxirZ.sc-AxhUy.dAaSNI.sc-fzozJi.sc-fzoaKM.HRsnz.new-todo-button > span {
    margin-right: 6px;
    font-size: 18px;
    animation: icon-infinite-rotation 1s linear infinite;
} 
```
* Restart app
* Lag present

So the lag is caused by the spinning icon, I have no idea why this would happen, because I have no issue with chrome.

**Comment by imkzh** [comment]
I wrote a simple electron app with a single rotating keyframe-animated element, and it DO cause the lag, so the issue is not caused by Joplin. 

(At present we can use a animated image like GIF rather than actual rotating DOM element to avoid the problem, which is, frustrating.)
