### ISSUE TITLE
Line Breaks Missing on iPad Pro

### ISSUE THREAD

**Issue by rsbrux** [laurent22/joplin#6322]
## Environment
Joplin App on iPad Pro 2020 running iPadOS 15.4

Joplin version: 12.7.1
Platform: iPadOS 15.4
OS specifics: ?

## Steps to reproduce

1. Open note in Joplin on iPad Pro
2. Compare appearance to that on other platforms (Android 12, Windows 10 21H2) 
3. Display on iPad is continuous, without line breaks. Both Android and Windows apps display notes with the expected line breaks.

## Describe what you expected to happen
Same appearance of notes on all platforms

## Logfile

These instructions are not very useful.  The errors from the Log tool in Joplin Configuration are all text but cannot be selected and copied as such.  They also take more than one screen. The displayed errors are sync errors and are therefore likely irrelevant. Joplin is not crashing, so the low level log instructions also appear irrelevant.

**Comment by rsbrux** [comment]
Much to my surprise, the line breaks returned when I *disabled* soft line breaks in Joplin's Configuration on my iPad. This seems counter-intuitive to me, but at least my immediate problem is solved.

**Comment by Daeraxa** [comment]
The default is hard line breaks, not soft so by turning it on you are asking joplin to render it as traditional markdown.
Typically in markdown a paragraph is delimited by a full blank line and a line break is by two spaces on the preceding line then a return.

https://www.markdownguide.org/basic-syntax/#paragraphs-1
https://joplinapp.org/markdown/#markdown-plugins

**Comment by rsbrux** [comment]
@Daeraxa, thx for responding and sorry that I was too ignorant to figure this out for myself!
MD is new to me.
