### ISSUE TITLE
Mobile/Beta Editor: Undo/redo stack is lost when closing and re-opening the editor

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#6329]
## Environment

Joplin version: https://github.com/laurent22/joplin/commit/dd10b6ac6543d0acc82d0debd860ed3b450feb32 on Android, 12.7.1 on iOS
Platform: Android, iOS
OS specifics: Android 11, iOS 15.4

## Steps to reproduce

1. Create a new note
2. Ensure the beta editor is enabled
3. Edit the note until the undo button appears
4. View the rendered version of the note (click the back button)
5. Edit the note again
6. Click `undo`

## Describe what you expected to happen

The editor should undo.

**Comment by personalizedrefrigerator** [comment]
At present, I can think of two possible solutions:
 1. After opening the `NoteEditor`, don't close it, just make it visible/invisible
     - This will lead to higher memory usage, but less frequent re-creations of the `NoteEditor` component (while also preserving `undo`/`redo` history)
 2. Use CodeMirror's [`EditorState::toJSON`](https://codemirror.net/6/docs/ref/#state.EditorState.toJSON) and [`EditorState::fromJSON`](https://codemirror.net/6/docs/ref/#state.EditorState^fromJSON) to serialize/deserialize the editor's state (which should include undo/redo history) when we close/re-open it.
     - This seems more difficult to implement...
 
Ideas for other ways to fix this/options are appreciated!

**Comment by roman-r-m** [comment]
Joplin already saves note revisions, can this be used for undo?

**Comment by personalizedrefrigerator** [comment]
> Joplin already saves note revisions, can this be used for undo?

Possibly! I think it would be ideal to preserve the CodeMirror undo/redo (if possible) — the note revisions (I expect) are separated by more time.

Thank you for the suggestion!
