### ISSUE TITLE
In windows, search in all notes begins in the middle of the input

### ISSUE THREAD

**Issue by Fr3d-P** [laurent22/joplin#6333]
## Environment

Joplin version: 2.6.10
Platform: Win32
OS specifics: Windows 10, French language

## Steps to reproduce

1. click on the search field
2. try to type 'collection'
3. In most of the case, the search will begin approximately for "collect"

## Describe what you expected to happen
Have to type Enter to launch the search, not trying to search when I type

## Logfile
No log file

**Comment by grvsh02** [comment]
I guess the search fields are dynamic, they use the `onChange` property, which means the search begins whenever there is a change in the search bar. 
It's a feature and not a bug.

**Comment by Fr3d-P** [comment]
Something that prevent me to search what I type can not be called a feature,  I think!

My opinion is that the search should work for the PC version like it works on the mac one:
The search begins as you type, but the search field doesn't clear when the search is launched, so the text can be modified/completed to correct or refine the search

**Comment by Daeraxa** [comment]
But that *is* what happens on the Windows version (or at least it does for me). You start typing into the box, it searches but the box remains in focus with the cursor still blinking, typing more letters or deleting previous ones changes the results of the search.

**Comment by Fr3d-P** [comment]
For me, on my window machine, if I type several characters and then slow down or stop typing, the search starts **and** the search field is cleared, so I can't refine my search.
The same behaviour exists since at least two versions of Joplin

What can produce this strange result?

**Comment by Daeraxa** [comment]
Honestly no idea but it is going to be difficult to find any issue unless it can be reliably replicated on other machines.

**Comment by Fr3d-P** [comment]
I noticed last week that the search is working correctly when the outline module is deactivated on windows.
I upgraded the module to the latest version, but the problem is still there.
Does anybody with outline module on windows have the same problem than mine?

**Comment by Fr3d-P** [comment]
Well,
it seems that I'm alone using outline on the windows version...
I did disable the module, I think I have to continue like that...
