### ISSUE TITLE
Support for tamil language

### ISSUE THREAD

**Issue by techstack2022** [laurent22/joplin#6336]
Hi,

https://joplinapp.org/help/#searching

#1 - Need support for Joplin search for tamil unicode fonts (ex: http://www.tamiltyping.in/)
#2 - Need support for tamil fonts (installed one. assume each note will have it's won font. ex: https://www.azhagi.com/freefonts.html)
#3 - Tamil Menus for localization - All menus for tamil readers/users

Thanks

**Comment by roman-r-m** [comment]
> #3 - Tamil Menus for localization - All menus for tamil readers/users

Translations are made by users. If you have time, you could help translating, otherwise we'd have to wait for someone to do it, as I'm pretty sure neither Laurent nor other regular contributors speak Tamil.
