### ISSUE TITLE
Pressing 'Esc' button in "Delete note?" confirmation dialog will delete the note

### ISSUE THREAD

**Issue by penguinsam** [laurent22/joplin#634]
### Operating system

- Windows

### Application

- Desktop

In the dialog of asking 'Yes' or 'No' when deleting a note, pressing 'Esc' button will delete the note, which I expect it will return to application without doing anything.

**Comment by laurent22** [comment]
I cannot replicate this actually. Is that Windows 10? Could you post a screenshot of the message box by any chance?

**Comment by penguinsam** [comment]
I attached 2 screenshots for you. The note was deleted after I pressed the 'Esc' key.
<img width="1280" alt="2018-06-22" src="https://user-images.githubusercontent.com/6859350/41739266-1f471c10-75c7-11e8-9bed-eedc88ed6f42.png">
<img width="1280" alt="2018-06-22 1" src="https://user-images.githubusercontent.com/6859350/41739272-276248b6-75c7-11e8-8240-1a2b9e612b72.png">

**Comment by penguinsam** [comment]
I just found the 'Delete note' dialog is different between English and Chinese:
<img width="1280" alt="2018-06-22 2" src="https://user-images.githubusercontent.com/6859350/41739366-72b75cca-75c7-11e8-8f33-f1a7aa42607f.png">

I cannot reproduce it using English but it can easily be reproduced in Traditional or Simplified Chinese, and Japanese too.

**Comment by laurent22** [comment]
Thanks, I'll do some tests with the Chinese version.

**Comment by penguinsam** [comment]
@laurent22 Tested ok in 1.0.104, thanks.
