### ISSUE TITLE
[feature request] Make the web clipper run on mobile

### ISSUE THREAD

**Issue by nr458h** [laurent22/joplin#635]
### Operating systeme
- Android
- iOS

As a mobile focused worker it would be helpful if the webclipper also runs on android (and ios)

Still thanks for your continues improvements on the app! Very nice piece of software!

**Comment by laurent22** [comment]
It's been requested before, but cannot be done.

**Comment by xcffl** [comment]
This might be related, though this feature currently still cannot be achieved by it: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
