### ISSUE TITLE
Reverse proxy problem

### ISSUE THREAD

**Issue by gracehuahua** [laurent22/joplin#6350]
Hi,  i use npm(niginx proxy manager) to accomplish reverse proxying of joplin, with the configuration as list :

    location / {
        proxy_pass http://192.168.20.200:22300;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Host $host;
        client_max_body_size 400M;
    }
I can visit joplin server (https//:jobplin.example.com:40000), but not perfectly. Like that:

![Screenshot_2022-03-31-14-11-26-565_com UCMobile](https://user-images.githubusercontent.com/92935161/160989333-3dab04cb-e89d-4670-9afc-083a667b234d.jpg)

 Likely, visiting some html elements are not allowed (invalid origin). But https//:jobplin.example.com:40000/login can be visited partily, and https//:jobplin.example.com:40000/images/icon.png is not allowed. Why? Can someone help me?

**Comment by ACasset** [comment]
Hello @gracehuahua
How is the Joplin Server installed on your host?
Is it with the docker-compose? If so, what was the APP_BASE_URL you provided?

**Comment by gracehuahua** [comment]
> Hello @gracehuahua How is the Joplin Server installed on your host? Is it with the docker-compose? If so, what was the APP_BASE_URL you provided?

yes, the Joplin Server was installed with docker-compose. The APP_BASE_URL  is https//:jobplin.example.com:40000. Everything including synchronization works well except the login web.

**Comment by rwoodpecker** [comment]
I spent far too much time troubleshooting a similar issues today but have finally got it working...

In the nginx config, try change this:

```
location / {
    proxy_pass http://192.168.20.200:22300;
    proxy_set_header Host $http_host;
    ...
```

To this:
```
location / {
    proxy_pass http://192.168.20.200:22300;
    proxy_set_header Host $host:22300;
    ...
```

One more thing, if you want to proxy Joplin to port 443 for example you'll need to reflect that in the APP_BASE_URL in the docker-compose. It'll probably look like APP_BASE_URL=https//:jobplin.example.com:443. The APP_PORT above that can be left at 22300.

**Comment by gracehuahua** [comment]
> 



> I spent far too much time troubleshooting a similar issues today but have finally got it working...
> 
> In the nginx config, try change this:
> 
> ```
> location / {
>     proxy_pass http://192.168.20.200:22300;
>     proxy_set_header Host $http_host;
>     ...
> ```
> 
> To this:
> 
> ```
> location / {
>     proxy_pass http://192.168.20.200:22300;
>     proxy_set_header Host $host:22300;
>     ...
> ```
> 
> One more thing, if you want to proxy Joplin to port 443 for example you'll need to reflect that in the APP_BASE_URL in the docker-compose. It'll probably look like APP_BASE_URL=https//:jobplin.example.com:443. The APP_PORT above that can be left at 22300.

Thanks for your kind replying. Unfortunately, that does not  work for me. Once set host as $host:22300, the login will fail to load with error message of "invalid origin https//:jobplin.example.com:22300", which conflicts with  APP_BASE_URL .

**Comment by rwoodpecker** [comment]
> > I spent far too much time troubleshooting a similar issues today but have finally got it working...
> > In the nginx config, try change this:
> > ```
> > location / {
> >     proxy_pass http://192.168.20.200:22300;
> >     proxy_set_header Host $http_host;
> >     ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To this:
> > ```
> > location / {
> >     proxy_pass http://192.168.20.200:22300;
> >     proxy_set_header Host $host:22300;
> >     ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > One more thing, if you want to proxy Joplin to port 443 for example you'll need to reflect that in the APP_BASE_URL in the docker-compose. It'll probably look like APP_BASE_URL=https//:jobplin.example.com:443. The APP_PORT above that can be left at 22300.
> 
> Thanks for your kind replying. Unfortunately, that does not work for me. Once set host as $host:22300, the login will fail to load with error message of "invalid origin https//:jobplin.example.com:22300", which conflicts with APP_BASE_URL .

Sorry I was sleep deprived and got that a bit wrong! The port in the nginx settings should match the APP_BASE_URL port, so in your case:

```
proxy_set_header Host $host:40000
```
