### ISSUE TITLE
Permanent Redirect in S3 Sync

### ISSUE THREAD

**Issue by ujaehrig** [laurent22/joplin#6356]
Observed on Desktop Version 2.7.15 and Android 2.7.2

I'm using Amazon S3. The Synchronization has worked with an older version of Joplin. 

When using the S3 URL: https://s3.amazonaws.com, the check fails with an error, but the reported error is empty
When using the S3 URL: https://s3-eu-central-1.amazonaws.com/, the check is successful.

But in both cases the synchronization itself fails. On desktop I get an error: 
```
Last error: redirect location header missing at: https://s3.amazonaws.com/MY_BUCKET/info.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=REDACTED%2F20220401%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20220401T082913Z&X-Amz-Expires=3600&X-Amz-Signature=REDACTED&X-Amz-SignedHeaders=host&x-id=GetObject
```

on Android the error in the log shows: 
```
PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint
```

When calling the URL shown on desktop via curl, I see the similar information as on Android:

```
< HTTP/1.1 301 Moved Permanently
< x-amz-bucket-region: eu-central-1
< Content-Type: application/xml
< Server: AmazonS3
<
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Endpoint>MY_BUCKET.s3.amazonaws.com</Endpoint>
```
 
## Environment

Joplin version: 2.7.15 and Android 2.7.2
Platform: Windows 10

Joplin version: 2.7.2
Platform: Android 12

**Comment by henrythasler** [comment]
I had a similar issue where I could sync to an existing bucket just fine but not into another one I just created in the same region. Changing the S3-URL to the region-specific URL solved my issue with the new bucket. I have no idea why...

**Comment by tobiasb** [comment]
I just encountered the same issue.
