### ISSUE TITLE
[ Feature Request ] Toggle sidebar also toggles note list.

### ISSUE THREAD

**Issue by sedstr** [laurent22/joplin#636]
### Operating system
- Windows 10

Feature Request/Suggestions:
'Toggle sidebar' button | hotkey includes 'notes list' in the toggle cycle in the same way as the layout button toggles between 3 states.

I guess it would require adding something to set the notes list to enabled if a new note is created.
Does the 'Toggle sidebar' button need the word Toggle in it?

**Comment by matthewmoppett** [comment]
(As a LInux desktop app user): I'd find the ability to hide the notes list to be really handy as a way of maximizing viewing/editing space, especially when taking notes from a document open in another app.

**Comment by nr458h** [comment]
:+1:

**Comment by Tommy-01** [comment]
> (As a LInux desktop app user): I'd find the ability to hide the notes list to be really handy as a way of maximizing viewing/editing space, especially when taking notes from a document open in another app.

This is realy distracting me. When writing/reading a Note, the Note List takes to much space. Even when the Window ist maximized.
An movable dividing line between Note List an Note would be fine.

**Comment by sedstr** [comment]
I get excited with every new release - "will I be able to hide that note list this time?"
Then I sigh... Still have that list on the side...

If I have to stare at it all day, at least let me change the font/bold/color of the note titles, as well as be able to change the order to no-order and be able to drag notes up/down the list.

**Comment by i-need-to-tell-you-something** [comment]
For comparison (this will be a feature request eventually when the issue at hand is implemented) in Evernote has separate hotkeys and toggleable buttons (in menubar > View) for hiding/showing all three parts of the UI:
```
[   ] Left Panel                 F10
[   ] Note List                  F11
[ v ] Note Panel            Ctrl+F11
```
The interesting part is that you can also hide the Note panel if you want to see more of Note List. I think as Joplin has many Evernote converts, there is no reason to not imitate Evernote in this feature.
