### ISSUE TITLE
rendered-md tag do not contain all the text in a newly created note

### ISSUE THREAD

**Issue by Sharar-Lykourgos** [laurent22/joplin#6363]
## Environment

Joplin version: Joplin 2.7.15
Platform: Linux
OS specifics:  Fedora Linux 35 (Workstation Edition)

## Steps to reproduce

1. Create a new note 
![New Notes Dev-mode](https://user-images.githubusercontent.com/96591262/161431556-3e0970fe-a39b-41ab-912d-0c96e1edb106.png)
2.  Write a single line of text inside the note
3. Press enter
4. Write another line of text
5. the next line will be inside a new div tag (not rendered-md tag) ![Note Before Switching Dev-mode](https://user-images.githubusercontent.com/96591262/161431607-ccaff6c6-a59b-4796-93f5-40cd84fb6d95.png)
6. Switching back and forth between this note and any note will make both text inside the rendered-md tag
![Note After Switching Dev-mode](https://user-images.githubusercontent.com/96591262/161431646-c12a7af3-d771-4c92-bc02-81f709a60343.png)

## Describe what you expected to happen
Both text should be inside the rendered-md tag.

**Comment by Sharar-Lykourgos** [comment]
Additionally, I noticed that the rendered-md tag disappear  when  pressing backspace if there is no text inside it, but it reappears when switching notes (or it got deleted and added again).


![Kooha-04-07-2022-14-22-22](https://user-images.githubusercontent.com/96591262/162187957-f519eb32-880a-447b-8b08-b28cd874158c.gif)


I would like to add that these bugs effect the note style whenever you change notes which make the note style inconsistent.

**Comment by Daeraxa** [comment]
The second one I reported here - https://github.com/laurent22/joplin/issues/6313
