### ISSUE TITLE
All notes in "Conflicts" after enabling encryption

### ISSUE THREAD

**Issue by jcshelor** [laurent22/joplin#6367]
## Environment

Joplin version: Joplin 2.7.15 (prod, darwin)
Platform: Mac
OS specifics: Monterey 12.2.1

## Steps to reproduce

1. I enabled encryption 
2. Then after Joplin tried to sync with Google Drive, everything moved into Conflicts folder and all notebook structure was lost
3. 

## Describe what you expected to happen

I would have expected my same note/notebook structure with encryption.

**Comment by Daeraxa** [comment]
This sounds like a support issue and you haven't provided any logs anyway. Please log this on [the forum](https://discourse.joplinapp.org/c/support/5) if you need help (with logs).
