### ISSUE TITLE
Cannot input Chinese words properly using Cangjei/Quick IME

### ISSUE THREAD

**Issue by penguinsam** [laurent22/joplin#637]
### Operating system

- iOS

### Application

- Mobile

Cannot input Chinese words properly using Cangjei/Quick IME. 
For example, a word "我" is composed by 3 codes in sequence: "竹" "手" "戈". In iOS, it fails to compose the word but show 3 words separately: https://imgur.com/a/azAJZUu

I remember the similar behavior happened in Google Keep in iOS few months ago.

**Comment by pei-lun** [comment]
It seems that all Chinese input methods fail to compose the word.

In Notes APP:

![img_2717](https://user-images.githubusercontent.com/4880850/41816002-6bd1fbe0-77ac-11e8-91f3-d10a408ddf90.GIF)

In Joplin:

![img_2716](https://user-images.githubusercontent.com/4880850/41816001-6ba8e2d2-77ac-11e8-80ed-ad6ce2a06a72.GIF)

**Comment by RCJacH** [comment]
Is this related to [#525](https://github.com/laurent22/joplin/issues/525)?

**Comment by penguinsam** [comment]
@RCJacH I think it is quite similar.

**Comment by laurent22** [comment]
Closed as duplicate
