### ISSUE TITLE
Error when trying to export to PDF (Linux snap, v 2.7.14)

### ISSUE THREAD

**Issue by MWH-Rookie** [laurent22/joplin#6372]
Hi

When I try to export a notebook to PDF (after fresh snap install of joplin desktop and just taking my first notes), I first get a file browser window, which lets me choose a destination of the PDF and afterwards I get an error message.
This message states:
"Error: ENOENT: no such file or directory, stat '/home/myname/snap/joplin-desktop/27/.config/joplin-desktop/tmp/VERYLONGALPHANUMERICFILENAME.html"
Well, and that's it.

## Environment

Joplin version: 2.7.14
Platform: Linux
OS specifics: Ubuntu 20.04

## Steps to reproduce

1. see above
2. 
3. 

## Describe what you expected to happen

I expected a PDF to be created.

**Comment by CalebJohn** [comment]
You might want to try reporting this to on the [joplin snap repo](https://github.com/MrCarroll/joplin-desktop-snap), it appears to be a snap specific problem.

**Comment by MWH-Rookie** [comment]
Thank you. I did not know that there are different branches on github depending on the distribution channel.
