### ISSUE TITLE
Mobile: Undo Button doesn't responds in Beta Editor 

### ISSUE THREAD

**Issue by entrymaster** [laurent22/joplin#6374]
## Environment

Joplin version: 2.7.2 
Platform: Mobile/ Android, Development Build/Android
OS specifics: Android 11, 10

## Steps to reproduce

1. Enable Beta Editor from Configuration
2. Open any note in Edit mode
3. Start editing the note -> `Undo` Button will appear
4. On Clicking `Undo` Button nothing happens

## Screenshot

https://user-images.githubusercontent.com/55127997/162059142-0c26a55e-1c23-4917-9f6c-a87d1db4c45c.mp4

## Describe what you expected to happen
Undo action should be performed with Redo button appearing

**Comment by personalizedrefrigerator** [comment]
https://github.com/laurent22/joplin/pull/6325 should fix this!

I can't confirm this on iOS, but I can on Android.

**Comment by entrymaster** [comment]
No, it still persists.

**Comment by personalizedrefrigerator** [comment]
> No, it still persists.

I made some changes to [`CodeMirror.ts`](https://github.com/laurent22/joplin/pull/6325/files#diff-2f2e0f0ef4045aa30099226be7d8fe1fd6bf12aa44686b8f300a5101fab21fe2R4), so be sure to run `yarn run buildInjectedJs`!

If it's still not working, please try adding `try { ... } catch(e) { alert(e); }` around the `cm.undo()` call here:
https://github.com/laurent22/joplin/blob/f6e21e01808a0f7ef535c6613d0331d0ca95941a/packages/app-mobile/components/NoteEditor/NoteEditor.tsx#L253

I was getting a `cm is undefined` error. For me, changing
https://github.com/laurent22/joplin/blob/f6e21e01808a0f7ef535c6613d0331d0ca95941a/packages/app-mobile/components/NoteEditor/NoteEditor.tsx#L230
to `window.cm = ...` fixed the issue. Oops! I think it might also make sense to change this line:
https://github.com/laurent22/joplin/blob/f6e21e01808a0f7ef535c6613d0331d0ca95941a/packages/app-mobile/components/NoteEditor/NoteEditor.tsx#L239
