### ISSUE TITLE
The first time I synced, I lost all my notes

### ISSUE THREAD

**Issue by pengyuwei** [laurent22/joplin#6378]
The first time I synced, I lost all my notes
I've been using Joplin for a while, and I feel pretty good about it, and I'm going to replace Evernote with it.
Yesterday I tried the sync feature for the first time, I set up the WebDav environment, the MacOS desktop side started syncing, and everything seemed to be fine, so I opened the phone to sync, and after a while, I found that no notes appeared on the phone, but all the notes on the desktop side had been deleted!
I rushed to check the server and found hundreds of md files were there, but no matter what the phone side and the desktop side remained without any notes.

![454591649339600_ pic](https://user-images.githubusercontent.com/1535830/162331246-ff905a46-2eb7-4491-b1fc-bdb845332a78.jpg)
![454701649339851_ pic](https://user-images.githubusercontent.com/1535830/162331264-8d203f8f-8426-4b14-a323-28d3dbd6c5d7.jpg)
![454721649339862_ pic](https://user-images.githubusercontent.com/1535830/162331273-09287e68-d305-40d1-a2cd-5e1eda874209.jpg)

## Environment

Joplin version: 
```
Desktop: 
Joplin 2.7.15 (prod, darwin)
客户端 ID: 44f44c98c4b447c5b9c29bf08144f3d1
同步版本: 3
配置文件版本: 41
支持的密钥链: 是
修订: 8352e23
iOS: Joplin 12.7.1
```
Platform: MacOS 10.15.7 (19H1824) , iOS 15.3
OS specifics:  macOS Catalina, iPhone 7plus

## Steps to reproduce

1. import 300 notes from enex
2. Configure WebDav sync at address like: http://192.168.1.10/dav/files/username
3. sync. After the synchronization is done, I found that all files are being written to the root directory of dav without creating subdirectories.
4. create a joplin_sync folder on the server side, move all files to it, modify the client configuration, change the WebDav address to http://192.168.1.10/dav/files/username/joplin_sync, and set the same on the phone
5. resynchronize, at this time no problem occurred, at this time opened the phone synchronization
6. after a while, I found that all the notes on the desktop were deleted.

## Describe what you expected to happen

Don't delete my notes!

**Comment by kishaningithub** [comment]
I strongly feel implementing a "recycle bin" would be great for such problems.. in my mind a recycle bin is a special notebook which holds deleted notes and notebooks for a period of say 60 days before permanently purging it. The reason for deletion could be because of a manual deletion or a sync process going wrong as above. 

Was just able to see a live discussion on this in the community forum
https://discourse.joplinapp.org/t/trashcan/3998/22

It would be a great value add IMO

**Comment by kishaningithub** [comment]
notstale
