### ISSUE TITLE
Overabundanted requests for session produces 439 Too Many Requests 

### ISSUE THREAD

**Issue by bernd-wechner** [laurent22/joplin#6379]
I'm trying to debug another issue (https://github.com/laurent22/joplin/issues/6344) but am currently hamstrung with a Joplin client that will not sync.

In summary:

1. Backend is a Joplin Server (v2.6.14)
2. MS Windows Joplin client (latest version) works fine, syncs well.
3. Android client (latest version) works fine, syncs well
4. Linux appimage client (v2.7.15), generates masses of 439 errors
5. Linux CLI client (latest version) works fine, syncs well (except for resources which is the subject of https://github.com/laurent22/joplin/issues/6344). 

I this captured a sample trace of the sync comms for the Linux appimage client in a pcap file on the server using tcpdump. It is attached (redacted to remove passwords, emails and session user_ids. It can be opened in Wireshark and reveals how the client is issuing calls GET to /api/sessions again and again ad again. At first they reply with a user_id (always the same one) but in time rate limiting seems to set in at the server end.  

[sync_redacted.pcap.zip](https://github.com/laurent22/joplin/files/8448478/sync_redacted.pcap.zip)

In https://github.com/laurent22/joplin/issues/6344#issuecomment-1091367053, it seems [roman-r-m](https://github.com/roman-r-m) suspects that the client is not saving the session as it should (forgetting the first response). My suspiscion also is that the intent here is open a session (one call) and close it when done.

**Comment by laurent22** [comment]
The app will try to renew the session if it's expired. Maybe your server clock is not correct? Based on Joplin Cloud's log, there doesn't seem to be an issue with apps making many GET session calls.

**Comment by bernd-wechner** [comment]
That's a good lead thanks!

Up front seems unlikely to be server end as I have an Android and Windows client synching to same server without this issue. 

If you can point me with a link into the repo to the place where said decision is made, that will save me some time hunting it down. But not a crisis if you're as snowed under as I as I can in time trace it. I'm just a tad busy diagnosing the parent issue (https://github.com/laurent22/joplin/issues/6344) still.

**Comment by laurent22** [comment]
But most of these errors don't make that much sense for Joplin Server, so you might want to check also your reverse proxy config. Maybe try to sync with the server directly, without any reverse proxy, on a local network to verify.

**Comment by bernd-wechner** [comment]
Just tried, and it complains:

Invalid origin: http://joplinserver.lan:22300

I see that the server name is configured in the APP_BASE_URL configuration.

I see no evidence that this can take a list (which it should IMHO) so I reconfigured it for a test.

And as long as it is set to the whole URL (including the port) then it works and a I get a full complete sync.

BUT, all the errors still listed as well and these are neither reset by the full successful sync nor does the app provide a "retry all" option. There should really be a way to clear them.

AND, as stated the Android app and the Windows app work totally fine with the reverse proxy AND to best of my knowledge the Linux app did too for many many months with no known (recalled) change to the reverse proxy. So, although the test does implicate the reverse proxy the issue is far from completely understood AND I do need to have it work through that reverse proxy (again) as well or the utility of keeping Joplin synched at home, at work and one the road disappears.

**Comment by bernd-wechner** [comment]
OK, I found a cause and culprit. A spam filter was installed on the webserver that acts a reverse proxy, on March 25th. 

Removing that, everything works as it once did. And the timeframe aligns well with commencement of Linux sync issues (if memory serves).

The issue to solve at my end now is what particular config on that filter interferes and how, but remaining as mysteries that you may or may not have some insight into, is why said spam filter disables the Linux client only and not the Android or Windows clients. 

My lazy first, shallow supposition is that it may relate to the useragent header (only because it's conceivable the prime if not only difference between those platform clients). 

And there is one further bug to note. What I did is synch everything on the LAN link. Then went back to the WAN approach, created a new note with image on Android and synched and then tried to sync and go this header:

![image](https://user-images.githubusercontent.com/7296506/162615259-41cf6758-c595-45d1-b45c-e488be14da78.png)

I click View them now, and am taken to a page that shows one image that failed to download. That is great and what I was testing. So then I fixed the reverse proxy, removing the spam filter for now (till I work out what config is interfering) and went back to Joplin and clicked Retry. That worked fine and the image was downloaded. But the orange header remains and if I click View them now I am taken to the same page (which is in fact just Help > Synchronisation Status) and there are no errors on it (of course), everything is fine. But the orange header remains ;-).

I may have to blow the local config away and just sync down from server afresh.

**Comment by laurent22** [comment]
I think there's a bug with this orange header in that it's not removed after the items have been synchronised. If you restart the app it will probably go away.

**Comment by bernd-wechner** [comment]
Alas, tried that and it's still there. I don't mind blowing away the local data and resyncing from scratch. Did it once already during testing. Once I work out what spam filter rule killed this I'll put a note here.

**Comment by bernd-wechner** [comment]
Though a day later I tried and started it again and the orange header is gone.

**Comment by bernd-wechner** [comment]
Though oddly lower left is Cancel whirring endlessly. And aargh, looking at Wireshark I see it's this old problem as in cyclic api/sessions ... and the spam filter is off. So further drilling into these reverse proxy settings ...

**Comment by bernd-wechner** [comment]
Righto, found the reason for that. This causes and endless api/sessions call:

1. Configure the client to use http://server
2. Configure the reverse proxy/gateway to upgrade all http:// to https://

Doing so gets the client in a knot somehow. But simply configuring the client to use https://server or removing the upgrade from http to https makes the problem go away.

IMHO the client should be able to cope with a protocol upgrade, though it's a low priority in the scheme of things as correct configuration of the client works.

Will turn to finding the spam filter rule that kills this now.

**Comment by bernd-wechner** [comment]
Aaargh. I have time to diagnose this, I enable the spam filter again and all works ... annoyed. Unable to reproduce it I can't nail the rule. 

They are simple enough though and block all requests with a host header that is empty or "-", a useragent header that is empty or "-" and and useragent containing any of these regex strings:

- perl
- \{
- \}
- \/var\/
- \/tmp\/
- \/etc\/
- China.Z
- ZmEu
- Zollard
- gawa\.sa\.pilipinas
- Jorgee
- netscan.lekus.su
- pdrlabs.net
- massscan
- ip138.com
- nerd.host
- PetalBot
- Baidu
- Baiduspider
- Sogou
- YoudaoBot
- YodaoBot
- HaoSouSpider
- 360Spider
- YisouSpider
- thunderstone
- PageAnalyzer
- Netcraft
- 5118\.com
- MJ12bot
- majestic12\.co\.uk
- dotbot
- LSSRocketCrawler
- LightspeedSystems
- StatsInfo
- ips-agent
- TurnitinBot
- SlySearch
- ScoutAbout
- RPT-HTTPClient
- WebZIP
- Webclipping\.com
- webrank
- websquash\.com
- lwp-trivial
- AESOP_com_SpiderMan
- Zeus
- Cyveillance
- Lite\ Bot
- flunky
- Microsoft\ URL\ Control
- NAMEPROTECT
- NPBot
- aipbot
- WebFilter
- Indy\ Library
- SurveyBot
- Morfeus\ Fucking\ Scanner
- probethenet\.com
- digitalmole
- AhrefsBot
- linkfluence\.net
- Kraken
- datasift\.com
- DomainSigmaCrawler
- AdnormCrawler
- adnorm\.com
- OptimizationCrawler
- domainoptima\.com
- woriobot
- worio\.com
- zitebot
- coccoc
- coccoc.com
- Mnogosearch
- Synapse

and referrer header that matches and of these:

 semalt
- -seo
- darodar\.com
- makemoneyonline\.com
- rankings-analytics\.com
- D-SHANGZJ\.COM
- for-website\.com
- for-your-website\.com
- social-buttons\.com
- free-share-buttons\.com
- buy-cheap-online\.info
- 24x7-allrequestsallowed\.com
- domainsigma\.com
- for-your
- video--production\.com
- justprofit\.xyz
- hundejo\.com
- pizza-tycoon\.com
- pizza-imperia\.com
- buypillsorderonline\.com

and any source IP that matches any of:

- 123\.125\.71\.*
- 220\.181\.108\.*
- 202\.46\.*.*
- 180.76.15.*
- 185.10.107.*

Now my source IP can change of course, but has been stable for over a week not matching those.

I am scratching my head as only yesterday I am 100% sure, the problems cited here and in  https://github.com/laurent22/joplin/issues/6344 were real and demonstrable, I was watching them in wireshark and restarting the Joplin app and recording and watching and the problems were real and live, so I proved that LAN internal access worked (as per your suggestion) so moved to WAN access and studying the configs, saw a spam filter, disabled it and tried with the WAN access and all was good. 

And today, a mere day later I re-enable the self same spam filter, and it still works.

Anyone here by the name of Murphy? A ghost in the machine? Pulling my hair out.
