### ISSUE TITLE
Images missing depending on sync method

### ISSUE THREAD

**Issue by ftastisch** [laurent22/joplin#638]
### Operating system
- Windows
- macOS
- Linux
- Android
- iOS

### Application
- Desktop
- Mobile
(- Terminal not tested)

Depending on the sync method on different clients, embedded pictures are not shown.
The problem occured with sync between different devices, e.g. two computers and one mobile device (not sure though whether actually different client types must be involved):
- 1 desktop and 1 mobile client, sync via webdav: everything is working, embedded pictures are shown on both clients (but sync notifications on desktop client are shown, as an additional nextcloud client also syncs the notes folder)
- adding 1 desktop with nextcloud client I changed the sync method for this computer to file system, as the folder is synced by nextcloud. This client shows all notes, but embedded images are missing.
- Changing the 1st desktop client also to file system sync breaks image syncing to the previously working mobile device. Whether sync between desktop clients works is to be checked.

Do all connected devices have to use the same sync method?

**Comment by laurent22** [comment]
> Do all connected devices have to use the same sync method?

Yes, this is the only officially supported way to sync in Joplin. Adding a layer of indirection (from Joplin, to filesystem, to Nextcloud) can cause unexpected problems and is probably hard to debug.

If you can provide a way to replicate this bug consistently though feel free to comment here again.
