### ISSUE TITLE
Bold text behave incorrectly if it ends with a whitespace 

### ISSUE THREAD

**Issue by Sharar-Lykourgos** [laurent22/joplin#6380]
## Environment

Joplin version: Joplin 2.7.15
Platform: Linux
OS specifics: Fedora Linux 35 (Workstation Edition)

## Steps to reproduce

1. Write some text that ends with a whitespace.
2. Make it bold (including the whitespace).
3. Switch back and forth between this note and any other one.
4. the bold text will be replaced with normal text with "**" on both sides (the markdown equivalent)
![Bold Text Bug](https://user-images.githubusercontent.com/96591262/162418971-9a830126-2693-43c1-9cf9-7a770d75f5b2.gif)

Additionally, There are some screenshots of the dev-tool before and after switching notes which shows that the strong/bold tag has been replace with "**" down below.

1. Before switching 
![Dev mode Before Switching](https://user-images.githubusercontent.com/96591262/162419446-f22a20b3-d9ce-468f-8677-ed078e380e55.png)

2. After switching 
![Dev mode After Switching](https://user-images.githubusercontent.com/96591262/162419322-3fe90817-7c76-48cf-a6ca-0785d5a6956e.png)

## Describe what you expected to happen
The text should still be bold after switching notes.

**Comment by bishoy-magdy** [comment]
Duplicated: [#6288](https://github.com/laurent22/joplin/issues/6288) 

It's not a bug in Joplin. The markdown render rejects the end of space (at least character) You can also test this in different markdown editors.
And u can use `<b>text </b>` to deal with space.

**Comment by bishoy-magdy** [comment]
Duplicated: [#6288](https://github.com/laurent22/joplin/issues/6288) 

It's not a bug in Joplin. The markdown render rejects the end of space (at least character) You can also test this in different markdown editors.
And u can use `<b>text </b>` to deal with space.
