### ISSUE TITLE
On numbered list, if the sentence is too long, text wrapping doesn't work. 

### ISSUE THREAD

**Issue by saurabh2804** [laurent22/joplin#639]
### Operating system

- Linux

### Application

- Desktop

Please see if this shows up OK in your systems:
**Procedure**
* * *

    1. Pipette 1-100 μl into 1.5ml tube.
    2. Make up volume to 100 μl with ATL buffer.
    3. Add 10 μl proteinase K.
    4. Add 100 μl buffer AL, mix by vortexing.
    5. Incubate at 56°C for 10 minutes.
    6. Centrifuge briefly.
    7. Add 50 μl ethanol (100%), vortex. Incubate at RT for 3 minutes.
    8. Centrifuge briefly
    9. Transfer the entire lysate to Qiagen minielute column which is placed in a 2 ml collection tube. Centrifuge at 6000 g for 1 minute. Discard the flow through after centrifugation.
    10. Add 500 μl of AW1 buffer. Centrifuge at 6000 g for 1 minute. Discard the flowthrough tube.
    11. Add 700 μl of buffer AW2. Centrifuge at 6000 g for 1 minute. Discard the flowthrough tube.
    12. Add 700 μl of ethanol. Centrifuge at 6000 g for 1 minute. Discard the flowthrough tube.
    13. Centrifuge at full speed for 3 minutes to dry the membrane.
    14. Place column in a fresh 1.5 ml tube (doesn’t come with kit). Open the lid and let it dry at RT for 10 minutes.
    15. Put 20-100 μl of ATL buffer to the center of the membrane. Incubate for 10 minutes.
    16. Centrifuge at full speed for 1 minute.
* * *
In my system, point 9 goes out of the page. Exporting the note to PDF gives the same result. I am on version 1.0.103 of Joplin, using AppImage on Linux Mint 18.3

**Comment by laurent22** [comment]
Could you post a screenshot of how it looks?

**Comment by saurabh2804** [comment]
[Joplin.pdf](https://github.com/laurent22/joplin/files/2128272/Joplin.pdf)

![joplin-2018-06-22 21-22-55](https://user-images.githubusercontent.com/7777109/41786199-7cc96f1e-7662-11e8-9157-6e560a50dd65.png)

**Comment by saurabh2804** [comment]
Please take a look at the PDF that exporting note from Joplin created.

**Comment by laurent22** [comment]
You should remove the tab (or spaces) in front of the numbered list because it means it's being detected as code, and so the lines don't wrap properly.
