### ISSUE TITLE
Sync error: Master key is not loaded

### ISSUE THREAD

**Issue by JasonSanDiego** [laurent22/joplin#6392]
## Environment

Joplin version: 2.7.15
Platform: Windows
OS specifics: Windows 10 Pro 21H2

## Steps to reproduce
Unclear how to reproduce as it seems I'm stuck in a permanent error state.

## Details
I'm a longtime user of Joplin across Windows, Android and iOS. I started having issues with one Windows client around the time I migrated from one Windows user to another by copying my user directory from one to another.

Since then, I've been getting an error when syncing: Master key is not loaded - see log provided below.

The last time I paid attention to encryption settings, I just had to provide a password for each master key. Now I see in the encryption settings there is also a master password and it was saying I needed to set one (sidebar - master password vs master key terminology is a bit confusing).

I set one and I now have a checkmark and it says Valid. But there's still a red message below it: Your master password is needed to decrypt some of your data. Please click on "Manage master password..." to proceed. If I click the button, all I get is a dialog saying my master password is Valid and a link to change master password.

Meanwhile, down in the encryption keys area, I see a single key - the one Joplin is complaining about in logs. It shows Active and an X under Valid. When I enter the password, and click Save, the password disappears, but nothing further happens. There are some clues in the log, though (see below).

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/8460852/log.txt)

**Comment by laurent22** [comment]
Could you post a screenshot of your encryption config screen please?

**Comment by JasonSanDiego** [comment]
![image](https://user-images.githubusercontent.com/1314250/163752427-520140c5-1e3d-47dd-8563-88406ea85fde.png)
