### ISSUE TITLE
Import markdown file including images

### ISSUE THREAD

**Issue by jdckr** [laurent22/joplin#640]
### Operating system
- Windows

### Application

- Desktop

I tried to import a markdown file containing an image, but the image is not shown inside Joplin. Is this feature supported?

### Code
```text
# Test

![GitHub Logo](github-mark.png)
```

### VSCode
![image](https://user-images.githubusercontent.com/40456550/41779449-1b8a03d8-7632-11e8-9da9-27dae115b843.png)

### Jopling
![image](https://user-images.githubusercontent.com/40456550/41779464-239ed03a-7632-11e8-8407-af6a4a0420c6.png)

**Comment by laurent22** [comment]
You would need the full URL, eg:

    ![](https://github.com/jennybc/googlesheets/raw/master/internal-projects/logos/GitHub-Mark/PNG/GitHub-Mark-32px.png)

**Comment by jdckr** [comment]
I am talking about local images. I also tried 

```![GitHub Logo](file:///C:/temp/github-mark.png)```

 but that doesn't work either.

**Comment by laurent22** [comment]
`![GitHub Logo](C:/temp/github-mark.png)` seems to be work, but actually this syntax is not really supported since it's not portable. A better way would be to import the image directly (with the "Attach image" button).

**Comment by jdckr** [comment]
That did the trick, thanks!
Doesn't have to be portable as I am just working on a converter from Google Keep takeout to Joplin. At the moment I am converting to markdown, but to also transfer the labels/tags I think I will switch to enex anyway.
