### ISSUE TITLE
iOS Nextcloud sync - Network error even after installed the self-signed certificate on mobile device

### ISSUE THREAD

**Issue by cmalvi** [laurent22/joplin#6405]
## Environment

Joplin version: 12.7.1
Platform: iOS
OS specifics: 15.4.1 

## Steps to reproduce

1. Install the self-signed certificate of you private Nextcloud server
2. Install Joplin from App store
3. Configure Joplin for use with Nextcloud using as URL the one provided from the Files app in Nextcloud dashboard 
4. See "Network request failed"

## Describe what you expected to happen
Sync success

## Logfile

04-13T11:42:08: Synchronizer: "TypeError: Network request failed
(QICIETNE L ETRETE SV le| YNl [eE i T VA
FE55A22E-77CF-49B1-88FF-87AEAB2CEAOC/Joplin.app/
main.jsbundle:101:8201
(QICIETNE L ETRETE SV le| YNl [eE i T VA
FE55A22E-77CF-49B1-88FF-87AEAB2CEAOC/Joplin.app/
main.jsbundle:79:1257
k@/private/var/containers/Bundle/Application/
FE55A22E-77CF-49B1-88FF-87AEAB2CEAOC/Joplin.app/
main.jsbundle:79:500
callTimers@/private/var/containers/Bundle/Application/
FE55A22E-77CF-49B1-88FF-87AEAB2CEAOC /Joplin.app/
main.jsbundle:79:2653
value@/private/var/containers/Bundle/Application/
FE55A22E-77CF-49B1-88FF-87AEAB2CEAOC /Joplin.app/
main.jsbundle:38:3557
(QICIETNE L ETRETE SV le| YNl [eE i T VA
FE55A22E-77CF-49B1-88FF-87AEAB2CEAOC/Joplin.app/
main.jsbundle:38:674
value@/private/var/containers/Bundle/Application/
FE55A22E-77CF-49B1-88FF-87AEAB2CEAOC /Joplin.app/
main.jsbundle:38:2504
value@/private/var/containers/Bundle/Application/
FE55A22E-77CF-49B1-88FF-87AEAB2CEAOC /Joplin.app/
main.jsbundle:38:646

**Comment by frisodubach** [comment]
Seems similar to the issue I'm having (#5986), but I use certificates signed by Let's Encrypt.

**Comment by cmalvi** [comment]
Any news about?

**Comment by cmalvi** [comment]
No isn’t solved

**Comment by cmalvi** [comment]
No isn't solved

**Comment by cmalvi** [comment]
The issue is still present

**Comment by cmalvi** [comment]
Still present
