### ISSUE TITLE
Copy/Paste text from Microsoft OneNote inputs a picture

### ISSUE THREAD

**Issue by ScriptInfra** [laurent22/joplin#6407]
## Environment

Joplin version: 2.7.15
Platform: Tested on Windows 11 and MacOS

## Steps to reproduce

1. Copy text from Microsoft OneNote.
2. Paste text into a note in Joplin.

## Describe what you expected to happen

I expected the text to be pasted into Joplin as text, instead of a picture.

**Comment by ScriptInfra** [comment]
Still an issue.

**Comment by 5chi-3cun-4fen** [comment]
It is Onenote's problem. You may paste what you copy from onenote into notepad.
And then copy from notepad.

**Comment by ScriptInfra** [comment]
This remains an issue.

**Comment by 5chi-3cun-4fen** [comment]
It is onenote's problem and has nothing to do with joplin...

check this out

https://answers.microsoft.com/en-us/msoffice/forum/all/copy-and-paste-from-onenote-as-an-image-not-text/d77148a4-eef7-4940-aa8b-f56b610d5ebb

> Me too! This pasting into Notepad to get the text is a real problem. There must be a way to copy just the text, similar to the paste where you can select which formatting , source, destination, or plain text, you want. This problem comes up any time you go to paste into an application that understands "text with formatting" but doesn't allow the formatting to be stripped off as most Office applications do.
>
> I use Evernote mostly these days just because I can copy from Evernote to other applications, where OneNote makes that simple function almost impossible.
>
> OneNote would be my normal choice but this formatting issue keeps me a loyal Evernote user. Fix this and I'll renew my subscription to Office 365 for sure. Right now it's not guaranteed.
>
> Further research indicates that this is not a bug at all, at least not in OneNote. OneNote under Windows, can put both text and images on the clipboard at the same time. I did a quick VB app and can see this and work around it by clearing the image from the clipboard and leaving only the text.
>
> The target application is the one responsible for pasting either the text or the image into the current document. Unfortunately, most applications choose the image (DIB) rather than the text and this is the issue, not OneNote, which after all is just trying to be helpful.
>
> Things like Notepad are unable to copy/paste images so they work only with text. Office applications give options when you paste. Most other applications just paste the image assuming I guess that the image is more important.
>
> OneNote needs a "Copy" process similar to the "Paste" process. The user selects what format (if both are possible) to copy and although this introduces the occasional extra step, it would cure the issue.
