### ISSUE TITLE
Impossible to select tag on web clipper (Vivaldi for Windows)

### ISSUE THREAD

**Issue by christubuntu** [laurent22/joplin#6408]
In Vivaldi for Windows, I can't choose tags by clicking on that down arrow.
However, doing same thing in Chrome works fine. So idk if this is a Joplin related issue or if I have to raise in the Vivaldi forum. Lets me know. 

Steps
1. Open Vivaldi for Windows
2. Go to https://www.videohelp.com/software/PotPlayer 
3. Open joplin extension icon, scroll down to tags
4. Press Down arrow to select tags

What happens= Nothing 
https://user-images.githubusercontent.com/55885756/163346447-5107e45e-3cf3-42b1-ae93-8d55d17c6581.mp4

Expected behavior= List of tags should pop up

Joplin for Windows 10 21h2
Joplin 2.7.15 (prod, win32)

Client ID: 6694762c366c48e9be0d4e0ac1f63493
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 8352e23

**Comment by laurent22** [comment]
Chrome had the same bug not long ago, but they fixed it. So my guess is that Vivaldi is on an older version of Chromium and need to upgrade their framework. Perhaps something you can bring up to their forum, although I don't think they are very responsive in general.

**Comment by christubuntu** [comment]
Still not fixed. The Vivaldi version I'm using (5.2) is based on Chromium 100.0.4896.81.
