### ISSUE TITLE
multiple profiles

### ISSUE THREAD

**Issue by Jipyc** [laurent22/joplin#6411]
👉 Please follow one of these issue templates:
- https://github.com/laurent22/joplin/issues/new/choose

When I switch to the new profile the langage is "english" and not mine (french) and when I come back to the main profile the langage is yet in english and not french.
⚠️
The GitHub issue tracker is for **bugs** and **security issues** ONLY. For feature requests and support, please use the forum:
https://discourse.joplinapp.org/
⚠️

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by kamalbuilds** [comment]
Hi , I am working on this
