### ISSUE TITLE
Sync problem with WebDav

### ISSUE THREAD

**Issue by Ademyan9** [laurent22/joplin#6413]
Hi everyone,

I use Joplin on my laptop and my phone. It worked for a week and since then they don't sync together anymore. My target synchronisation is WebDav.

When I try to sync on the computer, it says :

Last error: Error: PUT .resource/52a8fc48addd48918dd5ce6b8eeaf5ce: Unknown error 2 (413): <html> <head><title>413 Request Entity Too Large</title></head> <body bgcolor="white"> <center><h1>413 Request Entity Too Large</h1></center> <hr><center>nginx/1.14.2</center> </body> </html>

On the phone, it says nothing.

When I check the sync it says : Succes ! Synchronisation configuration appears to be correct.

Here is my sync status on my comptuter : 

Attachments

Not downloaded: 0
Downloading: 0
Downloaded and decrypted: 3
Downloaded and encrypted: 0
Created locally: 44
Error: 0

Sync status (synced items / total items)

Note: 41/41
Folder: 17/17
Resource: 46/47
Tag: 0/0
NoteTag: 0/0
MasterKey: 0/1
Revision: 95/109
Total: 199/215
 
Conflicted: 0
To delete: 0

**Here on my phone but the conflict is different :** 

Attachments
Not downloaded: 0
Downloading: 0
Downloaded and decrypted: 43
Downloaded and encrypted: 0
Created locally: 3
Error: 0

Sync status (synced items / total items)
Note: 46/46
Folder: 18/18
Resource: 46/46
Tag: 0/0
NoteTag: 0/0
MasterKey: 0/1
Revision: 144/144
Total: 254/255
 
Conflicted: 1
To delete: 0

Does anyone know how to fix it ?

Thank in advance

**Comment by dpoulton-github** [comment]
> A 413 HTTP error code occurs when the size of a client’s request exceeds the server’s file size limit. This typically happens when a client attempts to upload a large file to a web server, and the server responds with a 413 error to alert the client.

Check if your provider has set a low file size limit.
