### ISSUE TITLE
Android sync to DropBox does not complete configuration

### ISSUE THREAD

**Issue by neiljthomson** [laurent22/joplin#6417]
I have Joplin 2.7.15 working on 2 win 10 boxes using dropbox for sync
Attempted to install/sync Joplin on Android/Google Pixel 4A/5G with latest OS, etc.
Cannot sync to dropbox on android.
 - Following directions, select "dropbox" in "Sync Target" dropdown, return from config and hit Sync (which is supposed to give me instructions on completing sync). 
 - Returns me to config, where Sync Target is back to (none).

**Comment by laurent22** [comment]
Make sure you save your settings after selected Dropbox. It's the floppy disk icon on the top of the screen.

**Comment by neiljthomson** [comment]
Thx. 

 

I just noticed that earlier today. NOT obvious (small icon, odd location, not standard practice for save).

 

Neil Thomson
QueryVision
 <blocked::http://www.queryvision.com/> www.QueryVision.Com
T-613.220.9929
***@***.*** ***@***.***>
