### ISSUE TITLE
FR: Webclipper: Add where it was clipped from

### ISSUE THREAD

**Issue by gerroon** [laurent22/joplin#642]
Hi

It would be nice if the clipper actually puts a special line where it puts the original url of the content. It could be at the bottom, at the top, somewhere it exists so the source is clear. Sure one can edit the page but I think for convenience sake this should be provided. 

thanks

**Comment by laurent22** [comment]
The source URL is saved in the Joplin database, but currently not visible in the desktop app (in the CLI and mobile app it is).

**Comment by gerroon** [comment]
Sure but it is not use to us if it is hidden :) Anway I hope to see it in the notes as well.

**Comment by penguinsam** [comment]
As far as I know the URL was kept in the metadata.

**Comment by foxmask** [comment]
Yes, when you display the metadata from the android phone you can see it too

**Comment by laurent22** [comment]
Closed as duplicate
