### ISSUE TITLE
Desktop - no sync at exit

### ISSUE THREAD

**Issue by sylock** [laurent22/joplin#6420]
I have the cloud sync. From the desktop app (linux), if I create a note and exit before the next sync (every 5 min), then the note is not synchronized until I open again the app (there you have an automatic sync at startup).

It can lead to lost of data if you don't pay attention or confusion on a non-sync item and search from which device it was not synced.

## Environment

Joplin version: 2.7.14 (snap)
Platform: PopOS! 21.10

## Steps to reproduce

1. create a note
2. quit the app before the next sync
3. go to another device where you have Joplin
4. force a sync from that device
5. see that the last note written from the other device is not synchronize

## Describe what you expected to happen
As you have an automatic sync on startup, there should be an automatic sync on exit.

**Comment by Daeraxa** [comment]
It already performs a "push" sync on note change without waiting for the sync interval timer, it just isn't completely instant.

**Comment by sylock** [comment]
ok. I didn't see that because in my test I quit immediately after creating the note. The push is very nice then. But I still would add a check at the exit. That's what you have in any app with an auto save, like the Google doc etc. When you try to quit while the document is not entirely synced, you get a blocking popu asking you if you want to lost the changes.
I know it is a bit different here since you don't really loose the data. It is written locally. But as soon as you are working with a multi devices setup, I would find it useful for the user to have the choice between quitting without the sync or waiting for the sync to be completed.

I also would like to mention that I think that the mentionned use case is not completely theorical. In an everyday scenario, sometimes you open quickly the note taking app, take the note, and quit immediately to do something else. And you don't take the time to check if the sync is finished or not.

**Comment by Daeraxa** [comment]
In which case it needs to be requested as a feature on the forums as the github issue tracker is only used for bug reporting and the application is working as designed. The #features category is the one that should be used.
