### ISSUE TITLE
Mixing bullet lists and checklists in same note corrupts bullet lists

### ISSUE THREAD

**Issue by mcgroarty** [laurent22/joplin#6423]
## Environment

Joplin version: 2.7.15 (prod, darwin)
Platform: macOS
OS specifics: macOS 12.3.1 (Monterey)

## Steps to reproduce

1. Enter the following markdown while in the split view (also included as [sample-text.txt](https://github.com/laurent22/joplin/files/8501996/sample-text.txt) in case GitHub parses the contents):

`
Testing Joplin. Let’s see how it does with the core behavior of note-taking

Let's try some outlines.

- Bullet
    - Further
- Lesser
    - Greater again
        - More still
    - Back again
- Checklist too
    
- [ ] Checkbox list next
- [ ] Also checkbox
- [x] Checked checkbox
- [ ] Unchecked checkbox
`

2. Observe that the preview on the right appears as expected, with a bulleted list followed by a set of checkboxes (image-1)
3. Click the "toggle editors" Markdown button in the top right 
4. Observe that the bulleted list has been converted into both bullets and checkboxes (image-2)
5. Toggle any checkbox
6. Return to the Markdown view with the "toggle editors" button
7. Observe that Markdown checkbox brackets have been peppered throughout the bulleted list (image-3)

image-1: <img width="860" alt="image-1" src="https://user-images.githubusercontent.com/2642531/163723079-18ca1cb0-949b-40af-9a13-d95efd5976b8.png">

image-2: <img width="515" alt="image-2" src="https://user-images.githubusercontent.com/2642531/163723081-bbaa81f6-071a-462c-84ef-760d82814853.png">

image-3: <img width="860" alt="image-3" src="https://user-images.githubusercontent.com/2642531/163723085-5aa0a6b3-b614-4842-aa67-94842bc37ad0.png">

**Comment by Daeraxa** [comment]
Its a currently known limitation of the richtext editor see - https://joplinapp.org/rich_text_editor/

> All items in a list must be of the same type, so for example all checkboxes, or all bullet points. If you require two different types, you should create two different lists separated by a horizontal rule or similar.

I actually raised the same issue once before - https://github.com/laurent22/joplin/issues/4286

There is a general idea to improve integration of the richtext editor with Joplin to try to iron out some of these limitations or incompatibilities.

**Comment by mcgroarty** [comment]
Ah, thank you. This is a duplicate then. I tried searching before submitting, but didn't hit on the right terms.
