### ISSUE TITLE
Joplin Continuous Integration #5

### ISSUE THREAD

**Issue by milotype** [laurent22/joplin#6428]
Can someone please check:
https://github.com/milotype/joplin/actions/runs/2160180650

I'm not a programmer and don't understand the problem, nor how to solve it ...

**Comment by roman-r-m** [comment]
Why do you even need CI, especially if you're not a programmer? I suspect you don't actually need it, then you can just ignore this error.

**Comment by milotype** [comment]
@roman-r-m OK, thank you for your answer.
So I'll delete my current fork _https://github.com/milotype/joplin_ and will fork _https://github.com/laurent22/joplin_ again, so I'll obtain a fresh/current state of the project.

**Comment by roman-r-m** [comment]
> So I'll delete my current fork _https://github.com/milotype/joplin_ and will fork _https://github.com/laurent22/joplin_ again, so I'll obtain a fresh/current state of the project.

It may be that you'll see the error again. Just ignore it. I think you could delete `.github/workflows/github-actions-main.yml` and it should disable the CI but then when raising merge requests you'll need to be careful to not include this deletion.

**Comment by roman-r-m** [comment]
Oh actually, looks like it's even simpler than this!
In your repo go to "Actions - Joplin Continuous Integration" and you can disable from there:
![image](https://user-images.githubusercontent.com/995612/164311643-723a85e7-d896-4a94-b258-6b5606c1a0bd.png)
