### ISSUE TITLE
Notes are sporadically moved into a notebook 'Conflicted' when editing ( sometimes even disappear )

### ISSUE THREAD

**Issue by toddler-king** [laurent22/joplin#6429]
**Steps To Reproduce:**
This happens sporadically ( not easy to reproduce ) but happens repeatedly.
In what follows I try to describe the circumstances which seem to be correlated to the problem.

**First irregularity:**  
When editing a note, the note suddenly seems to disappear.
Scrolling down to sidebar I notice a folder in red called 'Conflicted'.
The notes have been moved there. 
On one occasion they seemed to have disappeared.
I also recall that on ( almost? ) every occasion this happens when I mistype something and my fingers slip onto some other benign key ( not F keys ) and also when attempting to re-order the note by clicking and dragging with the mouse. 
Even then, such benign user input should not result in the notes being conflicted as I make sure that the device I am currently working from ( a desktop ) is the only one editing the notes and that everything is properly synced before I start my edits ( see details of my setup below ).
My notes do contain a lot of KaTeX and some images as well as text and code inserts.

**My sync setup:**
Under 'Tools ->Options -> Synchronization -> Synchronization Target', 'File System' has been selected 
Synchronization is to a virtual drive from 'pCloud'. 
I have three devices using Joplin ( two desktops and a laptop ).
I always make sure that only one device is connect to 'pCloud' and that Joplin is open and in use on one location only.

**Second irregularity :**
Also sometimes when syncing manually ( initiating a 'sync' by clicking on the 'sync' button ) an ERROR message appears.
As it happens very quickly and ( apparently ) spontaneously, and I have so far not been able to reproduce the condition at will I can't report the ERROR type or messages. It appears that when this happens several ERROR messages appear, one per file that is placed into the red 'Conflicted folder'. 
Over 99% of the time the synching occurs without problems.
Even if this were a networking problem, this should not result in Joplin deeming a note as conflicted and moving it into the 'Conflicted' folder arbitrarily without some sort of dialogue or feedback with the user.
I.E. one should expect to see the ERROR messages BUT not the action of moving notes into 'Conflicted'.
Recall that I am the only one using the service and always make sure notes are being edited from one device with Joplin exited and pCloud logged out on the other device

**Further notes on usage:** 
As a remedy I tried the 'Delete local data and re-download from sync target' to re-download everything from the pCloud drive onto the local Joplin repositories ( on both devices I sue ).
When completed suddenly multiple copies of the 'disappearing' notes appeared in the relevant 'Notes list'.
They appear to have been 'saved' in various stages of completion / edit...sort of like frozen snapshots at the instance the erratic behaviour occurs.
Despite re-downloading from the sync target ( my pCloud drive ) the irregular behaviour re-occured.

**Environment:**

pCloud v1.9.9 on both devices

Joplin:
Joplin version on both devices ( from About Joplin ): 
Joplin 2.7.15 (prod, linux)
Client ID: 567eaa1e41e444b5955a58657a862b7d
Sync Version: 3
Profile Version: 41
Keychain Supported: No
Revision: 8352e23

**Platform 1 ( IBM-PC clone workstation case ):** 
Output from  `lsb_release -a` command below
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
The installation is 64 bit

**Platform 2 ( IBM-PC clone Lenovo laptop ):** 
Output from  `lsb_release -a` command below
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
The installation is 64 bit

NOTEWORTHY: I am throwing this in as an extra observation.
The two devices mentioned above ( the workstation and the laptop ) have their clocks on different time-zones ( due to my traveling with the laptop ).

**Comment by CalebJohn** [comment]
Are you using webdav with pcloud? Because [pcloud is not supported](https://github.com/laurent22/joplin/blob/360293949c2230f066d39f1218dd017e003fd149/readme/faq.md#the-following-webdav-hosts-are-not-supported). If you're using filesystem sync then the timezones could be an issue (but I think they shouldn't be)

**Comment by toddler-king** [comment]
Hi thanks for the feedback.
Much appreciated.
I am just using pCloud as it comes out of the box in Ubuntu.
I have been using Joplin for the last 18 months and I have used it with
pCloud on 4 devices ( Win10, Win7, 18.04 and 20.04 ) without any problems.
I don't insist on using pCloud. I'm under pressure on some other project (
so not much time for distractions ), therefore if something else is known
to work, I'd be grateful if you could point me in the right direction.
As long as I can keep my notes and continue working with Joplin.
I understand Joplin has introduced its own sync service?
Much appreciated
Reza

P.S.: If there is anything else on my side, I'm quite willing to do to help
you out to figure out the problem and/or improve Joplin

Am Di., 19. Apr. 2022 um 10:46 Uhr schrieb Caleb John <
***@***.***>:

**Comment by CalebJohn** [comment]
Just to clarify, how have you set up the sync settings? Filesystem or WebDav? You can check under Tools->Options->Synchronization.

Personally I use [Joplin Cloud](https://joplinapp.org/plans/) for syncing. It should be the most reliable.

**Comment by toddler-king** [comment]
Hi there,

Once again thank you for your reply and follow up.
Under 'Tools->Options->Synchronization-> Synchronization target' ,  I use
'Filesystem' ( not the 'WebDav' setting ).
My rationale was that since the 'pCloudDrive' appears as a folder in my FS
the 'Filesystem' option should be used ( which has worked fine in the 1.5
years of my Joplin usage...that is until recently ).

Let's say that there are two issues here:
1.) The main one was to inform you of something irregular I observed,
hoping to resolve my problem as well as help the community improve Joplin (
if one exists ) .
2.) The other was to find out what alternatives I have ( don't like
interrupt my work and migrate my notes yet once again ). The Joplin Cloud
option sounds interesting, thanks for the tip.

At any rate thanks and let me know if you need anything on my side.
Thanks for your work!

R.M.


Am Di., 19. Apr. 2022 um 22:03 Uhr schrieb Caleb John <
***@***.***>:

**Comment by CalebJohn** [comment]
I was re-reading your initial post (trying to find clues about your problem), and I noticed that you had already specified that you use the filesystem sync. Sorry to make you repeat yourself, I missed it on the first read.

If you haven't switched away from your current sync yet, I suggest you install the "Conflict Resolution" plugin. It adds an option to view conflicts side-by-side. This will be helpful to tell us where the conflict is in your notes (or if the conflict is in the metadata). You can install it under Tools->Options->Plugins, and then search for it by name. When there is a conflict (in the Conflicts folder) you can right click on the note name (in the notelist), and select "Resolve Conflict". This will popup the dialogue.

**Comment by toddler-king** [comment]
Thanks again for the tip,
I am a developer myself but hadn't had much time to tinker with Joplin (
mostly focussed on just using it ) .
I always wondered where the side-by-side note comparison capability was.
I installed the Conflict Resolution plugin ( Thank You ).
Much appreciated.
Kind regards
RM


Am Mi., 20. Apr. 2022 um 10:22 Uhr schrieb Caleb John <
***@***.***>:
