### ISSUE TITLE
FR: Realtime Markup Formatting

### ISSUE THREAD

**Issue by armaccloud** [laurent22/joplin#643]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile

### Request Details
This request is for the ability for realtime markup formatting, which would make it possible to only use 1 layout for writing notes and make the application even more accessible for people who don't like using or even seeing markup code on their screen.

You can see what I mean by watching the demo video from [Typora](https://typora.io/).

**Comment by laurent22** [comment]
Closed as duplicate
