### ISSUE TITLE
iOS does not work synology WebDAV Sync 

### ISSUE THREAD

**Issue by cache9527** [laurent22/joplin#6433]
## Environment

Joplin version: 2.7.15(win) / 12.7.2(iOS)  2.7.2(Android)
Platform: Windows, Android, iOS
OS specifics: Win10 /iOS 15.4.1/iOS15.2.1/iOS13.5/Android

1.Win client  work fine with WebDAV
2.Android app work with WebDAV
3.iOS app work with WebDAV (ip access)

does not work  https://mydomain.com:5006/joplin or http://mydomain.com:5005/joplin

**"network request failed"**

**Comment by JBBBB** [comment]
Try using the IP address of your Synology instead of its hostname.  It worked for me.

I was having a similar problem.  I reinstalled my WebDAV server.  The macOS desktop app worked fine, and a different iOS app (FE File Explorer) worked fine as well.  Using IP address fixed it.

**Comment by cache9527** [comment]
My router runs ddns,ip address will be change in few days.
windows and Android client works fine.

**Comment by gotoorder** [comment]
same problem
