### ISSUE TITLE
JoplinCloud: Could not find Stripe default billing portal configuration 

### ISSUE THREAD

**Issue by Wenzel** [laurent22/joplin#6438]
Hi,

I'm reporting an issue on my JoplinCloud account.
I wanted to manage my subscription and update the billing info, but I ended with this screen:

From
![Capture d’écran de 2022-04-22 08-44-43](https://user-images.githubusercontent.com/964610/164625757-5c6d4914-4a1f-4b60-8707-669b1d4b06de.png)

![Capture d’écran de 2022-04-22 08-44-47](https://user-images.githubusercontent.com/964610/164625683-346495fd-b394-433d-bfc4-85c793a4be4f.png)

Can you confirm the issue ?

Thanks !

**Comment by laurent22** [comment]
Hello this is now fixed, please give it another try.
