### ISSUE TITLE
Translation in Command palette

### ISSUE THREAD

**Issue by milotype** [laurent22/joplin#6440]
1. Several strings do not translate allthought translated in the .po file
2. One string cannot be translated, because it is missing in the .pot file

## Environment

Joplin version: 1.7.15, revision: https://github.com/laurent22/joplin/commit/8352e23bdf2054b7eb225d53ee4d2fa6b17fe44f
Platform: macOS
OS specifics: macOS 10.11.6

## Steps to reproduce

Please review the attached screenshots.
![Command palette 1](https://user-images.githubusercontent.com/43657314/164712093-ec315aab-c48a-4d5b-a24c-944c53dda25b.png)
![Command palette 2](https://user-images.githubusercontent.com/43657314/164712106-af8393ca-e81e-4f79-8976-351ec1c88e31.png)

**Comment by CptMeetKat** [comment]
Looking into this
