### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by milotype** [laurent22/joplin#6442]
1. Several strings do not translate allthought translated in the .po file

## Environment

Joplin version: 1.7.15, revision: https://github.com/laurent22/joplin/commit/8352e23bdf2054b7eb225d53ee4d2fa6b17fe44f
Platform: macOS
OS specifics: macOS 10.11.6
Steps to reproduce

Please review the attached screenshot.
![Create Notebook](https://user-images.githubusercontent.com/43657314/164727939-a2c3514b-6894-4a79-8317-e2b06f4c4dae.png)

**Comment by milotype** [comment]
Sorry, I forgot to mention, that this is a Croatian translation issue …

**Comment by laurent22** [comment]
All these strings are translatable so it should work from the next version, as long as the translation has been provided.
