### ISSUE TITLE
Desktop: Main Window can not display

### ISSUE THREAD

**Issue by JaedongLee** [laurent22/joplin#6449]
## Environment

Joplin version: 2.7.15
Platform: Windows 10
OS specifics:  Version 10.0.19044 Build 19044. Two Displayer

## Steps to reproduce

1. click "Joplin" icon

## Describe what you expected to happen

display the main window

## Logfile

![joplin bug](https://user-images.githubusercontent.com/25265598/164964469-668dfb22-1c09-4957-9bea-eb1a5fe60a5a.gif)

**Comment by graphit0** [comment]
Hi there, please make sure that the Joplin windows isn't on a second monitor and possibly reinstall the app.

If that doesn't help, I invite you to post this issue to our forum in support section, so more people could investigate the issue in better detail.

Cheers!
