### ISSUE TITLE
FR: Date function - Journaling/Diary

### ISSUE THREAD

**Issue by armaccloud** [laurent22/joplin#645]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

### Feature Request
It would be nice if Joplin gets the option to select a date for which the note has been taken.
For the purpose of journaling & keeping a diary, it would be nice if you can find & sort notes in a notebook based on its entered date.

There is the possibility to add a date to the note using the date button & the possibility to add a date to a ToDo, but they both don't cover the functionality for keeping a diary.

**Comment by foxmask** [comment]
except for the sorting of notes, I think that those issues expect the same :) #293 #282

**Comment by armaccloud** [comment]
Hi @foxmask,

Thanks for looking into this; partially, yes. From what I see in these other issues, they ask for functionality on the existing date fields (creation/modified date).

This request is for journaling purposes, for which the ability to (manually) choose a date would be the first requirement. Today I could be making journal entries for happenings from last week (an entry per day) but the creation/modified dates would only show today. So I would need a field in which I can set the date for these days.

Maybe the most elegant solution would be if the creation date can be changed manually?

**Comment by foxmask** [comment]
@armaccloud I understood. 

An OffTopic question (curiosity:) Do you publish your notes online once you made them ?
The way you use joplin seems to be for preparing blog posts before publishing them.

**Comment by armaccloud** [comment]
@foxmask 
That's an interesting idea and I think it could have good use for that. However I don't; it's for personal journaling (travel mostly) :)

But your question got me thinking... I migrated to Joplin from Nextcloud Notes (for notes) & Lifeograph (for journaling). Lifeograph has this method (date-selection-based note taking) as a standard. However, come to think of it, in Joplin it might be just as good to do journaling in chunks of months or even years within one note if a TOC function would be available (#478 & #263).

**Comment by foxmask** [comment]
@armaccloud I see. 
> That's an interesting idea and I think it could have good use for that

I thought about a way to publish blog post once an article is made in joplin.
It's easy to do by using some blog services like tumblr or [pelican](https://blog.getpelican.com/).
Automate things is an obsession (because I made a [project](https://github.com/push-things/django-th) that does that with many services and implementing that for joplin would be fun:)

**Comment by laurent22** [comment]
@armaccloud, setting the note time currently is not possible in the desktop app although I planned for it almost from day one (there's a `user_updated_time` property for this purpose, so I'd just need to give access to it from the GUI). Alternatively, for now, you can title them with the date and sort the notes by title - eg. "2018-06-27 My note".

Regarding the TOC, it's also not possible. In the meantime, one solution is to create one note that link to all the other notes and serves as a TOC. To link to a note, you can right-click on it (in the list), then click on the "Copy as Markdown link" item. Then you can paste this link in another note and use this to build a custom TOC.

**Comment by laurent22** [comment]
> I thought about a way to publish blog post once an article is made in joplin.
> It's easy to do by using some blog services like tumblr or pelican.

I've been thinking about this too as I use Joplin to maintain various web pages. Currently there are several ways to export notes, perhaps there could also be something like "Export website" when you right click on a notebook and that would generate all the required directories and HTML files? I'm not familiar with Pelican but if you have any suggestion, please post here.

**Comment by foxmask** [comment]
You are right . I forget the existing functionalities. As soon as I saw the possiblities offered by the webclipper I did not see anything else (like when you fall in love :D) and try to link services related with notes creation.
Export notes for pelican could be nice but it's not an emergency request compared to others issues.
And I would have wanted to do it myself to contribute to joplin :) But i'm not able to do it now.
And to avoid to be offtopic open another issue for that.

**Comment by laurent22** [comment]
Actually, come to think of it, the creation of a website from Joplin notes could already be automated using the command line tool. It's possible to export the relevant notes to Markdown files, then it's only a matter of building the website with a static site generator like [Hugo](https://gohugo.io/).

**Comment by foxmask** [comment]
Ok. So a couple of lines of code to add the properties expected by each blog engine to be able to generated the html page will be enough

**Comment by armaccloud** [comment]
@foxmask 
Looks like interesting projects you are doing. I'm curious where it will go for Joplin.

@laurent22 
Thanks for the info. I will use the workaround and wait for the user_updated_time option to be included at some point.

**Comment by IpeTek** [comment]
Without knowing if it is possible to implement in Joplin or not, I here reference two apps and two ways of sorting notes in a calendar view I found very easy to use, previously. One is an add-on to MS OneNote the other a diary app by an indie dev.

OneNote notes is a cal view: https://getonetastic.com/onecal
Diarium by Timo Partl (on the same page as the WorkingHours): https://timopartl.com/?app=WorkingHours

**Comment by armaccloud** [comment]
Hi,
This functionally was indicated as already present but it only had to be made visible in the ui?
I'm still using the workaround of putting the date in the subject but it would be nice if the application would support this diary function.

**Comment by laurent22** [comment]
This has been available on desktop for a while (click on the "i" button).

**Comment by armaccloud** [comment]
From your earlier remark I thought this would be the user-defined time field.
The two fields are _updated_ and _created_ dates. So the solution is to use the created date for this purpose?

**Comment by laurent22** [comment]
These two fields are user-defined ones. By default they are set to the time when the note was created or updated, but you can set it to something else.

**Comment by armaccloud** [comment]
Great, thank you Laurent!
