### ISSUE TITLE
Spell Checker is not working in

### ISSUE THREAD

**Issue by brandontan** [laurent22/joplin#6453]
Joplin version: Joplin 2.7.15 (prod, darwin)
Platform: Mac OS Monterey 12.3.1
OS specifics: 

## Steps to reproduce

Please see screen recording 

https://cln.sh/1CYyNH

## Describe what you expected to happen

Wrongly spelt words should be underlined.

**Comment by CalebJohn** [comment]
The spell checker is not supported in the markdown editor (yet). You can enable spell checking in the markdown editor by switching to the BETA editor (Tools -> Options -> General -> 
Enable spell checking in Markdown editor? (WARNING BETA feature)), but fair warning that it sometimes has issues with home/end behaviour.

This is a limitation of the editor that Joplin uses for markdown. It will eventually get replaced.

**Comment by Speculate7348** [comment]
> The spell checker is not supported in the markdown editor (yet). You can enable spell checking in the markdown editor by switching to the BETA editor (Tools -> Options -> General -> Enable spell checking in Markdown editor? (WARNING BETA feature)), but fair warning that it sometimes has issues with home/end behaviour.
> 
> This is a limitation of the editor that Joplin uses for markdown. It will eventually get replaced.

omg thank you, this worked fine.
