### ISSUE TITLE
search unreliable, doesn't seem to find partial matches

### ISSUE THREAD

**Issue by aleqx** [laurent22/joplin#6455]
I'm trying to migrate from Evernote to Joplin. I have a note titled "Capacitors for Samsung monitors". Inside that note the body text also has lots of occurrences of the word "capacitor". If I type "cap" in the search box, it doesn't find this note at all. If i type "capacitors" it does find it. I'm hoping this is a bug ... or else the find feature isn't that useful for me (I have thousands of notes that I'd like to partially match search on).

In fact, searching for "cap" finds only 2 notes, both where the string "cap" is matched inside the body text, one with a full match on the word `M5G.CAP` and the other on partial matches on the word `badcaps`.

Evernote finds 43 notes, with the string "cap" partially matched in both titles and body, on every string, as I expected (e.g. "capping" etc).

Evernote and Joplin have the same notes (imported from enex).

Joplin 2.7.15 (prod, win32)
Client ID: <snip>
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes
Revision: 8352e23

**Comment by Daeraxa** [comment]
https://joplinapp.org/help/#searching

By default it uses full text searching, if you need basic search then you need to add wildcards or swap to basic mode i.e. `cap*` or `/cap`

Curious that it managed to find `badcaps` though

From the above link

> For example, searching for cat will return all the  notes that contain this exact word. Note: it will not return the notes  that contain the substring - thus, for "cat", notes that contain  "cataclysmic" or "prevaricate" will not be returned.

> One drawback of Full Text Search is  that it ignores most non-alphabetical characters. However in some cases  you might want to search for this too. To do that, you can use basic  search. You switch to this mode by prefixing your search with a slash /.  This won't provide the benefits of FTS but it will allow searching  exactly for what you need. Note that it can also be much slower, even  extremely slow, depending on your query. | /"- [ ]" - will return all the notes that contain unchecked checkboxes.

You can also use goto anything for a quick search (ctrl + p) which will match "cap" to "capacitors"

**Comment by aleqx** [comment]
I see. Thanks for pointing that out. I wasn't expecting in this day and age for real-time search to not match partially, hence why I didn't read docs to find out if I'm doing something wrong.

It's curious that ctrl+p search and the general search box use different search syntax. In fact, I wonder why use two search features in the first place.

p.s. Perhaps "badcaps" is matched because you bound on known words like "bad" even when word boundaries don't exist?

**Comment by Daeraxa** [comment]
Goto anything is meant to be a quick way of jumping between notes, notebooks, tags etc. whereas the "full" search is designed for far more complex queries and filters to be made.

The reason for the full text search is mostly speed related (although personally I've never noticed the "basic" search to be particularly slow).

**Comment by ferrlen** [comment]
I must say I agree with aleqx, it's confusing for newcomers to have full matches in the search box, I think most new users would expect it to search for partial matches. I also thought the search was broken at first. I think it'd be a good idea to have the *goto* search bar by default instead of the current search bar, and let the user change this in a menu if they want to

**Comment by koppor** [comment]
@ferrlen Alternatively, one can use <kbd>Ctrl</kbd>+<kbd>P</kbd> to get a nice realtime fulltext search.
