### ISSUE TITLE
Joplin leaks private info despite end-to-end-encryption enabled

### ISSUE THREAD

**Issue by aleqx** [laurent22/joplin#6456]
I was looking for a true e2ee of all data. Joplin claims it uses e2ee but in fact leaks important private info. I enabled e2ee and then checked the files that it uploads. The following fields are not encrypted:

- created time
- updated time
- latitude
- longitude
- altitude
- author
- sourceurl
- istodo
- tododue
- todocompleted
- source
- sourceapplication
- applicationdata
- order
- usercreatedtime
- userupdatedtime

That is a lot of private info that is stored unencrypted -- basically it seems only the body text is encrypted. This defeats defeats the purpose of e2ee to a measurable degree.

Obviously this was not on oversight but intentional (I assume Joplin devs aren't incompetent), so my question to Joplin is: do you intend to change this in the future?

Trivia: 1password, a password manager which has enjoyed popularity, used to do the same, encrypting only the password and leaving all other fields in clear (websites, etc). They were obviously aware that making websites and other private info known to attackers can put owners at risk, but the appeal of harvesting data was too great and 1password resisted complaints for many years, and lost many customers because of it.

**Comment by Daeraxa** [comment]
The github issues are only for regressions and reproducible bugs, discussion of features or questions should be done on the forum.

**Comment by aleqx** [comment]
I guess I was hoping just a little bit that this was a bug and oversight ... thanks for confirming

**Comment by Daeraxa** [comment]
There is generally more activity on the forum so you are simply more likely to get a reply if nothing else, if it needs to be re-opened as a bug then we can still do so.

**Comment by hellodword** [comment]
Agree, e2ee should protect more.
