### ISSUE TITLE
Improve E2EE UI in desktop app

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#6458]
- [ ] In sync wizard dialog, add a checkbox "Enable encryption" (off by default). When ticked, it will open the same "Enable encryption" dialog as in the Encryption config screen. If the master password is already set, there's no need to open that dialog again and encryption can simply be enabled.

- [x] In the config screen, move the "Encryption" item under the "Synchronisation" item (indented below)

- [ ] In the config screen, under "Synchronisation", add an "Enable encryption" (off by default) below "Sync target". Again, clicking on it should open the "Enable encryption" dialog. Should share the same code as the Sync Wizard dialog.

- [ ] On top of the Encryption config screen, add a brief explanation of the feature.

**Comment by om2137** [comment]
Can I work on this issue @roman-r-m @laurent22 
Or someone is working on it already ?

**Comment by roman-r-m** [comment]
Yes, you can, no need to ask. I don't know if anyone's working on it but I doubt it.

**Comment by om2137** [comment]
opened topic on forum about this : https://discourse.joplinapp.org/t/improve-e2ee-ui-in-desktop-app-github-6458/28494

**Comment by om2137** [comment]
> opened topic on forum about this : https://discourse.joplinapp.org/t/improve-e2ee-ui-in-desktop-app-github-6458/28494

I have posted few doubts here can anyone clarify them so that i can push the changes

@roman-r-m @laurent22
