### ISSUE TITLE
app-questions

### ISSUE THREAD

**Issue by hype1type** [laurent22/joplin#6461]
When I sync from WebDAV to my mobile phone, the storage data of my mobile phone has been growing. Even if I delete my notes, it can't be reduced unless I clear the app data and restore the initial settings. My question is whether the attachment will not be deleted with the deletion of notes after downloading. Where is its storage location?

**Comment by Daeraxa** [comment]
Do you have note history enabled?

**Comment by hype1type** [comment]
No, I turned off all the history functions. I looked through the past questions and found some people like me. When I delete notes, the attachments will not be deleted locally or in the cloud, so the attachments will accumulate all the time, which can only be solved by clearing the app data.
