### ISSUE TITLE
Dropbox attachments not downloaded on Windows 11

### ISSUE THREAD

**Issue by v-marinkov** [laurent22/joplin#6462]
## Environment

Joplin version: 2.7.15
Platform: Windows 11

## Problem
An install on Win 11 does not download ANY old attachments into \.config\joplin-desktop\resources from Dropnox but does store new attachments to that folder and uploads them to Dropbox.

**Comment by graphit0** [comment]
Hi there, please check `Attachment download behaviour` dropdown, it should be set to Always and try syncing again. 

![image](https://user-images.githubusercontent.com/44114323/165977722-77a623ba-8e62-4cd6-b761-6fde3a805f33.png)

If that doesn't help, I invite you to post this issue to our forum in support section, so more people could investigate the issue in better detail.

Cheers!

**Comment by v-marinkov** [comment]
Thanks for the reply. It is set to Always and I even tried toggling it between the different options but still not downloading them. I also re-authenticated with Dropbox - no change.

**Comment by JackGruber** [comment]
To be able to say something about this, logfiles are needed.  Plz. upload the log.txt from a debugging run.
https://joplinapp.org/debugging/

**Comment by v-marinkov** [comment]
I checked the logs but there was nothing informative there, so I forced "delete local data and re-download from target" and everything seems to be working fine now :)
