### ISSUE TITLE
Table Properties not Retained [WYSIWYG editor]

### ISSUE THREAD

**Issue by ScriptInfra** [laurent22/joplin#6466]
## Environment

Joplin version: 2.7.15
Platform: Fedora Linux v35
OS specifics: Kernel 5.17

## Steps to reproduce

1. Create a table using the WYSIWYG editor.
2. Click inside the table, select 'Table properties' icon to open the Table Properties dialog box.
3. Select Advanced.
4. Select a Border style.
5. Select a Border color and Background color.
6. Select Save.
7. Select a different note. 
8. Select the note with the table.
9. Open the Table Properties dialog box to see that the properties are all lost.

## Describe what you expected to happen

I would expect the table properties to be retained.

**Comment by ScriptInfra** [comment]
This is still broken.

**Comment by ScriptInfra** [comment]
This remains an issue.

**Comment by uiop-on** [comment]
I'm having this issue as well.
