### ISSUE TITLE
The picture is lost, only the link is left

### ISSUE THREAD

**Issue by DFYX233** [laurent22/joplin#6467]
![image](https://user-images.githubusercontent.com/60833430/166093318-5760e578-c816-413e-a126-d67a459f8d88.png)
I didn't do anything. The picture was lost. Is there a way to recover it?

**Comment by JackGruber** [comment]
I don't think the picture is lost, only not renderd correctly. 

This probably happens with any HTML that does not have a close tag, is the first thing in a listing and the following listing is indented.

- Add a character after the img code
- Add a character befor the img code
- Add a `</img>` after your code
- Remove the indentation from the other images


```
One
- <b>bold</b>
	- ![ab36243f0bb666894fcd8c85152499c3.png](:/b2334de5115a4dfd87520c0c62874db6)
	- ![e5f2a8ba1a34255a3fd410ffc1235694.png](:/05b3f54c0ed94f628673b38b21f87cb7)


---
Two
- <br>
	- ![ab36243f0bb666894fcd8c85152499c3.png](:/b2334de5115a4dfd87520c0c62874db6)
	- ![e5f2a8ba1a34255a3fd410ffc1235694.png](:/05b3f54c0ed94f628673b38b21f87cb7)

---
Three
- <br>
	- ![ab36243f0bb666894fcd8c85152499c3.png](:/b2334de5115a4dfd87520c0c62874db6)
- ![e5f2a8ba1a34255a3fd410ffc1235694.png](:/05b3f54c0ed94f628673b38b21f87cb7)


---
Four
- A <br>
	- ![ab36243f0bb666894fcd8c85152499c3.png](:/b2334de5115a4dfd87520c0c62874db6)
	- ![e5f2a8ba1a34255a3fd410ffc1235694.png](:/05b3f54c0ed94f628673b38b21f87cb7)


---
Five
- <br> B
	- ![ab36243f0bb666894fcd8c85152499c3.png](:/b2334de5115a4dfd87520c0c62874db6)
	- ![e5f2a8ba1a34255a3fd410ffc1235694.png](:/05b3f54c0ed94f628673b38b21f87cb7)


```
![grafik](https://user-images.githubusercontent.com/24863925/166098841-3221b60f-2da2-4875-9b7d-424b5c9e843e.png)

**Comment by 304535076** [comment]
这是QQ邮箱自动回复邮件，

您的来信已收到。
