### ISSUE TITLE
Spell checker isn't working

### ISSUE THREAD

**Issue by 10vorne** [laurent22/joplin#6474]
I'm using Joplin on Mac (latest version on MacOSX 10.15.7) and the spell checker doesn't work, never has. My language (German) is selected and the correction is also activated. I don't get any (visual) feedback (e.g. an underline) when a word is misspelled.

Joplin 2.7.15 (prod, darwin)

Client-ID: c4bcfce3b7094f3ea138b106b7f0a813
Sync-Version: 3
Profil-Version: 41
Unterstützter Schlüsselbund: Ja

Revision: 8352e23

**Comment by Daeraxa** [comment]
Which editor are you using?
There are two spellcheck options at the moment, the one in the top right of the screen and another in `Preferences > General` "Enable spell checking in Markdown editor? (WARNING BETA feature)"

**Comment by 10vorne** [comment]
The BETA Feature is turned off at the moment and I use the MD-Editor....so I think that`s the problem.
