### ISSUE TITLE
Add note counts indicators per notebook to the CLI/Terminal app

### ISSUE THREAD

**Issue by Daeraxa** [laurent22/joplin#6478]
The desktop app has useful information displayed on the notebook list to show how many notes are contained within it.
e.g. 
![image](https://user-images.githubusercontent.com/58074586/166308775-875969cf-bd18-4df5-8512-4c0eae6dab6d.png)

The goal of this would be to extend this functionality to the terminal application.

- Counts of notes within notebooks should be displayed inline in the notebook pane as an indicator after the notebook entry
- Consider adding a config option to enable or disable the functionality - unlike the desktop application which can be modified with CSS, the terminal app doesn't have such user accessible UI customisation but the addition of this might cause undue clutter on lower resolution displays where the terminal app might be used

**Comment by riftsandroses** [comment]
Can this be done with addition of a BASH command ? If yes then I might be able to contribute.

**Comment by Daeraxa** [comment]
And what if the user doesn't have bash installed as a shell? The app is written mostly in JS (although I believe any new files should be written in TS) which is what any new features should be written in.

**Comment by riftsandroses** [comment]
> And what if the user doesn't have bash installed as a shell? The app is written mostly in JS (although I believe any new files should be written in TS) which is what any new features should be written in.

Got it. Thanks.

**Comment by eduebernal** [comment]
Hello! Is anyone working on this? I would like to take this issue!

**Comment by roman-r-m** [comment]
> Hello! Is anyone working on this?

I don't think so
