### ISSUE TITLE
slow action when clicking multiple times on a new note button or a new to-do

### ISSUE THREAD

**Issue by bishoy-magdy** [laurent22/joplin#6483]
## Environment
Joplin version: 2.8.2

## Steps to reproduce

https://user-images.githubusercontent.com/58605547/166331110-1f7611cb-83f0-462f-bd31-bff3bf13144e.mp4

**Comment by laurent22** [comment]
What are you trying to achieve?

**Comment by bishoy-magdy** [comment]
> What are you trying to achieve?

When creating multiple notes without a title or content, extra notes will be deleted as a default, but it is done slowly.

So it would be better if when creating a new note, the new note button remained inactive until the note got a title, had content, or was deleted. and the same in the new-to-do button to avoid the strange behavior shown in the video.
