### ISSUE TITLE
Web Clipper doesn't download images from one particular page:

### ISSUE THREAD

**Issue by LightTemplar** [laurent22/joplin#6488]
Web Clipper doesn't download images from one particular page: http://microkino.byethost32.com/list/graph/carlitto.htm

## Environment

WebClipper: Version 2.1.3
Firefox 99.0 (64-bit)

Joplin 2.6.10 (prod, linux)
Sync Version: 3
Profile Version: 41
Keychain Supported: No
Revision: 98fba37

OS specifics: Kubuntu 20.04

## Steps to reproduce

1. Try to clip page in any form: simplified page, complete page, selection, even HTML. I tried even with page, saved on a local drive.
2. Look in Joplin - there are no images in the note at all, only some placeholders and not even everywhere.

## Describe what you expected to happen
Note with images.

## Logfile
Sorry, I couldn't find what  exactly part of debugging window of WebClipper to copy/paste.

**Comment by laurent22** [comment]
I've add a look at it but unfortunately it's using some trick to prevent web scrappers, so we won't be able to support the site.

For reference, `curl http://microkino.byethost32.com/list/graph/carlitto/Kastaneda001.jpg` returns this:

```html
<html><body><script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){
var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)
e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),
c=toNumbers("b987a97fcf0b626a72facf83f2aca8bd");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+";
 expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; 
location.href="http://microkino.byethost32.com/list/graph/carlitto/Kastaneda001.jpg?i=1";</script><noscript>This site
 requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript>
</body></html>
```
