### ISSUE TITLE
FR: Web clipper in the terminal 

### ISSUE THREAD

**Issue by gerroon** [laurent22/joplin#649]
HI

I looked at the terminal doc to see how to enable the clipper in the terminal mode but I am not seeing it. Either not documented or not implemented. In either case please consider web clipper for the terminal app too.

thanks

**Comment by gerroon** [comment]
Well that seems to be the same case with teh regular gui. Maybe the doc can recommend to run it under screen or tmux which is how I use it?

**Comment by rcrx** [comment]
You can banish the gui to the system tray and let it work in the background. Of course that assumes you opened it in the first place (which the web clipper requires, obviously), but at least you can keep it out of the way.

**Comment by shankargopal** [comment]
This FR is particularly vital for those of us on 32 bit Linux systems, who can't seem to [run the desktop application](https://github.com/laurent22/joplin/issues/526).  This now means that we can't access the Web Clipper or the API either.

**Comment by magnific0** [comment]
I'd like to see this feature too.

@laurent22 I would just keep the application open using [screen](https://linux.die.net/man/1/screen).

**Comment by gerroon** [comment]
f@@@@@k you @stale piece of shit bot
