### ISSUE TITLE
Keyboard shortcut not working in WYSIWYG editor

### ISSUE THREAD

**Issue by globalhuman** [laurent22/joplin#6490]
Some keyboard shortcuts for joplin do not work when in WYSIWYG mode. Of main interest is the action "Toggle Editor" going between markdown -> WYSIWYG and back from WYSIWYG -> markdown. The latter case does not work.

This is not listed as a limitation of the rich-text-editor as per https://joplinapp.org/rich_text_editor/ . 

I would therefore describe this as a bug until otherwise documented or fixed. 

A number of other requests exist for this functionality, or have noted this behaviour:

- https://discourse.joplinapp.org/t/shortcut-for-toggle-markdown-editor-wysiwyg-editor/21148
- https://discourse.joplinapp.org/t/keyboard-shortcut-for-switching-between-md-wysiwyg/22206/2
- https://discourse.joplinapp.org/t/toggle-editors-by-keyboard/22999

The current workaround is to use the command pallet (CTRL+SHIFT+P) and select the "Toggle Editor" option.

## Environment

Joplin version: 2.7.15
Platform: macOS
OS specifics: 12.3.1

## Steps to reproduce

1. Open note in markdown editor mode
2. Add keyboard shortcut to ~/.config/joplin-desktop/keymap-desktop.json
```json
 {
    "command": "toggleEditors",
    "accelerator": "Ctrl+Cmd+T"
  }
  ```
3. Use keyboard shortcut as specified for "Toggle Editor" when in markdown editor mode
4. Observe change to WYSIWYG editor mode
5. (FAIL) Use keyboard shortcut again to "toggle" back to markdown mode

## Describe what you expected to happen

It is expected that the "Toggle Editor" action work in both directions markdown -> WYSIWYG and WYSIWYG -> markdown.

It is expected if there are key clashes where a shortcut defined in the markdown editor clashes with the WYSIWYG scope then this be highlighted.

**Comment by Daeraxa** [comment]
Related conversation - https://github.com/laurent22/joplin/issues/6063

**Comment by virious** [comment]
It's still not working. I tried to use Ctrl + Shift + T shortcut to Insert Date Time and when in WYSIWYG mode it doesn't do anything. As soon as I switch to markdown mode it starts working. My Joplin version:
```
Joplin 2.8.8 (prod, win32)

Client ID: e2267148534744c7844b2a47c32a31af
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: c2a6a13
```

**Comment by globalhuman** [comment]
This is still not working. Having looked a bit further into the docs I have discovered the following page which lists the keybinds between rich text editor and the markdown editor as an area requiring improvement.

https://joplinapp.org/gsoc2022/ideas/#6-improve-integration-of-the-richtext-wysiwyg-editor

**Comment by camilajenny** [comment]
```
  {
    "command": "toggleEditors",
    "accelerator": "Ctrl+W"
  }
```
doesn't work in Linux too. It changes to WYSYWIG but not back.
