### ISSUE TITLE
can not go back to sync options anymore

### ISSUE THREAD

**Issue by chatay** [laurent22/joplin#6499]
Hello,

once clicked on dropbox synchronise option, can not see again other sync options by clicking on back button

## Environment

Joplin version: 2.7.15
Platform: Windows
OS specifics: 

## Steps to reproduce

1. Click on Sync
2. hit dropbox option
3. click on Back but it goes all the way back to joplin screen instead of sync options UI

![image](https://user-images.githubusercontent.com/27813881/167314995-a640717c-ee07-4e39-aef0-8ca68da93397.png)

## Describe what you expected to happen

it should normally go back to SYNC options menu UI

**Comment by Daeraxa** [comment]
The options are in Tools > Synchronisation. Does that not show up?
If you want to run the sync wizard again then you select "open sync wizard".

**Comment by chatay** [comment]
there is no such option

![image](https://user-images.githubusercontent.com/27813881/167319167-2de6dc0f-d4d9-4ccb-97de-70107c2726de.png)

instead I click on that

![image](https://user-images.githubusercontent.com/27813881/167319185-514db9b6-0282-43e1-b472-4856a61de6a2.png)

**Comment by Daeraxa** [comment]
Sorry Tools > Options > Synchronisation. The wizard will only show up the first time you hit that sync button and select a sync target. After that you have to configure it via the config menu.
