### ISSUE TITLE
Improve initial UX for new users

### ISSUE THREAD

**Issue by JACooper** [laurent22/joplin#65]
### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [ ] Terminal

---

Really liking it so far! One suggestion: on the Windows desktop app, the initial view has no notebooks, so you get a view that says "No notes in here. Create one by clicking on 'New note'. However, the new note button is disabled, and you have to go into File -> New Note to get an error message that tells you to make a notebook first. It would be preferable to tell users to create a new notebook if they have none. Obviously not a show stopper, but it stood out.

**Comment by theobromine** [comment]
+1 Same issue on Mac. Should prompt users to create a new notebook instead.
