### ISSUE TITLE
FR: New note should open in edit mode

### ISSUE THREAD

**Issue by gerroon** [laurent22/joplin#650]
Hi

It would be very nice if new note automatically opens in edit mode if the current mode is view only. 

There is no reason to have a new note but not being able to edit it right away. It is just a convenience functionality. 

thanks

**Comment by laurent22** [comment]
I'm afraid this won't be changed as a user might want to create a note with just a title, and might want to keep the layout as it is. In general I'm not too keen on settings being changed automatically as that might be confusing/annoying for some users. There's a shortcut `Ctrl+L` to toggle the layout quickly if needed.
