### ISSUE TITLE
The Joplin web-clipper crashes Firefox

### ISSUE THREAD

**Issue by AlReul** [laurent22/joplin#6505]
[Console FireFox 10°05°22.docx](https://github.com/laurent22/joplin/files/8664722/Console.FireFox.10.05.22.docx)

## Environment
![Firefox Crash Capture d’écran du 2022-05-10 12-01-09](https://user-images.githubusercontent.com/105301282/167708992-a12803dd-9adb-4771-bcf1-9ac80d1ab661.png)

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1. 
2. 
3.

**Comment by AlReul** [comment]
Have I forgotten or misunderstood anything? I just see the case has been closed but I don't see any answer. What am I supposed to understand or do ?

**Comment by AlReul** [comment]
Hello Laurent22,

I have seen the case has been closed on Github but I don't see any answer. Have I misunderstood or missed anything ? What am I supposed to understand or do ?

Thank you for your attention to this message.

Hopeful regards,

Alain REUL



-------- Message d'origine --------
De : Laurent Cozic ***@***.***>
Date : 11/05/2022 14:52 (GMT+01:00)
À : laurent22/joplin ***@***.***>
Cc : AlReul ***@***.***>, Author ***@***.***>
Objet : Re: [laurent22/joplin] The Joplin web-clipper crashes Firefox (Issue #6505)


Closed #6505<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flaurent22%2Fjoplin%2Fissues%2F6505&data=05%7C01%7C%7C77cbb37b12e640321cbc08da334d2478%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637878703659738281%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ohECCTbMDeBqq%2FZR5Zytrobkiep445DOfbFZzI6n630%3D&reserved=0>.

**Comment by laurent22** [comment]
We need a bug report as described in the template, including version numbers, etc. For the log, you can paste it here or attach it as a text file (personally I don't open docx files from the internet).
