### ISSUE TITLE
Joplin does not respect GNOME animation settings

### ISSUE THREAD

**Issue by zakutin** [laurent22/joplin#6507]
Joplin does not respect GNOME animation settings after reboot or re-login, even if `gsettings set org.gnome.desktop.interface enable-animations false`

## Environment

Joplin version: Joplin 2.7.15 (prod, linux), Revision: 8352e23
Platform: Linux
OS specifics: Ubuntu 22.04 LTS, Wayland or X11, GNOME 42.0

## Steps to reproduce

1. Make a clean OS reboot with animations **enabled**: `gsettings set org.gnome.desktop.interface enable-animations true`
2. Open Joplin, it will have smooth scroll
3. Close Joplin
4. Change GNOME animations to **false**: `gsettings set org.gnome.desktop.interface enable-animations false`
5. Open Joplin, smooth scroll is disabled
6. Reboot or re-login with disabled GNOME animations
7. Open Joplin, it has smooth animations, despite disabled GNOME animations

## Describe what you expected to happen

Joplin shall keep smooth scroll **disabled** with `gsettings set org.gnome.desktop.interface enable-animations false` after OS reboot or re-login.

## Logfile
N/A

**Comment by zakutin** [comment]
The issue has not been resolved yet.

**Comment by roman-r-m** [comment]
It's probably an issue with electron rather than Joplin. Electron version used by Joplin has been recently bumped to 18 but I don't think this change has made it into the last release or even pre-release.
Might be worth checking again in the next version.

**Comment by zakutin** [comment]
@roman-r-m thanks for info.
