### ISSUE TITLE
Bug: Tags are converted to all lowercase

### ISSUE THREAD

**Issue by capnspacehook** [laurent22/joplin#651]
### Operating system

- Windows

### Application

- Desktop

Whenever I create a tag on the Windows desktop client, the tag is changed such that any uppercase characters are replaced with lowercase ones. The tags from notes I imported from Evernote retain their case variability.

**Comment by laurent22** [comment]
This is not a bug. In Joplin, tags are case-insensitive, however if they are imported from somewhere else they are left as-is.

**Comment by capnspacehook** [comment]
So there's no way to make tags with case sensitivity? Is there any reason for that design decision?

**Comment by laurent22** [comment]
Someone made a pull request not long ago to allow renaming a tag (by right-clicking on it in the sidebar). Maybe give that a try? If that doesn't work try, changing the tag name for example from "My-Tag" to "my-tag-2", and then finally "my-tag".

**Comment by capnspacehook** [comment]
Nope, none of those work. No matter what I do, all created tags are case insensitive.

**Comment by capnspacehook** [comment]
Is there anything else you want me to test?
