### ISSUE TITLE
iPadOS floating / split / undocked keyboard almost entirey overlays note editor

### ISSUE THREAD

**Issue by rain1155** [laurent22/joplin#6512]
## Environment

Joplin version: 12.7.2
Platform: iPad Pro 10.5 " 2017 
OS specifics: iPadOS 14.8.1

## Steps to reproduce

1. edit a note (preferably one with a lot of text for better effect) 
2. tap on a line in the note to bring up the keyboard
3. if floating, split or undocked keyboard is used, any content below the keyboard will be covered white. Moving around the keyboard covers almost everything of the note editor white making it impossible to edit the note.
4. you can resolve the issue by switching back to the normal keyboard at the bottom of the screen.
(switching the keyboard is done by tap+holding on the keyboard down button in the bottom right and swiping up to the desired option before releasing)

## Describe what you expected to happen
If any other keyboard than the default one that's at the bottom of the screen is used, you should still be able to properly use the note editing function. 

## Screenshots showing same note edit screen with and without floating keyword
normal keyboard - no problem:
![image](https://user-images.githubusercontent.com/66764212/168176850-f8b217fa-6485-4eeb-aef3-f1196e53b70c.png)

floating keyboard - unusable edit screen:
![image](https://user-images.githubusercontent.com/66764212/168176922-40302c6a-45e2-48db-b8d7-aab5e280df09.png)

There's also a video of this on an older issue report:
https://github.com/laurent22/joplin/issues/5663
On this report other similar issues were linked, but those aren't the same - or at least the workarounds with the accessibility settings don't have any effect on my iPad - the issue remains the same. 

## Logfile
Nothing that I can see related to this showing in the log. That said, this seems to be an issue already reported on react-native:
https://github.com/facebook/react-native/issues/29473
And there also seems to be workarounds posted that can help with the issue while it hasn't been fixed in react yet.

**Comment by rain1155** [comment]
The issue still remains after updating to Joplin 12.8.1 and I'm hoping that the workaround I linked to could be implemented if applicable to the reported issue.

**Comment by personalizedrefrigerator** [comment]
Please try enablimg the beta editor.

On Android, there still seems to be an issue (editor content duplicated). Is this also true with iPadOS?

**Comment by rain1155** [comment]
I already had the beta editor enabled. And the issue seems to only occur with the floating keyboard if the keyboard is moved around. 

I'm not sure I see any issue with editor content getting duplicated.

**Comment by rainforest1155** [comment]
The issue is still present and in order to use Joplin I always have to switch to the normal keyboard instead of using the floating one (which I otherwise use on iPad).

**Comment by personalizedrefrigerator** [comment]
Possibly-related: https://github.com/laurent22/joplin/issues/6682

**Comment by personalizedrefrigerator** [comment]
Still an issue.

**Comment by personalizedrefrigerator** [comment]
This may have been fixed upstream (see https://github.com/facebook/react-native/commit/4b9382c250261aab89b271618f8b68083ba01785, which fixes a related issue). We use an unmaintained library that is blocking an update to the latest version of React Native. We will have to fix/migrate away from that library first.

**Comment by personalizedrefrigerator** [comment]
Still an issue.
