### ISSUE TITLE
Sabre\DAV\Exception\MethodNotAllowed: The resource you tried to create already exists

### ISSUE THREAD

**Issue by armaccloud** [laurent22/joplin#652]
### Operating system

- Linux

### Application

- Desktop (Joplin 1.0.103 (prod, linux))

### Bug Description
When using the desktop Joplin for Linux, my Nextcloud log gets a lot of the following errors, both for `/Notes/.resource` and `/Notes/.sync`

![selection_002](https://user-images.githubusercontent.com/9272078/42029154-eab4aafa-7ace-11e8-94a5-c44c46973b8a.png)

`

Fatal | webdav | Sabre\DAV\Exception\MethodNotAllowed: The resource you tried to create already exists/home/ewiqzonl/public_html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 594: Sabre\DAV\Server->createCollection('Notes/.resource', Object(Sabre\DAV\MkCol))[internal function] Sabre\DAV\CorePlugin->httpMkcol(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/home/ewiqzonl/public_html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)/home/ewiqzonl/public_html/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method MKCOL', Array)/home/ewiqzonl/public_html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/home/ewiqzonl/public_html/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()/home/ewiqzonl/public_html/remote.php - line 164: require_once('/home/ewiqzonl/...'){main} | 2018-06-28T12:19:17+0200
-- | -- | -- | --
Fatal | webdav | Sabre\DAV\Exception\MethodNotAllowed: The resource you tried to create already exists/home/ewiqzonl/public_html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 594: Sabre\DAV\Server->createCollection('Notes/.sync', Object(Sabre\DAV\MkCol))[internal function] Sabre\DAV\CorePlugin->httpMkcol(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/home/ewiqzonl/public_html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)/home/ewiqzonl/public_html/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method MKCOL', Array)/home/ewiqzonl/public_html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/home/ewiqzonl/public_html/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()/home/ewiqzonl/public_html/remote.php - line 164: require_once('/home/ewiqzonl/...'){main}

`

**Comment by laurent22** [comment]
https://github.com/laurent22/joplin/issues/319#issuecomment-375064277
