### ISSUE TITLE
Search does not work for the code snippets in the editor mode

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [laurent22/joplin#6521]
Search does not work for the code snippets in the editor mode

## Environment

Joplin version: 2.7.15
Platform: Windows
OS specifics: 11

## Steps to reproduce

1. Insert a code into a note using Joplin "Code Block"
2. Click ctrl+f and start to search any word in the code block in the editor mode

## Describe what you expected to happen
1. The search should find a word

## Issue
The search and replace says: "Could not find a specified string"

**Comment by brijsiyag** [comment]
Hey @YevheniiPokhvalii , I reproduced this bug also in OSx.
I would love to work on this..

**Comment by Daeraxa** [comment]
Assuming this is talking about the richtext editor then this is upstream in TinyMCE rather than Joplin - you can see it on their demo: https://www.tiny.cloud/docs/demo/full-featured/

This is of course using the in-built search function as part of the editor rather than anything else.
