### ISSUE TITLE
“Some items cannot be synchronised” banner stays permanently on iOS client

### ISSUE THREAD

**Issue by lab6zine** [laurent22/joplin#6527]
I created a note on the desktop client and attached a large file, which is too large to synchronize with Dropbox. That’s ok. I only need the attachment on the desktop. Sync is otherwise working fine. 

But now when I open the iOS client, I see a permanent orange banner warning me of this non-syncing file. I can’t dismiss it. It takes up screen space which I would rather be using for note space. 

Please can you add a dismiss/close button to this banner. 

## Environment

Joplin version: 12.7.2
Platform: iOS 15.4.1

## Steps to reproduce

1. Attach large (>100MB) file on desktop client
2. Observe sync fail on desktop client
3. Observe banner on iOS client when it syncs

## Describe what you expected to happen

Warning banner can be closed. 

## Screenshot

![19E89402-E7CC-46DF-8AC0-9FFF63CDDA20](https://user-images.githubusercontent.com/1290238/169643986-b509fa7c-1f40-4f81-98b3-0a5b7a0db32b.png)

**Comment by lab6zine** [comment]
Unfortunately I can no longer reproduce this issue because the original large files have now managed to synchronize successfully. Good news for me, but I think the request remains valid.

**Comment by personalizedrefrigerator** [comment]
I'm experiencing a similar issue on Android with the "enter decryption password" banner.
