### ISSUE TITLE
Nitpick of Horizontal Rule in toolbar

### ISSUE THREAD

**Issue by RCJacH** [laurent22/joplin#653]
### Operating system

[x] Windows
- macOS
- Linux
- Android
- iOS

### Application

[x] Desktop
- Mobile
- Terminal

I would suggest changing the output from clicking the Horizontal Rule in toolbar to `---` or longer, from the current `* * *`, and the reason is that upon inserting `* * *`, when you press enter, Joplin automatically inserts another asterisk at the beginning of the new line, while dashes would not trigger this action.

Of course we can also add a condition for adding asterisks.

**Comment by laurent22** [comment]
I see what you mean but I will keep it as `* * *` as that's what Stack Exchange uses. However it's indeed an issue if the divider is incorrectly detected as a bullet list item, so that will need to be fixed.
