### ISSUE TITLE
Published Note Error: Unsupported File Type

### ISSUE THREAD

**Issue by Petr05** [laurent22/joplin#6531]
THIS IS MY FIRST BUG REPORT, APOLOGIES IF IT'S FORMATTED POORLY!

## Brief Description

I'm publishing a note to the web using the Joplin Cloud "publish note" feature. When I input the generated URL into my browser's address bar, it returns the following error message:

"Joplin Cloud- Error
Unsupported Item Type: 2"

I've published notes to the web before without any issues, and this particular note doesn't seem to have any peculiar properties that might cause an error. It has an attached image; several internal markdown links to other Joplin notes; several hyperlinks; and several footnotes. Further details of the published note are below:

Note ID: 54225e6c063f4fe498b53d8820d45f66
Published URL: https://sg3gmsnkh2.joplinusercontent.com/shares/2oh8R5eQi4nfhbtnkxvBR5

## Environment

Using Desktop Client 
OS: Windows 10. Version 10.0.19043 Build 19043
Joplin 2.7.15 (prod, win32)
Client ID: 14968736c1d0439486361d4998680ed9
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes
Revision: 8352e23

## Steps to reproduce

1. With a Joplin Cloud Pro account, select the 'publish note' option from a note's context menu. 
2. Copy generated link and paste into address bar of browser

## Describe what you expected to happen

I expected a static webpage of the note to be generated as usual, for quick-access via my browser. 

## Logfile

NOTE: This is my first bug report, and to perfectly honest I didn't really know what to look for! I simply followed the basic debug instruction and copied any potentially pertinent info below.

### From Logfile

Code: SQLITE_CONSTRAINT
Error: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: settings.key: INSERT INTO `settings` (`key`, `value`) VALUES (?, ?): plugin-io.github.jackgruber.backup.lastBackup,1653284267875
    at DatabaseDriverNode.sqliteErrorToJsError (C:\Users\peter\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\database-driver-node.js:23:18)
    at JoplinDatabase.sqliteErrorToJsError (C:\Users\peter\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\database.js:34:30)
    at JoplinDatabase.<anonymous> (C:\Users\peter\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\database.js:133:36)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\peter\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\database.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"

### From Development Tools-- Issues Tab

Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
Affected Resource:
C:\Users\peter\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\shim.js:1

### From Development Tools-- Console Tab

DevTools failed to load source map: Could not parse content for file:///C:/Users/peter/AppData/Local/Programs/Joplin/resources/app.asar/gui/note-viewer/pluginAssets/mermaid/mermaid.min.js.map: Unexpected end of JSON input
C:\Users\peter\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\utils\useMessageHandler.js:25 Got ipc-message: noteRenderComplete undefined

C:\Users\peter\AppData\Local\Programs\Joplin\resources\app.asar\gui\ShareNoteDialog.js:61 Render ShareNoteDialog
C:\Users\peter\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11494 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(ShareNoteDialog)

C:\Users\peter\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11494 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(ShareNoteDialog)
printWarning @ C:\Users\peter\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11494

C:\Users\peter\AppData\Local\Programs\Joplin\resources\app.asar\gui\ShareNoteDialog.js:61 Render ShareNoteDialog
C:\Users\peter\AppData\Local\Programs\Joplin\resources\app.asar\gui\ShareNoteDialog.js:61 Render ShareNoteDialog
C:\Users\peter\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\Logger.js:190 08:27:10: ShareService: Refreshed shares: {items: Array(2), has_more: false}

**Comment by laurent22** [comment]
Thanks for the detailed report, I will check
