### ISSUE TITLE
Blank screen on ipad, no note text visible

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#6532]
After editing a note I tap the back button/arrow. Then the screen gets blank. Sometimes the title is stille visible. The note text is not visible. There is a small black bar at the top.

https://user-images.githubusercontent.com/87373763/169972861-6080a48c-6dbd-4b94-ba3d-eed26de0d6fa.MOV

![86DAF7F7-5C47-4CA0-B1C7-11D53C055755](https://user-images.githubusercontent.com/87373763/169971993-308d4598-0c44-40f8-b8c2-bdb0935f1d70.png)
 Joplin 12.7.2 Ipad pro 9,7” ios 15.4

**Comment by ghost** [comment]
Hi,

Thx for your reply.
The issue has not been fixed.

**Comment by jbagdonas** [comment]
This is still broken on iOS.

**Comment by serranomorante** [comment]
Same is happening to me. Still no fix 😫
