### ISSUE TITLE
Clip does not download images

### ISSUE THREAD

**Issue by yangzw1024** [laurent22/joplin#6535]
When I use the clip completion page (HTML), it doesn't download the image, it still references the image using the HTML link, and when the image link dies, the note can't show the image. 
And when I'm export the note with PDF, some image don't show up

**Comment by laurent22** [comment]
What url did you try to clip?

**Comment by yangzw1024** [comment]
I clipped the url  https://mp.weixin.qq.com/s/M5XYv5EuCXGJ-6qYuRjihA, in Joplin, the pictures were fine, when I exported the PDF, all the pictures except the first one were not shown
Joplin:
![image](https://user-images.githubusercontent.com/59439277/171354725-0293585a-a987-43e3-b3eb-bfeaa8672054.png)
PDF:
![image](https://user-images.githubusercontent.com/59439277/171354812-9e1d2935-d8b9-4f50-bcb3-6f7df0aa9827.png)
