### ISSUE TITLE
Too high distance between line and line in Rich Text editor.

### ISSUE THREAD

**Issue by jzh20042003** [laurent22/joplin#6539]
I don't like using markdown and I like using Rich Text editor.
But There is a problem: Every time when I want to creat one new line,system creat two new line for me.
Every time system create 2 new line with one enter in Rich Text editor.
There are too much distance between new line and new line in Rich Text editor.
And when I create a new note with Rich Text editor and just type words in it,there isn't this problem.Everytime I press enter system create one newline but not two newline.
But I switch to other note and switch back to the note which I just created,all new line become two newline!
Then if I press enter,system create 2 newline per one time.
There are too much distance between line and line in Rich Text editor!!!!!!
![joplin1](https://user-images.githubusercontent.com/37479453/170708201-8de82606-c1cb-422e-8360-91aadea76aca.JPG)
![joplin2](https://user-images.githubusercontent.com/37479453/170708270-7dfb3f13-8927-458b-9697-b40ed7660d01.JPG)

system:windows7 x64
Joplin 2.7.15 (prod, win32)
sync version: 3
config version: 41

edited: 8352e23

**Comment by Daeraxa** [comment]
This isn't a bug, its part of TinyMCE itself (demo here - https://www.tiny.cloud/docs/demo/basic-example/). You can press shift + enter for a single line.

**Comment by jzh20042003** [comment]
> This isn't a bug, its part of TinyMCE itself (demo here - https://www.tiny.cloud/docs/demo/basic-example/). You can press shift + enter for a single line.

Can you put "use enter instead of shift + enter" into settings? This might be helpful for the user of Rich Text editor.
Or is it able for me to write a plugin to make enter instead of shift + enter?
Or is there any other idea to make "use enter instead of shift + enter"?
Thank you. This will be helpful for Rich Text editor users.
