### ISSUE TITLE
Joplin setup crashes on Windows 8.1 Embedded Industry Pro 32-bit if run without explicit admin privileges

### ISSUE THREAD

**Issue by TAbdiukov** [laurent22/joplin#6541]
## Environment

Joplin version: 2.7.15
Platform: Windows 8.1 Embedded Industry Pro 32-bit (note: not 64-bit)
OS specifics: As tested on Embedded Industry flavour. Possibly traditional Windows 8.1 32-bit is also affected. Must be 32-bit, not 64-bit. Windows 7 is unaffected (it seems.)

## Steps to reproduce

Discovered as I tried having virtualised low-profile Windows environment

1. [Get the ISO from MIcrosoft](https://www.microsoft.com/en-nz/download/details.aspx?id=40745) . You need 32-bit build, thus it's `9600.16384.WINBLUE_RTM.130821-1623_X86FRE_EMBEDDEDINDUSTRY_EN-US-IRM_CEI_X86FRE_EN-US_DV5.ISO`
2. Install in Virtualbox / VMWare
3. Get `Joplin-Setup-2.7.15.exe`
4. Try running it as usual - crash
![image](https://user-images.githubusercontent.com/18607514/170846785-6b902288-dfab-4f9e-8903-4bd9e1490f10.png)
5. Try running it with admin privileges ( Right-click > Run as Administrator ) - all good

## Describe what you expected to happen

Setup not to crash

**Comment by laurent22** [comment]
I don't think it works on any 32-bit Windows version?

**Comment by TAbdiukov** [comment]
@laurent22 Oh you're right... I didn't go as far as to test out the application there.

This is a different issue to #4649 (this is a setup file issue, not app issue), however, feel free upon your discretion to close this issue given it's relatively low priority
