### ISSUE TITLE
Joplin not launch

### ISSUE THREAD

**Issue by thevan96** [laurent22/joplin#6544]
Today, I switch from ubuntu 20.04 to ubuntu 22.04. But Joplin desktop not launch.
I'm try dowload Joplin-2.8.8.AppImage and run but it error
```
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run.
You might still be able to extract the contents of this AppImage
if you run it with the --appimage-extract option.
See https://github.com/AppImage/AppImageKit/wiki/FUSE
for more information
````

**Comment by laurent22** [comment]
I think this is this issue: https://discourse.joplinapp.org/t/appimage-incompatibility-in-ubuntu-22-04/25173
