### ISSUE TITLE
FR: Work on more than one note

### ISSUE THREAD

**Issue by nr458h** [laurent22/joplin#655]
- Desktop

As a user who is working with notes which are related to each other it would be helpful to be able to work on more than one note at the same time.
I would suggest something like tabs or to be able to open notes in a new window.

Thanks for this great app!

**Comment by stucki-at-home** [comment]
I second that!  Coming from Tomboy I transferred all notes in one big notebook.
So now I'm on the way to edit/re-split/sort into notebooks and sub-notebooks.
Therefore I see lots of cases of 'better put this info into somewhere else'!
And doing this by switching to one note, copy/pasting to some scratch-area
onscreen, switching the note, copy/pasting in, switching back … … …
It's very time-consuming (and frustrating too).  For kind of starters
it might be enough, to have one or more read-only notes onscreen,
and edit/sync only one at a time (allow 'layout for edit' only once),
which would keep write and sync complexity low.
Stucki

**Comment by laurent22** [comment]
Closed as duplicate. Some way to easily switched between notes being worked on would indeed be useful.
