### ISSUE TITLE
macOS ——— cmd+M —> minimize window

### ISSUE THREAD

**Issue by kopfuss** [laurent22/joplin#6555]
Joplin 2.7.15 on macOS won't **minimize** by pressing **cmd** + **M**

## Environment

Joplin version: 2.7.15
Platform: macOS
OS specifics: OS X 10.11.6 (15G22010) El Capitan

## Steps to reproduce

1. open Joplin, wait for it to be ready.
2. press cmd+M on keyboard
3. nothing happens.

## Describe what you expected to happen

App gets minimized to dock.

**Comment by ScriptInfra** [comment]
You might use cmd+H to hide Joplin in the mean time. It doesn't looks like minimize to dock is an option yet.

**Comment by ags799** [comment]
I'd like to see this re-opened. Minimizing with Cmd-M would be nice.
