### ISSUE TITLE
Search field 'X' does not work as expected

### ISSUE THREAD

**Issue by ScriptInfra** [laurent22/joplin#6557]
Please see this forum thread: https://discourse.joplinapp.org/t/desktop-joplin-search-field-x-does-not-work-as-expected/25409

## Environment

Joplin version: v2.8.8
Platform: macOS
OS specifics: v12.4

## Steps to reproduce

1. Type any text into the search bar.
2. Click off of the search bar.
3. Click the 'X' to clear the search text.
4. Notice that the search text did not get removed, and the 'X' moved to the right.

## Describe what you expected to happen

I would expect the text to clear.

**Comment by Daeraxa** [comment]
Specifically it seems to be this commit that has caused a regression - https://github.com/laurent22/joplin/commit/6b6574e7c9b26e9206facfce61834a9dca426ccc
