### ISSUE TITLE
After moving to other nextcloud folder I loose all data

### ISSUE THREAD

**Issue by pdifeo** [laurent22/joplin#656]
### Application

- Desktop

After I change nextcloud folder into config options, Joplin don't show notebooks. Also if I change to older folder, same result. I try to return also on dropbox (first config) with no results. 

On dropbox I have a lot of .md files. I try to import without success. Joplin show following notebook (for example). 

`id: 8e25526eec4b4338b0a446ae081916c7
mime: 
filename: 
created_time: 
updated_time: 2018-06-30T12:39:00.930Z
user_created_time: 
user_updated_time: 
file_extension: 
encryption_cipher_text: JED0100002201b196d2c9d7204dac8c104177a90e8fdb00027a{"iv":"5oea/0Fz2gSASDCKUfJqvQ==","v":1,"iter":1000,"ks":128,"ts":64,"mode":"ocb2","adata":"","cipher":"aes","salt":"SnJUbLF/REE=","ct":"h475xJ4BtBf/XCaNUUFh3QXeLGr+ueHgjPkwJy9144M4d6jK/ltf2EQ9OINhAnas9fzh6kf8btvWS702ijkjNKQVwczlKuXRqhl6TSWvSH/qqifaB6RvCDIdP0a19cBGNg9GhnJPv0gLxgEYKIJ3uUjBJY5s7aj8H2BHBOq1Qu0OUhNVzzN/d1DRJLHngXhxES4LdtLu3Ic...........
encryption_applied: 1
encryption_blob_encrypted: 
type_: 4`

There is a way to recover notes ?

Thanks in advance.
Pasquale

**Comment by laurent22** [comment]
On which sync target do you have all your notes? Probably what you should do is clear all your local data (in ~/.config/joplin-desktop), and then resync with the target that contains everything you need.

**Comment by pdifeo** [comment]
Thank you. I have recovered the data.

Regards
