### ISSUE TITLE
Trying to change shortcut results in Joplin reporting wrong shortcut in use from what I entered

### ISSUE THREAD

**Issue by blablaalb** [laurent22/joplin#6564]
I wanted to rebind shortcut for *Search for All Notes* from *F6* to `Ctrl` + `Shift` + `F`, but Joplin complained that

> Accelerator Ctrl + Shift + T is taken.
![image](https://user-images.githubusercontent.com/55081715/172502292-6dac4edf-ad5a-48ba-be2e-22c9110aea42.png)
Just for testing purpose I tried several random key combinations, but Joplin kept complaining  about `Ctrl` + `Shift` + `T`.

## Environment

Joplin version: 2.8.8
Platform: Windows 10
OS specifics: Windows 10 x64 16GB RAM Ryzen 5

## Steps to reproduce

1. Open `Tools` -> `Options`-> `Keyboard Shortcuts`
2. Type `search` keyword in the search box.
3. Try to change shortcut for *Search in all the notes* from `F6` to any other keys combination.

## Describe what you expected to happen
Joplin should report the inputted shortcut. `Ctrl` + `Shift` + `T` wasn't the shortcut I entered.

**Comment by Daeraxa** [comment]
I think this is plugin related, the commands `setTags` and `backlinksIgnoreListToggleCurrent` aren't core Joplin commands and both are set to use the same accelerator.

If you try to rebind one of them does to something else then does it resolve the issue?

**Comment by blablaalb** [comment]
Just removed the shortcut for `backlinksIgnoreListToggleCurrent` and it worked.  Thanks! The plugin this command comes from is probably "[Automatic backlinks (with manual insert option)](https://discourse.joplinapp.org/t/automatic-backlinks-with-manual-insert-option/13632)".
