### ISSUE TITLE
WebDAV sync issue on all iOS devices on even the latest version by failing to send network requests when using domain names instead of IP addresses

### ISSUE THREAD

**Issue by bogao** [laurent22/joplin#6565]
Platform: Android, iOS
Version: All versions including the latest ones
Symptom:
Cannot sync on WebDAV when using HTTPS protocol instead of HTTP protocol, or domain names instead of IP addresses in URL.
It **only** works when using HTTP protocol + IP address in URL.
Indicating there is a certification verification or a name resolution issue.
Since all devices are experiencing the same symptom so it can easily reproduce so an error log becomes unnecessary.
And also I find that there are so many issues reporting the same problem with very detailed error logs already.

Please fix it as it is a serious bug affecting core experience of a core feature - sync.

**Comment by OdinVex** [comment]
Joplin doesn't use the Android (I don't know about iOS) certificate store, so any certificates self-signed or by a Certificate Authority not already trusted by Joplin will not work. It really sucks, but no headway has been made on it that I know. I filed a [bug](https://github.com/laurent22/joplin/issues/5871) for the same issue. I'm forced to VPN to my internal network and use http with a rooted phone that firewalls Joplin unless it is operating over VPN, just to protect privacy.

I don't use JavaScript (hate anything Java*), but this 'NodeJS/Yarn' stuff seems to have some http-request flags you can specify: `rejectUnauthorized: false` might work...if I understand this project any at all. I don't do Android development, the IDE was so horribly put together back in the day that I couldn't even do a simple helloWorld&deploy to phone despite my having years of experience with Arm, embedded OS development, much more.

**Comment by bogao** [comment]
> 

Thanks for the reply but the issue is not quite related with certificate in the first place, but domain name resolution.

For example:
http://132.45.23.122/webdav will work but
http://name.of.myjoplinhost.com/webdav will not
(Both the IP address and the domain name are false, just for description purpose.)

As the example above uses only HTTP instead of HTTPS, it has nothing to do with certificate.

The reason why it is an annoying issue is that many, many family users are using Dynamic Domain Names, which uses a fixed domain name to resolve to dynamic IP addresses which change every time the router restarts.

Since this bug only appears on mobile devices but not on Windows I suppose it is related to some network library Joplin uses.

Getting this bug resolve will make Joplin an almost perfect solution for note taking software supporting almost every platform in the client side and self-hosting in the server side.

**Comment by OdinVex** [comment]
> > 
> 
> Thanks for the reply but the issue is not quite related with certificate in the first place, but domain name resolution.
> 
> For example: http://132.45.23.122/webdav will work but http://name.of.myjoplinhost.com/webdav will not (Both the IP address and the domain name are false, just for description purpose.)
> 
> As the example above uses only HTTP instead of HTTPS, it has nothing to do with certificate.
> 
> The reason why it is an annoying issue is that many, many family users are using Dynamic Domain Names, which uses a fixed domain name to resolve to dynamic IP addresses which change every time the router restarts.
> 
> Since this bug only appears on mobile devices but not on Windows I suppose it is related to some network library Joplin uses.
> 
> Getting this bug resolve will make Joplin an almost perfect solution for note taking software supporting almost every platform in the client side and self-hosting in the server side.

Ah, my bad. I immediately saw the comparisons to HTTP/S with WebDav and something “not working”.

I've no trouble using like that. I use http://fqdn.tld/ just fine. DNS-record updates can take time to propagate. I've seen mobile phone's DNS servers not get a record update for well over a few hours. That mostly occurred while I was setting up my own stuff. Despite my ISP giving dynamic IPs, even across modem restarts, I've had the same for a few years now, luckily. :) But still, mine works fine. Have you determined the actual DNS servers being queried by your phone to look at the raw data to determine if the correct IP is being used?

**Comment by bogao** [comment]
> > > 
> > 
> > 
> > Thanks for the reply but the issue is not quite related with certificate in the first place, but domain name resolution.
> > For example: http://132.45.23.122/webdav will work but http://name.of.myjoplinhost.com/webdav will not (Both the IP address and the domain name are false, just for description purpose.)
> > As the example above uses only HTTP instead of HTTPS, it has nothing to do with certificate.
> > The reason why it is an annoying issue is that many, many family users are using Dynamic Domain Names, which uses a fixed domain name to resolve to dynamic IP addresses which change every time the router restarts.
> > Since this bug only appears on mobile devices but not on Windows I suppose it is related to some network library Joplin uses.
> > Getting this bug resolve will make Joplin an almost perfect solution for note taking software supporting almost every platform in the client side and self-hosting in the server side.
> 
> Ah, my bad. I immediately saw the comparisons to HTTP/S with WebDav and something “not working”.
> 
> I've no trouble using like that. I use http://fqdn.tld/ just fine. DNS-record updates can take time to propagate. I've seen mobile phone's DNS servers not get a record update for well over a few hours. That mostly occurred while I was setting up my own stuff. Despite my ISP giving dynamic IPs, even across modem restarts, I've had the same for a few years now, luckily. :) But still, mine works fine. Have you determined the actual DNS servers being queried by your phone to look at the raw data to determine if the correct IP is being used?

Are you using it on your mobile device? The issue is not related to DNS update propagate. If it is, the result will be resolving fqdn.tld to an incorrect IP address (old rather than new), instead of not resolving at all.

The symptom is that it simply reports a "Network request failed" error, and I doubt the network request has never been raised, that said, the error may occur **before** name resolution.

**Comment by OdinVex** [comment]
> > > > 
> > > 
> > > 
> > > Thanks for the reply but the issue is not quite related with certificate in the first place, but domain name resolution.
> > > For example: http://132.45.23.122/webdav will work but http://name.of.myjoplinhost.com/webdav will not (Both the IP address and the domain name are false, just for description purpose.)
> > > As the example above uses only HTTP instead of HTTPS, it has nothing to do with certificate.
> > > The reason why it is an annoying issue is that many, many family users are using Dynamic Domain Names, which uses a fixed domain name to resolve to dynamic IP addresses which change every time the router restarts.
> > > Since this bug only appears on mobile devices but not on Windows I suppose it is related to some network library Joplin uses.
> > > Getting this bug resolve will make Joplin an almost perfect solution for note taking software supporting almost every platform in the client side and self-hosting in the server side.
> > 
> > 
> > Ah, my bad. I immediately saw the comparisons to HTTP/S with WebDav and something “not working”.
> > I've no trouble using like that. I use http://fqdn.tld/ just fine. DNS-record updates can take time to propagate. I've seen mobile phone's DNS servers not get a record update for well over a few hours. That mostly occurred while I was setting up my own stuff. Despite my ISP giving dynamic IPs, even across modem restarts, I've had the same for a few years now, luckily. :) But still, mine works fine. Have you determined the actual DNS servers being queried by your phone to look at the raw data to determine if the correct IP is being used?
> 
> Are you using it on your mobile device? The issue is not related to DNS update propagate. If it is, the result will be resolving fqdn.tld to an incorrect IP address (old rather than new), instead of not resolving at all.
> 
> The symptom is that it simply reports a "Network request failed" error, and I doubt the network request has never been raised, that said, the error may occur **before** name resolution.

Yes, my mobile devices, all of them. I have no trouble with using IP or DNS. I suggested checking the DNS, as it is technically possible. The difference here is the URI. IP, unmistakable to connect with, versus DNS, which *could* be behind, thus resulting in a network request that fails. Merely suggested double-checking, it is reasonable.

I do feel that “Network request failed” is an extremely vague error. You can always hop on WiFi and dump packets to check.

**Comment by bogao** [comment]
Could you please kindly help test the following sync configuration on iOS (any version from 12.x to 15.x)?

Type: WebDAV
WebDAV URL: http://notes.i8u8.com:8888/home/joplin
WebDAV Username: ghtest
WebDAV Password: QySqsiXY%$L2v#XM5W

The same configuration works on all desktop versions.

**Comment by OdinVex** [comment]
> 

I only have Android devices. Successful connection, though login failed (401, could be wrong directory or authentication parameters). As a good habit to get into, it's best to avoid passwords that use certain `;#"'$&+'!\` symbols. Many software libraries and backends have issues with them, mostly due to assumptions made about encoding, but still. ;)

**Comment by bogao** [comment]
OK I changed the password. The new configuration comes as follows:

Type: WebDAV
WebDAV URL: http://notes.i8u8.com:8888/home/joplin
WebDAV Username: ghtest
WebDAV Password: jqJ7aqrHmyvN3dMmGD

And I tested again on all desktop versions, all work. And also this even now works for Android devices!
But for iOS devices it still fails.

**Comment by OdinVex** [comment]
> OK I changed the password. The new configuration comes as follows:
> 
> Type: WebDAV WebDAV URL: http://notes.i8u8.com:8888/home/joplin WebDAV Username: ghtest WebDAV Password: jqJ7aqrHmyvN3dMmGD
> 
> And I tested again on all desktop versions, all work. And also this even now works for Android devices! But for iOS devices it still fails.

We've determined that there is possibly an encoding issue relating at least to authentication on Android, then (if password was correct both times). As for iOS, I think only the developer or someone more familiar with the iOS backend in use could explain. You said this all works if you use IPs but not domains? I'm wondering if the method used to authenticate is being misformatted. @laurent22 might know best. There is nothing left in the username or password that could throw parsing off for any standard library, my guess is the formatting done by Joplin.

**Comment by bogao** [comment]
> > OK I changed the password. The new configuration comes as follows:
> > Type: WebDAV WebDAV URL: http://notes.i8u8.com:8888/home/joplin WebDAV Username: ghtest WebDAV Password: jqJ7aqrHmyvN3dMmGD
> > And I tested again on all desktop versions, all work. And also this even now works for Android devices! But for iOS devices it still fails.
> 
> We've determined that there is possibly an encoding issue relating at least to authentication on Android, then (if password was correct both times). As for iOS, I think only the developer or someone more familiar with the iOS backend in use could explain. You said this all works if you use IPs but not domains? I'm wondering if the method used to authenticate is being misformatted. @laurent22 might know best. There is nothing left in the username or password that could throw parsing off for any standard library, my guess is the formatting done by Joplin.

Thanks for your time taking care of this bug in advance.

- Android works for both passwords. I did not see the issue you saw.
- iOS works if I replace the domain name with the corresponding IP address (you may use `dig` or `ping` to get the IP address of `notes.i8u8.com` as it is a dynamic one, and that's exactly why I have to use a domain name instead of an IP address).

**Comment by OdinVex** [comment]
> Thanks for your time taking care of this bug in advance.
> 
>     * Android works for both passwords. I did not see the issue you saw.
> 
>     * iOS works if I replace the domain name with the corresponding IP address (you may use `dig` or `ping` to get the IP address of `notes.i8u8.com` as it is a dynamic one, and that's exactly why I have to use a domain name instead of an IP address).

Weird, the first password didn't work for me for Android. 401, Unauthorized, eg bad password (either from encoding or wrong password sent/copied). Maybe I copied it wrong, though I do use KDEConnect, and it copies clipboards if set to. Glad it works for you on Android.

The only thing I can think of for iOS is maybe there is something about iOS that either blocks non-standard ports (8888 is odd...) or some iOS backend is screwing up the URI. Try Joplin temporarily on either 80 or 443. Just temporarily. If it works, try indicating the port in the URI, such as `notes.i8u8.com:80` or `notes.i8u8.com:443`. If it fails then (make sure Joplin is on those ports) then it is a backend issue parsing the URI/handling.

**Comment by bogao** [comment]
> 

Can you help involve @laurent22 or some experts in iOS to kindly look at this bug? I do not think it is related to non-standard port as the reproducing process clearly shows that when using IP addresses with the same port it works like a charm. So, the bug is quite likely having nothing to do with the port.

**Comment by OdinVex** [comment]
> > 
> 
> Can you help involve @laurent22 or some experts in iOS to kindly look at this bug? I do not think it is related to non-standard port as the reproducing process clearly shows that when using IP addresses with the same port it works like a charm. So, the bug is quite likely having nothing to do with the port.

I'm just a regular guy with no association to the project other than my own bug-filing. :/ If it works with IP:Port, then I'm clueless save for any iOS-specific backend. :/ I had forgotten you were able to get it with IP:Port.

**Comment by bogao** [comment]
It seems that no contributor cares about this post. :'(

**Comment by OdinVex** [comment]
@bogao, ... Any way... You can always look into it.

**Comment by gotoorder** [comment]
@bogao I've got a problem just like yours, but haven't found a solution so far
