### ISSUE TITLE
Android Joplin Fails to Sync Pictures Added on PC

### ISSUE THREAD

**Issue by 5chi-3cun-4fen** [laurent22/joplin#6570]
Not sure if this is a bug but it really bothers me greatly.
After I add pictures to my note on PC and sync my notes.(First on PC, then on my android phone.)
Texts and other attachments are good but pictures added on my PC can't be displayed normally.
This is what it looks like on my phone. I can't see or open the pictures.
![图片](https://user-images.githubusercontent.com/69151247/172827129-90e461e4-f367-415f-a0d8-7b4410458064.png)
This is what it looks like on my PC.
![图片](https://user-images.githubusercontent.com/69151247/172827928-62c7a378-9ea9-416f-8fc5-5873e26c1c6e.png)

If I add a picture on my android phone, it can be displayed well.

## Environment

Joplin version: 2.72 (Android) 2.88(WIndows)
Platform: Android, PC
OS specifics: MIUI 12.5.8/Android 11

## Steps to reproduce

1. Open the PC version and add a picture to any note. Sync after that.
2. Then sync on Android.
3. Pictures added on PC can't be displayed normally on Android.

## Describe what you expected to happen
Pictures added on PC can be displayed normally on my Android phone after syncing.

**Comment by SFulpius** [comment]
From looking at the pictures, your username contains non-ASCII characters. Can you try these steps to see if this is your bug?

Steps to reproduce:
1. The Joplin resource directory path must contain some non-ASCII characters.
2. Create a new note.
3. Using the markdown editor, attach an image to the note. The link to the image looks like ./12345.
4. Switch to the WYSIWYG editor and make some changes to the note (e.g. add some text below the image).
5. Switch back to markdown. The link to the image is now the full windows path (file:///C:/...).

**Comment by 5chi-3cun-4fen** [comment]
> From looking at the pictures, your username contains non-ASCII characters. Can you try these steps to see if this is your bug?
> 
> Steps to reproduce:
> 
>     1. The Joplin resource directory path must contain some non-ASCII characters.
> 
>     2. Create a new note.
> 
>     3. Using the markdown editor, attach an image to the note. The link to the image looks like ./12345.
> 
>     4. Switch to the WYSIWYG editor and make some changes to the note (e.g. add some text below the image).
> 
>     5. Switch back to markdown. The link to the image is now the full windows path (file:///C:/...).

yes this is exactly my bug
