### ISSUE TITLE
Changing the destination bucket for S3 sync, results in pre-existing notes being lost when next edited

### ISSUE THREAD

**Issue by pauldoo** [laurent22/joplin#6572]
## Environment

Joplin version: 2.8.8 (installed from [Flathub](https://flathub.org/apps/details/net.cozic.joplin_desktop))
Platform: Linux
OS specifics: Ubuntu 20.04

## Steps to reproduce

1. Enable synchronisation using an S3 bucket.
2. Save and sync some notes.
3. Edit the synchronisation setting to use a *different* S3 bucket.
4. Edit one of the existing notes, and sync it.
5. Wait a moment, then edit the same note further.
6. Observe that the note will be deleted and the contents apparently lost.

Note: _New_ notes created after step 3 are not lost when sync'd.

Further note: I also suspect, but cannot confirm, that the tags have been lost in Joplin.  They are no longer displayed in the left-hand panel.

## Describe what you expected to happen

I expect to be able to change the S3 bucket I sync to, and not lose pre-existing notes when I next next edit and sync.

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/8873699/log.txt)

**Comment by pauldoo** [comment]
I was able to stop notes from being further delete by using the "Re-upload local data to sync target" button in the advanced section of the synchronisation settings.

However, there was still an issue with tags not displaying...   I realised that the notes folder structure had been completely lost, and the UI showing the folders and list of tags wasn't displaying.  I was able to recover this by doing the following:
1. Export all my notes (I used markdown format).
2. Close Joplin.
3. Delete my local profile (`~/.config/joplin-desktop` and `~.var/app/net.cozic.joplin_desktop` directories).
4. Start Joplin, and re-import the notes I exported in step 1.  I had to manually put them back into the notebooks I wanted, and re-tag them.
5. Delete the contents of my remote S3 bucket.
6. Re-configure Joplin synchronization.

---

While I have been able to fix my personal problems here, I think there are some rough edges in Joplin if the user wants to change the S3 bucket they want to sync to.  Perhaps changing the S3 bucket shouldn't be permitted.. (?)

**Comment by Daeraxa** [comment]
When you change the target within a sync "type" then Joplin thinks the target is blank and proceeds to try to wipe the data (although it should activate the failsafe before anything is actually deleted from your local machine).
This FAQ topic is for WebDAV but it is relevant - https://joplinapp.org/faq/#all-my-notes-got-deleted-after-changing-the-webdav-url

**Comment by pauldoo** [comment]
Thanks for the link to the FAQ about this.  It's quite a sharp edge in the behaviour of the app.  It would be neat if there was a warning in the app itself about changing the sync destination.

**Comment by Daeraxa** [comment]
The fail safe should have activated as far as I'm aware. If it detects an empty sync target then usually it will kick in and say something along the lines of "you are about to delete all of your notes" and you have to manually untick the fail safe in the options to force it. Did this not happen in your case?

**Comment by pauldoo** [comment]
No alert about a fail safe appeared..  but equally notes didn't disappear all at once.  In that regard maybe the failsafe did work..?

Individual notes were definitely deleted after I made modifications to them (as I wrote in the steps to reproduce).
