### ISSUE TITLE
Joplin Sync sometimes ignores updated notes (file based sync via shared OneDrive folder)

### ISSUE THREAD

**Issue by rshalaev** [laurent22/joplin#6574]
## Environment

Joplin version: 2.7.13 (prod, win32)
Platform: Windows 10 x64
Sync via OneDrive shared folder

## Problem
Joplin is ignoring updated notes

I have Joplin setup on several Linux and Windows computers that sync via OneDrive. I'm observing behavior on one Windows PC where Joplin is failing to update a note that's been updated on another PC. File in OneDrive shared folder is showing newer timestamp than the note in Joplin, yet Joplin is not updating that note.

This has been a reoccurring issue. I'll add more details as I investigate this.

**Comment by rshalaev** [comment]
I've used suggestion from this thread:
[Sync silently ignores new files with old timestamps #6517](https://github.com/laurent22/joplin/issues/6517)

`for /f %a in ('dir /b *.md') do copy /b %a+`

To update modified timestamp to the current date for all `.md` files in Joplin sync directory. This fixed the problem, although still not sure why it occurred in the first place.

**Comment by laurent22** [comment]
I guess the main bug would be #6517, so closing this one in favour of the other.
