### ISSUE TITLE
Fatal Error on Apple OS M1

### ISSUE THREAD

**Issue by tamarue** [laurent22/joplin#6579]
Error
Joplin encountered a fatal error and could not continue.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/laurent22/joplin/issues/new?assignees=&labels=bug&template=bug_report.md&title=#), which will temporarily disable all plugins.

Message
Cannot read properties of null (reading 'wrappedInstance')

Version info
Joplin for Desktop

Copyright © 2016-2022 Laurent Cozic
Joplin 2.8.8 (prod, darwin)

Client-ID: 0cd91c3e621d45e087e45e193cd26f1d
Sync-Version: 3
Profil-Version: 41
Unterstützter Schlüsselbund: Ja

Revision: c2a6a13
Plugins
[
    {
        "id": "joplin.plugin.benji.favorites",
        "name": "Favorites",
        "enabled": true,
        "version": "1.3.0"
    },
    {
        "id": "com.lki.homenote",
        "name": "Home Note",
        "enabled": true,
        "version": "1.0.4"
    },
    {
        "id": "com.github.joplin.kanban",
        "name": "Kanban",
        "enabled": false,
        "version": "1.0.5"
    },
    {
        "id": "com.andrejilderda.macOSTheme",
        "name": "macOS theme",
        "enabled": false,
        "version": "1.2.14"
    },
    {
        "id": "io.treymo.LinkGraph",
        "name": "Link Graph UI",
        "enabled": false,
        "version": "1.2.0"
    },
    {
        "id": "org.joplinapp.plugins.ToggleSidebars",
        "name": "Note list and sidebar toggle buttons",
        "enabled": false,
        "version": "1.0.3"
    },
    {
        "id": "io.github.jackgruber.note-overview",
        "name": "Note overview",
        "enabled": false,
        "version": "1.5.5"
    },
    {
        "id": "joplin.plugin.note.tabs",
        "name": "Note Tabs",
        "enabled": false,
        "version": "1.4.0"
    },
    {
        "id": "outline",
        "name": "Outline",
        "enabled": true,
        "version": "1.3.1"
    },
    {
        "id": "com.whatever.quick-links",
        "name": "Quick Links",
        "enabled": true,
        "version": "1.2.3"
    },
    {
        "id": "com.gitlab.BeatLink.joplin-plugin-repeating-todos",
        "name": "Repeating To-Dos",
        "enabled": true,
        "version": "0.7.0"
    },
    {
        "id": "joplin.plugin.templates",
        "name": "Templates",
        "enabled": false,
        "version": "2.2.0"
    },
    {
        "id": "io.github.jackgruber.backup",
        "name": "Simple Backup",
        "enabled": true,
        "version": "1.0.5"
    },
    {
        "id": "com.gitlab.BeatLink.joplin-plugin-agenda",
        "name": "Agenda",
        "enabled": false,
        "version": "3.0.1"
    },
    {
        "id": "ylc395.betterMarkdownViewer",
        "name": "Better Markdown Viewer",
        "enabled": true,
        "version": "2.0.4"
    },
    {
        "id": "com.eliasvsimon.email-note",
        "name": "Email Note",
        "enabled": true,
        "version": "1.2.2"
    },
    {
        "id": "ylc395.noteLinkSystem",
        "name": "Note Link System",
        "enabled": true,
        "version": "0.5.0"
    },
    {
        "id": "plugin.calebjohn.rich-markdown",
        "name": "Rich Markdown",
        "enabled": true,
        "version": "0.8.3"
    },
    {
        "id": "org.joplinapp.plugins.admonition",
        "name": "Admonition markdown extension",
        "enabled": true,
        "version": "1.1.0"
    }
]
Stack trace
TypeError: Cannot read properties of null (reading 'wrappedInstance')
    at /Applications/Joplin.app/Contents/Resources/app.asar/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.js:646:32
    at commitHookEffectList (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:19986:26)
    at commitPassiveHookEffects (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:20016:11)
    at HTMLUnknownElement.callCallback (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:397:16)
    at invokeGuardedCallback (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:454:31)
    at flushPassiveEffectsImpl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22868:7)
    at unstable_runWithPriority (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:643:12)
    at runWithPriority$2 (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11305:10)
    at flushPassiveEffects (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22841:10)
Component stack

    in ForwardRef(CodeMirror) (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by ResizableLayout)
    in div (created by styled.div)
    in styled.div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in ResizableLayout (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in ThemeProvider (created by RootComponent)
    in StyleSheetManager (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider

**Comment by laurent22** [comment]
Fixed in #6506
