### ISSUE TITLE
Ios: Insert a photo into a note

### ISSUE THREAD

**Issue by refue** [laurent22/joplin#658]
### Operating system

- iOS (11)

### Application

- Mobile (10.0.24)

I insert a new  note and fill the subject and the body. So I take the photo. Then I would like to to insert it.
 But nothing happens. The body of the note is still empty.

<img width="285" alt="image1" src="https://user-images.githubusercontent.com/16164686/42137261-a1acabda-7d69-11e8-837e-04b31dfbace5.png">

**Comment by jdeutsch** [comment]
Same on Android  8.1.0

**Comment by zarenzeit** [comment]
Same on LineageOS 15.1 (Android 8.1.0).

**Comment by mcteefax** [comment]
Same like "dazrt" using iOS 11.4.1; Using Kamera is allowed.
Would be a SUPER feature.

**Comment by laurent22** [comment]
Note: Maybe use this package: https://github.com/react-native-community/react-native-camera

**Comment by diver-down** [comment]
Same, _insert photo from camera_ does not work on mobile app on any iOS devices.

**Comment by protree** [comment]
Same here on iOS 12

**Comment by laurent22** [comment]
Closing stale issue.

**Comment by diver-down** [comment]
Hopefully adding this comment doesn't re-open the issue (I'm still a bit new to GitHub)... I just wanted to give feedback that YES, the camera on all of our iOS devices, tablets and phones, now works beautifully. Thanks again laurent22  :)

**Comment by laurent22** [comment]
Great, thanks for confirming!

**Comment by somaGFX** [comment]
On iOS there is only one option to attach a photo. If I click it I can take a picture but I cannot choose any from my photos library. Also the Button attache any file doesn't let me choose something from my photos library just something that is stored in the stu… files app. 

Using the latest iOS 12.1 on an XS max.

**Comment by diver-down** [comment]
Can confirm, same issue on my end now that I try. Photo insertion from the camera roll isn’t an option, only the camera (via Attach Photo) and the file picker (which oddly enough doesn’t access your photos?) are there. 

Hope this helps!
