### ISSUE TITLE
When typing in foreign language (Korean), Joplin adds random lines below. 

### ISSUE THREAD

**Issue by Jae0143** [laurent22/joplin#6583]
## Environment

Joplin version: 2.8.8
Platform: Mac OS Monterey
OS specifics: 12.4

## Steps to reproduce

1. Type in foreign language 
2. Seems like when there is "Scheduling sync operation... 30000", the error occurs

https://user-images.githubusercontent.com/39797496/173930524-da7628c3-9103-4997-a0f4-bec9912456b7.mov

3. 

## Describe what you expected to happen
I do not expect the repetition of line to take place 

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/8913188/log.txt)

**Comment by tomasz1986** [comment]
This looks very weird. I type in Korean regularly myself, and I've never seen anything like that.

Do you use any 3rd party plugins? Do you experience the problem in safe mode as well? Just in case, safe mode is available under Help in the top menu.

**Comment by yanggthomas** [comment]
Hi, I encounter the same problem even when typing English. Did you solve this problem? @Jae0143 
This is really annoying and I have to use an external markdown editor.
