### ISSUE TITLE
Ios: Insert attachment don't work

### ISSUE THREAD

**Issue by refue** [laurent22/joplin#659]
### Operating system

- iOS (11)

### Application

- Mobile (10.0.24)

I insert a new note with subject and body. Then I want to insert an attachment. But this don't work (local filesystem of ios and cloud).

<img width="287" alt="local" src="https://user-images.githubusercontent.com/16164686/42137321-d81743d2-7d6a-11e8-8d8d-9b2847d8b65a.png">

<img width="285" alt="cloud" src="https://user-images.githubusercontent.com/16164686/42137323-ddd9b3fe-7d6a-11e8-9c2e-0473010dee9b.png">

<img width="285" alt="log" src="https://user-images.githubusercontent.com/16164686/42137325-e5a5a7e6-7d6a-11e8-8b6e-caf3c5e80d73.png">

**Comment by laurent22** [comment]
Did you try with other files?

**Comment by refue** [comment]
Yes, now I tried some other files. Only *.jpg work.
