### ISSUE TITLE
vim mode is usable only with "eng"(latin) keyboard layout

### ISSUE THREAD

**Issue by floppy-engineer** [laurent22/joplin#6591]
The editor in VIM mode working properly (follows vim commands) only when keyboard layout is set to English. As a result vim mode is workable only on English.

## Environment

Joplin version: 2.7.15 (appimage)
Platform: Linux
OS specifics: Manjaro, KDE, x11

## Steps to reproduce

1. set to vim mode in preferences
2. focus on input field of markdown editor in markdown source code mode
3. having english keyboard layout press Shift+i
4. Ensure that the cursor change the shape and you are in insert mode - you could enter text
5. Press ESC and exit from insert mode
6. Switch layout to non-latin
7. Try to enter into insert mode by pressing Shift+i.
8. The editor is still in command mode (you can't enter text)

## Describe what you expected to happen

That default shourtcuts(shift-i, ctrl-o, etc) and commands work as if keyboard layout is set to Eng

**Comment by personalizedrefrigerator** [comment]
We're using a library for ViM emulation in the editor. [CodeMirror5 ViM emulation library](https://codemirror.net/5/demo/vim.html).

This seems related to the following upstream issue: https://github.com/codemirror/codemirror5/issues/6771

**Comment by floppy-engineer** [comment]
I get it. You don't support the library.
But instead would it be possible to add configuration ability to the module? Like .vimrc file somewhere. It's possible to work around the behavior with vim magic)  
Thanks in advance

**Comment by personalizedrefrigerator** [comment]
We're currently using CodeMirror5 for the editor. There is also vim emulation for CodeMirror6 (which we might eventually switch to).

The [CodeMirror6 ViM emulation can be demoed here](https://replit.com/@util/codemirror-vim). Is the issue fixed with the CodeMirror6 version?
