### ISSUE TITLE
Almost blank screen. Joplin unusable.

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#6593]
## Environment

Joplin version: 12.8.1
Platform: ios 15.5
OS specifics: ipad pro 9,7”

## Steps to reproduce

1. Edit a note
2. Tap back arrow or close keyboard
3. Bug: Screen footer moves up and only the note title stays visible. UI is not visible anymore4. 
4. Hit title to start editing again.5. 
5. Tap back arrow or hide keyboard stop editing6. 
6. Bug: Screen scrolls up and all text is gone.
![AFAF37F4-DD7D-4191-912F-FC529426E495](https://user-images.githubusercontent.com/87373763/174405596-2a8ec523-ab34-4d56-8913-65787bb1d96c.jpeg)
![6CAFC292-B323-4FE7-B591-B0E8A5AF12A9](https://user-images.githubusercontent.com/87373763/174405600-aeda49b4-bc79-4117-bfb6-23e11ce09cfa.jpeg)
![329D8E55-8C12-4D08-9FDA-7CB41FD5CAA3](https://user-images.githubusercontent.com/87373763/174405603-b3dffaa3-831d-43f7-ba99-7d9bff132dee.jpeg)
![3D0EE7BA-9DC4-41DA-9F54-1B6DB43E171E](https://user-images.githubusercontent.com/87373763/174405605-1a41789c-5a29-4c88-9b9f-4ca7b21f8920.png)

7. Restart of the app is needed to get a full screen again.5. 

## Describe what you expected to happen
1 Editor screen closes
2 note is readable and navigation is possible

**Comment by nwabeen** [comment]
same issue on iPhone 8

This important issue needs to be fixed because it makes adding / editing notes completly unusable on iOS.

**Comment by treaz** [comment]
+1

**Comment by ghost** [comment]
This bug has been around for a while, using iPhone SE 2020. It does indeed make the Joplin iOS app unusable for any practical purposes, which is very unfortunate, because I love Joplin on my desktop!

**Comment by treaz** [comment]
as far as I'm concerned, this can be closed as I switched from Joplin to something else.

**Comment by ghost** [comment]
No, not solved. Joplin 12.8.1 not useable on iPad air 5th generation, iOS 15.5
