### ISSUE TITLE
Bug report: Strange behavior of "^"

### ISSUE THREAD

**Issue by Paulhilaire** [laurent22/joplin#6601]
Hi,
First thank you for the excellent app!
I've just found out a keyboard bug when using it. I am using a french (azerty) keyboard and Windows 10, and whenever I am using the key " ^ " + any key which doesn't combine with it, it goes back to the beginning of the note. By that I mean that " ^ + e" is fine and give the normal output " ê ", but if I do something such as " ^ + p ", the bug occurs and the cursor goes back to the beginning of the note (^p is written where my cursor was...).
It is particularly inconvenient given that the "^" is of easy access on azerty keyboard and is also very close to the "$" that I use a lot to write maths.

## Environment

Joplin version: Joplin 2.8.8
Platform: Windows
OS specifics:  Windows 10

## Steps to reproduce

1.  write something + place a cursor somewhere else than the beginning of the document
2. press the key ^ followed by any key that doesn't combine well with it (e.g. "^" + "k"), on an azerty keyboard
3. the cursor should be at the beginning of the note you are writing.

## Describe what you expected to happen

I would expect to obtain the normal result as for other editor (e.g. for "^+k" -> "^k") and not moving the cursor to the beginning of the doc

## Logfile

I didn't manage to produce a debug log... Sorry!

Thank you for the nice software, and in advance for the bug fix!
Best,
Paul

**Comment by Daeraxa** [comment]
I think this is a duplicate/extension of these two related issues, could you check the info there and see if it the same issue?

https://github.com/laurent22/joplin/issues/6256
https://github.com/laurent22/joplin/issues/6460
