### ISSUE TITLE
File invalidation after synchronization

### ISSUE THREAD

**Issue by zR00t1** [laurent22/joplin#6602]
## Environment

Joplin version: v2.8.8
Platform: Windows
OS specifics: Windows 10 Home

## Steps to reproduce

1. I use TeraCLOUD's WebDAV for backup，Synchronize local resources to TeraCLOUD
2. I delete all resources on the PC and synchronize resources from TeraCLOUD
3.  all downloaded images cannot be used. The attachments in the "tools->note attachments" interface are normal, but all image resources in the "Joplin desktop\resources" directory cannot be used，So the notes cannot be displayed

![image](https://user-images.githubusercontent.com/46400438/174696004-de8f573b-b861-4d7a-9299-271714367510.png)

![image](https://user-images.githubusercontent.com/46400438/174696096-b5a35e47-fe00-4183-90d0-5517aeca5e0b.png)

![image](https://user-images.githubusercontent.com/46400438/174697893-16167348-b19f-41ac-afd6-779302afc67a.png)

## Describe what you expected to happen

Fix these invalid picture files,
Provide a stable synchronization method,
Explain the cause of the problem

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/8945021/log.txt)

**Comment by Daeraxa** [comment]
What is the markdown for those resource links?
I think there is an issue logged that if any extended ascii is used in the file path then it converts it to a local path when it goes through the richtext -> md conversion which is then invalid.
