### ISSUE TITLE
Checkboxes and copy : disparition of the checkboxes !

### ISSUE THREAD

**Issue by fanofjop** [laurent22/joplin#6603]
Hello, I'm new and it's my first post. 

I had a look in the base with the keyword "checkbox" with no success. Maybe it's me... 

Anyway :

## Environment

Joplin version: 2.8.8
Platform: Windows 7 and others (windows 10, Kubuntu...)
OS specifics: 

## Steps to reproduce

1. create many checkboxes in a note (richtext editor)
2. copy them
3. paste them elsewhere (just some lines below for example)
4. the checkbox disapear. There's only the text of them and no spaces between
![image](https://user-images.githubusercontent.com/107914828/174748860-4810b068-c883-4d58-b429-e12750b202c2.png)
![image](https://user-images.githubusercontent.com/107914828/174752742-89501b8e-bda5-4ee0-b3f6-1e376210639a.png)

## Describe what you expected to happen
It would be normal that a copy/paste change nothing ! It a lost of time to rebuild the checkboxes everytime you copy one ! And there is a risk to make mistakes with the text.

## Logfile

YES BUT...
- The log.txt is 17 Mo !
- I don't know what to copy in the debug mode console !

Thank you very much for your help

**Comment by tomasz1986** [comment]
Not a real fix, but if you paste using the mouse (right click -> paste) instead of using Ctrl+V , then the formatting will be preserved.

**Comment by fanofjop** [comment]
Thank you very much for this tip ! It's not perfect (the checkbox list turns into bulleted list) but the more important is not everything is mixed !!!
Have a good day...
Stéphane, le  Mardi 21 Juin 2022  15:31 (France)
________________________________
De : tomasz1986 ***@***.***>
Envoyé : mardi 21 juin 2022 11:15
À : laurent22/joplin ***@***.***>
Cc : fanofjop ***@***.***>; Author ***@***.***>
Objet : Re: [laurent22/joplin] Checkboxes and copy : disparition of the checkboxes ! (Issue #6603)


Not a real fix, but if you paste using the mouse (right click -> paste) instead of using Ctrl+V , then the formatting will be preserved.

**Comment by laurent22** [comment]
I cannot replicate on macOS. It works fine with Cmd+V, right click or paste from menu.

**Comment by laurent22** [comment]
Could someone confirm it does it consistently on Windows?

**Comment by JackGruber** [comment]
Yes under Windows 10, Joplin 2.9.1 I can replicate this behavior with `Cmd + V`, with the context menue the checkboxes are converted to bullet points.

**Comment by pedr** [comment]
```
Joplin 2.10.5 (prod, linux)

Client ID: 14baeec429d24d84a5c2580de09d6247
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: c9b49a5
```

Is the Ctrl+Shift+V broken in this case, @laurent22? I will test on Windows next.

![image](https://user-images.githubusercontent.com/5051088/223106071-beb60373-20b9-4711-b075-47d2a5a1ef0a.png)

**Comment by laurent22** [comment]
Ctrl+Shift+V looks good in this case. Yes it seems to be a Windows only issue for some reason. I couldn't replicate on macOS eitehr

**Comment by pedr** [comment]
The Windows behavior is equal to the Linux one. I don't think this is a bug, but I found two odd behaviors with the Past as Text functionality that need to be fixed:

- Using Ctrl+Shift+V on Linux paste the content two times.
- Using the Context Menu option Paste as Text on Windows does not work (no content is added to the editor).

**Comment by pedr** [comment]
I think we can close this issue since the original problem was already fixed @laurent22

**Comment by laurent22** [comment]
That's true, let's close it
