### ISSUE TITLE
WebDAV sync Error: href

### ISSUE THREAD

**Issue by traversebitree** [laurent22/joplin#6604]
## Environment

Joplin version: 2.8.8
Platform: Windows 11
WebDAV Server Platform: Windows 11 with IIS 10.0

### Case 1: WebDAV sync with the external domain using port forwarding
I use DDNS to penetrate my intranet, the external domain is EXAMPLEDOMAIN.com, and the forwarding port is 60000.
I set the sync target as WebDAV, the WebDAV URL as `http://EXAMPLEDOMAIN.com:60000/NasWebDAV/Ddisk/Joplin/`.
Then can see the error:
**`Error: href http://EXAMPLEDOMAIN.com/NasWebDAV/Ddisk/Joplin/locks/ not in baseUrl http://EXAMPLEDOMAIN.com:60000/NasWebDAV/Ddisk/Joplin nor relativeBaseUrl /NasWebDAV/Ddisk/Joplin`**

**Note**: the first URL **doesn't have** a port ":60000", and the second URL has the port ":60000".

### Case 2: WebDAV sync with the local area network IP address using port 80 (**explicitly**)
My server's IP address is 192.168.1.2, and the WebDAV port is 80.
I set the sync target as WebDAV, the WebDAV URL as `http://192.168.1.2:80/NasWebDAV/Ddisk/Joplin/`.
Then can see the error:
**`Error: href http://192.168.1.2/NasWebDAV/Ddisk/Joplin/locks/ not in baseUrl http://192.168.1.2:80/NasWebDAV/Ddisk/Joplin nor relativeBaseUrl /NasWebDAV/Ddisk/Joplin`**

**Note**: the first URL **doesn't have** a port ":80", and the second URL **has** the port ":80".

### Case 3: WebDAV sync with the local area network IP address using port 80 (**not explicitly**)
My server's IP address is 192.168.1.2, and the WebDAV port is 80.
I set the sync target as WebDAV, the WebDAV URL as `http://192.168.1.2/NasWebDAV/Ddisk/Joplin/`. (Not appoint the port ":80", and use the 80 port default.)

Then successfully synchronized.

In all three cases, when I check the synchronous configuration, all are successful, but things go wrong when syncing.

## Appendix
![image](https://user-images.githubusercontent.com/30373236/174782500-edbe6e2d-6856-4da0-bdfd-873c5ae17100.png)
---
![image](https://user-images.githubusercontent.com/30373236/174782804-7e47f855-a4a9-4b44-a6c3-ac39df7e8f49.png)

**Comment by Thibaud-P** [comment]
Hi,

Joplin version: 2.8.8
Platform: Windows 11
WebDAV Server Platform: **Synology DSM 7.1 with WebDAV Server 2.4.3**

I use **Case 1** as my daily configuration on a custom port without synchronization problem (on mobile too).
I checked **Case 2** but not on port 80 and it works too.
I couldn't test **Case 3** as port 80 is not free to use with my WebDAV server...

There is a difference on server side, but I don't know how it would have an impact.
Also, I mapped the WebDAV server in windows File Explorer. I tried to disconnect it and it worked too, but didn't reboot so maybe this is irrelevant.

Did you test **Case 1 & 2** with an Android device ?

**Comment by traversebitree** [comment]
I've tried, but I still get errors. I think it's a problem of using IIS to build WebDAV service.

**Comment by traversebitree** [comment]
> Hi,
> 
> Joplin version: 2.8.8 Platform: Windows 11 WebDAV Server Platform: **Synology DSM 7.1 with WebDAV Server 2.4.3**
> 
> I use **Case 1** as my daily configuration on a custom port without synchronization problem (on mobile too). I checked **Case 2** but not on port 80 and it works too. I couldn't test **Case 3** as port 80 is not free to use with my WebDAV server...
> 
> There is a difference on server side, but I don't know how it would have an impact. Also, I mapped the WebDAV server in windows File Explorer. I tried to disconnect it and it worked too, but didn't reboot so maybe this is irrelevant.
> 
> Did you test **Case 1 & 2** with an Android device ?

I've tried, but I still get errors. I think it's a problem of using **IIS** to build WebDAV service.
