### ISSUE TITLE
Lost notes.

### ISSUE THREAD

**Issue by arnauldb** [laurent22/joplin#661]
Hello,

I had to connect the desktop Joplin to a new nextcloud instance. Just after synchronizing with it, I realized my notes in Joplin desktop were gone due, I guess, to the synchonization with the empty Joplin folder in Nextcloud.

I guess there is no way to recover them locally (on my desktop)...I should have made a local backup but I forgot...

**Comment by arnauldb** [comment]
> Are your notes still on the old nextcloud instance?
No :-(

**Comment by gerroon** [comment]
I had this exact same issue yesterday. Changing the sync settings to a new NC instance wiped my database. Luckily I had another synced desktop, so I was able to recover a backup from it.

**Comment by laurent22** [comment]
There's now a warning about this below the WebDAV URL field and I've added an entry in the FAQ: https://joplin.cozic.net/faq/ Any feedback on how to clarify this issue and avoid would be welcome.
