### ISSUE TITLE
server/shares: (copy) raw markdown

### ISSUE THREAD

**Issue by jtagcat** [laurent22/joplin#6611]
https://github.com/laurent22/joplin/blob/dev/packages/server/src/routes/index/shares.ts

I've been requested for sources; It'd be nice if you could get source markdown from the share page.

**Comment by Daeraxa** [comment]
This sounds like a feature request/enhancement rather than a bug? Is that correct?

**Comment by jtagcat** [comment]
> This sounds like a feature request/enhancement rather than a bug? Is that correct?

Yes, but I'm unsure how to handle these. I read that 'Feature requests go on forum' is for keeping GitHub issues close to development. For more moonshots, I've thrown them on Discourse. For features actually feeling missing, and on the horizon[^1], placing them on the forum feels wrong, as it looks more like a black hole.

Should I throw features on the forum in the future anyway?

[^1]: Especially with the server/cloud component.

**Comment by laurent22** [comment]
Whether here or on the forum, all feature requests have very little chance of being implemented. That's the reality of open source - thousands of requests and very few people to do something about them.

But in any case the forum is the right place because there can be a discussion, which helps define whether it should be implemented and how. Here it will just be closed by stale bot or a moderator.

**Comment by Daeraxa** [comment]
What Laurent said. 
Sorry wasn't intending to sound sarcastic in my original post, was just making sure it wasn't a regression or something that sometimes works.

It might feel like a black hole on the forum sometimes as not everything gains traction (I sometimes post things there about small changes that only ever get a handful of comments) but I do sometimes search the features category for certain keywords to see if anyone has asked about it before when I think of something which often leads to comments that show me a workaround or why the idea might be stupid (or even that it has already been developed).

It isn't a perfect solution but keeping the community discussions in one place can be very helpful, useful feature requests can then be added to GH with a specific label for potential contributors with a lot more fleshed out details about the potential implementation.
