### ISSUE TITLE
App doesn't open on Ubuntu 22.04

### ISSUE THREAD

**Issue by WillTirone** [laurent22/joplin#6612]
Hi all, 
Have never used Joplin but tried to install on 22.04. I can see an icon, but when I click on it nothing happens / doesn't attempt to launch. It appears though that install was successful based on the command from https://joplinapp.org/help/#desktop-applications. 

If I'm doing something dumb please feel free to delete this or if it's a duplicate issue :) thanks!!

## Environment

Joplin version: 2.8.8
Platform: Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

## Steps to reproduce

1. installed from https://joplinapp.org/help/#desktop-applications 
2. attempt to open from clicking icon 
3. No response from icon

## Logfile
```
(base) willtirone@dev:~$ wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash
--2022-06-24 14:44:58--  https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8002::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9793 (9.6K) [text/plain]
Saving to: ‘STDOUT’

-                   100%[===================>]   9.56K  --.-KB/s    in 0s      

2022-06-24 14:44:59 (39.8 MB/s) - written to stdout [9793/9793]


     _             _ _       
    | | ___  _ __ | (_)_ __  
 _  | |/ _ \| '_ \| | | '_ \ 
| |_| | (_) | |_) | | | | | |
 \___/ \___/| .__/|_|_|_| |_|
            |_|

Linux Installer and Updater

Checking architecture...
You already have the latest version 2.8.8 installed.
```

**Comment by dpoulton-github** [comment]
I believe that this may have been discussed on the Joplin forum. If so it is because Ubuntu 22.04 no longer comes with `libfuse2`.

https://discourse.joplinapp.org/t/appimage-incompatibility-in-ubuntu-22-04/25173/3

Suggestion from that thread is:

```
sudo add-apt-repository universe
sudo apt install libfuse2
```

**Comment by WillTirone** [comment]
oh that worked, amazing!! thank you @dpoulton-github. I guess I can leave this issue open on here in case anyone else is searching.

**Comment by breeze12x** [comment]
> I believe that this may have been discussed on the Joplin forum. If so it is because Ubuntu 22.04 no longer comes with `libfuse2`.
> 
> https://discourse.joplinapp.org/t/appimage-incompatibility-in-ubuntu-22-04/25173/3
> 
> Suggestion from that thread is:
> 
> ```
> sudo add-apt-repository universe
> sudo apt install libfuse2
> ```

thanks, I had same problem, I used your suggestion fix the problem

**Comment by Daeraxa** [comment]
Links have also been added to the FAQ now https://joplinapp.org/faq/#desktop-application-will-not-launch-on-linux

**Comment by jaidernunes** [comment]
> I believe that this may have been discussed on the Joplin forum. If so it is because Ubuntu 22.04 no longer comes with `libfuse2`.
> 
> https://discourse.joplinapp.org/t/appimage-incompatibility-in-ubuntu-22-04/25173/3
> 
> Suggestion from that thread is:
> 
> ```
> sudo add-apt-repository universe
> sudo apt install libfuse2
> ```

Worked for me! Thanks

**Comment by NicolasLeboeuf** [comment]
Got the same issue here (I was using Joplin on Windows before) and the fix works :+1:

**Comment by nachomachadostrata** [comment]
It worked for me! Thanks!!

**Comment by Senpawaii** [comment]
Yep this fixed it for me. Thanks!

**Comment by alexTitakoff** [comment]
Works!

**Comment by ThiagoDiniz-creator** [comment]
This fix worked for me too.

**Comment by vellskrad** [comment]
Работает! огромное спасибо)

**Comment by primercado** [comment]
oooh! thanks very very very much @dpoulton-github.

**Comment by GizawAAiT** [comment]
wuuuuuuuuuuf! you are so great man!
you just saved my time so much, I can't explain it. I think most ubuntu 22.04 users may face the same issue and almost all cases will be this one. thanks l lot!

**Comment by bearhudson** [comment]
Stellar thank you so much!!

**Comment by olgreet** [comment]
Would like to add my thanks to those already above - worked perfectly, thanks very much!!!

**Comment by danepowell** [comment]
I used the shell script to install Joplin on Ubuntu 22.10. Since this script runs before the app, can it check for this dependency and either warn the user or automatically download it? This would be a lot less confusing than the current silent failure.
