### ISSUE TITLE
keyboard shortcut for `forward` and `back` does not work 

### ISSUE THREAD

**Issue by joochlee** [laurent22/joplin#6619]
## Environment
Joplin version: 2.8.8
Platform: linux/windows10
OS specifics: ubuntu22.04LTS, windows 10

## Steps to reproduce
1. Options > Keyboard shortcuts > configure `forward` and `back` with proper shortcut
2. use configured shortcut
3. `forward` and `back` does not work by keyboard

## Describe what you expected to happen
configured keyboard shortcut for `forward` and `back` should work

**Comment by laurent22** [comment]
Works for me on macOS. When you set the shortcut, does it show up under the "Go" menu?

**Comment by joochlee** [comment]
hmmm... 
it's so weird.. 
Now it works as expected... what did I see yesterday??
I closed this bug (?)

I'm sorry @_@
