### ISSUE TITLE
Joplin app does not remember the display on Windows

### ISSUE THREAD

**Issue by gsturov** [laurent22/joplin#6621]
## Environment

Joplin version: 2.8.8
Platform: Windows
OS specifics: 11

## Steps to reproduce

1. In multi-display env open Joplin by clicking the taskbar icon
2. Move it to a different display. Close.
3. Open it again. It will open in the same place. All good.
4. But after "sleep" or "hibernate" and sometimes after "lock" you click it and it will open in the original display.

I have to move it to the right display several times a day.

**Comment by tomasz1986** [comment]
I also experience the same problem all the time, although here it always happens when opening Joplin for the first time after restarting Windows. No need for sleep/hibernate/lock in my case.
