### ISSUE TITLE
oauth2/v2.0/token failed, reason: unable to verify the first certificate

### ISSUE THREAD

**Issue by jack-liew** [laurent22/joplin#6623]
## Environment

Joplin version: JoplinPortable 2.8.8
Platform: windows
OS specifics: windows 11

## Steps to reproduce

1. To check update, or sync to onedrive

## Describe what you expected to happen
1:  To check joplin' update
![image](https://user-images.githubusercontent.com/102201538/176385459-866bffe3-31e4-4603-8a1e-595ae8b50555.png)
2:  sync to onedrive
request to https://login.microsoftonline.com/common/oauth2/v2.0/token failed, reason: unable to verify the first certificate

Thanks!

**Comment by dpoulton-github** [comment]
Are you using a company network? This error can occur when a company inserts its own certificates on all machines so they can read / monitor all HTTPS traffic. Joplin does not use the computer's certificate store and so cannot verify the company's certificate in the chain.

**Comment by jack-liew** [comment]
> 

Yes, my internal network access to github and onedrive is very unstable, so have been using fastgithub lately to keep access.
Your answer solved my problem, thank you
