### ISSUE TITLE
2.8.8 crashes when printing

### ISSUE THREAD

**Issue by gerald-drissner** [laurent22/joplin#6624]
When I want to print a note, the program crashes without error message and closes automatically. Printing as PDF also produces the same behavior.

## Environment

Joplin version: 2.8.8
Platform: Linux
OS specifics: KDE 5.25.2, Kernel: 5.18.7, Arch

## Steps to reproduce

1. File - Print
2. Crashes
3. 

## Logfile

[[-->](url)](https://file.io/PXnQHJRjsALl)

**Comment by Daeraxa** [comment]
Sounds like a duplicate of https://github.com/laurent22/joplin/issues/5651
