### ISSUE TITLE
The edit with preview layout display ircorrect in first few columns.

### ISSUE THREAD

**Issue by yisuixinq** [laurent22/joplin#6625]
Joplin version: 2.8.8
Platform:  Windows 10

The edit with preview layout display ircorrect in first few columns, it just leave some blank columns, and some characters are missing, and when edit in code block, the color of the blank lines does not match the color of the code blocks, which makes the code look discontinuous.

![image](https://user-images.githubusercontent.com/40953718/176483248-be985036-22cf-4a7b-96a3-ad4f1841a07b.png)

**Comment by Daeraxa** [comment]
Do you use the persistent folding plugin by any chance?
If so then you probably just need to set the "Editor maximum width" to 0 in the Appearance options of Joplin.

**Comment by yisuixinq** [comment]
yes, I have used "Folding in Code Mirror Editor", When I turn off the plugin, it looks normal

**Comment by Daeraxa** [comment]
Yeah, it is a plugin issue, not Joplin. It doesn't take into account the editor width setting but the plugin dev hasn't updated it. See https://discourse.joplinapp.org/t/persistent-text-folding-in-editor/16183/
