### ISSUE TITLE
Joplin 2.8.8白屏问题

### ISSUE THREAD

**Issue by wxm99399** [laurent22/joplin#6629]
每天都会使用，昨天打开时突然窗口白屏，试了下重新启动电脑、卸载重安新版本2.8.8都没有解决。
电脑系统：macOS 10.14.6
求助

**Comment by personalizedrefrigerator** [comment]
Do any errors show up in the 'console' tab of the app's development tools?

Developer tools can be opened by clicking `view`, then `toggle developer tools`.
![](https://user-images.githubusercontent.com/46334387/176994078-3c7298ad-c09e-4132-befe-b73338901975.png)

If `toggle developer tools` isn't present under `view`, open it by clicking on `help`, then `toggle developer tools`.
![](https://user-images.githubusercontent.com/46334387/176994114-c3159977-bbfc-4070-b404-695d44eaf2a3.png)

After opening `developer tools`, click on the `console` tab and check for error messages:
![](https://user-images.githubusercontent.com/46334387/176994106-0b73d680-7d1c-4b60-8ee0-28fe2523d172.png)

**Comment by wxm99399** [comment]
Thank u for help me.

After I tried to open the developer tools several times, it came back to normal......
