### ISSUE TITLE
CJK parenthesis not auto-paired

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#6630]
## Environment

Joplin version: 2.8.8
Platform: Linux
OS specifics: Arch Linux

## Steps to reproduce

1. Enabled "Auto-pair braces, parenthesis, quotations, etc."
2. Create new note
3. Insert `（`(U+FF88)

## Describe what you expected to happen
U+FF99 is auto-paired.
This issue also occurs with U+3008, U+300A, U+300C, U+300E, U+3010, U+3014, U+3016, U+3018, and U+301A.

**Comment by ghost** [comment]
Please keep this issue open.

**Comment by ghost** [comment]
Do not close.

**Comment by wh201906** [comment]
~~Maybe it's an upstream bug?~~
https://github.com/codemirror/codemirror5/blob/7f488eb5c12d71ea7ea75e286b7b9c029453a298/addon/edit/closebrackets.js#L13-L16
I guess we can add some extra options to make it support CJK brackets
