### ISSUE TITLE
'Open newly created note' button does not work

### ISSUE THREAD

**Issue by cast-away** [laurent22/joplin#6632]
The 'Open Newly Created Note' button does not show the note but the following error message:

```
The address wasn’t understood

Firefox doesn’t know how to open this address, because one of the following protocols (joplin) isn’t associated with any program or is not allowed in this context.

    You might need to install other software to open this address.
```

## Environment

Joplin version: 2.8.8
Platform: Linux
OS specifics: Kubuntu 20.04
Firefox: 101.0.1 (64-bit)

## Steps to reproduce

1. Open this website (I believe this is URL agnostic, but just following the rules...) https://architecturetoday.co.uk/new-court-trinity-college-cambridge-5th-studio-max-fordham/#
2. On the web clipper, select 'Clip simplified page' and clip 
3. Click on 'Open Newly Created Note'

## Describe what you expected to happen

The note to show up in Joplin

## Logfile

Not sure how to provide Firefox's log

**Comment by Daeraxa** [comment]
I can't replicate this, it works fine for me (2.8.8, clipper 2.8.1, FF 101.0.1, Fedora 36).
You can check the extension log by doing the following:
- On "add-ons and themes" in FF
- Press the cog on the top right and click "debug add-ons"
- Find Joplin Web Clipper and press "inspect"
- Select "console" on the top row
- Replicate the issue on a website then go back to the console tab and copy the log (right click)

Could you also see if the normal callback urls are working?
- Right click a note or notebook in the sidebars and "copy external link"
- Paste the link into your browser
