### ISSUE TITLE
Desktop: Re-ordering notelist items causes unwanted height change

### ISSUE THREAD

**Issue by Daeraxa** [laurent22/joplin#6639]
## Environment

Joplin version: dev branch since commit [fb9e78d](https://github.com/laurent22/joplin/commit/fb9e78d6c1f70473c40defcdd273703c972a5b9a)
Platform: Linux
OS specifics: Fedora 36

>Joplin 2.8.8 (dev, linux)
>Client ID: f8a67ce4381c4d96943c96a0203aebc8
>Sync Version: 3
>Profile Version: 41
>Keychain Supported: No
>Revision: fb9e78d6c

Originally discovered by "theParadoxica" on the Joplin Discord server
PR for commit: https://github.com/laurent22/joplin/pull/6542#

## Steps to reproduce

1. Enable custom ordering in a notebook with at least two notes
2. Drag note 2 above note 1 -> observe note height change
3. Restart Joplin to reset note heights (changing notebook has no effect)

## Describe what you expected to happen

Notelist items height should not change on reordering

## Logfile

No log events appear to be generated but issue is easy to replicate

**Comment by ken1kob** [comment]
This symptom doesn't happen when the height is styled.

> Restart Joplin to reset note heights (changing notebook has no effect)

Also, they can be reset by showing option screen. It's a convenient emergency exit. 😀

**Comment by Daeraxa** [comment]
I also noticed it reacts to how long you "hold" the notebook at the top. If you just flash over it then it only slightly reduces, holding it makes it keeps reducing until it it gets to 8px when it stops shrinking.

**Comment by ken1kob** [comment]
## Cause of the Symptom

When a note list item is dragged, its height is sometimes transiently being changed.

## Treatment

When a note list item is dragged, its height should not be considered as its permanent height.
