### ISSUE TITLE
Joplin keeps stopping

### ISSUE THREAD

**Issue by cast-away** [laurent22/joplin#664]
### Operating system
- Android

### Application
- Mobile

After the latest update (1.0.129) I am unable to run Joplin on my Android 7.0 device. The first error message is "Joplin has stopped" and after launching it again "Joplin keeps stopping". Clearing the app cache and data has no effect on the issue.

Any help on how to resolve this would be much appreciated.

**Comment by laurent22** [comment]
Could you provide a low level bug report as described there? https://joplin.cozic.net/debugging/

**Comment by cast-away** [comment]
wow, that was quick!
Copying what I think is relevant below (the debug file is over 17MB which goes a long way in terms of text, also has lots of personal information...) Please let me know if what to look for and I will fish it for you. As a side question, what does facebook have to do with Joplin? Not installed in my phone btw:
`07-02 20:04:34.334 15169 15169 E AndroidRuntime: FATAL EXCEPTION: main
07-02 20:04:34.334 15169 15169 E AndroidRuntime: Process: net.cozic.joplin, PID: 15169
07-02 20:04:34.334 15169 15169 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.cozic.joplin/net.cozic.joplin.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
07-02 20:04:34.334 15169 15169 E AndroidRuntime: Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.getReactNativeHost(ReactActivityDelegate.java:68)
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:88)
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:77)
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:52)
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6672)
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
07-02 20:04:34.334 15169 15169 E AndroidRuntime: 	... 9 more
07-02 20:04:34.338  3111  3179 I chatty  : uid=1000(system) Binder:3111_1 expire 8 lines
07-02 20:04:35.369  3111  3532 I chatty  : uid=1000(system) android.display expire 37 lines
07-02 20:04:35.696  3111  5136 I chatty  : uid=1000(system) Binder:3111_7 expire 1 line
07-02 20:04:36.782  3111 17922 I chatty  : uid=1000(system) Binder:3111_13 expire 2 lines
07-02 20:04:36.955 29366 29366 E AndroidRuntime: FATAL EXCEPTION: main
07-02 20:04:36.955 29366 29366 E AndroidRuntime: Process: net.cozic.joplin, PID: 29366
07-02 20:04:36.955 29366 29366 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.cozic.joplin/net.cozic.joplin.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
07-02 20:04:36.955 29366 29366 E AndroidRuntime: Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.getReactNativeHost(ReactActivityDelegate.java:68)
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:88)
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:77)
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:52)
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6672)
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
07-02 20:04:36.955 29366 29366 E AndroidRuntime: 	... 9 more
07-02 20:04:36.957  3111 25972 I chatty  : uid=1000(system) Binder:3111_17 expire 5 lines
07-02 20:04:38.383  3111  5696 I chatty  : uid=1000(system) Binder:3111_10 expire 3 lines
07-02 20:04:40.790  3111  5070 I chatty  : uid=1000(system) Binder:3111_5 expire 2 lines
07-02 20:04:40.918 29392 29392 E AndroidRuntime: FATAL EXCEPTION: main
07-02 20:04:40.918 29392 29392 E AndroidRuntime: Process: net.cozic.joplin, PID: 29392
07-02 20:04:40.918 29392 29392 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.cozic.joplin/net.cozic.joplin.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
07-02 20:04:40.918 29392 29392 E AndroidRuntime: Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.getReactNativeHost(ReactActivityDelegate.java:68)
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:88)
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:77)
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:52)
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6672)
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
07-02 20:04:40.918 29392 29392 E AndroidRuntime: 	... 9 more
07-02 20:04:42.716  3111 29117 I chatty  : uid=1000(system) Binder:3111_20 expire 1 line
07-02 20:04:45.541  3111 32513 I chatty  : uid=1000(system) Binder:3111_1A expire 2 lines
07-02 20:04:45.665 29419 29419 E AndroidRuntime: FATAL EXCEPTION: main
07-02 20:04:45.665 29419 29419 E AndroidRuntime: Process: net.cozic.joplin, PID: 29419
07-02 20:04:45.665 29419 29419 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.cozic.joplin/net.cozic.joplin.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
07-02 20:04:45.665 29419 29419 E AndroidRuntime: Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.getReactNativeHost(ReactActivityDelegate.java:68)
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:88)
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:77)
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:52)
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6672)
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
07-02 20:04:45.665 29419 29419 E AndroidRuntime: 	... 9 more
07-02 20:04:45.667  3111  5552 I chatty  : uid=1000(system) Binder:3111_A expire 2 lines
07-02 20:04:46.969  3111  5695 I chatty  : uid=1000(system) Binder:3111_F expire 1 line
07-02 20:04:47.007  3111  5689 I chatty  : uid=1000(system) Binder:3111_E expire 1 line
07-02 20:04:47.009  3111  5719 I chatty  : uid=1000(system) Binder:3111_12 expire 2 lines
07-02 20:04:47.891  3111  5146 I chatty  : uid=1000(system) Binder:3111_8 expire 3 lines
07-02 20:04:48.007  3111 32516 I chatty  : uid=1000(system) Binder:3111_1C expire 2 lines
07-02 20:04:49.436  3111  5147 I chatty  : uid=1000(system) Binder:3111_9 expire 1 line
07-02 20:04:58.543  3111  4524 I chatty  : uid=1000(system) UEventObserver expire 1 line
07-02 20:05:06.385  3111 32517 I chatty  : uid=1000(system) Binder:3111_1D expire 3 lines
07-02 20:05:10.606  3111  3181 I chatty  : uid=1000(system) Binder:3111_2 expire 1 line
07-02 20:05:15.171 29685 29685 E AndroidRuntime: FATAL EXCEPTION: main
07-02 20:05:15.171 29685 29685 E AndroidRuntime: Process: net.cozic.joplin, PID: 29685
07-02 20:05:15.171 29685 29685 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.cozic.joplin/net.cozic.joplin.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
07-02 20:05:15.171 29685 29685 E AndroidRuntime: Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.getReactNativeHost(ReactActivityDelegate.java:68)
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:88)
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:77)
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:52)
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6672)
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
07-02 20:05:15.171 29685 29685 E AndroidRuntime: 	... 9 more
07-02 20:05:35.548  3111 25971 I chatty  : uid=1000(system) Binder:3111_16 expire 1 line
07-02 20:05:47.667   556   722 I chatty  : uid=1000(system) EventThread expire 1 line
07-02 20:05:49.410  3111  3864 I chatty  : uid=1000(system) PackageManager expire 1 line
07-02 20:05:50.621  3111  3320 I chatty  : uid=1000(system) android.bg expire 1 line
07-02 20:05:58.289  3111 32518 I chatty  : uid=1000(system) Binder:3111_1E expire 1 line
07-02 20:05:58.295   556   556 I chatty  : uid=1000(system) /system/bin/surfaceflinger expire 13 lines
07-02 20:05:58.345  3111 24096 I chatty  : uid=1000(system) Binder:3111_15 expire 1 line
07-02 20:05:58.468 29901 29901 E AndroidRuntime: FATAL EXCEPTION: main
07-02 20:05:58.468 29901 29901 E AndroidRuntime: Process: net.cozic.joplin, PID: 29901
07-02 20:05:58.468 29901 29901 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.cozic.joplin/net.cozic.joplin.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
07-02 20:05:58.468 29901 29901 E AndroidRuntime: Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.getReactNativeHost(ReactActivityDelegate.java:68)
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:88)
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:77)
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:52)
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6672)
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
07-02 20:05:58.468 29901 29901 E AndroidRuntime: 	... 9 more`

**Comment by laurent22** [comment]
That's a strange error - and the version before that was working?

The Facebook files is because the framework is an open source project developed by Facebook, the company.

**Comment by cast-away** [comment]
yep, first time this is happening

**Comment by cast-away** [comment]
Odd... a good old reboot of the phone fixed this. Sorry for the trouble!

**Comment by laurent22** [comment]
Ok that's weird. I can't make sense of the error and online info about it is not clear, but if it happens again feel free to post back here.
