### ISSUE TITLE
Mobile: 'Set decryption password' warning cannot be hidden

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#6642]
## Environment

Joplin version: 3b35ab6581ed3bc1788780d6fcf906c85f47b63f
Platform: iOS/custom build
OS specifics: iOS 15.5

## Steps to reproduce
1. Enable encryption
2. Sync
3. Sync a new mobile device, do not enter the decryption password
4. Disable encryption
   - All notes -- except perhaps a few -- should now be decrypted
5. Sync the mobile device
6. Observe that an the `enter the decryption password` banner cannot be dismissed without entering the decryption password.

## Describe what you expected to happen
I should be able to dismiss the warning dialog without entering the decryption password.

**Comment by laurent22** [comment]
I'm not sure we want that because normally warnings appear to tell the user to do some action, and once they've done whatever needs to be done the warning disappears. Even if we have a close button, the warning condition is still there so that dialog will show up again on next sync or after app restart.

**Comment by personalizedrefrigerator** [comment]
> I'm not sure we want that because normally warnings appear to tell the user to do some action, and once they've done whatever needs to be done the warning disappears. Even if we have a close button, the warning condition is still there so that dialog will show up again on next sync or after app restart.

The warning also shows up when opening a note.

I currently have an "enter the decryption password" dialog that cannot, to my knowledge, be otherwise dismissed (I have forgotten the password and disabled encryption several months ago). I would like to dismiss the warning while editing notes (additional screen space).

Perhaps it would be better to address the cause of that issue...

**Comment by personalizedrefrigerator** [comment]
I'm no longer experiencing this (I'm not sure why -- the last update to Joplin on my iOS device was a few months ago...)
