### ISSUE TITLE
Sync Problem MacBookAir & iPhone7

### ISSUE THREAD

**Issue by wookahsh** [laurent22/joplin#6646]
Joplin 2.8.8 (prod, darwin)

Client-ID: a764fc3d108746388ff762e35df54f97
Sync version: 3
Profile version: 41
Supported keychain: Yes

Revision: c2a6a13

I have a sync problem between my MacBookAir (macOS Monterey 12.3.1) and my iPhone7 (iOS 15.0.2).

The error message is: Error: "Cannot acquire exclusive lock becaust the following clients have a sync lock on the target."

When I start Joplin on the Macbook then the sync runs in continuous loop and does not end. The arrow icons on the sync button spin incessantly.

During setup and shortly after everything went fine and since yesterday this error comes.

**Comment by JackGruber** [comment]
Posted also on discourse. 
https://discourse.joplinapp.org/t/sync-problem-macbookair-iphone/26333
