### ISSUE TITLE
Codeblock continues endlessly in editor

### ISSUE THREAD

**Issue by Schlaumra** [laurent22/joplin#6647]
Today I encountered a problem with the plaintext editor. I wrote normally and everything seems to work perfectly. Until I opened the WYSIWYG Editor and changed something. After I switched back to the normal editor the view has been distorted. The codeblock continues to the end of the document. In the rendered view everything seems normal.

![screenshot](https://user-images.githubusercontent.com/48768614/177624930-e0edea43-a394-4802-b22e-2fecc279219f.png)

I noticed the problem has to do something with the ordered list with a padded unordered list before the codeblock. (Not completely visible in the screenshot) I copied it in another note and tried it on another pc, it seems to happen every time. I tried it on MacOS and Linux.

Tried it also with this:
~~~
1.  test
    - test

```ts
test note used not correct symbol for codeblock
```

sdfsdf
~~~
Same behaviour.
IMPORTANT: There need to be 2 spaces before the text in the ordered list (caused by the WYSIWYG editor)

## Environment

Joplin 2.8.8 (prod, darwin)
and
Joplin 2.8.8 (prod, linux)

## Steps to reproduce

1. Open the editor
2. Create a ordered list with a padded unordered list
3. After that create a codeblock
4. Switch to the WYSIWYG editor and change something or add 2 space between `1.  text`
5. Switch back 

## Describe what you expected to happen
The codeblock continues until the 3 \`

**Comment by personalizedrefrigerator** [comment]
I tested this with the CodeMirror 6 editor (what's being used in [this PR](https://github.com/laurent22/joplin/pull/6684) and didn't experience the issue. As such, an eventual migration from CodeMirror 5 to CodeMirror 6 in the desktop app might fix this issue.
