### ISSUE TITLE
This rich text editor is not enough good, will you improve it?

### ISSUE THREAD

**Issue by jack-liew** [laurent22/joplin#6649]
## Environment

Joplin version: 2.8.8
Platform: windows amd64
OS specifics:  windows 11

## Steps to reproduce

1. Very messy formatting when copying content from a web page to joplin's rich text editor

## Describe what you expected to happen

I often need to copy something from a web page into a note, and I dont use Markdown, and I will not use it.
But now joplin's rich text editor is not very good at format conversion.

joplin:
![image](https://user-images.githubusercontent.com/102201538/177905692-452f3aeb-f4ae-47ca-ae8a-8fa06f451dc1.png)

evernote:
![image](https://user-images.githubusercontent.com/102201538/177905754-11e04496-e952-4de4-bb92-359a1e41e59d.png)

Can this problem be improved?

Thanks

**Comment by TAbdiukov** [comment]
@jack-liew Try

> (triple- `)
> any text
> (triple- ```)

**Comment by jack-liew** [comment]
> @jack尝试
> 
> > （三重-'）任何文本（三重“”）

I dont understand! How should i do?

**Comment by TAbdiukov** [comment]
@jack-liew 
![image](https://user-images.githubusercontent.com/18607514/177915623-8742681e-81df-490c-b839-636d3a58ebdc.png)

**Comment by jack-liew** [comment]
> @jack-liew ![image](https://user-images.githubusercontent.com/18607514/177915623-8742681e-81df-490c-b839-636d3a58ebdc.png)

Its worked!

```Thank You```

PS: How can I set joplin's default copy&paste to...any text...?
