### ISSUE TITLE
FR: sort notes differently in different notebooks

### ISSUE THREAD

**Issue by krc** [laurent22/joplin#665]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

I would like to be able to have notes in one notebook sorted by last modified,  and another notebook to be sorted by name, and have those remembered, rather than switching the sort order manually when I switch notebooks. And ideally to sync that setting with the data, though setting it once manually in each Joplin instance wouldn't be too bad.

**Comment by edenpc** [comment]
This would be nice to have.
