### ISSUE TITLE
Search textbox not clearing itself after first click on the close cross icon

### ISSUE THREAD

**Issue by antoniopaolini** [laurent22/joplin#6652]
Hi everybody.
I think this is a bug, but I don't remember if in some previous versions the behavior was different.

If you do a search in the "Note list column" when you try to clear the textbox you need two click in the "X" button.

## Environment
Joplin 2.8.8 (prod, win32)

Sinc. versione: 3
Profilo versione: 41
Portachiavi supportato: No

Revisione: c2a6a13

## Steps to reproduce

Maybe a picture will explain better than my english. :-)

![2022-07-08-bug-joplin](https://user-images.githubusercontent.com/60228211/178002360-0965fd44-c89f-483a-b1ab-b35d93e46377.gif)

Bye.

**Comment by Daeraxa** [comment]
Duplicate of https://github.com/laurent22/joplin/issues/6557

Should be resolved in the next release.

**Comment by antoniopaolini** [comment]
Thank you very much!!! I had searched in the open issues before but I had not found anything. :-)

I leave it open to save others from my same mistake. :-)
