### ISSUE TITLE
 Problem with images using rich-text editor (again?)

### ISSUE THREAD

**Issue by CLEMENT178** [laurent22/joplin#6659]
I believe this is an issue that arose some time ago (https://discourse.joplinapp.org/t/problem-with-images-using-rich-text-editor/12986  so hopefully, it will be easily fixed) but for the purpose of clarity, I will go through the steps again:

I use Joplin for Windows and Android.  If I paste an image from windows clipboard into Joplin rich-text editor, it seems to work just fine but when I open the note on the Android app, the image does not appear. This is what I get :

![image](https://user-images.githubusercontent.com/109150154/178489012-966bdfec-ef79-4999-957b-9ce44b809f8b.png)

If I paste an image from windows clipboard into Joplin MD editor, then I don't have the problem. But then, if I add some text to the note with Joplin rich-text editor, the same issue appears again, i.e. it seems to be OK on the Windows app, but I the image does not appear on the Android app.

I don't know if it is relevant but I use the e2e encryption feature.

I use have the latest Joplin versions :
**Android**
Joplin 2.8.1

**Windows**
Joplin 2.8.8 (prod, win32)

Client ID: 0489dec3054348cd802a72a3effa01e5
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: c2a6a13

**Comment by SFulpius** [comment]
Do you have some non-ASCII characters in your Windows username (e.g. é)? If yes you probably have the same bug as #6590. This bug is fixed on the development version so this will be fixed on a future version of Joplin.

**Comment by CLEMENT178** [comment]
I don't know if you speak French and read my Github username, but you guessed right with the "é" in my Windows username! Thank you for your reply, looking forward to the next/future version of Joplin.

**Comment by SFulpius** [comment]
I also have an "é" in my Windows username, that's why I gave it as an example ;)
Can you mark the issue as closed so we know we don't have to work on this ?
