### ISSUE TITLE
Failure Occurs in Build of 'joplin' in Arch User Repository

### ISSUE THREAD

**Issue by robcohen** [laurent22/joplin#6660]
There is an error which prevents me from installing joplin from the Arch User Repositories on EndeavorOS (Arch linux)
```

Fresh install of EndeavorOS Artemis.

[user@spin ~]$ yay -S joplin

➤ YN0009: │ root@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-f9937aaf/build.log)
➤ YN0000: └ Completed in 47s 413ms
➤ YN0000: Failed with errors in 1m 4s
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: joplin
```

## Environment

Joplin version:  joplin 2.7.15-4
Platform: Linux
OS specifics: EndeavorOS (Arch linux) Linux spin 5.18.10-arch1-1 #1 

## Steps to reproduce

1. yay -S joplin

## Describe what you expected to happen

I expected joplin to be compiled and installed.

## Logfile
 ```
tail  /tmp/xfs-f9937aaf/build.log

➤ YN0000: Done in 9s 768ms
    at makeError (/home/user/.cache/yay/joplin/src/joplin-2.7.15/packages/tools/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/user/.cache/yay/joplin/src/joplin-2.7.15/packages/tools/node_modules/execa/index.js:114:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fn (/home/user/.cache/yay/joplin/src/joplin-2.7.15/gulpfile.js:35:5)
 ```

**Comment by robcohen** [comment]
Installation of `joplin-appimage` works fine.

**Comment by Daeraxa** [comment]
You should raise this on the AUR if there is an issue with it. The AUR package isn't supported by the Joplin team.

**Comment by TravisTechcyte** [comment]
I believe this is the link for the bug report for the AUR pkgbuild:

https://github.com/alfredopalhares/arch-pkgbuilds/issues/116

**Comment by robcohen** [comment]
Thanks, I'll redirect the bug report to the appropriate project. My mistake!
