### ISSUE TITLE
Details and Summary Tag (Collapsible Header)

### ISSUE THREAD

**Issue by fahri314** [laurent22/joplin#6665]
When i use details and summary tag and `<, >` special html tags in code block, three bugs happening:
1- Markdown beautifer doesn't work after `</details>` tag.
2- In view section at right side alignment isn't work properly. (in long texts)
3- Collapsible header working just if we use extra enter line after `</summary>` tag.

**Example:**
```
<details><summary><b><font size="+1">Example Collapsable Header</font></b></summary>

**Lorem Ipsum** is simply dummy text of the printing and typesetting industry. ...

\```c
#include <stdlib.h>
\```

</details>

## Header
**Lorem Ipsum** is simply dummy text of the printing and typesetting industry. ...
```

**Screenshots:**
![image](https://user-images.githubusercontent.com/10153883/178723788-1a856770-a296-4364-a27a-9a99e243ae84.png)
Expected:
![image](https://user-images.githubusercontent.com/10153883/178723836-7335fae5-ba34-43c2-a878-03a77ba6170b.png)

Joplin Version: `2.8.8`
Platform: `Windows`

**Comment by fahri314** [comment]
This is still a bug. It needs review.

**Comment by araisantai** [comment]
i have the same problem with this, now im using spoilers plugins but it turns out the bug still exists
