### ISSUE TITLE
Search does not find partial matches

### ISSUE THREAD

**Issue by dreamflasher** [laurent22/joplin#6677]
First of all: Thank you for your amazing software. I am switching from StandardNotes to Joplin, and overall I am having a great experience. I especially hope: Better mobile app, less sync conflict errors. Please, don't close this issue right away, I have searched for tickets, I am aware of the search documentation, I still believe this is broken: 

## Environment

Joplin version: 2.8.8
Platform: Windows
OS specifics: 11

## Steps to reproduce

1. Type "lineage" in search
2. Relevant notes are not found

## Describe what you expected to happen
Find a note containing the word "LineageOS".

## Details
The first time I searched for a note it didn't find it and I thought the search is broken. I wanted to open a ticket, but found at least 3 tickets describing this issue:
https://github.com/laurent22/joplin/issues/6455
https://github.com/laurent22/joplin/issues/5313
https://github.com/laurent22/joplin/issues/4178

The response so far was: Read the documentation (https://joplinapp.org/help/#searching), this is expected behaviour. 

I totally understand the developer perspective. I totally understand that it's a non-trivial problem to make partial search fast.

Nevertheless, it's a behaviour users expect, and you can't expect from normal users to read the documentation on search before doing the first search. The user experience of new users will be: Oh this sucks.

From my perspective the expectation of search is:

input: `word1 word2`
actual search: `*word1* AND *word2*`

The full fix is likely a lot of work, but I believe there is a low hanging fruit to give a significantly better experience:

* auto-append a `*` to the search term, if the term is longer than one character

This would still be fast and improve the default search results significantly.

**Comment by floq-design** [comment]
+1

Same behaviour here on an M1 Mac.

I have a note titled 'jdownloader' - when searching using the phrase 'downloader' it fails to find the note.


```
Joplin 2.9.1 (prod, darwin)

Client ID: 16808c9afba04214bf05679c9884531e
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: c3179a3
```

**Comment by dreamflasher** [comment]
Still relevant, please turn off the stale bot.

**Comment by dreamflasher** [comment]
@laurent22 could you please reopen? The issue is not resolved :(

**Comment by laurent22** [comment]
Yes that will be changed on desktop and mobile eventually, but it's not a bug, just a feature we need to change

**Comment by ntomita** [comment]
This is still relevant and should be a high priority feature request, please turn off the stale bot.
