### ISSUE TITLE
No Linux packages

### ISSUE THREAD

**Issue by krc** [laurent22/joplin#668]
### Operating system

- Linux

### Application

- Desktop

There are no native packages for Linux, no .rpm or .deb, not even a .tar.gz binary

It would be nice to have a native package of some sort rather than having to build from source.

**Comment by foxmask** [comment]
There is a binary already : [Joplin-1.0.104-x86_64.AppImage](https://github.com/laurent22/joplin/releases/download/v1.0.104/Joplin-1.0.104-x86_64.AppImage)

**Comment by laurent22** [comment]
Yes this is currently the only supported Linux release.

**Comment by immartian** [comment]
for AppImage, it has to be with FUSE support on Chromebook (Crostini), a `.deb` would be perfect.
