### ISSUE TITLE
Joplin Installation failed.The open program is white screen.

### ISSUE THREAD

**Issue by 4687rabbit** [laurent22/joplin#6683]
I installed 2.7.15.0 Version of Joplin，But after opening the program, it is a white screen.Open the controller prompt.There is a problem with the name app.asar of the folder named resources.And cannot be closed normally.Please ask the joplin team to handle it.
![image](https://user-images.githubusercontent.com/103840532/180172212-c01da14e-76d0-4320-b1da-bf0c4af89672.png)

## Environment

Joplin version: 2.7.15.0
Platform:  WINDOWS 7
OS specifics: WINDOWS

## Steps to reproduce

1. Download the official website 2.7.15.0 installer.
2. Install the program and open it
3. file>exit ; help is noting
4. open view > Toggle Development Tools Can be displayed

## Logfile

Uncaught Error: Cannot find module 'E:\4.office办公软件\joplin\resources\app.asar\node_modules\sqlite3\lib\binding\napi-v3-win32-ia32\node_sqlite3.node'
Require stack:
- E:\4.office办公软件\joplin\resources\app.asar\node_modules\sqlite3\lib\sqlite3-binding.js
- E:\4.office办公软件\joplin\resources\app.asar\node_modules\sqlite3\lib\sqlite3.js
- E:\4.office办公软件\joplin\resources\app.asar\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.o._resolveFilename (electron/js2c/renderer_init.js:29:1118)
    at Module._load (internal/modules/cjs/loader.js:737:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:29:379)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\4.office办公软件\joplin\resources\app.asar\node_modules\sqlite3\lib\sqlite3-binding.js:4:15)
    at Object.<anonymous> (E:\4.office办公软件\joplin\resources\app.asar\node_modules\sqlite3\lib\sqlite3-binding.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1083:30)

**Comment by nelsonmic** [comment]
Hello there 😃, you could try using this cool bug reporting tool [birdeatsbug](https://birdeatsbug.com/) to help you handle bug reports. 

* Get steps to reproduce
* Logs 
* Clicks
* Network errors 

And you could share all of that here so that it's easy to see what happened and get to fixing it. Do check it out :-)

**Comment by 4687rabbit** [comment]
> 你好呀笑脸，您可以尝试使用这个很酷的错误报告工具[birdeatsbug](https://birdeatsbug.com/)来帮助您处理错误报告。
> 
> * 获取重现步骤
> * 日志
> * 点击次数
> * 网络错误
> 
> 您可以在这里分享所有这些，以便轻松查看发生了什么并修复它。请检查一下:-)

  @nelsonmic
How to operate it?I'm not a programmer，So I'm not familiar with the program operation.

**Comment by personalizedrefrigerator** [comment]
Can `E:\4.office办公软件\joplin\resources\app.asar\napi-v3-win32-ia32\` be opened in File Explorer? Is `node_sqlite3.node` a file in this folder?

**Comment by nelsonmic** [comment]
> 

Tell me where you need help, and I could walk you through the process. The first step would be to install the chrome extension on your browser. @4687rabbit

**Comment by 4687rabbit** [comment]
> 内
Sorry for taking so long to reply to you.
The file is invisible.

**Comment by 4687rabbit** [comment]
> > 
> 
> 告诉我你在哪里需要帮助，我可以引导你完成整个过程。第一步是在浏览器上安装 chrome 扩展程序。@4687rabbit

>The browser app store doesn't ，So I can't install the extension program.     @  [nelsonmic](https://github.com/nelsonmic)

**Comment by 4687rabbit** [comment]
I can't open it；&nbsp;&nbsp;

app.asar ，Windows program cannot open this software.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "laurent22/joplin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月23日(星期六) 凌晨0:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题： &nbsp;Re: [laurent22/joplin] Joplin 安装失败。打开的程序是白屏。（问题＃6683）





 
可以E:\4.office办公软件\joplin\resources\app.asar\napi-v3-win32-ia32\在文件资源管理器中打开吗？node_sqlite3.node此文件夹中有文件吗？
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您编写了该主题。Message ID: ***@***.***&gt;

**Comment by 4687rabbit** [comment]
Thank you for your help.

Browsers in China cannot use the App Store.

I guess

Joplin\resources\app.asar&nbsp;&nbsp;Something's wrong.
app.asar&nbsp;Can't open















------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "laurent22/joplin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月23日(星期六) 凌晨5:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题： &nbsp;Re: [laurent22/joplin] Joplin 安装失败。打开的程序是白屏。（问题＃6683）





   
告诉我你在哪里需要帮助，我可以引导你完成整个过程。第一步是在浏览器上安装 chrome ***@***.***
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
你收到这个是因为你被提到了。消息 ID：<laurent22/joplin/issues/6683/1192947165 @ github 。com&gt;
