### ISSUE TITLE
Can't fetch resource when set proxy

### ISSUE THREAD

**Issue by Rhilip** [laurent22/joplin#6688]
## Environment

Joplin version: 2.9.1
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. sync use webdav and enable proxy with proxy URL in Synchronisation options
2. open a note which resource is not download.
3. get warning : `Some items cannot be synchronised.`

![image](https://user-images.githubusercontent.com/13842140/180900888-984f5f71-9df6-438f-80b6-561f14672d00.png)

## Describe what you expected to happen

can fetch resource when set proxy

## Logfile

In develop Tools, I saw this error: 
![image](https://user-images.githubusercontent.com/13842140/180900351-6bdc29ef-84b3-4801-9a94-0e237c0ee3ca.png)

with breakpoint, we can see the `isUrlHttps` function get resource url in `Url` object but not string like note and other files 
![image](https://user-images.githubusercontent.com/13842140/180910601-a6565a34-04c8-4bfc-ac46-be718bbb6eff.png)

**Comment by wh201906** [comment]
Hi. The latest pre-release v2.9.11 has fixed this problem.
https://github.com/laurent22/joplin/releases/tag/v2.9.11
