### ISSUE TITLE
Plugin API DirectoryPath manual entered path with space is stored as JSON

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#6693]
When a path with space manual entered in `SettingItemSubType.DirectoryPath` the path is stored as JSON field in the database.
The quotes form the JSON object is returnd on the field request and causes the path to be invalid because it contains quotation marks.
When a value is enterd without a space the field type is TEXT.
![DB_Browser_for_SQLCipher_TLEnSSxYcK](https://user-images.githubusercontent.com/24863925/181104079-6972803e-3930-4872-ab34-7556bd8ced55.png)

## Environment

Joplin 2.9.1 (dev, win32)

Client ID: a1021b9020f14fc8bb841cd357208e9d
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: c3179a3

## Steps to reproduce

1. Manual enter a path with space, For example `c:\temp\test backup`
2. The path is displayed correctly
3. In the database is `"C:\temp\test backup"` stored and the field type is JSON

**Comment by laurent22** [comment]
I believe this is also fixed in 6a4eb3309396f1a2a1a979b1a07a82ad9f9c2c57
