### ISSUE TITLE
Incorrect duplicate detection for imported notebooks with sub-notebooks

### ISSUE THREAD

**Issue by MatsG23** [laurent22/joplin#6704]
## Environment
Joplin version: 2.8.8 (prod, linux) installed from snap
Platform: Linux
OS specifics: openSUSE Tumbleweed 20220725 (Wayland) + KDE Plasma 5.25.3

## Steps to reproduce
1. Export a notebook with sub-notebooks to JEX
2. Change the name of the notebook in the app to prevent a name conflict on import 
3. Import the created JEX file again
4. Every sub-notebook gets a "(1)" added behind its name.

## Describe what you expected to happen
Since there are no duplicate sub-notebooks names in the newly created notebook, the names should be kept. A number ("(1)", "(2)", ...) must not be added.

**Comment by kamalbuilds** [comment]
hi @laurent22 @MatsG23 can I work on this issue?
