### ISSUE TITLE
Can't be installed from PlayStore

### ISSUE THREAD

**Issue by SenkiJun** [laurent22/joplin#6709]
![Screenshot_20220802-064134](https://user-images.githubusercontent.com/110469283/182373589-d94d8332-dc7c-46ab-8262-1224992a53ee.png)

I'm getting this error when I try to install Joplin from playstore.
Installing manually from apk works without a problem.

OS specifics: Android 6.0.1

**Comment by laurent22** [comment]
What version did you install before the Play Store one?

**Comment by roman-r-m** [comment]
I think Android 6 is too old and is not supported by React-native (the version that Joplin uses)

**Comment by tomasz1986** [comment]
React Native supports Android 5.0 and higher (see https://github.com/facebook/react-native#-requirements). Joplin's minimum system requirements are also Android 5.0 and higher. I used to use the app on Android 6 just a few months ago. Has something changed in between?

**Comment by laurent22** [comment]
I think the message he's having is when trying to update an app, and the existing version has a different signing certificate. For example when trying to install a prod version over a dev version. So I don't think it's related to React Native.

**Comment by roman-r-m** [comment]
> React Native supports Android 5.0 and higher (see https://github.com/facebook/react-native#-requirements). Joplin's minimum system requirements are also Android 5.0 and higher. I used to use the app on Android 6 just a few months ago. Has something changed in between?

Ah, my bad. Should have checked.

**Comment by SenkiJun** [comment]
I just wiped all cache and data. And it worked. I can install from playstore now.
Sorry for taking your time. And thanks for the great app.
