### ISSUE TITLE
Joplin sync failure on IPv6 only networks.

### ISSUE THREAD

**Issue by AesaraB** [laurent22/joplin#6717]
## Environment

Joplin version: Flatpak 2.8.8
Platform: Linux
OS specifics: Fedora 36

## Steps to reproduce

With Dropbox on an IPv6 network:
1. Set up Dropbox sync (may need to do so on IPv4 enabled network)
2. Attempt to synchronise database
3. Joplin tries to connect to https://content.dropboxapi.com using it's A (IPv4) DNS record instead of the AAAA (IPv6) record.

Last error: FetchError: request to https://content.dropboxapi.com/2/files/download failed, reason: connect EHOSTUNREACH 162.125.83.14:443

I've never developed with Electron/Node.js before, but this is probably an upstream bug, see: signalapp/Signal-Desktop/issues/4121

**Comment by ghost** [comment]
# Environment

Joplin version: 2.8.8
Platform: Linux
OS specifics: Arch Linux

# Comment

I'm having the same problem, I'm not able to sync my Joplin with Dropbox when I'm on IPV6, but when I'm on IPV4, the sync works. I then had to disable IPV6 for synchronization in Joplin to work.

![Screenshot from 2022-08-09 10-56-37](https://user-images.githubusercontent.com/55219561/183668225-897ff531-e13a-4db8-9000-b8f4d768fc8e.png)
