### ISSUE TITLE
KaTeX parse error

### ISSUE THREAD

**Issue by pantiandashi** [laurent22/joplin#6718]
## Environment

Joplin version: 2.9.1
Platform: Linux 
OS specifics: manjaro 5.15

## Steps to reproduce
When you write the below text in the note:
1. `$\colorbox {aqua}{$\color{red}{f=ma}$}$`
2. 
It gives below error:
KaTeX parse error: Unexpected end of input in a macro argument, expected '}' at end of input: …olorbox {aqua}{
\color{red}{f=ma}
KaTeX parse error: Expected 'EOF', got '}' at position 1: }̲

## Describe what you expected to happen
https://katex.org/,Type an expression:
![1](https://user-images.githubusercontent.com/110668289/183063828-d3efd7d0-9e2f-424f-8021-2b1b07ff1c43.png)

**Comment by SeptemberHX** [comment]
`$\colorbox{aqua}{\color{red}{f=ma}}$` should work fine.

**Comment by pantiandashi** [comment]
'$$' replace '$',it's OK:
```
$$
\fcolorbox{red} {aqua}{\color{red}{$F=ma$}
$$
```
some differences between "text" and "math mode with `$`"
![2](https://user-images.githubusercontent.com/110668289/183281740-f3df2418-1f12-4ca9-8227-7cd81d50b1b7.png)

**Comment by personalizedrefrigerator** [comment]
Escaping the $s fixes it for me:
```
$\colorbox {aqua}{\$\color{red}{f=ma}\$}$
```

**Comment by l-arnold** [comment]
Would seem a common cause of a "KaTex parse issue".  Perhaps some flag, that if there is a EOF error, perhaps it is not KaTex at all.  Turning off the "Math Expressions" worked for me in my situation.
Thank  you for posting above.
