### ISSUE TITLE
[Webclipper] note not created in the right folder

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#672]
### Operating system

- Linux

### Application

- Desktop

### Description

When we start our browser, then joplin and use the webclipper, we can see that the browser plugin webclipper displays the last used folder. If you change the folder to another one, the grabbed page will go back to the previous folder.
This occurs only once, just after you start the browser. 
If you use the webclipper another time, all will go fine.

**Comment by capnspacehook** [comment]
Can confirm I experienced the same issue on Windows.

**Comment by BenoitBotton** [comment]
I also have the issue on MacOS 10.13

**Comment by foxmask** [comment]
with v 1.0.107 , today I can see the note been created in the right folder

**Comment by foxmask** [comment]
Coincidence, i thought that was fixed but in fact no

**Comment by laurent22** [comment]
Looks like this is still not fixed?

**Comment by foxmask** [comment]
no it's not

**Comment by foxmask** [comment]
yes always.
for example I click on the clipper and he shows me "porjects" as selected default folder, then I change it to something else and press "confirm" but the page wont be inside the new folder but in "projects".

**Comment by laurent22** [comment]
I've never managed to replicate this. I'll get back to it if someone can provide a way to replicate it consistently.

**Comment by foxmask** [comment]
* start Firefox
* Click on the webclipper to select another value instead of the current one.
*Grab  the page
* Check in Joplin the present of the article in that folder, and you should not find it there but in the folder displayed in the web clippers before we change the value

**Comment by laurent22** [comment]
I did try this before but for some reason it's not doing this for me. On which OS and with which browser is it happening for you?

**Comment by laurent22** [comment]
Sorry you did say Firefox. On which OS was it?

**Comment by foxmask** [comment]
Linux debian 9.
But the version of Mozilla not the Debian one

**Comment by foxmask** [comment]
it looks to be ok now
