### ISSUE TITLE
Resources with space are not imported on Markdown Frontmatter import

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#6721]
If a note contains resources with space and these are exported as Markdown Frontmatter and imported again, the resources are missing. 
![grafik](https://user-images.githubusercontent.com/24863925/183236309-b22f6036-acfe-4cfc-9ae4-51a58778e8c4.png)

## Environment

Joplin 2.9.1 (dev, win32)

Client ID: a1021b9020f14fc8bb841cd357208e9d
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: c3179a3

## Steps to reproduce

1.  Create a Note with a resource which contains a space in its name
2. Export this note as Markdown Frontmatter
3. Reimport this note

### Original note
![grafik](https://user-images.githubusercontent.com/24863925/183236220-438fb865-2be0-4f6f-8ba4-e5c521c27b2d.png)

### Imported note
![grafik](https://user-images.githubusercontent.com/24863925/183236230-25652f3d-be6b-4127-af7a-bbfe48552a7d.png)

### Example ZIP
[example.zip](https://github.com/laurent22/joplin/files/9274459/example.zip)

## Describe what you expected to happen

Also resources with space should be imported

**Comment by SFulpius** [comment]
I can reproduce this behavior.
Joplin version: 641b0fa9a2fa785afe1cc840bea9426e75c05a2b
Platform: Linux
OS specifics: Linux Mint 20.3
