### ISSUE TITLE
[Android] Checkbox-continuation

### ISSUE THREAD

**Issue by darkdragon-001** [laurent22/joplin#6728]
## Environment

Joplin version: 2.8.1
Platform: Android
OS specifics: "Opt-in to editor beta" enabled

## Steps to reproduce

1. Enable "Opt-in to editor beta"
2. Checkbox-list is only continued as normal list

## Describe what you expected to happen

A checkbox-list should be continued with checkboxes as in the Desktop version.

## Logfile

_none_

**Comment by personalizedrefrigerator** [comment]
This should be present in the next version of Joplin!

See https://github.com/laurent22/joplin/commit/21b6564301f799f02398136794aaebb0fd8f8725
