### ISSUE TITLE
Highlight search in Preview Pane Doesnt Work

### ISSUE THREAD

**Issue by koshibb** [laurent22/joplin#6729]
When searching either in a note or across all notes, the matching item (i.e. searched word) is only highlighted in the markdown view, not in the preview pane. I have spent a lot of time in the discourse forums, and I can't seem to find a reference to this being a bug, a non-existent feature, or something else. 

I consider myself very novice in markdown, so I typically use the preview only view when making notes. So the ability for the searched term to be easily highlighted within the note would be ideal. 

## Environment

Joplin version: 41
Platform: Windows 10

## Steps to reproduce

1. Be in preview pane
2. Press f6 or crtrl+ f to search either within a notebook or across all notebooks
3. Unable to find the matching searched word easily in the preview pane as it seems to only work in the markdown view.

ex) https://i.imgur.com/WpcwmOu.png

Highlight the searched term in preview pane

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/9285289/log.txt)

**Comment by JackGruber** [comment]
This works for me in Joplin 2.9.1, maybe it's the dark theme? Which Joplin version? 41 is the Profile/Synctaget version!

Searchbar
![grafik](https://user-images.githubusercontent.com/24863925/183563863-8fe88f7e-d3ba-4481-a3af-65e854bd88ac.png)

Search in note
![grafik](https://user-images.githubusercontent.com/24863925/183563985-379cdc24-286f-433d-99c8-85c426d877e2.png)

**Comment by koshibb** [comment]
Interesting @JackGruber -- can you share your CSS by chance under the appearance tab?

**Comment by JackGruber** [comment]
No css highlight stuff. Have you checked the behavior when all plugins are disabled or in safe mode? 

Custom stylesheet for rendered Markdown
```
#rendered-md > ul > li {
  margin-bottom: -4px;
}
#rendered-md > ol > li {
  margin-bottom: -8px;
}
```

Custom stylesheet for Joplin-wide app styles
```
::-webkit-scrollbar {
    width: 10px;
}

div.tag-list span {
    border-radius: 5px;
    color:white !important;
    background: blue !important;
}
```

**Comment by koshibb** [comment]
Interesting, my rendered-md looks like this with Custom stylesheet for rendered Markdown:

`#rendered-md, body, th, td {
  background-color: var(--darker) !important;
  font-family: var(--font-face) !important;`

I do have [Rich Markdown](https://github.com/CalebJohn/joplin-rich-markdown#readme) & [Text Colorize](https://github.com/sadmice/Joplin-Plugin-Text-Colorize) Installed though. I wonder if those are screwing with it. 

After turning both of those off, it worked. And further found that it was Text Colorize was the on that was doing it!

**Comment by koshibb** [comment]
Thank you again!
