### ISSUE TITLE
Offset in editing window

### ISSUE THREAD

**Issue by nolens** [laurent22/joplin#673]
### Operating system

- macOS 10.13.5

### Application

- Desktop, latest version
- this issue exists since several releases

Hello there,
when editing notes or "to do's", I frequently have an offset of minimum 3-4 characters. This offset is becoming larger the longer the line is that I am editing.

For example, when I try to correct typos in a single word, I visually place the cursor at the _end_ of the word, but if I enter or delete characters, those changes are made in the _middle_ of the word. 

Because of this bug, editing entries is a big hassle this way and very uncomfortable / somethings only possible with using an external editor.

Please check the attached screenshot for further explanation. 

<img width="393" alt="bildschirmfoto 2018-07-07 um 06 59 42" src="https://user-images.githubusercontent.com/21305551/42406992-a54f8c0a-81b3-11e8-9981-7add9141d2c2.png">

Thanks,
Thomas

**Comment by laurent22** [comment]
This is because the editor currently only support monospace fonts. If you change it in the settings it should work as expected.
