### ISSUE TITLE
iOS: Long press on images does nothing

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#6731]
## Environment

Joplin version: 12.8.1
Platform: mobile
OS specifics: iOS 15.6

## Steps to reproduce
1. Open the iOS client
2. Create a new note
3. Attach a PNG image to the note
4. Tap and hold on the image
5. Repeat with the Android client6. 

https://user-images.githubusercontent.com/46334387/183899931-0a9b37eb-9b48-4ea6-a6d6-f25156697d14.MOV

## Describe what you expected to happen
As on Android, a dialog with `open` and `share` options should appear.

## Additional information

It looks like this may have been disabled:
https://github.com/laurent22/joplin/pull/3367#issuecomment-709229165

**Comment by laurent22** [comment]
It doesn't even show the built-in context menu that's mentioned in the comment?

For some reason the video is not loading for me. But maybe that built-in context menu has been removed in recent iOS versions, in which case maybe we can simply enable it using the same method as in Android

**Comment by personalizedrefrigerator** [comment]
> It doesn't even show the built-in context menu that's mentioned in the comment?

I'm not seeing a built-in context menu. (I do see a context menu if I select text, however).

> For some reason the video is not loading for me.

The iOS screen recorder seems to create .MOV files by default! I've converted it to an MP4:


https://user-images.githubusercontent.com/46334387/183978331-1fa34098-110f-4ca6-b217-15b991943d53.MP4



> we can simply enable it using the same method as in Android

This would also allow me to add an "edit" action for SVG images!
