### ISSUE TITLE
Dropbox sync fails, payload_too_large error.

### ISSUE THREAD

**Issue by verbina29** [laurent22/joplin#6741]
## Environment

Joplin version: 2.8.8
Platform: Windows 10
OS specifics: Windows 10 Home version 21H2.

## Steps to reproduce

1. Attempt to sync with Dropbox.
2. Wait for it to "finish".
3. It will fail with the error  `Error: POST files/upload: Error (409): {"error_summary": "payload_too_large/...", "error": {".tag": "payload_too_large"}}`, and does not successfully sync.

## Describe what you expected to happen
It would sync successfully.

## Logfile
Log is too large to upload, the only errors seem to be
`2022-08-12 14:14:39: Synchronizer: "Error: POST files/upload: Error (409): {"error_summary": "payload_too_large/..", "error": {".tag": "payload_too_large"}}
Code: payload_too_large/..
Error: POST files/upload: Error (409): {"error_summary": "payload_too_large/..", "error": {".tag": "payload_too_large"}}
    at newError (F:\programs\Joplin\resources\app.asar\node_modules\@joplin\lib\DropboxApi.js:178:20)
    at DropboxApi.exec (F:\programs\Joplin\resources\app.asar\node_modules\@joplin\lib\DropboxApi.js:191:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FileApiDriverDropbox.put (F:\programs\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-dropbox.js:174:4)"`

## Additional Info
My dropbox isn't full, only 36 MB out of 2 GB are being used. Additionally, Joplin is using around 1.5 GB of data per sync attempt, and had used a whopping 175 GB of data total, which doesn't seem right at all when I only have 36 MB of notes. The data usage may be unrelated, but it seems likely that it is related. I have End-to-End encryption enabled.

**Comment by personalizedrefrigerator** [comment]
Sorry for the late reply! How big is the notebook's largest attachment? What happens if you delete this attachment and try to sync again?

**Comment by verbina29** [comment]
lol yeah that fixed it
