### ISSUE TITLE
Span tag not formatting text on IOS App

### ISSUE THREAD

**Issue by JasonWeise** [laurent22/joplin#675]
### Operating system

IOS

### Application

- Mobile

Hi Team
I have found if I want to style text with colour in Joplin I can surround the text with a span tag as follows:
```
<span style="color:red">**MY IMPORTANT TEXT**</span>
```

In the MacOS Joplin App the text shows perfectly in BOLD and Red but on the IOS App the text is actually displaying the Span tags and not styling the text in colour (it is bold though)

I am guessing this is not something I can solve directly on the App but is it likely the App will be able to have this capability at some point. We use Joplin for technical guides and it is important we are able to colour some important text such as warnings and so forth.

Thanks in advance!

**Comment by laurent22** [comment]
That will be fixed in the next release.
