### ISSUE TITLE
Input box obscures text while typing

### ISSUE THREAD

**Issue by ccvbc** [laurent22/joplin#6755]
Version 2.9.2
![图片](https://user-images.githubusercontent.com/103726582/185042459-3c38a37c-a901-49ad-9957-bfd591b5ef37.png)

The problem is as follows
![图片](https://user-images.githubusercontent.com/103726582/185042097-3b16b2aa-f797-4756-8254-13643155eac7.png)

![图片](https://user-images.githubusercontent.com/103726582/185042174-d6e58b05-022f-440f-a172-d000553db996.png)

In other software everything works fine like below

![图片](https://user-images.githubusercontent.com/103726582/185042301-26ce8bbb-890e-4a5a-ab37-4b7a380e601f.png)

![图片](https://user-images.githubusercontent.com/103726582/185042343-069e15cc-231d-437b-8062-670a34f13829.png)

**Comment by personalizedrefrigerator** [comment]
Does this also happen with the rich text editor?
<img width="238" alt="Screenshot: Arrow pointing to edit icon to the right of M downarrow icon" src="https://user-images.githubusercontent.com/46334387/185043578-207a8f36-7f59-4c29-9714-ca62d700696a.png">

**Comment by ccvbc** [comment]
Nope, in fact we've discussed it on the joplin forum.

**Comment by personalizedrefrigerator** [comment]
Still an issue.
