### ISSUE TITLE
Version 2.9.2 appimage is giving a white screen on Linux Mint

### ISSUE THREAD

**Issue by MHolkamp** [laurent22/joplin#6756]
Hi,

Version 2.9.2 seems to start, but ends in a white screen.
No error messages, just a white window with the menus above.

**Comment by Daeraxa** [comment]
Duplicate of https://github.com/laurent22/joplin/issues/6752
Also in the beta feedback thread:
https://discourse.joplinapp.org/t/pre-release-v2-9-is-now-available-updated-12-august/26416/3
and https://discourse.joplinapp.org/t/i-am-dealing-with-a-problem-to-open-app-in-new-joplin-instalation/26890/

**Comment by dayfuaim** [comment]
Same for me.
Ubuntu 22.10.

**Comment by laurent22** [comment]
Is it any better in this release? https://github.com/laurent22/joplin/releases/tag/v2.9.3

**Comment by MHolkamp** [comment]
For me it works on Linux Mint 20.3

**Comment by laurent22** [comment]
Thanks for confirming, I assume it's fixed now then.
