### ISSUE TITLE
2.9.3 on Mac gives a TypeError on start

### ISSUE THREAD

**Issue by msbentley** [laurent22/joplin#6761]
I've just installed v2.9.3 over 2.9.2 and on starting get this error:

<img width="254" alt="image" src="https://user-images.githubusercontent.com/1671065/185431346-67ba6cd4-0a15-45a1-9e34-38d5a5d8e2a2.png">

and Joplin fails to start.

## Environment

Joplin version: 2.9.3
Platform: Mac
OS specifics: 12.4 Monterey

**Comment by laurent22** [comment]
Ok I created this release to fix the Linux build, and now it's the macOS one that's broken. Some problem with Electron Builder it seems.

**Comment by laurent22** [comment]
I'm creating a new release which hopefully should have all the applications working.

**Comment by laurent22** [comment]
This release seems to be fine: https://github.com/laurent22/joplin/releases/tag/v2.9.4 If you still notice any issue feel free to post here.

**Comment by msbentley** [comment]
Looks good, many thanks!
