### ISSUE TITLE
Error: Cannot find module 'syswide-cas'

### ISSUE THREAD

**Issue by b0ssi** [laurent22/joplin#677]
### Operating system

- Linux (Arch)

### Application

- Terminal

No debugging output (enabled through `joplin --log-level debug`).

Joplin-CLI fails to load since last update (I updated it some time around/before 2018-07-05), trying to load a dependency that seems to not be available:

```
module.js:549
    throw err;
    ^

Error: Cannot find module 'syswide-cas'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/joplin-cli/lib/BaseApplication.js:27:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

Let me know if I can be of any help - not too on top of JS but happy to help with any trouble shooting if possible. Thanks!

**Comment by foxmask** [comment]
what is the ouput of:

```
joplin version
```

?

**Comment by b0ssi** [comment]
joplin-cli doesn't get there (errors out before with exception mentioned above), but the
`/usr/share/joplin-cli/package.json`
I have sitting in my system mentions:
`"version": "1.0.108"*`

**Comment by foxmask** [comment]
can't you rollback to the previous release https://github.com/laurent22/joplin/releases/tag/v1.0.104 that provides joplin cli 1.0.107 ?

**Comment by b0ssi** [comment]
1.0.107 is the latest version that works. But I wonder if anyone else is experiencing the underlying issue?
Are these `npm` dependencies of some sort might not be sufficiently specified?

**Comment by tobiasnegrui** [comment]
I'm also experiencing this issue.

**Comment by laurent22** [comment]
Please try with the latest version, which should be fixed.

**Comment by b0ssi** [comment]
Thanks @laurent22. I'm not entirely sure if I'm missing anything obvious, but `joplin-1.0.104` (still) bundles `joplin-cli-1.0.108` - that's the same cli-version that initially started to fail for me. Would it possibly be one of the later cli-versions (e.g. 110, 113...) that is meant to fix the CLI-client?

**Comment by b0ssi** [comment]
The latest release, `joplin-1.0.106`, fixes this issue for me, thanks @laurent22 .
