### ISSUE TITLE
Search can't find a word if it's in bold (with **...**)

### ISSUE THREAD

**Issue by gustavklopp** [laurent22/joplin#6775]
## Environment

Joplin version: 2.8.8 (prod, linux)
Platform: Linux
OS specifics: 5.10.136-1-MANJARO

## Steps to reproduce

1. Create a new note
2. Paste this into the note:
```
the **diﬀerence quotient** for the function f at the value x. 
the diﬀerence quotient for the function f at the value x. 
```
4. Press` control+F` to search in the note and type: `difference`
5. Only the word "difference" without bold is found by the search tool.

## Describe what you expected to happen
The two occurrences of the words in the note should be highlighted by the search tool.

**Comment by laurent22** [comment]
The ff is just one letter in your example so that's why can't find it when you search it with two letters

**Comment by gustavklopp** [comment]
Yes, that's right. Thanks a lot!
