### ISSUE TITLE
OneDrive login blank on iphone

### ISSUE THREAD

**Issue by aarondodd** [laurent22/joplin#6776]
Using Joplin 12.8.1 on iPhone iOS 15.6.1. I freshly installed Joplin and set the synchronization target as OneDrive. When clicking to synchronize, the OneDrive login asking for my email appears:

![B9AC8B50-7F83-4618-B45C-58C6DBA848C6](https://user-images.githubusercontent.com/6969492/186078081-c00e1b02-90d0-4131-83d2-c64717bf2e7b.png)

I enter it and the screen becomes blank. There are no buttons or other UI elements:

![56BAEBFF-35FF-41C8-B8BA-CA82699698D8](https://user-images.githubusercontent.com/6969492/186078105-b55146bc-7ea5-4a32-a482-7d35f5fc78b5.png)

I tried deleting the app and reinstalling to no avail. 

Joplin works fine on my iPad Pro, same version.

**Comment by personalizedrefrigerator** [comment]
Do you have the "prefer fade transitions" or a similar accessibility setting enabled?
(See also https://github.com/laurent22/joplin/issues/6682#issuecomment-1207123165)
