### ISSUE TITLE
[Webdav] Cannot synchronize if the URL contains commas

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#6777]
## Environment

Joplin version: 2.8.8
Platform:  Linux
OS specifics: Arch Linux

## Steps to reproduce

1.  Enter `https://dav.mailbox.org/servlet/webdav.infostore/Userstore/surname,%20givenname/Joplin` in the Webdav URL
2. Synchronization
3. Messeage `Error: href /servlet/webdav.infostore/Userstore/surname%2C%20givenname/Joplin/locks/ not in baseUrl https://dav.mailbox.org/servlet/webdav.infostore/Userstore/surname,%20givenname/Joplin nor relativeBaseUrl /servlet/webdav.infostore/Userstore/surname,%20givenname/Joplin`

## Describe what you expected to happen
Normal synchronization is completed.

## Logfile
Omitted because it contains too much confidential information.

**Comment by laurent22** [comment]
Not related to the comma. It's a faulty WebDAV that's not reporting correct urls

**Comment by ghost** [comment]
Do not close this issue.

**Comment by ghost** [comment]
Do not close this issue.

**Comment by ghost** [comment]
Do not close this Issue.

**Comment by gtlsgamr** [comment]
Hi, have you tried entering  `https://dav.mailbox.org/servlet/webdav.infostore/Userstore/surname%2C%20givenname/Joplin` in the Webdav URL? @carbongreat13

**Comment by teoman002** [comment]
@gtlsgamr Your solution does work for me!

**Comment by gtlsgamr** [comment]
> @gtlsgamr Your solution does work for me!

Good to know!

**Comment by ghost** [comment]
> Hi, have you tried entering `https://dav.mailbox.org/servlet/webdav.infostore/Userstore/surname%2C%20givenname/Joplin` in the Webdav URL? @carbongreat13

Thanks, that got me connected.

**Comment by gtlsgamr** [comment]
Close the issue? Definitely not joplin related. URLs with spaces should be encoded that way.
