### ISSUE TITLE
Translation update

### ISSUE THREAD

**Issue by devfreedom** [laurent22/joplin#678]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

I translated strings into Korean language and this is a ZIP file of translation generated using Poedit.

[ko.zip](https://github.com/laurent22/joplin/files/2184220/ko.zip)

**Comment by laurent22** [comment]
Many thanks for the translation, it will be part of the next release.
