### ISSUE TITLE
Mermaid "gitGraph"s render only a white rectangle

### ISSUE THREAD

**Issue by ggruen** [laurent22/joplin#6784]
## Environment

Joplin version: 2.8.8
Platform: Windows
OS specifics: Windows 11 running on a Surface Pro X

## Steps to reproduce

1. Create a new note in Joplin
2. Enter a mermaid gitGraph, e.g.:
```
```mermaid
gitGraph
    commit
    commit
``` (remove everything after backticks)
```

## Describe what you expected to happen

Markdown render pane should show a git commit graph. Instead, it just displays a white rectangle.

![image](https://user-images.githubusercontent.com/5510793/187047939-978828c3-f0a3-45c5-b50c-96ee887491d7.png)

Notes:
- Reproduced in light and dark mode
- Reproduced on macOS Monterey as well

## Logfile

Followed the directions on https://joplinapp.org/debugging/, but it looks like the flags.txt file isn't being read (i.e., when I quit Joplin and run it again, it opens normally, not with the developer console open). I looked in the console and in the log file and didn't see anything unusual when reproducing the issue. If you're unable to reproduce it for some reason, I can try harder.

**Comment by Daeraxa** [comment]
I don't think this is a bug as such. From the looks of it, gitgraph was only moved from an experimental alpha status to a release status in mermaid v9.0.0. Joplin is on v8.13.9 and it seems there was some [major refactoring](https://github.com/mermaid-js/mermaid/releases/tag/9.0.0) between those versions which I think includes the syntax.

Your example works just fine if you use a colon after `gitGraph`:
````
```mermaid
gitGraph:
    commit
    commit
```
````

If and when there is an update to the package within Joplin then the grammar should work as per the v9.x mermaid syntax for gitgraph.

**Comment by ggruen** [comment]
I suspected git graphing was pretty new in Mermaid. Although using `gitGraph:` technically works, it doesn't produce a very useful graph (hence the alpha status I suppose - see screenshots below).

So I guess this issue is really "Upgrade Mermaid in Joplin to 9.0.0 or higher" (or at least that's the fix). I'd submit a PR if I were familiar enough with React to delve into development.

Mermaid in Joplin 2.8.8:
<img width="1169" alt="joplin_mermaid_screenshot" src="https://user-images.githubusercontent.com/5510793/187527626-4daa3f83-67be-4285-aecc-b06f96e949d4.png">

Mermaid on Mermaid.live:
<img width="1099" alt="mermaid_live_screehshot" src="https://user-images.githubusercontent.com/5510793/187528343-76abebaa-41b1-4bde-8fcb-735a95923007.png">

**Comment by roman-r-m** [comment]
> I'd submit a PR if I were familiar enough with React to delve into development.

You don't need to know react to do this. At least in the best case where all it takes is just bumping a version number in `package.json`. There could be compatibility issues though.

**Comment by lajawi** [comment]
> I suspected git graphing was pretty new in Mermaid. Although using `gitGraph:` technically works, it doesn't produce a very useful graph (hence the alpha status I suppose - see screenshots below).
> 
> So I guess this issue is really "Upgrade Mermaid in Joplin to 9.0.0 or higher" (or at least that's the fix). I'd submit a PR if I were familiar enough with React to delve into development.
> 
> Mermaid in Joplin 2.8.8: <img alt="joplin_mermaid_screenshot" width="1169" src="https://user-images.githubusercontent.com/5510793/187527626-4daa3f83-67be-4285-aecc-b06f96e949d4.png">
> 
> Mermaid on Mermaid.live: <img alt="mermaid_live_screehshot" width="1099" src="https://user-images.githubusercontent.com/5510793/187528343-76abebaa-41b1-4bde-8fcb-735a95923007.png">

https://mermaid.live/ does have a `Copy Markdown` button. You can use that as a temporary solution:
[![](https://mermaid.ink/img/pako:eNp1jjEOwjAMRa9See7CmhnEAVizmMRtouKkcp0BVb07QQSEivD09fT0v1dw2RMYGKOeBedgbOrqXQWTCx3joiQv5DJz1N_c1IFQi9ChCYHclIvu8Z-Oj_49yCQj7Qqgh4oZo68_r09mQQMxWTA1epTJgk1b9crsUenko2YBM-BtoR6waL7ckwOjUugtHSOOgtys7QF251xh)](https://mermaid.live/edit#pako:eNp1jjEOwjAMRa9See7CmhnEAVizmMRtouKkcp0BVb07QQSEivD09fT0v1dw2RMYGKOeBedgbOrqXQWTCx3joiQv5DJz1N_c1IFQi9ChCYHclIvu8Z-Oj_49yCQj7Qqgh4oZo68_r09mQQMxWTA1epTJgk1b9crsUenko2YBM-BtoR6waL7ckwOjUugtHSOOgtys7QF251xh)
