### ISSUE TITLE
Folder with mounting point doesn't appear in the browser file 

### ISSUE THREAD

**Issue by vince252871** [laurent22/joplin#6788]
## Environment

Joplin version: 2.8.8 
Platform: PC LINUX
OS specifics: LINUX MINT 21.0

## Steps to reproduce

1. insert a file from a mounting point
2. the disk with a mounting point isn't visible. 
3. So I can't download file in a Joplin note
![Capture d’écran du 2022-08-29 12-03-05](https://user-images.githubusercontent.com/112388144/187179039-d188a177-32d4-4d2d-83e8-02622d593b6a.png)

. 

## Describe what you expected to happen
With other apps, the folder CAMIF HABITAT is visible in the browser file. But not with JOPLIN. 
Thank you for your interrest. 
Best regards.

**Comment by vince252871** [comment]
With the last version 2.9.4, the problem has disappeared. Thank you very much for your work !
Best regards.

**Comment by JackGruber** [comment]
Than plz. close the issue.
