### ISSUE TITLE
FR: Drag and Drop to tags

### ISSUE THREAD

**Issue by gerroon** [laurent22/joplin#679]
Hi

It would be very nice if one could drag and drop notes  on to tags to associate the dragged note with that tag. At the moment it feels like it is possible but no assignment is done. 

thanks

**Comment by foxmask** [comment]
or also the opposite, drag a tag on a note to add it :)

**Comment by gerroon** [comment]
Or that, for sure

**Comment by BenoitBotton** [comment]
+1
this would be very useful
