### ISSUE TITLE
Android sync fails when it tries to move resources inside app's internal data folder

### ISSUE THREAD

**Issue by jd1378** [laurent22/joplin#6791]
It seems the fix I provided for last issue won't cut it, sorry
it worked when copying files from internal data to external storage but not vice versa
I'll need to handle the internal paths for mkdir as well

I'll open a PR when I fix it
sorry for the inconvenience

**Comment by personalizedrefrigerator** [comment]
Thank you for working on this!

**Comment by jd1378** [comment]
I hope that this will be the last fix for the fix 😄
