### ISSUE TITLE
Editing .md file manually on Dropbox, does not sync the changes on Desktop app?

### ISSUE THREAD

**Issue by tmfelwu** [laurent22/joplin#6793]
## Environment

Joplin version: 2.8.8
Platform: Linux
OS specifics: Ubuntu 22.04

## Steps to reproduce

1. Make a change on a .md file that is stored on Dropbox
2. Sync on Desktop app 
3. The updates are not reflected (Although the logs show that the file has been re-fetched )
4. The change is not even reflected on restarting Joplin

## Describe what you expected to happen

I expected the changes to be reflected in the app.

## Logfile

If we look at the logs, the modified file has been fetched from the server.

```
10:50:19: FileApi: delta 
Logger.ts:219 10:50:21: Synchronizer: Sync: fetchingTotal: Fetching delta items from sync target
Logger.ts:219 10:50:21: **FileApi: get 509bfdbd163846f8a610e92c327bedda.md**
Logger.ts:219 10:50:21: Synchronizer: Sync: fetchingProcessed: Processing fetched item
Logger.ts:219 10:50:22: FileApi: delete locks/1_1_2c66ff280828437b9e30fabd8fc2f27d.json
```

**Comment by tmfelwu** [comment]
What other files are being updated by another joplin client say "joplin android app" that makes sure the desktop app knows to update the file?

**Comment by tomasz1986** [comment]
This is probably expected, as those MD files aren't meant to be edited directly, especially since a single note can be comprised of multiple MD files (e.g. including older versions and various other pieces of information).

**Comment by roman-r-m** [comment]
You should not edit those files directly as it may break synchronization.

**Comment by tmfelwu** [comment]
I understand I need to be careful when editing those files. If someone aware of the internals can let me know this?

> What other files are being updated by another joplin client say "joplin android app" that makes sure the desktop app knows to update the file?

**Comment by roman-r-m** [comment]
What exactly are you trying to achieve?

**Comment by tmfelwu** [comment]
I am using obsidian with joplin. I am able to edit files in obsidian (which are basically the .md files that joplin puts on Dropbox). I want to be able to edit those files manually and let joplin think that some other joplin client (eg android app) edited those. 

It seems it is possible because I dont see any sqlite db in the files that joplin puts on Dropbox.

Moreover, when I use the following feature I am able to see my changes from Obsidian being reflected in Joplin.
![image](https://user-images.githubusercontent.com/8553391/187662736-14b01f00-2ee1-451c-88aa-e2f6b4f0fef9.png)

So There is a difference in how joplin android app is updating those Dropbox files and how I am doing it manually. I need to know that diffference.

PS i understand i cant change the filename and metadata and stuff, as it might mess up sync

**Comment by tomasz1986** [comment]
> I need to know that diffference.

Well, as this isn't the intended and documented use case, I'd assume you will probably have to figure this out 
 yourself. You can do this either by studying the source code, or simply making a copy of the filesystem sync folder before and after making changes to a note in Joplin, and then comparing the two.
