### ISSUE TITLE
Inconsistencies in numbered items between markdown panel and preview

### ISSUE THREAD

**Issue by lbo34** [laurent22/joplin#6804]
I have a strange behaviour:
I am using numbered items but I need to skip number. For instance, I write

<img width="104" alt="image" src="https://user-images.githubusercontent.com/18358046/188171234-4e33a888-6e55-436c-a2b0-0c2d4491d599.png">

and I get 
1. a first thing 
3. a third thing
5. a fifth thing 

Please see example here:

<img width="2117" alt="image" src="https://user-images.githubusercontent.com/18358046/188170749-10f3e687-943e-4cd3-a24e-ad0e25c545b7.png">

## Environment

Joplin version: Joplin 2.8.8 (prod, darwin)
Platform: MacOS
OS specifics: 12.5

## Steps to reproduce

1. create a numbered list with "holes"
3. preview

## Describe what you expected to happen

I expect to see the numbers I have in the markdown editor. They seem to be renumbered when doing the preview and the PDF extraction

**Comment by personalizedrefrigerator** [comment]
See also https://superuser.com/questions/1399326/is-there-a-way-to-fix-the-numbering-of-a-numbered-list-in-markdown


For now, one workaround is to write the list with HTML:
```md
<div>
1. Test<br/>
3. Another test<br/>
5. Yet another test<br/>
</div>


```

**Comment by Daeraxa** [comment]
It is simply part of the commonmark spec so Joplin is behaving as designed according to spec. Basically it uses a start marker number then ignores subsequent numbers, just incrementing until the list ends. https://spec.commonmark.org/0.30/#ordered-list-marker

You can see the exact same behaviour on the commonmark reference implementation:
https://spec.commonmark.org/dingus/

![image](https://user-images.githubusercontent.com/58074586/188187159-a839f698-d181-4677-a484-a62d1324b1f6.png)
