### ISSUE TITLE
Mobile: Markdown toolbar: Pressing bold then italicize doesn't make a bold-italic region.

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#6808]
## Environment

Joplin version: e40d7331767e4de4e90021d433c75f3dbb2b7672
Platform: Mobile
OS specifics: Android 12

## Steps to reproduce

1. Enable the beta editor
2. Open a note
3. Move the cursor to a blank line
4. Press the bold button
5. Press the italicize button

## Describe what you expected to happen
A bold-italic region should be created at the cursor.

**Comment by Daeraxa** [comment]
Interestingly this is the same behaviour as seen in the desktop app so having not looked into it I assumed it was somewhere upstream.
i.e.
`I` -> `B` = Strong emphasis
`B` -> `I` = Emphasis only

**Comment by personalizedrefrigerator** [comment]
> Interestingly this is the same behaviour as seen in the desktop app so having not looked into it I assumed it was somewhere upstream.
> i.e.
> `I` -> `B` = Strong emphasis
> `B` -> `I` = Emphasis only

The markdown formatting logic has been re-written to take advantage of the syntax tree generated by CodeMirror 6's markdown parser. As such, for now, the mobile app has separate code for doing markdown formatting. We can replace/merge with the desktop app's markdown formatting logic when/if we migrate the desktop app to CodeMirror 6.
