### ISSUE TITLE
Documentation still missing Terminal syncronization with Joplin Cloud

### ISSUE THREAD

**Issue by taw00** [laurent22/joplin#6809]
It's been almost a year since this missing bit was noticed. Can we please fix it? Joplin Cloud as sync target is implied by listing Joplin Cloud in the keys/values section, but in the higher-level explanatory text (what folks read first), it is missing.

Reference:

- https://discourse.joplinapp.org/t/joplin-cloud-sync-support-for-linux-terminal-app/22594/4
- https://joplinapp.org/terminal/

**Comment by Daeraxa** [comment]
Part of it was resolved as I remember updating the terminal help with the newer commands but I think the higher level Cloud sync info is also missing from the main docs - along with Joplin Server but as that is still marked as beta then I guess it makes sense why it is still missing.
