### ISSUE TITLE
not able to add tags with webclipper

### ISSUE THREAD

**Issue by 0vermind** [laurent22/joplin#681]
Hi guys,
I just discovered Joplin looking for a replacement for Evernote.
I am amazed at how many features it has! Well done!
I'm not able to add tags at saving time of a webpage with the webclipper. Is there any way to do it?
Thanks in advance

### Operating system

- Windows

### Application
- Desktop web clipper with chrome browser

**Comment by foxmask** [comment]
no, not yet and until you ask :)

**Comment by 3d73a4a412** [comment]
+1!
To add to this thoughts, the old del.icio.us bookmarking addon (or maybe it was a bookmarklet?) was great in that it gave a list of tags that one could pick from, but not pull down menu (am start to hate those things) but just a list of tags like:
https://www.socialmediaexaminer.com/images/1010kh-delicious-save-bookmark.jpg
actually that post https://www.socialmediaexaminer.com/how-to-use-delicious-social-bookmarking/ pretty much covered how delicio.us is (was) awesome at tagging!! 
For me though, the option having tags in a list is most important, either all maybe tag cloud, or most common tag in joplin, or last uses? 
Anyway, thank you for a grate program!!
