### ISSUE TITLE
Single quotation marks show an error

### ISSUE THREAD

**Issue by kN6jq** [laurent22/joplin#6810]
## Environment

Joplin version: 2.8.8
Platform: windows
OS specifics:  win10

## Steps to reproduce

ok，When I use makedown to edit, the single quotes are displayed incorrectly
![image](https://user-images.githubusercontent.com/27048404/188275963-e5bd72bf-f2f5-4970-aeb1-eff18c1270d0.png)

I think what should be shown is   (       '    )
But it is now  like picture

**Comment by personalizedrefrigerator** [comment]
Are you using a theme, or is that the default? Can you please paste a copy of one of the single quotes that isn't displaying correctly? It's possible it's the character <code>&lsquo;</code> and not the character <code>'</code>.

**Comment by personalizedrefrigerator** [comment]
It might also be the editor's monospace font:
![Editor font can be found under appearance, then editor monospace font family](https://user-images.githubusercontent.com/46334387/188289802-93d97ea8-5631-4276-93ce-963f3703ce4f.png)
Try changing the font in settings.

**Comment by kN6jq** [comment]
I confirm that it is  '  
Because I copied him out It also shows  '

![image](https://user-images.githubusercontent.com/27048404/188299205-2d23741f-ab3e-4e69-85ec-6cee81a3966e.png)
