### ISSUE TITLE
Unable to launch portable version in Windows

### ISSUE THREAD

**Issue by earthjasonlin** [laurent22/joplin#6812]
## Environment

Joplin version: v2.8.8 and v2.9.4
Platform: Windows Portable
OS specifics: Windows 10 21H2 Aug. x64 Enterprise

## Steps to reproduce

1. Download portable version
2. Double-click to launch

You can see the process in task manager for about 3 sec, but there's not a window and the process terminated itself. No errors, no warnings, no logs.

## Describe what you expected to happen

Start normally

**Comment by earthjasonlin** [comment]
However, it works after I extracted it and launched it maually

**Comment by wh201906** [comment]
@earthjasonlin The portable version is provided in .exe format. I wonder how do you "extract" the portable version. Did you archive the portable executable with the `JoplinProfile` folder in an .zip or .7z file?

**Comment by earthjasonlin** [comment]
Nope, I did it by right click the JoplinPortable.exe file and then open with winrar, so that it can be extracted

**Comment by wh201906** [comment]
I can't reproduce this bug by following your steps. I tried the portable version of v2.9.4 and it works fine.  
Maybe your anti-virus software blocks the self-extract process?
