### ISSUE TITLE
Update electron to have the fix for kernel page size on linux so it can ran on Asahi linux without the need of a 4k kernel

### ISSUE THREAD

**Issue by cmalvi** [laurent22/joplin#6813]
Install Joplin on Asahi linux (Macbook Air M1 2020)
you can run it only if you have a 4k kernel due to not updated electron 

## Environment

Joplin version: 2.8.8
Platform: Linux
OS specifics: Asahi Linux

**Comment by roman-r-m** [comment]
Do you know which version of electron is required?

**Comment by cmalvi** [comment]
> Do you know which version of electron is required?

The fix is from 19 or 20 I think, but the patch was also backported to previous version but I don’t know them precisely

Edit: for info, is fixed from chromium 102

**Comment by root-io** [comment]
Fixed in electron v18.3.2

**Comment by brad** [comment]
@cmalvi #6888 fixes this. [Here](https://github.com/alfredopalhares/arch-pkgbuilds/pull/117) is a PR to fix the `PKGBUILD` in the AUR

**Comment by cmalvi** [comment]
> @cmalvi #6888 fixes this. [Here](https://github.com/alfredopalhares/arch-pkgbuilds/pull/117) is a PR to fix the `PKGBUILD` in the AUR

Thank you! :)

**Comment by cmalvi** [comment]
@brad does this also apply to the AppImage?

**Comment by brad** [comment]
@cmalvi I think so. If you do a build with this change, you should get a working AppImage

**Comment by cmalvi** [comment]
> @cmalvi I think so. If you do a build with this change, you should get a working AppImage

Seems the release AppImage is only for x64, so seems a no go for now.
Thanks for you help :)

**Comment by brad** [comment]
@cmalvi Do you mean the official builds made by github actions? Yeah, I didn't change those, but when you build locally in Asahi you get an arm64 AppImage
```
> yarn workspace @joplin/app-desktop run electron-builder build --linux                                                                                                
  • electron-builder  version=23.0.8 os=5.19.0-asahi-5-1-ARCH
  • loaded configuration  file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=dist/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=linux arch=arm64 electron=19.0.10 appOutDir=dist/linux-arm64-unpacked
  • building        target=AppImage arch=arm64 file=dist/Joplin-2.9.8-arm64.AppImage
  ```

**Comment by cmalvi** [comment]
> @cmalvi Do you mean the official builds made by github actions? Yeah, I didn't change those, but when you build locally in Asahi you get an arm64 AppImage
> 
> ```
> 
> > yarn workspace @joplin/app-desktop run electron-builder build --linux                                                                                                
> 
>   • electron-builder  version=23.0.8 os=5.19.0-asahi-5-1-ARCH
> 
>   • loaded configuration  file=package.json ("build" field)
> 
>   • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies
> 
> 
> 
> To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
> 
>   • writing effective config  file=dist/builder-effective-config.yaml
> 
>   • skipped dependencies rebuild  reason=npmRebuild is set to false
> 
>   • packaging       platform=linux arch=arm64 electron=19.0.10 appOutDir=dist/linux-arm64-unpacked
> 
>   • building        target=AppImage arch=arm64 file=dist/Joplin-2.9.8-arm64.AppImage
> 
>   ```

Do I need to download the AppImage every time or there is an internal auto update?

**Comment by cmalvi** [comment]
The fix is from 19 or 20 I think, but the patch was also backported to previous version but I don’t know them precisely
