### ISSUE TITLE
Hello! It does not work after the editor font size setting is found during use. Please find the cause and fix it in time. 1. In the process of using, it is found that the font size setting of the editor does not work. 

### ISSUE THREAD

**Issue by zhouxinghong** [laurent22/joplin#6814]
Hello! It does not work after the editor font size setting is found during use. Please find the cause and fix it in time.
1. In the process of using, it is found that the font size setting of the editor does not work. Please find the cause and fix it in time.
2. [Network image download is very slow] After pasting the clipboard image into the editor, the download is very slow.
System: Windows10 19043
Version: Jop 2.9.4

**Comment by zhouxinghong** [comment]
![image](https://user-images.githubusercontent.com/54253524/188304533-7f4c26eb-841f-4990-a475-710eaaf018ad.png)

**Comment by personalizedrefrigerator** [comment]
The editor font size only seems to apply to the markdown editor, not the rich text editor. It should probably be applied to both.

For now, one way to adjust the editor (and app) font-size is `ctrl++` and `ctrl+-`.

**Comment by personalizedrefrigerator** [comment]
Another way to adjust the font size in the rich text editor is to click "custom stylesheet for rendered markdown", type
```css
#rendered-md {
  font-size: 24pt;
}
```
and restart the app. This adjusts the font size in the markdown preview window and the rich text editor.

![](https://user-images.githubusercontent.com/46334387/188308788-00b6edb0-da69-45c5-aed9-3731bbcb39b5.png)

**Comment by zhouxinghong** [comment]
> The editor font size only seems to apply to the markdown editor, not the rich text editor. It should probably be applied to both.
> 
> For now, one way to adjust the editor (and app) font-size is `ctrl++` and `ctrl+-`.

This method is to enlarge all fonts, including (UI, editor, images) will be enlarged, this is not the effect I want, I only want the editor font to be enlarged, the best way is to support Ctrl + mouse scroll zoom.😜

**Comment by zhouxinghong** [comment]
>

**Comment by Daeraxa** [comment]
Closing to stop whatever pattern is going on here...
