### ISSUE TITLE
[Network image download is very slow] After pasting the clipboard image into the editor, the download is very slow

### ISSUE THREAD

**Issue by zhouxinghong** [laurent22/joplin#6816]
[Network image download is very slow] After pasting the clipboard image into the editor, the download is very slow.
System: Windows10 19043
Version: Jop 2.9.4

**Comment by zhouxinghong** [comment]
Can you try pasting the image below into the jop editor and see how it works?
![src](https://c0.jdbstatic.com/samples/y3/y3Vvv_l_9.jpg

**Comment by Daeraxa** [comment]
Works instantly for me

**Comment by zhouxinghong** [comment]
> Works instantly for me

How do you do it? Are you using the right-click menu to paste? Still use Ctrl+V to paste into the editor, and I find that sometimes the image will be compressed and lose quality after pasting. The image pasted into the editor is much smaller than the original image. . .

**Comment by tomasz1986** [comment]
Are you sure it's not the website that uses scaled down and lower quality images on the page, and only link to the originals, e.g. on click? This is very common, e.g. when you use the Web Clipper to save some news articles, which often ends up with low quality images. I then need to go back to the site and copy and paste the original images over the low quality ones manually.

**Comment by Daeraxa** [comment]
@zhouxinghong Just right click copy, right click paste. I don't see any reduction in quality either.

**Comment by zhouxinghong** [comment]
> @zhouxinghong Just right click copy, right click paste. I don't see any reduction in quality either.

Thanks!👍😜

**Comment by Daeraxa** [comment]
Closing to stop whatever pattern is going on here...
