### ISSUE TITLE
A bug using espanso when spell checking in Markdown editor is enabled

### ISSUE THREAD

**Issue by ivangretsky** [laurent22/joplin#6818]
## Environment

Joplin version: 2.8.8
Platform: Windows
OS specifics: 10

## Steps to reproduce

1. Install espanso app (https://espanso.org/).
2. Configure Joplin to enable spell checking in Markdown editor.
3. Open Joplin note in markdown mode and run any [espanso match](https://espanso.org/docs/matches/basics/) (1 on the screenshot)
4. See that the replacement text (2 on the screenshot) is put on the top of the note, not where it should appear. In addition the trigger part is not removed. When spell checking is off everything works as expected.

![изображение](https://user-images.githubusercontent.com/6697626/188405667-f30d8a89-097d-4c48-b56f-2241f3924e85.png)

## Describe what you expected to happen

The repacement text (2) should replace the trigger text (1) where it is.

## Logfile

[joplin-log.txt](https://github.com/laurent22/joplin/files/9488111/joplin-log.txt)

**Comment by Daeraxa** [comment]
I actually suspect this is the same bug as https://github.com/laurent22/joplin/issues/6432

That one can be replicated by hitting a key and backspace at the same time and it only seems to happen when the spellcheck it turned on, I suspect espanso is performing a similar set of "key presses" which cause this to happen more reliably.

**Comment by ivangretsky** [comment]
It still needs attention.
