### ISSUE TITLE
Writing in the WYSIWYG editor adds addtional new lines inside code and math expressions

### ISSUE THREAD

**Issue by magical-heyrovsky** [laurent22/joplin#6822]
The problem is best explained by watching the video:

[2022-09-05_16-19-05.webm](https://user-images.githubusercontent.com/101060148/188470914-baaf75b8-cd96-4135-ab59-4f394ad8472d.webm)

## Environment

Joplin version: 2.8.8
Platform: Ubuntu 22.04

## Steps to reproduce

1. While in the markdown editor write a math expression between $$ $$ anywhere in the document
2. Now switch to the WYSIWYG editor and add additional text outside the math expression.
3. Switch back to the markdown editor and notice that a additional line was automatically added inside the $$ $$.
4. Repeat step 2-3 and every time a additional new line will be added inside the $$ $$.

## Describe what you expected to happen

The additional new line should not be added.

## Logfile

Let me know if you need a logfile and I will provide one.

**Comment by personalizedrefrigerator** [comment]
I can confirm this is still an issue in Joplin 2.9.4 (built from source).

**Comment by SuperSamus** [comment]
Also happens with code blocks ` ``` `.

**Comment by personalizedrefrigerator** [comment]
There are tests that seem to pass that should be catching this: https://github.com/laurent22/joplin/blob/dev/packages/app-cli/tests/html_to_md/mathjax_block.md?plain=1

**Comment by magical-heyrovsky** [comment]
I noticed that the switching between Markdown and WYSIWYG has nothing to do with it. Just writing something in the WYSIWYG editor adds these new lines. So if I create a new note and start writing in the WYSIWYG editor and after minutes switch to the Markdown editor I will find something like this wherever I have code or math expressions:

```
$$
a + b







$$
```

And not even the "external editing" feature can prevent this problem. This is really bad.

**Comment by magical-heyrovsky** [comment]
The problem remains, issue should stay open.

**Comment by magical-heyrovsky** [comment]
The problem remains, issue should stay open.

**Comment by magical-heyrovsky** [comment]
> The problem remains, issue should stay open.

**Comment by chronos1970** [comment]
This bug is the main reason why I don't use the WYSIWYG editor anymore. All of my notes end up being filled with empty lines.
