### ISSUE TITLE
The keyboard appears while scrolling in edit mode

### ISSUE THREAD

**Issue by jcperil** [laurent22/joplin#6825]
## Environment

Joplin version: 2.8.1
Platform: Android
OS specifics: Android 12

## Steps to reproduce

1. Create a note with more than one page of content and then return back to **All Notes**
2. Open the note and click edit button. By default, we are at the bottom of the content.
3. Scroll upwards. As soon as you release your finger from scrolling, default keyboard appears.

## Describe what you expected to happen

The keyboard would not appear while scrolling. I expect it to appear when I click somewhere, not while scrolling.

https://user-images.githubusercontent.com/89805719/188607739-7c8c1a0e-4b01-41fb-8a37-e4192f8ab949.mp4

**Comment by personalizedrefrigerator** [comment]
Consider enabling the beta editor in settings — it shouldn't have this issue.
