### ISSUE TITLE
TOC regularly replaced by a list

### ISSUE THREAD

**Issue by IStevant** [laurent22/joplin#6828]
## Environment

Joplin version: 2.8.8
Platform: Linux
OS specifics: Debian

## Steps to reproduce

1. Insert `[TOC]` (or `[[TOC]]`) at the top of a note
2. Navigate around other notes, or close the application
3. Go back to the note with the `TOC` and see the `[TOC]` disappeared and is replace by a markdown list

I am trying to enhance the style of the pdf I export from my notes for professional communication. I used the `.table-of-contents` attribute to customize the TOC in the css but when the `[TOC]` is replaced by the simple markdown list, the attribute is removed (I checked on the html version of the page), and so the style is broken. The replacement seems to happen randomly but at a high frequency. I can recover the style by deleting manually the list and replace again by `[TOC]` but it is quite annoying.

**Comment by roman-r-m** [comment]
Could be a plugin. Do you have any installed?

**Comment by IStevant** [comment]
I have the 'plugin bundle' installed.
I just disabled it, but the problem is still here.

Just to specify, I use the WYSIWYG editor by default, except to add the `[TOC]` or some other markdown stuff.

**Comment by roman-r-m** [comment]
Ok, I was able to replicate it like this
* start a new note in the WYSIWYG mode
* add a few headers
* switch to the Markdown editor
* add `[[TOC]]`
* switch back to WYSIWYG
* edit the note
* switch back to MD - the TOC is gone and replaced with links

I think it general Joplin doesn't handle very well editing the same note in both editors, it's not the only issue that can happen when you do try doing this.

**Comment by IStevant** [comment]
This is problematic. 
Would it be possible to add a button in the WYSIWYG to add a TOC then, to avoid switching between the two editors?
I will try to use the double view contently from now to avoid this behavior.
