### ISSUE TITLE
Plugins missing with 2.9.4

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#6829]
## Environment

Joplin 2.9.4 (prod, darwin)

Client ID: fa27762d267e4dcfaed6169a925e6ea0
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 6277958d6 (dev)

## Steps to reproduce

0. Run 2.8.x with plugins installed
1. Install 2.9.4 (build with `yarn run dist` at hash `6277958d6`)
2. Go to `Preferences... > Plugins`
3. no plugins are shown as installed

## Describe what you expected to happen

The plugins that are installed should show up and be available/enabled.

## Logfile

```
2022-09-07 17:52:36: App: "There was an error loading plugins from /Users/XXXX/.config/joplin-desktop/plugins:", "Error: Error: ENOENT: no such file or directory, scandir '/Applications/Joplin.app/Contents/Resources/build/defaultPlugins'
Code: ENOENT
Error: Error: ENOENT: no such file or directory, scandir '/Applications/Joplin.app/Contents/Resources/build/defaultPlugins'
    at FsDriverNode.fsErrorToJsError_ (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/fs-driver-node.js:22:24)
    at FsDriverNode.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/fs-driver-node.js:139:28)
    at Generator.throw (<anonymous>)
    at rejected (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/fs-driver-node.js:6:65)"
```

Error in console:

```
Logger.ts:219 17:45:08: App: There was an error loading plugins from /Users/XXX/.config/joplin-desktop/plugins: Error: Error: ENOENT: no such file or directory, scandir '/Applications/Joplin.app/Contents/Resources/build/defaultPlugins'
    at FsDriverNode.fsErrorToJsError_ (fs-driver-node.ts:12:23)
    at FsDriverNode.<anonymous> (fs-driver-node.ts:115:15)
    at Generator.throw (<anonymous>)
    at rejected (/Applications/Joplin…driver-node.js:6:65)
Setting.ts:1702 Uncaught Error: Unknown key: plugin-io.github.jackgruber.backup.path
    at Function.settingMetadata (Setting.ts:1702:33)
    at Function.formatValue (Setting.ts:2049:19)
    at Function.setValue (Setting.ts:1901:16)
    at Object.setSettingsForDefaultPlugins (defaultPluginsUtils.ts:45:13)
    at app.ts:330:5
```

# Additional info

I even tried to install a plugin that was already installed, but after restarting Joplin it also does not show up as installed:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/223439/188924269-bfa9b92d-1575-4320-ba95-c22feccf3332.png">

**Comment by CalebJohn** [comment]
@mak2002 is this fixed by #6827?

**Comment by mak2002** [comment]
These 2 errors should be fixed by #6827. I will try to replicate and confirm it though.

**Comment by mak2002** [comment]
I tried it and #6827 is indeed fixing these 2 errors and you can access all of your installed plugins. If you want to try App-image from the [patch branch](https://github.com/mak2002/joplin/tree/dev-mode-fix-for-default-plugin), here's the [link](https://drive.google.com/file/d/1-ABf0u-AQxDf4atwyghxwUSazYhnhIIN/view?usp=sharing)

**Comment by tessus** [comment]
I can't run an AppImage on macOS. ;-)

I'll test the PR after work (probably in 3.5h). I've noticed the error yesterday and opened the issue today before checking the PRs. I usually check the commits in the dev branch, before opening an issue, but I didn't check the PRs.

**Comment by tessus** [comment]
Ok, I have had a few minutes to test this. It works - almost.

Unfortunately it automatically enables all my installed plugins. e.g. I had 3 plugins disabled (out of 8), because I usually do not need them and only enable them occasionally for testing purposes.
After I ran this branch (even just locally without creating a package), all the plugins showed up, but my 3 disabled plugins were enabled as well. This is IMO a bug.

**Comment by laurent22** [comment]
So to be clear it's not 2.9.4, but a custom build from dev, is that correct?

The whole thing seems so buggy anyway. @mak2002 are you able to replicate this bug where all plugins get re-enabled?

**Comment by tessus** [comment]
@laurent22 yes, I built the dev branch at the commit I specified in my first post. I forgot to check if a 2.9.4 pre-release binary was available. I now also tested with the official dmg from github. Same issue.

And then I ran (and also built a dmg) from the PR branch #6827. Which fixed the issue of the plugins no showing up in the config panel, nor them being enabled. But it automatically enabled even disabled plugin at the first start.

**Comment by mak2002** [comment]
Laurent , I am not able to replicate this bug where all plugins get re-enabled. In my case, I ran 2.8.8 with plugins and then ran custom build from #6827 branch. It didn't enable disabled plugins.

@tessus , Is it giving you any errors in console?

**Comment by mak2002** [comment]
@laurent22 , I am not able to replicate this bug where all plugins get re-enabled. In my case, I ran 2.8.8 with plugins and then ran custom build from #6827 branch. It didn't enable disabled plugins.

@tessus , Is it giving you any errors in console?

**Comment by tessus** [comment]
Nope, no errors. And when I disable them again, they stay disabled.

I only noticed that they were enabled (when I started Joplin from the branch) because I tested the White Theme a while back, but then disabled it. I use Dark mode, so when I started Joplin it looked like a mess, since random elements were white....

**Comment by mak2002** [comment]
Hey, I just tested on Ubuntu VM and it works fine. First I started AppImage (2.8.8) and installed White theme along with some plugins and then disabled the White Theme plugin. After this, I started the AppImage built from #6827 PR branch and the plugin stayed disabled.

**Comment by tessus** [comment]
Ok, then. Not sure why my disabled plugins got enabled then. I certainly didn't do anything weird.

**Comment by mak2002** [comment]
It would be great if someone else can try and confirm this.

**Comment by laurent22** [comment]
> Ok, then. Not sure why my disabled plugins got enabled then. I certainly didn't do anything weird.

How about the plugin settings? Do you know if they were reset?

**Comment by tessus** [comment]
@laurent22 I am not sure on my dev machine, but I don't think so. I'll check on the other MacBook as well. I don't have too many plugins there, so I should have remembered all settings.

**Comment by tessus** [comment]
@laurent22 it looks like the settings were reset to the default.

**Comment by mak2002** [comment]
Hey tessus, Was this on your first testing or you tried this on another machine? Also today, I tried it again by running on fresh Ubuntu VM and it worked fine. Maybe this is a Mac-OS specific issue.

**Comment by tessus** [comment]
It's hard to say. On my dev machine I use the dev version in the branch (`yarn run start`), but also have a "release version" running. On the other macOS machine I always replace the binary with another one. Either a release version or a version I built (e.g. the on for your branch).
I would have to start tests from scratch, but don't have the time to do so at the moment.

It just looks to me that in all Joplin instances I am running, the plugin settings are reset to their defaults.

**Comment by laurent22** [comment]
I confirm I got a similar bug in latest release, except that for me all my plugins were gone. This seems to be due to [this bug](https://github.com/laurent22/joplin/pull/6827) which prevents the plugins from being loaded at all.

**Comment by mak2002** [comment]
As #6827 is merged, this issue should be fixed except on macOS. On macOS, as pointed out by Laurent on Discord, bundled plugins should be signed in order to install them. 

I think after signing the bundled plugin, this issue should be completely fixed!

**Comment by laurent22** [comment]
@mak2002, what would be the fix for the unsigned 7zip executable? Doesn't seem simple

**Comment by mak2002** [comment]
I am still learning about signing files and executables, but for now, I think default plugins' developers have to sign the executable on their own, so they can be installed on macOS. 

For this, there are 2 options:
1. Signing with Apple Developer ID, which is paid, if I am not wrong. 
2. Signing with open source tool like PGP or GPG. 

But after a bit of searching, I found that to pass Gatekeeper on macOS, we must have a code signing certificate, which is signed with your Apple Developer ID. I think, we have to go with option 1.
Also, I guess this issue will come up with any default plugin we bundle, not just with 'Simple backup' plugin.

Although, I am still thinking if there is another way to fix this unsigned 7zip issue.

**Comment by laurent22** [comment]
Maybe bring that up to the plugin developers to see if they have any suggestion.
