### ISSUE TITLE
Not able to install Joplin in Archlinux

### ISSUE THREAD

**Issue by cypherkaka** [laurent22/joplin#683]
### Operating system

- Linux  (Arch Linux)

### Application

- Desktop
- Terminal

[2018-07-13T20_50_45_367Z-debug.log](https://github.com/laurent22/joplin/files/2194163/2018-07-13T20_50_45_367Z-debug.log)

**Comment by foxmask** [comment]
how do you proceed ?

**Comment by cypherkaka** [comment]
I was trying to install Joplin into Arch linux via AUR package manager

`trizen -S joplin`

**Comment by foxmask** [comment]
you dont have to ... get tha AppImage from https://github.com/laurent22/joplin/releases and run it.

> Please see last comment at https://aur.archlinux.org/packages/joplin/ as well.

leads to a 404.

**Comment by MarcusE1W** [comment]
I think I had the same error. As I see it it occurs when _node-gyp_ get’s installed.
In my case I have installed node-gyp with npm seperately first, that worked and then I could install joplin as well.

**Comment by mannp** [comment]
I am having the same issue and trying to install node-gyp manually gives me the same error.

Installing nodejs-lts-carbon with trizen fixed it for me.

**Comment by laurent22** [comment]
The AppImage currently is the only way to install the app. Unless there's an easy way to do it, package managers won't be supported.
