### ISSUE TITLE
sync cancel hangs

### ISSUE THREAD

**Issue by jjon** [laurent22/joplin#6835]
Joplin 2.8.8 (prod, darwin) client on macbook pro OS 11.6, using WebDav as sync target. Often after system sleep I return to find sync cancel endlessly cycling:
![image](https://user-images.githubusercontent.com/279479/189453359-4d956707-270a-4384-863f-9a3efb39655b.png)

updated or new items are saved locally, but in order to sync I have to quit Joplin and open it again
Is there any way to cancel the cancel, or coerce the sync?

update: Also, 'Hard reload page' from within Dev Tools sometimes (frustratingly, not always) breaks the cycle, and sync then commences.

**Comment by ericswpark** [comment]
Maybe mashing the cancel button should act as a “force cancel” after a couple of times – or just even once. I’ve definitely had sync hang a couple of times, but I just let it sync and it clears up after a while. But maybe I don’t have a large amount of notes that causes this bug.

**Comment by Mr-Kanister** [comment]
I can confirm, this bug has existed for some time:
https://discourse.joplinapp.org/t/sync-issue-on-file-system-dropox-folder/25310

Unfortunately it is very hard to replicate it, because it only happens infrequently.
