### ISSUE TITLE
Note view not scrolling while typing on mobile

### ISSUE THREAD

**Issue by ericswpark** [laurent22/joplin#6837]
Whenever the text wraps around and goes to the next line, the view should scroll so the text is still visible. However, currently the keyboard keeps hiding the typed text, making it rather tedious as manually scrolling the view is required. 

## Environment

Joplin version: 12.8.1
Platform: iOS ~~(maybe Android too?)~~
OS specifics: iOS 15.6.1, iOS 16

## Steps to reproduce

1. Type a long document
2. Keep typing until text wraps around, underneath the keyboard

## Describe what you expected to happen

The view should scroll up as the line wraps so it continues to stay in view.

## Logfile

N/A

**Comment by personalizedrefrigerator** [comment]
Does this work in the beta editor (try enabling it in settings)?

**Comment by ericswpark** [comment]
@personalizedrefrigerator I'm unable to find the option in settings. Does the option exist for the iOS app? If so, what is the name of the option exactly? I don't see anything for beta editor. Sorry if I'm missing something obvious.

**Comment by personalizedrefrigerator** [comment]
![Going to configuration -> note, then turning on opt into the editor beta](https://user-images.githubusercontent.com/46334387/190227220-74f7df07-a8ff-4068-805d-dbec08ba46e1.jpeg)

There are some iOS-specific bugs with the beta editor. For example, the keyboard is always in light mode (an upstream react-native-webview bug).

**Comment by ericswpark** [comment]
@personalizedrefrigerator thanks, I finally found it thanks to your screenshot. I can confirm it doesn’t happen in the beta editor, although I’m not sure if it will happen sometime as I’ve briefly tested the editor. It’s possible that the bug may occur again given enough usage. 

I also encountered the light keyboard bug you mentioned, as well as a bug where the keyboard autocorrect suggestions not showing. Hopefully these bugs can be fixed so that the editor could be used as a replacement. Thanks for the reply!

**Comment by ericswpark** [comment]
I’ll keep this bug report open until either the bug gets fixed in the regular editor, or until the beta editor gets promoted to stable.

**Comment by wh201906** [comment]
I tested it on Android(v2.9.2) with the beta editor on and off. The bug doesn't appear in both cases.

**Comment by ericswpark** [comment]
@wh201906 thanks for the confirmation. I'll edit the OP to show that it seems to be an iOS-specific issue.

**Comment by ericswpark** [comment]
Bug persists in iOS 16.

**Comment by wh201906** [comment]
I found a similar bug #3607 and it should have been fixed in #4794

**Comment by ericswpark** [comment]
@wh201906 that seems to be a different issue. In my issue I *am* able to scroll to the last line. But it should automatically scroll as I keep typing content so I don’t have to flick up every now and then while typing.

**Comment by wh201906** [comment]
Ok.

**Comment by ericswpark** [comment]
This issue is still relevant; please do not close

**Comment by ericswpark** [comment]
Still relevant on latest Joplin 12.8.1 (no new updates since OP).

I've noticed that the text is obscured by the text replacements bar (the autocompleted suggestions bar that appears on iOS). Pressing enter will get the text to scroll.

**Comment by ericswpark** [comment]
I've tested the new beta editor on 12.9.1 on iOS/iPadOS and can confirm it is way better now. The white theme bug is gone and the text autocorrect works. Since the bug can now be worked around and will disappear once the beta editor gets switched out with the stable one I will close this issue.
