### ISSUE TITLE
custom application layout is lost after switching profiles and switching profile back

### ISSUE THREAD

**Issue by o5t6iaqo7** [laurent22/joplin#6840]
Posted almost a month ago without an answer yet so I am newly also posting to Joplin forums:

[](https://discourse.joplinapp.org/t/problem-switching-profiles-app-layout-forgotten/27706)

https://discourse.joplinapp.org/t/problem-switching-profiles-app-layout-forgotten/27706

Appreciate any workaround / solution. Too busy to do a lot of troubleshooting. My need is to have an entirely separate profile but I can easily switch databases. My main database / profile needs to sync to JoplinCloud but not the others. Thanks!

## Environment

Joplin version: 2.8.8 (prod,darwin)
Platform: macOS
OS specifics: 12.5.1

## Steps to reproduce

1. have customized profile layout similar to screenshot 1 (note, I have Favorites v1.3.0 plugin as part of my custom layout)
2. create a new profile
3. switch profile to new profile (no need to customize Layout for new profile)
4. switch profile back to Default profile (original)
5. custom application Layout for Default has been reset, one has to customize again
6. each time I switch profiles, custom layout of my primary / Default resets

## Describe what you expected to happen

Custom application layouts will be remembered / linked to each profile, so automatically restored upon switching profiles, especially for my primary (Default) profile.

Logfile very long incl hash/crypto info for Joplin cloud maybe - is there a way to export shorter / non-private log if you need?

kindly see screenshots this should make bug / unexpected behavior clear:

<img width="1346" alt="1 correct custom layout" src="https://user-images.githubusercontent.com/2606359/189550383-977c9e12-d8e4-41ce-a45b-a8a6cf8f2fd4.png">
<img width="1442" alt="2 layout of new profile" src="https://user-images.githubusercontent.com/2606359/189550384-fa9b72b6-a023-485f-8b05-9aab6f40fffd.png">
<img width="1443" alt="3 layout of original profile after switching back - customization lost" src="https://user-images.githubusercontent.com/2606359/189550387-56e17668-9912-4092-b5e8-77a2a0505a65.png">

**Comment by o5t6iaqo7** [comment]
In order to get support / feedback for any workaround - should I duplicate this post over in a different forum? Or add a different label?

**Comment by o5t6iaqo7** [comment]
added comment to keep from getting closed and cross-posted to Joplin forums Support - hoping someone can help!

**Comment by laurent22** [comment]
The layout is shared between profiles, so maybe that's your issue?

**Comment by o5t6iaqo7** [comment]
> The layout is shared between profiles, so maybe that's your issue?

Ahh. That explains it. I had assumed profiles had independent layouts, much as Firefox and Chrome user profiles customize the interface. Please consider this a feature request.

In the meantime, as a workaround, is there a command or plugin to manually save and restore a layout? My plug-ins in my default profile, include Favorites, which adds a panel.
