### ISSUE TITLE
Unable to sync with Nextcloud and Tailscale on Android App

### ISSUE THREAD

**Issue by pustefix8965** [laurent22/joplin#6842]
## Environment

Joplin version: v2.8.1
Platform: Android
OS specifics: Android 12
Tailscale: version 1.30.0

## Steps to reproduce

1. Turn on Tailscale VPN
2. In Joplin Android app, Configuration->Synchronisation target "Nextcloud", specify the WebDAV URL to either Tailscale hostname or IP, e.g. https://nextcloud/remote.php... or https://tailscale_ip/remote.php...
3. Clicking on "Check Synchronization configuration" button will result in "Error, Network request failed"

## Describe what you expected to happen
Synchronisation with Tailscale turned on should be successful. The sync is working if I specify "https://nextcloud.example.com/remote.php..." in the URL. The sync is also working in Windows Joplin app when specifying "https://nextcloud/remote.php.." in the URL.

## Logfile
![Screenshot_20220912-110218_Joplin](https://user-images.githubusercontent.com/42058160/189566470-7adaa1fc-054a-481e-80f3-8e8075b56c36.jpg)

**Comment by pustefix8965** [comment]
The bug is still there.

**Comment by bitkris-dev** [comment]
Still same issue in 2026
