### ISSUE TITLE
[ FEATURE REQUEST ] Receive Email For Alarm

### ISSUE THREAD

**Issue by janus0** [laurent22/joplin#685]
Are there any plans to receive an email for todo alarms? I imagine the email might contain just the title of the todo, or something like that. Google keep uses this with it's reminder feature, but doesn't really do a good job of displaying the body of the todo, so I don't expect that here either (unless that's something you're interested in trying).

Thanks.

**Comment by laurent22** [comment]
Unfortunately that won't be supported as it would require the user to run an SMTP server on their computer.
