### ISSUE TITLE
No notebooks on Android with Dropbox Sync

### ISSUE THREAD

**Issue by langdon** [laurent22/joplin#6851]
Everything about sync seems to be working. As in, it syncs between desktops just fine. I also (seem to) have all the notes sync'd with the android mobile app. However, I do not seem to get any notebooks (all notes are in "all notes") unless I make a notebook on the mobile app then it shows up in both. I can't for the life of me figure this out. I suspect there may be something to do with the sync on dropbox, like is only part of the information going there or something.

## Environment

Joplin version: 2.8.8
Platform: Linux
OS specifics: Fedora Flatpak

Joplin version: 2.8.1
Platform: Android
OS specifics: Google Pixel 6

## Steps to reproduce

1. Sync via Dropbox
2. 
3. 

## Logfile

[syncReport-1663259789111.txt](https://github.com/laurent22/joplin/files/9577275/syncReport-1663259789111.txt)

**Comment by roman-r-m** [comment]
A common issue with Joplin on Android is that it syncs only as long as the app runs in foreground and the screen is on. Could be that the sync was interrupted when the screen switched off and the folders weren't synced.

**Comment by langdon** [comment]
Yeah, I thought that could be the case too. However, I have cleared the data, reinstalled, use dev mode to keep the phone on and unlocked on the app, moved the data on dropbox, forced a resync from desktop to dropbox, etc (some multiple times). I still encounter the same problem.

**Comment by roman-r-m** [comment]
The only other suggestion I have is to make sure clocks are in sync on your Linux and Android.

**Comment by langdon** [comment]
No idea what changed but this issue has gone away. Happy it is gone, sorry that there doesn't seem to be an obvious root cause :/
