### ISSUE TITLE
Creating a New Profile Caused Joplin Crash

### ISSUE THREAD

**Issue by StrangeCalibur** [laurent22/joplin#6854]
This is a hard one because I dare not do it again as I am now running Joplin as another user while logged in as my normal user on my work laptop. 

I had not seen the profile functionality before, so decided to create a new profile to see what happened. Joplin crashed immediately and ever since trying to open it causes the following error: 

<img width="360" alt="image" src="https://user-images.githubusercontent.com/15046126/190640316-bcfa6be8-fb29-4548-9d2e-4131097f7db1.png">

After seeing this I used sfc/ scannow and Dism /Online /Cleanup-Image /RestoreHealth which didn't work. I then tried removing Joplin from the system completely using revo and reinstalling but again, same error. 

My current way of running joplin is to shift right click, more options and to run as another user I created just for Joplin..... which is not ideal. 

Note: I am willing to try this again on another laptop of mine to see what happens if requested. 

## Environment

Joplin version: 2.8.8
Platform: Windows 11
OS specifics: Windows 11

## Steps to reproduce

1. Navigate to file
2. Switch Profile
3. Create new profile... 

## Describe what you expected to happen
Expected a new profile to be created and to be switched over to that profile. 

### Log Post Reinstall
[log.txt](https://github.com/laurent22/joplin/files/9584084/log.txt)

### Log Pre Reinstall
[log.txt](https://github.com/laurent22/joplin/files/9584091/log.txt)

**Comment by personalizedrefrigerator** [comment]
Things to try:
 * If you haven't already, move `C:/Users/your-main-account-username-here/.config/joplin-desktop` to the trash folder (or some other location where Joplin won't find it) and restart Joplin.
 * What happens if you open Task Manager before starting the broken version of Joplin? Does Joplin use a large amount of memory/is your machine low on memory when Joplin crashes?

**Comment by kauffy** [comment]
I discovered this same thing today. The moment I hit Enter after naming the new profile, Joplin CTDs, however, the new profile _is_ created, and upon opening Joplin next time, it is the profile opened-- no harm, no foul otherwise, it seems.
