### ISSUE TITLE
Latest Android Apk is missing

### ISSUE THREAD

**Issue by quwepiro** [laurent22/joplin#6863]
Dear Joplin-Team,
I do not know where could state this, whether here on GitHub or in the Forum.
However, the latest android release (https://github.com/laurent22/joplin/releases/tag/android-v2.9.2) is not available as an apk on https://github.com/laurent22/joplin-android.

I could help to set up a GitHub Action that automatically pushes an apk on every android release.

Thank you for this great project :heart:

**Comment by roman-r-m** [comment]
It's under "tags":
https://github.com/laurent22/joplin-android/releases/tag/android-v2.9.2

(Probably because it's pre-release)

**Comment by laurent22** [comment]
> I could help to set up a GitHub Action that automatically pushes an apk on every android release.

Do you have some experience with this? We'd be interested in such GitHub Action since currently I need to manually run a command on my laptop

**Comment by quwepiro** [comment]
I created some GitHub Actions based on Templates. But I do not think it is so difficult.
If you could post the command you are executing, I can give it a try in an own fork and then create a pull request.

**Comment by laurent22** [comment]
We just run `./gradlew assembleRelease` from packages/app-mobile
