### ISSUE TITLE
iPad sidebar too big in width

### ISSUE THREAD

**Issue by ericswpark** [laurent22/joplin#6866]
## Environment

Joplin version: 12.8.1
Platform: iPadOS
OS specifics: iPadOS 15.7 (19H12)

The default sidebar width on iPad is too big. It should cover maybe 1/3 or less of the screen. Right now it covers about 60%:

![C12D6C7C-8CD4-4E74-9E27-FA7E8CDFF628](https://user-images.githubusercontent.com/13326074/191026536-046ef8df-af9b-441c-aed7-648118221d5a.jpeg)

Or, it might be great if the iPad app can be changed to display both the sidebar and the content side-by-side if in landscape.

**Comment by Daeraxa** [comment]
There is a specific tablet UI coming soon as part of GSoC.
https://discourse.joplinapp.org/t/joplin-mobile-tablet-layout/25775

**Comment by ericswpark** [comment]
GSoC contributions are not merged yet; please do not close

**Comment by ericswpark** [comment]
Not merged yet, do not close

**Comment by ericswpark** [comment]
No longer an issue on 12.9.2!
