### ISSUE TITLE
Text does not auto scroll high enough above the keyboard

### ISSUE THREAD

**Issue by Jegber** [laurent22/joplin#6868]
When entering text, the text eventually becomes obscured by the keyboard's auto word guess strip. 

![image](https://user-images.githubusercontent.com/13168972/191126034-f5dc1a20-a89f-4e1f-a00f-ad5156da042e.png)

## Environment

Joplin version: 12.8.1
Platform: iPhone
OS specifics: iOS 15.6.1

## Steps to reproduce

1. In a note, type enough text that new lines eventually reach the keyboard. 
2. Notice that text appears underneath the word guess strip at the top of the keyboard. The text is not visible because it is obscured by the keyboard word guess strip. This is really annoying.

## Describe what you expected to happen

I expect that there will be some margin above the guess strip where the text content will auto scroll up with each new line. Note that this issue is occurring with soft wrap visual formatted new lines, not newline literals.

## Logfile
![image](https://user-images.githubusercontent.com/13168972/191126069-69f776ad-3993-41a0-b487-a3c10021de91.png)

**Comment by Daeraxa** [comment]
Can it be replicated if you enable the beta editor in the options?

**Comment by wh201906** [comment]
I guess it's the same bug as #6837

**Comment by wh201906** [comment]
I found a similar bug #3607 and it should have been fixed in #4794
