### ISSUE TITLE
Dropbox sync option not available in Terminal App

### ISSUE THREAD

**Issue by bitdom0** [laurent22/joplin#687]
### Operating system

- macOS

### Application

- Terminal

The docs instruct to set sync.target to 7 for dropbox. However this gives an error: "Invalid option value: "7". Possible values are: 2: File system, 3: OneDrive, 4: OneDrive Dev (For testing only), 5: N"

**Comment by foxmask** [comment]
In the meantime, can't you use the same profile of the Joplin GUI  by entering --profile so you could launch the terminal version ?

**Comment by foxmask** [comment]
you can keep the issue opened as it looks like to be a real bug as you described. Laurent will see what he could do.

**Comment by laurent22** [comment]
Could you try again with the latest CLI version?

**Comment by laurent22** [comment]
This is probably due to an old version of Joplin as I cannot replicate it.
