### ISSUE TITLE
Mobile app: note title not rendering some unicode characters

### ISSUE THREAD

**Issue by hhvitek** [laurent22/joplin#6870]
Android app: Some emoji unicode characters are not properly rendered in a note's **title**. Like this: 🤮 and this: 🧘 or 🧍
Those characters are rendered in note's body just fine...

## Environment

Joplin version: 2.8.1
Platform: Android
OS specifics: 7.1.2

## Steps to reproduce

1. Copy unicode character U+1F9CD (https://unicode-table.com/en/1F9CD/)
2. Paste it inside Desktop app into title of some note. See no issue there.
3. Open mobile app, sync and watch out for icons to (not) show up. There is some generic character indicating unrecognized icon instead.

Not sure if this is bug or issue with my mobile but:
For bug reports, please post them on GitHub - https://github.com/laurent22/joplin/issues
If you are not sure if it's a bug or not, PLEASE POST ON GITHUB ANYWAY.

**Comment by wh201906** [comment]
I can't reproduce this bug on my device with your steps.
I'm using Joplin 2.8.1 on Android 11.

Then I try it on Android 8, the U+1F9CD is not rendered even in my latest browser. So I guess this emoji is too new for your device.

**Comment by hhvitek** [comment]
Weird thing to me is difference between note's body and note's title. Body supports those icons just fine on my device but title does not...

**Comment by wh201906** [comment]
That's strange...
