### ISSUE TITLE
Paste a link

### ISSUE THREAD

**Issue by RomanistHere** [laurent22/joplin#6871]
Joplin version: Joplin 2.2.8 (prod, linux)
Platform: Pop!_OS
Not a MD-based editor

## Steps to reproduce

1. paste a link, starting with "http://" or "https://"
2. pasted like a text (expected: to be a hyperlink at this point - and sometimes it is hyperlink)
3. select the link and use "insert/edit link" tool
4. paste a link and close
5. continue to type
6. everything else that you type adds to hyperlink
7. press right arrow, continue typing as usual
8. delete with Backspace everything to the edge of a link
9. continue to type again - see the 6.

![image](https://user-images.githubusercontent.com/49812531/191275699-df79ab53-b474-4f6a-aaaa-d4d8f82b0977.png)

## Describe what you expected to happen

I expected it:
a) be pasted as a url
b) after I inserted a link, everything else I type should not be considered a link
c) after deleting to the edge of link, new typing should not be considered a link

I'd like to contribute on this issue, seems like an easy place to start, however I need some points in where to find what I'm looking for and... what am I actually looking for?

- is text on "pasting" handled? we can find all the link-alike strings and convert it automatically?
- how are links actually handled, is it markdown beneath of the editor?

**Comment by personalizedrefrigerator** [comment]
We're using [TinyMCE](https://www.tiny.cloud/) for our rich text editor. I'm noticing this issue in their online demo.

Consider reporting this issue with [their issue tracker](https://github.com/tinymce/tinymce/issues?q=is%3Aissue+paste+link+).

**Comment by RomanistHere** [comment]
> We're using [TinyMCE](https://www.tiny.cloud/) for our rich text editor. I'm noticing this issue in their online demo.
> 
> Consider reporting this issue with [their issue tracker](https://github.com/tinymce/tinymce/issues?q=is%3Aissue+paste+link+).

I will. It pastes the link all-right though
