### ISSUE TITLE
Android: Editor goes off screen after screen rotate

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#6872]
**This happens with and without the beta editor enabled.** While more noticeable with the beta editor because of the toolbar, this happens with and without the beta editor enabled. This happens with and without the beta editor enabled.

## Environment

Joplin version: afc34b44c84d18d3c7ff67b135a6f31b844f7037
Platform: Android
OS specifics: Android 12

## Steps to reproduce

1. Create a long note with text that wraps.
2. Observe where the text wraps
3. Rotate the device's screen
4. Observe where the text wraps

## Describe what you expected to happen
The point at which the text wraps should always be the edge of the screen, text should not wrap past the edge of the screen.

## Screenshots
![Screenshot_20220920_142005_Joplin](https://user-images.githubusercontent.com/46334387/191366899-78eac760-a546-4717-8adb-0af6c848ceb8.jpg)
Pressing the toggle sidebar button twice mostly fixes the issue, but the note's titlebar is slightly off-screen:
![Screenshot_20220920_142221_Joplin](https://user-images.githubusercontent.com/46334387/191367234-d36abbf2-8fca-40de-a6cd-35f05c2cd34a.jpg)
When I then rotate the screen back,
![Screenshot_20220920_142403_Joplin](https://user-images.githubusercontent.com/46334387/191367466-5d326e49-077e-4d3b-96d3-7f09bc961f67.jpg)

**Comment by personalizedrefrigerator** [comment]
@Tolu-Mals This seems related to the new sidebar. If you have time to look at this, that would be helpful! If not, I can try to fix it!

**Comment by Tolu-Mals** [comment]
> @Tolu-Mals This seems related to the new sidebar. If you have time to look at this, that would be helpful! If not, I can try to fix it!

I'm already looking into it. I'll try to get a fix as soon as possible.

**Comment by personalizedrefrigerator** [comment]
> > @Tolu-Mals This seems related to the new sidebar. If you have time to look at this, that would be helpful! If not, I can try to fix it!
> 
> I'm already looking into it. I'll try to get a fix as soon as possible.

Thank you!!!

**Comment by Tolu-Mals** [comment]
It's been fixed! Creating a pull request now.

**Comment by personalizedrefrigerator** [comment]
Thank you!
