### ISSUE TITLE
 How to pack the desktop app into a .dmg or .exe file?

### ISSUE THREAD

**Issue by YaronWong** [laurent22/joplin#6874]
This is not a bug
But the help will jump to joplinapp.org
I had to write here

Hi, I'm new to node development and I want to add more features to joplin. Currently I've successfully running npm install and npm start.

Now I want to find a simple way to build the desktop version into an executable file, but I couldn't find any instructions in the doc and readme files.

So, how can I build the desktop version into an executable .dmg or .exe file?

I found the question, but the link to the answer does not open

[Question](https://discourse.joplinapp.org/t/how-to-pack-the-desktop-app-into-a-dmg-or-exe-file/13903)

Hope to get help, thanks again!

**Comment by Daeraxa** [comment]
Your post was trapped by the spam filter (as a new user) but has been approved now.
