### ISSUE TITLE
"Show note counts" makes the text unreadable after hover notebook & tags on linux

### ISSUE THREAD

**Issue by xs539** [laurent22/joplin#6875]
## Environment

Joplin version: 2.9.4
Platform: Linux
OS specifics: Ubuntu 22.04

## Steps to reproduce

1. go to Menu "View"
2. enable "Show note counts"
3. Hover notebooks & tags

With "Show note counts" enabled when you hover a notebook name or tag in the sidepanel, the hover seems to add text over the name.
See the attachted screenshot: the text below is what the notebooks are called, but as seen in the screenshot "Notebook 3" is not visible.

- Notebook 3
- Notebook 1
- Notebook 2

![notebooks](https://user-images.githubusercontent.com/53227774/191469111-52f0f5c4-9273-4fca-8994-e45eeb30818a.png)

**Comment by Daeraxa** [comment]
Are you using any kind of CSS or theme plugin? I can't see this on my own system.

**Comment by xs539** [comment]
No css, no plugins, its a clean install.

Below a visual to make the issue more clear.
It looks like the "first notebook text" is shown elsewhere when hovering over something.
But when the "first notebook text" itself is selected this issues doesn't appear.

[Screencast from 21-09-22 13:16:02.webm](https://user-images.githubusercontent.com/53227774/191494647-7628c0a7-1be7-4837-a729-9131753716c3.webm)

**Comment by xs539** [comment]
Missclicked on close and comment
