### ISSUE TITLE
Plugins icons missing

### ISSUE THREAD

**Issue by AngelicaRibeiro** [laurent22/joplin#6876]
## Environment

Joplin version: joplin-appimage  2.8.8-1 (installed from AUR)

Platform: Linux

OS specifics: 
DISTRIB_ID= ManjaroLinux
DISTRIB_RELEASE= 22.0.0
DISTRIB_CODENAME= Sikaris
DISTRIB_DESCRIPTION= "Manjaro Linux"

## Steps to reproduce

1. Install a plugin, it can be any plugin
2. Restart joplin
3. Create a note and set joplin to the editor mode
4. The icons of the plugins are missing, there is just a gear icon as a placeholder

## Describe what you expected to happen

I've installed some plugins, seven to be precise. I'would expect that  these plugins have icons so that should be easy to use them, but there no icon and just the gear icon,it's counterproductive. I was expecting the plugin icon, not a generic gear icon.
It also would be great the the icons also have shortcuts.

## Logfile
The tool
![image](https://user-images.githubusercontent.com/13433634/191489703-c86f0f96-246c-4d81-99e0-6db22d37bdd2.png)

**Comment by personalizedrefrigerator** [comment]
Does this happen with the markdown editor or just the rich text editor?

**Edit**: I can reproduce this, but only in the rich text editor.

**Comment by personalizedrefrigerator** [comment]
Still an issue.

**Comment by dpoulton-github** [comment]
This can occur when you use the rich-text editor and install a plugin that does not work with the rich text editor.

This picture shows the editor bar for the rich text editor with "cog" icons for the five controls for the *"Menu items, Shortcuts, Toolbar icons"* plugin.

![image](https://user-images.githubusercontent.com/60117449/201199943-793a1ab6-67c0-4724-9ed5-79c36d0175e4.png)

This picture shows the icons displaying when editing in Markdown mode.

![image](https://user-images.githubusercontent.com/60117449/201199989-1a0a915f-7fd5-40d3-ac2a-faf7ad9a0ac6.png)

I guess it would be useful if any toolbar plugins that only work in one editor, only appear in the toolbar for that particular editor.

[Previous forum post](https://discourse.joplinapp.org/t/icons-for-plugins/26088)

**Comment by personalizedrefrigerator** [comment]
Still an issue.

**Comment by personalizedrefrigerator** [comment]
Still an issue in the latest stable release (will check again with beta).

**Comment by personalizedrefrigerator** [comment]
Still an issue.
