### ISSUE TITLE
All notes view doesn't persist after restarting 

### ISSUE THREAD

**Issue by seanieb** [laurent22/joplin#6877]
![Screen Shot 2022-09-22 at 1 55 36 PM](https://user-images.githubusercontent.com/191516/191752675-1ca3891b-7a39-4abb-a829-0fcc0dfe1d17.png)

When viewing note in a notebook, if you restart the app it will reopen in that notebook. If view the "All notes" view prior to re-starting Joplin it doesn't keep the "All notes" view it jumps to the last notebook used.  

## Environment
Joplin version: 2.8.8
Platform: macOS & iOS
OS specifics: Latest

## Steps to reproduce

1.  Open "All notes"
2.  Close and reopen the app
3. The focus will be on the Notebook prior to viewing "All notes" view

## Describe what you expected to happen
- that the state prior to closing the app is preserved.

**Comment by Daeraxa** [comment]
I think this is, at least partially, expected. Joplin still maintains the last selected notebook as its "current" notebook. For example if you click `all notes` then `new note` the new note will be created in the last selected notebook.

As it is driven from the same field (I think) - `settings.activeFolderId` - then you wouldn't be able to blank this on selection of "all notes" as it would allow creation of "orphan" notes that don't have a parent notebook.
