### ISSUE TITLE
[TOC] can't display the katex title normally?

### ISSUE THREAD

**Issue by HeConnor** [laurent22/joplin#6878]
Hello,

![20220923113726](https://user-images.githubusercontent.com/22026546/191888588-1fd13ea3-8ca4-4a1b-91b6-1777fcc163d3.jpg)

the command **[TOC]** seems that the katex title cannot be displayed normally?

## Environment
- Joplin version: 2.8.8 (prod, win32)
- Platform: win7

**Comment by personalizedrefrigerator** [comment]
This is still an issue in 2.11.11.

**Comment by laurent22** [comment]
Hmm, yes this is strange that it strip out the Katex code. But that's most likely an upstream issue that should be asked on the `markdown-it-toc-done-right` repository
