### ISSUE TITLE
Joplin force close when inserting emoji

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#688]
### Operating system

- Android

### Application

- Mobile

This happens when entering a word, eg "maison" then android suggests a home emoji, and as soon as the replacement occurs boom force close

**Comment by laurent22** [comment]
It's not happening on my device. Do you know what keyboard you are using? Also is there any chance you could provide a crash dump as described there? https://joplin.cozic.net/debugging/

I suspect it's some issue with a particular keyboard and a buggy React Native text input, so it might just be fixed on the next RN update.

**Comment by foxmask** [comment]
I use GBoard the keyboard of Google

**Comment by foxmask** [comment]
Fixed. May be by an update of Google itself
