### ISSUE TITLE
Same font in viewer as in editor

### ISSUE THREAD

**Issue by yungpants** [laurent22/joplin#6881]
Hello Guys :)
I am a bit new into the JOPLIN-Game so maybe you can help me out. I wanted to change the font to Joplin, which I partially managed to do. I entered 'Lucida Console' under Tools>Options>Appearance>Editor font family> which adjusted the font in the Note Editor. My main question is: How can I have the same font (font, size, color) in the "note viewer" as in the "note editor"? 

(I've seen people creating customized userstyle.css sheets -> unfortunately I haven't managed to create one myself which changes the font in both views (editor + viewer)).

![image](https://user-images.githubusercontent.com/114239760/191980511-d2dc8efb-eb77-4b38-a463-8921cf1c011f.png)

![image](https://user-images.githubusercontent.com/114239760/191981009-eff361de-5ada-4fc6-906c-cf753a3e04fb.png)

That is currently how it looks like. My goal would be to have the same font, size, color etc. in both views. That if I still want to change something I can adjust this. 

Maybe someone can help me :)

Thanks in advance 

 https://discourse.joplinapp.org/t/change-font/10383

## Environment

Joplin version: [v2.8.8](https://github.com/laurent22/joplin/releases/tag/v2.8.8) - 2022-05-17T14:48:06Z
Platform: WINDOWS (ASUS PC)
OS specifics: Edition Windows 10 Home

 

## Steps to reproduce

1.  Set the settings the default (I did this already but tried again still it just changes the Editor not the Viewer)
2.  If standard family font does not work maybe try and create a userstyle.css custom sheet
3.  Safe the userstyle.css
4. Restart Joplin
5. Look if it works

 I did copy a userstyle.css from the joplin forum -> nothing has changed (yeah maybe you can help me find out what I am doing wrong)

## Describe what you expected to happen

If I manage to have correct userstyle.css and I can launch it correctly than I think it would solve my problem. I just want change the font not more.

## Logfile

 DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/Joplin/resources/app.asar/Dialog.js.map: Unexpected end of JSON input

**Comment by Daeraxa** [comment]
The github issues are only for bugs and enhancements, if you want support on how to use Joplin then please make a new forum topic in the support category.

But basically yes, the font for the editor only changes the editor, if you want to edit the rendered output then you need to change the `userstyle.css` stylesheet.
Make a topic on the forum explaining what you are trying to do and what you have already done.

**Comment by yungpants** [comment]
Oh Thnaks... I will do that :)

**Comment by yungpants** [comment]
Oh Thanks... I will do that :)
