### ISSUE TITLE
Saving Reddit posts with the comments

### ISSUE THREAD

**Issue by FlyingRug** [laurent22/joplin#6883]
I'm not sure if this is really a bug or not. The forum suggested that I post here in this case. I have already asked [this question on Reddit](https://www.reddit.com/r/joplinapp/comments/xm5xdr/how_do_you_save_reddit_posts_with_comments_in/) and was instructed to post here as well. 

The issue is that I have not found a way to get a Reddit page (probably easier job for Jopling to be the old reddit format) with the comments into Jopling. This is considering that the comments tree is expanded manually and visible on the page before clipping. Clipping using "simplified page" works great is done only for the body of the post, and not extended to the comments section. "Complete page (HTML)" method does not work properly, as the texts of the comments are not imported. See the attached screenshot for instance.

![u3j5orhmonp91](https://user-images.githubusercontent.com/114287432/192092894-cecfb92d-4ee1-4a98-af11-fe8a061d4792.png)

## Environment

Joplin version: Joplin 2.8.8 (prod, win32)
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes
Revision: c2a6a13
Platform: Windows 10 and 11
Clipper Version: 2.8.1
OS specifics: 21H2

## Steps to reproduce

1. Open any post with comments with the old reddit layout.
2. Clip the page using the "Simplified page" or "Complete page (Markdown)" or "Complete page (HTML)".
3. The formatting is messy in Joplin or the comments section is entirely missing.

## Describe what you expected to happen

Have a properly formatted text with all visible comments in a similar tree format as on Reddit.

## Logfile

I'm not sure if a log file is necessary.

**Comment by mmarquezs** [comment]
Having same issue here, it makes the web clipping tool completely useless for clipping reddit posts.
