### ISSUE TITLE
smartphone notifications don't work right

### ISSUE THREAD

**Issue by imre84** [laurent22/joplin#6885]
## Environment

Joplin version: 2.8.1 installed from google play
Platform: android
OS specifics: miui 11, android 7.1.1, xiaomi mi max2

## Steps to reproduce

1. create a todo on your smartphone, with an alarm time 30 or so minutes in the future
2. once your todo is created (and possibly synced) close joplin app by pressing the back button as many times as required for the app to be closed
3. wait for the notification alarm to go off
sometimes you don't even get the notification (no (battery) restrictions are applied to joplin)
but when you do:
the notification LED isn't used
the notification sound is quieter than other apps' notification sound

**Comment by magical-heyrovsky** [comment]
Today at 20:00 I've set an alarm to go off at 22:00. I received the notification at 22:35 (so 35 minutes too late). I didn't open the app in between. I wonder if this is an Android thing or if the same problem exist for iOS users. But it probably is some Android battery restriction stuff. (Android 13, Joplin 2.8.1)

**Comment by imre84** [comment]
I specifically disabled all battery optimizations for joplin

**Comment by magical-heyrovsky** [comment]
Yes, you are right. Today I've tested it again without any battery restrictions and the alarm was 18 minutes too late.

**Comment by imre84** [comment]
now I made todos to go off hourly, and I get notified about the wrong todos. Sometimes several hours early. And there are todos which are now past the deadline, and I haven't been notified about (todos were made at least 40 minutes early, all synced, no battery restrictions, phone wasn't switched off)

**Comment by imre84** [comment]
now I rebooted my smartphone and now it sent notifications about some (but not all) todos that have been missed so far

**Comment by magical-heyrovsky** [comment]
The problem remains, issue should stay open.

**Comment by ruzoka** [comment]
Same issue here, notifications feel for me almost random, and rarely occur on the time I have set the alarm for unfortunately.
If I set the alarm of an todo is the android app it works better. 
Would it be possible to list upcoming notifications of joplin somewhere, so it is easier to see if the notifications are right?
I have seen a post from someone, unfortunately I cannot remember were, that stopped using alarms and still go notifications from ols alarms, if I remeber correctly, it feels that this is happening for me as wel and therefor the notifications when using an alarm on several todos just seem random.

**Comment by ruzoka** [comment]
I have found a list for upcoming alarms und configuration -> sync status -> upcoming alarms
here all the alarms are synced correctly. However I still get notifications for old alarms randomly which is rather frustrating. Does not seem to be a problem that joplin has the wrong alarms synced, but that the alarms are not forwarded correctly to android, or do not get updated when the alarm date is changed.
somebody has an idea how to fix this, are there plans for the issue? 
Kind regards

**Comment by magical-heyrovsky** [comment]
> The problem remains, issue should stay open.

**Comment by magical-heyrovsky** [comment]
> > The problem remains, issue should stay open.

(I will test it tomorrow again but I assume the problem remains)
