### ISSUE TITLE
On iOS 16, UI disappears after editing a note or trying to sign into OneDrive

### ISSUE THREAD

**Issue by Cralex** [laurent22/joplin#6887]
## Environment

Joplin version: 12.8.1
Platform: iOS 
OS specifics: iOS 16.0 and up, iPhone SE (2020)

## Steps to reproduce

While editing:
1. Create a new note or begin editing a note. (It seems to only happen when the keyboard actually appears.)
2. Close the note to return to reading view.
3. The whole UI retracts up and cannot be accessed except for the new note button.

[Video Link](https://www.dropbox.com/s/9hyjyinc2qf9t8i/Video%20Sep%2025%202022%2C%2011%2016%2028%20AM.mov?dl=%5D(https://www.dropbox.com/s/9hyjyinc2qf9t8i/Video%20Sep%2025%202022%2C%2011%2016%2028%20AM.mov?dl=1) 

While logging into OneNote:
1. Set OneNote as the sync target.
2. Press the sync button.
3. Type in your OneNote email address and press Next
4. The whole UI retracts up and cannot be accessed

[Video Link](https://www.dropbox.com/s/62inbm09pqswbdi/Video%20Sep%2025%202022%2C%2011%2014%2047%20AM.mov?dl=%5D(https://www.dropbox.com/s/62inbm09pqswbdi/Video%20Sep%2025%202022%2C%2011%2014%2047%20AM.mov?dl=1) 

## Describe what you expected to happen

Before updating to iOS 16, my existing Joplin install functioned normally, where I could open another note after editing one note. I expected this to continue after installing the public release of iOS 16, but now I have to kill the app in order to access the UI again.

I tried reinstalling the app to see if it would fix it, but the same issue prevented me from signing into OneDrive in the first place.

**Comment by personalizedrefrigerator** [comment]
I'm also using iOS 16 (iPhone) and can edit notes (I'm using the beta editor) without experiencing this issue.

Note: This might be a duplicate of https://github.com/laurent22/joplin/issues/6859.

**Comment by Cralex** [comment]
Confirmed! Turning off one of the settings mentioned in that issue seems to fix my problem.

**Comment by giteshwar** [comment]
I have been experiencing a similar problem on my iPad.

I set the Sync target as OneDrive and Save.

When I click synchronize, I get the authentication page of OneDrive (Microsoft account). Once I enter email and submit, I get a screen which is blank. It appears the section with fields and buttons to submit are hidden. When I rotate the screen, it appears fleetingly. I have tried tapping all over the screen to enable the keyboard but it never shows up.

<img width="768" alt="joplin-2022-10-01-102008" src="https://user-images.githubusercontent.com/10822466/193393266-4953a894-37a3-441c-aeba-816906b4d0c4.png">

**Comment by personalizedrefrigerator** [comment]
> I have been experiencing a similar problem on my iPad.
> 
> I set the Sync target as OneDrive and Save.
> 
> When I click synchronize, I get the authentication page of OneDrive (Microsoft account). Once I enter email and submit, I get a screen which is blank. It appears the section with fields and buttons to submit are hidden. When I rotate the screen, it appears fleetingly. I have tried tapping all over the screen to enable the keyboard but it never shows up.
> 
> <img alt="joplin-2022-10-01-102008" width="768" src="https://user-images.githubusercontent.com/10822466/193393266-4953a894-37a3-441c-aeba-816906b4d0c4.png">

Are you using the floating keyboard?

**Comment by giteshwar** [comment]
> > I have been experiencing a similar problem on my iPad.
> > I set the Sync target as OneDrive and Save.
> > When I click synchronize, I get the authentication page of OneDrive (Microsoft account). Once I enter email and submit, I get a screen which is blank. It appears the section with fields and buttons to submit are hidden. When I rotate the screen, it appears fleetingly. I have tried tapping all over the screen to enable the keyboard but it never shows up.
> > <img alt="joplin-2022-10-01-102008" width="768" src="https://user-images.githubusercontent.com/10822466/193393266-4953a894-37a3-441c-aeba-816906b4d0c4.png">
> 
> Are you using the floating keyboard?

Yes, I am using floating keyboard. Taking your cue, I switched to the fixed keyboard and could complete my sync with OneDrive. I recall having similar issue with editing notes as well and I had to close the app and start again to continue editing. I maybe there is an issue with floating keyboard. I will continue using and report if I encounter the issue.

**Comment by serranomorante** [comment]
Nice! Changing from floating keyboard to fixed can be used as a workaround for now.

**Comment by giteshwar** [comment]
Issue is open. Unable to use floating keyboard

**Comment by Cralex** [comment]
This continues to be a problem on Joplin 12.9.1 on iOS 16.2. If the accessibility option “Prefer Cross-Fade transitions” is enabled, any note will collapse into an unreadably tiny space after being edited. While simply turning off this setting is an effective workaround, ideally Joplin should be compatible with the setting eventually.
