### ISSUE TITLE
Encryption not ready , How to do it?

### ISSUE THREAD

**Issue by UNIONDONG** [laurent22/joplin#6889]
when I update files, it happended error!

Joplin version: 2.8.8
Platform: windows

![image](https://user-images.githubusercontent.com/35584433/192658805-fa00c5d6-996d-45a1-9b4e-4d7d24f3e17b.png)

**Comment by Daeraxa** [comment]
You have a topic open on the forum about this now - https://discourse.joplinapp.org/t/encryption-not-ready-how-to-do-it/27571 - which is the correct place for it.
