### ISSUE TITLE
Synchronization lags with error in flatpak version

### ISSUE THREAD

**Issue by robertoswald** [laurent22/joplin#6891]
## Issue

When using flatpak version synchronisation is laggy and test results in error:

```
Error. Please check that URL, username, password, etc. are correct and that the sync target is accessible. The reported error was:
request to https://<my webdav url> failed, reason: getaddrinfo ENOTFOUND <my webdav url> (Code ENOTFOUND)
```

## Environment

Joplin version: 2.8.8 (flatpak)
Platform: Linux
OS specifics: Ubuntu 22.04 (Wayland & X11)

## Steps to reproduce

1. launch joplin flatpak version
2. Tool -> Options -> Synchronization -> Check Synchronization Configuration

## Describe what you expected to happen

Test result:  
Success! Synchronization configuration appears to be correct.  

As it is when using Joplin 2.8.8 appimage.

**Comment by Daeraxa** [comment]
If it is specific to the flatpak version then it needs to be brought up with the maintainers of it. The only official distribution for linux is the appimage.
See: https://discourse.joplinapp.org/t/unofficial-alternative-joplin-distributions/23703

**Comment by robertoswald** [comment]
@Daeraxa Thanks, then I stay with the appimage.
