### ISSUE TITLE
appimage offers no app menu entry

### ISSUE THREAD

**Issue by robertoswald** [laurent22/joplin#6892]
## Issue

 Joplin appimage creates no desktop integration like app menu entry.

## Environment

Joplin version: 2.8.8
Platform: Linux
OS specifics: Ubuntu 22.04 (Gnome)

## Steps to reproduce

1. launch appimage
2. close appimage
3. no app menu entry is created

## Describe what you expected to happen

An app menu entry is created, so that is possible to add joplin to dock.  
This works with different appimages.

**Comment by wh201906** [comment]
There is a installation script mentioned in README.md.
https://github.com/laurent22/joplin#desktop-applications
> On Linux, the recommended way is to use the following installation script as it will handle the desktop icon too:

**Comment by mmahmoudian** [comment]
@robertoswald AppImage is not suppose to make the .desktop file for you. That is a beauty of it. You can have different versions of the same software in a folder side-by-side , and therefore if such feature is implemented, it would overwrite the .desktop file every time you open one of those versions.

To create the .desk6top file, either run the shell script as mentioned in the README (the link @wh201906 provided), or manually create a file based on:

https://github.com/laurent22/joplin/blob/afc34b44c84d18d3c7ff67b135a6f31b844f7037/Joplin_install_and_update.sh#L210-L224

Note that if you are creating the file manually, you don't necessarily need to have `${SANDBOXPARAM}` and you can remove it. or if you want it to be sandboxed, check if you can meet the criteria:

https://github.com/laurent22/joplin/blob/afc34b44c84d18d3c7ff67b135a6f31b844f7037/Joplin_install_and_update.sh#L177-L192

**Comment by robertoswald** [comment]
Thanks a lot for your hints. I am going to use the install script.
