### ISSUE TITLE
Edit mode is out of sync with preview mode. Every time you modify the content in editing....

### ISSUE THREAD

**Issue by zhouxinghong** [laurent22/joplin#6893]
Edit mode is out of sync with preview mode. Switching to preview mode after modifying content in Edit will preview from the very beginning of the document. Expected result: switch to preview mode after editing the content, you should see the modified content instead of previewing from the beginning of the document. This problem makes this software very difficult to use. . .
OS Windows 10
Version 2.9.4
[Video_2022-09-29_edit.zip](https://github.com/laurent22/joplin/files/9670845/Video_2022-09-29_edit.zip)

**Comment by Daeraxa** [comment]
Closing to stop whatever pattern is going on here...
