### ISSUE TITLE
Edit mode conflicts with outline view. Every time the outline view document is activated from the editor....

### ISSUE THREAD

**Issue by zhouxinghong** [laurent22/joplin#6894]
Edit mode conflicts with outline view. Every time the outline view is activated from the editor, the position of the editor document returns to the very beginning of the document. The expected result is that the position where the outline view document is activated from the editor should not go back to the very beginning of the document, but should stay where the document content was edited. This problem makes this software very difficult to use. . .
Operating System Windows 10
Version: 2.9.4
[Video_2022-09-29_11.zip](https://github.com/laurent22/joplin/files/9670830/Video_2022-09-29_11.zip)

**Comment by Daeraxa** [comment]
Closing to stop whatever pattern is going on here...
