### ISSUE TITLE
Mobile: app crashes when moving notes between notebooks

### ISSUE THREAD

**Issue by wh201906** [laurent22/joplin#6898]
## Environment

Joplin version: v2.9.2
Platform: Android
OS specifics: Android 11

## Steps to reproduce

1. Long-press the note item in a notebook
2. Click `Move to notebook...`
3. The app crashes

## Describe what you expected to happen
The app should not crash.

## Logfile

None. No errors or related information are logged because the app just crashes immediately.

<details><summary>Here are some debug information</summary>

![IMG_20220930_182232](https://user-images.githubusercontent.com/62299611/193250442-3e6645f6-41c0-46e0-b511-9e7920d58f6a.jpg)
![IMG_20220930_182152](https://user-images.githubusercontent.com/62299611/193250423-3d449523-f277-4a61-a05c-e248ad6ae0ff.jpg)
![IMG_20220930_182207](https://user-images.githubusercontent.com/62299611/193250437-a4805475-1052-4d5c-b396-eb2eb463e67c.jpg)

</details>

**Comment by wh201906** [comment]
If there are some conflicts on mobile, it's hard to resolve them because you cannot just select the needed then move them due to this bug. You can only copy and paste the content of each needed note one by one. So I think this issue deserves a `high` tag.
I think it's easy to reproduce this bug.

**Comment by laurent22** [comment]
@personalizedrefrigerator, that was due to your change [here](https://github.com/laurent22/joplin/commit/92c24c2129407f36f04c979c16665c9352767927#diff-5007edf0cc6e7b53c729e5cd7c4aa296e49341f5631a2175eb2b659bb53cd91fR125) It happens, but take away is to change as little as possible when making the JS to TS conversion because we often miss subtle bugs like this. And of course also to check all the screens where the dropdown is used as doing so would have caught this particular crash.

**Comment by wh201906** [comment]
@laurent22 Thanks for your fix

**Comment by personalizedrefrigerator** [comment]
> @personalizedrefrigerator, that was due to your change [here](https://github.com/laurent22/joplin/commit/92c24c2129407f36f04c979c16665c9352767927#diff-5007edf0cc6e7b53c729e5cd7c4aa296e49341f5631a2175eb2b659bb53cd91fR125) It happens, but take away is to change as little as possible when making the JS to TS conversion because we often miss subtle bugs like this. And of course also to check all the screens where the dropdown is used as doing so would have caught this particular crash.

Thank you for fixing this!!!
In the future, I'll try to write automated tests for files I migrate to TypeScript, or at least ensure that the relevant pull request's testing plan includes testing more aspects of the migrated component.
