### ISSUE TITLE
More portable synced note files

### ISSUE THREAD

**Issue by monotasker** [laurent22/joplin#69]
### Operating system

- [X] Windows
- [X] macOS
- [X] Linux
- [X] Android
- [X] iOS

### Application

- [X] Desktop
- [X] Mobile
- [X] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---
I would like to be able to do things like (a) dropping markdown files produced elsewhere into the OneDrive folder, and (b) opening notes in the OneDrive folder with another program that handles markdown files. These kinds of tasks are awkward right now because

- the note filenames are not readable
- the note metadata is embedded in the note file

Would it be possible to make the synced note files more portable markdown files? To my mind that would involve (a) giving the files readable names (derived from the note title), and (b) storing the note metadata outside the note files themselves.

I suppose the metadata issue is easier to work around, although it makes for ugly files if I decide to take them elsewhere in the future. The bigger, more immediate problem is really the unreadable file names.

**Comment by Doideira** [comment]
+1

**Comment by laurent22** [comment]
Unfortunately that would be out of scope as the files on the sync target aren't really meant to be edited directly. Using the title as the filename would also not be possible for performance reasons.

Drag and dropping files directly on the app might be supported later on.
