### ISSUE TITLE
Bug in Search Bar

### ISSUE THREAD

**Issue by YashBhole29** [laurent22/joplin#6900]
## Issue in Search Bar

Joplin version: 2.8.1
Platform:  Android
OS specifics: Android Version 12

We can't search the note unless the entire title is entered.
All notes with matching search should show up.
For eg. If I have a note with title "Hello" it should appear when "H" is typed in the search bar, which is not the case.
It only appears when the entire word "Hello" is typed. This reduces functionality of the search bar.

## I have two notes with Title "Hello", "Hey" respectively.

<img src="https://user-images.githubusercontent.com/105486311/193304921-426853b9-a11f-4b7c-acf0-8a0ab2f2d2c4.jpg" width=200>

## Search doesn't show any results when "He" is searched.

<img src="https://user-images.githubusercontent.com/105486311/193304957-a9a2b1c0-39ba-42e6-9256-cb79bf5ff0c2.jpg" width=200>

**Comment by Daeraxa** [comment]
Please see the [searching](https://joplinapp.org/help/#searching) documentation. It works on full text search so this is expected behaviour. If you want to search partials you need to revert to basic search by using `/`. So `/he` should return what you expect.
