### ISSUE TITLE
[Bug] Terminal output is truncated in shell pipes

### ISSUE THREAD

**Issue by gera2ld** [laurent22/joplin#6902]
## Environment

Joplin version: Terminal 2.8.1
Platform: macOS
OS specifics: macOS 12.6

## Steps to reproduce

I have 729 small notes in my profile, so the json output is larger than 64K. The terminal works well when not using pipes.

```bash
$ joplin ls -f json
> works as expected

$ joplin ls -f json > file.json
> works as expected
```

When piping output larger than 64K, I got a truncated and invalid JSON string.

```bash
$ joplin ls -f json | jq
> parse error: Unfinished string at EOF at line 1, column 65536

$ joplin ls -f json | cat
> shows the truncated json, see the image below

$ joplin ls -f json | wc
>       0      85   65536
# always 65536 when the content size is obviously larger than 65536.
```

![image](https://user-images.githubusercontent.com/3139113/193398239-61301cfd-d814-4d0b-8ec2-0053874013bf.png)

The root cause is that you are using `console.info` to write the output but don't wait for the data to be flushed and exit explicitly and immediately.

https://github.com/laurent22/joplin/blob/50baad3c0456b9a8ac20b3ad3386010996cc7a5d/packages/app-cli/app/app.js#L280-L282

https://github.com/laurent22/joplin/blob/50baad3c0456b9a8ac20b3ad3386010996cc7a5d/packages/app-cli/app/app.js#L449-L451

## Describe what you expected to happen

Piping should work with complete data.

After adding a 1-second delay before exit as a workaround, I got the expected output:

```bash
$ joplin ls -f json | wc
>       1     359  261936
```

**Comment by wh201906** [comment]
Would you like to make a PR to fix it? Seems like you have figured out the reason of this issue.

**Comment by wh201906** [comment]
By the way, I think the 65536 is exactly the pipe capacity.
See `Pipe capacity` in [this page](https://man7.org/linux/man-pages/man7/pipe.7.html)

**Comment by wh201906** [comment]
@gera2ld Maybe you can add `fs.fsyncSync(1)` before `process.exit(0)`?

**Comment by gera2ld** [comment]
> I think the 65536 is exactly the pipe capacity

Yeah that's why we only need to flush data when the size of output is larger than 64K.

I tried `fs.fsyncSync(1)` but it didn't work.

According to the doc:

> The return value (of `Writable.write`) is true if the internal buffer is less than the highWaterMark configured when the stream was created after admitting chunk. If false is returned, further attempts to write data to the stream should stop until the ['drain'](https://devdocs.io/node/stream#event-drain) event is emitted.

Looks like the correct way is to switch `console.info` to a Promise to wait until writing is done. But that's a lot of effort I guess.

Maybe I can just switch `console.info` to a synchronous `process.stdout.write` and use an additional variable to make sure the `drain` event is fired before exit. The limit is we cannot trigger `drain` multiple times which seems to be the case in this project. Is that OK for you?

**Comment by wh201906** [comment]
@gera2ld I made some changes on `app.js`. It gives me the full output, but I'm not sure if these code will introduce new bugs.
```
gitpod /workspace/gitpod-workspace/joplin-output/packages/app-cli (cli-output) $ node build/main.js ls -f json | wc
      0       1   75915
```
https://github.com/laurent22/joplin/compare/dev...wh201906:afc66c25ad8535d5063fff66c23fadd3a735fcf1?expand=1

**Comment by wh201906** [comment]
Plus, if the timeout is necessary, why don't we just remove this
https://github.com/laurent22/joplin/blob/50baad3c0456b9a8ac20b3ad3386010996cc7a5d/packages/app-cli/app/app.js#L449-L451
This was firstly introduced in 214eae27da95e0edcdbb3a28cc1dcaff225446d5
