### ISSUE TITLE
Addition to the list of supported services for file storage

### ISSUE THREAD

**Issue by benmcollins** [laurent22/joplin#6905]
## Environment

Joplin version: N/A
Platform: N/A
OS specifics: N/A

## Describe what you expected to happen

In `README.md`, there is a list of services that Joplin can use to store data. One of them is WebDAV. I would like to ask that [SwissDisk](https://www.swissdisk.com) be added to this list. It is a free WebDAV service built on Open Source software (Linux Encrypted Filesystems, and Apache+WebDAV).

It also has zero tracking and a strict privacy policy to make it a safer choice than oneDrive, Dropbox, et al.

Full disclosure, I own SwissDisk.

**Comment by benmcollins** [comment]
I should also point out that a good number of SwissDisk's current customers are Joplin users.

**Comment by da2x** [comment]
The SwissDisk website says it supports the WebDAV protocol. Joplin already supports syncing to WebDAV.

**Comment by benmcollins** [comment]
@da2x My report was to have SwissDisk listed as an actual service that provides WebDAV in Joplin's README.md.

Most users wouldn't know how to search for a "WebDAV Service" with any confidence. As SwissDisk is built on open source software and provides a more secure and private alternative to the big-name commercial vendors that are already listed there, I would consider the alternative option beneficial to Joplin users.

**Comment by ScriptInfra** [comment]
> @da2x My report was to have SwissDisk listed as an actual service that provides WebDAV in Joplin's README.md.
> 
> 
> 
> Most users wouldn't know how to search for a "WebDAV Service" with any confidence. As SwissDisk is built on open source software and provides a more secure and private alternative to the big-name commercial vendors that are already listed there, I would consider the alternative option beneficial to Joplin users.

You could always submit a pull request to the page with the update you'd like and see what happens.

**Comment by benmcollins** [comment]
> You could always submit a pull request to the page with the update you'd like and see what happens.

Fair enough.
