### ISSUE TITLE
Android editor does not render with monospace font

### ISSUE THREAD

**Issue by sjeon87** [laurent22/joplin#6906]
## Environment

Joplin version: 2.8.1
Platform: Android 12
OS specifics: Samsung Galaxy Note 10+ 5G

## Steps to reproduce

1. Install and launch Joplin
2. Configure Joplin to use monospaced font and save configuration (not beta editor)
3. Create any note and try to edit note body
4. See font is non-monospaced

## Describe what you expected to happen

Editor font is monospaced

**Comment by manofprimes** [comment]
Hello, any update on this?

**Comment by sjeon87** [comment]
Hello, any update on this...?
