### ISSUE TITLE
Description Onedrive synchronization failed

### ISSUE THREAD

**Issue by xxdccLove** [laurent22/joplin#6914]
Sorry, Onedrive synchronization error

Display "已完成: 2022/10/04 20:38（130ms）
最后的错误: Error: Not a valid URL: https://graph.microsoft.com/v1.0/drives/b!yuMsVofocE-VWIjz8oQKd99STQXlwDhEn68w3FFJVrmecE9IBICIR7Utzu3k6H5x/root:/应用/Joplin/info.json:/content":
![image](https://user-images.githubusercontent.com/63762023/193822553-c14c6432-cf5e-4a75-b8f5-1594e8fe07fa.png)

## Environment

Joplin version: Joplin 2.8.8 (prod, win32)
Platform: Windows
OS specifics: 22H2 22621.521

## Steps to reproduce

![image](https://user-images.githubusercontent.com/63762023/193822499-eb29762a-2e28-463e-9dc5-bdaaa995d2b8.png)

## Describe what you expected to happen
Synchronization failure

## Logfile
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Logger.js:190 20:49:16: OneDriveApi: Got unhandled error: undefined Not a valid URL: https://graph.microsoft.com/v1.0/drives/b!yuMsVofocE-VWIjz8oQKd99STQXlwDhEn68w3FFJVrmecE9IBICIR7Utzu3k6H5x/root:/应用/Joplin/info.json:/content Error: Not a valid URL: https://graph.microsoft.com/v1.0/drives/b!yuMsVofocE-VWIjz8oQKd99STQXlwDhEn68w3FFJVrmecE9IBICIR7Utzu3k6H5x/root:/应用/Joplin/info.json:/content
    at Object.shim.fetch (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\shim-init-node.js:425)
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:279)
    at Generator.next (<anonymous>)
    at C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:8
    at new Promise (<anonymous>)
    at __awaiter (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:4)
    at OneDriveApi.exec (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:228)
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:397)
    at Generator.next (<anonymous>)
    at C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:8
log @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Logger.js:190
error @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Logger.js:64
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:292
rejected @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:6
processTicksAndRejections @ internal/process/task_queues.js:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:7
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:4
exec @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:228
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:397
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:4
execText @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:396
get @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-onedrive.js:114
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api.js:282
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api.js:51
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api.js:4
tryAndRepeat @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api.js:41
get @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api.js:282
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\synchronizer\syncInfoUtils.js:55
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\synchronizer\syncInfoUtils.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\synchronizer\syncInfoUtils.js:4
fetchSyncInfo @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\synchronizer\syncInfoUtils.js:54
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:412
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ internal/process/task_queues.js:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ internal/process/task_queues.js:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ internal/process/task_queues.js:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ internal/process/task_queues.js:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:4
start @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:352
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:121
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:5
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:5
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:7
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:4
timeoutCallback @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:77
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:146
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:4
Registry.scheduleSync @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:57
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:66
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:5
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:5
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:7
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:4
execute @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:26
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:158
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:4
execute @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:149
onClick @ C:\Program Files\Joplin\resources\app.asar\gui\Sidebar\Sidebar.js:490
onClick @ C:\Program Files\Joplin\resources\app.asar\gui\Button\Button.js:205
callCallback @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:347
invokeGuardedCallbackDev @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:397
invokeGuardedCallback @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:454
invokeGuardedCallbackAndCatchFirstError @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:468
executeDispatch @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:600
executeDispatchesInOrder @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:622
executeDispatchesAndRelease @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:725
executeDispatchesAndReleaseTopLevel @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:733
forEachAccumulated @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:707
runEventsInBatch @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:750
runExtractedPluginEventsInBatch @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:881
handleTopLevel @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:5901
batchedEventUpdates @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:2344
dispatchEventForPluginEventSystem @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:5996
dispatchEvent @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:6025
unstable_runWithPriority @ C:\Program Files\Joplin\resources\app.asar\node_modules\scheduler\cjs\scheduler.development.js:643
runWithPriority$2 @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11305
discreteUpdates$1 @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:21672
discreteUpdates @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:2359
dispatchDiscreteEvent @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:5979
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Logger.js:190 20:49:16: Synchronizer: Error: Not a valid URL: https://graph.microsoft.com/v1.0/drives/b!yuMsVofocE-VWIjz8oQKd99STQXlwDhEn68w3FFJVrmecE9IBICIR7Utzu3k6H5x/root:/应用/Joplin/info.json:/content
    at Object.shim.fetch (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\shim-init-node.js:425)
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:279)
    at Generator.next (<anonymous>)
    at C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:8
    at new Promise (<anonymous>)
    at __awaiter (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:4)
    at OneDriveApi.exec (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:228)
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:397)
    at Generator.next (<anonymous>)
    at C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:8
20:49:16: Synchronizer: Error: Not a valid URL: https://graph.microsoft.com/v1.0/drives/b!yuMsVofocE-VWIjz8oQKd99STQXlwDhEn68w3FFJVrmecE9IBICIR7Utzu3k6H5x/root:/应用/Joplin/info.json:/content
    at Object.shim.fetch (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\shim-init-node.js:425)
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:279)
    at Generator.next (<anonymous>)
    at C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:8
    at new Promise (<anonymous>)
    at __awaiter (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:4)
    at OneDriveApi.exec (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:228)
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:397)
    at Generator.next (<anonymous>)
    at C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:8

[log.txt](https://github.com/laurent22/joplin/files/9707001/log.txt)

**Comment by wh201906** [comment]
This is the same bug as #6838. The url contains "应用", which is not support now.
