### ISSUE TITLE
iOS: Regression: Mermaid.js not loading

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#6926]
## Environment

Joplin version: cea1aeac4b0af498290e2bc8ca3030a6f6eb17c7
Platform: iOS simulator 15.5
Works as expected on Android.

## Steps to reproduce

1. Create a Mermaid chart
2. Open the note viewer
3. Open Safari's inspector for the note viewer
4. Observe an error message about mermaid.min.js not being loadable.

## Describe what you expected to happen

Should load mermaid.min.js

## Logfile
Not currently available --- I don't presently have access to the iOS simulator.

Note that this is still an issue if the `NoteViewer` and `useSource` are reverted to not use the `ExtendedWebView`.

~~**Note**: It's possible this is an issue caused by resources not being minified locally during build (e.g. perhaps I last ran `yarn build` before I `git reset --hard upstream/dev`). I will edit this when I have access to a Mac (and thus can do further testing).~~

**Comment by laurent22** [comment]
Could you provide the full error message please?

**Comment by personalizedrefrigerator** [comment]
> Could you provide the full error message please?

Perhaps in a few hours (no development machine access at present). Please note that KaTeX works as expected (which also loads a resource linked from the HTML file).

The message is **similar** to the following:
```
Unable to load resource at file:///null/Users/Dev/...snipped.../pluginAssets/mermaid.min.js
```

**Comment by personalizedrefrigerator** [comment]
Log:
```
file://null/Users/Builder/Library/Developer/CoreSimulator/Devices/E126A393-DC99-4FDA-ADD0-640E649A118B/data/Containers/Data/Application/C9CCE142-A8C1-459A-8158-FEAE15AC66E4/Documents/pluginAssets/mermaid/mermaid.min.js.map
[Error] Failed to load resource: The requested URL was not found on this server. (mermaid.min.js.map, line 0)
```

The network tab suggests that `mermaid.min.js` is loading correctly and that Safari/WkWebView is also expecting a `mermaid.min.js.map`...
<img width="772" alt="" src="https://user-images.githubusercontent.com/46334387/194721221-efdd2fb6-468c-4892-9ca4-6ebc9e33b115.png">
(I can click on `mermaid.min.js` and see its contents).

**Comment by laurent22** [comment]
Is the mermaid diagram rendering fine? Because as long as it works it's ok if there's a warning

**Comment by personalizedrefrigerator** [comment]
It looks like that isn't the issue at all --- running the following in the developer console,
```
> mermaidInit()
< undefined
> mermaid.init
< function (){try{lu.apply(void 0,arguments)}catch(t){o.warn("Syntax Error rendering"),o.warn(t.str)}}
> mermaidReady()
< true
> mermaidInit()
< undefined
// Copy-pasting the post-initialization code from mermaidInit():
> const elements = document.getElementsByClassName('mermaid');
for (const element of elements) {
	element.style.width = '100%';
}
< undefined
> elements
< HTMLCollection [] (0)
```

It's not rendering and no elements have a `mermaid` class.

The element that should render has this as its source (and is currently being rendered by hljs, instead of mermaid):
```
<pre class="joplin-source" data-joplin-language="mermid" data-joplin-source-open="```mermid
" data-joplin-source-close="
```">graph TD;
    A--&gt;B;
    A--&gt;C;
    B--&gt;D;
    C--&gt;D;</pre>
```

**Comment by personalizedrefrigerator** [comment]
This was caused by a typo! Sorry!!!

I had typed `mermid` instead of `mermaid` (I thought I had copy-pasted the source from an existing Joplin note --- apparently, I hadn't).
