### ISSUE TITLE
Can't create notes from the terminal with spaces

### ISSUE THREAD

**Issue by jlvcm** [laurent22/joplin#6930]
## Environment

Joplin version: 2.8.8
Platform: Linux
OS specifics: Arch

## Steps to reproduce

1. Open a shell, any shell should work (bash/zsh/fish)
2. Try to create a note or todo with a space
3. 
```bash
> joplin mktodo "first second third"
> joplin ls
[ ] first
```
## Describe what you expected to happen
I've tried a bunch of different ways to create a note but i was not able to using the terminal, on the joplin-cli works fine, if i do
```
:mktodo "first second third"
```
It gets created correctly as "first second third"

**Comment by rokaicker** [comment]
@laurent22 Would it be alright if I looked into this? I'm a bit of a novice contributor, but I can see that it's working in v2.8.1 (on Ubuntu), so I can try to figure out what changed between 2.8.8 and 2.8.1 to fix it.

**Comment by rokaicker** [comment]
Actually, I tried recreating this issue from the dev branch, but I couldn't recreate it.

(Although I'm not entirely sure if this is the write way to test the cli tool).

![image](https://user-images.githubusercontent.com/97995977/194791672-13403a43-e6a1-47ef-9ba8-b02bc5669c9b.png)

**Comment by jlvcm** [comment]
you'r right

- i've tried dev and it worked fine
- i've tried the branch for version 2.8.8 and it worked fine
- i've tried the 2.8.8 build and it worked fine
- I've even tried my joplin install directly and it worked fine

i think the issue is with the running script from AUR, so probably joplin is fine

https://aur.archlinux.org/cgit/aur.git/tree/joplin.sh?h=joplin
i believe the issue is here `${@}`, it should be `node main.js "${@}" ` , after this change it works fine. 

thanks for the help!
