### ISSUE TITLE
Symlink to profile directory location does not work

### ISSUE THREAD

**Issue by zudanievil** [laurent22/joplin#6931]
## Environment

Joplin version: 2.8.8 (prod, linux)
(joplin was installed via flathub)
Platform: Linux
OS specifics: Fedora 35

## Steps to reproduce

1. move joplin "profile directory" to a new location (`mv -T ~/.config/joplin-desktop ~/some_place`)
2. put symlink to the new location at the old location (`ln -sT ~/some_place ~/.config/joplin-desktop`)
3. start joplin 
4. produces gui error message:
```
fatal error
EEXIST: file already exists, mkdir '<home>/.config/joplin-desktop' 
<...>
```
Apparently, joplin cannot resolve symlinks to "profile directory", which is an unexpected behavior for linux applications.

## Describe what you expected to happen
After steps 1-2 joplin should start without any visible changes.

**Comment by Daeraxa** [comment]
Does this happen with the appimage version? Wondering if this is just a side effect of the flatpak sandboxing? If so then it should be reported to the flatpak maintainers.

**Comment by roman-r-m** [comment]
Works ok for me when running from source (`yarn start`)

**Comment by kubuntu-newbie** [comment]
Same problem with Joplin for Desktop 2.8.8 (prod, linux) installed via snap on Kubuntu 22.04.1

creating a symbolic link for joplin-desktop to point to a different location, joplin-desktop fails with

Fatal error;

Error: EACCES: permission denied, scandir '/home/.../snap/joplin-desktop/28/.config/joplin-desktop'
   at FsDriverNode.fsErrorToJsError_(/snap/joplin-desktop/27/opt/joplin-desktop/resources/app/node_modules/@joplin/lib/fs-driver-node.js:22:25)

etc

**Comment by Daeraxa** [comment]
As I mentioned in my other comment, does this happen with the appimage? Snap also features sandboxing like flatpak so may be a side effect of that and should be reported to the snap maintainer.
