### ISSUE TITLE
The software could not be opened

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#6933]
## Environment

Joplin version: 2.9.2 portable
Platform: windows
OS specifics: windows11

## Describe what you expected to happen

An error occurred while opening

![图片](https://user-images.githubusercontent.com/112467275/194847031-95b9650d-442c-4894-9e8e-04114f4979d0.png)

# Logfile
[log.txt](https://github.com/laurent22/joplin/files/9745222/log.txt)

**Comment by laurent22** [comment]
Anything in the console? joplinapp.org/debugging

**Comment by ghost** [comment]
> Anything in the console? joplinapp.org/debugging

Is that what you're talking about? I'm not a developer. I don't understand. I use a portable application.
If I'm doing it wrong, you can coach me if you want.

![图片](https://user-images.githubusercontent.com/112467275/194891324-d8048d6c-f3bb-40e9-bef0-86ffc93a1e5b.png)
![图片](https://user-images.githubusercontent.com/112467275/194891357-f80a0478-447e-4ee3-a1d8-c1bf64a482f0.png)
![图片](https://user-images.githubusercontent.com/112467275/194891379-74963158-5ee1-440d-b25b-8ef0449168af.png)
![图片](https://user-images.githubusercontent.com/112467275/194891391-cd5d608c-f2a7-4bbf-9975-5f76acd013bd.png)

**Comment by laurent22** [comment]
Yes I think we'd need the whole content of this console

**Comment by wh201906** [comment]
You can follow the steps on this site to get the log.txt and post it there.
https://joplinapp.org/debugging/
你可以按照这个网页上的步骤获取更多的日志信息，然后发到这里
