### ISSUE TITLE
Invalid origin: http://127.0.0.1:22300

### ISSUE THREAD

**Issue by ErDongChen1973** [laurent22/joplin#6946]
When i install joplin server on docker,and access it via http://127.0.0.1:22300, i get "Invalid origin: http://127.0.0.1:22300". Could someone tell me what should i do?

**Comment by woodboy12** [comment]
Are you trying to access it locally or through your domain?

**Comment by SnejPro** [comment]
For those how have the same issue:
You have to set the APP_NAME in the Host-header:
```
#Nginx config
proxy_set_header Host joplin.example.org;
```

or easier:

```
#Nginx config
proxy_set_header Host $host;
```
