### ISSUE TITLE
Bash keyword highlighting works in code editor, but not in preview or on Android 

### ISSUE THREAD

**Issue by clawsl** [laurent22/joplin#6949]
## Description
In the most recent Desktop version, I get keyword highlighting for bash code in the code editor, but not in the rendered preview. This also results in a similar highlighting issue in the most recent Android client version (2.8.1) on my phone 

## Environment
Platform: Windows 10
Joplin 2.9.4 (prod, win32)
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 9698284

## Steps to reproduce

1. Create a new note and add a code block for multi line `bash` code 
```
```bash
#!/bin/bash
wget -O ~/install.sh https://github.com/Hinara/linux-vm-tools/blob/ubuntu20-04/ubuntu/22.04/install.sh
chmod +x ~/install.sh && sudo ~/install.sh
```
2.  Compare the code view with the preview on desktop

![image](https://user-images.githubusercontent.com/78071043/196060579-19635b8d-cf87-4f50-b7d4-08a731f67800.png)

3. See the issue on Android

![image](https://user-images.githubusercontent.com/78071043/196060617-acd6733d-44db-447b-bb2a-871dbfb36b8a.png)

## Describe what you expected to happen
I'd expect the highlighting to work similarly to the version I see in the code editor in the rendered preview  and on Android (wget, chmod and sudo should be highlighted as keywords)

**Comment by bdouxx** [comment]
same problem here.

Joplin 2.8.8 (prod, linux)

Version de Synchro : 3
Version du profil : 41
Trousseau supporté : Non

Révision : c2a6a13
