### ISSUE TITLE
Image URL may be not correct after importing RAW directory from File system of "Synchronisation target" 

### ISSUE THREAD

**Issue by ImaginationWork** [laurent22/joplin#695]
### Operating system
- Windows 10

### Application
- Desktop

Hello laurent,

I feel Joplin is great, and I'm planing to replace Evernote with Joplin. But in this moment I found an tiny issue about Image URL. Here are the reproducible steps:
- Install Joplin-Setup-1.0.104.exe on Machine A (Windows 10);
- Goto "Tools" and select "Synchronisation target" -> "File System" ;
- Type one directory like "C:\sync_joplin" in "Directory to synchronise with (absolute path)" edit box ;
- Create one new note and insert one Image. And the image is presented well;
- after few minite, somethings generated in the "C:\sync_joplin;
- compress "C:\sync_joplin" directory and send it to Machine B (Windows 10, too);
- decompress it to "C:\like_joplin" in Machine B;
- Install Joplin-Setup-1.0.104.exe on Machine B;
- Import "RAW" in Machine B from "C:\like_joplin";
- The image in dosen't shown in Imported note of Machine B's Joplin. When I double click the note, the dialogbox told me the file path dosen't exist - however, the  file path is existed only in Machine A only;

But fortunately, if I Import RAW directory which Export manully from Machine A, everything is OK!

Thanks you 🙂

**Comment by ImaginationWork** [comment]
It seems like this issue occured in the other type of resources (other file type like pdf, ppt) , too :(

**Comment by laurent22** [comment]
To synchronise you need to point the two clients to the same directory (for example shared over the network) and use **synchronisation** (not import/export).

Import/Export is only for backup purposes.

**Comment by zhang-ray** [comment]
Thanks for your answer. But one more question: how can I automaticlly export notes periodically for backup purpose? Are there some settings or CLI command available? 

Thank you very much 😄.

**Comment by ImaginationWork** [comment]
Thanks for your answer. But one more question: how can I automaticlly export notes periodically for backup purpose? Are there some settings or CLI command available?

Thank you very much 😄
