### ISSUE TITLE
Joplin crashes when sharing text to it from clipboard in Android 13

### ISSUE THREAD

**Issue by citadel-lewis** [laurent22/joplin#6951]
On Android 13, when I try to copy some text and share it to Joplin from android's pop-up clipboard, Joplin crashes and doesn't save the text.

## Environment

Joplin version: 2.8.1
Platform: Android
OS specifics: Android 13 Pixel 6

## Steps to reproduce

1.  Select text in Android 13
2. Click the share button on pop-up clipboard 
3. Select Joplin from sharing menu 
4. Nothing will happen
5. Do it again and Android will say that Joplin keeps crashing 

## Describe what you expected to happen
Text is shared to Joplin note 

## Logfile
No errors in Joplin log. Screenshot attached of Android bug report.

![Screenshot_20221017-231256](https://user-images.githubusercontent.com/65517233/196175564-5ec6224b-5c57-43fe-a2a9-65a40501f2e7.png)

**Comment by magical-heyrovsky** [comment]
I don't have this problem on Android 13. When I open my browser, select & copy some text and then share it with Joplin it will create a new note with the copied text in the note body.
