### ISSUE TITLE
suggestion: application styling really needs to be run through a validator during the build

### ISSUE THREAD

**Issue by taw00** [laurent22/joplin#6952]
There are random oddball errors I see as I examine things in the developer tool. This one poked its head up today:

```css
h2 {
			font-size: 1.3em;
			font-weight: bold;
			padding-bottom: .1em; */
```

That came out of `joplin-2.8.8/packages/renderer/noteStyle.ts`. I just looked at the master branch and the error is still there. It's not a terrible one. Just ... messy.

So then I just created a blank note and did a `Publish Note`, grabbed its URL, and shoved it into the W3C Validator ... It did catch that above error (it's the line 90 error below (though it really is line 290 in the source code of that blank note) and it also caught a bunch in `bulma.min.css` ...

<h3>Sorry! We found the following errors (11)</h3>
            <div class="error-section-all">
                <div class="error-section">
                    <h4>URI : <a href="https://joplincloud.com/css/bulma.min.css">https://joplincloud.com/css/bulma.min.css</a></h4>
                    

1 |   | Value Error :  padding                                  auto is not a padding value :                                                                       auto
-- | -- | --
1 |   | Value Error :  padding-top                                  auto is not a padding-top value :                                                                       auto
1 |   | Value Error :  padding-right                                  auto is not a padding-right value :                                                                       auto
1 |   | Value Error :  padding-bottom                                  auto is not a padding-bottom value :                                                                       auto
1 |   | Value Error :  padding-left                                  auto is not a padding-left value :                                                                       auto
1 |   | Value Error :  padding-left                                  auto is not a padding-left value :                                                                       auto
1 |   | Value Error :  padding-right                                  auto is not a padding-right value :                                                                       auto
1 |   | Value Error :  padding-top                                  auto is not a padding-top value :                                                                       auto
1 |   | Value Error :  padding-bottom                                  auto is not a padding-bottom value :                                                                       auto

</div></div>

<h4>URI : <a href="https://862b2pcoar.joplinusercontent.com/shares/eJLKS2rXM3R2gKQdAaQ9Ss">https://862b2pcoar.joplinusercontent.com/shares/eJLKS2rXM3R2gKQdAaQ9Ss</a></h4>
                    

90 |   | Parse Error                                                                      */
-- | -- | --
212 |   | Value Error :  font-size                                  only 0 can be a unit. You must put a unit after your number :                                                                       15

And then there are a bunch of warnings though they all look like noise.

Anyway. I just wanted to put this out as a suggestion and couple errors that are popping up looks like low-hanging fruit for someone. I can't find bulma.min.css in the codebase so ... It must be, pulled in?

Thanks for a great application. -t

**Comment by Wartijn** [comment]
>  I can't find bulma.min.css in the codebase so ... It must be, pulled in?

It is. It's an npm package that Joplin server uses, as you can see [here](https://github.com/laurent22/joplin/blob/dev/packages/server/package.json#L31) 

The package [is on GitHub](https://github.com/jgthms/bulma). You can file an issue there if you want, but  if I were you, I wouldn't worry too much about css errors. If you have your devtools open for a day while browsing different websites, you'll notice that a lot of sites will give you warnings and errors, especially on websites that are a bit more complex (or if you have an adblocker). As long as the website isn't broken, that's not a huge deal. 
 
And because Joplin uses external packages, I don't think it will be useful to run a validator. It's not really possible for the Joplin devs to fix each of those errors themselves. And if they file an issue for every minor error, and wait with releasing until that error is fixed, they'll never be able to release a new version. Again: if it doesn't break the website/app (and isn't a security issue) it's not a huge deal.

**Comment by taw00** [comment]
Warnings? Yes.
Errors? ... should be squashed.

But, I see the point about the challenges of validating during the build since the styling is not all in-house. But ... some of the styling *is* in-house. So ... IMHO, that should be validated as part of the build process. Or at least manually reviewed on occasion. Anyway. I've said what I wanted to say. I will attempt to suppress my OCD. ;)

**Comment by tomasz1986** [comment]
> Again: if it doesn't break the website/app (and isn't a security issue) it's not a huge deal.

This really depends. When it comes to CSS, that's mostly true, but broken/invalid HTML can be a serious accessibility issue, even if the browser still manages to display it visually.
