### ISSUE TITLE
Follow the Freedesktop XDG base directory standard

### ISSUE THREAD

**Issue by x80486** [laurent22/joplin#6959]
On Linux, `Joplin` currently creates a `.config/joplin-desktop/` sub-directory wthin the user's home directory. Most applications/programs make use the `Freedesktop XDG` standard – found here: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html.

Using this standard:
- `$XDG_CACHE_HOME` says "temporal/non-essential" files go to `$HOME/.cache/`
- `$XDG_CONFIG_HOME` says "configuration files" go to `$HOME/.config/`
- `$XDG_DATA_HOME` says "data files" go to `$HOME/.local/share/`

This is just a request to consider using the defined variables for this standard. It makes a lot of sense; it is easy for the user to understand, makes it easier to backup / locate / restore / manage / clear user's data, and creates less clutter in the user's home directory.

Thanks in advance...and thanks so much for your hard work on this – it's amazing!

## Environment

Joplin version: `2.8.8 (Flatpak)`
Platform: `Linux`
OS specifics: `Linux uplink 5.15.74-1-lts #1 SMP Sat, 15 Oct 2022 06:43:47 +0000 x86_64 GNU/Linux`

**Comment by CalebJohn** [comment]
This has come up many times in the past (even resulting in a PR). The state of things was already nicely [summarized by Aeledfyr](https://github.com/laurent22/joplin/issues/6524#issuecomment-1140599533), so I won't be able to add much for you. Basically, it comes down to "If it ain't broke, don't fix it".

**Comment by Daeraxa** [comment]
You might also like to look at this topic
https://discourse.joplinapp.org/t/adherence-to-xdg-base-directory-specification/26725

**Comment by x80486** [comment]
I'm not sure what's being pointed out here. The change is super straightforward, with backwards compatibility. This is considered a bug in modern times — there is a reason for the standard. You could argue if the change might break something, but it wouldn't.

For instance, the first implication is that the `Flatpak` version needs access to the entire user's home directory (as discussed in #6079) because of this — there is some ground to minimize it, but it's not needed if `Joplin` would just stick to the standard.

**Comment by Daeraxa** [comment]
I agree but the correct place to discuss it is really in the forum post I linked above as it isn't technically a bug, it is by design. Please add to that thread if you feel strongly about the issue as I've tried to summarise each side of it as best I can.

**Comment by x80486** [comment]
I respectfully disagree. I'm not sure why do you keep insisting on the "by design" rhetoric because it was an overlook, which keep happening even on brand new applications. Like I said before: this is considered a bug in modern times, hence the reason for the standard.

On the other hand, plenty of bits had died in this process already since I see there are a good amount of conversations around it, so you are already aware of the issue.

Hope you can fix this any time soon! :wave:

**Comment by Daeraxa** [comment]
I say "by design" because that is how it was coded even if it was an oversight. It isn't a bug to be fixed because this isn't unintended behaviour from the application, it is hard coded to that location. A "fix" for this is really an enhancement/improvement request so that it adheres to the specification which is exactly why I opened the conversation in the first place.
If adherence to the spec became mandatory and the application no longer worked because of it then that would absolutely be a bug to fix.
