### ISSUE TITLE
Warning for synchronising with Onedrive business

### ISSUE THREAD

**Issue by matthewmoppett** [laurent22/joplin#696]
### Operating system

- Linux

### Application

- Desktop

I started using Joplin on LInux today and tried synchronising with a Onedrive account, but nothing happened: no warning or failure message, it just didn’t synchronise. Eventually, after a couple of restarts, a warning notice came up saying that synchronising using a Onedrive Business account is not possible (actually my account is a student account at at a university, but I’m guessing that it’s the same issue). I then tried switching to my personal Onedrive account, and the sync went fine.
 
The same story happened on two different LInux machines: with the first one, the warning message came up after I switched to debug mode; on the second, it occurred in normal mode, after restarting Joplin (so I'm not sure debug mode had anything to do with the warning showing up).

This seems like a bit of a bug, for me: the warning about the Onedrive account should happen reliably and immediately.

Attached: log files from laptop 1 (warning first showed up in debug mode)
[log.txt](https://github.com/laurent22/joplin/files/2231612/log.txt)

And from laptop 2: (warning eventually showed up out of the blue)
[log.txt](https://github.com/laurent22/joplin/files/2231630/log.txt)

**Comment by laurent22** [comment]
I agree but unfortunately Microsoft makes it hard to detect if it's OneDrive Business or not (no obvious error message), so the detection is like this at the moment and unlikely to change.
