### ISSUE TITLE
Seach issues with "Umlaut" characters

### ISSUE THREAD

**Issue by la-la-lars** [laurent22/joplin#6965]
## Environment

Joplin version: Joplin 2.8.8 (prod, win32)
Sync-Version: 3
Profil-Version: 41
Revision: c2a6a13
Platform: Windows
OS specifics: Windows 10 64bit

## Steps to reproduce

1. Create a note called _Motor Dämmung_
2. in search bar, type _/dämm_ => nothing shows up; expected: note found
3. Ctrl-P, type either _dämm_ or _/dämm_ => note shows up, but note title is displayed in lower case with wrong character: "motor d**a**mmung"
(inconsistency between search bar and Ctrl+P behaviour)

**Comment by la-la-lars** [comment]
@laurent22 what can I do to make this noticed?

**Comment by sanskarfc** [comment]
If the search query is 
```
dämm*
```
it returns the note.

Isn't this the expected result with respect to the search bar query that you were asking about?

**Comment by la-la-lars** [comment]
> If the search query is
> 
> ```
> dämm*
> ```
> 
> it returns the note.
> 
> Isn't this the expected result with respect to the search bar query that you were asking about?

Well, seems I chose a slightly too specific example...
_dämm*_ indeed works, but only because it occurs as prefix. There is no way to find a substring occurring in the middle of a word.

"Expected" is meant in perspective of a casual user: as such I would expect the search to find _any_ occurrences no matter where.
After re-reading the (hard to find) docs on searching I realize the restrictions of the FTS implementation. Knowing them or in the perspective of a Joplin dev I understand that the current behaviour might seem expected (as in "as implemented")...

Maybe it would be a good idea to look into the Trigram Tokenizer available in SQLite FTS5 to get a more natural search behaviour?
