### ISSUE TITLE
Error: Missing required property: type_:

### ISSUE THREAD

**Issue by markrenier** [laurent22/joplin#6967]
on PC running JoplinPortable.exe from a USB. 

Joplin 2.8.8 (prod, win32)
Client ID: f26539edb5dd40f8a346af9247bd6a41
Sync Version: 3
Profile Version: 41
Keychain Supported: No
Revision: c2a6a13

![joplinerror](https://user-images.githubusercontent.com/7487055/197478833-44707b46-6dda-4d51-ae20-e3bd56a6ce7d.jpg)

I had an image embedded in a note. On the image, right click, reveal location. I drag and drop that file back onto the note, forcing a resize down to 1920x I think. Then I deleted the original image, then saved the note. Now this message displays.

**Comment by JackGruber** [comment]
Please enbable debuging and post the logfile.

**Comment by markrenier** [comment]
[](url)
[log.txt](https://github.com/laurent22/joplin/files/9860096/log.txt)

**Comment by markrenier** [comment]
[log.txt](https://github.com/laurent22/joplin/files/9860104/log.txt)

**Comment by JackGruber** [comment]
For me there is not enough info in the log to say something more precise. 
Maybe something is missing in the md. file in the synctarget or this is not readable by a special character ... Can you upload the md file of the note from the synctarget? 

The noteid is unfortunately not included, you would have to find it via Joplin and it should be a note containing the following image 9ab4424ce8534052901f5e7cc825ec74.jpg

**Comment by tessus** [comment]
This error usually happens, if the files on the sync target are changed manually.
e.g. the file must not have a EOL at EOF.

There are a bunch of topics about this on the forum.

**Comment by markrenier** [comment]
> 

I found the note containing that image. I copied that data into a new note and deleted the original note. The error still appears.

**Comment by wh201906** [comment]
Maybe the note history still exists?
