### ISSUE TITLE
CTRL + P → Polish diacritic letters are casesize specific in search notebook name → should not like others

### ISSUE THREAD

**Issue by Rafurus** [laurent22/joplin#6969]
## Environment
Joplin 2.8.8 (prod, win32)
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes
Revision: c2a6a13
Windows 10

## Steps to reproduce

(I added space after @ to prevent linking to ppl profiles) 

1. Create notebook with upper-case polish diacritic letters ie. KSIĄŻKI
2. Search with "Goto Anything..." (CTRL + P) for lower-case notebook name ie. "@ książki" 
3. Nothing will be found. 
4. If you search for "@ KSIĄŻKI" or "@ ksiĄŻki" (uppercase specyfic diacritic letters) notebook will be found

## Expected behaviour

Search should be noncase specific. 
If you search for text without polish diacritics it's working fine no matter what case it is.

**Comment by Rafurus** [comment]
Bug still exists.

**Comment by JackGruber** [comment]
This is likely to be due to the same problem as with https://github.com/laurent22/joplin/issues/5102 .
