### ISSUE TITLE
Tags in sidebar are not displayed and tags toggles notebooks

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#6970]
The tags in the side menu are not displayed and a clicking on Tags toggles the notebooks (hidde/view).
![Joplin_SwUPuXfiaV](https://user-images.githubusercontent.com/24863925/197709489-b0efe684-af22-4062-afaa-49b89ea41b89.gif)

## Environment

Joplin 2.9.11 (dev, win32)

Client ID: a1021b9020f14fc8bb841cd357208e9d
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 42a7132

## Steps to reproduce

1. Create a note with a tag
2. Try to open the tag menue

## Describe what you expected to happen

Show the tags and toggel the tags menue. 

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/9867171/log.txt)

[console.log](https://github.com/laurent22/joplin/files/9867168/console.log)

**Comment by laurent22** [comment]
Fixed in 5b80fbc5430eb363eb4e13a1e19276e15278d923
