### ISSUE TITLE
synchronization error - self signed certificate in certificate chain

### ISSUE THREAD

**Issue by kiloloz** [laurent22/joplin#6977]
I'm using S3 to synchronize the notes. All set but when synchronizing, it shows the error:
Error. Please check that URL, username, password, etc. are correct and that the sync target is accessible. The reported error was:
self signed certificate in certificate chain (Code SELF_SIGNED_CERT_IN_CHAIN)

## Environment

Joplin version: 2.8.8, win32 portable
Platform: 
OS specifics: win10

**Comment by leematos** [comment]
So I think this error is related to node js moreso than our S3 code. There is no way for the s3 client to accept self-signed certs that I see which leads me to believe that this is being bubbled up from a node.js setting somewhere deep in the stack.
