### ISSUE TITLE
Display additional info when a plugin causes a dialog box to be displayed

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#6979]
To avoid this situation: https://github.com/joplin/plugin-bibtex/issues/33

![image](https://user-images.githubusercontent.com/1285584/198892534-a79bb4ff-dc7c-4593-a60d-9cb010dbe56f.png)

**Comment by laxris** [comment]
Should be easily addressed here:  https://github.com/joplin/plugin-bibtex/blob/94535601975de57aae82db77b0a2e37cef5e4806/src/init.ts#L19
