### ISSUE TITLE
Question about exporting notes periodically.

### ISSUE THREAD

**Issue by ImaginationWork** [laurent22/joplin#698]
### Operating system
- Windows

### Application
- Desktop
- Terminal

Hello Laurent! I eager to  know how can I automaticlly export notes periodically for backup purpose? Are there some settings or CLI command available?

Thank you very much!

**Comment by foxmask** [comment]
Use

    joplin export /path/to/backup/folder

**Comment by ImaginationWork** [comment]
Hello Foxmask, thanks for your reply. But I still want to know whether the funcitonanlity of exporting notes from Joplin Destop periodly automaticlly available?  I just use Joplin Desktop version...

**Comment by foxmask** [comment]
No you need to use a crontab or the at service

**Comment by ImaginationWork** [comment]
Sorry, but I can't get your point...
I just install this https://github.com/laurent22/joplin/releases/download/v1.0.104/Joplin-Setup-1.0.104.exe on my Windows 10. And I want to export all notes to RAW(Joplin Export Directory) automaticlly periodically.

If no, could you please give me more detail? Thank you very much!

**Comment by ImaginationWork** [comment]
Yes I can, but the main problem is that the command below is not working:
`
C:\Users\ImaginationWork\AppData\Local\Programs\Joplin\Joplin.exe export D:\
`

**Comment by foxmask** [comment]
This why you need the Joplin terminal version. Once installed give the path to the profile to use the Joplin desktop data. Because each version uses a different profile folder.
Have a look at the document. I can't details more, I'm on the beach 🏖️;)

**Comment by ImaginationWork** [comment]
Have a nice day 😊
