### ISSUE TITLE
Android: Title hidden when less than 18 lines in the note

### ISSUE THREAD

**Issue by kenricashe** [laurent22/joplin#6982]
## Environment

Joplin version: 2.8.1
Platform: Android
OS specifics: 8.1.0

## Steps to reproduce

1. Create a note or to-do item and enter the title and 17 lines of content.

## Describe what you expected to happen

Title is displayed normally.

## What actually happens

Title is hidden until you enter one more line of content (18 minimum).

## Logfile

![Capture+_2022-10-31-12-51-54](https://user-images.githubusercontent.com/26514157/199099026-094f7a70-1caf-4c8d-809d-a2e1e5a3e782.png)

## Screenshots

![Capture+_2022-10-24-03-01-06](https://user-images.githubusercontent.com/26514157/199099062-90393cdb-1b94-492b-b6fc-a92f47106a35.png)
![Capture+_2022-10-24-03-01-17](https://user-images.githubusercontent.com/26514157/199099066-7c094a1d-b6cb-44c7-aad1-352f922aeec6.png)

**Comment by laurent22** [comment]
Which editor are you using? Is that the new beta editor?

**Comment by kenricashe** [comment]
Not the beta editor, just the regular markdown editor that opens when you click the red circle. Took me a long time to figure out how to reproduce it until I noticed my long notes were displaying the title.

**Comment by laurent22** [comment]
What's the dimensions of you screen? (in pixels if possible) I can't replicate it at the moment.

Also if you have less than 17 lines, like only 1 or 2, it's not going to display the title field at all?

**Comment by kenricashe** [comment]
1080 x 2160. It's an LG Stylo 4.

Any number of lines from 1 to 17 and the title is hidden.

**Comment by laurent22** [comment]
Have you ever tried any version before 2.8 and did it work then?

**Comment by kenricashe** [comment]
Not certain about versions but I've been using Joplin since Jan 17, 2021. I don't remember exactly when I first noticed the missing titles, but it's been months at the very least. Sorry I didn't report it sooner. Wasn't even sure that it was a bug or feature and originally didn't know how to reproduce it.

**Comment by kenricashe** [comment]
Though I have seen great improvements in the Android app, this issue remains.

**Comment by kenricashe** [comment]
issue still not resolved

**Comment by laurent22** [comment]
I can't replicate this, but moving to backlog to prevent auto close

**Comment by kenricashe** [comment]
![Capture+_2024-07-08-16-05-28](https://github.com/user-attachments/assets/d32f0922-6b28-4a40-a041-e0be0e070149)
