### ISSUE TITLE
Tables are rendered differently when the markdown editor is off

### ISSUE THREAD

**Issue by TC68** [laurent22/joplin#6983]
## Environment

Joplin version: 2.8.8
Platform: Linux
OS specifics:  Pop!_OS 22.04 LTS

## Steps to reproduce

1. Toggle the markdown editor on
2. Create a table in markdown 
3. Toggle the markdown editor off
4. The appearance of the table in the view panel changes

## Describe what you expected to happen
I expected the table appearance to be consistent regardless of which editor method is active

## Logfile

No errors to report
![With Markdown](https://user-images.githubusercontent.com/8788393/199135777-3aade168-bdbc-494b-89b0-521c5382c42c.png)
![Without Markdown](https://user-images.githubusercontent.com/8788393/199135781-847d9b17-f520-4562-8187-f6bfc96debeb.png)

**Comment by VasuDevrani** [comment]
I found this issue for some other actions as well.
1. When you are in **full editor mode**, and inserts a new table. Then you open some other window like settings or options. Later when you return back to the editor, the table layout is changed with all properties as null.
2. A newly inserted table (with no content) is erased from the editor if we open another window and return.

## ❌ Problems:
Table layout and properties are not persistent.
Changes whenever editors are toggled or the current window is changed.

## 📸 ScreenShots:
1. Screenshot 1
- Before toggling editor (empty table created)
<img width="400" alt="image" src="https://user-images.githubusercontent.com/101383635/199479022-c4112d34-2860-42f1-a5a8-57451645b23f.png">
- After toggling editor (table lost)
<img width="400" alt="image" src="https://user-images.githubusercontent.com/101383635/199479186-8338c835-2c4e-446b-aefa-c35c5087242f.png">

2. Screenshot 2
- Before toggling editor
<img width="400" alt="image" src="https://user-images.githubusercontent.com/101383635/199479790-3ed25317-45b2-4902-be61-b66989767f01.png">
- After toggling editor (table structure changed and properties are nullified)
<img width="400" alt="image" src="https://user-images.githubusercontent.com/101383635/199479837-c64d1b78-76fc-419a-9949-ded5820e587c.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/101383635/199480111-6b0fb327-eb05-4a2c-bca7-ab1df1563993.png">

**Comment by djsudduth** [comment]
This is also true on MacOS v2.8.8

**Comment by TC68** [comment]
The issue is still here, even if it is a bit stake. Commenting to keep it open

**Comment by djsudduth** [comment]
Yes, this issue is still a problem. Really bummed it wasn't fixed in 2.9.17

**Comment by djsudduth** [comment]
Geeesh - please reopen this
