### ISSUE TITLE
when close input app,interface pile up to the top of the screen，i cannot draw them back to normal display.

### ISSUE THREAD

**Issue by xieyude** [laurent22/joplin#6986]
## Environment

Joplin version: 12.8.1
Platform: IOS 
OS specifics: ios 15.3.1,iphone 8 plus

## Steps to reproduce
sorry,i‘m not able to speak in english well,i'll try my best to describe specifically.抱歉我英语表达能力很差,，我尽力描述清楚。
1. open joplin and click anywhere can be input to activate input app;打开joplin程序，点击任何可以输入的区域以开启输入法程序；
2. close the input app,or click somewhere else that cannot be input;无论是否输入后点击任何不可输入区域或输入法收起按钮
3.all of joplin interface pile up to the top of screen,only a little bit show.joplin界面的所有东西堆叠到手机屏幕最顶端，只显示一行内容。

## Describe what you expected to happen

when close input app,or click somewhere cannot be input,joplin’s interface display normally.我希望关闭输入法或收起输入法后，joplin界面显示正常。

## Logfile
please see screenshot picture below.

![joplin bug pic01](https://user-images.githubusercontent.com/97643758/199191598-7cc4ff7b-f8b9-4d11-bd2b-b09af6d303a3.jpg)
![joplin bug pic02](https://user-images.githubusercontent.com/97643758/199191631-d3e09169-e4d4-4a55-bd5e-8a3280228258.jpg)
![joplin bug pic03](https://user-images.githubusercontent.com/97643758/199191672-54198fce-83d0-4e01-af88-4a03d9e2e5d1.jpg)

**Comment by laurent22** [comment]
Same bug as this? https://github.com/laurent22/joplin/issues/6982

**Comment by kenricashe** [comment]
> Same bug as this? #6982

I think not, as the bug I reported is about the title being hidden and it's Android not iOS.

**Comment by HeliosCultist** [comment]
Hello, I have the same problem. I'm on an ipad.
The issue appears when entering text, a work arround is rotating the screen, however if i enter text again in this mode then the issue is permanent untill i restart the application. This isn't acceptable.
![IMG_0686](https://user-images.githubusercontent.com/47058640/200133851-0cd8100b-0389-4ed3-8450-df7680fc836e.png)
