### ISSUE TITLE
Rich text editor deletes comments

### ISSUE THREAD

**Issue by hrittich** [laurent22/joplin#6997]
## Environment

Joplin version: 2.8.8
Platform: Linux
OS specifics: Debian 11 + Flatpak

## Steps to reproduce

1. Create a new note.
2. Write a HTML comment in the Markdown editor, like

       

4. Switch to the rich text editor.
5. Edit the file, e.g., add some text.
6. Switch back to the Markdown editor.

## Describe what you expected to happen

The comment should be still somewhere in the Markdown file. However, it has been completely removed from the file.

I use HTML comments for making notes to myself, e.g., for how to improve a text I am writing. Would be good, if they are not deleted.

**Comment by Daeraxa** [comment]
This is already noted as a current limitation of the editor: https://joplinapp.org/rich_text_editor/

> If a note is of 'Markup - Markdown' and contains HTML formatting, this may be lost when editing in the Rich Text editor as it cannot be converted to Markdown. Notes of 'Markup - HTML' are not affected by edits in the Rich Text editor as this conversion does not take place.

**Comment by hrittich** [comment]
Fair enough, the app shows the warning banner. Nevertheless, it gives me an uneasy feeling that it is so easy to make a destructive change that cannot be undone easily. Once you edited the file in the rich text editor and switch back to the Markdown editor, CTRL+Z does not work to give you the version before switching to the rich text editor. I was able to get my comments back, by going back in the version history, but it seems like there is no guarantee that a new snapshot is created before switching to rich text mode.

Maybe the situation could be improved by either providing an easy way to revert changes made in the rich text editor or to make it harder to accidentally use it. Is there an option to completely disable the rich text editor?

**Comment by tomasz1986** [comment]
> Is there an option to completely disable the rich text editor?

Not really, but you can hide the button with custom CSS.

**Comment by hrittich** [comment]
Hey,
I would consider it a bug that the rich text editor makes potentially destructive changes that cannot be undone easily (emphasis on the last part). Hence, I would suggest that when switching the the rich text editor, a new revision is stored in the history of a note. If you'd rather categorize this as a feature request, please let me know.
