### ISSUE TITLE
Options/Configuration should show storage location

### ISSUE THREAD

**Issue by yafp** [laurent22/joplin#7]
I am currently testing Joplin, one issue i had is that after creating some test notes & notebooks i can't really figure out where those notes are stored.

It would be helpful if the options UI would display the storage path.

**Comment by ErichDonGubler** [comment]
Alternatively, if this project is not open to configuring the actual location of the synchronized files, it would at least be helpful to document WHERE notes are stored.

**Comment by laurent22** [comment]
Yes I will add a line in the Option screen to show where the files are located.

On Windows: `C:\Users\YOUR_NAME\.config\joplin-deskop`

On macOS and Linux: `~/.config/joplin-desktop`

For the terminal app, it's under the directory "joplin" instead of "joplin-deskop"

**Comment by ErichDonGubler** [comment]
Given that #42 exists and seems to have more discussion on this same topic, could this be closed as a dupe?
