### ISSUE TITLE
PDF Export renders "garbage data"

### ISSUE THREAD

**Issue by hced** [laurent22/joplin#7034]
When rendering as PDF, the output file contains JavasCript, CSS and other code.

Here is the rendered PDF: 
[U2 - Karaktärsrigg guide__tutorial.pdf](https://github.com/laurent22/joplin/files/9931952/U2.-.Karaktarsrigg.guide__tutorial.pdf)

## Environment

Joplin version: 2.8.8 (prod, win32)
Platform: Windows
OS specifics: Windows 11 (22H2)

## Steps to reproduce

1. Create a note
2. Export to PDF

### log.txt output

```
19:04:54: CommandService::execute: exportPdf ['7e35b03e808c48faa24df94ebd92f740']
DevTools failed to load source map: Could not parse content for file:///D:/Temp/29INlr22WVbjvTPaF97yQMMWANh/resources/app.asar/InteropService_Exporter_Html.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///D:/Temp/29INlr22WVbjvTPaF97yQMMWANh/resources/app.asar/index.js.map: Unexpected end of JSON input
InteropServiceHelper.ts:43 Export HTML result:  {warnings: Array(0)}
```

## UPDATE

After going through the [instructions on debugging](https://joplinapp.org/debugging/) enabling debugger by creating `flags.txt` etc. the PDF suddenly renders correctly. No idea why. And after disabling debugger mode by deleting the `flags.txt` is also renders OK. Which means this issue could potentially be marked as Solved, but I'll leave it as Open since the issue shouldn't appear in the first place. Feel free to mark it as Solved.

**Comment by laurent22** [comment]
If you could replicate consistently, and could share the note (as jex) we can probably fix it but otherwise it will be hard

**Comment by hced** [comment]
It did happen again, so it seems to occur on and off. (I do have my notes synced via Dropbox, not sure that matters.) Since I can't reproduce the issue and am in the middle of demanding stydies, I'll close this issue. Maybe at some later point me or someone else could reopen it, providing more reproducible info.
