### ISSUE TITLE
Impossible to paste unformatted text in RichText editor after Joplin v2.9.4

### ISSUE THREAD

**Issue by tomasz1986** [laurent22/joplin#7036]
## Environment

Joplin version: 2.9.12 (or any newer than 2.9.4)
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Copy and pre-formatted text, e.g. with a custom font set and containing a URL.
2. Try to paste it using the RichText editor with formatting removed (e.g. using `Ctrl+Shift+V` on Windows).
4. In Joplin newer than v2.9.4, the content is pasted as plain text with all formatting removed. However, in Joplin newer than v2.9.4, e.g. the currently newest v2.9.12, the content is pasted with formatting despite using the keyboard shortcut that is supposed to remove it.

## Describe what you expected to happen

Until Joplin v2.9.4, it was possible to paste text without formatting. In the later versions, the formatting seems to be always kept. This is very annoying because it requires either to remove it manually or to specifically switch to the Markdown editor in order to paste the text with no formatting.

Also, there are no compiled binaries available between 2.9.5 and 2.9.10, so I can't currently test any of those versions to narrow down the issue a little bit more. When it comes to 2.9.4 and 2.9.12, there were 168 commits in between them (see https://github.com/laurent22/joplin/compare/v2.9.4...v2.9.12). Personally, I'm suspecting the commit https://github.com/laurent22/joplin/commit/5364965a690a3feb441cbe74b37ddaf587720312 to be the culprit.

For the record, this is how the problem looks on screenshots.

1. Joplin 2.9.4 (default font and no URL)

![image](https://user-images.githubusercontent.com/5626656/199810396-7ddcdb9f-ddc4-4d68-96e0-8462332dbfc2.png)

2. Joplin 2.9.12 (different font size and URL kept)

![image](https://user-images.githubusercontent.com/5626656/199810254-96b7a625-1d4c-461e-950a-ccac0e55ff65.png)

## Logfile

- Logfile from Joplin 2.9.4: [logfile Joplin 2.9.4.txt](https://github.com/laurent22/joplin/files/9932346/logfile.Joplin.2.9.4.txt)
- Logfile from Joplin 2.9.12: [logfile Joplin 2.9.12.txt](https://github.com/laurent22/joplin/files/9932347/logfile.Joplin.2.9.12.txt)

**Comment by wh201906** [comment]
I've made PR #7045 to fix it.

**Comment by tomasz1986** [comment]
Thank you very much for such a quick reaction! My workflow consists of much copy and paste from various websites, so being able to paste plain text is kind of critical to my use case 🙁.

**Comment by wh201906** [comment]
You are welcome. I'm supposed to fix it.

**Comment by satbirbains** [comment]
I'm still seeing an issue of formatting when pasting using Ctrl+Shift+V in 2.9.17

Steps:
1. Copy any text from website with which has a background colour
2. Paste into editor using Ctrl+Shift+V

Expected: Text to have been inserted with no formatting including the background colour
Actual: Text is inserted with colour and background colour

Downgrading to 2.9.2 the behaviour is as expected.

![paste_text_with_color](https://user-images.githubusercontent.com/16407417/206039376-13126624-4cdd-40ae-9949-ac0437ab0f3c.jpg)

**Comment by tomasz1986** [comment]
> I'm still seeing an issue of formatting when pasting using Ctrl+Shift+V in 2.9.17

The fix isn't available in 2.9.17 yet. We need to wait for yet another new release for it to be included.

**Comment by Stoneiiii** [comment]
> 我已经制作了 PR #7045来修复它。

is this fix available in 2.9.17?  And new version is still working on it?
