### ISSUE TITLE
[E2E] Consolidate master keys

### ISSUE THREAD

**Issue by ardevd** [laurent22/joplin#704]
I use Joplin on several different devices. Every time I install the app on a new device and enable encryption it seems to generate a new key. In the end I end up with a large number of master keys with the same password and it's a bit confusing. 

Is it possible to consolidate them somehow or at least delete the old keys?

**Comment by laurent22** [comment]
Please have a look at the documentation for info on how to best enable E2EE: https://joplin.cozic.net/e2ee/

**Comment by lazylionca** [comment]
Since I accidentally screwed up and added a master password before sync'ing, I now have three master passwords. Is there a way to see and change which key a note uses, and then delete the spares?

Feature Request.

Thank man. Keep up the great work.

**Comment by rjl6789** [comment]
This is definitely a required feature (consolidate and / or delete keys) - despite what I thought was following the instructions, I ended up with multiple keys after repeated attempts at synchronisation.  Some way of managing these keys would be good.

**Comment by msalini** [comment]
I coulnd't agree more with the comments above.
A way of managing master keys is a very necessary feature.
It would be good to know if at least it was in the backlog and some ETA.
Thanks again for giving us Joplin! :-)M
