### ISSUE TITLE
bug?: External link images are automatically downloaded when creating notes through joplin data api

### ISSUE THREAD

**Issue by rxliuli** [laurent22/joplin#7046]
I have observed that when creating a note through the joplin data api, all the backlink images are downloaded every time, I'm not sure what this is for? Because it seems that the download image is only required when the user is viewing the note preview

## Environment

Joplin version: 2.8.8
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. open joplin clipper service
2. run `curl --data '{ "title": "test", "body": "![1642905576354](https://images.weserv.nl/?url=https://lh3.googleusercontent.com/pw/AL9nZEUmvKBtRxGeG-J-0oVDVmdZccu0E0_HiDHaMPlvWBLp1v2wjaA152s9FxkIRFZROAChN-tYgimcK-ZYBFD_KGya40RzSKfDTVJqvoXjg5CsBmAaJPurSPdDmaDm6Bcunj4IxL_YPBnwtH0h7XdwaUxN=w1600-h1200-no)"}' http://127.0.0.1:27583/notes?token=5bcfa49330788dd68efea27a0a133d2df24df68c3fd78731eaa9914ef34811a34a782233025ed8a651677ec303de6a04e54b57a27d48898ff043fd812d8e0b31`
3. looking at the web proxy tool, you can see requests from joplin

![image](https://user-images.githubusercontent.com/24560368/199885558-99796542-4d86-4cdb-8a02-6968e3439ded.png)

## Describe what you expected to happen

Is there some way to disable this behavior when creating a note, for two reasons

1. It is very slow, if there are a lot of external link pictures in the note, it will even take more than 10s to create a note
2. It may be inaccessible, for example, it is impossible to directly access the pictures of google albums in China

**Comment by Wartijn** [comment]
This is because Joplin saves the image when you add it, so it doesn't need to be downloaded every time you open the note, but only when adding the image. 

@laurent22 isn't this expected behavior?

**Comment by laurent22** [comment]
Yes this is by design actually. As a general rule we want data in Joplin to be self contained so we download all images and convert them to local resources.

**Comment by rxliuli** [comment]
> Yes this is by design actually. As a general rule we want data in Joplin to be self contained so we download all images and convert them to local resources.

But I think it would be better if it was cached on first view or done asynchronously as that would make note creation really slow. . .

**Comment by laurent22** [comment]
It may be slow if there are many images, but I don't really have a solution for this. It is done asynchronously though - you don't have to wait for the API call to end as it will keep processing in the background
