### ISSUE TITLE
joplin desktop 2.9.11 broke macos theme

### ISSUE THREAD

**Issue by sdip15fa** [laurent22/joplin#7051]
## Environment

Joplin version: 2.9.11 onwards
Platform: arch linux
OS specifics: desktop

## Steps to reproduce

1. install joplin 2.9.11 / 2.9.12 prerelease
2. install macos theme
3. install some other plugins (maybe 10)
4. reopen joplin desktop, it would be an empty screen

## Other information

It does work when it is installed alone.

Also, starting from 2.9.11, there is a strange theme change behaviour. To reproduce, obtain a fresh install, then install macos theme alone.
>Just a quick question - do you get this weird theme changing behaviour upon launching Joplin? It feels as if it goes back to default theme every time, and then the plugin theme is applied(happens within 1 sec window)...

Please take a look at this [issue](https://github.com/andrejilderda/joplin-macos-native-theme/issues/83) at the macos theme repository.

## Logfile

all console output in a single not-working run:

[console-log.log](https://github.com/laurent22/joplin/files/9940504/console-log.log)

**Comment by Daeraxa** [comment]
Potential theme breakages are mentioned in the documentation. If there is an intentional change in Joplin that breaks the styles then this is something that would have to be addressed in the theme itself.

> Important: userstyle.css and userchrome.css are provided for your convenience, but they are advanced settings, and styles you define may break from one version to the next. If you want to use them, please know that it might require regular development work from you to keep them working. The Joplin team cannot make a commitment to keep the application HTML structure stable.

**Comment by laurent22** [comment]
You mention 2.9.11, and CSS in plugins was broken in that release. Does it really not work in 2.9.12? If it's an application error we can probably look into it. What we can't do however is guarantee things like class names or HTML structure

**Comment by sdip15fa** [comment]
> You mention 2.9.11, and CSS in plugins was broken in that release. Does it really not work in 2.9.12? If it's an application error we can probably look into it. What we can't do however is guarantee things like class names or HTML structure

If I did not remember wrongly, both on 2.9.11 and 2.9.12 it wouldn't work. I don't quite think it's because of class names / html structure because it would work fine if it's a clean install (that is, with only macos theme installed), but still with a weird theme switching.

**Comment by sdip15fa** [comment]
And there's no errors in the console

**Comment by andrejilderda** [comment]
@sdip15fa  Are you sure you've encountered this issue on 2.9.12? I've just upgraded to that version and for me it's working fine. Could it be that https://github.com/laurent22/joplin/commit/99a61f1 has fixed this issue?

**Comment by sdip15fa** [comment]
> @sdip15fa Are you sure you've encountered this issue on 2.9.12? I've just upgraded to that version and for me it's working fine. Could it be that [99a61f1](https://github.com/laurent22/joplin/commit/99a61f1) has fixed this issue?

I would need to rebuild it to test, but tomorrow

**Comment by sdip15fa** [comment]
> > @sdip15fa Are you sure you've encountered this issue on 2.9.12? I've just upgraded to that version and for me it's working fine. Could it be that [99a61f1](https://github.com/laurent22/joplin/commit/99a61f1) has fixed this issue?
> 
> I would need to rebuild it to test, but tomorrow

@andrejilderda 
no, doesn't work
