### ISSUE TITLE
WebDAV server not reachable, but synchronization falsely successful

### ISSUE THREAD

**Issue by hleskien** [laurent22/joplin#7052]
I sync my Joplin apps through my local WebDAV server. If I am outside the network, the server cannot be reached. When I then click the "Sync" button, nothing happens for a while until it times out. After that, the message "Completed" appears with a time stamp. This suggests that the synchronization was successful.

## Environment

Joplin version: 12.8.1
Platform: iOS
OS specifics: 15.7.1

## Steps to reproduce

1. Configure (local) WebDAV server as sync target
2. Be not connected to your local network, the WebDAV server must not be reachable
3. Press sync button at the bottom of the burger menu

## Describe what you expected to happen

Message "Sync failed" after timeout, maybe together with the reason of the network stack.

## Logfile

![IMG_1611](https://user-images.githubusercontent.com/34342248/200054881-49983016-ed0c-4316-838b-706c39346cc0.png)
![IMG_1610](https://user-images.githubusercontent.com/34342248/200054894-98ed8415-227c-41ca-973f-0cfcd94af0a5.png)

**Comment by wh201906** [comment]
I think this is the same bug/feature as https://github.com/laurent22/joplin/issues/6852#issuecomment-1292195365

**Comment by hleskien** [comment]
You are right. It's a duplicate. But in my opinion the feature is clearly a bug...
