### ISSUE TITLE
Typo in todo 'delete' dialog

### ISSUE THREAD

**Issue by VasuDevrani** [laurent22/joplin#7063]
## Environment

Joplin version: 2.8.8
Platform:  Windows
OS specifics: Windows 11 x64

## Steps to reproduce

1. In desktop application, Create a new todo
2. right click on new todo to see 'delete' option
3. click on delete 
4. dialog shows: **delete note ___**
<img width="500" alt="image" src="https://user-images.githubusercontent.com/101383635/200108791-1ac7fbed-de21-4a53-964a-54901146aed8.png">

## Describe what you expected to happen
Since we are deleting a todo, the dialog box should show: **delete todo __**

**Comment by Mr-Kanister** [comment]
The ability to distinguish between notes and to-dos in this case would still need to be built in. Probably in this area:
https://github.com/laurent22/joplin/blob/adc7d8e2f1fbdd1d16bdf829dbb05c358049eba1/packages/lib/models/Note.ts#L764-L774
