### ISSUE TITLE
'Sqlite error' since the latest update

### ISSUE THREAD

**Issue by super-ben** [laurent22/joplin#7077]
## Environment

Joplin version: latest
Platform: Linux
OS specifics: Ubuntu 22.04.1

## Steps to reproduce

1. Update Joplin Server using the `latest` tag
2. 
3. 

## Describe what you expected to happen

Since the latest Joplin Server update the service became unavailable. When I try to sync, a 502 bad gateway error is shown both on web and in the Joplin client, and when I take a look the docker logs, it shows that a certain sqlite file is missing (I'm using Postgres, by the way).

## Logfile
```shell
Error: Cannot find module '/home/joplin/packages/server/node_modules/sqlite3/lib/binding/node-v93-linux-x64/node_sqlite3.node'
Require stack:
- /home/joplin/packages/server/node_modules/sqlite3/lib/sqlite3-binding.js
- /home/joplin/packages/server/node_modules/sqlite3/lib/sqlite3.js
- /home/joplin/packages/server/dist/app.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/joplin/packages/server/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
```
My docker-compose file is unchanged since I set up the service a long while ago:

```shell
version: '3'

services:
    db:
        image: postgres:13
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DATABASE}
    app:
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        env_file: .env
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=${APP_BASE_URL}
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_HOST=db
```
(clearly using PGSQL)

I haven't touched the environment file or the concerning reverse proxy in more than 6 months.

I believe something changed in the latest update, please help me out as this effectively made Joplin Server defunct for our family.

**Comment by laurent22** [comment]
Strange, I'm not getting this locally, let me check

**Comment by super-ben** [comment]
Thank you. Since the update, my joplin-app-1 container is constantly restarting, so I can't even check things inside it. I don't understand this issue, to be honest.

**Comment by daniel-frak** [comment]
I'm also getting the same issue on a Synology NAS.

Perhaps unrelated, but it seems similar to another issue I found online:
https://discourse.joplinapp.org/t/cannot-find-module-node-sqlite3-node/197

**Comment by dmontesl** [comment]
I'm also getting this in unRAID

**Comment by laurent22** [comment]
Ok that should be fixed now, new version is being built and should be available soon.

https://github.com/laurent22/joplin/actions/runs/3400883601

**Comment by laurent22** [comment]
Please give it another try

**Comment by super-ben** [comment]
I can confirm that it works again, thank you for the quick fix! May we know the root cause? Missing file, permission, or else?

**Comment by dmontesl** [comment]
I works on my end now as well. Thanks for the hard work!

**Comment by laurent22** [comment]
Server was compiled using Node 18 but was running using Node 16. I've added a test now which should catch this kind of issue

**Comment by super-ben** [comment]
Great, thank you very much! Closing this one.
