### ISSUE TITLE
[Feature Request] History & Versioning of notes

### ISSUE THREAD

**Issue by Kriechi** [laurent22/joplin#712]
This is a feature request:

At the moment I'm simply putting all my (encrypted) files in Dropbox, which already provides some crude form of versioning. Since I don't trust Dropbox that much, I also use git to regularly commit all files into a local repository.

Since I'm using encryption, these low-level tools don't allow me to easily rollback or view older versions of a note.

It would be amazing if individual notes would be version-controlled and have a history of recent changes. Similar to what we all know from Google Docs and similar things.

**Comment by tessus** [comment]
see also #753
