### ISSUE TITLE
[Feature Request] Keyboard Shortcut: Ctrl+S / Cmd+S should trigger Sync

### ISSUE THREAD

**Issue by Kriechi** [laurent22/joplin#713]
I'm one of those people that hits Ctrl+s / Cmd+s to save documents every other second or so.

It would be great if the Joplin Electron App would recognise this keyboard shortcut and trigger a synchronization. If I recall correctly, Everynote already does that - which is nice!

**Comment by foxmask** [comment]
ctrl-s for me is to save things - habit with softs like libreoffice

**Comment by coelias** [comment]
I think it should be automatically every X seconds, like nvALT does, Sync should not be shown anywhere, just automatic.

**Comment by alexdevero** [comment]
I disagree with @coelias. Automatic synchronization already caused me a couple of issue. I decided to turn it off and rely on manual sync. I like the idea @Kriechi suggested. I have to admit that when I write something in Joplin, I often habitually press `Ctrl+S` to save and sync the note. Having this shortcut for triggering sync could be very useful.

**Comment by laurent22** [comment]
Sync is automated at the moment so probably this won't be implemented.
