### ISSUE TITLE
[Feature Request] Start up in hidden mode

### ISSUE THREAD

**Issue by tiaga** [laurent22/joplin#714]
I'm surprised that there was no such a request. So, it would be awesome if there will be a built-in option to start the app in hidden mode (in tray) for all desktop platforms.

**Comment by inovek** [comment]
This can be solved from OS, no option necessary. 

**Windows:**
https://www.cnet.com/how-to/how-to-automatically-start-a-program-minimized-in-windows/

**Mac:**
https://www.macworld.com/article/2047747/take-control-of-startup-and-login-items.html

**Linux**: Should be available in modern desktop x-servers, too.

**Comment by diximinga** [comment]
see also
https://discourse.joplin.cozic.net/t/start-minimized-to-tray/433/8

**Comment by pled** [comment]
Tried with devilspie (running Ubuntu 18.04 with Gnome), but no success.
I created  ~/.devilspie/Joplin.ds file with the following 
```
(if
  (is (application_name) "Joplin")
  (minimize)
)

```
but Joplin keeps starting window opened as before.

**Comment by tiaga** [comment]
As a workaround I created the following item in Startup Applications on Linux Mint:
```sh -c "/home/user/.local/bin/Joplin-1.0.104-x86_64.AppImage & sleep 5 && /usr/bin/wmctrl -c Joplin"```

**Comment by pled** [comment]
Closed because there is a workaround ? "Essential" "Enhancement" "Feature request" should still be valid.

**Comment by laurent22** [comment]
Closed because it's bee' implemented
