### ISSUE TITLE
[Feature Request] Navigation

### ISSUE THREAD

**Issue by domoenergytics** [laurent22/joplin#716]
Often, when I'm writing a note, I jump to another note to do a little update. Then I want to go back to the first note. I have not found an easy way. Would it be possible to add navigation keys back and forward, just like in a browser?

Another navigation feature, after searching for un note, the notebook is displayed. I would like to be able to click on this name displayed to reach the notebook.

**Comment by gonike** [comment]
Maybe related: Are there any shortcuts? For instance, something like CTRL+K for jumping to the search field, and then directly being able to use the arrow keys for navigating through search results would be great.

**Comment by gbirke** [comment]
I would still like to have this feature.

**Comment by 0vermind** [comment]
me too. It is very difficult to navigate back and forth without a breadcrumb menu. All GUI should have one.

**Comment by Ruco** [comment]
I would settle for a key binding. For example ALT+left to go back. (And possibly ALT+right to go forward).
So there wouldn't need to be any GUI changes (yet).

**Comment by AFewMistakesAgo** [comment]
+1 for easy navigation back and forth through history of notes visited in current session, at least in desktop version.

**Comment by mahibi** [comment]
.

**Comment by 0vermind** [comment]
Unfortunately, the issue did not get the attention it deserves by the community and the devs. This is a key feature for heavy users like me. I don't want so sound disrespectful Laurent. I'm using Joplin for some year now but ZIM wiki, (a 20 years old software I moved from) is still more navigable and userfriendly (i.e wysiwyg editor etc...) than Joplin. I hope Joplin will improve and catch up!

**Comment by Rishgod** [comment]
> Unfortunately, the issue did not get the attention it deserves by the community and the devs. This is a key feature for heavy users like me. I don't want so sound disrespectful Laurent. I'm using Joplin for some year now but ZIM wiki, (a 20 years old software I moved from) is still more navigable and userfriendly (i.e wysiwyg editor etc...) than Joplin. I hope Joplin will improve and catch up!

@0vermind there is an open PR for that #2563 hopefully it will get approved and this feature will be added soon

**Comment by domoenergytics** [comment]
I'm still waiting for these features...

**Comment by laurent22** [comment]
This has been implemented in #2819

**Comment by wtwver** [comment]
> I would settle for a key binding. For example ALT+left to go back. (And possibly ALT+right to go forward).
> So there wouldn't need to be any GUI changes (yet).

Help -> Toggle developments tools -> Paste the js code into the console

`document.onkeydown = checkKey;

function checkKey(e) {
    var pressed = "";
    if(e.altKey && e.keyCode==37 ){
	    console.log("back");
	    document.querySelector("#react-root > div > div > div.resizableLayoutItem.rli-root > div.resizableLayoutItem.rli-editor > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div > div:nth-child(1) > a:nth-child(1)").click();
    } else if(e.altKey && e.keyCode==39 ){
	    console.log("forward");
	    document.querySelector("#react-root > div > div > div.resizableLayoutItem.rli-root > div.resizableLayoutItem.rli-editor > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div > div:nth-child(1) > a:nth-child(2)").click();
    } 
}`
