### ISSUE TITLE
checkbox click ignored

### ISSUE THREAD

**Issue by br4nnigan** [laurent22/joplin#7186]
## Environment

Joplin version: 2.8.8 (prod, linux)
Platform: Linux
OS specifics: manjaro linux, installed from [AUR package](http://aur.archlinux.org/packages/joplin-desktop)

## Steps to reproduce

use this markdown:

```
- [ ] this
- [ ] that
- [ ] and more

```
toggle view to get the actual checkbox
click checkbox
doesn't get checked

I notice though than when I click the "more" icon (right of the paperclip) and while the submenu is visible, you can actually toggle the checkbox

no errors in console

**Comment by magical-heyrovsky** [comment]
I don't have that problem with Joplin 2.8.8 on Linux (installed via the [recommended](https://github.com/laurent22/joplin#desktop-applications) method).

**Comment by tomasz1986** [comment]
This is fixed in the current pre-releases (see https://github.com/laurent22/joplin/commit/c8b6122a656f7051dd378c8b5e3d9ec88e3788be).

**Comment by br4nnigan** [comment]
@0100110101001010 yeah I used the AppImage before (havent updated it ever though), but it is starting up notably slower.

@tomasz1986 that is great news, I guess I will close this as soon as I get the update and verified it
