### ISSUE TITLE
Android: Failed to attach multiple files to a note at once

### ISSUE THREAD

**Issue by wh201906** [laurent22/joplin#7195]
## Environment

Joplin version: v2.9.8(prod.)
Platform: Android

## Steps to reproduce

1. Click `Attach file` in a note
2. Try to select multiple files
3. Only one single file can be selected.

## Describe what you expected to happen

The file picker should support selecting multiple files

## Logfile

(I think it's unnecessary)

**Comment by wh201906** [comment]
I think this problem is introduced in [#6932](https://github.com/laurent22/joplin/pull/6932/files#diff-bae26a183bc9c96ac2dc7ada643bf5c06a8363be9dba3fca6f2ee0259661aecbL545-L558). 
The `DocumentPicker.pickMultiple()` in `packages/app-mobile/components/screens/Note.tsx` was replaced with `shim.fsDriver().pickDocument()`, but the latter should be called with option `multiple: true`.
~~Plus, when checking the code of `pickDocument()` in `fs-driver-rn.ts`, I found that the multiple selection might not be implemented properly in `react-native-saf-x`.~~ 
`react-native-saf-x` works fine.

**Comment by wh201906** [comment]
@jd1378 Shall we take the `DocumentPicker.pickMultiple()` back temporarily? We can use `shim.fsDriver().pickDocument()` after you implement the multiple selection when you are free.

**Comment by jd1378** [comment]
from what I remember the multiple selection of files should work as expected with saf-x as well
I'm sorry but I think I have probably made a mistake there
can you test it with setting `await shim.fsDriver().pickDocument({ multiple: true })` [locally here](https://github.com/jd1378/joplin/blob/1fe6910089fc5eb7054184a090d7d20ffd62e746/packages/app-mobile/components/screens/Note.tsx#L544) ?
see if it fixes the issue, if it does, please make a pr for it

**Comment by wh201906** [comment]
OK I will test it.

**Comment by wh201906** [comment]
Setting `multiple: true` works. Sorry for my assumption.
