### ISSUE TITLE
Importing notes from keepnote

### ISSUE THREAD

**Issue by masterkorp** [laurent22/joplin#72]
Hello everyone,

I am using a slightly old app called [keepnote](http://keepnote.org/) , that follows the same philsosophy as this one, but it stopped working recently. 

Fortunally all the notes are in plan html, and a sqlite database. 

Did anyone ever tried to import the data from this app?

I figured conveting it should't be too hard. 

Do you have any documentation on how so I contrsuct the markdown notes?

Regards,
Alfredo Palhares

---

**Comment by laurent22** [comment]
Are the notes in HTML format? In this case, the easiest would probably be to convert them to ENEX format and then import this into Joplin. The Enex format is relatively simple is you create it yourself - there's a sample here: https://gist.github.com/evernotegists/6116886

**Comment by yafp** [comment]
@masterkorp have you tested the convert?

**Comment by masterkorp** [comment]
@yafp actully not, I did a test library to convert html to markdown directly. 
```javascript
#!/usr/bin/env node

const fs = require('fs');
const toMarkdown = require('to-markdown');

// Proccess args
let htmlfile = process.argv[2];

// Filters that are specific to Keepnotes
const tt_to_code_block = {
  filter: 'tt',
  replacement: function(content) {
    return '```\n' + content + '\n```';
  }
};

let examplefile = fs.readFileSync(htmlfile, 'utf8');

let text = toMarkdown(examplefile, { converters: [ tt_to_code_block ] });

console.log(text);
```

**Comment by masterkorp** [comment]
I will try an enex converter soon, I really want my old notes back

**Comment by laurent22** [comment]
Closing for now, but if you came up with a solution to import the Keepnote notes please add the info to the Readme file in a pull request.
