### ISSUE TITLE
Importing a jex file causes all notes not in the jex file to be deteted

### ISSUE THREAD

**Issue by stormcoder** [laurent22/joplin#723]
### Operating system

- Windows
- macOS

### Application

- Desktop
- Mobile

I exported a jex file on a OSX 10.13.6 desktop installation and imported the jex file into a Windows 10 desktop installation. Every note and folder not in the jex file was deleted after the import. Joplin then synced immediately and the notes were then deleted from all the other syncing systems causing massive data loss. The sync files are encrypted on dropbox and so I can't tell if all the data is permanently gone or just inaccessible. I'd love to hear that there is some way to recover this data.

**Comment by laurent22** [comment]
Sorry to hear that. Normally importing a JEX file does not delete any data so probably it was synchronisation doing it. It's hard to tell without more information but unexpected things can happen when fiddling with synchronisation, import, export, etc. It's not necessary a bug but possibly a behaviour of the app that is unintuitive (I've added more info about this in the FAQ).

In the meantime, if you had all your notes in the JEX file, I'd recommend starting over from scratch:

- Delete all the config files of the desktop client
- Delete all the data on the sync target. 
- Import the JEX file in the desktop client
- Then synchronise to re-update the sync target.
