### ISSUE TITLE
Order notes manually by number

### ISSUE THREAD

**Issue by istodorionut** [laurent22/joplin#724]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

Hello guys,

They're is a problem with sorting notes automatically by number 1 - 100.
Take a look at the picture to understand better

image
![image](https://user-images.githubusercontent.com/42129745/44293109-d3aba800-a291-11e8-842b-72d692f82d8e.png)

Can this be fixed ?

Thanks,

**Comment by laurent22** [comment]
There's no easy way to fix this, so the solution would be to name the notes as "001. Done", "002. Done", etc.
