### ISSUE TITLE
Android not syncing in background

### ISSUE THREAD

**Issue by ftastisch** [laurent22/joplin#727]
### Operating system
- Android

### Application
- Mobile

Although the app is not optimized for energy consumption and set to sync in intervals, it only syncs when it is opened and not in the background.

**Comment by laurent22** [comment]
Cannot currently be fixed due a limitation of the underlying framework.

**Comment by Weizilla** [comment]
@laurent22 I'm noticing this with the latest version of android. Is this still a known issue? Does having a different storage provider make a difference (Dropbox vs NextCloud)?
