### ISSUE TITLE
Notebook link is removed when editing in wysiwyg editor

### ISSUE THREAD

**Issue by cjhabs** [laurent22/joplin#7294]
When creating a link to a notebook in the markdown editor, the link is removed and replaced with a "#" when the note is edited in the wysiyg editor. See below for detailed steps.

## Environment

Joplin version: 2.8.8
Platform: Linux
OS specifics: Ubuntu 18.04 with xfce4

## Steps to reproduce

1.  Create a link to a notebook in the markdown editor. For example:
`[Link to notebook](:/@506406fcc6384ca5aac5be401885d01a)`
2. Test the link in the markdown viewer - it works
3. Switch to the wysiwyg editor by hitting the "Toggle editor" button:
![image](https://user-images.githubusercontent.com/8117904/201540782-4d2a981a-f459-4c0c-8492-31a24e18323b.png)
4. Make any edit
5. Switch back to the markdown editor. The link now appears as:
`[Link to journal](#)`
All links to notebooks are changed to "#".

Note that if no edits are made in the wysiwyg editor, the notebook links remain in place, unchanged as expected.
Note that links to notes remain unchanged and still work even after editing the note in the wysiwyg editor.

In addition, in the wysiwyg editor:
ctrl-left click on a notebook link does not do anything
By contrast ctrl-left click on a note link jumps to the link

## Describe what you expected to happen
I expect the notebook links to remain unchanged, the way the note links are handled after editing in the wysiwyg editor.
Also, I expect ctrl-left click on a notebook link to behave the way it does when clocking the link in the viewer.

**Comment by wh201906** [comment]
I wonder how to get the markdown link of a notebook. I only get these actions
![image](https://user-images.githubusercontent.com/62299611/202418640-fa7125cd-39df-4b54-8f6d-063b9b004317.png)
Do you mean the link of a note?
![image](https://user-images.githubusercontent.com/62299611/202418914-8dae8d35-6fab-4e1a-bdc7-1e5b19101a0a.png)

**Comment by cjhabs** [comment]
Not the note link. This is the menu I get when I right click on the notebook:

I thought maybe that option was provided by a plugin. I tried disabling assorted plugins that looked like they might provide that functionality but I still had that option. I did not want to disable all plugins as that messes up the layout and you need to recreate it.

I am running Joplin version 2.8.8 on a Linux desktop.

Chris

**Comment by wh201906** [comment]
> This is the menu I get when I right click on the notebook:

Did you post a image there? I can't see the menu in your reply.

**Comment by cjhabs** [comment]
Hi
Sorry, I replied via email and it must have dropped the image.
![2022-11-17_05-56](https://user-images.githubusercontent.com/8117904/202428548-d264f6ee-a8e9-4409-86df-2cd54d4c1650.png)

**Comment by wh201906** [comment]
Joplin replaces html links to markdown links when editing something in the WYSIWYG editor. I guess the notebook link is implemented by a plugin and the conversion from Joplin itself doesn't support it. This also matches what you described:

> ctrl-left click on a notebook link does not do anything

I guess you can only use Markdown editor if you want to have notebook link.

**Comment by cjhabs** [comment]
Is there a way to remove the "toggle editor" button from the UI?

**Comment by wh201906** [comment]
I'm not sure if adding a special CSS in `Options`->`Appearance`->`Show Advanced Settings`->`Custom stylesheet for Joplin-wide app styles` works. There might be a existing one in the GitHub issue or forum?
![image](https://user-images.githubusercontent.com/62299611/202433300-03dea283-7967-49ca-999a-591d31c40415.png)

**Comment by cjhabs** [comment]
OK - I will take a look. Thanks

**Comment by wh201906** [comment]
You're welcome. You can also ask it in the forum.

**Comment by dpoulton-github** [comment]
> Is there a way to remove the "toggle editor" button from the UI?

**userchrome.css**

```text
 div.editor-toolbar div button {
    /* removes the MARKDOWN/RICH TEXT button */
     display: none !important;
}
```

**Comment by cjhabs** [comment]
I should have posted back here earlier. I found that CSS on the forums and can confirm that it works like a charm.
Thank you!
