### ISSUE TITLE
The folders (notebooks) are not displayed in sidebar.

### ISSUE THREAD

**Issue by wenzhizhang** [laurent22/joplin#7295]
The folders (notebooks) are not displayed in sidebar.
I tried to synchronize and even deleted local data and download from sync target, the problem is not solved.

![Annotation 2022-11-14 152308](https://user-images.githubusercontent.com/22928245/201599164-393cdd4d-b579-44e5-9366-45d2da1244ea.png)

## Environment

Joplin version: 2.8.8
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce
Sorry, I don't know how to reproduce it, the issue was there when I opened Joplin this morning
1. 
2. 
3.

**Comment by rickysixx** [comment]
Have you checked if your sidebar is simply hidden by going in the menu View and selecting Toggle sidebar?

![image](https://user-images.githubusercontent.com/51907568/202217552-b26d2c32-fb35-4cdd-8f6b-9b3ed2fab2e3.png)
