### ISSUE TITLE
Dropbox sync suddenly frozen on all devices

### ISSUE THREAD

**Issue by ivavictoria** [laurent22/joplin#7303]
## Environments

Joplin version: Joplin 2.8.8 (prod, darwin)
Platform: macOS 
OS specifics: Monterey 12.4

Joplin version: Joplin 2.8.1
Platform: Android
OS specifics: Android 11

## Steps to reproduce

This is happening to me on both platforms, has been going on for a few days, I think?

1. Open Joplin
2. Sync is already running, and never stops. It also never shows any additional info like it usually does. It just has the spinning arrows, and the cancel button.
3. If you hit cancel, it shows the word 'Cancelling...', but just keeps spinning, never finishes finish cancelling.

## Describe what you expected to happen

I expect it to actually sync the files -- usually it shows a count and progress as it goes through all the files, and eventually finishes the sync. Instead, it's getting stuck somewhere, and never starts syncing. Maybe something funny happened with a lock file somewhere? I have no idea. I haven't touched anything, and nothing seems amiss with Dropbox. It just... decided to stop syncing one day. ☹️

The logfile says that synchronization is already in progress?

## Logfile

[joplin-sync-stuck.log](https://github.com/laurent22/joplin/files/10015863/joplin-sync-stuck.log)

**Comment by wh201906** [comment]
If you are using Dropbox, you can check if there are any lock files in `Joplin/locks/`.

**Comment by ivavictoria** [comment]
Thanks! I went in and deleted the locks, and now it's syncing again. ❤️
