### ISSUE TITLE
joplin-desktop not running with /tmp mounted as noexec

### ISSUE THREAD

**Issue by RomainMorlevat** [laurent22/joplin#7304]
When trying to run `joplin-desktop` from my computer, "nothing happens". My /tmp is a mounted like that:
`none /tmp tmpfs defaults,nosuid,nodev,noexec 0 0`
I've identified the `noexec` to be responsible. If I run `TMPDIR="/home/tmp" joplin-desktop` it works.
I found that it comes from Electron but it may be an app config issue: [see this comment of @MarshallOfSound](https://github.com/electron/electron/issues/24242#issuecomment-648914819) 
I also found that @roman-r-m referred to `noexec` [here](https://github.com/laurent22/joplin/issues/4859#issuecomment-822022569) but without a solution.

## Environment

Joplin version: 2.8.8
Platform: x64
OS specifics: ArchLinux 

## Steps to reproduce

1. mount /tmp with noexec option (you can do it with `sudo mount -o remount,noexec /tmp`)
2. run joplin-desktop

## Describe what you expected to happen

I expect Joplin to run properly.

## Logfile
This is the output of `joplin-desktop --open-dev-tools --debug --log-level debug`:
From terminal:
```
[13298:1116/080415.630860:ERROR:node_bindings.cc(245)] Error parsing Node.js cli flags 
xdg-settings: invalid application name
Try 'xdg-settings --help' for more information.
(node:13298) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `@joplinapp-desktop --trace-warnings ...` to show where the warning was created)
[13332:1116/080416.114437:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```
From app/browser's console:
```
Uncaught Error: /tmp/.org.chromium.Chromium.jJsEsr: failed to map segment from shared object
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1143)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5)
    at Module.load (internal/modules/cjs/loader.js:940)
    at Module._load (internal/modules/cjs/loader.js:781)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Function.o._load (electron/js2c/renderer_init.js:29)
    at Module.require (internal/modules/cjs/loader.js:964)
    at require (internal/modules/cjs/helpers.js:88)
    at Object.<anonymous> (/usr/share/joplin-desktop/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4)
```

**Comment by FMRed** [comment]
Same here. 
Tried 2.8.8 and 2.9.3 appimage versions.
OS: Arch

**Comment by RomainMorlevat** [comment]
I still have the issue.

**Comment by RomainMorlevat** [comment]
I still have the issue.

**Comment by RomainMorlevat** [comment]
Still go the issue with:
```
Joplin 2.9.17 (prod, linux)
Révision : 0266536 (master)
```
App is build from [AUR](https://aur.archlinux.org/packages/joplin-desktop) (not AppImage version).

Electron v22.0.3

**Comment by RomainMorlevat** [comment]
Still got the issue.

**Comment by RomainMorlevat** [comment]
Still got the issue.

**Comment by RomainMorlevat** [comment]
Still got the issue with Joplin version 2.10.18

**Comment by RomainMorlevat** [comment]
Still got the issue.
```
joplin v2.10.19
electron v22.3.13
```

**Comment by RomainMorlevat** [comment]
Just a work around for those who need it:
In `/usr/bin/joplin-desktop`, add a `TMPDIR` on the last line with a _path_ that can be _exec_:
```
...
TMPDIR="/home/USERNAME/TMPDIR" ./@joplinapp-desktop "$@"
```
That way joplin-desktop run into that `TMPDIR` and no in `/tmp/`.

**Comment by opqriu** [comment]
/tmp/.mount_joplinLH8fHF
/tmp/.mount_joplinbt0l01
/tmp/.mount_joplincf36a8
/tmp/.mount_joplinvPjrzR

There are 4 Joplin folders in /tmp. 

Each folder is 730MB in size. 

They cannot be deleted using the "sudo rm -rf" command. 

The Joplin AppImage is not currently running. 

~$ ./joplin.appimage 

[9291:1119/060927.572707:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_joplinmfzsWf/chrome-sandbox is owned by root and has mode 4755. Trace/breakpoint trap (core dumped)

Not Run !!!!

**Comment by tcostermans** [comment]
I'm using joplin from within wsl 2 (ubuntu).

Be aware of [Release 2.5.1 · microsoft/WSL · GitHub](https://github.com/microsoft/WSL/releases/tag/2.5.1)
 This release ships following change:
WSLg: Create /run/user/ as a tmpfs mount that systemd expects (solves [#11261](https://github.com/microsoft/WSL/issues/11261))

Joplin was starting, but I saw a white screen.
I could open chrome dev tools and there I observed:
/run/user/1000/snap.joplin-desktop/.org.chromium.Chromium.E5MIAl: failed to map segment from shared object

This looks similar to the reported issue.
