### ISSUE TITLE
bold text of $ is rendered strange

### ISSUE THREAD

**Issue by jerry-ne** [laurent22/joplin#7306]
Markadown editor has strange rendering of bold text: **$$$**

## Environment

Joplin version: Desktop 2.9.11 (pre-release)
Platform: Win 10 x64

## Steps to reproduce

1.  write line **$$$** repeat it 4 times
2.  see differences in every last $

![image](https://user-images.githubusercontent.com/67690823/202292612-8c0d7caa-dfb3-4e7b-8fd5-056679a80911.png)
## Describe what you expected to happen

4 times same $$$

**Comment by roman-r-m** [comment]
Looks to be some weird interaction between Katex and markdown parser.
Looking at the rendered html I can see it treats the text as follows
```
**$$(katex start)$**

**$$(katex end)$**
```
so only the last `$` is in bold because the rest are treated as a katex block
