### ISSUE TITLE
Desktop client: formatting a text selection forces re-positioning of the line to the top

### ISSUE THREAD

**Issue by archont00** [laurent22/joplin#731]
### Operating system
- Linux

### Application
- Desktop
Joplin AppImage 1.0.104

### Issue
After application of text formatting, Joplin scrolls the document so that the selected text is placed on the 1st visible line.

To reproduce:
* Have a text which is longer than the screen height
* Select some text in the middle of screen
* Click on "B" in the tool bar to apply **strong** formatting.
* The selected line is moved to the top - it becomes the 1st visible line in the Edit & Preview layout

Proposal:
* The position of the line with selected text should remain where it was.

**Comment by markwdickson** [comment]
I can confirm that this also happens with the Windows Desktop app, even in the newest version (v127) I just installed.  It is very disorienting and I hope it can be fixed soon.

**Comment by Perkolator** [comment]
I can't reproduce this on Windows 1.0.167.

**Comment by archont00** [comment]
I cannot reproduce it on Linux 1.0.167 either.
