### ISSUE TITLE
Desktop client: Selecting a text in Preview section and clicking on formatting tool bar formats other part of text than the selection

### ISSUE THREAD

**Issue by archont00** [laurent22/joplin#732]
### Operating system
- Linux

### Application

- Desktop
Joplin AppImage 1.0.104

### Issue
* Change the layout so that only formatted Preview is displayed.
* Select some text.
* Click on "**B**" or "*I*" icon in the tool bar.
* Instead of the selection being formatted accordingly, a different part of document is formatted or a placeholder **strong text** or *emphasized text* is inserted in some other location.

This seems to be due to application of formatting for cursor position or text selection in the Editor layout - i.e. the selection in Preview layout is not relevant, which is confusing; especially in the Layout where only the Preview is displayed...

Expected behaviour
* The text selection in Edit and Preview layouts should be synchronised and formatting should be applied to that selection.

**Comment by CastedConst** [comment]
See #1381 

Also having an italic text selected in the editor-view and pressing the italic-button renders the text bold (cause *text* plus *<>* => **text**; tested under Windows, version 1.0.151).

**Comment by archont00** [comment]
The bug is still the same on Linux Desktop (AppImage) 1.0.167.

**Comment by archont00** [comment]
The layout have changed in the meantime:
- The Preview does not have the option to modify text formatting anymore.
- The WYSIWYG editor works as expected.
Closing the issue as invalid now.
