### ISSUE TITLE
Checklists not imported correctly from Evernote

### ISSUE THREAD

**Issue by harvii** [laurent22/joplin#7329]
## Environment

Joplin version: 2.8.8
Platform: Windows
OS specifics: Windows 11

## Steps to reproduce

1. Create a note in Evernote containing a Checklist
2. Export note as ENEX
3. Import note into Joplin (as MD or HTML)

Sample export as generated by Evernote:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE en-export SYSTEM "http://xml.evernote.com/pub/evernote-export4.dtd">
<en-export export-date="20221222T043818Z" application="Evernote" version="10.49.4">
  <note>
    <title>Test</title>
    <created>20221122T043758Z</created>
    <updated>20221122T043813Z</updated>
    <note-attributes>
    </note-attributes>
    <content>
      <![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd"><en-note><ul style="--en-todo:true;"><li style="--en-checked:true;"><div>Test1</div></li><li style="--en-checked:false;"><div>Test2</div></li><li style="--en-checked:false;"><div>Test3</div></li></ul></en-note>      ]]>
    </content>
  </note>
</en-export>
```

## Describe what you expected to happen
Note should contain a checklist with checkboxes:
- [x] Test1
- [ ] Test2
- [ ] Test3

## What actually happens
Checklist is imported as a Bulleted LIst:
- Test1
- Test2
- Test3

**Comment by Wartijn** [comment]
@harvii can you create an export of this note and share it here? 

https://www.evernote.com/shard/s713/sh/c638e835-b4b5-4798-078c-0a7ccbb581a9/3d8104614ea262f282adcc77bf401d83

**Comment by harvii** [comment]
Here it is exported after using the "Save Copy To Evernote" button:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE en-export SYSTEM "http://xml.evernote.com/pub/evernote-export4.dtd">
<en-export export-date="20221222T132350Z" application="Evernote" version="10.49.4">
  <note>
    <title>Testnote copy</title>
    <created>20221122T132253Z</created>
    <updated>20221122T132253Z</updated>
    <note-attributes>
    </note-attributes>
    <content>
      <![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd"><en-note><div><en-todo checked="false" />checkbox</div><div><en-todo checked="false" />another checkbox</div><div><en-todo checked="false" />one more checkbox</div><div><br /></div><div>some text</div><div><br /></div><ul style="--en-todo:true;"><li style="--en-checked:false;"><div>this </div></li><li><div>is a</div></li><li style="--en-checked:false;"><div>checklist</div></li></ul><div><br /></div><div><br /></div><div><br /></div></en-note>      ]]>
    </content>
  </note>
</en-export>
```
The bulleted list turned into checkboxes in Evernote!

However, importing this into Joplin produces a correct checklist+bulleted list, though I feel like this is unintentional :)

**Comment by Wartijn** [comment]
Thanks! So apparently checklists in Evernote are not lists with checkboxes, but bullet lists where every item just looks and behaves like a checkbox... Makes sense to turn them into checkbox lists in Joplin though.

**Comment by harvii** [comment]
Just to clarify, Evernote did not import the note you shared correctly, and the bullet list -incorrectly- became a checklist, so the ENEX export is also incorrect and should be imported into Joplin as two checklists!

Based on this ENEX export, Evernote has two different checkboxes; one is 'en-todo' and is handled correctly by Joplin, and the other is '--en-checked' which is not imported correctly.
