### ISSUE TITLE
import from JEX and RAW does not show subnotebooks

### ISSUE THREAD

**Issue by McSvenster** [laurent22/joplin#733]
### Operating system
- Linux

### Application
- Desktop , Version Joplin 1.0.96 (prod, linux)

### steps to reproduce
- create a notebook "nbtop"
- create a subnotebook "nbsub"
- drag "nbsub" onto "nbtop" to make it a subnotebook of nbtop:

The hierarchy looks like this:

    - nbtop
      - nbsub

Then
- export your data to a .fex file
- remove all config: `rm -Rf .config/Joplin` and `rm -Rf .config/joplin-desktop`
- start Joplin desktop app
- import the jex file

The top notebooks are shown, but not the sub notebooks:

    - nbtop

But when you try to create a new notebook with the name "nbsub" the error message appears, that a notebook with the name "nbsub" already exists.
The smae happens, when you try this with raw exports.

**Comment by McSvenster** [comment]
I found the problem: a look into joplin's sqlite db shows the two notebooks (nbtop and nbsub), but nbsub has the wrong parent id. It seems like an import creates new IDs for items?

**Comment by laurent22** [comment]
This should be fixed in the latest version (104) so please try with this. If it still doesn't work please post back here.
