### ISSUE TITLE
Export to Markdown or other cross-application format

### ISSUE THREAD

**Issue by davidwolfpaw** [laurent22/joplin#734]
Joplin currently focuses much more heavily on import of notes into the application. This is understandable as a way to get users from other services to start using Joplin. You can rescue data from closed file types like ENEX, as well as more open formats like Markdown.

Where Joplin fails is a lack of equally friendly export. Currently the desktop GUI only allows export as Joplin's own JEX and raw, as well as PDF. The terminal application only supports the first two.

What I am requesting is a more robust method of extracting Markdown data from Joplin, which could serve a variety of purposes beyond moving to a different application. As an example, it would allow for easier usage, sharing, and cloud syncing of individual notes.  Content created in or migrated to Joplin could more easily interface with other services, such as writing in Joplin to post to a blog or email while maintaining formatting.

I've reviewed issues about exporting, but haven't seen anything recently for additional export type feature request.

**Comment by foxmask** [comment]
It is not needed to export with Joplin terminal.

Spot the note you want to "export" by

joplin ls -l

Then 

joplin cat note_id > note_title.md

**Comment by davidwolfpaw** [comment]
@foxmask My suggestion is for both the terminal command and the GUI app to offer an Export to Markdown option, both for individual notes, notebooks, and the full storage location.
