### ISSUE TITLE
Can close, but not open menu on mobile with swipe gesture

### ISSUE THREAD

**Issue by 1661410107114145152525** [laurent22/joplin#7343]
On the latest Joplin Android app I can not open the side menu with all my tasks with a slide gesture, though closing it with a gesture is working.

## Environment

Joplin version: 2.8.1
Platform: Android
OS specifics: Samsung Galaxy S21 Ultra, latest OS.

## Steps to reproduce

1. Try to slide from left to right, to open the menu, as it is possible in every other app (not website).
2. Fail a hundred times
3. Decide to ask here for help <3

## Describe what you expected to happen
Menu with all notes should open.

**Comment by wh201906** [comment]
> On the latest Joplin Android app I can not open the side menu with all my tasks with a slide gesture

Does this gesture work on a older version of Joplin? If I remember correctly, this feature is not implemented.
https://discourse.joplinapp.org/t/feature-request-android-mobile-swipe-from-edge-opens-notebook-window-pane/10225

**Comment by 1661410107114145152525** [comment]
I can't remember that it worked ever, but I thought it is a bug because I
can close it with a swipe. It tricks me everyday I try to open it with a
swipe as it is done on every other app.

If it is not a bug, may you please add it as a feature request? It would
improve the UX a lot. My smartphone is very huge and I always need my
second hand to look something up in joplin :(.

Am 25. November 2022 13:22:29 schrieb Self Not Found
***@***.***>:

**Comment by wh201906** [comment]
> I thought it is a bug because I can close it with a swipe.

I think the close gesture works because it's a system-wide gesture. On Android, swipe from the edge of the screen has the same effect of clicking the `Back` button.

> It would improve the UX a lot.

Yeah it does improve the UX a lot, but I guess it might be a little bit difficult to implement it? There are some requests of this feature in the forum and GitHub issues. Hope someone would do this.

**Comment by wh201906** [comment]
> may you please add it as a feature request?

Sorry I don't have the permission to do so. Only the collaborators have the permission to change the label from `bug` to `enhancement`.

**Comment by 1661410107114145152525** [comment]
I have the system wide closure gesture deactivated, it has another cause.

I don't know how difficult it is, sorry.

Am 25. November 2022 13:36:42 schrieb Self Not Found
***@***.***>:

**Comment by 1661410107114145152525** [comment]
Oh okey, nevertheless many thanks!

Am 25. November 2022 13:41:46 schrieb Self Not Found
***@***.***>:

**Comment by wh201906** [comment]
> I don't know how difficult it is, sorry.

Never mind. I have no experience of front end and I don't know how difficult it is too. Maybe it's easier to implement it than I think.

**Comment by personalizedrefrigerator** [comment]
It works for me both ways on iOS with Joplin 2.8.1 when the device is in landscape mode (only the "properties" sidebar, though).

**Comment by 1661410107114145152525** [comment]
So it is a bug? Because on Android it does not work...

Am 1. Dezember 2022 22:45:45 schrieb Henry Heino ***@***.***>:

**Comment by personalizedrefrigerator** [comment]
> So it is a bug? Because on Android it does not work...

It's working for me on Android, too (built from source), but only in landscape mode. Note that I'm swiping left starting from the middle of a note page.

**Comment by 1661410107114145152525** [comment]
Hm ... on my OnePlus 6 and Galaxy S21 it does not work :/

Am 2. Dezember 2022 00:07:05 schrieb Henry Heino ***@***.***>:

**Comment by 1661410107114145152525** [comment]
Please leave the issue open, it has not been solved.

Am 1. Januar 2023 17:02:47 schrieb "github-actions[bot]"
***@***.***>:

**Comment by 1661410107114145152525** [comment]
(Still not fixed, please do not close.)

Am 1. Februar 2023 17:03:15 schrieb "github-actions[bot]"
***@***.***>:

**Comment by Aman-Anas** [comment]
This seems to still be a persistent issue in the latest version of the app. Newer versions of Android use Gesture navigation by default rather than 3-button navigation, and the "back" gesture conflicts with opening the menu.
