### ISSUE TITLE
Note is blank when entering EDIT mode (Android app)

### ISSUE THREAD

**Issue by Klementz** [laurent22/joplin#7350]
I frequently have this problem where the note is totally blank when I enter edit mode. I have to exit edit mode and re-enter to get the editable note to appear. Sometimes it takes three tries.

## Environment

Joplin version: 2.8.1 
Platform: Android
OS specifics: Android 12 

## Steps to reproduce

1. Open note 
2. Press edit button
3. Note is blank, hit back button to exit edit mode and try again

## Describe what you expected to happen
Expect to see the note in edit (markdown) version

## Logfile
[bugreport-caymanlm-SKQ1.211103.001-2022-11-25-10-24-00.zip](https://github.com/laurent22/joplin/files/10094250/bugreport-caymanlm-SKQ1.211103.001-2022-11-25-10-24-00.zip)

Note: I started the log file and entered edit mode in several notes without issue. The bug occured when I opened a note titled "Stones in mineral oil" which appeared blank on first and second try.

**Comment by Klementz** [comment]
I am no longer experiencing this issue. The problem probably went away when I upgraded to Joplin 2.9.8.

**Comment by XilinJia** [comment]
I use 2.8.1 on Android 9 and 2.9.8 on Android 13, don't see this issue.  So probably as the OP says it's already resolved.  Suggest to close this
