### ISSUE TITLE
Can't delete a shared item between two Joplin Cloud Pro accounts

### ISSUE THREAD

**Issue by kiteloopdesign** [laurent22/joplin#7353]
## Environment

Joplin version: 

Joplin 2.8.8 (prod, linux)

Client ID: ee421d08b5ff4bb2a407011b8fd0b623
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: c2a6a13

Platform: Linux (main account)
Also : Android with same user account as Linux. Iphone with other user account who accesses shared notebook

OS specifics: Fedora 35 up-to-date

## Steps to reproduce

Not really easy to list how to reproduce the issue since it does not trigger from a "clean state", so please read on for some background. 

Basically I have two cloud pro accounts so we can collaborate on one notebook. Working from Linux (main account which does 99.99% of creating notebooks, notes, etc), at some point I shared some notebook with the other pro account. Now I can't delete that notebook, without getting the following error when the application tries to save the local content to the joplin server

```
Deleted remote items: 1.
Completed: 26/11/2022 12:08 (30s)
Last error: Error: Cannot find share associated with item Ju14JmY2FNkmg3H9fuTueN
```

![image](https://user-images.githubusercontent.com/17339330/204086069-9a5cbc0e-3cc8-4a36-b7f0-632da2d4d596.png)

The error manifests at the moment from my current state when I do the following

1. delete shared notebook
2. re-synch
3. 

I have tried both deleting the cloud data and resyncing it with local, and also the other way around, deleting the local data and resyncing it to the local app; both result in having again the shared folder which can't be deleted...

Other thing that you guys should look at is why I can't "Leave notebook" when I right click on shared item. I get the following error. Not sure this is because there's this issue with this item or whether I can't "leave it" because it was me who shared it in the first place, in which case it would make sense not being able to "leave" but a more meaningful message could be given. In this case, more than "leave notebook", menu should read "stop sharing", or something of the sorts

![image](https://user-images.githubusercontent.com/17339330/204086475-d71630d8-70ce-4cb1-a79b-edb9093f5e77.png)

## Describe what you expected to happen

I expect to be able to either stop sharing and deleting the shared notebook, which I can't do at the moment

Synch configuration is correct:
![image](https://user-images.githubusercontent.com/17339330/204085741-7cd1f217-3ae8-40ed-9e24-26cb764bc29a.png)

When I have not deleted yet the local shared folder, the cloud server and local one state is clean; i can create and share any note across the devices under my same account. As soon as I delete the shared folder, all synch is broken

## Logfile

See attached. This is a NEW (old one is too long, I have backed it up) log so you guys can see the moment in which I re-sync from the cloud, then try to "leave notebook", then I delete the item, then save to cloud and the error pops up. All this can be seen on the logfile

[log.zip](https://github.com/laurent22/joplin/files/10096124/log.zip)

**Comment by laurent22** [comment]
I believe this has been fixed in a recent version of Joplin Cloud
