### ISSUE TITLE
iOS App with incorrect display of a note after editing (iOS 16)

### ISSUE THREAD

**Issue by McCisie** [laurent22/joplin#7355]
Hi @here! 
Wondering if I am the only one facing the issue on iOS?
Have already reinstalled Joplin twice, rebootet but no improvement.

## Environment

Joplin version: latest from Apple App Store (12.8.1)
Platform: iOS on iPhone 14, sharing encrypted Joplin file using Dropbox
OS specifics: iOS 16.1.1 

## Steps to reproduce

1. Create a note or edit an existing one and edit the text using the Edit button (lower right).
2. Click the "back arrow" in the upper left corner (not undo!)
3. Edited text will not be visible, screen will be broken (edit button is shown in upper right corner). Only restart solves this bug

## Describe what you expected to happen
After clicking the back button, new version of the note should be displayed.

## Logfile

![IMG_4061](https://user-images.githubusercontent.com/68681839/204097937-0a0b2dab-2f3d-432c-a717-d08da352aa0a.PNG)
![IMG_4062](https://user-images.githubusercontent.com/68681839/204097939-60773689-cb8a-4476-b3b7-d4d835a9eb94.PNG)
gging/

**Comment by McCisie** [comment]
![IMG_4061](https://user-images.githubusercontent.com/68681839/204097999-a589e3a5-ca32-459b-a384-9dcc505847a5.PNG)
![IMG_4062](https://user-images.githubusercontent.com/68681839/204098005-1708ac39-cabf-4d47-9079-17221623a9ce.PNG)

**Comment by loganrv** [comment]
I think this happens if you have "Reduce Motion" or "Prefer cross-fade transitions" enabled on your iPhone. Try to disable these. https://support.apple.com/en-us/HT202655

That said, it is a bug and should be not cause this issue really.

**Comment by Daeraxa** [comment]
Does it happen if you opt into the beta editor (in your configuration)?

**Comment by McCisie** [comment]
> I think this happens if you have "Reduce Motion" or "Prefer cross-fade transitions" enabled on your iPhone. Try to disable these. https://support.apple.com/en-us/HT202655
> 
> That said, it is a bug and should be not cause this issue really.

Thanks a lot for your reply, this solved my issue! 
Strange thing is that "Reduce Motion" was already deactivated and I was wondering why I can't see the option for "Prefer cross-fade transitions" at all. After switching ON "Reduce Motion", the option for "Prefer cross-fade transitions" was visible again and it was set to ON. 
After disabling both, Joplin is working well again.

Still it would be great to have the bug fixed: In the (German) App Store are a couple of 1 star reviews related to this issue.

**Comment by McCisie** [comment]
> Does it happen if you opt into the beta editor (in your configuration)?

Unfortunately it didn't solve the issue, needed to switch of both switches mentioned by [loganrv](https://github.com/loganrv).
