### ISSUE TITLE
ios最新版本16.1.1中，用webdav模式下，无法使用域名，只能用真实ip地址才能正常连接上。

### ISSUE THREAD

**Issue by jackpanl** [laurent22/joplin#7357]
Nov 27 04:29:17 iPhone mDNSResponder[160] <Notice>: [R3072->Q16773] getaddrinfo result -- event: add, ifindex: 0, name: BBIjDefB, type: AAAA, rdata: <none>, reason: no-data
Nov 27 04:29:17 iPhone mDNSResponder[160] <Notice>: [R3072->Q43008] getaddrinfo result -- event: add, ifindex: 0, name: BBIjDefB, type: A, rdata: <none>, reason: no-data
Nov 27 04:29:17 iPhone mDNSResponder[160] <Notice>: [R3072] getaddrinfo stop -- hostname: <mask.hash: 'PYWquGDOVJLGekqiqT6JjQ=='>, client pid: 609 (Joplin)
Nov 27 04:29:17 iPhone Joplin(Network)[609] <Notice>: [C92.1 Hostname#11b93af6:33303 failed resolver (satisfied (Path is satisfied), interface: en0[802.11], ipv4, ipv6, dns, proxy)] event: resolver:receive_dns @0.004s, error DNS Error: NoSuchRecord
Nov 27 04:29:17 iPhone Joplin(Network)[609] <Notice>: [C92 Hostname#11b93af6:33303 failed parent-flow (satisfied (Path is satisfied), interface: en0[802.11], ipv4, ipv6, dns, proxy)] event: flow:child_failed @0.005s
Nov 27 04:29:17 iPhone Joplin(Network)[609] <Notice>: nw_connection_report_state_with_handler_on_nw_queue [C92] reporting state failed error DNS Error: NoSuchRecord
Nov 27 04:29:17 iPhone Joplin(CFNetwork)[609] <Error>: Connection 92: received failure notification
Nov 27 04:29:17 iPhone Joplin(CFNetwork)[609] <Error>: Connection 92: failed to connect 12:8, reason -1
Nov 27 04:29:17 iPhone Joplin(CFNetwork)[609] <Error>: Connection 92: encountered error(12:8)
Nov 27 04:29:17 iPhone Joplin(CFNetwork)[609] <Notice>: Connection 92: cleaning up
Nov 27 04:29:17 iPhone Joplin(CFNetwork)[609] <Notice>: Connection 92: summary for unused connection {protocol="(null)", domain_lookup_duration_ms=0, connect_duration_ms=0, secure_connection_duration_ms=0, private_relay=false, idle_duration_ms=0}
Nov 27 04:29:17 iPhone Joplin(Network)[609] <Notice>: [C92 DC5DC0C7-A6FD-4BC5-B166-863745A2BF38 Hostname#11b93af6:33303 tcp, url hash: a4b9783a, definite, attribution: developer] cancel
Nov 27 04:29:17 iPhone Joplin(Network)[609] <Notice>: [C92 Hostname#11b93af6:33303 tcp, url hash: a4b9783a, definite, attribution: developer] cancelled
Nov 27 04:29:17 iPhone Joplin(Network)[609] <Notice>: nw_connection_report_state_with_handler_on_nw_queue [C92] reporting state cancelled error DNS Error: NoSuchRecord
Nov 27 04:29:17 iPhone Joplin(CFNetwork)[609] <Notice>: Task <25D92B31-933D-4E83-A1FC-46F835BF42ED>.<114> can retry(N) with reason(2) for error [12:8]
Nov 27 04:29:17 iPhone Joplin(CFNetwork)[609] <Notice>: _CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x3
Nov 27 04:29:17 iPhone Joplin(CFNetwork)[609] <Error>: Task <25D92B31
-933D-4E83-A1FC-46F835BF42ED>.<114> HTTP load failed, 0/0 bytes (error code: -1003 [12:8])
Nov 27 04:29:17 iPhone Joplin(CFNetwork)[609] <Notice>: Task <25D92B31-933D-4E83-A1FC-46F835BF42ED>.<114> summary for task failure {transaction_duration_ms=9, response_status=-1, connection=92, reused=1, request_start_ms=0, request_duration_ms=0, response_start_ms=0, response_duration_ms=0, request_bytes=0, response_bytes=0, cache_hit=false}
Nov 27 04:29:17 iPhone Joplin(CFNetwork)[609] <Error>: Task <25D92B31-933D-4E83-A1FC-46F835BF42ED>.<114> finished with error [-1003] Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo={_kCFStreamErrorCodeKey=8, NSUnderlyingError=0x2819131b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 UserInfo={_NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en0[802.11], ipv4, ipv6, dns, proxy, _kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=A server with the specified hostname could not be found., NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=12}

**Comment by jackpanl** [comment]
chinese

**Comment by dpoulton-github** [comment]
> ... nw_connection_report_state_with_handler_on_nw_queue [C92] reporting state failed error **DNS Error: NoSuchRecord**

> ... NSLocalizedDescription=**A server with the specified hostname could not be found** ...

Looks to be a DNS error rather than Joplin.

**Comment by zkgh2011** [comment]
I have the same problem.
The same webdav server with the external domain used on my Mac could be synced,but could not be synced on my Iphone.

**Comment by exfounder** [comment]
I have the same problem on linux and windows10 desktops. With the CLI and my android phone, it performed well.
