### ISSUE TITLE
`Signature validation failed` during synchronization with S3 compatible Backblaze B2 bucket

### ISSUE THREAD

**Issue by Neonox31** [laurent22/joplin#7359]
First thanks for making Joplin, it seems to be a remarkable application 👍
I'm totally new using Joplin and during my tests I discovered that I can't sync my notes with a Backblaze B2 bucket with an S3 compatible API, I hope it was possible after reading the following post : https://blog.zakkaru.xyz/2022/02/19/using-backblaze-b2-storage-as-a-synchronization-target-for-joplin/

Maybe Backblaze B2 is simply not supported ?

## Environment

Joplin version: 2.8.8
Platform: Linux
OS specifics: Ubuntu 20.04

## Steps to reproduce

1. Create a B2 bucket and add an application key (read/write) for this bucket for Joplin : 
![2022-11-27_08-19](https://user-images.githubusercontent.com/1135958/204123959-254468b3-8ddb-4bb9-8149-d9b470a2ed0d.png)
![2022-11-27_08-20](https://user-images.githubusercontent.com/1135958/204123958-7b0c3a3d-5843-4c52-b5d0-774e47930744.png)
2. Configure S3 sync in Joplin : 
![2022-11-27_08-21](https://user-images.githubusercontent.com/1135958/204123986-aa32a37d-db08-4f7b-9f0c-68126a1527de.png)
3. Click on `Apply` button

## Describe what you expected to happen

Joplin should normally sync my notes inside Backblaze B2 bucket because it has an S3 compatible API.

## Logfile

```
Logger.ts:219 08:32:53: models/Folder: updateNoteShareIds: notes to update: 0
Logger.ts:219 08:32:53: FileApi: get info.json
Logger.ts:219 08:32:54: FileApi: get .sync/version.txt
Logger.ts:219 08:32:54: Synchronizer: Sync target remote info: 
SyncInfo {version_: 0, masterKeys_: Array(0), e2ee_: {…}, activeMasterKeyId_: {…}, ppk_: {…}}
Logger.ts:219 08:32:54: Synchronizer: Sync target is new - setting it up...
Logger.ts:219 08:32:54: FileApi: get info.json
Logger.ts:219 08:32:55: FileApi: get .sync/version.txt
Logger.ts:219 08:32:55: MigrationHandler: Sync target version is 0 or 1 - creating "locks" and "temp" directory: 
{version: 0}
Logger.ts:219 08:32:55: FileApi: mkdir locks
Logger.ts:219 08:32:55: FileApi: mkdir temp
Logger.ts:219 08:32:55: MigrationHandler: Acquiring exclusive lock
Logger.ts:219 08:32:55: FileApi: list 
Logger.ts:219 08:33:20: FileApi: delete locks/2_1_ead8872323b046fb8fc3863a1de0f187.json
/tmp/.mount_JoplinZ7…er-amazon-s3.js:126 undefined
/tmp/.mount_JoplinZ7…er-amazon-s3.js:127 Signature validation failed
/tmp/.mount_JoplinZ7…er-amazon-s3.js:126 undefined
/tmp/.mount_JoplinZ7…er-amazon-s3.js:127 Signature validation failed
/tmp/.mount_JoplinZ7…er-amazon-s3.js:126 undefined
/tmp/.mount_JoplinZ7…er-amazon-s3.js:127 Signature validation failed
/tmp/.mount_JoplinZ7…er-amazon-s3.js:126 undefined
/tmp/.mount_JoplinZ7…er-amazon-s3.js:127 Signature validation failed
Logger.ts:219 08:33:45: Synchronizer: SignatureDoesNotMatch: Signature validation failed
    at deserializeAws_restXmlDeleteObjectCommandError (/tmp/.mount_JoplinZ7B5qA/resources/app.asar/node_modules/@joplin/lib/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5141:41)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /tmp/.mount_JoplinZ7B5qA/resources/app.asar/node_modules/@joplin/lib/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
    at async /tmp/.mount_JoplinZ7B5qA/resources/app.asar/node_modules/@joplin/lib/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/tmp/.mount_JoplinZ7B5qA/resources/app.asar/node_modules/@joplin/lib/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /tmp/.mount_JoplinZ7B5qA/resources/app.asar/node_modules/@joplin/lib/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
Logger.ts:219 08:33:45: Synchronizer: Sync: finished: Synchronisation finished [1669534373644]
Logger.ts:219 08:33:45: Synchronizer: Operations completed: 
Logger.ts:219 08:33:45: Synchronizer: Total folders: 1
Logger.ts:219 08:33:45: Synchronizer: Total notes: 7
Logger.ts:219 08:33:45: Synchronizer: Total resources: 3
Logger.ts:219 08:33:45: Synchronizer: There was some errors:
Logger.ts:219 08:33:45: Synchronizer: SignatureDoesNotMatch: Signature validation failed
    at deserializeAws_restXmlDeleteObjectCommandError (/tmp/.mount_JoplinZ7B5qA/resources/app.asar/node_modules/@joplin/lib/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5141:41)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /tmp/.mount_JoplinZ7B5qA/resources/app.asar/node_modules/@joplin/lib/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
    at async /tmp/.mount_JoplinZ7B5qA/resources/app.asar/node_modules/@joplin/lib/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/tmp/.mount_JoplinZ7B5qA/resources/app.asar/node_modules/@joplin/lib/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /tmp/.mount_JoplinZ7B5qA/resources/app.asar/node_modules/@joplin/lib/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
Logger.ts:219 08:33:45: Setting up recurrent sync with interval 300
Logger.ts:219 08:33:46: DecryptionWorker: starting decryption...
Logger.ts:219 08:33:46: DecryptionWorker: completed decryption.
```

**Comment by leematos** [comment]
Three things to try:

1. Is your time on the client/server in sync? Clock drift affects S3 signature generation so that's an easy thing to check.
2. Can you use a tool like cyberduck to connect to the B2 bucket and confirm the bucket "works"? That will help isolate this issue to Joplin's S3 code.
3. It's possible that you may need to "forcepath style" (force le style chemin). Try that as well and see if that changes anything.

I saw this a few times when I was implementing this code, and it was almost always a config issue if I remember correctly.

**Comment by leematos** [comment]
This also mentions something about special characters may be a problem? https://bobbyhadz.com/blog/aws-cli-signature-does-not-match

**Comment by Neonox31** [comment]
Thanks a lot @leematos for your help.

Finally, I have recreated another application key and everything works now.

**Comment by travnewmatic** [comment]
i'm having this same issue, but creating new credentials did not work

i'm able to hit the bucket successfully using the same creds with a desktop client (s3drive)

**Comment by leematos** [comment]
@travnewmatic -- being clear, You are having sync issues with B2+Joplin?

- What device?
- What Joplin Version?
- What S3 Settings in Joplin?

**Comment by travnewmatic** [comment]
it appears to have been fixed!  i'm not sure what changed!  i did see that there was a new flathub version, and the version on my phone is syncing properly now.  i havent changed any keys or anything on my android device.

thank you so much for the response and next time i'll be sure to include better information.  i work in IT.  i should be ashamed of my terrible bug report.

thanks again and have a great day!

**Comment by hamolicious** [comment]
> i'm having this same issue, but creating new credentials did not work
> 
> i'm able to hit the bucket successfully using the same creds with a desktop client (s3drive)

I am now stuck with the same issue in 2025 :/
Using minio, desktop client syncs fine, android does not and gives "Signature does not match error", Something about not being able to upgrade version 0 to 1.

I have the same settings on my phone as I do on my desktop.

Desktop: Joplin 3.3.13
Phone: Joplin 3.3.11

Also to address some of the usual fixes I saw:

> Is your time on the client/server in sync? Clock drift affects S3 signature generation so that's an easy thing to check.

yes

> Can you use a tool like cyberduck to connect to the B2 bucket and confirm the bucket "works"? That will help isolate this issue to Joplin's S3 code.

`mc cp` worked fine, desktop sync did too, I can see files in Minio.

> It's possible that you may need to "forcepath style" (force le style chemin). Try that as well and see if that changes anything.

yes, no effect.

> restarting app 😅 

yes
