### ISSUE TITLE
TypeError: dispatcher.useSyncExternalStore after react-redux upgrade to version 8

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#7360]
The upgrade from `react-redux` to version 8 in #7252 has broken the mobile app.
When I run the debug version with Metro I get the following error:

`ERROR  TypeError: dispatcher.useSyncExternalStore is not a function. (In 'dispatcher.useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot)', 'dispatcher.useSyncExternalStore' is undefined)`

With a downgrade to `^7.2.8` and recompile everything works again.

**Comment by personalizedrefrigerator** [comment]
According to [this comment on a related issue in another project](https://github.com/TanStack/query/issues/3839#issuecomment-1285036450), upgrading react-native might also fix this.

**Edit**: Upgrading to react-native 0.69.7 (this required applying [the diff generated by the React Native upgrade tool](https://react-native-community.github.io/upgrade-helper/?from=0.67.2&to=0.69.7) and merging https://github.com/laurent22/joplin/pull/6890) fixed the issue for me.

It might take me a while to create a pull request — an upgrade to react-native 0.69.7 requires changing a large number of iOS-specific files (I only made changes to the Android-specific files).

**Comment by Tolu-Mals** [comment]
I came across this error and created this pull request #7378 to fix it. I downgraded react-redux to `7.2.8`. Had no idea an issue was already created.
