### ISSUE TITLE
Text search not working properly

### ISSUE THREAD

**Issue by ppanish** [laurent22/joplin#7366]
I have a note titled "Turkey Tetrazzini Recipe : Emeril Lagasse : Recipes : Food Network". When I do a search for tetrazzini, any part of that word, start with an upper case T, or prefix with title:, nothing is found. 

When I search for turkey the search succeeds. If I precede the string with a '/' it also succeeds.

This does not seem to be the way a simple text search should work.

If this is functioning properly I can find no documentation to describe the search function, and what I do find does not work (i.e. :title). I only tried the / because somewhere in a web search this was mentioned in some related context I don't recall anymore.

## Environment

Joplin 2.8.8 (prod, darwin)

Client ID: 3acf562bf1d24ef788ce9e79d6b1bce7
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: c2a6a13

MacOS Ventura

## Steps to reproduce

1. See description above, Open joplin
2. perform search as described
3. 

## Describe what you expected to happen
I expect a text search to find the indicated string or substring

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/10104396/log.txt)

**Comment by Daeraxa** [comment]
Documentation on searching is in the main docs - [https://joplinapp.org/help/#searching](https://joplinapp.org/help/#searching)

It does whole word searching, if you need to search substrings then you can use `*` wildcards.

I would have expected searching `tetrazzini` to have returned that page though.

**Comment by sanskarfc** [comment]
If I search for 'tetrazzini', I get the page as follows:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/72058551/206911086-be66721d-6f97-4030-918e-ad0436ee4eed.png">

Isn't this the expected behaviour? Sorry if I missed something here.

**Comment by ppanish** [comment]
Behavior has changed. Previously whole word search failed when the text was not the leading word (though I don't know that this was the cause). This is now working as expected for whole word searches.

Sub-string search works for "basic search" (though there is no description as to what this means) and with wild cards.

This bug report can be closed. I don't appear to be able to do this myself.
