### ISSUE TITLE
Fatal error: Unknown key:spellChecker.languages

### ISSUE THREAD

**Issue by teddybearvan** [laurent22/joplin#7367]
Note: the following has been reported on the Joplin Forum.

I have uninstall, reinstall, Uninstall and deleted all Joplin files both in Folders and in the registry. Then reinstalled again. The problem persists. 
Please advise how to go forward.

Joplin.exe
Fatal error:
Unknown key: spellChecker.languages
Error: Unknown key: spellChecker.languages at Function.settingMetadata 
(C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\models\Setting.js:1319:19 at exports.default 
(C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\profileConfig\merg...:38) at Function.<anonymouse>
(C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\models\Setting.js:1450:78) at Generator.next (<anonymous>) at fulfilled
(C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\models\Setting.js:5:58)

## Environment

Joplin version: 2.8.8
Platform: Windows
OS specifics: Version 10.0.19045.2311

## Steps to reproduce

1. Install joplin.exe
2. completed
3. open joplin
4. fatal error

## Describe what you expected to happen
run the program

## Logfile
/Session Storage/LOG
2022/11/28-09:48:21.803 37cc Reusing MANIFEST C:\Users\"myusername"\AppData\Roaming\Joplin\Session Storage/MANIFEST-000001
2022/11/28-09:48:21.804 37cc Recovering log #3
2022/11/28-09:48:21.805 37cc Reusing old log C:\Users\"myusername"\AppData\Roaming\Joplin\Session Storage/000003.log 

Program will not open so cannot get debug log. 

Windows diagnostic log:
{
    "ver": "4.0",
    "name": "Microsoft.Windows.FaultReporting.AppCrashEvent",
    "time": "2022-11-28T14:31:35.0986439Z",
    "iKey": "o:0a89d516ae714e01ae89c96d185e9ae3",
    "ext": {
        "utc": {
            "shellId": 33786497947533312,
            "eventFlags": 258,
            "pgName": "WINCORE",
            "flags": 905970224,
            "epoch": "5308121",
            "seq": 346
        },
        "metadata": {
            "f": {
                "ProcessCreateTime": 9,
                "ExceptionOffset": 5,
                "AppVersion": 5,
                "ModVersion": 5,
                "AppSessionGuid": 8,
                "TargetAsId": 5
            },
            "privTags": 16777216
        },
        "os": {
            "bootId": 66,
            "name": "Windows",
            "ver": "10.0.19045.2311.amd64fre.vb_release.191206-1406",
            "expId": "FX:112F83D8"
        },
        "app": {
            "id": "W:0000f519feec486de87ed73cb92d3cac802400000000!0000a2309d8b2cd8ac1a796f0f2ba4f6b78ab26dec51!werfault.exe",
            "ver": "2059/06/13:04:57:20!859DA!werfault.exe",
            "asId": 54609
        },
        "device": {
            "localId": "s:5A8312A8-F559-4B62-B9A5-5DDF9363D2B9",
            "deviceClass": "Windows.Desktop"
        },
        "protocol": {
            "devMake": "Hewlett-Packard",
            "devModel": "HP Z800 Workstation"
        },
        "user": {
            "localId": "w:899B97AB-33CD-4CE5-989D-2AFC167A7CBE"
        },
        "loc": {
            "tz": "-05:00"
        }
    },
    "data": {
        "ProcessId": 15404,
        "ProcessCreateTime": "2022-11-28T14:31:28.3238154Z",
        "ExceptionCode": 3221225477,
        "ExceptionOffset": 5505,
        "AppName": "Joplin-Setup-2.8.8.exe",
        "AppVersion": 34360262658,
        "AppTimeStamp": 1544912774,
        "ModName": "System.dll",
        "ModVersion": 0,
        "ModTimeStamp": 1544912634,
        "PackageFullName": "",
        "PackageRelativeAppId": "",
        "ProcessArchitecture": 0,
        "ReportId": "4cd7251b-2049-44ce-be3b-574d3ff7b5e9",
        "Flags": 0,
        "AppSessionGuid": "00003C2C-0001-0042-0A89-FC193603D901",
        "TargetAppId": "W:0006be414129d9dbc098f4b66e1e3b56930c00000904!00003afd7a7b2df90de29302fde84ffb6e09d37c7ebc!Joplin-Setup-2.8.8.exe",
        "TargetAppVer": "2018/12/15:22:26:14!be09739!Joplin-Setup-2.8.8.exe",
        "TargetAsId": 54606,
        "FriendlyAppName": "Joplin for Desktop",
        "IsFatal": true
    }
}

**Comment by Daeraxa** [comment]
Expected behaviour, extra key added from 2.9 is not backwards compatible, refer to forum topic for further details. https://discourse.joplinapp.org/t/fatal-error-unknown-key-spellchecker-languages/28413
