### ISSUE TITLE
Trojan Detected

### ISSUE THREAD

**Issue by JasonCruz-Dev** [laurent22/joplin#7377]
## Environment

Joplin version:  lastest as of Nov 29, 2022
Platform: Desktop
OS specifics: Win10

## Steps to reproduce

1. Downloaded off main joplinaap.org
2. Installed fresh copy on windows 10
3. Ran program, made a new notebook, clicked on file, new note

## Describe what you expected to happen
And my anti-virus protection program pops up with a Trojan Detected and Blocked. 
"ipwho.is" "45.35.72.106"
port: 443
Outbound
AppData/Local/Programs/Joplin/Joplin.exe

## Logfile

Im wanting to know if this is intentional or malicious?

**Comment by laurent22** [comment]
So far 100% of virus reports we got were false positives, but if you want to confirm you can check with VirusTotal.com

**Comment by JackGruber** [comment]
This is 99% a false positive from the used AV software.

The request is from the Geo-location feature for the notes. 
https://github.com/laurent22/joplin/blob/c95367fbbbb6300de1f8fde5f717f0f07255ec9c/packages/lib/geolocation-node.ts#L31


https://github.com/laurent22/joplin/blob/3e518ff2c760672aeea932c3a87ee80c79905e8c/readme/welcome/5_privacy.md

**Comment by JasonCruz-Dev** [comment]
Thank you for clearing this up.
