### ISSUE TITLE
Character Accent Selector writes both characters to note

### ISSUE THREAD

**Issue by roman-mueller** [laurent22/joplin#739]
### Operating system

- macOS

### Application

- Desktop

On macOS when you hold a key on your keyboard you get a accent selection menu.
For example pressing and holding the "o" key will show you:
![screen shot 2018-08-27 at 16 29 35](https://user-images.githubusercontent.com/5560575/44665560-7c869f80-aa16-11e8-8dd0-f2bb138596e1.png)

When I select an accent now with the number keys normally only the adjusted character remains.
However in Joplin both the original as well as the adjusted are written to the note.
Selecting "2" in the above example will write "oö" to the note instead of only "ö".

**Comment by innocuo** [comment]
This now works in Ace, but it's unlikely it'll work for Joplin.

Joplin uses react-ace.
react-ace uses [brace](https://github.com/thlorenz/brace).
brace is using an outdated version of Ace, and hasn't been updated in over a year. It has a couple of PRs and issues posted to upgrade the Ace version, but no updates yet.
There is a PR for react-ace to move away from brace, but [it stopped](https://github.com/securingsincity/react-ace/pull/540).
