### ISSUE TITLE
Joplin 2.8.8 TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by EricCaoHZ** [laurent22/joplin#7394]
Joplin 2.8.8 Error "TypeError: Cannot read properties of undefined (reading 'length')" is reported using the S3 （Object storage for Tencent Cloud） synchronization method
The same goes for mobile

**Comment by EricCaoHZ** [comment]
After I configured another bucket and the corresponding API account, I was able to synchronize normally, but Joplin checked the synchronization configuration here in the settings, and the error will be reported: "发生错误。请检查 URL 、用户名、密码等是否正确以及同步目标是否可访问。报告的错误为："
The same goes for mobile

**Comment by leematos** [comment]
@EricCaoHZ I've seen this transient failure happen before and it usually goes away after a few retries. we do need to better handle the error though.

Re; the check config still failing with a blank error, do you have anything else in the logs? They might give us a little bit more context.

**Comment by EricCaoHZ** [comment]
I didn't find the location to view the log on the PC side, and opened the log on the mobile side, but I didn't see the <Check the synchronization configuration>log information generated by the error that clicked the button

I have also tried to check the synchronization configuration many times, and there is still an error, but fortunately it does not affect the actual use

![image](https://user-images.githubusercontent.com/31092494/205428252-d3d27929-d207-4c66-b537-8e8d133f99ea.png)
![image](https://user-images.githubusercontent.com/31092494/205428270-fda6babf-9adf-4155-ba35-2887e5e37721.png)

**Comment by EricCaoHZ** [comment]
I feel that the S3 synchronization information that I configured for the first time is still saved in the configuration, and I later configured the new Tencent Cloud bucket information, but when I checked the synchronization configuration, the new key was used to access the old S3 bucket, resulting in this error
