### ISSUE TITLE
Let me share a notebook between multiple persons

### ISSUE THREAD

**Issue by okoetter** [laurent22/joplin#74]
### Operating system

- [x] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [x] Desktop
- [x] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---
I would like to share a notebook with several persons. I guess for that I must share the folder on OneDrive, so the absolute path of the OneDrive folder must be configurable in Joplin.

**Comment by laurent22** [comment]
To share notes currently you can simply share a OneDrive account and all clients will sync to the same directory.

Sharing a particular notebook I suspect won't be possible as it means two users will only have partial access to a given sync target, which would be very tricky to get right.
