### ISSUE TITLE
Published notes: security certificate expired

### ISSUE THREAD

**Issue by TimFGMorgan** [laurent22/joplin#7404]
Good evening,

The security certificate seems to be expired on notes published to joplinusercontent.com. This is producing problems for users access it.

This is happening for others' content published, and not just mine. The following is an example of an attempt to access the content published by someone else.

![image](https://user-images.githubusercontent.com/111677696/205508391-da67cfab-de54-42c8-833d-1f0204a07610.png)

The problem is occurring with both Edge and Chrome. I have no other browsers to test on.

Can anyone explain or help?

Thank you!

I apologise if this information is insufficient. I'm a user not a developer, and I have no technical qualifications or training.

Thank you!

**Comment by laurent22** [comment]
Hello, please give it another try, that should work now. And thanks for letting me know about the issue!

**Comment by TimFGMorgan** [comment]
You are AMAZING. Thank you **so much**.
