### ISSUE TITLE
Tinymce: The weird DOM behavior from the h1, h2, h3 buttons. 

### ISSUE THREAD

**Issue by Sinacs** [laurent22/joplin#7407]
## Environment
- Joplin 2.9.17 (prod, win32) 
- Edition	Windows 11 Pro
  - Version	21H2
  - OS build	22000.1219
  - Experience	Windows Feature Experience Pack 1000.22000.1219.0

## Recreate the problem:

1. I created a new note with only one line of text "heading test" in tinymce:

> There is a `div#rendered-md` and `p`.

```
<body id="tinymce">
	<div id="rendered-md">
		<p>heading test</p>
	</div>
</body>
```

![1 start](https://user-images.githubusercontent.com/110529913/205626092-94ba8412-8134-4234-a322-e3f0beafcb81.png)

2. I first press the h2 button(applied h2):

> `p` turned to `h2`, it's normal. 

```
<body id="tinymce">
	<div id="rendered-md">
		<h2>heading test</h2>
	</div>
</body>
```

![2 first press h2 button](https://user-images.githubusercontent.com/110529913/205626107-1ff5c955-b994-442a-8b3a-dadc2d667e37.png)

3. I second press the h2 button(cancel h2):

> The `h2` turned to `div#rendered-md`

```
<body id="tinymce">
	<div id="rendered-md">
		heading test
	</div>
</body>
```

![3 second press h2 button](https://user-images.githubusercontent.com/110529913/205626119-9e97051d-fbe8-4828-aaee-0f1d7f784022.png)

4. I third press the h2 button(applied h2):

> The `div#rendered-md` turned to `h2#rendered-md`

```
<body id="tinymce">
	<h2 id="rendered-md">
		heading test
	</div>
</body>
```

![4 third press h2 button](https://user-images.githubusercontent.com/110529913/205626130-7a2a26bf-8dfa-465a-b910-c3a6b86b8243.png)

5. I fourth press the h2 button(cancel h2):

> The `#rendered-md` is completely disappears from the tinymce.

```
<body id="tinymce">
	<p>heading test</p>
</body>
```

![5 fourth press h2 button](https://user-images.githubusercontent.com/110529913/205626143-785462e0-f15f-4218-bc6f-009ffaa26cab.png)

**Comment by Aditya9764** [comment]
can you please give  this issue to me i'm new to open source contribution

**Comment by roman-r-m** [comment]
We do not assign issues, if you want to work on it, just go ahead

**Comment by Aditya9764** [comment]
What should I do  I want to contribute?

**Comment by roman-r-m** [comment]
> What should I do I want to contribute?

You can still work on this issue, or any other. It's just that we do not formally assign issues, that's all.

**Comment by mansi-garg-12** [comment]
I want to work on this issue. Can you please assign me?
