### ISSUE TITLE
Joplin upgrade fails

### ISSUE THREAD

**Issue by jdonlan17** [laurent22/joplin#7426]
## Environment

Joplin version: 2.8.8
Platform: Windows
OS specifics: Win 10

## Steps to reproduce

1. Open Joplin after installing V2.8.8 - long time since last used.
2. Notes synchronised to Dropbox and encrypted
3. This error window:
4. Joplin upgrade in progress...
Please wait while the sync target is being upgraded. It may take a few seconds or a few minutes depending on the upgrade. The application will automatically restart once it is completed.

Error
The sync target could not be upgraded due to an error. For support, please copy the complete content of this page and paste it in the forum: https://discourse.joplinapp.org/

The full error was:

POST files/list_folder: Error (409): {"error_summary": "path/not_found/..", "error": {".tag": "path", "path": {".tag": "not_found"}}}

Error: POST files/list_folder: Error (409): {"error_summary": "path/not_found/..", "error": {".tag": "path", "path": {".tag": "not_found"}}}
    at newError (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\DropboxApi.js:178:20)
    at DropboxApi.exec (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\DropboxApi.js:191:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FileApiDriverDropbox.list (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-dropbox.js:101:18)

**Comment by Daeraxa** [comment]
> The sync target could not be upgraded due to an error. For support, please copy the complete content of this page and paste it in the forum: [discourse.joplinapp.org](https://discourse.joplinapp.org/)

It gives you a link to the forum right in the message - you are more likely to get support there as it is unlikely to be a bug with the application.

**Comment by jdonlan17** [comment]
And when I went there it says to report bugs here... and I regard errors as a bug :)

**Comment by jdonlan17** [comment]
However, I'll give it a try.
