### ISSUE TITLE
The problem with the path to the program folder

### ISSUE THREAD

**Issue by superbulka** [laurent22/joplin#7434]
Joplin 2.8.8 (prod, win32)
Windows 7 x64

Hello. I use a portable version, but I mean that a bug is also possible in the usual version.
If there is a symbol # in the path to the program, then the markdown of the code breaks.

I use the path C:\ ##MySoft\Joplin\ and get it:

![2022-12-09_120300](https://user-images.githubusercontent.com/19206418/206711875-8c2abc37-58ce-4e11-8561-de69b4e2a4a7.png)

After removing the symbol # from the path, the problem is solved.

**Comment by roman-r-m** [comment]
Shouldn't this be labelled desktop rather than mobile?
