### ISSUE TITLE
Android: note content lost if typing too quickly

### ISSUE THREAD

**Issue by danepowell** [laurent22/joplin#7435]
## Environment

Joplin version: 2.8.1
Platform: Android (F-Droid)
OS specifics: 

## Steps to reproduce

1. Create or edit a note or todo
2. Quickly enter a title or body and hit the "back" arrow
3. Observe that some of the content just entered is lost - usually the last few characters. If the title is short, sometimes the whole title is lost and the note is "untitled".

This is not consistently reproducible, but it happens at least daily for me. Could be triggered by a sync happening simultaneously, or if Android resource utilization is high, not sure.

## Describe what you expected to happen

The note is saved with the full content (title and body) just entered

## Logfile

I'll try to capture a log file next time this happens.

**Comment by laurent22** [comment]
I confirm this has existed pretty much since the first version of Joplin and I still can't replicate it consistently either, let alone fix it. But that would be very nice if we could

**Comment by Karob2** [comment]
Probably the same as #5129

**Comment by danepowell** [comment]
Yep you are probably right that this is a dupe of #5129. I don't know why I assumed that this has to do with typing speed, I don't actually have evidence to support that.
