### ISSUE TITLE
Edit with external editor - no final newline

### ISSUE THREAD

**Issue by sciurius** [laurent22/joplin#744]
### Operating system

- Linux

### Application

- Desktop

When editing a note using an external editor, the document that is passed to the editor does not have a newline after the last line. This confuses some editors and tools. And users.

Solution: Add a final newline, and strip it when reading back the edited file.

**Comment by sciurius** [comment]
Of course my editor can do this, and more (it is rumoured to be an openrating system). I just want to point out that terminating lines with a newline is common practice and also that's how the POSIX standard defines a line:

         3.206 Line
         A sequence of zero or more non- characters plus a terminating character.
         Therefore, lines not ending in a newline character aren’t considered actual lines. That’s why some programs have problems processing the last line of a file if it isn’t newline terminated.

If Joplin wants its 'for internal eyes ony' data files without final newline, that's fine. But when passing a piece of text (a sequence of lines) to an external program conformance is appreciated.

**Comment by downpoured** [comment]
I'll see if I can add a pr for this.

**Comment by downpoured** [comment]
I made a patch, see https://github.com/laurent22/joplin/pull/939, but it's looking like it might not be merged.
