### ISSUE TITLE
Mermaid v8.13.9 needs to be updated

### ISSUE THREAD

**Issue by yunying61** [laurent22/joplin#7445]
## Environment

Joplin version: 2.8.8
Platform: Windows11
OS specifics: 

## Steps to reproduce

1. Use Mermaid's GitGraph
2. Use Mermaid's Double Circle
3. Use some Mermaid's Links
    For example, A o--o B <--> C x--x D

## Describe what you expected to happen

Syntax error in graph
mermaid version 8.13.9
![image](https://user-images.githubusercontent.com/51905599/207217900-12e6d1e9-3246-47a7-820a-9700ec35503d.png)

**Comment by roman-r-m** [comment]
I think it's already been done in dev and will be available in the next release
https://github.com/laurent22/joplin/pull/7330

**Comment by tessus** [comment]
Works in Joplin 2.9.17

**Comment by yunying61** [comment]
> Works in Joplin 2.9.17

Thanks, I saw this update
