### ISSUE TITLE
Joplin Server "Missing required property: type_: "

### ISSUE THREAD

**Issue by super-ben** [laurent22/joplin#7463]
## Environment

Joplin version: 2.9.17
Joplin Server version: 2.10.3
Platform: Linux, iOS
OS specifics: Ubuntu 22.04, Joplin installed via Snap

## Steps to reproduce

1. Update Joplin to the latest version
2. Update Joplin Server to the latest version (Docker)
3.  see error

## Describe what you expected to happen
Continuous sync

## Logfile
Console log:
```shell
17:51:06: Synchronizer: Details: PUT api/items/root:/a35de45550bb40dba48ee1915836c89c.md:/content: Missing required property: type_:  (500): {"error":"Missing required property: type_: "}
```

When I remove a certain note, the error ceases to exist, however, this is a really old note, in which I regularly change a line. On my wife's account the same thing occurs. This error happened only since I updated both my Joplin Client and the Server instance via docker compose.

Also, I see the error "500", indicating a HTTP error 500 but can't seem to imagine why that occurs. Everything related (nginx reverse proxy) remianed unchanged.

Edit:
Using the latest build, whenever I edit any note, the error occurs. A workaround is to downgrade to the previous version, 2.9.7.

**Comment by thegrandpoobah** [comment]
I *just* installed Joplin Server and Joplin on Linux Desktop and Android (from Play Store) and I'm getting the same thing.

Joplin Server: 2.10.3
Joplin Client (Linux): 2.9.17 from Snap Store
Joplin Client (Android): 2.8.1
It says Database v41 in Android's Configuration screen.

I don't have any custom notes yet, whatever is already there from a default install.

```
app_1  | 2022-12-16 17:21:14: App: PUT /api/items/root:/9b31b67f15b04fcd8a1980d68dbd454b.md:/content (500) (3ms)
app_1  | 2022-12-16 17:21:24: [error] App: 192.168.1.1 {
app_1  |   message: 'Missing required property: type_: ',
app_1  |   stack: 'Error: Missing required property: type_: \n' +
app_1  |     '    at Function.<anonymous> (/home/joplin/packages/lib/models/BaseItem.ts:504:28)\n' +
app_1  |     '    at Generator.next (<anonymous>)\n' +
app_1  |     '    at /home/joplin/packages/lib/models/BaseItem.js:8:71\n' +
app_1  |     '    at new Promise (<anonymous>)\n' +
app_1  |     '    at __awaiter (/home/joplin/packages/lib/models/BaseItem.js:4:12)\n' +
app_1  |     '    at Function.unserialize (/home/joplin/packages/lib/models/BaseItem.js:438:16)\n' +
app_1  |     '    at /home/joplin/packages/server/src/utils/joplinUtils.ts:97:18\n' +
app_1  |     '    at Generator.next (<anonymous>)\n' +
app_1  |     '    at /home/joplin/packages/server/dist/utils/joplinUtils.js:8:71\n' +
app_1  |     '    at new Promise (<anonymous>)'
```

**Comment by danepowell** [comment]
This seems to be a regression in 2.10.3. Reverting to 2.9.7 fixes it for me.

I'm able to reproduce the issue by simply editing an existing todo and initiating a sync.

**Comment by zivkovic** [comment]
I tried to actually install the joplin server for the first time today. The check synchronisation fails with
```
Error. Please check that URL, username, password, etc. are correct and that the sync target is accessible. The reported error was:
Could not access data on server "http://localhost:22300"
```

This seems to be caused by the same issue (if I try to manually sync after setting the sync settings), I can see the "_type" error displayed.

**Comment by super-ben** [comment]
> This seems to be a regression in 2.10.3. Reverting to 2.9.7 fixes it for me.
> 
> I'm able to reproduce the issue by simply editing an existing todo and initiating a sync.

Confirmed, this solved it for me, too, for now.

**Comment by thegrandpoobah** [comment]
Confirmed that downgrading to 2.9.7 fixed it for me as well. Thanks @danepowell for the suggestion.

**Comment by inglar** [comment]
how to downgrade to 2.9.7 using docker-compose.yml?
I tried to pull 2.9.7 tag but it's not exist
```
$ docker pull joplin/server:2.9.7
Error response from daemon: manifest for joplin/server:2.9.7 not found: manifest unknown: manifest unknown
```

**Comment by super-ben** [comment]
> how to downgrade to 2.9.7 using docker-compose.yml? I tried to pull 2.9.7 tag but it's not exist
> 
> ```
> $ docker pull joplin/server:2.9.7
> Error response from daemon: manifest for joplin/server:2.9.7 not found: manifest unknown: manifest unknown
> ```

Yes, the tag itself is 2.9.7-beta.

**Comment by Joshndroid** [comment]
Yep seeing this issue as well..
Docker Joplin server with WIndows joplin desktop app.
Pushing back to 2.9.7-beta fixes it for now.
Hopefully just something simple as the fix.

**Comment by super-ben** [comment]
I'm sorry but there's something I don't understand. Even the "file attachment problem on iOS" was tagged "high" two days ago, how come this issue didn't even warrant a response? 

Supposedly, this affects all Joplin Server users, thus on the latest version, the service is unusable - I would think this a rather serious issue.

**Comment by jtagcat** [comment]
@super-ben Have you read the [LICENCE](https://github.com/laurent22/joplin/blob/dev/LICENSE)?
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

edit: You got it for free on the condition that you can't demand anything. Complaining doesn't help.

**Comment by super-ben** [comment]
@jtagcat Yes, I have, tough being "as-is" doesn't change the fact that in it’s current state it cannot be used (the latest version, that is). Anyway, what I wished to convey is that in my book this issue is a tad more important than, for example, the other mentioned issue.

I don’t want to argue with anyone, didn’t blame anyone, it’s just a little strange, that’s all, that no “official” comment was received in any kind.

**Comment by lerenardo** [comment]
La version 2.10.4 fonctionne bien.
Merci @laurent22 !

**Comment by arnovdk** [comment]
Wonderful! @laurent22, thank you so much for the quick fix! I can confirm that the latest update to the Docker image works for me as well.
