### ISSUE TITLE
Still running when suspending Linux

### ISSUE THREAD

**Issue by scollovati** [laurent22/joplin#747]
### Operating system
Linux Mint 19
Cinnamon 3.8.8
Kernel 4.15.0-20-generic

### Application
When I try to suspend the system, this dialog box comes out:
![joplin_suspend](https://user-images.githubusercontent.com/20740642/44902577-b30c3500-ad0a-11e8-9da1-e17bae236f28.png)

then usually I close the app since it is the safest thing to do. 
However this is annoying since you suspend the system exactly for "freezing" the configuration.

**Comment by foxmask** [comment]
did you check to box  "show tray icon" in the general options ?

**Comment by scollovati** [comment]
Yes it is checked.

**Comment by foxmask** [comment]
So you may still have the tray icon in the status bar, even after closing the joplin desktop by clicking on the cross on top right of the joplin windows / or doing ALT-F4 ;  which does not quit Joplin at all.
For that use the menu File>Quit close the tray icon too.

**Comment by scollovati** [comment]
I perfectly understand this. My question is: why should I quit the app? 
When I suspend I can leave open other software but not Joplin.

**Comment by foxmask** [comment]
I see, It looks like the same behavior on android.
often I need to switch between apps and joplin restarts but does not resume when I go back to it.
I'm sure it's restarting because the count of the sync notes go back to 0. May be it's an electron behavior. I don't know.

**Comment by Erudition** [comment]
This is a **critical bug**, as I too am forced to keep Joplin closed whenever I'm not actively using it. _Power management is being suspended_, just like watching a video - meaning even my screen locker never activates! 

Even worse, when I try to put my computer to sleep, it goes into a half-sleep (power light is out, but fans are still spinning) and I cannot wake it. Had to kill the zombie (hard reset) to get my computer back, work lost. I guess my Plasma wasn't as nice as @scollovati 's Cinnamon, and didn't warn me before I tried to put my PC to sleep manually.

I suggest renaming this bug to something like "Joplin always disables power management while open". the tag @laurent22 added "linux-distro-specific" is not accurate, either. Here it is on Kubuntu 18.10:
![image](https://user-images.githubusercontent.com/3915447/52734286-c8aca880-2f92-11e9-8ee3-aefb012a6d28.png)

**Comment by laurent22** [comment]
> Joplin 1.0.111 (prod, linux)

How about trying a more recent version?

**Comment by Erudition** [comment]
> How about trying a more recent version?
While I don't know why Joplin wasn't updated on its own, I did install the latest version.  I used the script, and now that you mention it, I notice it said `Joplin installed in the version 1.0.125`.

However, opening Joplin via the usual icon got me back to 1.0.111 somehow, which is what I copied above. I now realize that there are two _Joplin_ icons in my applications list. The newer one seems to point to `joplin` instead of `appimagekit-joplin`. When I launched it, it asked if I want to install the icon to my system. I did, and now I still have two separate launchers.

So, the updated script installs new launchers but doesn't get rid of the old ones. How do I uninstall the old ones the proper way?

**Comment by laurent22** [comment]
Hmm not sure, as I don't maintain this part of Joplin. If I'm not mistaken the installation script was fixed some times ago so if you get the last script it should work, but you still might need to manually remove the old one.

**Comment by Erudition** [comment]
> but you still might need to manually remove the old one.
Right. Any idea how?

**Comment by foxmask** [comment]
with a kill  ?
ps auxfw |grep joplin 
then kill the parent PID eg 

```
foxmask  18135  0.0  0.0  12784   908 pts/0    S+   14:52   0:00                  |   |   \_ grep joplin
foxmask  12625  0.0  0.5 1478528 98532 tty7    Sl+  févr.12   1:43  \_ /tmp/.mount_JoplinwaRKxJ/app/joplin
foxmask  12645  0.0  0.1 334020 29368 tty7     S+   févr.12   0:00      \_ /tmp/.mount_JoplinwaRKxJ/app/joplin --type=zygote --no-sandbox
foxmask  12676  0.0  0.8 1165436 137992 tty7   Sl+  févr.12   1:10      |   \_ /tmp/.mount_JoplinwaRKxJ/app/joplin --type=renderer --no-sandbox [...]
foxmask  12703  0.0  0.5 1013140 85356 tty7    Sl+  févr.12   0:01      |   \_ /tmp/.mount_JoplinwaRKxJ/app/joplin --type=renderer --no-sandbox [...]
foxmask  12668  0.0  0.7 499256 129512 tty7    Sl+  févr.12   0:09      \_ /tmp/.mount_JoplinwaRKxJ/app/joplin --type=gpu-process ---no-sandbox [...]
foxmask@localhost:~ $ kill -9 12625
foxmask@localhost:~ $ ps auxfw|grep joplin
foxmask  18202  0.0  0.0  12784   980 pts/0    S+   14:53   0:00                  |   |   \_ grep joplin

```

**Comment by Erudition** [comment]
> with a kill ?
> get the PID to kill
> 
> ```
> ps auxfw |grep joplin 
> ```
> 
> then kill the parent PID eg
> 
> ```
> foxmask  18135  0.0  0.0  12784   908 pts/0    S+   14:52   0:00                  |   |   \_ grep joplin
> foxmask  12625  0.0  0.5 1478528 98532 tty7    Sl+  févr.12   1:43  \_ /tmp/.mount_JoplinwaRKxJ/app/joplin
> foxmask  12645  0.0  0.1 334020 29368 tty7     S+   févr.12   0:00      \_ /tmp/.mount_JoplinwaRKxJ/app/joplin --type=zygote --no-sandbox
> foxmask  12676  0.0  0.8 1165436 137992 tty7   Sl+  févr.12   1:10      |   \_ /tmp/.mount_JoplinwaRKxJ/app/joplin --type=renderer --no-sandbox [...]
> foxmask  12703  0.0  0.5 1013140 85356 tty7    Sl+  févr.12   0:01      |   \_ /tmp/.mount_JoplinwaRKxJ/app/joplin --type=renderer --no-sandbox [...]
> foxmask  12668  0.0  0.7 499256 129512 tty7    Sl+  févr.12   0:09      \_ /tmp/.mount_JoplinwaRKxJ/app/joplin --type=gpu-process ---no-sandbox [...]
> foxmask@localhost:~ $ kill -9 12625
> foxmask@localhost:~ $ ps auxfw|grep joplin
> foxmask  18202  0.0  0.0  12784   980 pts/0    S+   14:53   0:00                  |   |   \_ grep joplin
> ```

Are you replying to me? if so, you did not read the comment i was replying to - which was about an old installation script / launcher. I asked how to remove it (because I don't know where to look) and you said "with a kill?" which makes no sense because you do not "kill" a file, you kill a process (as you did in your pasted terminal output). There was no "old" _process_ being discussed; not sure how killing Joplin helps anything.
