### ISSUE TITLE
Can’t synchronize with Nextcloud, 404 MKCOL error 

### ISSUE THREAD

**Issue by Starcr0ss** [laurent22/joplin#7478]
Version: 2.8.8 (Linux), 2.8.1 (Android)
OSes: Arch Linux, Android 11
When trying to sync to my Nextcloud server on both the desktop app and Android, I get the following error:
```
Error: Could not upgrade from version 0 to version 1: 
MKCOL .resource/: Unknown error 2 (404): 
<!DOCTYPE html> <html lang="en"> <head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <meta http-equiv="X-UA-Compatible" content="ie=edge"> <title>Page Not Found</title> <style type="text/css"> body { background-color: #f5f5f5; margin-top: 8%; color: #5d5d5d; font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Robo
```
I am syncing to the following link (except with my domain): `(domain)/remote.php/webdav/Joplin`
and I have created a Joplin folder at the root of my Nextcloud files. How do I make Joplin sync to my Nextcloud server? Do I have to change the permissions of something through my server?
Any help is greatly appreciated!

**Comment by Ixtalo** [comment]
I can confirm this problem.

Today I upgraded from Nextcloud v24 to v25.
Now the WebDAV sync does not work anymore.

I'm not yet sure if this is a problem in Joplin or in Nextcloud (or its `end_to_end_encryption` plugin).


### Joplin

Synchronize-Button:
`Last error: Error: DELETE locks/2_1_c31d243b5c394c5d82b7769657913ce1.json: Client "Joplin/1.0" is not allowed to access end-to-end encrypted content (Exception OCA\DAV\Connector\Sabre\Exception\Forbidden) (403): <?xml version="1.0" encoding="utf-8"?> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:o="http://owncloud.org/ns"> <s:exception>OCA\DAV\Connector\Sabre\Exception\Forbidden</s:exception> <s:message>Client "Joplin/1.0" is not allowed to access end-to-end encrypted content</s:message`



### Nextcloud Server Logs

```
"MKCOL /remote.php/dav/files/testuser1/Joplin/locks/ HTTP/1.1" 405 2205 "-" "Joplin/1.0"
"MKCOL /remote.php/dav/files/testuser1/Joplin/temp/ HTTP/1.1" 405 2205 "-" "Joplin/1.0"
"MKCOL /remote.php/dav/files/testuser1/Joplin/locks/ HTTP/1.1" 405 2205 "-" "Joplin/1.0"
"MKCOL /remote.php/dav/files/testuser1/Joplin/temp/ HTTP/1.1" 405 2205 "-" "Joplin/1.0"
"PROPFIND /remote.php/dav/files/testuser1/Joplin/locks/ HTTP/1.1" 207 2509 "-" "Joplin/1.0"
"PUT /remote.php/dav/files/testuser1/Joplin/locks/2_1_c31d243b5c394c5d82b7769657913ce1.json HTTP/1.1" 403 2337 "-" "Joplin/1.0"
"DELETE /remote.php/dav/files/testuser1/Joplin/locks/2_1_c31d243b5c394c5d82b7769657913ce1.json HTTP/1.1" 403 2333 "-" "Joplin/1.0"
```

### Setup

* Nextcloud 25
	* New test user "testuser1"
	* End-to-End Encryption enabled
	* new folder /Joplin
* Joplin 2.9.17 and 2.10.2
	* Fresh instance
	* Nextcloud sync
		* WebDAV URL: https://mycloud.alest.de/remote.php/dav/files/testuser1/Joplin/
		* username "testuser1"
		* password "..."
		* Check -> "Success! Synchronization configuration appears to be correct."

**Comment by Ixtalo** [comment]
I can confirm this problem.

Today I upgraded from Nextcloud v24 to v25.
Now the WebDAV sync does not work anymore.

I'm not yet sure if this is a problem in Joplin or in Nextcloud (or its `end_to_end_encryption` plugin).


### Joplin

Synchronize-Button:
`Last error: Error: DELETE locks/2_1_c31d243b5c394c5d82b7769657913ce1.json: Client "Joplin/1.0" is not allowed to access end-to-end encrypted content (Exception OCA\DAV\Connector\Sabre\Exception\Forbidden) (403): <?xml version="1.0" encoding="utf-8"?> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:o="http://owncloud.org/ns"> <s:exception>OCA\DAV\Connector\Sabre\Exception\Forbidden</s:exception> <s:message>Client "Joplin/1.0" is not allowed to access end-to-end encrypted content</s:message`



### Nextcloud Server Logs

```
"MKCOL /remote.php/dav/files/testuser1/Joplin/locks/ HTTP/1.1" 405 2205 "-" "Joplin/1.0"
"MKCOL /remote.php/dav/files/testuser1/Joplin/temp/ HTTP/1.1" 405 2205 "-" "Joplin/1.0"
"MKCOL /remote.php/dav/files/testuser1/Joplin/locks/ HTTP/1.1" 405 2205 "-" "Joplin/1.0"
"MKCOL /remote.php/dav/files/testuser1/Joplin/temp/ HTTP/1.1" 405 2205 "-" "Joplin/1.0"
"PROPFIND /remote.php/dav/files/testuser1/Joplin/locks/ HTTP/1.1" 207 2509 "-" "Joplin/1.0"
"PUT /remote.php/dav/files/testuser1/Joplin/locks/2_1_c31d243b5c394c5d82b7769657913ce1.json HTTP/1.1" 403 2337 "-" "Joplin/1.0"
"DELETE /remote.php/dav/files/testuser1/Joplin/locks/2_1_c31d243b5c394c5d82b7769657913ce1.json HTTP/1.1" 403 2333 "-" "Joplin/1.0"
```

### Setup

* Nextcloud 25
	* New test user "testuser1"
	* End-to-End Encryption enabled
	* new folder /Joplin
* Joplin 2.9.17 and 2.10.2
	* Fresh instance
	* Nextcloud sync
		* WebDAV URL: https://.../remote.php/dav/files/testuser1/Joplin/
		* username "testuser1"
		* password "..."
		* Check -> "Success! Synchronization configuration appears to be correct."

**Comment by roman-r-m** [comment]
Try creating the `.resource` manually inside the Joplin folder.

**Comment by Starcr0ss** [comment]
> Try creating the `.resource` manually inside the Joplin folder.

I keep trying to do it but something within the server keeps deleting ".resource" files the moment they're created. I even tried to create a test file and renaming it to .resource and nextcloud complains "The name ".resource" is already used in the folder "/Joplin". Please choose a different name."
I SSH'd into my server and ran `sudo ranger` and found nothing titled ".resource".
This is very odd... any ideas?

**Comment by roman-r-m** [comment]
If the server deletes it, it sounds like an issue there, possibly unrelated to joplin at all. I don't know much about Nextcloud, might be worth asking on their forum, if there is one.

**Comment by Starcr0ss** [comment]
> If the server deletes it, it sounds like an issue there, possibly unrelated to joplin at all. I don't know much about Nextcloud, might be worth asking on their forum, if there is one.

Wait, I forgot that ranger hides files by default. There _is_ a .resource file there... I deleted and re-created it and Joplin is still throwing the same error. I don't know what the problem is. That .resource file does not have anything in it.

**Comment by Starcr0ss** [comment]
I just tried to sync with a fresh new user on my nextcloud server and I am facing the same 404 issue relating to the .resource file.
