### ISSUE TITLE
Docker beta tag 

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#7483]
Currently all docker releases are taged as beta, this makes it look like every version is a beta version and not a stable version. 
![grafik](https://user-images.githubusercontent.com/24863925/208314303-5fc5efce-c426-433e-92ac-007b1fe9f3d7.png)
![grafik](https://user-images.githubusercontent.com/24863925/208314571-81b7b65a-aaab-483c-a192-9bc3dc1564a2.png)
https://github.com/laurent22/joplin/blob/ad2b6ef2fa61c847fb8d3a51ed72536080298824/packages/tools/buildServerDocker.ts#L17-L22

https://github.com/laurent22/joplin/tree/dev/packages/server#supported-docker-tags

If these are all pre-releases, then the latest tag should not be applied and if they are stable, the beta tag should not be applied.

**Comment by tomasvanpottelbergh** [comment]
This is still an issue. It would be great to be able to rely on the `latest` tag for the stable version.

**Comment by lcotonea** [comment]
This issue should be reopened
