### ISSUE TITLE
Serious startup problem with v2.9.17

### ISSUE THREAD

**Issue by MenooMeow** [laurent22/joplin#7484]
When I start the application, only the (partial) menu bar and window frame appears.  No content or core program function menu items appear.  The GUI appears responsive to input but it doesn't do anything.  File --> Quit does nothing.  I have to go into Task Manager to kill several Joplin processes.  Then, it *might* start fully but not always.  It takes several launch attempts to start the program.  (this time it took 2 process kills and 2 restarts)

Once the program is successfully launched, if doing File --> Quit, it never really quits.  A Joplin executable seems to indefinitely use approximately 30% CPU and up to 250mb of memory.  

## Environment

Joplin 2.9.17 (prod, win32)

Client ID: 55bb4222705349c4899d4cfbdd505c0e
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: a84a8e7
Windows 10

## Steps to reproduce

1.  Start Joplin

## Describe what you expected to happen
Expect it to render GUI elements and content.

## Logfile

![2022-12-18 16_49_36-Task Manager](https://user-images.githubusercontent.com/44622158/208323855-bbc83172-8b5d-4ac1-bb6f-66a7fb923dc3.png)
![2022-12-18 16_58_45-Task Manager](https://user-images.githubusercontent.com/44622158/208323862-17ad1b68-97ee-4598-a0f6-e3c9bae7fedb.png)
![2022-12-18 16_57_52-C__Users_turtl_ config_joplin-desktop](https://user-images.githubusercontent.com/44622158/208323868-26548688-e855-40b8-ac36-909e977cf8b1.png)
[log.txt](https://github.com/laurent22/joplin/files/10254839/log.txt)
[1671402364714.log](https://github.com/laurent22/joplin/files/10254842/1671402364714.log)

**Comment by htjain** [comment]
![image](https://user-images.githubusercontent.com/46592577/208347022-7d24e0f3-35ab-4e67-9e8d-a62de674761e.png)
+1 latest version is using ~4GB RAM

**Comment by tomasz1986** [comment]
Do you use any plugins? If yes, then I would suggest to try disabling all of them (after you manage to start Joplin eventually, that is), then restart and see whether there is any difference.

**Comment by roman-r-m** [comment]
Also worth checking logs in the dev console (Help - Toggle development tools)

**Comment by htjain** [comment]
After system restart its back to normal.  Not sure what was the issue.
![image](https://user-images.githubusercontent.com/46592577/208429366-620a1b73-e08c-4e72-b07f-946627def10b.png)

**Comment by MenooMeow** [comment]
> Also worth checking logs in the dev console (Help - Toggle development tools)

I uploaded the dev tools log above.

I've disabled some plugins (notably the auto-backup plugin) and it seems to be working but that's only with 1 trial run.

**Comment by Aman-Anas** [comment]
I have also experienced this bug, I rolled back to 2.8.8 (using installer) and it works fine (rolled back because I needed to access notes quickly). On 2.9.17, the CPU usage skyrocketed as well as the RAM and the actual Joplin window was the same blank white. Developer options showed an empty inspect element window (no code or html, just tabs). I was running a couple plugins (although not the backup one) but didn't test removing those before rolling back.

**Comment by shubhamjain0594** [comment]
Same issue here on Ubuntu 22.04. Had to revert back to 2.8.8. 

- Issue persists in 2.10.3.
- Issue persists even when Joplin is started after disabling all plugins.

In version 2.8.8, the app gives warnings on electron upgrade to 15:

`(node:8090) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.`

Maybe this could be an issue as electron was upgraded to 18 when moving from 2.8 to 2.9?

Update: After several restarts and updates of the laptop the Joplin seems to be working with all extensions. Will update if issue re-occurs.

**Comment by J1wanSeo** [comment]
same error happens to me,  it fixed after downgrade to 2.8.8

Both occurs at mac and Windows 11 with 2.9.17

**Comment by elvynlee** [comment]
guys, try this: go to your joplin content folder, clear the 'userchrome.css‘ and the 'userstyle.css' file(backup them before). 
If you'd been reinstalled joplin and somehow it worked and happened this again, the folder may be back to default path: "C:\Users\ur_user_name\.config\joplin-desktop" due to the auto sync from cloud.

**Comment by J1wanSeo** [comment]
it seems that it happens when i adapt the macOS theme to joplin. If you delete plugin file in directory, it'll be fixed.
