### ISSUE TITLE
Search Functionality Issue in v2.10.2

### ISSUE THREAD

**Issue by godylockz** [laurent22/joplin#7486]
## BUG
In v2.10.2, when using the keyboard shortcut CTRL+F, it opens the search bar (below note window). However when typing afterwards, the typing focus is still inside the note not in the search bar (below note window).

## Solution
Change the focus back to the search bar for typing after CTRL+F is pressed to type directly after when searching within the note.

**Comment by laurent22** [comment]
OS?

**Comment by godylockz** [comment]
> OS?

Windows 11 sorry about that!

**Comment by sanskarfc** [comment]
reproduced in macOS too. 

Seems to be weird. I would like to work on this bug for some time 👍

**Comment by sanskarfc** [comment]
Is this code snippet relevant to this issue?

https://github.com/laurent22/joplin/blob/115cf116a2a9ab5024fd8fb2e531d6bf97d81d5c/packages/app-desktop/gui/MainScreen/commands/search.ts#L3-L18

**Comment by laurent22** [comment]
Duplicate of #7520
