### ISSUE TITLE
Joplin exits when switching profiles on Debian

### ISSUE THREAD

**Issue by vsatmydynipnet** [laurent22/joplin#7488]
## Environment

Joplin version: 2.9.17
Platform: Debian 11

I added a second profile to my Joplin Desktop setup. Each profile syncs to 2 different OwnCloud Instances via WebDAV, Encryption is enabled. 

Basicly all works fine, except:

- When switching Profiles, Joplin exits and I must manually start it, to enter the other profile.

Feature Request:

- A great idea would be to be able to start with something like --profile=ID and be able to run 2 Joplin in parallel on the PC:

Thank you for this great peace of Software!

**Comment by bjohas** [comment]
Confirming bug: I have a 2nd profile, but no sync. Ubuntu 22.04 LTS. App also crashes when switching profile.

@vsatmydynipnet - a profile switch for the command line seems to be available - I haven't tried it yet.

**Comment by XilinJia** [comment]
I also noticed this.  Can I work on this?  Note this would be my first contribution.  So any advice would be appreciated.

**Comment by bjohas** [comment]
@XilinJia - I'm not a developer on this, but I would love to see it fixed.

**Comment by XilinJia** [comment]
Actually, I didn't get an OK to work on this.  If OK, I will do it.

**Comment by eduardobehr** [comment]
Also happening on Fedora with both AppImage and Flatpak.

```
Joplin 2.10.19 (prod, linux)

Client ID: ae0e4a15f3514dd58e2f6bec922506a1
Sync Version: 3
Profile Version: 42
Keychain Supported: No

Revision: 1100ab0
```
