### ISSUE TITLE
After upgrade to 2.9.17 icon is no longer accessible 

### ISSUE THREAD

**Issue by Steve-Z** [laurent22/joplin#7496]
## Environment

Joplin version: 2.9.17
Platform: Linux desktop
OS specifics: Pop!_OS 22.04

## Steps to reproduce

1. View Joplin icon in Dock: generic icon. See attached png.
2. View Joplin icon in Applications Library (Super key): generic icon
3. Not affected by opening/closing Joplin app, nor by system restart.

![Joplin icon 2022-12-18 22-31-24](https://user-images.githubusercontent.com/31359112/208541360-b81a8a30-a4a9-4eff-974f-c44a1cf77dad.png)

## Describe what you expected to happen

I expect Dock and Applications Library to display the Joplin icon found at `$HOME/.local/share/icons/hicolor/512x512/apps/joplin.png` as it did prior to the upgrade.
![joplin](https://user-images.githubusercontent.com/31359112/208541830-e0530572-1d7e-44e3-86cd-aa02506db4b6.png)

## Logfile
[joplin_log.txt](https://github.com/laurent22/joplin/files/10263280/joplin_log.txt)

**Comment by ScriptInfra** [comment]
I am seeing this issue as well on Fedora.

**Comment by koji-k** [comment]
I have same problem.
But my problem had occurred with the previous version i did clean install already.
My OS is Linux Mint 21 Cinnamon edition.
I hoped fixed the problem this latest version.
But there is yet ...

I installed and updated with install script.

There is Joplin between VSCode and Gimp icon.
![joplin_linux](https://user-images.githubusercontent.com/1837402/208642249-1c394095-83f2-41f3-907a-1ac361481ae4.png)

**Comment by m1waterman88** [comment]
This is happening for me after updating to 2.9.17 as well on Ubuntu 22.04.

**Comment by roman-r-m** [comment]
How do you install Joplin?

@laurent22 I wonder if my recent change has made things worse. I doubt it but feel free to revert it
This is the change: https://github.com/laurent22/joplin/pull/7346

**Comment by Steve-Z** [comment]
@roman-r-m I installed using the install script: `wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash`

**Comment by laurent22** [comment]
If reverting will fix this I'm happy to do so, but are we sure it will fix it?

**Comment by roman-r-m** [comment]
> If reverting will fix this I'm happy to do so, but are we sure it will fix it?

No, I have to admit I don't understand what is causing this.
I can replicate the problem, maybe I'll find some time to look into this over the next week.

**Comment by omer-bar** [comment]
I have the same issue
I installed using this:
`wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash`

Joplin 2.9.17
running Ubuntu 22.10 Gnome 43.1

**Comment by korg91** [comment]
Same issue here, Joplin installed with:
`wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash`

I could solve it by manually reverting https://github.com/laurent22/joplin/pull/7346. I simply changed the Icon field to `joplin` in `~/.local/share/applications/appimagekit-joplin.desktop`, and after a few seconds I got my icon back (respecting my custom icon theme, which is Numix Circle).

**Comment by omer-bar** [comment]
> Same issue here, Joplin installed with: `wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash`
> 
> I could solve it by manually reverting #7346. I simply changed the Icon field to `joplin` in `~/.local/share/applications/appimagekit-joplin.desktop`, and after a few seconds I got my icon back (respecting my custom icon theme, which is Numix Circle).

Thanks, this solved it for me as well...

**Comment by Steve-Z** [comment]
Manually reverting from `"Icon": "@joplinapp-desktop"` to `"Icon": "joplin"` fixed this immediately for me as well. I do not understand why. I will leave it to developers, @laurent22 @roman-r-m, to explain the difference and why that seems to fix it.

**Comment by m1waterman88** [comment]
I'm still having this issue, and I'm on the latest release from the shell script.

**Comment by Steve-Z** [comment]
I used the workaround described above by me on Jan 5 and by @korg91 on Dec 27. I expect the issue has _not_ been permanently fixed because I am still on the same version as when I reported this: 2.9.17. That is the most up to date release version, yes?

**Comment by m1waterman88** [comment]
If I recall correctly, it was fixed but hasn't been released yet.

**Comment by koji-k** [comment]
Is this problem resolved?
I do not have a update yet.
