### ISSUE TITLE
Searching within a note crashes v2.10.2

### ISSUE THREAD

**Issue by annoyedhumanoid** [laurent22/joplin#7499]
## Environment

Joplin version: 2.10.2
Platform: macOS
OS specifics: Version 13.1

## Steps to reproduce

1. Open a note in the Markdown (not WYSIWYG) editor, in either of the layouts that include the editor (error occurs whether or not rendered note is visible, but the editor must be open)
2. Control/command + F to search text
3. Start typing something that can be found in the note
4. After typing several characters, Joplin encounters a fatal error — "Cannot read properties of null (reading 'removeChild')"

## Describe what you expected to happen

Expected to be able to search within note

## Logfile

[joplin error log.txt](https://github.com/laurent22/joplin/files/10265549/joplin.error.log.txt)

**Comment by msbentley** [comment]
I was just going to report this - my experience is two part:
- ctrl-f opens the search window, but does not move cursor focus to this field (it used to) with the side effect that I end up typing text into my note at the cursor location (potentially losing information and definitely screwing up the "last edited" meta-data)
- under some conditions I get the above error (I haven't managed to find exactly what triggers this in my case).

Platform and Joplin version the same as the OP

**Comment by laurent22** [comment]
Related to: https://github.com/laurent22/joplin/issues/7520
