### ISSUE TITLE
Let me sort the notes or change the order manually

### ISSUE THREAD

**Issue by okoetter** [laurent22/joplin#75]
### Operating system

- [x] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [x] Desktop
- [x] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---
I'd like to be able to sort the notes maybe by date of last change or alphabetically by title. Or let me sort the order of the notes manually.

**Comment by laurent22** [comment]
Duplicate of https://github.com/laurent22/joplin/issues/13
