### ISSUE TITLE
Android: Settings save button visible even when no settings have been changed

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#7503]
## Environment

Joplin version: 0527dbbdc2831add5b6ea4a607c8f3823850fde2
Platform: Android
OS specifics: Android 12

## Steps to reproduce

1. Open settings

## Describe what you expected to happen
The save button should be a "☑" icon, as it is on iOS when no settings have been changed.

## Notes

The "unsaved settings" are `["sync.maxConcurrentConnections", "net.proxyTimeout", "revisionService.ttlDays"]`. I'm not noticing this on the AppStore version of the iOS app.

I'm working on creating a confirmation dialog that prompts users to save unsaved changes. An accurate list of changed settings would be useful for this.

**Comment by laurent22** [comment]
Which actual version is it? 2.9.7? Because I'm not seeing this on it

**Comment by personalizedrefrigerator** [comment]
I haven't tested with an actual release yet. I was building from source on a branch based on https://github.com/laurent22/joplin/commit/0527dbbdc2831add5b6ea4a607c8f3823850fde2. I can test with the latest pre-release.

**Comment by personalizedrefrigerator** [comment]
I'm not noticing this in the 2.9.8 release, but I am noticing this in a build based on e3dc77357cc768f2e4f70e88f95c4ccf90934fd0 (fresh install for both). I've only tested it on Android, but it might happen on iOS, too.

**Comment by laurent22** [comment]
Thanks, let's tag it with "mobile" for now

**Comment by laurent22** [comment]
Have you been able to consistently replicate this? It's not happening for me on Android or iOS

**Comment by personalizedrefrigerator** [comment]
I'm still noticing this on Android, but not iOS. I haven't re-deployed from Android Studio recently, however, so I'll try doing that and see if it's fixed.

**Comment by personalizedrefrigerator** [comment]
> Have you been able to consistently replicate this? It's not happening for me on Android or iOS

I'm still noticing this on Android (I just re-deployed from Android Studio).

**Comment by laurent22** [comment]
Upstream issue: https://github.com/callstack/react-native-slider/issues/395
