### ISSUE TITLE
Sync fails in all devices after update to 2.9.17, error: "Last error: Error: Missing required property: type_:"

### ISSUE THREAD

**Issue by msartiano** [laurent22/joplin#7505]
**Info:**
I have been using Joplin for a long time. I do not manipulate Joplin notes manually, I do it exclusively via apps (Android, Windows, Mac).
A few days ago I updated to the latest version on Windows 10, when prompted by the app, to 2.9.17, from (if I remeber) 2.8.*.
I use Joplin on Android, Mac, WIndows, but only the Windows version was updated.
I self host a Joplin cloud server, version Joplin Server 2.10.3.

**Problem:**
Joplin stopped synching with all my devices. It fails when synching.
It also stopped working for friends with which I had folders shared with. These friends did not update Joplin, but both their and my Joplin cannot sync anymore.

**What I tried**
Windows 10: I created a new profile and reloaded Joplin notes. It worked initially then stopped again.
Android: Uninstall + reinstall of Joplin app, never worked again.
I searched and people had simila issues with the error you can read on the log below, and I deleted the last notes I created. This allowed me to sync initially, but then it stopped working again.

**Example of error:**
![image](https://user-images.githubusercontent.com/30049751/208793976-5f161632-fde9-40b8-a3a5-27d80e38d9b8.png)

## Environment

Joplin version: Mixed. Windows 10 2.9.17. Android latest? Mac 2.8.*.
Platform: All
OS specifics: No

## Steps to reproduce
I am unsure about steps to reproduce, but after updating the Windows App, the day after I faced issues.

## Describe what you expected to happen
Sync to work among devices.

## Logfile
```
Dec 21 01:42:50 2022-12-21 00:42:50: App: GET /api/ping (200) (0ms)
Dec 21 01:43:00 2022-12-21 00:43:00: App: GET /api/ping (200) (0ms)
Dec 21 01:43:09 2022-12-21 00:43:09: App: GET /api/items/root:/info.json:/content (200) (2ms)
Dec 21 01:43:09 2022-12-21 00:43:09: App: POST /api/locks (200) (2ms)
Dec 21 01:43:09 2022-12-21 00:43:09: App: GET /api/items/root:/4e0cf9fe19d04365b8721b283627d523.md: (200) (2ms)
Dec 21 01:43:09 2022-12-21 00:43:09: App: GET /api/items/root:/4e0cf9fe19d04365b8721b283627d523.md:/content (200) (6ms)
Dec 21 01:43:09 2022-12-21 00:43:09: [error] App: ::ffff:172.18.0.1 {
Dec 21 01:43:09 message: 'Missing required property: type_: ',
Dec 21 01:43:09 stack: 'Error: Missing required property: type_: \n' +
Dec 21 01:43:09 ' at Function.<anonymous> (/app/code/packages/lib/models/BaseItem.ts:504:28)\n' +
Dec 21 01:43:09 ' at Generator.next (<anonymous>)\n' +
Dec 21 01:43:09 ' at /app/code/packages/lib/models/BaseItem.js:8:71\n' +
Dec 21 01:43:09 ' at new Promise (<anonymous>)\n' +
Dec 21 01:43:09 ' at __awaiter (/app/code/packages/lib/models/BaseItem.js:4:12)\n' +
Dec 21 01:43:09 ' at Function.unserialize (/app/code/packages/lib/models/BaseItem.js:438:16)\n' +
Dec 21 01:43:09 ' at /app/code/packages/server/src/utils/joplinUtils.ts:97:18\n' +
Dec 21 01:43:09 ' at Generator.next (<anonymous>)\n' +
Dec 21 01:43:09 ' at /app/code/packages/server/dist/utils/joplinUtils.js:8:71\n' +
Dec 21 01:43:09 ' at new Promise (<anonymous>)'
Dec 21 01:43:09 }
```

**Comment by msartiano** [comment]
I'll add more info as I find them:

Possible steps to reproduce in Windows 10:
1. Create note with 2.8* or older App version.
2. Update to 2.9.*
3. change the previously created note.
4. Synching should fail.

If I delete the note that fails, synching works in Windows. It doesn't synch anymore with Android no matter what.
If I update a new note created after the Windows 10 App update, it synchs in Windows. Again in Android it continues not to synch.

**Comment by personalizedrefrigerator** [comment]
Possibly related to https://github.com/laurent22/joplin/issues/7479 . (Though it might be a different issue)

**Comment by dayue1984** [comment]
It seems that the version 2.10.2  fixed the problem, I have the same problem when using 2.9.17.
