### ISSUE TITLE
Joplin 2.9.17 stops running in MacOS

### ISSUE THREAD

**Issue by opewhi** [laurent22/joplin#7517]
## Environment

Joplin version: 2.9.17
Platform: MacOS
OS specifics:Ventura 13.0.1

## Steps to reproduce

1. Start Joplin
2. Do some clicks in the Notebooks panel
3. Application is frozen. It is possible to open the top menus, but nothing is working. Quit is not working. I have to force a kill through the activity monitor of the system.
 

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/10286217/log.txt)

thank you!

**Comment by laurent22** [comment]
This is probably because of a plugin. Which ones do you currently use? Also maybe try to disabled them one at a time to find out which one is causing this.

**Comment by opewhi** [comment]
thank you for your quick response, Laurent

this is the list of plugins I already have:

- [Automatic Backlinks to note ](https://github.com/laurent22/joplin/issues/7517#)v3.0.3
- [Combine notes ](https://github.com/laurent22/joplin/issues/7517#)v1.0.1
- [Favorites ](https://github.com/laurent22/joplin/issues/7517#)v1.3.0
- [Jira Issue ](https://github.com/laurent22/joplin/issues/7517#)v2.4.0
- [Link Graph UI ](https://github.com/laurent22/joplin/issues/7517#)v1.5.0
- [Math Mode ](https://github.com/laurent22/joplin/issues/7517#)v0.5.3
- [Metis ](https://github.com/laurent22/joplin/issues/7517#)v0.1.5 (disabled)
- [Note Link System ](https://github.com/laurent22/joplin/issues/7517#)v0.8.0
- [Note Tabs ](https://github.com/laurent22/joplin/issues/7517#)v1.4.0 (disabled)
- [Outline ](https://github.com/laurent22/joplin/issues/7517#)v1.5.3
- [Quick Links ](https://github.com/laurent22/joplin/issues/7517#)v1.2.3 (disabled)
- [Slash Commands: Datetime & More ](https://github.com/laurent22/joplin/issues/7517#)v1.3.2
- [Tagging ](https://github.com/laurent22/joplin/issues/7517#)v1.0.1
- [macOS theme ](https://github.com/laurent22/joplin/issues/7517#)v1.3.9

Could be that lately I have been playing around with _Note Link_... I will try your advise and disable one at a time.

**Comment by kamasylvia** [comment]
I have the same problem. Did you find what plugins are incompatible?

**Comment by laurent22** [comment]
Yes please @opewhi  let us know what plugin caused this. I’m going to start disabling plugins that freeze the app

**Comment by opewhi** [comment]
Sorry guys. I have been some days away from my computer and couldn't check
this. I will come back with my findings.

Meanwhile... Happy 2023!

**Comment by caressofsteel** [comment]
I had this issue when using the [macOS theme v1.3.11 ](https://github.com/andrejilderda/joplin-macos-native-theme) for Joplin Portable 2.9.17 on Windows 10. Once I disabled it Joplin was fine.

**Comment by opewhi** [comment]
thank you @caressofsteel for the hint

I can confirm that when I unable **macOS theme v1.3.9** the application doesn't crush.

to be more concrete, the crush was happening after starting Joplin and making some clicks in the left notebooks menu.
