### ISSUE TITLE
'Created at' attribute of a note is editable

### ISSUE THREAD

**Issue by rv602** [laurent22/joplin#7518]
When you open a note in the desktop app of Joplin, you get an ```info``` button at the top right corner

![image](https://user-images.githubusercontent.com/92572013/209120366-1e21c712-520b-4cd0-8e65-94e3712fdd71.png)

Once the info panel opens, there are few attributes of the notes displayed. In that there are 2 attributes, namely ```Created at``` and ```Last Edited at```.

The ```Created at``` date is editable, which shouldn’t be the case according to me. Although it's auto generated initially, it is editable to such an extent that you can set it to a future date which seems illogical.
Also the ```Last edited``` should not be editable as it may cause confusion

![image](https://user-images.githubusercontent.com/92572013/209121358-18a1e5f7-d400-49d5-9634-f21346107493.png)

## Environment

Joplin version: 2.9.17 (prod, darwin)
Platform: MacOS
OS specifics: M1 2020

## Steps to reproduce

1. Launch Joplin desktop app
2. Create a new sample note
3. Go to the info section of a note and try editing the ```created``` and ```edited``` attributes

## Describe what you expected to happen
According to me, both the ```created``` and ```edited``` attributes shouldn't be editable, as stated above.

**Comment by KunalSin9h** [comment]
yes i also think so. 
createAt date should not be mutable.

**Comment by ghost** [comment]
I don't agree. I use these features to change the sorting of my notes sometimes.
Why shouldn't a user have the right to change what he wants? It's HIS notes, after all.

**Comment by Daeraxa** [comment]
It should absolutely be editable. Like what if I created a note on my computer 3 years ago in a different app and needed Joplin to reflect that?

**Comment by tomasz1986** [comment]
There are probably multiple ways to look at this one, I think. For example, there's a reason why operating systems normally don't allow to edit file timestamps, or at least not easily through the GUI. Also, it probably doesn't matter if you can edit those dates when you're the only user of the application, but when doing collaborative work, it's usually best not to mess around with them and let the application handle everything by itself…

**Comment by roman-r-m** [comment]
In fact it's not even `created_time` that you're editing, it's `user_created_time`. It's initialised to be the same as `created_time` but then the user can modify it. And `created_time` remains unchanged.
The same goes for `updated_time`/`user_updated_time`
