### ISSUE TITLE
Android (2.9.8) beta editor, line breaks in nested to-dos are buggy

### ISSUE THREAD

**Issue by AngelCrawford** [laurent22/joplin#7519]
A nested to-do will be missing a to-do box after hitting the enter button on the keyboard. On other times hitting enter will move the current line one down and create an empty line between. See video for it to happen.

## Environment
Joplin version: 2.9.8
Platform: Android
OS specifics: 13 (installed over .apk)

Enabled the new beta editor for Joplin in the settings.

## Steps to reproduce
1. Create a note, start with first to-do item
2. Hit enter for next line, nest the to-do with four spaces, hit enter again
3. Repeat nesting and hitting enter

## Describe what you expected to happen
I would like to see a to-do box appear on the same indent as before hitting enter button.

https://user-images.githubusercontent.com/16148683/209139416-0926da6c-d1b8-4e17-9c8f-e671aef8dd94.mp4

**Comment by personalizedrefrigerator** [comment]
I can reproduce this with both bulleted and task lists. List continuation is implemented [by CodeMirror](https://github.com/codemirror/lang-markdown/pull/2). I plan to open an issue upstream later today ([upstream bug-tracker](https://github.com/codemirror/dev/issues)).

**Comment by personalizedrefrigerator** [comment]
It looks like an [upstream issue already exists](https://github.com/codemirror/dev/issues/987) and the issue should be fixable by updating CodeMirror's lang-markdown package, if it hasn't been updated already.

**Comment by personalizedrefrigerator** [comment]
It's working for me in the [TestFlight version of Joplin](https://discourse.joplinapp.org/t/ios-pre-release-2-10-is-now-available-updated-29-dec/28848/2), which has a newer version of CodeMirror.
