### ISSUE TITLE
Search field doesn't get focus when pressing Ctrl+F

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#7520]
macOS, 2.10.2

When pressing Ctrl+F in Markdown editor, the search field doesn't get focus

**Comment by betty-alagwu** [comment]
Hello @laurent22 . I hope you are well. 

I'm a first time contributor, and have spent some time getting familiar with Joplin. I would love to be assigned this issue if possible, and have availability to work on it immediately. Thank you very much.

**Comment by laurent22** [comment]
We don't assign issues but feel free to work on it, as it's unlikely anyone else picked it up.

**Comment by betty-alagwu** [comment]
Alright thank you working on it.
