### ISSUE TITLE
Exported Mermaid graphs as PNG are incredibly small

### ISSUE THREAD

**Issue by iRomanyshyn** [laurent22/joplin#7521]
I don't know when it started. Maybe, a couple of weeks ago. Joplin on Ubuntu started making Mermaid renders very small in size if I export them as PNG.

## Environment

Joplin version: 2.9.17
Platform: Ubuntu 22.04

## Steps to reproduce

1. Paste the code:
```mermaid
flowchart TD;

b ===> a
b === c
c -...- |Test| b
d & e & f --- b

subgraph "A"
	a
	d
	e
	f
	b
end
```
```
flowchart TD;

b ===> a
b === c
c -...- |Test| b
d & e & f --- b

subgraph "A"
	a
	d
	e
	f
	b
end
```
2. Click the right mouse button on the rendered image and save it somewhere as PNG.
3. Check the PNG file size. It will be 4.5kB which is catastrophically small to distinguish anything from there.

## Describe what you expected to happen
Expected to have a bigger image than this.
![mermaid-1671722589364](https://user-images.githubusercontent.com/11888301/209172461-bc4331ee-4cab-4156-b21b-1f76b5ad1f65.png)

**Comment by tessus** [comment]
One more thing for me to add to my Mermaid tests: exporting to png/svg.

I am sorry that I missed this. I totally forgot about this feature.

Update: Although I doubt it's Mermaid, b/c exporting to PNG is not done with Mermaid.

**Comment by adarsh-sgh** [comment]
`Save as png` option converts svg code of the image into png and saves it.

Svg Images have a [viewBox](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox) attribute, we can use it to define width and height of the image we will be saving as png.
e.g. the mermaid in first comment of this diagram has svg: 
```html
<svg viewBox="-8 -8 258.080078125 446" ...
```

so setting png dimensions to 258 * 446 we get following png image
![afterChange](https://user-images.githubusercontent.com/63918341/209528158-88eba96e-e19d-48d3-9721-98df4a746340.png)

Should I open A PR with these changes ?

**Comment by tessus** [comment]
Yes, I think that would make sense. Please do.

P.S.: If the origin point is negative, doesn't it mean we should add those values ABS(x, y) numbers to x' and y'.

e.g. for this image 266x454

**Comment by adarsh-sgh** [comment]
> If the origin point is negative, doesn't it mean we should add those values ABS(x, y) numbers to x' and y'.

I think the size of image would remain same regardless of origin changes so we need not add it to width and height.
following image has first two parameter of viewBox as -50 but still it has same dimensions as original image.

<img width="276" alt="image" src="https://user-images.githubusercontent.com/63918341/209573618-1c261244-a50d-4dcf-8d69-7ae4590976f3.png">
 viewBox is drawn with red
