### ISSUE TITLE
iOS: Joplin keeps creating new note with previously shared photo when re-launching

### ISSUE THREAD

**Issue by weimingqing** [laurent22/joplin#7523]
## Environment

Joplin version: 12.9.2
Platform: iOS
OS specifics: iOS 16.2

## Steps to reproduce

1. Open a photo and choose "Share", choose "Joplin"
2. A new note with the photo is created (expected)
3. Now, whenever joplin is killed in background by iOS or manually killed by me, when launching joplin again, it will always recreate a new note with the photo as shared in step 1

## Describe what you expected to happen

No new note should be created when joplin is killed and re-launched

## Logfile

```
12-23T10:31:41: "Got lat/long"
12-23T10:31:41: "Updating lat/long of note
22994de48a38464b9fe6183187476ed"
12-23T10:31:40: "Fetching geolocation..
12-23T10:31:40: "Original dimensions " "{"width":780,"height" :1060}"
12-23T10:31:40: "Got file: file:///private/var/mobile/Containers/Shared/ AppGroup/33499051-44BF-4B44-8443-B745973229E0/IMG1993.JPG"
12-23T10:31:40: "Got type: image/jpeg"
12-23T10:31:40: "about to attach resource
{"name":"IMG_1993.JPG" "mimeType":"image/jpeg" "uri":"file:///private/var/ mobile/Containers/Shared/AppGroup/33499051-44BF-4B44-8443-
B745973229E0/IMG_1993.JPG"}"
12-23T10:31:40: "Received shared data"
12-23T10:31:40: "ResourceFetcher: Auto-added resources: O"
12-23T10:31:40: RevisionService: "runInBackground: Starting background service with revision collection interval 30000"
12-23T10:31:40: "Application initialized"
12-23T10:31:40: "ResourceFetcher: Auto-add resources: Mode: always"
12-23T10:31:40: "Sync target: 9"
12-23T10:31:40: e2ee/utils: "Trying to load 0 master keys.."
12-23T10:31:40: e2ee/utils: "Loaded master kevs: O"
12-23T10:31:40: "Loading folders..
!
12-23T10:31:40: "PluginAssetsLoader: Assets are up to date. Hash: abde4aa0d82375ca24be9dde8c971a"
12-23T10:31:40: "Client ID: 2561a5a3d6d45528749c83596082f6f"
12-23T10:31:40: models/Setting: "Applying default migrations..
12-23T10:31:40: e2ee/utils: "Trying to load 0 master keys...
12-23T10:31:40: e2ee/utils: "Loaded master keys: O"
12-23T10:31:40: e2ee/utils: "Master password is not set - trying to get it from the active master key..
12-23T10:31:40: "KeychainService: checking if keychain supported"
12-23T10:31:40: "Keychain Service: check was already done - skipping.
Supported:" "O"
12-23T10:31:40: "Database is ready."
12-23T10:31:40: "Loading settings..."
12-23T10:31:40: "Current database version"
"{"version" :41,"table_fields_version":41}"
12-23T10:31:40: "Upgrading database from version 41"
12-23T10:31:40: "New version: 41. Previous recorded version: 41"
12-23T10:31:40: "Database was open successfully"
12-23T10:31:40: "Checking for database schema update..."
12-23T10:31:40: "Starting application net.cozic.joplin-mobile V12.9.2 (prod)"
12-23T10:31:40: "===================================="
```

**Comment by personalizedrefrigerator** [comment]
I can reproduce this. It also happens with shared text.

**Comment by kaztela** [comment]
Same here unfortunately.

**Comment by unixnation** [comment]
I'm also seeing this with a shared URL from a browser app - which I guess is essentially the same as shared text.

Joplin 12.9.2
iOS 15.7.2

**Comment by ethanxrosen** [comment]
Also experiencing this

**Comment by fgrove** [comment]
Same here on iOS and iPadOS

**Comment by ghost** [comment]
I'm experiencing this bug as well, in a similar manner as explained by others. 

![image](https://user-images.githubusercontent.com/123326084/214656001-b0dbaa75-9cfe-40f9-8033-a22f4ab43007.png)

**Comment by zhaobozb** [comment]
Same here on iOS and iPadOS

**Comment by cuibonobo** [comment]
This is still an issue in version 12.9.2 of the iOS app.

**Comment by fgrove** [comment]
I can confirm that. Also in same version of iPadOS app.

**Comment by personalizedrefrigerator** [comment]
It seems to be fixed in the [TestFlight release](https://discourse.joplinapp.org/t/ios-pre-release-2-10-is-now-available-updated-29-dec/28848) (iOS 16.3.1, Joplin 12.10.4).

**Comment by ghost** [comment]
The most recent test version in TestFlight DOES correct the issue mentioned here (at least it has for me). I'm not sure if that version has gone public yet.

**Comment by personalizedrefrigerator** [comment]
I think the relevant commit is https://github.com/laurent22/joplin/commit/b8e4150bfd6e20414b92b4853e494eb0d976b8c7

**Comment by weimingqing** [comment]
Yes, confirmed this issue has been fixed in new version.
