### ISSUE TITLE
Joplin Cloud rendering changed

### ISSUE THREAD

**Issue by danlhenry** [laurent22/joplin#7525]
Joplin Cloud's rendering of a note I published has changed where it's showing a massive 5.5"x5.5" "J" logo and the body has no left margin. Rendering was "normal" a few days ago when I'd check with a browser.

![image](https://user-images.githubusercontent.com/8107951/209411281-00db4ef8-10cc-4b9b-80f9-3c57686da7fe.png)

It's the same for Firefox, Edge, Chrome. I made an innocuous edit so the note would re-synchronize and the rendering problem does not change.

## Environment

Joplin 2.9.17 (prod, win32)

Client ID: 770808a881e541d2b4f3f4e1c4ab708e
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: a84a8e7

## Steps to reproduce
[Link to the shared note where I'm observing this](https://f1lpsixhdp.joplinusercontent.com/shares/dGNz8pBNCXgKCjrtQd0jCk)

**Comment by personalizedrefrigerator** [comment]
# Temporary workaround to make things look slightly better:

Adding the following to the published note should hide the large Joplin logo.
```html
<style>
nav.navbar {
    display: none;
}
</style>
```

# What I think is happening...
I'm seeing [`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://joplincloud.com/css/main.css. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://joplinapp.org’)`](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSAllowOriginNotMatchingOrigin) in the browser console. I think a dependency upgrade probably changed the CORS (Cross-Origin Resource Sharing) headers for `https://joplincloud.com/css/main.css` (and similar CSS files), and so `*.joplinusercontent.com/*` no longer has access to these CSS files.

**Comment by laurent22** [comment]
Yes this is correct, an upgrade to the CORS package caused this and that should be fixed later today on Joplin Cloud. Thanks for reporting this!
