### ISSUE TITLE
Cannot change the behavior of the Alt key when pressed alone in the keyboard shortcut change settings

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#7530]
## Environment

Joplin version: 2.8.8
Platform: Desktop
OS specifics: Linux

## Steps to reproduce

1. When I edit text, I press the Alt key.
2. The cursor is focused on the top menu.

This behavior cannot be changed in the settings.
When typing Japanese on a US ANSI layout keyboard, you usually use Alt + ` to toggle the IME on and off.
The current behavior of Joplin interferes with the IME on/off shortcut key, which interferes with Japanese input.

**Comment by artemgur** [comment]
The issue is not fixed, the problem still exists
