### ISSUE TITLE
Can’t synchronize with Nextcloud / WebDAV, 404 MKCOL error

### ISSUE THREAD

**Issue by Starcr0ss** [laurent22/joplin#7533]
Version: 2.9.17 (Linux), 2.8.1 (Android)
OSes: Arch Linux, Android 11
When trying to sync to my Nextcloud server on both the desktop app and Android, I get the following error:
```
Error: Could not upgrade from version 0 to version 1: 
MKCOL .resource/: Unknown error 2 (404): 
<!DOCTYPE html> <html lang="en"> <head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <meta http-equiv="X-UA-Compatible" content="ie=edge"> <title>Page Not Found</title> <style type="text/css"> body { background-color: #f5f5f5; margin-top: 8%; color: #5d5d5d; font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Robo
```
I am syncing to the following link (except with my domain): `(domain)/remote.php/webdav/joplin`
and I have created a Joplin folder at the root of my Nextcloud files. How do I make Joplin sync to my Nextcloud server? Do I have to change the permissions of something through my server?
I have even tried to create a file titled ".resource" and a folder titled ".resource" within Hestia Control Panel and Joplin still gives this 404 error. 
I'd also like to note, Joplin does not automatically create anything related to ".resource" within my Nextcloud Joplin directory.
Any help is greatly appreciated!

**Comment by roman-r-m** [comment]
Are you sure the URL is right? Even something small like "Joplin" vs "joplin" could cause this.

**Comment by ericswpark** [comment]
It's not a bug, you've specified an incorrect URL. Nextcloud has a WebDAV URL of `example.com/remote.php/dav/files/<username>/path/to/dir`.

**Comment by Starcr0ss** [comment]
> Are you sure the URL is right? Even something small like "Joplin" vs "joplin" could cause this.

@roman-r-m I tried both spellings of folders in my Nextcloud, my Joplin folder is "/joplin" lowercase.

**Comment by Starcr0ss** [comment]
> It's not a bug, you've specified an incorrect URL. Nextcloud has a WebDAV URL of `example.com/remote.php/dav/files/<username>/path/to/dir`.

@ericswpark Just tried to use the following path to no success
`https://nextcloud.example.com/remote.php/dav/files/serena/joplin`
Same exact error.

**Comment by ericswpark** [comment]
@Starcr0ss curious, what happens when you navigate to that link in the browser? You should get the following message:

This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client.

If you get this screen instead then you have the wrong URL:

![5488A46C-353B-4723-92C2-EAEE0787BD7B](https://user-images.githubusercontent.com/13326074/209475444-0bf2479c-ce39-46b1-ae96-56aa9cd08a6b.jpeg)

**Comment by roman-r-m** [comment]
@Starcr0ss you should be able to find the URL from the Nextcloud web UI.
Just open the folder and the URL will be in the lower left corner.

See this random screenshot I found online:
https://www.hosting.de/blog/mit-joplin-notizen-erstellen-und-mit-nextcloud-synchronisieren/screenshots/nextcloud_webdav_url.png

**Comment by Starcr0ss** [comment]
@ericswpark I do indeed get the

> This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client.

message.

**Comment by Starcr0ss** [comment]
@roman-r-m I used the link from my desktop Nextcloud files app, adding "/joplin" to the end of that link and nothing has changed. Still have that 404 error coming up.

**Comment by roman-r-m** [comment]
I'm out of ideas tbh.

Not sure if nextcloud has any useful logs you could check.

In this situation I'd probably just use tcpdump + wireshark to look at what is being sent from Joplin.

Is there a proxy between Joplin and your nextcloud btw?

**Comment by Starcr0ss** [comment]
@roman-r-m How would I do that with Wireshark? I really am not familiar with that program.
Also, I don't have any proxy that I know of? Only thing related to proxies on my server is that I have nginx which Hestia CP calls my "reverse proxy".

**Comment by Heart1010** [comment]
> @roman-r-m How would I do that with Wireshark? I really am not familiar with that program. Also, I don't have any proxy that I know of? Only thing related to proxies on my server is that I have nginx which Hestia CP calls my "reverse proxy".

Did you find a solution for that? (also using HestiaCP)

Edit: Found the solution in my case - see my answer in the forum => https://discourse.joplinapp.org/t/nexctcloud-sync-error/34179
