### ISSUE TITLE
Visual anomalies in editor when using Folding in plugin.

### ISSUE THREAD

**Issue by eagleofnorth** [laurent22/joplin#7540]
Joplin for desktop 2.9.17 (prod, darwin) [Mac]
OS: macOS Ventura 13.1 (M1)
Plugin: Folding in Code Mirror Editor v2.0.1

Issue is only there when the "Folding in" (mentioned above) is active.

Please see image below, editor panel to "see" the missing text.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/17335622/209644184-18384d76-7ffb-4a8c-a0bf-76141f584d09.png">

**Comment by JackGruber** [comment]
This is a problem with the plugin, not Joplin. 
I mean in this topic also a workaround was mentioned.
https://discourse.joplinapp.org/t/persistent-text-folding-in-editor/16183/46

**Comment by eagleofnorth** [comment]
Thanks, @JackGruber. The workaround seems to work as expected.

**Comment by eagleofnorth** [comment]
Bug in plugin, not Joplin.
