### ISSUE TITLE
Won't Decrypt Notes

### ISSUE THREAD

**Issue by Curtis-Mortensen** [laurent22/joplin#7550]
## Environment

Joplin version: 2.9.17
Platform: Linux
OS specifics: Ubuntu 22

## Steps to reproduce
1. Download Joplin
2. Configure OneDrive sync
3. Enter master password

## Describe what you expected to happen
It would download and decrypt notes at the same time. Instead it just downloaded them all and never decrypted. 

## Logfile

[syncReport-1672285863772.csv](https://github.com/laurent22/joplin/files/10317476/syncReport-1672285863772.csv)

![Screenshot from 2022-12-28 19-16-59](https://user-images.githubusercontent.com/56660391/209900972-818fc5df-12da-4d8a-b37d-47a1185b3fb4.png)
![Screenshot from 2022-12-28 20-51-01](https://user-images.githubusercontent.com/56660391/209901082-a24e0a6b-8fd8-4b17-9412-7f1f6efd49c7.png)
![Screenshot from 2022-12-28 20-50-51](https://user-images.githubusercontent.com/56660391/209901088-9918c85e-b8da-4c87-a5fb-562d56607503.png)
![Screenshot from 2022-12-28 20-51-40](https://user-images.githubusercontent.com/56660391/209901129-155349dc-9ebf-4bd5-a751-ecce6e757021.png)

**Comment by vanshdeepsingh-coder** [comment]
Hi if anyone is not working on this please assign it to me

**Comment by laurent22** [comment]
There's a message that says "Decrypting items: x/y", so isn't it just a matter of waiting for everything to be decrypted?
