### ISSUE TITLE
Unable to install Joplin via the wget method on Pop_os

### ISSUE THREAD

**Issue by VBtheFirbolg** [laurent22/joplin#7552]
## Environment

Joplin version: 2.9.17
Platform: Linux
OS specifics: Pop_os

## Steps to reproduce

1. Enter `wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash` into a terminal to install Joplin

## Describe what you expected to happen
The program must ideally get installed

## What happened
I get the following message:
```
--2022-12-29 23:49:56--  https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 202.83.21.14
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|202.83.21.14|:443... connected.
OpenSSL: error:0A0003E8:SSL routines::reason(1000)
Unable to establish SSL connection.
```

**Comment by CalebJohn** [comment]
This appears to be an issue pulling the file from GitHub. Can you try again and report back if it works?

**Comment by VBtheFirbolg** [comment]
I did try again now, got the same output

**Comment by CalebJohn** [comment]
There is some issue on your computer. Maybe SSL versions are out of date? Unfortunately, I can't help you troubleshoot that.

I recommend you just download the appimage using your browser.

https://github.com/laurent22/joplin/releases/tag/v2.9.17

**Comment by VBtheFirbolg** [comment]
I did realise this. I could download Joplin using the `wget` method from a different ISP, of all things. Though I understand that this is not a problem with Joplin, could you point me to someplace where I can try and fix this problem? For starters, I don't even know how to frame it.

**Comment by laurent22** [comment]
`OpenSSL: error:0A0003E8` returns a few results, so you could start there
