### ISSUE TITLE
Move into the Joplin organization

### ISSUE THREAD

**Issue by Neustradamus** [laurent22/joplin#7558]
Dear @joplin team, @laurent22,

Currently there is a problem, an historical problem!

It will be better to tranfer https://github.com/laurent22/joplin into https://github.com/joplin.

Doc :
- https://help.github.com/en/articles/transferring-a-repository

Do you want help?

I have already done with success!

Thanks in advance.

Regards,

Neustradamus

**Comment by Daeraxa** [comment]
What problem? What does it solve? How is this a bug?

**Comment by Neustradamus** [comment]
All at the same place will be better, the Joplin place is https://github.com/joplin.

**Comment by Daeraxa** [comment]
Yes I'm aware, but better how?

**Comment by Neustradamus** [comment]
@laurent22: It has not been done...

**Comment by Neustradamus** [comment]
@laurent22: Can you reopen it?

**Comment by Daeraxa** [comment]
No. You didn't even answer my question.

**Comment by Neustradamus** [comment]
You can see here docs:
- https://docs.github.com/organizations

You can see, for example:
- https://github.com/Debian
- https://github.com/GNOME
- https://github.com/KDE
- https://github.com/apple
- https://github.com/microsoft
- ...

**Comment by Neustradamus** [comment]
@Daeraxa:
- Pulsar: https://github.com/pulsar-edit

**Comment by Daeraxa** [comment]
I don't understand, yes those are links to organisations. Yes, we are fully aware of what an organisation is. I'm asking what benefit that gives us. This will not be re-opened.

1) It is not a bug, you selected the option to report a bug or reproducible issue. This is neither so even if this is something we wanted to do, this is not the correct place for it. This would be a discussion on the forum.
![image](https://user-images.githubusercontent.com/58074586/215607018-fdf6a548-4820-457d-815e-23de3324c596.png)

2) What benefits would this provide that we are currently missing out on that we need? Considering we would have to change all of the places that links to this in the code, not to mention invalidating all of the links out there on the internet. I've asked twice and you haven't provided this either time.

If you want to continue this conversation then please open a topic on the forum where it can be discussed although I very much doubt there is much, if any appetite, to move the repo to a different org.
