### ISSUE TITLE
Text previously highlighted from searching in note remains highlighted

### ISSUE THREAD

**Issue by annoyedhumanoid** [laurent22/joplin#7565]
## Environment

Joplin version: 2.10.2, 2.10.3
Platform: macOS
OS specifics: 13.1

## Steps to reproduce

1. Open a note in markdown (not WYSIWYG) editor with the layout set to include the editor
2. Control/command + F to search text
3. Search for something specific enough as to have only one result in the note (e.g., "hello")
4. Edit that one result in the note so that it no longer matches the input search (e.g., to "he.llo")

Rather than there being no highlighted text (since there are no longer any strings in the note that match the search), highlighted text appears as if the input search has been trimmed to a few characters (e.g., from "hello" to "he"). This highlighted text then remains until restart, unaffected by clearing the search field or by closing search, and even applies to other notes upon switching. Searching anew only adds more highlighted text without erasing the previous (see second image).

<img width="459" alt="rendered Markdown showing the string 'th' highlighted with nothing in the find bar" src="https://user-images.githubusercontent.com/46287328/210164093-0d265fc0-543a-4c14-b658-2f68767d1b0b.png">
<img width="481" alt="rendered Markdown showing the string 'th' highlighted despite 'a' in the find bar" src="https://user-images.githubusercontent.com/46287328/210164094-303eb82b-5567-46e0-8ccd-0981213508ba.png">

**Comment by solo-daemon** [comment]
@laurent22 can you please assign me this issue?

**Comment by JackGruber** [comment]
We don't assign issues. But feel free to work on it.

**Comment by laurent22** [comment]
And GSoC is not started

**Comment by laurent22** [comment]
I can't replicate this. When it happens @annoyedhumanoid, is there any error in the console? joplinapp.org/debugging

Also please provide the note you are testing with as a JEX file

**Comment by LightAPIs** [comment]
I can completely reproduce this issue (and #7499) when using some [IME](https://developer.mozilla.org/en-US/docs/Glossary/Input_method_editor) input method. To illustrate, I built the application(dc5dc94), and add following code to the  [useEditorSearch.ts#L157](https://github.com/laurent22/joplin/blob/dc5dc94ed56eb5782fc5d61c42b406e229027775/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useEditorSearch.ts#L157) to print kwywords in the console.

```ts
export default function useEditorSearch(CodeMirror: any) {
  // ...
  CodeMirror.defineExtension('setMarkers', function(keywords: any, options: any) {
    // ...
    if (keywords[0].value === previousKeywordValue) return nMatches;
    logger.info(`keywords[0].value: "${keywords[0].value}"`); // Print keywords
  }
}
```

---

Here are two kinds of input methods repetition error screenshot:

1. Input mode 1

![inline](https://gcore.jsdelivr.net/gh/LightAPIs/PicGoImg@master/img/202301190025372.gif)

The reason for the error: `"新"`, `"新w"` and `"新版"`, `"新版d"` are passed in at extremely short intervals.

2. Input mode 2(This input method will insert a space in the input box in advance)

![preedit](https://gcore.jsdelivr.net/gh/LightAPIs/PicGoImg@master/img/202301190032448.gif)

The reason for the error: similar to above, `"新"`, `"新 "` and `"新版"`, `"新版 "` are passed in at extremely short intervals().

---

Secondly, I tested that I can handle this situation after adding `debounce`.
