### ISSUE TITLE
Plugins(draw.io,plantuml2,kity-mindmap) do not work on Mac

### ISSUE THREAD

**Issue by linckerr** [laurent22/joplin#7569]
I am asking a support for using the plugins on my Joplin. I am not sure it is a bug or whatever.

**What is the problem?**

After downloading and turning on the plugins(draw.io, plantuml2, kity-mindmap),they do not work. 

As the pics shows:

- There is no a _draw.io_ button in the _Tools_
- The plantuml syntax can not be rendered

Other plugins such as Day Review and History Panel, however, work well.

**The Environment Information**

Version: Joplin 2.9.17
Platform: Mac OS

**The Pics Of The Problem**

![WechatIMG137](https://user-images.githubusercontent.com/32325484/210264489-f972076f-4612-47a2-be10-86700bd9b5b4.png)
![WechatIMG138](https://user-images.githubusercontent.com/32325484/210264505-6544de60-acdf-41f2-be46-a9d1cebc114c.png)

**Comment by linckerr** [comment]
**Update**：When I uninstall version 2.9.17 and then change to older version 2.7.15, it works.

Believe that 2.9.17 version has some bug with those plugins.

**Comment by personalizedrefrigerator** [comment]
[Corresponding issue in the draw.io repository](https://github.com/marc0l92/joplin-plugin-drawio/issues/17).

**Comment by laurent22** [comment]
Fixed in a43ce33adfd2986689f0dd2d2f6ace294c371104

**Comment by laurent22** [comment]
If you have an issue with a plugin not loading please download pre-release 2.10. Unfortunately I won't backport the fixes to 2.9 because the transition between both is heavy due to all the dependencies that have been upgraded.

**Comment by mthii** [comment]
Using Joplin-2.10.4.AppImage on linux, I don't have no draw.io menu. But after creating the joplin-drawio-plugin under tmp dir, it works. Does this issue comming from the same problem ? Fix already ?
