### ISSUE TITLE
iOS: typing caret is misaligned

### ISSUE THREAD

**Issue by B0BIC** [laurent22/joplin#7572]
## Environment

Joplin version: All versions, though I am using 12.10.1.
Platform: iPhone X
OS specifics: iOS 16.2

## Steps to reproduce

1. Open any note
2. Type enough lines that the caret should bump down by itself.

<img src="https://user-images.githubusercontent.com/3453126/210281360-c50d43ce-7b4a-45b6-973c-d88ccf7eaa4a.PNG" alt="IMG_8051.PNG" width="250" height="542">

<img src="https://user-images.githubusercontent.com/3453126/210281363-77ec7a41-f4c2-4f22-8f83-b37a2f40b031.PNG" alt="IMG_8051.PNG" width="250" height="542">

Note that turning off/on predictive text does not change the issue.

## Describe what you expected to happen

I expected there to be a little buffer between the typing caret and the keyboard which remains or is even "triggered" by inputting text at a certain line, as is common in other environments.

**Comment by personalizedrefrigerator** [comment]
[Consider enabling the beta editor (settings > opt-in to the beta editor).](https://github.com/laurent22/joplin/issues/6837#issuecomment-1247115456)

See also https://github.com/laurent22/joplin/issues/6868

**Comment by B0BIC** [comment]
I did, but now spell check isn’t working.

**Comment by jatinsahijwani** [comment]
i want to solve this bug.please assign it to me
