### ISSUE TITLE
Sidebars are not collapsable in desktop app - Mac

### ISSUE THREAD

**Issue by rv602** [laurent22/joplin#7573]
When you open a note in the desktop app of Joplin, you get 2 sidebars, as labelled below

![image](https://user-images.githubusercontent.com/92572013/210355947-66ce3cb4-b06c-4d28-8b43-1249ce6762d7.png)

These 2 sidebars aren't collapsable, which may cause a bit of annoyance as I feel there are times when we would prefer to just collapse/hide them and focus on reading the notes

## Environment
Joplin version: 2.9.17 (prod, darwin)
Platform: MacOS
OS specifics: M1 2020

## Describe what you expected to happen
I expect for a button to be present, which will either hide/collapse or make the sidebar visible, according to it's respective state.

**Comment by Daeraxa** [comment]
Does F10 and F11 not work on mac? Should also be in the view menu.

**Comment by rv602** [comment]
F10 and F11 doesn’t work. Although it is there in the View Menu I think it would be convenient to have a toggle kind of thing as a switch/button as well. Or even key binding it with F10, F11 works.

**Comment by annoyedhumanoid** [comment]
I believe the keyboard shortcuts are `command + option + S` for sidebar and `command + option + L` for note list

**Comment by Daeraxa** [comment]
Yeah I would check the keybindings, it seems odd if they don't work at all I just don't remember what they are on mac.

**Comment by rv602** [comment]
The keybindings stated by @annoyedhumanoid works fine.
Although @Daeraxa I still do think a hamburger menu/toggle switch would be much more user friendly.

**Comment by rv602** [comment]
@Daeraxa can I work on this, I feel making a hamburger menu/toggle switch for collapsing the sidebars would be more intuitive and user friendly.

**Comment by Daeraxa** [comment]
Ideally it should be discussed in the forum first to see if it is something we actually want to add.

**Comment by rv602** [comment]
alright, thanks.

**Comment by laurent22** [comment]
Also see rule 1 here - https://github.com/laurent22/joplin/blob/dev/readme/gsoc2022/pull_request_guidelines.md
