### ISSUE TITLE
Auto sync on start should observe user setting

### ISSUE THREAD

**Issue by XilinJia** [laurent22/joplin#7574]
On every start of Joplin, it performs a sync (in my case, I set the sync to file system).  Despite that I set sync interval to "Disabled".

I am not sure if this is intended or a bug.  But is does contradict with sync interval being "Disabled", which should mean never auto sync, correct?  

Normally, this has not been a big issue for me in the past, but now that I have Joplin running on Android 13, the sync of about 100 notes (over 3000 Joplin files though) takes about 2 minutes on a high-end phone like Galaxy S21.  If I set Joplin as unrestricted, then it never needs restarted (unless I kick it out), and this is not a problem.  Otherwise, the sync behavior at start is unbearable.

## Environment

Joplin version: 2.10.2, 2.9.17
Platform: Android, Linux
OS specifics: Android 13, Ubuntu 22.04

## Steps to reproduce

1.  kill Joplin
2. restart Joplin
3. 

## Describe what you expected to happen
If sync interval set to "Disabled", it should not perform the sync

So if it's agreed, I'd like to take this issue.

**Comment by laurent22** [comment]
If you don't want to sync, you can set the target to None.

Everything else is as designed - the sync algorithm requires frequent sync to keep things working and avoid conflicts. And no we won't add options to change this

**Comment by wh201906** [comment]
Hi. Would you like to try the new apk from @jd1378? 
https://github.com/laurent22/joplin/issues/6942#issuecomment-1399041159
There are some improvements for the performance. I wonder how fast it is in your case.
