### ISSUE TITLE
Android 13: Filesystem sync error (syncthing)

### ISSUE THREAD

**Issue by andreasio** [laurent22/joplin#7576]
## Environment

Joplin version:  2.8.1
Platform: Android
OS specifics: Android 13 + Samsung ONE UI

## Steps to reproduce

1.  On Linux (in this case) install joplin
2.  Save files to a syncthing folder
3.  On android install joplin from playstore
4.  On android specify sync + filesystem + path to the syncthing folder
5. Sync items.
6.  Notice sync error: Could note upgrade from version 0 to version 1: Error: File '/storage/emulated/0/Documents/..../.sync/version.txt` does not exists
7. Go til file manager, conform that said file actually does exists. Its content is "2". Readme in the same directory however says that version number is sotres in "info.json". "info.json" does not exists
8. Joplin configuration states that the following permissions are needed: Storage, Camera and location. In androud 13 it seems that "storage" is not an option. I have granted Joplin the following persionsion: "Music and audio" ; "Photos and videos". Not allowed are: "Camera", "Location" and "notifications".
9. I have search for simular issues here. I found 6779, 5773, 5779 - but still I experience the above.

## Describe what you expected to happen
Sync succesful (the same way Obsidian can do)

## Logfile
I am not completely sure what the logfile I generated contain - so I prefer not to share it on a public site. I created both an interactive bug report (was nothing interactive about it thoug) and a full report. Its a big zip file.  Not sure I did it correctly.

**Comment by Daeraxa** [comment]
> Joplin version: 2.8.1

This is before the file system fix. If you need it then you should upgrade to the new one but unfortunately it isn't on the play store. https://discourse.joplinapp.org/t/whats-new-in-joplin-2-9/28661/3#fixed-filesystem-sync-on-mobile-7

**Comment by andreasio** [comment]
Thank you! It works with 2.9.8 - sorry for the confusion.
