### ISSUE TITLE
Security : password in SQLITE are not hashed

### ISSUE THREAD

**Issue by Ravinou** [laurent22/joplin#7578]
I wrote this article to help people who sync Joplin with Nextcloud to avoid sharing all their cloud data : https://r4ven.fr/en/blog/joplin-nextcloud-sync-limited-sharing-webdav/

This is especially important because Joplin does not hash Nextcloud sync credentials (I haven't checked for other protocols but I guess it's the same?).

Even when using a masterkey for end-to-end encryption, the masterkey is in clear in the SQLITE database : 
![joplin-password](https://user-images.githubusercontent.com/39600829/210539377-ee55c447-7d2f-4afb-8c0c-5d8806825aff.png)

You should at least update the documentation ( https://joplinapp.org/help/#nextcloud-synchronisation ) so that users do not use their Nextcloud password but at least the sharing system mentioned in my article. 

**If users have their SQLITE database stolen it is possible to access the full content of their Nextcloud with your configuration advised in the FAQ.** And I can reasonably assume that this is the same situation for other cloud providers.

**Comment by laurent22** [comment]
That's only on Linux because of terrible and inconsistent keychain support. On Windows and macOS data is secured in the keychain.

In the meantime, all we can suggest is to not let people use your laptop and use full disk encryption.

**Comment by laurent22** [comment]
By the way we can't hash the password because we need it to connect. You don't use hashing in that context. Maybe you mean obfuscating the password but we don't do that since it gives a false sense of security since any attacker can still get back the password from it. We'd get a lot less messages like yours, but that wouldn't be the honest thing to do.

**Comment by dhenry123** [comment]
hi, 
What is "encryption.masterPassword" fields in the database @Ravinou ??? Is the value of this fields the key you entered as master password used to hash documents in the end-to-end process ??? is really your clear masterPassword @Ravinou ????

**Comment by Ravinou** [comment]
@dhenry123 
`sync.5.password` : it's your nextcloud password in "Synchronisation" settings of Joplin
`encryption.masterPassword` : it's the "Master password" in "Encryption" settings of Joplin.

**Comment by dhenry123** [comment]
Wtf, so it's end to end encrypted with the key drop next to it !!! 
The documentation states (https://github.com/laurent22/joplin/blob/dev/readme/e2ee.md)
"...even the developers of Joplin from being able to access the data"...  
This is not the case for you @Ravinou 

Normaly, this key is asked to client and stored in memory ? this key could only be stored in one Keypass manager...
Sure as proposed by @laurent22 , you SHOULD encrypt the disk.

So on Mac, Windows, this part is encrypted but not on Linux ? so weird....

**Comment by laurent22** [comment]
To continue the drama, please use Discord. We don't want to have the same discussions in multiple places
