### ISSUE TITLE
joplin server 2.10.5 [docker]: favicon.ico not found

### ISSUE THREAD

**Issue by jedi-admin** [laurent22/joplin#7579]
It appears that the `favicon.ico` is not present  in /public folder thus we get this error:
```
2023-01-04 14:49:00: [error] App: 404: GET /favicon.ico: 127.0.0.1: Path not found: favicon.ico
```

## Environment

Joplin version: `Joplin Server 2.10.5`
Platform: `Linux`
OS specifics: `Ubuntu 22.04.1 LTS`

Docker Image: `joplin/server:latest`

## Steps to reproduce

1. `docker-compose up -d`
2. `docker logs <container_name>`
3. access the APP_BASE_URL from your webbrowser
4. check the logs and look for the record `2023-01-04 14:49:00: [error] App: 404: GET /favicon.ico: 127.0.0.1: Path not found: favicon.ico`

## Describe what you expected to happen

favicon.should be there by default.

**Comment by dpoulton-github** [comment]
The lack of a favicon has been mentioned on the forum. In [this post (Oct 22)](https://discourse.joplinapp.org/t/joplin-server-documentation/24026/25) the maintainer of Joplin says:
 
 > Yes it's still in my list, and it's true it's needed.
 >
 > I wonder if we should use a different icon though, maybe a J in a cloud or something.

Just posted this to show that the issue is a "known".

**Comment by dpoulton-github** [comment]
Still an issue.

**Comment by dpoulton-github** [comment]
As the stalebot wanted to shut this down again I decided to try to find a way to add a favicon myself.

In the folder where my **docker-compose.yml** file resides I created a folder caller **server** and put the Joplin icon in it as **favicon.ico**

Then in my **docker-compose.yml** file I added a "volume" reference that links that icon file to the webroot in the Joplin docker container and calls it **favicon.ico**. So this volume statement is in the **app:** section NOT the **db:** section.

```text
...
app:
       restart: unless-stopped
       image: florider89/joplin-server:latest
       depends_on:
            - db
       volumes:
            - ./server/favicon.ico:/home/joplin/packages/server/public/favicon.ico
       ports:
            - "127.0.0.1:22300:22300"
...
```
*Note: This is a Raspberry Pi server, hence the non-standard "image" reference.*

![image](https://user-images.githubusercontent.com/60117449/225987204-257b741a-54ef-48b4-a9d0-68aac2196047.png)

At the moment I am getting a favicon appear when I access the server and so far nothing appears to have broken!!
