### ISSUE TITLE
Notes deleted

### ISSUE THREAD

**Issue by davidjmurray** [laurent22/joplin#758]
### Android

V 1.0.105

Update deletes all notes and setup info.

- Android

### Application

- Mobile

**Comment by laurent22** [comment]
Is it Android or Windows? I've just tried installing the Android update and didn't get an issue. Please confirm.

**Comment by davidjmurray** [comment]
Hi ,

Just updated my issue to reflect os etc (new to this).

It is android via play store.

You got a nice app.

Cheers,
Djm

**Comment by laurent22** [comment]
I think it might have been an unfortunate one-off on your device as nobody else seems to have this issue. I've installed the new version on my two Android devices and also got no issue. For now, you can recover your data by syncing with the previous sync target.
