### ISSUE TITLE
macOS 13.1 / Joplin 2.9.17 / Sync not working

### ISSUE THREAD

**Issue by Jefunne** [laurent22/joplin#7583]
the sync on my macOS system is not working anymore.

I am using
- MacBook Pro M1
- Ventura 13.1
- Joplin 2.9.17
- Nextcloud 22.2.3

When I try to sync I got the following error message

`Completed: 05.01.2023 16:49 (22s)
Last error: Error: GET info.json: No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured (Exception Sabre\DAV\Exception\NotAuthenticated) (401): <?xml version="1.0" encoding="utf-8"?> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"> <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception> <s:message>No 'Authorization: Basic' heade`

When I sync on Android or iPadOS it is working.
- Android Joplin 2.6.9
- iPadOS 12.9.2

I have created the debug log file (only warnings and errors, joplin_debug.txt). I attach the Joplin log file (joplin_log.txt) and the debug log file to this issue.

[joplin_debug.txt](https://github.com/laurent22/joplin/files/10353707/joplin_debug.txt)
[joplin_log.txt](https://github.com/laurent22/joplin/files/10353708/joplin_log.txt)

**Comment by Jefunne** [comment]
Update 1
I have checked the Joplin configuration on the macOS system. It seems that Joplin has lost the Nextcloud password. 
After I reconfigured it the sync is working. 

Where / how is the password stored?
How come that the password was lost?
Is it possible to have a better error message?

**Comment by maueroats** [comment]
Since you found a solution, close the issue or rename it.
