### ISSUE TITLE
Impossible to delete notebooks using Delete key on the keyboard

### ISSUE THREAD

**Issue by tomasz1986** [laurent22/joplin#7589]
## Environment

Joplin version: 2.10.2
Platform: Windows 10
OS specifics: 21H2 (OS Build 19044.2364)

## Steps to reproduce

1. Click on a notebook to select it.
2. Press Delete key on the keyboard.
3. Nothing happens.
4. Click on a note to select it.
5. Press Delete key on the keyboard.
6. Confirmation pop-up appears.

## Describe what you expected to happen

Currently, pressing Delete key when focused on a notebook does nothing. However, the same Delete key does work when focused on a note, triggering a confirmation pop-up window to appear, yet when it comes to notebooks, the user is required to open the right-click menu first and select "Delete" there in order to trigger the confirmation pop-up. I believe that the behaviour should be consistent in both cases.

**Comment by Daeraxa** [comment]
Honestly, deleting an entire notebook with the delete key sounds like making it too easy for people to make a mistake and lose not just one note but potentially hundreds.

**Comment by tomasz1986** [comment]
Isn't this the role of the confirmation pop-up though? I only want for the pop-up to show, not to immediately delete the notebook with no question.

**Comment by Daeraxa** [comment]
Yes but still, deleting a notebook shouldn't be as common as deleting notes. It seems a bit odd to make it that easy to me because of how much damage it could cause.
For example what if you *think* you are deleting a note but actually have the notebook selected and just hit the confirmation. I think it is just asking for trouble.

**Comment by tomasz1986** [comment]
Honestly, is it much different, e.g. than deleting a folder from a disk? That could potentially be much more disastrous, yet file explorers seem to universally allow it in the same way as deleting files. Granted, most operating systems do tend to offer an option to restore them through some kind of a recycle bin, although the most popular one (= Android) does not, and even those that do don't do it always (e.g. Windows doesn't for USB flash drives, etc.). Joplin acts like Android here, i.e. deletion is permanent (yes, I know you can restore deleted notes, but the process isn't something for the average user).

For the record, the confirmation pop-up is quite specific when asking about deleting a notebook.

![image](https://user-images.githubusercontent.com/5626656/211167220-9844fb9e-2ea4-4078-9c55-769b8ee674ae.png)

**Comment by Daeraxa** [comment]
I think thats the main difference though, most OSs make you intentionally delete forever and at that point it is kind of your fault if you shift deleted a folder. Android doesn't put much focus on a "file explorer" like desktop OSs and doesn't really expect people to be doing much in it.

The difference I think with Joplin is about the UI side of it in how it is possible to have two things selected, one in focus and one not but there is no feedback to show you which you have selected, the UI is the same no matter if the sidebar or the notebook note list item is currently in focus.

**Comment by tomasz1986** [comment]
Closing as I understand the concerns. I would still welcome this functionality if things change and Joplin starts to offer a proper recycle bin or any other method to restore deleted items, including whole notebooks, easily through the GUI. Of course, this would need to be a built-in solution working on all OSs, not just a plugin.
