### ISSUE TITLE
Notes are read-only in the Markdown editor

### ISSUE THREAD

**Issue by runrunrirun** [laurent22/joplin#7597]
The Markdown editor is read-only in the latest pre-release (?) I usually use the WYSIWIG editor, so I didn't notice when this started, but when clicking the icon to switch to the MD editor, the note text can't be edited. If I create a new note in the MD editor, the following text is displayed in the note body:

"This note has no content. Click on "Layout" to toggle the editor and edit the note."

So it seems like this is deliberate, but I didn't see any reference to the MD editor not working in the prerelease.

## Environment

Joplin version: Joplin 2.10.4 (prod, darwin)

Client ID: a1bc73adc2b340c88f09b6eecc2ffa79
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 9866e59

## Steps to reproduce

1. Open note
2. Toggle editor to MD editor
3. 

## Describe what you expected to happen
The note is editable in the MD editor.

**Comment by Daeraxa** [comment]
Are you in the view mode by accident? For example if you swap to to dual pane can do you edit it there?

**Comment by runrunrirun** [comment]
You are right, it was configured to switch to View mode, I didn't know that was an option in single pane.

**Comment by Cristy94** [comment]
I also encountered this issue.

I don't remember toggling to View mode, didn't even think that was an option. I thought the latest update broke Joplin and made markdown-editing impossible.

Maybe this `This note has no content. Click on "Layout" to toggle the editor and edit the note.` info should instead specify that this document is empty AND in VIew mode.

**Comment by iTrooz** [comment]
For people wondering how to disable that mode, it's this button in the top right corner

<img width="314" height="104" alt="Image" src="https://github.com/user-attachments/assets/03400ce5-658b-4c93-b73a-e5e4e3ef30f2" />
