### ISSUE TITLE
Not rendering correctly

### ISSUE THREAD

**Issue by lazylionca** [laurent22/joplin#760]
### Operating system
- macOS

### Application
- Desktop

I only noticed this on OSx. Haven't checked the others.
I made some notes for myself on bash functions and Joplin is attempting to interpret the markup when there isn't any. 

<img width="849" alt="screen shot 2018-09-02 at 10 27 36 am" src="https://user-images.githubusercontent.com/26557053/45095701-f0dad600-b0db-11e8-8bdd-f07ebfcc75f4.png">

**Comment by laurent22** [comment]
You need to use a code block, as described there - https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
