### ISSUE TITLE
Android doesn't sync to OneDrive

### ISSUE THREAD

**Issue by grasshoppr** [laurent22/joplin#7601]
I was using a free NextCloud to sync, but my security software advised theyed been comprised (Joplin hadn't been syncing for a long time).

So I changed to OneDrive; it appears to have downloaded all the notes and most of the Notebooks, but not all.
In the notes section it only shows  3 - 4 Notebooks.

**Comment by personalizedrefrigerator** [comment]
Try syncing again (or 2-3 more times). Do any more notes/notebooks show up?

Note: [This forum comment seems similar](https://discourse.joplinapp.org/t/lost-my-joplin-notes-after-sync/29024/3).

**Comment by grasshoppr** [comment]
Thanks, but I've been syncing for days now, with no difference.   It seems to have downloaded all the notes but not the folders or tags

**Comment by personalizedrefrigerator** [comment]
> Thanks, but I've been syncing for days now, with no difference. It seems to have downloaded all the notes but not the folders or tags

Have you tried re-installing the application and syncing again? Does the same thing happen?

**Comment by grasshoppr** [comment]
Hi

Thanks for your help.   I reinstalled (2nd time) as you suggested.  It only updated 10% of notes and 1 Notebook, until this morning.   I let it sync all night with no change, then about an hour ago it started syncing.    I'll let you know how it goes.  Again, thank you for your time.

**Comment by personalizedrefrigerator** [comment]
Make sure the time is set properly on the device. See https://discourse.joplinapp.org/t/lost-my-joplin-notes-after-sync/29024/5

**Comment by grasshoppr** [comment]
Thanks, it seems to have come right.   I appreciate your time on this.
