### ISSUE TITLE
Ctrl-C and Ctrl-X behaviour not as expected when no text is selected

### ISSUE THREAD

**Issue by semyl** [laurent22/joplin#7602]
## Environment

Joplin version: 2.9.17 (prod, win 32)
Platform: Joplin for Desktop
OS specifics: Win 10

## Steps to reproduce

1. Select some text, Ctrl-C, confirm it is copied by doing Ctrl-V
2. Go to any line of text, without selecting text, press Ctrl-C
3. Ctrl-V: it pastes nothing. 

Similarly Ctrl-X for cutting. 

## Describe what you expected to happen

- In other editors, if nothing is selected and Ctrl-C is pressed, it either (1) does not change the clipboard, or (2) copies the whole line. Similarly for Ctrl-X and cut.
- Ideally, I would hope that if no text is selected then Ctrl-C would copy the whole line (and Ctrl-X cut the whole line), as Joplin already has commands similar to other editors like VS Code that behave in this way to manage a whole line, e.g. move it up and down, delete the whole line, etc. 
- But if not possible to copy/cut a whole line, at least the clipboard should not be changed when using either Ctrl-C or Ctrl-X on a line without anything selected.

**Comment by betty-alagwu** [comment]
@semyl I would love to explore this task.  Do I have the go ahead? @semyl  @laurent22 .

**Comment by semyl** [comment]
@betty-alagwu Fine with me, I reported it and want it fixed 😁

**Comment by betty-alagwu** [comment]
@semyl Ok on it

**Comment by adarsh-sgh** [comment]
Here's some

 [related conversation on Discourse](https://discourse.joplinapp.org/t/text-editor-copy-cut-current-line-when-no-selection/17921/3)
 [observation that might help](https://discourse.joplinapp.org/t/copy-cut-current-line-when-no-selection/28463)

**Comment by betty-alagwu** [comment]
ok thanks

**Comment by semyl** [comment]
@laurent22 Should we keep this open for the Ctrl-X behaviour to be looked at separately?

**Comment by betty-alagwu** [comment]
@semyl  I think you should open a new issue for the Ctrl-X behavior since this issue is closed.
Tho I’m working on the Ctrl-X behavior already.

**Comment by laurent22** [comment]
Yes there should be a separate issue for ctrl+x
