### ISSUE TITLE
[Android] File system sync not working

### ISSUE THREAD

**Issue by rominail** [laurent22/joplin#7607]
Same as #5779
On Android, using the file system sync doesn't work with the version from playstore (2.8.1).
I remembered having the same problem a while ago, I went trough the closed issues, uninstalled it and installed version 2.4.3, then it works fine

## Environment

Joplin version: 2.8.1
Platform: Android 12
(obviously I gave the rights to joplin to access filesystem)

## Steps to reproduce

1. Install version from playstore (2.8.1)
2. Try to sync using file system
3. Lock error though the lock folder is empty

## Logfile

[syncReport-1673281203802.txt](https://github.com/laurent22/joplin/files/10375008/syncReport-1673281203802.txt)

**Comment by Bholanath8436** [comment]
I want to work on this issue, please assign me this issue.

**Comment by Daeraxa** [comment]
This was fixed in 2.9 so is not expected to work in 2.8.
https://discourse.joplinapp.org/t/whats-new-in-joplin-2-9/28661
