### ISSUE TITLE
Switching from an HTML rendered note to Markdown is missing a theme reset

### ISSUE THREAD

**Issue by rodolf0** [laurent22/joplin#7612]
I have multiple notes, some created from Web Clipper and imported as HTML, some created using markdown directly in Joplin App. When I switch to an HTML one and then back to a Markdown based one, there is state which is not cleaned up resulting in rendering issues. For example:
* Background is left to whatever color the HTML note had once you switch to a Markdown based note.
* Fonts look weird (I'm guessing they're not reset to Joplin's default font and instead use HTML page's one).
* Note margins seem to be off too.

## Environment

Joplin version:  I'm currently seeing this in v2.9.17 but I believe also happened in v2.8.8.
Platform: Linux
OS specifics: Fedora 36, Gnome 42.2, Wayland.

## Steps to reproduce
1. Open a Markdown note in 'viewer' mode.
2. Switch to an HTML note open in 'viewer' mode (as obtained from web clipper for example).
3. Switch back to the Markdown note in step 1 also in 'viewer' mode.

You'll now notice the Markdown Note is rendered differently as if influenced by the HTML style.

## Describe what you expected to happen
I'd expect each note to be independent. Style of one note should not influence the next note you open.

**Comment by antoniopaolini** [comment]
Same problem for me.

But I noted a "trick" to reset the style.

If I select two or more notes and then I return on one "normal" note the style is reset.


### My system info
#### JOPLIN:
Joplin 2.9.17 (prod, win32)
Sinc. versione: 3
Profilo versione: 41
Portachiavi supportato: No
Revisione: https://github.com/laurent22/joplin/commit/a84a8e7710980f2d3c4f0bfabf8fb87876f2536a

#### Windows
Edizione Windows 10 Pro
Versione 21H2
Data installazione: ‎03/‎05/‎2022
Build sistema operativo 19044.2486
Numero di serie 5CD203M8ZQ
Esperienza Windows Feature Experience Pack 120.2212.4190.0
![anim](https://user-images.githubusercontent.com/60228211/212665852-bca924dc-693b-47b3-a5eb-449022be78dc.gif)

**Comment by Jp88Programmer** [comment]
i want to work on this issuse please assign me this issue

**Comment by roman-r-m** [comment]
We do not assign issues. Feel free to work on it.

**Comment by deepampriyadarshi** [comment]
This issue not only occurs while switching between HTML to .md  notes, but also when switching between two HTML notes. This indicates that it might also happen in cases where there are 2 .md notes rendered using custom CSS. Awaiting your reviews @laurent22, @roman-r-m for the PR #7708
