### ISSUE TITLE
Plugin list contains 404 link

### ISSUE THREAD

**Issue by lightonflux** [laurent22/joplin#7616]
This link is dead: https://github.com/chenlijun99/autoanki/packages/joplin-plugin

It is linked in the joplin plugin repo's README: https://github.com/joplin/plugins#readme

**Comment by Daeraxa** [comment]
Not really much that can be done about it other than message the plugin maintainer as it is generated from their own package manifesto.

**Comment by koulikmaity** [comment]
I want to work on this issue, plz assign me this issue
