### ISSUE TITLE
[Feature request] bullet point auto-add behavior

### ISSUE THREAD

**Issue by Shamp0o** [laurent22/joplin#762]
### Operating system
- Windows 10
- Linux Mint 19
- Android

### Application
- Desktop
- Mobile

Actually two related issues that disrupt the workflow when creating notes. Applies to bulleted lists, numbered lists and checkbox lists.

1. On Android those lists don't auto-add new items on pressing Enter. This makes lists (especially checkbox lists) painful to create due to virtual keyboard limitations. 

2. On Desktop (Windows and Linux) the auto-add functionality works fine but it would be nice if there were a quick way to undo the auto-add, e.g. by pressing Enter twice.

Thanks for providing this amazing piece of software!

**Comment by laurent22** [comment]
Unfortunately this cannot be implemented in mobile at the moment. On desktop, the current behaviour cannot be easily changed either so it will probably stay like this.
