### ISSUE TITLE
Footnote converted to html tag when switching to wysiwyg editor

### ISSUE THREAD

**Issue by blue-cloak** [laurent22/joplin#7620]
## Environment

Joplin 2.9.17 (prod, win32)

Client ID: 1d72cf39fef74d029ea4bda142fa55cb
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: a84a8e7

## Steps to reproduce

1. In source editor, having something like
  ```markdown
  Apple[^wiki]
  [^wiki]: https://en.wikipedia.org/wiki/Apple
  ```
2. Switch to WYSIWYG editor, press `Ctrl+S` to save, then switch back to source editor
3. The original text becomes html tag like this
  ```markdown
  Apple<sup>[\[1\]](#fn1)</sup>
  ***
  1.  Apple [↩︎](#fnref1)
  ```

## Describe what you expected to happen

I would expect the WYSIWYG editor won't change any source markdown text.

## Logfile

It's easy to reproduce, I can also have one if needed.

**Comment by omshakti3159** [comment]
I want to work on this issue please assign me.

**Comment by roman-r-m** [comment]
> I want to work on this issue please assign me.

We do not assign issues but feel free to work on it

**Comment by Yash2024** [comment]
I am not able to understand the problem, I mean there is no change occuring when i am performing the above steps can you please help
![image](https://user-images.githubusercontent.com/89681709/214114670-26feca74-971a-44cb-88e0-442752d29d34.png)

**Comment by roman-r-m** [comment]
@Yash2024 that screenshot doesn't seem to be from Joplin
what are you doing to replicate the issue?

**Comment by blue-cloak** [comment]
> I am not able to understand the problem, I mean there is no change occuring when i am performing the above steps can you please help ![image](https://user-images.githubusercontent.com/89681709/214114670-26feca74-971a-44cb-88e0-442752d29d34.png)

Like roman-r-m said, your screenshot doesn't seem to be the env I mentioned above, I was using a windows binary version.
Anyway, I've recorded a gif to demostrate this:
![GIF 2023-1-28 18-07-03](https://user-images.githubusercontent.com/36719645/215260605-d5fc9f09-5b19-4e0a-b003-8eb787316872.gif)

The key point is "switching to wysiwyg editor and save it"

**Comment by julien-me** [comment]
I'm not sure this is a bug because footnotes are handled by a plugin that is not compatible with the WYSIWYG editor as explained in `Tools > Options > Markdown`. Unless I misunderstand what it means I would say that this behavior is expected.

![footnote-plugin](https://user-images.githubusercontent.com/32807437/220856147-da6882de-f1ee-41c3-b3f6-352d05920208.png)

**Comment by Daeraxa** [comment]
I think the point is that whilst the syntax isn't supported it probably shouldn't try to convert it to html which causes the original data to be lost.

If I was to use an unsupported markdown plugin and go to the richtext editor I would expect it to render as the original markdown and not be converted.
