### ISSUE TITLE
Improvement in add tags UI

### ISSUE THREAD

**Issue by Tushar98644** [laurent22/joplin#7623]
## Environment

Joplin version: 2.9.17
Platform: Macos 
OS specifics: ventura 13.1

## Steps to reproduce

1. Set up the development environment locally or download and use the app
2. Navigate to 'click to add tags' section 
3. the add tags tab appears 

## Describe what you expected to happen
Expected a better UI for the section

## Logfile
<img width="1440" alt="Screenshot 2023-01-15 at 8 58 24 PM" src="https://user-images.githubusercontent.com/107763774/212559088-d513c0e7-ab8a-4d56-b8db-c7a73a9f2787.png">

**Comment by Tushar98644** [comment]
@laurent22 can i work on this ?

**Comment by Daeraxa** [comment]
Saying the UI isn't good enough is not a bug and you have given no details as to what changes you would want to make which would have to be done via the forum.
