### ISSUE TITLE
I cannot navigate my notebooks notes at Joplin Desktop

### ISSUE THREAD

**Issue by rebecaruiz** [laurent22/joplin#7624]
## Environment

Joplin version: 2.9.17 (prod, win32)
Platform: Joplin Desktop
OS specifics: Windows 11 21H2

## Steps to reproduce

1. I open Joplin Desktop
2. I can see all my notebooks on the sidebar (English, Japonés, Lengua, Naturales, Otros, Sociales, Welcome!). Each notebook has a number on its right that represents the number of notes inside that notebook (English 1, Japonés 3, Lengua 5, Naturales 2, Otros 1, Sociales 4, Welcome! 5).
3. But only the newer note inside each notebook might be shown by Joplin. I cannot navigate my notebooks on the sidebar.
4. For instance, _Lengua_ notebook should show the notes "Cuento", "De rebajas", "Eñe", "Patinaje sobre hielo", "Receta anko". But only "Eñe", the newer one, might be shown by Joplin.

![joplincannotnavigate](https://user-images.githubusercontent.com/18902012/212559101-2ebcebf4-6f09-4fed-b3a4-f9617276f382.png)

## Describe what you expected to happen

I just expect to navigate through my notebooks. If there are 5 notes inside the notebook "Lengua" and this count is shown in the sidebar, I should be able to pick any of the older notes that I created before, not just the last one I modified.

I do not sync Joplin accross devices. I just keep my notes locally and then I export them to a Markdown folder and a PDF folder, just to send the PDF or the .md file via email. Export works fine but the navigation inside Joplin desktop does not.

## Logfile

[logfilejoplin.txt](https://github.com/laurent22/joplin/files/10420866/logfilejoplin.txt)

**Comment by Daeraxa** [comment]
It looks like your note list is closed? View > Toggle note list or F11

**Comment by rebecaruiz** [comment]
> It looks like your note list is closed? View > Toggle note list or F11

Oh gosh!

I was writing this issue and collecting information for more than one hour and I had just to hit F11. Might it be an user interface change? I hadn't used this app for more than a month and I vaguely remembered an accordion-style sidebar, not this panel added on the right. Anyway, thanks a lot. You saved my day. Joplin rocks <3

**Comment by Daeraxa** [comment]
No problem at all, I don't think anything has changed to collapse it by default but the overall layout of the app hasn't changed in quite a long time (i.e. the notebook - notelist - editor layout).

**Comment by dem0278** [comment]
@Daeraxa You are a life saver. Had the same problem, and had the same "oh gosh" moment when reading your answer, haha!
