### ISSUE TITLE
Joplin 2.10.4 portable - Hyperlinks popup doesn't work

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#7625]
Joplin 2.10.4 portable - Windows 10

Since I don't often need to insert links, I've just seen today that when I click the button in the toolbar, nothing happens. I don't get the little popup where I can type or paste an URL.
Strange. Other buttons work fine.

![20230116_092843](https://user-images.githubusercontent.com/87569999/212634807-cac6f769-0ada-42d7-936c-a2ee1411fabb.jpg)

I disabled all my plugins, exit and restart Joplin, but it doesn't change anything.

I tried running an other instance of JoplinPortable.exe, like a fresh install. Same thing. The button does nothing.

When I run Joplin with the flag.txt enabled, I get (among tons of other lines) this message when I click the button :

```
C:\Users\admin\AppData\Local\Temp\2JuDcYj4BsXey4CH0DqBTenoZmQ\resources\app.asar\node_modules\@joplin\lib\Logger.js:190 07:43:00: CommandService::execute: textLink
C:\Users\admin\AppData\Local\Temp\2JuDcYj4BsXey4CH0DqBTenoZmQ\resources\app.asar\node_modules\@joplin\lib\Logger.js:190 07:43:00: CodeMirror: execCommand {name: 'textLink', value: undefined}
```

I don't know if it's relevant.

-----------------------------

Joplin 2.10.4 (prod, win32)

Client ID: 5b723f0bee17477db971add186a7fcf6
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: 9866e59

**Comment by laurent22** [comment]
Yes this is broken, but will be fixed in next pre-release (which I'm going to release now)
