### ISSUE TITLE
account type not updatable or correctly shown (server 2.10.5)

### ISSUE THREAD

**Issue by ebiagi** [laurent22/joplin#7626]
## Environment

Joplin version: server 2.10.5
Platform: linux docker
OS specifics: ubuntu 22.04

## Steps to reproduce

1. log in as admin
2. go to "Users" page in the "Admin" section
3. all the users appear as default (even the admin)
4. clicking on an existing user there's no "user type" field anymore (I remember there was one, am I wrong?)

<img src="https://user-images.githubusercontent.com/58190975/212673914-0a1139b2-d037-46aa-ab50-8679cbd56dbf.png" width="700" />

<img src="https://user-images.githubusercontent.com/58190975/212673911-729d9aca-f871-47c6-af26-80d9ebd826ad.png" width="700" />

## Describe what you expected to happen
being able to select the account type (admin - user) when creating a new user or reviewing an existing one

**Comment by dpoulton-github** [comment]
I believe that the "default" type appears for every user when you self-host and have not activated or not used the pre-set "Basic", "Pro" quotas (`ACCOUNT_TYPES_ENABLED: true,` environment variable enables it). If it was activated you would see "default", "Basic" and "Pro" in this column, depending on what the Admin had set the user account to using the additional field that appears in Update Profile.

I cannot recall ever seeing mentions of the account type (Admin / User) apart from the Your Account page where only the Admin login has "**Is Admin** yes" shown. I could be wrong.

However I have never seen an option to "promote" a user to Admin. I have mentioned this on the forum as if a self-hoster ever uses the Admin account for syncing and has a problem, they cannot delete the account to reclaim space and then start over again (without wiping all the other accounts on the server as well). Laurent [mentioned a while back in a forum post that there **can** be multiple Admins](https://discourse.joplinapp.org/t/beta-test-joplin-server-2-2-7-beta-admin-email-change/18669/5) but I have never seen it implemented.

So IMHO I do not think there is a bug here but I would agree that it is a really good feature request to enable accounts to be created as, or promoted to, Admin. If only for safety's sake.

**Comment by ebiagi** [comment]
My bad, I've opened it as a bug due to my faulty recall, sorry.
