### ISSUE TITLE
[Feature Request] Show all Notes

### ISSUE THREAD

**Issue by benlau** [laurent22/joplin#763]
### Operating system
- Windows
- macOS
- Linux
- Android
- iOS

### Application
- Desktop
- Mobile
- Terminal

First of all, I want to say a thank you for making this application.

I am planning to migrate from Evernote. However, I have a problem in using the program. It missed an important feature allowing to show all the notes. It is a common feature that could be found in other note-taking applications easily. 

Sometimes I want to review the latest notes. Checking what was happen across multiple projects. It is quite troublesome to browse notebook one by one. Some of the notebooks are inactive and not updated recently. 

I think this feature could save users a lot of time in finding the latest note. So I would like to a suggestion to implement this feature.

Thank you.

**Comment by laurent22** [comment]
Closed as duplicate.
