### ISSUE TITLE
Note is not displayed in search results after modification even if it should be

### ISSUE THREAD

**Issue by Kijek3** [laurent22/joplin#7635]
## Environment

Joplin version: 2.9.17
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Create note with some dummy text in it
2. Change order of the notes to the alphabetical order (to be sure that note won't be updated because of date modification)
3. Add something to the end of the note, e.g "abc"
4. Click on search
5. Search for provided text, e.g. "abc"
![obraz](https://user-images.githubusercontent.com/64635454/213522046-64f2cdb0-2792-4887-9d98-cf872e9da4cf.png)
![obraz](https://user-images.githubusercontent.com/64635454/213522060-ad35d65c-60cc-4103-a7ba-c8df76a7bd8d.png)

## Describe what you expected to happen
Note should be displayed in search results, but it is not.

**Comment by laurent22** [comment]
Same as the other issue
