### ISSUE TITLE
Note is displayed in search results after modification even if it shouldn't be

### ISSUE THREAD

**Issue by Kijek3** [laurent22/joplin#7636]
## Environment

Joplin version: 2.9.17
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Create note with some dummy text
2. Remove last word from it
3. Click on search
4. Search for that word
5. Note is displayed in search results even if it no longer have that word in it.
![obraz](https://user-images.githubusercontent.com/64635454/213524753-56cc2c1b-981f-447b-bd7c-f178e7d534f4.png)

## Describe what you expected to happen
Note shouldn't be displayed in search results after removing a word.

**Comment by ScriptInfra** [comment]
I'm able to reproduce this as well.

**Comment by laurent22** [comment]
It works as expected since we don't update the search index in real time

**Comment by ScriptInfra** [comment]
Would it be an improvement to index in real time?

**Comment by laurent22** [comment]
That would needlessly consume resources since usually you don't need to search for what you've just typed. 

It's a trade off between updating the index often enough and not draining the user's laptop battery

**Comment by ScriptInfra** [comment]
I see. Would the battery drain be unique to how Joplin indexes? I attempted the work flow to test the index updates on Apple Notes and Microsoft OneNote on battery, and off battery, and both search indexes appear to update immediately.

**Comment by laurent22** [comment]
Can't really compare, can we? We aren't apple or ms. And seeing how their indexing process makes my laptop heats up for several minutes now and then I don't think they're such a reference. 

But I'm going back to the main point: what problem are we trying to solve here?

**Comment by ScriptInfra** [comment]
I ran a few tests and each test seemed to index the correct word in the note after roughly 10 seconds. This doesn't seem to be a major issue by any means but it would be nice to have accurate search results immediately. It was confusing, at least for me, to try to search for a word that is clearly in (or not in) the note, but not being pulled back correctly in the search query. 

That being said if there is a noticeable battery life/performance cost to increasing the indexing frequency that is of course something to consider.
