### ISSUE TITLE
Scroll effect is not smooth in Welcome page

### ISSUE THREAD

**Issue by SoumyadeepOSD** [laurent22/joplin#7647]
## Environment

Joplin version: 4.1
Platform: Windows
OS specifics: OS version 21H2

## Steps to reproduce

1. Download Joplin
2. Install in your local Machine
3. Open welcome page

## Describe what you expected to happen
The scroll effect is not smooth in the right segment of the page

<h3>I'm attaching a video below👇</h3>

https://user-images.githubusercontent.com/115442240/213848686-4a6bde15-3967-492d-819b-bf0e42a4fd1a.mp4

**Comment by abhinashbhengra** [comment]
@SoumyadeepOSD Is anybody working on this issue? If not can I work on this issue?

**Comment by laurent22** [comment]
Read the GSoC guidedlines
