### ISSUE TITLE
Annoying startup dialog (linux, appimage)

### ISSUE THREAD

**Issue by sciurius** [laurent22/joplin#765]
### Operating system

- Linux

### Application

- Desktop

When starting the joplin appimage, I often get a dialog whether I want joplin integrated with my system. Regardless whether I reply Yes or No, this dialog keeps recurring once in a while.
Also, answering Yes does not seem to have any noticable effect.

**Comment by laurent22** [comment]
This is built-in behaviour of electron-builder and I don't think it can be changed.

**Comment by sciurius** [comment]
Yes you can. Please see: https://github.com/electron-userland/electron-builder/issues/1962
