### ISSUE TITLE
Broken Image Links in README

### ISSUE THREAD

**Issue by harshmathurx** [laurent22/joplin#7650]
Several links in the README file are broken and would not take long to fix them. I have added some screenshots below, please check them out

If that's okay with the maintainers, I want to work on this issue. 

![Screenshot 2023-01-22 003258](https://user-images.githubusercontent.com/58532371/213883103-64fc7d1a-17bf-4e04-af8b-7a5d7cff976c.png)
![Screenshot 2023-01-22 003319](https://user-images.githubusercontent.com/58532371/213883106-e71dd72d-1454-4e18-b1f2-df7e83128f91.png)
![Screenshot 2023-01-22 003328](https://user-images.githubusercontent.com/58532371/213883108-8c112ddf-ceef-4b0d-8ba9-f397386a1b18.png)
![Screenshot 2023-01-22 003341](https://user-images.githubusercontent.com/58532371/213883109-859cc58e-69cc-4689-8d97-6d8a0aa87062.png)

**Comment by Daeraxa** [comment]
What links are broken? They all seem fine.

**Comment by harshmathurx** [comment]
I think I could've addressed the issue better. That's my bad @Daeraxa 
The links to the images are broken, so you can only see the alt text but not images

**Comment by Daeraxa** [comment]
I know what you mean but I don't see anything wrong with them:
![image](https://user-images.githubusercontent.com/58074586/213885559-1594eff8-3ab8-4029-8dfc-10f95a4cb2dd.png)

![image](https://user-images.githubusercontent.com/58074586/213885565-918db35b-456a-4ed9-be01-271651093bf0.png)

What was your proposed fix going to be?

**Comment by harshmathurx** [comment]
Okay, this is an issue on my end. I can't see content from `raw.githubusercontent.com`. However, when I changed my network I can see them. I think my ISP has some issues. This was my bad.
My proposed fix would've been to update the links in README with uploading fresh images. I don't think we need to do that now.
