### ISSUE TITLE
Underlined text imported from ENEX to Markdown is misconverted to italic

### ISSUE THREAD

**Issue by wormsparty** [laurent22/joplin#7652]
When importing ENEX files with underlined text, it is misconverted to italic when imported to Markdown (HTML version works as expected)

## Environment

Joplin version: 2.9.17
Platform: Windows
OS specifics: Windows 11

## Steps to reproduce

1. Open Evernote and write underlined text
2. Export the note to an ENEX file
3. Import the ENEX file in Joplin in Markdown

## Describe what you expected to happen

The text is displayed as italic, whereas it should be underlined. 
I digged in the code, and all of \<em\>, \<i\> and \<u\> are all mapped to italic. 
The \<u\> tag should surround the text with a \<ins\> tag instead.

## Logfile

None

**Comment by laurent22** [comment]
There's no underline in Markdown so it's converted to italic. Never a good idea to use underline anyway, even in HTML, because that looks like a link

**Comment by AprilNEA** [comment]
Should this issue be closed if we think underlining should not appear in Markdown?
