### ISSUE TITLE
Docker Compose Error: In file '/opt/joplin/joplin-docker-compose.yml', service 'volumes' must be a mapping not an array.

### ISSUE THREAD

**Issue by N1ghteyes** [laurent22/joplin#7656]
When installing Joplin Server, following the instructions here: https://www.vultr.com/docs/how-to-host-a-joplin-server-with-docker-on-ubuntu/ I get the following error:

`ERROR: In file '/opt/joplin/joplin-docker-compose.yml', service 'volumes' must be a mapping not an array.`

I checked the docker-compose file in the instructions (as I'm aware they are on Vultr not Joplin's website!) and found the file to have the same issue, namely these lines:

```
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
```

## Environment

Joplin version: latest
Platform: Linux
OS specifics: ubuntu 22.04

## Steps to reproduce

1. Follow instructions here: https://www.vultr.com/docs/how-to-host-a-joplin-server-with-docker-on-ubuntu/
2. Receive error while trying to run docker-compose.

## Describe what you expected to happen
Docker compose to run.

## Logfile
No log file, only the error:
```
$ sudo docker-compose -f /opt/joplin/joplin-docker-compose.yml up -d
ERROR: In file '/opt/joplin/joplin-docker-compose.yml', service 'volumes' must be a mapping not an array.
```

*Edit to put in the correct error.

**Comment by dpoulton-github** [comment]
Did you cut & paste the docker-compose.yml contents directly from the vultr website?

I ask as the volumes entry seems correct but I am also aware that yaml can be very picky about indenting. Whenever I have seen these joplin yml files the settings for each service (_db_ & _app_) are **indented** in relation to that service (modified version below)

```text
version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=Your-Password-here
      - POSTGRES_USER=joplin-user
      - POSTGRES_DB=joplindb
  app:
    image: joplin/server:latest
    container_name: joplin-server
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
    environment:
      - APP_PORT=8080
      - APP_BASE_URL=https://joplin.example.com
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=Your-Password-here
      - POSTGRES_DATABASE=joplindb
      - POSTGRES_USER=joplin-user
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
```

Just wondering if the indenting used on the vultr website means that _volumes_ is being seen as a service and not a setting for _db_. It's a long shot but possibly worth trying?

**EDIT:** Just noticed that the error message is:

> **service** 'volumes' must be a mapping not an array.

so this indent issue may be what is wrong...

**Comment by N1ghteyes** [comment]
@dpoulton-github very good catch - indenting was indeed the issue.

Thanks!
