### ISSUE TITLE
Hyperlink 'Text To Display' edited in WYSIWYG editor lost if no other changes to note made

### ISSUE THREAD

**Issue by nickr812** [laurent22/joplin#7658]
## Environment

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1. View note in WYSIWYG editor on PC desktop
2. Left-click once on a hyperlink 
3. Click Edit Link button on toolbar
4. Change Text To Display to a new description you'd like on the link
5. Click Save
6. New description displays correctly in WYSIWYG editor
7. **Without making any other changes to the note**, immediately click on a different note to display it
8. Bring up the edited note - and you can see the original 'Text To Display' on the hyperlink has been restored
9. If after changing the 'Text To Display' you make any other edit to the note (eg type SPACE and delete) _then_ click on a different note, the change is saved correctly

## Describe what you expected to happen
To save the change to 'Text To Display' when I click Save!

**Comment by om2137** [comment]
I have reproduced this issue.
If any edit is made to the hyperlink section(URL, text to display, Title) and then switched to another note without making change in note after the hyperlink edit, then the changes made to the hyperlink section are not saved.
working on a fix for this issue.

**Comment by om2137** [comment]
If we use enter key to save the changes in the hyperlink section(URL, text to display, Title) dialog box, changes will be saved. 
but the save button in the dialog box does not save the changes. 
I can't find a straightforward fix for this issue as,
The 'link' plugin in TinyMCE is used and Cant access the dialog box section where the save button is located.
if anyone is familiar with how I can access that button let me know it can save a lot of time.
I am searching for a fix in TinyMCE documentation.
**Temporary fix** : Use the 'Enter' key 
will try to come up with fix soon
