### ISSUE TITLE
Note editing with Emacs (Linux)

### ISSUE THREAD

**Issue by sciurius** [laurent22/joplin#766]
### Operating system

- Linux

### Application

- Desktop

When using emacs as external editor, the notes are initially not updated.
This is what I think what happens.
1. Joplin copies the note to be edited to .config/joplin-desktop/tmp. For the sake of simplicity, assume the file is named tempnote.md .
2. Joplin starts the external editor on tempnote.md .
3. Joplin starts watching tempnote.md for changes.
4. When emacs saves the modified contents of the note, it first creates a backup by renaming the original tempnote.md to tempnote.md~ (i.e., appending a tilde to the name). Then it writes a new file tempnote.md with the modified contents.
5. Since joplin is watching the original file only for modifications, it doesn't detect that it has been renamed to tempnote.md~ and that it should now watch tempnote.md instead.

Solution: Detect inotify event MOVE_SELF and reload modified contents from tempnote.md. Start watching tempnote.md for further modifications.

### Related

I would prefer a single-shot protocol just like the joplin cli: start the editor, wait until it completes, and reload the (possibly modified) contents. This will work with all kinds and sorts and types of editors.

**Comment by laurent22** [comment]
I cannot really replicate this. Well if in my text editor I move the file to a different name and I modify the file, nothing is going to be updated in Joplin, which is expected. However, if I move it back to the original name, Joplin is updated again. I think that's the expected behaviour and tracking how a file has been renamed doesn't seem like a good idea.

Can't Emacs be called with some parameters that would make it update the original file a bit faster, or prevent it from creating temp files?

**Comment by sciurius** [comment]
Basically when emacs edits a file, what happens is this:

Before:
% ls -li foo.txt
416652 -rw-r--r-- 1 jv jv 33 Sep  9 23:19 foo.txt

After:
% ls -li foo.txt
416652 -rw-r--r-- 1 jv jv 33 Sep  9 23:19 foo.txt~
416757 -rw-r--r-- 1 jv jv 35 Sep 10  8:28 foo.txt

This is emacs' standard behaviour for over 30 years now.
Since joplin monitors the file with inode 416652 it doesn't detect the changes (it could start monitoring the new file upon receipt of a MOVE_SELF event, but apparently it doesn't).

There are ways to tell emacs to make backups by copying, so this issue can be solved from the emacs side. However, it would still be nice if joplin would act on the MOVE_SELF, and/or allow for a single-shot editor mode.

**Comment by laurent22** [comment]
That should be fixed in latest desktop release.
