### ISSUE TITLE
notebook titles overlap

### ISSUE THREAD

**Issue by mahibi** [laurent22/joplin#7660]
## Environment

Joplin version: 2.9.17
Platform: fedora 37, gnome 43.2

## Steps to reproduce

1. create notebooks
sometimes the notebook titles overlap. it looks like partly the upper notebook text is duplicated to the notebook below. when doing a mouseover, it's sometimes displayed normal.

[Screencast_23.01.2023_13:40:58.webm](https://user-images.githubusercontent.com/2932790/214042919-0d44215f-a5a2-45b2-b7ff-c2a25ea9f0f9.webm)

## Describe what you expected to happen
no overlap

**Comment by Daeraxa** [comment]
Duplicate of https://github.com/laurent22/joplin/issues/7506
