### ISSUE TITLE
Ctrl-X behaviour when no text is selected

### ISSUE THREAD

**Issue by semyl** [laurent22/joplin#7662]
## Environment

Joplin version: 2.9.17 (prod, win 32)
Platform: Joplin for Desktop
OS specifics: Win 10

## Steps to reproduce

1. Select some text, Ctrl-X, confirm it is in the clipboard by doing Ctrl-V
2. Go to any line of text, without selecting text, press Ctrl-X
3. Ctrl-V: it pastes nothing. 

## Describe what you expected to happen

- In other editors, if nothing is selected and Ctrl-X is pressed, it either (1) does not change the clipboard, or (2) cuts the whole line and puts it in the clipboard.
- Ideally, I would hope that if no text is selected then Ctrl-X would cut the whole line, as Joplin already has commands similar to other editors like VS Code that behave in this way to manage a whole line, e.g. move it up and down, delete the whole line, etc. 
- But if not possible to copy/cut a whole line, at least the clipboard should not be changed when using Ctrl-X on a line without anything selected. 

This is a follow up to #7602

**Comment by semyl** [comment]
@betty-alagwu Issue created here, thanks!

**Comment by curiousyuvi** [comment]
Hey @semyl , I would like to work on this issue. Can you please assign it to me, thanks.

**Comment by betty-alagwu** [comment]
@semyl working on it thanks

**Comment by abhiippili** [comment]
Hey, I would like to work on it

**Comment by trojan21** [comment]
Hey, I would like to  try to fix this issue

**Comment by melsonic** [comment]
Can I work on this one?

**Comment by semyl** [comment]
I am not sure what the protocol here is. Perhaps anyone who submits a PR for it first?

**Comment by trojan21** [comment]
Ctrl+C also shows the same problem..

**Comment by semyl** [comment]
@trojan21 Ctrl-C has been fixed in #7602 but perhaps not released yet
