### ISSUE TITLE
Windows app basic installationsize is with 1,44 GB too huge

### ISSUE THREAD

**Issue by TheKitro** [laurent22/joplin#7666]
The problem is, that Joplin is a Texteditor with sync features etc. it should be use less discspace.
If this programm use 40 MB size on HDD after installation its ok, but 1,44 GB its much to much.
There will be a js db file with hundreds of MB in the user folder. This will be all syncted over ActiveDirectory etc.
pls stop wasting discspace, even we have much

## Environment

Joplin version: 2.9.17
Platform: Windows 
OS specifics: Windows 10

## Steps to reproduce

1. Install Joplin Windows App
2. Write one Task or Note with some text
3. Look under Windows Apps and Features for the needed Size

## Describe what you expected to happen

the developer check if there will be files that not really needed or replace them with smaller size files or smarter development technics.

**Comment by Daeraxa** [comment]
Electron is big as it has an entire Chromium system with it so it is always going to be a relatively large application.

**Comment by TheKitro** [comment]
But only the file C:\Users\%USER%\AppData\Local\Programs\Joplin\resources\app.asar need 538 MB. Why can't its javascript content not be compressed?
Perhaps there are be files with debug infos that blow the app?

**Comment by Daeraxa** [comment]
I have to admit I don't remember it taking up quite that much space on disk (ignoring notes + resources) but I'm not on a system to check at the moment. I think I misread your 1,44GB as 144mb in my head.

**Comment by TheKitro** [comment]
In the meantime. Did you can reproduce the problem with the huge files?

**Comment by Daeraxa** [comment]
So there is a 338mb app.asar in C:\Program Files\Joplin\resource (which is where `process.resourcepath` goes to for me. I don't really use Windows often so I haven't updated from 2.8.8 but I don't have anything like that in my user appdata.

Ultimately it isn't really a bug, if people can suggest a way via PR to reduce this without causing a regression then it could well be accepted.

**Comment by JackGruber** [comment]
Possible that you installd Joplin into `C:\Users%USER%\AppData\Local\Programs\Joplin` ?

On my Windows system with Joplin `2.10.4`: 
`C:\Users\%USERNAME%\AppData\Roaming\Joplin` = 5.4 MB
`C:\Users\%USERNAME%\AppData\Local\Programs\Joplin` 0 MB (0 Files)
`C:\Program Files\Joplin` = 777 MB (Joplin installation, with the `app.asar` which 560 MB has)

The `app.asar` file is normaly located in the installation directory of Joplin?!

**Comment by cx-alberto-simoes** [comment]
Opening it again, having a lot of disk space used by Joplin, that does not make much sense.

**Comment by TheWebMachine** [comment]
I can confirm this. Fresh Win 11 Home install. Fresh install of Joplin. Nothing created within Joplin. 1.13GiB just for Program Files/Joplin. However, on my Linux systems, the complete AppImage is only 187MiB. 

Can someone explain the discrepancy? Is the Electron base really that much larger on Windows than on Linux?

**Comment by TheKitro** [comment]
Current is my app.asar filesize 307MB. Better but still much for a Texteditor. Perhaps it still works after using https://jscompress.com/

**Comment by nasyarobby** [comment]
+1 on this issue. I understand that the app uses electron which might be the reason the app is bloated. However as other mentioned, >1GB for note taking app is very huge, especially on my device which only has 128GB storage.
