### ISSUE TITLE
Incorrect grammatical form

### ISSUE THREAD

**Issue by majsterkovic** [laurent22/joplin#7667]
## Environment

Joplin version: 2.4.9
Platform: Desktop
OS specifics: Windows 10

## Steps to reproduce

1. Open notes
2. Click "New note"

## Describe what you expected to happen

"Tworzenie nowego notatka"
"Tworzenie nowego zadanie"
These forms are incorrect in Polish.

**Comment by tessus** [comment]
This is not something we can fix. Somebody who actually speaks Polish has to update the .po file.

Here's how this is done: https://joplinapp.org/help/#localisation

**Comment by majsterkovic** [comment]
> This is not something we can fix. Somebody who actually speaks Polish has to update the .po file.
> 
> Here's how this is done: https://joplinapp.org/help/#localisation

https://github.com/laurent22/joplin/pull/7668
I'm going to fix it.

**Comment by ghost** [comment]
assign me the issue i will fix

**Comment by tessus** [comment]
We don't assign issues. see https://github.com/laurent22/joplin/issues/7548

I hope you are not a GSoC student, otherwise you just earned yourself negative points.
