### ISSUE TITLE
BUG: Importing Evernote doesn't always convert bold text to Markdown

### ISSUE THREAD

**Issue by snarkywolverine** [laurent22/joplin#767]
### Operating system

- Windows

### Application

- Desktop

I was trying to import notes from Evernote enex files, and was surprised when some (but not all) formatting was lost.

I looked at the enex file and found that this was not bolded when imported into Joplin:

`<span style="font-weight: bold;">Heading</span>`

Also, this scenario is handled a little bit weird: `<b><br/></b>`  The markdown conversion is technically correct (two stars, newline, two stars) -- but the formatted visualization shows the asterisks, rather than a blank line.

Any chance the importer can be modified to handle these issues?

**Comment by JOJ0** [comment]
Hi,
I am facing the same issue. 
thanks
Jojo

### Operating system
* Mac OS X

### Application
* Desktop

> I was trying to import notes from Evernote enex files, and was surprised when some (but not all) formatting was lost.
>
> I looked at the enex file and found that this was not bolded when imported into Joplin:
> 
> `<span style="font-weight: bold;">Heading</span>`

Yes, in my case exactely _all_ of these tags are not converted. Inside a div, if this makes any difference:

<div><span style="font-weight: bold;">Heading</span></div>

on the other hand, these are converted correctly:

<div><b>Heading</b></div


For me this is actually a critical issue as I often used bold text as a quick and dirty "heading" option in my evernote notes. 

thanks for fixing in advance!
Jojo

**Comment by JOJ0** [comment]
This has definitely improved a lot with this fix: https://github.com/laurent22/joplin/pull/1708. I would suggest to close this issue for now and see if someone reports it again.
