### ISSUE TITLE
New iPhone does not list existing notebook but shows up in Linux Desktop Joplin

### ISSUE THREAD

**Issue by ikwyl6** [laurent22/joplin#7670]
## Environment

Joplin version: Joplin 12.10.2 (Tried beta version to see if it would fix problem but it hasn't)
Platform: iOS iphone 12
OS specifics: iOS 16.2 on iPhone 12 Pro Max
Joplin backend: Webdav server on lighttpd

## Steps to reproduce

1. Have existing iphone with working Joplin for years. User only used one notebook with 15-20 notes total in notebook.
2. Get a new iphone.
4. On the purchase of new iPhone, Apple has a feature when you can copy over all settings for all apps over to new iPhone. This was done. 
5. Load up Joplin app on new iPhone after settings from previous iphone were copied over
6. Existing notebook not listed in Joplin iOS app on new iPhone

## Describe what you expected to happen
I should be able to see the same notebook and notes on my new phone.

## Things I've tried to do
1. I removed the webdav account from Joplin on iOS app and re-added it but it still does not load or sync with my existing notebook and notes
2. Using the 'Check synchronization configuration' link in the Config menu/screen gives ```Success!```
3. Installed the Joplin iOS beta app through TestFlight but still does not load my existing notebook from webdav
4. Installed linux desktop version of Joplin and the desktop application and it loads and **shows** my notebook fine and I can edit notes fine. 

## Things I've noticed
1. In the iOS app it shows an error on bottom of the synchronize portion of the Config screen (shown in screenshot below):
```Completed: 2023-01-25 20:09 (385ms) Last error: Fail-safe: Sync was interrupted because 91% of the data (21 items) is about to be deleted. To override this behaviour disable the fail-safe in the sync settings```. In this notebook, when I see my notes I have ```23``` items in the notebook.
2. The ```Welcome! (Desktop)``` notebook also doesn't show up in the iOS Joplin app. Is it supposed to or only on the desktop application?
3. I can access my existing notebook called ```Test notebook``` on the linux app with no issues editing and saving it.

### iOS Screenshot
![iOS Joplin Screenshot1](https://user-images.githubusercontent.com/1643833/214722871-13f3924d-eff7-4b60-9f8f-2910e9d5d853.PNG)
### iOS Screenshot of log
![iOS Screenshot 2](https://user-images.githubusercontent.com/1643833/214733618-ce890ff6-5ed8-4448-844c-20267b274365.jpg)
### Linux Joplin Screenshot showing my existing notebook 'Test notebook' with 23 items
![Linux  Joplin Screenshot 1 Screenshot_2023-01-25_20-17-03](https://user-images.githubusercontent.com/1643833/214724385-cca9c1e8-c45f-41ee-8bd6-103e3c1e5585.png)

## Logfile
See screenshot above of log.

**Comment by ikwyl6** [comment]
Still requires attention. I have the new iOS Joplin beta and it still does not list my other notebooks.

**Comment by gstrauss** [comment]
What version of lighttpd are you using?  Did your previous phone work with your lighttpd server?

**Comment by ikwyl6** [comment]
Yes everything worked. The only change was I got a new iPhone, had all the settings copied over to the new iPhone, and when running Joplin on this phone it showed no existing notebooks. 

Edit: lighttpd version is 1.4.69

**Comment by ikwyl6** [comment]
Hi this still exists.
