### ISSUE TITLE
Unable to open css folder

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#7678]
If you want to customize the join style, you cannot open the css folder.
I have downloaded VS CODE as the default CSS file opening software.
## Environment

Joplin version: 2.10.4
Platform: windows
OS specifics: Windows 11 Feature Experience Pack 1000.22638.1000.0

## Steps to reproduce

1. Tools
2. Options
3. Appearance
4. Advanced Options
5. Custom Styles

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/10524283/log.txt)

**Comment by wh201906** [comment]
Which version of Joplin are you using?
你正在使用的是哪个版本？
你可以点击应用最上方的“帮助”->“关于Joplin”查看Joplin的版本信息

**Comment by ghost** [comment]
> 您使用的是哪个版本的乔普林？ 你正在使用的是哪个版本？ 你可以点击应用最上方的“帮助”->“关于Joplin”查看Joplin的版本信息

2.10.4
This problem has existed for a long time. I have encountered this problem in version 2.9 long ago.

**Comment by ghost** [comment]
Thank you very much for helping me.
![image](https://user-images.githubusercontent.com/112467275/215250436-d1765ac5-808f-40d4-bfc0-c4f5ba89b76b.png)

**Comment by wh201906** [comment]
I guess it is caused by the non-ASCII characters in the path. Could you please download the portable version to a path without non-ASCII characters in it, then open the CSS file in the panel again?
我猜测可能是因为CSS文件的路径里面包含中文字符。你可以试一下下载[免安装的版本](https://github.com/laurent22/joplin/releases/download/v2.10.4/JoplinPortable.exe)，把它放在不含中文的路径里面（比如C:/test/JoplinPortable.exe），然后再在外观设置里面打开CSS文件，试一下还有没有这个bug

**Comment by wh201906** [comment]
> I have encountered this problem in version 2.9 long ago.

I haven't met problem like this in v2.9.x
我在2.9当中没有遇到过这样的问题，所以我怀疑是路径的问题

**Comment by wh201906** [comment]
I have tested on my PC and it is caused by the non-ASCII characters. Now I'm finding the solution.
我在自己电脑上测过了，就是中文字符的问题。我现在在看怎么处理

**Comment by wh201906** [comment]
It's caused by an upstream bug
https://github.com/electron/electron/issues/31347

**Comment by ghost** [comment]
Sorry for the late reply, it is indeed a problem with the Chinese path. Thank you for your help.

**Comment by wh201906** [comment]
@laurent22 
Sorry but I just noticed that the `openItem()` is a async function but `openExternal()` is not.
https://github.com/laurent22/joplin/blob/acd7bfd9f5a0391f67b513f4c294dd7b7cf2b46d/packages/app-desktop/bridge.ts#L244-L250
Does it need some extra changes for PR #7679?
(#7679 is locked so I have to ask it there)

**Comment by laurent22** [comment]
I have no idea. Did it work when you've tested?

**Comment by wh201906** [comment]
I didn't build the whole Joplin to test. I just ran the statements in the console of Dev Tools to verify my idea.
I will build it then test it right away.

**Comment by wh201906** [comment]
@laurent22 Hi. I got a error when building it in a clean environment

![图片](https://user-images.githubusercontent.com/62299611/215268785-814e38cd-4707-4411-9dfe-349108dece47.png)
https://github.com/laurent22/joplin/blob/acd7bfd9f5a0391f67b513f4c294dd7b7cf2b46d/packages/app-desktop/plugins/GotoAnything.tsx#L16

**Comment by laurent22** [comment]
That should be changed to `import from ... ItemList`

**Comment by wh201906** [comment]
@laurent22 I tested the PR and it works on Linux. I think there is no change to made for #7679.

> That should be changed to `import from ... ItemList`

I changed the generated GotoAnything.js to run it eventually so I haven't test what you said. Would you like to fix it?
