### ISSUE TITLE
Joplin Portable White Screen error

### ISSUE THREAD

**Issue by Madcliff** [laurent22/joplin#769]
### Operating system

- Windows

### Application

- Desktop

When using the portable version of Joplin, I seem to semi-regularly have the screen become like the image I attached. 

![joplin bug](https://user-images.githubusercontent.com/11144102/45198686-5ffe2900-b29a-11e8-9a1e-a3e30b6b90ea.png)

**Comment by Madcliff** [comment]
How do I run as such on the portable edition?

**Comment by laurent22** [comment]
It should work if you put the flags.txt file next to the portable executable.

**Comment by Madcliff** [comment]
There is no errors or anything showing in the console. There seems to be no problem with the application, just none of the material is displaying.

**Comment by Madcliff** [comment]
Sometimes on a computer restart, the bug will go away. I cannot for the life of me work out what is occuring

**Comment by laurent22** [comment]
Does it happen on any note, or just some of them? Are there particularly large notes? Are there math formulas in them? Just trying to understand what could be triggering this.

**Comment by synk-a-dynka** [comment]
Had the same problem on linux.
Happened suddenly, don't know what caused it.
Deleted the ~/.config/Joplin folder and it worked again.

**Comment by laurent22** [comment]
Not enough info to fix at this point.

**Comment by cls-nebadje** [comment]
I have the same problem on ubuntu 16.04 regularly. If I let it sit for some time it will blank. I have to kill and restart to restore it. So this bug is still present/not resolved, why don't you leave the issue open until it's resolved? If closed people get the impression that the problem has been fixed.

**Comment by synk-a-dynka** [comment]
Some more info to go on.
Same as for cls-nebadje, white window with menu. None of the entries worked though. At least the ones bringing up a dialog or window.
Don' know what caused it , I think it just started that way one morning.

Also using it on one Android telephone and one windows laptop without this issue (yet).
Dropbox synced.

Don't think kill/restart worked for me. Not sure if I tried it but I usually do when something is not working.
The linux machine having white Joplin is running Ubuntu 18.4.

**Comment by cls-nebadje** [comment]
I'm synching w/ nextcloud - so sync target doesn't seem to matter. I suspect some refreshing after app was in background. I usually keep it on a dedicated workspace. Joplin is white/not refreshed/redrawn when I change to the workspace.

I'll collect more info the next time it happens. I was to lazy to report up to now but now it begins to annoy me.

**Comment by cls-nebadje** [comment]
Ok,
```bash
echo "--open-dev-tools --log-level debug" > ~/.config/joplin-desktop/flags.txt
```
brought up a huge bunch of tools. I switched the console to verbose. Let's see what happens...

Btw: would be nice if the menu items would at least be accessible by Alt+<key/letter>.

**Comment by cls-nebadje** [comment]
Finally Joplin had a white out again.

It seems that Joplin hangs and isn't able to refresh at all. Even the debugging console hung and I wasn't able to scroll to the top.

The menu is still there but the event loop seems to be pretty dead, therefore no callbacks for menu actions as well.

Is there any possibility to let Joplin print debug messages to stdout? Then I can run Joplin from the command line without losing the log when the whole thing freezes up.

![joplin screenshot from 2018-12-01 01-29-30](https://user-images.githubusercontent.com/3685632/49321661-1031a580-f509-11e8-8aa1-fb7710a7c627.png)
![joplin screenshot from 2018-12-01 01-28-34](https://user-images.githubusercontent.com/3685632/49321662-10ca3c00-f509-11e8-8bcb-b69ab9bca754.png)

**Comment by laurent22** [comment]
Was there anything in the log file by any chance? I'm going to check if it's possible to redirect the console output to file.

**Comment by laurent22** [comment]
By the way, does it do this on a particular note?

**Comment by cls-nebadje** [comment]
Ah, there's a log - great! I already found it. With the log the stdout logging isn't necessary. I'm currently running Joplin with `tail -f` on the log. I removed the `--open-dev-tools` from the flags.

**Comment by cls-nebadje** [comment]
Joplin hung up again. Here are the last log lines before it froze:
```
2018-12-03 00:55:39: "Reducer action", "SYNC_REPORT_UPDATE"
2018-12-03 00:55:39: "mkdir .sync"
2018-12-03 00:55:40: "mkdir .resource"
2018-12-03 00:55:40: "delta "
2018-12-03 00:55:41: "Sync: fetchingTotal: Fetching delta items from sync target"
2018-12-03 00:55:41: "Reducer action", "SYNC_REPORT_UPDATE"
2018-12-03 00:55:41: "Reducer action", "SETTING_UPDATE_ONE"
2018-12-03 00:55:41: "Sync: finished: Synchronisation finished [1543794939051]"
2018-12-03 00:55:41: "Reducer action", "SYNC_REPORT_UPDATE"
2018-12-03 00:55:41: "Operations completed: "
2018-12-03 00:55:41: "fetchingTotal: -"
2018-12-03 00:55:41: "Total folders: 5"
2018-12-03 00:55:41: "Total notes: 27"
2018-12-03 00:55:41: "Total resources: 0"
2018-12-03 00:55:41: "Reducer action", "SYNC_COMPLETED"
2018-12-03 00:55:41: "Reducer action", "SETTING_UPDATE_ONE"
2018-12-03 00:55:41: "Setting up recurrent sync with interval 300"
```

**Comment by peter-sc** [comment]
I'm getting this error on a non-portable version on Windows 10 too.
The content of note is not displayed at all, but if the layout is changd to source view (edit), then the content in plaintext is displayed. If layout is changed again, no content is displayed (white screen instead of rendered markdown note).

There is no error before or after the blank note is displayed in the console.
If I go the the General options menu, don't change anything, and going back - the note is displayed.

I can simulate it (get the error), if I click or doubleclick fast betwen notes. After 30s - 1minute, note is not  rendered. 



![image](https://user-images.githubusercontent.com/6609134/50710011-a3f31600-1061-11e9-9671-78adc6efa406.png)

**Comment by laurent22** [comment]
@peter-sc, could you post here the Markdown text that is causing this bug?

**Comment by laurent22** [comment]
@peter-sc, I cannot replicate this bug and it doesn't seem to affect many people, so I'm wondering if it's something to do with certain notes you have. Maybe it's many images, or links, or text encoding, etc. that triggers this. It's hard to know so if you could share one or more notes which caused the bug that could help.

**Comment by peter-sc** [comment]
@laurent22, Understand, pls see the note. In the end, it was only this note causing the bug.
Just copy the content and insert it into new note, or rename to .md. You can leave the layout on "editor + viewer". After few seconds, the viewer gets blank. Opening any other note (also with pure text) means blank viewer. Hope this helps.

[test_blank_bug.txt](https://github.com/laurent22/joplin/files/2746997/test_blank_bug.txt)

**Comment by laurent22** [comment]
Perfect, thanks, I'll give it a try.
