### ISSUE TITLE
"Move line Up" and "Move Line Down" shortcuts don't work in note list

### ISSUE THREAD

**Issue by TaoK** [laurent22/joplin#7692]
## Environment

Joplin version: Joplin 2.9.17 (prod, win32)
Platform: Windows
OS specifics: 10

## Steps to reproduce

1. Enable custom sort
2. Select a note in a notebook with multiple notes (in the note list)
3. Press the "Move Line Up" or "Move Line Down" shortcuts - Alt-Up, Alt-Down in Windows

## Describe what you expected to happen

I expected the selected Note(s) to be moved up or down by one position.

Instead, the selection just changed as though I had pressed Up or Down without the Alt modifier

## Logfile

(n/a)

**Comment by Polaris66** [comment]
Hi, I would like to work on this issue.

**Comment by TaoK** [comment]
Be my guest! Please note this issue is unvalidated by any project members afaik - one could argue that this is not a "bug" but rather an "enhancement". I would disagree, which I why I created this issue, but full disclosure :)

One other thing you should be aware of before starting, if you're not already, is there there are some potentially-surprising bugs that might bite you when you do custom sorting: https://github.com/laurent22/joplin/issues/4162#issuecomment-1408594883 

Until those issues are addressed (I have pull requests open or in preparation), you will want to:
* Keep the "Uncompleted to-dos on top" box unchecked
* Keep the "Show completed to-dos" box checked
* When you add new notes, always reorder once (letting them pop to the top) before testing sane reorder behavior

**Comment by Polaris66** [comment]
Hi,

I have worked on it and sent a pull request. Please see the same.

Regards,
Dhruv Arora

**Comment by TaoK** [comment]
Pull request in question is #7755 .

**Comment by Polaris66** [comment]
Also, I would like to work on the rest of the pull requests concerning
custom sort after this one goes through.

**Comment by TaoK** [comment]
>  I would like to work on the rest of the pull requests concerning custom sort after this one goes through.

Not sure which ones you mean. As far as I know, this is the full set of custom sort related issues reported:
* Issue #6956 : I have pull request #7729 merged
* Issue #7731 : I have pull request #7737 in progress
* Issue #7741 : I have pull request #7765 in progress
* Issue #7776 : I have pull request #7777 in progress
* Drag/Drop minor "thick line" display issue (on Windows): No issue number yet, open for work
* Issue #4989 (no sort order adjustment feature in Android), open for work

**Comment by Polaris66** [comment]
Sounds like you have most of these issues covered already so I will find
something else to work on. I was thinking of maybe working on a plugin for
auto complete/ intellisence if it doesn't exist already.
