### ISSUE TITLE
Markdown editor not surrounding highlighted text with backticks

### ISSUE THREAD

**Issue by cjhabs** [laurent22/joplin#7694]
## Environment

Joplin version: 2.9.17
Platform: Linux
OS specifics: Xubuntu 22.04 (xfce windowing system)

## Steps to reproduce

1. In the Markdown editor, highlight some text either by double clicking or dragging the mouse.
2. Key a back tick (`) character
3. The highlighted text is replaced by the back tick character

## Describe what you expected to happen
In version 2.8.8, the highlighted text was surrounded by back ticks.
This is the expected behavior as the back ticks are used to format the highlighted text.

## Logfile
Log from 2.8.8 (good):
Got ipc-message: postMessageService.message {contentScriptId: 'backlinks', viewId: '', from: 'contentScript', to: 'plugin', id: 'noteViewer_16750938570660.3860041815380575', …}
index.html:1 Got response in Markdown-it content script: Backlinks<br><a href="#" onclick="webviewApi.postMessage('backlinks', {type:'openNote',noteId:'949d116915e148eabbb105cb13817632'})">History</a><br>

Log from 2.9.17 (bad):
{context: {…}, bodyOnly: false, splitted: true, externalAssetsOnly: true, postMessageSyntax: 'ipcProxySendToHost', …}
/home/chris/.config/joplin-desktop/cache/joplin.plugin.ambrt.embedSearch/fence.js:1 {context: {…}, bodyOnly: false, splitted: true, externalAssetsOnly: true, postMessageSyntax: 'ipcProxySendToHost', …}
/home/chris/.config/joplin-desktop/cache/joplin.plugin.ambrt.embedSearch/fence.js:1 ---ids----
/home/chris/.config/joplin-desktop/cache/joplin.plugin.ambrt.embedSearch/fence.js:1 embedSearch
/home/chris/.config/joplin-desktop/cache/joplin.plugin.ambrt.embedSearch/fence.js:1 joplin.plugin.ambrt.embedSearch
/home/chris/.config/joplin-desktop/cache/joplin.plugin.ambrt.goToItem/tagsNotebooks.js:1 {context: {…}, bodyOnly: false, splitted: true, externalAssetsOnly: true, postMessageSyntax: 'ipcProxySendToHost', …}
/home/chris/.config/joplin-desktop/cache/joplin.plugin.ambrt.backlinksToNote/notesReferences.js:1 foot tokens
/home/chris/.config/joplin-desktop/cache/joplin.plugin.ambrt.backlinksToNote/notesReferences.js:1 (13) [Token, Token, Token, Token, Token, Token, Token, Token, Token, Token, Token, Token, Token]
index.html:1 sending message
useMessageHandler.ts:16 Got ipc-message: noteRenderComplete undefined
useMessageHandler.ts:16 Got ipc-message: postMessageService.message {contentScriptId: 'backlinks', viewId: '', from: 'contentScript', to: 'plugin', id: 'noteViewer_16750939562570.15083531824042962', …}

**Comment by tessus** [comment]
I am afraid that PR https://github.com/laurent22/joplin/pull/6858 had more impact than we anticipated.

e.g. I certainly think that this is a bug, even though the backtick character is not technically a brace, but neither are single or double quotes.

@laurent22 I think we should add back the backtick character, since this is clearly a regression.

**Comment by wh201906** [comment]
I'm sorry for the regression I brought in #6858.
According to the docmuent from [CodeMirror](https://codemirror.net/5/doc/manual.html#addon_closebrackets), the default behavior is to auto-close ()[]{}''"". So I just added them to the `matchBracesOptions`.

> By default, it'll auto-close ()[]{}''"", but you can pass it a string similar to that (containing pairs of matching characters), or an object with pairs and optionally explode properties to customize it.

However, when skimming the code a few minutes ago, I found that the backticks is somehow considered for auto-matching, even if it is not in the default option.
https://codemirror.net/5/addon/edit/closebrackets.js
```
  var keyMap = {Backspace: handleBackspace, Enter: handleEnter};
  function ensureBound(chars) {
    for (var i = 0; i < chars.length; i++) {
      var ch = chars.charAt(i), key = "'" + ch + "'"
      if (!keyMap[key]) keyMap[key] = handler(ch)
    }
  }
  ensureBound(defaults.pairs + "`") // <-here is the backtick
```
I haven't got to know how it works.

**Comment by tessus** [comment]
@wh201906 no worries. It seems that the backtick is not added when we set the pairs manually. Anyway, my PR fixes the issue.

**Comment by laurent22** [comment]
What if someone wants to add three backticks to open and close a code block?

**Comment by tessus** [comment]
It's smart enough to detect that.


https://user-images.githubusercontent.com/223439/215774619-61f7b7fa-5da3-4bd1-bf18-b4c9ff76ed8e.mp4

**Comment by cjhabs** [comment]
That works on 2.8.8 and surrounds the text. 
But if you insert a return after the 3 backticks it removes the highlighted text.
That seems logical to me.

**Comment by Daeraxa** [comment]
In 2.8.8 on the first press it makes two backticks with the cursor between them. The second will "type" the second one and move the cursor on, the third will create the third backtick.

We should make sure that same behaviour works

Edit - Tessus beat me to it with a whole video
