### ISSUE TITLE
Joplin is filling up Nextcloud's trashbin

### ISSUE THREAD

**Issue by oculos** [laurent22/joplin#7706]
Hi,

I am using the latest Joplin on macOS. I sync to Nextcloud.
I realize that, after every sync, some files are dumped on my trashbin. I found it out because yesterday I saw that it was taking ages and lots of memory to simply access my "Deleted files" folder on Nextcloud, and I realize that tens of thousands of files where there dumped by Joplin.

Is there a way to fix it, or is this problem inherent to Nextcloud's Deleted files plugin, which dumps files on a trashbin instead of deleting them right away?

**Comment by laurent22** [comment]
It's a bug in that trashcan plugin, it makes webdav work in a non standard way, and there's nothing we can do on our side
