### ISSUE TITLE
WebDav sync error

### ISSUE THREAD

**Issue by RZarifov** [laurent22/joplin#7707]
This issue is already discussed here: https://github.com/laurent22/joplin/issues/6450  
And looks like the solution is to upgrade lighttpd?  
Why is it still not upgraded?  
Please upgrade it, so we could use webdav.  

## Environment

Joplin 2.6.10 (prod, linux)  

Client ID: ac8c7a9c17e242b4af22eda621a91035  
Sync Version: 3  
Profile Version: 41  
Keychain Supported: No  

Revision: 98fba37  

OS: Manjaro Linux, 5.15 kernel.  

## Steps to reproduce

1. try to setup webdav using keenetic
2. see 412 error
3. upgrade lighttpd?

## Describe what you expected to happen
No 412 error while syncing wia webdav.

**Comment by RZarifov** [comment]
Dug into it deeper and it looks like not joplin issue?  
How then people go around this?

**Comment by roman-r-m** [comment]
> Dug into it deeper and it looks like not joplin issue?

That's right.

> How then people go around this?

Use another WebDAV server? Or don't use WebDAV at all.
