### ISSUE TITLE
Chrome detect Joplin 1.0.106 setup as malware

### ISSUE THREAD

**Issue by pdifeo** [laurent22/joplin#771]
When I download the lastest version 1.0.106 Chorme tell me that the file is suspicius 

![image](https://user-images.githubusercontent.com/8618744/45261302-986b4780-b3ff-11e8-85fb-82317cc752f9.png)

Also VirusTotal recognize it as bad file (Bkav : HW32.Packed)

**Comment by laurent22** [comment]
This is because this version was not signed. It will be fixed in the next release.
