### ISSUE TITLE
During migration to new nextcloud 2 folders are created & I get the error: Last error: Error: href /remote.php/dav/files/xxxxxxx/Documents/joplin/locks/ not in baseUrl https://xxxxxx.io/remote.php/dav/files/xxxxxxxx/Documents/joplin nor relativeBaseUrl /remote.php/dav/files/xxxxxx/Documents/joplin

### ISSUE THREAD

**Issue by Forgev41** [laurent22/joplin#7710]
I've been using Joplin and it synchronization already for some time, but I need to move to a new nextcloud.
During setup of the Synchronization I get the error:
Last error: Error: href /remote.php/dav/files/xxxxxxx/Documents/joplin/locks/ not in baseUrl https://xxxxxx.io/remote.php/dav/files/xxxxxxxx/Documents/joplin nor relativeBaseUrl /remote.php/dav/files/xxxxxx/Documents/joplin

However the "Check synchronization configuration" says it's `Success! Synchronisation configuration appears to be correct.`

## Environment

Joplin version: Joplin 2.9.17 (prod, win32)

Client ID: ac505a44e1424e9b93b3add8d6aca901
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: a84a8e7
Platform: Windows
OS specifics: 10

## Steps to reproduce

1. I login into my nextcloud -> All files -> Settings at the bottom -> I copy the WebDav address.
https://xxx.io/remote.php/dav/files/name%40e.email/
2. Inside my nextcloud I go to `Documents`
3. I create the directory `joplin`.
So it is empty
![afbeelding](https://user-images.githubusercontent.com/12109871/216158460-9a1967ff-ff5f-4a24-86e7-cbac39030c78.png)
4. In Windows 10
5. I start Joplin
6. Menu -> Tools -> Options -> Synchronization
7. Syncrhonization target: <address copied in step 1>/Documents/joplin
8. Enter user name & password
9. Click button `Check synchronization configuration`
**Result:** `Success! Synchronisation configuration appears to be correct.`
10. Click `Show Advanced Settings`
11. Click `Re-upload local data to sync target`
![afbeelding](https://user-images.githubusercontent.com/12109871/216159302-bb00e860-6515-42a8-a7d9-f5698a851d8a.png)
12. Click on the `Ok` button
13. After some time this error shows:
Last error: Error: href /remote.php/dav/files/name@e.email/Documents/joplin/locks/ not in baseUrl https://xxx.io/remote.php/dav/files/name%40e.email/Documents/joplin nor relativeBaseUrl /remote.php/dav/files/name%40e.email/Documents/joplin
14. 2 Folders are created, I do see that 2 folders have been created:
![afbeelding](https://user-images.githubusercontent.com/12109871/216160642-dd6dc8a7-b35c-4e01-afa0-99cd7aab5138.png)
15. 

**However** I also tried copying all the files from my current webdav environment over to nextcloud, but then the same error occurs.

## Describe what you expected to happen
I expected that the synchronization would work and my local files being uploaded to nextcloud because I clicked the `Re-upload local data to sync target` button.

**Comment by tessus** [comment]
While you are at it, why don't you paste the .log file into the title?

Also, this is not a bug. Please use the forum.
