### ISSUE TITLE
The CPU utilization rate of Joplin on win11 suddenly increases

### ISSUE THREAD

**Issue by JulyLies** [laurent22/joplin#7715]
In my daily use, the CPU utilization rate of Joplin on win11 sometimes becomes suddenly high, and the whole system is stuck. After shutdown, the white screen is started
![joplin1](https://user-images.githubusercontent.com/73873604/216745678-7fc19d91-5b67-424a-a0c0-9e5dfde05359.png)
![joplin2](https://user-images.githubusercontent.com/73873604/216745807-b4309474-f1d3-47a8-bb54-633b2a2af94a.png)
![joplin3](https://user-images.githubusercontent.com/73873604/216745819-60277424-5aef-44a6-8cf0-1b2266f296d1.png)

## Environment
Joplin version: Joplin2.10.3
Platform: windows
OS specifics: windows11

**Comment by laurent22** [comment]
Usually due to a plugin. Which ones do you use?

**Comment by JulyLies** [comment]
Using these two, I can't reproduce this problem now. I'm sorry
[joplin-rich-markdown](https://github.com/CalebJohn/joplin-rich-markdown)
[joplin-macos-native-theme](https://github.com/andrejilderda/joplin-macos-native-theme)

**Comment by JulyLies** [comment]
> Usually due to a plugin. Which ones do you use?

Using these two, I can't reproduce this problem now. I'm sorry
[joplin-rich-markdown](https://github.com/CalebJohn/joplin-rich-markdown)
[joplin-macos-native-theme](https://github.com/andrejilderda/joplin-macos-native-theme)

**Comment by benmordecai** [comment]
I've had severe performance issues from the macOS plugin on both Windows 11 and on Arch Linux to the point that Joplin was completely unresponsive when the MacOS plugin was enabled.

**Comment by benmordecai** [comment]
Not resolved, but not confirmed the root cause
