### ISSUE TITLE
Add a toolbar which simplify markdown decorations entering

### ISSUE THREAD

**Issue by MontiniCristian** [laurent22/joplin#774]
I'm thinking to something like that:

![](https://i.imgur.com/D3QZLMx.jpg)

Source: Fasthub, an android git client

**Comment by nr458h** [comment]
Already asked in #691, but closed because of technical debt

**Comment by MontiniCristian** [comment]
@nr458h man, we had the same idea by writing from the same application, stupidly I was so enthusiastic that I did not check for a similar issue. Thanks

**Comment by laurent22** [comment]
React Native changes fast so it's possible they'll eventually fix the bug that prevents this toolbar from existing. The code is already here in some branch, we just need the React Native fix.
