### ISSUE TITLE
With Custom Sort, new notes appear at bottom and later randomly "pop" to the top

### ISSUE THREAD

**Issue by TaoK** [laurent22/joplin#7741]
## Environment

Joplin version: Joplin 2.9.17 (prod, win32)
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Set sort to "Custom order"
2. Uncheck "Uncompleted to-dos on top" and check "Show completed to-dos" to avoid interference from issue #7731 
3. Add several notes in a notebook
4. Drag-drop to reorder any note (some surprising reorganization may happen)
5. Start a new note (with some content) -> it will appear at the bottom of the list
6. Drag-drop a *different* note to a new position -> the note you previously created will "pop" to the top of the notebook
7. Start a new note (with some content) -> it will appear at the bottom of the list
8. Drag-drop the note you just created to a new position -> it will appear one slot higher than where you dropped it.
9. Start a new note (with some content) -> it will appear at the bottom of the list
10. Start a new note (with some content) -> it will appear *one slot above the one you just created*

## Describe what you expected to happen

There are three "misbehaviors" here:
* When creating new notes, they are not consistently or coherently positioned (after a re-sort the next note is at the bottom, but after creating notes, new ones appear above recently-created ones)
  * I expect new notes to appear somewhere consistent and predictable:
    * Always at the top, or
    * Always at the bottom, or
    * Above the currently selected note, or
    * Below the currently selected note.
  * None of these predictable behaviors currently occur.
* When reordering notes, newly created notes "shift" unexpectedly to the top of the notebook
  * I expect notes to "stay still" when I move other notes around
* When reordering a newly-created note, it does not land where you place it, but typically one slot higher
  * I expect notes to stay where I drop them

**Comment by TaoK** [comment]
**Technical explanation for this issue:**

Ignoring the "Uncompleted to-dos at top" feature, the sort logic for "custom sort" is "sort_value DESC, created_date DESC".

When notes are newly created, they have a "sort order" of 0 - the lowest possible value - so they appear at the bottom. Additional new notes (without an interim re-sort) have the same "0" sort value, but a newer creation date, so they appear above the previously created ones. 

When a drag-drop reorder even occurs, there is a "sorting sanity" process that kicks in, setting sort values to any notes that don't have one - and that value is the current date/time, the highest possible sort value, so the new notes "pop to the top".

If the drag-drop reorder event concerns a new note, that note will "pop up" (shifting other notes down one) *before* being inserted at the desired position - and when it *is* moved to the desired position, it will be moved away/down - shifting all the other notes back to their original position, but the newly-moved note one higher than was intended.

**Fix proposal**

The fundamental fix required in this issue is for a sort value to be set as new notes are created, so that they don't get a completely different sort value assigned some arbitrary time later.

The challenge, however, is to determine what a most appropriate "initial sort value" might be. The easiest to implement, and maybe most reasonable, would be to always implicitly set the current time - the same that would otherwise later happen, and have new notes always appear at the top of custom sort.

A possibly-more-sophisticated strategy would be to set the sort value right above or below the currently selected note.

The strategy most consistent with current & historical behavior would be to have new notes appear at the bottom - with a sort value that is non-0 (so no "popping" later), but lower than the lowest previous note.


I would love to see opinions about what would be preferable and why.

**Comment by TaoK** [comment]
**Alternative fix proposal**

Another way of approaching this issue is to argue that the problem is not the fact that new Notes lack a sort value, but rather that any sort activity, when there are existing items without sort values, sets *arbitrary* new sort values to those existing items (thereby popping them to the top at that time).

A more coherent fix could be to have the sort-value-allocation process, for missing-sort-value items, create sort values to maintain the exact existing sort; basically, if you perform a sort operation on a note list that contains zero-sort-value items, there will be an initial/prior sort pass that will sort the zero-value items into their exact current position.

This would fix the issue *not only* for new Notes going forwards, but also for **existing notes** that never had their sort set.

On the other hand, wrt the list of "misbehaviors" above, the first would not be addressed: When you create multiple new notes in sequence without reordering, the newest would always appear at the top of that set. After a reorder event, the newest one would appear at the bottom again. 

Fixing this behavior to something such as "by default, position a new note above the currently selected note" would be a **separate** enhancement or bugfix, rather than being addressed here.

~~This approach would need to build on Pull Request #7737 - it would need to use the correct sort order in this newly improved "pre-sort" operation.~~ (after working on this, a much simpler solution presented itself)

**Comment by laohuzhigege** [comment]
good thankyou

**Comment by DMClVG** [comment]
This is also the case in the "Notebooks" panel--except, of course, there is no custom ordering.
