### ISSUE TITLE
Confusing sync behavior in iOS app

### ISSUE THREAD

**Issue by pekkavaa** [laurent22/joplin#7750]
## Environment

Joplin version: 12.9.2
Platform: iOS
OS specifics: latest, Joplin Cloud synchronization

## Steps to reproduce

1. Create a new note in Joplin Desktop
2. Synchronize the new note by clicking the button and wait until it's done
3. Open iOS Joplin App
4. Tap Synchronize in the app

## Describe what you expected to happen

The newly added note would appear.

However, after tapping the Synchronize button in the iOS app, only older changes appeared. I had to tap the synchronize button again for the newly added note would appear.

## Logfile

![image](https://user-images.githubusercontent.com/934568/217668159-2f12b07c-1425-4573-89a3-8d82d7ffa5ab.png)

**Comment by personalizedrefrigerator** [comment]
Sorry for the late reply! Make sure that the device date and time is correct on both devices (not having correct date/time is known to cause sync issues).
