### ISSUE TITLE
Latest stable version is missing from Google Play Store

### ISSUE THREAD

**Issue by Solomon1732** [laurent22/joplin#7754]
## Environment

Joplin version: 2.8.1
Platform: Android
OS specifics: Samsung A73, Android 13

## Steps to reproduce

1. Go to the play store
2. Check its current version
3. It's 2.8.1

## Describe what you expected to happen

I expected for the version to be the latest stable one, 2.9.17

### Google Play Store version

![Google Play Store](https://user-images.githubusercontent.com/16454223/218101137-4f25ba2c-96ac-4fd6-b532-7ff4b298912f.jpg)

### Current latest stable version

![Stable version](https://user-images.githubusercontent.com/16454223/218101168-9ecfd33d-54ba-4f4b-bd7b-9a4ba524fa9a.jpg)

**Comment by dpoulton-github** [comment]
The reason for this is explained on the forum.

> Unfortunately we cannot publish the Android version because it is based on a framework version that Google does not accept. To upgrade the app a lot of changes are needed and another round of pre-releases, and therefore there will not be a 2.9 version for Google Play. You may however download the official APK directly from there: [Android 2.9 Official Release](https://github.com/laurent22/joplin-android/releases/tag/android-v2.9.8)
>
>This is the reality of app stores in general - small developers being imposed never ending new requirements by all-powerful companies, and by the time a version is finally ready we can't even publish it because yet more requirements are in place.
>
> For the record the current 2.9 app works perfectly fine. It targets Android 11, which is only 2 years old and is still supported (and installed on millions of phones). Google requires us to target Android 12 which only came out last year.

_https://discourse.joplinapp.org/t/whats-new-in-joplin-2-9/28661#about-the-android-version-9_

**Comment by Solomon1732** [comment]
Unfortunate, but undersandable. I'll close the issue. I hope you'll have more luck with 2.10.

Edit: Rephrased to reflect my intentions better.
