### ISSUE TITLE
Android app feedback 

### ISSUE THREAD

**Issue by samtuke** [laurent22/joplin#7756]
I don't see a better place to share this product feedback, which is based on android app testing. Please forward elsewhere as desired. It's intended for input to someone in a product management role. Not a support request. No support or other reply expected or required. 

My use case: ceo of small business. Looking for a primarily personal note taking app to replace simplenote. Main motive to switch from simplenote: lack of gtd support. 

My requirements: Gtd methodology desired though I'm not using it now. Preference for open source. Need seamless sync on android and Linux. Top priority: not losing data / notes created. Next priority: data portability and compatibility (also to not lose access to data in future, and for searching and editing using powerful cli tools in future). 

I have a nextcloud business server but don't want to use it for note sync because the technologies aren't sufficiently reliable. 

I'd be happy to pay up to 25$ per user per month for this app if it met my criteria. 

- Joplin doesn't work for me because
  - min sync interval is 5 mins. Too risky. I'll lose data between sync. 
  - no unlimited storage of note history. This keeps my notes, mistakes, deletions safe. I don't want history deleted ever. 
  - ux of app is not designed for Joplin cloud. It's just another sync target. I want confidence that it's a first class citizen with priority integration. No wizard, onboarding etc in the android app. I expect it to be just as buggy as any other sync provider therefore.
  - no obvious way to use gtd methodology
  - I go to make a feature request. Github directs me to the forum. The forum has many relatively recent reports of completely data loss, which makes me conclude my notes won't be safe.
  - generally the ux of the app looks identical to years ago when I first tried it, indicating that there's little real progress. I want to see signs of frequent updates and improvements to the app and that the devs take ux seriously.
  - github and the app itself (donation requests) feel like the app is still made by one person and dependet on them. Not on a company with proper product management and ux expertise. Which makes me expect a poor ongoing experience with it, and high risk of development slow down or death in future (single point of failure).

Hope that's helpful.

**Comment by laurent22** [comment]
Hello, this is a bug tracker so not the place for feedback. Based on a quick read, it seems Joplin is indeed not for you
