### ISSUE TITLE
Joplin fails to open on upgrade to Linux Kernel 6.x 

### ISSUE THREAD

**Issue by speightashley** [laurent22/joplin#7761]
Upon a system upgrade on Manjaro Linux, I tried to open Joplin and it closes straight away.

The upgrade was an upgrade of the Kernel. I was running 5.15 initially which works perfectly fine.

I can repair the issue by reverting back to 5.15 but doing this keeps me locked in the past.

Terminal output:

`update.go:85: cannot change mount namespace according to change mount (/run/user/1000/doc/by-app/snap.joplin-desktop /run/user/1000/doc none bind,rw,x-snapd.ignore-missing 0 0): cannot inspect "/run/user/1000/doc": lstat /run/user/1000/doc: permission denied
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" subproperty "joplin" setting to invalid value "@joplin/app-desktop.desktop"
Gtk-Message: 15:17:16.363: Failed to load module "xapp-gtk3-module"
zsh: trace trap (core dumped)  joplin-desktop`

## Environment

Joplin version:  2.9.17
Platform: Manjaro Linux
OS specifics:  Kernel 6.2 / Gnome 43.2 / Material Shell

## Steps to reproduce

1.  Switch Kernel from 5.15 to 6.2
2.  Restart
3.  Open joplin from the app loader / Terminal

## Describe what you expected to happen

Joplin to open as it always has
[joplin-log.txt](https://github.com/laurent22/joplin/files/10723155/joplin-log.txt)

**Comment by JGCarroll** [comment]
The `6.0` kernel series had issues with their Squashfs implementation that broke snaps, fixed in `6.0.7`

`6.1` is stable now and also likely to be an LTS release, so upgrading to it is likely ideal.

https://lore.kernel.org/lkml/20221020223616.7571-1-phillip@squashfs.org.uk/
