### ISSUE TITLE
Android: monochrome icon doesn't work

### ISSUE THREAD

**Issue by fobo66** [laurent22/joplin#7766]
The icon on Android doesn't follow the system color palette. As I can see, the app has the monochrome icon [specified](https://github.com/laurent22/joplin/blob/dev/packages/app-mobile/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml), but because it's a raster image, adaptive colors are not applied, and the icon is displayed with the default background. It looks like an implicit requirement, because there is no such info in the [docs](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive), but it doesn't work with raster monochrome icons.

The fix for it could be to use vector foreground icon. There is already some vector icon in the [assets](https://github.com/laurent22/joplin/blob/dev/Assets/JoplinLetter.svg) that we can convert to VectorDrawable and use in the app. I can help with that.

## Environment

Joplin version: 
Platform: Android
OS specifics: Android 13 on Samsung S22, OneUI 5.0

## Steps to reproduce

1. Enable color palette for app icons
2. Drag Joplin icon on the home screen
3. Observe the icon

## Describe what you expected to happen

Icon should follow general color palette

**Comment by laurent22** [comment]
Happy to accept a pull request if you know how to get this working
