### ISSUE TITLE
Implement eslint-plugin-prefer-arrow-functions rule

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#7771]
We should only use arrow function expressions (`const onSetAttrib = (...)`). This is because `function` implicitly creates a `this` variable inside the function, and that has made refactoring more difficult in the past.

See if we can add `eslint-plugin-prefer-arrow-functions` and if possible convert the whole codebase to arrow functions (it sounds like the plugin supports auto-fix).

**Comment by pedr** [comment]
I'm doing some tests trying to run the auto-fix but I'm not sure if it is the best idea.

For example, it seems like the auto-fix has a bug with the `$` character. Many parts of the code have similar mistakes

![aa(1)](https://user-images.githubusercontent.com/5051088/219809874-83bd2be8-de4a-4afc-a3d0-658f588e6ae1.png)

I think it is probably a lib bug, but I'm trying to understand it better

**Comment by laurent22** [comment]
Hmm, yes that's weird. Maybe try to report it on the plugin repo? Or perhaps it's something we can fix

**Comment by pedr** [comment]
It seems like it was my mistake by trying to run the auto-fix with the option `singleReturnOnly` set to `false`, which is not a supported option for the auto-fix (there is some documentation about it in the original npm package https://www.npmjs.com/package/eslint-plugin-prefer-arrow that seems to be abandoned).

Running the auto-fix with the `singleReturnOnly` option set to `true` doesn't seem to cause any errors but a function like the one below would not be converted and I'm not sure why. I'm going to look into that tomorrow.

```javascript
function newBlockSource(language = '', content= '', previousSource= null) {
	let fence = '```';

	if (language === 'katex') {
		if (previousSource && previousSource.openCharacters === '$') {
			fence = '$';
		} else {
			fence = '$$';
		}
	}

	const fenceLanguage = language === 'katex' ? '' : language;

	return {
		openCharacters: fence === '$' ? '$' : `\n${fence}${fenceLanguage}\n`,
		closeCharacters: fence === '$' ? '$' : `\n${fence}\n`,
		content: content,
		node: null,
		language: language,
	};
}
```

```
'prefer-arrow-functions/prefer-arrow-functions': [
	'error',
	{
		'classPropertiesAllowed': false,
		'disallowPrototype': true,
		'returnStyle': 'unchanged',
		'singleReturnOnly': ,
	},
],
```
