### ISSUE TITLE
Mobile: Note link long-press logs error

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#7773]
## Environment

Joplin version: 7d7b7ed6f37102a123ee6322567b7ab62f8fd750
Platform: Mobile
OS specifics: Both Android 13 and iOS 16.3

## Steps to reproduce

1. Create a new note (note A)
2. Create another note (note B)
3. Add a link to note A in note B.
4. Long-press on the link.

## Describe what you expected to happen
No error should be added to the log/logged to the console.

## Logfile
Relevant portion of the log:
```
 INFO  Got IPC message:  longclick:56d632433de045a9b0a44730d8f84b68
ERROR: Could not handle link long press [TypeError: null is not an object (evaluating 'resource.title')]
```

The error is logged in `packages/app-mobile/components/NoteBodyViewer/hooks/useOnResourceLongPress.ts`, line 36.
https://github.com/laurent22/joplin/blob/7d7b7ed6f37102a123ee6322567b7ab62f8fd750/packages/app-mobile/components/NoteBodyViewer/hooks/useOnResourceLongPress.ts#L36

**Comment by personalizedrefrigerator** [comment]
Still an issue.

**Comment by personalizedrefrigerator** [comment]
Still an issue.

**Comment by Tolu-Mals** [comment]
I want to work on this
