### ISSUE TITLE
F-Droid Repo version is marked as incompatible with arm64-v8a

### ISSUE THREAD

**Issue by kpspu** [laurent22/joplin#7779]
Hi, have a nice day!
I have just bought Google Pixel 7 Pro and noticed that Joplin Android 2.9.8 from F-Droid Repo marked as incompatible with arm64-v8a.
I installed 64bit version directly from GitHub, but worrying about automatic updates. I'm not sure I will get updates because of incompatibility.
Is it possible to mark Joplin as compatible with arm64-v8a?

**Comment by tomasz1986** [comment]
There is no Joplin in the official F-Droid repository. You must be using a 3rd party repository, so it's likely that the maintainer of that must be the one who marks the APK as compatible with arm64-v8a.

**Comment by kpspu** [comment]
Didn't know that. Thank you!
