### ISSUE TITLE
Feature Request: Store Notebook Data In Seperate Folders To Allow Partial Share

### ISSUE THREAD

**Issue by KlausHans** [laurent22/joplin#778]
Hello, i didn't found any similar issue so i open this.

If i am not mistaken it is currently impossible to have a personal notebook and a share notebook that gets shared via the host service (e.g. Nextcloud). I can only go full share (share the folder via Nextcloud for example) or full personal (share nothing via Nextcloud).
The data gets saved flat in my Joplin folder with some hashes and i can not distinguish between notebooks.

The solution would be simple, i think: the data of every notebook needs a own folder. This way i could share only the folder and thus only one notebook.

### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile

**Comment by laurent22** [comment]
Closed as duplicate

**Comment by KlausHans** [comment]
Can you please link the existing issue?

**Comment by devzsolt** [comment]
> Can you please link the existing issue?

I guess it's https://github.com/laurent22/joplin/issues/336
