### ISSUE TITLE
v2.10.4 Pre-release - "Enable encryption" button does not trigger encryption dialog

### ISSUE THREAD

**Issue by dpoulton-github** [laurent22/joplin#7797]
## Environment

Joplin version: 2.10.4 pre-release
Platform: Windows 10 pro x64 (Virtual Machine)
OS specifics: 22H2

## Steps to reproduce

1. Install Joplin Desktop.
2. Go to **Tools > Options > Encryption**.
3. Under **End-to-end Encryption** press the **Enable encryption** button.
4. The button changes colour to show it has been pressed but nothing happens.

![Encryption_Button](https://user-images.githubusercontent.com/60117449/219813540-a9977bee-6731-4b78-abd3-9ef29abf17ce.gif)

## Describe what you expected to happen

The encryption set-up dialog should appear.

## Logfiles

The below logs were produced when following the above steps and pressing the **Enable encryption** button twice.

### Joplin log

[log.txt](https://github.com/laurent22/joplin/files/10772192/log.txt)

### Console log

```text
C:\Users\vbox\AppDat…r\gui\dialogs.js:16 Uncaught (in promise)
TypeError: smalltalk.alert is not a function
    at Dialogs.<anonymous> (C:\Users\vbox\AppDat…ui\dialogs.js:16:29)
    at Generator.next (<anonymous>)
    at C:\Users\vbox\AppDat…gui\dialogs.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\vbox\AppDat…gui\dialogs.js:4:12)
    at Dialogs.alert (C:\Users\vbox\AppDat…ui\dialogs.js:15:16)
    at C:\Users\vbox\AppDat…figScreen.js:181:37
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\vbox\AppDat…onfigScreen.js:6:65)

C:\Users\vbox\AppDat…n\lib\Logger.js:190 19:11:45: e2ee/utils: toggleAndSetupEncryption: enabled: true  Master key null

C:\Users\vbox\AppDat…r\gui\dialogs.js:16 Uncaught (in promise)
TypeError: smalltalk.alert is not a function
    at Dialogs.<anonymous> (C:\Users\vbox\AppDat…ui\dialogs.js:16:29)
    at Generator.next (<anonymous>)
    at C:\Users\vbox\AppDat…gui\dialogs.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\vbox\AppDat…gui\dialogs.js:4:12)
    at Dialogs.alert (C:\Users\vbox\AppDat…ui\dialogs.js:15:16)
    at C:\Users\vbox\AppDat…figScreen.js:181:37
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\vbox\AppDat…onfigScreen.js:6:65)
```
*Console log text*🡅

![console_log](https://user-images.githubusercontent.com/60117449/219813296-ba94c5da-22aa-405a-8324-ff2d9d8f169e.png)
*Console log screengrab showing error highlights*🡅

## Other information

- File system sync to a local folder on the same disk.
- Default install, no plugins. no modifications, no notes added.
- This is not intermittent. Testing so far with this set-up has a 100% failure rate.
- Following a downgrade to 2.9.17, with the same system set-up, the **Enable encryption** button works and the dialog is triggered.
- Linked forum post 🡆 [*Joplin 2.10.4 (pre-release) can’t Enable encryption*](https://discourse.joplinapp.org/t/joplin-2-10-4-pre-release-cant-enable-encryption/29601).

**Comment by dpoulton-github** [comment]
The above issue can also be replicated using Joplin v2.10.4 and the following environments:

- Windows 11 Pro 21H2
- Linux Mint 20.3 Cinnamon
- Linux Mint 21.0 Cinnamon (upgraded from Mint 20.3)
- Kubuntu 22.04 (KDE Plasma 5.25.5)
- KDE Neon 5.27 (KDE Plasma 5.27)
- Ubuntu 22.04 LTS

**Comment by melsonic** [comment]
can I work on this one?

**Comment by dpoulton-github** [comment]
Didn't see it mentioned in the release notes for v2.10.6 but the **Enable encryption** button in v2.10.6 is now working and the dialog displays. No console errors seen. Tested using Windows 10 (same VM as above) and Linux Mint 20.3.

![joplin_2 10 6_encryption](https://user-images.githubusercontent.com/60117449/220197604-198b4ec4-f0a2-48e5-93e4-0c62acc21430.png)

**Comment by pedr** [comment]
I tested this yesterday in the dev version too, and I can confirm that is fixed.

**Comment by laurent22** [comment]
Ok great, let's close then, thanks for looking into it
