### ISSUE TITLE
Any contributing guide?

### ISSUE THREAD

**Issue by flipjs** [laurent22/joplin#78]
I couldn't find a contributing guide in the repo. If there is, could you please direct me where to find it? Im interested in contributing specially for the terminal application. There are some issues posted here already that I'd like to work on that could also be useful for me. Thanks.

**Comment by 3DJetengine** [comment]
you could do that on [wikibooks](https://en.wikibooks.org/w/index.php?search=joplin&title=Special:Search&profile=advanced&fulltext=1&ns0=1&ns3=1&ns4=1&ns7=1&ns102=1&ns110=1&ns112=1)

**Comment by laurent22** [comment]
There's no contributing guide at the moment but feel free to open a pull request anyway. If an issue regularly comes up in pull requests, I'll add them to a guide.
