### ISSUE TITLE
Markdown Editor Code Block 

### ISSUE THREAD

**Issue by Carl-Be** [laurent22/joplin#7805]
## Environment

Joplin version: Joplin 2.9.17 (prod, darwin) 
Platform: macOS 
OS specifics: Ventura 13.1 (22C65)

## Steps to reproduce

1.  Use $$ before the code block in the editor window within a markdown table
2.  create a code block below the table

Incorrect Code Block Display (no highlighting):
<img width="662" alt="image" src="https://user-images.githubusercontent.com/63538326/219949314-3a586b8d-4a86-4437-9373-8efdd77ca84c.png">

Code block highlighting disappears in the markdown editor when preceded by $\$ within a table.  However, this is corrected when using an escape character. Moreover, the escape character is not needed to display a double $  in the markdown viewer table.

## Describe what you expected to happen
A working code block like the control code block in the above picture. 

## Logfile

[-1676812037766.log](https://github.com/laurent22/joplin/files/10776934/-1676812037766.log)
<img width="894" alt="image" src="https://user-images.githubusercontent.com/63538326/219950045-a144a917-6b88-4e80-ab59-c1dcc6e56028.png">

**Comment by dpoulton-github** [comment]
`$$` is a control code to signify Katex. This is possibly confusing the editor. Escaping one of the dollar signs (`\$$`) so that it cannot be confused with a Katex marker should make the second code block work properly.

**Comment by LightAPIs** [comment]
Because `$$` is a wrapper string of [Math notation](https://github.com/laurent22/joplin/blob/dev/readme/markdown.md#math-notation), if you don't intend to use it, you should disable "Options/Markdown/Enable math expressions" or always escape `$`.

**Comment by Carl-Be** [comment]
Interesting, I understand the notation; ~~however, it does not break the table like it brakes the code block.  Any thoughts?~~ 

Edit: Never mind.
