### ISSUE TITLE
joplin doesn't start on linux mint 21.1 

### ISSUE THREAD

**Issue by fmk64** [laurent22/joplin#7811]
Hi,
Joplin app doesn't start in my new linux mint 21.1 install:
Please check following journal:
Thx for your help, I have many important files on this joplin/nextcloud files.

17:47:34 systemd-coredum: Process 420705 (@joplinapp-desk) of user 1000 dumped core.

Found module /tmp/.mount_Joplin3cC145/@joplinapp-desktop with build-id: 00575f24f6c10741380ab1964d91017633f6ccf2
Found module /tmp/.mount_Joplin3cC145/usr/lib/libXtst.so.6 with build-id: 0403493a3501094414e75b977548928a413d8146
Found module /tmp/.mount_Joplin3cC145/libffmpeg.so with build-id: 6ac3f596c64ad6f3e9a28afd34503016f2445683
Found module linux-vdso.so.1 with build-id: 6a61cf67fbc559c10e60ed0adeb9ab5e42248a3c
Found module libresolv.so.2 with build-id: 7fd7253c61aa6fce2b7e13851c15afa14a5ab160
Found module libkeyutils.so.1 with build-id: ff27227afa5eeddccab180dd29bd7fcff94aea7c
Found module libbrotlicommon.so.1 with build-id: 43a72967cf84155914c8b3e915926733d1e57c11
Found module libgpg-error.so.0 with build-id: 3fbec71c67bee60d8aef00697ee187079b0fb307
Found module libmd.so.0 with build-id: cd2d2f71b3967ebde30e2aa43b8eb63339020c06
Found module libgmp.so.10 with build-id: f110719303ddbea25a5e89ff730fec520eed67b0
Found module libhogweed.so.6 with build-id: 3cc4a3474de72db89e9dcc93bfb95fe377f48c37
Found module libnettle.so.8 with build-id: 3d9c6bf106ef53d625b7b1c8bb1300e84598a74a
Found module libtasn1.so.6 with build-id: 2fde6ecb43c586fe4077118f771077aa1298e7ea
Found module libunistring.so.2 with build-id: ca5149da8d5a298b8f286ffca3d6e2402ec0fe01
Found module libidn2.so.0 with build-id: 45b73e0e1c46a76be22f572ee98c60af5768bf8f
Found module libp11-kit.so.0 with build-id: a0ffe1d002de5812dc718186172efb78604ddf2c
Found module libkrb5support.so.0 with build-id: 60c3bf331f85f4be0c25e701818c2cd36b1b8b9c
Found module libcom_err.so.2 with build-id: ce0901f10854b3c9276066b98d9a72303206e0d5
Found module libk5crypto.so.3 with build-id: 48fa2634690fb84d81748073f60fe2759fc09ba8
Found module libkrb5.so.3 with build-id: ae22aca5575bb9ec63eb47a7c2d04ad9802d92d4
Found module libbrotlidec.so.1 with build-id: 4b1f390dd6e24d49684db8b2443d082379e8e977
Found module libdatrie.so.1 with build-id: 128b6874a47f2b783d9e9060d3caaee4110bfd3d
Found module libuuid.so.1 with build-id: 64c0d0cb22fa2bdeca075a0c0418ba5ff314b220
Found module libgraphite2.so.3 with build-id: 5ffbc76fc948f6b88d766a7210c2e6a329a6c278
Found module libgcrypt.so.20 with build-id: 60a5e524de0ed8323edf33e9eb9127a9eee02359
Found module libcap.so.2 with build-id: 9e11e3bca4b0a25d047cb36e933e1d727663cf8e
Found module liblz4.so.1 with build-id: a85971851cd059f1af80d553c8e7170d42ec59a1
Found module libzstd.so.1 with build-id: 5d9d0d946a3154a748e87e17af9d14764519237b
Found module liblzma.so.5 with build-id: b85da6c48eb60a646615392559483b93617ef265
Found module libbsd.so.0 with build-id: 9a6c72469251e2feb63e175ef5cb944ce6e00df3
Found module libpcre2-8.so.0 with build-id: 184a841c55fb7fe5e3873fcda8368c71016cd54c
Found module libblkid.so.1 with build-id: cdf95a964e3302bb356fefc4b801fae8c4340b31
Found module libgnutls.so.30 with build-id: b9fa7b6d0c47adb8a3f03b2452c3df3eb2c93715
Found module libavahi-client.so.3 with build-id: bfe4357823739cfde10dbc3a40971c391bee9c41
Found module libavahi-common.so.3 with build-id: 5e23004fad8b0b7f921dcff3df5f9855904f45d2
Found module libgssapi_krb5.so.2 with build-id: 1b957c0ba6d4ac8e5db64652bbcf553c3ebad23b
Found module libwayland-server.so.0 with build-id: 75c4598a62c3c6e94868467866488cdfba049e7d
Found module libxcb-render.so.0 with build-id: cb521131fd3b0f2ee6056cbc2014b3b8ef0d5c0e
Found module libxcb-shm.so.0 with build-id: edb24ef4079aa423edcc50a3bb0dfb912fe8a57a
Found module libfreetype.so.6 with build-id: e3aff1d56fb1aecc723a73882f7d0f208a36c4bc
Found module libpixman-1.so.0 with build-id: 5e936cdac032b6048d9d1a8c0bb0e4a10c86d48c
Found module libthai.so.0 with build-id: afa54530349e68380815d606d15dbfda8952799f
Found module libwayland-client.so.0 with build-id: a85980f4efa33fa5cadfbf257349fef99d499427
Found module libwayland-egl.so.1 with build-id: e13dfac5961e8fb58c54984fe8110a73c2f5ef99
Found module libwayland-cursor.so.0 with build-id: abcd1ab467757354ac36fd0938b82d47d7aebe1f
Found module libxkbcommon.so.0 with build-id: a4b17d939092101dc8f6b2a1d70eaf1fddb2dd51
Found module libXinerama.so.1 with build-id: 9823bebfa26a681265db4aeb09abf44deec38401
Found module libfontconfig.so.1 with build-id: 0bb435fdd5ec37178e14ea03bb36f779a4b72a94
Found module libharfbuzz.so.0 with build-id: 3b9c495c079286b8d1f55d0937a0a771593eb7e6
Found module libpangoft2-1.0.so.0 with build-id: a7dd79c7ea8ec4d5791f83f9a8f34ffbfa8c3801
Found module libfribidi.so.0 with build-id: 6e075a666e1da8ffdb948d734e75d82b1b6dc0fb
Found module libepoxy.so.0 with build-id: 5ea53a2b100e4b044eee19d5222881a724abf046
Found module libcairo-gobject.so.2 with build-id: 71b5bd37d77ea1862d2ed00e9f6ead482f307db8
Found module libjpeg.so.8 with build-id: c54abff9294357e28532a76a049a4cb2542fc15b
Found module libpng16.so.16 with build-id: d58bf7c11ac793d528926238d831792b5ef792cf
Found module libsystemd.so.0 with build-id: 61fb1ea64197576f79977fb27e1be39a088e7f3e
Found module libplds4.so with build-id: 7a42de24ba93c1411714c1bf4179f213861ca88d
Found module libplc4.so with build-id: 5a402ce5ec0224c4d29815c4e15334d92f6ecf05
Found module libXdmcp.so.6 with build-id: 6b60f99504aa1d3999ea02a14366d1a39d6c5dcf
Found module libXau.so.6 with build-id: 7089b383cacbfc1760634a3be19a923e51fe3315
Found module libselinux.so.1 with build-id: 6fa53202ce676297de24873c886443b2759bfd8a
Found module libmount.so.1 with build-id: eeb33f2b4b9c3eb0a29575eb9932ef08663bd836
Found module libz.so.1 with build-id: 30840b79ac329ecbf1dec0bb60180eed256d319f
Found module libgmodule-2.0.so.0 with build-id: 991a9f61e69c30ef8ab73761c300ae51249ede63
Found module libpcre.so.3 with build-id: 3982f316c887e3ad9598015fa5bae8557320476a
Found module libffi.so.8 with build-id: 59c2a6b204f74f358ca7711d2dfd349d88711f6a
Found module ld-linux-x86-64.so.2 with build-id: 61ef896a699bb1c2e4e231642b2e1688b2f1a61e
Found module libc.so.6 with build-id: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d
Found module libgcc_s.so.1 with build-id: 09c4935b79388431a1248f6a98e00d7dc81b8513
Found module libcups.so.2 with build-id: d3f64a3ab859de045e124a0271356296fa446150
Found module libatspi.so.0 with build-id: 2843c68233d5ba81da3d6bc31422e49472873dba
Found module libasound.so.2 with build-id: d1986cd985564afaa9aa64c753423b01dd5b228e
Found module libgbm.so.1 with build-id: 89a16c18f7aa117775d69c8bd00dffd3fb6ec23d
Found module libdrm.so.2 with build-id: 9c7cb19295d20e515902cb0710326a0b8d6394c8
Found module libexpat.so.1 with build-id: d212d1f61d04a1e60fccad1a8c118428cfd9be42
Found module libXrandr.so.2 with build-id: 069f930a2b41f3908a1a92b1a51c38bd13a559e2
Found module libm.so.6 with build-id: 27e82301dba6c3f644404d504e1bb1c97894b433
Found module libcairo.so.2 with build-id: 60a39c3684e41370bd0a59ed1ecbdccf47e30069
Found module libpango-1.0.so.0 with build-id: 2d778a30dd59c0673b0208c538999ccc0991093a
Found module libpangocairo-1.0.so.0 with build-id: cb231e62ccba07e561d1d08804e975f615a6faf6
Found module libgdk-3.so.0 with build-id: 97b768ef80858a79741be2492754d948989e63c6
Found module libgtk-3.so.0 with build-id: 9a340345f5e200f42140f3cb4bacb407e91843f8
Found module libgdk_pixbuf-2.0.so.0 with build-id: 374b383e3b68b5d8b552519094129f401596e502
Found module libdbus-1.so.3 with build-id: 63e8b99215502138cb63afd6d65851a5e837ed49
Found module libatk-bridge-2.0.so.0 with build-id: 7e8009077fbdcd7bf094c51bf78742b96f216d73
Found module libatk-1.0.so.0 with build-id: b93088667fbd06f6b72d273403d352e7c0554698
Found module libnspr4.so with build-id: e3e4d4d1a1147e472eccb52c81c7900edd363c43
Found module libsmime3.so with build-id: 292adbee233a91d925fd9ee6383937642dfabd74
Found module libnssutil3.so with build-id: b24a1ca29f12cf954fe008d91fdb385f813cce7f
Found module libnss3.so with build-id: 8b792587a5804b3f7a31761a10d2b45fdfed054b
Found module libXrender.so.1 with build-id: 7ccbfa4c24e93c42fa50dd2e42fa277630f9650c
Found module libXi.so.6 with build-id: 8ff5a3ac871a90fd9d0a7917c61f748a41c6b5ee
Found module libXfixes.so.3 with build-id: a9c550a40b8154a3b4b5e2ac182bb50c013c3f18
Found module libXext.so.6 with build-id: 9fb1880e02dfa11a8c39cd1a170109de08302059
Found module libXdamage.so.1 with build-id: 8358b7625700dc247fa21fb4304cba877a28bb04
Found module libXcursor.so.1 with build-id: d936a5db46d8babb0f2cc490df36b6b18a16d8aa
Found module libXcomposite.so.1 with build-id: 2c84db5342304ba1a76db7dd9b7a3bfaa8a716ce
Found module libxcb-dri3.so.0 with build-id: b6aa69fda711358025ae4dd29fa597866d29b8c5
Found module libxcb.so.1 with build-id: 1bef862a339557aa16c34c7a4b27f8f3aea90517
Found module libX11-xcb.so.1 with build-id: 916a9b062e61b0310210ae16428615ebbe01c87d
Found module libX11.so.6 with build-id: b8d9314a7185312e4813abcac67d8b68ae2fd690
Found module libgio-2.0.so.0 with build-id: 9b52271b63917542ba10ffb8a82b97befd2c238f
Found module libglib-2.0.so.0 with build-id: 137458a0f7846a084270bf5bb03df075a578db6d
Found module libgobject-2.0.so.0 with build-id: 44f60e584780daaeb1880ead5dd00f12ffd423d2
Found module librt.so.1 with build-id: 1030be4690f8aa93b63acd9180b3037d99a974bf
Found module libpthread.so.0 with build-id: e62798b68557abb4bc5548aba2640cd5ab948f36
Found module libdl.so.2 with build-id: 952123c3bdce7c3370553717942b4878d1fad797
Stack trace of thread 420711:
#0  0x000055c7a75ca9f0 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x48959f0)
#1  0x000055c7a8059884 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x5324884)
#2  0x000055c7a805716a n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x532216a)
#3  0x000055c7a6f706b3 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x423b6b3)
#4  0x000055c7a6f4a05b n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x421505b)
#5  0x000055c7a6f74228 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x423f228)
#6  0x000055c7a6f753ee n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x42403ee)
#7  0x000055c7a6f46f4b n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x4211f4b)
#8  0x000055c7a6f5f185 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x422a185)
#9  0x000055c7a6f5f4cb n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x422a4cb)
#10 0x000055c7a6f5e9e3 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x42299e3)
#11 0x000055c7a52234f8 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x24ee4f8)
#12 0x000055c7a522285c n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x24ed85c)
#13 0x000055c7a521e49e n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x24e949e)
#14 0x000055c7a52144ae n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x24df4ae)
#15 0x000055c7a5228795 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x24f3795)
#16 0x000055c7a6c5c32b n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f2732b)
#17 0x000055c7a6da0b2b n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x406bb2b)
#18 0x000055c7a6c5c58b n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f2758b)
#19 0x000055c7a6c16f84 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3ee1f84)
#20 0x000055c7a6beff6e n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3ebaf6e)
#21 0x000055c7a6c2f1f7 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3efa1f7)
#22 0x000055c7a6c4f245 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f1a245)
#23 0x00007f586d03cb43 start_thread (libc.so.6 + 0x94b43)
#24 0x00007f586d0cea00 __clone3 (libc.so.6 + 0x126a00)

Stack trace of thread 420710:
#0  0x00007f586d039197 __futex_abstimed_wait_common64 (libc.so.6 + 0x91197)
#1  0x00007f586d03bf1b __pthread_cond_wait_common (libc.so.6 + 0x93f1b)
#2  0x000055c7a6c4bdbb n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f16dbb)
#3  0x000055c7a6c4c420 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f17420)
#4  0x000055c7a6c28b48 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3ef3b48)
#5  0x000055c7a6c29376 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3ef4376)
#6  0x000055c7a6c2904d n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3ef404d)
#7  0x000055c7a6c4f245 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f1a245)
#8  0x00007f586d03cb43 start_thread (libc.so.6 + 0x94b43)
#9  0x00007f586d0cea00 __clone3 (libc.so.6 + 0x126a00)

Stack trace of thread 420719:
#0  0x00007f586d039197 __futex_abstimed_wait_common64 (libc.so.6 + 0x91197)
#1  0x00007f586d03bac1 __pthread_cond_wait_common (libc.so.6 + 0x93ac1)
#2  0x000055c7a6c4bc93 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f16c93)
#3  0x000055c7aa0fa1f6 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x73c51f6)
#4  0x000055c7a6c4f245 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f1a245)
#5  0x00007f586d03cb43 start_thread (libc.so.6 + 0x94b43)
#6  0x00007f586d0cea00 __clone3 (libc.so.6 + 0x126a00)

Stack trace of thread 420709:
#0  0x00007f586d0cdfde epoll_wait (libc.so.6 + 0x125fde)
#1  0x000055c7a6da332a n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x406e32a)
#2  0x000055c7a6da09da n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x406b9da)
#3  0x000055c7a6c5c64b n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f2764b)
#4  0x000055c7a6c16f84 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3ee1f84)
#5  0x000055c7a6beff6e n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3ebaf6e)
#6  0x000055c7a6c219bd n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3eec9bd)
#7  0x000055c7a6c2f1f7 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3efa1f7)
#8  0x000055c7a6c4f245 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f1a245)
#9  0x00007f586d03cb43 start_thread (libc.so.6 + 0x94b43)
#10 0x00007f586d0cea00 __clone3 (libc.so.6 + 0x126a00)

Stack trace of thread 420713:
#0  0x00007f586d039197 __futex_abstimed_wait_common64 (libc.so.6 + 0x91197)
#1  0x00007f586d03bf1b __pthread_cond_wait_common (libc.so.6 + 0x93f1b)
#2  0x000055c7a6c4bdbb n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f16dbb)
#3  0x000055c7a6c4c420 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f17420)
#4  0x000055c7a6c28b48 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3ef3b48)
#5  0x000055c7a6c291aa n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3ef41aa)
#6  0x000055c7a6c2904d n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3ef404d)
#7  0x000055c7a6c4f245 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f1a245)
#8  0x00007f586d03cb43 start_thread (libc.so.6 + 0x94b43)
#9  0x00007f586d0cea00 __clone3 (libc.so.6 + 0x126a00)

Stack trace of thread 420721:
#0  0x00007f586d039197 __futex_abstimed_wait_common64 (libc.so.6 + 0x91197)
#1  0x00007f586d03bac1 __pthread_cond_wait_common (libc.so.6 + 0x93ac1)
#2  0x000055c7a6c4bc93 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f16c93)
#3  0x000055c7aa0fa1f6 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x73c51f6)
#4  0x000055c7a6c4f245 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f1a245)
#5  0x00007f586d03cb43 start_thread (libc.so.6 + 0x94b43)
#6  0x00007f586d0cea00 __clone3 (libc.so.6 + 0x126a00)

Stack trace of thread 420705:
#0  0x00007f586d039197 __futex_abstimed_wait_common64 (libc.so.6 + 0x91197)
#1  0x00007f586d03bac1 __pthread_cond_wait_common (libc.so.6 + 0x93ac1)
#2  0x000055c7a6c4bc93 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f16c93)
#3  0x000055c7a6c4c449 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f17449)
#4  0x000055c7a6c4c20f n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3f1720f)
#5  0x000055c7a5e8f23c n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x315a23c)
#6  0x000055c7a9a6faa3 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x6d3aaa3)
#7  0x000055c7a9a72170 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x6d3d170)
#8  0x000055c7aa11264d n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x73dd64d)
#9  0x000055c7a8957d78 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x5c22d78)
#10 0x000055c7a890bb78 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x5bd6b78)
#11 0x000055c7a890dab5 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x5bd8ab5)
#12 0x000055c7a6c055f6 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3ed05f6)
#13 0x000055c7a6c168bc n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3ee18bc)
#14 0x000055c7a6bd66fa n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3ea16fa)
#15 0x000055c7a6c16f84 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3ee1f84)
#16 0x000055c7a6beff6e n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x3ebaf6e)
#17 0x000055c7aa11f9db n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x73ea9db)
#18 0x000055c7a5f30099 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x31fb099)
#19 0x000055c7a80c9eaf n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x5394eaf)
#20 0x000055c7a522c6f1 n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x24f76f1)
#21 0x000055c7a45d83bd n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x18a33bd)
#22 0x00007f586cfd1d90 __libc_start_call_main (libc.so.6 + 0x29d90)
#23 0x00007f586cfd1e40 __libc_start_main_impl (libc.so.6 + 0x29e40)
#24 0x000055c7a45d80ea n/a (/tmp/.mount_Joplin3cC145/@joplinapp-desktop + 0x18a30ea)

## Environment

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1. 
2. 
3.

**Comment by victor03303** [comment]
How did you install it? By building it from source?

Why don't you try the AppImage?

**Comment by fmk64** [comment]
Thx for advice. I have install fresh appimage & appimage launcher. It works fine with all my synchronized datas.
