### ISSUE TITLE
Synchronise Modal is not responsive

### ISSUE THREAD

**Issue by ABHINAV-JHA-27** [laurent22/joplin#7812]
After I opened Joplin I clicked on Synchronise button on bottom left, the modal appeared had not no options to be removed.
It seems that the modal is not responsive according to window sizes

<img width="1150" alt="Screenshot 2023-02-21 at 12 48 47 AM" src="https://user-images.githubusercontent.com/75615092/220185280-cabed66f-b9cd-4b44-81c4-9d47081cee02.png">

## Environment

Joplin version: Latest
Platform: Mac
OS specifics:  Ventura 13.1

## Steps to reproduce

1.  Open a Joplin Desktop App
2.  Click on Synchronise

## Describe what you expected to happen

I expected to see the close button upon scroll or maybe anywhere according to view area

**Comment by jayeshuk** [comment]
Hi Abhinav,
I've forked and cloned the repo on Linux. 
What is the script to run the desktop app locally?

**Comment by ashwanth511** [comment]
Hi,joplin team i  would like to work on this
