### ISSUE TITLE
Mobile: Spellcheck setting no longer visible

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#7822]
## Environment

Joplin version: 6a9848ebe70358b373288f07796052654b76a48d, 12.10.2
Platform: Android, iOS
OS specifics: iOS 16.3.1

## Steps to reproduce

1. Open settings
2. Ensure the plain text editor is disabled
3. Search for "enable spellcheck" option

## Describe what you expected to happen
The `spellcheckEnabled` setting should be visible.

## Cause
The spellcheck setting is only visible when the `editor.beta` setting is `true` and it is always false (it has been replaced by the `editor.usePlainText` setting).

https://github.com/laurent22/joplin/blob/6a9848ebe70358b373288f07796052654b76a48d/packages/lib/models/Setting.ts#L1042-L1060

**Comment by melsonic** [comment]
I want to work on this

**Comment by personalizedrefrigerator** [comment]
> I want to work on this

Feel free to open a pull request when you have a working fix.
