### ISSUE TITLE
Sync with dropbox on android doesn't work.

### ISSUE THREAD

**Issue by theDude823** [laurent22/joplin#7828]
## Environment

Joplin version: 2.8.1
Platform: Android
OS specifics: Android version: "11 RP1A.200720.011"

## Steps to reproduce

1. Open joplin app. 
2. Sync with dropbox doesn't work whether u wait or press the cancel (then cancellation of cancel doesn't work).

## Describe what you expected to happen
Sync with dropbox is supposed to work. I reinstalled joplin. It still doesn't work.

## Logfile

[syncReport-1677156768510.txt](https://github.com/laurent22/joplin/files/10813671/syncReport-1677156768510.txt)

**Comment by wh201906** [comment]
There are some workarounds.
https://www.reddit.com/r/joplinapp/comments/xvp4rl/android_client_sporadically_hangs_on_sync/

**Comment by theDude823** [comment]
I tried the method mentioned in that link. It didn't work. @wh201906 
I installed android-v2.9.8 and tried that method, it didn't work.
In that link, they say downgrading to v2.5.5 works, but v2.5.5 doesn't install in my mobile.

**Comment by theDude823** [comment]
It fixed itself. I installed android-v2.9.8.
