### ISSUE TITLE
Cannot render Katex content: KaTeX parse error: Expected 'EOF', got '&'

### ISSUE THREAD

**Issue by asasoft** [laurent22/joplin#783]
### Operating system
- Android

### Application
- Mobile

Hello,

One of my notes include a portion of code like this:

if [ "$ADDRFAM" != inet ] && [ "$ADDRFAM" != inet6 ]; then
	exit 0
fi

But the parse error on Android , truncate the note to:

if [ "Cannot render Katex content: KaTeX parse error: Expected 'EOF', got '&' at position 20: …FAM" != inet ] &̲& [ "ADDRFAM" != inet6 ]; then
exit 0
fi

On windows and linux client, the note is ok, the problem is Katex on Android.
Im worried about sync a modified note on android and corrupt the note in all 3 clients. Copy and past shows unexpected results too.

Thanks for Joplin!

**Comment by laurent22** [comment]
The code is incorrectly detected as Katex, so it's better to wrap this kind of text in a code block. There's no risk of corruption even if the note doesn't correctly render - it will still sync without any problem.
