### ISSUE TITLE
Note cannot be exported as HTML if not all attachments in it are downloaded

### ISSUE THREAD

**Issue by wh201906** [laurent22/joplin#7831]
## Environment

Joplin version: 2.9.17
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Install Joplin on PC and phone
2. Configure them with the same sync target
3. Set Attachment download behaviour to "Manual" on PC
4. Attach a file in a note on the phone, then do sync
5. Do sync on the PC
6. Export the note in Step 4
7. The bug occurs

## Describe what you expected to happen

Joplin should notice the user some attachments are not downloaded, so the export process fails.
Plus, Joplin could ask the users whether they want to download all attachments in the note for the export process

## Logfile
![图片](https://user-images.githubusercontent.com/62299611/220967442-4eaa3ba2-92d0-4a09-a1cd-9d55a308d2ea.png)

**Comment by wh201906** [comment]
As I mentioned in this comment
https://github.com/laurent22/joplin/issues/7827#issuecomment-1441559012

This bug is caused by the inconsistency of `resourcePaths` and `linkedResourceIds`. If some attachments are not downloaded, the 
```
const id = linkedResourceIds[i];
const resourceContent = `...${basename(resourcePaths[id])}`;
```
will not get the right result.

**Comment by laurent22** [comment]
It you already know where the issue is in the code, could you create a PR? For now it should simply skip the resources if they haven't been downloaded yet

**Comment by wh201906** [comment]
> For now it should simply skip the resources if they haven't been downloaded yet

It's a simple solution, but I think a prompt showing the user that the resources are not complete is also necessary. However, I don't know how to implement the prompt.
Anyway, I will create a PR for the solution you provided.
