### ISSUE TITLE
Multiple variants of the same spellcheck languages in the title bar should be more specific (or merged)

### ISSUE THREAD

**Issue by tomasz1986** [laurent22/joplin#7834]
## Environment

Joplin version: 2.10.4
Platform: all desktop platforms
OS specifics: all desktop OSs

## Steps to reproduce

1. Enable spell check for `English`, `English (Australia)`, `English (Canada)`, `English (United Kingdom)`, `English (United States)`, etc.
2. All of the selected English variants are displayed in the title bar multiple times as just `en`.
  ![image](https://user-images.githubusercontent.com/5626656/221141324-10e4c78a-9701-4f89-9094-7807cbb9c4fc.png)

## Describe what you expected to happen

The current display format isn't very useful (and also unnecessarily takes horizontal space). I can think of two possibilities to "fix" the problem:

1. Use more specific shorthand variants, e.g. `en-AU`, `en-GB`, `en-US`, etc.
2. Display only one single `en` (and do the same for all other languages that have multiple variants).

**Comment by laurent22** [comment]
Is it something that you need, selecting multiple times the same language?

**Comment by tomasz1986** [comment]
Yeah, personally I do need to use at least both British and American English.

**Comment by HahaBill** [comment]
Hi! I am happy to work on this issue. I will update you on my progress and do the PR provided with images and videos.
