### ISSUE TITLE
Change to Keyboard Shortcut Does Not Work

### ISSUE THREAD

**Issue by danielmeek** [laurent22/joplin#7839]
Version Joplin 2.9.17 (prod, win32)

I changed the keyboard shortcut for search in all notes from F6 to F3 and saved the change.  I go back to the notes.  F3 does not cause a search.  F6 still does cause a search.

I tried other changes to the search in all notes function.  None of them take effect.

**Comment by tangodev** [comment]
Hello,

I'm on:
```
Joplin 2.8.8 (prod, linux)

Client ID: ff2459656f0b4027af8b43ed72a9b56c
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: c2a6a13
```

And I have the same issue. I tried assigning a shortcut for going back:
![image](https://user-images.githubusercontent.com/12778629/222287134-ce95aba5-fa5b-443c-babb-d2bc62748402.png)

but it's not working. I made sure and checked that nothing in the OS is conflicting and intercepting this keybind.

**Comment by tangodev** [comment]
I just realized two things:

1. `CTRL`+`left` conflicts with a very basic keyboard move
2. This issue appears to be tied to the *focus* of your "cursor"

Are you @danielmeek focused on the *note list*, *note header* or the *note body*?

Try doing a `CTRL`+`SHIFT`+`b` to focus on the note body (or just click on the text). Now try to use the shortcut. In my case only being in the note body works.

IMHO the intended behavior should be to "just work" regardless of focus.
