### ISSUE TITLE
New note/todo buttons hidden/shown when search is focussed

### ISSUE THREAD

**Issue by msbentley** [laurent22/joplin#7847]
I'm not sure if this is related to #7780 but in the last few weeks the "New note" and "New to-do" buttons are hidden when the search box gets focus, and shown again when it loses focus.

This is in particular a pain if you:
- run a search (buttons are hidden)
- click through the note list (buttons are shown)
- refine your search
  - here I would normally double click the text and type a new search
  - but now the first click focuses the search box and hides the buttons, and the second click ends somewhere random

https://user-images.githubusercontent.com/1671065/221509665-bdedfbd0-c826-4805-b55b-e6a15732148b.mp4

## Environment

Joplin version: 2.10.8
Platform: MacOS
OS specifics: Ventura 13.2.1

## Describe what you expected to happen

Personally I would simply leave the buttons in place to avoid jarring changes to the UI.

**Comment by msbentley** [comment]
Probably this is covered by ongoing work at https://github.com/laurent22/joplin/issues/7848 ?

**Comment by julien-me** [comment]
@msbentley I think this is fixed in https://github.com/laurent22/joplin/pull/7850.
