### ISSUE TITLE
Collecting feedback on the New to-do and New note redesign 

### ISSUE THREAD

**Issue by julien-me** [laurent22/joplin#7848]
The redesign of the buttons to create new notes and new todos opened some discussions regarding its current implementation and possible improvements.

Below are the comments that were made.

**1) The new design could be more responsive.**
Right now the buttons expand and shrink with the width of the note list but when the list is below a certain width the buttons overflow.
![overflow](https://user-images.githubusercontent.com/32807437/221560973-14855328-dc50-402a-acbb-550dcc1505dd.png)

It was suggested to make the buttons responsive so that the text displayed shortens instead of overflowing. For instance "New" could be removed below a certain width and if the width shrinks further instead of text we could show the icons of the previous design.

**2) Combine the two lines when the note list is wide enough**
Vertical space is precious on small screens and for this reason when the note list is wide enough we could put the search bar and the buttons on one line. It's especially prevalent with a vertical layout.

1/4 => New note
1/4 => New to do
2/4 => Search bar (+filter button)

![two-lines](https://user-images.githubusercontent.com/32807437/221561271-92e215b4-ce7e-4618-98f6-ca35f4b60828.png)

**3) Bug: Do not hide buttons when the focus in on Search**
Buttons don't need to disappear anymore when a user clicks on the search bar. This was originally done so that the search bar could expand.
![buttons-disappear](https://user-images.githubusercontent.com/32807437/221561393-05921400-1c94-46f8-ba4a-315198b7d1d6.png)

**4) Bug: The two lines don't align when the sort buttons are disabled.**

**Comment by laurent22** [comment]
@julien-me, for this please create a separate pull request for each item

**Comment by uiop-on** [comment]
Vertical space is at a premium so suggest keeping the three items (search, sort, new) on one line as far as possible.  I only ever use 'New note' so 'New to-do' could easily be removed for me (or maybe a toggle option in settings).  Then the button text can be a much shorter and simpler "New".

**Comment by tomasz1986** [comment]
The current iteration still has the problem of unusable space when using the note-list-at-the-top layout:

![image](https://user-images.githubusercontent.com/5626656/224564406-66fb0620-f2b1-4ce6-ac11-90b54e9a0e26.png)

The highlighted area is unusable. This can be easily reproduced as long as your note list is long enough. The same issue was already fixed previously, however it has now come back due to the newly implemented responsive layout which moves all four elements to a single line which also changes the height.

**Comment by laurent22** [comment]
Added here: https://github.com/laurent22/joplin/issues/7848#issuecomment-1465266507
