### ISSUE TITLE
unescaped characters when using onedrive as sync target

### ISSUE THREAD

**Issue by tino926** [laurent22/joplin#7851]
## Environment

Joplin version: 2.9.17
Platform: windows
OS specifics: windows 11

## Steps to reproduce

1. using sync wizard
2. set sync target to onedrive (provided by my school)
3. press synchronize
4. Joplin shows error message:
   TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
   ![Capture2](https://user-images.githubusercontent.com/2639399/221734270-8ee7d718-0e6c-4f8f-90fe-34dfd020e044.PNG)

The following is how I made "sync" works normally

1. I found that in my onedrive, a new folder named "應用程式" is created
![Capture](https://user-images.githubusercontent.com/2639399/221734654-5a5a1f9a-f189-4a51-9494-e6d805ec5a31.PNG)
2. I manually rename this folder to "Apps", now the sync function works

## Describe what you expected to happen

sync completed with no error message even not manually rename folder in onedrive.

**Comment by wh201906** [comment]
Could you please post the logfile or console output of the Toggle Development Tools?
https://joplinapp.org/debugging/#desktop-application

**Comment by tino926** [comment]
@wh201906, 
I just migrated the 'sync target' to 'OneDrive' and made the 'sync' work normally. I felt a little stressed during the transfer process because I was worried about losing my notes. I'll do what you say when I can borrow another OneDrive (business) account.

**Comment by wh201906** [comment]
Thanks

**Comment by Vveeb** [comment]
Hi there! @wh201906 
I'm new to Joplin and I've been through the same situation when I trying to sync OneDrive(I'm using OneDrive with my work account)
I upload my log file
[-1677813686582.log](https://github.com/laurent22/joplin/files/10877934/-1677813686582.log)

Could you please check if this is the Joplin issue, or my environment's issue?

- Mybe my company's network policy?
- Mybe I'm behind a company proxy?

**Comment by wh201906** [comment]
@Vveeb Hi. Which version are you using?
<details>
<summary>steps to check the version</summary>

![图片](https://user-images.githubusercontent.com/62299611/222627916-022f95c7-77df-41fa-bc94-34bd91cdfb62.png)  
![图片](https://user-images.githubusercontent.com/62299611/222627993-cbcf9994-e07a-436e-a11b-346ead753172.png)  
![图片](https://user-images.githubusercontent.com/62299611/222627944-6ec32a76-d1ee-4303-bcff-146270670f44.png)  

</details>

**Comment by wh201906** [comment]
@tino926 @Vveeb I'm doubting that this bug only occurs when you are using the work/education account, because I tracked the URL of my personal account and the non-ASCII part is coded as a normal URL. 
However, I don't have such a account so I can't reproduce it.

**Comment by Vveeb** [comment]
> 

Joplin 2.9.17 (prod, win32)

Client ID: c80cf712d9d64b86aa1397ef4b571e6b
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: a84a8e7

**Comment by wh201906** [comment]
@Vveeb Have you ever tried OneDrive personal account? I guess this only happens on the work account.
By the way, I think #7868 will fix this.

**Comment by Vveeb** [comment]
> @Vveeb Have you ever tried OneDrive personal account? I guess this only happens on the work account. By the way, I think #7868 will fix this.

Yeah, good to hear that.
After I switching to my personal account + Proxy enabled in Joplin with a "magic" proxy URL (to avoid my company's😈), the synchronization works well

**Comment by wh201906** [comment]
~~@Vveeb You can check the latest pre-release to see if this bug is fixed, if you want.~~
~~https://github.com/laurent22/joplin/releases/tag/v2.10.9~~
This PR is not included in recent pre-releases, please wait.

**Comment by MinseokKim-KR** [comment]
Hi @wh201906 .
I have trouble same as Vveeb.

I've done everything(changed to my personal account).

I can use compay & personal Onedrive account in Android, but not Window.

My Joplin version is below and attached log file.

Joplin 2.9.17 (prod, win32)

Client ID: 4c78e0097e39453383867a383eb0eb6b
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: a84a8e7

[log.txt](https://github.com/laurent22/joplin/files/11103697/log.txt)


+ Also I tried to remove space "My Local windows account". But it has same issue.

**Comment by wh201906** [comment]
Hi @MinseokKim-KR 
> I've done everything(changed to my personal account).

Well then it shows this bug also happens on personal account sometimes.
As I replied to Vveeb, the only thing we can do is waiting now.

**Comment by wh201906** [comment]
@laurent22 Hi. Would you please include #7868 in the pre-releases? This bug affects more users than I originally thought.

**Comment by laurent22** [comment]
@wh201906, it's now in the pre-release 2.10.13. Could someone confirm that it's now working please?

**Comment by MinseokKim-KR** [comment]
@laurent22 @wh201906 Great!! It work for me. Thank you so much.

------- version 
Joplin 2.10.13 (prod, win32)

Client ID: 4c78e0097e39453383867a383eb0eb6b
Sync Version: 3
Profile Version: 42
Keychain Supported: Yes

Revision: 9645414


---------log file
[log.txt](https://github.com/laurent22/joplin/files/11142567/log.txt)

**Comment by wh201906** [comment]
@laurent22 As an extra test, I just tested [v2.10.13](https://github.com/laurent22/joplin/releases/tag/v2.10.13) with a previously working OneDrive account, whose URL is correctly encoded on the server side. It works as before so I think there is no regression.

**Comment by laurent22** [comment]
Great, thanks for confirming it's working, and thanks for fixing this @wh201906!
