### ISSUE TITLE
Sync failure -> info.json limit?

### ISSUE THREAD

**Issue by swdrumm** [laurent22/joplin#7866]
I have Joplin configured to sync from my primary machine to a RPi 4 running ownCloud and nginx.  After years of reliable operation, sync stopped working sometime on February 27th with the following error message:

`Last error:  FetchError: response timeout at https://192.168.1.4/owncloud/remote.php/webdav/Joplin-SYNC/info.json over limit: 120000`

I get this error with both Nextcloud sync (used for years) and Webdav sync options.  Clearly it's a timeout issue, but not sure what info.json does.  Any ideas?  All iOS clients also fail to sync so it's gotta be on the server side...

## Environment

Joplin version: 2.9.17
Platform: linux
OS specifics: Linux mint (client); Raspberry Pi buster (server); ownCloud 10.10.0; nginx 1.14.2

## Steps to reproduce

1.  Start Joplin
2.  Set sync option to either Nextcloud or WebDav
3.  Press sync button

## Describe what you expected to happen

Should sync!

## Logfile
Not sure how to generate this

**Comment by leocoelho-jor** [comment]
Not sure why, but I´ve been unable to sync in an apparent similar matter. I also use webdav. The error that appears seems to be related to JSON files as well

Last error: Error: DELETE locks/2_1_f939c3ddb2dc46a38ef90ffa32d4aa59.json: Unknown error 2 (400): �ad

I´ve checked the login cred and info and all is good to go. Since my server at Bluehost went down a few days ago it did not come back to normal since. Pain in the ass

**Comment by swdrumm** [comment]
I looked at info.json in my Joplin sync folder and it's....empty.  But the date the file was last modified was 27 February, the same date when sync stopped working.  Hhhmmm....

**Comment by swdrumm** [comment]
OK, on the theory that "if it's broke, it can't get any more broke" I intrepidly deleted info.json from the sync folder on the target device (RPi4 as above).  I attempted a complete "upload of local data to sync target" refresh via WebDav under the Advanced Settings page, which resulted in the following:

**Error**
`The sync target could not be upgraded due to an error. For support, please copy the complete content of this page and paste it in the forum: https://discourse.joplinapp.org/`

`The full error was:`

`Could not upgrade from version 1 to version 2: PUT info.json: "Joplin-SYNC/info.json" is locked (Exception OCA\DAV\Connector\Sabre\Exception\FileLocked) (423): <?xml version="1.0" encoding="utf-8"?> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"> <s:exception>OCA\DAV\Connector\Sabre\Exception\FileLocked</s:exception> <s:message>"Joplin-SYNC/info.json" is locked</s:message> </d:error>`

`Error: Could not upgrade from version 1 to version 2: PUT info.json: "Joplin-SYNC/info.json" is locked (Exception OCA\DAV\Connector\Sabre\Exception\FileLocked) (423): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\FileLocked</s:exception>
  <s:message>"Joplin-SYNC/info.json" is locked</s:message>
</d:error>`

`at newError (/tmp/.mount_Joplin5OWcau/resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:414:11)
    at WebDavApi.exec (/tmp/.mount_Joplin5OWcau/resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:441:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FileApiDriverWebDav.put (/tmp/.mount_Joplin5OWcau/resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:201:10)`

**Comment by swdrumm** [comment]
FIXED!  In the spirit of brute-force solutions, I created a new sync folder on ownCloud and pointed all of the clients to it.
