### ISSUE TITLE
Joplin-android can't restore note and notebooks

### ISSUE THREAD

**Issue by tateisu** [laurent22/joplin#7870]
## Environment
- Joplin-android 2.10.8
- confirmed on 2 devices: ASUS Zenfone 9(Android 13), Samsung Galaxy S20 Ultra(Android 12)
- Synchronize target: Dropbox. usage/quota is 10MB/8GB.

## Steps to reproduce
1. install Joplin-android 2.10.8 , then open it.
2. open side menu, tap Synchronize, choose Synchronize target to Dropbox, save, back
3. open side menu, tap Synchronize, do authorization,
4. open side menu, tap Synchronize, run synchronization.

- On my Windows PC, my data has 268 notes, 33 folders, 468 total. (from sync status on Joplin for Desktop 2.9.17 (prod, win32))
- On the Joplin-android after sync, the data has 80 notes, 8 folders, 243 total. (from sync status shown in Joplin-android)

![image](https://user-images.githubusercontent.com/333944/222873659-fda20927-804a-4676-a479-46a4139339f5.png)
![image](https://user-images.githubusercontent.com/333944/222873720-74029af8-6750-46b2-9860-c68b80d592d8.png)

## Describe what you expected to happen
- notes and folders should be synchronized to same count on Joplin Desktop.

## Logfile
[syncReport-1677899183774.txt](https://github.com/laurent22/joplin/files/10887354/syncReport-1677899183774.txt)

**Comment by tateisu** [comment]
also I tried joplin-v2.9.8.apk on GitHub release page, but result is same.

**Comment by personalizedrefrigerator** [comment]
Is the time correct on both devices? (An incorrect device time is known to break sync).

**Comment by tateisu** [comment]
android devices use time from DHCPd and NTP.
PC device use time from NTP.

also unsynchronized folders was created before 1years or older.

**Comment by tateisu** [comment]
I has been solve the problem by using "Re-upload local data to sync target".

### step 1: PC side:
- (optional: create a backup using "File/Export all" in the PC's Joplin app.)
- Exit the Joplin app on PC.
- Open Web browser, open DropBox site and Login, then delete the "Apps/Joplin" folder.
- Open the Joplin application on the PC.
- Open "Tools/Options/Synchronization", tap "Open Sync Wizard", then re-authenticate the sync target.
- Perform the first synchronization, but it's shows very fewer items.
- Open "Tools/Options/Synchronization", tap "Show Advanced Settings", tap "Re-upload local data to sync target".
- the app force closed. (why???)
- Open the Joplin app on the PC.
- wait a long synchronization.
- Open "Help/Sync status".

### step 2: Android side:
- open app.
- wait a long synchronization.
