### ISSUE TITLE
Fingerprint authentication

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#7872]
## Environment

Joplin version: 21.10.8
Platform: Android
OS specifics: LineageOS 19.1

## Steps to reproduce

1. Enable fingerprint authentication on device
2. Enable fingerprint on joplin
3. Terminate joplin, re-open & authenticate 
4. Lock your device 
5. Unlock your device 
6. Open joplin 

## Describe what you expected to happen

Joplin should only ask the user to authenticate once per session and the authentication should be invalidated once they close the app. 

This feature seems pointless if I can access my notes without needing to authenticate when unlocking my device for the second time. Pressing my finger on the screen once is less inconvenient than terminating the app. 

Please request if debug logs are necessary.

**Comment by sif** [comment]
Not sure if bug, as I think that depends on what the OS considers a session. 

If you try the following:
1. terminate Joplin
2. lock device
3. unlock device
4. re-open Joplin

Does it ask you to authenticate? It should, right?

Locking the device doesn't mean the app (or any app) is closed.
