### ISSUE TITLE
Joplin freezes after startup

### ISSUE THREAD

**Issue by hhermerschmidt** [laurent22/joplin#7875]
## Environment

Joplin version: 2.9.17, 2.10.8
Platform: Mac
OS specifics: MacOs 13.2.1

## Steps to reproduce

1. Open Joplin
2. Wait a few seconds
3. GUI freezes

## Describe what you expected to happen
I encounter the same behaviour as mentioned in #7517. I have installed the extension maxOS theme (v1.3.11). After disabling it as described in #7517, the gui continues to response without problems.

So, the problem from #7517 does still exist. Is it possible to fix the pulgin behaviour?

Best regards
Henning

**Comment by laurent22** [comment]
Could see if there's any messages (in particular messages that keep repeating) in the console? joplinapp.org/debugging

**Comment by hhermerschmidt** [comment]
Unfortuantely, not anymore. Furthermore, I tried to recreate the issue and re-activated the mac os theme plugin. But now the problem does not occur anymore. I'm sorry for that. In case it reappears, I will directly take the log output.

But the buttons "new note" and "new to-do" have definitely changed. Before deactivating the plugin the first time, the buttons were placed very next to the search field and the toggle sort-order button and had the same look as the toogle button. Now, after re-activating they are above the search field and have a rectangular shape.

**Comment by hhermerschmidt** [comment]
Now, it happend again. The GUI froozes randomly after it had been ok for a couple of days. I deactivated the macOS theme plugin and now it is working again.

As you asked, I've attached the log output. There, I cannot find a hint regarding the macOS theme plugin, but an error regarding the draw io plugin.

I have installed the following plugins:
* Admonition markdown extension (v1.1.0)
* Automatic Backlinks to note (v3.0.3)
* BibTex (v0.5.0)
* CodeMirror Line Numbers (v2.0.0)
* Draw.io (v2.1.0)
* Favorites (v1.3.0)
* Folding in Code Mirror Editor (v2.0.1)
* Link Graph UI (v1.5.0)
* Menu items, Shortcuts, Toolbar icons (v1.1.0)
* Note Tabs (v1.4.0)
* Outline (v1.5.7)
* Quick Links (v1.2.4)
* Table Formatter Plugin (v1.2.1)
* macOS theme (v1.3.11, now disabled)

---

## Logfile

/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:29840 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtoolsYou might need to use a local HTTP server (instead of file://): https://reactjs.org/link/react-devtools-faq
main-html.js:60 Environment: prod
main-html.js:82 appId: net.cozic.joplin-desktop
main-html.js:84 appType: desktop
Logger.ts:237 12:32:45: App: Profile directory: /Users/henning/.config/joplin-desktop
Logger.ts:237 12:32:45: App: Root profile directory: /Users/henning/.config/joplin-desktop
Logger.ts:237 12:32:45: Database was open successfully
Logger.ts:237 12:32:45: Checking for database schema update...
Logger.ts:237 12:32:45: Current database version Object
Logger.ts:237 12:32:45: Upgrading database from version 42
Logger.ts:237 12:32:45: New version: 42. Previously recorded version: 42
Logger.ts:237 12:32:45: KeychainService: checking if keychain supported
Logger.ts:237 12:32:45: KeychainService: check was already done - skipping. Supported: 1
Logger.ts:237 12:32:45: e2ee/utils: Master password is not set - trying to get it from the active master key...
Logger.ts:237 12:32:45: handleSyncStartupOperation: Processing operation: 0
Logger.ts:237 12:32:45: App: Client ID: 4f8c7ff720bd471298d309cfea9c54c8
Logger.ts:237 12:32:45: models/Setting: Applying default migrations...
Logger.ts:237 12:32:45: e2ee/utils: Trying to load 0 master keys...
Logger.ts:237 12:32:45: e2ee/utils: Loaded master keys: 0
Logger.ts:237 12:32:45: ResourceFetcher: Auto-add resources: Mode: always
Logger.ts:237 12:32:45: ResourceFetcher: Auto-added resources: 0
Logger.ts:237 12:32:45: App: "syncInfoCache" was changed - setting up encryption related code
Logger.ts:237 12:32:45: e2ee/utils: Trying to load 0 master keys...
Logger.ts:237 12:32:45: e2ee/utils: Loaded master keys: 0
Logger.ts:237 12:32:45: App: "syncInfoCache" was changed - setting up encryption related code
Logger.ts:237 12:32:45: e2ee/utils: Trying to load 0 master keys...
Logger.ts:237 12:32:45: e2ee/utils: Loaded master keys: 0
Logger.ts:237 12:32:45: App: "syncInfoCache" was changed - setting up encryption related code
Logger.ts:237 12:32:45: e2ee/utils: Trying to load 0 master keys...
Logger.ts:237 12:32:45: e2ee/utils: Loaded master keys: 0
Logger.ts:237 12:32:45: app.start: doing regular boot
Logger.ts:237 12:32:45: App: "syncInfoCache" was changed - setting up encryption related code
Logger.ts:237 12:32:45: e2ee/utils: Trying to load 0 master keys...
Logger.ts:237 12:32:45: e2ee/utils: Loaded master keys: 0
Logger.ts:237 12:32:45: App: "syncInfoCache" was changed - setting up encryption related code
Logger.ts:237 12:32:45: e2ee/utils: Trying to load 0 master keys...
Logger.ts:237 12:32:45: e2ee/utils: Loaded master keys: 0
Logger.ts:237 12:32:45: App: "syncInfoCache" was changed - setting up encryption related code
Logger.ts:237 12:32:45: e2ee/utils: Trying to load 0 master keys...
Logger.ts:237 12:32:45: e2ee/utils: Loaded master keys: 0
Logger.ts:237 12:32:45: RevisionService: runInBackground: Starting background service with revision collection interval 600000
Logger.ts:237 12:32:45: defaultPluginsUtils: Could not find default plugins' directory: /Applications/Joplin.app/Contents/Resources/build/defaultPlugins - skipping installation.
Logger.ts:237 12:32:45: Starting Clipper server on port 41184
Logger.ts:237 12:32:45: PluginService: Loading plugin from /Users/henning/.config/joplin-desktop/cache/com.andrejilderda.macOSTheme
Logger.ts:237 12:32:45: PluginService: Not running disabled plugin: "com.andrejilderda.macOSTheme"
Logger.ts:237 12:32:45: PluginService: Loading plugin from /Users/henning/.config/joplin-desktop/cache/com.github.marc0l92.joplin-plugin-drawio
Logger.ts:237 12:32:45: PluginService: Loading plugin from /Users/henning/.config/joplin-desktop/cache/com.shantanugoel.JoplinCMLineNumbersPlugin
Logger.ts:237 12:32:45: PluginService: Loading plugin from /Users/henning/.config/joplin-desktop/cache/com.whatever.quick-links
Logger.ts:237 12:32:45: PluginService: Loading plugin from /Users/henning/.config/joplin-desktop/cache/com.xUser5000.bibtex
Logger.ts:237 12:32:45: PluginService: Loading plugin from /Users/henning/.config/joplin-desktop/cache/cx.evermeet.tessus.menu-shortcut-toolbar
Logger.ts:237 12:32:45: PluginService: Loading plugin from /Users/henning/.config/joplin-desktop/cache/io.treymo.LinkGraph
Logger.ts:237 12:32:45: PluginService: Loading plugin from /Users/henning/.config/joplin-desktop/cache/joplin.plugin.ambrt.backlinksToNote
Logger.ts:237 12:32:45: PluginService: Loading plugin from /Users/henning/.config/joplin-desktop/cache/joplin.plugin.ambrt.fold-cm
Logger.ts:237 12:32:45: PluginService: Not running disabled plugin: "joplin.plugin.ambrt.fold-cm"
Logger.ts:237 12:32:45: PluginService: Loading plugin from /Users/henning/.config/joplin-desktop/cache/joplin.plugin.benji.favorites
Logger.ts:237 12:32:45: PluginService: Loading plugin from /Users/henning/.config/joplin-desktop/cache/joplin.plugin.note.tabs
Logger.ts:237 12:32:45: PluginService: Loading plugin from /Users/henning/.config/joplin-desktop/cache/net.rmusin.joplin-table-formatter
Logger.ts:237 12:32:45: PluginService: Not running disabled plugin: "net.rmusin.joplin-table-formatter"
Logger.ts:237 12:32:45: PluginService: Loading plugin from /Users/henning/.config/joplin-desktop/cache/org.joplinapp.plugins.admonition
Logger.ts:237 12:32:45: PluginService: Loading plugin from /Users/henning/.config/joplin-desktop/cache/outline
Logger.ts:237 12:32:46: SpellCheckerServiceDriverNative: Set effective languages to "en-GB"
Logger.ts:237 12:32:47: DecryptionWorker: cannot start because no master key is currently loaded.
Logger.ts:237 12:32:47: Preparing scheduled sync
Logger.ts:237 12:32:47: Starting scheduled sync
Logger.ts:237 12:32:47: Synchronizer: Sync: starting: Starting synchronisation to target 5... supportsAccurateTimestamp = false; supportsMultiPut = false [1678361567308]
Logger.ts:237 12:32:47: Synchronizer: Indexing resources...
Logger.ts:237 12:32:47: ResourceService::indexNoteResources: Start
Logger.ts:237 12:32:47: joplin.plugins: Starting plugin: com.shantanugoel.JoplinCMLineNumbersPlugin
Logger.ts:237 12:32:47: joplin.plugins: Starting plugin: com.whatever.quick-links
Logger.ts:237 12:32:47: joplin.plugins: Starting plugin: com.github.marc0l92.joplin-plugin-drawio
Logger.ts:237 12:32:47: joplin.plugins: Starting plugin: cx.evermeet.tessus.menu-shortcut-toolbar
Logger.ts:237 12:32:47: joplin.plugins: Starting plugin: io.treymo.LinkGraph
Logger.ts:237 12:32:47: joplin.plugins: Starting plugin: joplin.plugin.ambrt.backlinksToNote
Logger.ts:237 12:32:47: joplin.plugins: Starting plugin: joplin.plugin.note.tabs
Logger.ts:237 12:32:47: joplin.plugins: Starting plugin: joplin.plugin.benji.favorites
Logger.ts:237 12:32:47: joplin.plugins: Starting plugin: org.joplinapp.plugins.admonition
Logger.ts:237 12:32:47: joplin.plugins: Starting plugin: outline
Logger.ts:237 12:32:47: joplin.plugins: Starting plugin: com.xUser5000.bibtex
Logger.ts:237 12:32:47: joplin.plugins: Uncaught exception in plugin "com.github.marc0l92.joplin-plugin-drawio": Error: ENOENT: no such file or directory, stat '/var/folders/k9/ql1y1cbd585353thkj62dpt00000gn/T/joplin-drawio-plugin/'
    at statSync (node:fs:1538:3)
    at e.statSync (node:electron/js2c/asar_bundle:5:4539)
    at __node_internal_ (node:internal/fs/utils:793:8)
    at Object.rmdirSync (node:fs:1156:15)
    at t.clearDiskCache (/Users/henning/.config/joplin-desktop/tmp/plugin_com.github.marc0l92.joplin-plugin-drawio.js:1:4250)
    at /Users/henning/.config/joplin-desktop/tmp/plugin_com.github.marc0l92.joplin-plugin-drawio.js:1:9886
    at Generator.next (<anonymous>)
    at /Users/henning/.config/joplin-desktop/tmp/plugin_com.github.marc0l92.joplin-plugin-drawio.js:1:9465
    at new Promise (<anonymous>)
    at n (/Users/henning/.config/joplin-desktop/tmp/plugin_com.github.marc0l92.joplin-plugin-drawio.js:1:9210)
log @ Logger.ts:237
Logger.ts:237 12:32:47: joplin.plugins: Finished running onStart handler: com.github.marc0l92.joplin-plugin-drawio (Took 181ms)
Logger.ts:237 12:32:47: joplin.plugins: Finished running onStart handler: com.xUser5000.bibtex (Took 178ms)
Logger.ts:237 12:32:47: joplin.plugins: Finished running onStart handler: com.shantanugoel.JoplinCMLineNumbersPlugin (Took 440ms)
Logger.ts:237 12:32:47: joplin.plugins: Finished running onStart handler: org.joplinapp.plugins.admonition (Took 421ms)
useMessageHandler.ts:17 Got ipc-message: noteRenderComplete undefined
Logger.ts:237 12:32:48: joplin.plugins: Finished running onStart handler: com.whatever.quick-links (Took 960ms)
2useHtmlLoader.ts:40 useHtmlLoader: isReady false
useHtmlLoader.ts:20 useHtmlLoader: message Object
useHtmlLoader.ts:40 useHtmlLoader: isReady true
useHtmlLoader.ts:45 useHtmlLoader: setHtml 30019fc57d2a13f4e7b5cc94689a8ca0
Logger.ts:237 12:32:49: RevisionService: maintenance: Starting...
Logger.ts:237 12:32:49: RevisionService: maintenance: Service is enabled
useHtmlLoader.ts:40 useHtmlLoader: isReady true
useHtmlLoader.ts:45 useHtmlLoader: setHtml 907b171f12d3a927b7e5cfc6317b1439
useHtmlLoader.ts:20 useHtmlLoader: message Object
useHtmlLoader.ts:20 useHtmlLoader: message Object
Logger.ts:237 12:32:50: joplin.plugins: Finished running onStart handler: cx.evermeet.tessus.menu-shortcut-toolbar (Took 2689ms)
Logger.ts:237 12:32:50: RevisionService: collectRevisions: Created revisions for 0 notes
Logger.ts:237 12:32:50: checkForUpdates: Starting...
Logger.ts:237 12:32:50: checkForUpdates: Checking with options {"includePreReleases":false}
Logger.ts:237 12:32:50: RevisionService: maintenance: Done in 926ms
Logger.ts:237 12:32:50: Plugin: onContentScriptMessage: No such content script: backlinks
log @ Logger.ts:237
Logger.ts:237 12:32:50: joplin.plugins: Finished running onStart handler: io.treymo.LinkGraph (Took 3245ms)
Logger.ts:237 12:32:50: joplin.plugins: Finished running onStart handler: joplin.plugin.ambrt.backlinksToNote (Took 3318ms)
2useHtmlLoader.ts:40 useHtmlLoader: isReady false
Logger.ts:237 12:32:51: ResourceService::indexNoteResources: Completed
useHtmlLoader.ts:20 useHtmlLoader: message Object
useHtmlLoader.ts:40 useHtmlLoader: isReady false
useHtmlLoader.ts:40 useHtmlLoader: isReady true
useHtmlLoader.ts:45 useHtmlLoader: setHtml 670cf654af087efdccadc25b68146495
useHtmlLoader.ts:20 useHtmlLoader: message Object
useHtmlLoader.ts:40 useHtmlLoader: isReady false
useHtmlLoader.ts:20 useHtmlLoader: message Object
useHtmlLoader.ts:40 useHtmlLoader: isReady true
useHtmlLoader.ts:45 useHtmlLoader: setHtml ee609a5af6197373b78365b16916dea7
useHtmlLoader.ts:20 useHtmlLoader: message Object
Logger.ts:237 12:32:51: checkForUpdates: Current version: 2.10.8
Logger.ts:237 12:32:51: checkForUpdates: Latest version: 2.9.17
Logger.ts:237 12:32:51: checkForUpdates: Is Pre-release: false
Logger.ts:237 12:32:51: checkForUpdates: Done.
useHtmlLoader.ts:40 useHtmlLoader: isReady false
useHtmlLoader.ts:40 useHtmlLoader: isReady true
useHtmlLoader.ts:45 useHtmlLoader: setHtml c0ec2e05cc3b133a71d7723c627fcc2d
Logger.ts:237 12:32:52: joplin.plugins: Finished running onStart handler: joplin.plugin.benji.favorites (Took 4767ms)
Logger.ts:237 12:32:52: Synchronizer: Sync target remote info: SyncInfo
Logger.ts:237 12:32:52: Synchronizer: Sync target is already setup - checking it...
Logger.ts:237 12:32:52: Synchronizer: Sync target local info: SyncInfo
useHtmlLoader.ts:20 useHtmlLoader: message Object
useHtmlLoader.ts:40 useHtmlLoader: isReady false
useHtmlLoader.ts:20 useHtmlLoader: message Object
useHtmlLoader.ts:40 useHtmlLoader: isReady true
useHtmlLoader.ts:45 useHtmlLoader: setHtml 446b9da91eb398a627aecad8220b228a
useHtmlLoader.ts:20 useHtmlLoader: message Object
useHtmlLoader.ts:40 useHtmlLoader: isReady true
useHtmlLoader.ts:45 useHtmlLoader: setHtml 3ec5cbd6df646d45a038d98705588319
useHtmlLoader.ts:20 useHtmlLoader: message Object
Logger.ts:237 12:32:52: joplin.plugins: Finished running onStart handler: outline (Took 5161ms)
useHtmlLoader.ts:40 useHtmlLoader: isReady true
useHtmlLoader.ts:45 useHtmlLoader: setHtml aa6aa2363a7e68ae77592907da9c3ff9
Logger.ts:237 12:32:52: joplin.plugins: Finished running onStart handler: joplin.plugin.note.tabs (Took 5337ms)
useHtmlLoader.ts:20 useHtmlLoader: message Object
/Users/henning/.config/joplin-desktop/cache/joplin.plugin.ambrt.backlinksToNote/notesReferences.js:1 Object
/Users/henning/.config/joplin-desktop/cache/joplin.plugin.ambrt.backlinksToNote/notesReferences.js:1 foot tokens
/Users/henning/.config/joplin-desktop/cache/joplin.plugin.ambrt.backlinksToNote/notesReferences.js:1 Array(325)
index.html:1 sending message
useMessageHandler.ts:17 Got ipc-message: noteRenderComplete undefined
useMessageHandler.ts:17 Got ipc-message: postMessageService.message Object
index.html:1 Got response in Markdown-it content script: 
Logger.ts:237 12:32:55: SearchEngine: Updating FTS table...
Logger.ts:237 12:32:55: SearchEngine: Updated FTS table in 12ms. Inserted: 0. Deleted: 0
DevTools failed to load source map: Could not parse content for file:///Applications/Joplin.app/Contents/Resources/app.asar/gui/note-viewer/pluginAssets/mermaid/mermaid.min.js.map: Unexpected end of JSON input
Logger.ts:237 12:32:57: Synchronizer: BasicDelta: Report: {"timestamp":1678201077000,"older":7129,"newer":0,"equal":1}
Logger.ts:237 12:32:58: Synchronizer: Sync: fetchingTotal: Fetching delta items from sync target
Logger.ts:237 12:32:58: Synchronizer: Sync: finished: Synchronisation finished [1678361567308]
Logger.ts:237 12:32:58: Synchronizer: Operations completed: 
Logger.ts:237 12:32:58: Synchronizer: fetchingTotal: -
Logger.ts:237 12:32:58: Synchronizer: Total folders: 54
Logger.ts:237 12:32:58: Synchronizer: Total notes: 1066
Logger.ts:237 12:32:58: Synchronizer: Total resources: 4972
Logger.ts:237 12:32:58: Sync has finished and note has never been changed - reloading it
Logger.ts:237 12:32:58: Updating all notifications...
Logger.ts:237 12:32:58: Garbage collecting alarms...
Logger.ts:237 12:32:59: DecryptionWorker: cannot start because no master key is currently loaded.
Logger.ts:237 12:33:15: ResourceService::indexNoteResources: Start
Logger.ts:237 12:33:15: ResourceService::indexNoteResources: Completed
Logger.ts:237 12:33:15: ResourceService::deleteOrphanResources:

**Comment by laurent22** [comment]
Could you try for a few days without the plugin to make sure it's definitely due to it? It's surprising since it's just a theme. You might want to report it to the author of the plugin too
