### ISSUE TITLE
Yeoman Extension Generator project not building on Node 17 and above

### ISSUE THREAD

**Issue by maptz** [laurent22/joplin#7877]
I am trying to create a Joplin plugin and have been following the insturctions [here](https://joplinapp.org/api/get_started/plugins/). 

On a new Windows 11 installation, with NODE installed (v 18.13.0), I run the following commands:

```
npm install -g yo generator-joplin
yo joplin
```

The second command fails with the error 
```
PATH\node_modules\loader-runner\lib\LoaderRunner.js:133
                if(isError) throw e

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (PATH\node_modules\webpack\lib\util\createHash.js:135:53)
```

I'm assuming I'm running into a NPM version number issue, but maybe it's something else. 

Any hints on how to proceed?

**Comment by roman-r-m** [comment]
A workaround is to set the following env var `NODE_OPTIONS=--openssl-legacy-provider`
However I believe this is not recommended due to potential security issues.

**Comment by maptz** [comment]
Hi @roman-r-m, 

That didn't work for me (using the equivalent environment variable in Windows).

I found a working solution which did point to a node versioning issue.  

I am using `nvm` to run node version 16 (see [here](https://github.com/coreybutler/nvm-windows/releases).

```
nvm install 16
nvm use 16
```

This worked, and I was able to run `nvm run dist`  in the extension directory with no errors.

**Comment by bradharms** [comment]
@maptz With respect, I don't think this issue has been resolved and the issue should be re-opened. While there are workarounds, the issue remains, as a new user who runs `yo joplin` on the current version of Node 18 will run into the same problem and the cause and workarounds are far from obvious.

For search crawlers I want to also point out that Node will report `code: 'ERR_OSSL_EVP_UNSUPPORTED'`.

**Comment by maptz** [comment]
Hi @bradharms, 

Yes. You are correct. I'll re-opened the issue. 

Do you think I should update the issue title? I never know what the right form is with Github.  Perhaps `Yeoman Extension Generator project not building on Node v18`?

**Comment by bradharms** [comment]
The issue comes from changes in Node 17 which are incompatible with Webpack 4, which is the version of Webpack that the plugin generator uses, so I would put "on Node 17 and above"

I'm trying to figure out if any of the changes in the Joplin dev branch would have addressed the issue since version of the generator that is currently published on Npmjs.org. I assume current versions of Webpack (5+) would have dealt with the Node incompatibility issue, and I can see that the dev branch has a recent version of Webpack for the package.json template, but I haven't looked into it any further.

**Comment by bradharms** [comment]
I was able to build dev at the [current commit](https://github.com/laurent22/joplin/commit/4983327f909de158ebe6ad65ca0d02703df8234e) and run the Joplin desktop app, but if I `npm link` the Yeoman plugin, I get this error when trying to run the generator:

```
PS C:\...\joplin-plugin-test> yo joplin .
Error joplin .

Cannot use 'in' operator to search for 'defaults' in npm
```

I don't know what this is referring to.
