### ISSUE TITLE
Notifications not working in Android 13

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#7891]
https://discourse.joplinapp.org/t/still-no-notification/29563

**Comment by ZeinebGuellouz** [comment]
Hi ,
You could check the notifications' permissions because they are put as blocked by default when installing the app on Android .
You just put "Allow notifications".
Hope I could help .

**Comment by magical-heyrovsky** [comment]
Notifications have not been working correctly for a long time and not just on Android 13: https://github.com/laurent22/joplin/issues/6885

**Comment by laurent22** [comment]
I think that was fixed in a recent release as it's working fine for me
