### ISSUE TITLE
Notebook and Note title not shown in portrait view (Android)

### ISSUE THREAD

**Issue by ajay-gh** [laurent22/joplin#7899]
## Environment

Joplin version: 2.10.8
Platform: Android
OS specifics: Android 8.1

## Steps to reproduce

1. start with any note in Joplin, first look at it in landscape mode
2. open the note by clicking/selecting its title
3. you should see the complete note with the note title on top, and the notebook name on top of that
4. now, turn the phone or switch manually to portrait view
5. you will still see the note, but note title and notebook name or no longer shown
6. instead you'll see some empty space where name and title should be shown

## Describe what you expected to happen
is obvious from the steps above

## Logfile

**Comment by laurent22** [comment]
I cannot replicate, please could you provide a screenshot?

**Comment by ajay-gh** [comment]
Sure!

![note before opening](https://user-images.githubusercontent.com/46941311/224379708-9a5c51d8-0563-4d10-8450-f10bbc8bcb55.png)
![note in landscape view](https://user-images.githubusercontent.com/46941311/224379721-b69c9fc5-cce7-441c-a680-16525e57f646.png)
![note in portrait view](https://user-images.githubusercontent.com/46941311/224379726-2e1dc6a2-4c13-4d9b-93be-5b88e18cfeae.png)
