### ISSUE TITLE
Sample of broken list rendering

### ISSUE THREAD

**Issue by tmoravec** [laurent22/joplin#7900]
List rendering randomly switches from asterisks to bullet points and back in some notes. Reproducible across at least Mac and iOS version. Here's a sample note: https://gist.github.com/tmoravec/ba47a446cf32672e0c1ca51347cc3b8d

Screenshot:

<img width="1182" alt="Screenshot 2023-03-10 at 21 21 22" src="https://user-images.githubusercontent.com/816745/224421608-2162eabf-3008-4c12-8de5-7494b3102fc7.png">

## Environment

Joplin version: Joplin 2.9.17 (prod, darwin)
Platform: MacOS
OS specifics: MacOS Ventura 13.2.1 

## Steps to reproduce

1. Create a note with text from the sample gist above
2. Press command + L to render it. Or, on iOS, just save the note and stop editing to get to the rendered view
3. 

## Describe what you expected to happen

Consistent list rendering.

## Logfile

https://gist.github.com/tmoravec/a2d2d5759d9e4a9c3d6384fb24bbdd51

**Comment by tmoravec** [comment]
Still broken.

**Comment by oleole39** [comment]
For the record, I have just tested the provided sample note with Joplin 2.9.17 (prod, linux) on Ubuntu 22 and I don't have this issue. Likely to be OS specific.
