### ISSUE TITLE
Users Delete after  Update

### ISSUE THREAD

**Issue by Kerbster715** [laurent22/joplin#7901]
I am running Joplin as a docker in Unraid. Each time there is a Joplin docker update installed, the "Joplin User Accounts" are deleted and the admin account has reset to admin@localhost and pw admin. What would cause this to happen?

**Comment by dpoulton-github** [comment]
Possibly by not adding a "Volume" in the **docker-compose.yml** file for the database so that the user data in the db is stored on your system, *outside* the database docker container.
