### ISSUE TITLE
How to fill the gaps between different plug-ins without repackaging?

### ISSUE THREAD

**Issue by SUN-SZY** [laurent22/joplin#7903]
How to fill the gaps between different plug-ins without repackaging?

For example, there is no appropriate attribute between the file and the header content to locate the` div `element
`<div class="" style="position: absolute; user-select: none; width: 10px; height: 100%; top: 0px; cursor: col-resize; right: -5px;"></div>
`
![Uploading image.png…](https://www.hualigs.cn/image/640c2f4e3fccc.jpg)

## Environment

Joplin version: 2.10.8 (prod, win32)
Platform: Windows
OS specifics: window 11

修订：2262cbf
Save Note as MD: 1.0.2
Kity Minder: 1.0.9
Enhancement: 1.1.3
Menu items, Shortcuts, Toolbar icons: 1.1.0
Simple Backup: 1.2.2
Custom CodeMirror .vimrc: 1.0.3
Search & Replace: 2.2.0
MultiMarkdown Table Tools: 1.0.0
Quick HTML tags: 0.2.0
ReMoods Theme: 4.1.4
Templates: 2.3.0
turnToChart: 1.9.3
Victor: 1.0.0
Outline: 1.5.7
Rich Markdown: 0.13.2
Note Link System: 0.8.0

## Steps to reproduce
This problem may only need to supplement the class attribute of some locations
How to modify the color or theme without repackaging? This attribute is not referenced by the appropriate class attribute, so it may not be noticed.

## Describe what you expected to happen
The configuration of patching the gap is introduced without repackaging. The global attribute is obviously not suitable

## Logfile
This issue may not need a log, but only for beautification. If I think it is unnecessary to ignore it, I will close this issue

**Comment by TahaNw** [comment]
If you have different plugins that need to communicate with each other or share information, you can use a technique called "plugin messaging". This allows plugins to send messages to each other and exchange information without having to modify or repackage the plugins themselves.

To implement plugin messaging, you can use a shared messaging channel, such as the window.postMessage() method. This method allows you to send a message from one plugin to another, even if they are hosted on different domains or iframes. Here's an example:
`// In plugin A:
window.addEventListener('message', function(event) {
  if (event.data.type === 'getHeaderContent') {
    var headerContent = getHeaderContent(); // Get the header content from plugin A
    event.source.postMessage({ type: 'headerContent', content: headerContent }, '*'); // Send the header content to plugin B
  }
});

// In plugin B:
window.addEventListener('message', function(event) {
  if (event.data.type === 'headerContent') {
    var headerContent = event.data.content; // Get the header content from plugin A
    var divElement = document.createElement('div'); // Create a new div element
    divElement.className = ''; // Set the class name
    divElement.style.position = 'absolute'; // Set the style properties
    divElement.style.userSelect = 'none';
    divElement.style.width = '10px';
    divElement.style.height = '100%';
    divElement.style.top = '0px';
    divElement.style.cursor = 'col-resize';
    divElement.style.right = '-5px';
    document.body.appendChild(divElement); // Add the div element to the page
  }
});

// In your application:
var pluginA = document.getElementById('pluginA'); // Get a reference to plugin A
var pluginB = document.getElementById('pluginB'); // Get a reference to plugin B

pluginA.contentWindow.postMessage({ type: 'getHeaderContent' }, '*'); // Request the header content from plugin A`

we have two plugins, A and B, that need to communicate with each other. Plugin A has a function called getHeaderContent() that returns the header content, but it doesn't have an appropriate attribute to locate the div element. Plugin B needs to add a div element to the page, but it doesn't have access to the header content.

To fill this gap, we use the window.postMessage() method to send a message from plugin A to plugin B, requesting the header content. Plugin A listens for this message and responds by sending the header content back to plugin B. Plugin B listens for the header content message and adds a new div element to the page based on the header content. Finally, in your application, you can request the header content from plugin A by sending a message using postMessage().

**Comment by SUN-SZY** [comment]
你好，您发的信息我已收到，尽快给你回复。

**Comment by SUN-SZY** [comment]
你好，您发的信息我已收到，尽快给你回复。

**Comment by SUN-SZY** [comment]
你好，您发的信息我已收到，尽快给你回复。

**Comment by SUN-SZY** [comment]
你好，您发的信息我已收到，尽快给你回复。

**Comment by SUN-SZY** [comment]
你好，您发的信息我已收到，尽快给你回复。

**Comment by SUN-SZY** [comment]
你好，您发的信息我已收到，尽快给你回复。

**Comment by SUN-SZY** [comment]
你好，您发的信息我已收到，尽快给你回复。

**Comment by SUN-SZY** [comment]
你好，您发的信息我已收到，尽快给你回复。

**Comment by SUN-SZY** [comment]
你好，您发的信息我已收到，尽快给你回复。

**Comment by SUN-SZY** [comment]
你好，您发的信息我已收到，尽快给你回复。
