### ISSUE TITLE
Text not displayed in the edit mode

### ISSUE THREAD

**Issue by aliakseiz** [laurent22/joplin#7910]
It is not possible to edit the note using markdown editor, the text area in "edit mode" is blank. Though it works still with the plain text editor enabled.
Application theme doesn't affect it, tried different ones.

## Environment

Joplin version: 2.10.8
Platform: Android
OS specifics: v5.1.1

## Steps to reproduce

1. Create a note with some text using the plain text editor
2. Change settings not to use the plain text editor
3. Try to modify the newly created note -> the editor screen becomes white and text is not displayed in there, it is not possible to modify it

[ScreenRecord_2023-03-13-06-52-17.zip](https://github.com/laurent22/joplin/files/10953439/ScreenRecord_2023-03-13-06-52-17.zip)

## Describe what you expected to happen
It should be possible to modify the note text using markdown editor.

## Logfile

[syncReport-1678679931902.txt](https://github.com/laurent22/joplin/files/10953427/syncReport-1678679931902.txt)

**Comment by personalizedrefrigerator** [comment]
This might have to do with the version of Android (listed above as v5.1.1). The following information might be helpful:
- Are there any errors in the log (Joplin > Configuration > Tools > Log > Errors only)?
- The new editor uses a WebView. What is the version of the WebView used on your device ([see the second paragraph of this post](https://developer.chrome.com/docs/multidevice/webview/) for how to determine this version).

**Comment by aliakseiz** [comment]
WebView version was 44.0.2403.117, I updated it to the latest available 95.0.4638.74 and the issue is gone, everything works fine and smooth.

Thank you for the tip!
