### ISSUE TITLE
Copy and paste not working on links in Rich Text editor

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#7913]
- Create new note
- Attach file
- Ctrl+A
- Ctrl+X
- Ctrl+V

=> The text is pasted but not the link

https://user-images.githubusercontent.com/1285584/224717293-f428d4f4-e030-452b-9be3-a61212fbe741.mov

**Comment by personalizedrefrigerator** [comment]
The behavior seems to have changed (version 2.12.11) — now the link is preserved, but the target is broken. For example, `[output.pdf](# ":/96cb273b9961457bab5b3f1f33fdf8b3")` when converted to markdown.

**Comment by laurent22** [comment]
I can replicate both behaviours actually:

- If I copy the link only (without any whitespaces around it), it's pasted as plain text  like in the video
- If I copy the link with something around it, it's pasted with this broken markup

I guess there should be a second issue for that because it's a proper bug, while the first one is mostly about the invisible html tags surrounding the link not being copied

**Comment by laurent22** [comment]
I've created a new issue for the second bug: https://github.com/laurent22/joplin/issues/8706

**Comment by laurent22** [comment]
Seems fixed?
