### ISSUE TITLE
4 second pause before actions allowed in app (Android)

### ISSUE THREAD

**Issue by markprouse** [laurent22/joplin#7921]
Using Joplin Android, almost every time i navigate away from the app and come back to it, if i click edit note, create note, or use the show left side control button, the app freezes for about 4 seconds before it will allow you to continue. I am wondering if an index is missing on the local DB or something. 

I have;
8 Notebooks

In each book I have; (notes)
6 + 17 + 4 + 41 +3 + 102 + 5 + 37 = 215

Whats the maximum number of notes that Joplin app can support?
Or does it just need like a DB index to solve the issue?

**Comment by laurent22** [comment]
version?

**Comment by JackGruber** [comment]
I think this could be the sync task. 
I have the same behaviour with iOS and Android with WebDav as sync target on the app start or when I press the sync button, but the app freez is approx. 16 seconds. 

iOS: 12.10.5
Android: 2.10.8

**Comment by markprouse** [comment]
> version?

Version: 2.7.2, Database: v41

**Comment by markprouse** [comment]
Just to let you know i have version 2.11.32 and db version v42 and i still have this issue.
