### ISSUE TITLE
Joplin Web Clipper: Problem with some pages in HTML capture

### ISSUE THREAD

**Issue by antoniopaolini** [laurent22/joplin#7925]
Hello, 
I found some pages  non correctly captured by web clipper, if I choose "Clip complete page (HTML)" .

For Example: 
### 1. https://devblogs.microsoft.com/oldnewthing/20180529-00/?p=98855

 This works fine with "clip complete page (Markdown)" but not in HTML

### 2. https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/how-to-correctly-check-file-versions-with-powershell/ba-p/257642

In this page the pictures were not captured

***
Joplin version: 2.10.10

**Comment by cirrusnine** [comment]
I'm not sure if this is the same bug or not.  In my case pages, clipped pages _are not being imported at all_.  Web Clipper reports it is "Processing". 

An attempt was made with:
Simplified
Complete(markdown)
Complete HTML
Clip Selection: works for limited amounts of text, but fails when the majority of the content is chosen.

Mac OS 13.1
Brave Browser: [Version 1.49.120 Chromium: 111.0.5563.64 (Official Build) (arm64)](https://brave.com/latest/)
Joplin Desktop:
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes
Revision: a84a8e7 

Example links:

https://aws.amazon.com/blogs/aws/new-for-aws-datasync-move-data-between-aws-and-google-cloud-storage-or-aws-and-microsoft-azure-files/
https://aws.amazon.com/blogs/storage/how-to-move-data-from-azure-files-smb-shares-to-aws-using-aws-datasync/

I don't see anything meaningful in the web clipper logs. In debug Joplin logs I see:

2023-03-15 11:53:40: PluginRunner: "Got message (3): joplin.data.get", "[["resources"],{"page":1,"fields":["id","title","mime","updated_time"]}]"
...
2023-03-15 12:56:40: PluginRunner: "Got message (3): joplin.data.get", "[["resources"],{"page":43,"fields":["id","title","mime","updated_time"]}]"


If I can provide any other data please let me know.
