### ISSUE TITLE
iOS iPad Joplin search broken

### ISSUE THREAD

**Issue by PascalDognaux** [laurent22/joplin#7926]
## Environment

Joplin version:  12.9.2
Platform:  iOS iPad
OS specifics: iOS 16.3.1, Model iPad (10th generation)

## Steps to reproduce

1. Open joplin
2. click on search
3. type in anything you want to search
4. You see briefly the results of the search, but then the screen goes blank. It cannot be recovered: must close Joplin and open again
Have a look at the attached capture

## Logfile
log screenshot attached. No obvious errors

![IMG_0242](https://user-images.githubusercontent.com/106609309/225305773-77461e48-958f-4ed9-8004-d845b0dd6e64.png)

https://user-images.githubusercontent.com/106609309/225305865-9d869010-9e26-4350-9700-84997befff5d.mp4

**Comment by laurent22** [comment]
Is it for all searches or for some words in particular?

**Comment by PascalDognaux** [comment]
All searches. It feels like an issue with the rendering of the results, rather than with the search. The Joplin on my iPhone is working fine

**Comment by personalizedrefrigerator** [comment]
> Joplin version: 12.9.2

Please update to the latest version of Joplin — I think it has a fix for this!

**Comment by PascalDognaux** [comment]
Yes! Thank you. It works now
