### ISSUE TITLE
PDF preview Pane does not show the whole first page.

### ISSUE THREAD

**Issue by deadlock-dev** [laurent22/joplin#7932]
## Environment

Joplin version: 2.9.17
Platform: Linux, Windows, Mac
OS specifics: 

## Steps to reproduce

1. Create a note that contains a PDF file.
2. Switch the editor mode to Preview.
3. Enlarge the preview area as much as possible.

## Describe what you expected to happen
If possible, the complete first page of the PDF file should be displayed.

However, the PDF preview pane remains small, even if there is enough space to display the full page.

The screenshot shows an example of the problem:

![grafik](https://user-images.githubusercontent.com/85509918/225550906-b29d222f-76a0-49e3-8803-da51f2c06aa4.png)

In the forum there is already a [thread](https://discourse.joplinapp.org/t/how-to-resize-the-pdf-preview-pane/29767) on this topic.

**Comment by CaptWeiss** [comment]
Looking into this

**Comment by TahaNw** [comment]
If the CSS styles aren't working, you can try setting the size of the preview area using JavaScript.
here's an example of how you can use JavaScript to set the size of the PDF preview area based on the size of its container element:
`<div id="pdf-container" style="width: 100%; height: 500px;">
  <div id="pdf-preview"></div>
</div>
`
`const container = document.getElementById("pdf-container");
const preview = document.getElementById("pdf-preview");

// Load the PDF file into the preview area
// (code to load the PDF file goes here)

// Resize the preview area based on the size of the container
function resizePreview() {
  const containerWidth = container.clientWidth;
  const containerHeight = container.clientHeight;
  const previewWidth = containerWidth;
  const previewHeight = containerHeight;

  preview.style.width = `${previewWidth}px`;
  preview.style.height = `${previewHeight}px`;
}

// Call the resizePreview function when the page is loaded
window.addEventListener("load", resizePreview);

// Call the resizePreview function when the window is resized
window.addEventListener("resize", resizePreview);
`

In this JavaScript code, we first get references to the container element (pdf-container) and the preview area (pdf-preview). We then define a resizePreview function that calculates the size of the container element and sets the width and height of the preview area accordingly.

Finally, we add two event listeners to the window object. The first listener calls the resizePreview function when the page is loaded, and the second listener calls the function when the window is resized.

**Comment by cgarde39** [comment]
I wish to try working on a fix, although it is my first time ever tackling on an issue, therefore if anybody could point me to which file the displaying of the previewing mode is getting taken care of I would greatly appreciate it.

**Comment by deftdawg** [comment]
This is still an issue as of
Joplin 2.10.4 (prod, linux)

Client ID: 30b59b5bcb54405986d2c653aebe0404
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: 9866e59

**Comment by dankerthrone** [comment]
Hey, I just want to confirm that this is still a problem. 

I went with the userstyle.css solution proposed [here](https://discourse.joplinapp.org/t/how-to-resize-the-pdf-preview-pane/29767/24), but I think it really should be fixed properly. 

Joplin 3.4.12 (prod, linux)

Device: linux, 13th Gen Intel(R) Core(TM) i5-1334U
Client ID: dfcc79cc91304af7bdb82070f7f63a37
Sync Version: 3
Profile Version: 48
Keychain Supported: No
Alternative instance ID: -

Revision: e9a9f68

Backup: 1.4.3
Freehand Drawing: 3.1.0
Jarvis: 0.10.5
macOS theme: 1.5.20
Note Link System: 0.8.0
