### ISSUE TITLE
Masterkey in synchronize status is “0/1”

### ISSUE THREAD

**Issue by inphj** [laurent22/joplin#7940]
## Environment

Joplin version:  2.9.17
Platform:  windows, android
OS specifics:  windows 10 // one drive sync

## Steps to reproduce

The master key does not change from 0/1 to 1/1.
I'm actually using encryption through masterkey, and I can see the note well.
I just want to change masterkey 0/1 to 1/1.

Below is a list of synchronizations.
Note: 764/764
Folder: 51/51
Resource: 2219/2219
Tag: 125/125
NoteTag: 817/817
MasterKey: 0/1
Revision: 23/23
Total: 3999/4000

## Describe what you expected to happen

![image](https://user-images.githubusercontent.com/128053455/225852318-d01091cd-15a2-4f58-b502-18a533e67700.png)

**Comment by dpoulton-github** [comment]
I cannot recall ever seeing this entry shown as other than **0/1**. I always assumed that the MasterKey had some special status. As **desktop** and **high** labels have been added this appears to actually be a bug.

Therefore I thought I would mention that as well as seeing this on all my desktop v2.9.17 clients (Linux & Win11), I also get exactly the same on android-v.2.10.8. These clients are all linked to the same account on Joplin Server-v.2.10.9.

**Comment by inphj** [comment]
I tested it.

1. Install Joplin on Android Smartphones
2. Set the data to be stored in local storage on the smartphone
3. Make an empty note.
4. Enable encryption
5. Masterkey is 0/1 equally, but data is actually stored and encrypted.

Here we can see.
The master key is fixed at 0/1.
I just wanted to synchronize everything.
However, architecturally, masterkey 0/1 would be unavoidable.

Description of the design architecture of @laurent22 is required.

**Comment by laurent22** [comment]
It's not a bug, just a display issue. Master keys are not longer synced like regular items so that line should simply be removed from there

**Comment by inphj** [comment]
OK.

It is not a critical issue.
I hope it will be handled when you have time.

**Comment by CaptWeiss** [comment]
Is anyone working on this yet

I would like to work on it.
