### ISSUE TITLE
Android: Freezing on start

### ISSUE THREAD

**Issue by glocalglocal** [laurent22/joplin#7941]
## Environment

Joplin version: 2.10.8 in Aurora and F-Droid
Platform: Android
OS specifics: 7

## Steps to reproduce

1. I start Joplin 
2. I see a white screen and the app freezes. I see on Google app store someone reported seeing a black screen, so this may be theme dependant. 

## Describe what you expected to happen

It worked OK for a long time. I think the latest update caused the freezes. 

Both Aurora and F-droid report the version as 2.10.8 but under Versions F-droid lists 2.9.8 as the only available and suggested version.

**Comment by laurent22** [comment]
We only support the Google Play Store version and the APK downloaded from here

**Comment by glocalglocal** [comment]
I reinstalled from Aurora and it is working. It is one of the few remaining apps I have from Google Play, which is unfortunate, but it is working. Hopefully, I will be able to add it back to my F-droid apps one day. Thank you.

**Comment by laurent22** [comment]
You might want to report this to the F-Droid project as they may be interested in fixing this
