### ISSUE TITLE
Sorting overlay window does not respect user theme

### ISSUE THREAD

**Issue by jcperil** [laurent22/joplin#7946]
## Environment

Joplin version: 2.10.8
Platform: Android
OS specifics: Android 12

## Steps to reproduce

1. Set theme to Nord, let's say.
2. Click the döner menu on top right.
3. The sorting window appears all white in an otherwise Nordic theme.

<img src="https://user-images.githubusercontent.com/89805719/226156535-109117c0-8894-4f5e-b8d9-f8b356dfaa81.jpg" height="300px"/>

## Describe what you expected to happen

Apply user theme to sorting window as well.

**Comment by jcperil** [comment]
Please leave it open.

**Comment by gitstart** [comment]
This issue has been addressed in #8024

**Comment by jcperil** [comment]
Please leave it open.

**Comment by jcperil** [comment]
Please leave it open.

**Comment by jcperil** [comment]
Please leave it open.
