### ISSUE TITLE
Abnormal interface display

### ISSUE THREAD

**Issue by wangyingbo** [laurent22/joplin#7951]
## Environment

Joplin version: 2.9.17 - 2.10.11
Platform: macos Ventura 13.0.1
OS specifics: 

## Steps to reproduce

1. 
2. 
3. 

## Describe what you expected to happen

When you first open the software, it displays normally，
![截屏2023-03-21 10 49 11](https://user-images.githubusercontent.com/12741589/226507969-270aa0b5-6765-4d39-a802-52a5b9d5b12f.png)

After about two seconds, it's like this

![截屏2023-03-21 10 49 17](https://user-images.githubusercontent.com/12741589/226507968-b56bbc03-1556-45db-878f-5f7d0e45c4e7.png)

**Comment by Daeraxa** [comment]
Did you install a plugin theme?

**Comment by wangyingbo** [comment]
> Did you install a plugin theme?

Probably not, here is my theme lis
<img width="1094" alt="截屏2023-03-30 01 45 24" src="https://user-images.githubusercontent.com/12741589/228624197-0f079a3c-1178-4ef4-920b-eddab73b7d28.png">

**Comment by Daeraxa** [comment]
I can literally see it on your screenshot:
![image](https://user-images.githubusercontent.com/58074586/228643997-c7a7a915-a7ee-4c01-80db-f700b87b6d66.png)

**Comment by wangyingbo** [comment]
It works when i close the mac os theme plugin!  Thanks you very mach!

**Comment by wangyingbo** [comment]
> I can literally see it on your screenshot: ![image](https://user-images.githubusercontent.com/58074586/228643997-c7a7a915-a7ee-4c01-80db-f700b87b6d66.png)

It works when i close the mac os theme plugin! Thanks you very mach!
