### ISSUE TITLE
joplin docker mail send failed

### ISSUE THREAD

**Issue by appotry** [laurent22/joplin#7952]
## Environment

Joplin version:  Joplin Server 2.10.10
Platform:  Alma 8.7
OS specifics: 

## Steps to reproduce

mail config env

```
      - MAILER_ENABLED=1
      - MAILER_HOST=smtp.qq.com
      - MAILER_PORT=465
      - MAILER_SECURITY=starttls 
      - MAILER_AUTH_USER=xxxxx@foxmail.com
      - MAILER_AUTH_PASSWORD=xxxxxxx
      - MAILER_NOREPLY_NAME=JoplinServer
      - MAILER_NOREPLY_EMAIL=noreply@xxx.xxx
```

this config also failed
```
      - MAILER_ENABLED=1
      - MAILER_HOST=smtp.qq.com
      - MAILER_PORT=587
      - MAILER_SECURITY=starttls 
      - MAILER_AUTH_USER=xxxxx@foxmail.com
      - MAILER_AUTH_PASSWORD=xxxxxxx
      - MAILER_NOREPLY_NAME=JoplinServer
      - MAILER_NOREPLY_EMAIL=noreply@xxx.xxx
```

## Logfile

Error log on `https://joplin.xxx.com/admin/emails`
```

{"code":"EENVELOPE","message":"Mail command failed: 501 Mail from address must be same as authorization user.","stack":"Error: Mail command failed: 501 Mail from address must be same as authorization user.\n at SMTPConnection._formatError (/home/joplin/packages/server/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)\n at SMTPConnection._actionMAIL (/home/joplin/packages/server/node_modules/nodemailer/lib/smtp-connection/index.js:1578:34)\n at SMTPConnection.<anonymous> (/home/joplin/packages/server/node_modules/nodemailer/lib/smtp-connection/index.js:1047:18)\n at SMTPConnection._processResponse (/home/joplin/packages/server/node_modules/nodemailer/lib/smtp-connection/index.js:953:20)\n at SMTPConnection._onData (/home/joplin/packages/server/node_modules/nodemailer/lib/smtp-connection/index.js:755:14)\n at TLSSocket.SMTPConnection._onSocketData (/home/joplin/packages/server/node_modules/nodemailer/lib/smtp-connection/index.js:193:44)\n at TLSSocket.emit (node:events:513:28)\n at addChunk (node:internal/streams/readable:324:12)\n at readableAddChunk (node:internal/streams/readable:297:9)\n at TLSSocket.Readable.push (node:internal/streams/readable:234:10)"}
```

**Comment by dpoulton-github** [comment]
It looks like the answer is possibly in the question.

> "Mail command failed: 501 Mail from address must be same as authorization user."

```
      - MAILER_AUTH_USER=xxxxx@foxmail.com
      - MAILER_NOREPLY_EMAIL=noreply@xxx.xxx
```

**Comment by appotry** [comment]
you are right 

It worked fine after modifying the configuration below.

```
      - MAILER_AUTH_USER=xxxxx@foxmail.com
      - MAILER_NOREPLY_EMAIL=xxxxx@foxmail.com  # Same as the above parameter
``` 

@laurent22  It's better to add an environment variable named MAILER_FROM

so, MAILER_NOREPLY_EMAIL can be a value diffent from MAILER_AUTH_USER

**Comment by appotry** [comment]
@laurent22  It's recommended to add comments in the configuration file that MAILER_AUTH_USER and MAILER_NOREPLY_EMAIL parameters need to have the same value, otherwise emails won't work properly. Alternatively, an environment variable named mail_from can be added as a parameter.

this issues can be closed

**Comment by dpoulton-github** [comment]
`MAILER_NOREPLY_EMAIL` ***can*** be a different value to `MAILER_AUTH_USER`, just not with the SMTP server you are using.

What you saw was not a Joplin Server error. This error comes from Tencents SMTP server at `qq.com`.

When Joplin has tried to log on to the SMTP server with one address (`xxxxx@foxmail.com`) but use a different address as the "From" address (`noreply@xxx.xxx`) it has been sent the error message as a response because this particular SMTP server does not allow it.

I guess that Tencent has placed this restriction on their SMTP server to prevent someone creating a free account and then using the SMTP server to send out spam pretending to be from different email addresses.

**Comment by dpoulton-github** [comment]
> this issues can be closed

As you opened the issue you should also be able to close it.

**Comment by appotry** [comment]
@laurent22 Many other software have two parameters, MAILER_NOREPLY_EMAIL and MAILER_FROM, for SMTP configuration. Should Joplin also have these two parameters?
