### ISSUE TITLE
Android: Continue writing on the line where you left the note

### ISSUE THREAD

**Issue by Tommy-01** [laurent22/joplin#7954]
## Environment

Joplin version: 2.10.8
Platform: Android 

## Steps to reproduce

1. Write a text in a Note longer than the screen height
2. Close, Save the Note
3. Open the Note again to resume the writing
4. The Cursor is set in the first Line of the Note, i have to scroll down to the last Line to continue writing.

## Describe what you expected to happen
I was expecting, that the cursor is set to the position, where it was, when the note was left.
It seems that this behavior came with the last version. Previously it had behaved as expected.

**Comment by TahaNw** [comment]
One solution to this issue is to save the position of the cursor in the Note when it's closed, and then restore the cursor's position when the Note is opened again.
To implement this solution, you'll need to save the cursor's position along with the Note text when the user closes the Note. You can use the getSelectionStart() method of the EditText view to get the position of the cursor within the text. You can then save this position along with the Note text to your app's storage, such as a local file or a database.

When the user reopens the Note, you can retrieve the saved position and set the cursor's position to that position using the setSelection() method of the EditText view. This will automatically scroll the Note to the appropriate position, so the user can continue writing where they left off.

`public class NoteActivity extends AppCompatActivity {
    private EditText editText;
    private int cursorPosition;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_note);

        // Get a reference to the EditText view
        editText = findViewById(R.id.note_text);

        // Check if there is saved state for this activity
        if (savedInstanceState != null) {
            // Restore the cursor position from saved state
            cursorPosition = savedInstanceState.getInt("cursorPosition");
        }
    }

    @Override
    protected void onResume() {
        super.onResume();

        // Retrieve the saved Note text and cursor position from app storage
        String noteText = loadNoteTextFromStorage();
        cursorPosition = loadCursorPositionFromStorage();

        // Set the Note text and cursor position in the EditText view
        editText.setText(noteText);
        editText.setSelection(cursorPosition);
    }

    @Override
    protected void onPause() {
        super.onPause();

        // Save the Note text and cursor position when the Note is closed
        String noteText = editText.getText().toString();
        cursorPosition = editText.getSelectionStart();

        // Save the Note text and cursor position to app storage
        saveNoteTextToStorage(noteText);
        saveCursorPositionToStorage(cursorPosition);
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);

        // Save the cursor position to the activity's saved state
        outState.putInt("cursorPosition", cursorPosition);
    }

    private String loadNoteTextFromStorage() {
        // TODO: Load the Note text from app storage
        return "";
    }

    private void saveNoteTextToStorage(String noteText) {
        // TODO: Save the Note text to app storage
    }

    private int loadCursorPositionFromStorage() {
        // TODO: Load the cursor position from app storage
        return 0;
    }

    private void saveCursorPositionToStorage(int cursorPosition) {
        // TODO: Save the cursor position to app storage
    }
}`

Note that the sample code above includes some placeholders for methods that you'll need to implement to load and save the Note text and cursor position to the app's storage.

**Comment by wh201906** [comment]
@TahaNw The Android app of Joplin is based on React Native, and it seems like your code is for a native Android app.

**Comment by TahaNw** [comment]
@wh201906 my bad, her is a React Native version of the code: 

`import React, { useState, useEffect } from 'react';
import { View, TextInput, StyleSheet } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

const NoteScreen = () => {
  const [noteText, setNoteText] = useState('');
  const [cursorPosition, setCursorPosition] = useState(0);

  useEffect(() => {
    loadNoteTextFromStorage();
    loadCursorPositionFromStorage();
  }, []);

  const loadNoteTextFromStorage = async () => {
    try {
      const noteText = await AsyncStorage.getItem('noteText');
      if (noteText !== null) {
        setNoteText(noteText);
      }
    } catch (error) {
      console.error(error);
    }
  };

  const saveNoteTextToStorage = async (noteText) => {
    try {
      await AsyncStorage.setItem('noteText', noteText);
    } catch (error) {
      console.error(error);
    }
  };

  const loadCursorPositionFromStorage = async () => {
    try {
      const cursorPosition = await AsyncStorage.getItem('cursorPosition');
      if (cursorPosition !== null) {
        setCursorPosition(parseInt(cursorPosition));
      }
    } catch (error) {
      console.error(error);
    }
  };

  const saveCursorPositionToStorage = async (cursorPosition) => {
    try {
      await AsyncStorage.setItem('cursorPosition', cursorPosition.toString());
    } catch (error) {
      console.error(error);
    }
  };

  const handleNoteTextChange = (noteText) => {
    setNoteText(noteText);
    setCursorPosition(Math.min(noteText.length, cursorPosition)); // Prevent cursor from going beyond text length
    saveNoteTextToStorage(noteText);
    saveCursorPositionToStorage(cursorPosition);
  };

  const handleCursorPositionChange = ({ nativeEvent }) => {
    const { selection: { start } } = nativeEvent;
    setCursorPosition(start);
    saveCursorPositionToStorage(start);
  };

  return (
    <View style={styles.container}>
      <TextInput
        style={styles.noteInput}
        value={noteText}
        onChangeText={handleNoteTextChange}
        onSelectionChange={handleCursorPositionChange}
        multiline={true}
        autoFocus={true}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 10,
  },
  noteInput: {
    flex: 1,
    fontSize: 16,
  },
});

export default NoteScreen;
`

**Comment by wh201906** [comment]
@TahaNw If you know how to do it, then you can make a Pull Request for it.
