### ISSUE TITLE
Blank screen on start (Android)

### ISSUE THREAD

**Issue by lambda100** [laurent22/joplin#7956]
Screenshot of app: ![photo_2023-03-22_21-05-21](https://user-images.githubusercontent.com/5515428/226913390-b04c8b2e-4d22-4bdf-a720-2c9472ec2f19.jpg)

It happens after an unpredictable period of usage, could be a few days, or next day. Once I encountered this, the only solution I know of is to reinstall, but seems to be happening more frequently.

## Environment

Joplin version: 2.10.8
Platform: Android
OS specifics: Android 13, Samsung One UI 5.1
Sync: MS OneDrive

## Steps to reproduce

1. Start app
2. Realised you are stuck and you can do nothing

## Describe what you expected to happen

Expects to see the UI.

**Comment by laurent22** [comment]
Are you able to run `adb logcat` to see what happens when the screen goes blank?

Alternatively, could you do this?

- Start the app and write down at what time
- Create a debug report: https://joplinapp.org/debugging/#creating-a-low-level-bug-report-on-android

Then if you could either upload that here that would be great

**Comment by laurent22** [comment]
Would you mind trying this release and let me know if it works?

https://github.com/laurent22/joplin-android/releases/tag/android-v2.10.9

**Comment by lambda100** [comment]
Updated the original msg with: "It happens after an unpredictable period of usage, could be a few days, or next day. Once I encountered this, the only solution I know of is to reinstall, but seems to be happening more frequently."

I'm not sure if you really need the whole 27 MB bug report zip, is there something more specific to provide?

I will try the provided APK, but depending on luck, it can happen the next time I start the app or a few days.

**Comment by laurent22** [comment]
> I'm not sure if you really need the whole 27 MB bug report zip, is there something more specific to provide?

Yes if you can dig through it and find the log lines that happen when the screen goes blank, but that might be tricky

> I will try the provided APK, but depending on luck, it can happen the next time I start the app or a few days.

The only thing I can think that would cause this error is the new fingerprint support, which was doing a native call on startup. I've improved this now, so I'm hoping that it will fix this and related issues

**Comment by lambda100** [comment]
> Yes if you can dig through it and find the log lines that happen when the screen goes blank, but that might be tricky

Turns out the whole .zip is too big to be uploaded. Is just a zip of the dumpstate.txt good enough?
[dumpstate.zip](https://github.com/laurent22/joplin/files/11050785/dumpstate.zip)

> The only thing I can think that would cause this error is the new fingerprint support, which was doing a native call on startup. I've improved this now, so I'm hoping that it will fix this and related issues

I have been using Joplin for 1 to 2 years, have always have biometric enabled. Problem seems to have started a month+ ago.

If the problem happens again, I will try disabling biometric, before trying the 32-bit version.

**Comment by lambda100** [comment]
Day 11: I no longer experience the "blank-screen" problem ever since trying out the new apk.

**Comment by laurent22** [comment]
That's great, thanks for confirming
