### ISSUE TITLE
Android - Unable to create new notes

### ISSUE THREAD

**Issue by tanc** [laurent22/joplin#7960]
On the Android client I can't see any way to add a new note or todo. Also, if I long press on the icon and choose "new note" Joplin opens but not on the new note screen.

Editing an existing note works fine.

## Environment

Joplin version: 2.10.8
Platform: Android
OS specifics: MIUI Global 14.0.8 (Android 12) on Xiaomi 12 Pro

Running Joplin Server in a container. Syncing works fine (all notes appear and updates done on other devices show up fine).

## Steps to reproduce

1. Open the app
2. Icon missing to create new note

## Describe what you expected to happen

I expect to see a new note button somewhere

## Logfile

Will upload a logfile later. I just wanted to see if this was a known issue or something weird with my install.

**Comment by laurent22** [comment]
Are you able to take a video of this? as it's not clear to me what's happening

**Comment by tanc** [comment]
https://user-images.githubusercontent.com/76320/227196127-ef9f0c78-7b3a-4b6e-9b73-27cfca4abf17.mp4

Hopefully this helps. If I remember on iOS there was a floating button over the list to add a new note

**Comment by laurent22** [comment]
Ok that's so strange, why is the button no showing up. What if you switch to a different notebook, it's still not there?

**Comment by tanc** [comment]
I created a new notebook and yes! It does show. So it seems the problem is with my "notes" Notebook, or somehow the notes are not associated with a notebook.

On my desktop I see this after creating the new notebook on my Android mobile:
![image](https://user-images.githubusercontent.com/76320/227202351-e4296cdc-fa34-49f9-839d-1e928fbac24d.png)

Whereas on my Android mobile I see this:
![Screenshot_2023-03-23-13-22-24-529_net cozic joplin](https://user-images.githubusercontent.com/76320/227204184-0dc4caaa-e630-4a5e-98ed-a5ef8a45b9b0.jpg)

But now I can't see all my synced notes as there doesn't seem to be an associated notebook, only the new "Test" notebook I created.

**Comment by tanc** [comment]
On my desktop I tried renaming "notes" notebook to "Notes" and after submitting it deleted all my notes! Any idea how I get them back?

**Comment by laurent22** [comment]
They are probably still under "All notes"? But anyway it seems there's something wrong with your setup so you might want to restore from a backup and try again

**Comment by tanc** [comment]
I'll close the issue as while it isn't resolved I can't now replicate it due to all my notes getting deleted. I've decided to use a different project for my future note taking but I want to thank the developer for taking the time to respond and trying to help
