### ISSUE TITLE
No iOS Notifications for To-Do w/ Alarm by Default

### ISSUE THREAD

**Issue by Swamp2k9** [laurent22/joplin#7968]
When creating a to-do alarm on my PC, the alarm doesn't sound on my iPhone. 

Joplin doesn't appear in System Settings -> Notifications list by default.

## Environment

Joplin version: 12.10.5
Platform: iOS, iPhone 14 Pro Max
OS specifics: iOS Version 16.4

## Steps to reproduce

1. Create a to-do with an alarm on a synchronized device that's not iOS / MacOS  (I did so on my PC)
2. Wait for the alarm to go off. You will be notified on the other device (PC), but not from the iOS device.  

## Describe what you expected to happen

I was expecting a notification to appear on my iOS device.

I found a workaround: If you create a to-do list on the iOS device, you'll get the popup asking for permission to add Joplin to the system notifications list. Once accepted, it works, as normal. 

A solution would be to prompt users upon startup of the Joplin app.

**Comment by laurent22** [comment]
Is it still happening?
