### ISSUE TITLE
[ Feature Request ] vim-style navigation (hjkl) in terminal app

### ISSUE THREAD

**Issue by seagoj** [laurent22/joplin#797]
### Operating System
- Windows
- macOS
- Linux

### Application

- Terminal

I may take a stab at implementing this if I have time, but vim-style navigations in the terminal app would be a great feature to add.

**Comment by laurent22** [comment]
Can't that be done by setting up custom shortcuts? https://joplin.cozic.net/terminal/#shortcuts

**Comment by seagoj** [comment]
It certainly can. Sorry, I hadn't expected that to be configurable. :)

**Comment by seagoj** [comment]
Just for those that find this ticket later: this is what I landed on to make things a little more vim-like:

*~/.config/joplin/keymap.json*:
```json
[
    { "keys": ["h"], "type": "function", "command": "focus_previous" },
    { "keys": ["j"], "type": "function", "command": "move_down" },
    { "keys": ["k"], "type": "function", "command": "move_up" },
    { "keys": ["l"], "type": "function", "command": "focus_next" },
    { "keys": ["/"], "type": "prompt", "command": "search \"\"", "cursorPosition": -2 },
    { "keys": ["q"], "type": "exec", "command": "exit" }
]
```
