### ISSUE TITLE
Joplin has problems when exporting markdown and attachments with spaces

### ISSUE THREAD

**Issue by jesusdeveloper** [laurent22/joplin#7970]
## Environment

Joplin version: Joplin 2.9.17 (prod, darwin)
Platform: Mac OS X
OS specifics: Mac OS X

## Steps to reproduce

1. Choose a Joplin note containing image or files.
2. The image or file must be saved in the resources folder (default) and must have spaces.
3. Export the note in Joplin as markdown or as markdown + front matter.
4. The exported markdown shows attachments or images that have spaces by replacing spaces with "%20".
5. The image or attachment is no longer visible because the path is incorrect.

## Describe what you expected to happen

Perhaps the solution would be a script that:
- Search the resource folder for files or images that have spaces in their name. For example "image a.jpg"
- Replace the space with an underscore for that file. For example: "image-a.jpg
-Search all notes that have that file or image attached to it and replace it with the new name:
Joplin note containing "image a.jpg" replace the string "image a.jpg" with "image-a.jpg".

Is this feasible?

I would need your help for this please.

Thank you.

## Extra information

Good,
this is very important to me.
Imagine you have a note saved in Joplin with text, images and attachments saved by default in the resource folder.
If we export this note as markdown in Joplin or export as markdown + Front matter the export result looks like this:

```
Prueba exportacion

Probando exportación con imagen:

![pez-dorado_526_0_orig.jpg](../_resources/pez-dorado_526_0_orig-1.jpg)

Y archivo adjunto:

[Factura logitech combo ipad pro.pdf](../_resources/Factura%20logitech%20combo%20ipad%20pro-1.pdf)



![Captura de pantalla 2022-02-18 a las 21.17.15.png](../_resources/Captura%20de%20pantalla%202022-02-18%20a%20las%2021.17.15-1.png)
```

That is, Joplin fails when exporting markdown /markdown + front matter because when an image or attachment in the resource folder has spaces, it exchanges the spaces for a %20.
This causes that afterwards, the file image does not find the path.
I see a solution: run some plugin or script for Joplin to convert the spaces in the attachments by an underscore. This way you would have to rename all the notes and attachments to put the _ to the spaces.

The question: how to solve this problem if we have files or images with spaces in the resource folder?

I have seen that this problem was going to be solved but it still fails :(
https://github.com/laurent22/joplin/issues/4847
https://github.com/laurent22/joplin/issues/6721

THANK YOU

**Comment by laurent22** [comment]
URLs with encoded characters are correct in Markdown. The bug is in whatever viewer you are using, which is not processing encoded characters correctly.

See here:

https://spec.commonmark.org/0.30/#example-502

And for info if we change and convert `%20` to a space we will break other (also buggy) viewers which expect everything to be encoded, so it's not possible for us to "fix" the problem. Your best bet is to file a report with the viewer you're using.
