### ISSUE TITLE
Android app 2.10.x upwards shows error of missing file when taking screenshot

### ISSUE THREAD

**Issue by Fogjogger** [laurent22/joplin#7975]
![20230326_101249](https://user-images.githubusercontent.com/128966608/227799479-61064659-f808-442b-9cec-4286ff7acd72.jpg)

I got installed Joplin on Nextcloud on own VPN server Ubuntu 20.04. (No recent updates to database or php)

An error on my android Samsung a5 2017 start showing about 2 weeks after 2.10 release. Only downgrading to 2.08.x does the job. After upgrade error is coming back.

The same error when installed Joplin on other android mobile Samsung s23 Ultra.

Joplin is not showing other errors.

## Environment

Joplin version: 2.10.8
Platform: android
OS specifics: all

## Steps to reproduce

1. Taking screenshots and clicking share/Joplin OR open existing screenshot in gallery and trying to share to Joplin
2. Error popup with message: "file does not exist at:"
3. OK button closes message and creates Untitled, empty file in Joplin which synchronise with no other problems but still empty.

## Logfile
![Screenshot_20230326_204845_Joplin](https://user-images.githubusercontent.com/128966608/227800809-5372f064-625b-44a1-9914-dfbe31a9ae5f.jpg)

**Comment by palfreym** [comment]
I have the same problem :-(

**Comment by Fogjogger** [comment]
Hi.I think this is because of turning some google apps/servicess off.Ta
-------- Original message --------From: palfreym ***@***.***> Date: 02/05/2023  13:34  (GMT+00:00) To: laurent22/joplin ***@***.***> Cc: Fogjogger ***@***.***>, Author ***@***.***> Subject: Re: [laurent22/joplin] Android app 2.10.x upwards shows error of missing file when taking screenshot (Issue #7975) 
I have the same problem :-(
