### ISSUE TITLE
Revert 'fix' for #3917 for numbered lists

### ISSUE THREAD

**Issue by sedlund** [laurent22/joplin#7979]
## Environment

Joplin version: 2.9.17
Platform: Windows
OS specifics: 

I consider the merge to 'fix' #3917 to be a regression.  This is incorrect markdown syntax for ordered lists.  All wiki's also use the 1. syntax, this makes maintenance of lists easy to reorder without having to manually renumber everything by hand when moving or inserting steps.  This is a FEATURE of markdown.  The 'fix' merged makes managing lists in Joplin much more difficult than it should be.

**Comment by CalebJohn** [comment]
> This is incorrect markdown syntax for ordered lists

The Joplin behaviour is consistent with the [commonmark spec](https://spec.commonmark.org/0.30/#ordered-list-marker).

Further, the Joplin renders the 1. syntax correctly e.g.
![image](https://user-images.githubusercontent.com/2179547/228102331-4a212f83-c964-409c-b6a7-9aac61849510.png)

I do understand that it must be annoying to have the lists auto-increment when you would prefer them not too. Fortunately, I think it's actually possible to disable the auto-increment using a plugin. I'll look in to it tonight and see if I can get something pushed out.

**Comment by sedlund** [comment]
I concur that rendered markdown does comply with commonmark.  Although, the specification does not specify what a markdown editor's behavior should be.

After rethinking the current behavior, it's clear that it's goal is as a basic editor, so the implementation is correct, unless it were to be made better by updating the list to be correct when modifying the items (as it does in the markdown view).

I've realized I should be using the external editor.

Thanks for your feedback and time!  Please close as you see fit.
