### ISSUE TITLE
Canceling bypasses biometric auth

### ISSUE THREAD

**Issue by winghat** [laurent22/joplin#7984]
## Environment

Joplin version: 2.10.8
Platform: Android
OS specifics: v10

## Steps to reproduce

With "Use biometrics" option on,
1. Reboot OS. Run Joplin app.
2. Popup "Verify your identity" with fingerprint: CANCEL
3. "Could not verify": OK
4. Exit
5. Rerun the app
6. Notes show up.

**Comment by laurent22** [comment]
Not really the proper way to disclose security issues, is it? And that's most likely manufacturer specific, because I can't replicate on my phone or emulator. Other people who tried also can't.

**Comment by pirm-in** [comment]
Just came here to report the same issue. Can reproduce it everytime.

Joplin: 2.10.8
OS: EMUI12/Android11
Phone: Huawei P30 pro

**Comment by laurent22** [comment]
I believe this is fixed in prerelease
