### ISSUE TITLE
Help needed to fix file or image attachment on Android 5.x

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8]
A few users have reported they cannot attach images in Android 5.x however I cannot replicate it, and I haven't managed to get anyone to provide more information about it.

If it's happening on your device too, please could you do the following?

- Go to Configuration and enable Advanced options
- Try to attach an image to a note, which should fail
- Open the menu in the top right hand corner and click Log
- Make a screenshot of it and send it over

That would be really useful to help fix this as for some reason it's not doing it in neither my Android phone nor emulators.

**Comment by cmill72** [comment]
Just to let you know, I attempted this on a Nexus 6P running Android 8.0 and it worked perfectly.  No errors here.

**Comment by laurent22** [comment]
Thank you, looks like it's working now.
