### ISSUE TITLE
Joplin Clipper HTML Notes Change Background of Other Notes

### ISSUE THREAD

**Issue by SyafaHadyan** [laurent22/joplin#8013]
## Environment

Joplin version: 2.9.17
Platform: Windows 10 Home Single Language
OS specifics: 

|Processor|Installed Ram|
|:---|:---|
|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz 2.80|8.00 GB (7.70 GB usable)|

## Steps to reproduce

1. Open Joplin.
2. Open any note.
3. Open an HTML note created using Joplin Clipper from [Google Form](https://docs.google.com/forms/).
4. Open other markdown note.
5. Observe that the background changes from white to the background of the previous note created using Joplin Clipper.

## Describe what you expected to happen

The background of the current note should not change.

## Bug Description

When I open an HTML note created using Joplin Clipper from Google Forms, and then open another note, the background of the second note changes to the background of the previous note created using Joplin Clipper. This is not the expected behavior, and it is causing confusion while using Joplin.

## Logfile

[issues.txt](https://github.com/laurent22/joplin/files/11135493/issues.txt)
[-1680504348813.log](https://github.com/laurent22/joplin/files/11135494/-1680504348813.log)

## Video

https://user-images.githubusercontent.com/107655102/229432110-3fb31c65-2fe1-49cd-bc9b-82f825feaa09.mp4

**Comment by Daeraxa** [comment]
I think this is resolved with https://github.com/laurent22/joplin/commit/d1e545ac2c3b79d2c76a102bdc3046799607a716. Not sure if this is in 2.10 but might be in 2.11 so it can be tested when 2.11 is out for pre-release.

**Comment by dpoulton-github** [comment]
> Not sure if this is in 2.10

From the release notes it appears that  https://github.com/laurent22/joplin/commit/d1e545ac2c3b79d2c76a102bdc3046799607a716 was included in [v.2.10.8](https://github.com/laurent22/joplin/releases/tag/v2.10.8)

**Comment by laurent22** [comment]
Indeed should be resolved in d1e545ac2c3b79d2c76a102bdc3046799607a716
