### ISSUE TITLE
Set line spacing and font sizing controls

### ISSUE THREAD

**Issue by xelcho** [laurent22/joplin#802]
### Operating system

- Linux

### Application

- Desktop

 In using the reader to read, web clippings I am not able to control the font size or line spacing easily. I am able to resize the whole app via the zoom txtbx and a reload. When this is done the font is overwriting lines only at 1.0 
![screenshot_20180916_180816](https://user-images.githubusercontent.com/30007489/45601486-b296be00-b9db-11e8-8e84-649ea12c4b7d.png)
, see attached image.

Please advise

**Comment by laurent22** [comment]
What url did you clip? It's needed to be able to replicate the bug

**Comment by xelcho** [comment]
Here ya go:

https://www.nakedcapitalism.com/2018/09/jumping-the-abyss-marriner-s-eccles-and-the-new-deal-1933-1940.html

Thanks for the quick response!

**Comment by laurent22** [comment]
Note: for example happens when selecting zoom 200%

**Comment by xelcho** [comment]
Thx, you rock!!!
