### ISSUE TITLE
Mobile: CodeMirror syntax highlighting broken

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#8022]
## Environment

Joplin version: 66ef37b
Platform: Android
OS specifics: Android 13

**See also**: https://github.com/laurent22/joplin/issues/7253, https://github.com/laurent22/joplin/commit/66ef37bd4eae0ea0c02fb0096db85fef4693990e

### With the app
1. Create a note with the following content:
```
# Heading 1
## Heading 2

*Test*... This is a **test**.
```
2. Enable the beta editor
3. Edit the note 

### With the editor demo page
1. Open `packages/app-mobile/components/NoteEditor/CodeMirror/demo.html` in a browser
2. Replace the content of the textbox with
````
Testing...

# Foo
## Foobar

*test*... This is a **test**.

| Foo | |
|-------|--|
|     |   |

_foo_

`test`. ```test```

```js

function foo() {
    alert(3);
}

```


````

This results in the following:
![screenshot of editor with only partial highlighting](https://user-images.githubusercontent.com/46334387/201497511-99476874-ddaf-4a25-97fa-bbcb16590190.png)

## Describe what you expected to happen

The headers and bolded/italic regions should have different sizes/styles.

## Notes

Updating the CodeMirror dependencies seems to fix the issue. I plan to submit a pull request soon.

**Comment by laurent22** [comment]
Do you know what may have broken this? I have excluded CodeMirror from the Renovate updates, so normally it shouldn't change unless we change it. Unless there's some additional dependencies that should be excluded?

**Comment by personalizedrefrigerator** [comment]
It should also ignore `@lezer/highlight` and other `@lezer/` packages (`@lezer` is the project used by CodeMirror to do parsing).

**Comment by personalizedrefrigerator** [comment]
See https://github.com/laurent22/joplin/pull/8023 .

Interestingly, all tests passed (including the test that was later disabled in https://github.com/laurent22/joplin/commit/66ef37bd4eae0ea0c02fb0096db85fef4693990e) when `@lezer/highlight` was updated in https://github.com/laurent22/joplin/commit/b8854a99be59775c5c526f4290c67fa02bd85385 .

**Edit**: b8854a99be59775c5c526f4290c67fa02bd85385 may have skipped parts of the CI:
![image](https://user-images.githubusercontent.com/46334387/230490908-9f464338-5ef3-4bd5-83eb-f01e259c13bd.png)

Running `git checkout b8854a99be59775c5c526f4290c67fa02bd85385 ; yarn install ; cd packages/app-mobile ; yarn test` results in the relevant test failing.
