### ISSUE TITLE
Reduce installer size

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8028]
Let's see if we can reduce the installer size.

- For now remove packages/pdf-viewer, it takes 250 MB unpacked and doesn't even work properly
    - Also remove any reference to pdf-viewer
    - Hide the setting `useCustomPdfViewer`. And if the user has it enabled, make sure it reverts to the default PDF viewer
- Use the electron-builder `compression` options - https://www.electron.build/configuration/configuration.html
- Should we bundle all the JS code using a bundler?
- How about tree shaking - can we implement this?

**Comment by palerdot** [comment]
> Use the electron-builder compression options - https://www.electron.build/configuration/configuration.html

As per the docs,
> maximum doesn’t lead to noticeable size difference, but increase build time.

Should this be tried?

**Comment by laurent22** [comment]
> Should this be tried?

But why not? Is it difficult to turn on the flag and compare the size before and after?

**Comment by palerdot** [comment]
Ok. Will do this.

**Comment by laurent22** [comment]
This is the current state in macOS

```
$ du -ch -d 1 . | sort -h
 68M    ./renderer
174M    ./lib
250M    ./pdf-viewer
491M    .
491M    total
```

**Comment by antoniopaolini** [comment]
> * For now remove packages/pdf-viewer, it takes 250 MB unpacked and doesn't even work properly

I feel guilty... :-)

**Comment by laurent22** [comment]
Well there's probably a way to optimise this, but we don't have resources for this at this point. For now I feel we don't gain enough from this features to increase the app size so much

**Comment by antoniopaolini** [comment]
I agree with you. 
Custom pdf viewer would have been a nice thing, especially for the behaviour in the note viewer, which unlike the current viewer does not constantly redraw when editing. 
If it can be integrated without problems in the future, the increase in size will be acceptable, but for the time being I agree with you.

**Comment by laurent22** [comment]
We've done what we could but there's no easy solution.
