### ISSUE TITLE
Lock,pinned and colorful notes

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [laurent22/joplin#803]
Please add an option to lock notes and an option of pinning colorful notes just like scarlet or material notes.

**Comment by foxmask** [comment]
Hi,
If you could create one issue per topic that will be great. Also pointing what /where are scarlet/materiel notes?
Thanks

**Comment by Ashutosh-Kukreti** [comment]
I'm sorry for being so vague.
I was talking about this app: https://f-droid.org/en/packages/com.bijoysingh.quicknote/

I tried it sometime ago and it has two good features:
1. you can pin colorful notes.
2. You can lock the notes in the app.

I was thinking that these features can be agreat addition to Joplin.

**Comment by foxmask** [comment]
I already asked for pinned notes [here](https://github.com/laurent22/joplin/issues/296)

**Comment by foxmask** [comment]
we did not say that :) it's a feature request marked as "enhancement" , "nice to have"

**Comment by Ashutosh-Kukreti** [comment]
Okay
Thanks , I'll wait :)

**Comment by justyns** [comment]
https://keep.google.com/ is another example of an app that lets you select a color for your notes.  I'm not really sure how that would translate to Joplin's current interface though..   Maybe there could be a new card-like interface in the future?

**Comment by laurent22** [comment]
Duplicate of #296
