### ISSUE TITLE
Add support for Vosk

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8030]
Vosk allows adding an offline, ungoogled (or unappled), support for text to speech. We should see if it can be integrated to the mobile application:

Ref: https://alphacephei.com/vosk/

RN Package: https://github.com/riderodd/react-native-vosk

**Comment by 7john8** [comment]
We might also benefit from the likewise offline capable whisper from OpenAI. Even the smaller models are said to rival Vosk.

https://github.com/openai/whisper

There is also a port of whisper that takes less resources and is IOS/Android capable:

https://github.com/ggerganov/whisper.cpp

**Comment by laurent22** [comment]
Done
