### ISSUE TITLE
Markdown rendered using ghost style from another notes

### ISSUE THREAD

**Issue by NothingCtrl** [laurent22/joplin#8032]
In markdown rendered mode, after you view a note that is clipped from a web page and then switch to a note (write in markdown), rendered view style (font size, background etc...) is wrong, check in developer mode, showing that elements using difference style file.

Notes: I using `userstyle.css` for styling the rendered note

Example source of clipped URL: https://superuser.com/questions/1756354/windows-defender-credential-guard-does-not-allow-using-saved-credentials-for-r

## Environment

Joplin version: Desktop version 2.9.17
Platform: Windows
OS specifics: Windows 11 amd64

## Steps to reproduce

1. Make sure you have added some custom css style in `userstyle.css`, for example: `body {font-family: Avenir, Arial, sans-serif !important; font-size: 15px}`, created a markdown note for test (optional), example:
  ```
  #### **Consumables** are meant for products you need to receive in the warehouse, but you will not use to make other products and will not sell them to Customers.  You consume them yourselves.

  Examples:  Cleaning Supplies, Coffee, Printer Paper.

  * These are the things you would NOT count during a cycle count or full Inventory count.
  * You can receive them, deliver them and see the movement history.
  ```
2. Go to: https://superuser.com/questions/1756354/windows-defender-credential-guard-does-not-allow-using-saved-credentials-for-r
3. Click on Joplin Web Clipper, choose "Clip complete page (HTML)"
4. Open just clipped note in view mode in Joplin app
5. Switch to a another note, it will render in wrong style (example: smaller font), using element inspectation will showing the css source file is changed.

## Describe what you expected to happen

Note should render with correct style

![image](https://user-images.githubusercontent.com/5380820/230712502-ee6fbfaf-3d5d-4ccc-b65b-0bdfb9b9f49d.png)

## Logfile

No error in console

**Comment by laurent22** [comment]
Please try version 2.10
