### ISSUE TITLE
Change Keyboard Shortcuts for Wysiwyg Editor does not work

### ISSUE THREAD

**Issue by fravid77** [laurent22/joplin#8038]
## Environment

Joplin version: 2.9.17 and 2.10.13
Platform: Windows 10
OS specifics: 

## Steps to reproduce

1. I open Tools -> Options -> Keyboard Shortcuts
2. I reassign bold to CTRL+R ans Save
3. I  open an note in the the wysiwyg editor
4. I select a word an press CTRL+R  -> **nothing happens**
(CTRL+B still works in the wysiwyg editor)
5. I change to the markdown editor and select a word
6. I press CTRL+R and the word is changed to bold.

## Describe what you expected to happen

Expectation: At step 4, the selected word should be shown in bold when pressing the reassigned shortcut CTRL+R.

**Comment by marph91** [comment]
AFAIK there isn't a way to change the [wysiwyg editor shortcuts](https://www.tiny.cloud/docs/advanced/keyboard-shortcuts), yet. See https://discourse.joplinapp.org/t/custom-keyboard-shortcuts-for-any-command/26621.
