### ISSUE TITLE
Firefox's Resist Fingerprinting breaks Joplin Web Clipper

### ISSUE THREAD

**Issue by junoslukan** [laurent22/joplin#8046]
When setting `user_pref("privacy.resistFingerprinting", true);` in `user.js`, the Web Clipper extension cannot be opened. When clicked on, it only shows a thin sliver of UI, like this:

![screenshot](https://user-images.githubusercontent.com/19954026/231531521-36c807db-3fc2-40f4-9874-2b36a131cacb.png)

This is not dependent on the currently viewed webpage. Other extensions such as KeePass-XC-Browser (also pictured) do not have a similar problem.

## Environment

Joplin version: Joplin 2.9.17 (prod, win32)
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes
Revision: a84a8e7
Web Clipper version: 2.11.2
Platform: Windows
OS specifics: Windows 10, Firefox: 112.0 (64-bit)

## Steps to reproduce

1. Set `user_pref("privacy.resistFingerprinting", true);` in `user.js`.
2. Relaunch Firefox.
3. Click on the Joplin Web Clipper extension.

## Describe what you expected to happen

I would expect the extension to first ask me for authorization (the desktop app still registers the request and I granted the authorization, see log below) and on subsequent clicks show the Web Clipper UI.

## Logfile
```js
17:04:57.337 Popup: Init bridge and restore state... index.js:113:9
17:04:57.339 Popup: Init bridge bridge.js:21:10
17:04:57.343 Popup: Env: prod bridge.js:84:10
17:04:57.344 Popup: Creating React app... index.js:117:9
17:04:57.347 findClipperServerPort: Trying 41184 bridge.js:256:12
17:04:57.363 findClipperServerPort: Got response: JoplinClipperServer bridge.js:259:12
17:04:57.379 Popup: Restoring saved state: 
Object { authToken: "", authTokenTimestamp: 0, selectedFolderId: null, token: "d6a57bb137ebd9adf2f42d249092d03dfb22663d5a8439e72cd115d453fab42e5b1234d74f7a6d95d35466ef845c6fab496f9b793e2ac8411c50683b0cb62796" }
bridge.js:244:10
17:04:57.381 Popup: GET auth/check bridge.js:400:10
17:04:57.392 checkAuth: we already have a valid token - exiting bridge.js:134:11
17:04:57.394 Popup: GET folders bridge.js:400:10
17:04:57.410 Popup: GET tags bridge.js:400:10
17:04:57.424 Sending message  
Object { name: "isProbablyReaderable" }
bridge.js:394:10
17:04:57.435 Popup: Got command: 
Object { name: "isProbablyReaderable", value: true }
bridge.js:47:11
17:05:11.557 Popup: Init bridge and restore state... index.js:113:9
17:05:11.559 Popup: Init bridge bridge.js:21:10
17:05:11.561 Popup: Env: prod bridge.js:84:10
17:05:11.562 Popup: Creating React app... index.js:117:9
17:05:11.563 findClipperServerPort: Trying 41184 bridge.js:256:12
17:05:11.572 findClipperServerPort: Got response: JoplinClipperServer bridge.js:259:12
17:05:11.597 Popup: Restoring saved state: 
Object { authToken: "", authTokenTimestamp: 0, selectedFolderId: null, token: "d6a57bb137ebd9adf2f42d249092d03dfb22663d5a8439e72cd115d453fab42e5b1234d74f7a6d95d35466ef845c6fab496f9b793e2ac8411c50683b0cb62796" }
bridge.js:244:10
17:05:11.600 Popup: GET auth/check bridge.js:400:10
17:05:11.602 Sending message  
Object { name: "isProbablyReaderable" }
bridge.js:394:10
17:05:11.606 checkAuth: we already have a valid token - exiting bridge.js:134:11
17:05:11.611 Popup: GET folders bridge.js:400:10
17:05:11.616 Popup: Got command: 
Object { name: "isProbablyReaderable", value: true }
bridge.js:47:11
17:05:11.634 Popup: GET tags bridge.js:400:10
17:05:11.712 Popup: Saving state 
Object { selectedFolderId: null }
bridge.js:236:11
```

**Comment by gvlx** [comment]
Also observed since Firefox 111.0 (Windows 10).

resetting the privacy.resistFingerprinting to "false" enables normal behavior

there's maybe something to add on the property privacy.resistFingerprinting.exemptedDomains ?

**Comment by liza** [comment]
confirming this is happening with Firefox 112.0 and Librewolf 112.0-1; on Ubuntu 20.04; running Gnome/GDM3 41.0 on flatpaks, snaps and debs. 

my original installations where flatpaks. after their recent update, the joplin web clipper stopped working. i thought it may have been a permissions problem, so i changed parameters with Flatseal with no success. so i installed both snaps and tested again. same result. desperate, i purged both flatpaks & snaps and did fresh installs of the debs. nothing changed. same issue. 

i may or may not have cried myself to sleep. 

so after six installs in the last 24 hours, thanks for posting this. RFP doesn't disable javascript but it makes the app throw a notice like "Got command: isProbablyReaderable" and die out silently. losing this app would have thrown a huge monkey wrench on my workflow. 

at least now i don't have to cry myself to sleep... allegedly.

**Comment by laurent22** [comment]
Please report these bugs to Mozilla

> Fingerprinting Protection is a different, experimental feature under heavy development in Firefox. It is likely that it may degrade your Web experience so we recommend it only for those willing to test experimental features.

https://support.mozilla.org/en-US/kb/firefox-protection-against-fingerprinting
