### ISSUE TITLE
Joplin goes unresponsive after closing external editor

### ISSUE THREAD

**Issue by anasem** [laurent22/joplin#805]
### Operating system

- Linux

### Application

- Desktop

### Description
Open external editor (VIM) write something, save and close. Joplin gets stuck until forcibly killed, the log file is flooded with:
```
10097 2018-09-18 15:45:25: "ExternalEditWatcher: Stopped watching all files"
10098 2018-09-18 15:45:25: "Reducer action", "NOTE_FILE_WATCHER_CLEAR"
10099 2018-09-18 15:45:25: "ExternalEditWatcher: Stopped watching all files"
10100 2018-09-18 15:45:25: "Reducer action", "NOTE_FILE_WATCHER_CLEAR"
10101 2018-09-18 15:45:25: "ExternalEditWatcher: Stopped watching all files"
10102 2018-09-18 15:45:25: "Reducer action", "NOTE_FILE_WATCHER_CLEAR"
10103 2018-09-18 15:45:25: "ExternalEditWatcher: Stopped watching all files"
10104 2018-09-18 15:45:25: "Reducer action", "NOTE_FILE_WATCHER_CLEAR"
10105 2018-09-18 15:45:25: "ExternalEditWatcher: Stopped watching all files"
10106 2018-09-18 15:45:25: "Reducer action", "NOTE_FILE_WATCHER_CLEAR"
```

**Comment by laurent22** [comment]
How do you set it up to open vim from the desktop application?

**Comment by anasem** [comment]
Sorry, I should have mentioned it's actually GVim but I've also tried with Leafpad and xed, still the problem persists. I'm setting the text editor command without any arguments. I've also noticed Joplin keeps working fine after closing the external editor until I press "New note" or "New to-do" then it goes unresponsive.
