### ISSUE TITLE
Divest OS 20 (A13) synchronization does not work.

### ISSUE THREAD

**Issue by ed-karate** [laurent22/joplin#8058]
Synchronization attempt failed. Android 13 (Divest OS) without google services.
![photo_2023-04-17_16-06-23](https://user-images.githubusercontent.com/116094642/232495608-24a3a7e5-49ad-41cb-ac9a-d4f02878bfb4.jpg)

Debug log
[syncReport-1681737214510.txt](https://github.com/laurent22/joplin/files/11250599/syncReport-1681737214510.txt)

**Comment by laurent22** [comment]
Try with 2.10
