### ISSUE TITLE
Syncing S3 cannot synchronize the information in the bucket to a brand new device.

### ISSUE THREAD

**Issue by arantir53** [laurent22/joplin#8059]
I want to retrieve my previous notes from a new PC. Although the log shows that over 600 items were retrieved, only the welcome document is displayed in the list. What could be the issue?
![eb3cd92779970063a189f6d024650a8](https://user-images.githubusercontent.com/34082555/232539957-a2737ea3-4219-4efd-83b8-b674f22702c5.png)
Debug log
[syncReport-1681746642869.csv](https://github.com/laurent22/joplin/files/11252734/syncReport-1681746642869.csv)

**Comment by apotoczek** [comment]
Having a similar issue after recently reinstalling Win10.

Works fine on a couple Macs and iPhones, but on the PC, I've tried various Joplin version downgrades, re-installs, deleting local data, rotating profiles, AWS access keys, but keep running into the same issues:

1. Sync check in settings works about half the time and errors out half... (and again, settings work on mac/i OS, so not an AWS/creds/syntax problem)

2. Actual sync usually results in one of the following errors:

```
Created local items: 88.
Created remote items: 9.
Fetched items: 89/100.
Completed: 17/04/2023 11:58 (68s)
Last error: TypeError: Cannot create property 'message' on string 'request to https://my-bucket....s3.amazonaws.com...&x-id=GetObject failed, reason: getaddrinfo ENOTFOUN
```

```
Completed: 17/04/2023 12:26 (21s)
Last error: request to https:/my-bucket....s3.amazonaws.com/info.json...&x-id=GetObject failed, reason: getaddrinfo ENOTFOUND my-bucket.s3.amazonaws.com](http://my-bucket.s3.amazonaws.com/)
```

Note: getting that URL, for example simply via browser, does successfully get the info.json RE the 2nd error, so nothing wrong with my bucket name, or URL, and I've tried rotating access keys in AWS, and again it all works fine on my Mac/iPhone.

Joplin used to work fine on this same PC before Win10 clean wipe, but I don't recall any particular differences in terms of my setup/software that would make a difference here, other than Joplin version, which I tried current 2.9.17, pre-release 2.10.13, 2.8.8, and 2.7.15, with same problems.

**Comment by arantir53** [comment]
@apotoczek  I tried the same thing, deleting local data and re-downloading from sync target, but it didn't work either. However, I haven't tried using an older version of the software, so I'll give that a try. If 2.7.15 doesn't work, I'll try even earlier versions.

**Comment by apotoczek** [comment]
@arantir53 lmk if an earlier version works for you.. I gave up and went back to the free Dropbox tier for now.  What's really puzzling is why it seems to sync on a rare occasion, but errors out almost all other times (i.e. I see it synced Apr 18th, while I posted the above issue on the 17th).
