### ISSUE TITLE
Is there a way of changing the used colours for the terminal app

### ISSUE THREAD

**Issue by mschaaf** [laurent22/joplin#806]
In my current terminal configuration, some of the used colours are to dark. 
Is there a way to change that?
Where is the place where these colours are defined?
Thanks for your help.
![screenshot](https://user-images.githubusercontent.com/703355/45699809-2c10e680-bb6b-11e8-8a0e-55b8685d9492.png)

**Comment by laurent22** [comment]
Does it work with a black terminal and white text? I'm not sure what's being highlighted actually as, if I remember correctly, only links have a different colour.

**Comment by mschaaf** [comment]
with a black terminal it is better readable but still dark
![screenshot](https://user-images.githubusercontent.com/703355/45752154-d98c0480-bc14-11e8-85b5-1b4b88be74d6.png)

**Comment by laurent22** [comment]
I think it might be some issue with the way the theme is done. [The code](https://github.com/laurent22/tkwidgets/blob/master/src/ListWidget.js#L275) simply specifies "bgWhite and black text" for selected item in focs, and "bgBlackBright and black text" for selected item not in focus.

So the theme needs to map "bgBlackBright" to something that makes sense (maybe some light blue colour). It seems to map white and black correctly (to white and blue). I'll close this issue as I don't think it can be fixed on Joplin side, but if you find some more info feel to post back.

**Comment by mschaaf** [comment]
I switched to a base16 project terminal theme and that solves it for me. Thanks for your help.
