### ISSUE TITLE
FFox Web clipper fails to show when privacy.resistFingerprinting is true

### ISSUE THREAD

**Issue by wiwwo** [laurent22/joplin#8060]
Might be hard to fix (if not impossible): by setting `privacy.resistFingerprinting` to `true` in `about:config`, Joplic web Clipper fails to appear.

**Comment by dpoulton-github** [comment]
This closed issue covers this https://github.com/laurent22/joplin/issues/8046. 

Below is the comment by @laurent22.

> Please report these bugs to Mozilla
>> Fingerprinting Protection is a different, experimental feature under heavy development in Firefox. It is likely that it may degrade your Web experience so we recommend it only for those willing to test experimental features.
>
> https://support.mozilla.org/en-US/kb/firefox-protection-against-fingerprinting

**Comment by GlassGruber** [comment]
I can confirm this as well on Firefox ESR 112.11.0 , but as a workaround is possible to install version [2.8.1 of the clipper](https://addons.mozilla.org/en-US/firefox/addon/joplin-web-clipper/versions/) and it will work again, even with `privacy.resistFingerprinting` enabled.
Maybe should be noted this also in #8046.

**Comment by wiwwo** [comment]
2.8.1 made the trick, thanks!!

**Comment by wiwwo** [comment]
Closing as "won't fix", even do, as suggested by GlassGruber, installling the 2.8.1 made the trick.
