### ISSUE TITLE
Markdown viewer does not switch back to light theme

### ISSUE THREAD

**Issue by vroger11** [laurent22/joplin#8066]
## Environment

Joplin version: Joplin 2.9.17 
Platform: Macos
OS specifics: 13.3.1

## Steps to reproduce

1. open joplin
2. set the option that switch automatically theme with system
3. open the app with light theme (while the system is on light theme)
4. wait until the theme switch to dark -> everything went ok
5. wait until the theme switch to light -> not all the theme switch to the light one especially the markdown viewer and code editor

## Describe what you expected to happen
The switch of the theme from dark to light should be complete and not ending with a mix of the two themes.

## Logfile

Not having one, but I can try to provide one if it is needed

**Comment by laurent22** [comment]
Try 2.10 please
