### ISSUE TITLE
v2.10.13 - Enter Key No Longer Saves & Closes The Tag Dialog

### ISSUE THREAD

**Issue by dpoulton-github** [laurent22/joplin#8072]
## Environment

Joplin version: 2.10.13
Platform: Windows 10 / Linux
OS specifics: 22H2 / Mint 20.3 Cinnamon
Modifications / Plugins: None
Sync method / target: None

## Steps to reproduce

1. Open the tag dialog box
2. Type a tag name and press ENTER to either select or create a tag
3. Without typing anything more, press ENTER again **to save the changes** and close the dialog box
4. Nothing happens. The tag dialog box does not save/close
5. The changes can be saved and the tag dialog box *can* be closed by selecting "OK" with the mouse

## Describe what you expected to happen

The tag dialog box should save and close when pressing ENTER if not selecting or creating another tag. This is the behaviour in v2.9.17 and before. It appears that the dialog box no longer has a default of "OK".

This has been an issue since at least v2.10.3 (see forum post below).

## Logfile

With **flags.txt** enabled no errors appear in the log or the console log.

## Other Information

- Linked forum post > [Can we use less mouse when entering tags](https://discourse.joplinapp.org/t/can-we-use-less-mouse-when-entering-tags/29202)

**Comment by priyanshu-kun** [comment]
@dpoulton-github  shouldn't you use the ESC(escape) key?

**Comment by dpoulton-github** [comment]
@priyanshu-kun 

No. ENTER was the equivalent of pressing "OK" and so any tags you had selected or created were also saved. Using ESC does close the dialog but it has the same effect as pressing "CANCEL" and nothing is saved. However your comment did highlight that I had not made the "saving" aspect clear in the issue. I have therefore updated it. Many thanks.
