### ISSUE TITLE
Joplin synchronizes after start of app although interval is set to `Disabled`

### ISSUE THREAD

**Issue by jmizv** [laurent22/joplin#8073]
## Environment

```
Joplin 2.9.17 (prod, linux)

Client ID: /clipped/
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: a84a8e771
```
Platform: Linux
OS specifics: 64-bit Ubuntu 22.04.2 LTS (GNOME v42.5)

I've set the synchronization interval in the settings to `Disabled`. After that no synchronization happens which is fine. But when I close the app and start it again it first starts to synchronize which is not what I've configured. Did I miss something? Is this the default behaviour although I've set it differently?
Note: that in this scenario Joplin would try to sync with Dropbox. Because I have no access to `content.dropboxapi.com` Joplin fails every time to sync (which is why I've disabled syncing in this scenario). I have also set a proxy

## Steps to reproduce

1. Set Sync interval to `disabled`
2. Restart the application
3. See that it is trying to sync nonetheless

## Describe what you expected to happen
I've expected that Joplin does not try to synchronize after (re)start of the application.

**Comment by Daeraxa** [comment]
This is intentional. It disables the sync interval but the app still sync to avoid conflicts. For it not to sync at all you need to change the sync target to `(none)`.
