### ISSUE TITLE
Joplin的windows x64客户端使用系统自带的微软拼音输入法会出现候选字框遮挡输入的字母这个问题

### ISSUE THREAD

**Issue by zhousone** [laurent22/joplin#8078]
## Environment

Joplin version: 
Platform: Windows10 X64
OS specifics: 

## Steps to reproduce

1. 
2. 
3. 

## Logfile

我在使用Joplin的windows x64版本客户端写笔记的时候，使用win10自带微软输入法，输入中文会出现候选字框挡了近一半输入的字母，很别扭，能否解决下这个问题。

我尝试在view中使用zoom out 三次，基本上能够显示正常。看起来这是同缩放相关的bug。

**Comment by wh201906** [comment]
Please fill out the Joplin version you are using. 
Plus, which editor are you using? The Markdown editor or the rich text editor(WYSIWYG editor)
请填写你正在使用的Joplin版本
另外，你是在什么编辑器上遇到这个问题的呢？是Markdown编辑器还是富文本编辑器(所见即所得编辑器)？

**Comment by huozhebuhao** [comment]
![image](https://github.com/laurent22/joplin/assets/79900170/44ac5fc0-86f2-49ea-baee-c81896f2c8ca)
