### ISSUE TITLE
Custom sort of to-do items does not work

### ISSUE THREAD

**Issue by Spereicle** [laurent22/joplin#8082]
Sorting To-Do notes by custom order does not result in notes actually being sorted. 

## Environment
Joplin 2.9.17 (prod, win32)
Client ID: 42f2f9b1c6834541be54808d1c5463a2
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes
Revision: a84a8e7

Platform & OS: Microsoft Windows [Version 10.0.22621.1555]

## Steps to reproduce

1. Create a list of to-do items
2. drag and drop to re-sort
3. accept 'To manually sort the notes... -> Do it now

## Describe what you expected to happen

Items would be successfully sorted

## Other
Long standing issue on multiple platforms.
Also see: [Custom sort does not work #4162](https://github.com/laurent22/joplin/issues/4162)

**Comment by glantucan** [comment]
Same here.
Joplin is great, but this is the only thing preventing it to really be useful for me. No pressure ;P
