### ISSUE TITLE
Issue with synchronisation - FetchError: request to [webdav URL] failed, reason: read ECONNRESET

### ISSUE THREAD

**Issue by wengfch** [laurent22/joplin#8093]
Hello Joplin development team,

I am writing to report an issue I have encountered with synchronisation in Joplin. When attempting to sync, I am receiving the following error message:

FetchError: request to [webdav URL] failed, reason: read ECONNRESET
at ClientRequest.<anonymous> (/app/node_modules/node-fetch/index.js:133:11)
at ClientRequest.emit (node:events:526:28)
at Socket.socketErrorListener (node:_http_client:442:9)
at Socket.emit (node:events:526:28)
at emitErrorNT (node:internal/streams/destroy:157:8)
at emitErrorCloseNT (node:internal/streams/destroy:122:3)
at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

I have confirmed that my network connection is working properly and I am able to access the [webdav URL] in a web browser. However, Joplin is unable to connect to it and throws the ECONNRESET error.

I have attempted to troubleshoot the issue by updating to the latest version of Joplin, checking and reconfiguring my sync settings, clearing the cache, disabling antivirus and firewall software, and reinstalling Joplin from the official channel. However, the issue persists.

Could you please advise me on how to resolve this issue, or provide any further information that would be helpful in diagnosing it?

Thank you for your assistance.

Sincerely,

[weng]

**Comment by laurent22** [comment]
Do you use a custom TLS certificate? There are options to deal with this in the Sync settings

**Comment by wengfch** [comment]
We haven't tested with TLS yet, and have been using HTTP without any issues. Recently, we switched to a different webdav URL and the problem seems to be resolved, although we are not sure what the issue was.
