### ISSUE TITLE
Feature Request: Tab Completion in Terminal 

### ISSUE THREAD

**Issue by adueck** [laurent22/joplin#81]
I'm using the terminal client on Ubuntu. It would be great if we could have *tab completion in the command-line mode* for files and items within the notebook. This would make this great already great application extra convenient and amazingly fast in the terminal.

**Comment by laurent22** [comment]
Right, the input field I'm using from terminal-kit already supports auto-completion so it shouldn't be too hard to implement - https://github.com/cronvel/terminal-kit/blob/master/doc/high-level.md#ref.inputField

Tagging this as "good first issue" for now.

**Comment by gabcoh** [comment]
#82

**Comment by laurent22** [comment]
Implemented in #185
