### ISSUE TITLE
Android client doesn't sync anymore (unless you know where to look)

### ISSUE THREAD

**Issue by sciurius** [laurent22/joplin#810]
### Operating system

- Linux
- Android
- Probably others as well

### Application

- Desktop
- Mobile

### Description

Setup: Joplin (desktop) on Linux, sync to cloud (ownCloud). Collection of 4 folders, 15 notes, and 7 resources (small images).

In the desktop Joplin, enable encryption. Enter the desired key (note: single entry, no verification).
Content encryption starts and is extremely slow (takes 10 minutes or so!!!), though Joplin process hardly uses cpu. Eventually, it finishes. Synchronize.
The notes in cloud are now encrypted, the SQLite database contains plaintext notes.
A key note (type_: 9) is added.

Disable encryption. All notes are decrypted and re-synched. This is pretty quick (less than a minute).
Note, however, that the key note remains.

On Android, do a clean install of Joplin. Enable cloud sync. Synchronize. All notes show up.
Create a new note. Sync reports "Created remote items: 1" but nothing is synced. Updates from the server are not transferred either. Press Synchronise again: same results. The communication is stuck.

Only when inspecting "Encryption Config" (but why would you do that? All notes are unencrypted) it reports that encryption is enabled. Note that it didn't ask for a password.

Although many things can be explained, I think from end user perspective this is pretty mixed up.
At least it should notify the user that it enabled encryption, and prompt for a password with the option to disable encryption.

**Comment by foxmask** [comment]
i have an issue too with the sync on android (i think since last update) : 
```
Decryptionworker: error for:
xxxxxxxxxx_id_of_the_resource_xxxxx (resource)"  "Error: json decode : this isn't json!"
```
I thought that was because opf a note with 3 attachments so I dropped it but sync is stuck on the first message "Objets distants créés: 1" "Etat : en cours" and that's all, during hours.

**Comment by laurent22** [comment]
@foxmask, is it still happening? Could you try to enable debug mode to see if you have any error or warning?

@sciurius, as I understand there's not really a bug but just the process that's not very clear? It's documented there by the way but I agree usability could be improved: https://joplin.cozic.net/e2ee/

**Comment by foxmask** [comment]
@laurent22 I uninstalled since yesterday evening and the reinstall is in progress.

**Comment by laurent22** [comment]
By any chance, did you identify and kept the resource that couldn't be decrypted? If it's corrupted, there's probably nothing to do, but at least it shouldn't block syncing of other items.

**Comment by foxmask** [comment]
i don't know yet what's blocked the sync. I will wait the end if it's happened :)

**Comment by sciurius** [comment]
@laurent22 IMHO when a user installs Joplin, synchs with the cloud, and then it refuses to synch anymore without giving a clue why ­— that's definitely a bug.
It may be considerd okay that Joplin automatically enables encryption when it synchs a type_:9 note, but it should inform the user and ask for the password.

**Comment by foxmask** [comment]
@laurent22 finally sync finished successfully on my side.
