### ISSUE TITLE
Desktop: Sidebar unpredictably looses focus during keyboard navigation

### ISSUE THREAD

**Issue by PaulS-26** [laurent22/joplin#8101]
## Environment

Joplin version: 2.10.16
Platform: Windows
OS specifics: 10

## Steps to reproduce

1. Set focus to sidebar
2. Navigate through notebook list using arrow down and up keys
3. Focus unpredictably moves to note list, the arrow keys suddenly navigate through note list

## Describe what you expected to happen
Sidebar doesn't loose focus while navigating through notebook list using arrow keys

## Logfile

No errors or warnings appear in log or console

**Comment by Jackdaw-Zero** [comment]
This issue does still persist in version 2.11.11, also on Windows. Is it possible for this bug to be reopened?
