### ISSUE TITLE
andriod  error  -- Error: Got metadata for path but could not fetch content: debf3057844b4bf3b7698a7e2339de0d.md

### ISSUE THREAD

**Issue by bruceanhuifs** [laurent22/joplin#8104]
S3 beta when i use 
Error: Got metadata for path but could not fetch content: debf3057844b4bf3b7698a7e2339de0d.md

## Environment

Joplin version:  2.9.17
Platform: android 2.9.8
OS specifics:  win10

## Steps to reproduce

I am using S3 beta with Tencent Cloud data bucket. Syncing and creating new notes on the PC side is working normally. I am using the latest Android system 13. However, after taking photos or creating new notes on my phone, I am unable to sync the data with my PC. Even though the sync check in settings is normal, an error occurs during syncing with the message "Error: Got metadata for path but could not fetch content: debf3057844b4bf3b7698a7e2339de0d.md"

## Logfile

04-30T22:43 :00 : Synchronizer :
"There was some errors
04-30T22:43:00: Synchronizer: "Error : Got
metadata for path but could not fetch content :
debf3057844b4bf3b7698a7e2339deod.md
index.android.bundle : 1041 :16135
p@index.android.bundle :83 :588
index.android.bundle :83 :1893
p@index.android.bundle :83 :588
P@index.android.bundle :83 :2325
index.android.bundle :83 :1670
c@index.android.bundle :1041 :984
u@index.android.bundle :77 :157
index.android.bundle : 77 :866
index.android.bundle :85 :1672
k@index .android.bundle:85 :500
w@index.android.bundle :85 :898
callReactNativeMicrotasks@index.android.bundle:85:3054
value@index.android.bundle:38 :2868
index .android.bundle :38 :960
value@index.android.bundle:38 :2504
value@index.android.bundle :38 :919
value@[native code]
value@[native code]

**Comment by laurent22** [comment]
This is most likely due to this particular version of S3 being beta. Joplin requires certain properties to work properly, which are present in the basic S3 but I don't know about this beta one. Basically don't use untested, unsupported, beta services for sync. I'll close as we don't support this for now
