### ISSUE TITLE
Window corruption witg latest Joplin and Ubuntu 22.04 MATE LTS

### ISSUE THREAD

**Issue by nestorac** [laurent22/joplin#8108]
Just install and open the app, it is corrupted, it does not work, we should close it with 'kill' command. The window is incorrectly drawn, like you can see in the attached capture.

![image](https://user-images.githubusercontent.com/1285584/235488713-a2be6629-522e-47d2-b742-0b0cf551736f.png)

**Comment by laurent22** [comment]
In which way is it corrupted?

**Comment by nestorac** [comment]
The black space sorrounding the app, the mouse position does not correspond to the elements of the app, it's like it's broken. You cannot press the buttons, or select the text. It's weird. The only way of closing the app is killing it from console, if you change the desktop tom, say, the second one, Joplin is also there. You cannot control the desktop, the only way of fixing it is closing the app from virtual terminal (Ctrl+Alt+F1), for instance.

**Comment by laurent22** [comment]
You have some data there though, so it used to work. What has changed? Did you install a new version? And how?

**Comment by nestorac** [comment]
I use it with Joplin Cloud. It happens sometimes, I don't know why. If you ask me to test something, I'll do it. I use Ubuntu MATE 20.04 LTS with latest Joplin, installed Joplin for Desktop, AppImage.
Icon executes: `/home/nestor/.joplin/Joplin.AppImage  %u`

**Comment by nestorac** [comment]
I also use it from my Android mobile phone, with no problems. I'm new to Joplin, this is the only version I have tested.

**Comment by laurent22** [comment]
How do you install it?

**Comment by victor03303** [comment]
> How do you install it?

AppImages don't get installed but they are simply executed.

**Comment by victor03303** [comment]
> I also use it from my Android mobile phone, with no problems. I'm new to Joplin, this is the only version I have tested.

Dear nestorac

Please try the flatpak or snap version from Joplin. AppImages on general don't work well any longer because they use an older library (I think it's a library) libfuse. The creator of AppImages still don't use the newer libfuse that Ubuntu comes with. 

I believe you'll have a better experience with the snap or flatpak version.

**Comment by Daeraxa** [comment]
> AppImages on general don't work well any longer because they use an older library (I think it's a library) libfuse. The creator of AppImages still don't use the newer libfuse that Ubuntu comes with.

If this was the case and libfuse2 wasn't installed then it wouldn't work at all

> AppImages don't get installed but they are simply executed.

Yes but Laurent is trying to work out if they used the install script or the plain appimage I imagine.

**Comment by nestorac** [comment]
I have used the script, now I'll switch to snap, there are three options, is it this? [Joplin desktop](https://snapcraft.io/joplin-desktop)
