### ISSUE TITLE
Emojis are the wrong size until restart

### ISSUE THREAD

**Issue by robme** [laurent22/joplin#8114]
## Environment

Joplin version: Joplin 2.9.17 (prod, win32)
Platform: Windows 10
OS specifics: 

## Steps to reproduce

1. Create a new notebook.
2. Give the notebook an emoji _that you have not used before_.
3. Observe that the emoji is large.
4. Sync, then close and exit Joplin completely (including system tray).
5. Start Joplin again.
6. Observe that the emoji is small.
7. Create another new notebook.
8. Give the notebook an emoji _that you have not used before_.
9. Observe the difference in the size of the emojis.

![image](https://user-images.githubusercontent.com/6419062/235773683-b6ddad89-b5ce-4643-a60e-026ca1f4fe62.png)

## Describe what you expected to happen

Icons should always be the same size. Presumably small, since that's the size they all end up as eventually.

**Comment by FellipeMTX** [comment]
this is still a problem?

**Comment by robme** [comment]
It's still an issue, there is a PR above.

**Comment by robme** [comment]
Still an issue, it didn't magically fix itself.
