### ISSUE TITLE
Chrom and Firefox plugin not working

### ISSUE THREAD

**Issue by MarcS1975** [laurent22/joplin#8127]
## Environment

Joplin version: 2.9.17 (prod, win32)
Platform: Windows 10, Chrome, Firefox
OS specifics: 

## Steps to reproduce

1. install Joplin web clipper 
2. launch Joplin app on Windows 10
3. click on Joplin web clipper
4. Error apears

## Describe what you expected to happen
Clipping to Joplin

**Comment by dpoulton-github** [comment]
What is the error?

**Comment by MarcS1975** [comment]
The Joplin extension is not available on this tab due to:
tabsExecuteScript: Cannot load {"file":"/content_scripts/JSDOMParser.js"}:
Cannot access a chrome:// URL

**Comment by MarcS1975** [comment]
Firefox error: "The Joplin extension is not available on this tab due to:
Missing host permission for the tab "

**Comment by laurent22** [comment]
I believe this is solved in another thread?
