### ISSUE TITLE
Two icons in gnome after using ubuntu installer

### ISSUE THREAD

**Issue by csemken** [laurent22/joplin#813]
### Operating system

- Linux

### Application

- Desktop

Hi, just started using Joplin and I love it!

I just ran into one (very small) problem with the [ubuntu installer](https://raw.githubusercontent.com/laurent22/joplin/master/install_ubuntu.sh).  It manually creates a gnome shell icon.  However, upon running the app you are asked if you want to create one.  Clicking yes (and the message comes up every time until you click yes) results in two icons in the shell. 

Just deleting the icon created by the ubuntu installer (~/.local/share/applications/joplin.desktop) fixes the issue.  So I would suggest taking out the corresponding line in the installer:
`echo -e "[Desktop Entry]\nEncoding=UTF-8\nName=Joplin\nExec=/home/$USER/.joplin/Joplin-$version-x86_64.AppImage\nIcon=/home/$USER/.joplin/Icon512.png\nType=Application\nCategories=Application;" >> ~/.local/share/applications/joplin.desktop`

--Christoph

**Comment by laurent22** [comment]
Any chance you could create a pull request with the change? (as I'm not familiar with all this) Or maybe @tanrax could help with this?

**Comment by tanrax** [comment]
Personally I have had many problems with this automatic icon that is created. When updating it has become orphaned. Hence my contribution and I looked for a native way to integrate it into gnome.
I propose to deactivate it in Linux version and leave the Gnome integration.

**Comment by csemken** [comment]
I actually ran into the same issue now. The reason seems to be that – during updates – the AppImage file gets moved to `~/.joplin/Joplin-{version}-x86_64.AppImage`. 

Maybe there is a way to change the update process, such that the filename stays the same? Or could the gnome-integration feature be altered to create/update a link (e.g. `~/.joplin/Joplin-latest-x86_64.AppImage`), so that this link can be used in the `joplin.desktop` file instead?

Just two ideas I could think of. However, I am afraid I cannot help with implementing them, as I am not at all familiar with React. If they cannot be realised, deactivating the feature seems like a good idea, since it just leads to orphaned icons at the moment (well only after an update, but the default setting is to update automatically).

**Comment by tanrax** [comment]
Maintaining the same name could be a solution, maybe.

**Comment by 13xps** [comment]
I got the same issue running:

wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash

Ubuntu 18.04
Tested on upgrade, as well as fresh install, still have the same issue.
One icon is slightly blurry, other is perfect.

**Comment by 13xps** [comment]
I uninstalled then reinstalled, fixed the issue.

**Comment by csemken** [comment]
Just updated to the newest version. With the removal of the question at the start the issue is now resolved.
