### ISSUE TITLE
Rendering issues on an e-ink screen due to animations

### ISSUE THREAD

**Issue by IlyaBizyaev** [laurent22/joplin#8132]
## Environment

Joplin version: 2.11.2
Platform: Android
OS specifics: an Android-based e-book reader (Android version 8.1)

## Steps to reproduce

1. Install Joplin on an Android device with an e-ink screen
2. Press the hamburger button to open the sidebar
3. The sidebar is not legible due to artifacts

![PXL_20230504_223609600~2](https://user-images.githubusercontent.com/11175213/236344518-dd8479b2-0990-434f-b653-b4361f1c9f84.jpg)

## Describe what you expected to happen

My understanding is that adapted Android versions that run on e-books disable stock animations in common Android components, but Joplin uses some custom animations that are not affected by these adaptations. If that's the case, I think there should be a configuration option in the settings menu to disable in-app animations. For example, AnkiDroid has such an option.

FWIW it seems that most other features work well, i.e. I can view and edit notes as expected.

**Comment by personalizedrefrigerator** [comment]
This might be fixed by https://github.com/laurent22/joplin/pull/7953.

**Comment by IlyaBizyaev** [comment]
For the bot: I'll close this issue once a version is released with the change mentioned above, and I confirm that the problem is gone.

**Comment by IlyaBizyaev** [comment]
Fixed! There's still some animation, but it doesn't cause the artifacts.

**Comment by personalizedrefrigerator** [comment]
There was a build issue and https://github.com/laurent22/joplin/pull/7953 was reverted! We're working on re-applying the changes, however. Until then, this should again be an issue.

**Comment by IlyaBizyaev** [comment]
Has it been re-applied? Seems to still be working as of 2.11.32.
