### ISSUE TITLE
Lost in Biometric Hell

### ISSUE THREAD

**Issue by CandaceSoVan** [laurent22/joplin#8133]
## Environment

Joplin version: 12.10.5 (inferred since I cannot open the app to check)
Platform: iPad Pro 12.9", Gen 3
OS specifics: iPadOS 16.4.1 (a)

## Steps to reproduce

1. I went to open app. A pop-up appeared that asked if I wanted to use biometrics to authenticate (odd, because I have never used anything to secure my Joplin data)
2. Half-asleep, I clicked okay.
3. App attempted to use my face for authentication, which cannot work because case covers camera. So face ID failed. Choices: Retry or Cancel. At one point it offered using a password, but when I clicked on that it said that wasn't an option (?!). There now appears to be no way for me to access or use the app on this device.

## Describe what you expected to happen

I expected to have some other way to get into the damned app. I didn't realize that clicking okay was a permanent lockout.

## Logfile

I cannot get into the app at all, and so there is no way for me to get a log file to send you.

**Comment by laurent22** [comment]
Maybe try this:

- Remove the case from your phone
- Restart your phone to be sure
- Start Joplin, and let the authentification work
- Go into setting and disable Biometrics Authentication (it's somewhere at the top)

The newer versions have a much better workflow for biometics, which would have prevented what happened in your case
