### ISSUE TITLE
android Fingerprint lock cannot be shut down

### ISSUE THREAD

**Issue by freezuike** [laurent22/joplin#8134]
## Environment

Joplin version: Joplin 2.11.4
Platform:  Android
OS specifics: 

## Steps to reproduce

1.  Unable to save after closing the fingerprint lock
2. Once again into the still is locked
3.

**Comment by laurent22** [comment]
I can't make sense of any of this. Please provide screenshots or explain further

**Comment by freezuike** [comment]
https://user-images.githubusercontent.com/105642498/236461710-ef0d32f9-73f8-4be4-9977-7bd09c6d954e.mp4

**Comment by laurent22** [comment]
I believe this has been fixed in latest pre-releases
