### ISSUE TITLE
Leaving the Joplin desktop on Windows closes my browser.

### ISSUE THREAD

**Issue by birrellwalsh** [laurent22/joplin#8135]
👉 Please follow one of these issue templates:
- https://github.com/laurent22/joplin/issues/new/choose

⚠️
The GitHub issue tracker is for **bugs** and **security issues** ONLY. For feature requests and support, please use the forum:
https://discourse.joplinapp.org/
⚠️

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by birrellwalsh** [comment]
Thanks for not helping.

**Comment by Daeraxa** [comment]
Help with what? You created an issue with a blank template. Your other issue is still open.
You also didn't add any log files to your other issue (#8136) as mentioned in the template you completed.

**Comment by birrellwalsh** [comment]
I have no idea.  New to Joplin, not particularly familiar with github.  I
am just trying to get in and out of Joplin without Vivaldi closing.

Thanks for what must be an unpaid job.  Those are hard, and I appreciate
you doing it.
