### ISSUE TITLE
Leaving my desktop Joplin also closes my browser

### ISSUE THREAD

**Issue by birrellwalsh** [laurent22/joplin#8136]
After bringing in something to Joplin with the clipper, when I leave Joplin, my browser also closes.  It is the browser Vivaldi, based on Chromium, most current version.

## Environment

Joplin version:  2.9.17
Platform: Windows 10
OS specifics: 

## Steps to reproduce

1. Clip something to Joplin with the clipper
2. Open the note on desktop Joplin as you are invited to do
3. leave Joplin
4. Joplin stays open, but Vivaldi closes.

## Describe what you expected to happen

I expected to go to the broswer

**Comment by laurent22** [comment]
Maybe something to report to Vivaldi. We don't explicitly support this browser and it had problems in the past.

Is there any error or warning in the log when you close the app? https://joplinapp.org/debugging
