### ISSUE TITLE
After version 2.11.5 of Android

### ISSUE THREAD

**Issue by freezuike** [laurent22/joplin#8144]
## Environment

Joplin version: 2.11.6...
Platform: android
OS specifics: HarmonyOS3.0

## Steps to reproduce

1. After version 2.11.5 of Android, I can't open it at all. I'm not sure if it's a problem with my phone or the program. After the installation is completed, I will flash back when I open it. I've tried all the subsequent versions, regardless of whether they come with "vosk" or not

**Comment by laurent22** [comment]
To narrow it down please install the regular (non-vosk) version. We need to see the low level debug log to understand what's happening. Could you please do as follow?

- Start the app and write down the **exact time** (to the second). We need this otherwise it's impossible to find something in the log
- Create a debug log https://joplinapp.org/debugging and please let us know the time

By the way, what version do you normally install? Was that the 32-bit one? Because it's no longer available (because I assume it's no longer needed)

**Comment by freezuike** [comment]
1：I have been installing a 64-bit program all along. Sorry, I cannot provide the log because it did not start at all and it flashed by
2：The non (vock) version has also been installed, which is the same issue

**Comment by laurent22** [comment]
I mean what we call the "low-level log" there: https://joplinapp.org/debugging/#creating-a-low-level-bug-report-on-android This you can create it

**Comment by freezuike** [comment]
> 我的意思是我们在那里所说的“低级日志”：https://joplinapp.org/debugging/#creating-a-low-level-bug-report-on-android 你可以创建它

[bugreport-COL-AL10-HUAWEICOL-AL10-2023-05-09-00-05-24.zip](https://github.com/laurent22/joplin/files/11422807/bugreport-COL-AL10-HUAWEICOL-AL10-2023-05-09-00-05-24.zip)
[bugreport-COL-AL10-HUAWEICOL-AL10-2023-05-08-23-58-25.zip](https://github.com/laurent22/joplin/files/11422835/bugreport-COL-AL10-HUAWEICOL-AL10-2023-05-08-23-58-25.zip)
I'm not sure if this is the correct thing, but after following the steps, this file appears

**Comment by laurent22** [comment]
Thank you for the log, although unfortunately that seems hard to fix:

```
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: FATAL EXCEPTION: main
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: Process: net.cozic.joplin, PID: 26027
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/net.cozic.joplin/lib-main flags = 1]
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/net.cozic.joplin-8J5WOvzx3FbHERZb7-uziw==/lib/arm64 flags = 0]
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	Native lib dir: /data/app/net.cozic.joplin-8J5WOvzx3FbHERZb7-uziw==/lib/arm64
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime:  result: 0
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1127)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:943)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:855)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:802)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:772)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:25)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:19)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:23)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:393)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:343)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:96)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at net.cozic.joplin.MainApplication.onCreate(MainApplication.java:92)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7601)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at android.app.ActivityThread.access$2600(ActivityThread.java:259)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2440)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8673)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
05-08 20:21:23.734 10352 26027 26027 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

I will investigate and let you know if I find a fix

**Comment by laurent22** [comment]
Could you try the latest version to see if it's any better? https://github.com/laurent22/joplin-android/releases/tag/android-v2.11.11

**Comment by freezuike** [comment]
> 你能试试最新版本，看看它是否更好吗？https://github.com/laurent22/joplin-android/releases/tag/android-v2.11.11

It's still the same situation

**Comment by laurent22** [comment]
About this version? https://github.com/laurent22/joplin-android/releases/tag/android-v2.11.12

I doubt it will make a difference but if you could check and let me know anyway

**Comment by freezuike** [comment]
Still unable to start, flashing by

**Comment by laurent22** [comment]
Hmm, that's unfortunate. I can't replicate it, and the error doesn't make much sense. On your device it's trying to load a file that it's not supposed to load since the feature is disabled. Or maybe I can try to enable it again for testing.

**Comment by freezuike** [comment]
I tested 2.11.13 and this version can be opened normally

**Comment by laurent22** [comment]
Oh well, that's brilliant, I forgot to ask you to test. Ok so it seems we need to have Hermes enabled now for the app to work on all devices
