### ISSUE TITLE
You go quieter - you will be farther. ))

### ISSUE THREAD

**Issue by igorog** [laurent22/joplin#8147]
Joplin portable starts almost 9!!! seconds (my Windows starts faster). At the same time, the laptop fan spins like crazy and the RAM eats up almost 1 GB. It's some kind of monster, quite simply. Disk NVME, Intel 12 generation and 32 MB of RAM. Friends, don't you think that something is not normal in this kingdom? ((
PS: no additional plugins are installed, synchronization is disabled.

**Comment by laurent22** [comment]
Could you take these 9 seconds, while Joplin is starting, to fill up the issue template?
