### ISSUE TITLE
Unable to update Joplin on Windows to 2.10.17

### ISSUE THREAD

**Issue by mikebabb** [laurent22/joplin#8148]
On trying to upgrade to Joplin 2.10.17 on Windows 11, I get the following error message:

>Joplin cannot be closed. 
>Please close it manually and click Retry to continue.

Joplin is not running. This issue occurs even after a reboot, when Joplin has not run in the current session.

## Environment

Joplin version: 2.9.17
Platform: Windows 11
OS specifics: 

## Steps to reproduce

1. Download `Joplin-Setup-2.10.17.exe`
2. Try to install it
3. Error message shows

## Describe what you expected to happen

The upgrade process to complete successfully.

**Comment by slate17** [comment]
i have the same issue.

**Comment by Daeraxa** [comment]
Same as https://github.com/laurent22/joplin/issues/8149, closed in https://github.com/laurent22/joplin/commit/3adfa574c0264f68f4c33c4133e734fb8b027c34
