### ISSUE TITLE
Search results note titles are shown in lowercase

### ISSUE THREAD

**Issue by euoia** [laurent22/joplin#8150]
When searching for notes using Cmd-P the note titles are shown in lowercase.

I realise the search is possibly not case sensitive - I think that is sensible (although perhaps consider supporting "smart case", i.e. case insensitive except when the pattern contains an uppercase letter). I think the results should still show in their original case, however.

## Environment

Joplin version:  2.10.17
Platform: Mac OS
OS specifics: Ventura 13.3.1

## Steps to reproduce

1. Create some notes with uppercase characters in the titles
2. Search for the notes using Cmd-P
3. Observe that the results window finds the notes, but displays the titles in lowercase

## Describe what you expected to happen

The results window shows the notes with their original case preserved.1

**Comment by Hachemdr** [comment]
I reproduced this bug. I would like to solve it.

**Comment by euoia** [comment]
This is still an issue.

I am interested in fixing this but I would like a steer from the developers (@laurent22 perhaps?) on the best approach.

The root of this issue is that the results are shown based on the values stored in `notes_normalized`.

I see two possible approaches to fix:
1. Store the original title as well as the normalized title in `notes_normalized`, and search based on the normalized title but display the original title. Presumably this would require a schema change, and also a rebuild of the database as part of the release.
2. For each result in the list, fetch the note from the database and show the note's title.

Or maybe there is another way?

I am happy to submit a PR, just would like an idea on which approach to use.

**Comment by laurent22** [comment]
Option 2 seems to make more sense. We wouldn't want a schema change for this unless there's no other options
