### ISSUE TITLE
Buttons are blue from latest update and inconsistent with Dracula theme

### ISSUE THREAD

**Issue by hynow** [laurent22/joplin#8155]
## Environment

Joplin version: 2.10.17 (portable)
Platform: Windows
OS specifics: Version 10, 64 bit

## Steps to reproduce

The new "New note" and "New to-do" buttons are blue and inconsistent with the Dracula theme.

Can these be made the same subtle purple used in the Options menu (used in sidebar text like "General", "Synchronization", "Appearance", etc.)?

I had very carefully tried to remove all traces of blue.  The latest update also makes them stand out a lot.

**Comment by laurent22** [comment]
Any chance you could create a pull request to change this? What colour should it be anyway?

**Comment by Daeraxa** [comment]
Just to mention this isn't since the update, the colours haven't actually changed, at least since 2.8.

2.8
![image](https://github.com/laurent22/joplin/assets/58074586/0a4444b5-039a-4e84-a18d-faf77d69b02f)

2.11
![image](https://github.com/laurent22/joplin/assets/58074586/eb465918-7158-49d3-8fc9-5f0af7f993a7)

It is the same colour as applied to the other buttons like in the config menus (#789FE9).

**Comment by hynow** [comment]
Oh you're right. I think it was some settings on one of the monitors I was using at work with the old buttons that threw me off.  I think the increase in button size made me notice it yesterday on a different monitor.

Is it possible to change this using userchrome file?

I am pretty unskilled with this stuff and wouldn't know how to create a pull request that modifies it.  As a default for all themes, I would have chosen grey.  I can understand using colour to make a button stand out on something like a shopping cart checkout, etc. but creating a new note or to-do is one of the most used buttons that people will easily find.  It is pretty noticeable in peripheral vision, whereas I would prefer it to be as unnoticeable as possible.

**Comment by shubhadeepMH** [comment]
Hey can i work on this ?

**Comment by hynow** [comment]
Oh, hey I just opened version 2.9.17 on one of my laptops.  This is with Dracula and the "macOS theme" with Icon family "Phosphor" and Accent color "Graphite".  

![image](https://github.com/laurent22/joplin/assets/74511445/fdb310be-f5ac-4c05-89bd-3af0e87bb266)
