### ISSUE TITLE
Harmony OS can not connect

### ISSUE THREAD

**Issue by caeser2** [laurent22/joplin#8157]
In Harmony OS, client can not connect joplin server，and webdav，and other，log is:

TypeError:Network request faild
index.android.bundle.108:8201
index.android.bundle.85:1257
....

**Comment by freezuike** [comment]
The following WebDAV hosts are not supported[🔗](https://joplinapp.org/faq/#the-following-webdav-hosts-are-not-supported)
Jianguoyun (see [Github issue](https://github.com/laurent22/joplin/issues/4294))
pCloud (see [Forum thread](https://discourse.joplinapp.org/t/feature-request-pcloud-synchronisation/3530/51))

joplin server我的鸿蒙可以

**Comment by caeser2** [comment]
> 

我用的是2.9.8版本，您用的是哪个版本？我去试试。
有个现象是，如果我故意修改一点点joplin server需要验证的那个地址串，客户端这边就能得到服务器返回的访问串不匹配的提示，说明网络是通的，但用正确的信息就提示Network request faild，webdav也是相同的反馈，无论填入什么信息。而同样的信息换成另外一部安卓手机就没问题。

**Comment by freezuike** [comment]
现在最新测试版2.11.13    或者2.10.8   -    2.11.4都可以，我基本都试过，2.11.6- 2.11.12就不用试了，鸿蒙闪退

**Comment by freezuike** [comment]
我测试了一下，域名错误，或者没网显示Network request failedd

**Comment by caeser2** [comment]
> 我测试了一下，域名错误，或者没网显示Network request failedd

我尝试了googleplay上的2.10.8，还是同样的问题，可能是我手机鸿蒙的版本比较低吧，2.0.0.230，已经不更新了，唉

**Comment by freezuike** [comment]
https://zuike-joplin-northflank.zuike.cf

账号  test@gmail.com

密码  test@gmail.com
你测试一下

**Comment by caeser2** [comment]
> 
连这个服务很神奇的成功了，为啥我本地架设的不行呢，我本地的服务是git上2.10.9的版本，其他pc，手机访问都没问题，就这个鸿蒙不行

**Comment by freezuike** [comment]
其他设备可以用，那就不知道了，我先删除了
