### ISSUE TITLE
Webdav Sync with cyrus-imap httpd fails

### ISSUE THREAD

**Issue by dekeonus** [laurent22/joplin#816]
### Operating system
- Android

### Application
- Mobile

### Server
Self hosted Cyrus Imap 3.0.5 on Gentoo Linux x86

* Used WinSCP to create a "Joplin" folder on the webdav server. 
* Configured Joplin (android) for my self hosted cyrus-imap webdav server, "check synchronisation configuration" failed. Tried creating a default notebook and a test note 'check sync config' still failed as did the sync it's self. 
* After several tries the 'check sync config' was returning 403 not authorised responses. Joplin (android) stayed emitting the 403 unauthorised even after device reboot. 
* Cleared the application, realised too late that the debug log was in the app data directory and lost the results from the above testing. 
* Re-configured the clean Joplin with the same settings. 

log output from Joplin (android)
```
09-25T13:33:09,20,"""Error: MKCOL .sync/: Unknown error 1 (Exception 403) (403): <?xml version="1.0" encoding="utf-8"?>
<D:error xmlns:D="DAV:"><D:resource-must-be-null/></D:error>

Code: 403
```
log output from cyrus-imap server
```
Sep 25 13:22:57 <serverName> cyrus_imap/https[20361]: inittls: Loading hard-coded DH parameters
Sep 25 13:22:57 <serverName> cyrus_imap/https[20361]: starttls: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits new) no authentication; application protocol = h2
Sep 25 13:22:57 <serverName> cyrus_imap/https[20361]: login: [<android_ipv4>] <userName> Basic+TLS User logged in SESSIONID=<cyrus_imap-20361-1537845772-1-17571817764775926263>
Sep 25 13:22:57 <serverName> cyrus_imap/https[20361]: [<android_ipv4>] as "<userName>" with "okhttp/3.6.0"; "PROPFIND /dav/drive/user/<userName>/Joplin/ HTTP/2" (if-none-match=JoplinIgnore-53077; depth=0) => "HTTP/2 415 Unsupported Media Type" (error=This method requires an XML body
)
Sep 25 13:32:50 <serverName> cyrus_imap/https[21525]: inittls: Loading hard-coded DH parameters
Sep 25 13:32:51 <serverName> cyrus_imap/https[21525]: starttls: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits new) no authentication; application protocol = h2
Sep 25 13:32:51 <serverName> cyrus_imap/https[21525]: login: [<android_ipv4>] <userName> Basic+TLS User logged in SESSIONID=<cyrus_imap-21525-1537846365-1-18311394746140815914>
Sep 25 13:32:51 <serverName> cyrus_imap/https[21525]: [<android_ipv4>] as "<userName>" with "okhttp/3.6.0"; "MKCOL /dav/drive/user/<userName>/Joplin/.sync/ HTTP/2" (if-none-match=JoplinIgnore-24588) => "HTTP/2 403 Forbidden"
Sep 25 13:32:55 <serverName> cyrus_imap/https[21525]: login: [<android_ipv4>] <userName> Basic+TLS User logged in SESSIONID=<cyrus_imap-21525-1537846365-1-18311394746140815914>
Sep 25 13:32:55 <serverName> cyrus_imap/https[21525]: [<android_ipv4>] as "<userName>" with "okhttp/3.6.0"; "MKCOL /dav/drive/user/<userName>/Joplin/.sync/ HTTP/2" (if-none-match=JoplinIgnore-69997) => "HTTP/2 403 Forbidden"
Sep 25 13:33:02 <serverName> cyrus_imap/https[21525]: login: [<android_ipv4>] <userName> Basic+TLS User logged in SESSIONID=<cyrus_imap-21525-1537846365-1-18311394746140815914>
Sep 25 13:33:02 <serverName> cyrus_imap/https[21525]: [<android_ipv4>] as "<userName>" with "okhttp/3.6.0"; "MKCOL /dav/drive/user/<userName>/Joplin/.sync/ HTTP/2" (if-none-match=JoplinIgnore-74703) => "HTTP/2 403 Forbidden"
Sep 25 13:33:12 <serverName> cyrus_imap/https[21525]: login: [<android_ipv4>] <userName> Basic+TLS User logged in SESSIONID=<cyrus_imap-21525-1537846365-1-18311394746140815914>
Sep 25 13:33:12 <serverName> cyrus_imap/https[21525]: [<android_ipv4>] as "<userName>" with "okhttp/3.6.0"; "MKCOL /dav/drive/user/<userName>/Joplin/.sync/ HTTP/2" (if-none-match=JoplinIgnore-96689) => "HTTP/2 403 Forbidden"
```
As mentioned the Joplin folder / collection was created with a 3rd party application. The `/Joplin/.sync` and `/Joplin/.resource/` collections were successfully created by Joplin (android) on the previous failed configuration attempt. Sync did not and does not occur and 'check sync config' fails. I have confirmed the .sync and .resource exist both on the server's filesystem and with WinSCP

[syncReport-1537846521543.txt](https://github.com/laurent22/joplin/files/2413728/syncReport-1537846521543.txt)

**Comment by laurent22** [comment]
Is WebDAV supported on it?

**Comment by dekeonus** [comment]
Yes the component that provides caldav and carddav also supports generic webdav as well. cyrus-imapd httpd is the backend for fastmail's cal/card/web-dav (afaik they contributed the *dav code to the cyrus project)

**Comment by laurent22** [comment]
Any chance you could create a test user so that I can try to replicate the bug? If so, you can send the credentials at https://github.com/laurent22/joplin/blob/master/Assets/Adresse.png
