### ISSUE TITLE
Syncing down from PC (x 2) and iPhone app

### ISSUE THREAD

**Issue by TimFGMorgan** [laurent22/joplin#8171]
I click synchronise. Synchronisation fails.

I get this:

![image](https://github.com/laurent22/joplin/assets/111677696/17981d25-42dc-4b7f-9c90-7bad6139d50b)

## Environment

Joplin version:

Joplin 2.10.18 (prod, win32)

Client ID: bb72a60f95004eb8adcd4aacb599b5e2
Sync Version: 3
Profile Version: 42
Keychain Supported: Yes

Revision: c67f5fa

Victor: 1.0.0

## Additional point

Published files at joplinusercontent.com are also not accessible.

Error:

502 Bad Gateway
nginx/1.18.0 (Ubuntu)

## Further point

I wondered whether it was the ISP. I've tested this with different ISPs. Problem the same with all of them.

**Comment by laurent22** [comment]
Sorry about that, this is now fixed. Please see here for more details: https://github.com/laurent22/joplin/issues/8173
