### ISSUE TITLE
Unable to add checkbox using the command palette

### ISSUE THREAD

**Issue by vaz-ar** [laurent22/joplin#8172]
Using the latest Joplin version I am not able to create checkboxes using the command palette any more.
It looks like it is the same kind of issue as described in #5707

## Environment

Joplin version:  Joplin 2.10.18 (prod, win32)
Platform:  Windows
OS specifics: Windows 10

## Steps to reproduce

1. Ctrl+P to open the command palette
2. type in "check"
3. Only result is spell  checker

## Describe what you expected to happen

I expected to have in the list of action the checkbox creation one.

**Comment by Daeraxa** [comment]
I can't replicate this in the current dev branch.

![image](https://github.com/laurent22/joplin/assets/58074586/914461dd-f340-476e-9096-77e579ee88a4)

**Comment by vaz-ar** [comment]
I checked on another Windows computer and I don't have the issue, I will look further on monday on the one where I have had the issue

**Comment by Daeraxa** [comment]
It is worth noting that this command only shows up when in the markdown editor, were you by any chance using the richtext editor on the original machine?

**Comment by vaz-ar** [comment]
Closing this as I am not able to reproduce it any more, I don't know what happened in the first place.

**Comment by sedlund** [comment]
@vaz-ar did you ever figure this out?  I have the same problem.  checkbox bold italic, insert time etc -- are not in the palette anymore for me on windows with 2.13.15 for me.  tried installing the beta same thing.  

nevermind - see: #9855
