### ISSUE TITLE
Error 502 Bad Gateway - AFTER UPDATE

### ISSUE THREAD

**Issue by fintzd** [laurent22/joplin#8173]
## Environment

Joplin version: 2.10.18 (prod, darwin)
Platform: macOS
OS specifics: macOS Monterrey 12.6.5 (21G531)

## Steps to reproduce

1. update Joplin on macOS to latest version (follow all steps)
2. launch the new Joplin application
3. press "Synchronise"

## Describe what you expected to happen

Message should show: Synchronisation Complete (or something like this, not sure of the exact wording)
Message that is shown:

```
Completed: 12/05/2023 15:06 (26s)
Last error: Error: Error 502 Bad Gateway: <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx/1.18.0 (Ubuntu)</center> </body> </html>
```

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/11464308/log.txt)

**Comment by jweile** [comment]
I'm seeing the same error on Ubuntu 20.04, Joplin version 2.10.17.

Although by the looks of it, the problem lies with the Joplin Cloud server. Even navigating to https://joplincloud.com/ shows the same error message:  
```
502 Bad Gateway
nginx/1.18.0 (Ubuntu)
```

**Comment by Jonathanlion** [comment]
I have the same issue now on Windows 11 Home. My error is `Completed: 12/05/2023 15:51 (24s)
Last error: Error: Error 502 Bad Gateway: <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx/1.18.0 (Ubuntu)</center> </body> </html>`

You can find my issue described [here](https://github.com/laurent22/joplin/issues/8174)

**Comment by jweile** [comment]
It's fixed now. According to the forums, the server was down for maintenance: https://discourse.joplinapp.org/t/unable-to-synchronize-via-any-device/30802/4

**Comment by laurent22** [comment]
Yes sorry about that, it should work fine so please try again

**Comment by TimFGMorgan** [comment]
Thank you so much!

**Comment by fintzd** [comment]
> It's fixed now. According to the forums, the server was down for maintenance: https://discourse.joplinapp.org/t/unable-to-synchronize-via-any-device/30802/4



> Yes sorry about that, it should work fine so please try again



> It's fixed now. According to the forums, the server was down for maintenance: https://discourse.joplinapp.org/t/unable-to-synchronize-via-any-device/30802/4

Thank you!

**Comment by fintzd** [comment]
> Yes sorry about that, it should work fine so please try again

Thank you!

**Comment by fintzd** [comment]
> It's fixed now. According to the forums, the server was down for maintenance: https://discourse.joplinapp.org/t/unable-to-synchronize-via-any-device/30802/4

Thank you!
