### ISSUE TITLE
latest flatpak update has bad checksum

### ISSUE THREAD

**Issue by kylrth** [laurent22/joplin#8176]
## Environment

Joplin version: **upgrading from** `2.9.17` to whatever is current (flathub says `2.10.18`)
Platform: Linux
OS specifics: flatpak on Manjaro

## Steps to reproduce

1. have `2.9.17` installed via flatpak
2. run `flatpak update`
3. observe the following output

```
Looking for updates…


        ID                            Branch     Op     Remote      Download
 1. [✗] net.cozic.joplin_desktop      stable     u      flathub     84.9 MB / 204.0 MB

Error: While pulling app/net.cozic.joplin_desktop/x86_64/stable from remote flathub: opcode close: Corrupted file object; checksum expected='4d65aa51719b1d240e703117ee164e74f616f3a089e2b1f26d1fe5e2ee7c2b99' actual='7963aaf8196a20c9362d4ee6429468f77103b0e4d5971dbae35bc5eebc4b83e0'
Updates complete.
error: There were one or more errors
```

## Describe what you expected to happen

a painless upgrade, like normal

## Logfile

I don't feel that this is necessary for this bug.

**Comment by Daeraxa** [comment]
Flatpak isn't an officially supported distribution, any issues should be reported to the flatpak maintainer. https://github.com/flathub/net.cozic.joplin_desktop

**Comment by kylrth** [comment]
thanks
