### ISSUE TITLE
Inability to Display Attached Files or Photos in Joplin Notes.

### ISSUE THREAD

**Issue by TahaNw** [laurent22/joplin#8177]
I would like to report an issue with the Joplin application regarding the display of attached files or photos within notes. When attempting to attach a file or photo to a note, the expected behavior is to see the attached file or photo displayed within the note content. However, instead of the actual image or file, I am presented with a text representation in the following format: ![dog.jpg](:/b1187ae936d6423d802b1938a7989b79). Similarly, for other attached files like report.txt, I see [report.txt](:/2a4f18085f124a2c8ddf9684c3886397).

Steps to Reproduce:

1- Open the Joplin application on Windows.
2- Create a new note.
3- Attempt to attach a file or photo to the note.
4- Observe the note content area where the attached file or photo should be displayed.

Expected Behavior:
The expected behavior is that when attaching files or photos to a note, the actual content of the file or photo should be displayed within the note, providing visual representation and easy access to the attached files.

![Screenshot (53)](https://github.com/laurent22/joplin/assets/105979405/6b2c2f4d-b585-4b78-85dd-888495e079a9)

**Comment by Daeraxa** [comment]
Your picture only shows the markdown editor. Do they not show if you turn on the markdown viewer? (View > Toggle editor layout).

**Comment by dpoulton-github** [comment]
You can also use the "Toggle editor layout" button.

![markdown_layouts](https://github.com/laurent22/joplin/assets/60117449/92f99117-8bb4-45f4-aa5a-2f4714da72cf)
