### ISSUE TITLE
Sorting options ignored in tags view

### ISSUE THREAD

**Issue by hsiktas** [laurent22/joplin#818]
### Operating system

- Windows
- macOS
- Android

### Application

- Desktop
- Mobile

Hello,
as already mentioned in https://discourse.joplin.cozic.net/t/unsorted-notes-in-tag-view/720/3 I can't change the sorting if I view the notes filtered by the tag view. I am seeing this on Windows and macOS with the desktop app and also on Android.

I don't need to do anything special to reproduce this:
- Tag multiple notes with the same tag
- Click on the tag in the sidebar
- Try to change the sorting to "Updated date" or "Title" and nothing changes.

I don't know if this is relevant but my notes where imported from Evernote and initially they started with uppercase letters. After doing
- Right-click on tag
- Rename
- Press "OK" without changing anything

the uppercase letter was turned into lowercase and to maintain uniformity, I applied this to all my tags. Accroding to https://github.com/laurent22/joplin/issues/651 this seems to be intentional behavior but I can't tell if it is relevant to reproduce this. 🤔

**Comment by nr458h** [comment]
Evernote and tag renaming are not necessary to reproduce this issue. 
Same here without evernote import or anything else.
