### ISSUE TITLE
2.10.18 crashes on launch Mac

### ISSUE THREAD

**Issue by rez-photos** [laurent22/joplin#8182]
After installing version ..18 on a Mac Studio running Monterey, this error message showed up:
----
Error: SQLITE_CORRUPT: database disk image is malformed: DELETE FROM table_fields

Error: Error: SQLITE_CORRUPT: database disk image is malformed: DELETE FROM table_fields
at DatabaseDriverNode.sqliteErrorToJsError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database-driver-node.js:23:18)
at JoplinDatabase.sqliteErrorToJsError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:34:30)
at JoplinDatabase.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:135:36)
at Generator.throw (<anonymous>)
at rejected (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:6:65)
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

## Environment

Joplin version: 2.10.18
Platform:  Mac Studio
OS specifics:  MacOS 12.6.5

## Steps to reproduce

1.  Just attempt to run the app. 

## Logfile

I can't get to the app to find the debug report.

I have version 2.10.17 on my Macbook Pro and that works fine.  How to I fix this? I deleted the app and reinstalled it.  No luck.  I installed version 2.10.17 but that won't run because the database is not up to date.

**Comment by laurent22** [comment]
You'll need to restore from backup unfortunately because the db is corrupted and can't reliably be restored

**Comment by rezphotos** [comment]
I think I did that but get the same error message.  (I'm not a coder at all = have little idea what I'm doing here.)  I completely replaced the app.  I used the back up copy, then the copy from my laptop that does work.  No luck at all.  ?

**Comment by laurent22** [comment]
Joplin saves its data to ~/.config/joplin-desktop so you need to restore this particular folder from backup. If you use Time Machine it should have it

**Comment by rezphotos** [comment]
For a test, I installed Joplin on another computer.  I was thinking that the Dropbox data might be what was corrupted.  That worked fine. I've reinstalled Joplin in my desktop multiple times with different methods with no changes in the error messages.  The only difference I can see is my desktop is M1 while the machines Jopin works on are Intel.  But, Joplin did work before I installed 2.10.18.   Completely puzzled.

**Comment by rezphotos** [comment]
restored the folder jopiln-desktop.    It's working again.  Thanks for your help.

**Comment by rezphotos** [comment]
I encountered this same problem again - this time I knew how to fix it.  But I'm wondering if there's some problem either with Mac OS or Joplin, or possibly a user problem?

**Comment by laurent22** [comment]
I assume there isn't. We use the SQLite library, which is known to be robust and fault-tolerant. But if the drive is somehow faulty, then nothing can be done and the db might end up being corrupted.

Another way it can happen is if multiple applications access the database at the same time, but there's a mechanism to ensure that only one instance of the app is running at a time.
