### ISSUE TITLE
Webdav sync resource issue

### ISSUE THREAD

**Issue by venetin** [laurent22/joplin#8185]
Hello, there is a strange issue with Joplin on Android. Actually I experience this issue since the first day I started to use Joplin. When a note which contains a file e.g picture and this note is created in the mobile app and then synced via webdav there are sync issue when this note is synced back on another mobile device. First  I observed that the pictures of the "Wellcome" notes are doubled and trippled in the webdav storage location. It seems that every new device is uploading it's own set of pictures for the default notes. Probably they have different random UUIDs. I decided to delete the default notes because I don't need them anyway. The notes were deleted but the pictures remain in the wedbav store location. I deleted them manualy and forgot about this. Since I was using joplin only for text there was no issue for me. Recently I decided to move all my notes from any other software to Joplin. I started to create some notes with attachments and I observer probably the same issue again. When a note is created on a mobile device and synced to webdav and then synced back to another mobile device a yellow banner appear on the second device which states that the resources can't be downloaded. But the resources are actually downloaded most of the times. When I sync this note to the desktop app there are no errors and everything seems OK. But on every new mobile device there is an error which can't be hidden. Only the mobile device where the note is created and the desktop app are not affected. Even if I delete the note from the source device the banner remains on the taged devices. I observed that even tough the note is deleted the target devices continue to try to download the resource. And the resource is actually not deleted and it remains in the webdav store. The only workaround is manually delete the resource.
So there are two or peobably 3 issues here:
1. There is an error on the target mobile devices when there are notes with attachments created on another device.
2. When a note with attachment is deleted and the deletion is synced, the attachment is not deleted and remains in the webdav storage,
3. When the resource folder is deleted, Joplin is not able to re-create it and the sync is not possible.

## Environment

Joplin version: 2.11.13 F-Droid build
Platform: Android
OS specifics: v10 (Both EMUI 12 and HarmonyOS2)

## Steps to reproduce

1. Create a note with picture in the mobile app.
2. Sync with webdav
3. Sync the note on another mobile device
4. An error will appear on the targed mobile device
5. Delete the note via any of the devices
6. The picture will remain into the sync location (webdav)
7. The error on the target mobile device will disapear only when the picture is deleted manualy from the sync location 

## Describe what you expected to happen
I expect to be able to cross sync notes with attachments with no issue.

**Comment by venetin** [comment]
[syncReport-1684064367584.txt](https://github.com/laurent22/joplin/files/11471793/syncReport-1684064367584.txt)
![Screenshot_20230514_143113_net cozic joplin](https://github.com/laurent22/joplin/assets/45770812/39a12fa5-2990-4327-bc43-32098c1a0b66)

**Comment by laurent22** [comment]
For the "Download interrupted" error you can try the latest version, which may have a fix for it: https://github.com/laurent22/joplin-android/releases/tag/android-v2.11.22

I had this issue too for some resources and this version fixed it

**Comment by venetin** [comment]
Thank you very much for the fast response. I will wait for this version to appear in F-droid and after I test it I will come back with a feedback. I will stick with the F-droid build because I need to update all devices to perform proper tests.
But what about the other issues? Is there a clue in the logs why Joplin can't delete resources when a note is deleted?
And what about the resource folder creation issue? Is this folder meant to be created only by the desktop app? This way a mobile only sync is not possible. Or the user must know to create the folder manualy.

**Comment by everdred** [comment]
> For the "Download interrupted" error you can try the latest version, which may have a fix for it: 

I was having this happen with the latest F-Droid version, and can confirm that this version fixes it.

**Comment by venetin** [comment]
Hello,
It seems that there is another issue now on 2.11.22. Please see the screenshot.
![Screenshot_20230518_200732_net cozic joplin](https://github.com/laurent22/joplin/assets/45770812/276e2eb3-0575-4994-9e46-12668b960eab)
