### ISSUE TITLE
Abililty to create subtasks (and drag and drop to support it)

### ISSUE THREAD

**Issue by DozyDolphin** [laurent22/joplin#819]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

### Feature request 

I would like to request the ability to create subtasks. This would support a GTD workflow where the top task would be the project, and all subtasks would be tasks to execute to see that project to completion.

* Ability to drag and drop tasks onto another task to make it a subtask
* Ability to create tasks directly as subtasks - maybe by having a task highlighted when creating a new task (although this conflicts with the existing behaviour on desktop where the first note/task is always highlighted when opening a notebook)

**Comment by nr458h** [comment]
I like the idea of linking a note or a task by dragging on the other note/task!

But do you think that a forecast that the task is done or note connected with the link (requested in #736) would do the job?

In my opinion that would make subtasks available which also can have a alarm, tags ... but also be visible among all other tasks.

What do you think?

**Comment by laurent22** [comment]
Wouldn't all this be more or less possible with sub-notebooks? Create one main notebook for the project and sub-notebooks for tasks and sub-tasks. 

It wouldn't be as convenient as a built-in solution but it should do the job.

**Comment by nr458h** [comment]
Totaly agree!
I think a great workflow would be to be able to link a note/task to another one by drag and drop.
And for tasks to be able to see from the link if the task is closed.

**Comment by nr458h** [comment]
@dolzydolphin I created a new FR for the drag and drop support, because I think this is a nice feature independent from the subtask-feature

**Comment by DozyDolphin** [comment]
@nr458h I'm not entirely sure I understand the whole linking...

* How would you be able to see the linked notes/tasks - in the description? 
* Would you be able to see all tasks/notes that are linked to a specific task/note?

@laurent22 That might actually work. Projects in GTD is not the normal scale of projects - it is anything that takes more than one actionable step to complete. So a Project notebook with subnotebook projects with tasks in them could do the trick. 

You can consider this solved. I hope it is okay if I create a Feature Request/Discussion regarding some wished for the mobile client? Instead of creating multiple from the start and finding out there is an easy solution.

**Comment by nr458h** [comment]
![](https://i.imgur.com/K3BReCB.png)

**Comment by nr458h** [comment]
The different tests are markdown links to other tasks. And my idea would be to also have the checkbox linked.
For example if I check Test 2 than, when I open the task it is marked as closed.

**Comment by DozyDolphin** [comment]
@nr458h That looks amazing :-)
