### ISSUE TITLE
Sync from windows app doesn't work anymore

### ISSUE THREAD

**Issue by MarcS1975** [laurent22/joplin#8191]
I am syncing Joplin from several devices (Android, IOS and Windows PC) to a Nextcloud server
 All worked fine but recently the Joplin Windows App always shows an error message about locked files.
The strange thing is that all other devices sync without problem to the same server

## Environment

Joplin 2.10.18 (prod, win32)
Client ID: 69d4b9b85a3d4302a395933fc9093ee0
Sync Version: 3
Profile Version: 42
Keychain Supported: Yes
Revision: c67f5fa
Note encryption: 1.1.1

Platform: 
OS specifics: Windows 10Pro

## Steps to reproduce

1. launch Joplin app in Windows 
2. click Synchronise
3. Error

![image](https://github.com/laurent22/joplin/assets/52089754/61db86c3-fa98-4840-9104-1622e6f1eda7)

## Describe what you expected to happen
sync finish without error like with my Android app and iOS app

## Logfile
[syncReport-1684101755651.csv](https://github.com/laurent22/joplin/files/11473031/syncReport-1684101755651.csv)

**Comment by laurent22** [comment]
Search for "nextcloud filelocked" for a fix

**Comment by MarcS1975** [comment]
why did you close this. Its obviously not a Nextcloud issue since it works fine with Joplin IOS and Android.
It is a Joplin Windows issue

**Comment by laurent22** [comment]
It's a Nextcloud bug and I closed it because it's been asked dozens of time before and it has nothing to do with Joplin. I've suggested what you can search for, but it's up to you

**Comment by MarcS1975** [comment]
So it's a nextcloud bug that only happens with Joplin and only happens with
one particulat joplin app, not the Joplin Android and not Joplin Ios?

**Comment by laurent22** [comment]
Ok let me google it for you: https://discourse.joplinapp.org/t/if-youre-getting-a-filelocked-error/10947
