### ISSUE TITLE
Allow creating sub-notebooks from the mobile app

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8193]
Long press on a notebook to open a dialog, which will include the option "Create a sub-notebook..." to make it a sub-notebook of the current one. And that will redirect to the existing notebook creation/edition screen.

**Comment by wh201906** [comment]
Is #7980 for this?

**Comment by laurent22** [comment]
Yes that would be it. Weird how I've never noticed this PR, even I thought I looked through all PRs today

**Comment by wh201906** [comment]
Maybe the title is not so intuitive.

**Comment by tessus** [comment]
I remember we had a few PRs about this topic, but unfortunately they were abandoned.

**Comment by PaulS-26** [comment]
The demo video of @jcgurango 's implementation in pull request https://github.com/laurent22/joplin/pull/7980 looks great.

Been waiting for this for a long time, same for https://github.com/laurent22/joplin/pull/7981 (Implement sorting of notes).

Any chance these two can be merged and released soon? Would definitely be a great upgrade to the core features of the mobile client!
