### ISSUE TITLE
Dead area at the end of the Note List

### ISSUE THREAD

**Issue by DimiMp33** [laurent22/joplin#8194]
There is a dead area at the end of the Note List, and it seems to be related to the new New Note/New ToDo buttons design.

## Environment

Joplin version: Joplin 2.10.18 (prod, win32)
Platform: Windows
OS specifics: Windows10 LTSC

## Steps to reproduce

1. Change the background color of the class '.note-list, .sc-fzqNJr'
eg.
```css
.note-list, .sc-fzqNJr {
	background: #222;
}
```
You can see at the end of the Nost List that there is a dead area. If you increase the bottom padding of New Note/New ToDo buttons the dead area goes away (although i don't think that should be the solution).

![DeadArea](https://github.com/laurent22/joplin/assets/97843215/d42bab69-a09f-4537-96df-3473d3985ff8)

## Describe what you expected to happen
There should not be any dead area.

**Comment by personalizedrefrigerator** [comment]
I can confirm this on Linux with no custom CSS.

**Comment by DimiMp33** [comment]
Still an issue in 2.11.11

**Comment by iakoboss7** [comment]
I can confirm this is an issue also on Windows 11 and Joplin 2.11.11

**Comment by personalizedrefrigerator** [comment]
Still an issue.

**Comment by CptMeetKat** [comment]
Looking into this
