### ISSUE TITLE
Copy and paste table rows and columns

### ISSUE THREAD

**Issue by hsandt** [laurent22/joplin#8200]
In the Rich Text Editor (WYSIWYG), when copying and pasting multiple cells of a table, sometimes entire rows/columns, a new table is created with the multiple cells in the last selected cell instead of replacing the cells' content; even if the target selection has the same number of cells as the source copy.

For instance, copying the first row of a table:

| Source | row | 1 | 2 |
|-|-|-|-|
| | | | |
| | | | |

into the second row (assuming we highlight from left to right so the last selected cell is on the right) will give:

| Source | row | 1 | 2 |
|-|-|-|-|
| | | | [Source / row / 1 / 2] |
| | | | |

or, since GitHub Markdown doesn't allow to write a table in a table, see the screenshot below:

![Joplin 2 10 18 - Copy table cells in table creates sub-table](https://github.com/laurent22/joplin/assets/1067772/2016933d-eca4-4e7f-b21f-aeb7fda82849)

This is an issue I also had with OneNote web, and it makes copying table content very hard.

My current workarounds:
a. copy each cell one by one
b. switch to pure Markdown (harder to edit table)
c. select all the cells to copy and use widget menu > Table > Row/Column > Copy Row/Column then Paste Row/Column before/after for each row/column I need to copy. But it copies full rows/columns, it will require extra cleanup work if you only wanted to copy part of them.

## Environment

Joplin version: 2.10.18
Platform: Linux, macOS
OS specifics: for Linux: Ubuntu 22.10 with Unity desktop

## Steps to reproduce

1. Create table with a few rows and columns, and fill a few cells. For example:

| Source | row | 1 | 2 |
|-|-|-|-|
| | | | |
| | | | |

2. Select a partial grid inside the table, such as the first row (4x1 sub-table), and copy the cells (Ctrl+C)
3. Select another partial grid of same size inside the table, such as the second row (also 4x1) and paste (Ctrl+V)

The result is the screenshot attached more above.

You can retry by selecting only one cell in step 3, or highlighting a rectangle of cells, and highlighting in different directions (from right to left, bottom to top): a new table will always be created in the last selected cell.

## Describe what you expected to happen

I expect the copied content to be pasted in each target cell following the same structure (cell-wise copy), at least when the target selection has the same size as the source copy.

With the example above, it would give:

| Source | row | 1 | 2 |
|-|-|-|-|
| Source | row | 1 | 2 |
| | | | |

It would also be convenient if it worked even when the target selection has a different size, as long as there is enough room to paste. We could even insert more rows/columns if needed, but that's something to check with design.

Finally, when the cursor is simply located inside a cell (no multi-cell highlight; we cannot highlight a single cell anyway), then I'm not sure we should absolutely copy table content into neighboring cells: there may be some cases where the user really wants to paste an embedded table inside the table after all. But when user highlights multiple cells, it's very likely they want to paste table content cell-wise.

## Logfile

Can provide if needed, but I'm not sure it's relevant for this kind of "bug" which is a behavioral thing.

**Comment by marph91** [comment]
In the [TinyMCE5 demo](https://www.tiny.cloud/docs/release-notes/release-notes50/#tinymce50demo), copy and paste of table cells works as intended. This might be a starting point to fix it.
