### ISSUE TITLE
Joplin 2.10.18 AND Joplin 2.10.19 do not open after update from 2.10.17

### ISSUE THREAD

**Issue by zUscNezx8RQv8** [laurent22/joplin#8208]
## Environment

Joplin version: 2.10.19
Platform: MacOS 13.3.1 (a)
OS specifics: 

## Steps to reproduce

1. 
2. 
3. 

## Describe what you expected to happen
After upgrade from 2.10.17 version to either 2.10.18 or 2.10.19, Joplin opens as a white screen and does not respond. 
I have to exit it by Force Quit command. 
Debugging tools are not available. 
I've reported this via Joplin forum as well.

**Comment by gorbehnare** [comment]
Hello

I just run into a similar issue in two of my systems. In my case version v2.10.18 works, but after update to 2.10.19 the application fails to open with following errors:
```
- $ flatpak run net.cozic.joplin_desktop
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 21:51:52.637: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:51:52.638: Failed to load module "canberra-gtk-module"
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```
Version 2.10.18 works as expected. 

I am currently using Joplin via flatpak on Ubuntu 23.04 with the default Gnome desktop (both systems are the same).

**Comment by Daeraxa** [comment]
@gorbehnare I believe the original issue was related to plugins - https://discourse.joplinapp.org/t/joplin-2-10-18-does-not-open-after-update-from-2-10-17/30821

We don't support the flatpak version directly, can you check to see if you have the same problem with the appimage?

**Comment by gorbehnare** [comment]
Thanks for quick response. I have not installed any plugins as far as I know (nothing is listed under the settings > plugins). I did not even know there are plugins available. 

The appimage does work. That probably means something is borked in the flatpak version. I suppose I should open an issue with the flathub maintainers here https://github.com/flathub/net.cozic.joplin_desktop ?

**Comment by Daeraxa** [comment]
Yeah, if the appimage is working then I suspect it is an issue on the flatpak so that repo would be the place to do it.

**Comment by gorbehnare** [comment]
Thank you... I generally dislike Appimages, and don't like them just lying around, but if that's the only supported format, then I guess I am stuck with that.
