### ISSUE TITLE
Anchor linking to a Joplin note doesn't work when the note has an image

### ISSUE THREAD

**Issue by annoyedhumanoid** [laurent22/joplin#8209]
## Environment

Joplin version: 2.11.4
Platform: macOS
OS specifics: Ventura 13.3.1 (a)

## Steps to reproduce

1. Create a note with at least the following: (1) an image, (2) some HTML element assigned an id attribute (for example, `<span id="link"> text </span>`), and (3) enough other content to allow the viewport to scroll vertically (I used https://loripsum.net/).
2. Create another note and, in that note, link to the note created in step 1 (right click > Copy Markdown link) and append `#{value of id attribute}` to the link destination (for example, `[Click here](:/add3d841example12ad7091cbcc#link)`).
3. Restart the application and do not yet open the step 1 note (tip: Joplin automatically opens the note listed first in the most recently used folder, so make sure that isn't the step 1 note). Open the step 2 note in the Markdown editor and click the link in the rendered Markdown.

## Describe what you expected to happen

The rendered Markdown view should automatically scroll to the linked element and stay there until the user scrolls. However, when there's an image in the note, the viewport scrolls to the proper position for an instant then reverts back to the top of the page (see attached video). This only happens when the note contains an image, and only reliably on first time being loaded per session, but it seems to randomly happen other times in the same session.

https://github.com/laurent22/joplin/assets/46287328/98fc1dfb-739a-4a57-84ed-77aa425b9a65

## Logfile

The logs are identical for when the viewport scrolls to the proper position vs. when it reverts to the top (see images). The only warning of note is "ItemList: resetting scrollTop to 0. visibleltemCount is negative, scrollTop is positive", but this occurs even when regularly linking (i.e., not anchor linking) to a note _without_ an image.

<img width="500" alt="Screenshot of console when viewport scrolls to proper position" src="https://github.com/laurent22/joplin/assets/46287328/52c65e75-67cf-45ce-a973-fb9c834d056b">
<img width="500" alt="Screenshot of console when viewport reverts to top" src="https://github.com/laurent22/joplin/assets/46287328/79b13e1f-8a08-4aa4-9ae0-db079fb4106e">

[Here are the notes I used to demonstrate the bug.](https://github.com/laurent22/joplin/files/11510575/link.bug.directory.zip) Unzip then import into Joplin via File > Import > RAW - Joplin Export Directory.

**Comment by Wladefant** [comment]
@laurent22 @annoyedhumanoid please reopen this issue and delete the bot. Why would an issue that is not commented on be closed, what is the reasoning behind it?!? 

Either way it is still an issue, when and if I learn the codebase I would be glad to fix that. It works fine with the outline plugin, but when I link from within the same note, nothing happens. When I link from another note, it jumps to the start of the note, but not to the correct anchor.

I am talking about the anchor syntax here: [Joplin Feature Requests / Plugins # note Tabs](:/6715c5565f964b0299a1571ee8ceadde#note-tabs)

This was requested back in 2019 #1490 and there was seemingly some work done there https://github.com/scoroi/joplin/commit/cf77ef01e14389b51077a98fce2f796656cd5e10 but what I can tell is that it is not working ;)
