### ISSUE TITLE
Console.log not showing output for plugin development

### ISSUE THREAD

**Issue by danielb2** [laurent22/joplin#8210]
ref: https://discourse.joplinapp.org/t/console-log-not-showing-output-2-10-19/30809

When running /Applications/Joplin.app/Contents/MacOS/Joplin --env dev I'm not seeing the console log messages.

Development tools and that console shows up still, but not the console that would print console.log messages. The console window doesn't open whereas the devtools console still shows.

## Environment

    Joplin 2.10.19 (dev, darwin)

    Client ID: 14ae02406da64470ac99be3087138b2f
    Sync Version: 3
    Profile Version: 42
    Keychain Supported: Yes

    Revision: 1100ab0

    Publish to Web: 1.0.6

## Steps to reproduce

1. /Applications/Joplin.app/Contents/MacOS/Joplin --env dev

## Describe what you expected to happen

Console window doesn't open. Joplin windows opens fine

## Logfile

_nothing to see here_

**Comment by laurent22** [comment]
It works for me. Isn't it because you need to select the message tab here?

<img width="242" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/614cc97f-11e1-452b-89cb-36cb87fb2eb2">

**Comment by danielb2** [comment]
before there was a  separate window open just for the console logs. now I don't see any output I do

```javascript
joplin.plugins.register({
	onStart: internals.onStart,
});
internals.onStart = async function() {

	console.log(joplin.settings.globalValue("sync.2.path"));
	console.log('daniel');
	await internals.registerCommands();
	// await internals.registerMenu();
	await internals.registerToolbarButtons();
	await internals.registerSettings();

	await internals.initOctokit();

	joplin.settings.onChange(async (event: any) => {
		if (event.keys.indexOf("GithubAuthToken") !== -1) {
			console.log("Github Auth Token changed");
			await internals.initOctokit();
		}
	});
	internals.gistDialog = await joplin.views.dialogs.create('gistDialog');
}
```

but there's no result other than my directory having the same name, the log doesn't show what I'm logging. 

<img width="850" alt="Screen Shot 2023-06-05 at 10 27 05" src="https://github.com/laurent22/joplin/assets/26678/0a9a4216-a72b-4fae-9c99-171bd5d10735">

**Comment by laurent22** [comment]
I don't think the plugin console is supposed to open in this case. But it does if you add the plugin path under Settings => Plugin => Advanced

**Comment by danielb2** [comment]
> I don't think the plugin console is supposed to open in thi
s case. But it does if you add the plugin path under Settings => Plugin => Advanced

I have that for developing my plugin

<img width="401" alt="Screen Shot 2023-06-05 at 11 01 45" src="https://github.com/laurent22/joplin/assets/26678/6d91c273-26aa-47c5-97b1-3b5ddd64b245">

I tried removing the path, restarting, adding, and restarting. still no luck
