### ISSUE TITLE
Incoming shared content logged in plain text

### ISSUE THREAD

**Issue by Terrance** [laurent22/joplin#8211]
This is effectively a regression following the share rework in #7791, originally noted at https://github.com/laurent22/joplin/issues/7170#issuecomment-1445457710.

## Environment

Joplin version: 2.11.22
Platform: Android 12
OS specifics: OnePlus Nord CE, OxygenOS 12.1

## Steps to reproduce

1. Share text content to Joplin
2. Check the log or export a debug report

## Describe what you expected to happen

Debug logs should avoid including sensitive information like the plain text content of notes, to prevent accidental sharing of personal or otherwise private data.  Previously this was the case, though the recent changes to share handling now log the entire content of each share to the log, meaning I need to check through the log and redact anything I don't want to post publicly when reporting other issues.

## Logfile

[syncReport-1684448489476-snip.txt](https://github.com/laurent22/joplin/files/11511938/syncReport-1684448489476-snip.txt)

Note the existence of the shared content in plain text:

```
05-18T23:21:12,30,"root: ""Sharing: handleShareData:", "{"text":"My secret text","resources":[],"title":null,"type":"text/plain"}""
```

**Comment by personalizedrefrigerator** [comment]
I'm re-opening this for now -- #8211 is only a partial fix. We still need to remove any existing sensitive data when sharing/exporting the log.

**Comment by laurent22** [comment]
The mobile version delete log entries older than 7 days, and since the latest version has been published for some time this is not really an issue anymore, so I think we can close
