### ISSUE TITLE
ramdon lost data when using external text editor with joplin

### ISSUE THREAD

**Issue by longforrich** [laurent22/joplin#8217]
using cudaText as the external text editor for joplin to edit a huge lines markdown file will lost data on tail of file

I don't know who is responsible for this issue, so I submitted it on both projects
only the cudaText with joplin will lost data
can download cudaText on https://github.com/Alexey-T/CudaText/releases/tag/1.194.4

## Environment

Joplin version:  2.10.19
Platform: X86-64
OS specifics: win10 22H2

## Steps to reproduce
1. setup cudaText as the external text editor
2. make a new notes
3. copy the [simple.txt](https://github.com/laurent22/joplin/files/11518629/simple.txt) text on attachment to new notes
4. the simple text has 3906 lines
5. edit it with cudaText by 'toggle external editing'
6. type something on tail of text and save it
7. you can see the saved file on c:\user\username\.config\joplin-desktop\edit-xxxxx.md with opening it directly using any editing tool. it has more then 3906 lines,is ok.
8. click 'stop' on joplin to stop 'toggle external editing'
9. click 'toggle external editing' again
10. you can see the lines of text is less then 3906, lost some data on tail of file
11. only occurs after 'toggle external editing' by cudaText with huge lines makedown file(>= 3000 I guess?)
12. use vscode as the external text editor is ok

## Logfile
log.txt
[log.txt](https://github.com/laurent22/joplin/files/11518652/log.txt)
Console
[Console.log](https://github.com/laurent22/joplin/files/11518683/Console.log)

**Comment by longforrich** [comment]
![1](https://github.com/laurent22/joplin/assets/53457069/cdf71f92-7c21-4d9b-874f-b57562c544f0)

**Comment by dariuskramer** [comment]
I have the same problem when using NeoVim on Windows, with far less lines (~50)
