### ISSUE TITLE
Created 2 test profiles to sync - both download the two of them

### ISSUE THREAD

**Issue by NicoleSigaud** [laurent22/joplin#8222]
Hello, 
I use JOPLIN version **2.8.8 Win 32, revision c2a6a13 French language**, on a **Windows7 Full Edition SP1**, and created 17 different profiles for my art classes, all synced to (none), since everything, software included, is stored already inside Dropbox in a root folder called "!!!!!!JOPLIN"

Recently, I created 2 test profiles synced in Dropbox in order to test the Android sync on my tablet later. For some reason, whenever I synced both test profiles in Dropbox (still in my notebook), both synced to both, downloading all notes for test1 and test2 in both of them. I don't know if this is a bug or if the fact that Joplin is already inside Dropbox can create such a strange behavior. From all the 17 profiles I have, I need to sync only 2 of them in my Android tablet (with **Joplin version 2.10.8, database v42**).

**Comment by JackGruber** [comment]
Both profiles use the same synctarget. Therefore, both profiles have the same content. The desired behaviour only works with different Dropbox accounts. For discussions and questions please post in the [forum](https://discourse.joplinapp.org/). Github is for tracking issue.
