### ISSUE TITLE
Error: EROFS: read-only file system, open '/File.pdf'. 

### ISSUE THREAD

**Issue by JackPala** [laurent22/joplin#8224]
## Environment

Joplin version: 2.10.19
Platform: MacOS Apple Silicon
OS specifics: Latest MacOS Stable

## Steps to reproduce

1. Select multiple notes 
2. select export
3. select export as PDF - file browser opens - error opens

## Describe what you expected to happen
Exporting a batch of notes as a PDF

**Comment by JackPala** [comment]
I suspect that it may be write permissions related? Though I am not certain.

**Comment by laurent22** [comment]
I cannot replicate this, so it might indeed be a permission issue. Have a look at `~/.config/joplin-desktop` - permissions should be like this:

<img width="81" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/6e5e4d6e-aeab-4604-8f21-0d357187b9af">
