### ISSUE TITLE
View - show completed to-dos - unreadable

### ISSUE THREAD

**Issue by verityj** [laurent22/joplin#8225]
Menu item View - show completed to-dos displays the checked to-dos in gray font. Unfortunately, there's also a strikethrough through the to-do title, making it hard to read what each to-do says.

## Environment

Joplin version: 2.10.19 (prod, darwin)
Platform: Mac OS 13.3
OS specifics: Joplin for Desktop

## Steps to reproduce

1. View menu
2. Show completed to-dos (selected)
3. Try to quickly read any of the titles of completed to-dos

## Describe what you expected to happen

Completed to-dos should not have strikethrough lines. They are readable on iOS, no strikethrough - Desktop version should align.

## Logfile

N/A

**Comment by usmailaabdoul** [comment]
@verityj can i pick this up?

**Comment by verityj** [comment]
Please do!

**Comment by martiz** [comment]
I'm confused at this... I've no issues of having completed to-do's being struck.
Is there a way to have this as an additional option?

**Comment by verityj** [comment]
> I'm confused at this... I've no issues of having completed to-do's being struck. Is there a way to have this as an additional option?

Really? Readability of crossed out text is markedly lower than non crossed out. Making it gray is perfect, but to review and let's say unmark something as done kinda requires reading it, and easier is better than trying to decipher line items because of overlapping cross outs... That's my perspective, so I'm asking. Mobile app is fine, desktop - not so much.
