### ISSUE TITLE
Joplin UI does not appear to render unless ~/.config/Joplin is deleted

### ISSUE THREAD

**Issue by BeenEncoded** [laurent22/joplin#8226]
## Issue
Joplin may or may not appear to open.  After starting the program, it never renders the GUI.  Issue is intermittent, and may not happen but tends to happen a good 80% of attempts.  Deleting `~/.config/Joplin` always resolves the issue.  `~/.config/Joplin` is recreated after starting Joplin again.

## Environment

Joplin version: 2.10.19
Platform: Fedora 39 (with the Gnome Desktop Environment)
```
OS: Fedora Linux 38 (Workstation Edition) x86_64 
Host: Laptop (12th Gen Intel Core) A4 
Kernel: 6.2.15-300.fc38.x86_64 
Package Manager: rpm/dnf
Shell: bash 5.2.15 
DE: GNOME 44.1
WM: Mutter
```

Joplin was installed via the `Joplin_install_and_update.sh` script from the joplin home page.  The app is being run from `~/.joplin/Joplin.AppImage` via the Gnome Desktop Environment (as a pinned app) when the issue occurs, but the issue also occurs when run directly from the terminal in the app's directory.

## Steps to reproduce
1. Attempt to open Joplin
2. If the GUI does not appear within 10-20 seconds, kill joplin processes with signal SIGABRT (`sudo kill -6 $(pgrep joplin)`)
3. remove the `~/.config/Joplin` directory and try again

## Expected Result:
If joplin has not yet been opened during the current session, startup time should be typically within 30 seconds.

## Logfile
The attatched logfile captures 3 attempts to open the program.  The first 2 attempts the GUI doesn't render.  I annotated the log to show when I intervened.

Unfortunately I was unable to capture a debug log.  The thing keeps working whenever I pass `--log-level debug` for some reason.  I will continue to try capturing a debug log though.

[clipped joplin log.log](https://github.com/laurent22/joplin/files/11533871/clipped.joplin.log.log)

If any additional information is required, please let me know.  I will do what I can.

**Comment by ScriptInfra** [comment]
Possibly consider launching in KDE?

**Comment by laurent22** [comment]
what plugins do you use?

**Comment by BeenEncoded** [comment]
> what plugins do you use?

At the moment the installation is vanilla -- no plugins.

**Comment by BeenEncoded** [comment]
I was able to capture the issue with `--log-level debug' passed.  Here are the logs from that.
[joplin debug log.log](https://github.com/laurent22/joplin/files/11577071/joplin.debug.log.log)

The first 3 times it didn't work.  Then I killed joplin.  I didn't do anything after that except restart it, and then it came up.

I think it might have somthing to do with my config... I'll be resetting that tomorrow (my plate is rather full today).

**Comment by rio-codes** [comment]
Can you use `journalctl` or GNOME Logs to capture what is happening system-wide? Maybe it is a GNOME or Mutter issue. https://docs.fedoraproject.org/en-US/quick-docs/viewing-logs/

**Comment by BeenEncoded** [comment]
Deleting my `~/.config/joplin-desktop` directory, resyncing and setting everything back up manually seems to have fixed it, but on initial open the issue still occurs.  Just closing the UI and reopening it resolves it.

Here are the journalCTL logs for it.
[joplin journalctl logs.log](https://github.com/laurent22/joplin/files/11616366/joplin.journalctl.logs.log)

**Comment by rio-codes** [comment]
I looked up the error you are getting in journalctl, it seems like there is an issue with vsync in Wayland related to hardware acceleration. Here's the Electron bug: https://github.com/electron/electron/issues/32760

I guess it can be fixed by adding `app.disableHardwareAcceleration()`  to the code but I'm not sure if that would break anything else. I can take a look at it.

**Comment by rio-codes** [comment]
I'm wondering if it would be better to add a setting to the Options menu to disable/enable hardware acceleration and leave it disabled by default. I have seen other apps do the same thing. @laurent22 this seems like a major change either way (affecting entire GUI), do you think this is something I should work on as a new contributor?

**Comment by Daeraxa** [comment]
Out of interest does it work if you pass `--no-sandbox` when starting it?
