### ISSUE TITLE
"Open newly created note" also opens blank browser tab

### ISSUE THREAD

**Issue by truthsword** [laurent22/joplin#8233]
## Environment

Joplin version: Joplin 2.10.19 (prod, win32)

Client ID: f97e5c660ed34a03b0d2e95051855674
Sync Version: 3
Profile Version: 42
Keychain Supported: Yes

Revision: 1100ab0

Combine notes: 1.0.1
Conflict Resolution: 1.2.3
Simple Backup: 1.2.2
Platform: Win 10 Home
OS specifics: Extension 2.11.2

## Steps to reproduce

1. Clip simplified page
2. Open newly created note
3. While the Joplin app reveals the new note, the browser (Firefox) opens a new blank tab with the URL link and tab name:
![](https://i.imgur.com/Vid99NV.png)

## Describe what you expected to happen
No new blank empty browser tab

## Logfile
Have no idea where the extension stores this

**Comment by truthsword** [comment]
> If you require support or are **requesting an enhancement or feature**

I'm reporting a nuisance bug. Last time I did this on the forum, I was directed here.

**Comment by truthsword** [comment]
Surely I'm not alone here?

Jul 24, 2023 12:02:51 PM github-actions[bot] ***@***.***>:

**Comment by personalizedrefrigerator** [comment]
It seems to work in Chromium (Ubuntu 23.04). (Ctrl+Clicking, however, opens a nonfunctional version of the webclipper dialog in a new tab).

**Comment by truthsword** [comment]
Seems like there is no interest here, or at the forum,  so I will quietly slink away.

Aug 24, 2023 12:02:55 PM github-actions[bot] ***@***.***>:
