### ISSUE TITLE
Changing profile shuts down Joplin

### ISSUE THREAD

**Issue by Key-Snapper** [laurent22/joplin#8236]
## Environment

Joplin version: Joplin 2. 10. 19 (prod, linux) as appimage
Platform:  Linux Mint 21.1 Cinnamon
OS specifics: 

## Steps to reproduce

1. File>Switch profile
2. 
3. 

## Describe what you expected to happen
Joplin should start on its own with the changed profile

## profiles.json
{
	"version": 2,
	"currentProfileId": "default",
	"profiles": [
		{
			"name": "Default",
			"id": "default"
		},
		{
			"name": "Linux",
			"id": "qzopw8am"
		}
	]
}

**Comment by dpoulton-github** [comment]
**Additional Info:** Related forum post from DEC22 which suggests why Joplin on Linux does not display the same restart dialog as seen when updating / installing plugins.

https://discourse.joplinapp.org/t/linux-profile-switch-warning/28580
