### ISSUE TITLE
Error 1114 The table 'oc_filecache' is full

### ISSUE THREAD

**Issue by CodeBeast357** [laurent22/joplin#8245]
I received this error while trying to synchronize.

## Environment

Joplin 2.10.19 (prod, win32)

Client ID: 9655ff9d80714fd080a71abe1d898ed2
Sync Version: 3
Profile Version: 42
Keychain Supported: Yes

Revision: 1100ab0
Platform: Windows
OS specifics: version 10 (10.0.19045 N/A version 19045)

## Steps to reproduce

1. Synchronize

## Logfile

Error: PUT locks/1_1_9655ff9d80714fd080a71abe1d898ed2.json: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1114 The table 'oc_filecache' is full (Exception Sabre\DAV\Exception) (500): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception</s:exception>
  <s:message>An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1114 The table 'oc_filecache' is full</s:message>
</d:error>

Code: 500
Error: PUT locks/1_1_9655ff9d80714fd080a71abe1d898ed2.json: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1114 The table 'oc_filecache' is full (Exception Sabre\DAV\Exception) (500): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception</s:exception>
  <s:message>An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1114 The table 'oc_filecache' is full</s:message>
</d:error>

    at newError (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\WebDavApi.js:414:11)
    at WebDavApi.exec (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\WebDavApi.js:441:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FileApiDriverWebDav.put (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-webdav.js:203:10)

**Comment by Daeraxa** [comment]
This sounds like a problem with your sync target (nextcloud?) rather than Joplin.

**Comment by dpoulton-github** [comment]
It looks like the OP may have now raised the question on the Nextcloud Help Forum.

https://help.nextcloud.com/t/error-1114-the-table-oc-filecache-is-full/163006
