### ISSUE TITLE
Impossible to cut an image (like in copy - cut - paste)

### ISSUE THREAD

**Issue by fanofjop** [laurent22/joplin#8246]
OS : windows 7 and Kubuntu 23.04
JOPLIN : 
![image](https://github.com/laurent22/joplin/assets/107914828/447fc756-f5a6-4901-bceb-81fb3135e80c)
---
![image](https://github.com/laurent22/joplin/assets/107914828/627fde9b-1080-4788-b576-861e5fb2f045)
![image](https://github.com/laurent22/joplin/assets/107914828/b02e7d1b-1813-4f70-950e-e7e3abce11fd)
We have a "copy image" but a "cut image" is missing
[CTRL] [X] is working anyway.
Thanks if you can add it...

**Comment by fanofjop** [comment]
By the way. After a copy "paste" is OK :
![image](https://github.com/laurent22/joplin/assets/107914828/ffb52a27-cd80-4624-8d3d-96a7fac3e3f3)

**Comment by Daeraxa** [comment]
You know you can just edit the issue, you don't need to make a new one...
