### ISSUE TITLE
Impossible to cut an image (like in copy - cut - paste)

### ISSUE THREAD

**Issue by fanofjop** [laurent22/joplin#8247]
OS : windows 7 and Kubuntu 23.04
JOPLIN : 
![image](https://github.com/laurent22/joplin/assets/107914828/447fc756-f5a6-4901-bceb-81fb3135e80c)
---
![image](https://github.com/laurent22/joplin/assets/107914828/627fde9b-1080-4788-b576-861e5fb2f045)
![image](https://github.com/laurent22/joplin/assets/107914828/b02e7d1b-1813-4f70-950e-e7e3abce11fd)
We have a "copy image" but a "cut image" is missing
[CTRL] [X] is working anyway.
By the way, after copying, "paste" works.
![image](https://github.com/laurent22/joplin/assets/107914828/f9c8601a-7e0e-4e5f-8045-f8257de7ad2d)

Thanks if you can add it...

**Comment by Daeraxa** [comment]
I think this is because it shares the same right click menu as the standard html render when clicking the image and that obviously wouldn't have a cut command.

**Comment by fanofjop** [comment]
Well spotted ! I think so...
Anyway it's important to be able to cut an image in order to be able to move it from a place to another inside a note or to another note without the need to copy, paste and go back and delete...

**Comment by fanofjop** [comment]
I must add that to drag and drop the image from a place to another  doesn't work too.
