### ISSUE TITLE
Joplin IOS 12.11.2 sync error

### ISSUE THREAD

**Issue by lumloong** [laurent22/joplin#8252]
## Environment

Joplin version: 12.11.2
Platform: IOS
OS specifics: 16.5
![IMG_1844](https://github.com/laurent22/joplin/assets/17349915/443c7b83-3635-413b-a4e9-5a935a1ad8f6)

Sync error after update 12.11.2

**Comment by laurent22** [comment]
Hello, sorry about this issue. I've released a new version which should be in store as soon as Apple approve it (probably within the next few hours)

**Comment by laurent22** [comment]
The latest version 12.11.3 appears to have fixed the issue. Please download and let me know how it goes

**Comment by eflydata** [comment]
> 最新版本 12.11.3 似乎已经解决了这个问题。请下载并告诉我进展如何



> The latest version 12.11.3 appears to have fixed the issue. Please download and let me know how it goes

Updated to 12.11.3, everything works fine, thanks.

**Comment by lumloong** [comment]
> The latest version 12.11.3 appears to have fixed the issue. Please download and let me know how it goes

Updated to 12.11.3, everything works fine, thanks.
