### ISSUE TITLE
Upgrade to Electron 25

### ISSUE THREAD

**Issue by DoodlesEpic** [laurent22/joplin#8258]
The Electron version used by @joplin/app-desktop is Electron 19 which has been EOL since November 2022 according to https://www.electronjs.org/docs/latest/tutorial/electron-timelines

This version of Electron still has some bugs regarding running under Wayland sessions. Electron 20 is the first version that adds support for `ozone-platform-hint`, however it's also EOL too. I believe Joplin should move to Electron 25 if there are no blockers, since it just went stable today.

## Environment

Joplin version: 2.10.19
Platform: Linux
OS specifics: Fedora 38

## Steps to reproduce

N/A

## Describe what you expected to happen

Joplin should attempt to follow Electron release schedule as closely as possible to provide better platform support, get security and performance updates and provide a consistent experience.

## Logfile

N/A

**Comment by cwilby** [comment]
There are a couple of breaking changes that affect Joplin, namely:
- Drops support for macOS <=10.12
- Drops support for Windows <=8.1

Other than that, I read through the [breaking changes](https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-190) and compared it with this codebase - here are my notes:

## 19 => 20
- 🟢 Removed macOS 10.11 / 10.12 support
- 🟢 Renderers now sandboxed by default
- 🟢 Removed `skipTaskbar` on Linux
- 🟢 API Changed: session.setDevicePermissionHandler(handler)

## 20 => 21
- 🟢 Added memory cage for native modules
- 🟡 API Changed: webContents.printToPDF()
    - Used once in `packages/app-desktop/InteropServiceHelper`.
    - None of the changed or removed arguments noted in [breaking changes](https://www.electronjs.org/docs/latest/breaking-changes#api-changed-webcontentsprinttopdf) are included in `ExportNoteOptions`.
        - Should be compatible.

## 21 => 22
- 🟢 Deprecated: webContents.incrementCapturerCount(stayHidden, stayAwake)
- 🟢 Deprecated: webContents.decrementCapturerCount(stayHidden, stayAwake)
- 🟢 Removed: WebContents new-window event
- 🟢 Deprecated: BrowserWindow scroll-touch-* events

## 22 => 23
- 🟡 Behavior Changed: Draggable Regions on macOS
    - Need to test dragging/dropping notebooks in sidebar.
- 🟢 Removed: Windows 7 / 8 / 8.1 support
- 🟢 Removed: BrowserWindow scroll-touch-* events
- 🟢 Removed: webContents.incrementCapturerCount(stayHidden, stayAwake)
- 🟢 Removed: webContents.decrementCapturerCount(stayHidden, stayAwake)

## 23 => 24
- 🟢 API Changed: nativeImage.createThumbnailFromPath(path, size)

## 24 => 25
- (No documentation yet)

**Comment by cwilby** [comment]
@laurent22 the PR lock prevented me from commenting before closing.

Unfortunately it may be a while before I'm willing to create an acceptable solo effort PR.

**Comment by RayJW** [comment]
I second this. There are so many small issues with performance and functionality on Linux because of this, and I'm not even talking about the security implications. I don't really get the focus of the development sometimes. Why is no one trying to at least somewhat keep up with the Electron versions? I get that Electron moves very fast and some developers have issues keeping up, but the choice for this framework has been made and when people recommend a switch, it doesn't seem like the devs are open to that. Also, while on the topic of performance, why don't they merge the amazing performance enhancements from @ken1kob. Those are some of the best PRs I've seen in a long time with an explanation, analysis, graphs, and testing of everything done by him/her and the community and the devs just don't even look at them. Just look at the extensiveness of the write-up in #6386.

**Comment by personalizedrefrigerator** [comment]
This is still an issue!

**Comment by laurent22** [comment]
@personalizedrefrigerator, when you have a moment could you check if we can upgrade to Electron 25? Perhaps it will also fix the weird issues we have with cross-compiling the Apple Silicon release.

One issue we need to pay attention to is the one described here:

https://github.com/laurent22/joplin/blob/383e9d4e467e96fc454cbbcf091652a6b0154277/.github/scripts/run_ci.sh#L188

The Windows installer breaks with electron-builder@23. Also whenever upgrading Electron, we need to do a few manual checks:

- Check resource attachment
- Check sync
- Check print
- Check plugins
