### ISSUE TITLE
Joplin iOS 12.11.3 unable to open app

### ISSUE THREAD

**Issue by chemicL** [laurent22/joplin#8260]
After the latest update I can’t use the app. I haven’t set up biometrics, yet it complains about this feature. Tried rebooting, updating to latest iOS, shutting down the app, no success in making it work.
![IMG_5689](https://github.com/laurent22/joplin/assets/2554306/fd533abc-dab6-4286-aad4-de2eaa516fb7)

## Environment

Joplin version: 12.11.3
Platform: iOS
OS specifics: iOS 16.5

## Steps to reproduce

I’ve used the app for ages. Not sure if a clean setup will reproduce it. Probably installing an older version, configuring with Dropbox for backup, and afterwards updating to the latest version would do the job.

## Describe what you expected to happen

App should function normally.

## Logfile

—

**Comment by laurent22** [comment]
Could you try to setup Face ID on the device, then reboot, and then try to start the app. Then once logged in, you should be able to switch off biometrics from the config.

But I don't understand why it's asking for it here if you've never enabled it

**Comment by chemicL** [comment]
Thanks for a quick response. Due to my lack of understanding of the nature of the support in Joplin, let me first clarify: I do have Face ID set up on the device. However, I never did anything in Joplin or on behalf of Joplin with regards to Face ID. Now after your recommendation, I went to Settings -> Face ID & Passcode -> (Use Face ID for:) Other Apps -> enabled Joplin (as it was the only one that was disabled).
It got my installation of Joplin to launch properly.
Hope it helps anyone facing this issue or perhaps change some defaults in the next release of the app.

BTW huge thanks for your amazing work on this project, I've been a happy user for years!

**Comment by laurent22** [comment]
> Settings -> Face ID & Passcode -> (Use Face ID for:) Other Apps -> enabled Joplin (as it was the only one that was disabled).

Thank you, I wasn't aware of this option and indeed if it's off it would cause this when the biometrics option is on.

I'm assuming that the problem was caused by the previous version, that was buggy, and automatically enabled biometrics for you. The new version is fixed so that should be a one off. I'll keep that in mind though in case someone else reports the same issue.
