### ISSUE TITLE
Building Joplin - missing @joplin/utils@~2.11

### ISSUE THREAD

**Issue by thomascrisan** [laurent22/joplin#8262]
I am trying to build Joplin v2.11.6 on Arch Linux and am receiving the following error:

```
error Couldn't find package "@joplin/utils@~2.11" required by "./package.tgz" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
==> ERROR: A failure occurred in package_joplin().
    Aborting...
 -> error making: joplin-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
joplin - exit status 4
```

I went back and try to build the released version, v2.10.19, which I had built previously and now receive the same error.

**Comment by laurent22** [comment]
How do you build it?

**Comment by thomascrisan** [comment]
I am building Joplin using Arch Linux's makepkg and the build script for Joplin found here:

https://github.com/alfredopalhares/arch-pkgbuilds/tree/master/joplin

**Comment by laurent22** [comment]
We don't support this build method, so you'll need to check with them
