### ISSUE TITLE
Can't access joplin cloud because my email verification token has expired. How do I get a new one?

### ISSUE THREAD

**Issue by Michelleeekafljdal** [laurent22/joplin#8267]
## Environment

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1. 
2. 
3.

**Comment by laurent22** [comment]
Hello, does it work if you go to this page:

https://joplincloud.com/login

Then click on "I forgot my password"? If not please send an email with your email address to support AT joplincloud DOT com

**Comment by Michelleeekafljdal** [comment]
That page tells me this:
"An email has been sent to you containing an activation link to complete your registration.

Make sure you click it to secure your account and keep access to it."

I'm trying to sync my iphone joplin app with my mac joplin app. The iphone app says it's syncing but the mac app isn't. I'm hoping it's just because I haven't completed the registration.

**Comment by laurent22** [comment]
But can you login to your account in joplincloud.com

**Comment by Michelleeekafljdal** [comment]
Yes.

**Comment by laurent22** [comment]
Ok, in that case can you do a simple test?

- create a note on your iphone
- sync the iphone
- sync on mac

Did the note show up on mac? If not please provide the logs in iphone and mac

**Comment by Michelleeekafljdal** [comment]
Okay sorry, I should have mentioned. Every time i hit synchronize on the mac app it says: "Joplin can synchronise your notes using various providers. Select one from the list below." I choose Joplin Cloud and it pulls up a sign in box. I put in my un and pw and it just takes me back to the app home page. No sync, no error message, nothing else to do. I've tried it a bunch of times, making sure my un and pw are correct. Same thing occurs every time.

**Comment by Michelleeekafljdal** [comment]
Wait. Hold on. Idk what's different, but I just tried it again because I'm maybe a little neurotic and it finally signed me into the joplin cloud. Wow. I've been passively trying to figure this out for two months. Now my apps are synchronizing just fine.

**Comment by laurent22** [comment]
Ok, that's great that it's working now. But indeed I'd be curious to know why it wasn't previously!
