### ISSUE TITLE
REST API: Get resource data (or local file path)

### ISSUE THREAD

**Issue by tsumare** [laurent22/joplin#827]
### Operating system

- Windows
- macOS
- Linux

### Application

- Desktop

### Request

Please add a way to retrieve the contents of a resource from the REST API.  If this is not feasible, add a way to retrieve the filesystem path of that resource which could be opened by another local application.

I have written a tool that formats and uploads notes to a webpage, as well as any embedded images or attached files.  At present it uses joplin-cli's export function, but this requires syncing my notes to a cli instance.  Having just looked at the new API however, it seems to be a much cleaner method, save this missing feature.

Thanks

**Comment by laurent22** [comment]
I knew I had forgotten something :-) It will be in the next release.

**Comment by laurent22** [comment]
Implemented in latest version (/resources/:id/file)
