### ISSUE TITLE
iOS Share Extension stopped working

### ISSUE THREAD

**Issue by luigicarrini** [laurent22/joplin#8271]
Joplin version: 12.11.3 
Platform: iOS
OS specifics: iOS 16.5

## Steps to reproduce

1. Share a website link from iOS webbrowser to Joplin app via iOS share menu.
2. After sharing, Joplin app opens, but it doesn't create a new note and doesn't save the webpage link.

This issue just came up recently (after update of Joplin on iOs or after update of iOS system.)

**Comment by laurent22** [comment]
Fixed in 37b745c69e2a5207980d640ea554e8530c8ef162
