### ISSUE TITLE
Failed to build on macOS, Exit code: ENOENT. spawn /usr/bin/python ENOENT  failedTask=build stackTrace=Error: Exit code: ENOENT. spawn /usr/bin/python ENOENT

### ISSUE THREAD

**Issue by n1majne3** [laurent22/joplin#8272]
## Environment

Joplin version: 2.11.6
Platform: macOS
OS specifics: 12

## Steps to reproduce

It seems happened after #8149 , the version has become electron-builder: 22.11.7
## Logfile

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=darwin arch=arm64 electron=19.1.4 appOutDir=dist/mac-arm64
  • downloading     url=https://github.com/electron/electron/releases/download/v19.1.4/electron-v19.1.4-darwin-arm64.zip size=79 MB parts=6
  • downloaded      url=https://github.com/electron/electron/releases/download/v19.1.4/electron-v19.1.4-darwin-arm64.zip duration=4.524s
  • skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=     0 identities found
                                                Valid identities only
     0 valid identities found
Checking if notarization should be done...
Either not running in CI or not processing a desktop app tag - skipping notarization. process.env.IS_CONTINUOUS_INTEGRATION = undefined; process.env.GIT_TAG_NAME = undefined
  • building        target=DMG arch=arm64 file=dist/Joplin-2.11.2-arm64.dmg
  ⨯ Exit code: ENOENT. spawn /usr/bin/python ENOENT  failedTask=build stackTrace=Error: Exit code: ENOENT. spawn /usr/bin/python ENOENT
    at /Users/runner/work/Joplin-Action-for-macOS/Joplin-Action-for-macOS/joplin/packages/app-desktop/node_modules/builder-util/src/util.ts:132:18
    at exithandler (node:child_process:427:5)
    at ChildProcess.errorhandler (node:child_process:439:5)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
Error: Process completed with exit code 1.

**Comment by laurent22** [comment]
I had this issue too, you need to do this:

<s>https://github.com/electron-userland/electron-builder/issues/6726#issuecomment-1360898486</s>

**Comment by laurent22** [comment]
Actually you need to do what I've done in this commit: https://github.com/laurent22/joplin/commit/21648b1b1b541e7bb87cff262bcc6b54f817e114

    PYTHON_PATH=$(which python) yarn run dist

**Comment by laurent22** [comment]
And it will be solved by upgrading electron-builder, but the problem is that the latest electron-builder is broken in a different way that's much harder to solve
