### ISSUE TITLE
Thinks it's syncing, but it's not

### ISSUE THREAD

**Issue by SeaGab** [laurent22/joplin#8274]
I have Joplin set up to sync on three devices, and they all think they're doing so without issue. One created a conflict file and put a single note in it. The other two have shown no changes and are in no way synced.

I'm not finding these.
👉 Please follow one of these issue templates:
- https://github.com/laurent22/joplin/issues/new/choose

⚠️
The GitHub issue tracker is for **bugs** and **security issues** ONLY. For feature requests and support, please use the forum:
https://discourse.joplinapp.org/
⚠️

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by SeaGab** [comment]
- The version you are using. LATEST VERSION is not a version number!: Sync Version: 3
Profile Version: 42
Keychain Supported: Yes

Revision: 1100ab0

- If it is a sync issue, please let us know what you are syncing with: Mac desktop, iphone 6+, iphone 12 pro
- If you report a problem with upgrading, please let us know both versions (from/to).
- If you report a problem with the editor, please tell us which editor you are using (WYSIWYG/Markdown).
- The operating system you are using; Ventura 13.4 (22F66), iOS 12.5.7, iOS 16.5

**Comment by SeaGab** [comment]
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:29840 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtoolsYou might need to use a local HTTP server (instead of file://): https://reactjs.org/link/react-devtools-faq
main-html.js:60 Environment: prod
main-html.js:82 appId: net.cozic.joplin-desktop
main-html.js:84 appType: desktop
Logger.ts:237 09:24:34: App: Profile directory: /Users/victory/.config/joplin-desktop
Logger.ts:237 09:24:34: App: Root profile directory: /Users/victory/.config/joplin-desktop
Logger.ts:237 09:24:34: Database was open successfully
Logger.ts:237 09:24:34: Checking for database schema update...
Logger.ts:237 09:24:34: Current database version Object
Logger.ts:237 09:24:34: Upgrading database from version 42
Logger.ts:237 09:24:34: New version: 42. Previously recorded version: 42
Logger.ts:237 09:24:34: KeychainService: checking if keychain supported
Logger.ts:237 09:24:34: KeychainService: check was already done - skipping. Supported: 1
Logger.ts:237 09:24:34: e2ee/utils: Master password is not set - trying to get it from the active master key...
Logger.ts:237 09:24:34: handleSyncStartupOperation: Processing operation: 0
Logger.ts:237 09:24:34: App: Client ID: d7d2d90937eb46738c14cfdc962cc303
Logger.ts:237 09:24:34: models/Setting: Applying default migrations...
Logger.ts:237 09:24:34: e2ee/utils: Trying to load 0 master keys...
Logger.ts:237 09:24:34: e2ee/utils: Loaded master keys: 0
Logger.ts:237 09:24:34: ResourceFetcher: Auto-add resources: Mode: always
Logger.ts:237 09:24:34: ResourceFetcher: Auto-added resources: 0
Logger.ts:237 09:24:34: App: "syncInfoCache" was changed - setting up encryption related code
Logger.ts:237 09:24:34: e2ee/utils: Trying to load 0 master keys...
Logger.ts:237 09:24:34: e2ee/utils: Loaded master keys: 0
Logger.ts:237 09:24:34: Scheduling sync operation... 10000
Logger.ts:237 09:24:34: Setting up recurrent sync with interval 300
Logger.ts:237 09:24:34: App: "syncInfoCache" was changed - setting up encryption related code
Logger.ts:237 09:24:34: e2ee/utils: Trying to load 0 master keys...
Logger.ts:237 09:24:34: e2ee/utils: Loaded master keys: 0
Logger.ts:237 09:24:34: Scheduling sync operation... 10000
Logger.ts:237 09:24:34: App: "syncInfoCache" was changed - setting up encryption related code
Logger.ts:237 09:24:34: e2ee/utils: Trying to load 0 master keys...
Logger.ts:237 09:24:34: e2ee/utils: Loaded master keys: 0
Logger.ts:237 09:24:34: Scheduling sync operation... 10000
Logger.ts:237 09:24:34: app.start: doing regular boot
Logger.ts:237 09:24:34: App: Refreshing notes: null null
Logger.ts:237 09:24:34: App: "syncInfoCache" was changed - setting up encryption related code
Logger.ts:237 09:24:34: e2ee/utils: Trying to load 0 master keys...
Logger.ts:237 09:24:34: e2ee/utils: Loaded master keys: 0
Logger.ts:237 09:24:34: Scheduling sync operation... 10000
Logger.ts:237 09:24:34: Setting up recurrent sync with interval 300
Logger.ts:237 09:24:34: App: "syncInfoCache" was changed - setting up encryption related code
Logger.ts:237 09:24:34: e2ee/utils: Trying to load 0 master keys...
Logger.ts:237 09:24:34: e2ee/utils: Loaded master keys: 0
Logger.ts:237 09:24:34: Scheduling sync operation... 10000
Logger.ts:237 09:24:34: App: "syncInfoCache" was changed - setting up encryption related code
Logger.ts:237 09:24:34: e2ee/utils: Trying to load 0 master keys...
Logger.ts:237 09:24:34: e2ee/utils: Loaded master keys: 0
Logger.ts:237 09:24:34: Scheduling sync operation... 10000
Logger.ts:237 09:24:34: Scheduling sync operation... 1000
Logger.ts:237 09:24:34: RevisionService: runInBackground: Starting background service with revision collection interval 600000
Logger.ts:237 09:24:34: App: Refreshing notes: 2 6a4e3090b7e64c75b68f1d6bdc15a830
Logger.ts:237 09:24:34: defaultPluginsUtils: Could not find default plugins' directory: /Applications/Joplin.app/Contents/Resources/build/defaultPlugins - skipping installation.
Logger.ts:237 09:24:34: SpellCheckerServiceDriverNative: Set effective languages to "en-US"
Logger.ts:237 09:24:35: Loading existing note 6d50f32f17d547df9bc9a0b51ee87c4d
Logger.ts:237 09:24:36: DecryptionWorker: cannot start because no master key is currently loaded.
Logger.ts:237 09:24:36: Preparing scheduled sync
Logger.ts:237 09:24:36: Starting scheduled sync
Logger.ts:237 09:24:36: Synchronizer: Sync: starting: Starting synchronisation to target 10... supportsAccurateTimestamp = true; supportsMultiPut = true [1685809476576]
Logger.ts:237 09:24:36: Synchronizer: Indexing resources...
Logger.ts:237 09:24:36: ResourceService::indexNoteResources: Start
Logger.ts:237 09:24:36: models/Setting: Saving settings...
Logger.ts:237 09:24:37: Loaded note: {id: '6d50f32f17d547df9bc9a0b51ee87c4d', parent_id: '6a4e3090b7e64c75b68f1d6bdc15a830', title: 'Pulphead by John Jeremiah Sullivan', body: 'Essays recommended by Roxane Gay\n', created_time: 1685557788118, …}
Logger.ts:237 09:24:38: models/Setting: Saving settings...
Logger.ts:237 09:24:38: RevisionService: maintenance: Starting...
Logger.ts:237 09:24:38: RevisionService: maintenance: Service is enabled
Logger.ts:237 09:24:39: checkForUpdates: Starting...
Logger.ts:237 09:24:39: checkForUpdates: Checking with options {"includePreReleases":false}
Logger.ts:237 09:24:39: ResourceService::indexNoteResources: Completed
Logger.ts:237 09:24:39: RevisionService: collectRevisions: Created revisions for 0 notes
Logger.ts:237 09:24:39: RevisionService: maintenance: Done in 560ms
Logger.ts:237 09:24:39: models/Folder: updateFolderShareIds: {shareUpdateCount: 0, unshareUpdateCount: 0}
Logger.ts:237 09:24:39: models/Folder: updateNoteShareIds: notes to update: 0
Logger.ts:237 09:24:39: FileApi: get info.json
useMessageHandler.ts:17 Got ipc-message: noteRenderComplete undefined
Logger.ts:237 09:24:39: ShareService: Refresh share invitations:
Logger.ts:237 09:24:40: models/Setting: Settings have been saved.
Logger.ts:237 09:24:40: checkForUpdates: Current version: 2.10.19
Logger.ts:237 09:24:40: checkForUpdates: Latest version: 2.10.19
Logger.ts:237 09:24:40: checkForUpdates: Is Pre-release: false
Logger.ts:237 09:24:40: checkForUpdates: Done.
Logger.ts:237 09:24:40: models/Setting: Settings have been saved.
Logger.ts:237 09:24:40: ShareService: Refreshed shares: {items: Array(0), has_more: false}
Logger.ts:237 09:24:40: models/Folder: updateNoLongerSharedItems: {folders: 0, notes: 0, resources: 0}
Logger.ts:237 09:24:40: Synchronizer: Sync target remote info: SyncInfo {version_: 3, masterKeys_: Array(0), e2ee_: {…}, activeMasterKeyId_: {…}, ppk_: {…}}
Logger.ts:237 09:24:40: Synchronizer: Sync target is already setup - checking it...
Logger.ts:237 09:24:40: Synchronizer: Sync target local info: SyncInfo {version_: 3, masterKeys_: Array(0), e2ee_: {…}, activeMasterKeyId_: {…}, ppk_: {…}}
Logger.ts:237 09:24:40: FileApi: delta 
DevTools failed to load source map: Could not parse content for file:///Applications/Joplin.app/Contents/Resources/app.asar/gui/note-viewer/pluginAssets/mermaid/mermaid.min.js.map: Unexpected end of JSON input
Logger.ts:237 09:24:41: Synchronizer: Sync: fetchingTotal: Fetching delta items from sync target
Logger.ts:237 09:24:41: ShareService: Refresh share invitations:
Logger.ts:237 09:24:41: ShareService: Refreshed shares: {items: Array(0), has_more: false}
Logger.ts:237 09:24:41: models/Folder: updateNoLongerSharedItems: {folders: 0, notes: 0, resources: 0}
Logger.ts:237 09:24:41: Synchronizer: Sync: finished: Synchronisation finished [1685809476576]
Logger.ts:237 09:24:41: Synchronizer: Operations completed: 
Logger.ts:237 09:24:41: Synchronizer: fetchingTotal: -
Logger.ts:237 09:24:41: Synchronizer: Total folders: 2
Logger.ts:237 09:24:41: Synchronizer: Total notes: 14
Logger.ts:237 09:24:41: Synchronizer: Total resources: 1079
Logger.ts:237 09:24:41: Sync has finished and note has never been changed - reloading it
Logger.ts:237 09:24:41: Setting up recurrent sync with interval 300
Logger.ts:237 09:24:41: Updating all notifications...
Logger.ts:237 09:24:41: Garbage collecting alarms...
Logger.ts:237 09:24:42: DecryptionWorker: cannot start because no master key is currently loaded.
Logger.ts:237 09:24:44: SearchEngine: Updating FTS table...
Logger.ts:237 09:24:44: SearchEngine: Updated FTS table in 1ms. Inserted: 0. Deleted: 0
Logger.ts:237 09:24:46: CommandService::execute: synchronize false
Logger.ts:237 09:24:46: Scheduling sync operation... 0
Logger.ts:237 09:24:46: Preparing scheduled sync
Logger.ts:237 09:24:46: Starting scheduled sync
Logger.ts:237 09:24:46: Synchronizer: Sync: starting: Starting synchronisation to target 10... supportsAccurateTimestamp = true; supportsMultiPut = true [1685809486988]
Logger.ts:237 09:24:46: Synchronizer: Indexing resources...
Logger.ts:237 09:24:46: ResourceService::indexNoteResources: Start
Logger.ts:237 09:24:47: ResourceService::indexNoteResources: Completed
Logger.ts:237 09:24:47: models/Folder: updateFolderShareIds: {shareUpdateCount: 0, unshareUpdateCount: 0}
Logger.ts:237 09:24:47: models/Folder: updateNoteShareIds: notes to update: 0
Logger.ts:237 09:24:47: FileApi: get info.json
Logger.ts:237 09:24:47: Synchronizer: Sync target remote info: SyncInfo {version_: 3, masterKeys_: Array(0), e2ee_: {…}, activeMasterKeyId_: {…}, ppk_: {…}}
Logger.ts:237 09:24:47: Synchronizer: Sync target is already setup - checking it...
Logger.ts:237 09:24:47: Synchronizer: Sync target local info: SyncInfo {version_: 3, masterKeys_: Array(0), e2ee_: {…}, activeMasterKeyId_: {…}, ppk_: {…}}
Logger.ts:237 09:24:48: Synchronizer: TaskQueue.stop: syncDownload: waiting for tasks to complete: 0
Logger.ts:237 09:24:48: Synchronizer: TaskQueue.stop: syncDownload: Done, waited for 0
Logger.ts:237 09:24:48: FileApi: delta 
Logger.ts:237 09:24:48: Synchronizer: Sync: fetchingTotal: Fetching delta items from sync target
Logger.ts:237 09:24:48: ShareService: Refresh share invitations:
Logger.ts:237 09:24:49: ShareService: Refreshed shares: {items: Array(0), has_more: false}
Logger.ts:237 09:24:49: models/Folder: updateNoLongerSharedItems: {folders: 0, notes: 0, resources: 0}
Logger.ts:237 09:24:49: Synchronizer: Sync: finished: Synchronisation finished [1685809486988]
Logger.ts:237 09:24:49: Synchronizer: Operations completed: 
Logger.ts:237 09:24:49: Synchronizer: fetchingTotal: -
Logger.ts:237 09:24:49: Synchronizer: Total folders: 2
Logger.ts:237 09:24:49: Synchronizer: Total notes: 14
Logger.ts:237 09:24:49: Synchronizer: Total resources: 1079
Logger.ts:237 09:24:49: Sync has finished and note has never been changed - reloading it
Logger.ts:237 09:24:49: Setting up recurrent sync with interval 300
Logger.ts:237 09:24:50: DecryptionWorker: cannot start because no master key is currently loaded.
Logger.ts:237 09:25:04: ResourceService::indexNoteResources: Start
Logger.ts:237 09:25:04: ResourceService::indexNoteResources: Completed
Logger.ts:237 09:25:04: ResourceService::deleteOrphanResources:

Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
1 source
/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.developme…:1
Learn more: User-Agent String Reduction

**Comment by laurent22** [comment]
I can't see any error in the log. If there was a conflict, then it's expected that the original note won't be changed.

Can you try again to make some changes and sync, and see if you see the changes on all the devices?

**Comment by SeaGab** [comment]
Hi,

I changed the title.

It tells me ti's creating 1 remote item.

That item is only on the 6+ (the others don't have the Conflicts notebook). The desktop has the original version, unchanged (which is nowhere else). None of the notes from the other devices show up on the 6+. Aside from the single, conflicting note, which only shows in its original version on the 12 pro, the 12 pro and desktop are synced.

Thank you for your help!!

best,
Sea

_________
I love you. This is my signature. It is also true.

https://mythicdeviant.com
***@***.***://www.youtube.com/channel/UCZYkBonjetzqQb5NIppdNVw

------- Original Message -------

**Comment by GJPvWesten** [comment]
Are you having these issues on the mac client?I think this is similar to what I am describining here with my mac client. The mac client does not update and does not give any error: https://github.com/laurent22/joplin/issues/8170 

I specifically encounter this when notes are created or modified in the android client.

**Comment by SeaGab** [comment]
Yes: it seems like the same problem.

**Comment by GJPvWesten** [comment]
This is now also starting to happen when syncing from mac to iphone. Notes made and modified on mac are not updated on iphone (have not been able to check android).

**Comment by GJPvWesten** [comment]
Starting to get a bit desperate. May have to move away from Joplin. 

I did notice a 'body dif' file that was not processed by mac. Is this underlyng the issue?
<img width="852" alt="Screenshot 2023-06-27 at 14 55 26" src="https://github.com/laurent22/joplin/assets/3306167/edad2718-c873-4551-a041-7f596e5f3abd">

**Comment by laurent22** [comment]
Hello I'm closing this issue as we can't properly reply to all these different unrelated sync issues. If you still have a sync problem, please open a new issue and follow the template
