### ISSUE TITLE
Pasting text to WYSIWYG-Editor results in additional newlines

### ISSUE THREAD

**Issue by marcorombach** [laurent22/joplin#8276]
## Environment

Joplin version: Joplin for Desktop 2.10.19
Platform: Windows
OS specifics: Windows 10 Pro 22H2 64bit

## Steps to reproduce

1. Write to lines of text in a plain text editor
2. Copy these lines of text and paste into a note in Joplin
3. Now there is one addtional newline in Joplin for each newline in the plain text editor

## Describe what you expected to happen
If I paste text it should have the same amount of line breaks/newlines as it has at it's source.

## Logfile
The only log message that shows up when doing this is:
C:\Program Files\Joplin\resources\app.asar\gui\NoteEditor\utils\useMessageHandler.js:26 Got ipc-message: noteRenderComplete null

Here is a screenshot showing the source text and how it's presented in Joplin:

![image](https://github.com/laurent22/joplin/assets/36333308/f413782c-7bea-4ae2-b46b-63f32ae22bb0)

**Comment by chronos1970** [comment]
Possibly related to #6822

**Comment by marcorombach** [comment]
Issue still present in v.2.11.11 (win)

**Comment by marcorombach** [comment]
Seems to be fixed in 2.12.10, thanks!
