### ISSUE TITLE
Opens menu instead of app by click on icon in tray

### ISSUE THREAD

**Issue by vitonsky** [laurent22/joplin#8290]
I use Joplin a few years, recently i've update on new version and now it's absolutely unusable, because i have to do 2 click to just open my notes. It makes my research activity absolutely not possible with Joplin.

Joplin always has problems with UI that interfered to draw notes fast and forced to use text editor or even Telegram to add notes fast, but this bug just kills Joplin for me. Please, pay attention on severity of this bug and fix it as soon as possible.

It looks as small bug in the code, but it's a bad signal that this bug did not been catch by QA, for me it looks Joplin does not focus on UX. All i needs of notes app is to supports markdown and allow me to create notes fast.

## Environment

Joplin version: 2.11.6 AppImage
Platform: Linux
OS specifics: Ubuntu 22.04, KDE

## Steps to reproduce

1. Enable option "Show tray icon"
2. Run Joplin and close window
3. Click on button in tray

## Expected behavior

Open application by click on button in tray

## Actual behavior

Open menu with 2 items - "Open Joplin" and "Quit"

**Comment by laurent22** [comment]
How did you install the app?

**Comment by vitonsky** [comment]
I've download https://github.com/laurent22/joplin/releases/download/v2.11.6/Joplin-2.11.6.AppImage
Then i make it executable and run

**Comment by personalizedrefrigerator** [comment]
I'm noticing similar functionality on MacOS. Clicking on the shortcut once brings Joplin to the foreground. Clicking on the shortcut again (or right clicking for the first time) shows the relevant menu.

Edit: Nevermind! I observed the expected behavior!

**Comment by vitonsky** [comment]
@github-actions

Not fixed

**Comment by vitonsky** [comment]
Not stale

**Comment by vitonsky** [comment]
Not stale, still reproduces

**Comment by vitonsky** [comment]
Not stale, still reproduces
