### ISSUE TITLE
path spec for local file sync must end in /

### ISSUE THREAD

**Issue by pcause** [laurent22/joplin#83]
### Operating system

- [ ] Windows
- [ ] macOS
- [ x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x ] Desktop
- [ ] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

I entered a path to sync to as /x/y/z/j and closed preferneces.  when I reopen i see that /x/y/z is the path.  but if i enter /x/y/z/j/ then /x/y/z/j/ is there.  can you remove the requirement for a trailing slash?

*If there is an error, please copy and paste the full error message*

---

**Comment by laurent22** [comment]
I couldn't replicate this but there are several changes regarding sync path in the last version, so could you give it a try and see if it's still happening?

**Comment by pcause** [comment]
yes, seems fixed in latest.  thanks
