### ISSUE TITLE
Persian/Arabic default font sucks

### ISSUE THREAD

**Issue by mahdimahdieh** [laurent22/joplin#8304]
## Environment

Joplin version: Latest
Platform: Windows
OS specifics: 11

## Steps to reproduce
 
Just type something in the subject or title or notebook's title and this ugly font will appear:

![image](https://github.com/laurent22/joplin/assets/74340183/ed3f8616-07be-4603-b521-3cf9adf1dae7)

![image](https://github.com/laurent22/joplin/assets/74340183/51935f5b-6bc3-4df0-8501-f10be3254b3a)

## Describe what you expected to happen

change defualt arabic/persian font to something like https://rastikerdar.github.io/vazirmatn/en or https://aminabedi68.github.io/Estedad/

**Comment by rio-codes** [comment]
Do you like any of these? https://fonts.google.com/?subset=arabic&noto.script=Arab  
Google Fonts has some nice choices and might be easier to integrate.

**Comment by mahdimahdieh** [comment]
Thanks for your response. Vazirmatan that I mentioned above is also available on Google Fonts:
https://fonts.google.com/specimen/Vazirmatn?subset=arabic&noto.script=Arab&query=vazir

**Comment by rio-codes** [comment]
You could change the css yourself, I don't see an elegant way to do it in the existing code. Click Tools -> Options -> Appearance -> Show Advanced Settings and select "Custom stylesheet for Joplin-wide app styles".

In the editor that comes up, copy paste this in:

```
:root {
	--font-face: "Vazirmatan"
}
* {
  font-family: var(--font-face) !important;
}
```
As long as you have the font installed it should change the non-markdown text to that font.

**Comment by mahdimahdieh** [comment]
Thanks! That's worked!
