### ISSUE TITLE
Export notes with links begin with a slash (/) as PDF not working

### ISSUE THREAD

**Issue by amane-katagiri** [laurent22/joplin#8305]
## Environment

Joplin version: 2.10.19
Platform: Windows
OS specifics: 11 Pro (build 22621)

## Steps to reproduce

1. Create note with `[a link starts with slash](/)`
2. Export as PDF.
3. Showed an error "EISDIR: illegal operation on a directory, read" and no PDF file exported.

![1](https://github.com/laurent22/joplin/assets/8361232/2ff893d4-ff6c-41c5-b53d-7f61e088c93b)
![2](https://github.com/laurent22/joplin/assets/8361232/9c1b1678-a2de-448e-8a99-ca6dbc7ca961)

## Describe what you expected to happen

1. Create note with `[link starts with slash](/)`
2. Export as PDF.
3. Saved a PDF file with "a link starts with slash".

## Logfile

```
C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\MainScreen.js:338 Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
    at DataURISync (C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\htmlpack\node_modules\datauri\sync.js:13:42)
    at dataUriEncode (C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\htmlpack\dist\index.js:44:20)
    at processAnchorTag (C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\htmlpack\dist\index.js:136:21)
    at Object.onopentag (C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\htmlpack\dist\index.js:178:39)
    at Parser.onopentagend (C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\htmlpack\node_modules\@joplin\fork-htmlparser2\lib\Parser.js:206:27)
    at Tokenizer._stateBeforeAttributeName (C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\htmlpack\node_modules\@joplin\fork-htmlparser2\lib\Tokenizer.js:201:23)
(anonymous) @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\MainScreen.js:338
rejected @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\MainScreen.js:6
Promise.then (async)
step @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\MainScreen.js:7
fulfilled @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\MainScreen.js:5
processTicksAndRejections @ node:internal/process/task_queues:96
Promise.then (async)
step @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\MainScreen.js:7
(anonymous) @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\MainScreen.js:8
__awaiter @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\MainScreen.js:4
printTo_ @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\MainScreen.js:316
(anonymous) @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\commands\exportPdf.js:53
fulfilled @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\commands\exportPdf.js:5
processTicksAndRejections @ node:internal/process/task_queues:96
Promise.then (async)
step @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\commands\exportPdf.js:7
fulfilled @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\commands\exportPdf.js:5
Promise.then (async)
step @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\commands\exportPdf.js:7
fulfilled @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\commands\exportPdf.js:5
processTicksAndRejections @ node:internal/process/task_queues:96
Promise.then (async)
step @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\commands\exportPdf.js:7
(anonymous) @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\commands\exportPdf.js:8
__awaiter @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\commands\exportPdf.js:4
execute @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\commands\exportPdf.js:24
(anonymous) @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:158
(anonymous) @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:8
__awaiter @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:4
execute @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:149
(anonymous) @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\services\commands\MenuUtils.js:54
click @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\services\commands\MenuUtils.js:42
apply @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\callbacks-registry.js:54
(anonymous) @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:346
(anonymous) @ C:\Users\amane\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:328
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
```

**Comment by dpoulton-github** [comment]
Possibly because links do not start with a slash. They start with colon slash. 

`[Link starts with colon slash](:/e442f3a587204a60b43e515f829ff86a)`

Missing out the colon also throws an error if the link is clicked in the desktop app.

![image](https://github.com/laurent22/joplin/assets/60117449/011bb841-0e22-4130-808c-d68c743dc190)

**Comment by amane-katagiri** [comment]
Ah, I use Joplin to create drafts of my blog posts, and I often write links without hostname (`/path/to/my/post.html`) to describe links within the site.

I want to print out notes containing such links, but I have to  temporally replace them with links with hostnames appended (`https://example.com/path/to/my/post.html`) just only to export them.

I know that img or video tags starting with `:/...` represent resources in Joplin, but this is not relevant with showing text links on a PDF, so I want them to be exported without problem.

**Comment by rio-codes** [comment]
There should be a way to [escape slash characters](https://stackoverflow.com/questions/26514580/tinymce-html-encode-backslash) with TinyMCE. I wasn't able to reproduce it on my Linux desktop, I'll try and find a Windows 11 desktop to test this.

edit: I think I misunderstood the issue, it's not the slash character itself, it looks like Markdown wants relative filepaths. So for your example `https://example.com/path/to/my/post.html` instead you would use `../../../post.html`. Do you mind trying that out and telling me if it works?

**Comment by amane-katagiri** [comment]
> edit: I think I misunderstood the issue, it's not the slash character itself, it looks like Markdown wants relative filepaths. So for your example https://example.com/path/to/my/post.html instead you would use ../../../post.html. Do you mind trying that out and telling me if it works?

Sorry, after reviewing the pattern in more detail, I found that the "begin with a slash" condition was a misunderstanding. In fact, it appears that the EISDIR error occurs when the resolved address reaches some root directory.

| link | PDF export | resolved path (*at a guess*) |
| --- | --- | --- |
| `../../../..` | ❌ | `/` |
| `../../../../path/to/file` | ⭕ | `/path/to/file` |
| `../../../../path/to/file/..` | ⭕ | `/path/to` |
| `../../../../path/to/file/../../../..` | ❌ | `/` |
| `/` | ❌ | `/` |
| `/../../../..` | ❌ | `/` |
| `/path/to/file` | ⭕ | `/path/to/file` |
| `path/to/..` | ⭕ | `/path` |
| `path/to/../../..` | ❌ | `/` |
| `path/to/../../../../file` | ⭕ | `/file` |
| `path/to/../../../../my/file/..` | ⭕ | `/my` |
| `path/to/../../../../my/file/../..` |  ❌ | `/` |
| `path/to/file` | ⭕ | `/path/to/file` |

note: `file` or `file/` does not change the outcome.

**Comment by rio-codes** [comment]
I wonder if it is a Windows vs. Linux thing. I can't reproduce it on Arch Linux 6.3.8-arch1-1 and I know Windows can be touchy about filepaths. Especially since it uses backslashes as defaults for local paths rather than forward slashes like URLs (or Unix-based systems). I wonder what it would consider the "root"? Would it be your home directory like `C:\Users\amane` or just `C:\`? 

If you make one of the paths that works above (non-root) point to something that exists on your local computer, does clicking it open the local file?

**Comment by amane-katagiri** [comment]
In Joplin, only showed "Unsupported link or message" on click. In exported PDF file, the current directory `.` seems to be `C:\Users\amane\.config\joplin-desktop\tmp` and the "root" directory `/` is `C:\`, regardless of current location.

[pdf-test.pdf](https://github.com/laurent22/joplin/files/11860454/pdf-test.pdf)

```
$ strings pdf-test.pdf | grep URI
/S /URI
/URI (file:///C:/Users/path/to/file)>>>>
/S /URI
/URI (file:///C:/Users/path/to/)>>>>
/S /URI
/URI (file:///C:/path/to/file)>>>>
/S /URI
/URI (file:///C:/Users/amane/.config/joplin-desktop/tmp/path/)>>>>
/S /URI
/URI (file:///C:/Users/amane/.config/file)>>>>
/S /URI
/URI (file:///C:/Users/amane/.config/my/)>>>>
/S /URI
/URI (file:///C:/Users/amane/.config/joplin-desktop/tmp/path/to/file)>>>>
```

| link | path in Joplin (*at a guess*) | path in PDF |
| --- | --- | --- |
| `../../../../path/to/file` | `/path/to/file` | `C:\User\path\to\file` |
| `../../../../path/to/file/..` | `/path/to` | `C:\User\path\to\` |
| `/path/to/file` | `/path/to/file` | `C:\path\to\file` |
| `path/to/..` | `/path` | `C:\Users\amane\.config\joplin-desktop\tmp\path\` |
| `path/to/../../../../file` | `/file` | `C:\Users\amane\.config\file` |
| `path/to/../../../../my/file/..` | `/my` | `C:\Users\amane\.config\my\` |
| `path/to/file` | `/path/to/file` | `C:\Users\amane\.config\joplin-desktop\tmp\path\to\file` |

I would like the same "directory rules" to apply to path failed to export PDF, but why can't?
