### ISSUE TITLE
Copy from Quora to Joplin fails

### ISSUE THREAD

**Issue by red-ochre** [laurent22/joplin#8306]
## Environment

Joplin version: 12.11.3
Platform: iOS 
OS specifics: 16.5

## Steps to reproduce

1. Open Quora app
2. Find an entry that I'd like to keep.
3. Tap on three horizontal dots at bottom right of entry.
4. Tap on "Share via..."
5. Tap on "Joplin"
6. Joplin app opens but at the page that was last open and no copying of info from Quora.

## Describe what you expected to happen

I expect the Quora entry to be copied into Joplin as a new note. I have been doing this for some time to copy Quora entries into Evernote instead of Joplin and it works fine there.

## Logfile

No errors in the log from this.

**Comment by djsudduth** [comment]
Same issue for all sharing from **any app** on iOS and iPadOS -> using the Apple Share option will launch Joplin but won't create a new note. 

Joplin iOS mobile version: 12.11.3
iOS: 16.5
