### ISSUE TITLE
Sorting users by "total size" leads to a crash

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8308]
> select "id", "email", "password", "full_name", "is_admin", "updated_time", "created_time", "email_confirmed", "must_set_password", "account_type", "can_upload", "max_item_size", "can_share_folder", "can_share_note", "max_total_item_size", "total_item_size", "enabled", "disabled_time" from "users" where "enabled" = $1 order by "total_size" asc limit $2 - column "total_size" does not exist

**Comment by hubertfilho** [comment]
I changed the label desktop to server.

**Comment by hubertfilho** [comment]
There are 4 columns that leads to the same kind of crash. They're:

- account
- total size
- max total size
- can share

I believe it's happening because the name of the column in the table is not the same as in the database.
