### ISSUE TITLE
Resizing an image changes it's orientation.

### ISSUE THREAD

**Issue by Tamono** [laurent22/joplin#8310]
## Description
When attaching a previously taken image to a note, Joplin changes its orientation.

## Environment

Joplin version: 2.10.9
Platform: Android
OS specifics: Android 12

## Steps to reproduce

1. Take picture outside of Joplin 
2. Go into note 
3. Click on 3 dots. Select "Attach"
4. Dialog pops up. Choose "Attach file"
5. Select picture taken in step 1
6. Resize dialog pops up. Select "Yes"
7. Image has a wrong orientation.

## Describe what you expected to happen
I expect the image to have it's original orientation after being resized by Joplin.

## Logfile
![log_file_screenshot](https://github.com/laurent22/joplin/assets/27372683/f46d671e-6d37-4f2c-9c7a-abffc9ed4e1e)

**Comment by laurent22** [comment]
Can you provide the image that's causing problem? In general it doesn't happen with most images as far as I know

**Comment by marph91** [comment]
I had this issue a few weeks ago too, but can't reproduce it. I believe I rotated the image before by 90 degrees.

**Comment by MoriarT3a** [comment]
I have this problem with every picture I shot in Portrait (I mean the picture is higher then wide).

The funny thing is, if I made some changes to the picture with another app, the orientation stays like it should be, after resizeing by Joplin.

I've made actually a picture here to reproduce it.

What happend:
![Screenshot_20230711-211549_Trebuchet](https://github.com/laurent22/joplin/assets/30555787/19af7597-7606-4755-ac99-819ec02988ec)

Nd here is the Test Picture
![IMG_20230711_211427165](https://github.com/laurent22/joplin/assets/30555787/35bb7fa9-7c5f-4351-8c30-fb828f8baaca)

I don't know if uploading the image maybe do something to my example image. Otherwiese I maybe could upload it to a cloud. 🤔

**Comment by Tamono** [comment]
I still have the same problem with every picture taken in portrait mode (meaning picture being higher than wide) as described above by @MoriarT3a. For me the image too keeps its orientation if I edit it outside of Joplin before attaching it. Pictures taken in landscape mode (meaning picture being wider than high) that are attached to a note keep their original orientation like the are supposed to.

**Comment by laurent22** [comment]
> I don't know if uploading the image maybe do something to my example image. Otherwiese I maybe could upload it to a cloud. 🤔

I can't replicate the bug with your test image so indeed it may be modified by GitHub when you upload it. If you zip it up first and attach it that should preserve it

**Comment by MoriarT3a** [comment]
> > I don't know if uploading the image maybe do something to my example image. Otherwiese I maybe could upload it to a cloud. 🤔
> 
> I can't replicate the bug with your test image so indeed it may be modified by GitHub when you upload it. If you zip it up first and attach it that should preserve it

@laurent22  Lets give it a try.

[2go.zip](https://github.com/laurent22/joplin/files/12327572/2go.zip)

@Tamono are you using LineageOS? Maybe this is relatet to our OS or the Camera App.
