### ISSUE TITLE
Line breaks added when importing lists from Evernote

### ISSUE THREAD

**Issue by br3ndonland** [laurent22/joplin#832]
Thanks for your work on Joplin.

Lists are importing from Evernote with line breaks between bullets/numbers and text, like this:

```text
-
This note has an unordered list
-
List item
-
List item

1.
This note also has an ordered list
2.
List item 2
3.
List item 3
```

![joplin-list-import-20180930](https://user-images.githubusercontent.com/26674818/46262971-14c0ea00-c4d7-11e8-848b-957aebaac470.png)

The _.enex_ file I imported is available in [this public GitHub Gist](https://gist.github.com/br3ndonland/d6d3067780bfb20d81561aeeb332f5f6).

This was briefly mentioned in issue #[585](https://github.com/laurent22/joplin/issues/585).

System info: macOS High Sierra 10.13.6, Evernote 7.5, Joplin 1.0.111 desktop app

No console errors appear with debug mode enabled, and no app errors appear when importing.

**Comment by laurent22** [comment]
That will be fixed in the next release.

**Comment by aremesch** [comment]
Hi, could it be this issue is still there in 1.0.160 (windows)?

**Comment by laurent22** [comment]
> Hi, could it be this issue is still there in 1.0.160 (windows)?

Could be. Do you have an example enex file that still shows this problem?

**Comment by aremesch** [comment]
Hi Laurent,

Thank you for your answer & your great work!

The attached file Test2.enex is part of an export from the current Evernote
6.18.4.8489 I did yesterday. I had to anonymize the note a bit, but it
shows the problem I observed with the bulk import that random line breaks
have been inserted into the code which makes the note rather unusable.

Interestingly, I failed with my first attempt reproduce the problem by
duplicating the note and exporting a notebook with only that note in it.
I've attached this file as well (Test-Notebook.enex).

Probably Evernote exports the note differently as a single export or as a
bulk export containing other notes with base64 encoded graphics, etc.

Best, Alex

Am Di., 18. Juni 2019 um 00:01 Uhr schrieb Laurent Cozic <
notifications@github.com>:

**Comment by aremesch** [comment]
Sorry, I just realized the attachments I sent with my mail reply won't make it here, so I just created a public gist: https://gist.github.com/aremesch/b7df0085bfd64ed903bbcb0c04e788e7

Test2.enex is the note from a bulk export thats broken in Joplin, Test-Notebook.enex is the same note from a single export thats imported correctly.

**Comment by laurent22** [comment]
Thanks for the Enex file. I've created a new issue to track this: https://github.com/laurent22/joplin/issues/1672
