### ISSUE TITLE
Add a CI step to check that basic HTTP requests are working

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8332]
In `.github/workflows/github-actions-main.yml`, in the `ServerDockerImage` job, add a build step at the end to check that basic http requests are working.

I guess it should look like this:

```
- name: Check HTTP request
  run: |
    # Need to pass environment variables:
    docker run joplin/server:0.0.0-beta node dist/app.js --env dev &

    # Wait for server to start
    sleep 10

    # Here, check the result - it should be valid json
    curl http://localhost:22300/api/ping
```

The goal is to know if basic functionalities are still working when we upgrade, in particular, a Koa package via Renovate

**Comment by pedr** [comment]
I'm creating a PR for this

It seems like we would want to throw an error if the response if different than what we expect. I think there is no need to check the response content, if the curl exit code is 0 it means that the requested worked, if not it means that the server is not working properly, right? 

Not sure if this is enough, to be honest. If we hit a not found endpoint we get a exit code 0 too (but that would still means that the server is running), would be a very weird kind of bug. 

For now I'm going to just check for exit code 0, after that we could use curl to check the http status and body to make sure that everything is working.

For testing the only way is to push new commits, right? Do you know if there is a way to run to only the relevent action?

**Comment by laurent22** [comment]
Yes you need to push a commit to test on CI, although you can manually test the commands on your machine before that.

Please check that the ping command returns the right json text to be extra sure that it works. You're right that normally it should return non-zero on failure but since it's easy to check the json content it's an additional check
