### ISSUE TITLE
Joplin reports "Completed" when network request times out

### ISSUE THREAD

**Issue by darkdragon-001** [laurent22/joplin#8337]
## Environment

Joplin version: 2.10.19
Platform: Linux
OS specifics: Ubuntu 23.04

Joplin version: 2.10.8
Platform: Android
OS specifics: Android 9

## Steps to reproduce

1. Shut down server
2. Synchronize Joplin
3. Get "Completed" message after timeout

The "Check synchronization connection" option in the menu shows "Network request failed".

## Describe what you expected to happen

Joplin should report an error instead of "Completed" which is used for success.

**Comment by Perkolator** [comment]
Duplicate of #6173? (which the repo owners seem to want to automatically close with the stale bot)

**Comment by darkdragon-001** [comment]
Seems similar. Thanks for linking!
