### ISSUE TITLE
Copying an image to Rich Text editor breaks the image link

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8339]
On Discord: https://discord.com/channels/610762468960239627/610762468960239629/1119690647151071446

[See video](https://github.com/laurent22/joplin/assets/1285584/edc3f925-77ef-4415-86e0-6126a20893c7)

**Comment by personalizedrefrigerator** [comment]
This might be fixed -- copy pasting everything from joplinapp.org into the rich text editor then switching notes seems to correctly create image resources.

I'm testing on Ubuntu 23.04 and copying from Firefox.

**Comment by laurent22** [comment]
Ok let's close it then if we can't replicate it
