### ISSUE TITLE
Consider implementing headless API server

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#834]
https://discourse.joplin.cozic.net/t/web-clipper-api-for-cli/725/8?u=laurent

**Comment by sciurius** [comment]
Thank you!

**Comment by hscissors** [comment]
Just to add a use-case to this (if it's needed):
I'd like to have the notes on my laptop and notes on my phone sync, locally and non-locally, the transmission should be encrypted.

**Comment by virtadpt** [comment]
If whatever you're using as your back-end store (WebDAV, etc) supports HTTPS, you should be good to go.

**Comment by foxmask** [comment]
It's in progress mr bot
