### ISSUE TITLE
 can't past when drag & drop text and image  

### ISSUE THREAD

**Issue by sdfsfsfwrt** [laurent22/joplin#8345]
[![Z2hXY.gif](https://imgtr.ee/images/2023/06/19/Z2hXY.gif)](url)
also image cant past when drag & drop 

Joplin version: Joplin-2.10.19.AppImage
Platform: linux 
OS specifics: Xubuntu 22.04.2 LTS x86_64
DE: Xfce 4.16 
WM: Xfwm4 

i go for log but joplin return this 
DevTools failed to load source map: Could not parse content for file:///tmp/.mount_JoplinNRPmUS/resources/app.asar/pluginAssets/mermaid/mermaid.min.js.map: Unexpected end of JSON input

**Comment by shahilsinghyadav** [comment]
I want to do this #8345

**Comment by sdfsfsfwrt** [comment]
No 
Not solved even after last update
