### ISSUE TITLE
Sync interval setting is ignored on Windows and Android

### ISSUE THREAD

**Issue by DBDigital** [laurent22/joplin#8349]
With the Windows client 
Joplin 2.10.19 (prod, win32)
Sync Version: 3
Profile Version: 42
Keychain Supported: Yes
Revision: 1100ab0
Using DropBox as the cloud storage

No matter what I set the sync interval to, it is ignored and it will sync when a note is updated, deleted, or created.  Or at some seemingly random time.   Set it for 24 hours and it syncs quite often.

It is the same on the Android app 2.10.8.  If the sync interval is set to 24 hours, it will sync whenever a note is changed, deleted, created, or possibly at a seemingly random times a sync will be attempted.

## Environment

Joplin version: 2.10.19 (prod, win32)
Platform: Windows 7
OS specifics: 

## Steps to reproduce

1. Set the Sync Interval to disabled.
2. Edit a note, create a note, or delete a note 
3. It will start a sync shortly after the note is edited, created, deleted.  And a sync will happen at seemly random times.  It certainly won't wait 24 hours if you have set for that.  Or if it is set to disabled.

## Describe what you expected to happen
Shouldn't it wait until I hit the sync button to start a synchronization when the sync interval is set to DISABLE?  Many people have limited bandwidth and would prefer to have it only sync when told.  Yes conflicts could happen but that is something I rarely if ever had with Evernote (since 2012) and I had it set to sync manually for every device.  The 3 or 4 times I had conflicts it was one or two notes and easy to see which to keep and which to zap.  If it is a problem with some users forgetting and causing conflicts perhaps make the setting harder to enable with many warnings.

**Comment by Daeraxa** [comment]
The sync interval only applies to the "pull" sync and not the "push" sync.

Basically so long as you have a valid sync target Joplin will still sync on app startup and push any changes out that you make. The interval is only for the "pull" or "fetch" sync that routinely checks for remote changes.

**Comment by DBDigital** [comment]
So fundamentally, it will do a sync (more often than not) no matter what I say.  Drat.  That is  a problem for me (several reasons, but bandwidth being one).  And I was liking Joplin.  Being Joplin seems geared to allowing people to replace Evernote if they wish, it is a bit surprising to see a limited bandwidth situation ignored.

**Comment by Daeraxa** [comment]
Just to point out that my comment isn't making any statement on the other issue you logged about wifi vs mobile data as I would have assumed that setting would be honoured but I don't know for sure.

**Comment by DBDigital** [comment]
Yes I figured, as those are two separate issues, or at least I would assume so.

**Comment by DBDigital** [comment]
The only work-around I have found is to change the sync target to none.  Then switch it back when I want to sync.  Not Ideal and a pain, but does work.

**Comment by DBDigital** [comment]
While I know this is not a bug per se and more of a design choice, but I still think there should be a way to turn off auto-sync.  A hidden switch would be fine, something the casual user wouldn't see or use.  But for some of us, it would be very helpful.  Especially over on Android where the only sync when on wifi vs data often doesn't work and it syncs anyway.

**Comment by DBDigital** [comment]
I will leave one more comment on this situation.  There are many times when auto-sync is a PROBLEM for me.  For example I am working on notebooks, moving notes around or making fast edits in multiple locations at once.  This can get the system confused often has a sync lock failure and I have to try multiple times to clear it.  Now if it just waited until I was done, hey NO PROBLEM.

I have this issue on both Windows and Android clients.  It is even worse on Android and I fight with it to clear the sync lock problem because I am hopping from different apps and sharing notes.

Sure I can turn off syncing entirely by clearing the sync target but this is far from ideal and quite annoying to say the least.  If it would just WAIT until I said sync, it would solve this problem.  I understand developers feel it would create problems with conflicts.  And perhaps it would with some users, but I didn't have conflicts with evernote and I used that since 2014.  Well perhaps one or two, but it was a easy fix.  Which is easy to do with Joplin as well since it also has a conflict system IF it should happen.

How about a hidden option, so the default is auto sync always on but power users that know what they are doing can turn it off?
