### ISSUE TITLE
No search result? → CMD-n won't focus on input

### ISSUE THREAD

**Issue by oknowletssee** [laurent22/joplin#8354]
### Positive example
1. enter a search term which will definitely show search results.
2. hit CMD+n to create a new note
3. One can immediately enter text to the new note

### Reproduce / Bug
1. enter a search term which will definitely NOT show search results.
2. hit CMD+n to create a new note
3. One can NOT enter text to the new note. The search field is still focused

### Expected
See positive example, only without search results.

### Preferred
When entering a search term which is not found in any note it would be great to just hit enter to create a new, blank note with the search term as headline/name. Then focus on the input below. Other note-taking tools like _Notational Velocity_, _nvALT_ and _Logseq_ do this too.

### Environment
Joplin 2.10.19 (prod, darwin)
Client ID: 6257c87217b049be9885d0a6xxxxxxxx
Sync Version: 3
Profile Version: 42
Keychain Supported: Yes
Revision: 1100ab0
Platform: macOS 13.4 (22F66)

**Comment by personalizedrefrigerator** [comment]
> When entering a search term which is not found in any note it would be great to just hit enter to create a new, blank note with the search term as headline/name. Then focus on the input below. Other note-taking tools like Notational Velocity, nvALT and Logseq do this too.

I like that idea!
