### ISSUE TITLE
Lost data -- undo/redo doesn't persist between notes.

### ISSUE THREAD

**Issue by matthias-ccri** [laurent22/joplin#8356]
1. Delete text
2. Switch to another note
3. Switch back to the first note
4. Attempt to undo

Result: you cannot undo

## Environment

Joplin 2.10.19 (prod, linux)

Client ID: ddfa7aca40aa48dd9e846f6f1d5bac2a
Sync Version: 3
Profile Version: 42
Keychain Supported: No

Revision: 1100ab0

Ubuntu 20.04

**Comment by matthias-ccri** [comment]
Would this be classified as a bug or an improvement? You could argue either but I am asking because it affects the status of this Issue.

**Comment by personalizedrefrigerator** [comment]
Leaving it as a bug should be fine — we're now aware of the issue!

It looks like there's also a similar issue when switching between the markdown and rich text editors even if no changes have been made.

**Comment by DCRemi** [comment]
I am also interesting about this bug to be fixed 
I loose many data because of that !!!
