### ISSUE TITLE
eslint `indent` rule not enforcing tab indentation

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#8360]
# Summary
Many TypeScript files in the Joplin monorepo are currently indented with mixed spaces and tabs (e.g. [`types.ts`](https://github.com/laurent22/joplin/blob/dev/packages/app-mobile/components/NoteEditor/types.ts) and [`getResponsiveValue.ts`](https://github.com/laurent22/joplin/blob/dev/packages/app-mobile/components/getResponsiveValue.ts)).

Running `yarn linter path/to/file/with/spaces` has no effect, despite the presence of `'indent': ['error', 'tab'],` in `.eslintrc.js`. Presumably, this rule is not applied to TypeScript files.

# Proposed solution
One option is to use [`@typescript-eslint/indent`](https://github.com/typescript-eslint/typescript-eslint/issues/1824) (which [is what js-draw uses](https://github.com/personalizedrefrigerator/js-draw/blob/81baaec5b67b16f97ee9e5ca8ec4fd8c98f05843/.eslintrc.js#L23)).

Note, however, a metaissue marks `@typescript-eslint/indent` as [broken in many cases](https://github.com/typescript-eslint/typescript-eslint/issues/1824). [A workaround is to disable the rule for a subset of the nodes in the TypeScript AST](https://github.com/typescript-eslint/typescript-eslint/issues/1824#issuecomment-1378327382).

**Comment by laurent22** [comment]
That's interesting, thanks for pointing that out, indeed it looks like the indentation rule was never applied to TypeScript files.

I guess for now we could indeed do what you suggest and implement that workaround
