### ISSUE TITLE
iOS app can’t decrypt notes synced from latest desktop pre-release

### ISSUE THREAD

**Issue by annoyedhumanoid** [laurent22/joplin#8361]
## Environment

Joplin version: 12.11.3
Platform: iOS
OS specifics: 16.5.1

## Steps to reproduce

1. Create a new note or edit an existing one on the latest Joplin desktop version (2.11.11 pre-release)
2. Sync from desktop with encryption enabled
3. Sync on iOS with the correct master password in Encryption Config

## Describe what you expected to happen

The iOS app should be able to decrypt the new/edited note(s) synced from desktop, but they are seemingly permanently stuck on “🔑 Encrypted”. I assume it’s because of [the change to the encryption method (from AES-128 to -256)](https://github.com/laurent22/joplin/issues/7686) in the latest desktop version. I don’t know if this is considered a bug but the forum said in that case to report on GitHub.

## Logfile

![log screenshot 1](https://github.com/laurent22/joplin/assets/46287328/fba0fe34-2c29-485f-8f32-3111be09205f)
![log screenshot 2. I cropped out a bunch of text because I don’t know how much is safe to share](https://github.com/laurent22/joplin/assets/46287328/365b885f-8d05-4e0e-b13a-5dbf10b1cc22)

**Comment by laurent22** [comment]
Hello, please get the latest iOS version. The previous one didn't support the new encryption method, thus the error

**Comment by m-pawelczyk** [comment]
Hello,
I have downloaded latest iOS version and still see in `Encryption config` that 100 elements are not decrypted :/ I have updated Joplin on all devices (MacOS, iOS, Android). I also use synchronisation via Joplin server.
