### ISSUE TITLE
Shortcut icons missing on Android

### ISSUE THREAD

**Issue by PrestigiousBeat6355** [laurent22/joplin#8366]
Shortcut icons are missing in android version
![Screenshot_20230626_174121_One UI Home](https://github.com/laurent22/joplin/assets/76486380/3962a973-48cd-46e7-b367-dd31b078be3a)
![Screenshot_20230626_174404_One UI Home](https://github.com/laurent22/joplin/assets/76486380/a728672e-59cf-41f7-afd5-6ae9bcb24042)

## Environment
Joplin version: 2.10.31
Platform: Android
OS specifics: Android 13

## Steps to reproduce

1. Touch and hold Joplin app icon
2. Shorcut icons are missing.

## Describe what you expected to happen

Shortcut icons to show properly.

**Comment by personalizedrefrigerator** [comment]
Are monochrome icons enabled? If so [this commit](https://github.com/laurent22/joplin/commit/77505e3c752e13ed9fe2e85db0d3bef44f267651) _might_ be related.
