### ISSUE TITLE
Improve error message when a client doesn't know about an encryption method

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8369]
Ask the user to update the app, as that would resolve the issue

**Comment by laurent22** [comment]
@personalizedrefrigerator, I believe we have addressed this now?

**Comment by personalizedrefrigerator** [comment]
I've checked and I don't think we have. 

I originally thought that this message had been changed to suggest upgrading the application
https://github.com/laurent22/joplin/blob/14957b1a0df265c241f79a3b6f801b8c23f6a969/packages/lib/services/ReportService.ts#L213

but it seems that this is not the case (I was likely remembering #8403 or a similar closed PR).

**Comment by laurent22** [comment]
We made several improvements regarding this issue so hopefully now it should be fine. We will also make sure this issue doesn't happen again by releasing the encryption method several months before we make it the default method
