### ISSUE TITLE
drag and drop from note list no longer inserts markdown link

### ISSUE THREAD

**Issue by jjon** [laurent22/joplin#8370]
I just upgraded my Mac (OS 11.7.6) Joplin client to 2.11.11. In the previous version one could drag a note title into a note and the markdown link for the dragged note would be pasted. This no longer works. Was this intended?

It's still possible to copy a markdown link from the contextual menu of a note title, but the drag & drop was useful.

**Comment by personalizedrefrigerator** [comment]
This looks like a bug! I'm in the process of looking for the bad commit. (With 815419260def82dfee33b28a7e48b81e337e0fd8 it doesn't work, with af0136ef3, it does, so the issue was introduced somewhere between those two).

**Comment by personalizedrefrigerator** [comment]
The commit that introduced the issue seems to be 89fc5e19d9f4e7eb426974f0750f18b24e1fdcca. @palerdot Do you have time to/would you like to work on addressing this?

**Comment by jjon** [comment]
This was a useful feature that I used often. It would be a shame to lose it. I can't help thinking the fix might be straightforward.
