### ISSUE TITLE
Joplin's command line tool errors on fresh installation.

### ISSUE THREAD

**Issue by josh-tuik** [laurent22/joplin#8375]
Fresh install of Joplin's command line tool on Fedora 38. I followed the direction here: https://joplinapp.org/terminal/

I get this when attempting to start the application from the command prompt:

> node:internal/modules/cjs/loader:571
>       throw e;
>       ^
> 
> Error: Cannot find module '/usr/lib/node_modules/joplin/node_modules/@joplin/utils/dist/index.js'
>     at createEsmNotFoundErr (node:internal/modules/cjs/loader:1096:15)
>     at finalizeEsmResolution (node:internal/modules/cjs/loader:1089:15)
>     at resolveExports (node:internal/modules/cjs/loader:565:14)
>     at Module._findPath (node:internal/modules/cjs/loader:634:31)
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
>     at Module._load (node:internal/modules/cjs/loader:920:27)
>     at Module.require (node:internal/modules/cjs/loader:1141:19)
>     at require (node:internal/modules/cjs/helpers:110:18)
>     at Object.<anonymous> (/usr/lib/node_modules/joplin/node_modules/@joplin/lib/BaseApplication.js:34:17)
>     at Module._compile (node:internal/modules/cjs/loader:1254:14) {
>   code: 'MODULE_NOT_FOUND',
>   path: '/usr/lib/node_modules/joplin/node_modules/@joplin/utils/package.json'
> }
> 
> Node.js v18.16.0
> 
> 

If it helps at all, there is a .gitignore that excludes/ignores utils/dist, but something appears to reference it. I could be very wrong in my attempt to debug. Thanks for any assistance you can lend.

**Comment by laurent22** [comment]
Hello, please install the app again, that should work now

**Comment by josh-tuik** [comment]
Confirmed! Back to 100% Joplin goodness. Thank you so much for the fix and speed.
