### ISSUE TITLE
Sub-notebooks show up in incorrect parent notebook in CLI

### ISSUE THREAD

**Issue by edhilgendorf** [laurent22/joplin#838]
### Operating system

- macOS

### Application

- Desktop
- Terminal

I'm experiencing an issue where sub-notebooks do not show under the correct parent notebook in CLI. It's fine in mobile and desktop, but does not display correctly for CLI.
Example:
Two notebooks, Work and Personal, each with a couple sub-notebooks. I can create a new sub-notebook in GUI for Personal, then sync, open CLI and it shows the new sub-notebook underneath Work instead.

Is anyone else getting a similar issue? Thanks -- I can open this as a separate issue if needed.
Example(GUI, correct):
![image](https://user-images.githubusercontent.com/7498517/46366648-7cd71380-c630-11e8-8392-f01958525b70.png)

CLI, incorrect:
![image](https://user-images.githubusercontent.com/7498517/46366669-8791a880-c630-11e8-9be7-41e086718470.png)

**Comment by laurent22** [comment]
Which version of the cli client?

**Comment by edhilgendorf** [comment]
joplin 1.0.113 (prod)

**Comment by laurent22** [comment]
Could you try with 116? As this bug should have been fixed in a recent version.

**Comment by edhilgendorf** [comment]
Works perfect! Thank you, I love Joplin. Side note, I'm showing latest version in brew is .113

**Comment by edhilgendorf** [comment]
@tessus thanks, NPM install is how I was able to get the correct version, I only mention Brew since that's what's recommended under the Installation instructions for the MacOS CLI.

**Comment by tessus** [comment]
I've updated the brew formula.

Closing. (Assuming that all issues in this ticket have been resolved.)

**Comment by tessus** [comment]
/ref https://discourse.brew.sh/t/where-are-the-maintainers-listed/3126
