### ISSUE TITLE
Mermaid rendering not automatic

### ISSUE THREAD

**Issue by TC68** [laurent22/joplin#8387]
I use mermaid graphs in my notes quite regularly.

Recently, the mermaid code is displayed instead of the graph in the view pane until text is altered. 

## Environment

Joplin version: Joplin 2.11.11 (prod, linux)

Sync Version: 3
Profile Version: 43
Keychain Supported: No

Email Note: 1.2.2
Link Graph UI: 1.5.0
Quick Links: 1.2.3
Suitcase: 0.2.0
Platform:  Linux
OS specifics:  Pop!_OS 22.04 LTS

## Steps to reproduce

1.  Open an existing note containing a mermaid graph
2.  Graph displayed as text instead of image

Going to the line below \```mermaid in the note and adding \``` triggers the display (as an error) then deleting the new ``` symbols results in the graph displaying correctly and other notes containing mermaid graphs will also be correctly displayed.

This persists without any plugins enabled

## Describe what you expected to happen

Graph is expected to show as an image in the viewer pane without needing to trigger the mermaid rendering

## Logfile

10:03:13: FileApi: list 
Logger.ts:237 10:03:14: FileApi: stat d017e6b6d82d49cf9e7b0c6ee6c68a8e.md
Logger.ts:237 10:03:14: FileApi: get d017e6b6d82d49cf9e7b0c6ee6c68a8e.md
Logger.ts:237 10:03:14: SearchEngine: Updating FTS table...
Logger.ts:237 10:03:15: models/Setting: Saving settings...
Logger.ts:237 10:03:15: models/Setting: Settings have been saved.
Logger.ts:237 10:03:15: SearchEngine: Updated FTS table in 43ms. Inserted: 1. Deleted: 0
Logger.ts:237 10:03:15: Synchronizer: Sync: updateRemote: local has changes: Note: (Local d017e6b6d82d49cf9e7b0c6ee6c68a8e): (Remote d017e6b6d82d49cf9e7b0c6ee6c68a8e.md)
Logger.ts:237 10:03:15: FileApi: put d017e6b6d82d49cf9e7b0c6ee6c68a8e.md null
Logger.ts:237 10:03:15: Saving note... {id: 'd017e6b6d82d49cf9e7b0c6ee6c68a8e', parent_id: '1de66309f11b4edbb4234227e2c9f28e', title: 'mermaid', body: "```mermaid\n\n\n\n\ngraph LR\n%%{init: {'theme':'neutral…ECO warnbox\nclass GW,SV,ECO,OFFSITE greenbox\n```\n"}
useMessageHandler.ts:17 Got ipc-message: noteRenderComplete undefined
Logger.ts:237 10:03:16: Synchronizer: Processing a path that has already been done: d017e6b6d82d49cf9e7b0c6ee6c68a8e.md. sync_time was not updated? Remote item has an updated_time in the future?
Logger.ts:237 10:03:16: FileApi: delete locks/1_1_2e77cc265f47425ea61b4d7b7c1bbadc.json
Logger.ts:237 10:03:17: Synchronizer: Sync: finished: Synchronisation finished [1687996986165]
Logger.ts:237 10:03:17: Synchronizer: Operations completed: 
Logger.ts:237 10:03:17: Synchronizer: updateRemote: 1
Logger.ts:237 10:03:17: Synchronizer: Total folders: 3
Logger.ts:237 10:03:17: Synchronizer: Total notes: 408
Logger.ts:237 10:03:17: Synchronizer: Total resources: 121
Logger.ts:237 10:03:17: Sync has finished and note has never been changed - reloading it
Logger.ts:237 10:03:17: Setting up recurrent sync with interval 300
Logger.ts:237 10:03:17: Updating all notifications...
Logger.ts:237 10:03:17: Garbage collecting alarms...
Logger.ts:237 10:03:18: DecryptionWorker: cannot start because no master key is currently loaded.
Logger.ts:237 10:03:25: SearchEngine: Updating FTS table...
Logger.ts:237 10:03:25: models/Setting: Saving settings...
Logger.ts:237 10:03:25: models/Setting: Settings have been saved.
Logger.ts:237 10:03:25: SearchEngine: Updated FTS table in 42ms. Inserted: 1. Deleted: 0
Logger.ts:237 10:03:35: ResourceService::indexNoteResources: Start
Logger.ts:237 10:03:35: models/Setting: Saving settings...
Logger.ts:237 10:03:35: models/Setting: Settings have been saved.
Logger.ts:237 10:03:35: ResourceService::indexNoteResources: Completed
Logger.ts:237 10:03:35: ResourceService::deleteOrphanResources:

**Comment by personalizedrefrigerator** [comment]
It seems to be working for me (Joplin 2.11.11). If you have any custom stylesheets, try disabling them (while also disabling all plugins) and restarting Joplin.

Note that I'm testing with two mermaid graphs taken from https://mermaid.js.org/intro/.
