### ISSUE TITLE
Android 2.11.31 endless sync / decryption loop

### ISSUE THREAD

**Issue by alondmnt** [laurent22/joplin#8394]
I did a fresh install of the Android app recently, and since then my sync (via Joplin Cloud) is unable to complete. It keeps downloading items in an endless loop. The retrieved item count is way higher than my sync item count in the desktop app sync status, e.g. reaching 7000+ items whereas in the desktop I have 1749. The decrypted item count goes from 1/100 to 100/100 repeatedly.

## Environment

On the mobile (where this happens):

Joplin version: 2.11.31
Platform: Android
OS specifics: v13

On my desktop (where everything is fine):

Joplin version: 2.11.11
Platform: macOS
OS specifics: Ventura 13.4.1

## Steps to reproduce

1. Install Joplin from the app store.
2. Setup the sync target.
3. Sync and wait.

## Logfile

[syncReport-1688064087411.txt](https://github.com/laurent22/joplin/files/11909688/syncReport-1688064087411.txt)

**Comment by personalizedrefrigerator** [comment]
If note history is enabled, it's possible that the 7000+ items are be caused by that.

**Comment by alondmnt** [comment]
I had the same thought, and so I disabled note history on the mobile, and restarted sync. I think that I indeed (somehow, not sure why) have a lot of revisions stored on the cloud. But sync does not seem to regard the note history setting, and items keep being downloaded. I do hope that it will complete eventually, and the progress is just slow due to the many revisions.

Here's my current sync status on Android after hours of syncing.

Note: 401/401
Folder: 23/23
Resource: 32/32
Tag: 66/66
NoteTag: 589/589
Revision: 9403/124
Total: 10514/1235

It's a pretty small database of a total of ~600 notes: 39 MB sqlite, mostly text, almost no resources.

I can also say that the stats above do not only increase, but sometimes also decrease during the sync. Maybe that's expected (but seems a little strange).

Attaching another log:
[syncReport-1688106637681.txt](https://github.com/laurent22/joplin/files/11913627/syncReport-1688106637681.txt)

**Comment by personalizedrefrigerator** [comment]
> Revision: 9403/124

That's a large number of previous versions (about 23 per note)! Decreasing the number of previous revisions on a client like the desktop app, then syncing again should decrease the number of revisions stored on the server.

**Comment by alondmnt** [comment]
I tried exactly that *before* the sync that is documented in the previous comment: went through my active Joplin clients and disabled note history completely (and just in case, set the no. of days to 1). Indeed, on the client the no. of items decreased and I see no revisions. And yet this was the result.

I suspect the following (wild guess): Perhaps the previous Android install (this one is a fresh one), or some other deleted old client, had accidentally a very large no. of days set for revisions (a user error), and for that reason they were saved on the server. I don't know how long they will be kept for on Joplin Cloud before they're deleted. In any case, what surprised me was that during the new, first sync on Android the setting to disable note history is ignored and all revisions are being downloaded.

What I plan to do next, if there is no other choice: clean up Joplin Cloud and upload the database from scratch from one of the desktop clients. The new database will not contain revisions, is that correct?
