### ISSUE TITLE
Exporting to markdown doesn't leave table of contents

### ISSUE THREAD

**Issue by danielb2** [laurent22/joplin#8397]
exporting to HTML & PDF honor the `[toc]` tag, but exporting to markdown does not

## Environment

Joplin 2.11.11 (prod, darwin)

Client ID: 59825d61142446b1992338b2a16a878a
Sync Version: 3
Profile Version: 43
Keychain Supported: Yes

Revision: 6886f6f

Journal: 1.0.11
Publish to Web: 1.1.0
turnToChart: 1.9.3

## Steps to reproduce

1.  right click note and select export -> MD - Markdown

## Describe what you expected to happen

Like the PDF and HTML, the table of contents is expected when exporting to markdown

**Comment by laurent22** [comment]
This is as expected actually, and the reason why we have this disclaimer on the Markdown plugin setting screen:

> These plugins enhance the Markdown renderer with additional features. Please note that, while these features might be useful, they are not standard Markdown and thus most of them will only work in Joplin. 

Basically once you export, it's not Joplin anymore so how special tags, such as `[toc]` are going to be interpreted depends on the Markdown renderer.

**Comment by danielb2** [comment]
Yes, that's why I thought the toc would actually be generated as a markdown toc. MD export isn't following the same format otherwise, so the output is unexpected
