### ISSUE TITLE
Wrong GPS coordinates on Surface Go 2

### ISSUE THREAD

**Issue by guckuck** [laurent22/joplin#8399]
Joplin use a wrong location for new notes on Surface Go 2 with Windows 11

## Environment

Joplin version: 2.11.11
Platform: Windows
OS specifics: 11

## Steps to reproduce

1. Create a new note
2. GPS coordinates are wrong (abount 50 km)

## Describe what you expected to happen

Joplin should use the actual gps coordinates. Under privacy in the windows settings: There is no joplin entry.

**Comment by personalizedrefrigerator** [comment]
The desktop app determines [the user's location from the device's IP address](https://github.com/laurent22/joplin/blob/8eba798cdd6c442b0b17e8314a1a24ed92e08452/packages/lib/geolocation-node.ts#L28), which can be very inaccurate. (The mobile app uses a different method, which should be more accurate).

We might instead use the web [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition) (which [it looks like can be used in Electron](https://github.com/electron/electron/issues/9420)). This API, however, seems to require a Google API key, which might have privacy implications.

Thank you for reporting this!
