### ISSUE TITLE
"splitCommandString is not a function" in joplin CLI, since 2.11.11

### ISSUE THREAD

**Issue by benoliver999** [laurent22/joplin#8401]
## Environment

Joplin version:  2.11.11
Platform: Linux
OS specifics: Arch linux AUR build

---

I am getting the error `splitCommandString is not a function` when

- Trying to open file (vim is set as my editor) with Enter but also `:edit file`
- Trying to quit with `q`

---

My `keymap.json`

```
[
    { "keys": ["l"], "type": "function", "command": "focus_next" },
    { "keys": ["h"], "type": "function", "command": "focus_previous" },
    { "keys": ["k"], "type": "function", "command": "move_up" },
    { "keys": ["j"], "type": "function", "command": "move_down" },
    { "keys": ["s"], "type": "exec", "command": "sync" },
    { "keys": ["CTRL_U"], "type": "function", "command": "page_up" },
    { "keys": ["CTRL_D"], "type": "function", "command": "page_down" },
    { "keys": ["/"], "type": "prompt", "command": "search \"\"", "cursorPosition": -2 },
    { "keys": ["q"], "type": "exec", "command": "exit" }
]
```

My `settings.json`

```
{
	"$schema": "https://joplinapp.org/schema/settings.json",
	"locale": "en_GB",
	"api.token": "xxxx",
	"markdown.plugin.softbreaks": false,
	"markdown.plugin.typographer": false,
	"sync.target": 10,
	"sync.10.username": "xxx",
	"style.editor.contentMaxWidth": 600,
	"editor": "vim"
}
```

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

I have a few questions:
- What version of `node` are you using?
- Is there any additional information about the error in the logs? (I think they're in `~/.config/joplin`).

**Testing I've done so far**: I tested this in debug mode with a single note, and with this setup am not experiencing this issue. I'm building from https://github.com/laurent22/joplin/commit/fbf2fef17c0d8727055b055eff5e60a7236fe3be and also using `vim` on Ubuntu 23.04. 

When I have time, I plan to test with a build from the 2.11.11 commit.

**Comment by benoliver999** [comment]
`node --version` prints `v20.3.1`

Nothing in the logs, the error message just shows up in the text-bar on the bottom left of the terminal.

I guess there's something with `type: exec`. I can't call `:sync` either but navigating up/down/left/right works.

When I try to search, `/` brings up the search box (as set in my config) but hitting enter brings up the error again.

**Comment by laurent22** [comment]
There's no CLI version 2.11.11, so we'd need to know the real version number. I believe this bug has been fixed in the latest release, but again we need to know what version you have

**Comment by benoliver999** [comment]
Ah my mistake sorry. I used the one here https://aur.archlinux.org/packages/joplin

When I run `joplin version` I get this

```
(process:3806): VIPS-WARNING **: 16:06:22.871: unable to load "/usr/lib/vips-modules-8.14/vips-openslide.so" -- libopenslide.so.0: cannot open shared object file: No such file or directory
Cannot find module './package.json'
Require stack:
- /usr/share/joplin/node_modules/joplin/app/command-version.js
- /usr/share/joplin/node_modules/joplin/app/app.js
- /usr/share/joplin/node_modules/joplin/app/main.js
```

I wonder if it's an AUR packaging issue

**Comment by laurent22** [comment]
It could be. I have the latest version and it works fine, but the version before that was broken. Maybe check with them to see if they have updated to the latest which should be 2.11.1

**Comment by benoliver999** [comment]
Closing this out, smells of distro packaging issue. The app works fine when I install with npm directly.
