### ISSUE TITLE
Recent notes created on android not decrypting on Windows app

### ISSUE THREAD

**Issue by davidfraser** [laurent22/joplin#8406]
## Environment

_Android app_
Joplin version: 2.11.31
Platform: Android
OS specifics: Xiaomi phone running Android 10 QkQ1.190828.002, MIUI 12.0.3
Database v42
FTS enabled: 1
Hermes enabled: 1

_Windows desktop_
Joplin version: 2.10.9 (installed with Chocolatey)
Platform: Windows
OS specifics: Windows 11 Home 22H2
Sync Version: 3
Profile Version: 42
Keychain supported: Yes
Revision: 1100ab0

## Steps to reproduce

1. Create a new note in Android
   * ![IMG_20230703_074555.jpg](https://github.com/laurent22/joplin/assets/356451/2ba190f6-5ac1-4e3c-b16a-f6de06e8ff39)
2. Synchronize from Android (using OneDrive for synchronization)
3. Synchronize from Windows Desktop
4. Note shows up as Encrypted, with a warning that says they couldn't be decrypted multiple times:
   * <img width="126" alt="image" src="https://github.com/laurent22/joplin/assets/356451/4089e26a-f439-4446-83ab-322ca86a033f">
   * <img width="260" alt="image" src="https://github.com/laurent22/joplin/assets/356451/a26dca98-9400-4d00-bb55-1ac2a7e797e6">
   * <img width="285" alt="image" src="https://github.com/laurent22/joplin/assets/356451/c81b1c04-0f2a-43db-b7b2-ac6f49600897">
5. Creating a note on Windows and syncing to Android works successfully and the notes are decrypted without a problem

This happened recently; I was using version 2.9.17 on Windows desktop so tried upgrading to 2.10.x but problem remains.

Windows sync status shows 0/1 for Master Key:

<img width="272" alt="image" src="https://github.com/laurent22/joplin/assets/356451/90164916-f399-4b68-b999-2b306cd25559">

But the encryption config does show a key:
<img width="620" alt="image" src="https://github.com/laurent22/joplin/assets/356451/41392918-668f-4a56-b8b4-55a9413e553e">

Android configuration shows a matching key ID:
![Screenshot_2023-07-03-07-43-34-172_net.cozic.joplin.jpg](https://github.com/laurent22/joplin/assets/356451/38925a4f-9730-4d65-9d8f-e8866f3d5113)

## Describe what you expected to happen

Bidirectional encryption and decryption between Windows app and Android app, as has been working since setting this up in 2021

## Logfile

In the debug log, I found messages like this:
```
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Logger.js:205 07:53:38: DecryptionWorker: starting decryption...
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Logger.js:205 07:53:38: DecryptionWorker: error for: 175da5045b4f4482bafdbc47831415c8 (notes) Error: Unknown decryption method: 7
    at EncryptionService.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\e2ee\EncryptionService.js:376:23)
    at Generator.next (<anonymous>)
    at C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\e2ee\EncryptionService.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\e2ee\EncryptionService.js:4:12)
    at EncryptionService.decrypt (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\e2ee\EncryptionService.js:369:16)
    at EncryptionService.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\e2ee\EncryptionService.js:443:46)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\e2ee\EncryptionService.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5) {id: '175da5045b4f4482bafdbc47831415c8', parent_id: '324e95805df04343b516bbbd6b343693', title: '', body: '', created_time: 1688276375289, …}
```

Full debug log attached:
[joplin-debug-1688363653083.log](https://github.com/laurent22/joplin/files/11933570/joplin-debug-1688363653083.log)

**Comment by davdr** [comment]
I believe this is due to a recent change to use AES-256 for new or updated notes, instead of the former default of AES-128 (https://github.com/laurent22/joplin/issues/7686). Updating the Windows installation of Joplin and retrying the decryption will probably solve it.

**Comment by davidfraser** [comment]
Yes, that looks like it, attached debugging notes. The error message says "Error: Unknown decryption method: 7"

**Comment by davidfraser** [comment]
It would be great to have news like this posted on the news page - since updating the algorithm is an infrequent operation, I went there to look and see if there'd been any recent changes but didn't see any. Didn't think to look on Twitter :)

**Comment by davidfraser** [comment]
Upgrading did indeed fix this
