### ISSUE TITLE
Add support for plugin icons

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8408]
We'd like to allow the plugin developers to specify an icon for their plugin in manifest.json. Please investigate what would be a good format for that icon (for example by checking what they do on the Chrome Store or Firefox Addons), and add support for it.

**Comment by hubertfilho** [comment]
I've found these articles about icons in plugins in the

Chrome web store:
https://developer.chrome.com/docs/extensions/mv3/manifest/icons/
https://developer.chrome.com/docs/webstore/images/#icons

and

Firefox Addons:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/icons

As I understand these icons are going to be display on the plugins page inside the Joplin app. Right? Are they going to be displayed in somewhere else?

If they'll be display only inside Joplins application I believe, basically, that we just need to define the extension of the images and the sizes that we'll need. And of course, there're some good practices about the spacing, shade, perpspective of the icons etc. The google article can give us some good insides about that.

**Comment by hubertfilho** [comment]
Update

As our applications runs on Chromium, we could stick with the same pattern from Chrome web store. Does this sound like a good idea?

**Comment by laurent22** [comment]
Yes I think using something similar to what's in the Chrome extension manifest would make sense

**Comment by hubertfilho** [comment]
Nice. Let's go to this path, then.
