### ISSUE TITLE
Markdown footnotes changed with unknown syntax, how to prevent or revert back 

### ISSUE THREAD

**Issue by kklepper** [laurent22/joplin#8410]
I work for weeks on a lengthy report with footnotes. Yesterday, I noticed that the Markdown syntax has changed from

example: 
**Anreicherung.^[**Anlage** mikrobiologischer Befund-2022-04-07.pdf]** 
to
**Anreicherung.<sup>[\[7\]](#fn7)</sup>**

Also, the mechanism of jumping to footnotes and back to text did not work anymore both in PDF and published versions.

I never had this phenomenon before. The breaking version had an unusual number of changes: 
signature **02.07.2023 16:25 (-48111, +52807)**

I don't know how this happened and how to revert this behavior, I resolved the issue by restoring to the version prior to that, identifying changes and reentering the changes since manually.

How can I prevent this from happening again and how to revert more easily?

I  upgraded to version 2.11.11, I don't know when. Since I had troubles the last time when upgrading which I resolved by muting my 3 plugins, I did so this time again beforehand. I remember that I enabled them again and upgraded with no problem, but somehow I must have been prompted to do so - I don't remember why.

![image](https://github.com/laurent22/joplin/assets/6130319/7cc68025-37d9-4575-80e9-136ffa42af73)

## Environment

Joplin version: 2.11.11
Platform: Windows
OS specifics: Windows 10 Pro Version 22H2 build 19045.3086

## Steps to reproduce

1.  Sorry, I don't know how this happened and am anxious to fool around to find out
2. 
3. 

## Describe what you expected to happen

keep the old syntax

## Logfile

As long as I cannot reproduce, it makes no sense to enable debugging.

**Comment by personalizedrefrigerator** [comment]
Do you use the rich text editor? (The rich text editor is known to change markdown formatting as it converts to/from HTML when editing).

**Comment by kklepper** [comment]
> Do you use the rich text editor?

Not that I know of, but that could be an explanation, thank you. I don't even know how to change the editor but I will be on my guard.

**Comment by personalizedrefrigerator** [comment]
The "toggle editors" button switches between editors.
![image](https://github.com/laurent22/joplin/assets/46334387/bd6580f7-8c5e-4393-8c0a-eac4b5114d1f)


When I tested it, however, it transformed
```
Test.^[This is a test of footnotes]
```
into
```
Test.<sup>[\[1\]](#fn1)</sup>

* * *

1.  This is a test of footnotes [↩︎](#fnref1)
```

Thus, I think that the issue has a different source.

**Comment by kklepper** [comment]
Thanks a lot for the clarification! So I just didn't understand basic concepts. My sincere apology!

**Comment by personalizedrefrigerator** [comment]
> Thus, I think that the issue has a different source.

My apologies! I meant that the rich text editor changed the footnote format in a different way from what was listed above. Thus, this is probably not caused by the rich text editor.

I'm re-opening the issue and will keep trying to replicate it.

Thank you for reporting this!
