### ISSUE TITLE
Sync issues with encrypted notes - note name shows "Encrypted" in title, no content visible

### ISSUE THREAD

**Issue by Timoses** [laurent22/joplin#8412]
I use encryption on all my devices, successfully so far.
I updated a note in Desktop App.
Now, after syncing, my mobile app shows "Encrypted" as note title with a key symbol to the left. I can not open the note.

I then updated my mobile App. 
Also, I disabled Encryption (while disabling Wifi and mobile data) and re-enabled it again.

## Environment

Joplin version: Joplin 2.11.11 (prod, darwin)
Platform: MacOS
OS specifics: BigSur 11.7.3 (20G1116)

Joplin version: 2.11.31   (previous version before update to this version unknown, should have at least been updated a month ago) 
Platform: Android
OS specifics: Android v8

## Steps to reproduce

1. Update note in Desktop App and Sync
2. Sync on mobile app
3. See "Encrypted" note as title. The old (unencrypted) note on the mobile was auto-removed. Info: Other notes that have not been updated are shown as before (not as "encrypted" title).

## Describe what you expected to happen
See the unencrypted notes as previously.

## Logfile

Let me know if you need more logs than these ones from mobile:
![image](https://github.com/laurent22/joplin/assets/6923843/0808695f-3f0b-4390-bc26-f84584a59b5b)
![image](https://github.com/laurent22/joplin/assets/6923843/4fde85ec-9932-4a6c-a672-a85feb9870fc)

**Comment by Timoses** [comment]
Found related issue (but quite old): https://github.com/laurent22/joplin/issues/2966

**Comment by laurent22** [comment]
Please update your Android app, as you need the latest version to decrypt the notes from the desktop app

**Comment by Timoses** [comment]
@laurent22  I actually did.
I am using F-Droid.

**Comment by WeirdCircumstances** [comment]
Same issue here. Using the f-droid version. I did not changed anythin execept the updating to the new version. 
![Screenshot_20230709-223020](https://github.com/laurent22/joplin/assets/6939992/47898320-44cb-4e5b-a492-9f0d39fd1562)
