### ISSUE TITLE
JoplinCloud not Syncing on Android 5.0.1 ?

### ISSUE THREAD

**Issue by Beltrando** [laurent22/joplin#8413]
## Environment

Joplin version: 2.11.31
Platform: ANDROID 
OS specifics: Android 5.0.1 (Huawei Mediapad X2 without 4G)

## Steps to reproduce

1. Fresh installation of Android 5.0.1 (Huawei Mediapad X2 Reset to factory settings)
2. Wifi connexion
3. Fresh installation of Joplin 2.11.31
4. Configuration / Sync / Joplin Cloud email & password 
5. Check Sync

## Describe what you expected to happen
Sync is not working !
I get an error : "Network Request Failed"

## Logfile

[syncReport-1688459681714.txt](https://github.com/laurent22/joplin/files/11946952/syncReport-1688459681714.txt)

**Comment by laurent22** [comment]
Android 5.0 has been discontinued for 6 years now so we don't really support it. But perhaps it's a problem with the outdated root certificates, which you could fixed as described here: https://android.stackexchange.com/a/232051/38089
