### ISSUE TITLE
Notes not uploading to dropbox on ios after deleting all data from dropbox manually

### ISSUE THREAD

**Issue by ta0ma0** [laurent22/joplin#8419]
## Environment

Joplin version: 12.11.5
Platform: IOS
OS specifics: 16.5.1

## Steps to reproduce

1. Disable desktop APP sync
2. Disable IOS APP sync
3. Delete all Joplin data on Dropbox
4. Resetup sync in IOS APP with Dropbox
5. Start sync in IOS APP
6. Nothing, data not upload in Dropbox, Status in APP complited.

## Describe what you expected to happen
Expected that the data from the phone will be loaded into the dropbox

## Logfile

![photo_2023-07-06_12-20-52](https://github.com/laurent22/joplin/assets/15641919/99b685d2-9a85-4e97-9df9-ceb3b8647828)

**Comment by roman-r-m** [comment]
You're not supposed to delete data manually and sync. You're lucky Joplin didn't delete your local data.

To give a bit more detail: when Joplin tries to sync and sees that you have a note locally but not on Dropbox it can either upload to Dropbox or assume the note has been deleted by another client and delete locally as well. The way to resolve this is by comparing the note's last update time vs last sync time. From your description it sounds like it should have deleted it.

**Comment by ta0ma0** [comment]
We are talking about absolutely all notes, they have different update times, but invariably earlier than the synchronization time. I suspect if you connect a cloud that was not configured before, for example, a onedrive, then the note will be uploaded there. But I want to use dropbox.

**Comment by ta0ma0** [comment]
No, when I'm connect APP to OneDrive, notes start deleted locally, I stopped sync and disconnect Cloud, for save my notes. this is a difficult situation for me, because records for many years in unencrypted form are only locally on the iPhone and I would really afraid to lose them.

**Comment by personalizedrefrigerator** [comment]
Is there a recent backup of your notes?

If not, I can try to implement JEX (Joplin Export File) export on mobile so a backup can be made. This might take a while (a few weeks), though!

**Edit**: Pull request: https://github.com/laurent22/joplin/pull/8428

**Comment by ta0ma0** [comment]
Unfortunately there is no backup. I will wait and hope.

**Comment by ta0ma0** [comment]
Thank you for your message and attention. The problem remains the same. All notes for several years, saved only in the version for the smartphone. So far, I don't know how to backup them and transfer them to the desktop application. I exported a few especially important messages via sharing.

**Comment by personalizedrefrigerator** [comment]
A pull request that adds the ability to export to JEX has been merged. It still might take a while for it to be released, though.

Relevant commit https://github.com/laurent22/joplin/commit/6ce88657194b2cd0d9e4e0de537cf1c270946edf

**Comment by ta0ma0** [comment]
I'm sorry. Any news?

**Comment by personalizedrefrigerator** [comment]
JEX export is in the latest version on iOS!

To export, open "Configuration" the scroll down to "Export all notes as JEX":
![screenshot: export all notes as JEX](https://github.com/laurent22/joplin/assets/46334387/a706238a-0b59-439b-a5c8-6c149d10dfb8)

The resultant JEX file can be imported by the Joplin desktop application.

**Comment by ta0ma0** [comment]
Wow! Great! All notes restored. Thank you.

**Comment by ta0ma0** [comment]
In iOS app after restore notes in desktop created doublicates notepades. In iOS app i'am not find function delete all and redownload notes. After reinstall app on smartphone and connect Dropbox, ios client start delete notes in Dropbox cloud  it's unexpected.

**Comment by ta0ma0** [comment]
Thanks again guys. Donate or subscribe to the cloud from me, as it will be.
