### ISSUE TITLE
Provide option to auto-detect external editor exit

### ISSUE THREAD

**Issue by tsumare** [laurent22/joplin#842]
### Operating system

- Windows
- macOS
- Linux

### Application

- Desktop

### Request

Provide an option which will automatically detect when a compatible external editor has exited and finalize the updates automatically without further user interaction.

vim/gvim for instance provides the `-f` flag to support this type of behavior.  It is quite likely other editors can be configured in a similar manner.  Allowing the option of enabling this sort of check will streamline the user experience somewhat as far as external editing is concerned.

```
       -f          Foreground.   For  the  GUI  version, Vim will not fork and 
                   detach from the shell it was started in.  On the Amiga, Vim 
                   is  not restarted to open a new window.  This option should 
                   be used when Vim is executed by a program  that  will  wait 
                   for  the  edit session to finish (e.g. mail).  On the Amiga 
                   the ":sh" and ":!" commands will not work.                  
```

**Comment by laurent22** [comment]
What would be the benefit of this option? Currently if you open a note in an external editor and close it, you go back to Joplin and you can switch notes, keep editing the note, etc. There's nothing blocking, so I'm wondering what would be the goal of this feature?

**Comment by tsumare** [comment]
I had noticed that the icon changes to a "waiting" state when I open the editor, but doesn't notice when I closed it unless I click it again.  I was worried that if I forgot to turn it back off or went back to editing the contents of the note directly something might not save or end up getting out of sync.  (I tend to only use an external editor for more complex replacements or reformatting.)  If this isn't the case, then I apologize for my confusion, and you can simply close this issue.  Thanks

**Comment by laurent22** [comment]
Yes the note is actually saved regardless of the waiting state and whether you click on the button or not.

I'm going to remove the state from the button actually as it doesn't provide useful information, and can indeed be confusing.

**Comment by laurent22** [comment]
External edition has been improved in the latest release.
