### ISSUE TITLE
Android, BT Spanish keyboard and new editor: writing an accented vowel, when using a Spanish BT keyboard, deletes all previously written letters of the word.

### ISSUE THREAD

**Issue by RBauglir** [laurent22/joplin#8421]
When writing in Spanish with a bluetooth keyboard in the Android app with the new editor, you're writing a word and when you write an accented vowel all previously written letters of that word disappear. It doesn't happen when you switch to the old editor.

## Environment

Joplin version: 2.11.31, but happens with prior versions too.
Platform: Android.
OS specifics: crDroid 9.6 (A13).

## Steps to reproduce

1. Open Android app and open or create a note and enter edition mode with the default new editor.
2. (or 1., the order doesn't matter) Connect a bluetooth keyboard and configure it to Spanish (my keyboard has Spanish layout but maybe it can be tested with any other layout). It doesn't matter if you connect the keyboard before or after opening the app.
3. Begin to write a word or simply write some characters without spaces.
4. Write an accented vowel as part of the same word and all previously written letters of that word (until previous space) will disappear.
5. Go to app's "Configuration" and switch on "Use the plain text editor" which actually switches to the old markdown editor and not to the plain one.
6. Enter edition mode within a note and write words with accented vowels without problems. 

## Describe what you expected to `happen`

The accented vowels should be written without affecting previously written letters of that word.

**Comment by personalizedrefrigerator** [comment]
The new editor uses CodeMirror internally. Does this also happen with the online CodeMirror editor? (https://codemirror.net/)

I've also noticed that the software keyboard I have configured can change how BlueTooth keyboard input is handled. What software keyboard are you using? 

Edit: With the `Español (US)` layout on Android 13 and a bluetooth keyboard, I am not experiencing this issue.

**Comment by RBauglir** [comment]
> The new editor uses CodeMirror internally. Does this also happen with the online CodeMirror editor? (https://codemirror.net/)

Yes, exactly the same happens within the CodeMirror field at codemirror.net, so I suppose this issue should be moved to codemirror's Github. Please, tell me if you want me to copy/link this issue to CodeMirror's repo or in you want to do it yourself (or any other Joplin dev) to give them more information.

I'm using AOSP keyboard and I'm only experiencing this problem with Joplin so it doesn't seem to be a matter of keyboard configuration. My keyboards (soft and hard) are `Español (ES)` (Spain).

**Comment by personalizedrefrigerator** [comment]
CodeMirror uses a web-browser's built-in `contenteditable` edit field internally.

[The MDN web docs have an example `contenteditable` field](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable). Does this issue also happen with that `contenteditable` field?  

The `contenteditable` field can be found in the "output" section of the "try it" portion of the page. 
![contenteditable field circled in the documentation](https://github.com/laurent22/joplin/assets/46334387/362b4c76-323a-46dc-83e9-1ab02c9a24c3)

**Comment by RBauglir** [comment]
Yes, it happens the same within the Mozilla webpage, in both the output `contenteditable` field and the input field (both HTML and CSS tabs). BUT I've done a bit deeper research and have realised that **this problem happens with Chrome (actually tested with Brave) and Android Browser (WebView afaik) but NOT with Firefox (actually tested with Fennec F-Droid and Mull).**

Edit: as I understand this problem should not happen within the input field at Mozilla's webpage I've performed more tests and found out that it happens within every text field, and not only `contenteditable` ones, as e.g. with these Github comment boxes. I'm testing with more devices...

Edit 2: I've performed tests with a Samsung stock device and have found no issues, so it seems to be a problem with my main device. I suppose Joplin uses WebView underneath and I don't normally use WebView nor Chrome browsers (I normally use Firefox browsers which don't have this problem) so I didn't know the roots of the problem. Thank you very much for you support and I apologize for the inconveniences. I think we can close the issue.

**Comment by personalizedrefrigerator** [comment]
Another thing to check: Are there any updates available for Chrome/the system WebView?

**Comment by RBauglir** [comment]
> Another thing to check: Are there any updates available for Chrome/the system WebView?

I use Android System Webview version 114.0.5735.131 and last one seems to be 114.0.5735.196, but I don't update via Play Store (I don't use Gapps) but with the OTAs. And I don't have Chrome installed in my device.
