### ISSUE TITLE
soft-breaks not persistent

### ISSUE THREAD

**Issue by ajay-gh** [laurent22/joplin#8430]
## Environment

Joplin version:  desktop v2.11.11
Platform: Macos
OS specifics: Monterey 12.6.4

## Steps to reproduce

1. create a new note in the WYSIWIG editor
2. write any short text, add a soft-break (  as <shift><return> 
3. write more text
4. open another note, then go back to the note just created

## Describe what you expected to happen
a) at first the new note looks as expected, the soft-break creates a new line, line spacing is smaller than when you added a hard break
b) after switching back to the note just created, the line break is no longer shown, all text flows continuously across the window
I do not see (or change) an app setting which could cause such problem.

## Logfile

I do not believe that a logfile is needed / relevant in a case like this, but let me know I am wrong, and I will add it.
I am using the following plug-ins: simple-backup 1.3.0, favorites 1.3.0, and conflict resolution 1.2.3. None of these, given their nature, seems to play a role. If useful, I will try to recreate the problem with a fresh copy of Joplin without any plug-ins installed.

**Comment by personalizedrefrigerator** [comment]
It seems to work for me (Joplin 2.11.11/Linux, no plugins/custom CSS):

[Screencast from 2023-07-07 13-14-38.webm](https://github.com/laurent22/joplin/assets/46334387/71ebde6e-7dd5-4999-8e5f-5242205e4cde)

Please try to replicate on a fresh copy of Joplin.

**Comment by ajay-gh** [comment]
On one hand, that is good to know, on the other hand ... Linux is not Mac, and I tried on 2 different machines. same result.
Thanks for your response anyway.

**Comment by personalizedrefrigerator** [comment]
I'm hopeful that I'm not trying to replicate this correctly. (Or maybe something like language/accessibility/keyboard settings are making the difference). Here's how I'm testing this on MacOS:

https://github.com/laurent22/joplin/assets/46334387/996fc1de-a017-4058-9daa-d1f81106ba36

I'm creating the soft-breaks with Shift+Enter.

Version information:
<img width="265" alt="Joplin 2.11.11" src="https://github.com/laurent22/joplin/assets/46334387/d08868ae-99f0-42a9-846f-6e32b5b10804">

More information:
- I'm using an en-US keyboard with Joplin's language set to `English (United Kingdom)` and have tested with plugins both enabled and disabled.
- MacOS Ventura 13.4.1
- x86_64 processor


Thank you for testing it on another device!

**Comment by personalizedrefrigerator** [comment]
I had soft breaks disabled!!! (I can reproduce this now!!!)

Sorry for the confusion. I plan to work on a fix some time during the next few days.

**Comment by laurent22** [comment]
Was that actually a regression or a bug that was always here?

**Comment by ajay-gh** [comment]
If your question concerns the comments on tags by personalizerefri...
I cannot answer that question. But if you are asking about Joplin as seen by a user : this problem did not show at all some months ago in any older versions of Joplin. Unfortunately I cannot pinpoint the exact version of Joplin when it started.

**Comment by personalizedrefrigerator** [comment]
I just tested with the [2.8.8 AppImage](https://github.com/laurent22/joplin/releases/tag/v2.8.8) and the issue seems to be present (though I could be testing incorrectly...).

[Screencast from 2023-07-13 11-38-43.webm](https://github.com/laurent22/joplin/assets/46334387/b54cdc56-a1cf-444e-8418-f17863608ca4)

I think I remember the rich text editor inserting `<br/>`s though... It's possible the issue was fixed after 2.8.8 and then has regressed since then.
