### ISSUE TITLE
Bullet items nested under checkboxs render incorrectly with WYSIWYG editor

### ISSUE THREAD

**Issue by dkonigsberg** [laurent22/joplin#8431]
I frequently create bullet-list items under elements in a checkbox list, often to provide extra details or clarifications on a particular checkbox item.  I've found that the Joplin WYSIWYG editor renders these nested elements incorrectly, as a square with an off-center circle inside of it.  Meanwhile, the preview pane of the Markdown editor seems to render these items correctly.

Here's the Markdown editor side-by-side preview:
![Screenshot from 2023-07-08 08-07-11](https://github.com/laurent22/joplin/assets/1144556/7d72421b-4a83-4c32-9c37-1c0754b6dbdb)

And here's the WYSIWYG editor:
![Screenshot from 2023-07-08 08-07-19](https://github.com/laurent22/joplin/assets/1144556/81849997-40d8-4765-9955-c8c861d26ee4)

And here's markdown code that can reproduce this:
```
- [ ] One
    - Red
    - Green
    - Blue
- [ ] Two
    - Alpha
    - Beta
    - Gamma
- [ ] Three
- [ ] Four
```

## Environment

Joplin version: 2.11.11 (prod, linux)
Platform: Linux
OS specifics: Pop!_OS 22.04 LTS

(Note: Issue also reproduces on Windows 11, and does not appear to be platform-specific.)

## Steps to reproduce

1. Create a note with the Markdown editor
2. Add a bulleted list (see above snippet)
3. Add checkboxes to the top-level elements of that list (see above snippet)
4. Note the preview window
5. Switch to the WYSIWYG editor
6. Note the displayed contents

## Describe what you expected to happen
I expect non-checkbox elements that are children of checkbox elements to render with normal bullet points, regardless of which editor mode I'm using.

**Comment by Daeraxa** [comment]
It's a known limitation of the editor:

https://github.com/laurent22/joplin/issues/4286

https://joplinapp.org/rich_text_editor/

> All items in a list must be of the same type, so for example all checkboxes, or all bullet points. If you require two different types, you should create two different lists separated by a horizontal rule or similar.

**Comment by dkonigsberg** [comment]
Being a known limitation does not mean it isn't a problem.  Just that its a problem you already know about, and added a doc note alerting people to.
As many have apparently complained about this limitation before, at what point does it transition from a "known limitation" to a "to-do item to eventually fix"?  Or is the Rich Text Editor an external component developed elsewhere?
