### ISSUE TITLE
Notebook can not be moved back as top-level one

### ISSUE THREAD

**Issue by ayanamist** [laurent22/joplin#8432]
## Environment

Joplin version: 2.11.11
Platform: win32
OS specifics: Win10

## Steps to reproduce

1. Use mouse to move a notebook as another notebook's sub notebook
2. Use mouse to move it back as top level notebook
3. But can't finish it because moving is invalid.

## Describe what you expected to happen
Successfully move it back as top level notebook

**Comment by Daeraxa** [comment]
Did you drag it back to the `NOTEBOOKS` header?

**Comment by ayanamist** [comment]
@Daeraxa Thank you! Yes it works.
