### ISSUE TITLE
Possibility to select which layouts are in "layouts cycle"

### ISSUE THREAD

**Issue by theerror** [laurent22/joplin#844]
Operating system: macOS
Application: Desktop

I would like to be able to select which layouts will be available during switching (ex. only read view and full screen edit) or, the best way I can imagine, would be system of view/edit modes, where you select you preferred way of editing (like Laverna have, for example).

1) View layout as default for all notes during viewing (markdown)
2) Whenever you want to edit note, just press edit button (or click into note, or press shortcut) and based on option, you have set in preferences, you will see the split edit or fullscreen edit layouts.

For me it makes much more sense, then "cycle of layouts".

**Comment by theerror** [comment]
From my point it's not stale at all. A really would like to have it, but not a developer, to help, however. :(

**Comment by laurent22** [comment]
I didn't see this issue and created a duplicate there: #1900. I'm going to close this issue in favour of the other ones since someone started working on it.
