### ISSUE TITLE
Joplin crashes at Launch

### ISSUE THREAD

**Issue by symisz** [laurent22/joplin#8443]
Joplin just crashes at Launch, although this doesn't happen all the time.
I opened the dev tools and see that Joplin failed to connect to the sqlite database.
Once it crashed at launch, I'm unable to start Joplin it again after force closing it.
Only a OS restart would make Joplin to open normally again, unless it get this bug.

```
Uncaught Error: ENOENT, node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-x64\node_sqlite3.node not found in C:\Users\xxx\AppData\Local\Programs\Joplin\resources\app.asar
```

## Environment

Joplin 2.11.11
OS Name	Microsoft Windows 11 Pro,
Version	10.0.22631 Build 22631

**Comment by personalizedrefrigerator** [comment]
Does `C:\Users\YOUR_USERNAME_HERE\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-x64\node_sqlite3.node` exist?

**Comment by symisz** [comment]
yes the path to the file exist
