### ISSUE TITLE
Sync between Android and Windows app via Joplin Server has broken encryption

### ISSUE THREAD

**Issue by mu88** [laurent22/joplin#8445]
Dear @laurent22 

I've been running my own Joplin Server instance within Docker for several months. As clients, I'm using the Android and Windows app. Probably with the Android app's latest version, encrypted notes created on Android can no longer be decrypted on Windows.

When syncing into the other direction (from Windows to Android), items can still be properly decrypted and displayed.

It this has been working for several months until now, so I assume it to be a regression.

Updating Joplin Server from `2.9.x` to `2.11.x` didn't solve the issue.

## Environment

| Joplin version | Joplin type | Platform | OS specifics                     |
|----------------|-------------|----------|----------------------------------|
| 2.11.2         | Server      | Linux    | Bullseye (arm64), Raspberry Pi 4 |
| 2.10.19        | Client      | Windows  | Windows 11                       |
| 2.11.31        | Client      | Android  | Android 12                       |

## Steps to reproduce

👉🏻 Ensure that encryption is enabled 👈🏻
1. Create note within the Android app.
2. Sync to the server.
3. Sync with the Windows app.

## Describe what you expected to happen

The note should be properly decrypted so that it can be read.

## Logfile

The _Joplin - Synchronization Status_ on Windows is:
```
Items that cannot be decrypted
Joplin failed to decrypt these items multiple times, possibly because they are corrupted or too large. These items will remain on the device but Joplin will no longer attempt to decrypt them.
 
Note: 924e7ef3c6bf4bf2a0c25d502fd1e4c6 Retry
Note: b1b3876d87824cf4892106ea87b3d121 Retry
Note: 2e0c158b3a94467c8a0414d911acbde7 Retry
Note: a8db14545d584c0dbe3f49775eca867b Retry
Retry All
```

**Comment by Daeraxa** [comment]
https://discourse.joplinapp.org/t/if-you-have-an-issue-with-encryption-please-read-this/31552

**Comment by mu88** [comment]
Thank you for your quick reply. Are you the owner of the Chocolatey package? https://community.chocolatey.org/packages/joplin
If yes it would be cool to update it as well because I'm managing all my installed software via Chocolatey.

**Comment by Daeraxa** [comment]
No, the only official distributions are the downloads from https://joplinapp.org/help/#desktop-applications (i.e. for Windows the install and portable `.exe`s). We do link to it on our [community distributions](https://discourse.joplinapp.org/t/unofficial-alternative-joplin-distributions/23703#desktop-windows-3) page but we aren't involved with its maintenance.
