### ISSUE TITLE
If you have a problem with encryption, please read this first!

### ISSUE THREAD

**Issue by Daeraxa** [laurent22/joplin#8446]
https://discourse.joplinapp.org/t/if-you-have-an-issue-with-encryption-please-read-this/31552

Encryption was recently upgrade to use AES-256 so any app you upgrade will start using this. The problem is that apps you do not upgrade will see these encrypted notes, and will not know how to decrypt them. That will result in encryption-related errors such as a `Unknown decryption method`.

- First, **there is no risk for your data**. It cannot currently decrypted but it still there and it is not corrupted

- To ensure you can decrypt those notes, make sure you update all your apps. If you did so, and it still doesn't work double-check your version number. It should be:
    - Desktop: 2.11.11
    - Android: 2.11.1
    - iOS: 12.11.5
    - CLI: 2.11.1

- All the official releases are up-to-date however some non-official channels have not updated their releases. In that case, contact the developer for that channel, or directly install our official release.

- Once you start the upgraded version there may be some items that need to be manually processed for decryption. To do so, in the **desktop app**, go to `Help => Sync status` and click on "Retry all". In the **mobile app**, go to to the configuration screen, scroll down to the "Sync status" button, then press "Retry all".

Any question, feel free to ask on the forums or discord.

**Comment by mistermoutan** [comment]
Thanks! I updated the apps but was not aware that you need to manually retry the decryption :)

**Comment by frenciszak** [comment]
>> First, there is no risk for your data. It cannot currently decrypted but it still there and it is not corrupted
NOT TRUE! 
Cannot descrypt my notes manually ! 
Each time I run the app on one of my devices the notes are still not descrypted. 
Do you need to upgrade ALL your installations at once?!

**Comment by matt32106** [comment]
I think the advice in this post should be part of Joplin's UI (in the error message add this advice) and this post should be made sticky.
