### ISSUE TITLE
New user setup: password accepted during setup but 403's at login.

### ISSUE THREAD

**Issue by geekzer0** [laurent22/joplin#8449]
Setting up a new Joplincloud account, I used a roughly 50 character random (including symbols) password auto-generated by my password vault app.  The setup succeeded, I got the activation email, then tried to log in from another browser.  That threw a 403 error.

Using the already logged in window, I reset the password to a (roughly) 30 character password with no symbols, now everything works.

Please update the initial account creation dialogs with what your password limitations are; not everyone will work around your limitations easily.

## Environment

Joplin version:  2.11.11 (prod, darwin)
Platform: MacOS Ventura 13.4.1 on iMac Pro
OS specifics: fully patched latest MacOS non-beta

## Steps to reproduce

1. Create a new account in JoplinCloud.  Make its password complex with symbols, 50 characters or more
2. Activate the account via email click
3. Now try to login with those credentials from another browser or separate (private) window.  Get 403.

## Describe what you expected to happen

Either accurate information about password limitations, or accept whatever is input

## Logfile

No point, the fault is in your server code.

**Comment by laurent22** [comment]
There is no limit on the password length and if there was one it would be more than 50 characters. We'll check and see if that can be replicated

**Comment by pedr** [comment]
I could not reproduce this bug, I tried creating a user with a long password and a user without a password just creating one after following the email confirmation link and neither approach seemed to reproduce any kind of bug.

I used Bitwarden to create the passwords using the following configuration:

![image](https://github.com/laurent22/joplin/assets/5051088/0ec23ff1-1dab-498b-b6be-8cd1abf28803)

**Comment by laurent22** [comment]
Closed, as we cannot replicate. The only way we can trigger this bug is by inputting an incorrect username or password.

**Comment by personalizedrefrigerator** [comment]
It looks like we're [using `bcrypt` internally](https://github.com/laurent22/joplin/blob/d33df549699631b2d5bb01e269bb3c41110dbecf/packages/server/src/utils/auth.ts#L5), which [has a maximum input length of 72 bytes](https://github.com/dcodeIO/bcrypt.js#security-considerations). According to the README, UTF-8 characters take up to 4 bytes[^1]. As such, passwords can be limited to as few as 18-20 characters (depending on the characters chosen).

[^1]: [this source seems to give a counter-example](https://security.stackexchange.com/a/184090).
