### ISSUE TITLE
Import folder with many .md files in subfolders

### ISSUE THREAD

**Issue by seth100** [laurent22/joplin#845]
Hi,

would it be possible to implement the feature of importing a folder in Joplin so that the subfolders structure will be maintained and all `.md` files imported?
I'm using another app to read my `.md` files but I have many files and want to switch to Joplin. 

I hope there will be a way to do that.
Thanks for your work.

**Comment by laurent22** [comment]
I think this is already supported via the "Import Markdown Directory" feature:

![image](https://user-images.githubusercontent.com/1285584/46459299-60fa7b80-c7b0-11e8-97aa-a516a1a6565e.png)

Is that what you are looking for?

**Comment by seth100** [comment]
Ah sorry I was looking for the feature in the mobile app.
I'll try that and let you know.
Thanks

**Comment by seth100** [comment]
Hi, that's the feature I was looking for thanks.
Just 2 more questions: 

1. is it possible to share an encrypted image from Joplin Android app? It's currently sharing the source code of the image and not real image.
1. is it possible to customize desktop and/or Android app CSS style of the rendered markdown files?

Thanks
