### ISSUE TITLE
FDroid help

### ISSUE THREAD

**Issue by PeterKW** [laurent22/joplin#8453]
I think I have the latest version of joplin on this fdroid repo that has the same signature as the one on the installed? Is there a way of updating it without loosing the app installed on my phone currently? https://apt.izzysoft.de/fdroid/repo/net.cozic.joplin_2097685.apk

Sorry, it seems a bit confusing to me

**Comment by Daeraxa** [comment]
The GitHub issue tracker is only for bugs. For help and advice please use the [forums](https://discourse.joplinapp.org/) or Discord.
