### ISSUE TITLE
Is there a way to to change the font size for notes (iOS)?

### ISSUE THREAD

**Issue by Panja0** [laurent22/joplin#8455]
I can change the font size for the editor but for the notes themself I cannot change the size, using the iOS app.
Is there any way to change that, without changing the whole font size/system wide font size?

**Comment by personalizedrefrigerator** [comment]
I don't think that there is...

You can change the font size for everything in Joplin, though:
1. Open system settings > accessibility
2. Scroll down to the bottom and select "**per-app** settings".
3. Click "add app", then "Joplin"
4. Select "larger text"

**Comment by Panja0** [comment]
Thanks @personalizedrefrigerator 
This is something I can work with! Cheers

**Comment by ikwyl6** [comment]
This also affects the editor font size when changing the 'Larger text' option. My end goal is to make the viewer smaller font than default. So finding this issue and adjusting it to
Make the font smaller makes both Viewer font and editor font smaller.

**Comment by personalizedrefrigerator** [comment]
It's now possible to adjust the mobile app's viewer/editor font sizes from Joplin's settings (this is an old issue).

**Comment by ikwyl6** [comment]
> It's now possible to adjust the mobile app's viewer/editor font sizes from Joplin's settings (this is an old issue).

Yes I have that option for the viewer but it does not change the font size settings when I change it within Joplin.
