### ISSUE TITLE
Fix error handling when sync credentials cannot be found in the keychain

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8466]
Currently when the app cannot find auth information in the keychain, it seems it tries to sync with empty credentials. It results in an ambiguous error message:

https://github.com/laurent22/joplin/issues/6052#issuecomment-1634389364

And there's no easy way to recover from it:

https://github.com/laurent22/joplin/issues/6052#issuecomment-1634395803

We should handle this properly:

- Maybe by going through the auth process again? Auth info is cached to keychain, and it should be regenerated in this case but somehow the current code doesn't do this

- Or if it's easier by clearing the user password (thus they should get a proper error message, and will know they need to enter their password again)

Whatever is easier I guess since the situation should happen rarely.

Happens with WebDAV at least, but please also check at least Joplin Server/Cloud and Dropbox/OneDrive.

The reported bug is on macOS but I assume the same could happen on other platforms.

**Comment by personalizedrefrigerator** [comment]
Here's what I've found so far:
- Joplin produces an "UnknownError 2" with code 401 or 403 when it can't authenticate to WebDAV (401 in the case where it's missing credentials).
     - With my WebDAV server (Apache), the response text Joplin includes does make the error descriptive.
- It retries authentication with a delay three times before displaying the message, however. Thus, "syncing..." is visible for some time until the error message is visible.

I've replaced "Unknown Error 2" with a more descriptive error message. Retrying fewer times or not retrying in specific cases still needs to be done.

**Comment by laurent22** [comment]
I think the more worrying issue is this:

```
Synchronizer: Error: GET info.json: No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured (Exception Sabre\DAV\Exception\NotAuthenticated) (401): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured</s:message>
</d:error>

    at newError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:414:11)
    at WebDavApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:441:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FileApiDriverWebDav.get (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:166:21)
```

It means that we don't have the auth info (probably the password), but we're trying to login anyway, and apparently there's no way to get out of this situation without changing the password to a wrong one, then back to the good one. I expect it will lead to many support requests once we deploy the ARM64 version more widely
