### ISSUE TITLE
Text that is pasted in Rich Text editor has extra new lines

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8476]
If I copy this plain text:

```
one paragraph

two paragraph
```

and paste it in the rich text editor, I get this:

```
one paragraph


two paragraph
```

So it's adding an extra newline character, while it should simply be creating two paragraphs.

A fix was attempted here: https://github.com/laurent22/joplin/pull/8511

**Comment by lapaz17** [comment]
whic rich text are we talking about? https://www.richtexteditor.com/Docs/install_div.aspx is it this?

**Comment by verglor** [comment]
This is still unresolved issue since the referenced PR #8511 was closed without merging. Please reopen it @laurent22.

**Comment by laurent22** [comment]
That was fixed in [b9659bb](https://github.com/laurent22/joplin/commit/b9659bb9c187f1f9e665f0bbb27625abab0347ad). If there's still an issue, a new detailed bug report should be opened
