### ISSUE TITLE
iOS with Keyboard: Ctrl-C to copy deletes your text irretrievably

### ISSUE THREAD

**Issue by hamble** [laurent22/joplin#8483]
Using a keyboard attached to an iOS device (e.g. iPad). 

Clicking Ctrl-C intending to copy text immediately wipes it. It is then not recoverable.

## Environment

Joplin version: 
Platform: iOS Native App
OS specifics: iOS

## Steps to reproduce

1. Connect wireless keyboard to iPad (e.g. Logitech K400)
2. Higlight text in Joplin
3. Press 'Ctrl-C'. BOOM!

## Describe what you expected to happen

Text left intact, and copied to clipboard

**Comment by personalizedrefrigerator** [comment]
I can confirm the deletion part! Undoing it works for me, though.

The keyboard shortcuts on my iOS keyboard seem to be similar to macOS keyboard shortcuts. As such, the keyboard shortcuts try to use a "command key". On my bluetooth keyboard, this is the Windows key. Thus, windows+z is undo, windows+Shift+z is redo, and windows+c is copy.

**Comment by hamble** [comment]
Thanks for confirming!

I couldn’t find a way to undo.

I don’t have a meta key on my keyboard.
________________________________

**Comment by personalizedrefrigerator** [comment]
If you have a Windows key, try that. If not, there should be an undo arrow at the top of the screen that can be clicked.

There might also be a way to change what the meta/command key is in settings (I'll look for it).

**Comment by personalizedrefrigerator** [comment]
It looks like you can change what the command key is in settings (it's called the command key there, not the meta key — it's called the meta key in code).

To do this, go to the settings app, then general > keyboards > hardware keyboard > modifier keys. Next, click one of the keys that exists on your keyboard (e.g. control) and choose for it to perform the "command" action.

(I'm on iOS, so it might be a bit different on iPadOS)
![Screenshot: Opening settings > general > keyboards > hardware keyboard > modifier keys and selecting a different action for the control key.](https://github.com/laurent22/joplin/assets/46334387/51125784-f02b-45a2-a8c2-1e4886c81185)
