### ISSUE TITLE
Joplincloud Not syncing withj Android 6 marshmallow

### ISSUE THREAD

**Issue by Beltrando** [laurent22/joplin#8487]
## Environment

Joplin version: 2.11.32
Platform: Android 6.0
OS specifics: n/a

## Steps to reproduce

1. Fresh installation of Android 6.0 (Huawei Mediapad X2 Reset to factory settings)
2. Wifi connexion
3. Fresh installation of Joplin 2.11.32 v42
4. Configuration / Sync / Joplin Cloud email & password 
5. Ignore TLS error, or not ignoring (same behavior)
6. **Check sync : OK !**

But error while syncing :
"Error: upLoadBlob: PUT https://api.joplincloud.com/api/items/root:/.ressource/bc6986 ... .. .../content: Error: java.security.cert CertPathValidatorException: Trust anchor for certification path not found

## Describe what you expected to happen
Syncing !

**Comment by laurent22** [comment]
It seems certain Android 6 devices have issues with root certificates, and unfortunately we can't do anything about it ourselves. Perhaps try what's mentioned here:

> After manually installing [Let's Encrypt ISRG Root X1](https://letsencrypt.org/certs/isrgrootx1.der) certificate on an Android 6 emulator, Realm is working fine.

https://github.com/realm/realm-dotnet/issues/2865#issuecomment-1076520852

**Comment by Beltrando** [comment]
It worked. Thank you.
Bien à vous,

Eric Beltrando
www.linkedin.com/in/Éric <http://www.linkedin.com/in/%C3%A9ric>
***@***.***


Nos *528 projets*: http://www.bilog.fr/realisations
Standard:  +331 30 21 63 92



Le dim. 16 juil. 2023 à 16:47, Laurent Cozic ***@***.***> a
écrit :
