### ISSUE TITLE
Tray Icon Huge on KDE Plasma

### ISSUE THREAD

**Issue by ScriptInfra** [laurent22/joplin#8488]
Hello. I am not entirely sure if this an issue with Joplin itself but I noticed that after upgrading to Joplin version 2.12.7, the app icon is now massive (larger than previous versions).

## Environment

Joplin version: 2.12.7
Platform:  Fedora 38 / KDE Plasma 5.27.6

## Steps to reproduce

1. Launch Joplin application.
2. View the size of the tray icon.

Please see below screenshot of enlarged icon size:

![image](https://github.com/laurent22/joplin/assets/63025323/e17488bb-53ec-4b98-a05f-f775a4e7dfc2)

**Comment by laurent22** [comment]
I don't think we changed that. How did it look before?

**Comment by ScriptInfra** [comment]
The icon previously was probably around 75% the scale of what is seen in the screenshot. It better aligned with the size of the other tray icons.
I'm unsure how this icon sizing is actually defined but wanted to at least report it as it is quite a staggering size difference.

**Comment by ScriptInfra** [comment]
This remains an issue.

**Comment by ScriptInfra** [comment]
This remains an issue.
