### ISSUE TITLE
Issues with sync to local directory

### ISSUE THREAD

**Issue by yafp** [laurent22/joplin#85]
### Operating system

- Ubuntu Linux - 0.10.38

### Application

- Desktop

### Problem

* I did create some test notebooks and notes
* I then configured in Options a local sync path
* Triggers sync manually - no results/output in the configured local sync folder. No error either.
* Restarted the app and all notes and notebooks are gone

If i create new notes now, they get synced to the configured folder. So it seems like a problem which only happens after configuring the local sync path and next app start.

---

**Comment by laurent22** [comment]
I couldn't replicate this but there are several changes regarding sync path in the last version, so could you give it a try and see if it's still happening?

**Comment by crile** [comment]
I observe same kind of problem on Windows (v0.10.39)

To reproduce:
* backup local sync directory
* delete local sync directory
* start joplin
* synchronize
* everything is gone (it is normal)
* stop joplin
* restore the local sync directory from your backup
* restart joplin
* the notebooks are gone (tags and documents seem to be here)

**Comment by laurent22** [comment]
Thanks to @crile steps I managed to replicate and fix this issue, so this use-case will be supported in the next version.
