### ISSUE TITLE
In the rich text editor, display the plugin icons instead of gear icons

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8504]
Currently, in the Markdown editor, we display the plugin icons correctly in the toolbar.

In the Rich Text editor however, we display them all as gear ⚙ icons. Instead we should display whatever icon was chosen by the plugin developer

See here for an analysis of the issue: https://github.com/laurent22/joplin/issues/8433#issuecomment-1627841176

**Comment by personalizedrefrigerator** [comment]
See also https://github.com/laurent22/joplin/issues/8433
