### ISSUE TITLE
Server sync issues since latest Android update?

### ISSUE THREAD

**Issue by DeltaTangoLima** [laurent22/joplin#8509]
## Description

I run Joplin clients on my Android phone, my personal iMac, and my company Macbook Pro (versions and other details below).

I've belatedly realised that, for several days at least, my notes haven't been syncing from any of the three clients, with all of them getting the same error from the server. Looking at the most recently edited notes on each client, it seems the earliest this problem occurred was July 11th.

This date coincides with the latest Android client update via the Play Store, so I'm wondering if the Android client could have written something to the server that is causing this issue.

No other changes have occurred. I did update the server docker image to 2.12.1 to see if that would help, but it changed nothing.

## Error specifics

The macOS and Android clients all deliver the following error immediately below the 'Completed' message:
`Last error: SyntaxError: Unexpected end of JSON input`

When enabling debugging tools in one of the macOS clients, I receive this error in the web developer console:
```
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(189, 198, 207); font-family: menlo, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">20:48:53: Synchronizer: <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">SyntaxError: Unexpected end of JSON input
    at JSON.parse (&lt;anonymous&gt;)
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link" role="link" tabindex="-1" title="file:///Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/syncInfoUtils.ts:69:17" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">syncInfoUtils.ts:69:17</span>
</span>    at Generator.next (&lt;anonymous&gt;)
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at fulfilled (<span class="devtools-link" role="link" tabindex="-1" title="/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/syncInfoUtils.js:5:58" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">/Applications/Joplin<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>ncInfoUtils.js:5:58</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at process.processTicksAndRejections (<span class="devtools-link" role="link" tabindex="-1" title="node:internal/process/task_queues:96:5" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">node:internal/process/task_queues:96:5</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(189, 198, 207); font-family: menlo, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size:11px; --monospace-font-family:menlo,monospace; --source-code-font-size:11px; --source-code-font-family:menlo,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

  | log | @ | Logger.ts:237
-- | -- | -- | --
  | error | @ | Logger.ts:111
  | (anonymous) | @ | Synchronizer.ts:1099
  | rejected | @ | /Applications/Joplin…b/Synchronizer.js:6
  | processTicksAndRejections | @ | node:internal/process/task_queues:96
  | Promise.then (async) |   |  
  | step | @ | /Applications/Joplin…b/Synchronizer.js:7
  | fulfilled | @ | /Applications/Joplin…b/Synchronizer.js:5
  | processTicksAndRejections | @ | node:internal/process/task_queues:96
  | Promise.then (async) |   |  
  | step | @ | /Applications/Joplin…b/Synchronizer.js:7
  | fulfilled | @ | /Applications/Joplin…b/Synchronizer.js:5
  | processTicksAndRejections | @ | node:internal/process/task_queues:96
  | Promise.then (async) |   |  
  | step | @ | /Applications/Joplin…b/Synchronizer.js:7
  | fulfilled | @ | /Applications/Joplin…b/Synchronizer.js:5
  | processTicksAndRejections | @ | node:internal/process/task_queues:96
  | Promise.then (async) |   |  
  | step | @ | /Applications/Joplin…b/Synchronizer.js:7
  | fulfilled | @ | /Applications/Joplin…b/Synchronizer.js:5
  | processTicksAndRejections | @ | node:internal/process/task_queues:96
  | Promise.then (async) |   |  
  | step | @ | /Applications/Joplin…b/Synchronizer.js:7
  | (anonymous) | @ | /Applications/Joplin…b/Synchronizer.js:8
  | __awaiter | @ | /Applications/Joplin…b/Synchronizer.js:4
  | start | @ | Synchronizer.ts:360
  | (anonymous) | @ | registry.ts:163
  | fulfilled | @ | /Applications/Joplin…n/lib/registry.js:5
  | Promise.then (async) |   |  
  | step | @ | /Applications/Joplin…n/lib/registry.js:7
  | fulfilled | @ | /Applications/Joplin…n/lib/registry.js:5
  | Promise.then (async) |   |  
  | step | @ | /Applications/Joplin…n/lib/registry.js:7
  | (anonymous) | @ | /Applications/Joplin…n/lib/registry.js:8
  | __awaiter | @ | /Applications/Joplin…n/lib/registry.js:4
  | timeoutCallback | @ | registry.ts:113
  | (anonymous) | @ | registry.ts:186
  | (anonymous) | @ | /Applications/Joplin…n/lib/registry.js:8
  | __awaiter | @ | /Applications/Joplin…n/lib/registry.js:4
  | Registry.scheduleSync | @ | registry.ts:89
  | (anonymous) | @ | synchronize.ts:60
  | fulfilled | @ | /Applications/Joplin…ds/synchronize.js:5
  | Promise.then (async) |   |  
  | step | @ | /Applications/Joplin…ds/synchronize.js:7
  | fulfilled | @ | /Applications/Joplin…ds/synchronize.js:5
  | Promise.then (async) |   |  
  | step | @ | /Applications/Joplin…ds/synchronize.js:7
  | (anonymous) | @ | /Applications/Joplin…ds/synchronize.js:8
  | __awaiter | @ | /Applications/Joplin…ds/synchronize.js:4
  | execute | @ | synchronize.ts:16
  | (anonymous) | @ | CommandService.ts:248
  | (anonymous) | @ | /Applications/Joplin…CommandService.js:8
  | __awaiter | @ | /Applications/Joplin…CommandService.js:4
  | execute | @ | CommandService.ts:241
  | (anonymous) | @ | MenuBar.tsx:228
  | (anonymous) | @ | MenuBar.tsx:301
  | click | @ | MenuUtils.ts:83
  | apply | @ | /Applications/Joplin…acks-registry.js:54
  | (anonymous) | @ | /Applications/Joplin…derer/remote.js:346
  | (anonymous) | @ | /Applications/Joplin…derer/remote.js:328
  | emit | @ | node:events:526
  | onMessage | @ | node:electron/js2c/renderer_init:69

</span></div>
```

The server docker container logs produce this error when the problem occurs:
```
2023-07-19 10:49:19: [error] App: ::ffff:127.0.0.1 TypeError: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at new URL (node:internal/url:560:13)
    at isValidOrigin (/home/joplin/packages/server/src/utils/routeUtils.ts:166:17)
    at /home/joplin/packages/server/src/utils/routeUtils.ts:209:18
    at Generator.next (<anonymous>)
    at /home/joplin/packages/server/dist/utils/routeUtils.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/joplin/packages/server/dist/utils/routeUtils.js:4:12)
    at execRequest (/home/joplin/packages/server/dist/utils/routeUtils.js:184:12)
    at /home/joplin/packages/server/src/middleware/routeHandler.ts:13:63 {
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}
2023-07-19 10:49:19: App: GET / (500) (3ms)
```

### Server:
Joplin version: both **2.12.1** and **2.11.1** (rolled back docker container during testing)
Platform: Linux
OS specifics: Debian Linux 11 (running under Proxmox)

### Mac clients
Joplin version: **2.11.11**
Platform: macOS
OS specifics: macOS Ventura 13.4.1

### Android client
Joplin version: **2.11.32**
Platform: Android 13
OS specifics: Android 13, security update 5 July 2023

## Steps to reproduce

1. Attempt to sync
2. Observe error in client status
3. Determine no changes have actually synced

## Describe what you expected to happen

Sync without errors

## Logfile

See debug console error pasted above.

**Comment by personalizedrefrigerator** [comment]
I've started looking into this. So far, here's some additional information based on the logs above.

# The client error

The stack trace from the first log, when reformatted, reads:
```
20:48:53: Synchronizer: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at syncInfoUtils.ts:69:17
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Joplin…ncInfoUtils.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Thus, the `JSON.parse` call this references is made here:
https://github.com/laurent22/joplin/blob/1fe01dc0ceb47a092f5cf00f16a7e2d1fbc01c4d/packages/lib/services/synchronizer/syncInfoUtils.ts#L62-L71

It would be useful to know whether `JSON.parse` is being called with actual JSON or with an error message. Here's how to fetch `info.json` from the developer tools:
<details>

Open the developer tools on one of the desktop clients and type the following into the console:
1. `Setting.value('sync.target')`
    - This returns the ID of the sync target currently configured to be used with Joplin. This should be `9` for Joplin Server.
2. `const reg = require('@joplin/lib/registry').reg;`
    - This imports a library that gives access to Joplin's synchronizer, logger, database, etc.
3. `const sync = await reg.syncTarget(9).synchronizer()`
    - `reg.syncTarget(9).synchronizer()` returns the Joplin Server sync  target (which has ID 9)
4. `await sync.api().get('info.json')`
    - `sync.api()` returns the synchronizer's file API and `.get('info.json')` fetches `info.json` from the sync target.

Does the output of `await sync.api().get('info.json')` look like JSON? Does it end with a closing brace `}` or does it look incomplete? (No need to post the output).

</details>

# The server error

Similarly, the Joplin Server error comes from here:
https://github.com/laurent22/joplin/blob/1fe01dc0ceb47a092f5cf00f16a7e2d1fbc01c4d/packages/server/src/utils/routeUtils.ts#L165-L167
which is called here:
https://github.com/laurent22/joplin/blob/1fe01dc0ceb47a092f5cf00f16a7e2d1fbc01c4d/packages/server/src/utils/routeUtils.ts#L205-L210

Note that `new URL(someStringHere)` produces an error similar to that from the server if `someStringHere` is `undefined`:
```
bash$ node
> new URL(undefined)
Uncaught TypeError [ERR_INVALID_URL]: Invalid URL
    at __node_internal_captureLargerStackTrace (node:internal/errors:491:5)
    at new NodeError (node:internal/errors:400:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5) {
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}
>
```
Thus, `ctx.URL.origin` is either `undefined` or `"undefined"` in the call to `isValidOrigin`. (This is odd because to call `isValidOrigin`, `ctx.URL` must be non-null...)

**Comment by DeltaTangoLima** [comment]
@personalizedrefrigerator well, that's interesting. After step 4 in the client developer tools console, I can see that the JSON out is definitely truncated.

What it appears to have dumped back out is some JSON for a number of `masterKeys` being used for encryption. The last of these `masterKeys` in the output is definitely truncated - the `content` object is cut short, with the other child objects that come after (`created_time`, `updated_time`, etc) missing.

Now, in that output, the truncated `masterKey` is the fourth one. My clients all have six keys configured, with five of them disabled (I had a period of time last year where I had to keep swapping between phones - I suspect that's where the "extra" keys came from).

So is the question how I somehow force all parties (server and clients) to drop the disabled keys and just have the one enabled key? I tried turning off encryption and resyncing, but I still have the same issue, so I suspect I need to do something on the server - perhaps cleanup a row or table in the database?

**Comment by personalizedrefrigerator** [comment]
Here's what I think happened: Somehow, Joplin Server (or one of the clients) was interrupted while writing to `info.json` leading to a corrupted file. 

Before doing anything else, make sure you have a recent backup of your notes.

Here are some options:
1. Open Settings > Synchronization > Advanced then click "Re-upload local data to sync target". This will delete all notes/resources on the server and upload everything from the client. This should (I think) replace `info.json` with a new version.
2. Try to correct `info.json` manually and upload it to the server.
    - To do option 2, I think you can run ``await sync.api().put('info.json', `fixed-JSON-here`)`` where `fixed-JSON-here` is manually-updated JSON. 
3. Delete `info.json` from the server and allow Joplin to re-create it.
    - To do this, run `await sync.api().delete('info.json')`.

Option 3 _seems_ to work, but I can't guarantee that it won't break things.

**Comment by DeltaTangoLima** [comment]
@personalizedrefrigerator thanks for your advice on this. Option 3, above, did the trick for me. All clients now syncing again, and all are in sync. Thanks again.
