### ISSUE TITLE
CLI - "Illegal instruction (core dumped)"

### ISSUE THREAD

**Issue by ambrt** [laurent22/joplin#8513]
I get `Illegal instruction (core dumped)` after updating cli version with npm.
It was working on database version 41, but i had to upgrade due to conflict with Desktop newest version.
Desktop version works properly.

## Environment
Joplin version: Latest
Platform: terminal
Operating System: Ubuntu 20.04.6 LTS
Kernel: Linux 5.4.0-153-generic
Architecture: x86-64
Node: 18.15.0
NPM: 9.5.0

## Steps to reproduce

1. npm i -g joplin (or `NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin`)
2. joplin --debug --log-level debug

## Logfile
All i get is - "Illegal instruction (core dumped)" on terminal - ~/.config/joplin/log.txt does not have any new entries.

**Comment by laurent22** [comment]
Can you find more information somewhere? This is Node.js crashing so we'd need to see some crash dump to be able to google the issue. Maybe Node just needs to be updated

**Comment by ambrt** [comment]
My PC is old: 
    ``` 
     CPU: (2) x64 Intel(R) Core(TM)2 Duo CPU     E4500  @ 2.20GHz
    ```

Its apparently problem with  `sharp.js` lib:
Running `gdb --args node ~/.joplin-bin/lib/node_modules/joplin/main.js `:

```Starting program: /home/user/.nvm/versions/node/v20.4.0/bin/node /home/user/.joplin-bin/lib/node_modules/joplin/main.js
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7a3c700 (LWP 27416)]
[New Thread 0x7ffff723b700 (LWP 27417)]
[New Thread 0x7ffff6a3a700 (LWP 27418)]
[New Thread 0x7ffff6239700 (LWP 27419)]
[New Thread 0x7ffff5a38700 (LWP 27420)]
[New Thread 0x7ffff7fca700 (LWP 27421)]

Thread 1 "node" received signal SIGILL, Illegal instruction.
0x00007fffbf150306 in ?? ()
   from /home/user/.joplin-bin/lib/node_modules/joplin/node_modules/sharp/build/Release/../.././vendor/8.14.2/linux-x64/lib/libvips-cpp.so.42
   ```
Same problem was reported here: https://stackoverflow.com/questions/70488206/how-to-fix-invalid-instruction-error-when-running-node-js-in-docker-with-shar/

Basic solution is to downgrade `sharp`:
   ```
cd ~/.joplin-bin/lib/node_modules/joplin
   npm i sharp@0.27.2 --save-exact
   ```
