### ISSUE TITLE
Desktop: Rich text editor produces a large number of `&nbsp;`s in markdown 

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#8530]
## Environment

Joplin version: Since #8468
Platform: Desktop
OS specifics: Ubuntu 23.04

## Steps to reproduce

1. Create a new note and switch to the rich text editor.
2. Type `  This is a test    ...`
3. Switch to the markdown editor.

## Describe what you expected to happen

Where possible, the editor should produce markdown that uses Unicode nonbreaking spaces (`\u00A0`) instead of HTML nonbreaking spaces, as it did before #8468.

(Some nonbreaking HTML spaces may still be necessary to preserve leading indentation).

**Comment by konashevich** [comment]
I confirm the same issues. My understanding it appears when I hit Enter in edit mode (new line / paraphgraph).
I mostly write texts in Edit mode, but once in a while I switch to MD and see this hell of &nbsp;

That might not perceived as a bug though, but MD gets really ugly
