### ISSUE TITLE
Web Clipper clips wrong article

### ISSUE THREAD

**Issue by Addlai** [laurent22/joplin#8553]
I've consistently encountered a problem with the Chrome web clipper on web pages that have a sequence of stories, such as  MSN or Microsoft Start pages. Generally the clipper captures the second, not the first article. This is a longstanding issue that has prevented me from using Joplin for a while (more than a year). The behavior is the same with Chrome and Microsoft Edge and affects Mac, Windows, and Linux. (I haven't checked recently on Windows and Linux but have no reason to think the problem isn't still there.) 

Here's an example url. Note however that this behavior is 100% of the time (or close to 100%) on news feeds through Microsoft MSN and Microsoft Start, so if this page disappears, any other page will do.
https://www.msn.com/en-us/foodanddrink/foodnews/sorry-what-the-specks-on-strawberries-aren-t-actually-seeds/ar-AA1ejURm?ocid=msedgntp&cvid=1893f45ddce5469c8dbf626e72dbd8af&ei=31

## Environment

Joplin version: Joplin 2.11.11 (prod, darwin)
Platform: macOS
OS specifics:  Ventura 13.2.1

## Steps to reproduce

1. Visit the page with, say, the above url
2. Clip the page using, say, "Clip Simplified Page"
3.  Note that the clipped article in Joplin desktop is not the same as the lead article in the web page.

**Comment by laurent22** [comment]
The web clipper is not suitable to capture content from infinite scroll pages unfortunately
