### ISSUE TITLE
Dark Mode - Editing or Creating a new note flickers the screen with a white page 

### ISSUE THREAD

**Issue by malthousiast** [laurent22/joplin#8557]
As soon as a new note is created, the body goes white then dark again.

## Environment

Joplin version: 12.11.5
Platform: iOS
OS specifics: 16.5.1 Dark Model enabled

## Steps to reproduce

1. Enable dark mode
2. Open Joplin app
3. Click on any notebook then the "+" to add a new note
4. Notice the flickering (flickers only once per edit/new)

## Describe what you expected to happen
Don't flicker, keep it all dark.

**Comment by personalizedrefrigerator** [comment]
I can reproduce this on iOS 17.
