### ISSUE TITLE
Implement js-draw UI

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8568]
The design for this is here: https://www.figma.com/file/NA5F2AMWO3wUuaoDfUaAb8/Material-3-wireframes?type=design&node-id=54490%3A1103&mode=design&t=Ee0UwnPnQ2bNC2uM-1

So we'll focus on the mobile UI for now, and just make sure it's good enough for desktop. In v2 we'll review and make it more suitable for desktop/tablet.

**Comment by personalizedrefrigerator** [comment]
This was completed in https://github.com/laurent22/joplin/pull/7588. I'm closing this for now.

If there are still changes to be made for this, please let me know!
