### ISSUE TITLE
Mobile Android app not correctly updating notes on filesystem

### ISSUE THREAD

**Issue by seth100** [laurent22/joplin#857]
### Operating system

- Linux
- Android

### Application

- Desktop
- Mobile

### Description

I have the Desktop app and I have encrypted my `.md` notes after importing them from folder.
I'm using [Syncthing](https://syncthing.net/) to synchronise notes folder between Desktop and Android phone.
After configuring everything and synchronizing Desktop app I went to the mobile Android app and, after specifying the correct Filesystem folder (synchronised between Desktop and Mobile by Syncthing)  I have executed the first synchronization (by following the official guide [here](https://joplin.cozic.net/e2ee/)).
Joplin mobile correctly imported all my notes (encrypted) so I just finalized the process by adding the encryption password and Joplin decrypted them.

Now, when I update a note from Desktop, Syncthing updates it and I'm able to see the update on the mobile app after synchronization.

On the contrary, when updating from the mobile app and executing the "Synchronise" operation, it's always saying:
`Updated remote items: 1`
no matters how many times I tap "Synchronise".
Indeed, I do **not** see the updated note on the Desktop app.

So I decided to check the note was actually updated by Joplin on the filesystem, and I discovered it was not. The latest edited file was old comparing to the time I updated the note.
So it's not Syncthing not sending the update (as I was thinking at the beginning) but Joplin is not updating the note on the filesystem.

There are no errors in logs, just the following message everytime I tap "Synchronise":

![image](https://user-images.githubusercontent.com/4366877/46568087-8cf83700-c93f-11e8-81ba-99d652989249.png)

but the master key **is** specified, indeed the notes were decrypted before.

I have recently switched to Joplin for all my notes and I really need them to work for my work.
Any help would be appreciate!

Thanks a lot!

**Comment by seth100** [comment]
Sorry I'll close it because I solved it by resetting everything: deleted folders in `.config` for the desktop app and reimported my notes, re-encrypted and synchronised.
For the mobile app I reinstalled it and imported again. This time I first tried to edit a note from the mobile app and synchronised with desktop. Now it works and also the opposite from desktop to mobile.
Thank for your work, hope you'll keep maintaining and improving Joplin.

**Comment by laurent22** [comment]
Glad that your problem is fixed. In general, I would expect that cloud services like Nextcloud or Dropbox are more reliable than going through the filesystem, since various things can interfere with the file system, change the timestamps, etc.
