### ISSUE TITLE
Code blocks inside of table cells don't persist after switching between the markdown editor and the WYSIWYG editor.

### ISSUE THREAD

**Issue by futuremotiondev** [laurent22/joplin#8579]
## Environment

Joplin version: 2.12.9
Platform: Windows
OS specifics: Windows 10 Pro x64

## Steps to reproduce

1. Switch to WYSIWYG mode.
2. Create a table.
3. Create a code block inside one of the cells.
4. Switch back to the markdown editor mode.
5. Switch back to WYSIWYG mode.
6. Code block is now just an inline code block.

Here's a video:

https://github.com/laurent22/joplin/assets/33441569/0cc63710-0a98-41a1-bab3-1cf21a686f0e

## Describe what you expected to happen

The code block in the table to persist.

**Comment by laurent22** [comment]
I don't think code blocks are supported within markdown tables, but we should investigate whether we could persevere the table as html when it contains data that's not supported by markdown

**Comment by futuremotiondev** [comment]
> I don't think code blocks are supported within markdown tables, but we should investigate whether we could persevere the table as html when it contains data that's not supported by markdown

That would be great. Having a code block inside of a table would be really useful and allow for more rich presentation possibilities - I.E. When documenting APIs, or outlining codebases. Often a code example alongside of a description really helps content comprehension.

**Comment by Kroc** [comment]
I've just discovered how useless this is :( 

![image](https://github.com/laurent22/joplin/assets/142650/68c13110-db28-4a7b-bec8-8625ab15bb14)
