### ISSUE TITLE
Joplin upgrade downloads the wrong file

### ISSUE THREAD

**Issue by chevdor** [laurent22/joplin#8584]
## Environment

Joplin version:  2.11.11
Platform: MacOS
OS specifics: Intel

## Steps to reproduce

1.  Start 2.11.11
2. wait for the message suggesting an update
3. follow the guide

## Describe what you expected to happen

Get `Joplin-2.12.10.dmg` and not `Joplin-2.12.10-arm64.dmg`.

## Logfile

n/a

**Comment by itsthejoker** [comment]
And intel macs download the ARM64 version, which is how I found this issue.

**Comment by laurent22** [comment]
Sorry about this, that will be fixed in the next version. In the meantime, please get the latest version from here:

https://github.com/laurent22/joplin/releases/download/v2.11.11/Joplin-2.11.11.dmg

**Comment by chevdor** [comment]
No need to apologize and thanks for the great work, this is not a major issue ❤️

**Comment by chevdor** [comment]
Dear GHA bot, issues do not fix themselves by magic :)

**Comment by itsthejoker** [comment]
@chevdor do we need to keep this open? There have been several releases since then, and they've all downloaded the correct release for me. I think we can chalk this up to a single broken release that has since been fixed?

**Comment by chevdor** [comment]
Fine closing, I did keep an eye on the issue and indeed did **not** notice any glitch since the initial report.
