### ISSUE TITLE
Start problem with KDE openSUSE

### ISSUE THREAD

**Issue by alpvonkri** [laurent22/joplin#8585]
Since version 2.12.5 it won't start (at most start with white screen), already did the flags.txt steps but it won't generate a log file, however it generates CLI outputs. Version 2.12.4 works perfectly.

## Environment

Joplin version: 2.12.5 and up
Platform: Linux openSUSE KDE
OS specifics: openSUSE Linux 15.5, KDE 5.27.6

## Steps to reproduce

1.  Launch AppImage

## Describe what you expected to happen
The app to open

## Logfile

There is not log file, but this CLI output:
./Joplin-2.12.10.AppImage

MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/database.sqlite>: 9
MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/flags.txt>: 9
MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/settings.json>: 9
MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/cache>: 9
MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/resources>: 9
MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/tmp>: 9
MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/database.sqlite>: 9
MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/flags.txt>: 9
MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/settings.json>: 9
MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/cache>: 9
MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/resources>: 9
MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/tmp>: 9
MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/database.sqlite>: 9
MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/flags.txt>: 9
MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/settings.json>: 9
MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/cache>: 9
MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/resources>: 9
MEGASYNCOVERLAYPLUGIN: getOverlays </home/alpvonkri/.config/joplin-desktop/tmp>: 9

**Comment by personalizedrefrigerator** [comment]
I don't think KDE is the issue — I just tested v2.12.10 on Fedora 38 with KDE Plasma on Wayland. (I haven't tested on openSUSE, though).

Does launching with the `--safe-mode` command line flag help? If so, this might be a plugin-related issue.

**Comment by alpvonkri** [comment]
Still the same, nothing happens, attached details:
![image](https://github.com/laurent22/joplin/assets/104341/19e1661d-0b19-465a-9736-169989b708b6)
![image](https://github.com/laurent22/joplin/assets/104341/b7ce1490-f47e-4969-bb02-5e16db6914c5)
![image](https://github.com/laurent22/joplin/assets/104341/e036869f-2d1e-4b2b-8a94-f22805ecdbab)

Any specific I should try?

**Comment by personalizedrefrigerator** [comment]
Another thing to try (make sure you have a backup first!) is renaming the profile directory (e.g. from `~/.config/joplin-desktop` to `~/.config/joplin-desktop-old`) so that Joplin can't find it when it launches. This should help confirm that the issue isn't a plugin (though launching in safe mode would also have done this) or an issue with Joplin's database.

I plan to install OpenSUSE tomorrow to see if I can reproduce this issue.
**Edit**: Joplin 2.12.10 launches for me on openSUSE Tumbleweed (KDE Plasma/**Wayland**, untested on X11), however, I installed it without having first installed a previous version.

**Comment by alpvonkri** [comment]
Thanks for the follow-up, still the same. No start. BTW I use X11 not Wayland.
![image](https://github.com/laurent22/joplin/assets/104341/d49369b2-9961-41ed-872b-44febec5fb4d)
And the same situation with last working one.
![image](https://github.com/laurent22/joplin/assets/104341/630d8fd7-2905-4ce4-8245-a9087e11116b)

**Comment by personalizedrefrigerator** [comment]
Here's my system information, for comparison:
![Screenshot: Joplin running next to settings](https://github.com/laurent22/joplin/assets/46334387/3f15b035-d146-422b-9f89-ffc36a52df63)

**Comment by alpvonkri** [comment]
![image](https://github.com/laurent22/joplin/assets/104341/07e4bc10-8902-477f-b8d4-406eb5e4a9e3)

Might be some dependency thing that's different on my system, TW uses more recent versions than LP.

**Comment by alpvonkri** [comment]
It's not solved, it hasn't been followed up. Not an additional specific command or thing to test. Waiting for some feedback

**Comment by personalizedrefrigerator** [comment]
Sorry for the delay!

This is a possible duplicate of https://github.com/laurent22/joplin/issues/8777. If so, it should (hopefully!) be fixed in the next release.

**Comment by Perkolator** [comment]
> If so, it should (hopefully!) be fixed in the next release.

Hopefully it is not pushed back to the next release cycle on `Dec 1 2023 - Dec 7 2023` (Joplin 2.13). The latest version is broken for many users.

**Comment by personalizedrefrigerator** [comment]
If this is the same issue, it should be fixed in v2.12.16:

https://github.com/laurent22/joplin/releases/tag/v2.12.16

**Comment by alpvonkri** [comment]
FIXED
