### ISSUE TITLE
the popup to delete a note is still in English

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#859]
The cancel choice is still "Cancel" not `annuler`

**Comment by LonghornRach** [comment]
I can fix this!

**Comment by foxmask** [comment]
go ahead :)

**Comment by LonghornRach** [comment]
So I might not be the best one to fix this after all? The translation file is correct, which leads me to assume that the template is somehow missing the tag for the mobile cancel button. BUT Poedit doesn't have a lot of documentation so I have to assume the template is generated by tagging all text strings with something but I can't figure out what or where that is done.

Unless we're not talking about the French translation at all...

**Comment by foxmask** [comment]
Several things to read I had to follow myself when I made translation earlier : 

* read this https://github.com/laurent22/joplin/blob/master/BUILD.md to be able to compile Joplin and see if the translation are in the right place 

* a process I worte to summarize the step I followed for the po files  https://github.com/laurent22/joplin/issues/572#issuecomment-393157827

**Comment by LonghornRach** [comment]
Let me give it a shot!

**Comment by foxmask** [comment]
I think you can try to update the locale file as follow:

run 
```
node Tools/build-translation.js 
```
in the file Cliclient/locales/fr_FR.po (for example), spot that string 
```
# fuzzy
#~ msgid "[Cancel]"
#~ msgstr "Annulation..."
```
and drop everything (even fuzzy) to get that result
```
msgid "[Cancel]"
msgstr "Annulation..."
```
and run again

```
node Tools/build-translation.js 
```
then build the (desktop) app
```
cd ElectronClient/app
rsync --delete -a ../../ReactNativeClient/lib/ lib/
npm install
yarn dist
```
but my knowledge stops here too because that fixes of translation concern the mobile as the desktop is already ok.

**Comment by foxmask** [comment]
Been fixed
