### ISSUE TITLE
Joplin 2.12.10 stopped creating log.txt file ?

### ISSUE THREAD

**Issue by MR-Joplin** [laurent22/joplin#8592]
Joplin 2.12.10

does not create log.txt file!

**Comment by laurent22** [comment]
There's log rotation now, but it should create a current log.txt.

There's nothing at all for you?

**Comment by MR-Joplin** [comment]
> There's log rotation now, but it should create a current log.txt.
> 
> There's nothing at all for you?

Laurent22, thanks for your time.
So far I haven’t...
It is not a problem for the functioning of the application.
It’s just my curiosity and on the other hand it’s good not to have to delete the log.txt file from time to time.

**Comment by MR-Joplin** [comment]
Laurent22
Not wanting to bother and thanking in advance, just one more small question: 
Is it definite that the editor (toggle editors) stops removing blank lines ?

**Comment by laurent22** [comment]
Yes it should do that now

**Comment by laurent22** [comment]
Duplicate of #8598

**Comment by MR-Joplin** [comment]
> Yes it should do that now

Thank you, Laurent22
