### ISSUE TITLE
App-icon missing on linux

### ISSUE THREAD

**Issue by yafp** [laurent22/joplin#86]
![20171211_144956](https://user-images.githubusercontent.com/67605/33834400-1ff83cd8-de83-11e7-9b4c-ba607eb175eb.png)
### Operating system

- Ubuntu Linux - 

### Application

- Desktop 0.10.38

The app is not showing any specific application icon in my panel. Instead a default/generic application icon is displayed.

The android app has an app-icon, therefor i assume it is not just the fact that there is no logo designed yet.

**Comment by yafp** [comment]
This is still valid for me with 0.10.39 on Ubuntu, running gnome-shell.

If i search for joplin the blue icon is displayed in the search results, but not in the dock (using Gnome Shell extension Dash-to-Dock) itself.

**Comment by deadpyxel** [comment]
Same is happening to me, using latest (1.0.64) AppImage. The application icon is shown in the picture below:

![screenshot from 2018-02-27 18-29-24](https://user-images.githubusercontent.com/8644691/36755923-64f0818c-1bec-11e8-94b2-93190c9b7ab2.png)

This is the application icon when I search for it:

![screenshot from 2018-02-27 18-31-53](https://user-images.githubusercontent.com/8644691/36755968-86353b8a-1bec-11e8-9e8b-26d0195f9dee.png)


I am using:
- Ubuntu x64 16.04.3  LTS
- Paper icon theme
- Gnome-shell 3.18.5

**Comment by blueorignal** [comment]
Hi,

Firstly, thank you for an *amazing* project.

You may be able to resolve this by calling "QApplication::setWindowIcon()" in Joplin.

You can see a write-up for a similar issue for another application here: https://discourse.appimage.org/t/appimage-does-not-show-icon-in-task-bar/40

Hopefully this is a reasonably straight forward fix for the Linux icon issue.

Thanks again for the wonderful work.

Regards...

**Comment by StefanTT** [comment]
If you edit the appimagekit-joplin.desktop file (located in ~/.local/share/applications) and add

`StartupWMClass=Joplin`

to it then the icon is displayed in Gnome3.

**Comment by deadpyxel** [comment]
@StefanTT This worked as a workaround for me.

Is there any chance that this happens due to some kind of config conflict on Gnome-Shell? My version is `3.18.5` by the way. 

I wonder if with the new Ubuntu 18.04 LTS coming next month this will still happen. May be Gnome-Shell related.

**Comment by StefanTT** [comment]
If I look at the generated .desktop entry and what xprop for the Joplin window outputs then I have no good idea how the window manager should get the icon for the application.

A quick test with TeamViewer - one of the apps I have installed that did not come with the distribution - showed that they do not set StartupWMClass in the desktop entry but set the window property WM_ICON_NAME.

So either the setWindowIcon() that @blueorignal suggested or my workaround should be done. I doubt that other desktop environments currently find the correct icon.

**Comment by scollovati** [comment]
Thank you @StefanTT ! 
This worked also for Linux Mint 19 with Cinnamon 3.8.8

**Comment by develar** [comment]
@laurent22 Today evening (CET) electron-builder 20.26.0 will be released — `StartupWMClass` will be added correctly (thanks to @StefanTT).

**Comment by fmmarzoa** [comment]
@StefanTT workaround worked for me to in Ubuntu 18.04

**Comment by scollovati** [comment]
Actually today after reinstalling my OS (a clean install) I'm experiencing a problem with the tray icon

![screenshot from 2018-08-06 09-03-08](https://user-images.githubusercontent.com/20740642/43701785-cc95c3a4-9957-11e8-8357-ffb24f5b10c5.png)

I manually added the suggested line to the ` .desktop` file.
Still using Linux Mint 19 with Cinnamon 3.8.8, Kernel 4.15.0-20-generic

**Comment by laurent22** [comment]
Should be fixed with recently added install_ubuntu.sh script.
