### ISSUE TITLE
Dropbox API User Limit Reached

### ISSUE THREAD

**Issue by tsumare** [laurent22/joplin#860]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

### Issue

Attempting to link to Dropbox sync produces the following error message:

![image](https://user-images.githubusercontent.com/7296913/46576686-dbd0bb80-c995-11e8-948a-4366f81f59c2.png)
"This app has reached its user limit. Contact the app developer and ask them to use the Dropbox API App Console to increase their app's user limit."

**Comment by laurent22** [comment]
Normally the production Dropbox app doesn't have a user limit. Are you using the dev version of Joplin by any chance? If not, could you try again to connect as it might have been a one off thing.

**Comment by tsumare** [comment]
Oh! I was, yes. I have no option while I wait for #591, since there's no option to disable "singleton mode" altogether (though a --no-singleton might make a nice stopgap for #591).  I didn't realize the linkage website was different.  I'll make sure to configure my credentials in production mode.  I resolved this case by ripping the credentials out of the sqlite db on the other side of the sync.  Sorry for the trouble!
