### ISSUE TITLE
Some Items Cannot Be Syncronized

### ISSUE THREAD

**Issue by m10d** [laurent22/joplin#8601]
In some cases attachments can not be decrypted/downloaded (top level UI banner Message: "some items can not be syncronized", in the `view them now` page, it says `Items that cannot be decrypted`).

The behavior was already described in https://github.com/laurent22/joplin/issues/4403 and https://github.com/laurent22/joplin/issues/4472, https://github.com/laurent22/joplin/issues/4403, and presumably others but all were closed due to inactivity - thus not fixed.

Per advice in other issues:
- I have tried to delete the affected .crypted-files --> I do not have this `find ~ -type d -name '.crypted-files'` returns nothing.  I am on a **paid plan** / joplin-cloud, perhaps that's Dropbox specfiic?
- I have tried searching for the ID's on all devices - no results are returned (neither on the devices that give the error, and on the (one) mobile that does not.
- not aware of any other other way I can at least identify what file is not syncing?

Based on my specific reproduction, I have a (very tentative) hypothesis to what might have lead to the issue in MY case:  The error mentioned encrypting/corruption and _size_.  I generally don't put images in notes, except for recently I did from mobile.  I've used Joplin a long time across multiple devices and have not seen this until recently - and I'm pretty sure I only ever added images (via any method) very recently, via my Android with Joplin installed

## Environment

Joplin version: 2.9.17
Platform: linux
OS specifics: 
- `v2.9.17` on `ubuntu 20.04` desktop (**YES** displays the error)
- `v2.9.17` on `ubuntu 21.04` laptop (**YES** displays the error)
- `v2.10.8` via `F-droid / android` phone (does **NOT** show any error - although it's a different/mobile API so all I can say is no error is _apparent_ I suppose) 

## Steps to reproduce
I am guessing this is related to images from my android, but aren't sure

one trial with the following does NOT reproduce:
1. take pic on phone
2. make a new todo note, and attach the image
3. repeat steps with BOTH:
    - YES to joplin resizing it to 1920
    - NO to joplin resize; attach full ~6mb image
5. sync android, then sync linux
6. total count (13) of sync errors uid's remains same; image shows in the new notes on linux as I'd expect.

The other thing I would mention is that I recently use joplin in some really poor network conditions (lots of timeouts, web browsing for instance was really intermittent).  IDK, I just guess that's a less-stress-tested path.

## Describe what you expected to happen

well, that this bug doesn't not occur :)

But foremost, since this could lead to data loss (if the only device with the data is lost or fails, for instance) joplin should make it **EASY** to figure out exactly what data is not syncing.  

As it is I have **NO** way to figure this out - searching by the ID's in the top-level joplin search, linux or android, produces nothing.

**Comment by m10d** [comment]
@laurent22 @tessus Thank you for your work on this project.  I am a paid (joplin-cloud) user for several years.  

I feel this bug is both

- common enough (for a potentially severe issue) to merit a response
    -  (multiple prior issues have been opened, with numerous folks confirming it reproduces for them, with no clear fix or acknowledged actions the user should take)
- potential **data loss** 
    - (eg if my phone, which seems likely to have been the source the non-syncing data, is lost, as I understand it the data will be gone despite full sync's to multiple other devices)

All the previous issue get auto-closed when folks eventually give up.  

I humbly ask that you at least provide me a definitive way to:

- identify the resource that is failing to sync (eg search for it? how?)
- [hopefully] id the same resoure on my phone, where no errors are apparent and the resource theoretically exists so I can _manually_ back it up
- finally delete / purge that resource from joplin so I can get back to green (No errors)
- (after which I can continue use Joplin `safely`, and also attempt to create a reproduction intentionally, which might help this get actually fixed)

<respectfully including the next-highest commiter as well, in the hopes that at least decent triage steps can be added here>

**Comment by personalizedrefrigerator** [comment]
Here's a way to potentially get a more descriptive error message:

1. Open a desktop client that is unable to decrypt some items.

2. Click "Help", then "Toggle Development Tools"

![](https://github.com/laurent22/joplin/assets/46334387/1a136f65-4aac-4e38-b930-7e23d0d12a87)

3. In the sync warning, click "view them now"
![](https://github.com/laurent22/joplin/assets/46334387/90f85a4d-6a57-4842-9b56-b681e16a5e64)

4. Click "retry" next to a resource
![](https://github.com/laurent22/joplin/assets/46334387/7c5cb67d-cf4b-441b-8781-4d9af983227a)

5. Look for a DecryptionWorker warning in the console (click on the "Console" tab in the development tools).

![screenshot of a yellow warning that begins with DecryptionWorker: error for: b32e9cd...](https://github.com/laurent22/joplin/assets/46334387/34d28043-6afd-4b97-8d1a-94e0e1c94e56)

Thank you for reporting this!

> **Note**:
>
> If a client was recently upgraded to a more recent version (e.g. the Android client), this issue could be caused by the migration to AES-256 from AES-128. (Older clients don't understand how to decrypt the AES-256-encrypted items). In that case, see https://github.com/laurent22/joplin/issues/8446.

**Comment by m10d** [comment]
> Here's a way to potentially get a more descriptive error message:

>     1. Open a desktop client that is unable to decrypt some items.
>     2. Click "Help", then "Toggle Development Tools"
>     3. In the sync warning, click "view them now"
>     4. Click "retry" next to a resource
>     5. Look for a DecryptionWorker warning in the console (click on the "Console" tab in the development tools).

Thanks for the steps.  Here's what I see.  All ~13 resources are the same stacktrace:

    Logger.ts:219 15:26:33: DecryptionWorker: error for: 7180e777bab1456da554db15c6181d81 (resources) Error: Unknown decryption method: 7
    at EncryptionService.<anonymous> (EncryptionService.ts:398:52)
    at Generator.next (<anonymous>)
    at /tmp/.mount_joplinHA…tionService.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/.mount_joplinHA…tionService.js:4:12)
    at EncryptionService.decrypt (EncryptionService.ts:393:73)
    at EncryptionService.<anonymous> (EncryptionService.ts:472:33)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_joplinHA…tionService.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5) 


> Note:
> If a client was recently upgraded to a more recent version (e.g. the Android client), this issue could be caused by the migration to AES-256 from AES-128. (Older clients don't understand how to decrypt the AES-256-encrypted items). In that case, see https://github.com/laurent22/joplin/issues/8446.

Hmm - I could not tell you when the Android updated, that should be automatic.  While my desktop `v2.9.17` would appear to be old / unaware of the new scheme, my Android `v2.10.8` is **also** old meaning it should not have caused this.

**Comment by personalizedrefrigerator** [comment]
> Error: Unknown decryption method: 7

The new encryption method has ID 7 — this suggests that an updated client synced and started updating the encryption method on some notes. Thus, upgrading should (hopefully) fix this.

To see whether the Android device is dong this, try modifying a specific note on the Android device, then syncing. If the Android device is new enough to use the new encryption method, the note should be re-encrypted using that method and thus undecryptable by the desktop clients. 



Please let me know whether this helps!

**Comment by m10d** [comment]
Ok, so I've updated my linux Appimages to `2.11.11` and the **issue resolves**

This reminds me that a week or so ago, I had to briefly install Joplin on a windows computer.  That PC is since un-installed - but given your statement about `ID 7` being the new encryption error, and the fact that the issue resolves upon upgrading past the change, that seems like the smoking gun.  All three of my clients are now showing no errors. 

This leaves me with one question, though.  It seems the fact that my android had "no errors" was just a red herring.  Did android `v2.10.8` (A) have errors as well and just not make it obvious to me; or (B) does 2.10.8 contain AES256 support, or (C) is there something else possibly going on with that?

Thank you.  Assuming that (A) or (B) (not C) is true, then this is resolved.  Given how this issue seems to occur with some frequency, I would hope that the reporting to the user can be made more robust/future proof, but I recognize that is a Feature Request not a Bug.

**Comment by personalizedrefrigerator** [comment]
To see whether the Android device is unable to decrypt some notes, go to Configuration > Sync Status and click "refresh". If decryption-related errors are visible, the ~~Android device~~ Android app needs to be upgraded. (The error message not showing should be fixed by https://github.com/laurent22/joplin/pull/8481).

If your Android package manager doesn't have the latest version of Android, you can download [a more recent release from the Android releases repository](https://github.com/laurent22/joplin-android/tags) or from Google Play.

**Comment by frenciszak** [comment]
> the Android device needs to be upgraded

I'm sorry, do I understand correct that to be able to use Joplin I need new phone? Or upgrade my phone system ?

**Comment by Stargirl0** [comment]
RESOLVED: IT WAS ONEDRIVE absolute fecking nightmare.   
 Sorry, new to this type of language and set up. Need to post a bug issue with syncing on multiple devices.  Joplin to onedrive. Have Windows 11, Samsung note 6 lite (newly purchased) Samsung A71. Each device is creating its own folder.  Onedrive is updated on each device.  Not sure if user error and how to resolve this. Many thanks for your time.

**Comment by personalizedrefrigerator** [comment]
> > the Android device needs to be upgraded
> 
> I'm sorry, do I understand correct that to be able to use Joplin I need new phone? Or upgrade my phone system ?

Sorry!!! I meant to write "Android app"!

The original source of this issue was different Joplin clients using different encryption methods — ensuring all clients are the latest version was the proposed solution.
