### ISSUE TITLE
Translation question

### ISSUE THREAD

**Issue by milotype** [laurent22/joplin#8607]
Please explain the "%s" in the following translation string.
```
#: packages/app-mobile/components/voiceTyping/VoiceTypingDialog.tsx:89
msgid "Downloading %s language files..."
msgstr ""
```

- Is it the name of the language (English, Croatian, etc.)?
- Is it a number/count? (If it's a number, please provide a plural form for it)

**Comment by laurent22** [comment]
It is the name of the language. So for example "Downloading English language files..."

**Comment by milotype** [comment]
Thank you for the explanation.
