### ISSUE TITLE
Include preinstalled Notebook with notes on configuration (readme.md info)

### ISSUE THREAD

**Issue by Jakethethird** [laurent22/joplin#861]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

I am installing Joplin for the first time and it is taking me a while to figure out the configuration (on Nextcloud - Joplin folder configuration necessary before sync etc.). The info is here on GitHub in the readme.md doc plus on your faq section on your website.
It would be really useful if the sections in the readme.md file were included as a default set of notes in a preinstalled Joplin Setup notebook. Also possibly a markdown cheatsheet note could be added. This notebook and notes could be deleted by the user afterwards.

**Comment by foxmask** [comment]
I like the idea. Could also be an help section inside Joplin.

**Comment by foxmask** [comment]
May be 2 notes with differents title :
* "Welcome to Joplin Desktop" on joplin-desktop
* "Welcome to Joplin Mobile" on joplin iOs/Android
