### ISSUE TITLE
Check that we can update the emoji lib

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8616]
Please test this pull request locally and verify that our emoji lib integration is still working: https://github.com/laurent22/joplin/pull/8613

It is used when setting a notebook icon

**Comment by hubertfilho** [comment]
Hi,

It isn't working. In fact, I even couldn't ran the app-desktop:

![image](https://github.com/laurent22/joplin/assets/19213902/cb907bf2-7d66-4767-8932-faad69c5f0a3)

**Comment by laurent22** [comment]
Ok it's an es module, so we don't upgrade
