### ISSUE TITLE
 Ubuntu > Joplin Server > Android Sync - 2 notes not syncing

### ISSUE THREAD

**Issue by blackfrank74** [laurent22/joplin#8618]
## Environment

Laptop
Joplin version: Joplin 2.11.11 (prod, linux)
Platform: Linux
OS specifics: Ubuntu 22.04.2 LTS 64 bit

Joplin Server
Joplin version: Joplin Server v2.12.1, copyright © 2021-2023 JOPLIN.
Platform: Asustor NAS
OS specifics: ADM4.2.2.RI61

Android phone
Joplin version: 2.11.32
Platform: Samsung Galaxy S10+
OS specifics: Android 12

Android tablet
Joplin version: 2.11.32
Platform: Samsung Galaxy Tab S7
OS specifics: Android 13

## Steps to reproduce

1. On 3/8 I created 2 notes on the laptop which refuse to sync to either of the Android devices
Both notes are titled Newcastle Permanent, and the note properties are:

---------------------
Note 1
Note properties
Updated
03/08/2023 21:46
Created
03/08/2023 21:46
URL
Location
33° 52′ 7.75″ S, 151° 12′ 33.46″ E
Note History
Previous versions of this note
Markup
Markdown
ID
599bb3cfceab496f975734bdaaaf9584

---------------------
Note 2
Note properties
Updated
03/08/2023 21:46
Created
03/08/2023 21:45
URL
Location
33° 52′ 7.75″ S, 151° 12′ 33.46″ E
Note History
Previous versions of this note
Markup
Markdown
ID
990855deba2c445fa255d31ad83ffe59

---------------------

These 2 notes refuse to sync to the Android devices.
 They are very simple notes, consisting of a 2 word note title, and an embedded print screen - example
![image](https://github.com/laurent22/joplin/assets/34759786/1fd884cd-8584-49e5-a27c-2804fd9829e7)

This very similar note have successfully synced over to both Android devices
![image](https://github.com/laurent22/joplin/assets/34759786/28625540-433d-4c17-a404-89cdc6de72b3)

The Android logs last error was on 31 July/1Aug which predate these notes.

What is preventing the 2 notes from syncing?

## Describe what you expected to happen

The 2 notes should sync to the Android devices.

## Logfile

The Android logs last error was on 31 July/1Aug which predate these notes.
Ubuntu device log files included on https://github.com/laurent22/joplin/issues/8656

**Comment by blackfrank74** [comment]
Hi team - any feedback or questions?
The notes still have not synced.
This is an opportunity to fix bugs in the Joplin server beta code so that it moves closer to production ready status

**Comment by personalizedrefrigerator** [comment]
I'm suspicious that either Joplin or Joplin server incorrectly handles interruptions/errors while updating resources/files on the server (see the EHOSTUNREACH and related errors in the log). [If this is the case, this issue may be related.](https://github.com/laurent22/joplin/issues/8509#issuecomment-1642867031)

Please also make sure that the date/time is roughly correct on all devices — an incorrect date/time has also been reported to cause sync issues.

I plan to try to reproduce this by:
1. Attaching a large file to a note in Joplin
2. Starting a sync
3. Either:
    - Closing Joplin during the sync. (**Edit:** In this case, sync seems to work again after re-opening and syncing the closed client.)
    - Closing Joplin Server during the sync (still needs to be tested)
    - Disconnecting the device with Joplin server from the internet during sync (still needs to be tested)
4. Checking to see whether the item was synced successfully.


Thank you for reporting this!

**Comment by blackfrank74** [comment]
Thank you for the update, happy to help/test/whatever to get this sorted,
though i may be slow in doing so as my little kids take a lot of my time.

**Comment by personalizedrefrigerator** [comment]
It could be related to sync/decryption errors. If you're using encryption, please check "Configuration" > "Sync Status" for decryption errors on the Android device. In Joplin 2.11 for Android, the "some items failed to decrypt" warning doesn't display on the main page.

**Comment by blackfrank74** [comment]
I do not use encryption anywhere (at this time).
Eg Ubuntu laptop - shows "encryption: disabled"
And Android devices (x 2) - encryption config button - shows "encryption is: disabled"
I'm sending data around on my LAN only and did not want to add additional potential points-of-failiure while trialling Joplin.

**Comment by blackfrank74** [comment]
Hi, 

My inter-device performance is getting progressively worse. 

For the past 2 weeks+ notes creating on my android devices have not been syncing to the Ubuntu laptop, and new items on the Ubuntu laptop have not been syncing to Android at all.

Over the weekend I noted that the Joplin Server version on the ASUSTOR repository is 2.4.2.r02 - last updated Sept 2021.
https://www.asustor.com/app_central/app_detail?id=1416&type=0&model=
Maintainer is patrickhsu.ast@gmail.com

Is this repo updateable by someone at the Joplin end?

Cheers

**Comment by andrewdolphin** [comment]
Hi. A couple of questions. What are the file sizes of the files that don't sync? Are you using locally only or using any web proxy for access?

**Comment by blackfrank74** [comment]
Hello 

File sizes:
a208c83374c58efeadec100fe1d2b909.png = 80.9kb
The other would be very similar in size.
When I go Tools/Note Attachments I see png attachments ranging up to 4.7MB

Access:
I sync to a local Joplin Server instance being http://192.168.0.208:22300
All my devices point to here.
I do not use a web proxy, the "proxy enabled" tick box under Tools/Options/Synchro/Show Advanced Settings is NOT ticked.
