### ISSUE TITLE
Desktop: Enable/Disable search term highlighting OR do not instantly search on "clear"

### ISSUE THREAD

**Issue by archont00** [laurent22/joplin#862]
### Operating system
- Linux

### Application
- Desktop, Joplin 1.0.111 (prod, linux), AppImage

### Description
Searching a term via the search bar correctly identifies all notes containing the search term. The search term is also highlighted in the Preview layout.
**If the user wants to work with some of the found notes, it is better to turn off the highlighting to avoid distraction.**
However, there is no other way to do so than to cancel the search - which instantly changes the focus to the first note of an active Notebook.

### Expected behaviour
**I would expect that the note having been selected manually after the search would remain focused also when I clear the search box** (i.e. "instant" search will be off termporarily until I start typing a new search term).
Alternativelly, there could be a button to enable/disable search term highlighting.

### A workaround
So long as the users has 'Sort by date' set, it helps to edit the selected note and only then to cancel the search. As a result, the note would be shown as the first one in the Notes list within a Notebook and it will remain in focus.

**Comment by i-need-to-tell-you-something** [comment]
>I would expect that the note having been selected manually after the search would remain focused also when I clear the search box

This seems to be working for me on Joplin 1.0.152 (prod, linux).

**Comment by tessus** [comment]
Has been fixed for a while now. Closing.

**Comment by archont00** [comment]
Indeed. Thanks.
