### ISSUE TITLE
Sync date format on desktop app is UK only

### ISSUE THREAD

**Issue by shyun3** [laurent22/joplin#8620]
My language in the desktop app is set to US English but the synchronization date appears to follow DD/MM/YYYY:
![image](https://github.com/laurent22/joplin/assets/10998824/d9f2d586-04bc-45ce-a2ea-de1f11e5fcd5)

## Environment

Joplin version: 2.11.11
Platform: Windows
OS specifics: Windows 10 Home 22H2 19045.3208

## Steps to reproduce

1. Turn on sync
2. Click on "Synchronize"
3. Wait for sync to finish and confirm the date format

## Describe what you expected to happen
The image above shows the date as 05/08, but this took place on August 5th. So in the US format, it should be displayed as 08/05/2023.

## Logfile

I see several similar warnings in the console:
```
DevTools failed to load source map: Could not parse content for file:///C:/Users/shyun3/AppData/Local/Programs/Joplin/resources/app.asar/ResourceScreen.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/shyun3/AppData/Local/Programs/Joplin/resources/app.asar/Navigator.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/shyun3/AppData/Local/Programs/Joplin/resources/app.asar/WelcomeUtils.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/shyun3/AppData/Local/Programs/Joplin/resources/app.asar/gui/note-viewer/pluginAssets/mermaid/mermaid.min.js.map: Unexpected end of JSON input
```
There are several more such warnings, let me know if you need all of them.

**Comment by dpoulton-github** [comment]
The date format is not controlled by the language setting but by the date setting below it.

In my case I use YYYY-MM-DD and it is reflected in the sync date format.

![setting](https://github.com/laurent22/joplin/assets/60117449/d4c3d034-0cea-4fc8-a070-bbb66484b3dd)
![sync](https://github.com/laurent22/joplin/assets/60117449/59be0bc1-a082-486d-bdc7-cd1a81eac234)

**Comment by shyun3** [comment]
Oh, I completely forgot about the options page. Thanks!
