### ISSUE TITLE
Navigation (Go Back) should go back to previous positions

### ISSUE THREAD

**Issue by benintech** [laurent22/joplin#8621]
This issue affects both Desktop and mobile (Android) app

Suppose you click on a link internal to a note (e.g., a link to an anchor, for example a TOC entry). If you hit the back button, I think you should go back to the previous position inside that note. But that's not the case, it leaves the note entirely and goes back to the previous note.

That behavior makes the navigation between anchors of a note impossible.

**[Update]**
Another point : in the mobile app, switching between View mode and MD mode always takes us to the top of the note. IMO it should stay at the position it was when switching.

**Comment by taw00** [comment]
See also: https://discourse.joplinapp.org/t/save-cursor-location-and-navigation-history-between-joplin-sessions/30743

What I would like to see is for Joplin to retain cursor location information throughout the application. Did you just clicked into a notebook? Then go to the same note you were in that notebook and the exact position you were last at in that note.  Now, retain this information for every note and notebook, and have it remain true between closing the application and opening it again. And if something changes outside of this instance that makes the location indeterminant, then have a sensible fall-back behavior.

And, as you said, the back button should work as one would expect and take you back to the prior position. Joplin would have to track the last position in every note, the last visited note in every notebook, and a generalized position history for the forward and back buttons.

**Comment by benintech** [comment]
Not fixed. I think a Joplin developer should say if it's a good idea, or dismiss the idea (and thus close this issue).

**Comment by benintech** [comment]
[Not fixed](https://github.com/laurent22/joplin/issues/8621#issuecomment-1734078887).

**Comment by benintech** [comment]
[Not fixed](https://github.com/laurent22/joplin/issues/8621#issuecomment-1734078887).

**Comment by benintech** [comment]
[Not fixed](https://github.com/laurent22/joplin/issues/8621#issuecomment-1734078887).

**Comment by benintech** [comment]
[Not fixed](https://github.com/laurent22/joplin/issues/8621#issuecomment-1734078887).

**Comment by benintech** [comment]
[Not fixed](https://github.com/laurent22/joplin/issues/8621#issuecomment-1734078887).
