### ISSUE TITLE
Joplin erased my synchronization password after auto-update

### ISSUE THREAD

**Issue by nickrbogdanov** [laurent22/joplin#8625]
I am running Joplin Desktop (GUI) on macOS, and synchronizing to a locally hosted Joplin Server (Beta) instance.

Recently Joplin updated itself to 2.12.10.  Around the same time, I noticed that synchronization would get stuck forever on this system.  The sync progress icon would keep spinning forever, and if I clicked Cancel, it would get stuck canceling forever too.

I enabled logging per https://joplinapp.org/debugging/ and saw an error in the JS console that indicated that the server was rejecting my login name or password.  I went into the Joplin preferences and re-entered my password.  Prior to re-entering the password, the field was blank; it did not show up as "********".  After doing this, Joplin worked again normally.

I have never changed this password on the server side and I didn't mess with the synchronization settings myself.  I suspect that Joplin erased this password due to some sort of settings migration bug.

Also, I am confused as to why Joplin auto-updated to 2.12.10 if the latest public release is 2.11.11?  I have not opted into prereleases:

![image](https://github.com/laurent22/joplin/assets/63979903/03b640e2-6acf-4773-b992-780bb784cf46)

![image](https://github.com/laurent22/joplin/assets/63979903/3c7bff86-d221-41f6-8af2-175d183ff689)

**Comment by laurent22** [comment]
I believe this is because you upgraded to the ARM64 version and it does not have access to the same keychain access as the non-ARM64 version, thus it cannot see your password and it needs to be re-entered. We are working on a fix to make this more intuitive starting from next version

**Comment by personalizedrefrigerator** [comment]
We've applied an error message fix for WebDAV, but it seems that (at least) these sync targets still need to be updated:
- [ ] NextCloud
    - See https://discord.com/channels/610762468960239627/610762468960239629/1135845095204204594
- [ ] Joplin Server 

I plan to work on addressing this over the next week.

**Comment by personalizedrefrigerator** [comment]
When I test locally, I'm getting the following error:

<img width="238" alt="Screenshot: Error: Invalid username or password." src="https://github.com/laurent22/joplin/assets/46334387/1363271b-01b6-407e-96fc-6f144cfa5071">

I was running Joplin Server (built from 3d4740203f0decbbdb9d5a25cf6038f72e69e097) in development mode on `localhost` without `https` or a reverse proxy, however (I plan to try that next).

**Comment by personalizedrefrigerator** [comment]
May be fixed by https://github.com/laurent22/joplin/pull/8644
