### ISSUE TITLE
Joplin failes to render apostrophe in notes on computer and android devices

### ISSUE THREAD

**Issue by s1-ranjan** [laurent22/joplin#8628]
## Environment

Joplin version: 2.11.11 (prod,linux)
Platform: Linux
OS specifics: Linux Mint 

## Steps to reproduce

1. When I type I'm
2. It gives output as
3. I÷m

## Describe what you expected to happen
I expect when I type I'm it should be rendered properly on every device.

**Comment by laurent22** [comment]
Could you export a note showing this problem as a JEX file?

**Comment by s1-ranjan** [comment]
I have included the file with the issue.
[Here_s  the file showing the issue.jex.zip](https://github.com/laurent22/joplin/files/12304251/Here_s.the.file.showing.the.issue.jex.zip)
Please have a loo.

**Comment by laurent22** [comment]
We cannot replicate this issue, so it might be something specific to your computer. Maybe a font or something similar
