### ISSUE TITLE
Searching for partial string doesn't return anything

### ISSUE THREAD

**Issue by davemeier** [laurent22/joplin#8634]
I was searching for a number in one of my notes and it wouldn't find it unless I search for the entire number (e.g. searching for "122115" fails, but "122115897" succeeds).

## Environment

Joplin version: 2.11.11
Platform: Mac OSX
OS specifics: Ventura 13.5

## Steps to reproduce

1. Create a note with 122115897 in the body of the note.
2. Search for 122115 -> no note is returned from the search.
3. Search for 122115897 -> the note is returned from the search.

## Describe what you expected to happen
Note should be found with partial match, not entire word match being required.

**Comment by JackGruber** [comment]
From the documentation:
![grafik](https://github.com/laurent22/joplin/assets/24863925/2f2dda8d-9098-4da8-b0d9-178c8c77c9c0)
https://joplinapp.org/help/#searching

You can add a wildcard `122115*`

**Comment by davemeier** [comment]
Confirmed using wildcard works fine - thank you @JackGruber!
