### ISSUE TITLE
Can't open joplin://x-callback-url link in android mobile app

### ISSUE THREAD

**Issue by GonzRon** [laurent22/joplin#8639]
Support external links in android mobile so I can create This for Joplin: 

https://github.com/GonzRon/evernoteNFC

**Comment by yajo** [comment]
Being able to generate these links from notes within the android app would be the same or a separate request?

**Comment by roman-r-m** [comment]
> Being able to generate these links from notes within the android app would be the same or a separate request? 

I suppose it can be done separately but there's not much point in having one without the other

**Comment by GonzRon** [comment]
Hi there good question, the current workflow for ever note is to share the note with the external app, which passes an internal note link to the target app that can then be used to open the note directly in evernote later, ( app specific note URL with an android view intent ).  The idea here is the same, to provide a facility to share the note link to the external app, and then be able to launch Joplin and display the note using the note link. 

I can open a separate ticket for the "generate or share" note link functionality if you desire.

**Comment by yajo** [comment]
@laurent22 asked to create this issue: https://github.com/laurent22/joplin/issues/5168#issuecomment-1067908776

So I think this should not stale. But if you want the forum, you have https://discourse.joplinapp.org/t/android-callback-links/24430 (which is also blocked, BTW).

**Comment by saltlakeryan** [comment]
I would love to see this feature implemented on Android
