### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by TuTAH1** [laurent22/joplin#8643]
![image](https://github.com/laurent22/joplin/assets/15982179/abf868bc-5606-4199-9430-50e839693054)

The way localization handle this entry doesn't allow me to translate it correctly. It should be "Создание новой задач**и**"/"Создание новой заметк**и**", but the single buttons should be "+ задача/+ заметка" (as now)

**Comment by CptMeetKat** [comment]
Looking into this
