### ISSUE TITLE
Search not working (on Windows version)

### ISSUE THREAD

**Issue by bovergaauw** [laurent22/joplin#8646]
Joplin version: 2.11.11 (prod, win32)
Platform: Windows
OS specifics: Windows 10 Professional 22H2 x64

Steps to reproduce

1. Click "All notes"
2. Click Search..." field
3. Enter search term that you know is in one of the notes

I expect the notes with the search term to be listed. However, in the majority of cases, after just one or two letters, I get the message "No notes in here. Create one by clicking on "New note"."

**Comment by JackGruber** [comment]
From the documentation:
![258908234-2f2dda8d-9098-4da8-b0d9-178c8c77c9c0](https://github.com/laurent22/joplin/assets/24863925/6544f3d3-2f5a-468c-bee9-25c6200ba107)

https://joplinapp.org/help/#searching

See also https://github.com/laurent22/joplin/issues/8634

**Comment by Roshan-Pawar** [comment]
This can be done without using the wildcard right..?, we can add a feature that can match the words in search bar with out note's.

**Comment by bovergaauw** [comment]
> This can be done without using the wildcard right..?, we can add a feature that can match the words in search bar with out note's.

The wildcard option works, but I agree that a setting or option to search for partial matches without wildcards would be very useful.
