### ISSUE TITLE
Note content does not refresh after sync

### ISSUE THREAD

**Issue by alondmnt** [laurent22/joplin#8652]
Note content does not refresh after sync.

## Environment

Joplin version: 2.12.10
Platform: macOS
OS specifics: Ventura 13.4.1 (arm64)
Sync: File system

## Steps to reproduce

1. Open a note on device A.
2. Edit the same note on device B.
3. Sync B, then sync A.
4. The note does not refresh on device A.
5. Switch to a different note and back, and the content changes.

## Describe what you expected to happen

In version 2.11 the same process works (note content refreshes immediately after sync).

**Comment by laurent22** [comment]
On which editor? The Markdown one? And are you sure that was working in 2.11?

**Comment by personalizedrefrigerator** [comment]
I can reproduce this with both the markdown editor and the rich text editor.

**Edit**: At least in the markdown editor, it sometimes updates automatically after sync, but this seems to happen about 20 seconds after sync finishes.

**Comment by alondmnt** [comment]
Thank you!
