### ISSUE TITLE
Android > Joplin Server >  Ubuntu Sync - pdfs not syncing

### ISSUE THREAD

**Issue by blackfrank74** [laurent22/joplin#8656]
Laptop
Joplin version: Joplin 2.11.11 (prod, linux)
Platform: Linux
OS specifics: Ubuntu 22.04.2 LTS 64 bit

Joplin Server
Joplin version: Joplin Server v2.12.1, copyright © 2021-2023 JOPLIN.
Platform: Asustor NAS
OS specifics: ADM4.2.2.RI61

Android phone
Joplin version: 2.11.32
Platform: Samsung Galaxy S10+
OS specifics: Android 12

Android tablet
Joplin version: 2.11.32
Platform: Samsung Galaxy Tab S7
OS specifics: Android 13

## Steps to reproduce

1.  On 12/8 I created a new pdf scans on my Android phone.
2. I shared this pdf to Joplin on Android, a new Joplin note is created
3. I synced Joplin on the Android device to the Joplin server
4. Joplin on Android processes/indicates the file had been synced into the Joplin server   
5. ![tempFileForShare_20230812-115307](https://github.com/laurent22/joplin/assets/34759786/6fc994aa-33dc-4a53-b891-2d9a0476b3bd)
6. I sync the Ubuntu device with the Joplin server.
7. The Ubuntu device updates from the Joplin server.
8. The wrapper/shell/structure of the note is created
9. ![image](https://github.com/laurent22/joplin/assets/34759786/bbde4b86-782a-46d2-af45-2fd243d5a1ee)
10. But when I click the pdf link on the Ubuntu device (far right on screenprint 8), nothing happens - the pdf should open
11. On Ubuntu, I search /.config/joplin-desktop/resources for cfdea62776334ac2a94874c1078cce88 - no hits
12. It seems the note structure is synced, but not the attachment
13. I have reproduced this behavior on 4 different notes times in 30 minutes
 

## Describe what you expected to happen
Per above - the full note + pdf attachment/s should fully sync between devices so that it is consistently viewable everywhere 

## Logfile

[joplin console.txt](https://github.com/laurent22/joplin/files/12326224/joplin.console.txt)
[joplin log.ods](https://github.com/laurent22/joplin/files/12326225/joplin.log.ods)

Note - the this issue refers to pdf sync issues, whereas https://github.com/laurent22/joplin/issues/8618 refers to whole-of-note sync issues

**Comment by Akhilbisht798** [comment]
Is this happening with only pdfs? And as per your issue the note are properly syncing unlike #8618 but only pdf are syncing.

**Comment by blackfrank74** [comment]
Hello Akhil, i will need to test as i dont recall.

**Comment by Akhilbisht798** [comment]
@blackfrank74 . Do you have any report on it?

**Comment by blackfrank74** [comment]
Hi Akhil

At the time 8618 was reported, all attachments seemed to sync ok (other pdfs, jpgs etc)-  those 2 notes were not syncing.
A week later 8656 was logged, at that time my Joplin was starting to become unstable and I detected that pdfs were not syncing.
As noted on https://github.com/laurent22/joplin/issues/8618#issuecomment-1695297020 my Joplin server version seems very old, could be a possible cause.
I'm asking around to see if it can be updated.

**Comment by blackfrank74** [comment]
Hi Akhil
At the time I 1st logged this issue, I was only experiencing problems on pdfs.
Since then though things have been getting worse, as noted in https://github.com/laurent22/joplin/issues/8618#issuecomment-1695297020 - given the Asustor repo Joplin version seems outdated, that should maybe be the 1st thing to look into fixing.
 Thoughts?
