### ISSUE TITLE
s3 sync error: TemporaryRedirect

### ISSUE THREAD

**Issue by ben-kenney** [laurent22/joplin#8658]
I'm exploring using s3 sync for the first time and so I started a new Joplin profile to test it out. I'm somewhat confident that my bucket is set up correctly because I can copy files using the `awscli` tool with the same credentials that I'm using in Joplin. I've also tried using a policy that allows all s3 permissions to my bucket but I get the same error message.

The error(s) that I'm seeing:
1. When setting up the sync configuration and clicking `check synchronization configuration`:
```
Error. Please check that URL, username, password, etc. are correct and that the sync target is accessible. The reported error was:
UnknownError
```
2. When ignoring the above and trying to sync:
```
Last error: TemporaryRedirect: Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.
```
3. As far as I can tell this is a relevant part of the debug log (more complete log can be found here https://pastebin.com/yFhkeTfF):
```
Logger.ts:237 09:13:01: Synchronizer: TemporaryRedirect: Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.
    at throwDefaultError (/tmp/.mount_Joplin7IP9g3/resources/app.asar/node_modules/@joplin/lib/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_restXmlDeleteObjectCommandError (/tmp/.mount_Joplin7IP9g3/resources/app.asar/node_modules/@joplin/lib/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:3572:43)
```

## Environment

Joplin version: 2.11.11
Platform: Linux (app image install using recommendend bash script)
OS specifics: Ubuntu

## Steps to reproduce

1. I followed [these directions](https://blog.jfx.ac/syncing-joplin-notes-to-aws-s3.html) for setting up s3 bucket/user/policy. Confirmed they work using `awscli`.
2. Configuration screenshot:
![screenshot](https://github.com/laurent22/joplin/assets/2074287/428438a2-f647-451c-87fc-b91f66b6ea04)

 

## Describe what you expected to happen

Expected to be able sync to my s3 bucket

## Logfile

My debug log can be found here: https://pastebin.com/yFhkeTfF

**Comment by personalizedrefrigerator** [comment]
From the [S3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingRouting.html#TemporaryRedirection):
> A temporary redirect is a type of error response that signals to the requester that they should resend the request to a different endpoint. Due to the distributed nature of Amazon S3, requests can be temporarily routed to the wrong facility. This is most likely to occur immediately after buckets are created or deleted.
>
> [...]
>
> [...] **Temporary redirects contain a URI to the correct facility, which you can use to immediately resend the request.**

(emphasis added).


Thus, it seems that:
1. [Now that a few days have passed, S3 sync might work.](https://repost.aws/knowledge-center/s3-http-307-response)
2. Joplin should be handling this error and forwarding the request to the correct URI.

**Comment by ben-kenney** [comment]
Yes, you're right! I can confirm I am now able to sync to s3, all it took was some time. I'm not sure if this is a bug or not given your point 2 above but at least this is resolved.
