### ISSUE TITLE
joplin 外部编辑器打开按钮

### ISSUE THREAD

**Issue by x2358473** [laurent22/joplin#8677]
In version v2.12.10, I found that the "Edit in External Editor" button in the top menu of the notes display only in markup mode cannot be clicked. You can only right-click in the note list on the left and select 'Edit in External Editor'

**Comment by dpoulton-github** [comment]
If using the Markdown editor in viewer layout only mode the external editor button and the menu **Note** > **Toggle external editing (Ctrl+E)** options are not available. They *are* available if the editor is active (editor only / split view layouts).

However you are right in that the note list right-click menu lets you trigger an external edit in *any* layout and it works. It seems that the logic is not consistent.

**Comment by x2358473** [comment]
已经在最新的2.12.15中修复了这个问题。特此关闭

This issue has been fixed in the latest 2.12.15. Hereby closed
