### ISSUE TITLE
Joplin mknote from terminal is very slow

### ISSUE THREAD

**Issue by jbriales** [laurent22/joplin#868]
### Operating system
- Linux

### Application
- Terminal

Creating a note from a shell, via `joplin mknote ...` is very slow (it takes 1-2 seconds, sometimes even more, up to 10 seconds).
Any reason why this might be happening?

**Comment by foxmask** [comment]
A Sync is also in progress or another mknote ?
What's the "top" show you about the computer when that's happening?

**Comment by laurent22** [comment]
Hard to tell why it's so slow. 1s could be possible, but 10 is way too much. Do you have many notes?

**Comment by jbriales** [comment]
10s might have happened only once for some random reason,
but 1s is common. Still 1s seems slow for a "simple" operation, doesn't it? Why might that happen?
I have around 300 notes.

**Comment by foxmask** [comment]
You can use the Joplin API with curl for example to " post " note see ://joplin.cozic.net/api/

**Comment by shankargopal** [comment]
I can confirm this problem. On a 32 bit Debian system, mknote takes between 3 - 4 seconds to complete. So does `joplin mknote set <note> body <text>`.  My system has slow disk I/O for a number of reasons, but that still seems like a very long time for these operations.  Are there a lot of read/writes involved? 

I cannot test out the API access, as I am running on a 32 bit Linux system and the desktop application AppImage does not work (and so far I have not been able to get it to build either).
