### ISSUE TITLE
jump-to-folder doesn't move the focused folder in the visible area of the notebook pane

### ISSUE THREAD

**Issue by truegreyhound** [laurent22/joplin#8681]
Do a search, select a note and click on the button with the displayed notebook name of the note. 

## Environment

Joplin version:  2.12.10
Platform: Windows 10
OS specifics: 22H2

## Steps to reproduce

1. open Joplin, there must be (much) more notebooks than can be displayed in the list of notebooks
2. scroll to the end of the notebook list, click on one of the last notebooks with Notes and make a note of it (prominent search term)
3. close joplin
4. open joplin
5. do a search with the memorized term
6. select a note in the result list
7. click on the button with the displayed notebook name of the note

## Describe what you expected to happen
I know the focus is now on the notbook shown in the button.
But, the notebook is not in the visible area of the notebook list. I now have to catch the scrollbar button and scroll through the notebooks list to find the focused notebook. This is tedious and time consuming, often having to scroll up and down several times to discover the notebook with the focus.

Why is the list of notebooks with the focused notebook not moved to the center of the visible area?

Or do I need to change a configuration setting to do this?

**Comment by CptMeetKat** [comment]
Looking into this.

**Comment by truegreyhound** [comment]
Yes, #8922 seems to solve the problem. When can we expect this version?
