### ISSUE TITLE
No email sent to confirm the share (folder)

### ISSUE THREAD

**Issue by adminapc262** [laurent22/joplin#8683]
[podlog_v2.txt](https://github.com/laurent22/joplin/files/12362317/podlog_v2.txt)
Environment
Joplin version: Joplin 2.11.11 
Joplin server version: 2.7.4
Platform: (prod, win32)
OS specifics: 10

Steps to reproduce

Right click on notebook.
Click on "share notebook".
Add joplin user email (previously added on Joplin server).

No email sent to confirm the share

**Comment by dwarf-king-hreidmar** [comment]
I am having the same issue. Other emails are sent. 
Joplin Server Version 2.11.1-beta & 2.12.1-beta

I do get other email such as account confirmations

I do have sharing notebooks enabled.

**Comment by dpoulton-github** [comment]
Is there supposed to be a "share notebook" email? The accept / reject appears to take place in the client itself.

![screenshot](https://github.com/laurent22/joplin/assets/60117449/ef29966c-217f-4a4e-a12e-82af9c6c68a8)

Joplin Client: 2.11.11
Joplin Server: 2.12.1

**Comment by adminapc262** [comment]
No Email Sent. The mobile app does not receive the accept / reject (share notebook) affirmative action. You have to use the client (desktop software) first, then the shared notebook will appear in the mobile app.
