### ISSUE TITLE
Inconsistent tab width between editor and preview

### ISSUE THREAD

**Issue by Kroc** [laurent22/joplin#8694]
Hard tabs in pre-blocks do not render as next 8th-character tab-stop in the markdown editor vs. the preview making it difficult to align monospace text.

Joplin 2.11.11 (prod, win32)

Client ID: 11bf38a5b53c45308ff91736a06f94ae
Sync Version: 3
Profile Version: 43
Keychain Supported: Yes

Revision: 6886f6f

![image](https://github.com/laurent22/joplin/assets/142650/0e4313ec-5267-4d73-bcc7-e21f6d01b465)

**Comment by hubertfilho** [comment]
@laurent22, for you information:

I worked on this issue but unfortunately I couldn't figure it out any simple solution to the problem.
Even changing the number of tab spaces to 8 or 12 the problem continuous...
I looked for a TinyMCE demo and even in the demo the tab is inconsistent between the editor and the preview. So, maybe it's not work as we expected in the TinyMCE.
As I had other things to do I prefer to put this issue in stand by to working in other things.
I believe there's a way to fix it, but maybe we need to implement something, and not only change the TinyMCE configuration.
