### ISSUE TITLE
large email-to-inbox slows Joplin to a near standstill

### ISSUE THREAD

**Issue by taw00** [laurent22/joplin#8698]
I haven't used the Joplin Cloud-enabled email-to-inbox feature before. So, I decided to do a simple test run to see how it worked and where the note shows up. The email was simple but had an embedded image (a 4.2MB) image ...

Subject line: Test Note
Body:
How about this?
![PXL_20230711_205104310 PORTRAIT](https://github.com/laurent22/joplin/assets/6908872/0d315b4b-de59-4a24-965d-43b5fc081317)

-- 
Todd Warner
</END OF BODY OF EMAIL>

I turned on dev logging, but I haven't seen anything odd. The application is not truly halted, but so slow as to be unusable. For example, it takes minutes for the note just to load up. I can't delete the note since the UI is effectively stalled. I will add new information to this issue as I discover it. Maybe you can recreate it with what I provided here.

**Comment by taw00** [comment]
[log.txt](https://github.com/laurent22/joplin/files/12388750/log.txt)
Log file attached. What I did:

- I opened Joplin.
- I clicked on Inbox and then the note.
- Then I clicked the X to exit Joplin. 
- Five minutes or so later, it shut down.

**Comment by taw00** [comment]
Note that I was able to eventually delete the note by emailing myself a simple note that would be ordered above the problematic note. Since Joplin never truly remembers where you were when you exited when you open it (it only remembers which notebook), it opened on the new note. I right-clicked on the problem note and deleted it.

**Comment by laurent22** [comment]
Sorry to ask, but would you mind recreating this note and this time export a JEX of it and share it here?

We can probably try with that image but I don't think that will be enough to replicate the issue

**Comment by pedr** [comment]
I'm going to try to make some tests with big images to see if I can replicate this, I made tests with big attachments, but I don't think I test large images inside the body.

The log file seems like to have been cut short of finishing logging the image data as base64. I never really worked with the logs, but maybe there is something there, @laurent22 ? Do you think the new log rotation feature could be causing this?

**Comment by laurent22** [comment]
> The log file seems like to have been cut short of finishing logging the image data as base64. I never really worked with the logs, but maybe there is something there, @laurent22 ? Do you think the new log rotation feature could be causing this?

I'm not sure, but I don't think it would cause this issue.

By the way, images are always encoded as base64 by email-to-note? Because that might be the reason why it's so slow since a 4MB image as base64 is probably massive in the editor

**Comment by taw00** [comment]
> Sorry to ask, but would you mind recreating this note and this time export a JEX of it and share it here?

A JEX would include everything. 187M and would contain my entire brain for the last ... years and years. So, no. And I can't send the note to a different profile, right?

If you just do what I did above, that should recreate the situation. I downloaded the image I included in this issue and confirmed it is identical to the image I used.

**Comment by laurent22** [comment]
> A JEX would include everything. 187M and would contain my entire brain for the last ... years and years. So, no. And I can't send the note to a different profile, right?

Just the JEX of that particular note - right-click => export => JEX

**Comment by taw00** [comment]
*I should have added: Joplin 2.11.11, of course. The latest release.*

I'm attaching two JEX files. (Note, I didn't realize until this conversation that you could export an individual note to a .jex — fun!)

Both notes were created with the same image file. For one note, I attached the image. For the other, the image was embedded inline. Attached (4.1M). Inline (15M).

[bloated note - inline.jex.zip](https://github.com/laurent22/joplin/files/12407306/bloated.note.-.inline.jex.zip)
[bloated note - attached.jex.zip](https://github.com/laurent22/joplin/files/12407308/bloated.note.-.attached.jex.zip)

My desktop instance of Joplin did not have an issue with the attached version of this. It did, again, choke on the inline version.

**Comment by laurent22** [comment]
I think there are two issues here - one is that Email To Note should convert images from base64 to plain resources (this is being done by Pedro), and another is that large Base64 images can freeze the app. We should probably look at this separately as a performance issue.

**Comment by taw00** [comment]
This was closed with no resolution noted. Is this now folded into some other work? If so can you link it? If not, is this simply something we have to be careful not to trigger?

**Comment by laurent22** [comment]
Yes this was fixed, and will be part of the next Joplin Cloud release
