### ISSUE TITLE
Reorder the list of notebooks after renaming

### ISSUE THREAD

**Issue by chrisb86** [laurent22/joplin#870]
### Operating system

- macOS
- iOS

### Application

- Desktop
- Mobile

After renaming a notebook, the list won’t be reordered. I have a renamed a notebook to @Inbox. It should be ordered to the beginning of the list. 

On the macOS client the list has been reordered after quitting and restarting the app. On the iOS client I haven’t found a way to trigger the reordering.

It would be nice if the list will be updated after each renaming.

**Comment by foxmask** [comment]
the folder are not sorted, even after triggering the sync process ?

**Comment by chrisb86** [comment]
Yep.

**Comment by subi54** [comment]
+1
Would like reordering folders on desktop(Windows).
On Android it happens alphabetically, after a sync or a restart of the app.

**Comment by chrisb86** [comment]
On iOS it‘s fixed for me after the latest update.

**Comment by vlebedev** [comment]
It would be great to have an item in View menu for sorting notebooks (by name, by updated date, created date), like for notes.
