### ISSUE TITLE
joplin-desktop 2.12.10 doesn't render text anymore

### ISSUE THREAD

**Issue by easyteacher** [laurent22/joplin#8719]
## Environment

Joplin version: 2.12.10
Platform: Linux
OS specifics: openSUSE Tumbleweed 20230821

```
Operating System: openSUSE Tumbleweed 20230821
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.4.11-1-default (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Ryzen 7 4700U with Radeon Graphics
Memory: 15.0 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: HP
Product Name: HP ZHAN 66 Pro A 14 G3
```

## Steps to reproduce

1. Open joplin-desktop appimage
2. 
3. 

![图片](https://github.com/laurent22/joplin/assets/23738961/fd3b9dec-0f8c-4fc2-97d1-9d38c200e152)

## Describe what you expected to happen
Text is rendered normally

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/12430647/log.txt)

**Comment by laurent22** [comment]
Do you use any custom theme or CSS?

**Comment by personalizedrefrigerator** [comment]
It's working for me, but I'm using Intel graphics:

![OpenSUSE Tumbleweed 20230809](https://github.com/laurent22/joplin/assets/46334387/8992d7d1-0be5-4469-86c7-8c1abe377bff)
![Joplin 2.12.12](https://github.com/laurent22/joplin/assets/46334387/60b3b50c-14a0-44c6-bcf8-7120eada1953)

(I'm currently applying updates to the OpenSUSE computer and will report back after updates have been installed).

**Comment by easyteacher** [comment]
Following the workaround in https://bbs.archlinux.org/viewtopic.php?id=285507

By deleting `~/.config/Joplin/GPUCache` the problem is gone.
