### ISSUE TITLE
Add option to import HTML and TXT file

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8722]
The MD import module supports importing TXT and HTML files too, but that may not be obvious. Currently if a user wants to import a TXT or HTML file, they should select the option to import MD files.

We should add options to the Import menu:

- HTML - Directory
- HTML - Single file
- TXT - Directory
- TXT - Single

Internally those will simply be shortcuts to the MD importer.

**Comment by Daeraxa** [comment]
Is this not going to overload the menu a bit? We will now have 12 import options under that menu. Does it make sense to, rather than make independent items, to include them in the existing one? For example:

- MD/TXT/HTML - Directory

Or even split into subdirectories split by directory or single file. e.g.:

- Import File
    - MD
    - TXT
    - HTML
- Import directory
    - MD
    - TXT
    - HTML

**Comment by dpoulton-github** [comment]
If txt is going to be stated as an import option may there not also be an expectation by users that using this import option will also "defang" or escape any Markdown characters? 

![image](https://github.com/laurent22/joplin/assets/60117449/216dce1b-8b98-4d3d-9790-7840ffaa7493)

**Comment by laurent22** [comment]
> If txt is going to be stated as an import option may there not also be an expectation by users that using this import option will also "defang" or escape any Markdown characters?

There may also be the expectation that we don't change their data. For example if they have `This is _important_` and we convert it to `This is \_important\_` that will be unexpected at least for some users.

I feel it's more of display issue than import issue - eventually maybe we should have a way to get the editor to display plain text without any formatting.

**Comment by dpoulton-github** [comment]
Yes, I see what you mean. I had a bit of a "senior moment" there as for some reason I was assuming that the note would still be viewed in the viewer which would hide the escape character. Of course, the viewer is not really necessary if you are just dealing with pure plain text.
