### ISSUE TITLE
Rich Text editor toolbar doesn't show all buttons even when there's enough space

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8726]
When switching from the Markdown editor to the Rich Text one, the toolbar doesn't show all buttons even though there's enough space:

<img width="833" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/481b82d2-f819-4cda-82d7-aa4b2a56d3ac">

 Resizing the window makes them reappear:

<img width="844" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/2fae4f57-f188-4858-906b-95c013d52a7c">

**Comment by tomasz1986** [comment]
I think this also happens simply if you restart Joplin without switching editors.

1. Set the editor to Rich Text.
2. Make more buttons visible by resizing the note window (but only barely).
3. Close and restart Joplin.
4. The buttons are hidden again even though there is enough space to display them.
