### ISSUE TITLE
White screen when opening the program

### ISSUE THREAD

**Issue by csprock** [laurent22/joplin#8748]
When I open the a Joplin AppImage I get a white screen .The white screen blocks out other windows and I am unable to interact with the screen or the windows it blocks. The only way for me to regain control of my system is a hardware shutdown. This happens with all versions of Joplin.

## Environment

Joplin version: All
Platform: Linux
OS specifics: Mint 21.1

## Steps to reproduce

1. Download any version of Joplin AppImage
2. Open Joplin

## Describe what you expected to happen
For the app to open

## Logfile

The problem prevents me from accessing logs.

**Comment by Closer2U** [comment]
Same happened to me on Kali 2023.3. 
Updated to the current version (2.11.11) and only a white screen would start that could not be exited or closed.
Had to do that through the `kill`-command.

What fixed it for me was deleting ~/.config/Joplin and ~/.config/joplin-Desktop.
I recommend to backup them beforehand. 

I had to resync all my notes and reinstall the extensions but at least I have access to them.
Joplin works perfectly now.

It's a temporary workaround until the real issue can be fixed, I guess.

**Comment by csprock** [comment]
Doing this has solved the problem for now. Thank you.

**Comment by csprock** [comment]
Unfortunately, this did not solve the problem. I was able to open Joplin once. The second time I opened it the problem returned.

**Comment by vomobile** [comment]
Same happened to me on Ubuntu 20.04.

**Comment by Perkolator** [comment]
I just updated from 2.11.11 to 2.12.15 (on Mint 20.3 Cinnamon (Ubuntu 20.04)) and starting Joplin I see only white screen. Had to KILL the it from System Monitor, though a `@joplinapp-desktop --enable-crashpad` process was left hanging and couldn't be killed (seems to be in a "zombie" status? Some older process (started in July)?).

Then tried to open it again, now I don't see any window at all... but processes are running.

Third time opening (after killing it again) I can see the white window again. \*sigh\*

Running the appimage from terminal, there's no messages at all.

Looking at recently created/updated various issues, there seems to be a lot of this happening to users.

Backed up & removed the following folders:

- `.config/@joplin`
- `.config/Joplin`
- `.config/joplin-desktop`

Still doesn't work. Can't even see a white window now.

The following files are recreated in the `.config` folder when running the appimage:

![image](https://github.com/laurent22/joplin/assets/53913724/156519e1-7244-44ed-ac4c-1f40050d9143)

Comparing to the backed up same folder, I can see few folder/file differences, e.g. `Session Storage` folder and `Cookies` file is not created.

Notably the `.config/joplin-desktop` folder is not recreated at all.

Something to do with the "Electron 25" update (change in 2.12.7 pre-release)?

**Comment by Perkolator** [comment]
I ran few versions of Joplin in VirtualBox (same Mint 20.3 Cinnamon, "clean OS"):

```
$ ./Joplin-2.12.5.AppImage 

xdg-settings: invalid application name
Try 'xdg-settings --help' for more information.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[3171:0904/163409.950459:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
[3135:0904/163409.998270:ERROR:backend_impl.cc(2020)] Invalid file version or magic
```
= Joplin opened just fine.

```
$ ./Joplin-2.12.7.AppImage 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```
= Joplin does not open.

```
$ ./Joplin.AppImage 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```
= Joplin (latest 2.12.15 version installed with the installation script as instructed in README.md) does not open.

Note, the `libva error` comes only in VirtualBox, probably because of the graphic adapter used in the virtual environment.


Seems that the "Electron 25" update in 2.12.7 pre-release version is the culprit. It drops support for older linuxes? Ubuntu 20.04 has standard support to April 2025.
