### ISSUE TITLE
security: perform sha512 sum to validate the downloaded app image

### ISSUE THREAD

**Issue by abmusse** [laurent22/joplin#8756]
https://github.com/laurent22/joplin/blob/10ea9b75685c31c6b3b481317838ff9f0c62ce82/Joplin_install_and_update.sh#L158-L166

Looks like each github release contains the sha512 checksum.
For example, the latest release at the time of this post: https://github.com/laurent22/joplin/releases/download/v2.11.11/Joplin-2.11.11.AppImage.sha512

 To enhance security we should download the checksum and verify it matches the downloaded AppImage before we run the install.

**Comment by abmusse** [comment]
This issue is about to be closed but received no feedback. 

Are github issues not monitored by the maintainers??

**Comment by Daeraxa** [comment]
It is because what you logged is a feature request and not a bug.

![image](https://github.com/laurent22/joplin/assets/58074586/2ee5ea91-2890-4d97-b778-07d0232f3c30)

This is neither a regression nor a reproducible bug so should be raised on the forum as per the link on the feature request option.

**Comment by abmusse** [comment]
Sure I can open this feature request in the forum.

I opened another issue that look like a bug: 

https://github.com/laurent22/joplin/issues/8757#issuecomment-1742124759

Which also will be auto closed by the bot without feedback soon
