### ISSUE TITLE
server: user never really deletes after scheduling for deletion

### ISSUE THREAD

**Issue by abmusse** [laurent22/joplin#8757]
## Environment

Joplin version: latest
Platform: Linux
OS specifics:  Debian 12

## Steps to reproduce

1.  Install Joplin Server in a container see https://raw.githubusercontent.com/laurent22/joplin/dev/docker-compose.server.yml
2.  Create a new user
3.  Try to delete the new user

The UI indicates that the user is scheduled to be deleted. After a week or so later I noticed the user was still around at least listed within the UI user list. I even tried to use the run all scheduled jobs now button which runs but the user is never _really_ deleted.

I used PostgreSQL as the DB, does anyone know the name of the table where the users are stored in? 
I could take a peek in the DB to 100% confirm if the user is still in there.

## Describe what you expected to happen

The user to _really_ be deleted.

**Comment by chrislawso** [comment]
This issue continues to persist. Someone else posted about it in forum https://discourse.joplinapp.org/t/joplin-server-user-deletion-task-not-executing/28871

I am running Joplin Server v2.14.2 and am experiencing exact same issue as original poster abmusse. The web  UI indicates that the user is scheduled to be deleted and I also try to manually start selected task and I never noticed this running '8 	Process user deletions '. The columns for Last Run and Last Completion show dates and times which make it appear that the process did run. However I do not believe the process successfully deleted the user because I can continue to login to that user account.

What steps can I take to delete a user?

Thank you

**Comment by abmusse** [comment]
@chrislawso 

Thanks for reviving this issue and pointing out that I'm not the only one 🙂.

I'm not sure you will get a response from the devs on GH. According to the bot the forum is your best bet to get actionable results! So perhaps getting more folks pointing out the issue on the forum post is the way to go. 

I abandoned my initial kick of tires of Joplin Server due to this persistent issue. If this get resolved I'll look into again to test its viability.

**Comment by namtabmai** [comment]
For anyone else finding this old issue, for me it appears that you can only delete users that have been disabled.

See: https://github.com/laurent22/joplin/blob/dev/packages/server/src/services/UserDeletionService.ts#L102

But when I schedule a user for deletion, it doesn't disable that account. So when the scheduled deletion task runs, it doesn't do the delete and just removes the task.

Scheduling the user for deletion and then disabling them will allow the scheduled deletion to complete.

Perhaps users should be automatically disabled when you schedule them for deletion?

**Comment by dasunsrule32** [comment]
@namtabmai That doesn't seem to actually work. I disabled, then deleted a user and it doesn't do anything. If I trigger the job manually it's the same result.
```
joplin  | 20:08:19 1|app  | 2026-03-10 20:08:19: TaskService: Running #8 (Process user deletions) (manual)...
joplin  | 20:08:19 1|app  | 2026-03-10 20:08:19: TaskService: Completed #8 (Process user deletions) in 4ms
```
Version: `Joplin Server v3.5.2`

**Comment by namtabmai** [comment]
@dasunsrule32 can you check your "admin/user_deletions" section of the admin site? I can see you've done a manual run of the Process user deletions. User account deletions are scheduled for 24 hours after you click the delete button, so even with a manual run it won't delete any accounts until that 24 hours are up.

**Comment by dasunsrule32** [comment]
@namtabmai ok, I will wait to see what happens with the old accounts. I thought that a manual run would nix them...

**Comment by dasunsrule32** [comment]
@namtabmai Waiting 24 hours worked. I wish it would work as soon as I ran the manual run, this works though. Thanks. :)
