### ISSUE TITLE
Mobile - Add share menu

### ISSUE THREAD

**Issue by chrootlogin** [laurent22/joplin#876]
Allow the sharing of pictures and links to Joplin Mobile.

### Operating system

- iOS

### Application

- Mobile

**Comment by foxmask** [comment]
which sharing of links ? because with android you can use the built-in share options and the URL of the webpage will be added to joplin.

**Comment by chrootlogin** [comment]
Nope, I can't share things on iOS to Joplin. Tested with Safari Browser and the Photos App.

**Comment by elasticfusion** [comment]
Agreed. you can share "from" Joplin but not "to" Joplin directly.  By that I mean the Joplin app is nowhere to be found on "Activities" menu.

![img_0178](https://user-images.githubusercontent.com/32307469/46906857-0bbd1900-ced8-11e8-81bb-c578018b3e12.PNG)

There are workarounds

.  For example, there is a tight integration for photos: 

- Share Photo

However, for other content links to web content, you are left with a clunky copy and paste exercise.  Hope this helps.

**Comment by CalebJohn** [comment]
As a note for anyone looking to implement this. The android side of things is implemented with [react-native-share-extension](https://github.com/alinz/react-native-share-extension), it also supports ios but you need the ios dev tools to actual implement it. From the joplin side the code is cross platform you'll just need to remove an os check at [root.js line 541](https://github.com/laurent22/joplin/blob/c72f92e22fb42cba39da43ba9ff482d38e2c5c7a/ReactNativeClient/root.js#L541) and [note.js line 241](https://github.com/laurent22/joplin/blob/c72f92e22fb42cba39da43ba9ff482d38e2c5c7a/ReactNativeClient/lib/components/screens/note.js#L241)

**Comment by ufulu** [comment]
I would like to bump this feature implementation, as this is the only drawback i have from using this awesome tool on a daily basis. thanks in advance for all your great work!

**Comment by aritrakoley** [comment]
Sharing to Joplin from browsers:
In Android, sharing to Joplin from the Chrome browser just copies the url to a new note. It would be helpful if some details of the shared webpage were added to the note. For example, the title of the page, if possible, a screenshot, or summary, etc. 
Sharing of other media:
Even if not for audio and video, a feature to share images to Joplin as notes should be a priority.

**Comment by CalebJohn** [comment]
Sharing is a fairly complicated os specific detail, and because of this Joplin uses a library to handle it. Unfortunately that library is fairly buggy and can't currently support those extra features. But we have our eye on it and will update when possible.

**Comment by CalebJohn** [comment]
I think this should be re-opened, I don't think we have sharing on iOS yet.

**Comment by rallek** [comment]
Sharing on Android works. But it can be improved. There are only the markdown of an picture is transfered not the picture itself.

**Comment by jareware** [comment]
Was expecting to be able to share on iOS; would be a supremely useful addition!

**Comment by tatoosh** [comment]
this woud be a killer feature. all other notes app still can release this.
or is there a workaround?

**Comment by Aaryan-kapur** [comment]
Can I start working on this for my GSOC 2020 application!

**Comment by CalebJohn** [comment]
Of course, fair warning this is a fairly difficult feature so you may not make any large progress before the application deadline.

**Comment by Aaryan-kapur** [comment]
@CalebJohn  thank you so much for the opportunity!
could you please assign me!

**Comment by limj0825** [comment]
Hello mentors! my name is MiaojinLi, a first year graduate student from xlab open laboratory and looking for participate in gsoc this year. I am interest in Sharing on mobile, my github also have a easy 2048 game made by react-mobile. so i want to know can i work with android?

**Comment by CalebJohn** [comment]
Not stale

**Comment by CalebJohn** [comment]
Note stale

**Comment by Aaryan-kapur** [comment]
Hey @calebJohn I had applied for this problem as my GSOC Project, but unfortunately I didn’t make it! Can I collaborate with the student selected for this particular project??

**Comment by CalebJohn** [comment]
Hi @Aaryan-kapur , unfortunately we didn't get as many slots as we initially wanted so this project did not get a student. You are free to start looking into adding ios sharing support, but I would suggest you work on something easier while you build up confidence.

**Comment by Aaryan-kapur** [comment]
Thanks for the guidance! @CalebJohn, I will start looking into other problems too, and start working on this task too!
could you please assign me?

**Comment by blizzrdof77** [comment]
> Thanks for the guidance! @CalebJohn, I will start looking into other problems too, and start working on this task too!
> could you please assign me?
👆 _😀 __👍  Hi @CalebJohn - Sounds like @Aaryan-kapur wants to take a swing at this (assuming this is still something you have time for, Aaryan-kapur?).

**Comment by CalebJohn** [comment]
@blizzrdof77  we haven't from Aaryan since that last comment 2 months ago. It would be great if he can make this work but it doesn't look like it's being actively worked on.

**Comment by adamj-codethink** [comment]
+1

**Comment by CLSherrod** [comment]
I think this is the last item on my checklist of things that I need before I can switch from Evernote to Joplin.

**Comment by stephenhouser** [comment]
+1

**Comment by cuiyuzhong** [comment]
+1

**Comment by Breuxi** [comment]
Hello, I recently got into the IOS Ecosystem and already thought about diving a bit more into IOS Development, now I found Joplin and I also need this Feature. So I would love to help on this :)

**Comment by lighthousebulb** [comment]
> Sharing is a fairly complicated os specific detail, and because of this Joplin uses a library to handle it. Unfortunately that library is fairly buggy and can't currently support those extra features. But we have our eye on it and will update when possible.

@CalebJohn can you point out the used library? Are we able to push development on this?

**Comment by CalebJohn** [comment]
@lighthousebulb Joplin no longer uses the [react-native-share-extension](https://github.com/laurent22/joplin/issues/876#issuecomment-429957083) and instead has everything implemented natively for android. You can see [the changes here.](https://github.com/laurent22/joplin/pull/2870/files) If you're interested in pushing this, go ahead! I'm sure a lot of IOS users would really appreciate it.

**Comment by harabat** [comment]
+1

**Comment by hkgnp** [comment]
+1 for this too. 
I am extremely new to web development but would love to help out where I can.

**Comment by lighthousebulb** [comment]
Awesome! Thank you! It got addressed in ios-v10.8.1. Now we have a working share-extension in iOS. Thanks!
This Issue might be closed now.

**Comment by lighthousebulb** [comment]
Well... I'm missing the share-menu in Joplin ios-v-12.0.2 again.

**Comment by iFork** [comment]
> Well... I'm missing the share-menu in Joplin ios-v-12.0.2 again.

Try restarting iPhone. I encounter similar issues with some other app after its updates.
