### ISSUE TITLE
search in Persian language 

### ISSUE THREAD

**Issue by mimZD** [laurent22/joplin#8760]
i have problem with search in Persian language
you should write all letter of words or sentence to find it
now i use '*' after part of word to find it faster
but still if your note  had misspell when you wrote it, you will never find it again

**Comment by mimZD** [comment]
i want to search " تلویزیون " which means TV
and until i typed " تلویزیو " there was no result
![image](https://github.com/laurent22/joplin/assets/25129673/b692a88a-c172-43bf-a5ef-2cd4188a82d7)

**Comment by mimZD** [comment]
i should use * or write it completely to get the result
![image](https://github.com/laurent22/joplin/assets/25129673/05de5c2a-7ea3-418a-9262-65734332c17c)


![image](https://github.com/laurent22/joplin/assets/25129673/dd0795f6-b9bf-4ef6-b6d8-2ab55fa2dc47)

**Comment by julien-me** [comment]
This is how search works in Joplin.


See the documentation https://joplinapp.org/help/#searching
And https://github.com/laurent22/joplin/issues/8646
