### ISSUE TITLE
Linux app without title bar

### ISSUE THREAD

**Issue by akosma** [laurent22/joplin#8776]
The Linux version does not have a window bar on top, and can only be manipulated (moved, resized, etc) using the keyboard. Please see screenshot below:

![bug](https://github.com/laurent22/joplin/assets/55348/9431d01f-296d-4117-b991-d1869f9f7a17)

## Environment

Joplin 2.12.15 (prod, linux)

Client ID: 58157d2b38034fc1b0471c00b5c84099
Sync Version: 3
Profile Version: 43
Keychain Supported: No

Joplin version: 2.12.15
Platform: 
OS specifics: Fedora 38

## Steps to reproduce

1. Open the application
2. No window bar available

## Describe what you expected to happen

The window should have a top bar, like all other GNOME windows.

## Logfile

No errors or warnings on the console.

**Comment by tvdstaaij** [comment]
Another Fedora 38 user here. Just wanted to add that this is a regression in 2.12.15. I just downgraded to 2.11.11 (using `flatpak update --commit=45c32eede1370e99469f5e4b7febf5da296e102fbe3d3760e1dc516fc8ab14cf net.cozic.joplin_desktop`) and the issue disappeared.

**Comment by JGCarroll** [comment]
Can you try opening Joplin in a X11 session? I'm thinking this is a Wayland bug.

In a Wayland session, try passing the parameters:

`--enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland`

**Comment by akosma** [comment]
@MrCarroll thanks a lot! That did work:
`flatpak run net.cozic.joplin_desktop --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland` launches the app correctly.

I'll override the launcher file for the time being:
`cp /var/lib/flatpak/exports/share/applications/net.cozic.joplin_desktop.desktop ~/.local/share/applications` and editing it so that the app launches with those parameters.

**Comment by personalizedrefrigerator** [comment]
I think this issue is related to this change in the Flathub Joplin repository (as per the above comments):

https://github.com/flathub/net.cozic.joplin_desktop/commit/2f0f2a72e87ef675bcdb97cb2a73f60e0a413964#diff-bce5e1303e97e9873c09a3e6850bb69eae5347a8a3da87c2b1b270407e2e165dR119-R121

I've created an [issue in the repository for the Flathub distribution of Joplin](https://github.com/flathub/net.cozic.joplin_desktop/issues/125).

**Comment by utmost-premise** [comment]
> @MrCarroll thanks a lot! That did work: `flatpak run net.cozic.joplin_desktop --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland` launches the app correctly.
> 
> I'll override the launcher file for the time being: `cp /var/lib/flatpak/exports/share/applications/net.cozic.joplin_desktop.desktop ~/.local/share/applications` and editing it so that the app launches with those parameters.

It doesn't solve to me. It adds the title bar, however the window keeps glitched, moving, resizing and tiling with other windows don't work as expected.

For now I downgraded as pointed by @tvdstaaij , I also tried the AppImage but I got issue #8777

**Comment by JGCarroll** [comment]
You can temporarily disable the Wayland backend by forcing the Flatpak to think there's no Wayland support, such as e.g `export WAYLAND_DISPLAY=null`. 

This'll force the conditional in the Flatpak script to fail, remove the Wayland parameters, and fall back to X11, which should work as before the update.

**Comment by catsout** [comment]
Just use flatseal to disable wayland permission.

**Comment by russell-bie** [comment]
> Just use flatseal to disable wayland permission.

It works. thanks

**Comment by akosma** [comment]
This issue has been solved.
