### ISSUE TITLE
v2.12.15 can not run on Ubuntu 18.04.6 LTS 64-bit

### ISSUE THREAD

**Issue by sysescool** [laurent22/joplin#8777]
## Environment

Joplin version: v2.12.15
Platform: Linux
OS specifics: Ubuntu 18.04.6 LTS 64-bit

## Steps to reproduce

1. Download  AppImage from https://github.com/laurent22/joplin/releases/tag/v2.12.15
2. cd the folder where contains joplin run `./Joplin-2.12.15.AppImage`
3. bash hang there, no anything output and no window show.

## Describe what you expected to happen

run it like v2.11.11 normally.

## Logfile

1. run v2.11.11
2. click Help > Open Profile Directory find the path is: ~/.config/joplin-desktop/flags.txt
3. `rm ~/.config/joplin-desktop/log.txt`
4. `echo "--open-dev-tools --debug --log-level debug" > ~/.config/joplin-desktop/flags.txt`
5. `./Joplin-2.12.15.AppImage`
6. no log.txt generate in ~/.config/joplin-desktop/

**Comment by passenger94** [comment]
Same thing on Ubuntu 22.04, updated yesterday from v2.11.11
(works fine on Android but v2.12.2, also just updated)

**Comment by wiwwo** [comment]
Can confirm the problem with Ubuntu 22.04.
I managed to get the Electron running, and with the Dev Tools i managed to get this error:

```
Uncaught Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Joplin9aEFBx/resources/app.asar.unpacked/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/tmp/.mount_Joplin9aEFBx/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
'''

Screenshot:
![image](https://github.com/laurent22/joplin/assets/3930671/e7a8fdef-a221-4a9d-bee6-a5516386a29f)

**Comment by wiwwo** [comment]
The screenshot again:
![image](https://github.com/laurent22/joplin/assets/3930671/74845368-570a-42a7-90eb-352374b268a2)

**Comment by sysescool** [comment]
check GLIBC version on ubuntu:
1. `ldd --version`
2. `getconf GNU_LIBC_VERSION`

I checked it on my Ubuntu 22.04.2 LTS 64-bit. it's `glibc 2.35` and of course, v2.12.15 runs normally.
However, I have another Ubuntu 18.04.6 LTS 64-bit, a productive machine. It's sad which version is `glibc 2.27`.

I don't know why we have the same 22.04 but a different glibc version. @wiwwo @passenger94 

--------

Ubuntu 18.04 EOF date is just Apr 2023.
Ubuntu 20.04 EOF date is Apr 2025.
I mean Joplin's use too newer glibc is radical to force users to update their glibc.
If the glibc upgrade fails, it can easily cause the system to crash. Especially for users new to Linux.

Must we use the newer Joplin with a higher glibc?

**Comment by personalizedrefrigerator** [comment]
The last working pre-release is [v2.12.5](https://github.com/laurent22/joplin/releases/tag/v2.12.5) — I suspect that either upgrading Electron to version 25 or [upgrading electron-builder](https://github.com/electron-userland/electron-builder) caused the issue.

I just tested again with `electron-builder` v22.11.7 (the version before [the commit that upgraded Electron](https://github.com/laurent22/joplin/commit/a354feb626ee7d3f150b33cf64f281d181bb7132#diff-db409dacbda0a1ee42af0360204bd69196b8b274463531dd2bb7299e9aa3c064L118)) and the issue is still present.

I'm going to try downgrading `electron` next.

**Comment by passenger94** [comment]
glibc 2.31 here

Thanks for tackling the issue :)

**Comment by personalizedrefrigerator** [comment]
Here's what I've tried so far:
- `electron` 25.3.1, `electron-builder` 22.11.7, `--force-abi 116` with the latest commit. **Doesn't work**.
- `electron` 19.1.4, `electron-builder` 24.0.0, `--force-abi 116` with the latest commit. **Doesn't work**. 
- `electron` 19.1.4, `electron-builder` 24.0.0, `--force-abi 89` with the latest commit. **Doesn't work**. 
- `electron` 25.3.1, `electron-builder` 24.0.0, `--force-abi 116` (equivalent to latest). **Doesn't work**.
- https://github.com/laurent22/joplin/commit/c0fe29ec823a450b864b038062c2758b7407df1c (commit before upgrade to Electron 25). **Does work.**
- `electron` 19.1.4, `electron-builder` 22.11.7, `--force-abi 89` with the latest commit. **Doesn't work**.

I'm now testing with `electron-rebuild` version 3.2.9 (`electron-rebuild` was also upgraded in a354feb626ee7d3f150b33cf64f281d181bb7132).

**Comment by personalizedrefrigerator** [comment]
Downgrading `electron-rebuild` to version 3.2.9 seems to fix the issue. Looking at its [release notes](https://github.com/electron/rebuild/releases), however, I don't see anything that should cause the glibc issue. As such, this is probably a bug in `electron-rebuild`.

Joplin was using `electron-rebuild` 3.2.13. I'm now testing with version 3.3.0. **Edit**: `electron-rebuild` 3.3.0 works! It produces an AppImage that runs on Ubuntu 18.04.

**Comment by passenger94** [comment]
Thank you very much !!! :)

**Comment by gcinglese** [comment]
Thanks (I got the same issue on Ubuntu 20.04.6 LTS). Which Joplin's release will include this fix ?

**Comment by personalizedrefrigerator** [comment]
> Which Joplin's release will include this fix?

@laurent22 If you have time, would you be willing to create a new prerelease based on the `release-2.12` branch? (If not, I can try to do so.)

**Comment by Perkolator** [comment]
I'd release a stable, not a pre-release, this affects many users. There are users in various issues, not just in this issue, having this problem.

**Comment by wiwwo** [comment]
HI @sysescool 
The EOL can be extended 
https://ubuntu.com/about/release-cycle
https://ubuntu.com/pro

**Comment by personalizedrefrigerator** [comment]
It should be fixed in v2.12.16:

https://github.com/laurent22/joplin/releases/tag/v2.12.16

**Comment by passenger94** [comment]
Indeed :) Thank you

**Comment by sysescool** [comment]
Thanks to everyone and your efforts. I tested it with an install on Ubuntu 18.04.6 and it works all right now.

Thanks again.
