### ISSUE TITLE
Mobile app : no more content in notes and no edit.

### ISSUE THREAD

**Issue by WillZegal** [laurent22/joplin#8778]
Hi,

on my mobile app, I can't access anymore to notes content.

I still have notebooks and note titles, but no content in notes and when I try to create a note, I juste can put a title and nothing else.

I used to work properly and I don't think I've changed anything.

My notes are synced with Dropbox. They are OK on my computer and in Dropbox.

I've tried to reinstall the app. I get the welcome notes, still without any content and I still can't edit them.

## Environment

Joplin version: 2.11.32
Platform: Androi Redmi Note 8 Pro
OS specifics: MIUI 12.0.4 - android 10 QP1A.190711.020

## Steps to reproduce

1. Open the app
2. Open a note. It looks empty
3. try to edit. You get the editor GUI but there's no way to enter any text.

## Logfile

Not accepted by GitHub : too long

**Comment by WillZegal** [comment]
[syncReport-1693670017398.txt](https://github.com/laurent22/joplin/files/12512070/syncReport-1693670017398.txt)
[syncReport-1693817147768.txt](https://github.com/laurent22/joplin/files/12512071/syncReport-1693817147768.txt)

**Comment by WillZegal** [comment]
Finally it was not a Joplin bug, but a phone bug. It's now solved. Sorry for that.

**Comment by WillZegal** [comment]
Finally it was not a Joplin bug, but a phone bug. It's now solved. Sorry for that.

**Comment by graphit0** [comment]
can you tell what was this problem with the phone? thanks

**Comment by WillZegal** [comment]
Sorry I didn't see your question.
I don't really know, but I hadn't shut it down for a while and began to have some matters with some apps. A reboot solved everything, including the worst one that was in Joplin.
