### ISSUE TITLE
OneDrive Sync: The caller does not have permission to perform the action

### ISSUE THREAD

**Issue by OctarineSorcerer** [laurent22/joplin#878]
### Operating system

- Arch Linux

### Application

- Terminal

Attempting to sync via :sync, with config.sync.target set to 3, and having authenticated Joplin via the page it tells you to go to (localhost:something/auth), the following error appears:

`The caller does not have permission to perform the action`
Log is attached.
[log.txt](https://github.com/laurent22/joplin/files/2465893/log.txt)

The directory Apps/Joplin was not created in the OneDrive, and the same error occurred when that directory had already been created.

It's worth noting I'm currently using the Arch package, so the version's a little out of date (`joplin version` gives 1.0.114), but I haven't seen anything in the patch notes since about anything related?

**Comment by laurent22** [comment]
Looks like just a wrong password or username?

Is that regular OneDrive by the way? (not OneDrive Business)

**Comment by OctarineSorcerer** [comment]
Ah, no, it is OneDrive Business indeed. If I recall correctly, I had been logged into OneDrive at the time, and I don't think I was prompted at any point by Joplin for login details. Is there any way to reset the sync details, for testing again?
