### ISSUE TITLE
求助：自己搭建的webdav,ios系统无法同步

### ISSUE THREAD

**Issue by lizhiwei8061** [laurent22/joplin#8783]
求助：自己搭建的webdav，ios系统无法同步，检查同步配置提示：发生错误。请检查URL、用户名、错误是否正确以及同步的目标是否可访问。报告的错误报告为：Network request failed。如果把请求的URL域名改成ip地址可以检查同步配置成功，但是同步数据依然失败

**Comment by ancelee** [comment]
是否使用了https

**Comment by lizhiwei8061** [comment]
没有使用https，但是之前用https测试过，也没成功
