### ISSUE TITLE
Joplin V2.12.15 does'nt start after installation

### ISSUE THREAD

**Issue by bubusbos** [laurent22/joplin#8785]
Hello,
Joplin V2.12.15 does'nt start immediately after installation. My system is Windows 8.
The error  message on te screen is :
Le point d'entrée de procédure DiscardVirtual Memory est introuvable dans la bibliothèque de liens dynamiques C:\Program Files\Joplin\Joplin.exe

## Steps to reproduce

1. start
2. message
3. 

## Logfile : no logfile

Thank You

**Comment by tomasz1986** [comment]
Windows 8 is no longer supported. You will need to upgrade your operating system to Windows 10 or 11 if you want to use Joplin v2.12 and newer.

**Comment by laurent22** [comment]
Or revert to 2.11 which will always be available from the release page:

https://github.com/laurent22/joplin/releases/tag/v2.11.11

**Comment by sacreps** [comment]
This is also an issue in Linux (openSUSE Leap 15.5). Run the program and no window opens, although a "ps -f" lists several related processes running. This first appeared in V2.12.7 (V2.12.5 works), so I suspect it may have to do with the change to Electron 25 mentioned in the release notes for V2.12.7. Is there a list of minimum requirements for Linux related to this change?

**Comment by Ranko-Saotome** [comment]
i'm Having the same issue i'm on zorin os 16 which is basically  ubuntu 20.04.

**Comment by Perkolator** [comment]
@sacreps & @Ranko-Saotome : The issue has been fixed already in #8777, though there's no new version available with the fix.

**Comment by ghost** [comment]
Version 2.12.15 works flawlessly in Debian 12. 
Version 2.12.16 doesn't work.
