### ISSUE TITLE
add Liberapay on fdroid metadata

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#8786]
@laurent22 
* **your explicit consent is required** to add Liberapay id ```laurent22``` given at https://joplinapp.org/donate/ in [fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/HEAD/metadata/net.cozic.joplin.yml)
* fdroid [policy](https://gitlab.com/fdroid/admin/-/issues/417), [discussion 1](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13549#note_1508711371) and [discussion 2](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13533#note_1504648422) wrt to adding AuthorEmail, AuthorWebSite, Donate, etc..

**Comment by laurent22** [comment]
Yes of course, it'd be great if you could add it, thank you
