### ISSUE TITLE
Unable to set due date on Android  Joplin 2.12.2

### ISSUE THREAD

**Issue by Grydpype** [laurent22/joplin#8789]
Joplin 2.12.2
Android 10

Cannot set a due date for tasks.

To reproduce:
- Open a task
- Go to "Set due date" in hamburger menu
- choose day and time
- click on "Save"

Expected: 
- due date is saved to task

Actually happening:
- date field is cleared, 
- nothing else happens, 
- due date is not saved

**Comment by Grydpype** [comment]
Addon: I did a fresh install from PlayStore (V. 2.12.2) on a second device (Fairphone; with Android 12 this time); no sync; created a ToDo and could exactly reproduce the behaviour described in my first post (using a Xiaomi with Android 10).

In addition, I noticed that modifications of existing due dates set are not possible on the mobile device either. A task with a due date keeps its due date regardless of changes I try to make on the mobile device.

**Comment by JackGruber** [comment]
I cant reproduce the behavior.
I can create new tasks with a due date and modify the due date on Android 13 and Joplin 2.12.2

**Comment by Grydpype** [comment]
OK, but thats's a differnt OS.

**Comment by jbsauvan** [comment]
I also encountered this issue (on Android 10 as well).
Here is what I believe could be the error message:

![log_joplin](https://github.com/laurent22/joplin/assets/5569798/570f5348-6fe0-4326-9677-54fd0ccfae8c)

It is happening when clicking on "Save".

**Comment by laurent22** [comment]
If you go in the application info screen (the system one), have you given notification permission to the app?

**Comment by laurent22** [comment]
We should investigate if it's possible to ask for notification permission at this point or, if it's not, we should display an alert box about it

**Comment by Grydpype** [comment]
All permissions for notifications (apart from vibrating) are given.

**Comment by jbsauvan** [comment]
In my case the app is allowed to **display** notifications (+ emit sound). And the notification display actually works just fine: for due dates that I set before updating to 2.12.2, the notifications are correctly displayed.
Concerning app permissions (I mean here permissions in the same sense as storage access, camera access, position access, etc.) I don't see a way to set notification permission, and I don't see any app having notification permissions here.

**Comment by personalizedrefrigerator** [comment]
I'm able to reproduce this on an Android 7 device (also all notification permissions granted in settings).
