### ISSUE TITLE
FR: Android: Auto advance with todo entries

### ISSUE THREAD

**Issue by gerroon** [laurent22/joplin#879]
Hi

It would be very nice if todo entries can be added automatically to the next line when pressed enter in the Android app. This is how it works on Desktop version but the Android app missing it. It is a bit off hassle to add markdown formatting for such lines a mobile keyboard

thanks

**Comment by foxmask** [comment]
For things like that I make template notes, thus I can (relativly) "quickly" create a one.

**Comment by markwdickson** [comment]
This is actually a huge feature for me, and part of what is keeping me on Evernote at the moment.  I don't mind writing full-on Markdown formatting on the desktop app, but it's tough on the phone.  I make a lot of lists, so being able to easily add items in the mobile app is key.

**Comment by subi54** [comment]
Currently using Gboard's text expander feature for this. cb shows the suggestion to change into `- [ ]`. Quite useful.

I'd rather have a formatting toolbar, something like iA Writer than just this one feature.

**Comment by dangerfish96** [comment]
Why can the desktop version do this but not the Android/iOS version?

**Comment by gerroon** [comment]
fuck the @stale bot

**Comment by foxmask** [comment]
insult are not allowed even against a bot
so please avoid.
if you need this feature ; reopen the issue as explain earlier.
thanks
