### ISSUE TITLE
How to create tags

### ISSUE THREAD

**Issue by yafp** [laurent22/joplin#88]
### Operating system

- [ ] Windows
- [ ] macOS
- [x ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x ] Desktop - 0.10.38
- [ ] Mobile
- [ ] Terminal

---
Might be a silly question, but how can a user create a tag? i searched the project side for informations regarding this step and tried several things ... but seem unable to create a tag.

**Comment by yafp** [comment]
Adding tags in the desktop client works as follows:

* right-click a single note
* choose "add or remove tag" from the context menu.

**Comment by leolivier** [comment]
Easy when you know it but hard to guess!

**Comment by laurent22** [comment]
@leolivier, that's true, there should probably be an icon in the task bar for this.

**Comment by chipbag01** [comment]
Agreed, @laurent22 !
