### ISSUE TITLE
Capitalization-Problem, Typing Text in Notes

### ISSUE THREAD

**Issue by mcteefax** [laurent22/joplin#880]
### Operating system

- iOS 11.x an newer

### Application

- Mobile

When typing a text into a notice or ToDo, often the text switches to upper-case letters. The Dictionary sometimes corrects the word, but the result often looks like that:

> DAS GÄSTEbuch ISt LEer.

  (german language)

To get an lower case letter, I have to töuch the SHIFT-Key for each letter, although the shift-lock is not active! Continuosly pressing the shift-key results in upper case letters.

**Comment by tessus** [comment]
Duplicate of #558
