### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [laurent22/joplin#8801]
Description
The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this.

URL:
https://joplinapp.org/

Screenshot

<img width="960" alt="Screenshot 2023-09-08 160239" src="https://github.com/laurent22/joplin/assets/91591901/961fc26d-5ac5-4ccb-9023-1840d6e8c26a">

## Environment

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce
Scroll to the bottom and see twitter's old logo

## Describe what you expected to happen
Twitter logo should be changed to X

@bronson 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by laurent22** [comment]
It's ok as it is, doesn't really matter
