### ISSUE TITLE
Front Matter import/export actions incorrectly handle the first line following the YAML block

### ISSUE THREAD

**Issue by DeanHutchings** [laurent22/joplin#8802]
## Description

1) The Front Matter export actions insert a blank line following the YAML block's closing "---" line. The blank line is not part of the actual MD content.

2) The Front Matter import actions throw away the first line following the YAML block's closing "---" line. Importing MD files with text immediately following the "---" line is lost.

This behavior is the same when operating on individual notes or a directory with many notes.

I apologize in advance if this is a "feature" and not a "bug". I wasn't able to find much info on the specifics of the MD with Front Matter import/export and discovered this issue as I was writing a PowerShell script to convert an old Day One journal archive (JSON format) into a nested folder structure of MD with Front Matter files. Some of the newly imported notes looked fine but many of them were completely blank.

## Environment

Joplin version: 2.12.15 (prod, win32)
Platform: Windows
OS specifics: Windows 11 Pro, Version 22H2, OS Build 22621.2134

Info from Joplin About dialog:
Joplin 2.12.15 (prod, win32)
Client ID: 197c9e6467374c86a3fb013e79f79fae
Sync Version: 3
Profile Version: 43
Keychain Supported: Yes
Revision: 2d26332
Journal: 1.0.14

## Steps to reproduce

Export Steps

1. Open the "Welcome!" notebook that is shipped with Joplin
2. Right-click on the "1. Welcome to Joplin!" note and select "Export -> MD - Markdown"
3. Finish the export process and open the exported MD file, "1. Welcome to Joplin!.md", in any text editor.
4. You will see a blank line between the closing "---" line and the first line of the markdown content, "# Welcome to Joplin!".

Import Steps

1. Take any MD file with Front Matter. I used the file I exported using the steps above, "1. Welcome to Joplin!.md".
2. I opened the file in VS Code and removed the blank line following the YAML block's closing "---". At this point there are no blank lines separating the YAML Front Matter and the first line of the markdown content.
3. Save the file.
4. Import the file using any of the import actions (file or directory) that handle MD files with Front Matter.
5. Examine the imported not in Joplin - The first line of the markdown content seen in the editor in step 2 is gone.

## Describe what you expected to happen

The markdown content of MD files with Front Matter should begin immediately after the YAML block's closing "---" line.

## Logfile

n/a

**Comment by laurent22** [comment]
To clarify, if this file is imported:

```
---
title: my note
updated: 2023-09-10 16:59:25Z
created: 2023-09-10 16:59:17Z
latitude: 51.54822860
longitude: -0.23791760
altitude: 0.0000
completed?: no
---
# TITLE
```

It will result in a note titled "my note" with no body. So the `# TITLE` part is removed.

What we should do is trim any extra space at the top, and import this instead of removing the top line

**Comment by DeanHutchings** [comment]
Yes. That is correct.

I don't think altering the markdown content (trimming leading blank lines) is the proper approach. Anything that alters the 
markdown content should be avoided. If a person, for whatever reason, enters 5 blank lines at the top of a note, the import/export actions should preserve the writer's content.

IMO, to correct the problem during export, the blank line inserted before the markdown content should not be present. To correct the problem during import, the first line following the YAML block should be preserved as the first line of the markdown content.

Does that make sense?

**Comment by laurent22** [comment]
> I don't think altering the markdown content (trimming leading blank lines) is the proper approach. Anything that alters the markdown content should be avoided.

I agree actually but as you pointed out it doesn't look like there's a proper spec for MD+FrontMatter. In that case, since we don't know if any blank space if significant or not, we may as well remove it from the top. Or maybe we should remove just one but I'm not sure. I feel that if we trim everything at the top we have a more consistent behaviour.

> IMO, to correct the problem during export, the blank line inserted before the markdown content should not be present. To correct the problem during import, the first line following the YAML block should be preserved as the first line of the markdown content.

Yes, but what if an application generates MD+FrontMatter file that contain no space between "---" and the content? Is that an error and should importing the file fail? I guess not. But then what if that same application exports another note with a space after "---" - in that case you say we should remove it, but in fact it was significant. So that's what I mean - without a spec we don't know what the spaces, or lack of spaces at the top mean, so we may as well remove them. I suspect that it's rare files that start with a blank space at the top anyway

**Comment by DeanHutchings** [comment]
I feel that I'm confusing you. Sorry.

I think the markdown content should begin in the line immediately following the YAML code block's trailing "---" line. Nothing added or removed.

**Comment by laurent22** [comment]
Not confused but maybe overthinking it! Maybe we should indeed start right after the "---" but on the other hand having a space improves readability. I feel we should research the topic a bit more and find out what is the generally accepted way to do this.

But next to this, we need to fix this bug where the top line is deleted even if non-empty

**Comment by imshivam-gupta** [comment]
> But next to this, we need to fix this bug where the top line is deleted even if non-empty

@laurent22 Can u please elaborate this line i am still confused

**Comment by laurent22** [comment]
@imshivam-gupta, just to let you know, we're no longer participating in GSoC.

**Comment by imshivam-gupta** [comment]
@laurent22 Sir will joplin participate in GSOC 2024

**Comment by laurent22** [comment]
> @imshivam-gupta, just to let you know, we're no longer participating in GSoC.

**Comment by laurent22** [comment]
@hubertfilho, could you research this please and find out if there's any standard, or generally accepted way to do this? Basically should there be an empty line after "---" or not?

Then also please fix the bug mentioned above

**Comment by laurent22** [comment]
I've looked at several examples of Markdown+FrontMatter and all of them had an empty line between the "---" and the content.

So let's do this:

- When writing the document, add an empty line between "---" and the content
- When reading the document:
    - Skip the first empty line, and assume the rest of the text is the actual content (we don't trim all white spaces at the top)
    - As a special case, if there's no empty line between "---" and the content, we just assume that everything after "---" if the content.
