### ISSUE TITLE
Android note contents & rich text editor blank for all notes - contents visible in plain text editor

### ISSUE THREAD

**Issue by calebjones** [laurent22/joplin#8804]
## Environment

Joplin version: 2.12.2 (database v43)
Platform: Android (Galaxy S9+)
OS specifics: Android 10

## Steps to reproduce note content missing

1. Open App
2. Browse to any note (notice notebook and note titles are visible)
3. Open the note
4. Notice that the note's content is missing
5. Click button to edit note (w/ "Use the plain text editor" setting disabled - which is default)
6. Notice that note's content is still missing

## Steps to reproduce ability to see note's contents when editing

1. Open App
2. Go to settings and enable "Use the plain text editor"
3. Browse to any note (notice notebook and note titles are visible)
4. Open the note
7. Notice that the note's content is missing
8. Click edit button
9. Notice that note's content is now visible in plain text

NOTE: in both cases, search works fine. I can search for notes based on their contents and get expected results, but just can't view the contents when selecting notes.

## Describe what you expected to happen

Expected: Ability to see note's content either in viewing or editing in rich text mode.

## Logfile

Couldn't see how to copy log contents from app. But no errors in the log. :-(

**Comment by personalizedrefrigerator** [comment]
This might be a WebView-related issue! Both the note viewer and default text editor use a WebView to display their contents.

If you have the Google Play Store (or another app store) installed, please make sure that the Android system WebView is installed and up-to-date. (This [should be a link to the Android system WebView on the Play Store](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en_US&gl=US&pli=1)).

**Comment by calebjones** [comment]
If it is WebView, it is likely the most recent release that is causing the problem.

My phone shows WebView v116.0.5845.172 updated on Sept. 5, 2023 (which would be about when I started to see this issue).

**Comment by calebjones** [comment]
FIX: Realized that I hadn't tried restarting my device. Since restarting, the issue has gone away.

As a note, I noticed that several other apps were failing to load content. My guess is that the most recent WebView update didn't properly load and required a restart.

Closing issue.
