### ISSUE TITLE
Android "back" button *sometimes* causes crash

### ISSUE THREAD

**Issue by jesteria** [laurent22/joplin#8806]
## Environment

Joplin version: 2.12.2
Platform: Android
OS specifics: Android 13

## Steps to reproduce

1. From within a note: press the back button

The app will immediately close – and disappear from the app overview list of recent apps. Reopening the app will _e.g._ prompt for biometrics – indicating that the app has been _entirely_ closed and _i.e._ crashed.

Additional detail: I personally have Android configured to go back with a "swipe" rather than a back button. But this is ostensibly immaterial to Joplin.

To be sure, this is *not* always the result; however it is frequent, maybe half the time I attempt this standard operation.

## Describe what you expected to happen

If the keyboard is open, then I expect the keyboard to close. If merely in the editor, then I expect to go back to the note rendering. If in the note rendering view, then I expect to return to the note list. If I've "shared to" Joplin, then I expect to be returned to the sharing app. _Etc._

## Logfile

I saw no errors and nothing out of the ordinary in the log. I've exported the [syncReport.txt](https://www.dropbox.com/scl/fi/o2lmzhotav0dct6ciqvdg/syncReport-1694276433608.txt?rlkey=1obig0k4c1x664i8lkjj2b3kz&dl=0) though this is ostensibly unrelated.

**Comment by personalizedrefrigerator** [comment]
Possibly related to https://github.com/laurent22/joplin/issues/8791

**Comment by tomaThomas** [comment]
For me this consistently happens if I'm editing a note, the keyboard is open and I go back using the swipe gesture. If  the keyboard is closed, it does not crash

Edit: after looking at the referenced issue I realized that it happens if the scroll bar is there

**Comment by Wladefant** [comment]
@personalizedrefrigerator yeah it sure is, happens every time I click on back button

**Comment by personalizedrefrigerator** [comment]
@Wladefant @tomaThomas Are either of you using version 2.12.3 (it might be listed as 12.12.3 in "Configuration"). That version might have a fix for this issue.

**Comment by tomaThomas** [comment]
> @Wladefant @tomaThomas Are either of you using version 2.12.3 (it might be listed as 12.12.3 in "Configuration"). That version might have a fix for this issue.

Yes, that version does not have die issue anymore, thanks!

**Comment by jesteria** [comment]
Yes, it _appears_ that this was related to the drawer gesture issue, and that it has been resolved. I'll close it. Thanks all!
