### ISSUE TITLE
Scrollbar thumb is barely visible in Light theme

### ISSUE THREAD

**Issue by bgoodmansf** [laurent22/joplin#8817]
## Environment

Joplin version: 2.12.15
Platform: Windows
OS specifics:  Windows 11 22H2

## Steps to reproduce

1. Select Tools > Options > Appearance > Theme: Light
2. Open a profile which has many tags.

## Describe what you expected to happen

Expect to see thumb of scrollbar, but it is extremely difficult to find.

Thumb is slightly easier to see in dark themes, but still almost invisible in most.
![Screenshot 2023-09-10 111027_2](https://github.com/laurent22/joplin/assets/4819742/b0c1eac3-5d4f-4360-b86a-80ec73e6627f)

**Comment by imshivam-gupta** [comment]
I have fixed the issue in my PR. I am new to Open Source and my all the technologies i have learnt till now are used in joplin. Please guide me if all the above steps i have done are correct.
