### ISSUE TITLE
KDE Plasma 5 Tray Icon Not Found

### ISSUE THREAD

**Issue by SiqingYu** [laurent22/joplin#882]
### Operating system
Kubuntu 18.04 LTS (64bit)
KDE Plasma Version: 5.12.6
KDE Frameworks Version: 5.44.0
Qt Version: 5.9.5

As mentioned in [https://discourse.joplin.cozic.net/t/start-minimized-to-tray/433/7](https://discourse.joplin.cozic.net/t/start-minimized-to-tray/433/7)
When the app closes, there is no process closes too, so the web clipper cannot access the service.

**Comment by laurent22** [comment]
There's already an option to start minimised in tray, is that what you're looking for?

**Comment by SiqingYu** [comment]
@laurent22 Thank you very much. It solves this issue.

**Comment by laurent22** [comment]
No problem, the feature was introduced in a recent version.
