### ISSUE TITLE
Can put a alarm on to-do

### ISSUE THREAD

**Issue by MsopyFR** [laurent22/joplin#8841]
When I will save the alarm (date and hour), the date file become blank. 

## Environment

Joplin version: 2.12.2
Platform: Android 12
OS specifics: Samsung S10e

## Steps to reproduce

1. create a to-do
2. click on ...
3. choose "régler alarme" or in english "set alarm"
4. click on "set date" and choose one , then a date and hour appear at the left of "set date" 
5. click on "enregistrer alarme" or in english "save alarm"
6. the date and hour disappear
7. so to quit I must have to click on "cancel"

## Describe what you expected to happen
The button "enregistrer alarme" or "save alarm" have the same function than "enlever l'alarm" or in english "remove alarm"

## Log file
Date,Level,Message
09-11T21:12:53,30,"root: ""root.biometrics: biometricsEnabled", "false""
09-11T21:12:53,30,"root: ""root.biometrics: shouldShowMainContent", "true""
09-11T21:12:53,30,"root: ""root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}""
09-11T21:12:53,30,"root: ""root.biometrics: biometricsDone", "true""
09-11T21:12:52,30,"root: ""root.biometrics: biometricsDone", "true""
09-11T21:12:52,30,"root: ""root.biometrics: biometricsEnabled", "false""
09-11T21:12:52,30,"root: ""root.biometrics: shouldShowMainContent", "true""
09-11T21:12:52,30,"root: ""root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}""
09-11T21:12:47,30,"RevisionService: ""maintenance: Done in 124ms""
09-11T21:12:47,30,"RevisionService: ""collectRevisions: Created revisions for 0 notes""
09-11T21:12:47,30,"root: ""root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}""
09-11T21:12:47,30,"root: ""root.biometrics: biometricsDone", "true""
09-11T21:12:47,30,"root: ""root.biometrics: biometricsEnabled", "false""
09-11T21:12:47,30,"root: ""root.biometrics: shouldShowMainContent", "true""
09-11T21:12:47,30,"RevisionService: ""maintenance: Service is enabled""
09-11T21:12:47,30,"RevisionService: ""maintenance: Starting...""
09-11T21:12:42,30,"root: ""root.biometrics: shouldShowMainContent", "true""
09-11T21:12:42,30,"root: ""root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}""
09-11T21:12:42,30,"root: ""root.biometrics: biometricsDone", "true""
09-11T21:12:42,30,"root: ""root.biometrics: biometricsEnabled", "false""
09-11T21:12:41,30,"root: ""root.biometrics: biometricsDone", "true""
09-11T21:12:41,30,"root: ""root.biometrics: biometricsEnabled", "false""
09-11T21:12:41,30,"root: ""root.biometrics: shouldShowMainContent", "true""
09-11T21:12:41,30,"root: ""root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}""
09-11T21:12:15,30,"RevisionService: ""maintenance: Done in 139ms""
09-11T21:12:15,30,"RevisionService: ""collectRevisions: Created revisions for 0 notes""
09-11T21:12:15,30,"RevisionService: ""maintenance: Starting...""
09-11T21:12:15,30,"RevisionService: ""maintenance: Service is enabled""
09-11T21:11:46,30,"checkPermissions: ""Requested permission:", "never_ask_again""
09-11T21:11:46,20,"screens/Note: ""POST_NOTIFICATION permission was not granted""
09-11T21:11:46,30,"checkPermissions: ""Checked permission:", "false""
09-11T21:11:45,20,"screens/Note: ""POST_NOTIFICATION permission was not granted""
09-11T21:11:45,30,"checkPermissions: ""Requested permission:", "never_ask_again""
09-11T21:11:45,30,"checkPermissions: ""Checked permission:", "false""
09-11T21:11:44,30,"RevisionService: ""maintenance: Done in 182ms""
09-11T21:11:44,30,"RevisionService: ""collectRevisions: Created revisions for 0 notes""
09-11T21:11:44,30,"checkPermissions: ""Requested permission:", "never_ask_again""
09-11T21:11:44,20,"screens/Note: ""POST_NOTIFICATION permission was not granted""
09-11T21:11:44,30,"RevisionService: ""maintenance: Starting...""
09-11T21:11:44,30,"RevisionService: ""maintenance: Service is enabled""
09-11T21:11:44,30,"checkPermissions: ""Checked permission:", "false""
09-11T21:11:20,30,"checkPermissions: ""Requested permission:", "never_ask_again""
09-11T21:11:20,20,"screens/Note: ""POST_NOTIFICATION permission was not granted""
09-11T21:11:20,30,"checkPermissions: ""Checked permission:", "false""
09-11T21:11:19,30,"checkPermissions: ""Requested permission:", "never_ask_again""
09-11T21:11:19,20,"screens/Note: ""POST_NOTIFICATION permission was not granted""
09-11T21:11:19,30,"checkPermissions: ""Checked permission:", "false""
09-11T21:11:12,30,"RevisionService: ""maintenance: Done in 1838ms""
09-11T21:11:12,30,"RevisionService: ""collectRevisions: Created revisions for 0 notes""
09-11T21:11:10,30,"RevisionService: ""maintenance: Starting...""
09-11T21:11:10,30,"RevisionService: ""maintenance: Service is enabled""
09-11T21:10:40,30,"checkPermissions: ""Requested permission:", "never_ask_again""
09-11T21:10:40,20,"screens/Note: ""POST_NOTIFICATION permission was not granted""
09-11T21:10:40,30,"""Running background sync on timer...""
09-11T21:10:40,30,"""Preparing scheduled sync""
09-11T21:10:40,30,"""Sync cancelled because we're on mobile data""
09-11T21:10:40,30,"checkPermissions: ""Checked permission:", "false""
09-11T21:10:26,30,"root: ""root.biometrics: biometricsDone", "true""
09-11T21:10:26,30,"root: ""root.biometrics: biometricsEnabled", "false""
09-11T21:10:26,30,"root: ""root.biometrics: shouldShowMainContent", "true""
09-11T21:10:26,30,"root: ""root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}""
09-11T21:10:26,30,"RevisionService: ""maintenance: Done in 401ms""
09-11T21:10:26,30,"RevisionService: ""collectRevisions: Created revisions for 0 notes""
09-11T21:10:25,30,"RevisionService: ""maintenance: Starting...""
09-11T21:10:25,30,"RevisionService: ""maintenance: Service is enabled""
09-11T21:09:17,30,"RevisionService: ""maintenance: Done in 135ms""
09-11T21:09:17,30,"RevisionService: ""collectRevisions: Created revisions for 0 notes""
09-11T21:09:17,30,"root: ""root.biometrics: biometricsEnabled", "false""
09-11T21:09:17,30,"root: ""root.biometrics: shouldShowMainContent", "true""
09-11T21:09:17,30,"root: ""root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}""
09-11T21:09:17,30,"root: ""root.biometrics: biometricsDone", "true""
09-11T21:09:17,30,"RevisionService: ""maintenance: Starting...""
09-11T21:09:17,30,"RevisionService: ""maintenance: Service is enabled""
09-11T21:08:27,30,"root: ""root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}""
09-11T21:08:27,30,"root: ""root.biometrics: biometricsDone", "true""
09-11T21:08:27,30,"root: ""root.biometrics: biometricsEnabled", "false""
09-11T21:08:27,30,"root: ""root.biometrics: shouldShowMainContent", "true""
09-11T21:08:19,30,"""ResourceService::indexNoteResources: Completed""
09-11T21:08:19,30,"Synchronizer: ""Indexing resources...""
09-11T21:08:19,30,"""ResourceService::indexNoteResources: Start""
09-11T21:08:19,30,"Synchronizer: ""Sync: starting: Starting synchronisation to target 6... supportsAccurateTimestamp = false; supportsMultiPut = false [1694459299658]""
09-11T21:08:19,30,"root: ""root.biometrics: biometricsDone", "true""
09-11T21:08:19,30,"root: ""root.biometrics: biometricsEnabled", "false""
09-11T21:08:19,30,"root: ""root.biometrics: shouldShowMainContent", "true""
09-11T21:08:19,30,"root: ""root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}""
09-11T21:08:19,30,"""Preparing scheduled sync""
09-11T21:08:19,30,"""Starting scheduled sync""
09-11T21:08:15,30,"root: ""root.biometrics: biometricsDone", "true""
09-11T21:08:15,30,"root: ""root.biometrics: biometricsEnabled", "false""
09-11T21:08:15,30,"root: ""root.biometrics: shouldShowMainContent", "true""
09-11T21:08:15,30,"root: ""root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}""
09-11T21:08:14,30,"root: ""root.biometrics: biometricsDone", "true""
09-11T21:08:14,30,"root: ""root.biometrics: biometricsEnabled", "false""
09-11T21:08:14,30,"root: ""root.biometrics: shouldShowMainContent", "true""
09-11T21:08:14,30,"root: ""root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}""
09-11T21:08:13,30,"RevisionService: ""maintenance: Done in 126414ms""
09-11T21:08:13,30,"RevisionService: ""collectRevisions: Created revisions for 0 notes""
09-11T21:08:12,30,"RevisionService: ""maintenance: Done in 33ms""
09-11T21:08:12,30,"RevisionService: ""maintenance: Service is enabled""
09-11T21:08:12,30,"RevisionService: ""maintenance: Starting...""
09-11T21:06:06,30,"RevisionService: ""maintenance: Service is enabled""
09-11T21:06:06,30,"RevisionService: ""maintenance: Starting...""
09-11T21:05:32,30,"root: ""root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}""
09-11T21:05:32,30,"root: ""root.biometrics: biometricsDone", "true""
09-11T21:05:32,30,"root: ""root.biometrics: biometricsEnabled", "false""
09-11T21:05:32,30,"root: ""root.biometrics: shouldShowMainContent", "true""
09-11T21:05:30,30,"RevisionService: ""maintenance: Done in 1062629ms""
09-11T21:05:30,30,"RevisionService: ""collectRevisions: Created revisions for 1 notes""
09-11T21:05:30,30,"RevisionService: ""maintenance: Done in 489ms""
09-11T21:05:29,30,"root: ""root.biometrics: biometricsDone", "true""
09-11T21:05:29,30,"root: ""root.biometrics: biometricsEnabled", "false""
09-11T21:05:29,30,"root: ""root.biometrics: shouldShowMainContent", "true""
09-11T21:05:29,30,"root: ""root.biometrics: this.state.sensorInfo",

**Comment by JackGruber** [comment]
Duplicate https://github.com/laurent22/joplin/issues/8789 
Should be fixed in the next release
