### ISSUE TITLE
json failed, reason: Parse Error: Invalid header value char

### ISSUE THREAD

**Issue by natsort** [laurent22/joplin#8848]
Mac OS Ventura
Joplin 2.12.16

When syncing against Nextcloud server I get  this error:

"json failed, reason: Parse Error: Invalid header value char"

I can see folders "lock" and "temp" is created on nextcloud server.
The same server has no issues when syncing from iOS Joplin app.

## Steps to reproduce

1. install joplin (clean) 
2.  setup sync - validate credentials
Server: https://drive.kbx.dk/remote.php/dav/files/joplinbugx
user: joplinbugx
pw: joplinbugx
4. create a note
5. sync

Error: 
Completed: 12/09/2023 10:37 (75s)
Last error: FetchError: request to https://drive.kbx.dk/remote.php/dav/files/joplinbugx/locks/2_1_fbc65c60dc48411586b683bbac6b7c16.json failed, reason: Parse Error: Invalid header value char

## Describe what you expected to happen
sync on notebooks/notes to nextcloud user.

## Logfile

DevTools failed to load source map: Could not load content for file:///Applications/Joplin.app/Contents/Resources/app.asar/gui/note-viewer/pluginAssets/mermaid/mermaid.min.js.map: Unexpected end of JSON input
Logger.ts:247 10:42:08: MigrationHandler: Acquiring exclusive lock
Logger.ts:247 10:42:34: FileApi: Could not retrieve remote date - defaulting to device date: FetchError {message: 'request to https://drive.kbx.dk/remote.php/dav/fil…d, reason: Parse Error: Invalid header value char', type: 'system', errno: 'HPE_INVALID_HEADER_TOKEN', code: 'HPE_INVALID_HEADER_TOKEN', stack: 'FetchError: request to https://drive.kbx.dk/remote…amRead (node:internal/stream_base_commons:190:23)'}
log @ Logger.ts:247
warn @ Logger.ts:120
(anonymous) @ file-api.ts:184
rejected @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:6
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:7
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:4
remoteDate @ file-api.ts:166
(anonymous) @ LockHandler.ts:348
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:4
currentDate @ LockHandler.ts:347
(anonymous) @ LockHandler.ts:298
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:7
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:4
acquireExclusiveLock @ LockHandler.ts:264
(anonymous) @ LockHandler.ts:431
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:4
acquireLock @ LockHandler.ts:422
(anonymous) @ MigrationHandler.ts:109
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/MigrationHandler.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/MigrationHandler.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/MigrationHandler.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/MigrationHandler.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/MigrationHandler.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/MigrationHandler.js:7
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/MigrationHandler.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/MigrationHandler.js:4
upgrade @ MigrationHandler.ts:83
(anonymous) @ Synchronizer.ts:461
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:4
start @ Synchronizer.ts:366
(anonymous) @ registry.ts:164
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:5
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:5
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:7
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:4
timeoutCallback @ registry.ts:114
listOnTimeout @ node:internal/timers:569
processTimers @ node:internal/timers:512
Logger.ts:247 10:43:05: Synchronizer: FetchError {message: 'request to https://drive.kbx.dk/remote.php/dav/fil…d, reason: Parse Error: Invalid header value char', type: 'system', errno: 'HPE_INVALID_HEADER_TOKEN', code: 'HPE_INVALID_HEADER_TOKEN', stack: 'FetchError: request to https://drive.kbx.dk/remote…amRead (node:internal/stream_base_commons:190:23)'}
log @ Logger.ts:247
error @ Logger.ts:121
(anonymous) @ Synchronizer.ts:1059
rejected @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:6
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:4
start @ Synchronizer.ts:366
(anonymous) @ registry.ts:164
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:5
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:5
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:7
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:4
timeoutCallback @ registry.ts:114
listOnTimeout @ node:internal/timers:569
processTimers @ node:internal/timers:512
Logger.ts:247 10:43:05: Synchronizer: Req 10:41:51: GET https://drive.kbx.dk/remote.php/dav/files/joplinbugx/info.json {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:247 10:43:05: Synchronizer: Res 10:41:51: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>

Logger.ts:247 10:43:05: Synchronizer: Req 10:41:53: GET https://drive.kbx.dk/remote.php/dav/files/joplinbugx/.sync/version.txt {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:247 10:43:05: Synchronizer: Res 10:41:53: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>

Logger.ts:247 10:43:05: Synchronizer: Req 10:41:54: GET https://drive.kbx.dk/remote.php/dav/files/joplinbugx/info.json {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:247 10:43:05: Synchronizer: Res 10:41:54: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>

Logger.ts:247 10:43:05: Synchronizer: Req 10:41:56: GET https://drive.kbx.dk/remote.php/dav/files/joplinbugx/.sync/version.txt {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:247 10:43:05: Synchronizer: Res 10:41:56: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>

Logger.ts:247 10:43:05: Synchronizer: Req 10:42:02: MKCOL https://drive.kbx.dk/remote.php/dav/files/joplinbugx/locks/ {"headers":{"Authorization":"********","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-67226","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:247 10:43:05: Synchronizer: Res 10:42:02: <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\MethodNotAllowed</s:exception>
  <s:message>The resource you tried to create already exists</s:message>
</d:error>

Logger.ts:247 10:43:05: Synchronizer: Req 10:42:08: MKCOL https://drive.kbx.dk/remote.php/dav/files/joplinbugx/temp/ {"headers":{"Authorization":"********","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-82161","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:247 10:43:05: Synchronizer: Res 10:42:08: <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\MethodNotAllowed</s:exception>
  <s:message>The resource you tried to create already exists</s:message>
</d:error>

Logger.ts:247 10:43:05: Synchronizer: Req 10:42:09: PROPFIND https://drive.kbx.dk/remote.php/dav/files/joplinbugx/locks/ {"headers":{"Depth":1,"Authorization":"********","Content-Type":"text/xml","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-35211","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:247 10:43:05: Synchronizer: Res 10:42:09: <?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:response><d:href>/remote.php/dav/files/joplinbugx/locks/</d:href><d:propstat><d:prop><d:getlastmodified>Tue, 12 Sep 2023 08:41:57 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>

Logger.ts:247 10:43:05: Synchronizer: Req 10:43:05: DELETE https://drive.kbx.dk/remote.php/dav/files/joplinbugx/locks/2_1_9b7d35d9817b4d81b9e28cbea18a09b0.json {"headers":{"Authorization":"********","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-26354","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:247 10:43:05: Synchronizer: Res 10:43:05: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>

Logger.ts:247 10:43:05: Synchronizer: Sync: finished: Synchronisation finished [1694508110234]
Logger.ts:247 10:43:05: Synchronizer: Operations completed: 
Logger.ts:247 10:43:05: Synchronizer: Total folders: 1
Logger.ts:247 10:43:05: Synchronizer: Total notes: 5
Logger.ts:247 10:43:05: Synchronizer: Total resources: 3
Logger.ts:247 10:43:05: Synchronizer: There was some errors:
log @ Logger.ts:247
warn @ Logger.ts:120
(anonymous) @ Synchronizer.ts:266
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:4
logSyncSummary @ Synchronizer.ts:246
(anonymous) @ Synchronizer.ts:1096
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
rejected @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:6
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:4
start @ Synchronizer.ts:366
(anonymous) @ registry.ts:164
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:5
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:5
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:7
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:4
timeoutCallback @ registry.ts:114
listOnTimeout @ node:internal/timers:569
processTimers @ node:internal/timers:512
Logger.ts:247 10:43:05: Synchronizer: FetchError {message: 'request to https://drive.kbx.dk/remote.php/dav/fil…d, reason: Parse Error: Invalid header value char', type: 'system', errno: 'HPE_INVALID_HEADER_TOKEN', code: 'HPE_INVALID_HEADER_TOKEN', stack: 'FetchError: request to https://drive.kbx.dk/remote…amRead (node:internal/stream_base_commons:190:23)'}
log @ Logger.ts:247
warn @ Logger.ts:120
(anonymous) @ Synchronizer.ts:269
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:4
logSyncSummary @ Synchronizer.ts:246
(anonymous) @ Synchronizer.ts:1096
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
rejected @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:6
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:4
start @ Synchronizer.ts:366
(anonymous) @ registry.ts:164
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:5
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:7
fulfilled @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:5
Promise.then (async)
step @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:7
(anonymous) @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:8
__awaiter @ /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/registry.js:4
timeoutCallback @ registry.ts:114
listOnTimeout @ node:internal/timers:569
processTimers @ node:internal/timers:512
Logger.ts:247 10:43:05: Sync has finished and note has never been changed - reloading it
Logger.ts:247 10:43:06: DecryptionWorker: cannot start because no master key is currently loaded.

**Comment by general03** [comment]
Hello,

I have the same issue since I upgrade from 2.7 to 3.0.15, before the joplin upgrade the sync was OK.
I don't do anything on nextcloud side

Did you found fix ?

Thanks

**Comment by general03** [comment]
Hello,
I have the same issue, I open a new ticket https://github.com/laurent22/joplin/issues/11240
Thanks
