### ISSUE TITLE
Crash after update to 1.0.151 from F-Droid

### ISSUE THREAD

**Issue by seth100** [laurent22/joplin#885]
### Operating system

- Android v7.1 
- Honor 8 phone

### Application

- Mobile

Crash on app startup after upgrade to v1.0.151.
Don't want to clear data in order not to loose configuration, how can I solve it?

Thanks

**Comment by foxmask** [comment]
[thread of the forum](https://discourse.joplin.cozic.net/t/v1-0-151-crashing-on-android/852) about it
