### ISSUE TITLE
"Download the app Button" Aligned in the left in mobile view

### ISSUE THREAD

**Issue by VivekBaldha0712** [laurent22/joplin#8854]
![image](https://github.com/laurent22/joplin/assets/86009821/b9d8110a-7096-497c-a842-eb5c21ccbcde)

In desktop view, Button is perfectly aligned according to the structure. But in mobile view, as structure change, button should be in center in order to enhance structure of the website

**Comment by laurent22** [comment]
We don't participate in GSoC
