### ISSUE TITLE
Joplin Mac Markdown View -> Render View stuck or blank

### ISSUE THREAD

**Issue by hannesvei** [laurent22/joplin#8859]
I´m using Joplin in a mixed OS setting. I´m using MacOS 10.15 and 13.5.1 (before 12.x) in combination with WIN 11 machines.

With the newer MacOS Versions I found a glitch

When starting the Layout Markdown  |  Render shows left the markdown code and left the correct rendered text.

After a certain time or a switch to another note the render view either freezes ore goes blank.

  ![image](https://github.com/laurent22/joplin/assets/122828295/b6798d0a-f23b-4ae3-8489-9b05385d1cba)
![image](https://github.com/laurent22/joplin/assets/122828295/0af74513-1c29-4a3a-b20f-f506be70b358)

## Environment

Joplin version: Joplin 2.12.16 (prod, darwin)
Platform: 13.5.1 (22G90)
OS specifics: 

## Steps to reproduce

1. Open Joplin MAc
2. Switch note
3. Renderview is blank

## Describe what you expected to happen

The Render viwe should behave like on my Mac 10.15 or windows machines eg. stay in sync with the note in markdown

## Logfile
[-1694560147053.log](https://github.com/laurent22/joplin/files/12591517/-1694560147053.log)

**Comment by personalizedrefrigerator** [comment]
It's possible that this is related to a plugin. Does this still happen when all plugins are disabled?

**Comment by hannesvei** [comment]
What ever it was, it was related to plugins!

I disabled all plugins and gradually enabled them again. Now its working als supposed.

A great thank you to [personalizedrefrigerator]
