### ISSUE TITLE
New installation fails to run after installing with brew

### ISSUE THREAD

**Issue by mrcybermac** [laurent22/joplin#886]
### Operating system
- macOS

### Application
- Terminal

Hi.

Installed from scratch successfully using `brew install joplin`
Error when subsequently trying to run `joplin` from command line:

```
➜  joplin
module.js:540
    throw err;
    ^

Error: Cannot find module '/usr/local/Cellar/joplin/1.0.116/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/Cellar/joplin/1.0.116/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**Comment by foxmask** [comment]
Which version did you installed?

**Comment by mrcybermac** [comment]
It's in the path in the stack trace:  1.0.116

**Comment by tessus** [comment]
This is kind of weird. brew uses npm to actually install joplin.

I use `npm install` to install Joplin on Linux and macOS and I didn't run into this issue.
However, I had the same problem when trying to get the Electron client to run. Very strange.

**Comment by mrcybermac** [comment]
I've gathered some clues.

The command in the stack trace tries to build a path to the sqlite3 binary, and it uses the sqlite3 package.json for help.  If we look in the sqlite3 package.json (https://github.com/mapbox/node-sqlite3/blob/master/package.json) we see that it uses this interpolation to build the path to its binary:

`"module_path": "./lib/binding/{node_abi}-{platform}-{arch}"`

If we look at the path that it's trying to find in the stacktrace we can see that the path inherits a `node_abi` of `node-v57`. 

Here is the path it's trying to find on my system in the joplin installation directory:
`/usr/local/Cellar/joplin/1.0.116/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node`

But here is the the path that actually exists on my system (the difference is the 'v64'):
`/usr/local/Cellar/joplin/1.0.116/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node`

So I dug a little deeper and found this commit which shows that node version 8 correlates with 'v57' ABI and node version 10 correlates with 'v64' ABI:
https://github.com/mapbox/node-sqlite3/commit/9820bfc12880d4a431088fad62622f93f015622d

Sure enough node on my system was node version 8.  After I upgraded to node version 10 joplin was able to start up.

Though I'm now able to run joplin this sure still seems like a bug of some kind.  I'm not sure if the bug is with sqlite3 or joplin.  It looks like somewhere it's mistakenly assuming/hardcoded to use node version 10.  Somehow the installation wrote a folder name of `node_modules/sqlite3/lib/binding/node-v64-darwin-x64` even though I had node version 8 running on my system and it should have had `v57` instead.

**Comment by tessus** [comment]
This is a great analysis of this issue. Maybe @laurent22 can give his input as well. I believe he opened an issue with node-sqlite a while back.

**Comment by mrcybermac** [comment]
@laurent22 
Yeah the issue could be the npm version.  I use node version manager (nvm) to switch between node versions.  It looks like I'm using the latest version of npm (6.4.1) no matter what version of node I'm using at the time.  So if the build gets the 'node abi' from npm when it builds the path, that could be why it's assuming the latest version of node.  

If this is indeed what is happening it does seem like a wrong approach built on an incorrect assumption that the version of npm and node will always correlate with the same 'node abi', which they won't obviously.  Seems like a 'node abi' should be calculated directly from node, not inferred through a different tool.    

All that being said, not sure why the sqlite3 install is hardcoding a file path to a specific version of node (or potentially the npm version actually).  If you install joplin with brew using node/npm v8 then upgrade to v9 or v10 the installation just straight up breaks.  ...The sqlite3 or joplin applications don't necessarily have any issues or errors at all with the higher version, but the installation itself just breaks due to hardcoded path.  If sqlite3 is somehow dependent on a node version then it should probably be enforced when run in node rather than by a hardcoded/encoded file path in the installation.  For example, sqlite3 could give an error saying, "This version of sqlite3 requires node version 10" or something like that.  Just a thought.

**Comment by tessus** [comment]
@mrcybermac do you think you could open an issue with node-sqlite3? IMO this is something they should fix.

**Comment by mrcybermac** [comment]
Sure I can do that

**Comment by earthday** [comment]
Similar issue in my Mac, https://github.com/laurent22/joplin/issues/1153

**Comment by iiian** [comment]
Having same issue on `macOS mojave 10.14.2`, `node v10.15`. 

Would **love** to be able to install/use this program.

**Comment by tessus** [comment]
@iian according to the `node-sqlite3` web site, node v10.15 is not even supported.
as a workaround you could try to create a symbolic link..

e.g. error  message says: Cannot find module `/usr/local/Cellar/joplin/1.0.116/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node` so now go to `/usr/local/Cellar/joplin/1.0.116/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/` and check what is there. e.g. `node-v67-darwin-x64`
then do a `ln -s node-v67-darwin-x64 node-v57-darwin-x64`

Pleawe note that this might not work.

**Comment by jkimmell-astound** [comment]
```
npm install -g joplin
```
Worked like a charm!

**Comment by nooop3** [comment]
this is the `napi_build_version` conflict, i  have a solution. 
```bash
alias joplin="nvm exec --silent system joplin"
```

and if you installed nvm by brew,  you should fix `nvm-exec` by [sr105](https://github.com/nvm-sh/nvm/issues/856#issuecomment-417187758)
```bash
cd ~/.nvm
ln -s $(brew --prefix nvm)/nvm.sh
ln -s $(brew --prefix nvm)/nvm-exec
```
