### ISSUE TITLE
Assets order for github releases

### ISSUE THREAD

**Issue by skydive241** [laurent22/joplin#8864]
## Describe what you expected to happen
The order of the joplin assets to download via github releases changes nearly with every new release. Is it possible to establish and keep a specific order? This would make it easier to download the correct software packages for automated updates.

It's not very important, but it would make at least MY update process easier! :)

Thanks and greetings from germany
Patrick

**Comment by Daeraxa** [comment]
You mean on the assets page? I don't think there is any explicit control over the order - GitHub sorts them automatically based on the name of the file. There have been changes to some of the executables recently (such as the addition of the apple silicon .dmgs and .zips) which will obviously have an effect to the overall list but I don't think it would be a good promise that no new assets would be added to the list or make contrived file names just to make sure they add to the bottom of the list or something.

So long as the pattern of the filename itself doesn't change it should be easy to grab the correct release still from the API.

**Comment by skydive241** [comment]
Hi and thanks for the answer! Yes, I mean on the assets page. Okay, if you cannot control the order yourself, you can close my issue. Of course, new assets change the order, but if you don't change the order by purpose, I will have to accept it. :)

Thanks again and greetings,
Patrick
