### ISSUE TITLE
Despite enough space to display all toolbar icons they are collapsed into three-dot icon

### ISSUE THREAD

**Issue by tconsta** [laurent22/joplin#8865]
## Environment

Joplin version: 2.12.16 (prod, darwin)
Platform: MacOS
OS specifics: Ventura 13.5.2 (22G91)

### Case 1

1. Make WYSIWYG editor width wide enough to display all the default and plugin icons.
2. Restart Joplin 
3. The icons will be collapsed into three-dot "More" icon.

### Case 2

1. Make WYSIWYG editor width wide enough to display all the default and plugin icons.
2. Switch to Markdown editor and then back to WYSIWYG
3. The icons will be collapsed into three-dot "More" icon.

### Case 3

And worst of all, this happens all the time without any reason, I just work, switching to other apps and back and realize at some point that the icons have been collapsed again. 

***

I find myself quite often moving the editor width to uncollapse it into the toolbar (either way, if you just press three-dots button it appears as a pop-up menu). Related support question https://discourse.joplinapp.org/t/wysiwyg-toolbar/27322

Is there any workaround involving editing *userchrome.css*? 

## Describe what you expected to happen
If the WYSIWYG editor width is wide enough do display all the default and plugin icons, those icons should never be collapsed into three-dot "More" icon.

## Logfile
Neither errors nor warnings

**Comment by laurent22** [comment]
Is it any better in prerelease 2.13?

**Comment by tconsta** [comment]
@laurent22 much better, thanks!
