### ISSUE TITLE
Installer no longer honors default browser settings

### ISSUE THREAD

**Issue by shava23** [laurent22/joplin#8869]
Fail.

## Environment

Joplin version: 2.12.15
Platform: Windows
OS specifics: Windows 10 Home 64bit (10.0 build 19045)

## Steps to reproduce

1. Joplin announces most recent release.
2. Tell it to install now.
3. Instead of honoring default browser (Vivaldi) it opens BING 
4. barf

## Describe what you expected to happen

Previously it had honored my default browser setting and opened a download in Vivaldi

**Comment by dpoulton-github** [comment]
The default browser is a Windows setting not a Joplin setting.

On my Win10 system the default browser is Waterfox. I have just installed 2.12.15 and when it prompted me to downlod the upgrade it was downloaded by Waterfox.

This is my default browser setting on Windows.

![image](https://github.com/laurent22/joplin/assets/60117449/1a4dc974-586a-43e7-a706-4881d47adfeb)

What does yours show?

IIRC some Windows Updates "suggest" the user switches to "better" browser settings and if you are not careful with your response to the prompt it will set the browser to Edge.

**Comment by shava23** [comment]
Thanks, I know that.  However a couple versions ago, it jumped to Bing even
though my Windows systems setting was Vivaldi.  It seems to have rectified
itself in the last release -- I should have noted that on Github, but I
figured the Github report was fixed and closed.

Silly me...;)

Thanks for all you do!

Shava Nerad
***@***.***
https://patreon.com/shava23
