### ISSUE TITLE
[enhancement] Utilize XDG_DATA_HOME for data files

### ISSUE THREAD

**Issue by NGenetzky** [laurent22/joplin#887]
### Operating system

- Linux

### Application

- Desktop
- Terminal

### Request

Consider moving a data files from out of the "config" directory. Ideally they should be in the "data" directory. At a minimum the "resource" files should be moved, but I believe the sqlite database would also be something to consider.

Reference:

- [XDG Base Directory Specification / variables](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables)

**Comment by foxmask** [comment]
What's the windows alternative for that variable?

**Comment by NGenetzky** [comment]
@foxmask , that specification influences many UNIX based distributions, but Windows has similar definitions that are specific to their OS. I am only familiar with using the Portable Version of Joplin on Windows.

For the PAF structure ([PortableApps / paf / layout](https://portableapps.com/manuals/PortableApps.comLauncher/ref/paf/layout.html)) I would recommend:
```
Z:/PortableApps/JoplinPortable/
Z:/PortableApps/JoplinPortable/Data/log/
Z:/PortableApps/JoplinPortable/Data/resources/
Z:/PortableApps/JoplinPortable/Data/settings/
Z:/PortableApps/JoplinPortable/Data/tmp/
Z:/PortableApps/JoplinPortable/JoplinPortable
```

I consider that a separate concern than the one identified here, but I would be happy to create a separate issue with that content if you would in return vote (👍) for this one.

**Comment by foxmask** [comment]
I'm just asking details ; I'm deciding of nothing ;)

**Comment by krc** [comment]
Agreed, from what is currently in the XDG_CONFIG_HOME/joplin-desktop/ dir, I would say resources/ and database.sqlite should go in XDG_DATA_HOME and/or have configurable location.

not sure what tmp/ gets used for (mine is empty at the moment), but it should possibly go in XDG_CACHE_HOME (usually .cache/)

Not sure where the log files should go, I could see arguments for a few options... 

userstyle.css definitely belongs in XDG_CONFIG_HOME. Hm... I guess the the options are currently stored in the DB with the data? Might be nice to have external plain txt config file for those settings...  even if just optional and values are copied into the db or something (maybe not the password for sync? IDK)

**Comment by NGenetzky** [comment]
Please consider moving to backlog. `.config` should only be for configuration files.
