### ISSUE TITLE
Add indicator to note properties

### ISSUE THREAD

**Issue by Blackjack92** [laurent22/joplin#889]
I would like to add an indicator to a note, so that i can highlight specific notes.
E.g. green --> read and red --> not read yet. (eventually via the note properties)

Is this actually possible? - otherwise this would be a good feature

![image](https://user-images.githubusercontent.com/11227428/46938305-b57ce100-d063-11e8-8546-33dc480b7c5c.png)

**Comment by foxmask** [comment]
or may be something like a grey line instead of black to see the different between read/unread

**Comment by Blackjack92** [comment]
Maybe the color and the meaning behind could be chosen, so that not only "read" and "unread" are possible. Also "important", "to prove", etc.

![image](https://user-images.githubusercontent.com/11227428/46943477-04307800-d070-11e8-9749-0c1b2e4e273a.png)

**Comment by foxmask** [comment]
i prefer this new layout instead of a bullet ; and the idea too :)

**Comment by foxmask** [comment]
May be, but there is no color to highlight a note. Then may be a color by tag like github ? :) 
then the layout could be 
```
note title 
tag1 tag2
```
where tag1 and tag2 could be display each with their own color.

**Comment by laurent22** [comment]
Yes that would make sense. I guess to accomplish this feature, we basically need:
- Tag colour
- Being able to filter/search by tag

**Comment by foxmask** [comment]
to avoid offtopic here, i made a post about filter/search things on the forum

**Comment by Blackjack92** [comment]
It sounds quit good, with adding tags. This is exactly what I thought of!
