### ISSUE TITLE
simplified page clip : bug capture

### ISSUE THREAD

**Issue by utilisateuralpha** [laurent22/joplin#8894]
Hello
On the web page :

[link page web](https://openclassrooms.com/fr/courses/7008001-debutez-avec-react/7134597-apprehendez-la-logique-de-react)

The Chrome extension 'Joplin Web Clipper' does not capture all range content (simplified page clip mode)
On the example of this web page, the application does not capture all paragraphs beginning with the "i" symbol.
Why is this and how can I fix it?
..................................................................................................................
Here are examples of some paragraphs (in the previous web page) not captured :

1)
“L’un des plus populaires” ? Comment on le sait ?De nombreux rapports vont dans ce sens depuis des années (vous pouvez par exemple le voir sur le rapport de State of JS 2022, ou bien en France dans les tendances de recherches sur la plateforme de freelances Malt). Vous pourrez également confirmer cette information avec vos propres recherches dans le monde des frameworks JS !

2)
Un composant = HTML + CSS + JS.

3)
La méthode que je vous montre ici n'est pas une méthode utilisée dans le monde du travail. Il s'agit d'un moyen de vous montrer les bases sans avoir à faire trop de paramétrage, et sans avoir à utiliser trop d'outils tels que Webpack. Ici, nous pouvons nous concentrer sur l'essentiel. Si vous voulez suivre directement une installation avec Create React App, rejoignez-moi à la partie suivante.

**Comment by laurent22** [comment]
The simplified clip is not guaranteed to work as it depends on the page. Does it work with regular markdown clip?

**Comment by laurent22** [comment]
As I understand the content in these boxes are asides, so they are purposely removed from the simplified document. It makes sense to me but I can understand why in some cases it might be nice to keep them. There's no fix other than clipping the full page
