### ISSUE TITLE
Adding a hyperlink in WYSIWYG editor does not persist after switching from Markdown Editor back to WYSIWYG.

### ISSUE THREAD

**Issue by futuremotiondev** [laurent22/joplin#8895]
## Environment

Joplin version: 2.12.17 (prod, win32)
Platform: Windows 10 Pro x64
OS specifics: Version 22H2

![Joplin_C72La46Wet](https://github.com/laurent22/joplin/assets/33441569/f01d7b51-2dd8-45a5-b004-2b7746e913ec)

## Steps to reproduce

1. In WYSIWYG editor: Select some text and then click on the hyperlink button on the toolbar.
2. Paste or enter your hyperlink and click OK.
3. Switch to the markdown editor mode, and then back to the WYSIWYG editor.
4. Notice your hyperlink is no longer a hyperlink (You can also see this in the previous step when you switch to the markdown editor).

I created a screen recording of the behavior. Here it is:

https://github.com/laurent22/joplin/assets/33441569/b5674826-5d63-40ca-887f-fed9ec900b40

## Describe what you expected to happen

I expected the hyperlink to remain a hyperlink after switching views.

## Logfile

Here are a bunch of errors I copied from the DevTools console:

[Joplin-Console-Log.txt](https://github.com/laurent22/joplin/files/12641937/Joplin-Console-Log.txt)

**Comment by personalizedrefrigerator** [comment]
I'm able to reproduce this if I disable "Linkify" in markdown settings.

Is "Linkify" disabled in markdown settings? If so, try enabling it:
![Screenshot: Settings > Markdown: Linkify checkbox checked](https://github.com/laurent22/joplin/assets/46334387/00440762-6b19-450e-8404-dcfa989874b2)

**Comment by futuremotiondev** [comment]
> I'm able to reproduce this if I disable "Linkify" in markdown settings.
> Is "Linkify" disabled in markdown settings? If so, try enabling it

This was the problem. Thank you so much for the quick reply and solution.

**Comment by personalizedrefrigerator** [comment]
I'm re-opening this -- links should not disappear even if linkify is disabled. (This is still a bug).
