### ISSUE TITLE
Plugin toolbar buttons that don't specify an icon are invisible

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8898]
Previously if a plugin doesn't specify an icon (which is optional) for a button, it would display "cog" icon. Now it displays nothing so the button is invisible.

I think this regression has been introduced by this change:

https://github.com/laurent22/joplin/commit/776b6d8f1259e4b6ba29805355aa946620c113e2#diff-fb2784e1f41d3bf2a4009fddb388dc101430ea8c9a3993b9df538b0fa77be2d7L302

**Comment by personalizedrefrigerator** [comment]
I'm experiencing this bug in the markdown editor with Joplin v2.11.11, so I don't think it's a regression. I'll try to have a fix available for this by Thursday.
