### ISSUE TITLE
Joplin white screen at launch after installing Markmap plugin 

### ISSUE THREAD

**Issue by xto3** [laurent22/joplin#8899]
Hi, 

I installed multiple plugins today to give them a try, including Markmap. After relaunch, I ended with a white screen and no access to my notes.

I followed the step-by-step process for debugging described here: [https://joplinapp.org/debugging/](https://joplinapp.org/debugging/)

Joplin properly launched in safe mode:

**Console output**

DevTools failed to load source map: Could not load content for file:///Applications/Joplin.app/Contents/Resources/app.asar/pluginAssets/mermaid/mermaid.min.js.map: Unexpected end of JSON input

## Environment

Joplin version: 2.13.1
Platform: macOS 13.5.2
OS specifics: N/A

## Steps to reproduce

1. Install Markmap plugin from the settings section in Joplin
2. Relaunch
3. White screen

## Describe what you expected to happen

Joplin and the Markmap plugin should launch properly.

Thanks for your help.

**Comment by laurent22** [comment]
Please could you check again the console and see if there's any errors or warnings? The one you reported is normal

**Comment by xto3** [comment]
Hi @laurent22. Thanks for your quick reply. I have disabled all the plugins and then re-enabled Markmap. It works properly now. The blank screen at launch could have been related to another plugin. I'll keep investigating and will provide more input if I applicable.
