### ISSUE TITLE
About Joplin dialog - Text is preselected (ctrl+a as default)

### ISSUE THREAD

**Issue by yafp** [laurent22/joplin#89]
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop - 0.10.39
- [ ] Mobile
- [ ] Terminal

---
If i do open the "About Joplin" dialog the entire text is preselected, similar to pressing CTRL+a.
Text can be deselected and cursor can be placed inside the text.

Not sure if that behaviour is expected. It's for sure a really minor thing.

**Additional ideas:**
adding project url and app icon to the about dialog would add some benefit as well.
![20171212_081014](https://user-images.githubusercontent.com/67605/33871800-5b60d53c-df14-11e7-93a8-fcca0fe844ee.png)

**Comment by laurent22** [comment]
This would need to be fixed on Electron directly so closing it for now.
