### ISSUE TITLE
Add support for multiple plural forms

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8912]
Regarding the string `%d notes`:

> The problem with those is that the noun form changes depending on the number, e.g.
>
> - 1 notatka
> - 2 notatki
> - 5 notatek
>
> This is for Polish only, other languages may have their own variations.

It means we should support multiple plural forms as described here for example:

https://stackoverflow.com/questions/12121515/multiple-plural-forms-in-gettext

Official doc: https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html

Here's a list with the plural form conditions for each language: https://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html

The feature would have to be available to the Joplin app and to the translators.

Edit: In fact plural forms don't appear to be working at all?

**Comment by CptMeetKat** [comment]
Looking into this

**Comment by laurent22** [comment]
@CptMeetKat, have you been looking into this issue? I guess one problem is that the "msg_plural" string is not currently processed by the translation builder script. And also we're only saving msgstr[0], while we'd also need [1], [2], etc. for certain languages.

The condition under which we display a particular string also needs to be saved depending on the language. Normally this is part of the .po file but that can be modified or deleted by a translator, so it might be better to put that logic somewhere in `locale.ts::_n()`
