### ISSUE TITLE
Desktop: Scrollbar invisible on hover

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#8920]
## Environment

Joplin version: a8efad988722ffa473a865c470cfc33658feb578
Platform: Desktop
OS specifics: openSUSE 20230917

## Steps to reproduce

1. Set the theme to light
2. Hover over the markdown editor's scrollbar

## Describe what you expected to happen

The scrollbar thumb should not be invisible on hover.

## Screenshot

![screenshot: scrollbar thumb and background are same color](https://github.com/laurent22/joplin/assets/46334387/dd7a0c91-eed2-487f-973c-16c590c8be9d)

**Comment by personalizedrefrigerator** [comment]
Possibly related to c824f252623f21898a993a1529e493933bae6f4c

**Comment by laurent22** [comment]
I think for now we'll revert this commit and applies the fix to 2.12 too

**Comment by laurent22** [comment]
Reverted
