### ISSUE TITLE
Annoying stream of delete messages drom DropBox regarding Joplin Temp files

### ISSUE THREAD

**Issue by aplteam** [laurent22/joplin#8930]
I am syncing with DropBox. Interval time is 5 minutes.

I constantly (several in less than 5 minutes) get messages that some file that was obviously created by Joplin got deleted. This is very annoying and blurs matter regarding important DropBox messages.

I also wonder why there is so much activity anyway: I may get a hundred such messages per day without editing a single note, or even looking at it.

## Environment

Joplin version: 2.12.17
Platform: Windows 
OS specifics: 10

**Comment by Daeraxa** [comment]
This isn't a bug, this is just how Joplin works. Are you actually syncing your Joplin sync target locally? If you are using the DropBox sync type and not file system then there isn't any need to have it on disk.

**Comment by aplteam** [comment]
> Are you actually syncing your Joplin sync target locally?

I don't understand the question, please elaborate.

**Comment by Daeraxa** [comment]
Are you downloading your Joplin sync target data to your computer? i.e can you see the Joplin folder within your local Dropbox folder. If so, then you shouldn't be doing that and should be excluding it.

**Comment by aplteam** [comment]
??

I don't do anything. I just told Joplin to sync with DropBox.

Joplin has decided to put its data folder into DropBox/Apps/ - I was not involved. I am doing nothing at all, I leave it Joplin to up- and download data as required, depending on which device made I changes.

Now Joplin features files in the locks/ sub dir. These are the ones that constantly pop up, for no apparent reason. Why is there any need to lock something if I have not even started the application?!

**Comment by Daeraxa** [comment]
Right but Joplin syncs via the API, not local files. If you don't want local file notifications then don't sync them to your local device. If you exclude them then you wont get any notifications.

**Comment by roman-r-m** [comment]
One may want to use Dropbox for other purposes as well which requires syncing it.
But I believe there was an option to exclude certain folders from being downloaded. Excluding `Apps/Joplin` should fix the issue.

**Comment by Daeraxa** [comment]
That's exactly what I'm getting at, there isn't a need to include the sync folder so exclude it from downloading, certainly don't mean to stop all of Dropbox syncing as that defeats most of its raison d'être.

**Comment by dpoulton-github** [comment]
Found this picture on the forum which shows the Joplin sync folder being excluded in the Dropbox client so there are no notifications when a file in Apps/Joplin changes.

![image](https://github.com/laurent22/joplin/assets/60117449/aec1f788-37ef-448f-978a-cfda2ec6bab8)

**Comment by aplteam** [comment]
That makes no sense whatsoever: although it is correct that I would not get those messages anymore, this is because that prevents DropBox from synchronizing anything.

**Comment by roman-r-m** [comment]
Not anything, just the Joplin folder

**Comment by dpoulton-github** [comment]
The point being raised here is that **if you are using the Dropbox connector** in Joplin settings (see image) Joplin is connecting **directly** to Dropbox. You do not even need the Dropbox client installed on your system for Joplin to be able to sync to Dropbox.

![image](https://github.com/laurent22/joplin/assets/60117449/3d389106-9935-4220-ba13-1ec79809e787)

If you are connecting directly and if you do have the client installed, all you are doing is allowing the Dropbox client to unnecessarily copy all the Joplin sync data back onto your machine into the Dropbox client's **copy** of the Apps/Joplin folder. Joplin is not using this as it is communicating directly with Dropbox using the Dropbox API.

**Comment by aplteam** [comment]
That makes sense. Tx for this.
