### ISSUE TITLE
Copying and pasting an image in the RT editor does not work

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8933]
- Copy an image from somewhere
- Paste it in the RT editor

=> It shows a broken link. The resource also appears to be invalid.

<img width="155" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/61baeaef-80a3-4815-b604-947be7b894ec">

**Comment by personalizedrefrigerator** [comment]
Pasting images seems to work in version 2.12.17 and 2.12.18. As such, this is likely a regression in v2.13.

I'm testing with the following images copied (from Firefox/GitHub) and pasted into the rich text editor:
- ![image of a handwritten word: Test](https://github.com/laurent22/joplin/assets/46334387/4b43327e-9c74-4430-9128-2221ed9ee0c7)
- ![Joplin logo](https://raw.githubusercontent.com/laurent22/joplin/dev/Assets/LinuxIcons/256x256.png)

**Edit**: They also seem to be working in a build from the [latest dev commit](fc515313cff934e904e71689bc9bda339ecb87d6).

**Comment by laurent22** [comment]
I cannot replicate it anymore so closing for now. I'll see next time what image exactly caused this
