### ISSUE TITLE
Joplin shows blank screen only

### ISSUE THREAD

**Issue by MatejKovacic** [laurent22/joplin#8935]
When I run Joplin desktop, the screen is empty. I cannot see anything, however, if I try to blankly select a text and can copy it, but basically I can not see anything.

## Environment

Joplin version: Joplin 2.12.17 (prod, linux)
Platform: Linux 
OS specifics: Ubuntu 23.04
Revision: b9cb9e42f

## Steps to reproduce

1. Open Joplin app.
2. Nothing is visible

## Describe what you expected to happen
I should see the content of the window. :)

## Logfile

Cannot provide it, there are no menus or anything else visible.

**Comment by ageorgiev-bg** [comment]
Same thing with 2.13.1

**Comment by iRomanyshyn** [comment]
Check v2.12.18, it looks like the problem was in the Electron.

**Comment by MatejKovacic** [comment]
Any idea when v2.12.18 will be in Snap store?

**Comment by iRomanyshyn** [comment]
> Any idea when v2.12.18 will be in Snap store?

It's a good question to James Carroll, the [publisher](https://snapcraft.io/publisher/james-carroll). But I prefer to use AppImage installed with official installation script:

`wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash`

**Comment by MatejKovacic** [comment]
Well, I already have snap version...

**Comment by bavaria-blue** [comment]
New version fixed the problem for me.

**Comment by MatejKovacic** [comment]
For me also. I got the new version through Snap today and it works like a charm. :)

**Comment by JGCarroll** [comment]
You can always revert a snap with e.g `sudo snap revert joplin-desktop`; which will undo an update if there's a regression like this one. For a lot of snaps (i.e including Joplin) that'll even rollback the database of notes to how it was before the update happened incase there was a database schema update or similar.

But yes, the snaps updated about 12 hours ago and usually will have ~90% deployment within 48 hours. Unfortunately I was occupied this weekend with a wedding and some nice extras like locking my car key in my car!

The issue itself seems to be specific to AMD Ryzen users on certain GPU driver stacks so unfortunately wasn't something easily caught even with the manual testing I do before each snap release.

**Comment by hovancik** [comment]
I have the same issue via install script: 

![Screenshot_20231107_164943](https://github.com/laurent22/joplin/assets/4745859/0d37344b-3dc5-4183-ae70-a64abfe31729)
