### ISSUE TITLE
Regression: Editing note Create/Update erases the previous value

### ISSUE THREAD

**Issue by jtikalsky** [laurent22/joplin#8937]
When I open a note's properties to edit its creation or update date, the existing value is now erased.  In the past, it was preserved, so that you could edit it without having to retype the whole thing.

(I occasionally do this for certain notes by copying 'created' to 'updated' and adjusting it, when I make minor fixes months later, to preserve the note's sorting properties.)

## Environment

Joplin 2.12.17 (prod, win32)

Sync Version: 3
Profile Version: 43
Keychain Supported: Yes

Revision: b9cb9e4

Windows 11

## Steps to reproduce

1. Open note properties
2. Click "edit" icon to the right of "Updated".

## Expected:

3. The current value is in the textbox and can be edited.

## Actual:

3. The textbox is empty and you must retype the current value to copy or edit it.

**Comment by CptMeetKat** [comment]
Looking into this
