### ISSUE TITLE
Fullscreen mode doesn't work.

### ISSUE THREAD

**Issue by MatthewBlanchard** [laurent22/joplin#8941]
## Environment

Joplin version: Latest
Platform: Linux
OS specifics: Fedora

Pressing f11 doesn't do anything but get rid of a single side bar. The small screen experience with this app is frankly terrible because you can't fullscreen or hide half the elements. This is standard application behavior.

The behavior I expect from hitting f11: The window decorations disappear and it's content area takes up the whole screen.

**Comment by VatsalBhuva11** [comment]
@MatthewBlanchard Is the desired view obtained by pressing f10, and f11? f10 toggles the "sidebar", while f11 toggles the "note list". Maybe a short-cut that achieves both these results simultaneously might be convenient for a fullscreen mode. Or do you want to hide the bar at the top as well (File, Edit, View, etc.) ?

**Comment by MatthewBlanchard** [comment]
It should work like Obsidian, VSCode, etc. Windows decorations disappear and it becomes fullescreen.
