### ISSUE TITLE
Lose URL when copy & paste a markdown link in WYSIWYG mode

### ISSUE THREAD

**Issue by mjj2000** [laurent22/joplin#8946]
## Environment

Joplin version: 2.12.18 (prod, darwin)
Platform: macOS
OS specifics: 13.6

## Steps to reproduce

1. copy a markdown link in WYSIWYG mode
        <img width="321" alt="image" src="https://github.com/laurent22/joplin/assets/1393773/c9bd9c64-1db8-47f3-8e05-78f0e7ef2409">

    original markdown source

    ```
    [I am a markdown link](:/c6c2e21be93e43o3af6ae84b31beb577)
    ```
2. paste it to the other note in WYSIWYG mode
3. observe the markdown source of the pasted link. The url is replaced with `#`

    ```
    [I am a markdown link](#)
   ```

## Describe what you expected to happen

It should keep the original markdown link url after pasting.

**Comment by CptMeetKat** [comment]
Looking into this
