### ISSUE TITLE
Sync via OneNote quadruplicates (and more) a note

### ISSUE THREAD

**Issue by th** [laurent22/joplin#8952]
Sync multiplies notes.

## Environment

Joplin version: 2.12.18 (Win), 12.12.13 (iPadOS
Platform: Windows, iPadOS
OS specifics: 

## Steps to reproduce

1. I create a new note on PC, consisting only of text and bullet points.
2. I sync from the PC app.
3. I sync on the iPadOS app
4. The note appears on the iPad, but at least thrice, usually four times ,just now I got six copies.

## Describe what you expected to happen
Only one copy of each note.

You can delete the copies one by one, but there is no indication which one the "real" one is, so you usually delete the one that makes the PC note disappear on next sync.

**Comment by laurent22** [comment]
Do you use any plugin?

**Comment by th** [comment]
No plugins.

This morning everything looked fine again, the additional notes were gone (probably another sync over night), but I could just reproduce the problem with a new note on Win that resulted in six versions on iPad.

Sync status says "14 conflicts". but I can only see that in the settings, there is no message when syncing.
