### ISSUE TITLE
Always return true

### ISSUE THREAD

**Issue by takuya** [laurent22/joplin#8953]
## MAILER_SECURE environment cannot use false
```
secure: !!Number(env.MAILER_SECURE) || true,
```

[!!Number('false') || true](https://github.com/laurent22/joplin/blob/67a000add903fc9d0329dc5388564e28f463898a/packages/server/src/config.ts#L90C11-L90C46) is always return true.

here is return sample
```
!!Number('-1') || true // => true
!!Number('0') || true // => true
!!Number('1') || true // => true
```

so this env uselsess 
```
MAILER_SECURE=0
MAILER_SECURE=false
```

**Comment by laurent22** [comment]
I don't know what code you're looking at but we haven't used that variable for a while now. It's `MAILER_SECURITY` now
