### ISSUE TITLE
Desktop Dev console in Dev indicates recursive re-renders

### ISSUE THREAD

**Issue by CptMeetKat** [laurent22/joplin#8954]
The dev console is reporting maximum depth exceeded for a recently modified component. This started in https://github.com/laurent22/joplin/commit/a1821d607e8a7305500d9f112255a63f11b8f04a

![image](https://github.com/laurent22/joplin/assets/32354598/11a82f7c-01dd-4851-a944-8c03b3274455)

## Steps to reproduce
1. Open Note Properties 
![image](https://github.com/laurent22/joplin/assets/32354598/a213ff86-4144-41e7-8559-9d9a5323dfd9)
2. Click OK
3. Observe Console

## Environment

Joplin 2.13.1 (dev, linux)

Client ID: 19ad5dea08324a7b97e2b5ff1e1cf583
Sync Version: 3
Profile Version: 43
Keychain Supported: No

Revision: a1821d607

## Describe what you expected to happen
- The Dev console should not report maximum update depth exceeded

**Comment by laurent22** [comment]
Fixed in 34c4b832ba7760aa343372b0b74e704e9bcc3342
