### ISSUE TITLE
Double Braces preventing note from syncing

### ISSUE THREAD

**Issue by cdb-boop** [laurent22/joplin#8963]
### Joplin version:
2.12.18 (prod, win32)
Client ID: d270c794fd96441ca65d90ef059baa49
Sync Version: 3
Profile Version: 43
Keychain Supported: Yes

Revision: a0a4a81

### Platforms:
- Windows
- iOS
### OS specifics:
- Microsoft Windows 11 Home (10.0.22621)
- iOS 16.7 (20H19)

## Steps to reproduce
1. Create a new note containing the following two braces: {{
2. Sync to WebDAV server.
3. Make any change to the note so it will be resynced.
4. Sync to WebDAV server.

## Describe what you expected to happen
I was unable to see the note afterwards on any other device after the error happened. I tried clearing the note's contents and syncing again but the error wouldn't go away. I had to completely remove the note and sync all devices to completely flush out the problem.

## Logfile
```
"Error: Got metadata for path but could not fetch content: 2c7f39969d58424f949b36f4e96c5df6.md
Error: Got metadata for path but could not fetch content: 2c7f39969d58424f949b36f4e96c5df6.md
    at Synchronizer.<anonymous> (C:\Users\CDBPC\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:584:43)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\CDBPC\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
```

[log_double_brace.txt](https://github.com/laurent22/joplin/files/12725809/log_double_brace.txt)

**Comment by laurent22** [comment]
What WebDAV server is it? It means the server reports that the file is there when listing the files, but then doesn't return it when the app requests it.

**Comment by cdb-boop** [comment]
A local Caddy server using a Caddyfile:
```Caddyfile
http://192.168.0.19:2019 {
	encode zstd gzip
	templates
	root C:\Users\User\Documents\Joplin\Notes
	basicauth bcrypt {
		# password: password_goes_here
		user_name_goes_here hash_goes_here
	}
	route {
		webdav
		file_server browse
	}
}
```

An example Caddy server's error output before and after:
> http.log.error  template: /f0495dec26f94f85b75494e2d76569af.md:5: function "id" not defined   {"request": {"remote_ip": "192.168.0.19", "remote_port": "56873", "client_ip": "192.168.0.19", "proto": "HTTP/1.1", "method": "GET", "host": "192.168.0.19:2019", "uri": "/f0495dec26f94f85b75494e2d76569af.md", "headers": {"Accept-Encoding": ["gzip,deflate"], "Connection": ["close"], "Authorization": [], "Cache-Control": ["no-store"], "User-Agent": ["Joplin/1.0"], "Accept": ["*/*"]}}, "duration": 0.0010586, "status": 500, "err_id": "a66wektty", "err_trace": "templates.(*Templates).executeTemplate (templates.go:425)"}

> http.log.error  template: /f0495dec26f94f85b75494e2d76569af.md:5: function "id" not defined   {"request": {"remote_ip": "192.168.0.19", "remote_port": "57015", "client_ip": "192.168.0.19", "proto": "HTTP/1.1", "method": "GET", "host": "192.168.0.19:2019", "uri": "/f0495dec26f94f85b75494e2d76569af.md", "headers": {"Authorization": [], "Cache-Control": ["no-store"], "User-Agent": ["Joplin/1.0"], "Accept": ["*/*"], "Accept-Encoding": ["gzip,deflate"], "Connection": ["close"]}}, "duration": 0.0005035, "status": 500, "err_id": "dsjcbjyag", "err_trace": "templates.(*Templates).executeTemplate (templates.go:425)"}

**I removed `templates` line from the Caddyfile and that seems to have resolved the error.** You can close the issue if you think it is resolved. Thank you.
