### ISSUE TITLE
Pocket Support

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [laurent22/joplin#897]
Can you please add support for pocket so that I can read articles which I've saved in pocket through joplin app.
The problem with Joplin web clipper is that you need the desktop application also for it to save webpages.

**Comment by foxmask** [comment]
With the API you are able to do such a thing. Not difficult. And if you use the webclipper I suppose you use add-on with chrome or nothing special with Firefox and thus everything can be saved in pocket can't you?

**Comment by nr458h** [comment]
Because this is an OpenSource Project going for wallabag instead of Pocket would be the more logical move

**Comment by foxmask** [comment]
I don't know why, but I was waiting for a notice about wallabag :D But as I said earlier, I don't think Joplin will support any external service as now it provides an API that can be used for that.
If you have a little bit of skill with ruby you could make a ruby API supporting Joplin and could be used with huginn. 
On my side I started to support Joplin with [trigger-happy](https://trigger-happy.readthedocs.io/en/latest/) (a project like huginn with less supported services)
Finally may be you could create a post on the forum for asking support for your favorite services ;) Thus we could see who expect what.

**Comment by foxmask** [comment]
https://discourse.joplin.cozic.net/t/support-for-your-favorite-services/924
