### ISSUE TITLE
whole doc in bold font

### ISSUE THREAD

**Issue by Rujula8** [laurent22/joplin#8973]
The document I wrote on Joplin is in the **bold font** even though I didn't select
![Screenshot 2023-09-27 171713](https://github.com/laurent22/joplin/assets/146192428/caf04e61-d349-489b-9936-560ae74e086e)
 it to be.
Please fix this ASAP

**Comment by laurent22** [comment]
Oh that must be fixed ASAP? How about you start by filling up the issue template properly?
