### ISSUE TITLE
iOS Resize image option doesn't work for certain images

### ISSUE THREAD

**Issue by luigicarrini** [laurent22/joplin#8976]
## Environment

Joplin version: 12.12.3
Platform: iOS
OS specifics: iOS 16.6.1.

## Steps to reproduce

1. Send image to Joplin on iPhone via native iOS share dialog.
2. Joplin opens automatically, asks if photo should be resized. Choose _Yes_
3. You get the error message: _Image uri invalid._ and the photo is not attached.
(if you choose _No_, there's no problem.)

Error only occurs with some images.

**Comment by personalizedrefrigerator** [comment]
It's working for me on iOS 17.0.2, Joplin v12.12.3, sharing from Safari and Photos.

Are there any relevant errors in the log (Settings > Log > Errors)? (For comparison, I have several error messages related to sync locks.)

**Comment by luigicarrini** [comment]
If I enable _Always Resize_ large images in settings, it works. 
Seems as if the _Always Ask_ dialog seems to be broken.

(If I choose _No_ when it asks me to resize with _Always Ask_ option enabled, it also works)

Seems to work in most cases. Maybe not that important

**Comment by laurent22** [comment]
Could you post here an image that's having this issue? (But zip it first otherwise GitHub will modify it)

**Comment by luigicarrini** [comment]
here's an image that causes this error - might be due to the filename?

[Whiteboard am 27.09.2023, 19_23_02.jpg.zip](https://github.com/laurent22/joplin/files/12753535/Whiteboard.am.27.09.2023.19_23_02.jpg.zip)

**Comment by wh201906** [comment]
Could you please post the log file there? We need to check what happens when Joplin trying to resize this image.

**Comment by laurent22** [comment]
I checked but that cannot happen with the attached image since it's below 1920px. We need an image that could be used to replicate the bug

**Comment by luigicarrini** [comment]
I just followed the _steps to reproduce_ again and could not reproduce the bug. (Joplin version: 12.13.10, Platform: iOS
OS specifics: iOS 17.2.1). So the iOS share function seems to work fine currently.

**Comment by laurent22** [comment]
Thanks for checking @luigicarrini. So let's close the issue for now
