### ISSUE TITLE
Spell checker issue with British & American dictionaries

### ISSUE THREAD

**Issue by tconsta** [laurent22/joplin#8977]
## Environment

Joplin version: 2.13.1 (prod, darwin)
Platform: MacOS
OS specifics: Ventura 13.5.2 (22G91) 

## Steps to reproduce

Not sure, but probably: enable British spell checker, then switch to American. It will still be British:

<img width="704" alt="image" src="https://github.com/laurent22/joplin/assets/13377078/ed649502-825f-499e-80a1-d0955673105d">

## Describe what you expected to happen

Possibility to use American English or better both American and British simultaneously.

## Logfile

no problems

**Comment by personalizedrefrigerator** [comment]
At least with Spanish+English, it seems to require editing previous lines and waiting for the spellcheck language to change:

https://github.com/laurent22/joplin/assets/46334387/79b6e8eb-a23b-4905-bc78-e21b4885615f
