### ISSUE TITLE
Rich text editor discards repeated `<br/>`s

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#8978]
## Environment

Joplin version: 2.12.18
Platform: Desktop
OS specifics: Linux

## Steps to reproduce

1. Open the rich text editor
2. Type something
3. Press <kbd>Shift</kbd>+<kbd>Enter</kbd> 5 times
4. Type something else
5. Switch to the markdown viewer
6. Switch back to the rich text editor

## Describe what you expected to happen

Repeated `<br/>`s should be preserved.

Note that the default `<p><br/></p>`s generated by pressing <kbd>Enter</kbd> (without <kbd>Shift</kbd>) **are** preserved.

**Comment by laurent22** [comment]
Isn't the fix for this in 2.13?

**Comment by personalizedrefrigerator** [comment]
> Isn't the fix for this in 2.13?

Not unless it's very new (not in the 2.13.1 pre-release). I'm building to test from `dev` now.

**Edit**: The fix does not seem to be present.

**Comment by laurent22** [comment]
I meant this change: https://github.com/laurent22/joplin/commit/35f375d7562f0ab36edc6e179e3c902c96cf0fee It looks like it's supposed to preserved BR tags, or it's not doing anymore? (or only doing it in some cases?)

**Comment by personalizedrefrigerator** [comment]
https://github.com/laurent22/joplin/commit/35f375d7562f0ab36edc6e179e3c902c96cf0fee seems to be specifically for `<p>&nbsp;</p>`s (what TinyMCE generates when pressing enter repeatedly and doesn't handle `<br/>`s).

https://github.com/laurent22/joplin/pull/8469 is also related, but preserves linebreaks when the softbreak setting is enabled (not necessarily preserving repeated `<br/>`s).

**Comment by mr-loop-1** [comment]
Hi @laurent22 I would like to work on this. Please assign me.
