### ISSUE TITLE
To an external editor, editor changes behave differently depending on if the change was made at the source or if it was synced

### ISSUE THREAD

**Issue by taw00** [laurent22/joplin#8984]
> _This is not the easiest to articulate in the summary. Please improve it if you can._
> Joplin 2.12.18, Fedora Linux 37, Joplin Cloud

The behavior of Joplin in how it tracks change, from the context of an external editor, is different depending on if a change happens to the source note via Joplin's internal editor vs. making that change via editing the same note but on a different device and then syncing.

#### Open note in external editor; and then make a change on that note with the internal editor

1. Open an external editor using the toggle on a note.
2. Now change something in the Joplin note, but with Joplin's editor and not the external editor  (Note,  I only use the markdown editor) And do this without clicking Stop  (digression: that word "stop" seems wrong IMHO).
3. Look at the external editor version of the note, it should now present an alert that the source note changed on disk and it should give you option for how to deal with it. —**This is expected behavior.**

… Now do the same then, but where the note gets changed on another device

#### Open note in external editor; and then make a change on that note from a different device

1. Open an external editor using the toggle on the note (device 1)
2. Open the same note, but on a 2nd device (device 2)
3. Make a change on that 2nd device.
4. Wait for the sync to percolate (can take some minutes), or sync from 2nd device, then sync from device 1
5. Look at the external editor on device … No change on disk was noted and the text is the old text.  —**THIS IS UNEXPECTED BEHAVIOR.**

This begs the question: Why would the behavior be different? Why can't the external editor see that something has changed in one case and not in the other?

I bounce between three devices all the time and sometimes something lands in Conflicts and I have no clue why. (In fact, for this test, this note landed there on device number two.) Regardless, something is amiss.

**Comment by taw00** [comment]
undoing stale label

**Comment by taw00** [comment]
Sorry bot. Not complete.

**Comment by justyn** [comment]
So in the second scenario, the changed text has synced from another device onto this device, and the changes are reflected inside the Joplin app, but not in the already open external app?

Whereas if a change is made directly on this device, the already open external app spots the change and updates/warns the user that the file has changed?

**Comment by taw00** [comment]
> So in the second scenario, the changed text has synced from another device onto this device, and the changes are reflected inside the Joplin app, but not in the already open external app?
> 
> Whereas if a change is made directly on this device, the already open external app spots the change and updates/warns the user that the file has changed?

You got it.

**Comment by justyn** [comment]
That seems very inconsistent - this issue should probably stay open then?

**Comment by taw00** [comment]
I have discovered why this happens and it is still an annoying issue that leads to conflicts.

1. Have a note open in an external editor on one machine.
2. Open the note on another machine and edit it.
3. Sync that second machine. Then sync the first machine.

The note mirrors each other on each machine BUT the first machine's external editor still retains the old note and sees no change.

The note that is saved to disk for the external editor (in the .config/joplin-desktop folder on my linux machine) is not being updated by the Joplin application.

Looks like I will have to open a new ticket.
