### ISSUE TITLE
KaTex failing to parse '\set' control sequence

### ISSUE THREAD

**Issue by owenineson** [laurent22/joplin#8988]
Hi all,

When attempting to define a mathematical set using KaTex (such as $\set{x|x<5}$ or its counterpart $\Set{ x | x<\frac 1 2 }$) a KaTex parse error "KaTeX parse error: Undefined control sequence: \set at position 1: \̲ s̲e̲t̲{x|x<5}< div="">" is returned. The KaTex notation is taken from the documentation and I have verified that it renders correctly in other applications. This issue persists when exporting a note as a PDF as well.

## Environment

Joplin version: Joplin 2.12.18 (prod, win32)
Platform: Windows
OS specifics: Windows 10 Pro 19045.3448

## Steps to reproduce

1. Enter either set KaTex function (\set, \Set) e.g. $\set{x|x<5}\set{x|x<5}$

## Describe what you expected to happen

A rendering of the KaTex function i.e.

"$\set{x|x<5}$" --> $\set{x|x<5}$

## Logfile
[debug.txt](https://github.com/laurent22/joplin/files/12775581/debug.txt)

**Comment by laurent22** [comment]
Was that a feature recently added to Katex? In which case we probably need to update the lib

**Comment by owenineson** [comment]
> Was that a feature recently added to Katex? In which case we probably need to update the lib

It looks like it was added in v0.15.6 May 20, 2022 (relevant changelog [here](https://github.com/KaTeX/KaTeX/compare/v0.15.5...v0.15.6)).

**Comment by laurent22** [comment]
I've now setup the project so that Katex gets updated automatically, so it should be part of the next release. Commit: 37efd2d91f019b19e145ddba049854989616ade7
