### ISSUE TITLE
Scroll while editing note on mobile Android app

### ISSUE THREAD

**Issue by seth100** [laurent22/joplin#899]
### Operating system

- Android

### Application

- Mobile

### Description

Hi,

when editing a note the scroll is not smooth and you can't fast scroll to top or to bottom.
This way, editing a very long note content will be such a boring and long process, just to get to top or bottom (from top) of the note content.

Is it possibile to make the content scroll exactly like it does while in view mode (it also has the scroll bar and will be nice to have it on edit mode too)?

Thanks a lot

**Comment by seth100** [comment]
Hi, any feedback on this? Thanks

**Comment by binarygraka** [comment]
Thanks for this awesome open-source application and your efforts.

I would also really appreciate it, if the scroll speed in edit mode could be the same as in view mode. Thanks.

**Comment by seth100** [comment]
Hi,

I still would like this feature to be implemented. Is it possibile to reopen it?
Thanks
