### ISSUE TITLE
Android UI is misaligned for RTL languages

### ISSUE THREAD

**Issue by alondmnt** [laurent22/joplin#8999]
While helping a friend setup Joplin on their mobile I noticed the following:

<img src="https://github.com/laurent22/joplin/assets/17462125/c200a4d0-6644-4bcd-9d1b-8ccf5d394693" width="30%" />

Left: extra (unneeded) panel space.
Middle: notebook list (too narrow and clipped).
Right: note list (I think that in the expected width).

This is unrelated to Joplin's localization, but rather to the language settings of the Android system.

## Environment

Joplin version: 2.12.3
Platform: Android 13
OS specifics: Xiaomi Note 11 / Galaxy S20

## Steps to reproduce

1. Change the Android display language to a RTL language.
2. Open Joplin.
3. Open the notebook list panel (the button will appear *on the right hand side* instead of the left).

**Comment by personalizedrefrigerator** [comment]
The note actions menu is also shown on the opposite side from the button that opens it:
![screenshot: Note actions menu shown on wrong side](https://github.com/laurent22/joplin/assets/46334387/c7605590-c0c0-45b3-b4fa-4676729059a9)

Similarly, the back arrow should be pointing the other way.

In Joplin, the arrow points to the left, in messages (and perhaps other apps) the arrow points to the right:
![google messaging: Arrow points to edge of screen](https://github.com/laurent22/joplin/assets/46334387/bc61772a-5f0c-4493-8a3b-10c1af53ed77)
![joplin: Arrow points away from edge of screen](https://github.com/laurent22/joplin/assets/46334387/eb4b60e1-b9a3-4a9d-b7c6-4f01826068f8)

**Comment by personalizedrefrigerator** [comment]
> Middle: notebook list (too narrow and clipped).

Upstream bug report: https://github.com/chakrahq/react-native-side-menu/issues/7

**Comment by personalizedrefrigerator** [comment]
Still an issue!

**Comment by personalizedrefrigerator** [comment]
Still an issue. Due to the lack of upstream activity, we may need to fork `react-native-sidemenu-updated` (or the updated version of that package).

**Comment by personalizedrefrigerator** [comment]
Still an issue. Related to https://github.com/laurent22/joplin/issues/9142, as we may also have to fork `react-native-sidemenu-updated` to fix that issue.
