### ISSUE TITLE
Add support for editing notes inside joplin terminal

### ISSUE THREAD

**Issue by haikyuu** [laurent22/joplin#9]
Thanks for the great work on this project. 

Is there a way to edit notes inside joplin? else can you please point me to where to add this in the code so i can make a PR? @laurent22

**Comment by laurent22** [comment]
Hmm, but wouldn't that mean creating a text editor from scratch? Currently it's possible to edit a note in Vim for example by pressing "Enter". Just make sure the editor is configured properly by typing `:config editor vim`

**Comment by haikyuu** [comment]
The point is to permit to quickly edit notes without changing context. Just normal typing, without an editor. Just like when you want to edit the name of a todo
