### ISSUE TITLE
Feature request: tweaking search - search on key-press/key-up

### ISSUE THREAD

**Issue by yafp** [laurent22/joplin#90]
### Operating system

- [x] Windows
- [x] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

---
It's a feature request, please feel free to delete it if you don't like the idea.

Assuming a user has a big amount of notes some minor changes to the search function could help finding notes.

- a permanent visible search-field in the UI (i.e. in the left sidebar above "Notebooks"
- re-running search on each key-press inside the search-field

This change would remove as well the featuring of the searches in the sidebar.

This should cook down the search results easily while typing/searching and feel more like a direct live search.

I guess performance wise it shouldn't be a problem for the desktop clients, but it might be for the mobile ones.

**Comment by laurent22** [comment]
This was implemented

**Comment by yafp** [comment]
yay ... we'll see it in the next release (post v1.0.104) then i guess, right?
