### ISSUE TITLE
[feature request] Update note from file

### ISSUE THREAD

**Issue by vuquangtam** [laurent22/joplin#900]
### Operating system

- Linux

### Application

- Terminal

Hi,

When i update large content note from terminal cli, it has error: "Argument list too long". This error cause by linux kernel limit arg's length. Can we have an option for updating note from file ?

Thanks.

**Comment by foxmask** [comment]
what command do you enter ?

**Comment by vuquangtam** [comment]
@foxmask 
I use this
```
joplin set <id> body <large-content>
```

**Comment by foxmask** [comment]
Try 

   Joplin set XXX body < file_with_large_content

For example

**Comment by vuquangtam** [comment]
@foxmask It still show error: "Argument list too long".

**Comment by foxmask** [comment]
So [ulimit](https://unix.stackexchange.com/questions/45583/argument-list-too-long-how-do-i-deal-with-it-without-changing-my-command#45584) could be a temporary solution.

**Comment by vuquangtam** [comment]
@foxmask Thanks :+1: . But in my case the note content is so large (a book) and it still has this error.

**Comment by foxmask** [comment]
What is the size of that content ? 
Are you able to put that content with joplin destkop ?

**Comment by vuquangtam** [comment]
My note is 238617 characters. I write a plugin for updating note in my editor, so i need update through commandline app.

**Comment by foxmask** [comment]
I even can't make it work with xargs

```
find my_file  -exec cat {} \; | xargs -0 -n1 joplin set ed6ff body
xargs: ligne de paramètres trop longue
find: ‘cat’ a terminé son exécution par le signal 13
```

**Comment by vuquangtam** [comment]
@foxmask I've try many workaround in linux (xargs, parallel, find | xargs) but nothing work :(.

**Comment by foxmask** [comment]
Try with the API and curl for example.
See a post on the [forum](https://discourse.joplin.cozic.net/t/grab-a-page-article-from-web-to-joplin-for-creating-new-notes/149/5).
And the [API page](https://joplin.cozic.net/api/)

**Comment by vuquangtam** [comment]
@foxmask thanks 👍, i will look at it

**Comment by foxmask** [comment]
if your script is in python, i made [joplin-api](https://github.com/foxmask/joplin-api) otherwise the API doc should do the trick :)

**Comment by vuquangtam** [comment]
@foxmask great! I will try it. I wrote script by python 👍
