### ISSUE TITLE
Desktop: issues with placement, name, tooltip and translations for the underline button in Rich Text Editor

### ISSUE THREAD

**Issue by mjourdan** [laurent22/joplin#9005]
Because of the unexpected placement of the button, I thought at first the icon was wrong, then I thought [the translation was wrong](https://github.com/laurent22/joplin/blob/dev/packages/tools/locales/fr_FR.po#L2323), and now I think the issue resides in the [button definition](https://github.com/laurent22/joplin/blob/dev/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/utils/setupToolbarButtons.ts#L23)
- the button location
- the button name
- the english tooltip and consequently, all its translations

![image](https://github.com/laurent22/joplin/assets/5346620/ff5b68bd-b089-46f5-a225-ddb62fbbd211)

## Environment

Joplin 2.13.1 (prod, linux)

Version de Synchro : 3
Version du profil : 43
Trousseau supporté : Non

Révision : cfea26d

Outline: 1.5.10

## Steps to reproduce

1. create new note
2. open rich text editor
3. click the 3 dots

## Describe what you expected to happen

I expected the underline icon to be called '"underline", have "underline" as a tooltip, and be placed right after the italic button.

## Logfile

n/a

**Comment by Daeraxa** [comment]
It isn't called underline because Markdown *doesn't have an underline*. Instead this converts to `<ins>` which is the *insert* tag which is often underlined when presented. Generally this isn't fully compatible with some markdown editors as it is part of an extended spec, hence why it is on a different section of the toolbar (along with `<sup>` and `<sub>`). See https://joplinapp.org/markdown/#markdown-plugins.

**Comment by mjourdan** [comment]
Thanks for the fast reply and clear explanation!

I suppose keeping the button name this way is fine then. Still, nothing in the UI convey the idea the button placement is on purpose, it just looks out of place.

I  believe the button placement and tooltip should match people's expectations. Hiding extended specs features in markdown editor and revealing them in RTE would then probably more effectively convey the idea some features are not supported in both modes.

**Comment by denysonique** [comment]
Maybe instead of `insert` the tooltip could be `<ins>`
