### ISSUE TITLE
Desktop: voice memo (m4a format) embeds are broken

### ISSUE THREAD

**Issue by ericswpark** [laurent22/joplin#9006]
## Environment

Joplin version: 2.12.18
Platform: macOS
OS specifics: macOS 14.0

## Steps to reproduce

1. Attach a voice memo with the m4a extension
2. Watch the embed show up with 0:00 as the length. The embed does not play

## Describe what you expected to happen

The embed is playable

**Comment by laurent22** [comment]
I'm not sure we support this format. Did it ever work?

**Comment by ericswpark** [comment]
I don't ever recall it working, although I'd wager that it shouldn't show up as an embed unless it is playable.

**Comment by laurent22** [comment]
That's a good point - we should investigate if it can be supported and, if not, we should disable the player

**Comment by ericswpark** [comment]
Weird, it's working for some reason. Environment is all same (Joplin same version, macOS on 14.0). My only guess is some underlying library got updated with Homebrew? Should I leave this bug report open? Anybody else verify that it's working on their end?

**Comment by ericswpark** [comment]
Unable to reproduce the issue anymore. Closing
