### ISSUE TITLE
joplin-cli does not return

### ISSUE THREAD

**Issue by jdckr** [laurent22/joplin#901]
### Operating system

- Windows

### Application

- Terminal

Joplin is not returning after executing a command. When I call `joplin help` help is printed but it does not return. Same applies if I try to export my notes, export is done but it does not return. With a clean profile on the other hand the export command prints `Missing required argument: path` and joplin returns.

**Comment by tessus** [comment]
I'm a bit confused.

Are you trying to run the joplin cli application on Windows or are you trying to invoke the Windows application from the terminal?

Also, what's the version and can you please provide a debug log?

**Comment by jdckr** [comment]
I am trying to use Joplin cli on Windows. I installed it using `npm install -g joplin`. I did the Installation two days ago, so should be the most recent version (can't check the version right now). I checked the debug log but didn't see anything besides some info about the masterkey. I will recheck the log and attach it was soon as I am home.

**Comment by tessus** [comment]
Ok, then it should be 1.0.116, which I have both installed on Linux and macOS. Unfortunately I don't have a Windows box to test an install on Windows.
On both of mysystems though, the command prompt returns after running the command.

Maybe this is something Windows specific. Well, maybe the log file tells us a bit more.

**Comment by jdckr** [comment]
Unfortunately the log doesn't tell anything, what it shows is:

> 2018-10-25 21:14:21: "Profile directory: JoplinProfile\"
2018-10-25 21:14:21: "Trying to load 1 master keys..."
2018-10-25 21:14:21: "Loaded master keys: 1"

I used the following command to export:
> joplin --profile JoplinProfile export c:\temp\joplin_export --format md --log-level debug

Inside task manager I can see that the following process is running
> node.exe "C:\Users\digger\AppData\Roaming\npm\\node_modules\joplin\main.js" --profile JoplinProfile export c:\temp\joplin_export --format md --log-level debug
