### ISSUE TITLE
Paste image from web

### ISSUE THREAD

**Issue by EHMilon** [laurent22/joplin#9017]
## Environment

Joplin version: 2.12.3
Platform: Android
OS specifics: Android 

## Steps to reproduce

1. Fix Paste image/attachment to note from web
I need to select multiple lines included image and paste to my note. But when I try to paste it to my note it only paste the text not any image. If I try to paste image from web URL, it not work.
It's very inconvenient.

## Describe what you expected to happen

This app should add image, similar to the other apps (Evernote) does. When I selected and copied text and image, I expected it to be pasted onto my note.

**Comment by BenBlumer** [comment]
I believe the issue is that Joplin Android either doesn't let you paste images at all, or there's something sticky about it. 

For example, when I try to copy a single image from, e.g. Chrome, and then paste in my Joplin note:

1) long pressing in the editor and then clicking paste: nothing happens.
2) from the Google keyboard clipboard, I get "Joplin does not support image pasting here."

It seems currently the only way to get images in is by using the triple dot menu and going to "attach".

It would be very useful, e.g., for dropping screenshots in.

On the code side: Given the markdown-first nature of the app, I guess it would involve detecting that a paste contains an image, uploading that image to Joplin, then inserting it as a markdown ref.

**Comment by BenBlumer** [comment]
Still an issue.

**Comment by BenBlumer** [comment]
Still an issue

**Comment by Wladefant** [comment]
Oh man once again the stupid bot. Yeah, that is really disturbing for me. I want to copy paste paste images. I want to drag and drop images, especially with all the new tablets, and dex modes and so on. @personalizedrefrigerator is it difficult to fix? (just curious, no hidden meaning or something

**Comment by personalizedrefrigerator** [comment]
> Oh man once again the stupid bot. Yeah, that is really disturbing for me. I want to copy paste paste images. I want to drag and drop images, especially with all the new tablets, and dex modes and so on. @personalizedrefrigerator is it difficult to fix? (just curious, no hidden meaning or something

**Drag-and-drop**: Does dragging and dropping into the image editor in Joplin work? If so, it shouldn't be too difficult to implement as we can [listen for `drop` events](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/drop_event) in the editor. If not, it might be difficult :).

**Copy-paste**: This should be very similar to implementing drag-and-drop for images. I think the most difficult part of this would be sending the images from the CodeMirror WebView to ReactNative, then saving them as resources.

Related code that handles this in the desktop app:
- https://github.com/laurent22/joplin/blob/a863f924906d9a7ae94832f0b50a0c6dab803f27/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/CodeMirror.tsx#L135
- https://github.com/laurent22/joplin/blob/a863f924906d9a7ae94832f0b50a0c6dab803f27/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/CodeMirror.tsx#L80
- https://github.com/laurent22/joplin/blob/a863f924906d9a7ae94832f0b50a0c6dab803f27/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/Editor.tsx#L43

Notes:
- In the desktop app, the code editor isn't running in an iframe/WebView, which makes communication with it easier.
- [`fileToBase64`](https://github.com/personalizedrefrigerator/js-draw/blob/800d35917a41539b0bb92b6a7dc4ee44c0653050/packages/js-draw/src/util/fileToBase64Url.ts#L11) in `js-draw` is used to convert an image to a base64 data URL. We could use something similar to this within the `WebView`, send the base64 data to React Native, then save it to a file using the `base64` encoding.
**EDIT**: Web APIs: On my Samsung tablet, [the w3schools drag-and-drop example](https://www.w3schools.com/HTML/html5_draganddrop.asp) doesn't work in Chrome. [It looks like it used to work](https://github.com/Fyrd/caniuse/issues/5042), so this is probably a regression (or related to Samsung tablets?)

**Comment by Wladefant** [comment]
At least on my samsung tablet nothing really works, neither drag and drop nor pasting images from clipboard. I mean I have never seen an app that does not have that funtionality. Shouldnt there be somewhere a default behaviour for that?

EDIT: I take my words back, apparently obsidian does not have that functionality too
