### ISSUE TITLE
Web clipper Bugs 

### ISSUE THREAD

**Issue by EHMilon** [laurent22/joplin#9018]
## Environment

Joplin version: 2.12.3
Platform: Web
OS specifics: Windows 

## Steps to reproduce

Joplin web clipper is so problematic. It doesn't work as I expect. I thought it will work as Evernote Web Clipper, but I am disappointed. It's need lot of enhancement. The web clipper defends on Desktop application. if you want to use this extension you have to run the application in background. If you want to use this extension on an android device (kiwi, Firefox nightly) you can't.
1. Remove web clipper dependency from the application 
2. There are a lot of bug in the extension, fix them. 

## Describe what you expected to happen

Web clipper is very useful for note-taking, while browsing. But when it not work, loading, Bugging it's very frustrating. 
Make this extension like Evernote web clipper. And if the application is not installed in windows, still it should be work and sync across devices.

**Comment by laurent22** [comment]
Ok we'll keep that in mind
