### ISSUE TITLE
Sharing a page from the browser, modify note I was reading

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#902]
### Operating system

- Android 8

### Application

- Mobile

When I use my browser and want to share a link to joplin: 
* if I was on the note list , joplin create a note.
* if I was on a note, joplin edit this one, do not change the title, but replace the content of the body by the grabbed URL

**Comment by CalebJohn** [comment]
You can find additional information about this bug in the [comments](https://github.com/laurent22/joplin/issues/110#issuecomment-422892523) of #110

**Comment by foxmask** [comment]
thanks ! So I can wait for your fix :)
