### ISSUE TITLE
Copy & Paste in Editor inconsistent behavior on Emacs/Vim keyboard mode

### ISSUE THREAD

**Issue by cinsk** [laurent22/joplin#9021]
## Environment

Joplin 2.12.18 (prod, win32 and darwin)
Platform: Windows 11 Version 22H2 and MacOS Ventura 13.5.2
OS specifics: 

## Steps to reproduce

Case 1: (paste short cut does not respect global clipboard)

1. restart Joplin (make sure that you never copy text in Joplin before)
2. [tool]->[option]->[general]->[show advanced settings]
3. change "keyboard mode" to either Emacs.
4. Copy some text from another app.
5. Pressing Emacs paste(yank) shortcut `Control+Y` does not do anything.

Case 2: (copy short cut does not add text to the global clipboard)

2. `[Tool]->[Option]->[General]->[Show advanced settings]`
3. change "keyboard mode" to Emacs.
4. Copy some text Joplin usign Emacs key (select area and press `Alt+W`)
5. Do paste in some other app (e.g. Notepad.exe)

VIM shortcut like `yy` (copy line) and `p` (paste) have the same problem.

## Describe what you expected to happen

With the default setting (keyboard mode: default), copy & paste works with other apps (all apps share the same clipboard).
When the keyboard mode set to either Emacs or Vim, Joplin seems to create its own clipboard which is not shared with other apps.  You can copy text from Joplin editor and paste to Joplin editor, but you cannot copy text from another app paste to Joplin, and you cannot copy text from Joplin and paste to the another app.    This behavior only happens on the keyboard shortcut of Vim and Emacs.
If you click the menu item Copy or Paste, they are working as expected (no dedicate clipboard, but works with the global clipboard).

To be consistent with default keyboard mode, I think Emacs/Vim shortcut for copy&paste should not use Joplin's internal clipboard but uses global one.

**Comment by personalizedrefrigerator** [comment]
See https://github.com/laurent22/joplin/issues/3870

**Comment by personalizedrefrigerator** [comment]
Copy/paste with the `"+` register should be fixed in Vim mode in [v2.13.2](https://github.com/laurent22/joplin/releases/tag/v2.13.2)'s beta editor. 

As [it uses CodeMirror's `emacsStyleKeymap`](https://codemirror.net/docs/ref/#commands.emacsStyleKeymap) for Emacs emulation, rather than a full solution like [`@replit/codemirror-emacs`](https://github.com/replit/codemirror-emacs), its Emacs emulation might be more limited than CodeMirror 5. (I'm not very familiar with Emacs keybindings :) ).
