### ISSUE TITLE
Endless sync with "Delete local data and re-download from sync target"

### ISSUE THREAD

**Issue by ParanoidShiba** [laurent22/joplin#9023]
## Environment

Joplin version: 2.12.8 (prod, win32)
Platform: Windows
OS specifics: Windows 11
Syncing with Joplin Cloud

## Steps to reproduce

1. Start Joplin Desktop. 
2. Disable note history. 
3. Synchronize. 
4. Use Victor plugin to delete all files. This succeeds as expected with "All items have been deleted". 
5. JoplinCloud still has 40MB, so per instructions in [Victor readme](https://github.com/joplin/plugin-victor#if-there-is-still-some-data-left-on-the-sync-target), do Tools -> Options -> Synchronisation -> Delete local data and re-download from sync target. 
6. Endless sync. Waited overnight, about 12 hours. Joplin won't let me cancel, either. Just keeps going. 
7. Forced sync stop by rebooting Windows, started from 1. with same results. 

## Describe what you expected to happen
1. For sync to complete. 
2. If the sync is corrupted, for Victor to delete all resources. 
3. If Victor fails, to allow a fresh restart. 

## Logfile

Victor seems to succeed

![victor](https://github.com/laurent22/joplin/assets/147148192/254c160e-7f61-4f6c-a25a-3b45ce46b2c8)

Cannot cancel. 

![cancelling](https://github.com/laurent22/joplin/assets/147148192/de55dd62-a357-43fe-8d24-e28679618e0a)

Looks like something is wrong with number of items. 

![syncstatus](https://github.com/laurent22/joplin/assets/147148192/d3f5faca-72b1-4e48-8f18-689b85238647)

During endless sync, went through lots of fetched items:  
```
2023-10-06 16:08:57: Synchronizer: "Sync: fetchingTotal: Fetching delta items from sync target"
2023-10-06 16:08:57: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2023-10-06 16:08:57: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2023-10-06 16:08:57: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
```
And went into loop: 
```
2023-10-06 17:34:54: RevisionService: "maintenance: Starting..."
2023-10-06 17:34:54: RevisionService: "maintenance: Service is enabled"
2023-10-06 17:34:54: RevisionService: "collectRevisions: Created revisions for 0 notes"
2023-10-06 17:34:54: RevisionService: "maintenance: Done in 107ms"
2023-10-06 17:44:54: RevisionService: "maintenance: Starting..."
2023-10-06 17:44:54: RevisionService: "maintenance: Service is enabled"
2023-10-06 17:44:54: RevisionService: "collectRevisions: Created revisions for 0 notes"
```

**Comment by laurent22** [comment]
could you post the full log?

**Comment by ParanoidShiba** [comment]
Thanks for checking laurent22, uploading whole log. 

[log.txt] 
(removed link)

**Comment by laurent22** [comment]
Thanks for the log. I don't see anything obviously wrong in there, it just looks like there's a lot to sync so you might just want to let it run overnight for example so that it completes a full sync once. Once that's done, sync operations should be fast again

**Comment by ParanoidShiba** [comment]
Thanks for tackling the log! 
I tried re-installing Joplin and let it do the full sync. So now with only the default "Welcome!" notebook with five notes. 
However, after the sync, I have 10,707 NoteTags and 2,459 Revisions (attached). No other notes. Is this expected? 
![2023-10-08-0943_aftersync](https://github.com/laurent22/joplin/assets/147148192/0208fc7c-66b2-4315-8969-4f018853ef9a)

I then proceeded to install Victor. I recall using v1.0.0, but now is v1.0.1. 
Running Victor does not change the above numbers. I assume this is the reason I continue to have 40MB on Joplin Cloud. Will Victor not delete the NoteTags? 

Adding my log for reference. 
[log-2023-10-08.txt](https://github.com/laurent22/joplin/files/12839595/log-2023-10-08.txt)
(edited the log to remove my email addresses)

**Comment by ParanoidShiba** [comment]
I checked my local database.sqlite, which is 27MB, and it does have 10,707 note_tags and 2,464 revisions. 
It seems that my original "Delete local data and re-download from sync target" is working, and it is Victor that is not deleting all my resources that I would expect. Could Victor clear the note_tags and revisions tables, too? 
Maybe I should close this thread and ask for an update of Victor.

**Comment by ParanoidShiba** [comment]
Thank you laurent22, I'll close this issue as it is not really a Joplin bug, but more of a function request for the Victor plugin.

**Comment by laurent22** [comment]
The latest version of Victor also deletes the revisions which should solve some of these issues

**Comment by ParanoidShiba** [comment]
Yes, thank you so much for that update! Much appreciated. I should have mentioned that Victor v1.0.1 deletes revisions. 
For me, it looked like note_tags take up a majority of the size, so not a big difference. 
Hopefully it will reduce the sync time for other users.
