### ISSUE TITLE
Desktop: Keyboard Shortcut Changes Overwite Prior keymap-desktop.json

### ISSUE THREAD

**Issue by GeekVisit** [laurent22/joplin#9024]
## Environment

Joplin version: 2.12.8 (prod, win32)
Platform: Windows
OS specifics:  Windows 10

## Steps to reproduce

1. Make backup of keymap-desktop.json in your c:\users\[name]\.config\joplin-desktop folder
2. Open Joplin.
3. Select Tools->Options->Keyboard Shortcuts  in Joplin
4.  Create or delete a custom keymapping for one or more actions, e.g.,  search for "Actual Size", delete the current combination, click save. 
5. Open keymap-desktop.json in text editor (notetab++ or similar which can detect changes on disk) and view the 
contents. It should show that the keymapping code set in step 4 above. 
6. Close Joplin.
7. Open Joplin. 
8. Repeat steps 3-4 to change a keyboard mapping for another action.
9. Reload keymap-desktop.json in your editor. It will be overwritten with just the keymapping for the latest keyboard shortcut changes. 
10. To restore settings, restore your keymap-desktop.json from your backup and restart Jopiln.

## Describe what you expected to happen
Additional keymaps should be added to not overwrite contents in keymap-desktop.json

**Comment by CptMeetKat** [comment]
I suspect this may be a duplicate of #8916 (contains workaround) and #5591

Please correct my understanding as required:
1. You changed/added/deleted some shortcuts in the GUI
2. Used `import` to reload a previously exported keymap
3. Verified the state of the keymap by viewing the Joplin keymap file **directly** with a text editor

If this is correct, then it should be noted that the version of Joplin you are using does not save keymaps to file after `import`, and this is why you may find:
> It will be overwritten with just the keymapping for the latest keyboard shortcut changes.

There is a potential fix available (#9128), hopefully it is approved for release.
