### ISSUE TITLE
Setting external editor on Windows requires you to change file path from backslash to forward slash

### ISSUE THREAD

**Issue by MarkQueppet** [laurent22/joplin#906]
### Operating system

- Windows 

### Application

- Desktop

I was struggling to get Joplin to open my notes in emacs on Windows. Turns out I needed to change all the backslashes used in normal Windows filepaths to the unix forward slash and it worked fine. 

So instead of 
```
E:\Dropbox\user\my-TOOLS\Emacs\bin\runemacs.exe
```
Which produces the error message of 
`Error opening note in editor: spawn E:Dropboxusermy-TOOLSEmacsbinrunemacs.exe`

It needed to be
```
E:/Dropbox/user/my-TOOLS/Emacs/bin/runemacs.exe
```
Which worked fine. 

I'm thinking that the backslashes are actually viewed as escape characters due to the error message which could cause some problems for other people. 

Maybe this is super obvious, but being able to use an external editor is one of the killer features of Joplin for me so I figured I'd drop this in here in case anyone else struggles with this. Maybe the documentation should be updated?

**Comment by downpoured** [comment]
Issue does consistently repro for me, yes looks like a backslash escaping issue. I'll see if I can fix this.
