### ISSUE TITLE
Clicking on a link in a PDF file breaks Joplin

### ISSUE THREAD

**Issue by harun27** [laurent22/joplin#9070]
## Environment

Joplin 2.12.18 (prod, win32)
Platform: Windows 10
Revision: a0a4a81

Plugins:
Note Tabs: 1.4.0
Outline: 1.5.9
Rich Markdown: 0.13.2

## Steps to reproduce

1. Create a new note or open an existing one
2. Create a PDF document with a link in it to a website, f.e. with libreoffice or any other program
3. Paste the pdf document in the note
4. In the markdown viewer, you will see the pdf file open up. Just click the link and it will break.

You can use this example pdf file I created:
[Unbenannt 1.pdf](https://github.com/laurent22/joplin/files/12915541/Unbenannt.1.pdf)

## Describe what you expected to happen
- The link should be opened in the browser
- But Joplin breaks. 
- If I open Joplin, the page is opened in joplin as it is a browser and i can't close the page
- I can't even close Joplin through the taskbar, ctrl-q or the icon. You need to execute the process with task manager

**Comment by ArpitShukla3** [comment]
I AM WORKING ON THIS
