### ISSUE TITLE
CodeMirror 6 split code rendering on special characters

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9072]
Using this string:

    `testing_testing; 2*3`

Results in this rendering:

<img width="240" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/b049fa5a-a5fb-46b9-81eb-43057c5f56c3">

While in CM6 it looks like this:

<img width="215" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/fdf7fdd9-bcdb-4d2e-a3a8-3b8785d71016">

Not sure if CM6 allows handling this case. If not, maybe we can use a codeblock without border and without rounded corners, so that the different blocks are not visible?

Also I think the backticks indeed should not be included in the gray rectangle.

**Comment by personalizedrefrigerator** [comment]
Are you using the rich markdown plugin? If so, I think that this might be an issue with the CodeMirror 5 shim.

For me, it looks like this
![single border around all code](https://github.com/laurent22/joplin/assets/46334387/3086f36e-6b53-4634-b715-b1013fbb07a6)

**Comment by laurent22** [comment]
Indeed that was it - it works fine after unselecting "Add additional CSS classes for enhanced customization"
