### ISSUE TITLE
No content rendered after libdrm update

### ISSUE THREAD

**Issue by tdltdc** [laurent22/joplin#9080]
On 2023-10-16 apt upgraded (among others) the following libdrm related packages:
```libdrm-dev:amd64 (2.4.115-1, 2.4.116-1)
libdrm-nouveau2:amd64 (2.4.115-1, 2.4.116-1)
libdrm-common:amd64 (2.4.115-1, 2.4.116-1)
libdrm-amdgpu1:amd64 (2.4.115-1, 2.4.116-1)
libdrm-radeon1:amd64 (2.4.115-1, 2.4.116-1)
libdrm2:amd64 (2.4.115-1, 2.4.116-1)
libdrm-intel1:amd64 (2.4.115-1, 2.4.116-1)
```

After this upgrade, Joplin fails to render its content. Screenshot:

![image](https://github.com/laurent22/joplin/assets/92337702/2d784af9-2b9c-4b4b-834d-85d52a895443)

Related bug reports:
https://github.com/ferdium/ferdium-app/issues/1265#issuecomment-1757053977
https://github.com/laurent22/joplin/issues/8923 (not a duplicate, because I was running Joplin 2.12.18 before the libdrm upgrade)

## Environment
Joplin version: 2.12.18
Platform: Linux
OS specifics: Debian Sid

## Steps to reproduce
1. Run Debian Sid and have current version of Joplin installed
2. Launch and close Joplin
3. Upgrade certain libdrm packages (see above)
4. Launch Joplin again. Content is now not rendered / blank.

## Describe what you expected to happen
Content being rendered.

## Logfile

Couldn't set debug logging due to broken GUI. Here's the start of the output of "./.joplin/Joplin.AppImage".

[appimage_output.txt](https://github.com/laurent22/joplin/files/12927473/appimage_output.txt)

**Comment by tdltdc** [comment]
As suggested in https://github.com/ferdium/ferdium-app/issues/1265#issuecomment-1757053977, running `rm -rf .config/Joplin/GPUCache/` and then starting Joplin again fixes the issue.

**Comment by PaulVanSchayck** [comment]
Flatpak suffers the same. The directory is located (by default) at:
```
~/.var/app/net.cozic.joplin_desktop/config/Joplin/GPUCache/
```

**Comment by TechD123** [comment]
Thanks @PaulVanSchayck, you saved me!

**Comment by tdltdc** [comment]
Bumped into once this in the last couple of days again on Joplin 2.12.19, so this doesn't appear to be solved.
