### ISSUE TITLE
[Joplin web clipper] Import markdown page from github: img tag not surrounded if it is a link

### ISSUE THREAD

**Issue by antoniopaolini** [laurent22/joplin#9081]
Hello, 
I saved a page from github with the Chrome web clipper.
In the original page there's some "button", Discord icon, twitter, reddit., linked with the related page.
In the imported document the start "["is missing. See attached screenshot.

Maybe it depends on the page (it is a Joplin competitor...) :-P
![2023-10-17 12_35_18-Joplin](https://github.com/laurent22/joplin/assets/60228211/59ff7f41-e164-468a-8a12-257b27a15ae5)

## Environment

Joplin 2.12.18 (prod, win32)

ID del Client: 6c64c797f00b410c98d19c8697f4355e
Sinc. versione: 3
Profilo versione: 43
Portachiavi supportato: No

Revisione: a0a4a81

Admonition markdown extension: 1.1.0
bytefield-svg: 1.1.0
Draw.io: 2.2.0
Embed Search: 2.0.0
joplin-excalidraw: 1.3.0
Kity Minder: 1.0.16
Life Calendar: 1.4.1
Markdown table calculations: 1.0.5
Markmap: 1.4.1
Math Mode: 0.6.2
Metis: 0.1.5
Note Tabs: 1.4.0
Outline: 1.5.10
Simple Backup: 1.3.3
Templates: 2.4.0
turnToChart: 1.9.3
Wavedrom: 1.0.0

**Comment by mo-han** [comment]
Please reopen this issue.
This issue is not fully resolved, and I still run into situations on some sites, similar to this issue or exactly the same.

For example, URL：https://bgm.tv/index/44619
There are error codes like this after clipping, more than one, all of which are missing a '[': to the left of '<img':
```markdown
- <img width="78" height="78" src=":/011f0259a97045adbd349a024f01dcf2"/>](https://bgm.tv/subject/208559)
```

I'm not using the latest version, but it's not an old version either:
```
Joplin 3.3.9 (prod, win32)

设备：win32, x64
客户端 ID: ab5a89d18b0d4204a3f989d5fc854e7a
同步版本：3
配置档版本：47
支持的密钥链：是
替代性实例 ID: -

修订：5d0fa75

Backup: 1.4.2
Conflict Resolution: 1.2.3
Freehand Drawing: 3.0.1
Inline tags: 1.3.0
Joplin Batch: 0.2.2
Quick Links: 1.3.2
Rich Markdown: 0.16.0
Search & Replace: 2.2.0
Table Formatter Plugin: 1.2.1
```

**Comment by laurent22** [comment]
Hello, we cannot track bugs on closed issues, so please open a new one and fill up the template
