### ISSUE TITLE
Does Joplin support rendering math expressions that write in html table tag? 

### ISSUE THREAD

**Issue by floating-yuan** [laurent22/joplin#9084]
## Environment

Joplin version: 2.12.18 (prod, darwin)
Platform: macOS
OS specifics: 14.0 (23A344)

## Steps to reproduce

The note content:
```
<table>
	<tr>
		<td> $\frac{1}{2}$ </td>
		<td>$$ \frac{3}{4} $$</td>
	</tr>
</table>

$\frac{1}{2}$
$$ \frac{3}{4} $$

|a|b|
| --- | --- |
| $\frac{1}{2}$ | $$ \frac{3}{4} $$ |
```

The content and rendering result:
<img width="1408" alt="image" src="https://github.com/laurent22/joplin/assets/4819251/88017e41-464a-475f-ad9e-b9f6f4a826c4">

As you can see, In the right red box `$\frac{1}{2}$` redering does not work. I think that redering math formula in a html table  is a very commonly used feature. Since the native table in markdown has some limitations, like table cell merge.  
I really want that joplin can support this feature.

**Comment by personalizedrefrigerator** [comment]
Try something like this:
```
<table>
<tr>
	<th>Test:</th>
<td>

$3+3$

</td>
<td>

$1+1$

</td>
</tr>
</table>
```

Note that the above method does add extra space. I think some markdown processors support attributes on HTML elements like `<div markdown="true">markdown here</div>`. It might make sense for Joplin to support that (if it doesn't already).

**Comment by floating-yuan** [comment]
Thank you @personalizedrefrigerator. The method of adding extra space is working. It's very helpful. And the method of attributes on HTML elements that you mentioned, I have tried it. It doesn't seem to be working in Joplin. Maybe I just don't know how to write it exactly. But this method also seems to be a good way. Hope that Joplin team can read this information. Thanks again.
