### ISSUE TITLE
iOS new device Joplin Cloud sync keeps fetching thousands of notes

### ISSUE THREAD

**Issue by o5t6iaqo7** [laurent22/joplin#9091]
## Environment

Joplin version: 12.12.3
Platform: iOS
OS specifics: 17.0.3

## Steps to reproduce

1. bought new device, transferred data
2. Joplin database empty; deleted app and data
3. downloaded app and set sync to joplin cloud, E2E set up
4. ran synchronise times - took hours all notes seem to be downloaded
5. attachments Manual download
6. Synchronise re-fetches thousands of notes each time I synchronise takes hours

## Describe what you expected to happen

After a full sync Synchronise should take a few seconds at most as it dud on old device

## Logfile
can't save from iOS pressing and holding Log does nothing no Share option, touching shows lig- many thousands of note does not exist fetching

**Comment by laurent22** [comment]
It's most likely because the initial sync didn't actually complete. If you have a lot of data you might want to let it sync overnight, ensuring your device doesn't switch off automatically. Once that's done, subsequent sync operations will be fast

**Comment by o5t6iaqo7** [comment]
I have tried that leaving Joplin app open in foreground overnight. Eventually finushes goes all the way to completion 30,000 sec or more 10,000+ notes. Next manual Synchronise starts all over fetching 1000s of items and saying created items - created count goes up steadily about half that of # fetched - keeps goin! seems to be some kind of loop or error in Joplin Cloud. Total note count same not making duplicates. Happens every time I manually press Synchronise in iOS app - over last few days total before Completed has reduced from 10k+ fetched/created (more items than I have Notes!) and 36k seconds first sync to 1000s yesterday to today 1392 fetched and 560 local created and 332sec each sync but still hundreds. Am not editing or creating more than 1 note across 3 devices between manual sync. Used to sync to completion on 2sec on old phone I'd always do manual sync on iOS otherwise conflict duplicates created.

**Comment by laurent22** [comment]
Would you mind sharing your log in case there's some error that we can fix? https://joplinapp.org/debugging

**Comment by o5t6iaqo7** [comment]
Very busy with work just getting to this -- I tried to obtain a log following directions but in Configuration when I touch-and-hold on the Log button, nothing happens except color of "Log" button changes slightly. If I touch-and-release on the Log button, I get a copy of the Log on screen but the only options at top of screen are back arrow, and at bottom of screen Refresh or Errors Only, no share pop-up. Since I opened this I am now on iOS 17.1,  Joplin 12.12.3 still.

Issue itself is still going on - "creating" >1000 items, fetching >2x this number, each time I open the iOS app and initiate Synchronise, even though at most 2 or 3 notes have changed. iOS app creates about 1/2 the # of items fetched over 300sec to complete. I do let it run through completion on iOS even keeping app in foreground (and background update is enabled in iOS System settings). A side-effect of this functioning is that I get conflicts, I actually only edit a couple of existing notes on a regular basis but sometimes these sync on iOS towards the end of the cycle and so a duplicate note is formed. In the past (prior iOS device) to ensure no conflict I would manually sync, with same general population of notes on Joplin cloud, iOS would only take a few seconds to complete, and then I could be assured no conflicting notes would be created, but I can't wait so long to use the iOS app. On macOS manual Synchronise continues to take at most a second or two to Complete.

**Comment by o5t6iaqo7** [comment]
> Very busy with work just getting to this -- I tried to obtain a log following directions but in Configuration when I touch-and-hold on the Log button, nothing happens except color of "Log" button changes slightly.

Is there any elevated support mechanism / or other support mechanism as I subscribe to Joplin Cloud and this might be an issue with Synchronise between the iOS app and Joplin Cloud?

**Comment by laurent22** [comment]
Sorry there's no solution other than waiting for sync to complete. If you have many items it might take a while so the best is to plug your phone and let it run with the screen on

**Comment by o5t6iaqo7** [comment]
You may not have noticed, I mentioned log button function isn't working - details above - any ideas how to fix this, then I can upload a log so you could see if there is some other issue? I had the same number of items on the old phone and it took about 2sec to sync each time. macOS Joplin also syncs in a second or two.

**Comment by o5t6iaqo7** [comment]
After about 3 weeks of daily use / multiple times a day most days - this finally resolved itself - iOS Joplin Cloud Synchronise is back to 1 or 2sec to complete. Many inadvertent conflicts in the meantime I might need to try a different solution for note taking as I am not sure how I could easily confirm no data has been lost. Markdown notes in files-subfolders rather than within a single large database file might facilitate user-troubleshooting if the glitch with sync is particular notes (very different app than Joplin). Never did figure out why Log file wasn't saving. Closing with this comment.
