### ISSUE TITLE
Requests to HTTP URLs on iOS generate no network traffic (WebDAV and Server)

### ISSUE THREAD

**Issue by devzero** [laurent22/joplin#9097]
## Environment

Joplin version: 12.12.3
Platform: iPhone 13
OS specifics: iOS 17.0.3 

## Steps to reproduce

1.  Fresh installation of Joplin app, stand up either a Docker instance of the Joplin Server or WebDAV (tried nginx and webdav) listening on HTTP (no TLS). Verify that they work with desktop linux client, verify files written to server
2.  Configure synchronization in the iOS client with the http://myserver.local:22300/ with any credentials. 
3.  Press "Check Synchronization Configuration" get error that Network request failed (notice no prompt to allow application access to your local network - it's not even trying).  Observe no network traffic traversing the wireless link on the ports in question using TCPdump on your router.
4. Change the url to begin with "https" instead and it will generate ssl traffic (which will be rejected by the server because it is malformed, and which are observable via tcpdump).

## Describe what you expected to happen
I expected the iOS app to make http requests, much like the desktop clients successfully do.  At first I thought it was one of the WebDAV sync bugs, so I switched to running a local joplin server, but without an https in the URL, no network traffic is even generated.

Logs:

10-19T17:50:25: JoplinServerApi: "curl -v -X POST -H "X-API-MIN-VERSION: 2.6.0" -H "Content-Type: application/json" -H "Content-Length: 55" --data
"{"email":"joplin@logon.pw","password":"******"}' 'http://void.home:22300/api/
sessions'"
10-19T17:50:25: JoplinServerApi: "Code:", "undefined"
10-19T17:50:25: JoplinServerApi: "TypeError: Network request failed TypeError: Network request failed
at anonymous (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-
drdhpweaoeuqjzfaauzuekgfvihb/Build/Intermediates.noindex/ArchiveIntermediates/
Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:11103:33)
at apply (native)
at
anonymous (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-
drdhpweaoeuqjzfaauzuekgfvihb/Build/Intermediates.noindex/Archivelntermediates/
Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:8734:26)
at _call Timer (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin- drdhpweaoeuqjzfaauzuekgfvihb/Build/Intermediates.noindex/ArchiveIntermediates/
Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:8682:17)
at callTimers (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin- drdhpweaoeuqjzfaauzuekgfvihb/Build/Intermediates.noindex/Archivelntermediates/
Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:8829:19)
at apply (native)
at
callFunction (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-
drdhpweaoeuqjzfaauzuekgfvihb/Build/Intermediates.noindex/Archivelntermediates/
Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:1827:36)
at anonymous (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-
drdhpweaoeuqjzfaauzuekgfvihb/Build/Intermediates.noindex/ArchiveIntermediates/
Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:1666:31)
at_guard (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin- drdhpweaoeuqjzfaauzuekgfvihb/Build/Intermediates.noindex/Archivelntermediates/
Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:1778:15)
at callFunctionReturn FlushedQueue (/Users/laurent/Library/Developer/Xcode/
DerivedData/Joplin-drdhpweaoeuqjzfaauzuekgfvihb/Build/Intermediates.noindex/
ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/
main.jsbundle:1665:21)"
10-19T17:50:25: JoplinServerApi: "Could not acquire session:", "undefined", " ", "TypeError: Network request failed TypeError: Network request failed
at anonymous (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-
drdhpweaoeuqjzfaauzuekgfvihb/Build/Intermediates.noindex/Archiveintermediates/
Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:11103:33)
at apply (native)
at anonymous (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-
drdhpweaoeuqjzfaauzuekgfvihb/Build/Intermediates.noindex/Archivelntermediates/
Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:8734:26)
at _callTimer (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin- drdhpweaoeuqjzfaauzuekgfvihb/Build/Intermediates.noindex/ArchiveIntermediates/
Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:8682:17)
at callTimers (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin- drdhpweaoeuqjzfaauzuekgfvihb/Build/Intermediates.noindex/ArchiveIntermediates/
Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:8829:19)
at apply (native)
at callFunction (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-
drdhpweaoeuqjzfaauzuekgfvihb/Build/Intermediates.noindex/ArchiveIntermediates/
Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:1827:36)
at anonymous (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-
drdhpweaoeuqjzfaauzuekgfvihb/Build/Intermediates.noindex/ArchiveIntermediates/
Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:1666:31)
at guard (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin- drdhpweaoeuqjzfaauzuekgfvihb/Build/Intermediates.noindex/ArchiveIntermediates/
Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:1778:15)
at callFunctionReturn FlushedQueue (/Users/laurent/Library/Developer/Xcode/
DerivedData/Joplin-drdhpweaoeuqjzfaauzuekgfvihb/Build/Intermediates.noindex/
ArchiveIntermediates/Joplin/Build ProductsPath/Release-iphoneos/

**Comment by devzero** [comment]
Is there anything I can do to help fix or troubleshoot this more? It’s blocking me from using Joplin

**Comment by JackGruber** [comment]
I'm not sure, but think this is a iOS restriction. You need to use https, http is not allowed from a iOS policy for apps.
