### ISSUE TITLE
Font setting doesn't seem to work

### ISSUE THREAD

**Issue by cybrwshl** [laurent22/joplin#9098]
Since yesterday I'm unable to change the font in Joplin. I'm using 'Cascadia Code' but even if I change it to something else like Comic Sans or Arial the editor text (not the preview) looks the same.
In the dev tools there is no font-family set.

![image](https://github.com/laurent22/joplin/assets/5388891/1c7e60d1-556d-4c34-9fe1-110f557724db)

## Environment
Joplin 2.12.16 (prod, win32)

Client ID: 4709cc0a9d614077abc00cef31db4d78
Sync Version: 3
Profile Version: 43
Keychain Supported: Yes

Revision: 9666ea6

Better Code Blocks: 1.1.0
Rich Markdown: 0.13.3
Space Indenter: 0.2.2

Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Set a font in Settings > Appearance > Editor font family to 'Cascadia Code'
2. Apply
3. Return to notes

## Describe what you expected to happen
Cascadia Code as font family of the markdown editor

**Comment by personalizedrefrigerator** [comment]
Does setting it to "monospace" or "serif" work?
<img width="400" alt="screenshot: editor font box set to monospace" src="https://github.com/laurent22/joplin/assets/46334387/bfd856a6-3cb7-4bd6-8e7b-8a8cab8644f7"/>
<img width="400" alt="screenshot: editor font box set to serif" src="https://github.com/laurent22/joplin/assets/46334387/a8327ece-9a1f-44b3-9053-c81bc3514ba8"/>

These are more general fonts that Electron should show using other fonts.

If the above doesn't work (and if you haven't already tried this :) ) try quitting (File > Quit) and re-opening Joplin.

**Comment by cybrwshl** [comment]
I tried to restart it, but this didn't solve my problem. Today it works just fine. Maybe my reboots did solve this problem.
Anyway thanks for your support!
