### ISSUE TITLE
Feature request: multiple cell types

### ISSUE THREAD

**Issue by LeonardoGentile** [laurent22/joplin#91]
Hello,
thank you very much for your efforts and for giving this application for free to the OS community! 👍 

I've been using for a while a note taking app call quiver http://happenapps.com/ 
This is wonderful for developers because it has different kind of cells (markdown, code formatted, plain text, Latex). 

The problem with this app is that it is locked to OSX systems and development/bug fixing is way too slow.

Would you consider adding these features to your application?
 - different type of cells in order to have different pieces of information in the note completely isolated and well formatted 
 - nested notebooks
 - import from quiver notes

I know it's a lot of work! 😆  I could help you but I wanted to know if you would go in this direction or not

Thanks

**Comment by laurent22** [comment]
It's unlikely that something like cells will be implemented as a complete rewrite of the editor would be necessary, however Joplin already supports something similar to cell, which can be used to add custom content (for instance for Katex which was added recently).
