### ISSUE TITLE
SimpleBackup 1.3.1 no longer works after Joplin update to 2.12.19

### ISSUE THREAD

**Issue by Grydpype** [laurent22/joplin#9111]
Dear all,

after updating to Joplin 2.12.19, the SimpleBackup plugin no longer works. It regularly produces the error:

`error.folderCreation:`

Regards,
kai.

## Environment
Joplin 2.12.19 (prod, linux)

Client ID: 3708fbfebb3646c787c57619e7200257
Sync Version: 3
Profile Version: 43
Keychain Supported: No

Revision: 7081046

Agenda: 3.7.1
Csv Import: 1.0.1
Email Note: 1.2.2
Embed Search: 2.0.0
Emoji: 1.0.4
Ez Table: 1.0.2
Hotfolder: 1.1.0
Inline TODO: 1.7.0
Insert Date: 1.0.1
Journal: 1.1.2
Markdown Table: Sortable: 1.2.2
Note list and sidebar toggle buttons: 1.0.3
Note Tabs: 1.4.0
Persistent Editor Layout: 2.2.0
Rich Markdown: 0.13.3
Simple Backup: 1.3.3
Table Formatter Plugin: 1.2.1
Templates: 2.4.0
## Steps to reproduce

1. choose "Create backup" from the Tools-menu.
2. See error
3. That's it

## Describe what you expected to happen
I would have expected a backup file in the **unchanged** backup directory as has happened until the update of Joplin

## Logfile
**Excerpt from console:**
Uncaught (in promise) Error: ENOENT: no such file or directory, mkdir '/home/kai/.local/share/Cryptomator/mnt/Erasmus/Joplin-Backups/joplin_active_backup_job'
    at Object.mkdirSync (node:fs:1396:3)
    at e.exports.makeDirSync (/home/kai/.config/jo…backup.js:273:35397)
    at Object.d (/home/kai/.config/jo…backup.js:273:38898)
    at t.Backup.<anonymous> (/home/kai/.config/jo…r.backup.js:3:35103)
    at Generator.next (<anonymous>)
    at /home/kai/.config/jo…r.backup.js:3:18312
    at new Promise (<anonymous>)
    at r (/home/kai/.config/jo…r.backup.js:3:18057)
    at t.Backup.createEmptyFolder (/home/kai/.config/jo…r.backup.js:3:34999)
    at t.Backup.<anonymous> (/home/kai/.config/jo…r.backup.js:3:28072)

**Comment by laurent22** [comment]
I cannot replicate this

**Comment by Grydpype** [comment]
Apparently it has something to do with the location of my Backup-Folder configured for SimpleBackup (in .../.local/ ...).
Moving the folder to my home directory fixes it, backup worked perfectly.
So as a workaround I'll move my backup-folder, but for backup- and encryption purposes I would like to stick to my original path.

Regards,
kai.

**Comment by laurent22** [comment]
Isn't it just a permission issue? Maybe you need to give write access to this folder to Joplin?

**Comment by Grydpype** [comment]
Nothing has changed except that I installed Joplin 2.12.19. As I said, it worked perfectly with the previous versions.

I just set up a new folder at the same location with a different name, and it seems to work. So I don't understand what has happened but I will close the issue.
(Just saw it's already been closed ...)
Thanks for your time.

Cheers,
kai.

**Comment by Grydpype** [comment]
> Isn't it just a permission issue? Maybe you need to give write access to this folder to Joplin?

And how exactly would I do that if I get no error messages during the configuration?

**Comment by personalizedrefrigerator** [comment]
> no such file or directory, mkdir '**/home/kai/.local/share/Cryptomator/mnt/Erasmus/Joplin-Backups/joplin_active_backup_job**

The following information may be helpful:
1. Does `/home/kai/.local/share/Cryptomator/mnt/Erasmus/Joplin-Backups/` exist?
2. In a terminal, does running `mkdir /home/kai/.local/share/Cryptomator/mnt/Erasmus/Joplin-Backups/test-directory` work?
    - This should show whether it's possible for any application to create subdirectories in the backup folder.
4. From **Joplin**'s developer tools (Help > Toggle developer tools), does `await fsDriver.stat('/home/kai/.local/share/Cryptomator/mnt/Erasmus/Joplin-Backups/')` [(`stat` implementation)](https://github.com/laurent22/joplin/blob/909776c6665b746cb6c791d2030de9415fe7a9d8/packages/lib/fs-driver-node.ts#L87) produce non-null output?
    - This should show whether Joplin has read access to the backup folder.

**Comment by Grydpype** [comment]
hi @personalizedrefrigerator ,

thanks for the elaboarate feedback. Regarding your questions:

ad (1.) that has been the backup location for the last 8 or so months, ever since I move the Joplin backups into the Cryptomator vault.
ad (2.) now that will be difficult, because, as I noted above, since the definition of a new folder in the vault solved the problem, I moved my backups from the old folder and deleted it. And now recreating it would surely not lead to any useful conclusion.
ad (3.) that exceeds my linux knowhow; I'll have to check that.

But the main thing for me is that the problem no longer exists (and I am obviously the only one who experienced this, otherwise it would have been noted); backup works as it should (checked just now) so that's good enough for me.

Thanks again for your effort,
kai.
