### ISSUE TITLE
if the notebooks can be sorted freely? 

### ISSUE THREAD

**Issue by lizhizilt** [laurent22/joplin#9118]
Hello, I was wondering if the notebooks can be sorted freely? When I drag a notebook, I find that it can be placed on the next level of a notebook, but when I want to place a notebook on the upper level or free sorting, I find that I can't do it, how can I solve it?

**Comment by dpoulton-github** [comment]
To move a notebook back to the top level drag and drop it onto "NOTEBOOKS".

![image](https://github.com/laurent22/joplin/assets/60117449/258d2ba8-ecb7-4234-8a16-272e476aaba7)

**Comment by lizhizilt** [comment]
ok，thanks！！！
