### ISSUE TITLE
FR: exporting notes in JSON

### ISSUE THREAD

**Issue by mrkafk** [laurent22/joplin#912]
The closest alternative is JEX format, but JSON would be better.

**Comment by laurent22** [comment]
Note: it's trivial to export as JSON, simply by duplicating the [RAW export](https://github.com/laurent22/joplin/blob/master/ReactNativeClient/lib/services/InteropService_Exporter_Raw.js) and serializing as JSON instead of Joplin's format.

**Comment by downpoured** [comment]
New to the project, trying out the Hacktoberfest thing. I think I'll look at this.

**Comment by laurent22** [comment]
If you need any help feel free to ask here or on the [forum](https://discourse.joplin.cozic.net/).

**Comment by downpoured** [comment]
Thanks. Submitted a pull request, let me know if there's anything that doesn't match the code style, e.g. eslint etc.

I could add a json importer, too, in another checkin, for symmetry.

**Comment by laurent22** [comment]
Done in #927. Thanks @moltenform!
