### ISSUE TITLE
Joplin onedrive synchronization error

### ISSUE THREAD

**Issue by yiugn** [laurent22/joplin#9126]
## Environment

Joplin version: 2.1
Platform: Windows 10
OS specifics: Windows 10

## Steps to reproduce
I use Joplin synchronization with onedrive. In my office, lots of desktop PC use Joplin with same onedrive synchronization.
However, only 2 PC fails to be synchronized, so those 2 PC is not synchronized in cloud.
There's no problem in internet connection.  

1. Open Joplin
2. Click synchronization button (I use onedrive synchronization)
3. Error meassage shows up in the left bottom 

## Describe what you expected to happen
Error message

Last Error : error : Could not innitizlise
synchroniser : objecthandle is invalid

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

This seems like it might be the same issue as https://github.com/laurent22/joplin/issues/9123. Knowing that this happens on iOS and Windows suggests that this is coming from `onedrive-api.ts` and not from the mobile/desktop filesystem driver implementations.

After this error message is shown, please either attach a log or
1. Open the development tools: 
![screenshot: Help menu, toggle development tools option focused](https://github.com/laurent22/joplin/assets/46334387/fe42e808-13b7-4fb4-bc1c-750650ecdd8f)

2. In the console, look for a message like this: 
![screenshot: right pointing filled triangle: 06:29:32: Synchronizer: Some error here](https://github.com/laurent22/joplin/assets/46334387/39070f35-59e9-4e7d-8cca-07e1efca2738)

3. Click the arrow by the message, then copy and paste its content here: 
![screenshot: down pointing triangle: 06:29:32: Synchronizer: Some error here. Stack trace. Selected.](https://github.com/laurent22/joplin/assets/46334387/b788c695-4773-4d50-9da5-57b30d63f6d1)

The stacktrace/log should help us determine what is happening.

**Comment by viocha** [comment]
I encountered the same issue on my Android device 
![Screenshot_2023-10-25-21-50-02-683_net cozic joplin](https://github.com/laurent22/joplin/assets/66580331/a4fca9a6-fe88-4aa6-a308-c065a0a083c7)
