### ISSUE TITLE
Joplin does not build on Manjaro 22

### ISSUE THREAD

**Issue by Sabin-Gheorghiu** [laurent22/joplin#9127]
## Environment

Joplin version: 2.12.18
Platform: Manjaro Linux 22
OS specifics: None

## Steps to reproduce

1. Try to build package using pacman 
2. fails due to not finding several packages in the NPM registry 

## Describe what you expected to happen

To build and for me to be able to try out Joplin

## LOGFILE
 `Building joplin...
==> Making package: joplin 2.12.18-1 (Tue 24 Oct 2023 13:40:05 BST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found joplin.desktop
  -> Found joplin-desktop.sh
  -> Found joplin.sh
  -> Downloading joplin-2.12.18.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1212k    0 1212k    0     0   749k      0 --:--:--  0:00:01 --:--:-- 1255k
100 3649k    0 3649k    0     0  1288k      0 --:--:--  0:00:02 --:--:-- 1674k
100 3798k    0 3798k    0     0  1046k      0 --:--:--  0:00:03 --:--:-- 1276k
100 7641k    0 7641k    0     0  1655k      0 --:--:--  0:00:04 --:--:-- 1928k
100 9885k    0 9885k    0     0  1738k      0 --:--:--  0:00:05 --:--:-- 1964k
100 13.1M    0 13.1M    0     0  2043k      0 --:--:--  0:00:06 --:--:-- 2461k
100 16.8M    0 16.8M    0     0  2246k      0 --:--:--  0:00:07 --:--:-- 2807k
100 18.9M    0 18.9M    0     0  2237k      0 --:--:--  0:00:08 --:--:-- 3090k
100 19.0M    0 19.0M    0     0  1930k      0 --:--:--  0:00:10 --:--:-- 2159k
100 19.1M    0 19.1M    0     0  1803k      0 --:--:--  0:00:10 --:--:-- 1874k
100 19.8M    0 19.8M    0     0  1734k      0 --:--:--  0:00:11 --:--:-- 1334k
100 22.4M    0 22.4M    0     0  1819k      0 --:--:--  0:00:12 --:--:-- 1155k
100 24.3M    0 24.3M    0     0  1832k      0 --:--:--  0:00:13 --:--:-- 1118k
100 25.3M    0 25.3M    0     0  1759k      0 --:--:--  0:00:14 --:--:-- 1385k
100 25.3M    0 25.3M    0     0  1647k      0 --:--:--  0:00:15 --:--:-- 1303k
100 26.8M    0 26.8M    0     0  1652k      0 --:--:--  0:00:16 --:--:-- 1456k
100 29.1M    0 29.1M    0     0  1691k      0 --:--:--  0:00:17 --:--:-- 1371k
100 30.7M    0 30.7M    0     0  1692k      0 --:--:--  0:00:18 --:--:-- 1308k
100 33.6M    0 33.6M    0     0  1756k      0 --:--:--  0:00:19 --:--:-- 1746k
100 35.3M    0 35.3M    0     0  1741k      0 --:--:--  0:00:20 --:--:-- 2038k
100 35.9M    0 35.9M    0     0  1704k      0 --:--:--  0:00:21 --:--:-- 1875k
100 37.5M    0 37.5M    0     0  1698k      0 --:--:--  0:00:22 --:--:-- 1721k
100 39.1M    0 39.1M    0     0  1698k      0 --:--:--  0:00:23 --:--:-- 1719k
100 41.1M    0 41.1M    0     0  1709k      0 --:--:--  0:00:24 --:--:-- 1527k
100 42.6M    0 42.6M    0     0  1706k      0 --:--:--  0:00:25 --:--:-- 1554k
100 44.3M    0 44.3M    0     0  1681k      0 --:--:--  0:00:27 --:--:-- 1591k
100 44.3M    0 44.3M    0     0  1632k      0 --:--:--  0:00:27 --:--:-- 1349k
100 44.3M    0 44.3M    0     0  1576k      0 --:--:--  0:00:28 --:--:-- 1022k
100 44.4M    0 44.4M    0     0  1504k      0 --:--:--  0:00:30 --:--:--  609k
100 44.4M    0 44.4M    0     0  1487k      0 --:--:--  0:00:30 --:--:--  366k
100 47.1M    0 47.1M    0     0  1526k      0 --:--:--  0:00:31 --:--:--  616k
100 49.6M    0 49.6M    0     0  1534k      0 --:--:--  0:00:33 --:--:-- 1014k
100 49.6M    0 49.6M    0     0  1489k      0 --:--:--  0:00:34 --:--:-- 1014k
100 49.6M    0 49.6M    0     0  1464k      0 --:--:--  0:00:34 --:--:-- 1189k
100 51.3M    0 51.3M    0     0  1476k      0 --:--:--  0:00:35 --:--:-- 1408k
100 56.0M    0 56.0M    0     0  1567k      0 --:--:--  0:00:36 --:--:-- 1823k
100 60.6M    0 60.6M    0     0  1645k      0 --:--:--  0:00:37 --:--:-- 2447k
100 63.5M    0 63.5M    0     0  1671k      0 --:--:--  0:00:38 --:--:-- 2964k
100 63.7M    0 63.7M    0     0  1645k      0 --:--:--  0:00:39 --:--:-- 2910k
100 66.6M    0 66.6M    0     0  1679k      0 --:--:--  0:00:40 --:--:-- 3128k
100 69.7M    0 69.7M    0     0  1714k      0 --:--:--  0:00:41 --:--:-- 2794k
100 72.4M    0 72.4M    0     0  1741k      0 --:--:--  0:00:42 --:--:-- 2477k
100 74.6M    0 74.6M    0     0  1748k      0 --:--:--  0:00:43 --:--:-- 2372k
100 76.2M    0 76.2M    0     0  1748k      0 --:--:--  0:00:44 --:--:-- 2561k
100 78.2M    0 78.2M    0     0  1755k      0 --:--:--  0:00:45 --:--:-- 2376k
100 78.2M    0 78.2M    0     0  1756k      0 --:--:--  0:00:45 --:--:-- 2192k
==> Validating source files with sha256sums...
    joplin.desktop ... Passed
    joplin-desktop.sh ... Passed
    joplin.sh ... Passed
    joplin-2.12.18.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting joplin-2.12.18.tar.gz with bsdtar
==> Starting prepare()...
  -> Yarn cache directory: /var/tmp/pamac-build-santa/joplin/src/yarn-cache
  -> Yarn binary: /var/tmp/pamac-build-santa/joplin/src/joplin-2.12.18/.yarn/releases/yarn-3.3.1.cjs
  -> Disabling husky (git hooks)
  -> Checking Node PATH
  -> Tweaking .yarnrc
  -> Tweaking lerna.json
  -> Deleting app-mobile
==> Starting build()...
  -> Yarn cache directory: /var/tmp/pamac-build-santa/joplin/src/yarn-cache
  -> Installing dependencies through Yarn 3...
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 512ms
➤ YN0000: ┌ Fetch step
➤ YN0000: │ MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
➤ YN0000: │ MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
➤ YN0000: │ MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
➤ YN0000: │ MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
➤ YN0000: │ MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
➤ YN0066: │ typescript@patch:typescript@npm%3A5.0.4#~builtin<compat/typescript>::version=5.0.4&hash=ad5954: Cannot apply hunk #1
➤ YN0066: │ typescript@patch:typescript@npm%3A5.1.3#~builtin<compat/typescript>::version=5.1.3&hash=ad5954: Cannot apply hunk #1
➤ YN0000: └ Completed in 2m 38s
➤ YN0000: ┌ Link step
➤ YN0007: │ root@workspace:. must be built because it never has been before or the last one failed
➤ YN0007: │ keytar@npm:7.9.0 must be built because it never has been before or the last one failed
➤ YN0007: │ sharp@npm:0.32.3 must be built because it never has been before or the last one failed
➤ YN0007: │ sqlite3@npm:5.1.6 [ea905] must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-free@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0007: │ electron@npm:25.8.1 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-common-types@npm:0.2.36 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-common-types@npm:6.1.2 must be built because it never has been before or the last one failed
➤ YN0007: │ @joplin/app-desktop@workspace:packages/app-desktop must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-svg-core@npm:1.2.36 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/free-regular-svg-icons@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/free-solid-svg-icons@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-svg-core@npm:6.1.2 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/free-solid-svg-icons@npm:6.1.2 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 1m 26s
➤ YN0000: Done with warnings in 4m 4s
  -> Building the workspace
➤ YN0000: tests/support/test_notes/yaml/utc.md
➤ YN0000: tests/support/welcome.pdf
➤ YN0000: tests/testUtils.js
➤ YN0000: tests/testUtils.js.map
➤ YN0000: tests/testUtils.ts
➤ YN0000: tools/populateDatabase.js
➤ YN0000: tools/populateDatabase.js.map
➤ YN0000: tools/populateDatabase.ts
➤ YN0000: tsconfig.json
➤ YN0000: Package archive generated in /var/tmp/pamac-build-santa/joplin/src/joplin-2.12.18/packages/app-cli/package.tgz
➤ YN0000: Done in 0s 923ms
  -> Installing package
{
  name: 'joplin',
  packageManager: 'yarn@3.3.1'
}
yarn add v1.22.19
warning package.json: No license field
warning joplin: No license field
[1/4] Resolving packages...
error Couldn't find package "@joplin/lib@~2.12" required by "./package.tgz" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
warning ./package.tgz > tkwidgets > emphasize > highlight.js@9.12.0: Version no longer supported. Upgrade to @latest
warning ./package.tgz > tkwidgets > emphasize > lowlight > highlight.js@9.12.0: Version no longer supported. Upgrade to @latest
warning ./package.tgz > sqlite3 > node-gyp > make-fetch-happen > cacache > @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
Error: Couldn't find package "@joplin/renderer@~2.12" required by "./package.tgz" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@joplin/utils@~2.12" required by "./package.tgz" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "aws-sdk@2.1340.0" required by "./package.tgz" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "compare-version@0.1.2" required by "./package.tgz" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "chalk@4.1.2" required by "./package.tgz" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "fs-extra@11.1.1" required by "./package.tgz" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "html-entities@1.4.0" required by "./package.tgz" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "chalk@^2.1.0" required by "tkwidgets@0.5.27" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "chalk@^1.1.3" required by "emphasize@^1.5.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
==> ERROR: A failure occurred in package_joplin().
    Aborting...
`

**Comment by Sabin-Gheorghiu** [comment]
Just to say re-running the build seems to solve this.

From what I understand (please correct me if my understanding wrong or add more details). It seems NPM dependencies were not correctly added to cache on first run

**Comment by personalizedrefrigerator** [comment]
The Manjaro/ArchLinux build script isn't maintained here — please consider reporting this to its maintainers.

If `pacman` is using the AUR, [this comment might be relevant](https://github.com/laurent22/joplin/issues/9058#issuecomment-1773973952).
