### ISSUE TITLE
Joplin desktop does not accept `--disable-gpu` flag

### ISSUE THREAD

**Issue by orl0** [laurent22/joplin#9130]
**Joplin desktop does not accept Electron `--disable-gpu` flag.**

At some point I encountered GPU rendering errors on Linux with most Electron applications. And while every other application could be started with `--disable-gpu` flag Joplin desktop refused to accept this flag so I couldn't use it anymore.

I guess this flag is important and desktop app should accept it.

## Environment

Joplin version: latest
Platform: all

I've made a patch for myself.

[Git patch](https://gist.github.com/orl0/6a5e8f46acb000fa1cc33a9b4b2434aa)

I can make a PR if you want.

**Comment by personalizedrefrigerator** [comment]
I think a PR for this would be welcome.

**Comment by personalizedrefrigerator** [comment]
Possibly related: https://github.com/laurent22/joplin/issues/9080#issuecomment-1766122432
