### ISSUE TITLE
Android and iOS: glitch in UI

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#914]
### Operating system

- Android
- iOS

### Application

- Mobile

When loading a note the red `add note +` sign is shortly seen in the top right quadrant of the UI.
I have made a small screen recording, since a movie/picture says more than a thousand words...

Unfortunately gh does not allow a video to be uploaded, thus here it is:
https://evermeet.cx/pub/screenshots/sailfishPPR2.181005.003kct10242018214618.mp4

The loading of a note also seems a bit sluggish compared to previous versions of Joplin for Android.

**Comment by foxmask** [comment]
The glitch happens to me too but since a long time, not since the last version.
I'm feeling, it's a lag, that occurs at the opening of the app when it tries to sync/decrypt.

**Comment by tessus** [comment]
Hmm, at that time, everything was synced already. So it must be something else. I have not seen this behaviour with the previous version.

**Comment by tessus** [comment]
If you look closely this is not the only glitch. There's a white line showing up between the Joplin app and the Android notification area.
I have the feeling that there's a problem with rendering somehow and/or an issue with the drawing of GUI components.

**Comment by tessus** [comment]
After installing the latest version on my iPad, I see the same glitch in the UI. But luckily the interface is not behaving as sluggishly as on Android.

**Comment by tessus** [comment]
Maybe this has something to do with the updae of the react-native component.

**Comment by tessus** [comment]
I can also see this "glitch" in the simulator for Android and iOS. Therefore @laurent22 should be able to reproduce this issue. I don't know what other info I could provide.

**Comment by tessus** [comment]
Just wanted to follow up on this @laurent22. Is this a bug with the new react-native component, or is this related to other changes in the Joplin code?

**Comment by tessus** [comment]
This problem is no longer apparent. I think the latest react update fixed it.
