### ISSUE TITLE
Increase the font size for note titles in the note view/edit pane

### ISSUE THREAD

**Issue by dbogdanov** [laurent22/joplin#915]
It will make sense to increase the font size for a note title in the note view/edit pane on the right. 

Right now, the title font size is very small to be visually grasped easily. It is overwhelmed by the size of the text editing icons right below the title. I would rather expect the opposite, small icons and large font for the title (e.g., see Evernote). 

Also, the text title should be larger then the default font size for the note text. 

<img width="660" alt="screen shot 2018-10-25 at 04 38 34" src="https://user-images.githubusercontent.com/409668/47472694-eac9c180-d80f-11e8-8db6-2e5d46408964.png">

### Application
- Desktop

**Comment by edenpc** [comment]
I agree. For an example check out how [inkdrop](https://inkdrop.app/) does it.

**Comment by dbogdanov** [comment]
This looks like a small design issue, but it makes Joplin unusable for me in its current version.

**Comment by foxmask** [comment]
did you see that for mobile version ? https://github.com/laurent22/joplin/pull/1797

**Comment by dbogdanov** [comment]
Font size for note titles is independend 

> did you see that for mobile version ? #1797
> 
> and [#337 (comment)](https://github.com/laurent22/joplin/issues/337#issuecomment-522329146)

Haven't tried that, but this does not address font size for note titles as I understand.  

This is still an issue. The titles can be at least made bold. It looks weird that the H1 headers in a note body are huge compared to the note title.
