### ISSUE TITLE
Import of inter-linked md files (Zim export) crashes notebook structure

### ISSUE THREAD

**Issue by AliceOrBob** [laurent22/joplin#9151]
## Environment

Joplin version: 2.12.9
Platform: Windows
OS specifics: 11

## Steps to reproduce
Precondition (testdata attached)
- Zim Notebook with subpages incl. attachments on subpage
- Journal page with link to subpages
- Export the whole Notebook as single pages to markdown format with Zim --> resulting files attached

1. Import folder of Zim exported markdown files (File > Impoert > "MD - Markdown (Directory)")
2. Check subpage that was linked in previous Journal entry 
--> subpage is not available in its previous structure but in "Journal" Noteboook
--> attachment of the subpage is not available

## Describe what you expected to happen
- Notebook structure is created based on the structure in the Import folder of md files
- Attachments are imported and assigned to their original pages

![Screenshot 2023-10-27 140313](https://github.com/laurent22/joplin/assets/63558020/29ba1c5e-cfe0-4d21-891b-ea9d5a6ba620)
[ZimExport.zip](https://github.com/laurent22/joplin/files/13188675/ZimExport.zip)

**Comment by pedr** [comment]
I don't know what to do with the attached file.

The markdown file never references the PDF, so it gets ignored by the importer. I'm not sure if we should import just because it is inside the import folder @laurent22 

This is the structure of the import folder:
```
├── Journal
│   ├── 2023
│   │   ├── 09
│   │   │   └── 20.md
│   │   ├── 09.md
│   │   ├── 10
│   │   │   └── 27.md
│   │   └── 10.md
│   └── 2023.md
├── Journal.md
├── Page_1
│   ├── Page_1.1.md
│   └── Page_1.2.md
├── Page_1.md
├── Page_2
│   ├── Page_2.1.md
│   ├── Page_2.2
│   │   └── attachment_2.2.pdf
│   └── Page_2.2.md
└── Page_2.md
```

And the content for `Page_2.2md` is

```
# Page 2.2
Created Friday 27 October 2023

Content Page 2.2
```
