### ISSUE TITLE
Message that says "Some items cannot be synchronised" doesn't go away after retrying

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9157]
When resources cannot be downloaded, and after retrying download, and there's no more resources to download, yet that message "Some items cannot be synchronised" doesn't go away.

![image](https://github.com/laurent22/joplin/assets/1285584/f7a58b6c-f264-4e02-a6d2-d754822e90d6)

**Comment by samratghosh291** [comment]
please assign me to this issue. I
 would like to work on it.

**Comment by laurent22** [comment]
We don't participate in GSoC
