### ISSUE TITLE
When items cannot be downloaded, there is no link to retry all items

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9158]
If resources cannot be downloaded, they appear on the status screen with "Retry" link next to each item. However there should also be a link to retry all items, as there is for encryption issues.

Tested on desktop, but may apply to mobile too

**Comment by samratghosh291** [comment]
Please assign me on this issue. I'll try it out.

**Comment by pedr** [comment]
Can you help me reproduce this bug? I'm not sure if I understand the issue, I don't think I ever saw this happen.

**Comment by laurent22** [comment]
It happens if an item cannot be downloaded after multiple attempts. In that case `sync_disabled` is set to `true` and the item will no longer be synced. They will then show in the status screens on both desktop and mobile, and each item will have  "Retry" button. There's a "Retry all" button that was implemented but it doesn't seem to always show up.

You can find the logic in StatusScreen.tsx. Maybe if you sync with Joplin Server, and make it throw an error on purpose, it will make all items unsyncable, and they will appear in that screen. Or you could do that by tweaking the profile database but not sure how.
