### ISSUE TITLE
Fast search broken in mobile

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9159]
If I type "jo", internally it should do a search for "jo*" and return "Joplin", "Joseline", etc. That used to work but was broken recently, probably after the search engine update.

**Comment by personalizedrefrigerator** [comment]
This could also be related to the `db.ftsEnabled` setting (which is enabled on my device). When enabled, the `if` condition is taken here:
https://github.com/laurent22/joplin/blob/c7c86c2b5211b4e089d844388f514e89d87560dd/packages/app-mobile/components/screens/search.tsx#L100-L106

`notes = await SearchEngineUtils.notesForQuery` [takes an `appendWildCards` option](https://github.com/laurent22/joplin/commit/9f14e61aff76fff5db92d6c3a4b3983d1d6f45ea), which defaults to `false`. I suspect that we need to replace
```ts
notes = await SearchEngineUtils.notesForQuery(query, true); 
```
with

```ts
notes = await SearchEngineUtils.notesForQuery(query, true, { appendWildCards: true }); 
```
