### ISSUE TITLE
Syncing error

### ISSUE THREAD

**Issue by TimFGMorgan** [laurent22/joplin#9160]
I'm experiencing a syncing error on the desktop and mobile versions. Syncing apparently completing but data not transferring via the cloud to different devices.

![image](https://github.com/laurent22/joplin/assets/111677696/53bc1dc6-a19e-4403-8bc5-adaeb92f977b)

Can anyone help?

**Comment by akosma** [comment]
According to the [Joplin Status page](https://stats.uptimerobot.com/LpAJ5CNYjE) Joplin Cloud systems are down right now.

**Comment by akosma** [comment]
Issue solved right now.

**Comment by TimFGMorgan** [comment]
Super. Thank you!
