### ISSUE TITLE
Increase size of the search bar

### ISSUE THREAD

**Issue by dbogdanov** [laurent22/joplin#917]
My subjective feeling (and may be other people will agree) is that the search bar feels too narrow. Its width hardly fits three or four long words (e.g., "searching long sentences"). There's more screen real estate that can be taken advantage of. 

### Application
- Desktop

**Comment by ComputingFroggy** [comment]
+1, search bar is really too small on desktop screen

**Comment by gbirke** [comment]
I would still like the search bar to be bigger.

**Comment by SubodhDahal** [comment]
@laurent22 I've made the search bar a bit larger and also added some space before the search bar. The changes are in pull request #1933. Please have a look.
