### ISSUE TITLE
API documentation website is broken

### ISSUE THREAD

**Issue by marph91** [laurent22/joplin#9171]
## Environment

Website

## Steps to reproduce

Go to https://joplinapp.org/help/api/references/rest_api/#post-notes. The documentation looks broken. Specifically the codeblocks with triple backticks.

![Screenshot_20231030_165124](https://github.com/laurent22/joplin/assets/33229141/6bb5e774-8200-4f2c-b963-0182dfe3a4b1)

Likely caused by https://github.com/laurent22/joplin/pull/9132.

**Comment by laurent22** [comment]
Oh well, I had fixed all that, but looks like I've done so on the wrong file and all my changes got overwritten. Thanks for the report, I'll look into it
