### ISSUE TITLE
Editor missing in latest TestFlight and Android beta releases

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#9180]
## Environment

Joplin version: iOS:12.13.3, Android:2.13.5
Platform: Mobile
OS specifics: iOS, Android 13

## Steps to reproduce

1. Click "Edit" on a note

## Describe what you expected to happen

The editor should be visible.

## See also
[Forum post](https://discourse.joplinapp.org/t/mobile-image-editor-beta-image-edits-not-syncing/33403/7)

**Comment by personalizedrefrigerator** [comment]
I haven't been able to reproduce this in development builds from latest `dev` or from 3b98060c27a89c5c60ba08892ab15804d39e9319

**Comment by personalizedrefrigerator** [comment]
A custom release build from 3b98060c2 works for me (Android 13). I suspect that something went wrong during the build.

**Comment by laurent22** [comment]
Hmm, weird, I'm going to rebuild it then and hopefully that will fix it

**Comment by laurent22** [comment]
Is it any better with the latest TestFlight version?

By the way I missed that you had also mentioned the Android release, however it works for me, so not sure about this one

**Comment by personalizedrefrigerator** [comment]
It's now working!
