### ISSUE TITLE
UI is gone

### ISSUE THREAD

**Issue by chatmurai** [laurent22/joplin#9187]
After launching Joplin, the screen is white, then grey or blue and there is no UI. Random bits of UI show up if I fiddle with the the menu items.

## Environment

Joplin version:  2.12.19
Platform: Linux
OS specifics: Debian 12 Bookworm, Gnome 43.6 with Wayland

## Steps to reproduce

1. Launch Joplin
2. UI is gone

## Describe what you expected to happen
The UI is there

I can't provide a log file as the devtools are gone too (the frame is there, but it's mostly black)
![Screenshot from 2023-11-01 14-43-28](https://github.com/laurent22/joplin/assets/1504536/f602681b-29c7-49f4-a9c2-f2484faa070b)

**Comment by KopfKrieg** [comment]
I have the same error on Fedora 38, using Gnome 44.5, running on Wayland.

I can't get any log output using the devtools, but I get the following error (which repeats itself until the application is closed) if started from the terminal:

```
// Vertex SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform float4 sk_RTAdjust;in float2 position;in half4 color;in float2 localCoord;flat out half4 vcolor_S0;noperspective out float2 vlocalCoord_S0;void main() {// Primitive Processor QuadPerEdgeAAGeometryProcessor
vcolor_S0 = color;vlocalCoord_S0 = localCoord;sk_Position = position.xy01;}
// Fragment SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform sampler2D uTextureSampler_0_S0;
flat in half4 vcolor_S0;noperspective in float2 vlocalCoord_S0;void main() {// Stage 0, QuadPerEdgeAAGeometryProcessor
half4 outputColor_S0;outputColor_S0 = vcolor_S0;float2 texCoord;texCoord = vlocalCoord_S0;outputColor_S0 = (blend_modulate(sample(uTextureSampler_0_S0, texCoord), outputColor_S0));const half4 outputCoverage_S0 = half4(1);{ // Xfer Processor: Porter Duff
sk_FragColor = outputColor_S0 * outputCoverage_S0;}}
// Vertex GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
uniform highp vec4 sk_RTAdjust;
in highp vec2 position;
in mediump vec4 color;
in highp vec2 localCoord;
flat out mediump vec4 vcolor_S0;
noperspective out highp vec2 vlocalCoord_S0;
void main() {
    vcolor_S0 = color;
    vlocalCoord_S0 = localCoord;
    gl_Position = vec4(position, 0.0, 1.0);
    gl_Position = vec4(gl_Position.xy * sk_RTAdjust.xz + gl_Position.ww * sk_RTAdjust.yw, 0.0, gl_Position.w);
}

// Fragment GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
out mediump vec4 sk_FragColor;
uniform sampler2D uTextureSampler_0_S0;
flat in mediump vec4 vcolor_S0;
noperspective in highp vec2 vlocalCoord_S0;
void main() {
    mediump vec4 outputColor_S0;
    outputColor_S0 = vcolor_S0;
    highp vec2 texCoord;
    texCoord = vlocalCoord_S0;
    outputColor_S0 = texture(uTextureSampler_0_S0, texCoord, -0.5) * outputColor_S0;
    {
        sk_FragColor = outputColor_S0;
    }
}


Errors:
link failed but did not provide an info log
[42:1101/152443.247917:ERROR:shared_context_state.cc(81)] Skia shader compilation error
```

I also tried to use `--disalbe-gpu` and `--disable-gpu-driver-bug-workarounds`, but unfortunately both flags don't work/aren't recognized :/

**Comment by personalizedrefrigerator** [comment]
See also https://github.com/laurent22/joplin/issues/9080#issuecomment-1766122432

If there's a way to detect this from within Joplin, it might make sense to automate clearing the GPU cache.

**Comment by KopfKrieg** [comment]
Removing the GPUCache solved the issue for me. Thanks!

**Comment by chatmurai** [comment]
Once GPU cache removed, GUI is back.
Note for Flatpak users : GPU cache folder is located here `~/.var/app/net.cozic.joplin_desktop/config/Joplin/GPUCache/`

**Comment by ccoenen** [comment]
There are very similar issues with a lot of electron based programs, apparently stemming from a change in Electron 25?

* https://github.com/flathub/im.riot.Riot/issues/411
* https://github.com/microsoft/vscode/issues/190437
* https://github.com/VSCodium/vscodium/issues/1701
