### ISSUE TITLE
Import a "Raw - Joplin Export Directory" messing links

### ISSUE THREAD

**Issue by andrea-marini** [laurent22/joplin#919]
### Operating system
- Linux

### Application

- Desktop

Logs: Import result:  Object {warnings: Array(0)} /tmp/.mount_JoplinbmRwEt/app/resources/app/app.js:304 Import result:  Object {warnings: Array(0)}

I am trying to import a mediawiki-like wiki into Joplin using the "Raw - Joplin Export Directory" menu in File >>Import of the Joplin desktop application: I created a python script which reads from mediawiki database and writes the markup files inside an export directory as if exported by Joplin.
I thus have many hundreds of .md files in this export directory.
I call the "Raw - Joplin Export Directory" menu and the import works correctly, when I look at the pages in Joplin Desktop however the links between pages are completely messed up (by messed up I mean clicking one link brings to another page).

If I move three incriminated files (whose links were messed up) inside another export directory without the many other .md files, the links between the three are correctly imported, if I move them back among all other files and re-do the import the same three links are messed.

Unfortunately when using the "Raw - Joplin Export Directory" the ids I gave are not kept by Joplin so it's hard to see what link was what between export directory and Joplin Desktop program.
It seems messing however is consistent (always the same pages and always linking to the same wrong pages).

**Comment by foxmask** [comment]
With python when you read the mediawiki database, You can use : 
* the [API](https://joplin.cozic.net/api/) (and specialy the [one](https://github.com/foxmask/joplin-api) I made :) and then do 
```
>>> from joplin_api import JoplinApi
>>> joplin = JoplinApi(token='the token provided by Joplin in the WebClipper menu:P'))
>>> folder_title = 'Default'
>>> folder = joplin.create_folder(folder_title) # to create a folder
>>> # to create a new note
>>> note_title = 'My title'
>>> note_body = '# My Title ## My Subtitle my body'
>>> joplin.create_note(note_title, note_body, folder['id'])
```
* the joplin terminal and run `joplin import /path/to/folder notebook_name`

**Comment by andrea-marini** [comment]
Hi, thank you for your answer, I worked with the API but I'm afraid it misses one crucial feature, when I call:

`joplin_api.create_note(page.title, page.content, notebook_id)`

I cannot pass a previously calculated ID for that note but I am returned an ID created by Joplin at runtime. I thus cannot create interwiki links because I would need at each note creation to replace all instances of that ID in all previously created note urls. I hope it's clear what I mean.

what I would need is something like:

`joplin_api.create_note(page.id, page.title, page.content, notebook_id)`

**Comment by foxmask** [comment]
What is ` page ` ?

**Comment by andrea-marini** [comment]
ok my explanation was poor so let's make it clear.
I have a series of wiki pages in a database (or notes that's just up to naming convention), let's say I have page_1 with id pageid_1, page2 with id pageid_2 etc etc.
Each wiki page just like a Joplin note has an id, a title and a body.
The body of page_1 is made up of wiki markup possibly containing internal links to other pages.

My export/import script scans all wiki pages for links and creates a python dict of wiki links -> joplin links:

`links_dict = {"page_1": "3a3445e6446cd2ba1f6b165533acab20", "pageid_2":"9964695d78136d6f0b42e93db0574f03"}`

the joplin ids are calculated with the function:

```
def get_random_joplin_id(self)
    random_uuid = uuid.uuid4()
    uuid_dehyphenated = random_uuid.hex
    return hashlib.sha256(uuid_dehyphenated.encode('utf-8')).hexdigest()[0:32]
```

it then replaces all links from the body of all pages from the format accepted by the wiki to the format accepted by Joplin, that is

`[[page2|pageid_2]] `

is replaced with

`[page2](:/9964695d78136d6f0b42e93db0574f03)`

it then creates a Joplin note for each page in the wiki, calling:

`joplin_api.create_note(page.title, page.content, notebook_id)`

for the page1 I would for instance call something like:

`joplin_api.create_note("page1", "Hello this is a link to [page2](:/9964695d78136d6f0b42e93db0574f03) hope it works", notebook_id)`

from the example above I hope it's clear that when I'm creating the note for page1 I have not created the note for page2 yet so I must know in advance note2 id in order to create the correct content for note1!

The solution for me would be to have some method like:

`joplin_api.create_note("3a3445e6446cd2ba1f6b165533acab20", "page1", "Hello this is a link to [page2](:/9964695d78136d6f0b42e93db0574f03) which has not been created yet", notebook_id)`

the above create a note for page1 with ID 3a3445e6446cd2ba1f6b165533acab20, which creates a link to a page2 which has not been created yet.
then I would call:

`joplin_api.create_note("9964695d78136d6f0b42e93db0574f03", "page2", "Finally this is page2 !!!!", notebook_id)`

Hope it's clear now what import problem I have :(

**Comment by foxmask** [comment]
I understand but the python lib I provide is just made for using the API as it is designed for. And Joplin itself does not handle page.
So if you want to use it for this usage, you'll need to adapt stuff to make it enter in the  existing boxes

**Comment by foxmask** [comment]
If you want to go furthere create a post in the development forum to exchange on the topic;)
