### ISSUE TITLE
Upgrade js-draw before feature freeze

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9195]
If Renovate doesn't do it

**Comment by laurent22** [comment]
@personalizedrefrigerator, I guess we need to manually upgrade it? It seems Renovate has been slow lately. I had to manually upgrade Electron too.

**Comment by personalizedrefrigerator** [comment]
In that case, I can re-open a version of https://github.com/laurent22/joplin/pull/9120 &mdash; we likely want to customize the about page as well.

**Comment by laurent22** [comment]
Ok let's go with this pull request for now
