### ISSUE TITLE
Cannot sync from command line: SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by d53dave** [laurent22/joplin#92]
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [x] Terminal

```bash
$> node --version
v9.2.1
$> npm --version 
5.5.1
$> joplin version
joplin 0.10.83 (prod)
```

I'm trying to sync from the command line, but after authenticating, my browser (latest Firefox, latest Chrome) redirects to `https://localhost:9967/?code=<omitted>` and shows the following error:

```
An error occurred during a connection to localhost:9967. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG
```

**Comment by laurent22** [comment]
> https://localhost:9967

Normally it should be "http". Do you have something like HTTPS Everywhere enabled?
