### ISSUE TITLE
iCloud Sync iOS

### ISSUE THREAD

**Issue by LifeIsAParadox** [laurent22/joplin#920]
### Operating system

- macOS
- iOS

### Application

- Desktop
- Mobile

It would be great if there is a feature to synchronize the files i uploaded to iCloud with the iOS version.

On the mac version I could synch the file with the option"Directory to synchronise with (absolute path): ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/test.jex"

**Comment by ChristianKniep** [comment]
Any progress or guidance on how to use iCloud on iOS.
