### ISSUE TITLE
No "Ignore TLS errors" in latest Portable Windows app

### ISSUE THREAD

**Issue by klaberte** [laurent22/joplin#9209]
Joplin 2.13.4 (prod, win32)

Client ID: 4fbb021e2e764ec3884474dbcef2be59
Sync Version: 3
Profile Version: 44
Keychain Supported: No

Revision: 66036c2
OS: Windows 10 Work Computer (behind corporate firewall)

## Steps to reproduce

1. Download Portable Windows Joplin app
2. Open portable app JoplinPortable.exe
3. Set up synchronization with personal OneDrive account, sign in, app is authorized without issue
4. Try to sync, will not sync, returns 'reason: unable to get local issuer certificate' (Full error message below)
5. Attempt to turn on "Ignore TLS errors", as was an option in previous versions, but the option does not appear in Tools-Options-Synchronisation (even under Advanced Settings)

{
    "message": "request to https://raw.githubusercontent.com/joplin/plugins/master/manifests.json failed, reason: unable to get local issuer certificate",
    "type": "system",
    "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
    "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

## Describe what you expected to happen
I expected an option to ignore TLS certificate errors under Options-Synchronisation, but it is not available in this application.  I understand the certificate issue, and have previously used end-to-end encryption as a workaround, but that does not appear to be a solution in this version of the app.

**Comment by dpoulton-github** [comment]
I am not a dev just a user but I do not think that this is confined to the latest version of Joplin. From what I can see in the changelog Joplin appears to have never had an "Ignore TLS errors" option for OneDrive (or Dropbox).

According to the Changelog it looks like "Ignore TLS errors" was added as a feature in v1.0.103 (which I guess included Nextcloud & WebDAV). It was then added for Joplin Server in v1.7.4, for Joplin Cloud in v2.1.5, and for S3 in v2.13.2.

> 5. Attempt to turn on "Ignore TLS errors", as was an option in previous versions, ...

I did not find any mention of it ever being an option for OneDrive (or Dropbox).

I then went back as far as Joplin Portable v1.7.11 as a "dip sample" and downloaded it. It wasn't an option for OneDrive or Dropbox back then either (FEB21).

Whether it is *possible* to add this is something I cannot assist with ...
