### ISSUE TITLE
Update module joplin-excalidraw 1.3.0 to 1.4.1

### ISSUE THREAD

**Issue by julienallexandre** [laurent22/joplin#9224]
## Environment

Joplin version: 2.12.19
Platform: MacOS
OS specifics: Sonoma 14.1

## Steps to reproduce

1. Settings > Modules > Search > joplin-excalidraw
2. Install

<img width="426" alt="Capture d’écran 2023-11-06 à 22 20 59" src="https://github.com/laurent22/joplin/assets/58303569/a0e06db6-c4f1-4a9e-abb1-507c9eaefc5d">

## Describe what you expected to happen

The extension icon doesn't appear with version 1.3.0, but with version 1.4.1 it works manually.

**Comment by personalizedrefrigerator** [comment]
See https://github.com/artikell/joplin-excalidraw/issues/6
