### ISSUE TITLE
[bug] Cannot sync to filesystem with "Error: Missing required property: type_: note01

### ISSUE THREAD

**Issue by photonxp** [laurent22/joplin#924]
### Operating system

- Linux

### Application

- Desktop

### Joplin package
1.0.107 - 1.0.114

### Issue type:
bug

### Description:

Relative log content with "--log-level debug" enabled:

Error: Missing required property: type_: note01

some updated content..

id: e7a920pccef0ki165fedxefgc92308u
parent_id: 8949a959b5od428okda0k57b9023do57
created_time: 2018-09-22T10:18:02.791Z
updated_time: 2018-09-22T10:52:42.078Z
is_conflict: 0
latitude: 0.00000000
longitude: 0.00000000
altitude: 0.0000
author: 
source_url: 
is_todo: 0
todo_due: 0
todo_completed: 0
source: joplin-desktop
source_application: net.cozic.joplin-desktop
application_data: 
order: 0
user_created_time: 2018-09-22T10:18:02.791Z
user_updated_time: 2018-09-22T10:52:42.078Z
encryption_cipher_text: 
encryption_applied: 0
encryption_applied: 0
type_: 1

    at Function.unserialize (/tmp/.mount_JoplintIE9X3/app/resources/app/lib/models/BaseItem.js:371:28)
    at Synchronizer.start (/tmp/.mount_JoplintIE9X3/app/resources/app/lib/synchronizer.js:282:39)
    at <anonymous>"
    2018-10-26 21:26:37: "Reducer action", "SYNC_COMPLETED"
    2018-10-26 21:26:37: "Setting up recurrent sync with interval 300"

And I have quite a few notes with type_: 1
$ grep "type_" -r .
> ./ad9836df849340118fe1a4wpa1dceac6.md:type_: 1
> ./087cb72cad4544d496e7e0bfd6f588eb.md:type_: 1
> ./c98fda88361544889e0d3d7c3c1517fe4.md:type_: 1
...

I don't know how "type_: 1" is generated, but I assume this error is part of the reasons why I can't sync the updated content of the notes to the linux filesystem.

**Comment by photonxp** [comment]
Probably a compatibility issue? Because I imported the data with an older terminal client 1.0.116.

**Comment by laurent22** [comment]
Did you manually edit some of these notes on the sync target? It can happen if there's an extra newline at the end of the md file.

**Comment by andrea-marini** [comment]
> Did you manually edit some of these notes on the sync target? It can happen if there's an extra newline at the end of the md file.

I can confirm that a newline or some other special character at the end of the file can cause the above error, only that in my case it was not a newline but some special character inserted by vim.
I had to edit .md files with vim in binary mode in order to avoid inserting hidden characters in the file with the -b option:

`vim -b samplefile.md`

overall I think Joplin should ignore non printable characters in the file because the current approach is quite fragile.

**Comment by laurent22** [comment]
> overall I think Joplin should ignore non printable characters in the file because the current approach is quite fragile.

As mentioned in the FAQ, the sync data is basically a database. I understand it's confusing because the files have a ".md" extension but really they should be seen as binary, non-editable files. I'm planning to add a readme file in the sync target to make this clearer.

**Comment by photonxp** [comment]
@andrea-marini Your diagnosis is correct. There's indeed an extra character or newline at the end of the problematic file. It's easier to see the extra line if open the .md file with sublime editor. Remove the extra line, make "type_: 1" the end of the md file would fix the problem. Now I can sync again.
