### ISSUE TITLE
External resources not synced on file system sync

### ISSUE THREAD

**Issue by e-belair** [laurent22/joplin#9249]
I've set the desktop app my sync to "File system", the target is ~/Drive/Joplin
When I add an external resource to a note like image, xls file ..., this resource is copied in ~/.config/joplin-desktop/resources

So these resources are not synced and I lost them when I installed Joplin on another machine.

For example in this note:
![image](https://github.com/laurent22/joplin/assets/596562/e53745aa-9ee0-4843-9e86-8ee27bb6575b)

I've dropped the two files inside the note body

and they have been stored here:
![image](https://github.com/laurent22/joplin/assets/596562/cf70823d-747e-47a5-90ec-5f3921106870)

## Environment

Joplin version: 
Joplin 2.8.8 (prod, linux) via AppImage

Client ID: 5b1e333b85584da697a7e5b9aa7cec30
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: c2a6a13
Platform: Linux
OS specifics: Ubuntu 22.04.3 LTS

## Steps to reproduce

1. Install the desktop app
2. Set the sync to "File system" and choose a target
3. Create a note and drop an external file inside
4. Locate the file inside ~/.config/joplin-desktop/resources

## Describe what you expected to happen

The external resource should be copied inside the sync target folder.

## Logfile

No need for a log file ... I guess.

**Comment by tomasz1986** [comment]
Please make sure to use an up-to-date version of Joplin. Yours is heavily outdated and there were some issues, e.g. with resources being attached using absolute paths instead of relative ones linking to resources inside Joplin, which have now been fixed.

Also, when it comes to file system sync specifically, all resources are stored inside a folder called `.resource` under your file system sync target path.

**Comment by e-belair** [comment]
I've just installed the last version 2.12.19 (snap) and I can find the .resource under my target path. Seems to work now.

**Comment by e-belair** [comment]
I would like to add that I'm using Synology drive to backup the target folder. Unfotunately, it does not sync hidden folder. So .resource will not be saved.
The solution I've found is to create a folder _resource and create a symlink .resource that target that folder.
```
ln -s _resource .resource
```
![image](https://github.com/laurent22/joplin/assets/596562/3e83b9b9-976b-46cb-a6d3-9f6479632593)

Maybe that could help ...

EDIT:

You can also check the option to sync hidden files/folders in sync settings:
![image](https://github.com/laurent22/joplin/assets/596562/057cd19c-1634-4a77-b2e8-343c0b632257)

**Comment by jvolker** [comment]
@e-belair, thanks a lot for sharing this. I'm really interested in syncing via Synology Drive as well. 

What's your experience so far? Are you syncing or just backing up?
With your modifications, is it stable?
Is it working with other devices like Android and iOS?

Thanks a lot!

**Comment by e-belair** [comment]
I have a good experience with that for years. 
I'm currently syncing my Drive, I've just added a folder that contains Joplin data and settled Joplin like this:
![image](https://github.com/laurent22/joplin/assets/596562/f7f722dc-850b-448d-919e-c237955687f3)

It works very well on my Linux and Windows inside a VM. However, I never tested on Android or IOS. It should be more tricky on mobile.

**Comment by jvolker** [comment]
Thanks so much! I imagine setting up the symlink on mobile is going to be tricky.
