### ISSUE TITLE
Cannot scroll to the bottom of the setting screen

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9259]
The screen doesn't scroll at all:

<img width="567" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/50797fbb-3591-44c3-b6c8-4d8a590cc063">

But somehow it's fine in landscape mode

**Comment by personalizedrefrigerator** [comment]
Adding `flex: 1` to the section list container seems to fix the issue. I'm currently testing on another device to verify this, though.
