### ISSUE TITLE
[feature request] folder chooser for filesystem sync on Andoird

### ISSUE THREAD

**Issue by Wenzel** [laurent22/joplin#926]
### Operating system

- Windows
- macOS
- Linux
- [x] Android
- iOS

### Application

- Desktop
- [x] Mobile
- Terminal

Hi,

I have been using `Joplin` with the filesystem synchronisation so far, to be used with another sync app.

When trying to setup the filesystem sync on Android, I have difficulties to set the right folder, since i have to specify the path manually.
In fact, so far, i havent' been able to set the right path, the application telling me that this path doesn't exist.

![screenshot_20181028-031639](https://user-images.githubusercontent.com/964610/47610527-06c3a200-da60-11e8-8461-08f20f58da51.png)

-> Would it be possible to open a **folder chooser** to let the user select a given folder instead of manually typing the full path to the directory ?

Besides that, it's an amazing app, and it improved my producitivty :) :+1: :100: 

Thanks !

**Comment by Wenzel** [comment]
hi @laurent22 , 

just wanted to know if you had considered this feature, and if implementing it would be rather easy (the task chooser is a simple API call, accessible on all platforms), or complicated (many APIs, platform specific code)

I still can't make use of `Joplin` on Android because of this :/

Thanks !

**Comment by borisrorsvort** [comment]
This would really simplify the setup so much !

**Comment by gibranlp** [comment]
I had the same issue, this feature would be really helpful.

So far i had success with this path try it maybe it works for you too:

/storage/emulated/0/Notes

i created the Notes folder on the root of my phone, the root the file explorer lets me see my phone is not rooted or anything, then just give storage permissions to Joplin and i sync everything with MEGA.

So far so good. 
Thanks guys this is a really cool app.

**Comment by kylejbrk** [comment]
@gibranlp

How did you sync the folder with MEGA?

**Comment by gibranlp** [comment]
@kylejbrk 

I'm usign an app called MegaSync, which syncs some folders from MEGA to the phone locally, it actually downloads the content, i'm using specifically just for Joplin.

i'm using the folder i described above

/storage/emulated/0/Notes

cheers

**Comment by kylejbrk** [comment]
@gibranlp

Im a bit confused.

MegaSync is a desktop app which does as you describe.

The official android Mega app only has a save for offline feature, but I believe that transaction is only one way.

Are you using the official Mega app or something else?

**Comment by gibranlp** [comment]
@kylejbrk

  Yes but is also an App for android.

https://play.google.com/store/apps/details?id=com.ttxapps.megasync&referrer=utm_source%3DMetaCtrlCom%26utm_medium%3Dreferral%26utm_campaign%3DMetaCtrlCom
