### ISSUE TITLE
Add a note on Sync Wizard Screen - "Dropbox/OneDrive throttles connection so the initial synchronisation will be slow"

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9261]
Since we get a lot of support requests about this, we should add a message on the sync wizard screen so that users know what to expect.

**Comment by Daeraxa** [comment]
I suggest it should say "may be slow" rather than "will be" or something else to that effect.

**Comment by laurent22** [comment]
I'm thinking of going for this, how does it sound?

<img width="1203" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/b01a9c01-9d87-4afa-8dcc-b1946c9f28fc">

I prefer that users expect it to be slow and it's not, than the opposite so that's why I left "will be".
