### ISSUE TITLE
`buildInjectedJs` randomly fails with no error during `yarn install`

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9262]
During `yarn install` it can randomly fail but doesn't provide an error message.

If I run `yarn build` separately it seems to work fine but somehow building `svgEditorBundle` is very slow - is that the JS-Draw editor? Maybe it's doing more than it needs to and running out of memory or there's a timeout?

In fact it would be good if possible to make the WebPack output verbose, at least to print errors and warnings (and even infos message if possible)

On macOS, as of commit 37c925dcf208bea8c4375a188d50f87e302b45e5

```
# This file contains the result of Yarn building a package (@joplin/app-mobile@workspace:packages/app-mobile)
# Script name: postinstall

Jetifier is deprecated. Future versions of react-native CLI may not run it by default.
Jetifier found 13384 file(s) to forward-jetify. Using 12 workers...
[12:56:57] Requiring external module ts-node/register
[12:56:59] Using gulpfile ~/src/joplin-2.13/packages/app-mobile/gulpfile.ts
[12:56:59] Starting 'build'...
[12:56:59] Starting 'buildInjectedJs'...
Building bundle: codeMirrorBundle...
Building bundle: svgEditorBundle...
Creating: /Users/laurent/src/joplin-2.13/packages/app-mobile/lib/rnInjectedJs/createJsDrawEditor.bundle.js
[12:57:02] The following tasks did not complete: build, buildInjectedJs
[12:57:02] Did you forget to signal async completion?
```

**Comment by personalizedrefrigerator** [comment]
Both build tasks (the CodeMirror bundle and the js-draw bundle) run asynchronously, so it's possible that this is coming from either. (Printing `Building bundle: ...` does not mean that the previous bundle was built successfully).

I haven't been able to reproduce this locally on Linux (though I'm now doing a full re-build &mdash; `git clean -dXf && yarn install` &mdash; and trying again).

If you have time, please apply this diff
```diff
diff --git a/packages/app-mobile/tools/buildInjectedJs.ts b/packages/app-mobile/tools/buildInjectedJs.ts
index d6da0e204..f2de2b7d3 100644
--- a/packages/app-mobile/tools/buildInjectedJs.ts
+++ b/packages/app-mobile/tools/buildInjectedJs.ts
@@ -128,6 +128,9 @@ class BundledFile {
 			console.info(`Building bundle: ${this.bundleName}...`);
 
 			compiler.run((error, stats) => {
+				// Always output stats, even on success
+				console.log(stats?.toString());
+
 				let failed = this.handleErrors(error, stats);
 
 				// Clean up.
@@ -184,11 +187,10 @@ export async function buildInjectedJS() {
 	await mkdirp(outputDir);
 
 
-	// Build all in parallel
-	await Promise.all(bundledFiles.map(async file => {
-		await file.build();
-		await file.copyToImportableFile();
-	}));
+	for (const bundledFile of bundledFiles) {
+		await bundledFile.build();
+		await bundledFile.copyToImportableFile();
+	}
 
 	await copyJs('webviewLib', `${mobileDir}/../lib/renderers/webviewLib.js`);
 }
```
and post the output.

The above diff runs builds synchronously and logs more verbose output (with the tradeoff that errors might be logged twice).

This does seem like it could somehow be a timeout issue or an issue with `gulp` and asynchronous code &mdash; intentionally introducing a type error *does* seem to log output for me, even without the above diff.

**Comment by laurent22** [comment]
I've tried again and cannot replicate it at the moment, but yes it's a good idea to go back to non-parallel build. Also maybe it would make sense to convert these tasks to proper gulp tasks to get more visibility? At least we'll know which task has failed.

From gulp.ts, you could call `buildInjectedJS()` with some argument so that it builds either CodeMirror or JsDraw (or webviewLib, although this one is less of a problem)

**Comment by personalizedrefrigerator** [comment]
It's also possible that this is related to a corrupted [Webpack cache](https://webpack.js.org/configuration/cache/). In this case, replacing

https://github.com/laurent22/joplin/blob/f3daa7f0e4f771f91a2f273a874c6c1488aef2fb/packages/app-mobile/tools/buildInjectedJs.ts#L77-L79

with `cache: false` may fix the issue.

**Comment by personalizedrefrigerator** [comment]
See https://github.com/laurent22/joplin/pull/9266
