### ISSUE TITLE
ElectronClient sqlite3 breaks nodejs 10+ build.

### ISSUE THREAD

**Issue by iboyperson** [laurent22/joplin#928]
### Operating system
- Linux (Arch Linux)

### Application
- Desktop

The ElectronClient's package.json still requires: "sqlite3": "^3.1.13". This breaks builds on NodeJS 10+. Is there a reason the sqlite3 version for ElectronClient is held back when CliClient requires "sqlite3": "^4.0.1"?

**Comment by wwywong** [comment]
For what it is worth, I just tried building with 4.0.1 and the build seems to complete with no problem. So far the compiled version hasn't crashed. :-)

**Comment by iboyperson** [comment]
latest 1.0.119 release fixed this with a updated sqlite3
