### ISSUE TITLE
Attachment error in notes imported from ENEX to HTML containing PDFs (new)

### ISSUE THREAD

**Issue by fellowweb** [laurent22/joplin#9288]
### Operating system

Windows

### Application version

2.12.19 (prod, win32)

### Desktop: About dialog content

Joplin 2.12.19 (prod, win32)

Client-ID: [removed as I assume it is uniquely identifiable, happy to share if required]
Sync-Version: 3
Profil-Version: 43
Unterstützter Schlüsselbund: Ja

Revision: 7081046

### Current behaviour

1. Exported multiple notes containing embedded PDF attachments from Evernote v6.25.3 on Windows 11.
2. Imported notes from ENEX into Joplin 2.12.19 (prod, win32) using the HTML option.
3. Note note properly imported/ displayed in Joplin (example screenshot below)
4. No action when clicking on the link

![grafik](https://github.com/laurent22/joplin/assets/150602852/cb7ac429-95f1-4d46-9ed9-bd0ad2657408)

### Expected behaviour

Joplin imports note and shows embedded/ inline PDF.

### Logs

[Example ENEX](https://github.com/laurent22/joplin/files/13328324/Lego_Duplo_Family_House.zip) (contains a LEGO building manual as PDF as sole content).

**Comment by personalizedrefrigerator** [comment]
This might be partially fixed in version 2.13.5 &mdash; in that version, clicking links for attached resources seems to work. Previously, links to resources didn't seem to work in HTML notes.

**Comment by fellowweb** [comment]
Thank you for looking into this! I'm starting to work with Joplin and importing the Evernote ENEX notes was the first step. Do you understand that the notes' import WAI, however, the way they're rendered isn't? Or do you understand that already the import went wrong?

(If you understand that the import is fine and the notes imported into Joplin aren't corrupted, I'd already start working with Joplin. Otherwise I'd wait for v2.13.5 or later. Thanks again!)

**Comment by pedr** [comment]
I could not test it on Windows, but the latest version does not have this problem when running on Linux.

**Comment by fellowweb** [comment]
Joplin still claims 2.12.19 (prod, win32) to be the latest version on my device and I don't see any change in behaviour. Is there a way for me to share logs if that's helpful? Also happy to wait for 2.13.
