### ISSUE TITLE
To put a table inside a table destroy the host table !!!

### ISSUE THREAD

**Issue by fanofjop** [laurent22/joplin#9293]
### Operating system

Windows

### Application version

 Windows 10

### Desktop: 
JOPLIN 2.13.5 (issue still there since previous versions of JOPLIN under WINDOWS 7)
### Current behaviour

![image](https://github.com/laurent22/joplin/assets/107914828/83ea3b3b-24a5-43c4-8eb6-a4d5d9fa4432)
![image](https://github.com/laurent22/joplin/assets/107914828/510f0428-4380-45e2-8817-d2bf835bd070)
![image](https://github.com/laurent22/joplin/assets/107914828/4f66e609-36fd-45fd-81b7-5223a119fb7f)
![image](https://github.com/laurent22/joplin/assets/107914828/f70e70a5-f453-4fe0-b50c-31398904d667)
![image](https://github.com/laurent22/joplin/assets/107914828/082d7d40-6728-4002-ad82-c4df5185adad)

So : the first table is destroyed and datas are mixed !

### Expected behaviour

If it's not possible to put a table inside a table it should be great to forbid it !
Thanks

**Comment by laurent22** [comment]
We have a mechanism in place to preserve HTML tables now, but it needs to be applied to tables within tables.
