### ISSUE TITLE
joplin android can't launch camera anymore

### ISSUE THREAD

**Issue by yoshiz44** [laurent22/joplin#9296]
### Operating system

Android

### Joplin version

2.13.5

### Current behaviour

When i write a note, i want to add a Photo, when i choose "take a photo" option it doesn't do anything. I check authorization of joplin app but looks good .
Thank you

### Expected behaviour

The camera should start to take photo

**Comment by laurent22** [comment]
It works for me. From where did you get this version?

**Comment by yoshiz44** [comment]
Thank for your reply. I download the app with droid-ify, using f-droid repo.

13 nov. 2023 17:54:02 Laurent Cozic ***@***.***>:

**Comment by yoshiz44** [comment]
I just delete the app and download the play store version, and it works. The app asked me the camera authorization.
Thank you.
Sorry for my english.

13 nov. 2023 17:54:02 Laurent Cozic ***@***.***>:

**Comment by laurent22** [comment]
Yes as mentioned in the description page, the F-Droid app doesn't have the camera feature

**Comment by yoshiz44** [comment]
Oh, sorry for my mistake...

13 nov. 2023 18:11:13 Laurent Cozic ***@***.***>:
