### ISSUE TITLE
Html Export Missing Links to other Html files

### ISSUE THREAD

**Issue by djsudduth** [laurent22/joplin#9297]
### Operating system

macOS

### Joplin version

2.12.19

### Desktop version info

Joplin 2.12.19 (ventura 13.5.2)

### Current behaviour

1. Created an html directory export of nested folders with notes where many of the notes are linked to each other
2. Folders and notes exported successfully
3. Html exported notes contain links back to Joplin IDs rather than relative paths to the linked html files directly

(This behavior does not happen with Markdown exports)

### Expected behaviour

All of the links within html exports should be URIs linking to the proper html files not back to the Joplin app. Markdown export does this correctly - html does not.

**Comment by personalizedrefrigerator** [comment]
I can reproduce this with Joplin 2.13.9.

Links seem to be external Joplin links. For example,

![screenshot, link in note shown to be joplin://idhere](https://github.com/laurent22/joplin/assets/46334387/2c3aa7dd-8342-4cb9-af81-742dac3d49e2)

This link has HTML
```html
<a data-from-md="" data-resource-id="bea18afe919f4dcca90ca31ace2f7e31" href="joplin://bea18afe919f4dcca90ca31ace2f7e31">Test link</a>
```
