### ISSUE TITLE
Changelog Link Broken

### ISSUE THREAD

**Issue by ScriptInfra** [laurent22/joplin#9299]
### Operating system

macOS

### Joplin version

2.12.19

### Desktop version info

Joplin 2.12.19 (prod, darwin)

Client ID: b5ba655ddd2c4ca8886b8b3cec534baf
Sync Version: 3
Profile Version: 43
Keychain Supported: Yes

Revision: 7081046

### Current behaviour

1. Select Joplin > Check for Updates > Full changelog
2. The following links loads: https://joplinapp.org/changelog/
3. Note the changelog does not load.

### Expected behaviour

I suspect the following link should load: https://joplinapp.org/help/about/changelog/desktop

**Comment by personalizedrefrigerator** [comment]
[It should be possible to customize the 404 error page](https://github.com/facebook/docusaurus/discussions/6030). It might make sense to have it include a script that redirects from outdated URLs to the new URLs.

**Comment by laurent22** [comment]
Thanks for the report, that will be fixed from 2.13
