### ISSUE TITLE
Theme support for desktop apps

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#93]
The mobile app can be customised easily by adding the CSS to [global-style.js](https://github.com/laurent22/joplin/blob/04a64368c0207b68c91a5adb991f8730fa385965/ReactNativeClient/lib/components/global-style.js) and tweaking the logic of the `themeStyle()` function.

The theme ID then needs to be added to [setting.js](https://github.com/laurent22/joplin/blob/master/ReactNativeClient/lib/models/setting.js), and the theme will be available to the application.

The Amoled theme for instance would be nice to have:

![unnamed](https://user-images.githubusercontent.com/1285584/33909925-0eb36300-df85-11e7-8509-60666e69d7cb.png)

**Comment by martinpengellyphillips** [comment]
I'd like to get involved with the development of Joplin by having a go at this.

Any pointers on what I need to do to set myself up for developing Joplin (I'm on Windows 10)?

**Comment by martinpengellyphillips** [comment]
Okay, got myself setup now. Some notes:

* Had to `npm install --global windows-build-tools` for `node-gyp` to work.

* Had to change `electron-updater` dependency in `package.json` to `^2.18.2`. Otherwise, `yarn dist` would fail with:
```console
yarn run v1.3.2
$ node_modules/.bin/electron-builder
  • electron-builder version=19.52.1
  • loaded configuration file=package.json ("build" field)
Error: At least electron-updater 2.18.2 is required by current electron-builder version. Please set electron-updater version to "^2.18.2"
```

* Had to run `yarn dist` at least once before trying `.\node_modules\.bin\electron . --env dev --log-level debug --open-dev-tools` as otherwise `sqlite3` would not be found.

**Comment by laurent22** [comment]
Thanks for the feedback, I will add some of this to BUILD.md.

This issue was mainly for the mobile app, which has already themes setup. The Electron app in theory also supports theme but since only one theme has ever been used (the "Light" one), there are probably some more tweaks required to get it to work properly.

**Comment by martinpengellyphillips** [comment]
Cool - I'll have a play around with theming of the desktop application in general then.

**Comment by Munchotaur** [comment]
If you want a hand testing dark themes etc, please let me know. I love Joplin but it's hurting my eyes :smiley:

**Comment by laurent22** [comment]
Right, thanks, I've renamed it.

**Comment by BramVer** [comment]
Are there any updates on this?  
The dark theme already exists on mobile, so it doesn't seem like too much of a hassle to port those settings to desktop (although I am assuming this is a hybrid app).

I'd be happy to chip in if someone points me in the right direction, the light theme being the only one available is hurting my eyes :)
