### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by nitanmarcel** [laurent22/joplin#9314]
### Operating system

Linux

### Joplin version

master

### Current behaviour

As reported in the issue bellow is in not possible to use a database like CockroachDB with the `pg` client, or at least without a database version specified ( I think ).

https://github.com/knex/knex/issues/1477

**Comment by nitanmarcel** [comment]
String connections seem to problematic too, I can't get out of the following error: `Could not connect. Will try again. Cannot read properties of undefined (reading 'name')`

**Comment by laurent22** [comment]
This is not a bug, it's simply not supported. At the moment we don't plan to add support for other DBMS

**Comment by nitanmarcel** [comment]
> This is not a bug, it's simply not supported. At the moment we don't plan to add support for other DBMS

Aren't they still postgres databases btw?
