### ISSUE TITLE
Donation link in readme 404s

### ISSUE THREAD

**Issue by url00** [laurent22/joplin#9323]
### Operating system

Windows

### Joplin version

dev

### Desktop version info

I wanted to donate to the project, so I clicked the donate link on GitHub: https://github.com/laurent22/joplin/blob/dev/readme/about/donate.md

... which currently goes to a 404 page. I was able to then find the Patreon but this should probably be fixed.

### Current behaviour

Donate link is broken, 404s.

### Expected behaviour

Take me to where ever I should give money to.

**Comment by laurent22** [comment]
Where did you find this link?

**Comment by personalizedrefrigerator** [comment]
> Where did you find this link?

https://github.com/laurent22/joplin/blob/062d0898a02c977ccac58976dd82e3d1b6f15a4c/README.md?plain=1#L29

**Comment by lalitkumawat1m** [comment]
I am willing to work on this issue please assign it to me

**Comment by laurent22** [comment]
It should be fixed now, thanks for reporting this!
