### ISSUE TITLE
Mobile: New note button no longer visible in "all notes" on startup

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#9328]
### Operating system

iOS

### Joplin version

12.13.5

### Current behaviour

Steps to reproduce:
1. Open the "all notes" section.
2. Close the app
3. Re-open the app

After step 3, the "new note" button is not visible, "all notes" is open.  On 12.12.3 (iOS), the "new note" button is visible and the "welcome" notebook is open.

**Edited**: Added that the app needs to be restarted.

### Expected behaviour

The "new note/todo" floating action button should be visible.

### See also

https://discourse.joplinapp.org/t/cannot-create-new-notes-in-2-13-6/33708

**Comment by electricmessiah** [comment]
This is happening to me on iOS. Updated the iOS app two days ago. Desktop was a forced upgrade with notice about sync.
