### ISSUE TITLE
Attach menu hidden behind keyboard on iOS 

### ISSUE THREAD

**Issue by davidearl** [laurent22/joplin#9342]
### Operating system

iOS

### Joplin version

12.12.3

### Current behaviour

this is on an iPhone 13 mini iOS 17.1.1.

Open note, or start a new note.
Tap the edit button
Position the cursor where an attachment is wanted
Tap the three dots menu top right, then “Attach…”

The menu comes up behind the keyboard, so it is not possible to select anything other than the first item from it, and that one only just

![image](https://github.com/laurent22/joplin/assets/1050651/58862c7c-7d6a-469f-8afe-91ad1862f823)

### Expected behaviour

Opening the attach menu should also dismiss the keyboard.

**Comment by personalizedrefrigerator** [comment]
This should be fixed in the beta version! See [this commit](https://github.com/laurent22/joplin/commit/bb5befc8bf48da681f34c853a3e934ce59ee2978) and [the associated issue](https://github.com/laurent22/joplin/issues/8774).

**Comment by personalizedrefrigerator** [comment]
This should be fixed in v12.13.10 (tested on December 21). Please comment and/or re-open the issue if you're still experiencing this.

**Comment by davidearl** [comment]
Looks good. Thank you very much.
