### ISSUE TITLE
"Show completed to-dos" has no effect until I click on "Reverse sort order"

### ISSUE THREAD

**Issue by ferrum** [laurent22/joplin#9361]
### Operating system

Android

### Joplin version

2.13.7

### Current behaviour

If I have a notebook with some "activities" and want to show or hide the completed ones, I click on `Sort -> Show completed to-dos` it has no effect, until I press on "Reverse sort order"

### Expected behaviour

Completed to-dos show or hide regardless on the click on "reverse sort order"

**Comment by laurent22** [comment]
Fixed in 24ed5bda636ffa16dafcc6deb49fac895b6a8389
