### ISSUE TITLE
Drawing cannot be edited

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9375]
### Operating system

Android

### Joplin version

2.13.7

### Current behaviour

- Create the attached drawing
- Save

=> It cannot be edited. No edit button shows up and the drawing is not displayed in the note either

I think what I may have done differently in this case is that I zoomed out.

It also doesn't show up on desktop.

[Dessin a garder.jex.zip](https://github.com/laurent22/joplin/files/13464908/Dessin.a.garder.jex.zip)

**Comment by personalizedrefrigerator** [comment]
The drawing seems to be empty:
```svg
<svg viewBox="0 0 50 50" width="50" height="50" version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg" class="js-draw--autoresize"><style id="js-draw-style-sheet">path{stroke-linecap:round;stroke-linejoin:round;}text{white-space:pre;}</style><path d="M50,50L50,0L0,0L0,50L50,50" fill="#ffffff" class="js-draw-image-background"></path></svg>
```

Possible issues:
- The drawing didn't sync correctly (the complete drawing is only present on the mobile device)
    - **Edit**: In that case, an "edit" button should show up on mobile. (With the js-draw plugin, an "Edit" button shows up for me on desktop).
- There was an error while saving (e.g. the initial drawing was saved, but none of the edits were)
- "Cancel" was pressed &mdash; it seems that creating a new drawing, pressing "Close", then "Discard changes" causes an empty image to be attached to the note.
    - If this isn't the issue, I can create a separate bug report.

A log or part of one might be helpful here &mdash; it should contain statements like
- `screens/Note: Saving drawing to resource some-resource-id-here`
- `ImageEditor: WebView error: Some error here`
- `ImageEditor/autosave: Auto-saving drawing to some-path-here`.

**Comment by laurent22** [comment]
I can't see anything in the log, just this, and no errors:

```
11-22T16:52:46: screens/Note: "Saving drawing to resource", "4b716dd989d945df8a52031ea251ac10"
11-22T16:52:46: screens/Note: "Saved new drawing to", "/data/user/0/net.cozic.joplin/files/saved-drawing.joplin.svg"
```

So yes, I assume I was distracted and pressed "Discard changes" when I wanted to press "Save changes". At least I cannot replicate the bug anymore so I think it's all good.

I'm wondering though, would it make sense to delete the image if all changes were discarded?

**Comment by laurent22** [comment]
I've created this related issue: https://github.com/laurent22/joplin/issues/9377
