### ISSUE TITLE
Sidebar is not dismissed when creating a note

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9376]
### Operating system

Android

### Joplin version

2.13.7

### Current behaviour

- Open the sidebar
- Create a note

=> The sidebar is not automatically dismissed.

I'm not sure how it used to work - either the "New note" button should be hidden, or the sidebar should be automatically dismissed.

**Comment by nikkuAg** [comment]
Is this issue still open? I would like to work on it.

**Comment by laurent22** [comment]
We don't participate in GSoC
