### ISSUE TITLE
JS-Draw images that are empty are invisible in light theme

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9377]
### Operating system

Android

### Joplin version

2.13.7

### Current behaviour

- Create an image
- Discard all changes

=> An empty white image is created. If the light theme is being used it's not possible to see that there's a drawing in the preview

**Comment by personalizedrefrigerator** [comment]
> I'm wondering though, would it make sense to delete the image if all changes were discarded?

I think this makes more sense than creating an invisible image :).

**Comment by nikkuAg** [comment]
Is this issue still open? I would like to work on this

**Comment by laurent22** [comment]
> Is this issue still open? I would like to work on this

We don't participate in GSoC
