### ISSUE TITLE
Joplin shows blank screen - only menu showing

### ISSUE THREAD

**Issue by aquada** [laurent22/joplin#9381]
### Operating system

Linux

### Joplin version

2.12.18

### Desktop version info

Joplin 2.12.18 (prod, linux)

Client ID: f29a49ca70d34c0bb06a3073b8ecd290
Sync Version: 3
Profile Version: 43
Keychain Supported: No

Revision: a0a4a81

Csv Import: 1.0.1
JSheets: 1.1.3
Kanban: 1.0.7
Math Mode: 0.6.2
MultiMarkdown Table Tools: 1.1.0
Search & Replace: 2.2.0
Simple Backup: 1.3.3
Templates: 2.4.0

### Current behaviour

1. After upgrading I only see a blank screen on launching Joplin. The menu is there, but the rest is blank. 

![image](https://github.com/laurent22/joplin/assets/5299994/7c4e426f-6112-4817-90be-ea676202a4ef)

2. Functions the same it would seem, I click on reset app layout and I can partly see a dialog as in a ghost of a button and and x to close a dialog. 

This is running NixOS

### Expected behaviour

Expected to see normal screen

### Logs

[log.txt](https://github.com/laurent22/joplin/files/13466367/log.txt)
[startinterminal.txt](https://github.com/laurent22/joplin/files/13466369/startinterminal.txt)

**Comment by laurent22** [comment]
Is there anything in the console?  https://joplinapp.org/help/apps/debugging

**Comment by aquada** [comment]
I've included a terminal log if that helps, but console not showing.

26 Nov 2023 11:47:30 Laurent Cozic ***@***.***>:

**Comment by laurent22** [comment]
Even this doesn't work?

> open Help > Toggle Development Tools or View > Toggle Development Tools in the menu

**Comment by aquada** [comment]
> Even this doesn't work?
> 
> > open Help > Toggle Development Tools or View > Toggle Development Tools in the menu


All I get are some artefacts on the screen
![image](https://github.com/laurent22/joplin/assets/5299994/f6898e25-c853-4828-92ed-32ac0496d000)

**Comment by aquada** [comment]
I've installed 2.12.19 from flathub and this is working. Please let me know if I can help anymore. I still have the NixOS package installed. Maybe it's the Nix package that has a problem?

**Comment by 1447262390** [comment]
I also had this problem, when I was using it, the screen suddenly turned blank, I opened the taskbar and noticed that a lot of joplin processes appeared, I ended all the processes and then opened it again and it returned to normal, my current version is as follows
![image](https://github.com/laurent22/joplin/assets/51668733/8253d490-c5fc-41c5-ab93-f4d5fb029059)

**Comment by JackGruber** [comment]
possible workaround on linux: https://github.com/laurent22/joplin/issues/8923#issuecomment-1807178695 ?

**Comment by aquada** [comment]
> possible workaround on linux: [#8923 (comment)](https://github.com/laurent22/joplin/issues/8923#issuecomment-1807178695) ?

Works for me, thank you
