### ISSUE TITLE
LaTeX Rendering Issue with Inline Text

### ISSUE THREAD

**Issue by KarthiDreamr** [laurent22/joplin#9385]
### Operating system

Linux

### Joplin version

2.12.19

### Current behaviour

When I include LaTeX formulas in a line of text with other characters (like a full stop or the word 'and'), the formula doesn't render correctly. It only renders properly when the LaTeX formula is on a line by itself.
For example, the following does not render correctly:

``` This is a test $$F(z) = \frac{2z}{2z-1}$$ ``` 

This is a test $$F(z) = \frac{2z}{2z-1}$$ 

However, if I put the formula on its own line, it renders correctly:

```This is a test```
```$$F(z) = \frac{2z}{2z-1}$$```

This is a test
$$F(z) = \frac{2z}{2z-1}$$

### Expected behaviour

I expect Joplin to correctly render LaTeX formulas regardless of their placement within a line of text. The presence of other characters on the same line should not affect the rendering of the formula.

### Steps to reproduce
- Open a new note in Joplin.
- Type a line of text that includes a LaTeX formula and other characters (e.g., This is a test $$F(z) = \frac{2z}{2z-1}$$
- Notice that the formula does not render correctly.
- Move the formula to its own line and notice that it now renders correctly.

**Comment by personalizedrefrigerator** [comment]
Does the following markdown render correctly?

```md
# $\KaTeX$ test

This is a $\texttt{test}$ of inline $\KaTeX$.

$$ \texttt{block }\KaTeX $$
```

Rendering on Ubuntu 23.10, Joplin 2.12.19:
![screenshot: working inline and block math](https://github.com/laurent22/joplin/assets/46334387/9ec2251e-1946-4a31-9ad0-ab3b5e33dbc5)

If you use plugins, try disabling them and restarting Joplin.

**Comment by KarthiDreamr** [comment]
the code  you gave works fine. $$ causes the problem when other texts are nearby

``` $$ \texttt{block }\KaTeX $$ test```

![image](https://github.com/laurent22/joplin/assets/84800257/9f22bc1c-baba-458e-9214-1a6167bc3230)

**Comment by personalizedrefrigerator** [comment]
`$$` may need to be either at the beginning or end of a line.

See https://joplinapp.org/help/apps/markdown#math-notation

**Comment by KarthiDreamr** [comment]
Thank you so much for your clarification
