### ISSUE TITLE
Feature Request: Font Settings in the Mac Desktop

### ISSUE THREAD

**Issue by inteltao** [laurent22/joplin#94]
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---
I wonder if it's possible to change the font and font size for the note content in the Mac Desktop application? Currently there is no such options in the app. Thanks

**Comment by breisfeld** [comment]
I have the same question with regard to the Windows desktop.  Thanks.

**Comment by laurent22** [comment]
Font size can now be changed in the settings.
