### ISSUE TITLE
Error: Got metadata for path but could not fetch content: xxxx.md

### ISSUE THREAD

**Issue by lverissimo** [laurent22/joplin#940]
### Operating system

- Linux

### Application

- Desktop

Hello, While trying to sync I am getting the following error, what should I do?

Error: Got metadata for path but could not fetch content: xxxx.md

**Comment by vascowhite** [comment]
### Operating system



- Linux

### Application



- Desktop


Same problem here. I'm sure there must be a simple fix.

**Comment by laurent22** [comment]
Would need full error log.

**Comment by vascowhite** [comment]
Was just getting one :)

[log1.txt](https://github.com/laurent22/joplin/files/2952323/log1.txt)

**Comment by vascowhite** [comment]
I fixed this by deleting `.config/joplin-desktop` and syncing with my server again. However, that seems a bit drastic and may lead to loss of local work.
