### ISSUE TITLE
Only quarter of selected screenshot is pasted/snapped into note

### ISSUE THREAD

**Issue by theerror** [laurent22/joplin#942]
### Operating system
- macOS

### Application
- Desktop

When I use "Clip screenshot" in web clipper, it clips only part of page, not whole I selected. 

See printscreen of this bug report, where I selecting whole visible site:

![a40f342d80d549a28aada5002583d964](https://user-images.githubusercontent.com/4508328/47859349-6dddaf80-ddee-11e8-8db6-a6a5f7a4519c.jpg)

Why only the quarter is captured???

**Comment by theerror** [comment]
i just noticed, that it really do not meet the place, I'm trying to clip neither. It's moved a lot to the left site. (selecting "new issue" button will clip "Issues" and "Pull requests" tabs

**Comment by laurent22** [comment]
Was the page zoomed in the browser?

**Comment by theerror** [comment]
Nope. And it's related only to Chrome / Vivaldy. In FF it's working quite fine.

**Comment by laurent22** [comment]
This is a bug in Chrome that cannot currently be worked around.
