### ISSUE TITLE
Use of internal md-link causes override/disregard of userstyle.css

### ISSUE THREAD

**Issue by Grydpype** [laurent22/joplin#9434]
### Operating system

Linux

### Joplin version

2.12.19

### Desktop version info

Joplin 2.12.19 (prod, linux)

Client ID: 3708fbfebb3646c787c57619e7200257
Sync Version: 3
Profile Version: 43
Keychain Supported: No

Revision: 7081046

Agenda: 3.7.1
Email Note: 1.2.2
Embed Search: 2.0.0
Emoji: 1.0.4
Ez Table: 1.0.2
Hotfolder: 1.1.0
Insert Date: 1.0.1
Journal: 1.1.2
Markdown Table: Sortable: 1.2.2
Note list and sidebar toggle buttons: 1.0.3
Note overview: 1.6.0
Note Tabs: 1.4.0
Persistent Editor Layout: 2.2.0
Reset Checkboxes: 1.0.1
Rich Markdown: 0.13.3
Simple Backup: 1.3.3
Table Formatter Plugin: 1.2.1
Templates: 2.4.0

### Current behaviour

My userstyle.css modifies the colour of the hifghlighted text like so:

> mark {
>     /* sets the background and font colour of user highlighted text (==mark==) */
>      background-color: #9933FF;
>      color: white;
> }

This works perfectly, until I click on a markdown-link in the note. Joplin then opens the linked target note, and after returning to/reopening the original source note, the colour of the highlighted text has reverted to the default orange/yellow.

### Expected behaviour

I would expect the colour of the highlightet text to stay as defined in the userstyle.css.

**Comment by tomasz1986** [comment]
What if you use `!important`, e.g.

``` css
mark {
/* sets the background and font colour of user highlighted text (==mark==) */
background-color: #9933FF !important;
color: white !important;
}
```

?

**Comment by Grydpype** [comment]
Perfect; that fixed it. Thank you very much,

kai.
