### ISSUE TITLE
Link is lost when pasting a text with link (on WYSIWYG)

### ISSUE THREAD

**Issue by casainho** [laurent22/joplin#9439]
### Operating system

Linux

### Joplin version

2.12.19

### Desktop version info

Joplin 2.12.19 (prod, linux)

Client ID: 8f4688faa3ef425d967272b789cf1a29
Sync Version: 3
Profile Version: 43
Keychain Supported: No

Revision: 7081046

Cursor Sync: 2.1.0
Delete unlinked resources: 1.0.0
Markdown Table: Sortable: 1.2.2
MultiMarkdown Table Tools: 1.1.0
Note Tabs: 1.4.0
Text Colorize: 1.2.3
Toggle Markup Type: 1.0.0

### Current behaviour

1. on WYSIWYG, write some text and add a web link
2. cut the text and past on another line
3. check the link

### Expected behaviour

The link should not be lost.

### Logs

Get this but does not seem an error info to me:

Got ipc-message: noteRenderComplete null

**Comment by casainho** [comment]
Issue still exists on Joplin 2.13.10 Linux version.

**Comment by personalizedrefrigerator** [comment]
For me (Ubuntu 23.10, Joplin 2.13.12), it seems to work, but only if I also select text that isn't in the link:

[Screencast from 2024-01-03 10-41-20.webm](https://github.com/laurent22/joplin/assets/46334387/806f1d7b-edd1-4fce-86b1-474b4ef21085)

**Comment by personalizedrefrigerator** [comment]
This also seems to be an issue with colored text:

[Screen recording: Selecting and copying colored text only retains formatting if edge of text is in selection.](https://github.com/laurent22/joplin/assets/46334387/81bd45fd-5621-40c4-9f6d-618e8e1bb2df)
