### ISSUE TITLE
Large notebook deleted note-by-note (visible in GUI)

### ISSUE THREAD

**Issue by msbentley** [laurent22/joplin#944]
### Operating system

- Linux

### Application

- Desktop

### Issue

When deleting a large notebook (many notes), the deletion appears to run note-by-note and is visible in the GUI:

![peek 2018-11-02 11-49](https://user-images.githubusercontent.com/1671065/47911862-ed26be00-de96-11e8-9a3e-0f1079e8d52a.gif)

I would have thought this deletion should happen in bulk, and behind the scenes - this way the GUI is busy for several minutes (still counting ;-) ).

Thanks!

**Comment by Xunius** [comment]
Same here. Deletion is too slow.
version: Joplin-1.0.158

**Comment by Xunius** [comment]
Tested on 1.0.169 (Joplin-1.0.169-x86_64.AppImage), it is still rather slow deleting a whole note-book.
