### ISSUE TITLE
Merge notes for joplin andoid

### ISSUE THREAD

**Issue by kiro5678** [laurent22/joplin#9446]
### Operating system

Android

### Joplin version

2.13.7

### Current behaviour

Please add merging notes in joplin for android

**Comment by laurent22** [comment]
https://github.com/JackGruber/joplin-plugin-combine-notes

**Comment by kiro5678** [comment]
> https://github.com/JackGruber/joplin-plugin-combine-notes

No, I mean Joplin for Android not Joplin Desktop
