### ISSUE TITLE
CliClient/app/command-server.js blames here, require('lib/model/Resource') is needed

### ISSUE THREAD

**Issue by joybinchen** [laurent22/joplin#945]
https://github.com/laurent22/joplin/blob/f92546d6eb4af1854c0b93b2f3a44061e28d9384/ReactNativeClient/lib/services/rest/Api.js#L496

**Comment by tessus** [comment]
Can you please be a bit more specific. When do you get this message? What are the steps to reproduce?

I'm running the latest version of joplin cli 1.0.117 and I have yet to come across this error.

**Comment by joybinchen** [comment]
I merge the headless-server branch to master,
> cd  CliClient
> ./run.sh server start

Open a web page with images in the main content on Chromium, and use a joplin-webclipper to Clip simplified page. then the error show up on cli output.

>   NODE_PATH="/opt/joplin.headless/CliClient/build" node build/main.js --profile ~/Temp/TestNotes2 --stack-trace-enabled --log-level debug --env dev server start
>   2018-11-03 14:39:46: "Starting Clipper server on port 27583"
>   2018-11-03 14:40:00: "Request: GET /ping"
>   2018-11-03 14:40:00: "Request: GET /folders"
>   2018-11-03 14:40:00: "Request: GET /tags"Resource
>   2018-11-03 14:40:09: "Request: POST /notes"
>   2018-11-03 14:40:09: "Request (1541227209625): Downloading images: 25"
>   2018-11-03 14:40:12: "Request (1541227209625): Creating resources from paths: 25"
>   2018-11-03 14:40:13: "ReferenceError: Resource is not defined
>   ReferenceError: Resource is not defined
>   	at md.replace (/opt/joplin.headless/CliClient/build/lib/services/rest/Api.js:496:24)
>   	at String.replace (<anonymous>)
>   	at Api.replaceImageUrlsByResources_ (/opt/joplin.headless/CliClient/build/lib/services/rest/Api.js:493:19)
>   	at Api.action_notes (/opt/joplin.headless/CliClient/build/lib/services/rest/Api.js:338:21)
>   	at <anonymous>"

**Comment by joybinchen** [comment]
I didn't do a merge actually. I just copy the following files from the headless-server branch to master, and npm install multiparty on CliClient
ReactNativeClient/lib/randomClipperPort.js
ReactNativeClient/lib/ClipperServer.js
CliClient/app/command-server.js

**Comment by laurent22** [comment]
I think this is fixed now.
