### ISSUE TITLE
Desktop: Move CodeMirror 6 editor out of beta

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#9450]
The CodeMirror 6 beta editor on desktop still has a number of issues that need to be addressed before it can be considered stable:
- [x] Plugin API documentation -- https://github.com/laurent22/joplin/pull/9933
- [ ] Fix search highlighting not synced between viewer and editor. (#9197)
- [x] Auto-indent doesn't work in code blocks with no recognised type.
- [x] Toggle comment doesn't work (see https://github.com/laurent22/joplin/pull/10016)
- [x] Enable multiple cursors (#9196) and fix the related list issue (#9200)
- [ ] Themes -- use colors from existing CodeMirror 5 themes in CodeMirror 6.
- [ ] Upgrade some of the most popular plugins to CodeMirror 6
    - [ ] Rich Markdown -- https://github.com/laurent22/joplin/pull/9935
    - [x] Quick Links -- https://github.com/roman-r-m/joplin-plugin-quick-links/pull/15
        - [x] Requires further work when other autocomplete plugins are enabled. https://github.com/roman-r-m/joplin-plugin-quick-links/pull/17 allows fixing an issue.
    - [x] Inline tags -- https://github.com/roman-r-m/joplin-inline-tags-plugin/pull/10
    - [ ] Math mode
        - Seems to only **sometimes** work in CodeMirror 6. Possibly related to [this issue](https://github.com/laurent22/joplin/pull/10024)? (This may be a regression...)
    - [x] [Multimarkdown table tools](https://joplinapp.org/plugins/plugin/joplin.plugin.MultiMarkdownTableTools/?from-tab=all) (https://github.com/FelisDiligens/joplin-plugin-multimd-table-tools/pull/7)
        - **Status**: Waiting for review.
    - [ ] [Note link system](https://joplinapp.org/plugins/plugin/ylc395.noteLinkSystem/?from-tab=all)
    - [ ] Themes: [MacOS theme](https://joplinapp.org/plugins/plugin/com.andrejilderda.macOSTheme/?from-tab=all), [ReMoods theme](https://joplinapp.org/plugins/plugin/joplin.plugin.remoods.theme/)
    - [ ] Enhancement -- https://github.com/SeptemberHX/joplin-plugin-enhancement/issues/63
        - I originally thought that making Enhancement compatible with CM6 would be a very large amount of work. For at least 2-3 of its main features, this might not actually be the case.

## List of known broken plugins

- Partial: Rich Markdown -- changes to support CM6 not released.
- Partial: [MacOS theme](https://joplinapp.org/plugins/plugin/com.andrejilderda.macOSTheme/?from-tab=all), [ReMoods theme](https://joplinapp.org/plugins/plugin/joplin.plugin.remoods.theme/)
    - CodeMirror themes don't work
- Partial: [Note link system](https://joplinapp.org/plugins/plugin/ylc395.noteLinkSystem/?from-tab=all)
    - Non-CodeMirror features work
- Partial: [Math mode](https://joplinapp.org/plugins/plugin/plugin.calebjohn.MathMode/)
- No support: [Better codeblocks](https://joplinapp.org/plugins/plugin/com.ckant.joplin-plugin-better-code-blocks/?from-tab=all)
- No support: [Enhancement](https://github.com/SeptemberHX/joplin-plugin-enhancement/issues/63)

**Comment by laurent22** [comment]
Thanks for creating this plan!

How many active CodeMirror plugins are there? I wonder if it really makes sense to spend a lot of time on this compatibility layer if we could simply fix the few that are out there?

Also once we make this editor the default, I think we should restrict access to the compatibility layer to existing plugins only. New plugins should not use it at all. Maybe like it's been done here, or similar solution: https://github.com/laurent22/joplin/blob/2c0f8d5c6be150475a3534ba5c5df3413fec825e/packages/lib/services/plugins/api/JoplinSettings.ts#L11

**Comment by personalizedrefrigerator** [comment]
> How many active CodeMirror plugins are there?

Based on a GitHub code search, I estimate 20-50 ([code search](https://github.com/search?q=%2Fjoplin%5C.contentScripts%5C.register%5C%28%5B%5Cn+%5Ct%5D*ContentScriptType%5C.CodeMirror%2F&type=code&p=1)).

> Also once we make this editor the default, I think we should restrict access to the compatibility layer to existing plugins only. New plugins should not use it at all.

This makes sense.

Perhaps we could have a separate method for registering content scripts. For example,
```
joplin.contentScripts.register(
            ContentScriptType.CodeMirror6Plugin,
            ...
)
```

In this case, CodeMirror6 plugins could export a [CodeMirror 6 extension](https://codemirror.net/docs/guide/#extension).


**Notes**:
- Our CodeMirror compatibility layer extends [CodeMirror-vim's compatibility layer](https://github.com/replit/codemirror-vim/blob/master/src/cm_adapter.ts), so we aren't maintaining all of it.
- CodeMirror 6's extension system is very different from CodeMirror 5's.
- If I recall correctly, one of the biggest issues we have when updating CodeMirror is multiple copies of global objects (e.g. [facets](https://codemirror.net/docs/guide/#facets)) such that equality checks fail (copy1 !== copy2). For this reason, it may be necessary for us to export these static objects to plugins.
