### ISSUE TITLE
'Use' command not listed in the help docs for Joplin termianl client

### ISSUE THREAD

**Issue by mlaiseca3** [laurent22/joplin#9452]
### Operating system

Linux

### Joplin version

2.13.2

### Current behaviour

1. 'help' command is used
2. 'use' command is not listed as the possible commands 
3. 'help all' command used
4. scroll to find 'use' command in help docs
5. 'use' command not found
6. 'help use' command used
7. description of 'use' command shown

### Expected behaviour

1. show 'use' command as part of list of possible commands after using 'help' command
2. show 'use' command documentation after using 'help all' 
3. include in 'tag' documentation that you need to apply 'use' command prior to using the 'tag' command to target the desired notebook
![Screenshot from 2023-12-05 16-50-42](https://github.com/laurent22/joplin/assets/7256921/badcf981-5c06-4dc9-9f16-dbc14a3fcba9)
![Screenshot from 2023-12-05 16-51-12](https://github.com/laurent22/joplin/assets/7256921/10c05e32-091b-44c8-8518-a16238f4505b)
![Screenshot from 2023-12-05 16-58-10](https://github.com/laurent22/joplin/assets/7256921/39ebae87-ab1e-4f1b-b472-b10507f23402)

**Comment by Daeraxa** [comment]
I assume this went missing somewhere, it did used to be in `help all` as you can see from the output of 2.8.1:

![image](https://github.com/laurent22/joplin/assets/58074586/9bd41d7f-71da-46d2-bbaf-9e38c31901e3)

**Comment by laurent22** [comment]
This is very weird, I'm on 2.13.2 as well and can't replicate any of this. The `use` command is there as expected

**Comment by personalizedrefrigerator** [comment]
On [my branch for this pull request](https://github.com/laurent22/joplin/pull/9552) `yarn start help` includes `use`, but `:help` does not. (It should be the other way around).

`command-use` has
```js
	compatibleUis() {
		return ['cli'];
	}
```
which should probably be
```js
	compatibleUis() {
		return ['gui', 'cli'];
	}
```
as switching notebooks can be done in either command line mode or GUI (terminal user interface) mode.
