### ISSUE TITLE
Desktop: Note list: Highlighted note barely visible in "OLED Dark" theme

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#9453]
### Operating system

Windows

### Joplin version

2.13.8

### Desktop version info

Joplin 2.13.8 (prod, win32)

Client ID: 25d9dae7661c4d5a9611082882a41044
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 604dcbc

Freehand Drawing: 2.5.0
RevealJS Integration: 0.6.0

### Current behaviour

To reproduce:
1. Enable the "OLED Dark" theme in settings
2. Open a note

### Expected behaviour

The selected note's background should have higher contrast with the surrounding notes.

### Screenshot

![screenshot: Low contrast](https://github.com/laurent22/joplin/assets/46334387/9af1036b-ac9e-4385-b71e-50992b747900)

**Comment by personalizedrefrigerator** [comment]
Originally reported on the forum: https://discourse.joplinapp.org/t/dark-theme-highlight-issue/34103

**Comment by personalizedrefrigerator** [comment]
Comparing to version 2.12.19, this does not seem to be a regression:
![screenshot from v2.12.19 of low contrast in OLED dark theme](https://github.com/laurent22/joplin/assets/46334387/488b6d4e-7059-415d-b0ac-2181e6938bfc)

**Comment by Harshiths1** [comment]
The contrast ratio should be approximately of 3:1 which would be good enough for even some color blind people , do I need to write a test for this too ?
