### ISSUE TITLE
Joplin portable update 

### ISSUE THREAD

**Issue by daniporr** [laurent22/joplin#9459]
### Operating system

Windows

### Joplin version

Any

### Desktop version info

Portable

### Current behaviour

1. A new version of Joplin is released
1. When you run Joplin, it says "An update is available, do you want to download it now?"
1. If you click on the "Download" button
1. It downloads the normal "-Setup" version

### Expected behaviour

It should download the "Portable" version

**Comment by laurent22** [comment]
The app is setup to get the portable version in this case. Are you sure you were using the portable version?

**Comment by laurent22** [comment]
You didn't provide any version info anyway so we can't answer that
