### ISSUE TITLE
I lost my note, is there a way to get them back from the .crypted file?

### ISSUE THREAD

**Issue by boringcoder** [laurent22/joplin#946]
### Operating system

- Windows

### Application

- Desktop

I have installed joplin on two linux servers (terminal) and one windows laptop (desktop version), today, I found that I lost some notes, but I don't know when and why it happen. I want to know is there a way to get them back from those .crypted files on my windows laptop? ( I mean those files in C:\Users\xxx\.config\joplin-desktop\resources)

**Comment by laurent22** [comment]
You can with the command line tool and the command `joplin e2ee decrypt`, but for further discussion please use the forum.
