### ISSUE TITLE
Android: cannot read or modify notes with the new editor

### ISSUE THREAD

**Issue by John-Johns0n** [laurent22/joplin#9464]
### Operating system

Android

### Joplin version

2.13.10

### Desktop version info

I have never used the desktop version.

#### The problem
I am not able to edit notes at all using the new editor. My installation of the app is essentially only usable with the plain text editor.

#### Screenshots
This is the view I get when looking at a note (perfectly normal):
[Fig 1: Viewing the note to read it (normal)](https://github.com/laurent22/joplin/assets/84598043/368f49e2-55bd-44ad-8f5a-7d1eb40424d4)

When I click the edit button, the note's contents disappear, and I am left with a "blank" screen. I cannot write anything nor read the note. The on-screen keyboard does not come up, either.
[Fig 2: Trying to edit the note](https://github.com/laurent22/joplin/assets/84598043/315ea67e-c1c3-4c88-b1a2-c21f2be1379c)

The only "exception" is that I can still edit the note's title as normal. Interestingly, the note's contents also disappear while I do (not sure if this is normal or not).
[Fig 3: Editing a note's title](https://github.com/laurent22/joplin/assets/84598043/4cb93d87-2e7c-45f9-87cc-8a9d8ea984b7)

#### Extra info
- **Everything works fine with the plain text editor. This issue is with the new editor.**
- This happens with all new notes as well, not just the "welcome" notes.
- The problem persists even after rebooting my device.
- I have tried uninstalling and reinstalling the app, but the problem is still there.
- While looking through the app's settings, I did notice that it didn't have the `Storage` permission; I went ahead and enabled it, though it does not seem to have changed anything.
- My device is running Android 8.0.
- I am not sure how relevant the log is in this case, but I went ahead and included it anyway just to be sure. I got it right after re-installing and messing around a little to make sure the bug was still there.

### Expected behavior
I downloaded the app yesterday, and it was working fine then. I expected it to keep working normally, but here we are.

### Logs
[mobile-log.log](https://github.com/laurent22/joplin/files/13600499/mobile-log.log)

**Comment by personalizedrefrigerator** [comment]
Check for updates for an "Android System WebView" app.

Joplin uses a WebView to display the editor (which is based on CodeMirror). If the WebView is out of date, it may not support some features the editor tries to use.

**Comment by John-Johns0n** [comment]
> Check for updates for an "Android System WebView" app.
> 
> Joplin uses a WebView to display the editor (which is based on CodeMirror). If the WebView is out of date, it may not support some features the editor tries to use.

I did this and it seems to have fixed the issue for now. Thanks for mentioning it.
