### ISSUE TITLE
Add support for colours in RTE

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9468]
TinyMCE already supports setting colours so it should be as simple as adding the button to the toolbar.

On Markdown side, we will use HTML to apply the colour - it should be self-contained and not rely on an external CSS stylesheet so that the Markdown content can be used anywhere.

**Comment by Inntel-Joplin** [comment]
Hi, I just installed Joplin and I am looking to use this new feature but can't find any trace of it in the current version. Is this scheduled for the next version or is there a particular way to enable it. I just started migrating from Evernote and text colors is the one feature that Joplin is missing for me to use it.

**Comment by Inntel-Joplin** [comment]
Forgot to add I'm using the Windows version at the moment.

**Comment by richcarl** [comment]
This was a great addition, but I'd really like to be able to change the background colour as well, to mark up some text sections differently, e.g. to show status or source. Only changing the text colour isn't as visible (esp. on a white background).
