### ISSUE TITLE
Notebook icons missing rightmost part in sidebar.

### ISSUE THREAD

**Issue by dimitristsilis** [laurent22/joplin#9475]
### Operating system

Android

### Joplin version

2.13.10

### Current behaviour

The notebook icons are not shown correctly in the sidebar **if they are emojis**. Can't check if the problem are the macOS emojis or something else.  Used language does not affect this behaviour.
![Screenshot_20231208_113456](https://github.com/laurent22/joplin/assets/15839158/4b904ced-0d68-4560-ac2e-5c07ab946c6d)

### Expected behaviour

Show whole icons and not part of them.

**Comment by laurent22** [comment]
I had this problem in an earlier version but that was fixed and indeed it's working for me. Could you provide an example of notebook title that has this issue? (that we can copy and paste)

**Comment by laurent22** [comment]
What phone and Android version?

**Comment by dimitristsilis** [comment]
@laurent22 It is Android 7.0 on an LG G6 device. Any notebook title will reproduce it. Here is a notebook named "Test". The properly shown exclamation icon was uploaded from disk.
![joplin screenshot](https://github.com/laurent22/joplin/assets/15839158/bbbbffdc-9d1b-4d46-a688-b8b6dbb5dffd)

**Comment by dimitristsilis** [comment]
Is there something we can do about this issue?

**Comment by personalizedrefrigerator** [comment]
Another issue [proposes that we bundle an Emoji font with the app](https://github.com/laurent22/joplin/issues/9505). Doing so may also fix this issue if caused by different Emoji fonts (and not text scaling).
