### ISSUE TITLE
Encrypted shared notes dissapear (and behave weird)

### ISSUE THREAD

**Issue by MatejKovacic** [laurent22/joplin#9476]
### Operating system

Android

### Joplin version

2.13.10

### Current behaviour

I am using Joplin server and I am sharing notes with my wife.

After some update notes on her account were not synchronized. First we noticed this on her desktop app. So I went to `Tools` - `Synchronisation`, enabled `Advanced options` and re-synced data from server.

Then I found out the same problem on her Android phone. So I wanted to do the same, but there is no `Advanced options` on Android app?? So Android users are unable to re-sync notes from the Joplin server?

Anyway, I deleted app, reinstalled it again and entered credentials. Now I was able to see shared notes, but since they are E2E encrypted, I needed to enter decryption password first.

I did this, and after I clicked sync button on her phone, shared notes just disappeared!

Then I found the "solution". I tried to share the notes again, my desktop app said that notes are already shared with this user, but when I clicked sync button on her phone, notes appeared back!

Unfortunately not all. Because I have nested notes. This was then solved in that way, that I moved nested notes to the root of my notes (in my desktop Joplin), synced my desktop Joplin, synced my wife's Joplin on Android, moved that notes back (so they are nested again), synced my desktop Joplin, synced my wife's Joplin on Android, and now it is working.

So there seems to be a bug with sharing notes and there is no `Advanced options` on Android app to resync the notes from server.

Some more info:
- Joplin versison: 2.13.10
- Database v44
- FTS enabled: 1
- Hermes enabled: 1

Phone:
- Galaxy S22 Ultra
- Android 14

**Comment by MatejKovacic** [comment]
First screenshot after I synced notes from server. You can see one shared notes and nested note, that is also shared:

![joplin_notes1](https://github.com/laurent22/joplin/assets/3339198/ba36b681-d1ed-4783-9776-f96a22c4dd93)

After entering E2E passwords and syncing again shared notes dissapear:
 
![joplin_notes2](https://github.com/laurent22/joplin/assets/3339198/be5bcdef-f02c-4701-ba53-3184edac21ab)

**Comment by laurent22** [comment]
You seem to have a lot of notes and from the sync status it's still synchronising and decrypting, so you might just need to wait to get all your data?

**Comment by MatejKovacic** [comment]
No, because syc was finished. And as you can see from the first picture, I can see the notes, and after syncing second time, shared notes disappeared.

And when I tried to share them again, Joplin warned me that notes are already shared with the user and then shared notes finally appear on a phone.

I tried this several times, so it is not that is needs some time...
