### ISSUE TITLE
Android: "could not autheize application" "code: must not be empty" "error: invlid_request"

### ISSUE THREAD

**Issue by ewonchang** [laurent22/joplin#948]
### Operating system

- Android

### Application

- Mobile

I was not able to setup Dropxbox sync on my Android 9.0 phone, although I have enabled all three permissions prior to launching the app.

Here is the error message when I hit "submit" button. I have also posted the log file below.
![screenshot_20181102-120450](https://user-images.githubusercontent.com/30449109/47927040-99b56f80-de98-11e8-8909-159bed91fb6a.png)

> Date,Level,Message
11-02T00:20:33,30,"""Reducer action", "NAV_GO, Log""
11-02T00:20:29,30,"""Settings have been saved.""
11-02T00:20:28,30,"""Reducer action", "NAV_BACK""
11-02T00:20:28,30,"""Saving settings...""
11-02T00:20:28,30,"""Reducer action", "SETTING_UPDATE_ONE""
11-02T00:20:28,30,"""Reducer action", "SETTING_UPDATE_ONE""
11-02T00:20:28,30,"""Reducer action", "SETTING_UPDATE_ONE""
11-02T00:20:28,30,"""Reducer action", "SETTING_UPDATE_ONE""
11-02T00:20:28,30,"""Reducer action", "SETTING_UPDATE_ONE""
11-02T00:20:23,30,"""ResourceService::deleteOrphanResources:", "[]""
11-02T00:20:23,30,"""ResourceService::indexNoteResources: Completed""
11-02T00:20:23,30,"""ResourceService::indexNoteResources: Start""
11-02T00:20:04,30,"""Reducer action", "DECRYPTION_WORKER_SET""
11-02T00:20:04,30,"""DecryptionWorker: completed decryption.""
11-02T00:20:04,30,"""Reducer action", "DECRYPTION_WORKER_SET""
11-02T00:20:04,30,"""DecryptionWorker: starting decryption...""
11-02T00:20:03,30,"""Garbage collecting alarms...""
11-02T00:20:03,30,"""Updating all notifications...""
11-02T00:20:03,30,"""Synchroniser is missing credentials - manual sync required to authenticate.""
11-02T00:20:03,30,"""Preparing scheduled sync""
11-02T00:20:02,30,"""Reducer action", "NAV_GO, Config""
11-02T00:19:56,30,"""Settings have been saved.""
11-02T00:19:56,30,"""Saving settings...""
11-02T00:19:56,30,"""Reducer action", "SIDE_MENU_CLOSE""
11-02T00:19:56,30,"""Reducer action", "SIDE_MENU_CLOSE""
11-02T00:19:56,30,"""Reducer action", "NAV_GO, DropboxLogin""
11-02T00:19:56,30,"""Reducer action", "SETTING_UPDATE_ONE""
11-02T00:19:56,30,"""Saving updated Dropbox auth.""
11-02T00:19:55,30,"""Reducer action", "SIDE_MENU_OPEN""
11-02T00:19:55,30,"""Reducer action", "SIDE_MENU_TOGGLE""
11-02T00:19:54,30,"""DecryptionWorker: completed decryption.""
11-02T00:19:54,30,"""Reducer action", "DECRYPTION_WORKER_SET""
11-02T00:19:54,30,"""Reducer action", "DECRYPTION_WORKER_SET""
11-02T00:19:54,30,"""DecryptionWorker: starting decryption...""
11-02T00:19:54,30,"""Settings have been saved.""
11-02T00:19:54,30,"""Saving settings...""
11-02T00:19:53,30,"""ResourceFetcher: Auto-added resources: 0""
11-02T00:19:53,30,"""Reducer action", "APP_STATE_SET""
11-02T00:19:53,30,"""Scheduling sync operation...""
11-02T00:19:53,30,"""Application initialized""
11-02T00:19:53,30,"""Reducer action", "NAV_GO, Welcome""
11-02T00:19:53,30,"""Reducer action", "FOLDER_SET_COLLAPSED_ALL""
11-02T00:19:53,30,"""Reducer action", "MASTERKEY_UPDATE_ALL""
11-02T00:19:53,30,"""Reducer action", "TAG_UPDATE_ALL""
11-02T00:19:53,30,"""Reducer action", "FOLDER_UPDATE_ALL""
11-02T00:19:53,30,"""Loading folders...""
11-02T00:19:53,30,"""Loaded master keys: 0""
11-02T00:19:53,30,"""Trying to load 0 master keys...""
11-02T00:19:53,30,"""Scheduling sync operation...""
11-02T00:19:53,30,"""Reducer action", "MASTERKEY_REMOVE_NOT_LOADED""
11-02T00:19:53,30,"""Loaded master keys: 0""
11-02T00:19:53,30,"""Trying to load 0 master keys...""
11-02T00:19:53,30,"""Sync target: 7""
11-02T00:19:53,30,"""Reducer action", "SETTING_UPDATE_ONE""
11-02T00:19:53,30,"""Reducer action", "SETTING_UPDATE_ONE""
11-02T00:19:53,30,"""Reducer action", "SETTING_UPDATE_ALL""
11-02T00:19:53,30,"""Loading settings...""
11-02T00:19:53,30,"""Database is ready.""
11-02T00:19:53,30,"""Initializing tables...""
11-02T00:19:53,30,"""Converting database to version 13""
11-02T00:19:53,30,"""Converting database to version 12""
11-02T00:19:52,30,"""Converting database to version 11""
11-02T00:19:52,30,"""Converting database to version 10""
11-02T00:19:52,30,"""Converting database to version 9""
11-02T00:19:52,30,"""Converting database to version 8""
11-02T00:19:52,30,"""Converting database to version 7""
11-02T00:19:52,30,"""Converting database to version 6""
11-02T00:19:52,30,"""Converting database to version 5""
11-02T00:19:52,30,"""Converting database to version 4""
11-02T00:19:52,30,"""Converting database to version 3""
11-02T00:19:52,30,"""Converting database to version 2""
11-02T00:19:52,30,"""Converting database to version 1""
11-02T00:19:52,30,"""Current database version", "0""
11-02T00:19:52,30,"""Checking for database schema update...""
11-02T00:19:52,30,"""Database was open successfully""
11-02T00:19:52,30,"""Starting application net.cozic.joplin-mobile (prod)""
11-02T00:19:52,30,"""====================================""
================================================================================
type,id,updated_time,sync_time,is_conflict

**Comment by laurent22** [comment]
Did you actually copy and paste the Dropbox code in the text field?

**Comment by ewonchang** [comment]
No, I wasn't able to.
I opened Firefox, signed into Dropbox and actually got the authentication code.
Then I turned back to the app and hit "submit" button. That's what appeared in the picture

**Comment by ewonchang** [comment]
I'm so stupid, I didn't see the blank for authentication code. Sorry!
