### ISSUE TITLE
App asks to restart in safe mode after new update dialog is displayed

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9480]
### Operating system

macOS

### Joplin version

2.13.7

### Current behaviour

- Open the dialog that notifies you that a new update is available
- Let it open long enough
- Close it

=> A new dialog pops up saying that the window is unresponsive

<img width="313" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/d6b87ad2-3e6c-455a-8bdd-3c023328cfd5">

**Comment by personalizedrefrigerator** [comment]
Possibly related: https://github.com/electron/electron/issues/6146

**Comment by personalizedrefrigerator** [comment]
I haven't been able to reproduce this (tested on Ubuntu 23.10 and MacOS Sonoma, keeping dialog open for roughly 30 seconds).

Here are some options:
1. Test with [this commit](https://github.com/personalizedrefrigerator/joplin/commit/4ac4a6f7712fc37da61cc51720f728966c6a254e), which might fix the issue (depending on when the `unresponsive` event is fired).
2. Switch to `async` dialog methods.
3. Store information about whether a dialog is open in `bridge.showMessageBox_` and check this before showing the "unresponsive" dialog.
4. Remove the `unresponsive` event handler.

Option 3 should be easiest to implement without being able to reproduce the issue.

**Comment by laurent22** [comment]
According to the linked issue, it seems to be more like 2-3 minutes wait. In my case it might have been 30 min or more since I was away from my computer. Maybe we can record the time when the dialog is closed, and if it's been less than x seconds  since it happened, we ignore the next unresponsive event.

But long term we should probably switch to async dialogs to avoid this issue.

**Comment by laurent22** [comment]
(On the other hand it seems to work well with detecting when the renderer process is gone, which just happened to me when testing OCR, and it gives the option to restart in safe mode)

**Comment by personalizedrefrigerator** [comment]
By leaving dialogs open for longer (2-3 minutes), I am able to reproduce this issue.

**Comment by renesugar** [comment]
I am still seeing this error (first on Mac OS; then, on Ubuntu).

Nothing shows up in the console log if it is open before the error occurs (eg. which window is unresponsive).

![joplin_window_unresponsive_error](https://github.com/user-attachments/assets/706588d8-3c17-4d4a-a9d7-b07f6bc51bee)

**Comment by personalizedrefrigerator** [comment]
> I am still seeing this error (first on Mac OS; then, on Ubuntu).

Is this specific to the update dialog? (Does it happen when the "update available" dialog isn't open?) If so, is the backup plugin enabled? Does disabling it help?

**Comment by renesugar** [comment]
I see the dialog when trying to do a search long after any update has taken place.

Sometimes the UI locks up when doing a search and eventually shows that dialog with nothing in the console log showing why it happened.

Disabling plugins didn't have any effect.

**Comment by renesugar** [comment]
This is an older article which might be related to what is happening.


The Horror of Blocking Electron’s Main Process

https://medium.com/actualbudget/the-horror-of-blocking-electrons-main-process-351bf11a763c

"I took a deeper look at this today. IPC is critical for all rendering tasks and keeping the main process busy seems to block the IPC pipe and drops frames across all renderer processes."

https://x.com/NumaanAshraf/status/968496732278374400


Electron: Getting Custom Error Messages from IPC Main

https://m-t-a.medium.com/electron-getting-custom-error-messages-from-ipc-main-617916e85151


Simplified IPC communication for Electron apps

https://www.npmjs.com/package/electron-better-ipc


Syncing State between Electron Contexts

https://brunoscheufler.com/blog/2023-10-29-syncing-state-between-electron-contexts


Things I Wish I Knew Before Working with Electron.js

https://www.bomberbot.com/electron/things-i-wish-i-knew-before-working-with-electron-js/

"However, it‘s easy to overuse IPC and create performance bottlenecks by shuttling too much data back and forth."


The Secret of Good Electron Apps

https://archive.jlongster.com/secret-of-good-electron-apps
