### ISSUE TITLE
Feel sorry! This is a misuse...

### ISSUE THREAD

**Issue by zhouxinghong** [laurent22/joplin#9482]
### Operating system

Windows

### Joplin version

0.1.0

### Desktop version info

rtrt

### Current behaviour

trtr

### Expected behaviour

trt

### Logs

trt

**Comment by Gaberilla** [comment]
Leave my shit alone! Idk who the fuk u guys are or what u r getting paid to
do this…. I’m telling u now… u keep messing with my phone, my personal
private business, my kids accounts, as well as mine…. I will figure u out!
I might be smart with the numbers, them codes, behind a screen somewhere….
News Flash… I’ve HAD enough! Idk if u wack your dick while talking into
your mic trying to do ur pull request and stop everything for the man
telling you what to do! GROW THE FUCK UP & GET A LIFE! Don’t send one more
email to my shit! Not 1!! I’m telling u, today ain’t the day! I don’t know
if u ever met a woman who is scorned, angry as hell for allowing herself to
be so manipulated, so disrespected, and walked on… Well keep Fucking with
ME… I’ll meet you when & where ever you fucking like! No FUCKIN LIE!
