### ISSUE TITLE
Hovering over list of notes does not cause the second note to be highlighted

### ISSUE THREAD

**Issue by kristophercrawford** [laurent22/joplin#9496]
### Operating system

macOS

### Joplin version

2.13.9

### Desktop version info

Joplin 2.13.9 (prod, darwin)

Client ID: fc12d697483d497e9e2cc6406155c88e
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 1bbec44

Better Code Blocks: 1.1.0
macOS theme: 1.3.13
Rich Markdown: 0.13.3
Table Formatter Plugin: 1.2.1
Templates: 2.4.0

### Current behaviour

1. Have a notebook with at least three notes.
2. Hover over the title of each note in the list. 
3. The first note will transition to having a light gray background.
4. The second note in the list will not
5. The third note in the list will. 

https://github.com/laurent22/joplin/assets/32402434/0a821c4c-a082-40d0-85db-dabca19a7a3f

### Expected behaviour

All notes in the list should have a light gray background when hovering over them.

**Comment by dimitristsilis** [comment]
I am using the same version of Joplin on Ventura and cannot reproduce this bug. Perhaps it has to do with the macOS theme?

**Comment by dimitristsilis** [comment]
@kristophercrawford does it happen with "macOS theme" plug-in disabled?

**Comment by kristophercrawford** [comment]
Confirmed, disabling the MacOS theme resolves the issue I am facing. Closing this and will re-open an issue under the MacOS theme plugin.
