### ISSUE TITLE
[Feature request] Add custom global html code to all notes

### ISSUE THREAD

**Issue by seth100** [laurent22/joplin#950]
### Operating system

- Linux
- Android

### Application

- Desktop
- Mobile

Hi,

would it be possible to add a feature to be able to add some custom html to customize note rendering style and structure?

If I add some custom html code (e.g. with some `<style></style>` rules) in the Desktop app I see the change but it's related to the specific note file and not to all notes, so I don't want to repeat that code for each file.

Please, it would be really helpful for me.

Thanks

**Comment by subi54** [comment]
It might be coming soon, [see](https://github.com/laurent22/joplin/pull/925).

**Comment by seth100** [comment]
@CalebJohn yes for me css is enough yes. Will that pull request be merged soon?
Thanks

**Comment by seth100** [comment]
@CalebJohn that's a great news, thank you so much!
