### ISSUE TITLE
on dark theme Joplin Cloud email should be white 

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9500]
### Operating system

Android

### Joplin version

2.13

### Current behaviour

- choose a dark theme
- go to JC setting screen

=> The email is using a black font, but it should be white.

It needs to use the "color" property of the theme

**Comment by pedr** [comment]
I'm not sure how to tackle this issue yet.

I think I understand the assignment, some emails have almost unreadable content if the color scheme is set to dark:

![Screenshot from 2023-12-11 21-19-37](https://github.com/laurent22/joplin/assets/5051088/40d43b8d-8c4e-4646-9142-d4032bc66a4a)

But I have some questions

- Are we talking only about text set to to `#000` color?
- If not, how are we going to ensure that the text is "darker" enough? Image above is an example, I think is reasonable to read, but not comfortable.
- Some emails have background color like the image bellow, so we can't just set all font to a brighter color

![image](https://github.com/laurent22/joplin/assets/5051088/efd8cee2-e20e-4f58-bce9-c658b0586424)

**Comment by pedr** [comment]
Maybe the idea is just to change the color of the content that appears in the "Forward message" header? If this is the case I imagine that we would need to have a special CSS rule for each email provider (since each one must have its own HTML structure), but I need to test some popular services to understand it better

**Comment by laurent22** [comment]
Sorry I was on mobile when I wrote this bug report and it's not very clear.

I mean, in the mobile app, open the configuration screen, and go to to the "Joplin Cloud" section. There you have your email-to-note email address that's displayed. It's always in black, whether the current time is light or dark, which means it's not readable in dark theme.

The other issue you raised is indeed also something we'll need to deal with though, but it's more a general issue about how the desktop app displays HTML-based notes.

**Comment by pedr** [comment]
Ah ok, that makes sense. Thanks for clarifying!
