### ISSUE TITLE
KaTex error when using \hline in \{array} enviornment on Android

### ISSUE THREAD

**Issue by georg-mayer** [laurent22/joplin#952]
### Operating system

Android 7.0 on several devices

- Android

### Application

- Mobile

This problem does not occur on the Linux app, which I also use and where everything is rendered nicely.
On Android Mobile App, when I use inline Latex in an array enviornment, then the \hline at the end of a row throws an error.

Example:
`
$\begin{array}{ccc}
1 & 2 & 3 \\ \hline
4 & 5 & 6
\end{array}$
`
Comes back with:
Cannot render Katex content: KaTeX parse error: Expected & or \\ or \end at position 33: …} 1 & 2 & 3 \\ \̲h̲l̲i̲n̲e̲ 4 & 5 & 6 \end…

(\hline is underlined).

It seems this is an KaTeX error which should already be fixed since long time according to information provided by KaTeX.  

Thanks for this great application and your help!

Cheers,
Georg

Here's the debug log output, it doesn't report the error:
Date,Level,Message
11-06T07:26:52,30,"""Reducer action", "NOTE_UPDATE_ALL""
11-06T07:25:59,30,"""Reducer action", "NOTE_UPDATE_ALL""
11-06T07:25:58,30,"""Reducer action", "NAV_BACK""
11-06T07:25:15,30,"""Reducer action", "NAV_GO, Config""
11-06T07:25:12,30,"""Reducer action", "SIDE_MENU_CLOSE""
11-06T07:25:09,30,"""Reducer action", "SIDE_MENU_OPEN""
11-06T07:25:09,30,"""Reducer action", "SIDE_MENU_TOGGLE""
11-06T07:25:07,30,"""Reducer action", "NOTE_UPDATE_ALL""
11-06T07:24:54,30,"""Reducer action", "NOTE_UPDATE_ALL""
11-06T07:24:52,30,"""Reducer action", "NAV_BACK""
11-06T07:24:24,30,"""Reducer action", "FOLDER_UPDATE_ALL""
11-06T07:24:24,30,"""Reducer action", "SYNC_COMPLETED""
11-06T07:24:24,30,"""Total resources: 1""
11-06T07:24:24,30,"""Total notes: 301""
11-06T07:24:24,30,"""Total folders: 8""
11-06T07:24:24,30,"""createRemote: 1""
11-06T07:24:24,30,"""Operations completed: ""
11-06T07:24:21,30,"""Reducer action", "NAV_GO, Log""
11-06T07:24:19,30,"""Reducer action", "SYNC_STARTED""
11-06T07:24:19,30,"""Starting scheduled sync""
11-06T07:24:19,30,"""Preparing scheduled sync""
11-06T07:24:14,10,"""Could not get lat/long for note 47e15193970742c09f3cd4a75060b084: ", "{"TIMEOUT":3,"POSITION_UNAVAILABLE":2,"PERMISSION_DENIED":1,"message":"No location provider available.","code":2}""
11-06T07:24:14,30,"""Scheduling sync operation...""
11-06T07:24:14,30,"""Reducer action", "NOTE_SELECT""
11-06T07:24:14,30,"""Fetching geolocation...""
11-06T07:24:14,30,"""Reducer action", "EVENT_NOTE_ALARM_FIELD_CHANGE""
11-06T07:24:14,30,"""Reducer action", "NOTE_UPDATE_ONE""
11-06T07:24:08,30,"""Reducer action", "NAV_GO, Note""
11-06T07:24:05,30,"""Reducer action", "SIDE_MENU_CLOSE""
11-06T07:24:03,30,"""Reducer action", "SIDE_MENU_OPEN""
11-06T07:24:03,30,"""Reducer action", "SIDE_MENU_TOGGLE""
11-06T07:24:02,30,"""Reducer action", "NAV_BACK""
11-06T07:23:49,30,"""Reducer action", "NAV_GO, Note""
11-06T07:23:47,30,"""Reducer action", "SIDE_MENU_CLOSE""
11-06T07:23:47,30,"""Reducer action", "NAV_GO, Notes""
11-06T07:23:47,30,"""Reducer action", "SIDE_MENU_CLOSE""
11-06T07:23:47,30,"""Settings have been saved.""
11-06T07:23:47,30,"""Saving settings...""
11-06T07:23:47,30,"""Reducer action", "SIDE_MENU_OPEN""
11-06T07:23:47,30,"""Reducer action", "SIDE_MENU_TOGGLE""
11-06T07:23:46,30,"""Reducer action", "FOLDER_UPDATE_ALL""
11-06T07:23:46,30,"""Reducer action", "SETTING_UPDATE_ONE""
11-06T07:23:46,30,"""Reducer action", "SYNC_COMPLETED""
11-06T07:23:46,30,"""Total notes: 300""
11-06T07:23:46,30,"""Total resources: 1""
11-06T07:23:46,30,"""Total folders: 8""
11-06T07:23:46,30,"""Operations completed: ""
11-06T07:23:46,30,"""fetchingTotal: 1""
11-06T07:23:46,30,"""Reducer action", "SETTING_UPDATE_ONE""
11-06T07:23:45,30,"""Reducer action", "NAV_BACK""
11-06T07:23:43,30,"""Reducer action", "NAV_BACK""
11-06T07:23:41,30,"""Reducer action", "SYNC_STARTED""
11-06T07:23:41,30,"""Reducer action", "NOTE_UPDATE_ALL""
11-06T07:23:41,30,"""Starting scheduled sync""
11-06T07:23:41,30,"""Scheduling sync operation...""
11-06T07:23:41,30,"""Preparing scheduled sync""
11-06T07:23:41,30,"""Running background sync on timer...""

**Comment by laurent22** [comment]
Yes it's just the katex lib that needs to be updated.

**Comment by georg-mayer** [comment]
Thanks for confirming that laurent22!
