### ISSUE TITLE
 it is not possible to write note or edit notes.

### ISSUE THREAD

**Issue by parduspanteri** [laurent22/joplin#9521]
### Operating system

iOS

### Joplin version

12.13.10

### Current behaviour

https://github.com/laurent22/joplin/assets/105588014/790f09f2-c341-4c40-a7ef-b5c6a76351f5

New note can't be written and old notes can't be changed. It broke with the latest update. it didn't have this problem before.

IOS version:12.5.7

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this! I suspect it's an incompatibility between iOS 12 and a feature used by the markdown editor (which runs in a WebView).

I'm currently working on setting up an iOS 12 simulator for testing.

For now, notes should be editable by enabling the "Plain editor" in "Configuration > Note".

A log may also be helpful.

**Comment by parduspanteri** [comment]
Yes, "plain text editor" enable is working currently. Thanks...

**Comment by personalizedrefrigerator** [comment]
It seems that the oldest version I can test on from XCode iOS 15 (unless there's another way to select older iOS versions);

<img width="942" alt="Screenshot: iOS simulator version list" src="https://github.com/laurent22/joplin/assets/46334387/00668b29-93e3-4de3-870e-edd3cc67e5e5">

A log (Configuration > Tools > Log) might contain more information about what's going wrong.
