### ISSUE TITLE
pasting rich text into WYSIWYG editor can result in invalid formatting

### ISSUE THREAD

**Issue by ghosttie** [laurent22/joplin#9530]
### Operating system

Windows

### Joplin version

2.13.9

### Desktop version info

Joplin 2.13.9 (prod, win32)

Client ID: 6767f00071024d1aa6fa338f36c999d5
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 1bbec44

Conflict Resolution: 1.2.3

### Current behaviour

1. copy rich text from somewhere that has formatting that isn't valid in markdown, e.g. color or font
2. paste this into Joplin's WYSIWYG editor
3. the text appears with the invalid formatting
![image](https://github.com/laurent22/joplin/assets/1552778/93d373d0-7343-4062-93f7-34897083d2ca)
4. click on a different note and click back to force it to refresh
5. now the text appears with only the valid markdown formatting
![image](https://github.com/laurent22/joplin/assets/1552778/ac13f594-72d4-490b-9063-5ce88b27efad)

### Expected behaviour

I would expect Joplin to sanitize the pasted text, removing any formatting that's invalid in markdown

**Comment by futuremotiondev** [comment]
This might be by design - if you use `Ctrl+Shift+V` to paste, it will only paste plain text.

**Comment by ghosttie** [comment]
Not fixed

**Comment by personalizedrefrigerator** [comment]
The [2.14.12 release notes](https://github.com/laurent22/joplin/releases/tag/v2.14.12) contain this line:
> Fixed: Pasting rich text in the RTE sometimes result in invalid markup (https://github.com/laurent22/joplin/issues/9512)

A brief test suggests that this might be fixed in the latest pre-release.

**Comment by ghosttie** [comment]
It looks fixed in the current version
