### ISSUE TITLE
Master key is loaded and not loaded at the same time

### ISSUE THREAD

**Issue by alexanderadam** [laurent22/joplin#9534]
### Operating system

Android

### Joplin version

2.13.10

### Current behaviour

Joplin messed up sync again on my Android mobile app so I decided to invest the hours and sync from scratch again.
However, this time it doesn't seem to work as it's claiming that there's no master key available.
If I look at the settings everything looks fine though.

So what do I need to do now?

![Screenshot_20231216_115652_Joplin](https://github.com/laurent22/joplin/assets/372620/68fbd47a-0577-4e4a-bd56-7d035a577101)

![Screenshot_20231216_115708_Joplin](https://github.com/laurent22/joplin/assets/372620/88bdfca8-c053-4426-83a7-e1a9f5c824ab)

### Expected behaviour

Sync should work

**Comment by laurent22** [comment]
How does it look like on desktop, could you provide screenshot?

**Comment by alexanderadam** [comment]
@laurent22 on Desktop everything looks normal. I never have sync issues on Desktop anyway.
I guess it's because it can run safely in the background while the mobile app is being killed once the sync wasn't babysitted and the screen goes off.

Or do you mean how it looks when I'd try to sync completely from scratch on Desktop?
Can you elaborate on that?

**Comment by laurent22** [comment]
I just wonder if the desktop encryption config screen would show more information, such as what keys are active, which ones have the right password or not. I'm wondering if the mobile screen is showing the full information

**Comment by alexanderadam** [comment]
That's the Desktop encryption overview.

I double checked the keys and they are the same on both devices (btw it would help if the keys would be alphabetically ordered here :wink: )

![image](https://github.com/laurent22/joplin/assets/372620/3f479ac3-1227-4bfd-bd0d-88b33cf2b4bb)

**Comment by alexanderadam** [comment]
Oh nice: now it seems to work!

I'm not sure whether it's related but I fully killed the app from system overview and restarted it.
It might be a bug but it's working for me right now and there are more urgent issues that aren't tackled right now so I'm making room for these and close this issue instead.

**Comment by laurent22** [comment]
Thanks for the feedback. I think what may have happened is that on first sync it fetches the key, but don't load them (while it should). I'm going to reopen the issue to keep track of this bug

**Comment by laurent22** [comment]
I cannot replicate it so closing it for now
