### ISSUE TITLE
Android 9 - Network Request Failed 

### ISSUE THREAD

**Issue by popolski67** [laurent22/joplin#954]
### Operating system
- Android 9
### Application
Joplin

Hi,
I implemented Joplin desktop apll. on Linux Mint 19 and it syncs fine with my nextcloud home server. But the android app on my mobile phone always shows: "Network Request Failed". I checked webdav-adress, user and PW several times and I can't figure out, what's wrong.

11-07T14:21:08,10,"""TypeError: Network request failed onerror@index.android.bundle:111:4815***

**Comment by royalheadwear** [comment]
I have the same issue on a Honor 10 Smartphone running Android 8.1.0

**Comment by popolski67** [comment]
Thank you very much for your hint. I finally managed to apply for a domain, get letsencrypt licenses and modify config.php. Now sync on Android finally works.Quite complicated for users who only want to de-google themselves via nextcloud...
