### ISSUE TITLE
log can't be copied or shared on Android

### ISSUE THREAD

**Issue by alexanderadam** [laurent22/joplin#9547]
### Operating system

Android

### Joplin version

2.13.10

### Current behaviour

Every single time I'm reporting a bug, the log file only can be "shared" but it would be easier if it could be downloaded or even copied. 

### Expected behaviour

Copying or downloading of log file works

**Comment by personalizedrefrigerator** [comment]
There seems to be a similar issue for note attachments and long-press > "Share". I think it would make sense to either:
1. When clicking "share" on Android, show a modal dialog that allows selecting "save to file" or "share to an app"
2. Add an additional "save to file" option in menus where "share" is used.

For now, "Export" > "Export debug report" should have similar content to a log from "Tools" > "Log", but instead saves to a file (and includes additional information about which items have been synced).
