### ISSUE TITLE
Yaml front matter mishandled with external editing 

### ISSUE THREAD

**Issue by ilveroluca** [laurent22/joplin#9556]
### Operating system

Linux

### Joplin version

2.13.9

### Desktop version info

Joplin 2.13.9 (prod, linux)

Client ID: 39762fab5c4f49199a1d6c1b1e09bdf3
Sync Version: 3
Profile Version: 44
Keychain Supported: No

Revision: 1bbec44

Emoji: 1.0.4
Insert Date: 1.0.1
Note Tabs: 1.4.0
Outline: 1.5.13

### Current behaviour

Suppose you have a note with a title "my title".

![image](https://github.com/laurent22/joplin/assets/1502936/c56c471f-e06e-44fd-bd6d-a39a6ef31971)

You open it in an external editor and add some front matter:
```
---
lang: en
---

my title


Some text
```
![image](https://github.com/laurent22/joplin/assets/1502936/a362a1d8-d021-428f-a663-f4444a0ae41c)

If I add new yaml front matter to a document while editing externally, the front matter is not interpreted correctly. The first `---` line ends up overwriting the title, the first line of the yaml document seems to be lost, and the rest is interpreted as markdown text.

### Expected behaviour

When starting external editing, I would expect metadata to be inserted in the document as yaml front matter.

When concluding external editing, I would expect Joplin to correctly parse the yaml front matter and document metadata, rather than interpreting it as markdown formatted text.

**Comment by laurent22** [comment]
This is not a bug, FrontMatter is simply not supported when using the external editor

**Comment by ilveroluca** [comment]
Ah, ok.  Thanks.
