### ISSUE TITLE
Custom CSS inconsistently applied to HTML notes

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#9570]
### Operating system

Linux

### Joplin version

2.13.9

### Desktop version info

Joplin 2.13.9 (prod, linux)

Client ID: 24b2a961cccf40fe8448cdc0930b6fce
Sync Version: 3
Profile Version: 44
Keychain Supported: No

Revision: 1bbec445d

Freehand Drawing: 2.7.1
RevealJS Integration: 0.6.1
Simple Backup: 1.3.4
Work tracker: 0.0.1

### Current behaviour

1. Add custom CSS
2. Open an HTML note
3. Compare rendered version to a markdown note with the same content
4. Re-open the HTML note
5. Switch to the rich text editor 
6. Open a markdown note
7. Switch back to the rich text editor

Currently, custom CSS is only applied after switching from a markdown note to an HTML note (rich text editor).

**Edited**: Edited to reflect that custom CSS sometimes loads.

### Expected behaviour

- Custom CSS should be applied to HTML notes consistently.

**Comment by laurent22** [comment]
It was enabled before but later disabled because it caused too many conflicts with the html's own css.

In general html notes come from web pages which are all very different, so trying to apply a uniform style to all of them is not doable. You can imagine for example a div with a black background, and a css that forces the font to be black too, making the text unreadable

**Comment by personalizedrefrigerator** [comment]
This was originally requested on the forum, for Evernote imports: https://discourse.joplinapp.org/t/feature-request-use-custom-css-userstyle-css-in-evernote-notes-imported-as-html-shown-in-iframe/34531/7.

(I'm unsure why users are importing as HTML instead of as markdown).

> You can imagine for example a div with a black background, and a css that forces the font to be black too, making the text unreadable

As custom CSS is set by the user, we could add an additional class to `<html>` in the markdown viewer (e.g. `markdown-viewer`. Users could then write custom CSS similar to the following:
```css
:root.markdown-viewer {
    /*Styles to apply to markdown only*/
}
```

As such, it should be possible to support this (and allow users to have different custom CSS for HTML and markdown notes).

Currently custom CSS is only sometimes applied (in the rich text editor after switching from a markdown note, presumably because state is not being cleared). I've updated the issue to reflect this.
