### ISSUE TITLE
Clicking [X] to close window does not close Joplin

### ISSUE THREAD

**Issue by RodBarnes** [laurent22/joplin#9571]
### Operating system

Windows

### Joplin version

2.13.9

### Desktop version info

Joplin 2.13.9 (prod, win32)

Client ID: cfed8248927846bc80c3246ceee2f6c4
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 1bbec44

### Current behaviour

Clicking the [X] to close the window does not close the app.  After 5 minutes, the processes are still running.  The window closes but the app remains running in the background.  However, selecting "File > Quit" closes correctly closes the window and the application.

Joplin is open and processes running, click on [X]:
![01 Joplin open with running processes](https://github.com/laurent22/joplin/assets/3944607/773a3454-1a2f-4f86-bca3-fc0a980b6d2c)

Joplin window closes but processes still running:
![02 Closed with  X  but still running](https://github.com/laurent22/joplin/assets/3944607/ed833082-b99e-411d-a42c-6c6114a92395)

Joplin is open and processes still running -- it initially fires up a new process but then that one goes away and only the original is left.  Click "File > Quit".
![03 Opened again](https://github.com/laurent22/joplin/assets/3944607/97aae494-482e-45c4-9371-9cb95dd60c03)

Joplin window is closed and processes are now terminated.
![04 Closed with File-Quit and no processes](https://github.com/laurent22/joplin/assets/3944607/5f387a8a-a4dc-4f9b-8c22-24c77debfb17)

### Expected behaviour

Clicking [X] should produce the same behavior as "File > Quit"; i.e., closing both the window and terminating the application.

**Comment by personalizedrefrigerator** [comment]
On Windows, the "Show tray icon" setting (under "Settings" >  "Application") should change this behavior:

![screenshot](https://github.com/laurent22/joplin/assets/46334387/007040b2-b0ec-4445-bfd7-050d3a884c79)

**Comment by RodBarnes** [comment]
@personalizedrefrigerator: Thanks for pointing that out.  Makes sense but it's kind of hidden given that most tray icons are also hidden by default.  Yet, not sure how that would be made more visible to the user....  Maybe a first-time, one-time notice when first using [X] to inform the user it is still in the tray?

Closing as "not bug".
