### ISSUE TITLE
Joplin Server. Add linux/arm64 support during docker build.

### ISSUE THREAD

**Issue by vyuzhanin** [laurent22/joplin#9576]
### Operating system

macOS

### Joplin version

joplin/server:latest

### Desktop version info

As you know the latest Apple devices is ARM-64 based only. That means that when I try to pull the [joplin/server:latest](https://hub.docker.com/layers/joplin/server/latest/images/sha256-5d48bbf9a4b0942560724c9c1a3b68d3dc5aa20cf110972219561ca395f9ad36?context=explore) image then the `Docker Desktop.app` shows me the following error:

<img width="307" alt="image" src="https://github.com/laurent22/joplin/assets/596514/b7d434f8-2863-4663-b0d7-852b32b47632">

As example I've found the following docker build command from [this](https://www.padok.fr/en/blog/docker-arm-architectures) article. It builds the images for linux/amd64 and linux/arm64 platforms as well:

```shell
# Only build
docker build --platform linux/amd64,linux/arm64 -t <image-tag> .
# When you need to push
docker build --platform linux/amd64,linux/arm64 -t <image-tag> --push .
```

**Comment by iraklis10** [comment]
Tried adding the platform designation to my docker-compose.yml

```
image: joplin/server:latest
platform: linux/arm64
```

but got

`image with reference docker.io/joplin/server:latest was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64`

on a raspberry pi

**Comment by rootiam** [comment]
Wanted to use Joplin on a Hetzner arm64 machine. 

Throws an error at the moment:
" ! joplin-server The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested"

**Comment by marekhanzlik** [comment]
Please consider adding `arm` support. Servers based on `arm` are standard nowadays. And it would be really great to support them. Thanks

**Comment by marekhanzlik** [comment]
@vyuzhanin from the forum i found out you can use community build  
https://hub.docker.com/r/etechonomy/joplin-server  
(https://discourse.joplinapp.org/t/joplin-server-for-arm64-arm-v7/19958/15)
