### ISSUE TITLE
Exiting Joplin CLI does not start next line prompt on nice newline

### ISSUE THREAD

**Issue by gwpantazes** [laurent22/joplin#958]
### Operating system
- macOS

### Application
- Terminal

Exiting Joplin does not leave a perfect newline and causes a bit of strange line wrapping. Observe the bottom of the Joplin application and running `:exit`

```
                   |│                  │|
...................''------------------''.......................................
:exit
                                                                               georgep:~$ ls
Applications/   Downloads/      Desktop/    Documents/      Library/
georgep:~$
```

Note the position of `georgep:~$` and how the one directly following the Joplin `exit` is very far to the right.

I would want/expect the terminal prompt following an exit to start on a clean new line.

**Comment by tessus** [comment]
I cannot reproduce this. In fact, when I exit the joplin terminal app, no text from the app remains on the screen.

e.g.

before lunching the app:

```
$ joplin
```

after existing the app:

```
$ joplin
$ 
```

**Comment by gwpantazes** [comment]
I just had the idea of uploading an Asciinema if what I’m seeing, I’ll do that soon. A detail that I don’t think should matter, but might, is that I’m using iTerm, which is a third party terminal app. But that shouldn’t affect the output, right?

**Comment by tessus** [comment]
I'm also using iTerm2 Build 3.2.5 on macOS 10.13.6.

**Comment by gwpantazes** [comment]
Looks like this isn't a problem anymore! Closing
