### ISSUE TITLE
Code blocks with blank lines break tables

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#9586]
> [!NOTE]
>
> This is a single-issue version of #9544 (which describes several issues with tables in the rich text editor).
>

### Operating system

Linux

### Joplin version

2.13.9

### Desktop version info

Joplin 2.13.9 (prod, linux)

Client ID: 24b2a961cccf40fe8448cdc0930b6fce
Sync Version: 3
Profile Version: 44
Keychain Supported: No

Revision: 1bbec445d

Freehand Drawing: 2.7.1
RevealJS Integration: 0.6.1
Simple Backup: 1.3.4
Work tracker: 0.0.1

### Current behaviour

1. Create a table with a code block with a blank line in the rich text editor
2. Switch to a different note and back

### Expected behaviour

The code block should not be corrupted.

> [!NOTE]
>
> See https://github.com/laurent22/joplin/issues/9544 for details.
>

**Comment by personalizedrefrigerator** [comment]
For comparison, this is the markdown that was generated by a multi-line code block in a table in Joplin 2.12.19:

![see details below](https://github.com/laurent22/joplin/assets/46334387/845b1142-f69a-4669-b7a3-91a476b2b3f5)

<details>

````
|     |     |
| --- | --- |
| ```javascript<br>function foo() {<br>    // This<br>    <br>    <br>    // is<br>    // a test<br>}<br>``` |     |
|     |     |
````

</details>

**Comment by laurent22** [comment]
I think that may be the same issue I've added here: https://github.com/laurent22/joplin/issues/9595
