### ISSUE TITLE
Feature request: Fulltext search

### ISSUE THREAD

**Issue by jbriales** [laurent22/joplin#959]
At this point I'm certain Joplin has all the fundamental features to be an awesome note app (way better for me than e.g. Evernote).
Yet, I feel it lacks regarding search: Currently a simple LIKE search seems to be done based on word matching.
From my experience, when retrieving notes via several keywords (which I think is quite common), a fulltext search, like the one already natively provided by SQLite, gives a much better usability. What's the potential/feasibility to introduce fulltext search (by note content) in Joplin?

**Comment by jbriales** [comment]
Actually I don't think this is a duplicate of #293 
In #293 you propose having the ability to filter/restrict the search looking at multiple fields, which may be useful, but requires dealing with various note fields/metadata.
Here I argue the content search should be done via a usual fulltext search table, which is much more flexible specially when searching for various keywords that may appear in a given note, but in an unknown order (which I think is the most common scenario). Otherwise, the current search approach only finds "exact" (case-insensitive) matches, which I think makes retrieving notes from keywords much harder.

**Comment by ComputingFroggy** [comment]
+1 for full text search

**Comment by foxmask** [comment]
it's in [progress](https://github.com/laurent22/joplin/tree/full_text_search)

**Comment by foxmask** [comment]
https://github.com/laurent22/joplin/releases/tag/v1.0.119 
"Full Text Search" done
