### ISSUE TITLE
Table with code block in RTE breaks the table

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9595]
### Operating system

Windows

### Joplin version

2.14.0

### Current behaviour

- Switch to RTE
- Create a 2x2 table
- Add this code block to one of the cells

```
public record User(string Name, int Age);

var user = new User("Alice", 30);
// user.Age = 31;  // This line would cause a compilation error
var updatedUser = user with { Age = 31 }; // Creates a new object with the updated age
```

- Select "java" as markup
- Close the code editor
- Switch to Markdown editor
- Switch back to RTE

=> Table is broken

## Creating the table

<img width="957" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/f83fcd8a-2f05-4d6d-b99d-382580b745bb">

## After switching to Markdown then RTE

<img width="957" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/0b4712a4-6220-4b0c-8c26-bc3859c945f9">

**Comment by personalizedrefrigerator** [comment]
I can reproduce this in 2.13.15, but not 2.14.9. As such, I think this has been fixed.

**Comment by laurent22** [comment]
Thanks for checking! Let's close the issue then
