### ISSUE TITLE
Rotation of attached image is lost when the image is resized

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9597]
### Operating system

Windows

### Joplin version

2.13.0

### Current behaviour

- Drag and drop the below image on the RTE
- Don't choose to resize it

=> The rotation is preserved

- Drag and drop the below image on the RTE
- Choose to have it resized

=> The rotation is lost (image is displayed in landscape mode instead of portrait)

[20231224_142837.jpg.zip](https://github.com/laurent22/joplin/files/13762102/20231224_142837.jpg.zip)

The same issue may be happening on mobile too, so it should be checked

**Comment by personalizedrefrigerator** [comment]
Related: https://github.com/laurent22/joplin/issues/8310

**Comment by personalizedrefrigerator** [comment]
I'm uploading another test image for use in creating an upstream bug report:

[testing.jpg.gz](https://github.com/laurent22/joplin/files/14105773/testing.jpg.gz)

This is [the Electron Fiddle I plan to use to report the bug upstream](https://gist.github.com/personalizedrefrigerator/37faf57d2a511ba3f3f7ce3e8f5b10ef).
