### ISSUE TITLE
Copied and pasted text from Firefox to RTE doesn't include images

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9607]
### Operating system

macOS

### Joplin version

2.3.11

### Current behaviour

- Copy some text and images in Firefox
- Paste in the RTE

=> Images are missing

They all have a resource ID though, so something appears to be working but somehow the images are not being displayed

Maybe it's when copying text/images from a page that's behind a login page. In that case the app doesn't have access to the images and it fails.

**Comment by personalizedrefrigerator** [comment]
This seems to work on Linux (Ubuntu 23.10, Joplin v2.13.11), so maybe this is a Windows-only bug?

**Comment by laurent22** [comment]
It was macOS actually (just fixed it), and yes maybe it's macOS only.

**Comment by personalizedrefrigerator** [comment]
With further testing, it seems to work only for _some_ images (copied from https://joplinapp.org/plugins/#tab-all):
![screenshot: Only some images are pasted correctly](https://github.com/laurent22/joplin/assets/46334387/e4ec9679-5c33-450f-8f5b-75105f85b564)
(Alt text added for clarity).

In this case, the non-working images are SVGs.
