### ISSUE TITLE
all notes are deleted if sync dir gets umounted

### ISSUE THREAD

**Issue by rhambach** [laurent22/joplin#961]
### Description

Using a NFS/Samba share as file directory for sync, all data is lost, if the sync directory gets unmounted. This also happens if the sync directory does not exist after unmounting, as the full path it is automatically recreated by Joplin (mkdir -p). This issue has been recently discussed in the comments of #883: see [comment](https://github.com/laurent22/joplin/issues/883#issuecomment-431684233).

### Proposed Solution

- do not automatically create non-existing sync paths, or at least only one level
- ask for confirmation by user before syncing with a completely empty directory. Most likely this is a user error and one might want to read the [FAQ](https://joplin.cozic.net/faq/).

### Operating system

- Linux (Ubuntu 18.04, affects all Linuxes)

### Application

- Desktop,  v1.0.114 (prod, linux)

**Comment by laurent22** [comment]
On the NFS/Samba side is there no config option that can be used to make it return an error if the directory cannot be mounted? As mentioned before, any sync tool (such as "rsync --delete") will erase all the data if you sync with an empty directory, it's not specific to Joplin. So it seems to me it's an error that Samba creates an empty directory if it couldn't mount - it would be better if it doesn't create anything, or deny access to this invalid mount. I'm not familiar at all with this though, are there any option that can be set on NFS/Samba side?

**Comment by rhambach** [comment]
In contrast to my previous comment, it is indeed possible to prevent writing to an unmounted directory (see related [question](https://serverfault.com/questions/570255/prevent-the-possiblity-of-writing-data-to-an-unmounted-mount-point-directory)):

On several file systems (ext2/ext3/ext4), files can be flagged as immutable using [chattr](https://en.wikipedia.org/wiki/Chattr). This can be used to prevent any changes of the mount point directory if not mounted - and thus also the sync.
```
sudo chattr +i /path/to/mount/point
```
However:
- After using Linux for 15+ years I was not aware of this possibility. It is likely to be omitted.
- I still deleted all notebooks by accident during the tests - a user prompt before with an empty directory would still be highly desirable.

**Comment by mic704b** [comment]
The syncing is great but it is very easy to lose all notes. As the above comments, I also expected the behaviour to be based on whether the sync folder exists. Eg something like:

If the sync folder doesn't exist then either:
  a) do nothing -- wait for it to come back;  or
  b) create and initialise a new sync folder

If the sync folder does exist, then either:
  c) if it is empty then delete all notes (perhaps with a warning?)
  d) if it is not empty, then sync like usual

**Comment by laurent22** [comment]
No fix for this, but there's now a fail-safe.
