### ISSUE TITLE
Error with WebDAV synchronization on the Android app <> QNAP NAS TS-433

### ISSUE THREAD

**Issue by xvs03** [laurent22/joplin#9611]
### Operating system

Android

### Joplin version

2.13.10 ;  Android 11 ; QNAP QTS 5.1.4.2596

### Desktop version info

Windows 10 ; Joplin 2.13.11

### Current behaviour

WebDAV share folder for Joplin set up on QNAP NAS.
Synchronization settings Windows=Android; path,user,password
When checking the synchronization settings, the following error is displayed in the Android app:
Access denied: Please check username and password(401)
see logs

### Expected behaviour

Error-free WebDav synchronization with the Android app

### Logs

[mobile-log.log](https://github.com/laurent22/joplin/files/13780799/mobile-log.log)

**Comment by roman-r-m** [comment]
Double-check your username and password. On my phone Android sometimes tries to capitalize the 1st letter.
If that doesn't work then maybe check if there are any details in logs on your server.
