### ISSUE TITLE
Joplin still syncs deleted notes

### ISSUE THREAD

**Issue by ericswpark** [laurent22/joplin#9623]
### Operating system

Windows

### Joplin version

2.13.9

### Desktop version info

Joplin 2.13.9 (prod, win32)

Client ID: ce347a534a274c8f9a154a4ff68bb0bd
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 1bbec44

Templates: 2.4.0

### Current behaviour

I had a notebook with around 700 entries (about 5000+ items inside due to history). Because the sync was getting a bit slow, I exported all but 20 of the notes and then deleted them from Joplin. Then I ran a sync again to make sure they were deleted server-side (running selfhosted Joplin Cloud).

However, while setting up Joplin on a new device today, I noticed it still synced over 5k+ entries until the 20 or so notes started to show up.

![image](https://github.com/laurent22/joplin/assets/13326074/34cee9a6-f580-4bd9-8db1-531741c6ab40)

### Expected behaviour

Joplin should prune the deleted entries and not sync them over before discarding them anyway

**Comment by JackGruber** [comment]
This is due to the note history. The deleted notes are only marked as deleted and are only deleted after the history time. 
https://joplinapp.org/help/apps/note_history

**Comment by ericswpark** [comment]
@JackGruber thanks, but I also set the note history setting to 7 days, so in theory it should be considerably less than the 5k items synced, considering that most of the items were written ages ago.

EDIT: previously it was set to the max of 730 days so the 5k items synced makes sense with that setting. No idea why it won't discard the items with the new setting though.

**Comment by laurent22** [comment]
I don't know if that's the issue, but normally all deletion actions will be processed even if it means they are a no-op (if the note is already gone). It won't download a note that has been deleted since the note really is gone.

**Comment by ericswpark** [comment]
@laurent22 then does that mean the fetched items count will always grow, even when I delete notes? Because every time I set up or restore a device Joplin takes ages downloading 7,000 items that doesn't exist.

EDIT: this is a problem on any platform. I just set up Joplin on Android and the exact same behavior occurred. Joplin fetched, decrypted, and then threw away thousands and thousands of notes.

**Comment by ericswpark** [comment]
What can I do to troubleshoot this? I'm not sure why Joplin is still syncing 7k+ items, when I only have 50-100 notes *total*. This makes syncing with Joplin quite painful when setting up new devices.

**Comment by ericswpark** [comment]
Here's the sync result after setting up a new device:

![image](https://github.com/laurent22/joplin/assets/13326074/843aa3e3-40fc-457b-88d0-85fdbf7c0e02)

I currently have 48 notes in total, so I'm not sure why it's still fetching 5k items. How do I figure out what they are so I can prune them? I've already cleared out attachments from other devices before setting up fresh so it can't be the attachments.

**Comment by ericswpark** [comment]
Still an issue

**Comment by ericswpark** [comment]
Still an issue

**Comment by ericswpark** [comment]
Still an issue

**Comment by ericswpark** [comment]
Unfortunately I will no longer be able to provide repros for this issue as it got unbearable to the point where I had to switch to an alternative note app. Feel free to close, but I will not prompt the stale bot to keep the issue open if it retags it as stale.
