### ISSUE TITLE
Editing a note opens it scrolled down

### ISSUE THREAD

**Issue by robme** [laurent22/joplin#9630]
### Operating system

Android

### Joplin version

2.13.10

### Current behaviour

1. Open a note which has enough content to require scrolling and begin editing it.
2. The note opens scrolled down.
3. Add some text at the top or bottom.
4. Close the note.
5. Open the note again for editing.
6. The note again opens halfway down in a place which the cursor was not before.

It always opens scrolled to the exact same place. It started happening after the last update, I wonder if it's a feature that isn't working correctly since it seems to be trying to remember where to scroll to but it gets it totally wrong. I don't know how/why it has remembered this location halfway down the page.

### Expected behaviour

It used to open the editor at the top, so that would be preferable. Or if it could resume in the same location then that would also be fine, but at the moment it does neither.

**Comment by personalizedrefrigerator** [comment]
This should be fixed by https://github.com/laurent22/joplin/commit/d4157e14fe3929012a57a3a60b28f79ac6afccf4. However, it doesn't seem to be in an Android release yet (the last Android release is from about a month ago).

**Comment by robme** [comment]
Still a problem on the current Android version of Joplin.

**Comment by robme** [comment]
Still happens.

**Comment by robme** [comment]
Yeah I think the fix got into the release now, haven't seen this happening.

**Comment by bartekmotyl** [comment]
I am a bit confused, because my experience on Android is quite different. My notes are in markdown and lots of them are pretty long (usually a long list of checkboxes). When I open the note in read-only mode (markdown view, not source), scroll down to some place and click edit icon, the editor starts at the top of the file (editing markdown source, as expected). 

Joplin 3.1.8 (prod, android)

**Comment by robme** [comment]
This is resolved and closed @bartekmotyl

**Comment by bartekmotyl** [comment]
Can you elaborate, @robme ? You mean that the behavior I describe is resolved in the android app? I can still reproduce it, even now, being on  version 3.1.8.

**Comment by robme** [comment]
I misunderstood you. I thought you were describing the expected behaviour, i.e. saying it's not a bug, because you said this:

> the editor starts at the top of the file (editing markdown source, as expected).

That's the intended behaviour. When you edit a note, it opens at the top, always.
The bug I reported was that it was opening scrolled down the page a random amount.

**Comment by bartekmotyl** [comment]
Ok, thanks for clarification. 


> That's the intended behaviour. When you edit a note, it opens at the top, always.

I actually find it very annoying (especially for longer notes) but I understand it does not fit here. 
I will file a feature request.
