### ISSUE TITLE
After clicking the edit button, the content area is blank and cannot be entered.

### ISSUE THREAD

**Issue by aghinouz** [laurent22/joplin#9638]
### Operating system

Android

### Joplin version

2.13.10

### Current behaviour

1. Open Joplin.
2. Open a note.
3. Click the edit button.
4. It is now blank and cannot be edited.
![Screenshot_20231231-194645](https://github.com/laurent22/joplin/assets/61457649/dc048cde-5bb6-4dbc-82e0-d44a2f28eeaa)

### Expected behaviour

After clicking the edit button, the content should be displayed and editable as shown below instead of being blank as shown above.
![Screenshot_20231231-194656_Joplin](https://github.com/laurent22/joplin/assets/61457649/a8d8f67c-0894-40be-b81e-e73486ae43c4)

### Logs

Platform: Android 9
[joplin.log](https://github.com/laurent22/joplin/files/13801136/joplin.log)

**Comment by personalizedrefrigerator** [comment]
Please check whether there's an update available for the "Android System WebView" in the app store &mdash; Joplin uses a `WebView` to display a CodeMirror-based note editor. (The editor may be incompatible with older `WebView` versions).

**Comment by aghinouz** [comment]
Thank you very much. I found that the system webview version is 74.0.3729.136. Upgrading to the latest version solved the problem.
