### ISSUE TITLE
Profile switcher unavailable

### ISSUE THREAD

**Issue by Emmanuel-L** [laurent22/joplin#9641]
### Operating system

iOS

### Joplin version

12.13.10

### Current behaviour

1. Click on burger menu
2. Then there is no entry to switch of profile

### Expected behaviour

I can create a personal profile in desktop application and swith into it. However I cannot do the same from the iOS app although it should be available according to this pull request [#7586](https://github.com/laurent22/joplin/pull/7586).

I want to :

1. separate my personal notes from the notes of my other activities
2. synchronize personal and other notes at the same time
3. switch a note to personal profile (Ok if not done, I could export/import them)

Thanks for support and this great app.

**Comment by laurent22** [comment]
Hello, if you go under Configuration => Tools, you can create new profiles. Then you'll have a profile switcher in the sidebar
