### ISSUE TITLE
docker-compose.server.yml shoud not expose Postgres port 5432 publicly

### ISSUE THREAD

**Issue by oli-arborum** [laurent22/joplin#9645]
### Operating system

Linux

### Joplin version

Joplin Server 2.10.6

### Current behaviour

The Joplin Server configuration in `docker-compose.server.yml` does not need to (and should not) expose port 5432 publicly. In Compose, containers that -- like Postgres -- expose ports can be reached by service-to-service communication inside the Compose network via that port. Thus, additionally exposing the Postgres server publicly might raise security issues, because the database server can be accessed directly (possibly from the internet, when no firewall is active).

Additionally, when using a reverse proxy (like Jason Wilder's nginx-proxy or Trafaek) it is even not necessary to expose port 22300 publicly. Reason: For the proxy-internal network this port is available as well (see explanation above). Thus, the reverse proxy just must be made to use this port (e.g. for nginx-proxy by setting the environment variable VIRTUAL_PORT=22300).

### Expected behaviour

The section "`ports`" should be removed from the service "`db`" in `docker-compose.server.yml`.

Optional: The section "`ports`" should be removed from the service "`app`" in `docker-compose.server.yml` (when using a reverse proxy and not accessing the server directly via port 22300).

**Comment by laurent22** [comment]
Hello, if you have any suggestions on how to update this please create a pull request

**Comment by oli-arborum** [comment]
see #9661
