### ISSUE TITLE
Search not working correctly

### ISSUE THREAD

**Issue by Killea** [laurent22/joplin#9648]
### Operating system

Windows

### Joplin version

2.13.12

### Desktop version info

Joplin 2.13.12 (prod, win32)
Client ID: edb63642a2024e1ca7cd4f9d52e0039a
rever：e027cdc

### Current behaviour

![image](https://github.com/laurent22/joplin/assets/5551824/a2c9c2fe-9f92-4eef-8fc6-83deaad14ff0)
![image](https://github.com/laurent22/joplin/assets/5551824/5805e788-823e-4a7d-9858-0608f4a4f5a7)
When searching 'test', it's ok; when searching 'tes', you cannot get the correct result.

### Expected behaviour

get the result for 'tes'.

**Comment by JackGruber** [comment]
To search substrings you have to use a wildcard search, like `tes*`
![grafik](https://github.com/laurent22/joplin/assets/24863925/fab1ab49-3820-4ebc-b760-b34249b8d803)
![grafik](https://github.com/laurent22/joplin/assets/24863925/f700c950-a6cb-422b-8b80-71407afbd285)

https://joplinapp.org/help/apps/search
