### ISSUE TITLE
the top tips content block in mac os desktop can not close

### ISSUE THREAD

**Issue by chenqy9** [laurent22/joplin#9651]
### Operating system

macOS

### Joplin version

Joplin 2.13.12 (prod, darwin)

### Desktop version info

Joplin 2.13.12 (prod, darwin)

Client ID: fde03f7bad6b46fa81f94aadbc8b2c86
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: e027cdc

### Current behaviour

when there are some items sync or decrypt failed, joplin would display a tips block on the top of the desktop app to show the message. The question is that it seems no way to close the tips even though I have got the message. 
![image](https://github.com/laurent22/joplin/assets/10264688/390a1818-bbd9-4ccf-8b8e-7238781122c6)

### Expected behaviour

user can close the top tips block

**Comment by personalizedrefrigerator** [comment]
I'm linking to https://github.com/laurent22/joplin/issues/9669, which is a somewhat-related issue for mobile.
