### ISSUE TITLE
Android app doesn't ask to resize cropped pictures

### ISSUE THREAD

**Issue by benintech** [laurent22/joplin#9653]
### Operating system

Android

### Joplin version

2.13.10

### Current behaviour

1. If you import pictures larger than 1920p, Joplin proposes to reduce it, both on mobile and desktop apps. Works fine
2. If however on Android you import a picture previously cropped, but still larger than 1920p, Android/Joplin app doesn't propose to reduce it anymore
3. A workaround is to sync the cropped picture with your desktop, and use the desktop app to import it. The desktop app still proposes to reduce it, even if the picture has previously been cropped.

### Expected behaviour

Joplin on Android should propose to reduce all images larger than 1920p, even the ones that have been cropped.

I think this issue has been discussed [here](https://discourse.joplinapp.org/t/why-doesnt-the-mobile-app-ask-to-resize-image-down-to-1920p/32188/17), but the discussion has been close due to lack of activity.

**Comment by benintech** [comment]
Not fixed

**Comment by personalizedrefrigerator** [comment]
Related to https://github.com/laurent22/joplin/issues/8856

**Comment by benintech** [comment]
Closing it, because it's the same as https://github.com/laurent22/joplin/issues/8856
