### ISSUE TITLE
Markdown Editor/Rich Text Editor: Markdown is not rendered automatically, when it starts with an configuration

### ISSUE THREAD

**Issue by faneauvi** [laurent22/joplin#9668]
### Operating system

Windows

### Joplin version

2.13.12

### Desktop version info

Joplin 2.13.12 (prod, win32)

Client ID: b8bfa8b50f314322bd51d9e2be42ee1d
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: e027cdc

Metis: 0.1.5

### Current behaviour

1. When you are in Markdown Editor and have a mermaid diagram starting with an config line, then it is not rendered automatically, only the mermaid definition is shown as normal text. Example Code:
```
'''mermaid
%%{init: {'theme':'base', 'themeVariables': {'primaryColor': '#FFBB00'}}}%%
gantt
  title Roadmap 2024
  item : 2024-01-01, 4w
'''
```
2. When you remove the config line and add it again, the graph is rendered until you switch to Rich Text Editor or restart Joplin.
3. When you are in Rich Text Editor and have a mermaid diagram starting with an config line, then it is not rendered automatically, only the mermaid definition is shown as normal text. Example Code, see in point 1.
4. When you open the Edit dialog with an double click and add close it again with Ok without any change, the graph is rendered until you switch to Markdown Editor or restart Joplin.

### Expected behaviour

The mermaid diagramm is always rendered automatically.

**Comment by personalizedrefrigerator** [comment]
Might be fixed by https://github.com/laurent22/joplin/commit/4e09b6f2a478cf740f74425c30f1fcc92c0a923f, which changes how the Mermaid library is initialized.

This change should be in Joplin ≥ 2.14.6.

**Comment by faneauvi** [comment]
Thank you very much, I will test it with the next update and provide a feedback :-)

**Comment by faneauvi** [comment]
Just as a hint, I found as a workaround, that it works, if there is a (dummy) diagram without a config line in the same note before/above the diagram with a config line. Maybe the workaround help somebody else as well in the meantime.
Dummy Example:
```
'''mermaid
gantt
	title dummy
'''
```
Still waiting for a productive 2.14.x (>6) for final feedback.

**Comment by faneauvi** [comment]
After the update to 2.14.17 it looks like the issue is solved as @personalizedrefrigerator has expected.
Thank you very much!
