### ISSUE TITLE
[Feature Request] Undo in Title

### ISSUE THREAD

**Issue by contradictioned** [laurent22/joplin#969]
### Operating system

- macOS

### Application

- Desktop

I just noticed that it is not possible to _undo_ changes in the title of a note. For example, when you accidentally delete the title, you cannot revert that. In contrast, when editing the note in the editor, it CMD + Z reverts the last changes.

I am not sure, if other platforms have the same behaviour. If you are interested, I'd look into making the title input undoable.

**Comment by laurent22** [comment]
Yes I would welcome a pull request for that if you can figure out how to get it working.

**Comment by contradictioned** [comment]
When doing `npm install` in ElectronClient/app, I get no matching versions of katex, like here https://ci.appveyor.com/project/laurent22/joplin/builds/20133437

So I guess, I'll try with katex 0.10.0 and do not add this package.json to the commit (after I hopefully figured out the original problem 😉)

**Comment by contradictioned** [comment]
... after solving that katex problem, I ran into the same as in #467, as the sqlite version in that package.json is still `"^3.1.13"`. Is this intended?
I have not thoroughly tested it, but the ElectronClient seems to build and run fine with `"^4.0.0."`.

**Comment by laurent22** [comment]
It seems the Katex version needs to be fixed then. For sqlite, there's no known problem with that particular version in Electron. If it works for you with v4, maybe indeed set it to that for development.
