### ISSUE TITLE
What was remotely deleted during sync?

### ISSUE THREAD

**Issue by BetaMaxHeadroom** [laurent22/joplin#9690]
### Operating system

Windows

### Joplin version

2.13.13

### Desktop version info

Joplin 2.13.13 (prod, win32)

Client ID: REMOVED
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: c3cdeeb

Combine notes: 1.0.1
Conflict Resolution: 1.2.3
Menu items, Shortcuts, Toolbar icons: 1.1.0
Note Tabs: 1.4.0
Outline: 1.5.10
Rich Markdown: 0.13.3
Simple Backup: 1.3.3
Tags Generator: 1.0.0

### Current behaviour

I setup Joplin Notes to automatically sync to Dropbox every 10 minutes. 

I turned on my pc today, and the sync status stated that 2 remote items were deleted. I don't recall deleting anything the last time that I used Joplin. 

1. Could this be from some update? 
 
2. Could it be that Dropbox purged some items, and Joplin didn't actually remotely delete anything?

3. Are there any plugins that could help me identify just exactly what items were changed from the latest sync? 

4. Is there a way for me to approve/deny the remote deletion of items before they are deleted?

### Expected behaviour

I expected the status to simply state that the sync was complete without anything being remotely deleted since I didn't use my laptop all weekend.

**Comment by laurent22** [comment]
It may have deleted expired revisions

**Comment by BetaMaxHeadroom** [comment]
Thank you for responding so quickly. Can you please let me know how I could validate this?

Also, can you help me understand what you mean by "expired revisions"? I am inferring this to mean that these are items that were scheduled to be removed from dropbox because I deleted something about a month ago. I just want to make certain I fully understand. Sorry if I'm being a bother. 

Edit: I should have looked this up before responding https://joplinapp.org/help/dev/spec/history/

**Comment by laurent22** [comment]
You can check the log for more information: https://joplinapp.org/debugging but it's possible you will have to enable dev mode to see all the sync operations

**Comment by Yolakalemowa** [comment]
hi @laurent22 ... please forgive me for asking my question here. I didn't want to create a new account on "discourse". I just wanted to ask why Joplin isn't updated on Chocolatey for windows? And whether there are plans to keep it updated from there?

**Comment by laurent22** [comment]
Could create a new issue about this please? Indeed if it's not maintained anymore we need to do something about it

**Comment by Yolakalemowa** [comment]
> Could create a new issue about this please? Indeed if it's not maintained anymore we need to do something about it

I'm a top notch noob but I tired creating an issue no please check :)
thanks

**Comment by laurent22** [comment]
Where do you create it? Could you send a screenshot of it please?

We seem to have problems with issues that we can't see but not sure if that's the problem

**Comment by BetaMaxHeadroom** [comment]
@laurent22 can you please direct me to a page that explains how I would interpret the sync report? This isn't very intuitive.
