### ISSUE TITLE
"[toc]" tag is occasionally replaced with the generated table of contents

### ISSUE THREAD

**Issue by kendalharland** [laurent22/joplin#9692]
### Operating system

MacOS

### Joplin version

2.13.13

### Desktop version info

Joplin 2.13.13 (prod, darwin)

Client ID: 83c9cfccec9a4920b0eef5da714bc2bd
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: c3cdeeb

### Current behaviour

1. Create a note
2. Add some content with several subheadings
3. Add "[toc]" to the top of the file.
4. Save the note

### Expected behaviour

Expected: "[toc]" should stay at the top of the file permanently.

Actual: After a while, somewhere between opening/closing the note, syncing it to another computer, etc... the "[toc]" tag is overwritten with the generated list of markdown links that make up the table of contents, allowing the contents to become stale as the note is modified in the future.

**Comment by personalizedrefrigerator** [comment]
Related: https://github.com/laurent22/joplin/issues/8482 (though perhaps a different issue).

**Comment by kendalharland** [comment]
I believe it's the same issue, thanks for linking. I didn't realize `[toc]` is not compatible with the wysiwyg editor. If there are no plans to make it compatible, this can be closed as WAI.   

I also see that I can use https://github.com/cqroot/joplin-outline as an alternative to `[toc]` and that should work fine for me.
