### ISSUE TITLE
clip url  notwork

### ISSUE THREAD

**Issue by mh710774265** [laurent22/joplin#9702]
### Operating system

Linux myname 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Joplin version

Joplin Server v2.13.3

### Desktop version info

joplin 2.13.13

### Current behaviour
Chromium 版本 120.0.6099.199（正式版本）snap （64 位）
Microsoft Edge 版本 121.0.2277.4 (正式版本) beta (64 位)

clip  markdown or html  not work
https://www.taterli.com/3213/
https://www.taterli.com/1206/

**Comment by laurent22** [comment]
It works for me but this website is incredibly slow so you may have to wait for a minute or two for everything to be downloaded and then the note will be created

**Comment by mh710774265** [comment]
I created an http after storing it through the browser and it worked, waiting didn't work
