### ISSUE TITLE
Note text in joplin is not updated when editing and saving the note with vscode extension

### ISSUE THREAD

**Issue by JonathanPlasse** [laurent22/joplin#9704]
### Operating system

Linux

### Joplin version

2.13.13

### Desktop version info

Joplin 2.13.13 (prod, linux)

Client ID: 8aaf78f05ca94729a9f2c948ed015ed6
Sync Version: 3
Profile Version: 44
Keychain Supported: No

Revision: c3cdeeb

### Current behaviour

1. Create a note in joplin
2. Edit the note in vscode
3. Save the note
4. The note is not updated in Joplin
5. Go to another note
6. Go back to the note
7. The note is now updated

### Expected behaviour

The note should be refreshed with the text saved in vscode immediately without having to go to another note first.

**Comment by JackGruber** [comment]
Duplicate https://github.com/laurent22/joplin/issues/5955

**Comment by JonathanPlasse** [comment]
Sorry for the noise.
Closing in favor #5955
