### ISSUE TITLE
Text layout corrupted for non-standard symbols

### ISSUE THREAD

**Issue by h-b** [laurent22/joplin#971]
### Operating system

- macOS 10.14.1

### Application

- Desktop 1.0.114

When using exotic unicode symbols like ⌘, from this cursor position on the cursor does not blink at the correct position. The delta accumulates when using more such symbols, so the cursor blinks not where text is really inserted when you type, but more to the left. In the same way a selection does not mark the shown text correctly. This is of course annoying when editing such text.

For example after typing ⌘⌘⌘⌘⌘⌘⌘, the cursor is not located at the right end of the text, but in the middle of it, i. e. after the first four symbols ⌘⌘⌘⌘|⌘⌘⌘ - but when you continue to type, text is appended at the end and not where the cursor is shown.

**Comment by h-b** [comment]
I justed tested under Windows with version 1.0.168. This is reproducable with various symbols. For example if you type ꙱ the cursor is not at the correct position if you proceed to type.

I regard this as a major problem, because it makes editing of a line of text that includes such a symbol awkard. For example I have a table of keyboard shortcuts for my Mac which is nearly impossible to edit.

**Comment by laurent22** [comment]
There's no fix for this since the editor only support monospace fonts. It might be fixed when the editor is changed.
