### ISSUE TITLE
second line cannot be mouse hovered. 

### ISSUE THREAD

**Issue by hunter-xue** [laurent22/joplin#9715]
### Operating system

macOS

### Joplin version

All versions

### Desktop version info

Joplin 2.13.14 (prod, darwin)

客户端 ID: 79cba8b62b0d4f78aed631a12ab49fc3
同步版本：3
配置文件版本：44
支持的密钥链：是

修订：174c5f4

Enhancement: 1.2.1
macOS theme: 1.3.13

### Current behaviour

![Joplin](https://github.com/laurent22/joplin/assets/4905312/7e3d242e-edbc-40fa-9fbf-64ca0c485685)

### Expected behaviour

second line CAN be mouse hovered correctly.

**Comment by personalizedrefrigerator** [comment]
Related: https://github.com/andrejilderda/joplin-macos-native-theme/issues/110
