### ISSUE TITLE
Force reset of synchronization

### ISSUE THREAD

**Issue by ronsmits** [laurent22/joplin#972]
### Operating system
- Android

### Application
- Mobile

I have a lot of problems with the synchronization. Only solution I have found sofar is uninstalling the app and reinstalling. Make it possible to force a total sync.

**Comment by foxmask** [comment]
what kind of sync problem ?
when it's the first sync on mobile, it's take a very long time. [On desktop there is a workaround](https://discourse.joplin.cozic.net/t/workaround-for-slow-initial-bulk-sync-after-evernote-import/746) to avoid to loose patient ;)

**Comment by ronsmits** [comment]
This was not the first sync on mobile. The synchronisation started (according to the menu) and basically never finished. It just sat on "state: In progress" for two hours. It never did anything else. 
After 2 hours I cancelled it, started it again and the same happened. That is when I decided to uninstall the app, and reinstall. The problem  has not occurred since.

**Comment by ronsmits** [comment]
nothing at all.

**Comment by laurent22** [comment]
Unfortunately cannot be replicated.
