### ISSUE TITLE
Searching within an open note is buggy

### ISSUE THREAD

**Issue by BigErn77** [laurent22/joplin#9720]
### Operating system

macOS

### Joplin version

2.13.14

### Desktop version info

Joplin for Desktop

Copyright © 2016-2024 Laurent Cozic
Joplin 2.13.14 (prod, darwin)

Client ID: 4aca3a9777c34272a24dd81ef9b39ee8
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 174c5f4

### Current behaviour

I have notes that are many pages of math and numbers. If I search for a particular number; say, 23, it will give me way more search results than are actually there. As a workaround, I have to type space and then backspace to get the correct number of search results.

### Expected behaviour

Give the correct number of search results.

**Comment by BigErn77** [comment]
The issue is still there. No one has even addressed the bug at all.

**Comment by hulxv** [comment]
Can you preview your problem with something like a video or image to know what actually happens?

**Comment by BigErn77** [comment]
> Can you preview your problem with something like a video or image to know what actually happens?

![IMG_20240308_012452021](https://github.com/laurent22/joplin/assets/20691014/f31328d3-25ec-4dac-95db-f01f0c06cbc0)

Here's a screenshot of one of my notes. You can see that I searched for the number 142, but it only acknowledges the '1', hence all the highlighted '1's. It doesn't happen all the time, only occasionally. Might want to double check the search code.
