### ISSUE TITLE
when enter an http site into HTML tag <font> , the TAG is not working

### ISSUE THREAD

**Issue by MatanOstrovsky** [laurent22/joplin#9727]
### Operating system

macOS

### Joplin version

unknown

### Current behaviour

when enter http link with green color
<font color = green>https://github.com/laurent22/joplin/issues/new?assignees=&labels=bug&projects=&template=BUG_REPORT.yml</font> 

its not set the color to Green

But, if I do like this (remove the http...):
<font color = green>github.com/laurent22/joplin/issues/new?assignees=&labels=bug&projects=&template=BUG_REPORT.yml</font> 

it work and the font is in Green.

### Expected behaviour

expecting the below to set the font to be in green

<font color = green>https://github.com/laurent22/joplin/issues/new?assignees=&labels=bug&projects=&template=BUG_REPORT.yml</font> 
![Screenshot 2024-01-15 at 17 59 19](https:/
![Screenshot 2024-01-15 at 18 00 34](https://github.com/laurent22/joplin/assets/156690857/6c78ceed-771b-433b-a439-af48948dec5f)
/github.com/laurent22/joplin/assets/156690857/64f296ca-bd8a-42b1-a203-c2430e6a87fb)

**Comment by MatanOstrovsky** [comment]
now I found the version:
version: 2.13.12

**Comment by Daeraxa** [comment]
Do you have the `linkify` Markdown extension turned on? That extension wraps any "unlinked" URLs in `<a>` tags in the rendered markdown so what you need to style isn't `<font>` but `<font><a>` which would need to be done in your CSS files. Alternatively you can just turn off linkify in your settings and it will work as you expect.

![image](https://github.com/laurent22/joplin/assets/58074586/b78854df-1bcb-4b23-a4d0-88b10fa9e900)
