### ISSUE TITLE
In Rich Text Editor, deleting a non-code character after inline code deletes an extra character

### ISSUE THREAD

**Issue by MMachado05** [laurent22/joplin#9729]
### Operating system

Linux

### Joplin version

2.13.8, persists on 2.13.15

### Current behaviour

1. Open desktop Joplin with the Rich Editor view.
2. Select the option to create an inline code snippet, begin typing. Example: `hello`
3. After an arbitrary amount of characters have been entered, use the right arrow key twice to exit the inline code block (I am assuming needing to press right-arrow twice is the expected behavior to leave the inline code block). Cursor should look like this: [ `hello`| ], NOT [ `hello` | ] with a space.
4. type in a character. Example: `hello`s|
5. Press the backspace key with the cursor placed after the new character.
6. Both the first character outside of the inline code block *and* the last character of the incline code block will be deleted. Example: `hello`s| → `hell`|

### Expected behaviour

At step 6, the cursor should only delete the last character inputted. Ideally, it would also stay *out* of the inline codeblock by default, until the user hit left-arrow to enter it manually.

### Logs

N/A

**Comment by futuremotiondev** [comment]
Also experiencing this bug.

**Comment by MMachado05** [comment]
I'm also experiencing similar strange behavior with other "text style" features, such as bold text and italic text. Maybe it has something to do with how the rich editor treats markdown text behind the scenes with respect to cursor placement?

**Comment by MMachado05** [comment]
After updating to 2.13.15, the bug persists.

**Comment by personalizedrefrigerator** [comment]
A related change was made in https://github.com/laurent22/joplin/commit/24776ee6cec5da0997bac02f7cd8901eb2158e46 &mdash; this [seems to be fixed in 2.14.12!](https://github.com/laurent22/joplin/releases/tag/v2.14.12)

**Comment by MMachado05** [comment]
Fixed by most recent latest release, 2.14.17! 🥳
