### ISSUE TITLE
plugin can not  install 

### ISSUE THREAD

**Issue by song-dq** [laurent22/joplin#9736]
### Operating system

macOS

### Joplin version

2.13.15

### Current behaviour

<img width="260" alt="Snipaste_2024-01-17_09-39-08" src="https://github.com/laurent22/joplin/assets/46775141/78de7045-12ba-4197-8d97-5b9f5f7f9d62">

### Expected behaviour

If the network is unavailable, manual installation method is provided

**Comment by JackGruber** [comment]
You can already install plugins manually/offline

- Download the jpl file (Can be found under `Browse all plugins` or on side from the plugin author)
- Install JPL file

![grafik](https://github.com/laurent22/joplin/assets/24863925/170c2da7-817f-462f-89ab-5953b64f117f)

**Comment by song-dq** [comment]
> You can already install plugins manually/offline
> 
> * Download the jpl file (Can be found under `Browse all plugins` or on side from the plugin author)
> * Install JPL file
> 
> ![grafik](https://private-user-images.githubusercontent.com/24863925/297284281-170c2da7-817f-462f-89ab-5953b64f117f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NzYwNDMsIm5iZiI6MTcwNTQ3NTc0MywicGF0aCI6Ii8yNDg2MzkyNS8yOTcyODQyODEtMTcwYzJkYTctODE3Zi00NjJmLTg5YWItNTk1M2I2NGYxMTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA3MTU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzZDkyZjU3NmM0ODM5ZDNhYmM2ZjQ0ZGQ2ZjUxNjJlM2UwYmJiM2RiZGMyMmZlMDMyYmQwNmY2MGM3M2ZjMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Z0mNUw1DpZ3bXMI39odt90dSroNY13ZY9WoTlihits)

Thanks, but some plugins do not provide jpl files, such as Agenda

**Comment by JackGruber** [comment]
Every plugin, when a plugin has no jpl no installation in joplin is possible unless you build the plugin yourself
