### ISSUE TITLE
cannot create new topic on Joplin Forum

### ISSUE THREAD

**Issue by kklepper** [laurent22/joplin#9746]
### Operating system

Windows

### Joplin version

Joplin 2.13.15 (prod, win32)  

### Desktop version info

Joplin 2.13.15 (prod, win32)  Client ID: 9bbf6dcc44c04a4f984e6acfb8fc73d2 Sync Version: 3 Profile Version: 44 Keychain Supported: Yes  Revision: 7d2c1c0  Calendar: 1.0.0-rc2 Cursor Sync: 2.1.0 Plugin Bundle: 0.5.5 Search & Replace: 2.2.0

### Current behaviour

Tried to create new topic, not for the first time, but the +CreateTopic button  or Ctrl+Enter both have no effect. What to do?

### Expected behaviour

Create new topic, of course.

**Comment by laurent22** [comment]
What happens if you try? Could you post a screenshot of any error you're getting?

**Comment by kklepper** [comment]
It happens nothing. I can click on the button or press Ctrl+Enter, no reaction. I found a draft with only the title and tried several times to no avail.

**Comment by kklepper** [comment]
I uploaded 2 screenshots without problems several times to illustrate the original problem.

**Comment by kklepper** [comment]
![grafik](https://github.com/laurent22/joplin/assets/6130319/494b0e67-e220-4fa5-95af-2943a012b7e1)
![grafik](https://github.com/laurent22/joplin/assets/6130319/1342afd1-ce56-4991-8e5f-d904266de89f)

My text is

The last windows update wrecked my installation so I had to start from scratch. Fortunately, I installed Joplin on a separate disk, so I see all my notebooks. 

Now I am urged to set a master password which I did not have to before. But I cannot even do that, see screenshots.

What to do? I looked at similar issues and found no solution. No cloud backup is a no go.

**Comment by kklepper** [comment]
Any idea?

**Comment by Daeraxa** [comment]
You probably got silenced - if you post your username then we can unsilence you.

**Comment by laurent22** [comment]
The screenshots show that you need to enter the correct password for sync and for decryption. The easiest would probably be to just enter the right passwords, but if you forgot them you need to start over somehow. That will depend on what you are synchronising with.

**Comment by kklepper** [comment]
Thank you, Laurent. I synchronize with joplin cloud, right? 

I found a key called masterkey in my joplin forum password section (I do not have a Joplin section), but it wasn't accepted, so I installed it anew. Now the missing password notice is gone, but I get a new error:

![grafik](https://github.com/laurent22/joplin/assets/6130319/ec6b88c4-0a88-4afc-a3ff-cbf7e9fd9a90)

What to do now? I don't have any information about my Joplin identity. Where can I find it? 

Ah, I found my username and Joplin Cloud password in hidden form under Options/Joplin Cloud. I changed the password to the found masterkey (which had a different number of characters)  to no avail: 

> Invalid username or password (Code 403).

How do I start over then? It would sure be a viable option for me.

**Comment by laurent22** [comment]
Can you login on https://joplincloud.com ? Because that would be the same email and password for synchronisation. You enter the sync details under Config > Synchronisation

**Comment by kklepper** [comment]
Thank you, Laurent. No, I cannot, as I don't know the password. So I set a new one. 

To this end, I clicked on _I forgot my password_ and used the link sent by email (_If we have an account that matches your email, you should receive an email with instructions on how to reset your password shortly. _). The result was _Your password was successfully reset. _

I logged in successfully, made sure I had the same password in _Options->Synchronisation_ and checked successfully. Next I checked the synchronisation of my note, it worked. 

Next I looked at the published link. I expected to get a new link after all this fuss, but I got an error:

![grafik](https://github.com/laurent22/joplin/assets/6130319/dfdab83b-2a3a-400c-9cac-b4d9f0e49fb2)

I checked again successfully, the test was ok, the synchronisation as well, but the publish process gave the same error after _Generating link_

![grafik](https://github.com/laurent22/joplin/assets/6130319/4c546c55-739c-48f4-827b-e9ddac88469d)

I'm sorry, there seems to be another bug, or did I do something wrong?

**Comment by laurent22** [comment]
I think there's something wrong with your installation. This message means that this particular note hasn't been uploaded to Joplin Cloud, and the app is not going to upload it because of the invalid sync status. Or did you switch from one Joplin Cloud account to another? Because that's not currently supported.

To make sure you don't keep a corrupted sync status your best option would be to:

- Export everything as JEX
- Delete all your notebooks and notes and synchronise (You can use the Victor plugin to help with this)
- Reimport the JEX file and sync

With this you'll start with Joplin Cloud and the app properly in sync.

**Comment by kklepper** [comment]
This does not sound good. And it even gets worse.

I have Joplin desktop open all the time and tested with my main note _Krankengeschichte_ which is (or rather was) the only note in the folder _Krankenhausaufenthalt_ and made a synchronization when I noticed that the note has **vanished**. Nothing left. How can this be? Is there any chance to recover?

The latest published note is https://***.joplinusercontent.com/shares/*** and still valid (Last updated: 11 Jan 24 20:49:36 (UTC)). I have copies in a subnote folder _backup_ which I can roughly classify by the number of annotations, the more the later the text is (is there a method to find the last updated time in notes? Oh, I see the date right top)

I have an entry *Krankengeschichte.md* in *D:\Backups\Joplin\Krankenhausaufenthalt* which seems to be the latest version from 18.01.2024, luckily having a PDF file from the same date derived from the md version. I imported this md version and found that the PDF has the latest addition which I remember whereas the md has it not, so I could reconstruct that.

Having installed Victor, I noticed a new note *conflicts* having two subnotes, one of them being *Krankengeschichte*.

I had severe problems with my PC and had to reinstall Windows and later switch to a new machine and port all SSDs and HDDs.  This does not explain the loss. On Android the note is still present although the version is not synchronized either. Therefore I didn't work on this text for some time and I have a hard time to remember the latest changes.

I can't make any sense of the explanation with regard to conflicts, so I guess I should proceed with your recipe.

And it went well. Thank you very much

Now the Android version cannot synchronize. *Invalid username or password.* Should I deinstall the app and install anew?

**Comment by laurent22** [comment]
> Now the Android version cannot synchronize. Invalid username or password. Should I deinstall the app and install anew?

Yes do that to be sure, and make sure to use the same email/password you use for the desktop app

**Comment by kklepper** [comment]
Well, deinstallation and reinstallation was all too easy. I got some 1800 objects and things looked pretty familiar.

I am confused, though, because the app asked for a decryption password. Following the link, I had the choice between 3 candidates of which I chose the latter. I cannot remember seeing this on the desktop app. 

Well, I chose the latest candidate with date of today. Next a reindexing process was started, it seems, which was extremely slow and could not be finished because of automatic Android timeout. 

I started the whole process 3 times and am still urged to set the decipher password. What to do? Where do I find the corresponding process on the desktop app? I understand that the synchronizing procedure can be encrypted and if so, it should be the same on Windows and Android, right? 

Please instruct me.

**Comment by laurent22** [comment]
There's not much to do other than entering your password. What is not working? If it takes time on Android you need to make sure the phone stays on during sync

**Comment by kklepper** [comment]
I entered my password and synchronization was perfect. The additional notification about decryption password to be set after everything is fine is confusing me.

**Comment by kklepper** [comment]
I understand that by this additional password the data transfer process to the Joplin cloud is encrypted, too. But why is the process asymmetric with respect to the desktop app?

**Comment by laurent22** [comment]
Sorry I don't know the details. If you want more information please post the encryption config screen on desktop and on mobile

**Comment by kklepper** [comment]
There is `no end-to-end encryption` set on desktop:

![grafik](https://github.com/laurent22/joplin/assets/6130319/82f6a526-68b3-42dd-b940-abccce390633)

There is `no end-to-end encryption` set on Android either: 

![grafik](https://github.com/laurent22/joplin/assets/6130319/48e008ad-a6b7-4fcf-a5b7-a41390f07b18)

---

---

---

How can I `disable` the urge to set end-to-end encryption on Android?

![grafik](https://github.com/laurent22/joplin/assets/6130319/ce35a1a1-bce7-45ff-9c70-c5f4e8508c3f)

**Comment by kklepper** [comment]
Anyone?
