### ISSUE TITLE
the software cannot be opened

### ISSUE THREAD

**Issue by chen-ziwen** [laurent22/joplin#9750]
### Operating system

Windows

### Joplin version

all versions

### Desktop version info

![image](https://github.com/laurent22/joplin/assets/85820568/41a1fd8d-9ad9-4a46-b670-ce8ad50cf660)
database write issue, I have tried installing many versions but cannot open them. How can I solve this problem?

### Current behaviour

cannot open

### Expected behaviour

I hope it can be used normally

**Comment by laurent22** [comment]
It looks like the folder it's trying to write to is read-only. I would check the permission of `c:\Users\YOUR_NAME\.config\joplin-desktop` and see it can be written to

**Comment by chen-ziwen** [comment]
Oh, thank you mainly because I just updated a version and it didn't work, making me think there was something wrong with the software.

**Comment by chen-ziwen** [comment]
I have modified the permissions and can now use them normally

**Comment by luzpaz** [comment]
Ticket can be closed, AFAICT
