### ISSUE TITLE
Spellchecker introduces lag, lines to blink when pasted and more

### ISSUE THREAD

**Issue by LaPeste** [laurent22/joplin#9751]
### Operating system

Linux

### Joplin version

2.13.15

### Desktop version info

Joplin 2.13.15 (prod, linux)

Client ID: 62995c287f974573b58afc43969610b3
Sync Version: 3
Profile Version: 44
Keychain Supported: No

### Current behaviour

* At times there's some very noticeable lag when inputting characters.
* When pasting and undoing the line sometimes blink in and out once.

It gets so bad that at times while typing that for example it seems that the delete key isn't read, then I press it again and I find 2 characters deleted at once. There are other cases where it gets so bad that I doubt myself if I pressed a key or not.

All seems to get worse the more you stay writing in a note, but this could just be a feeling. I don't have a proper way to assess this.

I found that the culprit was the spell checker just because of a [post](https://discourse.joplinapp.org/t/desktop-ui-is-too-slow-to-work-efficiently/23657) on discourse from 2022.
Then I saw in `Option/General/Enable spell checking in Markdown editor? (WARNING BETA feature)` the suggestion to report strange behaviours in the Github issue page. I checked if there were any other issues concerning the spell checker and given that none were currently opened, I did opened one.

P.S. I have had this issue for a long time but only now I took action (searching online etc) as in this period I'm using Joplin a fair bit.

### Expected behaviour

None of the above should happen. No input lag should be there.

**Comment by personalizedrefrigerator** [comment]
Is the beta markdown editor enabled? If not, does this also happen in the beta editor (or just the non-beta)?

**Comment by LaPeste** [comment]
Actually, I can say that the lag is still there even with the spellchecker off.
Probably I should rename the issue? :/

<br/>
<br/>

> Is the beta markdown editor enabled?

No it is not.

**Comment by personalizedrefrigerator** [comment]
Does this issue seem the same/similar to https://github.com/laurent22/joplin/issues/9735?

**Comment by LaPeste** [comment]
> Does this issue seem the same/similar to #9735?

Yes really similar rendering issues but not necessarily related to titles. At least I did not get that impression.

I didn't mention it before and I don't know if it's relevant, but I'm on Nvidia+wayland+flatpak.

**Comment by personalizedrefrigerator** [comment]
https://github.com/laurent22/joplin/issues/9735#issuecomment-1962440067 suggests that this issue happens for all XWayland apps.
