### ISSUE TITLE
[Bug] When adding a link to a custom div element in the RTE, it doesn't get converted to HTML and breaks.

### ISSUE THREAD

**Issue by futuremotiondev** [laurent22/joplin#9755]
### Operating system

Windows

### Joplin version

Joplin 2.14.10 (prod, win32)

### Desktop version info

Joplin 2.14.10 (prod, win32)

Client ID: 4dab185d885945ac897a0608af59c6f7
Sync Version: 3
Profile Version: 45
Keychain Supported: Yes

Revision: 3ed6ad5

CodeMirror Options: 1.1.0
Csv Import: 1.0.1
Ez Table: 1.0.2
Favorites: 1.3.2
Menu items, Shortcuts, Toolbar icons: 1.1.0
Quick HTML tags: 0.2.0
Simple Backup: 1.3.6
Simple Highlighter: 1.0.0
Suitcase: 0.3.2
Table Formatter Plugin: 1.2.1
turnToChart: 1.9.3

### Current behaviour

1. I have the following code in the MD editor:

```html
<div class="vsyscallout"><div class="title">Lorem Ipsum Dolar Sit Amit</div><div class="content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Get fringilla ligula gravida nec. Pellentesque habitant Cras ullamcorper turpis ex, eget fringilla ligula gravida nec. Cras ullamcorper turpis ex, eget fringilla ligula gravida nec.Cras ullamcorper turpis ex, eget fringilla ligula gravida nec.Cras ullamcorper turpis ex, eget fringilla ligula gravida nec</div></div>
```

2. It looks like this (with my custom CSS applied):

<img width="742" alt="Joplin_TEklNHVcIz" src="https://github.com/laurent22/joplin/assets/33441569/349f00ea-43f2-415b-8395-0c076b3f004f">

3. If I create a hyperlink within the content box, it works at first in the RTE:

<img width="738" alt="Joplin_m1Jg3axXkt" src="https://github.com/laurent22/joplin/assets/33441569/0d52424d-de6c-4f6f-8730-00a1dfce1270">

4. As soon as I switch from RTE to the MD Editor, and then back to the RTE - the link breaks. See this image:

<img width="743" alt="Joplin_qeuQ8WZRDX" src="https://github.com/laurent22/joplin/assets/33441569/fb621890-4ffb-4389-a960-2e99d8aeb49e">

Is there any way that Joplin can insert a proper <a> element if the content being modified is within HTML content and not markdown?

### Expected behaviour

Joplin should insert the correct <a> tag in the custom HTML content instead of a markdown formatted link.

**Comment by laurent22** [comment]
I don't think we would support this. Any HTML code generated by the RTE is supported, but anything custom added from the Markdown editor is undefined behaviour
