### ISSUE TITLE
[Bug] A backslash is automatically inserted before every '-' character after editing content in the RTE and switching from the MD Editor to the RTE again.

### ISSUE THREAD

**Issue by futuremotiondev** [laurent22/joplin#9756]
### Operating system

Windows

### Joplin version

Joplin 2.14.10 (prod, win32)

### Desktop version info

Joplin 2.14.10 (prod, win32)

Client ID: 4dab185d885945ac897a0608af59c6f7
Sync Version: 3
Profile Version: 45
Keychain Supported: Yes

Revision: 3ed6ad5

CodeMirror Options: 1.1.0
Csv Import: 1.0.1
Ez Table: 1.0.2
Favorites: 1.3.2
Menu items, Shortcuts, Toolbar icons: 1.1.0
Quick HTML tags: 0.2.0
Simple Backup: 1.3.6
Simple Highlighter: 1.0.0
Suitcase: 0.3.2
Table Formatter Plugin: 1.2.1
turnToChart: 1.9.3

### Current behaviour

1. I have some custom HTML content:

<img width="742" alt="Joplin_uY6Xz4zZF9" src="https://github.com/laurent22/joplin/assets/33441569/abca9e1b-e0ae-47c1-8aa0-9ba9f7b8d215">

<img width="744" alt="Joplin_8s3Ko4FzVD" src="https://github.com/laurent22/joplin/assets/33441569/7fa8f31d-3009-4ffa-84c2-a57ad750e1b5">

2. If I then edit the content in the RTE (insert a space, or change a letter) and then switch  from the RTE editor to the MD editor and then back to the RTE, all of my inline code definitions that start with a dash (-) get an extra backslash before the dash.

<img width="745" alt="Joplin_drGuY8885t" src="https://github.com/laurent22/joplin/assets/33441569/4f91dbcd-e5c7-45b4-8c41-d330c1f41e6d">

If I repeat the process over and over again, the dashes compound:

<img width="740" alt="Joplin_YlgblmW0Ta" src="https://github.com/laurent22/joplin/assets/33441569/610ce40e-081d-438f-b2e4-66b00937dbd2">

I'm not sure why this is happening but it's frustrating as I can't really use inline code now inside this custom container.

Would really like to see this fixed if possible.

Thanks

### Expected behaviour

Not insert backslashes before elements that begin with a dash (-)

**Comment by pedr** [comment]
I could not find a way to reproduce this bug, @fmotion1 even with the same plugins 
Can you provide the note that you observed this behavior? Maybe test it with plugins disabled to see the bug still persists?

**Comment by pedr** [comment]
I could not find a way to reproduce this bug, @fmotion1  so I'm closing this issue for now
