### ISSUE TITLE
Too many folders and notes cause the software to run slowly

### ISSUE THREAD

**Issue by librix** [laurent22/joplin#9758]
### Operating system

Windows

### Joplin version

2.13.13

### Desktop version info

Joplin 2.13.13 (prod, win32)

客户端 ID: d5ea82ded4ce4ab18fb2538b24e1695f
同步版本：3
配置文件版本：44
支持的密钥链：是

修订：c3cdeeb

### Current behaviour

On the one hand, importing notes is very slow, about 3GB txt file, more than 36 hours still not finished importing, force quit found only less than 1/3 completed.
On the other hand, due to too many notes and too many directories, the laptop list rendering was laggy when loading and took over 5~10 seconds to respond, even if it doesn't take up much hard disk space.

### Expected behaviour

I would like to see some optimizations in terms of efficiency to improve the speed of the software.

**Comment by personalizedrefrigerator** [comment]
I'm linking this to a few related issues I've just created:
- https://github.com/laurent22/joplin/issues/9891
- https://github.com/laurent22/joplin/issues/9890
- https://github.com/laurent22/joplin/issues/9889
