### ISSUE TITLE
Syncing using filesystem method along with Syncthing causes repetitive lock file errors

### ISSUE THREAD

**Issue by luixxiul** [laurent22/joplin#9759]
### Operating system

Android

### Joplin version

2.13.10

### Current behaviour

1. Install [Syncthing](https://syncthing.net/) on an Android device
2. Install Syncthing on a desktop computer, set up and run it
3. Sync files between the two computer with Syncthing
4. Wait until syncing with Syncthing is finished
5. Set up and start syncing on Joplin a lot of notes like hundreds between those two devices
6. Keep the Android device awake
7. Syncing is cancelled repetitively due to lock file errors

### Expected behaviour

Syncing should not be cancelled and keep running until it is finished.

The issue is not reproduced once syncing files between them is stopped by ending the Syncthing process on the desktop computer.

**Comment by tomasz1986** [comment]
Honestly, I think you will need to provide detailed logs for this one. I've been using Syncthing to sync Joplin files extensively for a very long time between a dozen of devices, including several Android phones and tablets among them, and I've never seen these kind of errors in Joplin.

Syncthing itself does sometimes complain about the lock files disappearing while still being in sync, but the errors seem harmless, with no impact on the actual synchronisation. The instructions also aren't clear on whether you're starting from scratch on Android, or whether the two devices already have their own set of notes present.

Screenshots of the specific error messages would help. Specifically, are the errors coming from Joplin, or from Syncthing?

**Comment by luixxiul** [comment]
> whether you're starting from scratch on Android, or whether the two devices already have their own set of notes present.

I hope this should make it clearer:

1. Install Joplin on an Android device
2. Run it
3. Set sync target to "Filesystem" on Joplin
4. Set up Syncthing to sync the local directory on the device with a PC
5. Keep using Joplin for a while until the folder is filled with ~7000 files
6. Install Joplin on another Android device
7. Set up Syncthing to sync the directory on the PC with the new Android device
8. Wait until the directory is fully sync'd by Syncthing on the new device
9. Install Joplin on the new device
10. Run it
11. Set sync target to "Filesystem"
12. Select the sync'd directory
13. Run sync on Joplin on the new device

> Specifically, are the errors coming from Joplin, or from Syncthing?

The error came from Joplin.

> Honestly, I think you will need to provide detailed logs for this one.

Sorry, unfortunately I am afraid I would not do so because I would not like to experience the issue yet again by resetting the app only to debug the issue after syncing was finally over, checking the phone and restarting sync on Joplin manually a lot of times over several days. I should have copied the log. I wish someone with the same issue would share a log.

**Comment by tomasz1986** [comment]
Yeah, I do think the logs will be required, because following your reproduction steps, they seem like the standard way of setting up Joplin with file system sync via Syncthing, and I have personally never encountered lock file-related errors on any of the Android devices here. In other words, if this was the case, then everyone using Syncthing to sync Joplin files would encounter those errors, but I don't think this is the case.

Just on a side note, is there anything peculiar about your Syncthing configuration? Have you ignored any files in the Joplin file system directory? For example, the lock files are supposed to be synced, and ignoring them in Syncthing could lead to unpredictable consequences.

**Comment by luixxiul** [comment]
> In other words, if this was the case, then everyone using Syncthing to sync Joplin files would encounter those errors, but I don't think this is the case.

I would agree, and since I have replaced my old phone with a new one this month, I am not able to reproduce the error, so I am going to close the issue for now. I will reopen this if the issue will occur again.
