### ISSUE TITLE
Fix "TypeError: Cannot read properties of null (reading 'show')"

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9763]
Version 2.14.10

<img width="1186" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/e4cb59ce-c44f-45ee-8883-e17bbb6853d0">

`window().show()` fails here:

```ts
	public createTray(contextMenu: any) {
		try {
			this.tray_ = new Tray(`${this.buildDir()}/icons/${this.trayIconFilename_()}`);
			this.tray_.setToolTip(this.electronApp_.name);
			this.tray_.setContextMenu(contextMenu);

			this.tray_.on('click', () => {
				this.window().show();
			});
		} catch (error) {
			console.error('Cannot create tray', error);
		}
	}
```

**Comment by pedr** [comment]
I tried to find an explanation why this happens and I think it might be related to this:

> Note that on Linux this event is emitted when the tray icon receives an activation, which might not necessarily be left mouse click.

https://www.electronjs.org/docs/latest/api/tray#event-click

**Comment by pedr** [comment]
Do you think that just wrapping the error with a try catch and improving the error message is better than nothing?
