### ISSUE TITLE
Joplin Cloud's "Logo URL" setting does nothing

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9766]
Ref: https://discourse.joplinapp.org/t/joplin-clouds-logo-url-setting-does-nothing/35408

### Operating system
Linux

### Joplin version
2.13.15

### Desktop version info
Joplin Cloud

### Sync target
Joplin Cloud

### Editor
Markdown Editor

### Joplin Cloud

I love that we can change the logo and text next to the logo for published notes. The "Logo URL" setting, though …
I set it to the URL of my choosing, but it remains https://joplinapp.org

**Comment by personalizedrefrigerator** [comment]
**Note**: A pull request has been created in the Joplin Cloud repository.

**Comment by laurent22** [comment]
This is now fixed and will be part of the next Joplin Cloud release
