### ISSUE TITLE
Deployment with ansible on Ubuntu fails with error : tput: No value for $TERM and no -T specified

### ISSUE THREAD

**Issue by redisded** [laurent22/joplin#9767]
### Operating system

Linux

### Joplin version

2.13.15

### Desktop version info

Joplin 2.13.15 (prod, linux)

ID client : fc9b8646df964f61a58d120cb46fe75d
Version de Synchro : 3
Version du profil : 44
Trousseau supporté : Non

Révision : 7d2c1c0

### Current behaviour

Try to deploy Joplin with ansible in two steps : 
- Downloading install script
- Executing script with bash : fails with error "tput: No value for $TERM and no -T specified"
After a few test, it appears that $TERM is set to "Dumb" when deploying with ansible.
I managed to install modifying the install script with an if condition wich skip tputs settings when $TERM is set to "Dumb".
A PR correcting the problem will follow (This is my first one, please just tell me if the method is not good and I will correct it)

### Expected behaviour

Installation goes well when deploying with ansible

**Comment by tessus** [comment]
fixed in 8b452106be82f1eca16ef7fde02f378273ea7c35
