### ISSUE TITLE
Both Firefox and Windows 10 give warning about the 1.0.115 installer

### ISSUE THREAD

**Issue by apastuszak** [laurent22/joplin#977]
### Operating system

- Windows

### Application

- Desktop

The title says it all.  I downloaded the Joplin installer and Firefox gives me a warning

![image](https://user-images.githubusercontent.com/3401054/48647468-0ad94480-e9ba-11e8-92a1-cce37354fa99.png)

If I try and run it, Windows also gives me a warning.

![image](https://user-images.githubusercontent.com/3401054/48647505-2ba19a00-e9ba-11e8-8d4a-efc0c335ba73.png)

**Comment by laurent22** [comment]
If anyone is trying this version, I'd be interested to know if you are getting this message too. I've recently renewed the signing certificate. So if you are getting this or not, please post the feedback here.

**Comment by skrrgh** [comment]
I get the same warning form Firefox 63.0.3 (64-Bit). But there are no warning from Windows 7.

![joplin](https://user-images.githubusercontent.com/22778376/48654361-882da500-ea0c-11e8-8ae1-036a1a6bee78.png)

**Comment by myparrotsteeth** [comment]
I just tried this. I downloaded it from Chrome (no warning), but Windows 10 did flag it.

**Comment by John-Barr** [comment]
No warnings presented to me. 
Win 10 V:1809 B:17763.134 and Chrome 70.0.3538.102 64 bit.

**Comment by olafthiele** [comment]
I got the same warning message Win10 Buil 17134.407 with Firefox 63

**Comment by apastuszak** [comment]
Just to clarify my original post.  I am on Windows Version 10.0.17134.407

On Windows 7 Version 6.1.7601, I do not get the popup.

**Comment by laurent22** [comment]
I'm hoping that Windows learnt that the app is not harmful by now, but if you're still having warnings in future release, feel free to post back here or on the forum.
