### ISSUE TITLE
Joplin Source code flagged as malware

### ISSUE THREAD

**Issue by miki2119** [laurent22/joplin#9777]
### Operating system

Any

### Joplin version

2.13.15 (and current git)

### Current behaviour

The source code from the latest release is getting flagged as malware by multiple vendors
https://www.virustotal.com/gui/file/74ab900e929ba11b11c114c406ea379f5c2486efb1b809a95afd81d4a78c8d10?nocache=1

The detected malware is described as Generic.HTML.Phishing.Q.F1D2261A 

This is most likely a false positive, but it would probably be a good idea to locate the actual code that triggers this warning to verify this and possibly contact the anti malware vendors about it before users get locked out of their joplin notes because some corporate snakeoil blocks the application.  

Note that the portable .exe release was also flagged with a different warning and only from a single engine.
https://www.virustotal.com/gui/file/94a4bbd5aee616c4e6460c63c91f57628ac83321b59008b6e7ca8957f47f9b67?nocache=1

All other releases seem to be without warning at the moment

**Comment by laurent22** [comment]
Technically Joplin source code contains malware since there are sample hacks that are used to verify that our security fixes work. They are not however bundled with the apps.

**Comment by miki2119** [comment]
After removing the test folder https://github.com/laurent22/joplin/tree/dev/packages/app-cli/tests the repo is no longer flagged as malicious.

The issue in this case seems to be with https://github.com/laurent22/joplin/blob/dev/packages/app-cli/tests/md_to_html/sanitize_12.html and https://github.com/laurent22/joplin/blob/dev/packages/app-cli/tests/md_to_html/sanitize_12.md

https://www.virustotal.com/gui/file/1c61208a5ba44b329cf68d78b66d9ce367b621cb9351663936f5d21d1bc052f6
https://www.virustotal.com/gui/file/671312c0b021b20c606a0739f9d91e1ed4307de802aa8788037a0604d3de030a

Locally removing the test cases folder from the source will probably solve future alerts like this as well

**Comment by laurent22** [comment]
Thanks for checking. Unfortunately we cannot remove these files since they are used to verify that the app is not vulnerable to them.
