### ISSUE TITLE
Display an error message when the mobile note editor fails to load

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#9783]
### Operating system

Android

### Joplin version

2.14.10

### Current behaviour

Currently, when the note editor is [loaded on a device with an incompatible version of the Android System WebView](https://discourse.joplinapp.org/t/cannot-write-into-notes/35485/2) (or iOS), the editor is blank.

### Expected behaviour

We should display an error message.

On Android:
- Explain how to update the Android System WebView
- Give the user the option to switch to the plain editor.

On iOS:
- Give the user the  option to switch to the plain editor.

Depending on what's causing the issue, we may also want to look into transpiling [CodeMirror with babel or adding polyfills.](https://babeljs.io/docs/babel-polyfill)

**Comment by personalizedrefrigerator** [comment]
I'm getting a syntax error when loading the note editor on Safari 11.1 (it doesn't support `a?.b` syntax):
![screenshot: Line beginning with result.selectionLine = ...](https://github.com/laurent22/joplin/assets/46334387/6dcf13c9-e7e9-4e50-bad7-597cd0b72d5b)

The above testing was done on a [browserstack.com free account](https://www.browserstack.com/open-source) (which seems to only allow 1 minute of testingper browser version). We may be able to fix this by setting the Webpack compilation target to ES5: https://stackoverflow.com/a/64528815.

**Edit**: The issue seems to be related to the vim emulation package, which we also use for CodeMirror 5 emulation. If the issue is in a plain `.js` file, we may need to use [`babel-loader`](https://webpack.js.org/loaders/babel-loader/) to transpile (rather than relying on TypeScript).

**Edit 2**: Using `babel-loader` does seem to fix the issue. I've [enabled Babel loader in this branch](https://github.com/laurent22/joplin/compare/dev...personalizedrefrigerator:work/fix-editor-in-old-browsers?expand=1). I plan to create a pull request after doing more testing.

**Comment by laurent22** [comment]
Not sure if this is fully fixed but I suggest leaving it aside for now in any case. If we still get bug reports about this from users we can reconsider
