### ISSUE TITLE
Feature request: Add API to capture a image from a PDF side

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#9794]
### Operating system

Windows

### Joplin version

2.14.10

### Desktop version info

For the OCR process Joplin can capture a image from a PDF page, this would also be greate to publish via `imaging.createFromResource` or via a seperated function for the Plugin API

**Comment by laurent22** [comment]
That makes sense. I think we can indeed expose the pdfjs API to the imaging API
