### ISSUE TITLE
Check that Imaging API creates images with the right quality

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9796]
### Operating system

Windows

### Joplin version

2.14

### Current behaviour

Generated JPEG at 75% quality:

![image](https://github.com/laurent22/joplin/assets/1285584/63e9d482-ffc1-4ef5-b710-195aa81cacdf)

And original image:

![image](https://github.com/laurent22/joplin/assets/1285584/ef59f0f1-a0f8-47fe-b1dc-6a305a6769c7)

I would expect the quality to be better at 75%

**Comment by personalizedrefrigerator** [comment]
At least for the Note List (Preview) plugin, this seems related to the image being [resized to 75px by 75px](https://github.com/JackGruber/joplin-plugin-notelistpreview/blob/d40465fbdeedbc963bada0e2d9430ae0dd1f9d67/src/notelist.ts#L846) (if using default settings) before converted to a JPEG.

Resizing the image to that size, without compressing, seems to yield similar results.

**Comment by personalizedrefrigerator** [comment]
If I change the plugin to resize images to 150px × 150px before saving as a JPEG, I get a less blurry result, particularly at higher zoom levels.

For example (100% zoom, 75% compression):
![screenshot: test note with preview image](https://github.com/laurent22/joplin/assets/46334387/ad20796e-abbc-4f4e-b4a7-cc577bb22595)

**Comment by laurent22** [comment]
Fixed in https://github.com/JackGruber/joplin-plugin-notelistpreview/issues/18
