### ISSUE TITLE
Bug: editor window highlights any line starting with '#' even if not heading

### ISSUE THREAD

**Issue by cjtapper** [laurent22/joplin#98]
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal
![screenshot from 2017-12-15 16-31-37](https://user-images.githubusercontent.com/5920765/34028195-796954de-e1b5-11e7-9668-93c717fb3c63.png)

---
The line should only be highlighted as a heading if there is a space after the '#' before the next character. Otherwise, it should be treated as a plain text line and not highlighted.

**Comment by marcosvega91** [comment]
It seams to be a bug of the library ACE, I'll  investigate on a possible solution.

**Comment by laurent22** [comment]
Yes that's indeed a bug ACE so I've reported there: https://github.com/ajaxorg/ace/issues/3515

**Comment by laurent22** [comment]
That was fixed there - https://github.com/ajaxorg/ace/issues/3515#event-1468436718
