### ISSUE TITLE
Synchronization happens every 10 seconds even if nothing has changed

### ISSUE THREAD

**Issue by iJorgen** [laurent22/joplin#9800]
### Operating system

Linux

### Joplin version

2.14.11

### Desktop version info

Joplin 2.14.11 (prod, linux)

Client ID: <redacted>
Sync Version: 3
Profile Version: 45
Keychain Supported: No

Revision: 0f9d6a1

Simple Backup: 1.3.6

### Current behaviour

The desktop client checks for changes every 10 seconds even if no changes are made. This happens 24/7 and it finds nothing to synchronize, just the spinning wheel and a message that it's completed "Completed: 2024-01-29 16:40 (2s)".

Using "1 hour" as the "Synchronization interval" under settings.

### Expected behaviour

Follow the setting under "Synchronization interval" or sync only after a while when changes are made locally.

**Comment by marph91** [comment]
Same for me:

- Joplin 2.14.11 (prod, linux)
- Synchronization interval: 5 minutes
- Sync target: self-hosted nextcloud

**Comment by personalizedrefrigerator** [comment]
I can reproduce this with Joplin Server sync (synchronization interval: 1 hour, Joplin in dev mode, v2.14.11), but not filesystem sync.

**Comment by personalizedrefrigerator** [comment]
I'm getting a large number of
```
10:02:21: App: "syncInfoCache" was changed - setting up encryption related code
```
messages in the log.

The relevant code seems to trigger a sync 10 seconds in the future:
https://github.com/laurent22/joplin/blob/99e8818ba093a931b1a0cbccbee0b94a4fd37a54/packages/lib/BaseApplication.ts#L370-L380

https://github.com/laurent22/joplin/blob/99e8818ba093a931b1a0cbccbee0b94a4fd37a54/packages/lib/BaseApplication.ts#L385-L390

https://github.com/laurent22/joplin/blob/99e8818ba093a931b1a0cbccbee0b94a4fd37a54/packages/lib/registry.ts#L89-L94

**Comment by personalizedrefrigerator** [comment]
From a `git bisect`, 7b060902551537655ad487f28a7a6473e244bb94 seems to be the first commit with this issue.

**Comment by stevemagruder** [comment]
I've noted this in the Joplin forum, but this applies to the Windows app as well. I'm seeing the same issue happen with a 30-minute interval set. (this is a "for the record" statement, given the above code fix covers Windows too)
