### ISSUE TITLE
Dark theme doesn't show syntax highlighting for fenced code blocks

### ISSUE THREAD

**Issue by John-Barr** [laurent22/joplin#982]
### Operating system

- Windows

### Application

- Desktop

---

I apologise in advance if anything is wrongly done here, this is my first issue.

When using fenced code snippets via markdown, syntax highlighting doesn't seem to be visible in the preview pane.

Example: 

    ```languageModifier 
		    <code>
	```

---

This is just pseudo code but I provided the java language modifier here just for some basic highlighting.

![Default Theme](https://user-images.githubusercontent.com/34806546/48669930-bfae6580-eb62-11e8-90bc-77fc9add2c3a.png)

![Dark Theme](https://user-images.githubusercontent.com/34806546/48669926-b1f8e000-eb62-11e8-856d-adc1bb85289e.png)

v.1.0.115

---

I just changed the language modifier to javascript and it seems as the highlighting is now done via editor pane instead of the preview pane.
![image](https://user-images.githubusercontent.com/34806546/48670095-cc808880-eb65-11e8-8225-2b4b8c806099.png)

**Comment by StrScr** [comment]
I'm having this problem as well. Using Windows 10 1803, latest portable release. Changing the language to JavaScript seems to apply highlighting in the editor only.

**Comment by CalebJohn** [comment]
Sorry about that, I forgot to add the syntax highlighting for the dark theme, I had it on my computer but forgot to add it to github. It should be fixed in the next update!

**Comment by gerroon** [comment]
Thanks for the dakr theme, it is great. But I was just going to complain about this issue. Thanks for the upcoming fix.!
