### ISSUE TITLE
regression in command palette: text commands not shown

### ISSUE THREAD

**Issue by sedlund** [laurent22/joplin#9855]
### Operating system

Windows

### Joplin version

2.13.5+

### Desktop version info

Joplin 2.13.15 (prod, win32)

Client ID: 75d58322754e4db98998fe8512a71b9b
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 7d2c1c0

Outline: 1.5.4
Rich Markdown: 0.13.2
Table Formatter Plugin: 1.2.1

### Current behaviour

Same issue as #5707 

command palette does not have 'bold' 'italic' checkbox 'list' 'insert time' etc

I downloaded a bunch of the AppImages on a linux VM and saw the last version it worked was in v2.13.4   it has been broke since v2.13.5 came out.  I tried current beta v2.14.12 also does not work.

### Expected behaviour

the command palette should have the text features listed above.

**Comment by personalizedrefrigerator** [comment]
From a `git bisect`, the first commit with the issue seems to be c3510bf26b6ba8cd01bfb7fbf61285738a6dfb0b.
