### ISSUE TITLE
KaTex Parse Error

### ISSUE THREAD

**Issue by njmulsqb** [laurent22/joplin#9856]
### Operating system

macOS

### Joplin version

2.13.15

### Desktop version info

Joplin 2.13.15 (prod, darwin)

Client ID: 5ab41cb905494c2882efb1db8a1d3612
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 7d2c1c0

Conflict Resolution: 1.2.3
Simple Backup: 1.3.5

### Current behaviour

When I paste the following aggregate query in text editor

```
db.iprepservicedbs.aggregate([ { $group: { _id: { orgID: "$orgID", machine_identifier: "$machine_identifier", processName: "$processName" }, count: { $sum: 1 }, communicationTime: { $push: "$communicationTime" }, /* Keep other fields intact by using $first*/ orgID: { $first: "$orgID" }, machine_identifier: { $first: "$machine_identifier" }, IP: { $first: "$IP" }, isMalicious: { $first: "$isMalicious" }, reason: { $first: "$reason" }, processName: { $first: "$processName" }, ipOrganization: { $first: "$ipOrganization" }, country: { $first: "$country" }, countryCode: { $first: "$countryCode" }, exePath: { $first: "$exePath" }, appSigned: { $first: "$appSigned" }, __v: { $first: "$__v" }, firstId: { $first: "$_id" } /* Preserve the _id of the first document*/ } }, { $project: { _id: "$firstId", /* Use the preserved _id of the first document*/ count: "$count", /* Include count but not in the final output*/ orgID: 1, machine_identifier: 1, IP: 1, isMalicious: 1, reason: 1, communicationTime: 1, processName: 1, ipOrganization: 1, country: 1, countryCode: 1, exePath: 1, appSigned: 1, __v: 1 } }] ).pretty()
```
it shows up as:

<img width="766" alt="image" src="https://github.com/laurent22/joplin/assets/47940898/5c1e431f-f6ef-42be-a91c-b9e20f49378b">

### Expected behaviour

The error should not be there.

**Comment by laurent22** [comment]
When pasting source code that may contain reserved characters it's better to wrap it in a code block like so:

![Screenshot_20240204_190524_Joplin](https://github.com/laurent22/joplin/assets/1285584/b833ba8b-69f3-44c3-b6a2-7095867140a5)
