### ISSUE TITLE
Mobile: Share to Joplin broken if last open section was "All notes"

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#9863]
### Operating system

Android, iOS 17

### Joplin version

2.14.5 (Android), 12.14.3 (iOS)

### Current behaviour

To reproduce:

1. Open "All notes"
2. Close Joplin
3. Open a different application
    - Tested with Chrome on Android and Safari on iOS
4. Share a website URL with Joplin
5. Share another website URL with Joplin

Currently, no new note is created after either steps 4 or 5. Share only works after navigating to another notebook.

Note that share works if a user has navigated to a notebook since opening Joplin, then navigates back to "All notes" before sharing.

### Expected behaviour

Share should work.

**Comment by personalizedrefrigerator** [comment]
Possibly related to https://github.com/laurent22/joplin/issues/9850.

**Comment by personalizedrefrigerator** [comment]
I'm switching this from `high` to `medium` -- it seems that either [it doesn't happen on all devices](https://github.com/laurent22/joplin/issues/9850#issuecomment-1933116777) or is a regression from 2.13.

**Comment by luisriverag** [comment]
Hi. I've also been experiencing this issue in the last couple of versions
