### ISSUE TITLE
Data loss/Unsaved notes can be lost on Android

### ISSUE THREAD

**Issue by EternityForest** [laurent22/joplin#988]
### Operating system

- Android

### Application

- Mobile

As far as I can tell, the bug occurs when Android kills the task, but it seems like it's also possible to manually exit a note in such a way that data is lost with no warning or save prompt.

To reproduce, just make a note, minimize the app, swipe it away in the tasks,and everything you typed will be gone.

Alternatively, use the sidebar to directly switch to a different note(Without using the back button that triggers the dialog).  Go back to the note and all unsaved text will be gone without a prompt.

**Comment by kuyper** [comment]
Same here

**Comment by laurent22** [comment]
Hmm yes I think it boils down to supporting auto save which is not yet supported on mobile.

**Comment by EternityForest** [comment]
Even with autosave turned off this shouldn't happen, I think it should
handle Android's notification that it's about to suspend the process, and
also do the "would you like to save" thing when switching notes.
