### ISSUE TITLE
bug(turndown): no browser support

### ISSUE THREAD

**Issue by maxpatiiuk** [laurent22/joplin#9884]
### Current behaviour

While original `turndown` includes builds for the browser, `@joplin/turndown` only includes a single build:

![Screenshot 2024-02-07 at 20 16 04](https://github.com/laurent22/joplin/assets/40512816/1c434ea6-33c1-4145-b17a-57af08372198)

![Screenshot 2024-02-07 at 20 16 15](https://github.com/laurent22/joplin/assets/40512816/5b94d9aa-5b5f-41f7-9477-1f61abb1be26)

And unlike the original turndown, `@joplin/turndown` has `const css = require('css');` import, which in turn imports `fs`:

https://github.com/reworkcss/css/blob/master/lib/stringify/source-map-support.js#L9

That causes an error in Webpack when trying to build a project that uses `@joplin/turndown`:

```yaml
ERROR in ./node_modules/@joplin/turndown/node_modules/css/lib/stringify/source-map-support.js 9:9-22
Module not found: Error: Can't resolve 'fs' in '/Users/maxpatiiuk/site/javascript/text-hoarder/node_modules/@joplin/turndown/node_modules/css/lib/stringify'
```

The same goes for "path" and "url" node core modules

### Expected behaviour

Could you please publish the browser builds like the original library did?

---

A workaround for now involves adding this to my webpack config:

```js
    resolve: {
      fallback: {
        fs: false,
        path: false,
      },
    }
```

and things seem to work fine, but doesn't meant it will keep working in the future...

Thanks

**Comment by personalizedrefrigerator** [comment]
Looking at the [`code` tab on NPM](https://www.npmjs.com/package/@joplin/turndown?activeTab=code), it seems that the published version of `@joplin/turndown` uses `css` and not `@adobe/css-tools`:
```js
'use strict';

const css = require('css');

function extend (destination) {
  for (var i = 1; i < arguments.length; i++) {
    var source = arguments[i];
    for (var key in source) {
```

This difference is likely related to [Joplin's release cycle](https://joplinapp.org/help/about/release_cycle).

[`@adobe/css-tools`](https://www.npmjs.com/package/@adobe/css-tools?activeTab=readme) is a fork of [the `css` package](https://www.npmjs.com/package/css) that should have browser support. See [this commit](https://github.com/laurent22/joplin/commit/47072b3813f4a993e0693cf75c8151832c1ec21d) and [this pull request](https://github.com/laurent22/joplin/pull/9660) for additional details.

**Comment by maxpatiiuk** [comment]
That's great news - looking forward to the new release!
