### ISSUE TITLE
sync not working

### ISSUE THREAD

**Issue by smokinjo** [laurent22/joplin#99]
### Operating system

- [ ] Windows
- [ ] macOS
- [X ] Linux
- [ ] Android
- [ ] iOS

### Application

- [X ] Desktop
- [ ] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---
I have succeeded in installed Joplin and I can enter notes and what not.

But hitting the synchronize button does not pull up the log in screen to OneDrive.

I tried it on my android phone, and it works fine.

Not sure why the sync is not reacting.

Thanks for ideas.

Joseph

**Comment by laurent22** [comment]
Which version is it? (in help > about)

**Comment by smokinjo** [comment]
0.10.25

Hope this helps.

**Comment by laurent22** [comment]
Please try with the latest version 0.10.39, it should be fixed in that version.

**Comment by smokinjo** [comment]
I do not know where I got the old version.  Weird.

I got the new version, and it synchronizes fine.

Thanks

**Comment by ottopor** [comment]
I'm trying the version 1.0.64. using Nextcloud to synchonise. However, my android app syncs well with nextcloud, but the linux app is not syncing.
