### ISSUE TITLE
[Desktop] Note list scrolls when creating a new note

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#9908]
### Operating system

Linux

### Joplin version

2.14.11

### Desktop version info

Joplin 2.14.11 (prod, linux)

Client ID: 934e50ae74a941f587912680f6d54c43
Sync Version: 3
Profile Version: 45
Keychain Supported: No

Revision: 0f9d6a1

Favorites: 1.3.0
Inline tags: 1.2.1
Rich Markdown: 0.12.0
Simple Backup: 1.1.1
Table Formatter Plugin: 1.2.1
Templates: 2.3.0

### Current behaviour

1. Open a folder with more notes than can fit on the screen, so that there's a scrollbar
2. Set sort by update time descending
3. Create a new note
4. Note list scrolls almost to the end (but not quite) while the new note is created at the top

### Expected behaviour

No scrolling

**Comment by personalizedrefrigerator** [comment]
I haven't been able to reproduce this in version 2.14.12 (Ubuntu 23.10, custom build from a recent commit). As such, this may have been fixed in https://github.com/laurent22/joplin/commit/25b12a236682e68027820dd5096c851cb79cbfb9 (which is in version 2.14.12).

**Comment by roman-r-m** [comment]
Thanks, it is indeed fixed in the latest pre-release.
