### ISSUE TITLE
Command palette search normalizes item title

### ISSUE THREAD

**Issue by pedr** [laurent22/joplin#9919]
### Operating system

Linux

### Joplin version

2.13.9

### Desktop version info

Joplin 2.13.9 (prod, linux)

Client ID: d3fa10d48b63492bb7d8084553eec963
Sync Version: 3
Profile Version: 44
Keychain Supported: No

Revision: 1bbec44

### Current behaviour

1. Create a note with non-latin characters (e.g.: "É uma nota")
2. Add some content to it
3. Open Comand Palette
4. Search by the content of the note
5. The title of the note will be shown as "e uma nota"

![image](https://github.com/laurent22/joplin/assets/5051088/1056e198-bd57-41be-ad84-04dc4b133af0)

### Expected behaviour

The title should be displayed as the original and not a normalized version.

**Comment by RafaR13** [comment]
Hello,

I've come across this issue and would like to take a shot at solving it.
