### ISSUE TITLE
App not working at all after update 2.14.13

### ISSUE THREAD

**Issue by tconsta** [laurent22/joplin#9922]
### Operating system

macOS

### Joplin version

2.14.13

### Desktop version info

Can't say, just Version 2.14.13 (2.14.13) in "About"

### Current behaviour

1. Just installed a new release
2. Launch, see empty window:
<img width="881" alt="SCR-20240210-ohrp" src="https://github.com/laurent22/joplin/assets/13377078/bc563934-9a8c-4ea9-938b-84cd93327a69">
3. Nothing happens, can be closed only with kill -9

Rolled back to 2.14.12, works fine.

### Expected behaviour

Work

### Logs

[log_tail_100.txt](https://github.com/laurent22/joplin/files/14228700/log_tail_100.txt)

**Comment by laurent22** [comment]
Can you try to open the console and see if there's any error in there? https://joplinapp.org/help/apps/debugging/#desktop-application

**Comment by orr721** [comment]
Same issue here. I have tried `--debug`, but it is not working? So I have used --inspect. Anyway no change, just a blank window and I have to force quit the app. 

(edit) And there is nothing at all in the `log.txt`, last messages are from sync when the old version was still working.

Thanks..

```
~/Desktop 1> ~/Applications/Joplin.app/Contents/MacOS/Joplin --debug --log-level debug
electron: [DEP0062]: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` and `node --inspect-brk` instead.
~/Desktop 9> ~/Applications/Joplin.app/Contents/MacOS/Joplin --inspect
Debugger listening on ws://127.0.0.1:9229/5d655395-b654-4ffe-9a5e-0088e647d6d0
For help, see: https://nodejs.org/en/docs/inspector
Sentry: Initialized with autoUploadCrashDumps: false
2024-02-10 14:07:30.174 Joplin[3506:206244] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
~/Desktop -1>
```

**Comment by laurent22** [comment]
Could you try this as well?

> If the application starts with a white screen, open **Help \> Toggle Development Tools** or **View \> Toggle Development Tools** in the menu. Then check in the console if there is any error or warning and please let us know about it.

**Comment by laurent22** [comment]
Also try to to start in safe mode: https://joplinapp.org/help/apps/debugging/#safe-mode

I'm not having this issue so I'm guessing it's something to do with a plugin.

Also do you have an Intel or Apple silicon Mac?

**Comment by orr721** [comment]
Ah, we are getting somewhere, this is in the developer console:

```
Uncaught Error: dlopen(/var/folders/k8/8mgzdl0x43xfhhpdqhzrf8j80000gn/T/.net.cozic.joplin-desktop.r4wgXf, 0x0001): tried: '/var/folders/k8/8mgzdl0x43xfhhpdqhzrf8j80000gn/T/.net.cozic.joplin-desktop.r4wgXf' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/k8/8mgzdl0x43xfhhpdqhzrf8j80000gn/T/.net.cozic.joplin-desktop.r4wgXf' (no such file), '/var/folders/k8/8mgzdl0x43xfhhpdqhzrf8j80000gn/T/.net.cozic.joplin-desktop.r4wgXf' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/private/var/folders/k8/8mgzdl0x43xfhhpdqhzrf8j80000gn/T/.net.cozic.joplin-desktop.r4wgXf' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/k8/8mgzdl0x43xfhhpdqhzrf8j80000gn/T/.net.cozic.joplin-desktop.r4wgXf' (no such file), '/private/var/folders/k8/8mgzdl0x43xfhhpdqhzrf8j80000gn/T/.net.cozic.joplin-desktop.r4wgXf' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:2131)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2358)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function.<anonymous> (node:electron/js2c/asar_bundle:2:13327)
    at Function._load (node:electron/js2c/renderer_init:2:2455)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at bindings (/Users/user/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)
```

It is an Apple Silicon M1 Macbook Air, Rosetta is not installed. Mac OS Sonoma 14.3.1. 


(edit) The safe mode does nothing. BTW the Help menu is completely empty.

**Comment by laurent22** [comment]
Would you mind trying with this release?

https://github.com/laurent22/joplin/releases/tag/v2.14.14

**Comment by orr721** [comment]
Yep, version 2.14.14 works, thank you.. 👍

**Comment by laurent22** [comment]
> Yep, version 2.14.14 works, thank you.. 👍

Great, thanks for confirming!
