### ISSUE TITLE
Wrong Appimage for 2.13.15.

### ISSUE THREAD

**Issue by bjwest** [laurent22/joplin#9923]
### Operating system

Linux

### Joplin version

2.13.15

### Desktop version info

Joplin 2.9.17 (prod, linux)

Client ID: 65afbac01ff64a03b8d442a6e4f13fea
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: a84a8e7

### Current behaviour

1.  Download the file Joplin-2.13.15.AppImage from GitHub.
2. Make executable and run to integrate to desktop via AppImageLauncher.
3. Run newly installed app and check version in About dialog.
4. Version is reported as 2.9.17.
5. Select 'Check for updates...' in Help menu.
6. The dialog indicates the version is 2.9.17, and a new version, 2.13.15 is available.

### Expected behaviour

About dialog to report Joplin 2.13.15, and 'Check for updates...' should indicate Joplin is up to date.

I've downloaded the AppImage twice with the same results.

**Comment by personalizedrefrigerator** [comment]
Please verify that Joplin isn't running before launching the AppImage. If Joplin is already running when launching the AppImage, the running version of Joplin will be shown.

(For me, the AppImage shows version 2.13.15 in the about dialog.)

**Comment by taw00** [comment]
I am running the 2.13.15 AppImage on Linux. This is from my about results:
```
Joplin 2.13.15 (prod, linux)

Client ID: 9959465eea794e60b1b95760c308ca91
Sync Version: 3
Profile Version: 44
Keychain Supported: No

Revision: 7d2c1c0
```
