### ISSUE TITLE
extra space (2 rows) on top of note

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#993]
### Operating system

- macOS

### Application

- Desktop

There's an extra space now at the beginning of the note (about 2 rows).
It looks rather weird.

![extraspace](https://user-images.githubusercontent.com/223439/48804891-d8925480-ece3-11e8-994d-4a7c106a98fa.jpg)

**Comment by laurent22** [comment]
@Abijeet, it looks like it's the tab bar. I guess it should be hidden when there's no tag?

**Comment by alexdevero** [comment]
@Abijeet you did a good job.

**Comment by laurent22** [comment]
Being worked on
