### ISSUE TITLE
Server - Table events grow constantly

### ISSUE THREAD

**Issue by luckyguido** [laurent22/joplin#9931]
### Operating system

Linux

### Joplin version

Server - v2.13.3

### Desktop version info

Server Joplin  v2.13.3 installed on docker with PostgreSQL 

### Current behaviour

Table events has milion of records, and grows every second.
<img width="560" alt="image" src="https://github.com/laurent22/joplin/assets/11061359/3f72350a-9c4b-4fe3-9903-0dcb05ab9bfd">
here's an example of the latest line on my DB, as a workaround can oldest record can be deleted from this table or it will brake something on server sync?
I have 15MB of notes (attachments included) and 400MB of events table
<img width="1376" alt="image" src="https://github.com/laurent22/joplin/assets/11061359/8d2ffddf-b56a-4b65-add5-955092a3bb6d">

### Expected behaviour

Events table should be deleted by a rolling windows

**Comment by laurent22** [comment]
Yes there should be something to clean this up. In the meantime you can run a query such as `DELETE FROM events WHERE created_time < SOME_TIMESTAMP`. Where `SOME_TIMESTAMP` is old enough such as a week ago, and it's in milliseconds.

**Comment by McOrvas** [comment]
Hello, I have a problem with a continuously increasing database, too. I have already opened a thread in the forum two weeks ago, but without any answers yet: https://discourse.joplinapp.org/t/joplin-server-sql-dump-increases-every-day/35542

I don't know if it's the same reason, but I suspect it is. I hope it's okay if I reuse my original text here:

**Operating system**
Linux

**Joplin version**
Server 2.13.3 / 2.14.2 with PostgreSQL in container

Hello everyone, I am using the Joplin App on different devices (Linux, Windows, Android) with syncing to Joplin Server (v2.13.3 / v2.14.2), which uses PostgreSQL for storage. Every night a backup script runs which executes pg_dumpall. Everything works fine and as intended, but the size of the SQL dump increases every day by approx. 1,2 MB without adding any new content from user side. Even during vacation with no syncs it increases. If I stop the Joplin Server container but keep PostgreSQL running, the dumps are identical every day. So Joplin Server adds a lot of data to the database every day without user interaction. For example: The today's SQL dump has 154,6 MiB, the complete Backup with the desktop app exports a JEX file with only 19,6 MiB. The web frontend of Joplin Server reports "Total size 29.2 MB (0%)". This ~1,2 MB per day are not a problem for the local storage, but generates unnecessary data for further online backup of the dumps.

Therefore my questions are:

- What kind of data is written to the database by the Joplin Server without user interactions / synchronization processed?
- Is it possible to deactivate this behavior?
- Is it possible to clean up the database with Joplin Server to delete the (presumed) data garbage?

Thanks a lot for your support!
McOrvas

**Comment by McOrvas** [comment]
In the meantime I have created a cron job on the server with the SQL statement provided by laurent22 above. It works, but it would be better and less cumbersome if it was built right into the software. 

Out of curiosity: What is the exact purpose of the event entries every second and why was the deletion period of one week chosen in the SQL example above?

**Comment by danepowell** [comment]
I'm assuming the purpose of the events table is to coordinate syncs. I'm guessing that if you delete events further back than the last sync date of any client, any events prior to that date will be lost, i.e. changes before that date won't be synced to an out-of-date client.

If that's true and you ensure all your clients are synced, it should be safe to delete nearly all events (certainly anything older than 1 week).

But again, these are all complete assumptions based on a general understanding of server/client synchronization and not Joplin specifically.

**Comment by tugdualenligne** [comment]
Hi, my Joplin server Postgre DB is huge. I suspect something is wrong. I have ran the command above to try delete events but it didn't work (I set 1 week in milliseconds).
Any help appreciated, and thanks for that great note taking app !

A SQL command to estimate table sizes gives this (only first two significant tables shown). 
I suspect 819MB of events isn't normal:
events 819 MB
items 291 MB

**Comment by EricDuminil** [comment]
@tugdualenligne

Just in case it could help...

## Manual delete

> I have ran the command above to try delete events but it didn't work (I set 1 week in milliseconds).

You need to set a datetime in milliseconds, not a duration. So, one week ago in milliseconds would be

```javascript
Date.now() - 7*24*60*60*1000
#=> 1756210623252
```

In SQL:
`DELETE FROM events WHERE created_time < 1756210623252;` would delete all the old events.

`vacuum full events;` would reclaim the space, and your DB should be much smaller.

You can check with `select table_name, pg_size_pretty(pg_total_relation_size(quote_ident(table_name))), pg_total_relation_size(quote_ident(table_name)) from information_schema.tables where table_schema = 'public' order by 3 desc;`

## Automatic task

You can now delete old events automatically via 2 environment variables:

```
EVENTS_AUTO_DELETE_ENABLED=true
EVENTS_AUTO_DELETE_AFTER_DAYS=15
```

You'd still need to manually vacuum if your DB is too large already.

**Comment by tugdualenligne** [comment]
I suspect that helps, many thanks, will try later when in front my laptop

**Comment by tugdualenligne** [comment]
Tried successfully, it does help a lot: I went from 1,7Gb (yes you read correctly), to 75Mb. I had understood incorrectly the instruction to calculate in milliseconds. Thx for taking the time
I also inserted your variables to automatically clean the events DB

**Comment by EricDuminil** [comment]
@danepowell  Indeed. Syncing does not work anymore if clients are too out-of-sync, after deleting old events.

And apparently, a fresh sync on a new client does not work either anymore, which might be a bigger problem.

**Comment by laurent22** [comment]
No that's unrelated, we don't use the events table for sync

**Comment by EricDuminil** [comment]
@laurent22 : That's good to know.

I'll investigate further, and try to understand where `2026-01-11 11:35:27: checkDisabledSyncItemsNotification: 7 resource download errors: Triggering notification` are coming from.

Thanks for the reply and the awesome project!
