### ISSUE TITLE
Note's internal search ignores text inside code blocks & inline code

### ISSUE THREAD

**Issue by alonbilu** [laurent22/joplin#9937]
### Operating system

Windows

### Joplin version

2.13.15

### Desktop version info

Joplin 2.13.15 (prod, win32)

Client ID: a165ec570e7b405f830748c600c21e0a
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 7d2c1c0

Better Code Blocks: 1.1.0
CodeMirror Line Numbers: 2.0.0
CodeMirror Options: 1.1.0
Quick Move: 1.1.0

### Current behaviour

1. I write few lines of text in a new note's WYSIWYG editor.
2. I then create a new code block or an inline code  and writes some text inside
3. I hit the CTRL-F -> Find & replace window appears
4. Searching for a text which resides inside the code block  returns "could not find the specific string error" regardless of the case matching settings.
5. However, searching for a text outside the code block works just fine

### Expected behaviour

Should also search inside code blocks

**Comment by personalizedrefrigerator** [comment]
Possible duplicate of https://github.com/laurent22/joplin/issues/9504
