### ISSUE TITLE
Removing an unused tag

### ISSUE THREAD

**Issue by josesalvador** [laurent22/joplin#994]
### Operating system

- Linux
- Andriod

### Application

- Terminal

## Issue

I don't be able to remove an unused tag from terminal neither android apps.

The tag has no note linked.

**Comment by laurent22** [comment]
If the tag is not associated with any note it should not be displayed anywhere. If it is, please could you let me know where specifically?

**Comment by josesalvador** [comment]
It is displayed as android as terminal (1.0.106) version.

You can see the tag affected has no note linked to it visually neither tag list command through screenshot attached.

![joplin_screenshot](https://user-images.githubusercontent.com/2736452/48890628-a561d980-ee39-11e8-862b-045de111fe91.png)

**Comment by SinTan1729** [comment]
It's still happening as on 11/03/19
