### ISSUE TITLE
Unknown profile version. Most likely this is an old version of Joplin, while the profile was created by a newer version. 

### ISSUE THREAD

**Issue by eravse** [laurent22/joplin#9945]
### Operating system

macOS

### Joplin version

2.13.15

### Desktop version info

<img width="632" alt="image" src="https://github.com/laurent22/joplin/assets/404877/a76f7c13-300e-4fe1-98d5-44c451f30291">

**Comment by laurent22** [comment]
Hello you previously installed version 2.14 so you need to go back to it for the profile to work. 2.14 is now quite stable
