### ISSUE TITLE
Context menu disappears in Insert/Edit Link dialog

### ISSUE THREAD

**Issue by bgoodmansf** [laurent22/joplin#9948]
### Operating system

Windows

### Joplin version

2.13.15

### Desktop version info

Joplin 2.13.15 (prod, win32)

Client ID: 552af2772b294d9f821072c45033338f
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 7d2c1c0

Note: Same behavior is observed on Fedora with Joplin version 2.13.11

### Current behaviour

1. Open new note
2. Select Smart/WYSIWYG editor
3. Click Insert/Edit Link icon to open link dialog
4. Right click mouse to open context menu.
5. Menu flashes then disappears. Cannot cut/copy/paste.

### Expected behaviour

Expected context menu to display and remain in view.

**Comment by graphit0** [comment]
I was able to reproduce it on 2.14.14 linux (ubuntu 22.04)

**Comment by personalizedrefrigerator** [comment]
This is also the case in the edit code dialog.

**Comment by personalizedrefrigerator** [comment]
Related: https://github.com/laurent22/joplin/issues/9953
