### ISSUE TITLE
LInks created by Linkify are not clickable in WYSIWYG editor

### ISSUE THREAD

**Issue by bgoodmansf** [laurent22/joplin#9949]
### Operating system

Windows

### Joplin version

2.3.15

### Desktop version info

Joplin 2.13.15 (prod, win32)

Client ID: 552af2772b294d9f821072c45033338f
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 7d2c1c0

### Current behaviour

1. Enable LInkify
2. Create a new note
3. Select WYSIWYG editor
3. Add "https://yahoo.com" to note
4. Switch to another note
5. Switch back to note created in step 2
6. https://yahoo.com is underlined but nothing happens when the link is clicked.

### Expected behaviour

Clicking on underlined link should open web page in browser,

This works in the viewer window of the markdown editor but does not work in the WYSIWYG editor.

The Tools > Options > Markdown > Linkify option says that LINKIFY works with the WYSIWYG. If this is not fixed, then the option text should be changed to indicate that LINKIFY  does **NOT** work with WYSIWYG.

**Comment by graphit0** [comment]
Links in WYSIWYG are followed by Ctrl+click

**Comment by bgoodmansf** [comment]
I did not know that. Now I see it was creating a tab but not bringing the window to the top, so I did not see the new tab.
