### ISSUE TITLE
Link created by LINKIFY in WYSIWYG editor is not underlined until switch to another note

### ISSUE THREAD

**Issue by bgoodmansf** [laurent22/joplin#9950]
### Operating system

Windows

### Joplin version

2.13.15

### Desktop version info

Joplin 2.13.15 (prod, win32)

Client ID: 552af2772b294d9f821072c45033338f
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 7d2c1c0

### Current behaviour

1. Enable LInkify
2. Create a new note
3. Select WYSIWYG editor
4. Add "https://yahoo.com/" to note
5. Link is not underlined
6. Switch to another note
7. Switch back to note created in step 2
8. https://yahoo.com/ is underlined

### Expected behaviour

Links should be underlined without having to leave and return to note.

**Comment by graphit0** [comment]
I was able to reproduce it on 2.14.14 linux (ubuntu 22.04)

**Comment by bgoodmansf** [comment]
Still fails in 2.14.19
