### ISSUE TITLE
Web Clipper: Open newly created note opens new window with garbage in Firefox

### ISSUE THREAD

**Issue by bgoodmansf** [laurent22/joplin#9951]
### Operating system

Windows

### Joplin version

Web clipper 2.11.2

### Current behaviour

1. Open Firefox
2. Click web clipper icon
3. Click "Clip URL"
4. Click "Confirm"
5. Click "Open newly created note"
6. Firefox opens new window with URL: joplin://x-callback-url/openNote?id=588ee103a214443ebd89d1039b26b762
7. Firefox window with blank content remains open.

### Expected behaviour

Expect browser window to close.

The web clipper properly creates a note in Joplin, but opening the note from the web clipper opens a new window in Firefox with a strange URL. Performing the same sequence in Chrome does not open a new window (or maybe the window is closed so quickly it is not visible).

**Comment by graphit0** [comment]
I couldn't reproduce this behaviour

Firefox 124 Nightly
Brave 1.62 Chromium 121
Joplin 2.14.14 
Clipper 2.11.2 
ubuntu 22.04

> - Firefox opens new window with URL: joplin://x-callback-url/openNote?id=588ee103a214443ebd89d1039b26b762
> - opening the note from the web clipper opens a new window in Firefox with garbage URL

This URL is external link to clipped note and should open dialogue to run Joplin window with created note

Firefox 
![image](https://github.com/laurent22/joplin/assets/44114323/3b488b3e-d712-46f7-9cb6-eb2dbf4e5ccb)
Brave (chromium)
![image](https://github.com/laurent22/joplin/assets/44114323/07f6d364-4ed4-4ff3-a57c-d96a3a8083f9)

Could you be possibly running portable version of Joplin?

**Comment by bgoodmansf** [comment]
I have tried this on both Windows 10, Windows 11 and Fedora 39 with the same result. I am running the non-portable version of Joplin on Windows. Here is a screenshot after clipping a note on Fedora.
![Screenshot_20240216_083017](https://github.com/laurent22/joplin/assets/4819742/b3682732-8399-4c93-8f8e-d001d3a564f5)

**Comment by graphit0** [comment]
Could you report what application is assigned to open joplin:// links

In firefox: General -- Applications
![image](https://github.com/laurent22/joplin/assets/44114323/f063b8ed-9acd-4664-bb3a-d56d638c2ac1)

**Comment by bgoodmansf** [comment]
On Fedora 39, my FIrefox settings looks the same as yours (Use Joplin (default).

Note that the note is opened correctly in Joplin. But the window/tab is left open in Firefox. In Chrome, the window/tab goes away.

**Comment by graphit0** [comment]
So the issue here is the tab not closing or there's no warning that you may close the tab afterwards? 
Or there's some other expected behaviour?
Gotta clarify that in expected behaviour of original issue.

**Comment by bgoodmansf** [comment]
From the user's perspective, they asked to open a note in Joplin. Instead a tab or window opens in the browser.

I don't know if opening a browser window is a required part of the sequence, but it is definitely not what the user expects. It may be that Chrome also opens a browser window, but it gets closed. 

I will add more to the expected behavior.

**Comment by graphit0** [comment]
Okay, I can see that now, thanks. Would be nice to update the title as well :eyes:

**Comment by bgoodmansf** [comment]
The title seems correct to me. The problem is that there is window of junk opened in Firefox.

What do you think would be a better description?

**Comment by graphit0** [comment]
I see. In my view, opening new tab with external x-callback-url is expected behavior. Joplin uses it to communicate with other applications -- for example you can create a desktop shortcut that would open a particular note using this kind of link.

I believe Joplin expects user to interact with such links, so maybe there's a point of making it somehow more intuitive and easy. That said, I believe x-callback-url is not garbage :sweat_smile: (not to mention calling it that might be offensive to people who developed it -- who has main knowledge to fix it) 

To keep this particular issue focused on functionality (i.e. not to deal with UX -- without a designer, it's difficult to work on such issues) I suggest the following title

Web Clipper: "Open newly created note" doesn't close its tab after redirect in Firefox

**Comment by bgoodmansf** [comment]
This is using the web clipper. When the user is on a web page, they click the "open note in Joplin" button. I don't think they expect some new window to open in the browser. They expect to see the note in Joplin.

I don't think anyone but a developer would have any idea what an x-link is. I am a developer and I have never heard of such a thing. The person who showed this to me thought that Joplin had crashed because of the window that appeared in the browser.

The window with the x-link seems to be some sort of intermediate temporary window which the user is never intended to see. But somehow with Firefox is remains visible. It does not show when you use Chrome.

**Comment by bgoodmansf** [comment]
The user does not create this tab. They are viewing a different tab in the browser. They create a clipping in Joplin. The button they click in the extension asks to open the new note in Joplin.

From the user's perspective, a new window is opened in the browser which has unrecognizable text in the URL. There is nothing for the user to do with that window. It is clearly some sort of intermediate step used by the extension. It is supposed to be closed by the extension, but it ends up being left visible when using Firefox. It's like a temp file left behind.

This temporary window is properly closed in Chrome, but it gets left open in Firefox.

**Comment by bgoodmansf** [comment]
I am certain Joplin does NOT expect the user to interact with the tab because it is deleted when using Chrome.
