### ISSUE TITLE
searching works only with full word

### ISSUE THREAD

**Issue by zzzazzz** [laurent22/joplin#9957]
### Operating system

Linux

### Joplin version

2.13.15

### Description

Hi and thx for Joplin,
Just a little problem with the search module. Searching will only returns words have been completly typed.
It should be great if typing part of a word returns results… No ?

thkx

### Current behaviour
![Capture d’écran du 2024-02-18 09-11-31](https://github.com/laurent22/joplin/assets/4640081/3ed87161-80b6-4e0a-8824-17a9e857a287)

![Capture d’écran du 2024-02-18 09-11-45](https://github.com/laurent22/joplin/assets/4640081/cdcd1ffd-40fe-48d3-bef4-c17d843f7f3b)

_No response_

**Comment by laurent22** [comment]
That is changed in 2.14
