### ISSUE TITLE
Focus is lost when the hyperlink modal is cancelled

### ISSUE THREAD

**Issue by geball** [laurent22/joplin#9970]
### Operating system

Linux

### Joplin version

2.13.15

### Desktop version info

Joplin 2.13.15 (prod, linux)

Client ID: 59929b147fa5436cbc8a24035555730a
Sync Version: 3
Profile Version: 44
Keychain Supported: No

### Current behaviour

1. I open or create a note.

![Screenshot showing the Joplin markdown editor and preview pane. There is an H1 that reads "A new note!" and the cursor is below it.](https://github.com/laurent22/joplin/assets/45116528/48c4e7d8-eb89-4fec-8161-2f5c717422d5)

2. I hit `<Ctrl-K>` to open the Insert Hyperlink modal. The field receives focus, as expected.

![Screenshot of the Insert Hyperlink modal, with focus in the single field. There are OK and Cancel buttons in the bottom-right corner.](https://github.com/laurent22/joplin/assets/45116528/a1b2bebc-9d17-4b6c-81a6-cc04b7e3ee7f)

3. If I enter a hyperlink and hit `<Enter>` or click OK, everything works fine. However, if I hit `<Esc>` or click Cancel, the pane loses focus. It seems Joplin is still in focus, since pressing `<Alt>` focuses the File menu, but I need to click back into the pane to start typing again. (I can also `<Shift-Tab>` 3 times or `<Tab>` 4 times to focus the Markdown pane again, in case that helps narrow down what's focuses after cancelling the modal. I've tried arrow keys, etc., but can't see where focus is going.)

### Expected behaviour

Upon cancelling the hyperlink modal, I would expect to return to where the cursor was previously.

**Comment by danimnunes** [comment]
Hello everyone,

I've come across this issue and I would like to take a shot at resolving it. I'll keep you all posted on my progress.

**Comment by geball** [comment]
Re: [bot reply](https://github.com/laurent22/joplin/issues/9970#issuecomment-2025573400), still an issue in 2.14.20.
