### ISSUE TITLE
KaTeX `alignat` breaks TeX code below it

### ISSUE THREAD

**Issue by IvanaGyro** [laurent22/joplin#9974]
### Operating system

Android

### Joplin version

2.13.10

## Minimal example code

```
$$
\begin{alignat}{3}
1 &= 1 \\
10 &= 10 \\
100 &= 100 \\
\end{alignat}
$$

$a$
```
## Current behaviour

The line `$a$` is displayed as an error: Cannot read property 'map' of undefined

![Screenshot_20240222-131117](https://github.com/laurent22/joplin/assets/11438642/334640ed-be4e-448c-9f55-e7b6b440f4f2)

## Expected behaviour

Rander the whole code correctly.

## More information

If replace `alignat` with `aligned`, the whole code can be rendered correctly.

```
$$
\begin{aligned}
1 &= 1 \\
10 &= 10 \\
100 &= 100 \\
\end{aligned}
$$

$a$
```

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

This seems to be fixed in the 2.14 pre-release (perhaps by https://github.com/laurent22/joplin/commit/fd5a4dcbbfd0d1417c2b4370c9da85c829e97c4e), which should become stable in the next few weeks!
