### ISSUE TITLE
Beta markdown editor: Support Ctrl+Enter keyboard shortcut (Cmd+Enter on MacOS)

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#9980]
### Operating system

Linux

### Joplin version

2.14

### Current behaviour

Currently, pressing <kbd>Ctrl</kbd>-<kbd>Enter</kbd> (Cmd+Enter on MacOS) in the beta and legacy markdown editors does nothing. In VSCode and with the [default CodeMirror setup](https://codemirror.net/), it inserts a new line below the current.

### Expected behaviour

Pressing <kbd>Ctrl</kbd>-<kbd>Enter</kbd> should have behavior consistent with VSCode and the CodeMirror 6 defaults.

**Comment by njmulsqb** [comment]
I am trying to work on it but need a bit assistance in finding where to add the changes. I found this article https://www.electronjs.org/docs/latest/tutorial/keyboard-shortcuts that mentions adding the shortcuts in Electron JS using `accelerator` but I want to know where should I implement these changes as we have multiple directories in note body i.e. CodeMirror, PlainEditor, TinyMCE. 

If someone can point me to the relevant code it'll help a lot.

**Comment by roman-r-m** [comment]
I don't think this has anything to do with electron shortcuts. It should be specific to CodeMirror (version 6, since it mentions beta editor, I believe)
