### ISSUE TITLE
Option to "Toggle own sort order" should be added to "All notes"

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9984]
Currently a custom order can be set by right-clicking on a notebook and selecting "Toggle own sort order". That same option should be added to the "All notes" entry in the sidebar.

**Comment by 2003Aditya** [comment]
Hey! @laurent22 can you please describe more...

**Comment by PackElend** [comment]
please avoid mentioning people, he created the issue, so he will be notified anyway. May read again *Important* in https://discourse.joplinapp.org/t/gsoc-2024-live-blog/36127

**Comment by HahaBill** [comment]
> Hey! @laurent22 can you please describe more...

Hi, I've been looking at this issue and currently working towards it. What 'Toggle own sort order' should do is that a toggled notebook has its own way of ordering the notes. I think what he means is to enable all own sort order for all notebooks if I am correct.

**Comment by laurent22** [comment]
> I think what he means is to enable all own sort order for all notebooks if I am correct.

Specifically for the "All notes" item at the top of the list on the sidebar.

![image](https://github.com/laurent22/joplin/assets/1285584/d1a96d5b-52d4-4d67-b83b-5a31ed3726a6)

So right-clicking on it should show a menu with one item: "Toggle own sort order". And that should do the same as for regular notebooks.

**Comment by HahaBill** [comment]
> > I think what he means is to enable all own sort order for all notebooks, if I am correct.
> 
> 
> 
> Specifically for the "All notes" item at the top of the list on the sidebar.
> 
> 
> 
> ![image](https://github.com/laurent22/joplin/assets/1285584/d1a96d5b-52d4-4d67-b83b-5a31ed3726a6)
> 
> 
> 
> So right-clicking on it should show a menu with one item: "Toggle own sort order". And that should do the same as for regular notebooks.

Alright, that clarifies it! To summarize, adding “Toggle own sort order” to “All notes” so it has its sort order, and other regular notebooks won’t affect its order. 

I think this new feature will be pretty nice to have.

**Comment by HahaBill** [comment]
Hi, I have some updates! I managed to solve the issue. I have to refactor the code a bit and add some tests. I did not delete any existing implementations, only added some codes. I made the 'All Notes' to be the FolderEntity.

https://github.com/laurent22/joplin/assets/32552798/264a55e5-47c0-438d-8d10-ef559a773bc0

**Comment by laurent22** [comment]
> Hi, I have some updates! I managed to solve the issue. I have to refactor the code a bit and add some tests. I did not delete any existing implementations, only added some codes. I made the 'All Notes' to be the FolderEntity.

Thanks Hahabill, it seems to work as expected
