### ISSUE TITLE
When printing sync target info to the log, filter the data

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9985]
Currently during sync, the full sync info is printed to the log. It contains a lot of unnecessary information and should be filtered out:

- `masterKeys_`: The `content` and `checksum` properties should be removed
- `ppk_.value.privateKey`: The first 20 characters and last 20 characters should be kept, and the rest removed (replaced by "...")
- `ppk_.value.publicKey`Keep the first 40 characters

**Comment by Baalekshan** [comment]
Can I take this ?

**Comment by Sanket-0510** [comment]
I understood the issue, but I am not able to find where have we defined sync Info schema, also when you are talking about the log where are you pointing exactly?

**Comment by Nainish-Rai** [comment]
ppk_.value.privateKey: The first 20 characters and last 20 characters should be kept, and the rest removed (replaced by "...")
ppk_.value.privateKeyKeep the first 40 characters  

I am having confusion do you want to keep first 40 characters or the first point??

**Comment by Gurpreetk9** [comment]
ppk_.value.privateKey: The first 20 characters and last 20 characters should be kept, and the rest removed (replaced by "...")
ppk_.value.privateKey:Keep the first 40 characters

I think one of them shoul be ppk_.value.publicKey
